### ISSUE TITLE
Convert scale to map zoom

### ISSUE THREAD

**Issue by ecarrillo01** [mapbox/mapbox-gl-js#10005]
I have an input where the user can enter a scale value in meters/feet and when the user clicks enter the map should zoom to that scale, the problem im having is that mapbox zoom valid values are from 0 to 22, i neet to convert the meters/feet to mapbox zoom, but i dont have idea how it cound be achieved

**Comment by mourner** [comment]
We'll need to use some napkin math to try to derive this — let me try!

Earth circumference at the equator is 40,007,000 meters. At a certain latitude, it is `40007000 * Math.cos(lat * Math.PI / 180)`. On zoom 0, the width of the whole world takes 512 pixels on a Mapbox map (size of a zoom 0 tile). When we zoom in, it increases exponentially, doubling with every zoom, so the whole world takes `512 * Math.pow(2, zoom)` pixels. 

From this, we derive: 

```js
metersPerPixel = 40007000 * Math.cos(lat * Math.PI / 180) / (512 * Math.pow(2, zoom))
``` 

Let's try to inverse it to get zoom from `metersPerPixel`:

```js
Math.pow(2, zoom) = 40007000 * Math.cos(lat * Math.PI / 180) / metersPerPixel / 512;
zoom = Math.log2(40007000 * Math.cos(lat * Math.PI / 180) / metersPerPixel / 512);
```

Now let's assume we want the given number of meters to span the width of the map. That means `metersPerPixel = meters / map.getContainer().clientWidth`. So the final formula would be:

```js
zoom = Math.log2(map.getContainer().clientWidth * 40007000 * Math.cos(lat * Math.PI / 180) / meters / 512);
```

I'm not sure if it's fully correct, but you can take it from there — hope this helps!
