### ISSUE TITLE
How can I add a marker image via an SVG image blob?

### ISSUE THREAD

**Issue by asencis** [mapbox/mapbox-gl-js#10001]
**mapbox-gl-js version**:

### Question

Does anyone know the method for adding a marker image to a map via a loaded image that is a URL blob?

Essentially, something like this:

```
      const blob = new Blob([this.markerSVG], {type: 'image/svg+xml'});
      const url = URL.createObjectURL(blob);

      // Add the default marker asset to the rendered map:
      if (!this.map.hasImage('marker')) {
        this.map.loadImage(url, (error, image) => {
          this.map.addImage('marker', image);
        })
      }
```

**Comment by mourner** [comment]
The GL JS image API expects a raster image, so you would need to convert SVG to raster. One way to do that in the browser would be to load the blob as an image, then draw that image onto a 2D canvas, and then get the image data from it. E.g. like so: https://levelup.gitconnected.com/draw-an-svg-to-canvas-and-download-it-as-image-in-javascript-f7f7713cf81f
