### ISSUE TITLE
Add circle-z-order layout property

### ISSUE THREAD

**Issue by scottsfarley93** [mapbox/mapbox-gl-js#10012]
## Motivation

I have a circle layer with a property called `score`. This circle layer is very dense and many of the feature have similar values for score. However, there are some outliers. I have used `circle-color` to paint points based on their score (linear interpolation). However, the outliers are often "buried" underneath other features, making it hard to identify them. For this use case, it is important that I see all the points (and not bin them, heatmap them, or cluster them). 

I'd like to see a `circle-z-order` property that's analogous to [`symbol-z-order`](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-symbol-z-order) but for circle layers. 

## Design Alternatives

Many clients with a similar use case are likely to want to change their visualization strategy to use clusters or heatmaps. However, I do not want to do this. 

## Design

The new layer layout property should behave the same way the symbol-z-order property behaves, but operate on circle layers instead of symbol layers. 

### Mock-Up

This will look the same as symbol-z-order implementations. 

### Implementation

I'm not sure.

**Comment by mourner** [comment]
While `symbol-z-order` controls the algorithm by which the features are sorted automatically, it seems what you're looking for is a way to sort rendering order of circles based on a property (`score`)? Have you tried using `circle-sort-key` for this? https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-circle-circle-sort-key

**Comment by scottsfarley93** [comment]
@mourner thanks for the suggestion -- this works like a charm! 

We're all set here.
