### ISSUE TITLE
Support for rectangular tilesets

### ISSUE THREAD

**Issue by Seairth** [mapbox/mapbox-gl-js#10010]
I have a raster tileset that is rectangular (the tiles are square).  In other words, at zoom level 4, the tile set is 32 tiles horizontally and 16 tiles vertically.  The `sources` config does not give an option to specify non-square configurations, and I couldn't find a way to specify an alternative tiling for that layer.

Is this at all possible?

If not, what would it take to add a minimal solution?  My thought would be a config option that doubles the x axis, as it seems the most likely alternative to square tiling.  I'm happy to submit a PR, if someone can point out where I should be looking to make the change.

(note: though not necessarily important, I am working with OGC GeoPackages, which can arbitrarily define how many horizontal and vertical tiles there can be at each zoom level.  Fortunately, in my case, it is uniformly a 2:1 ratio, doubling at each zoom level.  So, "y" is the same as the Slippy scheme, but "x" is always twice that.)

**Comment by asheemmamoowala** [comment]
@Seairth It's not clear what is currenlty not working about a raster tileset with rectangular area. The [TileJSON specification](https://github.com/mapbox/tilejson-spec/tree/master/2.2.0) supports a `bounds` attribute that lets clients know what region to request tiles for. When specifying a `source`, you can either include `bounds` in your TileJSON, or as a property in the source configuration.

**Comment by Seairth** [comment]
After a bit more research, I figured out that the GeoPackage tiles are using an equirectangular (Plate Carree) projection, with MapBox GL does not appear to support.  I am closing this issue.
