### ISSUE TITLE
Popup example

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1001]
GL analog of https://www.mapbox.com/mapbox.js/example/v1.0.0/utfgrid-data-popup/ with data from vector tiles.

Possibilities:

* Recreate NPR station map in GL. Needs https://github.com/mapbox/mapbox-gl-js/issues/358 and https://github.com/mapbox/mapbox-gl-style-spec/issues/105
* POIs from Mapbox Streets
* trimet rail stops justin.1c661773 or food carts food carts justin.98007e0e

@peterqliu I just added Popups (https://github.com/mapbox/mapbox-gl-js/commit/2d6b56bd644ffcdaa9e17fbb5282a333dd923567), want to try them out?

**Comment by peterqliu** [comment]
--> https://github.com/mapbox/mapbox-gl-js/pull/1009
