### ISSUE TITLE
What does "Supports interpolate expressions." mean exactly in documentation for circle-translate

### ISSUE THREAD

**Issue by raegen-work** [mapbox/mapbox-gl-js#10016]
**mapbox-gl-js version**: 1.12.0

### Question

What does "Supports interpolate expressions." mean exactly in documentation for **circle-translate**?
![image](https://user-images.githubusercontent.com/61435208/95115707-34362180-0746-11eb-8672-ed4154185ffe.png)

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-circle-circle-translate

**Comment by arindam1993** [comment]
It means that a `zoom` dependent expression can be used to interpolate between various different values of translation. This allows you to smoothly translate a feature as a user zooms in.

This example uses this mechanism to update the color of the buildings.
https://docs.mapbox.com/mapbox-gl-js/example/change-building-color-based-on-zoom-level/
