### ISSUE TITLE
Add a "layers" parameter to "Evented#on" 

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1002]
Map events should accept an optional second parameter which is the name of a layer or an array of layer names for which to delegate events. Internally, this would bind an event handler that uses `featuresAt` and dispatches the event only when it matches features from the given layer(s). The features themselves would be passed as a member of the event object. For example:

``` js
map.on('click', 'poi', function(e) {
    (new Popup())
        .setLatLng(e.features[0].latLng)
        .setHTML(e.features[0].properties.description)
        .addTo(map);
});
```

This should not require setting `interactive: true` for each layer separately; binding a delegated event should automatically enable interactivity for the specified layers.

**Comment by mourner** [comment]
> This should not require setting interactive: true for each layer separately; binding a delegated event should automatically enable interactivity for the specified layers.

This may be tricky, because you need to reparse tiles when `interactive` for a layer changes.

**Comment by lucaswoj** [comment]
We should do this as soon as #2224 lands!

**Comment by arthurhammer** [comment]
Playing with v0.35 and pretty happy about this change. Any plans to support multiple layers to query with `on`?

**Comment by anandthakker** [comment]
Seems like a doable enhancement to me -- @jfirebaugh did you encounter any subtleties in implementing this that would make this problematic?

**Comment by mourner** [comment]
Looks like a one-line change to me since underlying `queryRenderedFeatures` already accepts an array of layer ids.

**Comment by jfirebaugh** [comment]
Yeah, should be straightforward. @arthurhammer can you open a new issue so we don't lose track of the request?

**Comment by arthurhammer** [comment]
Done in #4578. Thanks!
