### ISSUE TITLE
Grouping Circle and Symbol Layers to Avoid Odd Overlapping

### ISSUE THREAD

**Issue by Metzen2k** [mapbox/mapbox-gl-js#10021]
Using 1.12.0 I'm creating numbered circle markers by adding a Circle and Symbol layer for each item:

```
map.addLayer({
	'id': 'marker',
	'type': 'circle',
	'source': 'geojson',
	'minzoom': 0,
	'maxzoom': 24,
	'paint': {
		'circle-radius': 10,
		'circle-color': '#FFFFFF',
		'circle-stroke-color': '#000000',
		'circle-stroke-width': 2,
		'circle-opacity': 1,
	},
	'filter': ['==', '$type', 'Point']
});

map.addLayer({
	'id': 'marker-label',
	'type': 'symbol',
	'source': 'geojson',
	'minzoom': 0,
	'maxzoom': 24,
	'layout': {
		'text-field': [ 'format', ['get', 'name'], { 'font-scale': 0.8, 'text-translate': [0,-20] }	],
		'icon-allow-overlap': true,
		'icon-ignore-placement': true,
		'text-allow-overlap': true,
		'text-optional': false
	},
	'filter': ['==', '$type', 'Point']
});
```

The problem comes in the z-index layering. All of the circles (black stroke, white fill) are on the bottom and the text is on the top. As you zoom in and out you end up with the number for multiple markers on one circle, which is confusing and looks bad.

For a given marker (```#1```,``` #2```, etc) how can I group the Circle and Symbol layers together or change the sort order so that the entire marker for ```#1``` (Circle and Symbol together) are on top of the entire marker for ```#2```?

Or is there a better way to make a numbered circle marker? If it needs to done with an image for the circle and text label I'm fine with that, too.

<img width="89" alt="A" src="https://user-images.githubusercontent.com/342179/95262666-c93e2680-07e9-11eb-99ed-b8e3b536fea1.png">

<img width="76" alt="B" src="https://user-images.githubusercontent.com/342179/95262677-cc391700-07e9-11eb-8db6-ee7aa5785ae9.png">

<img width="72" alt="C" src="https://user-images.githubusercontent.com/342179/95262683-ce9b7100-07e9-11eb-9c3c-aeeaf0dd56bb.png">

Thanks!

**Comment by arindam1993** [comment]
For your usecase I'd recommend using just one symbol layer, with `icon-text-fit`, `icon-image` and using `symbol-sort-key` to define the render order.

Its not possible to interleave z-order between two layers, but you can use `*-sort-key` to define a z-index within the same layer.
