### ISSUE TITLE
RemoveEventListener does not working for click event

### ISSUE THREAD

**Issue by stharmar-hitachi** [mapbox/mapbox-gl-js#10027]
**mapbox-gl-js version**: 1.12.0

### Question
RemoveEventListener doesn't work for click event because of functions are not equal and returns false even I used the same function and I have mentioned the code as below 
**if(s.layer===e&&s.listener===i)**

But it is working for me when I changed the code like below.
**if(s.layer===e&&s.listener.toString()===i.toString())**

Is this correct approach, please clarify on the same 

### Links to related documentation

https://stackoverflow.com/questions/12216540/how-to-test-for-equality-of-functions-in-javascript

**Comment by mourner** [comment]
Listeners are removed by reference, not by source content. You can only remove the same function (by reference) you passed  in `addEventListener`.
