### ISSUE TITLE
closeOnClick behaviour fires before 'click' event

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#10029]
**mapbox-gl-js version**: 1.12.0

**browser**: FF

### Steps to Trigger Behavior

A pretty common way to do popups is code like this:

```js
      const popup = new mapboxgl.Popup();
      map.on("click", "mylayer", (e) => {
        popup.setHTML(e.features[0].properties.name).setLngLat(e.lngLat).addTo(map);
      });
```

### Expected Behavior

Each time user clicks on a feature, a popup appears.

### Actual Behavior

Click behaviour alternates:

1. Show popup
2. Just hides existing popup
3. Show popup ....

This is because the `closeOnClick` behaviour triggers after the `on('click', ...)` behaviour, so the popup is moved and updated, then instantly closes.

Not sure if a bug, or just an inconvenient aspect of the current design.

Interestingly, this behaviour doesn't occur in [this example](https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/), which creates a new popup every time. I had thought that wasn't the recommended approach, but may be wrong.

**Comment by mourner** [comment]
Yeah, I think we should fix this. The way Leaflet handles this is by having a `preclick` event, introduced precisely for the cases like `closeOnClick` where you want something to happen before any other `click` listeners.
