### ISSUE TITLE
icon-anchor ignored when using icon-text-fit

### ISSUE THREAD

**Issue by bob-gray** [mapbox/mapbox-gl-js#10025]
**mapbox-gl-js version**: 1.12.0

**browser**: Chrome 85

### Steps to Trigger Behavior

 1. Add symbol layer where the `icon-image` has `stretchX` and `stretchY`
 2. Set `icon-anchor` to `"bottom"`
 3. Set `icon-text-fit` to `"both"`

### Link to Demonstration

The Mapbox GL JS [stretchable image example](https://docs.mapbox.com/mapbox-gl-js/example/add-image-stretchable/) is a great test. Run this example and add `"icon-anchor": "bottom"` and you'll see the point at the bottom of the icon isn't the anchor.

Having stretch areas of an icon would be more useful if the icon can be anchored instead of the text. I've tried several combinations of text and icon layout properties to get the point at the bottom of the icon to be the anchor and was unsuccessful.

### Expected Behavior

The icon point being the icon anchor.

### Actual Behavior

The icon is anchored by the text resulting in the icon point not being the anchor.

**Comment by asheemmamoowala** [comment]
> Having stretch areas of an icon would be more useful if the icon can be anchored instead of the text. I've tried several combinations of text and icon layout properties to get the point at the bottom of the icon to be the anchor and was unsuccessful.

When using `icon-text-fit`, the icon is fit around the text portion of a symbol, and the icon's position is determined by that of the symbol. The text can be placed relative to a symbol using `text-translate` and `text-offset`.

[Here's an example](https://jsfiddle.net/bhox4j3d/) modified to anchor the tail of the image to the source point. 
![image](https://user-images.githubusercontent.com/11619675/95816559-4418ad00-0cd4-11eb-8789-024b05f16947.png)

Like you said, though, this is tricky and doesn't work for text fields with arbitrary line length.

**Comment by bob-gray** [comment]
@asheemmamoowala Thanks for pointing me to `text-translate`. Using `text-translate`, `icon-translate`, and `text-anchor: 'bottom'`, I was able to set the point of the `icon-image` to be fixed at the symbol's position even when the line length is variable. This seems to work great as long as the pixel distance between the bottom of the image and the bottom of the text is known and constant. This true for my use case.

https://jsfiddle.net/2g6saxjm/

Is there any drawbacks to this approach that you can think of?

**Comment by asheemmamoowala** [comment]
> Is there any drawbacks to this approach that you can think of?

You might want to profile performance of your style with these changes. But I don't see any major issues with this approach.

cc @ansis
