### ISSUE TITLE
Seek Help

### ISSUE THREAD

**Issue by yuanyuan-xy** [mapbox/mapbox-gl-js#10034]
I want to use Mapbox-GL in the LAN, can you tell me what to do or which document I should read, thank you

**Comment by ryanhamley** [comment]
Mapbox GL JS doesn't officially support any offline functionality. This issue tracker is for reporting bugs and requesting new features. For general "how to" questions like this, please contact [Mapbox Support](http://support.mapbox.com/). Thanks.
