### ISSUE TITLE
Patterns computed from zoom-based expressions render with incorrect scale

### ISSUE THREAD

**Issue by rf-** [mapbox/mapbox-gl-js#10033]
It seems like v1.9.1 introduced a bug in the rendering of `fill-pattern` properties computed from zoom-based step expressions with non-literal values. At least that's as far as I've been able to boil down the repro case so far.

PR #9482 seems potentially relevant, although I don't know enough to understand what the connection is.

**mapbox-gl-js version**: v1.9.1 and above

**browser**: Chrome 86.0.4240.75 on macOS 10.15.7

### Steps to Trigger Behavior

1. In the given CodePen, slowly zoom in through a few whole-numbered zoom levels. Note that, once you've gone from the outermost zoom level to the second-outermost, the gray boxes maintain a constant scale relative to the map as you continue zooming in.
 2. Slowly zoom out and note that as soon as you hit a new zoom level, the gray boxes get much larger. As you continue to zoom out all the way, note that they stay this new size at every zoom level.

### Link to Demonstration

* Latest version (bad): https://codepen.io/rf-/pen/yLJYONM
* 1.9.1 (bad): https://codepen.io/rf-/pen/xxOZrOB
* 1.9.0 (good): https://codepen.io/rf-/pen/wvWMeoJ
* Latest version with literal step values instead of `concat` expressions (good): https://codepen.io/rf-/pen/LYZGLGo

### Expected Behavior

The scale of the pattern within a given zoom level doesn't depend on which direction you're zooming when you enter it.

### Actual Behavior

The pattern appears much larger when zooming out than when zooming in.

**Comment by rf-** [comment]
It's also worth noting that, when zooming in and out a bunch on any of these examples (the last one, on the newest Mapbox with literal step values, is probably the most relevant), the texture often renders incorrectly and then fixes itself on the next zoom-level transition.

Example of corrupted rendering:
<img width="966" alt="image" src="https://user-images.githubusercontent.com/345106/96911559-dac43700-1455-11eb-9ac0-97bc60668f5e.png">

Example of correct rendering at the same zoom level:
<img width="989" alt="image" src="https://user-images.githubusercontent.com/345106/96911704-0e06c600-1456-11eb-9587-202f8f7908cc.png">

I don't know whether this is related, but it's characteristic of a bunch of random rendering glitches I've run into when trying to find workarounds to allow us to continue rendering scale-independent textures like this.

**Comment by karimnaaji** [comment]
Fix the main regression issue in #10284 . The visual corruption you described in https://github.com/mapbox/mapbox-gl-js/issues/10033#issuecomment-714664765 is a separate issue, I created a specific ticket for it in https://github.com/mapbox/mapbox-gl-js/issues/10322.
