### ISSUE TITLE
popup.setOffset throws

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#10032]
Calling `setOffset` appears to throw with not a function. Which is curious because there is a [passing unit test for it](https://github.com/mapbox/mapbox-gl-js/blob/f0cc0159819617f59bbb5c3405a13a22f2f5c704/test/unit/ui/popup.test.js#L483-L497). My best guess is that the [space between the function name and parenthesis](https://github.com/mapbox/mapbox-gl-js/blob/f0cc0159819617f59bbb5c3405a13a22f2f5c704/src/ui/popup.js#L459) is throwing off the bundler?

**mapbox-gl-js version**: `v1.12.0`

### Steps to Trigger Behavior

```js
const popup = new mapboxgl.Popup()
popup.setOffset(10); // Throws
```

### Link to Demonstration

Visit https://jsfiddle.net/tristen/792oryg3/2/ and open the dev console.

**Comment by ryanhamley** [comment]
`setOffset` has not yet been included in a GL JS release. If you run this code in a debug page, it works as expected.
