### ISSUE TITLE
Is there a TypeScript definition file for mapbox-gl-style-spec?

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#10044]
I want to use `featureFilter` from `@mapbox/mapbox-gl-style-spec` but i coudnt load a TypeScript definition for this function. Is it some how possible to load a description for all of that style spec? For example is there a `@types` package?

**Comment by ryanhamley** [comment]
GL-JS uses Flow, not Typescript. I don't believe we export any style-spec Flow types. The package does include `types.js` at the root level which contains most of the Flow types that are used in the package, so you may be able to make use of that.
