### ISSUE TITLE
Hide Chrome's new ugly focus styling by adding "outline: none" to ".mapboxgl-canvas"

### ISSUE THREAD

**Issue by blq** [mapbox/mapbox-gl-js#10048]
I think I said it in the subject line :)

**Comment by ryanhamley** [comment]
In general, adding `outline: none` for focused elements is bad UX for accessibility reasons and I don't think that's something we'd ever do. In the future, please fully fill out the issue template when opening a ticket.

**Comment by blq** [comment]
a bit sloppy reported yes, sorry. The black border shows up with Chrome recently but I notice both Leaflet and Google maps etc seems unaffected or fixed it. Maybe can do it with better semantics than 'outline: none' I guess.
