### ISSUE TITLE
reload, scale, and clip tiles for z > source.maxZoom

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1004]
For zoom levels greater than a tile source's max zoom level, load lower zoom level tiles and clip them.

We need this so that
- layout properties are reprocessed at higher zoom levels
- label placement only needs to place labels 1 zoom level deep

**Comment by mourner** [comment]
Capturing discussion with @ansis — I think it should be much easier to modify tile pyramid to replace parent tile on higher zoom levels than implement tile clipping for overzoomed tiles.
