### ISSUE TITLE
Can it support '3D Tiles' format? E.g. cesium

### ISSUE THREAD

**Issue by MrSmallLiu** [mapbox/mapbox-gl-js#10042]
3D Tiles has become an OGC standard。 The format refrence document: 
https://github.com/CesiumGS/3d-tiles
https://www.ogc.org/standards/3DTiles

**Comment by ryanhamley** [comment]
Mapbox GL JS does not support 3D Tiles. All tiled vector and raster data used with GL JS must conform to the [TileJSON specification](https://github.com/mapbox/tilejson-spec).

**Comment by asheemmamoowala** [comment]
> I know Mapbox GL JS does not support 3D Tiles now. Is it possible to support 3D Tiles Format in the future? 

@MrSmallLiu Support for the 3D Tiles spec is not in our roadmap at the moment. Do you have a specific type of data or aspect of 3D Tiles that you would like to see rendered directly by GL-JS? 

There is some support for 3D tiles in this plugin: https://github.com/Geodan/mapbox-3dtiles

**Comment by MrSmallLiu** [comment]
@asheemmamoowala Thanks. I know the plugin.
3D Tiles is now a good OSGB solution . Does mapbox consider add 3D Tiles to roadmap?
