### ISSUE TITLE
Points disappear/shift polygons when zooming <11

### ISSUE THREAD

**Issue by MapZombie** [mapbox/mapbox-gl-js#10059]
**mapbox-gl-js version**: 1.12

**browser**: Chrome

### Steps to Trigger Behavior
 1. Start map at zoom level of < 11
 2. zoom into map slowly starting from zoom level 8 to past 11
 3. Once you hit zoom level 11, all the data points appear

### Link to Demonstration
https://jsfiddle.net/mapzombie/j3Lmt21p/7/

### Expected Behavior
Nearly all areas of this map should have green points visible which vary in density. These should be visible at all zoom levels, not just 11+.  

### Actual Behavior
I have an issue with my large set of points data (about 100,000 of which probably 40,000 should be visible). Certain points inside polygons do not show up when zooming <11, as we zoom in from 8 to 11 we see different points turn on and off. The points are all part of a single tileset layer. 

Zoom <11 
<img width="505" alt="Screen Shot 2020-10-28 at 12 04 03 PM" src="https://user-images.githubusercontent.com/17599236/97477865-cb416400-1915-11eb-979f-e022a6f13a93.png">
Zoom 11+ 
<img width="501" alt="Screen Shot 2020-10-28 at 12 04 13 PM" src="https://user-images.githubusercontent.com/17599236/97477857-c7addd00-1915-11eb-93b4-e1ee71cc8b2e.png">

**Comment by stevage** [comment]
I think what you're seeing here is all about how you prepare your vector tiles, and not related to what front end library (Mapbox GL JS in this case) you're using to display them.

**Comment by mourner** [comment]
Yeah, this is definitely an issue on the data processing side, not GL JS. If you experience this with Mapbox tools such as MTS or when uploading in Studio, please contact Mapbox support.
