### ISSUE TITLE
Possible to keep mulitple popups open at once?

### ISSUE THREAD

**Issue by mattehicks** [mapbox/mapbox-gl-js#10052]
I am a developer working on a number of projects within my company.  I had a request to build the map with the ability to display multiple popups.  I have not found a way to do this. 

Does anybody know if this is possible?
Thanks, love mapboxGL.

**Comment by ryanhamley** [comment]
You can add the popup to the map with `setLngLat()` and it will be open by default. See https://jsbin.com/somofibiva/edit?html,js,output as an example and the [Popup docs](https://docs.mapbox.com/mapbox-gl-js/api/markers/#popup) for more information. Note that this issue tracker is for reporting bugs and requesting features in GL JS. For general "how to" questions like this, please contact [Mapbox Support](https://support.mapbox.com/). Thanks!
