### ISSUE TITLE
maps render without text or symbols (font-related 403 errors)

### ISSUE THREAD

**Issue by theiliad** [mapbox/mapbox-gl-js#10058]
Hi 👋 
I work on the IBM Carbon Design System, and we've recently published 4 Carbon-compliant mapbox themes.

https://www.carbondesignsystem.com/data-visualization/advanced-charts#mapbox
(style URLs can be found here^^)

On these themes we use the IBM Plex Sans fonts, which unfortunately are being tagged as `private` somewhere in your platform where any user using the fonts sees a `403` error in their console when mapbox-gl is requesting the fonts from your servers.

![image](https://user-images.githubusercontent.com/14989804/97472786-9a1a6100-1920-11eb-8afa-fd653ec6d2d0.png)

Reaching out to a couple of people I found this endpoint which seems like it would allow me to change the `visibility` of the font. I've called the endpoint with our token and it's telling me that it's changing the visibility of the font, however users are still getting these errors and maps render without any text.

![image](https://user-images.githubusercontent.com/14989804/97472851-aacad700-1920-11eb-8922-25dde665edc5.png)

![image](https://user-images.githubusercontent.com/14989804/97472871-b3231200-1920-11eb-9156-2054dfa0c406.png)

Please let me know ASAP if this is something we're able to fix.

**Comment by theiliad** [comment]
**Update** I was able to call the endpoint with a bunch of font names and get things into a better state, **however still getting some 403s for fonts that I've successfully made the PATCH call for**

![image](https://user-images.githubusercontent.com/14989804/97475783-0a76b180-1924-11eb-805a-f213cc170109.png)

**Comment by asheemmamoowala** [comment]
@theiliad Thanks for reporting this issue. These styles look great, and we're excited to see them included in your design system. 

This issue tracker is for reporting bugs and feature requests to the GL-JS SDK. I've reported this issue to the internal team that maintains these endpoints. The font requests have a short TTL, so any cached 403 responses on your local browser should resolve in 10-15 minutes. Please [contact support](https://www.mapbox.com/contact/) if you have any further issues with the font access.

**Comment by theiliad** [comment]
Thanks @asheemmamoowala
