### ISSUE TITLE
Any alternative to mapboxMap.getProjection().toScreenLocation(<LatLng>) ?

### ISSUE THREAD

**Issue by jayarjo** [mapbox/mapbox-gl-js#10062]
I wonder if there's any alternative to [mapboxMap.getProjection().toScreenLocation(<LatLng>);](https://docs.mapbox.com/android/maps/overview/events/#convert-from-screen-pixel) from Android SDK in `mapbox-gl-js`?

### Links to related documentation

https://docs.mapbox.com/android/maps/overview/events/#convert-from-screen-pixel

**Comment by rbrundritt** [comment]
For the gl-js version use the "project" function on the map. https://docs.mapbox.com/mapbox-gl-js/api/map/#map#project

The reverse is "unproject" https://docs.mapbox.com/mapbox-gl-js/api/map/#map#unproject

**Comment by Twist96** [comment]
Is this unproject function from GL-JS option available for iOS?
