### ISSUE TITLE
featuresAt with GeoJSON source containing a linestring only hits on coordinates

### ISSUE THREAD

**Issue by StevenLooman** [mapbox/mapbox-gl-js#1006]
See this [JSFiddle](http://jsfiddle.net/ssLf2rqs/2/) Hover on the coordinates of the line, and you'll see a hit. Hover on a segment between two coordinates, and no hit is reorted.

**Comment by mourner** [comment]
Yep, confirmed.

**Comment by lbud** [comment]
Actually, I'm seeing this in regular vector tile sources as well — you can see this in https://www.mapbox.com/mapbox-gl-js/example/featuresat/

**Comment by jfirebaugh** [comment]
Fixed.

**Comment by StevenLooman** [comment]
Thank you!
