### ISSUE TITLE
Calculate Accurate meter/pixel

### ISSUE THREAD

**Issue by Aiamjay** [mapbox/mapbox-gl-js#10066]
**mapbox-gl-js version**:

### Question
From you documentation, https://docs.mapbox.com/help/glossary/zoom-level/. I can refer to different meter/pixel at different zoom-level. Here is my question, can I get the accurate meter/pixel at a specific latitude and zoom-22, suppose 31.99791317674392? 
It's a critical issued in my project, because we need very precise meter/pixel.

**Comment by sgolbabaei** [comment]
Thank you for using mapbox-gl-js. For future "how do I" questions like this, please refer to our [help documentation](https://docs.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to [https://stackoverflow.com/questions/tagged/mapbox-gl-js](https://stackoverflow.com/questions/tagged/mapbox-gl-js) to ask the community for help.

**Comment by Aiamjay** [comment]
I totally cannot agree with your altitude toward your users. I've almost read all related document regarding meter/pixel in your websites. I find nothing. And I ALSO CONNECT WITH YOUR TECHNICAL SUPPORT, no responds.

**Comment by Aiamjay** [comment]
Please do not clone my issue hasty. I AM your customer, I need your help. You CANNT close my issue ticket so hasty.

**Comment by Aiamjay** [comment]
I spend hundreds of dollars buying your service. And you cannot do that, I need some help, this issue blocked my development for weeks.

**Comment by Aiamjay** [comment]
> Thank you for using mapbox-gl-js. For future "how do I" questions like this, please refer to our [help documentation](https://docs.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.
> 
> You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.

I totally cannot agree with your altitude toward your users. I’ve almost read all related document regarding meter/pixel in your websites. I find nothing. And I ALSO CONNECT WITH YOUR TECHNICAL SUPPORT, no responds.

Please do not clone my issue hasty. I AM your customer, I need your help. You CANNT close my issue ticket so hasty.

I spend hundreds of dollars buying your service. And you cannot do that, I need some help, this issue blocked my development for weeks.

**Comment by asheemmamoowala** [comment]
> I totally cannot agree with your altitude toward your users. I’ve almost read all related document regarding meter/pixel in your websites. I find nothing.

@Aiamjay the question you have asked here has been asked by you before and answered: https://github.com/mapbox/mapbox-gl-js/issues/9893 and https://github.com/mapbox/mapbox-gl-js/issues/9880.

For future reports in this issue tracker of an open source project, please refer to the [contributor covenant code of conduct](https://www.contributor-covenant.org/version/2/0/code_of_conduct/), adopted for this project.
