### ISSUE TITLE
How to add a class name and id to geojson data?

### ISSUE THREAD

**Issue by ats1999** [mapbox/mapbox-gl-js#10070]
## How to add a class name and id to geojson data?

I want to add some animation to geojson data.
Eg. Change color of line on mouse hover. 
 
So, i want to add class name in geojson data.
I am using React.

**Comment by sgolbabaei** [comment]
Thank you for using mapbox-gl-js. You can use `setFeatureState` to set the state of a feature. For more information you can refer to [SetFeatureState document](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#setfeaturestate) and also [create hover effect example](https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/).

For future "how do I" questions like this, please refer to our [help documentation](https://docs.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. You might also consider posting your question to [https://stackoverflow.com/questions/tagged/mapbox-gl-js](https://stackoverflow.com/questions/tagged/mapbox-gl-js) to ask the community for help.
