### ISSUE TITLE
setting maxBounds on Map constructor creates a bug on Map panning

### ISSUE THREAD

**Issue by zotijs** [mapbox/mapbox-gl-js#10084]
**mapbox-gl-js version**: v1.12.0/

**browser**: Chrome Version 86.0.4240.183 

### Steps to Trigger Behavior

 1. Change [render world copies example](https://docs.mapbox.com/mapbox-gl-js/example/render-world-copies/) adding maxBounds
 2. pan map (drag move)

### Link to Demonstration

https://codepen.io/zotijs/pen/GRqwJRd

### Expected Behavior
Keep the canvas to its initial position

### Actual Behavior
Moves the canvas down

**Comment by mourner** [comment]
It moves down because the bounding box value is incorrect — you set `[-180, 90]` as the south-west point of the bounding box, while this is the north pole. Flipping the latitude sign in the value fixes this.
