### ISSUE TITLE
Cannot avoid caching tiles and imagery data into mapbox-tiles cache storage?

### ISSUE THREAD

**Issue by nmahser** [mapbox/mapbox-gl-js#10080]
**mapbox-gl-js version**:

### Question
I cannot avoid caching tiles and satellite imagery into mapbox-tiles cache storage. I also couldn't find any info regarding management of mapbox-tiles cache storage, other than deleting it with mapboxgl.clearStorage();

**Comment by mourner** [comment]
Yes, unfortunately there's no way to manually control the use of the cache storage because its use is essential for GL JS performance. We can't rely on browser's cache because URLs for the same Mapbox resources change between user sessions. Can you say more about your use case and why you need to disable the cache?

**Comment by nmahser** [comment]
Hi @mourner, I'm trying to implement offline use capability to my mapbox application. I need to create my own cache storage for map tiles with service worker where I have full control of caching strategies and expiration time.

Additionally, even if I don't try to create my own cache storage. When I go offline and refresh the page, the cached satellite images (I can see them in the mapbox-tiles storage) don't get retrieved from mapbox-tiles storage, so the satellite images don't show up.

Please let me know if you any other info that I can provide.

**Comment by asheemmamoowala** [comment]
@nmahser, as was previously stated:

> there's no way to manually control the use of the cache storage because its use is essential for GL JS performance

`mapboxgl.clearStorage()` should work for you to clear the cache and handle your own cache using a service worker.
