### ISSUE TITLE
Draw line

### ISSUE THREAD

**Issue by SephReed** [mapbox/mapbox-gl-js#10088]
## Motivation
I want to draw a line

## Design
Create the ability to draw lines without using geojson sources and layers to do it.

### Mock-Up
```
const line = new PolyLine({ points: [ {lat: 0, lng: 0}, {lat: 1, lng: 1}]});
line.addTo(map);

line.remove();
```

### Concepts
You don't have to teach anything with a design like this because it's immediately obvious what is going on.

### Implementation
This is really easy to implement, most of the code already exists.  The hard part right now is that (AFAICT) you have to create a geojson source then add a layer for every single line drawn.  It really makes me think I'm doing something wrong because it's such a vastly overcomplicated workflow.

**Comment by ryanhamley** [comment]
The entire architecture of GL JS is based around GeoJSON sources which are visualized using layers. Something like this would be a fundamental re-write of the codebase. Furthermore, the style-spec that defines the layer and source types available in GL JS is designed in such a way that it can be used across the Mapbox ecosystem, including in GL Native. The style-spec provides a declarative way for visualizing maps and is backwards-compatible.

One way that something like what you've outlined could be achieved is to create a plugin or wrapper library for GL JS that creates an interface that adds the source and layer behind the scenes and abstracts away some of the complexity (in fact, there are many libraries such as [React Mapbox GL](https://github.com/alex3165/react-mapbox-gl) that do something similar to this approach). But this is not something we'd add in the library itself.
