### ISSUE TITLE
Bug with controls

### ISSUE THREAD

**Issue by CharlesOnAir** [mapbox/mapbox-gl-js#10081]
Hello,

I have a problem with the Mapbox controls. My geolocate icon is white.

Do you have a solution ?

Thank you !

<img width="118" alt="Capture d’écran 2020-11-09 à 12 10 52" src="https://user-images.githubusercontent.com/16211129/98534358-a1c4f880-2284-11eb-904d-1cd85c851c44.png">

**Comment by mourner** [comment]
There's no way to diagnose an issue like this with a screenshot alone and no details. Please submit a live page where this is reproducible, e.g. with a JSFiddle.

**Comment by CharlesOnAir** [comment]
https://jsfiddle.net/charlessauvat/kuj073La/

**Comment by mourner** [comment]
@CharlesOnAir this is not a reproducible case, since the page does not work.

**Comment by CharlesOnAir** [comment]
To make it easier, can you give me the name of the geolocation button?
So that I can edit the SVG?

**Comment by CharlesOnAir** [comment]
Problem solved, I had imported the wrong library version
`<script src='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css' rel='stylesheet' />`
