### ISSUE TITLE
querySourceFeatures w/ 'within' filter returns no results

### ISSUE THREAD

**Issue by Delerme** [mapbox/mapbox-gl-js#10087]
**mapbox-gl-js version**: 1.12.0

**browser**: Firefox

### Steps to Trigger Behavior

 1. Using a tileset source, use querySourceFeatures with a 'within' polygon filter

### Link to Demonstration

https://jsfiddle.net/9Lmwptou/36/

The two buttons run the same query on the airport labels source, with and without the 'within' filter. Without the filter, airports are returned fine. With the filter, no airports are returned. The filter is a rectangular polygon surrounding LGA, as validated with geojson.io

### Expected Behavior

LGA is returned

### Actual Behavior

No features are returned

**Comment by zmiao** [comment]
@Delerme this issue should have been resolved by https://github.com/mapbox/mapbox-gl-js/pull/9933

**Comment by ryanhamley** [comment]
Yep, this has been resolved since the last release of GL JS. We're planning a v1.13 release sometime in the near future so keep an eye out. In the meantime, if you must have this fix, you can pull directly from the `main` branch.

**Comment by Delerme** [comment]
Perfect, thanks!
