### ISSUE TITLE
Tileset data (point data) partially disappearing/appearing at different zoom levels

### ISSUE THREAD

**Issue by ShihWen** [mapbox/mapbox-gl-js#10099]
**mapbox-gl-js version**: v1.12.0

**browser**: chrome

### Steps to Trigger Behavior

 1. Generate tileset with tippecanoe
 2. Add layer with map.addLayer
 3. When zoom level crossing from 12 to 13, the point pattern changes, some disappear and some appear.

image illustrate the area where point features disappear/appear while zooming:
![mapbox_issuedExample](https://user-images.githubusercontent.com/26899058/99046330-8d0e9a80-25cd-11eb-887f-f37489ec640a.PNG)

### Link to Demonstration

https://jsbin.com/darohuy/edit?console,output

### Expected Behavior
Showing all feature points at all zoom level (in this case 11~14)

### Actual Behavior

The number of feature point is different while zoom level crossing from integer to integer (ex. 12 to 13)

**Comment by mourner** [comment]
This is the default behavior of Tippecanoe, per [the docs](https://github.com/mapbox/tippecanoe#options):

> Tippecanoe will normally drop a fraction of point features at zooms below the maxzoom, to keep the low-zoom tiles from getting too big. If you have a smaller data set where all the points would fit without dropping any of them, use -r1 to keep them all. If you do want point dropping, but you still want the tiles to be denser than -zg thinks they should be, use -B to set a basezoom lower than the maxzoom.

GL JS renders tiles the way they come, and points appear to be filtered at the data level.
