### ISSUE TITLE
Is it possible to add height to a marker point

### ISSUE THREAD

**Issue by John2397** [mapbox/mapbox-gl-js#10092]
I would like to display marker points in 3-d space but adding the height along with lat long does not work.

Is there any workaround?

**Comment by mourner** [comment]
Currently there's no easy way to do this, and it's ticketed as #9945. There's a complicated workaround described in #9814 which might suit your purpose.

**Comment by spencerthayer** [comment]
Has there been any progress getting markers, points, or any object to render with a z-offset or altitude?
