### ISSUE TITLE
featuresAt should return GeoJSON

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1010]
Specifically, a FeatureCollection.

This is the natural format for "a collection of features, including properties and geometry", which is what featuresAt wants to return.

Related: https://github.com/mapbox/mapbox-gl-js/issues/723.

**Comment by peterqliu** [comment]
+1

would obviate having to [stuff latlng into `feature.properties`](https://github.com/mapbox/mapbox-gl-js/pull/1009/files#diff-87445e61148291d6f3e9ab31f79caea4R83)

**Comment by jfirebaugh** [comment]
⇢ #1027
