### ISSUE TITLE
document that setFeatureState needs numeric ids

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#10105]
#9559 changed the documentation for `setFeatureState` which previously read

> Features are identified by their `id` attribute, which must be an integer or a string that can be cast to an integer.

That part was removed, however it appears that string `id`'s don't work when using `setFeatureState`.

I couldn't find an existing ticket, so short of implementing this so that string id's work, we could better document this limitation.

**Comment by geirmarius** [comment]
Hey, we're using string IDs without issues in `setFeatureState`. We're targeting the `promoteId` which points to a string value in our geojson.

Just wanted to let you know.

**Comment by andrewharvey** [comment]
Strange I put together a minimal example https://jsfiddle.net/andrewharvey4/1oLj6u8t/3/ and it's not working with string ids.

**Comment by geirmarius** [comment]
Aha, that makes ... sense. Ids in mapbox cannot be numbers, but you can use promoteId to "promote" another property to use in setFeatureState, and that one can be a string: https://jsfiddle.net/g1wL8q7n/

Not very well documented tho, and I spend hours trying to figure out how to. 😅

**Comment by douglasg14b** [comment]
Seriously, I just wasted 1/2 a day trying to figure out why `setFeatureState ` wasn't working. Then I found this issue https://github.com/mapbox/mapbox-gl-js/issues/7986 that states that is accepts strings that can be coerced into numbers. Except that I'm using hexadecimal strings that are numbers just in base 16...

Please fix the document, this was absolutely exhausting.

**Comment by asheemmamoowala** [comment]
Thanks for the feedback here, I have a small improvement in https://github.com/mapbox/mapbox-gl-js/pull/10356
