### ISSUE TITLE
Calling setCoordinates on a video source causes the video to momentarily disappear or flicker

### ISSUE THREAD

**Issue by neodescis** [mapbox/mapbox-gl-js#10113]
**mapbox-gl-js version**: 1.12.0

**browser**: Google Chrome v86

### Steps to Trigger Behavior

 1. Add a video source and layer to the map
 2. Call setCoordinates on the source
 3. See video temporarily disappear and come back

### Link to Demonstration

https://jsfiddle.net/jx5t4nu9/

### Expected Behavior
Video's location on the map is updated fluidly.

### Actual Behavior
Video's location on the map is updated, but the video disappears momentarily.

**Comment by neodescis** [comment]
It appears this is fixed with the version 2.0 render improvements. Alternatively, there is a workaround for 1.x: set raster-fade-duration to zero on the layer's paint options.

**Comment by ansis** [comment]
Thanks for reporting back with the confirmation and workaround!
