### ISSUE TITLE
Raster source loads tiles for different zoom levels

### ISSUE THREAD

**Issue by aczerwoniec** [mapbox/mapbox-gl-js#10116]
**mapbox-gl-js version**: 1.12.0

### Question
We've came across a problem where mapbox seems to request raster tiles for a lower zoom level that the current one (the replaced bbox at {bbox-epsg-3857} is twice as large as usual) and as a result we're receiving some glitches, e.g.:
![image](https://user-images.githubusercontent.com/13660277/99528132-1ba06480-299e-11eb-8712-d7c0384cf5d0.png)

We've seen that there is a lot of logic behind that tile loading and we've tried setting both SourceCache.maxOverzooming and SourceCache.minOverzooming to 0 but then some of the tiles were not loaded at all :) 

![image](https://user-images.githubusercontent.com/13660277/99528458-9a959d00-299e-11eb-8890-6bde43315db1.png)

The issue is totally random (it's sometimes correct and sometimes not for the same tile) and happens at application startup as well so it's not related to caching (the WMS requests are not cached either).

Could you please provide us with some explanation of this behaviour? 

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#raster

**Comment by mourner** [comment]
Can you provide a minimal live test case (e.g. with JSFiddle) where this is reproducible? It might be a problem with the raster data source. Tile loading logic should not load parent tiles unless it was already loaded (e.g. before zooming in) and then the new ideal tile failed to load or is taking too long.

**Comment by aczerwoniec** [comment]
You've just gave me an answer I think :) 

The issue was connected to the raster data source, it sometimes returned wrong image format and when mapbox was unable to parse the ideal tile it tried loading a tile for a lower zoom (at least I think so :) ) so it caused the error, after fixing it on the source everything is correct.

Thank you very much for quick response!
