### ISSUE TITLE
use turf for hit testing in feature_tree.js

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1011]
At least [this code](https://github.com/mapbox/mapbox-gl-js/blob/d4203769183141a98d510117efac90aaae506394/js/data/feature_tree.js#L68-L127), and possibly all of feature_tree.js, should be replaced with modules / a module from turf.

cc @morganherlocker

**Comment by mourner** [comment]
:+1: 

> possibly all of feature_tree.js

Yeah, we would need rbush-based GeoJSON indexing module for this, which is on the Turf roadmap.

**Comment by jfirebaugh** [comment]
Ref: https://github.com/Turfjs/turf/issues/173

**Comment by mourner** [comment]
I think it's easier to leave indexing on the app side for now because it's super simple.

**Comment by jfirebaugh** [comment]
`turf.inside(point, turf.buffer(feature))` is the obvious way to do this currently, but that pulls in JSTS which we definitely don't want in gl-js.

**Comment by mourner** [comment]
@jfirebaugh creating a buffer is unnecessarily expensive here... Is there an equivalent to `distance(point, feature`?

**Comment by morganherlocker** [comment]
@jfirebaugh I would only pull in turf modules on a case by case basis for something like this. [turf-inside](https://github.com/Turfjs/turf-inside) does not depend on JSTS.

**Comment by mourner** [comment]
@morganherlocker turf-buffer still does. 

@jfirebaugh I think it's fine to keep the code. It's not generic so it'll probably be 10-20x smaller than what you'd pull from Turf selectively.

**Comment by jfirebaugh** [comment]
> distance(point, feature)

Yeah, this was what I was looking for initially. Currently [turf.distance](http://turfjs.org/static/docs/module-turf_distance.html) is point-to-point only, and it's not clear whether it would be desirable to generalize it to point-to-closest-point-on-feature.

**Comment by jfirebaugh** [comment]
Closing; not feasibly currently.
