### ISSUE TITLE
Why mapboxgl delete the function 'getCameraPosition'

### ISSUE THREAD

**Issue by FreeGIS** [mapbox/mapbox-gl-js#10115]
**mapbox-gl-js version 1.12.0:

### Question
I found the function 'getCameraPosition' in 'src/geo/transform.js' two years ago,but now it was deleted。

### Links to related documentation
https://github.com/mapbox/mapbox-gl-js/pull/6093

**Comment by ryanhamley** [comment]
#6093 was never merged so this function was never part of the library and was thus never removed from the library. The PR went stale and was closed pending further development, but the changes in that PR will likely be unnecessary given upcoming changes to the library, so there's no plan to revisit this PR.

**Comment by FreeGIS** [comment]
> was never merged so this function was never part of the library and was thus never removed from the library. The PR went stale and was closed pending further development, but the changes in that PR will likely be unnecessary given upcoming changes to the library, so there's no plan to revisit this PR.

Thanks，but i think the function  'getCameraPosition' is very useful when someone to develop 3d scenes to keep perspective consistent。
