### ISSUE TITLE
missing large chunks of data at certain zoom levels

### ISSUE THREAD

**Issue by briantran37** [mapbox/mapbox-gl-js#10110]
i am missing large chunks of data at certain zoom levels- it wont display data at zoom levels less than 6 - when trying to project mbtile layers.... i dont suspect it being data issue....could it be a maputnik/maptiler loading issue?
have you any idea how to diagnose/ resolve this issue?

![image](https://user-images.githubusercontent.com/72456221/99342987-0969dd80-285b-11eb-83e6-206b1497dc27.png)
zoom level less than 6 with large chunks of data missing

**Comment by mourner** [comment]
> have you any idea how to diagnose/ resolve this issue?

Filling the proposed issue template would help, including a live reproducible test case. We have no way of addressing issues like this without it.
