### ISSUE TITLE
Cannot load image from local folder or url

### ISSUE THREAD

**Issue by acebelowzero** [mapbox/mapbox-gl-js#10129]
**mapbox-gl-js version**: 1.13.0

### Question
I am trying to load and image to see my data but while doing I saw I get the error belowe
`mapbox-gl.js?e192:31 Uncaught (in promise) Error: Could not load image because of The source image could not be decoded.. Please make sure to use a supported image type such as PNG or JPEG. Note that SVGs are not supported`
I was following the tutorial below I am trying to replicate it but instead of the data being static it will be constantly changing.

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#symbol

Here is my code and how I am loading it.

```
map.on("load", async function () {
      const response = await axios.get(env.process.url);
      const aircrafts = response.data;
      for (let air in aircrafts) {
        var list = {
          type: "Feature",
          geometry: {
            type: "Point",
            coordinates: [
              aircrafts[air].coordinates[0],
              aircrafts[air].coordinates[1],
            ],
          },
          properties: {
            planeId: aircrafts[air].planeId,
          },
        };
      }
      let plane = require("@/assets/VRStumb.jpg");
      map.loadImage("@/assets/VRStumb.jpg", function (error, image) {
        if (error) throw error;
        map.addImage("plane", image, { sdf: true });
        map.addLayer({
          id: "points",
          type: "symbol",
          source: {
            type: "geojson",
            data: {
              type: "FeatureCollection",
              features: list,
            },
          },
          layout: {
            "icon-image": "plane",
            "icon-size": 1.5,
            "text-field": "planeID",
            "text-font": ["Open Sans Semibold", "Arial Unicode MS Bold"],
            "text-offset": [0, 0.9],
            "text-anchor": "top",
          },
        });
      });
    });
```

**Comment by John2397** [comment]
[Solution posted here](https://github.com/videojs/http-streaming/issues/1009)

Please close the issue.

**Comment by asheemmamoowala** [comment]
`Map#loadImage` does not support relative url paths. It looks like you are using special path identifiers, in which case you can provide a `transformRequest` option into the Map constructor to modify the path at runtime as in this example: https://docs.mapbox.com/mapbox-gl-js/api/properties/#requestparameters
