### ISSUE TITLE
Is there anything while using fill-extrusion in mapbox-gl-js

### ISSUE THREAD

**Issue by ats1999** [mapbox/mapbox-gl-js#10126]
I am trying to create a polygon in `mapbox-gl-js` using ***react***. I am using `react-map-gl` as a wrapper for react of mapbox-gl-js.

I have taken example from here https://docs.mapbox.com/mapbox-gl-js/example/3d-extrusion-floorplan/
and everything is live  on https://codesandbox.io/s/hopeful-wind-l0mtw?file=/src/App.js 

I am using `react-map-gl` as a wrapper for react.

**Comment by mourner** [comment]
It's not clear what your issue is since you haven't filled the prompted issue template, so unfortunately I have to close this. If you're having issues with `react-map-gl`, please submit them in their repo.
