### ISSUE TITLE
The display is shifted away from the map centre compared to an OpenLayers map canvas

### ISSUE THREAD

**Issue by dbauszus-glx** [mapbox/mapbox-gl-js#10133]
v1.12.0

observed on Chrome 86.0.4240.111 and others

I put this on stackoverflow but had this closed quickly by an eager moderator.

[https://gis.stackexchange.com/questions/379976/epsg3857-shift-between-mapbox-gl-and-openlayers](https://gis.stackexchange.com/questions/379976/epsg3857-shift-between-mapbox-gl-and-openlayers)

I follow this [example](https://openlayers.org/en/latest/examples/mapbox-layer.html) to put a Mapbox-gl-js map on top of an OL map. The initial view seems good. However, when I move the map however it looks like as if the Mapbox map is stretched and shifted away from the center.

![image](https://user-images.githubusercontent.com/22201617/100133614-e654b480-2e7e-11eb-810a-da55a752edf2.png)

It looks like some pseudo 3d style.

**Comment by asheemmamoowala** [comment]
@dbauszus-glx This issue seems specific to the `mapbox-layer` plugin to OpenLayers, and might be best reported to that project. If you believe that this is a bug in Mapbox-GL-JS specifically, can you please provide a minimal, complete, verifiable demonstration of the issue. We recommend using https://jsbin.com.

**Comment by dbauszus-glx** [comment]
Thanks. I will do this. You are probably right. This might be an OL issue. I wasn't so sure in the beginning and reported on both ends. I'll update here anyways if I get response from the OL team or find the issue myself.

**Comment by dbauszus-glx** [comment]
When I set a breakpoint at the point of creating the mapboxgl.Map I record that the node which I pass as container has a clientWidth of x, for example 674px.

```
new mapboxgl.Map({
          container: _xyz.mapview.node
})
```

But the width of the resulting canvas is always 15 pixel less.

```
<canvas class="mapboxgl-canvas" tabindex="0" aria-label="Map" width="659" height="981" style="width: 659px; height: 981px; position: absolute; display: block;"></canvas>
```

I can fix this by resizing the container which will resize the mapbox canvas accordingly.

**Comment by dbauszus-glx** [comment]
The stretch and shift is caused by a css rule which sets the min-width to 100%. The problem remains though. The mapbox-gl canvas seems to be 15px thinner than the OL container.

![image](https://user-images.githubusercontent.com/22201617/100149667-73efce80-2e96-11eb-989a-06d3ad3fd5d6.png)

**Comment by dbauszus-glx** [comment]
I only could fix this by calling a delayed resize of the mapboxgl.Map instance.

```
if (!mbMap.resized) {
  mbMap.resized = true
  window.setTimeout(()=>mbMap.resize(), 500)
}
```
