### ISSUE TITLE
Mapbox-GL-JS + Static Maps (google maps)

### ISSUE THREAD

**Issue by DerecksonS** [mapbox/mapbox-gl-js#10137]
Hello! Thanks for open source contributing :) 

**mapbox-gl-js version**:
Lastest.

### Question
I need to configure Mapbox-gl-js with HERE or Google maps, however, i was unable to integrate with Google maps tile layers.
How do I configure Mapbox-GL-JS with Static Maps (layers of google maps).

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/example/map-tiles/

Thank you, 
Best regards

**Comment by mourner** [comment]
As far as I know, Google Terms of Use forbid displaying their map data on a non-Google interactive map, so this is unfortunately not possible.
