### ISSUE TITLE
Zooming in on map breaks isochrone

### ISSUE THREAD

**Issue by iamwillow** [mapbox/mapbox-gl-js#10134]
### Version:
"mapbox-gl": "^1.12.0"

### Bug:
When zooming in, the isochrone map UI breaks.  It looks like the  outline is still intact, but  the fill gets distorted.

### Zoomed out:
<img width="474" alt="Screen Shot 2020-11-24 at 09 10 29" src="https://user-images.githubusercontent.com/3923914/100105162-0bbcd080-2e35-11eb-917d-8be65906a087.png">

### Zoomed in:
<img width="628" alt="Screen Shot 2020-11-24 at 09 10 38" src="https://user-images.githubusercontent.com/3923914/100105198-137c7500-2e35-11eb-9c98-0e3daf45e4a8.png">

I circled the isochrone outline in red to show that it is still loading properly. Only the fill is broken.

### Isochrone Code: 
const fetchIsochrone = `https://api.mapbox.com/isochrone/v1/mapbox/${mapInfo.commuteType}/${dataLon},${dataLat}.json?contours_minutes=${mapInfo.commuteTime}&access_token=${MAPBOX_TOKEN}`;

Here is a copy of the isochrone data that gets returned with that API call:
[isochrone_data.txt](https://github.com/mapbox/mapbox.js/files/5590435/isochrone_data.txt)

```
map.on("load", function () {
    map.addSource("iso", {
        type: "geojson",
        data: fetchIsochrone,
    });
    map.addLayer({
        id: "isoLayer",
        type: "fill",
        source: "iso",
        layout: {},
        paint: {
            "fill-color": "#2557a7",
            "fill-opacity": 0.3,
        },
    }, "poi-label" ); 
});

**Comment by iamwillow** [comment]
I found the issue for this.  `&polygons=true` is required in the API call.  

Before:
https://api.mapbox.com/isochrone/v1/mapbox/${mapInfo.commuteType}/${dataLon},${dataLat}.json?contours_minutes=${mapInfo.commuteTime}&access_token=${MAPBOX_TOKEN};

After:
https://api.mapbox.com/isochrone/v1/mapbox/${mapInfo.commuteType}/${dataLon},${dataLat}.json?contours_minutes=${mapInfo.commuteTime}&polygons=true&access_token=${MAPBOX_TOKEN};

**Comment by mourner** [comment]
@iamwillow so, `&polygons=true` solves the issue for you and it can be closed, right?

**Comment by iamwillow** [comment]
Yes, thanks. Closing.
