### ISSUE TITLE
bboxify boxes sometimes have NaN x and y values

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1014]
Sometimes the x and y values for boxes are NaN. We are currently skipping them here https://github.com/mapbox/mapbox-gl-js/blob/0d7badd14f16366f461a134e6484cc292f28e3d4/js/placement/placement.js#L44

They should never be NaN.

**Comment by kapadia** [comment]
@ansis This is now fixed. The NaNs were produced when walking along a vertical segment of the polyline. The next step along the polyline requires computing the slope of the segment. In the case of a vert segment, the slope is Inf.

Fix is at: https://github.com/mapbox/bboxify-labels/blob/1a1904f61b7bb4a7f8d329115bd5deb9d3d3f7e4/index.js#L43-L44
