### ISSUE TITLE
Displaying incorrect data when returning from the background in ios

### ISSUE THREAD

**Issue by peiwal** [mapbox/mapbox-gl-js#10146]
After upgrading to version 6.3.0, we noticed the following strange behavior. At some point in time, the map saves its state and shows it for some time after returning from background mode. Then it shows the current state. What is the reason for this? The sample code fully corresponds to the basic example from the documentation. This error is also present in version 6.2.0.

**Comment by ryanhamley** [comment]
I believe you're looking for https://github.com/mapbox/mapbox-gl-native This is the repo for the web version of GL JS
