### ISSUE TITLE
getSource().setData() is not a function

### ISSUE THREAD

**Issue by songololo** [mapbox/mapbox-gl-js#10141]
**mapbox-gl-js version**: 1.13.0

### Question
Why does `getSource('my-source').setData(<geojson>)` return `Uncaught TypeError: context.state.mapInstance.getSource(...).setData is not a function`

The source in question is a URL vector source, e.g.

```js
my-source: {
    type: 'vector',
    url: 'https://my-source-url,
},
```

I am trying to override the `maxzoom` parameter. Am I correct in assuming that this is then not possible on a URL vector source?

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/api/sources/#geojsonsource#setdata

**Comment by ryanhamley** [comment]
Do you have a working example of the bug? It's hard to say without seeing the issue. My initial guess is the source may not have finished loading. Have you tried calling `setData` inside a `map.on('load')` callback?

**Comment by songololo** [comment]
Yes, I'm using it from a `load` event.

**Comment by ryanhamley** [comment]
Can you reproduce the example using a site like JSFiddle? We can't diagnose any issue otherwise.

**Comment by ansis** [comment]
`.setData(...)` only exists for geojson sources. You need to first create a source with `type: "geojson"`. Vector tile sources cannot be updated from this library.

These examples may be helpful:
https://docs.mapbox.com/mapbox-gl-js/example/geojson-polygon/
https://docs.mapbox.com/mapbox-gl-js/example/animate-point-along-line/

**Comment by taloengrat-p** [comment]
try to cast object return from **map.getSource('my-source') as GeoJSONSource** and then .setData already appear

**Comment by Shiva127** [comment]
> try to cast object return from **map.getSource('my-source') as GeoJSONSource** and then .setData already appear

For casting, you can do:
```ts
map.getSource<GeoJSONSource>('some id')
```
