### ISSUE TITLE
fill-pattern does not support feature-state expressions

### ISSUE THREAD

**Issue by wtravO** [mapbox/mapbox-gl-js#10142]
**mapbox-gl-js version**: latest

**browser**: all

### Steps to Trigger Behavior

 1. Add a layer with a fill-pattern paint property with a case expression dependent on a feature-state. i.e. the fill-pattern is imageA when the feature state is A, the fill-pattern is imageB when the feature state is B.
 2. Toggle the feature-state and observe.

**Comment by ryanhamley** [comment]
This is a known issue. Let's focus discussion in the existing ticket https://github.com/mapbox/mapbox-gl-js/issues/7207
