### ISSUE TITLE
Mapbox markers not positioned or styled correctly

### ISSUE THREAD

**Issue by Shalashtein** [mapbox/mapbox-gl-js#10156]
I'm using Mapbox in my rails app, the map works fine, geolocation works fine, however the markers aren't and I've checked the other similar issues but this is slightly different. The div is created, and the styling supplied by the default mapbox css CDN file generates am invisible marker, that is position: absolute; top: 0; left: 0;

In the chrome developer tools, I unchecked this styling attribute:

```
transform: translate(-50%, -50%) translate(-18184px, -23353px) rotateX(0deg) rotateZ(0deg);
```

and I can see the marker, however it is position at the top left corner rathen than at the click location

The JS

```
const mapElement = document.getElementById('map');

  if (mapElement) { // only build a map if there's a div#map to inject into
    mapboxgl.accessToken = mapElement.dataset.mapboxApiKey;
    const map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/shalashtein/ckieyax2e43ic19qrhajxpasn',
      center: [35.5018, 33.8938], // starting position
      zoom: 13 // starting zoom
    });
    map.on('load', function () {
      console.log("resizing");
      map.resize();
    });
    map.addControl(new MapboxGeocoder({ accessToken: mapboxgl.accessToken,
                                      mapboxgl: mapboxgl }));
    map.on('click', function(e) {
    // The event object (e) contains information like the
    // coordinates of the point on the map that was clicked.
      console.log('A click event has occurred at ' + e.lngLat);
      console.log(e.lngLat.wrap().lat);
      console.log(e.lngLat.wrap().lng);
      map.resize();
      var marker = new mapboxgl.Marker()
      .setLngLat([e.lngLat.wrap().lat, e.lngLat.wrap().lng])
      .addTo(map);
    });
  }
```
the console shows the right coordinates, everything is working fine except for the positioning and styling of the marker

**Comment by brncsk** [comment]
@Shalashtein I think you might have mixed up the order of `lng` and `lat` in `.setLngLat([e.lngLat.wrap().lat, e.lngLat.wrap().lng])`

**Comment by ryanhamley** [comment]
Did you include the GL JS CSS file?

**Comment by Shalashtein** [comment]
> @Shalashtein I think you might have mixed up the order of `lng` and `lat` in `.setLngLat([e.lngLat.wrap().lat, e.lngLat.wrap().lng])`

You are absolutely right, I still haven't gotten used to the fact that Mapbox puts the Longitude before the Latidude, thank a lot I wasted a lot of time trying to figure this out
