### ISSUE TITLE
change bboxify input and output to avoid conversion

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1015]
We currently [convert before calling bboxify]( https://github.com/mapbox/mapbox-gl-js/blob/0d7badd14f16366f461a134e6484cc292f28e3d4/js/placement/placement_feature.js#L14-L21).
[And after](https://github.com/mapbox/mapbox-gl-js/blob/0d7badd14f16366f461a134e6484cc292f28e3d4/js/placement/placement_feature.js#L27-L31).

We should get rid of this.

**Comment by kapadia** [comment]
@ansis `bboxify-labels` now conforms to the input/output needed by gl.
