### ISSUE TITLE
How do you control the flyTo animation of the GeolocateControl ?

### ISSUE THREAD

**Issue by vomc** [mapbox/mapbox-gl-js#10153]
**mapbox-gl-js version**: ^1.12.0

### Question

We have a react app that uses a wrapper but we also access the mapboxGL map object directly. We also have a GeolocateControl that we added to our map.

I am not finding any documentation that helps me understand how I could disable the `flyTo` animation that is triggered when a user clicks on this control. Setting various options on the underlying map object such as `AnimationOptions` with `animate: false` seems to not be possible.

Is there a document or any tips on where I can find information on how one might control this?

Thanks!

**Comment by andrewharvey** [comment]
Docs for GeolocateControl are at https://docs.mapbox.com/mapbox-gl-js/api/markers/#geolocatecontrol.

There is an option `fitBoundsOptions` described as

> A Map#fitBounds options object to use when the map is panned and zoomed to the user's location. The default is to use a maxZoom of 15 to limit how far the map will zoom in for very accurate locations.

When you click through to https://docs.mapbox.com/mapbox-gl-js/api/map/#map#fitbounds it describes that the `fitBounds` `options` supports "supports all properties from AnimationOptions and CameraOptions".

Under `AnimationOptions` at https://docs.mapbox.com/mapbox-gl-js/api/properties/#animationoptions you can then see there is an `animate` option which you can set to false to disable the animation and instead the camera with just immediately change to the new view.

eg

```js
map.addControl(new mapboxgl.GeolocateControl({
  flyBoundsOptions: {
    animate: false
  }
}));
```

**Comment by vomc** [comment]
Yay ! THank you so much -- could not really find this in the docs when I was searching 🙏
