### ISSUE TITLE
External GeoJson not populating map when formatted with custom icon

### ISSUE THREAD

**Issue by Larry3DT** [mapbox/mapbox-gl-js#10150]
Wondering if you can advise me why when I try and upload the json from https://www.myiapps.net/MappedCases/index.php  (the result of this url, is the exact-same as what is in the html code below). The code below works but when I try load it externally it does not.

`<!DOCTYPE html>
<html>
<head>
<meta charset=utf-8 />
<title>Custom marker icons</title>
<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
<script src='https://api.mapbox.com/mapbox.js/v3.3.1/mapbox.js'></script>
<link href='https://api.mapbox.com/mapbox.js/v3.3.1/mapbox.css' rel='stylesheet' />
<style>
  body { margin:0; padding:0; }
  #map { position:absolute; top:0; bottom:0; width:100%; }
</style>
</head>
<body>
<div id='map'></div>
<script>
var getLocation = 'https://www.myiapps.net/MappedCases/index.php'; 
L.mapbox.accessToken = 'pk.eyJ1IjoibGFycnloc2EiLCJhIjoiY2ltcWg2cDI4MDAyZHc4bTJ3d2hyOTJhNiJ9.yYthkZMRrtjoW3WWfroRxA';
var map = L.mapbox.map('map')
    .setView([-33.97397, 18.46131], 8)
    .addLayer(L.mapbox.styleLayer('mapbox://styles/mapbox/streets-v11'));

var myLayer = L.mapbox.featureLayer().addTo(map);

var geoJson = {
  "type":"FeatureCollection","features":[{"type":"Feature","properties":{"title":"Carjacking Status: Open","icon":{"iconUrl":"https://www.myiapps.net/_lib/img/pegs/abduction.png","iconSize":[30,30],"iconAnchor":[0,25],"popupAnchor":[0,-25],"className":"dot"}},"geometry":{"type":"Point","coordinates":[18.46131,-33.97397]}},{"type":"Feature","properties":{"title":"Abduction Status: In-court","icon":{"iconUrl":"https://www.myiapps.net/_lib/img/pegs/abduction.png","iconSize":[30,30],"iconAnchor":[0,25],"popupAnchor":[0,-25],"className":"dot"}},"geometry":{"type":"Point","coordinates":[18.58153,-33.66621]}}]
};

// Set a custom icon on each marker based on feature properties.
myLayer.on('layeradd', function(e) {
    var marker = e.layer,
        feature = marker.feature;

    marker.setIcon(L.icon(feature.properties.icon));
});

// Add features to the map.
myLayer.setGeoJSON(geoJson);
</script>
</body>
</html>`

**Comment by ryanhamley** [comment]
Can you create a working example of the problem with a site like JSFiddle? That will make it easier to diagnose the issue.
