### ISSUE TITLE
mapboxgl get "Uncaught ReferenceError: g is not defined"  in npm run build mode

### ISSUE THREAD

**Issue by linze99** [mapbox/mapbox-gl-js#10168]
**mapbox-gl-js version**:
2.0.0
**browser**:
Chrome
### Steps to Trigger Behavior

 1. npm init react-app test
    npm install --save mapbox-gl
    create a div container , and new a mapboxgl object.
 2. npm start
     it all goes well
 3. when npm run build,and published under tomcat
i got a error:
e76d7262-a227-4481-baf2-011636f4a47e:1 Uncaught ReferenceError: g is not defined

### Link to Demonstration

https://jsbin.com/

**Comment by mourner** [comment]
Same issue as #10173 — let's keep the discussion along with the current workaround there.
