### ISSUE TITLE
Weird rotation of labels when `text-rotation-alignment` is `map`

### ISSUE THREAD

**Issue by brncsk** [mapbox/mapbox-gl-js#10163]
![image](https://user-images.githubusercontent.com/1205180/101527378-373fcf00-398e-11eb-992b-3932c82d92b9.png)

Please observe that labels are upside down. They also exhibit weird rotation changes whenever the map is rotated.

The style snippet in question is the following:

```json
{
  "id": "city-label",
  "type": "symbol",
  "source": "composite",
  "source-layer": "place",
  "layout": {
    "text-size": [ "interpolate", ["linear"], ["zoom"], ...  ],
    "text-radial-offset": 1,
    "text-allow-overlap": true,
    "text-variable-anchor": ["left"],
    "text-max-angle": 30,
    "text-transform": "uppercase",
    "text-font": ["PT Sans Caption Bold", "Arial Unicode MS Regular"],
    "text-padding": 1,
    "text-rotation-alignment": "map",
    "text-pitch-alignment": "viewport",
    "text-field": [
      "to-string",
      ["coalesce", ["get", "name:hu"], ["get", "name"]]
    ]
  },
  "paint": {
    "text-halo-color": "hsla(0, 0%, 100%, 0.75)",
    "text-halo-width": ["interpolate", ["linear"], ["zoom"], 0, 1, 22, 8],
    "text-halo-blur": 1,
    "text-color": "hsl(19, 0%, 18%)"
  }
}
```

**mapbox-gl-js version**: v2.0.0

**browser**: Google Chrome 87.0.4280.88

**Comment by ansis** [comment]
> "text-rotation-alignment": "map"

Changing this property to `"text-rotation-alignment": "viewport"` should fix this. This is the default behavior so you can also just delete the property.

Setting it to `"map"` makes the text rotate along with the map. In screenshot it looks like the map is rotated nearly 180 degrees and the text is rotated to match that.
