### ISSUE TITLE
Use sessions for v2 billing

### ISSUE THREAD

**Issue by korywka** [mapbox/mapbox-gl-js#10178]
This ticket is a continue of discussion https://github.com/mapbox/mapbox-gl-js/issues/10162#issuecomment-742160053

Why I think that paying for each new mapbox instance is not the best solution. Some examples:

1. One interactive element, each switching between a map and a drone 360 photo (have a map in the left corner) call new mapbox instance:

https://www.dropbox.com/s/i0zsi2dmf665l2g/Screen%20Recording%202020-12-10%20at%2012.18.02.mov?dl=0

Possible solution: use the same map instance to reduce cost

2. A map is opened inside a preview modal window for multiple grid elements at one page:

https://www.dropbox.com/s/kv2dqn9mv36rk3o/Screen%20Recording%202020-12-10%20at%2012.19.44.mov?dl=0

Possible solution: hide the map inside div with `display: none`, and do magic with styles, center and data before rendering a new modal window.

3. The same map, not SPA, switching between filters changes URL and a new map instance is called:

https://www.dropbox.com/s/5ky1iewfocui3do/Screen%20Recording%202020-12-10%20at%2012.21.14.mov?dl=0

Possible solution: to render a new page URL without page reload, so to make SPA from MPA site.

---

I think that using sessions for billing is more fair solution. For example, calc all new map instances as single one if there is no delay between invocation for 20 min. If 20 minutes have passed since the last call of new instance - this is a new session.

**Comment by aleksejleonov** [comment]
@bravecow 

I believe, we had similar use cases.

We widely use 2-3-4 maps on one page in sync to compare different types or dates of satellite imagery.
In most cases, we use only our own in-house generated tiles for in-house processed satellite imagery.

We use react for such pages, but each page is separate (not SPA, we have the Rails app).

With v2 all these maps would be billed and it would be crazy expensive.

<img width="974" alt="Screen Shot 2020-12-10 at 14 00 38" src="https://user-images.githubusercontent.com/241582/101770020-8271f300-3af0-11eb-9e82-5e0f1d99b960.png">

**Comment by asheemmamoowala** [comment]
@bravecow @aleksejleonov Thank you for sharing these cases (cool stuff!)

We see the multiple maps within a page session and mini-map scenarios as valid ways to use GL-JS and are investigating how this can be addressed. 

> The same map, not SPA, switching between filters changes URL and a new map instance is called:
> https://www.dropbox.com/s/5ky1iewfocui3do/Screen%20Recording%202020-12-10%20at%2012.21.14.mov?dl=0

> Possible solution: to render a new page URL without page reload, so to make SPA from MPA site

It's not clear from the video - are the filters changing the hash portion of the URL or loading a new webpage? From the video it looks like this can be achieved with a single map instance, using `map#setStyle` and other runtime styling APIs.

**Comment by bravecow** [comment]
@asheemmamoowala ops, sorry. Forget to record address bar. This switcher changes page URL, for SEO purpose these maps should be accessed on different URL. Since it is not SPA, page fully reloads.

**Comment by underbluewaters** [comment]
This will be an issue with our application as well. Using frameworks like React it is really common to end up creating new map instances unintentionally. There are ways to avoid it but it puts a high burden on the developer. There are also plenty of cases where it's a legitimate design choice to show multiple maps (see screenshot), and you may not want to discourage it. Of course that's more of a business decision than a technical one.

<img width="997" alt="Screen Shot 2020-12-11 at 8 34 20 AM" src="https://user-images.githubusercontent.com/511063/101929537-d7167c00-3b8b-11eb-8cdc-fe82a2a97ce8.png">

**Comment by philippe18** [comment]
Some examples of use cases for which the new billing model will lead to a major increase in the cost of Mapbox.

Map embed
If a map is embedded in a web page, a session will be counted on page load.
If the user moves to a different page and comes back after 2 seconds to the page with the map embed,  another session is being counted.
With Mapbox GL1.0 and map loads billing, you introduced sessions with 12 hours timeout.
In Mapbox GL2.0, a user can generate 2 different sessions within 2 seconds. 
12 hours session is great but as someone suggested, 30 minutes sessions would be reasonable.

Map Creation
We have customers creating and customizing maps through our platform.
In our editor, a user can open multiple maps simultaneously. The main map is used for preview. Other smaller maps are used as “tools” for customizations like drawing, positioning, zoom, pitch...
Those “tools” are designed to be opened for a few seconds and then closed.
A user can open and close those “tools” maps tens of times while editing a map.
This would lead to a very large number of map loads based on the Mapbox GL2.0 definition of map loads.

**Comment by douglasg14b** [comment]
Similarly for a mobile game. The user will often switch to different views within the game, and then back to the map. A user might load the map dozens of times in a play session.

Just me, doing development on it have already performed ~800 map loads after just 2 days....

**Comment by asheemmamoowala** [comment]
Thanks for providing your input and use cases in this ticket. We have decided to leave the Map Load pricing unchanged at this time. Pricing by sessions seems like an easy solution, but turns out to be very complicated from implementation, billing, documentation, and future-proofing given Web browser changes. 

We also offer [Seats pricing](https://www.mapbox.com/pricing/#webmapseats) where cost scales by number of users and not number of map loads. For those anticipating large volumes, I can suggest reaching out to our [sales team](https://www.mapbox.com/contact/sales).

**Comment by joewoodhouse** [comment]
We have similar issues. 

Our use case is a mobile data collection app where a user selects a form to complete and then steps through the form to submit the data. One of the pages of the form _could_ be a map for them to enter a location or polygon. So each time a user starts this form, they could be costing us a map load, and they can do this as many times as they like, so our Mapbox costs now become completely unbounded. This isn't a sustainable business model for us.

**Comment by asheemmamoowala** [comment]
Thank you for sharing these scenarios with us. As mentioned in https://github.com/mapbox/mapbox-gl-js/issues/10178#issue-761138881, there are mitigations possible to decrease the number of instantiations in some of these cases. The mitigations also turn out to be good performance improvements for applications. 

We are not considering offering session-based pricing at this time. We’ve debated this internally and considered the complexity of all the above cases among others in defining a session, and the ability to maintain a technical implementation over a long period of time. We continue to look at how GL-JS is used in applications, and look for ways to provide the right billing mechanisms to enable customer use cases.

For now, we also offer pricing by [seats](https://www.mapbox.com/pricing/#webmapseats), which provides unlimited usage per user. For volume discounts or annual pricing, please contact our [sales team](https://www.mapbox.com/contact/sales/?page=/pricing).

**Comment by douglasg14b** [comment]
> We are not considering offering session-based pricing at this time.

That's too bad that pricing models are different between product offerings even if the use case is the same. The rise in PWAs for mobile games is one that may pass mapbox right on by when the pricing is actually impossible.

> and look for ways to provide the right billing mechanisms to enable customer use cases.

This actively disables all use cases **that have short usage sessions many times daily**, which is the problem. These use cases are now incompatible with mapbox 2.0+. It's not a matter of "T_his just cost a bit more_" it's a matter of "_This has an exorbitant cost orders of magnitude higher than before, and is more than the revenue the app could ever hope to achieve_" kind of cost. It's entirely incompatible.

And the worst part is that it is charged regardless of if we use mapbox resources or not, that's the really erogenous and almost _maliciously greedy_ part here. That fact is what makes your words more akin to PR lip-service, than something genuine or understandable, it's almost loathsome in it's disingenuity.

_______________________________________

> The mitigations also turn out to be good performance improvements for applications.

By keeping a map in memory on small-memory footprint devices or forcing the application to have a background process on mobile devices just to avoid unnecessary loads? I don't think performance means what you imply it does?

**Comment by korywka** [comment]
I agree with @douglasg14b that keeping mapbox instance at background to save $$$ is hard to consider performance improvement.

It is hard to consider moving from MPA to SPA as performance improvement too. All users that deploy their sites as HTML pages ([Static Site Generated](https://www.cloudflare.com/learning/performance/static-site-generator/)) to S3 or something have to pay more. But in most cases SSG is faster than SPA.

My first comment was likely a list of hacks to reduce costs.

Offtopic: A lot of complaints about decisions of mapbox managers on glassdoor lately. Please, listen to your users and don't make us look for an alternative :)
