### ISSUE TITLE
re-add support for text- and icon-padding

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1017]
It could probably be added here https://github.com/mapbox/mapbox-gl-js/blob/82967e121ee44d99e93a07162e94baabafdc40fd/js/data/symbol_bucket.js#L228-L231

**Comment by ansis** [comment]
done in fac0152

**Comment by kkaefer** [comment]
To confirm, this is only in the placement branch, and used to be there before, right?

**Comment by ansis** [comment]
@kkaefer yes
