### ISSUE TITLE
Where does terrain data come from and can other sources be used?

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-js#10188]
Hi,

The new 3D terrain feature is awesome and something we've been looking for for some time. The performance is great and can open many possibilities.

Having used it in more detail, we noticed some examples of unrealistic bumps and divots in the terrain. It made us wonder where the data behind it comes from, how accurate is it, and could we use other sources which might be more detailed? Is there a maximum 'resolution' or could we in theory use detailed landscape surveys/scans?

Here's an example of a bump in the middle of a river, and a divot in a car park. I noticed the equivalent location in Cesium seems to be more accurate, detailed and realistic.

<img width="629" alt="Screenshot 2020-12-11 at 14 01 17" src="https://user-images.githubusercontent.com/13920398/101912614-e6acb980-3bb9-11eb-819d-a9921afae13a.png">

Equivalent location in Cesium
<img width="702" alt="Screenshot 2020-12-11 at 14 08 05" src="https://user-images.githubusercontent.com/13920398/101912961-50c55e80-3bba-11eb-87e1-c04c638ee6bc.png">

And from the movie Godzilla which it kind of reminds me of (sorry couldn't resist!)
![z7Dc3_](https://user-images.githubusercontent.com/13920398/101913933-93d40180-3bbb-11eb-8cb2-88d4e951e35d.gif)

Perhaps it's not the intention for the feature to be used at this kind of level of detail, and it is aimed more at displaying landscapes at lower scales such as mountain ranges?

Any info on this would be interesting.
Thanks

**Comment by asheemmamoowala** [comment]
@joedjc Any [raster_dem](https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#raster-dem) source type can be used for the terrain. 

Out terrain tileset is a conflation of multiple data sources and is updated from time to time. We've reported the area you highlighted above as needing review. 

Thanks for the report!
