### ISSUE TITLE
vectortile parsing error

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1019]
`Uncaught TypeError: Cannot read property 'push' of undefined`
`vectortilefeature.js:76`
https://github.com/mapbox/vector-tile-js/blob/5b562b945aa552f48b3e0b6fb37c5de08a5219af/lib/vectortilefeature.js#L76

This happens when parsing tile 11/572/748
`http://localhost:3000/debug/#11.3/43.5449/-79.4266/-17.3`

**Comment by jfirebaugh** [comment]
The second feature in the "water" layer of this tile has a geometry that begins with a "closePolygon" command. vector-tile-js assumes that can't happen.

/cc @springmeyer

**Comment by jfirebaugh** [comment]
Pushed a failing test-case to vtjs: https://github.com/mapbox/vector-tile-js/compare/mapbox-gl-js-1019

**Comment by springmeyer** [comment]
@jfirebaugh - will need to try to reduce a testcase by recreating tiles from water - tracking at https://github.com/mapbox/mapnik-vector-tile/issues/90

**Comment by mourner** [comment]
Upstream.
