### ISSUE TITLE
line-dasharray has some problem

### ISSUE THREAD

**Issue by Yuki-Zhao** [mapbox/mapbox-gl-js#10199]
1) set line-dasharray = [0] or 0. there is not feature on map. how to appear solid line?
2) Dose line-dasharray support expression?

**Comment by karimnaaji** [comment]
@Yuki-Zhao 

> 1. set line-dasharray = [0] or 0. there is not feature on map. how to appear solid line?

You can use a non-dasharray line feature in such case. For example, directly using something like that to have a full color fill/solid:

```
map.addLayer({
  'id': 'route',
  'type': 'line',
  'source': 'route',
  'layout': {
    'line-join': 'round',
    'line-cap': 'round'
  },
  'paint': {
    'line-color': '#888',
    'line-width': 8
  }
});
```

>2. Dose line-dasharray support expression?

No, there are no expression supported for line-dasharray.

I'll close this issue as I don't believe the above is an issue directly related with the library.
