### ISSUE TITLE
map.flyTo(...) altitude is relative to the 3d terrain mesh, not sea level

### ISSUE THREAD

**Issue by benjamintd** [mapbox/mapbox-gl-js#10204]
Hey friends! I've been playing with the new release. Thanks a lot for that, it's been very fun to use the 3d so far. 

**mapbox-gl-js version**: 2.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. Add 3d terrain and move the map over mountains
 2. trigger a flyTo to a neighboring point on the other side of a mountain 

![Dec-14-2020 19-18-58](https://user-images.githubusercontent.com/11202803/102119341-3d77f480-3e41-11eb-9183-3f0c71731ad6.gif)

### Expected Behavior

The camera smoothly transitions to the flyTo point

### Actual Behavior

The camera, even with no collision or closeness with the 3d terrain mesh, will move relative to the 3d terrain, not sea level.

Perhaps another camera method is more suited to this kind of usage (transitions in 3d space), however `flyTo` is convenient and easy to use.

**Comment by karimnaaji** [comment]
hey @benjamintd thanks for the bug report and feedback, we're already tracking this issue in https://github.com/mapbox/mapbox-gl-js/issues/10195. I'll close this one as duplicate.
