### ISSUE TITLE
Add wireframe terrain debug mode/toggle

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#10208]
Similarly to showTileBoundaries, it may be useful to provide a small toggle allowing visualization of the terrain mesh.

A few use cases reported by @samanpwbb 
- Improve understanding/debugging issues with terrain sources
- Improve understanding and visualization of camera interaction with terrain

**Comment by rreusser** [comment]
This issue could be a good way for me to jump into the 3D world. It seems like the obvious way to accomplish this is to reuse the buffer of vertices and draw line elements for the wireframe, probably with GL_LINES even though they're limited to 1px wide.

A potential downside is that it takes a bit of work to de-dupe the edges that result from naively converting each face into three edges. The only thing that would make duplicate edges okay is if it's still relatively cheap to render and is a debug-only feature.

Alternatively, a wireframe can be rendered as a triangle mesh fragment shader using barycentric coordinates. This allows lines > 1px, but also requires either modifying the existing rendering or a completely separate draw of the whole surface which would presumably discard almost all fragments. I think this approach is best avoided.

**Comment by karimnaaji** [comment]
@rreusser using GL_LINES seems like a simple option, and is good enough for this purpose. We have used this in internal code which I can point you too if that's helpful, it only involved using a different buffer due to the ordering of vertices.

<img width="718" alt="Screen Shot 2021-02-18 at 9 16 37 AM" src="https://user-images.githubusercontent.com/7061573/108394835-02d86280-71ca-11eb-909c-b556ebee816b.png">

We did not expose it as a debug flag, but we have other debug flag that are usually exposed using map.map.showOverdrawInspector, map.showCollisionBoxes, map.showTileBoundaries, etc..

**Comment by rreusser** [comment]
Yeah, if there's anything you can't point me toward, that'd be very helpful! No sense completely reinventing the wheel.

**Comment by rreusser** [comment]
Got it working, though my approach required completely duplicating the gl program just to combine the terrain program with a constant-color fragment shader. Maybe this could be accomplished more easily in the existing terrain program via a mapbox pragma. At this point though, I'm mostly just glad to have some pixels flowing onto the screen! 😄 

So far it's not an unreasonable amount of code, and probably pretty concise if I can figure out how to piggyback on the existing terrain program and turn the fragments a solid color. Is this still a thing that's worthwhile to add?

![wireframe](https://user-images.githubusercontent.com/572717/108460272-1d8ff300-722d-11eb-9935-5dcf74923cab.jpg)

**Comment by rreusser** [comment]
@samanpwbb, just a ping to inquire: is this still an interesting feature?

Context: I just started at Mapbox 🎉. I gave this a shot as a good first issue. I think I could tackle this relatively easily, but the above results fall somewhat short of production-ready so that before digging farther, I wanted to reach out and check if this still interesting or if there's a particular design or other requirements that would accomplish the goal.

Glad to discuss here or out of band or, if nothing else, chalk it up to a good learning experience that's not needed at this particular moment. Thanks!

**Comment by samanpwbb** [comment]
> is this still an interesting feature? It's interesting to look at but perhaps less interesting than if the terrain were adaptively downsampled.

Yes, I do think it's useful and should be added as long as it doesn't come with any significant costs (like increased bundle size). There are two use-cases where I'd like to see this: 

1. Developer building with the camera API. Tools for clearly visualizing the mesh will make it easier for developers to iterate on fly-throughs or custom movement controls.
2. Designer working in Studio. Clearly visualizing the terrain mesh will help designers make decisions about labelling and exaggeration.

If you look at Studio's "view modes" you will see which debug options we offer now:

<img width="348" alt="Screen Shot 2021-02-19 at 1 48 30 PM" src="https://user-images.githubusercontent.com/108094/108565225-2b8b5580-72b9-11eb-8db7-113043673cdf.png">

---

If I could make one feature request for a terrain view mode, it'd be the addition of labels that provide some insight into the z values for points on the mesh. The tile boundary debug option eposes tile coordinates for each tile in top left corner and that detail is super convenient:

<img width="460" alt="Screen Shot 2021-02-19 at 1 56 48 PM" src="https://user-images.githubusercontent.com/108094/108565887-52965700-72ba-11eb-95ae-aa4f694a434d.png">

**Comment by rreusser** [comment]
Thanks for the info, @samanpwbb! I'm going to see if I can get it working a bit more economically, in terms of bundle size. Do you think this would be ideal as:

1) wireframe-only (see [karim's picture](https://github.com/mapbox/mapbox-gl-js/issues/10208#issuecomment-781505617) above; terrain is rendered only as a wireframe. This is the most minimal and easy on the technical level)
3) wireframe shows through terrain (middle of the road for effort)
3) hidden line (see [example above](https://github.com/mapbox/mapbox-gl-js/issues/10208#issuecomment-781825722); terrain occludes wireframe; has z-fighting issues)

Would a single high-visibility color be adequate?

**Comment by samanpwbb** [comment]
(3) certainly looks best but even (1) would be useful. 

> Would a single, hard-coded high-visibility color be adequate?

Yep! This approach has worked fine for past debug modes.

**Comment by karimnaaji** [comment]
Addressed in https://github.com/mapbox/mapbox-gl-js/pull/10406.
