### ISSUE TITLE
Add configurable fog to enhance 3d scene depth perception

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#10205]
Fog (or haze) is a simple effect that can be used to increase depth cues and perception of 3d terrain. More than a design feature, by allowing to smoothly blend the horizon with the sky, the fog can be used as a scene size reduction. It would allow for a performance opportunity around horizon cutoff for tiles by using distance tile culling (e.g. more aggressively reducing tile count when reaching close to the opaque fog cutoff).

Some technical differences with 2d vs 3d mode: all pixels go through draw_raster_terrain (drawn as a draped layer), which is a convenient and easy way to evaluate pixel depth and apply the fog falloff in single shader place, in 2d (when tiles do not go through draping phase) this is different and we would need to inject the fog factor evaluation globally. A good location for that might be in the shader prelude which gets injected in every shader variants, and evaluate the fog on a per layer basis.

Some open questions:
- **Pitch** If depth is used as a fog falloff input, we may have to ensure 0-fog factor on non-tilted views, does this mean the fog should be a function of the tilt? Where 0-tilt is equivalent to 0-fog, while full tilt results in fully applying full fog contribution?
- **Labelling** Are labels affected by fog?
- **Design**
   - Should fog be a global property, or is there any other layer that could host this system? (Thinking of the sky layer) 
   - When using sky layers, should the sky horizon color used for a convenient fog color default in order to more easily blend sky with fog. How is that specific color evaluated based on the sky layer?
  - Is there a strong need for potentially having different falloff options?
     - Pixel constant
     - Tile constant
     - Distance constant
   - Should the fog contribution change with zoom level?
   - Is there a strong need for height fog (Smog)? (Refer http://shadedrelief.com/3D_Terrain_Maps/3dterrainmapsval.html)

Fixed fog factor prototyping results from gl-js:

<img width="815" alt="Screen Shot 2020-12-14 at 11 48 44 AM" src="https://user-images.githubusercontent.com/7061573/102128508-d50a2280-3e02-11eb-9f02-d50dc39c1dc2.png">
<img width="984" alt="Screen Shot 2020-12-14 at 11 49 16 AM" src="https://user-images.githubusercontent.com/7061573/102128513-d6d3e600-3e02-11eb-8aa4-edc875663175.png">
<img width="970" alt="Screen Shot 2020-12-14 at 11 49 32 AM" src="https://user-images.githubusercontent.com/7061573/102128517-d89da980-3e02-11eb-9aff-7cd3f8fbece6.png">

Further references & prior art: http://shadedrelief.com/3D_Terrain_Maps/3dterrainmapsfor.html

<img width="824" alt="Screen Shot 2020-12-14 at 11 15 54 AM" src="https://user-images.githubusercontent.com/7061573/102124958-c66d3c80-3dfd-11eb-80f8-8dc40b2d6311.png">

**Comment by samanpwbb** [comment]
> * Should fog be a global property, or is there any other layer that could host this system? (Thinking of the sky layer)

I like the idea of making fog a root level property, similar to terrain. Not sure how multiple fogs from different sky layers would interact, and then users would have two separate stacks to reason about (sky stacking on top of each other, with their fogs also stacking on each other) which might get confusing.

**Comment by karimnaaji** [comment]
> I like the idea of making fog a root level property, similar to terrain. Not sure how multiple fogs from different sky layers would interact, and then users would have two separate stacks to reason about (sky stacking on top of each other, with their fogs also stacking on each other) which might get confusing.

Yes I agree. While experimenting I've noticed a few strong components to eventually reflect in the spec:
- _fog color_: If not provided this could inherit the color evaluated at the horizon to smoothly blend the scene at the distance (horizon color is determined by the scene sky layers, as done in prototype screenshot above).
- _falloff_: how fast does the fog reaches full opacity, this is essentially a function of the distance (exp, linear, ...)
- _falloff edges_: how far in front of the camera does the fog starts blending in, and how far does the fog ends (reaching full opacity). This may implicitly be a function of the tilt, as top down views should have no fog contributions (edges could be given values that no-op the fog in such case)
