### ISSUE TITLE
broken links in FreeCameraOptions doc description

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#10206]
**mapbox-gl-js version**: 2.0.0

**browser**: N/A

### Steps to Trigger Behavior

 1. Go to https://docs.mapbox.com/mapbox-gl-js/api/properties/#freecameraoptions
 2. See text "See {@Link Camera#setFreeCameraOptions} and {@Link Camera#getFreeCameraOptions}", expect to see real links.

**Comment by ryanhamley** [comment]
This will be fixed by https://github.com/mapbox/mapbox-gl-js/pull/10164
