### ISSUE TITLE
map.addSource() should accept a POJSO

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1021]
(plain-old JavaScript object)

e.g.:

```
map.addSource("geojson", {
    "type": "geojson",
    "data": {
        ...
    }
});
```

**Comment by rjairath** [comment]
But map is not accepting a variable that contains the json object. In that case it throws the error: "Input data is not a valid GeoJSON object."

**Comment by ryanhamley** [comment]
@rjairath `addSource` will accept a variable containing a JSON object, but the variable has to point to valid GeoJSON. You can view the GeoJSON spec at [geojson.org](https://geojson.org/) and validate and debug your GeoJSON with [geojson.io](http://geojson.io).
