### ISSUE TITLE
Mapbox GL JS and Here Maps

### ISSUE THREAD

**Issue by DerecksonS** [mapbox/mapbox-gl-js#10216]
**mapbox-gl-js version**:
2.0 

### Question
Hello, 
I am migrating from Leaflet to Mapbox-gl-js and I have some questions:

- Is it possible to use vector tiles from Here Maps with Mapbox GL JS?
- Is it necessary to always use Mapbox styles?

Same as in this example?
https://developer.here.com/documentation/vector-tiles-api/dev_guide/topics/examples/mapbox.html

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/style-spec/

**Comment by mourner** [comment]
> * Is it possible to use vector tiles from Here Maps with Mapbox GL JS?

Yes. However, starting from GL JS version 2.0, a Mapbox account is required regardless of which tiles you use, and map loads beyond 50,000 per month will be billed. See #10162 for more information.

> * Is it necessary to always use Mapbox styles?

No. The default Mapbox styles are tailored for Mapbox tiles, so you'll have to make your own style that targets HERE vector tiles which might have different layer names, properties etc.

**Comment by DerecksonS** [comment]
Thanks for that! 

Best regards
