### ISSUE TITLE
Uncaught TypeError undefined 'transform' from custom markers when moving map

### ISSUE THREAD

**Issue by lukashakkarainenvayqer** [mapbox/mapbox-gl-js#10210]
Hi!

Since V2 we've come across this TypeError from marker.js on line 450. 

*Mapbox GL JS V2 2.0.0*:

*Google Chrome*:

### Steps to Trigger Behavior

I have not reproduced this issue outside our enviroment, but it was working as intended pre 2V.
 1. Create a custom map-marker
 2. Move the map

### Expected Behavior
Not throwing TypeError

### Actual Behavior
Throwing TypeError of undefined on line 450 in marker.js

Thank you for your help.

**Comment by sgolbabaei** [comment]
Thank you for your opening this ticket. To help the maintainers and community understand and address the problem accurately can you please provide a minimal, complete, verifiable demonstration of the issue. We recommend using [https://jsbin.com](https://jsbin.com). Please include information about the browser version and operating system used.

**Comment by ajbraudev** [comment]
We are encountering this error as well
