### ISSUE TITLE
How to remove Map's black border when clicking on it ?

### ISSUE THREAD

**Issue by SparkDragon** [mapbox/mapbox-gl-js#10223]
**mapbox-gl-js version**: 2.0.0

### Question

When clicking on the map, a thin black border is displayed in the canvas.

Is there a way to disable this "feature" ?

Map before click : 
![image](https://user-images.githubusercontent.com/6637451/102499980-1d804500-407c-11eb-8952-dbfcd0556218.png)

Map after click : 
![image](https://user-images.githubusercontent.com/6637451/102500107-3d176d80-407c-11eb-96e5-450357681d81.png)

You can test on Mapbox' official doc website : https://docs.mapbox.com/mapbox-gl-js/example/simple-map/

As far as I know, this behaviour is the same on every example. 

It's important for me to disable this, because it's messing with my app design...

**Comment by mourner** [comment]
See #10048. `.mapboxgl-canvas { outline: none; }`

**Comment by SparkDragon** [comment]
Thank you @mourner !!!
I've been searching for hours...
