### ISSUE TITLE
Blurry line labels on v2 3D map

### ISSUE THREAD

**Issue by ivanrigovsky** [mapbox/mapbox-gl-js#10220]
**mapbox-gl-js version**: 2.0.0

**browser**: Chrome, Safari

### Steps to Trigger Behavior

 1. open https://sheregesh.traveler.today/en#map
 2. rotate the map to see the 3D view. 

### Link to Demonstration

https://sheregesh.traveler.today/en#map

### Expected Behavior
Readable line labels.

### Actual Behavior
Blurry labels.

**Comment by mourner** [comment]
Yeah, this doesn't look right, especially on max pitch:

![image](https://user-images.githubusercontent.com/25395/102500353-e9f5e880-4084-11eb-907b-324ee6356f91.png)

**Comment by mourner** [comment]
@ansis and me have tracked it down to this uniform:

https://github.com/mapbox/mapbox-gl-js/blob/4eda2785747558c70d63013e94143c7fa397da5d/src/render/program/symbol_program.js#L200

The `cos(pitch)` part that scales label blurriness with pitch doesn't take terrain into account, so labels that appear legibly on a hill during max pitch are rendered as if they were extremely squished. An OK workaround for now would be to simply disable that scaling when terrain is enabled.
