### ISSUE TITLE
3D terrain limits a certain area from loading

### ISSUE THREAD

**Issue by zhanghanbing1998** [mapbox/mapbox-gl-js#10228]
**mapbox-gl-js version**: 2.0.0

### Question
Hi，I am here https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/ Add 3D terrain to the map.
`setTerrain()` Is it possible not to load 3D terrain within a certain range ?
Looking forward to hearing from you !

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/

**Comment by mourner** [comment]
Unfortunately not — terrain source is set globally and can't be limited to a certain area. What use case do you have in mind for this?

**Comment by zhanghanbing1998** [comment]
@mourner I want to embed the tunnel model into the mountain in 3D terrain, using the three.js However, after I added the model directly, I found that it would be lifted by 3D terrain. Therefore, I thought of not loading the 3D terrain of a certain area, so that I could replace the position with my own mountain model, and then embed my tunnel. Do you have any better suggestions?

**Comment by asheemmamoowala** [comment]
If you know the exact position where you do not want terrain data to be available, you could use `transformRequest` to replace those tiles or portions of those tiles with your own tiles or flat tiles.

```
const m = new Map( {transformRequest: breakTiles });
...

function breakTiles (url, resourceType) {
  if (resourceType === 'Source' && url.indexOf(`raster-dem-v1/<tileId>) > -1) {
    return {
      url: <URL to special tile with area of interest 0'ed out>
      }
    }
}
```
