### ISSUE TITLE
ImageSource is not shown on Firefox and Safari (v1.13.0, v2.0.0)

### ISSUE THREAD

**Issue by OttyLab** [mapbox/mapbox-gl-js#10226]
**mapbox-gl-js version**: v1.13.0, v2.0.0

**browser**: Firefox, Safari

### Steps to Trigger Behavior

 1. Access the [example site](https://docs.mapbox.com/mapbox-gl-js/example/animate-images/) on Firefox or Safari
 2. You notice that "radar" image is not shown
 3. On chrome, it works.

### Link to Demonstration
https://jsbin.com/ponanoc/edit?html,output

From the bisect, following update causes a regression.
https://github.com/mapbox/mapbox-gl-js/commit/59c54259dda570983e3d18e1dd45625252ae6d10

### Expected Behavior
`ImageSource` is shown

### Actual Behavior
`ImageSource` is not shown

**Comment by asheemmamoowala** [comment]
@mourner can we patch v2. and v1.13 with https://github.com/mapbox/mapbox-gl-js/commit/59c54259dda570983e3d18e1dd45625252ae6d10 reverted to unblock this issue first.

**Comment by mourner** [comment]
No, I believe we should fix the underlying issue, and it's likely small. Bringing back the memory leak, especially with everyone now playing with the new imagery, is not a good option.
