### ISSUE TITLE
license

### ISSUE THREAD

**Issue by MicheleFioretto** [mapbox/mapbox-gl-js#10238]
Please consider change the license back to open source. 
from: https://www.mapbox.com/pricing/
".....A map load is counted every time Mapbox GL JS initializes on a webpage or in a web app. A map load includes unlimited Vector Tiles API and Raster Tiles API requests......" 

In my opinion this will have a negative impact on this project.... 
thanks

**Comment by mourner** [comment]
Let's keep the discussion centralized in the licensing ticket: #10162
