### ISSUE TITLE
Benchmark build script broken since removal of Buble

### ISSUE THREAD

**Issue by andycalder** [mapbox/mapbox-gl-js#10233]
Running `yarn start` fails to build `bench/benchmarks_view.js` because rollup does not recognize JSX. `rollup-plugin-buble` was removed from the rollup config in 20a210cd and now rollup cannot transform the JSX in this file.

**mapbox-gl-js version**: main since 20a210cd

@mourner I hesitated before submitting a simple PR to fix this because it looks like Buble is a legacy tool. Perhaps Babel is the way to go? I don't have much experience with bundlers.

**Comment by mourner** [comment]
@andycalder thanks for catching this! I'm not even sure we want to add back transpilation just for the benchmark JSX. Perhaps we should just remove JSX from the templates instead, replacing it with something simple like https://github.com/developit/htm

**Comment by andycalder** [comment]
Hi @mourner, sorry for the slow reply. I had a look at htm as you suggested, and it works as advertised. I just opened a PR (#10343) with some discussion points.
