### ISSUE TITLE
TypeError: Cannot read property 'line-join' of undefined

### ISSUE THREAD

**Issue by ats1999** [mapbox/mapbox-gl-js#10247]
**mapbox-gl-js version**:
latest
**browser**:
chrome
### Steps to Trigger Behavior
I don't think this can be generated every time.

I am getting this  TypeError 
```js
TypeError: Cannot read property 'line-join' of undefined
    at diffLayerStyles (layer.js:73)
    at Layer._updateLayer (layer.js:178)
    at Layer.componentDidUpdate (layer.js:125)
    at commitLifeCycles (react-dom.de
```
I am rendering Linestring to render line, the line data and coordinate is being changed frequently.

**Comment by mourner** [comment]
Unfortunately it's impossible to diagnose this issue without a reproducible live test case. The error stack trace above references methods/objects not present in GL JS — if it originates in a compatibility layer like a React component, you should report the issue in the corresponding project.
