### ISSUE TITLE
Pitch events not firing upon flyTo 

### ISSUE THREAD

**Issue by edwillys** [mapbox/mapbox-gl-js#10249]
**mapbox-gl-js version**: 1.13.0 (or even 2.0.0)

**browser**: Firefox / Chrome

### Steps to Trigger Behavior

 1. Set a listener to 'pitch', 'pitchstart' and/or 'pitchend' event
 2. Perform a flyTo action
 3. Check if the listener is reached vie, e.g. console logging. 

### Link to Demonstration

https://codepen.io/edwillys/pen/xxEYwvb

### Expected Behavior
All of the pitch listeners are reached as result of flyTo interaction

### Actual Behavior
None of them is reached

**Comment by edwillys** [comment]
Is there any feedback on this issue? Are you having this problem on your end?

**Comment by asheemmamoowala** [comment]
@edwillys the codepen you provided doesn't change the pitch of the map. The pitch related events are logged in the console if pitch is changed in the `flyTo`. Here's an example of how you might do that:
```
map.flyTo({
            center: [
                -74.5 + (Math.random() - 0.5) * 10,
                40 + (Math.random() - 0.5) * 10
            ],
            pitch: (Math.random() * 80),
            essential: true // this animation is considered essential with respect to prefers-reduced-motion
        });
```

**Comment by edwillys** [comment]
@asheemmamoowala Thanks for pointing that out. I corrected the pen, but still no message on console...
