### ISSUE TITLE
The position of the popup changed as the zoom changed

### ISSUE THREAD

**Issue by ChenGuanglin0924** [mapbox/mapbox-gl-js#10245]
**mapbox-gl-js version**:
2.0.0
**browser**:
chrome 87
### Steps to Trigger Behavior

 1. Click on the feature that added to the map, open the popup
 2. Zoom in map level

### Link to Demonstration

https://jsfiddle.net/garaschan/yzx5d4a7/31/

### Expected Behavior
The position of the popup does not change
### Actual Behavior
The popup is getting farther and farther
![image](https://user-images.githubusercontent.com/22443356/103265639-febd6f00-49e8-11eb-80e9-626a7528d8ca.png)

**Comment by mourner** [comment]
Unfortunately it's a technical limitation of GL JS — I don't think we can't fix this on our side. When you click the point and query the current map view for the feature under the cursor, it gets the coordinates information from the vector tiles the map uses for rendering, and vector tiles are optimized for a certain zoom level — the coordinates are simplified & snapped to a grid, so you don't get the precision of the original location when querying on a low zoom level. 

The only workaround I can think of is on the app side — e.g. lookup the original GeoJSON feature by id you get from the click handler, and use its original coordinates.

**Comment by ChenGuanglin0924** [comment]
would you solve this problem in the future?

**Comment by mourner** [comment]
@ChenGuanglin0924 it's hard to say, but I don't see an easy way to solve this at the moment.
