### ISSUE TITLE
set filter to map,zoom is 8.63, there are not't feature.

### ISSUE THREAD

**Issue by Yuki-Zhao** [mapbox/mapbox-gl-js#10241]
i set filter to map. There are some features.
but when zoom is 8.63, there are not feature in map,
when zoom is 7.15 or 9.94, there are some features in map.
why?
if i donesn't set filter to map, it's ok

**Comment by asheemmamoowala** [comment]
Thank you for your opening this ticket. To help the maintainers and community understand and address the problem accurately can you please provide a minimal, complete, verifiable demonstration of the issue. We recommend using https://jsbin.com.
