### ISSUE TITLE
Inconsistent final camera position using easeTo with V.2 + terrain 

### ISSUE THREAD

**Issue by fxi** [mapbox/mapbox-gl-js#10256]
Hello,

I've got something similar to to issue #10195, but not only the transition is sketchy, but the final camera position is unpredictable. Which is blocking.

**mapbox-gl-js version**: v2.0.0-dev

**browser**: 87.0.4280.88 (Official Build) (x86_64)

### Steps to Trigger Behavior

 1. Add terrain
 2. Navigate to flat area
 2. jumpTo mountains = ok
 3. flyTo  mountains = bumpy ride 
 4. easeTo mountains = messed up 

### Link to Demonstration

https://codepen.io/fxi/full/WNGJMVN

Note : terrain doesn't work in firefox 84.0.1 (64-bit) ( no 3d at all )

![mapbox_2_glitch](https://user-images.githubusercontent.com/1196833/103671293-021da100-4f7b-11eb-86fe-bb47295ee05b.gif)

Thanks, have a nice day

**Comment by ansis** [comment]
Thanks for the good example! I've merged this into the existing issue.
