### ISSUE TITLE
mapbox zoom to multiple markers

### ISSUE THREAD

**Issue by rullymartanto** [mapbox/mapbox-gl-js#10251]
I have multiple marker, and I want to make it zoom in to all marker

**Comment by asheemmamoowala** [comment]
For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
