### ISSUE TITLE
Prevent one finger manipulating map

### ISSUE THREAD

**Issue by lamtonylam** [mapbox/mapbox-gl-js#10250]
On Mapbox GL JS, if the user is on mobile and touches the map with one finger, the map moves. This creates frustration in the user, as maybe the user didn't want to manipulate the map, but just happened to touch it.

I would like to request a feature that allows map manipulation on mobile only when there are two fingers on the map.

For example, here's how Google Maps does it by default. I would like to see Mapbox have this feature because I like Mapbox better.

![image](https://user-images.githubusercontent.com/63186670/103476254-c341ec80-4dbc-11eb-94d2-120d7ef9e606.png)

**Comment by avpeery** [comment]
@lamtonylam we introduced the map option: `cooperativeGestures` in v2.6. Setting `cooperativeGestures` as `true` in the map constructor will require using two fingers to move the map when on a touch device. See this example on Mapbox documentation: https://docs.mapbox.com/mapbox-gl-js/example/cooperative-gestures/
