### ISSUE TITLE
polygon renderer error?

### ISSUE THREAD

**Issue by wtusmchen** [mapbox/mapbox-gl-js#10259]
**mapbox-gl-js version**:
2.0.1
**browser**:
Edge87
### Steps to Trigger Behavior

 1.add geojson source
 2.add fill layer
 3.zoom
 4.code:

mapboxgl.accessToken = '************************************************';
var map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/mapbox/streets-v11',
center: [112.9590472373244,35.86941098698303],
zoom: 5
});
 
map.on('load', function () {
map.addSource('maine', {
'type': 'geojson',
'data': {
'type': 'Feature',
'geometry': {
'type': 'Polygon',
'coordinates': [
[

[108.5317801116255,42.20044053912534],
[106.7371454285842,37.647452328119],
[119.03443518794614,37.35997327804749],
[118.86415761384978,43.1489235338606],
[112.9590472373244,35.86941098698303],
[108.5317801116255,42.20044053912534]

]
]
}
}
});
map.addLayer({
'id': 'maine',
'type': 'fill',
'source': 'maine',
'layout': {},
'paint': {
'fill-color': '#088',
'fill-opacity': 0.8
}
});
});

![1](https://user-images.githubusercontent.com/12149282/103714076-bb6e8c00-4ff8-11eb-9248-51a272ae34ea.png)
![2](https://user-images.githubusercontent.com/12149282/103714081-bd384f80-4ff8-11eb-861a-eabf6df5e0ef.png)
![3](https://user-images.githubusercontent.com/12149282/103714082-bdd0e600-4ff8-11eb-94e6-e17d1d96fc3e.png)

### Link to Demonstration

https://jsbin.com/

**Comment by mourner** [comment]
Mapbox GL JS only supports valid polygons, without self-intersections and other geometric degeneracies. See #7023 for more information.
