### ISSUE TITLE
Could not load image because of The source image could not be decoded

### ISSUE THREAD

**Issue by John2397** [mapbox/mapbox-gl-js#10277]
I add jpeg images to the map periodically (every X secs) using 
`map.addSource(...)`
and then 
`map.addLayer(...)`

Each image is first created dynamically and uploaded on a web server. So, once the request is successful on each image link, it means that the image is created and uploaded, so I add that image to the map.

```
every X s do:
      $.ajax({url: photo_url,  success: function(){  //if success it means 
                                                 //the photo I'm looking for is created
      
                  map.addSource("sourceid_" + photo.name, {
                                  "type": "image",
                                  "url": photo_url,
                                  "coordinates": [...]
                              })
      
      
      
                     map.addLayer({
                                "id": "layerid_" + photo.name,
                                "source": "sourceid_" + photo.name,
                                "type": "raster",
                                "paint": {"raster-opacity": 0.6}
                              })
                              },
                          });
```

The problem I'm facing is, although the request to that image might be a success, I get the error : `Could not load image because of The source image could not be decoded.. Please make sure to use a supported image type such as PNG or JPEG. Note that SVGs are not supported.`

My guess is that it happens because the photo has just been created but didn't give it enough time to write all the data?

If I refresh the page, the photos are successfully added (because I guess enough time has passed to be fully written on the webserver?).

A solution would be to wait until I know the image is fully written on the webserver, but how could I do that?

I tried to catch the above error with no results.

**Comment by George2397** [comment]
Solved the problem by [converting the image to base64 string](https://stackoverflow.com/questions/6150289/how-can-i-convert-an-image-into-base64-string-using-javascript) and then [checking if it's corrupted or not](https://stackoverflow.com/a/41635312/10371713)

**Comment by John2397** [comment]
Solved the problem by [converting the image to base64 string](https://stackoverflow.com/a/20285053) and then [checking if it's corrupted or not](https://stackoverflow.com/a/41635312/10371713)
