### ISSUE TITLE
No webgl

### ISSUE THREAD

**Issue by Feodor2** [mapbox/mapbox-gl-js#10275]
Hi
I found a mapbox on the site, but it does not work without webgl though. Sometimes i myself put a map pointer to site. I know for sure no any gl including webgl required for showing maps.  It would be very good to make an option for showing a map even if no any webgl.

**Comment by ansis** [comment]
[This library](https://github.com/mapbox/mapbox-gl-supported) can be used to check if the browser supports everything mapbox-gl-js needs, including webgl. When webgl is not supported, [mapbox.js](https://docs.mapbox.com/mapbox.js/api/v3.3.1/) can be used to add a map.
