### ISSUE TITLE
terrain source key should have compatibility config

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#10283]
**style-spec version**: 13.19.0

The source key on terrain should have the same SDK support config as exaggeration: https://github.com/mapbox/mapbox-gl-js/blob/2c9c1a62b784fc0e868fdc64178a8882d1da638d/src/style-spec/reference/v8.json#L3785-L3789 since source is not supported by any SDK besides GL JS v2+

**Comment by dereklieu** [comment]
👋  This issue of terrain source not properly identifying SDK requirements is causing customer pain in https://github.com/mapbox/studio/issues/14489. Can this be fast-tracked into the next style spec release?

**Comment by asheemmamoowala** [comment]
@dereklieu The fix has been merged already, and will be included in our next GL-JS release.
