### ISSUE TITLE
queryRenderedFeatures returns incorrect order of features based on map pitch 

### ISSUE THREAD

**Issue by m0hamad** [mapbox/mapbox-gl-js#10286]
**mapbox-gl-js version**: 2.0.1

**browser**: Chrome (87.0.4280.141)

### Steps to Trigger Behavior

 1. Rotate map to have higher pitch
 2. Click on a feature (part of fill-extrusion layer)
 3. The feature below the one that has been directly clicked on is highlighted

### Video
https://user-images.githubusercontent.com/25091942/104412847-6667d400-552a-11eb-9e00-a88722d62dad.mov

### Link to Demonstration
https://jsbin.com/muwukew/edit?html,output

### Expected Behavior
When I click on a feature, I select whichever element is at index 0 in the queryRenderedFeatures array. When I highlight a feature, I expect queryRenderedFeatures at index 0 to return the feature I'm clicking on directly, regardless of the map pitch.

### Actual Behavior
When rotating the map and increasing pitch, clicking on a feature then changes the ordering of the queryRenderedFeatures array, resulting in a different feature being highlighted.

Please let me know if you need any additional information.

**Comment by ryanhamley** [comment]
Does this happen with terrain enabled? If so, this is a known issue. Can you provide a minimal example of the bug in JSBin or JSFiddle?

**Comment by m0hamad** [comment]
Good question. This happens with any map style, I have 6 different map styles that I use and it happens with all of them. I'll create a JSBin shortly and post it.

**Comment by m0hamad** [comment]
Here it is: https://jsbin.com/muwukew/edit?html,output

**Comment by arindam1993** [comment]
Thanks for the repro @m0hamad , I have a fix in https://github.com/mapbox/mapbox-gl-js/pull/10293

**Comment by m0hamad** [comment]
Thank you!!

**Comment by arindam1993** [comment]
@m0hamad do you mind if I use your geojson from your fiddle in as a test case in our automated test suite?

**Comment by m0hamad** [comment]
Absolutely, go for it!

**Comment by karimnaaji** [comment]
@m0hamad our beta [v2.1.0-beta.1](https://github.com/mapbox/mapbox-gl-js/releases/tag/v2.1.0-beta.1) was released with a fix for this issue.

**Comment by m0hamad** [comment]
Thank you. Y'all are the best!
