### ISSUE TITLE
Freshly added source filter property is not working

### ISSUE THREAD

**Issue by crow7m** [mapbox/mapbox-gl-js#10280]
**mapbox-gl-js version**:

### Question
In order to filter regular markers and cluster, we are using filter on source, once i remove the source=>update filter and readd source to map, all features are not visible anymore,
The filter is very basic one as :
` [
            'all',
            [
              '>=',
              ['get', 'timeStamp'],
              parseInt(moment(self.getDatesRange[0]).format('x'))
            ],
            [
              '<=',
              ['get', 'timeStamp'],
              parseInt(moment(self.getDatesRange[1]).format('x'))
            ]
          ];`
Source addition code is:

                      ` map.addSource(sourceId, {
      type: 'geojson',
      cluster: true, //modify if heatmap
      //will be by default maxZoom -1
      clusterMaxZoom: clusterMaxZoomLevel ? clusterMaxZoomLevel : 23, // Max zoom to cluster points on
      clusterRadius: clusterRadius,
      maxzoom: maxZoom,
      clusterProperties: {
        usersCount: ['+', ['get', 'usersCount']],
        color: ['get', 'color'],
        
      },
      data: {
        type: 'FeatureCollection',
        features: sourceData
      },
      filter: filter
      // filter: filter
    });`

so we are just making compare operation between 2 i integers that represent date(timestamp),
the feature has feature.properties.timeStamp and it has some value, so cant see any reason for this not to work,
Will be glad to receive some answer and how this can be fixed.
Thank you for your time and effort.

### Links to related documentation
Link to source filter docs [https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson-filter](url)

**Comment by mourner** [comment]
It's difficult to diagnose the issue without a full example — could you please set up a minimal live test case, e.g. on JSBin or JSFiddle?

**Comment by crow7m** [comment]
@mourner thank you for quick action, here is the link to fiddle with reproduction.
[https://jsfiddle.net/0aefqht9/6/](url)
The filter is added once on load to the source, you can remove it in order to see that once we don't set any filter the data is being rendered on map as expected.

**Comment by crow7m** [comment]
@mourner Hope you are doing well and everyone is healthy, may i ask you if there is any update about this issue ? Thank you , and have a great week ahead.

**Comment by mourner** [comment]
@crow7m sorry for not getting back to you earlier — the example linked above doesn't work because you're using a very old version of GL JS (v0.28.0). `GeoJSONSource` `filter` option was introduced in v1.13.0. I confirmed that the example works properly with the latest release (v2.0.1).
