### ISSUE TITLE
Using v2 with invalid access token

### ISSUE THREAD

**Issue by bravecow** [mapbox/mapbox-gl-js#10282]
Hi. Looks like it is possible to use v2 with invalid access token.

1. Assign invalid token:

```js
mapboxgl.accessToken = '1';
```

2. Register service worker:

```js
navigator.serviceWorker.register('./sw.js', {
  scope: '/',
  origins: ['*'],
});
```

3. Mock mapbox responses inside sw.js:

```js
self.addEventListener('fetch', event => {
  console.log('HTTP call intercepted - ' + event.request.url);
  if (event.request.url.startsWith('https://api.mapbox.com/map-sessions/v1?sku') || event.request.url.startsWith('https://events.mapbox.com/events/v2?access_token=')) {
    event.respondWith(new Response(null, {
      status: 200,
    }));
  }
});
```

![image](https://user-images.githubusercontent.com/988471/104384139-9f5b7500-5539-11eb-8f1a-62684f37703b.png)

![image](https://user-images.githubusercontent.com/988471/104384156-a8e4dd00-5539-11eb-9d19-d6343904f05e.png)

![image](https://user-images.githubusercontent.com/988471/104384195-b8fcbc80-5539-11eb-8b55-b964b8dbc550.png)

It works well for self-hosted styles and tiles.

**Comment by asheemmamoowala** [comment]
@bravecow Mapbox GL JS v2 is governed by the Mapbox Service Terms, available at https://www.mapbox.com/legal/tos/. Under those terms, you may not use Mapbox GL JS v2 except under the conditions spelled out in those terms, and those terms state that you may not interfere with or limit the data that the Mapbox Web SDK send to us, whether by modifying the SDK or by other means. Using Mapbox GL JS v2 in violation of those terms violates the license and constitutes copyright infringement.

**Comment by bravecow** [comment]
I think you should consider to fix this issue, cause all offline, network restricted environments like admin panels and so on can break the rules. Yes, 100% protection most likely will not be, but this solution is **very** simple. As you wish 🤷‍♀️

**Comment by asheemmamoowala** [comment]
@bravecow yes - we are tracking that in https://github.com/mapbox/mapbox-gl-js/issues/10200.
