### ISSUE TITLE
WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.

### ISSUE THREAD

**Issue by romanstingler** [mapbox/mapbox-gl-js#10287]

**Comment by mourner** [comment]
You can safely ignore this warning in Firefox. See the discussion in #5292.

**Comment by martinhath** [comment]
The number of warnings Firefox reports before going silent (32 in @aolo2's screenshot) is configurable as `webgl.max-warnings-per-context` in `about:config`. Increasing it is a decent workaround.

**Comment by garma83** [comment]
> The number of warnings Firefox reports before going silent (32 in @aolo2's screenshot) is configurable as `webgl.max-warnings-per-context` in `about:config`. Increasing it is a decent workaround.

so I need to tell users to modify their firefox settings? How is that acceptable
