### ISSUE TITLE
queryRenderedFeatures returns duplicate feature

### ISSUE THREAD

**Issue by am2222** [mapbox/mapbox-gl-js#10297]
**mapbox-gl-js version**:1.12.0

### Question
Hi,
I somehow know why this is happening but I don't know how to solve this issue. Lets assume we have a dataset which is a set of points. We have also a TMS vector tile server which based on XYZ coordinates of each tile queries the dataset and returns a `pbf` file and we render them on them mapbox map. So far everything works fine. But there is one issue here. as mapbox loads data in each zoom the duplicate points are being downloaded and as a result `queryRenderedFeatures` returns duplicate features. Imagine tile number `1/1/1` is loaded. so any other tiles with `1/1/1` as their parent will have duplicate data.
Is there any way to solve this issue? like setting a base zoom for the source and then optimize tile loading?

### Links to related documentation
I guess such parameter should be part of source object definition or Style
https://docs.mapbox.com/mapbox-gl-js/api/sources/

**Comment by kbrownlees** [comment]
I am seeing the same behaviour on a geojson polygon source, so may not just be related to vector tilesets?

**Comment by am2222** [comment]
@kbrownlees It is mainly because of the duplicate features in all the zoom layers. I think there must be a wat to avoid rendering duplicate features (maybe using ID field?) and it should really impact the performance.  
For the large datasets one of the easiest methods to render data is transferring them as Vector tiles. But like I said we don't have multi-resolution data (per zoom level) and the tiling is only used to increase the query performance. So maybe mapbox is able to filter data in each datasource based on the id and avoid rendering/adding duplicated data?

**Comment by asheemmamoowala** [comment]
@am2222, per the `queryRenderedFeatures` [docs](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#queryrenderedfeatures), duplicates are possible: 

>  features come from tiled vector data or GeoJSON data that is converted to tiles internally, feature geometries may be split or duplicated across tile boundaries and, as a result, features may appear multiple times in query results. For example, suppose there is a highway running through the bounding rectangle of a query. The results of the query will be those parts of the highway that lie within the map tiles covering the bounding rectangle, even if the highway extends into other tiles, and the portion of the highway within each map tile will be returned as a separate feature. Similarly, a point feature near a tile boundary may appear in multiple tiles due to tile buffering.

If your question is about data in the Mapbox tilesets, you can consult the vector tile reference and specs at https://docs.mapbox.com/vector-tiles/reference/.

**Comment by am2222** [comment]
@asheemmamoowala Thanks for the reference, But is there any solutions or ideas for fixing this issue?

**Comment by spreaderman** [comment]
@asheemmamoowala  If there is a unique identifier for each feature, you can do something like the getUniqueFeatures() function in this [link](https://docs.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/).  Search for the function getUniqueFeatures()
