### ISSUE TITLE
Sprites on 1.5x

### ISSUE THREAD

**Issue by drewvosburg** [mapbox/mapbox-gl-js#1029]
I have two custom sprite sheets, on for @1x and one for @2x, but my icons get cut off on displays with a pixel density of 1.5.

I tried making sprites@1.5x.json, but it didn't do anything different.

I did notice that some of the default Mapbox sprite sheets don't have this problem.  What am I doing wrong?

![capture](https://cloud.githubusercontent.com/assets/313949/6359922/ea9e66fa-bc3b-11e4-97cd-6def34aea82d.PNG)

**Comment by ljbade** [comment]
I think we only support @1x and @2x, but gl-js should select the correct size for the current pixel density. Are you using Android?

/cc @ansis

**Comment by drewvosburg** [comment]
No, the issue is occurring on a Microsoft Surface in IE.  It's replicable in Chrome on a Mac through dev tools by setting the pixel density to 1.5

**Comment by meule** [comment]
The same problem in Firefox and Opera: http://cl.ly/image/0Q0w1p390Y1w
Looks like mapbox-gl-js uses constant height and width instead of those specified in my icons.json

**Comment by meule** [comment]
That happens if window.devicePixelRatio is not integer (0.835... in my case)

**Comment by lucaswoj** [comment]
@meule Can you confirm that this bug is fixed with the latest `master`? Feel free to re-open this ticket if it isn't.
