### ISSUE TITLE
Fix dev environment for Node v14

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#10290]
Currently GL JS development environment is not compatible with Node v14, which is the current [Active LTS version](https://github.com/nodejs/release). The dependencies get installed without errors, but running unit or render/query tests produces errors like this:

```bash
> ./build/run-node test/unit/geo/lng_lat.test.js 

/Users/mourner/projects/mapbox-gl-js/node_modules/@mapbox/flow-remove-types/index.js:1
SyntaxError: Error parsing /Users/mourner/projects/mapbox-gl-js/node_modules/babylon/package.json: Unexpected token , in JSON at position 726
    at JSON.parse (<anonymous>) {
  path: '/Users/mourner/projects/mapbox-gl-js/node_modules/babylon/package.json'
}
```

It's not related to `babylon` specifically, because running render tests points to a different JSON file:

```bash
> yarn run test-render

yarn run v1.22.10
$ SUITE_NAME=render run-s build-token testem-ci
$ node build/generate-access-token-script.js
$ CI=true testem ci -f test/integration/testem.js
/Users/mourner/projects/mapbox-gl-js/test/integration/lib/generate-fixture-json.js:1
SyntaxError: Error parsing /Users/mourner/projects/mapbox-gl-js/node_modules/glob/package.json: Unexpected token , in JSON at position 1082
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/Users/mourner/projects/mapbox-gl-js/test/integration/lib/generate-fixture-json.js:4:14)
    at Object.<anonymous> (/Users/mourner/projects/mapbox-gl-js/test/integration/lib/generate-fixture-json.js:1) {
  path: '/Users/mourner/projects/mapbox-gl-js/node_modules/glob/package.json'
}
```

Currently I'm not sure what's the issue here, but it might be related to our module loading set up with flow removal, esm and other hooks.

**Comment by mourner** [comment]
Instead of trying to untangle the issues with `esm` / `tap` / `flow-remove-types` with our current dated setup, I've looked into the possibility of dropping `esm` in favor of native ESM resolution for unit tests. It works! I've only tested on a small subset of the codebase (running `test/unit/geo/lng_lat.test.js`), but basically the steps are:

1. Declare `"type": "module"` in both GL JS and style-spec `package.json` so that Node resolves `.js` files in the project as modules.
2. Fix imports to have explicit extensions (`import {wrap} from '../util/util.js'`) instead of implicit (`'../util/util'`), which aren't supported by native ESM
3. Instead of `require` hooks which no longer work with native ESM, hook `flow-remove-types` through an experimental [ESM loaders API](https://nodejs.org/api/esm.html#esm_loaders) and a custom transform loader. Thus we would call Node like this:

```bash
> node --experimental-loader ./build/flow-loader.js test/unit/geo/lng_lat.test.js
```

With the following loader:

```js
import flowRemoveTypes from 'flow-remove-types';

export async function transformSource(source, context, defaultTransformSource) {
    if (source.indexOf('@flow') >= 0) {
        source = flowRemoveTypes(source.toString()).toString();
    }
    return defaultTransformSource(source, context, defaultTransformSource);
}
```

We could do step 2 (fixing imports) as a separate preliminary step by adding a corresponding rule to the ESLint import plugin and fixing all offenders.

**Comment by mourner** [comment]
The root offender appears to be the `esm` package which we use for ESM resolution — it simply fails on Node v14 with the errors above on a minimal example. We should drop it in favor of the approach above as soon as possible:

- The version we use, `3.0.84`, was released on 18 Sep 2018. We weren't able to upgrade to later versions due to weird incompatibilities — I remember spending several days on this a few years ago and not succeeding. #8450
- Even if we manage to upgrade, the latest version, `3.2.25`, was released on 17 May 2019 — almost 2 years ago, and the project is no longer maintained, with all issues and PRs ignored. Node v14 compatibility won't happen.
- We can't remain on old Node / `esm` versions indefinitely because of security risks.

**Comment by asheemmamoowala** [comment]
> The version we use, 3.0.84, was released on 18 Sep 2018. We weren't able to upgrade to later versions due to weird incompatibilities — I remember spending several days on this a few years ago and not succeeding. #8450

➕ ➕  I tried a bisect approach to update and revert `esm` with no additional insight.

**Comment by arindam1993** [comment]
Would it be possible to use rollup to build the tests into a bundle and then pass that bundle to tap?

**Comment by mourner** [comment]
@arindam1993 possibly, but that breaks the workflow of being able to run specific test files quickly when working on something, and it somewhat complicates the setup. Also, I think I attempted it a few years ago but ran into some very weird race conditions when all tests were in the same bundle.

**Comment by asheemmamoowala** [comment]
We should look at #6753 once this is done to see if there is an improvement in test run times as a result of these changes.

**Comment by mourner** [comment]
This was done in #10367
