### ISSUE TITLE
Is it possible to set a layer's metadata property in code and persist it

### ISSUE THREAD

**Issue by Bernoulli-IT** [mapbox/mapbox-gl-js#10295]
**mapbox-gl-js version**: 1.13

### Question

When applying filters from code onto layers (`map.setFilter`) it is needed to persist a possible filter from the style specification. To persist it I tried using the metadata property of a layer. Setting it in code goes well. Unfortunately, when retrieving the identical layer next time from (`map.getStyle().layers`) the metadate only reflects the original metadata from the style specification and the extra information added by code is "gone".

Also do I misinterpret the layers that come from `map.getStyle().layers` (apparantly from the style specification) and `map.getLayer`? Is there a definition of layers in the style specification and a working (living) set of layers actually used for map visualization (although setting a filter gets persisted when retrieving a layer with `map.getStyle().layers` 🤔 after updating the filter for a specific layer)

Any help would be appreciated. Another approach would be to store initial filter expressions from layers in a separate store (an Angular service in the application I am working on).

**Comment by mourner** [comment]
Unfortunately there's no way to persist changes to layer metadata at the moment. As a workaround, I'd suggest using a separate JS store, e.g. a `Map` object with `layer.id` as a key.

**Comment by Bernoulli-IT** [comment]
Already did so @mourner 👍🏼 It did went with an Array<KeyValuePair<string, Array<any>>> 😉 coming from a C# background and like to work with key value pairs 🤓
