### ISSUE TITLE
layer-level opacity

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#103]
Let's say I want to draw a semi-transparent street layer on top of satellite imagery.

If we just change the line opacity it looks something like this:
![lineoverlap](https://f.cloud.github.com/assets/1421652/1262172/634c0c52-2c3b-11e3-9aba-3ea29ec1ff9a.png)
Ideally, we can get rid of the overlapping. I'm seeing two possible approaches.

One approach would be to draw opaque lines to a framebuffer, and then copy them over with a different opacity, but this is probably fairly slow (completely untested).

The second approach would be to use the depth buffer to prevent double drawing. This works, but has some bugs:
![lineblock](https://f.cloud.github.com/assets/1421652/1262145/fe96fe3e-2c3a-11e3-89d4-e5de9011134a.png)

There are hairline cracks caused by anti-aliasing where the roads connect. The fragment is not opaque, but the depth buffer still gets written preventing the other line from being drawn there. To avoid this the anti-aliasing would need to be drawn later, separately. During the second draw, most of the fragments would be depth culled, so this shouldn't add a fragment shading cost. This change would also need to be made for #77 to be implemented.

The second problem is round linecaps. See the intersection on the right. The only way I see getting around this is adding something to the datatiles to specify whether a road ends in a junction or dead end. Or drawing linecaps/joins separately might fix this problem.

**Comment by cyrilchapon** [comment]
As of 2018, is that still possible ?

**Comment by ansis** [comment]
@cyrilchapon it is not possible anymore. The framebuffer approach was removed because it turned out to be a performance trap. It was too easy to create slow maps by adding more than a few layers with layer-level opacity.

**Comment by cyrilchapon** [comment]
If I hypothetically have a mvt server and a "dissolved coverage" to show, semi transparently. What would be the best approach then ?

I don't need and don't want the cumulative approach (multiplying features opacity), I literally want to have polygon visually dissolved runtime

**Comment by vin-ni** [comment]
Still no solution to this?

**Comment by waissbluth** [comment]
also wondering about the status of this -- it would be very useful to manage the transparency of a layer that has overlapping features
