### ISSUE TITLE
Raster tile loading thresholds

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1030]
Q: at what thresholds are raster tiles loaded and replaced? Would I see `z4` tiles from `z3.5` - `z4.5`, or `z4`-`z5`, or some other scheme?

Ideally, I'd prefer never to see a raster tile stretched beyond what it was meant for-- they get awfully pixellated right before hitting that handoff point. Can we keep the tile level 1 z ahead of the map's current zoom level (show `z4` tiles from `z3` - `z4`)? 

On the downside, this would mean loading quadruple the number of images

cc/ @jfirebaugh

**Comment by jfirebaugh** [comment]
Currently gl-js uses [`Math.floor`](https://github.com/mapbox/mapbox-gl-js/blob/a58c246f3f5b86473798e10a16fd3eecb5ee72c9/js/source/tile_pyramid.js#L130-130), i.e. z4 tiles from `z4` - `z5`.

Leaflet master uses [`Math.round(zoom)`](https://github.com/Leaflet/Leaflet/blob/4101f017784f3c40ba744b4fd33bdc0401522983/src/layer/tile/GridLayer.js#L387) -- i.e. `z4` tiles from `z3.5` - `z4.5`.

gl-js should switch to what Leaflet does.

**Comment by ansis** [comment]
Should we also switch how fill and line patterns are scaled?

**Comment by ansis** [comment]
Should we also switch vector tiles?

**Comment by jfirebaugh** [comment]
@ansis You are the best person to answer those q's. :)

**Comment by peterqliu** [comment]
>gl-js should switch to what Leaflet does

It's certainly better than what we have now, but `Math.round` still yields blurriness half the time (instead of all the time). Is `Math.ceil` too many tiles to load? It would guarantee at *least* the expected sharpness, at all zooms:

![screen shot 2015-02-25 at 11 59 14 am](https://cloud.githubusercontent.com/assets/4551508/6379304/0c880f14-bce6-11e4-9f64-04ad0ab5b54f.png)

**Comment by ansis** [comment]
This is a tradeoff between sharpness and download size. The bigger the image size, the more you have to download.

`round` leads to **2x** more pixels than `floor`
`ceil` leads to **4x** more pixels than `floor`

This means 2x-4x more data and slower tile load times. We need to find the right tradeoff.

Our raster layers are also blurrier because we can't pixel align the images. We can't pixel align because we allow fractional zooms and rotation. This is similar to the half pixel transform problem:
![](http://media.tumblr.com/tumblr_m7gb8q6sTa1qedoqt.png) 

So, there are two things causing blurriness:
- overscaling
- not being able to pixel align images (due to fractional zooms and rotation)

**Comment by incanus** [comment]
> Leaflet master uses `Math.round`, i.e. `z4` tiles from `z3.5 - z4.5`.

We should do this — it's what the mobile raster tools do as well. This is causing a problem in https://github.com/mapbox/mapbox-gl-native/issues/963 because `512px` raster tiles are showing way larger than they should be (just under twice as large at e.g. `zX.9999`).

**Comment by samanpwbb** [comment]
@peterqliu is this something you can experiment with in a branch of gl-js? Would be great to get a sense for how different approaches to the tile loading threshhold feel in practice.

**Comment by jfirebaugh** [comment]
@peterqliu I was thinking you could make a side-by-side tool that shows Math.floor vs Math.round vs Math.ceil (using current .js and two custom builds).

**Comment by peterqliu** [comment]
@jfirebaugh hmm, I'm seeing something weird:

1) the current js behaves like it's already using `Math.ceil`: going to https://www.mapbox.com/bites/00144/#9.1/40.0000/-74.5000 (z9.1) we expect to see z9 tiles, since we're currently using `floor`. but debug mode is clearly showing z10, and the z10 tiles were downloaded.

![screen shot 2015-05-22 at 6 30 15 pm](https://cloud.githubusercontent.com/assets/4551508/7781890/c11a276a-00b0-11e5-8602-14852f0b821f.png)

2) ^ Debug is showing tile labeling for both z9 and z10-- is that expected?

**Comment by incanus** [comment]
You can tell by the debug label size difference that the tile sizes are different. The 9's are from vector tiles which are being rendered in four times as much screen space (twice as long on a side). This coverage calculation happens whether tiles are shown are not IIRC.

**Comment by jfirebaugh** [comment]
@incanus is correct. z9 vector tile == 512x512 pixels == 4 256x256 z10 satellite tiles. If gl-js were using `ceil` it would need to load 16 z11 satellite tiles at z9.1.

**Comment by peterqliu** [comment]
Just built a [comparison tool](https://www.mapbox.com/bites/00144) switching between `ceil` and `round` (since we're comparing loading speeds, I opted not to have them both running side-by-side, as that would underestimate the speed when either mode is running by itself).

on my current connection, even `ceil` loads pretty quickly.

**Comment by peterqliu** [comment]
Let's implement `Math.round` for now. @jfirebaugh should I just branch off of the current master with the changes?

**Comment by jfirebaugh** [comment]
:+1: `Math.round` looks pretty good to me.

**Comment by tmcw** [comment]
Chatted with @ansis about this: the current behavior that we're seeing is worse than a round/ceil/floor issue would ever look: this is likely a mismatch between GL's "up by 1" zoom levels and its expectations around raster tiles: it is loading a z9 tile at "zoom level 9" but since zoom level 9 in gl == zoom level 10 in leaflet, the tile is blurry.

**Comment by ansis** [comment]
raster sources currently need `"tileSize": 256` so that they are rendered at the right size. For example, https://www.mapbox.com/mapbox-gl-js/example/map-tiles/

Blurriness caused by `Math.floor` is probably still an issue.

**Comment by peterqliu** [comment]
current progress is at https://github.com/mapbox/mapbox-gl-js/pull/1221

**Comment by peterqliu** [comment]
:boat:
