### ISSUE TITLE
Terrain: holes in ground on negative elevation (cut on far clipping plane)

### ISSUE THREAD

**Issue by astojilj** [mapbox/mapbox-gl-js#10317]
Reproducible:

Set terrain exaggeration to 5 in terrain-debug.html,
Navigate to http://localhost:9966/debug/terrain-debug.html#18.1/35.685084/139.768292/12.7
With no pitch hole is visible in ground - larger the exaggeration, larger is the hole.
For default exaggeration 1.0 there's no hole.

http://localhost:9966/debug/terrain-debug.html#18.1/35.685084/139.768292/12.7

https://user-images.githubusercontent.com/549216/105491103-75831a80-5cbe-11eb-9569-62c8f54dc01f.mov

**Comment by astojilj** [comment]
Elevation at the point is around -20 meters.

**Comment by karimnaaji** [comment]
A good test case is araound the salton sea area (next to LA):

https://user-images.githubusercontent.com/7061573/107275112-2b13d480-6a06-11eb-93b4-fbf51fad1bce.mov

**Comment by pratikyadav** [comment]
👋  One more location where I spotted this issue https://pratikyadav.github.io/maps/3d/#11.06/31.7289/35.5292

**Comment by karimnaaji** [comment]
@rreusser I pushed the diff we were chatting about, it makes use of the minimum elevation seen through the DEM mipmaps and pushes the far plane forward to account for that: https://github.com/mapbox/mapbox-gl-js/commit/22e988d3b1dc68669446bff74123aee381db82ec. I haven't tested that change thoroughly, only in some of the locations known to be problematic.
