### ISSUE TITLE
Terrain: expose getElevation API

### ISSUE THREAD

**Issue by astojilj** [mapbox/mapbox-gl-js#10318]
Without knowing elevation of item being rendered, it is not possible to place it on terrain.
E.g. If adding terrain support to custom layer example https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/, we wouldn't see the antenna: it assumes default 2D 0 level elevation and it is rendered invisible, under the terrain.

To display it, replacing modelTransform.translateZ (which has value of 0), by real elevation (scaled by meter to mercator scale used in the scene) fetched in the example using internal code (so not an API): `map.painter.terrain.getAtPoint(modelAsMercatorCoordinate)`. The objective is to expose this to public API.

Original code:
```
var l = new THREE.Matrix4()
    .makeTranslation(
        modelTransform.translateX,
        modelTransform.translateY,
        modelTransform.translateZ
)
```

It is rendered correctly (video below) after changing it to this:

https://github.com/mapbox/mapbox-gl-js/blob/fff43a3d162831e0e216565ca34074bb383075d5/debug/threejs-antenna.html#L110-L114

https://user-images.githubusercontent.com/549216/105498750-3908ec00-5cc9-11eb-83d9-297d84424202.mov

Example code is in branch https://github.com/mapbox/mapbox-gl-js/pull/new/astojilj-customLayerElevation

Important constrain of this API is that value is available only for the visible region on the screen, if terrain (DEM) tile is available.

**Comment by benjamintd** [comment]
This would be great to be able to compute the elevation of a route (e.g. a gpx track) client-side. I have been doing it in the past using the tile-query api, but as the elevation data is already downloaded to the client to render the terrain, this would make the computation faster (and potentially synchronous). In the case of real-time route editing, this would prevent many useless calls to an external service. 

Another way to do this had been to query the rendered features for elevation lines, but I believe the precision and resolution of the data is lesser than the newer elevation sources.

There's still an API question around the fact that the style could be missing an elevation source, and how to deal with exageration.

**Comment by karimnaaji** [comment]
Some quick thoughts after discussion with @arindam1993 :
- We need to differentiate cases with actual 0 altitude or whether tiles are unavailable through error handling
- We may allow an array of points as input to prevent going back and forth through the API surface for multiple geolocation queries

**Comment by astojilj** [comment]
Note that the API is implemented in Mapbox Maps v10 Mobile SDKs, both in Map and CustomLayerHost callback properties object. This relates to thread safety, to discourage access to Map API from render thread callback. No such requirements for gl-js.


Signature:
```
/**
 * @brief Get elevation for the given coordinate.
 * Note: Elevation is only available for the visible region on the screen.
 *
 * @param coordinate defined as longitude-latitude pair.
 *
 * @return Elevation (in meters) multiplied by current terrain exaggeration, or empty if elevation for the coordinate is not available.
 */
- (nullable NSNumber *)getElevationForCoordinate:(CLLocationCoordinate2D)coordinate
                                       withError:(NSError * _Nullable * _Nullable)withError __attribute((ns_returns_retained)) __attribute__((swift_error(nonnull_error)));

```

https://docs.mapbox.com/android/maps/api/10.0.0-beta.17/-mapbox%20-maps%20-android/com.mapbox.maps/-mapbox-map/get-elevation.html


For an illustration on usage, providing mapbox-maps-ios use case: in custom layer callback, vehicle is rotated (placed to follow terrain slope). For each wheel, LngLat gets calculated as input for `elevationData.getElevationFor`.

```
        let mercatorPosition = try Projection.project(for: self.position, zoomScale: scale)
        var dataNotAvailable = false;
        let ps = try wheels.map {
            (wheel: SCNNode) -> simd_double3 in
            let pos = wheel.convertPosition(SCNVector3Zero, to: self.scene.rootNode)
            let rotated = modelToMapRotation.act(SIMD3<Double>(Double(pos.x), -Double(pos.y), 0.0))
            let wheelRotated = MercatorCoordinate(x: mercatorPosition.x + rotated.x * meterInMercatorCoordinateUnits, y: mercatorPosition.y + rotated.y * meterInMercatorCoordinateUnits)
            let elevation = try elevationData.getElevationFor(Projection.unproject(for: wheelRotated, zoomScale: scale))
            dataNotAvailable = dataNotAvailable || elevation == nil
            return simd_make_double3(rotated.x, rotated.y, elevation != nil ? elevation!.doubleValue : 0.0)
        }
```

**Comment by bkhan23544** [comment]
@astojilj Man this is amazing


> Without knowing elevation of item being rendered, it is not possible to place it on terrain.
> E.g. If adding terrain support to custom layer example https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/, we wouldn't see the antenna: it assumes default 2D 0 level elevation and it is rendered invisible, under the terrain.
> 
> To display it, replacing modelTransform.translateZ (which has value of 0), by real elevation (scaled by meter to mercator scale used in the scene) fetched in the example using internal code (so not an API): `map.painter.terrain.getAtPoint(modelAsMercatorCoordinate)`. The objective is to expose this to public API.
> 
> Original code:
> 
> ```
> var l = new THREE.Matrix4()
>     .makeTranslation(
>         modelTransform.translateX,
>         modelTransform.translateY,
>         modelTransform.translateZ
> )
> ```
> 
> It is rendered correctly (video below) after changing it to this:
> 
> https://github.com/mapbox/mapbox-gl-js/blob/fff43a3d162831e0e216565ca34074bb383075d5/debug/threejs-antenna.html#L110-L114
> 
>  customlayerelevationapi.mov 
> Example code is in branch https://github.com/mapbox/mapbox-gl-js/pull/new/astojilj-customLayerElevation
> 
> Important constrain of this API is that value is available only for the visible region on the screen, if terrain (DEM) tile is available.

Man this is amazing!!!!!
I was looking for a solution for 3 hours. You saved me a lot of time
