### ISSUE TITLE
Clarify docs for layer transition properties

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#10310]
**mapbox-gl-js version**: 1.12

**browser**: FF

### Steps to Trigger Behavior

```js
map.setStyle({...map.getStyle(), 'icon-opacity-transition': {duration:1000,delay:0}})
console.log(map.getStyle()['icon-opacity-transition']); // undefined

map.setStyle({...map.getStyle(), 'transition': {duration:1000,delay:0}})
console.log(map.getStyle()['transition']); // {duration:1000,delay:0}
```
### Expected Behavior

By my reading of the spec, the first version should also save this `icon-opacity-transition` property.

### Actual Behavior

`icon-opacity-transition` (and presumably other `*-transition`) properties, don't seem to work. Or at least, not when set dynamically like this.

**Comment by mourner** [comment]
Per the [transition spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/transition/), only `transition` property is set globally — individual layer transitions like `icon-opacity-transition` are set per layer, so you'd have to use `map.setPaintProperty` on the corresponding layer. Perhaps it's not clear enough in the docs — any improvement suggestions are welcome.

**Comment by stevage** [comment]
Oh, wow. Yeah, that is certainly not how I read the docs:

>  A style's root transition property provides global transition defaults for that style.
>...
> Any transitionable layer property, marked by [icon], may also have its own `*-transition` property that defines specific transition timing for that layer property, overriding the global transition values.

I would suggest adding a sentence:

> This property is defined within the layer's `layout` or `paint` object, as appropriate.
