### ISSUE TITLE
How to prevent automatic window scrolling when opening popup?

### ISSUE THREAD

**Issue by enmust** [mapbox/mapbox-gl-js#10329]
**mapbox-gl-js version**: 1.13.0

### Question
Opening popup using mouseenter, click or any other way sometimes scrolls window. I get that this so-called feature should make the popup visible but sometimes it scrolls the page to top even if the map div is not on the top. Is there any way to prevent or disable the automatic window scrolling. 

### Links to related documentation

Use case can be seen on the mapbox docs page https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/ if you scroll the page down so that the clickable icon is barely visible then it scrolls the window.

**Comment by mourner** [comment]
Yep, this looks like a bug — needs investigation. Agree that the behavior looks inconsistent. Might be the browser reacting to the opened popup focusing on content, which is a recent accessibility behavior that can be turned off with the `focusAfterOpen` option.

**Comment by enmust** [comment]
@mourner Thanks, setting `focusAfterOpen` to **false** fixed it for me. I don't know why I didn't think to test it.

**Comment by philipp-rudloff-sendcloud** [comment]
This issue should be re-opened. While setting `focusAfterOpen` to `false` serves as a workaround for this particular issue, it shouldn’t be necessary. Focusing the popup as part of opening is desirable and doing so should not cause the window to scroll.

**Comment by Madhav-Malhotra** [comment]
To clarify for other readers, setting `focusAfterOpen` to `false` refers to passing an object to `mapboxgl.Popup()` like so:

```
const popup = new mapboxgl.Popup({ focusAfterOpen: false });
```
