### ISSUE TITLE
Mapbox gl and service worker

### ISSUE THREAD

**Issue by hmendezm** [mapbox/mapbox-gl-js#10326]
**mapbox-gl-js version**: 2.0.1

### Question

Do you have an example of how to use workers to have a separate thread for Mapbox gl?
The purpose of having Mapbox gl in a separate thread is to improve performance in the app.
Best
Henry

**Comment by mourner** [comment]
Henry, Mapbox GL already uses Web Workers under the hood by default, offloading as many expensive computations as possible to a separate thread to improve performance. Service Workers, on the other hand, are not related to performance — they are usually used for custom networking logic in offline apps.
