### ISSUE TITLE
Missing vertical labels

### ISSUE THREAD

**Issue by kapadia** [mapbox/mapbox-gl-js#1032]
Sometimes vertical labels are missing. A little nudge in rotation brings some of these labels back, but not always. Here's an example where a few tenths of a degree brings the label back.

![missing](https://cloud.githubusercontent.com/assets/581337/6363288/d2012e06-bc4b-11e4-85ee-d47fd1ee85de.jpg)

/cc @ansis

**Comment by kapadia** [comment]
Two things were going on here:

1. All symbols have two buffers associated with them: i) for upright text, ii) for upside down text. The map and label rotations determine which symbol is uploaded to the buffer. The statement which checks the angle had strict inequalities on both bounds, leaving cases where no symbol was uploaded to the GPU. https://github.com/mapbox/mapbox-gl-js/commit/76ecda06f94844e6d78726a6fc92f675d2e36386

2. Each symbol has an anchor that described the label's origin on the map. The anchor has properties like x/y/angle. In some cases the angle property was overwritten with the [angle property from the `point-geometry` library](https://github.com/mapbox/point-geometry/blob/master/index.js#L42-L44). This is avoided by instantiate a new Anchor object and explicitly setting the angle property. https://github.com/mapbox/mapbox-gl-js/commit/0b26deccd5d6d46de054e324e368561632b938cf

**Comment by kapadia** [comment]
Some vert labels are still missing. e.g.:

![16](https://cloud.githubusercontent.com/assets/581337/6385055/cc7ee030-bd19-11e4-8cf2-1fa056a24201.jpg)

**Comment by ansis** [comment]
fixed in  0d2b4ea
