### ISSUE TITLE
clip lines before making line labels

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1033]
Areas near tile edges have low line label density.

The vector tiles are padded with data for areas outside tile boundaries, so many line labels geometries start outside the tile boundaries. Our label interpolation tries to place the first label as close to the beginning of the line as it can. This first label often is partially outside the tile boundaries, and gets dropped later.

We should clip line label geometries to the tile edges so that we don't try to place labels that cross boundaries.

**Comment by kapadia** [comment]
@ansis can you point me to the part of the code where clipping should happen.

**Comment by mourner** [comment]
@kapadia somewhere here https://github.com/mapbox/mapbox-gl-js/blob/master/js/data/symbol_bucket.js#L157.

I could do this relatively quickly since I have clipping code in Leaflet.

**Comment by ansis** [comment]
done in d384378

**Comment by ansis** [comment]
@mourner I only read "I could do this relatively quickly since I have clipping code in Leaflet." just now. If your Leaflet clipping code is nicer or faster, we can switch to that.

**Comment by mourner** [comment]
@ansis looks pretty fast and also simple enough — lets leave it like this for now.
