### ISSUE TITLE
Can mapbox-gl-js theoretically support DEM/Terrain above zoom level 14 and 10m accuracy?

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-js#10333]
According to the docs mapbox terrain v2 supports zoom levels up to 14, with 10m vertical accuracy (https://docs.mapbox.com/vector-tiles/reference/mapbox-terrain-v2/).

This is great for displaying large landscapes such as mountain ranges, but not so good a more nuanced details.

To evaluate if we can use mapbox-gl for more detailed terrain visualisation we'd like to know:

- Can mapbox-gl in theory support higher zooms and accuracies? I.e. is the current z14 a limitation of mapbox-gl-js or the data?
- If yes, is it on the roadmap to either add more detailed data, or allow custom sources (I appreciate this has been asked already here https://github.com/mapbox/mapbox-gl-js/issues/10198) 

Some indication of whether this is possible in future would be really helpful.
Thanks

**Comment by andrewharvey** [comment]
The Terrain-RGB format has a limit of 0.1m vertical resolution https://blog.mapbox.com/global-elevation-data-6689f1d0ba65 the 1m DEM I use has a vertical accuracy of 0.3m. You can already use your own custom terrain source and go beyond z14/10m accuracy that the default Mapbox terrain source uses. But you can't drape yours on top of the Mapbox one, hopefully #10198 would solve that allowing your custom terrain but fallback to the Mapbox global one outside of your data coverage.

**Comment by joedjc** [comment]
@andrewharvey thanks for the response - thats really helpful.

I hadn't appreciated you can use any DEM source - I will definitely give that a try.

**Comment by mttreed** [comment]
@andrewharvey how does one use their own terrain source? I have so far been unsuccessful in getting that to work. Details here [11870](https://github.com/mapbox/mapbox-gl-js/issues/11870)
