### ISSUE TITLE
How to add multiple photo sources on a single layer

### ISSUE THREAD

**Issue by John2397** [mapbox/mapbox-gl-js#10341]
Every 2 seconds I create a new image source and a new layer for that source:
```
map.addSource("source_" + photo_id, {
    "type": "image",
    "url": photo_url,
    "coordinates": [... ]
})


map.addLayer({
    "id": "layer_" + photo.photo_id,
    "source": "source_" + photo_id,
    "type": "raster",
    "paint": {"raster-opacity": 0.6}
})
```

That means for every photo, a new layer is created.
I was wondering, is it possible to add the photo sources on  the same layer every time?

I've checked the documentation on this but couldn't find anything.

I'm just concerned wheather or not is efficient to create a new layer each iteration. Wouldn't that degrade performance if I end up having, let's say, 200 different layers?

**Comment by ansis** [comment]
`map.getSource('photoSource').updateImage(...)` can be used to change the image for a layers. https://docs.mapbox.com/mapbox-gl-js/api/sources/#imagesource#updateimage

**Comment by John2397** [comment]
Sorry if it wasn't clear but I would like all the previous photos to also remain on the map.
Doesn't changing the source mean that only the last one will be displayed?

**Comment by engrabid411** [comment]
> `map.getSource('photoSource').updateImage(...)` can be used to change the image for a layers. https://docs.mapbox.com/mapbox-gl-js/api/sources/#imagesource#updateimage

why this issue is closed? is it resolved?
