### ISSUE TITLE
How do you handle clicks on buttons in marker popup in React?

### ISSUE THREAD

**Issue by dzmitry-maslau** [mapbox/mapbox-gl-js#10345]
Hi all! So the question is - How do you handle clicks on buttons in marker popup in React, if it's possible?
I have around 50 markers and popups for each one of the markers. On popups I want to have buttons.
I was trying to create handleClick for it, but can't figure out how to do it using setHTML.

I know that this would work:
"<button type='button' onclick=alert('Success')>This Button</button>"

But instead, I need something like this:
"<button type='button' onClick={() => this.handleClick(something)}>This Button  </button>"
Unfortunately, this doesn't work.

This is what I have. 
Thanks a lot! 

componentDidMount() {
...........
map.on("load", function () {
...........
new mapboxgl.Marker(elem)
.setLngLat([longitude, latitude])
.setPopup(           
new mapboxgl.Popup({ offset: 25 }).setHTML(
"<button type='button' onClick={() => this.handleClick(something)}>This Button</button>"
)
...........
}

handleClick() {
...........
}

**Comment by LynnAU** [comment]
Just came across this issue myself, not sure if you're still experiencing it. But for anyone else, I found this after some googling.
https://stackoverflow.com/questions/48916901/possible-to-render-react-component-within-mapboxgl-popup-in-sethtml-or-setdo

Describes how you can use `Popup.setDomContent()` to a node that you can have React render into. So you still keep all your lifecycle events and not left with plain html/js

**Comment by dollysingh3192** [comment]
For React Checkout https://stackoverflow.com/a/66355541/10102695
