### ISSUE TITLE
Font cannot be aligned

### ISSUE THREAD

**Issue by zx3236114** [mapbox/mapbox-gl-js#10340]
Font cannot be aligned

How can I solve it？

this.map.addLayer({
          "id": data.id+"symbol",
          "source": data.id,
          "type": "symbol",
          "layout": {
             'text-font': [
              'Microsoft YaHei'
              ],
              "text-field": "大:12a大",
              "text-size":30,
              "text-padding":0,
              "text-anchor": "bottom"   
          },
          "paint": {
            "text-color": "#00008B",  
           }
          
        });

![1](https://user-images.githubusercontent.com/46116423/106119461-32c6b400-6190-11eb-98c4-fe4e7140e655.png)

**Comment by mourner** [comment]
See https://github.com/mapbox/mapbox-gl-js/pull/10298 which fixes this with the new `localFontFamily` option. You can try this out with the `v2.1.0-beta.1` pre-release we rolled out yesterday.
