### ISSUE TITLE
easeTo results in querySourceFeatures returning old information

### ISSUE THREAD

**Issue by skarnl** [mapbox/mapbox-gl-js#10350]
I'm working on an application based on the custom HTML clustering example (https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/) and got a weird behavior where after zooming in (with `easeTo`) the state of the features wasn't retrieved correctly

### Version information
**mapbox-gl-js version**: v2.0.1
**browser**: Firefox / Chrome (but doesn't seem browser depending)

### Steps to Trigger Behavior
 1. cluster markers
 2. add click-handling on the markers and when clicked, `easeTo` to zoom in on the marker-position
 3. add `moveend` listener so you can use `querySourceFeatures` when the zoom-animation has finished
 4. now the features from `querySourceFeatures` are still the features from 'just before' this finished state. So some clusters are still marked as clusters, but should be markers now.
 5. drag the map just 1px to trigger the `moveend` again and rerender the correct state

### Link to Demonstration
https://codepen.io/skarnl/pen/XWNmzrz?editors=0010

The source here is a tweaked variant of the HTML clustering example, except I added the click-listener (line 168). And also draw the HTML-marker when it's not a cluster - to show the difference outcome of the `querySourceFeature`.

I also simplified the regular markers, to show when they are drawn (black circles) or when it's the HTML-variant (red box with a black X)

I guess it has nothing to do with the clustering, so maybe a simpeler example with just a button and a `easeTo` would also do the trick. 

### Expected Behavior
I expect that when I listen to `moveend` and the zoom-animation has finished, the `querySourceFeature` would give back the features rendered at that moment in time.

### Actual Behavior
When clicking the cluster and do the `easeTo`, the rendering of the features works as intended (the black circles show the different markers) - but the `querySourceFeature` doesn't give back the correct state and seems to be lacking behind. Only after another `moveend` is triggered (by moving the map) the correct state is retrieved. 

When zooming in/out with my mouse-wheel it does work ... eventhough that also triggers the same `moveend` callback 🤔 

A solution I tried is to add some `setTimeout` in the `moveend`-handler, but that's weird and the timeout-time is arbitrary - 10ms doesn't work, but 200ms does. No idea why ...

**Comment by arindam1993** [comment]
@skarnl I don't think this is a bug, I believe you need to use `queryRenderedFeatures` instead of `querySourceFeatures`,

**Comment by mourner** [comment]
Another thought that I had looking at this issue is that it may be by design because `moveend` signifies the end of movement, but not necessarily the moment when new tiles for that zoom appear. A workaround might be to listen to `idle` event instead — this one will fire after all movement ended AND all requested data got fetched and rendered.

**Comment by skarnl** [comment]
>  I believe you need to use `queryRenderedFeatures` instead of `querySourceFeatures`,

I can't use the `queryRenderedFeatures` because that means I have to render something on the layer. Normally there is an filter active to hide the actual layer, I only use it so Mapbox will cluster stuff. In the example it also works like that.

```
        map.addLayer({
            'id': 'earthquake_circle',
            'type': 'circle',
            'source': 'earthquakes',
            //'filter': ['has', 'nothingHasThis'],  // UNCOMMENT THIS TO HIDE THE CIRCLES         
        });
 ```

If I enable (uncomment) the filter, so the debug (black) circles won't show, there won't be any HTML markers either when using `queryRenderedFeatures`.
And if I comment the filter, the black circles will show, the HTML markers will be created - **but** the same issue occures. After the `easeTo` animation, the state of the features isn't up to date to what is rendered.

So I don't think this is not a bug.

**Comment by skarnl** [comment]
> Another thought that I had looking at this issue is that it may be by design because `moveend` signifies the end of movement, but not necessarily the moment when new tiles for that zoom appear. A workaround might be to listen to `idle` event instead — this one will fire after all movement ended AND all requested data got fetched and rendered.

I understand what you are saying - but don't think it's by design. Especially since the example is build on this same idea, that after a `moveend` the markers will update.

And yes, I could update on `render` or `idle` or something - but that means that the clustering / markers will have to wait until all the vector-tile information is loaded as well. Which will be a weird delay.
In that case the `setTimeout` with some arbitrary delay might even be more user friendly.

My issue is that judging by the black (debug) circles, Mapbox renders the correct elements and _knows_ what should be shown and what not. So it kinda feels that the `querySourceFeatures` (and `queryRenderedFeatures` apparently) don't target the same source (no pun intended).

In the source-code I saw the `querySourceFeatures` uses some `sourceCache` or something - that sounds like it might be some kind of caching going on 🤔
