### ISSUE TITLE
text-font and icon-image do not get updated across all zoom levels

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-js#1035]
There is some form of caching happening for symbol fonts and images. This shows a literal `icon-image` value that retains the previously set image on some zoom levels.

![symbols](https://cloud.githubusercontent.com/assets/1577766/6404167/e5e7a3e4-bdc9-11e4-8035-6b38dfeab99e.gif)

**Comment by jfirebaugh** [comment]
@edenh Got live code somewhere?

**Comment by edenh** [comment]
http://jsfiddle.net/jkLcnh3o/2/ Zoom in past z10 and go back and forth around 10 to see the bug.

**Comment by jfirebaugh** [comment]
This is a symptom of #994, and was fixed.
