### ISSUE TITLE
High resolution SDFs caused Firefox performance regression

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#10357]
In testing for https://github.com/mapbox/mapbox-gl-js/pull/10346, I realized that Firefox TinySDF performance went off some kind of cliff with the high-res SDF changes. Loading `15.4/35.675906/139.764176/-22.7` in a style with many CJK glyphs, time spent in TinySDF drawing code went from 116ms to 4759ms!

According to the profiler, it's all time spent in `edt1d`, although the glyphs look like they're being rendered at the same size as in Chrome/Safari, so I don't have any immediate ideas for why it would be so much slower.

cc @mourner @asheemmamoowala @ansis

**Comment by mourner** [comment]
That's so weird! Can you see if using the previous version and just doubling the resolution has a similar slow down, just to see if any other changes like metrics have to do with it? Profilers are weird and sometimes can show time spent incorrectly.

**Comment by ChrisLoer** [comment]
You can disable the metrics logic by changing the `true` to a `false` in this line:

https://github.com/mapbox/tiny-sdf/blob/67de39bcc91d8be8e852d0b2b21134bccad6765c/index.js#L149

(Actually that still calls `measureText` but it only gets the "advance" and doesn't try to get the bounding boxes).

After making that change, Firefox performance goes back into the expected range. It wouldn't be very satisfying, but we could try to quickly patch this by disabling the metrics extraction on Firefox -- the "advance" is the only part we need for the new functionality, and the rest is just meant for performance optimization (not rasterizing glyphs any larger than they need to be).

**Comment by mourner** [comment]
Fixed by #10363
