### ISSUE TITLE
Label around a sharp corner

### ISSUE THREAD

**Issue by kapadia** [mapbox/mapbox-gl-js#1036]
Independence Ave is taking a sharp turn. These scenarios should be caught at:

https://github.com/mapbox/mapbox-gl-js/blob/8ee8e879d6863821278dbdd99ab427458b0f04ee/js/symbol/placement.js#L240-L245

![craycray](https://cloud.githubusercontent.com/assets/581337/6404659/282e1878-bdcf-11e4-8f92-e335d1323494.jpg)

/cc @ansis

**Comment by mourner** [comment]
Yeah, this will require some kind of lookahead to measure quick angle changes through several points.

**Comment by ansis** [comment]
implemented in 8f06055
