### ISSUE TITLE
Specific address shows incorrect location on the map -  wrong zipcode

### ISSUE THREAD

**Issue by MikeB-303** [mapbox/mapbox-gl-js#10373]
**mapbox-gl-js version**: "mapbox-gl": "^1.4.1"

**browser**: All (Chrome, Safari and Edge)

### Steps to Trigger Behavior

 1. Call this Get call: GET https://api.mapbox.com/geocoding/v5/mapbox.places/5980 E Coury Dr.json?autocomplete=true&country=US&types=region,district,address,place,poi&fuzzyMatch=true&limit=20
 2. The return is incorrect and shows the wrong zipcode for the address.
 3. When showing this on the map it is Cottonwood (not Camp Verde).

### Link to Demonstration

https://jsbin.com/

### Expected Behavior
zipcode: 86322
### Actual Behavior
zipcode: 86236
Response data from the Get is attached as a document.
[responseJson5980ECoury.zip](https://github.com/mapbox/mapbox-gl-js/files/5953093/responseJson5980ECoury.zip)

**Comment by ansis** [comment]
This issue tracker is for the mapbox-gl-js project. To report an issue with geocoding please go to https://support.mapbox.com/ or https://labs.mapbox.com/geocoder-feedback/

Thanks!
