### ISSUE TITLE
filter out labels failing text-max-angle earlier

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1037]
We used to figure out at what scale the label would fit without reaching the angle, and then show the label starting there. But since we're redoing placement at every zoom level this doesn't matter. We can just skip that label completely if it goes around a sharp corner.

The check and skip should happen sometime around here https://github.com/mapbox/mapbox-gl-js/blob/4e2c209dbb91a4688445845a159c22afcaf67d7b/js/data/symbol_bucket.js#L200

**Comment by mourner** [comment]
Are there many labels like this compared to the total number? The win might be negligible compared to the amount of added code.

**Comment by ansis** [comment]
While it helps with density a tiny bit, the main reason to do this is to not have something affecting visibility in the code responsible for generating glyphs. Doing it before the collision tests also makes debugging collisions easier because you don't have collision boxes drawn for labels that aren't visible.

Implemented in 8f06055
