### ISSUE TITLE
Question: Is it possible to feed your own virtual location instead of using the GPS's?

### ISSUE THREAD

**Issue by jeffreylanters** [mapbox/mapbox-gl-js#10380]
**mapbox-gl-js version**: N/A

### Question

Hi!

The title saids it all, is it possible to feed your own virtual location instead of using the GPS's? Simply allowing for the application to send custom coords into MapBox "tricking", if you will, it into showing a different user location. And if not, would this be a valuable addition to the module?

Thanks.

**Comment by jeffreylanters** [comment]
The reason behind this question is, we're creating a hybrid app which has contains of a WebView with a MapBox client. But every time this view is opened, the Safari WebView on iOS requests for Location permissions. I was looking around if it was possible to feed our GPS location from the native app into the WebApp to MapBox.

**Comment by ansis** [comment]
Would this solve your problem? https://github.com/mapbox/mapbox-gl-js/pull/10232

**Comment by jeffreylanters** [comment]
I think it will, I'll look into it. Thanks @ansis
