### ISSUE TITLE
by default, shift + drag -> zoom to bounding box  

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#1038]
This should be a default interaction in GL:

![2015-02-27 14_07_24](https://cloud.githubusercontent.com/assets/108094/6419290/ebf30c68-be89-11e4-9554-ac38022f4e11.gif)

**Comment by jfirebaugh** [comment]
:+1: 

Leaflet implementation: https://github.com/Leaflet/Leaflet/blob/master/src/map/handler/Map.BoxZoom.js

**Comment by tristen** [comment]
:+1: might pick this one up here.

**Comment by fnicollet** [comment]
Hello,

Is there a way to disable this default behaviour?

Thanks,

**Comment by jfirebaugh** [comment]
@fnicollet: https://www.mapbox.com/mapbox-gl-js/example/interactive-false/

**Comment by fnicollet** [comment]
What about being able to zoom in/out but not box-zoom as it interferes with existing behaviour? In leaflet, when settings the map's "boxzoom" option to false, it disables the handler automatically. It would be nice to be able to pick (boxzoom, rotation, tilt, etc.) when building the map

**Comment by jfirebaugh** [comment]
If I understand it correctly, what you're requesting can be characterized as "granular interactivity configuration". Can you open a separate ticket for that?

**Comment by mourner** [comment]
Yeah, that was on my TODO for a while — I want to refactor interaction code to be able to turn on/off individual features.

**Comment by mourner** [comment]
At least at the moment, we can quickly add a `boxZoom` option to `Map` that when set to `false` would disable `boxZoom`.

**Comment by fnicollet** [comment]
@mourner did you open an issue already or should I start one?

**Comment by mourner** [comment]
Don't remember, probably didn't open yet.

**Comment by fnicollet** [comment]
No problem, opened it as #1056
