### ISSUE TITLE
Strange error when my geoJSON is too large

### ISSUE THREAD

**Issue by chrismcnally** [mapbox/mapbox-gl-js#1039]
I'm new to Mapbox and trying to learn Mapbox-gl-js and testing it with a set of 330+ points using your sample html example is failing. I can only get it to work if I use < 10, or even < 7 markers.

https://gist.github.com/chrismcnally/111223a20136431a286f

I've tested my largest geoJSON in geojson.io and it works fine. But when I use it with Mapbox gl I get the error 

Chrome:
api.tiles.mapbox.com/mapbox-gl-js/v0.6.0/mapbox-gl.js:206   Uncaught TypeError: Cannot read property 'leaf' of undefined

In firefox I get the same line number, but the error is that 'i' is undefined.

I saw at least one other instance on stack exchange where the same error occurs.

**Comment by jfirebaugh** [comment]
Yes, this is a known issue: #987. It will be fixed in the next release (early this coming week).
