### ISSUE TITLE
Visualize a geo-referenced .obj 3D model in Mapbox using Three.js

### ISSUE THREAD

**Issue by dprovasoli** [mapbox/mapbox-gl-js#10392]
**mapbox-gl-js version**: v2.1.0

### Question

I would like to display a geo-referenced 3D object in .obj format in the correct location on my Mapbox map, creating a customLayer and loading the model with OBJLoader in Three.js. I am following this example (although I use THREE.OBJLoader instead of THREE.GLTFLoader) :

https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/

The difference is that while the vertices in the above example are expressed in meters with respect to a local origin (somewhere in the proximity of the object), in my case the vertices of my .obj file are in meters with respect to the origin of the EPSG:3857 coordinate system, which corresponds to (0°, 0°) in geographic coordinates. Here is an example of a group of vertices from my .obj file:

v 1249035.499624 5477018.159725 707.495766
v 1249035.877786 5477018.335839 707.495766
v 1249035.499624 5477018.159725 707.795766
v 1249035.877786 5477018.335839 707.795766
v 1249035.702283 5477018.715317 707.495766
v 1249035.702283 5477018.715317 707.795766
v 1249035.324120 5477018.539203 707.495766
v 1249035.324120 5477018.539203 707.795766

While I can reproduce the example above and even display my .obj models with local origin correctly, I cannot render models with the origin at (0°,0°).

My guess is that the problem comes from the scaling to convert real meters to mapbox units, since this scaling is different at the origin (0°,0°) and at the object location (I have tried with both scalings without any success).

I have also tried removing the PI/2 x-rotation, varying the altitude and averaging the two scalings. I am out of ideas.

Is my approach correct? Does anyone have any idea of how to correctly solve this problem?
Thanks in advance!

```js
  mapboxgl.accessToken = ' '
    
  var map = (window.map = new mapboxgl.Map({
  container: 'map',
  style: 'mapbox://styles/flyted/ckkgqa38s0dac17m3rj4clxgc',
  zoom: 6,
  center: [11.219807478, 44.0745266739],
  // pitch: 45,
  // roll: 90,
  antialias: true // create the gl context with MSAA antialiasing, so custom layers are antialiased
  }));




    // parameters to ensure the model is georeferenced correctly on the map
    // var modelOrigin = [11.219807478, 44.0745266739];
    // var scaleOrigin = [11.219807478, 44.0745266739];
    var modelOrigin = [0,0];
    var modelAltitude = 0;
    var modelRotate = [Math.PI / 2, 0, 0];
    
    var modelAsMercatorCoordinate = mapboxgl.MercatorCoordinate.fromLngLat(
    modelOrigin,
    modelAltitude
    );

    // transformation parameters to position, rotate and scale the 3D model onto the map
    var modelTransform = {
    translateX: modelAsMercatorCoordinate.x,
    translateY: modelAsMercatorCoordinate.y,
    translateZ: modelAsMercatorCoordinate.z,

    rotateX: modelRotate[0],
    rotateY: modelRotate[1],
    rotateZ: modelRotate[2],
    /* Since our 3D model is in real world meters, a scale transform needs to be
    * applied since the CustomLayerInterface expects units in MercatorCoordinates.
    */
    scale: modelAsMercatorCoordinate.meterInMercatorCoordinateUnits()
    };
    
    var THREE = window.THREE;
    
    // configuration of the custom layer for a 3D model per the CustomLayerInterface
    var customLayer = {
    id: '3d-model',
    type: 'custom',
    renderingMode: '3d',
    onAdd: function (map, gl) {
    this.camera = new THREE.Camera();
    this.scene = new THREE.Scene();
    
    // create two three.js lights to illuminate the model
    var directionalLight = new THREE.DirectionalLight(0xffffff);
    directionalLight.position.set(0, -70, 100).normalize();
    this.scene.add(directionalLight);
    
    var directionalLight2 = new THREE.DirectionalLight(0xffffff);
    directionalLight2.position.set(0, 70, 100).normalize();
    this.scene.add(directionalLight2);


    var loader = new THREE.OBJLoader();
    loader.load(
      "{% static '3D/sf.obj' %}",
    function (obj) {
    this.scene.add(obj);
    }.bind(this)
    );


    this.map = map;
    
    // use the Mapbox GL JS map canvas for three.js
    this.renderer = new THREE.WebGLRenderer({
    canvas: map.getCanvas(),
    context: gl,
    antialias: true
    });
    
    this.renderer.autoClear = false;
    },
    render: function (gl, matrix) {
    var rotationX = new THREE.Matrix4().makeRotationAxis(
    new THREE.Vector3(1, 0, 0),
    modelTransform.rotateX
    );
    var rotationY = new THREE.Matrix4().makeRotationAxis(
    new THREE.Vector3(0, 1, 0),
    modelTransform.rotateY
    );
    var rotationZ = new THREE.Matrix4().makeRotationAxis(
    new THREE.Vector3(0, 0, 1),
    modelTransform.rotateZ
    );
    
    var m = new THREE.Matrix4().fromArray(matrix);
    var l = new THREE.Matrix4()

    .makeTranslation(
    modelTransform.translateX,
    modelTransform.translateY,
    modelTransform.translateZ
    )
    .scale(
    new THREE.Vector3(
    modelTransform.scale,
    -modelTransform.scale,
    modelTransform.scale
    )
    )
    .multiply(rotationX)
    .multiply(rotationY)
    .multiply(rotationZ);
    
    this.camera.projectionMatrix = m.multiply(l);
    this.renderer.state.reset();
    this.renderer.render(this.scene, this.camera);
    this.map.triggerRepaint();
    }
    };
    
    map.on('style.load', function () {
    map.addLayer(customLayer, 'waterway-label');
    });

```

**Comment by rcorbari** [comment]
Hi. It sounds like there is an issue with Mapbox EPSG reference. Since you are using a common coordinates reference system, all the objects (like raster maps or vectors/CAD) with the same EPSG must be placed in the correct position on the map.
We work daily with files produced by different softwares, and we put them all together into the same "master" project, and we never found this kind of problem. This is why (EPSG) coordinates reference systems exist.
So your model's XYZ 0,0,0 is set - in this case - to the same origin as [EPSG:3857](https://epsg.io/3857)and the position - in meters - should be correct.

If not, this means that something with Mapbox reference system is wrong. For instance, you say that Mapbox scales the reference to a value between 0 and 1, this means that Mapbox does not comply with the EPSG:3857.

I would suggest to get in touch with Mapbox engineers in order to understand why they states to use the 3857, while actually this is not true.

**Comment by ansis** [comment]
@dprovasoli would it be possible to share an example model to help us debug this?

I think no rotation would be correct: `var modelRotate = [0, 0, 0];`

I don't think this is the problem, but could you try having no rotation and removing the `-` here?
```diff
new THREE.Vector3(
    modelTransform.scale,
-    -modelTransform.scale,
+   modelTransform.scale,
    modelTransform.scale
)
```

**Comment by dprovasoli** [comment]
I have tried no rotation and removing the `-` already without success. 
I suspect the issue lies in the scaling to 'Mapbox units'. This varies with latitude but my latitude values are in meters with respect to the (0°,0°) geographical origin, which is on the order of 1249035 meters away, hence spanning many latitude zones.

Unfortunately, all the models I am working with right now belong to our clients and I cannot share them. Sorry.

Thanks!

**Comment by boraerden** [comment]
Reopening this issue as I am dealing with the same roadblock. Hoping someone can lend a helping hand :)

I created a dummy [.obj file](https://gist.githubusercontent.com/boraerden/682c7775e00562bc37d9764ed019ecb5/raw/62e90009c7a7e111777a273a0e7f58a40eb6d412/paris_31n_points.obj) that contains 6 vertices (outlining an island in Paris and creating an extruded shape) in [EPSG:32631 WGS 84 / UTM zone 31N](https://epsg.io/32631).

Here is a similar dummy [.obj file closer to world origin](https://gist.githubusercontent.com/boraerden/21b535c722fa7cf758bd22b9385fe4cf/raw/2d14c7410be0951d1ca5ef707ac3a019e83620d3/paris_31n_points_near_center.obj) for debugging purposes.

The desired outcome is something like this:
![desired outcome](https://user-images.githubusercontent.com/7088004/149232308-534b33e3-b5c9-4230-829c-fccb4da6a314.png)

I created a [codepen](https://codepen.io/boraerden/pen/eYGQbrX) for ease of debugging.

Any help would be appreciated!
