### ISSUE TITLE
Custom markers throw error on map zoom event v2.1.1 "cannot read property "tranform" of undefined"

### ISSUE THREAD

**Issue by ajbraudev** [mapbox/mapbox-gl-js#10402]
We are using Mapbox gl js with react and nextjs. 
After adding these markers to the map, on a zoom event, we are seeing this error:
Unhandled Runtime Error
TypeError: Cannot read property 'transform' of undefined
Call Stack
na._onOcclusionTimer

it is not a breaking error, everything is running smoothly, but we still get that error, and this error is not caught by the map.on('error') handler. (That would be sufficient for now just to have that work).

import { render } from "react-dom";
const markerEl = new mapboxgl.Marker().setLngLat(marker.lng_lat).addTo(map);

            render(
                <SquareMapIcon id={marker.id} color={marker.color} Icon={WanderIcons[marker.icon]} />,
                markerEl.getElement(),
            );
            
This was working on version 1, and is no longer working on v2
            
            
            markerEl.markerId = marker.id;`

**Comment by mourner** [comment]
Looks like a bug that occurs because we don't clear this timeout when a marker is removed:

https://github.com/mapbox/mapbox-gl-js/blob/b66fb775ad8dbc677a70b1ebd949509dc06ed3c2/src/ui/marker.js#L445

Should be an easy fix on our side, but meanwhile, you can work around this by clearing the timer manually when a marker or a map its added to is removed:

```js
clearTimeout(marker._occlusionTimer);
```

**Comment by ajbraudev** [comment]
> Looks like a bug that occurs because we don't clear this timeout when a marker is removed:
> 
> https://github.com/mapbox/mapbox-gl-js/blob/b66fb775ad8dbc677a70b1ebd949509dc06ed3c2/src/ui/marker.js#L445
> 
> Should be an easy fix on our side, but meanwhile, you can work around this by clearing the timer manually when a marker or a map its added to is removed:
> 
> ```js
> clearTimeout(marker._occlusionTimer);
> ```

That workaround works great, thank you so much!
