### ISSUE TITLE
Source tile unable to parse Relative URL

### ISSUE THREAD

**Issue by ClassicSours** [mapbox/mapbox-gl-js#10407]
I'm trying to work around https://docs.mapbox.com/help/troubleshooting/cors-errors/ in order to get some vector tiles working in my application.  I'm able to proxy requests to the server using @deck.gl/geo-layers TileLayer, as well as in mapStyle for raster tiles, but for vector tile sources it errors as follows:

Firefox:
![image](https://user-images.githubusercontent.com/15790261/108882111-a611e900-75c9-11eb-84a1-562f801d9900.png)
Chrome:
![image](https://user-images.githubusercontent.com/15790261/108882226-c5107b00-75c9-11eb-94a1-6f56eeee20eb.png)

directly hitting the actual URL results in CORS issues, so proxying through the express server, or reconstructing all the layers with deck.gl layers instead of mapbox layers seems to be the only workarounds I can think of for this issue.

**Comment by karimnaaji** [comment]
@ClassicSours do you have a small example you could share with us to help troubleshoot this? We usually share such examples in jsfiddle or codepen.

**Comment by asheemmamoowala** [comment]
Relative URLs are not supported @ClassicSours. See https://github.com/mapbox/mapbox-gl-js/issues/3636#issuecomment-261119004 for reasons why we don't support this. 

You may try to use placeholder URLs in your source definition and edit them right before requests are made by using the Map's transforRequest construction option which allows you to modify the [RequestParameters](https://www.mapbox.com/mapbox-gl-js/api#requestparameters) prior to a request being fetched.
