### ISSUE TITLE
Incorrect serialize() in 'raster-dem' source results in wrong diff computation of two equal stylesheets

### ISSUE THREAD

**Issue by bolatuly** [mapbox/mapbox-gl-js#10416]
It seems like there is a bug in the implementation of the raster dem tile source. At least that's as far as I've been able to boil down the repro case so far.

The presence of any attribute except `url, tileSize, tiles, bounds, encoding` (or removing one of them) causes an update of the style's state when applying the same style again.
Seems like removing (i.e using parent's one) [serialize()](https://github.com/mapbox/mapbox-gl-js/blob/35b26521ab3082c27b0762bdeb362ee748ad1fd8/src/source/raster_dem_tile_source.js#L31) solves a problem.

mapbox-gl-js version: 2.1.1

### Link to Demonstration
map 'jumps' on setStyle()
https://codepen.io/bolatuly/pen/KKNQqaE

**Comment by karimnaaji** [comment]
Thanks for the details @bolatuly , it seems like some option fields were newly added to the RasterDEMSourceSpecification but not reflected back in the serialized function. Could you confirm that this commit https://github.com/mapbox/mapbox-gl-js/commit/36495f137eef99d2de672738896e1b149c3fa7aa fixes your use case?

**Comment by exe-dealer** [comment]
@karimnaaji why not just completly remove `serialize` function from `RasterDEMTileSource`? Base class of `RasterDEMTileSource` already has the same `serialize` function as you commited

**Comment by karimnaaji** [comment]
@exe-dealer yes good point I did not notice! it can be entirely removed.

**Comment by bolatuly** [comment]
@karimnaaji thanks, it works now as expected

**Comment by karimnaaji** [comment]
Closed via #10418
