### ISSUE TITLE
clusterRadius=0 has bigger radius than clusterRadius=1

### ISSUE THREAD

**Issue by enersis-pst** [mapbox/mapbox-gl-js#10426]
**mapbox-gl-js version**: 2.1.1

**browser**: chrome

### Steps to Trigger Behavior

 1. set clusterRadius by 0
 2. have some points next to each others

### Link to Demonstration
https://jsbin.com/bawahotome/edit?html,output
https://jsbin.com/bawahotome/1/edit?html,output

### Expected Behavior
1. cluster only points **with same coordiantes**,
2. radius is smaller than clusterRadius 1

### Actual Behavior
1. cluster neighbor points
2. radius is higher than clusterRadius 1

**Comment by mourner** [comment]
Yeah, there's a small bug here:

https://github.com/mapbox/mapbox-gl-js/blob/e1942b33221e0a84e117642c5c31204a29dbd0c9/src/source/geojson_source.js#L141

It falls back to 50 when it's 0, but it should only do it when it's `undefined`. You're welcome to submit a PR for this, but meanwhile you can just use a small non-zero value such as `0.01` as a workaround.

**Comment by enersis-pst** [comment]
hope thats the right way :-)
https://github.com/mapbox/mapbox-gl-js/pull/10427
