### ISSUE TITLE
Clustering causes points to be quantized

### ISSUE THREAD

**Issue by kbrownlees** [mapbox/mapbox-gl-js#10422]
Apologies if this is documented somewhere and I missed it?

**mapbox-gl-js version**: 2.1.1
**browser**: Chrome

### Steps to Trigger Behavior

 1. Add a geojson source of points with clustering enabled
 2. Display the source
 3. Observe that the points get quantized and snapped to a grid

### Expected Behavior

The points should be displayed in the correct position.

### Actual Behavior

The points gets displayed snapped to a grid.

### Discussion

Having done some digging this appears to be because supercluster is using 32bit numbers (by calling `Math.fround`).

example: the gps longitude values from `173.189049` -> `173.189064` all have a `Math.fround` result of `173.18905639648438`. The difference between `173.189049` & `173.189064` is ~2.25m at my latitude.

It would good to at least include this in the documentation so you know that clustering is not useful in situations where accuracy is important.

Edit: looking at the commits in supercluster this was actually changed last month? https://github.com/mapbox/supercluster/commit/592d0665d344e7306dcfaf958a9bb04098656475. For us this is certainly a regression in behaviour.

**Comment by mourner** [comment]
The coordinates of points and clusters in Supercluster were always stored as Float32 in the internal index, the recent commit just made the rounding more internally consistent to fix a bug. However, we may be able to fix the precision for non-clustered points — let me look into this.

**Comment by mourner** [comment]
@kbrownlees I have pushed a potential fix to https://github.com/mapbox/supercluster/commit/96ac4caaa00e13b4aa2588799d65d72f362dfbc3 — can you give it a go in your app to confirm if it helps?

**Comment by kbrownlees** [comment]
> @kbrownlees I have pushed a potential fix to [mapbox/supercluster@96ac4ca](https://github.com/mapbox/supercluster/commit/96ac4caaa00e13b4aa2588799d65d72f362dfbc3) — can you give it a go in your app to confirm if it helps?

@mourner that branch has the the same behaviour as master for me.

Downgrading to `2.0.1` fixes this issues in our use case so something appears to have changed in the latest release..

**Comment by mourner** [comment]
@kbrownlees that's quite puzzling! Would you be able to set up a minimal live test case so that I could reproduce the issue then?

**Comment by kbrownlees** [comment]
> @kbrownlees that's quite puzzling! Would you be able to set up a minimal live test case so that I could reproduce the issue then?

@mourner is there any recommended platform to easily stand up a mapbox-gl instance for demoing something like this? Tried my usual suspects but none of them worked..

**Comment by rreusser** [comment]
@kbrownlees Does something like codepen work, e.g. https://codepen.io/rsreusser/pen/poNZrvO ?

**Comment by kbrownlees** [comment]
@rreusser thanks for that, tried a bunch of things except codepen..

@mourner https://codepen.io/kbrownlees/pen/QWGPpqe reproduces it for me. The cluster of 4 positions by the corner are the most obvious:

Using 2.1.1:

![image](https://user-images.githubusercontent.com/641520/111255745-89bf1480-867c-11eb-9cb9-c80372fd9096.png)

Using 2.0.0:

![image](https://user-images.githubusercontent.com/641520/111255788-9ba0b780-867c-11eb-812e-480026f2ec51.png)

**Comment by mourner** [comment]
The image below is using the latest `main` build but with `supercluster` pointing to the branch from https://github.com/mapbox/supercluster/pull/176, so the latter does appear to fix the issue. Since you stated that it doesn't for you, could you please check again — perhaps the GL JS build on your side didn't incorporate the change properly? 

I'm testing this by doing `yarn link` in the `supercluster` repo with the branch, then doing `yarn link supercluster` in `mapbox-gl-js` and then `yarn run build-prod-min` to make a `dist/mapbox-gl.js` build with the fix.

![image](https://user-images.githubusercontent.com/25395/111281426-983e0980-8645-11eb-937c-9e622f6ee5ac.png)

**Comment by kbrownlees** [comment]
Apologies @mourner, I didn't realise you were bundling dependencies into your npm dist package. So I incorrectly assumed I could just update my supercluster version and have it get picked up. Fix appears to be working by the looks of your screenshot, thanks for the quick replies on this.
