### ISSUE TITLE
What is mapbox-gl-csp-worker.js in Webpack bundle analyzer?

### ISSUE THREAD

**Issue by mmz15** [mapbox/mapbox-gl-js#10424]
**mapbox-gl-js version**:

### Question

Like many before me, I've gotten to the point in my project that I am trying to slim down my bundle size.

What I don't understand is that I have two different kinds of Mapbox. When analyzing my bundle with Webpack bundle analyzer:

Mapbox 1:

<img width="286" alt="Screen Shot 2021-03-02 at 07 26" src="https://user-images.githubusercontent.com/69217396/109734799-9e38e280-7b8f-11eb-8c5e-2abe7e449b5f.png">

Mapbox 2:

<img width="472" alt="Screen Shot 2021-03-02 at 07 26 1" src="https://user-images.githubusercontent.com/69217396/109734807-a09b3c80-7b8f-11eb-852f-ac791ff852ca.png">

I don't understand the purpose of the second Mapbox. What is mapbox-gl-csp-worker.js and how does that differ from mapbox-gl.js?

I won't get into Mapbox's size. That's a discussion for a different thread. But I just want to understand where my bundle size is going.

**Comment by asheemmamoowala** [comment]
> I don't understand the purpose of the second Mapbox. What is mapbox-gl-csp-worker.js and how does that differ from mapbox-gl.js?

The `csp` variant of the gl libraries was added to address environments with strict content security policies by separating the main bundle and the worker bundle into separate script files. See the [Transpiling and CSP](https://docs.mapbox.com/mapbox-gl-js/api/#transpiling-v2) documentation for more info.

If you are using the default `mapbox-gl.js` bundle, you don't need to include any other `js` files from the `dist\` folder in your bundle.
