### ISSUE TITLE
Question: Cluster aggregate string properties to uniqual string array  

### ISSUE THREAD

**Issue by enersis-pst** [mapbox/mapbox-gl-js#10425]
### Question

i want to use `clusterProperties` to create aggregation of a string property. And i want to ask if it is possible to merge them to a uniqual array.

For example
```
features: [
{ properties: { state: "a"}},
{ properties: { state: "a"}},
{ properties: { state: "b"}}
]
```

`clusterProperties `should return for a cluster of alle of these: ["a", "b"]

**Comment by mourner** [comment]
Unfortunately there's no way to do that with Mapbox expressions. However, if you know all possible values beforehand, you could define a property that tells if any of the children have a certain value or not:

```js
"clusterProperties": {
  "has_a": ["any", ["==", ["get", "state"], "a"]],
  "has_b": ["any", ["==", ["get", "state"], "b"]],
  ...
}
```
