### ISSUE TITLE
Trying to load layer from the 3D terrain example shows CORS error

### ISSUE THREAD

**Issue by risharde** [mapbox/mapbox-gl-js#10421]
I'm having this issue even using this official example from mapbox
https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/

When I add the code to my instance, I get the cors warning:
"...has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

Any ideas how I can get around this issue?

**Comment by asheemmamoowala** [comment]
Thank you for your opening this ticket. To help the maintainers and community understand and address the problem accurately can you please provide a minimal, complete, verifiable demonstration of the issue. We recommend using https://jsbin.com. Please also include information about the browser version and operating system used where applicable.

**Comment by osavelieva** [comment]
@asheemmamoowala the issue can be reproduced in the official example at https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/ Drag and zoom the map every so often and the error would be there soon enough.

![image](https://user-images.githubusercontent.com/45556723/112118818-6d176500-8bc5-11eb-8413-d035d080faeb.png)

Here's an example of a request that returns CORS error:
```
curl 'https://api.mapbox.com/raster/v1/mapbox.mapbox-terrain-dem-v1/2/1/2.webp?sku=101H2Svt22YYl&access_token=pk.eyJ1IjoiZXhhbXBsZXMiLCJhIjoiY2p0MG01MXRqMW45cjQzb2R6b2ptc3J4MSJ9.zA2W0IkI0c6KaAhJfk9bWg' \
  -H 'Connection: keep-alive' \
  -H 'accept: image/webp,*/*' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57' \
  -H 'DNT: 1' \
  -H 'Origin: https://docs.mapbox.com' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Referer: https://docs.mapbox.com/' \
  -H 'Accept-Language: en-US,en;q=0.9,ru;q=0.8' \
  --compressed
```

The response headers do not have `Access-Control-Allow-Origin` for some reason even though other tiles have it.

**Comment by asheemmamoowala** [comment]
Thanks for this report @risharde and @osavelieva ! I've forwarded the issue to the internal team that owns the `https://api.mapbox.com/raster/v1/mapbox.mapbox-terrain-dem-v1` service. 

Since there are no further actionable tasks on this ticket with regard to this repo, I'm going to close out this ticket.

**Comment by Zandor300** [comment]
In my case Sentry SDK was adding the `sentry-trace` and `baggage` headers to requests to api.mapbox.com. When I fixed the `tracePropagationTargets` array regex, it was no longer adding this to the Mapbox requests and the terrain DEM tiles load correctly.
