### ISSUE TITLE
supported check doesn't work correctly

### ISSUE THREAD

**Issue by ArtemAstakhov** [mapbox/mapbox-gl-js#10435]
**mapbox-gl-js version**: v2.1.1

**browser**: Microsoft Edge 44.19041.423.0

### Steps to Trigger Behavior

 1. Open mapbox test page

### Link to Demonstration

https://docs.mapbox.com/mapbox-gl-js/example/check-for-support/

### Expected Behavior

Page should show an alert

### Actual Behavior

Empty map

**Comment by ryanhamley** [comment]
Edge 44 is the older IE engine which GL JS dropped support for with v2.0.0. GL JS is fully compatible with Chromium-based Edge versions. I'd suggest updating to a newer version of the browser if possible; I confirmed that newer Edge versions do not replicate this issue.

**Comment by ArtemAstakhov** [comment]
@ryanhamley 
I agree that this is an old version, but this should be mentioned to users and mapbox has a .supported method for this purpose, but it doesn't work

**Comment by ryanhamley** [comment]
@ArtemAstakhov do you get any errors in the console?

**Comment by ArtemAstakhov** [comment]
@ryanhamley none
