### ISSUE TITLE
icon-halo showing up as a solid square for SDF-enabled PNGs

### ISSUE THREAD

**Issue by monicapoletti** [mapbox/mapbox-gl-js#10449]
I'm trying to use the icon-halo-width/color properties to make a border around some icons on my map. Even though the icon is a PNG with no background and enabled for SDF, the icon halo at any width is always just a square. I tried out my logic using the shop-15.png icon in your [recolorable icons tutorial](https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/#using-sdf-enabled-images), but I got the same result, just a white square instead of bordering the icon. 

**mapbox-gl-js version**: 2.0.1

**browser**: Chrome

### Steps to Trigger Behavior

1. Add a GeoJson source of individual data points to the map
2. Load a single-color PNG image and add to map with SDF enabled
3. Add a layer to display your point source using the loaded icon image as the markers
4. Set icon-halo-width and icon-halo-color to try to get a border on the icons.

Code snippet here:
```
map.addSource('tree-points', {
  type: 'geojson',
  data: treePoints,
  maxzoom: 30, // Set max zoom level of source in order to set clusterMaxZoom appropriately
  cluster: true,
  clusterMinPoints: 3,
  clusterMaxZoom: 30, // Don't cluster if zoomed in higher than this level
  clusterRadius: 40 // Radius of each cluster when looking for points
});

map.loadImage("/assets/mapbox/map_marker.png", (error, image) => {
  if (error) throw error;
  map.addImage('tree-marker', image, { sdf: true });
  map.addLayer({
    id: 'unclustered-points',
    type: 'symbol',
    source: 'tree-points',
    filter: ['!', ['has', 'point_count']],
    layout: {
      'icon-image': 'tree-marker',
      'icon-size': 0.30,
      // Get the tree price from the source's "price" property.
      'text-field': ['get', 'price'],
      'text-font': ['EB Garamond SemiBold'],
      'text-size': 15,
      'text-offset': [0, -0.20]
    },
    paint: {
      'icon-halo-width': 4,
      'icon-halo-color': 'white',
      'icon-color': 
      ['case',
        ['boolean', ['feature-state', 'hover'], false], '#fd7e14',   // $orange
        ['boolean', ['feature-state', 'active'], false], '#fd7e14',  // $orange
        '#259a84',
      ],
      'text-color': 'white'
    }
  });
});
```

### Link to Demonstration

Screenshots using my icon and the shop-15.png icon from the docs.Mapbox.com tutorial:
<img width="359" alt="Screen Shot 2021-03-09 at 4 19 14 PM" src="https://user-images.githubusercontent.com/3247994/110559460-19067e00-80f9-11eb-9077-b1b024ca01a6.png">
<img width="368" alt="Screen Shot 2021-03-09 at 4 50 35 PM" src="https://user-images.githubusercontent.com/3247994/110559462-1a37ab00-80f9-11eb-8bc5-09fce5dde33b.png">

### Expected Behavior

The icons would have a border around them that is n pixels wide, where n is set by icon-halo-width. This border should be fitted to the curves of the icon.

### Actual Behavior

The icons get a square around them instead of a fitted border.

**Comment by arindam1993** [comment]
@monicapoletti This seems to be an issue with the SDF asset in the tutorial. There doesnt seem to be a smooth transition around the edge of the icon see [here](https://mapbox.github.io/tiny-sdf/) for reference on how SDF's should look inorder to support halos.
