### ISSUE TITLE
Interactive Titles of 10m x 10m 

### ISSUE THREAD

**Issue by waqas740** [mapbox/mapbox-gl-js#10443]
How can we set 10 x 10 tiles on the whole map and we need title numbers and coordinates when users will select their titles. 
could someone help me with how we can do this?

**Comment by ryanhamley** [comment]
Hi @waqas740 unfortunately it's not clear what you're trying to achieve from your brief description. Also, this issue tracker is for reporting bugs and requesting features in GL JS. We cannot offer general support in this channel. For "how to" questions like this, I suggest contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks.
