### ISSUE TITLE
Set baseApiUrl when dynamically importing

### ISSUE THREAD

**Issue by m-vo** [mapbox/mapbox-gl-js#10452]
**mapbox-gl-js version**: 2.1.1

### Question
I need to proxy all requests to the mapbox API through a transparent proxy (for GDPR reasons). While setting the `baseApiUrl` works when using `require` it cannot be done when dynamically importing (webpack):

```js
const mapbox = await import('mapbox-gl');
mapbox.baseApiUrl = 'https://foo'; // TypeError: Cannot set property baseApiUrl of [object Module] which has only a getter

const map = new mapbox.Map();
// …
```

Could this become another constructor option for `Map` or is there another way to achieve this?

It's very well possible be that I'm overlooking or misunderstanding something. :relaxed:

**Comment by asheemmamoowala** [comment]
You can use the `transformRequest` constructor option as documented in https://github.com/mapbox/mapbox-gl-js/issues/9740#issuecomment-636129589.

**Comment by JuanIrache** [comment]
This isn't working with the standard map style. There are multiple calls to events.mapbox.com and even api.mapbox.com that aren't going through transformRequest, so you can't hide the token from the front-end and replace it in a server-side proxy.

```
const mapBox = new mapboxgl.Map({
          accessToken: 'dummy-token-will-replace-in-server',
          container: 'mapbox',
          style,
          center: [lon, lat],
          zoom,
          pitch,
          bearing,
          language,
          interactive: false,
          trackResize: false,
          preserveDrawingBuffer: true,
          performanceMetricsCollection: false,
          transformRequest: url => {
              const match = url.match(/^https:\/\/(.+)\.mapbox\.com\b/);
              if (match) {
                const subdomain = match[1];
                url =
                  url.replace(match[0], SERVERMAPBOX) +
                  `&subdomain=${subdomain}`;
              }
              return { url };
            };
        });
```
