### ISSUE TITLE
Arabic words are in opposite order and they are not readable

### ISSUE THREAD

**Issue by malik446644** [mapbox/mapbox-gl-js#10459]
**mapbox-gl-js version**: v2.1.1

**browser**: brave

### Steps to Trigger Behavior

 1. open map
 2. you will see unreadable Arabic words for Arab countries

### Image for Demonstration

![image](https://user-images.githubusercontent.com/59079190/110842605-97a11e00-82a7-11eb-8d10-8aa84929033f.png)

### Expected Behavior
العربية
### Actual Behavior
ﺔﻴﺑﺮﻌﻟﺍ

**Comment by ryanhamley** [comment]
You'll need to include the [RTL Text Plugin](https://github.com/mapbox/mapbox-gl-rtl-text) in order to correctly display Arabic.

**Comment by malik446644** [comment]
thanks @ryanhamley 
## example:
this is an example of how to implement it https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/
