### ISSUE TITLE
mapbox.LatLng undefined is not a function

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1045]
Hi and thanks for the great app.

I have an annoying error in chrome console, saying mapbox.LatLng is undefined, but still it seems to work. Maybe a browserify issue? I attach some pictures:

![undef](https://cloud.githubusercontent.com/assets/2299642/6471191/5ad866c0-c1e9-11e4-91b4-2d2cec22a0e0.gif)
![latlng](https://cloud.githubusercontent.com/assets/2299642/6471196/604ca9a4-c1e9-11e4-89bb-11eccdc46753.gif)

Thanks for any insight

**Comment by jfirebaugh** [comment]
Can you provide a link to a live example please?

**Comment by misterfresh** [comment]
Link to live example : http://france2100.com/

**Comment by jfirebaugh** [comment]
Thanks, that helps. You are running into #787 -- currently mapbox-gl-js cannot be included in a browserify bundle. You should require it as a standalone script.
