### ISSUE TITLE
Terrain Demo Not Working

### ISSUE THREAD

**Issue by jleppert** [mapbox/mapbox-gl-js#10465]
The terrain demo here isn't working: https://labs.mapbox.com/bites/00332/#12.1409/38.4357/-106.9449/52.8028/36

It is not loading the tiles and some of the resources.

![Screenshot_2021-03-12_17-11-26](https://user-images.githubusercontent.com/120971/111013892-1a80b200-8356-11eb-9258-92f40bb165a2.png)

**Comment by ryanhamley** [comment]
@jleppert That demo is made with mapbox.js not GL JS. AFAIK, mapbox.js isn't actively maintained anymore. As of v2.0.0 though, GL JS supports [3D terrain](https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/).

**Comment by mourner** [comment]
@ryanhamley mapbox.js is maintained (for simple raster-tile-only use cases). This demo (that also uses Three.js) doesn't fully work for unrelated reasons — it's very old and points to outdated tile endpoints.
