### ISSUE TITLE
calling map.remove() breaking with following error Cannot read property 'destroy' of undefined     at Map.remove()

### ISSUE THREAD

**Issue by kallesh111** [mapbox/mapbox-gl-js#10477]
Cannot read property 'destroy' of undefined
    at Map.remove (vendor.js:65)

**Comment by rreusser** [comment]
@kallesh111 are you able to provide a minimal reproducible example, perhaps something in the style of https://codepen.io/rsreusser/pen/oNYOLPz ? At a glance, it looks to me like `vendor.js` might be external code so that it's not clear to me that this is an issue with Mapbox. Thanks!
