### ISSUE TITLE
Fill antialiasing breaks for long lines in perspective view

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1047]
In perspective view, antialiasing breaks for long vertical edges. It doesn't interpolate v_pos linearly relative to screen space. Maybe interpolation happens before dividing by the `.w` component? Or maybe something else entirely?

![screen shot 2015-03-03 at 3 09 40 pm](https://cloud.githubusercontent.com/assets/1421652/6474648/73e56442-c1b7-11e4-877e-f0f9789086a0.png)

the difference between the interpolated y value and the gl_FragCoord y value:
![screen shot 2015-03-03 at 2 54 21 pm](https://cloud.githubusercontent.com/assets/1421652/6474500/243c5bb8-c1b6-11e4-82d9-2df8f8ccf57c.png)

http://stackoverflow.com/questions/24441631/how-exactly-does-opengl-do-perspectively-correct-linear-interpolation might clear up how interpolation works.

If there is no adjustment we can make to fix this, we could fix it by:
- resampling long segments when adding them to the buffers
- using triangles

**Comment by lucaswoj** [comment]
This seems to be much better now (or just very rare) 😄  
![screen shot 2016-07-28 at 3 08 51 pm](https://cloud.githubusercontent.com/assets/281306/17231186/3f03a498-54d5-11e6-9bae-7100e9610928.png)
