### ISSUE TITLE
Is there a way to place labeled 3D point and labeling 3D building with floor numbers in mapbox gl

### ISSUE THREAD

**Issue by gireeshbhogireddy** [mapbox/mapbox-gl-js#10483]
3D point should be plotted and also to be labeled with name.
Floor numbers of 3D building to be placed at every floor.
As far as i explored in map box gl documentation only extruding polygons is possible. Is there a way for point features and labels to be plotted in 3D space.

**Comment by ansis** [comment]
There is currently no way to set elevation for symbols but this is something we would like to add. We have https://github.com/mapbox/mapbox-gl-js/issues/3993 that covers adding this for symbols and other layer types.  I'll close this issue to avoid duplicates. Thanks!
