### ISSUE TITLE
Measure Radius by Distance

### ISSUE THREAD

**Issue by jennynottingham** [mapbox/mapbox-gl-js#10482]
## Motivation

The cluster radius is currently based on pixels, which causes different screens to result in a different experience of pixel size.

## Design Alternatives

The request from the customer is to have the radius be measured by distance.

## Design

One method would be to calculate pixel size as a variable (height x width) and change cluster radius based on that pixel density. If the radius is measured by distance, it ensures the experience is the same on different monitors/screens. 

### Mock-Up

TBD

### Concepts

TBD

### Implementation

TBD 

cc: @mourner @allanwalkerit

**Comment by mourner** [comment]
I'm not sure I understand this correctly. How does a pixel-based radius change the experience on different screens? And what would it mean to cluster by distance — as in geographical distance? The latter would mean the clusters wouldn't adapt to zoom level, defeating the purpose of clustering.

**Comment by mourner** [comment]
Closing this for now because there seems to be no follow up, but let's possibly reopen when we have more specific requirements from the customer.
