### ISSUE TITLE
Cannot find module 'worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker' in Jest test

### ISSUE THREAD

**Issue by chanan** [mapbox/mapbox-gl-js#10487]
**mapbox-gl-js version**: 2.1.1

**browser**: N/A

### Steps to Trigger Behavior

 1. inside a Create React App use the instruction found here to make a mapbox component: https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/
 2. Create a test for your component
 3. run "yarn test" - or what ever package manager you use
 4.  See the error for example:

```
    Cannot find module 'worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker' from 'src/lib/components/mapBox/Mapbox.js'

    Require stack:
      src/lib/components/mapBox/Mapbox.js
      src/lib/components/mapBox/MapBoxGl.js
      src/lib/components/msp-order-invoice/create-order-invoice/targeting-tracking/targeting/location-targeting/LocationTargetingForm.js
      src/lib/components/msp-order-invoice/create-order-invoice/targeting-tracking/targeting/location-targeting/LocationTargeting.js
      src/lib/components/msp-order-invoice/create-order-invoice/targeting-tracking/targeting/TargetingContainer.js      src/lib/components/msp-order-invoice/create-order-invoice/targeting-tracking/targeting/Targeting.js
      src/lib/test/msp-invoice-order/create-invoice-order/targeting-tracking/targeting/Targeting.test.js

      2 | import mapboxgl from "mapbox-gl/dist/mapbox-gl-csp";
      3 | // eslint-disable-next-line import/no-webpack-loader-syntax
    > 4 | import MapboxWorker from "worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker";
        | ^
      5 | import _ from "lodash";
      6 |
      7 | import configData from "../../api-config/config";

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:306:11)
      at Object.<anonymous> (src/lib/components/mapBox/Mapbox.js:4:1)
```

### Link to Demonstration

https://github.com/chanan/mapbox-test-error

### Expected Behavior

No error should be thrown by the test

### Actual Behavior

An error is thrown and the test fail

### Linked Issue

I also open an issue in the Jest repo: https://github.com/facebook/jest/issues/11225

**Comment by chanan** [comment]
Added a link to a reproduction repo: https://github.com/chanan/mapbox-test-error

**Comment by chanan** [comment]
So according to this comment from the Jest repo: https://github.com/facebook/jest/issues/11225#issuecomment-804694640 - `moduleNameMapper` in `jest` needs to be configured to load `worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker` correctly, but I have no idea how to do that. Can you guys provide guidance on that?

**Comment by arindam1993** [comment]
Hey @chanan , Jest runs tests in Node, GL-JS is not designed to run in node since it has hard requirements of the DOM, WebGL, WebWorker's and other browser specific API's (localStorage, cache etc etc) that are not present out of the box in Node.

The `worker-loader` import fails because thats webpack specific syntax. If you're looking to run tests in jest, you'd have to setup a mock browser environment within node. We have some legacy code that does this can can be used as a starting point 
https://github.com/mapbox/mapbox-gl-js/blob/main/src/util/window.js

but that being said, we ourselves moved our tests to run in the browser to avoid relying on mocking like this.

**Comment by arindam1993** [comment]
https://github.com/tom-sherman/blog/blob/master/posts/02-running-jest-tests-in-a-browser.md#the-good-stuff

Might be a good starting point to setup karma with jest to get this running.

**Comment by chanan** [comment]
I was able to mock in Jest like so:

```
jest.mock("../../components/mapBox/Mapbox", () => () => <></>);
```
Replace the path with the path to your componnet from the test file
