### ISSUE TITLE
labels in perspective view

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1048]
In the current perspective implementation labels closer to the bottom are bigger and further back labels are smaller. Line labels are rendered skewed.

Why? because it was easier to implement it this way.

It's sort of cool that closer stuff is bigger, bit it also can make labels harder to read. Far labels can be tiny and close ones are giant. The skewness makes reading line labels even harder. The reading difficulty depends on text size and pitch steepness.

- Should line labels never get skewed? Would straight labels be preferable to curved but skewed labels?
- Should labels be the same size no matter their vertical position? This would mean that labels would show up and disappear as you pan. See apple maps for how this would look.

Example with altitude=1 pitch=50. This might be a bit more extreme than usual.
![screen shot 2015-03-03 at 7 17 45 pm](https://cloud.githubusercontent.com/assets/1421652/6477596/215cb0fe-c1da-11e4-80d3-d7196370f77f.png)

**Comment by peterqliu** [comment]
>Should line labels never get skewed?
I think tilt mode is used to emphasize the on-the-ground perspective, and inherently favors nearby things over faraway things. Toward this end, I think the skew is actually **good** because it affects nearby objects the least, thereby establishing this hierarchy of readability from `near > far`.

**Comment by mourner** [comment]
I also think the way it works in the current `perspective` branch is perfectly fine for now. Lets not worry about skewed labels readability until we solve higher priority issues.

> Would straight labels be preferable to curved but skewed labels?

No, it would be worse in my opinion.

**Comment by ansis** [comment]
Nothing actionable here right now. closing

**Comment by bsudekum** [comment]
@ansis I think we should revisit this issue and what a perspective-quest-round-two would look like. Two large issues I'm seeing with perspective:

1. Line labels should be rendered similar to POI labels. I.E. no skewing
2. Labels in the background are illegible. 
 * I think this will be fixed if 1 is fixed first. Even line labels near the middle of the screen are difficult to read.

**Comment by nickidlugash** [comment]
> Line labels should be rendered similar to POI labels. I.E. no skewing

:+1:

**Comment by lucaswoj** [comment]
We are making this behaviour configurable with `*-pitch-alignment` and `*-rotation-alighment` per https://github.com/mapbox/mapbox-gl-style-spec/issues/459
