### ISSUE TITLE
how to show markers on the visible area and lazy load others when the user zooms/navigates

### ISSUE THREAD

**Issue by bashasm** [mapbox/mapbox-gl-js#10490]
**mapbox-gl-js version**: 2.1.1

### Question
how to show markers on the visible area and lazy load others when the user zooms/navigates
When I centre the map, by the below code, I want to know the exact visible details so that I can show my points/markets on the map. Also, I would like to know the same for any zoom in/out/navigate by the user

```
this.map = new mapboxgl.Map({
      container: mapNode,
      style: this.style,
      center: this.center, // Chicago Airport
      pitch: this.pitch,
      zoom: this.zoom,
});

```

I tried these events on actual  Mapbox instance, but not getting the required information

```
this.map.on('zoomend', (event: any) => {
   console.log('zoomend', event);
});

this.map.on('zoom', (event: any) => {
   console.log('zoom', event);
});

this.map.on('zoomstart', (event: any) => {
   console.log('zoomstart', event);
});
```

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/api/events/

**Comment by bashasm** [comment]
any suggestions?

**Comment by asheemmamoowala** [comment]
@bashasm you can use the `Map#getBounds` and `Map#getZoom` methods to get the maps camera state after a `zoomend` event. This can also be used with a `moveend` event which is fired (almost) every camera state change.

**Comment by bashasm** [comment]
@asheemmamoowala 
Thanks, I was looking at` getBounds()` method

Do we need to always get the data from the server on the `getBounds()`? Do you think is there any way to avoid loading the same data using  `getBounds()`. Something like caching etc...

Pleae advise
