### ISSUE TITLE
refreshExpiredTiles not working when offscreenCanvasSupported

### ISSUE THREAD

**Issue by dannybloe** [mapbox/mapbox-gl-js#10491]
Hi folks,

We heavily rely upon the refreshExpiredTiles setting but since we moved to the latest and greatest (1.13.1) this no longer works. Turns out that when using offscreenCanvas all the cache headers no longer end up in setExpiryData. If we disabled offscreenCanvas support (window.OffscreenCanvas = null) this works again.

Danny

**Comment by andycalder** [comment]
Hi Danny, I've encountered this bug too. I assume you're talking about raster tiles? I just opened a PR to fix this.

**Comment by dannybloe** [comment]
Yes raster tiles indeed. Haven't tested it with vector just yet
