### ISSUE TITLE
setClickEventForLayer gives a unaccurate result when having multiple markers

### ISSUE THREAD

**Issue by iJoris** [mapbox/mapbox-gl-js#10497]
**mapbox-gl-js version**:  1.13.0.  

**browser**: Latest chrome

### Steps to Trigger Behavior

 1. Have multiple markers close to each other
 2. Click on a marker
 3. See that a different marker is selected then the cursor points to

### Link to Demonstration

![image](https://user-images.githubusercontent.com/11030139/112128501-c7fd8c00-8bc6-11eb-90f2-2ae06d30baed.png)
![image](https://user-images.githubusercontent.com/11030139/112128533-cfbd3080-8bc6-11eb-9445-e8a6f26224d3.png)

### Expected Behavior
The marker that is under the cursor is selected.

### Actual Behavior
A other marker is selected

**Comment by ryanhamley** [comment]
It's impossible to tell what's happening from screenshots. Can you provide an example of the problem using JSFiddle or a similar site?

**Comment by iJoris** [comment]
Found out that the issue was due to my markers not being transparent.
