### ISSUE TITLE
Mapbox gl native is not rendering all styles sources, causing missing map data

### ISSUE THREAD

**Issue by neelakandan-dhanigachalam** [mapbox/mapbox-gl-js#10507]
We are using tileserver-gl 3.0.0. We are having around 30 MBTiles and getting served without any issues with tileserver-gl 2.3.1. We have recently upgraded to tileserver-gl 3.0.0. But when we notice the maps data is missing intermittently, like one of the map sources are missing.

When we did a debugging, the mapbox-gl-native itself is not sending the source data calls.

Can anyone aware of the similar issue before or how can we identify why mapbox-gl-native is not calling the style sources?

tileserver-gl -3.0.0
mapbox-gl-native -5.0.2

Any assistance will be much appreciated.

Note: No error logs thrown from the tileserver-gl or mapbox-gl-native.

**Comment by ryanhamley** [comment]
@neelakandan-dhanigachalam This is the repository for GL JS. You're looking for [GL Native](https://github.com/mapbox/mapbox-gl-native/issues). But I would suggest reaching out to [Mapbox Support](https://support.mapbox.com/hc/en-us) before opening an issue there to see if Support can help resolve any issue in your setup.
