### ISSUE TITLE
setView should use current zoom, bearing, pitch if undefined

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1051]
From https://github.com/mapbox/mapbox-gl-js/pull/1049#discussion_r25761481

> This starts to get pretty inconvenient... Lets have setView use current zoom, bearing and pitch if undefined.

**Comment by ansis** [comment]
It might make sense to change both `setView` and `easeTo` to a single options argument to avoid having to remember to argument order and write lots of undefined.

Or maybe keeping view separate from transition options is good:` easeTo(view, options)`

**Comment by jfirebaugh** [comment]
```
map.jumpTo(options)
map.easeTo(options)
```

y/n?

**Comment by ansis** [comment]
What would the argument types look like on -native?
