### ISSUE TITLE
Animated points hide nearby points on zoom out

### ISSUE THREAD

**Issue by vigneshkrv** [mapbox/mapbox-gl-js#10513]
**mapbox-gl-js version**: 1.13

### Question
On animating a point with "pulse" effect, the nearby points disappear when you zoom out as the pulse effect of each points clash. Is there a way to avoid this?
![zoomed in](https://user-images.githubusercontent.com/42761544/112657370-5b7dc980-8e20-11eb-8a4b-342e3c58a97c.PNG)
![zoomed out](https://user-images.githubusercontent.com/42761544/112657454-72bcb700-8e20-11eb-85a4-5655870bf0f1.PNG)

**Comment by mourner** [comment]
See:
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-icon-allow-overlap
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-icon-ignore-placement
