### ISSUE TITLE
maps not working brave browser

### ISSUE THREAD

**Issue by primozs** [mapbox/mapbox-gl-js#10518]
**mapbox-gl-js version**:
latest

**browser**:
Brave
Version 1.22.70 Chromium: 89.0.4389.105 (Official Build) (x86_64)

### Steps to Trigger Behavior

 1. Install latest brave, 
 2. set browser fingerprinting to strict

### Link to Demonstration
https://www.mapbox.com/maps/light

Map is not displayed

import { supported } from '@mapbox/mapbox-gl-supported';

WebGl test does not return support.

Attached screenshot .
<img width="838" alt="Screenshot 2021-03-28 at 14 18 47" src="https://user-images.githubusercontent.com/1006789/112751905-a3435300-8fd0-11eb-9ecd-68788a237429.png">

**Comment by rreusser** [comment]
Hi, @primzos! Brave's strict mode is specifically labeled "Strict, may break sites", and from what I can tell by running [the check from mapbox-gl-supported](https://github.com/mapbox/mapbox-gl-supported/blob/214c1ed12dba316a6434469384010948354a8c69/index.js#L137-L180) directly, Brave in strict mode does not have the ability to compile and run shaders at all, to say nothing of minimal extension support ([it supports none](https://webglreport.com/)) or other capabilities. I'm a big fan of Brave, but as far as I know, Mapbox GL-JS in Brave's strict fingerprinting mode will always be a non-starter.

I think you'l need to either use standard fingerprinting mode (which seems to work for me) or find some other configuration which is acceptable for you.

**Comment by ryanhamley** [comment]
We've looked into this previously and Brave's more restrictive fingerprinting settings block WebGL functionality that GL JS relies on and for which there is no workaround. There's no way for us to address this behavior at this time. GL JS is not using this functionality to fingerprint anyone, but the browser doesn't distinguish between an application's calls to these APIs and fingerprinting attempts. You can read more in https://github.com/mapbox/mapbox-gl-js/issues/8377 and on Brave's [Github](https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections). It's also worth noting that this isn't limited to Brave. Any anti-fingerprinting application has the potential to break GL JS maps.

**Comment by mprove** [comment]
It seems to be getting better – apart from some nasty spike errors.

Screenshot of https://pratikyadav.github.io/maps/3d/#13.08/-0.70076/-78.44448/52/75 on Brave Version 1.25.70 Chromium: 91.0.4472.77 (Official Build) (x86_64):

![Spikes on Brave](https://user-images.githubusercontent.com/1712125/120880243-65167100-c5c9-11eb-8ff9-71a139845eed.jpg)
