### ISSUE TITLE
 Restrict heatmap to an arbitrary area

### ISSUE THREAD

**Issue by vadmbertr** [mapbox/mapbox-gl-js#10521]
Hi!

I'm using the heatmap layer and I would like to restrict the coloring to an arbitrary area (let say a polygon shape). To make it clearer: inisde the polygon coloring would follow the heatmap-color property of the layer and outside the polygon I'd like to have a transparent or greyed color. I also attached a picture reflecting it (note that the actual heatmap I have inside the polygon is quite different).
Is there any way I could do it?

Vadim
![heatmap](https://user-images.githubusercontent.com/36510417/112820833-50c46e00-9086-11eb-8a9b-1bbb7b108988.png)

**Comment by mourner** [comment]
Unfortunately you can't restrict the heatmap rendering to a particular polygon. What you can do is sort your dataset into two parts — with points inside and outside the polygon, and then create a heatmap layer for the first batch.

**Comment by vadmbertr** [comment]
Thanks for your reply. 
Such a solution won't help I think. Basically I would like to set the value of heatmap-density to 0 for all the area outside my polygon.
I tried to add a color stop at 0.001 with a transparent color but by doing so I also "cut" the heatmap for some areas inside the polygon when the density is low.

Would it be possible to overwrite the heatmap-density (I'm afraid not...)?

**Comment by vadmbertr** [comment]
I was also thinking about something like this. I will give it a try. Thank you for the replies.
