### ISSUE TITLE
satellite street v11 -- satellite image mismatch when zoomed in at Lat: 33.447908912712 Lng: -112.185739376236 .

### ISSUE THREAD

**Issue by AlexHtZhang** [mapbox/mapbox-gl-js#10528]
**mapbox-gl-js version**: v2.2.0 

**browser**: chrome

### Steps to Trigger Behavior

 1. in satellite-streets-v11, go to point Lat: 33.447908912712 Lng: -112.185739376236 at zoom level 14.49. 
 https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#14.49/33.45015/-112.18395
 2. zoom in, the 202 highway is gone in the satellite image.  https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#14.84/33.45188/-112.18803

### Link to Demonstration
zoom out  hgihway 202 presents in the satellite image.
https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#14.49/33.45015/-112.18395

zoom in  hgihway 202 is gone in the satellite image.
https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v11.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#14.84/33.45188/-112.18803

### Expected Behavior
Expected highway 202 in satellite image when zoomed in at Lat: 33.447908912712 Lng: -112.185739376236 .
### Actual Behavior
highway 202 is missing in satellite image when zoomed in at Lat: 33.447908912712 Lng: -112.185739376236 .

**Comment by karimnaaji** [comment]
Hi @AlexHtZhang , that's an issue with the underlying data, not with the library. I'll go ahead and close this ticket, but feel free to reach out to support@mapbox.com to report such data mismatch issues.
