### ISSUE TITLE
Marker not showing using forEach in useEffect

### ISSUE THREAD

**Issue by zekhoi** [mapbox/mapbox-gl-js#10538]
I am trying to add markers to map, the code is below

        const [countryData, setCountryData] = useState([])
        useEffect(() => {
            setPageIsMounted(true)
        
            const map = new mapboxgl.Map({
                container: "map",
                style: "mapbox://styles/mapbox/dark-v10",
                zoom : 1.5,
            });
            const fetchDataLocations = async () => {
                setCountryData(await fetchLocations())
            }    
            fetchDataLocations()
            countryData.map((country) => {
                // create the popup
                const popup = new mapboxgl.Popup().setHTML(`<div class="flex flex-row"><div class="flex-auto font-xl font-bold text-center"><img class="w-full border" src=${country.flag} alt=${country.country}> ${country.country}</div></div><div class="flex flex-row"><div class="flex-auto"> <a><i class="lni lni-heart-filled text-four mx-1 font-medium"></i>${country.cases.toLocaleString()}</a></div><div class="flex-auto"> <a><i class="lni lni-heart-filled text-blue mx-1 font-medium"></i>${country.deaths.toLocaleString()}</a></div><div class="flex-auto"> <a><i class="lni lni-heart-filled text-red mx-1 font-medium"></i>${country.recovered.toLocaleString()}</a></div></div><div class="flex flex-row"><div class="flex-auto text-center font-medium">Updated : ${(new Date(country.updated)).toDateString()}</div></div>`);
                // create DOM element for the marker
                const el = document.createElement("div");
                el.id = "marker";
                el.className = "lni lni-map-marker cursor-pointer text-blue font-black text-sm"
                
                // create the marker
                new mapboxgl.Marker(el)
                .setLngLat([country.longitude,country.latitude])
                .setPopup(popup) // sets a popup on this marker
                .addTo(map);
            })
        },[])

the code will work if i delete a row of code then i save it, and then i put the code back and save it. The marker will appear, but when i refresh the page the markers is not showing. 

*countryData state has 221 length of data when the page mounted, so the problem is not from there

**Comment by mourner** [comment]
Thank you for the report! However, it looks like an issue with your React code, not something on the Mapbox side. If I could guess by the cited code (although a live JSFiddle test case would be more helpful), I'd suggest it's likely due to the `countryData.map` loop running before the locations are fetched — `fetchDataLocations` is an async function but you're not waiting for it to finish before the loop.
