### ISSUE TITLE
Fill extrusions below sea level may be extremely tall.

### ISSUE THREAD

**Issue by rreusser** [mapbox/mapbox-gl-js#10532]
Some buildings below sea level end up very tall. I'm not sure the exact cause, but it seems reasonable to guess it's extending the top to sea level.

<img width="499" alt="Screen Shot 2021-04-01 at 11 15 30 AM" src="https://user-images.githubusercontent.com/572717/113337091-27048480-92dc-11eb-984f-5d5d2453e68f.png">

**mapbox-gl-js version**: 2.1.1 / main

**browser**: Chrome

### Steps to Trigger Behavior

 1. Navigate to location like Death Valley (elevation -282 ft), e.g. the debug page http://localhost:9966/debug/terrain-debug.html#16.27/36.457537/-116.86859/-45.6/45
 2. Turn on buildings

### Link to Demonstration

http://localhost:9966/debug/terrain-debug.html#16.27/36.457537/-116.86859/-45.6/45

### Expected Behavior

Buildings have realistic height

### Actual Behavior

Whether a data, interpretation, or rendering issue, building heights are not reasonable.

**Comment by ShareQiu1994** [comment]
After upgrading to 2.2.0, I had the same problem
The premise of this problem is to add terrain
![image](https://user-images.githubusercontent.com/19948086/113372605-a73def00-939b-11eb-891f-d3712738c34b.png)

**Comment by rreusser** [comment]
Re: passing comment about throwing an exception. Upon taking another look, I think I'm mistaken and there is not actually an error thrown.

**Comment by rreusser** [comment]
The offending code seems to be here:

https://github.com/mapbox/mapbox-gl-js/blob/d66ff288e7ab2e917e9e676bee942dd6a46171e7/src/data/bucket/fill_extrusion_bucket.js#L448-L454

Simply changing the type to int16 didn't help, which suggests the logic needs to be changed to `> INT16_MIN` rather than `> 0`.

**Comment by rreusser** [comment]
Not opposed to someone else tackling this, but started looking into this. Maybe another hour to nail down all the conditionals, but I think I can get this by just changing the type to a signed integer, as noted by @ansis.
