### ISSUE TITLE
How to use new contributions under the 3-Clause BSD license, without asking for permission on each PR

### ISSUE THREAD

**Issue by JannikGM** [mapbox/mapbox-gl-js#10543]
[Since the license change in mapbox 2.0](https://github.com/mapbox/mapbox-gl-js/issues/10162), mapbox is no longer under 3-BSD license.
The new license adds a lot of uncertainty for some users (due to it being revocable / temporary), so forks started to appear.

However, there have also been **valuable contributions** to mapbox 2.x where authors (mapbox employees or third parties) likely don't care about the license for their contribution.

Unfortunately, **nothing in the PR makes clear wether the author is open to the idea of relicensing their work for FOSS forks (like https://github.com/maplibre/maplibre-gl-js)**, which continue under the 3-BSD license that was being used for mapbox v1.x.

This makes it tedious to ask on each PR wether a 3-BSD project like maplibre can take these changes. It also adds overhead for contributors, where they have to submit their PR to multiple projects.

**Examples of changes which should potentially be under 3-BSD:**
- https://github.com/mapbox/mapbox-gl-js/pull/10558 (not merged at time of writing)
- https://github.com/mapbox/mapbox-gl-js/pull/10551
- https://github.com/mapbox/mapbox-gl-js/pull/10553 (not merged at time of writing)
- https://github.com/mapbox/mapbox-gl-js/pull/10096
- https://github.com/mapbox/mapbox-gl-js/pull/10557
- https://github.com/mapbox/mapbox-gl-js/pull/10546
- https://github.com/mapbox/mapbox-gl-js/pull/10530
- https://github.com/mapbox/mapbox-gl-js/pull/10525
- https://github.com/mapbox/mapbox-gl-js/pull/10531
- https://github.com/mapbox/mapbox-gl-js/pull/10524 (https://github.com/mapbox/mapbox-gl-js/pull/10526 &rarr; this change *is* under 3-BSD now)

I'd appreciate if mapbox maintainers figured out a good way that authors can signal that they are fine with use of their PR in 3-BSD projects.
If this does not happen, I assume that we'll see ongoing license discussions on merged PRs, either by people asking for the ability to relicense, OR, bots asking on behalf of people.
Asking on each 1.x relevant PR is certainly the route I plan to take if no solution is found.

**Potential solutions to avoid this:**
- Second CLA bot to also ask about 3-BSD use (ideal, allows per-PR decision wether code can be used for mapbox 1.x forks).
- Section in PR template so the authors themselves can state that 3-BSD use is fine (acceptable, but bad because users might ignore the template).
- Section in PR template which recommends 3-BSD projects to also submit PRs to (bad, because then we'd have to keep a list of projects and put burden on author).
- Add a section in the mapbox CLA to allow 3-BSD use of changes which weren't done by mapbox employees (bad, because it's probably difficult to differentiate mapbox employees, and legal wording might be diffcult; also some changes are by mapbox employees, but not worth protecting under the new license).
- Add a section in the mapbox CLA to allow unconditional 3-BSD use for commits after a specific date, to keep most 2.x features protected, but allow 3-BSD for patches and unrelated features (sounds difficult to implement).

**Comment by mourner** [comment]
> However, there have also been **valuable contributions** to mapbox 2.x where authors (mapbox employees or third parties) likely don't care about the license for their contribution.

This is not a reasonable assumption to make. The PRs that I backported to v1 adher to our publicly stated policy of supporting v1 with critical bugfixes for a limited time. We are not going to backport features and improvements.

> If this does not happen, I assume that we'll see ongoing license discussions on merged PRs, either by people asking for the ability to relicense, OR, bots asking on behalf of people. Asking on each PR is certainly the route I plan to take if no solution is found.

As a fervent open source advocate and contributor for 10 years now, I honestly do wish for the fork and its community to thrive, and want to help where I can, but demands in a tone like in this issue are not helpful.

It's unfair to ask us to take on extra burden for the benefit of a different project. Also note that if license-related comments under the project's PRs ever rise to the level of harassing contributors, we will have to act according to the project's [code of conduct](https://github.com/mapbox/mapbox-gl-js/blob/main/CODE-OF-CONDUCT.md).

**Comment by JannikGM** [comment]
> but demands in a tone like in this issue are not helpful.

I did not mean to demand anything. Sorry if this came across wrong.
I'm trying to find a solution that works for all parties so we can avoid administrative overhead.

> This is not a reasonable assumption to make. The PRs that I backported to v1 adher to our publicly stated policy of supporting v1 with critical bugfixes for a limited time. We are not going to backport features and improvements.

I understand; I specifically meant PRs which are of interest to 1.x forks (such as the ones mentioned above).

This already excludes many PRs (such as the recent changes to fog, terrain, etc. which mapbox explicitly wanted to have under the new license).

However, it does include some PRs which might not get backports by mapbox, due to them not being considered "critical bugfixes" by mapbox.
See my examples above, which did not receive backports yet (and where it is unreasonable to expect mapbox to spend time on backporting these to 1.x).

> It's unfair to ask us to take on extra burden for the benefit of a different project.

Yes. And that's why I'd like to find an automated solution for this, so we can avoid additional work for mapbox.

Ideally mapbox has to spent less time on backporting to v1.x if the community has permission to backport these changes.
Ideally follow-up changes in forks will remain compatible with mapbox 2.x so they can be upstreamed again.

> Also note that if license-related comments under the project's PRs ever rise to the level of harassing contributors, we will have to act according to the project's code of conduct.

Understood and agreed.
That's also why I'd prefer if mapbox decided for an acceptable solution to avoid that problem upfront.

**Comment by asheemmamoowala** [comment]
> I'd appreciate if mapbox maintainers figured out a good way that authors can signal that they are fine with use of their PR in 3-BSD projects.
> If this does not happen, I assume that we'll see ongoing license discussions on merged PRs, either by people asking for the ability to relicense, OR, bots asking on behalf of people.
> Asking on each 1.x relevant PR is certainly the route I plan to take if no solution is found.

I don't think it's fair to jump into this repo with requests pertaining to the MapLibre project, however we cant stop you from individually communicating with contributors outside of Mapbox repos. 

That said, contributors to mapbox-gl-js should not be harassed with repeated requests even outside this project. As already mentioned by @mourner we will treat harassment of our community members (where ever it may occur)  according to the project's [code of conduct](https://github.com/mapbox/mapbox-gl-js/blob/main/CODE-OF-CONDUCT.md).

**Comment by mourner** [comment]
> I specifically meant PRs which are of interest to 1.x forks (such as the ones mentioned above).  [...]
> Ideally mapbox has to spent less time on backporting to v1.x if the community has permission to backport these changes.

@JannikGM automating permissions for backports of v2 changes would be reasonable assuming Mapbox wants those changes regularly backported. What I don't understand is why MapLibre has to rely on watching Mapbox PRs and constantly asking for backports to make any kind of improvements, and why Mapbox has to accommodate this premise.

Isn't the whole idea to be an independent open source project, with its own maintainers, contributors, priorities and a different roadmap? I understand that it's excruciatingly difficult if at all possible to maintain a project of such complexity and depth without a ton of funding and a dedicated team of highly skilled engineers working on it for years. But relying on Mapbox to do this maintenance work is not a sustainable way to move the fork forward, nor is it fair.

In the same vein, aggressive promotion of the fork across Mapbox repositories by pinging people in PRs is not a sustainable way of building a contributor community. If the project is healthy, moving in the right direction and people want to use it, contributors will come naturally. It's a long and difficult process and there are no shortcuts.

> Ideally follow-up changes in forks will remain compatible with mapbox 2.x so they can be upstreamed again.

You seem to assume that Mapbox v2 is just a set of additional features on top of v1 in a separate part of the code, but the fact is the whole project is evolving fast — there are already plenty of core changes spread across the code, and we have big plans for further substantial architectural and performance improvements. This means that v2 codebase will diverge more and more with time, and at some point it will be technically impossible to reapply v2 changes on top of v1 and viсe versa.

So, instead of trying to cling to Mapbox v2 changes through automations, constant backport requests and poaching contributors, I would suggest focusing on building a sustainable independent project that doesn't have to rely on Mapbox to be successful.
