### ISSUE TITLE
Map loading in a strange size inside a Bootstrap modal.

### ISSUE THREAD

**Issue by joexn** [mapbox/mapbox-gl-js#10556]
**mapbox-gl-js version**: 2.1.1, through CDN.

**browser**: Safari & Chrome

### Steps to Trigger Behavior

 1. Click button to open modal
 2. On modal open event, load coordinates into map
 3. JS automatically displays modal and map displays in weird proportions

### Link to Demonstration

<img width="815" alt="Screenshot 2021-04-11 at 20 05 20" src="https://user-images.githubusercontent.com/17342019/114317755-82ffb200-9b01-11eb-881b-d75af841965d.png">

----

The weird thing about this is, the mapbox logo and question are present in the right places but the actual map says in the usual dimensions until the browser window size is changed. Even opening developer tools fixes the problem.

I have tried running an update on the map once the modal actually opens but nothing seems to work so far.

Any help would be great.

(I have moved the map away from the centre to hide the location as it's loading in my current location)

**Comment by joexn** [comment]
I forgot to point out that running `map.resize()` on the event that fires once the modal has been shown fixes things but it causes it to fix in front of the end user.

**Comment by arindam1993** [comment]
@joexn , I'm unable to repro any flashing when `map.resize()` is called.

Since resizing the map can be pretty slow, its up-to the user to either use `ResizeObserver` or use polling with setInterval to call `map.resize()`.

The best practice is to only call it at the end of animations and transitions.
