### ISSUE TITLE
_normalizeBearing kills rotations <4.5º and resets to north

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-js#1055]
When dragging the compass navigation control to rotate the map, rotations less than 4.5º are normalized to 0.

The relevant code in [js/ui/easings.js](https://github.com/mapbox/mapbox-gl-js/blob/241a07d0607447cbc393f2ccfab3f03e765ced13/js/ui/easings.js#L341-L348) (L341-L348):

```javascript
// convert bearing so that it's numerically close to the current one so that it interpolates properly
_normalizeBearing: function(bearing, currentBearing) {
    bearing = util.wrap(bearing, -180, 180);
    var diff = Math.abs(bearing - currentBearing);
    if (Math.abs(bearing - 360 - currentBearing) < diff) bearing -= 360;
    if (Math.abs(bearing + 360 - currentBearing) < diff) bearing += 360;
    return bearing;
},
```

Also see @mourner's original commit f5c640ab8f7e6fc1548735c091c36c5b4d04d1ec.

Personally, I view ignoring bearing changes that end ~±7º of north as a UX enhancement (mapbox/mapbox-gl-native/pull/938), but this current implementation acts on relative bearing changes and results in small rotations resetting the rotation entirely, regardless of the current bearing.

**Comment by jfirebaugh** [comment]
Hmm, this is not from `_normalizeBearing` but from a click event getting triggered on the button at the end of the gesture and thus resetting to north. Will fix.

**Comment by friedbunny** [comment]
That does make more sense, I figured I just wasn't seeing the problem with the math. Thanks @jfirebaugh, and sorry to impugn your arithmetic, @mourner. :wink:

As an aside, is there enough interest in non-bug-induced compass snapping that I should spin that off into its own discussion?

**Comment by jfirebaugh** [comment]
@friedbunny Yes, please open an issue.
