### ISSUE TITLE
Just start from v1.3.0, only the  symbol layer will get stuck. Does anyone know what's going on?

### ISSUE THREAD

**Issue by thomashooo** [mapbox/mapbox-gl-js#10554]
blow v1.2.0 everything is ok,I had test from v1.3.0~v2.2.0, the  symbol layer cannot update immediately ? (on iPhone 8, Especially in old devices)
Here is the demo, You can see the difference more clearly here (the airplane symbol layer update lag,  the circle layer is better,It's more different on mobile phones):
## test url:
[https://thomashooo.github.io/mapboxtest/](https://thomashooo.github.io/mapboxtest/)

## test gif:
<img src = "https://thomashooo.github.io/mapboxtest/demo.gif"/>

Does anyone know what's going on, thanks?

**Comment by thomashooo** [comment]
Maybe it's the poor performance of the mobile phone, the frequent use of animation, and the performance problems of high mapbox version. But how to follow the camera when symbol layer moving in high version？？
map.easeTo({center: point.features[0].geometry.coordinates,
		     bearing: point.features[0].properties.bearing,
		   essential: true // this animation is considered essential with respect to prefers-reduced-motion});

**Comment by arindam1993** [comment]
@thomashooo Could you please retry with v2.2.0? We added https://github.com/mapbox/mapbox-gl-js/pull/10417 which should have fixed this.

If you still see this, could you please point to a simple code snipped that reproduces the issue?

**Comment by thomashooo** [comment]
> @thomashooo Could you please retry with v2.2.0? We added #10417 which should have fixed this.
> 
> If you still see this, could you please point to a simple code snipped that reproduces the issue?

@arindam1993 thanks for comment,  v2.2.0 become much better, but not good as v1.2.0, any ideas？here is comparison，you can see diff just open blow url in safari：
1.2.0 VS 2.2.0: https://thomashooo.github.io/mapboxtest/index.html

simple code(just add a easeTo in official demo: https://docs.mapbox.com/mapbox-gl-js/example/animate-point-along-route/):
`
//official demo sinip:
map.getSource('point').setData(point);
//simple code
map.easeTo({center: point.features[0].geometry.coordinates,
		     bearing:point.features[0].properties.bearing,
		   essential: true // this animation is considered essential with respect to prefers-reduced-motion
		});
`

**Comment by thomashooo** [comment]
> @thomashooo Could you please retry with v2.2.0? We added #10417 which should have fixed this.
> 
> If you still see this, could you please point to a simple code snipped that reproduces the issue?

problem still exists in 2.5.1：
https://thomashooo.github.io/mapboxtest/symbolTest.html#v=1.2.0
https://thomashooo.github.io/mapboxtest/symbolTest.html#v=2.5.1
