### ISSUE TITLE
[Urgent] Issue of showing uploaded GeoTIFF tilesets

### ISSUE THREAD

**Issue by forfullstack** [mapbox/mapbox-gl-js#10560]
I have to show Geo TIFF files(really one JPG file and more TIF files) on the map. They are high resolution files taken by drone.
I followed to "Upload a tileset to Mapbox with the Uploads API" https://docs.mapbox.com/help/tutorials/upload-curl/ and everything was ok so far.
Here's my result of "Retrieve upload status" and it says uploading was successful.
root@Mysrv:~# curl "https://api.mapbox.com/uploads/v1/steven921/{id}?access_token={security_token}"
{"id":"ckneprskq01dd28qk92qe0aml","name":"Traverse Bay","complete":true,"error":null,"created":"2021-04-12T14:51:29.328Z","modified":"2021-04-12T14:51:29.328Z","tileset":"steven921.traverse-bay","owner":"steven921","progress":1}

But I'm confusing at the next stop.
Basically I'm going to follow to https://docs.mapbox.com/mapbox-gl-js/example/map-tiles, but it says url of tiles as format of "https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.jpg"

Why this format differs to the url in the https://docs.mapbox.com/api/maps/raster-tiles/#retrieve-raster-tiles ?
There says url as format of "/v4/{tileset_id}/{zoom}/{x}/{y}{@2x}.{format}" in the https://docs.mapbox.com/api/maps/raster-tiles/#retrieve-raster-tiles.

Here's my html.
<link href="https://api.mapbox.com/mapbox-gl-js/v2.2.0/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.2.0/mapbox-gl.js"></script>
...
    var map = new mapboxgl.Map({
        container: 'map', // container id
        style: {
            'version': 8,
            'sources': {
                'raster-tiles': {
                    'type': 'raster',
                    'tiles': [
                        'https://api.mapbox.com/v4/steven921.traverse-bay/{z}/{x}/{y}.jpg'
                    ],
                    'tileSize': 256,
                }
            },
            'layers': [
                {
                    'id': 'simple-tiles',
                    'type': 'raster',
                    'source': 'raster-tiles',
                    'minzoom': 0,
                    'maxzoom': 22
                }
            ]
        },
        center: [-74.5, 40], // starting position
        zoom: 2 // starting zoom
    });

And I got the result as following:
![mapbox_fail1](https://user-images.githubusercontent.com/70382697/114434799-ff73bd00-9bf5-11eb-9f9a-77af2e93c85d.PNG)

I have struggled two hours and googled but got nothing right solution.
Really appreciated if anyone can help.
Thanks for advance.

**Comment by asheemmamoowala** [comment]
@forfullstack For "how do I" questions like this, if our [help documentation](https://www.mapbox.com/help/) doesn't answer your question, our [support](https://www.mapbox.com/contact/) team can help with the use of Mapbox services. This issue tracker is for reporting bugs and feature requests to the Mapbox-GL-JS library. Thank you!
