### ISSUE TITLE
Granular interactivity configuration

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#1056]
At the moment, there is only one option that can be passed to the map: interactive (true/false), which disable every interaction. It would be good to have different options:
 - rotation
 - draggable
 - boxzoom
 - tilt
 - ... other future options

It would be better to have something similar to leaflet "handlers":
 - Being able to pass options to the map corresponding to each interactivity so that the can be disabled by default
 - Being able to access the handler's instance and call enable() / disable() on the fly to activate an interaction on demand

This is a follow-up on the comments of @jfirebaugh and @mourner on issue #1038:
https://github.com/mapbox/mapbox-gl-js/issues/1038#issuecomment-77328219

Fabien

**Comment by KP** [comment]
Related, when I pinch-to-zoom a map the bearing of the map changes (the map rotates). This behavior feels a bit jarring as we're conditioned to expect the map to simply zoom. I was hoping to disable this bearing change for touch events (mobile) but not disable map rotation on desktop.

May be worth considering this change by default. An alternate gesture might be a stationary touch with one finger while another finger rotates the map.

**Comment by mourner** [comment]
@KP That's not how mobile maps work — try Apple or Google Maps on mobile. The only difference is that we need to implement #1059 to make it easier to keep the bearing zero.

**Comment by KP** [comment]
Ah. Yes. You are right. That will definitely help. Honestly, I hadn't even realized you could rotate Google Maps with a pinch.
