### ISSUE TITLE
Missing "type=button" attribute for the button in the attribution div

### ISSUE THREAD

**Issue by Antho-G** [mapbox/mapbox-gl-js#10573]
Hello,

I'm using mapbox 2.2.0 and I have a little issue caused by a missing attribute in the button tag used for the attribution on the map.
In this part of the code (which is automatically added by mapbox):

 ```
<div class="mapboxgl-ctrl mapboxgl-ctrl-attrib">
<button class="mapboxgl-ctrl-attrib-button" title="Toggle attribution" aria-label="Toggle attribution">
</button>
```

The button is missing the attribute "type='button'" which is causing me trouble because I am using the map in a "form" tag so when I press ENTER on any of my inputs in my page, this button is submitting the form!

Could you add the missing type by default ?
Thank you for your work !

The problematic button :
<img width="28" alt="Capture d’écran 2021-04-14 à 15 46 32" src="https://user-images.githubusercontent.com/57936551/114720803-9fd1fa80-9d38-11eb-8173-cb5f46d6830b.png">

**Comment by ryanhamley** [comment]
Hi @Antho-G this was fixed with https://github.com/mapbox/mapbox-gl-js/pull/10531 and will be in the next GL JS release
