### ISSUE TITLE
CORS Bug

### ISSUE THREAD

**Issue by moustaphahennawi** [mapbox/mapbox-gl-js#10571]
Hello i'm using mapbox gl in my app to display map, and i have issue to display one particulier map : "http://igngp.geoapi.fr/tile.php/cartes-oaci/{z}/{x}/{y}.png".
When i'm using tiles to display this map server respond with CORS bug any idea how to resolve this problem?
<img width="527" alt="Capture d’écran 2021-04-14 à 04 26 30" src="https://user-images.githubusercontent.com/56674781/114645402-b137ea00-9cd9-11eb-8136-9e669f68162d.png">
![Capture d’écran 2021-04-14 à 04 27 02](https://user-images.githubusercontent.com/56674781/114645410-b6953480-9cd9-11eb-814a-88418cf60882.png)

**Comment by ryanhamley** [comment]
Hi @moustaphahennawi unfortunately CORS errors are going to be specific to your application's setup and the server you're receiving data from. We cannot debug these errors via this issue tracker. We have a small [help page](https://docs.mapbox.com/help/troubleshooting/cors-errors/) on CORS errors, but if you need further assistance, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).

**Comment by robibrazze** [comment]
Hi @ryanhamley, i view the [help page](https://docs.mapbox.com/help/troubleshooting/cors-errors/)  but I don't understand in which folder you need to put my local raster , in the folder js? I try it but i don't work.
In my case i work only in local and i would like show my custom raster, whit the code below 
`        'geotif_comp': {
                    'type': 'image',
                    'url': './geotif_jpg_qgsi.jpg',
											"coordinates": [
											[7.462533, 44.247039],
									   	[7.678129, 44.247039],
											 [7.678129, 44.111750],
								 			[7.462533, 44.111750]`

thanks a lot
