### ISSUE TITLE
About the layers of lines

### ISSUE THREAD

**Issue by li-0813** [mapbox/mapbox-gl-js#10572]
Hello, why can't line layers also have height settings？

**Comment by mourner** [comment]
Duplicate of #3993.

**Comment by li-0813** [comment]
_this.map.addLayer({ type: "line",...}) But the line type does not have the property extrusion-height

**Comment by li-0813** [comment]
> [＃3993的](https://github.com/mapbox/mapbox-gl-js/issues/3993)重复项。

_this.map.addLayer（{type：“ line”，...}）但是，该线型不具有属性trusion-height
