### ISSUE TITLE
Isochrone

### ISSUE THREAD

**Issue by rudyhadoux** [mapbox/mapbox-gl-js#10574]
Hi,

How do you calculate moving times in your Isochrone API ?

**Comment by ryanhamley** [comment]
Hi @rudyhadoux the GL JS team does not maintain the Isochrone API. If you need help getting started with it, you can follow [this tutorial](https://docs.mapbox.com/help/tutorials/get-started-isochrone-api/). If you need further help, contact [Mapbox Support](https://support.mapbox.com/hc/en-us).

**Comment by rudyhadoux** [comment]
That was not the question.

**Comment by rudyhadoux** [comment]
What are the statistics to calculate the average journey times ?

**Comment by ryanhamley** [comment]
>What are the statistics to calculate the average journey times ?

I'm not really sure what you mean by this. As I said, the GL JS team does not maintain this API so I can't really answer this question for you. The proper forum for general questions such as this is to contact Mapbox Support.

**Comment by rudyhadoux** [comment]
Let it go bye.

**Comment by ryanhamley** [comment]
@rudyhadoux please note that this project is governed by a [Code of Conduct](https://github.com/mapbox/mapbox-gl-js/blob/main/CODE-OF-CONDUCT.md) which all contributors are expected to abide by
