### ISSUE TITLE
MultiPolygon polygon/fill disappears while zooming out, and then reappears as I continue to zoom out.

### ISSUE THREAD

**Issue by mhsdevus** [mapbox/mapbox-gl-js#10592]
Please excuse me if this has been reported elsewhere or explained in the documentation. I haven't been able to find anything describing this issue specifically.

**mapbox-gl-js version**: v2.2.0

I've also tested v2.1.1, v2.1.0, v2.0.0, v1.13.0

**browser**: Chrome (Mac) 89.0.4389.128. Also observed in Firefox and Safari.

### Steps to Trigger Behavior

 1. Start at zoom>=10. Observe: the polygon is filled with black.
 2. Zoom out to zoom<10 but zoom>=9. Observe: the polygon is no longer filled and only an outline remains.
 3. Zoom out further to zoom <9. Observe: the polygon is now filled again.

### Link to Demonstration

https://codepen.io/mhsdev/pen/abpjKXr

- Very simple GeoJSON data source with a single MultiPolygon, and a simple fill layer to display that data source.
- The MultiPolygon consists of 1 large polygon and 5 smaller, outlying polygons. None of the polygons overlap. I've verified all of the polygons begin and end with the same point.

### Expected Behavior

Either:

- The feature's geometry/fill should always be visible, regardless of zoom level.
- The entire feature (fill+outline) should disappear predictably below a certain zoom threshold.

### Actual Behavior

The polygon's fill disappears, oddly leaving only an outline, but only within a specific zoom-level range: 9>=zoom<10

I notice this glitch occurs at the same zoom threshold that other basemap features disappear; e.g., small water bodies. This seems to indicate that the behavior might be intentional/expected to some degree.

Followup:

- If I modify the GeoJSON to remove the smaller/extra polygons in the feature, so that only the single large polygon remains, the issue does not occur and the feature is no longer affected.
- If I set `threshold=0`, the feature is no longer affected.

These details lead me to believe that perhaps there is some algorithm that is incorrectly treating a larger feature as if it were smaller than it is, on the basis of the feature's smaller polygons. This seems to cause the feature to prematurely disappear relative to other similarly-sized features, and then oddly reappear at some lower level in the zoom range.

**Comment by mhsdevus** [comment]
Followup: I now realize that this issue might already be covered under https://github.com/mapbox/mapbox-gl-js/issues/7023. However if anyone has any insights for a workaround, I'd appreciate it.

**Comment by mhsdevus** [comment]
Followup: I was able to set ```tolerance=0``` and that solves the problem. However I still find it odd that this behavior occurs between a specific zoom-level range and not the levels below it.

**Comment by mhsdevus** [comment]
### Followup

At first I thought perhaps this was a rendering bug, a la https://github.com/mapbox/mapbox-gl-js/issues/7023, but that doesn't seem to be the case.

If I set `tolerance=0`, it fixes the particular feature shown my demo's data source. However, in my actual app/data, other smaller features are still affected by the behavior.

As the larger features/polygons are no longer affected when `tolerance=0`, the issue isn't as obvious/blatant during zooming. Smaller features are still affected, but since the zoom level is so low, it's not so obvious, except when those smaller features are clustered together into a larger area.

This now leads me to believe that the behavior might actually be intended. i.e., Small features get culled/hidden at low zoom levels, as a performance optimization.

**If my assumption is correct, it appears there is a bug: when a larger feature consisting of a MultiPolygon containing some smaller polygons, this "culling behavior" gets applied to that feature prematurely.** This can be seen in the demonstration of my original bug report.

**Comment by mourner** [comment]
This is likely the same issue as #7023, so I'll close this one as duplicate. As you zoom out, simplification and snapping to a grid introduces self-intersections that the triangulation code can't handle. Using `tolerance = 0` may be a suitable workaround in some cases like this.

**Comment by mhsdevus** [comment]
I did consider that #7023 was somehow related, but I wasn't really familiar enough to apply that here.

Now I'm seeing that this does seem related to the way geometry is split at varying zoom levels. Fwiw, if I shift the geometry by a few or scale it down (presumably causing it to no longer overlap a tile's edge in a particular way), the issue stops occurring.

However I do find it interesting that if I remove one of the tiny polygons (specifically the first polygon), the issue stops occurring entirely. Part of my overall optimization plan is to generate different levels of detail for different zoomLevels, and that would naturally involve culling out such small polygons. Fingers crossed!

**Comment by tibotiber** [comment]
Same issue here, solved with `tolerance: 0` set on the [geojson source](https://docs.mapbox.com/style-spec/reference/sources/#geojson-tolerance). Thanks!
