### ISSUE TITLE
Feature: Snap compass/bearing to north

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-js#1059]
When rotating the map, it would be friendly to snap to north if bearing ends within some tolerance of 0º.

I proposed the same enhancement for native at mapbox/mapbox-gl-native/pull/938. Something around ±7º (or slightly smaller) felt right to me in tests there. [Here's a video of what this looks like on native/iOS.](https://www.dropbox.com/s/whvr60fqgm7jycf/snapCompassIfNeeded.mp4?dl=0)

Previously this feature kinda' existed on JS via bug #1055.

**Comment by mourner** [comment]
Should it snap on the API level (when setting bearing), or only in certain interaction handlers like mouse and pinch rotation?
