### ISSUE TITLE
Support drawing lines with changing colours

### ISSUE THREAD

**Issue by ygoe** [mapbox/mapbox-gl-js#10601]
## Motivation

Currently it seems like lines can only be drawn onto a map in the form of a GeoJSON line layer. The entire line will have the same colour and style. That's fine to display a simple track recording but it's not suitable for more advanced path data visualisations. It cannot render the altitude, speed or other properties of the track that change along the way.

An example is the way how flightradar shows the position trace of any aircarft with a colour that depends on the current altitude.

My specific aim is to display a bit of history of a track and let it fade out more the older it gets. This lets the user quickly see how an object has moved in a specific time or how long ago it was at a position on the track.

## Design Alternatives

Not possible now, no alternatives suitable.

## Design

Not sure, but I'm thinking of an API that lets me add lines in a similar way as markers, just as lines, not other objects. Of course the lines should update correctly when the map is zoomed (markers don't do anything like that, they just keep their anchored position).

**Comment by ryanhamley** [comment]
@ygoe Are you sure there aren't any workarounds that will work for your use case? I think what you're trying for is doable with a bit of work. You can use [line-gradient](https://docs.mapbox.com/mapbox-gl-js/example/line-gradient/) to change the color of a line over distance. [Data-driven colors](https://docs.mapbox.com/mapbox-gl-js/example/data-driven-lines/) are also possible for lines so you should be able to color lines based on certain properties like speed. That may require processing the lines to make multi-line features rather than one long line. As for removing older pieces of a line in a time-series, something like that should be possible by using `setData` to remove older sections of the line from the source data. I'd recommend [contacting Mapbox Support](https://support.mapbox.com/hc/en-us) to see if they can help guide you in the right direction.

**Comment by ygoe** [comment]
That gradient definition only affects the position along the rendered line (in pixels), right? It does not consider the data points. They might lie near to each other or further apart. That's the main point of rendering a trail behind a moving object. If that movement varies in speed, the line gradient should be uneven.

Also, it would be hard to convert data that's already there into a gradient position. Consider a set of points like these:

```js
[
    { lat: 0, lng: 1, alt: 1 },
    { lat: 0, lng: 2, alt: 2 },
    { lat: 0, lng: 11, alt: 3 },
    { lat: 0, lng: 12, alt: 4 },
]
```

The values are arbitrary but you can guess that there's a larger gap between the points 1, 2 and 3, 4. Looking at the altitude values, the gradient looks even, but considering the actual positions, it certainly isn't. Is that also possible?

I wouldn't expect a smooth gradient here but rather just have each line segment in a different colour depending on its associated data. After all that's the measurement precision and it cannot in general be assumed that the real data changes smoothly between measurements.

**Comment by peterqliu** [comment]
@ygoe you can achieve that effect by splitting the line into segments of two points each, and coloring them by your `alt` property

https://turfjs.org/docs/#lineSegment

>That gradient definition only affects the position along the rendered line (in pixels), right?

No, it is by percentage along the line https://docs.mapbox.com/mapbox-gl-js/example/line-gradient/. if you calculate each vertex's distance along the whole line, you can achieve the same effect with one single line geometry.

**Comment by ygoe** [comment]
> No, it is by percentage along the line

That wasn't a contradiction and I can interpret that as agreement with my question/statement. I've seen that example and played with it to make it more meaningful. And it fails my test. Please do this:

* Remove all points but keep two at the start and one at the end. The two points should be much closer together than the last point.
* Remove all intermediate colours and change the gradient from blue at 0 to yellow at 1.

Now you see an even gradient along the entire line. That's what I meant. It ignores the actual distance of the points.

I just need a different colour for each connection between two points. I don't even want that gradient (but could accept it if necessary). I just want to define a colour to apply between each two points. No complex distance calculations to pre-undo what the map does again. You're proposing a solution that doubles the algorithmic complexity instead of removing it where it's unnecessary in the first place.

**Comment by peterqliu** [comment]
@ygoe I haven't seen this as a common use case, but it sounds like you know exactly how to build it!  Since you might be the only one interested _and_ qualified to implement this feature, feel free to [contribute](https://github.com/mapbox/mapbox-gl-js/blob/99f02030172b998c7ae77ca23d57c7e794c4cd43/CONTRIBUTING.md).

**Comment by ygoe** [comment]
To be clear, I know nothing about WebGL. If you would be willing to accept any code from me, and also wait years for it (my current average delivery time for new projects), then we can do this. Until then, I'll have to conclude that Mapbox can't render this type of visualisation. That's a valid answer. It simply reduces the feature set of my application. I can justify that. Maybe I can implement a workaround with degraded performance (use several separate path segments with their individual colour and add them as separate layers).

**Comment by karimnaaji** [comment]
@ygoe If I correctly understand your use case I believe the initial request here is about data-driven line-gradients. This would be based on some data input, whether it's elevation or other feature properties.

We already have a ticket tracking this issue in https://github.com/mapbox/mapbox-gl-js/issues/8977 so let's continue discussion on the other issue as there is already a lot of discussion happening on that ticket.
