### ISSUE TITLE
It can be use multiple container from single instance?

### ISSUE THREAD

**Issue by seong889** [mapbox/mapbox-gl-js#10607]
**mapbox-gl-js version**: 1.13.0

### Question
I didn't speak English, so I used a translator. Please understand. 

I want look at multiple locations at the same time with same datas.
ex) 
container A : zoom level 13, location : [0,0]
container B : zoom level 5, location : [120, 0]

In my opinion, create multiple instances to display in multiple containers, have to apply the same data twice. but this is so Uncomfortable.

So. I want solution for control two container.

Thanks for reading

**Comment by karimnaaji** [comment]
If I understand this correctly, you would like to have two map instances referring to the same data, and be able to make updates once that are reflected at the same time on both the map instances?

**Comment by karimnaaji** [comment]
Closing this ticket due to lack of information, feel free to reopen with more details.

**Comment by seong889** [comment]
I mean single data with multiple map instance. Changing the data once then reflect multiple map at the same time.

The purpose of this program is real-time data that periodically received from server is displayed through a map and user observes several areas at the same time. The effect of this will reduce the number of requests to the server and fewer management points.

**Comment by ryanhamley** [comment]
That's not built-in functionality but you should be able to do it. Something along these lines would probably do the job.

```
const maps = [];
const mapOptions = [{...}, {...}...];

mapOptions.forEach(function (options) {
    maps.push(new mapboxgl.Map(options));
});

function getDataFromServer() {...}

getDataFromServer()
.then(function (data) {
    maps.forEach(function (map) {
        map.addSource('mySource', {
            type: 'geojson', // or whatever it is
            data
        });

        map.addLayer({
            id: 'myLayer',
            source: 'mySource'
            type: 'polygon' // or whatever
            layout: {...},
            paint: {...}  
        });
    });
});
```
