### ISSUE TITLE
How to diplay limited number of titles for a line

### ISSUE THREAD

**Issue by dmitrykinakh** [mapbox/mapbox-gl-js#10600]
Hi there,

I have a question about displaying a limited set of titles when displaying a line on the Mapbox map. Right now it looks like the title is present for each segment of my line. Is there a way how this can be limited via Mapbox styles?

![image](https://user-images.githubusercontent.com/8025637/115383258-43f6ee00-a1de-11eb-87f1-4d3ac78a00ec.png)

 "mapbox-gl@1.11.1",

**Comment by rreusser** [comment]
Hi, @dmitrykinakh. This might happen if each line segment is a separate feature (I'm not 100% certain; a reproducible example helps diagnose the issue if something doesn't seem right), but if the path is one feature, then I believe the property you're looking for is [`symbol-spacing`](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-symbol-spacing). The purpose of this issue tracker is for bug reports and feature requests though, so it you have questions about usage, [Mapbox Support](https://support.mapbox.com/hc/en-us) is probably the most appropriate forum.
