### ISSUE TITLE
Setting fill-outline-color results in "Cannot read property 'r' of null" error

### ISSUE THREAD

**Issue by Yuki-Zhao** [mapbox/mapbox-gl-js#10617]
![image](https://user-images.githubusercontent.com/22816207/116195854-54badd00-a765-11eb-8afd-1f6e34cdd8d0.png)

i set an expression to fill-outline-color.
but one of feature, there isn't "MS-LENGTH-Average" in properties.
so I get the following error:
![image](https://user-images.githubusercontent.com/22816207/116196054-9481c480-a765-11eb-91ed-09997b5db6a3.png)

**Comment by karimnaaji** [comment]
@Yuki-Zhao would you be able to put the above in a working example like [jsfiddle](https://jsfiddle.net/)?

**Comment by karimnaaji** [comment]
Closing due to lack of information, from your screenshot my guess is that `MS-LENGTH-Average` is not available in your feature data. Feel free to reopen with the full example if this is still an issue for you.
