### ISSUE TITLE
I hava a question in   handler_manager.js  

### ISSUE THREAD

**Issue by adlovley** [mapbox/mapbox-gl-js#10623]
but when I debug the code , I found that when triggerrepaint ,the taskqueue first add the task , and then execute the render ,  why ? 

_requestFrame() {
         this._map.triggerRepaint();
        return this._map._renderTaskQueue.add(timeStamp => {
            delete this._frameId;
            this.handleEvent(new RenderFrameEvent('renderFrame', {timeStamp}));
            this._applyChanges();
        });
    }

I think  the task insert into taskqueue  should  be execute before triggerRepaint , 

_requestFrame() {

         this._frameId  = this._map._renderTaskQueue.add(timeStamp => {
            delete this._frameId;
            this.handleEvent(new RenderFrameEvent('renderFrame', {timeStamp}));
            this._applyChanges();
        });

        this._map.triggerRepaint();
    }

**Comment by ansis** [comment]
triggerRepaint() doesn't do anything right away. It ends up calling [`requestAnimationFrame(...)`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) which will render the frame later, asynchronously. This means the task is added to the queue before the rendering happens no matter which order the methods are called.
