### ISSUE TITLE
Example using perspective

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#1062]
When https://github.com/mapbox/mapbox-gl-js/pull/1049 is merged.

**Comment by jfirebaugh** [comment]
:+1: Let's do a route fly-along for this.

**Comment by jfirebaugh** [comment]
https://www.mapbox.com/mapbox-gl-js/example/set-perspective/
https://www.mapbox.com/mapbox-gl-js/example/scroll-fly-to/
