### ISSUE TITLE
fill-extrusion layer After setting the transparency, the occluded fill-exutrusion layer cannot be seen

### ISSUE THREAD

**Issue by hahaxiaowai** [mapbox/mapbox-gl-js#10630]
**mapbox-gl-js version**: 2.2

### Question

When I set the map style, I found that after setting the transparency of the building layer, I can see things on the ground.But I can’t see the obscured buildings behind.Is this related to the rendering mechanism?Blocked buildings will not be rendered.
![1](https://user-images.githubusercontent.com/49934348/116526254-faa84c00-a90b-11eb-9108-6ace570c568b.jpg)

**Comment by astojilj** [comment]
Yes, this is according to design. Further information is available at https://github.com/mapbox/mapbox-gl-js/issues/9046#issuecomment-559855385.
