### ISSUE TITLE
Unclean rendering of the halo with sdf icons with  'icon-halo-width' 

### ISSUE THREAD

**Issue by CptHolzschnauz** [mapbox/mapbox-gl-js#10637]
**mapbox-gl-js version**: 2.2

**browser**: All

### Steps to Trigger Behavior

 1. Add a sdf image for an icon: map.addImage('poi-icon', image, { 'sdf': true });
 2. Paint the icon with a halo:  'paint': {
                    'icon-color':  '#690000',
                    'icon-halo-color':  '#ffffff',
                    'icon-halo-width':  4
                },
 3. Pitch the map.

Problem: The further away the icon is, the more the halo becomes a square

### Demonstration:

<img width="328" alt="issue" src="https://user-images.githubusercontent.com/68701579/116817533-14919b00-ab67-11eb-9e13-97406508f979.png">

### Expected Behavior

icon-halo-width interpolating with its width

### Actual Behavior

There is a step: The halo becomes a square with it's color

This bug is not with text halo, here everything is rendered correct.
Example:
'paint': {
                    'text-color': '#202',
                    'text-halo-color': '#fff',
                    'text-halo-width': 2
                },

**Comment by CptHolzschnauz** [comment]
I am using a png and declare map.addImage('poi-icon', image, { 'sdf': true });

![poi](https://user-images.githubusercontent.com/68701579/117916825-30740a00-b2e8-11eb-9603-093c4d3a0096.png)

I have no public website to show at the moment. You can reproduce the bug with any marker png. 

Workaround : I use svg markers preloaded as custom images in mapbox studio - more elegant anyway.

**Comment by karimnaaji** [comment]
>Workaround : I use svg markers preloaded as custom images in mapbox studio - more elegant anyway.

Sounds good.

Concerning the image you provided, it's not an SDF image, I would recommend going through this documentation https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/ that covers this topic in more detail.
