### ISSUE TITLE
Use anisotropic filtering for raster tiles in perspective view

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1064]
We should use the `EXT_texture_filter_anisotropic` extension if it is available. Anisotropic filtering will make [textures clearer when viewed at an angle](http://media.tojicode.com/webgl-samples/anisotropy.html). The filtering level used should depend on the current pitch.

**Comment by lucaswoj** [comment]
@nickidlugash I wonder if this could help us render pitched labels more clearly 🤔

**Comment by nickidlugash** [comment]
@lucaswoj this looks interesting. Do we use mipmaps for labels? I don't really know how our textures work.

**Comment by andrewharvey** [comment]
This certainly makes pitched raster maps look much nicer!

![selection_490](https://cloud.githubusercontent.com/assets/117278/24040809/d753ec5e-0b5e-11e7-8687-3c1d9c4079c6.png)
![selection_489](https://cloud.githubusercontent.com/assets/117278/24040811/d9987926-0b5e-11e7-840e-3482f0f36a7f.png)

Working on this in #4443

**Comment by mollymerp** [comment]
🚢 in #4443 - thank you @andrewharvey !
