### ISSUE TITLE
Greater label density in 0.7 makes some more important labels disappear

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#1066]
Hello,

Just updated to 0.7 and the result is very different. Here is a screenshot of version 0.5.2:
![image](https://cloud.githubusercontent.com/assets/1240481/6537905/aba01818-c45b-11e4-8127-bc90c1bd7577.png)

And a screenshot of the same zoom level in version 0.7.0 (from the CDN)
![image](https://cloud.githubusercontent.com/assets/1240481/6537914/b92ca316-c45b-11e4-8e25-b2b67f3de5b6.png)

There was an accepted PR about labels density (https://github.com/mapbox/mapbox-gl-js/pull/989) and it is true, there is more road labels but they seem to take over on labels with more importance such as higher admin_*. You can see that the neighbourhoods are not visible anymore, apart from one on the right of the screen.

Is that expected behaviours? Should there not be some kind of priorities between labels?

Thanks,
Fabien

**Comment by kristfal** [comment]
Following up on this, not sure if related. I'm seeing some issues "symbol-placement": "line" at the moment which were not present before #989 was accepted.

Symbol line placement overlap is wonky. See attached screenshot. The line label has no allow-overlap, is listed at the very end of the stylesheet, yet still overlap all other labels. The overlapped labels may have "symbol-placement": "line" or "point".

![screenshot 2015-03-11 11 01 52](https://cloud.githubusercontent.com/assets/5638107/6594147/e7d54e9e-c7de-11e4-8a83-8b6554f3eeef.png)

**Comment by ansis** [comment]
@fnicollet that looks like a style problem. I opened an issue here: https://github.com/mapbox/mapbox-gl-styles/issues/41

@kristfal can you check if the problem still exists with the latest master? we just merged a rewrite of label placement: https://github.com/mapbox/mapbox-gl-js/pull/1079

**Comment by kristfal** [comment]
@ansis Still seeing line issues after building the latest master, same issue on GL native (not the most recent master) as well, but significantly fewer collisions in the same places. 

Also noticed that two line labels from the same line can collide at certain zoom levels (screenshot nr 2).

![screenshot 2015-03-19 13 40 18](https://cloud.githubusercontent.com/assets/5638107/6730622/a1aa6114-ce3e-11e4-853e-9ec873830d7f.png)
![screenshot 2015-03-19 13 40 59](https://cloud.githubusercontent.com/assets/5638107/6730621/a1a8b8aa-ce3e-11e4-9812-a2d2a663ec9a.png)
![screenshot 2015-03-19 13 42 04](https://cloud.githubusercontent.com/assets/5638107/6730623/a1b444ae-ce3e-11e4-8499-7f5b38055ee3.png)

**Comment by jfirebaugh** [comment]
0.8.1 has significant labeling changes and Mapbox Streets looks OK to me. Neighborhoods do defer to streets at a certain level but I think that's a stylistic choice.

@kristfal If you're still seeing labeling issues with 0.8.1, please open a separate ticket. Thanks!

**Comment by fnicollet** [comment]
Thanks for this feedback on that issue. 0.8.1 indeed has more street labels (still cropped at times, but that's another issue), it's ok if they hide the neighbourhood labels that way
