### ISSUE TITLE
Tiny rendering artefact when rendering highway shields

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#1067]
Hi, just updated to 0.7 and noticed that highway shields seem to have some kind of padding, which cut them by 1 px at the top and show a line at the bottom:
![image](https://cloud.githubusercontent.com/assets/1240481/6537987/850afa82-c45c-11e4-91ed-b8967da23b70.png)
or
![image](https://cloud.githubusercontent.com/assets/1240481/6537996/9c393034-c45c-11e4-9027-d28c171053f1.png)

Reproduced with:
https://api.tiles.mapbox.com/mapbox-gl-js/v0.7.0/mapbox-gl.js
https://api.tiles.mapbox.com/mapbox-gl-js/v0.7.0/mapbox-gl.css
https://www.mapbox.com/mapbox-gl-styles/styles/bright-v7.json

**Comment by ansis** [comment]
@fnicollet I think 2127609 should fix this

**Comment by fnicollet** [comment]
@ansis thanks a lot for taking care of those issues, really! :) i'll give it a try asap, probably on monday and let you know

Fabien

**Comment by fnicollet** [comment]
It probably works but I do all my testing in IE and there are issues that makes the rendering bad with current master so I can't really say if good or not as the highway shields don't even display anymore (as well as water and other stuff)
