### ISSUE TITLE
Many white dots flicker when zooming in

### ISSUE THREAD

**Issue by spirityy** [mapbox/mapbox-gl-js#10689]
**mapbox-gl-js version**:2.2.0

**browser**:Chrome

### Steps to Trigger Behavior

dark style 3d mode white points flash
 
### Expected Behavior
no white points flash

**Comment by ryanhamley** [comment]
Can you provide an minimal, working example of the issue? We can't diagnose anything from a short description

**Comment by spirityy** [comment]
![WeChatWorkScreenshot_670dc812-482e-479a-b07a-db9407f159d5](https://user-images.githubusercontent.com/424997/119336550-61791500-bcc0-11eb-819c-1a33e65930ea.png)

**Comment by spirityy** [comment]
Flickering white dots

**Comment by ryanhamley** [comment]
@spirityy Can you use a site like [JSBin](https://jsbin.com/?html,output) to create an example using your code (stripped down to the minimal amount of code that reproduces the bug)? We can't diagnose any problems from a screenshot.

**Comment by karimnaaji** [comment]
Closing this ticket as we're missing important information to diagnose here.
