### ISSUE TITLE
How to use accumulated to create array?

### ISSUE THREAD

**Issue by enersis-pst** [mapbox/mapbox-gl-js#10695]
i want to cluster features and to accumulate all ids into one array. In the style i want to use for example "in" to check if the id exists.

I find out that this works by using string, but array<string> would be much likelier.
`clusterProperties: { "myids": ["concat", ["concat", ["get", "id"], ","]]},`
`"circle-color": ["case", ["in", "B", ["get", "myids"]], "green", "red"]`

### Question
How to use accumulated to create array?

**Comment by mourner** [comment]
Unfortunately GL JS currently doesn't support array-forming expressions (not only for cluster properties but generally in the epression system). Moreover, the [vector tile specification](https://github.com/mapbox/vector-tile-spec/tree/master/2.1) doesn't support arrays as property values, which makes things even more complicated, making it very difficult to implement. I'm happy that strings work for your case though — this seems like a great workaround.

**Comment by enersis-pst** [comment]
if someone is interested in how to store key value pairs:
This count ids group by same ids. String would be `<id1>:<count1>,<id2>:<count2>,...`
Not the best solution but it works

```
      clusterProperties: {
		 "idCounts": [
			["let", "find", ["index-of", ["get", "idCounts"],["accumulated"]],
				["case",  
					["==", ["index-of", ":",["accumulated"]], -1],
					// first run
					["case", 
						["==", ["accumulated"], ["get", "idCounts"]],
						// acc & current are same
						["concat",["accumulated"], ":2,"],
						// acc & current are different
						["concat",["accumulated"], ":1,", ["get", "idCounts"], ":1,"]
					],
					["==", ["var", "find"], -1],
					// add new id
					["concat",["accumulated"], ["get", "idCounts"], ":1,"],
					// count for same id
					["let", 
						"start",  ["+", 1,["index-of", ":", ["accumulated"], ["var", "find"]]], 
						"stop", ["index-of", ",", ["accumulated"], ["var", "find"]], 
						["let", 
							"count", ["to-number", ["slice", ["accumulated"], ["var", "start"], ["var", "stop"]]],
							"beginnText", ["slice", ["accumulated"], 0, ["var", "start"]],
							"endText", ["slice", ["accumulated"], ["var", "stop"]],
							["concat", ["var", "beginnText"], ["+", 1, ["var", "count"]], ["var", "endText"]]
							
						]
					]
				]
			],
			["get", "id"]
		]
      },
```

to get one specific count in the style:
`"text-field": ["let", "find", ["index-of", "B", ["get", "idCounts"]], ["slice", ["get", "idCounts"], ["index-of", ":", ["get", "idCounts"], ["var", "find"]], ["index-of", ",", ["get", "idCounts"], ["var", "find"]]]]`
