### ISSUE TITLE
Support for relative URLs in style json

### ISSUE THREAD

**Issue by AgentSmith0** [mapbox/mapbox-gl-js#10692]
Please add support for relative URLs in json style properties. This would make it easier to use and some properties like glyphs or tile source already support relative paths. Is it possible to support it also on properties like sprite?

**Comment by mourner** [comment]
Support for relative URLs in the style was removed intentionally — see https://github.com/mapbox/mapbox-gl-js/issues/3636#issuecomment-261119004 for discussion around this, and some workarounds in the comments.
