### ISSUE TITLE
How to cluster custom icons which added by marker

### ISSUE THREAD

**Issue by tonviet712** [mapbox/mapbox-gl-js#10693]
**mapbox-gl-js version**: ^2.0.1

### Question
I added custom icon following this example : https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons

How I can cluster these icons ?

### Links to related documentation

1. https://docs.mapbox.com/mapbox-gl-js/example/cluster
2. https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/

**Comment by mourner** [comment]
You would do this exactly as in the [HTML clustering example](https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/), just replace the donut SVG code with the one from the custom icons example that creates the DOM element for the marker.
