### ISSUE TITLE
How to add (and then fire) a custom event on mapboxgl.Map ?

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1071]
There are already some events defined such as 'render', 'load', 'move'.

Can you give me an example of how I can add a custom event to the Map object and then fire it?

Thanks

**Comment by tristen** [comment]
@misterfresh You can register an event handler with `on` and then `fire` it when you want the function to be called. i.e.

``` js
var map = new mapboxgl.Map({container:document.createElement('div')});
map.on('foo', function() { alert('bar'); })
map.fire('foo');
```

**Comment by misterfresh** [comment]
Thanks, this works!

**Comment by Fractaliste** [comment]
@tristen Is the fire method still available? Otherwise its seems undocumented :/

**Comment by tristen** [comment]
@Fractaliste this is [no longer public as of 0.45.0](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#%EF%B8%8F-breaking-changes-3). You'll need to bring your own event emitter package.

**Comment by chriszrc** [comment]
@tristen Can you give us an example of a package that we'd use in the browser for this?

**Comment by tristen** [comment]
@chriszrc here's a few! http://microjs.com/#event%20emitter
