### ISSUE TITLE
fix raster maps in projections branch

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#10713]
Fix raster maps in the `projections` branch. it looks like the texture coordinates may be scaled incorrectly.

![Screen Shot 2021-05-26 at 12 19 50 PM](https://user-images.githubusercontent.com/1421652/119699295-02321680-be20-11eb-905f-86e0d2b5f1dd.png)

**Comment by ryanhamley** [comment]
Capturing from Slack:  `looks like this is because of the stencil PR that replaced the raster bounds array with the stencil one, but the latter doesn’t have texture_pos attribute`

**Comment by ryanhamley** [comment]
Fixed with https://github.com/mapbox/mapbox-gl-js/pull/10732
