### ISSUE TITLE
Filtering on substring in the setFilter function

### ISSUE THREAD

**Issue by JonathanLauwers** [mapbox/mapbox-gl-js#10711]
Hi Everyone

In the [docs](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#in) it says that the "in" operator can be used to filter on substrings. However, when I try this search functionality, I only get matches whenever I completely match the desired value.

Example use case: 
- I have a search input field which the user can use to filter the shown items on the map. 
- Initial example titles of items: "title a", "title b", "title c"
- User types "title" -> No matches -> expected to match "title a", "title b", "title c"
- User types "title a" -> matches "title a" 

Are the docs wrong or am I misinterpreting something?
 
 
Example filter array:
`
["all", ["in", "title", "Verdant Pass"], ["in", "difficulty", "5"], ["<=", "start_month", 6], [">=", "end_month", 6]]
`
This filter is then set the following way:
`
map.current.setFilter(LAYER_ID, filterArray)
`
-> Shows one match
-> the moment I change "Verdant Pass" to "Verdant Pas" it shows no matches anymore.

**Comment by ryanhamley** [comment]
You're using the [`in` filter](https://docs.mapbox.com/mapbox-gl-js/style-spec/other/#set-membership-filters) which is strictly looking for set membership. The filter syntax is deprecated and we recommend users use expressions instead. The [`in` expression](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#in) does find substrings. If you turned this into an expression on the layer, rather than a filter, you should get the desired result. This is a common mistake and we've tried to make the documentation as clear as possible. Sorry for the confusion.

**Comment by JonathanLauwers** [comment]
Hi Ryan

Could you maybe provide an example of how I could refactor the setFilter to an expression? I found this one [example](https://docs.mapbox.com/help/tutorials/mapbox-gl-js-expressions/) which uses an expression on load but mine only needs to be applied when the user adds a filter or the data changes.

How would you add an expression after the map has already been initialised and the layer has already been loaded?

**Comment by ryanhamley** [comment]
Hi @JonathanLauwers The exact setup probably depends a bit on your use case. The filter you have there looks like it could probably be plugged in as is to be an expression. The approach you linked to in the example is going to be the right way to go. If you need to do it at a specific time based on user interaction, then in the event handler for that user interaction you can call `map.setPaintProperty` or `map.setLayoutProperty` to update the appropriate style property on the correct layer. This will trigger a redraw and should update your layer. You can see this basic approach in [this example](https://docs.mapbox.com/mapbox-gl-js/example/color-switcher/) although that doesn't use expressions. I also built an [example of the `in` expression](https://codepen.io/rsh412/pen/yLygeZR) that uses it to color roads based on the type as determined by the name that could be helpful.
