### ISSUE TITLE
Marker location loses precision when zoomed in

### ISSUE THREAD

**Issue by djibarian** [mapbox/mapbox-gl-js#10726]
**mapbox-gl-js version**:

**browser**:

### Steps to Trigger Behavior

 1.
 2.
 3.

### Link to Demonstration

https://jsbin.com/

### Expected Behavior

A marker created at any zoom level would behave the same. 

### Actual Behavior

However, when created at a low zoom level and then zooming in, the marker is out of place. This is visible if you create a symbol and then create a marker at the exact same location.

This doesn't happen if the marker is created at a high zoom level. In that case, its location remains properly shown at any zoom level.

**Comment by rreusser** [comment]
@djibarian Could you provide a bit more information about how you're creating and placing the marker and symbol? Or a [JSFiddle](https://jsfiddle.net/) to demonstrate the issue? It sounds like this could involve the [marker anchor](https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker-parameters) or [icon-anchor](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-icon-anchor) property, but it's impossible to say without a bit more information. Thanks!

**Comment by djibarian** [comment]
OK, I got it. The lack of precision was in the coordinates returned by `queryRenderedFeatures()`. Not very obvious. The coordinates returned by that function for a symbol should be the ones given in the GeoJSON source, but it seems is not the case, and their precision is affected by the zoom level. For anyone interested.

**Comment by rreusser** [comment]
Thanks for the followup! I wonder if the `maxzoom` property might solve this? See: https://github.com/mapbox/mapbox-gl-js/issues/10108#issuecomment-728298265

**Comment by djibarian** [comment]
Yes it could be because of the fact that the GeoJSON is converted internally to tiles. That makes total sense.

**Comment by karimnaaji** [comment]
@djibarian did the suggestion of using `maxzoom` solve your issue?

**Comment by djibarian** [comment]
@karimnaaji No, I solved it using the original coordinates in the GeoJSON source, instead of the coordinates returned by `queryRenderedFeatures()`, which suffer from a precision loss based on the zoom level. Didn’t try changing the `maxzoom`, but I doubt that would have solved this specific problem.
