### ISSUE TITLE
Video Source  Add  HLS .m3u8 real-time stream  type

### ISSUE THREAD

**Issue by ShareQiu1994** [mapbox/mapbox-gl-js#10727]
At present, mapbox only supports playing WebM + MP4 files on the map. If only I could support other formats: I have a real-time stream in the form of HSL .M3u8, and I want to show it on a map.

If there is a solution, please let me know!

**Comment by mourner** [comment]
Mapbox GL JS has no way of extending video formats support because it relies on the browser codecs. Please see https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Video_codecs for supported video formats on the Web.

**Comment by syauqisabili** [comment]
Hi @ShareQiu1994, instead of using HSL (m3u8) you can use WebRTC (Use ffmpeg and publish it to MediaMTX) by adding a custom marker. You can check this https://github.com/maplibre/maplibre-gl-js/discussions/5422 to add live stream video overlay.
