### ISSUE TITLE
Offline version

### ISSUE THREAD

**Issue by francis-fullstack** [mapbox/mapbox-gl-js#10723]
Do you have an offline version of mapbox-gl.js? we want to use the map as offline version in our localhost

**Comment by ryanhamley** [comment]
We don't officially support offline GL JS usage. You can use locally hosted tiles and resources so you may be able to set up something that meets your needs. Mapbox also offers [Atlas](https://www.mapbox.com/atlas) as a fully self-contained solution that may meet your use case. I'd suggest talking to [Mapbox Support](https://support.mapbox.com/hc/en-us) if you have more detailed questions about your particular use case. Thanks.

**Comment by folsze** [comment]
Hi, 

@ryanhamley can I use a local mapbox server in my capacitorJS app? For offline maps?  I have an app for maps that would  be used offline a lot. I asked GPT4 but I think the things it says is wrong:
https://chat.openai.com/share/efbe3f5d-ea30-494c-8c0c-7f61b4606bfd

you cannot embed an express.js server into an ionic capacitor app or can you? If you can: how do I make mapbox-gl-js acess this local server?

If this is 100% completely impossible please lmk. And would also be interesting to know whether support like the native IOS/Android tile server is planned in the future
