### ISSUE TITLE
How do I choose a backup language to be used for labels that don't have a specified language?

### ISSUE THREAD

**Issue by SephReed** [mapbox/mapbox-gl-js#10740]
**mapbox-gl-js version**: < 1yr old

### Question

I'm attempting to support Spanish users of my map, and have figured out how to set all the label layers to a certain language:

```
const langCode = Math.random() < 0.5 ? "en" | "es";
const layers = this.mapbox.getStyle().layers.filter((it) => it.id.includes("label"))
layers.forEach((layer) => {
  this.mapbox.setLayoutProperty(layer.id, "text-field", [
    "get",
    `name_${langCode}`
  ])
});
```

The issue is that most the map ends up empty in Spanish mode. What I would like is for English to be the default back-up if nothing else exists. How can I do this?

### Links to related documentation

https://docs.mapbox.com/help/troubleshooting/change-language/

**Comment by korywka** [comment]
Note that `text-field` can be an expression, and you will just kill it by your example. You can find example of replace function [here](https://github.com/korywka/mapbox-gl-controls/blob/master/src/LanguageControl/localizeTextField.ts) or [in this package](https://github.com/mapbox/mapbox-gl-language/).

**Comment by rreusser** [comment]
Thanks, @korywka! Yes, you could use the [coalesce](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#coalesce) expression to accomplish this. The following expression would prefer the Spanish name, then English, then anything at all.

```
[
  "coalesce",
  ["get", "name_es"],
  ["get", "name_en"],
  ["get", "name"]
]
```

Also, we try to answer minimal questions within reason, but please keep in mind that this issue tracker is intended for bug reports and feature requests. The best place to ask questions about usage is [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks!

**Comment by SephReed** [comment]
Thank you.  As a feature request, I do think updating the docs on language changes to show this would be inline with typical use cases.
