### ISSUE TITLE
Feature request: accumulation for propertie arrays of mvt 

### ISSUE THREAD

**Issue by enersis-pst** [mapbox/mapbox-gl-js#10746]
## Motivation

Im thinking about how to use cluster by mvt. And i beleave it could be reached only by having the accumulated function also for mvt.
My idea is to generate a mvt where features are stored as clusteres depending by radius and zoom level . All properties from all clustered features are stored as obect in a array:
```
{
      "type": "Feature",
      "properties": {
           features: [
                 {type: "A", category: 1, id:"123"},
                 {type: "B", category: 2, id:"456"}
          ]
        },
      "geometry": {
        "type": "Point",
        "coordinates": [
              8.906098487986396,
              48.63653353027896
            ]
        }
```

The accumulated function could be used like for geojson to store additional propertie or like a expression to use it directly for a style propertie or for a filter.

```
accumulated: {
  has_A_2: [
    ["get", "features"],
    ["any", ["get", "has_A_2"],["accumulated"]],
    ["all",["=","A",["get","type"]],["=",2,["get","category"]]]
  ],
  count_A_2: [
    ["get", "features"],
    ["+", ["get", "countA_2"],["accumulated"]],
    ["case", ["all",["=","A",["get","type"]],["=",2,["get","category"]]], 1, 0]
  ]
}
```

**Comment by karimnaaji** [comment]
Hey @enersis-pst thanks for the proposal. This seems to be a similar topic as https://github.com/mapbox/mapbox-gl-js/issues/10408. Could you continue the discussion there to consolidate and see if your proposed solution works for others already interested in that? In the meantime, I'll close this issue as duplicate.
