### ISSUE TITLE
Markers added on map are located in wrong position & Marker location moves when zoom in/out

### ISSUE THREAD

**Issue by dev-owen** [mapbox/mapbox-gl-js#10749]
**mapbox-gl-js version**: v2.3.0

### Question

I would like to add markers on map when 'click' events triggered. I wrote some code with mapbox docs.

```typescript
    mapboxgl.accessToken = process.env.REACT_APP_MAPBOX_KEY;

    const initMap = ({ setMap, mapContainer, currentPosition }) => {
      const map = new mapboxgl.Map({
        container: mapContainer.current, // container ID
        style: 'mapbox://styles/mapbox/streets-v11', // style URL
        center: [currentPosition.lngX, currentPosition.latY], // starting position [lng, lat]
        zoom: 14, // starting zoom
      });

      map.on('load', () => {
        setMap(map);
        map.resize();
      });

      map.on('click', (e) => {
        const marker = new mapboxgl.Marker();
        marker.setLngLat(e.lngLat).addTo(map);
      });
    };

    if (!map) initMap({ setMap, mapContainer, currentPosition });
    else map.jumpTo({ center: [currentPosition.lngX, currentPosition.latY] });
``` 

I got two issues, which are not working as I intended to.
1. I clicked [lng, lat] position, and I checked that the position is entered exactly on the newly created marker. However, I found the marker is created on wrong position(a little bit left, down position from I clicked). I changed offset options but it doesn't work.
2. when I zoom in/out, the marker moves randomly. I never intended this effect.

I read mapbox api docs several times, and also searched a lot of stackoverflow posts, but I'm struggling to this issue few days so far. Please help.

https://user-images.githubusercontent.com/39744246/120916580-5f15b280-c6e5-11eb-9a76-8d51d0cf201f.mov

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker

**Comment by rreusser** [comment]
Hi, @dev-owen. My first thought is maybe a CSS issue. I would start by ensuring you're [loading the CSS correctly](https://docs.mapbox.com/mapbox-gl-js/api/#quickstart) and that your markers aren't accidentally affected by external CSS rules.

I copied your code into codepen, and it appears to work correctly: https://codepen.io/rsreusser/pen/LYWrOXq?editors=0010

**Comment by dev-owen** [comment]
Thanks for your answer and sample code.

**Comment by karimnaaji** [comment]
Assuming this to be resolved per https://github.com/mapbox/mapbox-gl-js/issues/10749#issuecomment-856062631 comment. @dev-owen Feel free to reopen if this is still an issue for you.

**Comment by plutownium** [comment]
An above reply says "make sure you're loading the CSS correctly" and links to a page that explains nothing about "loading the css correctly."

I had to hunt around and find this Stackoverflow post: https://stackoverflow.com/questions/71008574/react-map-gl-marker-is-moving-when-zooming-the-map

**Comment by diegosepulveda** [comment]
It happen to me the same that those videos about zooming in and markers moving in my React App.

This way I import those styles.
`import 'mapbox-gl/dist/mapbox-gl.css';`

@plutownium help me in finding the answer.
By the way this link explain more.
[https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/]

**Comment by plutownium** [comment]
@diegosepulveda What I had to do was import a particular css file into my React app's index.html file.

Stick this line into the index.html file in the public folder. `        <link href="https://api.mapbox.com/mapbox-gl-js/v2.6.1/mapbox-gl.css" rel="stylesheet" />`

(It goes in the header)

**Comment by DeveloperRyan** [comment]
@abdul-Tz-prog 
Did you find a fix for this issue? I also cannot seem to get the desired functionality with the CSS imported.

**Comment by benesg** [comment]
I am working on an Angular Project using MapLibre, and I fixed it by adding
`node_modules/maplibre-gl/dist/maplibre-gl.css`
to my styles array (/projects/[name]/architect/build/styles) in my `angular.json` file.
I guess you could easily fix it for mapbox as well by adjusting the path.

**Comment by cdpadilla42** [comment]
This solved my instance of this issue. If it's just Markers that are acting strangely, this is really all you need from the file:

```css
.mapboxgl-marker {
	position: absolute;
	top: 0;
	left: 0;
	will-change: transform;
	opacity: 1;
	transition: opacity .2s;
} 
```

> An above reply says "make sure you're loading the CSS correctly" and links to a page that explains nothing about achieving such a thing.
> 
> I had to hunt around and find this Stackoverflow post: https://stackoverflow.com/questions/71008574/react-map-gl-marker-is-moving-when-zooming-the-map
> 
> Putting this link here for future people trying to solve the bug where the markers move when you zoom the map

**Comment by mattixpet** [comment]
Nothing I saw on this thread worked, however, setting
```
offset = [0, 0]
```
on the marker did.

**Comment by isaacdarcilla** [comment]
> It happen to me the same that those videos about zooming in and markers moving in my React App.
> 
> This way I import those styles. `import 'mapbox-gl/dist/mapbox-gl.css';`
> 
> @plutownium help me in finding the answer. By the way this link explain more. [https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/]

Works for me adding in head tag.

<link href='https://api.mapbox.com/mapbox-gl-js/v3.3.0/mapbox-gl.css' rel='stylesheet' />

**Comment by williamlung** [comment]
I have this issue too and I solved it.
Followed the documentation to create a marker: https://visgl.github.io/react-map-gl/docs/api-reference/marker
and the marker location moves when zoomed in/out, then I **removed the anchor attribute under the Marker tag**, and the problem was solved.

**Comment by torus-cfilo** [comment]
This issue seems to continue to persist across versions of react-map-gl. I encountered this when using `react-map-gl/maplibre`, and none of the solutions seemed to work. I was only able to solve this by switching to the mapbox implementation.

**Comment by rubkn** [comment]
> Nothing I saw on this thread worked, however, setting
> 
> ```
> offset = [0, 0]
> ```
> 
> on the marker did.

This worked for me.

**Comment by esteban2841** [comment]
import the mapbox css for issues related to markets or pop ups locations points bad behaviors
import 'mapbox-gl/dist/mapbox-gl.css';
