### ISSUE TITLE
Vector tileset not accurate at lower zoom levels

### ISSUE THREAD

**Issue by nmandiveyi** [mapbox/mapbox-gl-js#10750]
I am creating a web map that will allow users to click on a polygon and have information about the polygon displayed (the polygon also gets highlighted). I have 4000+ polygons displayed on the map. The issue is when a polygon is clicked, the map is highlighting a different but nearby polygon. At higher zoom levels the map is highlighting the correct polygon. I've tried different ways to create the vector tileset (Tippecanoe and MTS), but I keep running into the same problem. 

Also, I have the cursor turn into a pointer when hovered over the tileset but it does not do so for some polygons. Sometimes the cursor points where there isn't any polygon.

@1ec5 @ajashton @alulsh @ericfischer @springmeyer @tmcw @jingsam

Please help...

**Comment by ryanhamley** [comment]
Hi @nmandiveyi sorry that you're having trouble. The best way to get help for an issue such as this is to contact [Mapbox Support](https://support.mapbox.com/hc/en-us) as we cannot offer support through Github. Thanks.
