### ISSUE TITLE
No labels in IE11

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#1075]
Labels appear to be completely missing in IE

![mapboxgl-ie11](https://cloud.githubusercontent.com/assets/61150/6603489/e21cbee6-c7f8-11e4-8733-9516417e30b4.png)

cc @ansis

**Comment by fnicollet** [comment]
I make most of my tests in IE11 and I don't have this issue with current mapbox-gl master. Maybe cross-domain restrictions on fonts PBFs?

**Comment by jfirebaugh** [comment]
This is working in my IE11 VM as well.
