### ISSUE TITLE
SetPaintProperty['some-property'] isnt't updated immediately in layer.paint['some-property']

### ISSUE THREAD

**Issue by Bernoulli-IT** [mapbox/mapbox-gl-js#10761]
**1.13.1**:

**Chrome V91.0.4472.77 (Official Build) (64-bit)**

**Mapbox incorporated in an Angular app**

### Steps to Trigger Behavior

 1. map.setPaintProperty(layer.id, 'fill-opacity', 0.6)
 2. console.log(layer.paint['fill-opacity']) -> displays previous value (for example 0.1)

### Expected Behavior

Trivially the expected behavior is for the layer.paint property to reflect the value set just before.

### Actual Behavior

It doesn't reflect the correct value immediataly after setting it, although the visualisation on the map updates correctly.

### Remark

After firing map.setPaintProperty(layer.id, 'fill-opacity', 0.1) again, the value from layer.paint['fill-opacity] is the previously set 0.6 🤪. Is there a valid reason for this. Does it take "a while" before the value gets propagated into the style layer (different from the rendered layer?).

All advice, suggestions. workaround, hacks are appreciated.

**Comment by karimnaaji** [comment]
I haven't been able to reproduce the issue mentioned with the following sequence of API calls:

<img width="1123" alt="Screen Shot 2021-06-23 at 3 19 40 PM" src="https://user-images.githubusercontent.com/7061573/123175302-70292800-d436-11eb-934b-5c8f4af8a4c0.png">

Could you demonstrate that issue in a running example on [jsfiddle](https://jsfiddle.net/)?

**Comment by karimnaaji** [comment]
Closing this ticket as we're missing out important information on the reproduction steps, but please feel free to reopen with more information.
