### ISSUE TITLE
Double Click zoom around center

### ISSUE THREAD

**Issue by zurbergram** [mapbox/mapbox-gl-js#10770]
## Motivation
Both ScrollZoomHandler and TouchZoomRotateHandler allow for the option object `{around: 'center'}` to be passed in when enabling and affect where zooming is on.

DoubleClickZoomHandler does not have a similar option to pass to ClickZoom and TapZoom in its enable function.

### Implementation
```
map.doubleClickZoom.enable({around: 'center'});
```
In ClickZoom and TouchZoom set and use this option when zooming is happening.

**Comment by ryanhamley** [comment]
I think the idea is that `around: 'center'` doesn't make as much sense for click/touch zooms. Those are inherently point-based events so it makes sense to use the point from the event as the point around which to zoom. @ansis what are you thoughts on this?

**Comment by zurbergram** [comment]
Double clicking is not zooming on mouse pointer at https://staging.va.gov/gi-bill-comparison-tool-sandbox/?search=location it instead zooming somewhere else to the right. Note this might start double click zooming on center because a change to disable default double click behavior and use `map.on('dblclick', ()={})` to do desired behavior.

mapbox-gl 1.12.0 (can't upgrade at this time)



https://user-images.githubusercontent.com/1094999/122062942-d9b59080-cdbd-11eb-98e6-50cb4171e195.mov

**Comment by ryanhamley** [comment]
Hmm that's not the default behavior of double click. It _should_ be zooming on the clicked point. Can you provide a minimal reproduction in JSBin/JSFiddle of that behavior if you think there's something wrong?

**Comment by karimnaaji** [comment]
>Note this might start double click zooming on center because a change to disable default double click behavior and use map.on('dblclick', ()={}) to do desired behavior is being worked on.

@zurbergram I see that the page page now works as you desired (e.g. double click zooming on center). Could you post the snippet of code you used for posterity in case someone else is trying to achieve the same? This would help until we decide on a behavior.

>I think the idea is that around: 'center' doesn't make as much sense for click/touch zooms. Those are inherently point-based events so it makes sense to use the point from the event as the point around which to zoom.

For parity and completeness I agree with this proposal and think that `DoubleClickZoomHandler` should offer the same option, because we could make the same argument for `TouchZoomRotateHandler` to be point-based, since it is centered on the pinch/touch gesture. I'll mark this as good-first issue as it seems like a small addition improving API completeness.

**Comment by zurbergram** [comment]
> Hmm that's not the default behavior of double click. It _should_ be zooming on the clicked point. Can you provide a minimal reproduction in JSBin/JSFiddle of that behavior if you think there's something wrong?

This was done with a fairly standard looking [usage of mapboxgl](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx#L42) with only a [css tweak to allow for a larger size](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi-sandbox/sass/partials/_gi-search-location.scss#L58)

**Comment by zurbergram** [comment]
> > Note this might start double click zooming on center because a change to disable default double click behavior and use map.on('dblclick', ()={}) to do desired behavior is being worked on.
> 
> @zurbergram I see that the page page now works as you desired (e.g. double click zooming on center). Could you post the snippet of code you used for posterity in case someone else is trying to achieve the same? This would help until we decide on a behavior.

[The double click function](https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/applications/gi-sandbox/containers/search/LocationSearchResults.jsx#L85) code was borrowed and modify from https://github.com/mapbox/mapbox-gl-js/blob/v1.12.0/src/ui/handler/click_zoom.js#L19

**Comment by zurbergram** [comment]
The longitude and latitude returned in MapMouseEvent for a double click event are not correct based on mouse pointer, it consistently returns values way off to the left of the actual mouse pointer.

**Comment by rreusser** [comment]
A couple things I notice are that the map container is a [`<map>` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/map), which may be something different than what's intended here. It relates to clickable polygons. I wonder if it could be affecting the mouse coordinates returned. I also notice that the map container has a couple flex css properties. One thing you might try, if all else fails, is to apply those properties to a _wrapper_. It might then be possible to style the map container as a regular block element. (It _might_ be necessary to apply position: relative to the wrapper and `position: absolute; top: 0; right: 0; bottom: 0; left: 0` to the map element, which is not ideal, though it might help eliminate CSS interactions as a cause.)
