### ISSUE TITLE
Total crash in Mobile Safari on iOS Simulator

### ISSUE THREAD

**Issue by MauriceConrad** [mapbox/mapbox-gl-js#10785]
## Problem

The whole web page crashes and shows the message `A problem repeatedly occurred`, when opening any page with any MapboxGL map within Mobile Safari on iOS Simulator (part of XCode  Dev Tools).

## Why it's an important issue

This currently only happens on iOS Simulator's Safari and I did not got recognized the same behavior on a real-world Mobile Safari which is currently out there. But I think it's an important issue because of the fact that the iOS Simulators Safari is always a copy of the original Safari software (with superficial differences). And the fact that this seems to be a blackboxed internal web engine error of WebKit offers the possibility that we will see the same problem in future WebKit versions. iOS Simulator is also widely being used to debug real-world behavior of Mobile Safari (because it's normally more or less exactly the same software)

**all versions**:

**Mobile Safari / iOS Simulator version 12.5 (Simulator Kit 609, CoreSimulator 757.5**: 

### Steps to Trigger Behavior

 1. Open any web page including a MapboxGLmap (e.g. [https://docs.mapbox.com/playground/gl-js-usage/](https://docs.mapbox.com/playground/gl-js-usage/)) in iOS Simulator's Safari (Version 12.5)

![Bildschirmfoto 2021-06-17 um 15 08 39](https://user-images.githubusercontent.com/12884009/122402605-eaad0000-cf7d-11eb-96d9-aa3d204f8f2c.png)

**Comment by ansis** [comment]
This looks like the same issue as https://github.com/mapbox/mapbox-gl-js/issues/10260, right?
Unfortunately we probably can't do anything to fix this on our end but reporting it to Apple may help.
