### ISSUE TITLE
Id is undefined for clusters by using promoteId

### ISSUE THREAD

**Issue by enersis-pst** [mapbox/mapbox-gl-js#10786]
If promoteId is set, id for clusters are undefined. It is only set by using promoteId: "cluster_id"

**mapbox-gl-js version**:
2.3.0

**browser**:
all

### Steps to Trigger Behavior

 1. open demo
 2. click on big circle (cluster)
 3. have a look at console

### Link to Demonstration
https://jsbin.com/cagaculite/edit?html,js,console,output

### Expected Behavior
for clusters the cluster_id would be still used for id

### Idea 
there could be the case, that by using clusterProperties there would be the same field like it was defined for promoteId. In that case it maybe make sense to use that instead. So i would prefer to overwrite it by cluster_id if the field of promoteId return undefined.

**Comment by ryanhamley** [comment]
This seems to be the same or a very similar issue to https://github.com/mapbox/mapbox-gl-js/issues/10094 so I think we should consolidate on that ticket. I'll close this issue, but this does seem to be a bug so we'll investigate it. Thanks for the report and the demonstration! They'll be very helpful.
