### ISSUE TITLE
A more realistic street width rendering on high zoom levels

### ISSUE THREAD

**Issue by CptHolzschnauz** [mapbox/mapbox-gl-js#10805]
## Motivation

At high zoom levels (higher about 19), the roads remain disproportionately thin. What works really well when rendering with smaller zoom levels is just completely missing the reality at high zoom. 

Example:

Here (Zoom level +-16)  the drawn road is approximately realistic: 

<img width="362" alt="Bildschirmfoto 2021-06-24 um 14 24 49" src="https://user-images.githubusercontent.com/68701579/123263167-f9089800-d4f8-11eb-8ec4-d3289271b3f5.png">

With zoom level 22 the drawn road would be about as wide as a hotdog long...

<img width="1169" alt="Bildschirmfoto 2021-06-24 um 14 25 03" src="https://user-images.githubusercontent.com/68701579/123263435-3ec56080-d4f9-11eb-833d-16c19c3af79e.png">

## Design Alternatives / Solution

From zoom level 18 no longer reduce the size of the road.

**Comment by karimnaaji** [comment]
Hi, I think you need to adjust your styling rules to match the desired behavior there. If it's too short, you need to have stops that reflect how much larger your road needs to be at max zoom.

A small example increasing the size at zoom 22:

https://user-images.githubusercontent.com/7061573/123304832-43c3e900-d4d4-11eb-998b-328b39468975.mov

Closing this ticket as this is a styling issue and not an issue with the library.
