### ISSUE TITLE
Navigation View Ui (turn by turn)

### ISSUE THREAD

**Issue by pranavshahWanbuffer** [mapbox/mapbox-gl-js#10806]
1. How to finish activity when i reach destination point in mapbox.
2. How to customize navigation view ui(turn by turn) in mapbox.

**Comment by karimnaaji** [comment]
Hi, unfortunately it's not really clear what you're trying to achieve from your brief description. Our issue tracker is for reporting bugs and feature requests. For "how to" questions, I suggest contacting support@mapbox.com.
