### ISSUE TITLE
easeTo to a clustered feature and zoom in until it is unclustered.

### ISSUE THREAD

**Issue by vchrisb** [mapbox/mapbox-gl-js#10810]
**mapbox-gl-js version**: v2.3.1

### Question

I have a map with a geojson source, with a clustered and non-clustered symbol layer.
I would like to easeTo to the location of a feature and if the feature is currently clustered, also zoom in, until it is visible.

Is there a way to query for a given feature, if it is currently not rendered, what the parent cluster is? Or ideally is there an equivalent to `getClusterExpansionZoom` for a feature?

Currently I use `queryRenderedFeatures` with a filter to find out if the feature is rendered, if not I zoom in and query again. I loop until the Feature is rendered.  
This approach isn't very efficient and might involve many easeTo steps.

**Comment by mourner** [comment]
There's no direct way to do this. However, one workaround would be to use the `getClusterChildren` method after the initial query, iterating over all features and clusters inside recursively until the feature is found while keeping track of the zoom level, and finally zoom to the feature with that zoom. It's a little involved code-wise but should be a much better user experience than multiple easeTo steps.

**Comment by vchrisb** [comment]
Thank you. Are the clusters actually generated when a source is loaded/updated or generated on the fly when zooming?

**Comment by mourner** [comment]
They're generated once after the source is loaded. See the Supercluster library for the source.

**Comment by vchrisb** [comment]
Thx. I was able to implement it.
It is either only one easeTo if the marker location is visible in the current map container or two, if the marker location has first get into the viewable area.
