### ISSUE TITLE
No panning inertia on certain models of iPhone

### ISSUE THREAD

**Issue by samkuhn** [mapbox/mapbox-gl-js#10816]
We're hoping to launch a Mapbox GL JS based microsite today and have had reports from testers on iOS that panning inertia isn't kicking in after dragging the map and letting go.

The affected phones so far are:

iPhone 11 pro / iOS 14.6
iPhone 8 plus / iOS 14.2 

The inertia isn't working in either Safari or Chrome.

It works perfectly on my iPhone 7 / iOS 14.6 in both browsers so it seems tied to model rather than iOS version..

It's not the end of the world but just seeing if anyone has any ideas for a quick fix as it does add a lot to the experience.

Thanks.

**Comment by asheemmamoowala** [comment]
@samkuhn If this problem still persists, could you share a reproducible case to help us diagnose the underlying issue. In such scenarios a screen recording with touch point recording are very helpful as well.

**Comment by samkuhn** [comment]
Hi @asheemmamoowala, Thanks for getting back and apologies for the lack of a test case there just wasn't time unfortunately. 

We have since discovered that this line was preventing inertia when panning the map:

if (options.animate === false || !options.essential && ref_properties.exported.prefersReducedMotion)
 options.duration = 0;

Which I guess is fair enough since the user opted out of motion - although they didn't seem aware that they had.
