### ISSUE TITLE
benchmark test start error

### ISSUE THREAD

**Issue by YeomanYe** [mapbox/mapbox-gl-js#10819]
**mapbox-gl-js version**:
master branch

**browser**:

### Steps to Trigger Behavior

 1. npm install
 2. APBOX_ACCESS_TOKEN=pk.eyJ1IjoiZndoZWFydCIsImEiOiJja3FicGZjdzAwZ2QyMzJxcXlxdTFkeWQ5In0.OwfBKui6EuzmGHHkntwytQ yarn start
 3. open browser http://localhost:9966/bench/versions

### Expected Behavior
benchmarks.js load success and start service normal

### Actual Behavior
benchmarks.js load error and report 403 Forbidden

![image](https://user-images.githubusercontent.com/18027354/124564755-f51f3300-de73-11eb-99af-441a9eb587d0.png)

**Comment by ryanhamley** [comment]
Hi @YeomanYe I think if you just don't set your own access token, this should work. I will note however that these are largely for internal use and in fact have mostly been supplanted by other internal tools. We likely won't be putting more development work into maintaining or expanding this benchmark suite.

**Comment by YeomanYe** [comment]
> Hi @YeomanYe I think if you just don't set your own access token, this should work. I will note however that these are largely for internal use and in fact have mostly been supplanted by other internal tools. We likely won't be putting more development work into maintaining or expanding this benchmark suite.

Thank you for your reply.If you don't maintain the tool, how do you test performance metrics?

**Comment by ryanhamley** [comment]
We have internal tooling now that is more robust than this suite. We test performance metrics frequently and monitor it week over week to ensure GL JS stays performant.
