### ISSUE TITLE
Pass raw event object during mouse events.

### ISSUE THREAD

**Issue by lsimkins** [mapbox/mapbox-gl-js#1084]
There may be a deliberate reason for not doing this - but is there any chance you can pass the raw javascript event object for mouse events?

The benefit is access to extra event data (like ctrlKey, shiftKey, etc).

If there is a specific reason for not passing the event object I'll grab mouse events externally rather than using built-in mouse events.

**Comment by mourner** [comment]
That sounds useful, feel free to submit a PR! It's pretty easy to add.

**Comment by lsimkins** [comment]
Awesome to hear! You'll see one soon.

**Comment by lsimkins** [comment]
Closing - will submit PR for the issue.
