### ISSUE TITLE
Change miles with KM

### ISSUE THREAD

**Issue by mbio1986** [mapbox/mapbox-gl-js#10873]
Hello

I recently started to use mapbox GL JS  Wordpress Plugin. I have limited technical skills unfortunately.

As you can see on the picture attached, by default we have distances in miles. However my business is active in Europe and therefore using KM.

Could you please let me know where I could make the change, ideally from GL JS Wordpress pluging menu ?

<img width="694" alt="Capture" src="https://user-images.githubusercontent.com/86351244/125952997-5049c20f-25d1-404c-9e5c-b64730617774.PNG">

Thanks in advance

**Comment by ryanhamley** [comment]
Please contact the plugin's maintainer for support https://www.mapster.me/wp-mapbox-gl-js/contact/
