### ISSUE TITLE
Issue with Text colour Vs Background colour same

### ISSUE THREAD

**Issue by mbio1986** [mapbox/mapbox-gl-js#10872]
Hello

I recently started to use mapbox GL JS  Wordpress Plugin. I have limited technical skills unfortunately.

As you can see on the picture attached, the text colour of the directions functions is the same colour as the background colour. Could you please let me know how can I make the text colour white, and where exactly should I do that, ideally from GL JS Wordpress PLugin ? 

<img width="694" alt="Capture" src="https://user-images.githubusercontent.com/86351244/125952997-5049c20f-25d1-404c-9e5c-b64730617774.PNG">

Thanks in advance

**Comment by ryanhamley** [comment]
Please contact the plugin's maintainer for support https://www.mapster.me/wp-mapbox-gl-js/contact/

**Comment by mbio1986** [comment]
Thanks a lot Ryan for your answer.

I will contact support as mentioned

Gaetan
