### ISSUE TITLE
Marker is moving on zoom and is outside the map

### ISSUE THREAD

**Issue by SimonJ** [mapbox/mapbox-gl-js#10871]
**mapbox-gl-js version**:
2.3.1
### Question

Am using Vuejs version 3 where I in my method init the map and put a Marker on the map. But the map is "outside" the map and when i zoom in the zoom, the Marker is moving also.
Can't find anything in the docs about this and am not sure what do to do to debug it.

I have not included any CSS. do I need to do that?

## Video
Here is a video showing the issue
https://www.icloud.com/iclouddrive/0zqZVFigBSZH3x2pSL6ryRzSg

## Code snippet

This is the method where i init the map from a mounted function

```javascript
    methods: {
        initMap() {
            this.$nextTick(() => {
                mapboxgl.accessToken = this.accessToken;

                let map = new mapboxgl.Map({
                    container: "mapContainer",
                    attributionControl: false,
                    style: "mapbox://styles/simonij/ckr4pmuh50ori18jzd95p2xno",
                    center: [this.lat, this.lon],
                    zoom: 19,
                });

                var marker2 = new mapboxgl.Marker({ color: 'black' })
                    .setLngLat([this.lat, this.lon])
                    .addTo(map);


            });
        },
}
```

The map
```html
<div v-if="showMap">
    <div id="mapContainer" class="basemap"></div>
</div>
```

**Comment by ryanhamley** [comment]
>I have not included any CSS. do I need to do that?

Yes, the CSS is required for markers and map positioning to work correctly

**Comment by martin-richter-uk** [comment]
@ryanhamley What CSS have you added specifically?

**Comment by ryanhamley** [comment]
@martin-richter-uk GL JS includes a CSS file that is required for a lot of things to be positioned and rendered properly. See our [Quickstart guide](https://docs.mapbox.com/mapbox-gl-js/api/#quickstart) for more info.
