### ISSUE TITLE
Direction Walking - Forcing to use Ferry

### ISSUE THREAD

**Issue by mbio1986** [mapbox/mapbox-gl-js#10874]
Hello

I recently started to use mapbox GL JS Wordpress Plugin. I have limited technical skills unfortunately.

As you can see on the picture attached, when I select directions with "walking mode" the map is forcing me to use a Ferry. However I would like to ensure that when I select Walking, my journey will exclusively be using "walk" as means of transportation.

Could you please let me know where I could make the change, ideally from GL JS Wordpress pluging menu ?

Thanks in advance.
Gaetan
<img width="760" alt="Capture" src="https://user-images.githubusercontent.com/86351244/125953925-53abcf50-44b9-4edd-979a-6c670f2d985d.PNG">

**Comment by ryanhamley** [comment]
Hi @mbio1986 unfortunately we do not maintain this Wordpress plugin so I can't really offer much insight here. I'm not sure if what you're asking for is doable or not. I think your best bet here is to contact [support for the plugin](https://www.mapster.me/wp-mapbox-gl-js/contact/). You can also contact [Mapbox support](https://support.mapbox.com/hc/en-us). Best of luck!
