### ISSUE TITLE
map.featuresAt returns an empty array

### ISSUE THREAD

**Issue by mofoyoda** [mapbox/mapbox-gl-js#1088]
I have a map with a vector source, that uses PBF tile service. featuresAt is called on click event like this:
```    
map.on('click', function(e) {
      map.featuresAt(e.point, {radius: 5, layer: 'plots'}, function(err, features) {
          if (err) throw err;
          console.log(features);
      });
  });
```
But returns an empty array every time click is fired. How can I get coords and attributes of a single feature at specified coordinates? I need to highlight it on hover, recolour on click and display attributes in a div.

**Comment by jfirebaugh** [comment]
Does the `plots` layer have `"interactive": true` set in the style? This is currently necessary for using `featuresAt`.

**Comment by mofoyoda** [comment]
Yes it does. My style is very simple:
```
var mstyle = {
  "version": 7,
  "constants": {
    "@plots": "#e3b887",
    "@bg": "#ffffff"
  },
  "sources": {
    "vtiles": {
      "type": "vector",
      "tiles": ["http://127.0.0.1:7777/tiles/{z}/{x}/{y}.pbf"]
    }
  },
  "layers": [
   {"id": "plot",
    "type": "fill",
    "interactive": true,
    "source": "vtiles",
    "source-layer": "plots",
    "paint": { "fill-color": "@plots" }
   } ]
};
```

**Comment by jfirebaugh** [comment]
I regressed the `layer` option to `featuresAt` in the latest release. Sorry about that. Fix is above, will merge as soon as CI passes.

**Comment by mofoyoda** [comment]
@jfirebaugh Did the fix pass CI? I still have an empty array in result. 
I get mapbox-gl.js from here:
```<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.7.0/mapbox-gl.js'></script>```

**Comment by mofoyoda** [comment]
Also tested on local cloned master. Same empty array for ```featuresAt```.

**Comment by jfirebaugh** [comment]
@mofoyoda We close issues when they are fixed in master, which is before they are in a released version. This fix will be in v0.8.0 -- if you need it urgently, please clone the repository and obtain the sources from there.

**Comment by mofoyoda** [comment]
@jfirebaugh That's exactly what I did: cloned from this repo, npm installed and switched my web page to local versions
```<script src='mapbox-gl.js'></script>
    <link href='mapbox-gl.css' rel='stylesheet' />```

Still no luck - ```featuresAt``` returns an empty array. Any clues?

**Comment by jfirebaugh** [comment]
Sorry, I missed your comment where you said you were using master.

It looks like `featuresAt` is totally broken on master. [`TilePyramid#tileAt()`](https://github.com/mapbox/mapbox-gl-js/blob/691b431db16d96b7c923c533bf2d504b72947ebd/js/source/source.js#L72-72) always returns null.

@ansis Can you look at this? First guess it's related to tilt changes.

**Comment by jjjiia** [comment]
is featuesAt still supported in the latest mapbox?

**Comment by lbud** [comment]
@jjjiia `Map#featuresAt` was replaced with [`Map#queryRenderedFeatures`](https://www.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures) [in v0.16.0](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#breaking-changes-4).
