### ISSUE TITLE
Terrain wait until fully loaded 

### ISSUE THREAD

**Issue by traingethermarc** [mapbox/mapbox-gl-js#10906]
Hello,
I did a lot of research about how to check, if the map is fully loaded. I want to wait until all terrain tiles (with Satellite style) are fully loaded and no black areas are visible.

I basically read every thread about this and tried sooo many things.

• idle event, styleload, style.load, render etc. with all timeout workarounds
• loaded(), areTilesLoaded()…
• different timeout things in combination with event  
• checked if different sources mapbox etc. are loaded
• checked if different layers are loaded 
…. 

It seems like the approaches mentioned on GitHub, stack etc. are not made for 3D terrain?
Any ideas?

**Comment by ryanhamley** [comment]
`idle` should work for this use case. See https://jsbin.com/henoyumaja/edit?html,output for an example. Can you share a minimal example of your setup where `idle` is firing before rendering is done?

**Comment by traingethermarc** [comment]
Hi @ryanhamley thanks for your reply! I‘am using headless puppeteer chromium to render the frames - then I guess it has to do something with it…? I did a lot of research about it already, but haven’t found something useful. It seems like the events there are not working correct or a problem with webgl headless? Do you know a solution or workaround? Thank you so much!

**Comment by traingethermarc** [comment]
And it‘s more about the black „squares“ while loading. 
![Uploading 06909E3B-B85B-4D84-AE05-839BEE9C1121.png…]()

**Comment by ryanhamley** [comment]
We have seen sporadic issues reported about using GL JS in Puppeteer. https://github.com/mapbox/mapbox-gl-js/issues/9920 sounds like what you're reporting. You can also check out https://github.com/mapbox/mapbox-gl-js/issues/7721. In general, GL JS does work in Puppeteer; we even use Puppeteer for some of our test infrastructure. I don't think this is an issue with GL JS itself, so I'm going to close this issue. If you need more help getting things set up, I'd recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us).

**Comment by SnailBones** [comment]
Any chance that this meets your needs?
```
map.on('sourcedata', (e) => {
    if (e.source.type === "raster-dem") {
        ...
    }
});
```
