### ISSUE TITLE
Dynamic (or multiple) transformRequest

### ISSUE THREAD

**Issue by markusand** [mapbox/mapbox-gl-js#10908]
As suggested in [this answer](https://github.com/mapbox/mapbox-gl-js/issues/7284#issuecomment-891398150) I create this feature request to open a discussion about the convenience of its implementation.

## Motivation

With popularization of mapping solutions and reactive frameworks, it is not strange nowadays to create maps that combine multiple data sources (including self hosted tiles servers) and add/remove them dynamically under user demand.

This sources may require authentication tokens and the need to dynamically set/unset request headers via transformRequest.  

## Design

At the moment transformRequest can only be defined on map creation. It would be convenient to have some method(s) to update the transformRequest function according to dynamic sources needs.

How would this affect other sources?

If the method overrides the transformation, it is developer's responsibility to handle the edge cases.

An option would be to make it composable with add/remove methods.

Another option would be to define the transformation per source instead of per map, and apply it internally by mapbox on request time when needed.

### Implementation

Mapbox public API could look something like

```javascript
map.setTransformRequest((url, resourceType) => {
  ...
});
```

or

```javascript
map.addTransformRequest('name', (url, resourceType) => {
  ...
});
map.removeTransformRequest('name');
```

or even

```javascript
map.addSource('id', {
  type: 'vector',
  url: '...',
  transformRequest: (url, resourceType) => { ... },
  ...
})

```

**Comment by asheemmamoowala** [comment]
> At the moment transformRequest can only be defined on map creation. It would be convenient to have some method(s) to update the transformRequest function according to dynamic sources needs.

@markusand The current mechanism allows setting a `transformRequest` method with your implementation being dynamic, i.e the function can branch based on URL patterns and resource type. One way to do this would be to have your own application manage the additional transformers.

**Comment by ssontag55** [comment]
@asheemmamoowala So we can't update this after map creation?  We are having an issue where we don't have the session toekn or the session token changes after the map is created.

**Comment by markusand** [comment]
This is how I solved it

```javascript
const authenticators = {};

const map = new Map({
  container: 'map',
  transformRequest: url => Object.values(authenticators)
      .reduce((acc, authenticator) => authenticator(url) || acc, { url }),
});

const addAuthenticator = (baseURL, token) => {
  const headers = { Authorization: `Bearer ${token}` };
  authenticators[baseURL] = url => url.startsWith(baseURL)) ? { url,  headers } : { url };
}

const deleteAuthenticator = baseURL => delete authenticators[baseURL];
```

**Comment by ssontag55** [comment]
@markusand thanks. A bad way that is working well for us now is 
`map._requestManager._transformRequestFn = addHeaderToSource;`
