### ISSUE TITLE
FullscreenControl button does not appear on the map

### ISSUE THREAD

**Issue by babkouew** [mapbox/mapbox-gl-js#10902]
**mapbox-gl-js version**: 6.1.16

**browser**: Firefox, Chrome, Safari

### Steps to Trigger Behavior
 1. NavigationControl button is implemented and shows on the top-left
 2. With same implementation as above the FullScreenControl button doesn't show on the top-right

### Link to Demonstration
https://codesandbox.io/s/guinea-map-75bjx?file=/src/App.js:831-876

### Expected Behavior
FullscreenControl button must show on top-right

### Actual Behavior
FullscreenControl button doesn't show on top-right

**Comment by rreusser** [comment]
There's [documentation for the FullscreenControl](https://github.com/visgl/react-map-gl/blob/db08714945b106062a9e8b87722a8c0e343eb3de/docs/api-reference/fullscreen-control.md) here, but this team doesn't develop or support the `react-map-gl` library. You can find a plain Mapbox GL fullscreen example [here](https://docs.mapbox.com/mapbox-gl-js/example/fullscreen/). I think the best place to start would be with the example in the `react-map-gl` docs and on their issue tracker if it doesn't work.

**Comment by babkouew** [comment]
That's right, I posted on the right thread. Thanks for your prompt reply.
