### ISSUE TITLE
some tiles did not display at sometimes

### ISSUE THREAD

**Issue by yijialee** [mapbox/mapbox-gl-js#10921]
**mapbox-gl-js version**:  v2.4.0

**browser**: Edge latest

### Steps to Trigger Behavior

 1. add source 
 ```
map.addSource('custom-go-vector-tile-source-dltb1000wabi', {
                type: 'vector',
                'tileSize': 512, scheme: "xyz", 
                tiles: [ 
                       'https://gademo..cn/tiles/{z}_{x}_{y}.pbf'
                       ] 
            });
```
 2. add layer
 ```
map.addLayer({
                "id": "custom-go-vector-tile-layer-dltb1000wabi",
                "type": "fill",
                "source": "custom-go-vector-tile-source-dltb1000wabi",
                "source-layer": "dltb1000wabi",
                "paint": {
                    // "fill-color": "#ff0000",
                    "fill-color": [
                        'case',
                        ['==', ['get', 'dlbm'], "126"], '#F0F8FF',
                        ['==', ['get', 'dlbm'], "105"], '#FAEBD7',
                        ['==', ['get', 'dlbm'], "202"], '#00FFFF',
                        ['==', ['get', 'dlbm'], "121"], '#7FFFD4',
                        ['==', ['get', 'dlbm'], "127"], '#F0FFFF',
                        ['==', ['get', 'dlbm'], "122"], '#F5F5DC',
                        ['==', ['get', 'dlbm'], "113"], '#FFE4C4',
                        ['==', ['get', 'dlbm'], "104"], '#000000',
                        ['==', ['get', 'dlbm'], "042"], '#FFEBCD',
                        ['==', ['get', 'dlbm'], "011"], '#0000FF',
                        ['==', ['get', 'dlbm'], "111"], '#8A2BE2',
                        ['==', ['get', 'dlbm'], "033"], '#A52A2A',
                        ['==', ['get', 'dlbm'], "022"], '#DEB887',
                        ['==', ['get', 'dlbm'], "204"], '#5F9EA0',
                        ['==', ['get', 'dlbm'], "021"], '#7FFF00',
                        ['==', ['get', 'dlbm'], "116"], '#D2691E',
                        ['==', ['get', 'dlbm'], "107"], '#FF7F50',
                        ['==', ['get', 'dlbm'], "124"], '#6495ED',
                        ['==', ['get', 'dlbm'], "041"], '#FFF8DC',
                        ['==', ['get', 'dlbm'], "125"], '#DC143C',
                        ['==', ['get', 'dlbm'], "032"], '#00FFFF',
                        ['==', ['get', 'dlbm'], "043"], '#00008B',
                        ['==', ['get', 'dlbm'], "101"], '#008B8B',
                        ['==', ['get', 'dlbm'], "205"], '#B8860B',
                        ['==', ['get', 'dlbm'], "023"], '#A9A9A9',
                        ['==', ['get', 'dlbm'], "201"], '#006400',
                        ['==', ['get', 'dlbm'], "102"], '#BDB76B',
                        ['==', ['get', 'dlbm'], "031"], '#8B008B',
                        ['==', ['get', 'dlbm'], "203"], '#556B2F',
                        ['==', ['get', 'dlbm'], "112"], '#FF8C00',
                        ['==', ['get', 'dlbm'], "114"], '#9932CC',
                        ['==', ['get', 'dlbm'], "117"], '#8B0000',
                        ['==', ['get', 'dlbm'], "118"], '#E9967A',
                        ["rgba", 200, 200, 00, 0.5]
                    ],
                    "fill-outline-color": "#000" //"#E9967A"
                }
            });
```
 3.

### Link to Demonstration

https://codepen.io/yijialee/pen/QWvzaXQ

### Expected Behavior
it shoud to show all of the vector tiles

### Actual Behavior
some tiles is invisible sometimes, some tiles never show on screen , all pbf files  are existed.
sometimes i  zoom the map to a new level ,it did not request new tiles.

![lALPD4BhuNwf_3zNAwXNBSw_1324_773](https://user-images.githubusercontent.com/6447599/128833261-b6bf6f75-da3a-41ce-8d58-835218230555.png)

![lALPD3zUOjdXL2TNAs3NBUI_1346_717](https://user-images.githubusercontent.com/6447599/128833347-3acfb031-1da2-4d7e-96f2-e86b6286857d.png)

**Comment by mourner** [comment]
I traced this to a bug in [Earcut](https://github.com/mapbox/earcut) where some of the polygons in these tiles are malformed and cause an infinite loop in the library — investigating further. I don't think this is possible with Mapbox vector tiles though, and happens specifically on data coming from ArcGIS in this case, so it's a combination of an Earcut bug and Esri not providing valid polygons in their version of Mapbox vector tiles.

**Comment by yijialee** [comment]
> I traced this to a bug in [Earcut](https://github.com/mapbox/earcut) where some of the polygons in these tiles are malformed and cause an infinite loop in the library — investigating further. I don't think this is possible with Mapbox vector tiles though, and happens specifically on data coming from ArcGIS in this case, so it's a combination of an Earcut bug and Esri not providing valid polygons in their version of Mapbox vector tiles.

thanks,I will check the mvt file.  it's not pbf from arcgis service, but vector tiles encoded by no.ecc.vectortile java package.
I am trying to create a java tile service.

**Comment by mourner** [comment]
@yijialee here's a minimal test case from one of the tiles above that causes an infinite loop: https://github.com/mapbox/earcut/issues/149

**Comment by yijialee** [comment]
> @yijialee here's a minimal test case from one of the tiles above that causes an infinite loop: [mapbox/earcut#149](https://github.com/mapbox/earcut/issues/149)

Thank you very much. it happens when i try to convert lon&lat to tile x&y ,I fixed it and it was OK now.
