### ISSUE TITLE
How to dynamic update source properties

### ISSUE THREAD

**Issue by Drealler** [mapbox/mapbox-gl-js#10924]
I'm drawing orders on the map using layers with symbols, this orders has status. Whenever the status changes I'd like to change de color of the symbol.

My layer has this configuration:
```
map.current?.addLayer({
        id: "orders",
        type: "symbol",
        source: "order-markers",
        layout: {
          "icon-image": [
            "match",
            ["get", "orderStatus"],
            "UNASSIGNED",
            "unassigned-marker",
            "ASSIGNED",
            "assigned-marker",
            "IN_TRANSIT",
            "intransit-marker",
            "CONCLUDED",
            "concluded-marker",
            "UNASSIGNED-marker",
          ],
        },
      });
    });
```

Is there a recommended way to directly access the source and update the status ? Or is it right to always overwrite the object calling setData ?
After the change it will auto update its icon-image ?

Thanks.

**Comment by mourner** [comment]
There's no way to selectively change feature properties due to the way GeoJSON data is processed for rendering under the hood. So inline update and a `setData` seems like a suitable option. Another one you might explore is using `map.setFeatureState` for features that updated their status.
