### ISSUE TITLE
Vector tile data rendered incorrectly if extent != 4096

### ISSUE THREAD

**Issue by paulmach** [mapbox/mapbox-gl-js#1093]
It looks like all vector tiles get rendered the same regardless of the extent value in the pbf file. By default this value is 4096 so usually everything is fine. However, [tippecanoe](https://github.com/mapbox/tippecanoe) generates tiles with extents of 1024 and 2048 and those display incorrectly in mapbox-gl-js

I created an example gist (sorry no live version) that renders 3 vector tiles, each with the same short linestring data. The only difference is the extent values in the file (no other values changed or scaled). All are rendered on top of each other, when that is not correct. https://gist.github.com/paulmach/14fcf55bc67e8abdff62  Here is what it looks like:
![screen shot 2015-03-15 at 12 04 02 pm](https://cloud.githubusercontent.com/assets/366320/6657491/6cc82502-cb0b-11e4-849c-b451dd49ef5d.png)

FYI @ericfischer

**Comment by incanus** [comment]
Native side: https://github.com/mapbox/mapbox-gl-native/issues/250

**Comment by tmcw** [comment]
https://github.com/mapbox/mapbox-gl-js/blob/master/js/render/painter.js#L137

>  the magic number is used for raster and video rendering. Rendering raster and video is just copying a rectangular texture to part of the screen. Each vertex of this rectangle needs to have a position (where on the screen it is), and which part of the texture it is. For some reason that number is used to represent the right/bottom edge of the texture

---

> setup() doesn't need to be called again because it contains a lot of stuff that only runs once. I think instead of having one tileExtentBuffer there needs to be one for every extent. An object that indexes the buffers by extent maybe.
> Or this could be handled on the matrix side by accounting for the difference there. But I think that might be even worse.
> The buffers created in setup can be created sometime later, outside of setup()
> maybe lazily, with painter.getTileExtentBuffer(extent) that creates it if it's missing

**Comment by tmcw** [comment]
https://github.com/mapbox/mapbox-gl-js/pull/1227 was my first shot at this and I'm restarting it with a new branch.

**Comment by tmcw** [comment]
With https://github.com/mapbox/mapbox-gl-js/pull/1234 merged:

We now have support for vector tiles that have an extent that isn't 4096.

Still TODO is supporting vector tiles with _multiple extents_. In order to support that, we'll need to split the Tile class so that `calculateMatrices` doesn't have to constantly recalculate, and split the extent that is output by the WorkerTile to an object of `extents`, indexed by `id || ref`.

**Comment by ericfischer** [comment]
@ansis, here's an example of the problem persisting: http://trafficways.org/gltest/gl.html

It looks reasonable at low zooms, but z12 and beyond are garbage. The vector data is <code>enf.fwimgqfr</code>, and I believe has an extent of 1024 at low zooms and 16384 at z12.

**Comment by ericfischer** [comment]
Must be the Int16Array that will overflow when something goes beyond 32767?

**Comment by jfirebaugh** [comment]
91d2e0ee5cf4ed3811804ef40b1696f93de74410 added another hard-coded 4096.
