### ISSUE TITLE
calculation of distances with different values

### ISSUE THREAD

**Issue by marciotisouza** [mapbox/mapbox-gl-js#10939]
Hi, when I do the search with "directions" and then do the same search with "directions-matrix" the distance values are different, below I'll leave the urls and the results.

curl "https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-46.505909,-23.431929;-46.527718,-23.467348?geometries=geojson&access_token=pk.eyJ1IjoibWFyY2lvc291emEiLCJhIjoiY2pxMHRmM2lhMHA3ZTQzbGdmZ2xtZW8waiJ9.P36sqyfOmBfXcOQmA3xZEA"

{"routes":[{"weight_typical":1200.266,"duration_typical":931.572,"weight_name":"auto","weight":1200.266,"duration":931.572,"distance":5825.034,"legs":[{"via_waypoints":[],"admins":[{"iso_3166_1_alpha3":"BRA","iso_3166_1":"BR"}],"weight_typical":1200.266,"duration_typical":931.572,"weight":1200.266,"duration":931.572,"steps":[],"**distance":5825.034**,"summary":"Avenida Otávio Braga de Mesquita, Avenida Monteiro Lobato"}],"geometry":{"coordinates":[[-46.505931,-23.431949],[-46.505292,-23.432559],[-46.505426,-23.432764],[-46.504326,-23.433049],[-46.505512,-23.435506],[-46.507902,-23.438867],[-46.50766,-23.443311],[-46.508434,-23.447309],[-46.509022,-23.455721],[-46.510938,-23.459069],[-46.51309,-23.464882],[-46.514328,-23.465889],[-46.515326,-23.467879],[-46.516324,-23.468589],[-46.521943,-23.469708],[-46.525611,-23.469672],[-46.527696,-23.467332]],"type":"LineString"}}],"waypoints":[{"distance":3.106,"name":"Rua Trajano de Faria","location":[-46.505931,-23.431949]},{"distance":2.834,"name":"Rua Luís Faccini","location":[-46.527696,-23.467332]}],"code":"Ok","uuid":"F-KtViKdVf0Cc7kYP5mb0tJ2GF58a7xX8I9mfqLwkCag46rTRjxGGw=="}

curl "https://api.mapbox.com/directions/v5/mapbox/driving-traffic/-46.527718,-23.467348;-46.536934,-23.448598?geometries=geojson&access_token=pk.eyJ1IjoibWFyY2lvc291emEiLCJhIjoiY2pxMHRmM2lhMHA3ZTQzbGdmZ2xtZW8waiJ9.P36sqyfOmBfXcOQmA3xZEA"

{"routes":[{"weight_typical":469.699,"duration_typical":347.139,"weight_name":"auto","weight":469.699,"duration":347.139,"distance":2343.693,"legs":[{"via_waypoints":[],"admins":[{"iso_3166_1_alpha3":"BRA","iso_3166_1":"BR"}],"weight_typical":469.699,"duration_typical":347.139,"weight":469.699,"duration":347.139,"steps":[],"**distance":2343.693**,"summary":"Rua Luís Faccini, Avenida Salgado Filho"}],"geometry":{"coordinates":[[-46.527696,-23.467332],[-46.530039,-23.46489],[-46.532833,-23.4597],[-46.533445,-23.457767],[-46.533709,-23.455738],[-46.534135,-23.45438],[-46.534083,-23.453901],[-46.534342,-23.453634],[-46.535195,-23.450917],[-46.53654,-23.4493],[-46.536934,-23.448598]],"type":"LineString"}}],"waypoints":[{"distance":2.834,"name":"Rua Luís Faccini","location":[-46.527696,-23.467332]},{"distance":0,"name":"Avenida Salgado Filho","location":[-46.536934,-23.448598]}],"code":"Ok","uuid":"pp-tHiwNP4G4ckJNNQIasU8JmAD6UMFq-ZVIxQwEnXXJC6m3zwm1jw=="}

curl "https://api.mapbox.com/directions-matrix/v1/mapbox/driving/-46.505909,-23.431929;-46.527718,-23.467348;-46.536934,-23.448598?sources=all&access_token=pk.eyJ1IjoibWFyY2lvc291emEiLCJhIjoiY2pxMHRmM2lhMHA3ZTQzbGdmZ2xtZW8waiJ9.P36sqyfOmBfXcOQmA3xZEA"
{"code":"Ok","durations":[[0.0,1119.1,1105.2],[1131.9,0.0,400.5],[940.0,669.6,0.0]],"destinations":[{"distance":3.156124316,"name":"Rua Trajano de Faria","location":[-46.505931,-23.431949]},{"distance":2.782532155,"name":"Rua Luís Faccini","location":[-46.527697,-23.467332]},{"distance":0.102200468,"name":"Avenida Salgado Filho","location":[-46.536935,-23.448598]}],"sources":[{"**distance":3.156124316**,"name":"Rua Trajano de Faria","location":[-46.505931,-23.431949]},{"**distance":2.782532155**,"name":"Rua Luís Faccini","location":[-46.527697,-23.467332]},{"**distance":0.102200468**,"name":"Avenida Salgado Filho","location":[-46.536935,-23.448598]}]}

angular : 12.1.0
mapbox": 1.0.0-beta10
mapbox-gl : 2.4.0

**Comment by mourner** [comment]
Thank you for the report! However, it seems unrelated to this repository, which specifically tracks issues with the Mapbox GL JS library and its style specification, not any server-side services like the Directions API. Can you please submit the report to the [Mapbox support channel](https://www.mapbox.com/contact/support/) instead? We'll do our best to help you out!
