### ISSUE TITLE
Interpolation doesn't take fractional zoom values into account

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox-gl-js#10934]
The issue is displayed here:
https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/

```javascript
'fill-extrusion-height': [
'interpolate',
['linear'],
['zoom'],
15,
0,
15.05,
['get', 'height']
],
```

This expression tells extrudes to grow up quite fast (from 15 to 15.05 zoom level), but in reality extrusion height grows until it hits whole zoom value of `16`.

**Comment by arindam1993** [comment]
This is a duplicate of 
https://github.com/mapbox/mapbox-gl-js/issues/5760

closing this in favor of continuing the discussion there.
