### ISSUE TITLE
Trying to access unnecessary folders for raster tilemap

### ISSUE THREAD

**Issue by D3vmotiv** [mapbox/mapbox-gl-js#10947]
**mapbox-gl-js version**: 2.4.0

**browser**: firefox 91.0

### Steps to Trigger Behavior

 1. Just start the app

### Link to Demonstration

vuecode: https://jsbin.com/kutecewiha/edit?html,js
my file structure: https://ibb.co/nMPFd6F

### Expected/Actual Behavior
Im trying to render this tilemap, but unsuccessful its trying to get for example /0/0/2.png when the map is place between 17-19 x, and it cause error because our exported tileset doesnt have this folders. Secondly, the layer doesnt corretly render, but when we try demo with this file on export in another lib - its working fine.
For any help, ill be gratefull

**Comment by arindam1993** [comment]
Hey @D3vmotiv please report a bug with an isolated test case, a clear list of steps and with minimal possible external dependencies. Its not possible for us to go through your entire Vue project to reproduce a bug. jsbins/codepns are the preferable.
