### ISSUE TITLE
Remove padding of a projected point 

### ISSUE THREAD

**Issue by simon-milleto** [mapbox/mapbox-gl-js#10945]
**mapbox-gl-js version**: v1.13.0

### Question
Hello, I built a function to remove the padding of coordinates because for some reasons I don't want to handle it with mapbox easeTo function. So I have a function that project coordinates to have a point in pixels, remove padding from it and then unproject this point to get back the coordinates, it looks like this:

```js
project(latLng, zoom, padding) {
    let project = this.map.project(latLng, zoom); // Use map.transform.project behind
    let offset = [
        (padding.left - padding.right) / 2,
        (padding.top - padding.bottom) / 2
    ];

    // Correct with map rotation angle
    const correctionAngle = this.map.getBearing() / 180 * Math.PI;
    const cosC = Math.cos(correctionAngle);
    const sinC = Math.sin(correctionAngle);
    offset = [
        offset[0] * cosC - offset[1] * sinC,
        offset[0] * sinC + offset[1] * cosC
    ];

    project[0] -= offset[0];
    project[1] -= offset[1];

   return project;
}

easeTo(pcenter, zoom, options) {
    const project = this.project(pcenter, zoom, options.padding);
    const center = this.map.unproject(project, zoom); // Use map.transform.unproject behind

    this.map.easeTo({
        center: center,
        zoom: zoom
    });
}
```
But it doesn't work when the map is tilted, I believe I have to add/remove offset accordingly to the pitch of the map but I don't know what kind of formula it can be. How can I update the projected point including the pitch of the map ?

I also posted this question on [stackoverflow](https://stackoverflow.com/questions/68844514/how-to-calculate-projection-with-a-pitched-map)

**Comment by arindam1993** [comment]
@simon-milleto We use the issues section here on GitHub for bugs/feature requests. 

Re: your question I don;t think you need to reimplement `map.project` you can extract the projected value and subract the padding from all sides.

**Comment by simon-milleto** [comment]
@arindam1993 As you mentioned I removed my reimplementation of the project function. But I still have an issue/bug, in my use case the map have a `map.easeTo` function with padding and then a `map.fitBounds` with a different padding. 

Since the map keeps the padding from the `easeTo` function I need to reset the padding of the map in order to have a correct padding for the `fitBounds` function. Unfortunately after the reset of padding and `fitBounds` the map "jumps" and create a weird effect. 

You can try it [here](https://codepen.io/simonmilleto/pen/jOmjaya?editors=1011), first click on "ease to padding" and then "fit bounds padding"
