### ISSUE TITLE
Year Slider in Mapbox

### ISSUE THREAD

**Issue by BrechreizZ** [mapbox/mapbox-gl-js#10949]
Hey there,

i have a small problem with Java Scripting and Mapbox.
The concept is realy easy:

1) I have set up a Mapbox map with a bunch of Places with some propertys like 'Name', 'Year' and so on.
2) Now i want to filter my Mapbox Map by the property 'Year', like if 2 of my Places have the 'Year' set to 1990 i want them to show up
3) while useing the silder from the first 'Year' wich in my case is 1970 to the last one (1995), i want them to show the places year by year.

My Problem:
I am not familier with Java (since its not my profession), i am able to understand small pieces of code and glue them together - thats how i tried to fix my Problem useing Mapbox's own tutorial: https://docs.mapbox.com/help/tutorials/show-changes-over-time/

I got the CSS Part of my Problem already solved, i got a Silder but i dont got the logic behind it.

I would realy like to get some help ;)
Big Thanks!

(If you care: It is for a Webpage wich shows squatted Places in germanys Ruhr-Area)

**Comment by arindam1993** [comment]
Hey @BrechreizZ , best of luck with your project!
I'd recommend posting this to stackoverflow, we use the issues section on GitHub for bug reports and feature requests. Sorry I'm going to have to close this here.
