### ISSUE TITLE
Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by olso** [mapbox/mapbox-gl-js#10953]
<img width="729" alt="Screenshot 2021-08-20 at 13 45 30" src="https://user-images.githubusercontent.com/7975158/130228452-ecdc2d54-1598-4f90-bf4a-c048056d096f.png">

<img width="1679" alt="Screenshot 2021-08-20 at 13 46 32" src="https://user-images.githubusercontent.com/7975158/130228510-29dc5871-23a5-4b23-a478-19fa3c9294f6.png">

<img width="1215" alt="Screenshot 2021-08-20 at 13 46 50" src="https://user-images.githubusercontent.com/7975158/130228537-b3d89fb6-311d-46b5-9813-24b6db816e29.png">

**mapbox-gl-js version**:

**browser**:

### Steps to Trigger Behavior

 1.
 2.
 3.

### Link to Demonstration

https://jsbin.com/

**Comment by rreusser** [comment]
Hi, @olso. Can you describe the setup which causes this issue? Without some sense of what triggered this, it's very difficult to work out what could have caused it. Thank you!

**Comment by olso** [comment]
@rreusser basically go to https://www.seasy.at/ click on card e.g. "Marina Lumbarda" and scroll down fast

**Comment by SnailBones** [comment]
I'm not seeing the issue with your instructions. Would you be able to reproduce this in a codepen/jsbin and let us know what browser and operating system you are using?

**Comment by rreusser** [comment]
Please pardon the delayed reply. I don't doubt the issue, but I also wasn't able to see it on the linked page. Perhaps it was fixed, or maybe it's browser/platform-dependent?

**Comment by rreusser** [comment]
The trace gives hints of what might be happening here, but we haven't been able to reproduce this, so at this point I'm going to close the issue as not actionable. We can work through the above trace on our side, but there are just so many different things that could conceivably be going on that it's not currently actionable without a live reproduction or first narrowing down the conditions which trigger this.

At the moment, the fact that `style.layout.get` is failing with property `get` undefined suggests to me that `style.layout` is undefined, which suggests to me that this might be a loading issue, for example not first waiting for `map.on('load', () => { ... })`, as is a common idiom in many of the Mapbox example (e.g. https://docs.mapbox.com/mapbox-gl-js/example/geojson-line/ )

Please feel free to reopen if you're still seeing this and can assist in narrowing down the conditions which cause it. Thanks!
