### ISSUE TITLE
Typescript definition incomplete

### ISSUE THREAD

**Issue by robbertkl** [mapbox/mapbox-gl-js#10966]
It seems Map's `updateImage()` is missing from the Typescript definition (@types/mapbox-gl).

**Comment by mbullington** [comment]
`@types/mapbox-gl` is managed by DefinitelyTyped, which is a third-party. If you have time, please consider opening a PR there with these changes!

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mapbox-gl

We have a small list of fixes we'll be contributing there soon, but it's really a separate org and not authored by Mapbox.

**Comment by robbertkl** [comment]
Created https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55529, I also spotted incorrect return types (for some reason the image functions don't allow chaining), but I think there might be some more things to fix.

Since the code has flow types, wouldn't it be possible to generate most of the types to automate this process?
