### ISSUE TITLE
Lines rendered skewed

### ISSUE THREAD

**Issue by paulmach** [mapbox/mapbox-gl-js#1097]
![screen shot 2015-03-16 at 11 30 07 pm](https://cloud.githubusercontent.com/assets/366320/6682392/611b5be0-cc35-11e4-9d29-3ddbd0f79eab.png)

Rendering many short lines. I expect them to be basically rotated rectangles, but they are skewed. There does not appear to be any consistency in the way they are skewed. The layer JSON is:
```
{
  "id": "time" + i,
  "type": "line",
  "source": "activities",
  "source-layer": "time10",
  "paint": {
    "line-width": 0,
  },
  "paint.time10on": {
    "line-width": 6,
    "line-color": '#F94D1E',
  },
  "filter": [
    "==",
    "t",
    "Ride"
  ]
}
```
with the `time10on` class added.  I can provide a more detailed test case if needed.

**Comment by ansis** [comment]
Would it be possible to get access to the source?

**Comment by paulmach** [comment]
I might have done something weird, here is an example https://gist.github.com/paulmach/14bb232091a31f24b70d

What I did was use tippeecanoe to generate tiles with extent 256. Then I "manually" multiplied the move-to/line-to geometry values by 16 and set the extent to 4096 so they'd display correctly.  The difference between just having tippeecanoe generage 4096 extent tiles is that the geometry is simplified. I'm dealing with a lot of data and was exploring ways to make the tiles smaller.

I could have a bug here but I don't understand why the lines wouldn't be some form of rectangles, even if in wrong locations.

When I just display the original 256 extent tiles I still see a few skew issues, but there were less of them. And the lines are in the wrong locations as mentioned before in #1093

**Comment by ansis** [comment]
Thanks for the great test case!

One of the lines (with bigger width, transparency and round caps) looks like this:


![screen shot 2015-03-18 at 1 14 07 pm](https://cloud.githubusercontent.com/assets/1421652/6718409/c13eaf04-cd70-11e4-94c4-1bd1558b518a.png)

The point values:

```
[
    {
        "x": 4294968908,
        "y": 1696
    },
    {
        "x": 4294968992,
        "y": 2147485312
    },
    {
        "x": 4294969052,
        "y": 4294968956
    }
]
```

When tessellating the line into triangles it uses these big values to calculate the offsets, but when they are added to the rendering buffers the positions are forced into [a short](https://github.com/mapbox/mapbox-gl-js/blob/c35ca560c20c923ace8f0155b11f7ab19c203da7/js/data/buffer/line_vertex_buffer.js#L35). The positions and the offsets don't correspond so the lines look weird.

Are the coordinates being calculated and encoded correctly? If they are, this could be a pbf decoding issue on our side.

**Comment by paulmach** [comment]
Yes, this was my bad. Signed bit shift issue. I guess the impact was magnified in this test case. Sorry to trouble you.
