### ISSUE TITLE
icon-color doesn't work

### ISSUE THREAD

**Issue by YuriyDyachkov** [mapbox/mapbox-gl-js#10975]
`  map.on('load', () => {
      setIsLoad(true);
      map.addSource('digest', {
        type: 'geojson',
        data: source,
        cluster: true,
        clusterMaxZoom: 14,
        clusterRadius: 40,
      });

      map.addLayer({
        id: 'unclustered-points',
        type: 'symbol',
        source: 'digest',
        filter: ['!has', 'point_count'],
        layout: {
          'icon-image': 'marker-15',
        },
        paint: {
          'icon-color': 'orange',
        },
      });
      
      const cluster = [
        [10, '#e60e0e'],
        [0, '#E7BB95'],
      ];

      cluster.forEach((layer, i) => {
        map.addLayer({
          id: `cluster-${i}`,
          type: 'circle',
          source: 'digest',
          paint: {
            'circle-color': layer[1],
            'circle-radius': 20,
          },
          filter: i === 0
            ? ['>=', 'point_count', layer[0]]
            : ['all',
              ['>=', 'point_count', layer[0]],
              ['<', 'point_count', cluster[i - 1][0]]],
        });
      });
      
      map.addLayer({
        id: 'cluster-count',
        type: 'symbol',
        source: 'digest',
        layout: {
          'text-field': '{point_count}',
          'text-font': [
            'DIN Offc Pro Medium',
            'Arial Unicode MS Bold',
          ],
          'text-size': 12,
        },
      });
    });`

Can you please tell me why this code does not work? The icon does not change color.

**Comment by SnailBones** [comment]
@YuriyDyachkov Can you provide a working codepen demonstrating the issue? Thanks!

**Comment by SnailBones** [comment]
This is intentional. The icon-color field only works with custom [SDF images](https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/).

**Comment by YuriyDyachkov** [comment]
@SnailBones Thanks, I already made a sdf icon using [image-sdf](https://www.npmjs.com/package/image-sdf).
I've got one more question. Is there any way to make such an icon with several colors? I have to achieve the result as in the picture.
I can do this using another circle layer, but on hover, the marker grows in size, and the circle lags in response. Maybe there is some other way?
![image](https://user-images.githubusercontent.com/70245262/131959264-9f27a43a-b58a-4a0d-9b80-d7f52d4d8bf2.png)

**Comment by SnailBones** [comment]
@YuriyDyachkov No problem!

I see two options here. One would be to make a version of the marker in each color and add them to your style. Or if you can use the `mapboxgl.Marker` object which can handle custom colors.

**Comment by YuriyDyachkov** [comment]
@SnailBones I read in the documentation that the marker should not be used if there are more than 20 of them. It significantly slows down performance.  And how can I dynamically change them at the moment, depending on a certain field? Is there an example of such code somewhere?

**Comment by SnailBones** [comment]
@YuriyDyachkov If you have a large number of markers, you'll want to use geojson icons. You can use data expressions to select the [icon-image](https://docs.mapbox.com/mapbox-gl-js/style-spec/types/#resolvedimage) property according to the field.

**Comment by viktorasatiani** [comment]
is this working only on images or also on svgs ? or should i convert SVG to image and then do the same operation ?
