### ISSUE TITLE
Mapox Dynamic Markers with Vue

### ISSUE THREAD

**Issue by alexandruana** [mapbox/mapbox-gl-js#10983]
After digging through the whole documentation for the past two days, I am still facing issues in figuring out how can I use coordinates coming from `props` to populate the map with markers.

Below is the code I have so far, however the function which should automatically add the markers on prop change is missing.

Can anyone assist in putting together that function?

```
export default {
    name: "TripMap",
    data() {
        return {
            locations: {}
        }
    },
    mounted() {
        this.initMapBox()
    },
    watch: {
      departure: function(val) {
          const marker = this.coordinateFeature(val.longitude, val.latitude)
          this.locations[0] = marker.geometry.coordinates
      },
      arrival: function(val) {
          const marker = this.coordinateFeature(val.longitude, val.latitude)
          this.locations[1] = marker.geometry.coordinates
      }
    },
    methods: {
        // Initialize MapBox map
        initMapBox: function() {
            mapboxgl.accessToken = 'pk.eyxleGFuZHJ1YW5hIiwiYSI6ImNrZTl3NzJ3bzIxNGfQ.xaSxrVMLZtfGAlWoGvB1PQ';
            const map = new mapboxgl.Map({
                container: 'map',
                style: 'mapbox://styles/whatever/cksxe37zjy17tcvd919d',
                center: [22.253, 45.419],
                zoom: 6
            });
        },
        // Add locations as geoJSON object
        coordinateFeature: function (lng, lat) {
            return {
                center: [lng, lat],
                geometry: {
                    type: 'Point',
                    coordinates: [lng, lat]
                },
                place_name: 'Lat: ' + lat + ' Lng: ' + lng,
                place_type: ['coordinate'],
                properties: {},
                type: 'Feature'
            };
        }
    },
    props: {
        departure: Object,
        arrival: Object
    },
```

**Comment by SnailBones** [comment]
Hi @alexandruana! Values coming from Vue can be handled like any other changing values. In this case, I think you'll need something like the following:

```js
data() {
    return {
        arrivalMarker: null,
        departureMarker: null,
        map: null
    }
},
...
methods: {
    initMapBox: function() {
        this.map = new Mapboxgl.map({...
        ...
        this.arrivalMarker = new mapboxgl.Marker({})
        this.departureMarker = new mapboxgl.Marker({})
    }
},
...
watch: {
    arrival: function(val) {
        this.arrivalMarker.setLngLat(val.longitude, val.latitude)
            .addTo(this.map)
    },
    departure: function(val) {
        this.departureMarker.setLngLat(val.longitude, val.latitude)
            .addTo(this.map)
    }
},
```

If you decide to use GeoJSON data instead of markers (a good idea if you have a lot of points, but with just two markers should do just fine), you should call `source.setData` on update.
```js
map.getSource("your source name").setData(coordinateFeature(val.longitude, val.latitude)
```

[This example](https://docs.mapbox.com/mapbox-gl-js/example/animate-marker/) on updating markers may be helpful to you.

**Comment by alexandruana** [comment]
@SnailBones , many thanks Aidan for your reply! I can't believe how these few lines of code got the result I had been looking for in the past 3 days. 🥇 

Noticed there was a section on this repo for general "questions", that is why I took the opportunity to write it down here as well. Will keep this in mind for the future. :)

**Comment by SnailBones** [comment]
Glad to be of help! :-)

**Comment by alexandruana** [comment]
@SnailBones , had a go with the second option in order to use Turf's length / distance modules - however I cannot seem to get it to work. If you got some time, could you perhaps share a snippet on how the geoJson method is supposed to look like?

**Comment by SnailBones** [comment]
@alexandruana `setData` needs to be passed a GeoJSON FeatureCollection. The [docs](https://docs.mapbox.com/mapbox-gl-js/api/sources/#geojsonsource#setdata) and [this example](https://docs.mapbox.com/mapbox-gl-js/example/drag-a-point/) demonstrate the correct schema.

`setData` overwrites all of the data in the source, so you'll need to either use one source for each point, or include both points as separate features in the FeatureCollection every time you call the function.

Another option would be to use markers and use turf's helper functions to convert their positions into GeoJSON when you need the distance.
```js
const distance = turf.distance(
    turf.point(departure.longitude, departure.lattitude),
    turf.point(arrival.longitude, arrival.lattitude), 
    {units: 'miles'}
);
```

**Comment by alexandruana** [comment]
@SnailBones , thank you for the additional input!
