### ISSUE TITLE
Do not hide markers at specified zoom level?

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1098]
I have a map where I set maxZoom at 9. At the moment for testing purposes I would like to show all markers at that zoom level, even if they overlap.

How can  I do that? 

Thanks.

**Comment by mourner** [comment]
See `icon-allow-overlap` in the style spec https://www.mapbox.com/mapbox-gl-style-spec/#symbol

**Comment by misterfresh** [comment]
Thanks.

With the following code markers still can't seem to overlap : 

```
    var style = require('./../../conf/outdoors-v7.json');
    style.layers.push({
        "id": "markers",
        "type": "symbol",
        "source": "markers",
        "layout": {
            "icon-image": "{marker-symbol}-12",
            "icon-allow-overlap": true,
            "icon-ignore-placement": true,
            "text-field": "{title}",
            "text-font": "Open Sans Semibold, Arial Unicode MS Bold",
            "text-offset": [0, 0.6],
            "text-anchor": "top"
        },
        "paint": {
            "text-size": 12
        }
    });

**Comment by SimonaJ** [comment]
This is an old thread but in case anyone else runs in this issue - 

you also have to add 'text-allow-overlap': true, probably because your layer has text-field property and if it is not set, mapbox somehow ignores icon-allow-overlap: true and hides icons anyways.

**Comment by haffla** [comment]
@SimonaJ in my case I don't even have text. Just an icon. But still most of my icons are not visible (up to a certain zoom level) even though they are 'miles away' from other icons. 
This is what I have now. Would appreciate any hints.

```
map.addLayer({
      id: constants.MAP_LAYER_ID,
      type: 'symbol',
      source: constants.MAP_SOURCE_DATA_ID,
      layout: {
          'icon-image': '{icon}-15',
          'icon-allow-overlap': true,
          'icon-ignore-placement': true,
          'icon-padding': 0,
          'text-allow-overlap': true // doesnt make sense I know, but I tried this
      }
  });
```

**Comment by sidonaldson** [comment]
I'm also finding this. Do the docs hide a clue?
![image](https://cloud.githubusercontent.com/assets/236669/25660314/990fda92-3003-11e7-89b9-0c2102051adb.png)
What exactly does data-driven styling mean? As this isn't supported yet.

**Comment by woshitom** [comment]
@haffla when you create your source, do not add this option:

> cluster: true

or set it to false

**Comment by liushengxian** [comment]
run into this problem, too.

My code as following:

` layout: {
                "icon-image": "my-icon",
                "icon-allow-overlap": true,
                "icon-padding": 1,
                "icon-size": 0.8,
                "text-allow-overlap": true,
                "icon-ignore-placement": true ,
            }`

In fact, there's no text at all. But still most of my icons are not visible (up to a certain zoom level) even though they are 'miles away' from other icons.

**Comment by leogoesger** [comment]
Anyone finding a solution for this? I am facing the same issue.
`fromJS({
    id: source,
    source: source,
    type: 'symbol',
    interactive: true,
    layout: {
      'icon-image': {
        property: 'geoClassId',
        stops: [
          [1, `${source}-1`],
          [2, `${source}-2`],
          [3, `${source}-3`],
          [4, `${source}-4`],
          [5, `${source}-5`],
          [6, `${source}-6`],
        ],
      },
      'icon-allow-overlap': true,
      'symbol-avoid-edges': true,
      'text-field': {
        property: 'geoClassId',
        stops: [
          [1, `${source}-1`],
          [2, `${source}-2`],
          [3, `${source}-3`],
          [4, `${source}-4`],
          [5, `${source}-5`],
          [6, `${source}-6`],
        ],
      },
      'text-font': ['Open Sans Bold', 'Arial Unicode MS Bold'],
      'text-size': 8,
      'text-transform': 'uppercase',
      'text-letter-spacing': 0.05,
      'text-offset': [0, 1.3],
    },
    paint: {
      'text-color': '#ffffff',
    },
  })`

**Comment by leogoesger** [comment]
I solved my issue by adding `'text-allow-overlap': true,` and `'icon-allow-overlap': true,`.

**Comment by jsina** [comment]
@leogoesger How could I add have a box with background like a box to show textField on it?

**Comment by zhuxiaomengjj** [comment]
It's probably caused by the source, not the style. In the source tile there are distributed to several zoom levels, so, you can't see them all in one zoom level

**Comment by hb0** [comment]
In my case switching from `'symbol-placement': 'line'` to `'symbol-placement': 'line-center'` helped.

**Comment by vijaykharage7** [comment]
how can we use this in iOS SDK?
