### ISSUE TITLE
Static API: Support language and worldview url parameters

### ISSUE THREAD

**Issue by johnnyshields** [mapbox/mapbox-gl-js#11005]
My sincere apologies, Im aware this is not the right repo to raise this request but Im unsure where I should raise it.

Currently, the Mapbox Static Image URL API does not allow “language” and “worldview” parameters which override the map style’s built-in values. Since my app is translated in 20+ languages this requires me to create 20+ map styles (one for each language.) Google Maps and other similar APIs support these parameters.

I would appreciate if someone from Mapbox can let me know where I should raise this feature request.

**Comment by asheemmamoowala** [comment]
@johnnyshields  as you noted, this repo is for bugs and feature requests specific to the gl-js project. I'd encourage you to [contact support](https://www.mapbox.com/contact/) with this request - they are best placed to respond and take this feedback to the correct product teams
