### ISSUE TITLE
Glyph range truncated a bit short

### ISSUE THREAD

**Issue by friedbunny** [mapbox/mapbox-gl-js#1101]
Same issue as mapbox/mapbox-gl-native/issues/931.

The glyph range is being truncated at [`65280`](https://github.com/mapbox/mapbox-gl-js/blob/241a07d0607447cbc393f2ccfab3f03e765ced13/js/symbol/glyph_source.js#L83) and [`65533`](https://github.com/mapbox/mapbox-gl-js/blob/241a07d0607447cbc393f2ccfab3f03e765ced13/js/symbol/resolve_text.js#L32), while the actual unicode block extends to `65535`. This has been fixed in fontstack (mapbox/node-fontnik/issues/71) and will be a simple fix here in JS.

This bug results in characters in that range not being displayed, [as you can see here](https://friedbunny.github.io/mapbox-gl-style-dark/example.html#16.35/36.45125/-222.74102). The text should read `国道４１号`, but `４１` is missing (while `41` is fine).

![screen shot 2015-03-17 at 11 55 13 pm](https://cloud.githubusercontent.com/assets/1198851/6704079/1b6072a8-cd01-11e4-9f54-82e0b5bef979.png)

**Comment by friedbunny** [comment]
Looks like: [js/symbol/resolve_text.js](https://github.com/mapbox/mapbox-gl-js/blob/241a07d0607447cbc393f2ccfab3f03e765ced13/js/symbol/resolve_text.js#L32) and [resolve_text.test.js](https://github.com/mapbox/mapbox-gl-js/blob/241a07d0607447cbc393f2ccfab3f03e765ced13/test/js/symbol/resolve_text.test.js#L63-L74).

**Comment by friedbunny** [comment]
![screen shot 2015-03-17 at 11 36 05 pm](https://cloud.githubusercontent.com/assets/1198851/6703846/6ef34178-ccfe-11e4-870c-d8b5373d55e4.png)

Right is the fixed `４１`.

I'll look at the tests tomorrow and put this in a pull request.

**Comment by mikemorris** [comment]
:+1: thanks for catching this!
