### ISSUE TITLE
@types/mapbox-gl line-cap missing Expression

### ISSUE THREAD

**Issue by enersis-pst** [mapbox/mapbox-gl-js#11026]
For me this config throws a error because `line-cap` of type interface could only be a type of `'line-cap'?: "butt" | "round" | "square"`
```
"line-cap": [
                "step",
                [
                    "zoom"
                ],
                "butt",
                11,
                "round"
            ],
```

using
"@types/mapbox-gl": "2.4.1",

**Comment by rreusser** [comment]
Hi @enersis-pst! Looks like you're right and that data-driven line-cap styling [goes back to 2.3.0](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-line-line-cap). The GL JS team doesn't maintain or update the DefinitelyTyped repo, so I think the right course of action is to open up a PR over there to get this change in. (That said, we are glad to advise!)

It looks like this line just needs the addition of `| Expression`:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e827f569f4ace3fbbf17fb1295fb7ab35a262f1b/types/mapbox-gl/index.d.ts#L2342

If it's alright, I'll close this issue, but let me know if anything about the above is unclear. Thanks!

**Comment by enersis-pst** [comment]
@rreusser thanks for the info.
i create a pr 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55840#issuecomment-921559954
