### ISSUE TITLE
Markers show in the top-left corner until map is loaded

### ISSUE THREAD

**Issue by adamkovalsky** [mapbox/mapbox-gl-js#11020]
**mapbox-gl-js version**: 2.3.0+

**browser**: Chrome 93.0.4577.63

### Steps to Trigger Behavior

Load/refresh a map with markers attached to it.

### Link to Demonstration

https://docs.mapbox.com/help/demos/custom-markers-gl-js/final.html

### Expected Behavior

The markers are positioned correctly.

### Actual Behavior

The markers are positioned in the top/left corner until the map is loaded. This appears to be a regression in v2.3.0 and onward, and works as expected in v2.2.0. Potentially a regression introduced by #10530.

**Comment by rreusser** [comment]
Confirmed directly with git-bisect. #10530 indeed introduced this regression.

**Comment by rreusser** [comment]
Good catch, and spot on determining the cause. ❤️ 👏 🙇  I've submitted https://github.com/mapbox/mapbox-gl-js/pull/11025 to fix this.

**Comment by adamkovalsky** [comment]
Brilliant, thanks for the quick fix!

**Comment by rreusser** [comment]
No problem! (Though unfortunately we *just* released the 2.5.0 beta yesterday, so it's currently the longest possible time before the next minor release 2.6.0 which will include this, but still glad to get the fix in. Thanks for reporting this!)
