### ISSUE TITLE
Mapbox-GL.js:31 Image "default-5" could not be loaded Ask

### ISSUE THREAD

**Issue by Looxor** [mapbox/mapbox-gl-js#11039]
When I try to display the map i ve this message in code inspector (Safari)

![unknown](https://user-images.githubusercontent.com/1319853/133987351-b31dffbd-fcd7-4e17-a15f-2edee7eb0b44.png)

I m working with : 

- Mapbox-GL 2.3
- Safari WebBrowser

Does anyone have the solution for settle this issue . It make me tired

**Comment by mourner** [comment]
Can you provide a reproducible live example? Does it happen on any of the online examples like [this](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/)?

**Comment by Looxor** [comment]
Hi Vladimir (@mourner) 
Thank u to try to help me
It's happening in this case 👇
 https://user-images.githubusercontent.com/1319853/134032859-2e028c1c-f550-4c50-8b68-062889f4a802.mp4

**Comment by Looxor** [comment]
Hi @mourner 

I tested also with sample you provided before and with our map style it doesn't work 
![unknown](https://user-images.githubusercontent.com/1319853/134307862-e6199357-6041-46e9-b78a-28dc975387bd.png)

**mapboxgl.accessToken** = pk.eyJ1IjoibG9uZ3g2OTUiLCJhIjoiY2pscTFpOWlsMDBudzNzcXRtbXFnMTlsOSJ9.1EPpR4TwAyA0YTlg-894GA

**mapStyle**
mapbox://styles/longx695/cjlqekbzp1w2c2rqr4elp6rdb

**Comment by Looxor** [comment]
It's ok @mourner 
Thank U 🤝
