### ISSUE TITLE
Rotate fires moveend events when it shouldn't

### ISSUE THREAD

**Issue by derrickpelletier** [mapbox/mapbox-gl-js#1104]
Clicking on the compass in the navigation control and dragging to rotate the map seems to fire a `moveend` event for every pixel the cursor is moved while the mouse button has not been released.

Seems to me it shouldn't fire this event until the mouseup

**Comment by mourner** [comment]
Agreed.

**Comment by tmcw** [comment]
Internally, the rotation control calls .setBearing, which calls .setView, which fires the [moveend event](https://github.com/mapbox/mapbox-gl-js/blob/a487137a13df1b279093ef3818cc7d53dd8b3cf0/js/ui/map.js#L146). We can either make a 'quiet setView' method or option for cases like these, or avoid using setView/setBearing.

My gut instinct is that a quiet option is the cleanest here.
