### ISSUE TITLE
🗺Map 3D Rendering not displayed on 📲Safari Mobile 

### ISSUE THREAD

**Issue by Looxor** [mapbox/mapbox-gl-js#11046]
Hello every body !

I try to render a 3D Map on a PWA Mobile App on Safari but the 3D not rendered (No relief)

**🗺Mapbox-gl-js version 2.3**
**🧭Safari Mobile**

Is anyone have an idea for settle this issue ?

**Comment by avpeery** [comment]
Hi @Looxor, check out the [example for adding 3D terrain in a map](https://docs.mapbox.com/mapbox-gl-js/example/add-terrain/) or the [example for displaying buildings in 3D](https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/). Can you provide more information on any errors you are receiving when attempting to render the 3D map?

**Comment by Looxor** [comment]
Thank u @avpeery

**Comment by avpeery** [comment]
@Looxor Glad I could provide you with some resources on implementing 3D. Generally, this issue tracker is focused on bug reports and feature requests. If you need further assistance, I suggest contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks!
