### ISSUE TITLE
Change the color of selected 3D buildings

### ISSUE THREAD

**Issue by janeczeq25** [mapbox/mapbox-gl-js#11056]
Hi,
in my database I have ID numbers (mapbox) of about a million buildings, each building is associated with a category.
Buildings are scattered all over the world.
There can be many more buildings, so the data should be downloaded dynamically (json, geojson, etc.).

I would like to change the color of 3D buildings (fill-extrusion-color) depending on the category and add an icon next to it.

I have been browsing the documentation but I am not able to combine it into a solution.

I am asking for help as I should solve this problem.

Currently, it only controls color like this:

`
'fill-extrusion-color': [
"case",
[
"! =",
["get", "min_height"],
0
],
"hsl (224, 18%, 56%)",
[
"match",
["get", "type"],
["building: part"],
true,
false
],
"hsl (224, 25%, 38%)",
[
"interpolate",
["linear"],
["get", "height"],
0,
"hsl (224.47%, 29%)",
twenty,
"hsl (224.61%, 33%)",
50,
"hsl (224.53%, 48%)",
400,
"hsl (224, 83%, 72%)"
]
]
`

**Comment by avpeery** [comment]
Hi @janeczeq25 Check out our docs on [data-driven styling](https://docs.mapbox.com/help/glossary/data-driven-styling/) if you haven't already, and the [getting started with data-driven styling](https://docs.mapbox.com/help/getting-started/map-design/#data-driven-styles). This issue tracker is focused on bug reports and feature requests, so although we’re glad to point you in the right direction we can’t offer general support in this channel. For “how to” questions like this, I suggest contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks!
