### ISSUE TITLE
new Map options localIdeographFontFamily in ios15 make iphone freezed

### ISSUE THREAD

**Issue by wilsunson** [mapbox/mapbox-gl-js#11057]
**mapbox-gl-js version**: 2.4.1

**browser**: Safari

### Steps to Trigger Behavior

 1.defind an option in new mapboxgl.Map
 2.option includes localIdeographFontFamily
 3.localIdeographFontFamily first value is 'Open Sans Regular'
 4.when map addLayer, the layout use text-font 'Open Sans Regular', the browser fell like crack up

**Comment by avpeery** [comment]
Closing as this is a repeat of similar open issue: https://github.com/mapbox/mapbox-gl-js/issues/11045

**Comment by mourner** [comment]
@wilsunson can you please try out the `main` branch build and see if it's different? I wonder if https://github.com/mapbox/mapbox-gl-js/pull/11047 could have fixed it.
