### ISSUE TITLE
E/Mbgl: [Setup]: loading style failed: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by LqTk** [mapbox/mapbox-gl-js#11058]
mapboxMap.setStyle(Style.Builder().fromUri("https://..."))使用自定义style可不可以设置忽略证书问题？

**Comment by avpeery** [comment]
@LqTk This issue tracker is for reporting bugs and requesting features in GL JS. We cannot offer general support in this channel. For "how to" setup questions like this, I suggest contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks.
