### ISSUE TITLE
Suggest supporting a "union" operation to solve per-layer opacity property request

### ISSUE THREAD

**Issue by Anonymapper** [mapbox/mapbox-gl-js#11054]
#4090 is a long standing issue (41 comments) dating from 2017, requesting a per-layer opacity property. Mapbox devs have explained how this would require composited rendering which would be difficult:

![](https://cloud.githubusercontent.com/assets/126952/16423800/8658eae0-3d2b-11e6-8eef-0a8eb36f1355.png)

Several users report that their use case was solved by pre-processing with a "union" operation (https://github.com/mapbox/mapbox-gl-js/issues/4090#issuecomment-402662425, https://github.com/mapbox/mapbox-gl-js/issues/4090#issuecomment-513464641, https://github.com/subsetOfInsanity/subsetOfInsanity.github.io/commit/b63dcaa14f8db81f2d92555bab0249212cd78a7b). But the roundtrip via turf.js has performance issues. It would be more efficient to implement "union" natively within GL JS.

**I therefore ask that you consider adding support for "union".** If Mapbox could support "union", this would remove a pain point for a lot of people.

**Comment by mourner** [comment]
Have to close this because it's out of scope for the GL JS project 😉
