### ISSUE TITLE
Mapbox GeolocateControl marine navigation, position jumps to shore when shore is nearby

### ISSUE THREAD

**Issue by Cmoen11** [mapbox/mapbox-gl-js#11050]
I'm developing an app with Mapbox where the users' position is required. I'm using GeolocateControl to display the users' position within the Mapbox map.

It seems fine until you're near land, and it seems like it would try to stick you to any nearby road instead of the actual position.

I understand that this might be to be more accurate for common tasks, but in this task, it's making it worse.

Is it any possibility to turn this off?

**Comment by ryanhamley** [comment]
Hi @Cmoen11 the GeolocateControl uses the browser's [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) so the rendered position is what is returned from the browser. You can try setting `enableHighAccuracy` as shown below to get a more accurate position. I don't believe that GL JS is doing anything that should change where the geolocated point is shown; however, if you can provide a minimal reproduction in a site like JSBin or CodePen, that would be helpful in making sure.

    var geolocate = new mapboxgl.GeolocateControl({
        positionOptions: {
            enableHighAccuracy: true
        }
    });

**Comment by Cmoen11** [comment]
yeah. I'm sorry for creating this issue. I think it is more up to the device GPS, and not mapbox.. 

Would like an option to prevent huge drops of GPS jumps, or a GPS callback function that allows doing modification to the new GPS position, before updating the marker position.. So if I want to skip the GPS read for some reason, I can.. 

But anyway.. this is not an mapbox issue, so I'll close the issue :)
