### ISSUE TITLE
sprite icon error

### ISSUE THREAD

**Issue by cdhuangyong** [mapbox/mapbox-gl-js#11051]
When used on a display device with a DPR of 1, the icon is misaligned. Mac no problem

**mapbox-gl-js version**:  

**browser**: chrome

![image](https://user-images.githubusercontent.com/47745622/134514815-0babc622-fdfb-4776-ba62-fc828b2cfa52.png)

![image](https://user-images.githubusercontent.com/47745622/134514687-de1efdea-6f37-489b-84d5-b2f613ce832a.png)

**Comment by cdhuangyong** [comment]
This problem seems to have been solved.
The reason for the error I found is because when devicePixelRatio is 1, the loaded resource is (https://api.mapbox.com/styles/v1/mapbox/streets-v11/sprite.json), which does not match the sprite image. When devicePixelRatio is 2, there is no problem (the URL contains "@2x")

**Comment by cdhuangyong** [comment]
Did you adjust sprite resources yesterday?

**Comment by avpeery** [comment]
Yes, it seems there was a release in the sprite resource recently, and is likely related. Sometimes there is a cache that causes the mismatch between .json and .png so a refresh would help with the error.
