### ISSUE TITLE
Sprite+label issues

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1105]
New labeling code introduced two visual bugs:

- Labels with sprites now align to the line, instead of point
- Labels scrambled-- looks like two labels sitting overlapping?

Comparing v7 and the latest code at http://mapbox.s3.amazonaws.com/mapbox-gl-js/master/mapbox-gl.js, with identical styling and zoom level:

v7
![screen shot 2015-03-18 at 11 02 07 am](https://cloud.githubusercontent.com/assets/4551508/6715896/ef1987da-cd5e-11e4-9fce-2ac44b79c3d6.png)

latest labeling code
![screen shot 2015-03-18 at 11 01 40 am](https://cloud.githubusercontent.com/assets/4551508/6715900/faf5f822-cd5e-11e4-9c07-37aba7cc0172.png)

**Comment by ansis** [comment]
I think `http://mapbox.s3.amazonaws.com/mapbox-gl-js/master/mapbox-gl.js` might not be up to date. With a local version of master I'm seeing 
![screen shot 2015-03-18 at 11 57 58 am](https://cloud.githubusercontent.com/assets/1421652/6716944/109fba30-cd66-11e4-8476-e0be239e462a.png)

**Comment by ansis** [comment]
It was still failing in some cases. c35ca56 should fix it everywhere. Rendering tests were already correct.
