### ISSUE TITLE
why the water mesh draw twice ?

### ISSUE THREAD

**Issue by adlovley** [mapbox/mapbox-gl-js#11068]
1.   In the zoomlevel 1,   I use spector.js to capture the frame draw call,  and the result  I found that the ocean area mesh draw call twice, the differece is only ocean's color , why ?  I could't understand that

**Comment by rreusser** [comment]
@adlovley is it possible there's a ~2px offset and what you're seeing is the manner in which the `water-shadow` and `water` layers are rendered to accomplish this effect? See the dark blue outline in the image below.

<img width="283" alt="Screen Shot 2021-09-30 at 8 29 50 AM" src="https://user-images.githubusercontent.com/572717/135485801-5e77e35c-d596-44e7-8d3e-7faa2767b9dd.png">

**Comment by mourner** [comment]
Yep, that's something to look for in the style, not a GL JS issue.
