### ISSUE TITLE
How can ı get data properties from tileset?

### ISSUE THREAD

**Issue by BerkayAkgurgen** [mapbox/mapbox-gl-js#11063]
I add my data to the map via Mapbox studio, but I cannot see the data found on the frontend such as id, the creation date of my data. How can I access this data?

**Comment by ryanhamley** [comment]
I'm not sure specifically what you're asking for, but to access feature data in a map you need to add the source and layer and style them appropriately. If you need general help with GL JS, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).
