### ISSUE TITLE
How could I count the number of points in a layer when filtering them?

### ISSUE THREAD

**Issue by aguito1877** [mapbox/mapbox-gl-js#11077]
**mapbox-gl-js version**: 2.5

### How could I count the number of points in a layer when filtering them?

I would like to obtain the number of points that I obtain when filtering a geojson file

### Links to related documentation
I have searched the documentation but I did not find something in particular that gives me a clue on how to solve this.

**Comment by mourner** [comment]
Can you please describe what you're trying to do in more detail, preferably with code examples? It's very hard to understand your request from just these few sentences alone.
