### ISSUE TITLE
ImageSprite leaks image

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1109]
The imagesprite code creates a temporary image to get its data, stores the data in img, but keeps a reference to that image. https://github.com/mapbox/mapbox-gl-js/blob/fontstack-array/js/style/image_sprite.js#L42

This seems like a leak: the [image isn't removed when the style is](https://github.com/mapbox/mapbox-gl-js/blob/fontstack-array/js/style/style.js#L366-368), it isn't used anywhere, and it's one of the top global handles

![2015-03-18 at 7 25 pm](https://cloud.githubusercontent.com/assets/32314/6721545/9e14f068-cda4-11e4-8e53-e0c8c651a8d0.png)

**Comment by jfirebaugh** [comment]
I'd expect the image to be garbage collected as soon as it's containing `ImageSprite` is. Are you seeing it retained for longer than that?

The data and width are used by `SpriteAtlas`. We could possibly extract those and release the image itself but I'm not sure that would accomplish much in terms of saving memory.
