### ISSUE TITLE
addLayer ({ type: 'symbol',......})  How to make points not converge？？

### ISSUE THREAD

**Issue by qikong333** [mapbox/mapbox-gl-js#11106]
addLayer ({ type: 'symbol',......})   
In this case, I want the points to not aggregate

**mapbox-gl-js version**:
"mapbox-gl": "^2.4.1"

**Comment by arindam1993** [comment]
Hey @qikong333  we don't plan on implementing this right now. PR's are always welcome!

**Comment by qikong333** [comment]
找到方法了，配置'icon-allow-overlap': true,可以实现，谢谢
