### ISSUE TITLE
handle non-Basic-Multilingual-Plane characters

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1110]
from https://github.com/mapbox/mapbox-gl-js/pull/1108#issuecomment-83258559

https://github.com/mapbox/mapbox-gl-js/blob/4935a4bbf81b78897b9e29013ac9e461f59038d9/js/symbol/resolve_text.js#L31

> Note that String.charCodeAt() will always return a value that is less than 65536. This is because the higher code points are represented by a pair of (lower valued) "surrogate" pseudo-characters which are used to comprise the real character. Because of this, in order to examine or reproduce the full character for individual characters of value 65536 and above, for such characters, it is necessary to retrieve not only charCodeAt(i), but also charCodeAt(i+1) (as if examining/reproducing a string with two letters). See example 2 and 3 below.

This isn't critical. Probably not common enough to be worth the effort.

It sounds like if we currently encounter one of these characters it will be displayed as random characters and the last character will be missing. It could be fixed by using the [algorithm here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt) or by never converting to a string when reading the pbf. I'm not sure if our pbf parser even reads these correctly right now so that should be checked first.

@mikemorris

**Comment by mikemorris** [comment]
We're currently not baking any glyph pbfs in this range, node-fontnik is hardcoded to stop at 65535. That algorithm could be reasonable if we implement this at some point.

**Comment by lucaswoj** [comment]
Given that `node-fontnik` doesn't produce glyph pbfs in this rage, we can close this issue for the time being.
