### ISSUE TITLE
JS Fiddle examples don't appear to work

### ISSUE THREAD

**Issue by fc** [mapbox/mapbox-gl-js#11115]
1. Click here: https://docs.mapbox.com/mapbox-gl-js/example/custom-style-layer/
2. Then click 'Edit JS Fiddle'

If I use 'Edit JS Fiddle' it simply displays nothing...
![image](https://user-images.githubusercontent.com/20962/137040826-c0e1a455-ba95-4a06-bfcf-1dc961bef528.png)

**Comment by HeyStenson** [comment]
Hi @fc, I'd suggest trying this in your browser's private/incognito mode and seeing if it works then. If so, this may be related to a browser extension you have installed that's interfering with the JSFiddle functionality - that was happening to me!
