### ISSUE TITLE
Handling sprites in perspective

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1112]
Elements near the viewer are scaled up, compared to than those far away. This works well for most things, but not rasterized sprites (enlarge to see blurriness):

![screen shot 2015-03-19 at 2 24 54 pm](https://cloud.githubusercontent.com/assets/4551508/6741356/0f5ca05a-ce44-11e4-827c-11fc68f7a3ce.png)

Three ways around this:

- Only scale sprites down for far things, but keep original size for close things.
- When baking the spritesheet, make them far bigger than necessary, so that they remain crisp with enlargement. Will need to know the largest scale factor to do this.
- Switch to vector sprites.

cc/ @ansis

**Comment by lucaswoj** [comment]
We have made scaling behaviour configurable with `*-pitch-alignment` and `*-rotation-alighment` per https://github.com/mapbox/mapbox-gl-style-spec/issues/459

Switching to vector sprites is a big separate issue that we aren't ready to tackle right now.
