### ISSUE TITLE
Add isHighAccurate property to Marker

### ISSUE THREAD

**Issue by malekeym** [mapbox/mapbox-gl-js#11135]
## Motivation
For animating a point the example that Mapbox provided is [animate point along a route](https://docs.mapbox.com/mapbox-gl-js/example/animate-point-along-route/). This convention has bad performance and triggers a repaint map on every update source.  
![image](https://user-images.githubusercontent.com/70053533/137860952-3d810909-5d4e-4f47-b525-4b4434bb1c20.png)
as you can see The CPU is involved throughout the airplane movement.

If we use Marker instead of symbol layer the result is very different, because it works with CSS and doesn't trigger a repaint. 
![image](https://user-images.githubusercontent.com/70053533/137862125-c3b25c34-486c-42fc-b7a0-b1f18254b619.png)
As you can see this convention uses less CPU and memory, but if you check this you can see [Codesandbox link](https://codesandbox.io/s/beautiful-dew-ummh0?file=/index.html) that movement is not smooth and sometimes the marker shakes. This behavior happens because round `marker._pos` property of Marker(maybe for performance) but if we want to implement animation movement, we should have highAccuracy.

### Implementation
We can add `isHighAccuracy` property and check if we want high accurate marker don't round `marker._pos`.

**Comment by SnailBones** [comment]
@malekeym I just noticed that we do have an example of [animating a HTML Marker](https://docs.mapbox.com/mapbox-gl-js/example/animate-marker/). The jittering behavior is clear in it, especially at lower zoom levels.
