### ISSUE TITLE
Preserve text-translate when map is in perspective

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1113]
Check out how the labels' ascenders start running into the symbol when map gets tilted back:

![textranslate](https://cloud.githubusercontent.com/assets/4551508/6741772/9bdf5182-ce47-11e4-8806-9d38af8c0002.gif)

cc @ansis

**Comment by ansis** [comment]
I think you want to use `text-offset` instead of `text-translate` here
