### ISSUE TITLE
Does setPaintProperty with fill-color and stops interpolate colors on it's own ? 

### ISSUE THREAD

**Issue by mfaizan1** [mapbox/mapbox-gl-js#11140]
Hello, i am trying to build data driven choropleth map of a US state, 
Issue i am facing is i have just three colors in my stops but i can see map is being made with more than 3 colors, my best guess is that library is interpolating colors on it's own, if that is the case how can i stop it from doing so ? 

details
i start with default stops
```
[
    [-1, "#FFF"],
    [-1, "#AFA"],
    [-1, "#FAF"],
  ]
  ```
  these are just placeholder values, 
  after data arrives i build stops again with actual values 
  
  ```
  [
    [
        19,
        "#afc5ff"
    ],
    [
        22,
        "#376eff"
    ],
    [
        28,
        "#1c3780"
    ]
]
```

once stops are calculated i add source to map, add layer and paint the layer
   ```
    map.current.addSource("counties", {
      type: "geojson",
      data,
    });
    map.current.addLayer({
      id: "county",
      type: "fill",
      source: "counties",
    });
    map.current.setPaintProperty("county", "fill-color", {
      property: options.property,
      stops,
    });
```
after doing all map that is rendered contains colors that are not in my stops (marked by red numbers in image below). 

![screenshot](https://user-images.githubusercontent.com/17065546/138003137-acf7f9f7-6a48-4786-a90c-07f90a16795b.png)

either i am doing something wrong or i am not aware of some feature provided by library

**Comment by ryanhamley** [comment]
Hi @mfaizan1 you're right that `stops` will interpolate between the values. The [`step` expression](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#step) should work better for you. This [example](https://docs.mapbox.com/mapbox-gl-js/example/cluster/) in particular shows how to set a circle's color to one of three options. Your code should end up looking something like this:

```
 map.current.setPaintProperty("county", "fill-color", [
    'step',
    ['get', 'someCountableProperty'],
    '#afc5ff', // any item where `someCountableProperty` is <= 19 will be displayed with this color
    19,
    '#376eff', // any item where `someCountableProperty` is <= 22 && > 19 will be displayed with this color
    22,
    '#1c3780' // any item where `someCountableProperty` is > 22 will be displayed with this color
]);
```
