### ISSUE TITLE
Docs search is not useful for finding paint/layout property names

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#11141]
This is a video of me attempting to use the Search function in the docs. At the time, I was trying to remember the name of the property that lets you control which order features are rendered in. I knew it existed, and roughly how it worked.

https://user-images.githubusercontent.com/678344/138003283-8048f49d-dca1-4b99-bf6f-b9463f4f7a14.mov

Eventually I remembered that the name contained "sort-key" and that was enough to let me text-search to find it.

I hope this helps understand just how painful and not useful the current search experience.

Major issues:

1. Defaulting to searching all docs, and not retaining that preference at all, is a terrible experience. I don't know if there are any developers who work in both Mapbox GL JS and Swift and Android and Unity...but they must be a very rare breed. If I'm searching from Mapbox GL JS docs, it's extremely unlikely any of those other platforms are going to be anything other than confusing distractions.
2. Giving the Layers page of the style spec as a result is nowhere near granular enough. That's narrowing down the entire search space to maybe 20-30% for me. (In this particular case, it didn't narrow it down at all, because I already knew it would be a layer property).

I normally try to say something positive, but I really can't think of anything good to say about the search feature for my use case. It is never useful for anything, despite how much time I spend in docs. All it does is occasionally tempt me to use it and waste my time, before I revert to manually navigating to the right place in the docs and use browser text-search.

At least in the Mapbox GL JS API docs, there is the useful search box on the right hand side. I don't know if this would be true for everyone, but docs search would be much much more useful with these changes:

- get rid of the global multi-platform search (or bury it somewhere)
- put the API docs search on the left side (where multi-platform search is)
- create an equivalent Style Spec docs search (where multi-platform search is)

**Comment by katydecorah** [comment]
# Update

> create an equivalent Style Spec docs search


<img width="1521" alt="2021-11-16 at 10 40 AM" src="https://user-images.githubusercontent.com/2180540/142016868-62ec8fde-2431-41e4-b90a-e2c7f60e2aaa.png">


@stevage This is live! https://docs.mapbox.com/mapbox-gl-js/style-spec/ 

We are still working with marketing on improving the site-wide search experience, so this is an intermediate step until we can make progress on moving the (currently less optimal) site-wide search out of the page layout.

**Comment by stevage** [comment]
![image](https://user-images.githubusercontent.com/678344/142085289-0e810571-9ae1-42bd-bf35-1e59759743f7.png)

That's a huge improvement!

**Comment by asheemmamoowala** [comment]
Closing since the style spec search is now available on the docs site.
