### ISSUE TITLE
enable line breaks after hyphens

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1115]
For line break purposes, treat hyphens as spaces:

![screen shot 2015-03-20 at 10 14 16 am](https://cloud.githubusercontent.com/assets/4551508/6756875/14a30bf2-ceea-11e4-9870-18d54918ff6c.png)

Would be
```
Stow-on-
the-wold
```

**Comment by mofoyoda** [comment]
Is there a way to pass the line break symbol to ```text-field``` property? 
If that is possible, I could break long strings in a database query etc.
