### ISSUE TITLE
Render tests do not write `actual.png` or `diff.png` locally

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#11160]
Regression introduced by https://github.com/mapbox/mapbox-gl-js/pull/11111 (reverting this PR fixes the issue locally). Noticed on the `globe-view` dev branch. That specific line looks suspicious: https://github.com/mapbox/mapbox-gl-js/pull/11111/files#diff-88099fc4985b97d27e9097eea08260e933af572dd877814a654c5aeec65037caR152.

`actual` and `diff` are not updated after sequential run of `yarn run test-render`, even though some tests may fail.

<img width="452" alt="Screen Shot 2021-10-21 at 11 05 24 AM" src="https://user-images.githubusercontent.com/7061573/138332705-608ec96a-a3c4-4553-bf8e-35cbdb2a96d3.png">

cc @arindam1993

**Comment by arindam1993** [comment]
You can use the `watch-render` command to generate the images.

**Comment by SnailBones** [comment]
Does this apply to `expected.png` when running with `UPDATE=1`? Do tests still pass or fail correctly with`test-render` despite images not being written to file?
