### ISSUE TITLE
Label collision dead zones

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1117]
https://www.mapbox.com/bites/00108/#14.79/42.3398/-71.0749

At this exact zoom, there are almost no street labels-- zoom in or out slightly, and they reappear

cc/ @ansis

**Comment by mourner** [comment]
yeah looks like a bug

![image](https://cloud.githubusercontent.com/assets/25395/6760717/30f33c18-cf54-11e4-9be5-2855b336e11e.png)

**Comment by mourner** [comment]
Zooming in further, I see these stripes going through the screen - might be related:

![image](https://cloud.githubusercontent.com/assets/25395/6760738/57b7a79e-cf54-11e4-9b6c-25042833137e.png)

**Comment by ansis** [comment]
The "us_interstate_label" layer has `"text-padding": 1000`.

**Comment by peterqliu** [comment]
that does tend to do it, doesn't it?
