### ISSUE TITLE
Equirectangle doesn't morph back into mercator

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11187]
It looks like when 

```js
projection: {
  name: 'equirectangular'
}
```
is set, the map doesn't morph back into mercator at high zoom levels. See video demonstrating this: 

https://user-images.githubusercontent.com/61150/139319293-7eaf9f9d-4489-4bba-99de-8cfb2bf0cb57.mp4

**Comment by mourner** [comment]
@ansis could this possibly be fixed by calculating separate `scaleX` and `scaleY` adjustments instead of a single `scale` one in `getProjectionAdjustments`?
