### ISSUE TITLE
Refreshed tiles not reflecting projection

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11188]
If I leave a rendered map idle then return to it, it looks like tiles are being loaded with a different projection than the one set. 

![projection-on-projection](https://user-images.githubusercontent.com/61150/139327704-c499f56e-6366-49a4-9b2f-c0846f22c9f8.gif)

**Comment by willymaps** [comment]
Was able to recreate this by adding a new data viz. component/layer to a map that has a projection other than Mercator in Studio:

![image](https://user-images.githubusercontent.com/12721145/139949025-6918ff08-a437-4c80-bcaa-bfc0c82d214c.png)
 
The map defaults back to Mercator as soon as a source is requested.

![studio_projections](https://user-images.githubusercontent.com/12721145/139950019-9db728a0-196f-4cb0-b7e5-f67438c31079.gif)
