### ISSUE TITLE
new mapboxgl.Source returns TypeError

### ISSUE THREAD

**Issue by mofoyoda** [mapbox/mapbox-gl-js#1119]
When declaring ```mapboxgl.Source``` variable, I get a ```Uncaught TypeError: undefined is not a function```
Reproduced in a fiddle http://jsfiddle.net/mofoyoda/16dLrLp8/3/
Code copied from API doc.

**Comment by jfirebaugh** [comment]
The API docs reflect the last released version (0.7.0). Since then, `mapboxgl.Source` was removed as a public API. It will be removed from the docs in the next release.

**Comment by mofoyoda** [comment]
But if I use ```map.addSource``` instead, how can I access the source later on to change its properties?

**Comment by jfirebaugh** [comment]
You can use `map.getSource()`. However, note that the only public API for the result will be to do `setData()` on a GeoJSON source. If that's what you want, great. If you're trying to do something else, let me know what and I can suggest an alternative.

**Comment by mofoyoda** [comment]
Thanks, @jfirebaugh that's partly what I want. Is there a way to exclude certain feature from data in a VectorTile source? I need an inverted hover effect - when mouse is over an object, hide it instead of highlighting. So I guess I have to dynamically add filter to a layer, or pull the feature out of the data, then put it back.

**Comment by jfirebaugh** [comment]
Cool -- sounds like you want `map.setFilter`. I just documented it: 2406d8775c4625c23f8609e822e35e8cd3b6f355.

**Comment by mofoyoda** [comment]
@jfirebaugh Thanks, looks like it. Can I do the same with paint classes? I.e. add a class with a certain name to a layer definition, so that ```map.AddClass``` affects only specific layers.

**Comment by jfirebaugh** [comment]
Yes, with `map.setPaintProperty()`. 3983649664b16d3002858a7545241494c0c17765

**Comment by bFlood** [comment]
@jfirebaugh will there eventually be an insertData() method as well, so smaller deltas can be added to large data sources without incurring a full setData?

thanks!

**Comment by jfirebaugh** [comment]
@bFlood No, not unless there's a strong need that `setData` or manipulating layer filters doesn't satisfy. Incrementally updating the tiled GeoJSON would be quite complex, and `setData` or layer filters should be fast enough for virtually all needs.

**Comment by bFlood** [comment]
ok, thanks. It does seem like a difficult task but I was hoping this comment from geojson-vt had been implemented already. https://github.com/mapbox/geojson-vt/issues/26

the sources in question have millions of records and I was hoping to keep already processed data available but that list could easily be trimmed to keep setData calls as speedy as possible

thanks again

**Comment by mgiraldo** [comment]
what if I want to add a raster source?
