### ISSUE TITLE
customAttribution does not respect order of array elements

### ISSUE THREAD

**Issue by mattskone** [mapbox/mapbox-gl-js#11191]
**mapbox-gl-js version**: 1.12.0

**browser**: Firefox 93

### Steps to Trigger Behavior

We have specified custom attribution as shown here:

```javascript
const AttributionControl = new MapboxGl.AttributionControl({
    customAttribution: [
        '<a href="mailto:feedback@allencoralatlas.org">Feedback</a>',
        `Data variously licensed and ©${new Date().getFullYear()} Allen Coral Atlas`,
        `<a href="https://www.planet.com/" target="_blank">Reef Mosaic ©${new Date().getFullYear()} Planet</a>`,
    ],
    compact: (getBrowserWidth() < 768),
});
```

But the order in which the custom attribution elements are displayed does not respect the order in which they are specified in the array.

<img width="684" alt="image" src="https://user-images.githubusercontent.com/2359322/139489965-6b87898d-ae24-45bf-9acc-062d1bdd241d.png">

### Expected Behavior

```
Feedback | Data variously... | Reef Mosaic...
```

### Actual Behavior

```
Data variously... | Feedback | Reef Mosaic...
```

**Comment by avpeery** [comment]
Hi @mattskone, thanks for reporting this! We have a fix to allow setting the order of the custom attribution, and will let you know the next time a patch release happens.
