### ISSUE TITLE
Map <div> fills the screen but map <canvas> fills it only sometimes

### ISSUE THREAD

**Issue by Danysan1** [mapbox/mapbox-gl-js#11192]
**mapbox-gl-js version**: 2.5.1 from npm

**browser**:  Chrome for Android and Edge on Windows

### Steps to Trigger Behavior

 1. Initialize the map in a `<div>` element styled to fill the screen
 3. Open the page on a browser

### Link to Demonstration

https://www.dsantini.it/etymology/

(here the map is initialized with [this code](https://gitlab.com/dsantini/open-etymology-map/-/blob/f91118dafefd6eb67a373f9b7fe34a5674ec583e/web/index.js#L387), which to me seems very similar to [the official examples](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/))

### Expected Behavior

The map should  always fill the screen, like that:

- [Good behavior on mobile](https://user-images.githubusercontent.com/8406735/139502542-364192f5-f734-4e6b-adc5-4560f99799ed.jpg)
    - [Dev tools analysis of the `<canvas>`](https://user-images.githubusercontent.com/8406735/139502234-9fe775e0-4b93-4cf0-8d50-2e353f5cff1c.png)
    - [Dev tools analysis of the `<div>`](https://user-images.githubusercontent.com/8406735/139502238-5ad8cd1d-565a-4482-a021-52cc135c671f.png)
- [Good behavior on PC, with dev tools analyisis](https://user-images.githubusercontent.com/8406735/139503974-786f246a-8172-4b23-853d-14ca3518d323.png)

### Actual Behavior

Often the map `<canvas>` does not fill the screen, even though the map `<div>` does fill it:

- [Bad behaviour on mobile](https://user-images.githubusercontent.com/8406735/139502584-4e5c6c08-1542-4dc5-aedf-eaba425de713.jpg)
- [Bad behaviour on mobile](https://user-images.githubusercontent.com/8406735/139502612-39cfa900-250b-4328-8c1f-cdd38199b74f.jpg)
    - [Dev tools analysis of the `<canvas>`](https://user-images.githubusercontent.com/8406735/139502270-dd79ed34-abed-4aca-9b02-0deb0771119b.png)
    - [Dev tools analysis of the `<div>`](https://user-images.githubusercontent.com/8406735/139502272-78d645b8-1c59-4b2a-b809-af62263df94d.png)
- [Bad behavior on PC, with dev tools analyisis](https://user-images.githubusercontent.com/8406735/139503799-0d201846-1d37-4a59-a6c0-2d880d0c7dae.png)

This behavior is somewhat random: you open the page and there is this problem, you reload and it goes away, you reload and it comes back again.

**Comment by Danysan1** [comment]
Taking a further look at the problem I noticed that in the console it appears this warning:

![image](https://user-images.githubusercontent.com/8406735/139505400-4b96810d-180c-4c68-a1d9-e6ffb642a9e7.png)

At the top i see that some inline style is blocked by the Content Security Policy, is it possible that this is the culprit?

If that's the case, the documentation about CSP [at this link](https://docs.mapbox.com/mapbox-gl-js/guides/browsers-and-testing/) needs to be updated specifying that (unsafe) inline style must be allowed with `style-src 'unsafe-inline'`

**Comment by Danysan1** [comment]
CSP was not the culprit: I have added `unsafe-inline` to the allowed styles and the errors are gone but the warnng still remains:

> This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/.

![image](https://user-images.githubusercontent.com/8406735/139507102-9801ffeb-aad0-4e6d-8d4b-0fe48c20688a.png)

But I have included mapbox-gl.css!

From [index.php](https://gitlab.com/dsantini/open-etymology-map/-/blob/36febdf944f11a792967c43a031177b0c4c1e7e5/web/index.php#L82):

>     <link rel="stylesheet" href="./node_modules/mapbox-gl/dist/mapbox-gl.css" type="text/css" />
>     <link rel="stylesheet" href="./node_modules/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.css" type="text/css">

**Comment by ryanhamley** [comment]
I don't believe those CSP errors are coming from GL JS. It looks like they may be from Google Fonts?

As for the CSS, can you try including it before the `mapbox-gl.js` file and see if that solves the issue? The fact that this happens randomly suggests that it's a race condition where the map's display is dependent on whether or not the CSS finishes downloading before the JS is instantiated.

**Comment by Danysan1** [comment]
I have now included the css before the js but the problem keeps happening
 
```html
    <link rel="stylesheet" href="./style.css" type="text/css" />
    <!--<link rel="stylesheet" href="./w3.css" type="text/css">-->
    <link rel="stylesheet" href="./node_modules/mapbox-gl/dist/mapbox-gl.css" type="text/css" />
    <link rel="stylesheet" href="./node_modules/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.css" type="text/css">

    <script defer src='./node_modules/mapbox-gl/dist/mapbox-gl.js' type="application/javascript"></script>
    <script src='./node_modules/@mapbox/mapbox-gl-language/index.js' type="application/javascript"></script>
    <script defer src="./node_modules/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.min.js" type="application/javascript"></script>
```

**Comment by Danysan1** [comment]
Actually I just noticed that for some reason it is stille serving the old code with thee css after the js. I'll fix this and then report about the map problem.

**Comment by Danysan1** [comment]
After I pushed this change I haven't been able to reproduce the problem again, so it's probably solved.

**Comment by Danysan1** [comment]
Thanks for the support
