### ISSUE TITLE
click does not correctly on polygon 

### ISSUE THREAD

**Issue by Shabnam-Veranloo** [mapbox/mapbox-gl-js#11194]
i use mapbox in react project when server start i can draw polygon and click is exactly inside fill but when component change and i back to map component click is lefter than polygon and its depends on zoom level

**mapbox-gl-js version*2.5.1*:

**browser*chrome*:

**Comment by ryanhamley** [comment]
Unfortunately, there's not enough information for us to help. It sounds like it's likely an issue with the particular setup, so I would recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us) and including a minimal reproduction of the issue in your support ticket.
