### ISSUE TITLE
Strange rendering behaviours on neighbouring polys

### ISSUE THREAD

**Issue by derrickpelletier** [mapbox/mapbox-gl-js#1120]
Here's the example polys i'm dealing with. I'm getting this case a lot in my dataset.
http://geojson.io/#id=gist:derrickpelletier/120f98456aa008220767&map=15/37.7060/-122.4393

The point where the left poly fits into the right poly, those vertices are shared, so directly overlapping mesh.

I have two `fill` layers, one for each of the polys using a filter.
And a `line` layer on top of those.

The fills are just a 100% opacity, nothing crazy.
The line is just 100% opacity width 2. Real simple.

Geojson.io screenshot:
![image](https://cloud.githubusercontent.com/assets/833426/6787235/b4535ca4-d14e-11e4-9239-63e145bcc8e3.png)

mapbox gl rendered just lines:
![image](https://cloud.githubusercontent.com/assets/833426/6787228/a7b5db52-d14e-11e4-8a2e-9c711f7349bb.png)

mapbox gl rendered with fills:
![image](https://cloud.githubusercontent.com/assets/833426/6787250/c5f956d4-d14e-11e4-9cf7-5ba020fe85fb.png)

I'm not really seeing anything wrong with the geometries so I suspect it's a rendering issue. Hopefully someone can give some insight, maybe just a mapbox-gl limitation?

**Comment by ansis** [comment]
Yes, it was a rendering issue. Thanks for the great test cases!

**Comment by kkaefer** [comment]
Can we please add test cases for this?

**Comment by ansis** [comment]
@kkaefer rendering test added in https://github.com/mapbox/mapbox-gl-test-suite/commit/e137e95a3dbf4cbcc63679c3f98daca54a57266d
