### ISSUE TITLE
How do I get an array of feature properties in a cluster property

### ISSUE THREAD

**Issue by Kierchon** [mapbox/mapbox-gl-js#11205]
**2.4.1**:

### Question
How do I get an array of feature properties in a cluster??

Im looking to get all of the values of a property (SiteName) in my feature collection that is being clustered together.

```
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [...]
            },
            "properties": {
                "position": "NW",
                "siteName": "Captain USA"
            }
        },
        {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [...]
            },
            "properties": {
                "position": "W",
                "siteName": "Thunder 1"
            }
        }
    ]
}

```

```
        <Source id="devicesSource" type="geojson" data={deviceFeatures} promoteId="id" cluster clusterMaxZoom={14} clusterRadius={50} clusterProperties={{
            site: [["get", "siteName"], ["accumulated"]]
          }}>
```

I want to be able to pull all of the unique siteNames off of my cluster when I click it. But the site ends up being null when I look at the properties of the cluster on click.

How do I get all of the siteNames into the properties or the unique ones?

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson-cluster

**Comment by mourner** [comment]
This might be what you need: https://docs.mapbox.com/mapbox-gl-js/api/sources/#geojsonsource#getclusterleaves
