### ISSUE TITLE
Some lines are not rendering: line-dasharray:[1,0]

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1121]
At https://www.mapbox.com/bites/00108/#14.72/48.8621/2.3456, the weird dashed line is a [tunnel casing](https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/styles/emerald-v7.json#L554-L577) missing its [core](https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/styles/emerald-v7.json#L688-L709).

![screen shot 2015-03-23 at 12 16 06 pm](https://cloud.githubusercontent.com/assets/4551508/6788406/70cb0d44-d156-11e4-8535-481616de53bd.png)

Casing and core have identical sources and filters, and there is nothing in the style that hides the core (it goes from `0px` to `2.25px` from `z14` to `z14.1`, but we are now at `z14.72`). Is this a rendering bug?
Also visible in native.

cc/ @jfirebaugh @incanus

**Comment by peterqliu** [comment]
@ansis found it was a rendering bug with `line-dasharray:[1,0]`

**Comment by jfirebaugh** [comment]
This is fixed now, right?
