### ISSUE TITLE
Is it possible use "flyTo" with gLTF model

### ISSUE THREAD

**Issue by grischenko-v** [mapbox/mapbox-gl-js#11217]
I start project with mapbox and golf models
I load models on the map by ThreeJS loader add them as a source and then I want a call flyTo method to place the model in map bounds. But I do not know how get model bounds.
Is there any possible way to do it?

Another solution that I see is save camera position for each model. But it looks really bad. Does somebody use mapbox in such case?

**Comment by SnailBones** [comment]
To clarify, are you able to place models on the map correctly?

If you store the model's position as a `MercatorCoordinate` as seen in [this example](https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/), you should be able to get its position with [`MercatorCoordinate.tolngLat()`](https://docs.mapbox.com/mapbox-gl-js/api/geography/#mercatorcoordinate#tolnglat).

**Comment by grischenko-v** [comment]
@SnailBones Thank you for answer! My code based on this example.

Now I have an idea. Maybe I can get information about the model from Matrix.

**Comment by ryanhamley** [comment]
It seems like you may have enough to solve this issue, but if not please contact [Mapbox Support](https://support.mapbox.com/hc/en-us) for more help. Thanks!

**Comment by grischenko-v** [comment]
Finally I solve it)
Now each gLTF model has camera options. When I need to fly to model, I call flyTo with model coords and camera options.
If anybody looking for help in this case - you are welcome.
