### ISSUE TITLE
polygon simplification tends to shrink things

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#1122]
This is zoom level 0, but the problem is pretty noticeable down to z2:

![screen shot 2015-03-24 at 4 11 45 pm](https://cloud.githubusercontent.com/assets/108094/6811744/7db82308-d240-11e4-84ca-7726e182640d.png)

All complex polygons are smaller that they should be. Like everything has 10% shaved off. I would expect simplification to try to keep things roughly the same perceived size.

**Comment by mourner** [comment]
Doesn't look like polygon simplification, it's something style/rendering-related...

**Comment by samanpwbb** [comment]
> Doesn't look like polygon simplification, it's something style/rendering-related...

Heh, you're totally right. I just went to make an isolated test case and then things looked way better. Something's up with this particular style.
