### ISSUE TITLE
Additional Controls

### ISSUE THREAD

**Issue by derrickpelletier** [mapbox/mapbox-gl-js#1123]
Just wanted to get some info on the plans for more controls.

Is the plan to have some controls embedded in the core, like how Geocoder is part of `mapbox.js`, or is it to be more of a plugin style, like the fullscreen component?

I ported both to use with `mapbox-gl-js`, but just quick versions for prototyping.

**Comment by jfirebaugh** [comment]
A geocoder control would likely be an external plugin. Written and maintained by Mapbox but in a separate repo.
