### ISSUE TITLE
port sprite scaling

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1124]
https://github.com/mapbox/mapbox-gl-native/commit/48c55af5c1d39e9a29cdb2e0c8203e6767f76c57

I'm not sure that scaling up images when adding them to the sprite atlas is the right approach. They'll get bilinearly interpolated again when they are sampled in gl. Doing this in two separate steps instead of letting gl handle the scaling might produce blurrier results.

**Comment by ansis** [comment]
@kkaefer can you comment on why it's preferable to scale images when adding them to the sprite instead of just scaling them in gl?

**Comment by kkaefer** [comment]
We're doing this in response to pixel ratio changes: When pixel ratio of the map changes (e.g. the user drags the window to a screen with different pixel density), we're scaling the existing sprite atlas immediately, and kick of loading the sprite for the new pixel ratio. This takes some time though; and meanwhile we're showing the old (scaled) sprite. However, we need the space so we can update the sprite atlas with more appropriate graphics once the new sprite image is in.

**Comment by kkaefer** [comment]
Secondly, we're only doing bilinear interpolation when the user is dragging/rotating the map, not when it's standing still.

**Comment by ansis** [comment]
How often do pixel density changes happen? It seems like something that happens rarely on the web and almost never on mobile. I'm not sure it's something we need to handle at all as long as the old images render at the right size. Or we could just blow everything away and reparse tiles.

>  we're only doing bilinear interpolation when the user is dragging/rotating the map, not when it's standing still.

We're doing it when the map is standing still for
- patterns
- icons aligned with lines (oneway arrows)
- every icon in perspective view

**Comment by jfirebaugh** [comment]
Not going to do this: https://github.com/mapbox/mapbox-gl-native/issues/3164.
