### ISSUE TITLE
Arabic cities aren't shown correctly 

### ISSUE THREAD

**Issue by MustaphaGHA** [mapbox/mapbox-gl-js#11253]
If you try to zoom into any arabic place , the name of the city isn't shown correctly ( letters are reversed ) 

*Expected Behaviour :* 

باردو 

* Actual Behaviour :* 

![image](https://user-images.githubusercontent.com/72300612/140608621-2f1122b6-a26f-4f3c-bb06-3896fa5410ff.png)

**Comment by mourner** [comment]
This is a known issue — support for RTL languages is not enabled by default, and requires an additional plugin. See https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/ for the example.
