### ISSUE TITLE
Use higher resolution sprite to improve rotated / scaled icon rendering

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1125]
When icons are not rendered at their original resolution and orientation, we use linear filtering to get the scaled/rotated version. It may be good to use a higher resolution source image to offset the blurriness caused by linear filtering.

I'm not sure this makes sense.

We use linear filtering for:
- fill and line patterns
- icons that are rotated (one way arrows)
- icons that are scaled (every icon in perspective view)
- all icons while the map is being panned/rotated/zoomed

**Comment by jfirebaugh** [comment]
This will be subsumed by vector icons.
