### ISSUE TITLE
Animate between projections with setProjection

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11254]
Calling `map.setProjection` triggers a brief flash as the map is re-rendered with the new projection. It would be nice if this method supported an animation tween for smooth transitions between projections. Something as simple as this:

~~~js
map.setProjection({ name: 'albers', center: [-96, 37.5] }, { duration: 100 })
~~~

**Comment by mourner** [comment]
This is unfortunately almost impossible to implement with the current projections design. We have to fully reload the tiles in the view and reprocess their geometries from scratch using the new projection, which does not align well with smooth transitions. Not sure if we should keep this open when we don't know how to do this, but maybe @ansis has ideas.

**Comment by ansis** [comment]
Yep, I don't think we'll be able to implement this. There would be many challenges with doing this with good enough performance and the use cases are pretty narrow.

**Comment by chriszrc** [comment]
@ansis what about at least something to help with FOUC, like rendering the map with the new projection behind the existing one so the transition isn't so jarring?
