### ISSUE TITLE
Can I add image for floorplan where I can rotate image for adjustment, zoom in/out and drag drop

### ISSUE THREAD

**Issue by usamamalik75** [mapbox/mapbox-gl-js#11259]
**mapbox-gl-js version**: latest one

### Question
I want to give option for our customer to add floorplan image and they can drag drop image and rotate and can fit where they want. Is it possible with Mapbox OR any idea how I can achieve this feature

**Comment by usamamalik75** [comment]
> and

**Comment by SnailBones** [comment]
Yes, this is possible. See examples for [draggable marker](https://docs.mapbox.com/mapbox-gl-js/example/drag-a-marker/) and [https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/]().

For future "how do I" questions like this, please refer to our help documentation, and if you can't find the answer there, contact support. This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
