### ISSUE TITLE
Match the user’s language

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#1126]
Along the lines of mapbox/mapbox-gl-native#1108, it should be possible for the map to show labels in the user’s language (`navigator.languages` or `navigator.language`). Apple Maps for example provides a localization option to the user.

**Comment by vincentlaucy** [comment]
+!

**Comment by jfirebaugh** [comment]
We build an [example of how to switch languages](https://www.mapbox.com/mapbox-gl-js/example/language-switch/). It's up to specific implementations if they want to do this though -- doesn't fit well as a default library behavior.
