### ISSUE TITLE
`map.setProjection` should return a map object for function call chaining

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#11277]
Most our `set*` APIs return a map object to allow for function call chaining, e.g.:
```
map.setProjection().setZoom().set...
```
Currently, `map.setProjection` doesn't follow that pattern. We should update that for API consistency.

Refer https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/map.js#L1020_L1027.

cc @ryanhamley

**Comment by lpizzinidev** [comment]
Hi @karimnaaji. Can I work on this issue?

**Comment by karimnaaji** [comment]
Hello @lpizzinidev , yes!

**Comment by ryanhamley** [comment]
Closed by e534c870dc2a0c383c4e18095720e150f9713788 Thanks @lpizzinidev!

**Comment by karimnaaji** [comment]
Reopening as it was noticed that `map.setProjection` should also trigger an update, refer to @rreusser and @tristen examples in https://observablehq.com/d/c3799d41f58a5858 vs https://observablehq.com/compare/c3799d41f58a5858...f4c80005a5598a3e, where the first doesn't trigger a new repaint when editing the projection properties.

I think the fix should be as simple as using `return this._update()` instead of `this`, but we'd just have to add a test case covering this issue.
