### ISSUE TITLE
How can I customize the shader to change the layer‘s building material

### ISSUE THREAD

**Issue by yueyanshaosun** [mapbox/mapbox-gl-js#11274]
**mapbox-gl-js version**: v2

### Question
How can I customize the shader to change the layer‘s building material

### Links to related documentation

hello my dear:
 I am a Chinese developer, please ignore my poor English, for a long time,  I've always wanted MapBox to be like Threejs, to be able to customize shader materials, at least use shader on geojson buildings, to do what my desired effect, like "gradient", "sweep", etc；  
 I sincerely wish there were such interfaces or even examples；
just like this example：
https://codesandbox.io/s/elegant-feynman-1imdm?file=/index.html
https://www.wellyyss.cn/demo-3d/#/index4

**Comment by ryanhamley** [comment]
Hi @yueyanshaosun as you noted, GL JS does not currently allow custom shaders for most layers, including fill-extrusions (3d buildings). Depending on what you want to accomplish, there are a number of options available. We have ways to [style fill-extrusions](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#fill-extrusion) and it's possible to do some interesting, dynamic things with them, such as [this example](https://docs.mapbox.com/mapbox-gl-js/example/dancing-buildings/).

It is also possible to use Three.js (or any other shaders/3d libraries) directly using a [custom layer](https://docs.mapbox.com/mapbox-gl-js/api/properties/#customlayerinterface) but you'll need to provide your own models. Here's a [basic example](https://docs.mapbox.com/mapbox-gl-js/example/custom-style-layer/) of that and here's an [example of how to add a 3d model](https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/).

For more advanced data visualizations, you may also want to check out the [deck.gl](https://deck.gl/) plugin, although Mapbox does not maintain that.

If you need further support, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us). Good luck!
