### ISSUE TITLE
Add easing to `map.setPitch()`

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-js#1128]
I think a lot people will end up using wrapping this function in a `setInterval` to get a smooth animation like:

```js
var pitch = 0;
setInterval(function(){
    pitch++;
    map.setPitch(pitch);
}, 45);
```

Would it make sense to add a second optional argument to take care of this for devs? Something like `map.setPitch(angle, speed);`

/cc @ansis

**Comment by ansis** [comment]
@bsudekum this is taken care of with `map.easeTo(latlng, zoom, bearing, pitch, options)`.

`easeTo`'s arguments might change in the near future: https://github.com/mapbox/mapbox-gl-js/issues/1051.

It probably makes sense to keep `setPitch` simple and instant just like `setZoom`, `setCenter`, `setBearing`.
