### ISSUE TITLE
Sprite doesn't work

### ISSUE THREAD

**Issue by BerkayAkgurgen** [mapbox/mapbox-gl-js#11281]
I want to load sprites on my mapbox studio map via my own URL. My png, JSON files are ready, but they are not reflected in my map.

```
  const Mapbox = ReactMapboxGl({
    accessToken: mapStyle.accessToken,
    preserveDrawingBuffer: true,
    sprite: "https://example.com/sprites/sprites",
  });
```

**Comment by ryanhamley** [comment]
Hi @BerkayAkgurgen unfortunately we cannot solve your issue with the limited information in this ticket. If you can share the sprite URL or a working (and minimal) example of the issue, that would help us respond.

**Comment by ryanhamley** [comment]
Going to close this since it's not actionable as is. If you provide more info, we can re-assess.
