### ISSUE TITLE
Vector Tile feature-level access

### ISSUE THREAD

**Issue by apollolm** [mapbox/mapbox-gl-js#1129]
Howdy.  Just a question/possible enhancement.

I'd like to be able to get access to individual features without having to use featuresAt().  What I'm trying to do is access/inject dynamic properties into the vector tiles features that are currently loaded in the map, and subsequently create a choropleth map. Digging thru the code, it looks like I might be able to get access to features on a tile-by-tile basis. 

I'd also like to be able to set a style for an individual feature.  I imagine that to do this now would mean injecting some new layers that employ filters specific to the ID of an object I want to, say, highlight.  Then the matching features would be rendered with the updated layer style.

Thoughts on accessing a feature or setting a feature's style?

**Comment by jfirebaugh** [comment]
Hi Ryan, It sounds like your underlying need is to style the data based on its attributes. Take a look at https://github.com/mapbox/mapbox-gl-style-spec/issues/249 for our plans on that front and let me know if it sounds promising for your use case.

**Comment by apollolm** [comment]
Thanks - That will probably handle the styling piece.
As far as the access to features and properties - I currently bake vector tiles usually with an ID and maybe a label property.  Other properties are changing frequently, or are not known ahead of time.  What I do is hit an API to pull down additional properties at run time (based on user defined filters, perhaps) and then add the properties into the vector tile properties, and THEN render them.  So I'm wondering if this would be possible to do still in GL?

Thanks!

**Comment by jfirebaugh** [comment]
It wouldn't be possible to add additional properties to vector tile features, but you could do that with a GeoJSON source instead.
