### ISSUE TITLE
set offset for tiles or sources

### ISSUE THREAD

**Issue by PZD2937** [mapbox/mapbox-gl-js#11304]
Sometimes the tiles or sources are loaded incorrectly. Can you set an offset for them?
I tried to modify the calculatePosMatrix myself to add an offset, but the problem of the screen edge blank after the offset is not solved and the tiles will be messed up when tilted. Please let me know if you have any solutions, thanks!

**Comment by mourner** [comment]
No. The tile sources are expected to be in the Web Mercator tiling scheme. If they don't align, a constant offset isn't likely to help anyway. You should make sure the source is in the right projection.
