### ISSUE TITLE
Can I listener event load tile in mapbox gl js?

### ISSUE THREAD

**Issue by cuongnc5** [mapbox/mapbox-gl-js#11314]
I need improved performance when load multiple polygon. So I think i can load polygon when mapbox load tile. Can I listener event load tile in mapbox gl js?

**Comment by carlosrziegler** [comment]
I think you can use it : map.areTilesLoaded(); https://docs.mapbox.com/mapbox-gl-js/api/map/#map#aretilesloaded

**Comment by cuongnc5** [comment]
> I think you can use it : map.areTilesLoaded(); https://docs.mapbox.com/mapbox-gl-js/api/map/#map#aretilesloaded

I think i need event the same as areTilesOnLoad, because i need get z/x/y of tile and i can get polygon by z/x/y.

**Comment by mourner** [comment]
See https://docs.mapbox.com/mapbox-gl-js/api/map/#events-data-loading
