### ISSUE TITLE
How to i display buildings 3d with filter not in array of osm id?

### ISSUE THREAD

**Issue by cuongnc5** [mapbox/mapbox-gl-js#11313]
I need hide a lot of buildings in array osm id. IS not found expressions "not in" https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/. So how to i resolve it?

**Comment by brncsk** [comment]
Hey, @cuongnc5 - you might want to negate the expression by applying the [negation expression](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#!)  to the one you already assembled.

If you have an `in` expression in the form of `[“in”, …]` you’ll have to embed it into the `!` operator like this: `[“!”, [“in”, …]]`.

Please also do note, that for “how-to” style questions, like this, StackOverflow might be a better fit in the future, as opposed to this repo which is for the purpose of reporting potential bugs and/or feature suggestions about gl-js itself.

**Comment by cuongnc5** [comment]
Thank for you help

> Hey, @cuongnc5 - you might want to negate your expression by applying the [negation operator](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#!) to it.
> 
> If you have an `in` expression in the form of `[“in”, …]` you’ll have to embed it into the `!` operator like this: `[“!”, [“in”, …]]`.
> 
> Please also do note, that for “how-to” style questions, like this, StackOverflow might be a better fit in the future, as opposed to this repo which is for the purpose of reporting potential bugs and/or feature suggestions about gl-js itself.

It worked!
Thank fo your help!
