### ISSUE TITLE
Can Mapbox GL JS cluster across multiple sources?

### ISSUE THREAD

**Issue by Joey-Rose** [mapbox/mapbox-gl-js#11312]
**mapbox-gl-js version**: v2.2.0

### Question
Mapbox GL JS can cluster a geojson source on the fly using Supercluster [under the hood](https://github.com/mapbox/mapbox-gl-js/blob/2924b910d7a9a0a12e0d71bd0771f7529acfade8/js/source/geojson_worker_source.js#L130), but would it ever be capable of clustering data from more than one source? I have geojson source *and* an already clustered vector tile source (thanks to Tippecanoe) that I wish to have clustered together before rendering takes place to avoid overlapping clusters. However, it seems as though clustering is done on a source-by-source basis, meaning that unified clustering is not feasible?

Here's a screenshot showing how separated clustering can lead to overlapping circle layers (where green represents the already clustered vector tile source and red represents the geojson source):
![image](https://user-images.githubusercontent.com/52545237/143659259-26fdc478-3b94-49b0-966f-a6d665d92127.png)

### Links to related documentation

https://docs.mapbox.com/help/troubleshooting/working-with-large-geojson-data/#clustering
https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson-cluster
https://docs.mapbox.com/mapbox-gl-js/example/cluster/
https://github.com/mapbox/mapbox-gl-native/issues/11173#issuecomment-365357714

**Comment by mourner** [comment]
Yes, unfortunately it's not possible at the moment, and likely won't be for the foreseeable future due to the implementation difficulty.
