### ISSUE TITLE
distanceTo

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#1131]
Provide a `distanceTo` function that returns a metre distance between two coordinates like [leaflet does it](https://github.com/Leaflet/Leaflet/blob/98bf92530f56c0bee1f0764e0934a25db6a6692d/src/geo/crs/CRS.Earth.js#L11-L19)?

**Comment by peterqliu** [comment]
hmm, would it be better to do this, or make users add Turf for these kinds of measurements?

**Comment by jfirebaugh** [comment]
This is plugin/external library territory.
