### ISSUE TITLE
Heatmap Layer not displaying on android device (Samsung Galaxy A12)

### ISSUE THREAD

**Issue by thevisualagency** [mapbox/mapbox-gl-js#11327]
Hello, 
we are developing a SPA  application with Vue and mapbox GL js  for a client. 
In the mobile version the application consists of a full screen mapbox map layer and a mapbox heatmap layer. 

The heatmap layer is not displaying on the android mobile device of our client which is a  Samsung Galaxy A12.
In the Chrome developer console we can find the following error:

**[.WebGL-0xd7af9f00]RENDER WARNING: texture bound to texture unit 0 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?**

During our testing we ask the client to connect to the mapbox heatmap layer  example page https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/ and he reported that the example heatmap layer is not visible either with the same console warning we  mentioned before.

Since this example layer is not visible either on that specific device we are oriented to think that the issue is not related to our code, but we can provide further information if needed.

**mapbox-gl-js version**: 2.4.1

**browser**:Chrome

### Steps to Trigger Behavior

 1. Open https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer with chrome on Samusung Galaxy A12
 2. The heatmap layer is not visible

**Comment by mourner** [comment]
Yeah, the heatmap layer rendering currently depends on non-power-of-two textures, although they are generally [considered universally supported](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial/Using_textures_in_WebGL), so it's surprising to see such an error in a newer phone like Galaxy A12. We'll investigate.

**Comment by zuselli** [comment]
I have the same problem. 
heatmap layer is showing up perfect on desktop screens, iphone 11 but not working with android (Huawei RedMi 9A, Caterpillar) 
Also original example is not working with these two devices.. 
is there already a fix for this issue?
@thevisualagency could you solve this problem?

**Comment by astojilj** [comment]
Looks like it is about handling cases when OES_texture_half_float_linear is not supported.

https://github.com/mapbox/mapbox-gl-js/blob/4fc94453304834760e6ea70fa5ac03ed6b0e435a/src/gl/context.js#L130-L133 


![Screenshot 2023-01-20 at 8 36 59](https://user-images.githubusercontent.com/549216/213634203-11da1735-58b5-4c87-b0e6-056b6b6679da.png)

**Comment by astojilj** [comment]
The approach in https://github.com/mapbox/mapbox-gl-js/pull/12514 should resolve the issue, but let's keep the issue open until verified as fixed by the reporters. I don't have the hardware to check it.

**Comment by zuselli** [comment]
Wow, I'm impressed. 
I would love to verify your changes and see if it works on this specific hardware. 
But I'm a beginner in developing and I don't know how to implement your changes in my application. :-(

**Comment by astojilj** [comment]
❤️ . Nothing impressive there, really, regardless if it fixes the issue or not. If you prefer not to build it yourself,

**Comment by zuselli** [comment]
I think I'll wait for the next release and report it here. 
Do you know how frequently these releases will be released?

**Comment by zuselli** [comment]
hmm just realized that I'm using maplibre gl js and not mapbox gl js. So probably this fix is not included in the maplibre version...

**Comment by zuselli** [comment]
I coulnd't wait and did the standalone build according instructions :-) 
It's working now perfectly, thanks for helping :-)
