### ISSUE TITLE
Redundant title text on "Improve this map" link

### ISSUE THREAD

**Issue by anthony0030** [mapbox/mapbox-gl-js#11324]
**mapbox-gl-js version**: v2.6.1

**browser**: N/A

### Steps to Trigger Behavior

 1. Scan a page with the [Wave evaluation tool](https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh)

On version 2.6.1 
The text is: Improve this map
The title is: Improve this map

On Version 2.3.1
The text is: Improve this map
The title is: Map feedback

**Why it matters to me**
In Greece to get into a government program for a website grant, your website must pass certain tests. One of which is the WAVE evaluation tool. I am planning on using MapBox for future projects. I would like to use the most up-to-date version. But I can't due to it not passing the test.

Information from WAVE

**Alerts**
Redundant title text

**What It Means**
Title attribute text is the same as text or alternative text.

**Why It Matters**
The title attribute value is used to provide advisory information. It typically appears when the user hovers the mouse over an element. The advisory information presented should not be identical to or very similar to the element text or alternative text.

**How to Fix It**
In most cases, the title attribute can be removed, otherwise modify it to provide advisory, but not redundant information. Note that the title text may or may not be read by a screen-reader and is typically inaccessible to sighted keyboard users.

**Comment by mourner** [comment]
@avpeery this seems to have regressed with https://github.com/mapbox/mapbox-gl-js/pull/11064 because we no longer overwrite the title on the improve link directly. Can you take a look?
