### ISSUE TITLE
Where to report problems with elevation data?

### ISSUE THREAD

**Issue by etherlind** [mapbox/mapbox-gl-js#11320]
**mapbox-gl-js version**: 2.6.0

### Where to report problems with elevation data?
According to [the troubleshooting guide](https://docs.mapbox.com/help/troubleshooting/reporting-a-problem/), there is a [map feedback page](https://www.mapbox.com/contribute/#/?utm_source=https%3A%2F%2Fdocs.mapbox.com%2F&utm_medium=attribution_link&utm_campaign=referrer) but it doesn't allow for elevation data issue reporting. 

### Example
My exact issue at hand is that there is a significant dip where there should be the Matterhorn peak: 

![Screenshot 2021-12-01 at 09 12 21](https://user-images.githubusercontent.com/45455098/144197904-9b0b1a96-fa79-457c-b0d7-12a5302f9e99.png)

### Links to related documentation
I'd expect it to be documented here: https://docs.mapbox.com/help/troubleshooting/reporting-a-problem/

**Comment by SnailBones** [comment]
@mapbox/raster-tilesets-team

**Comment by abhumbla** [comment]
@etherlind thanks for the ticket! This is a known issue in our terrain data, and unfortunately we don't have it on our near term roadmap to fix. This is an artifact coming from the SRTM dataset, which is our elevation dataset for much of the world. We would need to find and integrate a different data source to fix this, or spend time manually correcting individual errors.

We are looking into improving the process to report feedback like this, thank you again for opening this ticket and prompting that discussion!

**Comment by SnailBones** [comment]
Closing as this falls outside the scope of the GL-JS codebase and is being addressed.

As @abhumbla mentioned our team is looking into setting up a feedback system for terrain data issues. @etherlind if you find further issues before that is available, I encourage you to comment on this issue.

Thanks @etherlind for bringing this to our attention and @abhumbla for your work on the feedback pipeline!
