### ISSUE TITLE
How to monitor map layer changes

### ISSUE THREAD

**Issue by FakeGISer** [mapbox/mapbox-gl-js#11338]
I Want to Listen layer change of the map. For example,addLayer,removeLayer.

**Comment by ryanhamley** [comment]
I'm not exactly sure what it is you want to achieve. You can listen for an event such as `styledata` to know when the style is changing. If you want to know when `{add/remove}Layer` specifically is being called, you may want to wrap the methods in your own function that does whatever notification you need. If you need more help, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).
