### ISSUE TITLE
Zoom crashes when mapbox-gl is compiled by swc

### ISSUE THREAD

**Issue by heldr** [mapbox/mapbox-gl-js#11332]
Hi! 

I'm using `mapbox-gl-csp` and `mapbox-gl-csp-worker` v2.6.1 in a Next.js app where all [CSP headers listed in mapbox docs](https://docs.mapbox.com/mapbox-gl-js/guides/browsers-and-testing/#csp-directives) are already set.

On localhost everything works nicely, on CDN(Vercel in our case) maps with a custom style works only with default `zoom=7` , but once zoom changes all map core layers are hidden.

Does anybody have any idea how to fix that? Or what CSP directive would fix this? I'm also attaching error logs from Chrome and Firefox.

### Map example
![CleanShot 2021-12-06 at 15 04 36](https://user-images.githubusercontent.com/134727/144898439-9d5a71be-6f73-4dd0-ba42-2d5e9a9669a6.gif)

### Chrome error
<img width="519" alt="CleanShot 2021-12-06 at 15 10 00@2x" src="https://user-images.githubusercontent.com/134727/144899080-dd47e014-b870-43d8-bf78-aa7e9c25b813.png">

### Firefox
<img width="304" alt="CleanShot 2021-12-06 at 15 12 13@2x" src="https://user-images.githubusercontent.com/134727/144899373-8e0d3850-37d8-469b-ad74-412cfa890bfc.png">

**Comment by mourner** [comment]
This does not appear to be related to CSP — it seems to be a bug related to line-dasharray settings in the style. Can you provide a minimal JSFiddle or JSBin test case that reproduces this?

**Comment by heldr** [comment]
Bug only happens on production version, I created 2 sandboxes, one in dev mode and other in production mode.

dev mode (with code as production)
https://codesandbox.io/s/friendly-hawking-y1m82?file=/src/App.tsx

Production mode (please zoom in or zoom out to reproduce the issue)
https://mapbox-sandbox.vercel.app/

**Comment by heldr** [comment]
After some research I figure this out

Zoom issue happens when `mapbox-gl` is compiled/minified in Next.js 12 with [SWC](https://github.com/swc-project/swc) enabled.

With SWC enabled
https://nextjs-netlify-b77t3cmr9-heldr.vercel.app/

Without SWC
https://nextjs-netlify-6of28w5sf-heldr.vercel.app/
https://61b2572b9d32d9ea7f040f17--cranky-bose-a8a255.netlify.app/

I'm going to up an issue in SWC and links this one as reference.

**Comment by heldr** [comment]
FIxed on next.js 12.0.7
https://github.com/vercel/next.js/issues/32336#issuecomment-990381448

https://mapbox-sandbox.vercel.app/

**Comment by garretteklof** [comment]
This still seems to be an issue .. due to the size of the private app it's been difficult to isolate the cause (or give a sandbox).. however when I run our web app with `swcMinify:true` outside of a local environment .. I get many client-side exception errors including `i is not a Constructor` .. any thoughts? We also use custom vector map styles via Mapbox.

**Comment by vogelino** [comment]
I am experiencing similar issues as @garretteklof. I use `swcMinify: true`, `mapbox-gl` and `react-map-gl`. Locally, everything runs fine too, but when using the deployed/minified version, the map doesn't load and I get a lot of different errors like `i is not a constructor` or `Cannot read properties of undefined (reading 'recalculate')`.

The deployed map with next 12 and `swcMinify: true`: https://stadtpuls-frontend-qjwfqp413-technologiestiftung1.vercel.app/sensors

**Comment by Ojay** [comment]
I've been stuck with this issue too, exactly the same as @vogelino - disabling `swcMinify` fixed the issue.

**Comment by jeafreezy** [comment]
Helpful tip @Ojay .

`swcMinify : false` solves it.
