### ISSUE TITLE
maybe offse first line label by text-padding

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1133]
Even if the symbol spacing is high enough (1000px) that it only places one label per tile you could end up with many close labels because of tile boundaries:

![screen_shot_2015-03-20_at_5 55 24_pm](https://cloud.githubusercontent.com/assets/1421652/6903712/21eb0d16-d6d1-11e4-89ff-e18ee9f88387.png)

This is because we place labels as close to the beginning of lines as possible. We might want to offset the first label by the text-padding property (or not-yet-implemented text-repeat-distance property).

cc @peterqliu

**Comment by peterqliu** [comment]
this sounds good, but it's hard to foresee quirks that may happen. let's try it

**Comment by nickidlugash** [comment]
This would be useful for oneway arrows on very short road segments:

![screen shot 2015-04-14 at 3 47 09 pm](https://cloud.githubusercontent.com/assets/5607844/7146239/28822ff6-e2c0-11e4-8be5-1bb9d8e5d102.png)

I've previously hacked my way around this in carto styles by including a space before the icon in the image file itself, but that doesn't render well in GL.

**Comment by nickidlugash** [comment]
@ansis could this possibly be implemented at the same time as adding [-repeat-distance](https://github.com/mapbox/mapbox-gl-style-spec/issues/269) properties?

**Comment by ansis** [comment]
I don't think we need to do this
