### ISSUE TITLE
How do I get the Tile3DHeader object in MapBoxgl via the onclick event in deck.gl? 

### ISSUE THREAD

**Issue by liu707852224** [mapbox/mapbox-gl-js#11345]
I now load the 3DTiles data using deck.js on MapBoxGL.  However, the event added via onclick cannot trigger the retrieval of the Tile3DHeader object.  How do I get Tile3DHeader from mapBoxGL?

**Comment by stepankuzmin** [comment]
Hi @liu707852224,

Mapbox GL JS provides the API for external libraries and doesn't operate with deck.gl layers itself. I'm not sure, but probably you should add `pickable: true` on your `Tile3DLayer`

https://deck.gl/docs/api-reference/geo-layers/tile-3d-layer#pickable

**Comment by liu707852224** [comment]
I also tried ScatterplotLayer to set pickable: true. The onclick of ScatterplotLayer can take effect, but Tile3DLayer did not take effect after setting it in accordance with the API Reference. I tried to read the source code and found that the webgl of deck.gl and the webgl of mapboxgl seem to be somewhat different. I have attached the code, please help me to see it, thank you.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mapbox/mapbox-gl-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月15日(星期三) 晚上6:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mapbox/mapbox-gl-js] How do I get the Tile3DHeader object in MapBoxgl via the onclick event in deck.gl?  (Issue #11345)





 
Hi @liu707852224,
 
Mapbox GL JS provides the API for external libraries and doesn't operate with deck.gl layers itself. I'm not sure, but probably you should add pickable: true on your Tile3DLayer
 
https://deck.gl/docs/api-reference/geo-layers/tile-3d-layer#pickable
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by stepankuzmin** [comment]
Most likely, this is a deck.gl issue. You should open an issue in the deck.gl repo https://github.com/visgl/deck.gl

**Comment by ryanhamley** [comment]
I agree with @stepankuzmin that this is likely a deck.gl issue and that would be the appropriate place to seek further information. If you determine that it is a Mapbox GL JS issue, we can re-open this ticket, but please provide us with a minimal, working example of the issue using a site like JSFiddle or CodePen to demonstrate what you're seeing.

**Comment by liu707852224** [comment]
Hello, I created a CodePan project as you said, please help me to see it, thank you! https://codepen.io/liu707852224/project/editor/AwyNwe




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ryan ***@***.***&gt;; 
发送时间: 2021年12月18日(星期六) 凌晨4:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mapbox/mapbox-gl-js] How do I get the Tile3DHeader object in MapBoxgl via the onclick event in deck.gl?  (Issue #11345)





 
I agree with @stepankuzmin that this is likely a deck.gl issue and that would be the appropriate place to seek further information. If you determine that it is a Mapbox GL JS issue, we can re-open this ticket, but please provide us with a minimal, working example of the issue using a site like JSFiddle or CodePen to demonstrate what you're seeing.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
