### ISSUE TITLE
The problem of syncing with the threejs camera in the custom layer

### ISSUE THREAD

**Issue by famousgeneral306** [mapbox/mapbox-gl-js#11347]
**mapbox-gl-js version v1.13.1 **
**three.js version r117 **
I want to get the matrixWorldInverse and projectionMatrixInverse of the camera.
But But it seems that after synchronization, the this.camera.projectionMatrix in the mapbox render function contains more information than the camera.projectionMatrixInverse of threejs. They are not always updated, and this.camera.projectionMatrixInverse is not updated simultaneously.

**Comment by stepankuzmin** [comment]
Hi @famousgeneral306 

Could you please add more context for this or provide a reproducible example? I'm not sure, but most likely, the problem might be somewhere in the synchronization itself than on GL JS side.
