### ISSUE TITLE
Feature size-based layer order

### ISSUE THREAD

**Issue by mofoyoda** [mapbox/mapbox-gl-js#1134]
I'm trying to style overlapping features of the same source layer (it's landcover data from OSM PostGIS import). The order of map layers is controlled by order of their declaration in the style. 
Problem is, that layers in mapbox-gl map contain only one filter (unlike mapnik layers, that can have multiple rules per style), so I can't have different layers rendered on the same "level". If a feature of the next declared layer overlap a feature of the previous layer, it will always be rendered on top of it. 
In mapnik this is easily solved by using ```ORDER BY way_area DESC``` in SQL query, so larger features get rendered earlier, and smaller features later. But when rendering with mapbox-gl ```ORDER BY``` doesn't make sense. 
I can't think of a possible workaround. Is there a solution for this case?

**Comment by ansis** [comment]
There isn't a good way to do this right now.

We're working on a way to set style properties per-feature: https://github.com/mapbox/mapbox-gl-style-spec/issues/249 When that is implemented you'll be able to create a single layer that contains different landuse types with different styles.

**Comment by mofoyoda** [comment]
Will it be possible to have multiple symbols per layer? 

Data-driven style properties are a great idea, but that only partially solves the problem. Usually polygon features are represented with ```fill``` and ```line``` symbols. So even if there'll be a data-driven per-feature ```fill-color```, all the outlines will be drawn on top, so that they overlap ```fill```s of smaller features. 
Ideally ```fill``` layer should have ```line``` properties aswell for it's outline (like mapnik symbolizers do). Any plans for that?

**Comment by jfirebaugh** [comment]
We've talked about having a polygon layer type which supports both fill and stroke, but haven't committed to yet: https://github.com/mapbox/mapbox-gl-style-spec/issues/223.

**Comment by lucaswoj** [comment]
We now support data-driven styling, the GL JS solution to these requirements 🎉
