### ISSUE TITLE
support for sdf patterns

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1135]
It should be possible to use a sdf images for fill and line patterns.

**Comment by bhousel** [comment]
Can this issue be closed or moved to [mapbox-gl-style-spec](https://github.com/mapbox/mapbox-gl-style-spec)?

**Comment by lucaswoj** [comment]
@bhousel We should open a parallel issue in mapbox-gl-style-spec](https://github.com/mapbox/mapbox-gl-style-spec), reference this issue, and keep both open.

**Comment by bhousel** [comment]
Per [style spec](https://www.mapbox.com/mapbox-gl-style-spec/#sprite) it seems that we support PNG only.

**Comment by lucaswoj** [comment]
Right you are. I found an old ticket at https://github.com/mapbox/mapbox-gl-style-spec/issues/117

**Comment by lucaswoj** [comment]
The fate of sdf support is uncertain at the moment. Closing this as stale.

**Comment by markusand** [comment]
sdf discussions have been closed a long time ago and sdf is supported in mapbox-gl-js, but I can't find if there's been any movements in supporting sdf for patterns.

My use case is simple: display a layer with vehicles paths. Path has an arrow pattern to identify the direction, and line is colored differently for each vehicle from a data property. I currently load the same pattern as png in different colors, but this is not scalable at all.
