### ISSUE TITLE
Terrain error reporting from style without terrain when using globe projection

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11352]
Notice the small preview map in Studio with a globe projection:

![projection-blib](https://user-images.githubusercontent.com/61150/147147054-f5e085b9-dfdb-4cb7-be5c-fc0ae1ff1158.gif)

It looks like there are instances where a map calling `map.setProjection('globe')` expects terrain to exist so it throws:

> Error: terrain: terrain is missing required property "source"

---

<details>
<summary><b>Simplified style for reference</b></summary>

```js
{
  version: 8,
  center: [0, 20],
  zoom: 0,
  sources: {
    composite: {
      url: 'mapbox://mapbox.mapbox-streets-v8',
      type: 'vector'
    }
  },
  sprite: 'mapbox://sprites/mapbox/streets-v11',
  glyphs: 'mapbox://fonts/mapbox/{fontstack}/{range}.pbf',
  layers: [
    {
      id: 'land',
      type: 'background',
      paint: {
        'background-color': '#ccc'
      }
    },
    {
      id: 'water',
      type: 'fill',
      source: 'composite',
      'source-layer': 'water',
      paint: {
        'fill-color': '#fff'
      }
    }
  ]
};

// After initializing the map style. setProjection is called:
map.setProjection('globe');

```

</details>

**Mapbox GL JS version:** `2.7.0-alpha.1`

**Comment by karimnaaji** [comment]
I gave it a look but haven't been able to reproduce this one after a few combination of calls (using the style provided). There might be a missing piece specific to the studio context. Are there any other calls made on the map?

**Comment by tristen** [comment]
@karimnaaji here's a reproducible example! See https://github.com/mapbox/mapbox-gl-js/blob/8d18e483f96427155986d963d20150463b88093a/debug/globe.html
