### ISSUE TITLE
Only symbol features appear queryable in globe view

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11356]
It appears as though querying features other than symbol layers are not detected if the projection is set to `globe`. In this example, I'm clicking on north America and layers using landuse are detected. If I switch to globe view, only labels appear to be detected

https://user-images.githubusercontent.com/61150/147159027-3701f801-6c9a-461e-804a-e711f60df125.mov

---

**Mapbox GL JS version:** `2.7.0-alpha.1`

**Comment by cguastini** [comment]
Was going to open a separate issue but noticed this one already existed. Here's a simple snippet I made to create a polygon and test `queryRenderedFeatures` with the globe projection. Nothing logs in the globe projection but does if I use Mercator.

```js
const map = new mapboxgl.Map({
    container: 'map',
    projection: {
        name:'globe',
    },
    style:'mapbox://styles/mapbox/dark-v10',
    zoom:2,
    center:[-100, 25],
});

map.on('load', function() {
    map.addSource('test', {
    type: 'geojson',
    data: {
        'type': 'FeatureCollection',
        'features': [
        {
        'type': 'Feature',
        'geometry': {
        'type': 'Polygon',
        'coordinates': [
        [
        [-120, 45],
        [-70, 45],
        [-70, 30],
        [-120, 30],
        [-120, 45]
        ]
        ]
        },
        'properties': {
            'prop-1':'prop-value'
        }
        }
    ]
    }
    })
    
    map.addLayer({
    'id': 'test-poly',
    'type': 'fill',
    'source': 'test',
    'paint': {
    'fill-color': 'red',
    'fill-opacity': 0.5
    }
    });

    map.on('mousemove', 'test-poly', (e) => {
        const features = map.queryRenderedFeatures(e.point, {
            layers:['test-poly']
        });
        console.log(features);
    })

})
```
<img width="939" alt="Screen Shot 2022-03-08 at 4 17 02 PM" src="https://user-images.githubusercontent.com/45727303/157326732-a0a24c1e-be21-4296-ae80-8cd9e1e6333f.png">

**Comment by karimnaaji** [comment]
Should be fixed by https://github.com/mapbox/mapbox-gl-js/pull/11663, but feel free to reopen if there are any issues.
