### ISSUE TITLE
Inconsistent sprite cropping

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1136]
Sometimes it looks like the sprite.json simply supplied the wrong pixel coordinates when sprites contain slivers of an adjacent sprite, but it only happens on certain instances, and not others:

![screen shot 2015-03-30 at 4 47 26 pm](https://cloud.githubusercontent.com/assets/4551508/6909591/8a3c8e0a-d6fc-11e4-9ff8-c30be2d15e10.png)

![screen shot 2015-03-30 at 4 41 00 pm](https://cloud.githubusercontent.com/assets/4551508/6909594/907901cc-d6fc-11e4-9b15-e3f24c4bc2c0.png)

![screen shot 2015-03-30 at 4 43 26 pm](https://cloud.githubusercontent.com/assets/4551508/6909599/968b8580-d6fc-11e4-8ec0-79237f911192.png)

cc/ @ansis

**Comment by ansis** [comment]
I think this is the same bug as https://github.com/mapbox/mapbox-gl-js/issues/1067
