### ISSUE TITLE
Custom layer data not displaying at set zoom level

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11368]
In this example, I've set a custom layer to display at z4 which works fine for mercator. As soon as the projection changes to globe it displays at a higher float

https://user-images.githubusercontent.com/61150/147768695-cee4c9d8-bad1-4c79-b7ce-157d2e9bd873.mov

---

**Mapbox GL JS version:** `2.7.0-alpha.1`

**Comment by karimnaaji** [comment]
@SnailBones I just chatted with @mpulkki-mapbox about this issue. If you find that this one is a duplicate or directly related to either https://github.com/mapbox/mapbox-gl-js/issues/11789 or https://github.com/mapbox/mapbox-gl-js/issues/11811, we should close it to prevent overlapping work.

**Comment by SnailBones** [comment]
@tristen `2.7.0-alpha.1` predates circle layer support, so circles appear after the transition to Mercator is complete at zoom level 6.

Testing this out with 6c36428ba621c8113494076bb2c49415b9fa43a1 (which became the v2.7.0 release), we see the same behavior:

https://user-images.githubusercontent.com/14878684/166831096-675fda56-54b7-4ed1-ae75-dc3fd3a5471d.mov

Circle layer support was added in #11437. Testing on the latest `main`, Here's a circle layer with `minzoom: 4`

https://user-images.githubusercontent.com/14878684/166832751-a09f8239-91a2-4e79-a648-d76caca33053.mov

So I think that we can consider this resolved. Feel free to reopen if I'm missing something @tristen!
