### ISSUE TITLE
Ability to reposition a circle layer after it has already been created?

### ISSUE THREAD

**Issue by johnnyashdev** [mapbox/mapbox-gl-js#11361]
I am creating a map of points around a specific resort. On init a circle is created around the resort. When the user clicks a marker I want to re-position the already existing radius around the clicked marker using the marker coordinates. Is this possible, or do I need to create a different radius for every marker (on marker click, remove on close)? I was hoping to use setLayoutProperty for the radius and change the position but it seems that visibility is the only property for that function.

Thank you

**Comment by stepankuzmin** [comment]
Hi @johnnyashdev,

I'm not sure if I get that right, but I think that you can use a [dynamic GeoJSON layer](https://docs.mapbox.com/mapbox-gl-js/api/sources/#geojsonsource#setdata) for the "radius" layer.

Consider example

```js
map.on('load', () => {
    // initial radius circle
    map.addSource('radius', {
        'type': 'geojson',
        'data': {
            'type': 'FeatureCollection',
            'features': [
                {
                    'type': 'Feature',
                    'geometry': {
                        'type': 'Point',
                        'coordinates': [-122.414, 37.776]
                    }
                }
            ]
        }
    });

    map.addLayer({
        'id': 'radius',
        'type': 'circle',
        'source': 'radius',
        'paint': {
          'circle-radius': 25,
          'circle-opacity': 0.5,
          'circle-color': '#000'
        }
    });
});

map.on('click', (e) => {
  // new radius circle
  const newData = {
      'type': 'FeatureCollection',
      'features': [
          {
              'type': 'Feature',
              'geometry': {
                  'type': 'Point',
                  'coordinates': [e.lngLat.lng, e.lngLat.lat]
              }
          }
      ]
  };

  map.getSource('radius').setData(newData);
});
```
