### ISSUE TITLE
Option to serve style sprite JSON and PNG from different URLs

### ISSUE THREAD

**Issue by nhoizey** [mapbox/mapbox-gl-js#11379]
## Motivation

I would like to leverage the image CDNs I'm using on sites also for the PNG sprite of maps, to enhance performance.

These image CDNs (Cloudinary, Cloudimage, TwicPics, etc.) allow providing one single image source (here it would be `sprite.png` or `sprite@2x.png`) and serve an enhanced version to users, more compressed and in a format depending on the best the browser supports (WebP or AVIF nowadays, JPEG XL soon).

Fictitious example, because these solution have different ways to build the target URL:
- JSON would be served at `https://example.com/sprite.json` or `https://example.com/sprite@2x.json`
- PNG would be served at `https://imagecdn.com/bestformat/?src=https://example.com/sprite.png` or `https://imagecdn.com/bestformat/?src=https://example.com/sprite@2px.png`

So instead of this in my mapbox style JSON file:

```json
{
  …
  "sprite": "https://example.com/sprite",
  …
}
```

I would like to be able to write this:

```json
{
  …
  "sprite": {
    "json": "https://example.com/sprite",
    "image": "https://imagecdn.com/bestformat/?src=https://example.com/sprite"
  }
  …
}
```

## Design Alternatives

I couldn't think of any other alternative.

## Design

It won't change anything visually.

### Mock-Up

It won't change anything visually.

### Concepts

The main concept would be to be able to serve sprite image and JSON from different URL or path, for any reason, including performance.

### Implementation

The style format should still support current single string `sprite` option, but allow the new object version with 2 string options `json` and `image`.

**Comment by ansis** [comment]
While I don't think we'll be able to implement this proposal, there is a pretty easy workaround for this!

Using the [`transformRequest`](https://docs.mapbox.com/mapbox-gl-js/api/map/) map option you can provide a [function](https://docs.mapbox.com/mapbox-gl-js/api/properties/#requestparameters) that can transform the url of any request before it is fetched. You can use this to replace the sprite image url with a different url.

**Comment by nhoizey** [comment]
@ansis this is a great workaround, I didn't know it existed, thanks a lot!
