### ISSUE TITLE
perspective view 

### ISSUE THREAD

**Issue by bFlood** [mapbox/mapbox-gl-js#1137]
Are there any plans to control the perspective itself, in addition to the tilt angle? or will we need to alter the perspective code in key locations to control this manually? (ex: sdf.vertex.glsl#L65)

I'm experimenting with using mapbox-gl as an overlay for google maps in a mobile app, for the most part it working really well, congrats on the amazing api! I know this is not a high priority issue but full control over the perspective might be valuable for other apps as well

here's a quick video that shows the misalignment as the features get further from the camera position (shown around the 20s mark) http://bit.ly/1DnrRz5

thanks

**Comment by ansis** [comment]
`map.transform.altitude` can be used to control the perspectiveness. We should add a public api for setting it. `map.transform.altitude = 1.5` sets the camera one and a half map heights above ground level. So, if the map is 600px tall then the camera would be set 900px above ground level.

**Comment by bFlood** [comment]
thanks ansis, that worked perfectly. fwiw, it looks like 1.85 matches pretty well with the gmaps implementation

thanks again!
