### ISSUE TITLE
Globe View: Pole fill at zoom 0

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#11385]
We do not fill pole at zoom 0, only at zoom 1 and above. This leads to empty holes at the poles for that zoom:

![147431029-8374fdf1-2ede-4214-8cdd-e3f565e5b099](https://user-images.githubusercontent.com/7061573/148835099-263dde98-a1c3-4918-b639-190a516a3568.png)

Reported by @HexCodeFFF in https://github.com/mapbox/mapbox-gl-js/pull/11329#issuecomment-1001313113.

**version v2.7.0-alpha.1**

**Comment by HexCodeFFF** [comment]
This is known by the team working on the PR
