### ISSUE TITLE
Some angles of vector layer cannot be selected on terrain map

### ISSUE THREAD

**Issue by cyyyyyyyyy** [mapbox/mapbox-gl-js#11388]
**mapbox-gl-js version**: v2.6.0

**browser**: chrome

### Steps to Trigger Behavior

 1. set terrain layer
 2. add point vector layer
 3. adjust map view
 4. select vector layer point

**Comment by cyyyyyyyyy** [comment]
![image](https://user-images.githubusercontent.com/18070879/148932923-bda30be2-3ceb-4118-9997-97a08abd5373.png)

The mouse cannot select a point at a partial position

**Comment by ryanhamley** [comment]
@cyyyyyyyyy Can you please include a working, minimal example of the issue using a site like JSFiddle or CodePen? We can't diagnose what's happening without a reproduction of the bug.

**Comment by mourner** [comment]
Closing as there's no minimal test case provided, so we can't diagnose the issue in GL JS.
