### ISSUE TITLE
labels visible for too long behind globe

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#11386]
When you quickly rotate a globe, labels that go behind the globe linger for too long. This makes the labelling look a bit messy.

**mapbox-gl-js version**: globe-view

**browser**: all

### Steps to Trigger Behavior

 1. open any debug page with globe view and zoom out
 2. pan quickly
 3. observe labels being visible on other side of the world as they fade out

### Expected Behavior

Labels disappear quickly when they go behind the globe.

### Actual Behavior

https://user-images.githubusercontent.com/1421652/148857904-c7d22296-f99c-4e23-ad3b-c20b1b9e8579.mov

---

Depending on how the fix is implemented, this could be related to https://github.com/mapbox/mapbox-gl-js/issues/11380

@karimnaaji

**Comment by karimnaaji** [comment]
I'll give a look at this issue at the same time as #11380.
