### ISSUE TITLE
Symbols visible through globe with text-allow-overlap true

### ISSUE THREAD

**Issue by cguastini** [mapbox/mapbox-gl-js#11380]
**mapbox-gl-js version**: `2.7.0-alpha.1`

### Steps to Trigger Behavior

 1. Set map projection to globe
 2. Add layer with style 
 ```js 
  map.addLayer({
        'id': 'aircraft',
        'type': 'symbol',
        'source': 'aircraft',
        'layout': {
        'text-size': 8,
        'text-field': '✈',
        'text-rotate': [
          "to-number",
          ["get", "trueTrack"]
        ],
        'text-allow-overlap': true
        },
        'paint': {
        'text-color': 'white',
        'text-opacity': 0.5
        }
    });
```
 3. See symbols through earth
![airplane-globe](https://user-images.githubusercontent.com/45727303/148595238-ff4e6338-535a-4c35-9782-774a27ba21eb.gif)

### Expected Behavior
Symbols on the other side of the earth should not be visible even when `text-allow-overlap` is set to `true`. Or there should be a parameter to hide them when a transparent globe is not desired.
### Actual Behavior
Symbols on the other side of the earth are visible.

**Comment by karimnaaji** [comment]
We should be able to resolve that at the same time as https://github.com/mapbox/mapbox-gl-js/issues/11351, as it's related to symbol occlusion for tiles that are backfacing.

**Comment by karimnaaji** [comment]
@cguastini Do you have the full example available for this issue?

**Comment by cguastini** [comment]
@karimnaaji Here's an Observable notebook that renders the airplane data on the globe (it'll take a couple seconds to load) https://observablehq.com/d/ee5e6828bde9a2b4?ui=classic
