### ISSUE TITLE
Redundant globe matrix calculations

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#11392]
Currently `calculateGlobeMatrix` takes a noticeable portion of the main thread, in addition to all the matrix allocations that need to be GCd later:

<img width="285" alt="image" src="https://user-images.githubusercontent.com/25395/149185770-09d15556-17a0-4388-9401-9dbcd94f4d09.png">

This matrix needs to be calculated once on transform change and cached, similarly to how it happens for other matrices in `Transform` `_calcMatrices`. cc @karimnaaji

**Comment by karimnaaji** [comment]
Yes that's a good CPU optimization opportunity, there are no mechanisms for doing so in `globe_tile_transform` at the moment.

**Comment by karimnaaji** [comment]
When getting to addressing this issue, we should also address this comment https://github.com/mapbox/mapbox-gl-js/pull/11395#discussion_r785141552.
