### ISSUE TITLE
Container with CSS transform scale behavior changed with > 2.5.0

### ISSUE THREAD

**Issue by pomm0** [mapbox/mapbox-gl-js#11394]
**mapbox-gl-js version**: 2.6.1

**browser**: Chrome Version 97.0.4692.71 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Open provided link 1
 2. Add a valid access token
 3. Notice, that the container would be much larger than the map is rendered
 4. Open provided link 2
 5. Add a valid access token
 6. Compare both versions and see the differences

### Link to Demonstration

1. jsfiddle with mapbox version 2.6.1: https://jsfiddle.net/rqpwtm8j/2/
2. jsfiddle with mapbox version 2.4.1: https://jsfiddle.net/rqpwtm8j/3/

### Expected Behavior
Same as in version 2.4.1 (full-size map according to its container) as I couldn't find any related notice in the changelog about that.

### Actual Behavior
Map too small.

### Notices
This is related to the `transform: scale(0.5)` of the parent container.

#### Screenshot with 2.4.1
![image](https://user-images.githubusercontent.com/6084030/149286033-d0394d8f-9567-4ce8-a16d-31e5c8b14bea.png)

#### Screenshot with 2.6.1
![image](https://user-images.githubusercontent.com/6084030/149286356-32502846-f1ac-440e-a6c3-d2457de05d61.png)

**Comment by SnailBones** [comment]
This issue is the same as  #11085, which has been fixed by #11310.
