### ISSUE TITLE
`map.loaded()` may return `true` too early when used with Globe View

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#11419]
`map.loaded` may return `true` incorrectly when used with Globe View projection, where the actual rendered frame isn't representative of the globe projection. The map usually need to be a few more frames further in its lifecycle to be rendered it as a sphere.

**mapbox-gl-js version**: v2.7.0-alpha.2

**browser**: all

### Steps to Trigger Behavior

 1. Set globe view projection on a map constructor
 2. At every frame in `map.once('render')`, check the status of `map.loaded()`

### Expected Behavior

`map.loaded` should only return true when the visual representation of the map is a globe when used with a Globe View projection adopting WYSIWYG.

### Actual Behavior

`map.loaded` returns `true` too early, this can be an issue in render test when updating render tests baselines as we rely on that before performing new baseline writes.

**Comment by avpeery** [comment]
This issue may be related to maps not being rendered when creating render tests in globe view on Mac devices (M1 and MacOS > Monterey 12.3)

**Comment by SnailBones** [comment]
I'm hitting this after updating to Montery 12.4. Globe render tests create fully transparent images with `yarn test-render` but work as expected with `yarn watch-render`.

**Comment by SnailBones** [comment]
This is also breaking automated image generation for docs. Images created show up as fully white:

![image](https://user-images.githubusercontent.com/14878684/174332175-2f3b746d-2d5f-4040-aa69-cfe5c62d8238.png)

Currently the only known workaround is to create the image manually with a screenshot.

**Comment by avpeery** [comment]
In the meantime, current workaround with generating globe render images with macOS is to replace `--use-gl=desktop` with `--use-gl=angle` https://github.com/mapbox/mapbox-gl-js/blob/main/test/integration/testem/testem.js#L121

**Comment by avpeery** [comment]
With satellite, map.loaded() is returning `true` when `render` is fired before all rendering has completed. However, this appears to be the same across all projections with satellite style. This is not an issue with streets.

With mercator projection:

https://user-images.githubusercontent.com/42715836/179830616-4e88ae65-117b-4917-9222-a4270f0569ba.mov
