### ISSUE TITLE
Add "transition options" argument to all style mutation methods

### ISSUE THREAD

**Issue by mofoyoda** [mapbox/mapbox-gl-js#1142]
I'm trying to do a nice fade in/out transition on hovering over features. 
Is it possible to override global transition settings, so that `map.addClass()` uses global transition settings, but `map.removeClass()` acts at full speed (like when duration set to 0)?
Ideally, if transition can somehow be set for each paint class independently, that'll be very handy.

**Comment by jfirebaugh** [comment]
Paint classes are no longer supported, but you should be able to accomplish this via the global `transition` property or individual `*-transition` properties.
