### ISSUE TITLE
Globe View: Heatmap layer support

### ISSUE THREAD

**Issue by mpulkki-mapbox** [mapbox/mapbox-gl-js#11424]

**Comment by akoylasar** [comment]
Heatmap is working as expected with the 2D projections. The goal is to enable this for the globe view (projection) as well.

**Comment by akoylasar** [comment]
Below is a screenshot of the correct rendering of the heatmap when globe view is enabled.
![heatmap-layer-support](https://user-images.githubusercontent.com/67509069/152209705-7dc23fe7-6eb5-456a-a410-9cfc13a65076.png)
