### ISSUE TITLE
How to change look at point angle

### ISSUE THREAD

**Issue by SkylinR** [mapbox/mapbox-gl-js#11422]
**mapbox-gl-js version**: 2.6.1

### Question
How to change look at point (or just camera) angle? I know that I can change pitch but it moves camera by some angle. I want to leave camera where it is but look a little bit up. I saw in docs that `FreeCamera` has only two properties `lookAtPoint` and `setPitchBearing`  but it not helps. The issue is that I want to show entire building on some zoom and I cannot change that zoom because of how mapbox returns default buildings.

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/api/properties/#freecameraoptions
https://docs.mapbox.com/mapbox-gl-js/api/properties/?size=n_10_n#cameraoptions

**Comment by ryanhamley** [comment]
Unfortunately, the map camera cannot look "up". The center of the map is guaranteed to be on the map plane, so it's impossible to set a center that would be over the horizon, such as looking up at a building. What you can do is change the camera's altitude using the `FreeCamera#position` property as in [this example](https://docs.mapbox.com/mapbox-gl-js/example/free-camera-point/).

```
const camera = map.getFreeCameraOptions();
 
camera.position = mapboxgl.MercatorCoordinate.fromLngLat(
    position,
    altitude
);
camera.lookAtPoint(target);
 
map.setFreeCameraOptions(camera);
```

**Comment by SkylinR** [comment]
I know that way but it changes zoom and that's what I cannot do because of 3d buildings which have no IDs on higher zoom than 16.
Ok so I see I need to find other way to deal with my case. Thanks.

**Comment by ryanhamley** [comment]
Yes, sorry, this is just how the library works. Altitude is directly linked with zoom and opening the camera to view points above the horizon would involve a significant amount of work that is largely outside the scope of the library.
