### ISSUE TITLE
How to make an animated marker popup?

### ISSUE THREAD

**Issue by mynameisjohnahahah** [mapbox/mapbox-gl-js#11429]
### Question
How to make an animated marker popup ?

example：https://codepen.io/liuxipeng/pen/bGoPLXW

**Comment by ryanhamley** [comment]
It seems that it's difficult to manually trigger the click event on a moving marker. However, you can programmatically open and close the popup with `marker.togglePopup()` as in [this example](https://codepen.io/rsh412/pen/ZEXgYYd).
