### ISSUE TITLE
atmosphere region approximation may lead to large error and does not match size of globe

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#11444]
The screenspace atmosphere region (approximation of screenspace sphere calculated [here](https://github.com/mapbox/mapbox-gl-js/blob/main/src/render/draw_globe_atmosphere.js#L23_L32)) does not match the exact size of the globe. This leads to incorrectness when rendering the map with a transparent background, or partially transparent layers:

![151247566-3edb04d1-1d19-4667-bd00-d74070c08598](https://user-images.githubusercontent.com/7061573/151427803-479c690d-fe94-425f-a97e-bbc737b868ae.png)

Here is a visualization of fov adjusted globe with a transparent green background, we can notice that the globe exactly matches the circle region of the atmosphere for close to 0-fov only, otherwise we add a small error to the calculated screen space circle region:

https://user-images.githubusercontent.com/7061573/151427842-06cfb7dc-5885-4ef0-9af6-82b0d7a5c811.mp4

We should also investigate whether that empty region should be left transparent, or filled with the background color of the map.

**Comment by mpulkki-mapbox** [comment]
We could try a fairly simple ray-sphere intersection test in the fragment shader which would be more accurate.
