### ISSUE TITLE
setStyle()/style property throws "Cannot read properties of undefined (reading 'expression')" for some style.json files

### ISSUE THREAD

**Issue by MaxGeldner** [mapbox/mapbox-gl-js#11457]
For some map styles an error is thrown, when set via setStyle or the map is initially loaded with the style. Specifically the MapTiler Hybrid style (https://api.maptiler.com/maps/hybrid/style.json?key=<key\>) doesn't work on newer versions of mapbox. The same style json worked fine in mapbox v2.1.1.. Did something in validating/setting the style change, so that some styles, which worked in ealier mapbox v2 versions, now wont work anymore, so that the style files need to be updated? If thats the case and no compatibility for older styles is wanted in mapbox, this issue can be ignored and closed. I will contact maptiler then and hope that they will update their styles :)
Here is the error with some of its stack trace:
<img width="333" alt="style switch error" src="https://user-images.githubusercontent.com/22854757/151999859-2248cbc3-e4d7-404c-a777-9ea5e2540133.PNG">

**mapbox-gl-js version**: 2.6.1 (same Error on 2.7.0 as well)

**browser**: Chrome

### Link to Demonstration

Demo only works with valid maptiler and mapbox keys: https://jsfiddle.net/0pfyhds5/
If changing the mapbox version to 2.1.1, the style works fine.

### Expected Behavior

Style should change.

### Actual Behavior

Error is thrown and no style change is made.

**Comment by ryanhamley** [comment]
This appears to be a regression from https://github.com/mapbox/mapbox-gl-js/pull/10795. That PR introduced a function to disallow certain parameters in filter expressions and it assumes that the options object will have a `valueSpec.expression` property. With the MapTiler style, `valueSpec` is undefined, leading to this problem. If you guard against this, the style loads properly. However, a little more debugging is needed to determine what the actual correct behavior here is.

https://github.com/mapbox/mapbox-gl-js/blob/6ffc4c099597c033752218082cba4c085bb6d1e3/src/style-spec/validate/validate_expression.js#L55-L57
