### ISSUE TITLE
Popup can stay when mouse goes to popup area from hovered point.

### ISSUE THREAD

**Issue by eminciftci** [mapbox/mapbox-gl-js#11491]
Hello, I add popup to map and it appears when the point is hovered. There is a button in popup in my implementation, so if I move the mouse popup area from point, it disappears and I can't click the button. I know I can achieve with close button, but it brings more actions to close popup. What I asked from you, if the point is hovered and after then I move the mouse to the popup it can stay until and I move it somewhere else in map.

Thank you.

**Comment by ryanhamley** [comment]
The precise solution would depend on your implementation and your goals so we can't offer exact advice here. You can see various approaches to using popups in [our examples](https://docs.mapbox.com/mapbox-gl-js/example/?search=popup). It sounds like you are using the `mouseenter` event on a layer and removing the popup on `mouseleave` as in [this example](https://docs.mapbox.com/mapbox-gl-js/example/popup-on-hover/). I think that you can modify this by not removing the popup on `mouseleave` and instead letting the popup close on map click or move instead.
