### ISSUE TITLE
SDFs not correctly scaled on retina

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#1150]
Compare same style 

### non-retina
![screen shot 2015-04-10 at 3 51 10 pm](https://cloud.githubusercontent.com/assets/108094/7095570/85e4de98-df99-11e4-9bb4-19508beb9a21.png)

### Retina
![screen shot 2015-04-10 at 3 50 03 pm](https://cloud.githubusercontent.com/assets/108094/7095571/88224344-df99-11e4-93de-51a13fcf3148.png)

We're using SDF point icons, and the size isn't scaling up with retina.

**Comment by samanpwbb** [comment]
Same problem occurs on mobile as well.

**Comment by ansis** [comment]
It looks like the version in the retina sprite is smaller. It has the same width and height, but a different pixel ratio. I think you might be able to fix this by just removing the `@2x` input image and letting it use the regular one for both sprites.

https://github.com/mapbox/mapbox-gl-styles/blob/ba4a641527109e8c9208f69742175320ae9259ae/sprites/mapbox-streets.json#L1013-L1015

https://github.com/mapbox/mapbox-gl-styles/blob/ba4a641527109e8c9208f69742175320ae9259ae/sprites/mapbox-streets%402x.json#L2181-L2183

**Comment by samanpwbb** [comment]
agh, you're totally right.
