### ISSUE TITLE
Map keeps shaking with percentage sizes

### ISSUE THREAD

**Issue by Jees1** [mapbox/mapbox-gl-js#11507]
Hello, my map seems to shake a lot when I use `width: 100%` (or any percentage)

With px, it works just fine. I want to make the width the whole screen though.

Here's a video of the shaking:

https://user-images.githubusercontent.com/49425409/153725273-faaec144-cee5-45a2-aff0-4af452fadeee.mp4

In the video the width is 90%

This is the part of the HTML: 
```html
<div id="mapContainer" style="width:100%;height:100%; position: relative;">
    <div id="map" style="width: 90%; height: 500px; left: 50%; bottom: 50%; transform: translate(-50%, 50%);">
      <a href="https://www.maptiler.com" style="position:absolute;left:10px;bottom:10px;z-index:999;"><img src="https://api.maptiler.com/resources/logo.svg" alt="MapTiler logo"></a>
    </div>
```

You can see it in action here: https://tankkiapuri.fi/aluev2/kuopio
**The map also doesn't show up for *some* reason, resize your window and it should show up**

Thanks in advance,
Jees

**Comment by mourner** [comment]
According to the video, you're using Leaflet, not Mapbox GL JS.

**Comment by Jees1** [comment]
@mourner The people at Leaflet told me the problem is in Mapbox GL JS. Please check the HTML in the Developer Tools, if possible.

**Comment by mourner** [comment]
@Jees1 I'm confused — the video you shared above clearly shows Leaflet, the page you linked doesn't show the map (even after resizing) because of a JS error, but the code uses Maplibre. You would need to set up a clearly reproducible live use case using GL JS for us to be able to diagnose the issue you're describing.

**Comment by Jees1** [comment]
I updated it to that one, I will revert the changes for you.

**Comment by Jees1** [comment]
@mourner Reverted

**Comment by Jees1** [comment]
@mourner Reverted to GL JS. Check the head of the HTML: https://tankkiapuri.fi/aluev2/kuopio
