### ISSUE TITLE
Icons of symbol layer not showing on mobile device(ios or android)

### ISSUE THREAD

**Issue by aviabunin** [mapbox/mapbox-gl-js#11518]
Dear Gurus!
      My symbol layer is displayed normally on desktop in any browser. However, when I connect to the site from mobile device (ios or android), the symbols are not displayed. If I change the type of layer from "symbol" to  "circle", then everything is fine. 
    Markers (created with mapboxgl.Marker ) works normally.
    Other types of layers (polygon and line) are displayed normally.
    How to solve the issue or where would be the best place to ask a question?

   The code is:

  `window.mymap.addLayer({`
                'id': 'Id1',
                'source': 'source1',
                'type': 'symbol',
                'layout': {
                    'icon-image': 'FireIcon',
                    'icon-size': 0.08,
                    'icon-offset': [0, 0],
                    'icon-allow-overlap': true,
                },
            });
`

**Comment by ryanhamley** [comment]
Hi @aviabunin it's impossible to say without an example of the issue, but I suspect based on what you've described that your sprite sheet or icons may be too large and you're running into issues of WebGL texture size or memory in mobile browsers. You could try to reduce the size of your icons to see if that resolves the issue. I suspect this isn't a bug in GL JS so if you need further help, I'd suggest contacting [Mapbox Support](https://support.mapbox.com/hc/en-us).
