### ISSUE TITLE
Default colour for values null/undefined  with setPaintProperty ?

### ISSUE THREAD

**Issue by erkanisuf** [mapbox/mapbox-gl-js#11527]
Hello i am displaying polygones/zones that are colored depending on the given value range. But some of these zones got values of null ,0 or undefined or the "key" property itself is missing in the data,  so the mapboxgl automatically sets default color for them "black" .  I am setting the colors this way:

`map.setPaintProperty("demographicOverview", "fill-color", [
					"interpolate",
					["linear"],
					["get", key],
					range[0], colors[0],
					range[1], colors[1],
					range[2], colors[2],
				]);`

Is there anyway to change the default "black" color to something else or can the opacity be reduced somehow for these zones with nullish values?

**Comment by erkanisuf** [comment]
Actually i managed to do it. Did it this way:
This solution worked for me :

//This will put color of white for the missing property 
```
map.setPaintProperty(
                    'layerName',
                    'fill-color',
                    ["case", ["==", ["get", key], null], "#ffffff", [
                        "interpolate",
                        ["linear"],
                        ["get", key],
                        range[0], colors[0],
                        range[1], colors[1],
                        range[2], colors[2],
                    ]]
                );
```
This works also for opacity:

```
map.setPaintProperty(
            'layerName',
            'fill-opacity',
            ["case", ["==", ["get", key], null], 0.1, 0.7]
        );
```

**Comment by ryanhamley** [comment]
@erkanisuf Using `case` as you've done would be the recommended way to do this.
