### ISSUE TITLE
Popup does not clean up event listeners if closeOnClick: true

### ISSUE THREAD

**Issue by Pessimistress** [mapbox/mapbox-gl-js#11535]
**mapbox-gl-js version**: 2.7.0

**browser**: any

### Steps to Trigger Behavior

 1. Create popup with `closeOnClick: true`
 2. Add listener to the popup's `close` event
 3. After the popup is closed, the `close` event continue to fire upon any click on the map

### Link to Demonstration

https://codepen.io/Pessimistress/pen/qBPmbrV

 1. Click on "open popup"
 2. Click anywhere on the map
 3. Repeat 1 & 2 a few times, observe console logs
 
### Expected Behavior

The `close` callback should be called once for each popup

### Actual Behavior

All `close` callbacks ever registered continue to be called when the map is clicked.

I believe this was introduced by https://github.com/mapbox/mapbox-gl-js/commit/9c1e1a0364bc5f94f225f6d6246104422b6894e3, as a `preclick` listener is added to the map: 

https://github.com/mapbox/mapbox-gl-js/blob/6828333478f5f7eb55cf9674856a625fe31c7121/src/ui/popup.js#L143

But on `popup.remove` it attempts to remove a `click` listener:

https://github.com/mapbox/mapbox-gl-js/blob/6828333478f5f7eb55cf9674856a625fe31c7121/src/ui/popup.js#L219

This bug cannot be reproduced on versions <2.5.0, when this commit was included.

**Comment by ryanhamley** [comment]
Thanks for the report @Pessimistress I submitted #11540 to fix this
