### ISSUE TITLE
["in", "", <empty string>] returns false

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#11543]
**mapbox-gl-js version**:
1.13.2

### Steps to Trigger Behavior

(Note, I'm leaving out the necessity for `['literal', ...]` in a couple of places for clarity.)

 1. Create a layer with a filter, `['in', ['literal', ''], '']`

### Expected Behavior

IMHO this should evaluate to true, considering that `[in, '', 'bananas']` evaluates is true (ie, empty string is found within anything else)

### Actual Behavior

Evaluates to false. 

This actually caused a problem for me when I had a filter that was a `['in', ['get', 'prop1'], ['get', 'prop2]'`]` and both values were empty.

**Comment by ryanhamley** [comment]
This makes sense. `''.indexOf('') >= 0` is true, but the expression returns false. I submitted a PR to address this.
