### ISSUE TITLE
`map.setStyle` may result in error when used with `globe` projection

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#11553]
From @stevage in https://github.com/mapbox/mapbox-gl-js/issues/10784#issuecomment-1050370220:

>After setting the globe projection, when I add a GeoJSON source, I weirdly get:
>
>>Error: terrain: terrain is missing required property "source"
>
>Adding terrain (with a source) made the error go away.

version 2.8.0-alpha.1

**Comment by avpeery** [comment]
@stevage Thanks so much for reporting this issue in #10784! I haven't been able to reproduce the error yet (though I suspect it's coming from [this conditional](https://github.com/mapbox/mapbox-gl-js/blob/main/src/style-spec/validate/validate_terrain.js#L47)). Are you setting globe view in the map parameters, and using addSource to add a geoJSON source once map is loaded?

**Comment by stevage** [comment]
>Are you setting globe view in the map parameters

Yes, is there a different way?

> and using addSource to add a geoJSON source once map is loaded?

Yes.

**Comment by stevage** [comment]
Interesting, I can't reproduce it now either, with the same codebase. I don't know what I would have changed that made a difference, but something, apparently.

**Comment by stevage** [comment]
Hmm, it's intermittently reproducible. Great.

http://mapswell.site44.com/geohash-map/#globe-bug&center=4.39/-45.63/143.89

![image](https://user-images.githubusercontent.com/678344/156509119-18cf4780-22b9-43a1-be5a-17012d3a4023.png)

**Comment by stevage** [comment]
Ah, I'm guessing it has something to do with the maybe strange way I manipulate the map style to add styles and layers, using [map-gl-utils](https://github.com/stevage/map-gl-utils), which calls `map.setStyle()` rather than `map.addSource()`.

**Comment by avpeery** [comment]
@stevage Ah so this error might be specific to your set-up. Just to be sure, (if you're still experiencing this error), can you provide a minimal code reproduction of this issue in jsbin or codepen? Thanks!

**Comment by karimnaaji** [comment]
I'll close this issue as stale as we have no repro and haven't seen this issue since then, but feel free to reopen if this issue is still visible in the latest beta we published!

**Comment by avpeery** [comment]
I was able to consistently reproduce the error mentioned in this issue. Click map to toggle between a mercator map with dark style and globe view set in a style. After third click, I receive the same error `terrain is missing required property "source"`. 
https://codepen.io/avpeery/pen/JjpJjQW

**Comment by karimnaaji** [comment]
@avpeery I'm reopening this issue as I've been able to reproduce this issue from latest `main` with the following:
- Navigate to http://localhost:9966/debug#2.52/26.79/-101.03
- Run `map.setProjection('globe')`
- Run `map.setStyle(map.getStyle())`

```
evented.js:150 Error: terrain: terrain is missing required property "source"
    at Object.emitValidationErrors (validate_style.js:13)
    at emitValidationErrors (style.js:57)
    at Style.setState (style.js:647)
    at Map._updateDiff (map.js:1888)
    at Map._diffStyle (map.js:1882)
    at Map.setStyle (map.js:1823)
    at <anonymous>:1:5
```

**Comment by karimnaaji** [comment]
Another test case that could be used as a way to prevent regressions on the potential fix when we address that:

- Start with a map in mercator
- `map.setStyle(Object.assign({}, map.getStyle(), {projection: {name: 'globe'}}))` -> no error
- `map.setStyle(Object.assign({}, map.getStyle(), {projection: {name: 'globe'}}))` -> error `Error: terrain: terrain is missing required property "source"`
