### ISSUE TITLE
removeImage on an animated image throws Uncaught TypeError: Cannot destructure property 'userImage' of 'e' as it is undefined

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#11558]
**mapbox-gl-js version**: 2.7.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. Follow the example at https://docs.mapbox.com/mapbox-gl-js/example/add-image-animated/ to add an animated image to the map
 2. use `map.removeImage`

### Link to Demonstration

https://codepen.io/andrewharvey/pen/BamGabP

### Expected Behavior

no error, the image just gets removed.

### Actual Behavior

an error is logged in the console
```
Uncaught TypeError: Cannot destructure property 'userImage' of 'e' as it is undefined.
    at _ (style_image.js:34:12)
    at dispatchRenderCallbacks (image_manager.js:298:29)
    at jc.patchUpdatedImages (image_atlas.js:125:22)
    at ad.prepare (tile.js:384:29)
    at qp.prepare (source_cache.js:168:18)
    at _o.render (painter.js:484:29)
    at Map._render (map.js:2944:26)
    at map.js:3270:26
````

**Comment by Kacri** [comment]
Excuse me, can you advise me on angular and mapbox, I'm doing a project.

**Comment by stepankuzmin** [comment]
Hi @Kacri

Thank you for using mapbox-gl-js. For advises like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
