### ISSUE TITLE
Raster type layer performance degradation in 2.x version

### ISSUE THREAD

**Issue by sienki-jenki** [mapbox/mapbox-gl-js#11559]
Hi, my application (using mapbox-gl-js 1.13) is using `.updateImage()` on `raster` layer very intensively and it's very performant, no FPS drops whatsoever. When I updated mapbox to newest version (2.7), image replacement performance degraded significantly. I dig deeper into it, since I couldn't find any connected issue. I found this PR https://github.com/mapbox/mapbox-gl-js/pull/10698 which seems to be case of performance degradation, especially this [LINE](https://github.com/mapbox/mapbox-gl-js/pull/10698/files#diff-b63f77e3bf15bd4e0a3d7571f1fa312744d249d3b8cb8591c4d789671951ef05L120-R121)

During tests I was using **Google Chrome**.

Specs:

- OS: macOS Monterey 12.2.1
- Google Chrome: Version 98.0.4758.102 (Official Build) (x86_64)

### How I tested it:
- In mapbox-gl-js repository I've set debugging page using `yarn run start-debug`
- Modified [THIS](https://docs.mapbox.com/mapbox-gl-js/example/animate-images/) mapbox example
- Instead of 5 weather images I was using 20 images from `https://picsum.photos/id/${currentImage}/1000/1000` in a **10ms** interval (1000x1000 px)
- Used chrome dev tools performance to check FPS drops.

### Mapbox-gl 2.7
with edited  line in `src/source/image_source.js` as in previous (Mapbox-gl 1.13 version):

`line 146` `this.image = image;`

<img width="1414" alt="Mouse_Highlight_Overlay" src="https://user-images.githubusercontent.com/34219675/156234434-67a093d5-8749-4f53-b0fd-2a999039895f.png">

with current (Mapbox-gl 2.7) implementation in `src/source/image_source.js`:

`line 146` `this.image = browser.getImageData(image);`

<img width="1211" alt="Mouse_Highlight_Overlay" src="https://user-images.githubusercontent.com/34219675/156235051-01279a83-9d84-4537-b453-12dca4ffd4da.png">

Performance degradation is also visible during less CPU intensive operations (instead of 10ms interval, use 50ms), it's still not 60fps smooth.

I understand it fixes race condition issue but in the same time it prevents us from upgrading to the latest mapbox version as this is one of our core features. Any idea on how we can have both?

**Comment by ryanhamley** [comment]
Hey @sienki-jenki thanks for this report. I have a potential fix for this issue in #11564. I'm not seeing quite such a large difference in performance between versions, even though I have the same OS and a newer version of Chrome (99). I know you laid out the steps you took to reproduce the issue, but it would be helpful if you could supply a JSBin/JSFiddle/CodePen with the page you've been testing. Alternatively, if you want to try out the patch in #11564 and see if it improves your performance, that would be helpful.

**Comment by sienki-jenki** [comment]
Hey @ryanhamley , thanks for reply, I will test it and provide you with some demo, most likely tomorrow. 🙏

**Comment by sienki-jenki** [comment]
Hey @ryanhamley , thanks for handling this performance issue, now it seems that image replacement is even faster comparing to 1.13. 🥇 
![Mapbox_GL_JS_debug_page](https://user-images.githubusercontent.com/34219675/156933133-7b9c99c9-2a11-4db9-8112-605994d738d3.png)

This is the code that I've been testing with: `debug/index.html` https://gist.github.com/sienki-jenki/3daac6368576d7b25961b8e82ac0ee65 (not sure if codePen wouldn't affect performance somehow, so supplying you with exact same way how I was testing it)

**Comment by karimnaaji** [comment]
Thanks for the helpful feedback @sienki-jenki . Closing, this fix will be pending next release.
