### ISSUE TITLE
Investigate performance bottlenecks when globe view is enabled

### ISSUE THREAD

**Issue by akoylasar** [mapbox/mapbox-gl-js#11557]
The goal is to identify bottlenecks that would help us improve the overall performance when globe view is enabled. This may include reducing memory usage, using caching to reduce unnecessary computation and simplifying code in general to optimize CPU usage. 

There are a few existing proposals:
*  Investigate whether all globe tiles could be rendered using a shared grid mesh as we're doing with the terrain (as mentioned [here](https://github.com/mapbox/gl-js-team/issues/367)).
* [Reduce mesh density of globe tiles](https://github.com/mapbox/mapbox-gl-native-internal/issues/2348).
* [Investigate opportunities to optimize globe tile mesh creation](https://github.com/mapbox/gl-js-team/issues/379).
* Globe mesh creation might take significant time.

**Comment by akoylasar** [comment]
After some profiling it turns out that optimizing the globe mesh routines could be a good starting point to increase performance. The screenshot below shows a frame where the tiles (and consequently the globe tile meshes) are created. As indicated the `createGridVertices` takes up a good percentage of the frame.
![performance0](https://user-images.githubusercontent.com/67509069/156341153-c8f0bad1-ccb8-4edb-98de-f21daf998538.png)

**Comment by akoylasar** [comment]
There are two main approaches that can be more performant than the current implementation.

### First approach (shared vertex buffer)
In this approach a simple grid (of positions only) will represent the vertex buffer. This is a gird on XY-plane. All tiles will use this same grid and as a consequence will no longer invoke `createGridVertices`. Instead a few additional uniforms (tile bounds) are passed to the shader with which we'll be to compute the final position of the vertices for each patch.
#### Pros:
* One shared vertex buffer for all tiles will be used at all times
* No more calls to `createGridVertices` per tile
* Simple to implement
#### Cons:
* Increased shader instruction count

### Second approach (longitudinal strips):
Here we create patches for `longitude = 0` for the current zoom level. For any arbitrary tile  at that zoom level all we need to do then would be to rotate the patch to correctly position it. In this approach we will still call `createGridVertices` but far fewer than the current implementation. We can also choose to use lazy initialization for populating the patches. Note however, that with each integral zoom level change the cache will be invalidated.
#### Pros:
* Fewer calls to `createGridVertices` per tile
* No shader changes
#### Cons:
* Cache invalidation is required on each zoom level change
* Harder to implement

One last thing to note is that both implementations above use a fixed number of vertices per tile patch. As latitude increases tiles closer to poles can actually have fewer vertices while the visual fidelity can still remain the same. With the first approach it's possible to create an LOD of grids. We can then use the latitude of a tile to select the LOD that's suitable for that tile.
The second approach could already incorporate this into the the "strip creation" logic.
Note however that currently a shared index buffer is used and these additional steps will necessarily make the shared index buffer obsolete. This is particularly true in second approach.

**Comment by mpulkki-mapbox** [comment]
Nice write up @akoylasar!

The second approach you mentioned was used at some point during the prototype development but I believe it's not the case anymore. Re-introducing would be a nice step forward but I would investigate whether the former approach is feasible.
