### ISSUE TITLE
Don't append .json to sprite URLs

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1155]
Our current sprite interface doesn't require a .json extension, like the rest of Mapbox's REST APIs. We'll either need to make it diverge from the REST custom, or gl-js shouldn't automatically append .json when it looks for sprite metadata json

**Comment by bhousel** [comment]
from #1927 
>This would be a breaking change for any homesteaders that have set up their own sprite server that doesn't support an unsuffixed sprite URL, which we've never documented as a requirement. I think we should WONTFIX #1155, and instead wait for mapbox/mapbox-gl-style-spec#220 to make breaking changes to how sprites are loaded.
