### ISSUE TITLE
Clusters move to the corner of the map with each render

### ISSUE THREAD

**Issue by Bjmn7** [mapbox/mapbox-gl-js#11562]
**mapbox-gl-js version:** 2.7.0
**browser:**  Chrome

### Steps to Trigger Behavior

 1. Zoom In/ Zoom Out / Move on the map

### Demonstration

![Animation](https://user-images.githubusercontent.com/89902485/156530284-6eb85c19-f6bf-43b3-95da-ed421690a82b.gif)

### Expected Behavior
Clusters do not move with each render
### Actual Behavior
Clusters move to the corner of the map with each render

### More information
Hello, it seems that the CSS transform: translate property of the markers is disabled at each render. By unchecking the property in the css I get the same result, the cluster is in the corner of the map. I followed the Display HTML clusters tutorial : https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/
Thank you in advance for taking the time to respond.

### Code
`const map = useRef() as MutableRefObject<Map>`

```
 map.current && map.current.on('render', () => {
    updateMarkers()
  });
  
 function updateMarkers() {
    const features = map.current.querySourceFeatures(lay.name.sourceName)   
    map.current.getSource(lay.name.sourceName) && clusterConstruction.clusterConstructor(features, map.current)
  }
```
```
const markers: any = {};
let markersOnScreen: any = {};

function clusterConstructor(features: any, map: Map) {
  const newMarkers: any = {};  

  for (const feature of features) {
    const coords = feature.geometry.coordinates;
    const props = feature.properties;

    if (!props.cluster) continue;
    const id: number = props.cluster_id;

    let marker = markers[id];
    if (marker) {
      marker.remove()
    }
    const el = createDonutChart(props);
    marker = markers[id] = new mapboxgl.Marker({ element: el }).setLngLat(coords);
    marker.addTo(map);
    newMarkers[id] = marker;
  }
  for (const id in markersOnScreen) {
    if (!newMarkers[id]) markersOnScreen[id].remove()
  }
  markersOnScreen = newMarkers;
}
```

**Comment by ryanhamley** [comment]
Your implementation isn't quite the same as in the example. I'm guessing that there's a change in your code that is unintentionally causing this. If you can make a simple reproduction (without typescript and react) of this with a site like JSFiddle or JSBin, that would help figure out what's wrong. Since the example works, I suspect this isn't a GL JS issue, so I'd recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us) if you need help debugging. If it does turn out to be a GL JS bug, let us know and we'll re-open this.

**Comment by Bjmn7** [comment]
Hi @ryanhamley , thank you for your reply. I'm not sure if I can reproduce this result in a JSBin but I'll try. I've never used this kind of tools. If I can't do it, I'll send a message directly to Mapbox support. I'll keep you posted on the progress of my research very soon.

**Comment by Bjmn7** [comment]
I had modified the mapbox example to address the problem I outlined in this issue : #4491 , perhaps it might help to understand.

**Comment by Bjmn7** [comment]
I solved the problem in the following way. I think you can close the issue permanently @ryanhamley.

```
map.current && map.current.on('render', () => {
    if(!map.current.isZooming() && !map.current.isMoving())
      updateMarkers()
  });
```

```
function clusterConstructor(features: any, map: Map) {
  const newMarkers: any = {};
  for (const feature of features) {
    const coords = feature.geometry.coordinates;
    const props = feature.properties;
    if (!props.cluster) continue;
    const id: number = props.cluster_id;

    let marker: Marker = markers[id];
    if (marker) {
      marker.remove()
    }
    const el = createDonutChart(props);
    marker = markers[id] = new mapboxgl.Marker({ element: el }).setLngLat(coords);
    newMarkers[id] = marker;
  }
  for (const id in markersOnScreen) {
    if (!newMarkers[id])  markersOnScreen[id].remove();
  }

  for (const id in newMarkers){
    newMarkers[id].addTo(map);
  }

  markersOnScreen = newMarkers;
}
```
