### ISSUE TITLE
fix background pattern in perspective view

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1156]
The pattern should be perspectivey

![screen shot 2015-04-14 at 5 55 11 pm](https://cloud.githubusercontent.com/assets/1421652/7150407/7af6514a-e2cf-11e4-9e15-bdf607ddf445.png)

**Comment by ashleyclough** [comment]
How do you get a map into perspective? I can't find anything in the current API - there was some mention previously of a map.transform.altitude setting, but I can't get that to do anything. Any clues?

**Comment by mourner** [comment]
@ashleyclough it's unreleased version, e.g. try `map.setPitch(30)`.

**Comment by lucaswoj** [comment]
@mourner @jfirebaugh What's the status of this issue? Is it resolved now? Or should I make a PR out of a38165f96a021953b6fe1899761ea5a540ef1eb6?

**Comment by lucaswoj** [comment]
This appears to be fixed in `master`

<img width="819" alt="screen shot 2015-11-17 at 2 02 47 pm" src="https://cloud.githubusercontent.com/assets/281306/11226317/fd9850bc-8d33-11e5-8441-1f891e3a5764.png">
