### ISSUE TITLE
Globe view does not respect sky settings

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#11561]
**mapbox-gl-js version**: 2.8.0-alpha.1

Probably old news (or maybe the opposite of [this](https://github.com/mapbox/mapbox-gl-js/pull/11344),   but as far as I can tell, in globe view, nothing you can do in a `sky` layer has any effect.

My use case:

![image](https://user-images.githubusercontent.com/678344/156510226-ce4f1e95-df62-4a22-ac4c-d59bf8bf35e8.png)

I have a dark basemap. I would like a dark background/halo around the globe.

**Comment by karimnaaji** [comment]
Thanks for the feedback @stevage . The atmosphere specification is very much in progress at the moment. We'll be providing controls over that soon and consider unification with sky layer or a deprecation. So far the atmosphere has a single set of control where you can't change the style of it nor disable it. Some considerations/requirements we are considering:
- It should be possible to entirely disable the background to transparent, so the globe can be used a miniglobe in regular mercator maps
- It should be possible to control inner and outer glow 
- It should be possible to add some level of parallax in the background to increase the 3d effect

Here are some previews of these controls in practice from the prototype:

<img width="960" alt="Screen Shot 2022-03-03 at 8 25 53 AM" src="https://user-images.githubusercontent.com/7061573/156607356-d8611469-bd19-4f91-bae9-6243e1989257.png">
<img width="1071" alt="Screen Shot 2022-03-02 at 7 32 39 PM" src="https://user-images.githubusercontent.com/7061573/156607402-fefe0f2d-151e-4a47-bc5b-aa1df8cc5466.png">
<img width="739" alt="Screen Shot 2022-03-02 at 1 40 10 PM" src="https://user-images.githubusercontent.com/7061573/156607454-76f3b031-4cf3-48d2-ae10-99f2fa405906.png">

**Comment by stevage** [comment]
Thanks very much for the update. The ability to use the same settings as the sky is not important to me.

I was also going to suggest supporting a starfield, looks like that's already on the cards.

**Comment by bumbeishvili** [comment]
Dynamic star background (env map) is definitely great

**Comment by karimnaaji** [comment]
>I was also going to suggest supporting a starfield, looks like that's already on the cards.

>Dynamic star background (env map) is definitely great

@bumbeishvili @stevage thanks for the feedback. Prototype of that proposal is available [here](https://124103-8629417-gh.circle-artifacts.com/0/test/release/index.html#page=fog&access_token=pk.eyJ1IjoiY2xhcmV0cmFpbm9yIiwiYSI6ImNqdWJkd2VoMjBjaDEzeXA4ZjZoN2dsZ3UifQ.zt421MySeSY0veX_MZpLnA) where you can play around some of the controls.

**Comment by stevage** [comment]
Thanks - looks like good progress. The stars look a bit odd currently because they're all exactly the same colour and just vary slightly in size. Would expect to see more very faint stars, and hues varying from blueish to reddish.

Also I'm finding that controlling the globe is very unintuitive. I drag it around but it feels a bit random which way the globe moves compared to how I dragged. And I keep ending up in this state where Antarctica is facing the camera and I can't find any way to rotate it back to have the horizon facing the camera. Maybe some sort of gimbal-lock problem.

**Comment by karimnaaji** [comment]
>Also I'm finding that controlling the globe is very unintuitive. I drag it around but it feels a bit random which way the globe moves compared to how I dragged. And I keep ending up in this state where Antarctica is facing the camera and I can't find any way to rotate it back to have the horizon facing the camera. Maybe some sort of gimbal-lock problem.

I think that was fixed by https://github.com/mapbox/mapbox-gl-js/pull/11545, but that branch hasn't been rebased against main quite yet, so you're seeing the old behavior on that link.

**Comment by karimnaaji** [comment]
The new beta (v2.9.0-beta.1) is out with the latest changes. I think there are no more action to take from us here.
