### ISSUE TITLE
Symbols do not rotate with globe-view map when "icon-rotation-alignment" is set to "map"

### ISSUE THREAD

**Issue by avpeery** [mapbox/mapbox-gl-js#11566]
**mapbox-gl-js version**: Current main branch

**browser**: All

### Steps to Trigger Behavior

 1. Add property "icon-rotation-alignment": "map" to a symbol layer (adding this to the marker symbol layer in debug/debug.html works)
 2. Set projection to 'globe'
 3. Rotate globe when zoomed out in globe view
*Also seems like the symbol fade-out/fade-in animation when rotating a symbol out of view in globe view seems to happen a little too late/early.

### Demonstration

https://user-images.githubusercontent.com/42715836/156823597-101a25ca-261d-4e37-b856-56ee1de8040f.mov

### Expected Behavior
Symbol should remain in the same "place" on the map and rotate out of view accordingly when rotating map in globe view

### Actual Behavior
Symbol falls into sky when rotating map in globe view.

**Comment by karimnaaji** [comment]
Somewhat related to marker alignment options as well as https://github.com/mapbox/mapbox-gl-js/issues/11358. cc @SnailBones
