### ISSUE TITLE
Image missing in default outdoors map

### ISSUE THREAD

**Issue by djibarian** [mapbox/mapbox-gl-js#11565]
Using stock unmodified style `mapbox://styles/mapbox/outdoors-v11` throws a `[Warning] Image "rectangle-yellow-5" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.` to the console.

This is not suppose to happen as the default styles should have all their icons available?

**Comment by ryanhamley** [comment]
Is there a particular latitude/longitude/zoom that you see this?

**Comment by djibarian** [comment]
Yes, you can see it for example here:

https://api.mapbox.com/styles/v1/mapbox/outdoors-v11.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#6.16/40.716/-2.158

**Comment by ryanhamley** [comment]
Thanks @djibarian This is a known issue, but fixing it requires some additional work on the backend and we're not sure if/when that will happen. For now, the warning can be safely ignored or users can [add](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addimage) a similar image if needed.
