### ISSUE TITLE
does setFilter allow boolean?

### ISSUE THREAD

**Issue by enersis-pst** [mapbox/mapbox-gl-js#11577]
for me setFilter() works also by using boolean. But this isnt listed in the the documentation.
https://docs.mapbox.com/mapbox-gl-js/api/map/#map#setfilter

**Comment by stepankuzmin** [comment]
Hi @enersis-pst,

Could you please elaborate on what you mean by that `setFilter` also works by using a boolean?

**Comment by enersis-pst** [comment]
@stepankuzmin i mean
is this allowed `setFilter("<layerId>", true)` or `setFilter("<layerId>", false)`?

**Comment by stepankuzmin** [comment]
I don't think that this should work. Setting the filter should be an array that is a [filter specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#filter). Then, you can use either `null` or `undefined` to remove the filter.
