### ISSUE TITLE
Marker popup position is not updated when terrain changes

### ISSUE THREAD

**Issue by astojilj** [mapbox/mapbox-gl-js#11579]
While marker position is updated, popup wouldn't get updated until camera move triggers the update.

https://user-images.githubusercontent.com/549216/157417662-3c460126-758a-4322-bf6f-9513b1f21040.mov

**Comment by anna-visarsoft** [comment]
I get this issue too.

**Comment by SnailBones** [comment]
Related to https://github.com/mapbox/mapbox-gl-js/issues/10982, fixed by https://github.com/mapbox/mapbox-gl-js/pull/10985.

**Comment by Ethan-Guttman** [comment]
Trying to become a contributor to Mapbox and so I picked this good first issue. I just tested this and it looks like it was already fixed as SnailBones said before. Can someone close this issue?

**Comment by stepankuzmin** [comment]
Hi @Ethan-Guttman! Thanks for the ping, closing the issue.
