### ISSUE TITLE
Click position occurs before `icon-offset`

### ISSUE THREAD

**Issue by YeomanYe** [mapbox/mapbox-gl-js#11573]
**mapbox-gl-js version**:
"mapbox-gl": "^2.6.1",

**browser**:
chrome: 99.0.4844.51

### Steps to Trigger Behavior
config layer info below
```js
{
  id: 'sd-way-layer-selectable-arrow-right',
  source: this.id,
  type: 'symbol',
  layout: {
      'symbol-placement': 'line-center',
      // 'symbol-spacing': 80,
      'icon-image': 'arrow-red',
      'icon-size': 0.7,
      'icon-allow-overlap': true,
      'icon-offset': [20, 0],
  },
  paint: {},
  filter: ['all', ['!=', ['get', 'link-intersection'], 'yes'], ['==', ['get', 'direction'], '1']],
  index: 10000,
},
{
  id: 'sd-way-layer-selectable-arrow-left',
  source: this.id,
  type: 'symbol',
  layout: {
      'symbol-placement': 'line-center',
      // 'symbol-spacing': 80,
      'icon-image': 'arrow-red',
      'icon-size': 0.7,
      'icon-allow-overlap': true,
      'icon-offset': [20, 0],
      'icon-rotate': 180,
  },
  paint: {},
  filter: ['all', ['!=', ['get', 'link-intersection'], 'yes'], ['==', ['get', 'direction'], '1']],
  index: 10000,
}
```

<img width="941" alt="image" src="https://user-images.githubusercontent.com/18027354/157042137-e386ce50-1574-4c41-b9fb-cfc3befcf93a.png">

when i click here，trigger event.

<img width="418" alt="image" src="https://user-images.githubusercontent.com/18027354/157045266-a04bd930-ca7e-4984-b106-db2b6fbda6b4.png">

### Expected Behavior

Click position occurs before offset

### Actual Behavior

Click on the right, the selection should be right. Click on the left, the left should be selected.

**Comment by stepankuzmin** [comment]
Hi @YeomanYe,

Thank you for your opening this ticket. To help the maintainers and community understand and address the problem accurately, please provide a minimal, complete, verifiable demonstration of the issue. We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.
