### ISSUE TITLE
loading ArcGIS Server data

### ISSUE THREAD

**Issue by bFlood** [mapbox/mapbox-gl-js#1159]
I'm loading ArcGIS Server data into mapbox gl on the fly, its working pretty well but now I've got a couple small style issues to work out in the conversion. I know you're working on a new style spec and possibly a new implementation of how sprites are stored/loaded but I think these issues will be present for me even when that is complete.

1) fill-image and sprite sheet - simple hatch fill and picture fill icons are added to the sprite sheet when the service is loaded. they show up in the map but the image becomes pixelated if zoom in too far. This is probably an issue on my side but is there any guidance on how fill-image PNG files should be created or sized? the maps below are loaded from this map server: https://hazards.fema.gov/gis/nfhl/rest/services/public/NFHL/MapServer

![img_0066 1](https://cloud.githubusercontent.com/assets/404991/7151975/c7ba833a-e300-11e4-8f5b-14e5680b02f8.PNG)

![img_0069](https://cloud.githubusercontent.com/assets/404991/7152010/50a90f7c-e301-11e4-89fc-00aeb21021a4.PNG)

![img_0068](https://cloud.githubusercontent.com/assets/404991/7152016/67ec06bc-e301-11e4-80b7-98d737fe24ff.PNG)

2) polygon label position - what is the proper syntax for centering a label in the polygon?

![img_0070](https://cloud.githubusercontent.com/assets/404991/7152002/1adbe54a-e301-11e4-894e-c1d305cd1fd5.PNG)

3) the geojson support is great however it's difficult to stream additional data changes into the source. if a layer contained millions of features, its definitely better to load areas within the current viewport however as the total downloaded feature count for the layer increases, it gets less and less efficient to pass all of those features to the web worker for parsing. to get around this, I need to maintain a separate set of geojson tiles and feed only those tiles into the source when needed. this works pretty well in practice (on mobile even) but it still seems like a waste, is there any possibility of passing feature deltas into a geojson source?

**Comment by bFlood** [comment]
when I tested on a new iPhone6, the weird fill-image issue from above went away. 

![img_0005](https://cloud.githubusercontent.com/assets/404991/7166757/bc3ae004-e37d-11e4-9b4c-ecb079922fb1.PNG)


however, all line strokes appear distorted like below 

![img_0006 1](https://cloud.githubusercontent.com/assets/404991/7166760/c3f3f3a8-e37d-11e4-8b49-4372b0acaee9.PNG)

**Comment by mourner** [comment]
Stale, fill/stroke issues might have been fixed in recent updates. Polygon centroid is tracked at #1231.

**Comment by jerrygarciame123** [comment]
Can someone provide a code snippet for adding ArcGIS map services to MapBox GL API?

**Comment by deligence** [comment]
Hi, how did you done this? I am looking for solution but no success.

**Comment by danpe** [comment]
@jerrygarciame123 @deligence any luck with this?
