### ISSUE TITLE
Page automatically scrolls down to the top of the map

### ISSUE THREAD

**Issue by dev-mirzabicer** [mapbox/mapbox-gl-js#11595]
**mapbox-gl-js version**: 2.3.1

**browser**: Chrome

### Steps to Trigger Behavior

 1. Include a map in the page
 2. The only option is "scrollZoom: false"
 3. It has markers, popups and bounds. 4. 
 4. Enter the page with the map
 5. The map in the page is down below.

### Link to Demonstration

Not including any links since the explanation is simple enough.

### Expected Behavior

The page should open at the top, like a normal page

### Actual Behavior

The page scrolls down to the map, so the very top of the map is at the very bottom of the page.

This is where it scrolls to:
<img width="1440" alt="Screen Shot 2022-03-14 at 3 07 32 PM" src="https://user-images.githubusercontent.com/90691873/158169358-8c22e7f7-6805-4586-b85f-00da13288ac8.png">

This is the map:
<img width="1440" alt="Screen Shot 2022-03-14 at 3 10 56 PM" src="https://user-images.githubusercontent.com/90691873/158169623-d8088bb2-ba9c-4637-b45a-c8051363f4a1.png">

**Comment by ryanhamley** [comment]
Hi @dev-mirzabicer can you please use JSBin/JSFiddle/CodePen to create a live example of this? It's possible that some particular setting is causing this so it's easier to debug with a live replication.

**Comment by vanminhle** [comment]
All you need to do is adding focusAfterOpen: false options in the mapboxgl.Popup({ }). Like this
```
new mapboxgl.Popup({ offset: 30, focusAfterOpen: false })
      .setLngLat(loc.coordinates)
      .setHTML(`<p>Day ${loc.day}: ${loc.description}</p>`)
      .addTo(map);
```

**Comment by MathiasHC** [comment]
Is that shown anywhere in the documentation @vanminhle ? I thought I had check it all, guess not though 😅
– Thank you 💪

**Comment by vanminhle** [comment]
@MathiasHC You can check it in here [https://docs.mapbox.com/mapbox-gl-js/api/markers/#popup](url). They list all the popup component options you can use.

**Comment by SnailBones** [comment]
Thank you for the solution @vanminhle!
