### ISSUE TITLE
Globe view `mouseenter` event is not firing after a certain zoom level

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#11597]
Originally reported by @bumbeishvili in https://github.com/mapbox/mapbox-gl-js/issues/10784#issuecomment-1067216398.

>I've just discovered one, globe view-related issue.
>
>`mouseenter` event is not firing after certain zoom level (when zooming out). I am using `2.8.0-alpha.1` version (mac, chrome)
>
>https://user-images.githubusercontent.com/6873202/158248521-4ee713a2-f0c6-4978-b340-e4705462a3f7.mp4

**Comment by avpeery** [comment]
@bumbeishvili Thanks for submitting this issue! I've tried reproducing this error, but it seems like `mouseenter` with globe view is firing for me no matter the zoom level. Can you provide a minimal code reproduction of the problem you're reporting so we can better investigate it? Thanks again!

**Comment by bumbeishvili** [comment]
@avpeery  this is an online example - https://bumbeishvili.github.io/stanislaw-fivrr-mapbox-globe/

Click the camera to see the globe view

![Screenshot 2022-03-22 at 02 49 10](https://user-images.githubusercontent.com/6873202/159375644-d44fb308-ed4c-46c6-81cd-245494c05c95.png)

You can find the source here - view-source:https://bumbeishvili.github.io/stanislaw-fivrr-mapbox-globe/

If I will find time, I'll assemble better example, but this also may be enough for you to investigate

**Comment by karimnaaji** [comment]
@avpeery looking at this issue more, it's directly dependent on feature querying on globe that @mpulkki-mapbox is working on.

So we have to wait until that is finished first before we get back to verify that all the mouse events work in general.

**Comment by avpeery** [comment]
@bumbeishvili globe view now has support for feature querying which was impacting "mouseenter" in the example you provided. 2.9.0-alpha.1 should resolve your issue. Thanks!

**Comment by bumbeishvili** [comment]
I changed the version from 
`<script src="https://unpkg.com/mapbox-gl@2.8.0-alpha.1/dist/mapbox-gl.js"></script>`
to
`<script src="https://unpkg.com/mapbox-gl@2.9.0-alpha.1/dist/mapbox-gl.js"></script>`

But current code is no longer working

![image](https://user-images.githubusercontent.com/6873202/164060666-5ece5c5f-96d7-46ab-886f-16fc95bf1220.png)

I suspect something is related to passing `globe` as a projection


<img width="459" alt="image" src="https://user-images.githubusercontent.com/6873202/164060840-62187589-98ed-4757-b705-54b1763b4db7.png">

**Comment by avpeery** [comment]
@bumbeishvili  Yes, apologies for the confusion - globe is not yet released. If you need to test out the globe view, please make a build from the main branch for now. Thanks!
