### ISSUE TITLE
setLayoutProperty() only work once with text-allow-overlap property

### ISSUE THREAD

**Issue by Maltretieren** [mapbox/mapbox-gl-js#1160]
I'm trying to set the layout property "text-allow-overlap" for a symbol layer dependent on the scale. setLayoutProperty() is triggered by a zoom event and toggles textAllowOverlap to true or false.

```
var textAllowOverlap = false;
if (map.transform.zoom > 15) {
    textAllowOverlap = true;
}
map.setLayoutProperty('SymbolLayer', 'text-allow-overlap', textAllowOverlap);
```

What I observe is that if the initial zoom level is greater than 15 the textAllowOverlap property will be true and all labels will be shown on the map on the the first zoom event (this is correct behavior). If I now zoom to a level less than 15 the property will be set back to false, but the map doesn't update corresponding to the property? 
If I start at zoom level less than 15 and than zoom with the trackpad to a level greater than 15 the map will not be updated to show all labels...

So, it seems that the map only reflects the first change done with setLayoutProperty() and than doesn't work anymore... I also tried to use stops for the property in the layer style - no luck...

**Comment by Maltretieren** [comment]
After further investigation this is not a bug, but a performance issue. The above code is called many times, because zoom is called many times between zoom start and zoom end. So, it sets the property many times which takes a long time to update the map.. It should be called only one time when it crosses the zoom level 15:

```
var prevZoom = map.transform.zoom;
map.on('zoom', function () {
    if (map.transform.zoom > 15 && prevZoom < 15) {
        map.setLayoutProperty('SymbolLayer', 'text-allow-overlap', true);
    } else if(map.transform.zoom < 15 && prevZoom > 15) {
        map.setLayoutProperty('SymbolLayer', 'text-allow-overlap', false);
    }
    prevZoom = map.transform.zoom;
});
```
The api could provide a zoomstart and zoomend event to simplify the code above...

The issue can be closed!

**Comment by jfirebaugh** [comment]
You can use a style function to accomplish this optimally:

```
{
  "id": "SymbolLayer",
  "layout": {
    "text-allow-overlap": {
      "stops": [[0, false], [15, true]]
    }
  }
}
```
