### ISSUE TITLE
Incorrect spacing in line layer dashes across tiles

### ISSUE THREAD

**Issue by endanke** [mapbox/mapbox-gl-js#11618]
This issue was original reported in GL-Native, but can be reproduced here too. https://github.com/mapbox/mapbox-gl-native-internal/issues/1226

**mapbox-gl-js version**: 2.7.0

**browser**: Google Chrome 99.0.4844.74

The image below illustrates the issue. The expected behaviour would be to seamlessly continue the dashes across the tiles, but in reality the dash starts from a different point in the middle tile and it gets clipped.

<img width="1126" alt="Screenshot 2022-03-18 at 17 32 21" src="https://user-images.githubusercontent.com/2576246/159033352-2299136e-5b06-41ae-b2bb-d7724d309de5.png">

The issue can be reproduced using the following source and layer:

```
map.addSource('route-source', {
    "type": "geojson",
    "data": {
    "type": "FeatureCollection",
    "features": [
        {
        "type": "Feature",
        "properties": {},
        "geometry": {
            "type": "LineString",
            "coordinates": [
            [
                46.9604,
                13.6676
            ],
            [
                54.8909,
                21.0603
            ]
            ]
        }
        }
    ]
    }
});

map.addLayer({
    "id": "route-layer",
    "type": "line",
    "source": "route-source",
    "paint": {
        "line-width": 15,
        "line-dasharray": [2,4]
    }
});
```

**Comment by ryanhamley** [comment]
This is a known issue https://github.com/mapbox/mapbox-gl-js/issues/5395

**Comment by endanke** [comment]
@ryanhamley thanks for mentioning the other issue! I'll close this one, but will look into a fix for the problem.
