### ISSUE TITLE
How i can Json parse properties in interpolate coloring?

### ISSUE THREAD

**Issue by erkanisuf** [mapbox/mapbox-gl-js#11629]
I am using a tile service that sends data to map. The service provides data from database which is in format jsonbl in PostgreSQL .
After the map receives the data and when i log the features/properties it looks like a string and i need a way to Json parse it.

![Screenshot 2022-03-19 at 21 16 08](https://user-images.githubusercontent.com/63913743/159135499-b40b3222-e9d4-4228-86bf-be42851d753b.png)

I also need a way to acces these nested properties of that "string".

I am trying to use it for coloring in :

    "paint": {
                        "fill-color": [
                            "interpolate",
                            ["linear"],
                            ["get", "PROPERTY_HERE"],
                            0, "#FFFFFF",
                            0.05, "#F9E3E1",
                            0.1, "#F3C6C2",
                            0.15, "#EDAAA4",
                            0.2, "#E88D85",
                            0.25, "#E27167",
                            0.3, "#DC5448",
                            0.35, "#D6382A"
                        ],

I need to acces the nested properties . How this string can be converted as object? The source is type vector.

**Comment by ryanhamley** [comment]
This isn't supported at the moment. There's explanations why not [here](https://github.com/mapbox/mapbox-gl-js/issues/2434#issuecomment-209595609) and [here](https://github.com/mapbox/mapbox-gl-js/issues/2434#issuecomment-209825111). https://github.com/mapbox/mapbox-gl-js/issues/2434 has some workarounds that you may be able to use, such as https://github.com/mapbox/mapbox-gl-js/issues/2434#issuecomment-497494737. There's also https://github.com/mapbox/mapbox-gl-js/issues/6546 that tracks adding `to-object` and `to-array` expressions. In the meantime, if you need more help implementing a solution, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).
