### ISSUE TITLE
RN ios app crash when xcode update to 13.3

### ISSUE THREAD

**Issue by VegaChen-BadtzMaru** [mapbox/mapbox-gl-js#11633]
When I update xcode to 13.3, the mapbox-gl-js component crashed when I open it.

Mapbox`-[MGLMapView renderSync]:

Thread 1: EXC_BAD_ACCESS (code=1, address=0x7ff2221ffee0)

**Comment by ryanhamley** [comment]
It sounds like you're actually using [GL Native](https://github.com/mapbox/mapbox-gl-native) so you'd want to open any bug tickets with them. You may want to contact [Mapbox Support](https://support.mapbox.com/hc/en-us) if you need help getting this set up.
