### ISSUE TITLE
Thoroughly document event objects

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1164]
We document [events you can listen to](https://www.mapbox.com/mapbox-gl-js/api/#new-mapboxgl-map-options--events) but need to thoroughly document event objects and their properties.

**Comment by tmcw** [comment]
To the PR https://github.com/mapbox/mapbox-gl-js/pull/1165

**Comment by Randgalt** [comment]
"We document events you can listen to". Hmm. That's generous. Documentation should tell me how to use a feature and, possibly, give examples. What you have are comments about your event system, not documentation.

**Comment by tmcw** [comment]
This comment is referring to _API documentation_, not guides or narrative documentation, which you are referring to. Two separate things, both of which we'll build, but the scope of this comment is the former.
