### ISSUE TITLE
Can layers have a higher z-index than Markers?

### ISSUE THREAD

**Issue by Niyaz94** [mapbox/mapbox-gl-js#11644]
**V2.1.1**

Is there any way to put(a higher z-index) the below line above This marker? If not, what is the alternative? 

![1](https://user-images.githubusercontent.com/63070453/160406587-6757f020-a682-48f5-adaa-b9aea57183f1.png)
![2](https://user-images.githubusercontent.com/63070453/160406620-2c8e5361-44e9-407f-974f-836c984b6407.png)

**Comment by SnailBones** [comment]
Hi @Niyaz94,

Markers are HTML elements drawn on top of the map, so they will always appear above all layers. The alternative is to use a [symbol layer](https://docs.mapbox.com/mapbox-gl-js/example/geojson-markers/),  and use the second argument of [`map.addLayer()`](https://docs.mapbox.com/mapbox-gl-js/example/geojson-layer-in-stack/) to place it at the desired order.
