### ISSUE TITLE
What does lineMetrics actually do and can it be used for different purposes than linear-gradient?

### ISSUE THREAD

**Issue by varna** [mapbox/mapbox-gl-js#11650]
**mapbox-gl-js version**: 2.7.1

### Question

What does `lineMetrics` actually do?

Docs only say: `boolean: Whether to calculate line distance metrics.`

Does it calculate the distance of all vertices?

Or does it calculate total distance of whole Feature?

Can I access this data?

Can this data be used for something else than `linear-gradient`?

I'm testing out possibilities for something similar to Google Ruler:
<img width="438" alt="image" src="https://user-images.githubusercontent.com/6717694/160635052-748213d5-198e-4ed5-a451-6c316ab30af6.png">

Also Vertex length (distance) and/or Point distance:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/6717694/160635391-8fa640d7-af67-4987-8c9e-f72807e7f62d.png">

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson-lineMetrics

https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-line-line-gradient

**Comment by asheemmamoowala** [comment]
@varna You can find more information about line metrics in the geojson-vt library where it is implemented [here](https://github.com/mapbox/geojson-vt/pull/93). 

> Can I access this data?

The `mapbox_clip_start` and `mapbox_clip_end` properties are available in line geometry returned from the `Map#queryRenderedFeatures` and `Map#querySourceFeatures` methods when line metrics is enabled. Keep in mind that these methods return data per tile and the clip information represents start and end percentage of the line for that particular tile only.
