### ISSUE TITLE
Adding symbol type layer throws "Unimplemented type: 3" when using non-mapbox basemap style

### ISSUE THREAD

**Issue by bercivarga** [mapbox/mapbox-gl-js#11659]
Hi all,

I'm building an application that displays geojson data on a basemap style provided by [ArcGIS (ESRI)](https://developers.arcgis.com/mapbox-gl-js/maps/change-the-basemap-layer/). I encountered an issue when adding `symbol` type layers to my map when I have a non-mapbox provided basemap set as my map's style, which I believe is caused by a bug.

When adding a symbol type layer to my map, I get an error in the console with the message: `Unimplemented type: 3`. Additionally, I see network requests being fired in my devtools asking for `.pbf` files from my basemap's server. This error results in my layers being removed from the map with only the basemap being actively shown. When switching the basemap style to one provided by Mapbox (e.g. `mapbox://styles/mapbox/streets-v11`), the error doesn't show and the network requests are not fired when adding the new `symbol` type layer. This last behavior made me open this bug ticket, as it doesn't make sense to me why the network requests happen only when using a non-Mapbox basemap style.

This behaviour is specific to having `symbol` type layers active on my map in combination with an external (non-mapbox) map style. When I tried adding a `circle` layer, everything worked as expected. Lastly, I wanted to mention that I've seen (only a few) somewhat similar threads with this error within Mapbox, however the errors for me **ONLY** appear when I try adding new `symbol` type layers to the map. On initial load, the basemap (in my case from ArcGIS) loads as expected.

**mapbox-gl-js version**: ^2.7.1

**browser**: any

### Steps to Trigger Behavior

 1. Initialise a new map with `new mapboxgl.Map()`
 2. Set the map's style to be a non-mapbox provided basemap (in my case it's provided by [ArcGIS/ESRI](https://developers.arcgis.com/mapbox-gl-js/maps/change-the-basemap-layer/))
 3. Add a new source with `map.addSource` with geojson data
 4. Add a new `symbol` type layer with `map.addLayer()`
 5. Open the console and see the `Unimplemented type: 3` error being thrown
 6. Open the network tab and see a new request being fired when adding the layer, with the respone containing `{"error":{"code":404,"message":"Requested font resource not available.","details":null}}`
 7. Change map's style to `mapbox://styles/mapbox/streets-v11`
 8. Check for the above mentioned behavior again. See how there're no errors and no new requests being fired when adding the `symbol` type layer

### Link to Demonstration
[Link to CodePen](https://codepen.io/vargajs/pen/WNdZYdb)
(note, that you need your own Mapbox token to run the example)

### Expected Behavior

Clicking on the "add symbol layer" button in the top-left corner should add two "Mapbox" text fields on the map, one above San Francisco, the other above Washington.

### Actual Behavior

Clicking on the button results in an error saying `Unimplemented type: 3` when using a non-mapbox basemap style. Additionally, a network request is made to the basemap's server for `0-255.pbf` files. When changing to one of the mapbox-provided map styles (e.g. `mapbox://styles/mapbox/streets-v11`), none of the above mentioned behaviors occur: no errors in the console and no network requests made for `.pbf` files.

Thank you for reading my ticket, and have a great day!

**Comment by asheemmamoowala** [comment]
@bercivarga The symbol layer you are adding references Fonts that are not available at the API endpoint specified in your style. Mapbox GL supports a single style property for specifying [font glyphs](https://docs.mapbox.com/mapbox-gl-js/style-spec/glyphs/). Any fonts used in your style, through the base map or runtime layers, should reference fonts available at the gylph URL.

This can be fixed in your codepen, for example, by switching to the `Arial Italic` font which is available at the glyph URL of the basemap provider.

**Comment by bercivarga** [comment]
@asheemmamoowala thank you for your reply!

The solution you proposed indeed works. You just saved me a lot of headaches. :)
