### ISSUE TITLE
map.FeaturesAt fails due to Tile having no zoom

### ISSUE THREAD

**Issue by atlefren** [mapbox/mapbox-gl-js#1166]
I'm currently using the master branch, and the map.FeaturesAt fuction doesn't work.

After some digging i've found that:

- tileAt in tile_pyramid.js calls tile.positionAt for each tile
- this returns an object with NaN for x & y

this is due to the fact that the positionAt  function in tile.js uses the property this.zoom in the call to coord.zoomTo

The problem is that the zoom property of the tile object is not defined. I'm thinking that this must be a bug? The FeaturesAt function works great with the hosted (more stable) version.

It might be that you guys have this under control, but I wanted to let you know at least. Feel free to close this issue if that's the case

**Comment by atlefren** [comment]
An update: I got this to work by editing tile.js so that the positionAt function calls coord.zoomTo with coord.zoom instead of the (non-existing) this.zoom

However, this lead to an error in FeatureTree.prototype.query, because the this.coord was undefined.

The cause of this was in worker_tils.js, where a FeatureTree was constructed using this.featureTree = new FeatureTree(this.id);

The problem was that this.id was undefined, because the constructor in worker_tile.js got a params object, with UID instead of id. Setting this.id = params.uid did the trick, and featuresAt seems to work now

**Comment by atlefren** [comment]
So, in short: 

Fix tile.js: positionAt should call  coord.zoomTo with coord.zoom (not this.zoom)

fix worker_tils.js: constructor should set this.id = params.uid; not params.id

**Comment by tmcw** [comment]
:+1: given how i've seen this issue before this sounds like a very likely diagnosis. Will check into a fix on Monday.

**Comment by ansis** [comment]
@atlefren thanks for the great report. fixed in https://github.com/mapbox/mapbox-gl-js/commit/2cfd9d0687e430d92c62f6ee2cbd5fd91d8fb44e

**Comment by atlefren** [comment]
@ansis Great, thanks for fixing!
