### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'klass')

### ISSUE THREAD

**Issue by ntakouris** [mapbox/mapbox-gl-js#11686]
After updating to latest `mapbox-gl` 7.20.3, in order to solve #11457, we get a new error:

`Uncaught TypeError: Cannot read properties of undefined (reading 'klass')`, every time we pan (and on map load). Sattelite tiles are indeed rendered, but the vector openstreetmap tiles (are names, some roads, etc) are not.

**mapbox-gl-js version**: 7.20.3

Edit: can confirm that this also works with latest versions (mapbox 2.8), published ~20h ago

**Comment by ntakouris** [comment]
It seems that downgrading to `mapbox-gl@2.2` renders those styles without issue.

**Comment by Aeropath** [comment]
+1 issue for mapbox-gl 2.8
Issues with create-react-app and the worker-loader approach I think.

I can get it to work fine during dev, but not after a build.

**Comment by SnailBones** [comment]
@ntakouris Would you be able to provide a reproduction of this issue in CodePen or JSBin to help us get this resolved?

This may be the same as #11684

**Comment by avpeery** [comment]
@ntakouris what is your setup like? Are you using a transpiler, like Babel? Thanks for reporting this issue!

**Comment by avpeery** [comment]
@Aeropath what is your browserlist? Have you tried excluding mapbox from being transpiled? https://docs.mapbox.com/mapbox-gl-js/guides/install/#excluding-mapbox-gl-js-explicitly-from-transpilation

**Comment by avpeery** [comment]
@ntakouris @Aeropath thanks for reporting this issue! We've released a patch [v2.8.1](https://github.com/mapbox/mapbox-gl-js/releases/tag/v2.8.1) that should fix your error! Thanks!

**Comment by vladd11** [comment]
Hello. I'm still getting this issue.
Error: Uncaught TypeError: Cannot destructure property 'klass' of 'Cr[e]' as it is undefined.

My code: import Head from 'next/head'
import styles from '../styles/Home.module.css'

import mapboxgl from 'mapbox-gl/dist/mapbox-gl-csp';
import MapboxWorker from 'worker-loader!mapbox-gl/dist/mapbox-gl-csp-worker';
import {createRef, useEffect} from "react"; // Load worker code separately with worker-loader

mapboxgl.accessToken = 'CENSORED'
export default function Home() {
    mapboxgl.workerClass = MapboxWorker; // Wire up loaded worker to be used instead of the default

    const map = createRef()
    const mapContainer = createRef()

    useEffect(() => {
        if (map.current) return;
        map.current = new mapboxgl.Map({
            container: mapContainer.current, // container ID
            style: 'mapbox://styles/mapbox/streets-v11', // style URL
            center: [-74.5, 40], // starting position [lng, lat]
            zoom: 9 // starting zoom
        })
    })

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <div id="map" ref={mapContainer}></div>
        </div>
    )
}

I'm using React.js with Next.js (HTML export/static site).
Mapbox GL JS version: 2.8.1
