### ISSUE TITLE
Map not showing in browser after update to 2.8.0

### ISSUE THREAD

**Issue by lruklic** [mapbox/mapbox-gl-js#11684]
After I updated `mapbox-gl` to `2.8.0` the map in my application stopped working. The recurring error in the DevTools is shown in the picture below. When I demote the version to `2.7.0` issue is not manifesting anymore.

![Capture2](https://user-images.githubusercontent.com/8364540/162422035-118dfb33-545a-44f9-8f50-58b589b37c1b.JPG)

The last point of stack trace where the error occurs is here:

![image](https://user-images.githubusercontent.com/8364540/162422993-d16b0530-9f76-4a05-b5ca-903af454c9fc.png)

Since the only change between working and not working app instances is the mapbox version, I assumed the bug is there somewhere. I haven't seen anything related to this bug and don't know is this specific to my case but I wanted to give notice here. If needed I can provide additional details about my project.

**Comment by SylvainLaconi** [comment]
Exact same issue appearing today. Map doesn't work anymore on localhost environment. But still working on deployed prod environment.

**Comment by Aeropath** [comment]
+1 issue for mapbox-gl 2.8
Issues with create-react-app and the worker-loader approach I think.

I can get it to work fine during dev, but not after a build.

**Comment by SnailBones** [comment]
@lruklic Thanks for opening this issue! Would you be able to provide a reproduction of this issue in CodePen or JSbin to help get this solved quickly?

**Comment by avpeery** [comment]
@SylvainLaconi What are your production and development browserlists? Thanks for also reporting!

**Comment by ansis** [comment]
It looks like this can be reproduced with the regular csp build:

`yarn run build-csp`
`yarn run start-debug`
`open http://localhost:9966/debug/csp-static.html`

**Comment by avpeery** [comment]
@lruklic @Aeropath @SylvainLaconi We've released a patch that fixes this issue ([v2.8.1](https://github.com/mapbox/mapbox-gl-js/releases/tag/v2.8.1)). Thanks!
