### ISSUE TITLE
Flaky query tests: master ticket

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/mapbox-gl-js#11736]
This ticket consolidates reports of flaky query tests in one place.

- [ ] https://github.com/mapbox/mapbox-gl-js/issues/11726
- [ ] https://github.com/mapbox/mapbox-gl-js/issues/11727
- [ ] https://github.com/mapbox/mapbox-gl-js/issues/11728
- [x] https://github.com/mapbox/mapbox-gl-js/issues/11735

**Comment by SnailBones** [comment]
Closing as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/11732, I added these tests there
