### ISSUE TITLE
Clamping behavior of `pointCoordinate` leads to false positives in feature queries

### ISSUE THREAD

**Issue by mpulkki-mapbox** [mapbox/mapbox-gl-js#11746]
Feature querying uses `pointCoordinate` functionality for projecting screen rectangles into query polygons. Globe view implementation of the function clamps the query ray to the horizon of the globe as the function signature does not allow null values. This has a side effect of returning features at the horizon line due to the clamping:

https://user-images.githubusercontent.com/7061573/163066618-db297271-4c5e-4983-877d-aad92f9e1442.mov

Perhaps we could consider modifying the function and allow returning null values?

**Comment by karimnaaji** [comment]
The behavior with globe using the https://docs.mapbox.com/mapbox-gl-js/example/mouse-position/:

https://user-images.githubusercontent.com/7061573/164530810-8a6bbd54-7a30-45d2-9f21-a77942ba60e6.mov
