### ISSUE TITLE
Globe + terrain combination results in symbol rendering artifacts

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#11753]
The combination globe + terrain result in rendering artifacts of symbols where the vertex buffer seems to be filled with incorrectly projected vertices:

https://user-images.githubusercontent.com/7061573/163267985-3db988ff-234e-4e63-ae74-b976703102a6.mp4

**Comment by mpulkki-mapbox** [comment]
This will be fixed by https://github.com/mapbox/mapbox-gl-js/pull/11765
