### ISSUE TITLE
Globe + terrain combination results in incorrect marker occlusion

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#11755]
The combination globe + terrain results in inconsistently occluding some markers, as shown in the video below:

https://user-images.githubusercontent.com/7061573/163274429-86dd0efc-1719-422a-9e1f-3c37ed17bd98.mp4

cc @SnailBones

**Comment by SnailBones** [comment]
This is caused by the `else if` instead of `if` [here](https://github.com/mapbox/mapbox-gl-js/blob/744367a7756ed7286556646f4bd003f6833a2c4d/src/ui/marker.js#L443), I will fix this as part of #11658

**Comment by karimnaaji** [comment]
@SnailBones and I haven't been able to reproduce this issue. We'll a close eye for this combination and reopen if we manage to get a proper reproduction situation.
