### ISSUE TITLE
Line labels float above the globe

### ISSUE THREAD

**Issue by zakjan** [mapbox/mapbox-gl-js#11761]
**mapbox-gl-js version**: 2.8.0-alpha4 (globe projection stopped working in later versions #11760)

**browser**: Chrome 100, Mac M1

### Steps to Trigger Behavior

 1. Use globe projection
 2. Add a layer with line labels

### Link to Demonstration

https://codepen.io/zakjan/pen/yLpQwMy (lines represent atmospheric pressure isobars)

### Expected Behavior

Line labels are positioned on the ground

### Actual Behavior

Line labels float above the globe

![Screenshot 2022-04-17 at 11 09 45](https://user-images.githubusercontent.com/173585/163708127-42c79b8e-90da-4085-80c5-0f48caa7ca02.png)

**Comment by mourner** [comment]
Is this reproducible on with the `main` branch version? See https://github.com/mapbox/mapbox-gl-js/issues/11760#issuecomment-1100909299

**Comment by karimnaaji** [comment]
Just tested this out and it's still reproducible on `main`. 

![Screenshot from 2022-04-18 13-19-11](https://user-images.githubusercontent.com/7061573/163871625-69246d76-dad4-4ea9-ad7e-80c7e1acbdb4.png)

But this issue is currently being worked on and covered by https://github.com/mapbox/gl-js-team/issues/368. It should be addressed soon and we'll close this ticket. Thanks for reporting @zakjan .

**Comment by zakjan** [comment]
Thanks for testing, I had troubles with a local build because of Node 17, and I couldn't switch quickly back. Great to hear it's already in progress.

**Comment by zakjan** [comment]
Thanks @karimnaaji, looking forward to try it out! When is it expected to be released?

**Comment by karimnaaji** [comment]
@zakjan We have a beta planned to be out in the next week or two. There are still a few release blockers that we want to get done before cutting the beta.

**Comment by karimnaaji** [comment]
@zakjan The beta (v2.9.0-beta.1) is out, so these new changes should be available to you.

**Comment by zakjan** [comment]
Works perfect, thanks!
