### ISSUE TITLE
Atmosphere: Fix circle fog contribution during globe-mercator transition

### ISSUE THREAD

**Issue by mpulkki-mapbox** [mapbox/mapbox-gl-js#11769]
Expected behavior:

https://user-images.githubusercontent.com/55925868/164227904-3df0e9a1-a817-4688-b065-c942e622d5e2.mp4

Observed behavior:

https://user-images.githubusercontent.com/55925868/164227926-c9711a6b-f0a9-43cc-8126-6853c82843dd.mp4

**Comment by mpulkki-mapbox** [comment]
@karimnaaji: you were right, this is related to the fog

**Comment by SnailBones** [comment]
Circles at Null Island seem unaffected

https://user-images.githubusercontent.com/14878684/166807295-64995e9f-679f-4787-9d49-f0f860001855.mov
