### ISSUE TITLE
`fill-image` is not resetting at each zoom level for overzoomed tiles

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#1177]
For overzoomed tiles, `fill-image` used to behavior in the same way as not overzoomed tiles – i.e. the image would be scaled to accommodate the increasing tile size, and then reset back to the original scale at each integer zoom level. This is no longer true:

![fill-image-overzoom](https://cloud.githubusercontent.com/assets/5607844/7257588/d8928864-e824-11e4-93e6-7a0ba311ca22.gif)

(You can see the image resetting between z14 and z15, and then not resetting from then onwards)

/cc @ansis

**Comment by ansis** [comment]
Are you using master? I can't reproduce

**Comment by nickidlugash** [comment]
@ansis oh, this is for `v7`, which is what the editor uses. I'm also using it to make demo videos, because master is causing tiles to load slower. Do we know when we're going to do another js release?

**Comment by ansis** [comment]
> because master is causing tiles to load slower.

-js master is causing tiles to load slower? is there an issue open for this yet?

> Do we know when we're going to do another js release?

Not sure. @jfirebaugh, do you know when we're going to do another js release?
