### ISSUE TITLE
How to drag and drop a marker in mapbox-gl-js ?

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1179]
I've seen an example on how to this in mapbox, but not in mapbox-gl.
Can you provide one please?
I think I could implement a custom one by using the on_mouse_down event, then looking if there is any marker near the point where the user clicks (using turf.js), but maybe there is a better way.
What I'm not sure about in terms of event, is how you differentiate the event "user clicking on the map", from the event "user clicking on a marker, on the map"?
Thanks

**Comment by tmcw** [comment]
Currently this is not possible - we're planning on implementing a [Draw tool](https://github.com/mapbox/mapbox-gl-js/issues/848) and this'll be included in it.

**Comment by jingsam** [comment]
Mapbox GL JS intergrated with turf.js is a good idea

**Comment by huangyingjie** [comment]
But `Draw tool` just draws point not marker.

**Comment by lennerd** [comment]
Are there any other options we're probably missing? Or is this simply a missing feature in Mapbox GL or the Draw Tool?
