### ISSUE TITLE
Turf.js doesn't consider globe projection in calculations

### ISSUE THREAD

**Issue by willymaps** [mapbox/mapbox-gl-js#11791]
**mapbox-gl-js version**: `v2.8.0-alpha.4`

**browser**: chrome `v100.0.4896.88`

### Steps to Trigger Behavior

 1. Add geojson points
 2. Generate `turf.voronoi`
 3. Voronoi will stop at anti-meridian

### Link to Demonstration

https://codepen.io/willymaps/pen/LYeaqRg

### Expected Behavior

https://observablehq.com/@d3/world-airports-voronoi?collection=@d3/d3-delaunay

### Actual Behavior

Turf.js functions that are likely affected:

- http://turfjs.org/docs/#voronoi
- http://turfjs.org/docs/#randomLineString
- http://turfjs.org/docs/#randomPolygon

**Comment by mourner** [comment]
Looks like this is an issue unrelated to GL JS — this is just the way turf-voronoi works, clipping Voronoi to the world extent (-180..180). The notebook from "expected behavior" uses `d3-geo-voronoi`, specifically handling the spherical case, instead of `d3-voronoi` which Turf uses.
