### ISSUE TITLE
Missing tiles on globe when using bathymetry example

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#11811]
The example https://docs.mapbox.com/mapbox-gl-js/example/style-ocean-depth-data/ is not working properly with globe projection, where the tile cover may incorrectly mark tiles as not visible:

**Current behavior**

https://user-images.githubusercontent.com/7061573/164812332-42311b83-b4e9-4458-9afa-04815ef725f1.mov

The map min zoom: is set to 3, and max zoom is set to 5. This issue is possibly related to https://github.com/mapbox/mapbox-gl-js/issues/11789 and https://github.com/mapbox/mapbox-gl-js/issues/11368.

**Expected behavior**

The globe renders without missing tiles.

**Comment by SnailBones** [comment]
I'm able to reproduce this as follows:

```js
    map.addLayer(
    {
        id: 'country-boundaries',
        source: {
            type: 'vector',
            url: 'mapbox://mapbox.country-boundaries-v1',
        },
        'source-layer': 'country_boundaries',
        type: 'fill',
        paint: {
            'fill-color': '#d2361e',
            'fill-opacity': 0.4,
        },
        minzoom: 3
    },
    'country-label'
    );

```
![image](https://user-images.githubusercontent.com/14878684/166770076-11b20cb2-da5e-4a9f-a0fb-4ee8a0669202.png)

Likely also related to #11368

**Comment by SnailBones** [comment]
Follow up on this after chatting with @ansis:

Ultimately fixing this issue would require decoupling tiles loaded from map styling. A short-term fix is to reduce globe tile optimization in the case of neighboring tiles that are currently rendered at a lower level than the center tile.. PR in progress here: https://github.com/mapbox/mapbox-gl-js/pull/11917.

**Comment by willymaps** [comment]
@astojilj the updated bathymetry tileset starts at `z0` so shouldn't be a concern.

**Comment by karimnaaji** [comment]
This issue was mitigated by https://github.com/mapbox/mapbox-gl-js/pull/11951.
