### ISSUE TITLE
flyTo method throws me undefined

### ISSUE THREAD

**Issue by StianOek** [mapbox/mapbox-gl-js#11816]
**mapbox-gl-js version**:

### Question

Hey!

I'm using the useMap hook from the "react-map-gl": "^7.0.10"

and i invoke the function like in the docs description : const { current: map } = useMap();

With the code below i get the "Uncaught TypeError: Cannot read properties of undefined (reading 'flyTo')"
```
const handleLocations = (item) => {
    // eslint-disable-next-line react-hooks/rules-of-hooks

    map.flyTo({ center: [52, 32] });

    console.log(item[1], item[0]);
  };
  
   onClick={() => handleLocations(data[item].coords)}
  
```

I cant seem to work this out. 

Fingers crossed for that someone see this :)

**Comment by williamhaley** [comment]
I'm seeing something similar. If I specify `id=` on my `Map` like `<Map id="whatever" />` AND I use a `<MapProvider>` then I eventually see the hook yield some meaningful data.

```
useMap: {whatever: {…}, current: undefined}
```

`current` seems to be always `undefined` with or without an `id` and with or without the provider

**Comment by pReya** [comment]
Having the same problem. `useMap().current` is always undefined.

**Comment by stepankuzmin** [comment]
Hi all,

Most likely, this is the issue with the `react-map-gl` wrapper itself. So this issue should belong to the https://github.com/visgl/react-map-gl bug tracker. Feel free to reopen this issue if you have any questions.
