### ISSUE TITLE
mapbox-gl-js 2.7 version problem

### ISSUE THREAD

**Issue by zhangyuanyong** [mapbox/mapbox-gl-js#11815]
**mapbox-gl-js version**: 2.7.1

### Question

When using Google 74 browser, mapbox-gl.js reports an error:Failed to execute 'getImageData' on 'CanvasRenderingContext2D': Value is not of type 'long'.

**Comment by ansis** [comment]
> Google 74 browser

This version was released three years ago. Can you reproduce this with a more recent browser?

If yes, can you share an example that can be used to reproduce the issue?

**Comment by zhangyuanyong** [comment]
But mapbox-gl.js 1.4 version supports Google 74&nbsp;browser,mapbox-gl.js 2.7 version&nbsp;incompatible




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ansis ***@***.***&gt;; 
发送时间: 2022年4月25日(星期一) 晚上9:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mapbox/mapbox-gl-js] mapbox-gl-js 2.7 version problem (Issue #11815)






Google 74 浏览器

这个版本是三年前发布的，能用最近的浏览器重现吗？

如果是，你能分享一个可以重现这个问题的例子吗？

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您编写了这个线程。留言 ID ***@***.*** 74 browser.This version was released three years ago. Can you reproduce this with a more recent browser?
