### ISSUE TITLE
Add map.getLayer()

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1183]
The .getLayer(id) method exists within the .style property but isn't proxied to the Map object like the .removeLayer and .addLayer methods are.

**Comment by kristfal** [comment]
@tmcw This method is still not exposed to the map object. Would be useful in a ton of situations.

**Comment by bhousel** [comment]
Discussion still not settled, per https://github.com/mapbox/mapbox-gl-js/commit/e86351d644d0cd273ad41edce28545bbc192f922#commitcomment-13605229

**Comment by jfirebaugh** [comment]
@tmcw @kristfal Can you elaborate on what situations this would be useful for? In particular, what layer methods would you like to use (they are all currently private)?

**Comment by kristfal** [comment]
@jfirebaugh This would be very useful when working with a lot of added / removed layers or in states where I am not aware which layers exist or not in the style.

My primary use case for this right now would be to check if a given layer is present and remove it before removing an underlying geoJSON source.

Currently, we'd have to do a try/catch along these lines:

```javascript

        // Remove existing layers if present
        for (var i = 0; i < Object.keys(ls.layers).length; i++) {   
          try {
            this.mgl.removeLayer(Object.keys(ls.layers)[i]);  
          } catch (err) {
            // No layers to remove. Improvement: If mgl exposes getLayer, use it instead of try/catch.
          }
        }

        // Remove existing source if present 
        if (this.mgl.getSource(ls.source)){
          this.mgl.removeSource(ls.source);
        }

```

It works, but I feel it is quite strange that we need to try/catch the layers, but can check sources straightforward like that.

**Comment by tmcw** [comment]
My usecase is the same ^

**Comment by jfirebaugh** [comment]
Cool, I'm fine with exposing `getLayer` as the functional equivalent of `hasLayer` for now.

**Comment by uncleunvoid** [comment]
or to exchange the geojson on an existing layer, or... plenty of uses

**Comment by AbrahamBrookes** [comment]
To hide or show a layer, the example in the docs seems verbose. `mapbox.getLayer('layer').hide()` I was hoping for
