### ISSUE TITLE
SSL cert issue

### ISSUE THREAD

**Issue by chrisbradleydev** [mapbox/mapbox-gl-js#11835]
**mapbox-gl-js version**: 2.8.2

**browser**: Chrome 101.0.4951.41 (Official Build) (x86_64)

### Steps to Trigger Behavior

Chrome is returning three `net::ERR_CERT_COMMON_NAME_INVALID` errors.

Here is the copied request that is failing in Chrome.

**Note: You must update `MY_ACCESS_TOKEN` and `MY_USER_ID` with your user information.**

```sh
❯ curl 'https://events.mapbox.com/events/v2?access_token=MY_ACCESS_TOKEN' \
  -H 'Referer: https://mysite.test/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Safari/537.36' \
  -H 'Content-Type: text/plain' \
  --data-raw '[{"event":"appUserTurnstile","created":"2022-04-28T00:44:23.987Z","sdkIdentifier":"mapbox-gl-js","sdkVersion":"2.8.2","skuId":"01","userId":"MY_USER_ID","enabled.telemetry":false}]' \
  --compressed
```

### Link to Demonstration

The above curl request demonstrates the behavior.

### Expected Behavior

Expecting a response.

### Actual Behavior

Request is blocked with the following error.

```sh
curl: (60) SSL: no alternative certificate subject name matches target host name 'events.mapbox.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by ansis** [comment]
Thanks for reporting. I was not able to to reproduce this and the certificate looks valid from my end. Can you check that this isn't an issue on your end? (try disabling extensions, a different browser, different machine)

**Comment by chrisbradleydev** [comment]
@ansis, here is a demonstration of the error.

https://codesandbox.io/s/mapbox-ydonp8

**Comment by chrisbradleydev** [comment]
After further investigation, it appears that my network is blocking that request.
