### ISSUE TITLE
How do I enable the globe projection/view in mapbox gl javascript API?

### ISSUE THREAD

**Issue by ftottittl** [mapbox/mapbox-gl-js#11865]
Hi I am using mapbox gl js, like below:  and I tried to change the projection to "globe" like the other threads do, but do not work. Anyone could help me?

new mapboxgl.Map({
			attributionControl: false,	// do not show the attribution at the right bottom corner
			bearing: bearing || 0,
			boxZoom: true,
			container: containerId,
			maxBounds: maxBounds || null,	// LngLatBoundsLike. If set, the map will be constrained to the given bounds.
			maxPitch: maxPitch || 85,	// 0 - 85
			minPitch: minPitch || 0,	// 0 - 85
			maxZoom: maxZoom || 22,	// 0 - 24
			minZoom: minZoom || 0,	// 0 - 24
			pitch: pitch || 0,
			projection: "mercator",    // "globe"??
			style: style || 'mapbox://styles/mapbox-map-design/ckhqrf2tz0dt119ny6azh975y'
		});

**Comment by ftottittl** [comment]
@mpulkki-mapbox

**Comment by karimnaaji** [comment]
Globe view isn't released yet, the first public beta will be available this week.

**Comment by karimnaaji** [comment]
Globe is available on the latest beta: v2.9.0-beta.1.

**Comment by Dildar-Khan** [comment]
Hello @karimnaaji how to give atmosphere style like one of them https://github.com/mapbox/mapbox-gl-js/issues/10784#issuecomment-866732966

**Comment by karimnaaji** [comment]
hello @Dildar-Khan , atmosphere can be set like so:
```
map.setFog({
  'horizon-blend': 0.1,
  'star-intensity': 0.15,
  'color': 'white',
  'high-color': 'rgba(66, 88, 106, 1.0)',
  'space-color': 'rgba(66, 88, 106, 1.0)'
});
```
We also have a few examples in [this page](https://github.com/mapbox/mapbox-gl-js/blob/main/debug/atmosphere.html).

**Comment by Dildar-Khan** [comment]
Thank you @karimnaaji
