### ISSUE TITLE
Filter by iterating through object array

### ISSUE THREAD

**Issue by Bemjamin** [mapbox/mapbox-gl-js#11886]
**mapbox-gl-js version**: 2.7.1

In my vector I have a property with an object array stringified. I need to filter the tiles based on a given value of the array, so let's say I have the following property: 

`"properties": {
        "zip": 99999,
        "ids": "[{\"id\":\"123\",\"affinities\":[{\"year\":2022,\"month\":1,\"affinity\":1.15}]},{\"id\":\"456\",\"affinities\":[{\"year\":2022,\"month\":1,\"affinity\":0.02}]}]"
    },`

I would like to filter the layer by checking if in the array we have a given "id" and also change the color of the layer by interpolating over the affinity object property of the same id.

Following the docs I can only go until here: 

`filter: ["array", ["get", "ids"]],`

In the documentation it doesn't show how to find objects in the array. Is this possible?

### Links to related documentation

[https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#types](url)

**Comment by avpeery** [comment]
Hi @Bemjamin, you can filter objects with [expressions](https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions).

Consider this example source that includes a property which is an array of objects:

```"properties": {
    "someProp": [
        {"foo": "it works!"},
        {"foo": "b"},
        {"foo": "c"}
    ]
}```

Now in our layer's layout properties, we can define the text field like this:

`"text-field": ["get", "foo", ["at", 0, ["get", "someProp"]]],`
This expression (reading from right to left) get the array at properties.someProp, then gets the element at the 0th index in the array, then gets property foo from that object. You would see "it works!" at the text on the map. 

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thanks for using Mapbox!

**Comment by Bemjamin** [comment]
Hello @avpeery this exemple doesn't work on my case because I dont want to pass an index, I want to iterate someProp to find a "foo" with given value, lets say "b" and get another property from the object, in my case, the affinity. Or how can we see if in someProp we have a foo with value c ? How do we iterate?

**Comment by mdxiaohu** [comment]
@Bemjamin I also have similar needs, I'm not sure if this issue has been resolved .
