### ISSUE TITLE
Example: click feature to zoom to it

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1188]
The behavior in this Mapbox.js example: https://www.mapbox.com/mapbox.js/example/v1.0.0/choropleth/

We should be able to support this.

**Comment by jfirebaugh** [comment]
Bringing over comment from #1813:

> `featuresAt` gives you features clipped to tile boundaries (even if the original source was GeoJSON). This means that `map.zoomTo(turf.extent(features[0]))` will not work as expected if you're already zoomed in. :cry:

**Comment by tmcw** [comment]
We have the basic example. Closing any 'have the whole extent' issue as by-design.
