### ISSUE TITLE
How do I find a reviewer for my PR?

### ISSUE THREAD

**Issue by varna** [mapbox/mapbox-gl-js#11885]
### Question

How do I find a reviewer for my PR?

It has been 2 weeks since I posted https://github.com/mapbox/mapbox-gl-js/pull/11839

And it has been a week since I posted https://github.com/mapbox/mapbox-gl-js/issues/11857

I can't add labels and I don't know who to tag about this.

**Comment by avpeery** [comment]
Thank you for using mapbox-gl-js! We greatly appreciate your recent contributions. Since we maintain a large repository, it may take a moment to get a review on your PR. For the future, this issue tracker is for reporting bugs and feature requests.
