### ISSUE TITLE
Responsiveness?

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1190]
New can of worms: <b>should maps look differently based on the size of their viewport, like web pages do?</b> Is what looks good in a browser, also suitable for a phone screen?

Mostly pertains to size (labels, road thicknesses). This is more of a design question, though the technical and spec challenge here is formidable.

cc/ @nickidlugash @samanpwbb

**Comment by samanpwbb** [comment]
Hm... this does makes sense. Not sure it needs to be a dedicated feature though, we can leave it up to developer to check device width and toggle a class on the style. The real task here seems to be: classes in the editor :skull:

**Comment by nickidlugash** [comment]
> Not sure it needs to be a dedicated feature though, we can leave it up to developer to check device width and toggle a class on the style. The real task here seems to be: classes in the editor :skull:

This makes sense to me.

Offhand it seems to me that the biggest styling gains would actually be in toggling values for label density/collision properties (esp once we have [`-repeat-distance`](https://github.com/mapbox/mapbox-gl-style-spec/issues/269) in place). Adjusting sizes (and even colors, to make them brighter for mobile) could be helpful, although this could be a slippery slope towards making the map much less maintainable (wasn't one advantage of GL for our customers that they only had to maintain one map across all their platforms?)

**Comment by peterqliu** [comment]
using classes here sounds good

**Comment by nickidlugash** [comment]
Should we try this out? I still think this is good idea in order to adjust [the properties I mentioned above](https://github.com/mapbox/mapbox-gl-js/issues/1190#issuecomment-97198580).

**Comment by jfirebaugh** [comment]
Can you prototype this using a window resize event handler that adds a style class?

**Comment by lucaswoj** [comment]
This feature can be handled outside of GL JS core using window resize event handlers, classes, and the runtime styling API.
