### ISSUE TITLE
featuresAt performance

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1191]
![featuresatperf](https://cloud.githubusercontent.com/assets/1421652/7382238/5d8bc70a-edc1-11e4-9d38-43ee71c96944.gif)

> featuresAt is very performant on minor roads at, for instance, zoom 14 and very slow at minor roads at zoom 7

cc @tmcw

**Comment by mourner** [comment]
Do we retain all feature trees of higher zoom levels even after we zoomed out of them? I don't think minor roads should be even queriable at z7.

**Comment by mourner** [comment]
There are 2 issues here combined.

The first is that `featuresAt` is not throttled. `mousemove` fires really often, and if the featuresAt roundtrip (r-tree query + worker communication) is much longer than the interval between the calls, the slowdown just builds up during the move (z7 example): 

![image](https://cloud.githubusercontent.com/assets/25395/8850334/e4c26a72-314f-11e5-8838-9a45edffb549.png)

If the call is throttled (e.g. to 100ms on the slow z7), then the query time with the same setup rarely exceeds 100ms. 

The second issue is that performance is unreasonably slow at z7 and less. E.g. at z8 and more, it's just 2-3ms on average (though also occasionally suffers from buildup above if not throttled).  At z7, it suddenly jumps to around 100ms. There's certainly something fishy going on here.

@tmcw @kelvinabrokwa while I investigate the low zoom issue, consider throttling featuresAt calls to something like 32ms and it should speed up things considerably.

**Comment by mourner** [comment]
Found out what's going on with z7- queries. In Mapbox Streets, at lower zooms starting at z7, roads are merged into huge multilinestring features with lots of points (right @ajashton?). Which means that a query that returned 100kb of geometry on a point query at z8 suddenly returns 1Mb at z7 at the same point (e.g. with a road containing 4k+ points).

The bottleneck that causes slowness buildup on mousemove is sending GeoJSON geometry from the worker to the main thread. If you do `geoJSON.geometry = null;` in `featureTree.js` where the response is formed, the performance is perfect without the need to throttle.

@tmcw @kelvinabrokwa So, if you don't plan on actually using geometry of `featureAt` results in the app (e.g. overlaying as GeoJSON for faking highlighting), the right solution here would be to bring back the `includeGeometry` option for `featuresAt` that was present at some point but got stripped out for some reason.

Not sure if we want to address the z7- MultiLineString issue (which is only relevant if we want fast road queries _with_ geometry on z7). If we do, the only solution I can think of is quite complicated — maintaining featureTree with parts of multi- geometries stored separately, and returning only a part by default, maybe with an option to return the whole thing that would require a merge step in the worker. I'd say punt for now.

**Comment by anandthakker** [comment]
FWIW, :+1: on the `includeGeometry` option from this outside user's perspective :)

**Comment by tmcw** [comment]
Yep, for this usecase `includeGeometry` would do the trick - we don't need geometries in this UI.
