### ISSUE TITLE
Toggling different projections with setStyle overwrite projection in style

### ISSUE THREAD

**Issue by avpeery** [mapbox/mapbox-gl-js#11916]
**mapbox-gl-js version**: 2.9.0-beta.1

**browser**: Any

### Steps to Trigger Behavior

 1. Open the code pen below
 2. Upon map load, the two different styles are logged in the console correctly (style a is with `"projection": {"name": "winkelTripel"}`, and style b is with `"projection": {"name": "naturalEarth"}`
 3. Click the map to toggle from style a to style b and note in the console that the projection name in style a is overwritten to be "naturalEarth"

### Link to Demonstration

https://codepen.io/avpeery/pen/PoQjagb

### Expected Behavior

Style A should maintain projection name as "winkelTripel"

### Actual Behavior
Style A's projection name is overwritten to "naturalEarth"

**Comment by avpeery** [comment]
The source of this issue stems from this line of code: https://github.com/mapbox/mapbox-gl-js/pull/11204/files#diff-c19065149b8e6b02ea30bd2576429dfc2f917695da9382c77a6957401f6fef4eR347

Removing this line resolves this issue.

@ansis is it intended behavior to overwrite a projection in a style you want to toggle between?

**Comment by avpeery** [comment]
This [change](https://github.com/mapbox/mapbox-gl-js/pull/11204/files#diff-c19065149b8e6b02ea30bd2576429dfc2f917695da9382c77a6957401f6fef4eR347) also resulted in this issue #11553. Removing the same line resolves the error.

**Comment by SnailBones** [comment]
The issue seems to be resolved by avoiding calls to `setProjection`on style updates.

Fix here: https://github.com/mapbox/mapbox-gl-js/pull/11940/files
