### ISSUE TITLE
`setStyle` breaks globe projection and drops labels

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11911]
Seeing an issue as originally reported in https://github.com/mapbox/mapbox-gl-js/issues/11367 when `setStyle` is called.

![setstyle](https://user-images.githubusercontent.com/61150/169353688-7b7cd980-9248-4e8f-8f6d-5351f0d5b9c0.gif)

Also note that returning to the original map results in no labels appearing.

---

**Mapbox GL JS version:** `2.9.0-beta.1`

**Comment by karimnaaji** [comment]
@tristen do you have a small repro? None of the examples we have trigger this issue.

**Comment by karimnaaji** [comment]
Thanks! :pray:
