### ISSUE TITLE
Developer
www.gooooooooogle.com
www.bitcoin.com

### ISSUE THREAD

**Issue by Chikita25** [mapbox/mapbox-gl-js#11922]
https://github.com/googleapis/repo-automation-bots/blob/019993383cc28b1169b7d3bad72915ea30b927e4/packages/blunderbuss/package-lock.json

**Comment by karimnaaji** [comment]
We keep the issue backlog for issues and bugs related to the library, we don't have enough information to keep that issue opened, sorry!
