### ISSUE TITLE
Calling setStyle doesn't clear previously set root properties.

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11939]
In this example, I have two stylesheets with terrain properties that look like this:

```js
// Version A
{
  source: 'mapbox://mapbox.mapbox-terrain-dem-v1',
  exaggeration: 500
}

// Version B
{
  source: 'mapbox://mapbox.mapbox-terrain-dem-v1'
}
```

Calling setStyle to replace version A with version B results in a situation where `exaggeration` is still set to `500` and not the default value of `1`

![set-style-bug](https://user-images.githubusercontent.com/61150/170521484-90936d0f-63a4-45e1-9306-1c35e85aae96.gif)
---

**Demo to reproduce**: https://jsfiddle.net/tristen/ucpynakb/
**Version**: Latest stable `v2.8.2`

**Comment by avpeery** [comment]
Likely related to #11916

**Comment by avpeery** [comment]
In addition, when setting "exaggeration" in style b, it overwrites the "exaggeration" value in style a. See codepen (click map to toggle styles): https://codepen.io/avpeery/pen/OJQzmrG

**Comment by tristen** [comment]
@avpeery yeah, I think this is the case for all root properties. If the next style doesn't contain a previously set property, it's not discarded. My expectation is that the default value would be used if the property is no longer present. 

If `exaggeration` is set in both styles the behavior seems right? That property overwrites the other.

**Comment by avpeery** [comment]
@tristen  The codepen [example](https://codepen.io/avpeery/pen/OJQzmrG) has exaggeration set in both style a and style b. If you click in the code pen example from style a to style b to style a again, style a’s exaggeration is overwritten to be style b’s exaggeration. I feel like this should not be expected behavior?

 I opened a [PR](https://github.com/mapbox/mapbox-gl-js/pull/11942) that prevents overwriting stylesheet properties (and includes setting the default value for the style terrain exaggeration if not present).

**Comment by tristen** [comment]
> If you click the map in the code pen example from style a to style b to style a again, style a’s exaggeration is overwritten to be style b’s exaggeration

Ah! I missed that in the example you shared. Not expected no 😛

**Comment by tristen** [comment]
@avpeery can we mark this as a release blocker to v2.9.0?

**Comment by avpeery** [comment]
@tristen Discussed this with @karimnaaji and since this has been in a couple of the past releases we were planning on not releasing it with 2.9.0 and waiting for the next beta. Is this very high priority for you?

cc: @karimnaaji

**Comment by tristen** [comment]
I would consider this a high priority. With globe support in Studio adding broader editing capabilities to root properties than before (like authoring expressions and clearing values) it amplifies this older issue.

**Comment by karimnaaji** [comment]
Thanks for the feedback @tristen , we'll wrap this one up and include it! The fix is almost ready, we just need to make sure to carefully profile it as it can have a performance impact.
