### ISSUE TITLE
Will Globe projection eventually support fitBounds API?

### ISSUE THREAD

**Issue by joshkautz** [mapbox/mapbox-gl-js#11938]
**mapbox-gl-js version**:

### Question

I am testing out **2.9.0-beta.1** (which is awesome, thank you for the hard work). I have using the _globe_ projection mode, and I've noticed that when I'm zoomed out far enough that _mercator_ mode isn't being used, the fitBounds() method does not work. I receive a warning in the console that says "Globe projection does not support fitBounds API." I don't want to report this as an issue or a bug since it successfully throws a warning; I'm assuming that this is a feature that the team would like to implement in the future, but I want to see if there is anything for this on the roadmap.

**Comment by avpeery** [comment]
Hi @joshkautz - Yes, Globe does not support fitBounds API. While globe support for fitBounds will not be available in the immediate future, we will update you on this issue when it becomes available. Thanks for using Mapbox!

**Comment by joshkautz** [comment]
Fantastic. Thank you - looking forward to enjoying the Globe projection in the meanwhile!

**Comment by joshkautz** [comment]
This appears to be handled with the new minor version release of 2.9.X! Great work - Thank you!
