### ISSUE TITLE
Mapbox Globe atmosphere style

### ISSUE THREAD

**Issue by Philip2809** [mapbox/mapbox-gl-js#11934]
Hello! I just found out that I can use a globe projection for my mapbox map and I have enabled it, using the beta version and projection set to globe. My question is how do I change the background or "atmosphere" as showed in the issue that demonstrated the globe (will link when I have found it again)?

My other question is will there be a fitbounds for this globe view?

Edit: #10784 is the issue I am taking about. 

I would like to know how to set these: 
![IMG_20220525_171212.jpg](https://user-images.githubusercontent.com/51290462/170296716-4b75b9ca-4571-4c37-9da0-dbc5311e52ab.jpg)
Image taken from that issue. 

Best regards
Philiip

**Comment by Philip2809** [comment]
I have tried to use the following guide to no avail:
https://docs.mapbox.com/mapbox-gl-js/example/gradient-sky/

**Comment by avpeery** [comment]
Hey @Philip2809, you can change/set atmosphere styling with 'fog' either in the style or with calling the `setFog` api (e.g. `map.setFog({});`). 

Fog properties that affect atmosphere are the following: [`range`](https://docs.mapbox.com/mapbox-gl-js/style-spec/fog/#range), [`horizon-blend`](https://docs.mapbox.com/mapbox-gl-js/style-spec/fog/#horizon-blend), [`color`](https://docs.mapbox.com/mapbox-gl-js/style-spec/fog/#color), and then three new properties (documentation to follow):`high-color`, `space-color`, and `star-intensity` 

Here is [a codepen example](https://codepen.io/avpeery/pen/eYVeKVB) of atmosphere to experiment with the different properties to see how they change they style. The default style on this example is:
`map.setFog({ 
        'range': [0.8, 8],
        'color': 'rgba(220, 159, 159, 1)',
        'horizon-blend': 0.5,
        'high-color': 'rgba(36, 92, 223, 0.7)',
        'space-color': 'rgba(0, 0, 0, 1.0)',
        'star-intensity': 0.15
});`

Hope this helps! Thanks for using Mapbox!
