### ISSUE TITLE
Invalid LngLat object: (NaN, NaN) with certain padding values

### ISSUE THREAD

**Issue by kpagcha** [mapbox/mapbox-gl-js#11935]
I got the following error `Invalid LngLat object: (NaN, NaN)` when initializing the map

I eventually found out it's introduced when inceasing the padding. I get the error with a padding of 150 but not when its value is 50.

**mapbox-gl-js version**:

2.8.2

**browser**:

Firefox 100.0.2

### Steps to Trigger Behavior

Setting `fitBoundsOptions: {padding: 150}`

### Link to Demonstration

```
const map = new mapboxgl.Map({
    container: "map",
    style: "mapbox://styles/mapbox/streets-v11",
    bounds: [{
        "lng": -103.397541,
        "lat": 20.299775
    }, {
        "lng": -101.25058,
        "lat": 21.008076
    }],
    fitBoundsOptions: {
        padding: 150
    }
});
```

### Expected Behavior

The map should be rendered.

### Actual Behavior

An error is thrown and the map is not rendered.

**Comment by avpeery** [comment]
Hi @kpagcha, do you have css set for the map height in your example? I tested out the example you provided and receive the same error when I do not set the css for height. However, when I set the css as the following the map loads and no issues. Please let me know if this does not resolve the reported error. Thanks for using Mapbox!
```
    <style>
        html, body, #map { height: 100%; }
    </style>
```

**Comment by kpagcha** [comment]
@avpeery yes, `#map` has a set height of 100%. And I'm still getting that error.

Also please check [this other issue ](https://github.com/mapbox/mapbox-gl-js/issues/11905)I opened. It's a really bad one. I'm a paying customer but getting a blurry map.

**Comment by avpeery** [comment]
Hi @kpagcha will take a look at #11905 - thanks for opening a ticket! 

Since I able to resolve the problem with the code you provided by setting the height, there may be something else at play. To help the maintainers address the problem accurately can you please provide a minimal code reproduction of the issue on https://jsbin.com/? Thanks again.
