### ISSUE TITLE
gl-js master keeps requesting favicon on map move

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1194]
Not sure if this is a GL bug, but all maps running gl-js `master` are trying to retrieve `favicon.ico` on every zoom and pan:

![screen shot 2015-04-29 at 2 44 06 pm](https://cloud.githubusercontent.com/assets/4551508/7402126/529a1398-ee7e-11e4-86ce-1dcc062d40a8.png)

 it's aborting `.flyTo()` animations midflight, as well

cc/ @ansis @jfirebaugh

**Comment by mourner** [comment]
I don't see that on the debug page (`localhost:1337/debug/index.html`) — does it reproduce for you?

**Comment by mikemorris** [comment]
I'm seeing the 403 on initial page loads from `bites` too.

**Comment by peterqliu** [comment]
@mourner it doesn't reproduce in any local environment, for me. Here's a test case where it [does happen](https://www.mapbox.com/bites/00108/#6.87/39.570/-76.103), and one where [it doesn't](https://www.mapbox.com/bites/00118/#5.34/38.440/-76.706) (uses v7 instead of master)

**Comment by samanpwbb** [comment]
heh, https://github.com/mapbox/bites/commit/cf091fd5646efb3b7aa841b102a1ca98dfbf5d5e

**Comment by peterqliu** [comment]
@samanpwbb hmm, that does look related but the issue persists both in /00116 and /00108, which [doesn't have the link at all](https://github.com/mapbox/bites/blob/mb-pages/00108/index.html)

**Comment by jfirebaugh** [comment]
I don't think this is related to gl-js.

**Comment by adamb70** [comment]
I was running into this same issue with v1.1.1, but only when the favicon url and my map marker css `background-image` url are the same. It happens both locally and on a heroku server.

I couldn't get it to occur in CodePen, but it happens in [this html file](https://pastebin.com/1P37CPeC). If it doesn't work on the first load, try refreshing the page and it should happen.
