### ISSUE TITLE
Make collision detection take into account "text-offset" and size changes

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1196]
In the Y direction, the symbol simply outruns its bounding box. Looking at `France`, going from [0,-10] to [0,0] to [0,10]:

![offsety](https://cloud.githubusercontent.com/assets/4551508/7436445/a63c2d08-f002-11e4-8eeb-0c5f0d89b087.gif)

In the X direction... it's bizarre. Looks like the box both scales and shifts. Going from [-10,0] to [0,0] to [10,0]:

![offsetx](https://cloud.githubusercontent.com/assets/4551508/7436482/fbff4054-f002-11e4-9ac9-8a0183829344.gif)

cc/ @ansis

**Comment by peterqliu** [comment]
this case was found in https://www.mapbox.com/bites/00108, but reproducible anywhere.

**Comment by jfirebaugh** [comment]
@ChrisLoer @ansis Is this fixed with recent text rendering changes?

**Comment by ChrisLoer** [comment]
Plain offsets are handled correctly now (watch Washington DC offset in both X and Y directions):

![offset dc 2](https://user-images.githubusercontent.com/375121/28805074-3b63cf8e-761c-11e7-9401-d9c1a53bb9d7.gif)

But for zoom-interpolated values the collision box can still end up looking different than the label:

![zoom interpolation still off](https://user-images.githubusercontent.com/375121/28805113-80a359d4-761c-11e7-86c3-4287ab06514d.gif)

**Comment by jfirebaugh** [comment]
→ #4798
