### ISSUE TITLE
House numbers in mapbox gl?

### ISSUE THREAD

**Issue by crippe-90** [mapbox/mapbox-gl-js#11966]
**mapbox-gl-js version**: 2.6.1

### Question
How do I show house numbers in a mapbox-gl-js map? 
According to the link it should be possible, but for some reason it does not show up. The link is a few years old however, but I did try with some older versions of the style as well.

### Links to related documentation
https://github.com/mapbox/mapbox-gl-styles/issues/271

**Comment by stepankuzmin** [comment]
Hi, @crippe-90

Yes, there are house numbers, e.g., `housenum_label` in [mapbox-streets](https://docs.mapbox.com/data/tilesets/reference/mapbox-streets-v8/#housenum_label) dataset. However, the house numbers have the min zoom level set to 16 for performance reasons.

If you have your dataset, you can also use the [Mapbox Tiling Service](https://docs.mapbox.com/mapbox-tiling-service/guides/) to create your tileset with the house numbers and use it in your style with Mapbox GL JS.

This issue tracker is for reporting bugs and feature requests in GL JS. For future questions like this, you can refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). 

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.

**Comment by alamenai** [comment]
I made it like this : 


```ts

 map.on("load", () => {

 map.addLayer({
        id: "building-numbers",
        type: "symbol",
        source: {
          type: "vector",
          url: "mapbox://mapbox.mapbox-streets-v8",
        },
        "source-layer": "housenum_label",
        layout: {
          "text-field": ["get", "house_num"],
          "text-size": 16,
          "text-anchor": "center",
          "text-allow-overlap": false,
          "text-cursor": "pointer", // Change cursor to pointer on hover
        },
        paint: {
          "text-color": "#000000",
          "text-halo-color": "#ffffff",
          "text-halo-width": 2,
        },
      })
    })

})
 
```

![Image](https://github.com/user-attachments/assets/5d7af121-d1a0-4a89-9afa-400a57e03a12)
