### ISSUE TITLE
Inconsistent fog styling after toggling between styles

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#11978]
Here are two styles with different fog properties:

```js
// Style A
fog: {
  color: 'red'
};
```

```js
// Style B

fog: {
  color: '#0F2127',
  'high-color': '#000',
  'horizon-blend': 0.5,
  'space-color': '#000'
};
```

It looks like when after you call `setStyle` again, default values (i.e. `high-color`) are dropped:

![fog](https://user-images.githubusercontent.com/61150/172939853-eef863ca-0d1d-4769-b2c1-5895e25d86a0.gif)

---

**Example**: https://jsfiddle.net/tristen/fx3L9jk0/
**Mapbox GL Version**: `v2.9.0-beta.2`

**Comment by tristen** [comment]
Come to think of it, if I have implicitly set

```js
fog: {
  color: 'red'
};
```

I don't think I'd expect styling for `space-color`, `high-color` etc to appear.

**Comment by karimnaaji** [comment]
@avpeery shouldn't style persistence be fixed by https://github.com/mapbox/mapbox-gl-js/pull/11942? Or is there something that was missed from the fix?

**Comment by avpeery** [comment]
In the terrain instance, the updating code path did not check for default values, so that was specifically addressed [here](https://github.com/mapbox/mapbox-gl-js/blob/a8de205d8bce3a1e50478e19a6e8d94aae0bca6f/src/style/style.js#L1499). There are probably other code paths that aren't checking for default values when it is an update, so I can make this fix and look into any other areas that may not be updating default values

**Comment by avpeery** [comment]
Hey @tristen, I have a fix for this that will use the default values of fog if it's not being set in the style, even when toggling between styles it'll replace the old style with the default value if not set in the new style. Just double checking this is behavior you would expect in regards to this comment? https://github.com/mapbox/mapbox-gl-js/issues/11978#issuecomment-1151603710

**Comment by tristen** [comment]
oh yeah @avpeery I suppose the behavior should match how other root properties work today (like `light`). https://github.com/mapbox/mapbox-gl-js/issues/11978#issuecomment-1151603710 probably doesn't make sense :p

**Comment by avpeery** [comment]
Ok Thanks @tristen it looks like calling `map.setLight` without all the properties will replace all property values with the default values over maintaining the property values of a previous `map.setLight` call. Let me know this makes sense to you! cc @karimnaaji
