### ISSUE TITLE
Draping artifacts on ocean tiles

### ISSUE THREAD

**Issue by SnailBones** [mapbox/mapbox-gl-js#11975]
With globe or terrain enabled, trianglular artifacts appear in specific locations between zoom levels 5 and six. This occurs with the tile 5/27/14.

 1.  Go to http://localhost:9966/debug/projections.html#5.5/19/125
 2. Enable globe OR terrain.

![image](https://user-images.githubusercontent.com/14878684/172932659-24247158-2828-4cb5-9309-394d62def455.png)

Acceptance Criteria:

These artifacts should no longer appear and be verified with a render test.

**Comment by SnailBones** [comment]
This bug can also be seen above Alaska on tile 5/2/6, which can be viewed with http://localhost:9966/debug/projections.html#5.41/71.852/-153.459/-28/59.

![image](https://user-images.githubusercontent.com/14878684/172947508-9df27cd3-7868-4a98-be9c-c8327f37725c.png)

Both of these cases are tiles with some land in the SW quadrant and are otherwise ocean.

This probably occurs in more tiles in other (especially higher) zoom levels. I've noticed these in zoom 5 as I'm working on an unrelated globe-to-Mercator transition bug.

**Comment by SnailBones** [comment]
This is also occurring off the US southeast coast on tile 5/9/13
![image](https://user-images.githubusercontent.com/14878684/178360751-818448d9-7a3b-4076-9ab3-c34ec69248d1.png)

**Comment by mourner** [comment]
@SnailBones are you still able to reproduce this? I tried but couldn't on all the examples above. I wonder if this is something environment-specific that's not reproducible on my machine/browser, or if it was a bug on the Streets data side that got hot-patched.

**Comment by SnailBones** [comment]
@mourner Yes, just tested again and I'm still seeing this bug. I'm seeing it in Chrome, Safari, and Firefox and MacOS (Intel chip), Windows and Linux machines.

**Comment by mourner** [comment]
@SnailBones that's so weird! Will have to unassign myself for now since I can't manage to reproduce...

**Comment by stepankuzmin** [comment]
I also couldn't reproduce this in Chrome, Safari, and Firefox on macOS (Apple chip) with globe or terrain.

**Comment by karimnaaji** [comment]
Reopening, refer https://github.com/mapbox/mapbox-gl-js/pull/12203#issuecomment-1233307545

**Comment by SnailBones** [comment]
@stepankuzmin Thanks for the nice reproduction! I'm able to reproduce it in all of the locations with your jsfiddle.

**Comment by avpeery** [comment]
Taking a stab at this issue as I can reproduce it consistently (macbook pro, monterey 12.6, intel processor).  I checked out the previous fix that was reverted: [#12203](https://github.com/mapbox/mapbox-gl-js/pull/12203) which resolves the issue on my machine. Does this solution still make the issue appear for you @karimnaaji? If so, what are the details of your machine?

**Comment by karimnaaji** [comment]
>Does this solution still make the issue appear for you @karimnaaji?

Responded on the PR: https://github.com/mapbox/mapbox-gl-js/pull/12279#issuecomment-1275044877
