### ISSUE TITLE
When you add the WMS service in frame 3857 using GeoJSON, the pipes rendered on the map will be clipped 

### ISSUE THREAD

**Issue by zhangjiagithub** [mapbox/mapbox-gl-js#11989]
**mapbox-gl-js version**:mapbox-gl.js v1.1.1

### Expected Behavior

![image](https://user-images.githubusercontent.com/48313333/173314551-0e4fa3f2-89cb-4e5d-a303-d8669dce48b3.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/48313333/173314718-e5d488fc-9c43-447c-9bb0-e9596c3ebb43.png)

### Loading methods
![image](https://user-images.githubusercontent.com/48313333/173315878-2c7a4917-aab1-423c-abc8-c885e30ec60e.png)

**Comment by mourner** [comment]
You might try setting a higher max zoom for the source — e.g. `maxzoom: 22`, but if it doesn't fix this, it looks more like a server problem than anything to do with GL JS, and you'd report there. Can't diagnose for sure since there's no live test case.
