### ISSUE TITLE
Setting map collision debug mode when there's a raster layer breaks

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1198]
Not all sources have a .reload() method, but we call it regardless here: https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/map.js#L830

Needs to check that the source has reload, or the sources should all support reload.

**Comment by tmcw** [comment]
So there are a bunch of other places we also call source.reload() and these break raster sources accordingly

https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style.js#L373

We either need to guard against every place we call .reload, or implement reload on every source. I'm leaning toward the latter.

**Comment by jfirebaugh** [comment]
> I'm leaning toward the latter.

Yeah, agreed.

**Comment by scothis** [comment]
Video sources also do not currently have a reload method. I'm debating between refetching the video source and a no-op. Opinions?

**Comment by jfirebaugh** [comment]
The purpose of `reload` is to trigger a re-evaluation of the layout information for the source. Layout information includes all the things that are calculated by the tile workers:

* layout properties (other than `visibility`)
* the result of applying a filter to the layer's features
* label placement and associated collision information

Video sources don't have any of those things, so their reload should be a no-op.

**Comment by scothis** [comment]
Put up a PR to add a reload method to all sources and deal with a couple related issues I saw while testing the change. I didn't pull out the previous guard logic, but can if you'd like.

**Comment by scothis** [comment]
fixed with #1252
