### ISSUE TITLE
Bug: `id: 0` value not handled correctly by `match` expression

### ISSUE THREAD

**Issue by straight-shoota** [mapbox/mapbox-gl-js#11994]
**mapbox-gl-js version**: 2.8.2

**browser**: Firefox

### Steps to Trigger Behavior

 1. Have a GeoJSON source with a feature with `id: 0` (this happens with `generateId: true`, for example).
 ```json
{
   "id": 0,
   "type": "Feature",
   "geometry": {
     "type": "Point",
     "coordinates": [-77.038659, 38.931567]
}
```
 3. Use a `match` expression with the feature id (`["id"]`) as input value and a label value `0`. 
 ```json
"layout": {
    "icon-image": [
      "match",
      ["id"],
      0,
      "theatre-15",
      "music-15"
    ],
    "icon-size": 2
  },
```

### Link to Demonstration

https://codepen.io/straight-shoota-the-reactor/full/ZErwjRy

### Expected Behavior

The label `0` should match for the feature with `id: 0` and apply the associated output value (`theatre-15` in the example).

![grafik](https://user-images.githubusercontent.com/466378/173807493-cc2d2de6-8fd3-4ac0-a474-4490d68cd921.png)

This works with a non-zero id.

It also works when the input value is a literal `0` instead of `["id"]`.

### Actual Behavior

The label `0` does not match for the feature with `id: 0`. Instead, the fallback branch is used (`music-15` in the example).

![grafik](https://user-images.githubusercontent.com/466378/173807177-55912714-bd54-448b-a047-1acd281343ec.png)

Related issues:
* #7166
*  #8293

**Comment by mourner** [comment]
Nice catch! It appears that the bug affects not just `match` but the `id` expression in general, and it slipped past me in #11602 (cc @stepankuzmin). Here's the offending change, likely made to satisfy Flow but effectively returning `null` when the value is `0`:

<img width="844" alt="image" src="https://user-images.githubusercontent.com/25395/173873305-87c0e836-1b76-423f-866e-d0b8cf8464f8.png">

Will submit a fix shortly.
