### ISSUE TITLE
Buggy when used besides (multiple) other canvas on the same page

### ISSUE THREAD

**Issue by felix-mittermeier** [mapbox/mapbox-gl-js#11998]
Hi there, we have kind of big issue with the javascript mapbox version and are basically stuck for weeks/months now on this topic. That's why we wanted to reach out to the maintainers/experts of this if you could help us with some fresh ideas etc.

So it's about using the Mapbox javascript version with Flutter for web (https://pub.dev/packages/mapbox_gl). The native plugins (iOS + Android) work like they should but with the Web variant we constantly have this issue:

We are using multiple maps on different pages in the app so there are multiple instances of it. What often happens for example is when going from the first page with a map to the second page with another map and then going back, the first original map is broken. So either the map is rendered only at a small square (default size from here: https://github.com/mapbox/mapbox-gl-js/blob/v0.42.2/src/ui/map.js#L1317) and the remaining area is just grey or (and the second issue is way more drastic actually) the map is not rendered at all and only a small error icon is shown in the top left corner. At this point the only way to get the map interactive again is to reload the whole page which is of course quite a bad user experience. In some cases it also happened without even going to another page and just by resizing the browser window.

Screenshot of the second issue:

![image](https://user-images.githubusercontent.com/100692288/173855176-4ecfae1a-5219-43f5-8b06-f131e11105f9.png)

The development console prints out statements like:<br/>

`Too many active WebGL contexts. Oldest context will be lost.`

combined with:

`WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use`

Sometimes also:

```
WebGL warning: deleteTexture: `obj` is from a different (or lost) WebGL context. 3 [canvaskit.js:231:489]
WebGL warning: deleteBuffer: `obj` is from a different (or lost) WebGL context. 2 [canvaskit.js:230:277]
WebGL warning: deleteFramebuffer: `obj` is from a different (or lost) WebGL context. [canvaskit.js:230:422]
WebGL warning: deleteTexture: `obj` is from a different (or lost) WebGL context. 2 [canvaskit.js:231:489]
WebGL warning: deleteProgram: `obj` is from a different (or lost) WebGL context.
```

It looks like this could be related to slow computing power + large screens but we are not able to find a case that consistently reproduces this. Its more like "there it happens way more often". On fast M1 Macs we nearly don't have this issue at all and only sometimes. Looks like a browser independent issue because this happened on Chrome, Firefox as well as Safari.

We are also using multiple `PointerInterceptors` (https://pub.dev/packages/pointer_interceptor) which each creates a new platform view (https://docs.flutter.dev/development/platform-integration/android/platform-views). I am not 100% sure but this might relate to this as written here: https://github.com/flutter/flutter/issues/50719#issuecomment-585942663

And because the count of WebGl-Contexts is limited, combined with the whole Flutter canvas itself, this might exceed the limit mentioned here: https://codereview.chromium.org/14217005/#ps51001

What I came over while investigating: https://github.com/greggman/virtual-webgl maybe something like would also make sense for MapBox.

Any help would be much appreciated. Thank you

**Comment by mourner** [comment]
If this error happens because there are indeed too many active WebGL contexts due to many instantiated maps or other WebGL canvases, there's no way for GL JS to control this at the library level. However, what you can do is try to make sure the number of contexts never grows without limit (e.g. switching between pages). There are to ways to do it with GL JS:

1. Reuse the same map instance when switching to a different page (storing the map state of each page and setting the map instance to it on switch).
2. When navigating away from a page, make sure `map.remove()` is called, and reinstantiate the map from scratch when navigating back.

Internally, GL JS uses this bit of code to mark it's get rid of the active WebGL context when it's removed, and you can use the same code for other WebGL canvases:

https://github.com/mapbox/mapbox-gl-js/blob/83881c4f1a3815cfaaaf3116727365f380c909b4/src/ui/map.js#L3442-L3443

I'll close the issue for now, but let me reopen it if there's a way we could help with this problem on our side.

**Comment by felix-mittermeier** [comment]
@mourner Hi there again, so I did more research on this topic and the second solution you proposed did not work out because `map.remove()` is already called like it should after leaving the second page. And also the call to lose the WebGl context is triggered but for some reasons this still does not clear the context from memory in Safari and it just works in Google Chrome for example. There is bug report for WebKit for this here: https://bugs.webkit.org/show_bug.cgi?id=218305

A minimum reproducible CodePen example demonstrates the issue again: https://codepen.io/philipbell/pen/RwRQGmo -> this works fine on Chrome but not on Safari.

Can you provide more information how the first proposed solution would work? I am not sure how it's possible to reuse the same map instance when combined with Flutter. Thanks
