### ISSUE TITLE
Popup examples are blank in Firefox

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#1201]
The “[Popup](https://www.mapbox.com/mapbox-gl-js/example/popup/)” and “[Popup on click](https://www.mapbox.com/mapbox-gl-js/example/popup-on-click/)” examples have blank maps in Firefox 39. Safari 8.0 is unaffected.

**Comment by 1ec5** [comment]
The map shows up if I visit a page without a map, such as [the overview page](https://www.mapbox.com/mapbox-gl/), then return to the example page (thereby loading the map from Firefox’s BFCache).

**Comment by jfirebaugh** [comment]
These examples are working in FF 38, the currently released version, so I'm inclined to attribute this to a FF regression.

**Comment by 1ec5** [comment]
It’s also showing up fine in 40.0a2 (2015-05-27).
