### ISSUE TITLE
Safari exceptions < 14.1 with NumberFormat

### ISSUE THREAD

**Issue by leigeber** [mapbox/mapbox-gl-js#12021]
In what I believe would be supported Safari versions, we're seeing many exceptions logged with 2.9.0. Before Safari 14.1 Intl.NumberFormat() didn't support a "style" value of "unit" from what I understand. This appears to be impacting the scale control.

Looks like it happened with this: https://github.com/mapbox/mapbox-gl-js/pull/11850

**mapbox-gl-js version**: 2.9.0

**browser**: Safari 14.0

**Comment by stepankuzmin** [comment]
Hi @leigeber, thanks for filling the issue for this.

**Comment by vandres** [comment]
Also getting this error after an update from 2.8.2 to 2.9.1
