### ISSUE TITLE
Vector tiles (by url) not visible in 2.9.0!

### ISSUE THREAD

**Issue by fr-an-k** [mapbox/mapbox-gl-js#12023]
When I switched to 2.9.0 production version, some vector tile url sources were no longer visible (while others were visble, using a TileJSON for source layer redefinitions).

I also still have this tile flickering issue: #12024

**mapbox-gl-js version**:
2.9.0 (https://cdn.jsdelivr.net/npm/mapbox-gl@2.9.0/dist/mapbox-gl.min.js)

**browser**:
Chrome Version 102.0.5005.115 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Add vector tile source (tiles url) and layer(s)
 2. You can queryRenderedFeatures but no features are displayed

It's quite possible that only lines are affected.

### Expected Behavior
Work as documented, i.e. display features.

### Actual Behavior
No features visible; this issue does not occur when switching to 2.7.0

**Comment by stepankuzmin** [comment]
Hi @fr-an-k,

This is most likely related to the https://github.com/mapbox/mapbox-gl-js/issues/12013. We've released [v2.9.1](https://github.com/mapbox/mapbox-gl-js/releases/tag/v2.9.1), which fixes this issue.
You can reopen this issue if you have any questions.
