### ISSUE TITLE
GeoJSON polygon rendering is sensitive to ring winding order

### ISSUE THREAD

**Issue by MelnikVasya** [mapbox/mapbox-gl-js#1202]
I add geojson to map https://jsfiddle.net/v0best2f/1/ and hole is filled 
http://geojsonlint.com/
![screen shot 2015-05-12 at 4 24 40 pm](https://cloud.githubusercontent.com/assets/5058192/7588095/6fbe8e28-f8c3-11e4-8af8-4bd904980f32.png)
mapbox-gl
![screen shot 2015-05-12 at 4 25 47 pm](https://cloud.githubusercontent.com/assets/5058192/7588121/9900f352-f8c3-11e4-9db4-163cfdf53953.png)

**Comment by mourner** [comment]
Thanks, we'll look into this.

**Comment by mourner** [comment]
OK found the issue. Apparently our GeoJSON implementation is sensitive to winding order. If you reverse the order of the second ring like here https://jsfiddle.net/v0best2f/3/, it works properly.

We can fix this pretty easily on mapbox-gl-js side, although the fix will become obsolete after #682 where this is handled differently.

**Comment by ansis** [comment]
This is fixed by https://github.com/mapbox/mapbox-gl-js/pull/2285
