### ISSUE TITLE
Tiles not drawn when other tiles have CORS errors

### ISSUE THREAD

**Issue by fr-an-k** [mapbox/mapbox-gl-js#12024]
**mapbox-gl-js version**:
All 2.x versions up to 2.9.0

**browser**:
Chrome Version 102.0.5005.115 (Official Build) (64-bit)

### Steps to Trigger Behavior
Happens regularly in vector tile sources.

### Screenshot
![mapbox_issue](https://user-images.githubusercontent.com/60439693/174781787-882bf0a5-e95e-405a-9f20-0c0fb2d2815e.gif)

### Expected Behavior
Show my tiles

### Actual Behavior
Tiles disappear when moving left beyond a certain x coordinate.

**Comment by stepankuzmin** [comment]
Hi @fr-an-k,

Could you please provide more details about your environment (OS), whether this happens in all browsers or just one, are there any warnings in the console, etc.?

**Comment by fr-an-k** [comment]
Same happens in Firefox and Edge except in these instance the tiles appear when going to the left; I suspect a shader issue.

Windows 11 Pro 21H2, build 22000.739
Intel i7, 32GB RAM
Intel UHD graphics 630
NVIDIA Quadro P600 (probably not used for the browser)

**Comment by fr-an-k** [comment]
Oh wait I do get errors; the tiles don't exist and as a consequence return HTTP status code 403 (forbidden). Sorry about that, I'll have to investigate this further myself.

**Comment by fr-an-k** [comment]
It was a CORS issue (fetch exception) that probably blocked an internal tile callback.
Technically it's an issue in Mapbox, but you can close this case if you don't support CORS handling.

I solved it with a hack ( custom source type, overriding some internal Mapbox class); unfortunately it's still not 100%, I suspect a cancelled tile is being cached as a missing tile and therefore not reloaded when visiting the area again. Probably due to my limited knowledge of the Mapbox internals.

Ideally Mapbox would decouple HTTP from the tile mapping system and allow a custom tile blob loader. The use case for this would be offline functionality and client-side image processing, without resorting to a hack or service worker (which does not implement the cancel signal and therefore causes onworkable map stuttering).

**Comment by stepankuzmin** [comment]
Thanks for the feedback, @fr-an-k 

We have an experimental Custom Source API that decouples data fetching from the tiling. You can try this example https://github.com/mapbox/mapbox-gl-js/blob/80e5afd1babdac879cc63dfd2abab4c3bc760837/debug/custom-source.html.
