### ISSUE TITLE
Marker movement example in mapbox-gl-js?

### ISSUE THREAD

**Issue by hanfeisun** [mapbox/mapbox-gl-js#1203]
In mapbox.js, I found a good example for marker movement at: https://www.mapbox.com/mapbox.js/example/v1.0.0/marker-movement/

However, in mapbox-gl-js, I can only find a example to add markers from a GeoJSON file. 
https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/

It seems that the marker methods (setLatLng) in mapbox.js doesn't exist in mapbox-gl-js..

Is it possible to implement marker movement in mapbox-gl-js?

**Comment by mourner** [comment]
You can do the same by changing the coordinates in the GeoJSON in place, then calling `source.setData(geojson)`. It's reasonably fast for real-time updates.

**Comment by jfirebaugh** [comment]
⇢ #1518.
