### ISSUE TITLE
North pole cap and Greenland have holes with exaggerated extrusions

### ISSUE THREAD

**Issue by AlexanderBelokon** [mapbox/mapbox-gl-js#12037]
**mapbox-gl-js version**: 2.9.1

**browser**: Firefox 101.0.1

### Steps to Trigger Behavior

 1. Login to [Studio](https://studio.mapbox.com)
 1. Create a new style (with `globe` projection by default)
 1. `3D -> 3D Terrain -> Enable terrain -> On`
 1. `3D -> 3D Terrain -> Exagerration -> 1000`
 1. Look at the area around the pole, slightly moving the viewport back and forth
 1. Notice that Greenland sometimes appears to have a hole in it, possibly when a specific tile is used for a part of it
 1. Notice that the polar cap moves further inside the globe when exaggeration is increased

### Link to Demonstration

[Shared style](https://api.mapbox.com/styles/v1/testy-user/cl4rd3chd000u15lk13a6sg0e.html?title=view&access_token=pk.eyJ1IjoidGVzdHktdXNlciIsImEiOiJjbDRyZDMyOTQwNTNzM2NvNjF3dmc1dGNmIn0.sRrT87LpCL7kd6XivEnkxg&zoomwheel=true&fresh=true#3.2/61.25/-16.01)

![holy-pole](https://user-images.githubusercontent.com/2198527/175382528-b9a65424-80f8-4853-be2c-f7811f023934.png)

![pole-hole](https://user-images.githubusercontent.com/2198527/175382739-91264268-7595-4dcc-97f4-d00d49c5b801.png)

https://user-images.githubusercontent.com/2198527/175383574-88e05138-303d-449b-a4cf-39c7d22e83d3.mp4

https://user-images.githubusercontent.com/2198527/175384583-825fa272-4b53-4938-b2e8-80506d3523b2.mp4

### Expected Behavior

Globe does not have holes

### Actual Behavior

Globe has holes

**Comment by AlexanderBelokon** [comment]
I noticed that even without exaggerated terrain (and even without any extrusions at all) the seams that are apparent here (around the polar cap and above iceland) are sometimes visible as hairlines, sometimes only a few transparent dots here and there, sometimes as almost complete single-pixel transparent lines. Extrusions just make them easier to notice.

https://user-images.githubusercontent.com/2198527/175432229-6b3b6be3-32f0-44f9-a215-d2264f769189.mp4

**Comment by SnailBones** [comment]
> I noticed that even without exaggerated terrain (and even without any extrusions at all) the seams that are apparent here (around the polar cap and above iceland) are sometimes visible as hairlines, sometimes only a few transparent dots here and there, sometimes as almost complete single-pixel transparent lines. Extrusions just make them easier to notice.

This looks like https://github.com/mapbox/mapbox-gl-js/issues/11858, good to note that the issue is heightened with terrain.

**Comment by AlexanderBelokon** [comment]
I think this issue is a result of two problems:

1) When creating tiles for greenlandish latitudes, normals for boundary points are calculated without taking into account neighboring tiles, making them too perpendicular to the globe, and as a result, accumulating errors with any exagerration.
This might be fixed if we take more points on the other side of the tile into accont and make sure that normals on both sides of the tile boundary are pointing in the same direction.

2) When creating the cap for the pole, the cap's origin is located somewhere close to the pole, and to make it aligned with the rest of the sphere it is given a slight negative altitude that is amplified by the exagerration. This may be fixed if we move the origin for each of the cap's triangles to the outer rim of the cap, making negative altitude unnecessary.
