### ISSUE TITLE
Radius of globe shrinks while extrusions from missing parts are still visible

### ISSUE THREAD

**Issue by AlexanderBelokon** [mapbox/mapbox-gl-js#12038]
Maybe the back clip plane is moving too close to the camera?

**mapbox-gl-js version**: 2.9.1

**browser**: Firefox 101.0.1

### Steps to Trigger Behavior

 1. Login to [Studio](https://studio.mapbox.com)
 1. Create a new style (with `globe` projection by default)
 1. `3D -> 3D Terrain -> Enable terrain -> On`
 1. `3D -> 3D Terrain -> Exagerration -> 1000`
 1. Play with viewport until you break it in a way similar to the video
 1. Notice that Earth's radius is oscillating

### Link to Demonstration

[Shared style](https://api.mapbox.com/styles/v1/testy-user/cl4rd3chd000u15lk13a6sg0e.html?title=view&access_token=pk.eyJ1IjoidGVzdHktdXNlciIsImEiOiJjbDRyZDMyOTQwNTNzM2NvNjF3dmc1dGNmIn0.sRrT87LpCL7kd6XivEnkxg&zoomwheel=true&fresh=true#3.2/61.25/-16.01)

![asteroids](https://user-images.githubusercontent.com/2198527/175385394-3cd308cb-0920-4eaf-9f0f-744bf0dc8cbe.png)

https://user-images.githubusercontent.com/2198527/175386449-e37517cb-1300-4881-83d1-1591c2541325.mp4

### Expected Behavior

Mountains grow on earth

### Actual Behavior

Mountains grow in space

**Comment by SnailBones** [comment]
I'm noticing that movement is also jittery and unresponsive when moving over greatly exaggerated terrain on globe (a bit but perhaps less so on Mercator).

Related to https://github.com/mapbox/mapbox-gl-js/issues/12037

**Comment by SnailBones** [comment]
I can only reproduce this with extreme exaggeration values, so I think this should effectively be resolved by https://github.com/mapbox/studio/issues/15819. Feel free to reopen if there's a need to support exaggeration > 100.
