### ISSUE TITLE
Extrusion angle becomes incorrect at some zoom levels

### ISSUE THREAD

**Issue by AlexanderBelokon** [mapbox/mapbox-gl-js#12035]
**mapbox-gl-js version**: 2.9.1

**browser**: Firefox 101.0.1

### Steps to Trigger Behavior

 1. Login to [Studio](https://studio.mapbox.com)
 1. Create a new style (with `globe` projection by default)
 1. `3D -> 3D Terrain -> Enable terrain -> On`
 1. `3D -> 3D Terrain -> Exagerration -> 1000`
 1. Zoom globe in and out for a bit
 1. Notice that mountains change their angle abruptly 

### Link to Demonstration

[Shared style](https://api.mapbox.com/styles/v1/testy-user/cl4rd3chd000u15lk13a6sg0e.html?title=view&access_token=pk.eyJ1IjoidGVzdHktdXNlciIsImEiOiJjbDRyZDMyOTQwNTNzM2NvNjF3dmc1dGNmIn0.sRrT87LpCL7kd6XivEnkxg&zoomwheel=true&fresh=true#3.2/61.25/-16.01)

https://user-images.githubusercontent.com/2198527/175380545-6ed0d566-d636-4c74-8273-9d699a3c2f28.mp4

### Expected Behavior

Mountains stay upright

### Actual Behavior

Mountains change their angle abruptly

**Comment by SnailBones** [comment]
@AlexanderBelokon I can only reproduce this with extreme exaggeration values, so I think this should effectively be resolved by https://github.com/mapbox/studio/issues/15819.
