### ISSUE TITLE
An uncompressed version for mapbox-gl-js?

### ISSUE THREAD

**Issue by hanfeisun** [mapbox/mapbox-gl-js#1204]
For mapbox.js, there are uncompressed version hosted at:
http://api.tiles.mapbox.com/mapbox.js/v1.0.0/mapbox.uncompressed.js

I tried to use the uncompressed version of "mapbox-gl-js" like this:
https://api.tiles.mapbox.com/mapbox-gl-js/v0.7.0/mapbox-gl.uncompressed.js

But that doesn't work. Is there an uncompressed version of "mapbox-gl.js"?

**Comment by mourner** [comment]
https://api.tiles.mapbox.com/mapbox-gl-js/v0.7.0/mapbox-gl-dev.js

**Comment by robertberry** [comment]
Would be useful if this were linked to somewhere on the website.

**Comment by mourner** [comment]
@robertberry why would you need the uncompressed version? The compressed one comes with a source map, so you see uncompressed code when debugging.
