### ISSUE TITLE
Area between border in polygon

### ISSUE THREAD

**Issue by faizan-karigar** [mapbox/mapbox-gl-js#12043]
**mapbox-gl-js version**:v2.8.2
**Draw-verson**:v1.2.2

### Question
Basically i want to calculate the area of selection between those borders or separately that how much area cover was covered individually on each side using layer or polygon
![image](https://user-images.githubusercontent.com/86834058/176137755-d7ea391c-d73b-4b73-841b-683b6f9bf6ed.png)

**Comment by stepankuzmin** [comment]
Hi @faizan-karigar,

Thank you for using mapbox-gl-js. You would need to find the difference between the drawn polygon and the coastline, e.g. using https://turfjs.org/.

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
