### ISSUE TITLE
the bug about index-of

### ISSUE THREAD

**Issue by zhangziyi123** [mapbox/mapbox-gl-js#12041]
The expression indexof does not play a fuzzy match.For example, { name: 'zhang' }, ['index-of', 'name', 'g'], the expected value is 4, but the actual value is -1.

**Comment by mourner** [comment]
`['index-of', 'name', 'g']` looks for `g` in the actual string `name` and doesn't find it. Try `['index-of', ['get', 'name'], 'g']`.

**Comment by zhangziyi123** [comment]
> `['index-of', 'name', 'g']` looks for `g` in the actual string `name` and doesn't find it. Try `['index-of', ['get', 'name'], 'g']`.

I tried, but I still can't! =.=

**Comment by mourner** [comment]
@zhangziyi123 please fill out the bug request form fully then, including a reproducible live test case that demonstrates the issue.
