### ISSUE TITLE
CustomLayerInterface support in globe

### ISSUE THREAD

**Issue by pratikyadav** [mapbox/mapbox-gl-js#12046]
**mapbox-gl-js version**: 2.9.1

**browser**: Chrome

### Steps to Trigger Behavior

 1. get to code pin from https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/
 2. change projection to globe and make threejs model larger by using `scale: 0.0005` value
 3. zoom out to see threejs model disappears in globe view

### Link to Demonstration

https://codepen.io/pratikyadav/pen/BaramrQ

### Expected Behavior

model should keep on appering 

### Actual Behavior

model disappears

**Comment by zakjan** [comment]
There is a custom WebGL layer on the globe showcased at https://www.mapbox.com/blog/globe-view, how is it integrated?

**Comment by mourner** [comment]
Support for custom layers on globe is in progress and likely coming in the next release — see e.g. https://github.com/mapbox/mapbox-gl-js/pull/11996

**Comment by zakjan** [comment]
That's a wonderful news! I appreciate the effort in inventing such new integration API. I'd like to explore the possibility to integrate with deck.gl when it's ready.

**Comment by astojilj** [comment]
> Support for custom layers on globe is in progress and likely coming in the next release — see e.g. #11996

We had to prioritize Mobile SDK support first https://github.com/mapbox/mapbox-maps-ios/pull/1501 first and there was some delay due to summer vacations...

**Comment by jaybo** [comment]
It would be great to get some hint of a timeframe for this.  I'm faced with the decision whether to totally remove bearing, pitch, (and globe) support from my app since I've recently begun to rely upon a CustomLayer.  Just knowing whether this work is still part of the near term plan would help me decide which way to go. Thanks!

**Comment by stepankuzmin** [comment]
Thanks, everyone! This is done in https://github.com/mapbox/mapbox-gl-js/pull/12182, and it's planned for the next release.
