### ISSUE TITLE
Missing tiles at the top of the screen in globe view

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#12069]
**mapbox-gl-js version**: `main`

Looks like #11988, which fixed tiles sometimes missing at the bottom in the globe view, inadvertently introduced an opposite bug  — tiles sometimes missing at the top. cc @SnailBones @karimnaaji 

### Steps to Trigger Behavior

Open http://localhost:9966/debug/#5.51/64.905/-30.35 with `projection: 'globe'` set

### Expected Behavior

This is pre-#11988:

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/25395/177776862-ad800306-9b64-425a-9e6b-b82dec655437.png">

### Actual Behavior

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/25395/177776408-046bfbe7-8ede-4e82-ad83-a01600621e36.png">

**Comment by karimnaaji** [comment]
I'll reopen as it might be worth investigating that one a bit more, I have noticed a similar problem of missing tiles at the edges of the screen from latest main (this time on the left/right side of the screen):

https://user-images.githubusercontent.com/7061573/186548389-6ce9721f-b50d-4819-87a0-f60fa041533a.mov

Location 5.18/49.269/-105.351, viewport size: 814x665

cc @SnailBones
