### ISSUE TITLE
gaps in symbol anchor placement?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#1206]
Looking at highway shields in a version of the Mapbox Streets style, I'm seeing pretty big gaps in anchor placements that aren't caused by collisions:

I90:
![screen shot 2015-05-15 at 7 06 02 pm](https://cloud.githubusercontent.com/assets/5607844/7663357/20396abe-fb37-11e4-936e-b1b14bfb566b.png)

I78:
![screen shot 2015-05-15 at 7 14 56 pm](https://cloud.githubusercontent.com/assets/5607844/7663360/281af626-fb37-11e4-84f0-7134374ed613.png)

Highway 22:
![screen shot 2015-05-15 at 7 15 33 pm](https://cloud.githubusercontent.com/assets/5607844/7663363/2daa4312-fb37-11e4-9752-fcaacbfc30a6.png)

Labels on these line segments show up at higher zooms, so I think they are in the data. Any ideas?

/cc @ansis

**Comment by peterqliu** [comment]
I see this in emerald, too. x-ray tells me the symbol data is present, long before a single shield appears in the style

**Comment by mourner** [comment]
For easier debugging, it's also helpful to look at the data in a style with a single layer that renders road_label data layer as lines. E.g. it may be because of highways being a set of tiny lines in the data.

**Comment by nickidlugash** [comment]
> E.g. it may be because of highways being a set of tiny lines in the data.

Sorry, forgot to mention that I had checked out these examples in xray mode of the editor, and the line lengths of these features don't appear to be particularly short.

**Comment by nickidlugash** [comment]
hrm. There appears to be some large gaps in the data:

![screen shot 2015-05-18 at 2 11 11 pm](https://cloud.githubusercontent.com/assets/5607844/7686973/da9256fa-fd67-11e4-9c3d-2303ff3f7b4b.png)

I'll follow up with @ajashton to see if this is coming from our vector tiles, and will update or close this ticket accordingly.

**Comment by ajashton** [comment]
My guess is this has do to with the fact that the road is broken up into such short segments and thus not making it through our linelabel filter. But looking at that filter, it doesn't account for the fact that some roads might have both a name and a shield value. I've made a ticket to fix that here: https://github.com/mapbox/mapbox-streets-source.tm2source/issues/186

**Comment by nickidlugash** [comment]
In addition to the areas with gaps in the data, I'm also seeing some areas that don't have labels but do have data:

![screen shot 2015-05-19 at 12 43 40 pm](https://cloud.githubusercontent.com/assets/5607844/7710679/6adaae1c-fe33-11e4-9fa8-59d1ef3634a8.png)

(The purple lines are the geometries that are being used to place these road labels)

**Comment by mourner** [comment]
@nickidlugash could this be just because of a big min-distance?

**Comment by ansis** [comment]
@nickidlugash are you still seeing this in any current styles, or can this be closed?

**Comment by ansis** [comment]
The original examples are because of missing vector tile data:
![screen shot 2016-02-04 at 7 52 04 pm](https://cloud.githubusercontent.com/assets/1421652/12837611/38437ac4-cb79-11e5-97f6-d56ae7ce5b1f.png)
![screen shot 2016-02-04 at 7 54 27 pm](https://cloud.githubusercontent.com/assets/1421652/12837610/384245fa-cb79-11e5-9c21-fefe51650290.png)

and [this one](https://cloud.githubusercontent.com/assets/5607844/7710679/6adaae1c-fe33-11e4-9fa8-59d1ef3634a8.png) is because of a large symbol-min-distance.
