### ISSUE TITLE
How to show / hide a layer related to Mapbox street v8 ?

### ISSUE THREAD

**Issue by joffreyBerrier** [mapbox/mapbox-gl-js#12064]
**mapbox-gl-js version**: 2.9.1

### Question
I want to show/hide a layer related to the data source **route** of **Mapbox streets v8** but when I set the layout property visible to 'none', the `LayoutProperty` is ignored because this data is related to the zoom of the map, is it possible to avoid this?

Thx

**Comment by stepankuzmin** [comment]
Hi, @joffreyBerrier 

Thank you for using mapbox-gl-js. This issue tracker is for reporting bugs and feature requests. Please provide a minimal, complete, verifiable demonstration of the issue to help the maintainers and community understand and address the problem accurately.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
