### ISSUE TITLE
Race condition between GeolocateControl and map removal

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#12073]
**mapbox-gl-js version**: v2.9.1

**browser**: All

### Steps to Trigger Behavior

 1. Add a GeolocateControl to a map
 2. Then remove the map before the geolocate control has finished its check for access

### Link to Demonstration

```js
      mapboxgl.accessToken =  "…;
      const map = new mapboxgl.Map({
        container: "map",
        style: "mapbox://styles/mapbox/streets-v11",
        center: [-79.4512, 43.6568],
        zoom: 8,
      });
      map.addControl(
        new mapboxgl.GeolocateControl({
          showUserLocation: false,
        })
      );
      map.remove();
```

### Expected Behavior

There should be no uncaught errors doing this.

### Actual Behavior

The `_checkGeolocationSupport` method calls its callback after the map has been removed, which them calls `_setupUI`, which refers to `this.map._getUIString`, which is not accessible because `this.map` has been destroyed.

A workaround would be to check that the `this.map` reference is still good after returning from the permission check. A fancier way to do this would be to "cancel" the promise by doing something like setting `this._removed = true` and throwing within the `.then` call if that's true.

**Comment by roevieDev** [comment]
Im having the save issue on the latest version

```
"mapbox-gl": "^2.11.0",
"@mapbox/mapbox-gl-geocoder": "^5.0.1",
```

![image](https://user-images.githubusercontent.com/115077715/204947797-b772a367-e933-4c49-9912-65494c3b01d6.png)

**Comment by stepankuzmin** [comment]
Hi @roevieDev,

Unfortunately, I couldn't reproduce this. Could you please provide a reproducible example for this?

**Comment by tmcw** [comment]
I've noticed the same thing but I think it's because 2.11.0 doesn't include this change. The 2.11.0 release points to e277a7bf1dbca7a25c7a52f8784fca28e14d84ab which includes a version of setupUI:

https://github.com/mapbox/mapbox-gl-js/blob/e277a7bf1dbca7a25c7a52f8784fca28e14d84ab/src/ui/control/geolocate_control.js#L419-L422

without the change:

https://github.com/mapbox/mapbox-gl-js/blob/2d8f3f470d77ec22066bfca075553e55955decdf/src/ui/control/geolocate_control.js#L419-L425

As far as I can tell, there's a release branch system in use and this didn't make it into the release, but I'm not sure how those releases are decided and how commits are pulled.

**Comment by tmcw** [comment]
There's a 2.11.1 release as well, which also doesn't include this fix. Is there a queue somewhere of commits that are in `main` but not in releases? Or a tag that could be applied to issues to indicate which are fixed technically versus those that are included? This release system seems a bit opaque to me.
