### ISSUE TITLE
maxZoom only works with integer number (and Terrain is set)

### ISSUE THREAD

**Issue by lstiz** [mapbox/mapbox-gl-js#12083]
I tried to set a float number to maxZoom and the map did not works properly: it flickers and some tiles dissapear when the 3D is activated.
It seems to only take integer maxZooms as valid values.

**Comment by stepankuzmin** [comment]
Thank you for your opening this ticket. To help the maintainers and community understand and address the problem accurately can you please provide a minimal, complete, verifiable demonstration of the issue. We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.
