### ISSUE TITLE
"==" expression does not match when id is zero

### ISSUE THREAD

**Issue by MartinP-C** [mapbox/mapbox-gl-js#12084]
**mapbox-gl-js version**: 2.9.1

**browser**: Chrome 103

### Steps to Trigger Behavior

 1. Add GeoJson Source and layer
 2. Use the "==" expression in a paint style

### Link to Demonstration
https://jsfiddle.net/t1qz7yfL/1/

### Expected Behavior
["==", ["id"], 0] should evaluate to true, and the top box should be coloured green.

### Actual Behavior
The top box isn't green. Appears to be because the id is zero.
The other polygons are coloured as expected and are also using integer IDs.

**Comment by mourner** [comment]
This was fixed by #12000 and the fix should be included in the next version (v2.10.0).
