### ISSUE TITLE
how to render intersection of lines like this?

### ISSUE THREAD

**Issue by haoziluo** [mapbox/mapbox-gl-js#1208]
![image](https://cloud.githubusercontent.com/assets/2647388/7670311/95749898-fcd2-11e4-9fee-aae5b2b8bb67.png)
I can't find the calculation about the intersection?

**Comment by mourner** [comment]
It just renders 2 layers — a brown one (casings) and a yellow one on top.

**Comment by haoziluo** [comment]
please make it clear, I can't understand how to fix the intersection, thank you!

**Comment by mourner** [comment]
I don't understand your issue then. Please be more clear.

**Comment by haoziluo** [comment]
![image](https://cloud.githubusercontent.com/assets/2647388/7670430/924c295c-fcd6-11e4-8379-a8f46847eddb.png)
how to wipe those lines?
