### ISSUE TITLE
Sometimes extrusion layers doesn't respect minzoom

### ISSUE THREAD

**Issue by EugeneMarshin** [mapbox/mapbox-gl-js#12082]
**mapbox-gl-js version**: 2.7.1 and 2.9.1

**browser**: Chrome(Latest)

### Steps to Trigger Behavior

1. go to the demo link, check layers config ("minzoom")
2. check properties color
3. change initial zoom level to 16
4. refresh right side
5. check properties color

### Link to Demonstration

https://jsbin.com/vabowijuco/edit?html,output

### Expected Behavior
on step 2 and 4 property should be highlighted
### Actual Behavior
step 2 property is not highlighted

**Comment by mourner** [comment]
It's not related to `minzoom`, but rather the lack of `id` on buildings in the streets source on zoom level 15. It's likely stripped to save on tile size. Closing as not related to GL JS, but feel free to reach out to support regarding this issue in the streets layer.
