### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by redimongo** [mapbox/mapbox-gl-js#12093]
Not sure if this plugin is the same as `@mapbox/search-js-core` However that plugin is returning an error when I import it 
to a nextJS app.
```
./node_modules/@mapbox/search-js-core/dist/index-esm.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
error - ReferenceError: document is not defined
error - ReferenceError: document is not defined
```

**Comment by mourner** [comment]
This is an unrelated repo, so I'll close this, but tagging @mpothier to investigate the issue internally.

**Comment by mpothier** [comment]
@redimongo The latest version of `@mapbox/search-js-core`, **v1.0.0-beta.12**, should resolve the error you're describing with webpack bundlers. If not, please submit any feedback or issues through that project's official [documentation site](https://docs.mapbox.com/mapbox-search-js/api/core/).
