### ISSUE TITLE
TileLoadFunction for custom url

### ISSUE THREAD

**Issue by berkayoruc** [mapbox/mapbox-gl-js#12094]
**mapbox-gl-js version**: 2.9.2

### Question
Hello everyone!

Is there any custom tileLoadFunction for source url manipulation like openlayers?
https://openlayers.org/en/latest/apidoc/module-ol_Tile.html#~LoadFunction

Default url: url/tile/{z}/{y}/{x}
What I need example: url/tile/L{z}/{y*5}/{x/2}

**Comment by ansis** [comment]
The map's `transformRequest` option can be used to manipulate the url of a tile.
https://docs.mapbox.com/mapbox-gl-js/api/properties/#requestparameters
