### ISSUE TITLE
How to differentiate between clicking on map and clicking on a marker?

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1209]
I'd like to have a popup open when clicking on a marker (with info specific to that marker).
I see that the popup example  displays a popup when clicking on the map.
How to differentiate between the two events "clicking on the map" and "clicking on a marker' ?

**Comment by tmcw** [comment]
Currently not - supporting this kind of behavior is part of the previous ticket #656

**Comment by 3zzy** [comment]
Was this feature added? I could find examples where clicking on 'symbol' and 'cluster' worked but still unsure how to detect click on markers.

**Comment by armved** [comment]
+1

**Comment by AshwinTayson** [comment]
Any update on this?

**Comment by asheemmamoowala** [comment]
Example: https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/

**Comment by Alex-Horlock** [comment]
For those of you who get here wondering how on earth Mapbox GL JS (which seems to be awesome) could not implement a 'click' event like I was... turns out the solution is actually pretty nice and you just need to get the markers 'element' and listen to that click event e.g.

`marker.getElement().addEventListener('click',` function (e) {
                console.log("marker clicked");
            });`

Cheers :)

**Comment by renatoniola** [comment]
> For those of you who get here wondering how on earth Mapbox GL JS (which seems to be awesome) could not implement a 'click' event like I was... turns out the solution is actually pretty nice and you just need to get the markers 'element' and listen to that click event e.g.
> 
> `marker.getElement().addEventListener('click', function (e) { console.log("marker clicked"); });`
> 
> Cheers :)

My concern about your solution is that it's going to apply one event handler for each marker  and if there are lots of them  the page might become too slow

**Comment by ibushah** [comment]
> marker.getElement().addEventListener('click', function (e) { console.log("marker clicked"); });

u just saved me from depression, love you man <3 <3 <3

**Comment by eusebiu** [comment]
```
                    var el = document.createElement('div');
                    el.innerHTML = `<label>some text</label>`;

                    const marker = new mapboxgl.Marker()
                      .setLngLat({ lng: longitude, lat: latitude })
                      .setPopup(new mapboxgl.Popup().setDOMContent(el))
                      .addTo(that.map);

                    marker.getElement().addEventListener('click', (e) => { marker.togglePopup(); e.stopPropagation(); }, false);
```

**Comment by crhistianramirez** [comment]
My use case is different in that I want to know when the map is clicked and the click was *not* on a marker. Anybody have an idea on how to differentiate?

**Comment by expdev** [comment]
> My use case is different in that I want to know when the map is clicked and the click was _not_ on a marker. Anybody have an idea on how to differentiate?

for example, you could differentiate a click on a marker from a click on a map, check the property 'map.getCanvas().style.cursor'.  If it's "pointer", then it's a marker

**Comment by frozeeen** [comment]
Got here finding a solution, but this is my current work-around.

```javascript
map.on('click', (e) => {
    if (e.originalEvent.target.localName == 'canvas') {
        alert('You clicked the map');
    }
})
```
