### ISSUE TITLE
Is the `testMode` only meant for Mapbox GL in real browsers using Selenium WebDriver?

### ISSUE THREAD

**Issue by markcnunes** [mapbox/mapbox-gl-js#12103]
**mapbox-gl-js version**: 2.9.2

### Question

Is the `testMode` only meant for Mapbox GL in real browsers using Selenium WebDriver?
The [docs](https://docs.mapbox.com/mapbox-gl-js/guides/browsers-and-testing/#automated-tests) says `Run automated browser tests without an access token by setting the testMode Map option.` and the [Github example](https://github.com/mapbox/mapbox-gl-js/tree/main/test/browser) also mentions `automated testing of Mapbox GL in real browsers using Selenium WebDriver` but I was hoping this parameter would also work for any other cases without Selenium WebDriver such as just previewing local pages and prevent the `mapboxgl.accessToken` from being used. I am not sure if this is only meant for Selenium WebDriver or perhaps I am missing something.

[Codesandbox example with `testMode` that still showing the error message](https://codesandbox.io/s/mapbox-gl-react-testmode-q5hi8l?file=/src/App.tsx)

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/guides/browsers-and-testing/#automated-tests

**Comment by mourner** [comment]
This option is meant primarily for automated tests — turning it on, while silencing auth errors, also disables map rendering. See #10445 for more context.
