### ISSUE TITLE
rotateTo breaks after setPitch is called

### ISSUE THREAD

**Issue by ehmorris** [mapbox/mapbox-gl-js#1210]
I just built the JS from master.

![example](https://cloud.githubusercontent.com/assets/654275/7714909/ce33913c-fe50-11e4-9171-96c81e9b0200.gif)

cc @ansis

**Comment by mourner** [comment]
What did you expect to see? You're rotating to the same bearing the map is already on after first rotate.

**Comment by ehmorris** [comment]
Hah! Whoops, should have done a little more work before I made an issue.
