### ISSUE TITLE
Project cannot setup, yarn run start-debug failure, mapboxgl is undefined

### ISSUE THREAD

**Issue by huangyingjie** [mapbox/mapbox-gl-js#12110]
I cloned latest code from main branch, `pnpm i`, and run `MAPBOX_ACCESS_TOKEN=xxx yarn run start-debug`
then line 69 in dist/mapbox-gl-dev.js show error below:
<img width="686" alt="image" src="https://user-images.githubusercontent.com/1618397/180658246-b7867815-3347-40eb-af6d-0660a8145d8e.png">
What's wrong here, how do you guys develop on local machine?

**Comment by mourner** [comment]
GL JS is developed using `yarn` v1, not `pnpm`. We don't know if there are compatibility issues with the latter, but please try installing deps using Yarn instead.

**Comment by huangyingjie** [comment]
fixed by yarn.

**Comment by 12finger** [comment]
tried to debug mapbox v2.15 locally following the [contributing guide](https://github.com/mapbox/mapbox-gl-js/blob/main/CONTRIBUTING.md), but only when i searched the issues i found out that `yarn 1` is being used. did not find such info in the guide. did i ovelrook something?

**Comment by 12finger** [comment]
i could not find any info on this in the official documentation.
  good to know yarn version 1 is being used.
