### ISSUE TITLE
Map Customization in 3d with building data  

### ISSUE THREAD

**Issue by HaseebUllahAbbasi** [mapbox/mapbox-gl-js#12111]
**mapbox-gl-js latest**:

### Links to related documentation

[https://docs.mapbox.com/playground/geocoding/?search_text=-0.13199205211660114,51.51616489520404&types=place%2Cpostcode%2Caddress&limit=1

**Comment by mourner** [comment]
Thank you for the report! However, it seems unrelated to this repository, which specifically tracks issues with the Mapbox GL JS library and its style specification. Can you please submit the report to the [Mapbox support channel](https://www.mapbox.com/contact/support/) instead? We'll do our best to help you out!

**Comment by HaseebUllahAbbasi** [comment]
Thanks for your response, Sir  I have been facing this issue, and I have
mailed it to support and contact Mapbox, but they did not answer any of
this, do let me know with your suggestions plz sir
