### ISSUE TITLE
Markers are visible when behind terrain

### ISSUE THREAD

**Issue by smitja** [mapbox/mapbox-gl-js#12123]
When 3D (mapbox-raster-dem) terrain is applied and map is pitched, markers behind terrain are dimmed but visible.

Is this intended behaviour? Is it possible to hide these markers?

![image](https://user-images.githubusercontent.com/16716418/182024394-c9bb54a6-5bc8-4bdd-974e-451fd3c59865.png)

**Comment by mourner** [comment]
Not at the moment — looks like the 0.2 opacity value for occluded markers is currently hardcoded:

https://github.com/mapbox/mapbox-gl-js/blob/745a210598ce407aad689a504ca7170f8da39795/src/ui/marker.js#L443-L446

We might need to introduce an option for this.
