### ISSUE TITLE
MapBox - Click On Marker and Go To URL...... with marker ID being passed as parameter

### ISSUE THREAD

**Issue by sparx1981** [mapbox/mapbox-gl-js#12128]
Hello everyone, 

I have the following code in my MapBox map and it allows me to click on a marker and redirect to a different page. This works fine, however I'd like the case_id to be dynamic based upon the marker I clicked on. 

map.on('click', 'earthquakes-point', function(e) {
    window.location.href = 'www.mypage.com?CASE_ID=11';
})

The marker is created using GEOJSON and that as a field in there for ID. It's that field value that I'd like to pass in my URL.
Is this possible?

Many thanks

**Comment by stepankuzmin** [comment]
Hi @sparx1981,

Thank you for using mapbox-gl-js. You can get the features under the cursor pointer from the [map mouse event](https://docs.mapbox.com/mapbox-gl-js/api/events/#mapmouseevent#features) object, and then you can use the feature properties to access the ID field.

```js
map.on('click', 'earthquakes-point', function(e) {
  if (e.features.length > 0) {
    window.location.href = `www.mypage.com?CASE_ID=${e.features[0].properties.ID}`;
  }
});
```

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
