### ISSUE TITLE
Mapbox - On Click, go to new URL passing co-ordinates as parameter

### ISSUE THREAD

**Issue by sparx1981** [mapbox/mapbox-gl-js#12127]
Hi guys, I have a map box map running and it's doing what I need graphically. My problem is that I use a form on another URL to populate my records. 

What I would like to have is the ability to click on the map, and when I do, it loads my form passing in the co-ordinates. 
Perhaps clicking to do this isn't the best approach as it would cause problems with dragging etc.. but any thoughts or help you could give would be great.

Many thanks

**Comment by stepankuzmin** [comment]
Hi @sparx1981,

Thank you for using mapbox-gl-js. For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
