### ISSUE TITLE
Add orthographic camera mode

### ISSUE THREAD

**Issue by alberto-taiuti-skydio** [mapbox/mapbox-gl-js#12132]
## Motivation

It would be very useful to have an orthographic projection rather than only a perspective one available. This would allow us to present the Mapbox 3D map view, alongside some other ThreeJS content, both with an orthographic projection, and hence create some interactions that would work much better if shown while using an orthographic projection.

## Design

The best option would be to offer the ability to change the projection being used like ThreeJS does: ThreeJS offers a [perspective camera](https://threejs.org/docs/#api/en/cameras/PerspectiveCamera) and an [orthographic camera](https://threejs.org/docs/#api/en/cameras/OrthographicCamera) which you can change at runtime.

**Comment by alberto-taiuti-skydio** [comment]
Any updates? 👀

**Comment by thadk** [comment]
According to https://github.com/mapbox/mapbox-gl-js/issues/13081 the syntax is:
`map.setCamera({"camera-projection": "orthographic"})` / `map.setCamera({"camera-projection": "perspective"})`
The link I saw in the documentation itself appeared broken. This blog post discussed the difference: https://blog.mapbox.com/designing-perspective-maps-in-studio-9194ce6a5f22

**Comment by astojilj** [comment]
Looks like this is already supported. 

`map.setCamera({"camera-projection": "orthographic"}) ` on the left side, `map.setCamera({"camera-projection": "perspective"})` (default) on the right.

<img width="2272" alt="Screenshot 2024-10-04 at 13 23 49" src="https://github.com/user-attachments/assets/931c476f-72a4-4f01-898b-8d65efa0510e">
