### ISSUE TITLE
iOS Source Code

### ISSUE THREAD

**Issue by nraptis** [mapbox/mapbox-gl-js#12150]
I am trying to build a project which transitions to-and-from a MapBox globe / map.

I would like to see the iOS source code down to the Metal shaders so that I can debug the differences between us at a vertex level. This is not for a MapBox clone or competitor, it is to work with MapBox.

Thanks,
Nick

**Comment by mourner** [comment]
It's closed source. Please reach out to support. Also, this repo is for submitting issues about the JavaScript library, not the mobile SDKs.
