### ISSUE TITLE
Can't resolve '%23clip' in '...\node_modules\mapbox-gl\dist'

### ISSUE THREAD

**Issue by Yura13** [mapbox/mapbox-gl-js#12164]
After updating angular from 13 to 14 I got failed build with the next error:
./node_modules/mapbox-gl/dist/mapbox-gl.css - Error: Module Error (from ./node_modules/postcss-loader/dist/cjs.js):
...\node_modules\mapbox-gl\dist\mapbox-gl.css:1:21755: Can't resolve '%23clip' in '...\node_modules\mapbox-gl\dist'

**mapbox-gl-js version**: 2.9.2

**Comment by mikefresh** [comment]
Same!

**Comment by alexsukhodolsky** [comment]
Referencing the `node_modules/mapbox-gl/src/css/mapbox-gl.css` stylesheet instead of the minified one found in the `dist` folder fixed the issue for me. It's not a great solution and the mapbox team should probably fix the broken stylesheet found in the `dist` folder.

**Comment by marfrede** [comment]
Same Problem here.

**Comment by hound-realscore** [comment]
Yep, me too.  :-(

**Comment by mourner** [comment]
The CSS file itself is perfectly fine (and even passes the [CSS Validator](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Funpkg.com%2Fmapbox-gl%402.9.2%2Fdist%2Fmapbox-gl.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en)). This appears to be an Angular CLI bug which has already been fixed on their side in https://github.com/angular/angular-cli/pull/23691, and the fix will be included in the next release (v14.2).

**Comment by Pawelele** [comment]
It look like this was broken i Angular 14.1.2. I just locked all angular packages in angular.json to 14.1.1. Remember to remove ^ or ~ before version number, remove package-lock.json and reinstall node-modules. Now everything is working fine.

**Comment by snocorp** [comment]
This wasn't fixed by https://github.com/angular/angular-cli/pull/23691 as that fix seems to be included in `14.1.3` and still happens. I have raised https://github.com/angular/angular-cli/issues/23773 to fix the specific issue related to the mapbox CSS.

**Comment by mourner** [comment]
Thanks for the clarification @snocorp! This appears to be fixed by https://github.com/angular/angular-cli/issues/23774 now.

**Comment by coracuity** [comment]
This is still affecting me using a create-react-app with webpack. I'm really not sure what can be done about it...
