### ISSUE TITLE
Overlaying SVG on mapboxgl canvas disables zoom,pan,keyboard movements in v0.7.0 - worked in v0.6.0

### ISSUE THREAD

**Issue by tmostak** [mapbox/mapbox-gl-js#1217]
Removing the svg makes things work properly. Without the svg, I can for example see the wheel event in interaction.js being fired on zoom and the map zooms properly.  With the svg overlaid, no event is fired and no zoom occurs.

Also note that I can still do programmatic movements (i.e. fitBounds). 

Note that everything works properly with overlaid svg with release v0.6.0.  What changed from v0.6.0 to v0.7.0 to alter this behavior?

**Comment by mourner** [comment]
Hmm, @jfirebaugh maybe that's because events are now added directly to canvas instead of the container?

**Comment by tmcw** [comment]
@tmostak can you try adding [pointer-events: none](https://css-tricks.com/almanac/properties/p/pointer-events/) to the SVG element to allow mouse events to fall through it?

**Comment by tmostak** [comment]
@tmcw Yes that works - however I still need to capture single click events on the svg so that I can trigger a popup (I'm basically overlaying a point map done in d3.js).  Any suggestions?  Or is it easy to revert the  behavior to bind events to the container instead of canvas?

**Comment by tmostak** [comment]
Just fixed things by downloading the source and replacing e.getCanvas() in Interaction.js with e.getContainer().  Could the binding level (to container or canvas) be optionally specified in the api?

**Comment by tmcw** [comment]
> however I still need to capture single click events on the svg so that I can trigger a popup

Yes, you can add a [pointer-events: all](https://css-tricks.com/almanac/properties/p/pointer-events/), as specified in the original linked article.

I think this should remain the same: the map canvas is the thing receiving click information, and events that overlay it should passthrough events with the `pointer-events` property.

**Comment by jfirebaugh** [comment]
An SVG overlay would want some events on children to pass through (the mousedown that starts a drag) but not others (a click on a path to open a popup). I think the right way to solve this while still preserving the intent of 7ba77d054a1b9076a0eb7499c9a95b5efc011e5d is to structure the DOM like:

```
<div id="map" class="mapboxgl-map">
  <div class="mapboxgl-canvas-container mapboxgl-interactive">
    <canvas class="mapboxgl-canvas" />
    <svg>
      ...
    </svg>
  </div>
  <div class="mapboxgl-control-container">
    ...
  </div>
</div>
```

The `.mapboxgl-canvas-container` would be available to add custom overlays inside, and map event handlers would be bound to it rather than to the `canvas`.

**Comment by jfirebaugh** [comment]
As of 6e99c4c3ef8ca2cb71a9bf203e7644aef18460aa you can append custom overlays to `map.getCanvasContainer()`, and you should get behavior identical to v0.6.0.
