### ISSUE TITLE
Mapbox GL JS 2.0 react-native library?

### ISSUE THREAD

**Issue by alexpchin** [mapbox/mapbox-gl-js#12170]
I'm looking to implement Mapbox GL JS, specifically the globe projection, in a react-native project.

Currently, the README points to https://github.com/nitaliano/react-native-mapbox-gl for react-native, however it suggests that this is Deprecated in favour of https://github.com/rnmapbox/maps which I believe uses the native libraries.

Is it possible to use Mapbox GL JS version 2.0 on React Native and if so what is the best recommended library / strategy.

**Comment by avpeery** [comment]
Hi @alexpchin, if you are looking to implement react-native you will need to use [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/). You can also checkout this [link](https://docs.mapbox.com/help/glossary/maps-sdk-for-react-native/) in Mapbox docs about getting setup with Maps SDK and react-native.

I am closing this issue as it does not pertain to Mapbox GL JS. Thanks for using Mapbox!
