### ISSUE TITLE
3d buildings position using 3d tiles isn't accurate and blink when reload on terrain

### ISSUE THREAD

**Issue by kongkbj** [mapbox/mapbox-gl-js#12173]
**mapbox-gl-js version**: 2.9.2

### Question
use tech
map -  mapbox gl js
terrain - terrain-dem-v1
deck.gl 8.8.6 - tile3dlayer
loader - cesiumionloader

problem 
1.  3d building's height using 3d tile is not correct. building's height is lower than terrain height.

2. whenever map moves, 3d buildings using 3d tile change height. (tremble)

3. when reload 3d tile, 3d buildings using 3d tile blink

if you know how to solve the problem, please tell me.

thank you.

**Comment by mourner** [comment]
This looks like an issue with deck.gl, not something we can fix on the GL JS side, so I'd have to close this.

**Comment by kongkbj** [comment]
@mourner  thank you for your answer!
