### ISSUE TITLE
non-Mapbox sources are billed in v1.x

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#12171]
### Steps to Trigger Behavior

Load a non-Mapbox source with Mapbox access token specified in v1.x.
The load will be billed by Mapbox.

### Detail
The bug is a missing bracket on the 2nd line here:
https://github.com/mapbox/mapbox-gl-js/blob/50adf1cc14e5aef09099f15c5cb803eaa5f72a48/src/util/mapbox.js#L392-L397

This means everyone who used 1.x with an access token was billed for non-Mapbox source loads. 

Simple bug - probably thousands of dollars billed in error to customers.

Note: using Prettier would have made it obvious to see this bug.

**Comment by mathewantony31** [comment]
Thanks for the report, Zsolt. We've worked with the small number of impacted users to fix the issue by removing the Mapbox access token if they're not using a Mapbox source. We don't have any plans to provide a new gl-js v1 release with this changed as a workaround exists for someone to remove their Mapbox access token.

**Comment by hyperknot** [comment]
My project was definitely affected and I found no way except for fixing the brackets myself. Removing the token is not an option as I need to be able to switch between Mapbox and non-Mapbox maps.

I was charged for the non-Mapbox usage, I'm trying to communicate it with billing now.

**Comment by mathewantony31** [comment]
Thanks for raising that, Zsolt. I've prioritized the request with the billing team who've processed a refund on your account.

**Comment by hyperknot** [comment]
Thanks @mathewantony31 they've issued me a refund now.

**Comment by stepankuzmin** [comment]
Thanks, everyone! This is now fixed in the [v1.13.3](https://github.com/mapbox/mapbox-gl-js/releases/tag/v1.13.3) release.
