### ISSUE TITLE
Mapbox Driver mode in Web

### ISSUE THREAD

**Issue by alifiroozidev** [mapbox/mapbox-gl-js#12197]
### Question
is it possible to use Mapbox "driver mode navigation" (which works in android & ios) in mapboxgl js on the Web  ?? 
something like [this link](https://labs.mapbox.com/bites/00359/) ...

![subjects](https://user-images.githubusercontent.com/164625/69425458-2c86ad80-0d2b-11ea-9762-a3b0f5f47814.png)

### Links to related documentation
https://labs.mapbox.com/bites/00359/

**Comment by ansis** [comment]
Unfortunately this is not available on the web.
