### ISSUE TITLE
Performance regression in ImageSource between v1 and v2

### ISSUE THREAD

**Issue by yuvadm** [mapbox/mapbox-gl-js#12209]
While upgrading a project from Mapbox GL JS v1 to v2 I've hit what seems to be a very annoying performance regression in map rendering.

**mapbox-gl-js version**: 2.10.0 vs. 1.13.2

**browser**: All browsers - profiled on Google Chrome but behavior exhibited on Firefox and Chromium as well

### Steps to Trigger Behavior

 1. Visit the example link
 2. With browser dev tools start a performance profiling run
 3. Slide the main slider back and forth a few times to trigger map rendering - slider is toggling opacity between 9 raster layers depending on slider position (you won't see any changes on the map since current rain radar images are empty, but it doesn't matter)
 4. Stop profiling and see results

### Link to Demonstration

v1 - https://geshem-git-v6-mapbox1-yuvadm.vercel.app/
v2 - https://geshem-git-v6-yuvadm.vercel.app/

Both projects run exactly the same code base, but differ in Mapbox GL JS major version.

Specific code that runs on Slider change [can be found here](https://github.com/yuvadm/geshem.space/blob/e588e0f41e26353dd5425150225817cc52fab4bf/src/Map.tsx#L82-L89).

### Expected Behavior

No performance hit expected.

### Actual Behavior

Profiling results look horrible on v2, initial culprit seems to be `texSubImage2D` -

#### v1
<img width="1113" alt="Screen Shot 2022-09-01 at 17 41 08" src="https://user-images.githubusercontent.com/315080/187944871-1b6f6ae7-90ce-4bea-aa1a-efd7cdc23121.png">

#### v2
<img width="967" alt="Screen Shot 2022-09-01 at 17 41 15" src="https://user-images.githubusercontent.com/315080/187944885-45e04b5f-265a-4256-a13e-fe2393f23fa5.png">

**Comment by mourner** [comment]
This appears to be related to #11564 — the texture is constantly being reuploaded on every frame after the PR added the `else` statement here:

https://github.com/mapbox/mapbox-gl-js/blob/321b1f17068316bd80923ce67d081ce2f17c680c/src/source/image_source.js#L326-L331

@karimnaaji you reviewed that PR — can you take a look at this?
