### ISSUE TITLE
What does the red numbers in the map mean? 

### ISSUE THREAD

**Issue by vasuhooda** [mapbox/mapbox-gl-js#12205]
What does these red numbers in the map mean? How to hide and show them?

![Screenshot 2022-08-31 at 09 08 34](https://user-images.githubusercontent.com/8009769/187615401-a2606e68-6cfe-4a4a-8768-eed0ba8d2aab.png)

**Comment by mourner** [comment]
These are likely motorway labels. You can update their appearance or the range of zooms they show up on when editing the map style in https://studio.mapbox.com/. Closing the issue because it's not related to GL JS.
