### ISSUE TITLE
mapbox-streets-v8 3D Building Burj Khalifa wrong extrude shape 

### ISSUE THREAD

**Issue by rodolforamos** [mapbox/mapbox-gl-js#12229]
Found an extrude shape error of Burj Khalifa building on streets-v8 that does not happen on streets-v7

The error can be found on Mapbox example page:  https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/

mapbox-treets-v7 Burj Khalifa shape is perfect
[[[![On Mapbox-Streets-V7 the shape of Burj Khalifa is perfect][1]][1]](https://i.stack.imgur.com/Zjz0k.jpg)](https://i.stack.imgur.com/Zjz0k.jpg)

mapbox-treets-v8 Burj Khalifa shape is wrong
[[![mapbox-treets-v7 Burj Khalifa shape is wrong][2]][2]](https://i.stack.imgur.com/nRWfV.jpg)

**Comment by stepankuzmin** [comment]
Hi @rodolforamos,

Thanks for reporting it
