### ISSUE TITLE
> 嘿@kt7456,

### ISSUE THREAD

**Issue by kt7456** [mapbox/mapbox-gl-js#12237]
> 嘿@kt7456,
> 
I wasn't able to reproduce this either. Could you please check that the example you provided is working?
this is other demo address 
http://animpen.com/pen/kfpPAJa7
this is old demo address 
https://plnkr.co/edit/zdKhXxpkDkgIThfm?preview
Requires google browser to open

_Originally posted by @kt7456 in https://github.com/mapbox/mapbox-gl-js/issues/12225#issuecomment-1244799527_

**Comment by mourner** [comment]
Please don't open duplicate issues, #12225 is still open.
