### ISSUE TITLE
@kt7456 the demo by that URL doesn't appear to be working — I don't see the custom layer and there are a bunch of errors in the console. Perhaps you forgot to save some code updates?

### ISSUE THREAD

**Issue by kt7456** [mapbox/mapbox-gl-js#12232]
@kt7456 the demo by that URL doesn't appear to be working — I don't see the custom layer and there are a bunch of errors in the console. Perhaps you forgot to save some code updates?

_Originally posted by @mourner in https://github.com/mapbox/mapbox-gl-js/issues/12225#issuecomment-1240581249_

**Comment by stepankuzmin** [comment]
Hey @kt7456,

Let's keep the discussion in the original issue, so we don't have duplications.
