### ISSUE TITLE
WebGL doesn't initialize in Safari

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox-gl-js#1224]
![screen shot 2015-05-27 at 3 16 04 pm](https://cloud.githubusercontent.com/assets/58878/7845200/70df1504-0483-11e5-80b7-94b94f35bd50.png)

- Mavericks 10.9.5
- in /app

**Comment by tmcw** [comment]
Works for me in Safari 8

![2015-05-28 at 11 25 am](https://cloud.githubusercontent.com/assets/32314/7863776/37eca528-052c-11e5-96c9-0c68260fc47d.png)

**Comment by mourner** [comment]
Yeah, AFAIK WebGL is enabled in Safari starting from version 8.

**Comment by 1ec5** [comment]
There's an option to turn it on in Safari 7 IIRC. Turn on the Develop menu in Advanced Preferences.

**Comment by aaronlidman** [comment]
ha duh

![screen shot 2015-05-28 at 11 46 47 am](https://cloud.githubusercontent.com/assets/58878/7864317/4500d204-052f-11e5-98da-edd3a3cf770a.png)

Thanks.

**Comment by danpat** [comment]
Should we perhaps be displaying an error message in the target #div if WebGL support is not detected?

**Comment by jfirebaugh** [comment]
@danpat That's left up to developers, as they may want to handle lack of WebGL support differently, e.g. by falling back to raster tile map instead. To help with that, [`mapboxgl.supported()`](https://www.mapbox.com/mapbox-gl-js/api/#mapboxgl/supported) is provided.
