### ISSUE TITLE
box zoom should not reset bearing

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1225]
Currently the box zoom behavior is to reset the bearing to 0. This means that box zooming doesn't actually zoom to the box if the map was rotated. Instead, it should keep the current bearing.

**Comment by 1ec5** [comment]
#1340 tracks a simple fix for this issue. #1338 tracks a fix that would correctly fit to a rotated bounds.

**Comment by andrewharvey** [comment]
I presume this would mean that `map.fitBounds(map.getBounds())` on a rotate map would retain the map's rotation rather than resetting it to 0.

**Comment by lucaswoj** [comment]
Merged with #2112
