### ISSUE TITLE
Access tokens for developers

### ISSUE THREAD

**Issue by korywka** [mapbox/mapbox-gl-js#12253]
Today I discovered that my example page with controls stopped to work: https://www.npmjs.com/package/mapbox-gl-controls

The reason is:
```
Reactivate your account
Your account has been deactivated. This could be due to a card expiration, insufficient funds, card number change, etc. Reactivate your account by adding a credit card below.
```

I don't use mapbox for now for any business. In spite of that I was developing new v2 version with new raster control (I think this control is unique for mapbox controls ecosystem). Motivation? None. Just for fun.

But how it should be fun when you block my account? I am sure I was below free limit.

Please, consider to separate business and developers. I switched several companies from Google maps to MapBox (and wrote about this [blog post](https://dev.to/korywka/from-google-maps-to-mapbox-4nfk)). Some of these companies pay you ~100k/year.

I definitely will stop support for open source packages and "propaganda" of MapBox in case you block open source developer's accounts.

**Comment by mourner** [comment]
Hey, this does look like an accidental blunder on the Mapbox part, definitely no intent to annoy open source devs like you — sorry! Let me ping the right people to take care of this 🙏

**Comment by korywka** [comment]
Looks like account was blocked because I didn't have address filled in. Thank you for help!
