### ISSUE TITLE
geometry-type filter doesnt work on Multi-Geometries for geojson

### ISSUE THREAD

**Issue by enersis-pst** [mapbox/mapbox-gl-js#12256]
https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#geometry-type
tells geometry-type filter should work for Multi-Geometries on geojson but for me it doesnt. See example.

**mapbox-gl-js version**: 2.10.0

**browser**: chrome

### Steps to Trigger Behavior

 1. open example
 2. find the circle ;-)
 3. replace `MultiPoint` by `Point` in filter and tada...

### Link to Demonstration
https://jsfiddle.net/3fvp8hd7/3/

### Expected Behavior
circle should be shown

### Actual Behavior
circle isnt shown

**Comment by SnailBones** [comment]
Thanks for opening this issue @enersis-pst! This seems to be an issue with the docs, and I've opened a ticket to fix it [here](https://github.com/mapbox/mapbox-gl-js/pull/12257).
