### ISSUE TITLE
Too slow on Chrome Mobile

### ISSUE THREAD

**Issue by tiagofassoni** [mapbox/mapbox-gl-js#1226]
I tested with the default style map and it is too slow: https://www.mapbox.com/mapbox-gl-styles/#14.45/-23.5381/-46.6551

I also made a visualization using version 0.7 and leaflet. It broke down rendering São Paulo, I couldn't move the map.

**Comment by tiagofassoni** [comment]
By the way, I was testing with a Moto G 2nd edition.

**Comment by mourner** [comment]
Is it too slow but working, or just not interactive? If the latter, we have that coming in #949.

**Comment by tiagofassoni** [comment]
Well, this is actually about it being slow. It's rendering at about 11 fps on my chrome mobile on a Moto G 2nd edition.

The scroll also has issues, but I'm talking about the speed.

**Comment by mourner** [comment]
I think this is a hardware limitation, and not something we can easily fix on the GL JS side.

**Comment by kkaefer** [comment]
It's not necessarily a hardware limitation; the Moto G 2 renders just fine with the native Android app; so it's likely that the slowdown is either from the discrepancies between GL/JS and GL/Native (tessellation), V8/JavaScript, or the Chrome WebGL bindings, or a combination thereof.

**Comment by mourner** [comment]
Yeah, I meant hardware or WebGL implementation limitation. It may be improved in future with things like #682, but there's no sense keeping this as a separate open ticket.
