### ISSUE TITLE
Mapbox  match polygon with circle?

### ISSUE THREAD

**Issue by erkanisuf** [mapbox/mapbox-gl-js#12278]
I attach the example screenshot.
 Is there a way to match this orange point with that polygon .
 I know there is possibility to match them somehow with feature ids  but is there any other way if in case there aren't any matching object properties?
Something similar to the method from ```turf``` package ``` booleanPointInPolygon``` but this one will match only if the dot is inside the polygon.

![Screenshot 2022-10-04 at 15 07 20](https://user-images.githubusercontent.com/63913743/193815335-0a35e243-e4bf-4fd9-a0ef-6d6a3d1bdfd2.png)

**Comment by enersis-pst** [comment]
it depends what join you want. you can create a convex hull and check if it inside this area. But if features are connected by each other then best to work with a id.
But this is a topic for turfjs.

**Comment by mourner** [comment]
Calculating a convex hull of a polygon before checking a point against the hull is a good idea to try. But this is more of a generic mapping question that one specific to GL JS, so let me close this.
