### ISSUE TITLE
Loading mapbox-gl.min.js 2.10.0 - Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by wreiske** [mapbox/mapbox-gl-js#12285]
**mapbox-gl-js version**: 2.10.0

**browser**: Google Chrome Version 106.0.5249.103 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Try to load the minified version of 2.10.0
 
### Link to Demonstration

Example with minified version loaded using jQuery.getScript https://jsfiddle.net/23yzm18b/
![image](https://user-images.githubusercontent.com/6295044/194568679-c1a9560e-063c-406d-a673-644f3a16605a.png)

Example with minified version loaded using HTML script tags https://jsfiddle.net/23yzm18b/2/
![image](https://user-images.githubusercontent.com/6295044/194569891-878f6179-d3a4-47d8-bc80-7300bdf247d3.png)

Example with non-minified version https://jsfiddle.net/23yzm18b/1/
![image](https://user-images.githubusercontent.com/6295044/194568954-b911eff3-2958-45a5-98ae-a82a617aa612.png)

### Expected Behavior
The minified version should be free of any javascript console errors.

### Actual Behavior

See the demonstration above.

```
mapbox-gl.min.js:8 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at new ds (mapbox-gl.min.js:8:75140)
    at new cd (mapbox-gl.min.js:1:82830)
    at hr (mapbox-gl.min.js:1:113986)
    at dr (mapbox-gl.min.js:1:115080)
    at mapbox-gl.min.js:8:17152
    at new Ho (mapbox-gl.min.js:8:17364)
    at new sn (mapbox-gl.min.js:8:23521)
    at mapbox-gl.min.js:8:85039
    at e (mapbox-gl.min.js:1:602)
    at mapbox-gl.min.js:8:333115
```

**Comment by mourner** [comment]
You might want to submit an issue to CDN JS. Official minified distribution of GL JS is here https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.js
