### ISSUE TITLE
Mapbox-gl-js throws an  error on Firefox & Safari and doesn't load images - [Error: OffscreenCanvas is not defined]

### ISSUE THREAD

**Issue by NefrayLaysh** [mapbox/mapbox-gl-js#12282]
**mapbox-gl-js version**: v2.10.0
**library-using-mapbox**: react-map-gl v7.0.19
**browser**: Firefox 104.0.2 (64-bit) & Safari 16.0

### Steps to Trigger Behavior

 1. Load map on Forefox | Safari

Code: 

</ReactMapGL
       ref={mapRef}
       initialViewState={viewport}
       mapStyle={mapboxStyles}
       mapboxAccessToken={mapboxToken}
       maxZoom={18}
>

### Expected Behavior

![example-chrome](https://user-images.githubusercontent.com/103362930/194293020-318dee61-7a37-43da-a3ab-01a616b7c91d.png)

### Actual Behavior
![example-firefox](https://user-images.githubusercontent.com/103362930/194293063-631a849a-17a4-42e4-a9d1-2c5263328c01.png)

**Comment by ansis** [comment]
Hi, we're unable to reproduce the issue.

Can you share a full code example?
Does it reproduce with https://docs.mapbox.com/mapbox-gl-js/example/simple-map/ ?
Does it work with earlier versions of mapbox-gl-js?

**Comment by NefrayLaysh** [comment]
I shall create a new Project where I will replicate my issue, and send you the code. I'm using react-map-gl v7.0.19. So I assume the library uses latest mapbox-gl-js. I shall give you all needed details until the end of this week.

**Comment by NefrayLaysh** [comment]
Okey, so If you install **react-map-gl** with latest **mapbox-gl** everything is working fine. 
It seems that my project is using **maplibre-gl v2.0.0-pre.1** which uses **mapbox-gl v1.13.2**. So I assume if I update the mapbox-gl version to the new one, everything will be working fine.
Sorry for the inconvenience. I assumed that I'm using newest version of mapbox-gl, this was big overlook on my part.
I will try to update mapbox-gl to the new version and I will update you with the result, so this issue can be closed. Thanks.
