### ISSUE TITLE
Cannot get point properties on click

### ISSUE THREAD

**Issue by marcelo2605** [mapbox/mapbox-gl-js#12296]
**mapbox-gl-js version**: 2.10.0

**browser**: all

### Steps to Trigger Behavior

 1. Open the link
 2. Click on the back button
 3. Check the popup content

### Link to Demonstration

[https://codepen.io/marcelo2605/pen/QWrzLRP?editors=0010](https://codepen.io/marcelo2605/pen/QWrzLRP?editors=0010)

### Expected Behavior

Show property value

Based on issue #11567, I also tried disable all extensions without success.

**Comment by Sh1-5** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48705798/195243390-bf17956b-e0c2-4eee-88aa-c37968255cc6.png">

**Comment by Sh1-5** [comment]
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/48705798/195243390-bf17956b-e0c2-4eee-88aa-c37968255cc6.png">

Chrome 106.0.5249.103

**Comment by enersis-pst** [comment]
for me it works ff & chrome under mac.

**Comment by ansis** [comment]
@marcelo2605 I'm also unable to reproduce the issue.

What platforms/browsers are you seeing the error with?
Does it it consistently not work, or only sometimes?
Are there any errors in the javascript console?
Does it work with earlier versions of mapbox-gl-js?

**Comment by marcelo2605** [comment]
Thanks for the replied. I'm testing on Ubuntu 22.04/Chrome 106.0.5249.91. I tested again right now and it's working. Closing this topic.
