### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1229]
So far there's very little internal documentation in mapbox-gl-js besides what I've written in guessed JSDoc comments. Given the amount of information sharing in gl-js, it's extremely hard to reason about how, for instance, [collisionbox](https://github.com/mapbox/mapbox-gl-js/blob/master/js/symbol/collision_box.js) is used without reading five or six other files.

We need documentation.

* Classes like CollisionBox should have a one-sentence summary of what they **are** and what they **do**.
* Chains-of-command like parsing should have a high-level architecture document explaining how the parts connect

/cc @ansis @kkaefer @jfirebaugh @mourner

**Comment by tmcw** [comment]
talked with @ansis about this, and he's working on a branch

**Comment by tmcw** [comment]
@ansis 

Doc requests

* What is a bucket? How does it relate to a layer in a vector tile? How does it relate to a layer in a style?

**Comment by tmcw** [comment]
@ansis ping - any luck writing some docs?

**Comment by ansis** [comment]
I documented the collision code in https://github.com/mapbox/mapbox-gl-js/pull/1261/files but thats all so far

**Comment by tmcw** [comment]
The documentation is way better now!

**Comment by Randgalt** [comment]
> The documentation is way better now!

This is considered better? Mapbox.js is reasonably documented. Mapbox GL appears to be a step backward in every way I can imagine. Maybe it's time to look for an alternative to Mapbox :(

**Comment by jfirebaugh** [comment]
Hi Jordan, sorry to hear you're feeling frustrated by the documentation. Would you mind sharing some specifics about what you're looking for but could not find, so that we could improve it?

**Comment by Randgalt** [comment]
I'm moving away from Mapbox.js as the mobile support is lacking. I'm trying to simulate markers from Mapbox.js. I've seen all kinds of random docs regarding style sheets, sprites, raster, etc. It's all disconnected and without context. I would simply like to be able to move from Mapbox.js and have markers.

**Comment by jfirebaugh** [comment]
Ok, here's what we have on markers in Mapbox GL:

* Example: [Add custom icons with Markers](https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/)
* Example: [Attach a popup to a marker instance](https://www.mapbox.com/mapbox-gl-js/example/set-popup/)
* Blog post: [Custom HTML markers in Mapbox GL JS](https://www.mapbox.com/blog/custom-markers-mapboxgl/)
* [API documentation for Marker](https://www.mapbox.com/mapbox-gl-js/api/#Marker)

Do any of those help clear things up? What else could we improve?

**Comment by Randgalt** [comment]
Those markers are nothing like the markers in Mapbox.js. They don't scale with the map, you have to provide your own image, etc. etc. Further, elsewhere I read about some kind of built in support for "sprites" in Mapbox GL. How do I use the provided sprites for markers or is that not possible? 

So, in short, what's missing is an upgrade path from Mapbox.js markers. I brought this up over a year ago and can't believe it's still not addressed.

**Comment by jfirebaugh** [comment]
I've opened an issue for providing `Marker` with a default image: #3557.

Can you say more about what you mean by "scale with the map"? Offhand I'm not aware of any scaling behavior for Mapbox.js/Leaflet markers.

[Sprites](https://www.mapbox.com/mapbox-gl-style-spec/#sprite) are an image resource for Mapbox Styles, in particular [symbol layers](https://www.mapbox.com/help/style-symbol-layer-studio/). Both Markers and symbol layers can be used to represent point features on the map. Markers are rendered with HTML and DOM elements, while symbol layers are rendered with WebGL. In terms of similarity with Mapbox.js/Leaflet, Mapbox GL JS Markers are much more like Leaflet Markers than symbol layers are.
