### ISSUE TITLE
How can I get the location whether it is the city, street, when moving the draggable marker?

### ISSUE THREAD

**Issue by luispv02** [mapbox/mapbox-gl-js#12302]
Hello, I have a map on my website which I add a draggable marker to, when I move the marker I get the coordinates and save them in a store, but I also want to get either the street, city or neighborhood of these coordinates, is there a way to get this data in mapbox gl?

Here I get the coordinates, how could I get the location of those coordinates?

              `const marker = new mapboxgl.Marker({
                    draggable: true
                })
                .setLngLat(e.result.center)
                .addTo(map)

                marker.on('dragend', (e) => {
                    const lgn = e.target._lngLat.lng
                    const lat = e.target._lngLat.lat

                    landsStore.center = [lgn, lat]
                    map.getSource('circle').setData(geoJSONCircle.value.data);

                })`

**Comment by uvishere** [comment]
You can use Mapbox geocoding API to convert your coordinates to an address text. In your case, you need to use a reverse geocoder which will convert the coordinate to address.

For more details:
[https://docs.mapbox.com/help/getting-started/geocoding/](https://docs.mapbox.com/help/getting-started/geocoding/)

**Comment by mourner** [comment]
Thanks for the answer @uvishere, you're correct! @luispv02 this task is called Reverse Geocoding, and Mapbox provides an API for it — see the docs here: https://docs.mapbox.com/api/search/geocoding/#reverse-geocoding
