### ISSUE TITLE
How can I restore the default native browser contextmenu?

### ISSUE THREAD

**Issue by dawidow** [mapbox/mapbox-gl-js#12301]
**mapbox-gl-js version**: LTS

### Question

Hello folks. I have a question, that make me crazy. I want to bring back default native contextmenu when I clicking Right Mouse Button. How can I do that? I need this so that my clients can open the contextmenu and select "open in new window".

Below I upload a piece of my code written in react

```js
<ReactMapGL
  {...viewport}
  onLoad={(event) => {
    const mapObject = event.target;

    mapObject.dragRotate.disable();
    mapObject.touchZoomRotate.disableRotation();

    if (mapObject) {
      setMap(mapObject);
    }
  }}
  width="100%"
  height="100%"
  onMove={(event) => {
    const viewport = event.viewState;
    setViewport(viewport);
  }}
  onContextMenu={(event) => {
    console.log(event);

    // What should I do here to achieve that?
  }}
  mapboxAccessToken={"..."}
  mapStyle={"..."}
>
```

**Comment by mourner** [comment]
GL JS does not prevent the default browser context menu if the event isn't used for anything else. So to make this work, you need to:

- Disable the default right-click-drag behavior with `map.dragRotate.disable();`
- Make sure the map has no other `contextmenu` listeners (so, remove `onContextMenu` in your code)

Hope this helps!
