### ISSUE TITLE
It is odd when displaying polygon geojson data 

### ISSUE THREAD

**Issue by anders86755** [mapbox/mapbox-gl-js#12303]
I load a polygon geojson data.

map.on('load', () => {
        map.addSource('maine', {
            'type': 'geojson',
            'data': my_polygon
        });
        map.addLayer({
            'id': 'maine',
            'type': 'fill',
            'source': 'maine', // reference the data source
            'layout': {},
            'paint': {
                'fill-color': '#0080ff', // blue color fill
                'fill-opacity': 0.5
            }
        });
        map.addLayer({
            'id': 'outline',
            'type': 'line',
            'source': 'maine',
            'layout': {},
            'paint': {
                'line-color': '#000',
                'line-width': 3
            }
        });
    });

When I zoom map, the polygon display incorrectly。 It looks like a bug?

![微信截图_20221016202750](https://user-images.githubusercontent.com/40052500/196035776-92646196-df89-43c3-a1ac-f4bf9b134353.png)

![微信截图_20221016202818](https://user-images.githubusercontent.com/40052500/196035773-d6599fd4-fcfd-4f0d-8368-1c3584a19f40.png)

![微信截图_20221016202851](https://user-images.githubusercontent.com/40052500/196035768-fa74c9bb-f602-4e95-8152-43d47673c338.png)

The source code (include polygon geojson data ):
[polygon-geojson.zip](https://github.com/mapbox/mapbox-gl-js/files/9794496/polygon-geojson.zip)

or

Demo:  [demo](https://jsbin.com/meremo/1/edit?html,js,output)

**Comment by mourner** [comment]
Per the GeoJSON specification, polygon coordinates must be closed — meaning the last point matches the first. If you add the first point at the end in the demo above, it works properly:

<img width="858" alt="image" src="https://user-images.githubusercontent.com/25395/196043968-5a64f611-396f-4df9-9f86-f118a9aa47d7.png">

**Comment by anders86755** [comment]
> 

Thank you for your reply! you helped me solve a problem. very thanks!
