### ISSUE TITLE
How to fit the map inside the div container removing white spaces

### ISSUE THREAD

**Issue by PterPmnta** [mapbox/mapbox-gl-js#12316]
**mapbox-gl-js version**: 2.10.0

### Question

I'm using mapbox-js API for a web app, but I couldn't figure out how to fit the map, avoid draggable, and appear a white frame at the top and bottom.

![Normal when load the compnent](https://i.stack.imgur.com/TEHPe.png)

![top white](https://i.stack.imgur.com/agemw.png)

![bottom white](https://i.stack.imgur.com/P7BjD.png)

I have been trying with multiple solutions, the first, was the normal way that using, but that's not my case, due my map is a child component into the father component

### child component

```
<div class="col-12">
  <div class="row">
    <div class="col-6 ml-0">
      <b>Needs to know:</b>
      <span class="text-primary ml-3">
        <b>4
          <span class="material-icons check-icon-position mr-1">
            check_circle_outline
          </span>
        </b>
      </span>
      |
      <span class="text-danger ml-2">
        <b>2 ETA Delay</b>
      </span>

    </div>
    <div class="col-6 d-flex flex-row justify-content-end align-items-start">
      <p class="text-muted">Style map:</p>
      <input type="radio" class="btn-check ml-3" name="options" id="option1" autocomplete="off" checked>
      <label class="btn btn-light ml-3 btn-style-position text-muted" for="option1" (click)="setGrayStyle()"><b>Gray</b></label>

      <input type="radio" class="btn-check ml-3" name="options" id="option2" autocomplete="off">
      <label class="btn btn-light ml-3 btn-style-position text-muted" for="option2" (click)="setDarkStyle()"><b>Dark</b></label>

      <input type="radio" class="btn-check" name="options" id="option4" autocomplete="off">
      <label class="btn btn-light ml-3 btn-style-position text-muted" for="option4" (click)="setColorStyle()"><b>Color</b></label>
    </div>
  </div>
</div>
<div id="map-container" class="col-12">
  <div #miniMapa class="mapa-acordeon border-rnd-map"></div>
</div>
```

### father component

```
<details>
  <summary class="bg-light text-dark">
    <nav class="navbar navbar-light
                bg-light fs-3 justify-content-end"
                (click)="changeMapArrow()">
      <span class="material-icons">
        <b>{{arrowClass}}</b>
      </span>
    </nav>
  </summary>
  <div class="row d-flex flex-column">
    <app-mini-map></app-mini-map>
  </div>
</details>
```

I had been used this way, like is showing in the official page

```
body { margin: 0; padding: 0; }
#map { position: absolute; top: 0; bottom: 0; width: 100%; }
```

I found this in one answer, but doesn't work

```
<div id="map-container">
  <div id="map">
  </div>
</div>

#map-container {
    position: relative;
    height: 180px;
    width: 600px;
}

#map {
    position: relative;
    height: inherit;
    width: inherit;
}
```

Even if I remove the CSS about position and things that maybe could cause any issue, still happens

![canvas1](https://i.imgur.com/F1id7Y5.png)

![canvas2](https://i.imgur.com/4zJ3TUc.png)

![canvas3](https://i.imgur.com/4LRCuaW.png)

**Comment by mourner** [comment]
Could you please describe what you're trying to do more clearly? It's a little hard to understand from the description above. 

To stop a container inside the map from passing mouse/touch events through, you should do something like `el.addEventListener('mousedown', (e) => e.stopPropagation(), false)`.

For positioning issues, it looks more like a generic CSS question rather something GL JS specific...

**Comment by PterPmnta** [comment]
@mourner I'm trying to load the map, from the child component, to the father component, but, maybe the error, is because the father component is a summary/details HTML tag. The idea, is to lock the map in the area, like happens in any example on the official page. That you can scroll to zoom out, but when the scroll rise to the limit, the map doesn't show the those white frame.

**Comment by PterPmnta** [comment]
I'm going to create a new issue to explain everything.
