### ISSUE TITLE
Overzoom vector tiles not working when filter is added to layer

### ISSUE THREAD

**Issue by Bemjamin** [mapbox/mapbox-gl-js#12314]
Hello, 

Our tiles are generated until zoom 10, but our map goes until zoom 14. When we don't use filters, the map keeps showing the circles until the maxzoom. When we add any filter, the tiles disappear after the 10th zoom. 

**mapbox-gl-js version**: 2.10

**browser**: Chrome 104.0.5112.101

Filter until zoom 10:

<img width="548" alt="image" src="https://user-images.githubusercontent.com/1276294/196470241-446cb9c7-0494-4cb5-a6ef-6192c10517a5.png">

Filter after zoom 10:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/1276294/196471101-7daff922-9d71-490a-9fb8-59bb46882955.png">

No filter until zoom 14:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/1276294/196471327-5e6d1aea-3238-48f3-bd2f-f246e9ac4e35.png">

**Comment by mourner** [comment]
@Bemjamin can you please provide a minimal live example reproducing the issue, as prompted by the issue template? We won't be able to diagnose this with screenshots and short description alone.

**Comment by Bemjamin** [comment]
Hello @mourner I just found the problem on our end, I will be closing the issue.
