### ISSUE TITLE
New permission dialog “://” Would Like To Use Your Location in Safari

### ISSUE THREAD

**Issue by yeener** [mapbox/mapbox-gl-js#12327]
**mapbox-gl-js version**: 2.9.2
**browser**: Safari (Version 15.41+ for iOS)

### Steps to Trigger Behavior

We use mapbox-gl in our Apache Cordova app. Recent changes from version 2.8.2 to 2.9.2 introduced a new location permission dialog from Safari with a bad app name. I tracked down the root cause of the problem first appears with version 2.9.0. This version introduced a new geolocation feature (https://github.com/mapbox/mapbox-gl-js/pull/10400). Due to a bug this feature was not active in Safari until corrected in version 2.9.2 (https://github.com/mapbox/mapbox-gl-js/pull/12080).

![IMG_E0066](https://user-images.githubusercontent.com/57756841/197226960-88e89b12-bf74-4f9c-8ac1-6f6ba43b9e15.JPG)

### Expected Behavior

No message appears like in the previous version 2.8.2

### Actual Behavior

The message **“://” Would Like To Use Your Location** appears every time the app is restarted and the user clicks on the location button (see attached image).

### Related Issues
- https://github.com/mapbox/mapbox-gl-js/pull/10400 (v2.9.0)
- https://github.com/mapbox/mapbox-gl-js/pull/12080 (v2.9.2)

**Comment by jorgegvillanueva** [comment]
Same issue here using capacitor 4.
I just tried to get permissions with capacitor Geolocation plugin but at the moment when mapbox take geolocation control shows that awful permissions prompt

**Comment by stepankuzmin** [comment]
Hi,

Thanks for using Mapbox GL JS. According to the Apple docs on the [Location Services](https://support.apple.com/en-us/HT203033), the first time an app tries to access a location on iOS and iPadOS, it must ask for the user's permission. You see a prompt explaining which app is asking for permission to use your location as well as the app developer's reason for requesting it.

You should be able to update the `info.plist` of your app to set the proper app name and the reason that the app accesses the user's location. You can also refer to the Cordova and Capacitor geolocation plugins docs:
* https://cordova.apache.org/docs/en/11.x/reference/cordova-plugin-geolocation/
* https://capacitorjs.com/docs/apis/geolocation

I'm closing this issue as there is not much we can do on the GL JS side, but feel free to reopen this issue if you have any questions.
