### ISSUE TITLE
How to calculate Map bounds in 3857 when map Rendered in 3d 

### ISSUE THREAD

**Issue by chakravarthi-vl** [mapbox/mapbox-gl-js#12378]
Hi

When I Am using  2d maps I am using  [proj4js](http://proj4js.org/#:~:text=Proj4js%20is%20a%20JavaScript%20library,the%20MetaCRS%20group%20of%20projects.)

Is there any logic or Existing Method available to compute bounds in 3857 when i am using 3d maps.

**Comment by karimnaaji** [comment]
@chakravarthi-vl I think you need to give a look at the [`getBounds`](https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/map.js#L807) map API. In 3d maps, it accounts for both globe or terrain.

>Returns the map's geographical bounds. When the bearing or pitch is non-zero, the visible region is not
>an axis-aligned rectangle, and the result is the smallest bounds that encompasses the visible region.
>If a padding is set on the map, the bounds returned are for the inset.
>With globe projection, the smallest bounds encompassing the visible region
>may not precisely represent the visible region due to the earth's curvature.

With terrain, refer to the logic from `getBounds3d` [here](https://github.com/mapbox/mapbox-gl-js/blob/20659095a5cb09af1ff69a780b55a214def7549d/src/geo/transform.js#L1437).
