### ISSUE TITLE
Have two words for "Layer"

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1237]
* Layers are things you define in a style
* Layers are also things in a datasource

Two concepts deserve two words

**Comment by tmcw** [comment]
Given that in Painter, layers from tiles are VectorTileLayer instances, I think we should call them `vectorTileLayer`.

**Comment by peterqliu** [comment]
> layers from tiles are VectorTileLayer instances

would this be #1 or #2 ?

**Comment by tmcw** [comment]
I'm not sure what you mean. Say more?

**Comment by peterqliu** [comment]
Just confused whether "layers from tiles" means 

>Layers are things you define in a style

or

>Layers are also things in a datasource

**Comment by tmcw** [comment]
The second. Datasources have tiles which have layers

**Comment by peterqliu** [comment]
I get the feeling that anything long, like `vectorTileLayer` would get shorthanded back to "layer" over time.

How about a different word altogether? A crack at the thesaurus: `source-level` and `source-section` resonate with me.

![screen shot 2015-06-03 at 3 41 21 pm](https://cloud.githubusercontent.com/assets/4551508/7973118/2fac253e-0a07-11e5-96c4-0d2668ade1a1.png)

**Comment by anandthakker** [comment]
Not that anyone asked me, but I like @peterqliu's notion of chucking "layer" altogether.  And if that's gonna happen, it seems to me like the `layers` in a vector tile source are very close analogues to `FeatureCollection`s, so maybe something along those lines?

**Comment by nickidlugash** [comment]
> Layers are also things in a datasource

In the app we're calling these "subsets", right? I also like the idea of getting rid of "layer" altogether for these. Layers suggest groups that get stacked on top of each other (as style layers do), but data layers are more amorphous than that (at least in GL).

**Comment by tmcw** [comment]
Indeed, we always call vector-layers subsets in Studio

![2016-03-21 at 6 53 pm](https://cloud.githubusercontent.com/assets/32314/13936747/3d33acfc-ef96-11e5-8eae-2d5251bb9d79.png)

Question is whether mapbox-gl-style-spec, gl-js, gl-native, and so on can or should eventually use the same terminology / cc @lucaswoj

**Comment by lucaswoj** [comment]
> Question is whether mapbox-gl-style-spec, gl-js, gl-native, and so on can or should eventually use the same terminology

This would be a huge cross-product change. We should discuss in https://github.com/mapbox/mapbox-gl/issues/13
