### ISSUE TITLE
The boxzoomend event should provide the box coordinates

### ISSUE THREAD

**Issue by mholt** [mapbox/mapbox-gl-js#12405]
## Motivation

I'm trying to implement a "bounding box search" feature: the user can click+drag a box over the map to find results within that box.

[Conveniently, Mapbox GL JS already has a function to allow the user to draw a box. It even zooms into the selected area!](https://docs.mapbox.com/mapbox-gl-js/api/handlers/#boxzoomhandler)

Relevant events:

`boxzoomstart`: https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:boxzoomstart
`boxzoomend`: https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:boxzoomend

## Design Alternatives

Currently, doing this requires [a tedious amount of code to wrangle event handling, drawing a polygon, and setting the cursor](https://docs.mapbox.com/mapbox-gl-js/example/using-box-queryrenderedfeatures/).

All I really need are the 4 sides of the bounding box in lat/lon (max+min latitude, max+min longitude), after the box is created.

## Design

Add a `coords` property to the [`MapBoxZoomEvent`](https://docs.mapbox.com/mapbox-gl-js/api/events/#mapboxzoomevent) object with the 4 sides of the box.

### Mock-Up

```js
map.on('boxzoomend', event => {
    console.log(event.coords);
});
```

^ From that, I can perform a search in my application and display relevant results on the map.

Of course, since the primary purpose of this function is to zoom the viewbox, my application has a button to toggle the "create bounding box" state. If the user clicks the button, then draws a box, we use that box as a search parameter and deactivate the button state. This solves the problem of the user unintentionally revising their search when they mean only to zoom.

### Concepts

Uses only existing concepts as far as I can tell. Just providing the coordinates through the event.

### Implementation

When the event is generated, simply add `coords` to the event object's properties.

Thank you for considering!

**Comment by stepankuzmin** [comment]
Hi @mholt,

You can also use the ["Highlight features within a bounding box"](https://docs.mapbox.com/mapbox-gl-js/example/using-box-queryrenderedfeatures/) example as a reference. As far as I understand your use case, you'd only need to [unproject](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#unproject) the `bbox` from pixel coordinates to the geographical coordinates like this:

```js
const topLeft = map.unproject(bbox[0]);
const bottomRight = map.unproject(bbox[1]);
```
