### ISSUE TITLE
Mapbox-gl fill layer distorts rendering on higher zoom

### ISSUE THREAD

**Issue by trilokr** [mapbox/mapbox-gl-js#12426]
I'm using mapbox-gl version "https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"

I've drawn simple fill layers using GeoJSON source.

At a specific zoom level, the polygon renders as expected.

Expected Layer: Expected Layer

![Polygon_without_zoom](https://user-images.githubusercontent.com/119493935/204781973-d5b202ca-7484-472c-bd25-12202020fa84.PNG)

But on zooming in, the polygon distorts.
![polygon_broken](https://user-images.githubusercontent.com/119493935/204781912-eec35933-a89a-47b7-9d63-b56de274ecb6.PNG)

When I tried in Codepen with same coordinates then there is not issue for breaking polygon either higher zoom level or not..
### Link to Demonstration

Online URL- https://codepen.io/trawat/pen/GRGXEjE

Request you to pls advise where is the issue and how can we resolved it .. Thanks in advance!!

**Comment by stepankuzmin** [comment]
Hi @trilokr,

Thanks for sharing this. Unfortunately, with the example you provided, I couldn't reproduce it in the latest versions of Google Chrome, Firefox, and Safari. What browser do you use, and what is the viewport when you see such distortion?

<img width="1143" alt="Screen Shot 2022-11-30 at 13 38 55" src="https://user-images.githubusercontent.com/533564/204787164-2efb0fd7-bcc3-41fb-a2f5-70aa62199c0b.png">

**Comment by trilokr** [comment]
Hi @stepankuzmin, Thanks for your reply ...

I'm using the mapbox version as below -
CSS-:  "https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css"
JS-:   "https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"

Browser - Google chrome - Version - 107.0.5304.122 (Official Build) (64-bit)  

**Note-** Actually It's not distortion while same polygon coordinates using online but the issue occurred in my local angular application and using the above mentioned versions of Mapbox and Google Chrome browser.. 
 
Pls let me know if you required any further information ... thanks!!

**Comment by stepankuzmin** [comment]
Are you able to reproduce it in the Codepen? https://codepen.io/trawat/pen/GRGXEjE
Could you please also share the map center and zoom when this happens?

**Comment by trilokr** [comment]
No!! that's I had mentioned .... it's not replicated online (in CodePen) but the issue is happened in Angular application locally..

Map center- -98.58, 39.50,
Zoom- 3.3
Also using,  max zoom- 18

**Comment by stepankuzmin** [comment]
I assume that there might be some differences in the setup, then. Probably, some data issue. Could you please check that you pass the same data in the Codepen and the app?

**Comment by trilokr** [comment]
Yes!! Thanks @stepankuzmin  for providing such a useful thought.. the issue has resolved and it's working fine now ..

**Comment by stepankuzmin** [comment]
👍
