### ISSUE TITLE
get all features in view

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1242]
We should add an API that lets one visit each feature in a loaded tile in view. This would be like featuresAt, but with an infinite radius.

**Comment by anandthakker** [comment]
@tmcw :+1: this would be nice to have, and it's not easy to simulate at present, because `featuresAt` only gives you the features in the tile containing the point you request--sliced at the tile boundary, of course.

**Comment by jfirebaugh** [comment]
#1302
