### ISSUE TITLE
Implement occludedOpacity for symbols

### ISSUE THREAD

**Issue by slavanga** [mapbox/mapbox-gl-js#12424]
For markers a new option called `occludedOpacity` was added.
This will prevent markers behind 3D (mapbox-raster-dem) terrain to be dimmed.

- [Issue: Markers are visible when behind terrain](https://github.com/mapbox/mapbox-gl-js/issues/12123)
- [Docs](https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker#setoccludedopacity)
- [PR](https://github.com/mapbox/mapbox-gl-js/pull/12258)

The same option would be very helpful to have for symbol layers too.

![dimmed-markers](https://user-images.githubusercontent.com/1077807/204588411-5472581a-c517-45bf-9c3e-351dfc1f0199.png)

**Comment by alexey-romanov** [comment]
This functionality for symbol layer was added in [3.6.0](https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.6.0) via two new symbol layer properties: `icon-occlusion-opacity` and `text-occlusion-opacity` which specify opacity multiplier in case of being occluded by 3d content (terrain, landmarks, 3d models, fill extrusions, ...).
