### ISSUE TITLE
Remove background or change color of the popup

### ISSUE THREAD

**Issue by PterPmnta** [mapbox/mapbox-gl-js#12433]
**mapbox-gl-js version**: 2.10.0

### Question

How I could remove the color or background color of the popup?

I'm using Mapbox in a project with Angular 10 and could not remove o change the color of the background. I had been trying many options including the recommended by the mapbox-gs-js API with the use my own classes using this way

```
.rmv-bg-color
 background: red !important
 background-color: !red important

const popup = new mapboxgl.Popup({ offset: 25, className: 'rmv-bg-color' })
        .setMaxWidth('200')
        .setHTML((await customMarker).popup)
        .trackPointer();
``` 

Or using the same class of the div in the DOM

```
.mapboxgl-popup-content
  background: red


.mapboxgl-popup-tip
  background: red
```

```
setMarkerForBounding(markersToRender, longlatPoints){

    markersToRender.forEach(async (marker) => {

      const customMarker = this.newMapService.createMarker(marker);

      const popup = new mapboxgl.Popup({ offset: 25 })
        .setMaxWidth('200')
        .setHTML((await customMarker).popup)
        .trackPointer();

      new mapboxgl.Marker({element: (await customMarker).marker, rotation: marker.angle})
        .setLngLat(marker.currentPosition)
        .setPopup(popup)
        .addTo(this.mapa);
    });

    const pointsToFit = this.newMapService.getBoundingArea(longlatPoints);
    this.fitBounding(pointsToFit);
  }
```

**Comment by stepankuzmin** [comment]
Hi @PterPmnta,

Thank you for using mapbox-gl-js! You should be able to override the styles using the classes `.mapboxgl-popup-content` and `.mapboxgl-popup-tip`, so make sure you correctly override these styles in your setup.

This issue tracker is for reporting bugs and feature requests. You might consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.

I'll close this issue, but feel free to reopen it if you have questions.

**Comment by PterPmnta** [comment]
@stepankuzmin Hi, I had been trying many solutions but doesn't work for me.
