### ISSUE TITLE
Empty package.json

### ISSUE THREAD

**Issue by saeedghasemi72** [mapbox/mapbox-gl-js#12443]
**mapbox-gl-js version**: 2.11.0

### Question
Hi guys, why package.json inside dist is empty object? I get this error:
No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file ~/node_modules/mapbox-gl/dist/package.json, or manually specify version in shared config.

**Comment by mourner** [comment]
You can find the reason in #10367 which introduced it. We can't remove it for compatibility reasons, so you'll have to tweak your dev setup to not complain about that file (I wonder which tool exactly produces the error?).

> 1. `"type": "module"` field was added to `package.json` to make sure every `.js` file in the project is treated as ESM. However, to support using `import mapboxgl from 'mapbox-gl'` or `require('mapboxgl')` from Node, the UMD bundles including the main entry point (`dist/mapbox-gl.js`) need to be treated as CommonJS, so this required adding a `{"type": "commonjs"}` `package.json` in the `dist` folder (Node resolution determines the type going through parent folders until it finds a `package.json`). This broke `webpack` bundling for unclear reasons, but Node docs state that it will treat files as `commonjs` if `type` isn't specified, so I had to leave a type-less `package.json` (`{}`) to satisfy both Webpack and Node.
