### ISSUE TITLE
Set different colors between waypoints in route

### ISSUE THREAD

**Issue by IgorMakara** [mapbox/mapbox-gl-js#12452]

**Comment by IgorMakara** [comment]
![image6](https://user-images.githubusercontent.com/19820109/206424757-b19fa836-bbc4-45f2-9012-2217f6e991d6.png)

**Comment by stepankuzmin** [comment]
Hi @IgorMakara,

Thank you for using mapbox-gl-js. This issue tracker is for reporting bugs and feature requests. Please provide a minimal, complete, verifiable demonstration of the issue to help the maintainers and community understand and address the problem accurately.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.

**Comment by linze99** [comment]
you can seperate the route into 3 lines, that each line has a property of color, 
than provide a expression to the paint property
just like:
```js
const data = [{geometry:{coordinates:[...], properties:{color: "#ff0000"}},{}];
map.addLayer(
          {
            id: "lineLayer",
            source: "lineSource",
            type: "line",
            layout: {
              "line-join": "round",
              "line-cap": "round",
            },
            paint: {
              "line-width": 3,
              "line-color": ["get", "color"], 
            },
          }
        );
```
