### ISSUE TITLE
Remove LineBucket.addFeature

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1245]
Looks like this method adds indirection without encapsulation

https://github.com/mapbox/mapbox-gl-js/blob/77acaedd0069165c0916dc9a899f2184b78cd4b7/js/data/line_bucket.js#L13-30

**Comment by tmcw** [comment]
Same with FillBucket: I don't see any reason for addFeature to be a function. https://github.com/mapbox/mapbox-gl-js/blob/77acaedd0069165c0916dc9a899f2184b78cd4b7/js/data/fill_bucket.js#L12-24

**Comment by jfirebaugh** [comment]
Tests are using `addFeature` and the vector-tile API does not make it easy to remove right now. Maybe if https://github.com/mapbox/vector-tile-js/pull/34 lands.
