### ISSUE TITLE
Orient CJK glyphs vertically along vertically oriented lines

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#1246]
For consistency with mapbox/mapbox-gl-native#1682, CJK labels running along north-south roads (or roads that go from top to bottom due to map rotation) should orient glyphs vertically.

/cc @ansis @nickidlugash @mikemorris

**Comment by yhahn** [comment]
Braindumping notes from discussion today:

------

### Currently

- Symbol bucket generates 2 orientations of quads (upright, flipped) for line labels

### Proposal

- Generate all 4 orientations of quads when condition X is met (???)
  - a label is in CJK ?
  - by some style spec property?
  - Ref: https://github.com/mapbox/mapbox-gl-js/blob/3a859f31012f3485eccd17889e5abe27b9a94aaa/js/symbol/quads.js#L158-L161
- Assumption: the vertical-label orientation of quads can use the same placement as normal labels with a quad-centric rotation (assumes CJK-ish characters)
- Add logic to symbol_bucket to select right set of quads based on 4 quadrants of rotation
  - Ref: https://github.com/mapbox/mapbox-gl-js/blob/3a859f31012f3485eccd17889e5abe27b9a94aaa/js/data/bucket/symbol_bucket.js#L467-L469

Probably: no shader changes, little affect on performance/data except other than symbol buffer transferred between workers.

### Other questions

- How to handle mixed characterset scenarios, examples from @nickidlugash:
  - `汉字 McDonald's`
    - when rotated shows vertical quads for `汉字` and upright quads for `McDonald's`
  - `汉字A`
    - when rotated shows vertical quads for `汉字A`

**Comment by lucaswoj** [comment]
Also, thanks to @mikemorris for pointing us towards a paper on robust vertical layout in unicode http://unicode.org/notes/tn22/RobustVerticalLayout.pdf

**Comment by 1ec5** [comment]
Since I can’t find a better place for this little nugget of knowledge, [this Wiktionary module](https://en.wiktionary.org/wiki/Module:scripts/data) contains character ranges for all the CJK writing systems. Of particular interest are `Hang`, `Hani`/`Hans`/`Hant`, `Hira`, `Kana`, `Kore`, `Jpan`, and `Mong`.

/cc @xrwang @nickidlugash

**Comment by 1ec5** [comment]
> How to handle mixed characterset scenarios

On OpenStreetMap, and therefore in Mapbox Streets, mixed CJK/romanized labels are ubiquitous on roads in [Hong Kong](http://www.openstreetmap.org/way/45740459), [Macao](http://www.openstreetmap.org/way/164166938), and [Shenzhen](http://www.openstreetmap.org/way/269895566). For example, [this way](http://www.openstreetmap.org/way/45740459) is tagged `name=海底隧道 Cross-Harbour Tunnel`. Unless we take care to rotate the Latin glyphs and advance them by the normal horizontal advance (rather than the glyph height), the label will become much longer when oriented vertically and stand a much higher chance of getting collided out.

**Comment by lucaswoj** [comment]
> Unless we take care to rotate the Latin glyphs and advance them by the normal horizontal advance (rather than the glyph height), the label will become much longer when oriented vertically and stand a much higher chance of getting collided out.

This should be fairly easy the way #3438 is now written. I'll move this into that PR's launch checklist.

**Comment by 1ec5** [comment]
#3470 tracks vertical text layout for point-placed labels.

**Comment by 1ec5** [comment]
> Unless we take care to rotate the Latin glyphs and advance them by the normal horizontal advance (rather than the glyph height), the label will become much longer when oriented vertically and stand a much higher chance of getting collided out.

→ #3506
