### ISSUE TITLE
Add Feature to style circle or other shapes  

### ISSUE THREAD

**Issue by afzalsmam** [mapbox/mapbox-gl-js#12471]
I love MapBox so far but I could not find any way to easily change circle border radius or change different shapes for layer types. I would really appreciate it if you add it. Thanks

**Comment by enersis-pst** [comment]
for circle
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-circle-circle-radius
https://docs.mapbox.com/mapbox-gl-js/example/multiple-geometries/

for different shape you need to create your own symbol-image and use the symbol layer
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#symbol
https://docs.mapbox.com/mapbox-gl-js/example/add-image/

**Comment by avpeery** [comment]
Thanks for using mapbox-gl-js @afzalsmam! For circles, you can change the border color, width and opacity using `circle-stroke-*` see [docs](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-circle-circle-stroke-color) in the layer. I think this [example](https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/) is helpful using a heatmap to demonstrate using a border around a circle. 

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.

**Comment by afzalsmam** [comment]
> I love MapBox so far but I could not find any way to easily change circle border radius or change different shapes for layer types. I would really appreciate it if you add it. Thanks

Thanks for your reply, I tried using the symbol with icon-image but I want to show a number on the specific coordinate too and I don't know why but I think it's because number/text also comes in symbol type I am not able to show both symbol layers together. I want to achieve something like in the attached image.

![rounded rectangle ](https://user-images.githubusercontent.com/31804022/209049828-890efeff-4cfd-4410-aab9-5874fade2c14.jpg)

**Comment by afzalsmam** [comment]
> Thanks for using mapbox-gl-js @afzalsmam! For circles, you can change the border color, width and opacity using `circle-stroke-*` see [docs](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-circle-circle-stroke-color). I think this [example](https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/) is helpful using a heatmap to demonstrate using a border around a circle.
> 
> For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.
> 
> You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.

Thanks for your reply. I will be posting queries on the link you provided next time. Thank you
