### ISSUE TITLE
move all attribute binding to buffer objects, or out of all of them

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1247]
IconVertexBuffer and Glyph vertex buffer bind attribute points within their .bind() call.
https://github.com/mapbox/mapbox-gl-js/blob/a9d2c42e7b1e51f763f2ace825fc61867daaa4b9/js/data/buffer/icon_vertex_buffer.js#L44-L47
https://github.com/mapbox/mapbox-gl-js/blob/a9d2c42e7b1e51f763f2ace825fc61867daaa4b9/js/data/buffer/glyph_vertex_buffer.js#L45-L49

LineVertexBuffer and FillVertexBuffer don't. The attributes get bound in drawLine and drawFill instead.

We should either move all attribute binding into .bind or move all of it into the draw* functions.

**Comment by jfirebaugh** [comment]
The driving considerations should be:

* Bring js and native into closer alignment
* Separate worker objects from GL wrapping objects

**Comment by lucaswoj** [comment]
This is done now
