### ISSUE TITLE
setHTML() in Popup? (Javascript newbie)

### ISSUE THREAD

**Issue by siyucchen** [mapbox/mapbox-gl-js#12484]
Hello, I'm trying to use setHTML in popUp window to do the following: 

The "name" text is a hyperlink to another page

Here is the code to the project without setHTML():
  

    mapboxgl.accessToken = 'pk.eyJ1Ijoic2l5dWNjaGVuIiwiYSI6ImNsYnZoYjViZzJoNXozcHBqbzR1Y2pxZjQifQ.5H9fghwphrlDGMgs2bgnqQ';

    const bounds = [
    [120.993700, 30.669902], // Southwest coordinates
    [122.209481, 31.828037] // Northeast coordinates
    ];  

    const map = new mapboxgl.Map({
    container: 'map', // container ID
    // Choose from Mapbox's core styles, or make your own style with Mapbox Studio
    style: 'mapbox://styles/siyucchen/clbwfvq7t000815rw928y0oak', // style URL
    center: [121.487, 31.2239], // starting position [lng, lat]
    maxZoom: 18,
    minZoom: 14.9,
    maxBounds: bounds
    });

    

    const list = [
      {
        name: 'Intersection between Beikongjia Alley and Jinjiafang Road',
        color: '#cf302d',
        lngLat: [121.480965,31.223564],
      },
      {
        name: 'Interior of No.91, Jinjiafang Road',
        color: '#cf302d',
        lngLat: [121.48199,31.22394]
      }                 
    ]

    list.forEach(({name, color, lngLat}) => {
    const popup = new mapboxgl.Popup({ offset: 25 }).setText(name)

      new mapboxgl.Marker({
        color,
        scale: 0.6
      })  
      
      .setLngLat(lngLat)
      .setPopup(popup)
      .addTo(map);
    })

      map.on('load', () => {
        map.setFog({});
        })

        map.scrollZoom.enable({around: 'center'});

    });

I saw this example on Mapbox (https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/) and tried the following, but doesn't work:

```

const list = [
  {
    name: 'Intersection between Beikongjia Alley and Jinjiafang Road',
    color: '#cf302d',
    description: '`<p><a href="link1.html">CLICK FOR MORE INFO</p>`',
    lngLat: [121.480965,31.223564],
  },
  {
    name: 'Interior of No.91, Jinjiafang Road',
    color: '#cf302d',
    description: '`<p><a href="link2.html">CLICK FOR MORE INFO</p>`',
    lngLat: [121.48199,31.22394]
  }                 
]

list.forEach(({name, color, descriptionlngLat}) => {
const popup = new mapboxgl.Popup({ offset: 25 }).setText(name)

  new mapboxgl.Marker({
    color,
    scale: 0.6
  })  
  
  .setLngLat(lngLat)
  .setHTML(description)
  .setPopup(popup)
  .addTo(map);
})

```

**Comment by avpeery** [comment]
Thanks @siyucchen for using mapbox-gl-js. `setHTML` is a method for the popup, not the marker. You'll want to call `setHTML` here: `const popup = new mapboxgl.Popup({ offset: 25 }).setText(name).setHTML(description)` instead. See documentation [here](https://docs.mapbox.com/mapbox-gl-js/api/markers/#popup#sethtml).

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
