### ISSUE TITLE
Feature Id and properties.id not always static and different

### ISSUE THREAD

**Issue by spimou** [mapbox/mapbox-gl-js#12487]
I click on a point on a map and get all the features from 2 vector layers (application/vnd.mapbox-vector-tile) and one geojson layer `data: 'http://localhost:8080/geoserver/mydata/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=mydata%3Acontexts&outputFormat=application%2Fjson' ,` , all served from GeoServer

In Geoserver's store I have `Expose primary keys` enabled, so in the features properties I have their IDs , coming from the database

I try to remove the duplicates that may created by mapbox based on their properties.id (sometimes mapbox creates duplicates of the same feature in vector and geojson, depending on zoom level)

Then I want to check if I have multiple features in the first vector layer. If I do, I create some objects, including data from other layers. To see what belongs to what feature from the first layer, I do it based on their properties.id , but sometimes its the same for both features, while feature id is different. I thought that properties.id always stays the same and its not duplicated on multiple features.  

**mapbox-gl-js version**: 2.10.0

**browser**: Chrome Version 108.0.5359.125 (Official Build) (64-bit)

### Steps to Trigger Behavior

```
map.current.on('click', (e) => {  
    //get point
    const point = e.point; 
    //get all features from all layers from that point
    let features = map.current.queryRenderedFeatures(point); 

    //separate features by layer
    let excavations = features.filter(f => f.layer.id === 'excavations-layer');
    let parts = features.filter(f => f.layer.id === 'excavation_parts-layer');
    let contexts = features.filter(f => f.layer.id === 'contexts-layer');  
    
    //removing duplicates 
    excavations = excavations.filter((value, index, self) =>
      index === self.findIndex((et) => (
        et.properties.id === value.properties.id
      ))
    )
    parts = parts.filter((value, index, self) =>
      index === self.findIndex((pt) => (
        pt.properties.id === value.properties.id
      ))
    )
    contexts = contexts.filter((value, index, self) =>
      index === self.findIndex((ct) => (
        ct.properties.id === value.properties.id
      ))
    ) 
      //organize data per excavation, based on ids
      excavations.forEach(e => {
        ex_excavations = excavations.filter((value) => 
          e.properties.id == value.properties.id
        )
        ex_parts = parts.filter((value) => 
          e.properties.id = value.properties.excavation_id
        )
        ex_contexts = contexts.filter((value) => 
          turf.booleanIntersects(value,e)
        )
        exgroupArray.push(
          {
            name:e.properties.name,
            excavations:ex_excavations,
            parts:ex_parts,
            contexts:ex_contexts
          }
        )
        console.log('e id  loop ', e.id);    
        console.log('exgroupArray ', exgroupArray);    
        console.log('====================');    
      }); 
```

The original excavations array where I do the first forEach `excavations.forEach(e => {` has different feature ids (12,13) , but the same properties.id (12,12)
Other times has the same feature ids (12,12) , but different properties.id (12,13)
Check image
I though that properties.id comes from the Geoserver and should always be the different for each feature. I try to base my code on that, but because it changes, it messes up my final `exgroupArray` and cannot loop it correctly in the HTML. 

Edit : It seems like if I am fully zoomed out, I get same feature id, different properties.id, check second image

### Link to Demonstration

https://jsbin.com/

### Expected Behavior
properties.id should always be different for each feature and never change
### Actual Behavior
properties.id is not different for each feature and changes

![01](https://user-images.githubusercontent.com/16806546/208936630-7b242e9a-cb55-4ac8-a332-f478b4fa1841.png)
![02](https://user-images.githubusercontent.com/16806546/208940878-f75a9c62-039c-4275-af91-51f289d9b5e8.png)

**Comment by mourner** [comment]
The ids should stay consistent. If they diverge, I guess that either you're using [the `generateId` option](https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson-generateId) for auto-assigning ids in GeoJSON, or the issue is on the server side. It's impossible to say for sure because there's no reproducible live test case, so I don't know how we can help here. Feel free to provide more details and I'll reopen.
