### ISSUE TITLE
Can the text padding parameter be added as a parameter for calculating the text placement position?

### ISSUE THREAD

**Issue by longhaiyan-lhy** [mapbox/mapbox-gl-js#12493]
When you set Label.anchor, the icon and label overlap.
![image](https://user-images.githubusercontent.com/56541965/209639100-b71aa584-c419-469f-82b3-29ab68af7a91.png)
Maybe it can be solved by that add the text padding parameteras a parameter for calculating the text placement position?

**Comment by mourner** [comment]
It's pretty difficult to answer this kind of question just by a single screenshot, without more details that are prompted when you submit an issue — namely, a live test case of the issue in question, steps to reproduce, exactly what you expect and what happens instead. I'll close this one, but feel free to submit an issue with the necessary details.
