### ISSUE TITLE
0.8.0 release

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1250]
There are _lots_ of improvements and bugfixes since 0.7.0, which was in March. Let's roll a release.

**Comment by jfirebaugh** [comment]
:+1: 

It should be 0.8.0 though, since there have been many breaking changes.

**Comment by jingsam** [comment]
I'm waiting 0.8.0 for a long time. I check your repository  everyday, excited about the coming release

**Comment by jfirebaugh** [comment]
The major remaining task is to update documentation. Either update API.md with all the changes and additions to JSDoc that we have made, or finish the switch to documentationjs (#952).

**Comment by jfirebaugh** [comment]
Released!
