### ISSUE TITLE
How to make sprite face camera in three-js custom layer

### ISSUE THREAD

**Issue by sunjunqing2008** [mapbox/mapbox-gl-js#12513]
I don't know that in Mapbox CustomLayer, if Threejs sprite rotates automatically, it will always face the camera。

[ My Code](https://github.com/sunjunqing2008/ThreejsMapbox/blob/main/sprite.html)
![20230116133104](https://user-images.githubusercontent.com/20146948/212605403-26f99a19-b3ee-4bc6-ba37-5698339d3ab3.png)
![20230116133112](https://user-images.githubusercontent.com/20146948/212605409-f3899800-3830-403c-bd28-73f61999e874.png)

**Comment by sunjunqing2008** [comment]
Thank you for your help. If there is only one sprite in the custom layer, it is OK, but I now have multiple sprites in the custom layer

**Comment by sunjunqing2008** [comment]
Thank you for your help. If there is only one sprite in the custom layer, it is OK, but I now have multiple sprites in the custom layer

**Comment by sunjunqing2008** [comment]
Thank you for your help. If there is only one sprite in the custom layer, it is OK, but I now have multiple sprites in the custom layer。

**Comment by stepankuzmin** [comment]
Hi @sunjunqing2008,

Thank you for using mapbox-gl-js. This issue tracker is for reporting bugs and feature requests. For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/).

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.

**Comment by GoodNameofzhang** [comment]
I have the same problem. Have you solved it
