### ISSUE TITLE
Add Pov to the map

### ISSUE THREAD

**Issue by SuhaibMaraqa** [mapbox/mapbox-gl-js#12515]
**mapbox-gl-js version**:

### Question

Hello everybody, I have a requirement to add a pov (I'm not sure about the name) to the map

![povOnMap](https://user-images.githubusercontent.com/88399263/212691752-1e875fe9-48d8-4486-b2ea-5676d7e70645.png)

I want to add the orange pov on the left.
how to add with mapbox please? and where to find the documentation about it

**Comment by stepankuzmin** [comment]
Hi @SuhaibMaraqa,

Thank you for using mapbox-gl-js. Unfortunately, there is no way to do it out of the box. You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help. E.g. integrating Mapillary with Mapbox, see  https://mapillary.github.io/mapillary-js/examples/viewer-to-map for example.
