### ISSUE TITLE
UPGRADING.md

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1251]
It would be great to have upgrade instructions that suggest how to move between versions of mapbox-gl-js.

**Comment by mourner** [comment]
> jfirebaugh [18:38]: @mourner: do you think we need a separate UPGRADING.md? https://github.com/mapbox/mapbox-gl-js/issues/1251
> jfirebaugh [18:38]: I'm kind of inclined to keep this in CHANGELOG and just be more verbose
> mourner [18:38]: @jfirebaugh: with a well-organized changelog and minor API changes, I think no

**Comment by jfirebaugh** [comment]
Let's do it like https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#breaking-changes
