### ISSUE TITLE
Map language doesn't work at all, neither browser autodetect nor setting explicit by code

### ISSUE THREAD

**Issue by danielsippel** [mapbox/mapbox-gl-js#12547]
**mapbox-gl-js version**:

mapbox-gl-js/v2.12.0
mapbox-gl-js/v2.11.0
mapbox-gl-js/v2.10.0
mapbox-gl-js/v2.9.0

**browsers**:

Google Chrome current (109.0.5414.119), macOS 13.2
Firefox current (109.0), macOS 13.2
Safari current (Version 16.3 (18614.4.6.1.5)), macOS 13.2
Google Chrome mobile current on Google Pixel 6a

### Steps to Trigger Behavior

 1. Set your browser's language to "German"
 2. View a map

### Link to Demonstration

https://jsbin.com/lobosov/edit?html,output

### Expected Behavior

Map displays "München"

### Actual Behavior

Map displays "Munich"

### Browser settings

<img width="1093" alt="Bildschirm­foto 2023-01-29 um 20 24 09" src="https://user-images.githubusercontent.com/7558075/215350963-7395a67e-6068-4efd-826c-70504f219209.png">

### Possible Workaround

use mapbox/mapbox-gl-language

### Further information

Setting the 'language' in mapboxgl.Map() constructor does not work as well.
Documented here: https://docs.mapbox.com/mapbox-gl-js/api/map/

No error is thrown with following values, but we still see "Munich":
```
	language: 'German'
	language: 'de'
	language: 'DE'
	language: 'de-DE'
	language: 'Germany'
```
	
https://jsbin.com/hijoqaf/edit?html,output
Every other language does not work as well.

**Comment by danielsippel** [comment]
https://www.youtube.com/watch?v=txqiwrbYGrs

**Comment by stepankuzmin** [comment]
Hey @danielsippel,

Thanks for creating this issue. It seems to work with the [example](https://jsbin.com/hijoqaf/edit?html,output) with the `language` option in the constructor you provided. The work on this feature is still in progress so it might be unstable sometimes. Sorry for the inconvenience.

![Screenshot 2023-02-15 at 13 45 18](https://user-images.githubusercontent.com/533564/219018959-f6d2c426-8e0a-4ca5-8602-36ba9c23087f.png)

**Comment by danielsippel** [comment]
https://jsbin.com/wiruvow/1/edit

@designcoagency @stepankuzmin 

> The work on this feature is still in progress so it might be unstable sometimes. Sorry for the inconvenience.

https://youtu.be/txqiwrbYGrs?t=9

**Comment by designcoagency** [comment]
@danielsippel thank you for your reply! 
So basically, the data is available at OSM, and Mapbox uses the tile data in their streets map, but there is some issue that is preventing their streets map from displaying data from OSM?
