### ISSUE TITLE
Document style object APIs

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#1254]
[map.style.getLayer](https://github.com/mapbox/mapbox-gl-js/blob/e326faf7764a24fbbf28e5021291d29be78b0682/js/style/style.js#L327-L335)
and
[map.style.getReferentLayer](https://github.com/mapbox/mapbox-gl-js/blob/e326faf7764a24fbbf28e5021291d29be78b0682/js/style/style.js#L337-L351)

**Comment by jfirebaugh** [comment]
@lbud Can you update the link above? I think the line numbers are out of date. (Protip: press `y` while on a page like https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style.js#L218-L422 to get a canonical URL whose contents will never change.)

**Comment by lbud** [comment]
@jfirebaugh aha, I was looking for these under a `style` object in the docs — wasn't realizing everything is called from the map object. Updated the only two undocumented (not called from map.js) above. Should the other style.js API methods all be private then? Many don't look that way…

**Comment by jfirebaugh** [comment]
Right, the public API is what's exposed by map. We [may expose `getLayer`](https://github.com/mapbox/mapbox-gl-js/issues/1183) but again it would be via map. The two methods you link have JSDocs (for internal use) and a `@private` tag. Is there something else you're looking for?

**Comment by lbud** [comment]
Ah @jfirebaugh I wasn't even looking for the `@private` tag, was just assuming based on the lack of leading underscore — my bad.
