### ISSUE TITLE
make units and unit conversions clearer

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1256]
there are many different units of measurement:
- pixels
- em
- glyph metrics unit
- layer geometry unit
- collision unit (same as layer geometry unit up until now, but since layers can have different extents this will be different in some cases)

It is often unclear what a variable's unit of measurement is. Values are converted from one unit to another by multiplying with some [magic ratio](https://github.com/mapbox/mapbox-gl-js/blob/2d14cfe4ff1bb43954477345937de38b885eac42/js/data/symbol_bucket.js#L136-L139).

This could all be clearer

**Comment by lucaswoj** [comment]
This is better now that we have standard extent units. We are clear within the style spec about the units of each value. Let's keep striving towards well-documented, readable code.
