### ISSUE TITLE
When does the global support custom layers?

### ISSUE THREAD

**Issue by FreeGIS** [mapbox/mapbox-gl-js#12574]
The laterst mapboxgl version(v.2.12) could not support custome layers，can you tell me which branch is doing this function and about when it can be supported？

**Comment by rememberedbound** [comment]
Hi, we're also interested in support for CustomLayerInterface while using the global view, have you got any kind of timeline on when this might be implemented, or any mitigation strategies if you need to do custom webgl rendering on it?

**Comment by stepankuzmin** [comment]
Hi! This is going to be available in the upcoming v2.13.0 release.
