### ISSUE TITLE
Newly added 3D Object after map completely rendered won't be visible unless map is zoomed

### ISSUE THREAD

**Issue by LumineLittlelight** [mapbox/mapbox-gl-js#12576]
Hi, 

I am trying to follow this tutorial with adaptation of Vue 2 and V-Mapbox wrapper.
https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/ 

We can see the 3D model rendered succesfully upon initial render (i.e when the layer first added to the map and the map loaded).

However, the issue come when we want to dynamically add another 3D model after the map and layers are rendered.

We cannot see the newly added 3D object unless we initiate a zoom movement onto the map. First I clarify, it is not because the zoom level is too far etc. It is just that zoom movement must be initiated for the object to be visible. 

We tried to call renderer.render(scene,camera) followed by map.triggerRepaint() after adding the object to the scene, but newly added 3D object won't be visible nevertheless unless zoom movement is invoked. 

Is there a manual way to trigger the render callback manually? (the one we specified when specifying the customLayer and render callback) I was told triggerRepaint should do it, but it does not seem so.  Or is this because something wrong with Vue or V-Mapbox wrapper themselves?

Could we seek clarifications on what events/functions being triggered upon map zoom?

Thank you.

**Comment by stepankuzmin** [comment]
Hi @LumineLittlelight,

Thank you for opening this ticket. It's hard to say what is wrong with our setup, but that might be related to how the Vue wrapper triggers map repaint. Could you please provide a minimal demonstration of the issue to help the maintainers and community reproduce this issue? We recommend using https://jsbin.com/.

**Comment by LumineLittlelight** [comment]
Hi Stepan. Apologies, we managed to find the root cause. It is not on mapbox fault.

Turns out the mesh object is missing a scaling function when being added. This caused the object is too small and cannot be seen until zoom call is called (that is binded to a scaling function).

Closing the thread.
