### ISSUE TITLE
Unclear how setUrl and setTiles works for raster layers

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#12587]
Its unclear how the just released `setUrl` and `setTiles` works for raster layer, and the [example](https://github.com/mapbox/mapbox-gl-js/blob/main/src/source/raster_tile_source.js#L166) doesn't help either since it just sets the same url again.

Wonder how it would work if I wanted to:

- Initialize the map with **Stamen Watercolor** and change to **Stamen Toner**? (Same domain, different tileset)
- Initialize the map with **Statmen Watercolor** and change to **OSM**? (Different domain)

Stamen Watercolor: `https://stamen-tiles.a.ssl.fastly.net/watercolor/{z}/{x}/{y}.png`
Stamen Toner: `https://stamen-tiles.a.ssl.fastly.net/toner/{z}/{x}/{y}.png`
OSM: `https://a.tile.openstreetmap.org/{z}/{x}/{y}.png`

Here's my fiddle:
https://jsfiddle.net/iaezzy/b1a8jukm/

**Comment by stepankuzmin** [comment]
Hey @3zzy,

Thanks for using Mapbox! Your example is correct. The only thing that needs to be changed is the `setTiles` argument must be an array.

```js
rasterTileSource.setTiles(['https://stamen-tiles.a.ssl.fastly.net/toner/{z}/{x}/{y}.jpg']);
```

Unfortunately, the toner-style tiles are not available at the moment, but it works with OSM tiles:

```js
rasterTileSource.setTiles(['https://a.tile.openstreetmap.org/{z}/{x}/{y}.png']);
```

I'm closing the issue, but feel free to reopen it if you have any questions.
