### ISSUE TITLE
Issue with new Chrome Version 111.0.5563.64 (on Intel Mac, works fine with M1 and M2 Apple Silicon)

### ISSUE THREAD

**Issue by CptHolzschnauz** [mapbox/mapbox-gl-js#12609]
Hello!

After updating to the newest Chrome, our map doesn't initialize with the following error:

vec3.js:484 Uncaught TypeError: Cannot read properties of null (reading '3')
    at el (vec3.js:484:11)
    at bl.fromInvProjectionMatrix (primitives.js:109:20)
    at Ko._calcMatrices (transform.js:1900:46)
    at Ko.resize (transform.js:1092:14)
    at Map.resize (map.js:787:24)
    at new Map (map.js:603:14)
    at map71.html:1100:19
el @ vec3.js:484
fromInvProjectionMatrix @ primitives.js:109
_calcMatrices @ transform.js:1900
resize @ transform.js:1092
resize @ map.js:787
Map @ map.js:603
(anonymous) @ map71.html:1100
vec3.js:484 Uncaught TypeError: Cannot read properties of null (reading '3')
    at el (vec3.js:484:11)
    at bl.fromInvProjectionMatrix (primitives.js:109:20)
    at Ko._calcMatrices (transform.js:1900:46)
    at Ko.clone (transform.js:222:15)
    at new Lt (placement.js:212:36)
    at new jt (pauseable_placement.js:78:26)
    at Qt._updatePlacement (style.js:1743:39)
    at Map._render (map.js:3169:57)
    at map.js:3559:26

map71.html:1100 : 

var map = new mapboxgl.Map({
            container: 'map',
            // Spiderman : mapbox://styles/superflytnt/cknrkcqyi0ur017mstn1vvpjp
            style: 'mapbox://styles/superflytnt/cknrlt7wq0bit17pqp3r6b4e6',
            center: [user_obj.vlng, user_obj.vlat],
            zoom: user_obj.vzoom,
            bearing: user_obj.vbearing,
            pitch: user_obj.vpitch,
            attributionControl: false,
            projection: { name: 'globe' }
        });

The same map works under Safari, Firefox without a problem.

TBH: I have absolutely no idea why.

The error is thrown at vec3.js (Marked bold and italic)

export function transformMat4(out, a, m) {
  var x = a[0],
      y = a[1],
      z = a[2];
  _**var w = m[3] * x + m[7] * y + m[11] * z + m[15];**_
  w = w || 1.0;
  out[0] = (m[0] * x + m[4] * y + m[8] * z + m[12]) / w;
  out[1] = (m[1] * x + m[5] * y + m[9] * z + m[13]) / w;
  out[2] = (m[2] * x + m[6] * y + m[10] * z + m[14]) / w;
  return out;
}

**mapbox-gl-js version**:
2.13.0
**browser**:
Chrome Version 111.0.5563.64 (on Intel Mac)

### Steps to Trigger Behavior

Loading the map

### Link to Demonstration

It's behind a dev enviroment, can't provide a link, sorry

### Expected Behavior

Work like in older Chrome Versions.
The issue is only on Intel Macs.

### Actual Behavior

Crash

**Comment by mourner** [comment]
Is this only reproducible for your specific style in a specific location and with some added application code? Maybe you could try reproducing the same issue with a minimal example so that we could see a live test case, e.g. using JSBin, JSFiddle or CodePen?

**Comment by CptHolzschnauz** [comment]
It's running in a protected dev enviroment and needs postgis et al. and mostly everything on the map is dynamic so no chance for CodePen. I can't open to the net because it's not hardened now. It would be a honour for me to invite you to a facetime screenshare to show the issue if you want and if it help. I have no better idea.

**Comment by mourner** [comment]
@CptHolzschnauz so the issue is only reproducible on your app with specific dynamic logic, not on any static styles, or even official Mapbox examples on the same Intel Mac on Chrome v111, correct?

**Comment by mourner** [comment]
Also, can you try looking into the debugger when the error happens (open DevTools, make sure "pause on uncaught exceptions" is turned on, reload the page), and inspect some of the values from which `cameraToClip` is calculated in `_calcMatrices`? I'm specifically interested in `this.width`, `this.height`, `this._farZ`.

**Comment by CptHolzschnauz** [comment]
<img width="842" alt="Bildschirmfoto 2023-03-08 um 17 51 34" src="https://user-images.githubusercontent.com/68701579/223777149-f5886fa6-1376-4dc6-bd9a-da4cf12ba439.png">

**Comment by CptHolzschnauz** [comment]
<img width="941" alt="Bildschirmfoto 2023-03-08 um 17 56 50" src="https://user-images.githubusercontent.com/68701579/223778443-ee89444d-1759-4c1a-8b77-9236d428b628.png">

**Comment by mourner** [comment]
@CptHolzschnauz so it looks like the root of the issue might be that the transform gets `NaN` as the zoom value. You could maybe trace how `_zoom` gets that value with some debugging?

**Comment by CptHolzschnauz** [comment]
I see, but still strange to me. As i said, works fine in Safari and Firefox, worked also with Chrome before the update, works on M cpu's and also with mapbox 2.9.x on Intel.  I didn't change the code on my side. I will investigate as soon as i find time. Thx for your attention and fantastic work. Chapeau!

**Comment by CptHolzschnauz** [comment]
I found the reason. I had the zoom value stored in a WebStore Object, parsedToInt worked for all values except for that zoom value, i treated the all the same. After deleting the WebStore and rebuild, everything was fine. There is no bug on mapbox js, the chrome update did something with that WebStorage value. I close this issue as not applicable to mapbox.
