### ISSUE TITLE
Div markers 

### ISSUE THREAD

**Issue by olanod** [mapbox/mapbox-gl-js#1260]
Allow the use of html elements as markers similar to what leaflet does but even better.

**Comment by jfirebaugh** [comment]
All our current plans revolve around GL-based markers, rather than HTML-based markers. This is for efficiency, consistency with Mapbox GL styles, and portability with Mapbox GL native. You can read more in [this issue](https://github.com/mapbox/mapbox-gl-js/issues/656).
