### ISSUE TITLE
Momentum scrolling instant on MacOS with reduced motion

### ISSUE THREAD

**Issue by joepio** [mapbox/mapbox-gl-js#12602]
**mapbox-gl-js version**: 2.12.0, 2.13.0

**browser**: Chrome, safari (on MacOS)

### Steps to Trigger Behavior

1. Turn on `reduced motion` on macOS accessibility settings
1. Open a map on MacOS (e.g. https://docs.mapbox.com/mapbox-gl-js/example/simple-map/)
2. Drag over the map with the mouse, let go while making the dragging motion (don't wait with letting go until movement has stopped)
3. You will see the map skips over an area, dependent on your speed (see video below)

### Link to Demonstration

Note how the map instantly teleports to a new location when the cursor changes from 'dragging' to 'normal' from `0:05` onward.

https://user-images.githubusercontent.com/2183313/222193649-95daca06-b4dd-4833-95aa-0fcbc9ff876d.mov

### Expected Behavior

There are two ways dragging and letting go while having momentum should work:

1. Freeze the position when the mouse button is let go. I think this should probably be the default with mouse users.
2. Momentum scrolling, even if reduced motion is on. 

### Actual Behavior

Map 'teleports' to position further then where the moust is let go. I suspect that it instantly teleports to the calculated 'momentum' position (where it should come to a stop), but the animation is 0ms long. But this is just a guess coming from someone who doesn't know the internals of course.

**Comment by joepio** [comment]
Pretty sure this is the culprit: 

https://github.com/mapbox/mapbox-gl-js/blob/b924e91b9464cfba038c61ccfdd04ed653773a61/src/ui/camera.js#L1505

**Comment by stepankuzmin** [comment]
Hi,

Thanks for creating an issue! This was recently fixed in https://github.com/mapbox/mapbox-gl-js/pull/12631
