### ISSUE TITLE
map.fitBounds make a "Cannot read properties of null (reading '3')"

### ISSUE THREAD

**Issue by MrDiablon** [mapbox/mapbox-gl-js#12604]
**mapbox-gl-js version**: 2.13.0

**browser**: Chrome - Safari

### Link to Demonstration

https://jsfiddle.net/Ld21p6w7/1/

### Expected Behavior

zoom on the point of the map

### Actual Behavior

nothing append and mapbox do nothing after that.
It's look like that the point use in the demonstration is too close from each other. After moving it a bite every thing is ok.

**Comment by stepankuzmin** [comment]
Hi @MrDiablon 

You seem to be trying to use [LngLatLike](https://docs.mapbox.com/mapbox-gl-js/api/geography/#lnglatlike) to extend the `LngLatBounds`. The problem is that `LngLatLike` should be in the shape of `{lon: number, lat: number}`, so you'd need to change `lng` to `lon` to make it work.

```js
const points = [
  { lat: 50.614351539999994, lon: -2.49247692 },
  { lat: 50.614341849999995, lon: -2.49248475 },
  { lat: 50.6143484, lon: -2.492463 },
];
```

**Comment by stepankuzmin** [comment]
Apparently, it's a bug on the GL JS side, `LngLatBounds` should support extending with `{lng: number, lat: number}`.

Made a fix for that https://github.com/mapbox/mapbox-gl-js/pull/12605

**Comment by MrDiablon** [comment]
> #12605

Try it today, and get the same bug
