### ISSUE TITLE
removeFeatureState docs inconsistent

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#12612]
![image](https://user-images.githubusercontent.com/678344/224224498-8c6499fd-4f20-4812-921e-df59fcb28e0a.png)

The text says:

> If only a feature.source is specified, it will remove the state for all features from that source.

But the table does not indicate that `feature.id` is optional.

Also, something weird is going on with `key`, which is not in the table.

**Comment by mudityadev** [comment]
Hi @stevage,

I hope you're doing well. I'm new to open source and I'm looking to contribute by fixing a documentation error in the Mapbox GL JS project. I understand that the documentation uses JSDoc comments and is processed with documentationjs in the source code.

Could you please guide me on how to edit the API documentation? I would appreciate any tips, best practices, or resources that can help me get started with this process.

Thank you in advance for your assistance!
Muditya Raghav

**Comment by stevage** [comment]
HI @mudityadev ,
  I don't work for Mapbox and am not the person to ask. Hopefully the contributors documentation will help you: https://github.com/mapbox/mapbox-gl-js/blob/main/CONTRIBUTING.md

Good luck :)

**Comment by mudityadev** [comment]
Thanks for your response, @stevage. I found the help I needed in the documentation and resolved the issue.

Best regards
Muditya Raghav

**Comment by mudityadev** [comment]
**Assistance Needed Regarding PR #12612 and Contributor License Agreement**

Hi @stevage and @stepankuzmin Sir,

I hope this message finds you well. Please accept my apologies for any inconvenience; as a newcomer to open source contributions, I could use your guidance. I have fixed issue #12612 and created a pull request (PR). However, I'm encountering a problem - even after signing the Contributor License Agreement (CLA), it still shows as unsigned.

Could you kindly take a moment to review my PR and verify if it has been submitted correctly? Additionally, please let me know if there are any changes required to make the PR more acceptable for maintainers to merge it.

Thank you for your time and support. I look forward to your response.

Best regards,
Muditya Raghav

**Comment by stepankuzmin** [comment]
Just for clarity, the `key` argument is not part of the `feature` object argument, so that's why it's not listed in the table /cc @stevage
