### ISSUE TITLE
Stop render loop when idle and nothing on screen is changing

### ISSUE THREAD

**Issue by trusktr** [mapbox/mapbox-gl-js#12625]
**mapbox-gl-js version**:

### Question

Is there a way to stop the map from rendering when idle and the visual is not changing. Otherwise it wastes CPU/GPU/Battery.

### Links to related documentation

I wasn't able to find it, maybe I don't know what to look for.

**Comment by trusktr** [comment]
Solution so far: override `map.triggerRepaint` with a no-op function. Restore it later when needed and call it once to get the loop running again.

**Comment by stepankuzmin** [comment]
Hi @trusktr,

Could you please add more context here? The map should not rerender when idle.

**Comment by trusktr** [comment]
Seems that it keeps re-rendering if we've set `map.on('render', () => {}...)`. Maybe the solution is to remove that event handler instead of patching, then add it back when needed.

**Comment by stepankuzmin** [comment]
Maybe you somehow update the map? Unfortunately, I can't reproduce continuous re-renders with `map.on('render', () => {...})`.

**Comment by trusktr** [comment]
Unfortunately I can't share the code at the moment, but what I see are two things in the code looping:

- custom rAF loop that updates some things in a map layer
- map.on('render', callback) to animate more things in a layer

Even when I disable both of these, the map keeps rendering (I see animation frames with `paintStartTimeStamp` coming from mapbox).

I don't see anything else updating the map in this code.

The only thing that works so far is the following (with Svelte `$:` reactive block handling the conditional change):

```js
  const triggerRepaint = map.triggerRepaint;

  $: if (map) {
    if (mapVisible) { // this block re-runs if mapVisible changes
      // Allow the map's render loop to run.
      map.triggerRepaint = triggerRepaint;
      map.triggerRepaint();
    } else {
      // Stop the map's render loop.
      map.triggerRepaint = () => {};
    }
  }
```

It works great! The nice thing about this is I don't need to debug and know where the code might be updating (if at all, because I've combed our code and see no other loops).

Do you know what causes `paintStartTimeStamp()` to be looping?

I tried other things like the following with no luck to remove our code's loops, where `layerCanvas.animate()` is the part that updates a canvas map layer and performs only canvas drawing calls. In the following, even when map.off and cancelAnimationFrame are called, I still see a mapbox `paintStartTimeStamp` loop:

```js
  let frameHandle = 0;

  function animate() {
    layerCanvas.animate();
    frameHandle = requestAnimationFrame(animate);
  }

  function stopAnimation() {
    cancelAnimationFrame(frameHandle);
  }

  $: if (map && readyToAnimate) {
    if (mapVisible) {
      // Start our own loop
      animate();
    } else {
      // Stop our own loop
      stopAnimation();
    }
  }

  $: if (map && readyToRenderMarkers) {
    if (mapVisible) {
      map.on('render', render);
    } else {
      map.off('render', render);
    }
  }
```

This is the only use of rAF to animate the map that we have, and the only other thing that loops is the `render` callback.

In the `paintStartTimeStamp` loop that I see in devtools, I do not see any of our functions in the callstack, only mapbox's.

Any ideas?

**Comment by stepankuzmin** [comment]
@trusktr, could you please try to isolate the issue and create a minimal reproducible example for this?

**Comment by trusktr** [comment]
@stepankuzmin do you have a most minimal example that should not be rendering? Perhaps I can start from there to try to reproduce.

**Comment by FalkF** [comment]
@trusktr did you find whats causing the rerenders without changes on the source?
