### ISSUE TITLE
v2.11 introduces a bug that causes misalignment of object and selection

### ISSUE THREAD

**Issue by dealeros** [mapbox/mapbox-gl-js#12632]
**mapbox-gl-js version**: v2.11

**browser**: Chrome

### Steps to Trigger Behavior

Mouse hover on sphere

### Link to Demonstration

v2.11 -> https://jsbin.com/ruxenuyazi/edit?html,output (incorrect behaviour)
v2.10 -> https://jsbin.com/moxayupeze/1/edit?html,output  (correct behaviour)

### Expected Behavior

When mouse hover on sphere it should be selected

### Actual Behavior

Area of selection doesn't match object.

**Comment by stepankuzmin** [comment]
Hi @dealeros,

What browser do you use? I couldn't reproduce it with the lastest versions of Chrome, Safari, and Firefox on macOS.

**v2.11**

![Screenshot 2023-03-29 at 14 43 46](https://user-images.githubusercontent.com/533564/228526080-aeca674b-76fa-437b-a239-2508a6549cb6.png)


**v2.10**

![Screenshot 2023-03-29 at 14 43 59](https://user-images.githubusercontent.com/533564/228526025-a087f01d-5649-4c7e-9013-d2041edde8cf.png)

**Comment by stepankuzmin** [comment]
Yes, I can see now that hovering on the right-hand side is not highlighting the feature.
