### ISSUE TITLE
Get all features within a bounding box

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#1264]
Similar to https://github.com/mapbox/mapbox-gl-js/issues/1242 For draw tools where a region is selected it would be ideal to have something like `map.featuresAtBounds(Bounds, Callback);` that selects all features within a bounding box.

![screen shot 2015-06-10 at 3 42 49 pm](https://cloud.githubusercontent.com/assets/61150/8092531/63fa0230-0f88-11e5-86ef-d8102b21fb1c.png)

**Comment by jfirebaugh** [comment]
Added with `featuresIn` in #1302.

**Comment by Cristy94** [comment]
Any example on how to replace the default shift+drag **zoom** with **selection** of all markers inside that area (when using the map, not in edit mode)

**Comment by jfirebaugh** [comment]
@Cristy94 Great idea. I filed a new issue for this: https://github.com/mapbox/mapbox-gl-js/issues/1494
