### ISSUE TITLE
How to convert .obj model vertex data into globe coordinates

### ISSUE THREAD

**Issue by kt7456** [mapbox/mapbox-gl-js#12640]
![1680580349483(1)](https://user-images.githubusercontent.com/35618730/229683016-7dabaa0e-ef06-41e8-9faa-c5737a26212a.jpg)
For example, x:239.0564422607422, y:-1.213919997215271, z:2.0829598903656006, in the picture , I want to convert xyz to globe coordinates，Thanks！

**Comment by mourner** [comment]
You can see an example of transforming model coordinates for rendering in GL JS in this example: https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/ — we don't provide any other utilities for this in GL JS.
