### ISSUE TITLE
How remove all routes from a map with mapbox?

### ISSUE THREAD

**Issue by lucasthaynan** [mapbox/mapbox-gl-js#12646]
### Version
**v2.13.0**

### Question
I have code with a structure similar to this one that I put in Codepen and I want to create a function to remove all the routes drawn on the map. But I can't remove the route in blue, which is the last one tested by mapbox.

### Link to Demonstration: 
https://codepen.io/lucasthaynan/pen/ZEqGYqM

Script done but unable to remove the route in blue:
```
function removeRoutes(map) {

  if (map.getSource("theRoute")) {
    map.removeLayer("theRoute");
    map.removeSource("theRoute");
  }
  if (map.getSource("theBox")) {
    map.removeLayer("theBox");
    map.removeSource("theBox");
  }
  if (map.getSource("clearances")) {
    map.removeLayer("clearances");
    map.removeSource("clearances");
  }
  if (map.getSource("route")) {
    map.removeLayer("route");
    map.removeSource("route");
  }
  if (map.getSource("load")) {
    map.removeLayer("load");
    map.removeSource("load");
  }

}
```

**Comment by mourner** [comment]
The Directions plugin API provides a method to remove the routes: https://github.com/mapbox/mapbox-gl-directions/blob/master/API.md#removeroutes — let me know if there's any problem with it.
