### ISSUE TITLE
add WMS Source, how to set individual BoundingBox?

### ISSUE THREAD

**Issue by pcace** [mapbox/mapbox-gl-js#12657]
Hi there, 

according to the documentation i would add a wms source like this: 

```
"wms-imagery": {
    "type": "raster",
    "tiles": [
        "http://a.example.com/wms?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&width=256&height=256&layers=example"
    ],
    "tileSize": 256
}

```

furthermore it sais: 

`The server URL should contain a "{bbox-epsg-3857}" replacement token to supply the bbox parameter.`

[https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#tiled-sources](https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#tiled-sources)

what do i do if there is not such replacement token configured in the wms server? 
what would i set the bbox to? 

Thanks a lot for any help!!

**Comment by mourner** [comment]
GL JS requests chunks of WMS data as individual tiles, dynamically setting the bounding box of every tile it requests. You can see an example of how it works on https://docs.mapbox.com/mapbox-gl-js/example/wms/ — if you look at network requests, GL JS forms the right urls itself. E.g. one of the requests has this as a bbox: `bbox=-8296780.798186172,5009377.085697312,-8218509.281222152,5087648.60266133`. If you set `srs=EPSG:3857` in the parameters, the WMS server should accept the right bbox values per its spec.

**Comment by pcace** [comment]
Hi, thank you so much for your explanation. The issue i have is that the WMS server i am using does not support EPSG3857. 
I could go for raster image source, but that would mean, that the full image is loaded every time. Is there any other way?

Cheers
