### ISSUE TITLE
2.14.0 introduced a bug that renders a blank map

### ISSUE THREAD

**Issue by MarkLyck** [mapbox/mapbox-gl-js#12659]
**mapbox-gl-js version**: 2.14.0

**browser**: any

### Steps to Trigger Behavior

 1. Upgrade from 2.13.0 to 2.14.0

### Expected Behavior

Map should work

### Actual Behavior

Renders a blank canvas with no map.

**Comment by mourner** [comment]
There's not much detail in your report, but it's likely a duplicate of #12656.
