### ISSUE TITLE
Vue3+Vite does not work. Error occurred while parsing the WebWorker bundle.

### ISSUE THREAD

**Issue by vladimir-chernykh** [mapbox/mapbox-gl-js#12656]
**mapbox-gl-js version**: 2.14.0

### Question

Hi, everyone!

I'm trying to set up and use `mapbox-gl-js` with **Vue3**.

Here is the most minimalistic reproducible example: https://github.com/vladimir-chernykh/vue3-vite-mapbox-gl-js. It contains just one div in html and only mapbox import in js.

No matter what, I get two following **errors** during the **dev-time** (not after build as it has been reported in other issues):

```
b87aeebe-9bb0-48ba-8c20-eafa29a1724c:1 An error occurred while parsing the WebWorker bundle.
This is most likely due to improper transpilation by Babel;
please see https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling
```
and
```
Uncaught ReferenceError: __publicField is not defined
```

I've read through multiple issues (https://github.com/mapbox/mapbox-gl-js/issues/10173, https://github.com/mapbox/mapbox-gl-js/issues/10565) and official [docs](https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling), but none of the solutions helped.

I'm using the default Vue3 scaffolding CLI, which now creates a project with **Vite** instead of WebPack. I do not use babel directly or any other tool (see minimalistic [example](https://github.com/vladimir-chernykh/vue3-vite-mapbox-gl-js)).

I suspect that the problem might be a little bit different, because it does not work even in development.

I'm highly interested if somebody's met this problem before and would appreciate if some of you can help!

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling

**Comment by JamesChevalier** [comment]
I'm seeing the same thing in a Rails 7 app with esbuild. Similarly not using babel, either.
I had to change the `--target` option from `--target=es2019` to `--target=es2022` or `--target=esnext` for it to work.

The end result of my `package.json` is:

```json
"scripts": {
  "build:css": "tailwindcss -c ./config/tailwind.config.js -i ./app/assets/stylesheets/application.tailwind.css -o ./app/assets/builds/application.css --minify",
  "build": "esbuild app/javascript/*.* --bundle --minify --sourcemap --target=es2022 --outdir=app/assets/builds",
  "dev:build": "esbuild app/javascript/*.* --bundle --sourcemap --target=es2022 --outdir=app/assets/builds"
}
```

I'm not necessarily sharing this to suggest that what I've done is good/correct 😄 more so to offer _some_ path forward.

**Comment by fbellomi** [comment]
Having the same issue with vitejs/esbuild, currently using target es2020.

The issue appeared moving from 2.13.0 to 2.14.0

**Comment by inomn** [comment]
Same, but for Vite + React + TS

```
"vite": "^4.2.1",
"mapbox-gl": "^2.14.0",
```

**Comment by fbellomi** [comment]
> Not sure why it did before though.

Same here, my understanding is that is a regression introduced with 2.14.0, which was released yesterday

**Comment by agracia-foticos** [comment]
Same issue

**Comment by mourner** [comment]
Investigating, thanks for the comments everyone!

**Comment by mourner** [comment]
Found the most likely culprit — an accidental introduction of a static field here https://github.com/mapbox/mapbox-gl-js/blob/main/src/style/style_layer/line_style_layer.js#L25 (added in #12588), which breaks our worker bundling setup in some cases when transpiled. Working on a patch now, and adding a test to make sure similar errors don't slip through in the future.

**Comment by mourner** [comment]
Fix coming in #12658.

**Comment by mourner** [comment]
Hey everyone, can you please try upgrading to v2.14.1 and see if it resolves the bundling issue?

**Comment by vladimir-chernykh** [comment]
> Hey everyone, can you please try upgrading to v2.14.1 and see if it resolves the bundling issue?

Works for me as well. Thanks a lot for such a quick fix!

**Comment by inomn** [comment]
> Hey everyone, can you please try upgrading to v2.14.1 and see if it resolves the bundling issue?

Hi @mourner , thanks a lot! It works now

**Comment by rafacribas** [comment]
Using Vue 2, I changed vue-cli for vite and the only thing that stopped working was the mapbox-gl-js map render.
Using mapbox-gl-js 2.15 and vite 4.0

**Comment by snakysnake** [comment]
Still got the issue on 2.15.0 just trying out if it works on 2.13
