### ISSUE TITLE
The documentation subsection for `RasterTileSource` is missing in `Sources`

### ISSUE THREAD

**Issue by paulovieira** [mapbox/mapbox-gl-js#12652]
### Steps to Trigger Behavior

 1. Go to https://docs.mapbox.com/mapbox-gl-js/api/sources/
 2. We see subsections for `CanvasSource`, `VectorTileSource`, etc. But not for `RasterTileSource`. In particular, the new methods introduced in #12352 (released in v2.13) are missing: `setTiles`, `setUrl`.

The changes in #12352 actually have the jsdoc comments. It looks like something is missing when building the website.

**Comment by mourner** [comment]
Good catch! We might have removed it accidentally. Will investigate.
