### ISSUE TITLE
Marker Layers, Cluster

### ISSUE THREAD

**Issue by PeterPilley** [mapbox/mapbox-gl-js#12660]
**mapbox-gl-js version**: latest

### Question
Hi I searched the issues list and the docs but it wasnt clear so I thought I would ask here, if there is another place I am supposed to ask these questions please let me know.

I am coming from using leaflet, in leaflet creating a layer and then adding data to it was straight forward but I cant see how to achieve the same thing with mapbox. 

I can see you can create a source and then add the source to the map, still not too sure how you can toggle it like you would in leaflet but that is the next hurdle.

what is not clear is if I create a source can I then add markers to it or is there no way to control a group of markers like leaflet

**Comment by stepankuzmin** [comment]
Hi @PeterPilley,

Thank you for using mapbox-gl-js. For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You can begin with:
* [Getting started guides](https://docs.mapbox.com/help/getting-started/) provide introductory context to help you understand and begin using Mapbox tools.
* [Tutorials](https://docs.mapbox.com/help/tutorials/) include step-by-step instructions for completing specific projects with Mapbox. Tutorials show common development workflows and can help you learn how to use multiple Mapbox tools together.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
