### ISSUE TITLE
Can you give us an example about displaying potree on mapboxgl like three.js

### ISSUE THREAD

**Issue by zzkzzk1984** [mapbox/mapbox-gl-js#12678]

**Comment by stepankuzmin** [comment]
Hi @zzkzzk1984,

Thank you for using mapbox-gl-js. For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
