### ISSUE TITLE
How do I raise the center point of the map rotation

### ISSUE THREAD

**Issue by myGITHUBdata** [mapbox/mapbox-gl-js#12672]
I added a marker with a height on the map, but it is not possible to rotate the map around this point with the mouse. May I ask if there is any way to change the center point of the map to be in the air? When rotating with the mouse, you can rotate around the marker in the air. I hope to receive your help. thank you

**Comment by stepankuzmin** [comment]
Hi @myGITHUBdata,

Thank you for using mapbox-gl-js. 

It's a bit unclear to me what you are trying to achieve. Could you please add more info on your use case? You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.

**Comment by myGITHUBdata** [comment]
[https://docs.mapbox.com/mapbox-gl-js/example/animate-camera-around-point/ ](https://docs.mapbox.com/mapbox-gl-js/example/animate-camera-around-point/ ) In this example, whether the map can be rotated around the top of the building

**Comment by stepankuzmin** [comment]
What do you mean by changing the map's center point to be in the air?

**Comment by stepankuzmin** [comment]
Hi @myGITHUBdata,

I see, thanks! In that case, you'd need to use the [FreeCamera](https://docs.mapbox.com/mapbox-gl-js/api/properties/#freecameraoptions) API to create an animation focused on a point. You can refer to [Animate the camera around a point with 3D terrain](https://docs.mapbox.com/mapbox-gl-js/example/free-camera-point/) as an example.

**Comment by Kirow** [comment]
@stepankuzmin I have same issue and can not find correct API to achieve desired result. I have object at some coordinates + altitude and I need to rotate camera around this point in the air. For now I can see only possibility to rotate around the point on the ground.
I believe we need Camera API like `lookAtPoint:altitude:`.

P.S. Good to have it on mobile as well

**Comment by AlasdairMott** [comment]
I found this works
```js
map.transform._centerAltitudeValidForExaggeration = 0;
map.transform._centerAltitude = altitude; // desired altitude to orbit around
```
