### ISSUE TITLE
Safari broken after recent shader changes

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#1268]
#1257 broke Safari on both desktop and iOS. It starts to look bad at https://github.com/mapbox/mapbox-gl-js/commit/ba36586530ee252651d3564534fbdc39695762af and goes completely broken on 88f138a59ed956bcc53ada9371944f9085ac4faf.

![image](https://cloud.githubusercontent.com/assets/25395/8120426/fabf006e-106c-11e5-9fd2-492623ccdade.png)

We'll probably have to either find a fix quickly, or revert the changes until we find a solution.

cc @lucaswoj @ansis

**Comment by lucaswoj** [comment]
Huh. Weird. I was testing on Safari and everything seemed ok. I'm OOO for the night so please revert if you're blocked. Will take a look first thing tomorrow.

**Comment by mourner** [comment]
@lucaswoj no worries, let's look tomorrow.

**Comment by lucaswoj** [comment]
Just double checked and I'm seeing beautiful Mapbox Streets in Safri on `f5a34c61ef2e5423b77ca7ef5e4dc52a28ff7d39`

![screen shot 2015-06-11 at 9 39 38 pm](https://cloud.githubusercontent.com/assets/281306/8122042/63dc67de-1082-11e5-97e0-0c9d45dcf63f.png)

I'll play around with other browsers and other platforms tonight.

Are you seeing any console output @mourner?

**Comment by lucaswoj** [comment]
That being said, I have acknowledged that some intermediate commits in this PR were silently broken (i.e. not causing test failures but had faults). I would expect errors on anything in this PR before `1c34f178776a0dc1c78a2e613c4a8f0ae6896124`

**Comment by mourner** [comment]
@lucaswoj hmm, what's your Safari & OS X version? Also, could you try it on iPhone/iPad?

**Comment by lucaswoj** [comment]
![screen shot 2015-06-11 at 10 05 44 pm](https://cloud.githubusercontent.com/assets/281306/8122313/1318bf74-1086-11e5-8687-16cdd060f9a8.png)
![screen shot 2015-06-11 at 10 05 50 pm](https://cloud.githubusercontent.com/assets/281306/8122312/1318b83a-1086-11e5-8551-de087c3f3d6b.png)

Same question to you!

**Comment by mourner** [comment]
The same! Just realized the difference — my discrete videocard is dying so I test GL on integrated card.

**Comment by lucaswoj** [comment]
This is going to be so much fun! :coffee: :coffee: :coffee:

**Comment by lucaswoj** [comment]
Lets talk tomorrow morning @mourner

**Comment by mourner** [comment]
WTF, `rm -rf node_modules` + `npm install` fixed this.
