### ISSUE TITLE
Does Mapbox GL JS not support caching for vector tiles?

### ISSUE THREAD

**Issue by BangDori** [mapbox/mapbox-gl-js#12693]
**mapbox-gl-js version**: 2.13.0

**browser**: Chrome

### Question

It seems that caching is not supported when calling the map component using the mapbox-gl JS library in React, even after saving the GeoJSON file to a Tileset and styling it in Mapbox Studio. It's unclear why this is happening. Could this be an issue caused by webpack?

### code

```
import React, { useEffect, useRef } from 'react';
import mapboxgl from 'mapbox-gl'; // eslint-disable-line import/no-webpack-loader-syntax
import { useSelector } from 'react-redux';
import '@styles/components/Map.scss';
import 'mapbox-gl/dist/mapbox-gl.css';
import useGetImages from '@hooks/useGetImages';
import { MAP_API_TOKEN, MAP_API_STYLE } from '@config/service';
import useMapEvents from '@hooks/useMapEvents';
import CustomMarker from './map/CustomMarker';

const Map = () => {
  const mapContainer = useRef();
  const map = useRef(null);
  const { accessToken } = useSelector((state) => state.accessToken);

  // get image for custom marker
  const imageData = useGetImages(!!accessToken);

  // map event initialize
  const { onMapLoad, onMapUnload } = useMapEvents({ map });
  const bounds = [
    // Southwest coordinates
    [130.8, 36.1395],
    [131.6, 36.8395], // Northeast coordinates
  ];
  // map initialize
  useEffect(() => {
    if (!map.current) {
      map.current = new mapboxgl.Map({
        container: mapContainer.current,
        accessToken: MAP_API_TOKEN,
        style: MAP_API_STYLE,
        center: [131.1, 36.4395],
        zoom: 5.5,
        minZoom: 5.5,
        maxZoom: 10,
        antialias: false,
        doubleClickZoom: false,
        dragRotate: false,
        interactive: !!accessToken, // accessToken ? Interactive : NULL
        maxBounds: [
          [112.704171, 32.745446],
          [145.046554, 41.038954],
        ],
      });
    }
  }, [accessToken]);

  // event loading
  useEffect(() => {
    if (map.current) {
      if (accessToken) map.current.on('load', onMapLoad);
      else map.current.on('load', onMapUnload);

      return () => {
        if (accessToken) map.current.off('load', onMapLoad);
        else map.current.off('load', onMapUnload);
      };
    }

    return null;
  }, [map, accessToken, onMapLoad, onMapUnload]);

  return (
    <div className='map-container'>
      <div className='ocean-container' />
      <div ref={mapContainer} className='map-container'>
        {imageData.map((data, index) => (
          <CustomMarker
            key={index}
            map={map.current}
            src={data.src}
            metadata={data.metadata}
            accessToken={accessToken}
          />
        ))}
      </div>
    </div>
  );
};

export default Map;
```

### Links to related documentation
- https://docs.mapbox.com/help/troubleshooting/mapbox-gl-js-performance/
- https://docs.mapbox.com/help/troubleshooting/api-caching/

**Comment by mourner** [comment]
What exactly are you seeing that makes you believe caching is not working? Can you provide a live test case, e.g. on Codepen/JSFiddle/etc.?

Mapbox vector tiles are cached, but not in the usual browser way, but rather by manually using the browser [Cache API](https://developer.mozilla.org/en-US/docs/Web/API/Cache), so you might not see it reflected in the DevTools Network tab.

**Comment by BangDori** [comment]
Hi @mourner!

Thank you for comment.

I have tried removing unused features and merging layers to increase the loading speed of vector tiles, but the speed improvement was not as expected. I wonder if this is because caching is not working properly or if the loading speed of vector tiles itself is slow.

**Comment by mourner** [comment]
@BangDori there's absolutely no way for us to help you unless you provide us with more concrete details, including a reproducible test case (a live page) that demonstrates the slow loading tiles.

**Comment by BangDori** [comment]
@mourner 

here is test case. try accessing the following website.

http://www.rootrip.site:8080/

**Comment by mourner** [comment]
@BangDori looking at the Network tab when loading the website, Mapbox GL JS and all its resources load very quickly and vector tiles are cached, but some subsequent image loads you do are extremely slow. So the issue is not on Mapbox side.

<img width="1404" alt="image" src="https://user-images.githubusercontent.com/25395/236130190-2014692a-7403-47d8-8114-b7d695773e6f.png">

**Comment by BangDori** [comment]
@mourner 

Thanks to that, I accurately identified the cause of the slow loading speed. Thank you.
