### ISSUE TITLE
round linejoins for dashed lines

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#127]
Both the new and old approaches to round linejoins don't work with dashed lines. The circle joins fill in the spaces.

The solution I'm seeing is to draw disconnected segments (currently `linejoin: butt`) and use the depth buffer to prevent it from overwriting the spaces.

**Comment by jfirebaugh** [comment]
@ansis Still relevant?

**Comment by ansis** [comment]
implemented in https://github.com/mapbox/mapbox-gl-js/pull/938
