### ISSUE TITLE
raster layer with opacity < 1 flickers to full opacity

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#1270]
With opacity for a raster layer set at 0.4, after changing zoom, I sometimes see tiles with full opacity.  Usually just moving the mouse causes the opacity to snap into place.

Also showed this to @samanpwbb

**Comment by samanpwbb** [comment]
Seeing a lot of this:

![screen shot 2015-06-12 at 6 23 37 pm](https://cloud.githubusercontent.com/assets/108094/8141167/5643e89a-1131-11e5-870e-530670057070.png)
![screen shot 2015-06-12 at 6 23 26 pm](https://cloud.githubusercontent.com/assets/108094/8141166/56416764-1131-11e5-8954-50a9a6563767.png)

**Comment by anandthakker** [comment]
BTW, I also saw #675 -- that issue's pretty old, but maybe it's related 

cc @mourner

**Comment by lucaswoj** [comment]
I'm guessing that we're doing a bad job of fading between two raster tiles at intermediate zoom levels. If `raster-opacity` is 0.4, there are two tiles of opacity 0.4 on top of each other instead of one tile of opacity 0.4.

**Comment by tmcw** [comment]
Also seeing this: any opacity value but 0 makes tiles opaque

**Comment by bhousel** [comment]
#1610 maybe fixes the thing @tmcw mentioned above, but probably not the main flickering issue.
