### ISSUE TITLE
map.getCanvas().toDataURL(), I can't get the right picture when I click the button

### ISSUE THREAD

**Issue by 13554599576** [mapbox/mapbox-gl-js#12700]
**mapbox-gl-js version**:1.13.2

### Question
map.getCanvas().toDataURL() it works fine in onload, but I can't get the right picture when I click the button

**Comment by kobeli** [comment]
Hi @13554599576

I have the same problem as you.
You need set as this:
![image](https://github.com/mapbox/mapbox-gl-js/assets/3961585/75eda36a-cd0d-4d4b-b6b4-5145e0dbd5cd)

#1230

**Comment by 13554599576** [comment]
I've already dealt with it, but I really appreciate your answer.




RN
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mapbox/mapbox-gl-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月29日(星期一) 下午4:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mapbox/mapbox-gl-js] map.getCanvas().toDataURL(), I can't get the right picture when I click the button (Issue #12700)





 
Hi @13554599576
 
I have the same problem as you.
 You need set as this:
 
 
#1230
