### ISSUE TITLE
WebGL Context Lost issue in Deck.gl Scatter Plot Charts with Mapbox API

### ISSUE THREAD

**Issue by santosh-sahoo334** [mapbox/mapbox-gl-js#12722]
Hi, 
We are using Apache Superset for data visualization. I have a dashboard with 10 Tabs and 40 Charts. Each Tab with 4 charts - all are of deck.gl scatter plot type. When the dashboard loads for the first time, all charts rendered correctly, but after sometime ( like 5 mins ), when I switch between the tabs, I see the chart disappears with a small image icon at the to left as shown below :-
When I refresh the page again, charts appears to be normal.

![superset-issue](https://github.com/mapbox/mapbox-gl-js/assets/116371351/0a646131-7b4c-4364-ae61-faa49993a3ea)

Behind the scene, we are using MapBox API (Free version - default Access Token) to render the visualization for deck.gl scatter plot charts. On further debugging, found that the browser (at least Chrome) allows no more than 6 web GL contexts (and one might need to configure it to allow > 4). Is this is the correct Assumption ? 
Also, we observe that its the context lost to MapBox API. Has anyone faced similar issue in their application ? What could be the reason for this and possible workaround ? Thanks!

**Comment by stepankuzmin** [comment]
Hi @santosh-sahoo334,

Thank you for using mapbox-gl-js. The limit on the number of WebGL contexts can vary across different browsers and depends on factors such as hardware capabilities, memory constraints, and browser implementations. Browsers usually limit WebGL to 8 to 16 contexts max.

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
