### ISSUE TITLE
403 forbidden for tokens with url restrictions

### ISSUE THREAD

**Issue by konstantin-tcherkashin** [mapbox/mapbox-gl-js#12724]
[Error] Error: Forbidden (403): https://api.mapbox.com/v4/mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,mapbox.mapbox-bathymetry-v2.json?secure&access_token=123

Tried recreating tokens a few times, copying restricted URLs in all possible formats  -- no luck

**Comment by tedsecretsource** [comment]
Like others, I landed here because there is no clear "support" link on any of the mapbox pages. How does one contact support?
