### ISSUE TITLE
Landcover data missing: French Contentin

### ISSUE THREAD

**Issue by Poseclop** [mapbox/mapbox-gl-js#12730]
Seems there is some croping going on with landcover data in this area at zoom 9+. I'm using Cali map style but from my tests it can be replicated with any style using lancover layers.

![image](https://github.com/mapbox/mapbox-gl-js/assets/37383113/b48e9267-7d5f-4d80-9589-0d79802bfa71)

**Comment by stepankuzmin** [comment]
Thanks for opening this issue. I've forwarded it to the data team, so closing it here. Feel free to reopen if you have any questions.
