### ISSUE TITLE
map panning will break webpage scrolling on android

### ISSUE THREAD

**Issue by flamed0011** [mapbox/mapbox-gl-js#1273]
I'm using the latest mapbox-gl-js code on Android 5.1.1 with firefox and phonegap. The map is embedded in a webpage, which can be scrolled. The scrolling of the webpage works as long as I do a map panning. As soon as the map receives the panning event it is only possible to do map panning and the web page scrolling is not possible anymore...

**Comment by KP** [comment]
We encountered this too. @Rich-Harris proposes a fix here https://github.com/mapbox/mapbox-gl-js/pull/1292

**Comment by jfirebaugh** [comment]
Fixed by #1292.
