### ISSUE TITLE
Missing types for styleimagemissing event

### ISSUE THREAD

**Issue by macalinao** [mapbox/mapbox-gl-js#12746]
## Motivation

The Typescript types for the styleimagemissing event are not present.

**Comment by stepankuzmin** [comment]
Hi @macalinao,

`@types/mapbox-gl` is managed by DefinitelyTyped, which is a third party. If you have time, please consider opening a PR there with these changes!

https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mapbox-gl
