### ISSUE TITLE
Cannot read undefined (reading 'mark') - Using Astro

### ISSUE THREAD

**Issue by croganm** [mapbox/mapbox-gl-js#12749]
**mapbox-gl-js version**:
2.15.0

**browser**:
Chrome

### Steps to Trigger Behavior

Just run the dev server.

### Link to Demonstration

[https://stackblitz.com/edit/withastro-astro-spedxh?file=src%2Fcomponents%2Fmapbox.js
](https://stackblitz.com/edit/withastro-astro-spedxh?file=src%2Fcomponents%2Fmapbox.js
)
### Expected Behavior
Load Map

### Actual Behavior
Throw the following error:
`TypeError: Cannot read properties of undefined (reading 'mark')`

Following the stack trace, it takes me to mapbox-gl.js from the dist folder, to the following line:
```js
$t={mark(t){e.performance.mark(t);},measure(t,r,n){e.performance.measure(t,r,n);}};
```

After searching on the github repo for Mapbox GL JS, I see the following code that matches most closely to that line (located in `src/util/live_performance.js`:

```js
export const LivePerformanceUtils = {
    mark(marker: $Keys<typeof PerformanceMarkers>) {
        window.performance.mark(marker);
    },
    measure(name: string, begin?: string, end?: string) {
        window.performance.measure(name, begin, end);
    }
};
```
Wondering why using astro would throw this error as I don't believe mapbox gl js has an issue with Vite (which is what astro uses under the hood).

Any help would be very much appreciated! Please let me know if you need anything else :)

**Comment by willrax** [comment]
:wave: If anyone stumbles upon this when searching for answers (like me 😅) here's how to tackle it:

```js
---
import Layout from "../layouts/Layout.astro";
---

<Layout title="Flight">
  <main>
    <div id="map" style="width: 400px; height: 300px;"></div>
  </main>
</Layout>

<script>
  import mapbox from "mapbox-gl";

  mapbox.accessToken = "YOUR_TOKEN";

  new mapbox.Map({
    container: "map",
    style: "mapbox://styles/mapbox/streets-v11",
    center: [-74.5, 40],
    zoom: 9,
  });
</script>

```

Note the use of import within the script tag.
