### ISSUE TITLE
Map is appearing twice

### ISSUE THREAD

**Issue by SalishKumar** [mapbox/mapbox-gl-js#12745]
Map is appearing twice when fully zoomed out (on map-gl studio too)
<img width="1440" alt="Screenshot 2023-06-08 at 9 52 58 AM" src="https://github.com/visgl/react-map-gl/assets/54025715/dfe80651-506f-4cc6-808a-1d8c2623f12e">

**mapbox-gl-js version**:2.7.11

**browser**:chrome

### Steps to Trigger Behavior

its is reproducible with basic implementation

**Comment by mourner** [comment]
That's by design to ensure continuity around antimeridian, since the world wraps around. If you want a more realistic view on low zoom levels, try the globe view by setting `projection: 'globe'` in map options.
