### ISSUE TITLE
Wrap GeoJSON Source

### ISSUE THREAD

**Issue by StepanKuzmin** [mapbox/mapbox-gl-js#1275]
GeoJSON data doesn't displays after antimeredian. I've used [this](https://gist.github.com/anonymous/d7e443308c5ade1f72ac) for example.

![screen shot 2015-06-15 at 17 29 35](https://cloud.githubusercontent.com/assets/533564/8160041/c393de90-1385-11e5-8968-ac28e249e20a.png)

Same GeoJSON using geojson.io — http://geojson.io/#id=gist:anonymous/d7e443308c5ade1f72ac
![screen shot 2015-06-15 at 17 29 29](https://cloud.githubusercontent.com/assets/533564/8160065/fea3bf96-1385-11e5-9258-dacb2444089f.png)

**Comment by mourner** [comment]
Yeah, upstream at https://github.com/mapbox/geojson-vt/issues/1 — going to look at this soon.

**Comment by mourner** [comment]
Implemented in geojson-vt. Now testing in gl-js...

**Comment by mourner** [comment]
![image](https://cloud.githubusercontent.com/assets/25395/8170304/dca65ec4-137d-11e5-9715-970cff73c335.png)

It works now!

**Comment by StepanKuzmin** [comment]
Yay! Thanks @mourner!
