### ISSUE TITLE
Where is defined mapboxgl?

### ISSUE THREAD

**Issue by sirion1987** [mapbox/mapbox-gl-js#12769]
Hello everyone, for a personal need, I would like to know where the object `mapboxgl` is defined. What is the mechanism that allows the browser to find the `mapboxgl`? Thank you very much.

**Comment by stepankuzmin** [comment]
Hi @sirion1987,

Thank you for using mapbox-gl-js. Before getting started coding up your Mapbox GL JS map, you'll need to include the relevant JavaScript and CSS files in your webpage. Mapbox provides hosted versions of each that you can include in the <head> of your HTML file:

```html
<link href="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v2.15.0/mapbox-gl.js"></script>
```

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
