### ISSUE TITLE
Two attributes are not found in the A document

### ISSUE THREAD

**Issue by myGITHUBdata** [mapbox/mapbox-gl-js#12765]
![screenshot-20230619-104117](https://github.com/mapbox/mapbox-gl-js/assets/43627968/234e9f5b-e924-4238-814a-cf13cb61e06f)

respectPrefersReducedMotion an isPointOnSurface Two attributes are not found in the https://docs.mapbox.com/mapbox-gl-js/api/map/ document

**Comment by stepankuzmin** [comment]
Hi @myGITHUBdata,

Thanks! It should be fixed now 👍
