### ISSUE TITLE
Screenshot and term of use

### ISSUE THREAD

**Issue by billzt** [mapbox/mapbox-gl-js#12764]
Hello everyone, I have created a website using mapboxJS to display maps, and now I need to capture a screenshot of the interface including the map to be placed in a SCI paper that I am writing for publication. Is this legally allowed?

If there exists legal issues, what should I do before post my screenshots in my publication?

Thank you.

**Comment by stepankuzmin** [comment]
Hi @billzt,

Could you please elaborate more on your use case?

You can refer to the **Print or Video Use** in [Mapbox Product Terms](https://www.mapbox.com/legal/product-terms). You can also [contact support](https://www.mapbox.com/contact/). Please note that this issue tracker is for reporting bugs and feature requests.
