### ISSUE TITLE
Mapbox doesn't display full until I open developer tools

### ISSUE THREAD

**Issue by DevEvil99** [mapbox/mapbox-gl-js#12766]
Im trying to generate a map and it will generate but the width is set to default until I open dev tools, how can I fix it? thank you!

```php
<div id="map" class="map" style="width:100%; height:400px; border-radius:24px;">
        </div>

        <script>
        mapboxgl.accessToken = 'MY_TOKEN'; 
        var map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/mapbox/streets-v12',
            center: [<?php echo $longitude; ?>, <?php echo $latitude; ?>],
            zoom: 12
        });
        

        var marker = new mapboxgl.Marker()
            .setLngLat([<?php echo $longitude; ?>, <?php echo $latitude; ?>])
            .addTo(map);
    </script>
```

![image](https://github.com/mapbox/mapbox-gl-js/assets/73029696/51e03960-3823-4c4e-a770-f965655b0029)
![image](https://github.com/mapbox/mapbox-gl-js/assets/73029696/5c505ae8-dae8-4d7f-ba7a-098cd68e1b5c)

**Comment by suryakumara** [comment]
Hi we have same problem. Anyone can solve this ?

**Comment by LongTalent** [comment]
Same here, using mapbox-gl in version 2.14.1

**Comment by suryakumara** [comment]
@LongTalent 
Hi, when the map instance you can try to add : 
```sh
window.addEventListener('fullscreenchange', () => {
    map.resize();
});
```
to listen fullscreenchange event.

**Comment by stepankuzmin** [comment]
Hi @DevEvil99,

Thank you for opening this ticket. Please provide a minimal, complete, verifiable demonstration of the issue to help the maintainers and community understand and address the problem accurately. We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.

**Comment by DevEvil99** [comment]
Hello @stepankuzmin 

I unfortunately lost my code but it was a PHP code that would get the IP of the user and used a API to get the city information and show that information in Mapbox code which I provided in the post, everything works perfectly but the map has a default value of 400px x 300px and it doesn't display full until I open developer tools, you can see better example [here](https://stackoverflow.com/questions/60216838/ionic-mapbox-doesnt-display-full-until-i-put-full-screen-or-open-developer-tool)

OS: Windows 10 
Browser: Brave. Version 1.52.129 Chromium: 114.0.5735.198 (Official Build) (64-bit)

**Comment by stepankuzmin** [comment]
Hi @suryakumara @LongTalent,

Could you please help us identify the issue? Could you create a small reproducible example of this issue?

**Comment by DevEvil99** [comment]
@stepankuzmin 

Something like this 

```
<?php
$ip = $_SERVER['REMOTE_ADDR'];
$access_key = 'ACCESS_KEY';

$response = file_get_contents("http://api.ipstack.com/$ip?access_key=$access_key");
$data = json_decode($response, true);

$longitude = $data['longitude'];
$latitude = $data['latitude'];
?>

<div id="map" class="map" style="width:100%; height:400px; border-radius:24px;"></div>

<script src="https://api.mapbox.com/mapbox-gl-js/v2.4.1/mapbox-gl.js"></script>
<link href="https://api.mapbox.com/mapbox-gl-js/v2.4.1/mapbox-gl.css" rel="stylesheet" />

<script>
    mapboxgl.accessToken = 'MY_TOKEN';
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v12',
        center: [<?php echo $longitude; ?>, <?php echo $latitude; ?>],
        zoom: 12
    });

    var marker = new mapboxgl.Marker()
        .setLngLat([<?php echo $longitude; ?>, <?php echo $latitude; ?>])
        .addTo(map);
</script>
```

**Comment by stepankuzmin** [comment]
@DevEvil99 Unfortunately, I'm not able to reproduce the error with your example. Can you reproduce it in other browsers, or is it only Brave?
