### ISSUE TITLE
License Mismatch: @mapbox/mapbox-gl-style-spec, ISC or Mapbox

### ISSUE THREAD

**Issue by fifafu** [mapbox/mapbox-gl-js#12778]
**mapbox-gl-js version**: 
```>= 2```

### Question
The npm package @mapbox/mapbox-gl-style-spec (version 13.28.0) indicates in its package.json file that it is licensed under the ISC license. However, it is incorporated into this monorepo, which prescribes the Mapbox Commercial license at its top level.

Could you please clarify which license is applicable to @mapbox/mapbox-gl-style-spec? This information is crucial to ascertain, as this package is utilized by several other open-source software.

### Links to related documentation

https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec

**Comment by mourner** [comment]
The `@mapbox/mapbox-gl-style-spec` is published under the ISC license.
