### ISSUE TITLE
map.style.sourceCaches 

### ISSUE THREAD

**Issue by Criska9527** [mapbox/mapbox-gl-js#12789]
map.style.sourceCaches       What is the current version replaced with

**Comment by stepankuzmin** [comment]
Hi @Criska9527,

Thank you for using mapbox-gl-js. It's unclear to me what you are trying to achieve. Could you please add more details on the issue? You can also provide a minimal, complete, verified demonstration of the issue to help the maintainers and community understand and address the problem accurately. We recommend using https://jsbin.com/.

Also, for future "how do I" questions like this, you can refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
