### ISSUE TITLE
fitbound function with the direction of progress

### ISSUE THREAD

**Issue by mungmoong2** [mapbox/mapbox-gl-js#12786]
**mapbox-gl-js version**: 
-   "@mapbox/mapbox-gl-language": "^1.0.0",
-  "@types/mapbox-gl": "^2.7.5",

### Question

Hello.

Please understand that we communicate using a translator due to our lack of English skills.

We are currently developing a map using React and Mapbox.

We used the coding below because we wanted to set the initial location of the map when the page was loaded.

[coding]

    const bounds = new mapboxgl.LngLatBounds();
    cgoData?.forEach((cgoItem: any) => {
      bounds.extend([cgoItem?.prtLogt, cgoItem?.prtLat]);
    });

    mapRef.current?.fitBounds(bounds, {
      duration: 1000,
    });

However, the 'fitBounds' function sets the center point of the nearest distance as the initial position.

We want to set the initial position, including the direction of the ship's progress, which is not always the shortest distance.

[The screen you see now]
![image1](https://github.com/mapbox/mapbox-gl-js/assets/47100635/31986377-cd1e-40d4-993c-d7afbd6f68c5)

[The screen that we want]
![image2](https://github.com/mapbox/mapbox-gl-js/assets/47100635/8437cbc6-36c9-47da-b166-52b82211afc4)

How can I set it up?

**Comment by stepankuzmin** [comment]
Hi @mungmoong2,

Thank you for using mapbox-gl-js. If I get it right, you want to expand the bounds you are zooming in. To do so, you can pass the `padding` option to the `fitBounds` call.

https://docs.mapbox.com/mapbox-gl-js/api/map/#map#fitbounds

```js
const bbox = [[-79, 43], [-73, 45]];
map.fitBounds(bbox, {
  padding: {top: 10, bottom:25, left: 15, right: 5}
});
```

You can also include the points ahead of progress into the `bounds.extend` call if you know them.

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
