### ISSUE TITLE
Using 3d terrain, vector tiles disappear when zooming in

### ISSUE THREAD

**Issue by frx08** [mapbox/mapbox-gl-js#12788]
Hello I have this problem, I tried to recreate it in codepen with minimal config and latest version of mapbox but is still there.
If I create a map with 3d terrain, load vector tiles with points, If i zoom in after zoom level 16, the vector points disappear, I expect the points to not disappear.
**If I disable 3d terrain I can zoom up to max and vector tiles are still visible**

**mapbox-gl-js version**: v2.15.0

**browser**: Chrome Version 114.0.5735.199

### Steps to Trigger Behavior

 1. load terrain
 2. load vector tiles
 3. zoom >=16

### Link to Demonstration
codepen dimostration: [https://codepen.io/frx08/pen/BaGdVor](https://codepen.io/frx08/pen/BaGdVor)

### Expected Behavior
this minimal script shows list of points as vector tiles, terrain is also loaded, zoom is set to 15.9 if I zoom in I expect the points to still be visible

### Actual Behavior
after zooming with zoom >=16 the points disappear

**Comment by bentaber** [comment]
I am seeing the same behavior. To verify I have created a geojson source and vector tiles from the same geojson source file, and added `circle` layers for each source.

- The geojson sourced circle features never dissapear (🔴 red circles). 
- The vector sourced circle features dissapear randomly when zooming, around zoom level 11 (🟢 green circles)
- Things behave correctly if terrain exaggeration is set to 0
- Other layer types `fill` and `line` _do not_ exhibit this behavior with vector tile sources and terrain exaggeration set to 1.

Source:
https://github.com/cloudninewx/mapbox-vector-circle-terrain-bug

Example behavior (terrain exaggeration = 1, zoom level >= 11):
https://cloudninewx.github.io/mapbox-vector-circle-terrain-bug/?exaggeration=1

Compare to (terrain exaggeration = 0):
https://cloudninewx.github.io/mapbox-vector-circle-terrain-bug/?exaggeration=0


https://github.com/mapbox/mapbox-gl-js/assets/175805/5d91f616-e9c4-43a5-84d1-6a37cd0a5dd1

**Comment by astojilj** [comment]
@bentaber 
There is a constraint with the implementation: vector tiles maxzoom (8 here)  needs to be greater than terrain’s DEM tile zoom (14).
Geojson when parsed, internally creates tiles up to max zoom 16 so there is no problem.

**Comment by bentaber** [comment]
Thank you @astojilj! I regenerated the test vector tile set to zoom level 15 and it works as desired.

While this is a usable work around, is it possible to slate a future enhancement/fix to have the vector tile internal representation work similarly to geojson with zoom levels above the tileset maxzoom? I ask as we deploy static z/x/y tile directory structures to s3-like storage, and going from a zoom level of 7 or 8 to 15 will increase our file counts by an order of magnitude or two.

**Comment by frx08** [comment]
@astojilj thanks for the hint, this solved the issue, my tileset was generated with `tippecanoe` that uses a default max-zoom of 13, I haven't found about this constraint and I thought I was able to use the over-zoom feature like it happens without the dem layer

**Comment by stepankuzmin** [comment]
Thanks for the help, @astojilj! Closing the issue since it's been resolved. Please reopen if you have any questions.
