### ISSUE TITLE
Mapbox geocoder [map.addControl(geocoder);] distorts in WordPress

### ISSUE THREAD

**Issue by NickWavve** [mapbox/mapbox-gl-js#12794]
I have added the Mapbox geocoder to my web map in the top-left position and made it collapsible.

![image](https://github.com/mapbox/mapbox-gl-js/assets/120218025/cd6ae98a-a68d-4ee5-a143-c0439aa00399)

As raw HTML it looks and works as expected.
![image](https://github.com/mapbox/mapbox-gl-js/assets/120218025/93eedd8c-a25d-4673-8a00-06ac9088550c)

However, once the code is copied and added into WordPress as a code block it completely distorts.
![image](https://github.com/mapbox/mapbox-gl-js/assets/120218025/fbf80423-5a62-44cb-b37f-601c7a2992ba)

Can't seem to figure out what causes this or how to fix it. Any thoughts?

Here is a copy of the current code:

[GeocoderIssue.txt](https://github.com/mapbox/mapbox-gl-js/files/12018372/GeocoderIssue.txt)

**Comment by stepankuzmin** [comment]
Hi, @NickWavve 

Please reopen the issue in the [mapbox-gl-geocoder](https://github.com/mapbox/mapbox-gl-geocoder) repo.
