### ISSUE TITLE
Support of shadow DOM

### ISSUE THREAD

**Issue by anthony-bernardo** [mapbox/mapbox-gl-js#12796]
Is mapbox working with shadow DOM ? 

It's seems that's marker are not working 

For exemple, https://github.com/Wykks/ngx-mapbox-gl/issues/240, this is exactly the same issue

**Comment by stepankuzmin** [comment]
Hi @anthony-bernardo,

Mapbox GL JS doesn't currently support Shadow DOM out of the box.
