### ISSUE TITLE
queryRenderedFeatures does not get full geometry of a feature

### ISSUE THREAD

**Issue by SourceCipher** [mapbox/mapbox-gl-js#12815]
**mapbox-gl-js version**: 2.15.0

**browser**: Brave v1.56.14

### The 🐞 

When hovering over the line, the output feature from the `queryRenderedFeatures` should always have the original geometry of the added line. Now every time you hover on this line, the geometry coordinates changes as you can see in the demo link. Change the zoom level and keep hovering on the different parts of the line. This will indicate the output of the coordinates changes in the top right corner. 

The feature should always contain in this case 12 coordinates within geometry, but it doesnt. We experienced this issue with the lines when we did the click, hover methods, or anytime we used `queryRenderedFeatures` function.

### Steps to Trigger Behavior

 1. Go to the link provided
 2. Hover on the line and see in the top right corner how many coordinates does the feature have

### Link to Demonstration

https://codepen.io/gmand/pen/zYamVGM

### Expected Behavior

It should always return the original feature when hovering on it with the original amount of coordinates.

### Actual Behavior

Depending on the zoom level and which part is being hovered over the line, the returned feature has different amount of coordinates within geometry.

**Comment by stevage** [comment]
What you're describing is absolutely fundamental to how vector tiles work. If you need the full geometry, you need to access it via  a different means.

**Comment by SourceCipher** [comment]
@stevage Yeah I was trying to do something different in our project but then realised that to do this we have to use `feature-state` and it works okay.
