### ISSUE TITLE
Error: Could not load image because of Cannot read properties of undefined (reading 'getImage')

### ISSUE THREAD

**Issue by dtabarceazeni** [mapbox/mapbox-gl-js#12810]
**mapbox-gl-js version**: 2.10.0

**browser**: Chrome, latest

### Steps to Trigger Behavior

 1.  open fiddle below
 2. open a console 
 3. wait a bit (max ~ 1 min)

### Link to Demonstration

https://jsfiddle.net/dnltbrca/uvjb3Ld1/

### Expected Behavior
No errors get thrown

### Actual Behavior
Could we at least have this error caught? Since it's coming straight from the library i can't do anything to prevent it from bubbling up. The behaviour of the map itself seems fine.  

![Screenshot 2023-07-19 at 18 54 49](https://github.com/mapbox/mapbox-gl-js/assets/109207790/56ce6f40-de50-4a19-93f8-702b4e2a6b30)

**Comment by agracia-foticos** [comment]
same issue with vue 3.5.3 and nuxt 3.13.1

**Comment by stepankuzmin** [comment]
Hey @dtabarceazeni @agracia-foticos,

Could you please try reproducing it with the latest version of GL JS?

**Comment by agracia-foticos** [comment]
@stepankuzmin with latest version of mapbox and nuxt-mapbox works fine!

**Comment by stepankuzmin** [comment]
Thanks for the confirmation @agracia-foticos 👍
