### ISSUE TITLE
GeoJSON rendering very slow with v0.8 for large data

### ISSUE THREAD

**Issue by benstadin** [mapbox/mapbox-gl-js#1282]
I have a large (several MB) GeoJSON file. The data is shown in 7 seconds with v0.7, but with v0.8 it takes 4 minutes and 31 seconds (I can rule out a server hickup, download speed of the file itself is the same). 

This is just copy paste example map, with mentioned GeoJSON data source in addition. 

~Ben

**Comment by mourner** [comment]
@benstadin do you pass the data directly in GeoJSONSource constructor, or an URL?

**Comment by mourner** [comment]
Meanwhile I'll test more on my big data samples... Previously my US zip codes 100MB test case was rendering pretty fast (in matter of seconds).

**Comment by mourner** [comment]
Yeah, 100Mb test case with about 6 million points loaded in 6 seconds. So if it's actually a problem on our side, you'll have to share your GeoJSON sample with us.

**Comment by benstadin** [comment]
In an URL. 

I've just installed all dependencies and deployed the current master to the same server. Speed is back to good. Seems the v08 version on your server is at fault.

**Comment by mourner** [comment]
@benstadin you're right, I just checked the source of the hosted version and it has an ancient geojson-vt inside, although in package.json there's a proper version specified. @jfirebaugh any clues what's going on here?

**Comment by jfirebaugh** [comment]
This is my fault, I didn't do a clean `npm install` before building 0.8.0. I'm going to switch to building the production version on CI to eliminate the human factor here, and then release 0.8.1.

**Comment by mourner** [comment]
Released https://api.tiles.mapbox.com/mapbox-gl-js/v0.8.1/mapbox-gl.js

**Comment by benstadin** [comment]
Loading is good again, but this version has an issue now with raster tiles. I get this error:

[Error] TypeError: undefined is not an object (evaluating 't.length')
	url (mapbox-gl.js, line 82)
	_loadTile (mapbox-gl.js, line 76)
	(anonyme Funktion) ([native code], line 0)
	addTile (mapbox-gl.js, line 84)
	update (mapbox-gl.js, line 84)
	update (mapbox-gl.js, line 76)
	_updateSources (mapbox-gl.js, line 104)
	render (mapbox-gl.js, line 162)
	(anonyme Funktion) ([native code], line 0)

My map is just the one from the raster example:

var map = new mapboxgl.Map({
  container: 'map', // container id
  style: {
    "version": 7,
    "sources": {
      "simple-tiles": {
        "type": "raster",
        "url": "",
        "tileSize": 256
      }
    },
    "layers": [{
      "id": "simple-tiles",
      "type": "raster",
      "source": "simple-tiles",
      "minzoom": 0,
      "maxzoom": 22
    }]
  },
  center: [40, -74.50], // starting position
  zoom: 2 // starting zoom
});

**Comment by mourner** [comment]
@benstadin the example works well for me https://www.mapbox.com/mapbox-gl-js/example/map-tiles/. In any case, you should make a JSFiddle test case and then open a new issue.

**Comment by benstadin** [comment]
I need to change the data set first. I can't upload the data I have, unfortunately (customer data). Though the issue didn't reappear after I cleaned the browser cache, seems a hickup.

I found another issue when mixing GeoJSON with raster tiles. Will open a new issue.

Thank you for your fast response and fix.
