### ISSUE TITLE
Non-interactive maps should not have a `tabindex`

### ISSUE THREAD

**Issue by bostondv** [mapbox/mapbox-gl-js#12822]
## Motivation

When instantiating a new `Map` with `interactive=false` the map is unactionable. Unactionable elements for accessibility should not have a `tabindex=0` and should not receive focus when tabbing through the HTML document.

Currently, maps [always have `tabindex` attribute set on the canvas](https://github.com/mapbox/mapbox-gl-js/blob/85ff58ce6730b6cefe0e9ce22b464d7cce16c74b/src/ui/map.js#L2942).

## Design Alternatives

N/A

### Mock-Up

N/A

### Concepts

N/A

### Implementation

I suggest that when creating a new non-interactive Map that the `tabindex` attribute is not set.

**Comment by kumiko-haraguchi** [comment]
@stepankuzmin Hi, is it ok to take this issue? 🙏🏻  I made a [draft PR](https://github.com/mapbox/mapbox-gl-js/pull/12852) but wasn't sure if someone is already working on it.

**Comment by stepankuzmin** [comment]
@kumiko-haraguchi sure! Thanks for the contribution!
