### ISSUE TITLE
Notes about model layer

### ISSUE THREAD

**Issue by astojilj** [mapbox/mapbox-gl-js#12847]
This issue collects pointers to code examples related to the model layer and clarifies the current state of implementation.

Model Layer is an **experimental** feature that renders 3D buildings and trees [in Standard Style (the blog post)](https://www.mapbox.com/blog/standard-core-style). It is available in [Mapbox GL JS v3](https://github.com/mapbox/mapbox-gl-js/blob/main/MIGRATION_GUIDE_v3.md) and Mapbox Maps SDK v11 for [iOS](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Documentation.docc/Migrate%20to%20v11.md) and [Android](https://github.com/mapbox/mapbox-maps-android/blob/main/docs/Migrate%20to%20v11.md) prereleases. _Experimental_ means it is still under development and prone to changes.

The model layer renders content from the following sources:
1. vector or geojson. Used for trees in Standard Style.
2. batched-model. Used for Mapbox landmark buildings in Standard style.
3. model-source. Please don't use this. This is used in some render tests; it is internal and will likely be removed from production code.

For use cases that require placing 3rd party models on the map, the approach _1. vector or geojson_ should be used, for now. The Standard [style trees example ](https://github.com/mapbox/mapbox-gl-js/blob/f501fa4498b22f9193a6fe3e8852dc1aeafac812/debug/dynamic.js#L5491) shows usage of [LOD](https://github.com/mapbox/mapbox-gl-js/blob/main/debug/dynamic.js#L5491), assigning different glTF models to features of geometry type point, assigning pseudo-random [rotation](https://github.com/mapbox/mapbox-gl-js/blob/f501fa4498b22f9193a6fe3e8852dc1aeafac812/debug/dynamic.js#L5854), model [color](https://github.com/mapbox/mapbox-gl-js/blob/f501fa4498b22f9193a6fe3e8852dc1aeafac812/debug/dynamic.js#L5818) (and amount of [color mix with original colors](https://github.com/mapbox/mapbox-gl-js/blob/f501fa4498b22f9193a6fe3e8852dc1aeafac812/debug/dynamic.js#L5836)) and [scale](https://github.com/mapbox/mapbox-gl-js/blob/f501fa4498b22f9193a6fe3e8852dc1aeafac812/debug/dynamic.js#L5867) to every instance. There are multiple other examples within [render tests](https://github.com/mapbox/mapbox-gl-js/blob/main/test/integration/render-tests/model-layer/).

![Screenshot 2023-08-14 at 8 57 38](https://github.com/mapbox/mapbox-gl-js/assets/549216/035848be-9e4b-4fc6-b235-a6839de90cf1)

### To load glTF models, use addModel
Load glTF model and assign an id. API: 

https://github.com/mapbox/mapbox-gl-js-internal/blob/534a5672c3eea2c40dd6d774220fb5246c94db52/src/ui/map.js#L2358-L2380

### to assign the model to a point geometry defined in source

- example1 ([using source and source-layer](https://github.com/mapbox/mapbox-gl-js/blob/f501fa4498b22f9193a6fe3e8852dc1aeafac812/debug/dynamic.js#L5913))  
- example2 ([using geojson source](https://github.com/mapbox/mapbox-gl-js/blob/f501fa4498b22f9193a6fe3e8852dc1aeafac812/test/integration/render-tests/model-layer/powerplants-float-zoom-lod/style.json#L177))

### LOD
If there is a large number of complex models to display, it is essential to use LOD approach. Use addModel to load and assign model ID to all the LOD variants. Then, use model layer's `model-id` property to assign the model id variants to different zoom levels. Zoom level gets evaluated during rendering, based on the distance to the camera, and different LOD variants get chosen for rendering.

e.g. from powerplants-float-zoom-lod render test
```
        "model-id": [
          "step",
          ["zoom"],
          "power_plant_lowest_detail",
          4.6,
          "power_plant_low_transparent",
          6.1,
          "power_plant_low",
          7.5,          
          "power_plant"
        ]
```

Some of the LOD examples:
- [powerplants-float-zoom-lod render test](https://github.com/mapbox/mapbox-gl-js/blob/f501fa4498b22f9193a6fe3e8852dc1aeafac812/test/integration/render-tests/model-layer/powerplants-float-zoom-lod/style.json)

- standard style debug page combines LOD with assigning different models based on leaf type and additional random assignment of different models for the same leaf type:

https://github.com/mapbox/mapbox-gl-js/blob/main/debug/dynamic.js#L5491-L5520

Note how the render test and debug page style don't use addModel API but achieve the equivalent by assigning models ids to glTF URIs in style:

https://github.com/mapbox/mapbox-gl-js/blob/f501fa4498b22f9193a6fe3e8852dc1aeafac812/debug/dynamic.js#L117-L119

### Examples:

Standard style debug page (outdated version):
1. [Serve debug pages,](https://github.com/mapbox/mapbox-gl-js/blob/f501fa4498b22f9193a6fe3e8852dc1aeafac812/CONTRIBUTING.md#serving-the-debug-page)
2. open http://localhost:9966/debug/3d-playground.html 

Mapbox Maps SDK v11 for iOS: 
[Apps/Examples/Examples/All Examples/ModelLayerExample.swift](https://github.com/mapbox/mapbox-maps-ios/blob/dbfa68106f95d92cb218345bfd139bce03840ec7/Apps/Examples/Examples/All%20Examples/ModelLayerExample.swift#L46)

**Comment by astojilj** [comment]
closing as this issue is used as temporary documentation.

**Comment by astojilj** [comment]
cc @soheilnikbin @b4rtt  @ajbraudev @JeyBi24 @JeyBi24 @NickLambert95 @nicolae1992 @noway - you have expressed interest in Android and iOS support in https://github.com/mapbox/mapbox-gl-native/issues/14494.

**Comment by markhougaard** [comment]
This is great @astojilj 👏 

One note: There's a link to the internal version of this repo in the text here:

```
To load glTF models, use addModel

Load glTF model and assign an id. API:

https://github.com/mapbox/mapbox-gl-js-internal/blob/534a5672c3eea2c40dd6d774220fb5246c94db52/src/ui/map.js#L2358-L2380
```

I figured you wanted to link to the external version of it: https://github.com/mapbox/mapbox-gl-js/blob/068a7f32954b3cb3d0754ec0e263b816a9eb3fd1/src/ui/map.js#L2355

**Comment by morlic** [comment]
Great feature :) Is it possible to update the data source and move the placement of the model dynamically?
