### ISSUE TITLE
3.0.0 beta 1: Require Glyphs

### ISSUE THREAD

**Issue by protrakit** [mapbox/mapbox-gl-js#12845]
**mapbox-gl-js version**: 3.0.0 beta 1

**browser**: Edge

### Steps to Trigger Behavior

 1. Set style to standard
 2. Add symbol layer
 3.

### Link to Demonstration

https://jsbin.com/

### Actual Behavior

Returning error when adding symbol layer:
layout.text-field: use of "text-field" requires a style "glyphs" property

**Comment by huanglii** [comment]
+1

**Comment by stepankuzmin** [comment]
Hi @protrakit,

Thank you for opening this ticket. I wasn't able to reproduce this issue. Please provide a minimal, complete, verifiable demonstration of the issue to help the maintainers and community understand and address the problem accurately. We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.

**Comment by ashleyclough** [comment]
I've spotted the same issue. The Mapbox 'Add Marker' example at https://docs.mapbox.com/mapbox-gl-js/example/geojson-markers/ will throw the error when using version 3.0.0 beta 1 and commenting out the streets-v12 style so as to default to the new standard map style. I've not yet spotted anywhere the details of how to explicitly link to the standard style so can't test that configuration.

**Comment by stepankuzmin** [comment]
Yes, this is expected with the Standard Style. The assets in Standard Style are unavailable through the public API as with `streets-v12`, i.e., you can't access the icons from the Standard Style. To use your own icons, you'd need to add them with [`map.addImage`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addimage).

**Comment by ashleyclough** [comment]
The Mapbox example is using addImage from a loaded jpg file and still fails.

**Comment by protrakit** [comment]
With the text field error I’m getting, it’s because I have a custom font
uploaded to my studio. How can I point the standard style to my account
fonts/glyphs?

Also, when adding circle layers the circle takes up the entire map when
zooming in.

**Comment by stepankuzmin** [comment]
Thanks for the comments, @protrakit

> With the text field error I’m getting, it’s because I have a custom font
uploaded to my studio.

So you've uploaded a custom font in the Studio and trying to reference it in the map that uses the Standard Style?

> Also, when adding circle layers the circle takes up the entire map when
zooming in.

Yes, this is a known issue and we are working on fixing it.

**Comment by protrakit** [comment]
Yes, I’d like to reference if possible, but if the circle layer needs
fixing, then I’ll just hold off until it’s working correctly. Doesn’t
really do me any good right now with not being able to add features to the
map. Thank you for the quick updates!

**Comment by protrakit** [comment]
So, I dug into this for a bit this morning and this what I found:
- I can set the glyph manager url by doing map.style.glyphManager.setURL(url, importId)
- I can set the "font" property by doing map.setConfigProperty('basemap', 'font', value)

But, you have to use a secret token to be able to list the fonts and also when ajax makes the request it's appending 'Regular', 'Medium', 'Bold', 'Italics' to the url. I believe if these two weren't an issue, then it would work.

**Comment by aaroncrawford** [comment]
@protrakit @stepankuzmin  Can you get text-field's to work when using just the default fonts that Mapbox uses?  I think it was Arial and Din?  I'm stuck on the same problem when using the following:
`map.addLayer({
	id: "name",
	type: "symbol",
	source: "name",
	layout: {
		"text-field": ["get", "description"],
		"text-size": 10,
	},
	paint: {
		"text-color": "#000",
	},
})
`

After attempting to apply this layer, I get `mapbox-gl.js:31 Error: layers.name.layout.text-field: use of "text-field" requires a style "glyphs" property`

Works fine in the old version which is v1, so attempting to figure out how to get this on Mapbox Standard with v3.

Anyway to get around this with v3 beta 1?

**Comment by GordoRank** [comment]
I don't have much to add other than to say that I'm having exactly the same issue here.
