### ISSUE TITLE
My map crash when zoom in or out after popup is show

### ISSUE THREAD

**Issue by Paradorn-248** [mapbox/mapbox-gl-js#12846]
**mapbox-gl-js version**: 2.15.0

**browser**: chrome

### Steps to Trigger Behavior
``` vue
mounted() {
		let center = process.env.VUE_APP_MAPBOX_CENTER_COORDINATES.split(',').map(parseFloat)
		this.map = new mapboxgl.Map({
			accessToken: process.env.VUE_APP_MAPBOX_ACCESS_TOKEN,
			container: 'map',
			style: process.env.VUE_APP_MAPBOX_STYLE,
			center: center,
			zoom: this.zoom
		});
	},
	methods: {
		checkUserPermissions() {
			const userPermission = getPermissions()
			this.permissions.canView = hasPermission(userPermission, Permissions.payment.VIEW_MATCH_RATE)
		},
		async getItemByRegion() {
			try {
				loadingScreen('Processing ...')
				this.$router.replace({ query: this.query }).catch(() => { })
				this.renderHexes()
			} catch (error) {
				await displayErrorModal({ error })
			} finally {
				loadingScreenClose('Processing ...')
			}
		},
		async renderHexes() {
			// this.areasData = (await getLinemanwalletAvailabilityByRegion(this.query)).data.data.areas;
			this.areasData = [{ region: "BKK", area: "8664a4b17ffffff", matchrateInConfig: 22, riderMatchrate: 23, linemanWalletState: "enabled" }, { region: "BKK", area: "8664a4b18ffffff", matchrateInConfig: 22, riderMatchrate: 23, linemanWalletState: "disabled" }]
			// this.areasData = [{ region: "BKK", area: "8664a4b17ffffff", matchrateInConfig: 22, riderMatchrate: 23, linemanWalletState: "enabled" }]
			const hexagonCoordinates = [];
			const coordinates = cellToLatLng(this.areasData[0].area);
			const centerLngLat = [coordinates[1], coordinates[0]]
			this.map.jumpTo({
				center: centerLngLat,
				zoom: this.zoom
			})

			this.clearLayerAndSource()

			for (let i = 0; i < this.areasData.length; i++) {
				const polygonCoordinates = geojson2h3.h3ToFeature(this.areasData[i].area);
				hexagonCoordinates.push(polygonCoordinates);
				this.h3HexesSourceIds.push(`h3-polygon-${i}`)
				this.h3HexesFillLayerIds.push(`h3-polygon-${i}-fill`)
				this.h3HexesLineLayerIds.push(`h3-polygon-${i}-line`)
			}
			console.log("hexagonCoordinates:", hexagonCoordinates)
			console.log("h3HexesLayerIds:", this.h3HexesSourceIds)

			for (let i = 0; i < hexagonCoordinates.length; i++) {
				this.map.addSource(`h3-polygon-${i}`, {
					'type': 'geojson',
					'data': hexagonCoordinates[i]
				});

				this.map.addLayer({
					'id': `h3-polygon-${i}-fill`,
					'type': 'fill',
					'source': `h3-polygon-${i}`,
					'layout': {},
					'paint': {
						'fill-color': this.getAreaColor(this.areasData[i]),
						'fill-opacity': 0.5
					}
				});

				this.map.addLayer({
					'id': `h3-polygon-${i}-line`,
					'type': 'line',
					'source': `h3-polygon-${i}`,
					'layout': {},
					'paint': {
						'line-color': '#000',
						'line-width': 1
					}
				});

				this.mousemoveHover(i)
				this.mouseleaveHover(i)
			}
		},
		clearLayerAndSource() {
			for (const layerId of this.h3HexesSourceIds) {
				console.log("layerId:", layerId)
				if (this.map.getLayer(layerId + "-fill") && this.map.getLayer(layerId) + "-line") {
					this.map.removeLayer(layerId + "-fill");
					this.map.removeLayer(layerId + "-line");
				}
				if (this.map.getSource(layerId)) {
					this.map.removeSource(layerId);
				}
			}
			this.h3HexesFillLayerIds = []
			this.h3HexesLayerIds = []
			this.h3HexesSourceIds = []
		},
		mousemoveHover(i){
			const popupContent = this.getPopupContent(this.areasData[i])
				this.map.on('mouseenter', `h3-polygon-${i}-fill`, () => {
					this.map.getCanvas().style.cursor = 'pointer';
					const coordinates = cellToLatLng(this.areasData[i].area);
					const center = [coordinates[1], coordinates[0]]
					this.popup = new mapboxgl.Popup({ closeButton: false })
						.setLngLat(center)
						.setHTML(popupContent)
						.addTo(this.map);
				});
		},
		mouseleaveHover(i) {
			this.map.on('mouseleave', `h3-polygon-${i}-fill`, () => {
					this.map.getCanvas().style.cursor = '';
					this.popup.remove()
				});
		},
		getAreaColor(area) {
			let color = "#61cc61"
			if (area.linemanWalletState === "disabled") {
				color = "#e35f5f"
			}
			return color
		},
		getPopupContent(area) {
			return `<div>
						<strong>Region:</strong> ${area.region}<br>
						<strong>Area:</strong> ${area.area}<br>
						<strong>Match Rate In Config:</strong> ${area.matchrateInConfig}<br>
						<strong>Rider Match Rate:</strong> ${area.riderMatchrate}<br>
						<strong>State:</strong> ${area.linemanWalletState}<br>
					</div>`
		},
```
 1. Before popup show: can zoom in/out normally
<img width="839" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/80895278/580efa4f-5d28-43fe-a850-63443fb41d14">
<img width="837" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/80895278/2db849dc-bf5f-49b1-adca-d82f286c5f27">

 2. After popup show (hover polygon) : map dump when zoom in/out
<img width="837" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/80895278/3a42c02b-2c27-43ed-a260-6828006d5069">

### Expected Behavior
Can zoom in/out properly
### Actual Behavior
Map crash

**Comment by Paradorn-248** [comment]
`
mounted() {
		let center = process.env.VUE_APP_MAPBOX_CENTER_COORDINATES.split(',').map(parseFloat)
		this.map = new mapboxgl.Map({
			accessToken: process.env.VUE_APP_MAPBOX_ACCESS_TOKEN,
			container: 'map',
			style: process.env.VUE_APP_MAPBOX_STYLE,
			center: center,
			zoom: this.zoom
		});
	},
	methods: {
		checkUserPermissions() {
			const userPermission = getPermissions()
			this.permissions.canView = hasPermission(userPermission, Permissions.payment.VIEW_MATCH_RATE)
		},
		async getItemByRegion() {
			try {
				loadingScreen('Processing ...')
				this.$router.replace({ query: this.query }).catch(() => { })
				this.renderHexes()
			} catch (error) {
				await displayErrorModal({ error })
			} finally {
				loadingScreenClose('Processing ...')
			}
		},
		async renderHexes() {
			// this.areasData = (await getLinemanwalletAvailabilityByRegion(this.query)).data.data.areas;
			this.areasData = [{ region: "BKK", area: "8664a4b17ffffff", matchrateInConfig: 22, riderMatchrate: 23, linemanWalletState: "enabled" }, { region: "BKK", area: "8664a4b18ffffff", matchrateInConfig: 22, riderMatchrate: 23, linemanWalletState: "disabled" }]
			// this.areasData = [{ region: "BKK", area: "8664a4b17ffffff", matchrateInConfig: 22, riderMatchrate: 23, linemanWalletState: "enabled" }]
			const hexagonCoordinates = [];
			const coordinates = cellToLatLng(this.areasData[0].area);
			const centerLngLat = [coordinates[1], coordinates[0]]
			this.map.jumpTo({
				center: centerLngLat,
				zoom: this.zoom
			})

			this.clearLayerAndSource()

			for (let i = 0; i < this.areasData.length; i++) {
				const polygonCoordinates = geojson2h3.h3ToFeature(this.areasData[i].area);
				hexagonCoordinates.push(polygonCoordinates);
				this.h3HexesSourceIds.push(`h3-polygon-${i}`)
				this.h3HexesFillLayerIds.push(`h3-polygon-${i}-fill`)
				this.h3HexesLineLayerIds.push(`h3-polygon-${i}-line`)
			}
			console.log("hexagonCoordinates:", hexagonCoordinates)
			console.log("h3HexesLayerIds:", this.h3HexesSourceIds)

			for (let i = 0; i < hexagonCoordinates.length; i++) {
				this.map.addSource(`h3-polygon-${i}`, {
					'type': 'geojson',
					'data': hexagonCoordinates[i]
				});

				this.map.addLayer({
					'id': `h3-polygon-${i}-fill`,
					'type': 'fill',
					'source': `h3-polygon-${i}`,
					'layout': {},
					'paint': {
						'fill-color': this.getAreaColor(this.areasData[i]),
						'fill-opacity': 0.5
					}
				});

				this.map.addLayer({
					'id': `h3-polygon-${i}-line`,
					'type': 'line',
					'source': `h3-polygon-${i}`,
					'layout': {},
					'paint': {
						'line-color': '#000',
						'line-width': 1
					}
				});

				this.mousemoveHover(i)
				this.mouseleaveHover(i)
			}
		},
		clearLayerAndSource() {
			for (const layerId of this.h3HexesSourceIds) {
				console.log("layerId:", layerId)
				if (this.map.getLayer(layerId + "-fill") && this.map.getLayer(layerId) + "-line") {
					this.map.removeLayer(layerId + "-fill");
					this.map.removeLayer(layerId + "-line");
				}
				if (this.map.getSource(layerId)) {
					this.map.removeSource(layerId);
				}
			}
			this.h3HexesFillLayerIds = []
			this.h3HexesLayerIds = []
			this.h3HexesSourceIds = []
		},
		mousemoveHover(i){
			const popupContent = this.getPopupContent(this.areasData[i])
				this.map.on('mouseenter', `h3-polygon-${i}-fill`, () => {
					this.map.getCanvas().style.cursor = 'pointer';
					const coordinates = cellToLatLng(this.areasData[i].area);
					const center = [coordinates[1], coordinates[0]]
					this.popup = new mapboxgl.Popup({ closeButton: false })
						.setLngLat(center)
						.setHTML(popupContent)
						.addTo(this.map);
				});
		},
		mouseleaveHover(i) {
			this.map.on('mouseleave', `h3-polygon-${i}-fill`, () => {
					this.map.getCanvas().style.cursor = '';
					this.popup.remove()
				});
		},
		getAreaColor(area) {
			let color = "#61cc61"
			if (area.linemanWalletState === "disabled") {
				color = "#e35f5f"
			}
			return color
		},
		getPopupContent(area) {
			return `<div>
						<strong>Region:</strong> ${area.region}<br>
						<strong>Area:</strong> ${area.area}<br>
						<strong>Match Rate In Config:</strong> ${area.matchrateInConfig}<br>
						<strong>Rider Match Rate:</strong> ${area.riderMatchrate}<br>
						<strong>State:</strong> ${area.linemanWalletState}<br>
					</div>`
		},
`

**Comment by Paradorn-248** [comment]
```
mounted() {
		let center = process.env.VUE_APP_MAPBOX_CENTER_COORDINATES.split(',').map(parseFloat)
		this.map = new mapboxgl.Map({
			accessToken: process.env.VUE_APP_MAPBOX_ACCESS_TOKEN,
			container: 'map',
			style: process.env.VUE_APP_MAPBOX_STYLE,
			center: center,
			zoom: this.zoom
		});
	},
	methods: {
		checkUserPermissions() {
			const userPermission = getPermissions()
			this.permissions.canView = hasPermission(userPermission, Permissions.payment.VIEW_MATCH_RATE)
		},
		async getItemByRegion() {
			try {
				loadingScreen('Processing ...')
				this.$router.replace({ query: this.query }).catch(() => { })
				this.renderHexes()
			} catch (error) {
				await displayErrorModal({ error })
			} finally {
				loadingScreenClose('Processing ...')
			}
		},
		async renderHexes() {
			// this.areasData = (await getLinemanwalletAvailabilityByRegion(this.query)).data.data.areas;
			this.areasData = [{ region: "BKK", area: "8664a4b17ffffff", matchrateInConfig: 22, riderMatchrate: 23, linemanWalletState: "enabled" }, { region: "BKK", area: "8664a4b18ffffff", matchrateInConfig: 22, riderMatchrate: 23, linemanWalletState: "disabled" }]
			// this.areasData = [{ region: "BKK", area: "8664a4b17ffffff", matchrateInConfig: 22, riderMatchrate: 23, linemanWalletState: "enabled" }]
			const hexagonCoordinates = [];
			const coordinates = cellToLatLng(this.areasData[0].area);
			const centerLngLat = [coordinates[1], coordinates[0]]
			this.map.jumpTo({
				center: centerLngLat,
				zoom: this.zoom
			})

			this.clearLayerAndSource()

			for (let i = 0; i < this.areasData.length; i++) {
				const polygonCoordinates = geojson2h3.h3ToFeature(this.areasData[i].area);
				hexagonCoordinates.push(polygonCoordinates);
				this.h3HexesSourceIds.push(`h3-polygon-${i}`)
				this.h3HexesFillLayerIds.push(`h3-polygon-${i}-fill`)
				this.h3HexesLineLayerIds.push(`h3-polygon-${i}-line`)
			}
			console.log("hexagonCoordinates:", hexagonCoordinates)
			console.log("h3HexesLayerIds:", this.h3HexesSourceIds)

			for (let i = 0; i < hexagonCoordinates.length; i++) {
				this.map.addSource(`h3-polygon-${i}`, {
					'type': 'geojson',
					'data': hexagonCoordinates[i]
				});

				this.map.addLayer({
					'id': `h3-polygon-${i}-fill`,
					'type': 'fill',
					'source': `h3-polygon-${i}`,
					'layout': {},
					'paint': {
						'fill-color': this.getAreaColor(this.areasData[i]),
						'fill-opacity': 0.5
					}
				});

				this.map.addLayer({
					'id': `h3-polygon-${i}-line`,
					'type': 'line',
					'source': `h3-polygon-${i}`,
					'layout': {},
					'paint': {
						'line-color': '#000',
						'line-width': 1
					}
				});

				this.mousemoveHover(i)
				this.mouseleaveHover(i)
			}
		},
		clearLayerAndSource() {
			for (const layerId of this.h3HexesSourceIds) {
				console.log("layerId:", layerId)
				if (this.map.getLayer(layerId + "-fill") && this.map.getLayer(layerId) + "-line") {
					this.map.removeLayer(layerId + "-fill");
					this.map.removeLayer(layerId + "-line");
				}
				if (this.map.getSource(layerId)) {
					this.map.removeSource(layerId);
				}
			}
			this.h3HexesFillLayerIds = []
			this.h3HexesLayerIds = []
			this.h3HexesSourceIds = []
		},
		mousemoveHover(i){
			const popupContent = this.getPopupContent(this.areasData[i])
				this.map.on('mouseenter', `h3-polygon-${i}-fill`, () => {
					this.map.getCanvas().style.cursor = 'pointer';
					const coordinates = cellToLatLng(this.areasData[i].area);
					const center = [coordinates[1], coordinates[0]]
					this.popup = new mapboxgl.Popup({ closeButton: false })
						.setLngLat(center)
						.setHTML(popupContent)
						.addTo(this.map);
				});
		},
		mouseleaveHover(i) {
			this.map.on('mouseleave', `h3-polygon-${i}-fill`, () => {
					this.map.getCanvas().style.cursor = '';
					this.popup.remove()
				});
		},
		getAreaColor(area) {
			let color = "#61cc61"
			if (area.linemanWalletState === "disabled") {
				color = "#e35f5f"
			}
			return color
		},
		getPopupContent(area) {
			return `<div>
						<strong>Region:</strong> ${area.region}<br>
						<strong>Area:</strong> ${area.area}<br>
						<strong>Match Rate In Config:</strong> ${area.matchrateInConfig}<br>
						<strong>Rider Match Rate:</strong> ${area.riderMatchrate}<br>
						<strong>State:</strong> ${area.linemanWalletState}<br>
					</div>`
		},
```

**Comment by stepankuzmin** [comment]
Hi @Paradorn-248,

Thank you for opening this ticket. Please provide an isolated, minimal, complete, verifiable demonstration of the issue to help the maintainers and community understand and address the problem accurately. We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.

**Comment by Paradorn-248** [comment]
I found my bug already. It must new only on popup. Thanks for your response.
