### ISSUE TITLE
Can still get the source after map.removeSource('maine')

### ISSUE THREAD

**Issue by huanglii** [mapbox/mapbox-gl-js#12844]
**mapbox-gl-js version**: v3.0.0-beta.1

**browser**:

### Steps to Trigger Behavior

 1. map.addSource('maine', {...})
 ```js
map.addSource('maine', {
  type: 'geojson',
  data: {
    type: 'Feature',
    geometry: {
      type: 'Polygon',
      // These coordinates outline Maine.
      coordinates: [
        [
          [-67.13734, 45.13745],
          [-66.96466, 44.8097],
          [-68.03252, 44.3252],
          [-69.06, 43.98],
          [-70.11617, 43.68405],
          [-70.64573, 43.09008],
          [-70.75102, 43.08003],
          [-70.79761, 43.21973],
          [-70.98176, 43.36789],
          [-70.94416, 43.46633],
          [-71.08482, 45.30524],
          [-70.66002, 45.46022],
          [-70.30495, 45.91479],
          [-70.00014, 46.69317],
          [-69.23708, 47.44777],
          [-68.90478, 47.18479],
          [-68.2343, 47.35462],
          [-67.79035, 47.06624],
          [-67.79141, 45.70258],
          [-67.13734, 45.13745],
        ],
      ],
    },
  },
})
```
 3. map.removeSource('maine')
 4. map.getSource('maine') // still return the source

### Link to Demonstration

https://codesandbox.io/s/removesource-5jvfc3

### Expected Behavior
undefined
### Actual Behavior
<img width="403" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/20068340/216f62d8-e5d6-495f-8dc0-b5d66296aa53">

**Comment by rreusser** [comment]
Just to add one additional piece of info, removeSource does not actually remove the source, but calling removeSource a second time fails with `Uncaught Error: There is no source with this ID`. So I guess the source is in a half-deleted state. 

Here's a quick codepen to demonstrate: https://codepen.io/rsreusser/pen/KKbPdeg
