### ISSUE TITLE
GeoJSON "tiles" occluded when using raster tiles

### ISSUE THREAD

**Issue by benstadin** [mapbox/mapbox-gl-js#1284]
I have a large GeoJSON which is overlayed over a raster tile map. Several tiles of the postprocessed GeoJSON data are occluded, and only get visible when zooming into the map. 

This does not happen when using vector tiles - and I cannot see a pattern for when tiles are occluded. It seems more or less random. 

I can share a link with data via private message if required. 

Edit: The issue occurs with both tested versions (0.7 and 0.8.1).

**Comment by jfirebaugh** [comment]
Hi @benstadin -- can you send the link to john@mapbox.com? Thanks!

**Comment by jfirebaugh** [comment]
Investigation revealed that this was due to the same cause as #1291 -- adding a "glyphs" property to the custom style resolved the issue.
