### ISSUE TITLE
The feature of map.queryRenderedFeatures(e.point) lost layer properties

### ISSUE THREAD

**Issue by huanglii** [mapbox/mapbox-gl-js#12849]
**mapbox-gl-js version**: v3.0.0-beta.1

**browser**:

### Steps to Trigger Behavior

 1. const features = map.queryRenderedFeatures(e.point)
 2. console.log(features[0].layer)

### Link to Demonstration

https://jsbin.com/mitixovuse/edit?html,console,output

### Expected Behavior
```js
{
  filter: ["match", ["get", "class"], ["military", "civil", "disputed_military", "disputed_civil"], ["match", ["get", "worldview"], ["all", "US"], true, false], false],
  id: "airport-label",
  layout: [object Object] {
    icon-image: [object Object] { ... },
    text-anchor: "top",
    text-field: [object Object] { ... },
    text-font: ["DIN Pro Medium", "Arial Unicode MS Regular"],
    text-letter-spacing: 0.01,
    text-line-height: 1.1,
    text-max-width: 9,
    text-offset: [0, 0.8],
    text-rotation-alignment: "viewport",
    text-size: 12
  },
  metadata: [object Object] {
    mapbox:featureComponent: "transit",
    mapbox:group: "Transit, transit-labels"
  },
  minzoom: 8,
  paint: [object Object] {
    text-color: [object Object] { ... },
    text-halo-color: [object Object] { ... },
    text-halo-width: 1
  },
  source: "composite",
  source-layer: "airport_label",
  type: "symbol"
}
```
### Actual Behavior
```js
{
  layout: {},
  paint: {}
}
```

**Comment by huanglii** [comment]
> * map.queryRenderedFeatures(e.point)
> * console.log(features[0].layer)

https://codesandbox.io/s/queryrenderedfeatures-94v53p?file=/index.html

**Comment by huanglii** [comment]
> Hi @huanglii
> 
> The example you provided is not available for some reason https://jsbin.com/mitixovuse/edit?html,console,output
> 
> Could you please check that it's working or move it to another sandbox?

https://codesandbox.io/s/queryrenderedfeatures-94v53p?file=/index.html

**Comment by stepankuzmin** [comment]
I can reproduce it now, thanks, @huanglii!

**Comment by kumiko-haraguchi** [comment]
@huanglii @stepankuzmin 
Hi, it seems like the reported behavior of the new standard style(basemap) is as expected according to the comment and code here. The internals are **not meant to be exposed**?
https://github.com/mapbox/mapbox-gl-js/blob/main/src/style/style.js#L521-L532

Once I remove the code above, I can see the clicked feature's layer properties.

**Current behavior**
![](http://g.recordit.co/ofTbkZASLy.gif)

**After removing the code**
![](http://g.recordit.co/TYq3QrdPCk.gif)

**Comment by stepankuzmin** [comment]
Hi @kumiko-haraguchi,

> The internals are not meant to be exposed

That's correct. The underlying internals of the Standard Style are not meant to be accessible with the current API. We're currently focusing on developing a new way to expose internals that will allow us to ship the latest versions of the Standard Style and not break the client code that might depend on those internals.

I'm closing the issue as we are not planning to expose the Standard Style features with the `map.queryRenderedFeatures`, and it will no longer return those features in the upcoming beta release. Feel free to comment here if you have any questions.

**Comment by alexwohlbruck** [comment]
is there any workaround for this? in trying not to break the API for developers, ironically, you've done just that
