### ISSUE TITLE
Tree models should be anchored to custom terrain source

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#12853]
**mapbox-gl-js version**: v3.0.0-beta.1

**browser**: Chrome

### Steps to Trigger Behavior

Add a custom `raster-dem` source, then use it in `setTerrain`.

```
map.addSource('custom-dem', {
  type: 'raster-dem',
  tiles: ['http://localhost:8000/terrain/tiles/{z}/{x}/{y}.webp'],
  tileSize: 256,
  maxzoom: 16
})
map.setTerrain({'source': 'custom-dem', 'exaggeration': 1 })
```

### Link to Demonstration

to be provided if needed

`mapbox://mapbox.mapbox-terrain-dem-v1` terrain source
![2023-08-16_13-16_1](https://github.com/mapbox/mapbox-gl-js/assets/117278/347a55f9-1ebb-4deb-8cf2-146e3e938deb)

Custom terrain source
![2023-08-16_13-16](https://github.com/mapbox/mapbox-gl-js/assets/117278/d1cab11c-3f79-486e-9734-2f1c20b8c9ce)

### Expected Behavior

Expected that the tree models are anchored to the custom terrain surface.

### Actual Behavior

Tree models are floating above/below the custom terrain surface and not anchored to it.

**Comment by astojilj** [comment]
@andrewharvey Thanks for reporting and trying out the model layer with the terrain. Is the case here that the terrain source gets changed in run time?

If so, this could be the reason and potential workaround until we fix this:

https://github.com/mapbox/mapbox-gl-js/blob/068a7f32954b3cb3d0754ec0e263b816a9eb3fd1/3d-style/render/draw_model.js#L416-L419

If the tile IDs are the same and the exaggeration is the same, we don't update the elevation for trees. Maybe, you could try with an exaggeration 1.001 for one of the terrain sources to trigger the update. Anyway, we'll work on it.

**Comment by andrewharvey** [comment]
@astojilj I tried applying a slightly different exaggeration but it didn't seem to solve the issue.

**Comment by andrewharvey** [comment]
Just a note to say I'm still seeing the issue in beta2

**Comment by astojilj** [comment]
> Just a note to say I'm still seeing the issue in beta2

Thanks. It is under work but it didn't make it for Beta 2.

**Comment by alexey-romanov** [comment]
@andrewharvey hi, could you please provide code/link that reproes the issue?

**Comment by astojilj** [comment]
This should be fixed now. @andrewharvey, please reopen if it happens again. Thanks
