### ISSUE TITLE
Raster tiles not rendered on iPhone

### ISSUE THREAD

**Issue by benstadin** [mapbox/mapbox-gl-js#1285]
Raster tiles aren't rendered correctly on the iPhone. 

See image below (screenshot of https://www.mapbox.com/mapbox-gl-js/example/map-tiles):

![image](https://cloud.githubusercontent.com/assets/98601/11694410/dc4f8240-9e5e-11e5-929c-6f0156b903a2.png)

**Comment by mourner** [comment]
This is probably the same as https://github.com/mapbox/mapbox-gl-js/issues/1818, could you check if #1852 really fixed it? We'll reopen if not.
