### ISSUE TITLE
Unable to load local sprites

### ISSUE THREAD

**Issue by wmonecke** [mapbox/mapbox-gl-js#12866]
Hey!

I am trying load sprites that I have locally in my project but this is becoming something quite painful.

There is inconsistent / little info on how to do this.

I have the following folder structure: 

```bash
/assets
    |_
       street-style.json
       /sprite
           |_
              sprite.json
              sprite.png
```

How do I correctly reference the sprites correctly from my `street-style.json`?

```json
     "sprite": "./sprite", // relative does not work
     "sprite": "/src/assets/sprite", // absolute does not work
```

Please any guidance would be greatly appreciated!

**Comment by stepankuzmin** [comment]
Hi @wmonecke,

The sprite URL should be an absolute URI, i.e., it should include the host:

```js
const map = new mapboxgl.Map({
    container: 'map',
    zoom: 2,
    center: [0, 0],
    style: {
        version: 8,
        sources: {},
        layers: [],
        sprite: 'http://localhost:3000/sprite'
    },
});
```

For the example above, the map will request the following URLs:
```
http://localhost:3000/sprite.json
http://localhost:3000/sprite.png
```

**Comment by wmonecke** [comment]
@stepankuzmin this will work locally but probably not when deployed in production right?

**Comment by stepankuzmin** [comment]
Correct, you should modify it to the production URLs when deploying it to the production environment.

**Comment by wmonecke** [comment]
@stepankuzmin this makes sense and our local fonts are working.

However, we are seeing a lot of Errors in the console for some reason:

```bash
Error {message: 'Unimplemented type: 4'}
```

<img width="346" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/24256469/9ad4a263-34ed-47d0-ab03-89203cdf2a09">

any ideas why that might be?

**Comment by stepankuzmin** [comment]
@wmonecke It's easier to say with the reproducible example. As far as I recall, the `Unimplemented type` error might be thrown by the https://github.com/mapbox/pbf package. I assume you are serving your tiles, so this might be the direction to look into.
