### ISSUE TITLE
[Mapbox GL 3] Use of "text-field" requires a style "glyphs" property

### ISSUE THREAD

**Issue by matbmapspeople** [mapbox/mapbox-gl-js#12865]
**mapbox-gl-js version**: v3.0.0-beta.1

**browser**: Chrome

### Steps to Trigger Behavior

Run new **mapbox-gl-3** without predefine style property and use '"text-field" inside map.addLayer -> 'layout'.

While reading Migration Guide:

-  _The Mapbox Standard Style is now enabled by default when no style option is provided to the Map constructor._

While using style option  (style: 'mapbox://styles/mapbox/streets-v11') in my construction, I can use ''text-field'' property inside layout. The problem appears when I want to use the latest Mapbox Standard Style. While removing style option in my project, I encountered unexpected console error shown below. I tried to use different approaches but the issue still exists. Is it something that I missed?

### Link to Demonstration

https://codepen.io/Mateusz-Tadeusz-Banaszak/pen/bGOdWdw
(Try to open console for codepen)

### Expected Behavior
No error in the console.

### Actual Behavior
![Screenshot 2023-08-23 at 12 30 29](https://github.com/mapbox/mapbox-gl-js/assets/56337591/96594f5f-10e1-4291-a5ee-7ad5d20b8223)

**Comment by stepankuzmin** [comment]
Hi @matbmapspeople,

This is a known issue and will be fixed in the upcoming beta release.
