### ISSUE TITLE
3.0.0-beta.1: Map.addLayer causes error 'Cannot set properties of undefined'

### ISSUE THREAD

**Issue by creatoff** [mapbox/mapbox-gl-js#12867]
I transitioned to version 3.0.0-beta.1, and the method Map.addLayer consistently encounters failures when dealing with custom layers, as evidenced by the subsequent stack trace.

**mapbox-gl-js version**: 3.0.0-beta.1

**browser**: Chrome 116 (Windows)

### Steps to Trigger Behavior

 1. add source with Map.addSource
 2. then add custom layer with Map.addLayer

### Link to Demonstration

https://jsfiddle.net/creatoff/280sf3wt/

### Expected Behavior

No errors in console

### Actual Behavior

```
Uncaught TypeError: Cannot set properties of undefined (setting 'wprl-draw-polygon')
    at StyleLayerIndex.update (6451c036-2d70-4612-8cd2-effee9185823:90698:48)
    at Worker.updateLayers (6451c036-2d70-4612-8cd2-effee9185823:93092:49)
    at Actor.processTask (6451c036-2d70-4612-8cd2-effee9185823:54746:39)
    at 6451c036-2d70-4612-8cd2-effee9185823:54706:74
    at Scheduler.add (6451c036-2d70-4612-8cd2-effee9185823:54511:17)
    at Actor.receive (6451c036-2d70-4612-8cd2-effee9185823:54706:59)
```

**Comment by stepankuzmin** [comment]
Hi @creatoff,

I see you are using the `styledata` event handler to add the source and the layer. What is your use case for using that event instead of `style.load`?

**Comment by creatoff** [comment]
Hi, @stepankuzmin

It helps! `styledata` was used most likely due to legacy code.
