### ISSUE TITLE
Can lines features be rendered with two composite lines style?

### ISSUE THREAD

**Issue by gisfinder** [mapbox/mapbox-gl-js#12862]
For clicking on line featues , it is difficult to click on the exact line's place. So expect normal line style overlapped with thick and transparent  style. Then it will be easy to click on it.
But not see any example for rendering the line with two composite line style.

**mapbox-gl-js version**:

**Comment by mourner** [comment]
You can do this by creating two line layers on top of each other, with one having opacity: 0, for example. GL JS doesn't have any built-in "composite lines" functionality.
