### ISSUE TITLE
Clusters using a symbol layer spawn to late 

### ISSUE THREAD

**Issue by joostwmd** [mapbox/mapbox-gl-js#12878]
**mapbox-gl-js version**:

**browser**:

### Steps to Trigger Behavior

 1. I am loading GeoJson on the map and adding two layers: one for the users and one for clusters. The clusters uses the symbol layer. Those layers spawn later compared to a circle layer, which results in a bad user experience. I cant figure out why, as the images are already loaded on the map. Here is my code : 
 
 
 `
               map.addSource('users', {
			type: 'geojson',
			data: usersGeoJson,
			cluster: true,
			clusterMinPoints: 1,
			//clusterMaxZoom: 10, // Max zoom to cluster points on
			clusterRadius: 30 // Radius of each cluster when clustering points (defaults to 50)
		});

		map.addLayer({
			id: 'user_clusters',
			type: 'symbol',
			source: 'users',
			filter: ['has', 'point_count'],
			//maxzoom: 11.5,
			layout: {
				'icon-image': ['concat', 'cluster', ['get', 'point_count']],
				'icon-size': ['interpolate', ['linear'], ['zoom'], 0, 0.25, 15, 0.8]
			}
		});

		map.addLayer({
			id: 'user_clusters_testCircle_layer',
			type: 'circle',
			source: 'users',
			filter: ['has', 'point_count'],
			paint: {
				// Use step expressions (https://docs.mapbox.com/style-spec/reference/expressions/#step)
				// with three steps to implement three types of circles:
				//   * Blue, 20px circles when point count is less than 100
				//   * Yellow, 30px circles when point count is between 100 and 750
				//   * Pink, 40px circles when point count is greater than or equal to 750
				'circle-color': [
					'step',
					['get', 'point_count'],
					colors[Math.floor(Math.random() * 5)],
					100,
					colors[Math.floor(Math.random() * 5)],
					750,
					colors[Math.floor(Math.random() * 5)]
				],
				'circle-radius': ['step', ['get', 'point_count'], 20, 100, 30, 750, 40]
			}
		});

		map.addLayer({
			id: 'user_point',
			type: 'symbol',
			source: 'users',
			filter: ['!', ['has', 'point_count']],

			layout: {
				'icon-image': ['concat', 'user', ['get', 'spotifyImage']],
				//'icon-image': ['get', 'spotifyImage'],
				'icon-size': ['interpolate', ['linear'], ['zoom'], 0, 0.1, 15, 0.42],
				'icon-allow-overlap': true
			}
		});`  

2. important to note is that i am using the styleimage missing function to lazy load all the user images and cluster images. This is the Code that does this
`
map.on('styleimagemissing', async function (missingImage) {
			if (missingImage.id.includes('user')) {
				console.log(missingImage.id);
				loadUserImage(missingImage.id.replace('user', '')).then((generatedImageData) => {
					try {
						//@ts-ignore
						map.addImage(missingImage.id, generatedImageData);
					} catch (error) {
						console.log(error);
					}
				});
			} else if (missingImage.id.includes('cluster')) {
				loadClusterImg(missingImage.id.replace('cluster', '')).then((generatedImageData) => {
					try {
						//@ts-ignore
						map.addImage(missingImage.id, generatedImageData);
					} catch (error) {
						console.log(error);
					}
				});
			}
		});
`
 5.

### Expected Behavior
The circle layer spawns a new cluster in as soon as a bigger cluster was splittet. 
### Actual Behavior
The symbol layer clusters spawns in later.

**Comment by stepankuzmin** [comment]
Hi @joostwmd,

Thank you for opening this ticket. Please provide a minimal, complete, verifiable demonstration of the issue to help the maintainers and community understand and address the problem accurately. We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.
