### ISSUE TITLE
[Mapbox GL 3] Data expression does not work for 'fill-extrusion-flood-light-color'

### ISSUE THREAD

**Issue by matbmapspeople** [mapbox/mapbox-gl-js#12874]
**Problem:**
For all the features in my project I applied this layer:

``` 
map.addLayer({
                    'filter': ['any',
                        ['==', 'featureClass', FeatureClass.ROOM_EXTRUSION],
                    ],
                    'id': MI_ROOMS_LAYER,
                    'type': 'fill-extrusion',
                    'source': MI_GEOJSON_SOURCE,
                    'paint': {
                        'fill-extrusion-color': ['get', 'fillColor'],
                        'fill-extrusion-opacity': 1,
                        'fill-extrusion-height': ['get', 'height'],
                        'fill-extrusion-ambient-occlusion-ground-attenuation': 1,
                        'fill-extrusion-flood-light-color': '#FFFFFF',
                        'fill-extrusion-flood-light-ground-radius': 10,
                        'fill-extrusion-flood-light-intensity': 0.3,
                        'fill-extrusion-flood-light-ground-attenuation': 1,
                        'fill-extrusion-ambient-occlusion-intensity': 0
                    }
                }); 
```

Additionally, I have a hold of above which feature my mouse cursor is. I would like to use 'case' (data expression) especially for 
`'fill-extrusion-flood-light-color': '#FFFFFF' `, so the extruded feature that mouse is over, would get another flood light colour.
By trying to use 'case' and 'feature-state' I am not able to achieve my goal. 

**Error:**
I am getting 'data expression is not supported for `'fill-extrusion-flood-light-color'`' console error.

**Question:**
Is there a way around it that I have missed? Is it possible to make 'case' and 'feature-state' possible for the new attributes that Mapbox GL 3 (beta) provided?

**Comment by stepankuzmin** [comment]
Hi @matbmapspeople,

Thanks for using the new styling APIs. Unfortunately, the `fill-extrusion-flood-light-color` property is a data-constant type, and we don't plan to support the data expressions for it now. However, we appreciate your feedback and will consider adding it in the future.
