### ISSUE TITLE
[Mapbox GL JS v3] Model Layer and addModel(): no model shows up, no errors

### ISSUE THREAD

**Issue by ammapspeople** [mapbox/mapbox-gl-js#12873]
Using a combination of `addModel()` and a layer of type "model", my model doesn't show up on the map.
I have taken inspiration from https://github.com/mapbox/mapbox-gl-js/issues/12847, specifically https://github.com/mapbox/mapbox-gl-js/blob/068a7f32954b3cb3d0754ec0e263b816a9eb3fd1/src/ui/map.js#L2355-L2383

**mapbox-gl-js version**: 3.0.0-beta.1

**browser**: Firefox 116.0.3, Chrome 116.0.5845.110, Safari 16.1

### Steps to Trigger Behaviour

1. Add a GeoJSON source.
2. Use `addModel` to load a 3D model so it can be used by the map engine.
3. Add a layer of type `model` using the GeoJSON source and the added model as the `model-id` layout property.

### Link to Demonstration

https://jsbin.com/yedahegivo/edit?html,output

### Expected Behavior

Three instances of the added model would show up on the map, corresponding to the number of features in the source.

### Actual Behavior

I see that a network request is made to load the model.
No model is showing up on the map at the coordinates from the features in the source.

The model I use works fine with the "old" Three.js approach mentioned at https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/

**Comment by jtorresfabra** [comment]
Hi @ammapspeople, 

Thanks for filling an issue. The bug has been identified and fixed for the next release (the scope was missing for manually added layers). 

In the meantime you can use a workaround/hack if this is blocking you. 
I modified your example to add a void scope to the model layer (also scaled a bit the models so they stand out). 

https://jsbin.com/xogusebaze/edit?html,output

Thanks!
