### ISSUE TITLE
ScaleControl unit space consistency (nautical-mile)

### ISSUE THREAD

**Issue by chboing** [mapbox/mapbox-gl-js#12876]
I instanciated a Map, created 2 ScaleControl one `nautical` and one `metric`

The result is this :
![image](https://github.com/mapbox/mapbox-gl-js/assets/2633332/36596740-6fc5-488b-a627-81e3358b0b19)

There is a space in front of the `nm` only, 
This is coming from https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/control/scale_control.js where there is a special case for `nautical-mile` setting in the method `_setScale`
I like this space, and I would love to have spaces between numbers and unit consistently ! 
Having the choice if "space or not" would be even better.

Cheers

**Comment by mourner** [comment]
This was recently fixed in #12644, and the fix included in v2.15. Can you check to make sure you're using the latest stable version?

**Comment by chboing** [comment]
oups, sorry my bad
