### ISSUE TITLE
How do I get Satellite style to show labels?

### ISSUE THREAD

**Issue by BdVade** [mapbox/mapbox-gl-js#12871]
I'm using the Satellite Style on my project. In the sample, it shows the labels but once I used it It just shows the maps. 
Related Packages: "mapbox-gl": "2.4.1", "react-mapbox-gl": "4.8.6", "react-mapbox-gl-draw": "2.0.4",

**Comment by stepankuzmin** [comment]
Hi @BdVade,

You can consider using the Mapbox Satellite Streets style. You can see the [list of available styles here](https://docs.mapbox.com/api/maps/styles/).

```
mapbox://styles/mapbox/satellite-streets-v12
```

![Screenshot 2023-08-30 at 12 45 20](https://github.com/mapbox/mapbox-gl-js/assets/533564/2ede0d85-4d68-40bc-b2e3-7af2d3839bb2)

Please note, that for future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
