### ISSUE TITLE
Symbols appear with text, but their background sprites flicker

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1288]
Most conspicuous during zooming and panning.

![screen shot 2015-06-16 at 9 14 14 pm](https://cloud.githubusercontent.com/assets/4551508/8199560/ae157f1e-146c-11e5-8686-e07d69c3ebbd.png)

can be found at https://www.mapbox.com/bites/00151/

cc/ @ansis

**Comment by benstadin** [comment]
This looks like an OpenGL z-ordering and / or floating point precision issue. This can be hacked around by fiddling with different z values, but the issue will always come up again. To fix these nasty things in the long run, it probably requires to rethink about data hierarchies and parent-child relationships (e.g. what will happen also in cases when you have extruded data, and add a layer with icons and icons should be always on top of them also in perspective view). See also my comment here: https://github.com/mapbox/mapbox-gl-js/issues/292#issuecomment-112599554

**Comment by ansis** [comment]
It looks like this has been fixed. It isn't reproducible with emerald-v8 and master.
