### ISSUE TITLE
Mapbox geocoder [map.addControl(geocoder);] distorts in WordPress

### ISSUE THREAD

**Issue by NickWavve** [mapbox/mapbox-gl-js#12895]
I have added the Mapbox geocoder to my web map in the top-left position and made it collapsible.
![image](https://github.com/mapbox/mapbox-gl-js/assets/120218025/eae6cdb4-78e6-4e8a-a1b6-9213bbb066a2)

As raw HTML it looks and works as expected.
![image](https://github.com/mapbox/mapbox-gl-js/assets/120218025/be7b09de-0676-44bb-9f0f-58489c18f1d3)

However, once the code is copied and added into WordPress as a code block it completely distorts.
![image](https://github.com/mapbox/mapbox-gl-js/assets/120218025/54bb82bc-231c-4687-bfd5-25790ea36a52)

Can't seem to figure out what causes this or how to fix it. Any thoughts?

Here is a copy of the current code:
[GeocoderIssue.txt](https://github.com/mapbox/mapbox-gl-js/files/12660975/GeocoderIssue.txt)

**Comment by stepankuzmin** [comment]
Hi @NickWavve,

Thanks for using Mapbox! Unfortunately, I couldn't reproduce the issue with the example you provided. Could you please re-open this issue in the corresponding [mapbox-gl-geocoder](https://github.com/mapbox/mapbox-gl-geocoder) repo and provide a minimal, complete, verifiable demonstration of the issue to help the maintainers and community understand and address the problem accurately? We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.
