### ISSUE TITLE
how to use seach address in iran?

### ISSUE THREAD

**Issue by EsrafilElahi** [mapbox/mapbox-gl-js#12892]
how to use seach address in iran?
is that possible?
any api? for iran? persian lang?

**Comment by stepankuzmin** [comment]
Hi @EsrafilElahi,

Unfortunately, we do not support address searches in Iran. Here's some more info on the search data types we support by country: https://docs.mapbox.com/help/getting-started/mapbox-data/#data-coverage-and-quality
