### ISSUE TITLE
getStyle() returns empty layers in beta

### ISSUE THREAD

**Issue by elygeo** [mapbox/mapbox-gl-js#12901]
**mapbox-gl-js version**: beta.1, beta.2

**browser**: Chrome, Safari, Firefox

### Steps to Trigger Behavior

<link href="https://api.mapbox.com/mapbox-gl-js/v3.0.0-beta.2/mapbox-gl.css" rel="stylesheet">
<script src="https://api.mapbox.com/mapbox-gl-js/v3.0.0-beta.2/mapbox-gl.js"></script>
<div id="map" style="width: 400px; height: 300px"></div>
<script>
  mapboxgl.accessToken = "YOUR_MAPBOX_ACCESS_TOKEN";
  const map = new mapboxgl.Map({ container: "map" });
  map.on("load", () => {
    console.log(map.getStyle().layers);
  });
</script>

### Expected Behavior

style layers in console

### Actual Behavior

layers are empty

**Comment by mourner** [comment]
This is by design — unlike the old Mapbox Streets, the new default Mapbox Standard style does not expose its internal details to make sure we can update it under the hood without breaking user applications. See https://github.com/mapbox/mapbox-gl-js/blob/main/MIGRATION_GUIDE_v3.md#customizing-standard

**Comment by elygeo** [comment]
Makes sense, thanks. I guess this means map.setLayoutProperty() goes away. It would be very handy to add a language schema to the Standard style and change all text_fields from:
"text-field": ["coalesce", ["get", "name_en"], ["get", "name"]],
to:
"text-field": ["coalesce", ["get", ["config", "lang"], ["get", "name"]],

**Comment by JuanIrache** [comment]
Is there an alternative way of changing the map language dynamically with the Standard style?

**Comment by elygeo** [comment]
Here is a way you can modify the Standard style to configure the language:

https://gist.github.com/elygeo/7e36a29935042679dfa3bd4f1982ecad

**Comment by JuanIrache** [comment]
> Here is a way you can modify the Standard style to configure the language:
> 
> https://gist.github.com/elygeo/7e36a29935042679dfa3bd4f1982ecad

Thanks. That's a great solution. It gets very convoluted in my implementation, but will do for now.
