### ISSUE TITLE
Unfork, clarify headless-gl, update to 0.12

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1290]
We use headless-gl to test mapbox-gl-js.

* The project uses @kkaefer's fork https://github.com/kkaefer/headless-gl
* We also have a mapbox fork https://github.com/mapbox/headless-gl which @jfirebaugh updated more recently. Doesn't look like this is being used anywhere
* The changes in any of these projects should go upstream to https://github.com/stackgl/headless-gl

The substantive change that I want is **node v0.12 support**: v0.12 is what you get via homebrew and via nodejs.org, and it's what I use.Without 0.12 support, I cannot run mapbox-gl-js tests locally.

It looks like @jfirebaugh started on this https://github.com/mapbox/headless-gl/tree/nan but like the other forks, there's no indication of whether it succeeded or failed or ran into any issues.

**Comment by mourner** [comment]
Yeah, I've been nagging about this for quite a while. @jfirebaugh says we stay at 0.10 because it's very hard to upgrade to 0.12 across our stack because of breaking changes in native modules API. But we'll have to that eventually, although maybe not the highest priority at the moment.

Currently I had to do:

```
brew unlink node
brew install homebrew/versions/node010
```

Then I switch between the two occasionally with link/unlink.

**Comment by tmcw** [comment]
> Yeah, I've been nagging about this for quite a while. @jfirebaugh says we stay at 0.10 because it's very hard to upgrade to 0.12 across our stack because of breaking changes in native modules API. 

This is not a justification for stalling work on headless-gl: with nan we can support _both_, just like we do with sqlite3 and lots of other modules. mapbox-gl-js isn't just part of our server stack or whatever - it's an open source project and it makes sense to invest in making it developable by the widest set of developers possible. Lacking support for the current stable version of node is a problem.

**Comment by mourner** [comment]
I fully agree. Now we need to find the best person to do it.

**Comment by jfirebaugh** [comment]
To start with, I'm going to refork mapbox/headless-gl from stackgl rather than kkaefer, and then switch `project.json` to use the mapbox fork.

As always, this is a case of much work and few hands, and code contributions, rather than nagging, is the best way to advance the situation.

**Comment by tmcw** [comment]
I'm happy to do this work - if there was a repo that I could easily contribute to and knew was the canon, then I would be working on a PR right now. The nagging is due to the lack of communication and documentation around the many forks of this repo, that make these tasks much less actionable for newcomers like myself.

**Comment by jfirebaugh** [comment]
e2e06191b9bf1ff867b0228f86d87b336888640a

Let's treat https://github.com/mapbox/headless-gl as the canonical repository going forward, or until we have a viable replacement.

**Comment by kkaefer** [comment]
:+1:

**Comment by kkaefer** [comment]
I'm going to delete my repo in ~1 month. Is that a good timeline or will we have code out there that depends on that repo then?

**Comment by jfirebaugh** [comment]
Can you keep it around? One thing that would break is git bisecting the history.

**Comment by mourner** [comment]
@jfirebaugh I don't think we'll ever be bisecting the history to find a test suite issue, since it was broken many times on other occasions.

**Comment by jfirebaugh** [comment]
@mourner I have done it a few times already. Sometimes I had to work around historical breakage but generally it worked well.

**Comment by mourner** [comment]
@kkaefer no need to remove, just update readme and description so it says "DEPRECATED, USE mapbox/headless-gl"

**Comment by jfirebaugh** [comment]
Done in becd235dc171e2375f571740b2033f2cfb69482f.

**Comment by kkaefer** [comment]
Okay, I'll just leave it there, and added a deprecation notice.
