### ISSUE TITLE
Interesting error for Mapbox

### ISSUE THREAD

**Issue by samuellhwarren** [mapbox/mapbox-gl-js#12902]
I am using Mapbox for a custom Power bI visualization...
When I click on an accompanying row in the matrix below, it gives me the following error:

layers.circle.paint.circle-radius[5]:input/output pairs for "interpolate" expressions Must be arranged with input values in strictly ascending order

Any idea what it means?

**Comment by mourner** [comment]
It means that in the expression you're setting for the `circle-radius` property, "input" numbers have to be sorted. As an example, this expression has input values 0, 0.2, 0.4, 0.6, 0.8, 1 are in ascending order, but if you change the order, it will throw an error:

```js
[
  'interpolate', ['linear'], ['heatmap-density'],
  0, 'rgba(33,102,172,0)',
  0.2, 'rgb(103,169,207)',
  0.4, 'rgb(209,229,240)',
  0.6, 'rgb(253,219,199)',
  0.8, 'rgb(239,138,98)',
  1, 'rgb(178,24,43)'
]
```

**Comment by samuellhwarren** [comment]
I’m not using any custom expressions though. I am just using a data field


--
Samuel Warren
***@***.***

2537974789

**Comment by mourner** [comment]
@samuellhwarren then it must be something on the side of your PowerBI environment — you should report the issue there, there's nothing Mapbox can do in this case.

**Comment by aethla** [comment]
I am facing the same issue with my mapbox powerbi visual.

My use case is that I am trying to build a drilldown layer for a mapbox chloropleth map. My first layer is chloropleth but the second layer is supposed to be points. I have a custom tileset with those points in mapbox studio, and have linked the set to the map but once i click on a chloropleth area, this error shows up:
![image](https://github.com/user-attachments/assets/c34b7bb9-a7ad-4fc4-9d5e-23d450fb12f7)

The tileset and powerbi visual I am using are as below:
![image](https://github.com/user-attachments/assets/10f04858-5c72-40cd-bfcc-7a95e7425341)
![image](https://github.com/user-attachments/assets/20ed0b9e-760f-4daa-a9c6-b5a863b693c6)
