### ISSUE TITLE
v3.0.0-beta.3 Loading multiple data sources and layers, layer styles are overridden

### ISSUE THREAD

**Issue by chenhongranl** [mapbox/mapbox-gl-js#12908]
**mapbox-gl-js version**:v3.0.0-beta.3

**browser**:chrome

### Steps to Trigger Behavior

 1.Load road data source and load road layer,Set the road style to gray.
 2.Load the river data source and load the river layer,Set the river style to blue.
 `setRoads() {
            const { url, layerName } = this.tileVectorObj.roads;
            this.mapboxInstance.addSource('roads-factory', {
                type: 'vector',
                tiles: [url],
                minzoom: 3,
                maxzoom: 20,
            });
            this.mapboxInstance.addLayer({
                id: 'road-polygon-fill',
                type: 'fill',
                source: 'roads-factory',
                'source-layer': layerName,
                layout: {},
                paint: {
                    'fill-color': 'hsl(224, 25%, 80%)',
                    'fill-outline-color': 'hsl(221, 20%, 70%)',
                    // 'fill-color': 'rgb(190,197,216)',
                    // 'fill-outline-color': 'rgb(170,179,198)',
                    // 'fill-opacity': 0.5,
                },
            });
        },`
`setRivers() {
            const { url, layerName } = this.tileVectorObj.rivers;
            this.mapboxInstance.addSource('rivers-factory', {
                type: 'vector',
                tiles: [url],
                minzoom: 8,
                maxzoom: 24,
            });
            this.mapboxInstance.addLayer({
                id: 'water',
                type: 'fill',
                source: 'rivers-factory',
                'source-layer': layerName,
                layout: {},
                paint: {
                    'fill-color': [
                        'interpolate',
                        ['linear'],
                        ['zoom'],
                        13,
                        'hsl(200, 100%, 80%)',
                        14,
                        ['interpolate', ['linear'], ['measure-light', 'brightness'], 0, 'hsl(200, 100%, 25%)', 0.02, 'hsl(200, 98%, 80%)'],
                    ],
                    'fill-emissive-strength': ['interpolate', ['linear'], ['zoom'], 5, 0.1, 7, 0],
                },
            });
        },`

### Expected Behavior
Roads appear gray and rivers appear blue

### Actual Behavior
Roads and rivers are gray

**Comment by chenhongranl** [comment]
Styles will also be overwritten when loading multiple fill-extrusion layers

**Comment by stepankuzmin** [comment]
Hi @chenhongranl,

Thank you for opening this ticket. Please provide a minimal, complete, verifiable demonstration of the issue to help the maintainers and community understand and address the problem accurately. We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.

**Comment by chenhongranl** [comment]
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.0.3/vue.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      href="https://api.mapbox.com/mapbox-gl-js/v3.0.0-beta.3/mapbox-gl.css"
      rel="stylesheet"
    />
    <script src="https://api.mapbox.com/mapbox-gl-js/v3.0.0-beta.3/mapbox-gl.js"></script>
    
    <title>Static Template</title>
    <style>
      body {
        margin: 0;
        padding: 0;
      }
      #map {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id="app">
      <div id="map"></div>
    </div>
    <script>
      
      var app = new Vue({
        el: '#app',
        data: {
          mapboxInstance: null,
        },
        mounted(){
          this.init();
        },
        methods: {
          init() {
            mapboxgl.accessToken = 'pk.eyJ1IjoibWVhdGphbSIsImEiOiJjazNwYWNmbGwwMTFnM2RwOHN5dmdkZ3pyIn0.OQ4ZUWt2jteFvqdKZ3DTzA';
            const style = {
                version: 8,
                sprite: 'mapbox://sprites/mapbox/standard-beta/73jrw2iv9yt1v27bf6hw4p4cn',
                glyphs: 'mapbox://fonts/mapbox/{fontstack}/{range}.pbf',
                metadata: {
                    test: {
                        standardDerivatives: true,
                        height: 1024,
                        width: 1024,
                        allowed: 0.0009,
                        operations: [['wait']],
                    },
                },
                sources: {
                    composite: {
                        type: 'vector',
                        maxzoom: 16,
                        tiles: [
                            'https://a.tiles.mapbox.com/v4/mapbox.mapbox-bathymetry-v2,mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2/{z}/{x}/{y}.vector.pbf?access_token=pk.eyJ1IjoibWVhdGphbSIsImEiOiJjazNwYWNmbGwwMTFnM2RwOHN5dmdkZ3pyIn0.OQ4ZUWt2jteFvqdKZ3DTzA',
                            'https://b.tiles.mapbox.com/v4/mapbox.mapbox-bathymetry-v2,mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2/{z}/{x}/{y}.vector.pbf?access_token=pk.eyJ1IjoibWVhdGphbSIsImEiOiJjazNwYWNmbGwwMTFnM2RwOHN5dmdkZ3pyIn0.OQ4ZUWt2jteFvqdKZ3DTzA',
                        ],
                    },
                    '3dbuildings': {
                        type: 'batched-model',
                        maxzoom: 14,
                        tiles: [
                            'https://a.tiles.mapbox.com/3dtiles/v1/mapbox.mapbox-3dbuildings-v1-beta/{z}/{x}/{y}.b3dm?access_token=pk.eyJ1IjoibWVhdGphbSIsImEiOiJjazNwYWNmbGwwMTFnM2RwOHN5dmdkZ3pyIn0.OQ4ZUWt2jteFvqdKZ3DTzA',
                            'https://b.tiles.mapbox.com/3dtiles/v1/mapbox.mapbox-3dbuildings-v1-beta/{z}/{x}/{y}.b3dm?access_token=pk.eyJ1IjoibWVhdGphbSIsImEiOiJjazNwYWNmbGwwMTFnM2RwOHN5dmdkZ3pyIn0.OQ4ZUWt2jteFvqdKZ3DTzA',
                        ],
                    },
                },
                zoom: 13.95,
                center: [2.293506, 48.858436],
                layers: [
                    {
                        id: 'land',
                        type: 'background',
                        layout: {},
                        paint: {
                            'background-color': 'hsl(20, 20%, 95%)',
                            'background-emissive-strength': ['interpolate', ['linear'], ['zoom'], 13, 0.1, 14, 0],
                        },
                    },
                  {
                        id: 'road-pedestrian-polygon-fill',
                        type: 'fill',
                        source: 'composite',
                        'source-layer': 'road',
                        minzoom: 14,
                        filter: [
                            'all',
                            ['match', ['get', 'class'], ['path', 'pedestrian'], true, false],
                            ['match', ['get', 'structure'], ['none', 'ford'], true, false],
                            ['case', ['has', 'layer'], ['>=', ['get', 'layer'], 0], true],
                            ['==', ['geometry-type'], 'Polygon'],
                        ],
                        paint: {
                            'fill-color': '#aaaaaa',
                        },
                    },
                    {
                        id: 'water',
                        type: 'fill',
                        source: 'composite',
                        'source-layer': 'water',
                        layout: {},
                        paint: {
                            'fill-color': [
                                'interpolate',
                                ['linear'],
                                ['zoom'],
                                13,
                                'hsl(200, 100%, 80%)',
                                14,
                                ['interpolate', ['linear'], ['measure-light', 'brightness'], 0, 'hsl(200, 100%, 25%)', 0.02, 'hsl(200, 100%, 80%)'],
                            ],
                            'fill-emissive-strength': ['interpolate', ['linear'], ['zoom'], 5, 0.1, 7, 0],
                        },
                    },
                ],
            };

            this.mapboxInstance = new mapboxgl.Map({
                container: 'map',
                style,
            });
          }
        }
      })

      

      

    </script>
  </body>
</html>
`

**Comment by chenhongranl** [comment]
solved
