### ISSUE TITLE
how to remove Antarctica

### ISSUE THREAD

**Issue by Calvin1121** [mapbox/mapbox-gl-js#12904]
**mapbox-gl-js version**: 1.13.0

### Question
I'm using the mapbox library, and I hope remove Antarctica from the map, only show the main lands.
And I also hope it can be implemented, the picture will not be repeated. As  shown below:
<img width="1108" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/31435496/a56949ee-4941-4bc5-9db2-41c2ebe22b46">
Can anyone help me～ thx 🙏

**Comment by mourner** [comment]
You can't remove a continent with Mapbox GL JS (unless you set up the map with completely custom data in Mapbox Studio, which is a big undertaking). However, what you can do is restrict the map area to certain geographical bounds, like on [this example](https://docs.mapbox.com/mapbox-gl-js/example/restrict-bounds/), which may help with you case. Also, there's a `renderWorldCopies` map option that when set to `false` disable rendering world wrapping on the left and right.
