### ISSUE TITLE
clusters not working on v3 standard map style

### ISSUE THREAD

**Issue by ricardoweiss** [mapbox/mapbox-gl-js#12914]
Running the example in the [docs](https://docs.mapbox.com/mapbox-gl-js/example/cluster/) with the new v3 standard style results in a bug after a certain zoom level, the whole screen get filled with the cluster circle and you cant see nothing anymore

**mapbox-gl-js version**: ^3.0.0-beta.1

**browser**: chrome v117.0.5938.92

### Steps to Trigger Behavior

 1. add new v3 cdn instead of the v2 shown in the docs:
```
<script src='https://api.mapbox.com/mapbox-gl-js/v3.0.0-beta.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v3.0.0-beta.1/mapbox-gl.css' rel='stylesheet' />
```
 2. add the source and the cluster layers
 3. zoom in till it bugs and a circle covers the whole screen

### Link to Demonstration

https://jsbin.com/jexicafako/edit?html,output

### Expected Behavior

The cluster should keep 'unclustering' with more zoom

### Actual Behavior

The cluster circle fills out the whole screen after a certain zoom level and you cant see nothing anymore

**Comment by mourner** [comment]
The circle rendering issue was fixed in subsequent betas — please try beta.3 and let us know if there are any issues.
