### ISSUE TITLE
Additional layers not shown when using raster tiles

### ISSUE THREAD

**Issue by benstadin** [mapbox/mapbox-gl-js#1291]
Additional layers aren't showing when the map source is set to use raster tiles. 

JSFiddle is here:
http://jsfiddle.net/6hjsbnc3/

**Comment by jfirebaugh** [comment]
The style in your JSFiddle does not have "glyphs" or "sprite" properties, which are required for symbol layers. If you add those properties, it works: http://jsfiddle.net/6hjsbnc3/1/

Mapbox GL should be doing better validation of the style though. I've opened a separate ticket for that.
