### ISSUE TITLE
[v3] fill-extrusion emissive strength

### ISSUE THREAD

**Issue by will-r** [mapbox/mapbox-gl-js#12929]
## Motivation

In night mode in the v3 standard style it is not possible to brighten a fill-extrusion layer, so they are generally invisible. 
We very often use fill-extrusion color as a data indicator and that information is lost at night.

## Design Alternatives

The ideal design here would cast a glow, but more pragmatically a brightening property is all we need. It can preclude floodlight and occlusion if necessary.

### Implementation

For consistency I imagine you would want to Implement 

```"fill-extrusion-emissive-strength": DataConstantProperty<number>,```

and then define a `emissionEnabled` in the painter, probably as an alternative to `aoEnabled || floodLightEnabled`. I would be happy to propose a pull request but I imagine there is a lot going on in this area...

**Comment by astojilj** [comment]
Thanks for pointing to this. Could you please try with fill-extrusion-flood-intensity and data driven styling for radius? This is an alternative way to get buildings glowing in dark and it would be good to know if it fits the use case and when it is not applicable.

E.g. dynamic style debug page has buildings higher than 100m glowing

![Screenshot 2023-10-11 at 13 45 43](https://github.com/mapbox/mapbox-gl-js/assets/549216/6b428e0c-a018-49a8-83b8-5877c9d147a6)



```
                "fill-extrusion-flood-light-intensity": [
                    "interpolate",
                    [
                        "linear"
                    ],
                    [
                        "measure-light",
                        "brightness"
                    ],
                    0.0,
                    0.3,
                    0.05,
                    0
                ],
                "fill-extrusion-flood-light-wall-radius": [
                    "case",
                  [">",
                    [
                      "number",
                      [
                        "get",
                        "height"
                      ]
                    ],100],
                  [
                    "/",
                    [
                      "number",
                      [
                        "get",
                        "height"
                      ]
                    ],
                    3.0
                  ],
                  0
                  ],
```


Or, e.g. the render test here has only the walls glowing https://github.com/mapbox/mapbox-gl-js/blob/main/test/integration/render-tests/lighting-3d-mode/fill-extrusion/flood-light/zero-radius/style.json#L57-L58 


![image](https://github.com/mapbox/mapbox-gl-js/assets/549216/75792b1d-8e28-4e08-a1a9-8cd8de138b3e)

**Comment by will-r** [comment]
Thank you, that's very clever. With exaggerated radius values we can give the features a lot of pop. 

However it doesn't quite work for this case because floodlight colour can't be a data expression. We achieve better visibility, but not information delivery.

![day_mode](https://github.com/mapbox/mapbox-gl-js/assets/872859/dbbecf93-839b-451f-bae7-2260bc3765c2)
![night_mode_white_flood](https://github.com/mapbox/mapbox-gl-js/assets/872859/507e8b3a-bcb5-4d18-af50-93085a632cad)
![night_mode_green_flood](https://github.com/mapbox/mapbox-gl-js/assets/872859/4562c3b6-54c7-44b8-891d-75b79c63403a)

**Comment by astojilj** [comment]
@will-r 
Thanks for help.
> However it doesn't quite work for this case because floodlight colour can't be a data expression.

How many different colors would you need to use for the use case? Would separate layers & filters with flood light work?

> "fill-extrusion-emissive-strength": DataConstantProperty<number>,

If this is a constant property, and all buildings have the same value, what values would you use? 1, so that the layer is not affected by light, or something between 0..1?

**Comment by will-r** [comment]
The example above has a simple good/bad/maybe colour scheme and could well be implemented as three filtered layers. Other cases have been more detailed but you're right, we are mostly talking about quite simple signals.

> If this is a constant property, and all buildings have the same value

I was probably over-reaching there, but the other *-emissive-strength properties are constant properties, I think in a 0..1 range? I was trying to fit in :)

I think a better way to put this: often our need is to display a data plane that stands out from the world plane. Maybe we only need a way for a layer to opt out of the global lighting scheme?

**Comment by mourner** [comment]
This will be a part of v3.1.0 — please check out the beta version! https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.1.0-beta.1
