### ISSUE TITLE
Cannot read properties of undefined (reading 'getSource')

### ISSUE THREAD

**Issue by N3iV** [mapbox/mapbox-gl-js#12923]
**mapbox-gl-js version**: 2.15.0

**browser**: chrome, edge

### Steps to Trigger Behavior

 1.
 2.
 3.

### Link to Demonstration

<img width="606" alt="Screenshot 2023-10-06 at 11 11 48" src="https://github.com/mapbox/mapbox-gl-js/assets/80262438/040b6a7e-2979-44b4-937d-400a466fbdf5">

<img width="871" alt="Screenshot 2023-10-06 at 11 12 10" src="https://github.com/mapbox/mapbox-gl-js/assets/80262438/d90d51d3-cd71-4c22-9590-36a251dfc3f5">

https://jsbin.com/

### Expected Behavior
Not throw error Cannot read properties of undefined (reading 'getSource')

**Comment by N3iV** [comment]
[@ncnthien](https://github.com/ncnthien)

**Comment by mourner** [comment]
Closing since you haven't filled the required fields for us to be able to diagnose the issue (reproducible live test case, steps to trigger, at least some minimal description).

**Comment by kopyl** [comment]
@mourner check https://github.com/mapbox/mapbox-gl-js/issues/13629
