### ISSUE TITLE
[V3] Changing map's style from standard to classic style throws an error

### ISSUE THREAD

**Issue by andriivarhanov** [mapbox/mapbox-gl-js#12934]
**mapbox-gl-js version**: v3.0.0-beta.1

**browser**: all major browsers

### Steps to Trigger Behavior

 1. Set map's style with `setStyle` to `mapbox://styles/mapbox/satellite-streets-v12` as an example
 2. Change map's style with `setStyle` to `mapbox://styles/mapbox/standard-beta`
 3. Change it back to `mapbox://styles/mapbox/satellite-streets-v12`. See the error

### Link to Demonstration

https://jsfiddle.net/rfnoL4gy/5/

it's based on the example https://docs.mapbox.com/mapbox-gl-js/example/setstyle/ just with `standard-beta` added to the list and updated versions to v3

### Expected Behavior
Switching map's style from standard to a classic is possible just like switching between classic styles

If you know a workaround on what to add besides `setStyle` to change the style I would appreciate your help

**Comment by brncsk** [comment]
@andriivarhanov The latest beta is [v3.0.0-beta.4](https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.0.0-beta.4)  - you may want to upgrade and test again.

**Comment by mourner** [comment]
Yep, this should have been fixed in later betas. Try it and let us know if there are any issues.

**Comment by andriivarhanov** [comment]
it works in v3.0.0-beta.4, thanks
