### ISSUE TITLE
Error: Unimplemented type: 3

### ISSUE THREAD

**Issue by NHQue** [mapbox/mapbox-gl-js#12944]
I am getting an error where I do not kno if and how that may be connected to #1567 or #861.

But this code:

```
const url = `https://api.mapbox.com/v4/mapbox.mapbox-streets-v8/${zoom}/${x}/${y}.mvt?access_token=${mapBoxAccessToken}` const array = await fetch(url)
const pos = await array.arrayBuffer().then((buf) => new Protobuf(buf))
const vectorTile = new VectorTile(pos)
```

Gives me an error saying **Unimplemented type: 3**

<img width="287" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/83555821/c859958a-e663-498f-856d-6c29900dd06e">

This just occurs for some tiles, e. g. for this one 
`const tile = { x: 19722, y: 39791, zoom: 16 }`

What I already did was to uncompress the vector tile data response with pako.

**mapbox-gl-js version**: 2.13.0,
**@mapbox/vector-tile**: 1.3.1,

**browser**: Chrome

Thanks for any help!

**Comment by mourner** [comment]
You should look at the response header before attempting to parse it. It might have been a 404 or something similar.

**Comment by NHQue** [comment]
@mourner 
Thank you!
What does it mean when fetching a tile responds with a 404 error?
No street data?

**Comment by mourner** [comment]
Yes, usually no data (the area is empty).

**Comment by NHQue** [comment]
Alright, thanks for helping out!
