### ISSUE TITLE
Use prefix module for vendor prefixes

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1294]
We [can drop this prefix selection code](https://github.com/mapbox/mapbox-gl-js/blob/e523db31c1a5d3355a5d97d6bbada2cd64b6711a/js/util/browser/dom.js#L12-L20) by using the prefix module https://www.npmjs.com/package/prefix

**Comment by mourner** [comment]
I'm not in favour of replacing a dead simple 5-line function with a 70-line module.

**Comment by tmcw** [comment]
The existing prefix creation doesn't work for opera, does it?

**Comment by mourner** [comment]
It does, since Opera uses Blink browser engine now, and we don't care about pre-Blink Opera.

**Comment by tmcw** [comment]
okay
