### ISSUE TITLE
线段在小比例尺下显示为虚线问题

### ISSUE THREAD

**Issue by szygiser** [mapbox/mapbox-gl-js#12949]
![image](https://github.com/mapbox/mapbox-gl-js/assets/15412933/058221f6-feb8-4664-9e27-dfa209c5b2a1)

**Comment by stepankuzmin** [comment]
Hi @szygiser,

Thank you for opening this ticket. Please provide a minimal, complete, verifiable demonstration of the issue to help the maintainers and community understand and address the problem accurately. We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.

**Comment by szygiser** [comment]
数据格式和咱们官网demo数据格式应该都是一样的，我也测试了从给你的数据中截取了一部分数据测试是正常的。换这个大数据量好像就不行了。
小数据量和大数据量的template都发您了




zy.S
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mapbox/mapbox-gl-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 晚上8:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mapbox/mapbox-gl-js] 线段在小比例尺下显示为虚线问题 (Issue #12949)





 
Hi @szygiser,
 
Thank you for opening this ticket. Please provide a minimal, complete, verifiable demonstration of the issue to help the maintainers and community understand and address the problem accurately. We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.

**Comment by szygiser** [comment]
提供的是测试html，可独立运行。


矢量切片是基于GeoServer发布的。GeoServer版本是2.22.3


浏览器版本是Chrome，版本 119.0.6045.160（正式版本） （64 位）


操作系统版本是window10，线上环境是Linux


zy.S
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mapbox/mapbox-gl-js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 晚上8:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mapbox/mapbox-gl-js] 线段在小比例尺下显示为虚线问题 (Issue #12949)





 
Hi @szygiser,
 
Thank you for opening this ticket. Please provide a minimal, complete, verifiable demonstration of the issue to help the maintainers and community understand and address the problem accurately. We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.

**Comment by stepankuzmin** [comment]
Unfortunately, it's unclear what is the issue and how to reproduce it, so I'm closing this ticket. If you still can reproduce the issue, please provide a minimal, complete, verifiable demonstration of it to help the maintainers and community understand and address the problem accurately. We recommend using https://jsbin.com/.
