### ISSUE TITLE
new mapboxgl.Popup remove() ： Dom element reference not removed

### ISSUE THREAD

**Issue by LarryZhu-dev** [mapbox/mapbox-gl-js#12954]
**mapbox-gl-js version**: 2.15.0

**browser**: chrome 120.0.6090.0 dev

### Steps to Trigger Behavior

 1. const popup = new mapboxgl.Popup();
 2. popup.remove()

### Expected Behavior

Remove references to dom nodes and free up memory

### Actual Behavior
![image](https://github.com/mapbox/mapbox-gl-js/assets/40397402/8e54a17e-1b67-47da-a5fb-595b8bbefaa0)

After executing the remove() method, when printing the popup, it can be seen that the dom node is still referenced, and it seems that re addTo(map) will repeatedly create a new string within setHTML(), causing the dom node to only increase without decreasing

![image](https://github.com/mapbox/mapbox-gl-js/assets/40397402/5dcf5ba0-1d0b-4434-bbed-6a158e4c51e1)

After repeatedly triggering pop and removing it：

![image](https://github.com/mapbox/mapbox-gl-js/assets/40397402/b2c2be42-6a85-4831-8f84-9a5a17eb3bd3)

**Comment by LarryZhu-dev** [comment]
I tried again and found that I used Vue's render function to mount new elements to the pop element, which caused this problem. Remove can only remove dom nodes within the setHTML range

**Comment by mourner** [comment]
@LarryZhu-dev so does this look like an issue on the Vue app side, not something GL JS can address?

**Comment by LarryZhu-dev** [comment]
@mourner I don't think so. The remove method should not only check the element string passed in by setHTML, but should also check all the child elements mounted under the element for better flexibility. Otherwise, it will be difficult for developers to confirm what caused the remove () function to not remove the correct dom

**Comment by wilburfs** [comment]
把dom元素移除后，再次rende(vnode，div)，发现无法挂载了！！请解释一下，谢谢！

**Comment by wilburfs** [comment]
设置一个函数， 绑定到按钮上：
import testTem from 'XXXXXXXXX'
renderDiv(){
  const testDiv=document.querySelector('#testDiv')
            testDiv != null && testDiv.remove()
            render(h(testTem),document.body)
}
发现第一次挂载成功，清除后，第二次就无法挂载了！！请问你和你这个问题是否类似？

**Comment by LarryZhu-dev** [comment]
@wilburfs 不一样，不清楚你这个是怎么回事
