### ISSUE TITLE
[Accessibility] The map feedback link has a wrong `aria-label` attribute

### ISSUE THREAD

**Issue by life777** [mapbox/mapbox-gl-js#12955]
Hi Team,

Version: v3.0.0-beta.5

I've scanned a few pages with mapbox-gl-js with the AXE tool and ran into an accessibility issue with the latest version. It's marked as serious, but visible only if you turn on an experimental feature.

Issue name: Elements must have their visible text as part of their accessible name
More informations about this types of issues: https://dequeuniversity.com/rules/axe/4.8/label-content-name-mismatch 

Fix for this issue is quite simple: either the link shouldn't have an `aria-label` attribute because the text inside the link is self explanatory or the text in `aria-label` attribute should start with `Improve this map`. I guess the first option is easier and better.

Element with the issue:
```html
<a class="mapbox-improve-map" href="..." target="_blank" aria-label="Map feedback" rel="noopener nofollow">
    Improve this map
</a>
```

![Screenshot from 2023-11-03 21-56-04](https://github.com/mapbox/mapbox-gl-js/assets/891497/d97363d4-3698-450b-86fe-7898d4a2f580)

**Comment by samthomson** [comment]
This causes an accessibility issue in googles lighthouse tool. Is there a way to add a label as an optional property? Or remove this link altogether?

**Comment by maggiewachs** [comment]
@samthomson can you provide more detail? Link elements really shouldn't have `aria-label` attributes (except in rare cases), so it's unclear why Lighthouse would be flagging this.

**Comment by samthomson** [comment]
I don't know why they flag it, but I wanted to have as best a score as possible to improve overall UX and any SEO rankings. 
In the end I found I could add `attributionControl: false` to the config object when instantiating the mapbox which solved the problem.
