### ISSUE TITLE
Please add a method to check if the map is idle

### ISSUE THREAD

**Issue by Etheryte** [mapbox/mapbox-gl-js#12964]
## Motivation

I would like to create a sturdy mechanism to enqueue different async actions on the map without them conflicting with one another. Currently, if you want to know when the map idles you can listen to the `idle` event on the map with either `map.on()` or `map.once()`.

These listeners however have the shortcoming that they do not fire if you attach them to a map that's already idle. There is also no method to check if a map is already idle, hence the request: please add a method to check if the map is idle.

## Design

The easiest API from the developer perspective would be a method that returns a boolean value indicating whether the map is idle.

```tsx
const isIdle: boolean = map.isIdle();
```

This would make programmatically controlling the map a breeze:

```tsx
const mapIdle = async () => {
  if (map.isIdle()) {
    return;
  }
  return new Promise((resolve) => {
    map.once('idle', () => resolve());
  });
};

const mapDemo = async () => {
  await mapIdle();
  map.flyTo(...);
  await mapIdle();
  // Etc
}
```

An alternative possibility would be to add a new event similar to `idle`, but which also fires on the leading edge when starting listening in case the map is already idle. This, however, I think is a suboptimal approach.

## Workarounds

Currently it is somewhat possible to work around this issue by checking for a few key map states, this however does not cover every edge case and is hence not quite a viable solution.

```tsx
const isIdleBuggy: boolean = !map.isMoving() && map.loaded();
```

Another possible workaround would be to listen to more or less every event the map emits for interactions and toggle a boolean value based on that. This is fragile and brings unnecessary overhead.

```tsx
let isIdleCostly: boolean = true;
map
  .on('load', () => { isIdleCostly = false })
  .on('movestart', () => { isIdleCostly = false })
  // ...and so on for other events of interest
  .on('idle', () => { isIdleCostly = true });
```

## Summary

There is currently no viable reliable way to check if a map is currently in idle state. None of the existing workarounds cover all the bases, hence I would urge you to consider adding a method to check whether the map is idle.

**Comment by mourner** [comment]
Yeah, I think this is a good idea. In general, it's good to have this kind of pattern (if _state_ return, otherwise wait for it) in other places too — e.g. I thought about maybe introducing `await map.ready()`, which would be equivalent to `await map.once('style.load')` extended to handle case where the event already happened.

By the way, the Promise wrapper is redundant in this case:

```js
// redundant
return new Promise((resolve) => {
  map.once('idle', () => resolve());
});

// equivalent since `once` returns a promise if no callback
return map.once('idle');
```

**Comment by Etheryte** [comment]
Thanks a lot for the tip about `map.once()`, I was not aware of this. That's very handy, thank you.

**Comment by stepankuzmin** [comment]
Hey all,

We've added the [`Map#idle`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map%23idle) method in GL JS v3.6.0.
