### ISSUE TITLE
frag precision qualifiers Injected twice

### ISSUE THREAD

**Issue by sakitam-fdd** [mapbox/mapbox-gl-js#12984]
frag precision qualifiers injected twice when building fragmentSource in the program:
https://github.com/mapbox/mapbox-gl-js/blob/37624d45b7185d5a213b8a5cd094ed95a9eb49d4/src/render/program.js#L126-L128

![image](https://github.com/mapbox/mapbox-gl-js/assets/19517451/5cdafb2e-275a-4b41-a79a-940f9c821a43)

**mapbox-gl-js version**: 2.0+

**browser**:

**Comment by mourner** [comment]
Nicely spotted, thank you! Will be fixed in one of the upcoming releases.

**Comment by mourner** [comment]
This was addressed for v3.0.0.
