### ISSUE TITLE
Reduce network traffic to tile service

### ISSUE THREAD

**Issue by erkanisuf** [mapbox/mapbox-gl-js#12987]
Hello i am looking a way to reduce the API calls form mapbox to my tileservice.

The tile service I am using is martin tile service (open source) .
I have this layer:

>   map.addSource("mysource", {
>             type: "vector",
>             tiles: [SOURCE_URL + "/" + table + "/{z}/{x}/{y}.pbf"],
>             promoteId: "mysource",
>         });
>         map.addLayer({
>             id: "mysource-layer",
>             type: "fill",
>             source: "mysource",
>             "source-layer": table,
>             layout: { visibility: "visible" },
>             "paint": {
>                 "fill-color": getColorExpression(),
>                 "fill-opacity": 0.5,
>             },
>         });

        
The mapbox sends request on every movement which makes too many API requests to the service and it results to timeouts due to heavy data. I want to reduce these API calls. For example on drag stop just to be send. The martin tile service returns .pbf format of data which mapbox can understand and auto transform to readable.

**Comment by stepankuzmin** [comment]
Hi @erkanisuf,

It's hard to say why GL JS re-requests tiles on each map movement without the reproducible use case. But most likely, you'd need to set up a caching before the tile request hits martin. There is an example of how you can set up martin with nginx caching, it'll help you avoid timeouts in most cases.

https://maplibre.org/martin/run-with-nginx.html#caching-tiles

I'm going to close the issue but feel free to provide a reproducible use case to help us debug the issue.
