### ISSUE TITLE
Fix linecap & linejoin on Android 

### ISSUE THREAD

**Issue by danpat** [mapbox/mapbox-gl-js#1298]
Running on an Samsung S6 Active, Android OS version 5.0.2
Built-in browser version 3.0.38.87-0_100601_477074

![screenshot_2015-06-19-10-26-39](https://cloud.githubusercontent.com/assets/1892250/8259064/a4cc7922-166e-11e5-9aec-a7b2605af8fa.png)

Source URL URL: http://danpat.net/whereisdan

Red line should have round linecaps (works OK on desktop browsers) (geojson layer).  Looks like background vector tiles are also affected by rendering problems.

**Comment by lucaswoj** [comment]
Closing as stale
