### ISSUE TITLE
Mapbox aggregation issue in Power BI

### ISSUE THREAD

**Issue by Jackrbigs** [mapbox/mapbox-gl-js#12994]
Apologies if this is posted in the wrong place, the power BI related section was archived in august.

I build dashboards for a non-profit and we use mapbox to show locations of a lot of our data. The newest dashboard we've been working on has been showing the "Aggregation Function" in the tooltips that pop up. Aggregation Function was something that never showed up or existed in the mapbox visual until we started this dashboard and I have no idea how to get rid of it or work around it from a wording standpoint. For an easy example: If we were showing the number of people living in each county, the tool tip would say "Number of people X" and "County X" but now it will say "Sum of Number of People X" or maximum/minimum etc. It doesn't seem to matter what I do I can't get that additional text to go away and obviously it's not ideal. Does anyone have any experience with this or have any ideas as to why this is? Also if I should move this post to a different section let me know. 

thanks,
Jack
![Screenshot 2023-12-01 102159](https://github.com/mapbox/mapbox-gl-js/assets/152637086/dff9f9aa-54a8-46b0-a143-75f674846597)
![Screenshot 2023-12-01 102229](https://github.com/mapbox/mapbox-gl-js/assets/152637086/51075b68-da1c-4927-88fb-949cfb0b56c3)

**Comment by mourner** [comment]
Yeah, this looks like something that was changed on the Power BI app's side, not anything to do with Mapbox GL JS specifically. Not sure whom to contact about it but you'll likely have more luck with Power BI's support.
