### ISSUE TITLE
Standard style "night" darkens defined LineStrings colors significantly

### ISSUE THREAD

**Issue by lancegliser** [mapbox/mapbox-gl-js#12991]
**mapbox-gl-js version**: Mapbox GL JS v3

**browser**: Chrome

### Steps to Trigger Behavior

 1. Load mapbox
 2. Load standard style
 3. Load geojson line source layer
 4. Load line with line-color or line-gradient style targeting source layer
 5. Set config to "night"

### Link to Demonstration

Simplified from https://docs.mapbox.com/mapbox-gl-js/example/set-config-property/ as a starting point.

See: https://jsfiddle.net/1x4f3pLh/1/
Simply comment and uncomment the lines near the end to see what should be a red and blue line go black in "night" mode.

### Expected Behavior

The color I specify is unchanged when setting the night mode. If it must be changed, I do not expect such a dramatic shift.

### Actual Behavior

The line's color is darkened so far I thought it was black.

Day mode:
<img width="545" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/12085479/0cc3303f-4525-413c-ae6f-0dede2f72f3c">

Night mode:
<img width="545" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/12085479/ee07d752-a80f-437b-8b9a-b75de91b376f">

**Comment by stepankuzmin** [comment]
Hi @lancegliser,

Thanks for posting this! This is due to the new 3D Lights system. You'd need to add a new [`line-emissive-strength`](https://docs.mapbox.com/style-spec/reference/layers/#paint-line-line-emissive-strength) paint property to brighten the line. These `*-emissive-strength` properties control the intensity of light emitted on the source features.

```js
'line-emissive-strength': 0.6
```

![Screenshot 2023-12-01 at 11 24 13](https://github.com/mapbox/mapbox-gl-js/assets/533564/98ebeba2-5a02-437f-8f89-85d9fc7541af)

I'm closing the issue, but please let me know if you have any questions.

**Comment by lancegliser** [comment]
Lovely! I'm glad there's a clear solution, forgive my ignorance. 

Perhaps this is just a documentation update need. I came back to MapBox from previous work about a year ago. My introduction was the [blog post](https://www.mapbox.com/blog/standard-core-style) announcing the standard style. I implemented, running through [migration guide](https://docs.mapbox.com/mapbox-gl-js/guides/migrate-to-v3/), but it didn't really click that lighting affected the lines. Not sure the right place to help make that obvious. If I were a brand new developer, coming from scratch I'd not even have read the migration guide. That might make it the wrong spot.

The [line docs](https://docs.mapbox.com/style-spec/reference/layers/#paint-line-line-emissive-strength) probably need updates to specifically call out on `line-color` and `line-gradient`. Maybe something like another element in the italicized docs like "Modified by [`line-emissive-strength](https://docs.mapbox.com/style-spec/reference/layers/#paint-line-line-emissive-strength)".

Possible other places to consider, probably covered by the pure docs addition:
- https://docs.mapbox.com/mapbox-gl-js/example/geojson-line/
- https://docs.mapbox.com/mapbox-gl-js/example/line-gradient/

**Comment by stepankuzmin** [comment]
Hi @lancegliser,

We've updated the `setConfigProperty` example here https://docs.mapbox.com/mapbox-gl-js/example/set-config-property/
