### ISSUE TITLE
mapbox-gl 3.0 pack size increased by ~25%

### ISSUE THREAD

**Issue by asdfjkalsdfla** [mapbox/mapbox-gl-js#12995]
**mapbox-gl-js version**: 3.0

### Expected Behavior
Building with rollup, the mapbox 3.0 bundle size has increased to 1,252.70 kB from 986.59 kB in 2.15. This impacts our render speeds/performance for an already heavy package.

**Comment by mourner** [comment]
I see how frustrating this can be — we did everything we could to keep the increase to an absolute minimum, but there's only so much you can do when adding so many new rendering features and enabling new kinds of 3D maps — they come at a cost to bundle size. Those features add a lot of complexity, and the bundle is relatively small in relation to how much it can do (for comparison, 3D libraries like Cesium & Babylon have 3–4 times bigger bundles). 

While we will continue looking for ways to cut the size, if you don't need the new 3D features and/or the Standard Style, it's perfectly fine to stay on v2.15.
