### ISSUE TITLE
OpenStreetMap attribution missing in the Standard Style

### ISSUE THREAD

**Issue by JamesChevalier** [mapbox/mapbox-gl-js#13002]
**mapbox-gl-js version**: v3.0.0 with the Standard Style in use

### Question

Is the OpenStreetMap attribution missing in the Standard Style on purpose?

When using the Standard Style, the "© Mapbox © OpenStreetMap Improve this map" attribution is no longer displayed. If I toggle the style to `mapbox://styles/mapbox/satellite-streets-v12` it shows the OpenStreetMap attribution & when I toggle back to `mapbox://styles/mapbox/standard` that attribution is removed.

### Links to related documentation

- https://labs.mapbox.com/standard-style
- https://docs.mapbox.com/mapbox-gl-js/api/markers/#attributioncontrol
- https://docs.mapbox.com/mapbox-gl-js/api/map/#map-parameters

**Comment by stepankuzmin** [comment]
v3.0.1 is here

**NPM**:
https://www.npmjs.com/package/mapbox-gl/v/3.0.1

**CDN**:
https://api.mapbox.com/mapbox-gl-js/v3.0.1/mapbox-gl.js
https://api.mapbox.com/mapbox-gl-js/v3.0.1/mapbox-gl.css

**GitHub**:
https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.0.1

**Comment by JamesChevalier** [comment]
🫣I hate to be a pain (and this is low priority), but it looks like the text is duplicated. It displays:
"© Mapbox Improve this map | © Mapbox © OpenStreetMap Improve this map"

<img width="454" alt="Screenshot 2023-12-08 at 10 18 09 AM" src="https://github.com/mapbox/mapbox-gl-js/assets/408939/8fbe6b70-5248-4e27-a1e3-e795c16b3f2c">

**Comment by mourner** [comment]
@JamesChevalier yep, this one is a slightly different issue that happens due to the attribution metadata in the DEM source — we'll try to fix this on the source side so that another GL JS patch won't be necessary.

**Comment by palhal** [comment]
Did this break again in 3.1.0? No attribution here after upgrading from 3.0.1 to 3.1.0. If you fix it again, can you please fix the duplication issue as well?

**Comment by mourner** [comment]
Looks like a recurrence of this bug, investigating...

**Comment by mourner** [comment]
Confirming that the fix was accidentally missed when releasing 3.1.0; we'll release 3.1.2 with the fix, and make sure we never miss it again afterwards — sorry about that. The duplication issue should already be fixed.

**Comment by mourner** [comment]
v3.1.2 now released to address the regression — apologies for the mixup, our bad.

**Comment by palhal** [comment]
No problem. Working like a charm now :) Thanks for the fast response. Sorry I didn't catch it before the 3.1.1 release :| I see that the duplication issue is no longer present on 3.0.1 as well. I'm quite sure I checked not _that_ long ago and it was there.

**Comment by mourner** [comment]
@palhal no worries and thanks for the report, don't know how we missed that! Messed up syncing branches and the fix from 3.0.1 just didn't get to 3.1. As for the duplication, it was fixed on the styles API side, so it's retroactive.
