### ISSUE TITLE
Can not create Marker Cluster Using Tileset

### ISSUE THREAD

**Issue by kumarrajeev23** [mapbox/mapbox-gl-js#13014]
Hi , I am trying to create marker-cluster using tileset but i am unable to do clustering using tileset data.

**Comment by stepankuzmin** [comment]
Hi @kumarrajeev23,

Thank you for using mapbox-gl-js. For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
