### ISSUE TITLE
jest unit tests saying "TextDecoder is not defined" when testing any file that imports mapbox

### ISSUE THREAD

**Issue by pdfabbro** [mapbox/mapbox-gl-js#13027]
any unit test for a file that has "import mapboxgl from "mapbox-gl"" at the top fails with "TextDecoder is not defined"

**mapbox-gl-js version**: ^3.0.1

**browser**: n/a

**Comment by mattdean-digicatapult** [comment]
Possibly caused by https://github.com/jsdom/jsdom/issues/2524?

We hit a simlar issue and https://github.com/jsdom/jsdom/issues/2524#issuecomment-1108991178 solved it for us in a jest setup file:

```js
import * as util from 'util'

// ref: https://jestjs.io/docs/manual-mocks#mocking-methods-which-are-not-implemented-in-jsdom
// ref: https://github.com/jsdom/jsdom/issues/2524
Object.defineProperty(window, 'TextEncoder', {
  writable: true,
  value: util.TextEncoder
})
Object.defineProperty(window, 'TextDecoder', {
  writable: true,
  value: util.TextDecoder
})
```

**Comment by pdfabbro** [comment]
@mattdean-digicatapult beautiful, that did the trick.  Thanks!  This can be closed
