### ISSUE TITLE
Publish 0.8.1 to npm

### ISSUE THREAD

**Issue by vespakoen** [mapbox/mapbox-gl-js#1303]
Hey!

The docs tell me 0.8.1 is available, but npm still gives me 0.8.0.
Can the new version be published?

Thanks!

**Comment by mourner** [comment]
Certainly!
@jfirebaugh hmm NPM says "You do not have permission to publish 'mapbox-gl'.".

**Comment by jfirebaugh** [comment]
@mourner You're an owner now.

**Comment by mourner** [comment]
Cool, published.
