### ISSUE TITLE
V3 upgrade: Custom Layer has a 1 second fade from white after each map move

### ISSUE THREAD

**Issue by jaybo** [mapbox/mapbox-gl-js#13031]
**mapbox-gl-js version**: 3.0.1

**browser**: chrome

### Steps to Trigger Behavior

 1. Upgrade PWA/SPA app from mapbox-gl@2.15.0 to @3.0.1.  No other code changes.
 2. When displaying weather layers, which are implemented as Custom Layers in WebGl, note that a fade in from white, which lasts one second happens on ever map move.  This did not happen in V2.

### Link to Demonstration

Note that WebGl weather layer updates are fluid, but after a map move, there is a fade in from white lasting 1 second.

https://github.com/mapbox/mapbox-gl-js/assets/1607323/9cd4072d-99e3-40d8-915e-4a996be93ede

### Expected Behavior
No fade in from white on map move.  I'm guessing this may have something to do with the new global light feature, but I have no idea how to fix it on my end.

### Actual Behavior
Flashes white.

**Comment by jaybo** [comment]
For comparison, here is the behavior with V2.  No white flashes.


https://github.com/mapbox/mapbox-gl-js/assets/1607323/588fcd7b-655c-4229-be6a-749ef5c8d385

**Comment by astojilj** [comment]
Thanks. Could you please share some more details that could help us reproduce this by providing a minimal, complete, verifiable demonstration or:
- share details about style.
- Is Map.setFog(null) resolving the issue?
- Is terrain enabled?

**Comment by jaybo** [comment]
1. Terrain was not enabled.
2. `map.setFog(null)` **FIXED IT**  Thanks!
