### ISSUE TITLE
Cannot read properties of undefined when calling getLayer

### ISSUE THREAD

**Issue by pdfabbro** [mapbox/mapbox-gl-js#13039]
When the map loads and getLayer is called, this line is erroring out because e is null ```return e.indexOf("us")>=0}(e)||(this.fire(new St(new Error(`IDs can't contain special symbols: "${e}".`)```

This seems to occur in ._isValidId method

![image](https://github.com/mapbox/mapbox-gl-js/assets/19414666/09618466-69a0-4561-8fcc-c2f84e07d449)

**mapbox-gl-js version**:
3.0.1

**browser**:
chrome

**Comment by pdfabbro** [comment]
Update, this was an issue on our side as we were passing an undefined id into getLayer.  However, mapbox should probably also add a check for null/undefined on their side

**Comment by stepankuzmin** [comment]
Hi @pdfabbro,

Good catch, thank you. We'll add an error for such cases.
