### ISSUE TITLE
How to add events to marker's popup

### ISSUE THREAD

**Issue by lympe92** [mapbox/mapbox-gl-js#13032]
**mapbox-gl-js version**:
 "mapbox-gl": "^3.0.1",
### Question
Hello guys,
I need to know how to use events like mouseover,click for the popup, when the popup is opened. I can't find anything about this functionality.
thanks

**Comment by stepankuzmin** [comment]
Hi @lympe92,

You can use the `getElement()` method on the Marker instance. It will return the underlying HTML element, which can be used to listen to DOM events like `click` and `mouseover`.

https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker#getelement

```js
const element = marker.getElement();
```

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
