### ISSUE TITLE
Mapbox 3.0.1 Beta Raster Emissive Strength

### ISSUE THREAD

**Issue by rivindubandara** [mapbox/mapbox-gl-js#13035]
Hi all, 

Just had a question about the new beta and the function that was requested by myself prior 'raster-emissive-strength'. 

I used it as such and am not getting the result that I expected. Am I using the property correctly?
![image](https://github.com/mapbox/mapbox-gl-js/assets/54240628/ae1d9d48-24d1-40e2-a0fa-5bd234fbda18)

Thanks

**Comment by stepankuzmin** [comment]
Hi @rivindubandara,

This looks correct to me. What GL JS version are you using? Could you please provide a minimal demonstration of the issue to address the problem? We recommend using https://jsbin.com/.

**Comment by rivindubandara** [comment]
Hi @stepankuzmin,

I am using latest beta 
![image](https://github.com/mapbox/mapbox-gl-js/assets/54240628/482a6c22-1cf2-4c08-9cd8-ca194207e26d)


This is at raster emissive strength 1.0 
![image](https://github.com/mapbox/mapbox-gl-js/assets/54240628/384c3af8-645d-4e52-a94c-ab08aa2fa807)

This is at raster emissive strength 0.1
![image](https://github.com/mapbox/mapbox-gl-js/assets/54240628/3da6ce05-e590-49a9-ba6c-41b9398bf505)

Clearly, there is no difference
