### ISSUE TITLE
Clear error should be thrown if adding a vector tile source without a `url`

### ISSUE THREAD

**Issue by scottsfarley93** [mapbox/mapbox-gl-js#13043]
**mapbox-gl-js version**: 3.0.1

**browser**: Chrome

### Steps to Trigger Behavior
Adding a vector tile source without a `url` property does not fail. However, once add a layer on top of that source, you get a cryptic error message. This message is hard to debug, because you can create the source, so it feels like the issue is with layer creation rather than the source creation. 

```
mapboxgl.accessToken = '...';
const map = new mapboxgl.Map({
    style: '...,
    container: 'map',
    center: [-122.54813, 37.90501], 
    zoom: 9,
    hash: true, 
});

map.on('load', () => {
                map.addSource('parcels-base', {
                    'type': 'vector',
                    'data': 'mapbox://...', //<-- NOTE: `data`, not `url` 
                })

            map.addLayer({
                    'type': 'fill',
                    'id': 'parcel',
                    'source': 'parcels-base',
                    'source-layer': 'parcellayer',
                    'paint': {'fill-color': 'red'}
                });
});

```

Error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'replace')
    at ku.url (tile_id.js:33:14)
    at Rw.loadTile (vector_tile_source.js:219:85)
    at Ax._loadTile (source_cache.js:155:29)
    at Ax._addTile (source_cache.js:802:18)
    at Ax._updateRetainedTiles (source_cache.js:660:31)
    at Ax.update (source_cache.js:562:29)
    at $A.updateSources (style.js:2531:42)
    at Map._render (map.js:3524:24)
    at map.js:3933:26
```

### Expected Behavior
Validation should be completed to ensure that the `url` is provided when creating a new vector tile source. If the URL is not provided, throw an error with an easy-to-debug error message.

### Actual Behavior
A cryptic error message is provided. 

Thanks!

**Comment by stepankuzmin** [comment]
Hi @scottsfarley93,

Good catch, thank you. We'll add an error for such cases.
