### ISSUE TITLE
WebpackError: TypeError: _layer_events_hoc__WEBPACK_IMPORTED_MODULE_1___defaul  t(...) is not a function

### ISSUE THREAD

**Issue by maghaffar** [mapbox/mapbox-gl-js#13052]
**mapbox-gl-js version**: mapbox-gl 3.1.0 and react-mapbox-gl 5.1.1

**browser**: Chrome

### Actual Behavior
I am using react-mapbox-gl library. It is working on my localhost but when I deploy it to netlify it is showing this error
![Screenshot from 2024-01-24 16-58-25](https://github.com/mapbox/mapbox-gl-js/assets/98881071/ca726f46-45b8-48e4-a62b-32a9873ff07e)

**Comment by stepankuzmin** [comment]
Hi @maghaffar,

Could you please make a small reproducible setup with Mapbox GL JS and Webpack?
