### ISSUE TITLE
Changes in v3.1.0 cause Mapbox to blow up when used with a MapTiler source

### ISSUE THREAD

**Issue by RoystonS** [mapbox/mapbox-gl-js#13066]
**mapbox-gl-js version**: 3.1.2

**browser**: Chrome 120

### Steps to Trigger Behavior

 1. Install Mapbox-gl-js
 2. Configure a MapTiler source
 3. Mapbox blows up with a `Either "url" or "tiles" is required.` error.

### Link to Demonstration

I can't provide a direct link to a complete example because using a MapTiler map requires a MapTiler API key.

The value that we're passing into `style` is `https://api.maptiler.com/maps/streets-v2-dark/style.json?key=<KEY-REDACTED>`.

That produces this source file (with some unnecessary details elided):

```
{
    "version": 8,
    "id": "streets-v2-dark",
    "name": "Streets Dark",
    "sources": {
        "maptiler_planet": {
            "url": "https://api.maptiler.com/tiles/v3/tiles.json?key=<KEY-REDACTED>",
            "type": "vector"
        },
        "maptiler_attribution": {
            "attribution": "<a href=\"https://www.maptiler.com/copyright/\" target=\"_blank\">&copy; MapTiler</a> <a href=\"https://www.openstreetmap.org/copyright\" target=\"_blank\">&copy; OpenStreetMap contributors</a>",
            "type": "vector"
        }
    },
    "layers": [
	  // <DETAIL-ELIDED-HERE>
    ],
    "glyphs": "https://api.maptiler.com/fonts/{fontstack}/{range}.pbf?key=<KEY-REDACTED>",
    "sprite": "https://api.maptiler.com/maps/streets-v2-dark/sprite",
    "bearing": 0,
    "pitch": 0,
    "center": [
        0,
        0
    ],
    "zoom": 1
}
```

The problem appears to be that as of commit ce9883d51b519b07d7b29b4edb1f8de46686dae9, the Mapbox code blows if it sees any source object without a `url` or a `tiles` property.  However, the attribution source above has no `url` property.  Mapbox used to handle this source without any issues.

### Expected Behavior

The MapTiler map is shown as it did with Mapbox 3.0.1 and earlier.

### Actual Behavior

As of Mapbox 3.1.0, the control blows up and the map cannot be used.

**Comment by stepankuzmin** [comment]
Hi @RoystonS,

I see an empty source, `maptiler_attribution`, which only adds the attribution string. I think the attribution property should be a part of the `maptiler_planet` source. Is it an intentional separation made on your side or a part of MapTiler logic?

**Comment by RoystonS** [comment]
Hi @stepankuzmin 
The above JSON is exactly what MapTiler emits when fetching `https://api.maptiler.com/maps/streets-v2-dark/style.json?key=<KEY-REDACTED>` with a valid API key, except that I removed the contents of the `layers` property and I redacted the API keys.

So, yes, it contains two objects in `sources`, one with a `url` property and one with an `attribution` property.

**Comment by RoystonS** [comment]
If you visit the publicly accessible page at https://www.maptiler.com/maps/#style=streets-v2&mode=2d&position=1/48.9/2.3 and take a look at the network traffic, you'll see such a `style.json` file being fetched, which illustrates the above.

(Understandably they have locked down the API key that that page uses to that domain only, so I can't paste you a direct URL to that particular `style.json` file, I'm afraid.)

**Comment by stepankuzmin** [comment]
I see, thanks for the clarification @RoystonS. We'll issue a warning instead of an error for such cases. This will be fixed in the next v3.2.0 release.

**Comment by RoystonS** [comment]
Interesting.  Does this mean you're changing the Mapbox Style Specification so that a `url` or `tiles` valid is now required?
Looking at the spec at the moment it says that both `url` and `tiles` are optional and doesn't indicate that one of the two is _required_.

https://docs.mapbox.com/style-spec/reference/sources/#vector

**Comment by stepankuzmin** [comment]
Yes. If a tiled source doesn't have tiles (`url` or `tiles` property), it makes it redundant. I'll add a note about that to the Style-Spec. Thanks for pointing out 👍
