### ISSUE TITLE
feature-state events (hover) stop working when many 3D models are rendered in a `model` layer

### ISSUE THREAD

**Issue by Jaszkowic** [mapbox/mapbox-gl-js#13068]
**Mapbox-GL-JS Version**: 3.1.2

**Browsers Tested**:
- Chrome (Version 120.0.6099.234)
- Firefox (121.0)

### Steps to Reproduce

1. Clone the repository from  https://github.com/Jaszkowic/feature-state-bug (public repo, minimal example)
2. Create an `.env` file with `REACT_APP_MAPBOX_ACCESS_TOKEN` set properly
3. Run `npm install`
4. Run `npm start`
5. Hover over a rendered tree circle; opacity should change, and the 3D model should scale bigger (works fine in the initial setup)
6. Change the number of rendered trees (`numTrees` variable) in `./src/Map.js` and reload
7. For small numbers (< 50, exact number unclear), everything works fine
8. For larger numbers (e.g., > 100 - reproducible in my case), the hover effect still works on the 2D circles but stops working on most of the 3D models. Strangely, some randomly selected 3D models still work.

### Demonstration Link

Public repo, minimal example: https://github.com/Jaszkowic/feature-state-bug

### Expected Behavior
`feature-state` events like `hover` should work for a large number of rendered 3D features in a layer of type `model`, as documented [here](https://docs.mapbox.com/style-spec/reference/layers/#model):

> [...] `model-scale` Supports [feature-state](https://docs.mapbox.com/style-spec/reference/expressions/#feature-state)

I understand that the `model` layer is in an experimental state. Maybe there is still some limitation here? If yes, could you clarify what the exact limitations are?

### Actual Behavior
`feature-state` events like `hover` cease to work for a large number of rendered 3D features in a layer of type `model`.

Thank you for your help!

**Comment by astojilj** [comment]
Thanks for reporting. This is a bug that we will work on.

**Comment by Jaszkowic** [comment]
HI @astojilj, any updates on this? Is there a rough timeline when work on this could bug could start? Thanks again.

**Comment by milospp** [comment]
@astojilj I tested this in v3.12.0, and unfortunately, feature-state still doesn’t work as expected with model-opacity.

Here’s a minimal example:
Example: https://codepen.io/milospp/pen/MYYPbNL (see line 65)


### Problem:
The following style expression ignores `feature-state` completely and always sets model-opacity to 1, regardless of the state.
```
        paint: {
            'model-opacity': [
                'case',
                ['boolean', ['feature-state', 'hover'], false],
                0.2,
                0.5
            ],
        }
```

However, using `interpolate` with `zoom` does work as expected:
```
        paint: {
            'model-opacity': [
                'interpolate',
                ['linear'],
                ['zoom'],
                16, 0, // At zoom level 16, opacity is 0
                20, 1    // At zoom level 20, opacity is 1
            ],
        }
```

#### Additional Issue:
Trying to use interpolate with`model-emissive-strength` completely breaks 3D rendering — the model doesn’t render at all.
```
        paint: {
            'model-emissive-strength': [
                  'interpolate',
                  ['linear'],
                  ['zoom'],
                  16, 0.1,
                  20, 0.9
              ],
        }
```

Can anyone confirm whether I’m using unsupported expressions here, or if this is a bug in the current version?
