### ISSUE TITLE
Feature request: Fixed-length line-dash gaps

### ISSUE THREAD

**Issue by benstadin** [mapbox/mapbox-gl-js#1307]
Besides one's personal taste, in some situations it's not desired to have dynamic line dash adjustments. For an example I have a small map where I would like to preserve the appearance of neighboring shapes which form some kind of group. 

Maybe the dash width could be defined as a metric value.

**Comment by mourner** [comment]
Can you describe your use case in more detail? I think the use case where this is necessary is extremely uncommon. It'll look bad in pretty much any situation because of the enormous variation of dash length — e.g. 1px gap would become a 1024px 10 zoom levels deeper.

**Comment by benstadin** [comment]
My use case is similar to scrolling and zooming at the same time a map along a road during navigation: Road line gaps should look more or less accurate and reflect their real world appearance.So like road lines they have have a defined gap width, and it's undesired that gaps "double up". 

For me it would be ideal to have control to define line gaps in meters, and set a different line styling (flat line instead of dash) when a certain zoom level is reached. 

Besides personal taste (I dislike the "turbulent" change of railway lines at [1]), I think it may in general be useful for navigation scenarios to control anything distracting the user's eye. 

[1] https://www.mapbox.com/bites/00151/

**Comment by ansis** [comment]
@benstadin this can be done by manually by making the dasharray a function of zoom level and manually setting each zoom level to be double the value of the previous zoom level. It's a bit annoying to do but it should work.

**Comment by benstadin** [comment]
Can you provide an example?

**Comment by ansis** [comment]
```
"paint": {
    "line-color": "#EC8D8D",
    "line-dasharray": {
        "stops": [
            [10, [1, 8, 1]],
            [11, [2, 16, 2]], 
            [12, [4, 32, 4]],
            [13, [8, 64, 8]],
            [14, [16, 128, 16]],
            
        ]
    },
    "line-width": 3 
}
```

The dash is split into two parts so that it is centered around the beginning of the line. At z10 it's a [2, 8] dasharray. I realize that this is fairly awkward to do.

**Comment by ansis** [comment]
I think this is uncommon enough that the approach in https://github.com/mapbox/mapbox-gl-js/issues/1307#issuecomment-115252724 is good enough
