### ISSUE TITLE
Oversimplified GeoJSON

### ISSUE THREAD

**Issue by benstadin** [mapbox/mapbox-gl-js#1309]
It seems the GeoJSON importer oversimplifies sometimes. Or it may be a precision issue (WGS84 single precision floats?). Is it possible to control whether or not an added layer should be simplified?

![too_simple](https://cloud.githubusercontent.com/assets/1433419/8302258/65095434-1995-11e5-8d10-2932e3bac387.png)

The same area from the same file as it looks in QGIS:

![lines_ok](https://cloud.githubusercontent.com/assets/1433419/8302322/d250586c-1995-11e5-9bd7-cc39819b914a.png)

**Comment by mourner** [comment]
Yes, you should be able to control that with `maxzoom` option of `GeoJSONSource` — see https://www.mapbox.com/mapbox-gl-js/api/#geojsonsource (it's 14 by default)

**Comment by mourner** [comment]
@jfirebaugh btw should we bump the default then? That appears often, and bumping to something like 16-18 would have almost no effect on performance.
