### ISSUE TITLE
Does mapbox server block the ip from China for request "events/v2"

### ISSUE THREAD

**Issue by topcnm** [mapbox/mapbox-gl-js#13098]
**mapbox-gl-js version**: 2.6.1

**browser**: Chrome

### Steps to Trigger Behavior

 1. construct a web app with mapbox
 2. run app and inspect the chrome dev-tool
 3. the request `https://events.mapbox.com/events/v2?access_token=xxx` fail for 'net::ERR_CONNECTION_REFUSED'
 4. turn on vpn , the request `https://events.mapbox.com/events/v2?access_token=xxx` successfully
 5. check other app  developped 3 years ago, which also includes mapbox, they have the same issue
 

### Expected Behavior
Run the request normally or disable it

### Actual Behavior
The request `https://events.mapbox.com/events/v2?access_token=xxx`  gives me an error

It seems that mapbox server block the IP from China.
So, if it is possible to disable this request by config somewhere or make it run successfully.

**Comment by stepankuzmin** [comment]
Hi @topcnm,

You'd need to change the [base API URL](https://docs.mapbox.com/mapbox-gl-js/api/properties/#baseapiurl) to point to https://api.mapbox.cn with:

```js
mapboxgl.baseApiUrl = 'https://api.mapbox.cn';
```

Related to https://github.com/mapbox/mapbox-gl-js/issues/6620

**Comment by stepankuzmin** [comment]
Unfortunately, customers from China are ineligible to sign up for Mapbox services at this time for regulatory reasons, and we cannot provide support to users located in China due to these. For more information, please refer to our Legal portal. https://www.mapbox.com/legal/tos
