### ISSUE TITLE
Safari browser does not support WebGL. How to handle this issue?

### ISSUE THREAD

**Issue by tjcchen** [mapbox/mapbox-gl-js#13096]
**error message**: Error: Failed to initialize WebGL.
<img width="974" alt="Screen Shot 2024-02-27 at 10 32 40 AM" src="https://github.com/mapbox/mapbox-gl-js/assets/6133656/24f8b014-7d85-4c81-96d5-226526307200">

**mapbox-gl-js version**: 3.0.1
```
 "mapbox-gl": "^3.0.1",
```

**browser**: Safari - Version 14.1.2 (16611.3.10.1.6)
<img width="293" alt="Screen Shot 2024-02-27 at 10 31 46 AM" src="https://github.com/mapbox/mapbox-gl-js/assets/6133656/1d4d744d-3b20-4465-9e4c-2a97f2a62a9b">

### Steps to Trigger Behavior
Code:
```js
import mapboxgl from "mapbox-gl";

mapboxgl.accessToken = "xxx";

// ...
// initialize the map
const map = new mapboxgl.Map({
  container: mapContainer.current,
  style: "mapbox://styles/mapbox/streets-v11",
  center: [-71.084014, 42.362602],
  zoom: 12,
});
// ...
```

**Comment by mourner** [comment]
To support many of its advanced 3D features, Mapbox GL JS v3 requires WebGL 2.0, which works in Safari v15 and later (with v17.4 being the current version). If you need to support very old Safari versions, you'd have to stay on Mapbox GL JS v2.15 — aside from not supporting the new Mapbox Standard style, it's still very capable.
