### ISSUE TITLE
[Typescript setup] 3D model custom layer not displayed in the mapbox

### ISSUE THREAD

**Issue by MiguelG97** [mapbox/mapbox-gl-js#13094]
**mapbox-gl-js version**:
^3.1.2
**browser**:
chrome
### Steps to Trigger Behavior

 1. checkout repo
 2. npm run dev [using vite]
 3.

### Link to Demonstration
Here is the source code used for the demonstration
https://github.com/MiguelG97/mapbox3dmodel/blob/main/src/main.ts

### Expected Behavior
gltf model should be displayed in the model origin
### Actual Behavior
nothing shows up

**Comment by underoot** [comment]
Why you switched translations for X and Y axises?
https://github.com/MiguelG97/mapbox3dmodel/blob/main/src/main.ts#L137-L138

**Comment by MiguelG97** [comment]
That fixed the issue with my setup! My bad,  I suspect that I made a mistake while switching to typescript.
Appreciate the help!
