### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by mehulPris** [mapbox/mapbox-gl-js#13092]
pod 'MapboxMaps', '11.1.0'

xcode Version 15.1 
swift version 5

pod install successfully but do not create build.

get error >>>>>>
Sandbox: rsync.samba(33848) deny(1) file-write-create /Users/m1macmini/Library/Developer/Xcode/DerivedData/mapbox_swiftui-ebtsswqxaqzgvpaemjejlxjqzazx/Build/Products/Debug-iphoneos/mapbox_swiftui.app/Frameworks/MapboxMaps.framework/MapboxMapsResources.bundle

**Comment by mourner** [comment]
Looks like you're reporting to the wrong repo. This one is about Mapbox GL JS (the Web SDK).
