### ISSUE TITLE
How to get density values calculated from source points for heat map layer? 

### ISSUE THREAD

**Issue by dantebiase** [mapbox/mapbox-gl-js#13103]
**mapbox-gl-js version**:

### Question
How to get density values calculated from source points for the resulting heat map layer? 

I'm looking to count the number of data points mapped between each color threshold, ex:
- 10 points lie between transparent and royalblue
- 30 points found between royalblue and cyan,
...

Is this possible?

### Links to related documentation
https://www.mapbox.com/blog/introducing-heatmaps-in-mapbox-gl-js
https://docs.mapbox.com/help/tutorials/make-a-heatmap-with-mapbox-gl-js/
https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/

**Comment by mourner** [comment]
I don't think there's a way to do that. However, you can get all the features that affect heatmap rendering in a particular point with `queryRenderedFeatures` after https://github.com/mapbox/mapbox-gl-js/pull/10996.
