### ISSUE TITLE
Aggressive panning in `featuresAt` demo causes lag

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-js#1310]
> [Example](https://www.mapbox.com/mapbox-gl-js/example/featuresat/) tested in both firefox and chrome

![](https://cloud.githubusercontent.com/assets/1058624/8310643/2f789406-1986-11e5-8291-bd8c86aea4d4.gif)

I'm thinking there are two solutions here:

* Don't trigger `map.featuresAt` on the`mousemove`
* Fix the underlying `featuresAt` code to handle more requests/s

**Comment by jfirebaugh** [comment]
Covered by #1191. featuresAt is asynchronous so there will inherently be some lag, but we need to profile and improve performance.
