### ISSUE TITLE
Creating bezier curves with Mapbox

### ISSUE THREAD

**Issue by ShafSpecs** [mapbox/mapbox-gl-js#13111]
**mapbox-gl-js version**: 3.0.1

### Question

How do I do something like: https://labs.mapbox.com/bezier-curves/? I have checked out a few tools like Mapbox GL Draw and https://github.com/Jeff-Numix/mapbox-gl-draw-bezier-curve-mode but haven't been able to correctly replicate a line system that allows for creation of bezier curves. 

The code seems to be closed source and the browser sourced is too minified to make sense of. Thanks

**Comment by stepankuzmin** [comment]
Hi @ShafSpecs,

This is made with [Paper.js](http://paperjs.org/).

**Comment by ShafSpecs** [comment]
> Hi @ShafSpecs,
> 
> This is made with [Paper.js](http://paperjs.org/).

Thanks a lot 😊! Extra, please does it use mapbox-draw with it? Or it's just paper and mapbox-gl. Appreciate the help
