### ISSUE TITLE
Tilesets Only Partially Rendering

### ISSUE THREAD

**Issue by wklumpen** [mapbox/mapbox-gl-js#13112]
I have some maps uploaded via the tileset service API that are only partially rendering tilesets at certain zoom levels:

![image](https://github.com/mapbox/mapbox-gl-js/assets/7478016/62f3b447-2517-49ca-bea9-cdefacc5949a)

But at closer zoom levels render fine:

![image](https://github.com/mapbox/mapbox-gl-js/assets/7478016/ab083c6b-e38b-437e-8174-0b2dfe3f2b3f)

This seems to also be the case with the [same upload in Studio](https://studio.mapbox.com/tilesets/wklumpen.CHI-20230925-WEDAM-tiles) (id: wklumpen.CHI-20230925-WEDAM-tiles)

However a [manual upload of the same data using a shapefile](https://studio.mapbox.com/tilesets/wklumpen.3cziqeju) seems to show no issues on zooms.

I have attempted to upload via the tileset processing service the same data with the same inferred zoom settings, and this has not resolved the issue.

I suspect this may be an issue with the processing pipeline, as suggested by a [previous issue](https://github.com/mapbox/mapbox-gl-js/issues/7113) - however there has been no update on this since it was closed.

I have also inspected my GeoJSON newline data via QGIS and the data is complete and works fine, so I don't think it's a data issue given the manual upload also.

**mapbox-gl-js version**: v2.14.1

**browser**: Firefox

### Link to Demonstration

Links provided in the description above. I've the recipe I used to upload.

[CHI-20230925-WEDAM-recipe.json](https://github.com/mapbox/mapbox-gl-js/files/14528156/CHI-20230925-WEDAM-recipe.json)

### Expected Behavior
Properly render tilesets at all zoom levels

### Actual Behavior
Improperly rendered tilesets at some zoom levels

**Comment by stepankuzmin** [comment]
Hi @wklumpen,

It seems that there was a warning in the MTS job run that features were dropped due to tile size limits. We would suggest to follow this guide to update your recipe and avoid hitting the size limit: https://docs.mapbox.com/mapbox-tiling-service/guides/frequentlyaskedquestions/#there-are-gaps-of-missing-data-in-my-tiles

I'm closing this issue since it's not related to the GL JS.
