### ISSUE TITLE
coordinates system

### ISSUE THREAD

**Issue by wxl17839938583** [mapbox/mapbox-gl-js#13114]
map.on('click', (e) => {
      console.log(‘Current click coordinates:', e.lngLat)
    })
    May I ask, what coordinate system is the latitude and longitude information printed？

**Comment by stepankuzmin** [comment]
Hi @wxl1783993858,

You can find the `click` event handler arguments [here](https://docs.mapbox.com/mapbox-gl-js/api/events/#mapmouseevent%23lnglat).

A `LngLat` object represents a given longitude and latitude coordinate, measured in degrees. These coordinates use longitude, latitude coordinate order (as opposed to latitude, longitude) to match the [GeoJSON specification](https://datatracker.ietf.org/doc/html/rfc7946#section-4), which is equivalent to the OGC:CRS84 coordinate reference system.

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.

**Comment by wxl17839938583** [comment]
ok

**Comment by wxl17839938583** [comment]
okay,thank you
