### ISSUE TITLE
v3.2.0 introduces hillshade bug for Desktop Safari

### ISSUE THREAD

**Issue by elygeo** [mapbox/mapbox-gl-js#13134]
**mapbox-gl-js version**: 3.2.0

**browser**: Desktop Safari 17.4.1

### Link to Demonstration

https://docs.mapbox.com/mapbox-gl-js/example/hillshade/

### Expected Behavior

![Hillshade-Chrome](https://github.com/mapbox/mapbox-gl-js/assets/338731/c5de45c8-0208-47dc-951d-9536a87d1e56)

### Actual Behavior

![Hillshade-Safari](https://github.com/mapbox/mapbox-gl-js/assets/338731/e4b88f2b-c279-4ab2-b243-2021f2f43857)

**Comment by mourner** [comment]
Do you have private browsing mode / fingerprinting protection enabled? See #12997 (closing this one as a duplicate)

**Comment by elygeo** [comment]
Yes, that's it, thanks! I will comment over there.
