### ISSUE TITLE
MapboxSearchBox not working in fullscreen mode

### ISSUE THREAD

**Issue by ouvreboite** [mapbox/mapbox-gl-js#13132]
When using the MapboxSearchBox and mapboxgl.FullscreenControl(), when in fullscreen the searchbox no longer works: typing in the search box does not open the result list.

**mapbox-gl-js version**:  3.2.0
**browser**: chrome 123.0.6312.87

### Steps to Trigger Behavior

 1. Create a simple map
 2. Add the MapboxSearchBox as a control
 3. Add the FullscreenControl as a control
 4. In non-fullscreen: the search box work as expected (typing a word display the list of possible search result)
 5. In fullscreen: the search box does not work (typing a word does nothing)

### Link to Demonstration

https://jsfiddle.net/hytcdL9v/2

### Expected Behavior

The MapboxSearchBox should present search result in fullscreen (same as in non-fullscreen)

### Actual Behavior

The MapboxSearchBox in fullscreen does nothing

**Comment by mpothier** [comment]
@ouvreboite Thank you for reporting the issue, I am able to reproduce it. I will open up an internal ticket for Search JS and will plan a fix for an upcoming release.

**Comment by mpothier** [comment]
@ouvreboite This issue is fixed with Search JS [v1.0.0-beta.22](https://docs.mapbox.com/mapbox-search-js/guides/changelog/#100-beta22)
