### ISSUE TITLE
autofill '22 rue voltaire paris' contains 0 address from paris

### ISSUE THREAD

**Issue by jlslew** [mapbox/mapbox-gl-js#13130]
**mapbox-gl-js version**: https://api.mapbox.com/search-js/v1.0.0-beta.19/web.js

**browser**: Google Chrome Version 123.0.6312.58 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Navigate to https://docs.mapbox.com/mapbox-search-js/example/autofill-checkout-js/
 2. In the address field, type '22 rue voltaire paris', it doesn't return an address from paris
 3. In the address field, type '22 rue voltaire 75011', it does return an address from paris

### Link to Demonstration

https://docs.mapbox.com/mapbox-search-js/example/autofill-checkout-js/

### Expected Behavior
Using the city in the address-line1 autocomplete returns the correct result

### Actual Behavior
Using the city in the address-line1 autocomplete doesn't return the correct result

**Comment by mpothier** [comment]
@jlslew thanks for bringing to our attention. I will create an internal ticket for our API team to investigate this issue further.
