### ISSUE TITLE
Enable data driven styling for `fill` layers

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1314]

**Comment by ansis** [comment]
This is blocked by in-browser polygon tessellation with earcut https://github.com/mapbox/mapbox-gl-js/pull/948 which is blocked by https://github.com/mapbox/mapnik-internal/issues/11

**Comment by lucaswoj** [comment]
Closing because all data-driven styling functionality has been reverted #1409 #1415 #1418
