### ISSUE TITLE
When drawing, self-intersecting polygons are removed

### ISSUE THREAD

**Issue by blend3dweb** [mapbox/mapbox-gl-js#13147]
Good afternoon.
When drawing polygons in one layer and if the polygons intersect themselves, the polygons that intersect are excluded from the display.

While studying this topic, I came to the conclusion that mapbox-gl does not work correctly with self-intersecting polygons.

Attached an image
1) Actual behavior
2) Expected behavior

![2024-04-15_14-24](https://github.com/mapbox/mapbox-gl-js/assets/43431061/5cfa76ed-75ab-498f-922c-0679191afce6)

Here are links to the information that led to the above conclusion.

[Link 1](https://github.com/mapbox/mapbox-gl-js/issues/2696#issuecomment-236292473)
[Link 2](https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule)
[Link 3](https://github.com/mapbox/mapbox-gl-js/issues/4962#issuecomment-315294990)
[Link 4](https://github.com/mapbox/mapbox-gl-js/issues/7023)

Is it possible to get around this bug?

mapbox-gl-js version:  3.2.0
browser: chrome / firefox

**Comment by mourner** [comment]
No. See #7023
