### ISSUE TITLE
Mapbox marker does not scale with GeoJSON symbols during pitch and bearing adjustments

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#13179]
**mapbox-gl-js version**: 3.3.0

**browser**: (Include the browser where you encountered the bug, e.g., Chrome 104.0.5112.101)
Chrome

### Steps to Trigger Behavior

 1. Load the map with GeoJSON circle symbols.
 2. Click on a circle to add a Mapbox marker styled as a circle directly on top of the clicked GeoJSON circle.
 3. Change the map's pitch and bearing.

### Link to Demonstration

[https://jsbin.com/(Paste your jsbin link here after creating the demo)](https://jsfiddle.net/iaezzy/0ck4tpL8/)

### Expected Behavior

The Mapbox marker, styled as a circle, should resize proportionally with the GeoJSON circles when the map's pitch and bearing are changed.

### Actual Behavior

The Mapbox marker does not resize in proportion to the GeoJSON circles during pitch and bearing changes, causing the marker to either overlap inappropriately or appear smaller/larger than the underlying GeoJSON symbol.
![CleanShot 2024-05-18 at 8  47 26](https://github.com/mapbox/mapbox-gl-js/assets/105034/a22f5de1-7ff9-422b-9704-c7503631af78)

**Comment by 3zzy** [comment]
Actually, I attempted a similar approach by adding a new layer stacked on top, using the exact same symbols. These symbols behaved similarly to the marker, so it appears the issue is not just with the marker.

**Comment by stepankuzmin** [comment]
Hi @3zzy,

The markers are rendered independently of layers. To highlight individual features, you could use [feature state](https://docs.mapbox.com/mapbox-gl-js/api/map/#map%23setfeaturestate). Closing the issue, but feel free to comment if there is anything else on the matter.
