### ISSUE TITLE
FitBounds done not function with projections other than Mercator.

### ISSUE THREAD

**Issue by DDDgfx** [mapbox/mapbox-gl-js#13170]
**mapbox-gl-js version**: 3^

**browser**: Chrome

### Steps to Trigger Behavior

 1. Call fitBounds via js.
 2. A flyTo is initiated that drives the camera to northwest infinity above Alaska.
 3. Switch the style to mercator projection and behavior is normal.
 4. 4. No errors are thrown.

### Link to Demonstration

https://jsbin.com/

### Expected Behavior
fitBounds acts as expected

### Actual Behavior
fitBounds flys to northwest infinity.

**Comment by stepankuzmin** [comment]
Hi @DDDgfx,

We've improved the fitBounds in the latest [v3.7.0-beta.1](https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.7.0-beta.1) release.
