### ISSUE TITLE
Bug: Slot property is missing

### ISSUE THREAD

**Issue by alamenai** [mapbox/mapbox-gl-js#13187]
**mapbox-gl-js version**: 3.2.0

**browser**: Chrome

### Steps to Trigger Behavior

 1.Read the [documentation](https://docs.mapbox.com/mapbox-gl-js/guides/migrate-to-v3/) of mapbox v 3.2.0.

 2. Adding slot property to the layer.

### Expected Behavior

- Slot property is existing in the layer.

### Actual Behavior

![image](https://github.com/mapbox/mapbox-gl-js/assets/20143684/90b2048a-cbaa-49b8-bb1e-3a0c0954c277)

**Comment by stepankuzmin** [comment]
The issue you are encountering is related to the outdated TypeScript community typings. The good news is that we now provide first-class TypeScript typings support after migrating GL JS to TypeScript. Please refer to the [v3.5.0 release notes](https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.5.0) and the [migration guide](https://github.com/mapbox/mapbox-gl-js/issues/13203) from `@types/mapbox-gl` to first-class TypeScript typings.
