### ISSUE TITLE
GeoJsonSource doesn't provide a method to update partial features that have been deleted or modified.

### ISSUE THREAD

**Issue by heavis** [mapbox/mapbox-gl-js#13188]
In my use case, I would load more than 100,000 features data with GeoJsonSource and then edit some of them. GeoJsonSource only provides the setData method to reset all feature data. GeoJsonSource will pass all data to the worker thread for tile cutting, but the transfer of large data between the UI thread and the worker is time-consuming, leading to rendering lag. How can this issue be resolved?

**Comment by Sunrisies** [comment]
同问

**Comment by heavis** [comment]
> 同问

Latest verson 3.4.0 has provided updateData API on GeoJSON source to add, update or delete partial features.

**Comment by mourner** [comment]
Yep, hope this is addressed now with `updateData`.
