### ISSUE TITLE
Markers Move on Edge at Zoom 5.977804006915341

### ISSUE THREAD

**Issue by allencoded** [mapbox/mapbox-gl-js#13193]
In the example code for placing a marker https://docs.mapbox.com/mapbox-gl-js/example/add-a-marker/ if you zoom to around `5.977804006915341` and drag the map so the markers about to fall off the canvas you will notice the markers begin to wiggle and move. If you make the map full screen it will even get worse.

Here is a fiddle of the issue
https://jsfiddle.net/6e81ofwr/6/

**mapbox-gl-js version**:
latest 

**browser**:
chrome latest

### Steps to Trigger Behavior

 1. Set Zoom to 5.977804006915341
 2. Move map so markers on edge of screen and watch them move

### Link to Demonstration
https://jsfiddle.net/6e81ofwr/6/

### Expected Behavior
I would expect that the markers stay in their place and don't dance around.

### Actual Behavior
Markers wiggle around.

**Comment by allencoded** [comment]
Is there any update on this bug?

**Comment by vbilki** [comment]
Any update?

**Comment by stepankuzmin** [comment]
Hi everyone. This is a known issue: https://github.com/mapbox/mapbox-gl-js/issues/13065. I will close this issue so we can track it in one place.
