### ISSUE TITLE
setLights doesnt work if an ambient light isn't provided

### ISSUE THREAD

**Issue by garma83** [mapbox/mapbox-gl-js#13192]
**mapbox-gl-js version**: 3.4.0

**browser**: Firefox, Chrome

### Steps to Trigger Behavior

 1. Add a directional light with the map.setLights() function
 2. Notice that the scene is still flat shaded (in the file style/style.js, the function enable3dLights() checks for ambient lights)
 3. Add an ambient light.

### Link to Demonstration

https://jsbin.com/

### Expected Behavior

Lights should work even when there is no ambient light

**Comment by stepankuzmin** [comment]
Hi @garma83,

Thanks for catching this. At the moment, both ambient and directional lights are required. We'll clarify the docs and might revise this in the future.
