### ISSUE TITLE
3D models not showing with GeoJSON source

### ISSUE THREAD

**Issue by joecusdin** [mapbox/mapbox-gl-js#13191]
**mapbox-gl-js version**: 3.4.0

**browser**: Chrome Version 122.0.6261.69

### Steps to Trigger Behavior

 1. Add a GeoJSON source
 2. Add a 3D model layer using the GeoJSON source

### Link to Demonstration

https://codepen.io/Joe-djc/pen/ZENeJQV#

### Expected Behavior

3D models show at positions of GeoJSON points

### Actual Behavior

No 3D models are shown, and no errors are thrown. In the demonstration, I have added a circle layer using the same source to show where I expect the models to appear. I am using the "turbinetower-lod1" model (part of the standard style).

**Expecting to see 'Turbine Towers' on the black circles**

<img width="1295" alt="Screenshot 2024-06-01 at 11 25 11" src="https://github.com/mapbox/mapbox-gl-js/assets/153616660/613941fb-0b21-4c5d-bd89-858b86ab368e">

**Comment by linze99** [comment]
This is not a bug,
add model before you add the model layer.
![截屏2024-06-03 14 00 03](https://github.com/mapbox/mapbox-gl-js/assets/30024479/35e7342f-576d-4763-b212-b53e9605c782)

**Comment by joecusdin** [comment]
Ok thanks @linze99. I used a model which was part of the style sheet assuming I could use it (e.g. a tree which is part of the standard style...those turbine towers are in the style). I'll add them after the style has loaded in future.
