### ISSUE TITLE
Mapbox Standard: Building shadows unchanged for polar angle values 75-90 degrees

### ISSUE THREAD

**Issue by stephent** [mapbox/mapbox-gl-js#13205]
**mapbox-gl-js version**:
3.4.0

**browser**:
Chrome 126.0.6478.62

### Steps to Trigger Behavior

1. With MapBox Standard (in a React app):

```
    // https://docs.mapbox.com/mapbox-gl-js/guides/migrate-to-v3/
    mapRef.current = new mapboxgl.Map({
      container: mapContainerRef.current!,
      style: 'mapbox://styles/mapbox/standard',
      center: center,
      zoom: zoom,
      pitch: pitch,
      bearing: bearing
    });
```
 2. And setting a direction light that casts shadows:

```
{
      id: 'directional',
      type: 'directional',
      properties: {
        direction: [az, polarAngle],
        intensity: 0.5,
        'cast-shadows': true,
        'shadow-intensity': 1.0
      }
}
```

3. Check the shadows as the polar angle increases beyond 75 degrees - the length of the building shadows should increase, but it remains unchanged.

### Screenshots

Shadows are shown for polar angle values 70, 75, 80, 85, 90. Note the position of the shadow tip of the Eiffel Tower. It does not change for any polar angle value >=75.

![CleanShot 2024-06-19 at 14 09 59@2x](https://github.com/mapbox/mapbox-gl-js/assets/898090/d99cfa47-31d8-4f13-84c0-ee61ab9308e3)
![CleanShot 2024-06-19 at 14 10 06@2x](https://github.com/mapbox/mapbox-gl-js/assets/898090/07690879-5029-4aaf-8c23-ee1a7fb06339)
![CleanShot 2024-06-19 at 14 10 11@2x](https://github.com/mapbox/mapbox-gl-js/assets/898090/87c0d4fb-8b83-4eeb-96e4-4ae7cc86a5d5)
![CleanShot 2024-06-19 at 14 10 17@2x](https://github.com/mapbox/mapbox-gl-js/assets/898090/da5d9d23-4e6b-4225-988c-e2cd4682f418)
![CleanShot 2024-06-19 at 14 10 22@2x](https://github.com/mapbox/mapbox-gl-js/assets/898090/6d74a164-8982-45c0-9658-10e8f496ba6e)

### Demo

This issue can also be reproduced in Brody Smith's demo online here: https://brody.fyi/blog/mapbox-lighting

### Expected Behavior

Building shadow length should increase with polar angle for values > 75 degrees.

### Actual Behavior

Building shadow length remains unchanged for polar angle for values > 75 degrees.

**Comment by jtorresfabra** [comment]
Hi @stephent,

You are right the MaxPolarCoordinate is clipped to 75 degrees. This behaviour is done on purpose for performance reasons and to avoid visual artifacts. The most space the projective shadows fill, the less resolution the shadow texture will have, creating ugly artifacts. To avoid this we should increase the shadow texture size, having impact in performance and memory used. That's why we took that decision. 

Thanks for your understanding.

**Comment by stephent** [comment]
@jtorresfabra thanks for the clarification. I don't see this behavior documented anywhere.

![image](https://github.com/mapbox/mapbox-gl-js/assets/898090/94d7ae57-ae6c-4983-8d60-8976e3727d6c)

Might you consider configurable shadow map size and bias in the future? It would be useful to have some control over this, trade offs notwithstanding.

**Comment by jtorresfabra** [comment]
@stephent For now there is no plans for having this configurable. What I can commit to is to document this in a clear way. Thanks for the headsup!
