### ISSUE TITLE
Web Gl 2 support for mapbox (Angular) ?

### ISSUE THREAD

**Issue by ShadyManu** [mapbox/mapbox-gl-js#13200]
Hello, I'm using Angular 17 as framework, and the last version of ngx-mapbox-gl is the 10.0.0, and I found that it's the 2.9.0 of webgl js..

### Question
I found out that WebGl 2 went by default on the latest releases (like the 3.4.0). Any way to make this work on Angular as well? Because I'm using the latest version of Threejs in Angular, which removed the support of Web Gl 1 from release 163. 
To fix that I had to downgrade the threejs version to 162.

**Comment by stepankuzmin** [comment]
Hey @ShadyManu,

We don't provide GL JS bindings for specific frameworks out of the box, so I think this should be addressed by `ngx-mapbox-gl`.
