### ISSUE TITLE
We're sorry! There's been an unexpected error. Please try again.

### ISSUE THREAD

**Issue by MickeyMouse623** [mapbox/mapbox-gl-js#13217]
注册时页面中提示
We're sorry! There's been an unexpected error. Please try again.

打开控制台提示
<img width="489" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/18524460/db38c2b2-1d33-4083-ae9a-fbce1c7e4710">
<img width="420" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/18524460/45e52323-53a8-43ee-9553-dc4f40847e28">

**Comment by mourner** [comment]
It's an error on your end, we don't have any code like that in GL JS.

**Comment by MickeyMouse623** [comment]
<img width="516" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/18524460/e21e9198-afb1-4169-a510-f29fdd2ce460">
