### ISSUE TITLE
Polygon Fill layer incorrectly displayed showing weird clipping

### ISSUE THREAD

**Issue by Fabioni** [mapbox/mapbox-gl-js#13214]
**mapbox-gl-js version**: 3.4.0 (but also does not work on mapbox-gl@3.5.0-beta.1)

**browser**: chrome

### Steps to Trigger Behavior

 1. create a goejson source with a polygon
 2. use that source in a fill layer
 3. try around with position of vertices and zoom level until you find the bug

### Link to Demonstration

https://codepen.io/Fabioni/pen/VwJZwXx

### Expected Behavior

show a correct polygon

### Actual Behavior

strange clipping

this should be a proper triangle:
<img width="561" alt="Screenshot 2024-07-03 at 15 52 26" src="https://github.com/mapbox/mapbox-gl-js/assets/45362676/1f93e526-bb87-484f-a530-3fb8e7cd9d4a">

<img width="790" alt="Screenshot 2024-07-03 at 15 58 24" src="https://github.com/mapbox/mapbox-gl-js/assets/45362676/cd1b61a7-8850-425e-8508-d2942965a131">

**Comment by stepankuzmin** [comment]
Hi @Fabioni,

According to the GeoJSON spec, the Polygon must be a closed LineString with four or more positions (the last coordinate must be the same as the first one). It works as expected if you fix that in the source definition:

```js
type: "Polygon",
  coordinates: [
    [
      [35.51817610057927, 47.12239633159362],
      [35.51490982435837, 47.109133462205136],
      [35.47684828857581, 47.097217388212215],
      [35.51817610057927, 47.12239633159362]
    ]
  ]
```
