### ISSUE TITLE
RemoveFeatureState typing error

### ISSUE THREAD

**Issue by xvThomas** [mapbox/mapbox-gl-js#13218]
I recently saw the typescript definition of `FeatureSelector` used by `RemoveFeatureState`:

```
type FeatureSelector = {
  id: string | number;
  source: string;
  sourceLayer?: string;
};
```

The attribute `id` is mandatory, but the doc mentions that `RemoveFeatureState` can be used as below:

```
@example
* // Reset the entire state object for all features
* // in the `my-source` source
* map.removeFeatureState({
*     source: 'my-source'
* });
```

**mapbox-gl-js version**:
3.5.1

### Expected Behavior

Define `FeatureSelector` as:

```
type FeatureSelector = {
  id?: string | number;
  source: string;
  sourceLayer?: string;
};
```

A workaround might be:

```
 map.removeFeatureState({
   source: 'my-source'
} as unknown as { source: string; sourceLayer: string; id: string | number })
```
But not really elegant

**Comment by stepankuzmin** [comment]
Thanks for flagging this, @xvThomas. We'll address this in the upcoming patch release.
