### ISSUE TITLE
GeoJSON sources in dynamic mode Linstring not straight

### ISSUE THREAD

**Issue by sboivinsystra** [mapbox/mapbox-gl-js#13219]
First of all. Thank you for this new feature. I was waiting for such a feature for a long time and I think it's awesome!

I have a problem when I display LineStrings and zoom on them. The issue seems to appear when the 2 ends of the linestring are outside the map view. So when we zoom on a linstring. It also seems to work fine with mapbox 3.4...

**mapbox-gl-js version**: 3.5.1.

**browser**: Firefox or Chrome (other not tested)

### Steps to Trigger Behavior

 1. create a **Geojson dynamic** layer with Linestrings
 2. have a long linestring
 3. zoom on it

ex: here I have a  LineString with 2 points

![Screenshot from 2024-07-11 14-07-39](https://github.com/mapbox/mapbox-gl-js/assets/79281989/3677651f-acd8-4318-9797-16a5623f7b6d)

When I zoom on it. it is not straight anymore.

![Screenshot from 2024-07-11 14-07-32](https://github.com/mapbox/mapbox-gl-js/assets/79281989/dc3122c1-5a39-4348-8484-f0110b4f1830)

### Expected Behavior
A straigth line
### Actual Behavior
A bunch or cut lines

**Comment by mourner** [comment]
Thanks for the report! Definitely looks like a bug. I think I know what's going on, we'll work on a fix.
