### ISSUE TITLE
Some Mapbox docs pages crashing

### ISSUE THREAD

**Issue by ian-weir** [mapbox/mapbox-gl-js#13215]
Sorry, I know probably not the correct repo for this but I couldn't find another avenue to report it.

**mapbox-gl-js version**: N/A

**browser**: Firefox & Chrome

### Steps to Trigger Behavior

 1. Go to various examples in the docs pages

### Link to Demonstration

https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/

### Expected Behavior

View an example

### Actual Behavior

Error

![Screenshot 2024-07-04 at 08 49 36](https://github.com/mapbox/mapbox-gl-js/assets/14279981/4126bdb9-030a-4f91-bf38-3aa11343d3a9)

**Comment by stepankuzmin** [comment]
Hey @ian-weir,

Thanks for catching this! We are working on it.

**Comment by mourner** [comment]
Looks like this was fixed?
