### ISSUE TITLE
New `Source` types in `v3.5` don't support type narrowing via the `type` property

### ISSUE THREAD

**Issue by ezzatron** [mapbox/mapbox-gl-js#13220]
Related to #13203

**mapbox-gl-js version**: v3.5.1

**browser**: N/A

### Steps to Trigger Behavior

 1. Write code that checks the `type` property of a `Source` to narrow its type.
 2. Try to use the narrowed type source as the expected type.
 3. Source type is not narrowed.

### Link to Demonstration

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgcQKYQFIGUDyA5LCAVygGNUAaOAWQEMwBfOAMyghDgCIR6AjCAB4BaAOYAbTgG4AUNNIQAdgGd4PMHAC8cBagDuNegAoE8hTFrAdUAFxwAJhFJEQqMwDoRqGAFExqF2YAQgCeAJJ2hpzAdpwAlACEDLEypipwSsRkqJpwah5ehCTkkdFxMtJ+8J6YuASZ5LZoNfiFWeXAzHCGGUWoAPxuMMFg2RpjXNUAVhkKcYjScItw1dgt9aPp6zIMQA

Repeated here:

```ts
import { GeoJSONSource, Map} from "mapbox-gl";

const map = new Map({container: document.getElementById("id")!});
const source = map.getSource("id");

let geoJSONSource: GeoJSONSource;

if (source?.type === "geojson") {
    geoJSONSource = source; // <-- this should not be a type error, but it is
}
```

### Expected Behavior

You can narrow a `Source` type to a `GeoJSONSource` type by using `source.type === "geojson"`.

### Actual Behavior

`Type 'GeoJSONSource | VideoSource | ImageSource | CanvasSource' is not assignable to type 'GeoJSONSource'.`

**Comment by stepankuzmin** [comment]
Thanks for creating an issue, @ezzatron. We'll address this in the upcoming patch release.
