### ISSUE TITLE
GeoJSONSource In dynamic mode, the new element is rendered in the wrong order

### ISSUE THREAD

**Issue by heavis** [mapbox/mapbox-gl-js#13229]
I added new points and  polygon layers in order, and the initial rendering was normal. When I update an element of the  polygon layer, the overlapping point elements are rendered below the polygon element.

**Steps to Trigger Behavior**

1.create a Geojson dynamic layers with point and polygon, The point layer is placed above the polygon layer.
![image](https://github.com/user-attachments/assets/42f0575e-e5f1-4e7d-991c-4e5275870fa5)
2.Update a polygon feature where is overlaped with point feature,  then the point feature is rendered below the polygon.
![image](https://github.com/user-attachments/assets/2996158c-1220-4c87-8d2b-e8dfffe8902a)

**Expected Behavior**

Point feature is placed above polygon layer.

**Actual Behavior**

Point feature is placed below polygon layer.

**Comment by mourner** [comment]
Can you please provided a minimal live test case (e.g. with JSFiddle) that reproduces this issue?
