### ISSUE TITLE
Build fails on Windows when running node docs : FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#1322]
Hello,

Just downloaded a zip copy of the mapbox-gl-js master from github and ran "npm install" as usual (it used to work when building 0.7.x).

After a while, the program crashes when running "node docs/_generate/generate.js" with the following error:
```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```
I use node v0.12.4 on WIndows 8.1 x64. The process crashes when it reaches about 780Mb or RAM used. I think I saw in the changes that you changed the documentation generator, maybe it hasn't been tested on Windows?

The strange thing is that before generating the docs, the process only takes about 80Mb or RAM so there is definately a problem with the docs generation.

I looked it up online and it seems like the "max-old-space-size" option can sort this out. I tried running 
```
npm --max-old-space-size=2000000 install 
```
But I get the same error.

Any idea?

Fabien

**Comment by springmeyer** [comment]
> I think I saw in the changes that you changed the documentation generator, maybe it hasn't been tested on Windows?

Good hunch. Another possibility is you have a stale build of some sort. Have you tried running `npm cache clean`, removing the `./node_modules` and doing a full re-install?

**Comment by fnicollet** [comment]
Thanks for the quick answer. 

This laptop is actually all new, bought it a couple weeks ago, I believe it was even the first node program that was executed on it. And I unzipped the master in a temp dir, so there was no existing node_modules folder inside it

Fabien

**Comment by jfirebaugh** [comment]
My hunch is that this is https://github.com/documentationjs/documentation/issues/133.

**Comment by jfirebaugh** [comment]
@fnicollet Is this still happening?

**Comment by fnicollet** [comment]
Hello @jfirebaugh ,

Just downloaded a fresh copy of master and ran npm install. It still crashes on Windows 10
[npm-debug.txt](https://github.com/mapbox/mapbox-gl-js/files/53215/npm-debug.txt)

I attached the log file

Fabien

**Comment by lucaswoj** [comment]
> 188066 info gl@2.1.5 Failed to exec install script

This looks like a bug with `headless-gl`. I expect it has been fixed with the update to v4.
