### ISSUE TITLE
styleimagemissing event missing id property

### ISSUE THREAD

**Issue by AnthonyKartorium** [mapbox/mapbox-gl-js#13232]
**mapbox-gl-js version**: 3.5.2

**browser**: Chrome

### Expected Behavior
this.map.on('styleimagemissing', (event) => {
                    const imageID = event.id
}
the returned event to have an id as stated in the [documentation](https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:styleimagemissing)

### Actual Behavior
Property 'id' does not exist on type '{ type: "styleimagemissing"; target: Map$1; }'.

const imageID = event.id

**Comment by stepankuzmin** [comment]
Hi @AnthonyKartorium,

Good catch, thanks! We'll address it in the next release.

**Comment by stepankuzmin** [comment]
Hi @AnthonyKartorium,

This should be fixed in the latest GL JS. Closing the issue, but feel free to comment if you have any questions.
