### ISSUE TITLE
Add a "circle-opacity" style property

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1323]
Related to https://github.com/mapbox/mapbox-gl-style-spec/issues/304

**Comment by ansis** [comment]
implemented in https://github.com/mapbox/mapbox-gl-js/pull/1364 and https://github.com/mapbox/mapbox-gl-js/pull/1347

**Comment by lucaswoj** [comment]
These changes were reverted from v8 along with the rest of data-driven styling.

**Comment by lucaswoj** [comment]
Little did he know that the changes were *not* actually reverted https://github.com/mapbox/mapbox-gl-js/blob/v8/js/style/style_layer.js#L184

**Comment by jfirebaugh** [comment]
So something like https://github.com/mapbox/mapbox-gl-js/commit/f6b61515036650682ae99c7f5035ce0dd3de1e36 is not necessary?

**Comment by jfirebaugh** [comment]
Yeah, that looks wrong, it's reading a layout property. Deleting the branch.

**Comment by lucaswoj** [comment]
The opacity is applied for all layer types here https://github.com/mapbox/mapbox-gl-js/blob/v8/js/style/style_layer.js#L189
