### ISSUE TITLE
Intersection doesn't seem to work consistently

### ISSUE THREAD

**Issue by pdfabbro** [mapbox/mapbox-gl-js#13234]
Searching for intersections in mapbox search doesn't consistently return results.  Searching for "Cypress Ave & Gates Ave" works on google maps but does not return the proper intersection in mapbox search

**mapbox-gl-js version**: all

**browser**: all

### Steps to Trigger Behavior

 1. Go here or to the developer playground https://www.mapbox.com/search-box
 2. Enter "Cypress Ave & Gates Ave" in the search box
 3. Do not get proper results

### Link to Demonstration

See above steps

### Expected Behavior

Should return an intersection in Queen's New York

### Actual Behavior
Does not return the above intersection

**Comment by ppatternn** [comment]
Thank you for the feedback!  This is something we plan to improve in the future.
