### ISSUE TITLE
the geojson source with dynamic property, when the camera is zooming ,symbol layer elements disappear and huge memory consumed  

### ISSUE THREAD

**Issue by ANALKH-DY** [mapbox/mapbox-gl-js#13233]
Hello, the author of the mapboxGL，I'm sorry my english is not good. I'm using mapboxgl v3.4.0 into my project. The main product demand is display our devices on map in real time, so i use the requestAnimationFrame to update the geojson source data, it's nearly updates the geojson data 300 times per 5 seconds , about 60 fps. it is very strange that my code is running well in development environment but getting something wrong in production environment. The detail is that icons and models will disappear when zooming the map in and out multiple times and the memeory leak, this bug occupi occasionally  

**mapbox-gl-js version**: v3.4.0

**browser**: edge, chrome

### Steps to Trigger Behavior

 1. icons of symbol layer and models of model layer disappear 
 2. memory leak
![1721614213469](https://github.com/user-attachments/assets/5d17544b-a369-4ab7-9e23-0323b6a56894)

**Comment by stepankuzmin** [comment]
Hi @ANALKH-DY,

Thank you for opening this ticket. Could you please provide a minimal, complete, verifiable demonstration of the issue to help us address it? We recommend using https://jsbin.com/. Please include information about the browser version and operating system used.

**Comment by ANALKH-DY** [comment]
![image](https://github.com/user-attachments/assets/fc4434ab-1e9e-40b4-8ee0-cad4aa9fa963)

ok, afew days later, i update the version of mapboxgl to 3.5.0, i found that the key source code show in a image above, why design  
like this, like a queue(line 245)? but how many features they can be finished in a single time? if there are to many features, will it push again and again, and throw a max stack size exceed error in the end?

**Comment by ANALKH-DY** [comment]
@stepankuzmin

**Comment by stepankuzmin** [comment]
Hi @ANALKH-DY,

It'd be really helpful if you could provide a reproduction for this.

**Comment by mourner** [comment]
I think I know what this is about — will submit a fix. I didn't anticipate a case were there would be too many updates within one coalesce cycle, it's not a common pattern, but will add a safeguard so that duplicate features aren't accumulated.

**Comment by ANALKH-DY** [comment]
@mourner , okay, thanks a lot for your reply, i'm looking forward to the next version. but how to do with this case that too many updates in mapbox , is there a perfect solution? split source?

**Comment by ANALKH-DY** [comment]
> Hi @ANALKH-DY,
> 
> It'd be really helpful if you could provide a reproduction for this.

thanks a lot.

**Comment by mourner** [comment]
@ANALKH-DY 500 should be fine, it doesn't sound like much. Maybe some kind of throttling on the app side could help, but first try the next version (the beta should come out today or tomorrow) and see if it helps.

**Comment by ANALKH-DY** [comment]
@mourner thank you so much
