### ISSUE TITLE
[3.5.2] setConfigProperty rerender

### ISSUE THREAD

**Issue by chunlampang** [mapbox/mapbox-gl-js#13249]
In 3.5.1 [example](https://docs.mapbox.com/mapbox-gl-js/example/set-config-property/), after calling `setConfigProperty` let say `lightPreset`, the map will only update the light effect with a smooth animation. While in 3.5.2, it just reload everything.

**Comment by chunlampang** [comment]
It solved in 3.6.0

**Comment by underoot** [comment]
Thank you @chunlampang! Closing the issue then
