### ISSUE TITLE
API reference page crash when viewing method of `Map`

### ISSUE THREAD

**Issue by kc0506** [mapbox/mapbox-gl-js#13248]
**browser**: Chrome 127.0.6533.90

### Steps to Trigger Behavior

 1. (optional) Run chrome in incognito mode
 2. Go to https://docs.mapbox.com/mapbox-gl-js/api/map/#map#queryrenderedfeatures
 3. The page crashed

The issue can also be triggered by clicking `queryRenderedFeatures` (or any other methods) on https://docs.mapbox.com/mapbox-gl-js/api/map/.

### Link to Demonstration

![image](https://github.com/user-attachments/assets/9a70d232-1dbb-4e46-94ee-18cdd1e35e1b)

**Comment by nickvisut** [comment]
I am seeing this as well across multiple desktop browsers.

**Comment by evdama** [comment]
add me to the list of ppl seeing this behavior; I'm currently using Chrome Canary, here's the user agent string `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`

**Comment by underoot** [comment]
Thank you for your feedback! I discussed it with the documentation team, and they were aware of it and fixed the problem. Feel free to reach out here and reopen issue if you reproduced the same issue after clearing of the cache!

**Comment by nickvisut** [comment]
Thank you, @underoot! Is there a way to read the docs offline?

**Comment by kc0506** [comment]
> Thank you, @underoot! Is there a way to read the docs offline?

If you are using VSCode, then `Ctrl+Left click (Go to definition)` can help.
