### ISSUE TITLE
mapbox.eventData.uuid and mapbox.eventData cookies are not documented

### ISSUE THREAD

**Issue by mvl22** [mapbox/mapbox-gl-js#13259]
**mapbox-gl-js version**: Latest

### Question

Use of the library results in two cookies being set:

- mapbox.eventData.uuid
- mapbox.eventData

However, the purpose of these is not documented.

Many organisations, particularly in the public sector, are increasingly required to document all cookies being set.

Could the purpose of these please be formally documented?

### Links to related documentation

I would expect to find a short table documenting the two cookies and their purpose, at or near:

https://docs.mapbox.com/mapbox-gl-js/api/map/

and possibly a handy link from:
https://www.mapbox.com/legal/cookies

**Comment by underoot** [comment]
Hello, @mvl22! Thank you for your valuable comment. We will address an issue with adding legal notice in the repo in the upcoming 3.7.0 version

**Comment by MangoMarcus** [comment]
Same issue, Cookiebot actually automatically classifies these as "statistics" rather than "necessary" which is requiring us to only load Mapbox once consent for those cookies has been given by the user

@underoot If you could clarify the role and advise if it should be considered "necessary" that would be very helpful 🙏

**Comment by underoot** [comment]
@MangoMarcus, could you explain what "statistics" in Cookiebot exactly means or point to the documentation of this service to compare it with our purpose for that storage? 

We released 3.7.0 and our storage notice can be found here https://github.com/mapbox/mapbox-gl-js/blob/main/STORAGE.md

**Comment by MangoMarcus** [comment]
@underoot Cookiebot describes "statistics" as:

"Statistic cookies help website owners to understand how visitors interact with websites by collecting and reporting information anonymously."

You can find more about the other categories (necessary, preferences & marketing) here: https://www.cookiebot.com/en/cookie-declaration/

The equivalent Google Consent Mode category is `analytics_storage`: https://support.google.com/analytics/answer/13802165?hl=en

Based on the storage notice you linked it does sound like "statistics" is the most appropriate category.

I'm not a legal expert but strictly speaking I _think_ we'll need to require the user to consent to that storage before we can load the mapbox script.

Unless there were an option to disable telemetry, which there's already issue for so I'll follow that instead: #13226

Thanks 🙂

**Comment by cookie10codes** [comment]
I’m also very sure it’s categorised as Statistics, which means we need to block the functionality before consent has been given.

it would be different if it’s only a logging feature, for example having loglevel. Than it can be stored as necessary
