### ISSUE TITLE
map.setConfigProperty('basemap', 'show3dObjects', false) in standard style doesn't work anymore in 3.6.0

### ISSUE THREAD

**Issue by romka-best** [mapbox/mapbox-gl-js#13252]
**mapbox-gl-js version**: 3.6.0

**browser**: Google Chrome. Version 127.0.6533.119

### Steps to Trigger Behavior

 1. Initialize the map, for example:
 ```
 const mapInstance = new Map({
      container: mapContainer.current,
      zoom: MAP_MIN_ZOOM,
      pitch: MAP_ANIMATION_PITCH,
      center: MAP_CENTER,
      interactive: true,
      accessToken: process.env.NEXT_PUBLIC_MAPBOX_TOKEN,
    });
 ```
 2. Wait, when map will be loaded, for example:
 ```
mapInstance.on('load', () => {});
 ```
 3. In 'load' event set config property 'show3dObjects' to false, for example:
 ```
 mapInstance.on('load', () => {
     mapInstance.setConfigProperty('basemap', 'show3dObjects', false);
 });
 ```

### Expected Behavior
No 3D objects appear on the map

### Actual Behavior
All 3D objects appear on the map

**Comment by mourner** [comment]
Should work properly now.
