### ISSUE TITLE
Remotely loaded code is blocking Web Extensions on Manifest v3

### ISSUE THREAD

**Issue by seanwessmith** [mapbox/mapbox-gl-js#13267]
**mapbox-gl-js version**: 3.6.0

**browser**: chrome

### Steps to Trigger Behavior

 1. install mapbox-gl into a chrome ext running React
 2. try to upload to Chrome Web Store
 3. Chrome Web store denies due to Mapbox remotely hoisted code

### Link to Demonstration

Violation(s):

Violation reference ID: [Blue Argon](https://developer.chrome.com/docs/webstore/troubleshooting/#additional-requirements-for-manifest-v3)

Technical Requirements - Additional Requirements for Manifest V3:

Violation:
Including remotely hosted code in a Manifest V3 item.
Violating Content:
Code snippet: content_script.js: https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.3/mapbox-gl-rtl-text.js

```javascript
function setGlobals(mapLib, props) {
    for (const key of globalSettings) {
        if (key in props) {
            mapLib[key] = props[key];
        }
    }
    const { RTLTextPlugin = 'https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.3/mapbox-gl-rtl-text.js' } = props;
    if (RTLTextPlugin &&
        mapLib.getRTLTextPluginStatus &&
        mapLib.getRTLTextPluginStatus() === 'unavailable') {
        mapLib.setRTLTextPlugin(RTLTextPlugin, (error) => {
            if (error) {
                // eslint-disable-next-line
                console.error(error);
            }
        }, true);
    }
}
```

### Expected Behavior
Tree shake the RTL Text Plugin so that there's no potential for remotely hoisted code to load if the RTL Text Plugin wasn't used.

### Actual Behavior
The RTL Text Plugin isn't used but the URL is still in the compiled code.

**Comment by underoot** [comment]
Hey, @seanwessmith, thank you for your feedback!
Could you elaborate a bit: this code snippet belongs to part of your codebase of the Chrome extension? 

`mapbox-gl` doesn't include the logic of fetching the RTL plugin by default. Thus you can do tree shaking of the code you don't use according to the documentation of your build system.

**Comment by seanwessmith** [comment]
Sorry for the delay. This is actually due to the other mapbox-js library and they're working on it
