### ISSUE TITLE
Allow custom `fire` events

### ISSUE THREAD

**Issue by korywka** [mapbox/mapbox-gl-js#13264]
Please consider to allow custom map events. This can be useful for custom mapbox controls.
Maybe the same error we have with `.on` listener, I have not checked.

<img width="1050" alt="image" src="https://github.com/user-attachments/assets/13678024-74c7-4d9a-a148-6aafa8eab992">

**mapbox-gl-js version**: 3.6.0

**Comment by underoot** [comment]
cc: @stepankuzmin

**Comment by stepankuzmin** [comment]
Hi @korywka,

This will be fixed in the upcoming v3.7.0-beta.1.
