### ISSUE TITLE
Standard Style CONTEXT_LOST_WEBGL

### ISSUE THREAD

**Issue by shuabrannigan** [mapbox/mapbox-gl-js#13273]
**mapbox-gl-js version**: v3.5.2

**browser**: Chrome Version 128.0.6613.119 (Official Build) (arm64)

### Steps to Trigger Behavior

 1. Load a map using the standard mapStyle `mapbox://styles/mapbox/standard`
 2. Add custom layers with filter applied
 3. Dynamically update the layer filter via `map.setFilter(...)`
 4. Interact with the map by zooming and panning

### Link to Demonstration

[jsbin](https://jsbin.com/lujixuvewe/1/edit?html,output)

### Expected Behavior
* The layer filter should update correctly, and the map should reflect the new filter.
* No WebGL context loss should occur, the map should function smoothly.

### Actual Behavior
* When updating the layer filter, the map loses WebGL context. 
* The map fails to render again, unless refreshed. (on multiple crashes webgl is disabled by the browser and requires a restart).

Additionally when i switch the style to `mapbox://styles/mapbox/streets-v12` i do not run into this issue.

![Screenshot 2024-09-06 at 12 10 15 pm](https://github.com/user-attachments/assets/5fe20d9b-bf9a-4460-8016-adc3d30031c3)

**Comment by stepankuzmin** [comment]
Hi @shuabrannigan,

What OS are you using? I wasn't able to reproduce it on Google Chrome 128.0.6613.138 on macOS 14.6.1.

**Comment by shuabrannigan** [comment]
Hey @stepankuzmin 

So i am running macOS 13.0.1 , i tried my jsbin again, and it happened as i described, however it take longer to fail than previously here is a screen grab of the console on failure, hopefully helpful. 

![Screenshot 2024-09-17 at 1 06 45 pm](https://github.com/user-attachments/assets/1374a77a-f85a-4d5f-b764-e94dad4080d7)

**Comment by stepankuzmin** [comment]
Thanks for more details, @shuabrannigan. Could you please also try reproducing it with the latest [v3.7.0-beta.1](https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.7.0-beta.1)?

**Comment by shuabrannigan** [comment]
@stepankuzmin okay here is an update, i did not lose context using that beta in my jsbin from the brief test I did. here is the updated code [jsbin](https://jsbin.com/samoyoxare/edit?html,console,output)

i did get the following messages in the console

![Screenshot 2024-09-18 at 8 01 49 am](https://github.com/user-attachments/assets/1caf1c06-0fc0-4cb6-9161-d505bd1a88f4)

but nothing killed the map, so issue seems resolved?

**Comment by stepankuzmin** [comment]
Yeah, it appears that the root cause was fixed. The messages in the console are unrelated to the GL JS itself, so I'm considering this issue was fixed. Thanks!
