### ISSUE TITLE
Fix text rendering v8 test suite failures

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1327]
Presently, in the v8 branch, text is being rendered in the browser but not in `mapbox-gl-test-suite`. All `mapbox-gl-test-suite` text tests are failing because nothing is rendered.

![screen shot 2015-06-24 at 5 27 58 pm](https://cloud.githubusercontent.com/assets/281306/8344442/932989a4-1a96-11e5-854f-daa8bf43f212.png)

The full console output of `mapbox-gl-test-suite` is available at https://gist.github.com/lucaswoj/98c31aaf3a7f1c77abb0

**Comment by jfirebaugh** [comment]
@ansis Can you look at this?

**Comment by lucaswoj** [comment]
This is also causing the `icon-*` test suite failures.

**Comment by ansis** [comment]
I started looking into this today but no progress so far.
