### ISSUE TITLE
Fail with vue 3.5.3 and nuxt 3.13.1

### ISSUE THREAD

**Issue by agracia-foticos** [mapbox/mapbox-gl-js#13277]
https://github.com/AlexLavoie42/Nuxt-Mapbox/issues/117

**mapbox-gl-js version**:

**browser**:
Chrome

### Link to Demonstration
(https://stackblitz.com/edit/nuxt-starter-bb51pv)

**Comment by stepankuzmin** [comment]
Hi @agracia-foticos,

I don't know if that is related to the GL JS, and it seems like a Nuxt wrapper issue, so I'm going to close this. If it's still relevant, please comment with the small reproducible example so we can verify the issue.
