### ISSUE TITLE
Can I write my own ISource without forking mapbox-gl-js?

### ISSUE THREAD

**Issue by dzfranklin** [mapbox/mapbox-gl-js#13282]
**mapbox-gl-js version**: 3.6.0

### Question

My ultimate goal is to render epsg:27700 tiles as a mapbox-gl layer.

OpenLayers provides [a function](https://github.com/openlayers/openlayers/blob/fe8a258a472205dd0364f1b9c697260a067445a3/src/ol/reproj.js#L212) that essentially takes a tile source and a target tile extents and projection and returns a canvas of the target tile reprojected from source tile(s).

I could implement this as a custom layer but I think it fits much better as an [`ISource`](https://github.com/mapbox/mapbox-gl-js/blob/7f1051753f2a0cbf817d098a9ce057cb927b522c/src/source/source.ts#L70). I want to write something like your [`RasterTileSource`](https://github.com/mapbox/mapbox-gl-js/blob/7f1051753f2a0cbf817d098a9ce057cb927b522c/src/source/raster_tile_source.ts#L46) except the loadTile function would also do reprojection.

If I wrote a custom layer I think I would need to figure out things like when to load or abort loading tiles based on map interactions whereas if I could write an ISource your existing code would handle all that.

The documentation for `ISource` hints at this being possible: "The `Source` interface must be implemented by each source type, including "core" types like `vector`, `raster`,  or `video`) and all custom, third-party types". However, I can't figure out how to do this in practice.

- style.addSource constructs the source via [a static map of source type to implementation](https://github.com/mapbox/mapbox-gl-js/blob/7f1051753f2a0cbf817d098a9ce057cb927b522c/src/source/source.ts#L129) in ISource
- ISource (recursively through Evented) contains a bunch of internal logic so I would want to have my class extend it rather than rewrite all the code needed to conform to the interface. But it isn't exported so I can't access it from an external project.

This makes me think I would have to fork mapbox-gl-js and make a few trivial changes to get a custom ISource to work. Is there a better way to do this?

### Links to related documentation

- The internal docs of ISource (mentioned above): https://github.com/mapbox/mapbox-gl-js/blob/7f1051753f2a0cbf817d098a9ce057cb927b522c/src/source/source.ts#L70
- https://docs.mapbox.com/style-spec/reference/sources/

**Comment by KERERCVASD** [comment]
download
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by dzfranklin** [comment]
For other who run into this you can do this with maplibre via addProtocol
