### ISSUE TITLE
Fix line-dasharray rendering v8 test suite failures

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1328]
![screen shot 2015-06-24 at 5 38 13 pm](https://cloud.githubusercontent.com/assets/281306/8344544/ddf6a560-1a97-11e5-9baf-c236e89fff4f.png)
![screen shot 2015-06-24 at 5 38 21 pm](https://cloud.githubusercontent.com/assets/281306/8344545/ddf7f460-1a97-11e5-9098-88506aa110f5.png)

 - line-dasharray literal
 - line-dasharray constant
 - line-dasharray array-constant
 - line-dasharray function
 - line-dasharray overscaled

**Comment by ansis** [comment]
fixed by 5050915676ae731ab74979575e630a37732ed076
