### ISSUE TITLE
`map.addImport` causes infinite recursion when loading cached Mapbox Satellite style

### ISSUE THREAD

**Issue by vcoppe** [mapbox/mapbox-gl-js#13295]
**mapbox-gl-js version**: 3.7.0

**browser**: tested with Firefox and Chrome

### Steps to Trigger Behavior

 1. Create a map with an empty style.
 2. Add the Mapbox Satellite style with `map.addImport`
 3. Remove it with `map.removeImport`
 4. Add it back with `map.addImport`

### Link to Demonstration

https://jsbin.com/holuzah/edit?html,css,js,output

### Expected Behavior

Import is added without error, like in the first call.

### Actual Behavior

`Uncaught RangeError: Maximum call stack size exceeded`

### Investigation

The error originates from the line below, because the object it tries to clone has a self-reference in it.

https://github.com/mapbox/mapbox-gl-js/blob/732345f70d61bdf10412e2ad62cbfb1af58259f8/src/style/style.ts#L706

The self reference is the following:
```
{
   sources: {
      mapbox-satellite: {
         data: {
            data: ...
         }
      }
   }
}
```

This self-reference is obviously not in the original style. I suspect it is added by the following line, when the style is loaded for the first time.

https://github.com/mapbox/mapbox-gl-js/blob/732345f70d61bdf10412e2ad62cbfb1af58259f8/src/style/style.ts#L1275

**Comment by underoot** [comment]
Thank you @vcoppe for your contribution! The issue was fixed in f5dd2374ba15df4bd83bcc6afbb71e65505bb146 and was released in [3.8.0-beta.1](https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.8.0-beta.1) and also will come in the upcoming stable release. Feel free to re-open it if you still able to reproduce it
