### ISSUE TITLE
thoughts on packing data driven properties closer together

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1334]
I'm not sure how much any of this matters since we haven't yet seen how often the smaller data driven properties get used. Just dumping my thoughts.

The values of paint properties are now stored in the buffers if they are data driven. Each paint property attribute is currently aligned with a 4 byte boundary. Even if the property is just a single byte it will [take up 4 bytes](https://github.com/mapbox/mapbox-gl-js/blob/6eaa167d4febd9adc9d342c2c78134d6caf1a4ec/js/data/line_bucket.js#L56) in the buffer. This is recommended: https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/TechniquesforWorkingwithVertexData/TechniquesforWorkingwithVertexData.html#//apple_ref/doc/uid/TP40008793-CH107-SW7
and https://github.com/mapbox/mapbox-gl-native/pull/590

3 empty bytes is bad too. It might be worse.

Multiple attributes can sometimes be packed into a single attribute and then unpacked in the shader.
For example, `extrude` and `linesofar` are packed into a single `vec4 a_data` attribute in the line sdf shader: https://github.com/mapbox/mapbox-gl-js/blob/37145b8b9bb0de022811ad46f3e89a2714896b18/shaders/linesdfpattern.vertex.glsl#L34-L35

We can't do this for paint properties like `line-width` and `line-opacity` because one may be zoom dependent while the other may be data driven.

If we implement renderer support for functions that are both zoom and data driven then we can pack these properties together.

@lucaswoj @kkaefer @jfirebaugh 

I'm closing this immediately because I don't think there is anything actionable yet.

**Comment by lucaswoj** [comment]
I'd love to do some experiments on this if/when I land #1318.
