### ISSUE TITLE
Mapbox Tiles Displaying Outdated Data Compared to OpenStreetMap

### ISSUE THREAD

**Issue by ali-ramazani** [mapbox/mapbox-gl-js#13357]
I'm trying to build a map of my college. It recently came to my attention that the map displays old data. For example, a building called "Communication" was demolished and, in its place, a new building called "Tech Building 1" is built. However, the style I'm using (and every other style) 'mapbox://styles/mapbox/streets-v11' displays "Communication Building" instead of "CMIT". When I click on Improve this Map, the map information is accurate. 

This is what it shows Mapbox.
![image](https://github.com/user-attachments/assets/5d3c7892-9e13-4920-b30f-617c27999ba2)

This is the correct building name on the Open Street Map the "improve this map" references.
![image](https://github.com/user-attachments/assets/1987eb9d-c06c-4fa3-ab3d-6fde08914f25)

I would appreciate it if you could help me fix/get around this.

**Comment by david-buck** [comment]
If you don't want to override the building name yourself, you can report it to Mapbox. The data being accurate in OpenStreetMap helps for this. I've done it before and the Mapbox team were responsive.

https://www.mapbox.com/contribute/

If you don't mind editing your style in studio you can apply this change to the poi-label text field rules

from

```
[
  "coalesce",
  ["get", "name_en"],
  ["get", "name"]
]
```

to

```
[
  "case",
  ["all",
    ["==", ["get", "name"], "Communication"],
    ["==", ["get", "class"], "education"]
  ],
  "Tech Building 1",
 ["coalesce", ["get", "name_en"], ["get", "name"]]
]
```

<img width="1155" alt="image" src="https://github.com/user-attachments/assets/37b91048-7684-4101-b8a8-3c1e8d1802f8" />

**Comment by underoot** [comment]
Hi, @ali-ramazani! Thank you for your request! I've passed information to our data team. In the next time please submit your request about data through "Improve the map" request anyway!

**Comment by underoot** [comment]
Data has been updated, thank you!

**Comment by ali-ramazani** [comment]
Thank you, David Buck, for your suggestion.

And @underoot, thank you for passing the information/request to your data team. The issue is solved now. I did try "Improve this map", but it included new information, so there was nothing for me to improve. It was more of an inconsistency between the maps.
