### ISSUE TITLE
QueryRenderedFeatures exception after upgrade to 3.9.0, with no other code changes 

### ISSUE THREAD

**Issue by jaybo** [mapbox/mapbox-gl-js#13365]
**mapbox-gl-js version**: 3.9.0

**browser**: Chrome 131.0.6778.140

### Steps to Trigger Behavior

 1. Upgrade existing project from 3.8.0 to 3.9.0.  *No other code changes.*
 2. QueryRenderedFeatures always gives exception when clicking on the map
 ```
clickAndTapProcessing:  TypeError: Cannot read properties of undefined (reading 'id')
    at a2 (:22399:70)
    at xo.queryRenderedFeatures (:22409:51)
    at Map.queryRenderedFeatures (:28754:37)
    at Editor.processClickedIcon (c:\GitHub\dzweb\ClientApp\src\modules\editor.ts:334:33)
    at Editor.clickAndTapProcessing (c:\GitHub\dzweb\ClientApp\src\modules\editor.ts:316:34)
    at Map.<anonymous> (c:\GitHub\dzweb\ClientApp\src\modules\editor.ts:268:22)
    at Map.fire (:1838:39)
    at i2.fire (:626:103)
    at ln.mouseup (:26688:23)
    at Zn.handleEvent (https://localhost:44346/node_modules/.q-cache/dev-spa/vite-spa/deps/mapbox-gl.js?v=6e707186:27562:108) {stack: 'TypeError: Cannot read properties of undefine…e-spa/deps/mapbox-gl.js?v=6e707186:27562:108)', message: "Cannot read properties of undefined (reading 'id')"}
```

Here are the first few lines of my calling code `processClickedIcon`
```
    processClickedIcon(e): boolean {
        if (!this.map || !this.draw) return false;
        let used = false;
        const bboxXY2 = 5;
        const bbox: [PointLike, PointLike] = [
            [e.point.x - bboxXY2, e.point.y - bboxXY2],
            [e.point.x + bboxXY2, e.point.y + bboxXY2],
        ];
        let features = this.map.queryRenderedFeatures(bbox);
```
The exception happens when referencing `t3.id`:
```
 queryRenderedFeatures(t2, i2, o2) {
            let s2;
            i2 && !Array.isArray(i2) && i2.filter && (this._validate(Se, "queryRenderedFeatures.filter", i2.filter, null, i2), s2 = e.aY(i2.filter));
            const r2 = {}, a2 = (e2) => {
              if (go.has(e2.type)) return;
              *const t3 = this.getOwnLayerSourceCache(e2), i3 = r2[t3.id] = r2[t3.id] || { sourceCache: t3, layers: {}, has3DLayers: false };*
```
 4. My project uses a branch of mapbox-draw from about a year ago.  It also uses many layers including custom layers.  It has undergone many years worth of upgrades to mapboxgl-js without issue.  See  https://www.deepzoom.com 
 5. I saw the release note "Rename featureset property to target in addInteraction and queryRenderedFeatures options." but I'm not referencing `featureset` anywhere.

### Link to Demonstration
https://codepen.io/jaybonomad/pen/QwLvjBO
Sorry, I can't repo in a simple project yet.

https://jsbin.com/

### Expected Behavior
Should not give exception.
### Actual Behavior
Gives exception.

**Comment by joshnice** [comment]
Yeah I am experiencing the same thing. I had just upgraded from 2.15 to 3.8 and was all working well. After upgrading to 3.9 I seem to get a console error on every mouse move (We do query the map on every mouse move).

I can produce a minimal example if needed.

**Comment by jaybo** [comment]
I'm sure a minimal example would be welcome, since I haven't figure out how to make one.  Are you using draw?

**Comment by joshnice** [comment]
Just figured it out. It is when there is a custom layer type on the map.

In the example I am using deckgl which adds layers of type "custom" to the map and when you move the cursor on the map you can see the error being thrown in the console.

https://jsbin.com/muyicec/edit?html,console,output

**Comment by mourner** [comment]
Thanks for the report and the test case! We'll try to make a patch for this shortly.

**Comment by mourner** [comment]
Should be fixed in https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.9.1
