### ISSUE TITLE
Allow each edge to have different padding when fitting to bounds

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#1339]
[`Camera.prototype.fitBounds()`](https://github.com/mapbox/mapbox-gl-js/blob/37145b8b9bb0de022811ad46f3e89a2714896b18/js/ui/camera.js#L345) accepts `padding` and `offset` options for adding slop area (in pixels) around the fitted bounds. In mapbox/mapbox-gl-native#1783, I’m instead allowing each side of the bounds to have a different padding amount. It would be great to have this in gl-js as well.

Independent edge padding is necessary on iOS, because it’s customary to include about 32 points of top padding to make room for a translucent top bar overlay. In gl-js, it isn’t possible to express this behavior with a combination of `padding` and `offset`: you don’t want any padding to be added in the horizontal direction.

**Comment by jfirebaugh** [comment]
Added in #1675.

**Comment by benmcginnis** [comment]
Any chance of this happening?

**Comment by mohsen1** [comment]
This is blocking us from using MapBox GL. I submitted https://github.com/mapbox/mapbox-gl-js/pull/3876 to resolve another blocker :)

**Comment by mollymerp** [comment]
@benjamintd @mohsen1 picking this up today -- I'll see what we can do!

**Comment by andrewharvey** [comment]
https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/ is a good example of how it could be used. So that the fitBounds for the route ensure that the route fills the space to the right of the controls/instructions.
