### ISSUE TITLE
A smarter setStyle()

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#1341]
Calling `map.setStyle()` currently throws away the current style. For minor style changes, this not only wastes resources, but causes the map to flash as the new context is built up and re-rendered.

Instead of performing a full reload, `setStyle()` should diff the new stylesheet with the current styles, and incrementally update the current styles. This incremental update should occur in a batch mode, as individual mutation calls preform significant work to flush and recreate state that is wasted when immediately followed by another mutation.

- [ ] get current map style as an exportable stylesheet (plain JS object)
- [ ] semantically aware stylesheet diff utility
- [x] batch mode for efficient application of multiple mutations
- [ ] replace current `setStyle()` with new `smartSetStyle()`

**Comment by anandthakker** [comment]
This is excellent.

FWIW, I'd also love for the batching to be available through the public API (not only behind `setStyle`), so that, e.g., I could group dynamic updates without having to keep track of my own style JSON object.

**Comment by scothis** [comment]
@anandthakker there's a batch method on Map now as well.

**Comment by anandthakker** [comment]
@scothis :dancers: !

**Comment by jfirebaugh** [comment]
Followups in #1391.
