### ISSUE TITLE
Label rendering glitches

### ISSUE THREAD

**Issue by lmcd** [mapbox/mapbox-gl-js#1344]
I have a custom build of `mapbox-gl-js` which has been modified to render to an off-screen framebuffer, which can then be reused as a texture inside a bigger WebGL project. I don't have this fork public yet (but plan to shortly).

I've run into a problem getting labels to render, and they're currently showing up like this:

![screen shot 2015-06-27 at 00 36 33](https://cloud.githubusercontent.com/assets/363540/8389206/89e4219a-1c64-11e5-87fe-097322be862c.png)

I haven't dug deep enough to figure out why this is happening, and was wondering if anyone can tell off the bat what might be going wrong here?

**Comment by peterqliu** [comment]
@lmcd what does your style json look like (especially for those label layers)?

**Comment by lmcd** [comment]
It's `https://www.mapbox.com/mapbox-gl-styles/styles/outdoors-v7.json`

**Comment by bsudekum** [comment]
related: https://github.com/mapbox/mapbox-gl-native/issues/1773

**Comment by lmcd** [comment]
Fixed. The blocks were due to some fiddling where I accidentally disabled the texture that was being sampled by the SDF shader causing the blocks.

The labels then appeared invisible, due to the glyph atlas texture being upside down. This is because my application is setting `gl.UNPACK_FLIP_Y_WEBGL` to `true` and Mapbox isn't resetting this state when updating textures.
