### ISSUE TITLE
Strange artifacts at coordinates [50, 5]

### ISSUE THREAD

**Issue by vespakoen** [mapbox/mapbox-gl-js#1346]
Hey there, I coincidentally stumbled upon a couple of roads and a poi at the coordinates [50, 5], (actually a bit north east to it)
I guess it might be worth investigating how they ended up there (probably just a problem in the data, not the logic, but who knows...)

Have a nice sunday!

**Comment by vespakoen** [comment]
**UPDATE**: turns out it is not at [50, 5] but at [0, 0].
That actually makes more sense and points the meter into the direction of a data problem, but still worth investigating I guess?

**Comment by 1ec5** [comment]
If it’s at (0, 0), aka [Null Island](https://en.wikipedia.org/wiki/Null_Island), it’s an issue with OpenStreetMap data. This area tends to accumulate test edits and such on OSM.

The artifacts should be gone now – do you still see them? If you encounter them in the future, you’re welcome to [delete them from OSM yourself](http://www.openstreetmap.org/#map=14/0/0); Mapbox Streets should reflect your corrections within a few minutes.

**Comment by vespakoen** [comment]
Awesome, didn't know about the Null island =) thanks!
