### ISSUE TITLE
Move all data driven style calculations for paint properties out of the worker 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1350]
Going down the rabbit hole of #1343 and https://github.com/mapbox/mapbox-gl-test-suite/issues/29, we've come to realize that [calculating data driven paint properties in the worker](https://github.com/mapbox/mapbox-gl-js/blob/v8/js/data/circle_bucket.js#L121) is causing some trouble with classes and transitions.

The [GL style spec documentation says](https://www.mapbox.com/mapbox-gl-style-spec/#background):
 > Layout properties appear in the layer's "layout" object. They are applied early in the rendering process and define how data for that layer is passed to the GPU. For efficiency, a layer can share layout properties with another layer via the "ref" layer property, and should do so where possible. This will decrease processing time and allow the two layers will share GPU memory and other resources associated with the layer.
 > 
 > Paint properties are applied later in the rendering process. A layer that shares layout properties with another layer can have independent paint properties. Paint properties appear in the layer's "paint" object. Layers can also have class-specific paint properties, which are applied only when the map has a certain class name set. For example, a layer with a "paint.night" property would have those properties applied when the map has the "night" class set.

In the short term, we should move all data driven style calculations for paint properties out of the worker and into the `draw_*` functions. 

We already [mutate the buffer in the draw_* functions](https://github.com/mapbox/mapbox-gl-js/commit/48050a042648781c5d22642e58b1dca4d724e1c7), so this isn't too much of a stretch. But it will require some care pass the right values into `draw_*` and to avoid too much duplicated logic with `*_bucket`

Thoughts @ansis?

cc @jfirebaugh @ansis

**Comment by ansis** [comment]
I think we should punt on transitions for data driven properties: https://github.com/mapbox/mapbox-gl-js/issues/1343#issuecomment-117176993

It could be useful to try to implement hover styles and transitions first. We'll need to update the buffers on the cpu for that and it could give us ideas.

**Comment by lucaswoj** [comment]
### Next Steps

 - [ ] implement calculating all paint property data driven style values in the `draw_*` method
 - [ ] explore calculating paint property data drivel style values in the shader 

(punt on transitions, though this should lay the groundwork for general layer transitions as well has hover state transitions)

**Comment by lucaswoj** [comment]
This is blocking mapbox/mapbox-gl-test-suite#29 because paint classes do not work with data driven styles.

**Comment by lucaswoj** [comment]
Blocked on #1318

**Comment by lucaswoj** [comment]
Stale
