### ISSUE TITLE
addlayer() does not redraw viewed tiles?

### ISSUE THREAD

**Issue by lawrence-n** [mapbox/mapbox-gl-js#1355]
In v0.8.1 it seems that when I call map.addlayer() the tiles that have already been rendered are not updated. The new layer will appear when I zoom or pan to a section of the map that has not been viewed yet. This may potentially be because I am reusing a source e.g. to highlight a selection.

https://jsfiddle.net/2h5Luaje/

![image](https://cloud.githubusercontent.com/assets/13115853/8446352/ae715bac-1fdb-11e5-9173-65f89c34839f.png)

**Comment by scothis** [comment]
@lawrence-n this is fixed on master. Can you give that branch a spin?

**Comment by lawrence-n** [comment]
Thanks Scott, master works as expected.
