### ISSUE TITLE
Move from /v4/fontstack to /glyphs/v1

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-js#1358]
Kinda blocked by https://github.com/mapbox/mapbox-gl-style-spec/issues/309 and https://github.com/mapbox/mapbox-gl-style-spec/issues/284 may be relevant as well. This will require handling "fontstack" logic on the client instead of the server-side API, and opens the path towards client-side text shaping.

> We could move the coverage logic to the client to skip requesting glyphs blocks from fonts that don't have any codepoints in a given range, and only request glyph blocks from a secondary font if the necessary glyphs are missing from the codepoints of all former fonts in the stack.

> The tradeoff here would be reducing possible filesize savings by eliminating the "fontstack" concept from the API and possibly downloading (but not adding to the atlas) glyphs from multiple fonts for a single codepoint. The upshot would be eliminating duplication in the glyph atlas, not requesting duplicate glyph PBFs in sparse ranges, and possibly increasing the cacheability of glyph PBF requests (by caching per font rather than per fontstack).

**Comment by jakepruitt** [comment]
Closed with #1385.
