### ISSUE TITLE
Use OES_vertex_array_object API when available

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1361]
https://www.khronos.org/registry/webgl/extensions/OES_vertex_array_object/

Per @ansis' comment at https://github.com/mapbox/mapbox-gl-js/pull/1356#issuecomment-118356001

Related to #1318 #1356

**Comment by kkaefer** [comment]
\o/

**Comment by jfirebaugh** [comment]
![image](https://cloud.githubusercontent.com/assets/98601/8528518/3edc8cf8-23c8-11e5-91ce-4103b0135a63.png)

From http://webglstats.com/, % relative to everyone who has WebGL support.
