### ISSUE TITLE
Set up continuous benchmarking system

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1362]
I'm not sure how we would implement this, but it'd be great to see the performance effect of each commit. 

https://github.com/travis-ci/travis-ci/issues/352

**Comment by jfirebaugh** [comment]
Related: #954.

**Comment by lucaswoj** [comment]
Related #1336

**Comment by lucaswoj** [comment]
http://karma-runner.github.io/0.13/index.html looks promising, although we'd need to ensure it was running on a machine with a real graphics card (e.g. an AWS `g2.2xlarge` instance or a physical computer left running in a Mapbox office :grimacing:)

**Comment by lucaswoj** [comment]
After a little digging it appears Karma is just smoke and mirrors around Selenium. We should use Selenium directly.

**Comment by lucaswoj** [comment]
https://github.com/tmcw/testing-webgl

**Comment by lucaswoj** [comment]
The new benchmark interface #2231 lays the groundwork for getting these tests running in an automated way. The big challenge is getting a GL-enabled WebDriver box running in the cloud somewhere. We might have to roll our own.

**Comment by mourner** [comment]
I'd suggest closing this issue. Benchmarks on CI will not be representative of real world performance, and will fluctuate randomly — there's no way to create a controlled CI benchmarking environment for GL JS unless we set up our own servers for that, and this is out of scope for the nearest term.
