### ISSUE TITLE
Getting "Uncaught Error: Invalid LatLng object: (NaN, NaN)" when zooming

### ISSUE THREAD

**Issue by hannesj** [mapbox/mapbox-gl-js#1369]
Hi, I have been getting the following exception when using map#easeTo, and not providing a zoom value to it, and when the map has just been zoomed.

    Uncaught Error: Invalid LatLng object: (NaN, NaN)
    LatLng @ lat_lng.js:19
    20.Transform.coordinateLocation @ transform.js:220
    20.Transform.pointLocation @ transform.js:193
    74.util.extend.easeTo @ camera.js:453
    (anonymous function) @ VM567 navigation-map.cjsx:100

It appears to be due to the division in camera.js:453, when scale is 1, and thus the point becoming (-Infinity, -Infinity)

**Comment by mourner** [comment]
Thanks! Will look into it.

**Comment by mourner** [comment]
Can't reproduce this anymore, it may have been fixed. That line can't execute when there's no zoom because of the `if (this.zooming)` condition.

**Comment by hannesj** [comment]
Hi @mourner, It seems that this.zooming is true, if you call the easeTo within 200ms zoomTo. This is due to zoomTo always taking at least 200ms as specified [here](https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/camera.js#L181-L187)
