### ISSUE TITLE
Cannot query data from vector tiles

### ISSUE THREAD

**Issue by vespakoen** [mapbox/mapbox-gl-js#1373]
Hey,

It looks like it is impossible to query features on a **vector tile** via `map.featuresAt`.
Is this correct?

If so, is there another way I can get the features from vector tiles via the mapbox-gl-js api?

I am already trying to load the tile from cache and parse it myself (with pbf & vector-tile) but I am guessing there is a better way =)

**Comment by vicapow** [comment]
Sounds like you forgot to set the layer to interactive.

**Comment by vespakoen** [comment]
That did it! Thanks!

**Comment by kelvinabrokwa** [comment]
@vicapow you just saved me a bunch of pointless debugging in [gl-draw](https://github.com/mapbox/gl-draw). Thanks man! :sunglasses:

**Comment by vicapow** [comment]
@kelvinabrokwa glad to help!
