### ISSUE TITLE
Provide a way to set/get default transition {duration,delay} in style properties

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-js#1379]
As per discussion in mapbox/mapbox-gl-native#302, we should provide a way to set the default transition `duration` and `delay` values. Currently they seem to be hardcoded (as per changes related to #447).

/cc @incanus @tmcw @mourner @edenh

**Comment by jfirebaugh** [comment]
There's already a style spec property for this -- https://www.mapbox.com/mapbox-gl-style-spec/#transition. Not sure about the current level of support for it though.

**Comment by lucaswoj** [comment]
☝️
