### ISSUE TITLE
Halo color always has an effect on rendering, even if halo-width: 0

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1381]
<img width="65" alt="2015-07-20 at 4 03 pm" src="https://cloud.githubusercontent.com/assets/32314/8785882/d0639870-2ef8-11e5-91b7-f50c798d67dd.png">

Even with halo-width: 0 and halo-blur: 0, a red-colored halo has an effect on text rendering, tinting the antialiased edges of the text that color.

Is this by design, or could halo-width remove the effect of the color entirely?

**Comment by samanpwbb** [comment]
If halo is always present, the default should match the text color (same way that that `fill-outline-color` matches fill color). Right now the default is `rgba(0, 0, 0, 0)`, which leads to awkwardness when user is trying to clear
