### ISSUE TITLE
featuresAt only works reliably on maxZoom

### ISSUE THREAD

**Issue by Schwanksta** [mapbox/mapbox-gl-js#1383]
I have a polygon/fill layer I ran through tippecanoe. I'm using the latest (0.8.1) Mapbox GL JS. I set interactive: true, and set up a base featuresAt handler:

```javascript
map.on('mousemove', function(e) {
  map.featuresAt(e.point, {radius: 10}, function(err, features) {
      if (err) throw err;

    if(features.length > 0) {
        $("#flag").html(features[0].properties.name + ": "+ Math.round(features[0].properties.pct_renters)+"%");
    } else {
        $("#flag").html("");
    }
  });
});
```

The bizarre thing is that it works somewhat sporadically at lower zooms, but appears to be 100% reliable at zoom 14, which are the highest tiles I have. I made a gif to demonstrate:

![featuresat](https://cloud.githubusercontent.com/assets/20067/8824378/14bb729a-3043-11e5-8bd6-1b5808efde0a.gif)

**Comment by mourner** [comment]
Yeah, should be fixed by #1530.
