### ISSUE TITLE
Include setClasses, addClass, etc. in batch()

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#1384]
Looks like the class mutation operations all prompt a style cascade.  It would be nice to expose this within a `batch` to avoid having to cascade twice if I'm both updating styles and changing a class.

Happy to submit a PR if yall are :+1:

**Comment by jfirebaugh** [comment]
We've decided that the active set of classes is a property of the map, rather than the style, and the existing batch API deals only with style properties, so this seems slightly awkward. But if it can be done without introducing too much complexity, I'm open to it.

**Comment by ansis** [comment]
@mourner now that you have batching fresh in your mind, how hard do you think it would be to add this?

**Comment by mourner** [comment]
Good point! It's very easy to do now. I'll take this.
