### ISSUE TITLE
Change glyphs URL from /v4/fontstack to /fonts/v1

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/mapbox-gl-js#1385]
In order to unblock people on the team, update gl-js to use the `/fonts/v1` endpoint rather than the `/v4/fontstack`. This would allow users to upload their own fonts.

I do not know if this requires a major change in the style-spec. At the moment, the `glyphs` property in the stylespec is in the format:

```
"glyphs": "mapbox://fontstack/{fontstack}/{range}.pbf"
```

which does not have a user id in it. The glyph property of the style will have to eventually map to the `/fonts/v1` endpoint with the format:

```
GET /fonts/v1/:owner/:face[,:face,:face...]/:start-:end.pbf
```

Is it possible to implicitly determine the owner within the gl-js code? cc/ @kkaefer @mikemorris @jfirebaugh @yhahn @tmcw

**Comment by jakepruitt** [comment]
After talking with @yhahn, it seems like you must choose between changing the style spec or parsing the user from the `access_token`. In order to get /app moving forward, I'm going to make a deal with the devil and parse the user from the access token and use that user in the request.

This will not be permanent, and future changes to the font functionality will make more intelligent decisions, and most likely change the style-spec for glyphs.

**Comment by mikemorris** [comment]
Refs https://github.com/mapbox/mapbox-gl-style-spec/issues/309

**Comment by jakepruitt** [comment]
Added conditional logic to only add `v4` for urls that start with `fontstack`. This allows the `font` endpoint to be used in the `mapbox://` url.
