### ISSUE TITLE
v0.8.2 release

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/mapbox-gl-js#1392]
Would it be possible to release an updated version of mapbox-gl-js with all of the changes that have landed on master since June 16th (the day of the last release)? I would do the release myself, but I'm not sure what exactly has changed, or how the order of operations works with creating a PR or just working off master.

cc/ @kkaefer @mourner @jfirebaugh @lucaswoj

**Comment by lucaswoj** [comment]
I've never cut a release of gl-js. I can make an informed guess about how to do it but would rather wait for someone more experienced to chime in about the logistics and semantics of a release.

**Comment by mourner** [comment]
OK let me make a release tomorrow. 

> I'm not sure what exactly has changed

Usually I'm just looking through the commit log and translating it to the changelog briefly.

> how the order of operations works with creating a PR or just working off master

Just off master usually.
