### ISSUE TITLE
Get rid of user-specified refs

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1393]
So off in app land we've been doing this for a while and I finally realized it might make sense as a gl-js builtin: https://gist.github.com/tmcw/fa0f38a489fdbe9e9fb1

It's quite possible and useful to generate 'refs' automatically and fairly quickly as a pre-processing step.

The linked example ^ uses es6 and ramda and xtend and json-stable-stringify because those are available in the surrounding environment, but a port to vanilla ES5 with no libraries is definitely possible.

**Comment by lucaswoj** [comment]
Refs get a little more complicated in the context of data driven styling because there's a n-to-m mapping of GL buffers to layers. I think the only way to manage the system effectively will be to automatically assign refs (but I haven't quite gotten around to that yet).

**Comment by lucaswoj** [comment]
Quick update: no data-driven styling blockers here but I want to make this happen :+1:
