### ISSUE TITLE
Allow fonts url to work without v1 specified

### ISSUE THREAD

**Issue by jakepruitt** [mapbox/mapbox-gl-js#1394]
In order to access the user-owned fonts API from a style, the glyphs url needs to be:

```
"glyphs": "mapbox://fonts/v1/jake/{fonstack}/{range}.pbf"
```

After talking with @willwhite and @yhahn, this should not require the **v1** specification in the style, and should work with

```
"glyphs": "mapbox://fonts/jake/{fontstack}/{range}.pbf"
```

Will this require a minor version bump in gl-js and gl-native? Will it require any changes in the style-spec? Regardless of how we do it, if a new style is used with an old client, the fonts will not appear. So rolling this change out will mean that wee need to push the newest version of the client to everyone.

cc/ @tmcw @kkaefer @mourner @edenh @samanpwbb

**Comment by jfirebaugh** [comment]
Hashing this out in https://github.com/mapbox/mapbox-gl-style-spec/issues/309 first.
