### ISSUE TITLE
Marker labels not showing anymore

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1398]
Ajax loading of mapbox label fonts fails, therefore marker labels are not shown anymore.
This is the request that fails with a 504 error: (I removed my access token at the end)
http://a.tiles.mapbox.com/v4/fontstack/Open%20Sans%20Semibold,%20Arial%20Unicode%20MS%20Bold/0-255.pbf

**Comment by mourner** [comment]
Can you set up a JSFiddle test case?

**Comment by misterfresh** [comment]
This is the error message : " No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mytestsite.com' is therefore not allowed access. The response had HTTP status code 504. " 

Regular web pages can use the XMLHttpRequest object to send and receive data from remote servers, but they're limited by the same origin policy. The problem seems to be that mytestsite.com is calling for the fonts on mapbox.com. But the maptiles load fine.

Do you have an example fiddle that I could edit, based on the Geojson Markers example https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/ ? I wasn't able to get mapbox to work in jsfiddle.

**Comment by misterfresh** [comment]
Now the 0-255.pbf works, the 256-511.pbf fails.
When I load the request directly in the browser, I get the following page : 

ERROR
The request could not be satisfied.
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.

Generated by cloudfront (CloudFront)
Request ID: GOCR9TR_u3z4fxHxVJxEaygSdq6zIhc_HE_F_ZT7J3TKy9u3RZkrHg==   

(this is for url "http://a.tiles.mapbox.com/v4/fontstack/Open%20Sans%20Regular,%20Arial%20Unicode%20MS%20Regular,%20Arial%20Unicode%20MS%20Bold/256-511.pbf?access_token=pk.eyJ1IjoibWlzdGVyZnJlc2giLCJhIjoiYlFEbUhkYyJ9.zW0qmGPMmZsKPmmPwz2F1w")

**Comment by mourner** [comment]
cc @jakepruitt not sure what's going on here

**Comment by jakepruitt** [comment]
Thanks for catching this, @misterfresh, I'll look into this right away.

**Comment by jakepruitt** [comment]
@misterfresh, thanks for catching this and giving us such good detail. We just deployed a fix, let us know if you have any more issues!

**Comment by lonnblad** [comment]
@jakepruitt I have a similar issue, we are running mapbox inside an angular app and it seems like we get a 301 Moved Permanently without the CORS headers so angular does not redirect when we try to get the fonts.

**Comment by jakepruitt** [comment]
Hello @lonnblad, 301 is interesting, do you have a sample test request that I could use?

**Comment by jfirebaugh** [comment]
Hi @lonnblad, we investigated this and it looks like it's an unintended result of a recent change on our API backend. We're going to roll back that change shortly. If you need an immediate workaround, you can do one of the following:

* In mapbox-gl-js 0.9.0, set `mapboxgl.config.FORCE_HTTPS = true`
* Upgrade to mapbox-gl-js 0.10.0 (this version removes `mapboxgl.config.FORCE_HTTPS` and always uses https)

Sorry for the disruption!
