### ISSUE TITLE
dezalgo

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1400]
Not necessarily the library, but the technique: http://blog.izs.me/post/59142742143/designing-apis-for-asynchrony

https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/evented.js

While mapbox-gl-js has "events", they fire synchronously when things happen: this is rather unexpected in some cases, and destructive in others. I think we should [minimally ensure that all events happen in the next tick rather than sync](https://github.com/npm/dezalgo).

**Comment by scothis** [comment]
:+1:

**Comment by jfirebaugh** [comment]
Which callbacks / events are you referring to specifically?

I don't think that any changes to when events like `dblclick`, `load`, `mousemove`, etc. are warranted. "Dezalgo" is about stuff like `maybeAsync(args, function(err, cb) { ... })`, not about eventing APIs. Calling `foo.on('event', function() {... })` does not immediately trigger the callback, so they don't release zalgo.

**Comment by tmcw** [comment]
@jfirebaugh specifically events that happen when you manipulate map state with APIs and then get event notifications of that state being manipulated. For instance:

```js
var sync = false;
map.on('move', function() { sync = true; });
map.setView(...);
// sync = true here.
```

**Comment by jfirebaugh** [comment]
Yeah, I'm pretty skeptical about changing that. Leaflet, for instance, does not behave that way.

Is there prior art for this behavior? What specifically would it accomplish?
