### ISSUE TITLE
Differentiate between left click and right click as map events?

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1405]
Is it possible to fire different events based on whether the click on the map is a right click or a left click?

**Comment by tmcw** [comment]
The `click` event includes an `originalEvent` member, which has the same `button` property as [the native DOM event](https://developer.mozilla.org/en-US/docs/Web/Events/click). You can differentiate on this property with a basic if/else and fire other events as you choose.

**Comment by misterfresh** [comment]
Thanks!

**Comment by enjalot** [comment]
I noticed that the right click is actually captured by `contextmenu` and not included in the `click` event now. Googling led me here, so I figured I'd leave a comment for the next person

**Comment by bhousel** [comment]
> I noticed that the right click is actually captured by contextmenu and not included in the click event now. Googling led me here, so I figured I'd leave a comment for the next person

You're right - that's a bug.. We should continue to fire `click` events for right button.
