### ISSUE TITLE
Remove data-driven styling features from the v8 branch

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1406]
What is involved here? Unless #1336 becomes a huge blocker, we can probably leave some parts of data-driven styling in v8, given that `gl-style-spec` will reject any use of data-driven styling functions. 

Ref https://github.com/mapbox/mapbox-gl-style-spec/issues/322

**Comment by jfirebaugh** [comment]
I don't want to take on the performance risk of #1336 right now. Lets rewind the v8 branch to 83b3b57187954dc655d2b30a2e62fba661661d56 or so and then cherry pick any subsequent fixes that were not related to DDS.

**Comment by lucaswoj** [comment]
Fair. I'll work through that tomorrow.

If we are going that route, then we might as well revert to `mapbox-gl-function` 1.0.0 at the same time. (re: https://github.com/mapbox/mapbox-gl-function/pull/8)

**Comment by jfirebaugh** [comment]
This is finished.
