### ISSUE TITLE
Allow arbitrarily many glyphs and sprites to be used in a style

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#141]
In areas that have a lot of distinct glyphs (e.g. Akihabara, Tokyo), we're pushing the limits of the glyph atlas because not all glyphs fit into one texture.

**Comment by ansis** [comment]
We're using a two bytes to store texture coordinates. With the current 1024 texture we round coordinates to the nearest 4px. For bigger textures either we need to use more space for texture coordinates or we need to round to 8px.

We could have multiple texture atlases and put glyphs in different buffers based on which atlas they are using. This could get annoying.

Or we could just make separate glyph atlases for each fontstack. This could give us enough breathing room to avoid implementing resizing.

**Comment by kkaefer** [comment]
Another optimization we could use is to optimize our font stacks. Contention for the texture space is only happening in areas with many glyphs, in particular Asian countries. However, in those areas, we're typically using either Arial Unicode MS or the Bold version thereof. Unfortunately, these are currently encoded as distinct glyphs for every font stack so that it's likely that we have the exact same glyph multiple times in our atlas.

**Comment by ansis** [comment]
an example style that hit the sprite atlas limit because of large fill patterns: https://github.com/mapbox/mapbox-gl-js/issues/1633

besides implementing resizing we could:
- use separate textures for fill patterns (but this would break data driven fill patterns later on)
- use a larger default size 1024x1024 instead of the current 512x512

**Comment by bhousel** [comment]
Hey @ansis I have this mostly working in the `glyph_overflow` branch.. I'll finish it up and PR this week.

**Comment by lucaswoj** [comment]
I think the 🔥 need has been sufficiently doused by increasing the glyph atlas size that we can remove the high priority tag on this one.
