### ISSUE TITLE
Fire 'mousedown' event when clicking on map?

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1411]
map.on('mousedown', function(e) {
                console.log('mousedown');
    });
This does nothing. How can I listen to mousedown and mouseup events? (need it to drag & drop markers)

**Comment by mourner** [comment]
You're right, it doesn't fire `mousedown` and `mouseup` currently. Should be fixed for the next release.

**Comment by misterfresh** [comment]
Ok thanks
