### ISSUE TITLE
GeoJSON "Point" styled via fill+ line (ie: circle-marker)?

### ISSUE THREAD

**Issue by facultymatt** [mapbox/mapbox-gl-js#1413]
My understanding of how styling GeoJSON data works is that certain GeoJSON types are mapped to certain styles, for example: 

```
Point -> Symbol
LineString -> Line
Polygon -> Fill
```

My question is would it be possible to style a point via Fill, for example, or Line? This end goal is to achieve an effect like circlemarkers in leaflet - where you can transform a point into a circle which can have fill, weight, etc.

**Comment by tmcw** [comment]
Yep, the next version of mapbox-gl-js will include a [circle render type](https://github.com/mapbox/mapbox-gl-js/pull/1286) including radius, color, opacity, and translate properties.

**Comment by facultymatt** [comment]
Fantastic, also realized a similar effect could be achieved using Turf's buffer method.

http://turfjs.org/static/docs/module-turf_buffer.html
