### ISSUE TITLE
typo 'klass' in documentation

### ISSUE THREAD

**Issue by morganherlocker** [mapbox/mapbox-gl-js#1417]
The [API docs include multiple references](https://www.mapbox.com/mapbox-gl-js/api/#map/setclasses) to `klass` or `klasses`, where it should be `class` or `classes`.

![](https://dl.dropbox.com/s/1ngqu5kgpqf09ua/Screenshot%202015-08-10%2013.16.10.png?dl=0)
![](https://dl.dropbox.com/s/gcwg5pump5oo5yn/Screenshot%202015-08-10%2013.18.15.png?dl=0)

**Comment by tmcw** [comment]
Hmm eslint/jsdoc will yell at you if you name params differently in docs than in code. Unfortunately class-as-a-reserved word will come back in force with es6

**Comment by bhousel** [comment]
> Unfortunately class-as-a-reserved word will come back in force with es6

Closing because this..  Let's kick the habit of using `class` now.
