### ISSUE TITLE
Add render tests for layout functions

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1421]
Some of the `layout` properties are used in `js/render/*`. These properties are never evaluated. They work fine if they are constant values but break if they are functions. It's rare that these properties are functions but the spec allows it.

we should either:
- support functions for these properties
- change the spec to disallow functions for these properties
- try to stop using them outside workers. I think this might not be possible

**Comment by lucaswoj** [comment]
> support functions for these properties

That should be pretty easy, right? We just need to call `.calculate` instead of reading the definition.

**Comment by ansis** [comment]
This was implemented at some point https://github.com/mapbox/mapbox-gl-js/blob/1ceacd9c1592ecae7c9c9c7526814bc03373b7d7/js/style/style_layer.js#L194-L197

**Comment by jfirebaugh** [comment]
Do we have render tests for it?
