### ISSUE TITLE
Performance: Allow caching of mapbox-gl assets

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1424]
Loading in chrome an html page with the following :
   &lt;link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.9.0/mapbox-gl.css' rel='stylesheet' /&gt;
    &lt;script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.9.0/mapbox-gl.js' &gt; &lt; /script>
If I go to the Audits tab of the console, I have the warning:
Leverage browser caching : The following resources are missing a cache expiration. Resources that do not specify an expiration may not be cached by browsers:
mapbox-gl.css
mapbox-gl.js

**Comment by tmcw** [comment]
Is this using the hosted version of the library - loading the scripts from `https://api.tiles.mapbox.com/mapbox-gl-js/v0.9.0/mapbox-gl.js` and such?

**Comment by misterfresh** [comment]
Yes

**Comment by jfirebaugh** [comment]
@ianshward Can you give me a second pair of eyes on the CloudFront settings for these assets? The way I read it, all these assets should already have `Cache-Control: max-age=86400` on them, and I can't figure out why they don't.

**Comment by jfirebaugh** [comment]
mapbox-gl-js assets are now served with `Cache-Control: max-age=2592000` (30 days).
