### ISSUE TITLE
flyTo animation finishes after specified duration; pitch is not used

### ISSUE THREAD

**Issue by perliedman** [mapbox/mapbox-gl-js#1429]
I'm using `flyTo` method in a pretty basic example with mapbox-gl 0.9.0:

```javascript
  var map = new mapboxgl.Map({
      container: 'map', // container id
      style: 'https://www.mapbox.com/mapbox-gl-styles/styles/outdoors-v7.json', //stylesheet location
      center: [40, -74.50], // starting position
      zoom: 9 // starting zoom
    });

  map.on('style.load', function() {
    var d = 5000,
        t = new Date().getTime();
    map.flyTo({
      center: [57.736, 11.94],
      pitch: 80,
      bearing: 90,
      duration: d,
      zoom: 50
    });
    map.once('moveend', function() {
      alert('we\'re done after ' + (new Date().getTime() - t));
    });
  });
```

I find two issues:

 1. although duration is specified as 5000 milliseconds, the map very, very slowly rotates to the specified bearing, and I get the alert after 22 or 23 seconds instead of expected 5
 2. the map is not pitched at all even when the animation has finished, although specified

From the docs (https://www.mapbox.com/mapbox-gl-js/api/#map/flyto), it appears that both `duration` and `pitch` should be supported, since they are part of `CameraOptions`, but perhaps this isn't entirely true for `flyTo`?

**Comment by perliedman** [comment]
Made a jsfiddle to illustrate the issue described: http://jsfiddle.net/k8fkosxc/

**Comment by perliedman** [comment]
Figured out that my setting of `zoom` to a much higher value than `maxZoom`. However, setting `zoom` to 20, the animation still takes 10 seconds to finish (twice the provided `duration`).

**Comment by jczaplew** [comment]
I'm interested in making the `pitch` option work properly when using `flyTo` - is there anywhere that I could start to debug this or otherwise assist?

**Comment by lucaswoj** [comment]
I can confirm that this bug still exists in v0.11.3 http://jsfiddle.net/9je928c5/

@jczaplew Does `easeTo` work for your use case? That does support pitch.

**Comment by lucaswoj** [comment]
:foot-in-mouth: #1744

**Comment by lucaswoj** [comment]
As a note, there are two separate, perhaps related, bugs being discussed here: 

 - the `easeTo` bearing animation extends beyond the specified `duration` under some conditions 
 - `easeTo` does not change the pitch if other parameters are set

**Comment by lucaswoj** [comment]
> the `flyTo` bearing animation extends beyond the specified `duration` under some conditions

My mistake. `flyTo` does not accept a `duration` parameter, only `speed`. Sorry for not catching that sooner! If you require an explicit `duration`, please use `easeTo` instead. 

> `flyTo` does not change the pitch if other parameters are set

Pushing a fix for this shortly :+1:

**Comment by 1ec5** [comment]
Filed #1854 to expose a `duration` option.
