### ISSUE TITLE
Icons jumping around

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#1430]
![sprite-jumping](https://cloud.githubusercontent.com/assets/5607844/9284538/a6cf4804-42aa-11e5-9680-42c38d2c0125.gif)

**Comment by nickidlugash** [comment]
This does not appear to be an issue for retina.

**Comment by nickidlugash** [comment]
> This does not appear to be an issue for retina.

I was wrong; it's an issue for retina, too.

**Comment by ansis** [comment]
Is the gif of one long zoom? or many short zooms?

**Comment by bhousel** [comment]
This looks a lot like mapbox/mapbox-gl-native#2230

**Comment by nickidlugash** [comment]
> Is the gif of one long zoom? or many short zooms?

@ansis @bhousel Sorry, I missed this question while I was on vacation. I think it was many short zooms, but I just tested it again now and the jumping currently still happens either way.

**Comment by bhousel** [comment]
I get this on many short zooms.  It's barely noticeable on retina, but even just zooming by one click on the mousewheel, it seems like the points are placed, then the urlhash updates, and the points jump a little bit.  

Maybe after zooming, it renders, then update the url hash with dropped precision, and then fires off another render again to match what the hash says.

**Comment by incanus** [comment]
Related? https://github.com/mapbox/mapbox-gl-native/issues/2230

**Comment by jfirebaugh** [comment]
This is the effect of rasterizing icons with linear interpolation while panning or zooming, and nearest neighbor when not. It's intended to keep the icons from jumping around while the animation is in progress, and make the look sharp when it is finished. Previously: #124.

**Comment by nickidlugash** [comment]
@jfirebaugh thanks for the background. So does this mean there is nothing practical we can do to fix this, other than to re-implement sdfs?

**Comment by jfirebaugh** [comment]
It's possible there's a bug with zooming, or we could tweak the behavior for zooming to make it look better.

**Comment by ansis** [comment]
I played around with several tweaks including having [the delay](https://github.com/mapbox/mapbox-gl-js/blob/971b956670d0e89039c22618410adb0d33cd1156/js/ui/camera.js#L186) be different whether it was a trackpad zoom or a mouse zoom but I don't think it helps overall. Increasing the delay makes really slow zooming smoother, but it makes the jump more obvious in all other cases. I think the current `200` is a good balance.
