### ISSUE TITLE
unused gaussian shaders

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1434]
Right now we include, link, and compile shaders for 'gaussian' that are completely unused

https://github.com/mapbox/mapbox-gl-js/blob/master/shaders/gaussian.vertex.glsl

**Comment by tmcw** [comment]
These match the gaussian shaders in gl-native, that are also unused https://github.com/mapbox/mapbox-gl-native/search?utf8=%E2%9C%93&q=gaussian

**Comment by ansis** [comment]
removed in 2c30df8d34d5eecdaee171730ed9ed469d0a3057
