### ISSUE TITLE
Benchmark broken as it tries to load v7 styles and 0.9 requires v8

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#1436]
Trying to run the benchmark, in site.js there is a reference to:
https://www.mapbox.com/mapbox-gl-styles/styles/bright-v7.json
Which produce
```
Uncaught Error: version: expected one of [8], 7 found
```
on benchmark page 1

Should the benchmark now be between 0.8 and 0.9?

Thanks

**Comment by fnicollet** [comment]
Note that if changed manually to v8, it still crashes as this file does not exist:
https://www.mapbox.com/mapbox-gl-styles/styles/bright-v8.json
even if it exists in the mapbox-gl-styles repo:
https://github.com/mapbox/mapbox-gl-styles/blob/master/styles/bright-v8.json

Looks like the release of 0.9 wasn't sync with other mapbox projects

**Comment by jfirebaugh** [comment]
If we want to benchmark between v0.9.0 or earlier and current `master` / upcoming v0.10.0, the benchmark tool needs to:

* load v7 style for v0.9.0 and v8 style for v0.10.0
* swap coordinate order of center location depending on version

**Comment by tmcw** [comment]
Whoops, referenced the wrong issue in my PR

**Comment by fnicollet** [comment]
Hello @tmcw ,

Can this issue be re-opened? I don't believe your commit fixes the benchmark issue. I just tried it and the benchmark still crashes. 

Thanks,
