### ISSUE TITLE
Rendering broken in Microsoft Edge

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#1437]
Hello,

Here is what /debug/ looks in Microsoft Edge:
![image](https://cloud.githubusercontent.com/assets/1240481/9291270/f34b331c-43b5-11e5-9a8e-4d31d09c6b88.png)

Works fine in Internet Explorer though. Tested on Windows 10 64 bits

Not sure what is happening, if you need me to test more stuff, please ask

Fabien

**Comment by lucaswoj** [comment]
cc @csuwildcat

**Comment by csuwildcat** [comment]
@lucaswoj I have looped in the teams responsible, I will update you when we have more.

**Comment by lucaswoj** [comment]
Amazing! Thank you @csuwildcat!

**Comment by lucaswoj** [comment]
@csuwildcat any updates?

**Comment by csuwildcat** [comment]
The team is aware of these render issues and is working to address them in a future release. I am afraid I don't have a firm time frame for release though.

**Comment by lucaswoj** [comment]
Glad to hear there's movement @csuwildcat!

**Comment by BergWerkGIS** [comment]
I tried W10 and Edge 20.10240.16384.0 on a real machine now (no VM).
Contrary to my last comment https://github.com/mapbox/mapbox-gl-js/issues/930#issuecomment-146047169 is looks very good:

![w10-edge-20 10240 16384 0](https://cloud.githubusercontent.com/assets/4549888/10369706/ebe42340-6ddb-11e5-9dc7-b79c4c3f803d.jpg)

![w10-edge-20 10240 16384 0-](https://cloud.githubusercontent.com/assets/4549888/10369796/61a2fef8-6ddc-11e5-998e-1547c5899625.jpg)

**Comment by csuwildcat** [comment]
@fnicollet can you confirm what @BergWerkGIS has said using an actual Windows install vs a VM? While we'd like to ensure both are working and looking great, I would like to know which is being affected.

**Comment by BergWerkGIS** [comment]
@csuwildcat  I just checked again in the VM and strangely enough, it also looks fine in the VM today.
Don't know, maybe yesterday was just a bad day looking at GL stuff :smirk:

**Comment by csuwildcat** [comment]
Maybe someone spiked your punch with some Web GLSD? :)

JK, we may have flighted a new release to the VMs, I'll report back the
good news. I'd love to see if things are also corrected for the people on
the other Edge compat ticket.

**Comment by BergWerkGIS** [comment]
:rainbow: :rainbow: :rainbow: 

>  we may have flighted a new release to the VMs

I suppose you are referring to VMs offered via modern.ie?
I have a custom setup via an ISO from my MSDN subscription.
Edge version today is the same as yesterday: `20.10240.16384.0`

**Comment by fnicollet** [comment]
Broken in Edge on a W10 PC (not a VM) but this PC is quite bad with anything related to webgl:
![image](https://cloud.githubusercontent.com/assets/1240481/10372091/94f11bbe-6de6-11e5-8749-e506f3977985.png)
Works in Chrome on the same PC though 
![image](https://cloud.githubusercontent.com/assets/1240481/10372110/a58a7ee8-6de6-11e5-9684-173e62ba83ae.png)

Edge version is 20.x.
Will try with my home computer later

**Comment by fnicollet** [comment]
On another W10 machine, exactly the same behaviour in Edge/Chrome on https://www.mapbox.com/mapbox-gl-js/examples/
Nothing in the console except from some nice Mapbox ASCII art :)

**Comment by lucaswoj** [comment]
@BergWerkGIS @csuwildcat Those screenshots look like `mapbox.js`, not `mapbox-gl-js`. Sadly, Edge is still broken.

**Comment by BergWerkGIS** [comment]
@lucaswoj oh my! You are right. Good catch.

once again: real machine, MacBook Pro 13" with W10:

**Edge 20.10240.16384.0**
![w10-edge-20 10240 16384 0-3](https://cloud.githubusercontent.com/assets/4549888/10387851/20d6853c-6e65-11e5-9e22-3bb288953097.jpg)

**Chrome 45.0.2454.101.m**
![w10-chrome-45 0 2454 101 m](https://cloud.githubusercontent.com/assets/4549888/10387861/32923cf8-6e65-11e5-8355-eb9aaf58419d.jpg)

**Comment by lyzidiamond** [comment]
tagging @mapbox/support for known issue

**Comment by scothis** [comment]
Seems to work great with the newly released Edge 13.

**Comment by lucaswoj** [comment]
We haven't dug in too deeply, but it appears Edge 13 renders gl-js _beautifully_! A huge thank you to @csuwildcat and the IE dev team for seeing this through.

Let's close this issue and create new issues if any more specific problems show up. 

cc @scothis
