### ISSUE TITLE
Support framebuffer plugins

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1438]
My understanding of framebuffers is pretty tenuous, but the ideal is that we could
1. Render each tile to a buffer
2. Pass that buffer through configurable shaders

This would help with things like full-view blurring, color-blindness simulation, and photoshop-style effects. The hope is that since at this point you're dealing with a generic image rather than any specific data, it's a place where configurable plugins could be applied to any map.

Over the weekend, I [sketched this out](https://github.com/mapbox/mapbox-gl-js/commit/47c3dfb3f5a3f3e2021d9672255d990e41a3c624) but was very dumb about it and probably made many mistakes.

**Comment by lucaswoj** [comment]
This is cool! Do you think this is something we should try to include in an upcoming release? 

Any thoughts about how this would work with tile-less rendering @ansis?

**Comment by lucaswoj** [comment]
💭  I wonder how this jivves with #281

**Comment by tmcw** [comment]
Closing in favor of #281
