### ISSUE TITLE
Drag events

### ISSUE THREAD

**Issue by SeanEire** [mapbox/mapbox-gl-js#1442]
Are there currently any events emitted for drag interaction events like dragstart / dragend?

**Comment by peterqliu** [comment]
hey @SeanEire , there's current support for `zoom` (fires whenever the z level changes), `move` (fires whenever zoom or drag), and `moveend` (fires at the end of the move). We're working to improve documentation for these.

**Comment by SeanEire** [comment]
@peterqliu Thanks! The move event was what I was looking for, I was listening for movestart. 

Is there any plan to add exclusive events for dragstart/dragstop? It would be useful to be able to bind to those events in isolation rather than binding to the move events since move will be triggered on zoom also.
