### ISSUE TITLE
Style source as function

### ISSUE THREAD

**Issue by christopherhelf** [mapbox/mapbox-gl-js#1444]
Is there any possibility to set a tile source via a callback function that is called dynamically whenever new tiles are requested from the server? i.e. something like 
"osm": { "type": "vector", "tiles": [getURL] } with function getURL(). When trying this I receive a validation error "string expected, function found". Or generally speaking, is there a way to directly set the vector bufferdata I receive from a server?

**Comment by tmcw** [comment]
The style itself should be serializable JSON, so functions should not be supported.

But what you're describing is very similar to https://github.com/mapbox/mapbox-gl-js/issues/929 - we'd like to have an API that allows custom URL construction as well as custom parsing for different datasources. Folding this ticket into that one.
