### ISSUE TITLE
stackgl/headless-gl attribute weirdness

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1449]
I updated headless-gl to the latest stackgl version and it broke a whole bunch of render tests. The `raster-brightness` test failure is stumping me:

[Flipping the order that two attributes are defined in a shader fixes the render test](https://github.com/mapbox/mapbox-gl-js/commit/e216144a9d55efecc0ae6ef6f6bbc4bab7022102).
I have no idea why.

To reproduce:

1. checkout and install https://github.com/mapbox/mapbox-gl-js/tree/stackgl-headless-gl
2. Install `headless-gl` manually because npm doesn't handle the git submodule. Use https://github.com/ansis/headless-gl/tree/teximage2d-imagedata
3. run `npm run test-suite`. The raster-brightness test **passes** for me.
4. checkout the parent commit, 793b993a063127f6e04aed485c2d7a760ed15439
5. run `npm run test-suite`. The raster-brightness test **fails** for me.

This is the only change: https://github.com/mapbox/mapbox-gl-js/commit/e216144a9d55efecc0ae6ef6f6bbc4bab7022102

[This is where the draw call is made](https://github.com/mapbox/mapbox-gl-js/blob/e2a0760f77b994ac81594d4dc74d5d05d20f6c2c/js/render/draw_raster.js#L51-L53).

I checked and:
- both attribute locations are gotten from the right shader program
- both attributes are enabled

It seems as if the attribute locations returned by `getAttribLocation` are wrong but I didn't find anything suspicious in the source. Any ideas @mikolalysenko?

**Comment by mikolalysenko** [comment]
I think I know exactly what is going on here.

There is a bug in ANGLE which I saw in the conformance tests where if you don't use a `vertexAttribPointer` on attribute 0 (ie you just set it using `vertexAttrib*f` instead), then rendering breaks.

Can you try printing the attribute location for `a_pos` and `a_texture_pos`?

**Comment by ansis** [comment]
Nope, it's not the "never disable vertex atttrib 0" bug. We're always using pointers for attributes.

In the broken version the location for `a_pos` is 0, `a_texture_pos` is 1. In the working version `a_pos` is 1, `a_texture_pos` is 0.

I have no idea why, but this also "fixes" the rendering test (but breaks it in browsers):
```diff
diff --git a/js/render/draw_raster.js b/js/render/draw_raster.js
index fa086fe..7b28ad6 100644
--- a/js/render/draw_raster.js
+++ b/js/render/draw_raster.js
@@ -48,8 +48,8 @@ function drawRaster(painter, layer, posMatrix, tile) {
 
     gl.bindBuffer(gl.ARRAY_BUFFER, tile.boundsBuffer || painter.tileExtentBuffer);
 
-    gl.vertexAttribPointer(shader.a_pos,         2, gl.SHORT, false, 8, 0);
-    gl.vertexAttribPointer(shader.a_texture_pos, 2, gl.SHORT, false, 8, 4);
+    gl.vertexAttribPointer(shader.a_texture_pos,    2, gl.SHORT, false, 8, 0);
+    gl.vertexAttribPointer(shader.a_pos,            2, gl.SHORT, false, 8, 4);
     gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4);
 
     gl.enable(gl.STENCIL_TEST);
```

It is as if the attrib location for `a_pos` was actually the one for `a_texture_pos` and vice versa.

**Comment by mikolalysenko** [comment]
That is weird, and needs to be investigated carefully.  I could take a closer look on Friday, but I need to catch up on some other projects first.

**Comment by mikolalysenko** [comment]
Ok, I fixed it in the latest version of headless-gl by just rebinding all attribute locations for a program before linking.  I think the underlying problem is deep in ANGLE/the OS X OpenGL drivers but can't figure out where.

**Comment by mourner** [comment]
Yes, fixed.
