### ISSUE TITLE
Touch event handler prevents scrolling on/within elements laid on top of the map canvas.

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#1450]
Hey,

the handler for ontouchmove prevents scrolling on/within all elements laid on top of the map canvas. This is probably clever for use cases where you'd embed a map as an element in a regular website, but not for building a single page app with a fullscreen map as the background with foreground elements on top (think google maps).

Disabling e.preventDefault(); in the handler fixes this issue, but I guess the best route would be to make touch handlers context aware.

```javascript

    function ontouchmove(e) {
        if (e.touches.length === 1) {
            onmousemove(e);
        } else if (e.touches.length === 2) {
            var p1 = mousePos(e.touches[0]),
                p2 = mousePos(e.touches[1]),
                p = p1.add(p2).div(2),
                vec = p1.sub(p2),
                scale = vec.mag() / startVec.mag(),
                bearing = vec.angleWith(startVec) * 180 / Math.PI;
            pinch(scale, bearing, p);
        }
        e.preventDefault();
     }
```

**Comment by mourner** [comment]
No, I think `e.preventDefault()` on the app side is the right way to go about this. No need to hack around something that has a nice intuitive fix.
