### ISSUE TITLE
changing text-size with style api broken

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#1451]
changes to `text-size` made with the style api aren't visible. This was probably broken by https://github.com/mapbox/mapbox-gl-js/pull/1419

`text-size` is also a paint property internally. The internal paint property gets set [here](https://github.com/mapbox/mapbox-gl-js/blob/1bff3b6d5a6c209df4a107db52a5a04cb662c487/js/style/style_layer.js#L121). I think `_resolvedLayout` might not be getting updated after the new `text-size` is set.

I think StyleLayer.setLayoutProperty might need to run some of this stuff: https://github.com/mapbox/mapbox-gl-js/blob/1bff3b6d5a6c209df4a107db52a5a04cb662c487/js/style/style_layer.js#L29-L39

**Comment by edenh** [comment]
Should `_resolvedLayout` be updated on every layout property change, or only for `text-max`?
