### ISSUE TITLE
If center and zoom are present on v8 style, initial center and zoom is 0,0,0

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-js#1452]
Now that center and zoom have been added to the style spec in v8, mapbox-gl-js should set the center and zoom to these values if they are not supplied else where. Right now, it ignores these values and sets center to `[0,0]` and zoom to `0`.

Example: http://bl.ocks.org/bsudekum/6919689c43037b19f6f7

/cc @jfirebaugh @mourner

**Comment by scothis** [comment]
... `bearing` and `pitch` as well

**Comment by jfirebaugh** [comment]
The fix in 0.11.0 doesn't seem to be working. I'm seeing `tr.zoom !== unset.zoom` and `tr.center.lat !== unset.center.lat`, most likely due to the effects of `Transform#_constrain`.
