### ISSUE TITLE
Unable to load styles for mapbox-gl-js v0.10.0

### ISSUE THREAD

**Issue by AbrahamArun** [mapbox/mapbox-gl-js#1455]
#### For mapbox-gl-js v0.10.0
As per #1436 , we are supposed to use v8 styles for the map. 

I am guessing I can use any of the v8 styles mentioned in https://github.com/mapbox/mapbox-gl-styles/tree/master/styles. But none of the v8 styles are hosted anywhere yet unlike the previous versions, for eg: https://www.mapbox.com/mapbox-gl-styles/styles/outdoors-v7.json

Also when I serve the debug page of the latest source code (master), I see this same issue
<img width="398" alt="screen shot 2015-09-03 at 10 38 07 am" src="https://cloud.githubusercontent.com/assets/5391059/9650990/255b193c-5228-11e5-9a2f-ef885d975e34.png">

**Comment by jfirebaugh** [comment]
Good question! I've just released updated API documentation and examples for v0.10.0, so take a look at [this example](https://www.mapbox.com/mapbox-gl-js/examples/). Basically, you want to use `mapbox://` URLs for the style, like `mapbox://styles/mapbox/streets-v8`. I've added documentation for this to [the description of the Map `style` option](https://www.mapbox.com/mapbox-gl-js/api/#map).
