### ISSUE TITLE
Stale tile pyrimid when adding source and layer in a batch

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#1459]
When adding a new source and a layer that consumes that source in the same batch update, the content of the source does not render until the map is paned past the current view or zoomed.  The behavior is similar to #1337

**Comment by jfirebaugh** [comment]
@scothis Want to take a stab at fixing this?

**Comment by scothis** [comment]
This is more involved than simply adding a source and a layer in the same batch. My current hunch is that this bug is triggered when a batch is closed, but not fully complete because of async operations, and a new batch is opened immediately.

If I debounce calls to batch, the issue disappears.

**Comment by scothis** [comment]
@jfirebaugh created a reproduction on CodePen. Still working to minimize the test case.

http://codepen.io/scothis/details/GppWRj/

**Comment by scothis** [comment]
A further reduced CodePen:

http://codepen.io/scothis/pen/ojjZYj/?editors=001

**Comment by mourner** [comment]
This should be fixed after #2355. Please reopen if still reproducible.
