### ISSUE TITLE
support per-feature style attributes

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#146]
Very bluesky, but it would be good to be able to style features based on their attributes, for example buildings based on heights, etc.

You could just split things into many buckets, but that will blow up the number of draw calls. The other approach would be to optionally add certain attributes to the buffers and pass them into shaders.

Since attributes can't be optional in shaders, we'd need a separate shader for each combination of attributes. As scary as it sounds, generating the shader code could work well.

**Comment by jfirebaugh** [comment]
⇢ https://github.com/mapbox/mapbox-gl-style-spec/issues/249
