### ISSUE TITLE
How to add a land only and ocean only layers

### ISSUE THREAD

**Issue by jiggy1com** [mapbox/mapbox-gl-js#1474]
I can create the map, but what I want to do is create a map with a land-only layer and an ocean-only layer.

How can this be done?

**Comment by lucaswoj** [comment]
If you want to customize the map, you can create a custom [Mapbox GL style](https://www.mapbox.com/mapbox-gl-style-spec/) and pass it to the [`Map` constructor](https://www.mapbox.com/mapbox-gl-js/api/#map). If you need some more help, feel free to reach out to help@mapbox.com.

**Comment by mannylopez** [comment]
@jiggy1com You can also create a custom Mapbox GL style from [Natural Earth Data](http://www.naturalearthdata.com/) and overlay it to get the land-only boundaries.
