### ISSUE TITLE
Sprites not rendering in IE 11

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-js#1475]

**Comment by fnicollet** [comment]
Hello,

Sprites show up ok in IE11 on my PC, there is only one case where it doesn't show sprites (in any browser), which is when page zoom is not 100% on load, see #1476 . Is it the same issue you are having?

Fabien

**Comment by lawrence-n** [comment]
I believe this is to do with window.devicePixelRatio not being an integer when the map is loaded. This affects many windows laptops where the default DPI scaling is 125% or 150% as well as pages loaded when the zoom is not 100%.

I have tested with a number of ratios in IE 11, Chrome and Firefox and only the integer ratios will display sprites.

If the map is loaded with a pixelRatio of 4 then the sprites and labels are large, changing the pixel ratio to 1 and then updating the map labels will cause the labels to re-size but not the sprites which will become relatively smaller. I assume this means that there are two issues: that the sprites don't work with non integer pixel ratios and that however the sprites are rendered is not being updated on a re-size, unlike the labels.

**Comment by fnicollet** [comment]
thanks @lawrence-n, now that I searched for devicePixelRatio in the issues, it looks like it is an already reported issue by a few different users:
https://github.com/mapbox/mapbox-gl-js/issues?utf8=%E2%9C%93&q=is%3Aissue+devicePixelRatio
Such as this one #1029 which is still opened

Fabien

**Comment by edenh** [comment]
@lawrence-n @fnicollet I can confirm that when the page zoom is at 100%, the sprites do show up.

**Comment by jfirebaugh** [comment]
Closing in favor of #1476.
