### ISSUE TITLE
POI icons don't show up when page zoom is not 100% on page load

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#1476]
Hello,

I have just found a weird issue in mapbox-gl-js. If you load it while the page is zoomed out (say 90%), texts appear but icons are not showing up. If you load mapbox-gl-js while page is 100% and then zoom out 90%, icons are correctly displayed.
![image](https://cloud.githubusercontent.com/assets/1240481/9809247/dff186de-5866-11e5-8de7-5bec66edda8d.png)
instead of
![image](https://cloud.githubusercontent.com/assets/1240481/9809262/f26c74d6-5866-11e5-970f-a0ce79e66206.png)

Here is a jsfiddle for you to reproduce the issue:

http://jsfiddle.net/fnicollet/u84yapaj/

I started looking in the code but I can't seem to find the issue. There are some icon drawSymbol calls with no error, it just doesn't show. I can't find where there is code looking for pixel density or anything.
Do you have an idea why this bug is happening or a hint on where I should look in the code?

Thanks a lot,
Fabien

**Comment by lucaswoj** [comment]
I was not able to replicate this issue in Safari Version 8.0.8 but _was_ able to replicate in Chrome Version 45.0.2454.85.

**Comment by lucaswoj** [comment]
Because it works in some browsers, I might start by looking at weird WebGL + page zoom interactions before I started looking for bugs in Mapbox GL JS.

**Comment by lucaswoj** [comment]
... that, or pixel density

> I can't find where there is code looking for pixel density or anything.

https://github.com/mapbox/mapbox-gl-js/search?utf8=✓&q=devicePixelRatio

**Comment by lucaswoj** [comment]
@ffnicollet I think I fixed this with #1593. Please re-open this ticket and ping me if you're still seeing the bug.

**Comment by ralphking** [comment]
I am getting this issue in Chrome 60 (only Chrome) only on Windows 10, only on some machines. 

I'm using a PNG as an icon, I can see it loading and follow the direct link in the browser, however mapbox is sometimes not rendering it.
