### ISSUE TITLE
eliminate need for "interactive" property on layers

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1479]
All layers should support `featuresAt` automatically. Behind the scenes the necessary datastructures should be built lazily, or however makes sense for performance.

Having a user-visible `interactive` layer property leaks implementation details to the API, is a big trap for users, and leads to convoluted examples [like this](https://github.com/mapbox/mapbox-gl-js/blob/ec2b789462e3320126962cdd8b1ec74ac133d67c/docs/_posts/examples/3400-01-05-featuresat.html#L23-L28).

**Comment by ansis** [comment]
I did some profiling and memory usage is fine when we remove `interactive` and make it enabled for all layers. and it could probably be optimized further.

The main task updating the style spec: https://github.com/mapbox/mapbox-gl-style-spec/issues/418

Should we wait until the spec is changed and released or can we start ignoring it immediately?

**Comment by lucaswoj** [comment]
I don't think we need to wait until the spec is changed.

That said, we do need to think carefully about this because it is a breaking change. Users who do not pass a `layer` parameter might expect only features from `interactive: true` layers to be returned.

**Comment by tmcw** [comment]
:tada: :tada: :tada: this is excellent news thx @ansis
