### ISSUE TITLE
featuresAt during transitions returns nothing

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1486]
Right now if you double-click a map and click again during the transition, the featuresAt call will always fail - giving no features.

It's not possible to distinguish this 'no features because data isn't loaded yet' from 'no features because there aren't any features'.

In other words:

> https://github.com/mapbox/mapbox-gl-js/blob/fde1b55c2d195a18e25d1ef8642430d7dbb985c7/js/source/source.js#L72-L78

I would prefer if these two early-exits returned Errors.

**Comment by tmcw** [comment]
@mourner thoughts on this issue? I can roll a patch, but it does amount to a pretty significant change in behavior.

**Comment by mourner** [comment]
@tmcw will look into this more closely on Monday. Not sure about throwing an error here here since it's a common response. Maybe we could address your use case by having something like `map.loading` that reflect the state of the map, and not expect all features when it's `true`?

**Comment by ansis** [comment]
@tmcw what kind of transitions are you referring to?

> I would prefer if these two early-exits returned Errors.

`queryRenderedFeatures` only has one early exit: https://github.com/mapbox/mapbox-gl-js/blob/df6b0c41a46b3f1d894b3715ee3ffeb54e0608ea/js/source/source.js#L96 I think an empty array is fine in this case.

**Comment by tmcw** [comment]
queryRenderedFeatures improves this case significantly.
