### ISSUE TITLE
Sprites do not render in Windows

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#1487]
The sprite sheet is loaded, but does not render on Windows 10.

Confirmed on https://www.mapbox.com/mapbox-gl-js/examples/ with:
- IE 11
- Chrome 45
- Firefox 40

Everything is fully patched.

**Comment by scothis** [comment]
Probably related to https://github.com/mapbox/mapbox-gl-js/issues/1476. I'm on a Surface with the default resolution (which is think is >100%)

**Comment by lucaswoj** [comment]
@scothis I think I fixed this with #1481. Please re-open this ticket and ping me if you're still seeing the bug.

**Comment by scothis** [comment]
:+1: looks good
