### ISSUE TITLE
Cancel tile load if given tiles are not in viewport

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-js#1490]
Notice how many requests are still coming in and how long it takes to load the tiles in the viewport after I've finished panning:

![](https://cldup.com/pXWs_NzAW6.gif)

Ideally, if the tiles are no longer in the viewport, the requests for the tiles should be canceled so room for more applicable tiles can load.

/cc @jfirebaugh

**Comment by jfirebaugh** [comment]
:+1: Good bug -- this happens for vector tiles but not raster tiles.
