### ISSUE TITLE
Line-end-icon

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1492]
A new property for lines, to tack a sprite onto each end. Useful for arrowheads. Rotationally aligned to the orientation of the line's end.

Optionally, support two different images for each end of the line.

The analogous feature in Illustrator:

<img width="223" alt="screen shot 2015-09-16 at 6 02 54 pm" src="https://cloud.githubusercontent.com/assets/4551508/9922413/0691ec4a-5c9d-11e5-89f7-58012539003f.png">

**Comment by incanus** [comment]
Shouldn't this go into the spec first?

**Comment by peterqliu** [comment]
moved https://github.com/mapbox/mapbox-gl-style-spec/issues/359
