### ISSUE TITLE
featuresIn example

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1494]
From https://github.com/mapbox/mapbox-gl-js/issues/1264#issuecomment-141074829:

> Any example on how to replace the default <kbd>shift</kbd>+<kbd>drag</kbd> **zoom** with **selection** of all markers inside that area.

**Comment by dkniffin** [comment]
I'd really like to see an example of how to use featuresIn with mapbox streets. I'm having some difficulties.

**Comment by bhousel** [comment]
related #1892 - that ticket has an example with a 2 click box, but shift-drag would be nicer

**Comment by tristen** [comment]
This happened https://www.mapbox.com/mapbox-gl-js/example/using-featuresin/
