### ISSUE TITLE
Disable touch rotation

### ISSUE THREAD

**Issue by bmehta** [mapbox/mapbox-gl-js#1496]
Still new to mapbox gl - so apologize if this is a stupid question. I cannot find the answer readily to this - is there a way to permanently disable rotation on a mapbox gl map? I see setBearing(), but that seems more of a one time function? We are looking at disabling rotation from a performance-enhancing standpoint - would disabling rotation improve responsiveness?

Any suggestions would be much appreciated. Thanks.

**Comment by jfirebaugh** [comment]
Yes: `map.dragRotate.disable()`. I filed a ticket to document this and other handlers: https://github.com/mapbox/mapbox-gl-js/issues/1497.

Other than disabling rotating, which is slightly more performance intensive than zooming and panning, it will not enhance performance.

**Comment by bmehta** [comment]
Thanks for the quick response. Confused. So I did this. But doesnt look like rotation is disabled. 

var map = new mapboxgl.Map({
...
...
})

map.dragRotate.disable();

I also tried to disable it within the "load" event handler. No luck. What am I missing?

**Comment by bmehta** [comment]
Disabling pan works just fine. 

map.dragPan.disable();

Why wouldnt disabling rotation work?

**Comment by jfirebaugh** [comment]
Can you be more specific? What did you expect to happen and what happened instead?

In the [example that was just added](https://www.mapbox.com/mapbox-gl-js/example/disable-rotation/), I can't rotate the map using right-click (or control-click), as expected.

**Comment by bmehta** [comment]
On a mobile device, I am able to to do a 2-finger touch (essentially a pinch?) and then rotate. Can that be disabled without actually disabling zoom-in and zoom-out?

**Comment by mourner** [comment]
No. I don't see any use cases where this kind of configurability would be needed.

**Comment by bmehta** [comment]
So, essentially, no way to disable rotation on mobile devices?

**Comment by jfirebaugh** [comment]
It should be possible to disable touch rotation but not touch zoom -- reopening for that case.

**Comment by liebrand** [comment]
Just my two cents here, but I think right now it's too easy to accidentally rotate when you are pinch zooming. I noticed that there are similar bugs on mapbox-gl-native for android (obviously a different code base - but same user issue).

Basically Google Maps is smart enough to detect when you start a pinch *zoom* (compared to *rotate*). Once that happens it won't allow rotate. If you on the other hand *started* to rotate with two fingers, it will allow rotation and not zoom.

I think the drag_rotate.js and pinch.js need to be a bit smarter (and/or combined)

**Comment by liebrand** [comment]
correction, drag_rotate.js doesn't have anything to do with this. But the pinch.js has

bearing = vec.angleWith(this._startVec) * 180 / Math.PI,

Instead it should do something a little smarter. Perhaps only start counting the rotation once the bearing is greater than X. Or (like Google Maps) ignore the rotation all together if you are already zooming..

**Comment by musicformellons** [comment]
👍

**Comment by dougaspland** [comment]
**Renovate America**, prospective customer question.

[Sales ticket](https://github.com/mapbox/sales/issues/1880)

> One of the ways we showcase our mapping solution is via a 50” touch screen tv, powered by windows using chrome.  We have noticed with the mapbox.js we are able to successfully disable rotating of the map.. In mapbox-gl.js disabling the rotating setting does not disable it for the touch events..  Is there another way of disabling it?

**Comment by charris-RA** [comment]
We have this issue as well when using a touch screen tv/touch enabled device.  An option to disable the map rotation is very much needed.

**Comment by whoiscarlo** [comment]
Can we revisit this issue? I don't understand why we can't disable touch rotate without disabling touch zoom.

If a user accidentally zooms in, it's easy to zoom out to whatever distance they had previously, because users are familiar with the gesture. They've been taught to do it for decades. However, the same can't be said with rotation. When a user rotates by mistake, it's not easy to reset to the previous orientation, because 1) users aren't familiar with the gesture and 2) it's awkward to perform even when you are.
