### ISSUE TITLE
Provide helpful error message when style does not specify "glyphs" or "sprites"

### ISSUE THREAD

**Issue by alukach** [mapbox/mapbox-gl-js#1501]
I seem to be getting an `Uncaught Error: Unimplemented type: 4` exception any time I try to add a `type: "symbol"` layer to a map.  This has occurred with both a custom generated set of labels and with `mapbox://mapbox.mapbox-streets-v6`.

This seems to occur with both Mapbox GL Style Version `7` and `8`. I've largely copied the styling from a Mapbox example (which does not exhibit the issue) so it may very well be an implementation error, but I'm at a loss as to what the cause would be.

An example of this error can be found here: http://codepen.io/anon/pen/LpNmWa?editors=001

**Comment by tmcw** [comment]
This style requires text to be displayed, but doesn't include a value in the `glyphs` field that would be used to specify the glyph images to draw it. We should provide a better error in this case, to make it clear that glyphs are required for text.

**Comment by bhousel** [comment]
@tmcw I'd like to close this out today.. Do we definitely want to throw an error if there are no glyphs or sprites?  I kind of feel like if they are left out or empty string it's more of an intent to just not show these things and we should just silently disable them.

**Comment by jfirebaugh** [comment]
Validating this is tracked in https://github.com/mapbox/mapbox-gl-style-spec/issues/299.
