### ISSUE TITLE
Language switcher feature demo

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1502]
It's possible to switch a map's language by using setLayoutProperty with the text-field property. This is amazing. We should make a demo of this.

/cc @lyzidiamond

**Comment by lyzidiamond** [comment]
Ooh, fancy! @danswick want to tackle this?

**Comment by danswick** [comment]
Cool, yeah! I'll start on this today.

**Comment by danswick** [comment]
This is magic. Here's a PR - https://github.com/mapbox/mapbox-gl-js/pull/1508

**Comment by danswick** [comment]
From @jfirebaugh: 

> committed to mb-pages as 7b16674.

**Comment by musicformellons** [comment]
@tmcw  Could this be picked up maybe?:
https://github.com/mapbox/mapbox-gl-style-spec/issues/362

**Comment by lucaswoj** [comment]
@musicformellons We are reserving the `:` character for [token defaults](https://github.com/mapbox/mapbox-gl-style-spec/issues/104). That feature is moving now!

**Comment by musicformellons** [comment]
@lucaswoj I am not sure I understand..., (I hope) you mean: until now it was used for token defaults, but it will be available pretty soon?

**Comment by lucaswoj** [comment]
We reserved the `:` character for token defaults but are just getting around to implementing that feature (token defaults) now. 

We don't plan to change the set of reserved characters but I like the idea of providing a way to escape reserved characters in field names.

Lets discuss syntax at https://github.com/mapbox/mapbox-gl-style-spec/issues/362 and move forward with an implementation once a syntax has been agreed upon.

**Comment by musicformellons** [comment]
Ok!
