### ISSUE TITLE
Add an 'only show this state' example

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1503]
@ajashton

I think that our ability to place layers _anywhere_ in the stack will make this usecase way better covered than it was with raster tiles. How far are we from being able to have a mask like `state=New Jersey` and hide or dim everything else?

/cc @lyzidiamond

**Comment by incanus** [comment]
Possibly useful: http://justinmiller.io/posts/2015/01/20/anatomy-of-a-travel-map/

**Comment by lucaswoj** [comment]
ref https://github.com/mapbox/mapbox-gl-js/issues/993
