### ISSUE TITLE
Wrap bearing value within 0° to 360°

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1509]
Spinning the map should never give a value >360

**Comment by mourner** [comment]
I thought this was the case already? https://github.com/mapbox/mapbox-gl-js/blob/master/js/geo/transform.js#L67

**Comment by 1ec5** [comment]
ref #1363

**Comment by jfirebaugh** [comment]
Bearing is wrapped to (-180°, 180°]. If you have a specific case where you're seeing an value outside that range, please provide details.
