### ISSUE TITLE
Popular Mapbox.js example: show polygon area

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1511]
No. 1 most popular Mapbox.js example by analytics in the last year

https://www.mapbox.com/mapbox.js/example/v1.0.0/show-polygon-area/

**Comment by colleenmcginnis** [comment]
New Show drawn polygon area example is live! see #3075 and https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/
