### ISSUE TITLE
Popular Mapbox.js example: Leaflet Markercluster

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1512]
No. 2 most popular Mapbox.js example by analytics in the past year

https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-markercluster/

**Comment by jfirebaugh** [comment]
Depends on #837.

**Comment by tristen** [comment]
https://github.com/mapbox/mapbox-gl-js/commit/43a49b465d6843f733b8cdf3144b981b945c7918
