### ISSUE TITLE
Popular Mapbox.js example: draw & animate a line on a map

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1513]
No. 3 most popular Mapbox.js example by analytics in the past year

https://www.mapbox.com/mapbox.js/example/v1.0.0/dynamically-drawing-a-line/

**Comment by YunjieLi** [comment]
Happy to work on this example

Curious why [this commit](https://github.com/mapbox/mapbox-gl-js/commit/423b2e1e8d3a794ef6f3179f51cf865c882f3f71) did not make its way to an example but may start from there.

cc @geografa @tristen

**Comment by tristen** [comment]
@YunjieLi Oh! I forgot about this and it's unfinished. Go for it!

**Comment by geografa** [comment]
@YunjieLi nice! From support questions, we get two types of requests for this kind of example - animating the line and making the line disappear after a specific distance or time similar to the [Courier example](https://www.mapbox.com/bites/00115/).

**Comment by YunjieLi** [comment]
Thanks @geografa ! 
It's easy to stop after a specific time. But it will need `turf` for a certain distance or along a specific route. I'll give that a shot and see how it works.

I'll definitely add a play/pause button too.

**Comment by mcurtiswilliams** [comment]
Hi,
Just wondering if there's an update on this, as I'm looking into this for a project I'm working on.
Thanks!

**Comment by YunjieLi** [comment]
@mcurtiswilliams this just went alive!
