### ISSUE TITLE
Popular Mapbox.js example: markercluster with Mapbox data

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1514]
No. 4 most popular Mapbox.js example by analytics in the past year (can probably combine example with #1512 )

https://www.mapbox.com/mapbox.js/example/v1.0.0/markercluster-with-mapbox-data/

**Comment by tristen** [comment]
This is in! https://www.mapbox.com/mapbox-gl-js/example/cluster/
