### ISSUE TITLE
Popular Mapbox.js example: Centering markers

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1516]
No. 6 most popular Mapbox.js example by analytics in the past year

https://www.mapbox.com/mapbox.js/example/v1.0.0/centering-markers/

**Comment by danswick** [comment]
I'll grab this one today @lyzidiamond.

**Comment by danswick** [comment]
To do: 

- [ ] Add helpful comments
- [ ] Call markers something other than markers?
