### ISSUE TITLE
Popular Mapbox.js example: Custom marker icon

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1517]
No. 7 most popular Mapbox.js example by analytics in the past year

https://www.mapbox.com/mapbox.js/example/v1.0.0/custom-marker/

**Comment by tristen** [comment]
I created this for a StackOverflow question but I'm not sure we should be endorsing this kind of example: http://bl.ocks.org/tristen/10b69f89b600ca0433fdc472db6a6cab

**Comment by lucaswoj** [comment]
@mourner is working on a `mapbox-gl-js-marker` plugin that takes a similar approach @tristen. We also have a similar system in GL Native now. This is a solution we're recommending for the time being :-)

**Comment by adcooley** [comment]
I've been trying to find a solution with the following requirements:

 a) Remote images as marker icons
 b) Click handling
 c) Fast performance

The Marker img example in the docs works for remote images, but I couldn't get click handling to work. Tristen's example would allow for click handling, but it also manages all the marker placement which I assumed was going to perform terribly with lots of icons. Having found no other example, I thought I'd see what you guys think of this as an option:

```
// Start with geojson for the points
geoJsonArray = [
  {
    'type': 'Feature',
    'geometry': {
      'type': 'Point',
      'coordinates': [lng, lat],
      'icon': {
        'iconUrl': 'https://your_image_url.com',
        'iconSize': [22, 22]
      }
    }
  },
  {
    …
  }
]
map.addSource('markers', {
  'geojson',
  data: {
    'type': 'FeatureCollection',
    'features': geoJsonArray
  }
})

// Add a layer building filled circles (or whatever shape you like) as the clickable element:
map.addLayer({
  'id': 'markers',
  'interactive': true,
  'source': 'markers',
  'type': 'circle',
  'paint': {
    'circle-radius': 22,
    'circle-color': '#a_bg_color_hex'
  }
})

// Add click handlers
map.on('click', (e) => {
  const features = map.queryRenderedFeatures(e.point, {layers: ['markers']})
  if (!features.length) { return }

  // Do what you're gonna do
}

// Change pointer style on hover
map.on('mousemove', function (e) {
    var features = m.queryRenderedFeatures(e.point, {layers: ['markers']});
    map.getCanvas().style.cursor = features.length ? 'pointer' : '';
})

// Finally, and MOST IMPORTANTLY, add Markers where the image is the background, and with pointerEvents turned off so the markers pass through to the layers underneath.
// The img example in the docs doesn't work because they're blocking the click events
map.on('load', function() {
  geoJsonArray.forEach((feature) => {
    var marker = document.createElement('div')
    marker.style.backgroundImage = "url(" + feature.properties.icon.iconUrl + ")";
    marker.style.backgroundSize = feature.properties.icon.iconSize[0] + "px " + feature.properties.icon.iconSize[1] + "px";
    marker.style.width = feature.properties.icon.iconSize[0] + "px";
    marker.style.height = feature.properties.icon.iconSize[1] + "px";

    // In my example it's a circular icon, so position it accordingly
    marker.style.marginLeft = "-" + Math.floor(feature.properties.icon.iconSize[0] / 2) + "px"
    marker.style.marginTop = "-" + Math.floor(feature.properties.icon.iconSize[1] / 2) + "px"

    marker.style.pointerEvents = "none"

    // add marker to map
    new mapboxgl.Marker(marker)
        .setLngLat(feature.geometry.coordinates)
        .addTo(map);
})
```

Thoughts? Seems to be working well for me.

**Comment by adcooley** [comment]
@tristen the only issue I'm still working with is that sometimes, not all the Marker objects get added to the map. Is there a limit to the amount you can add at one time? I'm kind of confused as to what exactly Marker's _are_, since you don't add them like you do other layer sources

**Comment by tristen** [comment]
> @tristen the only issue I'm still working through is that sometimes, not all the Marker objects get added to the map. Is there a limit to the amount you can add at one time?

@adcooley That sounds like a bug you might be running into. Can you cut a new issue for this along with a link to an example reproducing this?

>  I'm kind of confused as to what exactly Marker's are, since you don't add them like you do other layer sources

Right: Adding a new source layer and applying layer styles is applied to the map `<canvas>` element directly. This allows you to add a massive number point data but you are limited to the [styling spec](https://www.mapbox.com/mapbox-gl-style-spec/).

The [Marker API](https://www.mapbox.com/mapbox-gl-js/api/#Marker) OTOH is not part of the canvas element, allows you to add custom HTML content (and apply custom CSS) to dress it up, is limited to point data, and should be used on a smaller number of points as it bears the same performance limitations as adding many elements on top of a map using say Leaflet.

**Comment by adcooley** [comment]
@tristen I got to the bottom of my issue with map markers not showing. Relates to my invalid bug report here: #2879 

I've worked around it by removing/re-adding markers as you cross the date lines with 360 degree offsets.

Thanks for the help! Also, I'll just note again that if we could create geojson layer features with remote-urls for icons, it would have saved me about 16 hours of work :)

**Comment by lucaswoj** [comment]
Done in #2872! 🎉  https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons

**Comment by adcooley** [comment]
@lucaswoj can click handlers be applied to those markers?

**Comment by lucaswoj** [comment]
@adcooley Markers are regular HTML elements and have all the functionality thereof (including click handlers). I have opened an issue about repeating markers #2894.

**Comment by RaresSalcudean** [comment]
@lucaswoj Great examples! I have a questions and its kinda frustrating I can't find a clear answer.. 

When and why would we use map.AddSource, in this [example](https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/)) there is not addSource yet sill works fine. At the moment I finished this [tutorial](https://www.mapbox.com/help/building-a-store-locator/) uses addSource + the method you describe in the tutorial.

I can't understand why would you load data with addSource and then iterate to add the markers (whats the reason to use addSource if you still iterate to add the custom markers).

Thank you!

**Comment by tristen** [comment]
@RaresSalcudean where are you seeing `addSource` used in that example? It just creates markers by looking at each feature in a GeoJSON object. You can also just create a marker without iterating over a dataset like in the example provided in the documentation: https://www.mapbox.com/mapbox-gl-js/api/#marker

**Comment by r3weber** [comment]
I can't figure out how to create markers from map.queryRenderedFreatures.  Doesn't this create a GeoJSON object?  So if I do something like this:
`map.on('load', function() {
var features = map.queryRenderedFeatures(e.point, {
			layers: ['annapurna-basecamp-itinerary'] // replace this with the name of the layer
		});
		
		if (!features.length) {
			return;
		}

		var feature = features[0];
var marker = new mapboxgl.Marker()
  .setLngLat([30.5, 50.5])
  .addTo(map);`
