### ISSUE TITLE
Popular Mapbox.js example: Marker movement

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1518]
No. 8 most popular Mapbox.js example by analytics in the past year

https://www.mapbox.com/mapbox.js/example/v1.0.0/marker-movement/

**Comment by jfirebaugh** [comment]
#1203.

**Comment by tristen** [comment]
Done with https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-line/

**Comment by misterfresh** [comment]
#2417
