### ISSUE TITLE
Popular Mapbox.js example: Animating flight paths

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1519]
No. 9 most popular Mapbox.js example by analytics in the past year

https://www.mapbox.com/mapbox.js/example/v1.0.0/animating-flight-paths/

**Comment by iamvdo** [comment]
+1
I'm currently trying to achieve this *simple* effect using MapboxGL but I'm not sure if it's doable as of now (instead of modifying/redrawing source) ?

**Comment by lucaswoj** [comment]
Done in https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-route/

**Comment by iamvdo** [comment]
Thanks, but you're animating a point on a line, not the line itself as on first example.

**Comment by mollymerp** [comment]
@iamvdo yes, as of now the only way to do this is successively adding points to a `LineString` and updating the underlying source using the pattern `map.getSource(sourceName).setData(newData);`

**Comment by alpha-beta-soup** [comment]
It would be good to have an example of that. These two examples are quite different.
