### ISSUE TITLE
Popular Mapbox.js example: Leaflet draw

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1522]
No. 12 most popular Mapbox.js example by analytics in the past year

https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-draw/

**Comment by tmcw** [comment]
Depends on https://github.com/mapbox/gl-draw maturity.

**Comment by jfirebaugh** [comment]
https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/
