### ISSUE TITLE
Popular Mapbox.js example: Single marker

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1523]
No. 13 most popular Mapbox.js example by analytics in the past year

https://www.mapbox.com/mapbox.js/example/v1.0.0/single-marker/

**Comment by lucaswoj** [comment]
Done in https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/ and https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/
