### ISSUE TITLE
Popular Mapbox.js example: Toggling layers

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1525]
No. 15 most popular Mapbox.js example by analytics in the past year

https://www.mapbox.com/mapbox.js/example/v1.0.0/layers/

**Comment by geografa** [comment]
@lyzidiamond @lucaswoj this example is starting to get some requests in HS. I started [this](http://bl.ocks.org/geografa/357f49de547610de70f6) but stuck on how adding additional layers. When I added more layers, I'm getting back an `layer undefined`. I'm not even sure if this is the best way to add the sources and layers.

**Comment by lucaswoj** [comment]
A simpler way to do this would be to hide a layer by calling

```js
map.setLayoutProperty(layerID, 'visibility', 'none');
```

and show it by calling
```js
map.setLayoutProperty(layerID, 'visibility', 'visible');
```

**Comment by lucaswoj** [comment]
The only problem with your code is that you're always setting the new layer's id to "terrain-data"

```js
map.addLayer({
    "id": "terrain-data",
```

easy fix by changing that to
```js
map.addLayer({
    "id": layerID,
```

**Comment by geografa** [comment]
Thanks @lucaswoj. And sorry, forgot to mention I'd like to demo how to use other sources. Is it still recommended to use Mapbox sources only?

**Comment by lucaswoj** [comment]
I'm not sure what you mean by "recommended to use Mapbox sources only". We have [several examples using GeoJSON sources](https://www.mapbox.com/mapbox-gl-js/example/geojson-line) and [an example using a Mapzen source](https://www.mapbox.com/mapbox-gl-js/example/third-party).

**Comment by geografa** [comment]
merged.
