### ISSUE TITLE
Strange featuresAt behavior

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#1529]
Apologies for the incredibly vague subject line.

The problem: using a source of US county boundaries made with `tippecanoe`, featuresAt returns empty most of the time, and when it doesn't, it's significantly offset from the passed-in point.  

Reproduction here: http://bl.ocks.org/anandthakker/67ff3076df1235c3be44.  Put your mouse in western Maryland and look in North Carolina.

![featureat](https://cloud.githubusercontent.com/assets/4974151/10037087/2d89829a-617f-11e5-98d0-9f54fe2e7eb5.gif)

**Comment by mourner** [comment]
Weird. I'll investigate.

**Comment by mourner** [comment]
OK, found the issue — featuresAt don't calculate the coordinates correctly if the tile extent is not the default 4096 (in this case it's 1024).

**Comment by mourner** [comment]
Fixed in #1530

**Comment by anandthakker** [comment]
@mourner Well, that's a little embarrassing since I actually introduced a couple of those `4096` magic numbers myself.  Thanks for the quick fix!
