### ISSUE TITLE
Max value for options.speed?

### ISSUE THREAD

**Issue by bmehta** [mapbox/mapbox-gl-js#1533]
If I am using fitBounds -  https://www.mapbox.com/mapbox-gl-js/api/#map/fitbounds, is there a way to tell the max value I can use for options.speed?

**Comment by mourner** [comment]
Not yet, but that's a good idea. Should be easy to add.

**Comment by mourner** [comment]
Hmm, not, I must have misinterpreted the question. What do you want to achieve? `fitBounds` chooses a duration based on how far it must travel, that's why there's `speed` instead of duration, and it is constant.
