### ISSUE TITLE
collisionDebug option does not immediately take effect

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1537]
The collisionDebug option requires sources to be reloaded, which is an asynchronous operation, but calls .update() immediately. This leads to a behavior in which the map only shows collision boxes after the map is moved, after tiles are loaded: the `.update()` call isn't effective.

I sketched a solution in https://github.com/mapbox/mapbox-gl-js/pull/1536 but it seems like cutting against the grain.

**Comment by jfirebaugh** [comment]
I'd expect the reload to trigger `tile.load` events that trigger repaints.

**Comment by tmcw** [comment]
So `this.update` is fast enough that we're comfortable with calling it pretty often?

**Comment by mourner** [comment]
Yes.
