### ISSUE TITLE
Does mapbox gl support maxBounds property?

### ISSUE THREAD

**Issue by bmehta** [mapbox/mapbox-gl-js#1538]
I am trying to use maxBounds with minZoom and maxZoom when initializing a map.  See fiddle at https://jsfiddle.net/1Lv258e7/

Unfortunately I see the stacktrace below. What am I missing?

Uncaught RangeError: Maximum call stack size exceeded22.Transform.latY @ transform.js:13122.Transform._constrain @ transform.js:299zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317
9transform.js:132 Uncaught RangeError: Maximum call stack size exceeded22.Transform.latY @ transform.js:13222.Transform._constrain @ transform.js:299zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317zoom @ transform.js:9122.Transform._constrain @ transform.js:317

**Comment by tmcw** [comment]
Ah, since [zoom is a setter and calls _constrain](https://github.com/mapbox/mapbox-gl-js/blob/1d7bdd8d5d80753f7a6a79fa4b87062e4e295935/js/geo/transform.js#L317), constrain triggers an infinite loop.

**Comment by bmehta** [comment]
Any quick pointers for me so I can atleast fix locally and move forward till the bug is fixed?

**Comment by mourner** [comment]
Looking into it.

**Comment by mourner** [comment]
Fixed the infinite loop. Note that in your JSFiddle, the bounds are very small and in the middle of the ocean, so they're not quite compatible with your min/maxZoom.

**Comment by bmehta** [comment]
Thanks a lot for fixing. 
Is there a way to pre-calculate the min/max zoom based on the bounds?
