### ISSUE TITLE
"addLayer (layer, [before])", before ID is not working

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1541]
I am trying to extend/alter the mapbox geojson marker example:
https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/

using the 'before ID':
https://www.mapbox.com/mapbox-gl-js/api/#map/addlayer

The "before": ["trees"] should put the layer before the layer (from another (vector) source) with id "trees" and lots of taglayers etc so the trees&taglayers show in front, but it does not work. The marker layer is simply appended, as is default behavior when not giving a before ID.

The relevant stylesheet code:

     map.on('style.load', function () {
        map.addSource("markers", {
            "type": "geojson",
            "data":
            {"type":"FeatureCollection","features":[
            {"type":"Feature","geometry":{"type":"Point","coordinates":       
            [-71.5,42.3]}},{"type":"Feature","geometry":{"type":"Point",
            "coordinates":[-72,42]}}]}
           });

        map.addLayer({
            "id": "markers",
            "type": "circle",
            "source": "markers",
            "before": ["trees"],
            "paint": {
                 "circle-radius":{
                     "base": 1.3,
                      "stops": [[1,1],[3,1.1],[8,1.3],[10,1.7],[15,2.5],[20,17]]
                    },
                  "circle-color": "#ff442b",
              }
        });
    });

**Comment by mourner** [comment]
`before` is a second argument to `addLayer`, not a layer option. Take a closer look at the docs.

**Comment by musicformellons** [comment]
Thanks, of course! Works!
