### ISSUE TITLE
Documentation: easeTo vs jumpTo disparities

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#1545]
When looking for a way to set a pitch with easing I overlooked `easeTo` at first, as I was `⌘F` to find "pitch." This highlighted the inconsistencies between `jumpTo` and `easeTo`, where `easeTo` fails to mention "pitch":

![image](https://cloud.githubusercontent.com/assets/3170312/10078555/3431e99a-62b3-11e5-87bb-9db4e77991af.png)
![image](https://cloud.githubusercontent.com/assets/3170312/10078568/3c00e9a0-62b3-11e5-95e7-d53fbb698424.png)

These should be almost the same.

**Comment by mourner** [comment]
Hmm, but both mention CameraOptions which contains pitch. What would you like to see instead?

**Comment by lbud** [comment]
> What would you like to see instead?

I would expect to see consistency between the two since they're nearly identical interactions. (As a matter of personal preference, being able to `⌘F` for "pitch" and finding `jumpTo` was nice, but I understand that that's encapsulated in CameraOptions.)

**Comment by mourner** [comment]
Oh, I see, you're talking about descriptions.
