### ISSUE TITLE
map.onError is not helpful by default

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#1549]
The error message logged by the default onError handler within Map is often blank, and completely unhelpful.

https://github.com/mapbox/mapbox-gl-js/blob/v0.11.0/js/ui/map.js#L788

<img width="401" alt="screen shot 2015-09-24 at 11 48 59 am" src="https://cloud.githubusercontent.com/assets/302992/10083218/4bae399e-62b2-11e5-9e14-1c94edbadb26.png">

**Comment by jfirebaugh** [comment]
This is likely specific to a certain type of error. This is what I see for a style validation failure, for example:

![image](https://cloud.githubusercontent.com/assets/98601/10083632/25f9a2d6-62b4-11e5-8f78-b1ddff7b1a9d.png)

What do you see after clicking the disclosure triangle? Can you track down the source of this by other means?

**Comment by scothis** [comment]
Seems to be triggered by a tile 404ing

<img width="419" alt="screen shot 2015-09-24 at 12 05 44 pm" src="https://cloud.githubusercontent.com/assets/302992/10083741/a79ea11a-62b4-11e5-88f4-0290d16163e0.png">

**Comment by scothis** [comment]
Also, seeing a user report of tile 404s blocking the map `load` event.

https://github.com/laurenancona/philly-pope-map/commit/9dce95ac2c064776fad5c9b8a3354c11bcca9b55

**Comment by scothis** [comment]
Since we expect to receive a 404 for empty tiles, treating the response as an error seems wrong.

**Comment by mjumbewu** [comment]
Yup, the error comes from the `'load-tile'` worker process. It treats 404s the same as any other error. The fix/hack we used is https://github.com/mjumbewu/mapbox-gl-js/commit/b058bdfd3cffd3fd2a8a417181b10529fc5eb76a, but I'm pretty sure that's not entirely reliable.

**Comment by lucaswoj** [comment]
fixed in #1799
