### ISSUE TITLE
Test interaction handlers, UI controls, and browser utilities

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1550]
Figure out how to test our event handling and interaction modules.

**Comment by jfirebaugh** [comment]
Possible approaches:

* JSDom. Pro: likely less unpredictability / hard-to-debug timing issues than a browser environment. Con: likely lower fidelity event implementation.
* Reintroduce real-browser test suite using smokestack. Pro: higher fidelity. Con: https://twitter.com/tmcw/status/646345048142032896
* Selenium?

**Comment by lucaswoj** [comment]
<img width="512" alt="screen_shot_2016-03-10_at_5 47 58_pm_1024" src="https://cloud.githubusercontent.com/assets/281306/13691252/35b37bae-e6ec-11e5-9e19-c0f32001d46f.png">

**Comment by anandthakker** [comment]
> JSDom. Pro: likely less unpredictability / hard-to-debug timing issues than a browser environment. Con: likely lower fidelity event implementation.

At this point in time, I would vote for this particular tradeoff.  I think it would be the quickest way to get started and I'm betting a large majority of these tests would not require a super high fidelity event environment.  (E.g. #2972 )

**Comment by lucaswoj** [comment]
+ browser utilities (i.e. `js/util/browser/*.js`) 😄

**Comment by jfirebaugh** [comment]
We've been gradually filling these out.
