### ISSUE TITLE
Don't retry failed url requests

### ISSUE THREAD

**Issue by bhousel** [mapbox/mapbox-gl-js#1551]
We should cache urls that fail with 4xx and 5xx status and avoid re-requesting them every frame.

![screenshot 2015-09-24 15 39 35](https://cloud.githubusercontent.com/assets/38784/10084696/ce4fab56-62d2-11e5-9ffa-5fb8f9c670c6.png)

Applies to:
- [ ] tiles
- [ ] datasets
- [ ] styles
- [ ] glyphs
- [ ] sprites

**Comment by jfirebaugh** [comment]
@bhousel I don't believe gl-js re-requests any assets "every frame". If you zoom out and then return back to the original view, you might see rerequests, depending on the cache headers the server sent with the 404. That seems like reasonable behavior.

Can you clarify the scenario that generated the errors in the screenshot? If that `http://localhost:9966/debug/abc` was the tile URL, is it possible those errors were the result of requests that would normally be distinct after tile URL template substitution?

**Comment by mourner** [comment]
Closing as stale. Let's reopen after we have a good test case demonstrating the issue.
