### ISSUE TITLE
Decouple zoom and compass UI controls

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1554]
Adding 'navigation' gives zoom in and out and compass; would it be possible to have just the compass (thus saving 'mobile screen estate')?

**Comment by matijs** [comment]
@lucaswoj @jfirebaugh I added this feature in #5348. Is there anything (besides time 😁) that needs doing before this could be reviewed (and hopefully merged)?

**Comment by anandthakker** [comment]
Thanks @matijs!  I'll try to review #5348 soon!
