### ISSUE TITLE
draw priority is unstable in gl js

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#1558]
I wish I could find better examples of this problem, but: 

- Sometimes labels from one layer show up at the exact location on one refresh, and are gone on the next refresh. 
- Sometimes layers lower in the order seem to have draw priority _above_ layers higher in the stack.

**Comment by jfirebaugh** [comment]
Yeah, we're going to need examples for this to be actionable.

**Comment by samanpwbb** [comment]
The stylesheets are the same:

![step2](https://cloud.githubusercontent.com/assets/108094/10147931/cc45796a-65fe-11e5-99ce-fa78c6785a64.png)
![step1](https://cloud.githubusercontent.com/assets/108094/10147932/cc46a114-65fe-11e5-8459-f2b14faa4935.png)

**Comment by samanpwbb** [comment]
Same map style, two different loads:
![screen shot 2015-09-30 at 11 37 50 am](https://cloud.githubusercontent.com/assets/108094/10197866/950118a0-6767-11e5-99fa-72eef5d216d5.png)
![screen shot 2015-09-30 at 11 37 39 am](https://cloud.githubusercontent.com/assets/108094/10197867/9503dd56-6767-11e5-844b-93b85a4209f7.png)

**Comment by peterqliu** [comment]
I've run into this often with Emerald, starting with v8. I can't discern a pattern, though. A page refresh usually fixes the problem.

**Comment by Phrogz** [comment]
In case it's related, for me Emerald **always** fails to draw the ocean/rivers.

![emerald-nowater](https://cloud.githubusercontent.com/assets/14778/10200313/cb7e2724-6762-11e5-961d-647b9fb47f79.png)  
<sup>Chrome Version 45.0.2454.101 m  and Firefox v40.0.3
Windows 7x64
GeForce GTX 670 (Driver v355.82, released 2015-Aug-31)</sup>

I get the same results on Chrome and Firefox. I (and everyone in my office) previously had a different problem with background colors changing across tiles, that was also the same across Chrome and Firefox. Updating the graphics card drivers fixed that problem. Given this cross-browser consistency, I'm guessing it's a GL interaction with the driver.

**Comment by Phrogz** [comment]
Not sure if you changed code deployed for Mapbox Studio in the last 24 hours, or if my own upgrade to Windows 7 SP1 fixed something internal, but Mapbox Studio no longer exhibits the problem I described above. (And I can't test on the `mapbox-gl-styles` URL any more, because you have now changed it to redirect to GitHub.)

**Comment by jfirebaugh** [comment]
> (And I can't test on the `mapbox-gl-styles` URL any more, because you have now changed it to redirect to GitHub.)

Sorry, I actually changed that in response to your last comment and meant to post back here: the styles that were displayed there weren't being kept up to date, and the page was using a bleeding-edge version of mapbox-gl-js. Together, these made it an unreliable way to show off the available styles. Mapbox Studio has a built-in style picker, and we'll have something similar in our documentation soon.

We haven't changed anything intentionally to fix the rendering issues described here, so I suspect they disappeared for you for other reasons.

**Comment by amyleew** [comment]
Running into this issue with my vintage style... South San Francisco is taking priority over San Francisco while I'm editing the style.

![image](https://cloud.githubusercontent.com/assets/4587826/11214812/49dfa7cc-8d11-11e5-8cbb-342436005c7c.png)


**South San Francisco**, `place-label (sm towns)`

![image](https://cloud.githubusercontent.com/assets/4587826/11214907/ba58a652-8d11-11e5-8973-dda8ac6313da.png)

Is appearing before **San Francisco**, `place-label (lg)`

![image](https://cloud.githubusercontent.com/assets/4587826/11214903/aeef020c-8d11-11e5-96b0-2d6f97f5856c.png)


When I switch between `select data` and `style` it shows as the correct priority.

![image](https://cloud.githubusercontent.com/assets/4587826/11215002/1fc82a76-8d12-11e5-8420-a7f4de701363.png)

But after I `Publish` the style, it returns to the incorrect priority in edit mode and [slippy map](https://api.mapbox.com/styles/v1/mslee/cif5p01n202nisaktvljx9mv3.html?title=true&access_token=pk.eyJ1IjoibXNsZWUiLCJhIjoiclpiTWV5SSJ9.P_h8r37vD8jpIH1A6i1VRg#6.53/37.637/-120.447).

![image](https://cloud.githubusercontent.com/assets/4587826/11215044/46683fae-8d12-11e5-8834-c709e29750c8.png)

**Comment by amyleew** [comment]
Fixed ordering but still running into some inconsistency here with the layer order. Where `place-label (lrg)` should take priority over `place-label (med)` and `place-label (sm)` 

![image](https://cloud.githubusercontent.com/assets/4587826/11215960/bb85d374-8d16-11e5-935d-239576f61f5c.png)

![image](https://cloud.githubusercontent.com/assets/4587826/11215964/c32085ac-8d16-11e5-903b-1212e99e1203.png)

**Comment by lucaswoj** [comment]
I theorize this is a race condition having to do with labels that are too close to tile boundaries. Maybe #1727 will help.

<img width="936" alt="screen shot 2015-11-17 at 10 19 37 am" src="https://cloud.githubusercontent.com/assets/281306/11220432/e3e29b24-8d14-11e5-8ee0-d192ae6cd5f9.png">

**Comment by samanpwbb** [comment]
@lucaswoj it's not just borders. I have a style with two symbol layers. Whichever I edit first and apply with a smartsetstyle gets draw priority. The end result is that the things you edit end up on top, and the things you haven't edited in a while drop to the bottom.
