### ISSUE TITLE
Vocabulary

### ISSUE THREAD

**Issue by lyzidiamond** [mapbox/mapbox-gl-js#1561]
Per https://github.com/mapbox/mapbox-gl-js/pull/1527#issuecomment-143338520 (and many other current and future issues like it), I'd love to get on the same page about "terms of art" (as @bhousel referred to them) and the vocabulary of Mapbox GL JS.

What are the major vocabulary differences between GL JS and Mapbox.js that are going to trip up users? What should we keep and what should we redefine?

cc @lucaswoj @mcwhittemore @jfirebaugh @tmcw @mapbox/support

**Comment by 1ec5** [comment]
To throw another wrench into this discussion: mapbox-gl-native has some differences in terminology, too. It necessarily reflects the terminology of Apple’s MapKit and the Google Maps SDKs for iOS and Android. For instance, in the Mapbox iOS SDK, we usually talk about _annotations_. An annotation encompasses both the marker (the part you tap) and the callout view (the part you read).

**Comment by jfirebaugh** [comment]
I'm not sure that mapbox-gl-js will ever have "Markers" in the sense that Leaflet does. In Leaflet, Markers are separate DOM elements of some type that sit on top of tile layers. In mapbox-gl-js we'd prefer developers to work in terms of style concepts instead: sources, symbol layers, style properties. The benefits to this are:

* Accelerated rendering with WebGL. Huge numbers of symbols are no problem.
* Proper layering. Symbols can be above or below other layers.
* Collision and text placement. Symbols can avoid other symbols and labels.
* Consistency and knowledge transfer between mapbox-gl-js and Mapbox Studio. Same concepts, same techniques.

See https://github.com/mapbox/mapbox-gl-js/issues/656 for more discussion.

**Comment by danswick** [comment]
It's helpful for me to think about this in terms of one of our most common use cases / requests: make a map showing your business' locations. In the basemap-overlay paradigm, we've got lots of examples, guides, and tutorials showing users how to put some markers on a basemap. In fact, these are some of the most popular pages on the Mapbox website. In GL, basemaps don't really exist. It's all sources, layers and styles. 

I think the core of the issue @lyzidiamond opened is: is it better to adopt a totally new vocabulary or try to adapt the old one to the new tools? It sounds to me like there are multiple camps on the subject.

**Comment by jfirebaugh** [comment]
Closing; not seeing any actionable tasks here. If there's something I've missed, please open a followup ticket.
