### ISSUE TITLE
clickable marker popup

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1566]
@jfirebaugh I have been going through quite a lot of issues about and relating to 'clickable marker popups', but am still a bit puzzled whether this can be done right now or not. This:
mapbox-gl-js/docs/_posts/examples/3400-01-08-html-popup.html

seems the closest example I find but did this ever work (as it is called 'idealized' and I can not make it work so far under v8 of stylesheet)? Can it be done right now and how? Thanks!

**Comment by jfirebaugh** [comment]
I made a new example for this: https://www.mapbox.com/mapbox-gl-js/example/marker-popup/. Hope that helps!

**Comment by Randgalt** [comment]
The example is good, but it's still not where the JS lib is. The markers I'm looking for are like Google Map pins. They need to popup out of the map with shadow, etc.

**Comment by Randgalt** [comment]
Also this is WAY more code than JS lib. Until there's a better solution I'll stick with the JS lib.
