### ISSUE TITLE
Don't use an icon font for UI controls.

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#1572]
Would be simpler, easier to override the styling, if icons were just SVGs (maybe even inlined SVGs) rather than an icon font.

**Comment by jfirebaugh** [comment]
Sounds fine to me. We have svg sources already: https://github.com/mapbox/mapbox-gl-js/tree/master/dist/font/src

**Comment by bhousel** [comment]
I'm confused about this... I thought icon fonts often are just packaged up SVG.

Asking because I've been looking a lot at FontAwesome lately - maybe as a replacement for Maki? (sorry)

**Comment by jfirebaugh** [comment]
SVGs have the advantage over web fonts of not requiring CORS headers, which was the issue in #1590.
