### ISSUE TITLE
Remove Math.round in LineVertexBuffer

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1573]
This gives a substantial performance boost without any noticeable rendering changes (though, enough to fail test suite).

<img width="1032" alt="screen shot 2015-09-29 at 5 44 33 pm" src="https://cloud.githubusercontent.com/assets/281306/10181825/c366f840-66d1-11e5-9db7-9100a5091841.png">

ref https://github.com/mapbox/mapbox-gl-js/pull/1526#discussion_r40742956

**Comment by mourner** [comment]
I'd guess removing the round makes the values implicitly floored when saving into a typed array, so this would be a functional equivalent of replacing `round` with `floor`. @ansis thoughts?

**Comment by ansis** [comment]
If it's faster and rendering is fine, great!

> equivalent of replacing round with floor

This is what I would expect it to do

**Comment by jfirebaugh** [comment]
Ok, so fix here would be to update the test-suite (I do it via `npm link mapbox-gl-test-suite`; `UPDATE=1 npm run test-suite` in gl-js), commit the results, and send a PR for gl-js that removes `Math.round` and updates the test-suite pin in package.json.

**Comment by lucaswoj** [comment]
For reference, this makes the `buffer2` branch about twice as fast. 

(I think that implies we're spending about **half** of buffer creation time rounding numbers!)

**Comment by mourner** [comment]
@lucaswoj as I mentioned in #1526, `round` doesn't have any effect on performance for me (on `flat-push` branch), so I wonder if it's machine-specific or something weird is going on here...

**Comment by lucaswoj** [comment]
I'm seeing a consistent ~6% speedup on `master` f0faa3a2e303bf5fc3badd7fe7f7d3c2d7f843e5 with these (and similar) calls removed. Is that small fry? Or worth chasing? 

```
## without rounding / flooring

1346 ms, 122 samples for /debug/mapbox-gl.js
1726 ms, 117 samples for /debug/mapbox-gl.js
1491 ms, 125 samples for /debug/mapbox-gl.js
1695 ms, 121 samples for /debug/mapbox-gl.js

## with rounding / flooring

1521 ms, 122 samples for /debug/mapbox-gl.js
1854 ms, 127 samples for /debug/mapbox-gl.js
1493 ms, 123 samples for /debug/mapbox-gl.js
1748 ms, 126 samples for /debug/mapbox-gl.js
```

**Comment by lucaswoj** [comment]
Thoughts @jfirebaugh @mourner @tmcw @ansis? Should we do this or close the issue?

**Comment by jfirebaugh** [comment]
We should do this.

**Comment by lucaswoj** [comment]
I see a small perf boost here (~10ms in the buffer benchmark) but not enough to be worth pursuing right now.
