### ISSUE TITLE
Can we use svg symbols?

### ISSUE THREAD

**Issue by AbrahamArun** [mapbox/mapbox-gl-js#1577]
I can see that the styles such as [streets-v8](https://raw.githubusercontent.com/mapbox/mapbox-gl-styles/master/styles/streets-v8.json) use svg symbols for e.g., [circle](https://github.com/mapbox/mapbox-gl-styles/blob/master/sprites/streets-v8/_svg/circle-11.svg).

Now can I do something like this?

```javascript
      map.addLayer({
        "id": "random-points",
        "type": "symbol",
        "source": "geojson-random-points",
        "layout": {
          "icon-image": "./custom-circle.svg"
        }
      }); 
```

**Comment by mourner** [comment]
Not directly. SVGs have to be converted to GL-consumable sprites (images + JSON). We do this with https://github.com/mapbox/spritezero-cli

**Comment by AbrahamArun** [comment]
That's pretty cool. So from what I have understood from [sprite doc](https://www.mapbox.com/mapbox-gl-style-spec/#sprite), I will have to write my own style sheet (e.g., [streets-v8](https://raw.githubusercontent.com/mapbox/mapbox-gl-styles/master/styles/streets-v8.json)) and specify the new sprites location in that. Is there an easier way to go about, where I can just add on the new sprites that I want to use?
