### ISSUE TITLE
Use a length-bounded DataView in supported browsers instead of copying ArrayBuffer

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1579]
per https://github.com/mapbox/mapbox-gl-js/pull/1578#discussion_r40948805

This sounds easy to prototype and I think it is worth a benchmark.

cc @mourner @jfirebaugh

**Comment by jfirebaugh** [comment]
Y, we can probably feature detect this with a throwaway buffer.

**Comment by lucaswoj** [comment]
I'm not seeing any performance improvement using `DataView`

```
duration: 3000
29.2 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.10.0/mapbox-gl.js
39.7 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.11.1/mapbox-gl.js
37.9 fps /debug/mapbox-gl.js
29.1 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.10.0/mapbox-gl.js
35.8 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.11.1/mapbox-gl.js
36 fps /debug/mapbox-gl.js
```

or using a `UInt8Array`

```
duration: 3000
28.3 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.10.0/mapbox-gl.js
40.4 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.11.1/mapbox-gl.js
41.9 fps /debug/mapbox-gl.js
29.3 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.10.0/mapbox-gl.js
40.6 fps https://api.tiles.mapbox.com/mapbox-gl-js/v0.11.1/mapbox-gl.js
40.3 fps /debug/mapbox-gl.js
```

I'm guessing v8 is smart enough to do copy-on-write arrays.

(also, :clap: on improvements from v0.10 to v0.11)

**Comment by mourner** [comment]
@lucaswoj oh wow! I wonder what commits could have such a powerful impact on rendering performance... Looked through commits between 0.10 and 0.11 and didn't see anything that stands out.
