### ISSUE TITLE
map.addControl(new mapboxgl.Navigation())   has a bug in v 0.11.1

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1590]
In v 0.11.1  the map.addControl(new mapboxgl.Navigation())  does not render a plus and minus sign (give A and B instead). It still works correctly in v 0.11.0 

See e.g. the example:
https://www.mapbox.com/mapbox-gl-js/example/third-party/

![image](https://cloud.githubusercontent.com/assets/10334123/10282577/db7a4910-6b7b-11e5-8ac3-6f7bf91c5b99.png)

**Comment by bhousel** [comment]
That's odd, I see the + and - in Chrome 45.0.2454.101
Do you see any browser or javascript errors in the developer console?

**Comment by jingsam** [comment]
Chrome 47.0.2516.0 dev-m (64-bit) works fine

**Comment by tmcw** [comment]
See #1572 - we should switch to SVG

**Comment by lyzidiamond** [comment]
tagging @mapbox/support for known issue

**Comment by bsudekum** [comment]
Bumping, still seeing this a bunch:

![](https://cldup.com/zMNqLAmTeZ.png)
