### ISSUE TITLE
How to use MapboxGL.js + Meteor/Cordova?

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-js#1595]
I try to embed a map with meteor on a iphone4s. Meteor uses Cordova for this. But all I get is a white screen.

I first tried with the [MabogGL.js example](https://www.mapbox.com/mapbox-gl-js/examples/) then via [the mapbox package for meteor](https://github.com/pauloborges/meteor-mapbox). Both works well on desktop but not in emulator or target device.

Is there any known issue with Cordova and MapboxGL ?

**Comment by mourner** [comment]
Looks like Cordova doesn't support WebGL.

**Comment by lucaswoj** [comment]
mapbox-gl-js requires WebGL but you should be able to use [mapbox.js](https://github.com/mapbox/mapbox.js)

**Comment by dagatsoin** [comment]
No, I need webGL for my use. Nevermind, it was just a second choice. For now I will stick on MapboxGL native.

**Comment by mjnf** [comment]
Hi,

I'm working in a Phonegap application with mapbox-gl-js. Like @dagatsoin say, these is not working in iphone4 but I think is a iOs version limitation. We are testing with Phonegap in other iPhones and work really nice. Android browser work without problem but I have a problem with Android Phonegap. All look good, mapbox init fine and load the style and icons assets(png, json), set background color but not continue showing/loading the streets. If I drag or zoom mapbox update the feautes position but is not showing nothing. Looks like a network problem but I can't found the problem. Do you have some solution for this ? 

Thanks a lot.

Thanks
