### ISSUE TITLE
WebGL switching to software rendering more frequently with recent changes

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#1597]
Hello,

I didn't update the lib for about a month, just tried the new changes as @mourner seems to have improved a lot of things lately.
When I try my map (in IE11), with the Emerald style, after a couple zoom in and out, I get this error in the console:
> WebGL content is taking too long to render on your GPU. Temporarily switching to software rendering.

And it messes up the map rendering, which goes blank. The issue is harder to reproduce with the "bright" style, but easy to reproduce with "emerald" when you are at the buildings level

Any idea where the latest changes could have gone wrong? Or should I just bisect it?

Fabien

**Comment by jfirebaugh** [comment]
@fnicollet Yes, can you try bisecting please?

**Comment by mourner** [comment]
Not seeing any recent changes that could increase GPU load. Maybe the retina sprites for Win bump?

**Comment by fnicollet** [comment]
Quick question, when I git checkout to bisect, do I need to do "npm install" then "npm start" or just "npm start"? Because npm install takes ages

**Comment by mourner** [comment]
@fnicollet depends on whether dependencies have changed in a breaking way. I'd say try npm start and only try npm install if something's broken.

**Comment by fnicollet** [comment]
@mourner ok, I see, thanks!

I tried going back to 707eba675ebe79cd5bc28a198fcda3a3f925662b (v0.10.0 release) and can still reproduce the issue rather easily by "stressing" the map a little. Not sure what is happening here, i'll try to reboot and do further tests tomorrow

**Comment by fnicollet** [comment]
Can actually reproduce it with older versions than master, I guess it has always been there.

Is there a way to detect the browser switching to software rendering? Because it can fail on creation and there is already an option to do that but i am not sure if you can catch the context loss errors

**Comment by jfirebaugh** [comment]
Have you tried the `failIfMajorPerformanceCaveat` option for `Map`?

**Comment by fnicollet** [comment]
In the specs it says "Context creation will fail if the implementation determines that the performance of the created WebGL context would be dramatically lower than that of a native application making equivalent OpenGL calls."
So I think it is just on context initialization, not after that

**Comment by fnicollet** [comment]
Hello,

I proposed a PR for this, because WebGL currently swallows the contextlost events:
https://github.com/mapbox/mapbox-gl-js/pull/1612

IE switching to software rendering is just IE being IE, it can't take it when using the Emerald styles, which have a lot of details I think.
With the PR, I can catch the errors in my code and react accordingly

I'll close this issue as there is no clear way to reproduce it apart from stressing the map

Fabien
