### ISSUE TITLE
Implement a better sprite scaling algorithm

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1601]
![image](https://cloud.githubusercontent.com/assets/1240481/10318756/42f3d026-6c6b-11e5-9db8-f043d17d88eb.png)

We've made it possible to display sprites for non-integer pixel ratios in #1593 but the image scaling isn't very good. 

Maybe related to this [`TODO`](https://github.com/mapbox/mapbox-gl-js/blob/master/js/symbol/sprite_atlas.js#L65-L66)?

ref https://github.com/mapbox/mapbox-gl-js/pull/1593#issuecomment-145964474

**Comment by lucaswoj** [comment]
@jfirebaugh thoughts on adding this to the 0.12 milestone?

**Comment by jfirebaugh** [comment]
I'm not convinced that that TODO is relevant to the depicted rendering. The issue maybe elsewhere, and easier to fix.

**Comment by lucaswoj** [comment]
Ok. I updated the description above.
