### ISSUE TITLE
Add Blob detection to util.supported method

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1613]
https://github.com/mapbox/mapbox-gl-js/blob/e523db31c1a5d3355a5d97d6bbada2cd64b6711a/js/util/browser/browser.js#L55

This doesn't currently check for the Blob prototype. Blob support is not everywhere and we should confirm it.

**Comment by mourner** [comment]
Hmm caniuse says it's everywhere: http://caniuse.com/#search=Blob, do you know specific cases where it doesn't?

**Comment by tmcw** [comment]
Yes, we've run into a case of Firefox 11 lacking Blob support but having WebGL support.

**Comment by kristfal** [comment]
Would also be great to do a check for spawning web workers from blob URLs. Older versions of IE10 and IE11 doesn`t support this. See:

https://connect.microsoft.com/IE/feedback/details/801810/web-workers-from-blob-urls-in-ie-10-and-11

IIRC this affects the latest IE11 for W8 on surface tablets.

**Comment by lucaswoj** [comment]
moved to https://github.com/mapbox/mapbox-gl-js-supported/issues/2
