### ISSUE TITLE
Firefox 41 on Ubuntu complains about getImage Blob constructor

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1615]
<img width="751" alt="2015-10-12 at 2 32 pm" src="https://cloud.githubusercontent.com/assets/32314/10435471/363cc5cc-70ee-11e5-97ca-17bce7a6166a.png">

It's not clear from any of the [Blob documentation](https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob) that Uint8Array is a kosher input.

**Comment by jfirebaugh** [comment]
[`Uint8Array` counts as an `ArrayBufferView`](https://developer.mozilla.org/en-US/docs/Web/API/ArrayBufferView). This is a bug in FF 41, but one we can probably work around.

**Comment by jfirebaugh** [comment]
According to the documentation, the `Uint8Array` wrapper is unnecessary; `new Blob([imgData], { type: 'image/png' })` should work just as well.

**Comment by tmcw** [comment]
Noticed that Safari flags this as invalid as well.

**Comment by tmcw** [comment]
Marking as invalid: there's some polyfill or bad magic that's triggering this error.
