### ISSUE TITLE
flyTo speed depends on screensize?

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1624]
I use same script (same speed and curve values) but when started in a large screen the speed of flying is clearly higher than when opened in a small screen. Does not seem to make sense.

**Comment by mourner** [comment]
It does make sense. The algorithm chooses what zoom to zoom out to while flying based on both how far it needs to travel and how much stuff fits into the map at once. Smaller screen means less stuff fits so it needs to zoom out further, leading to longer fly.

If you know how to modify [the algorithm](https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/camera.js#L530) for better behavior, PRs are welcome. I don't consider this an issue.

**Comment by musicformellons** [comment]
Ok.
