### ISSUE TITLE
tile clipping with "symbol-placement": "line"

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1627]
This is producing test suite failures on native, but I suspect the issue is in js, so filing here. The `symbol-spacing/line-close` and `symbol-spacing/line-far` tests are failing:

![image](https://cloud.githubusercontent.com/assets/98601/10554790/a6b836a8-741b-11e5-831f-b92041e7e608.png)

Native rendering:

![image](https://cloud.githubusercontent.com/assets/98601/10554791/ac72a862-741b-11e5-81ac-5715486da805.png)

Js rendering:

![image](https://cloud.githubusercontent.com/assets/98601/10554808/d61fef1c-741b-11e5-9a54-a0b8af10972d.png)

(Ignore color difference, it's some color profile issue from copy and pasting from different source.)

**Comment by bhousel** [comment]
Are these artifacts caused by #193?

**Comment by jfirebaugh** [comment]
Yes, I suspect that layer-by-layer rendering will fix this.

**Comment by jfirebaugh** [comment]
These are now rendering the same in js and native.
