### ISSUE TITLE
validate style API inputs

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1632]
The following methods should validate their inputs with the style spec validator:

* `addSource`
* `addLayer`
* `setLayoutProperty`
* `setPaintProperty`
* `setFilter`

This will require the validator to expose granular validation methods for specific types.

Will catch issues like #1631.

**Comment by mourner** [comment]
+ validate `source` and `source-layer` references to make sure those are present (not sure if this can be validated on the spec side)

**Comment by lucaswoj** [comment]
We can validate that a layer's `source` is defined but cannot validate the existence of a `source-layer` without downloading a tile (or maybe all the tiles). I don't think that behavior belongs in the style validator -- it would require a network connection, API keys, and potentially large downloads.

**Comment by lucaswoj** [comment]
currently blocked on mapbox/mapbox-gl-style-spec#407
