### ISSUE TITLE
Overlapping background-patterns break rendering

### ISSUE THREAD

**Issue by g12n** [mapbox/mapbox-gl-js#1633]
The rendering of multiple layers with background patterns break the rendering of these layers:

![image](https://cloud.githubusercontent.com/assets/57556/10586647/6889f4c8-769d-11e5-90ef-c12ccf6024c1.jpeg)

You find the source of this sample here: https://github.com/g12n/cardboard-map-gl

The sample is hosted in github pages and can be accessed here: 
http://g12n.github.io/cardboard-map-gl/

I added a debug version without patterns in the gh-pages branch: 
http://g12n.github.io/cardboard-map-gl/debug.html

**Comment by mourner** [comment]
Wow, that looks bad. cc @ansis

**Comment by g12n** [comment]
I still suspect it's a mistake in my Sprite. It's my first shot at it.

**Comment by g12n** [comment]
Similar Problem in Mapbox Studio: 

Using multiple pattern causes Problems in Chrome on Mac. 

When you zoom into the map close enough so parks appear, the park pattern is replacing the water pattern. 

![pattern-bug](https://cloud.githubusercontent.com/assets/57556/11276859/2d3e9086-8ee4-11e5-8bc6-a51fa2089a47.png)

## Test style created in Mapbox studio: 
mapbox://styles/g12n/cih6bh7vl006lbpkrhtmbxjk3

## Preview of the published style on Mapbox:  

https://api.mapbox.com/styles/v1/g12n/cih6bh7vl006lbpkrhtmbxjk3.html?title=true&access_token=pk.eyJ1IjoiZzEybiIsImEiOiJpNnpzc2prIn0.0IvRMXsg6iYGFMrwPdpcbw#0/0/0/0

**Comment by ansis** [comment]
Thanks for the testcase @g12n

The problem was that the patterns did not fit in the sprite atlas. https://github.com/mapbox/mapbox-gl-js/issues/141 is the underlying issue. A temporary workaround would be to use smaller textures.

 b0167291ae2b29c39c2317c61070edcd29a20b79 improves how the failure is handled by not drawing the affected layers and logging a warning to the console.

**Comment by g12n** [comment]
Since this is Happening inside MapBox Studio as well, there should be a warning in the UI for Designers as well. Are you aware of an Issue in that Project?

**Comment by lyzidiamond** [comment]
Hi @g12n! We are working on the next release of Mapbox Studio right now, and we're thinking that the glyph atlas PR that will fix this ( #141) will be merged by that time, in which case there won't be an issue to warn about. Thanks for the heads up!
