### ISSUE TITLE
Firefox won't render 4th tab of GL-JS map

### ISSUE THREAD

**Issue by mannylopez** [mapbox/mapbox-gl-js#1635]
![glbug](https://cloud.githubusercontent.com/assets/3945073/10589956/19872a56-7663-11e5-9a71-f1a1b349cf4a.gif)

Firefox 41.0.2 will not load a 4th open tab of Mapbox GL. 
Chrome and Safari load the map just fine.

**Comment by mourner** [comment]
Wow, wtf. Must be some weird FF bug.

**Comment by bhousel** [comment]
see #1935 for the answer
