### ISSUE TITLE
Throw an exception if a user references an unknown source layer

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1636]
I've seen a few GL support requests having to do with users not understanding source layers or not knowing the name of their source layer.

We could alleviate the situation by throwing a runtime exception if the specified `source-layer` could not be found on the specified `source`, maybe even providing a list of layers that *are* available on that source.

ref https://github.com/mapbox/mapbox-gl-js/issues/1631#issuecomment-149561809

cc @lyzidiamond

**Comment by mourner** [comment]
Yeah, this is basically a subset of #1632.

**Comment by lucaswoj** [comment]
The style validator does not have information about the names of the layers in a vector tile source (nor should it, IMO). I think this should remain a separate issue.

**Comment by mourner** [comment]
What if a tile doesn't have a certain layer because there are no features in it?

**Comment by lucaswoj** [comment]
I'm looking at using the TileJSON `vector_layers` property. AFIK this is a non-standard property and only available on Mapbox vector tile sources but we should use it if available and degrade gracefully if not.
