### ISSUE TITLE
Are multiple maps supported in one app?

### ISSUE THREAD

**Issue by bmehta** [mapbox/mapbox-gl-js#1638]
Is it possible to have multiple maps in the same application (different screens)?
If yes, do we need to do unload the previous map before loading the new one?

**Comment by tmcw** [comment]
Yes, multiple maps are supported, and you don't need to unload previous maps before starting new ones. If you run into any issues doing this, please submit a specific bug report.

**Comment by bui3itf0ky00** [comment]
How to unload the map ? can't find the class to call for that

**Comment by ryanhamley** [comment]
@bui3itf0ky00 [`Map.remove`](https://docs.mapbox.com/mapbox-gl-js/api/#map#remove). There's also a [`map.on('remove')`](https://docs.mapbox.com/mapbox-gl-js/api/#map.event:remove) event.

**Comment by jan-nick** [comment]
Showing multiple maps isn't working for me. Using Angular I've created a component containing the map. Displaying multiple identical instances of this component leads to only one component displaying the map.

**Comment by saumya-007** [comment]
@jan-nick Hello, I am relatively new to react and am trying to make a project using map box.  Basically I have a component over which I am looping. The component has 2 thing 1 is a "div" element which contains some text information and another is a component having "map". My problem is that the map is displayed 3 times ( as I am looping the parent component 3 time ) but the map displayed is the same for all the 3 iterations.  I have set different parameters for map and am passing them as props.

This might be dumb mistake, by a little help would be appreciated. Thank you

**Comment by saumya-007** [comment]
Hello, let me just specify the component tree, I have a "ScheduledTrips" Component which is basically a table as shown

export const ScheduledTrips = (props) => {
    let trips = props.trips
    return (
        <>
            <div className="table-responsive">
                <table class="table">
                    <thead class="thead-dark">
                        <tr>
                            <th>Start</th>
                            <th>End</th>
                            <th>Date</th>
                            <th>Time</th>
                            <th>Vehicle</th>
                            <th>fair</th>
                            <th>Remove</th>
                        </tr>
                    </thead>
                    <tbody>
                        {
                            trips !== undefined ? (
                                trips.map(ele => {
                                    return (<ScheduledTripsDetails data={ele} setDeleted={props.setDeleted} />)

                                })
                            ) : (
                                console.log("tripsundefined")
                            )
                        }
                    </tbody>
                </table>
            </div>
        </>
    )
}

As seen above it loops over a component "ScheduledTripsDetails" which is basically 2 rows of the table one row displays some data and another row is a mapbox component. As you can see in the code below.

export const ScheduledTripsDetails = ({ data, setDeleted }) => {
    const deleteTrip = () => {
        axios.delete("http://localhost:8080/trips/" + data._id).then(res => {
            console.log(res)
            setDeleted("deleted")
            toast.success("Deleted Successfully !")
        }).catch(err => {
            console.log(err)
        })
    }
    return (
        <>
            <tr>
                <td>{data.startLocationCity.cityName}</td>
                <td>{data.endLocationCity.cityName}</td>
                <td>{data.tripDate}</td>
                <td>{data.tripTime}</td>
                <td>{data.vehicle.vehicleName}</td>
                <td>{data.customFairAmount}</td>
                <td>
                    <button className="btn btn-danger btn-sm" onClick={deleteTrip}><i className="fa fa-trash"></i></button>
                </td>
            </tr>
            <tr>
                <td colSpan={7}>
                    <CountryState id={data._id} startlatitude={data.startLocationCity.latitude.$numberDecimal} startlongitude={data.startLocationCity.longitude.$numberDecimal}
                        endlatitude={data.endLocationCity.latitude.$numberDecimal} endlongitude {data.endLocationCity.longitude.$numberDecimal}
                    />
                </td>
            </tr>
        </>
    )
}

I am passing latitude and longitude in the component which i am then using to set the start and end location in the map.

export const CountryState = (props) => {
    let startlatitude = Number(props.startlatitude)
    let startlongitude = Number(props.startlongitude)
    let endlatitude = Number(props.endlatitude)
    let endlongitude = Number(props.endlongitude)
    mapboxgl.accessToken = 'MY_TOKEN;
    console.log(startlatitude, startlongitude, endlatitude, endlongitude);
    const mapContainer = useRef(null);
    let map = useRef();
    const [lng, setLng] = useState(startlongitude);
    const [lat, setLat] = useState(startlatitude);
    const [zoom, setZoom] = useState(9);

    useEffect(() => {
        if (map.current) return; // initialize map only once
        map.current = new mapboxgl.Map({
            container: mapContainer.current,
            style: 'mapbox://styles/mapbox/streets-v11',
            center: [lng, lat],
            zoom: zoom,
            id: props.id
        });
        const directions = new MapboxDirections({
            accessToken: mapboxgl.accessToken,
            unit: 'metric',
            profile: 'mapbox/driving'
        })
        map.current.addControl(directions, 'top-left');
        map.current.on('load', function () {
            directions.setOrigin([startlongitude, startlatitude]);
            directions.setDestination([endlongitude, endlatitude]);
        })
    }, []);
    return (
        <div>
            <div ref={mapContainer} className="map-container" />
        </div>
    );
}

Every thing else is working fine but the only thing is each map loaded for all iterations is the same.

**Comment by saumya-007** [comment]
Hello @jan-nick , I have attached the details in this word file as i was unable to upload clean code directly in this comment please have a look.
[Problem.docx](https://github.com/mapbox/mapbox-gl-js/files/8399854/Problem.docx)
