### ISSUE TITLE
events are assumed to always come with event objects, but they don't

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1639]
The forwardSourceEvent method extends an e object with a target https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/map.js#L829-L831

But sometimes we just fire an event with no data: https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style.js#L166-L167

As a result, if a source loads _during_ a batch, it throws a TypeError: `e is not defined`

**Comment by mourner** [comment]
I think the events code should always fire a data object with at least `type` and `target` properties, which is expected in most custom event systems.

**Comment by mourner** [comment]
Can you set up a minimal test case that reproduces the issue?
