### ISSUE TITLE
Change double-click zoom behavior

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1640]
Currently logic is: https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/handler/dblclick_zoom.js#L20

```js
this._map.zoomTo(Math.round(this._map.getZoom()) + 1, {around: e.lngLat});
```

I don't think that this is the optimal way to handle zooming: it runs into cases in which you have a zoom like `1.55` and double-clicking gives you `Math.round(1.55 + 1)` -> `Math.round(2.55)` -> `3`. Instead, we should do something like

```js
var z = this._map.getZoom();
this._map.zoomTo(Math.ceil(z) > z ? Math.ceil(z) : z + 1);
```

This way `1.55` pops to `2`, integers will pop to higher integers.

I'll wait for consensus on an approach before rolling a PR.

cc @mourner

**Comment by jfirebaugh** [comment]
I would prefer `this._map.zoomIn({around: e.lngLat})`, to make it consistent with +/-.

**Comment by mourner** [comment]
Hmm, given that round zoom doesn't have any special meaning for GL map interactions, I'd probably also vote for just doing +/- everywhere without snapping. And it's a bit weird to zoom in twice and see it zoom by 0.01 first and 1.0 the second time.

**Comment by mcwhittemore** [comment]
Moving from 1.5 to 2.5 to 3.5 seems a lot better than 1.5 to 2 to 3.
