### ISSUE TITLE
Build 'live GeoJSON' example 

### ISSUE THREAD

**Issue by mtirwin** [mapbox/mapbox-gl-js#1641]
Per chat w/ @jfirebaugh and several user requests to me and @geografa, let's build an example for the API page that shows how to replicate https://www.mapbox.com/mapbox.js/example/v1.0.0/live-data-marker/ in GJ-JS using setData on a timer.

cc/ @lucaswoj

**Comment by lucaswoj** [comment]
I'll grab this today!
