### ISSUE TITLE
Feature request: Configuration options for asset locations

### ISSUE THREAD

**Issue by benstadin** [mapbox/mapbox-gl-js#1642]
I'd like to use mapbox-gl-js with kartotherian. I've therefore just now created a small project which packages required assets for own deployment here on Github (https://github.com/benstadin/mapbox-gl-js-packager). 

Ideally, this project wouldn't be required and al server side assets would be created when mapbox-gl-js is built. 

Besides figuring how to create some required assets, it took me some time to figure the correct asset locations for glpyhs, styles, sprites etc. 
This is currently hardcoded (v1, v4, mapbox.xyz). It would good if these locations are defined at a single place instead, like in config.js. 

~Ben

**Comment by jfirebaugh** [comment]
Asset loading is already highly configurable in multiple ways:

* The locations of assets (sprites, glyphs, tiles) are already fully configurable via the style itself. Any URL can be used for the [sprite](https://www.mapbox.com/mapbox-gl-style-spec/#sprite), [glyphs](https://www.mapbox.com/mapbox-gl-style-spec/#glyphs), and [source](https://www.mapbox.com/mapbox-gl-style-spec/#sources) properties.
* The location of the style can be any URL.

Can you clarify what you are trying to do, and what issue you ran into?

**Comment by benstadin** [comment]
The mapbox:// scheme is confusing for other usage than with the MapBox API. It's probably not intended to be used for other cases than with the MapBox API, but there is no convenient way to define a common base URL for all requests otherwise. One has to configure all URLs one by one without base URL (in a worst case).
Maybe the existing API_URL can by optional config defined to be the base URL for all API requests, as it is the case for mapbox:// requests.

**Comment by jfirebaugh** [comment]
Yep, the `mapbox://` scheme is by design intended only for the Mapbox API. If you want to use another API, you must load a style that points to URLs for that API. A style is a JSON object, easily manipulated by Javascript, so if you want to create centralized logic for URL configuration, you could implement it as a function that takes as input one style object and returns a new style object with adjusted sprite, glyphs,  and source URLs.
