### ISSUE TITLE
Documentation: option to video source is 'urls' not 'url'

### ISSUE THREAD

**Issue by batpad** [mapbox/mapbox-gl-js#1646]
The documentation for VideoSource says to pass a param called `url` whereas it actually accepts a parameter called `urls`.

See: 

- https://github.com/mapbox/mapbox-gl-js/blob/b38be165418e3166c93f161bcdd54b29e98e0291/js/source/video_source.js#L16
- https://github.com/mapbox/mapbox-gl-js/blob/b38be165418e3166c93f161bcdd54b29e98e0291/js/source/video_source.js#L37

**Comment by jfirebaugh** [comment]
Thanks, fixed.
