### ISSUE TITLE
Touch support on IOS9

### ISSUE THREAD

**Issue by pixnlove** [mapbox/mapbox-gl-js#1648]
Do you support touch event on mobile ? I'm using Ionic framework but I'm encountering difficulties to implement a touch listener on my map. I tried:
```
$scope.map.on('click', function (e) {
    alert('I clicked on the map from the mobile');
});
```
When I'm doing this, nothing append on mobile but on a browser, this is working well.

Thanks for your help.

**Comment by mourner** [comment]
It should work. Can you reproduce the same problem without Ionic?

**Comment by pixnlove** [comment]
My entire application is made with Ionic, and I need this framework to emulate it in a mobile. I think you are right, there is a conflict with one of my library (Angular or Ionic) because on Safari mobile, there is no problem without Ionic and Angular. I tried with Ionic:
```
$scope.map.on('mousemove', function (e) {
    alert('Move');
});
```
And this is working well but it's not very clean. Is it related to the `_fireEvent` function in `mapbox-gl/js/ui/interaction.js`?

**Comment by mourner** [comment]
I think there was some special HTML attribute that disables Ionic handling of touch events on an HTML element, you should consult the docs — it might help. Closing as this is not a GL JS issue.

**Comment by pixnlove** [comment]
Thanks for your help @mourner ! 
For your information, my template looks like:
```
<div data-tap-disabled="true">
    <div id="map"></div>
</div>
```
