### ISSUE TITLE
Zoom range specification for style layers

### ISSUE THREAD

**Issue by AbrahamArun** [mapbox/mapbox-gl-js#1651]
```javascript
   {
    'id': id,
    'type': 'line',
    'source':'source_id',
    'layout': {
      'line-join': 'round',
      'line-cap': 'round'
    },
    'paint': {
      'line-color': 'red'
    },
    'interactive' : false,
    'minzoom': 14,
    'maxzoom': 20
  };
``` 
The above json is a style layer that I am adding to the map. For some reason, I cannot give a minzoom value greater than 14. Why is that so?
eg: I would like the layer to be visible in the zoom range of 18-20, how do I do that?

**Comment by mourner** [comment]
This was a bug that got fixed by https://github.com/mapbox/mapbox-gl-js/commit/3532d809a1e0208e80e2db8cefff49cb4e5202d6, will be present in the next release.

**Comment by AbrahamArun** [comment]
Thank you

**Comment by AbrahamArun** [comment]
@mourner I cloned the repo, and tried the same in the debug (master), the issue seems to be still there.

**Comment by mourner** [comment]
Weird, I'll check that.

**Comment by AbrahamArun** [comment]
Great

**Comment by AbrahamArun** [comment]
@mourner When can we expect this to be fixed? And is there a workaround in the mean time?
