### ISSUE TITLE
Built in sort function

### ISSUE THREAD

**Issue by TheChrisLove** [mapbox/mapbox-gl-js#1664]
Hey Mapbox,

I'm using this example as my base: https://www.mapbox.com/mapbox.js/example/v1.0.0/marker-list-click/

I'd like to sort the titles of these markers >> item.innerHTML = layer.toGeoJSON().properties.title;

Can this be built in?

**Comment by tmcw** [comment]
That's a Mapbox.js example - you're looking for the [Mapbox.js](https://github.com/mapbox/mapbox.js) issue tracker.

Sorting is possible without the feature being built-in, so we'll likely keep this outside of Mapbox.js's scope: here's a sketch of how it'd work:

```js
      var items = [];
      map.featureLayer.eachLayer(function(layer) {
          var menuItem = document.createElement('li');
          var items.push(menuItem);
          item.innerHTML = layer.toGeoJSON().properties.title;
          item.onclick = function() {
             map.setView(layer.getLatLng(), 14);
             layer.openPopup();
          };
      });
      // sort the items
      items.sort(function(a, b) {
        return a.innerHTML > b.innerHTML;
      });
      // add them in order
      items.forEach(function(item) {
        markerList.appendChild(item);
      });

```
