### ISSUE TITLE
Popup.setHTML() doesn't accept DOM node

### ISSUE THREAD

**Issue by De-Lac** [mapbox/mapbox-gl-js#1671]
I am migrating from MapBox.js to GL.js. I used to have custom Angular directives as markers' popup, showing their properties with a button to call a controller function.
Anyway, I noticed that Angular code is not recognized in mapboxgl.Popup.setHTML().
Is there a real reason, or it's just a bug?
Thank you

**Comment by mourner** [comment]
Currently `setHTML` only accepts HTML as a string, not as a DOM node. cc @jfirebaugh

**Comment by De-Lac** [comment]
I used to pass a String also to L.popup().setContent(), but it worked.  I don't pass the object, but something like ` content = "<my-custom-directive>...</my-custom-directive>"`. Is that considered a DOM node, even if it's a String?

**Comment by anandthakker** [comment]
@jfirebaugh would you be open to a PR adding support for passing a DOM element to setHTML?

**Comment by jfirebaugh** [comment]
Yes, although my preference would be to add a third method -- `setContent` or `setElement` -- rather than overloading `setHTML`.

**Comment by barnendu** [comment]
Unable to load angular component in mapbox-gl popup

var popUp=new mapboxgl.Popup().setHTML(<vas-map-hover [marker]='marker'></vas-map-hover>);
var markerObj = new mapboxgl.Marker(el)
          .setLngLat(marker.geometry.coordinates)
          .setPopup(popUp)
          .addTo(self.map);

**Comment by ryanhamley** [comment]
Hi @barnendu, this seems to be an issue because the directive/component you are passing into the popup is outside of Angular's scope and not triggering any compile phase. Since this is a framework specific problem, support for it is not something we'll be able to add to the library. You may be able to work around this by doing manual compilation of the component.
