### ISSUE TITLE
Custom style IDs don't seem to work

### ISSUE THREAD

**Issue by SandroGrzicic** [mapbox/mapbox-gl-js#1676]
Hi,

I'm trying to use a custom style that I created in Mapbox Studio Classic in mapbox-gl-js.

I've followed the tutorial at https://www.mapbox.com/mapbox-gl-js/api/:
 
    Map style. This must be an an object conforming to the schema described in the style reference, or a URL to a JSON style. To load a style from the Mapbox API, you can use a URL of the form mapbox://styles/:owner/:style, where :owner is your Mapbox account name and :style is the style ID. 

Clearly, this means that if my mapbox username is sandrogrzicic (not my actual mapbox username) and my style ID is 6b9a578d, my URL should be mapbox://styles/sandrogrzicic/6b9a578d, but this doesn't work; the library goes to the URL

    https://api.mapbox.com/styles/v1/sandrogrzicic/6b9a578d?access_token=(...)

and returns with a 404.

Built-in mapbox styles work just fine.

so, how do I correctly specify a custom style URL in mapbox-gl-js?

Thanks!

**Comment by lucaswoj** [comment]
Unfortunately, Studio Classic styles only work with [mapbox.js](https://www.mapbox.com/mapbox.js/api/v2.2.3/), not mapbox-gl-js.

> Map style. This must be an an object conforming to the schema described in the style reference, or a URL to a JSON style. To load a style from the Mapbox API, you can use a URL of the form mapbox://styles/:owner/:style, where :owner is your Mapbox account name and :style is the style ID. 

^ These docs could be a little clearer -- "a style from the Mapbox API" must be a GL style, as designed by the _new_ Mapbox Studio (not Classic). 

You will need to either use [mapbox.js](https://www.mapbox.com/mapbox.js/api/v2.2.3/) or redesign your style in the _new_ Mapbox Studio. If you're interested in the latter, I'm happy to send you an invite!

**Comment by SandroGrzicic** [comment]
Hi,

thanks for the heads up.

We are indeed interested in using the new Mapbox Studio. I have signed us up already on our corporate account, but I'd be happy if you could send me an invite too at sandro@livware.com. :)

**Comment by lucaswoj** [comment]
Just enabled Studio access on your account @SandroGrzicic! Happy mapping. :earth_asia: :earth_americas: :earth_africa:

**Comment by SandroGrzicic** [comment]
Thank you!
