### ISSUE TITLE
Use browser-request instead of request for lighter footprint?

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#1677]
Mapbox GL seems to be bundling the request module, which was designed to run on a node server. Why not bundle browser-request instead?
Request zipped is 170 Kb, whereas browser-request is 12 Kb.

**Comment by jfirebaugh** [comment]
The request module is not included in the browserified bundle. It's required in [ajax.js](https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/ajax.js), but that file is only used for development-time testing. The browser bundle uses [browser/ajax.js](https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/browser/ajax.js), which is plain XHR.

**Comment by misterfresh** [comment]
Ok thanks for explaining!

2015-11-05 17:43 GMT+01:00 John Firebaugh <notifications@github.com>:
