### ISSUE TITLE
Fix vertical and horizontal artifacts on Firefox

### ISSUE THREAD

**Issue by yuvadm** [mapbox/mapbox-gl-js#1679]
Getting these rendering artifacts on OS X + Firefox:

![screen shot 2015-11-06 at 10 12 30](https://cloud.githubusercontent.com/assets/315080/10992562/a8a59bf4-846f-11e5-9f7e-3c5700ee5656.png)
![screen shot 2015-11-06 at 10 18 22](https://cloud.githubusercontent.com/assets/315080/10992572/c3e274fa-846f-11e5-96d5-b75c0205225d.png)

Code is built on the examples from the docs:

``` js
var mapStyle = {
    "version": 8,
    "name": "Dark",
    "sources": {
        "mapbox": {
            "type": "vector",
            "url": "mapbox://mapbox.mapbox-streets-v6"
        },
    },
    "sprite": "mapbox://sprites/mapbox/dark-v8",
    "glyphs": "mapbox://fonts/mapbox/{fontstack}/{range}.pbf",
    "layers": [
        {
            "id": "background",
            "type": "background",
            "paint": {"background-color": "#111"}
        },
        {
            "id": "boundaries",
            "source": "mapbox",
            "source-layer": "admin",
            "type": "line",
            "paint": {"line-color": "#797979"},
            "filter": ["all", ["<=", "admin_level", 2], ['==', 'maritime', 0]]
        },
        {
            "id": "water",
            "source": "mapbox",
            "source-layer": "water",
            "type": "line",
            "paint": {"line-color": "#797979"}
        },
        {
            "id": "cities",
            "source": "mapbox",
            "source-layer": "place_label",
            "type": "symbol",
            "layout": {
                "text-field": "{name_en}",
                "text-font": ["DIN Offc Pro Bold", "Arial Unicode MS Bold"],
                "text-size": {"stops": [[4, 9], [6, 12]]}
            },
            "paint": {
                "text-color": "#969696",
                "text-halo-width": 2,
                "text-halo-color": "rgba(0, 0, 0, 0.85)"
            }
        },
        {
            "id": "states",
            "source": "mapbox",
            "source-layer": "state_label",
            "type": "symbol",
            "layout": {
                "text-transform": "uppercase",
                "text-field": "{name_en}",
                "text-font": ["DIN Offc Pro Bold", "Arial Unicode MS Bold"],
                "text-letter-spacing": 0.15,
                "text-max-width": 7,
                "text-size": {"stops": [[4, 10], [6, 14]]}
            },
            "filter": [">=", "area", 80000],
            "paint": {
                "text-color": "#969696",
                "text-halo-width": 2,
                "text-halo-color": "rgba(0, 0, 0, 0.85)"
            }
        }
    ]
};

var map = new mapboxgl.Map({
    container: 'map',
    maxZoom: 10,
    minZoom: 2,
    zoom: 6,
    center: [35, 32],
    style: mapStyle,
    hash: false
});
```

**Comment by lucaswoj** [comment]
I created a preview out of the example code [here](https://jsfiddle.net/gwyaja6c/). 

Was not able to repro the bug on my OSX + Firefox setup. Could you tell me a little more about your system @yuvadm? Would you mind sharing the model # of your computer?

**Comment by lucaswoj** [comment]
Are you using the latest version of `mapbox-gl-js`? (v0.11.2)

**Comment by yuvadm** [comment]
Repros for me on the jsfiddle as well, and yes I'm on v0.11.2

What details do you need? This is a mid-2010 13" MBP running OS X 10.9.5

**Comment by lucaswoj** [comment]
@yuvadm Are you only seeing these artifacts in Firefox? Are Chrome or Safari affected?

**Comment by yuvadm** [comment]
@lucaswoj chromium is not affected, similar to #1680

**Comment by yuvadm** [comment]
Another nice sample taken from https://reactmaps.firebaseapp.com/

![screen shot 2015-12-06 at 11 15 15](https://cloud.githubusercontent.com/assets/315080/11612624/bcc1e432-9c0a-11e5-9814-436288116fae.png)

**Comment by jingsam** [comment]
mapbox-gl-js v0.20.1 windows 10 chrome 51
![image](https://cloud.githubusercontent.com/assets/1522494/16605983/8bb59218-4366-11e6-9e5b-ae893f89a9e3.png)

mapbox-gl-js v0.11.0 windows 10 chrome 51
![image](https://cloud.githubusercontent.com/assets/1522494/16606027/fae7eabe-4366-11e6-8893-b0eea2ea80c8.png)

**Comment by timiyay** [comment]
I've also encountered these line artifacts when using Mapbox's Static Image API. The resulting JPG images have the same tile seam lines.

So whatever Mapbox uses to render their own tiles is likely suffering from the same bug.

**Comment by andrewharvey** [comment]
Looks like the same issue as I'm having here https://github.com/mapbox/mapbox-gl-js/issues/2676 though for me I see the issue on Chrome.

**Comment by jmersonuo** [comment]
Still seeing this problem several years later....
Looks like it was thought to be fixed  [here](https://github.com/mapbox/mapbox-gl-js/pull/4636)
https://www.cms.int/en/gium/migration-atlas -> click on the "Kob" and zoom in. Seeing it in Firefox and Edge and didn't keep testing.
![Image](https://github.com/user-attachments/assets/b12ed2a2-f275-4a13-b6e4-e422c9ae1a63)
