### ISSUE TITLE
Fix water fill overflow on Firefox

### ISSUE THREAD

**Issue by yuvadm** [mapbox/mapbox-gl-js#1680]
Water fill on OS X + Firefox:
![screen shot 2015-11-06 at 10 27 25](https://cloud.githubusercontent.com/assets/315080/10992694/01406324-8471-11e5-97eb-22a97a4eabba.png)
(also seeing artifacts from #1679)

Same thing on Chromium:
![screen shot 2015-11-06 at 10 27 19](https://cloud.githubusercontent.com/assets/315080/10992695/0142d852-8471-11e5-975f-1f405b6db06a.png)

Code is same as in #1679 with an additional:

``` js
{
    "id": "waterfill",
    "source": "mapbox",
    "source-layer": "water",
    "type": "fill",
    "paint": {"fill-color": "#111122"}
},
```

**Comment by lucaswoj** [comment]
https://jsfiddle.net/7h1hgxzh/

Was also unable to repro this bug. Asking for more details in #1679.

**Comment by yuvadm** [comment]
Repros in this jsfiddle as well.

**Comment by jfirebaugh** [comment]
Can anyone still reproduce this issue?
