### ISSUE TITLE
Strange lines when raster data layer is rendered on top of raster satellite layer

### ISSUE THREAD

**Issue by sdotson** [mapbox/mapbox-gl-js#1684]
There are these strange horizontal lines that appear when I add a raster layer with data uploaded to Mapbox on top of a satellite layer. Any idea what might be causing these and how to get rid of them?

I attached a screenshot and created a JS Fiddle illustrating the issue.

http://jsfiddle.net/studotson/2zqbr15k/2/

![screen shot 2015-11-09 at 1 12 47 pm](https://cloud.githubusercontent.com/assets/5664775/11042273/23cd1926-86e4-11e5-81f2-54d9346b6e9d.png)

**Comment by lucaswoj** [comment]
I can reproduce this bug. I don't have any immediate ideas about what might be causing it but I will dig in this week.

**Comment by sdotson** [comment]
Hello,

Any update on this bug? We're trying to launch tomorrow.

Thanks!

**Comment by lucaswoj** [comment]
@sdotson I'm happy to report that things was resolved with #1705! I'll be publishing a v0.11.4 release today that includes the fix. 

Note that you might need to tweak your style slightly. Now that we support alpha blending in rasters, your overlay renders a little differently.

## Before

![screen shot 2015-11-16 at 11 02 59 am](https://cloud.githubusercontent.com/assets/281306/11191731/a9b1ebb2-8c51-11e5-874a-01e908a3ebf4.png)

## After

![screen shot 2015-11-16 at 11 03 13 am](https://cloud.githubusercontent.com/assets/281306/11191730/a9af7378-8c51-11e5-908c-487e936130c4.png)

**Comment by lucaswoj** [comment]
Please reopen this issue if the fix doesn't work for you.

**Comment by bhousel** [comment]
> Any update on this bug? We're trying to launch tomorrow.

FYI, v0.11.4 is released now, try it out!

**Comment by sdotson** [comment]
It works great! Thanks everybody.
