### ISSUE TITLE
no way to set position of attribution control

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#1689]
Attribution control should be able to take an `options` argument with a `position` property.

**Comment by tristen** [comment]
Doesn't look like this has been fixed? From `/test/manual/attribution.html`

<img width="1041" alt="screen shot 2015-12-22 at 2 05 31 pm" src="https://cloud.githubusercontent.com/assets/61150/11963468/258f8b98-a8b5-11e5-9257-95d922ae5216.png">

```js 
var map = new mapboxgl.Map({
  container: 'map',
  style: 'mapbox://styles/mapbox/bright-v8',
  attributionControl: false
});

new mapboxgl.Attribution({position: 'top-left'}).addTo(map);
```

**Comment by jfirebaugh** [comment]
Try `npm run build`.

**Comment by tristen** [comment]
Ah great! I was le confused because of ^ and that this change isn't in `v0.12.1`
