### ISSUE TITLE
Artifacts on OS X  Firefox and Chrome

### ISSUE THREAD

**Issue by OmniEarthDev** [mapbox/mapbox-gl-js#1691]
I am seeing rendering artifacts on OS X, on Firefox and Chrome using Mapbox version 0.11.2.
The layer is our own parcel layer.

The artifacts are not present on zoom level 14.
![screen shot 2015-11-10 at 12 21 55 pm](https://cloud.githubusercontent.com/assets/15254470/11070085/a89032f6-87a7-11e5-9738-0dfda3479ab3.png)

In zoom level 15 they start to appear.
![screen shot 2015-11-10 at 12 21 34 pm](https://cloud.githubusercontent.com/assets/15254470/11070105/c3f31216-87a7-11e5-8f34-97cb137ac500.png)

Any ideas?

**Comment by lucaswoj** [comment]
Looks similar to #1679 (though that's *only* in Firefox)

**Comment by lucaswoj** [comment]
@OmniEarthDev Can you tell me a little about how the parcel layer was created? Was the data's maxzoom set to 14 or 15?

**Comment by OmniEarthDev** [comment]
There is no minZoom, maxZoom set on the map so the default of 0-22 are in
effect.
The tiles were created with zooms  0-23.

On Tue, Nov 10, 2015 at 2:22 PM, Lucas Wojciechowski <
notifications@github.com> wrote:

> @OmniEarthDev <https://github.com/OmniEarthDev> Can you tell me a little
> about how the parcel layer was created? Was the data's maxzoom set to 14 or
> 15?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapbox/mapbox-gl-js/issues/1691#issuecomment-155538016>
> .
>



-- 
Ruth Raponi
Senior Software Engineer
OmniEarth <http://omniearth.net>

Tel: +1 888 838 6318 Ext. 709
ruth.raponi@omniearthinc.com

-- 
CONFIDENTIALITY. This email and any attachments are confidential, except 
where the email states it can be disclosed; it may also be privileged. If 
received in error, please do not disclose the contents to anyone, but 
notify the sender by return email and delete this email (and any 
attachments) from your system.

**Comment by OmniEarthDev** [comment]
Problem was found when creating tiles with intersection

**Comment by lucaswoj** [comment]
@OmniEarthDev could you elaborate on this? How were you able to resolve the problem? 

 > Problem was found when creating tiles with intersection
