### ISSUE TITLE
Rotated SVG symbol anti-aliasing

### ISSUE THREAD

**Issue by knikel** [mapbox/mapbox-gl-js#1693]
Hi mapbox-team!
I was wondering whether it is possible to apply anti-aliasing/smoothing of some sort to a rotated symbol SVG shape?

To give more context: I have a custom symbol, which I rotate at various amounts of degrees by setting `icon-rotate`, it works and behaves as expected, but oftentimes it looks jagged. Below are screenshots of retina and non retina rendering.

<img width="563" alt="retina-svg" src="https://cloud.githubusercontent.com/assets/1574656/11092953/8940e810-8887-11e5-81ba-d438145e87b9.png">

![non-retina-svg](https://cloud.githubusercontent.com/assets/1574656/11092958/92e314f6-8887-11e5-9d9b-d95d2d15ba57.png)

**Comment by lucaswoj** [comment]
Might be related to #1601

**Comment by mourner** [comment]
Yeah, the current workaround for these things is using SDF icons, although it's not very well documented.

**Comment by lucaswoj** [comment]
This was fixed as part of #2738 🎉
