### ISSUE TITLE
Uncaught TypeError in SymbolBucket.addSymbols

### ISSUE THREAD

**Issue by bhousel** [mapbox/mapbox-gl-js#1694]
With v0.11.3, opened debug page and zoomed out.

![screenshot 2015-11-11 12 00 14](https://cloud.githubusercontent.com/assets/38784/11097226/349df714-886c-11e5-84c5-e665c8ad5bff.png)
![screenshot 2015-11-11 12 00 24](https://cloud.githubusercontent.com/assets/38784/11097225/349af92e-886c-11e5-947d-00bf236c0586.png)

Uncaught TypeError: buffer.push is not a function.

**Comment by lucaswoj** [comment]
This happens because something is trying to push items onto the buffer after it has been transferred to the main thread. I'll look into a fix today. The good news is this doesn't affect rendering -- it just causes errors :grimacing:

**Comment by lucaswoj** [comment]
> The good news is this doesn't affect rendering

:point_up: this turned out to not quite be true!
