### ISSUE TITLE
Support a ratchety-zoom mode

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1695]
Noticed that some code that uses gl-js hacks it to snap to integer zoom levels. We should support this in core.

**Comment by lucaswoj** [comment]
:+1:

**Comment by lucaswoj** [comment]
Just a note for context: the biggest advantage (in my mind) of enabling "ratchety zoom" is improving  rendering performance.

**Comment by mourner** [comment]
How would this improve rendering performance?

**Comment by lucaswoj** [comment]
My impression was that some users were using rachety zooming to avoid some calculations on fractional zoom changes. Is that not your understanding, @mourner?

**Comment by mourner** [comment]
@lucaswoj I don't think there's a significant performance difference between a frame when zooming and a frame when panning. Fractional vs integer zoom levels shouldn't affect performance as well. 

The only use case I can think of for snapping to integer zoom levels is compatibility with stuff like Leaflet, but https://github.com/mapbox/mapbox-gl-leaflet doesn't need a GL JS option for that because it synchronizes based on its own events.

@tmcw can you elaborate more on use cases and how that would work exactly? Would it be completely discrete snapping (one frame per integer zoom), or animated zooming between integer zooms that you can't stop?

**Comment by tmcw** [comment]
The [ArcGIS API](https://developers.arcgis.com/javascript/3/sandbox/sandbox.html?sample=layers_vector) is one example - There's another scroll-zooming example I can dig up that snapped to integer zoom levels. Every example I've seen so far supports animated zoom but then snaps to a level, and I'm pretty sure that it's about two things:

* [Tradition!](https://www.youtube.com/watch?v=sWSoYCetG6A)
* Making raster imagery look nice, maybe? Since you don't have over or under-scaled images?

**Comment by zavan** [comment]
"Making raster imagery look nice, maybe? Since you don't have over or under-scaled images?"

That is the point for me.

**Comment by lucaswoj** [comment]
@zavan You can use some iteration of this to get the behavior you're looking for:

```js
map.on('moveend', function() {
    map.setZoom(Math.round(map.getZoom()));
});
```

**Comment by aliir74** [comment]
Do you support this feature now? The set zoom function sharply shakes map and isn't good for me.

**Comment by vwong** [comment]
This worked for me:

```js
import { debounce } from 'lodash'
import { Map } from 'mapbox-gl'

const map = new Map({
  scrollZoom: false
})

map.on('wheel', debounce(({ originalEvent: { wheelDelta } }) => {
  map.setZoom(map.getZoom() + Math.sign(wheelDelta))
}, 100))
```

**Comment by HarelM** [comment]
@vwong I assume your solution will not work when using the `fitBounds` function, right?
So the only valid workaround is to use @lucaswoj answer?

**Comment by vwong** [comment]
@HarelM It should work. Here's a fuller version of my example. Works on touch devices too.

```
const integerZoom = debounce(({ originalEvent: { deltaY, detail, wheelDelta } }) => {
  const delta = wheelDelta || -deltaY || -detail
  const zoom = Math.round(map.getZoom()) + (delta > 0 ? 1 : -1)

  map.setZoom(zoom)
}, 50, { leading: true, trailing: false })

const ratchet = () => {
  const zoom = Math.round(map.getZoom())
  if (zoom !== map.getZoom()) {
    map.setZoom(zoom)
  }
}

const ratchetOn = () => {
  map.setZoom(Math.round(map.getZoom()))
  map.on('idle', ratchet)
  map.on('wheel', integerZoom)
  map.scrollZoom.disable()
}

const ratchetOff = () => {
  map.off('idle', ratchet)
  map.off('wheel', integerZoom)
  map.scrollZoom.enable()
}
```

In my use case, I needed to turn ratchet on/off depending on other external factors. Good luck!

**Comment by geoyogesh** [comment]
> @zavan You can use some iteration of this to get the behavior you're looking for:
> 
> ```js
> map.on('moveend', function() {
>     map.setZoom(Math.round(map.getZoom()));
> });
> ```

this snippet will cause 
ERROR RangeError: Maximum call stack size exceeded

**Comment by geojs** [comment]
> > @zavan You can use some iteration of this to get the behavior you're looking for:
> > ```js
> > map.on('moveend', function() {
> >     map.setZoom(Math.round(map.getZoom()));
> > });
> > ```
> 
> this snippet will cause
> ERROR RangeError: Maximum call stack size exceeded

@geoyogesh to not have the ERROR RangeError:

```js
map.on('moveend', function () {
  const zoom = Math.round(map.getZoom())
  if (zoom !== map.getZoom()) {
    map.setZoom(zoom)
  }
})
 ```

**Comment by geoyogesh** [comment]
i wanted rachety zoom mode because i am using dynamic map service and mapbox aggregively fetches data during factional zoom... i disabled zoom scroll which made api fetch calls more friendly 
map.scrollZoom.disable();

user expecirece was bad while using map.setZoom so i prefered disabling zoom scroll
Thanks

**Comment by IgnacioHeredia** [comment]
As far as the wheel zoom is concerned, you are probably looking for:
```javascript
map.scrollZoom.setWheelZoomRate(1);
```
after starting from an integer zoom level.
