### ISSUE TITLE
Alpha blending issues for raster layers

### ISSUE THREAD

**Issue by gribbet** [mapbox/mapbox-gl-js#1698]
Raster layers with alpha layers are not blended correctly. 

Here's an example of a rasterized contour layer with alpha over a basemap:
![incorrect](https://cloud.githubusercontent.com/assets/1776091/11101145/28971d94-886a-11e5-8eb2-8b8e642ff1f4.png)

This is how it looks in Leaflet
![correct](https://cloud.githubusercontent.com/assets/1776091/11101180/613d12fc-886a-11e5-9048-4c516f414c48.png)

**Comment by lucaswoj** [comment]
Rebased, squashed, and updated the test suite in #1705. Will merge there once CI passes.
