### ISSUE TITLE
Add a legend generation example

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1700]
It would be useful to have an example showing how to generate a legend based on information stored in a GL style. This could be:
- a choropleth legend with ranges (should this happen before or after data-driven styles...)
- symbol legend pulling from the sprite
- road type legend pulling from line styles

**Comment by bengolder** [comment]
I just came across a need for making legends. So +1 for this example. If anyone has any suggestions for how to start, they would be greatly appreciated. I would be happy to share an example of work I make on this.

**Comment by tristen** [comment]
@tmcw For legend generation are you seeing this as:

- A legend control added to mapbox-gl-js with example using it?
- A separate plugin with example?
- A simple example not extending control but just using custom html/css?

**Comment by jfirebaugh** [comment]
Assuming the custom HTML/CSS is straightforward, the third one.

**Comment by tristen** [comment]
OK great +1 on the third option myself.

**Comment by mpjavali** [comment]
+1

**Comment by tristen** [comment]
> - a choropleth legend with ranges (should this happen before or after data-driven styles...)

This is done with https://www.mapbox.com/mapbox-gl-js/example/updating-choropleth/

**Comment by fedex1** [comment]
It seems that https://www.mapbox.com/mapbox-gl-js/example/updating-choropleth/ is not working properly. This is what we see in chrome and firefox:

I believe it is supposed to start at the state summary and then go to the county detail.  (I believe that is what is used to do)  And that is what the documentation says "Using 2014 census data, display state or county population depending on zoom level."

![screen shot 2016-02-20 at 12 58 25 pm](https://cloud.githubusercontent.com/assets/167614/13198233/bf6624de-d7d1-11e5-9615-7aeaa3f50c2a.png)

**Comment by jfirebaugh** [comment]
Thanks for the report @fedex1. I've diagnosed the issue field a separate ticket: https://github.com/mapbox/mapbox-gl-js/issues/2162.
