### ISSUE TITLE
Ditch glify for brfs

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#1701]
From https://github.com/mapbox/glify/pull/7#issuecomment-153504913:

> I'm not sure why we even need glify though. The only thing it does nowadays is run the source through glsl-compiler, which I guess is for minification but probably doesn't produce that much benefit. We might be better off avoiding the hassle and using brfs instead.

I think we should do this.

cc @jfirebaugh @ansis @tmcw @kkaefer

**Comment by tmcw** [comment]
We could also potentially go for "none of the above" and just use a comment-hack or string concatenation (

```js
function() {
/*
shader code... shader code
*/
}.toString().split('\n').slice(2, -4)
```

or similar.

Doesn't give us nice highlighting, but removes some complexity.

**Comment by jfirebaugh** [comment]
Hitting issues with glify + Node 5.0, JFDI'ing this.
