### ISSUE TITLE
update test-suite ignores for headless-gl 2.0

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1704]
With headless-gl 2.0, it looks like we can update the test-suite to remove a bunch of ignores for rendering tests that were failing under headless-gl 1.x.

**Comment by mourner** [comment]
@jfirebaugh if you update ignores/thresholds anyway, upgrade to pixelmatch 4.0 too.

**Comment by jfirebaugh** [comment]
Done in https://github.com/mapbox/mapbox-gl-test-suite/commit/4e9f7f8b8deb44eebfdd1b25142286b9130be6c5. Upgrading pixelmatch is https://github.com/mapbox/mapbox-gl-test-suite/issues/53.
