### ISSUE TITLE
collisionDebug broken in v0.11.3

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-js#1706]
Not seeing collision boxes, even after map pan/zoom.

**Comment by bhousel** [comment]
bisect implicates 0bfcb6972a299bc8aa6e51449bbaf4090b7f5738

**Comment by lucaswoj** [comment]
Ah! My fault. I'll have a fix this morning.

**Comment by bhousel** [comment]
Thanks!  Now I see _some_ of the collision bboxes, but not all of them.  Maybe an issue with draw order?

**Comment by lucaswoj** [comment]
D'oh. I `++`-ed when I should've `+= 8`-ed.

**Comment by lucaswoj** [comment]
Fixed in d7ea136ac969ab8e08bb4db4963388b2e6679638

**Comment by bhousel** [comment]
You fixed it so fast, I didnt even get to show you this awesome gif I made:

![debug collision boxes2](https://cloud.githubusercontent.com/assets/38784/11128737/aec45212-8949-11e5-83d1-209852d21dc6.gif)

**Comment by bhousel** [comment]
BTW Arlington National Cemetery is a great place to test stuff at tile boundaries.

**Comment by lucaswoj** [comment]
Great tip! Thanks @bhousel. Are we good to close this ticket now?

**Comment by bhousel** [comment]
Yes, looks great, thank you!
