### ISSUE TITLE
Document StyleBatch interface

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#1707]
https://www.mapbox.com/mapbox-gl-js/api/#Map.batch references the `StyleBatch` interface, but that interface [isn't documented](https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style_batch.js)

**Comment by lucaswoj** [comment]
Thanks @anandthakker! This should be fixed.

**Comment by anandthakker** [comment]
:+1: 

Note: I'm not seeing a fix in the commit history...

**Comment by lucaswoj** [comment]
I meant: "This ought to be fixed'! I'll get this done later today.

**Comment by anandthakker** [comment]
Ahhhh I see. Cool thanks!

**Comment by lucaswoj** [comment]
Fixed in #1724
