### ISSUE TITLE
Swapping out image overlays on a map instance

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#1710]
We are using this resource to put an image overlay on a Mapbox GL map.
https://www.mapbox.com/mapbox-gl-js/example/image-on-a-map/

When a user creates a map widget in our application, we send a request to our server for an image overlay to be displayed on top of the mapbox map.

When they move the map around, we have an event handler attached on 'move' to send a new request to the server for the image overlay of the new region.

In order to replace the overlay, we manually swap out the old overlay by calling a couple of the methods on the map instance.

1) We first add the new region overlay by calling `map.addSource()` then `map.addLayer()` with the new image.
2) Then we remove the old region overlay by calling `map.removeLayer()` then `map.removeSource()` to remove the old image.

To make the transition a bit smoother, we hardcoded a 20 millisecond setTimeout before removing the old overlay, however the two overlays still exhibit a slight flickering behavior when the old overlay is removed. 

We were hoping there was an event along the lines of 'overlayloaded' on which we could attach a handler to remove the old overlay as soon as the new one loads on the map.

The issue might stem from the fact that map.addSource() takes in the url of the overlay and will presumably fetch the resource asynchronously.

Is there a better method out there for swapping overlays seamlessly?

**Comment by lucaswoj** [comment]
Hi @DannyDelott! I'm sorry that we never got around to answering this issue for you. 

There is currently no event that indicates when an image has loaded. One workaround is to check `map.style.sources[sourceId].loaded()` within each `render` event. We will introduce a better API within #1715
