### ISSUE TITLE
Display an error message when a used source is removed and not re-added 

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1711]
Code: http://jsfiddle.net/rwccfmej/

cc/ @lucaswoj

**Comment by peterqliu** [comment]
(I also expected every layer referencing that source to disappear in a `poof`)

**Comment by lucaswoj** [comment]
> (I also expected every layer referencing that source to disappear in a poof)

I would prefer if we didn't support having layers with undefined sources or permanently removing sources with dependent layers. 

We should have a better error message in this case.
