### ISSUE TITLE
"circle-stroke-*" style properties 

### ISSUE THREAD

**Issue by vicapow** [mapbox/mapbox-gl-js#1713]
Currently, we can only style geoJSON points using the circle layer type but that doesn't give us the flexibility to style circles with a border. We can get close with two circle layers with different radii but the effect isn't ideal when they overlay.

<img width="139" alt="screen shot 2015-11-12 at 4 02 51 pm" src="https://cloud.githubusercontent.com/assets/583385/11135127/003dc954-8957-11e5-93a1-3dfbd723a868.png">

**Comment by bhousel** [comment]
Yes, we don't yet support separate stroke and fill parameters for circle layer type.  Can you open this issue in the [mapbox-gl-style-spec repository](https://github.com/mapbox/mapbox-gl-style-spec/issues)?   We need to consider proposals like this in the context of the whole Mapbox GL ecosystem.

I guess it might also be possible to achieve the effect you're looking for with a symbol layer type..

**Comment by lucaswoj** [comment]
I just opened a ticket on the `mapbox-gl-style-spec` repository https://github.com/mapbox/mapbox-gl-style-spec/issues/379 :smiley: We can leave this ticket while we nail down the syntax over there.
