### ISSUE TITLE
Render all symbols in a certain area or clustering workaround?

### ISSUE THREAD

**Issue by rishabhjain30** [mapbox/mapbox-gl-js#1716]
I want to use mapbox gl js for rendering a large no. of markers and each of those markers have unique attributes such as id. But, on the map at certain zoom levels I can only see some markers and not all.

**Comment by jfirebaugh** [comment]
Make sure the symbol layer has [`"icon-allow-overlap": true`](https://www.mapbox.com/mapbox-gl-style-spec/#icon-allow-overlap) and possibly ["icon-ignore-placement": true`](https://www.mapbox.com/mapbox-gl-style-spec/#icon-ignore-placement) as well. If that doesn't resolve the issue, please create a JSFiddle that demonstrates the issue.
