### ISSUE TITLE
Replacing tile layer in mapbox.js with GL version

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-gl-js#1718]
We've several maps using lots of standard Mapbox tile layers, rendered in Mapbox Studio Classic, with interactivity enabled using mapbox.js and mapbox/leaflet plugins. We also have a GL version of the same basemap. I notice that some of your examples have both the mapbox-gl.js and the mapbox.js in the head. Is there a simple migration path we can test that will allow us to replace a tiled base layer with a GL version whilst still retaining the leaflet marker and popup objects?

**Comment by mourner** [comment]
There's a separate project to do that: https://github.com/mapbox/mapbox-gl-leaflet
