### ISSUE TITLE
Documentation for events look like methods

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#1719]
The generated documentation for events is formatted poorly. For instance, the `load` event for a map looks like a method with arguments.

https://www.mapbox.com/mapbox-gl-js/api/#Map.load

**Comment by lucaswoj** [comment]
Y, we differentiate these in the sidebar but not here. 

ref 005279fe79c9a826e3fc697c6ca7da7b19eccc96 https://github.com/mapbox/mapbox-gl-js/pull/1663

**Comment by lucaswoj** [comment]
@bhousel The preferred solution is to use `{{#if event}}` blocks to style these sections differently. I don't think there'll by any additional upstream changes around events.

**Comment by bhousel** [comment]
@lucaswoj  I think @scothis was talking about this:

<img width="668" alt="screenshot 2015-11-16 16 02 05" src="https://cloud.githubusercontent.com/assets/38784/11194718/ab9d000e-8c7b-11e5-8b98-396ef0038b2b.png">

**Comment by scothis** [comment]
<img width="668" alt="ab9d000e-8c7b-11e5-8b98-396ef0038b2b" src="https://cloud.githubusercontent.com/assets/302992/11194790/face2446-8c62-11e5-87cf-a0e493608575.png">

**Comment by scothis** [comment]
The link to the source goes to the method that is being parsed for parameters. It should instead either not be included, or link to the documentation block.

**Comment by bhousel** [comment]
So, by moving the documentation block after the code, I now get this..
The link to source doesn't go quite to the right place, but at least the phantom parameters are gone.

<img width="680" alt="screenshot 2015-11-16 16 09 11" src="https://cloud.githubusercontent.com/assets/38784/11194854/8681a102-8c7c-11e5-8180-21eec0b8b3ff.png">

**Comment by tmcw** [comment]
Proper upstream issue in documentation is https://github.com/documentationjs/documentation/issues/205
