### ISSUE TITLE
Method to change a layer's source

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1722]
Need a method for changing a layer's `source`. Currently, we need to remove and re-add the layer with the new source.

**Comment by jfirebaugh** [comment]
I think you should just remove and re-add the layer. Any implementation inside gl-js would do just that.

**Comment by jback22** [comment]
try:
`const U = require('mapbox-gl-utils').init(map);`
`map.U.setData('mysource', data);`
this worked for me, thanks to @stevage

**Comment by stevage** [comment]
Oh, the method I was referring to is the `setLayerSource` one:

`map.U.setLayerSource('mylayer', 'mynewsource')`

**Comment by backspaces** [comment]
There is a possibly new function that simplifies this:

    map.getSource("source-id").setData(updatedGeoJSONData);

It is referred to here:

https://stackoverflow.com/questions/66829445/mapbox-gl-setdata-to-update-layer
