### ISSUE TITLE
Method to change the map's minZoom/maxZoom

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1723]

**Comment by netconstructor** [comment]
I have been looking to achieve the same exact thing - if anyone has been
able to accomplish this please outline the proper steps. CH
On Nov 13, 2015 12:29 PM, "Peter Liu" <notifications@github.com> wrote:

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapbox/mapbox-gl-js/issues/1723>.
>

-- 
CONFIDENTIALITY NOTICE: This e-mail message from NetConstructor (including 
all attachments) is for the sole use of the intended recipient(s) and may 
contain confidential and privileged information. Any unauthorized review; 
use, disclosure, copying or distribution is strictly prohibited. If you are 
not the intended recipient, please contact the sender by reply e-mail and 
destroy all copies of the original message.

**Comment by andrewharvey** [comment]
I'm also interested in this capability.

**Comment by ansis** [comment]
This was implemented in https://github.com/mapbox/mapbox-gl-js/pull/2243 and has been released as part of v0.16.0
