### ISSUE TITLE
Transparency being rendered in raster tiles.

### ISSUE THREAD

**Issue by DevinClark** [mapbox/mapbox-gl-js#1728]
Sample code: https://github.com/DevinClark/mapbox-gl-swarm/tree/gh-pages (including tiles in the project)
Demo: http://devinclark.github.io/mapbox-gl-swarm/

I am having issues with rendering raster tiles from WDT's tile server.

The blue and green areas on the image do not render when viewing the image anywhere else (browser, image editor, etc). I'm told from the team that maintains this that the areas are radar coverage, and set to 0 alpha in the image.

<img width="579" alt="2015-11-13 at 5 02 pm" src="https://cloud.githubusercontent.com/assets/353563/11159849/f076b1e8-8a28-11e5-87b8-e2f908baf4ec.png">

Here is one of the tiles rendered by the browser
![](https://raw.githubusercontent.com/DevinClark/mapbox-gl-swarm/gh-pages/tiles/2/0/1.png)

(I believe the white background is related to #1395 and not the subject of this issue)

Is there anything else I can add to help clarify?

**Comment by lucaswoj** [comment]
Can you check if #1698 resolves the issue? (just landed in `master`, not yet part of a release)

**Comment by lucaswoj** [comment]
Great news! #1698 seems to resolve your issue. 

<img width="854" alt="screen shot 2015-11-13 at 4 32 52 pm" src="https://cloud.githubusercontent.com/assets/281306/11160814/45c8490e-8a24-11e5-9473-779a4e6bfb70.png">

All you need to do is adjust `package.json` to point to `master`
```
    "mapbox-gl": "mapbox/mapbox-gl-js#master"
```

We should be releasing v0.11.4 with alpha blending early next week.

**Comment by DevinClark** [comment]
Yes it does. Thank you!
