### ISSUE TITLE
Smooth zoom transition

### ISSUE THREAD

**Issue by nthtran** [mapbox/mapbox-gl-js#1730]
`mapbox-gl-js` used to have smooth zoom transition on mousewheel, as seen here: https://www.mapbox.com/blog/mapbox-gl-js/

Has this been disabled or is there a way to enable it?

**Comment by mourner** [comment]
What do you mean, used to have? It works perfectly with the latest release too: https://www.mapbox.com/mapbox-gl-js/examples/

**Comment by nthtran** [comment]
Strange I'm not seeing it. The way it works for me is it immediately jumps to the next zoom level instead of smoothly animatiing from one level to another.

**Comment by mourner** [comment]
Can you provide more details? Is it reproducible on that examples page? What browser, OS and mouse do you use?

**Comment by nthtran** [comment]
Sure I was about to do that after a bit more testing.

So I see this behaviour consistently on both that examples page and Mapbox Studio beta. I tested on latest versions of Chrome and Firefox on Ubuntu 14.04 and Windows 8. I used a Razer mouse and then a Toshiba.

The map in the blog post I linked works on perfectly for me with smooth transitions between zooms. It was an older version of `mapbox-gl-js` so I assumed this feature had been disabled by default or something in latest versions.

I haven't looked at the source code much at all but does setting `duration` to `0` [here](https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/handler/scroll_zoom.js#L110) have anything to do with it?

**Comment by mourner** [comment]
Ah yes, probably. Will look into this.

**Comment by yuvadm** [comment]
A nice workaround here is to use:

```js
map.flyTo({zoom: nextZoom})
```

(kudos to @mushon for the idea)

**Comment by Bernoulli-IT** [comment]
You can now use [zoomTo](https://docs.mapbox.com/mapbox-gl-js/api/#map#zoomto) which provides an animated transition.
