### ISSUE TITLE
geocoding example

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#1736]
A basic geocoding example in https://www.mapbox.com/mapbox-gl-js/examples/ would go a long way.

**Comment by tmcw** [comment]
Should we write this before or after finishing & publishing the geocoder plugin?

**Comment by samanpwbb** [comment]
Probably after.

**Comment by tristen** [comment]
https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/
