### ISSUE TITLE
fill-outline-color on borders of clipped tiles 

### ISSUE THREAD

**Issue by leblowl** [mapbox/mapbox-gl-js#1738]
Hey all! So whenever I clip my geometries to the borders of their respective tiles, fill-outline-color draws all the borders. It makes sense in one way, but realistically I'd love it to recognize matching polygons in adjacent tiles. I'm not totally sure how it is supposed to work, so I'm asking ya'll. Is this intended behavior or am I doing something wrong?

I split my tiles with ST_Intersection, using the ne_10m_ocean dataset from natural earth:
```
       SELECT
           'Ocean' AS name,
           sum(way_area)::bigint AS area,
           'ocean' AS kind,
           'naturalearthdata.com' AS source,
           ST_Union(ST_Intersection(the_geom, !bbox!)) AS __geometry__,
           max(gid) AS __id__
       FROM
           ne_10m_ocean
       WHERE
           ST_Intersects(the_geom, !bbox!)
```

And the result at zoom level 4 with fill-outline-color set to #000:
![fill-outline-color](https://cloud.githubusercontent.com/assets/4041864/11287533/3ba01a22-8ed1-11e5-9dc3-5acaae4a0140.png)

Thank you

**Comment by jfirebaugh** [comment]
You should add a buffer to the vector tiles, and clip the polygons to these buffered dimensions rather than to the exact tile extent.

We're adding the following language to [the next version of the vector tile specification](https://github.com/mapbox/vector-tile-spec/pull/39) to clarify this:

> A layer MUST contain an extent that describes the width and height of the tile in integer coordinates. The geometries within the Vector Tile MAY extend past the bounds of the tile's area as defined by the extent. Geometries that extend past the tile's area as defined by extent are often used as a buffer for rendering features that overlap multiple adjacent tiles.
