### ISSUE TITLE
Complex filters and layers

### ISSUE THREAD

**Issue by derrickpelletier** [mapbox/mapbox-gl-js#1741]
I might be trying to shoehorn some functionality into something that probably wasn't necessarily designed to do this, but I made it work. However, I really want there to be a better way but I'm not seeing a better solution using the styles/filters available.

Essentially, I'm generating vector tiles on the fly based on some data analysis, and I color the polys based on a single value.

The analysis is interval based, say week or month, with a potentially different value each interval, so I'm doing a iterating over a timeline, and transitioning through the style layers with a class per interval ('i1', 'i2', etc)

So a poly might look like this before it is processed into the vector:

```
{
  type: 'Feature',
  geometry: {...},
  properties: {
    id: 'x',
    intervals: [3, 3, 3, 4, 5, 4 ...]
  }
}
```

But, because the filters don't allow for values to be of `Array` type, I'm storing those values as:
```
{
  type: 'Feature',
  geometry: {...},
  properties: {
    id: 'x',
    i0: 3,
    i1: 3,
    i2: 3,
    i3: 4,
    i4: 5,
    i5: 4
  }
}
```

and then my style layers on the frontend, I build dynamically, with a layer per segment (color) per interval.

```
var layers = [];
for(var x = 0; x < intervals; x++) {
  for(var y = 1; y <= segments; y++) {
    var l = {
      id: 'i' + x + 's' + y,
      source: 'dp',
      'source-layer': 'shapes',
      type: 'fill',
      filter: ['all',
        ['==', 'i' + x, y]
      ],
      'paint': {
        'fill-opacity': 0
      },
      'paint.hide-all': {
        'fill-opacity': 0
      }
    };

    l['paint.i' + x] = {
      'fill-color': colorScale(y).hex(),
      'fill-opacity': 1
    };

    layers.push(l);
  };
};
```

So, excuse any obviously glaring errors because this is just prototyping. So it's building it all dynamically, which isn't that burdensome for me, obviously, but my concern is more if I end up doing a two year time span on weekly intervals, we're looking at 104 intervals, with 10 segments per. Which is 1040 layers. And 104 properties per poly. Which just seems excessive.

Is there another tricky way I could organize this to reduce some of the bloat, I'm hoping I just missed something obvious while focusing on the actual tile generation aspects. Hopefully someone has an idea.

------

Note: i was originally just generating rasters for the given bounds and iterating through them, but other parts of the app utilize custom vector tiles as well, and rasters don't play nice with layering with canvas, obviously (place names, roads, etc).

**Comment by lucaswoj** [comment]
Hi @derrickpelletier! 

Unfortunately, I can't think of a better way to implement the functionality you've outlined right now. We're working hard on a new feature called data-driven styling #1626 that will make this kind of data visualization much easier.

**Comment by jfirebaugh** [comment]
Also related: #1180.

**Comment by derrickpelletier** [comment]
Dang! 

Thanks for pointing me to #1626 @lucaswoj. Just curious, is that feature far enough along for me to bother starting implementing that way, or would you recommend sticking with the path I'm on (I am not in production).

**Comment by lucaswoj** [comment]
Depends -- What is your timeline @derrickpelletier? The feature is quite far along but there are some potentially big technical blockers (namely #1336 #1714)

**Comment by derrickpelletier** [comment]
@lucaswoj, several months at least.

**Comment by lucaswoj** [comment]
@derrickpelletier I'd guess "several months" is a similar timeline for us to land #1626, at least in a stable feature branch.

If performance is acceptable the way you're doing things now, I'd stick with that for now and migrate over to data-driven styling once that lands.

**Comment by derrickpelletier** [comment]
Great, thanks for the feedback. That's what I'll do :ok_hand:

**Comment by derrickpelletier** [comment]
@lucaswoj is there a good example style anywhere for using data-driven styles that you can point me to? Looking through the related issues isn't particularly clear from an outsiders perspective here.
