### ISSUE TITLE
Add hooks into the render pipeline

### ISSUE THREAD

**Issue by vicapow** [mapbox/mapbox-gl-js#1742]
Would love to be able to add our own custom webGL overlays between existing layers. something like this maybe?

````js
map.renderHookAfterLayer('before-this-layer', function renderCallback(gl) {
  // gl calls.
});
````

Specifically, this would allow us to add custom overlays like heatmaps, etc. with labels on top and geo below.

**Comment by vicapow** [comment]
very similar to: https://github.com/mapbox/mapbox-gl-js/issues/281 maybe a duplicate?

**Comment by enjalot** [comment]
+1
don' think this is a duplicate, overlay would be different from something like being able to run a desaturation filter on a raster layer which needs #281 I believe.

**Comment by lucaswoj** [comment]
**IF** we consider this feature, it'll be after we have a bulletproof solution for https://github.com/mapbox/mapbox-gl-js/issues/145.

**Comment by lucaswoj** [comment]
I'm going to call this a duplicate of #281 and re-ope that issue.
