### ISSUE TITLE
Can not get featuresIn to work...

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1746]
My featuresAt for my 'markers' geojson layer (addSource) is working great. Now I try to get featuresIn working, but I tried all kinds of things but it just returns: [ ]

What is wrong with this? (layer is set: "interactive": true):
```
    map.featuresIn(map.getBounds().toArray(), {layer: 'markers', includeGeometry: true},
            function (err, features) {
                if (err) throw err;
                console.log(features);
            });
```
Here is a fiddle showing this issue:
https://jsfiddle.net/musicformellons/rmhax8L6/

featuresAt works: it activates the pointer when hovering over a marker; but featuresAt does not give any features of the marker.

**Comment by jfirebaugh** [comment]
[`featuresIn`](https://www.mapbox.com/mapbox-gl-js/api/#Map.featuresIn) takes bounds in pixel coordinates, but you're passing it geographic coordinates.

If you want to get all features currently visible, you can omit the first parameter entirely.

**Comment by musicformellons** [comment]
Yeah, I had seen that and already tried passing in pixel coordinates and also omitting, but they give no features either... I adjusted the fiddle accordingly. Could you tell me why no features are shown please?
https://jsfiddle.net/musicformellons/rmhax8L6/

**Comment by musicformellons** [comment]
Got it, thanks!
