### ISSUE TITLE
featuresIn layer filter not working

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1747]
I want the featuresIn for just one layer, but it does not work so far..., a fiddle:
https://jsfiddle.net/musicformellons/Lqdq31Lf/
```
map.on('load', function() {
	map.featuresIn( {layer: 'markersgreen'},
            function(err, features) {
                if (err) throw err;
                alert(JSON.stringify(features));
            });
        });
```
Although only markersgreen are requested, featuresIn returns both markersgreen and markersblue. BTW it works for the featuresAt in the fiddle as hovering just activates for the markersgreen.

An additional thing that puzzles me: As it seems no filter on layers is applied in my fiddle, I would expect to also get returned the features of the Mapbox Street-v8 map layers, so why do I not get these as well?

**Comment by jfirebaugh** [comment]
This is a bug in `featuresIn`. The implementation needs to follow the change in fb54d903266737ace49c901299af05db7d5d45b0 (actually it should be refactored so most code is shared with features `featuresAt`).

> I would expect to also get returned the features of the Mapbox Street-v8 map layers, so why do I not get these as well?

`streets-v8` layers do not have `"interactive": true`.

**Comment by jfirebaugh** [comment]
cc @anandthakker

**Comment by anandthakker** [comment]
Agreed re: refactor to common code path.  I can *hopefully* take a look at doing that sometime this weekend

**Comment by musicformellons** [comment]
Yeah, works now with version 0.11.5 ! Great!
