### ISSUE TITLE
Scroll example never moves to the last place 

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1749]
![bug](https://cloud.githubusercontent.com/assets/32314/11341145/1eba84fa-91cf-11e5-9215-bad572a34b58.gif)

The final frame is never fully exposed, so the map never moves.

**Comment by bsudekum** [comment]
@tmcw that gif looks outdated. @lucaswoj made a couple of updates last week, I'm seeing that this works now:

![2](https://cloud.githubusercontent.com/assets/1058624/11343616/a98078aa-91c1-11e5-95a8-6b0afc33ac7c.gif)
