### ISSUE TITLE
Make `loaded` a listenable event

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1758]
We can query `map.loaded()` at any time to see if all map resources have been loaded. But rather than querying repeatedly for this value to turn `true`, I would like to execute a function based on this event. This would work identically to `map.on('load')`, except not limited to the initial instantiation of the map.

@andreasviglakis and I were working on a project where we `.flyTo` a certain location and performed a `.featuresAt` there. Often, the `featuresAt` would fire before the map tiles loaded, yielding an empty result. An `.on('loaded')` handler would help greatly.

**Comment by lucaswoj** [comment]
I think this is a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/1715. Can you confirm @peterqliu?

**Comment by peterqliu** [comment]
confirmed. thanks @lucaswoj
