### ISSUE TITLE
Image url in markers

### ISSUE THREAD

**Issue by pixnlove** [mapbox/mapbox-gl-js#1760]
I have some images hosted on AWS that I would like to display them on the map like markers (a popup is assigned on each).

![issuemapbox](https://cloud.githubusercontent.com/assets/2814767/11385741/fef7dac0-931b-11e5-9ea7-a9e0720f166d.png)

They are loaded dynamically from my server, what is the best approach to integrate these images like the example?

Thanks for your help ;)

**Comment by jfirebaugh** [comment]
It's not yet possible to load marker images from an external source; they must be included in the style sprite. See #358 for the feature request.

**Comment by abuchanan** [comment]
Isn't this possible via [Image](https://www.mapbox.com/mapbox-gl-style-spec/#image) sources?

e.g. https://www.mapbox.com/mapbox-gl-js/example/image-on-a-map/

**Comment by pixnlove** [comment]
Images sources don't behave as markers: when you're scrolling on the map they don't keep their size. The only solution that I found for the moment is to add a popup element for each image marker but it's not very clean. 
It will be awesome to have the ability to add an extra HTML param on a feature :heart_eyes:

**Comment by pixnlove** [comment]
Maybe a solution to implement in the Mapbox GL library : https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Drawing_DOM_objects_into_a_canvas ?
