### ISSUE TITLE
Composite sources with custom data

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#1764]
Hey,

Short version:

Are composite sources supported for custom non-mapbox hosted data?

Long version:

Looking at a few of the Mapbox styles, composite sources (one source layer from multiple data sets) seems to be supported in the client, such as here: https://github.com/mapbox/mapbox-gl-styles/blob/master/styles/outdoors-v7.json and https://github.com/mapbox/mapbox-gl-styles/blob/master/styles/streets-v8.json

```json

"sources": {
    "mapbox": {
      "type": "vector",
      "url": "mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6"
    }
  },

```

with custom sources, this would seem to be the way to go as referenced at https://www.mapbox.com/mapbox-gl-style-spec/:

```json

mapbox-streets": {
  "type": "vector",
  "tiles": [
    "http://a.example.com/tiles/{z}/{x}/{y}.pbf",
    "http://b.example.com/tiles/{z}/{x}/{y}.pbf"
  ],
  "maxzoom": 14
}

```

However the tileJSON spec specifies that each endpoint must return the same data (https://github.com/mapbox/tilejson-spec/tree/master/2.1.0), indicating that it is not possible to merge multiple custom sources into one source layer.

Attempting to use different source data for each tileURL results in the client loading an arbitrary amount of non-overlapping tiles from each source as we'd expect after reading the tileJSON spec. Alas, there doesn't seem to be a way to create composite sources with non-mapbox hosted data. Is it just us misunderstanding the spec or is there any way around it?

**Comment by kkaefer** [comment]
Explanation in https://github.com/mapbox/mapbox-gl-native/issues/3141#issuecomment-160581589
