### ISSUE TITLE
Method chaining gets certain map movements ignored

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1768]
Demo: http://jsfiddle.net/mwseqkvy/

The demo seeks to `.flyTo()` a new center while setting a new pitch on the map. This works well if the instantaneous `setPitch()` method is chained before the animated `.flyTo()`, but instantaneous methods can cancel out the animation of chained after it.

**Comment by peterqliu** [comment]
Edit: Turns out that *any* map manipulation will cancel transition methods (easeTo and flyTo) when chained after them.

**Comment by jfirebaugh** [comment]
Yes, this is intended behavior. If you want make a single animation, you need to use a single `flyTo` or `easeTo` call with all desired properties.
