### ISSUE TITLE
map never fires a "load" event when raster layer is on custom style

### ISSUE THREAD

**Issue by OmniEarthDev** [mapbox/mapbox-gl-js#1770]
When I have a custom style with a public raster layer added on the map never fires a "load" event.

raster layer:

{   "id" : "dev_SanFrancisco_Sat",
    "layout" : { "visibility":  "visible"},
    "maxzoom" : 15,
    "minzoom" : 7,
    "paint": { "raster-opacity": 1},
    "source": "dev_SanFrancisco_Sat",
    "source-layer": "dev_SanFrancisco_Sat",
    "type": "raster"
}

See http://jsfiddle.net/rraponi/44aj1ta5/ for an example.

Just remove the raster layer from the custom style layers and an alert that states that the map has loaded will appear.

I need the "load" event since other actions happen once it is fired!

**Comment by lucaswoj** [comment]
@OmniEarthDev fixed in #1772. We'll roll this into a release `v0.11.5` soon.

**Comment by OmniEarthDev** [comment]
thanks!
