### ISSUE TITLE
Improve tests for and refactor camera.js

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1773]
There seems to be a lot of duplicated code in `js/ui/camera.js`. Simplifying the module would help prevent bugs like #1744 #1429 and make the module easier to test.

For example, `rotateTo` could just be a call to `easeTo`. More ambitiously, `easeTo` could probably be a parameterized call to `flyTo`.

ref #1771

**Comment by mourner** [comment]
I think this refactoring was covered recently by @ansis, don't remember the exact PR.
