### ISSUE TITLE
Support bounds in TileJSON

### ISSUE THREAD

**Issue by steinbachr** [mapbox/mapbox-gl-js#1775]
the combination of documentation <a href="https://www.mapbox.com/mapbox-gl-style-spec/#sources">here</a> which states, _"Tiled sources (vector and raster) must specify their details in terms of the TileJSON specification"_ and the TileJSON documentation <a href="https://github.com/mapbox/tilejson-spec/blob/master/2.1.0/README.md">here</a> leads me think it's possible to add a raster source that only adds tiles within certain bounds. However, when I try to do so, the entire map is tiled, rather than just the portion of map contained within `bounds`. For instance, this code tiles the entire map without respect to `bounds` whereas I would expect it to tile only within the bounds given (`[-10, -10, 10, 10]`):

```
"raster-layer": {
      "type": "raster",
      "tiles": [
           "https://some-tile-source/{z}/{x}_{y}.jpg"
       ],
      "bounds": [-10, -10, 10, 10],
      "tileSize": 256,
      "minzoom": 0,
      "maxzoom": 5
}
```

**Comment by jfirebaugh** [comment]
You're right, TileJSON `bounds` is something that should be supported, but isn't currently.

**Comment by steinbachr** [comment]
ah okay, thanks for the clarification @jfirebaugh

**Comment by lucaswoj** [comment]
ref #1404

**Comment by Scarysize** [comment]
We are using something like this to avoid requests to tiles which are located outside of a given bounding box:

https://gist.github.com/Scarysize/abcf22c514d64125111a5b130cf66fb3
