### ISSUE TITLE
Run a javascript linter on the examples

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1781]
It is important to have examples that are idiomatic and correct. We should find a linter capable of giving the ~~html,~~ javascript ~~and css~~ a once-over before we publish. Right now this is all done by hand and, as an imperfect human, I make mistakes :grin:

**Comment by tmcw** [comment]
Let's scope to JavaScript, otherwise this task will not be fixable. https://www.npmjs.com/package/eslint-plugin-html is the first step. It doesn't support YAML headers, so we need to write a PR adding that support.

**Comment by lucaswoj** [comment]
>  It doesn't support YAML headers, so we need to write a PR adding that support.
We could lint the generated files (i.e. in `_site/example`)

**Comment by tmcw** [comment]
I don't think we should do that - line numbers for lint errors are important. I wrote support and PR'ed https://github.com/BenoitZugmeyer/eslint-plugin-html/pull/19
