### ISSUE TITLE
featuresIn doesn't return features from non-visible layers

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-gl-js#1785]
Related to https://github.com/mapbox/mapbox-gl-js/issues/582

Here's a working demo which filters out Landsat scenes based on a selected region: https://gist.github.com/drewbo/9700ea2eb3ca9e9b83fb

It fails (stops returning features in the `featuresIn` callback) if [fill-opacity](https://gist.github.com/drewbo/9700ea2eb3ca9e9b83fb#file-gl-opacity-html-L65) is set to 0 or if `layout.visibility === none`

**Comment by timjcook** [comment]
+1. My use case is that I am revealing a layer that was previously hidden and want it's features in the viewport at that moment, however if I call `featuresIn()` immediately after revealing the layer and there is a delay in the map rendering the features, I get no features back.

**Comment by CodeCommander** [comment]
I want to use this to "flyTo" the coordinates of a feature that is filtered to be hidden. Is there no way to get a reference to a hidden feature?

**Comment by lucaswoj** [comment]
@CodeCommander Not yet but it'll be added in https://github.com/mapbox/mapbox-gl-js/pull/2052

**Comment by jfirebaugh** [comment]
Non-visible features are now queryable via [`querySourceFeatures`](https://www.mapbox.com/mapbox-gl-js/api/#Map#querySourceFeatures).
