### ISSUE TITLE
multiple events for same function

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1788]
In jQuery you can do:
```
map.on('load moveend', dosomething);
```
This does not work in Mapbox gl js.

This seems to work:
```
map.on('load', dosomething);
map.on('moveend', dosomething);
```
Maybe support jQuery style?

**Comment by tmcw** [comment]
I'd prefer not to support the jQuery style; this is a very minor bit of syntax sugar, and I'd bet it isn't an expectation for anyone but diehard jQuery fans.

**Comment by musicformellons** [comment]
@tmcw Ok, so 
```
map.on('load', dosomething);
map.on('moveend', dosomething);
```
is how to do it then?

**Comment by mourner** [comment]
Yes, or with chaining: 

```js
map
  .on('load', doStuff)
  .on('moveend', doStuff);
```

I'm also not in favor of supporting string sugar in events. We added it in Leaflet and it wasn't worth it.

**Comment by tmcw** [comment]
Agreed: no sugar here, chaining is the way to go for brevity.

**Comment by musicformellons** [comment]
Ok, thanks!
