### ISSUE TITLE
Map#remove doesn't remove DOM elements

### ISSUE THREAD

**Issue by rymohr** [mapbox/mapbox-gl-js#1789]
Is there another method I should be calling instead?

https://github.com/mapbox/mapbox-gl-js/blob/8ad09ffc5eec68b355f35f0fa0a990f53977035c/js/ui/map.js#L789

**Comment by jfirebaugh** [comment]
Correct it does not remove DOM elements. Can you say more about why you were expecting it to do so?

**Comment by jfirebaugh** [comment]
Oh, I think I see what you are getting at: it doesn't remove the canvas element or control containers that it added to the DOM. It should do that. Is that what you meant?

**Comment by rymohr** [comment]
Yeah, that's it.
