### ISSUE TITLE
featuresIn returns duplicates of marker points

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1790]
@anandthakker @jfirebaugh I have a geojson sourced layer with 5 (a, b, c, d, e) marker points which are shown nicely. Using featuresIn (with filter on the marker layer) the features of 5 points are returned when in the viewport. For several zoom layers this works as expected. There are zooms in which duplicates are returned however:
Zoom 13: 6 points: 1a, 1b, 1c, 2d, 1e.
Zoom 12; 7 points: 1a, 1b, 2c, 2d, 1e.
Zoom 11; 10 points: 1a, 2b, 4c, 2d, 1e. 
Zoom 10; 10 points, 2a, 2b, 2c, 2d, 2e. 
Zoom 4; 7 points: 1a, 1b, 1c, 2d, 2e.
Zoom 3; 10 points, 2a, 2b, 2c, 2d, 2e.

Other zoom levels seem ok.

I would think the tile-problem described here https://github.com/mapbox/mapbox-gl-js/pull/1302 does not apply to points. Any idea why I get duplicates? 

A fiddle to make things more clear (starts at zoom 12 and indeed gives 7 instead of 5 points):
https://jsfiddle.net/musicformellons/z1bgcwqx/

**Comment by anandthakker** [comment]
The fiddle doesn't seem to be working.

@musicformellons Can you try to see if the same thing happens using `featuresAt` with a very large radius?

**Comment by musicformellons** [comment]
Mmmh, edited fiddle address, should work now.

**Comment by musicformellons** [comment]
@anandthakker I am not sure how you want to test with featuresAt..., but now that you have the fiddle, maybe you can have a look?

**Comment by jfirebaugh** [comment]
This is the currently expected behavior from `featuresIn`. As the [documentation states](https://www.mapbox.com/mapbox-gl-js/api/#featuresCallback):

> Note: because features come from vector tiles or GeoJSON data that is converted to vector tiles internally, the returned features will be:
> 1. Truncated at tile boundaries.
> 2. Duplicated across tile boundaries.

This applies equally to point features -- points near tile boundaries may exist in multiple tiles because of tile buffering behavior that is necessary to obtain correct label placement across tile boundaries.

**Comment by musicformellons** [comment]
Yes, I read that, but it seemed to me that points would be less likely to hit tile boundaries, but apparently not so due to the buffering you mention. I will put a filter on it. Thanks for clearing this up.

**Comment by musicformellons** [comment]
Actually the result at zoom 11 seems quite spectacular to me: apparently one point hits 4 tiles...!
