### ISSUE TITLE
Add google maps base layer

### ISSUE THREAD

**Issue by rishabhjain30** [mapbox/mapbox-gl-js#1791]
Is there any way I can put google maps as base layer while using mapbox gl js?

**Comment by tmcw** [comment]
Legally, no: [Section 10.1a of Google's Terms of Service](https://developers.google.com/maps/terms?hl=en#10-license-restrictions).

> No access to APIs or Content except through the Service. You will not access the Maps API(s) or the Content except through the Service. For example, you must not access map tiles or imagery through interfaces or channels (including undocumented Google interfaces) other than the Maps API(s).

**Comment by rishabhjain30** [comment]
@tmcw Technically, can I use static maps api url to add it as a raster layer?

**Comment by tmcw** [comment]
Technically, sure. But it's illegal.

**Comment by rishabhjain30** [comment]
@tmcw I am just experimenting. Can you elaborate a bit on how can I do that?

**Comment by tmcw** [comment]
Nope, you'll have to do this one on your own. Locking this issue; we don't condone usage of Mapbox GL JS that breaks ours or anyone else's legally-binding Terms of Service.
