### ISSUE TITLE
No symbols shown when using GeoJSON with Mapbox newer then 0.11.1

### ISSUE THREAD

**Issue by buma** [mapbox/mapbox-gl-js#1792]
If I use GeoJSON with custom symbols or symbols from mapbox symbol set none of them are shown if I use Mapbox gl/js newer then 0.11.1.

On [jsbin](https://jsbin.com/namededeki/1/edit?html,output) I put minimal sample. It has much smaller geojson which shows that oneway icons are shown at least on two edges but they should be on all. But if I update mapbox version to 0.11.2 for js and css they aren't shown on any edge.

It is probably similar issue to #1563 but the text labels are rendered even on newer mapbox versions not on all edges but at least on same number as in version 0.11.1.
Rendering of symbols from mapbox works even on newer versions if I use mapbox tiles instead of GeoJSON. I don't know about custom symbols I tested Mapbox street layer.

**Comment by lucaswoj** [comment]
I can confirm this is a bug introduced in v0.11.2. It could be related to any of (or none of)

 - Fix sprites on systems with non-integer devicePixelRatios (#1029 #1475 #1476)
 - Fix symbol placement at the start of a line (#1461)
 - Fix raster-opacity on non-tile sources (#1270)
 - Upgrade geojson-vt from [v2.1.6 to v2.1.7](https://github.com/mapbox/geojson-vt/compare/v2.1.6...v2.1.7)

**Comment by mourner** [comment]
Let's do git bisect.

четверг, 3 декабря 2015 г. пользователь Lucas Wojciechowski написал:

> I can confirm this is a bug introduced in v0.11.2. It could be related to
> any of (or none of)
>
>    - Fix sprites on systems with non-integer devicePixelRatios (#1029
>    <https://github.com/mapbox/mapbox-gl-js/issues/1029> #1475
>    <https://github.com/mapbox/mapbox-gl-js/issues/1475> #1476
>    <https://github.com/mapbox/mapbox-gl-js/issues/1476>)
>    - Fix symbol placement at the start of a line (#1461
>    <https://github.com/mapbox/mapbox-gl-js/issues/1461>)
>    - Fix raster-opacity on non-tile sources (#1270
>    <https://github.com/mapbox/mapbox-gl-js/issues/1270>)
>    - Upgrade geojson-vt from v2.1.6 to v2.1.7
>    <https://github.com/mapbox/geojson-vt/compare/v2.1.6...v2.1.7>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapbox/mapbox-gl-js/issues/1792#issuecomment-161754012>
> .
>


-- 
Vladimir Agafonkin
http://agafonkin.com/en
+380 (93) 745 44 61

**Comment by lucaswoj** [comment]
Bisects to 3532d809a1e0208e80e2db8cefff49cb4e5202d6, which specifically mentions 1-way arrows.

    fix layer minZoom being ignored if not less than source maxZoom
    
    This condition led to layers with high minzoom like oneway street
    arrows (z15) get parsed and placed regardless of minzoom (e.g. z11+),
    wasting a lot of worker CPU time.
    
    It became unnecessary after we added reparsing tiles when overscaling,
    and even before that it should have probably been <= rather than <.
    Native has the same bug.

In this case, the arrows are set to show between zoom levels 15 and 22 but are not being displayed at zoom 18.

**Comment by lucaswoj** [comment]
Because the [default maxzoom for GeoJSON sources is 14](https://github.com/mapbox/mapbox-gl-js/blob/3532d80/js/source/geojson_source.js#L64), these one way arrows are not being rendered at zoom levels 15 to 22. 

@mourner Do you think there's an actionable fix there? Should we increase the default zoom of GeoJSON sources? Add some additional logic?

@buma You can fix the problem by adding `"maxzoom": 22` to your GeoJSON source definition. (And maybe you'd prefer setting `"icon-ignore-placement": true` in the layer style definition.)

**Comment by lucaswoj** [comment]
@buma Here's [a modified jsbin with the suggested fixes in place](https://jsbin.com/nocugadizi/2/edit?html,output). Happy mapping! :globe_with_meridians:

**Comment by mourner** [comment]
@lucaswoj ah, yeah, I think we should bump it to at least 16 which is what Mapbox Streets v7 uses, but can go deeper (say 18) — it won't affect performance noticeably.

**Comment by lucaswoj** [comment]
@mourner Does the source's `maxzoom` affect geojson-vt's tile generation? If so, it seems wrong to disable ability to render sprites on overzoomed geojson-vt tiles.

**Comment by buma** [comment]
That was fast! Thanks to all of you it works great now! But it seems there should be a FAQ or documentation about GeoJSON default maxzoom or it should be changed.
