### ISSUE TITLE
flyTo callback

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#1794]
Would be nice to have a callback function when a [flyTo](https://www.mapbox.com/mapbox-gl-js/api/#Map.flyTo) animation is complete.

**Comment by jfirebaugh** [comment]
Can you listen for the `moveend` event?

**Comment by tristen** [comment]
Yes but it would be nice/clearer to do it within flyTo

**Comment by mourner** [comment]
I think it's better to rely on `map.once(`moveend`, fn)` here. To add a reliable callback to `flyTo` directly, we need to add some ugly hacks, otherwise e.g. it won't be fired when stopped externally before it finishes.

**Comment by tristen** [comment]
:+1: this is a good solution. Closing.

**Comment by ansarikhurshid786** [comment]
https://gis.stackexchange.com/questions/173862/how-to-determine-when-mapbox-gl-js-flyto-has-arrived

**Comment by MoradiDavijani** [comment]
I use this solution:

```javascript
map.on('moveend', ({ originalEvent }) => {
  if (originalEvent) {
    map.fire('usermoveend');
  } else {
    map.fire('flyend');
  }
});
```

You can do the same for `movestart`.
