### ISSUE TITLE
Is map.update() supposed to respond to changes in GeoJSON source data?

### ISSUE THREAD

**Issue by abuchanan** [mapbox/mapbox-gl-js#1797]
http://jsfiddle.net/try031nq/1/

I update a GeoJSON object after 5 seconds and call `map.update(true)`. From reading the API, I would have expected this to respond to the change in data. Also tried `map.render()` but neither renders the changed data.

The only way this works is by calling `source.setData(data)`.

If I had to blindly guess, I'd say the data is being copied somewhere, maybe to the web worker, so mutating the original object doesn't work.

Is this expected behavior? From my point of view as a user reading the API docs, it is not expected.

In the end, what I'm looking for is a way to batch update sources.

**Comment by mourner** [comment]
Yes, the data needs to be processed by the workers before it can be rendered, so you're expected to call `source.setData` to update. Perhaps we should make this clearer in the docs.

**Comment by abuchanan** [comment]
Makes sense. Ya, maybe the docs need an update, particularly `map.update()`:
"Update this map's style and sources, and re-render the map."

What does it mean by "Update the sources"?

Also, is there a way to batch update sources? If I do:
```
source1.setData(data1);
source2.setData(data2);
```

Does this result in two renders?

**Comment by jfirebaugh** [comment]
`map.update()` is for internal use only and should not be publicly documented. There's no situation in which you need to call it yourself. Sorry for the confusion about that.

Yes, your second example would cause multiple renders. In fact, even a _single_ `source.setData(data)` may cause multiple renders, because GeoJSON data is converted to a tiled representation internally, and each individual tile is rendered as soon as it is ready. However, when changing the data, the old tile will remain in use until the new tile is ready, so you should not see a flicker.

**Comment by abuchanan** [comment]
Great. Thanks for the quick answers guys.

**Comment by BrunoSalerno** [comment]
It would be very useful to have the possibility of batching source updates. Now, when I have to call several `setData` of different sources at the same time it gets slow. I would like to be able to put the `setData` inside the `map.batch(function(batch){ ...`. Or perhaps, an option to avoid the map rerender when the `setData` method is triggered and a public method to update the map once all the setData have been performed.

**Comment by iryanjan18** [comment]
the setData does not work in my case. I have the following code when building the map
```
// this is inside the map.on('load'.....
this.map.addSource('contacts', {
    type: 'geojson',
        data: {
            type: 'FeatureCollection',
            features: this.ContactMapData.slice()
        }
});

this.map.addLayer({
        id: 'contact-population',
        type: 'circle',
        source: 'contacts',
        paint: {
          'circle-radius': {
            base: 1.75,
            stops: [
              [10, 2],
              [15, 2]
            ]
          },
          'circle-color': [
            'match',
            ['get', 'status'],
            'IDENTIFIED',
            '#66CBDF',
            'TRACED',
            '#45BF55',
            '#ccc'
          ]
        }
      });
```
Then I have a dropdown that filters the data property that is calling this function. The circles only disappear and not updating the data.
```
private updateData(province: string) {
    const geojson = {
      type: 'FeatureCollection',
      features: []
    };
    const value = this.ContactMapData.filter((data: any) => data.properties.address.province === province);
    geojson.features.push(value);
    this.map.getSource('contacts').setData(geojson);
  }
```

**Comment by chiragbytes** [comment]
Hello @iryanjan18, i am facing similar issue when trying to re-render by setData(geojson) but map is not updating.
Have you find any solution?

**Comment by GiuseppeHD** [comment]
Hello @chiragbytes @iryanjan18 , I've the same issue. 

Did you find any solution about this problem?

**Comment by iryanjan18** [comment]
> Hello @iryanjan18, i am facing similar issue when trying to re-render by setData(geojson) but map is not updating.
> Have you find any solution?

I did not use the `map.update()` in the end. You have to set which the layer the new/updated data will be reflected something like this.
```javascript
geojson.features = value.slice(0);
this.map.getSource(source).setData(geojson);
this.map.setFilter(layer);
```
