### ISSUE TITLE
Document interaction handlers and make an example using them

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1801]
ref https://github.com/mapbox/mapbox-gl-js/pull/1777#issuecomment-162087928

**Comment by lucaswoj** [comment]
We don't need a dedicated example for disabling touch rotation. I added this API to the other "Disable map rotation" example.

**Comment by jfirebaugh** [comment]
Dup of #1497?

**Comment by lucaswoj** [comment]
Yup. Sorry. Missed that.

**Comment by anjaliD-syn** [comment]
Hey @lucaswoj  @jfirebaugh can we prevent rotation but still allow zooming in map?
I tried setting up touchZoomRotate as false but it prevents both rotation and zooming in map using touch gesture. I want to disable the rotation only.
