### ISSUE TITLE
Duplicate attribution

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-gl-js#1804]
We're having this issue on the [Chennai flood map](http://osm-in.github.io/flood-map/chennai.html#16.86/12.99241/80.25987) after adding the `mapbox.satellite` layer.

<img width="665" alt="screenshot 2015-12-05 08 45 39" src="https://cloud.githubusercontent.com/assets/126868/11605735/144a0132-9b2d-11e5-80a1-c6f38af1f5d6.png">

**Comment by mourner** [comment]
I'm not sure we can fix this automatically — it grabs attribution strings from corresponding TileJSON of both sources, and it's not a 1:1 match. Perhaps we could detect whether one attribution is a substring of another one and then use the bigger one.

**Comment by lucaswoj** [comment]
We're due for an overhaul of our attribution system #1485. Perhaps we could support a per-source attribution syntax like

```
attribution: ["© Mapbox", "© OpenStreetMap", "© Digital Globe"]
```
 
So that we can better merge and dedupe strings

**Comment by mourner** [comment]
@lucaswoj but that would require changing the TileJSON spec and propagating that change through our whole stack, right? Substring matching may be good enough of a hack for now.

**Comment by lucaswoj** [comment]
Right. Substring matching sounds like a better short-term solution.

**Comment by jfirebaugh** [comment]
See also #1752.

**Comment by lucaswoj** [comment]
This was partially addressed by https://github.com/mapbox/mapbox-gl-js/commit/d7dacd63937b0429df46b8279a75090727501efd and I have not heard any reqests for refinements since. 

Related to #1485

**Comment by 1ec5** [comment]
A more structured attribution syntax like the one described in https://github.com/mapbox/mapbox-gl-js/issues/1804#issuecomment-162717387 is being tracked in mapbox/tilejson-spec/issues/20.

**Comment by ygoe** [comment]
I see this all the time here. Is there something I can do in my code?

**Comment by romankaravia** [comment]
Looks like this is currently happening with Light, Dark, Streets, and Outdoors styles, also on https://mapbox.com, see e.g. [Light style preview](https://www.mapbox.com/maps/light#:~:text=Mapbox%20Streets%20data):

![image](https://github.com/user-attachments/assets/cd23cd6c-9c3c-4e55-9792-1fce0938f652)

However, this seems to be a backend issue, e.g. the Light style internally depends on multiple sources, which are loaded from `https://api.mapbox.com/v4/mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2,mapbox.mapbox-bathymetry-v2.json?secure&access_token={access_token}`, which returns a style document that starts as follows:

```json
{
  "attribution": "\u003Ca href=\"https://www.mapbox.com/about/maps/\" target=\"_blank\" title=\"Mapbox\" aria-label=\"Mapbox\"\u003E&copy; Mapbox\u003C/a\u003E \u003Ca href=\"https://www.openstreetmap.org/about/\" target=\"_blank\" title=\"OpenStreetMap\" aria-label=\"OpenStreetMap\"\u003E&copy; OpenStreetMap\u003C/a\u003E \u003Ca href=\"https://www.mapbox.com/about/maps/\" target=\"_blank\" title=\"Mapbox\" aria-label=\"Mapbox\"\u003E&copy; Mapbox\u003C/a\u003E \u003Ca href=\"https://www.openstreetmap.org/about/\" target=\"_blank\" title=\"OpenStreetMap\" aria-label=\"OpenStreetMap\"\u003E&copy; OpenStreetMap\u003C/a\u003E \u003Ca class=\"mapbox-improve-map\" href=\"https://www.mapbox.com/contribute/\" target=\"_blank\" title=\"Improve this map\" aria-label=\"Improve this map\"\u003EImprove this map\u003C/a\u003E",
  "bounds": [-180, -85, 180, 85],
  "center": [0, 0, 0],
```

Highlight of the link to Mapbox being duplicated in the above attribution string:

![image](https://github.com/user-attachments/assets/da2f1141-9722-4eae-a26a-975ab1613597)

=> I'm just commenting this here to say that it looks like this is likely _not_ an issue with mapbox-gl-js, if anyone feels like it, you could try reporting this somewhere else at Mapbox (probably custom support, or your backend colleagues, in case you work at Mapbox).

**Comment by mhemmings** [comment]
We've also started seeing this a lot in the last few weeks. Assume a backend change somewhere has caused it?

**Comment by mourner** [comment]
@mhemmings yes, you might be seeing remnants of cached responses after the glitch was introduced on the API side. Whenever you see it again, please report the specific cases so that we can investigate.

**Comment by hf-farmqa** [comment]
I'm seeing this as well, but only for one of my account's access tokens. The others (like the default one) appear to be fine for the moment.

When using the 'bad' token, I can inspect the source caches and see their attributions after the map has loaded up. This is what the attribution control appears to do.

```
// Inspect _sourceCaches on map style property
map.style._sourceCaches
```
The object here produces two source ids that are mapbox related
'other:composite' and 'other:mapbox://mapbox.satellite'

I believe these names/sources are coming from the custom style that I pointed the map at. That style contains a composite set of vector-based features (such as the standard set of roads and POI's and such) and refers to the standard mapbox satellite tileset as a visual layer underpinning everything else

Interrogating those sources, I can see the attributions on both (doing it the same way that the attribution control does)
```
map.style._sourceCaches['other:composite'].getSource().attribution
'<a href="https://www.mapbox.com/about/maps/" target="_blank" title="Mapbox" aria-label="Mapbox">&copy; Mapbox</a> 
 <a href="https://www.openstreetmap.org/copyright/" target="_blank" title="OpenStreetMap" aria-label="OpenStreetMap">&copy; OpenStreetMap</a> 
 <a class="mapbox-improve-map" href="https://www.mapbox.com/contribute/" target="_blank" title="Improve this map" aria-label="Improve this map">Improve this map</a>'

map.style._sourceCaches['other:mapbox://mapbox.satellite'].getSource().attribution
'<a href="https://www.mapbox.com/about/maps/" target="_blank" title="Mapbox" aria-label="Mapbox">&copy; Mapbox</a> 
 <a href="https://www.openstreetmap.org/about/" target="_blank" title="OpenStreetMap" aria-label="OpenStreetMap">&copy; OpenStreetMap</a> 
 <a class="mapbox-improve-map" href="https://www.mapbox.com/contribute/" target="_blank" title="Improve this map" aria-label="Improve this map">Improve this map</a> 
 <a href="https://www.maxar.com/" target="_blank" title="Maxar" aria-label="Maxar">&copy; Maxar</a>'
```

The attribution control does appear to try and prevent duplicates by looking for exact substrings, but the two values above unfortunately differ.
The former contains an OpenStreetMaps href value of https://www.openstreetmap.org/copyright/ and does not contain the Maxar link.

When I switch to using the default token, the `mapbox.satellite` source switches to contain the 'copyright' version
```
'<a href="https://www.mapbox.com/about/maps/" target="_blank" title="Mapbox" aria-label="Mapbox">&copy; Mapbox</a>
 <a href="https://www.openstreetmap.org/copyright/" target="_blank" title="OpenStreetMap" aria-label="OpenStreetMap">&copy; OpenStreetMap</a>
 <a class="mapbox-improve-map" href="https://www.mapbox.com/contribute/" target="_blank" title="Improve this map" aria-label="Improve this map">Improve this map</a>
 <a href="https://www.maxar.com/" target="_blank" title="Maxar" aria-label="Maxar">&copy; Maxar</a>
```

With that change the first `composite` source attribution is then a substring of the `mapbox.satellite` one and the attribution control clips out the duplicate accordingly.

I can get around this in my application by just not using the odd token but I'm not sure if this won't suddenly appear on other tokens unexpectedly down the line.

Hopefully this is all just transient, but you asked for a report @mourner if it was seen so... here you go
