### ISSUE TITLE
Request raster tiles using center coordinates and zoom level

### ISSUE THREAD

**Issue by rishabhjain30** [mapbox/mapbox-gl-js#1805]
Is there a way to request raster tiles using center coordinates(i.e. lat/long values) and zoom level instead of tile coordinates?

**Comment by jfirebaugh** [comment]
No, there isn't. Tiles, almost by definition, are always loaded by tile coordinate. What are you trying to do?

**Comment by rishabhjain30** [comment]
Since google maps doesn't allow you to directly request their tile server, I want to interact with their javascript api to request tiles. Or can you suggest a better way of doing that?

**Comment by bhousel** [comment]
As you were already told on #1791, we are not going to help you load Google tiles as a raster source in Mapbox GL JS.  Doing so violates their TOS.
