### ISSUE TITLE
Question about featuresAt

### ISSUE THREAD

**Issue by liebrand** [mapbox/mapbox-gl-js#1806]
Hi there,

I'd like to get all features within a specific radius at a given lat/lon at a specific zoom level. As far as I can tell, the featuresAt operates on screen coordinates and the 'current zoom level'?  Is there a way to say something like this where the point and radius are expressed at real world coordinates:
map.featuresAt([-122.45, 37.935], {radius: 0.05, zoom: 13}, callback);

In such a way that it would even request the tiles at zoom 13 needed if it didn't already have them loaded?

Obviously I could just do this completely separate from the mapbox api, and just hit the vector tile source manually and then loop through the features in the layers to get what I want, but I suspect that's not as efficient, since it would be duplicating a lot of work mapbox is already doing...

I appreciate there isn't a direct API (that I can find) to do this today, but perhaps there is a way to poke the innards of the map object to achieve this? Or maybe this could be a nice extension for the featuresAt and featuresIn apis ?

**Comment by peterqliu** [comment]
>Is there a way to say something like this where the point and radius are expressed at real world coordinates

@liebrand you're looking for [`map.project()`](https://www.mapbox.com/mapbox-gl-js/api/#Map.project) to do the lnglat -> pixel conversion.

**Comment by incanus** [comment]
You might consider radius in meters, then implement the equivalent of native's [`getMetersPerPixelAtLatitude `](https://github.com/mapbox/mapbox-gl-native/blob/265e56d056d58d2a8e44c4a6aa1368ae60b3ef5c/include/mbgl/map/map.hpp#L142) to determine pixel distance, which with `scale` could be used to determine tile height/width at the current fractional zoom. The bit about pulling down needed tiles would also need to be implemented. So, short answer: this would require some work in this project even for the foundations.

**Comment by jfirebaugh** [comment]
Yep, `map.project()` is what you're looking for.

I think loading out-of-zoom tiles, or tiles that would otherwise not be loaded, for the sake of doing queries, is outside of the scope of Mapbox GL JS. You might want to ask for access to the [Mapbox Surface API](https://www.mapbox.com/developers/api/surface/) if that looks like it will fit your needs.

**Comment by liebrand** [comment]
Hi there, sorry for the late reply. Indeed the the Surface API is roughly what I need, except that I need it to be completely client side in order for it to work offline. And in my case I dont really need expensive functions like "nearest" feature. In essence, all I need is to verify wether or not a given LineString intersects *any* of the features within a given bounding box.

But it should do so for the features at zoom level XX (16 in my case), regardless of the viewport and zoom level of the map.

I guess I could try to poke my VectorTileSource myself, or perhaps extend it to achieve what i need...

**Comment by liebrand** [comment]
Ps. wrt offline, i'm planning on using a service worker to ensure the required tiles are cached, such that they can be loaded at a later (offline) time and queried

**Comment by lucaswoj** [comment]
@liebrand If your data set is small enough, downloading it as GeoJSON (instead of vector tiles) and performing your computations using [Turf.js](http://turfjs.org/) is a good way to go.

**Comment by Altiano** [comment]
@liebrand how do you accomplish offline tiles ?
