### ISSUE TITLE
Add a scale bar control

### ISSUE THREAD

**Issue by ehabebeid** [mapbox/mapbox-gl-js#1807]
I was wondering if it is possible to add a scale control like [this one] (https://www.mapbox.com/mapbox.js/example/v1.0.0/scale-control/) using Mapbox GL JS.

**Comment by gsambrotta** [comment]
i really wondering too... it shouldn't be so complicate but documentation isn't clear about it

**Comment by jfirebaugh** [comment]
No, Mapbox GL JS does not currently have such a control. We may add it in the future.

**Comment by ehabebeid** [comment]
I'm new to Mapbox and to JS in general. Is there any workaround to this or
way of inserting the scale control from mapbox.js?

**Comment by amishas157** [comment]
Approach for building Mapbox GL JS scale control

**Comment by amishas157** [comment]
Approach for building Mapbox GL JS scale control : https://gist.github.com/amishas157/3ce95fadca62d7eee9b0ef2a65a964ad

**Comment by amishas157** [comment]
I have started working on building a scale for Mapbox GL JS and the prototype is here: http://codepen.io/anon/pen/ZOOYaj

**Work done so far**
  - Made a scale with a constant length , whose values changes on panning and zooming around the map.
  - The scale value depends upon zoom level of the map and also the latitude value.

**Concern**
  - The dynamic length value of the scale control is a concern over here.

**Plans**
  - Keeping the length of the control as constant (As of now, it is kept as 4 cm). 
  - Finding the value for 1 cm length of scale and scaling it by the constant factor.
  - Rounding it to a near pretty number.
  - Setting the length of the scale for that value. This value will be very close to the constant value of the scale.

cc @geohacker @batpad @bkowshik

**Comment by amishas157** [comment]
I have build a scale with maximum length set as 100px. First it finds out for the coordinates pointed by the two end points of the scale control (At equator level) and then finds the real distance between these two points using spherical law of cosines approximation.
**Code reference**
http://codepen.io/anon/pen/gMMypY

**Comment by DannyDelott** [comment]
Any updates/movement on this issue?

**Comment by mollymerp** [comment]
I agree this is a feature we should support! 

@amishas157 thanks for your work on this! Do you want to start a PR for this feature and we can work on getting it ready to merge together? The functionality should live in [here](https://github.com/mapbox/mapbox-gl-js/tree/master/js/ui/control). Let me know if you have any questions!

**Comment by amishas157** [comment]
@DannyDelott Planning to work on it further.
@mollymerp Yep. Let's plan up getting together to work on it further. How about catching some time this week?

**Comment by lucaswoj** [comment]
Done in #2940
