### ISSUE TITLE
Labels are not present if text size is 0 at source max zoom

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#1809]
If text size is evaluated as 0 on a source max zoom (e.g. z15), labels won't appear even if the size gets non-zero on higher zooms.

For GeoJSON sources, the workaround is just bumping source `maxzoom`, and we're going to make it higher by default, but this is still a bug.

cc @lucaswoj @samanpwbb

**Comment by The82ndDoctor** [comment]
I've seen this happen.

**Comment by lucaswoj** [comment]
I'm guessing this is related to https://github.com/mapbox/mapbox-gl-js/blob/master/js/data/bucket.js#L175-L188

**Comment by ansis** [comment]
fixed by d3ffe37e580980451c89dfc1029c509d07b8c173

tested with https://gist.github.com/ansis/41e54263ca5eef929443
