### ISSUE TITLE
Error load Tile

### ISSUE THREAD

**Issue by rbonillajr** [mapbox/mapbox-gl-js#1814]
My Code is

var map = new mapboxgl.Map({
        container: 'mapgl',
        style: 'mapbox://styles/mapbox/streets-v8',
        zoom: 7,
        center: [-79.89260990593574,8.488481600020107]
    });
   
    map.on('style.load', function () {
        map.addSource('Comercios', {
            type: 'vector',
            url: 'mapbox://rbonillajr.6kph7pea'
        });
        map.addLayer({
                'id': 'COMERCIOS',
                'interactive': true,
                'type': 'circle',
                'source': 'Comercios',
                'paint': {
                    'circle-radius': 8,
                    'circle-color': 'rgba(55,148,179,1)'
                },
                'source-layer': 'COMERCIOS'
            });
    });

{message: "Tile does not exist"}
message: "Tile does not exist"

![image](https://cloud.githubusercontent.com/assets/8268226/11639322/2ab3b5de-9cfa-11e5-9c16-0e801405c5a8.png)

**Comment by jfirebaugh** [comment]
You can safely ignore this error. A future version of Mapbox GL JS will suppress it: that's issue #1800.
