### ISSUE TITLE
create plugins page

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1821]
Create https://www.mapbox.com/mapbox-gl-js/plugins/, the GL JS counterpart of https://www.mapbox.com/mapbox.js/plugins/.

To start off, we can list https://github.com/mapbox/mapbox-gl-draw and https://github.com/mapbox/mapbox-gl-directions. We can also include a call to action for plugin developers to help us grow the page.

**Comment by kelvinabrokwa** [comment]
@tristen please ping me when the page is up and I can throw add the gl-draw example

**Comment by jingsam** [comment]
I found that the [Fullscreen example](https://www.mapbox.com/mapbox.js/example/v1.0.0/leaflet-fullscreen/) is beautiful. Would you condsider to implement this feature?

**Comment by lucaswoj** [comment]
Just created a ticket for that @jingsam! https://github.com/mapbox/mapbox-gl-js/issues/1824
