### ISSUE TITLE
featuresIn no longer returns GeoJSON values with 'higher' bearings

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1822]
@anandthakker @jfirebaugh FeaturesIn works fine with no or small bearing, but when changing the bearing of the map to somewhat higher values it stops returning values. Seems that it stops somewhere around bearing values > 45 degrees. 
See:
![screenshot from 2015-12-10 08-17-40](https://cloud.githubusercontent.com/assets/10334123/11709392/8decc612-9f17-11e5-93ec-d705cc162be1.png)

And here the fiddle showing this behavior:
http://jsfiddle.net/musicformellons/q1n902vL/

**Comment by musicformellons** [comment]
Uh..., any comments on this?

**Comment by musicformellons** [comment]
@anandthakker @jfirebaugh Uh?

**Comment by lucaswoj** [comment]
@musicformellons I'm not sure how this has slipped through the cracks until now. I'll take a look this week!

**Comment by musicformellons** [comment]
@lucaswoj Yeah, I was a bit puzzled by the low interest this seemed to raise. Seems pretty relevant to me. Glad you will look into it!

**Comment by lucaswoj** [comment]
@musicformellons I was not able to reproduce the behavior you are reporting. Could you re-open this issue with a test case? Here is my attempt http://jsfiddle.net/4daxz657/

**Comment by lucaswoj** [comment]
Ah. I see. This seems to be a problem only with the bounds-less (i.e. entire viewport) version of `featuresIn`
