### ISSUE TITLE
JS error 'bucketStats' 

### ISSUE THREAD

**Issue by Adrian0350** [mapbox/mapbox-gl-js#1828]
I basically copied the example shown in https://www.mapbox.com/mapbox-gl-js/examples/.
Error: Uncaught TypeError: Cannot read property 'bucketStats' of undefined

You can see scripts and html here: http://xn--adrianzuiga-8db.com/mapbox

**Comment by lucaswoj** [comment]
After digging for a little while, I'm not sure what's happening here @Adrian0350. I'm suspicious of how mootools shows up in the error stack trace -- perhaps it is overwriting the `require` function and injecting a different event system implementation.

![screen shot 2015-12-14 at 11 06 45 am](https://cloud.githubusercontent.com/assets/281306/11790856/d9e0e20e-a252-11e5-9739-73116c2001f4.png)

Could you try to create a minimal test case with unminified code?

**Comment by Adrian0350** [comment]
It crossed my mind that maybe mootools was the reason for this to happen. As of this morning I removed mootools and it worked.

Thanks for following the issue. 
I work with mootools on a daily basis and I would like to use Mapbox and Mootools all together. I hope this issue gets resolved.

**Comment by mourner** [comment]
Looks like this is something that should be reported to Mootools — we probably can't fix this on gl-js side. Mootools is known to mess with native objects / globals. :(

**Comment by Adrian0350** [comment]
Will do @mourner.
The more compatible, the better.
