### ISSUE TITLE
Give user control over how to scale patterns by zoom

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#1831]
Sometimes the current strategy for pattern scaling works; most of the time it looks weird. 

Many textures and patterns are designed to be displayed at specific sizes and don't look good or lose legibility if scaled up or down, so an option to have 'static' patterns that don't change as the user zooms would be open up a lot more possibilities with patterns.

**Comment by KP** [comment]
I completely agree. This would be immensely helpful especially for data-drive textures. For now, I had question about current implementation, are the fill patterns actual size at zoom level integers?

Looks like relevant bit in draw_fill.js but I can quite make sense of it:

```
var factor = (tile.tileExtent / tile.tileSize) / Math.pow(2, painter.transform.tileZoom - tile.coord.z);

var matrixA = mat3.create();
mat3.scale(matrixA, matrixA, [
	1 / (imagePosA.size[0] * factor * image.fromScale),
	1 / (imagePosA.size[1] * factor * image.fromScale)
]);
```

**Comment by ansis** [comment]
@samanpwbb are you thinking about something like this?
![](https://camo.githubusercontent.com/2dc8196f8f457811a52f84cc899c4248d5537c57/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313432313635322f313231303137322f30663936623538302d323566362d313165332d386132652d3330653465383135323862352e676966)


@KP yes, fill patterns should be actual size at integer zoom levels

**Comment by samanpwbb** [comment]
@ansis maybe – curious how that strategy works for patterns that are fully filled. 

What I had in mind was simpler: no animation at all on textures. Just a static texture that does not scale at all.

Some other questionably good ideas:

- In order to maximize the amount of time a texture is shown at actual size while also giving some illusion of movement, would it be possible to show static textures but then trigger a one-time animation in or out whenever user hits an integer zoom level?
- Continue to scale textures, but _only_ underscale them. Never overscale them.

**Comment by kelvinabrokwa** [comment]
@samanpwbb like this?
![image](https://cloud.githubusercontent.com/assets/7795202/12100712/87646c82-b2e5-11e5-8f6f-ad220b947f4e.gif)

**Comment by kelvinabrokwa** [comment]
As you can see above, keeping the image the same size throughout causes some funky behavior because the size of the image does not evenly divide the size of the tiles. This results in some wild sliding.

I don't think its worth fixing this before layer-by-layer rendering lands. Thoughts?

**Comment by samanpwbb** [comment]
> I don't think its worth fixing this before layer-by-layer rendering lands. Thoughts?

It's too sloppy. If we can't have patterns that are seamless across tiles then we shouldn't bother.

**Comment by lucaswoj** [comment]
I think layer-by-layer will land in the next couple days!

**Comment by ansis** [comment]
https://github.com/mapbox/mapbox-gl-js/pull/1908 will fix the seamlessness but I think that not scaling textures will still look weird. Without scaling, the patterned area doesn't look like it's part of the map surface.

two possible approaches:
- something like [this](https://camo.githubusercontent.com/2dc8196f8f457811a52f84cc899c4248d5537c57/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313432313635322f313231303137322f30663936623538302d323566362d313165332d386132652d3330653465383135323862352e676966) where the pattern isn't scaled but the spacing is
- scale the pattern but reset it when the user stops zooming


> In order to maximize the amount of time a texture is shown at actual size while also giving some illusion of movement, would it be possible to show static textures but then trigger a one-time animation in or out whenever user hits an integer zoom level?

I'm not following

> Continue to scale textures, but only underscale them. Never overscale them.

This would look pretty much like the current implementation except all patterns would be half as big.

**Comment by ansis** [comment]
> two possible approaches:

> - something like [this](this) where the pattern isn't scaled but the spacing is
> - scale the pattern but reset it when the user stops zooming

The first approach would work well for symbol patterns where the symbols are *not* seamlessly tiled. As you zoom the spacing between the symbols changes by the scale of the symbols doesn't. I think this would be implemented as part of the symbol type by adding a new `symbol-placement` value that would create lots of of individual symbol points to cover a polygon.

The second approach is the only approach I can think of that would work for seamless patterns. It might look weird it in it's own different ways.


cc @alinapaz

**Comment by KP** [comment]
For me, the approach that works best with seamless patterns is ideal.

**Comment by mollymerp** [comment]
When I get some time I'll start hacking on some enhancements to the pattern spec.

**Comment by ajashton** [comment]
Linking the scaled spacing ticket I opened a while back in the style-spec repo: https://github.com/mapbox/mapbox-gl-style-spec/issues/427

This month is the 3 year anniversary of that gif by @ansis btw, nice to see the convo moving :)

**Comment by alinapaz** [comment]
@KP does https://github.com/mapbox/mapbox-gl-js/issues/1831#issuecomment-247503214 help you track towards a solution?

**Comment by rudza** [comment]
Is there any progress on this?

**Comment by tomass** [comment]
Does this issue cover situations when pattern should not be scaled and rotated?
Say wetland symbol is one of the best known in maps and it will not be possible to ignore for a long time. Here is how wetland and meadow symbols look at x.99 scale and rotated:
![paveikslas](https://user-images.githubusercontent.com/969513/48310611-665e9900-e59a-11e8-85ea-2d5e840c504e.png)
This is how they look at x.0 and no rotation:
![paveikslas](https://user-images.githubusercontent.com/969513/48310629-a1f96300-e59a-11e8-9111-a599b480b7a8.png)

**Comment by ansis** [comment]
@tomass yes, this covers that problem. Thanks for the example!

**Comment by samanpwbb** [comment]
Better ideas for solving this are articulated in https://github.com/mapbox/mapbox-gl-js/issues/6296 and https://github.com/mapbox/mapbox-gl-js/issues/6295, closing here!

**Comment by kelvinabrokwa** [comment]
how is this ticket still haunting me 4 years later 😩

**Comment by anish01stha** [comment]
Any updates?

**Comment by BramOoms** [comment]
@ansis Is the code of your demo available somewhere?
