### ISSUE TITLE
Can we reduce sensitivity of map rotate?

### ISSUE THREAD

**Issue by AbrahamArun** [mapbox/mapbox-gl-js#1839]
While pinching the map to zoom out or in, it rotates a lot compared to interactivity in google maps. Is there some way to control this sensitivity?

**Comment by liebrand** [comment]
FYI: I have a PR out that adds support for the pinch zoom to block the rotate much like how Google Maps seems to do it: https://github.com/mapbox/mapbox-gl-js/pull/1917

**Comment by AbrahamArun** [comment]
@liebrand Thank you for sharing the info. I am just waiting to see your PR merged. ;)

**Comment by bhousel** [comment]
This was merged in 4166ec3 / f17246e
