### ISSUE TITLE
simplification tolerance option for layer source

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#1840]
https://www.mapbox.com/mapbox-gl-js/api/#GeoJSONSource
What does options.tolerance do?

Can these options be used together with map.addSource as well?

**Comment by lucaswoj** [comment]
That parameter gets passed through [`geojson-vt`](https://github.com/mapbox/geojson-vt/blob/master/src/simplify.js#L7) to an implementation of the Douglas-Peucker algorithm. 

 - [tl;dr explanation](http://gis.stackexchange.com/questions/11910/meaning-of-simplifys-tolerance-parameter)
 - [longer explanation](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm)

We should update our docs to clarify this.

**Comment by lucaswoj** [comment]
It should work seamlessly with `addSource`.

**Comment by musicformellons** [comment]
Thanks!

**Comment by lucaswoj** [comment]
merged as https://github.com/mapbox/mapbox-gl-style-spec/pull/393
