### ISSUE TITLE
Can we remove `gl` as even an optional dependency?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1845]
`gl` is a big module that's a binary build - it slows down `npm install` of things that rely on `mapbox-gl-js` significantly. Could we avoid having it be npm installed when people install gl-js as a dep?

**Comment by jfirebaugh** [comment]
We can move it to devDependencies.

**Comment by lucaswoj** [comment]
the proposed `optionalDevDependencies` feature would have been an ideal solution to this https://github.com/npm/npm/issues/3870 (but it doesn't exist yet)
