### ISSUE TITLE
text-offset on multi-line point labels

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-gl-js#1847]
![](http://i.imgur.com/u41Rgv4.png)

The text-offset property is only affecting the first line for x values on multi-line labels.

**Comment by nickidlugash** [comment]
Bump :) Would anyone be able to outline here how big of a lift this is and/or when this might get fixed? We need this styling property for a few current styles.

**Comment by lucaswoj** [comment]
@nickidlugash I'll dig into this tomorrow. I have a hunch it will be a relatively easy fix.

**Comment by nickidlugash** [comment]
@lucaswoj awesome, thanks :)

**Comment by lucaswoj** [comment]
We should also add a `mapbox-gl-test-suite` test for this

**Comment by kelvinabrokwa** [comment]
done in https://github.com/mapbox/mapbox-gl-js/pull/1885
