### ISSUE TITLE
Addition of the plugins link causes layout issues on narrow screens

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1848]
![img_4372](https://cloud.githubusercontent.com/assets/281306/11882294/71a22aa2-a4c0-11e5-917e-9fce5a15ee23.jpg)

<img width="700" alt="screen shot 2015-12-17 at 1 17 04 pm" src="https://cloud.githubusercontent.com/assets/281306/11882304/7fc4f484-a4c0-11e5-8af7-1741177ab478.png">

cc @tristen

**Comment by tristen** [comment]
https://github.com/mapbox/mapbox-gl-js/pull/1850
