### ISSUE TITLE
background-pattern rendered incorrectly when pattern resolution does not match devicePixelRatio

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1851]
If a sprite contains a pattern whose pixel ratio is not the same as the devicePixelRatio (e.g., `@2x` not available, on a `@3x` device but only `@2x` available), the pattern is incorrectly rendered. This is exposed by the `sprites/1x-screen-2x-pattern` and `sprites/2x-screen-1x-pattern` tests in the test suite.

### 1x-screen-2x-pattern

expected: 
![image](https://cloud.githubusercontent.com/assets/98601/11904499/6fbb1cd4-a575-11e5-8edd-f85fd61850b4.png)

actual: 
![image](https://cloud.githubusercontent.com/assets/98601/11904504/761092c6-a575-11e5-8091-3af6e13d0d81.png)

### 2x-screen-1x-pattern

expected:
![image](https://cloud.githubusercontent.com/assets/98601/11904510/7f322676-a575-11e5-91cc-d7439dc69e5f.png)

actual:
![image](https://cloud.githubusercontent.com/assets/98601/11904513/82b666b8-a575-11e5-84ac-898c95f77e97.png)

Related to #1124, in that native has the correct rendering because it scales sprites when adding them to the atlas. But the desired solution will fix this without scaling in the atlas (c.f. https://github.com/mapbox/mapbox-gl-native/issues/3164).

**Comment by jfirebaugh** [comment]
Similar problems with icon rendering.

### 1x-screen-2x-icon

expected: 
![image](https://cloud.githubusercontent.com/assets/98601/11904668/707b9e40-a576-11e5-822b-4bf2b12ea897.png)
actual: 
![image](https://cloud.githubusercontent.com/assets/98601/11904670/7561b62e-a576-11e5-8889-92935636f738.png)

### 2x-screen-1x-icon

expected: 
![image](https://cloud.githubusercontent.com/assets/98601/11904687/9fe111d8-a576-11e5-910e-25404a9d4331.png)
actual: 
![image](https://cloud.githubusercontent.com/assets/98601/11904689/a73db44a-a576-11e5-8f90-8d4623cb0549.png)

**Comment by jfirebaugh** [comment]
Note: if you fix the scaling issue and find that the result still don't match between js and native, I suspect there's _also_ an off-by-one issue in native's padding in some cases.

**Comment by ansis** [comment]
This is mostly fixed by https://github.com/mapbox/mapbox-gl-js/commit/8f787fd16227febfcf9a65c908c063ed0a16e642 but there are off-by-one issues:

<img width="500" alt="screen shot 2016-01-11 at 2 26 46 pm" src="https://cloud.githubusercontent.com/assets/1421652/12248762/5ace1b38-b870-11e5-812f-c40443b7fe7d.png">

**Comment by ansis** [comment]
fixed by https://github.com/mapbox/mapbox-gl-js/pull/1919
