### ISSUE TITLE
flyTo refuses to cross antimeridian

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#1853]
`flyTo()` optimizes for frequent flier miles, traversing the entire world instead of simply crossing the antemeridian when the endpoints straddle the antemeridian. For example, alternate between the following lines, which are on either end of Fiji:

```js
map.flyTo({center: [178.4730, -18.1014], zoom: 4, bearing: Math.random() * 60, pitch: Math.random() * 360})
map.flyTo({center: [-178.8177, -18.1979], zoom: 4, bearing: Math.random() * 60, pitch: Math.random() * 360})
```

/cc @lucaswoj @mourner

**Comment by mourner** [comment]
:+1: currently the logic is to stay on the center world copy, but we could modify it so that we fly to the closest longitude considering world wrap.
