### ISSUE TITLE
Can mapbox-gl-js request lower "fallback" zoom tiles?

### ISSUE THREAD

**Issue by liebrand** [mapbox/mapbox-gl-js#1855]
I have a some vector data which (with the use of tippecanoe) I have converted to mb tiles. The resolution is good enough to generate the tiles at a max zoom level of 12, and mapbox-gl-js does a good job of overzooming when I zoom in beyond that level.

However, if I was already zoomed in at say level 16, then it will merely get 404s when it tries to request the tiles at level 16. Thus nothing shows on the screen. I have to first zoom back out to level 12 to see anything being drawn, and then if I zoom in again, it overzooms OK.

Similarly, if I were to then pan around to areas for which mapbox-gl-js did not yet retrieve any tiles at level 12, then it will attempt to retrieve them at the current level 16 zoom level. For which again it would receive 404s and render nothing.

Is it possible to make mapbox-gl-js smarter, such that if it receives a 404 for a tile at zoom level n that it would attempt to retrieve the tile of zoom level n-1?  And all the way up to zoom level 1 if it needs to, that way it could draw at least something correctly?

My only current alternative is to generate tiles at all zoom levels up to and including level 16. But that takes hours (actually, more likely days) for my given data. And it's wasteful, costing GBs of data that I shouldn't need. Most tiles at zoom level 16 are just rectangle geojson for that entire tile... And as I mentioned, the vector data at zoom level 12 is good enough for my purpose.

(Here's the bug from tippecanoe for reference https://github.com/mapbox/tippecanoe/issues/116)

**Comment by liebrand** [comment]
Or (just thinking about this), should the tileserver simply return the level 12 tile even if the level 16 is requested?

**Comment by jfirebaugh** [comment]
Did you specify [`maxzoom` in the source](https://www.mapbox.com/mapbox-gl-style-spec/#sources)?

**Comment by liebrand** [comment]
Aahhh maxzoom as opposed to maxZoom like the property of the map!! That lower case 'z' makes all the difference ;-)

This is working now, thanks!

**Comment by jfirebaugh** [comment]
Dang, I knew the upper-vs-lower-case issue was going to trip someone up: #909. Sorry about that! Glad to hear it does work though.
