### ISSUE TITLE
line pattern bug

### ISSUE THREAD

**Issue by dagatsoin** [mapbox/mapbox-gl-js#1856]
When choosing a pattern for a line, the pattern seems to be stretched all along the line instead to be tiled.
![image](https://cloud.githubusercontent.com/assets/3670794/11913276/1e0889c2-a65f-11e5-88c9-53eaa0a410ca.png)

PS: Not tested on iOS yet

**Comment by lucaswoj** [comment]
The way we scale `line-pattern` is strange. Here's my impression of how it works:

 - at integer non-overzoomed zoom levels, the line-pattern is displayed at 1:1 size, tiled along the line as expected
 - at non-integer non-overzoomed zoom levels, the line-pattern is displayed at 1:1 size along the axis perpendicular to the line and stretched along the axis parallel to the line
 - at overzoomed zoom levels, the pattern stretched further and further from the last integer non-overzoomed zoom level until it ends up looking like the screenshot above

I think we should support customizable line scaling, like we're thinking about doing for fill-patterns in #1831.

**Comment by ansis** [comment]
This is fixed by 57aa3e8
