### ISSUE TITLE
Add a max-width to popup containers

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#1862]
The default style should perform well. Without a max-width it looks like this:

![popup-max-width](https://cloud.githubusercontent.com/assets/61150/11961308/bb0e8f12-a8a5-11e5-87e4-266fd7076ce4.gif)

**Comment by lyzidiamond** [comment]
+1 to this

**Comment by jfirebaugh** [comment]
What do you propose for a default value? If we can find a value that looks decent for a variety of map/screen/popup sizes, :+1:.

**Comment by tristen** [comment]
240px _should_ work. I'll test it out on a few devices first.

**Comment by jfirebaugh** [comment]
It would also be really nice if this was user controllable by specifying an inline `style="max-width: x"` attribute in the HTML passed to `Popup#setHTML`, rather than needing to override specific mapbox-js.css CSS in their own CSS. I'm not sure that's possible, which is why I didn't do this before.

**Comment by tristen** [comment]
@jfirebaugh then this isn't an issue - a user can already specify an inline max width to a container div that surrounds what's passed to `Popup#setHTML`. But it's not exactly nice it has to be done that way and I've never seen a problem overriding CSS.

**Comment by jfirebaugh** [comment]
The ideal behavior is to have a default max-width, but be able to override it with inline styling. If that's not possible, then yeah, as CSS override is the next best option. But it means that certain parts of mapbox-js.css are effectively part of the public API and are change-constrained by semver. So if we do that let's at least add a comment to the CSS saying "this is a public API; don't rename the class or change the specificity".

**Comment by tristen** [comment]
That's probably a good notice to add to the top of the stylesheet as It's applicable to everything then. I mean, I regularly override default styles like here:

<img width="267" alt="screen shot 2016-01-05 at 11 14 50 pm" src="https://cloud.githubusercontent.com/assets/61150/12134900/4bdcf0bc-b402-11e5-8325-11011e06cd39.png">

Or here

<img width="274" alt="screen shot 2016-01-05 at 11 15 13 pm" src="https://cloud.githubusercontent.com/assets/61150/12134903/500bb254-b402-11e5-8897-28533b91bea2.png">


¯\_(CSS)_/¯

**Comment by Avatar88** [comment]
hey @tristen , 
How would the CSS code for these popup?
thanks

**Comment by ciukstar** [comment]
How should I override `max-width` of a popup? Thanks.

**Comment by ryanhamley** [comment]
@ciukstar You can pass in an options object with a `maxWidth` property when you create Popup. Alternatively, you can call `popup.setMaxWidth()`. Any valid CSS value will work. See the docs [here](https://docs.mapbox.com/mapbox-gl-js/api/#popup).
