### ISSUE TITLE
Replace "popup-on-click" example with "marker-popup"

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#1864]
Replace https://www.mapbox.com/mapbox-gl-js/example/popup-on-click/ with https://www.mapbox.com/mapbox-gl-js/example/marker-popup/ and redirect the latter to the former. The one with markers is much more of a real-world example, and will parallel #1861.

**Comment by tristen** [comment]
https://github.com/mapbox/mapbox-gl-js/pull/2119
