### ISSUE TITLE
text-max-angle is not working (because of missing unsupported text-max-size property?)

### ISSUE THREAD

**Issue by liebrand** [mapbox/mapbox-gl-js#1870]
I am placing some labels along a LineString, but the text-max-angle property appears not to work. Some very quick (read: limited ;-)) debugging shows that the calculations for the anchors rely on a layout property "text-max-size":
https://github.com/mapbox/mapbox-gl-js/blob/d7ea136ac969ab8e08bb4db4963388b2e6679638/js/data/symbol_bucket.js#L223

Because that's used as the textMaxBoxScale, which in turn is used to calculate the 'angleWindowSize':
https://github.com/mapbox/mapbox-gl-js/blob/b7032636206448e16eb681836f97e79f0587fd7e/js/symbol/get_anchors.js#L15

And if that is not set, the code will not attempt to check the angles:
https://github.com/mapbox/mapbox-gl-js/blob/b7032636206448e16eb681836f97e79f0587fd7e/js/symbol/get_anchors.js#L76

The problem is that you can not set the layout property 'text-max-size' for a symbol layer. It throws an exception:
layers[5].layout: unknown property "text-max-size"(…)

Which means the textMaxBoxScale becomes NaN, and thus angleWindowSize is NaN, which means it never checks the angles...

**Comment by liebrand** [comment]
In addition I'm seeing some labels be cut off, which I suspect is because of tile edges. I do use symbol-avoid-edges: true, but that didn't make any difference. Could that be related to the same bug?

**Comment by jfirebaugh** [comment]
Can you provide a self-contained example style that demonstrates the issue?

**Comment by liebrand** [comment]
Sure thing. In the example below, I expect the label '123.45' to not be bent around the LineString, since I gave it a text-max-angle of zero. But it bends all the way around:

    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v8',
        center: [-122.45211124420166,37.83656426746953],
        zoom: 15
    });

    map.on('style.load', function () {
        map.addSource("route", {
            "type": "geojson",
            "data": {
                "type": "Feature",
                "properties": {
                    SOME_TEXT: '123.45'
                },
                "geometry": {
                    "type": "LineString",
                    "coordinates":[[-122.45211124420166,37.83656426746953],[-122.45221853256226,37.836632053401715],[-122.45241165161133,37.83664899987504],[-122.45254039764404,37.83661510692451],[-122.45279788970947,37.83647953496666],[-122.45296955108643,37.836276176562734],[-122.45299100875854,37.8362083903035],[-122.45301246643066,37.83610671079788],[-122.4529480934143,37.83597113790567],[-122.45288372039795,37.835937244643716],[-122.45266914367676,37.835937244643716],[-122.45251893997192,37.83597113790567],[-122.45236873626709,37.836055870992496],[-122.45219707489014,37.83619144372895],[-122.45213270187378,37.83629312311781],[-122.45208978652954,37.836377855834755],[-122.45211124420166,37.83656426746953]]
                }
            }
        });

        map.addLayer({
            "id": "route",
            "type": "line",
            "source": "route",
            "layout": {
                "line-join": "round",
                "line-cap": "round"
            },
            "paint": {
                "line-color": "#888",
                "line-width": 1
            }
        });
        map.addLayer({
          "id": "contour-labels",
          "type": "symbol",
          "source": "route",
          "layout": {
            "text-field": "{SOME_TEXT}",
            "symbol-placement": "line",
            "text-max-angle": 0,
            "symbol-avoid-edges": true
          },
          "paint": {
            "text-color": "#000"
          }
        });

    });
