### ISSUE TITLE
singleClick map event

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#1874]
Are there any intentions to add debouncing functionality to achieve a singleClick event on the map?

Since the dblClick event normally is used for zooming the user experience in not great when using the regular click event (since double clicking triggers both a zoom and regular click events).

Both existing demos on clicking suffers from this (try double clicking on the features):
https://www.mapbox.com/mapbox-gl-js/example/center-on-symbol/
https://www.mapbox.com/mapbox-gl-js/example/popup-on-click/

Of course one can use timers to wrap the map events and facilitate debouncing in client code.

**Comment by mourner** [comment]
> Of course one can use timers to wrap the map events and facilitate debouncing in client code.

Yes, I think that's the way to go here. If we do `singleclick` by default, we inevitably introduce an unwanted delay, and there's no need to make it an option in the core given how easy it is to implement on the app side.

**Comment by pcwa-ahendricks** [comment]
if anyone is bringing in rxjs you can do something like...

```
clickSub$ = clickObs$
      .bufferWhen(() => clickObs$.debounceTime(300))  // whatever you feel is reasonable i suppose
      .filter(list => list.length === 1)
      .switchMap((item: any) => item)
      .subscribe((cEvt: any) => {
        console.log('(single)click fired: ', cEvt);
        // do something magical...
      });
```
