### ISSUE TITLE
Fix landcover flicker in Mapbox Streets style

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#1875]
Perhaps this is a dupe, but I didn't find any other issue on it..

When zooming in/out on streets what I believe is the landcover layer starts to flicker considerably. This does not seem to appear on the other styles, so it seems it is something related to this particular layer in the streets style itself.

![flicker2](https://cloud.githubusercontent.com/assets/1205805/12006529/4626dc12-abda-11e5-98f8-f2e960dbd027.gif)

**Comment by lucaswoj** [comment]
Not a dupe, as far as I know, but it reminds me a little of #1270. Can you repro this across all browsers?

**Comment by averas** [comment]
My report was made on Chrome/OSX. Same experience in Safari/OSX and Firefox/OSX. Tested on a Mac with retina resolution.

I don't have easy access to IE.

**Comment by ansis** [comment]
002c69071275997886fd98aa4dbc6025eed36a86 fixes this

**Comment by averas** [comment]
Was this actually fixed? Or is it back? I see considerable flicker on streets when zooming slowly in and out around zoom level 11-13.

**Comment by ansis** [comment]
I'm not able to reproduce this anymore on master. Does it still look like the flickering in the original gif, or is it different now?

**Comment by averas** [comment]
Well.. it might be a little bit more subtle.. but I don't know. Fresh video from Mapbox GL JS Examples (which I believe is using 0.13.1):

![new_flicker](https://cloud.githubusercontent.com/assets/1205805/12831156/18e17bb2-cb93-11e5-8afa-d7ffc2875044.gif)

My impression is that the effect is more clear in Mapbox Studio, either just perceptually because the map canvas is larger, or because rendering is a bit slower.

OS.X (El Capitan), Chrome, Retina Display.

**Comment by mourner** [comment]
@stevage do you still see this issue? I can't reproduce this on latest stable Chrome / OS X / Retina.

**Comment by stevage** [comment]
Me? Don't think I ever saw it. But for the record, I don't seem to be able to reproduce this effect using Mapbox Streets now.

**Comment by averas** [comment]
I think that the Mapbox core styles have been updated since I originally filed this issue making it a bit harder to reproduce, but I was still able to. To make it clearer I made a custom style based on Mapbox streets - nothing added, just removed a bunch of layers:

Goto https://api.mapbox.com/styles/v1/averas/cj1pk7b7d005q2so1r3t5kiag.html?title=true&access_token=pk.eyJ1IjoiYXZlcmFzIiwiYSI6ImRrb1Z6NXcifQ.8v3wimUeRVTvOMbozrwkfw#2.7/-2.02/27.21

Start zooming in _slowly_ over Africa. I see flickering starting around zoom 3 and intensifying up until ~ zoom 6 and it diminishes at zoom 7. It's clearly related to the opacity ramps of the grass/crop landcover layers. My impression is that the opacity ramp is non-linear perceptually, as it gives a subtle impression that the color oscillates between greenish/brownish.

![flicker-new](https://cloud.githubusercontent.com/assets/1205805/25205709/4b91644c-2564-11e7-84fa-af3dda457b7b.gif)

MacBook Pro (Retina, 15-inch, Late 2013) / Chrome Version 57.0.2987.133 (64-bit) (Also tested in Safari and Firefox)

**Comment by jfirebaugh** [comment]
Very strange. I see what you're talking about in the gif, but I can't reproduce that effect locally either. MacBook Pro (Retina, 13-inch, Early 2015) / Chrome 57.0.2987.133.

**Comment by stevage** [comment]
Me too - see it in the gif, not for real though. Macbook Pro Retina 15 inch mid-2014 (wow, is it that old already?), Chrome 57.0.2987.133 (and Firefox) either on laptop screen or externally. Also tried using either touchpad or scroll mouse.

**Comment by averas** [comment]
@jfirebaugh / @stevage Yes, that's really strange. Perhaps model-specific then.. I will check with some newer MacBooks at the office tomorrow.

If have the NVIDIA GeForce GT 750M (2048 MB) + Intel Iris Pro 5200 (1536 MB), but that ought to be the same configuration as @stevage has...

**Comment by stevage** [comment]
Yep, "Graphics  Intel Iris Pro 1536 MB".

I vaguely recall changing some WebGL settings in Chrome once...but you say you see it in Firefox too.

Are you able to produce an example with a different dataset? Or at least, style it so the difference in colours is clearer?

**Comment by mourner** [comment]
I can finally see the flickering with the test case above (although it's quite subtle). MBP Retina mid-2012, Nvidia GT 650M, Chrome.

**Comment by jfirebaugh** [comment]
Is this still reproducible? It may have been the same issue as #5490 / #5704 / https://bugs.chromium.org/p/chromium/issues/detail?id=784030.

**Comment by averas** [comment]
It's still reproducible for me on Chrome/OSX, Safari/OSX and Firefox/OSX, on my very same good old MacBook Pro (Retina, 15-inch, Late 2013) with NVIDIA GeForce GT 750M (2048 MB) + Intel Iris Pro 5200 (1536 MB) using the same map as above: 

https://api.mapbox.com/styles/v1/averas/cj1pk7b7d005q2so1r3t5kiag.html?title=true&access_token=pk.eyJ1IjoiYXZlcmFzIiwiYSI6ImRrb1Z6NXcifQ.8v3wimUeRVTvOMbozrwkfw#2.7/-2.02/27.21

I suspect it's platform/hardware related though.. trying out the same map at a newer Mac did not render the same issue.. so perhaps it's not worth spending time on this.

**Comment by mourner** [comment]
> I suspect it's platform/hardware related though.. trying out the same map on a newer Mac did not render the same issue.. so perhaps it's not worth spending time on this.

Yeah, it seems like there's nothing we can do on the GL JS side to address this, and given low severity of the issue, I think it's safe to close.
