### ISSUE TITLE
White squares when using a raster tile source

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#1876]
Perhaps this is a dupe, but I didn't find any other issue on it..

When using a raster tile source (like the one in the demo) I sometimes get blank (white) squares after zooming in/out. It seems more prone to happening if I scroll using the trackpad and "abort" the zooming by tapping the trackpad during zooming.

![white_raster_tiles](https://cloud.githubusercontent.com/assets/1205805/12006567/fe11babc-abdb-11e5-8bd0-fc617107dd53.gif)

**Comment by lucaswoj** [comment]
I have seen this too
