### ISSUE TITLE
"icon-image": "{marker-symbol}-15" doesn't work on a satellite raster map

### ISSUE THREAD

**Issue by gertcuykens** [mapbox/mapbox-gl-js#1878]
"icon-image": "{marker-symbol}-15" doesn't work on my own satellite raster map only streets-v8?

**Comment by jfirebaugh** [comment]
The `satellite-v8` sprite has no icons. If you want to use icons, you'll need to create a custom style in Mapbox Studio and add them as desired.

**Comment by gertcuykens** [comment]
Hmm confusing, can you explain please?

![image](https://cloud.githubusercontent.com/assets/863731/12100590/4921729e-b330-11e5-8b5c-18b1e5a64b0e.png)

![image](https://cloud.githubusercontent.com/assets/863731/12100782/59c4735c-b331-11e5-972b-d84af67e9f7f.png)


I expect marker icons added by this layer code "icon-image": "{marker-symbol}-15" to display on any background map, street, satellite or custom?

For example

```
 map.addLayer({
        "id": "markers",
        "interactive": true,
        "type": "symbol",
        "source": "markers",
        "layout": {
            "icon-image": "{marker-symbol}-15"
        }
    });
```
