### ISSUE TITLE
Update coordinates for ImageSource (and possibly VideoSource)

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#1880]
In a use case I have I need to adjust the coordinates of an ImageSource, but the current API only permits providing the coordinates when adding the source. I've managed to get around this by removing and adding the source when the coordinates change, but as you can imagine this is quite inefficient and causes considerable flicker when many changes occur. I imagine this is related to both the fact that removing and adding the source comes with some overhead, but also that the ImageSource performs an AJAX operation to fetch the image every time..

Would it be a huge effort to extend the ImageSource API to allow for updating the coordinates?

**Comment by averas** [comment]
I'm currently achieving this by calling <code>map.getSource(...).createTile([newCoords])</code> where createTile obviously isn't part of the public API. I wonder though, is the approach "correct" in principle? And if so, would it be right to wrap it in a public function, such as <code>setCoordinates()</code>, similar to <code>GeoJSONSource#setData()</code>.

Perhaps one would want to consider the interface for sources in general and incorporate this functionality as part of a general design to make source options mutable.

**Comment by jfirebaugh** [comment]
Yes, I think `{ImageSource,VideoSource}#setCoordinates()` would be the appropriate APIs to add here. It looks like an implementation might be as simple as renaming `createTile` and making it public.

**Comment by lucaswoj** [comment]
> It looks like an implementation might be as simple as renaming `createTile` and making it public.

That and making `createTile` set `this.coordinates` so that `serialize` still works correctly.
