### ISSUE TITLE
No continuous rendering during zooming with an enabled ImageSource

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#1881]
Aside from the fact that performance seems to degrade quite fast when using larger images with the ImageSource, it also seems that rendering if affected even with quite small/normal images.

When zooming out with a 200kB PNG overlayed using ImageSource I even noticed that there is no continuous rendering at all taking place and a sudden update comes when I stop zooming:

![zoom-out-imagesource](https://cloud.githubusercontent.com/assets/1205805/12046018/6dc8c21c-aeaf-11e5-8241-a7717b8f5e52.gif)

This even happens regardless of whether the image is in the viewport or not, i.e. I can zoom in/out somewhere else on the map, but as long as the ImageSource is added this occurs. Is this expected?

When testing with larger images I experience a quite substantial performance impact on zooming/panning. Are there some expensive operations going on during rendering here?

**Comment by jfirebaugh** [comment]
Can you link to the code for the above gif?

**Comment by averas** [comment]
Sure! It's essentially the example from your site but with the image swapped for another one.

http://codepen.io/anon/pen/XXpGoR#0

1) Zoom in over the image
2) Wait for the label layer to render
3) Slowly zoom out

**Comment by averas** [comment]
With <code>streets</code> this is even more evident, and there you also start to see performance affected.

http://codepen.io/anon/pen/obBOXP

**Comment by averas** [comment]
Were you able to reproduce this? For me its only present in Chrome/OSX, not Safari or Firefox.
