### ISSUE TITLE
error loading tile not fount

### ISSUE THREAD

**Issue by rbonillajr** [mapbox/mapbox-gl-js#1883]
This error is reported above.
Thanks

![image](https://cloud.githubusercontent.com/assets/8268226/12095186/02aa877e-b2db-11e5-8aa4-bce5b7feb386.png)

![image](https://cloud.githubusercontent.com/assets/8268226/12095146/cb330c62-b2da-11e5-80de-517f7705516f.png)

**Comment by jfirebaugh** [comment]
404s for custom tiles is likely an expected condition and can be ignored. We're planning to do that at a code level in #1800.
