### ISSUE TITLE
Provide additionally a CDN link to the latest version of the library

### ISSUE THREAD

**Issue by manuelroth** [mapbox/mapbox-gl-js#1890]
Currently a CDN link with a specific version number is provided. It would be very handy to have an alternative link to the latest released version of the library. 

#### Scenario:
Somebody just always wants to benefit of the latest features and bug fixes. And does not care if the newest version includes breaking changes.

#### Benefit for users:
One does not always have to update the version number to get the latest version available.

#### Suggestion:
Provide alternatively a "latest" version of the library.
```html
<script src='https://api.tiles.mapbox.com/mapbox-gl-js/latest/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/latest/mapbox-gl.css' rel='stylesheet' />
```

**Comment by mourner** [comment]
No, this considered is a really bad practice, since a version update could introduce breaking changes and consequently break production websites without you even knowing about it. You should always manually update versions.
