### ISSUE TITLE
Building master branch fails on Windows during "gl@2.1.5 install: `prebuild --download`"

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#1891]
Hello,

I just updated to master and ran npm install (I just removed the npm run-docs as it crashes on Windows, I already opened another issue about this, but it's ok, I don't need the docs)
Here is the stack after launching npm-install:
```
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"0.12.4","npm":"2.10.1"})
npm WARN deprecated pngjs2@2.0.0: pngjs2 has now taken over the original pngjs package on npm. Please change to use pngjs dependency, version 2+.
|
> gl@2.1.5 install D:\Workspaces\Windows8\mapbox-gl-js-master\mapbox-gl-js\node_modules\gl
> prebuild --download

prebuild WARN install Prebuilt binaries for node version v0.12.4 are not available
gyp: angle\build\standalone.gypi not found (cwd: D:\Workspaces\Windows8\mapbox-gl-js-master\mapbox-gl-js\node_modules\gl) while reading includes of angle\src\angle.gyp while loading dependencies of binding.gyp while trying to load binding.gyp
prebuild ERR! configure error
prebuild ERR! stack Error: `gyp` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onCpExit (D:\Workspaces\Windows8\mapbox-gl-js-master\mapbox-gl-js\node_modules\gl\node_modules\node-gyp\lib\configure.js:305:16)
prebuild ERR! stack     at ChildProcess.emit (events.js:110:17)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
prebuild ERR! not ok
prebuild ERR! build Error: `gyp` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onCpExit (D:\Workspaces\Windows8\mapbox-gl-js-master\mapbox-gl-js\node_modules\gl\node_modules\node-gyp\lib\configure.js:305:16)
prebuild ERR! build     at ChildProcess.emit (events.js:110:17)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! gl@2.1.5 install: `prebuild --download`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the gl@2.1.5 install script 'prebuild --download'.
npm ERR! This is most likely a problem with the gl package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls gl
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Workspaces\Windows8\mapbox-gl-js-master\mapbox-gl-js\npm-debug.log
```
Attached is the log file 
[npm-debug.txt](https://github.com/mapbox/mapbox-gl-js/files/78871/npm-debug.txt)

Let me know if I can do further testing, I know you don't have many Windows machines around at Mapbox :)
Fabien

**Comment by jfirebaugh** [comment]
This is an upstream issue in https://github.com/stackgl/headless-gl. The error message indicates that prebuilt binaries are not available for Windows + node v0.12.4, and then it tries to fall back to building from source and produces a follow on error that I'm not familiar with.

Windows isn't one of our targeted development environments, so we're unlikely to invest in tracking this down, but of course if you are, it would be appreciated.

**Comment by lucaswoj** [comment]
This failure might be related to our move of `gl` from `optionalDependencies` to `devDependencies` https://github.com/mapbox/mapbox-gl-js/issues/1845

**Comment by fnicollet** [comment]
Thanks @lucaswoj , by reverting commit from https://github.com/mapbox/mapbox-gl-js/pull/1846, the build works and master works just fine.
I don't know how package.json works, if you can have configuration per OS but it's too bad to be restricted to unix systems just for a simple difference.

Anyway, I'll keep my package.json modification in my fork, you do as you wish for master :)

Fabien

**Comment by nicoabie** [comment]
@lucaswoj I'm using a vagrant linux machine (3.13.0-74-generic #118-Ubuntu) with node v0.12.9 and it fails too.
I'm not sure if this is a windows only problem.

Btw as @fnicollet confirmed, reverting the commit fixes the issue.

**Comment by mourner** [comment]
We should also try a more recent version of https://github.com/stackgl/headless-gl, it seems to have some Windows-related fixes.
