### ISSUE TITLE
featuresIn results don't match original data in precision

### ISSUE THREAD

**Issue by rbonillajr** [mapbox/mapbox-gl-js#1892]
add two point en map and zoom in 
https://jsfiddle.net/rbonillajr/ngdetqL5/

![image](https://cloud.githubusercontent.com/assets/8268226/12125322/c79af3ba-b3b8-11e5-9581-8ad0434bcd82.png)

![image](https://cloud.githubusercontent.com/assets/8268226/12125333/d9438906-b3b8-11e5-93df-408927594574.png)

**Comment by jfirebaugh** [comment]
I don't understand this report. Thanks for the code sample, but can you please say what you believe the bug is?

**Comment by rbonillajr** [comment]
I can select markers in polygon.

blue marke are all infeature and yellow are selected.

the yellow marker must be in the same position.

thanks.

**Comment by rbonillajr** [comment]
if the zoom is close works well

![image](https://cloud.githubusercontent.com/assets/8268226/12125725/fc37ecd4-b3ba-11e5-975b-d41c542e99f6.png)

**Comment by rbonillajr** [comment]
another case is that when there are many markers do not come all

example:

![2016_01_05_14_49_34_edit_fiddle_jsfiddle](https://cloud.githubusercontent.com/assets/8268226/12126573/f1bbf278-b3bf-11e5-9851-8c723301bf77.png)

**Comment by bhousel** [comment]
Hey @rbonillajr, thanks for the jsfiddle, that really helps us debug.
I'm hitting a lot of circle undefined / not found errors (#1933) so I'll revisit once we have that fixed.

I also see what you are seeing: that while the results from `featuresIn` usually match up with the original data, there are sometimes precision issues.

<img width="347" alt="screenshot 2016-01-15 10 29 17" src="https://cloud.githubusercontent.com/assets/38784/12356910/10ad898e-bb73-11e5-8997-3fb30f2c89c4.png">

**Comment by rbonillajr** [comment]
ok thanks @bhousel

**Comment by lucaswoj** [comment]
I suspect this error has been fixed since we have rewritten the API.
