### ISSUE TITLE
Calling remove() on the mapbox-gl-js crashes

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#1900]
Calling remove() crashes on this line in IE11:
```
this._canvasContainer.remove();
```
As _canvasContainer is a DOM element, it has no remove method.
Same for _controlContainer on the next line

So, diffing a little bit, the change was introduced by @jfirebaugh  in this commit:
https://github.com/mapbox/mapbox-gl-js/commit/2524d95d7ebd5d840601b81de4061a63caf0b6bb#diff-274e90d38623e2e16a5e7d34414f33c7

Looks like there is a confusion between two "create" functions, one in dom.js and one in broswer/dom.js:
https://github.com/mapbox/mapbox-gl-js/search?utf8=%E2%9C%93&q=tagName%2C+className%2C+container

I don't know how this export.create works but is one overriding the other? In the dist/*-dev.js version, the dom.js version is not even present

Thanks,
Fabien

**Comment by jfirebaugh** [comment]
DOM elements [do have a `remove()` method](https://dom.spec.whatwg.org/#dom-childnode-remove), so this is an IE incompatibility.

**Comment by fnicollet** [comment]
Ah yes, the browser compatibility is only for Edge:
Chrome 23.0
Firefox (Gecko) 23.0
Internet Explorer Edge	
Safari 10.0	7.0
Not supported in Safari mobile nor IE mobile

The polyfill from Mozilla
```
if (!('remove' in Element.prototype)) {
    Element.prototype.remove = function() {
        if (this.parentNode) {
            this.parentNode.removeChild(this);
        }
    };
}
```
Should it be included in mapbox-gl-js source?

Fabien

**Comment by mourner** [comment]
I think we should just replace both lines with `node.parentNode.removeChild(node)`, or add an util method. `Node.remove` is a relatively recent addition (DOM4).

**Comment by fnicollet** [comment]
Created a PR with @mourner advices, fixes the issue:
https://github.com/mapbox/mapbox-gl-js/pull/1901
