### ISSUE TITLE
`featuresAt` sometimes returns nothing after layer's source is modified

### ISSUE THREAD

**Issue by andest01** [mapbox/mapbox-gl-js#1911]
`featuresAt` works fine after adding about 50,000 symbols in a small cluster. If I implement a click to center (e.g. https://www.mapbox.com/mapbox-gl-js/example/center-on-symbol/ ), each click centers perfectly.  However, when rapidly adding and removing elements to the layer's source, some calls to `featuresAt` do not return any features, even when clicking over several symbols. It works, but intermittently. 

Here is a plunkr that reproduces this issue:
https://plnkr.co/edit/3COaxhnCjlLTr1YQt2nW?p=preview

Steps to reproduce:
1). Open Chrome Dev Tools and open the plunkr
2). Ensure the line `startJittering();` is not commented out. Observe the thousands of gray symbols, and notice that they seem to "shimmer" slightly due to elements being added and removed very quickly. 
3). Click inside the cluster of gray symbols. Note that some clicks do not center, and a log is shown in the developer console that says "EMPTY CLICK DETECTED".

Expected behavior:
`featuresAt` returns several features over the cluster, even when elements have been added and removed.

To stop the bug and see correct behavior, comment out the line `startJittering();` Clicking anywhere in the cluster now works perfectly.

All that `startJittering` does is create a `setInterval` that adds and removes data from the source. I assume this is considered correct use of the API.

**Comment by ansis** [comment]
I wasn't able to reproduce the issue

[v0.16.0 replaces `featuresAt` with `queryRenderedFeatures`](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#0160-march-24-2016). Can you check if this is still an issue for you with v0.16.0?

**Comment by andest01** [comment]
I'd be happy to try this out.

**Comment by tmcw** [comment]
@andest01 any luck trying your code with the new queryRenderedFeatures method?

**Comment by lucaswoj** [comment]
Closing as stale. Potential duplicate of #2647
