### ISSUE TITLE
Map size print bug

### ISSUE THREAD

**Issue by derrickpelletier** [mapbox/mapbox-gl-js#1915]
If I have a map container that is fluid, 100% width and height, the map behaves properly in browser as the window resizes.

When I print (to pdf, irrelevant?), the map container fills the area, the `.mapboxgl-control-container` subsequently fills the area as well, but the `canvas.mapboxgl-canvas` does not not seem to respond. So the controls go to the full width/height (usually beyond the width of the map, and things look bad.

Probably because the `canvas` itself has pixel values set on it, per a resize event, so it's never _actually_ fluid, i guess?

I think the resize event still fires when the print is happening but maybe it happens too late? If i manually force the `canvas` to something like 100px wide, in the inspector, and then open the print dialog, it actually does trigger a resize on the page, but the element is still relative to that 100px in the pdf window

**Comment by derrickpelletier** [comment]
Don't leave this open for my sake! No longer need this on my end.

**Comment by chrisregner** [comment]
For anyone who stumbled here, my fix is this

1. Always render the map in the desired width and height, in a div with 1px width and height, and with overflow hidden.
2. (React specific) upon button click, I use `react-to-map`'s `useReactToPrint` (which allows me to pass the ref of the element for printing, without it actually being visible) with the ref of the content of the 1px div.
