### ISSUE TITLE
state_label filter on area isn't working

### ISSUE THREAD

**Issue by cwodwrth** [mapbox/mapbox-gl-js#1922]
The best way to replicate this is to create a fresh Streets style map, open the State labels folder, select state-label-lg, select data. Remove the filter, and add it again with the exact same parameters >= 80000. The labels that were highlighted before removing the filter are no longer highlighted after adding the same filter back on. This doesn't seem to be a problem with Streets, the same thing happens if you open and Empty style and try to add this data. Filtering on the abbr or the name still seem to work fine, but filtering on things like the osm_id (> 0) fail as well.

**Comment by lucaswoj** [comment]
Thank you for the report @cwodwrth. We have fixed this bug in Studio and will deploy the fix with the next release.
