### ISSUE TITLE
featuresAt when using an icon-offset

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#1924]
In the example at https://www.mapbox.com/mapbox-gl-js/example/marker-popup/ if I use pin style map markers rather than circle markers from the example, and then use icon-offset for the icon so that the pin head is set to the feature location rather that the center of the icon, featuresAt still only triggers based on the feature location, not where my marker icon is.

Maybe featuresAt needs an offset parameter so that it can trigger based on the offset icon?

PS. https://github.com/mapbox/mapbox-gl-js/issues/1274 isn't due to not icon-offset, so I don't think it's a duplicate.

EDIT: Possibly related to https://github.com/mapbox/mapbox-gl-js/issues/316

**Comment by jfirebaugh** [comment]
Yes, `icon-offset` (and `text-offset`, `line-offset`, etc) are specific cases that #316 will address. Let's track it there.
