### ISSUE TITLE
Add center and width css option(s)

### ISSUE THREAD

**Issue by majesticpdx** [mapbox/mapbox-gl-js#1926]
Hello, 

Would it be possible to add a center and width css options (i.e. top-center), specifically for the geocoder plugin?

Example: https://www.mapbox.com/bites/00121/

The example works well for longer strings and would add another great design option.

Thanks again.

**Comment by bhousel** [comment]
The geocoder plugin control now lives in its own repository.
Can you please check here: https://github.com/mapbox/mapbox-gl-geocoder

The bite linked to above is probably outdated, so you might find a better example of loading and customizing the geocoder control over on that repository.

**Comment by majesticpdx** [comment]
Thank you bhousel, I as thinking this would be a good starting point as the css appears to reside under the GL JS style sheet rather than the geocder style sheet. 

Thanks again.
