### ISSUE TITLE
drawing layer by layer

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#193]
This could open up interesting possibilities like rendering some layers from a child tile and some from a parent tile, and maybe even cross-fade the two. We could then render most features from a tile without waiting for text placement. Together with streaming downloads we could potentially start rendering layers before the entire tile is downloaded.

We could also do compositing operations on data from different sources. For example, a satellite layer that is desaturated everywhere except parks.

I hackishly implemented this way back, and it was slightly slower (40 vs 42fps or something).

**Comment by lucaswoj** [comment]
Sounds like this is getting unblocked as #682 gets ready to land in the next few weeks. I'm interested to see how much work it'll take to rebase this on `earcut-final` and get it working. Thoughts on priority @jfirebaugh @mourner @ansis?

**Comment by jfirebaugh** [comment]
This isn't actually blocked by earcut. See #1197 for current status. Closing here to avoid future confusion.

**Comment by mourner** [comment]
> This isn't actually blocked by earcut.

But with earcut in place, will we still need depth buffer support in headless-gl for tests?

**Comment by jfirebaugh** [comment]
@mourner Do you mean stencil buffer? We definitely need depth buffer for lots of things. And stencil buffer is also needed as long as some draw operations are clipped to tile bounds.

**Comment by mourner** [comment]
@jfirebaugh OK, so we're still blocked by https://github.com/stackgl/headless-gl/issues/26, right? Maybe it would be worth disabling render tests on JS for some time and merging layer-by-layer just to unblock (would running render tests locally work with headless-gl)?
