### ISSUE TITLE
Cannot load more than 3 maps even if on different tabs

### ISSUE THREAD

**Issue by mintuhouse** [mapbox/mapbox-gl-js#1935]
If I attempt to load more than 3 maps simultaneously (tested in Firefox on Ubuntu), even if not on same page, the tiles for latest one won't load. If I close the first tab, the map is loaded on 4th without refreshing. 
I sometimes get following warning in browser console. It may be related.
````
Exceeded 16 live WebGL contexts for this principal, losing the least recently used one.
`````
The number when tested in Chrome seems to be 8. 

I am using mapbox with turbolinks (rails), after 3 back and forth switches betweed pages, I no longer see the map.

Is there a way to manually disable webgl or hide it on unload?

**Comment by lucaswoj** [comment]
Closing in favor of #2656 which has more discussion & context.
