### ISSUE TITLE
Fix broken code on 3rd party example

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-gl-js#1937]
This example has bad code referring to Mapzen: 
https://www.mapbox.com/mapbox-gl-js/example/third-party/

![image](https://cloud.githubusercontent.com/assets/4587826/12365497/38cb1032-bba3-11e5-8d14-77bef430c98b.png)

**Comment by jfirebaugh** [comment]
cc @tristen -- looks like the same issue as https://github.com/mapbox/mapbox.js/issues/1105.

**Comment by tristen** [comment]
No idea why this is failing now. Anchor links in any of the descriptions need to have quotations wrapped around them. 

Will fix but if you see others [this is the fix](https://github.com/mapbox/mapbox-gl-js/commit/cff0f7239aebce277ae38b497a6e45c78089ca45)

**Comment by tristen** [comment]
Closed via https://github.com/mapbox/mapbox-gl-js/commit/d87e4de8963933d69ba5e8a4c7784232267ce4bf
