### ISSUE TITLE
Add a "jump to current location" control

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#1939]
the Navigation controls currently consist of the zoom-in/zoom-out buttons and a compass.  Are there plans to add a control that changes the map location to your current location ?

**Comment by lucaswoj** [comment]
I'm not aware of any plans to add this control yet. It sounds like something we should do! The [geolocation API](http://www.w3schools.com/html/html5_geolocation.asp) is supported on all of our target platforms. While it doesn't guarantee any particular accuracy, I've found it to be pretty good.
