### ISSUE TITLE
label double drawing when overscaling

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#194]
The plan to render cross-tile labels is to let tiles actually draw glyphs across boundaries. Collisions are prevented in preprocessing. Double drawing is prevented by only adding glyphs to the tile the anchor is located in. This gets complicated when you consider overscaling.

If placement is done right you won't have any collisions between parent and child tiles, but you could have double drawing.

```
 _________
|   P     |
|     ____|
|    |  C |
|____|____|
     ^
    this is a boundary while drawing, but the anchor might be in both
    in which case the glyph would be double-drawn.
```

I don't see how we can clip glyphs in the parent based on their anchor.

I'm seeing two options:
A. Clip the normal way with a depth or stencil buffer and include data for cross-tile labels in both tiles.
B. Let the parent tile draw all its labels, and have the child tile only draw labels that appear after the parent tile's max placement zoom.

I think B is better.

**Comment by mourner** [comment]
I've never seen label double drawing in practice, do you?

**Comment by ansis** [comment]
It does show up sometimes, but this isn't something that can be fixed separately from bigger changes.
