### ISSUE TITLE
Preventing accidental zoom in/zoom out

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#1940]
A map is shown on the left side of my website.  When a user scrolls down the website and moves over the map, instead of scrolling down the website, the map is zoomed in (or out). Can I prevent the map to listen to mouse scrolls ?

I know there 's an option "interactive" that you can set to false and pass to the Map instance, but this disables all mouse and keyboard listeners.  I just want to disable listening to the mouse scrolling.

maybe related to #1832

**Comment by lucaswoj** [comment]
It's not well documented (#1497) but you can disable zooming with the mouse wheel by calling

```js
map.scrollZoom.disable()
```

**Comment by lucaswoj** [comment]
Should we try to avoid responding to scroll events if the mouse pointer isn't over the map? My intuition is that's a little too "magic" to belong in mapbox-gl-js core.

**Comment by uhuru-be** [comment]
Thank you lucas ! 
Regarding your latest comment, I think this is indeed out of the scope of mapbox-gl-js core and could/would cause unwanted behaviour.
