### ISSUE TITLE
Added marker is not shown

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#1942]
I added a custom .svg image to the panel where the {maki} icons are shown, then tried to add markers to my map using the addSource and addLayer functions, with the "icon-image" property set to name of the .svg image.  However the markers are not shown on the map. What am I doing wrong ? Thanks for the help !

**Comment by averas** [comment]
Did you publish your map? Even with a saved style you have to publish your map in order for the markers to become available.

**Comment by uhuru-be** [comment]
Oops. I didn't publish the style again after uploading the image ! Problem solved. Thanks !
