### ISSUE TITLE
Cannot read property 'coordinates'

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#1943]
I tried to implement the marker popups (on click), exactly as shown in the example on the Mapbox website: 
https://www.mapbox.com/mapbox-gl-js/example/marker-popup/

When I click on the marker, the function map.featuresAt() is triggered and the features.length is 1 as expected. The following code is executed :

    var feature = features[0];

    new mapboxgl.Popup()
                .setLngLat(feature.geometry.coordinates)
                .setHTML(feature.properties.description)
                .addTo(map);

However the following error is thrown :  "Uncaught TypeError: Cannot read property 'coordinates' of null".  The property feature.geometry seems to be null .  The property features.properties is OK and I can access the description of the marker.  But I cannot access the coordinates of the marker.

I am a little bit stuck here. Any ideas ?

**Comment by tristen** [comment]
@uhuru-be it sounds like you might not have `includeGeometry: true` set as an option in [`featuresAt`](https://www.mapbox.com/mapbox-gl-js/api/#Map.featuresAt). By default, this is not included.

**Comment by uhuru-be** [comment]
Thank you tristen ! This solved my problem.

**Comment by unknownveer007** [comment]
can u give us this code
