### ISSUE TITLE
easeTo does not work properly if multiple values are changed

### ISSUE THREAD

**Issue by kennstenicht** [mapbox/mapbox-gl-js#1944]
I created a small jsfiddle to explain the issue. 
https://jsfiddle.net/rzgqmjj0/1/

If you press the "target" button in the upper left corner the camera flies to the correct position, but if you press the start button afterwards you don't return to the initial position. To get to the initial position, you have to click "start" a second time.

This error only occurs if more than one value (zoom, bearing or pitch) is changed at the same time.

**Comment by lucaswoj** [comment]
Bug confirmed. Sounds like a regression of #1744.

**Comment by lucaswoj** [comment]
Here's a slightly more :smiling_imp: test case: http://jsfiddle.net/rzgqmjj0/2/
