### ISSUE TITLE
'In' filter takes linear time, can be slow with lots of feature ids

### ISSUE THREAD

**Issue by Que3216** [mapbox/mapbox-gl-js#1945]
Hi,

We're creating a map which lets users style arbitrary sets of features (e.g. by dragging a box). It seems the easiest way to do this in mapbox is assign each feature an id, and use a feature id filter, using the 'in' operator: however this is quadratic in the number of features, and there could be quite a few features.

Would you accept a PR to allow the filter to be a function, instead of just a string (https://github.com/mapbox/mapbox-gl-js/blob/master/js/data/bucket.js#L63)? This would allow us to inject our own function, that quickly checks the feature id against a hash set.

Another alternative would be to modify feature filter's in operator to be more efficient (https://github.com/mapbox/feature-filter/blob/master/index.js).

Thanks!

Quentin

**Comment by mourner** [comment]
> Would you accept a PR to allow the filter to be a function, instead of just a string 

No, the style needs to be a valid serializable JSON.

> Another alternative would be to modify feature filter's in operator to be more efficient 

That would be great. Is performance poor even after https://github.com/mapbox/feature-filter/pull/7?

**Comment by mourner** [comment]
Closing here — let's make an issue or PR in the feature-filter repo.
