### ISSUE TITLE
Markers are dropped at certain zoomlevel

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#1949]
I am building a webpage that shows b&b's on a map.  The markers are loaded via a GeoJSON url.  All works well.  However I noticed that some markers are not shown at the default zoomlevel.  When I zoom in, more markers appear.  It seems that markers are "dropped" on the map when they are too close to each other ?  How can I prevent this behaviour so that all b&b markers are shown at zoomlevel 6.5 ?  I played with the "maxzoom" and "tolerance" properties of the GeoJSON data source, but did not succeed to show all markers.  Can someone help me out ? Thanks !!

**Comment by dbirks** [comment]
I had the same problem. Turns out that Mapbox was grouping pins that were close together. You can disable this by setting [icon-allow-overlap](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-icon-allow-overlap) to false.

**Comment by lucaswoj** [comment]
Thanks @dbirks! 

@uhuru-be, please reach out to help@mapbox.com if you're still having trouble.
