### ISSUE TITLE
Modifying GeoJSON source

### ISSUE THREAD

**Issue by Luixo** [mapbox/mapbox-gl-js#1954]
I'm building an app with a dynamic markers. My first attempt to update them was just removing layer & source and adding new ones, but the view was flickering on each update.
Then I found a setData method for source, but it throws with an error: "Uncaught DataCloneError: Failed to execute 'postMessage' on 'Worker': An object could not be cloned."
I made an example: https://jsfiddle.net/mr0pzv5c/

**Comment by lucaswoj** [comment]
```js
map.getSource('route').setData(source);
```

You're supposed to pass GeoJSON to `setData`, not an instance of `GeoJSONSource`.

**Comment by Luixo** [comment]
Thanks! Is there a way to add data instead of overwriting it?

**Comment by mcwhittemore** [comment]
@Luixo, not currently. [Maybe in the long term](https://github.com/mapbox/mapbox-gl-js/issues/1391). Until then we're working on try to make [adding faster](https://github.com/mapbox/mapbox-gl-js/issues/1504).

**Comment by shuoch** [comment]
I'm strangely getting the opposite issue, where setData is adding new points instead of the desired behavior of overwriting. Thus, I'm seeing all points after making multiples to `setData`. Any pointers?

**Comment by lokcon** [comment]
I just stumbled upon this but looks like an API token is pasted in the jsfiddle.

**Comment by Luixo** [comment]
> I just stumbled upon this but looks like an API token is pasted in the jsfiddle.

Thank you. The token in the fiddle is already invalidated.

**Comment by kirillegorov-dev** [comment]
> I'm strangely getting the opposite issue, where setData is adding new points on top of old points instead of the desired behavior of overwriting. Any pointers?

@shuoch can you reproduce such behaviour?
