### ISSUE TITLE
Refactor StyleLayer to prepare for data-driven styles

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#1957]
As a step towards data-driven styling #1626 we need a good way to share information about shader attributes between workers and the main thread. This should be done through `StyleLayer` subclasses. 

We should create a class per layer type (i.e. `LineStyleLayer`, `CircleStyleLayer`, `FillStyleLayer`, ...) like we did in mapbox-gl-native. In the long run, these classes should encapsulate all layer-specific operations, including drawing, bucket building, etc. For data-driven styling, these classes need to 

 - be easily instantiatable in workers 
 - be able to tell which shader attributes are enabled / disabled

**Comment by jfirebaugh** [comment]
:+1:, gl-native switched to a class hierarchy and it works well.

**Comment by lucaswoj** [comment]
# Goals

 - [ ] Instantiate `StyleLayer` subclasses in worker
 - [ ] Move shader stuff into `StyleLayer` subclasses
