### ISSUE TITLE
Add `zoomstart` / `zoom` / `zoomend` events

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#1958]
I want to bind a zoom handler to the navigation control, but did not find how to do this in the API or examples.

I tried the following, but this event was not called :
map.on('boxzoomend', function (e) {  //do something    });

PS.  I have disabled zooming in or out with the mouse scroll wheel

**Comment by uhuru-be** [comment]
I'm now using the "moveend" event to trigger execution of the code that I want to run after the user has zoomed in or out with the navigation control.  

map.on('moveend', function (e) { // do something });

The side effect is that the code is also triggered when the user drags the map.

I think  "zoomstart" and "zoomend" events (similar to "dragstart" and "dragend") would be desirable ?
When are the events "boxzoomstart", "boxzoomend" triggered ?

**Comment by bhousel** [comment]
> I think "zoomstart" and "zoomend" events (similar to "dragstart" and "dragend") would be desirable ?

Yes, I am planning to add these - I don't think it's ticketed yet, so I'll just use this issue for tracking it.

**Comment by barrylachapelle** [comment]
+1
