### ISSUE TITLE
Map style with circles freezes up when zooming

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#1966]
Test case: http://bl.ocks.org/peterqliu/7024d2e97c34125c64c8

Error: `Uncaught TypeError: Cannot read property 'circle' of undefined`

Refers to this line: `if (!tile.elementGroups[layer.ref || layer.id].circle) continue;`

cc @tmcw

**Comment by jfirebaugh** [comment]
#1933 -- upgrade to 0.12.4.
