### ISSUE TITLE
How to let the marker popups overflow the maps edges ?

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#1972]
How can I make the marker popups that are nearby the edges of the map, overflow these edges ? Now they are all clipped.  

I tried to accomplish this by setting the *overflow* property of css class `mapboxgl-poup` to *visibile* and by setting the *z-index* to 1, but this does not do the job.

Any ideas ?

**Comment by jfirebaugh** [comment]
I don't understand what you mean. Can you attach a screenshot or code example?

**Comment by uhuru-be** [comment]
Hi John. In attachment you'll find a screenshot.  In this screenshot I move over a marker at the top of the map.  The popup (with image and title) is shown on the map, but is clipped of at the upper edge of the map.  I marked it in red with a cross. 
![mapboxpopup](https://cloud.githubusercontent.com/assets/16693388/12520429/ce4805ba-c144-11e5-8fe4-7275437232de.png)

**Comment by lucaswoj** [comment]
This looks like a CSS problem with your website, not a `mapbox-gl-js` bug. Please see this source if you need more details on how the popup DOM element is created. https://github.com/mapbox/mapbox-gl-js/blob/skip-worker/js/ui/popup.js#L150-L152

**Comment by lucaswoj** [comment]
Also, feel free to contact help@mapbox.com if you need more help with this problem :smile:
