### ISSUE TITLE
showing more place names for a certain zoom level ?

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#1973]
I have a map that has a width of 400px and shows a region in France at zoom level 8. However no single place name is shown on the map, probably because there are no real big cities in this region, with the result that the map is not very informative/useful.

To give the visitors of the website a better overview and better orientation, I want to show more place names at zoom level 8.  How can I do this.  

Probably this more a Mapbox studio question than a Mapbox-gl-js one...

![dordogne](https://cloud.githubusercontent.com/assets/16693388/12507450/3256074a-c0f6-11e5-89ce-47889bcbab7d.png)

**Comment by lucaswoj** [comment]
> Probably this more a Mapbox studio question than a Mapbox-gl-js one...

That is correct, this is a data issue, not a mapbox-gl-js issue :smile: 

Some friendly pointers, though:

 - mapbox's postgis-vt-util includes a method called [`labelgrid`](https://github.com/mapbox/postgis-vt-util#labelgrid)
 - you might be able to use [`supercluster`](https://github.com/mapbox/supercluster) (now part of mapbox-gl-js core) to show more information
 - [tippecanoe](https://github.com/mapbox/tippecanoe) will help you create an efficient dataset containing a representative sample of all cities 

This is a hard problem!

**Comment by zanona** [comment]
Below it's a comparison from before (mapbox.js) and after (mapboxgl)
How can I replicate the same labels for places? After all, a map does need references :)
Nothing was required in order to show these labels previously.

Thanks

![mapbox](https://cloud.githubusercontent.com/assets/32017/25706683/7ace4b04-30b7-11e7-9909-3f7c4d700645.png)

**Comment by jfirebaugh** [comment]
Hi @zanoa -- that's a question best answered via Mapbox [help documentation](https://www.mapbox.com/help/) or [support](https://www.mapbox.com/contact/).

**Comment by andyiwest** [comment]
So there's no direct answer for this?
