### ISSUE TITLE
all user-initiated events should include originalEvent

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#1975]
In order to determine the source of a map event, we need to specify originalEvent on any event initiated by a user.

**Comment by bhousel** [comment]
I agree.  Some work already started on this in #1969 

I would need to add these to `touch_zoom_rotate` handler, and I'm also considering adding a param to the `jumpTo`/`easeTo` methods to be able to pass the original event info along to those methods which fire their own events.  Thoughts?

When you say "all"... I'm assuming you don't mean things like when user uses the zoom in/out or rotate controls.  We wouldn't want to propagate those click events, nor unproject and pass along the lng/lat underneath where the buttons happen to be.

**Comment by tmcw** [comment]
An alternative idea is to create a way for API-initiated events to _not_ fire events, or indicate their sourcing in the same way.

**Comment by bhousel** [comment]
@tmcw can you review e585f88 and see if that would help.  Going forward I'd like for all handlers to pass the original event source on to the camera methods.  Alternatively if you call camera methods directly, you could pass your own sourcing data in that parameter, then watch for it in the receiving code.
