### ISSUE TITLE
Are multiple styles allowed within a single geojson layer?

### ISSUE THREAD

**Issue by kylehotchkiss** [mapbox/mapbox-gl-js#1998]
I am trying to make a weather grid that looks like this animate.

![screen shot 2016-01-26 at 9 35 57 pm](https://cloud.githubusercontent.com/assets/108172/12602139/d12b40fc-c474-11e5-84b7-977c3f9eda74.png)

My data is coming via Geojson but the only way I could find to style the blocks was with this loop (below), that creates 20 separate layers. The process of removing and re-adding layers is a little slow so it doesn't animate well. 

Is it possible to have multiple Geojson styles within a single layer? Is there any way to pass those to the properties object in a feature? I think if it came down to animating one layer, animations would be a little more smooth.

```
        this.props.map.batch(batch => {
            for ( var i = 0; i < 20; i++ ) {
                var start = min + ( step * ( i + 1 ) );
                var layer = 'layer-' + i + '-' + this.state.step;

                batch.addLayer({
                    id: layer,
                    layout: {},
                    type: 'fill',
                    source: 'grid-' + this.state.step,
                    filter: [ "all", [ ">=", "temperature", start ], [ "<", "temperature", ( start + step ) ] ],
                    paint: {
                        'fill-opacity': .65,
                        'fill-antialias': false,
                        'fill-color': color( i ).hex()
                    }
                });

                layers.push( layer );
            }
        });
```

**Comment by jfirebaugh** [comment]
The loop technique that you are using is the best current solution. We're working on a better system -- search the issues for "data-driven styles" if you're curious to learn more.

**Comment by kylehotchkiss** [comment]
@jfirebaugh You rock! thanks for the response.

**Comment by SkylinR** [comment]
Hi, is there any better solution in 2017? :D
