### ISSUE TITLE
symbol Layers do not render after setStyle to satellite 

### ISSUE THREAD

**Issue by peckjon** [mapbox/mapbox-gl-js#1999]
I have a map with a current Source, a Layer of type "line", and a Layer of type "shape".

When I change backgrounds, I call map.setStyle(), then remove and re-add Sources and Layers

This works fine, except that when I use the Satellite style ("mapbox://styles/mapbox/satellite-v8"), the symbol Layer fails to add, erroring out with:

```
Uncaught TypeError: Cannot read property 'replace' of undefined
 glyphUrl @ glyph_source.js:128
 GlyphSource.loadRange @ glyph_source.js:102
 GlyphSource.getSimpleGlyphs @ glyph_source.js:76
 util.inherit.get glyphs @ style.js:509
 Actor.receive @ actor.js:34
```

**Comment by lucaswoj** [comment]
When you switch to the `satellite-v8` style, you're switching to a style that does not provide a [sprite](https://www.mapbox.com/mapbox-gl-style-spec/#root-sprite) and therefore has no icons available. 

I suggest cloning the `satellite-v8` style in Studio and adding your icons there.

**Comment by lucaswoj** [comment]
Ah, my mistake, it looks like you need to add fonts (perhaps in addition to sprites) to fix this error. 

I just opened an issue about adding standard icons and glyphs to the official Mapbox styles (like `satellite-v8`) https://github.com/mapbox/mapbox-gl-styles/issues/241 but can't promise that'll land any time soon.

**Comment by bhousel** [comment]
This seems related to (or dupe of):
[mapbox/mapbox-gl-js#1501](https://github.com/mapbox/mapbox-gl-js/issues/1501)
https://github.com/mapbox/mapbox-gl-style-spec/issues/299

**Comment by peckjon** [comment]
Thanks @lucaswoj !  If you have a second to provide a link or advice: I cloned streets-satellite in Studio, copied the link (mapbox://styles/empeng/cijx7upyd00no94kq4p29oe90), dropped it into my setStyle, and now get a 403 (I can see that the access token is attached as https://api.mapbox.com/styles/v1/empeng/cijx7upyd00no94kq4p29oe90?access_token=pk....)

Are the access tokens to styles in studio different from the primary one for my app?

I also tried simply downloading the JSON for that new style, but I get a 403 when using it (though for a different URL, apparently one of the sprites the style uses: api.mapbox.com/styles/v1/empeng/cijx7upyd00no94kq4p29oe90/sprite@2x.png?access_token=pk...)

**Comment by jfirebaugh** [comment]
Are you using an access token associated with the `empeng` account? Styles are private by default and not accessible by access tokens belonging to other accounts.

**Comment by peckjon** [comment]
Thanks, @jfirebaugh -- that appears to be the problem (I thought I had overridden it by adding ?access_token=... to the end of the mapbox:// style URL, but this does not recurse into external sprites used by that style)

Is there a way to share a clone between accounts?  Or to make one entirely public?

**Comment by peckjon** [comment]
PS is streets-satellite N/A for mapbox-gl-js?  I tried mapbox://styles/mapbox/streets-satellite-v8, but 404'd

**Comment by lucaswoj** [comment]
You can find documentation about available styles [here](https://github.com/mapbox/mapbox-gl-styles). It is called `satellite-hybrid-v8`.

**Comment by peckjon** [comment]
@lucaswoj That's the page I was missing!  Thanks!

Looks like that is linked from https://www.mapbox.com/developers/vector-tiles/ but not very obvious :-/

**Comment by jfirebaugh** [comment]
It's also here: https://www.mapbox.com/developers/api/styles/#styleids.
