### ISSUE TITLE
Refine release procedure

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2000]
We should spend a moment thinking about how / when we publish releases. It is important to me that we

 - give our users the latest and greatest features as soon as possible
 - follow semver as carefully as possible
 - only release stable code
 - don't release too often or too infrequently
 - remain flexible in deciding what to work on next
 - don't add unnecessary structure to our workflow

**Comment by lucaswoj** [comment]
Some ideas

 - find responsible ways to test a mapbox-gl-js canary build (i.e. whatever is in `master`) against real world usage so that we can identify bugs before they go into a release 
 - create a "release blocker" tag for issues
 - commit to doing a release whenever a non-trivial PR lands, unless a "release blocker" issue is present
 - fix "release blocker" issues as quickly as possible

**Comment by lucaswoj** [comment]
Thoughts @mourner @jfirebaugh @ansis @tmcw @bhousel? Anything here you're excited about or opposed to? Anything missing from this list?

**Comment by bhousel** [comment]
> automate the release process as much as possible (should be 1 bash command + changelog update)

I'm mildly :-1: on this.  Stuff frequently comes up in the merging between `master` and `mb_pages` steps.  But I do agree we should automate more of the "copy new version number everywhere" steps.

> require all examples are tested before publishing a release

I feel like we could automate this the same way we automate the render tests.  At least we could get a warning if any of the examples fail to render.


Also, not important but I'd like to
* move the release steps from README to a new RELEASE document.  
This stuff doesn't need to be on github or npm.

**Comment by mourner** [comment]
> publish a canary build (i.e. whatever is in master), preferably on our CDN (needs discussion)

What I'm doing for Leaflet: publish and access through S3, but not CDN (because it's cached forever, and I want the url to be the same), and don't publicize the url much so that people don't use it in production.

> publish release candidates for several days before committing to a final release

Not necessary I think because we have a fast release cycle, and doing rcs would be a chore. I'd reserve rc releases only for really huge releases, e.g. the one that will introduce data-driven styling.

> use npm-shrinkwrap

I'd prefer just pinning exact versions in package.json but not shrinkwrapping.

Agree with all the remaining points. I was the one who did the labeling revision last time, — let me know how you want to change it. I think we don't need to change the list much, the only problem is labeling issues regularly and consistently.

**Comment by lucaswoj** [comment]
> > automate the release process as much as possible (should be 1 bash command + changelog update)
> I'm mildly :-1: on this.  Stuff frequently comes up in the merging between `master` and `mb_pages` steps.  But I do agree we should automate more of the "copy new version number everywhere" steps.

Ok. I crossed out ~~(should be 1 bash command + changelog update)~~ above.

> > require all examples are tested before publishing a release
> I feel like we could automate this the same way we automate the render tests.  At least we could get a warning if any of the examples fail to render.

Render tests don't always capture movement-related or interaction-related bugs. This is a big ask for whoever is rolling the release but these have been breaking lately and we look really bad if our release contains a bug that breaks breaks our examples. We should spend an extra 30 minutes testing each release rather than continue to release broken code.

> move the release steps from README to a new RELEASE document. This stuff doesn't need to be in the main README that people see on github or npm.

I'm :+1: on this. Ticketed at https://github.com/mapbox/mapbox-gl-js/issues/2013

**Comment by lucaswoj** [comment]
> > publish a canary build (i.e. whatever is in master), preferably on our CDN (needs discussion)

> What I'm doing for Leaflet: publish and access through S3, but not CDN (because it's cached forever, and I want the url to be the same), and don't publicize the url much so that people don't use it in production.

Sounds great. We should do this. 

> > publish release candidates for several days before committing to a final release

> Not necessary I think because we have a fast release cycle, and doing rcs would be a chore. I'd reserve rc releases only for really huge releases, e.g. the one that will introduce data-driven styling.

I agree. A "canary" build would fill this role anyway. Updated list above.

> > use npm-shrinkwrap

> I'd prefer just pinning exact versions in package.json but not shrinkwrapping.

I agree. Updated list above.

> I was the one who did the labeling revision last time, — let me know how you want to change it. I think we don't need to change the list much, the only problem is labeling issues regularly and consistently.

The only things I had in mind were a "release blocker" label and any other structure that could help us decide when to do a release (i.e. milestones or a "release trigger" label). I'm open to discussion on this point.

**Comment by lucaswoj** [comment]
Closing this issue as every proposal has been rejected or separately ticketed out. 

If you would like to further discuss any proposals, please do so on their issue.
If you would like to submit a new proposal, please submit a new issue.

**Comment by danswick** [comment]
Thanks for leading out this discussion, @lucaswoj! Tagging @mapbox/support.
