### ISSUE TITLE
Random marker hiddens 

### ISSUE THREAD

**Issue by mjnf** [mapbox/mapbox-gl-js#2005]
Hi,

I'm having a problem with the custom markers. When I create two markers to closed, one of these is not showing. This happen in all zoom levels. I'm not sure what is the problem. If I move the other one, those two are showing without problems 

Thanks a lot !

**Comment by lucaswoj** [comment]
@mjnf Does setting [`icon-allow-overlap`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-icon-allow-overlap) to `true` help?

**Comment by mjnf** [comment]
@lucaswoj thank, sorry about that. I don't know that property. And what's the correct way to hide some icons on zoom out ? Could be a lot of icons with thas property.

Thanks.

**Comment by lucaswoj** [comment]
@mjnf You can use the new marker clustering feature (will be released later today) or [filters](https://www.mapbox.com/mapbox-gl-style-spec/#types-filter)
