### ISSUE TITLE
units for options passed to geojsonvt and supercluster

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2009]
The units for geojsonvt and supercluster options like `buffer`, `tolerance` and `clusterRadius` are based on the extent they use (currently 4096). The extent is an internal detail that isn't exposed anywhere. I think it would make more sense if the units were in pixels.

For example, `"buffer": 64` would become `"buffer": 8`.

Should this be handled entirely in mapbox-gl-js or partially in the libraries?

@mourner

**Comment by mourner** [comment]
@ansis this makes sense but should be done entirely in mapbox-gl-js, I think, because `geojson-vt` and `supercluster` don't know how the data maps to pixels in the end client — it's gl-js responsibility.

**Comment by ansis** [comment]
done in #2026
