### ISSUE TITLE
Add GeoJSON markers example is broken

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mapbox-gl-js#2011]
https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/

This example is currently not loading the GeoJSON markers, here's the error:

> Uncaught TypeError: Cannot read property 'type' of undefined mapbox-gl.js:92

**Comment by joedjc** [comment]
I had the same issue with my own map after upgrading - was there a breaking change?

**Comment by lucaswoj** [comment]
The "breaking" change is that it fails more loudly for invalid styles. I this case, we are setting [`text-size`](https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-text-size) as a paint property, though it is really a layout property. 

The best solution is #1632

**Comment by lucaswoj** [comment]
Fixed by 2385eb9

**Comment by lucaswoj** [comment]
@joedjc let me know if you have trouble finding where your style is invalid

**Comment by joedjc** [comment]
@lucaswoj Thanks, that makes sense. I got there through some trial and error. 

In doing so I discovered it seems like having any paint properties at all in a symbol layer causes this error (even if its empty). However in the style guide some of the properties are paint properties (e.g. icon-opacity, text-color). I tried putting them into layout but it created an error as well. Have the paint properties gone for symbol layers?

**Comment by lucaswoj** [comment]
@joedjc Paint properties still work for symbol layers. For example, the `streets-v8` basemap makes use of many symbol paint properties and renders correctly. Are you sure your stylesheet is valid otherwise?

**Comment by joedjc** [comment]
I think so...here is the code i'm using the add the layer(s) (I use some variables but it works fine in old versions). If I take out the paint section it works fine, but if I leave it in (even if its empty) it gives the error.

`
map.addLayer({
        "id": data.id,
        "type": "symbol",
        "source": data.id,
        "minzoom": data.minzoom,
		"interactive": data.interactive,
        "layout": {
            "icon-image": data.style["icon-image"],
		    "icon-size": data.style["icon-size"],
            "text-field": "{title}",
            "text-font": ["Open Sans Semibold", "Arial Unicode MS Bold"],
            "text-offset": [0, 0.6],
            "text-anchor": "top",
            "text-size": fontsize,
          "paint": {
		      	"icon-opacity": {"base": 1,"stops": [[7,1],[8,0]]},
		        "text-color": "#696969",
		        "text-halo-color": "#FFFFFF",
		        "text-halo-width":5
		      }
        }
    });
`

**Comment by lucaswoj** [comment]
@joedjc It looks like you're nesting your `paint` object _inside_ your `layout` object. They should both be peers on the overall layout object.

> it works fine in old versions

It didn't throw any errors, but it also didn't respect any of your paint properties!

**Comment by mcwhittemore** [comment]
@lucaswoj I just worked through this a bit for gl-draw (we were so off the spec :sob:). The error message I got was pretty confusing.

![image](https://cloud.githubusercontent.com/assets/1551510/12653419/73c6c34c-c5bd-11e5-9fec-ec13fc45d8ed.png)

Part of the difficulty is that it seems CDN must not have the right minmap for 0.13.1 as `type` isn't used on line 77 of draw_line.js.

It also might be good to report the layer and property that can't be found so the user knows where to look. I'll start a PR and see if this is an easy lift.

**Comment by joedjc** [comment]
@lucaswoj Ah, that was it - thanks! A more informative error message would definitely help.

**Comment by lucaswoj** [comment]
> I just worked through this a bit for gl-draw (we were so off the spec :sob:). The error message I got was pretty confusing.

Yeah. Take a look at my `skip-worker` branch. That has all the fixes.

> Part of the difficulty is that it seems CDN must not have the right minmap for 0.13.1 as type isn't used on line 77 of draw_line.js.

I think Chrome uses your local filesystem for the "minmap"

> It also might be good to report the layer and property that can't be found so the user knows where to look. I'll start a PR and see if this is an easy lift.

The right solution for error messages is #1632. If you're going to start a PR, can you look at that?
