### ISSUE TITLE
Labels become momentarily garbled when they change style while zooming

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2012]
![labelbarfwtf](https://cloud.githubusercontent.com/assets/281306/12653448/7325884c-c5a4-11e5-83e0-d4323c606577.gif)

Seems to have been introduced between v0.12.4 and v0.13.1

h/t @danswick

**Comment by mboeringa** [comment]
See my comment here https://github.com/mapbox/mapbox-gl-js/issues/3086#issuecomment-261713545

**Comment by mourner** [comment]
I've seen this sometimes happen recently when doing long `flyTo` animations too. Maybe we should revisit the issue.

**Comment by lucaswoj** [comment]
Me too @mourner. I cut a fresh ticket at #3669.
