### ISSUE TITLE
Publish canary builds to S3

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2014]
We should publish a canary build (i.e. whatever is in `master`) to S3 whenever something is merged into `master`.

> What I'm doing for Leaflet: publish and access through S3, but not CDN (because it's cached forever, and I want the url to be the same), and don't publicize the url much so that people don't use it in production. -- @mourner 

We should also try to come up with places we can get :eyes: on this canary build without putting it into production software. 

ref #2000

**Comment by jfirebaugh** [comment]
I'm mildly :-1: on this.

We used to do this. In practice, it was rarely used as a "canary", i.e. as a way to surface bugs and regressions early. Instead, the most common use was to gain early access to pre-release features. It was fairly common for production or semi-production applications to use `master` for this purpose and never update to a versioned URL even after there was a release with those features.

**Comment by lucaswoj** [comment]
>  Instead, the most common use was to gain early access to pre-release features. It was fairly common for production or semi-production applications to use the `master` URL for this purpose and never update to a versioned URL even after there was a release with those features.

Yes, talking to support, my impression is that this would be pretty common if we published a "canary" build. 

Perhaps the name `master.js` wasn't self-documenting enough. What if we called it `mapbox-gl-UNSTABLE.js`? 

I would love to have a couple users coming to us saying "Hey, I'm playing with `mapbox-gl-UNSTABLE.js` and noticed an error when..."

Thoughts @lyzidiamond @danswick?

**Comment by lucaswoj** [comment]
I don't have a strong opinion about this, so your experience carries a lot of weight, @jfirebaugh.

**Comment by danswick** [comment]
@lucaswoj @jfirebaugh just to add some context, I've been seeing two main issues around releases: 

1. A user has built something around an older version of Mapbox GL JS and now unpredictable things are happening. I'm not sure how avoidable this, but it might be helpful to find more ways to emphasize that Mapbox GL JS is under rapid development and that features will change. 
2. A user is wants to test out an upcoming feature to see if it will work for their project. A canary (or `UNSTABLE` or pre-release) would be welcome for these folks. A good middle ground might be to beef up our build instructions in Mapbox GL JS' `README`. Right now, it's not totally clear where in the [Developing](https://github.com/mapbox/mapbox-gl-js#developing-mapbox-gl-js) section you end up with a working build or how to find and test it.

**Comment by andrewharvey** [comment]
>A user has built something around an older version of Mapbox GL JS and now unpredictable things are happening. I'm not sure how avoidable this, but it might be helpful to find more ways to emphasize that Mapbox GL JS is under rapid development and that features will change. 

Several times now I've run into Mapbox GL JS bugs after spending time trying to nail down the issue, I discover that it has been fixed already. It would be nice if I could include a version like v0.x.x from https://api.tiles.mapbox.com/mapbox-gl-js/v0.x.x/mapbox-gl.js and hence automatically get all the goodies from each new release without constantly updating my source files with the new minor/patch release.

**Comment by mourner** [comment]
> Several times now I've run into Mapbox GL JS bugs after spending time trying to nail down the issue, I discover that it has been fixed already. It would be nice if I could include a version like v0.x.x from https://api.tiles.mapbox.com/mapbox-gl-js/v0.x.x/mapbox-gl.js and hence automatically get all the goodies from each new release without constantly updating my source files with the new minor/patch release.

No, that's a terribly bad practice. Things break all the time, even between minor versions, so you would be setting yourself up for trouble any time.
