### ISSUE TITLE
Automate version number updates during release

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2016]
We currently hand-edit several files to update the version number during a release. It isn't a big inconvenience but we should try to automate this step.

ref #2000

**Comment by jfirebaugh** [comment]
Ideally everything would flow from `package.json`.

* [ ] README.md: link to https://www.mapbox.com/mapbox-gl-js/ (needs to exist first), drop the "Include the source via HTML tags" part.
* [ ] _config.yml / _config.mb-pages.yml: write a simple jekyll plugin that reads from package.json?
* [ ] bench/fps/site.js: make this something that's served by `npm start` and `require('../package.json')`

**Comment by lucaswoj** [comment]
> - [ ]  bench/fps/site.js: make this something that's served by npm start and require('../package.json')

I recommend #2007 instead

**Comment by jfirebaugh** [comment]
If I understand it correctly, #2007 is for `/dist/mapbox-gl.js`. I'm :+1: on that, but there's another URL that's benchmarked: the versioned previous release on the CDN, e.g. `https://api.tiles.mapbox.com/mapbox-gl-js/v0.13.1/mapbox-gl.js`. What I meant was to construct this URL like so:

```
"https://api.tiles.mapbox.com/mapbox-gl-js/" + require('../package.json').version + "/mapbox-gl.js"
```

This assumes that we keep the last released version in `package.json` until we do a new release, which is the current convention.

**Comment by lucaswoj** [comment]
Ah! You're right. My mistake.

**Comment by lucaswoj** [comment]
We might also want to hit

* [ ] serve a dynamically built version of mapbox-gl-js to the locally running documentation server, like we do for the benchmarks

**Comment by lucaswoj** [comment]
There's been great progress here! The only "undesirable" version number left is in `README.md`. I can't see any way to automate that update that's easier than doing it by hand.
