### ISSUE TITLE
Automate creating GitHub release and publishing npm package on CI server

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#2017]
Ideal workflow:

* Do the git stuff and push a `vX.Y.Z` tag
* CI takes over:
  * Runs tests
  * Pushes to CDN
  * Pushes to npm
  * Creates a release on GitHub with content from CHANGELOG.md
    * Bonus: update prior releases where CHANGELOG.md has been edited

CI would need additional permissions:
* npm token with access to mapbox-gl-js
* GitHub token with access to mapbox-gl-js releases

**Comment by lucaswoj** [comment]
Publishing to npm on on the CI server is a good idea. That would eliminate a class of problems related to bad local environments causing bad npm package builds.

Automatically creating the GitHub release doesn't strike me as high priority. Parsing `CHANGELOG.md` might be tricky. Updating release notes is easy. 

Everything else on that list we already do :smile:

**Comment by lucaswoj** [comment]
Automating the GitHub release would make it feasible to attach build artifacts to the release, satisfying https://github.com/mapbox/mapbox-gl-js/issues/1342#issuecomment-180879039

**Comment by lucaswoj** [comment]
I'm going to break this out into some more atomic subtasks

**Comment by jfirebaugh** [comment]
https://docs.travis-ci.com/user/deployment/
