### ISSUE TITLE
Missing/inconsistent feature rendering when pitch is present (Android web)

### ISSUE THREAD

**Issue by laurenancona** [mapbox/mapbox-gl-js#2020]
<img src="https://cloud.githubusercontent.com/assets/2152151/12665438/c81991ca-c605-11e5-9df9-1c186eea5916.png" height="400" />

I've been doing some informal device testing preparing to launch a project. Yesterday, I encountered this on a friend's Android device. I didn't have a real debugging setup going on - for the moment I have this screenshot but I've emailed requesting more user agent details.

As near as I can tell, it's related to having a `pitch` value present. In this case the map loads at `pitch: 60` and levels `onClick`; that's what had happened directly prior to the image capture. Some mild efforts at refreshing/cache clearing caused more (and seemingly random) omission of features. 

I'll update with more details as possible. I've not seen anything like this on other devices, including Android phones when no `pitch` was assigned.

**Comment by laurenancona** [comment]
Device info:
Samsung Galaxy S6
Model # SM-G920V
Android version 5.1.1
Kernel version 3.10.61
Chrome version 47.0.2526.83

Studio style: mapbox://styles/laurenancona/cij3k82x800018wkmhwgg7tgt

**Comment by kristfal** [comment]
Can confirm this issue on the S5 as well.

Managed to fix it by forcing high-precision shaders, however some browsers/devices doesn't support highp shaders, so it shouldn't be considered a final solution.

Updating the following method in the gl-js source should make it render properly again:

```javascript

 context.getShader = function(name, type) {
        var kind = type === this.FRAGMENT_SHADER ? 'fragment' : 'vertex';
        if (!shaders[name] || !shaders[name][kind]) {
            throw new Error("Could not find shader " + name);
        }

        // User agent model for devices not supporting highp:
        //
        // GT-I9305

        var shader = this.createShader(type);
        var shaderSource = shaders[name][kind];

        // Increase precision for supported devices
        if(! /GT-I9305/i.test(navigator.userAgent) ) {
            shaderSource = shaderSource.replace(/ mediump /g,' highp ');
        }

        this.shaderSource(shader, shaderSource);
        this.compileShader(shader);
        if (!this.getShaderParameter(shader, this.COMPILE_STATUS)) {
            throw new Error(this.getShaderInfoLog(shader));
        }
        return shader;
    };

```


To the mapbox team: Any reason for not using highp whenever it is supported? Otherwise `getShaderPrecisionFormat` should provide sufficient feature detection. Keep in mind that it is not available in [all environments](https://github.com/Fyrd/caniuse/issues/1681), so a fallback should be considered.

**Comment by lucaswoj** [comment]
We avoid using `highp` when we can for performance reasons. If its omission is causing this bug, we will add it where it is needed :smile: 

I wonder if this branch is behaving incorrectly on some Android devices https://github.com/mapbox/mapbox-gl-js/blob/002c69071275997886fd98aa4dbc6025eed36a86/js/render/gl_util.js#L23-L26

Any thoughts @ansis?

**Comment by kristfal** [comment]
@lucaswoj yeh, that makes sense. And just heads up, some mobile devices, such as the Samsung Galaxy S3, doesn't support highp, so feature detection should probably be baked into the check.

**Comment by ansis** [comment]
@lucaswoj I'm not sure. I think I remember highp always being supported in the vertex shader, but not always in the fragment shader.

Does switching only the vertex shaders to highp and leaving fragment shaders as mediump fix the problem? https://github.com/mapbox/mapbox-gl-js/blob/002c69071275997886fd98aa4dbc6025eed36a86/shaders/line.vertex.glsl#L1

**Comment by kristfal** [comment]
@lucaswoj Did some digging, and the current master branch doesn't seem to set `highp` under any circumstances. PR with fix coming.

**Comment by ansis** [comment]
This should be fixed by https://github.com/mapbox/mapbox-gl-js/issues/2096
