### ISSUE TITLE
Cost of drawing overlapping polygons

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2021]
In #1879 I described a use case where I use polygons to render color relief. This actually works quite well and starts to look as beautiful as when made with mapnik.

However, in the previous issue I also mentioned that I noticed that using overlapping polygons seemed to be less performant than using non-overlapping polygons. Scaling this up a bit I experience considerable difference in drawing non-overlapping polygons vs. overlapping polygons, even when the underlying polygons don't show. Performance is far greater with the <code>earcut-final</code> branch, but still hampered with many overlapping polygons. With non-overlapping polygons performance is acceptable even with 100+ layers.

Ideally I would just go with non-overlapping polygons, but another problem struck me there - simplification. At certain zoom levels simplification creates slivers that affect UX badly:

![image](https://cloud.githubusercontent.com/assets/1205805/12673034/88e0fb54-c67a-11e5-8909-64a9f51ef596.png)

1) Is there any way to affect simplification when using vector tiles? (this is not a GeoJSON source)

2) Is it possible in theory to improve mapbox-gl-js with smarter layering logics? I experience most performance degradation at high zoom levels when many layers are in the viewport, but when few are actually visible (because of overlap) I.e. would it be possible to establish that the layer on top is actually covering the layers below and discard them? Perhaps this is what is actually happening and is what is expensive..

Another way to go would be to buffer my non-overlapping polygons a bit to avoid slivers caused by simplification, but that gives them faulty coverage which presents itself when not showing all layers.

**Comment by averas** [comment]
I realised the simplification was actually part of my own vtile pipeline :blush: .. perhaps there still are some insightful answers to my questions though.

**Comment by ansis** [comment]
Yeah, you're right, overlapping polygons are more expensive. More pixels to work with

>  I.e. would it be possible to establish that the layer on top is actually covering the layers below and discard them? 

We do do this on a pixel-by-pixel basis with the depth buffer for opaque polygon fills. It helps a bit, but there is still some cost. In master we're still using the stencil buffer heavily which gets slower the more pixels are covered by polygons.

`earcut-final` is a bit out of date and doesn't have the depth buffer pixel dropping. earcut + depth buffer dropping should be faster for overlapping polygons. But it will probably still be a bit slower than non-overlapping ones.

**Comment by averas** [comment]
Cool. Thanks. I will try to rebase <code>earcut-final</code> against master in my fork.

**Comment by jfirebaugh** [comment]
Another thing that will help this use case greatly is data-driven styles, which will allow you to go from 100+ layers to 1 layer.

**Comment by averas** [comment]
@jfirebaugh You bet. :-)
