### ISSUE TITLE
Add an option to set the number of spawned WebWorkers

### ISSUE THREAD

**Issue by altshul** [mapbox/mapbox-gl-js#2022]
I am working on the app where we need to be able to control / reduce the number of web workers that mapbox-gl uses. Looks like now it is always _navigator.hardwareConcurrency - 1_ ?  Is there a reason why the number of workers should not be exposed / overwritten via API?

**Comment by mourner** [comment]
I agree, we should expose it in API. It's also very convenient to profile if you switch it to 1.

**Comment by anandthakker** [comment]
Open to a PR on this?

**Comment by lucaswoj** [comment]
Yes! Very.

**Comment by anandthakker** [comment]
Hmm -- wonder if #899 might be a better (albeit more involved) place to address this?

**Comment by lucaswoj** [comment]
I can see this working in tandem with #899. Even if there's a global worker pool, one may want fewer than `navigator.hardwareConcurrency - 1` workers.

**Comment by anandthakker** [comment]
@lucaswoj fair point!
