### ISSUE TITLE
Upgrade to feature-filter 2.0

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#2024]
It comes with major improvements:

- major performance boost for big `in` filters (with thousands of items) — up to 100 times faster
- fixed error that prevented `in` filters go beyond 64k items
- 40% faster filter creation

**Comment by fnicollet** [comment]
Hello @mourner 

Should it speed up rendering significantly? I can't see any changes, apart from a few regressions that might not be related to this changes

Thanks,
Fabien

**Comment by mourner** [comment]
@fnicollet it doesn't affect rendering. It slightly reduces tile "loading" times (only noticeable if you use very complicated styles).

**Comment by mourner** [comment]
@fnicollet here's a cool example that benefits from the improved filter performance: https://www.mapbox.com/mapbox-gl-js/example/using-featuresin/

**Comment by fnicollet** [comment]
ok, thanks :)
