### ISSUE TITLE
workers + messaging tiles/models

### ISSUE THREAD

**Issue by jimmont** [mapbox/mapbox-gl-js#2031]
Would it make sense to use workers generally for all model operations, and make these workers more accessible, and does this overall reduce complexity and improve performance?

My guess is that having the worker manage/using transferable objects (#1504) would be key to making this efficient, at least from a ui-standpoint.

Several worker-related issues (#929 #1504 #899) overlap with a problem I'm tackling in cordova where tiles are provided by the filesystem (from the ui, for some reason the filesystem isn't available to workers) and am having to figure out passing the workers assets (via map.style.dispatcher). From this problem I started looking into how the tiles are loaded, workers and related messaging. Given the little I've read/understand of the source I'm not sure it makes sense but because it overlaps with open issues that are actively being solved I thought to ask.

**Comment by mourner** [comment]
> Would it make sense to use workers generally for all model operations, and make these workers more accessible, and does this overall reduce complexity and improve performance?

I don't understand what this would mean, can you provide a simple example?
