### ISSUE TITLE
Zoom Events is launching on map.flyTo.

### ISSUE THREAD

**Issue by mjnf** [mapbox/mapbox-gl-js#2041]
Hi,

I need watch the "zoom" event but it is launching all the time when map call to map.flyTo, and it is only panning not zooming. Are other best option to get the zoom events ?

Thanks a lot.

**Comment by bhousel** [comment]
I'm a bit confused by this.. `map.flyTo` default behavior is to zoom out and back in.   If you want to only pan and not zoom, why not use `map.panTo` or `map.easeTo`?

**Comment by lucaswoj** [comment]
I think @mjnf is trying to say that he isn't getting zoom events from `flyTo`

**Comment by mjnf** [comment]
Hi thanks for de answers,

Yes, I was using `map.flyTo` when I need to use `map.panTo`, I didn't know the real funtion of flyTo, I was watching a transición between 2 point to close and not see the "fly". 

Thanks
