### ISSUE TITLE
Map#load never fires fire if a style isn't passed to the constructor

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2042]
... even if a style is later set with `setStyle`

h/t @scothis

**Comment by scothis** [comment]
Possibly related. `map.loaded()` returns true while there is no style.

**Comment by jfirebaugh** [comment]
The fix here is that `map.loaded()` should be false if there's no style set, and `load` should be fired after the style is subsequently set and has been fully loaded.
