### ISSUE TITLE
Zoomend or Zoomstart doesn't activate callbacks. 

### ISSUE THREAD

**Issue by Wouter125** [mapbox/mapbox-gl-js#2045]
Hey,

I've been using the zoomend and zoomstart callbacks but they don't execute my functions. Only the zoom function / dragend / dragstart / drag functions do work. My function get's executed on these listeners. Any ideas what's up with the zoomend and zoomstart functions?

Also don't get a zoomend on the flyTo function, which I need.

Kind regards,

Wouter

**Comment by Wouter125** [comment]
Viewreset equals to moveend, I think. That works for me though.

**Comment by mourner** [comment]
What Mapbox GL JS version are you using?

**Comment by Wouter125** [comment]
v0.12.3

**Comment by mourner** [comment]
Those events were added in https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.13.0.
