### ISSUE TITLE
Duplicate clustering behavior

### ISSUE THREAD

**Issue by yuvadm** [mapbox/mapbox-gl-js#2048]
The new clustering option in 0.13.1 seems to be working, but even when specifying `'cluster': false` there still seems to be some rendering behavior that hides markers when zooming out. This is counter intuitive since there isn't any mentioning of more than one clustering behavior property.

The docs don't mention how or why this is happening, but I assume it's related to vector layer rendering, just like labels are rendered to ensure they do not overlap.

Where can I specify this behavior? What do I do if I want all markers in a marker layer to display on the map regardless of overlapping?

**Comment by yuvadm** [comment]
This seems to be solved by using `icon-allow-overlap: false`. I believe this is a very easy trap to fall into, and possibly should be mentioned in the docs somehow.

**Comment by mourner** [comment]
You mean `icon-allow-overlap: true`? Because it's false by default and does collision detection.

**Comment by yuvadm** [comment]
Yes, of course, `true`.

**Comment by tmcw** [comment]
This is a common question: I think it would be helpful to save this answer as a help or FAQ topic / cc @lyzidiamond

**Comment by lyzidiamond** [comment]
Thanks for the tag, @tmcw! Will ticket and add to docs.

**Comment by jfirebaugh** [comment]
See also https://github.com/mapbox/mapbox-gl-style-spec/issues/405
