### ISSUE TITLE
Strange street label and street border behavior on high zoom levels (z22)

### ISSUE THREAD

**Issue by manuelroth** [mapbox/mapbox-gl-js#2055]
**OS / Browser:** iOS 9.2.1 / Safari
**Steps to reproduce:** Visit the [Mapbox GL JS example map](https://www.mapbox.com/mapbox-gl-js/examples/) and zoom down to zoomlevel 21-22, look for a roundabout or street label.
**Notes:** This behavior only occurs on iOS devices, I couldn't reproduce it on desktops(chrome and safari) nor on android(chrome).
**Example:**
![rgkmfsigca](https://cloud.githubusercontent.com/assets/1810384/12815878/70527008-cb49-11e5-9efd-3192cd6e0443.gif)

**Comment by lucaswoj** [comment]
Looks like another place where we should be using `highp` values.

**Comment by ansis** [comment]
This should be fixed in master (with https://github.com/mapbox/mapbox-gl-js/issues/2096). Can you confirm?

**Comment by manuelroth** [comment]
@ansis Yes, I can confirm that this fixed the problem I described in this issue.
