### ISSUE TITLE
oneway arrows going in the wrong direction

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2062]
![screen shot 2016-02-04 at 1 16 48 pm](https://cloud.githubusercontent.com/assets/1421652/12829990/ca02542c-cb41-11e5-8196-29c511d876ad.png)

I think this is happening near tile edges.

http://localhost:9966/debug/#16.1/38.90339/-77.03731

https://github.com/mapbox/mapbox-gl-js/pull/1980 might fix this.

**Comment by lucaswoj** [comment]
looks like a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/1461

cc @1ec5

**Comment by ansis** [comment]
The screenshots in #1575 have wrong oneway arrows but the warping and tearing is a separate issue.
