### ISSUE TITLE
points produced by clipLine are not integers

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2067]
The `x` and `y` components of points created by `clipLine` are not integers. https://github.com/mapbox/mapbox-gl-js/blob/master/js/symbol/clip_line.js#L33

In -native they get truncated to integers: https://github.com/mapbox/mapbox-gl-native/blob/fa210516834feada45d69e218f9c1dce2d2ee6f6/src/mbgl/util/clip_lines.cpp#L24

in some other spots we round instead of truncating: https://github.com/mapbox/mapbox-gl-native/blob/fa210516834feada45d69e218f9c1dce2d2ee6f6/src/mbgl/text/get_anchors.cpp#L35

This should be consistent

Should we have separate float and integer point types in -js?
Should we truncate or round when converting from float to integer points?
Or should we just use floats for points in -native? 

@jfirebaugh what are the right answers?

**Comment by mourner** [comment]
I think there should be `round` everywhere.
