### ISSUE TITLE
Merge multiple vertex or elements buffers

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#207]
Currently, we create separate vertex/elements buffers when the vertex buffer reaches an item count of 65536. However, we could just continue in the same buffer and just reset the vertexAttribPointer to start indexing the buffer at a later position. That way, we'd have fewer buffer switches and fewer buffer transfer operations overall.

**Comment by jfirebaugh** [comment]
This is still relevant, and should be changed to match what native does.

**Comment by kkaefer** [comment]
Not sure how relevant this ticket is given that we use VBOs in most situations anyway.

**Comment by jfirebaugh** [comment]
I've implemented this and will have a PR pending #3439. Not needing to keep track of multiple array/buffer groups per bucket is a nice code simplification.

**Comment by kkaefer** [comment]
👍
