### ISSUE TITLE
icons wiggle during inertia panning

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2076]
Grab the map, drag it and release it with some momentum.

The icons will wiggle around.

two possible ways this could be fixed:
- use linear interpolation during inertia panning (or all panning)
- change inertia panning so that it only pans by whole pixels

**Comment by bhousel** [comment]
The icons get pretty wiggly when rotating the map too, even without inertia.

**Comment by lucaswoj** [comment]
This appears to be fixed now with linear interpolation.
