### ISSUE TITLE
Create system diagnostics utility

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#2078]
An API that prints out information like seen on http://webglreport.com/, so we can ask people to send it to us when they report that gl-js doesn't work or is slow.

**Comment by jfirebaugh** [comment]
Potentially useful: https://github.com/ashima/webgl-diagnostic

chrome://gpu/ has a bunch of useful information, but probably most of it is not script-accessible. We should make a habit of asking people to send it to us too.

**Comment by jfirebaugh** [comment]
Potentially also useful: https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html

**Comment by jfirebaugh** [comment]
https://www.khronos.org/webgl/wiki/BlacklistsAndWhitelists

**Comment by lucaswoj** [comment]
Though designed to solve a more specific problem, this page may be considered a prototype diagnostics utility for GL JS: 

 - https://github.com/mapbox/mapbox-gl-supported/blob/gh-pages/diagnostics.html
 - http://mapbox.github.io/mapbox-gl-supported/diagnostics.html

**Comment by mourner** [comment]
It's not clear what the next actions here are, and [this page](https://mapbox.github.io/mapbox-gl-supported/diagnostics.html) seems to fit well, so I think we can close.
