### ISSUE TITLE
Sprite attribute on global style has no effect

### ISSUE THREAD

**Issue by yuvadm** [mapbox/mapbox-gl-js#2081]
According to the current docs, it seems to be possible to do:

```js
new mapboxgl.Map({
  style: 'mapbox://styles/mapbox/light-v8',
  sprite: 'https://example.com/sprites',
  center: [11,22],
  zoom: 3,
  container: 'map'
})
```

However, the sprite attribute seems to have no effect, since the default sprites from the mapbox style are loaded (verified in network dev console).

If I'm not using a custom style I can edit, how is it possible to use custom sprites?

Either way, seems like another documentation bug, since this is very unclear.

**Comment by tmcw** [comment]
@yuvadm can you point out the specific documentation that suggests that this is possible? The [current API documentation](https://www.mapbox.com/mapbox-gl-js/api/) does not mention sprite as a configuration option for the Map object.

**Comment by yuvadm** [comment]
@tmcw You're correct. After reading some tickets reagrding sprites and custom markers, I was under the impression this was somehow possible, but indeed the Map object API is clear on this.
