### ISSUE TITLE
Performances with MapboxGL in fullpage (Desktop web)

### ISSUE THREAD

**Issue by Zlitus** [mapbox/mapbox-gl-js#2083]
We have some performance issues with MapboxGL (zoom, moving with mouse, etc.) when the map is on full page.

Please see here our very simple code (Directly copied from the documentation of MapboxGL): http://commodor.fr/mapbox.html
The performance is very poor on mac (Safari & Chrome), please see a a screencast here (The first map is with MapboxGL and the second one is with Mapbox.js): https://youtu.be/Zk7y_AChUL0
Can you please help us to resolve this issue.

**Comment by averas** [comment]
I honestly don't believe believe this is a bug/issue per se, but as good as it gets performance wise at this point. IMHO Mapbox GL JS is not quite ready to be used in full screen mode on hi-res desktops, especially not with custom layers rendered on top of the basic styles.

If you're willing to live on the edge you can try out the <code>earcut-final</code> branch. It deals with rendering of polygon fills differently than <code>master</code> and performs way better if you have many fills (which streets has). Hopefully this branch will make it to master eventually - #1606 ..

If you're using GeoJSON polygons with this branch you will have to mind the winding order of your rings, which is not something most GeoJSON producing libraries do natively.

**Comment by jfirebaugh** [comment]
It's hard to gauge FPS from a screen recording, but this seems much lower than I would expect for the basic example.

@Zlitus -- Do you see this on a single computer, or multiple computers? What's the screen resolution? Can you post the output of chrome://gpu/ and http://webglreport.com/? Can you make a screen recording with "Show FPS meter" enabled in developer tools:

![image](https://cloud.githubusercontent.com/assets/98601/12892208/e3c15ace-ce3f-11e5-8df9-b2f39cd8668b.png)

Any or all of those will help us narrow down the issue. Thanks!

**Comment by nbolten** [comment]
I can confirm performance issues on desktop here. It's not being fullscreen that causes the FPS drop, just a high resolution - e.g. the following examples are both windowed and less than 1600x900 resolution (my fullscreen resolution).

I didn't make a screen recording, but the following screenshots were taken at zoom level 14 after doing some moderate-speed panning.

Using mapbox-gl-js 0.14.3:
![without_earcut](https://cloud.githubusercontent.com/assets/1947393/13896877/ea471818-ed5a-11e5-8c3f-465fb2b698ec.png)

Using the earcut-final branch (commit 9369d51):
![with_earcut](https://cloud.githubusercontent.com/assets/1947393/13896881/14589f50-ed5b-11e5-9a9b-670ea7ca279f.png)

The output of chrome://gpu with my default settings: 
![gpu_normal](https://cloud.githubusercontent.com/assets/1947393/13896886/3e726dac-ed5b-11e5-9d9d-361af0571886.png)

If I force-enable 'Override software rendering list' and 'GPU rasterization', all of the features in chrome://gpu are enabled, but the FPS remains about the same in both the released version and the earcut-final branch of mapbox-gl-js. webglreport.com says my browser supports WebGL 1, but not 2.

The slow-down in panning in the 0.14.3 example is very noticeable on my system (on ending the drag, it's still catching up and animates in a 'jumpy' fashion), while the earcut-final branch is smooth and not distracting.

**Comment by lucaswoj** [comment]
> while the earcut-final branch is smooth and not distracting.

Earcut has merged now! 🎉

**Comment by Zlitus** [comment]
Really better on Chrome yes, but I have still the same issue on Safari (Version 9.1.1 11601.6.17) and also on the last nightly of Webkit (r201371); mapbox-gl-js/v0.18.0.

Tested on:
OS X 10.11 El Capitan, Macbook Pro Retina mid-2014 3 GHz Intel Core i7 / Intel Iris 1536 Mo.

URL of test:
http://commodor.fr/mapbox.html

**Comment by mourner** [comment]
@Zlitus can you test the master (unreleased) version too?

**Comment by Zlitus** [comment]
@mourner Yes sure, where I can find the master (unreleased) version? I don’t see a branch or a tag named like that :-( .

**Comment by mourner** [comment]
@Zlitus the improvements have been released now, try 0.19.1.

**Comment by Zlitus** [comment]
Thanx, the version 0.19.1 is really great on Safari and Chrome (Mac/Trackpad), but don’t work at all in Microsoft Edge and Internet Explorer 11 (You can re-try my link updated: http://commodor.fr/mapbox.html ).
Also, on some Windows computers with Chrome, I have bad performances (Maybe linked to a problem with old graphic card, but I need to investigate).

**Comment by mourner** [comment]
@Zlitus yes, the IE11 issue is known and already fixed in the master branch, to be released shortly. With an old graphics card, bad performance is to be expected, especially for full-screen maps.
