### ISSUE TITLE
Garbled labels on streets when passing zoom level 7-8

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2084]
Am I the only one seeing this on streets? Didn't find any other issue describing it ... The effect becomes more and more evident as rendering becomes slower (i.e. larger canvas).

(Tested in OSX on Chrome, Safari and Firefox)

![garbled-labels](https://cloud.githubusercontent.com/assets/1205805/12888726/b0274016-ce7b-11e5-81ce-5ab0df6b6b55.gif)

**Comment by bhousel** [comment]
This was reported in #2012 and is fixed already..
