### ISSUE TITLE
Fix debug/collision render test

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2087]
![screen shot 2016-02-08 at 12 59 11 pm](https://cloud.githubusercontent.com/assets/1421652/12898904/dd0a7b92-ce63-11e5-9a30-e674e946e004.png)

It fails on ci but not locally.

**Comment by mourner** [comment]
No longer fails on CI.

**Comment by jfirebaugh** [comment]
We should remove the ignore from the test suite if this is now expected to pass.

**Comment by mourner** [comment]
@jfirebaugh already did https://github.com/mapbox/mapbox-gl-test-suite/commit/6267dbff51429bf382dccf54101ed49defd559b1

**Comment by jfirebaugh** [comment]
🙇
