### ISSUE TITLE
Fix winding order for GeoJSON polygons before rendering

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-js#2089]
![](https://cloud.githubusercontent.com/assets/32314/11752959/7e5bbc40-a010-11e5-8292-740391704ad5.gif)

In [mapbox-gl-draw](https://github.com/mapbox/mapbox-gl-draw/issues/128) we're seeing a problem where holes are rendered in polygons when we don't expect them to be. At first I thought that this was due to poor winding order management in gl-draw (which is true) but after talking to @sgillies about this a bit today I'm pretty sure mapbox-gl-js is implementing geojson holes incorrectly.

In the above image each new polygon is a its own feature. [According to the spec](https://github.com/geojson/draft-geojson/blob/master/middle.mkd#polygon) holes happen when a second linear ring is provided to the array of linear ring coordinate arrays.

I'm guessing I can fix this in gl-draw by following the `a linear ring SHOULD follow right-hand rule` command, but still this should be fixed so end users don't get caught up in trying to check if their linear rights follow the right hand rule.

**Comment by jfirebaugh** [comment]
@mcwhittemore Can you post the GeoJSON that produces the depicted rendering?

cc @mourner

**Comment by averas** [comment]
I've noticed this too. Interestingly, it does not happen with <code>earcut-final</code> if that could give any pointers..

**Comment by mcwhittemore** [comment]
@jfirebaugh here you go - https://gist.github.com/mcwhittemore/a4ee8d9559369d478729

**Comment by ansis** [comment]
We need to enforce winding order for geojson polygons internally. https://github.com/mapbox/geojson-rewind does this
