### ISSUE TITLE
fitBounds/flyTo after resizing map container

### ISSUE THREAD

**Issue by danielduhh** [mapbox/mapbox-gl-js#2090]
map.fitBounds or map.flyTo does not response to a change in the map containers' size unless the browser window is budged.

Is there a workaround to this? 

example: https://jsfiddle.net/mb428g9g/1/

**Comment by jfirebaugh** [comment]
If you change the container's size, you need to call [`map.resize()`](https://www.mapbox.com/mapbox-gl-js/api/#Map.resize) to notify the map of that fact.
