### ISSUE TITLE
Improve shader attribute precision on mobile devices

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2096]
There are two outstanding bugs related to poorly calibrated shader attribute precision on mobile devices (#2055, #2060 and #2020)

@kristfal kindly provided a PR (https://github.com/mapbox/mapbox-gl-js/pull/2091) with one potential solution to the problem. 

We should all take a step back and come up with our ideal blue-sky solution to the problem. Should we

 - keep adding `highp` annotations to the shader source when bugs are reported 
 - design a "smarter" (than [this](https://github.com/mapbox/mapbox-gl-js/blob/master/js/render/gl_util.js#L23-L26)) shader attribute precision rewriting algorithm
 - other?

cc @kristfal @ansis @kkaefer @jfirebaugh

**Comment by jfirebaugh** [comment]
Previously: #1852, #750.

I think we should use `highp` universally and unconditionally in vertex shaders. There appears to be little or no downside to doing so.

For fragment shaders, [it's more complicated](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices). Do we know of any cases where our fragment shaders produce incorrect results on mobile with `mediump`?

**Comment by ansis** [comment]
> I think we should use highp universally and unconditionally in vertex shaders. There appears to be little or no downside to doing so.

> For fragment shaders, it's more complicated. Do we know of any cases where our fragment shaders produce incorrect results on mobile with mediump?

This sounds right to me. I don't think there are any cases we need high precision in fragment shaders.

**Comment by lucaswoj** [comment]
Naively switching most shader attributes to `highp` has led to many rendering errors on desktop devices, even though they claim `highp` support

```js
        var isHighpSupported = (
            context.getShaderPrecisionFormat &&
            context.getShaderPrecisionFormat(type, context.HIGH_FLOAT).precision > 0
        );
```

Do we want to continue restricting `highp` use to mobile devices?

**Comment by jfirebaugh** [comment]
> Naively switching most shader attributes to highp has led to many rendering errors on desktop devices

Can you elaborate on this?

**Comment by lucaswoj** [comment]
In my prototype branch, #2117, circles and lines fail to render in the browser and in headless testing. I'm not yet sure what the underlying cause is.

**Comment by ansis** [comment]
done https://github.com/mapbox/mapbox-gl-js/issues/2096
