### ISSUE TITLE
Zoom box transition broken in 0.14

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#2097]
Hello,

I just tried the 0.14 examples and noticed that the zoom box is broken. I can reproduce the issue on this page in Chrome:
https://www.mapbox.com/mapbox-gl-js/examples/
Shift+box and the zoom is off. It seems like zooming first to the top-left corner of the box and then at the last second, correcting the zoom, which gives a strange effect

Fabien

**Comment by ansis** [comment]
Is this the same issue as https://github.com/mapbox/mapbox-gl-js/issues/2070 ?

**Comment by fnicollet** [comment]
ah yes, sorry, didn't notice that issue

On Tue, Feb 9, 2016 at 10:36 PM, Ansis Brammanis <notifications@github.com>
wrote:

> Is this the same issue as #2070
> <https://github.com/mapbox/mapbox-gl-js/issues/2070> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapbox/mapbox-gl-js/issues/2097#issuecomment-182086039>
> .
>



-- 
Fabien Nicollet
Tel : +33 (0)6 60 54 72 20

**Comment by ansis** [comment]
no problem
