### ISSUE TITLE
Rendering broken in IE in master at low zoom levels

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#2098]
Hello,

Just tried master and noticed some bugs in IE. When you don't zoom too much, it seems all good:
![image](https://cloud.githubusercontent.com/assets/1240481/12931605/ecd0b2b4-cf7e-11e5-8d55-af2d99440b42.png)
But then, the rendering is messed up:
![image](https://cloud.githubusercontent.com/assets/1240481/12931628/040e0f44-cf7f-11e5-991b-01b07c7f73ec.png)
There is also some kind of dashed line across the screen sometimes:
![image](https://cloud.githubusercontent.com/assets/1240481/12931658/220f226c-cf7f-11e5-8a16-021a498d62c0.png)
The issue happens with all JSON styles

Fabien

**Comment by lucaswoj** [comment]
This might be related to #2095. Can you tell me if this bug still occurs using the `collision-2092` branch?

**Comment by fnicollet** [comment]
Hello Lucas,
Unfortunately, mapbox-gl-js is somehow broken on Windows (now also getting
errors in the debug page), so it only works with my fork, and I cannot
switch to your branch
I subscribed to your other issue, so when it will be merged into master, I
will be able to update and test it out

Fabien

On Tue, Feb 9, 2016 at 10:56 PM, Lucas Wojciechowski <
notifications@github.com> wrote:

> This might be related to #2095
> <https://github.com/mapbox/mapbox-gl-js/pull/2095>. Can you tell me if
> this bug still occurs using the collision-2092 branch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mapbox/mapbox-gl-js/issues/2098#issuecomment-182094725>
> .
>



-- 
Fabien Nicollet
Tel : +33 (0)6 60 54 72 20

**Comment by lucaswoj** [comment]
@fnicollet Unfortunately I can't help you debug your fork of mapbox-gl-js. We should figure out what it'd take to upstream your changes. I'm going to assume this was fixed by #2092 (which has now been merged into master). Please re-open if not.

**Comment by fnicollet** [comment]
Thanks, just updated my fork to master and it works a little better. The big zoom works now, but I get artifacts on lower zoom levels. 
Before:
![image](https://cloud.githubusercontent.com/assets/1240481/12934649/6b43befa-cf90-11e5-984a-791b720d8d49.png)
After:
![image](https://cloud.githubusercontent.com/assets/1240481/12934669/a351023a-cf90-11e5-884b-a975b976526b.png)
Anyway, i'll try updating to master in a few weeks, see if some changes might alter this

Fabien
