### ISSUE TITLE
Land disappears in v0.14.0

### ISSUE THREAD

**Issue by dbirks** [mapbox/mapbox-gl-js#2102]
I was testing out upgrading from v0.13.1 to v0.14.0 on a project I've been working on, and everything that would be land is replaced by water. I also noticed the same behavior on the [Filter markers](https://www.mapbox.com/mapbox-gl-js/example/filter-markers/) example:

<img width="561" alt="capture" src="https://cloud.githubusercontent.com/assets/7545665/12959703/9b3b5602-d005-11e5-9e4d-8e033b4e5470.PNG">

**Comment by averas** [comment]
Dupe #2092

**Comment by dbirks** [comment]
Sorry, didn't see that. Glad to see it's fixed.

**Comment by lucaswoj** [comment]
@dbirks the fix was just released in v0.14.1

**Comment by dbirks** [comment]
Awesome, that was quick. Just upgraded. Thanks @lucaswoj!
