### ISSUE TITLE
Map#getStyle() gets confused about classes

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2107]
If I have a layer with a class, such as "paint.night", <code>Map#getStyle()</code> will return a layer with a property called "paint.paint" instead of "paint.night".

Demo: http://codepen.io/anon/pen/JGwerB

**Comment by averas** [comment]
I think the problem is here: https://github.com/mapbox/mapbox-gl-js/blob/00ac67358d2aab6da778c768a1d305aed9bbcd41/js/style/style_layer.js#L228

<code> var key = klass === '' ? 'paint' : 'paint.' + key; </code>
should be
<code> var key = klass === '' ? 'paint' : 'paint.' + klass; </code>

**Comment by lucaswoj** [comment]
Your analysis looks spot on here @averas. PR ready.

**Comment by averas** [comment]
:+1:
