### ISSUE TITLE
Removing a class with fill-opacity set on a layer class leads to "Cannot read property '3' of null"

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2111]
If I have a style, with a fill layer where opacity is set on a class but not on the regular paint property, removing the class causes mapbox-gl-js to freeze with "Cannot read property '3' of null" on the console.

Demo: http://codepen.io/anon/pen/RrEdVd

1) Add the class (night) by clicking on button
2) Remove the class

**Comment by lucaswoj** [comment]
This looks like the same fault as #2105. I just confirmed that the codepen works correctly using `master`.

**Comment by averas** [comment]
You're absolutely right. Should have tested against master.. I'm still lingering on <code>earcut-final</code> so I mostly rebase against the release tags. :-)

**Comment by lucaswoj** [comment]
@averas I'll keep digging on the rendering problems in `earcut-final` today.
