### ISSUE TITLE
Where do I get the source-layer value from?

### ISSUE THREAD

**Issue by divya1c** [mapbox/mapbox-gl-js#2116]
Hi! 

I am new to mapbox gl and am trying to display vector tiles from my own tile server using mapbox gl. I see that there is a source-layer attribute that I have to specify for a layer of vector tiles. 

I am confused where I can get this value from.

Thanks!

**Comment by jfirebaugh** [comment]
The value of `source-layer` must be the name of a [layer](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#41-layers) from the vector tiles containing the data you wish to display.

For Mapbox vector tile sources, we document the names and contents of layers [here](https://www.mapbox.com/developers/vector-tiles/mapbox-streets-v6/). If you are generating your own vector tiles, you'll be choosing layer names somewhere in your generation code.
