### ISSUE TITLE
Get rid of the mapboxgl.Control class

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2118]
We shouldn't require 3rd party plugins to `require('mapbox-gl').Control` in their module. All the code in this class could be easily moved elsewhere (i.e. `map#addControl` and `map#removeControl` methods). 

ref https://github.com/mapbox/mapbox-gl-draw/issues/235

**Comment by jfirebaugh** [comment]
Would we deprecate/remove existing methods like `Popup#addTo`? Or not try to enforce `Control#addTo`/`Control#remove` as a standard API for controls?

cc @mourner

**Comment by lucaswoj** [comment]
We could deprecate the class and alias

 - `Control#addTo` to `Map#addControl`
 - `Control#remove` to `Map#removeControl`

**Comment by mcwhittemore** [comment]
For the short term gl-draw has copied the Control class into its code base and removed the direct dependency.

https://github.com/mapbox/mapbox-gl-draw/pull/244

**Comment by lucaswoj** [comment]
Done in https://github.com/mapbox/mapbox-gl-js/pull/3497
