### ISSUE TITLE
better error messages

### ISSUE THREAD

**Issue by gertcuykens** [mapbox/mapbox-gl-js#2122]
For example when you have a bad geojson

```json
{
    "type": "FeatureCollection",
    "features2": [
        {
            "type": "Feature",
            "properties": {
```
you get 

`map.js:840 TypeError: Cannot read property 'length' of undefined`

If you mess up a layer

```json
map.addLayer({
                        "id": "waypoints",
                        "type": "symbol",
                        "source": "waypoints",
                        "layout": {
                            "icon-image": "bar-15",
                            "icon-offset": [0,-8],
                            "text-field": "waypoint",
                            "text-font": ["Open Sans Semibold", "Arial Unicode MS Bold"],
                            "text-offset": [0,0],
                            "text-anchor": "top",
                        },
                        "paint": {
                            "text-size": 8,
                            "text-color": "white",
                            "text-halo-color": "black",
                            "text-halo-width": 1
                        },
                        "interactive": true
                    })
```

you get 

`style_declaration.js:9 Uncaught TypeError: Cannot read property 'type' of undefined`

Goodluck finding it :)

**Comment by tristen** [comment]
Yep - there should be better error handling here. Closing in favor of https://github.com/mapbox/mapbox-gl-js/issues/1632

**Comment by lucaswoj** [comment]
@gertcuykens validation of style API inputs landed in `master` last week and should go out in a release shortly. Until then, please read the [style spec](https://www.mapbox.com/mapbox-gl-style-spec/) carefully and use the style spec validator to debug your styles.

**Comment by Samuelfaure** [comment]
Sorry to comment two years later, but on recent mapbox-gl release I still get `TypeError: Cannot read property 'length' of undefined` for bad geoJSON input. Is this normal ?
