### ISSUE TITLE
Cannot read property 'loaded' of undefineddrawSymbol on satellite-v8

### ISSUE THREAD

**Issue by gertcuykens** [mapbox/mapbox-gl-js#2124]
`mapbox://styles/robertl/ciimcfg1400112lkn9vbllyrr` works (is just a satellite background)

`mapbox://styles/mapbox/satellite-v8` gives me a black screen and
```
draw_symbol.js:106 Uncaught TypeError: Cannot read property 'loaded' of undefineddrawSymbol @ draw_symbol.js:106drawSymbols @ draw_symbol.js:46Painter.renderLayer @ painter.js:319Painter.renderPass @ painter.js:300Painter.render @ painter.js:266util.extend._render @ map.js:783
```

**Comment by jfirebaugh** [comment]
What version of mapbox-gl-js? Can you please provide a JSFiddle that demonstrates the problem?

**Comment by gertcuykens** [comment]
v0.14.1 
`map.setStyle('mapbox://styles/robertl/ciimcfg1400112lkn9vbllyrr);` <= works perfect
`map.setStyle('mapbox://styles/mapbox/satellite-v8');` <= error

Going to prepare a demo hold on :)

**Comment by gertcuykens** [comment]
And of course the simple demo works as always grrr....

http://jsbin.com/hezexi/edit?html,output

Wait going to make a more complex demo with workers

**Comment by gertcuykens** [comment]
I give up, here is the complete complex version lol

Push on this button to see the error

![image](https://cloud.githubusercontent.com/assets/863731/13062871/62919758-d442-11e5-9b5b-99995b0da0d1.png)

http://gps.nyimbo.nl

PS don't quote the url please so I can remove it later :)

PS2 Going to be a separate ticket but when you are at it also note that you can still click on the cluster bubbles what should not be the case, because you are clicking something you can't see

**Comment by jfirebaugh** [comment]
Looks like you're using icons but your style doesn't have a `"sprite"` property.

@lucaswoj Can we bump https://github.com/mapbox/mapbox-gl-style-spec/issues/299 in priority?

**Comment by gertcuykens** [comment]
I am just using `mapbox://styles/mapbox/satellite-v8` and the weird part is this works `mapbox://styles/robertl/ciimcfg1400112lkn9vbllyrr` which for me is the same?

**Comment by gertcuykens** [comment]
Aaa ok now I get it about the sprite thing, PS what about the bubbles and the onclick event that should not get fired? Can you reproduce it in my example, I will create a separate ticket for it if you understand what I am talking about :)

**Comment by gertcuykens** [comment]
PS3 Can you also see this line artifact :) if so that going to be ticket number 3 haha

![image](https://cloud.githubusercontent.com/assets/863731/13063518/2a6e095e-d449-11e5-87c6-509d938c10a7.png)

**Comment by gertcuykens** [comment]
PS4 Anti Cluster collision would also be nice with icons?

![image](https://cloud.githubusercontent.com/assets/863731/13063717/0ffcd22e-d44b-11e5-9634-59a9e8faf11e.png)

**Comment by gertcuykens** [comment]
I replaced my code with this and now i don't get a error message whohoo, but I don't see tiles? (see link above)

```
var style = {
            "version": 8,
            "sprite": "mapbox://sprites/mapbox/bright-v8",
            "glyphs": "mapbox://fonts/mapbox/{fontstack}/{range}.pbf",
            "sources": {
                "mapbox-satellite": {
                    "type": "raster",
                    "url": "mapbox://mapbox.satellite",
                    "tileSize": 256
                }
            },
            "layers": [{
                "id": "new-layer",
                "type": "background",
                "paint": {"background-color": "#111"},
                "interactive": true
            }],
        }
```

**Comment by lucaswoj** [comment]
It looks like you have some questions that are better suited for our support team. GitHub issues are for bugs and feature requests only. Please head to https://mapbox.com/contact and fill out a ticket there.

**Comment by gertcuykens** [comment]
ok but the click handler on cluster bubbles is a bug right? Then I will make a new one for that and ask the style thing above on contact.

PS Can support use stackoverflow instead or slack.com ? 

A email form is sooo 90's lol

**Comment by gertcuykens** [comment]
No response from contact yet, anyway asked on stackoverflow for people that are also stuck creating a custom satellite source http://stackoverflow.com/questions/35461646/satellite-tile-source-not-working
