### ISSUE TITLE
Retina sprites not being scaled

### ISSUE THREAD

**Issue by Tam** [mapbox/mapbox-gl-js#2126]
I've got some custom sprites exported via the [spritezero-cli](https://github.com/mapbox/spritezero-cli) @ 2x. They are loading in fine, but don't seem to be being scaled down to the correct size.

![mapbox_sprite_scale_issue](https://cloud.githubusercontent.com/assets/977594/13053530/e37f6fac-d3fc-11e5-8267-5e3fea2dd5fa.gif)

The gif above shows that the hitbox appears to be the correct size, but the image is not. Also, on my retina screen the image appears very pixelated. Is there a way to fix this, or even use SVG's instead of PNG sprites?

**Comment by jfirebaugh** [comment]
What version of mapbox-gl-js? Can you please provide a JSFiddle that demonstrates the problem?

**Comment by Tam** [comment]
I'm using v0.14.1. See [Plunker](http://embed.plnkr.co/02BL3qOgTRgrcmnL5pZx/) for an example.

**Comment by jfirebaugh** [comment]
It's not loading for me:

![image](https://cloud.githubusercontent.com/assets/98601/13057839/86d610e0-d3d3-11e5-9bab-b70d785d137a.png)

**Comment by Tam** [comment]
Only the @ 2x files exist (although I've uploaded the 1x files now so your problem should be solved).But the issue is on retina, so you'll need to view it on a retina screen to see it.

<img width="222" alt="screen shot 2016-02-16 at 10 04 59" src="https://cloud.githubusercontent.com/assets/977594/13073201/47e6823a-d495-11e5-8256-7b3459065500.png">

I've attached a screenshot (above) illustrating the issue on my retina screen. You can see that the marker is noticeably lower quality compared to the rest of the map.

**Comment by ansis** [comment]
It is being rendered the right size on a retina screen (68px):

<img width="118" alt="screen shot 2016-02-16 at 10 59 58 am" src="https://cloud.githubusercontent.com/assets/1421652/13087390/7f30976a-d49c-11e5-8367-944ff5fbce5e.png">


```
"marker-blue": {
    "width": 136,
    "height": 136,
    "x": 0,
    "y": 0,
    "pixelRatio": 2
  }
```

The retina version does appear pixelated on a retina screen, but this also happens outside of gl for me. I think it's an issue with the image.
