### ISSUE TITLE
raster source: allow tiles option to be a function/array of functions

### ISSUE THREAD

**Issue by gstf** [mapbox/mapbox-gl-js#2129]
It would be nice if you could specify the tile URL as a function. Compare the getTileUrl function in leaflet. 
Possible use case is if you work with S3 signed urls.

Or am I missing another way of doing this?

Example:
```
var map = new mapboxgl.Map({
    container: 'map', // container id
    style: {
        "version": 8,
        "sources": {
            "raster-tiles": {
                "type": "raster",
                "url": function(tile) {
                    var url = '<construct url here>';
                    return s3.signUrl(constructUrl);
                },
                "tileSize": 256
            }
        },
        "layers": [{
            "id": "simple-tiles",
            "type": "raster",
            "source": "raster-tiles",
            "minzoom": 0,
            "maxzoom": 22
        }]
    },
    center: [-74.50, 40], // starting position
    zoom: 2 // starting zoom
});
```

**Comment by jfirebaugh** [comment]
We don't do this for a couple reasons:

* Styles need to be serializable JSON conforming to https://www.mapbox.com/mapbox-gl-style-spec/. Even runtime-added sources are expected to be serializiable by `Map#getStyle`.
* Tile requests are done on a web worker, and functions cannot be transferred to web workers.

**Comment by redrockhorse** [comment]
weak explanation.
