### ISSUE TITLE
Popups not showing for dense markers

### ISSUE THREAD

**Issue by yuvadm** [mapbox/mapbox-gl-js#2130]
I'm adding popups on marker hover similar to this example https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/

In most cases it works and I can see a `mapboxgl-popup` element added with style `transform: translate(0px, -50%) translate(500px, 300px)`. But when hovering over markers that overlap (I'm using `allow-icon-overlap: true`) none of the popups show and I can see they are indeed added to the markup but with style `transform: translate(-100%, -50%) ...`

Additionally, all the popups I set with `anchor: 'top'` are thrown off several hundered pixels to the left of the marker.

What's going on here?

**Comment by jfirebaugh** [comment]
Popups appear to behave correctly on overlapping markers in https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/.

Can you provide a JSFiddle that demonstrates the issue?

**Comment by mourner** [comment]
Closing the issue, but will reopen if there's a reproducible test case (e.g. on JSFiddle).
