### ISSUE TITLE
lib broken since v0.12.3 on my computer, blank canvas

### ISSUE THREAD

**Issue by KoAi** [mapbox/mapbox-gl-js#2131]
Hello,

I can't use anymore lib, all examples are broken for me, I see a white background instead of the map. Same result on Chrome and Firefox, it only works on IE.

![display a map mapbox - google chrome]
(https://cloud.githubusercontent.com/assets/1798678/13082206/07d0d12e-d4d0-11e5-8f71-b8b8187aa21e.jpg)

I could make it works on Firefox by changing parameter in about:config : webgl.disable-angle true (see below http://webglreport.com/ report)

With false

> Platform: 	Win32
Browser User Agent: 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
Context Name: 	webgl
GL Version: 	WebGL 1.0
Shading Language Version: 	WebGL GLSL ES 1.0
Vendor: 	Mozilla
Renderer: 	Mozilla
Antialiasing: 	Available
ANGLE: 	Yes, D3D11
Major Performance Caveat: 	No

With true
> Platform: 	Win32
Browser User Agent: 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
Context Name: 	webgl
GL Version: 	WebGL 1.0
Shading Language Version: 	WebGL GLSL ES 1.0
Vendor: 	Mozilla
Renderer: 	Mozilla
Antialiasing: 	Available
ANGLE: 	No
Major Performance Caveat: 	No

Could you help me find a workaround, or is it a bug ? Same thing heppen to me on https://www.mapbox.com/studio/ no map for me.

**Comment by jfirebaugh** [comment]
Setting webgl.disable-angle to true means you are turning off hardware accelerated rendering. If hardware accelerated rendering does not work it is likely an OS or graphics driver issue.

**Comment by Ventricule** [comment]
I have exactly the same issue.
It happen in the studio and in the exemples, but not in the gallery and not in all other webgl application.
It should be an OS or graphics driver issue, but, hard to understand why it only happen with mapbox.
I have a nvidia nvs 3100m graphic card, drivers up-to-date, on a windows 7 dell latitude e6510, @KoAi have you a similar hardware ? 
Thanks for the webgl.disable-angle trick.

**Comment by KoAi** [comment]
I have similar hardware nvidia GeForce 210 with dell computer on windows 7. I made lot of test and it is hard to understand, for now, I could make my app works on v0.12.2 and I am comparing commit to understand which part of code is concerning.

What is annoying for me is Mapbox Studio since one or two weeks, no display...
