### ISSUE TITLE
Search vector layer features.

### ISSUE THREAD

**Issue by ConorCoakley** [mapbox/mapbox-gl-js#2132]
Can anyone show how to search for and retrieve attribute features from vector layers using Mapbox GL using a search box (using jquery maybe)? 

A plugin in future along the lines of this would be great:
https://github.com/stefanocudini/leaflet-search

**Comment by lucaswoj** [comment]
There is no built in search API.

Depending on what you want to do, you might find these examples useful: 

 - https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/
 - https://www.mapbox.com/mapbox-gl-js/example/using-featuresin/

If you have any more support questions, please contact our support team. GitHub issues should be reserved for bug reports and feature requests. https://www.mapbox.com/contact/
