### ISSUE TITLE
User editable canvas

### ISSUE THREAD

**Issue by tehbenj** [mapbox/mapbox-gl-js#2133]
Does documentation exist on how to implement a user editable canvas (overlay) on a pre-set style (add marker, add polygon) on a gl js map?

I am having trouble achieving this as the examples all refer to static data (geojson) source. I wondered if i might have missed it? If there is no doc can anyone point me in the right direction? I may be in a position to contribute to a guide once i know how.

**Comment by jfirebaugh** [comment]
We're working on a plugin for this over at https://github.com/mapbox/mapbox-gl-draw.
