### ISSUE TITLE
Speed up "camera" / "#easeTo" / "can be called from within a moveend event handler" test

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2134]
https://github.com/mapbox/mapbox-gl-js/blob/data-driven-styling/test/js/ui/camera.test.js#L642-L657

This test accounts for a majority of the run time of the mapbox-gl-js tests

**Comment by mourner** [comment]
There's also video test that downloads a drone video from mapbox.com and it's taking ~22s.

**Comment by lucaswoj** [comment]
This is done now 🎉
