### ISSUE TITLE
Error:OK

### ISSUE THREAD

**Issue by divya1c** [mapbox/mapbox-gl-js#2136]
Hi!

I am unable to understand why this error may occur? I looked at where the error is coming from and figured out its from map.js. I did map.off, and found out the error os a source.error. 

What can the error mean? Or how can I debug this? I am using serving geojson file using SimpleHTTPServer.

This is how the head of my geojson file looks :
`{
"type": "FeatureCollection",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::4269" } },
                                                                                
"features": [
{ "type": "Feature", "properties": { "id": 1, "unique_id": "nc72282711", "damage": 0, "geoid10": "060770050013026" }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -121.137536, 37.728927 ], [ -121.132957, 37.72933 ], [ -121.133042, 37.723335 ], [ -121.133681, 37.723979 ], [ -121.134207, 37.724 ], [ -121.134797, 37.723737 ], [ -121.135264, 37.723054 ], [ -121.135204, 37.723619 ], [ -121.13597, 37.724828 ], [ -121.136689, 37.724804 ], [ -121.137429, 37.724349 ], [ -121.137536, 37.728927 ] ] ] ] } },
{ "type": "Feature", "properties": { "id": 2, "unique_id": "nc72282711", "damage": 0, "geoid10": "060770041062001" }, "geometry": { "type": "MultiPolygon", "coordinates": [ [ [ [ -121.372822, 38.209064 ], [ -121.371538, 38.208865 ], [ -121.371025, 38.20901 ], [ -121.369789, 38.209755 ], [ -121.368233, 38.209477 ], [ -121.366328, 38.209991 ], [ -121.366097, 38.209831 ], [ -121.365372, 38.20837 ], [ -121.364212, 38.208643 ], [ -121.36297, 38.208462 ], [ -121.361577, 38.20868 ], [ -121.3599, 38.210055 ], [ -121.358919, 38.21036 ], [ -121.358241, 38.212096 ], [ -121.356485, 38.212268 ], [ -121.355762, 38.212056 ], [ -121.355095, 38.211225 ], [ -121.35331, 38.210294 ], [ -121.350322, 38.209472 ], [ -121.348349, 38.209262 ], [ -121.347434, 38.208634 ], [ -121.34727, 38.208121 ], [ -121.346858, 38.207625 ], [ -121.346005, 38.207165 ], [ -121.3441, 38.206694 ], [ -121.343119, 38.207129 ], [ -121.342577, 38.207109 ], [ -121.339986, 38.205936 ], [ -121.336541, 38.205675 ], [ -121.335493, 38.205051 ], [ -121.335058, 38.20431 ], [ -121.335113, 38.203813 ], [ -121.336046, 38.202589 ], [ -121.336469, 38.200828 ], [ -121.336446, 38.200531 ], [ -121.335915, 38.199697 ], [ -121.335881, 38.198447 ], [ -121.335525, 38.198178 ], [ -121.334937, 38.198083 ], [ -121.333116, 38.198065 ], [ -121.332517, 38.197657 ], [ -121.332432, 38.197153 ], [ -121.332859, 38.196359 ], [ -121.332656, 38.195902 ], [ -121.332381, 38.195545 ], [ -121.331429, 38.195333 ], [ -121.331137, 38.195059 ], [ -121.33161, 38.193774 ], [ -121.331521, 38.193263 ], [ -121.330414, 38.192895 ], [ -121.329027, 38.191776 ], [ -121.328627, 38.190694 ], [ -121.328353, 38.190425 ], [ -121.327197, 38.190621 ], [ -121.324553, 38.190058 ], [ -121.323234, 38.19001 ], [ -121.322305, 38.189181 ], [ -121.335531, 38.189198 ], [ -121.335789, 38.196445 ], [ -121.354161, 38.196553 ], [ -121.353945, 38.189285 ], [ -121.372223, 38.189341 ], [ -121.372822, 38.209064 ] ] ] ] } },
`

Thanks!

**Comment by jfirebaugh** [comment]
Can you please provide a self-contained example that demonstrates the issue? We don't have enough to go on with the above description.

**Comment by divya1c** [comment]
This is my html file : 
`<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title></title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.14.1/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.14.1/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>

<div id='map'></div>
<script>


mapboxgl.accessToken = 'pk.eyJ1Ijoibmljb2xlaHUwOCIsImEiOiI4ZjcwZmFkZDVmNjNlMmJjMTQ2Y2E0MTFjOTcwMDJmOSJ9.g7jfXLm1yZzYfNNvKt7sgw';

// var url = 'http://127.0.0.1:8080/damage_blocks/{z}/{x}/{y}.json';
// var source = new mapboxgl.GeoJSONSource({
//     data: url
// });

var style = {
    "version": 8,
    "sources" : {
        "terrain-data" : {
            "type" : "geojson",
            "data" : "http://localhost:8000/ogr_out.json"
        }
    },
    "layers" : [
        {
            "id": "background",
            "type": "background",
            "paint": {
                "background-color": "#41afa5"
            }
        },  {
            "id": "terrain-data-layer",
            "type": "fill",
            "source": "terrain-data",
            "paint": {
                "fill-color": "#ff69b4",
                "fill-opacity": 0.8
            }
    }]
};

var map = new mapboxgl.Map({
    container: 'map',
    // style: 'mapbox://styles/mapbox/streets-v8',
    style : style,
    zoom: 10,
    center: [-122.447303, 37.753574]
});

map.off('style.error', map.onError);
//map.off('source.error', map.onError);
map.off('tile.error', map.onError);

</script>

</body>
</html>`


This the simple-server.py I run to host the directory with my json file : I run the python script to host the directory.
`#! /usr/bin/env python2
from SimpleHTTPServer import SimpleHTTPRequestHandler
import BaseHTTPServer

class CORSRequestHandler (SimpleHTTPRequestHandler):
    def end_headers (self):
        self.send_header('Access-Control-Allow-Origin', '*')
        SimpleHTTPRequestHandler.end_headers(self)

if __name__ == '__main__':
    BaseHTTPServer.test(CORSRequestHandler, BaseHTTPServer.HTTPServer)`


I uploaded the json file in txt format since git doesn't support json format files.
[ogr_out.txt](https://github.com/mapbox/mapbox-gl-js/files/135337/ogr_out.txt)

I am using google chrome browser. 

Thanks! :)

**Comment by divya1c** [comment]
It works with the new file. No idea why I got the error with an older file.
