### ISSUE TITLE
optimize style recalculation

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2141]
It takes 5-15ms to recalculate the mapbox-streets style. That's way too long for something that runs every frame while zooming.

Style recalculation takes twice as long as the rest of the rendering work done by the cpu:
<img width="420" alt="screen shot 2016-02-17 at 5 36 33 pm" src="https://cloud.githubusercontent.com/assets/1421652/13131016/b5699474-d59d-11e5-8677-a364b1616cb6.png">

We should have a benchmark for this.

**Comment by lucaswoj** [comment]
Looks like `_recalculate` is unoptimized by Chrome. That's not good.

Let's hold of on any big picture refactoring of the style classes until data-driven styling lands. I have been refactoring them towards the architecture we need for data driven styling, at some performance cost. We can revisit perf afterwards.

**Comment by mourner** [comment]
Quick profiling suggest that a heavy slowdown happened between 0.12 and 0.13 after @lucaswoj StyleLayer refactorings. Although in my profiles, Chrome doesn't mark it as unoptimized, it still takes about 3 times more time, which is pretty severe, so we might want to prioritize this.

0.12:
![image](https://cloud.githubusercontent.com/assets/25395/13137681/52f3a90e-d62b-11e5-9a09-d51265248f7e.png)

0.13:
![image](https://cloud.githubusercontent.com/assets/25395/13137688/68ef618a-d62b-11e5-80ab-2a5dab14b8bd.png)

**Comment by mourner** [comment]
For reference, the PR in question is #1960 and possibly some follow-up PRs.

**Comment by mourner** [comment]
> Let's hold of on any big picture refactoring of the style classes until data-driven styling lands. I have been refactoring them towards the architecture we need for data driven styling, at some performance cost.

@lucaswoj I looked through the changes in your #1932 data-driven styling PR, and they don't seem to contradict my optimizations in #2221, so let's review and merge the fix!

**Comment by lucaswoj** [comment]
Thank you for the consideration @mourner. :bow:
