### ISSUE TITLE
label drawing problem at pitching 55 degree

### ISSUE THREAD

**Issue by emreesirik** [mapbox/mapbox-gl-js#2148]
http://s11.postimg.org/87duhv4w3/mapbox_bug.png

There is a problem with drawing label

**Comment by jfirebaugh** [comment]
What version of mapbox-gl-js are you using?

**Comment by emreesirik** [comment]
v0.14.1

**Comment by ansis** [comment]
Is the layer causing problems using data from vector tiles or is it a geojson layer?

Here's what I think is happening:
The layer has `"*-allow-overlap": true`. Symbols that area allowed to overlap are sorted in the y direction (#470). This is implemented by sorting symbols within each tile. To get the sorting right across tile edges we clip these symbols to the tile edges and rely on the other tile to render the other half of the symbol. In this example the other tile doesn't have the point so it can't render the other half.

long term we may change the way we handle this case, but shorter term you could:
- increase the size of the data padding in the vector tile
- now use `"*-allow-overlap": true`
- use smaller labels

**Comment by lucaswoj** [comment]
Closing because

 - this issue is stale (it was reported long ago and hasn't come up since)
 - this issue fundamentally occurs because a point feature isn't included in the other tile's buffers
 - there's no clear actionable fix in this issue
