### ISSUE TITLE
Non-uniform dashes

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#2154]
Noticed that dashes look really ugly in mapbox-gl-draw with the gl-js master build:

![image](https://cloud.githubusercontent.com/assets/25395/13174789/bc95938e-d70e-11e5-908f-1c5d881ac5ec.png)

It's one single feature, but you can notice vastly different dashes on each segment. Must be a bug. cc @ansis

**Comment by mourner** [comment]
Another example:

![image](https://cloud.githubusercontent.com/assets/25395/13174846/0b8e4c10-d70f-11e5-811c-3d565fd86472.png)

**Comment by ansis** [comment]
@mourner I think https://github.com/mapbox/mapbox-gl-js/pull/2114 should fix this. Can you confirm?

**Comment by mourner** [comment]
Hmm, this totally looks like duplicate of #2099. Will see if #2114 fixes it.

**Comment by mourner** [comment]
@ansis confirmed to be fixed by #2114.
