### ISSUE TITLE
Initial map width not accurate, leaving gap on right on map

### ISSUE THREAD

**Issue by facultymatt** [mapbox/mapbox-gl-js#2156]
I have an angularjs app which renders a GL map. On load, the map is not the correct width. This leaves a white margin on the side. Once the page is resized the map width corrects itself. 

It looks like this:

<img width="396" alt="space" src="https://cloud.githubusercontent.com/assets/1406258/13186290/8ebabdb8-d713-11e5-83c1-0dc7b678d126.png">

My styles for the map div are:

<img width="196" alt="styles" src="https://cloud.githubusercontent.com/assets/1406258/13186309/a2fb367c-d713-11e5-8500-db1da1172589.png">

And the canvas element rendered by mapbox is (note width)

<img width="484" alt="dom" src="https://cloud.githubusercontent.com/assets/1406258/13186318/aec78b2c-d713-11e5-944d-a39820b56155.png">

After a resize (note width)  

<img width="449" alt="dom_after_resize" src="https://cloud.githubusercontent.com/assets/1406258/13186330/c378cad6-d713-11e5-9ede-108859f4b0ad.png">

**Comment by jfirebaugh** [comment]
Most likely angular or your app is resizing the map dynamically. You must call [`map.resize`](https://www.mapbox.com/mapbox-gl-js/api/#Map.resize) afterwards.

**Comment by averas** [comment]
I'm also using angular. If your map loads before its parent container has been rendered and received its width/height (for example when using <code>ng-cloak</code>) you will run into this. Either enforce the rendering/map-load order, or, as suggested above, call <code>map.resize()</code> afterwards. The former has the upside that the user will not be exposed to a small map that resizes during page load.
