### ISSUE TITLE
cannot export Canvas to image using satellite-hybrid-v8

### ISSUE THREAD

**Issue by peckjon** [mapbox/mapbox-gl-js#2161]
It appears that when mapbox://styles/mapbox/satellite-hybrid-v8 , map.getCanvas().toDataURL("image/png") fails silently.

This may be intentional due to copyright issues or similar... ?  If so, is it documented?  Also, failing silently may not be ideal.

**Comment by ansis** [comment]
Thanks for the report and jsfiddle. c8d54418cf86b7aaa7dee0c974dba3fd53f5d452
Yes, this was a bug in e6cb15c.  It's now fixed in master with c8d5441
