### ISSUE TITLE
Check all examples for style validation errors

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#2162]
6122e19a92f85c71579fc446271451cbe72a5dbb revealed at least one error in an example: as reported in https://github.com/mapbox/mapbox-gl-js/issues/1700#issuecomment-186659861, ["Update a choropleth layer by zoom level"](https://www.mapbox.com/mapbox-gl-js/example/updating-choropleth/) is rendering every state and county in yellow, because the filter does not validate:

> Error: undefined[2][2]: string, number, or boolean expected, undefined found

We need to go through every example and make sure that it does not produce style validation errors, fixing those that do.

cc @lucaswoj

**Comment by lucaswoj** [comment]
https://www.mapbox.com/mapbox-gl-js/example/video-on-a-map/ is broken due to #2167

**Comment by lucaswoj** [comment]
https://www.mapbox.com/mapbox-gl-js/example/measure is failing validation

**Comment by lucaswoj** [comment]
fixed in d21e02ffefd4de0006b485017d7e665b776a80b4
