### ISSUE TITLE
Library Not Loaded

### ISSUE THREAD

**Issue by dailenspencer** [mapbox/mapbox-gl-js#2163]
After adding the MapBox Framework to my project, I am receiving the following error : 

dyld: Library not loaded: @rpath/Mapbox.framework/Mapbox
  Referenced from: /private/var/mobile/Containers/Bundle/Application/2D2A4D3A-A590-471C-B0D6-546CE4C124AB/greek.app/greek
  Reason: image not found
(lldb) 

This error occurs when attempting to run on device only. So far I have found two routes that solve the issue temporarily but the project still doesnt run as expected.

1. Add MapBox framework to "embedded binaries". Only issue is that if i attempt to archive the project after doing so, I receive a ton of errors about unsupported architectures and other things.

2. Set MapBox framework to "optional". This allows the project to run. However, when presenting a viewcontroller that contains the MGLMapView, the project crashes.

Ive also tried disabling bitcode but that hasnt helped. Any suggestions?

**Comment by tmcw** [comment]
This is the issue tracker for Mapbox GL JS, the JavaScript version of the library: please file an issue in [the mapbox-gl-native issue tracker for issues with Mapbox GL native](https://github.com/mapbox/mapbox-gl-native/issues).
