### ISSUE TITLE
setFilter should accept lists for methods such as "in" or "!in"

### ISSUE THREAD

**Issue by MichaelMarkieta** [mapbox/mapbox-gl-js#2165]
I have a dynamically generated list for my layer filter, which I use with the "in" method. However, I cant pass that list as the set of values to filter by because the setFilter slices the parameters and creates a list of lists (which is then further down the line stringified with extra braces on the outside).

**Comment by MichaelMarkieta** [comment]
["in", key, v0, ..., vn]

It would be great if v0, ..., vn could be passed as a list of strings.

**Comment by jfirebaugh** [comment]
Filters are just regular JavaScript arrays. If you have an array of strings `vN`, and you want an `in` filter that allows any of those strings, use `Array#concat`:

```
["in", "key"].concat(["a", "b", "c"]);
  // returns ["in", "key", "a", "b", "c"]
```

For another example of a dynamic filter, [check out this example](https://www.mapbox.com/mapbox-gl-js/example/using-featuresin/): it builds a filter using `Array#reduce`.
