### ISSUE TITLE
0.14.2 regression, getOpacities() `Uncaught TypeError: Cannot read property 'z' of undefined`

### ISSUE THREAD

**Issue by jlc467** [mapbox/mapbox-gl-js#2167]
Getting `Uncaught TypeError: Cannot read property 'z' of undefined` when zooming on this example: https://www.mapbox.com/mapbox-gl-js/example/map-tiles/

Doesn't happen in 0.14.1.

My attempt at debugging led me to this commit that returns true instead of a tile.
https://github.com/mapbox/mapbox-gl-js/commit/e6cb15c3f18c73cfc7aea2a797d3a33eedb946cd

Going to dig some more but wanted to report my findings.

**Comment by ryanbaumann** [comment]
Likewise noted in #2161

**Comment by ansis** [comment]
Yes, this was a bug in e6cb15c. It's now fixed in master with c8d54418cf86b7aaa7dee0c974dba3fd53f5d452
