### ISSUE TITLE
name of `shader` property of buckets

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2172]
I'm not sure `shader` is the right name for [shader property of buckets](https://github.com/mapbox/mapbox-gl-js/blob/1ad40725cf925c61db2a6a80d18ff50144e85067/js/data/symbol_bucket.js#L83-L95). The buffers aren't necessarily 1-to-1 with a shader. `icon` could be rendered with either the sdf shader or the bitmap icon shader. Lines currently have one `shader` type in the bucket but three different shaders.

@lucaswoj

**Comment by lucaswoj** [comment]
> I'm not sure shader is the right name for shader property of buckets.

I see your point. The `shaders` data structure is intended to describe a set of shader _interfaces_ (the set of attributes and their types). Do you think `shaderInterface` is a better name? 

> The buffers aren't necessarily 1-to-1 with a shader.

Yes, that is why a single bucket can have multiple shaders. It is currently a 1-to-n relationship.

> icon could be rendered with either the sdf shader or the bitmap icon shader.

Yes, that is why there are two entires in the `shaders` data structure. (glyph and icon)

> Lines currently have one shader type in the bucket but three different shaders.

All three shaders support the same shader _interface_ so we only need one entry in the `shaders` object.

**Comment by ansis** [comment]
> Do you think shaderInterfaces is a better name?

Sounds good to me. That one extra word clarified it a ton for me.

> It is currently a 1-to-n relationship.

It's currently n-to-n.

> Yes, that is why there are two entires in the shaders data structure. (glyph and icon)

The `icon` shader interface is used with two shaders. `sdf` can be true or false for icons: https://github.com/mapbox/mapbox-gl-js/blob/master/js/render/draw_symbol.js#L111-L115

Icons and glyphs should have one shared shader interface but two separate buffer instances. The shader instances and buffer/elementgroup instances should be 1-to-n.

This isn't anything urgent. It just confused me for a bit.

**Comment by lucaswoj** [comment]
> Icons and glyphs should have one shared shader interface but two separate buffer instances. The shader instances and buffer/elementgroup instances should be 1-to-n.

This would be more complex than manually reusing the shader interface like we do now. We should punt on that refactor until it becomes a problem.

**Comment by ansis** [comment]
>  We should punt on that refactor until it becomes a problem.

sounds good to me

**Comment by lucaswoj** [comment]
:rocket:
