### ISSUE TITLE
Expose interaction handler enabled/disabled state

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2173]
There's an issue on mapbox-gl-js-draw asking for disabling boxZoom temporarily when selecting features (https://github.com/mapbox/mapbox-gl-draw/issues/213), however, as far as I can tell there is no supported way to determine whether a certain interaction handler is enabled or not.

Even if it would be possible to always disable boxZoom temporarily when selecting features, to determine whether to enable it again requires knowledge of whether boxZoom was intentionally disabled overall.

Would it make sense to expand the API to expose the state of interaction handlers?

**Comment by mourner** [comment]
Yes, I think we need to add `enabled` property or `isEnabled()` method.

**Comment by bhousel** [comment]
I agree, but the idea didn't seem to have much support before.
https://github.com/mapbox/mapbox-gl-js/pull/2085#issuecomment-181583108

**Comment by averas** [comment]
> Yes, I think we need to add enabled property or isEnabled() method.

If you guys agree on which alternative to go for I can wrap this up in a PR. Some interaction handlers already have a public (no leading underscore), but non-documented <code>active</code> property. For consistency it's probably either best to go for an <code>enabled</code> property, or wrap the <code>active</code> property in a <code>isActive()<code> method as well. The latter obviously being a breaking change.

**Comment by mourner** [comment]
Let's go for `enabled` public property.

**Comment by averas** [comment]
:+1:

**Comment by averas** [comment]
Fixed by #2238.
