### ISSUE TITLE
Add a Map#setMaxBounds method

### ISSUE THREAD

**Issue by yoannlal** [mapbox/mapbox-gl-js#2175]
Hi !

Any solution to update maps' maxBounds after a flyTo() or fitBounds() and fix the map to this specific area ?
Or a setMaxBounds(LngLatBounds) function which we could fire after a moveend event as an improvement ?

Thank you !

**Comment by lucaswoj** [comment]
Good point @yoannlal. We should allow the max bounds to be modified after the map is constructed.
