### ISSUE TITLE
Deleted features still visible with featuresAt

### ISSUE THREAD

**Issue by BrunoSalerno** [mapbox/mapbox-gl-js#2177]
### Context

* **mapbox-gl-js version**: 14.2
(This bug was fixed in 13.x series, but in 14.x it came back)

### Report

**Expected behavior**:
When deleting features using `setData` I expect them not to be shown by `featuresAt` (because the don't exist anymore!)

**Actual behavior**:
Deleted features still visible with `featuresAt`

See the js fiddle: https://jsfiddle.net/brunosalerno/pp7qqp6u/

**Steps to reproduce the behavior (in the fiddle)**:

- Open the console.
- Press the `Add features` button. (adds TWO features)
- Press the `Remove one feature` button THREE times.
- Move the mouse over the area where the features were. The hover will detect the missing features.

**Comment by lucaswoj** [comment]
This is happening with features hidden in other ways too, see #2207.

**Comment by lucaswoj** [comment]
Maybe related to #2244

**Comment by BrunoSalerno** [comment]
This is still happening with `queryRenderedFeatures`.
I will open a new issue.

Fiddle: https://jsfiddle.net/brunosalerno/tpus0kv8/
