### ISSUE TITLE
Is there a way to perform a featuresIn query on an entire layer?

### ISSUE THREAD

**Issue by ChexWarrior** [mapbox/mapbox-gl-js#2182]
Is it possible to perform a `featuresIn` like query on an entire layer that is not limited to a bounding rectangle or the viewport? I am currently trying to filter some features on a layer based on common properties, however I need to intercept the feature's property before the actual filtering is done otherwise I'd use `setFilter`.  Thanks in advance.

**Comment by tmcw** [comment]
By entire layer, do you mean all tiles? Such an API wouldn't be feasible performance-wise: asking for `.allFeatures()` on the `buildings` layer of Mapbox Streets at z22 would download many gigabytes of data.

If your intent is to incorporate newly-loaded features into your setFilter calculations, you might want to use a map movement event like `moveend` to run featuresIn again when the map is updated.

**Comment by ChexWarrior** [comment]
My intent is to filter some features created from a geojson file on a single layer, however I'd like to intercept the property value that I'm filtering on. 

I have a geojson file that creates some features that contain a **cost** property, in the `geojson` it is specified as a string. However when filtering I need to change that property's datatype to be an integer, I can't seem to do that with `setFilter`. As an alternative I was using `featuresIn` to intercept and modify a feature's properties before filtering, however since `featuresIn` only queries for features within certain bounds it can't be reliably used to query all features in a layer. Does that make sense?

I know I could ensure the correct datatype is specified in the geojson and I could also zoom out all the way before using `featuresIn` to ensure all features are included but I was wondering if there was a better way.

**Comment by lucaswoj** [comment]
> ... I could ensure the correct datatype is specified in the geojson ...

That sounds like the right solution in this case. :+1:
