### ISSUE TITLE
Emit event when WebGL context creation fails

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#2187]
### Context

* **mapbox-gl-js version**: 0.14.2

### Report

**Expected behavior**: When a `mapboxgl.Map` class is initialized and the getContext() call fails, the map should emit an error or another programmatically-readable indication of this failure

**Actual behavior**: The map calls [console.error](https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/map.js#L700).

**Steps to reproduce the behavior**:

1. Have too many WebGL contexts open on a page, causing context creation to fail
2. Initialize a mapboxgl map
3. Listen to the map's events

---

I expect that emitting the error initially and then binding `.on('contexterror', function() {})` will result in the error being fired _before_ the map is initialized? It may need to sit on a nextTick or something.

**Comment by mLuby** [comment]
👍 this would be great. The console.error is now on [line 778](https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/map.js#L778), inside the `_setupPainter` method.

**Comment by lucaswoj** [comment]
Related to #889

**Comment by jfirebaugh** [comment]
`Map` [fires an "error" event](https://github.com/mapbox/mapbox-gl-js/blob/6cbd5d0970073d85bad42f3002ddbee28f0f028c/js/ui/map.js#L963-L963) now.

**Comment by tetreault** [comment]
very odd this still happens in v65 (64 bit) of chrome on a 2018 MBP
