### ISSUE TITLE
.featuresAt() not firing when invoked with .on('load') event

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#2188]
### Context

* **mapbox-gl-js version**: v0.14.2

### Report

**Expected behavior**: hovering over the neighborhood polygons should bring up a green overlay

**Actual behavior**: hovering does nothing, until map zoomed in and out a few times

**Steps to reproduce the behavior**:

Check out http://bl.ocks.org/peterqliu/82e87e4b9cd8f4c95001

cc/ @lucaswoj @ansis

**Comment by tmcw** [comment]
'load' never fires in this code snippet.

**Comment by lucaswoj** [comment]
Fixed by #2176, going out in a release today
