### ISSUE TITLE
Is there a documentation of version changes or stable version?

### ISSUE THREAD

**Issue by peterbodo** [mapbox/mapbox-gl-js#2193]
Context

* **mapbox-gl-js version**: v0.13.1

### Report

**Expected behavior**: 
interactive= false (default)
source=composite - id = osm_id + 1,2,3*10^12,15

**Actual behavior**:
interactive=true (default)
id = osm_id*10 (node)
osm_id*10+2 (way,polygon)
osm_id*10+4 (relation,multipolygon)
(stopped reverse engineering here :)

Changes happened today and broken app.

**Comment by peterbodo** [comment]
Label: support

**Comment by tmcw** [comment]
@peterbodo are you referring to Mapbox GL JS, the JavaScript library, or something else, like Mapbox Studio? Mapbox Studio support is handled on help@mapbox.com

**Comment by peterbodo** [comment]
Well, I guess you are right. It is not the JS library that changed, but the source for street-v8 (while breaking mapbox gl js apps).
While it is offtopic, if you can, I would be grateful for showing me a page, where at least warnings appear for breaking changes for the provided map styles.
And of course, let's close it.
Thx

**Comment by samanpwbb** [comment]
Fixed by https://github.com/mapbox/mapbox-gl-styles/pull/265
