### ISSUE TITLE
Touch events don't trigger mapbox events

### ISSUE THREAD

**Issue by gordonnl** [mapbox/mapbox-gl-js#2195]
### Context

* **mapbox-gl-js version**:  v0.14.3
* **devices**:  Nexus 5, iPhone 6s, MBP chrome device emulator

### Report

**Expected behavior**: Tapping map fires 'click' event. Same for doubletap: 'doubleclick',  touchstart: 'mousedown', touchend: 'mouseup'

**Actual behavior**: No events fired

**Steps to reproduce the behavior**:

1. Instantiate gl map
2. Add 'click' event listener to map
3. Touch map

**Comment by tmcw** [comment]
Are touch events fired? We should not make mapbox gl js translate between native events and what we might want - it'd be a leaky abstraction because the `click` handler could get a click event _or_ unclear, maybe like a touchstart event or a touchend event.

**Comment by gordonnl** [comment]
Touch events don't work (e.g. 'touchstart'). I agree for 'mousedown' and 'mouseup' as they're very descriptive, therefore adding touch events on top of these makes sense.
For click - I'd have both touch and mouse events fire it - as is present on Mapbox.js.

**Comment by gordonnl** [comment]
What would be the easiest way to hack this functionality temporarily? We're hoping to use this in an application that's currently under production.

**Comment by bhousel** [comment]
Hey @gordonnl I'm going to look into this issue today and find out what's going on.  I believe browsers are expected to emit click events for either mouse or touch, so if we aren't re-emitting that as a map event, we should be.

**Comment by gordonnl** [comment]
Thanks a lot!

**Comment by bhousel** [comment]
@gordonnl, I agree we should emit touch events. I'm going to add this functionality.

However I'm confused by your report that you aren't getting _any_ events fired.  For example, I do see all of these events using our debug page and code like the following (I am testing v0.14.3 in Chrome Developer Tools using device emulation w/iPad):

```js
['mousedown', 'mouseup', 'click', 'dblclick'].forEach(function (s) {
  map.off(s).on(s, function(data) { 
    var e = data && data.originalEvent;
    console.log(s + (e ? ' buttons = ' + e.buttons + ', button = ' + e.button : '')); 
  });
});
```

**Comment by gordonnl** [comment]
Thanks very much. Looking forward to having the touch events.

I've done more digging after your last comment, and noticed that our framework was blocking the browser's emulated mouse events ('mousedown', 'mouseup', 'click') for touch devices. The reason for this is that we were adding something like the following:
`window.addEventListener('touchstart', function(e) {
    e.preventDefault();
}, false);`
This is commonly used to prevent the native 'page-pulling' in the mobile browser, for full-screen applications.

For this reason, the 'dblclick' event was still correctly firing, as I see that it's attached to the 'touchstart' event, which still fires.

This also explains why the click event was working in the Mapbox.js version, as Leaflet.js has mapped native touch events to fire the 'click' event as well.

Glad to have that sorted, thanks again.
