### ISSUE TITLE
Building standalone mapbox-gl.js fails with browserify?

### ISSUE THREAD

**Issue by knutole** [mapbox/mapbox-gl-js#2197]
I've cloned the repo and I'm attempting to simply build a standalone mapbox-gl.js file. 

A simple `browserify js/mapbox-gl.js -o dist/mapbox-gl.js` does not work, neither does  `browserify js/mapbox-gl.js -s mapboxgl -o dist/mapbox-gl.js` 

How can I simply build the standalone `.js` file, like https://api.tiles.mapbox.com/mapbox-gl-js/v0.14.3/mapbox-gl.js?

**Comment by tmcw** [comment]
* By "does not work", please give more detail: precise error messages and so forth. Please do this for all bug reports.
* Have you tried the `npm run build` command?

**Comment by knutole** [comment]
Sorry, by "does not work" I meant the generated file did not work in the browser (ie. `mapboxgl` not available as global). 

`npm run build` works very well. Perhaps worth adding a line in README.me about this, although perhaps I should have know this.

Thank you very much for your quick reply!
