### ISSUE TITLE
.setFilter() triggers vector tile requests

### ISSUE THREAD

**Issue by knutole** [mapbox/mapbox-gl-js#2198]
#### Problem
When using .setFilter(), vector tiles that are already loaded get **re-requested** from server. 

Requesting vector tiles when setting filter seems unnecessary and is a bit of a performance killer?

#### jsbin
See [this jsbin](http://jsbin.com/dikosecuza/1/edit?html,output) for a working example.

#### Screen dump
![tile_requests](https://cloud.githubusercontent.com/assets/2197944/13375244/dc52f8be-dd9a-11e5-8960-ebddc7b81767.gif)

#### Version
Mapbox-gl.js version: `0.14.3`

#### Relevant code:
```javascript
    var systemapic_access_token = 'pk.8FhhB90ax6KkQmoK0AMePd0R6IlkxM4VAGewsXw8';

    var systemapic = {
        "version": 8,
        "sources": {
            "vector-tiles": {
                "type": "vector",
                "tiles": ["https://dev.systemapic.com/v2/tiles/layer_id-5bff2873-83f3-4aa2-96f5-2e770f76199c/{z}/{x}/{y}.pbf?access_token=" + systemapic_access_token],
            },
            "norkart-tiles" : {
                "type" : "raster",
                "tiles" : ["https://proxy-txa.systemapic.com/v2/tiles/norkart/aerial/{z}/{x}/{y}.jpeg?access_token=" + systemapic_access_token],
                "tileSize" : 256
            }
        },
        "layers": [
            {
                "id": "background",
                "type": "raster",
                "source": "norkart-tiles",
                "minzoom": 0,
                "maxzoom": 22
            },
            {
                "id": "sydney",
                "type": "fill",
                "source": "vector-tiles",
                "source-layer": "layer",
                "filter": ["==", "$type", "Polygon"],
                "paint": {
                    "fill-color": "#3887be"
                },
                "interactive" : true
            }
            
        ]
    };

    var map = new mapboxgl.Map({
        container: 'map', // container id
        center : [-209, -34],
        zoom : 8,
        style : systemapic
    });

    map.on('mousemove', function (e) {
      
        map.featuresAt(e.point, {
            radius: 5,
            layers : ['sydney']
        }, function (err, features) {
            if (err) return console.log(err);

            if (features.length) {

                // set filter, paint
                map.setFilter('sydney', ["==", "gid", features[0].properties.gid]);

            } else {

                // set filter, paint
                map.setFilter('sydney', ["==", "$type", "Polygon"]);
            }
        });
    });
```

**Comment by knutole** [comment]
Could be related to https://github.com/mapbox/mapbox-gl-js/pull/2174.

**Comment by knutole** [comment]
Curiously, this issue seems to go away if tile source url _is not_ the same domain as webpage itself.

That is to say, if changing `tiles` url from `https://dev.systemapic.com` to `https://tiles-txa.systemapic.com`, then `.setFilter()` won't trigger requests of vector tiles.

```javascript
     "sources": {
            "vector-tiles": {
                "type": "vector",
                "tiles": ["https://tiles-txa.systemapic.com/v2/tiles/layer_id-5bff2873-83f3-4aa2-96f5-2e770f76199c/{z}/{x}/{y}.pbf?access_token=" + systemapic_access_token],
            },

   // (...)
```

**Comment by knutole** [comment]
Or it this expected behavior? I'm interested because we're trying to implement this functionality for a client, and it's a bit of a "make or break" to get this working. 

Would it be possible to used cached vector tiles instead of requesting new tiles, for example?

**Comment by lucaswoj** [comment]
Thanks for the bug report! This is not expected behavior. We'll take a look soon.

**Comment by knutole** [comment]
Don't mean to rush anyone, but do you have an ETA for a fix?

**Comment by ansis** [comment]
Is your browser cache disabled when your console is open? The current implementation makes new xhr request whenever it needs to reparse a tile. This should hit the browser cache pretty much always.

Whenever a change to any layer definition or layout property the entire tile is reparsed. We plan to improve this by recreating only what changed, but there is no current eta for that.

**Comment by knutole** [comment]
Can confirm this has to do with cache. I was serving vector tiles with `no-cache`. Amending this to `private, max-age=3600` fixes the problem!

Thanks a lot for the tip! Closing.
