### ISSUE TITLE
Example "Highlight features under mouse pointer" has errors

### ISSUE THREAD

**Issue by knutole** [mapbox/mapbox-gl-js#2199]
#### Problem
The example [Highlight features under mouse pointer](https://www.mapbox.com/mapbox-gl-js/example/hover-styles/) has lots of the following error:
`Error: layers.route-hover.filter[2]: string, number, or boolean expected, undefined found`

The hover does not work.

#### Versions
Mapbox-gl.js version: `0.14.3`
Chrome Browser: `Version 48.0.2564.116 (64-bit)`

#### Screen dump
![highlight_error](https://cloud.githubusercontent.com/assets/2197944/13375648/cb78400c-dda5-11e5-8919-8925977138b9.gif)

#### Error stack
![screen shot 2016-02-27 at 11 00 44 pm](https://cloud.githubusercontent.com/assets/2197944/13375656/fa08c464-dda5-11e5-8523-3551550aa3fd.png)

**Comment by lucaswoj** [comment]
Thank you @knutole! 

Fixed in fec9d58d710ff4fffb568b7f674e79e2f93aa1da
