### ISSUE TITLE
Styles with raster tiles make the browser unresponsive

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#2201]
**mapbox-gl-js version**: 0.14.3

### Steps to Trigger Behavior

 1. load mapbox://styles/mapbox/satellite-v8
 2. zoom and pan like a maniac

### Expected Behavior

The map remains responsive.

### Actual Behavior

Chrome will lockup without an error on the console. The tab will consume 100% and can only be terminated by `kill -9` the process. I have not tested in other browsers.

**Comment by lucaswoj** [comment]
@ansis could you triage this? I suspect it is related to #2168.

**Comment by geografa** [comment]
flagging @mapbox/support

**Comment by lucaswoj** [comment]
I suspect the flashing and unresponsiveness are related.

**Comment by lucaswoj** [comment]
The interpreter is stuck in an infinite loop on this line https://github.com/mapbox/mapbox-gl-js/blob/raster-flicker-2201/js/util/lru_cache.js#L108
