### ISSUE TITLE
Disable drag rotate handler during touch events

### ISSUE THREAD

**Issue by DenisCarriere** [mapbox/mapbox-gl-js#2204]
When holding down (touch) using a Mobile Device or even using Google Chrome inspect, the map seems to be very glitchy afterwards.

**mapbox-gl-js v0.14.3**:
### Steps to Trigger Behavior
1. Hold down map using Mobile device

The only way to prevent it from being glitchy was to disable `dragRotate`.

``` js
map.dragRotate.disable()
```

But that removes the really cool right click rotate functionality.

I tested this bug using a basic MapboxGL example.

![ycxfo5qykx](https://cloud.githubusercontent.com/assets/550895/13415877/86fe44b6-df2c-11e5-8350-dbc461b8b5dd.gif)

**Comment by lucaswoj** [comment]
Thanks for the report @DenisCarriere! Could you tell me more about the glitch-iness? What is the exactly map doing? It is hard to tell from the posted gif. 

cc @bhousel

**Comment by DenisCarriere** [comment]
Yea I know the GIF wasn't very clear, well just test it out using Google
chrome inspect and select mobile view. Hold down touching the map, after
that every time you click on the map it rotates the map at a random
location.

This bug is also found on Android devices viewing a Mapbox GL JS map.

**Comment by DenisCarriere** [comment]
**Changes to Issue**:  The error is still the same, however it was the `map.dragRotate` that was causing the error and not `touchZoomRotate`.
cc @bhousel

**Comment by DenisCarriere** [comment]
My quick fix was to implement a Mobile Detect library and turn off `map.dragRotate`, this doesn't change any of the functionality on the Browser and on mobile devices you have the Pinch gesture to rotate.

```javascript
import MobileDetect from 'mobile-detect'

const md = new MobileDetect(window.navigator.userAgent)

// Disable (Mobile)
if (md.mobile()) {
  map.dragRotate.disable()
}
```

**Comment by lucaswoj** [comment]
Thanks for the debugging @DenisCarriere! @bhousel do you think we should automatically disable `dragRotate` for mobile devices? Are there any other follow-ups?

**Comment by bhousel** [comment]
> @bhousel do you think we should automatically disable dragRotate for mobile devices? Are there any other follow-ups?

Probably a better idea would be to watch for `touchstart`/`touchend` and disable the handler if we detect a touch event happening.  The touch events fire before the mouse events.

Besides, some devices like new Windows Surface and Chromebooks support both mouse and touch, so the problem isn't just limited to mobile.

**Comment by ChrisBellew** [comment]
Added a PR. Please review :) https://github.com/mapbox/mapbox-gl-js/pull/3457

**Comment by jfirebaugh** [comment]
I can't reproduce any issues here with 0.44.1.
