### ISSUE TITLE
Identifying cluster events

### ISSUE THREAD

**Issue by cammanderson** [mapbox/mapbox-gl-js#2205]
Hi Guys, 

We are really happy to see the supercluster inclusion in Mapbox GL JS. Great stuff :-)

We were hoping to identify when clusters form or change. I have browsed through where it has been implemented, and looks like there is no access to the supercluster object. Not sure if that would help anyway. 

Is there a suggestion that people could make of a viable way to identify when clusters change?

I may be able to work around it by watching elements on map, just hoping there might be another technique.

Cheers
Cam

**Comment by lucaswoj** [comment]
Thanks for the feature request @cammanderson. I recommend going the route of "watching elements on map" for now. If you run into any roadblocks with that, I recommend contacting [Mapbox support](http://mapbox.com/contact) and/or re-opening this issue with a specific proposal for the cluster events you'd like to see.

**Comment by lucas-dolsan** [comment]
I haven't been able to find an event to detect something like [this](https://drive.google.com/file/d/1uV2x9l6o_bs1z1AcskRE3eQLUQxJ2Zjl/view)
An event that triggers when the map "reclusters" to fit a new zoom level.
I posted on stackoverflow a [question](https://stackoverflow.com/questions/58768283/detect-when-map-reclusters-features) about this
