### ISSUE TITLE
Mapbox gl selecting underneath feature and highlighting

### ISSUE THREAD

**Issue by akshaykapadia** [mapbox/mapbox-gl-js#2206]
I've created custom style using mapbox studio and using it in my web app in js file.

Custom map is loaded with one dataset of many polygon eg., properties.
 
So problem is when I'm trying to use onclick and highlighting that particular property shape, it's showing me error in api calling.
{"message":"Not Authorized - Invalid Token"}
or
{"message":"Not Found"}

So how can I select particular feature on click and change particular feature style?
Thanks and appreciate you support.

Attached error screenshot:

![image](https://cloud.githubusercontent.com/assets/17561109/13417734/9cfee1bc-dfc2-11e5-9345-1d7bdebc9569.png)

**Comment by lucaswoj** [comment]
Thanks for reaching out @akshaykapadia! This sounds like a question best handled by our support team.  Please [reach out to them here](https://www.mapbox.com/contact/).
