### ISSUE TITLE
Flickering of background layer when zooming

### ISSUE THREAD

**Issue by knutole** [mapbox/mapbox-gl-js#2208]
### Problem
Severe flickering of background raster when zooming in and out. Seems to be related to which layers are available higher up in the tilepyramid. Seems it's going higher up in the pyramid than necessary, exchanging high-res tiles for much lower-res tiles, even when high-res are available.

Looks like an optimization for smoother zoom, but with the tradeoff of showing low-res tiles in a flickering way.

### jsbin
Zoom in and out to see flickering:
http://jsbin.com/bogelujaqe/1/edit?html,output

### Screendump
![overlay_flicker](https://cloud.githubusercontent.com/assets/2197944/13426608/cdb6aa60-dfae-11e5-8ec9-381973840a80.gif)

### Versions
Mapbox-gl.js: `0.14.3` 
Chrome: `Version 48.0.2564.116 (64-bit)`
OSX: `10.9.5` 
GPU: `NVIDIA GeForce 8600M GT 512 MB` 

### Code
```javascript


    var systemapic_access_token = 'pk.8FhhB90ax6KkQmoK0AMePd0R6IlkxM4VAGewsXw8';

    var systemapic = {
        "version": 8,
        "sources": {
            "norkart-tiles" : {
                "type" : "raster",
                "tiles" : [
                    "https://proxy-txa.systemapic.com/v2/tiles/norkart/aerial/{z}/{x}/{y}.jpeg?access_token=" + systemapic_access_token,
                    "https://proxy-txb.systemapic.com/v2/tiles/norkart/aerial/{z}/{x}/{y}.jpeg?access_token=" + systemapic_access_token,
                    "https://proxy-txc.systemapic.com/v2/tiles/norkart/aerial/{z}/{x}/{y}.jpeg?access_token=" + systemapic_access_token,
                    "https://proxy-txd.systemapic.com/v2/tiles/norkart/aerial/{z}/{x}/{y}.jpeg?access_token=" + systemapic_access_token,
                ],
                "tileSize" : 256
            }
        },
        "layers": [
            {
                "id": "background",
                "type": "raster",
                "source": "norkart-tiles",
                "minzoom": 0,
                "maxzoom": 22
            },
           
        ]
    };

  
    var map = new mapboxgl.Map({
        container: 'map', // container id
        center : [ 20.426873995740664, 69.31845195098202],
        zoom : 13,
        style : systemapic
    });



```

**Comment by lucaswoj** [comment]
Thanks for the report! I'm going to merge this into https://github.com/mapbox/mapbox-gl-js/issues/2201.

**Comment by lucaswoj** [comment]
This is my top priority today. We will publish a new release once it is fixed.

**Comment by lucaswoj** [comment]
My apologies, this turned out to be a separate issue. Fix pending.

**Comment by knutole** [comment]
Great, confirm fix! Thanks a lot!
