### ISSUE TITLE
Feature highlight on click for polygons without any unique properties.

### ISSUE THREAD

**Issue by divya1c** [mapbox/mapbox-gl-js#2210]
**mapbox-gl-js version**: v0.14.1

Hi!

I am trying to implement a 'highlight feature' using mapbox gl js. I saw this example - https://www.mapbox.com/mapbox-gl-js/example/hover-styles/. But, the problem is that my polygons do not have any properties that are unique to the polygon (unlike the name property in the example). Is there a way to filter based on geometry? Or any other way to highlight or change the paint property of the feature on click? 

Thanks!

**Comment by jfirebaugh** [comment]
Nope; you'll need to add some identifying property to the data.

**Comment by jolesbi** [comment]
@jfirebaugh what would you recommend if it's not possible to add an identifying property (because i'm displaying third party data)?

**Comment by lucaswoj** [comment]
@jolesbi the feature you're requesting is #200. It's something we'd love to build but haven't yet had the time. 

Have you checked if your features have a unique `id` field? https://github.com/mapbox/mapbox-gl-style-spec/issues/391
