### ISSUE TITLE
raster flickering in when pitch > 0

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2212]
@ryanbaumann from https://github.com/mapbox/mapbox-gl-js/pull/2211#issuecomment-191007564

**mapbox-gl-js version**: 0.15.0

### Steps to Trigger Behavior

 1. tilt a raster map
 2. zoom

### Expected Behavior

no flickering

### Actual Behavior

flickering

However, I still notice flickering on Satellite maps with Map Pitch > 0 while panning and rotating on Chrome w/ Nvidia GTX680.  Example below:

[Video Example](https://drive.google.com/file/d/0B_LDe4RHtu0eTDFjdEJtSDlWenc/view)
[JSFiddle](https://jsfiddle.net/rsbaumann/g3v05y6x/3/)

**Comment by ansis** [comment]
It looks like [z-fighting](https://en.wikipedia.org/wiki/Z-fighting).

**Comment by scothis** [comment]
Seeing this behavior when pitch is 0 as well.

**Comment by freenerd** [comment]
This bug can be seen live on the map in https://www.mapbox.com/blog/la-turn-lanes-map/ as well

![turn lanes](https://cloud.githubusercontent.com/assets/25713/13779498/8759e204-eabb-11e5-8096-2afeb2f1609f.gif)

**Comment by planemad** [comment]
I'm maintaining ^ style, have turned off satellite for now, till the bug is fixed.

**Comment by ansis** [comment]
This should be fixed by https://github.com/mapbox/mapbox-gl-js/pull/2282
