### ISSUE TITLE
Symbol text-optional; symbol text collides with other symbols and causes them to disappear

### ISSUE THREAD

**Issue by cammanderson** [mapbox/mapbox-gl-js#2213]
Hi Guys, 

Great to be contributing, it's a great project and we are pretty excited about all your work. 

We are encountering some unexpected behaviour when using the 'text-optional' layout property. I have put together the example hopefully to show what we are experiencing (taken from a real world example).

From the documentation, we can deal with collisions a number of ways. The easiest option appears to be the "text-optional" style; If true, icons will display without their corresponding text when the text collides with other symbols and the icon does not.

We are seeing that symbols/icons are being hidden before the text of symbols disappear. 

It would seem more preferable with this that if the text is colliding with other symbols, and there is the chance that by removing the text of a symbol both icons could remain, it would be ideal. 

We would hope then that the icon is still shown if there is no room for the text. 

I hope this helps identify the use case. We are just hoping to treat text as fully optional, as it would be super slick. If I need to adjust the example, let me know. If I have mis-interpreted something, hopefully this post can give some other people some clarity.

**mapbox-gl-js version**: 0.15.0

### Steps to Trigger Behavior

 1. Visit: http://codepen.io/cammanderson/pen/qZddLX
 2. Slowly zoom back out and watch the icons / text behaviour

### Expected Behavior

1. As slowly zooming out, "Fergana Valley" text should disappear (text-optional, icon should remain), and "Osh" should be present still (with text, as there is room)
2. As continuing to zoom out, as "Sharizabh" text collides with "Smarkland", the "Smarkland" text should disappear and just have an icon
3. As continuing to zoom out, "Fergana Valley" text collides with "Tash Rabat", text for one should disappear leaving the icon (correct), but continuing to zoom out, the icons should remain, and text should disappear from the symbols

### Actual Behavior

1. When you scroll out, instead of "Fergana Valley" text disappearing, it causes the other symbol to disappear completely
2. When the symbol/icon comes up below the text of "Smarkland", "Sharizabh" disappears completely instead of the "Smarkland" text disappearing.
3. The text causes most of the other symbols to be removed without ever removing itself or reducing to an icon

**Comment by lucaswoj** [comment]
Thanks for the report @cammanderson! This looks like a bug. A proper test for `text-optional` is _long_ overdue https://github.com/mapbox/mapbox-gl-test-suite/issues/2.

**Comment by cammanderson** [comment]
OK great, glad to help. :-) if you would like me to create some more test data let me know.

**Comment by cammanderson** [comment]
Just adding to the behaviour being observed; it appears that text hitting text will cause one of the text elements to disappear as anticipated, but when text hits an icon from another symbol, that hit symbol with the icon is disappearing.

I think when the text hits another icon, that text should disappear.

**Comment by ansis** [comment]
Thanks for the clear report and example.

This behavior is expected based on the way labeling is currently implemented. `text-optional` doesn't prioritize icons over text. It just lets an icon be shown even if text can't.

Text that appears in an earlier feature still has priority over an icon in a later feature. For example, Fergana Valley is placed before Osh. When Fergana Valley is placed it doesn't collide with anything so both text and icons are shown. When Osh is placed it's icon collides with Fergana Valley's text. Osh can't go back and change Fergana Valley's placement so it hides both the icon and text.

There is currently no way prioritize icons over text.

**Comment by cammanderson** [comment]
Hi @ansis, 

Thanks for getting back to me. I understand your explanation for what limitation there is in the implementation. The effect though I feel renders the label placement a little unpredictable and maybe less intended than I had hoped. 

Is there a possibility of a 2-pass implementation if text-optional is set true? Place the icons first then again try and place the labels? That would offset the need to modify an existing placed element and probably open up this behaviour to be a little more as intended? 

I would consider trying to do this as 2 layers and offset this to be a decision of the developer (e.g. performance etc), but currently layers don't share any way to detect collisions with other features on other layers.

Any suggestion would be great. 

Thanks
Cameron

**Comment by ansis** [comment]
I agree that this would be a good thing to support.

> Is there a possibility of a 2-pass implementation if text-optional is set true? Place the icons first then again try and place the labels?

Yes, at some point.

I don't see us revising the collision algorithm or related properties soon though. It's a lot of work and there are so many other things that need to be done. I created a new issue to keep track of all the collision algorithm suggestions for when we have time to revisit the algorithm: https://github.com/mapbox/mapbox-gl/issues/14

Unfortunately I don't see a way to work around this problem in the short term.
