### ISSUE TITLE
Create an example of "searching" for features in vector tiles

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2215]
I've seen this question pop up a couple times recently ([1](http://stackoverflow.com/questions/35114740/how-to-search-vector-layer-features-in-mapbox-gl-js), [2](https://github.com/mapbox/mapbox-gl-js/issues/2132)). It seems ripe for an example!

cc @tristen @lyzidiamond @danswick @ConorCoakley

**Comment by lucaswoj** [comment]
Whoops. This was already done in #2202

**Comment by lucaswoj** [comment]
On further thought, this is a separate use case. What I'd like to see is an example that

 - loads a couple hundred POIs with unique names
 - displays the POIs on the map, with their names, as symbols on the map
 - allows users to filter those POIs on the map by name by typing into a text box

Behind the scenes, the example would use `featuresIn` to get all the features in the current viewport, filter them using some custom logic, and use `setFilter` to show/hide by id. There are more sane ways to do this for GeoJSON data but it'd be nice to make this functional on vector tiles too.

**Comment by lyzidiamond** [comment]
Described a potentially-similar workflow to a user here: https://secure.helpscout.net/conversation/173132145/51942/

**Comment by lucaswoj** [comment]
This has been done now. 🎉
