### ISSUE TITLE
Need to detect when GL is finished painting after addLayer() is called

### ISSUE THREAD

**Issue by peckjon** [mapbox/mapbox-gl-js#2218]
https://github.com/mapbox/mapbox-gl-js/issues/826 provides a way to detect when a map first finishes loading.

However, there can also be a significant gap between when map.addLayer() is called and when all shapes in that layer are fully rendered, especially for complex/dense shapes.

Can an event or callback be added to detect this?

**Comment by peckjon** [comment]
Incidentally, I thought I could get at this by waiting for the GL context to finish rendering, but `(map.getCanvas().getContext('webgl') || map.getCanvas().getContext('experimental-webgl')).finish();` does not appear to block (I may be using it wrongly?)

**Comment by jfirebaugh** [comment]
Yes, we're tracking this in #1715, with additional discussion in #1904.
