### ISSUE TITLE
Custom symbol (icon) not displaying on Chrome mobile (Android)

### ISSUE THREAD

**Issue by martinmaillard** [mapbox/mapbox-gl-js#2219]
I created a custom style in Mapbox Studio and use Mapbox-GL (0.11.0) to display it on a web page. This style includes custom SVG icons that I added to the sprite in Mapbox Studio.

I use this symbol to display GeoJSON data on the map, like in [this example](https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/).

Everything is displayed properly on desktop browsers, but if I access the page on Chrome on an Android phone, the symbols are not displayed. I know the features are on the map because I can click on them (they are interactive), but they are invisible.

**Comment by lucaswoj** [comment]
Thanks for the bug report @martinmaillard. Could you provide a link to a demo that uses the style and icons in question? My hunch is that there's something wrong with the `@2x` assets.

**Comment by martinmaillard** [comment]
I think I might have found the cause of this issue. I use bower to manage front-end dependencies and the last version of mapbox-gl on bower is 0.11.0. The issue seems to be fixed with 0.15.0 so I guess I will have to switch to the npm package.

**Comment by martinmaillard** [comment]
Is there no plan to officially distribute the package on bower?

**Comment by jfirebaugh** [comment]
@martinmaillard Correct. Please use the Mapbox CDN, the npm package, or tarballs from the [releases page](https://github.com/mapbox/mapbox-gl-js/releases).

**Comment by lucaswoj** [comment]
ref https://github.com/mapbox/mapbox-gl-js/issues/1342
