### ISSUE TITLE
Tile number can't display on satellite style

### ISSUE THREAD

**Issue by mayagao** [mapbox/mapbox-gl-js#2223]
**mapbox-gl-js version**:

0.15.0
### Steps to Trigger Behavior

With satellite style, turn on tile boundaries
### Expected Behavior

Display tile numbers just like on other styles
### Actual Behavior

Tile numbers can't display correctly

![screen shot 2016-03-04 at 8 48 32 am](https://cloud.githubusercontent.com/assets/5186564/13533580/ed078388-e1e5-11e5-9c58-7cac4ac79c2e.png)

**Comment by lucaswoj** [comment]
bug confirmed, here's a functioning [demo](http://jsbin.com/mitepazese/edit?html,output)

**Comment by lucaswoj** [comment]
Some context

 - this bug exists as far back as f06c3e53d6278542ef296050b90540c6aa27a1b7 (first included in v0.14.1)
 - before f06c3e53d6278542ef296050b90540c6aa27a1b7, debug labels don't render on the satellite map at all

**Comment by lucaswoj** [comment]
If I fix the bug causing debug labels to not render before f06c3e5, then I see that this bug seems to have been introduced in 250a50056a1a0ec63fcaf1ab608727c5048cc400

**Comment by lucaswoj** [comment]
@ansis Any ideas on why this would break iff there is a raster layer present?

**Comment by ansis** [comment]
@lucaswoj I think it's because raster tiles are 256 instead of 512? which makes [this hack]( https://github.com/mapbox/mapbox-gl-js/blob/61ca1c8bcfa24d38439e97ef0192cdac9e508081/js/render/draw_debug.js#L44) wrong and also makes everything smaller.

**Comment by lucaswoj** [comment]
Just confirmed that this bug is still present in `master` 😞
