### ISSUE TITLE
Iterate on GitHub issue labels

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2227]
GitHub issue labels are one of the best tools we have to manage the growing issue traffic in this repository. Below is a plan for an iterative improvement to our existing label structure, aiming to make it simpler and more useful.  

I'll leave this issue open until everyone has had a chance to weigh in. If we decide to go forward with this plan, I will document the final structure in `CONTRIBUTING.md` and do a pass over all open issues to ensure they have proper labels.

![rwn-wallstore-1](https://cloud.githubusercontent.com/assets/281306/13581567/67ad48de-e45c-11e5-91ce-b563d78b2b50.jpg)
(it's a bike shed)

I have a gut feeling that the value of our labels is inversely proporional to how many labels we have. Additionally good labels are

 - **objective** any two people with the same amount of context would agree on a labeling decision
 - **useful** a label tracks state or captures semantic meaning that would otherwise be hard to search for

cc @ansis @tmcw @mourner @jfirebaugh @bhousel @mcwhittemore @lyzidiamond @danswick 

## Labels

Labels are organized into categories. Each category has a color. 

### Actionable Status (red)

* needs clarification
* needs discussion
* in progress

### Non-Actionable Status (grey)

* blocked internally
* blocked externally 
* won’t fix
* duplicate
* support request

### Type (blue)

* bug report
* feature request

### Topic (purple)

* perspective
* testing
* release process
* examples
* documentation
* mapbox.js parity
* performance
* browser compatibility

### Difficulty (green)

* starter task

### Importance (orange)

* release blocker

## Labels to be Removed

I propose we do away with these labels because they are vague or not useful for issue organization. I erred on the side of removing labels that I was unsure about.

* api
* blue sky
* help-wanted
* internal
* needs C++ port
* needs port from C++
* rendering
* style
* text rendering

**Comment by jfirebaugh** [comment]
I'd like to keep `compatibility` and `performance` as "Project" tags.

`text rendering` is listed twice. I'm fine with removing it.

Is the idea that an issue should have exactly one of the "Actionable Status" or "Non-Actionable Status" tags, one "Type" tag, and any number of the other tags as appropriate?

**Comment by lucaswoj** [comment]
> I'd like to keep `compatibility` and `performance` as "Project" tags.

:+1: on keeping `performance`

What is `compatibility` supposed to mean? It has been used to refer to

 - browser compatibility
 - build system compatibility
 - compatibility with other coordinate systems
 - GeoJSON spec compatibility

> text rendering is listed twice. I'm fine with removing it.

:+1: done

> Is the idea that an issue should have exactly one of the "Actionable Status" or "Non-Actionable Status" tags, one "Type" tag, and any number of the other tags as appropriate?

Exactly.

**Comment by mourner** [comment]
I'm :+1: on everything including John's remarks. Maybe @ansis will need one-two more project tags for some ongoing stuff like 3d/perspective... Also, maybe we need more "Difficulty" tasks, e.g. to indicate a very complicated hard to solve task involving many steps (a lot of these are "bluesky" now).

**Comment by lucaswoj** [comment]
> Also, maybe we need more "Difficulty" tasks, e.g. to indicate a very complicated hard to solve task involving many steps (a lot of these are "bluesky" now).

I'm not so sure about adding a "very difficult" label. What is difficult enough to be very difficult? I think "starter task" is relatively objective.
