### ISSUE TITLE
data not being filtered by setFilter() calls in v0.15.0

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#2228]
**mapbox-gl-js version**: 0.15.0

### Steps to Trigger Behavior
example case [here](https://jsfiddle.net/gjpeyewd/1/)
 1. load point dataset into studio 
 2. set above dataset as a layer on Basic map style
 3. try and filter said data using `map.setFilter()` in a GL script
 4. you can see the correct behavior if you switch to v. 0.14.0 of mapbox-gl-js in the jsfiddle

### Expected Behavior
dataset is filtered following invocation of `map.setFilter()`
### Actual Behavior
data remains unchanged

**Comment by lucaswoj** [comment]
I can confirm there's something incorrect happening in v0.15.0

However, I'm having trouble reproducing the _correct_ behavior in `v0.14.0`. When I set a filter that should hide all circles, they all still appear. 

```js
map.setFilter('main', ['in', 'Source','how much wood would a woodchuck chuck']);
```


http://jsbin.com/fuhiwebida/edit?html,output
