### ISSUE TITLE
map.setFilter('layer1', [somefilter]) will affect other layers with the same data source if they are not visible in saved studio style

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#2229]
**mapbox-gl-js version**: 0.14.0 (problem might exist in 0.15.0 too, but #2228 prevents testing)

### Steps to Trigger Behavior

 1. load 2 separate layers with the same data source in a studio map, set one of the layers to opacity 0
 2. filter visible layer in using gl-js using `map.setFIlter()`
 3. check filter of both layers using `map.getFilter()`-- you will see that the filter has been applied to the second layer erroneously

example [here](https://jsfiddle.net/gjpeyewd/3/)

### Expected Behavior
`map.setFilter()` only applies filter to the layer specified in the first argument
### Actual Behavior
`map.setFilter()` will affect other layers with the same data source if they are set to opacity 0 in studio

**Comment by jfirebaugh** [comment]
The style specifies that the `main` layer is a `ref` layer which references the `hover` layer. Reference layers share their `filter` property (among others) with the parent layer. `setFilter`, when called on a ref layer, sets the filter of its parent layer. This isn't documented, and should be, but otherwise this behavior is by design. If you don't want the filter to be linked, change the `main` layer not to use `ref`.

**Comment by mollymerp** [comment]
Interesting. Thanks, @jfirebaugh -- maybe this is a studio bug then, because I never designated it as a `ref` layer in studio and I can't find any controls that allow me to remove the `ref` designation.

**Comment by lucaswoj** [comment]
I'm not seeing any actionable follow-ups here. The `ref` property is clearly documented [here](https://www.mapbox.com/mapbox-gl-style-spec/#layer-ref). Let's turn this into an upstream issue on Studio.

**Comment by tmcw** [comment]
This isn't really a bug in Studio: we automatically create refs whenever layers can have refs - creating a UI that lets you pick & choose refs would introduce a ton of complexity for little benefit.

I think the long-term goal is **making refs automatic in GL JS**. We have the code to detect ref'able cases in Studio and could port it. This is a performance optimization that leaks through to valid usecases and is hard to diagnose: I do not think it should be exposed to users at all.

**Comment by lucaswoj** [comment]
> I think the long-term goal is making refs automatic in GL JS. 

I'm totally on board with this idea. Tracking in https://github.com/mapbox/mapbox-gl-js/issues/1393

**Comment by jfirebaugh** [comment]
I agree too. And I think if we make refs solely an implementation detail of the renderer, we should make `setFilter` behave as @mollymerp expected, i.e. have `setFilter` on a layer that's internally a ref effectively break the reference and turn them into two independent layers.

**Comment by mollymerp** [comment]
^ sounds good to me. thanks for clarifying this !
