### ISSUE TITLE
Rename `layer` option to `layers` for featuresIn/At requests

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#2230]
I've seen this come up a couple times where someone has typed `layers` instead of `layer` in the property options for `featuresAt` or `featuresIn` requests. If the typo is not caught the effect is elusive (_appears_ to sort of work as the layer you want is captured in the request but buggy as it captures others)

Propose:

- `layer` continues to accept a single string value or an array of strings
- `layers` accepts an array of strings

**Comment by lucaswoj** [comment]
> someone

:+1: I've done this many times.

**Comment by tmcw** [comment]
:-1: rename to layers, require an array of strings as an argument. One true way.

**Comment by averas** [comment]
I agree with @tmcw.

**Comment by peterqliu** [comment]
Agree with `one true way`, though should we continue to support the singular form, to avoid a breaking change?

**Comment by jfirebaugh** [comment]
Let's support an array-valued `layers` property only, as part of #2052 / #2224, which are already breaking changes.

cc @ansis
