### ISSUE TITLE
Document or remove any event that can be fired by "Map"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2232]
There are many events that we fire but don't consider part of our public API. Many users are using these events despite them being undocumented. We should consider prefixing these events with an `_`, like a private method, to discourage their use.

**Comment by lucaswoj** [comment]
The biggest offender is `style.load`. I see a lot of uses of the undocumented `style.load` where `load` should have been used. I suspect many people started using `style.load` as a workaround for #2042.

**Comment by jfirebaugh** [comment]
I'd be fine with publicly documenting `style.load` and pretty much all the `*.*` events.

**Comment by tmcw** [comment]
Agree with @jfirebaugh, if an event isn't public, we shouldn't emit it.

**Comment by lucaswoj** [comment]
:+1: Makes sense. I adjusted the issue title to reflect this approach.

**Comment by lyzidiamond** [comment]
Here is a list of all of the events that are undocumented and where they live in the code. Some of them may be undocumented intentionally and the link I put here may not be the canonical link. Tell me which should be documented and which should be removed!

- `'error'`: https://github.com/mapbox/mapbox-gl-js/blob/b7032636206448e16eb681836f97e79f0587fd7e/js/style/image_sprite.js#L28
- `'touchstart'`: https://github.com/mapbox/mapbox-gl-js/blob/fc4568df71bddfe2fa2c5f7b3fe37c2cc511226f/js/ui/interaction.js#L42-L45
- `'touchmove'`: https://github.com/mapbox/mapbox-gl-js/blob/fc4568df71bddfe2fa2c5f7b3fe37c2cc511226f/js/ui/interaction.js#L42-L45
- `'touchend'`: https://github.com/mapbox/mapbox-gl-js/blob/fc4568df71bddfe2fa2c5f7b3fe37c2cc511226f/js/ui/interaction.js#L42-L45
- `'touchcancel'`: https://github.com/mapbox/mapbox-gl-js/blob/fc4568df71bddfe2fa2c5f7b3fe37c2cc511226f/js/ui/interaction.js#L42-L45
- `'tile.error'`: https://github.com/mapbox/mapbox-gl-js/blob/81f7959743dbaf84a35334795640389e04c1b349/js/source/vector_tile_source.js#L87
- `'tile.load'`: https://github.com/mapbox/mapbox-gl-js/blob/81f7959743dbaf84a35334795640389e04c1b349/js/source/vector_tile_source.js#L98
- `'tile.stats'`: https://github.com/mapbox/mapbox-gl-js/blob/81f7959743dbaf84a35334795640389e04c1b349/js/source/vector_tile_source.js#L99
- `'tile.add'`: https://github.com/mapbox/mapbox-gl-js/blob/81f7959743dbaf84a35334795640389e04c1b349/js/source/vector_tile_source.js#L108
- `'tile.remove'`: https://github.com/mapbox/mapbox-gl-js/blob/81f7959743dbaf84a35334795640389e04c1b349/js/source/vector_tile_source.js#L112
- `'change'`: https://github.com/mapbox/mapbox-gl-js/blob/d6c34c81f7b0d6e77f1b25c2c080a3c5afba94ab/js/source/geojson_source.js#L98
- `'pitch'`: https://github.com/mapbox/mapbox-gl-js/blob/9846a4f6d54bd09dfba5c655c56e11d4484458f9/js/ui/camera.js#L369
- `'render'`: https://github.com/mapbox/mapbox-gl-js/blob/2028b482ab7492fd4cfc4a3ec5772f353890219b/js/ui/map.js#L861

**Comment by bhousel** [comment]
Wow thanks @lyzidiamond!  I can help with this..

I just added the `touch*` events within the past few days, and they are documented, that code just hasn't made it into a release yet.

**Comment by lyzidiamond** [comment]
@bhousel ah yes, i saw the doc comments in the code and was confused as to why they weren't showing in the docs! Comment above updated.

**Comment by lyzidiamond** [comment]
@bhousel also I'm happy to add the doc, just need to know which ones to document!

**Comment by lyzidiamond** [comment]
A bunch more here, including the `source.*`, `layer.*` and `tile.*` events. I'm not sure where to find the `style.*` events. https://github.com/mapbox/mapbox-gl-js/blob/2028b482ab7492fd4cfc4a3ec5772f353890219b/js/ui/map.js#L508-L527

**Comment by lucaswoj** [comment]
> I'm not sure where to find the `style.*` events.

The `style.` prefix is added (here)[https://github.com/mapbox/mapbox-gl-js/blob/2028b482ab7492fd4cfc4a3ec5772f353890219b/js/ui/map.js#L922]

Style events are fired throughout the `js/style/style.js` file. For example, `style.load` is fired as `load` (here)[https://github.com/mapbox/mapbox-gl-js/blob/2028b482ab7492fd4cfc4a3ec5772f353890219b/js/style/style.js#L63]

**Comment by andreasplesch** [comment]
As somebody who did some ol3, I was actually looking for map generated events and was wondering if there were any because they are not in listed in the API documentation. In particular, I was looking for an event which is fired whenever a render is completed. map#render seems to fit. It would be great if these events could be documented, even if very briefly. Otherwise adopters will just try to find them in the code. Even a list of available events without documentation (such as above) is very helpful.
(Is there a canonical way to sync across two map canvases ?)

**Comment by lyzidiamond** [comment]
@lucaswoj @bhousel @jfirebaugh any idea which of the events i listed should have doc and which should be removed? Happy to hit this once I know which is which.

**Comment by lucaswoj** [comment]
Of the events listed, I think we should document `render` and `error`. I don't have any strong opinions about the rest.

**Comment by jfirebaugh** [comment]
I think these should all be documented except for `tile.stats`, which is an internal performance diagnostic thing.

**Comment by lucaswoj** [comment]
I think we should clean up our events architecture by doing the following things:

 - [ ] document `error`
 - [x] document `touchstart`
 - [x] document `touchmove`
 - [x] document `touchend`
 - [x] document `touchcancel`
 - [ ] merge `tile.error` with `error`
 - [ ] remove `tile.load` in favor of `data`
 - [ ] remove `tile.stats` in favor of `data`
 - [ ] remove `tile.add` in favor of `data`
 - [ ] remove `tile.remove` in favor of `data`
 - [ ] remove `source.change` in favor of `data`
 - [ ] document `pitch`
 - [ ] document `render`
 - [ ] implement and document `data` and `dataend` (ref https://github.com/mapbox/mapbox-gl-js/issues/1715#issuecomment-209069733)

**Comment by lucaswoj** [comment]
Split up remaining subtasks into

 - https://github.com/mapbox/mapbox-gl-js/issues/2448
 - https://github.com/mapbox/mapbox-gl-js/issues/2447
 - https://github.com/mapbox/mapbox-gl-js/issues/2446
 - https://github.com/mapbox/mapbox-gl-js/issues/1715

**Comment by lucaswoj** [comment]
Revisiting this at a high level. Now that #3244 has landed we have better visibility into our events: 

# Events fired in GL JS

 - `boxzoomcancel`
 - `boxzoomend`
 - `boxzoomstart`
 - `click`
 - `close`
 - `contextmenu`
 - `dblclick`
 - `drag`
 - `dragend`
 - `dragstart`
 - `error`
 - `geolocate`
 - `load`
 - `mousedown`
 - `mousemove`
 - `mouseout`
 - `mouseup`
 - `move`
 - `moveend`
 - `movestart`
 - `pitch`
 - `remove`
 - `render`
 - `resize`
 - `rotate`
 - `rotateend`
 - `rotatestart`
 - `source.change`
 - `source.load`
 - `style.change`
 - `style.load`
 - `tile.add`
 - `tile.load`
 - `tile.remove`
 - `touchcancel`
 - `touchend`
 - `touchmove`
 - `touchstart`
 - `webglcontextlost`
 - `webglcontextrestored`
 - `zoom`
 - `zoomend`
 - `zoomstart`

# Events Documented in GL JS

 - `boxzoomcancel`
 - `boxzoomend`
 - `boxzoomstart`
 - `click`
 - `close`
 - `contextmenu`
 - `dblclick`
 - `drag`
 - `dragend`
 - `dragstart`
 - `error`
 - `geolocate`
 - `load`
 - `mousedown`
 - `mousemove`
 - `mouseout`
 - `mouseup`
 - `move`
 - `moveend`
 - `movestart`
 - `pitch`
 - `render`
 - `rotate`
 - `rotateend`
 - `rotatestart`
 - `touchcancel`
 - `touchend`
 - `touchmove`
 - `touchstart`
 - `webglcontextlost`
 - `webglcontextrestored`
 - `zoom`
 - `zoomend`
 - `zoomstart`

# Events Fired but not Documented

 - `remove`
 - `resize`

## Events to be Merged into the `data` Event

 - `source.change`
 - `source.load`
 - `style.change`
 - `style.load`
 - `tile.add`
 - `tile.load`
 - `tile.remove`
