### ISSUE TITLE
Create automated testing of example pages and debug pages

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2240]
We should add automated testing for the [`mapbox-gl-js` examples](https://www.mapbox.com/mapbox-gl-js/examples) and [example code in the `mapbox-gl-js` api docs](https://www.mapbox.com/mapbox-gl-js/api/).

@tmcw suggested using [getsentry](https://getsentry.com/welcome/). We can explore a couple different options. 

cc @tristen

**Comment by lucaswoj** [comment]
> As this relates to a question around making sure our code documentation doesn't break between versions though, I think there should be a head's up on a version bump by ccing collaborator in a pr for each release with changelog notes cited.

I encourage you to open a separate ticket or, better yet, a PR against `RELEASE.md` about this.

**Comment by lucaswoj** [comment]
Run each of these until the first map render and ensure no exceptions are thrown

 - a new debug page using a webpack build (#2933 #1649)
 - all examples
 - all debug pages

This would ensure we don't break any examples or demo pages as GL JS improves. These tests need not be run every commit but should at least be run before releases.

**Comment by mourner** [comment]
Not feasible at the moment.
