### ISSUE TITLE
Replace "marker" with "point" in examples

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#2241]
And set up any necessary redirects. 

I think the general consensus is to refer to the geometry type it is in GeoJSON and start moving away from calling it a "marker".

cc @lucaswoj @tmcw @lyzidiamond @samanpwbb @danswick @jfirebaugh

**Comment by lyzidiamond** [comment]
Love this.

**Comment by peterqliu** [comment]
>I think the general consensus is to refer to the geometry type it is in GeoJSON

Let's say I make a geojson, and visualize it on a map. If someone comes and says, *"remove that point"*, do they mean removing it from the map visualization, or removing the point feature from the geojson source?

**Comment by jfirebaugh** [comment]
⇢ #2809
