### ISSUE TITLE
Improve visual organization of examples

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2242]
I'm excited that our collection of examples is growing! 

The sidebar navigation is getting unwieldy. Let's brainstorm some ways to make the examples easier to navigate. [`mapbox.js` groups the examples under subheadings](https://www.mapbox.com/mapbox.js/example/v1.0.0/).

<img width="235" alt="screen shot 2016-03-10 at 11 03 54 am" src="https://cloud.githubusercontent.com/assets/281306/13680971/d2bee628-e6af-11e5-8b46-664ca56d07a0.png">

cc @tristen @lyzidiamond @danswick

**Comment by danswick** [comment]
Yessssss thanks for getting this rolling, @lucaswoj!

If we were to follow the Mapbox.js template and go with section headings, my first instinct for headings would be: 

- Camera
- Dynamic styling 
- Adding and manipulating data
- User interaction 

Lots of examples fall under multiple categories, so we might also consider some kind of UI to filter the list by multiple tags. I've always wanted that for Mapbox.js, but it is nice to have all of them in one place.

**Comment by lucaswoj** [comment]
Just a note: this would solve some major pain points during our first mapbox-gl-js usability testing session

**Comment by tristen** [comment]
cc'ing @tatsvc into this conversation. Yes the sidebar is breaking but I think the way we present our documentation as a whole could use a facelift.

**Comment by lucaswoj** [comment]
Perhaps it'd be best to structure our examples more like our [gallery](https://www.mapbox.com/gallery/) or [d3's gallery](https://github.com/d3/d3/wiki/Gallery), with filtering by tag (GeoJSON source, interactivity, etc)

**Comment by mollymerp** [comment]
I don't think having a gallery view for the examples would improve ease of user navigation. The examples mostly use mapbox-streets so it would be hard to distinguish what the example is showing bc they would mostly look very similar. I do think filtering could be helpful though!

**Comment by tmcw** [comment]
Yep, we've had exactly this conversation with Mapbox.js, and Tristen even implemented a gallery view, and it came up with the same conclusion as @mollymerp points out; the content does not fit that format.

**Comment by lyzidiamond** [comment]
Closed in #3181!
