### ISSUE TITLE
filterEmptyBuckets breaks reloadSymbolData

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2244]
https://github.com/mapbox/mapbox-gl-js/blob/352eb64e7a232c52919186c407845af0b951190d/js/source/worker_tile.js#L191
https://github.com/mapbox/mapbox-gl-js/blob/352eb64e7a232c52919186c407845af0b951190d/js/source/tile.js#L97

`oldBucket` is undefined if the bucket used to be empty and was filtered out by `filterEmptyBuckets`. Trying to call destroy on undefined will error.

If a bucket is filtered out in the current set of results but was present in the last one, it won't get removed from `this.buckets` and we will render stale symbols.

cc @lucaswoj

**Comment by lucaswoj** [comment]
My fault. I even left this helpful comment. :grimacing: 

```// TODO rewrite this```

**Comment by lucaswoj** [comment]
I'm not sure how to trigger an error using this fault. Can you make a demo using this jsbin @ansis? http://jsbin.com/kavitapesi/1/edit?html,output
