### ISSUE TITLE
Automatically create GitHub Release on CI server during release

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2251]
ref #2017 

It would make releases easier and safer if we created GitHub releases automatically on the CI server.
- [ ] parse CHANGELOG.md for updated tests (bonus points for linting CHANGELOG.md for version correct numbers, dates, etc)
- [ ] attach build artifacts to GitHub release to allow package managers like bower to use mapbox-gl-js #1342 
- [ ] add GitHub token to CI server

**Comment by mourner** [comment]
I highly prefer to handcraft the changelog as a draft in the releases interface, and move it to the changelog after, rather than the other way around.
