### ISSUE TITLE
text and symbol collision when symbols are from custom tileset

### ISSUE THREAD

**Issue by jamescartifact** [mapbox/mapbox-gl-js#2254]
text labels and symbols overlap despite all relevant layers being set with:
- avoid edges: true
- allow overlap: false
- padding: 20px

text labels are from mapbox streets (places)
symbols are a custom tileset. does not appear to occur with mapbox streets based point symbols.

![screen shot 2016-03-10 at 8 25 33 pm](https://cloud.githubusercontent.com/assets/17776358/13693272/43fd28b0-e6fe-11e5-9790-979577449d01.png)

**Comment by jfirebaugh** [comment]
Thanks for the report! As you discovered, cross-source label placement / collision detection is not yet supported. The tracking ticket for that is #1042.
