### ISSUE TITLE
tile edges visible in polygon layer (buildings

### ISSUE THREAD

**Issue by jamescartifact** [mapbox/mapbox-gl-js#2255]
tile boundaries are showing up running through polygons (in our case buildings)
tile splits not present in native dataset, definitely coming from mapbox rendering
data was uploaded using studio classic to customize zoom extent (but used in studio)

in mapbox
![screen shot 2016-03-10 at 8 36 08 pm](https://cloud.githubusercontent.com/assets/17776358/13693455/2bd43fce-e700-11e5-9905-99c806038d94.png)

in qgis
![screen shot 2016-03-10 at 8 36 15 pm](https://cloud.githubusercontent.com/assets/17776358/13693456/2cbdd9a4-e700-11e5-9cfc-b63af20e9de8.png)

**Comment by mourner** [comment]
Did you set the buffer size in Mapbox Studio Classic options when uploading the data?

**Comment by jamescartifact** [comment]
gosh, duh. thank you.
