### ISSUE TITLE
Request : Add Built-in Marker Transitions

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#2258]
Feature Request:
In markers we should be able to set two properties in the point's geojson: nextPosition and timeToTransition :
- nextPosition is a coordinates array
- timeToTransition is a time in milliseconds
And then when I do source.setData with a feature collection, it will transition the markers automagically.
In this way I only have to do setData one time per second and not 30 times per second, and the update can be done in webgl and not js which I suppose would be faster
Maybe add a third property like transitionStyle (for example 'ease-in' or 'linear').
That would be a killer feature.

**Comment by lucaswoj** [comment]
Thanks for the feature request @misterfresh! 

>  In this way I only have to do setData one time per second and not 30 times per second, and the update can be done in webgl and not js which I suppose would be faster

This would not be possible without a significant refactoring of our codebase. We have decided to make `setData` the primitive for animation. There is an ongoing effort to make `setData` more efficient in #1391 and #1504.
