### ISSUE TITLE
Remove GlyphAtlas debug mode

### ISSUE THREAD

**Issue by haoshengfucn** [mapbox/mapbox-gl-js#2261]
mapboxgl crashed when i debug the GlyphSource. the code as these:(glyph_source.js)
    var glyphAtlas = new GlyphAtlas(512, 512);
    glyphAtlas.debug=true;
    this.atlases[fontstack] = glyphAtlas;

by the way ,is there a online geojson data source site?

**Comment by bhousel** [comment]
> glyphAtlas.debug=true;

Yeah this doesn't work.  We should probably remove the debug flag and the related code.

If you want to look at the atlas textures, you're better off using a real webgl inspector tool like https://benvanik.github.io/WebGL-Inspector/
