### ISSUE TITLE
loaded geojson tiles have `isUnloaded` set to true

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2265]
GeoJSON tiles are unloaded whenever they are loaded/reloaded. This sets `isUnloaded` to true, which prevents symbol data from being reloaded after placement is redone.

https://github.com/mapbox/mapbox-gl-js/blob/2b809ddaf3be1547dd485a2d968f0cc9efbf4fd1/js/source/geojson_source.js#L188

**Comment by lucaswoj** [comment]
I suspect this was fixed with the tile state improvements in https://github.com/mapbox/mapbox-gl-js/pull/2847
