### ISSUE TITLE
SetStyle on map with multiple layers

### ISSUE THREAD

**Issue by Iam-jegan** [mapbox/mapbox-gl-js#2267]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Initially load map with several layers(each layer has circles of different radius) and with a basic style
 2. After it has been loaded, change the style of the map to anyother style using setStyle method.
 3. map changes it style and layers drawn previouly are gone. 

### Expected Behavior
I need to retain the layers and just to change the map style

### Actual Behavior
layers are no more adn i couldn't able to get it.

**Comment by ryanbaumann** [comment]
When you change the map style using setStyle(), are you replacing it with a Mapbox://<streets-v8> vector tile reference?

SetStyle() replaces all of the layers and styles on a map with a new set of layers and styles - in the case above, the entire map will be set to "streets-v8" and all existing layers will be replaced.

There are two solutions I've used.

1) Prior to SetStyle(), call map.getStyle() which returns the current map and layer information all in one object.  Use the getStyle result to create a new map instance, or manipulate the style to fit your needs.

2)First use map.getLayer() and map.getSource() to parse out the layers and sources currently defined in your map.  Then use map.SetStyle().  Finally add the sources and layers back to your map.

It would be convenient if there were a method to only replace the "basemap" styles and layers.  Thoughts?

**Comment by Iam-jegan** [comment]
Absolutely it will be convenient if there is an option to just change the basemap styles and layers.

Thanks,
Jegan

**Comment by lucaswoj** [comment]
Unlike Leaftlet, mapbox-gl-js doesn't have a concept of "basemap" vs "other layers." All layers are part of the same entity, the style. You will have to find another way to achieve your desired functionality. 

I encourage you to ask about that on StackOverflow rather than this issue tracker. This issue tracker is reserved for feature requests and bug reports only.

**Comment by emakarov** [comment]
definitely, in a dynamic applications changing styles of base map indirectly is required

**Comment by emakarov** [comment]
meanwhile I'm experimenting with manual satellite layer manipulation. I think manual layers manipulation can be key to solution, i.e.
`
      map.addSource("mapbox-satellite", {
         "type": "raster",
         "url": "mapbox://mapbox.satellite",
         "tileSize": 256
      });

      map.addLayer({
         "type": "raster",
         "id": 'satellite-map',
         "source": "mapbox-satellite"
      });
`

**Comment by emakarov** [comment]
I found the solution by manual switching layers of base map (now works for lightv9 scheme)
so, 
1) I init the map with light-v9
2) I take raw data of light v9 from here https://raw.githubusercontent.com/mapbox/mapbox-gl-js/8f0475e66822a79d8a1ddfc8031c4733373c7d07/debug/light-v9.js
3) Then, idea is manually turning on and off all layers from light-v9:
`
map.addSource("mapbox-satellite", {
         "type": "raster",
         "url": "mapbox://mapbox.satellite",
         "tileSize": 256
      });


  map.base_layers = lightv9.layers;

  map.hide_base_layers = function() {
    for (var v in map.base_layers) {
        map.setLayoutProperty(map.base_layers[v]['id'], 'visibility', 'none');
    }
  }
  map.show_base_layers = function() {
    for (var v in map.base_layers) {
        map.setLayoutProperty(map.base_layers[v]['id'], 'visibility', 'visible');
    } 
  }

  map.turnOnSatellite = function() {
      map.addLayer({
         "type": "raster",
         "id": 'satellite-map',
         "source": "mapbox-satellite",
         "opacity": 0.6
      }, 'lowest_device_layer');
      map.hide_base_layers();
  }

  map.turnOffSatellite = function() {
     map.removeLayer('satellite-map');
  }
`

**Comment by emakarov** [comment]
it will be good if we could have a standard method of map in API to get all layers of "base map"

**Comment by aabhishekbindal** [comment]
I saw that this has been an issue for many people now. Has @mapbox team found a solution to this? or a direct way on how I can change the base map keeping the other layers intact?

Regards,
Abhishek

**Comment by emakarov** [comment]
@aabhishekbindal  see my solution described above. it works and easy
I did it for switching between basic map and satellite map
