### ISSUE TITLE
Allow the use of special characters in property field names

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2271]
... except "{" and "}"

Should require a one line change to https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/token.js#L14

ref https://github.com/mapbox/mapbox-gl-style-spec/issues/419
ref https://github.com/mapbox/mapbox-gl-native/issues/4336

**Comment by musicformellons** [comment]
@lucaswoj Curious: when can I expect this to be implemented in mapbox gl js?

**Comment by lucaswoj** [comment]
@musicformellons I'll make this change right now and 🚢 it in the next release
