### ISSUE TITLE
Add a transition effect to setFilter

### ISSUE THREAD

**Issue by Iam-jegan** [mapbox/mapbox-gl-js#2273]
I would like to do some animation while filters are being applied on layers. For example, I have 2 layers with circles drawn of different radius on some geo points. While I switch from one layer to other layer by setting filters using setFilter(), I want the transition on circle opacity for a smooth transition.

Please assist

**Comment by lucaswoj** [comment]
I don't foresee us getting around to this feature any time soon but I love the idea! As always, external contributions are welcome.

**Comment by jfirebaugh** [comment]
Closing; implementing this in core would be awkward given our rendering and worker architecture, and you can implement this effect in user code by transitioning opacity manually, and then changing the filter.
