### ISSUE TITLE
Design a protocol to diagnose and fix machine-specific bugs

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2274]
We need to develop a protocol for dealing with rendering problems that only occur on specific machines.
### Goals
- identify systems that do not have the specifications to render `mapbox-gl-js` and close those issues
- identify patterns across systems that have rendering problems, with the eventual goal of diagnosing and fixing the underlying problem
### Potential Solutions
- write a standard set of troubleshooting steps to help users with configuration problems
- add a `mapboxgl.diagnostics()` method #2078
- develop a standard protocol for collecting diagnostics from `chrome://flags`, etc

cc @lyzidiamond @jfirebaugh @ansis @tmcw @mourner

**Comment by jfirebaugh** [comment]
The pattern that has worked for me is: purchase physical hardware matching the reported issue, and debug it. Not sure there's much actionable here beyond that.
