### ISSUE TITLE
Move buffer stats to a separate debug page 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2281]
![screen shot 2016-03-17 at 11 44 28 am](https://cloud.githubusercontent.com/assets/281306/13857120/b94566fa-ec35-11e5-9fb9-f0d06ab3cb5d.png)

I want to keep the `index.html` debug page simple. "debug" and "collision debug" modes can stay.

**Comment by mourner** [comment]
That would be great! I'd also remove the random points geojson and leave only the route one.

**Comment by bhousel** [comment]
Worth mentioning - I was thinking of adding an "events debug" too.

I don't mind having buffer stats there.  Honestly I'd prefer to have all the debug things consolidated in one control rather than spread across different pages - but no strong opinion on this.

**Comment by lucaswoj** [comment]
I often use `debug/index.html` to build ephemeral testing "rigs". For that use-case, having a simple page possible is ideal (i.e. `new mapboxgl.Map(...)` and nothing else). 

Some testing rigs are worth checking in and reusing, like "buffer stats." Keeping those rigs on separate pages

 - frees us from having to build and maintain any enable / disable UI
 - frees testing rigs from having to "play nicely" with other rigs on the same page, allowing more "radical" setups (i.e. `require`ing and manipulating internal modules directly or displaying custom UI elements)
 - scales infinitely with the number of testing rigs we create

**Comment by mourner** [comment]
I agree with @lucaswoj — when I'm debugging a particular feature, I'll usually start by removing everything but the barebones code from `site.js` and start from there. It's cumbersome to do every time, so having a nice default simple debug page would be a time saver.

**Comment by bhousel** [comment]
Wouldn't it be better if the debugging things were contained in a `Control` like:

```js
map.addControl(new mapboxgl.Debug({position: 'top-left'}));
```

I agree `index.html` and `site.js` ideally shouldn't have this extra code.

**Comment by mourner** [comment]
-> #3596
