### ISSUE TITLE
Create a UI debug control

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2290]
We should consider adding a `mapboxgl.DebugControl` class which adds UI controls for toggling "tile debug" and "collision debug" modes (and future debug capabilities).

ref https://github.com/mapbox/mapbox-gl-js/issues/2281#issuecomment-198377911
ref https://github.com/mapbox/mapbox-gl-js/pull/2284#issuecomment-198347063

cc @bhousel @mourner @jfirebaugh @ansis

**Comment by lucaswoj** [comment]
I feel mildly :-1: towards this proposal on the grounds that

 - we should add as little debugging code to the distributed `mapbox-gl.js` as possible
 - toggling `tileDebug` and `collisionDebug` is easy from the console 
 - users who are likely to find `tileDebug` and `collisionDebug` useful are likely to be designers within the Studio interface or developers comfortable using the console

**Comment by mourner** [comment]
I don't see the need for a dedicated control — a debug page and ability to use console are enough.

**Comment by bhousel** [comment]
Then why open an issue for it??  Just to tell me my idea sucks?

In the amount of time we have discussed it, I probably could have built the damn thing.   I did most of a geolocation control yesterday in like 2 hours.

This is nuts.

**Comment by mourner** [comment]
> Then why open an issue for it?? Just to tell me my idea sucks?

Not at all! I'm sorry it looked that way. :panda_face: We open an issue for any improvement idea to have our decisions documented and easily searchable. Sometimes this can be an overkill, but we all make mistakes sometimes. :heart:
