### ISSUE TITLE
Refactor "SourceCache"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2291]
The `SourceCache` class could use a big refactor (maybe even a ground-up rewrite) to
- simplify and fix bugs in our wrapped tile retention system #1834
- simplify our tile caching system to make it easier to reason about
- create a cleaner API (the class currently includes some overly-complex methods, surprising side effects, and too-long argument lists)
- improve testability 
- move all code that isn't related to tile caching into separate modules 

ref #2287

**Comment by jfirebaugh** [comment]
I think we should wholly revert the relationship inversion between `Source` and `TilePyramid`/`SourceCache`. Judging by the resulting complex coupling, this seems to have been an architectural mistake.

**Comment by anandthakker** [comment]
@jfirebaugh can you say more about this?  I agree that the current coupling is not ideal, but it's not clear to me that inverting the dependencies would really eliminate it.  Would another way to improve this might be to clarify and simplify the Source interface?

**Comment by mourner** [comment]
Closing as too vague — we should create new issues for any specific things we can improve.
