### ISSUE TITLE
Ignore "holes" in query*Features collision detection

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2293]
Polygon holes don't need to be indexed:
https://github.com/mapbox/mapbox-gl-js/blob/158227693667b2e7d6cfa2a7e5822c7d5ad81d30/js/data/feature_tree.js#L68

**Comment by mourner** [comment]
@ansis Can you clarify this — why would we ignore holes in polygons?

**Comment by ansis** [comment]
We don't need to index holes because the ring containing the hole is indexed. After looking up features in the index we use the actual geometry (including holes) to make sure the intersection is real.

But we should remove this comment. We can't (with v1 tiles) know whether something is a hole right now, and even then I don't think it would be significant.

**Comment by mourner** [comment]
> We can't (with v1 tiles) know whether something is a hole right now

We can because we rely on v2 tiles since switching to Earcut. E.g. here https://github.com/mapbox/mapbox-gl-js/blob/master/src/util/classify_rings.js

**Comment by ansis** [comment]
Right, of course! I'd guess that skipping the hole is still not really worth it
