### ISSUE TITLE
Verify WebGL contexts have the context attributes we require

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2295]
https://www.khronos.org/registry/webgl/specs/latest/1.0/#2.1

According to the spec, `getContext` can return a context with different attributes than the ones you requested. See `contextAttributes` vs `actualAttributes` in the spec. We should check that `gl.getContextAttributes()` matches what we expect.

I'm not sure when this would happen, or if this would happen, but it could cause some hard-to-debug bugs.

**Comment by mourner** [comment]
This hasn't surfaced as a problem so far, so I think we can close for now.
