### ISSUE TITLE
Efficiently moving a single marker

### ISSUE THREAD

**Issue by Overv** [mapbox/mapbox-gl-js#2296]
All of the examples update the GeoJSON and completely recreate the markers from that when they move a point.

Is there a more efficient way to move a single marker when there are a lot of markers in the GeoJSON?

Or would writing a custom WebGL marker overlay be the best way of going about this?

*Context: I'm developing a public transit visualization application and I need move about 100 out of 5000 markers per second efficiently. Reloading the GeoJSON causes too noticeable of a stutter, even when buffering all the updates for a second.*

**Comment by mourner** [comment]
> Reloading the GeoJSON causes too noticeable of a stutter

Can you try the latest master version? There were related speedups.

We're investigating ways to improve this use case with #1504 and https://github.com/mapbox/geojson-vt/issues/26.

**Comment by Overv** [comment]
The problem is pretty much solved in the latest master version, thanks!

**Comment by mourner** [comment]
Great! Closing then.

**Comment by daumann** [comment]
@Overv what was the solution to your problem? Do you retile all data for every dataupdate?

**Comment by Overv** [comment]
@daumann My solution was to not use mapbox-gl-js and instead use https://github.com/eJuke/Leaflet.Canvas-Markers (and fork it over at https://github.com/Overv/Leaflet.Canvas-Markers).
