### ISSUE TITLE
Replace `style.load` with `load` in code documentation

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#2297]
Use `load`. `style.load` is used internally. https://github.com/mapbox/mapbox-gl-js/search?l=html&q=%22style.load%22&type=Code&utf8=%E2%9C%93

**Comment by lucaswoj** [comment]
Let's close this until we've made some high-level decisions in https://github.com/mapbox/mapbox-gl-js/issues/2232. If you think we should make `style.load` private, please speak up in that thread.
