### ISSUE TITLE
Vector tiles from latest node-mapnik do not play well with earcut

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2298]
Since I know you guys are working hard to start using earcut in <code>master</code> and I also know that you are working on the vector tile spec and the related implementations in mapnik I wanted to share something I ran into when upgrading node-mapnik in my vector tile stack from <code>3.4.16</code> to <code>3.5.2</code>. I've been using a rebased version of <code>earcut-final</code> for the past couple of months and it works good. Given my use case (lots of polygon fills) it's more or less a necessity for performance.

For the examples below I'm using the exact same data, and I reset my tile cache between the tests, and I've tried going back and fourth and the same issue occurs every time. I know that <code>earcut</code> is sensitive to polygon ring winding orders, but as I said the data does not change at all, only mapnik and mapbox-gl-js versions do.

node-mapnik 3.4.16 with <code>earcut</code> and 3.5.2 with mapbox-js-gl 0.15.0:
![working](https://cloud.githubusercontent.com/assets/1205805/13904510/a4f24f54-eea3-11e5-8426-de94f84e59ba.gif)
 
node-mapnik 3.5.2 with <code>earcut</code> (watch islands (holes) and relief):
![broken](https://cloud.githubusercontent.com/assets/1205805/13904513/bc7c16aa-eea3-11e5-8387-c295e024ec5e.gif)

cc. @mourner @lucaswoj @springmeyer @jfirebaugh @ansis

**Comment by mourner** [comment]
What Earcut version do you use? Can you try the latest one?

**Comment by averas** [comment]
@mourner I'd love to, if you help me with the latest rebase! There are currently conflicts too low level for me to be able resolve.

**Comment by mourner** [comment]
@averas can you try with a non-rebased version? Just installing the latest earcut with `npm install earcut@2.1.1`

**Comment by averas** [comment]
Ah yes, that solved it! Sorry I didn't think of it myself!

**Comment by mourner** [comment]
@averas a very pretty map by the way! Can't wait for it to go live online. :) Could be a nice map to show on the Mapbox gallery.

**Comment by averas** [comment]
@mourner Thanks! I'm actually wrapping things up as we speak.. It's a spare time project I've been working on for a while now and I'm making heavy use of mapbox so I will definitely let you know when I go live.

Check out https://youtu.be/GYfkZNuyCJE and https://youtu.be/xYSsC6ji4II to see in in context!

**Comment by averas** [comment]
Btw. @springmeyer I got similar results (watch the missing piece of the polygon up to the left) using the latest published node-mapbox-gl-native package (<code>3.0.2-earcut</code>), probably also from depending on an older version of earcut. If I force install <code>3.0.2</code> it looks fine.

![missing polygon](https://cloud.githubusercontent.com/assets/1205805/13908611/7fa9716a-ef06-11e5-9bc4-45a287fda9e2.png)
