### ISSUE TITLE
Polygon rendering artifacts on Chrome + Windows 7

### ISSUE THREAD

**Issue by timiyay** [mapbox/mapbox-gl-js#2300]
During a demo on our client's laptop, our polygon features had major artifacts (screenshots attached). These artifacts were occurring at all zoom levels, though the shape of the artifacts would vary _between_ zoom levels.

**mapbox-gl-js version**: 0.14.1

### Steps to Trigger Behavior

Note: we are yet to repro this issue on any other machine - the client has a fairly-rare config of running Windows 7 natively on Mac hardware.

 1. Export polygon layer from PostGIS to GeoJSON
 2. Create vector MBtiles using `tippecanoe`
 3. Upload MBtiles to Mapbox
 4. Load map on laptop with following specs:
    * Macbook Pro
    * with NVIDIA GeForce FT 650M graphics card
    * running Windows 7 natively (no VM)
    * running Chrome 49.0.2623.87
 5. Display polygon layer

### Expected Behavior

Features render correctly
![expected](https://cloud.githubusercontent.com/assets/1470250/13909342/72b438e6-ef65-11e5-9393-471a152545c8.png)

### Actual Behavior

Features are 'whack'
![actual](https://cloud.githubusercontent.com/assets/1470250/13909351/8dfd5f7e-ef65-11e5-9119-13c1500a6eb4.png)

**Comment by timiyay** [comment]
Just had the same issue arise for a different client:

* OS: Windows 10
* Browser: Chrome 49

**Comment by timiyay** [comment]
Further attempts to reproduce today. Tried on 5 different machines, and only managed to reproduce the bug on 1 of them.

The biggest thing I found out was that the bug is _only_ happening in Google Chrome. I was unable to test older versions of the browser, but version 49.0.2623.87, and the current Canary build, all exhibited the bug described above.

The bug did _not_ occur on Firefox, Internet Explorer 11, or Microsoft Edge on the same machines.

Here's an updated, partially-complete summary of specs for the machines experiencing the rendering bug:

<table>
	<tr>
		<td>Model</td>
		<td>OS</td>
		<td>Graphics Card</td>
	</tr>
  	<tr>
  		<td>HP ProBook 450 G1</td>
  		<td>Windows 8.1 x64</td>
  		<td>
  			AMD Radeon HD 8600/8700M
  			<br>
  			Driver: 14.100.0.0
  		</td>
	</tr>
  	<tr>
  		<td>HP 15" model unknown</td>
  		<td>Windows 10</td>
  		<td>
  			AMD Radeon R5 M330
  			<br>
  			Driver: 15.201.1101.0
  		</td>
	</tr>
  	<tr>
  		<td>Macbook Pro 15"</td>
  		<td>Windows 7 (native install, not VM)</td>
  		<td>NVIDIA GeForce FT 650M</td>
	</tr>
</table>

I'll update this table as I can get my hands on more Windows machines, or when I can get more-detailed specs from the clients.

If you think there's any other specs (CPU, RAM, 32 vs 64-bit browser, etc) that could help, please let me know.

**Comment by mourner** [comment]
@timiyay on the affected machine, can you try:

- the latest `master` branch
- `earcut-final` branch

**Comment by timiyay** [comment]
@mourner Thanks for the suggestion.

I'll deploy alternative versions of our app, using the branches you suggested. Once I can access one of the affected machines again, I'll see if it helps matter.

It's a very obscure bug, only seems to be occurring with rare blends of MapboxGL, Chrome, and certain graphics cards.

**Comment by mourner** [comment]
@timiyay `earcut-final` branch (#1606) is very likely to fix the bug, since it fully changes the way we render polygons (currently it's kind of a hack). However it may have it's own rendering artifacts too until we complete the switch to full vector tile spec v2 compliance when generating vector tiles on the server, which is currently in final stages.

**Comment by timiyay** [comment]
@mourner ok, sounds hopeful. I dig it. Thanks for the background.

On a related note: I'm creating most of my vector tiles with `tippecanoe`. Should I anticipate changes in how I create my vector tiles, to confirm with the v2 spec?

Happy to move that conversation / question elsewhere, if it's already happening...

**Comment by mourner** [comment]
> Should I anticipate changes in how I create my vector tiles, to confirm with the v2 spec?

Tippecanoe was already updated to conform with the VT2 spec. There are still some rare bugs to flesh out (e.g. https://github.com/mapbox/tippecanoe/pull/187) but you're generally all set.

**Comment by timiyay** [comment]
@mourner

Happy to say that `earcut-final` fixed my issue.
Current `master`at 8c31cfa did _not_ fix the issue.

Thanks for the help. We'll be basing off `earcut-final` until we see https://github.com/mapbox/mapbox-gl-js/pull/1606 land, which'll be awesome. Any gotchas to be aware of for `earcut-final`?

Thanks again mate

**Comment by mourner** [comment]
@timiyay you may experience rare polygon artifacts in certain cases. The branch will be fully safe to use with our main VT sources like Mapbox Streets/Terrain and any new data you upload within a week or two. Full migration of all VTs including old ones will be a matter of a few months, after which we'll merge the branch. Until that happens, we're rebasing the branch from time to time so that people who need it can use it today.

**Comment by timiyay** [comment]
Currently working through a gotcha for basing off `earcut-final`, unfortunately.

It looks like `earcut-final` was recently rebased off v0.16.0. This did 2 things:  

1. deleted the commit hash `9369d5` we were referencing in our `package.json`...
2. ...which forced us to upgrade to `mapbox-gl-js` v0.16.0

While I've nothing against upgrading, it appears that `mapbox-gl-draw` does. It fails to install:

```
npm ERR! peerinvalid The package mapbox-gl@0.16.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mapbox-gl-draw@0.4.0 wants mapbox-gl@^0.13.1 || ^0.14.0 || ^0.15.0
```

In hindsight, I should've forked `mapbox-gl-js` to prevent this. Hopefully this acts as a cautionary tale for others.

**Comment by mourner** [comment]
Whoa, is the hash actually deleted when rebasing? I thought it would still be available. Thanks for the heads up.

**Comment by timiyay** [comment]
@mourner No problems, I didn't expect it either.

I think my issue will be solveable by using an RC for `mapbox-gl-draw`, and I'm going to use my own fork for now.

**Comment by lucaswoj** [comment]
Earcut has shipped! 🎉

**Comment by timiyay** [comment]
noice. I'll be jumping on that, as soon as the npm release is out. Good stuff folks!
