### ISSUE TITLE
Raster hillshading + complex vector fills creates kaleidoscope effect.

### ISSUE THREAD

**Issue by dpieri** [mapbox/mapbox-gl-js#2304]
**mapbox-gl-js version**: 0.15.0 (also tested on local master build current to to [b26c036](https://github.com/mapbox/mapbox-gl-js/commit/b26c0367dd5d57e3f855d59b4a0542fb7b970340) to see if [2236](https://github.com/mapbox/mapbox-gl-js/issues/2236) fixed this issue. 

**[Example](https://jsbin.com/vuqerolama/1/edit?html,output)**. I've added buttons to turn on and off the complex vectors so you can see how they interact with the hill shading.

### Steps to Trigger Behavior

 1. Make a map that uses both raster hillshading and complex vector fill patterns.
 2. Zoom in on an area covered by a complex vector pattern.
 3. Try a few times because this does not happen 100% of the time

### Expected Behavior
Map zooms and styles as you'd expect.
<img width="510" alt="screen shot 2016-03-21 at 1 57 54 pm" src="https://cloud.githubusercontent.com/assets/539310/13933975/f2cf79bc-ef6c-11e5-9dcd-567bd7e540ce.png">

### Actual Behavior
At larger zooms (> 12) the raster layer switches to a strange kaleidoscope effect and moves above all the vector layers. There are also some other less common artifacts like flashing or hill shading and ground cover disappearing in areas that are covered in a vector pattern after you zoom out again.

I've observed this on multiple browsers and hardware configurations.

<img width="848" alt="screen shot 2016-03-21 at 1 55 18 pm" src="https://cloud.githubusercontent.com/assets/539310/13933932/bb42f5aa-ef6c-11e5-800f-b0ade2d13afc.png">

**Comment by ansis** [comment]
@dpieri Thanks for the great test case! https://github.com/mapbox/mapbox-gl-js/pull/2307 should fix this. Can you confirm?

**Comment by dpieri** [comment]
Confirmed, that fixes it! That was incredibly fast @ansis. Thank you! :pray:
