### ISSUE TITLE
Fix buffer artifact around videos

### ISSUE THREAD

**Issue by FredFunk** [mapbox/mapbox-gl-js#2309]
In Chrome browser notice in the 'Add a video' example there is a buffer artifact along southern border. This same issue is causing a shift in our video tile registration. Seems OK in Firefox.

https://www.mapbox.com/mapbox-gl-js/example/video-on-a-map/

![1](https://cloud.githubusercontent.com/assets/7557766/13952360/7931da1e-f00c-11e5-8c0b-4eb8ea0ca713.jpg)

**Comment by lucaswoj** [comment]
I am not able to reproduce this on my MacBook Pro running Chrome.

**Comment by jfirebaugh** [comment]
Closing; this is likely a browser issue which we'll be unable to fix in Mapbox GL JS itself.
