### ISSUE TITLE
improve documentation for sources in GL API & style ref

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#2315]
I discovered when working on #2305 that there is not clear documentation regarding sources with respect to adding layers to a style through the API. Specifically, adding a source to a background layer throws an error and causes some weird rendering results, but there is nothing in the documentation that indicates this. 

I will take a stab at this and then come back for :eyeglasses:

**Comment by lucaswoj** [comment]
This should be done within `mapbox-gl-style-spec` 

--> https://github.com/mapbox/mapbox-gl-style-spec/issues/433
