### ISSUE TITLE
Animation in the vertex shader

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#2317]
I'm trying to animate markers from the shader. The idea is to call source.setData only once per second to change markers positions, and then manage the transition between positions from the shader which means it will be computed in the GPU.

So I copied icon.fragment.glsl into animatedicon.fragment.glsl and icon.vertex.glsl into animatedicon.vertex.glsl . Then I added animatedicon in js/render/shaders.js and also in js/render/painter.js : setup

Now what I'd like to do : 
1) send a uniform lowp float u_completion to the animatedicon.vertex.glsl.
u_completion would be equal to (currentTime - AnimationStartTime)/1000 , so it's between 0 and 1and measures the progression of the animation.

2) have previous position available as a vertex attribute vec2 a_previous_pos in animatedicon.vertex.glsl.
Then in the main function of  animatedicon.vertex.glsl I could do 
`vec2 current_pos = vec2(a_previous_pos[0] + (a_pos[0] - a_previous_pos[0]) * u_completion, a_previous_pos[0] + (a_pos[0] - a_previous_pos[0]) * u_completion);`
 
My blocking points is that I'm not sure how to send this new data to the vertex shader, and also I'm not sure how to trigger a refresh, because when I call drawSymbol() manually from a closure the whole map flashes.

**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1.
 2.
 3.

**Comment by jfirebaugh** [comment]
Sorry, we can't offer support for mapbox-gl-js outside the boundaries of the public API. You are customizing the code at an extremely low level, and will need to work out these issues on your own.

**Comment by misterfresh** [comment]
Just to follow-up, I experimented a bit with this, and it seems to work well. The animation is butter-smooth even with hundreds of markers. What was a bit long was to pass on the next_position coordinates from the feature to vertex attribute (had to edit symbol_bucket.js).

**Comment by mourner** [comment]
@misterfresh this sounds pretty cool, can you show us a demo?

**Comment by misterfresh** [comment]
I'll try to put something online in the coming days. I did exactly as described above, the only thing that is long is to pass around the next_position values through all the rendering steps.

**Comment by misterfresh** [comment]
@jfirebaugh @mourner  here's a working demo : a commuting simulation [hardware accelerated mapbox gl js animation](http://misterfresh.github.io/mapbox-gl-js-animation-example/)  (to start/stop press the top-left button)

**Comment by mourner** [comment]
@misterfresh not working for me — the map is empty and the console says: `bundle.min.js:1 GET http://misterfresh.github.io/mapbox-gl-js-animation-example/external/sprites/sprite@2x.json 404 (Not Found)`

**Comment by misterfresh** [comment]
I did not test it on a high resolution device.

**Comment by misterfresh** [comment]
@mourner can you try again? it should work on all devices now

**Comment by misterfresh** [comment]
@jfirebaugh @mourner  Turns out the magical option was icon-overlap, now you can actually see the hundreds of markers moving on the screen. The number of vehicles starts small and gradually increases with time so it’s only after about a minute that the numbers get impressive. [http://misterfresh.github.io/mapbox-gl-js-animation-example/](http://misterfresh.github.io/mapbox-gl-js-animation-example/)

**Comment by misterfresh** [comment]
I published the unminified code with an easy-to-use API for markers animation in the following repo : 
[mapbox animation](https://github.com/misterfresh/mapbox-animation)

**Comment by ebrensi** [comment]
Hello, I'm looking into this functionality for a project I'm working on.  I realize this is an old issue so can someone tell me, is the method described here still relevant, or are there newer better ways to do custom animation of a lot of sprites now?
