### ISSUE TITLE
Create links between API docs and examples

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2318]
It'd be amazing to have links between our API docs and examples.

For example, the `addSource` API docs should link to https://www.mapbox.com/mapbox-gl-js/example/vector-source.

cc @mollymerp @lyzidiamond @jfirebaugh @ansis @mourner @tristen @bhousel

**Comment by lucaswoj** [comment]
Capturing from Slack conversation: 

 - implementing these links via `@see` tags allows us to seperate the presentation and content of these links
 - implementing these links via `@see` tags creates minimal boilerplate
 - implementing these links via `@see` tags is semantically correct via the JSDoc specification 
 - `@see` tags are supported by documentation.js per https://github.com/documentationjs/documentation/issues/9 (but not included in default themes) 
 - `@see` tags are exposed to the theme by a [`sees` property](https://github.com/documentationjs/documentation-schema/blob/master/input.js#L37) 
 - `sees` is an array of Markdown AST objects (generated by [remark](https://github.com/wooorm/remark) per the [unist specification]( https://github.com/wooorm/unist))
 - Markdown AST objects can be rendered to HTML by the [`md` helper](https://github.com/documentationjs/documentation/blob/master/default_theme/index.js#L55) 
```
<% sees.forEach(function(see) { %><li><%= md(see) %></li><% } %>
```

cc @jfirebaugh @mapsam @captainbarbosa

**Comment by mapsam** [comment]
Thanks @lucaswoj - @captainbarbosa has a good start over at https://github.com/mapbox/mapbox-gl-js/tree/example-links-nb

**Comment by captainbarbosa** [comment]
This has been done in #3185! 🎉
