### ISSUE TITLE
fix queryRenderedFeatures box across dateline

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2321]
**mapbox-gl-js version**: 8b52b55251b4d63bc6713d76c8314c1f1007f04a

### Steps to Trigger Behavior

 1. query a full screen box at zoom 0

### Expected Behavior

Returns all features.

### Actual Behavior

Returns a subset of features based on the wrapped coordinates of the box corners.

**Comment by ansis** [comment]
If you are zoomed out and there are multiple copies of a polygon, should queryRenderedFeatures return a feature for every instance visible on the screen? Or should it return only one feature?
<img width="943" alt="screen shot 2016-03-23 at 1 56 34 pm" src="https://cloud.githubusercontent.com/assets/1421652/14000605/1fc555fc-f0ff-11e5-974a-3f6c433cfc07.png">

**Comment by mcwhittemore** [comment]
@ansis I'd expect it to only return one. It is returning the features not the renderings. If you update one of them the other will move.

**Comment by ansis** [comment]
@mcwhittemore great. It'll return one

This is fixed by https://github.com/mapbox/mapbox-gl-js/commit/c418867f2ff419921dc8619a61b9b09a4d7efd95

**Comment by mcwhittemore** [comment]
@ansis :+1: Should we close this?
