### ISSUE TITLE
Support {lng, lat} objects in LngLat#convert

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2322]
https://github.com/mapbox/mapbox-gl-js/blob/master/js/geo/lng_lat.js#L84-L85

we should also add errors for invalid input

cc @jfirebaugh @ansis

**Comment by mourner** [comment]
Did you mean "{lng, lat}" instead of {x, y}?

**Comment by lucaswoj** [comment]
Oops, yes, I was conflating `Point` and `LngLat`

**Comment by lucaswoj** [comment]
ref https://github.com/mapbox/point-geometry/issues/3

**Comment by mourner** [comment]
BTW [Leaflet does that too](https://github.com/Leaflet/Leaflet/blob/master/src/geo/LatLng.js#L79), so it's nice to have parity here.

**Comment by yappel** [comment]
I think this issue can be closed. It was [implemented](https://github.com/mapbox/mapbox-gl-js/blob/master/src/geo/lng_lat.js#L89) in #3232.

If there is something missing that needs to be implemented, I'd be happy to look into it, but it seems all work on this issue is already done.

**Comment by jfirebaugh** [comment]
Thanks for pointing that out @yappel!
