### ISSUE TITLE
setting multiple filters dynamically

### ISSUE THREAD

**Issue by divya1c** [mapbox/mapbox-gl-js#2323]
**mapbox-gl-js version**: v0.15.0

### Steps to Trigger Behavior

 1. Try to set multiple filters using setFilter.
```
var new_Filter = ["all",["==", 'damage', 0],[">=", 'senior_population', 20]];
map.setFilter('terrain-data-layer', new_Filter);
```

### Expected Behavior
The filters should be applied and the map should show area with damage == 0 and senior_population >= 20.

### Actual Behavior
The map shows area with senior_population >= 20.

I also logged out the filter before and after setting the filter and it seems like the filter is set properly. But, I do not see changes in the display of the map.

**Comment by peterqliu** [comment]
@divya1c can you provide a test case?

**Comment by divya1c** [comment]
Hi @peterqliu 

I had a map with terrain-data-layer-damage0 layer, and a toggle for applying a new filter.
```
var filter_damage = ["==", 'damage', 0];
map.addLayer({
    'id': 'terrain-data-layer-damage0',
    'interactive': true,
    'type': 'fill',
    'source': 'terrain-data',
    'source-layer': 'mylayer',
    'paint': {
        'fill-color': '#a0e89b',
        'fill-opacity': 0.7
    },
    'filter': filter_damage
  });

var filterButton = document.getElementById("filter");
filterButton.onclick = function(e) {
  e.preventDefault();
  e.stopPropagation();

    var filter_map = map.getFilter('terrain-data-layer-damage0');
    console.log(JSON.stringify(filter_map));
    var new_Filter = ["all",["==", 'damage', 0],[">=", 'senior_population', 20]];
    console.log(JSON.stringify(filter_map));
    map.setFilter('terrain-data-layer-damage0', new_Filter);
  }
}

```

**Comment by peterqliu** [comment]
@divya1c hmm that should work. can you provide the test case in https://jsfiddle.net/?

**Comment by divya1c** [comment]
Hi @peterqliu , I was adding a layer somewhere else in my code. That was interfering with my results. Fixed it now :) Thanks a lot for the replies.
