### ISSUE TITLE
Cluster source and 'circle' layers don't return correct features on mouseover of varying circle radiuses

### ISSUE THREAD

**Issue by weareboxhead** [mapbox/mapbox-gl-js#2324]
Hello,

Without setting an incredibly large radius value in the 'featuresAt' method, is there any other way to make the entire circle (of any given size) hoverable? I would expect it to work in a similar way to how polygon layers work as mousing over any area within a random shape this causes the featuresAt event to return a 'feature'.

**mapbox-gl-js version**: 0.15.0

### Steps to Trigger Behavior
Using this example as a starting point (https://www.mapbox.com/mapbox-gl-js/example/cluster/) I have created a GeoJSON source with the clustering options turned on. For each breakpoint/threshold setup (which shows a different sized/coloured circle) I have a unique layer created.

I have then setup a 'mousemove' event on the map canvas and used the 'featuresAt' method set to be active on all the layers with a fixed radius set.

```
var map = new mapboxgl.Map({
				    container: 'map',
				    style: 'mapbox://styles/mapbox/dark-v8',
				    center: [-1.55, 53.79],
            		zoom: 14,
            		minZoom: 12
				}),
					visualLayerIds = [],
					clusterLayerThresholds = [
						[50, '#50e3c2', 22],
						[30, '#50e3c2', 20],
						[20, '#50e3c2', 18],
						[15, '#50e3c2', 16],
						[10, '#50e3c2', 14],
						[5, '#50e3c2', 12],
						[2, '#50e3c2', 10]
					];


                        // Add the cluster source
			map.addSource('cluster-src', {
					type: "geojson",
					data: 'path/to/geojson/data',
					cluster: true,
					clusterMaxZoom: 14, // Max zoom to cluster points on
					clusterRadius: 5 // Radius of each cluster when grouping points
				});

				// Add cluster grouping circle layers
				clusterLayerThresholds.forEach(function (layer, i) {
					map.addLayer({
						"id": "cluster-" + i,
						"type": "circle",
						"source": "cluster-src",
						"paint": {
							"circle-color": layer[1],
							"circle-radius": layer[2]
						},
						"interactive": true,
						"filter": i == 0 ?
							[">=", "point_count", layer[0]] :
							["all", 
								[">=", "point_count", layer[0]],
								["<", "point_count", clusterLayerThresholds[i - 1][0]]
							]
					});

					// Add this visual layer ID to the array
					visualLayerIds.push("cluster-" + i);
				});

				map.on('mousemove', function (e) {
					map.featuresAt(e.point, {
						radius: 22,
						layer: visualLayerIds
					}, function (err, features) {
					        map.getCanvas().style.cursor = (!err && features.length) ? 'pointer' : '';
					});
				});

```

### Expected Behavior
I would expect mousing over any part of the circle (no matter it's size/radius) to trigger the correct feature to be returned by the featuresAt method.

### Actual Behavior
The correct feature is only returned when mousing over the center of the circle up to the given radius set on the radius property of the 'featuresAt' method. Mousing over the edges of a circle whose radius is set to be larger than the radius set for featuresAt fails to return the feature.

**Comment by lucaswoj** [comment]
As it is implemented, `featuresAt` does not consider style properties, such as `circle-radius`, in hit-testing. 

This will be fixed by `queryRenderedFeatures` #2224, merging soon!
