### ISSUE TITLE
"Featuresat" appears in the example list

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#2330]
![image](https://cloud.githubusercontent.com/assets/98601/14035453/88f4a0b8-f1eb-11e5-8e38-aaacbf6ed91e.png)

This is a redirect to "Get features under the mouse pointer" and should not be displayed in the list.

**Comment by danswick** [comment]
cc @lyzidiamond 

We might want to move the redirect up to `www.mapbox.com` instead of within this project.

**Comment by lucaswoj** [comment]
> We might want to move the redirect up to www.mapbox.com instead of within this project.

That doesn't sound desirable from an organizational standpoint. We should be able to set up gl-js documentation redirects within gl-js.

**Comment by jfirebaugh** [comment]
Removing `category: example` from the front matter of the redirects should fix this.

**Comment by lucaswoj** [comment]
fixed by 32dc6ba
