### ISSUE TITLE
Optimize cascade

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#2339]
One of the causes of #2334 is expensive `style.cascade` calls when doing `Map` `setPaintProperty`, which in turn calls `map.batch`. `cascade` in batch was only needed to fix `text-size` and `icon-size` (#1451) — in all other cases it's unnecessary. In addition, `batch` calls `_update(true)` (causing full style recalculation) which is also unnecessary in most cases.

@ansis want to grab this? [Lines in question](https://github.com/mapbox/mapbox-gl-js/blob/7ca58c020bcb9f3eb3ab9eb8b7d704db9ee2023c/js/ui/map.js#L476-L477).

**mapbox-gl-js version**: 0.16.0

**Comment by jfirebaugh** [comment]
> `cascade` in batch was only needed to fix `text-size` and `icon-size` (#1451) — in all other cases it's unnecessary.

Not sure this is accurate.

**Comment by mourner** [comment]
@jfirebaugh I made this assumption based on your commit comment here https://github.com/mapbox/mapbox-gl-js/commit/1f9029cce00b230ec37f9b7792916f03fc191231:

> This ensures that both result in a recascade, which is necessary due to the status of text-size and icon size as pseudo-paint properties (#1451).

Do we rely on recascade for any other properties now?

**Comment by lucaswoj** [comment]
- `setPaintProperty` modifies `Declaration` objects
 - `cascade` turns `Declaration` objects into `Transition` objects
 - `getPaintValue` reads from `Transition` objects

"pseudo-paint properties" are layout properties that require a cascade.

It is necessary to "cascade" after any paint property OR pseudo-paint property mutation.

**Comment by lucaswoj** [comment]
We may be able to modify cascade to only touch properties that have been changed since the last cascade.

**Comment by mourner** [comment]
@lucaswoj makes sense! I'll look into it.

**Comment by lucaswoj** [comment]
One idea:

 - create an `updatePaintTransition` method which updates a single `Transition` object
 - repurpose / rename `cascade` to `setClasses`, call `updatePaintTransition` in a loop
 - add a call to `updatePaintTransition` in `setPaintProperty`
 

ref #2359

**Comment by mourner** [comment]
@lucaswoj yes, I was thinking along the same lines for this. It's surprising that we update all transition objects when changing only one.

**Comment by jfirebaugh** [comment]
s/setClasses/applyClasses, so there's not an implication that it's a simple setter method.

**Comment by lucaswoj** [comment]
The public API is called [`setClasses`](https://www.mapbox.com/mapbox-gl-js/api/#Map.setClasses).

**Comment by jfirebaugh** [comment]
`Map#setClasses` != `Style#applyClasses`

**Comment by lucaswoj** [comment]
`Map#setClasses` doesn't do much other than calling `Style#_cascade` https://github.com/mapbox/mapbox-gl-js/blob/10f2f2d136a37daffc92f821f4e00d07c9f01f3a/js/ui/map.js#L233

**Comment by jfirebaugh** [comment]
There are other places that call `cascade`. A style cascade is an operation: "calculate the effective set of paint properties based on this list of classes". It's not a setter.
