### ISSUE TITLE
Support for W3C Pointer Events / Trackpad + Touch events don't work on Edge

### ISSUE THREAD

**Issue by nsamala** [mapbox/mapbox-gl-js#2341]
Hello again! Are there any plans to support W3C Pointer Events? When testing our map view on Edge, no gestures to interact with the map via trackpad or a touch screen work. You have to use keyboard shortcuts or onscreen buttons.

**Comment by mourner** [comment]
Yes, we should add support for Edge touch interactions. Closing as a duplicate of #1928.
