### ISSUE TITLE
Remove util.throttle

### ISSUE THREAD

**Issue by bhousel** [mapbox/mapbox-gl-js#2345]
From https://github.com/mapbox/mapbox-gl-js/pull/2337#issuecomment-201432500

>If we throttle, we should throttle with requestAnimationFrame instead of setTimeout 16ms.
>
>frames might take more than 16ms
>chrome aggressively de-prioritizes setTimeout in some cases: #2139 >https://code.google.com/p/chromium/issues/detail?id=567800

**Comment by mourner** [comment]
Or alternatively:

> :+1: to a separate `frameThrottle` util method in `util/browser/browser.js`

It may need a bit of duplicating, but will be more explicit, and better fits `browser.js` since `reqAnimFrame` is a browser API.

**Comment by bhousel** [comment]
D3 uses [clever tricks](https://github.com/mbostock/d3/blob/c36befc7361cd61538294048c387a8a407b65dd1/src/event/timer.js#L8) to throttle their timed events and animation tweens to frame boundaries.

**Comment by ansis** [comment]
`util.throttle` ins't used anywhere. It should have been removed as part of https://github.com/mapbox/mapbox-gl-js/pull/2142

**Comment by bhousel** [comment]
But what we are talking about would be useful for any of the camera `flyTo`/`easeTo`animations.

**Comment by bhousel** [comment]
Updated: `throttle` is not used, so this can be removed
