### ISSUE TITLE
Failed to initialize WebGL - Cordova Crosswalk

### ISSUE THREAD

**Issue by hlehmann** [mapbox/mapbox-gl-js#2348]
**mapbox-gl-js version**: 0.16

I am using cordova with crosswalk making webgl available for hybrid apps.
Crosswalk is based on the latest versions of chromium, and I can use webgl with their sample but on calling mapbox gl I still get "Failed to initialize WebGL".

Here the example using ThreeJS.
https://crosswalk-project.org/documentation/samples/webgl.html

**Comment by hlehmann** [comment]
My bad it was due to chromium GPU blacklist.

You can disabled it with 
`<preference name="xwalkCommandLine" value="--ignore-gpu-blacklist" />`

**Comment by jgauna** [comment]
Anyone experiencing this issue? Using 

```<preference name="xwalkCommandLine" value="--ignore-gpu-blacklist" />```

in the config.xml file is not working and I still see the error message "Failed to initialize WebGL"

Is it safe to use mapboxgl for cordova apps development?

**Comment by eithed** [comment]
It depends - for example, atm I'm seeing the above-mentioned error in Cordova app on a LG K4 (Android 5.1), and green screen on http://mapbox.github.io/mapbox-gl-supported. Samsung J5 (Android 6.0) displays the WebGL correctly. Both are running up-to-date version of WebView (60.0.3112.116)

In theory - it should work fine, however for Android version <5.5 WebGL support isn't working in Cordova WebView, even though it's working in Android WebView.

To get around the issue I've had to:
- install Crosswalk (https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview)
- add `<preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect --ignore-gpu-blacklist" />`
