### ISSUE TITLE
Validate filters passed to queryRenderedFeatures

### ISSUE THREAD

**Issue by OmniEarthDev** [mapbox/mapbox-gl-js#2349]
**mapbox-gl-js version**: v0.16.0

### Steps to Trigger Behavior
queryRenderedFeatures filter is not working as expected as it is returning more features than desired.

1.  See fiddle: https://jsfiddle.net/rraponi/3pznu2ym/

### Expected Behavior
The cursor should change only over the markers that are displayed via
the filter that should only return features with the property of "test" that equal "bar".

 map.on('mousemove', function(e) {
    var features = map.queryRenderedFeatures(e.point, {
      filter: '["==", "test", "bar"]'
    });
    map.getCanvas().style.cursor = features.length ? 'default' : '';
  });

### Actual Behavior
More features are being returned and the cursor change is triggered in unexpected places.

**Comment by mourner** [comment]
It seems to work if you pass JSON as a filter instead of a string. https://jsfiddle.net/3pznu2ym/11/
We should probably throw a meaningful error in the original case.

**Comment by tmcw** [comment]
This seems like a usage mistake, not something that we need a special error for. Providing a string as a filter doesn't work anywhere else in gl-js.

**Comment by lucaswoj** [comment]
We can get meaningful error messages by passing this argument through `validateStyle.filter`, as we do in [other places](https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style_batch.js#L141-L142).

I wouldn't advocate writing a validator just for this case but we already have one and it is free to use!
