### ISSUE TITLE
queryRenderedFeatures returns already deleted features

### ISSUE THREAD

**Issue by BrunoSalerno** [mapbox/mapbox-gl-js#2353]
**Basically is #2177 but with `queryRenderedFeatures`.**

Context
----------

mapbox-gl-js version: 16.0

Expected behavior
-------------------------

When deleting features using setData I expect them not to be shown by `queryRenderedFeatures` (because they don't exist anymore!)

Actual behavior
---------------------

Deleted features still visible with `queryRenderedFeatures`

Js Fiddle: https://jsfiddle.net/brunosalerno/tpus0kv8

Steps to reproduce the behavior (in the fiddle):
-------------------------------------------------------------

Open the console.
Press the Add features button. (adds TWO features)
Press the Remove one feature button THREE times.
Move the mouse over the area where the features were. The hover will detect the missing features.

**Comment by ansis** [comment]
Sorry about the regression! fixed in master
