### ISSUE TITLE
map.addClass issue when "paint" style not visible

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#2357]
**mapbox-gl-js 0.16.0**:

### Steps to Trigger Behavior

 1. Run (Edited for new link) http://jsbin.com/casukehoga/1/edit?html,output and click addClass

### Expected Behavior

Water polygons shown

### Actual Behavior

Nothing shown. if you change the paint fill-opacity to 1, then adding the class works.

**Comment by jfirebaugh** [comment]
Your code has errors: `TypeError: document.getElementBy is not a function`. After fixing those, it works as expected.

**Comment by andrewharvey** [comment]
Sorry I'm having issues with jsbin it looks like it didn't save my latest code as it only saved it half way through editing.

See this one http://jsbin.com/casukehoga/1/edit?html,output

**Comment by jfirebaugh** [comment]
Yes, confirmed this version does not work as expected. Looks like the `fill-opacity` value is not getting recalculated after the `blue` class is applied.

**Comment by andrewharvey** [comment]
I understand what's happening now. When I apply the `blue` class, it still renders the base `paint` + `paint.blue` and because I've defined `paint.blue` before `paint` the `paint`'s `fill-opacity` is overwriting the `paint.blue` `fill-opacity`.

Within the style if I change the order so that the `paint` definition is before `paint.blue` then it works.

**Comment by jfirebaugh** [comment]
The order of `paint` vs `paint.blue` isn't supposed to matter -- I think this is a legitimate bug in mapbox-gl-js.

**Comment by lucaswoj** [comment]
This is occurring because our internal representation of the set of classes applied to a map is [an object, not an ordered array](https://github.com/mapbox/mapbox-gl-js/blob/data-driven-styling/js/ui/map.js#L231). We should refactor to use an ordered array.

**Comment by lucaswoj** [comment]
@mourner Does it make sense to fix this within the PR for #2339? If not, I'll hit this bug as soon as that PR lands.

**Comment by mourner** [comment]
@lucaswoj yes, I can hit this together with #2339. However I'm not sure using an object is the root cause here — the enumerable order of keys can only diverge from the adding order if some keys are deleted from the object, and it doesn't look like the case here.

```js
var classes = {paint: true};
classes['paint.blue'] = true
for (var i in classes) console.log(i);
// paint
// paint.blue
```

**Comment by lucaswoj** [comment]
[The "order" of `classes` isn't preserved because we iterate over `this._paintDeclarations` instead of `classes` in `StyleLayer#_cascade`.](https://github.com/mapbox/mapbox-gl-js/blob/data-driven-styling/js/style/style_layer.js#L205-L210). 

Although we could fix this bug in most cases by iterating over `classes`, using an array for class names would be more robust.

**Comment by mourner** [comment]
@lucaswoj I see now, totally makes sense.
