### ISSUE TITLE
See features combined in cluster on queryRenderedFeatures

### ISSUE THREAD

**Issue by bryanjjohnson** [mapbox/mapbox-gl-js#2358]
This is for Mapbox gl 16.0. Is there a way that I can see what features/markers/circles are inside of a cluster, specifically when I use queryRenderedFeatures on it. Right now, I can only get a point count from it. I have a popup associated with each marker, and would like to be able to aggregate the content together on the popup when the markers are clustered. Is that possible right now?

**Comment by mourner** [comment]
Not possible and unlikely to be implemented any time soon because of technical difficulty. Imagine clustering a few million points — then on the top level, we would have to keep references for hundreds of thousands points for each cluster, which would simply push the browser out of memory. 

It's theoretically possible to keep references to child clusters and then "unwrap" them with a depth-first search, implementing some kind of a paginated API for points inside a cluster, but it's a huge effort to implement and way out of scope for now.

**Comment by gzurbach** [comment]
I found a simple workaround for this issue. I'm using two layers: one visible and one not. There might be a cleaner solution but this seems to work just fine.

**1. Add two sources to the map (one clustered and one unclustered) using the same data**

```js
this.map.addSource('clustered-locations', {
  type: 'geojson',
  data,
  cluster: true
});

this.map.addSource('unclustered-locations', {
  type: 'geojson',
  data,
  cluster: false
});
```

**2. Add two layers to the map: one clustered (visible), and one unclustered (hidden)**

```js
this.map.addLayer({
  id: 'clusters',
  type: 'circle',
  source: 'clustered-locations',
  paint: {
     // customize your clusters here
  }
});

this.map.addLayer({
  id: 'hidden-locations',
  type: 'circle',
  source: 'unclustered-locations',
  paint: {
    'circle-radius': 0 // this makes the layer invisible
  }
});
```

**3. Use the invisible layer when querying for rendered features**

```js
let visibleFeatures = this.map.queryRenderedFeatures({
  layers: ['hidden-locations']
});
```

Hope that helps!

**Comment by wysisoft** [comment]
Isn't the GetClusterLeaves method a quick solution to this problem?

**Comment by baris-cincik** [comment]
As @wysisoft pointed out, GetClusterLeaves is the way to go!

**Comment by 3zzy** [comment]
@wysisoft @baris-cincik, don't you require cluster ID when using getClusterLeaves? In contrast, @gzurbach's solution directly utilises queryRenderedFeatures. However, I'm uncertain about the potential performance cost of rendering all those features, even if they remain hidden.
