### ISSUE TITLE
Replace drone.mp4/webm in the video test with something smaller

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#2361]
[This test](https://github.com/mapbox/mapbox-gl-js/blob/cb305e11d474fb1d30644eacd024def46156da1b/test/js/ui/map.test.js#L705) loads drone video from https://www.mapbox.com/drone/video/drone.mp4 and https://www.mapbox.com/drone/video/drone.webm, which takes around 22 seconds (slow!) and often times out (at least locally). We should find/make a simpler video for the test.

cc @bhousel @lucaswoj

**Comment by ansis** [comment]
I think you can just replace with with an empty array `[]` since the test doesn't actually use the video.
