### ISSUE TITLE
Speed up render tests

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#2366]
Render tests take a big portion of our test time (~9 min), especially after we switched on test coverage with `istanbul`. We could try to significantly speed this up:

1. Run it in two stages — the first generates all actual images, the second runs pixelmatch-powered diffing on all generated images. This allows us to run `istanbul` only on the first stage, speeding up the second one significantly.
2. Run both image generation and diffing in parallel batches with separate node processes (`child_process.fork`), similar to how `tile-reduce` parallelizes work. Since tests are independent, we can get a huge boost this way.

cc @lucaswoj @jfirebaugh

**Comment by ansis** [comment]
It looks like tests are also run serially when they could be run concurrently by bumping up [this number](https://github.com/mapbox/mapbox-gl-test-suite/blob/45066f6e78c780211d9587df2352597e07a197b5/lib/harness.js#L11).

**Comment by mourner** [comment]
@ansis just tried that. For some reason `pngjs` errors out if concurrency is more than 1:

```
/Users/mourner/projects/mapbox-gl-test-suite/node_modules/pngjs/lib/filter.js:213
        pxData.copy(rawData, rawRowLength * y + 1, pxRowLength * y, pxRowLength * (y + 1));
               ^

RangeError: out of range index
    at RangeError (native)
    at Filter._filterNone (/Users/mourner/projects/mapbox-gl-test-suite/node_modules/pngjs/lib/filter.js:213:16)
```

**Comment by mourner** [comment]
@ansis the error is fixed if you upgrade to the latest `pngjs`, however the change makes tests go a lot slower, and some tests fail where they passed earlier. No idea what's going on.

**Comment by springmeyer** [comment]
Noticed also that the tests feel really slow. There is a long pause before the first output shows up (`* skipped text-offset literal-multiline`) and then they progress very slowly. I did some profiling of the node binary that indicates the main even loop is jammed up with synchronous work (which confirms the thoughts above) and the node threadpool is always mostly idle.

Profiling during the long startup pause indicates that `fs.stat` is likely the culprit:

![screen shot 2016-08-09 at 1 41 19 pm](https://cloud.githubusercontent.com/assets/20300/17532963/bacf1416-5e37-11e6-981f-59657dce53b9.png)

Profiling while the tests are running indicates that `setImmediate` may be the culprit leading to lots of slow garbage collection:

![screen shot 2016-08-09 at 1 46 22 pm](https://cloud.githubusercontent.com/assets/20300/17532956/b5a82720-5e37-11e6-8b66-045c35334a1a.png)

**Comment by mourner** [comment]
Spent a lot of time on this and I still don't have a good clue on why this happens. I get a ton of `KeyedStoreIC_Miss` (most of the time is attributed to it) in `node --prof` v8 profile as well, but the stack traces are confusing, although most of them seem to be related to resource loading (tiles, glyphs, icons etc.). 

I also compared runs with and without coverage and the biggest slowdown seems to happen on tests that load a lot of resources (e.g. `text-font/chinese` takes 7s as opposed to 1s without coverage).  

`setImmediate` seems not to be the culprit because replacing it with `setTimeout`/`process.nextTick` and even synchronous versions doesn't affect times.

**Comment by mourner** [comment]
Just found a big offender, submitting a PR now.

**Comment by mourner** [comment]
OK, now I might have a clue about what `Key edStoreIC_Miss` means. I'm digging into istanbul instrumentation generator and seeing if I can patch it to be faster.

**Comment by mourner** [comment]
Well guess what! https://github.com/gotwarlost/istanbul/pull/694

<img src="http://ragefaces.memesoftware.com/faces/svg/fuck-yeah-clean.svg" width="400" />

**Comment by mourner** [comment]
See a test build with the patch here — https://circleci.com/gh/mapbox/mapbox-gl-js/4825 (ignore the failure at the end — needs a minor fix in my PR). It brings `test.sh` time down from 11:00 to 5:27, which should get further down after unit test coverage gets the patch through `tap` -> `nyc`.

**Comment by lucaswoj** [comment]
Incredible work @mourner! I am so excited about this!

**Comment by mourner** [comment]
PR ready at https://github.com/istanbuljs/istanbul-lib-instrument/pull/22, will likely get merged soon. The current `istanbul` module gets deprecated so we'll need to switch to `nyc` for covering render/query tests.

**Comment by mourner** [comment]
I think the times are good enough after #3161 and #3162 — under 6 minutes for `test.sh`. We can revisit later — further speedups (such as parallelization) will be pretty non-trivial.

**Comment by springmeyer** [comment]
Incredible work @mourner 🎉
