### ISSUE TITLE
Draw opaque fill patterns in opaque render pass

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2373]
-js version of https://github.com/mapbox/mapbox-gl-native/issues/182

Patterned fills are currently always drawn in the translucent render pass. We should:
- check if fill patterns are completely opaque when adding them to the `SpriteAtlas`
- return whether they are opaque as part of `SpriteAtlas.getPosition`
- draw patterned fills in the opaque pass if both patterns are completely opaque

**Comment by mourner** [comment]
This probably won't make a noticeable difference to performance in practice, and we didn't pursue this on the native side, so closing.
