### ISSUE TITLE
changing clusterMaxZoom parameter has no affect

### ISSUE THREAD

**Issue by weareboxhead** [mapbox/mapbox-gl-js#2374]
**mapbox-gl-js version**: 0.16.0

### Steps to Trigger Behavior
Add a source and layer to a map using the cluster parameters e.g.

```
map.addSource(cluster-src', {
    type: "geojson",
    data: 'path/to/geojson/source/data',
    cluster: true,
    clusterMaxZoom: 4, // Changing this value seems to have no affect
    clusterRadius: 5
});

map.addLayer({
    "id": "cluster-layer",
    "type": "circle",
    "source": "cluster-src",
    "paint": {
        "circle-color": "#ff2255",
        "circle-radius": 16
    },
    "interactive": true
});
```

### Expected Behavior
If I set a lower value for clusterMaxZoom I would expect the cluster circle to remain visible the further I zoom in rather than disappearing.

### Actual Behavior
Changing the value doesn't seem to have an affect on when the layer disappears. For example the layer disappears at around zoom level 8 even if I've set it to '1'

**Comment by lucaswoj** [comment]
cc @mourner

**Comment by mourner** [comment]
@weareboxhead should be fixed now, can you confirm? (and don't forget to update `supercluster` dependency).
