### ISSUE TITLE
Rotating the map does not update its bounds appropriately

### ISSUE THREAD

**Issue by amyhua** [mapbox/mapbox-gl-js#2375]
The map bounds do not update correctly as you rotate the map.

See demo: https://jsfiddle.net/kmmky7h5/

As you rotate the map in the demo, we expect to see the map bounds to update to the latest lat-long coordinates at the corners of the viewport, but instead, the bounds nest directly on top of each other based on the original bounds.

**Comment by indus** [comment]
The bounds you get are defined by only two Points ```[minLng, minLat]``` and ```[maxLng, maxLat]``` so you can only use it to construct a "north-facing" rectangle that encloses the viewport.

But you can use the 4 unprojected corners of the viewport to construct a real "corner-bound" polygon:

``` js
var canvas = map.getCanvas(),
  w = canvas.width,
  h = canvas.height,
  cUL = map.unproject([0,0]).toArray();
  cUR = map.unproject([w,0]).toArray(),
  cLR = map.unproject([w,h]).toArray(),
  cLL = map.unproject([0,h]).toArray();

  var coordinates = [cUL,cUR,cLR,cLL,cUL];
```
see: https://jsfiddle.net/kmmky7h5/1/

**Comment by amyhua** [comment]
Awesome! Thanks indus!

Still a +1 to accommodate rotations in `map.getBounds`

**Comment by lucaswoj** [comment]
Thanks for the workaround @indus! 

Let's merge this discussion with https://github.com/mapbox/mapbox-gl-js/issues/2112

**Comment by amyhua** [comment]
The only thing is that the corners of the canvas does not correspond to the corners of the map; the lower-right coordinate of the canvas goes beyond the map view. But it still works well for the most part.

**Comment by chriswhong** [comment]
Thanks @indus, just used this workaround!
