### ISSUE TITLE
Incomprehensible behavior of querySourceFeatures

### ISSUE THREAD

**Issue by Pipoupi** [mapbox/mapbox-gl-js#2378]
Hi, 
Just trying to use the new version but I'm having strange behavior for the new function querySourceFeatures.
Indeed, I have a geojson with 96666 features.
If I write `map.getSource('idSource')._data` it returns `Object {type: "FeatureCollection", features: Array[96666]}`
Then if I create a filter for nothing with `var filterArray = ["all"];` and then call querySourceFeatures with `map.querySourceFeatures('idSource', filterArray)` it returns `Array[333122]` ! 
Where am I wrong? 
![image](https://cloud.githubusercontent.com/assets/6475852/14201655/8405077e-f7f3-11e5-845e-846ca8e5f2e5.png)

**Comment by indus** [comment]
the second parameter named "params"  is an object, so try:
``` js
glMap.querySourceFeature('drone', {filter : filterArray});
```
besides that your filter looks strange, 'all' is meant to combine multible filters like so:
```js
[
  "all",
  ["==", "class", "street_limited"],
  [">=", "admin_level", 3],
  ["!in", "$type", "Polygon"]
]
```
I´m not sure if it is also valid by itself

**Comment by Pipoupi** [comment]
I figured out, looking at source code,that 2nd parameter has to be an object. If I put an empty object, result is the same.
I'm trying to put my geojson on jsFiddle to see if it's a problem caused by my code, I'll let you know.

![image](https://cloud.githubusercontent.com/assets/6475852/14203806/617503a0-f800-11e5-829a-ac4451fca25f.png)

**Comment by indus** [comment]
Are you are using the source named "drone" in multiple layers?

**Comment by Pipoupi** [comment]
Here's the [jsfiddle](https://jsfiddle.net/zy43d9u3/2/) . 
The `drone` source is used once, the json is huge so it takes time to display the points (~30 seconds). The debugger is on the `zoomend` event. 
The number of features for querySourceFeature depends on the zoom as it changes everytime the zoom changes. So I was guessing it depends on the zoom and the viewport, but `this.queryRenderedFeatures({layers:['route']})` doesn't return the same numbers.

Can you explain the purpose of `querySourceFeature`? I saw it as a function to get the number of features displayed, depending on the filter wanted for all my features.




.

**Comment by lucaswoj** [comment]
Features are split on tile boundaries when when convert the GeoJSON into vector tiles using `geojson-vt`.
