### ISSUE TITLE
Impossible to query original markers source when clustering

### ISSUE THREAD

**Issue by yuvadm** [mapbox/mapbox-gl-js#2384]
**mapbox-gl-js version**: 0.16.0

### Steps to Trigger Behavior
```js
>> map.queryRenderedFeatures(e.point, { layers: ['someLayer']})
{ cluster: true, point_count: 3, point_count_abbreviated: 3 }
```
### Expected Behavior
Would it be possible to get the actual feature array instead of just the count of points in the cluster? Right now there's no canonical method of fetching the clustered points from the cluster marker itself.

### Actual Behavior
Only the cluster point count is returned in the API.

**Comment by yuvadm** [comment]
Damn. This is a dupe of #2358.

**Comment by yuvadm** [comment]
Reopening since there's a serious limitation here that isn't addressed. If I'm clustering a dataset, there's literally no way for me to go back to the original data from the clusters.

I understand the performance limitations but this is an unreasonable limitation, as I can't even query the `GeoJSONSource` object for the markers in the vicinity of `(x,y)`.

What other options are there in this case?

**Comment by mourner** [comment]
This makes sense because `querySourceFeatures` queries data in underlying tiles, and clustering generates tiles with cluster objects. The only way to access unclustered data is to zoom in further. That's just how it works. I can't add much beside what I wrote in https://github.com/mapbox/mapbox-gl-js/issues/2358#issuecomment-203126055. If this feels like a limitation you can't accept, don't use clustering for now.

**Comment by lucaswoj** [comment]
You may be able to workaround this by adding the same data to an unclustered source.

**Comment by yuvadm** [comment]
@lucaswoj thanks for the tip, that was going to be my next attempt. I'm just curious how this data isn't accessible, the source *has* to have access to the higher resolution data at all times (i.e. to handle zoom in), so it's weird that once the GeoJSONSource object is built the data just vanishes.

**Comment by yuvadm** [comment]
@lucaswoj Is there some optimization where the source has to be on an active layer? Just adding the source to the map isn't enough?

```js
>> map.addSource = ('clusterMarkerSourceBackup', new mapboxgl.GeoJSONSource({ ... })
>> map.querySourceFeatures('clusterMarkerSourceBackup', {})
Array [  ]
```
