### ISSUE TITLE
fix documentation for setMaxZoom setMinZoom

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2387]
### Steps to Trigger Behavior

 1. https://www.mapbox.com/mapbox-gl-js/api/#Map.setMaxZoom

### Expected Behavior

The parameter name is `zoom` and type is `number`.

### Actual Behavior

The parameter name is `any` and the type is `zoom`.

**Comment by lucaswoj** [comment]
closed via f08aed5
