### ISSUE TITLE
Overlapping polygons creating zero fill

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-gl-js#2388]
Version 16.0 (Did quick tests with 13.0, 14.0, 15.0 and seems to occur on past versions as well)

Shown at: https://jsbin.com/kumakeyesa/edit?html,output

### Steps to Trigger Behavior

 1. Create tileset with multiple overlapping polygons
 2. Certain areas of intersection are shown with no fill

The no fill section appears like this:

<img width="253" alt="screen shot 2016-04-04 at 3 13 48 pm" src="https://cloud.githubusercontent.com/assets/7108211/14260127/fcea4cd6-fa77-11e5-9e8b-2bb3b174a53d.png">

To confirm there was a polygon in that space, I created a separate layer with most of the polygons filtered out (that layer shown in red):

<img width="254" alt="screen shot 2016-04-04 at 3 14 13 pm" src="https://cloud.githubusercontent.com/assets/7108211/14260146/1622b4a4-fa78-11e5-8772-769da11a4e44.png">

**Comment by ansis** [comment]
This looks like the same bug as https://github.com/mapbox/mapbox-gl-js/issues/2269

The [earcut-final](https://github.com/mapbox/mapbox-gl-js/pull/1606) branch will fix this. Hopefully we'll merge it into master soon.

**Comment by drewbo** [comment]
Thanks for the update and sorry for the duplicate

**Comment by ansis** [comment]
No problem!
