### ISSUE TITLE
Rendering getCanvas().toDataURL doesn't include all layers

### ISSUE THREAD

**Issue by eZ0** [mapbox/mapbox-gl-js#2396]
**mapbox-gl-js version**: v0.16.0

### Steps to Trigger Behaviour
`let data = this.map.getCanvas().toDataURL('image/png', 1.0);`
`let blob = this.imageGenerationService._dataURItoBlob(data);`
`FileSaver.saveAs(blob, 'template.png');`

I want to include all my layers to an image. I would expect that image will be created with all layers, but it's not. Is there something I missing, some option? I couldn't find it in the docs. Otherwise it's a feature request.

### Expected Behaviour
<img width="895" alt="screen shot 2016-04-05 at 11 14 47" src="https://cloud.githubusercontent.com/assets/1408613/14276747/4ffc9a48-fb20-11e5-955b-7f7505969f22.png">

### Actual Behaviour
![template 11](https://cloud.githubusercontent.com/assets/1408613/14276755/5ae44ff0-fb20-11e5-90ac-723fea888e49.png)

**Comment by jfirebaugh** [comment]
Are you referring to the popup and attribution? It is expected that those are not rendered via `getCanvas().toDataURL(...)`, because they are not part of the canvas. They are other DOM elements, and it's not possible to render them to an image.

**Comment by aliir74** [comment]
Hi @jfirebaugh 
I have the same problem and all of my layers are on canvas.

Map on browser:
![](https://cdn.pbrd.co/images/HT5oUUG.png)

Image after getCanvase:
![](https://cdn.pbrd.co/images/HT5pWnc.png)

**Comment by aliir74** [comment]
I add sleep to my code and this problem is solved. But why? I get canvas data after `load` and `render`:
```javascript
function takeScreenshot(map) {
  return new Promise(function(resolve, reject) {
    map.once("render", function() {
        map.on('load', async function () {
            await sleep(2000);
            resolve(map.getCanvas().toDataURL());
        })
    });
    /* trigger render */
    map.setBearing(map.getBearing());
  })
}
```

**Comment by ryanbaumann** [comment]
@aliir74  are just symbol layers missing from your map after the `map.load` event?  If so, try setting your map object initialization to include `fadeDuration: 0` to remove all fade transitions for symbol layers.

**Comment by aliir74** [comment]
Hi @ryanbaumann, I added `fadeDuration: 0` to map object initialization but my problem didn't solve.

**Comment by ryanbaumann** [comment]
Thanks @aliir74.  Can you create a minimal test case so we can reproduce the issue in a jsfiddle and drop here?
