### ISSUE TITLE
Publish documentation for previous versions of mapbox-gl-js

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2398]
For example, users of v0.15.0 now have no documentation for how to use `featuresAt` without spinning up their own documentation server.

**Comment by tmcw** [comment]
2c: publish these as markdown only, in the github repo or in the wiki. Maintaining legacy docs on the website for mapbox.js has always been pretty awful and leads to people using older docs & older docs landing higher in google or swiftype's index. Plus Markdown is easier.

**Comment by bhousel** [comment]
I think this is a good idea, but there shouldn't be an expectation for us to maintain legacy docs while still on v0.x.  To the extent that this distracts us from shipping a stable v1 product, I'd feel better deferring this until later.

For comparison the [lodash docs](https://lodash.com/docs) have a dropdown to pick from latest releases for each major version. This is good because it makes the old documentation available while encouraging people to upgrade to the latest minor version.

**Comment by jfirebaugh** [comment]
I don't think this is something that we should do right now. We haven't gotten any outside requests to do this, and we'd like to encourage people to update to the latest version.

**Comment by amyhua** [comment]
I agree with the sentiment of keeping things updated, but given the flux of how quickly this lib keeps changing, docs to previous version is very important for us, as we only have the capacity to update every once in a while. Please re-open this issue!

**Comment by lucaswoj** [comment]
Sounds great @mollymerp.

**Comment by why-el** [comment]
I echo the requests for having the docs hosted somewhere. Markdown or the actual website is fine, just not having to build it ourselves (which is not always possible/convenient). 

Without an End of Life announcement or similar process, there shouldn't be an expectation that people upgrade, I think. Some devs might not even have the chance to do so, or be required to do small fixes alone. Discouraging use can be done through google SEO by prioritizing your current version (or simply not index it to begin with). 

Another minor point: I personally prefer to upgrade more granularly, most likely just by jumping one or two versions at most, but given your current (commendable) update rate, I can't keep up. ;) So having access to the docs is key.
