### ISSUE TITLE
earcut-final rebase on 0.16.0 forces upgrade

### ISSUE THREAD

**Issue by timiyay** [mapbox/mapbox-gl-js#2401]
**mapbox-gl-js version**: 0.16.0

### Steps to Trigger Behavior

 1. include `mapbox-gl-js` in `package.json`, referencing a SHA from `earcut-final` branch
    * `"mapbox-gl": "git://github.com/mapbox/mapbox-gl-js.git#9369d5"`
 2. run `npm install`

### Expected Behavior

`npm install` succeeds, and pulls the `9369d5` SHA specified.

### Actual Behavior

`npm install` fails, as `9369d5` SHA no longer exists.

This forces the app to upgrade to `mapbox-gl-js` v0.16.0, which has several breaking changes.

### Background

I decided to open this as a new issue, as it has become a major problem for our app, and I'm running around creating issues like hotcakes. We have been forced to 0.16.0, and the upgrade process is proving painful.

My aim is to raise the possibility of creating a new branch, which keeps `earcut-final` based on v0.15.0.

I took a look at doing this myself on a fork, which I will if I have to. It appears non-trivial though, as it requires knowledge of the history of `earcut-final`.

We need the awesome improvements in `earcut-final` to fix a critical rendering bug in our app: https://github.com/mapbox/mapbox-gl-js/issues/2300

The upgrade has caused us some issues, which so far involve:

* popups working differently: https://github.com/mapbox/mapbox-gl-js/issues/2395
* `queryRenderedFeatures` is not a direct replacement for `featuresAt` in some cases: https://github.com/mapbox/mapbox-gl-js/issues/2400
* latest stable `mapbox-gl-draw` isn't compatible with 0.16.0: https://github.com/mapbox/mapbox-gl-draw/issues/282

Our urgency with these issues could be solved, if we had a 0.15.0-based `earcut-final` to use for our builds.

**Comment by ansis** [comment]
I just pushed `earcut-final-v0.14.2` which is at `9369d5`. Can you confirm this fixes your problem?

**Comment by timiyay** [comment]
thanks for the quick assist @ansis 

Yep, that SHA fixes my issues, the app is back, and the builds are passing.

That's extremely helpful, now we can do the 0.16.0 upgrade in a more-civilized manner.
