### ISSUE TITLE
queryRenderedFeatures and layer visibility

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2402]
Does `queryRenderedFeatures` return features if their layer's `visibility` is `none`?
Should it return features if that's the case?

**Comment by mourner** [comment]
Maybe make this an option of `queryRenderedFeatures`? `hidden: true`, turned off by default, which would also include features with `0` opacity, and otherwise exclude.

**Comment by jfirebaugh** [comment]
Non-visible layers are, by definition, not rendered. Therefore they shouldn't be returned by `queryRenderedFeatures`.

**Comment by mourner** [comment]
The main use case would probably be something like #2400. If we never return hidden features, there's just no workaround for this.

**Comment by mcwhittemore** [comment]
`queryRenderedFeatures` reminds me a lot of ray-picking and would thus not return things that don't make up what is seen by the user. It sounds like 'querySourceFeatures' should have a geospatial param.

We talked about this a bit on https://github.com/mapbox/mapbox-gl-js/issues/2106

**Comment by roelvanhintum** [comment]
I ran into this same problem, as a workaround i've set `circle-opacity` to `0.01`. It's enough to make it invisible. This works for now, but a nicer solution would be welcome.

**Comment by jordandudley** [comment]
Should the interactive property of layers have any effect on the results of queryRenderedFeatures? I apologize if this is considered to far off topic.

**Comment by jfirebaugh** [comment]
Closing per https://github.com/mapbox/mapbox-gl-js/issues/2402#issuecomment-206448387.


@jordandudley The introduction of queryRenderedFeatures obsoleted the `interactive` property. The code no longer uses it in any way.
