### ISSUE TITLE
Calling Map#setLayoutProperty for 'text-field' or 'icon-image' triggers an exception

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2407]
We don't pass a `style` to `validateLayoutProperty` in `mapbox-gl-js` [here](https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style_layer.js#L279-L284).

`mapbox-gl-style-spec` tries to access some properties on the style and throws an exception [here](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/lib/validate/validate_layout_property.js#L18-L20).

**Comment by lucaswoj** [comment]
Untagging as a  release blocker because there's a workaround in place. The only drawback to the workaround is that it won't trigger a validation error if the user sets `text-field` without providing a `glyphs` URL or `icon-image` without providing an `icon-image` URL. We have never fired a validation error in these cases.

**Comment by lucaswoj** [comment]
Possible implementation: instead of providing a whole style to `validateLayoutProperty`, just pass `{glyphs: ...}` 😈

**Comment by jfirebaugh** [comment]
This was fixed in c7d0d0f6cff5cb1689d6b6693a380ca2ff0d1583.
