### ISSUE TITLE
Add attribute type="button" to all buttons

### ISSUE THREAD

**Issue by jorismulliez** [mapbox/mapbox-gl-js#2410]
**mapbox-gl-js version**: 0.16

### Steps to Trigger Behavior

 1. include mapbox into a form : https://output.jsbin.com/xojetujomo/
 2. click on controls

### Expected Behavior

1. controls & form works separately
2. mapbox-gl-js does not affect form's behavior

### Actual Behavior

1. controls manipulation send the form

### How to fix it

1. Add an attribute `type="button"` on every "buttons" generate by mapbox and mapbox plugins

ex : 

- https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/control/navigation.js#L84
- https://github.com/mapbox/mapbox-gl-geocoder/blob/master/index.js#L84
- ...

Thanks for your work !

**Comment by bhousel** [comment]
Wow good catch, thank you for reporting this!

**Comment by lucaswoj** [comment]
Done in #2935 😄
