### ISSUE TITLE
Move mapbox:// logic into standalone module

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-js#2416]
Would it be worthwhile to break out [js/util/mapbox.js](https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/mapbox.js) into a standalone module (like `mapbox-gl-url`)? This logic is [no longer handled internally by the Node.js bindings for mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/issues/3862#issuecomment-207631064) and should instead be handled in JavaScript - it would be great to be able to share an implementation.

**Comment by jfirebaugh** [comment]
Share an implementation with what though?

**Comment by mikemorris** [comment]
Sharing an implementation of `mapbox://` URL parsing between gl-js and userland implementations of node-mapbox-gl-native

**Comment by jfirebaugh** [comment]
What do you mean by "userland implementations of node-mapbox-gl-native"?

**Comment by vkurchatkin** [comment]
@jfirebaugh this is required for making anything useful with `mapbox-gl-native` in node. I've spent some time trying to figure out how to translate `mapbox://` request to `http://` before it occurred to me that I could take the code from `mapbox-gl-js`

**Comment by mikemorris** [comment]
Another user of the gl-native Node.js bindings is hitting this issue in https://github.com/mapbox/mapbox-gl-native/issues/4922#issuecomment-216996759

**Comment by Maarius** [comment]
I guess the issue that I am running in here https://github.com/mapbox/mapbox-gl-native/issues/5711 would also be simplified if the urls are handled in a separate package.

**Comment by AdamCanady** [comment]
+1 native is unusable with downloaded styles (From Mapbox Editor) without some kind of bridge between `mapbox://` and `http://`

**Comment by lucaswoj** [comment]
We could expose this on `mapbox-gl-style-spec` alongside function evaluation code, color parsing code, etc.
