### ISSUE TITLE
Add interpolation options to Geojson source?

### ISSUE THREAD

**Issue by misterfresh** [mapbox/mapbox-gl-js#2417]
Calling setData often is expensive. One approach to workaround this is to interpolate marker positions between two setData calls.

By adding a few interpolation functions in the icon vertex shader and the sdf vertex shader, we can have multiple animation effects.

I put together this page to compare results with / without interpolation:
[interpolation techniques comparison](http://misterfresh.github.io/mapbox-animation/)

This works better on devices where the GPU power / resolution ratio is higher. The smoothest I’ve tested was on iPhone 6S. On a two year old macbook air its not as smooth but still ok. On retina MacBooks, it is choppy.

The code is available in the [mapbox-animation](https://github.com/misterfresh/mapbox-animation) repo, the interesting commit is [this one](https://github.com/misterfresh/mapbox-animation/commit/52341802df7fa672f5833ac59d7116595c09eafb). Hope this helps.

**Comment by lucaswoj** [comment]
Thank you for sharing @misterfresh! 

I'm closing this issue because we are looking to improve `GeoJSONSource#setData` performance rather than add any additional animation primitives.

**Comment by misterfresh** [comment]
Sure, I'm glad to share back to the community. I'd say the two are not necessarily mutually exclusive. With recent devices' gpu performance improving at a faster rate than their cpu performance, it makes sense to offload some of the work to the gpu whenever possible. Anyway in the meantime, you know where to point people who complain about setData performance.

**Comment by mourner** [comment]
@misterfresh thanks for sharing, this might get very useful in future! We don't want to consider in-GPU interpolation at the moment because it would add a lot of complexity to an already very complex system that is undergoing major changes currently (in particular, data-driven styling), but we may revisit this later.

**Comment by misterfresh** [comment]
@mourner  Cool, glad you find it interesting. I guess the question is whether this feature is widely requested by users or not. If not, it would not be worth it to deal with the additional complexity. On the other hand, built-in animation might be the feature to make mapbox stand out from other mapping vendors. It would be interesting to make advanced users aware of this and see if it raises interest (for example by linking animation-related issues to it).
