### ISSUE TITLE
Fix behavior in which duplicate features are rendered during zooming

### ISSUE THREAD

**Issue by endro** [mapbox/mapbox-gl-js#2418]
I have vector tiles created using Mapbox Studio Classic with layer:

`(
  SELECT
    osm_id,
    way_point AS way,
    CASE 
      WHEN z(!scale_denominator!) < 12 THEN tags->'ref'
      ELSE tags->'name'
    END AS name
  FROM power_polygon
  WHERE power = 'substation'
    AND area > 1000
    AND z(!scale_denominator!) >= 10
    AND way && !bbox!
) AS data`

On zoom 10,11 name is tags->'ref'
On zoom 12...15 name is tags->'name'

But sometimes I can see both of them (on zoom 12 or 13).

Example (please zoom +1):
https://jsbin.com/nomikokeha/edit?output

First and last line is name, in the middle is ref.
![screenshot](https://cloud.githubusercontent.com/assets/6293998/14423173/a2cc90c0-ffda-11e5-83ef-77cf7ea45262.png)

Am I doing something wrong or it is a bug?

**Comment by lucaswoj** [comment]
This occurs ephemerally during fast zooms as we render both `z` (preferred zoom level) and `z - 1` tiles (previous zoom level, used to fill in blank spaces). 

@ansis Have we thought about mitigation strategies for this common rendering problem? Are there any existing tickets open?

**Comment by lucaswoj** [comment]
> Are there any existing tickets open?

There are not 😄

**Comment by mourner** [comment]
With new symbol placement strategies, this is likely no longer relevant, and there were no updates in the last 2 years, so closing.
