### ISSUE TITLE
Move mapboxgl.supported logic into standalone module

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2425]
Presently, end users are required to include all of `mapbox-gl.js` in order to test if it is supported. This is impractical for bandwidth-conscious users who are implementing fallback to `mapbox.js`.

**Comment by c0** [comment]
:+1: 

This would greatly improve the experience for Android devices that don't support WebGL. We could use this to *only* download the GL or raster code and not double up. Critical for 2G/3G networks.

**Comment by mattp88** [comment]
Agreed, I'd love to see a solution for this.

**Comment by lucaswoj** [comment]
I have moved the necessary logic to https://github.com/mapbox/mapbox-gl-js-supported

# Next Steps

 - [ ] have another engineer review https://github.com/mapbox/mapbox-gl-js-supported
 - [ ] publish the new module to npm
 - [ ] use the new module within Mapbox GL JS

**Comment by lucaswoj** [comment]
@bhousel Does this look ready to 🚢?
