### ISSUE TITLE
Visually differentiate events from methods in documentation

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2427]
We already differentiate events in the sidebar. We should do the same in the body of the page.

<img width="713" alt="screen shot 2016-04-12 at 1 27 55 pm" src="https://cloud.githubusercontent.com/assets/281306/14474542/7e2486b4-00b2-11e6-9a3e-0d064a5c24b9.png">

**Comment by jfirebaugh** [comment]
With #2526, they are in a different section.
