### ISSUE TITLE
Support style functions using both feature properties and zoom

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#2428]
#1932 implemented data driven styling for circles. Other types will be implemented soon.

Style functions can currently either be functions of zoom or functions of data. They can't be functions of both at the same time. This makes it hard to use data-driven styles with properties should often change with zoom like `circle-radius`, `line-width` and `text-size`. For example, it would be nice if the circles could get bigger as you zoom in: https://bl.ocks.org/lucaswoj/raw/4fa16fcf9663f67f6b7d4a7225dc3524/

Data + zoom driven functions would also let us merge a lot of mapbox streets layers into one:
- all road layers could be one layer, all tunnel layers could be another layer
- all the multi-size label layers like country-label-lg, country-label-md, country-label-small could be merged into one layer

Data + zoom driven functions would be useful but would also add complexity to the spec and studio.

**If** we add it, imagine it would look something like a spreadsheet. On one axis you would have zoom levels and on the other axis you would have data properties. Each zoom/data pair would have it's own value.

### For example:

```
property: population

        0       1000        1000000
      ------------------------------
z0    | 1       10          20
z10   | 4       15          30
z20   | 6       20          40
```
is the function for circle radius. You would evaluate it for `{ properties: { population: 500000 } }` at z6 like this:
- find the two closest steps, z0 and z10
- at each step, find the value for the feature:
    - `interp(10, 20, (500000 - 1000) / (1000000 - 1000)) ~= 15 at z0` and
    - `interp(25, 30, (500000 - 1000) / (1000000 - 1000)) ~= 22.5 at z10`
- interpolate those two values based on the zoom levels to get the final value
    - `interp(15, 22.5, (6 - 0) / (10 - 0) = 19.5 at z6`

### The GL implementation:
When creating the buffers, find the 4(?) zoom level stops closest to the tile's zoom level. For each feature, calculate the value for the feature at each of these stops and add it to the buffer.
At render time, find the two stops the current zoom level is between and calculate the `t` interpolation value. This value is the same for all features because all features have stops at the same zoom levels. Pass this value as a uniform to the shader. The shader reads the values at the different stops as attributes and uses the uniform to interpolate the values.

@lucaswoj

**Comment by lucaswoj** [comment]
Would that implementation only allow function stops at integer zoom levels? Does that matter from a design perspective? cc @peterqliu

**Comment by ansis** [comment]
> Would that implementation only allow function stops at integer zoom levels? Does that matter from a design perspective? cc @peterqliu

I think it wouldn't have to be limited to integer zoom levels, but that might make things simpler.

**Comment by lucaswoj** [comment]
Here's my proposed syntax:

```json
{
  'circle-radius': {
    stops: [
      [{$zoom: 0, population: 0}, 1],
      [{$zoom: 0, population: 10000000}, 25],
      [{$zoom: 20, population: 0}, 5],
      [{$zoom: 20, population: 10000000}, 100],
  }
}
```

It's relatively easy to imagine how this would work for exponential functions. 

For categorical functions, we would need to calculate the input's euclidian distance to each stop and choose the closest. When two values are equally close ¯\_(ツ)_/¯.

For interval functions, we would need to choose an algorithm to divide the 2d input space into regions defined by the stops.
