### ISSUE TITLE
Enable data-driven styling functions for as many paint properties as possible

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2430]
follow-up to #1932

**Comment by mourner** [comment]
Let's make a check list to track which properties are already supported and which are yet to support.

**Comment by lucaswoj** [comment]
The unsupported properties are

 - *-pattern properties #2732
 - *-translate properties #2731
 - line-* properties #2729
 - symbol-* properties #2730
 - all layout properties except icon-rotation

I aspire to create a feature comparison table, in part tracking data-driven styling support, per https://github.com/mapbox/mapbox-gl/issues/16 but haven't yet found the time.

**Comment by lucaswoj** [comment]
Closed in favor of more specific follow-up tickets ^

**Comment by x9xjdzz9eaeeghcrar9c** [comment]
Is fill-opacity supported? I don't think it was captured by any of the follow-up tickets.

**Comment by lucaswoj** [comment]
@x9xjdzz9eaeeghcrar9c see #2728
