### ISSUE TITLE
Enable data-driven styling functions for as many layout properties as possible

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2431]
follow-up to #1932

**Comment by danielduhh** [comment]
Any chance on data-driven values for fill-color?

**Comment by mourner** [comment]
@danielduhh it's already implemented in 0.19.

**Comment by josiekre** [comment]
v0.19 works for fill-color. Just tested it.

**Comment by jfirebaugh** [comment]
The documentation of individual properties on https://www.mapbox.com/mapbox-gl-style-spec/ (e.g. [`fill-color`](https://www.mapbox.com/mapbox-gl-style-spec/#paint-fill-color)) now includes a version support matrix that details support for data-driven styles. We're going to keep this updated as we roll out support for data-driven styling of more properties.

**Comment by sdawson26** [comment]
Is the next step getting to line-color and text-color? I'm hoping we're close to more data-driven features. Thanks for all of your hard work!

**Comment by mourner** [comment]
@sdawson26 line-color is just around the corner, see https://github.com/mapbox/mapbox-gl-js/pull/2938

**Comment by jfirebaugh** [comment]
⇢ #4434.
