### ISSUE TITLE
rendering seems to miss some points, resulting in incomplete polygons

### ISSUE THREAD

**Issue by hsinister** [mapbox/mapbox-gl-js#2435]
**v0.16.0**:
This is an issues which seems specific to Opera. Basically, the rendering of the map doesn't work properly. At first I thought I broke something with my code but the same rendering problem occurs even on the Mapbox examples page.

Attached are screenshots of the issue on Opera 36.0:
![capture](https://cloud.githubusercontent.com/assets/7836781/14499320/669ac4ee-01d0-11e6-8b02-7a073bb9e8b0.PNG)
![capture2](https://cloud.githubusercontent.com/assets/7836781/14499324/69e505ce-01d0-11e6-905e-ab0f69485e39.PNG)

The rendering works on Edge:
![capture3](https://cloud.githubusercontent.com/assets/7836781/14499392/b57e50da-01d0-11e6-8eda-e59f5b1e5ceb.PNG)
![capture4](https://cloud.githubusercontent.com/assets/7836781/14499396/b9f6034c-01d0-11e6-8849-8afbbd45a205.PNG)

I don't seem to have any other problems with my browser, so I don't think it is a browser issue. Also, I used to be able to open it fine until recently.

**Comment by mourner** [comment]
Heh, this looks like one more bug that will probably be fixed by #1606. Can you try the `earcut-final` branch to confirm? Similar recent bug report #2300

**Comment by hsinister** [comment]
Yikes. I really haven't started using git so I don't know hot to do that.

**Comment by mourner** [comment]
Should be fixed by #1606 which was merged to master, to be included in the next release.
