### ISSUE TITLE
Map.addLayer documentation doesn't describe StyleLayer

### ISSUE THREAD

**Issue by danzel** [mapbox/mapbox-gl-js#2438]
https://www.mapbox.com/mapbox-gl-js/api/#Map.addLayer

StyleLayer isn't documented on this page.
I think maybe it should be linking to https://www.mapbox.com/mapbox-gl-style-spec/#layers (like addSource below)

**Comment by lucaswoj** [comment]
We do not intend for `StyleLayer` to be part of our public API. This documentation should be modified to not advertise `StyleLayer` as an acceptable input type and clarify that the `layer` object correlates with a style spec layer.

**Comment by lucaswoj** [comment]
This is much better now 😄
