### ISSUE TITLE
Create a data-driven styling example

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2439]
Now that we've merged #1932, we should post a simple example using data-driven styling. 

We only support data-driven styling for `circle-size` and `circle-color` in `mapbox-gl-js`. There’s no support for other properties, `mapbox-gl-native`, or Studio. Given all the caveats, we aren’t going to advertise it too heavily yet but I’d love to get some intrepid users using it.

I created a simple example here: https://bl.ocks.org/lucaswoj/4fa16fcf9663f67f6b7d4a7225dc3524

cc @danswick @tristen @peterqliu

**Comment by peterqliu** [comment]
oof, do we support compound styling by data *and* zoom? this would apply for any physical encoding, like circle-size, icon-size, text-size, and line-width

**Comment by lucaswoj** [comment]
Not yet, but that's high on my priority list. Tracking in https://github.com/mapbox/mapbox-gl-js/issues/2428.

**Comment by BrunoSalerno** [comment]
@lucaswoj are categories (strings) supported? For instance, the following isn't working:
```js
'circle-color': {
          property: 'line',
          stops: [
            ['A', '#8a8acb'],
            ['B', '#223b53'],
            ['C', '#3887be']
          ]
        }
```

**Comment by lucaswoj** [comment]
@brunoabinader see https://github.com/mapbox/mapbox-gl-style-spec/pull/445

**Comment by ericfischer** [comment]
From chat with @peterqliu: I'm going to pull the census race and ethnicity data [from this datamaps map](http://trafficways.org/#10/41.7800/-87.6009/census/nobase/13/0.05917/1.23/0.5/twos/antialias/nogps/nomercator/-C%208) into vector tiles to try with this.

**Comment by peterqliu** [comment]
🙇 thanks @ericfischer. This will come out as a map ID on `enf`'s account; @lucaswoj what's the best way to store this for longevity?

**Comment by ericfischer** [comment]
Census 2010 race and ethnicity data for a square around San Francisco is in `enf.4zdd7xxg` now, created with `tippecanoe -f -o sf-2010.mbtiles -z12 sf-2010.json` from `s3://mapbox/playground/ericfischer/sf-2010.json`.

**Comment by ericfischer** [comment]
The other case I'd be really interested to try with this is circle-size for intersection pedestrian volumes. The data is in `enf.6fzknzvu` and is used in [this Classic style](https://api.mapbox.com/v4/enf.d0d3328f/page.html?access_token=pk.eyJ1IjoiZW5mIiwiYSI6IkNJek92bnMifQ.xn2_Uj9RkYTGRuCGg4DXZQ#14/43.6530/-79.3955).

**Comment by peterqliu** [comment]
@ericfischer thanks for putting those together. Next actions on me to draft an example

**Comment by lucaswoj** [comment]
[Here's a demo of the pedestrian volume data set!](https://bl.ocks.org/lucaswoj/raw/2b6b29c77eea0792e68a485705804d61/#3/37.80/-96.00)

**Comment by peterqliu** [comment]
And here's the one for ethnicity: https://jsfiddle.net/8vnsbpqf/3/. The tileset is hosted on `examples` account; just gotta swap out my token and this should be good

**Comment by peterqliu** [comment]
Also, it's nice that we have an example each for categorical and continuous.

**Comment by ericfischer** [comment]
Thanks @lucaswoj! It's great to be able to do the pedestrian map with GL now.

**Comment by BrunoSalerno** [comment]
Excellent @lucaswoj !!!

**Comment by ryanbaumann** [comment]
How does setPaintProperty(layer, paint-prop, value) work with the new data-driven styles?

`map.setPaintProperty(layer, 'circle-radius-stops', [ [1, 1], [2, 5], [3, 10] ])`

Throws error 
`map.js:929 Error: layers.layer.paint.circle-radius-stops: unknown property "circle-radius-stops"(…)`

**Comment by tmcw** [comment]
https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/ is live

**Comment by wandergis** [comment]
data-driven styling can't work on line-color,i wrote the code:
```
"line-color": {
                    property: 'mp_type',
                    type: 'categorical',
                    stops: [
                        ['0x06', '#2C9DF1'],
                        ['0x05', '#223b53'],
                        ['0x03', '#e55e5e'],
                        ['0x08', '#3bb2d0'],
                        ['0x02', '#ccc']
                    ]
                }
```
but it doesn't work.

**Comment by lucaswoj** [comment]
@wandergis `line-color` does not yet support data-driven styling. This feature is coming in a release soon!

**Comment by josiekre** [comment]
+1 for `fill-color` working with `type: 'categorical'`

**Comment by jfirebaugh** [comment]
The documentation of individual properties on https://www.mapbox.com/mapbox-gl-style-spec/ (e.g. [`fill-color`](https://www.mapbox.com/mapbox-gl-style-spec/#paint-fill-color)) now includes a version support matrix that details support for data-driven styles. We're going to keep this updated as we roll out support for data-driven styling of more properties.

**Comment by wandergis** [comment]
When  can `line-color`  support data-driven styling? That would be very useful.

**Comment by kdanaher** [comment]
@lucaswoj : Is `map.setPainProperty` able to tap into the `property` or `stops` parameters of `fill-color` currently or is this planned for a future release by chance?

**Comment by lucaswoj** [comment]
@kdanaher data-driven styling support is documented in the [style spec](https://www.mapbox.com/mapbox-gl-style-spec/#paint-fill-color);

**Comment by wroscoe** [comment]
It was unclear to me that the values and zoom needed to be in ascending order to work. After this, it worked great.

**Comment by pzupan** [comment]
I'm unable to get circle-color to work in v0.27.0/mapbox-gl.js.  The circle-radius property responds properly in the code below, but not circle-color.

`    map = new mapboxgl.Map({
      container: 'map', 
      pitch: 0.01,
      style: 'mapbox://styles/mapbox/streets-v9',
      zoom: 1
    });

    map.on('load', function () {   
      map.addSource("points", {
        type: "geojson",
        data: ""
      });
      map.addLayer({
        id: "points",
        type: "circle",
        source: "points",
        paint: {
          "circle-color": { 
            property: "point_position",
            type: "categorical",
            stops: [
              [1, "#1e8449"],
              [2, "#ff5733"],
              [3, "#666666"]
            ]
          },
          "circle-radius": {
            base: 3,
            stops: [[8, 6], [22, 120]]
          },
        }
      });

      map.addLayer({
        id: "pointsLabels",
        type: "symbol",
        source: "points",
        layout: {
          "text-field": "{name}\n{created_at}",
          "text-font": ["Open Sans Semibold", "Arial Unicode MS Bold"],
          "text-offset": [0.6, 0.0],
          "text-anchor": "left",
          "text-size": 11
        }
      });
`
I've attached a screenshot indicating that the map object has the relevant data "point_position", but the points on the map are not the correct color.
![screenshot](https://cloud.githubusercontent.com/assets/45881/20448703/2a689bb0-ad9a-11e6-8180-638fd16034d8.png)

![screenshot 2](https://cloud.githubusercontent.com/assets/45881/20448711/347e8678-ad9a-11e6-8ec0-b53f2958009a.png)

And I'm not seeing any errors in the console.
