### ISSUE TITLE
Ensure `rotatestart` and `rotateend` events are fired in all cases

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2448]
We fire zoomstart and zoomend events whenever a zoom starts and ends.

We fire rotatestart and rotateend events only when a rotation GESTURE starts and ends, although map rotation can be triggered in other ways. 

cc @bhousel

**Comment by reidab** [comment]
One case where this is currently not happening is when clicking the NavigationControl compass to reset the map's bearing.
