### ISSUE TITLE
Add pitchstart and pitchend events

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2449]
`zoom` has `zoomstart` and `zoomend`

`rotate` has `rotatestart` and `rotateend` (see #2448)

`pitch` is all alone

**Comment by redbmk** [comment]
I'm actually having a hard time finding anywhere in the code that triggers a `pitch` event at all. I'm looking through the latest code for it, and `map.on('pitch', data => console.log(data))` never fires for me in version 0.28.0.

**Comment by redbmk** [comment]
Ah, looks like that part of an open issue in #3357. Would that make this a duplicate then, since that issue also mentions making sure that `pitchstart` and `pitchend` fire?

**Comment by vypah** [comment]
Is this still being worked on? Any update on this ? Firing `moveend` `zoomend` event on every touch really effects the performance.

**Comment by mollymerp** [comment]
@vypah yep I'm working on this as part of #4253 !

**Comment by vypah** [comment]
@mollymerp great 👍 I really hope that this will address https://github.com/mapbox/mapbox-gl-js/issues/3435 once we start distinguishing between touch events and other events like `moveend`, `zoomend`. During multi-touch, eg. two fingers touching the screen at the same time, `moveend` is fired on every single animation frame for the duration of the gesture.
