### ISSUE TITLE
Expose minimum and maximum zoom for clusters

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#2457]
**mapbox-gl-js version**: latest
### Steps to Trigger Behavior
1. Design a map that uses clusters
2. Intend to zoom to a level where a given cluster is expanded to show points
3. While we have a property for how many points are in a cluster, we don't have one for this.
### Expected Behavior

Clusters contain a `min_zoom` property and `max_zoom` for the bounds at which they are clustered.
### Actual Behavior

They don't

---

Implementation-wise, [supercluster's getClusterProperties method](https://github.com/mapbox/supercluster/blob/a2133d6d354dea559a251c5e3f6a1f16df413ed3/index.js#L172-L181) should expose the value of the cluster's max zoom. Behind that, clusters have a `zoom` property but this is the last zoom at which they are processed: this will need to include their range as well.

**Comment by mourner** [comment]
Why do you need these properties? Something like "click to expand" that would zoom in by one level in most cases but sometimes more?

**Comment by tmcw** [comment]
> Something like "click to expand" that would zoom in by one level in most cases but sometimes more?

Yep, that'd be one of the primary usecases - @arunasank can go into more detail about how this number would be useful for her project.

**Comment by arunasank** [comment]
>Something like "click to expand" that would zoom in by one level in most cases but sometimes more?

@mourner Exactly. If we had a property to reveal the exact zoom at which a cluster splits, it'll be easy to just split on click sometimes. 

It's useful when the points that make a cluster are very very close to each other sometimes, and spread apart at others.

I have some clusters on http://arunasank.github.io/labhopping. The cluster on the bottom left splits at zoom 6, but the one on the top right only splits at zoom level 19 or so.

**Comment by mourner** [comment]
@arunasank Sounds good! I'll look into it after vacation. Click to expand would be for the cluster max zoom, but what use case do you have for min zoom?

**Comment by arunasank** [comment]
@mourner \o/ The cluster max zoom would be super useful for our project, thanks! : ) 

I can't think of many use cases for the min zoom besides
* Click to zoom back out into cluster-view if you're in non-cluster-view.
* Instead of smooth zoom-in and zoom-out, zoom-in and zoom-out to have only two views - cluster or non-cluster by using your current cursor location to center the map.

**Comment by mourner** [comment]
Added in #6829
