### ISSUE TITLE
Animate point along line

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#2469]
Analogous to the [camera movement ticket](https://github.com/mapbox/mapbox-gl-js/issues/2441), would be great to have a dedicated method to [animate a point along a line](https://github.com/mapbox/mapbox-gl-js/pull/2455).

This would be useful not just to track a marker to a squiggly path, but animating markers simply to new positions, as provided by a websocket feed or some recurrent service.

Takes a `linestring`, `duration`, and maybe `easing` as arguments.

**Comment by tmcw** [comment]
You already have an extremely similar ticket open: #1391 and a nearly-identical ticket that is closed as duplicate #1207. Please search for issues.
