### ISSUE TITLE
Updating paint properties on layers without classes when a class is active throws exception

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2477]
**mapbox-gl-js version**: 0.17.0

### Steps to Trigger Behavior

 1. Add some layers to the map that do not contain classes
 2. Add a class to the map
 3. Set the paint property of a layer without a class

### Expected Behavior
That the regular paint properties (without classes) are updated. This has worked fine up until 0.17.0 and I guess it's either a bug in the new automatic batching behaviour, or the API has changed on this part.

### Actual Behavior
An exception is thrown.

Demo: http://codepen.io/anon/pen/JGwerB

**Comment by lucaswoj** [comment]
Bug confirmed. I'll fix this for the next release!

**Comment by jfirebaugh** [comment]
Flagging for https://github.com/mapbox/mapbox-gl-test-suite/issues/76.
