### ISSUE TITLE
querySourceFeatures not working as expected

### ISSUE THREAD

**Issue by facultymatt** [mapbox/mapbox-gl-js#2481]
It seems that `querySourceFeatures` only considers features within the current map bounds. 

Is this the expected behavior? The documentation suggests it considers all the source data, regardless of bounds. I believe it would be more useful to query all source data, since `queryRenderedFeatures` exists for querying within bounds.

**Comment by lucaswoj** [comment]
This is the expected behaviour. `querySourceFeatures` only operates on currently-visible vector tiles. 

We will update our docs to clarify this behaviour.

**Comment by facultymatt** [comment]
OK, then does it make sense to combine the 2 methods? There is really little difference expect that `queryRenderedFeatures` has an optional bounding box and a source is not required (does this query all sources then) ? Unless I'm misunderstanding something. 

```
queryRenderedFeatures({
    pointOrBox: Mixed
    sourceId: String,
    layers: Mixed 
    filter: Array, 
})
```

I still believe it would be useful to add another method which queried across all tiles (even non-visible). Although the client can still do this by filtering on `map._data`.

**Comment by lucaswoj** [comment]
> OK, then does it make sense to combine the 2 methods? There is really little difference expect that queryRenderedFeatures has an optional bounding box and a source is not required (does this query all sources then) ?

 - `queryRenderedFeatures` is concerned with what's rendered on the map, accounting for the shape of labels, symbols, translated geometries, etc
 - `querySourceFeatures` is concerned with raw feature geometries

> I still believe it would be useful to add another method which queried across all tiles (even non-visible). Although the client can still do this by filtering on map._data.

This feature is not possible. `querySourceFeatures` must work for both GeoJSON and vector tile sources. To query across all times in a vector tile source could easily require downloading hundreds of gigabytes of data. If you need access to the entire GeoJSON file, you should use the GeoJSON file.

**Comment by facultymatt** [comment]
I have an instance where I need to query raw geometeries which are within the maps current bounding box, but are on layer which is currently not visible. Is this possible with either? Or is there another workaround that you suggest?

**Comment by lucaswoj** [comment]
@facultymatt `querySourceFeatures` should work for your use case

**Comment by facultymatt** [comment]
Thanks @lucaswoj, `querySourceFeatures ` does work to query all the source geojson (must have been doing something incorrect before). I'm still confused with the behavior because I thought as you mentioned above `querySourceFeatures ` only works with "currently-visible vector tiles". As I zoom in, less tiles are visible, but they appear to still be queried. Is it because even a small part of the tile is still visible in the zoomed bounding box? 

Maybe you can help with the outcome I need: 

- I have 2 layers, Points which are not visible and Lines which are visible. 
- Starting zoomed out to the max, all geometry is visible in map bounding box
- I zoom in so only a few geometries are within the map bounding box. 
- I want to filter points (which are not visible) within the map bounding box, optionally using filters. 

Any suggestions? I know that I could always querySourceFeatures and then use `turf within` to filter inside the map bounds, but ideally I would not need the additional dependency.

Thanks for helping with this! Obviously `querySourceFeatures` and `queryRenderedFeatures` are very powerful once they are understood!

**Comment by lucaswoj** [comment]
It sounds to me like you should use `turf within`

**Comment by defaye** [comment]
The [docs](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#querysourcefeatures) still misleads people into thinking this filters against all features. 

> Returns an array of [GeoJSON](http://geojson.org/) [Feature objects](https://tools.ietf.org/html/rfc7946#section-3.2) representing features within the specified vector tile or GeoJSON source that satisfy the query parameters.

No mention of the fact that it seems to be filtering against the visible map area and the visible state of the features themselves.

**Comment by mryellow** [comment]
Confusing API.

Consumes hours of attempting to use it before it becomes apparent that it isn't useful for the expected use-cases.
