### ISSUE TITLE
overzoomed tiles dont draw where longitude > 180 or < -180

### ISSUE THREAD

**Issue by ian29** [mapbox/mapbox-gl-js#2482]
**mapbox-gl-js version**: 0.17.0

### Steps to Trigger Behavior

1. view a map that overzooms vector tiles (e.g. z17 or higher on most mapbox maps)
2. pan around the world so that your longitude is > 180 or < -180

compare these urls:
- wrapped https://api.mapbox.com/styles/v1/villeda/cifa01lh61psbskknpzv1eubz.html?title=true&access_token=pk.eyJ1IjoidmlsbGVkYSIsImEiOiJNY2hHRXVrIn0.epqbDBYitFBInieZNLLiWw#17/37.77891/-482.41879
- not wrapped https://api.mapbox.com/styles/v1/villeda/cifa01lh61psbskknpzv1eubz.html?title=true&access_token=pk.eyJ1IjoidmlsbGVkYSIsImEiOiJNY2hHRXVrIn0.epqbDBYitFBInieZNLLiWw#17/37.77891/-122.41879

- no errors in console
- chrome 49.0.2623.112 (64-bit)

### Expected Behavior

you should see a map at url hash like `17/37.77891/-482.41879`

### Actual Behavior

you dont see a map at url hash like `17/37.77891/-482.41879`, just the background color.

cc @ansis @nickidlugash

**Comment by lucaswoj** [comment]
This `git blame`s back to layer-by-layer rendering 002c69071275997886fd98aa4dbc6025eed36a86 😬

**Comment by lucaswoj** [comment]
I've narrowed this problem down further to our `TileCoord.cover` calculations when `w != 0` and `z != actualZ`. In particular, `z16coord.y == z15coord.y` while `z15coord.y == z14coord.y * 2`.

I'm finding this code hard to reason about. @ansis, could you take a look and let me know if you see an obvious fix?
