### ISSUE TITLE
Intro content fixes

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#2485]
![2016-04-22 at 11 39 am](https://cloud.githubusercontent.com/assets/32314/14733203/f386e464-087e-11e6-9162-3892f038b16d.png)

* bad link
* non-highlighted html
* bad code styling in the h1
* "click here" prose antipattern

**Comment by lyzidiamond** [comment]
Two options here.

This one mimics Mapbox.js:

![screen shot 2016-04-22 at 4 12 32 pm](https://cloud.githubusercontent.com/assets/2523165/14757123/2867a4f4-08a5-11e6-82fa-cf02a664c8b8.png)

This one is a bit more stylized:

![screen shot 2016-04-22 at 4 12 59 pm](https://cloud.githubusercontent.com/assets/2523165/14757124/2877caf0-08a5-11e6-87b0-08502e787599.png)

Thoughts @tmcw @lucaswoj?

**Comment by lyzidiamond** [comment]
Code is on this branch: https://github.com/mapbox/mapbox-gl-js/tree/intro-page

**Comment by lucaswoj** [comment]
Thanks for the feedback @tmcw and @lyzidiamond! I'm 100% on all these ideas and will implement them as soon as they come up in my queue. Pull requests welcome too!

**Comment by lyzidiamond** [comment]
@lucaswoj I can make a PR!

**Comment by tmcw** [comment]
This was fixed in the PR.
