### ISSUE TITLE
Add better error messages for invalid "Map#fitBounds" parameters

### ISSUE THREAD

**Issue by facultymatt** [mapbox/mapbox-gl-js#2487]
Example: 

```
_map.fitBounds([-71.1062070541746, 42.35829812478494, -71.1062070541746, 42.35829812478494]);
ERROR Invalid LngLat object: (NaN, NaN)LngLat
```

```
Stack 
index.js:63 Uncaught Error: Invalid LngLat object: (NaN, NaN)LngLat @ index.js:63Transform.unproject @ index.js:63(anonymous function) @ index.js:63(anonymous function) @ index.js:63n @ index.js:63requestAnimationFrame (async)exports.frame @ index.js:63exports.timed @ index.js:63util.extend._ease @ index.js:63util.extend.flyTo @ index.js:63util.extend.fitBounds @ index.js:63fitBoundsToGeoJson @ mapKit.service.js:195(anonymous function) @ app.module.js:211(anonymous function) @ async.min.js:8Q @ async.min.js:8(anonymous function) @ async.min.js:8(anonymous function) @ app.module.js:203processQueue @ angular.js:15757(anonymous function) @ angular.js:15773Scope.$eval @ angular.js:17025Scope.$digest @ angular.js:16841Scope.$apply @ angular.js:17133done @ angular.js:11454completeRequest @ angular.js:11652requestLoaded @ angular.js:11593XMLHttpRequest.send (async)(anonymous function) @ angular.js:11630sendReq @ angular.js:11423serverRequest @ angular.js:11133processQueue @ angular.js:15757(anonymous function) @ angular.js:15773Scope.$eval @ angular.js:17025Scope.$digest @ angular.js:16841Scope.$apply @ angular.js:17133done @ angular.js:11454completeRequest @ angular.js:11652requestLoaded @ angular.js:11593XMLHttpRequest.send (async)(anonymous function) @ angular.js:11630sendReq @ angular.js:11423serverRequest @ angular.js:11133processQueue @ angular.js:15757(anonymous function) @ angular.js:15773Scope.$eval @ angular.js:17025Scope.$digest @ angular.js:16841Scope.$apply @ angular.js:17133(anonymous function) @ angular.js:24813defaultHandlerWrapper @ angular.js:3417eventHandler @ angular.js:3405
```

**0.17.0**:
### Steps to Trigger Behavior
1. Create a map
2. Create bounding box where `v0 === v2` and `v1 === v3` [v0, v1, v2 ,v3]. Example [0,0,0,0] 
3. Call `map.fitBounds([0,0,0,0])` 
### Expected Behavior

Map zoom in to bounds. 
### Actual Behavior

Error thrown. 
### Maybe related

https://github.com/mapbox/mapbox-gl-js/issues/1776

**Comment by lucaswoj** [comment]
What would you expect to happen in this case? Zooming into a zero-width and zero-height box doesn't make much sense.

**Comment by lucaswoj** [comment]
Closing as this is not the intended use of this method. Please re-open if I am misunderstanding.

**Comment by facultymatt** [comment]
Sure it's not the intended use but in some cases with dynamic data a client may end up in the scenario where the bounding box has zero height and zero width - I would still expect the method to zoom in. 

At the very least I would expect a more accurate error since the LngLats provided are valid and the error is misleading (suggesting the LngLat's are invalid) which makes debugging more challenging.

**Comment by lucaswoj** [comment]
> At the very least I would expect a more accurate error since the LngLats provided are valid and the error is misleading (suggesting the LngLat's are invalid) which makes debugging more challenging.

That we can do!

**Comment by lucaswoj** [comment]
related to #2112

**Comment by joswinter** [comment]
I think this issue can be closed the unwanted behavior described in this issue cannot be replicated. `map.fitBounds([0,0,0,0])` doesn't throw an error anymore.

**Comment by mollymerp** [comment]
Thanks @joswinter! You're right this was fixed in https://github.com/mapbox/mapbox-gl-js/pull/3683
