### ISSUE TITLE
Objects gets clipped at the dateline

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-gl-js#2490]
Trying to create a night shadow effect using a large polygon. If I try to translate it to set it to the correct position for the time of day, it gets clipped.

It does not seem like there is any another way to get the same effect.

![untitled2](https://cloud.githubusercontent.com/assets/126868/14769460/1adf0f20-0a76-11e6-9055-7dd93612abce.gif)

**Comment by jfirebaugh** [comment]
The "translate" property can't translate things more than one tile away. This is kind of a fundamental limitation for tiled rendering, and it would be pretty hard to change it.

In order to accomplish a night shadow effect, I think you'll need to use a GeoJSON source with dynamic data.

**Comment by rlueder** [comment]
This is old and has been closed, but if someone lands here like I did, here's an example of a dynamic solar terminator in d3 that could be adapted to Mapbox GL: https://observablehq.com/@mbostock/solar-terminator
