### ISSUE TITLE
CommandBufferContext render warnings using raster tile source

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/mapbox-gl-js#2505]
```
[.CommandBufferContext]RENDER WARNING: there is no texture bound to the unit 1
```

This issue is looking similar to #2032

**mapbox-gl-js version**: v0.17.0

**OS X** 10.11.4
**Google Chrome** 50.0.2661.86 (64-bit)
**Opera Developer** 38.0.2205.0

Won't reproduce in Safari Technology Preview Version 9.1.1

### Steps to Trigger Behavior

 1. Go to https://www.mapbox.com/mapbox-gl-js/example/map-tiles/
 2. Open js console

### Expected Behavior

There should be no warnings 

### Actual Behavior

There are warnings

**Comment by mourner** [comment]
I didn't see any warnings in Chrome 49 and started seeing them after upgrading to Chrome 50. cc @lucaswoj @ansis
