### ISSUE TITLE
Add an option to use wrapped coordinates in URL hash

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#2507]
**mapbox-gl-js version**:  0.17.0, but present in much older versions as well
### Steps to Trigger Behavior
1. Navigate to a page like https://api.mapbox.com/styles/v1/saman/cimhtyumg001bqxnokqvveyx2.html?title=true&access_token=pk.eyJ1Ijoic2FtYW4iLCJhIjoiS1ptdnd0VSJ9.19qza-F_vXkgpnh80oZJww
2. Pan the map for a while
3. See that the URL changed to look like: https://api.mapbox.com/styles/v1/saman/cimhtyumg001bqxnokqvveyx2.html?title=true&access_token=pk.eyJ1Ijoic2FtYW4iLCJhIjoiS1ptdnd0VSJ9.19qza-F_vXkgpnh80oZJww#1.88/-27.1/-1887.5
### Expected Behavior

Lng value resets to 0 in hash when you pass the edge of the world 
### Actual Behavior

Lng value keeps increasing

**Comment by ryanbaumann** [comment]
+1 on this bug. Longitude does not reset to zero when panning/scrolling across 180 degrees (middle of Pacific Ocean).

Scope:  Impacts map.getBounds() function for sure, important for geospatial queries made from the current map bounds.

**Comment by lucaswoj** [comment]
@samanpwbb @ryanbaumann Can you explain why this behaviour is undesirable to you? Might there be cases where you _do_ want to differentiate between "wrapped" copies of the map? Are you able to normalize these coordinates internally?

**Comment by samanpwbb** [comment]
> Might there be cases where you do want to differentiate between "wrapped" copies of the map? 

Not in any of my use cases, but maybe someone wants this (I am reminded of https://www.youtube.com/watch?v=kpk2tdsPh0A).

Are you able to normalize these coordinates internally?

Yes, this would be possible, but difficult to manage in more complex systems where you're storing and sharing map position coordinates across multiple applications.

Could we default to wrapped coordinates but allow user to pass in an option to accumulate coordinates if it's important for certain types of users?

**Comment by lucaswoj** [comment]
> Yes, this would be possible, but difficult to manage in more complex systems where you're storing and sharing map position coordinates across multiple applications.

What can we do to make this less difficult? Expose some sort of `normalizeCoordinates` utility method? I would rather make it easy to normalize coordinates than complicate GL JS with more configuration options.

**Comment by ryanbaumann** [comment]
@lucaswoj The goal is to take the mapBounds() and make an underlying geospatial query from a given "point-in-polygon" area. 

Normalizing the longitude coordinate before making a geospatial query is certainly a viable option.  If so, we should make it clear in the docs at https://www.mapbox.com/mapbox-gl-js/api/#LngLatBounds.  A normalizeCoordinates() method would be perfect.

**Comment by samanpwbb** [comment]
A general purpose normalizeCoordinates method would be cool, yes. I often end up writing this myself. We have one in Studio, for example. 

I'd be most interested in the option to declare, when initializing my map, that the hash should wrap coordinates.

**Comment by jfirebaugh** [comment]
Fixed in #4451 -- longitude is now automatically wrapped when crossing the antimeridian.
