### ISSUE TITLE
Multiple Clusters in one map

### ISSUE THREAD

**Issue by eliglazier** [mapbox/mapbox-gl-js#2513]
It would be great if two geojson markerclusters could be included in the same map. Alternately, it would be great if markerclusters could be symbolized based on attributes within the geojson data, not just on how many points are clustered. 

Thanks!

**Comment by ansis** [comment]
> It would be great if two geojson markerclusters could be included in the same map.

Multiple marker clusters can be added by adding multiple geojson sources

> it would be great if markerclusters could be symbolized based on attributes within the geojson data, not just on how many points are clustered.

Does https://github.com/mapbox/mapbox-gl-js/issues/2412 cover this?
