### ISSUE TITLE
Intermittent sprite anti-aliasing rendering issue

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#2515]
![sprite-aliasing-issue](https://cloud.githubusercontent.com/assets/5607844/14924297/cdcd10ea-0e0f-11e6-9b4e-ceaabb2d8659.png)

Problematic in both Studio and our api. This issue is much more visible with icons with semi-transparent borders – I will get a screenshot of this if I can (I was seeing the issue on a map with these kinds of icons earlier today, but it started working again before I remembered to take a screenshot).

/cc @amyleew

**Comment by xrwang** [comment]
@nickidlugash this might be related to: https://github.com/mapbox/api-gl/issues/480, maybe an upstream gl issue? I'll update the other ticket.

**Comment by ansis** [comment]
Which icons don't look right?

If it's the blue ones with a white border, could it be that the border is just too narrow to render well at that resolution? If the icon is manually placed on top of a satellite tile outside of gl does it look better?

**Comment by nickidlugash** [comment]
@ansis Oh, perhaps this _is_ related to the issue @xrwang referenced. Seeing this now:

<img width="743" alt="screen shot 2016-04-29 at 4 38 58 pm" src="https://cloud.githubusercontent.com/assets/5607844/14929055/90f4a1b4-0e29-11e6-8461-94a5c4f7ee0b.png">

The highway shield has a solid white outline, and the other icons have a semi-transparent white outline. The fill pattern (which is also rendering incorrectly) is semi-transparent.

**Comment by ansis** [comment]
@nickidlugash where can I find the style and sprite for that image?

**Comment by lucaswoj** [comment]
I haven't seen this issue in a while. Please re-open if this is still a problem.
