### ISSUE TITLE
Add guidance labelling mode

### ISSUE THREAD

**Issue by yhahn** [mapbox/mapbox-gl-js#2518]
Capturing where I'm at with the experiments with guidance labelling.

- Branch: https://github.com/mapbox/mapbox-gl-js/tree/guidance-labelling
- Style spec: https://github.com/mapbox/mapbox-gl-style-spec/commits/guidance-labelling

**What it does**

- 2 new layout properties:
  - `text-unique: true`: uses label text to dedupe down to only a single label for a given string within a tile
  - `symbol-mode: guidance`: switches label placement mode to use the "guidance" approach
- Guidance approach:
  - Places labels close to the viewport center
  - Filtering labels for lines by an angle threshold (e.g. emphasizing cross streets)
  - Defined placement events at major changes to camera angle and aggressive label lockdown in-between to reduce popping/flickering

**What I feel confident in at this point**

- Guidance labelling is sufficiently different from basemap map labelling to have have a separate label placement mode.
- The approach in this branch is usable and a significant improvement over basemap labelling when designing guidance maps.
- It doesn't make sense to expose customizability to this in the style spec or our renderers beyond an on/off switch. I think we'll want to at least land cross-tile label placement before reconsidering this but for now exposing minimal API surface area on the feature makes most sense.

------

At the moment I've not given much attention to cleanliness of implementation. My next goals will be to clean up the code and add tests.

Most of the testing at this point has been through using http://github.com/mapbox/guidance-sim and using :eyes: which isn't going to be a sustainable approach to prevent regression going forward. I'll focus on setting up unit tests that can stress test the guidance approach, especially the strategies that prevent label flickering/popping.

**Next actions**

- [ ] @yhahn code cleanup, tests
- [ ] once ready, @ansis or @lucaswoj :eyes: for other approaches to cleanup/refactor

**Comment by lucaswoj** [comment]
@yhahn are you still planning to implement this feature in GL JS?

**Comment by yhahn** [comment]
Closing out -- achieved the usecase goals with https://github.com/mapbox/mapbox-gl-js/pull/2668
