### ISSUE TITLE
Make Map#flyTo respect maxBounds

### ISSUE THREAD

**Issue by cvn** [mapbox/mapbox-gl-js#2521]
Hello,

When using `flyTo` on a map with maxBounds set, it attempts to cross the antimeridian even if it can't. So instead of flying across the map, it flies into the edge. `easeTo` does not have this problem.

So, with a map with `maxBounds: [[-180,-85],[180,85]]`, starting at  `[-130, 60]`, and attempting to `flyTo([130, 60])`, you wind up at `[-164,60]` or so, depending on your zoom.

Here's a demo with mapbox-gl v0.18.0: http://jsbin.com/mogodi/edit?js,output

I suspect this was introduced #1857.

**Comment by lucaswoj** [comment]
related to #2801

**Comment by francoiscabrol** [comment]
any workaround? this problem is very frustrating

**Comment by cvn** [comment]
I commented out these lines and made a custom build: https://github.com/mapbox/mapbox-gl-js/blob/b9e10b9/src/ui/camera.js#L613-L621

It's not good, but it works if you need it.

**Comment by francoiscabrol** [comment]
Oh thanks! Your changes was merged, right? So is it going to be in the next release?

**Comment by cvn** [comment]
My suggestion is a workaround, not a fix. I'm not sure when a fix is coming.
