### ISSUE TITLE
background-pattern rendering problem at zoom > 0

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#2523]
Not sure when this was introduced, but definitely after [b9df775](https://github.com/mapbox/mapbox-gl-js/commit/b9df77549fe08fe582c9e282342171d952ccef77) because I was using the below steps to manual check my work along the way. 

**mapbox-gl-js version**: [924b770](https://github.com/mapbox/mapbox-gl-js/commit/924b77055a8dd20bf4f0dd034cdc9693d04cf549)

### Steps to Trigger Behavior

 1. add `map.setPaintProperty('background','background-pattern', 'fast-food-15')` to `debug/site.js`
 2. `npm start && open http://localhost:9966`
 3. behold

This does not cause the rendering tests to fail.

### Expected Behavior
hamburgers are rendered in the background layer at all zoom levels

### Actual Behavior

![gl-js-bug](https://cloud.githubusercontent.com/assets/2425307/15001780/441a334e-114f-11e6-8a23-8137a2cb0f49.gif)

It also triggers a bunch of the buffer extent errors
<img width="1000" alt="screen shot 2016-05-03 at 4 55 57 pm" src="https://cloud.githubusercontent.com/assets/2425307/15001879/1fe9f850-1150-11e6-96c4-d8412c907b24.png">

**Comment by jwarning** [comment]
I have the same issue after updating mapbox-gl from 0.16.0 to 0.18.0. A water pattern I had as a background renders with a similar black and white checker pattern as above.

**Comment by jfirebaugh** [comment]
@mollymerp Can you try using `git bisect` to pinpoint the commit where it stopped working?

**Comment by samanpwbb** [comment]
I'm running into broken background images on background layers as well:

![screen shot 2016-05-09 at 1 51 28 pm](https://cloud.githubusercontent.com/assets/108094/15122469/3e2b7dba-15ed-11e6-91b2-b84dcfdf10a3.png)

**Comment by mollymerp** [comment]
First bad commit is #2376 
I'll start looking into a fix.

**Comment by mollymerp** [comment]
After looking at the changed files and doing some eyeball testing, it looks like the bug only occurs when a symbol layer _with text_ and a background-pattern layer are in a style _together_ which is why the render tests were passing for both layer types individually.

I've isolated the problem to calling `drawSymbol` with `isText` set to `true`. Specifically, calling `glyphAtlas.updateTexture(gl)` is where the background pattern rendering gets messed up  (i.e. if I comment out [this line](https://github.com/mapbox/mapbox-gl-js/blob/master/js/render/draw_symbol.js#L151), the background-pattern loads correctly)

I'm not suuper familiar with image processing / texture rendering in GL but I'll continue looking around tomorrow to see if I can fix it.
