### ISSUE TITLE
Add option for bearing calculation

### ISSUE THREAD

**Issue by dresende** [mapbox/mapbox-gl-js#2527]
This is not a bug, just a possible improvement to the API. It would be really something if one could use `easeTo` or `jumpTo` and instead of:

```js
map.easeTo({
    center  : [ x, y ],
    bearing : b
});
```

One could avoid using bearing directly and pass another position that would serve as the location to where we want the map to be pointed to (from the center).

```js
map.easeTo({
    center   : [  x,  y ],
    lookAt   : [ x2, y2 ]
});
```

For anyone interested in this, I'm using this function that I did. I'm not 100% confident about it, but it works :)

```js
map.easeTo({
    center  : [  x,  y ],
    bearing : bearing([ x, y ], [ x2, y2 ])
});

function bearing(p1, p2) {
    var angle = Math.atan((p2[0] - p1[0]) / (p2[1] - p1[1])) * 180 / Math.PI;

    if (p1[1] > p2[1]) return angle;
    return angle + 180;
}
```

**Comment by jfirebaugh** [comment]
Thanks for the suggestion! Since this is simple to compute with `atan` as you show, I don't think we need to add the special-purpose option to the camera options.

**Comment by 1ec5** [comment]
For what it’s worth, we have this in the Mapbox iOS SDK, but it’s implemented at the SDK level, alongside other convenience methods. I agree that supporting it in the core camera options object would complicate the already complex code in `easeTo` and `flyTo`.

**Comment by dresende** [comment]
I just added as a suggestion since it's not that simple to make it right. I had quite some time to figure out I need the `if` condition for the 3rd and 4th quadrant.
