### ISSUE TITLE
The road to version version 1

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2528]
GL JS is almost three years old. If it were a human, it would be able to tell stories, ride a tricycle, and hop and stand on one foot for up to five seconds! (according to [WebMD](https://www.youtube.com/watch?v=eaIvk1cSyG8))

I have opened a [milestone](https://github.com/mapbox/mapbox-gl-js/milestones/v1.0.0) to track the tasks we want to complete before calling GL JS `v1.0.0`. Over the next few days, we can begin populating this milestone with issues. 

`v1.0.0` means that GL JS is stable, is unlikely to introduce breaking API changes in future versions, and has high-quality documentation. We can continue to develop new features in parallel with the `v1.0.0` milestone.

The `v1.0.0` milestone **will** include

 - release process improvements
 - testing infrastructure improvements
 - documentation improvements
 - API usability improvements that require breaking changes

With the intention of avoiding scope creep, the `v1.0.0` milestone **will not** include

 - new features that we want (even features that we _really_ want) (unless those features require breaking API changes) (this doesn't mean we aren't going to work on new features, just that they're parallel to our aspirations to release `v1.0.0`)

As with any written plan, this is a living document, open to discussion and amendment. Please share your 💭 ! 

cc @mapbox/gl @everybody

**Comment by mollymerp** [comment]
What do you envision for these changes?
> API usability improvements that require breaking changes

Also, would cross source label placement (#2516) be considered a new feature, or something we'd want to include in v1 ?

**Comment by lucaswoj** [comment]
> What do you envision for these changes?
> > API usability improvements that require breaking changes

I have a couple small ideas (suffixing all control classes with the word `Control`, i.e. `maboxgl.Navigation` -> `maboxgl.NavigationControl`) and a couple big ideas (redesign the Camera API to be simpler and more intuitive). I'll post more specific proposals as I have the time to think them through and write them down.

----

> Also, would cross source label placement (#2516) be considered a new feature, or something we'd want to include in v1 ?

I am very excited about shipping cross source label placement and it has higher priority than shipping `v1.0.0`!

The litmus test for whether or not a feature needs to be in the v1 milestone is "will this require breaking API changes?" I don't anticipate that cross source label placement will require any breaking API changes and therefore it should not be in the v1 milestone.

**Comment by mourner** [comment]
> API usability improvements that require breaking changes

I'd also add #2506 (newless API).

**Comment by dangerden** [comment]
Will you include a very important (for many people who previously used Leaflet as I see in the issues here) to create custom HTML pins (first of all for the dynamic images) into v1.0.0?
