### ISSUE TITLE
Unable to remove a fill-pattern from a layer

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#2534]
**mapbox-gl-js version**: 0.18.0

### Steps to Trigger Behavior

In Chrome 50

 1. create a layer with a fill-pattern
 2. use `map.setPaintProperty(layerId, 'fill-pattern', undefined)` to clear the pattern

### Expected Behavior

The pattern should be removed from the fill and the map should continue to be interactive and responsive to style mutations.

### Actual Behavior

The pattern is not removed, an error is sent on the console.

    Uncaught TypeError: Cannot read property 'stops' of undefined

<img width="480" alt="screen shot 2016-05-05 at 5 07 53 pm" src="https://cloud.githubusercontent.com/assets/302992/15057277/0fbda7f2-12e4-11e6-896c-7de997a0db19.png">

cc @lucaswoj

**Comment by samanpwbb** [comment]
I'm running into this when attempting to setstyle on line-dasharray

**Comment by jfirebaugh** [comment]
Flagging this as another case for https://github.com/mapbox/mapbox-gl-test-suite/issues/76 (refs https://github.com/mapbox/mapbox-gl-js/pull/2550).
