### ISSUE TITLE
Better communicate internal failures

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#2535]
https://github.com/mapbox/mapbox-gl-js/issues/2533 and https://github.com/mapbox/mapbox-gl-js/issues/2534 are issues that are easy to trigger in Studio. Both of these issues cause mapbox-gl-js to appear to hang; it stops responding to user input and style mutations.

There is no good way for Studio it know the gl-js rendering has stopped as no errors are thrown that are catchable, and no events are emitted. If gl-js was able to communicate its state, Studio could destroy the map and initialize a new map, causing a visual blip, but maintaining general working order.

Each recent release of mapbox-gl-js has fixed similar bugs and introduced new issues. It seems that these types are error happen and will continue to happen. Of course bug free code is ideal, but focusing on handling and communicating errors would go a long way.

**Comment by lucaswoj** [comment]
I synced up with @scothis this morning. A thrown error in the render loop was causing the render loop to stop running without any error events or catchable thrown errors.
