### ISSUE TITLE
Collisions not properly detected with custom data and map bearing

### ISSUE THREAD

**Issue by iambz** [mapbox/mapbox-gl-js#2536]
Hi!

I have an issue with the collision detection, bearing and custom data.

Quick JSFiddle that shows the issue with code from your examples (faster than a thousand words).

On launch, the markers are on top of each other, no collision, all OK.
Then, with a timeout, the map receives a setBearing(90). The content of the markers (text) flips correctly to stays in the viewport orientation, but not the collision boxes (they flip with the map. I activated them to see).
The markers now overlap, while they shouldn't.

Zoom in and out, rotate the map to see that the collisions are indeed detected, but with the collision boxes still oriented with the map.
Note that the data that comes with the style (street-v8) has collision boxes rotating correctly.

https://jsfiddle.net/berengerzyla/83bfphsr/6/

Using the last version of Mapbox (0.18)

**Comment by lucaswoj** [comment]
Fixed in the latest release https://jsfiddle.net/83bfphsr/10/
