### ISSUE TITLE
Resizing issue when working with ionic.

### ISSUE THREAD

**Issue by nicoabie** [mapbox/mapbox-gl-js#2539]
Due to the fact that mapbox listens to resize event, it may fall into a bug when working with ionic and not being on the current view.

**mapbox-gl-js version**: 0.18.0

### Steps to Trigger Behavior

 1. Use mapbox with ionic
 2. Navigate to other view
 3. Open soft keyboard
 4. Navigate to map view

### Expected Behavior
The map has the same size

### Actual Behavior
The map gets resized to default values (400*300)

Having an option to avoid resizing may mitigate the issue

**Comment by kristfal** [comment]
We've solved this by calling `resize()` on the map with debounced timer of 550ms whenever the viewport size changes. Depending on your app layout, you may just want to call resize whenever your map view appears. 

The timer is required to prevent rendering bugs that may occur if you call `resize()` while the keyboard is closing or opening.

**Comment by mourner** [comment]
Yeah, just call resize after the container size stabilizes.

**Comment by nicoabie** [comment]
@mourner if we fix it that way the user may see the map being resized.
Is it not feasible the possibility to add an option to not register the window resize event?

@kristfal thanks for the hack but I'd rather prevent resize event registration.

**Comment by mourner** [comment]
@nicoabie oh, yeah, that may be an easy thing to add — want to make a PR? Leaflet has a `trackResize` option and we could follow.

**Comment by nicoabie** [comment]
Sure thing @mourner, It would be great if this could land on 0.19.0. Thanks, I'll do it.

**Comment by nicoabie** [comment]
@johnbrattaker yeap, look into the documentation. You have to set `options.trackResize=false`.

**Comment by johnbrattaker** [comment]
thanks
yes this solves the problem, but it's no longer possible to enable landscape mode:)
