### ISSUE TITLE
Fix exception thrown when visiting API documentation URL with non-existant anchor

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#2540]
![2016-05-06 at 11 19 am](https://cloud.githubusercontent.com/assets/32314/15077474/7c6fd13e-137c-11e6-8b58-83fc96cb2a40.png)

Hashes that don't refer to IDs will trigger an error. Low-priority, doesn't affect page rendering.

**Comment by lucaswoj** [comment]
related to #2581
