### ISSUE TITLE
Directions example is not working correctly

### ISSUE THREAD

**Issue by emiltin** [mapbox/mapbox-gl-js#2545]
The example at https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/ is not working correctly with Chrome on Mac.

Dragging markers around causes markers to jump around erratically.

**Comment by lucaswoj** [comment]
Thanks for the report @emiltin! I can confirm the bug. Moving this issue to the appropriate repo: https://github.com/mapbox/mapbox-gl-directions/issues/67
