### ISSUE TITLE
Implement client-side hillshading

### ISSUE THREAD

**Issue by dpieri** [mapbox/mapbox-gl-js#2546]
**mapbox-gl-js version**: 0.18.0

The work that Mapzen has been doing on this looks very promising. https://mapzen.com/blog/elevation/

I'd love to be able to use this as traditional vector hillshading just isn't good enough for our needs. We've gone the pre-generated raster route, but would love to be able to drop that.

**Comment by lucaswoj** [comment]
cc @kkaefer

**Comment by dpieri** [comment]
Should this issue be closed in lieu of #3730?

**Comment by mollymerp** [comment]
yes! thanks @dpieri
