### ISSUE TITLE
How to trigger a queryRenderedFeatures for a layer at first load?

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#2549]
**mapbox-gl-js version**: 0.18.0

### Steps to Trigger Behavior

 1. A function which contains "var features = map.queryRenderedFeatures({layers: ['markers']});" etc.
 2. Trigger the function with "map.on('style.load', function)"
 
### Expected Behavior
At first load of the map the function is triggered.

### Actual Behavior
It is not triggered. No error message in console.

Further details:
The function is properly triggered when using some other events, e.g. "map.on('moveend', function);". Everything is working fine then.
I tried other events but none seem to give a trigger that works at first load of the map.
When using "map.on('load', function);" the console give following error:
![screenshot from 2016-05-09 22-38-41](https://cloud.githubusercontent.com/assets/10334123/15127416/e2c0ddb8-1636-11e6-9f38-45c7254478e4.png)

Which probably means the style of the layer is not yet ready loading...!? So that is why I use style.load but does not do anything it seems.

**Comment by lucaswoj** [comment]
Your code should work if you use the [`load`](https://www.mapbox.com/mapbox-gl-js/api/#Map.event:load) event instead of the `style.load` event. `style.load` is not part of the public API of GL JS.

**Comment by musicformellons** [comment]
'style.load' is used here:
https://www.mapbox.com/help/mapbox-gl-js-fundamentals/

**Comment by mourner** [comment]
Oh, we forgot to update it, sorry. сс @lyzidiamond
