### ISSUE TITLE
Back to online render

### ISSUE THREAD

**Issue by Nimble-Momonga** [mapbox/mapbox-gl-js#2556]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1.Go offline
 2.Search for a grey area
 3.Go back online

### Expected Behavior
Render the map when coming from offline
### Actual Behavior
The map stays without loading the grey area, the only way to load it's moving the map or with a zoom in/out

**Comment by indus** [comment]
https://github.com/mapbox/mapbox-gl-js/pull/2480/files#diff-3
(:worried: mixed up with another PR)

**Comment by kkaefer** [comment]
Closing in favor of #2564
