### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#256]
The repo has too many branches. We need to purge everything that's definitely not going to be used or was moved elsewhere, and move what makes sense to move to other repos. We can archive the current state of the repo somewhere so that no code is forever discarded while we have a clean repo here.

What we have now, with comments inline:
- [x] **gl**, updated 19 hours ago by mourner; — should be renamed to master?
- [x] **check-unused**, updated 18 hours ago by mourner; 1 commit — PR
- [x] **native**, updated 9 days ago by kkaefer; 59 commits — now lives in llmr-native?
- [ ] **gl-video**, updated 10 days ago by ansis; 2 commits — to be merged
- [x] **gl-ios**, updated 12 days ago by incanus; 529 commits — should this live in a separate repo?
- [x] **gl-ejecta**, updated 12 days ago by incanus; 37 commits
- [ ] **gl-editor**, updated 14 days ago by edenh; 27 commits
- [ ] **gl-pencil**, updated 23 days ago by edenh; 2 commits — pencil demo
- [ ] **gl-vector-tiles**, updated 23 days ago by kkaefer; 1 commit — vector hills styling demo
- [x] **ios**, updated a month ago by kkaefer; 11 commits — superseded by llmr-native and possibly a separate ios repo?
- [x] **ios-stencil**, updated 2 months ago by kkaefer; 7 commits — the same
- [ ] **gl-headless**, updated 2 months ago by kkaefer; 20 commits
- [ ] **gl-oscim-tiles**, updated 2 months ago by kkaefer; 3 commits — demo with opensciencemap.org tile format
- [ ] **gl-vectiles**, updated 3 months ago by kkaefer; 1 commit — demo with Migurski vectiles format
- [x] **gl-rotationlabels**, updated 3 months ago by ansis; 2 commits — is this relevant?
- [x] **gl-interaction**, updated 4 months ago by ansis; 2 commits — alternative mouse interaction with grid index, is this relevant?
- [x] **gl-sdf**, updated 4 months ago by kkaefer; 32 commits — SDF fonts, relevant for fontserver repo?
- [x] **gl-bloop**, updated 4 months ago by ansis; 1 commit — alternative dash rendering?
- [x] **gl-imagefill**, updated 4 months ago by ansis; 3 commits — will be merged?
- [x] **sdf-generator**, updated 5 months ago by kkaefer; 2 commits — should be a separate repo or included in fontserver repo?
- [x] **tessellate**, updated 5 months ago by kkaefer; 18 commits — should be a separate repo or a fontserver branch?
- [x] **fontinfo**, updated 5 months ago by kkaefer; 4 commits — a fontserver tool?
- [x] **gl-lines**, updated 5 months ago by kkaefer; 49 commits — some old line rendering experiments?
- [x] **gl-satellite**, updated 5 months ago by dmitrig01; 7 commits — old raster support branch, not relevant now?
- [x] **gl-lines-texture**, updated 5 months ago by kkaefer; 42 commits — old experiments with line textures, not relevant now?
- [x] **statistics**, updated 5 months ago by dmitrig01; 1 commit — some old script getting stats from cached vector files
- [x] **gl-rotation-mouse**, updated 5 months ago by dmitrig01; 16 commits — old rotation code, not relevant now?
- [x] **gl-rotation**, updated 5 months ago by dmitrig01; 10 commits — old rotation code, not relevant now?
- [x] **svg-labelling**, updated 6 months ago by kkaefer; 2 commits — failed labelling experiment, not relevant now?
- [x] **emscripten**, updated 7 months ago by kkaefer; 5 commits — old experiments using Emscripten with canvas 2D renderer
- [x] **gh-pages**, updated 7 months ago by kkaefer; 5 commits — old experiments with canvas 2D renderer
- [x] **wrapper**, updated 10 months ago by kkaefer; 10 commits — old experiments
- [x] **lua**, updated 11 months ago by kkaefer; 11 commits — lua experiments, superseded by llmr-native?
- [x] **master**, updated 11 months ago by springmeyer; 20 commits — some really old Dane's code that's superseded by llmr-native?

Please update the comments as you see fit.

**Comment by BramOoms** [comment]
@mourner I'm interested in the work done in the gl-imagefill branch. Is this code still available somewhere?
