### ISSUE TITLE
Incorrect rendering in Chrome 50 in Debian 8.

### ISSUE THREAD

**Issue by smakhtin** [mapbox/mapbox-gl-js#2571]
Hello, I'm using Chrome 50 in Debian 8 with Nvidia Driver 352.55. In this system, all Mapbox GL maps look like this: ![](http://i.imgur.com/FLZ8trw.png) I think something goes wrong with polygons before rasterization  step. Maybe wrong vertex indexes or something like this. In current Firefox everything works fine.

**Comment by mourner** [comment]
Can you try the version from the `earcut-final` branch and see if it looks the same?

**Comment by mourner** [comment]
It was merged to the master branch so you can now try it too.

**Comment by ansis** [comment]
This looks similar to https://github.com/mapbox/mapbox-gl-js/issues/2473 which was fixed in https://github.com/mapbox/mapbox-gl-js/pull/2553

**Comment by lucaswoj** [comment]
I assume this was fixed in https://github.com/mapbox/mapbox-gl-js/pull/2553
