### ISSUE TITLE
map.getCenter() longitude values fall outside of possible range [-180, 180]

### ISSUE THREAD

**Issue by bbbford** [mapbox/mapbox-gl-js#2572]
**mapbox-gl-js version**: 0.18.0

### Steps to Trigger Behavior

 1. Zoom map out
 2. Pan map to the east or the west - go all the way around the world
 3. Notice the output of map.getCenter()
 4. Longitude value continues to increase or decrease indefinitely, putting it outside the bounds of [-180, 180] degrees

### Expected Behavior
Longitude should never fall outside [-180, 180]

### Actual Behavior
Longitude increases or decreases indefinitely

### Screenshot
![image](https://cloud.githubusercontent.com/assets/5225875/15293978/fd6f6d78-1b4f-11e6-82dd-fa463e92d925.png)

### Workaround
I have found this work-around, however it is not ideal because it limits panning capabilities.
Set the map.transform.lngRange as such:
map.transform.lngRange = [-180, 180];

**Comment by ryanbaumann** [comment]
Similar to #2507

**Comment by tmcw** [comment]
The LngLat object already has a `.wrap()` method that works for this case https://github.com/mapbox/mapbox-gl-js/blob/master/js/geo/lng_lat.js#L45

I think the `getCenter()` behavior is correct: it is useful to differentiate between [-180, 180] and other worlds.

**Comment by ryanbaumann** [comment]
@tmcw Awesome, will be testing .wrap() today!

**Comment by bbbford** [comment]
@tmcw Brilliant!

`var center = map.getCenter().wrap()`
