### ISSUE TITLE
scrollZoom: false doesn't disable ScrollZoomHandler

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#2575]
when instantiating a Map object, setting `scrollZoom: false` doesn't actually disable scroll zooming. 
```js
var map = new mapboxgl.Map({
  center: [-73.9921, 40.74],
  zoom: 13,
 // this doesn't work 
  scrollZoom: false,
  container: "map",
  style: "mapbox://styles/mapbox/light-v9"
});
```
you have to call `map.scrollZoom.disable()` after instantiation to get the desired behavior

example here: http://jsbin.com/logeyosame/edit?html,output
the first release where this happens is  `0.16.0`
first bad commit is [f8dac7e](https://github.com/mapbox/mapbox-gl-js/commit/f8dac7e38601f5b5904185e82020f3cc1b0c944e)

**Comment by bsudekum** [comment]
Also seeing this.

**Comment by mourner** [comment]
@lucaswoj the fix should be a matter of readding `options = this.options = ...`. Are you OK with this?

**Comment by lucaswoj** [comment]
@mourner My intent in https://github.com/mapbox/mapbox-gl-js/pull/2286 was to remove `map.options` (looks like I didn't do a great job). There are clean solutions to this regression that don't require restoring `map.options`. 

ref #1550
