### ISSUE TITLE
Fix documentation anchors

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#2581]
Expand the documentation section for a method on https://www.mapbox.com/mapbox-gl-js/api/.

Expected behavior: URL anchor updates to a permalink for that method.

Actual behavior: It doesn't. In the JS console: Uncaught TypeError: Cannot read property 'classList' of undefined.

**Comment by lyzidiamond** [comment]
I'm no longer seeing this issue clicking around the docs -- good to close here?

**Comment by jfirebaugh** [comment]
I don't see the JS error in the console, but expanding the documentation section for a method still doesn't update the URL hash.

**Comment by lucaswoj** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-js/pull/3015 🎉
