### ISSUE TITLE
Add a "popup.close" event

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2584]
Popups should emit an event when they are closed.

**Comment by mapsam** [comment]
This is complete!

**Comment by nibygro** [comment]
Ho. How can I listen to it?

```js
    map.on('popup.close', function(e) {
        alert();
    });
```

doesn't work

**Comment by Luqqk** [comment]
@nibygro try listen to it this way:

```javascript
let popup = new mapboxgl.Popup()
popup.on('close', function(e) {
    alert()
})
```

**Comment by nibygro** [comment]
@Luqqk it works, thanx!

**Comment by mapsam** [comment]
Thanks @Luqqk!

**Comment by ansarikhurshid786** [comment]
It is working but pupup close event fire twice when open and close.

**Comment by styledev** [comment]
I am also seeing popup.on('close', ...) fire on creation, and then twice on close.

**Comment by pragsjain** [comment]
> @nibygro try listen to it this way:
> 
> ```js
> let popup = new mapboxgl.Popup()
> popup.on('close', function(e) {
>     alert()
> })
> ```

not working for me

**Comment by Matvik** [comment]
Same thing, this event fires in wrong time ((((

**Comment by alexshk** [comment]
I am also seeing popup.on('close', ...) fire on creation, and then twice on close too

**Comment by hvma411** [comment]
We have 2024 and 'close' event still appears on popup creation 🙄

**Comment by yunylz** [comment]
updates?

**Comment by AnmolSaini16** [comment]
If the close event in React is firing twice, this fix worked for me: adding the `pop.off()` listener before the `remove` listener.
```
    useEffect(() => {
        if (!map) return;

        const popup = new mapboxgl.Popup(options).setLngLat([longitude, latitude]).addTo(map);

        popup.on('close', handleClose);

        return () => {
            popup.off('close', handleClose);
            if (popup.isOpen()) {
                popup.remove();
            }
        };
    }, [map]);
```
