### ISSUE TITLE
Many "not found" errors in console

### ISSUE THREAD

**Issue by yuvadm** [mapbox/mapbox-gl-js#2587]
**mapbox-gl-js version**:
0.18.0

### Steps to Trigger Behavior

 1. In my mapbox application browser console, I'm seeing lots of errors that look like this

```js
Error: Not Found
```

with the following stack trace:

```js
.onError() bundle.js:27855
Evented.fire() bundle.js:29041
._forwardTileEvent() bundle.js:27877
Evented.fire() bundle.js:29041
Style.prototype<._forwardTileEvent() bundle.js:29963
Evented.fire() bundle.js:29041
VectorTileSource.prototype<._tileLoaded() bundle.js:48212
Actor.prototype.receive()
```

However, I don't believe I'm actually seeing anything wrong with how the map looks.

Are these errors something I need to worry about?

**Comment by mourner** [comment]
Can you provide a JSFiddle that triggers those errors?

**Comment by yuvadm** [comment]
@mourner I have a live example running on https://daat-hamakom.herokuapp.com it's not minimal by any means

**Comment by jfirebaugh** [comment]
You don't need to worry about these errors, and we have plans to suppress them: #1800.

**Comment by yuvadm** [comment]
@jfirebaugh that's great, good to know these aren't real errors!
