### ISSUE TITLE
Weird artifacts on Samsung mobile

### ISSUE THREAD

**Issue by viki53** [mapbox/mapbox-gl-js#2589]
Hi,

I just integrated Mapbox GL into a mobile (Ionic) app where we already use the regular JS version, in order to improve performance and test some new features.

So, I started by trying on a basic map which worked fine on my phone (*LG Nexus 4*) and some others (*HTC One* & *One Plus One*), but on a *Samsung Galaxy S6* we started seeing some artifacts appear.

**mapbox-gl-js version**: 0.18.0 (downloaded just a few hours ago)

### Steps to Trigger Behavior

 1. Use the following code:
```
new mapboxgl.Map({
    container: 'mapbox-map',
    style: 'mapbox://styles/mapbox/streets-v8'
})
```
 2. Test on a Samsung Galaxy S6 (possibly other devices)
 3. Try zooming in and out

### Expected Behavior

No artifacts

### Actual Behavior

Artifacts (see following screenshots) depending on location and zoom

![screenshot_20160518-152827](https://cloud.githubusercontent.com/assets/1763364/15360811/718c25e6-1d0f-11e6-8a97-885ce4c1989a.png)
![screenshot_20160518-152818](https://cloud.githubusercontent.com/assets/1763364/15360812/719e6eae-1d0f-11e6-98ea-a036f0e4e9e0.png)
![screenshot_20160518-152836](https://cloud.githubusercontent.com/assets/1763364/15360813/71a81486-1d0f-11e6-8917-163c920bb0ad.png)
![screenshot_20160518-152803](https://cloud.githubusercontent.com/assets/1763364/15360814/71a952ba-1d0f-11e6-855d-254a3c05b5db.png)

**Comment by mourner** [comment]
This may have been fixed by the recently merged #1606. Can you try the master branch version?

**Comment by viki53** [comment]
Thanks for the quick answer!

Is there a file that I can download directly to replace the `https://api.tiles.mapbox.com/mapbox-gl-js/v0.18.0/mapbox-gl.js` one? I'll get to testing right away

**Comment by mourner** [comment]
@viki53 you can build it by cloning the repo, then running `npm install && npm run production`, which will generate `dist/mapbox-gl.js`.

**Comment by viki53** [comment]
Seems much better! Thanks!
