### ISSUE TITLE
Review TileJSON support

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2590]
As a follow-up to #2565, we should review the TileJSON spec and document which features we
- already support
- should support
- won't support

cc @mourner @tmcw @jfirebaugh @indus @lyzidiamond @danswick

**Comment by lucaswoj** [comment]
related to #1775

**Comment by jfirebaugh** [comment]
Closing; I'm confident we're supporting what we want to (`tiles`, `attribution`, `minzoom`, `maxzoom`, `bounds`) and not supporting what we don't (everything else).
