### ISSUE TITLE
Document all options in the Map constructor

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#2603]
Hi, When I check the mapbox gl js api docs, in example:
```
var map = new mapboxgl.Map({
  container: 'map',
  center: [-122.420679, 37.772537],
  zoom: 13,
  style: style_object,
  hash: true
});
```
I found that `center` and `zoom` are not in options of map instance, I checked the code here:
https://github.com/mapbox/mapbox-gl-js/blob/mb-pages/js/ui/map.js#L155-L158

found that `bearing` and `pitch` are also undocumented. Maybe these options are set as default if they are not provided in `style`, or trying to overwrite options in style.

All in all, I think this part should be clarified.

**Comment by lucaswoj** [comment]
Agreed! I'll hit this soon.

**Comment by lucaswoj** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-js/pull/2651
