### ISSUE TITLE
Rendering of imagery fails on Android Chrome

### ISSUE THREAD

**Issue by pastcompute** [mapbox/mapbox-gl-js#2605]
**mapbox-gl-js version**: v0.17.0 running in Chrome 52 on Android

### Steps to Trigger Behavior

 1. Load a map using mapbox-gl.js API
 2. In `on('load')` handler, add a source and layer. I used a point and a linestring.
 3. Pan the map

### Expected Behavior

Map should pan, with imagery and additional layers visible.

### Actual Behavior

Map goes blank. However you still see the point and the line string.
Webgl per-se appears to be working, if you load a map and do nothing else at all, it renders fine.
This test works on Firefox on Android, and every browser I tested on Windows 10 & Linux.
The test fails on Chrome 52 (I assume the latest) on my Android tablet, an Acer A1-810 running Android 4.2.2

I have some screenshots at http://blog.oldcomputerjunk.net/2016/mapbox-android-chrome-bug/

The script I abstracted to repeat this is at https://github.com/pastcompute/html5-demos/blob/master/mapbox-chrome52-android-bug.html

I also noticed in adb the following many times repeated:

```
[INFO:CONSOLE(0)] "[.Offscreen-For-WebGL-0x5f0de500]RENDER WARNING: there is no texture bound to the unit 1", source: 
```

I'm hoping to acquire a newer Android device sometime this week to test further.
Of course its possible this is specific to this particular tablet, but I thought I'd post it in case others had similar issues.

**Comment by lucaswoj** [comment]
This was likely fixed by #2509. Please re-open if it was not.
