### ISSUE TITLE
Check if map is ready to queryRenderedFeatures

### ISSUE THREAD

**Issue by gertcuykens** [mapbox/mapbox-gl-js#2614]
Think this is a common mistake http://stackoverflow.com/questions/37400481/check-if-map-is-ready-to-queryrenderedfeatures/37400911#37400911

```js
map.on('mousemove', function (e) {
    if (!map.loaded()) return; // if you forget this you get error below the first few seconds
    map.getCanvas().style.cursor = ''
    var features = map.queryRenderedFeatures(e.point, {layers: ['markers']})
    if (!features.length) return;
    map.getCanvas().style.cursor = 'pointer'
});
```
I am not a expert how to optimise this, but I believe mabox should optimise and check this for us and just `return {}` if map not loaded?

![image](https://cloud.githubusercontent.com/assets/863731/15485435/8ff8c014-213f-11e6-8a12-ed0ed66ba12e.png)

Maybe a simple `if (!this.map) return{};` will do above `var styleLayers = this.map.style._layers;`?

**Comment by SirLee** [comment]
Did this get put into 0.19.1? I'm still encountering this problem. 'features' is undefined as queryRenderedFeatures `map.on('click', function(e) {
    if(!map.loaded()) return;
    var features = map.queryRenderedFeatures(e.point, {layers: ['markers']});
    
    
    if(!features.length) return;
    
    var feature = features[0];
    //alert(feature.properties.state_abbr);
    var state_name = features[0].properties.state_abbr;
    if (features.length){
        var ele = document.getElementById(features[0].properties.state_abbr);
        var x = ele.scrollLeft;
        var height = window.innerHeight;
        var y = ele.offsetTop - 300;
        //alert(x + " " + y);
        window.scrollTo(x, y);
    }
});`

What am I missing here?
