### ISSUE TITLE
GeoJSON source with null geometry

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#2616]
http://jsbin.com/busubabude/edit?html,output

as per that example, loading a GeoJSON source with geometry: null causes the error `TypeError: Cannot read property 'type' of null`.

As per the GeoJSON spec at http://geojson.org/geojson-spec.html#feature-objects "The value of the geometry member is a geometry object as defined above or a JSON null value."

I would expect mapbox-gl-js to silently ignore this feature and continue processing other features rather than throwing an error.

I've been trying to nail down the code causing this error, but I can't trace it back in Chrome dev tools.

**Comment by tmcw** [comment]
Maybe we should create a geojson-spectrum testcase that contains all valid geojson forms, so we can identify this kind of issue faster.

**Comment by emakarov** [comment]
+1 for this issue. I have also error with null geometry -
`TypeError: Cannot read property 'coordinates' of null`

**Comment by tmcw** [comment]
geojson-vt has this issue already fixed, by @andrewharvey ! https://github.com/mapbox/geojson-vt/blob/master/src/convert.js#L27 

But distributions of mapbox-gl-js are apparently using an older version that doesn't include the early check.

**Comment by andrewharvey** [comment]
@tmcw Yeah I fixed it in geojson-vt a while back, which makes it annoying as I spent hours trying to find the root cause in mapbox-gl-js but when the error is thrown the stacktrace in Chrome dev tools never let me identify the exact line where it was trying to read the property of null.

So moving forward it looks like you'll need to do a release of geojson-vt then update mapbox-gl-js to use the updated version?

/cc @mourner

**Comment by mourner** [comment]
Should be fixed.
