### ISSUE TITLE
Existential Filter "has", "!has" does not work

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-js#2617]
**mapbox-gl-js version**: v0.18.0

### Steps to Trigger Behavior

 1. Read up on Existential Filters at https://www.mapbox.com/mapbox-gl-style-spec/#types-filter
 2. Create a style with an Existential Filter like [ "!has", "ROTATE" ].

### Expected Behavior

Features with the ROTATE attribute should not be drawn.

### Actual Behavior

The map is not drawn, and the following are written to the console:
Error: layers[45].filter[0]: expected one of [==, !=, >, >=, <, <=, in, !in, all, any, none], !has found

**Comment by mourner** [comment]
Did you use v0.18 from the CDN or did you build it yourself?

**Comment by halset** [comment]
From the CDN. https://api.tiles.mapbox.com/mapbox-gl-js/v0.18.0/mapbox-gl.js

**Comment by mourner** [comment]
Can you also make a minimal JSFiddle test case please?

**Comment by jfirebaugh** [comment]
Support for `has`/`!has` filters isn't in any released version yet. It will be in the next release.

**Comment by halset** [comment]
@jfirebaugh Thanks! I got confused by the doc on https://www.mapbox.com/mapbox-gl-style-spec/#types-filter , but that is not a problem. Found a workaround for my case.

**Comment by suryan-airmap** [comment]
Has this fix made into the release?

**Comment by suryan-airmap** [comment]
Or is there a good work around for now?

**Comment by lucaswoj** [comment]
@suryan-airmap yes, this feature is included in the latest release
