### ISSUE TITLE
How to get source that's added in Mapbox Studio

### ISSUE THREAD

**Issue by johnnyluu** [mapbox/mapbox-gl-js#2625]
**mapbox-gl-js version**: 0.18

### Steps to Trigger Behavior

 1. add a geojson tile and add layer to a style 
 2. query the style using querySourceFeatures('sourceid') using the mapboxGL JS library;
 3. query the source using getSource('sourceid')

### Expected Behavior
Return a array of features
### Actual Behavior
querysourcefeatures returns an empty array, getSource returns undefined.

I'm not sure how to find the source id of a source I added on mapbox studio. Or is it even possible to do so? Thanks!

**Comment by johnnyluu** [comment]
Just figured it out: map.querySourceFeatures('composite', {sourceLayer: 'source-name', filter: [filters]}). Mapbox Studio really needs some documentation. All the google search results were about mapbox studio classic.

**Comment by mourner** [comment]
Thanks for the report! Tagging @mapbox/support to address this in the docs.

**Comment by teledemic** [comment]
Important to note (got burned by this) - querySourceFeatures will only return the features that are onscreen. Which could be a small subset of the whole sourceLayer.

**Comment by 1ec5** [comment]
Good point. Here’s what the documentation currently says about [`querySourceFeatures`](https://www.mapbox.com/mapbox-gl-js/api/#map#querysourcefeatures):

> In contrast to Map#queryRenderedFeatures, this function returns all features matching the query parameters, whether or not they are rendered by the current style (i.e. visible). The domain of the query includes all currently-loaded vector tiles and GeoJSON source tiles: this function does not check tiles outside the currently visible viewport.

**Comment by seanjhulse** [comment]
So how are we supposed to actually get a full list of GeoJSON features? I don't want to have to query everytime a user zooms or pans, but querySourceFeatures seems like the only way to get an array of features once the style is applied to the map.
