### ISSUE TITLE
Problem with showing linestrings ending with same points

### ISSUE THREAD

**Issue by ptpt** [mapbox/mapbox-gl-js#2627]
**mapbox-gl-js version**: v0.18.0
**tile spec version**: 1

### Description
If a linestring ends with two same points, the last non-zero-length linesegment will not show up.

### Steps to Trigger Behavior

 1. Install mapbox-vector-tile

    ```sh
    pip install mapbox-vector-tile
    ```

 2. Generate the tile

    ```python
    import mapbox_vector_tile as mvt
    # Only half of the first linestring will show, i.e. from (0 0) to (2000 2000). (2000 2000) to (4000 4000) won't show
    features = [{'geometry': 'LINESTRING (0 0, 2000 2000, 4000 4000, 4000 4000)'}, {'geometry': 'LINESTRING (0 4000, 4000 0)'}]
    layer = {'name': 'foo', 'features': features}
    tile = mvt.encode(layer)
    with open('tile.mvt', 'w') as f:
        f.write(tile)
    ```
 3. Show this tile on a map

### Expected Behavior
![screenshot from 2016-05-26 19-19-02](https://cloud.githubusercontent.com/assets/87357/15583597/c6506eda-2376-11e6-96fa-e14b3260bb3a.png)
### Actual Behavior

![screenshot from 2016-05-26 19-17-44](https://cloud.githubusercontent.com/assets/87357/15583607/d69576e6-2376-11e6-9ef7-9badb943b3ba.png)

**Comment by mourner** [comment]
Are you sure this is an issue with GL JS rendering, not with python mapnik-vector-tile package encoding?

**Comment by ptpt** [comment]
@mourner The thing I'm sure is that it didn't miss any coordinate, to verify it:

```python
content = open('tile.mvt').read()
mvt.decode(content)
# it returns:
#{u'foo': {'extent': 4096,
#  'features': [{'geometry': [[0, 0], [2000, 2000], [4000, 4000], [4000, 4000]],
#    'id': 0,
#    'properties': {},
#    'type': 2},
#   {'geometry': [[0, 4000], [4000, 0]], 'id': 0, 'properties': {}, 'type': 2}],
#  'version': 1}}
```

Would be great if you can verify it using other libraries.

Here is the tile:
[tile.mvt.tar.gz](https://github.com/mapbox/mapbox-gl-js/files/285323/tile.mvt.tar.gz)

**Comment by lucaswoj** [comment]
I suspect this is a bug in the vector tile encoding, not GL JS. Closing as we have not seen the issue since.
