### ISSUE TITLE
Glyph overflow

### ISSUE THREAD

**Issue by haoshengfucn** [mapbox/mapbox-gl-js#2632]
in the glyph_source.js, the glyph bitmap is 512X512，in the english languages countries, it is ok. but  if switch to china, 512X512 is not enought. "glyph bitmap overflow" happens.

**Comment by haoshengfucn** [comment]
in the glyph_source.js, the glyph bitmap is 512X512，in the english languages countries, it is ok. but if switch to china, 512X512 is not enought. "glyph bitmap overflow" happens.

**Comment by jingsam** [comment]
A glyph bitmap only have 255 glyph, so I think 512X512 is big enough to support 255 Chinese characters. One font will be split into multiple  glyph bitmaps, such as 0-255, 256-512...

**Comment by 1ec5** [comment]
Duplicate of #1681.

**Comment by 1ec5** [comment]
Whoops, I was thinking of mapbox/mapbox-gl-native#1681, which is the same issue in the Mapbox iOS and Android SDKs. Sorry for the confusion.

**Comment by jfirebaugh** [comment]
Duplicate of #141.
