### ISSUE TITLE
ez [SUGGESTION] -- Gitter room(s) pls :)

### ISSUE THREAD

**Issue by tiagocpontesp** [mapbox/mapbox-gl-js#2634]

**Comment by tmcw** [comment]
Hi Tiago!

Thanks for the suggestion! While we'd love to have the capacity to have a Gitter chat, and likely other venues like IRC, right now we'd like to keep conversation to GitHub, StackOverflow and the Mapbox support channel. Unfortunately, the lead developers simply don't have the extra time to idle in another chat room in addition to answering questions here, and we don't want to give the impression that Gitter is another venue for help when, in practice, our previous attempts at using Gitter have led to unanswered questions in a nearly-empty room, which is bound to be a downer.

Down the line, we might reconsider this decision - if we have more capacity or Gitter sets up a better system for asynchronous discussions. But for now we're going to keep it simple - feel free to ask any questions here on GitHub!

- Tom

**Comment by tiagocpontesp** [comment]
Thank you for the detailed answer. :)
I was only hoping for a chatroom where onboarders could help eachother.

FYI It seems the react guys have switched over to [discord](https://discordapp.com/.). 
Can't say much about it since I've only spent a minute there today, but it looks pretty slick.
