### ISSUE TITLE
road net display error on android chrome

### ISSUE THREAD

**Issue by haoshengfucn** [mapbox/mapbox-gl-js#2637]
**mapbox-gl-js version**:

Hi, I found the road polyline was not displayed correctly on android chrome. some road segment was not displayed.   
![mapboxgl](https://cloud.githubusercontent.com/assets/2070290/15669219/be039778-2751-11e6-82cf-c076a85a5fa1.png)

**Comment by haoshengfucn** [comment]
i think it is a serial problem. when the map is tilted. lots of road can't be displayed correctly.

**Comment by mourner** [comment]
@haoshengfucn what GL JS version are you using? What version of Android and Chrome? What mobile device?

**Comment by lucaswoj** [comment]
Closing as stale because requested clarification has not been provided.
