### ISSUE TITLE
Allow Map#setFilter to accept null or undefined to remove a filter

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#2638]
[Map#setFilter exists](https://www.mapbox.com/mapbox-gl-js/api/#Map#setFilter) but there is no removeFilter method to remove it again, given that [it is optional](https://www.mapbox.com/mapbox-gl-style-spec/#layer-filter). You can `setFilter(layer, ["all"])` but it doesn't seem as clean as being able to remove the filter.

**Comment by lucaswoj** [comment]
👍 we should support a better API here 

The precedent within GL JS is to use `setFilter(layer, null)` to remove a filter (this is, for example, how you remove a paint or layout property).

**Comment by andrewharvey** [comment]
I tried `setFilter(layer, null)` but it gives the error:
```
Error: layers.mylayer.filter: array expected, null found(…)
util.extend.onError	@	map.js:906
Evented.fire	@	evented.js:87
util.extend._forwardStyleEvent	@	map.js:916
Evented.fire	@	evented.js:87
throwErrors	@	validate_style.js:8
util.inherit._handleErrors	@	style.js:656
util.inherit.setFilter	@	style.js:501
util.extend.setFilter	@	map.js:620
```

**Comment by jfirebaugh** [comment]
This is implemented and [tested](https://github.com/mapbox/mapbox-gl-test-suite/tree/master/render-tests/runtime-styling/filter-false-to-default).

**Comment by andrewharvey** [comment]
> This is implemented and tested.

Since that link is dead now, for anyone else landing here the syntax to remove a filter is:

`map.setFilter('layer', null);`
