### ISSUE TITLE
Add "Using Mapbox GL JS with other module systems" to API docs quickstart

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2644]
We now have [webpack instructions in our `README.md`](https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-webpack) (Thanks @tmcw!). We should update the API docs "Getting Started" for parity. 

cc @tmcw @lyzidiamond

**Comment by contra** [comment]
Should be closed since webpack support was removed

**Comment by lucaswoj** [comment]
We still [support Webpack and other module systems](https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-other-module-systems). This information should still make its way to our [API docs quickstart guide](https://www.mapbox.com/mapbox-gl-js/api/). I will modify the issue title to reflect the pivot.

**Comment by lucaswoj** [comment]
Done in #4267
