### ISSUE TITLE
Inconsistent drag behaviour, sometimes system/browser drag behaviors takes over

### ISSUE THREAD

**Issue by livemixlove** [mapbox/mapbox-gl-js#2645]
Hi There,

I've implemented a drag/drop system similar to the https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/ example.  It works most of the time, but sometimes after starting to drag a feature on the map, the system drag behavior takes over and shows me a little paper icon.  Is there a e.preventDefault() or some equivalent that I should be using to prevent this?

I'm using the latest v18 version.  Attached is a screenshot (the cursor is missing due to OSX screen capture).  

<img width="119" alt="screen shot 2016-05-31 at 3 09 12 pm" src="https://cloud.githubusercontent.com/assets/148947/15692644/7d99e56e-2744-11e6-841c-1d1ef529de9f.png">

**Comment by mourner** [comment]
Can you set up a minimal JSFiddle test case? The issue doesn't seem to reproduce on the example. You can use `e.originalEvent` in events to do things like `stopPropagation` or `preventDefault`.

**Comment by livemixlove** [comment]
I think I misspoke.  I was actually testing on v17.  I am not able to reproduce on v.18.

**Comment by jfirebaugh** [comment]
Great, glad to hear that it's working in more recent versions!
