### ISSUE TITLE
Fix bug preventing "queryRenderedFeatures" from returning all features

### ISSUE THREAD

**Issue by cammanderson** [mapbox/mapbox-gl-js#2647]
Hi Guys, 

Love your work. 

I think that we may have a bug to contribute. Something that is unexpected and unpredictable behaviour around the queryRenderedFeatures API call on map. We observe occasions where the map markers are returned, and then other occasions that they are not - despite them still being rendered and no changes to layers/sources - just moving/zooming the map.

Please see the following code pen showing the issue;
http://codepen.io/cammanderson/pen/bc7ceb108e340cb30fa524ff982e761d?editors=1010

**mapbox-gl-js version**: 0.19.0

### Steps to Trigger Behavior

 1. Open your browser console
 2. Position the map viewport over Barcelona map marker (so it is only visible)
 3. Zoom in and out over this marker while the marker is still in view
 4. Watch the features that are console.logged/returned by the calling queryRenderedFeatures method

### Expected Behavior

The console should always show the map marker for Barcelona while you zoom in and zoom out. queryRenderedFeatures should always return the markers that are rendered on screen.

### Actual Behavior

There are occasions where the marker will not be returned while zooming in and out. It is like at some stages the marker is no longer present, even though it is rendered on screen at that time.

This can sometimes happen on dragging the map around, like it shows up in the top-right quadrant of the screen, but then disappears from being returned when on the bottom right. This seems to change as you move around the map. 

Let me know if my example has errors, if so, it's been a long day sorry. But I observed this on our application, then was able to reproduce this using codepen (just trying to make sure it wasn't just our code implementation in our app).

Thanks guys, 
Cheers
Cam

**Comment by lucaswoj** [comment]
I can confirm that `queryRenderedFeatures` is broken in the way you describe in this example.

**Comment by x9xjdzz9eaeeghcrar9c** [comment]
I'm also affected by this bug. I took the "Highlight features within a bounding box" example, and changed it to show the bug. I find that it only happens with symbol layers and only when you change from the initial zoom level. So, with the attached program, hold down shift to drag a rectangle and you will see that only some of the points are selected (they are colored red when selected). But it only happens after you have zoomed in or out.

[map.zip](https://github.com/mapbox/mapbox-gl-js/files/418718/map.zip)

**Comment by jmcazaux** [comment]
We are affected as well here.

Is there a workaround we can use until this is solved ?

**Comment by stevelacy** [comment]
I initially thought that the issue was solved by #2988, but after upgrading I can confirm that the issue still exists.

**Comment by x9xjdzz9** [comment]
This may require a different issue, but if I zoom out and features are hidden behind each other, or another layer is on top of the features from the layer I'm selecting from, the hidden features are not selected.

**Comment by benjamintd** [comment]
I ran into this bug too. From what I understand, I traced it to [this tilesIn method](https://github.com/mapbox/mapbox-gl-js/blob/9ef3584c2aec81e863324310e142e817bd3e50f2/js/source/source_cache.js#L456) behaving weirdly on non-integer zoom levels. This bug appears [here](http://www.benjamintd.com/climbing-map/): when points are in the right-most or bottom-most tiles, they do not get queried at intermediary zoom levels.

**Comment by 1ec5** [comment]
Possibly related to mapbox/mapbox-gl-native#6055.

**Comment by brunoabinader** [comment]
There is an issue affecting symbol feature queries that we've already fixed in GL native (see https://github.com/mapbox/mapbox-gl-native/pull/6773). I'm going to port that into GL JS.

**Comment by cammanderson** [comment]
Super cool issue comments. Thanks for that Bruno!

**Comment by mourner** [comment]
Can anyone confirm if #3459 fixes this issue?

**Comment by benjamintd** [comment]
It did for me. Thanks a lot @brunoabinader @mourner !

**Comment by brunoabinader** [comment]
Thank you all - closing for now.
