### ISSUE TITLE
Fix machine-dependent rendering abnormality when using an image layer

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#2652]
**mapbox-gl-js version**: 0.19.0 (also verified with 0.15.0, 0.16.0, 0.17.0, 0.18.0)
### Steps to Trigger Behavior
1. Goto http://codepen.io/anon/pen/pbvLXB
### Expected Behavior

That it renders normally, like this:
<img width="1339" alt="screen shot 2016-06-02 at 14 07 33" src="https://cloud.githubusercontent.com/assets/1205805/15744315/810cd3ae-28cb-11e6-9ff4-225f36341520.png">
### Actual Behavior

On a particular machine (MacBook Pro, Retina, 15-inch, Late 2013) with El Capitan it renders fine in all web browsers, however, on another machine with different hardware and GPU (MacBook Pro, Retina, 13-inch, Early 2015) with El Capitan the map blanks out with only the labels left looking like below. An interesting thing is that this happens across all browsers indicating that it is a low-level GL issue.

<img width="1277" alt="screen shot 2016-06-02 at 13 43 03" src="https://cloud.githubusercontent.com/assets/1205805/15744237/186b2896-28cb-11e6-91a9-296d50a4cae3.png">

**Comment by mourner** [comment]
Thanks for the report! So the issue is only present when you include an image layer, right?

**Comment by averas** [comment]
Correct. http://codepen.io/anon/pen/aZzxxy with the image source/layer removed renders fine on both machines.

**Comment by averas** [comment]
Another interesting detail is that https://www.mapbox.com/mapbox-gl-js/example/image-on-a-map/ renders fine on both devices... Image format? Image size (kB)? Rendered image size (w/h)?

**Comment by jfirebaugh** [comment]
@averas Is this still an issue with recent versions of Mapbox GL JS?

**Comment by averas** [comment]
@jfirebaugh Nope, works fine with latest version!
