### ISSUE TITLE
Use "WEBGL_lose_context" to destroy WebGL context in Map#remove 

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#2656]
**mapbox-gl-js version**: 0.19.0

Chrome 50

### Steps to Trigger Behavior

 1. create a map
 2. `.remove()` the map
 3. repeat

### Expected Behavior

No warnings or errors should occur.

### Actual Behavior

After a certain number of iterations (about 10 for me) there is a warning in the console `Too many active WebGL contexts. Oldest context will be lost`. This error indicates that the GL context is not being cleaned up when the map is removed.

**Comment by bhousel** [comment]
Backstory - I did some work on this back in #2019 (click through and see the "outdated diffs" for more info).

We are kind of at the mercy of the garbage collector to clean up unused webgl contexts, and that doesn't always happen immediately.

**Comment by lucaswoj** [comment]
@bhousel Do you know of anything we can do in GL JS to ameliorate the situation? If not, should we close this ticket as "not actionable"?

**Comment by tmcw** [comment]
There are [delete calls we could make](http://stackoverflow.com/questions/23598471/how-do-i-clean-up-and-unload-a-webgl-canvas-context-from-gpu-after-use) for the underlying resources, and that potentially-sketchy SO answer also claims that resizing the canvas to 1x1 will reduce the amount of memory it consumes until it's GC'ed... shots in the dark but worth a shot

**Comment by bhousel** [comment]
hmm, just realized there is a [WebGL extension to intentionally drop the context](https://www.khronos.org/registry/webgl/extensions/WEBGL_lose_context/) - that might help?

**Comment by bhousel** [comment]
There is a related thread happening now on the webgl developers list, for anyone looking for tips on how to free up webgl contexts: 

https://www.khronos.org/webgl/public-mailing-list/archives/1611/msg00013.php

**Comment by adoming3** [comment]
For anyone who comes across this... I use a work-around to show and hide the map canvas rather than redraw the map each time and that fixed my WebGL context issues. Not perfect but acceptable in my use case.

**Comment by meenu1** [comment]
Can you please share your workaround.

**Comment by kamillejohnson** [comment]
@adoming3 can you please share your workaround?
