### ISSUE TITLE
Mapbox GL: create a map without displaying it

### ISSUE THREAD

**Issue by kevinmachstudio** [mapbox/mapbox-gl-js#2663]
Is there a way of creating a map without displaying it? I couldn't find an example of that on the website. I know the example for displaying it is:

```
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/dark-v8',
    center: [-103.59179687498357, 40.66995747013945],
    zoom: 3,
});
```
However, I just want to create the map first but not actually display it until I want to use it later. When I take out the "container" field when creating the mapboxgl object, the API gives me an error since it's trying to look for the container in my html page (although it's not there since I don't want to display it yet):

`Uncaught TypeError: Cannot read property 'classList' of null`

**Comment by mourner** [comment]
Kevin, please don't use GitHub issues to ask generic web development questions. It's a place to report actual issues with the library. If you want to hide your map container, you could set it's style to `display: none` in CSS, or through many other means.

**Comment by kevinmachstudio** [comment]
@mourner Sorry, I'll ask my questions on StackOverflow then. Thanks for the suggestions.
