### ISSUE TITLE
Second time setData on GeoJSONSource doesn't re-render layer

### ISSUE THREAD

**Issue by roelvanhintum** [mapbox/mapbox-gl-js#2664]
I'm using v0.19.1, but this is also an issue on older versions.

When using `setData` on a GeoJSONSource to pass a new GeoJSON object, the re-render is never triggered. This goes for clustered sources on a symbol layer and for unclustered sources on a circle layer. Probably also for other combinations.

I'm sure the data is valid, because the first time i set the data, everything renders fine. The second time i use setData, nothing happens.

**Comment by mourner** [comment]
Can you set up a minimal JSFiddle test case reproducing the behavior?

**Comment by roelvanhintum** [comment]
I'm sorry, mapbox gl works fine in jsfiddle. This is my own mistake of not double checking the incoming data.
