### ISSUE TITLE
Recommended way to add background box around text

### ISSUE THREAD

**Issue by emakarov** [mapbox/mapbox-gl-js#2669]
Hi,
What is the recommended way to add background around the text?
On the screenshot we see a road label M-7 made by Mapbox GL, nicely looking in a box with white background and black border with rounded corner. Also we see a point on the map with text box (added by Circle and Symbol layer accordingly):
![screen shot 2016-06-05 at 2 06 02 am](https://cloud.githubusercontent.com/assets/395963/15801253/18c3cde0-2ac2-11e6-8c82-a1bc8c46a884.png)

How to make my text look like label on the road, i.e. to add background and border?

**Comment by lucaswoj** [comment]
The preferred way to add a box around a label is to use a pregenerated icon. In the Mapbox Streets style, we pregenerate an icon per potential label length, add a "len" property to the features, and then use tokens in the icon name to choose the right one `background-{len}`
