### ISSUE TITLE
Change rendered feature color or size from mbtile

### ISSUE THREAD

**Issue by stackTom** [mapbox/mapbox-gl-js#2675]
How does one change the color of a feature from an mbtile? My application relies on served mbtiles, and I know one can query the rendered features on the map, but how does one change the color or size of these rendered features? I change the color property (they are circles), and nothing changes. If this isn't possible, will this ability be added sometime in the future?

**Comment by jfirebaugh** [comment]
See [this example](https://www.mapbox.com/mapbox-gl-js/example/color-switcher/).

**Comment by stackTom** [comment]
That example switches the color of the whole layer, but is there a way to change the color of an individual feature. For example, changing the circle color or circle radius of a circle feature, similar to how individual GeoJSON features can be altered?

**Comment by mourner** [comment]
@stackTom like this? https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/

**Comment by stackTom** [comment]
Actually, I already use data driven styles in my project. The thing is, I was wondering if, after loading the layer and using data driven styles, one could change the features of a property and re render. In reality, I would like to be able to change a property in my features on the fly and then use data driven styles based on this new property. But, if I could change the color of a select number of features obtained through query rendered features on click, that would help, too.

**Comment by csimpi** [comment]
This shouldn't be closed... Nobody solved the exact problem or answered the question.

**Comment by asheemmamoowala** [comment]
@csimpi If the existing solutions don't work for you, you can try the `Map.setFeatureState` API in the next release. Here's an example: https://github.com/mapbox/mapbox-gl-js/blob/master/docs/pages/example/hover-styles.html

**Comment by asheemmamoowala** [comment]
@csimpi You can use if from the `master` branch if you want to roll your own build of mapbox-gl-js. If not, the next release of gl-js will be in the next 4-6 weeks.
