### ISSUE TITLE
Fix bug causing geometry outside tile (in buffer) to be drawn on large maps

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#2676]
**mapbox-gl-js version**: 0.26.0
### Steps to Trigger Behavior
1. Create a large 4096x4096px map.

Demo: http://jsbin.com/foqawokoqe/edit?html,output
### Expected Behavior

Shouldn't see these tile boundary lines.
### Actual Behavior

I'm seeing tile borders on both GeoJSON and `mapbox://styles/mapbox/streets-v8'`.

![selection_307](https://cloud.githubusercontent.com/assets/117278/15812468/cfa8ae18-2bf8-11e6-90b0-e98a1e61885f.png)

I've tried a bunch of different values for buffer (starting with the minimum 0, 1, 16, 128, ending with the maximum 512 and not setting it) all it does is move where the lines appear.

**Comment by dpieri** [comment]
FWIW I've noticed the same artifact on Mapbox GL Native (Android)

![pasted image at 2016_05_10 10_37 pm](https://cloud.githubusercontent.com/assets/539310/15868905/a3d22d4a-2c9e-11e6-85f8-a1f098e15932.png)
