### ISSUE TITLE
Fix exception thrown by "drag rotate" handler

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2680]
per https://github.com/mapbox/mapbox-gl-js/commit/4dd6786282e7d3e9e7b2a7fd866c3637d9e88737#commitcomment-17747349

**Comment by scothis** [comment]
Still seeing this error with 0.20.0

```
TypeError: undefined is not an object (evaluating 'this.options.bearingSnap')
  at snapToNorth(node_modules/mapbox-gl/js/ui/camera.js:241:55)
  at this(node_modules/mapbox-gl/js/ui/handler/touch_zoom_rotate.js:170:16)
```

**Comment by lucaswoj** [comment]
problematic line of code: https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/camera.js#L241
