### ISSUE TITLE
Mock module dependencies in unit tests

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#2685]
In the unit tests, I've encountered [one place](https://github.com/mapbox/mapbox-gl-js/blob/198fb97a4971052308bc90d8217f0a087e1be5f6/test/js/ui/map.test.js#L939-L941)--and I suspect there are more--where the only feasible way to do the test is to assert something about some private `_`-prefixed state variable.

In the example linked above, this could be avoided by mocking `map.js`'s reference to `Style` and then checking that the correct parameter is passed.  This would make the test less brittle and also make it a much more direct test of the behavior it's supposed to be validating.

Something like [proxyquire](https://www.npmjs.com/package/proxyquire) or [rewire](https://www.npmjs.com/package/rewire) ought to make this doable.

**Comment by lucaswoj** [comment]
I am open to giving this a try. We have some tests that are unnecessarily awkward due to the inability to mock out an entire module.

Thoughts @tmcw @jfirebaugh @mourner?

**Comment by jfirebaugh** [comment]
Are we talking about mocking `require`, as @anandthakker initially framed it, or using dependency injection, as @lucaswoj retitled the issue? To me, dependency injection would mean not using `require('style')` in map.js, and instead passing a `Style` object (or mock) to the constructor and `setStyle`. I don't think we should do that. But trying out proxyquire or rewire sounds good.

**Comment by anandthakker** [comment]
> dependency injection would mean not using require('style') in map.js, and instead passing a Style object (or mock) to the constructor and setStyle. I don't think we should do that.

👍 traditional DI would introduce significant architectural overhead of (in my opinion) dubious value

**Comment by lucaswoj** [comment]
Ah! I misunderstood the concept of dependency injection. Re-un-titling.

**Comment by lucaswoj** [comment]
this was done in https://github.com/mapbox/mapbox-gl-js/pull/2667
