### ISSUE TITLE
Improve error message when setting a "source-layer" on a layer that uses a GeoJSON source

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-gl-js#2691]
### Steps to Trigger Behavior
1. Add a layer that references a GeoJSON source with a `source-layer`
2. You'll hit this [assertion failure](https://gist.github.com/amyleew/abe91f57e25690e7b1a359f3673ce4e0)

![image](https://cloud.githubusercontent.com/assets/4587826/15877611/e6608f0a-2ce2-11e6-8d79-95fc9f6856d6.png)

The expected behavior is that either  `source-layer` is ignored, or you get a validation error with a comprehensible message.

/cc @jfirebaugh

**Comment by mollymerp** [comment]
agreed that we should handle errors like this with clearer messages 👍  I can't take this on now but I would be happy to after cross-source symbol placement is merged.

**Comment by mollymerp** [comment]
Looks like we no longer fire an `AssertionError` or crash, but we do still need to improve the behavior when this happens! Moving discussion to #3784 to discuss and define the behavior and display a better message

**Comment by lucaswoj** [comment]
@mollymerp Did you intend to link to a different issue? #3784 is closed.

**Comment by jfirebaugh** [comment]
@lucaswoj It was just fixed -- see #3896.
