### ISSUE TITLE
Amend the geocoder example to draw a marker at the result's location

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-gl-js#2692]
The GL implementation of [geolocate](https://www.mapbox.com/mapbox-gl-js/api/#Geolocate) does not visually show a position marker after successful geolocation, this makes it hard to identify where the user is located. 

This is very handy for tools that is based on user position. [Here is an example map](http://ocsidlab.github.io/treemap/#2.18/43.71/-42.80) to try the existing Geolocate() behavior for which i'd like to add a position marker. This app is being used to map trees locations.

cc @bhousel

**Comment by bhousel** [comment]
We dispatch a [geolocate event](https://www.mapbox.com/mapbox-gl-js/api/#Control.event:geolocate) on success, so the listening code can display a marker if they want to.  Is this ok?  It gives developers a bit more flexibility rather than just forcing a marker on them.

**Comment by lucaswoj** [comment]
I agree with @bhousel. This behaviour isn't want an end user would want in all cases and should be implemented downstream. (This'll get a even easier when we land @mourner plugin for #656 soon!)

What we can do is amend the [geocoder example](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/) to include a marker.

**Comment by danielduhh** [comment]
How can I listen for an event after geolocate is triggered?
`map.on('geolocate') does not work...`

**Comment by lucaswoj** [comment]
@danielduhh `map.on('geolocate')` is the correct way to listen for events from the geolocator control. In the future, please direct all questions except bug reports and feature requests to [StackOverflow](http://stackoverflow.com/questions/tagged/mapbox-gl-js).

**Comment by danielduhh** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/2824

**Comment by lucaswoj** [comment]
Oh! Hm. this already existed. http://127.0.0.1:4000/mapbox-gl-js/example/point-from-geocoder-result/

**Comment by mprove** [comment]
URL update for the example: https://www.mapbox.com/mapbox-gl-js/example/point-from-geocoder-result/

**Comment by dieterdreist** [comment]
the examples are for geocoding (get a position for an address), the issue is about geolocation (get the user's position)
