### ISSUE TITLE
Render self-intersecting polygons using nonzero-rule

### ISSUE THREAD

**Issue by mcwhittemore** [mapbox/mapbox-gl-js#2696]
**mapbox-gl-js version**: 0.19.1
### Steps to Trigger Behavior
1. Add a polygon to a GeoJSON source that is self intersecting
### Expected Behavior

![2ec7e4e6-280b-11e6-9b63-a32d817e66e9](https://cloud.githubusercontent.com/assets/1551510/15907122/d178a72e-2d89-11e6-9b5c-dd96701fb976.png)
### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/1551510/15907008/4d7520ba-2d89-11e6-9f3b-58505f583796.png)
### Notes

GeoJSON doesn't guarantee that Polygons aren't self intersecting.

> A LinearRing is closed LineString with 4 or more positions. The first and last positions are equivalent (they represent equivalent points).
> 
> For type "Polygon", the "coordinates" member must be an array of LinearRing coordinate arrays. For Polygons with multiple rings, the first must be the exterior ring and any others must be interior rings or holes.

/cc @tmcw @samanpwbb 

ref https://github.com/mapbox/mapbox-gl-draw/issues/319

**Comment by mourner** [comment]
This is currently not possible after the Earcut merge. We need a polygon cleaning library similar to how Clipper is used in Tippecanoe and Mapnik Vector Tile, but fast enough for JS use, and it's a big challenge to overcome.

**Comment by lucaswoj** [comment]
This issue suggests that we should use the [nonzero-rule](https://en.wikipedia.org/wiki/Nonzero-rule) to render polygons. Other potential design solutions are to leave this behaviour undefined or use the [even-odd rule](https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule)

**Comment by jfirebaugh** [comment]
Closing; the technical difficulties here make it unlikely that we'll fix this issue anytime soon.
