### ISSUE TITLE
"base" does not work as expected for exponential functions.

### ISSUE THREAD

**Issue by nrathi** [mapbox/mapbox-gl-js#2698]
**mapbox-gl-js version**: 0.19.1

First of all, thank you for adding data driven styling support!! I am so excited to start using it.

I am trying to convert my existing code (four layers of different colors, each filtered on either end in sqrt-space) to use a function (one layer with two stops in sqrt-space).

Here's what I have:
```
const layer = {
  id: layerId,
  source: sourceId,
  type: 'fill',
  paint: {
    'fill-opacity': 0.5,
    [colorProperty]: {
      property: propertyName,
      stops: [
        [0, '#FFF'],
        [maxValue, maxColor]
      ],
      base: 0.5,
    }
  },
 });
```
For some reason, "base: 0.5" does not work as expected. "base: 1" looks correct, but "base: 0.5" accentuates both ends of the spectrum. I re-created the GeoJson in sqrt-space and used "base: 1" and it looked correct.

Thanks!

**Comment by lucaswoj** [comment]
Thanks for looking into this @nrathi. I did some more digging and found that the `exponential` function actually uses cubic interpolation. You can see the implementation [here](https://github.com/mapbox/mapbox-gl-js/blob/a34479710bdaf6e8a3bf708d26f89f613da8c74c/js/util/util.js#L15-L21). We should definitely be more clear about how this works!

**Comment by lucaswoj** [comment]
[Here is the implementation of our exponential functions](https://github.com/mapbox/mapbox-gl-function/blob/master/index.js#L130-142). How would you expect this to be implemented?

**Comment by danvk** [comment]
We expected this bit:

```javascript
var ratio;
if (base === 1) {
    ratio = progress / difference;
} else {
    ratio = (Math.pow(base, progress) - 1) / (Math.pow(base, difference) - 1);
}
```

to just be this:

```javascript
var ratio = Math.pow(progress / difference, exponent);
```

That way linear (`exponent=1`) doesn't need to be special-cased and you include [sqrt-scales][2] and [power scales][1] naturally. You wouldn't get log scales, though.

[1]: https://github.com/d3/d3/wiki/Quantitative-Scales#pow
[2]: https://github.com/d3/d3/wiki/Quantitative-Scales#sqrt

**Comment by lucaswoj** [comment]
The cost of changing how exponential functions work outweighs the potential benefits of making them more intuitive 😞
