### ISSUE TITLE
Fix error handling in "GlyphSource#getSimpleGlyphs"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2711]
This issue comes from a [`// TODO` comment in `glyph_source.js`](https://github.com/mapbox/mapbox-gl-js/commit/d6877af8cb462b52baa0e4ff2ecbaa6dd8592964#diff-6632eb587812a66dac71654cb214cb6dR56)

```
// TODO not be silent about errors
```

cc @ansis

**Comment by jfirebaugh** [comment]
The `ajax.getArrayBuffer` call in GlyphSource is also ignoring errors.
