### ISSUE TITLE
Fix missing line segments when line-join = miter

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-gl-js#2726]
**mapbox-gl-js version**:  v0.19.1 + whatever is in Mapbox Studio `bundle.js?v2016-06-10-22-20-23`
### Steps to Trigger Behavior
1. Add a line layer with a simple line style (eg road from Mapbox Streets)
2. Compare miter / round / bevel line-join styles without changing any other aspect of the style.
### Expected Behavior

All lines should appear with the respective line-style.
### Actual Behavior

Some straight line segments will be missing when line-join is set to miter.

![studio-linejoin](https://cloud.githubusercontent.com/assets/126952/16022222/c9a246aa-3184-11e6-86ee-9f073f3bf884.gif)
- [line-join: round](https://api.mapbox.com/styles/v1/aj/cipegoelp001ob3ni4wtcuqll.html?title=true&access_token=pk.eyJ1IjoiYWoiLCJhIjoiY2lrZW4zZnE1MDA2NHRvbHl3Y2psejM1dSJ9.L2ShDU7WcmDhj5tZdBLD5w#10.75/39.7446/-104.9585)
- [line-join: miter](https://api.mapbox.com/styles/v1/aj/cipehq86n001pbunqfo8mufzl.html?title=true&access_token=pk.eyJ1IjoiYWoiLCJhIjoiY2lrZW4zZnE1MDA2NHRvbHl3Y2psejM1dSJ9.L2ShDU7WcmDhj5tZdBLD5w#10.75/39.7446/-104.9585)

**Comment by lucaswoj** [comment]
💭 Maybe related to #2627

**Comment by mourner** [comment]
I can no longer reproduce this, so closing.
