### ISSUE TITLE
Enable property functions for line paint properties

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2729]
## Properties
- `line-opacity`
- `line-color`
- `line-width`
- `line-gap-width`
- `line-offset`
- `line-blur`
- `line-dasharray`

**Comment by sguignot** [comment]
Below you will find a simple use case, using line-color as a feature property reference, the same way text-field does (using `resolveTokens` function): `'line-color': '{colour}'`

```
export const addTransitLayerToMap = (map) => {
  const source = {
    type: 'vector',
    tiles: ["https://vector.mapzen.com/osm/transit/{z}/{x}/{y}.mvt?api_key=API_KEY"]
  };
  map.addSource(transitSourceId, source);

  const localTransitFilter = ['in', 'kind', 'subway', 'tram', 'railway'];
  map.addLayer({
    id: transitLayerId,
    source: transitSourceId,
    'source-layer': 'transit',
    type: 'line',
    paint: {
      'line-color': '{colour}',
      'line-width': {
        base: 1,
        stops: [[10, 1], [13, 2], [16, 4]]
      },
      'line-gap-width': 0,
    },
    filter: localTransitFilter,
  });
};
```

@lucaswoj  please let me know if this is on your roadmap, if not I could work on it I guess :)

**Comment by lucaswoj** [comment]
@sguignot We do not plan to support that syntax for property functions. We prefer using a syntax based on Javascript objects to a syntax based on a custom minilanguage.

**Comment by sguignot** [comment]
@lucaswoj ok, it makes sense! I will use it as soon as it is released :)
