### ISSUE TITLE
Refactor to create StyleProperty class

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2739]
There are many methods within `StyleLayer` that only operate on a single style property.
- `setLayoutProperty`
- `getLayoutProperty`
- `getLayoutValue`
- `setPaintProperty`
- `getPaintProperty`
- `getPaintValue`
- `getPaintValueStopZoomLevels`
- `getPaintInterpolationT`
- `isPaintValueFeatureConstant`
- `isLayoutValueFeatureConstant`
- `isPaintValueZoomConstant`
- ... 

A cleaner design would be to have a `StyleProperty` object per property with all of these methods

``` js
type StyleValue<T> {
  isZoomConstant: boolean;
  isFeatureConstant: boolean;
  calculate(zoom:number, featureProperties: {}) => T;
  getInterpolationT(zoom: number) =>;
  ...
}
```

At the same time we might make `StyleTransition` conform to the same interface as `StyleProperty`

ref https://github.com/mapbox/mapbox-gl-js/pull/2629#discussion_r64939804

**Comment by jfirebaugh** [comment]
👍  -- what gl-native does might serve as a model here:

* [`PaintProperty`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/paint_property.hpp)
* [`LayoutProperty`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/style/layout_property.hpp)
* [`PropertyValue`](https://github.com/mapbox/mapbox-gl-native/blob/master/include/mbgl/style/property_value.hpp)
