### ISSUE TITLE
This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.

### ISSUE THREAD

**Issue by infacq** [mapbox/mapbox-gl-js#2742]
I added this to webpack.config.js

```js
resolve: {
        root: path.join(__dirname, '..', 'app'),
        alias: {
            'react': path.join(__dirname, 'node_modules', 'react'),
            'mapbox-gl': path.resolve('./node_modules/mapbox-gl/js/mapbox-gl.js'),
            'webworkify': 'webworkify-webpack'
        },
        extensions: ['', '.js', '.jsx', '.json', '.css', '.styl', '.png', '.jpg', '.jpeg', '.gif']
    },
```

I f I don't put that, the map won't come out. And when I put it up, I hit the abovemention warning. Please advise

**Comment by lucaswoj** [comment]
Hello @infacq! Thanks for writing in! Have you followed all the steps in our webpack setup instructions? https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-webpack

@tmcw do you have any insight here?

**Comment by infacq** [comment]
yes. everything is installed and the only hack I did is 

`'mapbox-gl': path.resolve('./node_modules/mapbox-gl/dist/mapbox-gl.js'),`

because I was following this post to get [fix of mapboxGL](https://mikewilliamson.wordpress.com/2016/02/24/using-mapbox-gl-and-webpack-together/)

**Comment by jfirebaugh** [comment]
That blog post is outdated; please try the webpack config @lucaswoj linked above.

**Comment by infacq** [comment]
that's true @jfirebaugh. Now I just follow the recommended way by official mapbox README. But still hit this warning

**Comment by chafnan** [comment]
I'm having this same issue, and the package is being required as the webpack setup is directing from the link above.  Is there any other suggestions on how to remove this warning?

**Comment by bendersej** [comment]
Add the following to your webpack config to get rig of the warning:

```
...
module: {
    noParse: /node_modules\/mapbox-gl\/dist\/mapbox-gl.js/,
    loaders: [{
    ...
    }]
}
...
```
