### ISSUE TITLE
Revise "Writing API Documentation" guidelines to use "@classdesc"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2748]
blocked on https://github.com/documentationjs/documentation/issues/109

see https://github.com/mapbox/mapbox-gl-js/pull/2744#issuecomment-226283142

cc @davidtheclark @jfirebaugh @tmcw

**Comment by jfirebaugh** [comment]
We've moved to ES6 classes, so `@classdesc` isn't necessary.
