### ISSUE TITLE
Revise existing documentation for compliance with "Writing API Documentation" guidelines

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2749]
With the awesome new documentation guidelines defined in https://github.com/mapbox/mapbox-gl-js/pull/2744, it is time we did a spring cleaning of our existing documentation to bring it up to our own standards. 😄 

cc @davidtheclark @tmcw @lyzidiamond

**Comment by lyzidiamond** [comment]
Looks like this was done in #2815! Close here?

**Comment by lucaswoj** [comment]
Yes! Thanks for the 🎏  @lyzidiamond.
