### ISSUE TITLE
Running mapbox-gl-js without a WebGL context

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#2750]
Browser test environments [often do not support WebGL](https://saucelabs.ideas.aha.io/ideas/SLIDEA-I-54). So far, we've made due with trying to mock the mapbox-gl-js APIs to blackhole methods, however, our needs are growing more advanced and we want to interact with gl-js as if it were a real live instance emitting real events and supporting real user interactions.

Because the runtime doesn't support WebGL, we'd like to have a mode in gl-js where everything is real except for the WebGL context.

Initial thinking is to introduce a `MOCK_GL` config property that is `false` by default. When set to `true`, the `getWebGLContext` and `supportsWebGLContext`methods in `./util/browser/canvas` are mocked for new Canvas instances. We'll need to find a good way to mock a GL context in the browser.

**Comment by jfirebaugh** [comment]
Can you explain the motivation here? It's difficult to see why running mapbox-gl-js without WebGL would be useful.

**Comment by lucaswoj** [comment]
Mocking dependencies is a common pattern in unit testing. Let's explore some non-invasive mocking techniques before adding functionality to GL JS core. 

In particular, https://github.com/thlorenz/proxyquire plus https://github.com/thlorenz/proxyquireify might be useful. @anandthakker is currently working on a PR which adds proxyquire to our testing system #2685 

I would be happy to make small changes to GL JS to make WebGL easier to mock out with `proxyquire`.

**Comment by scothis** [comment]
The primary use case I have is the Studio integration test suite which uses real web browsers and selenium. Hosted selenium environments typically do not support WebGL, and there have been numerous issues reported against those that do try to support WebGL.

To date, we have mocked gl-js at a high level by intercepting calls to `new Map()`. This worked as Studio was pushing data to gl-js and not as concerned about receiving data back from gl-js. This means we are not using automated tests for behavior like map movement, but instead rely on manual testing.

This pattern became problematic for us with the introduction of gl-draw. To properly integration a gl-js map with gl-draw installed we need the ability to both send data into the map and receive data from the map. Rather than attempt to mock the gl-js and gl-draw apis, we'd rather mock the limitation (WebGL).

**Comment by allthesignals** [comment]
@scothis do you have advice on patterns for testing projects that use mapbox-gl/mapbox-gl-draw? I sometimes go down the path of simulating mouse clicks with the private `fire` method, but that API is unstable. I'm curious if there's a way to simply trigger callback events that were passed _into_ mapbox-gl/mapbox-gl-draw - maybe I could do that by changing my source code to be more modular... but I'm curious to see what others have done before going down another rabbit hole.
