### ISSUE TITLE
Create an automated tool to keep our documentation in compliance with "Writing API Documentation" guidelines

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2751]
Could we enforce any of these with a linter? Should we plan a monthly readthrough of any new docs? 

ref https://github.com/mapbox/mapbox-gl-js/pull/2744

**Comment by davidtheclark** [comment]
Is there any built-in way with documentation.js to hook in and run a function on the generated AST? If not, we could either look into adding something like that, or use the Node API instead of the CLI. If we had access to the AST of JSDoc comments I imagine there's a lot we could enforce.

**Comment by lucaswoj** [comment]
Perhaps a good start would be to run [retext](https://www.mapbox.com/blog/retext-mapbox-standard/) on our doc comments. This may help avoid issues like https://github.com/mapbox/mapbox-gl-js/pull/2880.

**Comment by mourner** [comment]
Closing as stale — seems there's not enough interest in pursuing this at the moment. cc @colleenmcginnis
