### ISSUE TITLE
Fix double drawing on fill outlines

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2757]
If you draw a semi-transparent fill layer, the outline is drawn twice, resulting in a outline that is twice the desired opacity and a mix of the fill color and the outline color. 

See the demo at http://jsbin.com/peraxujibo/6/edit?html,output

I'm not yet sure if this behaviour is new or intentional. 

cc @samanpwbb

**Comment by samanpwbb** [comment]
Version 19 and version 18 handle transparency really differently:

Started in version 19.0 – http://codepen.io/samanbb/pen/aZmRdx
Version 18.0 – http://codepen.io/samanbb/pen/vKXVGL

**Comment by samanpwbb** [comment]
There was some discussion about how to "correctly" handle opacity in the style spec a while ago: https://github.com/mapbox/mapbox-gl-style-spec/issues/273

I proposed: 

> What if setting RGBA fill/stroke was per-feature while setting Opacity was per layer?

Seems like the recent change was accidental. Ideally we have _both_ per-feature and per-layer opacity, and the way this works is clearly defined in the style spec.

Short term, I would love to see the recent change to opacity-* rules reverted so styles designed before v19 look the way the designer wanted them to look.

**Comment by lucaswoj** [comment]
Thanks for the clarification @samanpwbb. I misunderstood the bug before.

This change in behaviour is due to us merging earcut #1606. 

> Ideally we have both per-feature and per-layer opacity, and the way this works is clearly defined in the style spec.

As of GL JS v0.19.0 every style property is defined per-feature. Pre-earcut fill style properties were the only exception to this rule. As far as I know, all style properties in GL Native have always been per-feature. (Can you confirm, @jfirebaugh?).

It is possible that GL Native has always been rendering translucent polygons like this and only now is GL JS rendering them consistently.

I will open a ticket about supporting per-feature and per-layer style properties in mapbox-gl-style-spec. 

> Short term, I would love to see the recent change to opacity-* rules reverted so styles designed before v19 look the way the designer wanted them to look.

We can revert the behaviour if

 - the new GL JS behavior is inconsistent with GL Native behaviour
 - the GL and carto teams agree that the new GL JS behaviour is undesirable
 - there exists a performant way to restore pre-earcut behaviour with earcut

# Next Steps

 - [ ] open a mapbox-gl-test-suite ticket to test overlapping translucent polygons 
 - [ ] decide whether or not we need to revert the new behaviour (then do so)
 - [ ] create a ticket in mapbox-gl-style-spec to discuss what per-feature / per-layer style properties would look like
 - [ ] update Mapbox styles and do a new release to mitigate the rendering change

**Comment by lucaswoj** [comment]
![img_1509](https://cloud.githubusercontent.com/assets/281306/16399053/114716fc-3c84-11e6-9047-be14bf738ac9.PNG)

![screen shot 2016-06-27 at 4 28 21 pm](https://cloud.githubusercontent.com/assets/281306/16399071/2e9427ea-3c84-11e6-97ad-a1c4773d9f78.png)

I have confirmed that GL Native renders polygon opacity per-feature, like GL JS as of v0.19.0.

This leads me to believe we should keep the existing per-feature opacity rendering and adjust our default styles to work on that assumption.

**Comment by samanpwbb** [comment]
one issue:

if fill is semitransparent, it is now impossible to use antialiasing without a noticeable stroke. Do you see any way around that?

There will continue toge many cases where per-layer rather than per-feature styling is desirable, will wait for that discussion in the style spec repo though.

**Comment by jfirebaugh** [comment]
Original issue discussing rendering behavior for overlapping semi-transparent fills is #859. As noted there, the behavior prior to earcut was considered a bug.

@samanpwbb, can you provide a minimized test case for the issue with antialiasing?

**Comment by lucaswoj** [comment]
All of the "Next Steps" outlined in this ticket have been 🚢ed!
