### ISSUE TITLE
Increase max sprite size to 1024

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-js#2761]
Mapbox GL Native [supports sprites up to 1024 x 1024](https://github.com/mapbox/mapbox-gl-native/pull/3703). Mapbox GL JS should match to ensure sprites created for mobile don't break on the web. 

cc @1ec5

**Comment by lucaswoj** [comment]
My understanding, per #141, is that GL JS could support a sprite atlas of 1024px square. I can't seem to find a reason why we are using a 512px square sprite atlas instead. 

Thoughts @bhousel @jfirebaugh @kkaefer?

**Comment by kkaefer** [comment]
We can use 1024x1024 atlases, but we should also implement https://github.com/mapbox/mapbox-gl-js/issues/141#issuecomment-98345854

**Comment by spavett** [comment]
Question maybe related to this: I'm trying to add some SVG icons to a layer in the streets base map in Studio. These icons are pretty large and meant to overlap - one is 400 x 400 (as an SVG). The next one is 120 x 120. This additional icon doesn't seem to work in conjunction with the first. I can get them to work individually but not together. You can see the size of the icons on the example screen grab. Is this to do with this glyph size? I see a "SpriteAtlas out of space" warning in my js console in the browser.

![streets___mapbox](https://cloud.githubusercontent.com/assets/872808/16194692/c6096b36-36ed-11e6-9f29-3d849a62263c.png)

**Comment by lucaswoj** [comment]
@spavett Yes, it sounds like your sprites are too large for GL JS as it is currently implemented. In the future, we would prefer if you used GitHub only for feature requests and bug reports, directing all other questions to [StackOverflow](http://stackoverflow.com/questions/tagged/mapbox-gl-js).
