### ISSUE TITLE
Add WMS example

### ISSUE THREAD

**Issue by mtirwin** [mapbox/mapbox-gl-js#2775]
@bhousel love the [new WMS support](https://github.com/mapbox/mapbox-gl-js/pull/2612) and excited to [see the docs roll](https://github.com/mapbox/mapbox-gl-style-spec/pull/464). 

Can you add an example to https://www.mapbox.com/mapbox-gl-js/examples/, maybe porting over https://www.mapbox.com/mapbox.js/example/v1.0.0/wms/?

cc/ @tmcw @lyzidiamond

**Comment by bhousel** [comment]
SGTM 👍
