### ISSUE TITLE
Fix race condition when calling "GeoJSONSource#setData" in rapid succession 

### ISSUE THREAD

**Issue by marcoqu** [mapbox/mapbox-gl-js#2776]
**mapbox-gl-js version**: v0.20.1
**browser**:  Chrome 51.0.2704.103 m (64-bit) on Windows 10
### Steps to Trigger Behavior
1. Create empty GeoJSONSource
2. Apply Circle Layer Style to the source
3. Update source with large GeoJson data
4. Reupdate source shortly after with small GeoJson data
### Expected Behavior

See the small GeoJson data on the map
### Actual Behavior

Some zoom levels have display the big dataset, some display the small dataset.
Sometimes even at the same zoom level, some tiles display one dataset, and some the other.
### Minimal demo

http://jsfiddle.net/scrbqjck/3/
Demo first updates the source with a 20000 points dataset, and later with  50 points dataset.
Zoom in and out to see the mixed tiles layers

I hope I'm not doing something terribly wrong :smile: and I guess this depends on the async nature of setData, but I would expect setData to abort any previous operation when it gets called again.

**Comment by lucaswoj** [comment]
related to https://github.com/mapbox/mapbox-gl-js/issues/2275

**Comment by lucaswoj** [comment]
Provided test case fixed as of 8f3ae8273
