### ISSUE TITLE
Error rendering a `GeometryCollection` geometry object 

### ISSUE THREAD

**Issue by chriddyp** [mapbox/mapbox-gl-js#2778]
**mapbox-gl-js version**: 0.20.1

### Example
http://codepen.io/etpinard/pen/vKyrMg

### Steps to Trigger Behavior

Add a GeoJSON source with a `geometry` object of type `GeometryCollection` and a `fill` layer.

### Expected Behavior
A filled region to be drawn.

### Actual Behavior
Nothing is drawn. Console warning `TypeError: Cannot read property 'type' of undefined` while parsing the GeoJSON.

### Notes
- I'm working off of the [GeoJSON spec here](http://geojson.org/geojson-spec.html#geometry-collection). 
- If I unnest the `geometry` object out of the `features`, a region is drawn. Example: http://codepen.io/chriddyp/pen/aZBKez?editors=0010

**Comment by jfirebaugh** [comment]
That GeoJSON is invalid; it's not legal for a FeatureCollection to contain a GeometryCollection. Each member of a FeatureCollection must be a Feature.

You can use https://github.com/mapbox/geojsonhint to catch these sorts of errors.

**Comment by dagjomar** [comment]
Just in case somebody else stumbles upon this issue in the future, as I did....

Here is a valid example with GeometryCollection:
http://codepen.io/anon/pen/xdWdym

**Comment by 3zzy** [comment]
@jfirebaugh Are you sure GeometryCollection in a FeatureCollection is not legal? I tested on http://geojsonlint.com/ and it rendered the layer just fine, no errors or warnings.
