### ISSUE TITLE
Mapbox crashing when loading large amounts of GeoJSON data

### ISSUE THREAD

**Issue by thompsonT** [mapbox/mapbox-gl-js#2779]
I am currently using mapbox on a project that is uploading large amounts of GeoJSON(Sometimes well over 100,000 points) of data on the map and on touch devices(iPad latest gen using mobile Safari or Chrome), and sometimes on a desktop browser using a powerful setup, I am seeing the map crash when users zoom in and out in a semi-aggressive fashion on the map.

I do see one warning in the console that states: 
"Geometry exceeds allowed extent, reduce your vector tile buffer size" 

However, I tried running a default setup of just using the map while uploading a large amount of GeoJSON and did not see the this warning, yet the map still crashed on a test iPad. 

**mapbox-gl-js version**: v0.20.1

### Steps to Trigger Behavior

 1.Wait for the map the load in and place over 100,000 GeoJSON points on the map
 2.Zoom in and out with the map in a semi-aggressive manner on a touch device(iPad for us)  or desktop 

### Expected Behavior
Map does not crash and restart the browser
### Actual Behavior
Map crashes and the browser restarts

**Comment by stackTom** [comment]
I had a similar issue. Do you have a lot of properties in the GeoJSON? Stripping out the properties can help. If your data is relatively densely populated, have you tried using mapbox vector tiles and tippecanoe, along with a vector tile server (or uploading the json to mapbox and letting it serve your tiles)? That was the solution I ended up using.

**Comment by Pipoupi** [comment]
You could try to pass on v0.15.0. See my issue #2443 I'm loading 150 000 points. I know it's not the best solution but performance are way better

**Comment by jfirebaugh** [comment]
Make sure you are using [`setData` with a URL](https://www.mapbox.com/mapbox-gl-js/api/#GeoJSONSource#setData), rather than passing a literal object.

**Comment by lucaswoj** [comment]
It sounds to me like the map is crashing because you are running out of memory. This is not a bug in GL JS, this is a bug in your application.

**Comment by vero4karu** [comment]
Hi! I'm having the same problem, but only with 685 polygons:
mapbox-gl-js: **v0.39.1**

```html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title></title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>

<div id='map'></div>
<script>
mapboxgl.accessToken = 'mapbox-token';
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [-74.07231699675322, 4.66336863727521],
    zoom: 12
});

map.on('load', function () {
    map.addSource('fulfillment', {
      'type': 'geojson',
      'data': 'https://gist.githubusercontent.com/vero4karu/b5019c0117876711b6570f188ee9fae8/raw/54c9612d325eaca7e79fda74c405eb019ffdabf4/fulfillment.geojson'
    });

    map.addLayer({
      "id": "fulfillment-polygon",
      "type": "fill",
      "source": "fulfillment",
      "paint": {
        "fill-color": {
          property: 'color',
          type: 'identity'
        },
        "fill-opacity": 0.5
      }
    });
});
</script>

</body>
</html>
```

![selection_999 055](https://user-images.githubusercontent.com/2270752/29428980-b11cf0e4-8354-11e7-97b1-43994095b8a0.png)
