### ISSUE TITLE
`drawCollisionDebug` is called when `showCollisionBoxes` is false

### ISSUE THREAD

**Issue by c0** [mapbox/mapbox-gl-js#2781]
When `map.showCollisionBoxes` is false, I noticed in the profiler that [`drawCollisionDebug`](https://github.com/mapbox/mapbox-gl-js/blob/master/js/render/draw_symbol.js#L61) is still called.

This only seems to take up CPU cycles. Can it be prevented from running when `showCollisionBoxes` is false?

**Comment by alinapaz** [comment]
@c0 thanks for opening this issue. @jfirebaugh or @mourner what would you recommend?

@c0 please also open any more specific details to your project in our private collab-repo. (https://github.com/mapbox/rentpath-collab)

**Comment by alinapaz** [comment]
@c0 Fix for that issue has landed and will go out with the next release ^^

**Comment by c0** [comment]
Thank you!
