### ISSUE TITLE
Make tapping with two-fingers zoom out on iOS

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#2785]
In WebKit on iOS, tapping once with two fingers should ideally zoom out by a factor of 0.5, for consistency with the Mapbox iOS SDK. Is there an API to accomplish that?

(v0.19.1 in Safari on iOS 9.3.)

/ref #2784
/cc @lucaswoj

**Comment by lucaswoj** [comment]
@1ec5 There is no API to control this behaviour at the moment. I will put together a PR to add it.

**Comment by asheemmamoowala** [comment]
Closed by https://github.com/mapbox/mapbox-gl-js/pull/9365
