### ISSUE TITLE
Getting mapbox-gl-js works with  Qt Canvas3D

### ISSUE THREAD

**Issue by lygstate** [mapbox/mapbox-gl-js#2786]
Cause Canvas3D support for WebGL, we could take that advantage.

**Comment by jfirebaugh** [comment]
mapbox-gl-js is built on standard, non-proprietary web technologies. We don't have any plans to change that. You might be interested in taking a look at [the Mapbox Qt SDK](https://github.com/mapbox/mapbox-gl-native/tree/master/platform/qt).
