### ISSUE TITLE
Adding and then removing a layer as part of the same update gives a 'Cannot read property 'updatePaintTransitions' of undefined(…)' error

### ISSUE THREAD

**Issue by Que3216** [mapbox/mapbox-gl-js#2787]
MapBox GL v0.19.0:

### Steps to Trigger Behavior

 1. Add and remove a layer as part of the same update

Demonstration: https://jsfiddle.net/e41m9uup/2/ (open the javascript console to view the error)

### Expected Behavior

Render the map as normal

### Actual Behavior

Throws a 'Cannot read property 'updatePaintTransitions' of undefined(…)' error.

My debugging so far:
   - In addLayer MapBox adds the layer to this._updates.paintProps (by calling updateClasses)
   - In removeLayer MapBox doesn't remove the layer from this._updates.paintProps (that only happens at the end of the update method)
   - _applyClasses happens before the end of the update method (before _updates.paintProps gets cleared), and expects every layer in this._updates.paintProps to be in this._layers, but the removed layers are no longer in this._updates.paintProps. So it throws a 'cannot read property of undefined'.

**Comment by jfirebaugh** [comment]
Confirmed that this still happens with v0.20.1.
