### ISSUE TITLE
Document, test, and port (or deprecate) per-layer and per-property transitions

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2788]
GL JS supports per-property transitions (i.e. `circle-color-transition`) and per-layer transitions. These features are not documented, tested, or ported to GL Native. We should either

 - document, test, and port this feature
 - deprecate this feature

cc @mapbox/gl @geohacker

**Comment by jfirebaugh** [comment]
> per-layer transitions

Are you sure about this? As far as I know it supports per-property transitions and a style-wide default. gl-native does as well.

Documentation: https://github.com/mapbox/mapbox-gl-style-spec/issues/171
Testing: https://github.com/mapbox/mapbox-gl-test-suite/issues/116

Deprecation / removal is another alternative. This feature is not widely used. In fact I'm not aware of _any_ production use.

**Comment by lucaswoj** [comment]
> Are you sure about this?

Nope. A user was complaining that this feature stopped working. I was unaware that we ever supported per-layer transitions but gave them benefit of the doubt. 

Seeing as these mapbox/mapbox-gl-style-spec#171 and mapbox/mapbox-gl-test-suite#116 are more actionable, let's focus on those 😄
