### ISSUE TITLE
Option for queryRenderedFeatures: execute only when map.loaded()

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#2796]
Offshoot of #2471 discussion:

When I call `queryRenderedFeatures()`, I assume the results come from a fully loaded map, with zoom/center defined as the map's state at the time I invoked it. Currently, I can achieve this with:

```
map.on('render', function() {
  if (map.loaded()){
    map.queryRenderedFeatures(...);
    map.off('render');
  }
})
```

I think it's a fair assumption that no one wants to run `.qRT` on a partially loaded map, so it would be nice for the method to check for `map.loaded()` internally before doing the query. Either by default, or via some parameter like `map.queryRenderedFeatures({onDataend:true});`

**Comment by jfirebaugh** [comment]
What should it return if `map.loaded()` is false?

**Comment by peterqliu** [comment]
>What should it return if map.loaded() is false?

I should say that this option would turn `.qRT` into an async method. It would not return anything until that evaluates to `true`.

**Comment by jfirebaugh** [comment]
We had multiple design discussions regarding whether `.qRT` should be synchronous or asynchronous, and the conclusion was that a sync API was preferable. I don't think we want to re-litigate that, and I don't think it would be good API design to make it synchronous by default but asynchronous if you pass a specific option. Please continue to use the `on('render')` pattern where needed.
