### ISSUE TITLE
Suffix control class names with "Control"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2799]
Handler classes end with `Handler`. Source classes end with `Source`.

Control classes are not self-documented and namespaced in this way.

<img width="180" alt="screen shot 2016-06-29 at 11 25 06 am" src="https://cloud.githubusercontent.com/assets/281306/16463783/2b41ff36-3dec-11e6-8137-6c8fcf34bc65.png">

**Comment by mollymerp** [comment]
fixed #3355
