### ISSUE TITLE
Feature: support loading of Bing raster tiles (and other quadcode sources)

### ISSUE THREAD

**Issue by mike-marcacci** [mapbox/mapbox-gl-js#2806]
Supporting a `{quadcode}` variable in tile URL templates would open up the ability to use Bing satellite tiles. In my particular case I need the best-possible resolution imagery of San Diego to use as a base layer, and Bing is currently in the lead by a decent margin.

I just submitted PR #2805 to add this feature, and a corresponding test. Let me know if you have any questions, and thanks for keeping this excellent lib open source!

**Comment by 1ec5** [comment]
(Noting a similar request over in mapbox/mapbox-gl-native#5485.)

**Comment by mike-marcacci** [comment]
Fixed by #2805
