### ISSUE TITLE
queryRenderedFeatures Coordinate bounding box

### ISSUE THREAD

**Issue by stackTom** [mapbox/mapbox-gl-js#2807]
Is there a way to use queryRenderedFeatures with a lat/long coordinate bounding box instead of a pixel coordinate bounding box? I need to be able to draw geojson within a lat/long bounding box on zoomend based on the currently rendered features from a vector tile source. If I use the pixel bounding box parameter, the bounding box gets smaller (in terms of area covered over the Earth) or larger depending on my zoom level, since the bounding box is pixel based. If there is no lat/long coordinate bounding box option, is there some sort of multiplier by which I can multiply the pixel bounding box on zoomend to simulate a lat/long coordinate bounding box?

**Comment by jfirebaugh** [comment]
Yes, you can use [Map#project](https://www.mapbox.com/mapbox-gl-js/api/#Map#project) to convert from lat/long coordinates to pixel coordinates for `queryRenderedFeatures`.

**Comment by stackTom** [comment]
Thanks, can't believe I didn't see that as it's right next to queryRenderedFeatures in the API documentation.
