### ISSUE TITLE
Create an example that uses "Marker"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2808]

**Comment by tmcw** [comment]
Currently blocked on needing another release: Markers (or ElementMarkers) are not in 0.20.1.

**Comment by mollymerp** [comment]
Per labs scrum, @tristen is planning on making a couple examples. If you're swamped, let me know and I will jump in 👍

**Comment by lucaswoj** [comment]
A release with markers has gone out! v0.21.0

**Comment by lyzidiamond** [comment]
Closed in #2872

**Comment by infacq** [comment]
is there any? especially that uses HTML nodes

**Comment by tristen** [comment]
@infacq see https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/
