### ISSUE TITLE
(Safari) Cannot do bbox search with queryRenderedFeatures

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#2822]
Check out https://jsfiddle.net/2mfby8nh/3/. Mousing over the map provides results in Chrome, but not in Safari. Occurs with some, but not all bboxes.

**mapbox-gl-js version**: 0.20.1

### Steps to Trigger Behavior

Go to link above, in Safari.

### Expected Behavior

I expect to get results for queryRenderedFeatures in Safari.

### Actual Behavior

No results returned, instead error:

```
[Error] TypeError: undefined is not a function (evaluating 'this.keys.slice()')
	query (mapbox-gl.js, line 280)
	query (mapbox-gl.js, line 14)
	_queryRenderedVectorFeatures (mapbox-gl.js, line 68)
	queryRenderedFeatures (mapbox-gl.js, line 90)
	queryRenderedFeatures (mapbox-gl.js, line 176)
	(anonymous function) (show, line 97)
	fire (mapbox-gl.js, line 198)
	h (mapbox-gl.js, line 148)
	u (mapbox-gl.js, line 148)
```

**Comment by lucaswoj** [comment]
Sounds bad! Thanks for the report @peterqliu. I will triage and fix ASAP.

**Comment by lucaswoj** [comment]
Root cause: Safari does not support `TypedArray.prototype.slice()` [source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/slice#Browser_compatibility)
