### ISSUE TITLE
Is there a way to toggle the style smoothly?

### ISSUE THREAD

**Issue by ZhenanH** [mapbox/mapbox-gl-js#2823]
the 'setStyle' method remove the old style with layers, so it does't feel smooth when switching styles. What't the best way to switch styles for example between 'street-v9' and 'outdoors'?

thanks

**Comment by jingsam** [comment]
Use mapbox-gl-style diff https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/API.md#diffstylesbefore-after

**Comment by jfirebaugh** [comment]
Yep, that's the best way currently. See #1989 for other plans.

**Comment by ZhenanH** [comment]
Hi thanks for the reply, but I am not sure how exactly to do that, could you give me an example? thanks in advance!

**Comment by ZhenanH** [comment]
For example, https://www.mapbox.com/mapbox-gl-js/example/setstyle/ the toggle doesn't feel smooth at all
