### ISSUE TITLE
Geolocate Event

### ISSUE THREAD

**Issue by sbindman** [mapbox/mapbox-gl-js#2824]
**mapbox-gl-js version**: 0.20.1

https://github.com/mapbox/mapbox-gl-js/blob/95af24d679130dfbdb8200e1dbb295e1ab8b9679/js/ui/control/geolocate.js#L65

### Steps to Trigger Behavior

 1. ` map.on('geolocate', function(position) {
                console.log(position);
            }); `
 2. Click on geolocate control
 
### Expected Behavior
Expect geolocate event to fire.

### Actual Behavior
The locator works but the event does not fire.

**Comment by tristen** [comment]
The event is actually bound to the geolocate control not the map object.

``` js
var geolocate = new mapboxgl.Geolocate();
map.addControl(geolocate);

geolocate.on('geolocate', function(e) {
  // console.log(e);
});
```

**Comment by sbindman** [comment]
Awesome thanks!
