### ISSUE TITLE
Code documentation for 'geolocate' event

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#2825]
With reference to https://github.com/mapbox/mapbox-gl-js/issues/2824 it would be good to document `geolocator` event in a code example.

- Click on the geolocate button
- on `geolocate` add a marker to the location with a popup detailing its location.

**Comment by lucaswoj** [comment]
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2692
