### ISSUE TITLE
Expose cluster markers latitude/longitude center point

### ISSUE THREAD

**Issue by icreatestuff** [mapbox/mapbox-gl-js#2830]
I've seen these two older threads #2384 and  #2661 having searched for the same functionality. MY use case is slightly different however. I am clustering points that appear at **exactly** the same latitude/longitude (having set the clusterRadius option to '1' for the source). Is it possible to get the centre point latitude and longitude from the cluster feature from queryRenderedFeatures? If I can get access to those I can then use querySourceFeatures to filter my original data set down to matching values.

Equally I wondered if a solution to the requested feature would be to expose the clusters latitude/longitude boundary which could then equally be used to filter the original data set?

**mapbox-gl-js version**: 0.20.1

**Comment by lucaswoj** [comment]
`queryRenderedFeatures` returns an array of valid GeoJSON features, including their geometries. This should work for your purpose. If you aren't seeing the geometry, please re-open this issue as a bug.

**Comment by icreatestuff** [comment]
In that case then I think this _is_ a bug. I'm not getting any useful geometry data back in the GeoJSON feature for a cluster unless I'm missing it. See the console output I get below when clicking on a cluster point and running `queryRenderedFeatures`.

![mapbox-cluster-feature](https://cloud.githubusercontent.com/assets/1300714/16665302/fc39a488-447a-11e6-9326-b4d076babbdd.jpg)

**Comment by lucaswoj** [comment]
@icreatestuff The `geometry` property is there but displayed differently because it is a computed property (lazily evaluated). 

![fc39a488-447a-11e6-9326-b4d076babbdd](https://cloud.githubusercontent.com/assets/281306/16667228/3f4ddc52-4440-11e6-9d83-fabb814a7bd1.jpg)

**Comment by icreatestuff** [comment]
@lucaswoj Thank you! I had assumed incorrectly that the data wasn't exposed. I'm not even sure what 'lazily evaluated' means but it got the better of me.
