### ISSUE TITLE
Clusters show wrong counts when layers/markers are hidden

### ISSUE THREAD

**Issue by jvence** [mapbox/mapbox-gl-js#2831]
If you hide layers that contain markers, the count on the cluster does not change. It should reflect the number of shown markers instead of the number of total (hidden & shown) markers.

**Comment by lucaswoj** [comment]
I think you are confused @jvence. Showing and hiding are operations that can be performed only on _style layers_. Clusters display _data layers_. It sounds like you might want to use [filters](https://www.mapbox.com/mapbox-gl-style-spec/#types-filter) to filter out certain features in the _data layer_.
