### ISSUE TITLE
Using mapbox-gl in ember-cli ecosystem.

### ISSUE THREAD

**Issue by ankeshdave** [mapbox/mapbox-gl-js#2835]
Hi,
How to use `mapbox-gl` in `ember-cli` based Ember Application.
Also any document/steps on best practices for handling/specifying `access token` or `Default Map settings`
Thanks :)

**Comment by lucaswoj** [comment]
Hi @ankeshdave. I don't know of any existing ember-cli-based applications using Mapbox GL JS. I reckon that you should hardcode the access token and default map settings, like you would for any other web application.

**Comment by JamesChevalier** [comment]
I've recently come across [ember-cli-mapbox-gl](https://github.com/kennstenicht/ember-cli-mapbox-gl), which might help you out @ankeshdave ... I haven't used it, yet, so I can't comment on its quality.
