### ISSUE TITLE
#10/0.0000/0.0000 cancels a jumpto in a load event

### ISSUE THREAD

**Issue by gertcuykens** [mapbox/mapbox-gl-js#2849]
example: https://gps.nyimbo.nl/?12E01DA8-18B8-4217-B6CC-6BB06552FFD4#10/0.0000/0.0000 
(please don't quote url so I can remove)

Sometimes my jumpto in the load event doesn't happen because of a race condition with the automatic mapbox hash option I think.

PS You need to copy and past the url several times in de address bar until it gets stuck one of the times you paste it in.

Can you make sure that the load event happens after the map has been centred by the hash tag and not at the same time?

Thanks

**Comment by lucaswoj** [comment]
Hi @gertcuykens. I don't quite understand the bug that you are referencing here. Could you create a minimal demonstration of the behaviour and fill out the provided issue template?

**Comment by gertcuykens** [comment]
I think I figured it out, changing just the hash tag #10/0.0000/0.0000 in the url bar doesn't trigger the browser to refresh the complete page so map.on('style.load', function() {}) doesn't get called.

So what I need is the `moveend` event i guess. I will reopen if it is not the case, thanks
