### ISSUE TITLE
Add flow types for all public APIs

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-js#2851]
I create a Flow definition file of this library for Mapbox Studio, and chatted a little with @lucaswoj about putting that definition in this repo.

I can think of some reasons that it would be a good idea to maintain the definitions in this repo:
- Closer to the source code
- Updates would always go out with new releases
- If we ever figure out a way to autogenerate the definition from the thorough JSDoc comments it can happen here

I can't think of any reason _not_ to put the definitions here. Can anybody else?

And if we do put them here, where should they go? I'm happy to open a PR.

**Comment by lucaswoj** [comment]
The flow definitions can go in this repository's root directory. PR away!

**Comment by davidtheclark** [comment]
Are all the properties exposed in https://github.com/mapbox/mapbox-gl-js/blob/master/js/mapbox-gl.js intended to be part of the public API?

If so, we should document `version`, `util`, and `config`, and add them all the Flow definition.

(I was thinking about this because Studio uses `mapboxgl.config` so needed it in the definition.)

**Comment by lucaswoj** [comment]
- :+1: `version` I added this property and failed to document it. This can and should be documented.
 - 👎 `util` There has been a lot of debate about whether or not we should document this. The current consensus is that we should not. https://github.com/mapbox/mapbox-gl-js/issues/1408
 - ❓ `config` I'm not aware of any existing discussion about documenting this property. My opinion is that we should look into simplifying the architecture and then document it. A simpler architecture would be dropping the `config` module in favor of top level properties on `mapboxgl`.

**Comment by lucaswoj** [comment]
We now have flow built in! Reframing this ticket to be about adding flow types to all public APIs.
