### ISSUE TITLE
Line rendering problem

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#2854]
Recently I upgraded mapbox-gl-js from 0.11.0 to 0.20.0, some wired artifacts appear with line feature rendering. 
ENV: Windows 10, Chrome 51, vector tile v2(created by tilelive-bridge)

![Uploading QQ截图20160712151214.png…](https://s31.postimg.org/lpkhl3t3v/QQ_20160712151214.png)

I have created a [jsFiddle](http://jsfiddle.net/jingsam/9g7otrp5/). Please help me, thanks.

**Comment by mourner** [comment]
What's the buffer size on those tiles?

**Comment by lucaswoj** [comment]
I wonder if this could be a true positive of the "Geometry exceeds allowable extent" error message.  

ref #2568

**Comment by jingsam** [comment]
@mourner I use tilelive-bridge to generate vector tiles. I use the default configuration, which the extent should be 4096 and buffer is [128](https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_tile.hpp#L42), I guess.

Here is one of my tile: http://218.244.250.70:8090/api/v1/tilesets/foxgis/admin2/8/210/99.vector.pbf

**Comment by mourner** [comment]
I remember seeing a very similar issue earlier but can't recall the number...

**Comment by jingsam** [comment]
checkout this:
https://github.com/mapbox/mapbox-gl-js/issues/1679
https://github.com/mapbox/mapbox-gl-js/issues/1680

**Comment by jingsam** [comment]
I tried to render my style using mapbox-gl-native, same problem happens. Maybe it is the new earcut engine causing the problem?

**Comment by jingsam** [comment]
I get the warning:
```
Geometry exceeds allowed extent
```
So confirmed it is the problem of buffer size

**Comment by andrewharvey** [comment]
possibly the same issue as https://github.com/mapbox/mapbox-gl-js/issues/2676 (though I only notice it for large a canvas of 4096px)

**Comment by lucaswoj** [comment]
@jingsam are you still seeing the "Geometry exceeds allowed extent" warning message using v0.21.0?

**Comment by jingsam** [comment]
@lucaswoj Yes, v0.21.0 has the warning: Geometry exceeds allowed extent, reduce your vector tile buffer size

**Comment by lucaswoj** [comment]
@jingsam can you try reducing the vector tile buffer size?

**Comment by lucaswoj** [comment]
This problem should be fixed by reducing your buffer size.
