### ISSUE TITLE
Fix bug preventing animated "Map#rotateTo" operations inside "moveend" event listener

### ISSUE THREAD

**Issue by lcapel** [mapbox/mapbox-gl-js#2855]
Hi, I'm using the latest version of Mapbox GL JS (0.20.1) and I have this issue where when I try to call `rotateTo()` after a `moveend` event fires nothing happens. If I try to call `flyTo()` instead, it works. I'm not sure if I'm doing anything silly, here are two simple examples demonstrating the issue.

http://jsbin.com/demecovehi/1/edit?html,console,output - Fly after move end

http://jsbin.com/komaloceci/1/edit?html,console,output - Rotate after move end

**Comment by lucaswoj** [comment]
This bug can be avoided by setting `duration` to 0 or placing the call to `rotateTo` within a `setTimeout(..., 0)` block. I suspect we are getting tripped up by the inability to have multiple overlapping camera animations. 

There is likely an easy fix to this issue by ending the camera animation before emitting the "moveend" event. 

related to #2801

**Comment by lcapel** [comment]
The workaround will get me going for now, thanks for the tip! Using `requestAnimationFrame(() => { ... } )` will also do the same thing 👍
