### ISSUE TITLE
Npm packages for mapbox-gl-shaders and mapbox-gl-style-spec

### ISSUE THREAD

**Issue by kachkaev** [mapbox/mapbox-gl-js#2856]
I'm trying to use a custom version of `mapbox-gl-shaders`in my repo, but this is currently impossible because the source code of the package is linked directly rather than via `npm` registry. The same applies to `mapbox-gl-style-spec`, [as it can be seen](https://github.com/mapbox/mapbox-gl-js/blob/bdadb1d448852d7b3c02db6296384fa9ce29991b/package.json#L24-L25) from `package.json`.

The outcome of the hard-linking is that even if I `npm install path/to/my/local/mapbox-gl-shaders` or use `npm link`, `mapbox-gl` creates an extra instance of this dependency in `node_modules/mapbox-gl/node_modules/mapbox-gl-shaders`, so all my preparations become vain.

What is the reason for not having `mapbox-gl-shaders` and `mapbox-gl-style-spec` packages on npm just like others? Could you please publish them and stop hard-linking?

**Comment by jfirebaugh** [comment]
mapbox-gl-js depends on specific commit hashes of mapbox-gl-shaders and mapbox-gl-style-spec, and publishing a version to npm every time we make a commit would add additional overhead to our already burdensome dependency management process.

If you need a version of mapbox-gl-js that uses a custom version of mapbox-gl-shaders, you'll need to fork mapbox-gl-js and change the package.json. That would be the case regardless of the source of mapbox-gl-shaders we use in the canonical package.json.
