### ISSUE TITLE
Fix incorrect z coordinate on overzoomed tiles

### ISSUE THREAD

**Issue by drewbo** [mapbox/mapbox-gl-js#2868]
**mapbox-gl-js version**: 0.21.0

When calling `querySourceFeatures` past the max zoom of the source layer, the tiles returned are not in the viewport. They have the `x` and `y` values from the max zoom of the source layer but the `z` value from the actual zoom level. My recreation relies on some private layers but you can also see the error in the tile boundary calculation (11/328/794 is correct, 11/164/397 has the correct x/y for zoom 10):

<img width="257" alt="screen shot 2016-07-14 at 11 08 03 am" src="https://cloud.githubusercontent.com/assets/7108211/16846615/1b6cbb66-49bb-11e6-90e5-57a3bc156bbc.png">

I believe the [`reparseOverscaled` ternary operator](https://github.com/mapbox/mapbox-gl-js/blob/de61bbfa21f070e7afbe4fd42e24e8e44e7e25f1/js/source/tile_pyramid.js#L151) is reversed in the `TilePyramid`; when swapping `z` and `actualZ` locally the problem was resolved. I can add a PR but not sure of a good test case

**Comment by lucaswoj** [comment]
See #1912 for more context
