### ISSUE TITLE
Create an automated test of webpack build flow

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2873]
We've had a number of bugs arise in our webpack build flow. Because this build flow is not used within Mapbox it is not regularly tested. We can mitigate the problem by creating an automated test of the webpack build workflow, ensuring no errors are encountered during the build process, and doing a basic sanity check on the build outputs. 

ref #1649 #2857

**Comment by mourner** [comment]
https://github.com/mapbox/mapbox-gl-js/blob/master/test/build/webpack.test.js
