### ISSUE TITLE
Markers added far away from the initial Map Center never show on the map

### ISSUE THREAD

**Issue by adcooley** [mapbox/mapbox-gl-js#2879]
**mapbox-gl-js version**: 0.21.0

### Steps to Trigger Behavior

 1. Open the jsbin: https://jsbin.com/riguyowutu/1/edit?html,css,output
 2. I only slightly modified the Marker().addTo(map) example in the docs. You'll notice I'm adding two icons, but only the one near the initial map `center` is showing. The other will never show.
 3. Swap the initial `center` for the map (using the commented code) to see that the other will now show.

### Expected Behavior
I expect all Markers added (especially when there are only 2) to show on the map when within the viewing range.

### Actual Behavior
Only markers added near the inital Map `center` are showing. I've tested adding a lot to both vicinities and multiple will show, but only near the initial `center`.

**Comment by jfirebaugh** [comment]
I'm seeing both markers:

![image](https://cloud.githubusercontent.com/assets/98601/16891768/4612d50e-4ab4-11e6-9bd6-5b78616204e7.png)

Perhaps you are looking 360 degrees to the east or west of this view? `Marker`s do not automatically repeat themselves across the antimeridian; if you desire that behavior you'll need to add multiple copies of the marker.

**Comment by peterqliu** [comment]
>if you desire that behavior you'll need to add multiple copies of the marker.

@adcooley alternately, you can set [lnglat bounds to the map](https://www.mapbox.com/mapbox-gl-js/api/#LngLatBounds) so that it never pans past where you'd like the markers to be

**Comment by adcooley** [comment]
@jfirebaugh I'd love to be able to reproduce the correct behavior… if I open the above jsbin, wait for the map to load, and zoom straight out, only one icon is visible.

I think I see what you mean about moving 360 deg, but i assumed if I head in one direction, I would see the 2nd icon before reaching the non-repeated first icon again.

**Comment by adcooley** [comment]
@peterqliu I'll give that a go too, thanks!

**Comment by adcooley** [comment]
@jfirebaugh I understand now, took me a bit to grasp what was going on.

I think the reason I was so confused is that when I add a layer source with 'symbol features', they are re-added to the map automatically as you scroll in either direction, whereas the Markers are not. For now I've worked up a solution that checks `moveend` and removes/re-adds Markers with the appropriate +-360 offset. Would love for this feature to be handled automatically!
