### ISSUE TITLE
mapbox for webtoolkit (info, not an issue)

### ISSUE THREAD

**Issue by yvanvds** [mapbox/mapbox-gl-js#2884]
Hey, by lack of a user forum, this space seemed like the best spot to notify you about some code I wrote: I created a bunch of classes to use mapbox-gl-js with webtoolkit, which is a c++ interface to create single page applications.

All code can be found on my github page: https://github.com/yvanvds/wtMapbox

The interface is not complete yet, but a lot of the demo applications are already implemented and working. 

Maybe it would be of use to other developers as well.

**Comment by lucaswoj** [comment]
Thank you @yvanvds! I just created a [new section in the `README.md`](https://github.com/mapbox/mapbox-gl-js#third-party-projects) to showcase this and other awesome 3rd party integrations. https://github.com/mapbox/mapbox-gl-js/commit/92a1c72b6e804e4a86fe94f3d53c8614c314f725
