### ISSUE TITLE
line-offset direction changed in v0.20.1

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#2889]
`mapbox-gl-js v0.21.0` bumped `geojson-vt` to `2.2.0` in https://github.com/mapbox/mapbox-gl-js/commit/ea3986698c2773cad9957356da7bd403d0356f0c. https://github.com/mapbox/geojson-vt/commit/a3aa2fa80b59ff993f864b94c4d23f3bda0318ad rewound polygons for vt2 compliance.

https://www.mapbox.com/mapbox-gl-style-spec/#paint-line-offset says

>positive indicates “rightwards” (if you were moving in the direction of the line) and negative indicates “leftwards.”

Currently using a Mapbox source a positive line-offset is inside the polygon (hasn't changed between v0.20.1 and v0.21.0).

Prior to `geojson-vt 2.2.0` (v0.20.1) a positive line-offset value was outside the polygon (which is inconsistent between mapbox and geojson sources :disappointed:), post  `geojson-vt 2.2.0` (v0.21.0) it reversed to positive being inside the polygon (which is now consistent with mapbox and geojson sources :smile:)

v0.21.0 ->  http://jsbin.com/qesaxohoka/1/edit?html,output
v0.20.1 -> http://jsbin.com/mopovifeni/1/edit?html,output

I think this change should be documented as a breaking change in v0.21.0, as it's nice it's now consistent. Something like this https://github.com/mapbox/mapbox-gl-js/pull/2890 ?.

It might also be helpful for designers if the mapbox-gl-style-spec was specific about the association between inside/outside and positive/negative offsets when the actual geometry is polygon, not just in relation to the direction of polylines. It's useful for doing inner/outer shadow/glow effects on polygons in that case you need to know what's going to make an inner shadow vs outer shadow.

**Comment by jfirebaugh** [comment]
I believe a more accurate/pedantic summary of the geojson-vt change is that geojson-vt now _enforces_ [the winding order specified by the Vector Tile specification](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/README.md#4344-polygon-geometry-type), whereas before it happened to return results with the same winding order as the input.

Note that although it was left undefined in the original GeoJSON specification, recent IETF drafts of the GeoJSON specification [define a winding order consistent with vector tiles](https://tools.ietf.org/html/draft-ietf-geojson-04#section-3.1.6). (It may appear at first glance to be inconsistent, but remember that GeoJSON uses a Y-up axis while Vector Tiles are Y-down.)

I agree we should mention the change in the CHANGELOG and spell out the intended behavior of `line-offset` for polygons in the style spec.

**Comment by andrewharvey** [comment]
That makes sense, thanks for the additional information!

>I agree we should mention the change in the CHANGELOG and spell out the intended behavior of line-offset for polygons in the style spec.

:+1:

**Comment by lucaswoj** [comment]
> spell out the intended behavior of line-offset for polygons in the style spec

Do you think it'd be possible to normalize `line-offset` so that users don't have to think about winding order? In practice, this could mean multiplying line offsets for odd-numbered inner rings by -1.

**Comment by jfirebaugh** [comment]
That's what rewinding in geojson-vt accomplishes -- it ensures that a positive `line-offset` consistently insets polygons, regardless of the input winding order.

**Comment by lucaswoj** [comment]
I meant normalizing so that `line-offset` doesn't reverse direction on each successive ring "depth." (Apologies if I'm misunderstanding the situation -- this isn't my area of expertise.)

**Comment by jfirebaugh** [comment]
Gotcha. Fortunately we don't have to worry about that, because both GeoJSON and Vector Tiles support only a single level of ring nesting.
