### ISSUE TITLE
Issue an error when map canvas is larger than allowed by gl.MAX_RENDERBUFFER_SIZE

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2893]
Once the map canvas is larger than `gl.MAX_RENDERBUFFER_SIZE / 2`, scaling behaviour starts to occur. I do not think we should invest significant resources into accommodating this case. 

See https://github.com/mapbox/mapbox-gl-js/issues/2673 and https://github.com/mapbox/mapbox-gl-js/issues/2863

**Comment by stepankuzmin** [comment]
Hi @lucaswoj! I'd like to help with some issues at my spare time. Is it correct, that the Error need to be thrown when `canvas.width` or `canvas.height` is larger than `gl.MAX_RENDERBUFFER_SIZE / 2` [like this](https://github.com/stepankuzmin/mapbox-gl-js/commit/c14d390b704aa0d48f3169396f048a060ae3da37)?

**Comment by lucaswoj** [comment]
Thank you thank you thank you @stepankuzmin. 🙇 

Your commit is on the right track. I'll leave my feedback as comments on that commit.

**Comment by stepankuzmin** [comment]
I've made a [PR](https://github.com/mapbox/mapbox-gl-js/pull/3841).

**Comment by 1ec5** [comment]
This change was reverted in #3986 because it caused #3915 in Firefox. Reopening.

**Comment by kristfal** [comment]
Just wanted to add that this change broke iPhone (6,6s,7) Plus and iPads with Retina Display support when the map was initialized as a full screen map. 

iOS have a MAX_RENDERBUFFER_SIZE of 4096, so please make sure that that it works with resolutions up and including 2732px.

**Comment by stepankuzmin** [comment]
We still need to issue an error or not?

**Comment by lucaswoj** [comment]
@stepankuzmin I'm going to add a warning message instead of an error. There are some systems in which we're firing an error and unnecessarily breaking functional maps.

**Comment by andrewharvey** [comment]
@lucaswoj I can no longer replicate the two original issues #2673 and #2863 when using 0.29.0. If others can confirm this, then I don't think we need a warning for `gl.MAX_RENDERBUFFER_SIZE / 2`.
