### ISSUE TITLE
Document viewport-based limitation on zooming out

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-js#2904]
I'm told by @samanpwbb that a feature of Mapbox GL JS is that it sets a minimum zoom based on your viewport size, so you can't zoom out far enough to see empty space instead of map. That explains why I've been unable to zoom out to level 0.

I can't find this in the documentation. Is it there? If not, I think it probably should be. I know it confused me.

I tried searching through issues to find a record about this but didn't uncover anything, though I imagine it must have been discussed before and I just didn't find it. Sorry if this is a duplicate.

**Comment by asheemmamoowala** [comment]
This was partially fixed in #9028. You can now zoom out to see a full world (i.e z0 tile) even on small viewports. This does not impact odd-shaped viewports though.
