### ISSUE TITLE
Fix bug causing symbols to be clipped when many are rendered

### ISSUE THREAD

**Issue by AndyMoreland** [mapbox/mapbox-gl-js#2907]
**mapbox-gl-js version**: v0.20.0, v0.20.1, v0.21.0.

Occurs in all browsers I've tested including chrome 51, FF47, FF39 and a few others on Mac OS and windows.

Repro here: http://23.239.25.88/repro.html 

To view the behavior, zoom in and out. When zoomed in, the sprites render at the coordinates specified by the geojson point geometry. When you zoom out past zoom level 10, copies of the sprites start being rendered in the "background" (or something) of the labels of the point data and the map is very clearly no longer correct.

I started observing this behavior circa mapbox-gl-js v0.20.0 in maps with more complicated sprite sheets and geometries. I bisected mapbox-gl-js and I believe the behavior was introduced in one of these commits: {e268120, 6537f3e, 92fbfb8}.

This example is probably not minimal, but I trimmed as much of the source map out as I could.

When you cross the zoom-level inflection point you should see the map transition from something like:

<img width="1032" alt="screen shot 2016-07-23 at 4 06 56 pm" src="https://cloud.githubusercontent.com/assets/37327/17080738/ab0989da-50ef-11e6-98f7-f0bec6423065.png">

which is correct, to:

<img width="1069" alt="screen shot 2016-07-23 at 4 07 03 pm" src="https://cloud.githubusercontent.com/assets/37327/17080741/b6001b74-50ef-11e6-8e09-ed0f429de9a7.png">

which is incorrect.

**Comment by Que3216** [comment]
Would be awesome to have a fix for this!

**Comment by mollymerp** [comment]
Thanks for reporting this issue @AndyMoreland -- could you please post a link to the `style.json` for the error reproduction example? I can't reproduce this behavior with other styles I've tried so it will be helpful to see the style to track down the root issue.

**Comment by AndyMoreland** [comment]
http://23.239.25.88/repro.json

**Comment by Que3216** [comment]
I've made a slightly simpler repo here: http://jsfiddle.net/Lqgnyna3/4/

![image](https://cloud.githubusercontent.com/assets/793481/17295633/05977234-57f5-11e6-9f1e-b664c33c39a0.png)

**Comment by Que3216** [comment]
Even simpler repro: http://jsfiddle.net/Lqgnyna3/5/

**Comment by lucaswoj** [comment]
There are two places that we fork on `text-allow-overlap` and `icon-allow-overlap`: 

  1. when we enable / disable `gl.STENCIL_TEST`
  2. when we populate the [grid index](https://github.com/mapbox/grid-index)

I've ruled out 1. as a source of the bug by hardcoding `gl.STENCIL_TEST` enabled / disabled and observing the bug.

More investigation is needed to determine if grid index could be the source of the bug. I'm especially interested to see if there are any places where this number of symbols could cause an integer overflow in grid index.

**Comment by AndyMoreland** [comment]
If it helps, I've updated my initial repro up above to remove the extremely large `filter` clauses and set `text-allow-overlap` and `icon-allow-overlap` to true for all symbol layers, and I still see the issue.

**Comment by mollymerp** [comment]
@AndyMoreland @Que3216 You're experiencing 2 issues:

1. sprite rendering artifacts: I've isolated this to integer overflow in the [`SymbolInstancesArray`](https://github.com/mapbox/mapbox-gl-js/blob/master/js/symbol/symbol_instances.js#L19-L27)

`iconQuadStart(/End)Index = UInt16`
![screen shot 2016-08-08 at 4 24 20 pm](https://cloud.githubusercontent.com/assets/2425307/17494868/9d5232c8-5d84-11e6-8623-ced9284f024e.png)

`iconQuadStart(/End)Index = UInt32`
![screen shot 2016-08-08 at 4 28 05 pm](https://cloud.githubusercontent.com/assets/2425307/17494978/1a234ecc-5d85-11e6-9ff4-fffbfb9e858d.png)

For now, modifying the code I referenced above should solve your rendering artifacts. 

2. The second issue is this [known bug](https://github.com/mapbox/mapbox-gl-js/issues/2706). Usually I don't see this problem when both `icon-overlap` and `text-overlap` are set to true, but apparently with giant geojson point data sources the behavior still exists.

**Comment by mollymerp** [comment]
We shipped #2966 which adds a warning when there are too many glyphs / icons being rendered in a tile. changing the

**Comment by AndyMoreland** [comment]
@mollymerp I made the change that you suggested (against v0.22.1), but it caused:

`glDrawElements: attempt to access out of range vertices in attribute 0`

which seemed to break the rendering.

**Comment by AndyMoreland** [comment]
Hm. I might have built my fork wrong. It does seem to work now! Thanks.

**Comment by bhison** [comment]
> We shipped #2966 which adds a warning when there are too many glyphs / icons being rendered in a tile. changing the `type` of `icon(/glyph)QuadStartIndex` + `icon(/glyph)QuadEndIndex` in [this](https://github.com/mapbox/mapbox-gl-js/blob/master/js/symbol/symbol_instances.js#L19-L27) code to `UInt32` should solve the rendering issues you're experiencing.

This link is now dead, any chance someone could inform us travellers from the future what the workaround looked like? I can't find anything in the documentation about start/endquadindex. Thanks in advance.

**Comment by lucaswoj** [comment]
@bhison I think the code you're seeking has moved here: https://github.com/mapbox/mapbox-gl-js/blob/master/src/data/bucket/symbol_attributes.js#L64

**Comment by bhison** [comment]
@lucaswoj thank you! Do you have an idea how I can change this type? I feel a bit out of my depth here.

**Comment by lucaswoj** [comment]
@bhison Unfortunately the process is rather involved. You'll need to figure out exactly which attributes are overflowing because of a too-small integer type, fork GL JS, change those types, and create your own build. I don't recommend it.

**Comment by bhison** [comment]
@lucaswoj oh ok. So the alternative is...have fewer symbols I guess?

**Comment by lucaswoj** [comment]
@bhison hard to say... it all depends on the situational specifics

**Comment by ChrisLoer** [comment]
It turns out this situation can also cause an exception to be thrown during rendering (assuming this code hasn't diverged too much from MapLibre) -- in line label projection, the code checks to see if there's enough room for all the glyphs on a line by checking that the first and last glyph fit. The code assume that the glyphs are in increasing-offset order. However, if the offsets get jumbled by the overflow, it's possible for a "middle" glyph to be outside of the min/max offset. When the code tries to place the glyph, it can't find a place to put the glyph on the line and ends up doing a null pointer dereference.
