### ISSUE TITLE
Touch events do not work on Windows 10 Edge Browser.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#2911]
**mapbox-gl-js version**: v0.21.0

### Steps to Trigger Behavior
None of the following samples respond to touch for pan/zoom/rotate on Edge browser running on Windows 10.  Map renders but does not respond to any of the touch events.
 
https://www.mapbox.com/mapbox-gl-js/examples/

### Expected Behavior
Map should rotate/pan/zoom touch gestures like it does on iOS and Android touch devices.

### Actual Behavior

Map renders but does not respond to any of the touch events.

**Comment by lucaswoj** [comment]
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/1928
