### ISSUE TITLE
Render features outside the range of real longitudes

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-js#2912]
We're having a problem in `mapbox-gl-draw`: https://github.com/mapbox/mapbox-gl-draw/issues/458. If you spin the globe a time or two and then try to draw, you'll create coordinates outside the real range of longitudes, like this point:

```json
{
	"id": "9fff69e4acb4b4e9d0175eaa7c7255ca",
	"type": "Feature",
	"properties": {},
	"geometry": {
		"coordinates": [460.6260419749865, 59.16322869014476],
		"type": "Point"
	}
}
```

Then when we try to render the features, GL JS errors.

![screen shot 2016-07-27 at 8 48 33 am](https://cloud.githubusercontent.com/assets/628431/17182231/b2d0cf76-53d7-11e6-9deb-1ef1c7884631.png)

The stack trace isn't very helpful here, but I thought someone who works on this library regularly might know the reason for the error.

I've tried some experiments in Draw to normalize positions as you create them, so that they always fall within the real range; but those failed because of lines and polygons. Those features might actually want to stretch around the world. And other weird things can happen because of the attempt at normalization (esp. lines wrapping the opposite direction you wanted them to wrap). 

So the simplest solution seems to be to allow rendering of these positions. Do you think that is a possibility?

cc @mcwhittemore, @tmcw, @samanpwbb

**Comment by mourner** [comment]
Handling this on the geojson-vt side is tricky (see https://github.com/mapbox/geojson-vt/pull/69). Could we fix it on the draw side so that coordinates don't go over -540–540 range and are wrapped automatically?

**Comment by mcwhittemore** [comment]
@mourner why does gl-js support longitudes outside of +/-540? Why doesn't it just snap back to -180 when 540 is reached?

**Comment by mourner** [comment]
@mcwhittemore it can snap back I think, although there will still be edge cases, e.g. a very wide map with a small height that fits many worlds — even if you snap, some will still be visible.

**Comment by mcwhittemore** [comment]
ah, multiple world support is to make sure the canvas is filled. Gotcha. That makes sense.
