### ISSUE TITLE
Add StyleOptions to setPaintProperty

### ISSUE THREAD

**Issue by bryanjjohnson** [mapbox/mapbox-gl-js#2913]
Would it be possible to add StyleOptions to setPaintProperty? I have been attempting to do an animation using the setPaintProperty, but I find that occasionally I get a stack exceeded error. Looking into it, it appears to be that the StyleTransition activated with each setPaintProperty was stacking up over the animation frames. So being able to turn that off would be nice.

**Comment by lucaswoj** [comment]
Merged with https://github.com/mapbox/mapbox-gl-js/issues/1142
