### ISSUE TITLE
Map Don't Center to Negative Latitude and Negative Longitude

### ISSUE THREAD

**Issue by brunoleaomaia** [mapbox/mapbox-gl-js#2914]
**mapbox-gl-js version v0.21.0**:

### Steps to Trigger Behavior

var map = new mapboxgl.Map({
                container: 'mapContainer',
                style: 'mapbox://styles/mapbox/basic-v9',
                zoom: 13,
                center: [-8.039469, -34.921480]
            });

### Expected Behavior

Center Map at Lat,Lng -8.039469, -34.921480

### Actual Behavior

Center Map in Middle of Ocean (I think 0,0)

**Comment by tmcw** [comment]
Hi Bruno,

When you specify a coordinate as a two-number array, Mapbox GL JS  interprets that array in the order `longitude, latitude`, not `latitude, longitude`. This is [documented in the Map constructor](https://www.mapbox.com/mapbox-gl-js/api/#Map) and reflected by the main coordinate type, [LngLat](https://www.mapbox.com/mapbox-gl-js/api/#LngLat). It reflects the coordinate order present in the currently-supported data type, GeoJSON, which also specifies longitude, latitude order.

Closing as invalid - sorry for the confusion, and we understand that latitude, longitude is often the order used in conversation, but it isn't the order mainly used in software, including Mapbox GL JS.

- Tom

**Comment by brunoleaomaia** [comment]
Thank you @tmcw by the information. I'm using the Mapbox JS (Not GL) and Array is [lat, lng], in constructor, markers, polylines, bounds, etc. I think this is the mainly order used in software like Google Maps JS Api, LeafletJS, OpenStreetMap, HERE, etc. But Thank you, now I know that Mapbox GL is LngLat.

https://www.mapbox.com/mapbox.js/api/v2.4.0/l-latlng/
