### ISSUE TITLE
MapBoxgl is undefined (conflict with API's loaded before it)

### ISSUE THREAD

**Issue by powersparks** [mapbox/mapbox-gl-js#2916]
not sure if this is a mapbox issue... 
I'm working with multiple api's on a website and found that mapbox api needs to be listed first in some cases using
mapbox-gl-js/v0.21.0/

Example is here: 
https://jsbin.com/putuqu/edit?html,output

I'm not sure if it's related to dojo that gets loaded with the ArcGIS api, or if there is a global that's getting stepped on that MapBox is dependent on.

https://stackoverflow.com/questions/tagged/mapbox-gl-js

 ### Steps to Trigger Behavior

 1. move the arcgis api reference above the mapbox reference in provided example

### Expected Behavior
MapBox api order shouldn't matter unless there is a dependency

### Actual Behavior
MapBox needs to be loaded first, before the ArcGis Api.

reach me at powersparks@gmail.com
v/r
Harley

**Comment by mourner** [comment]
This looks like a problem on the ArcGIS JS API side — all errors in the console point to it when you switch the order.

**Comment by powersparks** [comment]
this is just a guess... but there is a final error that mapboxgl is undefined... which is the last error.   There must be a global that mapbox creates, after the argis api created it... that would be why mapbox needs to load first... so arcgis api does a  check to see if the global already exists, and then extends or doesn't try to load it twice. MapBox doesn't check to see if the global already exists, it just assumes it's the only api.

**Comment by powersparks** [comment]
this is minor... and I appreciate your consideration on the issue.  I'll try to find something more definitive as to the cause.
