### ISSUE TITLE
Inserting breakpoints in worker.js or descendent calls. (Need workaround)

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#2919]
**mapbox-gl-js version**:master

### Steps to Trigger Behavior

 Inserting breakpoints in worker.js methods or descendent calls from them does not work in
chrome as well as firefox.

For e.g. insert a breakpoint in worker.js:'load tile' or
vector_tile_worker_source.js:'loadTile' does not work. 
The only way is to manually break into the debugger by adding 'debugger;' call
in the code.

Can you please suggest a way to insert breakpoints/debug worker code without having to manually edit it every time?

**Comment by mourner** [comment]
I don't think this is something we can fix on the GL JS side — I guess it's due to the way we create web workers with `webworkify`, which constructs workers with a string blob. Adding `debugger` in the code is a good workaround IMO.
