### ISSUE TITLE
Style source reload error on browser tab change

### ISSUE THREAD

**Issue by twelch** [mapbox/mapbox-gl-js#2926]
Observed with version 0.21.0 or latest master

I have a web socket streaming in events multiple per second. Each event is added to the map as a point icon for 2 seconds using its own source and layer.  All is good until I change browser tabs, then I observe that the map stops re-rendering (to be efficient I assume) and the style update queue starts filling.  When I switch back to the map tab, the style update resumes and batch processes the queue (with all of the source adds/removes), and I get a source reload error.

I didn't have this error with version 0.15.0, prior to the refactoring of batch processing.

### Example

Try out https://jsbin.com/zehuloqofu/edit?html,console,output

You should see contour sources and layers getting added and removed in quick succession.  Now change tabs for at least a few seconds and then change back.  Observe the console error _Cannot read property 'reload' of undefined_.  After that the map is in a broken state and you'll need to refresh.

From what I've observed the error is due to the Style trying to [reload](https://github.com/mapbox/mapbox-gl-js/blob/e60b53bf853a75724e8b6298cefdab562dd9607f/js/style/style.js#L704) one of the short-lived sources from [Style.update](https://github.com/mapbox/mapbox-gl-js/blob/e60b53bf853a75724e8b6298cefdab562dd9607f/js/style/style.js#L293), after its been removed.

I think what's happening is that the Style object isn't deleting source id's from it's internal _updates.sources list when [Style.removeSource](https://github.com/mapbox/mapbox-gl-js/blob/e60b53bf853a75724e8b6298cefdab562dd9607f/js/style/style.js#L359-L381) is called as is done for [_updates.layers](https://github.com/mapbox/mapbox-gl-js/blob/e60b53bf853a75724e8b6298cefdab562dd9607f/js/style/style.js#L452)

### The fix

Pull request forthcoming that I think resolves the issue.  Comments welcome, thanks.

**Comment by mourner** [comment]
Thanks! The fix looks right, merged.
