### ISSUE TITLE
issues with max zoom in raster layers

### ISSUE THREAD

**Issue by calvinmetcalf** [mapbox/mapbox-gl-js#2928]
**mapbox-gl-js version**: 0.21.0
### Steps to Trigger Behavior
1. create a map with vector tile style and set maxZoom to be 18
2. add a raster layer with a maxzoom (note capitalization) also of 18
3. zoom to level 18
### Expected Behavior

raster layer shows
### Actual Behavior

raster layer does not show

I can work around by setting the global maxZoom to be 17.9 seems like there might be a greater than in one place but a greater than or equals in another

**Comment by mourner** [comment]
I think this may be related to https://github.com/mapbox/mapbox-gl-js/issues/685 (a design decision rather than a bug in raster code)

**Comment by calvinmetcalf** [comment]
ah, it's unclear which params are for map zooms and which are for tile zooms
