### ISSUE TITLE
Support fractional minzoom values

### ISSUE THREAD

**Issue by vicapow** [mapbox/mapbox-gl-js#2929]
minzoom and maxzoom on layers don't seem to respect floating point values and instead round up.

Here's a quick demo: https://jsfiddle.net/oopkjeak/16/

If this is expected, maybe the docs should mention this and style validators should check for integers?

Otherwise, it would be awesome to support floating point values!

**Comment by shortsleeves** [comment]
FWIW - The style spec seems to indicate floats should be valid: [#layer-minzoom](https://www.mapbox.com/mapbox-gl-style-spec/#layer-minzoom)

**Comment by lucaswoj** [comment]
This is not but could be supported 😄

**Comment by lucaswoj** [comment]
Let me know if there is anything I can to do help you put together a PR @vicapow. 🙇

**Comment by mollymerp** [comment]
fwiw `maxzoom` seems to respect float values https://jsfiddle.net/cmozpyyk/

**Comment by vicapow** [comment]
@lucaswoj I spent some time digging but wasn't able to find where this is happening. Any pointers on where to look? really odd that this happens for min but not max.

**Comment by lucaswoj** [comment]
My theory is that the library that creates vector tiles, `geojson-vt`, is generating tiles from `floor(minzoom)` to `floor(maxzoom)`. We can overzoom to render tiles > maxzoom but we cannot "underzoom" to render tiles < minzoom. The fix may be to explicitly `ceil(minzoom)` before passing it to `geojson-vt`

**Comment by asheemmamoowala** [comment]
Close in #5039
