### ISSUE TITLE
Add example showing use of Marker#setPopup

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#2931]
In reviewing @YunjieLi 's Marker demo, I discovered that a `Popup` created on a click event to another DOM event, without `closeOnClick` set to `false`, will close itself immediately after being created giving the appearance that the popup class didn't work. 

Minimal example [here](https://jsfiddle.net/madedwqv/2/)

We should stop propagation by default in `Popup()`

**Comment by jfirebaugh** [comment]
Interesting example! Can you say more about what you mean by stopping propagation in `Popup`? It's not clear to me how that would resolve the situation here:

1. `click` event sent to `marker_el` listener, which creates and adds the `Popup`.
2. `click` event bubbles to the canvas container, triggering the map `click` event.
3. Map `click` event triggers `Popup:: _onClickClose`.

The possible solutions I see are:

1. Fix this specific example directly, by stopping propagation in the `marker_el` listener.
2. In `Popup::addTo`, delay binding `Popup:: _onClickClose` until the next tick.

I prefer the first solution, as in my experience when you mix asynchronicity and event bindings at the library level, it starts to become difficult to reason about the behavior. In Leaflet I recall seeing fixes of this sort cause regressions elsewhere.

**Comment by mollymerp** [comment]
Ah yes, you're right @jfirebaugh stopping propagation on `Popup` doesn't make any sense. 

Leaflet implements its own `DomEvent` class that has a [`stopPropagation` method](https://github.com/Leaflet/Leaflet/blob/cd30e283cf3b20453f7bffe300e0a1459e5c2060/src/dom/DomEvent.js#L156-L168), and I agree that we should avoid trying to add this layer of abstraction / complexity to DOM interactions in GL-JS. 

I suppose a solution would be to add an example showing how you'd need to implement a click listener on `Marker` to add a `Popup` because I think the use case is fairly common.

**Comment by jfirebaugh** [comment]
Good point, it is a very common use case. We could also consider a [`bindPopup`](http://leafletjs.com/reference.html#marker-bindpopup)-like API for `Marker`.

**Comment by mollymerp** [comment]
Oh I like that idea! I'll work on a PR.

**Comment by jfirebaugh** [comment]
`Marker#setPopup` landed; now we should make an example that uses it.

**Comment by dasulit** [comment]
I added this example in this PR: https://github.com/mapbox/mapbox-gl-js/pull/3287
