### ISSUE TITLE
Webpack issue: Could not locate module containing worker function!

### ISSUE THREAD

**Issue by bensleveritt** [mapbox/mapbox-gl-js#2933]
Using `webpack`, `mapbox-gl@0.21.0` doesn't work, and with `webworkify-webpack` offering this error:

```Uncaught Error: webworkify-webpack: Could not locate module containing worker function! Make sure you aren't using eval sourcemaps and that you pass named functions to webworkify-webpack!```

I have made [as much an isolated repo to showcase the issue](https://github.com/bensleveritt/mapbox-gl-webworkify-webpack-issue) as I can. I'm using webpack 2, but it seems to occur with webpack 1 too. Wonder if it's related to https://github.com/mapbox/mapbox-gl-js/pull/2887 in someway?

**mapbox-gl@0.21.0**:

### Steps to Trigger Behavior

 1. [Install and run issue demonstration](https://github.com/bensleveritt/mapbox-gl-webworkify-webpack-issue)

### Expected Behavior

Basic map rendered in browser.

### Actual Behavior

No map rendered, aforementioned error message in console.

**Comment by bensleveritt** [comment]
This issue is with `webworkify-webpack@1.1.4` and up. `1.1.3` seems to work with this version of `mapbox-gl`.

I'll raise it with `webworkify-webpack`

**Comment by lucaswoj** [comment]
@bensleveritt I think this is fixed by https://github.com/mapbox/mapbox-gl-js/pull/2887, which is ready to merge
