### ISSUE TITLE
drawAcrossEdges logic is incorrect / text-allow-overlap, text-ignore-placement, icon-allow-overlap and icon-ignore-placement results in clipping across tile boundaries

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#2937]
**mapbox-gl-js version**: Master

### Steps to Trigger Behavior
Add a symbol layer with following layout properties.  With these layout properties, text should be rendered with possible collisions. This works but text that crossing tile boundaries is clipped. (The same is true for icon-allow-overlap and icon-ignore-placement properties).  This happens because the  [drawAcrossEdges](https://github.com/mapbox/mapbox-gl-js/blob/c78a89bb69455925d72b029232bbbf7a5bc4652c/js/render/draw_symbol.js#L13) logic is wrong. Remove the not at the beginning of the condition. Verified that the clipping goes away with this change in master.

       "text-allow-overlap" : true,
       "text-ignore-placement" : true,
 

 2.
 3.

**Comment by lucaswoj** [comment]
Thanks for the report @mb12. This behaviour is intentional (though undesirable) as it prevents double-drawing along tile boundaries. We have an existing ticket for this issue open at https://github.com/mapbox/mapbox-gl-js/issues/2706.

**Comment by mb12** [comment]
In this case double drawing of glpyhs and icons across tile boundary is necessary and required.  With "text-allow-overlap"  it is okay to allow overlap of glpyhs irrespective of whether the overlap is between symbols within a tile or across tiles. 

clipping symbols across tile boundary makes the map look broken.
