### ISSUE TITLE
numSubLayers should be a constant independent of underzoom/overzoom (make it consistent with mapbox-gl-native).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#2939]
**mapbox-gl-js version**:master

### Steps to Trigger Behavior
[painter.numSubLayers
](https://github.com/mapbox/mapbox-gl-js/blob/def9cb5165e06f2a225e2df5854a0a14f50ad53f/js/render/painter.js#L37
)  is currently set to constant that is a function of underzoom/overzoom properties. This is wrong. It can be as low as 3 (For anti-aliasing we use 3 sublayers). This would result in better utilization of depthRange.
Even 14 is logically correct. Currently when reviewing the code, it gives the impression that this is somehow a function of underzoom/overzoom.

This change will also make it consistent with mapbox-gl-native (which uses the const 3 for numSubLayers).

**Comment by lucaswoj** [comment]
> Even 14 is logically correct. Currently when reviewing the code, it gives the impression that this is somehow a function of underzoom/overzoom.

`numSublayers` _is_ a function of the underzoom / overzoom range. See https://github.com/mapbox/mapbox-gl-js/pull/2282 for more context. In this case we should change GL Native to become consistent with GL JS, not the other way around.
