### ISSUE TITLE
Recommended way to switch tile URLs and reload tiles

### ISSUE THREAD

**Issue by Scarysize** [mapbox/mapbox-gl-js#2941]
So I already ask this on stackoverflow without getting an answer: http://stackoverflow.com/questions/38631344/recommended-way-to-switch-tile-urls-in-mapbox-gl-js

### Situation

We render a raster layer to the map. The layer's source has an initial tile url. Now we want to change the tile url of the source and trigger a reload for the new tiles.
E.g.: We have tiles for different points in time and we want to step through the different time steps.

### What can be done in `mapbox-gl@0.21.0`

```js
map.addSource('tile-source', {...});
map.addLayer('tile-layer', {source: 'tile-source', ...});

// react to a button click or what ever to trigger tile url change
...
const source = map.getSource('tile-source');
source.tiles = ['new-tile-url'];
source._pyramid.reload();
```
This works fine. But, of course, using private methods is bad practice; see the reason below:

### What can be done with the current version from github 
*(Latest commit b155118, 2016-07-28)*

```js
// init map, add layer, add source, like above
const source = map.getSource('tile-source');
source.tiles = ['new-tile-url'];

map.styles.sources['tile-source'].reload();
```

It has to be done this way, because the former `TilePyramid` has been refactored to a `SourceCache`. Here we are calling `reload()` on the `SourceCache` not the `RasterTileSource`. It seems that we don't have to use any private methods anymore, though this still looks like undocumented API, which may break in future versions.

Also there seems to be an issue with a memory leak when calling `reload()`: #2266 

Additionally the cache gets cleared when calling `reload()`. Which for now doesn't seem to be an issue.

### Question
What is the recommended way to do something like this? Is this a feature being worked on? Is there an explanation why this isn't a feature (yet) or never will be?

**Comment by lucaswoj** [comment]
Thank you for using GL JS. Due to the large volume of issues we get and the relatively small size of our team, we are unable to provide support here on GitHub. I have responded to your question on SO.

**Comment by ilomon10** [comment]
> ### ...can be done with the current version from github
> _(Latest commit [b155118](https://github.com/mapbox/mapbox-gl-js/commit/b155118cd65ee35d689ff85edb41e2411bbf1059), 2016-07-28)_
> 
> ```js
> // init map, add layer, add source, like above
> const source = map.getSource('tile-source');
> source.tiles = ['new-tile-url'];
> 
> map.styles.sources['tile-source'].reload();
> ```
> 
> It has to be done this way, because the former ....

source url from `map.getStyle().sources` not updated after `reload()`

any best practices for this method or official api to update source tile/url?

**Comment by bergkvist** [comment]
Note that the solutions mentioned earlier here no longer works. Instead, use this:

```js
// Set the tile url to a cache-busting url (to circumvent browser caching behaviour):
map.getSource('source-id').tiles = [ `http://some.url/{z}/{x}/{y}.pbf?dt=${Date.now()}` ]

// Remove the tiles for a particular source
map.style.sourceCaches['electrical-grid'].clearTiles()

// Load the new tiles for the current viewport (map.transform -> viewport)
map.style.sourceCaches['electrical-grid'].update(map.transform)

// Force a repaint, so that the map will be repainted without you having to touch the map
map.triggerRepaint()
```

**Comment by imran-5** [comment]
I have found an issue while using this solution. It says the id not found. I figure out the solution.
```
// Set the tile url to a cache-busting url (to circumvent browser caching behaviour):
map.getSource('source-id').tiles = [ `http://some.url/{z}/{x}/{y}.pbf?dt=${Date.now()}` ]

// Remove the tiles for a particular source
map.style.sourceCaches['source-id'].clearTiles()

// Load the new tiles for the current viewport (map.transform -> viewport)
map.style.sourceCaches['source-id'].update(map.transform)

// Force a repaint, so that the map will be repainted without you having to touch the map
map.triggerRepaint()
```
I have figure out a solution. instead of sourceCache try _sourceCashe function and type 'other' before your id.

```
map.style._sourceCaches['other:wms-source'].clearTiles();
map.style._sourceCaches['other:wms-source'].update(map.transform)
```

**Comment by kamil-sienkiewicz-asi** [comment]
@mourner Any reason why this isn't public API/configurable so users won't have to access private fields to refresh tile data?

**Comment by stepankuzmin** [comment]
Hi @kamil-sienkiewicz-asi,

There is a public API for the Raster and Vector sources for that:

* https://docs.mapbox.com/mapbox-gl-js/api/sources/#rastertilesource#settiles
* https://docs.mapbox.com/mapbox-gl-js/api/sources/#rastertilesource#seturl
* https://docs.mapbox.com/mapbox-gl-js/api/sources/#vectortilesource#settiles
* https://docs.mapbox.com/mapbox-gl-js/api/sources/#vectortilesource#seturl

**Comment by kamil-sienkiewicz-asi** [comment]
Hey @stepankuzmin , thanks for the quick answer. Yes, you are correct, I didn't spot these as typescript definitions did not have such methods as you could see here -> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L1582 

Will create PR to DefinitelyTyped soon 😅
