### ISSUE TITLE
Example for moving around on map with game-like controls

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#2943]
This demo is popular: https://www.mapbox.com/bites/00279/

I have gotten requests for an example that uses left, right, up, down ~~arrow keys~~ buttons for navigating a map. Here's the code @tristen and I wrote for these interactions: https://gist.github.com/samanpwbb/57a44206652ddc73887b11a392bf6c76

**Comment by lucaswoj** [comment]
We do have the ["Move symbol with the keyboard"](https://www.mapbox.com/mapbox-gl-js/example/rotating-controllable-marker/) example. What do you think about improving that example with your interaction handling code instead of creating a new example?

**Comment by samanpwbb** [comment]
> What do you think about improving that example with your interaction handling code instead of creating a new example?

The two examples are pretty different. My demo has UI controls that move the map position (the bat is just an absolute positioned div) and relies on on-screen buttons. The existing demo moves a geojson symbol layer with setData and relies on keyboard presses.

I see value in both examples. Adding keyboard controls to the existing demo that work the way the bat demo runs the risk of over-complicating the existing demo.

**Comment by colleenmcginnis** [comment]
See #3178 and the live example [here](https://www.mapbox.com/mapbox-gl-js/example/game-controls/)!

**Comment by lyzidiamond** [comment]
Looks like this was closed in #3178!
