### ISSUE TITLE
Fix bug preventing "queryRenderedFeatures" from being called with no arguments

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#2969]
The GL JS API documentation correctly lists this method's signature as 

```js
queryRenderedFeatures([region], [parameters])
```

... however calling `map.queryRenderedFeatures()` produces an error unless a parameters object is passed `map.queryRenderedFeatures({})`. 

This bug was causing some of our benchmark scripts to crash and was fixed in https://github.com/mapbox/mapbox-gl-js/pull/2950 ([exact spot in the diff](https://github.com/mapbox/mapbox-gl-js/pull/2950/files#diff-63abd99e8332ce21c1323063948b72f0R39))

Relevant source [here](http://github.com/mapbox/mapbox-gl-js/blob/f287983ecf88ee4df6ad0ee16144de02d93477ae/js/ui/map.js#L516-L517)

**Comment by mapsam** [comment]
Happy to grab this!

**Comment by lucaswoj** [comment]
This bug breaks the http://127.0.0.1:4000/mapbox-gl-js/example/queryrenderedfeatures/ example on `master`, blocking the release

**Comment by lucaswoj** [comment]
(good thing @mapsam has a PR ready!!!)

**Comment by mapsam** [comment]
\o/ thanks for chugging through this one @lucaswoj!
