### ISSUE TITLE
Add custom icons with Markers example seems buggy

### ISSUE THREAD

**Issue by lcapel** [mapbox/mapbox-gl-js#2974]
Hi,

I was actually trying to raise another issue when I noticed that the ["Add custom icons with Markers"](https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/) example seems a bit buggy, on your site the output looks like this

<img width="579" alt="screen shot 2016-08-10 at 16 54 05" src="https://cloud.githubusercontent.com/assets/870335/17560850/81620a28-5f1b-11e6-863d-848c224bcc92.png">

But if I paste the code on J[SBin](http://jsbin.com/xatijid/1/edit?html,output) or JSFiddle then it looks like this

<img width="605" alt="screen shot 2016-08-10 at 16 53 54" src="https://cloud.githubusercontent.com/assets/870335/17560879/9e56fd5a-5f1b-11e6-90c1-dc8158240241.png">

I'm using the latest version, normally pasting examples on on JSBin just works.

**Comment by tristen** [comment]
Thanks for the catch @lcapel. Looks like we're missing some css rules here.

**Comment by lucaswoj** [comment]
Fixed in #2976 😄
