### ISSUE TITLE
At some zoom levels, holes in geojson features are rendered wrong

### ISSUE THREAD

**Issue by kretz** [mapbox/mapbox-gl-js#2975]
**mapbox-gl-js version**: 0.21.0

### Steps to Trigger Behavior

I use geojson data like below, which is one feauture consiting of a polygon with a hole. I render it in mapbox.

```
{
  "type": "FeatureCollection",
  "features": [{
    "type": "Feature",
    "properties": {
      "type": "area"
    },
    "geometry": {
      "type": "Polygon",
      "coordinates": [
        [
          [0.00010,0.00010],
          [0.00010,0.00004],
          [0.00008,0.00004],
          [0.00009,0.00003],
          [0.00007,0.00003],
          [0.00008,0.00002],
          [0.00000,0.00002],
          [0.00010,0.00010]
        ],
        [
          [0.00006,0.00004],
          [0.00007,0.00003],
          [0.00009,0.00003],
          [0.00008,0.00004],
          [0.00006,0.00004]
        ]
      ]
    }
  }]
}
```

### Expected Behavior

The hole should always be rendered correctly, like the image below. This is zoom level 18.

<img width="788" alt="screenshot 2016-08-10 17 48 41" src="https://cloud.githubusercontent.com/assets/154819/17560542/c161f5be-5f22-11e6-976e-a1e67f7d0d2a.png">

### Actual Behavior

At certain zoom levels, the hole is not like to should. This is zoom level 17.

<img width="782" alt="screenshot 2016-08-10 17 48 27" src="https://cloud.githubusercontent.com/assets/154819/17560548/c76d0048-5f22-11e6-9221-88b2970f618f.png">

**Comment by lucaswoj** [comment]
It looks to me as though you are trying to render a [complex polygon](https://en.wikipedia.org/wiki/Complex_polygon#Computer_graphics). Mapbox GL JS's behavior in this case is undefined.

Can you confirm @mourner @mapsam?

**Comment by kretz** [comment]
Yes, it is a complex polygon. i.e. is has holes. I was expecting it to work since it is supported in the GeoJSON spec, http://geojson.org/geojson-spec.html#id4. 

Also, other geojson rendering tools I have tried does this successfully; Openlayers, Leaflet. There are even bugs that have been fixed on mapbox-gl-js that suppor holes; https://github.com/mapbox/mapbox-gl-js/issues/1202.

I stumbled upon this bug just because we are rendering at this precis zoom level.

**Comment by lucaswoj** [comment]
The problem isn't the holes -- we support those! The problem seems to be that the that the 2nd ring is outside of the 1st ring. The 1st ring defines the outer perimeter of the polygon and subsequent rings define holes in the polygon, subject to the [even-odd rule](https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule). 

It is unfortunate that other map renderers, including Leaflet, differ in behaviour in this case.

**Comment by kretz** [comment]
I'm not sure what the definition is, but the hole in the example shares 3 coordinates with the outer perimeter. I would have guessed that was inside?

**Comment by lucaswoj** [comment]
@kretz Is your desired effect a solid polygon and a diamond-shaped stroke?

**Comment by kretz** [comment]
The reason for the weirdly shaped polygon is that this was the only way I could get the effect. It is a simplified version of a more complex shape of a building.

**Comment by lucaswoj** [comment]
Would it be accurate to say that you want the 2nd ring to "subtract" from the 1st ring?

**Comment by kretz** [comment]
Yep, exactly.

**Comment by lucaswoj** [comment]
Unfortunately the spec we are working from doesn't allow interior rings to be coincident with the exterior ring. You need to do this subtraction operation outside of GL JS https://www.mapbox.com/vector-tiles/specification/#winding-order

**Comment by kretz** [comment]
Alright, thanks for taking the time to explain it!
