### ISSUE TITLE
Restore worker-side "redo placement" 

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#2983]
@lucaswoj I noticed some console errors when rotating the map, and I think they are being caused because in #2667 we lost [this code](https://github.com/mapbox/mapbox-gl-js/blob/302aadd4d7a2fbd07356bee9457da934b497c7c4/js/source/worker.js#L147-L161).  I _think_ that restoring this is probably as simple as copying this code into the currently-missing `VectorTileWorkerSource#redoPlacement` method, but since I have absolutely no idea what redoPlacement is actually doing, could you confirm that that makes sense?

**mapbox-gl-js version**: `master`

### Steps to Trigger Behavior

 1. Open debug page
 2. Open dev tools
 3. Rotate the map

### Expected Behavior

Clean console.

### Actual Behavior

Console errors:
`Uncaught TypeError: this.workerSources[type].redoPlacement is not a function`

**Comment by lucaswoj** [comment]
Bug confirmed. This is a release blocker.

**Comment by lucaswoj** [comment]
We will need to create a test-suite regression test for this bug

**Comment by anandthakker** [comment]
@lucaswoj I can take this on if you can help me understand: how does this bug present itself to the user? (So that I can (a) know what to look for when fixing, and (b) possibly include an appropriate unit-test)

**Comment by anandthakker** [comment]
(By "present itself to the user" I mean on the actual rendered map; I don't want to "solve" the console errors but retain some rendering problem...)

**Comment by lucaswoj** [comment]
I've got this under control 👍
