### ISSUE TITLE
Add documentation on cluster behavior + syntax

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#2985]
Right now the only things I could find on our clustering functionality were in the [examples](https://www.mapbox.com/mapbox-gl-js/example/cluster/) and in the style reference for [GeoJSONSource](https://www.mapbox.com/mapbox-gl-js/api/#GeoJSONSource). 

We should document things like the `point_count` property more explicitly. 

Also, I was trying to figure out if there's a way to set a minimum for the number of points in a clusterRadius that should be grouped in a cluster (i.e. if you only want clusters for areas w more than 3 points) and I did not have time to fully check. 

@mourner do you have any thoughts?

**Comment by mourner** [comment]
@mollymerp I don't think we need the `minClusterPoints` option, but it would be possible to add on the `supercluster` library level. We should definitely improve docs about clustering.

**Comment by YunjieLi** [comment]
I also find the `point_count` a little cryptic, like for a single point in a cluster=true source, its point_count is null instead of 0 (like if I need to filter them out).

**Comment by YunjieLi** [comment]
Peter and I just ran into an issue about map mouse event + queryRenderedFeatures. 
The highlight layer (shows on queryRenderedFeatures return a length>0) keeps flickering when as the mouse moves close. The query result is logged in console. 
When the highlight layer is set to invisible, the query result stabilizes though. 

Demo is [here](https://www.mapbox.com/labs/movoto/index1.html)
![image](https://cloud.githubusercontent.com/assets/12749701/17640229/73ee6a9e-60b0-11e6-8978-6ea33cc95e76.png)
$1.05M is the layer to query and New is the highlight layer.

@mollymerp @peterqliu @lucaswoj

**Comment by stevage** [comment]
So, what properties get generated exactly? `cluster` (boolean), `point_count` (integer), any others? 

(Are there any other examples of properties generated by Mapbox-G? I wonder if they should be `$cluster`, `$point_count` etc to reduce the chance of namespace collisions...)

**Comment by tuukka** [comment]
I'm seeing `cluster`, `cluster_id`, `point_count`, `point_count_abbreviated`.

**Comment by mourner** [comment]
Fixed in #7000
