### ISSUE TITLE
Markers API not behaving constistently

### ISSUE THREAD

**Issue by lcapel** [mapbox/mapbox-gl-js#2987]
Hi,

I have a bug with the latest version of Mapbox GL where markers sometimes do not appear on the map, I made a quick example to demonstrate the issue:

http://jsbin.com/vofixac/edit?html,console,output

In the example I'm laying down markers as well as points because I originally tried to raise a slightly different issue where the marker positioning would slightly move towards the right edge of the screen as I kept adding more of them (although logging the coordinates showed that they were the same as the GeoJSON) but I'm failing to reproduce this 😕 

This is a gif of the second issue, not too helpful I know, as soon as I'll manage to reproduce this properly I'll raise that as well, but I thought you may be interested (also not how the 2nd marker just doesn't appear).

![markers](https://cloud.githubusercontent.com/assets/870335/17586159/d4360d0c-5fb7-11e6-8d99-5b475f47d6d7.gif)

Thank you and sorry for the confusing issue.

**Comment by lucaswoj** [comment]
Markers do not wrap across the dateline by default. See #2780 for more information and a proposed feature to add this functionality.
