### ISSUE TITLE
queryRenderedFeatures returns incorrect numbers

### ISSUE THREAD

**Issue by Jimbo145** [mapbox/mapbox-gl-js#2988]
**mapbox-gl-js version**: 0.21.0

### Steps to Trigger Behavior
Numbers in geojson features seem to overflow when queried via queryRenderedFeatures or querySourceFeatures.

https://jsfiddle.net/Jimbo145/osgrne7y/2/

### Expected Behavior

Numbers that are in the object returned from queryRenderedFeatures should match the input source.

### Actual Behavior

Numbers that are returned from queryRenderedFeatures become random if they are large enough. Decimal numbers have randomly appended digits

**Comment by mourner** [comment]
Confirmed, this is a bug in `vt-pbf` value encoding cc @anandthakker. Submitting a PR shortly.

**Comment by mourner** [comment]
Should be fixed with `vt-pbf` 2.1.2 (which is already in the version range so no need to update in mapbox-gl-js package.json).
