### ISSUE TITLE
Long delay (~2s) between map style loading and vector tiles being requested

### ISSUE THREAD

**Issue by ekelleyv** [mapbox/mapbox-gl-js#2991]
**mapbox-gl-js version**: v0.21.0

**browsers**: Latest Firefox + Chrome on Mac
### Steps to Trigger Behavior
- Request any vector map (such as on https://www.mapbox.com/mapbox-gl-js/examples/) on Chrome or Firefox
### Expected Behavior
- Network requests for vector tiles start very shortly (on the order of milliseconds?) after style sheet is loaded and parsed
### Actual Behavior
- There is a 1-2s delay before the vector map tiles are even requested. Then the tiles load and render on the map correctly.

Here is a screenshot of the chrome developer console (https://www.mapbox.com/mapbox-gl-js/examples/):
![image](https://cloud.githubusercontent.com/assets/1816394/17607840/75417be4-5ff6-11e6-834d-ef40ae24c8c8.png)

Interestingly this does _not_ affect raster sources on any browser (https://www.mapbox.com/mapbox-gl-js/example/map-tiles/):
![image](https://cloud.githubusercontent.com/assets/1816394/17607865/ab52118a-5ff6-11e6-9762-d7c993e0056c.png)

This also occurs on Firefox:
![image](https://cloud.githubusercontent.com/assets/1816394/17608101/21ec495e-5ff8-11e6-9071-afbc2ba46bc6.png)

Even more interestingly, this does _not_ happen on safari:
![image](https://cloud.githubusercontent.com/assets/1816394/17608062/d87da57e-5ff7-11e6-8d73-76e71835f1e7.png)

So, we have maps that have both vector and raster sources where the raster tiles appear seconds before their vector counterparts.
### Best guess at what is happening

Purely speculation, but this seems the vector renderers (shaders? webworkers?) are being instantiated in such a way that blocks the network request for vector tiles. It seems like the vector tile requests could be triggered upon parsing the style sheet (like the glyphs and raster tiles are), so by the time the renderer is fully ready, the tiles are all available and render immediately, instead of drawing as the network requests return.

As to why this does not occur on safari?  `¯\_(ツ)_/¯`

**Comment by ekelleyv** [comment]
Here is a video of the delay on chrome:
https://cl.ly/3n3i1n2c030P

**Comment by ekelleyv** [comment]
As I look into this, it seems to be related to the overhead of bringing up the workers and the time spent in `set layers`. That is the key difference compared to raster tiles, as raster tiles do not instantiate workers/style layers before starting the network request.

**Comment by EMTurano** [comment]
I'm experiencing the same thing, but if you look at your Network tab, you'll see the resources that come from mapbox's domain are what's delaying the load.

**Comment by ekelleyv** [comment]
@EMTurano that is not what I am seeing. There is a "gap" in network requests. Also, if this were just a max connections issue, it would affect both raster and vector tiles. However, the time seems to be spent in the worker/layer instantiation rather than any network activity.

Based on my logging the network requests are not even being attempted until after the delay, whereas if it were a network bottleneck you would expect to see the tiles in the "Queueing" state for the duration of the delay.

**Comment by jfirebaugh** [comment]
Can you please reproduce the issue in Chrome with the network inspector open, and then right-click of the list of network requests and "Save as HAR with Content", and post a link? Thanks!

**Comment by ekelleyv** [comment]
Certainly:
https://cl.ly/0U2S3O0k2i1k

I think https://github.com/mapbox/mapbox-gl-js/issues/3153 and referenced issues describe exactly what I was seeing when I tried profiling things. @jfirebaugh think we should close this issue?

**Comment by mourner** [comment]
Let's close in favor of #3153.
