### ISSUE TITLE
Marker icon doesn't show in map

### ISSUE THREAD

**Issue by christiancannata** [mapbox/mapbox-gl-js#2994]
v0.21.0:

Hi guys,
I don't know why if I put a geojson with icon "marker", in map print a point, this is the only sprite that not works.
This is the code and the result in maps:
<img width="1385" alt="screenshot 2016-08-12 16 34 16" src="https://cloud.githubusercontent.com/assets/4604959/17625854/ef652a92-60aa-11e6-9e74-1c95047ffe90.png">

**Comment by lucaswoj** [comment]
The small circle above your label is the intended `marker-15` icon for some of our styles. If there is a particular marker icon that you would like to use, please follow [this guide](https://www.mapbox.com/help/custom-markers/) to add a custom icon or use the `Marker` class.

**Comment by YajanaRao** [comment]
I am getting error as 
` Image "marker-15" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.`
