### ISSUE TITLE
Water polygon disappearing at z14

### ISSUE THREAD

**Issue by bhousel** [mapbox/mapbox-gl-js#3000]
mapbox-gl-js version:  **v0.22.0**
mapbox style version:  **Mapbox streets v9**

Why is the Jacqueline Kennedy Onassis Reservoir disappearing at z14?
This happens in `master` but also on on our live examples pages:

![reservoir_disappears](https://cloud.githubusercontent.com/assets/38784/17649718/8881cdb6-6209-11e6-8407-4e588be61649.gif)

**Comment by mollymerp** [comment]
It appears that it is being covered by the layers `road-pedestrian-polygon-fill` and `road-pedestrian-polygon-pattern` at z14. I don't think this is a gl bug.

cc @ajashton is this intentional or a mistake in the data?

**Comment by mollymerp** [comment]
_mapbox streets_
![gl-js-bug2](https://cloud.githubusercontent.com/assets/2425307/17675303/073d4fd4-62de-11e6-95da-43ae58e71cfe.gif)

_mapbox streets with layers mentioned above at `visibility: none`_
![gl-js-bug](https://cloud.githubusercontent.com/assets/2425307/17675322/186c43d2-62de-11e6-82bc-5bdd56255289.gif)

**Comment by mollymerp** [comment]
closing here in favor of https://github.com/mapbox/mapbox-streets-source/issues/579
