### ISSUE TITLE
No way to set iconAnchor

### ISSUE THREAD

**Issue by soupman99** [mapbox/mapbox-gl-js#3002]
As far as I can tell there's no current way to change the anchor point of an icon.

http://jsbin.com/digeyavero/edit?html,output

**Comment by tmcw** [comment]
Hi Justin,

The equivalent of iconAnchor can be set with normal margin styles: here's an example: http://jsbin.com/dosaxatero/1/edit?html,output

Hope that helps!

- Tom

Refs #2900

**Comment by soupman99** [comment]
Like a boss!
