### ISSUE TITLE
Accept custom source types before or during Map creation

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#3004]
Currently, the only way to add a custom source type in client code is `Ma#addSourceType`.  This ends up being awkward, because (together with the issue raised in #3003) it means that you cannot construct a map instance with a stylesheet JSON, but rather have to use `Map#addSource` and `Map#addLayer`. (If #3003 is fixed, then `Map#setStyle` would also be an option, but this is still less ideal than `new Map({ style: stylesheet, ... })`.

Proposed fixes (I am proposing both, although either one alone would suffice):
1. Accept a `sourceTypePlugins: { /* maps source type name to the custom source type */ }` in the `Map` constructor, and handle it before creating the style. (This may mean moving where the Dispatcher is created, but I think it's not too bad.)
2. Move `Map#addSourceType` to something like `mapboxgl.Source.addSourceType`. <del>(This would require a deeper change, wherein when a new Worker is created, we check whether any custom sources require registering a WorkerSource.)</del>  Because adding a custom source type may require communication with the workers, this raises a complication: (i) when a new map is created, it must check for existing source types that have workerSourceURLs and register those with its workers; (ii) if a source type is added _after_ some map instances are created, how do we tell all of the instances to register the new worker source?

**Comment by anandthakker** [comment]
Updated ^

**Comment by lucaswoj** [comment]
Closing in favor of https://github.com/mapbox/mapbox-gl-js/issues/3323

**Comment by lucaswoj** [comment]
Let's punt on both this and #3323 right now.
