### ISSUE TITLE
Fix bug causing text distortion for some values of text-rotate" and "text-offset"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3005]
cc @danpat @nickidlugash @mourner 

**mapbox-gl-js version**: v0.22.0

### Minimal test Case

http://jsbin.com/zozejekeki/1/edit?html,output

```js
new mapboxgl.Map({
    container: 'map',
    style: {
        "version": 8,
        "glyphs": "mapbox://fonts/mapbox/{fontstack}/{range}.pbf",
        "sources": {
            turns: {
                "type": "geojson",
                "data": {
                  "type": "FeatureCollection",
                  "features": [{"type":"Feature","geometry":{"type":"Point","coordinates":[-122.445073127747,37.7995777578025]}}]
                }
            }
        },
        "layers": [{
            "id": "text",
            "type": "symbol",
            "source": "turns",
            "layout": {
                "text-field": "test",
                "text-offset": [19,19],
                "text-rotate": 4
            }
        }]
    },
    center: [-122.4452, 37.7949],
    zoom: 12
});
```

### Expected Behavior

The text is rendered with correct proportions.

<img width="93" alt="screen shot 2016-08-15 at 11 56 37 am" src="https://cloud.githubusercontent.com/assets/281306/17675628/60a11c80-62df-11e6-98c8-9c80682f64af.png">

### Actual Behavior

The text is stretched.

<img width="303" alt="screen shot 2016-08-15 at 11 55 52 am" src="https://cloud.githubusercontent.com/assets/281306/17675633/653b2e3e-62df-11e6-9d96-885ea472761b.png">

**Comment by lucaswoj** [comment]
I suspect this may be caused by an overflowing value somewhere. A text offset of `[19, 19]` will not trigger the bug. If this is the case and is intentional we should emit a style validation error for out-of-range values.

**Comment by danpat** [comment]
Observations:

Changing the Y offset:

 - `[19,20]` breaks
 - `[19,21]` to `[19,62]` looks OK
 - `[19,63]` breaks
 - `[19,64]` looks OK

Changing the X offset:

  - `[19,19]` to `[21,19]` works
  - `[22,19]` to `[41,19]` render badly

Additionally, it looks like the actual offsets might be really wonky.  While stepping through the offset changes above, the label position between X=19 and X=42 is a lot more than 20 pixels.

**Comment by mourner** [comment]
This seems to be a bug in the line wrapping routine. If you disable it, the test works as expected. Investigating.

**Comment by mourner** [comment]
Disregard the above, it's really some kind of overflow.  In practice you won't use the values like 19 though since these are in ems, not pixels. In the code, one em is 24 pixels.

**Comment by mourner** [comment]
-> https://github.com/mapbox/mapbox-gl-style-spec/issues/481
