### ISSUE TITLE
GPS marker functionality

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#3006]
I read that the GPS marker functionality has been implemented a year ago into mapbox by @bleege and @incanus 
https://github.com/mapbox/mapbox-gl-native/issues/756

Is there an example out there how to use it width mapbox-gl-js ? 
I don't find anything about GPS functionality in the API documentation

**Comment by lucaswoj** [comment]
This has been implemented in GL JS as of https://github.com/mapbox/mapbox-gl-js/pull/2283. See the [`Geolocate` control documentation](https://www.mapbox.com/mapbox-gl-js/api/#Geolocate) for more information.
