### ISSUE TITLE
Geolocate question

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#3008]
When I add the Geolocate control to my map and click on it, the map is centered and zoomed in to my current location. 

I could than add a marker to the map (although I expected a marker to be shown on my current position)
When I then walk (or ride) I would like the marker to follow me on the map... Is this possible ? or does I have to implement it myself ?

**Comment by peterqliu** [comment]
@uhuru-be you'd implement this yourself. The easiest way I imagine for this, is to put a static HTML div atop the map to represent the marker. Then, you periodically poll your current location and move the map to that position.

**Comment by achalnexus** [comment]
I have only Geolocate autocomplete GL-Mapbox  use. Load particular country wise data load. What i to do.?

**Comment by lucaswoj** [comment]
I can't see us adding a marker at the user's position. Most desktop web browsers do not have GPS and cannot determine their position accurately enough for this feature. You're welcome to add this feature yourself using `Marker`s or `symbol`s.

**Comment by andrewharvey** [comment]
See also #4479
