### ISSUE TITLE
Geolocate autocomplete GL-Mapbox use

### ISSUE THREAD

**Issue by achalnexus** [mapbox/mapbox-gl-js#3011]
I have only Geolocate autocomplete GL-Mapbox use. Load particular country wise data load.
What i to do.?
Particular park wise near place search..?

**Comment by mourner** [comment]
Please provide sufficient details for us to be able to help you, including Mapbox GL JS version, description of the expected and actual behavior, and steps to trigger the issue.

**Comment by achalnexus** [comment]
i want to Geolocate autocomplete only with particular country wise data load. For eg i have attach one image. i have using "v0.21.0/mapbox-gl.css" version file.
![screenshot_2](https://cloud.githubusercontent.com/assets/20719973/17723916/879e4826-645b-11e6-8da3-ff182a3296af.png)

**Comment by lucaswoj** [comment]
@achalnexus Looks like you have some questions about the [Mapbox Geocoding API](https://www.mapbox.com/geocoding/) (a separate Mapbox product from GL JS). I think you'll find the answers you're looking for in the [Geocoding API documentation](https://www.mapbox.com/api-documentation/#request-format). If you still have questions, please [reach out to the Mapbox support team](https://www.mapbox.com/contact/) or ask on [StackOverflow](http://stackoverflow.com/questions/tagged/mapbox).

**Comment by achalnexus** [comment]
I have load only "CALIFORNIA" related park in Geolocate autocomplete. I have attached in code in docx file and all code copy and paste in notepad file and save as html after run this code.
[geocode.docx](https://github.com/mapbox/mapbox-gl-js/files/427007/geocode.docx)
