### ISSUE TITLE
Docu on load event is vague / How to ensure code is run after the map is ready?

### ISSUE THREAD

**Issue by urbanhop** [mapbox/mapbox-gl-js#3012]
The docu on the **load** event is vague. Considering the code in the examples:
```

var map = new mapboxgl.Map({
    container: 'map',
});

// map could be loaded here already. (unlikely but possible?)

map.on('load', function () {
   console.log("the map has been loaded. do many things now and here.");
})
```

It apparently could happen that the map is fired before the load event is attached. Why is this usage ok ? Is it ok at all? How would I ensure code is run after the map is ready?

**Comment by mourner** [comment]
The `load` event will always fire in another frame, so the pattern above is safe.

**Comment by urbanhop** [comment]
Would you please briefly teach me why?

**Comment by urbanhop** [comment]
I see that load is fired of an animation frame. But isn't this animation frame requested inside the map constructor? And what ensures that the load-event handler running on another frame does not execute before map.on() runs?

**Comment by mourner** [comment]
@urbanhop it's the way JavaScript works in browsers. Anything in a single JS file that is included on a page will get executed in a single frame while blocking the browser.

**Comment by urbanhop** [comment]
Thx! JS is still a safe haven regarding concurrency.
