### ISSUE TITLE
Docu on layer type is vague.

### ISSUE THREAD

**Issue by urbanhop** [mapbox/mapbox-gl-js#3013]
> type
> Optional enum. One of fill, line, symbol, circle, raster, background.
> 
> Rendering type of this layer.

Hmmm, that does not say much without explaining the types. I can make sense of fill and line but symbol? circle? background?

Actually, I would like to render a geojson layer, with a geojson object that holds polygons and points, so neither a fill-only nore a point-only layer can draw the geojson. Is it possible to have a geojson layer that renders a more complex geojson ?

**Comment by tmcw** [comment]
Hi,

Thanks for the questions!

Moving spec improvement concern to that repo: https://github.com/mapbox/mapbox-gl-style-spec/issues/479

> Actually, I would like to render a geojson layer, with a geojson object that holds polygons and points, so neither a fill-only nore a point-only layer can draw the geojson. Is it possible to have a geojson layer that renders a more complex geojson ?

Layers in Mapbox GL JS render a single kind of geometry. You can create a layer for each type of geometry you want to render (a symbol/circle layer and a fill layer) and have those pull only from the points in your file and the polygons in your file. That way you can deeply customize the options for each specific type of rendering.

- Tom

**Comment by urbanhop** [comment]
Thank you for your helpful reply. I think a geojson layer should accept any valid geojson object, if not it should at least be clearly mentioned in the docs. because then it is just a polyon or a line layer that accepts geojson-formatted input. Just my oppinion.

Anyway, if adding such functionality is all the work you leave to me, I am fine. Thx for this and other great open source tools.

**Comment by tmcw** [comment]
> Thank you for your helpful reply. I think a 'geojson' layer should accept any valid geojson object, if not it should at least be clearly mentioned in the docs.

GeoJSON layers can accept multiple geometry types - we support the full range of GeoJSON constructs. The Mapbox GL rendering model is that the same data can be rendered multiple ways and multiple times: a polygon in geojson can yield a fill layer, a stroke layer, and a text layer, all from the same datasource. Creating a polygon + line layer from the same geojson source is the same as what you're proposing, but it allows you to control _which_ symbolizations of the data are chosen.
