### ISSUE TITLE
Unbearable debug page loading times

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#3014]
**mapbox-gl-js version**: v0.22

### Steps to Trigger Behavior

 1. `npm start`
 2. load `http://localhost:9966/mapbox-gl.js`

### Expected Behavior

The script loads in ~2-3s (this is how long `npm run build-dev` takes)

### Actual Behavior

The script loads in up to 20s (every time).

![image](https://cloud.githubusercontent.com/assets/25395/17708251/d916637e-63ec-11e6-9da7-81e42fa505e1.png)

This makes the development process really painful — having to wait half a minute after every code change. 

Not sure what the cause is — my bet would be a problem with https://github.com/ForbesLindesay/browserify-middleware, which hasn't been updated since last year (and with the author not responding to PRs). Are there any alternatives? cc @lucaswoj

**Comment by mourner** [comment]
I identified `browserify-middleware` as the source of the problem. It takes 2-3s to generate the response but then it spends 17s sending it. Investigating further.

**Comment by lucaswoj** [comment]
I'm not aware of any alternatives. We might be able to rig something up with [watchify](https://github.com/substack/watchify) outside of `server.js`.

**Comment by mourner** [comment]
Found the cause. Here's what happens:

- `browserify-middleware` is set to precompile all bundles regardless of the `precompile` option (in fact it was removed: https://github.com/ForbesLindesay/browserify-middleware/issues/78, the author just didn't update the docs)
- when you change any file in `mapbox-gl-js` source and then request `mapbox-gl.js`, it also starts precompiling `bench/index.js` which in turn uses `mapbox-gl`, but additionally spends **a ton of time** on Babel, React and all that bloat I warned about before
- since the server is one-threaded and the bundles start compiling at the same time, an expensive bench build ends up fully blocking `mapbox-gl.js` response while it builds

I'm strongly in favor of ditching `browserify-middleware` and going back to a `watchify`-based build system. And I'd love for us to drop react/babel dependencies as well of course...

**Comment by mourner** [comment]
Here's what I'm thinking for next actions:

- get rid of `server.js` completely in favor of simple NPM scripts with `watchify` and `st`
- make `npm start` serve debug pages
- make `npm run start-bench` download benchmark data and serve benchmarks (independently from debug pages)
