### ISSUE TITLE
Allow clusters to be by rendered features only

### ISSUE THREAD

**Issue by steinbachr** [mapbox/mapbox-gl-js#3016]
Consider the case where we're clustering the prices of homes on a map and as the value of the cluster, we want to show the minprice of the homes in the cluster. The actual display of the minprice as the cluster value isn't a requirement for this issue, I just wanted to give a bump to #2412 because it's vital to our use case ;). 

Anyways, say we then want to apply a filter to only show homes with a price of >$200,000. At a non-cluster layer level, this works just fine with the application of a `filter`. However, for cluster layers, the `point_count` includes all features, not just those rendered. I propose an extension to the source API such that the following be a valid declaration:

```
"type": "geojson",
"cluster": true,
"clusterTarget": 'rendered' // <-- where this could be either 'rendered' or 'source' (defaulting to source)
"clusterRadius": 50
"clusterMaxZoom": 5,
"data": ..
```

OR, alternatively:

```
"type": "geojson",
"cluster": true,
"clusterRendered": true, // <-- defaulting to false
"clusterRadius": 50
"clusterMaxZoom": 5,
"data": ..
```

**Comment by mourner** [comment]
> However, for cluster layers, the point_count includes all features, not just those rendered.

I have a hard time understanding what you mean by this. Can you describe in more detail what would a "rendered" option do in practice?

**Comment by steinbachr** [comment]
yeah, I realize that wasn't completely clear after having written it. 

Going back to our homes example, say we originally start out with a cluster of 10 homes in a given area. The ```point_count``` property of that cluster would then be 10. Then, say we want to apply a filter to the map, only show homes that have a price less than $200,000. After applying this filter, assume that their are only 5 homes in the original cluster of 10 which meet this criteria. I would expect the new ```point_count``` to display this value (5) rather than the un-filtered value (10)

**Comment by steinbachr** [comment]
Of course, one way to do this is to create a new source representing the currently filtered original source and making this the clustered source. Then, updating that source with new data from the original source whenever a filter is applied, but since there's already a mechanism for filtering at the layer level, that just feels dirtier to me for some reason.

**Comment by mourner** [comment]
The behavior you describe is technically not possible — the filter you set applies to the vector tiles with clusters generated from the source data, not to the source data itself. Additionally, you have to fully rerun clustering on all data because you have a different set of points after a filter, so they will be grouped differently. So the second approach in the comment above is the right one.
