### ISSUE TITLE
"Drag a point" sample does not work on Android or iOS devices.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#3017]
**mapbox-gl-js version**:v0.22.0
### Steps to Trigger Behavior

The following sample does not work on either iOS or Android devices.

https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/

**Comment by 1ec5** [comment]
I’m guessing that’s because `mouseDown()` is guarded by `isCursorOverPoint`, which is only set based on a `mousemove` event that would never get fired on a touchscreen.

**Comment by kristfal** [comment]
This example also needs #2419 to work on mobile devices.
