### ISSUE TITLE
replace symbol/marker when clicked on it

### ISSUE THREAD

**Issue by uhuru-be** [mapbox/mapbox-gl-js#3021]
Hello,
I have a map where symbols ("markers") are added to a symbol layer using a geojson source.  When moving over a marker (or clicking on it) a little popup is shown with a title, photo and description.

Now, I would like to replace the symbol when user clicks on it, so that the user sees instantly which symbols he has already checked..  What is the best way to accomplish this ?

**Comment by mourner** [comment]
Currently the only way to hide the symbol in this case is to remove it from the GeoJSON source and call `setData` again. We're investigating a way to accomplish this more efficiently, captured in #200.

**Comment by mourner** [comment]
Alternative you can try using the new DOM markers functionality (`mapboxgl.Marker`).

**Comment by uhuru-be** [comment]
It's not very clear to me when to use the symbol layer functionality and when to use the mapboxgl.Marker functionality.  What are the odds and benefits of each method ?

It would be nice to be able to change the symbol of a GeoJSON point in the future.

**Comment by mourner** [comment]
@uhuru-be general rule of thumb is to use a symbol layer when you have _tons_ of points that don't change often, and to use HTML markers when you have a few points that are animated/changed frequently or need the rich HTML styling.

**Comment by uhuru-be** [comment]
Thanks. Then I guess I stick to the symbol layer because some maps have hundreds of symbols and wait for the new feature.

**Comment by mourner** [comment]
@uhuru-be DOM markers are OK for 100-200 markers. It becomes a performance problem when it's 500 or more.
