### ISSUE TITLE
fitBounds throws exception "Failed to invert matrix" with large padding value

### ISSUE THREAD

**Issue by radubilei** [mapbox/mapbox-gl-js#3027]
**mapbox-gl-js version**: 0.22.0

### Steps to Trigger Behavior

 1. Visit http://jsbin.com/cenuquyapa/edit?html,output

### Expected Behavior
Map should zoom to the requested location.
### Actual Behavior
An exception is thrown and Mapbox dies.

**Comment by lucaswoj** [comment]
Duplicate of #1776
