### ISSUE TITLE
Text color clusters

### ISSUE THREAD

**Issue by martinrisseeuw** [mapbox/mapbox-gl-js#3028]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Open the store locator at [http://martinr.nl/lab/locator_v3/](http://martinr.nl/lab/locator_v3/)

### Expected Behavior

We would like to style the text color of the clusters. I saw in the documentation that text-color data-driven styling is not supported yet. I guess my question mostly is this in the pipeline? Or do you have a suggestion on how to change the text color.

### Actual Behavior

Black text instead of white.

**Comment by mollymerp** [comment]
Hi @martinrisseeuw,
You actually don't need data-driven styling to change the text color on your clusters. You have to add the following to your `cluster-count` layer:

```js
"paint": {
    "text-color":"white"
}
```
