### ISSUE TITLE
interaction for labels

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#303]
`map.featuresAt` should include labels. or have a separate call for it.

**Comment by tmcw** [comment]
@ansis how deep is this issue? Where would a contributor start if they wanted to add labels to the rtree?

**Comment by ansis** [comment]
I think it might be sort of deep. The tricky thing is that labels have different sizes and different lengths along a line at different zoom levels.

`CollisionTile` already uses an rtree to index label positions for collisions. I think I'd extend `CollisionTile` to be able to return which `CollisionFeature`s are in the query box at a given zoom level. This would involve understanding how labels are represented for collisions and how `CollisionTile.placeCollisionFeature` works.

And then a bunch of work to integrate the new `CollisionTile.featuresAt` with `FeatureTree`.

**Comment by samanpwbb** [comment]
Any chance this could move some time in the next couple months? Are there any ways to temporarily hack around the issue? It's a pretty big usability knock for direct selecting -> styling. Users always expect to be able to click on labels.

**Comment by peterqliu** [comment]
>Are there any ways to temporarily hack around the issue? It's a pretty big usability knock for direct selecting -> styling. Users always expect to be able to click on labels.

for /app, one hack is to call `.featuresAt()`a second time with a more generous radius, and filter for symbols only. Would probably be too slow for x-ray mode, but okay for one-shot direct select.
