### ISSUE TITLE
Inconsistency in fill layer linked to mulit-linear-ring Polygon GeoJSON source

### ISSUE THREAD

**Issue by etpinard** [mapbox/mapbox-gl-js#3032]
**mapbox-gl-js version**: 0.19.0 and up 

Tested on Chrome `52.0.2743.116` on Ubuntu `16.04`.

### Steps to Trigger Behavior

Reproducible example: http://codepen.io/etpinard/pen/VjNaaR

 1. Make map with fill layer linked to GeoJSON source consisting of the `Polygon` type with multiple linear rings
 2. Compare output of version `0.18.0` and `>= 0.19.0`  (including `0.22.0`)

### Expected Behavior

- All linear rings should be filled, at all zoom levels (as in `0.18.0`)

### Actual Behavior

- Only the first linear ring is filled on first render, zooming in makes other linear ring appear filled.

In `0.22.0`:

![gifrecord_2016-08-18_164430](https://cloud.githubusercontent.com/assets/6675409/17790219/906deeda-6563-11e6-886d-f15a302f1e91.gif)

Possible related to https://github.com/mapbox/mapbox-gl-js/issues/2696

**Comment by mourner** [comment]
Yes, unfortunately Mapbox GL JS no longer supports invalid polygons like the ones where holes are outside the outer ring. You should use a MultiPolygon here instead.
