### ISSUE TITLE
Deprecate "StyleLayer#paint" and "StyleLayer#layout"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3044]
`StyleLayer#paint` and `StyleLayer#layout` do not accommodate for data-driven styling. Any code that uses these properties probably doesn't accommodate for data-driven styling either. We should deprecate these properties in favor of `StyleLayer#getPaintValue` and `StyleLayer#getLayoutValue`. This might be done in conjunction with #2739. 

cc @davidtheclark

**Comment by davidtheclark** [comment]
@lucaswoj So this is the root of the problem I was seeing? — that `queryRenderedFeatures` seemed to always look for circles that are as large as they *might* be instead of as large as they actually are?

**Comment by lucaswoj** [comment]
@davidtheclark Worse, actually. `queryRenderedFeatures` assumed all circles were the size specified in the first function stop 😬

**Comment by jfirebaugh** [comment]
I think we need to do this before adding further data-driven properties -- it's hiding a lot of bugs.
