### ISSUE TITLE
how to 10 miles  radius draw in mapbox

### ISSUE THREAD

**Issue by achalnexus** [mapbox/mapbox-gl-js#3047]
I have draw radius in mapbox.
i have convert miles convert to meters and then after convert to meter to pixel but not perfect radius  draw.
=======I have try this code=======

function SetRadius_Layer() {
    if (map.getLayer("circle500")) {
        map.removeLayer("circle500");
    }
    if (map.getSource("source_circle_500") != undefined) {
        map.removeSource("source_circle_500");
    }

    map.addSource("source_circle_500", {
        "type": "geojson",
        "data": {
            "type": "FeatureCollection",
            "features": [{
                "type": "Feature",
                "geometry": {
                    "type": "Point",
                    "coordinates": RadiusLatitudeCenterPoint
                }
            }]
        }
    });
    map.addLayer({
        "id": "circle500",
        "type": "circle",
        "source": "source_circle_500",
        "paint": {
            "circle-radius": {
                "stops": [
                    // zoom is 5 -> circle radius will be 1px
                    [7, pixelValue(RadiusLatitude, 241402, 7)], // Convert miles to meters-150
                    [9, pixelValue(RadiusLatitude, 48281, 9)],// Convert miles to meters-30
                    [11, pixelValue(RadiusLatitude, 16094, 11)],// Convert miles to meters-10
                ]
            },
            "circle-color": "#000",
            "circle-opacity": 0.15
        }
    });
    if (map.getZoom() == 11)
        $("#divMiles").html("10 Mi");
    else if (map.getZoom() == 9)
        $("#divMiles").html("30 Mi");
}

var metersPerPixel = function (latitude, zoomLevel) {
    var earthCircumference = 40075017;
    var latitudeRadians = latitude * (Math.PI / 180);
    return earthCircumference * Math.cos(latitudeRadians) / Math.pow(2, zoomLevel + 8);
    
};

function pixelValue(latitude, meters, zoomLevel) {
    alert(meters / metersPerPixel(latitude, zoomLevel));
    return meters / metersPerPixel(latitude, zoomLevel);
};

**Comment by jfirebaugh** [comment]
Hello @achalnexus. I regret that I am unable to help you with this question on our GitHub issue tracker because this is neither a feature request nor a bug report. 

I encourage you to post this [question on StackOverflow if you need more help](http://stackoverflow.com/questions/tagged/mapbox-gl-js).
