### ISSUE TITLE
Draw direction in GL-Mapbox

### ISSUE THREAD

**Issue by achalnexus** [mapbox/mapbox-gl-js#3048]
I have draw root line between more then 2 park using direction gl mapbox.
I have try this of code. but not draw root line direction.
====

mapboxgl.accessToken = 'pk.eyJ1IjoiYWNoYWxwcmFqYXBhdGkiLCJhIjoiY2lyNGkwZGsxMDFpenUybHd5bjRtMjVjeiJ9.2teTa5MmVqOW-MDpryv56w';
            var map = new mapboxgl.Map({
                container: 'map',
                style: 'mapbox://styles/achalprajapati/cis1byfch0008hgnitiwbym9c',
                center: [-122.222461, 37.172263],
                zoom: 8
            });
			
		var directions = new mapboxgl.Directions({
                unit: 'metric', // Use the metric system to display distances.
                profile: 'walking', // Set the initial profile to walking.
                container: 'directions', // Specify an element thats not the map container.
               // proximity: [-122.222453, 37.172271] // Give search results closer to these coordinates higher priority.
            });
			
		map.on('load', function () {
                directions.setOrigin([-122.222461, 37.172263]);
                directions.addWaypoint(0, [-122.222461, 37.172263]);
                directions.addWaypoint(1, [-122.483318, 37.724502]);
                directions.setDestination([-122.483318, 37.724502]);

            });
            directions.on('route', function (e) {

**Comment by jfirebaugh** [comment]
Hello @achalnexus. I regret that I am unable to help you with this question on our GitHub issue tracker because this is neither a feature request nor a bug report. 

I encourage you to post this [question on StackOverflow if you need more help](http://stackoverflow.com/questions/tagged/mapbox-gl-js).
