### ISSUE TITLE
Make "queryRenderedFeatures" and "querySourceFeatures" share instances of "VectorTile"

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3064]
- `queryRenderedFeatures` instantiates a `VectorTile` for each queried tile via `FeatureIndex` [here](https://github.com/mapbox/mapbox-gl-js/blob/c38cce890eec9469b7b3493428ed1adaeba75767/js/data/feature_index.js#L101-L101).
- `querySourceFeatures` instantiates a `VectorTile` for each queried tile [here](https://github.com/mapbox/mapbox-gl-js/blob/de61bbfa21f070e7afbe4fd42e24e8e44e7e25f1/js/source/tile.js#L156-L156).

Instead, they should share a single `VectorTile` object.

**Comment by mourner** [comment]
Looks like this is done already.
