### ISSUE TITLE
Support custom controls

### ISSUE THREAD

**Issue by Nimble-Momonga** [mapbox/mapbox-gl-js#3066]
It will be good to add a custom control to the map.

Something like map.addControl(new mapboxgl.CustomControl(/*fn*/, /*cssClass*/));

**Comment by lucaswoj** [comment]
Hello @Nimble-Momonga! Nice to meet you 😄 

GL JS does support custom controls; however the API to create them isn't very ergonomic or well-documented. [The `mapbox-gl-draw` plugin, for example, is implemented as a custom control](https://github.com/mapbox/mapbox-gl-draw/blob/master/src/setup.js#L16).

We have a couple of outstanding issues related to making custom controls easier

 - Document GL JS plugin architecture (including custom controls) https://github.com/mapbox/mapbox-gl-js/issues/1835
 - Get rid of the `mapboxgl.Control` class https://github.com/mapbox/mapbox-gl-js/issues/2118
