### ISSUE TITLE
Allow rendering MultiPoint GeoJSON features as 'line' or 'fill' map features

### ISSUE THREAD

**Issue by chriddyp** [mapbox/mapbox-gl-js#3071]
**mapbox-gl-js version**: 0.19-0.23

### Steps to Trigger Behavior
1 - Create `MultiPoint` GeoJSON:
```
{
  "type": "FeatureCollection",
  "features": [{
    "properties": {},
    "type": "Feature",
    "geometry": {
      "type": "MultiPoint",
      "coordinates": [
        [-73, 45],
        [-76, 46],
        [-75, 47]
      ]
    }
  }]
}
```
2 - Render that GeoJSON as a `type: 'line'` layer

See codepen: http://codepen.io/chriddyp/pen/EyBGzg?editors=1010

### Expected Behavior
Layer with `type` set to `fill`, `line`, or `symbol` would be visible

### Actual Behavior
Layer is not visible.

### Note

This layer *was* visible up through version 0.18. Screenshot: 
![image](https://cloud.githubusercontent.com/assets/1280389/17990617/5cc7ce14-6b05-11e6-8a3e-422f32c04ce5.png)

Here in version 0.23:
![image](https://cloud.githubusercontent.com/assets/1280389/17990631/7caba34a-6b05-11e6-9627-27ae8f639180.png)

**Comment by lucaswoj** [comment]
@mourner Any thoughts about this from a GeoJSON semantics or `geojson-vt` perspective?

**Comment by mourner** [comment]
I don't think this is technically possible or something that we should do. MultiPoint is clipped differently than LineString. I would suggest changing the type in the input data rather than hacking around it in the Mapbox GL JS core or geojson-vt.
