### ISSUE TITLE
Combine "mapbox-gl-plugins" repo and "docs/_posts/plugins"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3076]
We should combine these two sources of truth about GL JS plugins, simplifying the plugin publishing workflow and reducing the potential for error. 

As a bonus, we may be able to automatically publish plugins to `s3` from `publisher` when the `mb-pages` branch is deployed.

 - ["mapbox-gl-plugins" repo](https://github.com/mapbox/mapbox-gl-plugins)
 - ["docs/_posts/plugins"](https://github.com/mapbox/mapbox-gl-js/tree/master/docs/_posts/plugins)

**Comment by mourner** [comment]
This was done in #3300.
