### ISSUE TITLE
Shift zooming is broken

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox-gl-js#3077]
<img width="180" alt="screen shot 2016-08-26 at 11 25 19 am" src="https://cloud.githubusercontent.com/assets/58878/18016158/cbb38cd0-6b7f-11e6-80cd-d6675aaad740.png">

<img width="580" alt="screen shot 2016-08-26 at 11 23 09 am" src="https://cloud.githubusercontent.com/assets/58878/18016163/cf4e1130-6b7f-11e6-821e-ea219658b2f4.png">

- [For example](https://api.mapbox.com/styles/v1/tcql/cili6nva200aw9gm3iddjcxp2.html?title=false&access_token=pk.eyJ1IjoidGNxbCIsImEiOiJaSlZ6X3JZIn0.mPwXgf3BvAR4dPuBB3ypfA#5.02/39.360/-120.030)
- mapbox-gl-js version 0.23.0

### Steps to Trigger Behavior

 1. Hold shift
 2. Drag a box

### Expected Behavior

- It zooms to the bbox
- The URL is usable to share

### Actual Behavior

- It doesn't zoom to the bbox
- The map goes blank
- The URL is no longer valid

cc @lucaswoj

**Comment by lucaswoj** [comment]
Bug confirmed.

**Comment by lucaswoj** [comment]
This bug was introduced in #2414
