### ISSUE TITLE
setFilter with a combining filter won't update map if you update the same array that you gave the map

### ISSUE THREAD

**Issue by anvarik** [mapbox/mapbox-gl-js#3079]
I am testing this on v0.23.0. I believe this is similar to #2486 

#### How to reproduce
 1. Add a new layer with an OR filter
 2. Get the filter and store it in an array, add another filter for our OR statement
 3. Set the filter to the map

It should show the newly added filter on the map, however nothing happens. Here is a pseudocode: 

```javascript
// this works just fine both location1 and location2 are visible on the map
map.addLayer({
    id: 'locations',
     ...
     "filter": ["any", ["==", "name", "loc1"], ["==", "name", "loc2"]]
 }); 

// this fails to show loc3
map.on("click", function(e){
    var myFilters = map.getFilter("locations");
    myFilters.push( ["==", "name", "loc3"]);
    map.setFilter("locations", myFilters);
   // this works however:
   //  map.setFilter("locations", ["any", ["==", "name", "loc1"], ["==", "name", "loc2"], ["==", "name", "loc3"]]);
})
```

**Comment by tmcw** [comment]
While we're looking at that bit of code, also [the clone method is called deepEqual](https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/util.js#L426) - probably a copypasta mistake.

**Comment by elgabato** [comment]
I think mine has a similar issue but just only 1 date will be shown in the filter as I was expecting 2 date

 var _filter = [
            "all",
            [
                "match",
                ["get", "date"],
                [
                    "2021-11-10",
                    "2021-11-15"
                ],
                true,
                false
            ]
        ];

        mapInstance.setFilter(layerName, _filter);
        
        output
        
![Screenshot 2022-04-05 135522](https://user-images.githubusercontent.com/39982054/161687972-6c0f95fc-0b74-42c5-af31-d4a243956e8b.png)

has anyone a solution for this issue?
