### ISSUE TITLE
Fix bug causing bad GeoJSON polygon rendering

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3080]
@YunjieLi generated the following minimal test case for bad GeoJSON polygon rendering:

https://jsfiddle.net/yunjieli/qsx6z6eh/6/

![image](https://cloud.githubusercontent.com/assets/12749701/18021767/77230dde-6b9e-11e6-928d-4f42991a7463.png)

This is very likely invalid geometry in the GeoJSON polygon, and therefore not considered a GL JS bug, but I'm filing here to create a public record of the issue while we diagnose it.

@YunjieLi, could you describe how you generated this geometry? I understand turf was involved, which may make it a turf bug.

**Comment by YunjieLi** [comment]
Sure! I traced out the land and islands in the dataset editor first, and export the dataset as a geojson. I create a separate rectangle bounding box that covers all the map content, also in dataset editor. Then I did something like:

```
datasetOutput.forEach(function( polygon ){
    rectangle = turf.difference( rectangle, polygon );
})
```

**Comment by sabman** [comment]
This might be related I used tippecanoe to generate mbtiles and now my map has similar strange effects - note the blocky tiles and also the shards like @YunjieLi 
![strangeness-mapbox](https://cloud.githubusercontent.com/assets/1907/18047573/e5fd7406-6ddd-11e6-824f-4ebc2e787192.gif)

**Comment by mourner** [comment]
GeoJSON itself seems to be OK — it triangulates correctly with Earcut. So maybe the bug appears after slicing into tiles — I'm investigating.

![image](https://cloud.githubusercontent.com/assets/25395/18053728/98cb50f0-6e09-11e6-8287-9f5301858016.png)

**Comment by jnorris441** [comment]
Another example:

https://jsfiddle.net/jnorris441/vyz5ymwx/1/

**Comment by mourner** [comment]
@jnorris441 thanks for a much simpler case, that will make it easier to debug.

**Comment by Craytor** [comment]
Hmm... It seems like my issue (#5324) is having this same issue.
Any idea where this is at in terms of being fixed? It looks like it's been an issue for a while.

Thanks for the awesome library guys.

**Comment by benderlidze** [comment]
Any updates on this issue?
Geometry with issue 
{ "type": "Feature", "properties": { }, "geometry": { "type": "LineString", "coordinates": [ [ -0.065146296918187, -0.027007849813508 ], [ -0.064418309398459, -0.027007849813508 ], [ -0.064418309398459, -0.014223489278065 ], [ -0.065146296918187, -0.014223489278065 ], [ -0.065146296918187, -0.027007849813508 ] ] } }

And the correct geometry 
{ "type": "Feature", "properties": { }, "geometry": { "type": "LineString", "coordinates": [ [ -0.065146296918187, -0.014223488379749 ], [ -0.064418309398459, -0.014223488379749 ], [ -0.064418309398459, -0.027007850711836 ], [ -0.065146296918187, -0.027007850711836 ], [ -0.065146296918187, -0.014223488379749 ] ] } }
It is the same polygon.

And an exaple of rendering 2 different polygons, the correct one is on the right.
![screenshot_3](https://user-images.githubusercontent.com/8510813/30953703-b6074882-a435-11e7-910d-953bc5214da5.png)

**Comment by Chasvortex** [comment]
Hey there - I'm also struggling with this! What's the current status here?

**Comment by Chasvortex** [comment]
@mourner Would it be useful having a further example source?

**Comment by mourner** [comment]
Made a master ticket for this and similar issues to centralize the discussion: #7023
