### ISSUE TITLE
TileCoord.id should be treated as an opaque handle in all module/classes using TileCoord(even though its numeric).

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#3083]
**mapbox-gl-js version**:Master

### Steps to Trigger Behavior
This line in [SourceCache]( https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/source_cache.js#L361
) removes a tile using an id. However in the call it appends a plus sign. Its not needed and is redundant/confusing.

**Comment by 1ec5** [comment]
For what it’s worth, the plus sign is a shortcut for coercing a string into a number (or ensuring a type is a number).

**Comment by lucaswoj** [comment]
Even if we remove that number coercion, `TileCoord#id` is not an opaque handle as evidenced by the existence and use of the `TileCoord.fromID` method. Are you seeing any bugs, performance implications, or architectural problems with the way we use `TileCoord#id`?

**Comment by mb12** [comment]
It does not cause any bug or performance issue. 
If we remove the coercion here and at one other place, TileCoord  id could be changed to hold other  members  (e.g. canonical zoom).

Currently TileCoord has one member that is overscaled, while others are canconical.
TileCoord.z : overscaled
TileCoord.x, TileCoord.y : canonical

To compute canonical z  in either Workers or Painter, one needs to compute it using Tile.overscaling and the contained TileCoord. 
I was playing around with TileCoord by adding a member to hold canonical zoom as well, when I ran into this issue.  Another place where this coercion happens is sorting by zoom.

**Comment by lucaswoj** [comment]
> If we remove the coercion here and at one other place, TileCoord id could be changed to hold other members (e.g. canonical zoom).

Sounds like a similar approach to https://github.com/mapbox/mapbox-gl-js/pull/1997 and a potential fix for https://github.com/mapbox/mapbox-gl-js/issues/2868. Feel free to include this refactoring in a PR that introduces a specific feature or fixes a specific bug.
