### ISSUE TITLE
Replace <div> in compass control with an inline element

### ISSUE THREAD

**Issue by erustusagutu** [mapbox/mapbox-gl-js#3089]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Load mapbox

### Expected Behavior
The button should have an image as a child

### Actual Behavior
The button has a div as a child

![image](https://cloud.githubusercontent.com/assets/20397756/18050161/be5d6c92-6de4-11e6-85be-d98fcd1d9991.png)

**Comment by mourner** [comment]
Why would it have to be an image? Can you explain more?

**Comment by lucaswoj** [comment]
Per the HTML spec a button can contain only inline elements. A `div` is a block element.
