### ISSUE TITLE
http://geojson.org/geojson-spec.html#positions

### ISSUE THREAD

**Issue by gertcuykens** [mapbox/mapbox-gl-js#3090]
Before the 1.0 release can we move to a universal order in coordinates please? Meaning `[longitude, latitude, altitude]`

see http://geojson.org/geojson-spec.html#positions

Example:
1) `LatLngBounds` should become `LngLatBounds` (edit: maybe this was just a typo in https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.23.0 commit message that got me worried :P)
2) The hashtag url should be `#longitude/latitude/altitude` where altitude is a rough estimate of the zoom level in a standard geojson altitude measurement.

Yes this will break allot of code, but in the end it is so much more pleasant to have the same order in every function / array.

Thank you

**Comment by mourner** [comment]
`LatLngBounds` is a typo: https://github.com/mapbox/mapbox-gl-js/blob/master/js/geo/lng_lat_bounds.js

I don't think it makes sense to break compatibility in the hashtag URL. Especially the altitude thing — it's not an equivalent value to zoom level, they mean different things.

**Comment by gertcuykens** [comment]
I don't know, my personal opinion for me is that the viewpoint in space is a certain altitude. Let say one day Mapbox decide to build a 3d map system from drone footage. Wouldn't it be nice to have a altitude api specification ready to be hooked in so you can generate a first person view of a drone on a map?

PS Also despite the zoom lat/long orde seems awkward to me especially if everything else is lnglat already?

Going to change the title of this topic.
