### ISSUE TITLE
Fix bug preventing rotation via two finger touch from rotating the compass icon

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#3094]
**mapbox-gl-js version**:Master
### Steps to Trigger Behavior
1. Rotate map using two finger rotate gesture. Map rotates but the compass does not rotate to always point to north.

Its only an issue with touch.  The following works:
- Rotate via right click mouse
- Use shift + right/left arrows keys.
### Expected Behavior

Compass should rotate like it does for keyboard and mouse controls for rotation.
### Actual Behavior

Compass ignores map rotation when initiated via touch.

**Comment by jfirebaugh** [comment]
Not reproducible with 0.43.
