### ISSUE TITLE
Marker.togglePopup() does not work

### ISSUE THREAD

**Issue by apkoponen** [mapbox/mapbox-gl-js#3096]
mapbox-gl-js version 0.23:

### Steps to Trigger Behavior

 1. Add a Marker and bind a Popup to it with setPopup();
 2. Call Marker.togglePopup();

### Expected Behavior

Popup should be shown.

### Actual Behavior

"Uncaught TypeError: Cannot read property 'stopPropagation' of undefined"

The reason is that Marker.togglePopup does not supply an event to Marker._openPopup() (https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/marker.js#L136) and Marker._openPopup does not check if the event exists (https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/marker.js#L141).

**Comment by lucaswoj** [comment]
👍 this bug and a few others were pointed out in the PR reivew at https://github.com/mapbox/mapbox-gl-js/pull/3056.
