### ISSUE TITLE
Lots of fake positions near Null Island

### ISSUE THREAD

**Issue by elliotleelewis** [mapbox/mapbox-gl-js#3097]
Which one of you added all these GTA: San Andreas references? 😄 

**mapbox-gl-js version**: v22.1

### Steps to Trigger Behavior

 1. Load up a mapbox-gl map.
 2. Set Center to [0, 0].
 3. Zoom in very close and lots of little non-existent places appear.

### Expected Behavior

Nothing but oceans.

### Actual Behavior

Tiny islands that are GTA: San Andreas references.

<img width="504" alt="screen shot 2016-08-30 at 15 51 24" src="https://cloud.githubusercontent.com/assets/17044667/18094127/525b2c78-6eca-11e6-912c-e76137ca3338.png">

**Comment by elliotleelewis** [comment]
They're all geographically placed relative to the GTA: SA map too. That weird square thing looks like Pershing Square...

![pershing_square](https://cloud.githubusercontent.com/assets/17044667/18094371/2cf834fc-6ecb-11e6-97fa-1784820784e0.png)

**Comment by lucaswoj** [comment]
Thanks for the report @elliotleelewis. 

This data comes from Open Street Map via Mapbox Streets, separate projects from the GL JS map renderer.

I recommend you take this up with the Open Street Map community or report the problem on the [Mapbox map feedback page](https://www.mapbox.com/map-feedback/)
