### ISSUE TITLE
Fix bug preventing changing a paint property via "Map#addClass"

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3098]
https://github.com/mapbox/mapbox-gl-test-suite/blob/ad6ce8d1111df7b4bef75beef285e4432c398927/render-tests/runtime-styling/class-add-override/style.json

**Comment by anandthakker** [comment]
Ref https://github.com/mapbox/mapbox-gl-js/pull/3643
