### ISSUE TITLE
[Question] Is there a way to cluster custom markers in mapbox-gl?

### ISSUE THREAD

**Issue by bcalik** [mapbox/mapbox-gl-js#3101]
I would like to cluster [custom html markers](https://www.mapbox.com/mapbox-gl-js/api/#Marker) like the way I can [cluster geojson markers](https://www.mapbox.com/mapbox-gl-js/example/cluster/).
Is there any way to do it? Or I have to switch to leaflet.

Sorry for asking a question here. Thanks.

**Comment by jfirebaugh** [comment]
Nope. For clustering you'll need to use a GeoJSON layer.
