### ISSUE TITLE
0.23.0 breaks some fill layers that use fill-pattern

### ISSUE THREAD

**Issue by dpieri** [mapbox/mapbox-gl-js#3107]
**mapbox-gl-js version**: 0.23.0

When using 0.22.1 and earlier, a fill layer with `fill-outline-color` and `fill-color` and `fill-pattern` specified will render the pattern, but not the color or outline (as is expected based on my reading of the style spec).

As of 0.23.0 the same layer will now be rendered with no pattern and no color.

To further complicate things, the issue described above does not surface if you use a hex color instead of hsla(). If you use a hex then the pattern renders as expected.

### Examples
0.22.1 + hsla(), pattern _does_ render: http://jsbin.com/xujowiqeno/1/edit?html,output

0.23.0 + hsla(), pattern _does not_ render: http://jsbin.com/zifoxutavo/1/edit?html,output

0.23.0 + hex(), pattern _does_ render: http://jsbin.com/mozefaxura/1/edit?html,output

### Expected Behavior
Pattern renders.

### Actual Behavior
Pattern does not render.

**Comment by lucaswoj** [comment]
This bug was introduced by https://github.com/mapbox/mapbox-gl-js/pull/3061. Fix coming shortly.
