### ISSUE TITLE
expose an api to remove an event Listener

### ISSUE THREAD

**Issue by omarbenh** [mapbox/mapbox-gl-js#3108]
**mapbox-gl-js version**: 0.23.0

### Steps to Trigger Behavior

 https://jsbin.com/tukobihume/edit?html,console,output

**Comment by omarbenh** [comment]
it's seems that there is an api to do that : this.off

**Comment by justswim** [comment]
Can you elaborate on how to remove an event listener? I did this:

map.on('drag', setPinCoords);
map.off('drag', setPinCoords);

but the second line ("off") didn't work.

**Comment by wandergis** [comment]
@justswim I also got this problem.

**Comment by bdoyle522** [comment]
@wandergis answer is over on #3484
