### ISSUE TITLE
Ensure removing releases tile resources

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3116]
If you use `Map#removeSource`, the source is removed but `unloadTile` isn't called for any currently loaded tiles, so their WebGL resources may continue to consume memory for an indefinite amount of time, including until the WebGL context is destroyed.

**Comment by jfirebaugh** [comment]
A similar problem likely exists for loading a new style.

**Comment by averas** [comment]
Relates to #2633... I'm having trouble clearing cached tiles in any way, since removing and adding the source does not seem to have the tile cache cleared...
