### ISSUE TITLE
Remove remaining "browser" modules

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3121]
Continuing the work started in #3106:
- [x] try to eliminate `canvas` module #3135
- [x] try to eliminate `ajax` module #3134 
- [ ] try to eliminate `web_worker` module
- [ ] eliminate all utilities that provide no abstraction over functionality provided by the DOM
- [ ] move window mock from `js` directory to `test` directory

**Comment by jfirebaugh** [comment]
I think we've captured the bulk of the benefits here.
