### ISSUE TITLE
will mapboxgl support drawing point、line or polygon which the coordinate has  altitude value?

### ISSUE THREAD

**Issue by wangtun** [mapbox/mapbox-gl-js#3124]
I want to draw some lines with different altitudes and  I try set the coordinate like (x,y,altitude) , but the mapboxgl will draw them on the plat with the same altitude.

**Comment by jfirebaugh** [comment]
This isn't currently possible; we're tracking the feature request in https://github.com/mapbox/mapbox-gl/issues/6.
