### ISSUE TITLE
Fix bug causing ctrl-drag rotate to not work in Mac Firefox

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#3131]
**mapbox-gl-js version**: 0.23.0
### Steps to Trigger Behavior
1. Hold down <kbd>⌃ Ctrl</kbd> and drag the map left and right.
### Expected Behavior

The map rotates clockwise and counterclockwise.
### Actual Behavior

The map stays put.

The standard two-finger rotation gesture doesn’t work either, but that’s #2618.

Observed in Firefox 50.0a2 (2016-08-31) on OS X 10.11.6 (15G1004) using a multitouch trackpad.

/cc @scothis

**Comment by averas** [comment]
Probably not related, but something one might want to adress while solving this is #1888

**Comment by 1ec5** [comment]
My hunch is that this bug is caused by Mac Firefox opening the context menu (and firing `contextmenu`) on Ctrl+mousedown, whereas Safari and Chrome do so on Ctrl+mouseup.

**Comment by lbud** [comment]
Woof. In Firefox, <kbd>⌃ Ctrl</kbd> + click/drag fires a `mousedown` event where `event.button = 2` (the [right button](https://developer.mozilla.org/en-US/docs/Web/Events/mousedown)), whereas Chrome and Safari event's `button` property gives `0` (the left button).

In practice this means our drag handlers think we should ignore the mousedown event ([here](https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/handler/drag_rotate.js#L202-L203)) and we don't add a `mousemove` listener (which presumably would suffer the same fate).

🤔🤔🤔
