### ISSUE TITLE
Feature Request: Native Style Viewer for Mapbox

### ISSUE THREAD

**Issue by fedex1** [mapbox/mapbox-gl-js#3138]
We love mapbox.  The mapbox web based style viewer is great.  But sometimes the native Android version of mapbox is faster and easier to use.

I've experimented with @zugaldia offline sample and built a simple native style viewer for Android.  See https://play.google.com/store/apps/details?id=com.brooklynmarathon.mapcityregister.mapboxviewer

I'd love to see the equivalent iOS native style viewer.

This is just a thought to make mapbox faster and better.  Not mandatory.

Also this uses the branch.io flow to help the user install the app if they do not have it.

For example, https://qrxf.app.link/DsC4mJxskw is a branch.io link to share the default style

But if you pass a style and token it will load that one:

https://qrxf.app.link?access_token=pk.eyJ1IjoiY2l0eXJlZ2lzdGVyIiwiYSI6ImNpbnhrMHJhcjE3OHh1Mm0zbnJ6YXZseWcifQ.1TP2MzhnoJCdzX_qYns1BA&style=mapbox%3A%2F%2Fstyles%2Fcityregister%2Fcinyzwrq10003a4npcz3lb1t3

**access_token**=pk.eyJ1IjoiY2l0eXJlZ2lzdGVyIiwiYSI6ImNpbnhrMHJhcjE3OHh1Mm0zbnJ6YXZseWcifQ.1TP2MzhnoJCdzX_qYns1BA

**style**=mapbox%3A%2F%2Fstyles%2Fcityregister%2Fcinyzwrq10003a4npcz3lb1t3

The parameters are similar to the parameters to the web mapbox style viewer.

It would be good if there was an iOS version of the native style viewer.  

Also, Branch.io has support for many more app stores.

Let me know if this is helpful.

Also one reason for the native viewer is it seems to run faster and it is easier to make controls work better.

Compare:

![screenshot_20160902-122718](https://cloud.githubusercontent.com/assets/167614/18210937/064f945e-7109-11e6-82c4-9e5135c83c13.png)

to
![screenshot_20160902-122837](https://cloud.githubusercontent.com/assets/167614/18210941/0cd1e6e2-7109-11e6-853e-49366326ebd6.png)

**Comment by jfirebaugh** [comment]
Hi, thanks for the suggestion. We provide native iOS and Android SDKs as well as numerous examples and example apps, many of which show how to load Mapbox default styles or a custom style. At this time we don't have plans to release an official app which would load any style by URL -- I'm assuming that's what you mean by "native style viewer". If that's something you think is valuable, feel free to build it!

**Comment by fedex1** [comment]
Thanks @jfirebaugh I already did for Android.  If anyone would like to help with an iOS native viewer please contact me or comment here.
