### ISSUE TITLE
Errors in console while updating

### ISSUE THREAD

**Issue by nicolehu15** [mapbox/mapbox-gl-js#3140]
I recently updated to v0.23.0 and notice several repeated errors in the console

![screen shot 2016-09-02 at 3 27 01 pm](https://cloud.githubusercontent.com/assets/6128569/18219853/c2a6cb96-7121-11e6-9a5f-b8ff56b5d963.png)

I also referred to issue https://github.com/mapbox/mapbox-gl-js/issues/2587 and was wondering if both of them are the same problem

**Comment by jfirebaugh** [comment]
Yes, it's the same as #2587, #1800, and other duplicates.
