### ISSUE TITLE
Add collection of mapboxgl.Marker to a layer

### ISSUE THREAD

**Issue by nicolehu15** [mapbox/mapbox-gl-js#3141]
I wish to use custom icons for my markers as in the [example](https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/) which adds mapboxgl.Marker for every point in the map.

However, I also wish to have an ability to [toggle](https://www.mapbox.com/mapbox-gl-js/example/toggle-layers/) my custom icons on/off. What would you recommend is the most ideal way to go about doing this?

The simplest way I see here is an ability to push an array of mapboxgl.Markers into a layer. However I do not know if there is a method of doing the above.

**v0.23.0**

**Comment by jfirebaugh** [comment]
There's not built in mechanism for grouping `Markers`; you will need to add and remove them in a loop.

**Comment by RamizSami** [comment]
Is there any support for this yet?
