### ISSUE TITLE
Mapbox GL not display map

### ISSUE THREAD

**Issue by RafalR** [mapbox/mapbox-gl-js#3143]
**mapbox-gl-js version v0.23.0**:

### Steps to Trigger Behavior

 1. Open https://www.mapbox.com/mapbox-gl-js/examples/

### Expected Behavior

I think I should see map

### Actual Behavior

http://i.imgur.com/tG3PQ4H.png

### Graphics Feature Status

*   Canvas: Hardware accelerated
*   Flash: Hardware accelerated
*   Flash Stage3D: Hardware accelerated
*   Flash Stage3D Baseline profile: Hardware accelerated
*   Compositing: Hardware accelerated
*   Multiple Raster Threads: Disabled
*   Native GpuMemoryBuffers: Software only. Hardware acceleration disabled
*   Rasterization: Software only. Hardware acceleration disabled
*   Video Decode: Hardware accelerated
*   Video Encode: Hardware accelerated
*   WebGL: Hardware accelerated

### Driver Bug Workarounds

*   clear_uniforms_before_first_program_use
*   disable_direct_composition
*   disable_discard_framebuffer
*   exit_on_context_lost
*   force_cube_complete
*   scalarize_vec_and_mat_constructor_args
*   texsubimage_faster_than_teximage
*   use_current_program_after_successful_link

### Problems Detected

*   Always call glUseProgram after a successful link to avoid a driver bug: [349137](http://crbug.com/349137)
    _Applied Workarounds: use_current_program_after_successful_link_
*   Some drivers are unable to reset the D3D device in the GPU process sandbox
    _Applied Workarounds: exit_on_context_lost_
*   TexSubImage is faster for full uploads on ANGLE
    _Applied Workarounds: texsubimage_faster_than_teximage_
*   Clear uniforms before first program use on all platforms: [124764](http://crbug.com/124764), [349137](http://crbug.com/349137)
    _Applied Workarounds: clear_uniforms_before_first_program_use_
*   Always rewrite vec/mat constructors to be consistent: [398694](http://crbug.com/398694)
    _Applied Workarounds: scalarize_vec_and_mat_constructor_args_
*   ANGLE crash on glReadPixels from incomplete cube map texture: [518889](http://crbug.com/518889)
    _Applied Workarounds: force_cube_complete_
*   Framebuffer discarding can hurt performance on non-tilers: [570897](http://crbug.com/570897)
    _Applied Workarounds: disable_discard_framebuffer_
*   Direct composition flashes black initially on Win <10: [588588](http://crbug.com/588588)
    _Applied Workarounds: disable_direct_composition_
*   Accelerated rasterization has been disabled, either via blacklist, about:flags or the command line.
    _Disabled Features: rasterization_
*   Raster is using a single thread.
    _Disabled Features: multiple_raster_threads_
*   Native GpuMemoryBuffers have been disabled, either via about:flags or command line.
    _Disabled Features: native_gpu_memory_buffers_

Version Information | -
--- | ---
|Data exported | 4.09.2016, 14:27:37|
| Chrome version | Chrome/52.0.2743.116 |
| Operating system | Windows NT 6.3 |
| Software rendering list version | 11.7 |
| Driver bug list version | 8.78 |
| ANGLE commit id | f07246f6a06d |
| 2D graphics backend | Skia |
| Command Line Args | Files (x86)\Google\Chrome\Application\chrome.exe" --profile-directory=Default --flag-switches-begin --enable-webgl-draft-extensions --flag-switches-end |

Driver Information  | -
--- | ---
| Initialization time | 85 |
| In-process GPU | false |
| Sandboxed | false |
| GPU0 | VENDOR = 0x10de, DEVICE= 0x06e8 |
| Optimus | false |
| AMD switchable | false |
| Desktop compositing | Aero Glass |
| Diagonal Monitor Size of \\.\DISPLAY1 | 15.9" |
| Driver vendor | NVIDIA |
| Driver version | 9.18.13.4144 |
| Driver date | 2-3-2015 |
| Pixel shader version | 4.0 |
| Vertex shader version | 4.0 |
| Max. MSAA samples | 8 |
| Machine model name |
| Machine model version |
| GL_VENDOR | Google Inc. |
| GL_RENDERER | ANGLE (NVIDIA GeForce 9200M GS Direct3D11 vs_4_0 ps_4_0) |
| GL_VERSION | OpenGL ES 2.0 (ANGLE 2.1.0.f07246f6a06d) |
| GL_EXTENSIONS | GL_OES_element_index_uint GL_OES_packed_depth_stencil GL_OES_get_program_binary GL_OES_rgb8_rgba8 GL_EXT_texture_format_BGRA8888 GL_EXT_read_format_bgra GL_NV_pixel_buffer_object GL_OES_mapbuffer GL_EXT_map_buffer_range GL_EXT_color_buffer_half_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_float GL_OES_texture_float_linear GL_EXT_texture_rg GL_EXT_texture_compression_dxt1 GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_OES_compressed_ETC1_RGB8_texture GL_EXT_sRGB GL_ANGLE_depth_texture GL_OES_depth32 GL_EXT_texture_storage GL_OES_texture_npot GL_EXT_draw_buffers GL_EXT_texture_filter_anisotropic GL_EXT_occlusion_query_boolean GL_NV_fence GL_EXT_disjoint_timer_query GL_EXT_robustness GL_EXT_blend_minmax GL_ANGLE_framebuffer_blit GL_ANGLE_framebuffer_multisample GL_ANGLE_instanced_arrays GL_ANGLE_pack_reverse_row_order GL_OES_standard_derivatives GL_EXT_shader_texture_lod GL_EXT_frag_depth GL_ANGLE_texture_usage GL_ANGLE_translated_shader_source GL_EXT_discard_framebuffer GL_EXT_debug_marker GL_OES_EGL_image GL_NV_EGL_stream_consumer_external GL_EXT_unpack_subimage GL_NV_pack_subimage GL_OES_vertex_array_object GL_KHR_debug GL_ANGLE_lossy_etc_decode GL_CHROMIUM_bind_uniform_location GL_CHROMIUM_sync_query |
| Disabled Extensions |
| Window system binding vendor | Google Inc. (adapter LUID: 0000000000005f5e) |
| Window system binding version | 1.4 (ANGLE 2.1.0.f07246f6a06d) |
| Window system binding extensions | EGL_EXT_create_context_robustness EGL_ANGLE_d3d_share_handle_client_buffer EGL_ANGLE_surface_d3d_texture_2d_share_handle EGL_ANGLE_query_surface_pointer EGL_ANGLE_window_fixed_size EGL_ANGLE_keyed_mutex EGL_ANGLE_surface_orientation EGL_ANGLE_direct_composition EGL_NV_post_sub_buffer EGL_KHR_create_context EGL_EXT_device_query EGL_KHR_image EGL_KHR_image_base EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_gl_renderbuffer_image EGL_KHR_get_all_proc_addresses EGL_KHR_stream EGL_KHR_stream_consumer_gltexture EGL_NV_stream_consumer_gltexture_yuv EGL_ANGLE_flexible_surface_compatibility EGL_ANGLE_stream_producer_d3d_texture_nv12 |
| Direct rendering | Yes |
| Reset notification strategy | 0x8252 |
| GPU process crash count | 0 |

Compositor Information | -
--- | ---
| Tile Update Mode | One-copy |
| Partial Raster | Enabled |

GpuMemoryBuffers Status | -
--- | ---
| ATC | Software only |
| ATCIA | Software only |
| DXT1 | Software only |
| DXT5 | Software only |
| ETC1 | Software only |
| R_8 | Software only |
| BGR_565 | Software only |
| RGBA_4444 | Software only |
| RGBX_8888 | Software only |
| RGBA_8888 | Software only |
| BGRX_8888 | Software only |
| BGRA_8888 | Software only |
| YUV_420 | Software only |
| YUV_420_BIPLANAR | Software only |
| UYVY_422 | Software only |

Diagnostics | -
--- | ---
| 0
| b3DAccelerationEnabled | true |
| b3DAccelerationExists | true |
| bAGPEnabled | true |
| bAGPExistenceValid | true |
| bAGPExists | true |
| bCanRenderWindow | true |
| bDDAccelerationEnabled | true |
| bDriverBeta | false |
| bDriverDebug | false |
| bDriverSigned | false |
| bDriverSignedValid | false |
| bNoHardware | false |
| dwBpp | 32 |
| dwDDIVersion | 10 |
| dwHeight | 768 |
| dwRefreshRate | 60 |
| dwWHQLLevel | 0 |
| dwWidth | 1366 |
| iAdapter | 0 |
| lDriverSize | 17559432 |
| lMiniVddSize | 0 |
| szAGPStatusEnglish | Enabled |
| szAGPStatusLocalized | Włączone |
| szChipType | GeForce 9200M GS |
| szD3DStatusEnglish | Enabled |
| szD3DStatusLocalized | Włączone |
| szDACType | Integrated RAMDAC |
| szDDIVersionEnglish | 10 |
| szDDIVersionLocalized | 10 |
| szDDStatusEnglish | Enabled |
| szDDStatusLocalized | Włączone |
| szDXVAHDEnglish | Supported |
| szDXVAModes | ModeMPEG2_A ModeMPEG2_C ModeVC1_C ModeWMV9_C |
| szDescription | NVIDIA GeForce 9200M GS |
| szDeviceId | 0x06E8 |
| szDeviceIdentifier | {D7B71E3E-45A8-11CF-CD67-47E01CC2C435} |
| szDeviceName | \\.\DISPLAY1 |
| szDisplayMemoryEnglish | 2024 MB |
| szDisplayMemoryLocalized | 2024 MB |
| szDisplayModeEnglish | 1366 x 768 (32 bit) (60Hz) |
| szDisplayModeLocalized | 1366 x 768 (32 bit) (60Hz) |
| szDriverAssemblyVersion | 9.18.13.4144 |
| szDriverAttributes | Final Retail |
| szDriverDateEnglish | 2/4/2015 05:56:28 |
| szDriverDateLocalized | 2015-02-04 05:56:28 |
| szDriverLanguageEnglish | English |
| szDriverLanguageLocalized | Angielski |
| szDriverModelEnglish | WDDM 1.2 |
| szDriverModelLocalized | WDDM 1.2 |
| szDriverName | nvd3dumx.dll,nvwgf2umx.dll,nvwgf2umx.dll,nvd3dum,nvwgf2um,nvwgf2um |
| szDriverNodeStrongName | oem1.[inf:0f066de391c2bc3b:Section008:9.18.13.4144:pci](inf:0f066de391c2bc3b:Section008:9.18.13.4144:pci)\ven_10de&dev_06e8&subsys_c04a144d |
| szDriverSignDate |
| szDriverVersion | 9.18.0013.4144 |
| szKeyDeviceID | Enum\PCI\VEN_10DE&DEV_06E8&SUBSYS_C04A144D&REV_A1 |
| szKeyDeviceKey | \Registry\Machine\System\CurrentControlSet\Control\Video\{C93650F3-0AAA-4303-99DE-01BB18B71C49}\0000 |
| szManufacturer | NVIDIA |
| szMiniVdd | n/d |
| szMiniVddDateEnglish | n/a |
| szMiniVddDateLocalized | n/d |
| szMonitorMaxRes |
| szMonitorName | Generic PnP Monitor |
| szNotesEnglish | No problems found. |
| szNotesLocalized | Nie znaleziono żadnych problemów. |
| szOverlayEnglish | Supported |
| szRankOfInstalledDriver | 00DA0001 |
| szRegHelpText |
| szRevision |
| szRevisionId | 0x00A1 |
| szSubSysId | 0xC04A144D |
| szTestResultD3D7English | Not run |
| szTestResultD3D7Localized | Nie uruchomiono |
| szTestResultD3D8English | Not run |
| szTestResultD3D8Localized | Nie uruchomiono |
| szTestResultD3D9English | Not run |
| szTestResultD3D9Localized | Nie uruchomiono |
| szTestResultDDEnglish | Not run |
| szTestResultDDLocalized | Nie uruchomiono |
| szVdd | n/d |
| szVendorId | 0x10DE |

### Log Messages

*   [23676:21576:0904/141206:[ERROR:gles2_cmd_decoder.cc(8107)](ERROR:gles2_cmd_decoder.cc(8107))] : [.Offscreen-For-WebGL-000000098323F980]RENDER WARNING: there is no texture bound to the unit 0
*   [23676:21576:0904/141206:[ERROR:gles2_cmd_decoder.cc(8107)](ERROR:gles2_cmd_decoder.cc(8107))] : [.Offscreen-For-WebGL-000000098323F980]RENDER WARNING: there is no texture bound to the unit 0
*   [23676:21576:0904/141252:[ERROR:gles2_cmd_decoder.cc(8107)](ERROR:gles2_cmd_decoder.cc(8107))] : [.Offscreen-For-WebGL-0000000985D159A0]RENDER WARNING: there is no texture bound to the unit 0
*   [23676:21576:0904/141252:[ERROR:gles2_cmd_decoder.cc(8107)](ERROR:gles2_cmd_decoder.cc(8107))] : [.Offscreen-For-WebGL-0000000985D159A0]RENDER WARNING: there is no texture bound to the unit 0
*   GpuProcessHostUIShim: The GPU process exited normally. Everything is okay.

**Comment by jfirebaugh** [comment]
Thank you for the detailed information.

When you load https://www.mapbox.com/mapbox-gl-js/examples/, is there any output in the Javascript console?

If you load https://www.khronos.org/registry/webgl/sdk/tests/webgl-conformance-tests.html and run the tests, are there any failures?

**Comment by KoAi** [comment]
Same for me since version v0.12.3 #2131
Is it working for you in v0.12.2 ? And have you same problem with mapbox Studio ?

You can also try a little "hack", add a pitch to make it working (for me it works)

https://jsfiddle.net/kngpteyj/

@jfirebaugh for me, no errors in console bu I have a lot of failures on webgl conformance tests ("expected shaders to compile and link properly, but failed to link")

**Comment by RafalR** [comment]
http://i.imgur.com/w6VmXkZ.png

I use Mapillary (https://www.mapillary.com/app/). About a month ago, everything worked. Then I used Vista yet who is no longer supported by Google Chrome. I wanted to check out the new features on the map but I do not see.

**Comment by RafalR** [comment]
@KoAi Your hack works. https://jsfiddle.net/kngpteyj/ :) But sites do not know about the issue.

Hack http://i.imgur.com/BdMGGAG.png
Map Studio https://cloud.githubusercontent.com/assets/659513/18346610/74b48de8-75c1-11e6-9007-2cec0059d1db.png

I think it's the same problem that appeared earlier. (https://github.com/mapbox/mapbox-gl-js/issues/2131) You will need to somehow fix it because I suspect that not all map users know that they can report a bug or change settings that everything worked as it should.

Not all users are sufficiently advanced to change a setting to view the map. This should work without problems

**Comment by RafalR** [comment]
https://youtu.be/m9aLGWxhaNo map is visible if pitch value is non-zero

**Comment by lucaswoj** [comment]
Merging this with https://github.com/mapbox/mapbox-gl-js/issues/2942. Thanks for the debugging y'all!
