### ISSUE TITLE
querySourceFeatures returning duplicated points

### ISSUE THREAD

**Issue by johnnyluu** [mapbox/mapbox-gl-js#3147]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Upload geojson dataset of 31 points (cisqv1fnx024h2omqlisu6xxb) to tileset (brightfox.0wmnn91w)
 2. Added the tileset to the style (mapbox://styles/brightfox/cisb9ymah000g2xk22vz2c9we)
 2. In the javascript, run markers = map.querySourceFeatures('composite', { sourceLayer: 'revive-markers-drqfu4' });

### Expected Behavior
Should return an array of 31 features
### Actual Behavior
Returns an array of 38 features with duplicated points. I'm using this data to generate a slide, and I've used the same code in multiple projects, and they all worked fine. I don't know what's wrong with this particular dataset that's messing with results.

**Comment by jfirebaugh** [comment]
See the documentation of [`queryRenderedFeatures`](https://www.mapbox.com/mapbox-gl-js/api/#Map#queryRenderedFeatures):

> Because features come from tiled vector data or GeoJSON data that is converted to tiles internally, feature geometries are clipped at tile boundaries and, as a result, features may appear multiple times in query results when they span multiple tiles. For example, suppose there is a highway running through the bounding rectangle of a query. The results of the query will be those parts of the highway that lie within the map tiles covering the bounding rectangle, even if the highway extends into other tiles, and the portion of the highway within each map tile will be returned as a separate feature.

**Comment by jfirebaugh** [comment]
Updated this documentation to clarify that this applies to point features as well due to tile buffering.

**Comment by johnnyluu** [comment]
Thanks for the reply @jfirebaugh. I thought that only applies to queryRenderedFeatures, not querySourceFeatures. Is there a method  I can use to get the source without duplicates?

**Comment by mb12** [comment]
@jfirebaugh Is buffering also done for vector tiles generated on the fly (on client side) for geojson tile sources?

**Comment by mb12** [comment]
@johnnyluu You should add a unique property id to every geojson feature. You can use this id to find out which features are duplicated.  This would work for all features (including line and area).

**Comment by edmangog** [comment]
I have the same issue. The filter expression in Javascript helps me to solve it by filtering out the duplicate id within the object return by the map.querySourceFeatures.

```
    var features = (map.querySourceFeatures('Cases', {
    sourceLayer: 'Cases-9rpxlo',
    }));

    let ids = features.map(o => o.id)
    let filtered = features.filter(({id}, index) => !ids.includes(id, index+1))
```
