### ISSUE TITLE
Allow pin icon to change when pin is clicked

### ISSUE THREAD

**Issue by jvence** [mapbox/mapbox-gl-js#3148]
It would be great to allow us to dynamically change the icon of a pin when it is clicked. Is this possible? Thanks

**Comment by jfirebaugh** [comment]
Hello @jvence. I regret that I am unable to help you with this question on our GitHub issue tracker because this is neither a feature request nor a bug report. 

I encourage you to post this [question on StackOverflow if you need more help](http://stackoverflow.com/questions/tagged/mapbox-gl-js).
