### ISSUE TITLE
Fix bug allowing camera easings to be stopped with a click on a non-interactive map

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#3150]
**mapbox-gl-js v0.23.0**:
### Steps to Trigger Behavior
1. Create a non-interactive map (interactive: false)
2. Initiate an animated transition, for example with flyTo
3. Click on the map during the transition

Demo: http://codepen.io/anon/pen/xEbZQm
### Expected Behavior

That the map does not react to the mouse click.
### Actual Behavior

The transition is aborted.

**Comment by averas** [comment]
As it looks the following ops just need to check for interactivity:

https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/bind_handlers.js#L46
and
https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/bind_handlers.js#L74

**Comment by mourner** [comment]
@averas a more general question is should we just not add [any of these event handlers](https://github.com/mapbox/mapbox-gl-js/blob/38ecfd37c233a34434fff835e28da36f94fa1720/js/ui/bind_handlers.js#L29-L39) if `interactive` is `false`?

**Comment by averas** [comment]
@mourner I thought of that as well and and it might be that some of them could be completely removed if the map is in non-interactive mode. But I can imagine scenarios where you still want the mouse events fired for other programmatic actions to take place. Say that you want the map to be completely non-interactive, but you still want to be able to have your application act on clicks on it.

**Comment by mourner** [comment]
@averas yeah, sounds fair. We'll welcome a PR with a fix then :)
