### ISSUE TITLE
Skip style validation when loading a style from mapbox.com

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3152]
In looking into #2991, I noticed that overall, style validation consumes a non-neglible amount of resources at startup. In addition to #3149 and #3151, for styles loaded via mapbox.com APIs, we should skip validation entirely, because the APIs themselves enforce validity.

**Comment by ekelleyv** [comment]
Could this be implemented as a setting (rather than caring about tile domain)? 

Add something like `skip_style_validation` to map instantiation that defaults to False, but can be set to True if the user is certain their styles are valid.

**Comment by lucaswoj** [comment]
Perhaps we could sniff for a value like `style.metadata.skipValidation`

**Comment by averas** [comment]
I like @lucaswoj's proposal. That way an application (such as my own) that switches client side styles frequently can skip style validation as well. Perhaps it even would be possible to have the style validation process cache its own outcome via a property on the style in the line of <code>style.metadata.isValid</code> which would be removed upon any mutation on the style. That way style validation wouldn't have to be carried out on non-mutated styles.

**Comment by averas** [comment]
I realised my own proposal wouldn't work for any mutations you would to on the style object directly, but I still like the idea that clients can skip validations at their own will.

**Comment by jfirebaugh** [comment]
How about making it an API option, rather than a metadata option? `map.setStyle(..., {validate: false})`

**Comment by averas** [comment]
@jfirebaugh That would work, but as I understood your initial proposal you would like to have official Mapbox styles skip validation automatically, which perhaps is trickier if not part of the style.

**Comment by lucaswoj** [comment]
Another approach would be to have "development mode" (validate everything) and "production mode" (skip all validations) settings at the global level.

**Comment by jfirebaugh** [comment]
I think we want a granular option like `{validate: false}`.

* The default for `setStyle` (if no `validate` option is present) can depend on the style URL (disabled for `mapbox://` URLs).
* ...but `setStyle` can pass `{validate: false}` to the methods to which it delegates, fixing #3151.
* ...but subsequent user-driven calls to those same methods can validate by default, no matter what the style URL is.
* Users can pass `{validate: false}` for performance-critical calls they are sure are valid, and keep it in place in general for safety.
* Workers can always pass `{validate: false}`, fixing #3149.

**Comment by Bernoulli-IT** [comment]
> 
> 
> Could this be implemented as a setting (rather than caring about tile domain)?
> 
> Add something like `skip_style_validation` to map instantiation that defaults to False, but can be set to True if the user is certain their styles are valid.

The other way around I assume? ;) Set to false if the user is uncertain...
