### ISSUE TITLE
Large images slowing down rendering of map

### ISSUE THREAD

**Issue by lewisj** [mapbox/mapbox-gl-js#3164]
Very large images(5000px X 3000px) cause the map to slow down when you pan around the map.

Throws this console error [.Offscreen-For-WebGL-0621F3E0]GL ERROR :GL_OUT_OF_MEMORY : glTexImage2D: 

**mapbox-gl-js version**:v0.23.0
http://codepen.io/anon/pen/yaNRER

### Steps to Trigger Behavior

 1.Load large image into map
 2.Pan around the map
 

### Expected Behavior
Image displays correctly
### Actual Behavior
Maps slows down

**Comment by mourner** [comment]
I'm not sure we want to support this case — the only way to fix this is probably splitting the image into tiles on the client, and it's a big effort, while a proper approach would be to convert to tiles in the first place (e.g. by uploading a GeoTIFF to Mapbox Studio).

**Comment by mourner** [comment]
Not actionable at this time, so closing.

**Comment by jfirebaugh** [comment]
> GL ERROR :GL_OUT_OF_MEMORY : glTexImage2D

This was probably the issue noted in https://github.com/mapbox/mapbox-gl-js/pull/3353#issuecomment-253206377, and fixed by that PR.
