### ISSUE TITLE
Build a CLI-based benchmark runner

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3166]
Having a CLI-based benchmark runner which works on our CI server would allow us to run benchmarks more often and get more consistent results. 

Some techniques that may be useful:
- stub out WebGL with performance penalties
- use JSDom to simulate the DOM

**Comment by lucaswoj** [comment]
Within the scope of this work, it would be wise to run benchmarks during unit tests to ensure no exceptions are thrown and some basic sanity tests pass.

**Comment by jfirebaugh** [comment]
Our current benchmarking system is serving our needs fairly well. A CLI-based runner might be useful, but doesn't seem like something we're likely to invest in the the short to medium term. In the interest of keeping our issue count manageable, I'm going to close this one.
