### ISSUE TITLE
support fontsize as function for placement

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#317]
If the fontsize increases a lot as you zoom in, then just using the largest fontsize during placement isn't good enough. It adds too much padding around labels and reduces density.

placement with `"fontSize": 40`
![](https://github-camo.global.ssl.fastly.net/042510244a9b8855c7fcd7fd76622eedb51bafd4/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f75706c6f6164732e686970636861742e636f6d2f38313833322f3539313937342f4c436f58694155665a53736153697a2f75706c6f61642e706e67)

placement with `"fontSize": 20`
![](https://f.cloud.github.com/assets/1421652/2300498/45f20188-a0f4-11e3-80ba-5987d23e64fa.jpg)

**Comment by mourner** [comment]
Done with #361
