### ISSUE TITLE
Restore "browserify" property to package.json

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3175]
9fd707ab869dc960fd23c4b3a9e1ebd215638db4 removed the `"browserify"` property from package.json. This means that downstream packages that include mapbox-gl-js in their bundle will not have asserts removed as expected.

We should restore this section to package.json. Additional transforms that are desirable for downstream bundles (e.g. #3174) should also go in this section.

cc @mourner

**Comment by mourner** [comment]
Agreed, I didn't think about downstream use case when removing those.
