### ISSUE TITLE
Composite error

### ISSUE THREAD

**Issue by bsudekum** [mapbox/mapbox-gl-js#3188]
**mapbox-gl-js version**: `v0.23.0`

### Steps to Trigger Behavior

 1. Load [this page](https://api.mapbox.com/styles/v1/pveugen/cit4av2fh00752ymgv9zszqfk.html?title=true&access_token=pk.eyJ1IjoicHZldWdlbiIsImEiOiJzS3V3cHpZIn0.H87ssrLbkHEoPhAHjvxRgA#2.87/39.32/-27.13)
 2. Open console
 3. View error

### Expected Behavior

 Load without errors

### Actual Behavior

Error:

```
Error: Source layer "output-0u6rek" does not exist on source "composite" as specified by style layer "output-0u6rek"(…)
```

/cc @lucaswoj @samanpwbb @pveugen

**Comment by pveugen** [comment]
`output-0u6rek` is a Tileset that no longer exists in my account.

I uploaded the tileset, added it to map and later removed the tileset. The reference in my map still exists:
![image](https://cloud.githubusercontent.com/assets/596618/18552320/30846120-7b5c-11e6-8133-b084584992d6.png)

**Comment by mourner** [comment]
Isn't this more of an api-styles issue rather than something in gl-js?

**Comment by mourner** [comment]
Or Studio. Definitely not GL JS related — it correctly reports that the tiles it loads don't have the layer that's referenced in the style.
