### ISSUE TITLE
Need a way to run an individual benchmark

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3191]
If you're debugging a new benchmark, or iterating on performance improvements that will only affect a single benchmark, it's tedious to wait for all the others to complete.

The benchmark page should support URLs with an anchor like `/bench/#geojson-setdata-large`, or some equivalent means to run only a single benchmark.

**Comment by lucaswoj** [comment]
[The URL scheme you suggest is already supported](https://github.com/mapbox/mapbox-gl-js/blob/master/bench/README.md#running-benchmarks). Please re-open if you've tried it and it isn't working for you.
