### ISSUE TITLE
Link to individual benchmarks in the sidebar

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3192]
Followup to #3191. To better surface the ability to run individual benchmarks, the names in the sidebar should be links that go to the appropriate anchor, running that benchmark in isolation.

**Comment by lucaswoj** [comment]
Are you suggesting that clicking a sidebar link will re-run a benchmark in isolation in addition to or instead of scrolling to it? Could we put that functionality behind a separate `Rerun` button instead?

**Comment by jfirebaugh** [comment]
I'm not wedded to any particular UI -- I just want a means of navigating to an individual benchmark run that doesn't require manual URL editing (and therefore knowing what the URL format is).
