### ISSUE TITLE
Check map rendering in ReactJS on Win10/Chrome

### ISSUE THREAD

**Issue by Fles** [mapbox/mapbox-gl-js#3199]
Chrome/53.0.2785.101 on Windows 10 
[jsfiddle](https://jsfiddle.net/d00tzfn5/)
[Image preview](http://i.imgur.com/KEs0nKD.png)

**Comment by mourner** [comment]
1. Does it only look like this when wrapped in React, and fine without it?
2. What happens if you change `bright-v8` to `bright-v9`?

**Comment by Fles** [comment]
1. Most googled "fiddle mapboxgl" examples are broken! e.g. [this](http://fiddle.jshell.net/chk1/0h6yz1pe/) one have same issue! But [this](https://jsfiddle.net/u7cg0bpa/) looks good.
2. Same thing (broken render)

**Comment by mourner** [comment]
The one that looks good according to your comment is using the latest version (0.23). All others are not — the one in the report is 0.18, the other one mentioned is 0.12. If there was an issue, it was apparently fixed. Unless you can reproduce this with latest version.
