### ISSUE TITLE
setMaxBounds() causes weird behaviour

### ISSUE THREAD

**Issue by gmaclennan** [mapbox/mapbox-gl-js#3214]
**mapbox-gl-js version**: 0.23.0

### Steps to Trigger Behavior

 1. Create a basic map
 2. var bounds = map.getBounds()
 3. map.setMaxBounds(bounds)

### Expected Behavior

Map should be restricted to within the current map view.

### Actual Behavior

Map jumps around all over the place and flashes.

**Comment by jfirebaugh** [comment]
Probably a duplicate of #3081. Can you check if it works correctly in master?

**Comment by gmaclennan** [comment]
Yes, that was it. Fixed in 0.24.0
