### ISSUE TITLE
Mouse stuck to map while panning

### ISSUE THREAD

**Issue by martinrisseeuw** [mapbox/mapbox-gl-js#3215]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Go to [http://martinr.nl/lab/locator_v3/](http://martinr.nl/lab/locator_v3/) in safari
 2. Start panning the map
 3. Keep trying till the map sticks to your mouse

### Expected Behavior
The user should be able to drag pan the map bij holding the mouse. When the click is released is should detach from the map.

### Actual Behavior
Sometimes in safari the map sticks to the mouse when panning. This can only be undone by double clicking on the map.

**Comment by lucaswoj** [comment]
It looks like exceptions from https://github.com/mapbox/mapbox-gl-js/issues/2822 are preventing event listeners from running. This bug has been fixed in the latest release.

**Comment by lucaswoj** [comment]
Implementing this feature will mitigate the problem: https://github.com/mapbox/mapbox-gl-js/issues/2891
