### ISSUE TITLE
Rendering markers in view

### ISSUE THREAD

**Issue by martinrisseeuw** [mapbox/mapbox-gl-js#3216]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Go to [http://martinr.nl/lab/locator_v3/](http://martinr.nl/lab/locator_v3/) in safari
 2. Start panning the map
 3. Check the list on the left side

### Expected Behavior
The user should be able to drag pan the map bij holding the mouse. While doing so it should update the list with the markers (not clusters) in the current view. 

### Actual Behavior
When the user starts zooming and panning the list seems to update irregularly. it seems it doesn't render the correct items on different zoom levels while panning.

**Comment by lucaswoj** [comment]
Please provide a minimal test case that demonstrates the bug and re-open this issue. We do not have the domain knowledge to debug your website.
