### ISSUE TITLE
Fire "mouseover" event

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3217]
We fire "mousemove" events and "mouseout" events but no "mouseover" events. http://stackoverflow.com/questions/39563365/cannot-seem-to-get-mouseover-event-to-work-with-mapbox

**Comment by peterqliu** [comment]
@lucaswoj does `mouseover` fire when the cursor moves over the map itself, a specific layer, a specific source feature, or specific rendered feature? If the former, that sounds the same as `mousemove`. If the others, does that also require us to specify which layer/features on which to bind the listener?

**Comment by lucaswoj** [comment]
`mouseover` (like `mouseout` and `mousemove`) fires when the cursor moves over the map itself. [`mouseover` is different than `mousemove`](http://www.w3schools.com/jquery/tryit.asp?filename=tryjquery_event_mouseenter_mouseover).

**Comment by ryanhamley** [comment]
This was closed by #6000
