### ISSUE TITLE
Upgrade to 0.24.0 causes errors

### ISSUE THREAD

**Issue by timiyay** [mapbox/mapbox-gl-js#3226]
**mapbox-gl-js version**: 0.24.0

### Steps to Trigger Behavior

 1. install `mapbox-gl-js` 0.24.0
 2. try to load an existing web app with a `mapbox-gl-js` map

### Expected Behavior

Everything works as expected, as no breaking changes were advertised in the GH release.

### Actual Behavior

1. `mapboxgl.version` returns `0.23.0`, so there's something going on with the `dist` build.

2. my source layers are now returning a wad of `404 Not Found` console errors if they're not in the current map bounds, which wasn't happening in version 0.22.x

3. my existing code using `queryRenderedFeatures` now throws an exception:

```js
const features = map.queryRenderedFeatures({
  layers: this.get('myLayerNames').map((layer) => { return layer.name; }),
});

// TypeError: Cannot read property 'feature' of undefined
//     at FeatureIndex.filterMatching
//     at FeatureIndex.query
//     at Object.exports.rendered
//     at Object.queryRenderedFeatures
//     at queryRenderedFeatures
```

Happy to break this into multiple tickets, after initial maintainer feedback.

**Comment by jfirebaugh** [comment]
> Happy to break this into multiple tickets, after initial maintainer feedback.

Yes, please always file separate issues. Also, when possible please provide self-contained examples that replicate the issue you are reporting. Thanks!

**Comment by timiyay** [comment]
OK i'll reopen tickets when I have time to create repros. This issue was posted during a 30-minute spike to see if I could upgrade to 0.24.0 without any breakages. Unfortunately I fell short.
