### ISSUE TITLE
Refactor benchmark suite to collect statistically significant results

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3237]
> Note that map-load benchmarks pretty much always has the branch time much lower than the master one, making this particular benchmark not very useful. Maybe it's because V8 warms up on the first run.

https://github.com/mapbox/mapbox-gl-js/pull/3224#issuecomment-248438078

cc @mourner @jfirebaugh

**Comment by jfirebaugh** [comment]
Can we use [Benchmark.js](https://benchmarkjs.com/)? It handles repeating the benchmarked code until it's able to collect a statistically significant result.

**Comment by lucaswoj** [comment]
@jfirebaugh Sounds like a good fit! I'll look into it.

**Comment by lucaswoj** [comment]
After toying with this a little, I think using `benchmark.js` specifically is more trouble than its worth. `benchmark.js` does not work well with asynchronous  setup / teardown or non-time-based tests. We should be able to implement our own stat sig metrics.
