### ISSUE TITLE
Data driven style Geojson, LineString

### ISSUE THREAD

**Issue by primozs** [mapbox/mapbox-gl-js#3242]
For the example applying style for feature collection of lines works only for zoom levels > 9 cca. From zoom level 0 - 9 some lines are hidden.
http://codepen.io/primozs/pen/VKPbwK
https://primozs.github.io/files/trackfclines.js

### Expected Behavior
Show lines on all zoom levels.

### Actual Behavior
All lines are displayed only after zoom level 9.. cca

Applying style feature collection of points works nicely for all zoom levels:
http://codepen.io/primozs/pen/JREWQo
Example data
https://primozs.github.io/files/trackfcpoints.js

It would be nice if it could be possible to filter style data not only by feature property but also position array custom values: pos[2], pos[3]
http://codepen.io/primozs/pen/zKNkZQ
Example data
https://primozs.github.io/files/track.js

Would it be possible to somehow apply style or filter by feature property of type array?
Example data:
https://primozs.github.io/files/trackproparray.js
Cheers

**Comment by mourner** [comment]
GeoJSONSource filters out very small polylines on lower zoom levels, and this depends on the value of the `tolerance` option (0.375 by default). If you set it to `'tolerance': 0.001` for example, everything displays fine in the codepen provided.

**Comment by primozs** [comment]
@mourner thank you for tolerance suggestion.

**Comment by primozs** [comment]
@mourner 
Normally you would define layer styles on feature properties per feature.
```
// beside feature properties to be able to specify which value to take from single position array  
filter ['<', 'coordinates[2]',  1500]
would be the same as
filter ['<', 'altitude',  1500]
{
      "type": "Feature",
      "properties": {
        "altitude": 1474,
        "time": 1434007104000
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          14.009383333333334,
          46.2311,
          1474,
          1434007104000
        ]
      }
}
```
It would be useful to be able to define filters and styles per feature geometry position.
```
// run trough all positions in geometry instead trough all features
'line-color': {
    'by': 'coordinates'  // run trough all geometry positions
    'property': 'altitude', // take value from property array
    // or 
    'by': 'coordinates'
    'coordinates':  2, // read value from position index 2
     'stops': [
          [0, 'blue'],
          [500, 'cyan'],
          [1000, 'lime'],
          [1500, 'yellow'],
          [3000, 'red'],
          [20000, 'pink']
     ]
},

{
      "type": "Feature",
      "properties": {
        "altitude": [
         1, 2, 3, 4
        ],
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [
            14.009383333333334,
            46.2311,
            1,
          ],
          [
            14.009383333333334,
            46.2311,
            2
          ],
          [
            14.009383333333334,
            46.2311
           3
          ],
          [
            14.009383333333334,
            46.2311,
           4
          ]
        ]
      }
    },
```
Could either one of these be a feature?

**Comment by mourner** [comment]
@primozs no, I don't think this is technically feasible. You'll have to break it up into multiple features manually.

**Comment by primozs** [comment]
@mourner Ok, Cheers
