### ISSUE TITLE
Document "remove" event 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3246]
Per https://github.com/mapbox/mapbox-gl-js/issues/2232#issuecomment-249243876 we need to document or remove the "remove" event 

http://github.com/mapbox/mapbox-gl-js/blob/24f2135f058372bd7906e3c09148c92c8ffebef0/js/ui/map.js#L1088

**Comment by jfirebaugh** [comment]
Added in 9def6df1f98222c068813dfcd56f8b50fa553bce. Is it used anywhere? I couldn't find any uses.

**Comment by jfirebaugh** [comment]
Oh, [here](https://github.com/mapbox/mapbox-gl-js/blob/9def6df1f98222c068813dfcd56f8b50fa553bce/bench/lib/create_map.js#L23-L23).

**Comment by colleenmcginnis** [comment]
fixed in #3295
