### ISSUE TITLE
Blurry marker pop-ups on non-retina screens 

### ISSUE THREAD

**Issue by noemiwalzebuck** [mapbox/mapbox-gl-js#3249]
Capturing here that @mollymerp and I are talking to a user experiencing blurry pop-ups on non-retina screens using GL JS. They're specifically seeing this in the React app they're building (see `Steps to Trigger Behavior` below) but Molly's seen this before in other settings. 

![blurry](https://cloud.githubusercontent.com/assets/16309484/18800689/3461d9a2-8193-11e6-9eec-e2223194e2cd.jpg)

### Steps to Trigger Behavior

 1. Using Studio
 2. Using Mapbox GL via NPM (building a React app)
 3. Using custom HTML/React components for markers; displaying dynamic text/HTML from an API

### Expected Behavior

Non-blurry pop-ups

### Actual Behavior

Blurry pop-ups

### Action items

@mollymerp - can you please link your fix PR here when you have it up?

**Comment by lucaswoj** [comment]
Per https://github.com/mapbox/mapbox-gl-js/pull/3258#issuecomment-249975324 we are not going to implement a workaround for this browser bug. We recommend that upstream users ensure their popups are of an even numbered pixel width to work around this bug.
