### ISSUE TITLE
Popups

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#325]
* [x] Implementation
* [x] Documentation
* [x] Example

We need an easy way to display some HTML info in a particular place, much like Leaflet does with the Popup class and methods.

**Comment by jfirebaugh** [comment]
Basic implementation is there. There are some features of L.Popup that I'm comfortable not supporting for now (or ever):

* `minWidth`/`maxWidth`/`maxHeight` options -- should be done with CSS if desired
* opacity transition -- should be done with CSS if desired
* having an open/close state that is separate from "on the map"/"removed from the map"
* `map.openPopup()`/`map.closePopup()`

Features we might want to add:

* `offset` option
* `autoPan` and `keepInView` options -- but I'd rather support auto-anchoring the popup at the left, top, or right sides depending its position relative to the viewport. In general I think that's a better feature to have from a UX perspective. Having the map pan when a popup opens is often an annoyance.
* specify content as DOM node
* `open`/`close` events (except rename them `add`/`remove`)

**Comment by mourner** [comment]
Yeah, sounds good. I'm up for auto-anchoring, although `autoPan` would still be useful, it would just not pan as much with auto-anchoring — just a little in some cases like popup in a corner.

**Comment by mourner** [comment]
Or we could do something like http://erictheise.github.io/rrose/ — anchoring to 6 sides.

**Comment by jfirebaugh** [comment]
Yeah, the rrose behavior is what I had in mind. I wonder if there's any way to do it with pure CSS.

**Comment by ivanakimov** [comment]
@jfirebaugh @mourner any plans to get `autoPan ` implemented? Couldn't find any open issues for it.
