### ISSUE TITLE
Custom SVG in Control elements

### ISSUE THREAD

**Issue by recound** [mapbox/mapbox-gl-js#3253]
I'd like to be able to change SVG for the zoom in, zoom out, and compass UI controls.

**Comment by mourner** [comment]
You can change the SVG by overriding this CSS code: https://github.com/mapbox/mapbox-gl-js/blob/master/dist/mapbox-gl.css#L73-L92

**Comment by recound** [comment]
Thanks for cooperation. I suppose, the solution assumes to fork my changes in separate repo?

**Comment by mourner** [comment]
No, you can just override `background-image` with external CSS.
