### ISSUE TITLE
Mapbox Studio Custom Tiles not working

### ISSUE THREAD

**Issue by rulsberger** [mapbox/mapbox-gl-js#3254]
**mapbox-gl-js version 0.24.0**:

I am creating a webmap using MapboxGL.js and just updated from 0.21.0 to 0.24.0 for the scale bar functionality. I am using custom vector tiles that I generated using Mapbox studio and rendering information client side with geojson. However, after updating to the most recent release I am now getting the following error:
>Uncaught TypeError: Cannot read property 'advance' of undefined

Some additional testing found that Mapbox styles such as Outdoor do not throw any errors. 
My tiles end up looking like so: 
![image](https://cloud.githubusercontent.com/assets/8922393/18848179/1a38b5c2-83e2-11e6-9922-606e0e82fcc5.png)

From the same studio account using Mapbox's Outdoor Style (same access token):
![image](https://cloud.githubusercontent.com/assets/8922393/18848348/bbc15e9e-83e2-11e6-82e1-96640e91a612.png)

### Steps to Trigger Behavior

 1. Using Customized Studio Tiles
 2. Draw Map using Custom Tiles via MapboxGL JS
 3. AddLayers from geojson over 

### Expected Behavior
Customized Vector Tiles from Studio would be fetched and drawn before adding additional geojson layers client side.
### Actual Behavior
Vector Tiles are unable to be rendered

**Comment by peterqliu** [comment]
@rulsberger this is hard to debug, without seeing code. Can you reproduce this on something like jsfiddle.net or bl.ocks.org?

**Comment by rulsberger** [comment]
@peterqliu Thanks!

This should have enough code to reproduce the error: https://jsfiddle.net/rulsberger/rezengjL/2/#&togetherjs=nowiHRrO7o

**Comment by peterqliu** [comment]
👍  was able to reproduce this error (also viewable in the [style page](https://api.mapbox.com/styles/v1/logos-barry/cipfstzum0000bam5ecee8id3.html?title=true&access_token=pk.eyJ1IjoibG9nb3MtYmFycnkiLCJhIjoidkNnYk1PcyJ9.iD3EXGR2HZ5PYkWMAacjzw#8.13/37.5565/39.0632) ), and looks like a regression in v0.24.0. Not experienced in Studio, as it's currently on v.0.23.0.

Tricky to debug this one, as the error points to a blob and there isn't a stack trace

**Comment by peterqliu** [comment]
Tracked the bug to this line https://github.com/mapbox/mapbox-gl-js/pull/3179/files#diff-b3089558a25dee1e74f59aa1829490e4R98

cc/ @mourner

**Comment by mourner** [comment]
Yep, seems like a regression caused by my PR. I'll fix this on Friday.

**Comment by mourner** [comment]
This bug triggers in tiles that have text features that end with a `\n`:

![image](https://cloud.githubusercontent.com/assets/25395/19000119/8b141506-8749-11e6-959e-fe5a36498acb.png)

Submitting a PR with a fix.
