### ISSUE TITLE
Memory usage increases even after map.remove()

### ISSUE THREAD

**Issue by jnorris441** [mapbox/mapbox-gl-js#3264]
**v0.24.0**:
### Steps to Trigger Behavior
1. Create a map 
2. remove the map with map.remove()
3. repeat many times, memory usage will continue to increase

This fiddle loads a map and lets you reload it. Watch the heap as you reload a bunch of times:
https://jsfiddle.net/jnorris441/24rgc7L4/2/

Screenshot after 10 reloads http://i.imgur.com/76PZUXb.png
### Expected Behavior

map.remove() should hopefully release memory and let you create maps indefinitely
### Actual Behavior

Memory usage increases. Not a huge deal on a desktop but this crashes tabs on mobile Safari and Chrome on Android after a few reloads.

**Comment by wandergis** [comment]
I have confused with this problem for a long time. #2607  #3095

**Comment by INRIX-Jonny-Sooter** [comment]
+1 this issue is still unresolved more than a year later. Map.remove() sure sounds like a silver bullet, but the heap continues to grow. This causes mobile devices to sure crash.

**Comment by Mariusun** [comment]
Update, Mapbox v0.44.2: This issue seems to be fixed in Chrome, but not in Safari (v11.1) or Firefox (v59.0.2).

**Comment by aryzing** [comment]
I'm using Mapbox GL through react-map-gl, and I'm experiencing heavy memory leaks. Even calling `remove()` does not clear up memory.

Versions used:
* Mapbox GL: 0.53.0
* React Map GL: 4.1.1
