### ISSUE TITLE
pinch zooming slow with lots of markers

### ISSUE THREAD

**Issue by jbhatab** [mapbox/mapbox-gl-js#3266]
**mapbox-gl-js version**: .24
### Steps to Trigger Behavior
1. Go to https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/ for lots of markers
2. Go to https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/ for few markers
3. Go to https://www.mapbox.com/mapbox.js/example/v1.0.0/filtering/ for mapbox js without GL
### Expected Behavior

Super smooth pinch zooming with mapbox GL for any marker count. 
### Actual Behavior

With lots of markers, mapbox GL seems very clunky when pinch zooming with a mac touchpad.

I'm on the latest version of chrome with a powerful macbook pro.

**Comment by mourner** [comment]
I can't reproduce this on the latest Chrome (v53) with a mid-2012 Macbook Pro — it pinch-zooms smoothly without performance issues on all three maps.

**Comment by jbhatab** [comment]
@mourner It just seems that the pinch zoom on the normal js vs the GL js is a lot smoother. Are you really not noticing it because I tested this on multiple macs?

I can record a video because it's the only holdback from me using GL

**Comment by jfirebaugh** [comment]
Is this still reproducible?

**Comment by jbhatab** [comment]
Seems to not be an issue anymore!
