### ISSUE TITLE
Make adding GeoJSON easier (skipping style modifications)

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#327]
Make it dead easy to add GeoJSON data to LLMR without forcing the user to set up buckets/structure/styles etc. Maybe set up default ones for cases when GeoJSON id is not specified.

**Comment by jfirebaugh** [comment]
I'm pretty happy with the current gl-js API: https://github.com/mapbox/mapbox-gl-js/blob/00d12c53d2aee008ff4362f515279665e211cb3b/debug/site.js#L15-L28.

The last thing I think we should do here is add a placeholder layer with id `labels` to all the example styles that doesn't render anything but can be used to do `map.addLayer({...}, "labels")`.

**Comment by mourner** [comment]
Yeah, looks pretty good now.
