### ISSUE TITLE
possible rendering issue with upcoming core style updates

### ISSUE THREAD

**Issue by natslaughter** [mapbox/mapbox-gl-js#3275]
While staging the updated v9 and new v10 core map styles in api-styles, there appeared to be a rendering issue for road data with a geometry type filter `point`. 

With the `level_crossing` and `turning_circle` classes, some points were receiving a name label, and some were not. Those that received a label were rendered with the desired icon, and those without a label had no icon. 

It seemed that a potential reason why some points received a label and others did not was proximity to other, similar points. Clusters of these points received no labels whereas the lone point did. 

![level-crossing-1](https://cloud.githubusercontent.com/assets/16616543/18971395/e5587026-8662-11e6-921d-a04f003a7254.png)

![turning-circle-1](https://cloud.githubusercontent.com/assets/16616543/18971416/fc92c8ae-8662-11e6-8966-cf2188f39631.png)

@ajashton and @ian29 will be able to speak more accurately and effectively to the details, but the cartography team was hoping this issue could be resolved for the next gl-js release. In two of our new styles - outdoors-v10 and streets-v10 - there is a new `level_crossing`, and it would be great to see all of them if possible. 

cc @xrwang

**Comment by ajashton** [comment]
The problem comes up when there are multiple points of the same type and class in one tile (including the buffer area). To keep tile sizes compact, the queries for most layers in Mapbox Streets include a [ST_Collect](http://postgis.net/docs/ST_Collect.html) that groups together any geometries that have identical data properties (name, type, class, etc).

**Comment by mollymerp** [comment]
I'm not sure if I fully understand the issue here. Was rendering unexpected only in the studio x-ray view? Did you try turning on the debug mode to see if your labels were getting removed due to collisions? 

@natslaughter

**Comment by ajashton** [comment]
In the screenshot above there is no difference between the points that have labels and the ones that do not, so they should all look the same in the x-ray view. But (more importantly) this is an issue in the main styling view as well - symbol styles (either icons or text) never appear for "multipoint"* objects. Styling them as a circle works, however.

\* I have been told our vector tiles do not encode "multipoints", but they do allow "multiple points as a single row / object" and I'm not sure what else to call that.

**Comment by jfirebaugh** [comment]
@natslaughter @ajashton Is this still a relevant issue?

**Comment by xrwang** [comment]
![img](https://media2.giphy.com/media/isxmSunZOVKfK/giphy.gif)

**Comment by jfirebaugh** [comment]
Turns out this was fixed in #3763.

![giphy](https://user-images.githubusercontent.com/98601/36927634-8f290f0c-1e33-11e8-8585-12cebeef9d13.gif)
