### ISSUE TITLE
Make attribution control mobile responsive

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#3284]
In mapbox.js, attribution is compressed to an `i` icon when the window is mobile-sized. we should implement this in Mapbox-GL-JS too. 

![screen shot 2016-10-03 at 10 19 53 am](https://cloud.githubusercontent.com/assets/2425307/19046634/20b7a342-8953-11e6-906c-a39131954d64.png)

**Comment by lennerd** [comment]
Thinking about making a PR for this. Wonder what the label `GL native parity` means?

**Comment by mourner** [comment]
@lennerd a PR would be very welcome! The label just means that an equivalent functionality is already there in Mapbox GL Native, and we just need to match it in GL JS.
