### ISSUE TITLE
Improve rendering of glyphs with thin strokes

### ISSUE THREAD

**Issue by rasagy** [mapbox/mapbox-gl-js#3286]
### Steps to Trigger Behavior

 Use a typeface with thin strokes (Calligraphic fonts like Gothic Ultra, Kingthings etc)
### Expected Behavior

Expect the type to be rendered with more detail (especially the thin strokes)
### Actual Behavior

Gothic Ultra:
<img width="899" alt="screenshot 2016-10-03 16 58 35" src="https://cloud.githubusercontent.com/assets/1117531/19053881/ce412ed4-898a-11e6-8c3d-c1b1e696ecf0.png">

Kingthings:
<img width="1142" alt="screenshot 2016-10-03 16 56 28" src="https://cloud.githubusercontent.com/assets/1117531/19053877/ca26b170-898a-11e6-847b-bcb5c736946a.png">

[Slippy map](https://api.mapbox.com/styles/v1/rasagy/cituiyq4w001e2jo1429rz0v6.html?title=true&access_token=pk.eyJ1IjoicmFzYWd5IiwiYSI6Ilk2ay1VMEEifQ.CJfn_CxDfwyN5xaVfx4jaw#2.9408102383974146/25.894280785503412/91.71820037540607/-0.15010402380585222)

**Comment by kkaefer** [comment]
also see https://github.com/mapbox/mapbox-gl-native/issues/137

**Comment by lucaswoj** [comment]
@rasagy You can read a little bit more about the way we render glyphs here: https://www.mapbox.com/blog/text-signed-distance-fields

**Comment by mourner** [comment]
Currently no plans to pursue this (see also discussion in https://github.com/mapbox/mapbox-gl-native/issues/137)
