### ISSUE TITLE
Text does not rotate by zoom level smoothly

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-gl-js#3289]
[Slippy map](https://api.mapbox.com/styles/v1/planemad/cisyfqlpf000i2xqof85bu0a4.html?title=true&access_token=pk.eyJ1IjoicGxhbmVtYWQiLCJhIjoiemdYSVVLRSJ9.g3lbg_eN0kztmsfIPxa9MQ#4.73/14.870/85.771)

**mapbox-gl-js version**: latest

### Steps to Trigger Behavior

 1. Set a text-rotate property of a label layer to change by zoom level

<img width="589" alt="screenshot 2016-10-03 20 09 19" src="https://cloud.githubusercontent.com/assets/126868/19061423/6f501032-89a5-11e6-824a-3dd315e30386.png">

### Expected Behavior
Smooth rotation of labels during zoom

### Actual Behavior
Labels rotation seems to be updating only at whole zoom levels. z5, z6, z7 etc
![untitled2](https://cloud.githubusercontent.com/assets/126868/19061375/21510198-89a5-11e6-83f7-dc1b59e844a5.gif)

**Comment by lucaswoj** [comment]
This is a known quirk that we should document clearly and make apparent in the Studio UI. Layout properties can only update on integer zooms. Recalculating layout properties is very expensive relative to paint properties. 

cc @scothis

**Comment by lucaswoj** [comment]
👉  https://github.com/mapbox/mapbox-gl-style-spec/issues/514
