### ISSUE TITLE
Failed to execute 'createObjectURL' on 'URL'

### ISSUE THREAD

**Issue by jaapster** [mapbox/mapbox-gl-js#3291]
Hi,

I just installed 0.25.0 and get the following error:

`web_worker.js:5 Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.`

That's `js/util/browser/web_worker.js`.

This does not happen in 0.24.0.

Maybe related to [#3239](https://github.com/mapbox/mapbox-gl-js/pull/3239)?

I'm building my app with webpack.

Any ideas about how to tackle this?

**Comment by jaapster** [comment]
If I change the `main` property in the mapbox-gl package.json from `js/mapbox-gl.js` to `dist/mapbox-gl.js` things work as expected.

**Comment by jfirebaugh** [comment]
Can you create a self-contained example on https://jsfiddle.net/ that demonstrates the issue?

**Comment by jfirebaugh** [comment]
> If I change the main property in the mapbox-gl package.json from js/mapbox-gl.js to dist/mapbox-gl.js things work as expected.

Oh, yes, you need to use the dist version for Webpack. See https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-other-module-systems

**Comment by mattp88** [comment]
We still experience this problem with 0.26.0.

**Comment by jfirebaugh** [comment]
@mattp88 Please open a new issue with a self-contained https://jsfiddle.net/ example.
