### ISSUE TITLE
Support for "circle"-type layers with geojson clustering

### ISSUE THREAD

**Issue by datadiver0x0** [mapbox/mapbox-gl-js#3292]
Currently, clustering only appears to be supported for point geometry features that are being rendered as "symbol"-type layers.  It would be much more flexible if the clustering feature could be expanded to accept circles.  I was not able to locate any documentation that specifies symbols only (the website simply refers to ["point features"] (https://www.mapbox.com/mapbox-gl-style-spec/#sources-geojson-cluster)), but a simple test of the current [clustering example] (https://www.mapbox.com/mapbox-gl-js/example/cluster/) modifying the unclustered layer to use circles:

    map.addLayer({
        "id": "unclustered-points",
        "type": "circle",
        "source": "earthquakes",
        "paint": {
          "circle-color": "#cab2d6",
          "circle-radius": 40
      }
    });
 
results in the following:
![screen shot 2016-10-04 at 11 40 25 am](https://cloud.githubusercontent.com/assets/14796218/19087644/a6569e02-8a27-11e6-9807-48d52cf241df.png)

Thanks for your consideration.

**Comment by jfirebaugh** [comment]
This is already supported -- in fact the example is using circle layers. Look lower down in the example:

```
        map.addLayer({
            "id": "cluster-" + i,
            "type": "circle",
            "source": "earthquakes",
            "paint": {
                "circle-color": layer[1],
                "circle-radius": 18
            },
            "filter": i === 0 ?
                [">=", "point_count", layer[0]] :
                ["all",
                    [">=", "point_count", layer[0]],
                    ["<", "point_count", layers[i - 1][0]]]
        });
```

The "unclustered-points" layer you're looking at is for when you're zoomed in and looking at individual unclustered features:

![image](https://cloud.githubusercontent.com/assets/98601/19088176/e8323a96-8a29-11e6-89ea-76450169ac54.png)

**Comment by datadiver0x0** [comment]
Sorry I was not sufficiently clear, @jfirebaugh.  It is the rendering of the **unclustered** points that I am concerned about, not the clusters.  I do not want to use symbols (aka markers) because of the limitations in sizing and coloring those entities.  Thx.

**Comment by jfirebaugh** [comment]
In that case, I think your modification will work as you expect if you add a filter on the unclustered layer: `["!has", "point_count"]`. That way, only features corresponding to unclustered points are rendered. (In the original, features corresponding to clustered points were included, but covered up by other layers. For clarity, I've updated the example to include the filter.)

**Comment by datadiver0x0** [comment]
Thanks, @jfirebaugh, that did indeed work for me.  I appreciate the help and the corrected analysis of the underlying problem.
