### ISSUE TITLE
Marker.setLngLat throws exception v0.25.1

### ISSUE THREAD

**Issue by chasenicholl** [mapbox/mapbox-gl-js#3293]
Marker.setLatLng options throws exception.  The error is ```options``` is undefined.
https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/marker.js#L155

A solution would be to check options first.
```
if (typeof options !== 'undefined' && options.roundPos) {
    pos = pos.round();
}
```

**v0.25.1**:

### Steps to Trigger Behavior

 1. Create a Marker
 2. marker.setLatLng
 3. observe error

### Expected Behavior
Marker position gets updated

### Actual Behavior
Exception is thrown

**Comment by jfirebaugh** [comment]
PR addressing this: https://github.com/mapbox/mapbox-gl-js/pull/3283

cc @mollymerp

**Comment by chasenicholl** [comment]
Ah I see this now. Thanks!
