### ISSUE TITLE
TypeError: Unable to get property 'concat' of undefined or null reference

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#3296]
**mapbox-gl-js version**:Master

### Steps to Trigger Behavior
Sorry I don't have exact steps to reproduce this. 
I run into this error message in console  at least a few times every day.  Typically when I get this error  map.addSource/addLayer etc stop working. (Refresh page  fixes everything).

"TypeError: Unable to get property 'concat' of undefined or null reference"

**Comment by jfirebaugh** [comment]
Can you please provide a JSFiddle? Or at least a complete stack trace? We're going to have a hard time going on just the error message.

**Comment by mb12** [comment]
I do not have steps to reproduce this. So I can provide you a JSFiddle.  I will copy paste the full stack trace next time I see it.  (I don't think it will be useful since it happens in a WebWorker). 
If someone can review the code to check for <obj>.concat calls that would be great.
Feel free to close the bug otherwise.

**Comment by lucaswoj** [comment]
Thanks for the report @mb12! Taking a quick look into this now.

## Potential `concat` Calls

Generated by`grep -rn "concat" js`.

### `js/render/painter/use_program.js:77:        defines = defines.concat('OVERDRAW_INSPECTOR');`

🚫 This does not happen in the worker.

### `js/source/worker_tile.js:220:            .concat(featureIndex_.transferables)`

🚫 This call will always be on an `Array` from `getTransferrables`.

### `js/source/worker_tile.js:221:            .concat(collisionTile_.transferables));`

🚫 This call will always be on an `Array` from `getTransferrables`.

### `js/source/worker_tile.js:248:        transferables: getTransferables(nonEmptyBuckets).concat(collisionTile_.transferables)`

🚫 This call will always be on an `Array` from `getTransferrables`.

### `js/symbol/mergelines.js:26:        mergedGeom[i][0] = mergedGeom[i][0].concat(geom[0]);`

🚫 If `mergedGeom[i][0]` was not an array, the previous line (`mergedGeom[i][0].pop()`) would have thrown an exception. 

### `js/symbol/mergelines.js:36:        mergedGeom[i][0] = geom[0].concat(mergedGeom[i][0]);`

✅ If any element in the `geometries` argument of `megelines` is null or undefined, the error described will be triggered.

## When will an element in the `geometries` argument of `megelines` be null or undefined?

There is a [single call site for `mergelines`](http://github.com/mapbox/mapbox-gl-js/blob/6d065cf299f50af0f8f23437d28ecabbf89ace34/js/data/bucket/symbol_bucket.js#L214-L215) which is in `SymbolBucket`. The `geometries` passed to this call of `mergelines` come from [`loadGeometry`](http://github.com/mapbox/mapbox-gl-js/blob/6d065cf299f50af0f8f23437d28ecabbf89ace34/js/data/load_geometry.js#L33-L34).

`loadGeometry` is guaranteed to always return an array or else it will throw an exception (`cannot read "length" of undefined`.

## Conclusion

More information is needed to diagnose this bug. Please re-open this issue when that is available. A stack trace would be helpful!

**Comment by mb12** [comment]
@lucaswoj  Thanks a lot for for the due diligence regarding concat review.
