### ISSUE TITLE
Improve the map link does not go to the right location

### ISSUE THREAD

**Issue by planemad** [mapbox/mapbox-gl-js#3299]
**mapbox-gl-js version**: latest

### Steps to Trigger Behavior

1. Goto [a GL style preview page](https://api.mapbox.com/styles/v1/rasagy/citw07bpz00682iolbbi27kjm.html?title=true&access_token=pk.eyJ1IjoicmFzYWd5IiwiYSI6Ilk2ay1VMEEifQ.CJfn_CxDfwyN5xaVfx4jaw#11.72/12.6671/80.0374).
2. Click `improve the map`

### Expected Behavior
https://www.mapbox.com/map-feedback/ page opens at the same map location

### Actual Behavior
The feedback page opens up at a zoomed out view of the world making it difficult to submit a report at the desired location. 

The link works correctly on [Mapbox JS](https://api.tiles.mapbox.com/v4/mapbox.streets/page.html?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpamV0Zms2ZzAwMGh0Zm01MDR3YmV2cHgifQ.m9a-_eKcMy9A6glxEtuj3Q#12/31.1173/33.8506)

**Comment by mollymerp** [comment]
fixed in #3356
