### ISSUE TITLE
map.loaded() always returns false when raster API returns 204 No Content

### ISSUE THREAD

**Issue by vicapow** [mapbox/mapbox-gl-js#3301]
**mapbox-gl-js version**: 0.25.1
### Steps to Trigger Behavior
1. Write a setInterval to load `map.loaded()`
2. Add an API that returns tiles with 204 No Content
### Expected Behavior

map.loaded eventually returns true
### Actual Behavior

map.loaded always returns false

**Comment by vicapow** [comment]
Here's a PR https://github.com/mapbox/mapbox-gl-js/pull/3302

**Comment by anandthakker** [comment]
Fixed in #3302
