### ISSUE TITLE
TouchEnd reported coordinates (e.lngLat) wrong on Android Chrome?

### ISSUE THREAD

**Issue by FDN73** [mapbox/mapbox-gl-js#3304]
Android: 5.0.1
Chrome: 53.0.2785.124

MapboxGL JS : "version":"0.24.0"

### Steps to Trigger Behavior

 1. simple map, add listeners to touchstart and touchend with console.log(e.lngLat) on both
 2. tap the map on a mobile phone and watch the coordinates with chrome remote debugging, or use an alert instead of console
 

### Expected Behavior
The two events should have almost equal coordinates
### Actual Behavior
The two events have different coordinates (the touchend is usually shifted up and left), example:
touchstart coords: LngLat(9.435743459690002, 45.642242729483655)
touchend coords: LngLat(9.425303808457613, 45.646926857999205)
I noticed this trying to implement a drag behaviour for markers - they would always end away from where I shifted them after release of the finger.
Using desktop events on desktop chrome works perfectly, using touch events on mobile does not (unless I'm doing something spectacularly wrong).

**Comment by FDN73** [comment]
Looking at the source code I found the potential problem:

```

    function fireMouseEvent(type, e) {
        var pos = DOM.mousePos(el, e);

        return map.fire(type, {
            lngLat: map.unproject(pos),
            point: pos,
            originalEvent: e
        });
    }

    function fireTouchEvent(type, e) {
        var touches = DOM.touchPos(el, e);
        var singular = touches.reduce(function(prev, curr, i, arr) {
            return prev.add(curr.div(arr.length));
        }, new Point(0, 0));

        return map.fire(type, {
            lngLat: map.unproject(singular),
            point: singular,
            lngLats: touches.map(function(t) { return map.unproject(t); }, this),
            points: touches,
            originalEvent: e
        });
    }
};
```

The difference with desktop event handling is the use of the **touches.reduce** function, I will try to understand what this function is doing to produce the **singular** variable - it seems that on a tap (where the finger leaving the screen does not change position too much) two different coordinates are produced on touchstart/touchend.

**Comment by lucaswoj** [comment]
Thanks for investigating this bug @FDN73! Keep on keeping on and let me know if you need any help.

Have you tested if this bug only affects Android Chrome and not, say, iOS? 

> I will try to understand what this function is doing to produce the singular variable

`singular` is an average of all the touch positions.

**Comment by FDN73** [comment]
Yeah sorry I'm not a javascript developer (more java and c/c++) - I've just looked at the docs for **reduce** and understood - another potential problem could be in mapbox-gl-js/js/util/dom.js
(sorry If I throw code around, I do it just in case someone more skilled in js than me spot the problem)
`exports.touchPos = function (el, e) {
    var rect = el.getBoundingClientRect(),
        points = [];
    for (var i = 0; i < e.touches.length; i++) {
        points.push(new Point(
            e.touches[i].clientX - rect.left - el.clientLeft,
            e.touches[i].clientY - rect.top - el.clientTop
        ));
    }
    return points;
};`

The el element is created here:

`exports.create = function (tagName, className, container) {
    var el = window.document.createElement(tagName);
    if (className) el.className = className;
    if (container) container.appendChild(el);
    return el;
};`

I suppose that when I add a movable icon through addLayer, a div gets created somewhere calling this create function?

In case of an icon, if small enough, could the points array be calculated very differently when I release the finger, due to the size of the icon?

I have only this android tablet at my disposal to test, sorry.
How can I test things with a non minified version of the library so I can check what's going on?

**Comment by FDN73** [comment]
Ok, found, solved and tested, it works perfectly. Check [https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/changedTouches] .
 The touchPos needs to be modified as follows:

`exports.touchPos = function (el, e) {
    var rect = el.getBoundingClientRect(),
        points = [];
    var touches = e.type === 'touchend'?e.changedTouches:e.touches;
    for (var i = 0; i < touches.length; i++) {
        points.push(new Point(
            touches[i].clientX - rect.left - el.clientLeft,
            touches[i].clientY - rect.top - el.clientTop
        ));
    }
    return points;
};`

Now, how should I proceed to submit this fix? Could there be some side effect I have not considered?
