### ISSUE TITLE
Collision debug disappears after zoom

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#3305]
**mapbox-gl-js version**: `master` (8fe56f5)
### Steps to Trigger Behavior
1. `map.showCollisionBoxes = true`.
2. Zoom to another integer level.
### Expected Behavior

Collision boxes are still present.
### Actual Behavior

Collision boxes disappear on other zoom levels.

**Comment by mollymerp** [comment]
I can't reproduce this on master @mourner. In the debug page if I check the `collision debug` box, scroll zoom a bit, and also call `map.setZoom(10)` I am still able to see the collision boxes even w a fresh `rm -rf node_modules && npm install`.
