### ISSUE TITLE
[.Offscreen-For-WebGL-0x7fae76876600]RENDER WARNING: there is no texture bound to the unit 0

### ISSUE THREAD

**Issue by evejweinberg** [mapbox/mapbox-gl-js#3312]
I'm loading an image layer and a video layer and they both generate the warning:
[.Offscreen-For-WebGL-0x7fae76876600]RENDER WARNING: there is no texture bound to the unit 0

I've seen this posted related to Three.js and someone said it was a Chrome bug, but that it was fixed. Any ideas why this is still happening? It nearly crashes my browser.

Thanks,
Eve

**Comment by jfirebaugh** [comment]
This was fixed in #3522.

**Comment by jaapster** [comment]
I still get this warning in v0.35.0

**Comment by denistsoi** [comment]
Also seeing this on v0.36.0

**Comment by lbud** [comment]
Thanks for the reports! If someone is able to provide a minimal [JSFiddle](https://jsfiddle.net/) that reproduces this issue, that would be helpful.

**Comment by jaapster** [comment]
I'll give it a shot

**Comment by denistsoi** [comment]
one thing i need to mention - not sure if @jaapster has this as well - I'm currently embedding `mapbox-gl-js` inside `ng 1.4.8` using `material-design` - it may be that: 

- warning is being thrown by initiating mapbox inside a directive
- or initiating mapbox within a div with column flexbox may be throwing this error

Haven't been able to reproduce the error within a blank jsfiddle - will continue to attempt

**Comment by jfirebaugh** [comment]
If this is reproducible in 0.39.1 or later, please open a fresh issue with a JSFiddle that demonstrates the issue.

**Comment by denistsoi** [comment]
Thanks for closing this @jfirebaugh - I don't think I'm able to reproduce since the original post.

**Comment by drewbo** [comment]
@jfirebaugh seeing this in `0.44.1`. Reproduction on a WMS layer here: https://jsfiddle.net/m77nkgme/1/
