### ISSUE TITLE
Make "dragstart", "dragend", "movestart", and "moveend" events emit an instance of "MapMouseEvent" or "MapTouchEvent"

### ISSUE THREAD

**Issue by ntilwalli** [mapbox/mapbox-gl-js#3315]
Demo: http://jsbin.com/lilulibogo/1/edit?html,console,output

Is that the intended behavior?  As it stands the docs indicate this is a `MapMouseEvent` which is supposed to have that property.  I can understand not including that info since the meaning of `lngLat` in the context of drag is unclear.  Users can always query the map to get the position if they want it.  Just wondering.

**Comment by lucaswoj** [comment]
Looking at the source, I can confirm that `dragstart` and `dragend` events do not attempt to attach any of the `MapMouseEvent` properties. http://github.com/mapbox/mapbox-gl-js/blob/6cc8ec766125bcbb060ae3083880f217248e0bb9/js/ui/handler/drag_pan.js#L100

We should fix!

**Comment by lucaswoj** [comment]
Until we get these events the way they should be, I've updated the docs to accurately describe how they are https://github.com/mapbox/mapbox-gl-js/pull/3321

**Comment by jfirebaugh** [comment]
I think @lucaswoj's fix above is the correct one. The `MapMouseEvent` or `MapTouchEvent` types are for mouse and touch events respectively; let's not try to overload them to apply to other events such as `drag*` and `move*`.
