### ISSUE TITLE
Transform 'pitch' getter should return in radians

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-js#3317]
This is the current behavior in GL native, which avoids extra conversions internally e.g. https://github.com/mapbox/mapbox-gl-js/blob/master/js/symbol/collision_tile.js#L41.

In that sense, conversions from radians to degrees are only made when necessary i.e. when returning pitch information from Map - see https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/map/map.cpp#L635-L637.

**Comment by jfirebaugh** [comment]
#1732
