### ISSUE TITLE
Fix z-fighting on overlapping fills within the same layer

### ISSUE THREAD

**Issue by tgecho** [mapbox/mapbox-gl-js#3320]
**mapbox-gl-js version**: 0.25.1
### Steps to Trigger Behavior
1. Add a geojson source with overlapping features and a fill layer
2. Adjust the pitch of the map
### Expected Behavior

The fill layers should stay smooth
### Actual Behavior

The fill layers flicker as the pitch changes and looks jagged when it's not moving. This happens in at least Chrome, Firefox and Safari

https://jsfiddle.net/tgecho/brhb9wng/
![image](https://cloud.githubusercontent.com/assets/49615/19197612/c9de3d7c-8c88-11e6-9642-d219c6996fa8.png)

**Comment by jfirebaugh** [comment]
This looks like the GL JS equivalent of https://github.com/mapbox/mapbox-gl-native/issues/6604.

**Comment by snkashis** [comment]
Yes, also happening for me in 0.26.0 with Chrome 54.0.2840.71.They are jagged during moves and also while static.

**Comment by gena** [comment]
I'm experiencing the same when the map is tilted: [![screen capture](https://img.youtube.com/vi/k5lWRefq96M/0.jpg)](https://www.youtube.com/watch?v=k5lWRefq96M) 

The map is here: [test map](https://api.mapbox.com/styles/v1/gennadiy/ciuwljd1d015u2hpbmoluv1qg.html?fresh=true&title=true&access_token=pk.eyJ1IjoiZ2VubmFkaXkiLCJhIjoiMm9WN3VWQSJ9.b9s_EXvxcqiAbaf5GzrEnA#3.21/-57.60/55.12/-36/60). The water polygons are based on the standard layers.

**Comment by nextstopsun** [comment]
Same issue here.

Do mapbox base maps also have this problem on overlapping landcover features?

<img width="679" alt="screen shot 2017-06-01 at 10 40 33" src="https://cloud.githubusercontent.com/assets/966321/26669548/fc06e7d4-46b6-11e7-93a6-bc276ff117a0.png">

**Comment by kermeat** [comment]
![image pasted at 2017-6-2 23-50](https://cloud.githubusercontent.com/assets/5646358/26744411/7da1b386-47ee-11e7-853a-c07d93c92915.png)

**Comment by nextstopsun** [comment]
Any news here? Everything looks great until you pitch the map. I hope feature rendering order won't become random when this gets fixed.

**Comment by jfirebaugh** [comment]
For some reason, translucent fill layers are currently drawn with the depth mask enabled (i.e. writing to the depth buffer during the translucent phase), which is inconsistent with every other layer type. If that's merely an accident, then we can disable the depth mask and fix this issue for translucent fill layers. I don't see any render test failures when doing so (well, there's one, but it's incidental and we'd fix it by just updating the fixture).

This wouldn't fully fix the problem -- opaque fill layers with a color that varies via a data-driven property, like in #3702, would still z-fight.

**Comment by nextstopsun** [comment]
@jfirebaugh Thanks for diving in this issue! I guess in most cases color is data-driven because there is "visually no" z-fighting when color of overlapping features is the same.
Do you think this could be fixed for data-driven coloured layers?

**Comment by jfirebaugh** [comment]
It would be more difficult to fix this for opaque data-driven color. The solution would have to involve one of the general techniques for solving z-fighting like adjusting the depth buffer precision (I think we already use the max though), adjusting the near/far clipping planes, using logarithmic depth buffering, or actually perturbing the z-coordinates of co-planar fill triangles in a way that doesn't affect the visual result other than fixing the fighting. Those would all be medium to large sized research projects.

**Comment by jfirebaugh** [comment]
It turns out that the fix in #9930 will resolve this issue for all kinds of fill layers. 🎉

**Comment by nextstopsun** [comment]
Really great news! 
@jfirebaugh Thanks, you rock as always!
Couldn't wait for a release, so tried this out on master and got some errors.
Not sure if this is related to this particular commit, but getting 
```
VM12703:83 Uncaught SyntaxError: Invalid or unexpected token
```
And 
```
Uncaught TypeError: Cannot read property 'has3DPass' of undefined
    at Painter.render (painter.js:300)
    at e._render (map.js:1557)
```
in Chrome. 

The former is quite a strange one but the latter seems to be related.

**Comment by indus** [comment]
big improvement :clap: - small regression :pensive: 
Im now getting a 1px overlap at the dateline for layered semitransparent layers:
![image](https://user-images.githubusercontent.com/2046274/30426480-81ac4770-994c-11e7-9491-c31fc6e20fb6.png)
I was trying this with v0.40.

**Comment by conect** [comment]
For 3D-extrusions z-fighting seems still to be there:
will there be a fix available?
![grafik](https://user-images.githubusercontent.com/1295174/38733137-1b47051c-3f21-11e8-93fc-45878e98a23f.png)

Thx.

**Comment by conect** [comment]
For 3D-extrusions z-fighting seems still to be there:
will there be a fix available?
![z-fighting](https://user-images.githubusercontent.com/1295174/38733186-44005b70-3f21-11e8-9022-c81a3ced9460.png)

Thanks.
