### ISSUE TITLE
Create a syntax for specifying custom sources in the style JSON

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3323]
If we are going to allow custom source types to be used in the style JSON, we should make sure the style JSON is completely self-contained. 

Strawman proposal:

```
{
    sourceTypes: {
        "topojson": "http://definately-not-xss.com/topojson.js"
    }
}
```

We may also choose to punt on this feature in the near term, pushing users to use the imperative `Map#addCustomSource` API

**Comment by jfirebaugh** [comment]
> We may also choose to punt on this feature in the near term, pushing users to use the imperative `Map#addCustomSource` API 

Given that this would be a style spec feature that can't be supported by a non-JS renderer, this might be the better long-term API too.

**Comment by lucaswoj** [comment]
That's a very good point that I hadn't considered.

**Comment by lucaswoj** [comment]
Let's punt on both this and #3004 for now.
