### ISSUE TITLE
autoPan for Popup?

### ISSUE THREAD

**Issue by ivanakimov** [mapbox/mapbox-gl-js#3325]
[MapboxGL Popup](https://www.mapbox.com/mapbox-gl-js/api/#Popup) does not seem to have an `autoPan` option like [L.popup](https://www.mapbox.com/mapbox.js/api/v2.4.0/l-popup/) does.
Any plans to add this? Seems like a super-useful feature (it's also mentioned [here](https://github.com/mapbox/mapbox-gl-js/issues/325#issuecomment-74810918))

**Comment by jfirebaugh** [comment]
No plans to implement `autoPan`. Mapbox GL popups implement the alternative mentioned in the issue you linked:

> I'd rather support auto-anchoring the popup at the left, top, or right sides depending its position relative to the viewport. In general I think that's a better feature to have from a UX perspective. Having the map pan when a popup opens is often an annoyance.

**Comment by ivanakimov** [comment]
Ah, I see. I guess I didn't think one was a replacement for the other.

I thought the `anchor` was responsible for position relative to coords (show popup at the top vs bottom), and the `autoPan` would actually move the map so the whole popup is visible on the screen.

Could you point me to the best way to implement something like this?

**Comment by lucaswoj** [comment]
> Could you point me to the best way to implement something like this?

That is a question better suited for StackOverflow than GL JS's issue tracker.

**Comment by andrewharvey** [comment]
> No plans to implement autoPan. Mapbox GL popups implement the alternative mentioned in the issue you linked:
>>I'd rather support auto-anchoring the popup at the left, top, or right sides depending its position relative to the viewport. In general I think that's a better feature to have from a UX perspective. Having the map pan when a popup opens is often an annoyance.

On small screens sometimes this isn't enough to keep the popup in the view. In this case moving the map would ensure the popup isn't partially hidden.

Though when screen sizes get that small, popups might not be the best design.

**Comment by ewirth** [comment]
I suppose if the popup is out of the border, that's just poor user-experience, and it's degrade the quality of the application against Leaflet.

> 
> 
> No plans to implement `autoPan`. Mapbox GL popups implement the alternative mentioned in the issue you linked:
> 
> > I'd rather support auto-anchoring the popup at the left, top, or right sides depending its position relative to the viewport. In general I think that's a better feature to have from a UX perspective. Having the map pan when a popup opens is often an annoyance.

**Comment by seekingtheoptimal** [comment]
Any hints on how to actually achieve this if needed? Like in my case, the popup is highly customized, has a portrait orientation kind of, while the map is wide but not too high. In my case it would actually be super useful to have such feature.
Options I can think of are either calculate the pixel <-> lat,long ratio and pan, or play with the setPadding() and flyTo() functions.
Any other suggestions? Thanks in advance.

**Comment by T-Spoon** [comment]
> I'd rather support auto-anchoring the popup at the left, top, or right sides depending its position relative to the viewport. In general I think that's a better feature to have from a UX perspective. Having the map pan when a popup opens is often an annoyance.

This is very situational - there are many cases where it's preferable to autopan, rather than having inconsistent placement for popups (which can be both ugly and more cognitive load for a user, since they don't know which direction the popup will show from).

I think this should be re-opened.

**Comment by TetianaBron** [comment]
njam, thank you very mach

**Comment by pacproduct** [comment]
@njam Thanks a lot, very useful.

For some reason I had to rework how the `popupClippedHorizontally` gets detected, like so:
```js
  const popupRelativeLeft = popupRect.x - mapRect.x;
  const popupRelativeTop = popupRect.y - mapRect.y;
  const popupClippedHorizontally = popupRelativeLeft < 0 || (mapRect.width - popupRelativeLeft - popupSize.width) < 0;
```

I'm not sure if it's because of how my elements are positioned... but using `left` as you do does not work in my case.
But the whole principle works great. Cheers!

----

The whole code I used, just in case it would be of any use to anyone:

```js
  const pan = [0, 0];
  const point = map.project(popup._lngLat);
  const popupSize = {
    width: popup._container.clientWidth,
    height: popup._container.clientHeight,
  };
  const popupRect = popup._container.getBoundingClientRect();
  const mapRect = map._container.getBoundingClientRect();

  // Center point horizontally to make the popup visible, if needed
  const popupRelativeLeft = popupRect.x - mapRect.x;
  const popupRelativeTop = popupRect.y - mapRect.y;
  const popupClippedHorizontally = popupRelativeLeft < 0 || (mapRect.width - popupRelativeLeft - popupSize.width) < 0;
  if (popupClippedHorizontally) {
    pan[0] = point.x - (mapRect.width / 2);
  }

  // Move point to the top to make the popup visible, if needed
  let popupClippedVertically = popupRelativeTop < 0 || (mapRect.height - popupRelativeTop - popupSize.height) < 0;
  if (popupClippedVertically) {
    pan[1] = point.y - ((mapRect.height - popupRect.height) / 2);
  }

  if (pan !== [0, 0]) {
    map.panBy(pan);
  }
```

**Comment by lauriselvijs** [comment]
From @pacproduct  response this is my way for left as well right overflow of popup
```js
          // left side overflow
          if (popupRelativeLeft < 0) {
            pan[0] = point.x - (mapRect.width + popupRect.width) / 2;
          // right side overflow
          } else if (mapRect.width - popupRelativeLeft - popupSize.width < 0) {
            pan[0] = point.x - (mapRect.width - popupRect.width) / 2;
          }

```
