### ISSUE TITLE
Investigate extruded fill-pattern pixel mismatch in render tests

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#3327]
I'm getting slightly different results in my locally produced expected render tests and CI's tests for extrude-fill-pattern tests: it seems the patterns are shifted a pixel or two. See `extrude-fill-pattern` [in the artifact](https://5250-8629417-gh.circle-artifacts.com/0/Users/distiller/mapbox-gl-js/node_modules/mapbox-gl-test-suite/render-tests/index.html) for the shift; diffs look like this:
![image](https://cloud.githubusercontent.com/assets/3170312/19204472/e7900838-8c91-11e6-9d49-c4c153f69d00.png)

Ticketing here as I'm going on vacation tomorrow and will investigate when I get back in two weeks.

**Comment by lbud** [comment]
This is also affecting _only some platforms_ on GL native ☠️ going to use this same ticket as the `ignored` reason for those tests.

**Comment by mourner** [comment]
Closing as stale.
