### ISSUE TITLE
Highlight doesn't work after re adding base layer 

### ISSUE THREAD

**Issue by KfirShainholtz** [mapbox/mapbox-gl-js#3330]
I'm using mapbox gl js v21. 0,
I've implemented a mechanism for toggling base layers, (satellite, basic etc). 
I have a basic style that includes every layer that I've mentioned and they are toggled by the zoom level. 

There is no support for toggling layers by external selection so I removed and added every layer 
from the map. When I do so, highlighting and bounding box selection doesn't work anymore. 
When the basic style is provided when the map initialized, selecting features colors them by setting data on another source with corresponding layer called 'selected-data', but when I remove all the base sources and layers (without removing selected-data source and layer), and re adding the user chosen base layer alone (just it, without toggling after a zoom level), by adding the source and the layer with the before option array set with every layer that is still on the map (static layers like selected data and layers that contains features), the selection doesn't color the selected features afterwards. 
Did anybody came across this problem?

**Comment by mourner** [comment]
Can you set up a minimal JSFiddle test case that reproduces the problem?

**Comment by KfirShainholtz** [comment]
Thanks for the quick reply mourner!

I'll try to explain in brief again, if I wouldn't be clear enough I'll make one (unfortunately the code will be reacheable only in three days).

I'm using the bounding box highlight on selection example, https://www.mapbox.com/mapbox-gl-js/example/using-box-queryrenderedfeatures/,

When I try to implement the toggle layers logic, I take the base layers, remove them and their sources (statelite layer and source, for example), then, I re-add the source and the layer, but I add the layer using the [before] option, which I fill with every layer that is still left, (for example, the 'counties' layer in the example above).

When the layer has been re-added, I can see the features (polygons, polylines etc) that was displayed earlier on the map, the base layer that I removed and re-added, but the functionallity of bounding box selection that paints the features selected in another color, is gone.

Once again, excuse me for the misinforming too much, but this is as far as I can explain right now.

Thank you in advance!

**Comment by mourner** [comment]
@KfirShainholtz thanks for the detailed explanation, but to be able to look into this, we need a http://jsfiddle.net/ test page that demonstrates this in practice — e.g. a sample map with a few buttons that trigger the bug you're describing.

**Comment by KfirShainholtz** [comment]
Well ok, I'll do it ASAP,
should I close the discussion for now?

**Comment by KfirShainholtz** [comment]
Hey everyone, 
I managed to fix the problem by instead of adding and removing sources and layers, now I'm just toggling the visibility of the static layers. 
Thank you!
