### ISSUE TITLE
extract text-size from feature

### ISSUE THREAD

**Issue by rvijgen** [mapbox/mapbox-gl-js#3331]
Is it possible to use a feature property for text size?
According to the documentation this can be done for text-field, but text-size requires a number.

I tried finding it in the source, but I'm a bit lost....

thanks,
Richard

**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1.
 2.
 3.

**Comment by mourner** [comment]
Currently property-based values for layout properties are not implemented. Tracking this feature in https://github.com/mapbox/mapbox-gl-js/issues/2431.
