### ISSUE TITLE
Add 'camera' argument to project/unproject methods on Map

### ISSUE THREAD

**Issue by ntilwalli** [mapbox/mapbox-gl-js#3343]
This request is related to https://github.com/mapbox/mapbox-gl-js/issues/3322

In mapbox.js there is a `zoom` argument on the map's `project`/`unproject` methods.  It would be quite useful if a similar argument was exposed on the map in Mapbox GL, making those methods consistent with each other.  It will help for people transitioning away from the JS lib to the GL JS lib.

**Comment by mollymerp** [comment]
@ntilwalli thanks for submitting your feature request. 

We would happily consider a Pull Request implementing this feature. If you need help getting started, just let us know 😊

**Comment by lucaswoj** [comment]
Expanding scope slightly: Let's try to add a full `camera` argument (a la #3583).

**Comment by jfirebaugh** [comment]
Let's actually consolidate this with #5687.
