### ISSUE TITLE
query-test failures: symbol/{panned,rotated}-after-insert

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3346]
The following related query tests are failing:
- https://github.com/mapbox/mapbox-gl-test-suite/tree/master/query-tests/symbol/panned-after-insert
- https://github.com/mapbox/mapbox-gl-test-suite/tree/master/query-tests/symbol/rotated-after-insert

These failures need investigation and fixing.

Refs https://github.com/mapbox/mapbox-gl-native/pull/6627 cc @brunoabinader

**Comment by ChrisLoer** [comment]
Re-enabled with #5603.
