### ISSUE TITLE
Buggy dragging in the "drag a point" example

### ISSUE THREAD

**Issue by 1icas** [mapbox/mapbox-gl-js#3352]
https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/

**mapbox-gl-js version**:
### Steps to Trigger Behavior
1. double click the map
2. drag the point to a new location
### Expected Behavior

drag the point  to an new location
### Actual Behavior

can't drag the point

**Comment by mollymerp** [comment]
Hi @1icas -- thank you for your bug report! 

I cannot reproduce the issue in chrome or firefox on macOS Sierra. Can you let us know what brower + OS you're using, and copy any errors you're seeing on the console to this ticket? Thanks!

**Comment by mourner** [comment]
@mollymerp I could reproduce a few times on Chrome under Sierra, but not consistently. My guess is that it's somehow related to the (c) symbol in the copyright getting selected on the double click.

**Comment by 1icas** [comment]
@mollymerp @mourner  the chorme version is 50.0.2661.87 m, it will help you. i think you should do nothing and double-click on the map first when you open the "drag a point" example.

**Comment by 1icas** [comment]
@mollymerp @mourner , i have another question.  i think you can reproduce in the "drag a point" example.

First : click ten times on the map. (left button)
Second: it's very slowly when you drag the point .
Third: keep mouse down and let the cursor leave the map. now, mouse up and let the cursor enter the map. it will be faster .  why ????!!!!!!!!!

i know that you can add 
 map.off('mousemove', onMove);
    map.off('mouseup', onUp);  in the  onUp() function

**Comment by mourner** [comment]
@1icas can you try a more recent Chrome version (v54)?

**Comment by 1icas** [comment]
@mourner can you send me chrome client from email？ 30893898@qq.com .because i have not proxy to download the new chrome client

**Comment by lucaswoj** [comment]
Closing as stale. I can't repro in any browser.
