### ISSUE TITLE
Layer metadata with function breaks map

### ISSUE THREAD

**Issue by Naimikan** [mapbox/mapbox-gl-js#3360]
**mapbox-gl-js version**: v0.25.1

### Steps to Trigger Behavior

 1. Create Layer with metadata attribute: 
 
    ```
    // ...
    map.addLayer({
       id: 'polygon_1',
       source: 'polygon_source',
       type: 'fill',
       metadata: {
          id: '111',
          fn: function () {
             return '';
          }
       },
       paint: {
          'fill-color': 'red'
       }
   });
   // ...
   ```

### Expected Behavior
Render map normally

### Actual Behavior
The map breaks

**Comment by mourner** [comment]
This is expected behavior — Mapbox Style should be a valid JSON, per the specification. You'll have to store non-JSON custom properties in a different place.

**Comment by lucaswoj** [comment]
Our style validator should check for this and present a helpful error message. Just openned a ticket in that repo https://github.com/mapbox/mapbox-gl-style-spec/issues/536
