### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#337]
This should be BSD, right? Since I'm taking some inspiration from [glfx](http://evanw.github.io/glfx.js/demo/) I'd like to add some creds. Plus, we're bundling some utilities with licenses, like glmatrix.

**Comment by genofire** [comment]
Is it possible to add License on a way that github understand it is a BSD.

The FOSSA at the end of the README.md shows a 17% unknown license, because of this leak.
