### ISSUE TITLE
options.touchZoomRotate = false breaks zoom behaviour in mobile safari

### ISSUE THREAD

**Issue by rvijgen** [mapbox/mapbox-gl-js#3371]
setting options.touchZoomRotate to false prevents the map from rotating as expected. It also makes the entire page zoomable in mobile safari. Pinch to zoom now zooms the page instead of the map.

**mapbox-gl-js version**:
### Steps to Trigger Behavior

 1.
 2.
 3.

**Comment by mourner** [comment]
Isn't this expected behavior? Or would you want to suppress standard browser page interactions on the map even if map interaction is disabled?

**Comment by mourner** [comment]
Oh, I see — this property should only govern rotation but not disable zoom.

**Comment by rvijgen** [comment]
Right, that is what I was looking for. 

Verstuurd vanaf mijn iPhone

**Comment by jfirebaugh** [comment]
→ #4395
