### ISSUE TITLE
Ensure changing a style releases tile resources

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3378]
Followup from #3116. In addition to the `Map#removeSource` case, we need to ensure that source/tile resources are released when the style is replaced wholesale.

**Comment by lucaswoj** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/3359 handles this case. [`Map#setStyle` calls `Style#_remove`](http://github.com/mapbox/mapbox-gl-js/blob/4dc27c3810cb8f09d0de9578ad2e6b0e8eeb499f/js/ui/map.js#L621-L622) which [releases the tile resources](http://github.com/mapbox/mapbox-gl-js/blob/4dc27c3810cb8f09d0de9578ad2e6b0e8eeb499f/js/style/style.js#L730-L731).

**Comment by jfirebaugh** [comment]
👍  Missed that, thank you.
