### ISSUE TITLE
Fix z-ordering of extruded features across multiple style layers

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#3387]
These are currently true, for extrusions in GL:

- GL respects three-dimensional space only **within** the context of a layer: if I draw two extrusions on two layers, one will render in front of the other regardless of my camera angle.

  In 2D maps, layer order was a handy heuristic for z-order, as there'd be no way for the camera to "peer around" the top layer. This is no longer true with the added dimension, and we may need a new way to define and draw what's in front.

- GL respects feature opacity only **between** layers: if I draw two translucent extrusions in the same layer, I cannot see through one to the other. Extrusions within each layer are treated as opaque to one another. It's my understanding that this might be a temporary technical limitation, though.

**Comment by jfirebaugh** [comment]
⇢ https://github.com/mapbox/mapbox-gl-style-spec/issues/545
