### ISSUE TITLE
"Navigation is not a method"

### ISSUE THREAD

**Issue by pcwa-ahendricks** [mapbox/mapbox-gl-js#3390]
Does renaming the `Navigation` constructor to 'NavigationControl` constitute a breaking change? Should these type of updates be included in the Changelog?  Feel free to close this ticket. Apologize in advance if I don't know all the specifics/subtleties about Semantic Versioning.

**Comment by tmcw** [comment]
Yep, it's [included in the changelog](https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.26.0), right?

**Comment by pcwa-ahendricks** [comment]
Big whoops on my behalf.  It certainly is.
