### ISSUE TITLE
Map unresponsive to `pitch` event

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#3391]
**mapbox-gl-js version**: 0.26.0

### Steps to Trigger Behavior

Check out https://jsfiddle.net/0gtvwgd0/

### Expected Behavior

Map should throw an alert message whenever the pitch changes.

### Actual Behavior

It does not.

**Comment by lucaswoj** [comment]
Agreed. Merging this with https://github.com/mapbox/mapbox-gl-js/issues/3357 because the two are so closely related the ought to be fixed in the same PR.
