### ISSUE TITLE
Ref layer bugs in worker.js

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3395]
[This comment](https://github.com/mapbox/mapbox-gl-js/blob/c88ec03d1da5058534e98a846e39c565deb973f8/js/source/worker.js#L80) claims that the following block updates ref parents, but in fact it updates ref children. Vice versa for subsequent block. If order is important, this might be a bug.

[This line](https://github.com/mapbox/mapbox-gl-js/blob/c88ec03d1da5058534e98a846e39c565deb973f8/js/source/worker.js#L93) treats `layer.ref` as if it always exists. For ref parents, it effectively looks up the layer with ID `"undefined"`, which is not what's desired.

**Comment by jfirebaugh** [comment]
Also, why does `'set layers'` skip layers that aren't fill, line, circle, or symbol, but not `'update layers'`?

**Comment by jfirebaugh** [comment]
Another issue is that `'update layers'` is written and tested as if `layerDefinitions` is an object, when in actual use it's an array.

**Comment by mourner** [comment]
@jfirebaugh they were probably equivalent but diverged at some point, which always happens when there is code duplication. Thanks for the fixes in #3396!

**Comment by mourner** [comment]
__
