### ISSUE TITLE
Use native ES6 classes

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#3400]
We should continue #3368 by converting to native ES6 class syntax. There are few things to figure out though:

- Is everyone OK with converting `Evented` from a mixin to a class? Given that it is inherited as a prototype everywhere it's used, this make sense, and we'll be able to use the native `class Foo extends Evented` syntax. It's a breaking change, although not sure if any downstream code depends on this.
- There are a few instances where we have some methods of a class defined in a separate file — specifically, `camera.js` (a part of `Map`) and `use_program.js` (a part of `Painter`). We can leave it as is, but after we convert to ES6 syntax, it would be much cleaner to get rid of prototype mixins like this. For the camera case, perhaps we should make it a composition with `Camera` as a separate class (similar to `Transform`). For the relatively small `use_program`, I would just move it back to `Painter`.

@jfirebaugh @lucaswoj

**Comment by lucaswoj** [comment]
All of these changes sound wonderful 👍

**Comment by jfirebaugh** [comment]
> For the camera case, perhaps we should make it a composition with `Camera` as a separate class (similar to `Transform`).

So long as we keep methods such as `Map#setCenter`, `Map#flyTo` delegating to the composed `Camera` object, this sounds good.
