### ISSUE TITLE
[example - Swipe between maps]  Missing 'mapbox-gl-compare.css'

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#3409]
![image](https://cloud.githubusercontent.com/assets/1522494/19519143/2cc84f0a-963d-11e6-9ecf-0cc32e0845d0.png)

Seems Missing https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-compare/v0.0.2/mapbox-gl-compare.css

**Comment by joedjc** [comment]
The JS file is also missing from the api directory I think...
https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-compare/v0.0.2/mapbox-gl-compare.js

**Comment by tristen** [comment]
👍 Thanks, should be fixed. Needed a deploy!
