### ISSUE TITLE
Question about the range of minZoom and maxZoom

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#3410]
What does "1-20" suppose mean? I see source tilesets can be 0-22
![image](https://cloud.githubusercontent.com/assets/1522494/19521183/560a1224-9645-11e6-8485-4efc21dbd5b6.png)

**Comment by lucaswoj** [comment]
GL JS is restricted to the zoom levels 1 - 20. The [TileJSON spec](https://github.com/mapbox/tilejson-spec/tree/master/2.0.0) allows a max zoom of 22.
