### ISSUE TITLE
builds no longer work on older versions of node

### ISSUE THREAD

**Issue by vicapow** [mapbox/mapbox-gl-js#3413]
Hello,

With the recent switch to Buble, I'm no longer able to build my project with mapbox through browserify. I get the following error: 

````
/Users/victorpowell/Documents/projects/my-project/node_modules/buble/dist/buble.umd.js:3706
  exports.REGULAR = new Map([
                        ^
ReferenceError: Map is not defined
    at /Users/victorpowell/Documents/projects/my-project/node_modules/buble/dist/buble.umd.js:3706:25
    at __commonjs (/Users/victorpowell/Documents/projects/my-project/node_modules/buble/dist/buble.umd.js:11:70)
    at /Users/victorpowell/Documents/projects/my-project/node_modules/buble/dist/buble.umd.js:3700:34
    at acorn (/Users/victorpowell/Documents/projects/my-project/node_modules/buble/dist/buble.umd.js:2:66)
    at Object.<anonymous> (/Users/victorpowell/Documents/projects/my-project/node_modules/buble/dist/buble.umd.js:5:2)
    at Module._compile (module.js:456:26)
````

I believe this is because I'm using an older version of node that doesn't have ES2015 `Map` class. One solution is to update Node but I wanted to see if there was interest in still supporting the older version first. (It also seems unusual an ES2015 compiler would require ES2015 features to run 😕). Is going back to babel an option?

**Comment by lucaswoj** [comment]
We have required node v4+ since https://github.com/mapbox/mapbox-gl-js/pull/2630. I think Buble should work with node v4.

**Comment by vicapow** [comment]
Ah, didn't see this. The project was still working fine for me with node v0.10.32 until this change
