### ISSUE TITLE
Fix exception caused when switching to a zoom-and-property function to any other value

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#3425]
**mapbox-gl-js version**:
### Steps to Trigger Behavior
1. Create a layer with a zoom-and-property function as a paint value
2. Call `setPaintProperty` to transition that layer to either a constant, a zoom fn, or a property fn
### Expected Behavior

Paint property is changed accordingly
### Actual Behavior

Breaks map, throws `a.declaration.calculateInterpolationT is not a function` error

This is because `StyleDeclaration.calculateInterpolationT` is [only created for a zoom-and-property fn](https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style_declaration.js#L43-L47), so when trying to transition from that to a declaration without it, it is missing that function.

Example: http://jsbin.com/sohoyumobi/edit?js,output

**Comment by ansis** [comment]
It looks like this has been fixed. I can't reproduce on master
