### ISSUE TITLE
Ensure "line-dasharray" works as specified when "line-width" changes at runtime 

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3426]
https://github.com/mapbox/mapbox-gl-test-suite/tree/master/render-tests/regressions/mapbox-gl-js%233426

Expected:

![image](https://cloud.githubusercontent.com/assets/98601/19581135/d4c61082-96df-11e6-8ffa-c7d711c6c436.png)

Actual:

![image](https://cloud.githubusercontent.com/assets/98601/19581146/dc6ea59c-96df-11e6-896f-11c12a472073.png)

**Comment by jingsam** [comment]
**TD, DR: When line-width changes, the calculation of dash length is always based on the old line-width, not the new one.**

Reproduce this bug:
set `line-dasharray = [1,1]`

1. Change line-width from 1px to 20px:

line-width = 1, looks fine:
![image](https://cloud.githubusercontent.com/assets/1522494/19591494/f509762a-97a9-11e6-9d12-b0e4c5709be3.png)

line-width = 20, looks wired:
![image](https://cloud.githubusercontent.com/assets/1522494/19591518/14d1d2e0-97aa-11e6-9ec3-3ace573d2e49.png)

But when zoom in and zoom out, everything looks alright:
![image](https://cloud.githubusercontent.com/assets/1522494/19591600/67fe4386-97aa-11e6-9900-77ed768b6580.png)

2. Let me change line-width back to 1px, this is what I get:
![image](https://cloud.githubusercontent.com/assets/1522494/19591699/d9f0bc1c-97aa-11e6-9fab-225621519bc5.png)

Zoom in and zoom out, looks OK:
![image](https://cloud.githubusercontent.com/assets/1522494/19591725/f8459cb4-97aa-11e6-983d-6bdf09b22b24.png)

**Comment by lucaswoj** [comment]
Thanks for the repro steps @jingsam 😄
