### ISSUE TITLE
Dashes are clipped on the tile boudaries

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#3428]
![image](https://cloud.githubusercontent.com/assets/1522494/19592205/47fdbc08-97ad-11e6-9267-93a51a356432.png)

This problem seems unavoidable when rendering with vector tiles

**Comment by mourner** [comment]
Yeah, I'm not even sure it's possible to fix.

**Comment by jfirebaugh** [comment]
Yes, this is expected behavior and not something that's feasible to fix.
