### ISSUE TITLE
Reduce .PBF size when zoom is small.

### ISSUE THREAD

**Issue by huangyingjie** [mapbox/mapbox-gl-js#3429]
When zoom is small (ie. the city level), mapbox-gl-js downloads too many PBF file, and each size is 100+Kb. The map spent 5+ seconds to finish its initialization in wifi env.
But when using google map, it always downloads only several 10+kb files which is fast.
Can we reduce the pbf size?

**Comment by jingsam** [comment]
Try to append `?optimize=true` in your style, e.g mapbox://styles/mapbox/streets-v9?optimize=true

**Comment by huangyingjie** [comment]
I will try.But the mapbox official examples also download too much pbf. Why don't mapbox itself use optimize option?

**Comment by jingsam** [comment]
Because [this feature](https://www.mapbox.com/blog/style-optimized-vector-tiles/) was just released yet a few days ago. I have send a issue  #3430 to make an example about this feature.

**Comment by jfirebaugh** [comment]
The number and size of vector tiles is dependent on the data source you are using. To reduce those metrics, you have the following options:

* Use a lower maximum zoom level for the data source. Above the maximum zoom level, Mapbox GL JS will overzoom the tiles, such that each tile covers a larger area.
* Reduce the detail or amount of data in the source.

**Comment by huangyingjie** [comment]
I found the truth: the `glyphs` like `23552-23807.pbf` is larger and more than vector tiles.
`xx.vector.pbf` is actually small.
