### ISSUE TITLE
Large circle disappears when center is outside of visible map area

### ISSUE THREAD

**Issue by princeofnaxos** [mapbox/mapbox-gl-js#3431]
**mapbox-gl-js version**: 0.26.0

### Steps to Trigger Behavior

 1. create a circle layer with a large radius
 2. move the map so that the center of the circle is outside of the visible area
 3. keep moving a bit more (probably to the edge of the tiles)

### Expected Behavior
The circle stays visible.

### Actual Behavior
The circle suddenly disappears.

**Comment by mourner** [comment]
Can you provide a minimal JSFiddle test case for this?

**Comment by lucaswoj** [comment]
This is an unfortunate limitation of how vector tiles work and something we cannot fix in the near future. I do not recommend using a circle radius greater than the width of a tile.

**Comment by princeofnaxos** [comment]
Yep, see https://jsfiddle.net/zhgp4vqf/

Just move the center of the circle away in any direction.

With best regards,

Edwin Boersma

*Fasterminds*
/A Marketing Company./
www.fasterminds.com <http://www.fasterminds.com>

Phone: +46 (709) 726431

Webpage: www.fasterminds.com <http://www.fasterminds.com>
Email: edwin.boersma@fasterminds.com <mailto:edwin.boersma@fasterminds.com>

This communication is intended for the person or entity to which it is 
addressed and may be confidential. Any review, re-transmission or 
dissemination is prohibited. If you received this transmission in error, 
please contact the sender then delete this message.

This email has been virus checked by the latest virus checking software, 
however, we advise you to carry out your own virus check as we cannot 
accept liability for any damage sustained as a result of any software 
viruses.
