### ISSUE TITLE
FR: circles should follow the map's tilting/projection

### ISSUE THREAD

**Issue by princeofnaxos** [mapbox/mapbox-gl-js#3433]
## Motivation

We are using circles to display a search area. When tilting the map, the circle doesn't change shape, where it should morph into eggform or ellips or so. Without this functionality, using circles as we do makes no sense and stops us from migrating to Mapbox GL.

**Comment by jfirebaugh** [comment]
This would be the `circle-pitch-alignment` property, tracked in https://github.com/mapbox/mapbox-gl-style-spec/issues/459.

**Comment by princeofnaxos** [comment]
Yes, it is, John. Thanks.
