### ISSUE TITLE
fire map load event for subsequent style loads

### ISSUE THREAD

**Issue by phuongcv1112** [mapbox/mapbox-gl-js#3434]
**mapbox-gl-js version**: 0.25.0 and 0.26.0

### Steps to Trigger Behavior

map.setStyle(newBasemapStyle);
map.style.on('load', function(){
    alert("Style load");
});

### Expected Behavior
Alert "Style load"

### Actual Behavior
Not show anything, I tried with version 0.24.0 and lower, then it work normally.
Please help to check this

Note: This related to this issue: https://github.com/mapbox/mapbox-gl-js/pull/1480

**Comment by mourner** [comment]
After https://github.com/mapbox/mapbox-gl-js/pull/3306, the proper way to do this is to subscribe to `map` `data` event and check for `e.dataType === 'style'`.
