### ISSUE TITLE
negative fill-extrude-base results in unexpected rendering

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#3456]
Following on from #3401 could negative values for `fill-extrude-base` be handled better?

**mapbox-gl-js version**: 0.26

### Steps to Trigger Behavior

Use a negative `fill-extrude-base`

http://jsbin.com/xulimayono/edit?html,output

![selection_404](https://cloud.githubusercontent.com/assets/117278/19671678/35793956-9abc-11e6-8534-a94b302fa156.png)

### Expected Behavior

I understand cutting into the ground plane isn't going to be supported per #3401, however if I supply a negative `fill-extrude-base` I would expect it would just disappear below the surface and look the same as a 0 value.

### Actual Behavior

Instead the negative value appears to overflow to a high positive number resulting in the the extrusion starting off at `fill-extrude-height` and extending to infinity. Not what you would expect.

I think either this should be documented that negative values aren't supported or they should be treated as 0.

As a side note, my current workaround is to use two layers with a filter for `>= 0` and `< 0`, and when `< 0` manually fix the `fill-extrude-base` to 0, though it suffers from https://github.com/mapbox/mapbox-gl-style-spec/issues/545. Ideally I would change the source data to simply trim negatives to 0 as a workaround.

/cc @lbud

**Comment by lbud** [comment]
Thanks for the report @andrewharvey! Addressing in https://github.com/mapbox/mapbox-gl-js/pull/3463 which clamps negative values to 0, so the example provided displays as
![image](https://cloud.githubusercontent.com/assets/3170312/19707649/ab08d544-9acd-11e6-8371-a751237a5665.png)


Both `fill-extrude-height` and `fill-extrude-base` have a `minimum: 0` specified in the style spec JSON, although it seems the `minimum` key doesn't render in our [documentation](https://www.mapbox.com/mapbox-gl-style-spec/) (will open separate issue)…

**Comment by lbud** [comment]
Related documentation issue: https://github.com/mapbox/mapbox-gl-style-spec/issues/551
