### ISSUE TITLE
Create example of multiple types of geometries coming from a GeoJSON layer

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#3467]
This question came up in support:

> How do I show multiple types of data - like lines _and_ points - from the same GeoJSON source?

We don't have an example that directly demonstrates this yet, and we should, since one part is rather simple - just reference the same example - and another is tricky - you might want to avoid adding lines around polygons and adding markers to vertices of non-Point geometries.

Creating this example would be a great starter task for someone from @mapbox/support who hasn't made an example yet!

**Comment by captainbarbosa** [comment]
Completed in #3554!
