### ISSUE TITLE
NPM registry yields prior string version of latest mapbox-gl dist

### ISSUE THREAD

**Issue by andest01** [mapbox/mapbox-gl-js#3475]
**mapbox-gl-js version:** `0.26.0` (??? see below ???)

Latest build under [https://registry.npmjs.org/mapbox-gl/-/mapbox-gl-0.26.0.tgz](https://registry.npmjs.org/mapbox-gl/-/mapbox-gl-0.26.0.tgz) at `dist/mapbox-gl.js` reports the incorrect version.

### Expected Behavior
exports string version: `0.26.0`

### Actual Behavior
exports string version: `0.25.1`

<img width="327" alt="screen shot 2016-10-27 at 10 30 05 am" src="https://cloud.githubusercontent.com/assets/1424223/19773761/612b36b0-9c30-11e6-9fe9-f0f952e06e72.png">

**Comment by michaeljonsampson** [comment]
I downloaded https://registry.npmjs.org/mapbox-gl/-/mapbox-gl-0.25.1.tgz and it reported build version 0.25.0.

I had 0.20.0 installed recently and it would report 0.19.1.

**Comment by mourner** [comment]
That probably happens when a person who does the release does not regenerate the bundle after running `npm version`, doing `npm publish` with an outdated version field. I think we can fix this by adding a `prepublish` script. cc @jfirebaugh 

A better long-term fix would be #2250.

**Comment by jfirebaugh** [comment]
Yeah, we need to automate this so there's no human involved.
