### ISSUE TITLE
Document/Clarify feature.id in return value of queryRenderedFeatures for vector sources.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#3477]
**mapbox-gl-js version**:Master

### Steps to Trigger Behavior

Can you please clarify/document if feature.id returned by queryRenderedFeatures is the following (or not) and if the client applications can use it this way?

feature.id is the index in the corresponding source layer in vector tile.

**Comment by jfirebaugh** [comment]
> feature.id is the index in the corresponding source layer in vector tile.

No, it's the `id` property of the feature, as defined in the [vector tile](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#42-features) or [GeoJSON](https://tools.ietf.org/html/rfc7946#section-3.2) specifications.

See #2716 for current caveat.

**Comment by mb12** [comment]
Thanks for the clarification.
