### ISSUE TITLE
fitBounds and jumpTo should refer to each other or be renamed

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#3482]
Many examples use `fitBounds` and I and others have had trouble figuring out that `fitBounds` and `jumpTo`, methods that don't sound like each other at all, do the same thing with/without animation.
### Documentation proposal

For fitBounds:

> Pans and zooms the map to contain its visible area within the specified geographical bounds. This uses animation to make the transition smooth: you can move to a new area or zoom level instantly by using jumpTo.

For jumpTo:

> Changes any combination of center, zoom, bearing, and pitch, without an animated transition. The map will retain its current values for any details not specified in options. You can move to a new area or zoom level with a smooth animation by using fitBounds.
### API Proposal
- fitBounds
- animateFitBounds

**Comment by tmcw** [comment]
Actually this was based on a misconception, that `jumpTo` could also accept a bounds. What _is_ the best and most obvious ways to fit to a bounds without animation? On a thorough read of the current documentation, I do not see it.

**Comment by jfirebaugh** [comment]
Previously: #1473.

**Comment by lucaswoj** [comment]
Would it be fair to close this as a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/2801?

**Comment by tmcw** [comment]
If you add more detail, sure - while #2801 discusses that the names need an update, this issue proposes a potentially new method entirely or a potentially new camera option in order to alleviate a gap in the current API.

**Comment by tmcw** [comment]
Closing in favor of #2801
