### ISSUE TITLE
map.off(event) doesn't works anymore

### ISSUE THREAD

**Issue by shaithana** [mapbox/mapbox-gl-js#3484]
**v0.26.0**

 1. Attach an event to a map:
`map.on('click', function(e){
			// do stuff;
		});`

 2. Detach all the 'click' events:
`map.off('click');`

The events must be detached (as in previous versions, see v0.18.0) but is not anymore.

**Comment by tmcw** [comment]
Hi Giovanni,

The [documented API of off](https://www.mapbox.com/mapbox-gl-js/api/#Evented.off) is `off(type, listener)`. In your example, you're only providing the type, not the listener, so this code snippet should not be expected to work. To use `off` correctly, please provide the listener function as an argument.

- Tom

**Comment by jfirebaugh** [comment]
This was a breaking change in v0.25.0 (part of #3244), and we neglected to include it in the CHANGELOG. Sorry about that! I'll add it now.

**Comment by jfirebaugh** [comment]
b708fd068a7f46f66b0c9b87115ae71108afea2b
