### ISSUE TITLE
Symbols rendered as black/purple rectangle patches on Android.

### ISSUE THREAD

**Issue by mb12** [mapbox/mapbox-gl-js#3494]
**mapbox-gl-js version**:Master and 0.26.0

### Steps to Trigger Behavior

I run into this issue several times everyday. The following steps consistently reproduce the issue on both Note3 (running 4.4.2) and Samung Galaxy Tablet (running 6.x).

 1. Open a GL JS Samples page.
 2. Lock the device.
 3. Unlock the device after half an hour. All text and icons are now rendered as black rectangular patches. Sometimes you may have to pan/interact with the map to cause these to appear. I've attached a screenshot from my device.

![screenshot_2016-10-31-11-50-11](https://cloud.githubusercontent.com/assets/8890269/19867585/997c76b2-9f61-11e6-99c5-37a53fc63411.png)

### Expected Behavior
Text and icons should be rendered correctly.
### Actual Behavior
Text and icons are  rendered as black patches.

**Comment by mb12** [comment]
Added another screenshot from samples page illustrating the problem. This is to emphasize that there is no problem with fills and lines. Only symbols are problematic.

![screenshot_2016-10-31-12-05-33](https://cloud.githubusercontent.com/assets/8890269/19867791/7a7cfd12-9f62-11e6-9db7-3bb2191d231c.png)

**Comment by jeroenbourgois** [comment]
I am experiencing the same issue on desktop (Chrome). I guess I am doing something wrong with the marker image (it is loaded though...), sometimes it works, sometimes it doesn't. This is what the console says:

![image](https://cloud.githubusercontent.com/assets/202312/26167951/b7b4abd6-3b38-11e7-9a0c-b0df83482749.png)

**Comment by nrako** [comment]
The same issues has been reported to me by some users. Running v0.39.1.

Occurs at least on Samsung galaxy tab a6, but I'm being told it also occurs on other Android tablets.

![image001](https://user-images.githubusercontent.com/425397/30016164-42a71708-9154-11e7-88ab-744b98b2f4e4.png)

Since this issue has stalled, does anybody have a workaround?  I just saw that tinkering with the `devicePixelRatio` might help on android https://github.com/mapbox/mapbox-gl-js/issues/1953 ?

**Comment by jfirebaugh** [comment]
Is this still an issue?

**Comment by nrako** [comment]
On my side, I'm not aware of any recent occurence.

**Comment by mourner** [comment]
Closing since this was likely a browser bug which doesn't appear to manifest anymore.
