### ISSUE TITLE
I am using something out of the question

### ISSUE THREAD

**Issue by itcongaili** [mapbox/mapbox-gl-js#3500]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1.i am using angualr ui route Switch pages 
![git](https://cloud.githubusercontent.com/assets/11898652/19877913/46f452d0-a01e-11e6-9646-d1b096a9d4e3.png).
I have this situation.

 2.normal circumstances.Refresh just fine.
![git](https://cloud.githubusercontent.com/assets/11898652/19877923/6c5d2aec-a01e-11e6-8b90-ad7bbf444249.png)

 3.Do not know how to solve.English is not good, a lot of inclusion》

**Comment by jingsam** [comment]
Press F12 to open DevTools, did you notice any "glyph overflow" warning?

**Comment by jfirebaugh** [comment]
Which version are you using? This looks like a bug that was fixed in v0.24.0.

**Comment by itcongaili** [comment]
![image](https://cloud.githubusercontent.com/assets/11898652/19878571/3de88bb4-a025-11e6-9ddd-28571e5723a4.png)
Seems 0.23.0

**Comment by jfirebaugh** [comment]
Ok, please upgrade to the latest version -- this bug has been fixed.

**Comment by itcongaili** [comment]
@jfirebaugh very thinks,has been resolved.

**Comment by itcongaili** [comment]
@jingsam  change version 0.26.0,has been resolved
