### ISSUE TITLE
Flaky flyTo test

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#3502]
`camera #flyTo peaks at the specified zoom level` test is flaky and sometimes fails on Circle. Need a more reliable test. cc @1ec5 

```
 1) test/js/ui/camera.test.js camera #flyTo peaks at the specified zoom level expect truthy value:
     Error: expect truthy value
      at Camera.camera.on (test/js/ui/camera.test.js:991:19)
      at Camera.fire (js/util/evented.js:34:317)
      at Camera.<anonymous> (js/ui/camera.js:322:1233)
      at Camera._finishEase (js/ui/camera.js:329:132)
      at Camera.<anonymous> (js/ui/camera.js:327:591)
      at Immediate.tick (js/util/browser.js:7:1758)
```

**Comment by mourner** [comment]
Seems to be related to https://github.com/mapbox/mapbox-gl-js/commit/407cad609cbf22c2e7fffef0ceb3b5d34273189e. @blanchg Where does the `1.1` value come from? Can it be >1.1 in some rare cases?

**Comment by blanchg** [comment]
Possibly I was seeing the end event producing varying results based on machine load/cpu

**Comment by mourner** [comment]
@blanchg want to make a PR to make this test more reliable?

**Comment by blanchg** [comment]
@mourner I can try but it won't be till tomorrow.

**Comment by mourner** [comment]
@blanchg sure, no rush.

**Comment by blanchg** [comment]
If I throttle my CPU to 5% the minZoom it reaches is still 1.01, I thought when I made this change from a strict 1.00 to 1.10 it would have been enough but with a very slow/busy cpu it is possible that the zoom event doesn't fire anywhere near the top (in fact if it is busy enough it may never even reach 10).

Not sure how lenient to make this.  I believe the intention was that it transitions from 20 to 1 and back to 20.  Maybe the test should be that it reaches 19?

**Comment by mourner** [comment]
@blanchg we should design the test in a way that doesn't depend on CPU load at all. The CI environment can be upredictable in this regard. If we can't make such a test, I think it's better to just disable this assertion, as it forces us to rerun tests for valid commits frequently.

**Comment by blanchg** [comment]
@mourner I don't know what the original test was for or a way to get the
zoom event to fire in a predictable pattern.
