### ISSUE TITLE
In labels in vertical writing mode, replace punctuation with fullwidth equivalents

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#3505]
Per https://github.com/mapbox/mapbox-gl-js/pull/3438#issuecomment-255553240, but various Chinese and Japanese dashes and brackets are [rotated](http://www.unicode.org/charts/PDF/UFE30.pdf) 90° or 180° when laid out vertically. Apart from dashes and parentheses, punctuation might be uncommon in road names (the most commonly line-placed names). However, if it ever occurs, the result could be confusing. For example, an em dash (—), left unrotated, could be confused with a radical (丨) or numeral (〡).

Below are the affected punctuation marks and their vertical forms. Some of them, like the em dash, are used both in Chinese and in English, so the replacement should only occur adjacent to a vertical (CJK) character lest the English side of a bilingual label get mangled.

Horizontal | Vertical
----|----
。|︒
—|︱
–|︲
_|︳
（|︵
）|︶
｛|︷
｝|︸
〔|︹
〕|︺
〘|︹ (?)
〙|︺ (?)
【|︻
】|︼
《|︽
》|︾
〈|︿
〉|﹀
「|﹁
」|﹂
『|﹃
』|﹄
｢|﹁
｣|﹂
［|﹇
］|﹈
“|﹁
”|﹂
‘|﹃
’|﹄
…|⋮
.|・

/cc @lucaswoj @nickidlugash @xrwang @friedbunny

**Comment by 1ec5** [comment]
Per https://github.com/mapbox/mapbox-gl-js/pull/3438#issuecomment-257750228, this is also necessary because a non-CJK glyph may in many cases extend upwards past the cap height, which would cause it to collide with the previous character in vertical text.

**Comment by lucaswoj** [comment]
> adjacent to a vertical (CJK) character

Which of these should our criteria be?

 - (a) use vertical punctuation if **either** of the surrounding characters "allow vertical writing mode"
 - (b) use vertical punctuation if **both** of the surrounding characters "allow vertical writing mode"

**Comment by 1ec5** [comment]
Most CJK punctuation marks have a built-in space, so they bind to one side or another: for example, `（` should turn into `︵` based on the CJK-ness of the following character. `—`, on the other hand, can become `︱` if either adjacent character is CJK. As for https://github.com/mapbox/mapbox-gl-js/pull/3438#issuecomment-257750228, `/` is a non-vertical glyph with no vertical equivalent, so we’d rotate the standard glyph regardless of what comes before or after.

We might have to endure some trial and error with `{name}` in Streets source to figure out the right set of rules.

**Comment by nickidlugash** [comment]
> Per #3438 (comment), this is also necessary because a non-CJK glyph may in many cases extend upwards past the cap height, which would cause it to collide with the previous character in vertical text.

To clarify my comment about the solidus character, this punctuation mark should actually **not** get rotated – only the characters in [the list above](https://github.com/mapbox/mapbox-gl-js/issues/3505#issue-186597964) should get rotated. So this ticket will not solve the solidus issue (although parenthesis, which *are* on the list, have the same overshoot issue).

**Comment by 1ec5** [comment]
Wouldn't we want to rotate the solidus once #3506 is implemented?

**Comment by 1ec5** [comment]
Actually, there's [a whole complement of fullwidth forms](https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms) we can use for cases where we want to avoid rotating a Western character. For example, we'd replace any solidus adjacent to CJK with `／`.

**Comment by nickidlugash** [comment]
> there's a whole complement of fullwidth forms we can use for cases where we want to avoid rotating a Western character. 

see my [previous comment](https://github.com/mapbox/mapbox-gl-js/pull/3438#issuecomment-257750228) regarding this.

**Comment by nickidlugash** [comment]
And yes, we do not want to rotate the solidus if it is surrounded by CJK.

**Comment by lucaswoj** [comment]
Rather than mark this a "release blocker", I'm going to roll this into #3438

**Comment by 1ec5** [comment]
> I've seen conflicting information as to whether this is the correct character to use for Chinese in general and specifically for vertical orientation – solidus (U+002F), versus fullwidth solidus (U+FF0F).

My understanding is that the ordinary ASCII character is preferred for horizontal text while the fullwidth form is preferred for vertical text. The same is true for the quote marks above (e.g., `“` versus `﹁`) and ideally for the [single-letter case](https://www.w3.org/TR/jlreq/#fig_2_2_50-en) (but that’s another story).

**Comment by 1ec5** [comment]
Fullwidth punctuation surprisingly quite common in Mapbox Streets data, especially on highway names. In OpenStreetMap, a mere [133 ways](http://overpass-turbo.eu/s/jPL) use fullwidth punctuation in `name:zh` in 🇨🇳🇭🇰🇲🇴🇹🇼, compared with [1,636](http://overpass-turbo.eu/s/jPK) in `name`. However, the Mapbox Streets source’s `{name_zh}` property falls back on `name` if `name:zh` is absent. There are [3,950 such ways](http://overpass-turbo.eu/s/jPM) in the largest 🇯🇵 bbox I can create without timing out.

These queries don’t account for ASCII punctuation that often occurs in conjunction with Chinese text.

**Comment by lucaswoj** [comment]
Initial work done in https://github.com/mapbox/mapbox-gl-test-suite/commit/b6281b1629b20746e9fff0628eba1138e56e5b7d and https://github.com/mapbox/mapbox-gl-js/pull/3438/commits/4d5f5e6eb43ed1fd3cd1a61a0c833f2a742177f5

**Comment by lucaswoj** [comment]
Done in #3438

**Comment by 1ec5** [comment]
Next steps: #3587.
