### ISSUE TITLE
Docs: Do event listeners get cleaned up when map is removed?

### ISSUE THREAD

**Issue by jisaacks** [mapbox/mapbox-gl-js#3507]
Reading the docs about [map.remove()](https://www.mapbox.com/mapbox-gl-js/api/#Map#remove) It does not say if it removes all event listeners attached to map. Would I need to manually remove any event listeners beforehand or is calling map.remove good enough?

Whatever the answer is, should be added to the docs also. Thanks!

**Comment by lucaswoj** [comment]
Good question @jisaacks. We unbind all DOM event listeners. We do not unbind internal event listeners. I'm pretty sure this arrangement will allow the map to be garbage collected when its reference goes out of scope.
