### ISSUE TITLE
Map.jumpTo(...) does not cancel pending tile requests

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#3511]
If you invoke `Map#jumpTo` with a new center point, pending tile requests for unused tiles are not aborted.

In my case, tiles can be expensive to calculate and using `Map#jumpTo` too many times causes the tile server to get flooded with requests, only some of which are necessary for the currently visible area.

I think `Map#jumpTo` should behave like `Map#flyTo`, which aborts intermittent tile requests as the map moves.

**mapbox-gl-js version**: 0.24.0 and 0.26.0

### Steps to Trigger Behavior

```js
  const map = new mapboxgl.Map({
    container: '#map',
    style: 'mapbox://styles/mapbox/light-v9',
    center: [-122.9, 38.6],
    zoom: 12
  });
  
  map.on('load', function () {
    map.addSource('some-source', {
      'type': 'vector',
      'tiles': ['mapbox-vector-tile-source-here']
    });
  
    map.addLayer({
      'id': 'some-layer',
      'type': 'fill',
      'source': 'some-source',
      'source-layer': 'some-source-layer',
      'paint': { 'fill-color': '#000',}
    });
  
    map.jumpTo({ center: [-120.9, 38.6] });
  });
```

### Expected Behavior

Tile requests for `some-layer` should be aborted if they are not needed for the map's new viewport.

### Actual Behavior

Pending tile requests for unused tiles stay open until they resolve.

**Comment by jfirebaugh** [comment]
I'm not able to replicate an issue here. `jumpTo` and `flyTo` use the same mechanism for cancelling tile loads, and it seems to be working.

```
    const map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/light-v9',
        center: [-122.9, 38.6],
        zoom: 12
    });

    map.on('load', function () {
        map.flyTo({ center: [-120.9, 38.6] });
        setTimeout(function() {
            map.jumpTo({ center: [-120.9, 38.6] });
        }, 10);
    });
```

![image](https://cloud.githubusercontent.com/assets/98601/25509257/797da63c-2b6c-11e7-9755-d096d42cc44d.png)

**Comment by apoorvabhaskarshetty** [comment]
Is it possible to set map.jumpTo() to false?
