### ISSUE TITLE
Drawing multiple video sources on the same map causes incorrect rendering

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3524]
**mapbox-gl-js version**: v0.26.0

### Steps to Trigger Behavior

1. view http://jsbin.com/yuqodasuri/edit?html,output
2. press the "Run with JS" button a couple of times

### Expected Behavior

The video & satellite raster layer renders 

<img width="825" alt="screen shot 2016-11-02 at 6 22 18 pm" src="https://cloud.githubusercontent.com/assets/281306/19953281/582e7182-a129-11e6-87f0-f67ccad607e6.png">

### Actual Behavior

After a quick flash of the satellite raster layer, the map goes blank

<img width="826" alt="screen shot 2016-11-02 at 6 22 27 pm" src="https://cloud.githubusercontent.com/assets/281306/19953292/710ead66-a129-11e6-9a75-8607b0ed6fdb.png">

**Comment by asheemmamoowala** [comment]
Cannot reproduce this with latest Firefox/Safari/Chrome on OSX. 

Note that jsbin requires an updated access token
