### ISSUE TITLE
Feature request: map.getLayerIds function

### ISSUE THREAD

**Issue by voltagex** [mapbox/mapbox-gl-js#3528]
## Motivation
Currently, to get a reference to a layer on a map, you must run getLayer, passing in the ID of the layer. It would be easier in some cases to be able to get a list of all currently loaded layers (e.g. to loop/filter through them)

## Design Alternatives
* Continue with the current getLayer, require users to manually maintain list of layers
* Create a getLayerIds that returns a list of layer ID strings, as most functions (e.g. setLayoutProperty) expect a string reference

### Mock-Up

```
map.getLayerIds()
> ['firstlayer', 'secondlayer', 'thirdlayer']
```

### Implementation

```js
return map.style._order; // or
return map.getStyle().layers.map((layer) => layer.id);
```

**Comment by mourner** [comment]
It would probably be better to call it `map.getLayerIds()`. The implementation could be as easy as `return map.style._order;`.

**Comment by voltagex** [comment]
Thanks @mourner, I've edited my post slightly to reflect your suggestions.

**Comment by lucaswoj** [comment]
I would prefer we suggest using [`Map#getStyle().layers`](https://www.mapbox.com/mapbox-gl-js/api/#Map#getStyle) rather than creating another getter. Would that work for your use case, @voltagex?

**Comment by mourner** [comment]
@lucaswoj that would look more like `map.getStyle().layers.map((layer) => layer.id)`, and includes an expensive style serialization step. `map.style._order` on the other hand would be instant because it already stores layer ids.

**Comment by voltagex** [comment]
@mourner how expensive are we talking? This is not something I'd run in a loop, more likely on user input.

If you can give me some pointers on how to benchmark the two calls I'm happy to run it to check.

**Comment by mourner** [comment]
@voltagex oh, not much actually — ~2ms. :) This only matters if it's called very often, e.g. multiple times per frame.

**Comment by voltagex** [comment]
Sounds okay, perhaps it could start as `map.getStyle().layers.map((layer) => layer.id)` with a comment to move to `map.style._order` if performance becomes an issue.

**Comment by voltagex** [comment]
Wow, `map.getStyle().layers` returns an array of 199 objects for a simple test map. Is there really no distinction between basemap layers (e.g. streets-v9) and "custom" ones from my account?

**Comment by jfirebaugh** [comment]
I don't think we should implement this. Our model for the API is the JSON schema defined by the style specification; we should avoid implementing special-case getters and setters that go beyond that when they can be easily implemented in client code where needed.
