### ISSUE TITLE
Symbol features are not returned by `queryRenderedFeatures`

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3534]
GL JS `master` isn't returning any symbol features from `Map#queryRenderedFeatures`. Why isn't this causing any `test-suite` failures? The bug bisects to https://github.com/mapbox/mapbox-gl-js/pull/3478. 

cc @jfirebaugh @mourner @mapsam 

**mapbox-gl-js version**: `master` as of 46a73c4efcf119d287810e0f7ec305eb9d4102a6 / https://github.com/mapbox/mapbox-gl-js/pull/3478

### Steps to Trigger Behavior

call `Map#queryRenderedFeatures` at a point with a symbol feature

(tricky to provide a jsbin because this bug occurs only in `master`)

### Expected Behavior

the symbol feature is returned

### Actual Behavior

the symbol feature is not returned

**Comment by jfirebaugh** [comment]
I can take a look later today. I believe all of the query tests are for very simple styles, usually with only one layer. One thing I would check is if this only shows up if there are other layers present with the symbol layer.

**Comment by lucaswoj** [comment]
## Debugging Notes

* the bug was introduced in https://github.com/mapbox/mapbox-gl-js/pull/3478
* the bug does not manifest itself on a map with only symbol layers & background layers
* the bug does manifest itself on a map with a symbol layer and a line or fill layer
* the symbol in the StructArray returned by CollisionTile#queryRendered has an incorrect bucketIndex

## 💡 

As of #3478, `SymbolBucket` no longer inherits from `Bucket`.

Most of the constructor logic from `Bucket` was copied to `SymbolBucket` but the initialization of the `index` property was not https://github.com/mapbox/mapbox-gl-js/pull/3478/files#diff-621f09c210ab28c3dbf7bc1f0f03c6b2R116

## Next Steps

 - [ ] initialize `index` within the `SymbolBucket` constructor
 - [ ] add a regression test to `mapbox-gl-test-suite`
 - [ ] 🚢
