### ISSUE TITLE
Map.querySourceFeatures throws a TypeError when parameters option not included

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#3540]
**mapbox-gl-js version**: 0.26.0

http://jsbin.com/hoqobapaha/edit?html,console,output

### Steps to Trigger Behavior

 1. `map.querySourceFeatures('source');` omitting the optional `parameters`

### Expected Behavior

No error. The documentation seems to indicate `parameters` is optional.

### Actual Behavior

`tile.js:169 Uncaught TypeError: Cannot read property 'filter' of undefined` at https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/tile.js#L177

I've created a PR at https://github.com/mapbox/mapbox-gl-js/pull/3542

**Comment by mapsam** [comment]
Closed by #3542
