### ISSUE TITLE
Fix constructor documentation in docs

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#3543]
This code generates nice documentation for constructing an object:

```js
/**
 * A `LngLat` object represents a given longitude and latitude coordinate, measured in degrees.
 * @param {number} lng Longitude, measured in degrees.
 * @param {number} lat Latitude, measured in degrees.
 */
class LngLat {
    constructor(lng: number, lat: number) {
```

However it's not semantically correct. Moving `@param` block to its proper place (constructor) produces broken docs:

```js
/**
 * A `LngLat` object represents a given longitude and latitude coordinate, measured in degrees.
 */
class LngLat {
    /**
     * @param lng Longitude, measured in degrees.
     * @param lat Latitude, measured in degrees.
     */
    constructor(lng: number, lat: number) {
```

Note `new LngLat()` and the absence of parameter description:

![image](https://cloud.githubusercontent.com/assets/25395/19996514/4fe7e5a4-a21d-11e6-9f2a-39249b51ec4a.png)

 cc @tmcw @jfirebaugh

**Comment by jfirebaugh** [comment]
As part of https://github.com/documentationjs/documentation/issues/109, documentation should probably treat the comment associated with ES6 `class` as a `@classdesc`.

See also https://github.com/mapbox/mapbox-gl-js/pull/2744#issuecomment-226283142.

**Comment by mourner** [comment]
Not actionable until it's implemented upstream https://github.com/documentationjs/documentation/issues/109
