### ISSUE TITLE
Add support for geodesic polyline

### ISSUE THREAD

**Issue by flex-tuan** [mapbox/mapbox-gl-js#3544]
## Motivation

We're considering switching from Google Maps plans to Mapbox GL, but there are a couple of blockers. Support for geodesic polyline is one of them. The use case is for drawing fly paths between cities or long distance ocean ship routes. 
There's a simple setting in google maps for this https://developers.google.com/maps/documentation/javascript/reference#PolylineOptions; also it looks like it can be worked around with leaflet https://github.com/henrythasler/Leaflet.Geodesic

**Comment by andrewharvey** [comment]
https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-route/

**Comment by mourner** [comment]
Yep, or you could use https://github.com/springmeyer/arc.js/ to generate the arc.

**Comment by zakjan** [comment]
I created a MapboxDraw plugin to enable drawing geodesic map features. https://github.com/zakjan/mapbox-gl-draw-geodesic

I am wondering if the geodesic calculation could be ported into mapbox-gl-js, possibly as a layer style layout property `geodesic: true`?
