### ISSUE TITLE
Rendering artefact with GeoJSON

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#3545]
**mapbox-gl-js version**: 0.26.0

### Steps to Trigger Behavior

http://jsbin.com/decosuxiwo/edit?html,output

- Source [GeoJSON data here](https://www.alantgeo.com.au/share/au-states.geojson) or a more minimal version [here](https://www.alantgeo.com.au/share/au-states-nsw.geojson).
- QGIS Geometry Validation is okay
- Loads fine in geojson.io so I don't think it's a geometry/data issue
- Can't replicate it as a problem in geojson-vt using http://mapbox.github.io/geojson-vt/debug/

### Expected Behavior

![selection_409](https://cloud.githubusercontent.com/assets/117278/19997563/9597b6ee-a2bb-11e6-9eb4-895e1cd4d8e6.png)

### Actual Behavior

![selection_408](https://cloud.githubusercontent.com/assets/117278/19997556/8922f8d8-a2bb-11e6-90dc-4cd0fcc3808f.png)

**Comment by mourner** [comment]
Seems to be an Earcut problem. I'll look into it.

**Comment by lucaswoj** [comment]
I can still repro this in `master`.

**Comment by mourner** [comment]
This is likely not possible to fix until I finish http://github.com/mapbox/polysnap.

**Comment by mourner** [comment]
Likely the same problem: #3080

**Comment by andrewharvey** [comment]
I put together a minimal test case for this https://gist.github.com/andrewharvey/ee7d9b91c182dce34f96d0dbcd19bb29 but I guess @mourner you already have a handle on what the issue is. I've opened an earcut ticket 

- Passes http://geojsonlint.com/
- fine in Leaflet
![leaflet](https://user-images.githubusercontent.com/117278/37183540-a2e8b54a-238a-11e8-9d58-81ce9df42362.png)
- broken in gl js
![gl js](https://user-images.githubusercontent.com/117278/37183614-13d182aa-238b-11e8-8fec-0740cd3b1472.png)
- broken in earcut
![earcut](https://user-images.githubusercontent.com/117278/37183594-f65f5ddc-238a-11e8-8b77-b23318621dea.png)

**Comment by mourner** [comment]
Made a master ticket for this and similar issues to centralize the discussion: #7023
