### ISSUE TITLE
Enhancement: Add hover over highlight to 3D buildings

### ISSUE THREAD

**Issue by svcninja** [mapbox/mapbox-gl-js#3550]
## Motivation

The 3D building is a great feature. However, it seems that there is no way for me to highlight an individual building when mouse hovering over it. In OSMbuildings project, there is osm_id per building that allows you to tell the difference from one building to another, therefore there is highlight supported. It would be nice to have that feature in the mapboxgl. 

## Design Alternatives

Mapbox streets v7 building feature only have the fields:
**extrude , height,  min_height,  type,  underground**
It would be nice to add a unique ID, such as ATN. It would be nice if we could conflate address with building data, to provide address in the building feature.

## Design
Add the data to streets v7, then https://www.mapbox.com/mapbox-gl-js/example/hover-styles/

### Mock-Up

Developer can highlight the individual building if have the data to tell the difference from one building to another.

### Implementation
Needs some guidelines in terms of how to

**Comment by clouddie** [comment]
Hi, I tried this with my own dataset, and I can select each building individually and display information about it.

The issue is that the click only intercepts the base of the building, and not the extruded part when the map is pitched, is there a plan to go "full 3D" ?

**Comment by lbud** [comment]
@clouddie the problem you're encountering is a separate issue — see https://github.com/mapbox/mapbox-gl-js/issues/3122.

@svcninja to my knowledge we don't have plans to add OSM IDs to every building in the Mapbox Streets source, but @ajashton can you confirm this?

**Comment by ajashton** [comment]
We don't have plans to add IDs to buildings. In order to keep vector tiles as small as possible, we merge all buildings that have identical properties. That wouldn't be possible if every building had a unique ID. The IDs themselves also have a noticeable impact on vector tile sizes at zoom levels where building are very dense.

**Comment by lbud** [comment]
👍 thanks @ajashton

**Comment by svcninja** [comment]
Thanks for response.

I have tried to use the "ID" of the building geojson, it seems the "ID" is duplicated for the buildings on the screen. To combine the "ID" with the "height" property, does not give the uniqueness as well. 

The other way I tried is to query the feature on mouse move over, and add the "target" source data and layer dynamically, which performs too bad.  

It seems the option left to me is to create my own dataset in order to efficiently highlight each building. 

@clouddie Can you please share how do you create your own dataset? How can I get the building dataset from the mapbox?

**Comment by svcninja** [comment]
@ajashton @lbud 
Sorry to bother. I also have a question for the "ID" field of the building geojson. Seems the "ID" is not unique, what's it for then? Considering the efficiency...

**Comment by lbud** [comment]
> the "ID" field of the building geojson

Not sure to what you're referring — the `building` layer in the Mapbox Streets vector tiles does not have an ID field. If you're getting this "ID" using something like `queryRenderedFeatures`, that ID is an internal ID used to represent features within an individual vector tile, so those IDs will be duplicated across different tiles.

You may be interested in using a tool like Overpass Turbo to get the buildings you need, with `osm_id`s, from OpenStreetMap, and uploading them as vector tile sets. You may find this guide useful: https://www.mapbox.com/help/overpass-turbo/

**Comment by svcninja** [comment]
Yeah, I was referring to the feature ID. Thanks for explaining. It helps. Have a great holiday!

**Comment by cmarfil** [comment]
From what I've been able to investigate, mapbox does not work if you need to select buildings/extrusions or add hover effects on them... It's a shame..

**Comment by RickoSol** [comment]
> From what I've been able to investigate, mapbox dosn't work if you need to select buildings/extrusions or add hover effects on them... It's a shame..

The situation hasn't changed? Is it still impossible to highlight buildings when hovering?

**Comment by astojilj** [comment]
> > From what I've been able to investigate, mapbox dosn't work if you need to select buildings/extrusions or add hover effects on them... It's a shame..

> The situation hasn't changed? Is it still impossible to highlight buildings when hovering?

This should have been resolved some time ago - zoom level 15 tiles include feature ID, too.

**Comment by RickoSol** [comment]
> > > From what I've been able to investigate, mapbox dosn't work if you need to select buildings/extrusions or add hover effects on them... It's a shame..
> 
> > The situation hasn't changed? Is it still impossible to highlight buildings when hovering?
> 
> This should have been resolved some time ago - zoom level 15 tiles include feature IDs, too.

Thank you for your reply.
Could you please tell me how to solve the problem that not the whole building changes color when hovering over it, but only a part of it?

https://jsfiddle.net/rickopluto/gy21vpt7/

<img width="500" alt="image" src="https://github.com/mapbox/mapbox-gl-js/assets/143557701/6dcf50d5-2a92-48ea-9c77-aff73ad3a240">

**Comment by astojilj** [comment]
The buildings are made of multiple building parts and queryRenderedFeatures returns array while the example code is handling only the first (the closest element to camera).

E.g.

![Screenshot 2023-09-13 at 15 42 18](https://github.com/mapbox/mapbox-gl-js/assets/549216/82cb245d-067f-4771-a5a5-3d59b8acda7d)

Buildings don't include parent child information so that you could make a decision about all the parts that need to be highlighted. I also don't think that intersectionZ (on the screenshot could help).

Maybe processing the part coordinates and finding out overlapping:

![Screenshot 2023-09-13 at 15 42 32](https://github.com/mapbox/mapbox-gl-js/assets/549216/a9be3321-1a15-4ef8-8ac6-eae7225ec486)
