### ISSUE TITLE
Make the distribution build the main NPM entry point

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#3551]
Currently [our readme](https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-browserify) suggests `require('mapbox-gl')` for Browserify-bundled projects and `require('mapbox-gl/dist/mapbox-gl.js')` for all the rest. 

But is there a real need to support building Mapbox GL JS from within a Browserify-bundled project? Would it be better overall to just change the main entry point in the `package.json` to `dist/mapbox-gl-dev.js` and make the workflow the same (`require('mapbox-gl')`) for all module systems?

This would also enable us to safely use a Yarn lockfile in the repo (#3364 ) for producing the same build and not worry about any downstream modules, and also move all `dependencies` into `devDependencies` for a lighter downstream install.

The only cons I can think of:

- Possible code duplication in downstream Browserify-bundled modules that also use some `mapbox-gl` dependencies like `geojson-vt` or `earcut`. Very rare and not a big deal.
- Not being able to require a specific branch/hash of `mapbox-gl` in a Browserify-bundled downstream module. Not a big deal as well.

Thoughts @jfirebaugh @lucaswoj @tmcw?

**Comment by lucaswoj** [comment]
I think this is a good idea. 

Do you have a sense of what precedent exists for similar libraries? 

> Not being able to require a specific branch/hash of mapbox-gl in a Browserify-bundled downstream module. Not a big deal as well.

We could build system that ensures `dist/mapbox-gl.js` is up to date for every commit. A combination of a git precommit hook + a CI test should do the trick. We don't need to do this until we feel the pain of not being able to require a specific branch / hash.

**Comment by mourner** [comment]
> We could build system that ensures dist/mapbox-gl.js is up to date for every commit.

We should avoid committing the build to the repo at all costs. I think it's much easier to just publish a prerelease version in case we have to require a particular version from a downstream module.

**Comment by anandthakker** [comment]
> Not being able to require a specific branch/hash of mapbox-gl in a Browserify-bundled downstream module. Not a big deal as well

If we're going to make 'dist/.../mapbox-gl.js' the main script for the NPM package, then I'd like to advocate that we also support `require('mapbox-gl/js/mapbox-gl.js')` as a way to target a specific commit in a browserify build.  (Alas, this would mean _not_ moving build deps to `devDependencies`.)  The occasions when it's necessary to target a specific commit of a library may be _infrequent_, but I think they can be sort of _severe_ or _urgent_: it's the kind of thing where you're fighting some subtle bug for hours trying to ship something and finally the only workaround involves temporarily forking/patching the lib you're depending on...
