### ISSUE TITLE
Provide default contents for Marker

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3557]
For closer parity with Leaflet markers, the `element` parameter to the `Marker` class should be optional, and the default should be render a traditional marker pin icon similar to ![image](https://cloud.githubusercontent.com/assets/98601/20068106/67b546de-a4cc-11e6-9340-a8ec330220f1.png).

For implementation, I suggest that this use some inline SVG source, so as not to require an external asset.

**Comment by mikehatfield** [comment]
Any progress on this?

**Comment by jfirebaugh** [comment]
@mikehatfield Nope -- want to work on a PR?

**Comment by rahuldhawani** [comment]
Anyone working on this? If not, then I would like to pick it up.

**Comment by jfirebaugh** [comment]
Go for it @rahuldhawani!

**Comment by samanpwbb** [comment]
I recommend this marker, for consistency across gl native / mapbox's static image API: https://github.com/mapbox/makiwich/blob/master/sources/marker-large.svg

**Comment by Qwertie-** [comment]
This would be very helpful. It's overly complex to add a basic marker to the map currently.
