### ISSUE TITLE
Including a username in map-feedback attribution link

### ISSUE THREAD

**Issue by nikhilprabhakar** [mapbox/mapbox-gl-js#3558]
Similar to [this](https://github.com/mapbox/mapbox.js/issues/1187), It would be great if we could include a username in to the map-feedback links. This can be parsed out of the accessToken included with the map to understand the user better, irrespective of the map style they use. And hence will help us give proper support to them.

cc:// @tmcw

**Comment by mollymerp** [comment]
closing here in favor of #4669
