### ISSUE TITLE
Create a project roadmap

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3559]
I recently stumbled across the [GitHub Platform Roadmap](https://developer.github.com/early-access/platform-roadmap/). 

In few words, this page communicates the GitHub platform team's priorities. 

I imagine it is effective at managing external users' expectations and focusing internal engineers' attention.

We should build something similar for GL JS / the GL ecosystem.

**Comment by mapsam** [comment]
I agree! I see this lives on GitHub's developer pages. Could the GL JS equivalent live on mapbox.com/mapbox-gl-js?

I'd be happy to take this on but first would like to think about how it is kept up to date (programmatically or something manual?)

**Comment by lucaswoj** [comment]
A linear roadmap may be a more useful system for us than release milestones. (Though we'll still release every 2 weeks)

**Comment by lucaswoj** [comment]
Here are a couple rough requirements for whatever system we build:

 - store all roadmap state within Github issues / projects / pull requests
 - give us a framework to determine what the top `n` highest priority tasks are (perhaps sort first by priority label then second by issue creation date?)
 - don't show projects so far into the future that they are likely to be bumped out by higher priority projects before we get around to the 
 - inform external users what we're working on next
 - help GL JS engineers figure out what they should work on next

**Comment by mapsam** [comment]
> linear roadmap may be a more useful system for us than release milestones

Yeah, I think starting simple is the way to go. No need to overcomplicate it right away.

I think we could add a new page to the mapbox.com docs at `mapbox.com/mapbox-gl-js/roadmap` (or an equivalent). This will give us an easy spot to point people to, plus we can link to it easily from within the docs.

A brainstorm of ways to organize roadmap content:

1. By **issue labels**: we can create new labels, `roadmap priority 1`/`roadmap priority 2`/etc to query with the GitHub search API
1. Use **github projects** exclusively for the roadmap, anything created as a project is on our roadmap. Some negatives here: there's no way to label projects, so we wouldn't be able to show priority in anything other than date
1. Create a **single "roadmap" project**, which has columns based on priority. This could remove the need for adding issue labels, as well as even a need for mapbox.com integration.

**Comment by lucaswoj** [comment]
cc @isiyu, who is interested in building something similar for another project. If we end up writing any code for this that could be shared, there is interest on other teams at Mapbox.

**Comment by mapsam** [comment]
Adding a new page to the docs, here's a quick example:

<img width="835" alt="screen shot 2016-11-10 at 10 33 48 am" src="https://cloud.githubusercontent.com/assets/1943001/20189272/42f17b80-a731-11e6-9622-ee0a9b57acbe.png">

> there is interest on other teams

It appears we are beginning to use projects for things other than roadmap-specific work, which is totally fine. Even coming up with a re-usable jekyll template is a good start, then content is added manually.

**Comment by mapsam** [comment]
Another layout option:

![image](https://cloud.githubusercontent.com/assets/1943001/20224755/daf49b6a-a7f4-11e6-97c4-2757868e4cfb.png)

Let's plan on updating this manually on a weekly basis (I'll plan on doing this) for now, this will give us some time to figure out our real needs, then we can iterate.

**Comment by mapsam** [comment]
Roadmap is live! Closing this now, we can iterate on it as we use it more.

**Comment by stevage** [comment]
That link is now dead.

**Comment by andrewharvey** [comment]
@stevage see https://github.com/mapbox/mapbox-gl-js/issues/9173
