### ISSUE TITLE
"tiledata", "sourcedata", "styledata" events

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3578]
Users can consume the `data` event if they want a callback whenever the map's data changes. Users who are listening specifically for `data[type=tile]` events are forced to jump through some ergonomically 🙅 hoops. 

```
// 🙅
map.on('data', function(event) {
    if (event.type === 'tile') {
        ...
    }
});

// ✅ 
map.on('tiledata', function(event) {
    ...
});
```

**Comment by lucaswoj** [comment]
Perhaps we should consider dropping `tiledata` events and rolling all `tile` events into `source`. It feels right alongside #3577.

**Comment by hoogw** [comment]
The answer in 2019 is: 

map.once('styledata', loadTiles);   //The listener will be called first time the event fires after the listener is registered.


          map.once('styledata', loadTiles);   //The listener will be called first time the event fires after the listener is registered.


         map.on("styledata", loadTiles);    // will fire multiple 3 times, whenever style changed.  
                                    // event.stopPropagation(); does not work.


         map.on("load", loadTiles);       // only fire 1 time. but when you change base map, use below

      map.setStyle('mapbox://styles/mapbox/' + layerId, {diff: false});

        //  on load event will not fire, which I need it fire to re-load geojson layer. 


           map.on("styledata"    // works fine, but it fire 3 same event at same time, cause load 3 times geojson layer, cause other error when you load 3 times geojson layer at same time.
