### ISSUE TITLE
map#getMinZoom and map#getMaxZoom

### ISSUE THREAD

**Issue by Naimikan** [mapbox/mapbox-gl-js#3585]
Is there any way to get the minimum and maximum zoom?

There are setMinZoom and setMaxZoom but there are no getters.

Thanks.

**Comment by mapsam** [comment]
Hey @Naimikan! You can get the max and min zoom through the [Transform class](https://github.com/mapbox/mapbox-gl-js/blob/47a0e69a8deb42e10e75f2af7ae6018a68a98574/js/geo/transform.js#L43-L55). If your constructor is called `myMap`, that will look like `myMap.transform.maxZoom` or `myMap.transform.minZoom`.

**Comment by lucaswoj** [comment]
:+1: It should be noted that `map.transform` is not part of the public API.

**Comment by mourner** [comment]
Yes, we should add public getters for any setters.

**Comment by Naimikan** [comment]
@mapsam @lucaswoj @mourner Thanks guys!

**Comment by mapsam** [comment]
@Naimikan this was merged into master this morning, we are working on a release `0.27.0` so it should be available shortly.

**Comment by Naimikan** [comment]
Thanks very much! Good job!
