### ISSUE TITLE
Map#queryRenderedFeatures returns the wrong feature

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3591]
**mapbox-gl-js version**: master

### Steps to Trigger Behavior

 0. `git checkout 98b6c121575519b009fe980783b80a1e4778f06a`
 0. `npm run start-docs`
 1. navigate to http://127.0.0.1:4000/mapbox-gl-js/example/queryrenderedfeatures/ 
 2. hover over `San Francisco`

cc @mapsam @mourner @lbud 

### Expected Behavior

the top result in the sidebar includes `"name": "San Francisco"` ([as it does in v0.26.0](https://www.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures/))

<img width="769" alt="screen shot 2016-11-10 at 3 14 43 pm" src="https://cloud.githubusercontent.com/assets/281306/20198248/70fcecfe-a758-11e6-98b5-2ecc459c345b.png">

### Actual Behavior

<img width="766" alt="screen shot 2016-11-10 at 3 12 22 pm" src="https://cloud.githubusercontent.com/assets/281306/20198189/3587187a-a758-11e6-8799-bf86bc205693.png">

**Comment by lucaswoj** [comment]
@mourner @jfirebaugh @brunoabinader @ansis Do any of you have time to look at this bug? It appears to be a bug within the symbol bucket / collision tile / feature index code, a part of the codebase with which I am relatively unfamiliar. 

Rebasing has proved to be extremely difficult due to overlapping qRF bugs and broken intermediate commits. 

# Things I Know For Sure

 - when the "Texas" label is inserted into the collision tile, it has index 5
 - when I hover over the "Texas" label, I consistently get "Ontario" instead
 - "Ontario" has index 44

**Comment by lucaswoj** [comment]
I have managed to bisect the bug to 0a6a7ca634b5e46e5800d595a4646751f0800daa / https://github.com/mapbox/mapbox-gl-js/pull/3418

**Comment by lucaswoj** [comment]
Found the problem, working on a test case.

**Comment by reyemtm** [comment]
queryrenderedfeatures still giving strange behavior, in this case when passed a lngLat object. It's hard to describe just that when given a lngLat object, the map gives back different features at different zoom levels, and never the actual feature at that location. Tested using 0.26.0 & 0.28.0. To recreate simply highlight a feature on click by the methods described in the mapbox example, but use e.lngLat instead of e.point and see what happens.
