### ISSUE TITLE
Map not fetch Layer and Source immediately

### ISSUE THREAD

**Issue by guilemos** [mapbox/mapbox-gl-js#3593]
Hi,

I'm trying to fetch data to the map and then use it immediately through querySourceFeatures/queryRenderedFeatures methods, but layer neither source aren't available right after they've been added.

Reading the documentation, I saw workers don't process data yet. There's a way to force it, so I can use data right after they're added
```
.
.
.
.done(function(data, textStatus, xhr) {
    map.getSource("sLocals_uc").setData(data.geojson);
    map.addLayer(
    {
        "id": "lLocals_uc",
        "type": "symbol",
        "source": "sLocals_uc",
        "layout": {
                    "visibility": "visible",
                    "icon-allow-overlap": true,
                    "icon-ignore-placement": true,
                    "text-allow-overlap": true,
                    "text-ignore-placement": true,
                    "text-font": ["Open Sans Semibold", "Arial Unicode MS Bold"],
                    "text-offset": [0, 0.6],
                    "text-anchor": "top",
            }
    });

        var competitorsIES = map.querySourceFeatures("sLocals_uc", {}); <--- return nothing
        //OR
        var competitorsIES = map.queryRenderedFeatures({layers:["lLocals_uc"]}); <--- return nothing
        .
        .
        .
        several code
        .
        .
        .
});
```

**OBS:** this code is inside of a jQuery ajax call and data is return by this call

**mapbox-gl-js version**: 0.25.1

### Steps to Trigger Behavior

 1. Add/Set Source to the map
 2. Add a layer to the map
 3. Use added data with querySourceFeatures/queryRenderedFeatures

### Expected Behavior
Layer and symbols are added to the map

### Actual Behavior
Layer do not appears on the map then query methods aren't return features immediately. Layers are just added to the map at the end of js execution.

Regards,

**Comment by mapsam** [comment]
Hi @guilemos! I have some initial thoughts, but it will be helpful to have your full script to understand the context of your map. 

Have you included the `map.on('load', function() { ... })` event in your code? The drawing of the map and layers is asynchronous so it's good to wrap any additional layers additions or queries within this event to ensure your map draws successfully. Here's an example of querying features, which adds the airport layer _after_ the map has `load`ed. Then it only queries when the map has moved. https://www.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/

**Comment by guilemos** [comment]
Thank for answer @mapsam!

Yes, I have map load event. But I just use this event to load Source and Layers necessary for main functionality of my application.

After, when user was using some others functionalities, additional layers and sources would be added as needed. I choosed this way because data for these aditional sources are generated during app usage, then at the begining I can't add source on map load cuz there's no data yet.

Layers added within load event work great!

There's no way to add layers and sources after map load event or a way to add a empty source at load event then fit data posteriorly?

**Comment by lucaswoj** [comment]
@guilemos You are correct that source data is not available to be rendered or queried synchronously after being added. Data from the source needs to be downloaded over the network before it can be rendered or queried.

In your case, you have two options:

 1. process the GeoJSON directly without passing it through GL JS

```js
var competitorsIES = data.geojson
```

2. wait for a `data` event that indicates the data has loaded 

```js
map.getSource("sLocals_uc").setData(data.geojson);
map.addLayer(...);

map.on('data', function listener() {
    if (map.loaded()) {
        competitorsIES = map.querySourceFeatures("sLocals_uc", {});
        map.off('data', listener);
    }
});
```

**Comment by amelhaoui** [comment]
Hi @lucaswoj,

I'm facing similar issue above. I tried the second solution you provided but still it's not working.

`source.setData({
                type: 'FeatureCollection',
                features: visible_segments
            });
            
            // wait until data is loaded to process it. Data render/download is async
            map.on('data', function listener() {
** code
result = map.queryRenderedFeatures(area, {
                            layers: LAYERS
                        });
** code

`
my use case is used with the geocoder, so the map stop moving I update the source and wait on 'data' event.
