### ISSUE TITLE
GeoJSONWorkerSource leaks memory: it never deletes old WorkerTiles from removed sources/layers

### ISSUE THREAD

**Issue by Que3216** [mapbox/mapbox-gl-js#3595]
**mapbox-gl-js version**: v0.26.0

### Steps to Trigger Behavior

 1. Open this jsfiddle: http://jsfiddle.net/h93hgmko/1/. The fiddle repeatedly adds and removes a layer and source, each time with a different id.
 2. Take repeated heap snapshots of one of the workers, and you'll see the retained memory usage gradually increase to an unbounded size

### Expected Behavior

Since the amount of data on the map never increases, the retained memory usage of the worker should hit a ceiling.

### Actual Behavior

Retained memory usage of the worker increases unboundedly:

![2a5fd2e3-fbb5-4362-9d40-ed61be855236](https://cloud.githubusercontent.com/assets/793481/20227727/7af46db8-a802-11e6-8fa7-23beee47fd8f.png)

If you add a breakpoint in `geojson_worker_source.js` you can see that the worker is retaining the old WorkerTiles for sources/layers which have since been deleted:

![image](https://cloud.githubusercontent.com/assets/793481/20227760/a4b2e274-a802-11e6-9d3c-64a8b216fa17.png)

It looks like the old data never gets deleted -- the 8 workers collectively have references to all of the data from each previous iteration.

**Comment by mourner** [comment]
Thanks for the report! Related issues: #2607 #3220. This is definitely a priority for us — going to address those shortly.

**Comment by Que3216** [comment]
Thanks for prioritising this! Do you have an estimate of when this may be fixed?

**Comment by Que3216** [comment]
I tried repro-ing this on the master branch of MGL. The behaviour is slightly different, however it still leaks memory (the retained memory of a worker goes up over time). It now correctly erases old WorkerTiles in the loaded hash, however it still leaks GeoJSONVT's in the _geoJSONIndexes:

On MGL 0.26.0:

![2a1a3531-e5af-4102-b3e6-f5dbef67d2cc](https://cloud.githubusercontent.com/assets/793481/20232722/3885a3a8-a81f-11e6-97e0-da322bd79989.png)

On master:

![e0184c88-c7b8-4d5f-9814-9e95f9c5d1d0](https://cloud.githubusercontent.com/assets/793481/20232730/3e4a4b4a-a81f-11e6-8c3e-cdef00e733c2.png)

(good)

![ca601440-deea-4924-a2a7-c637355cb902](https://cloud.githubusercontent.com/assets/793481/20232736/421a8348-a81f-11e6-9dc3-230375dd30a8.png)

(bad)

**Comment by Que3216** [comment]
Each GeoJSONVT seems to be separate objects, and so are taking up mem: _geoJSONIndexes["points_1"].tiles[0].features !== _geoJSONIndexes["points_2"].tiles[0].features

**Comment by Que3216** [comment]
I've pushed a quick PR that removes old sources from _geoJSONIndexes https://github.com/mapbox/mapbox-gl-js/pull/3602. It appears to help, however the retained memory on the worker thread still grows over time. I can't spot any remaining problems immediately by browsing the references from the worker.

**Comment by Que3216** [comment]
These fixes appear to slow the memory growth down by an order of magnitude.

**Comment by Scarysize** [comment]
Sorry to comment on closed issue. Do/Did raster sources have an similar issue (memory leak) when they are being removed?

**Comment by mourner** [comment]
@Scarysize this seems to warrant a new GitHub issue. Can you report?

**Comment by Scarysize** [comment]
Will do. Thanks for the fast response.
