### ISSUE TITLE
Coveralls doesn't work with external PRs

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#3603]
I noticed that all PRs made by external contributors (not repo collaborators) never get the Coveralls check passed — it's always hanging waiting for info like this:

![image](https://cloud.githubusercontent.com/assets/25395/20234529/b4e57038-a831-11e6-93f0-042a3cffada3.png)

We should investigate what's going on and either fix this or disable Coveralls in such cases.

**Comment by lucaswoj** [comment]
Yes. This is really annoying & poor form. 

I have an existing ticket open about this here: https://github.com/mapbox/mapbox-gl-js/issues/2465
