### ISSUE TITLE
0.27.0 broken in IE11 (Object doesn't support property or method 'fromCodePoint')

### ISSUE THREAD

**Issue by aleksejleonov** [mapbox/mapbox-gl-js#3606]
Looks like 0.27.0 broken in IE11:
![screen shot 2016-11-12 at 17 56 15](https://cloud.githubusercontent.com/assets/241582/20239154/86829eba-a902-11e6-8232-40a59911e5ef.png)

Tested on IE11 (ver. 11.447.14393.0, Windows 10 with latest updates inside Parallels VM).
Edge, Chrome and other browsers on same VM works fine.

IE 11 console output:
```
SCRIPT438: Object doesn't support property or method 'fromCodePoint'
glyph_source.js (75,19)
```
![screen shot 2016-11-12 at 18 08 54](https://cloud.githubusercontent.com/assets/241582/20239176/126011ce-a903-11e6-8f39-daefd9fddb72.png)

**mapbox-gl-js version**: 0.27.0

### Steps to Trigger Behavior

 1. Open https://www.mapbox.com/mapbox-gl-js/examples/ in IE11 (Win 10).

### Expected Behavior

Map should loads successfully (or alert saying browser doesn't support Mapbox GL).

### Actual Behavior

Map doesn't load (and no "doesn't support Mapbox GL" alert).

**Comment by aleksejleonov** [comment]
`String.fromCodePoint()` not supported by IE at all.
Also, it's not supported by Safari 9.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/String/fromCodePoint

<img width="549" alt="screen shot 2016-11-12 at 18 18 30" src="https://cloud.githubusercontent.com/assets/241582/20239236/69f35832-a904-11e6-992b-188aa9c1c10f.png">

Same problem with `String.codePointAt()`.

With next 2 small polyfills map start working fine in IE11:
https://github.com/mathiasbynens/String.fromCodePoint
https://github.com/mathiasbynens/String.prototype.codePointAt

**Comment by mourner** [comment]
Good catch! We should get 0.27.1 out with a fix. cc @lucaswoj @1ec5

**Comment by jfirebaugh** [comment]
Unfortunately, we won't be able to use those polyfills directly: https://github.com/mathiasbynens/String.fromCodePoint/issues/4.

**Comment by 1ec5** [comment]
We don’t actually need `String.fromCodePoint()`, do we? `String.fromCharCode()` is sufficient for the Basic Multilingual Plane, and we don’t support rendering anything in the astral planes (mapbox/mapbox-gl#29).
