### ISSUE TITLE
mapbox-gl-geocoder example broken needs new release

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#3607]
The example at https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder/ is broken since the 0.27.0 release since mapbox-gl-geocoder needs to be updated to 1.3.2, perhaps at https://github.com/mapbox/mapbox-gl-js/blob/master/docs/_data/plugins.json#L70

Although 1.3.2 is released as per https://github.com/mapbox/mapbox-gl-geocoder/releases, the API endpoint https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v1.3.2/mapbox-gl-geocoder.js isn't there yet.

**Comment by tmcw** [comment]
Tracking issues are:

* mapbox-gl-geocoder https://github.com/mapbox/mapbox-gl-geocoder/issues/67
* mapbox-gl-js https://github.com/mapbox/mapbox-gl-js/issues/1835
