### ISSUE TITLE
Map data is not updated

### ISSUE THREAD

**Issue by hanchao** [mapbox/mapbox-gl-js#3609]
**mapbox-gl-js version**: v0.23.0

### Steps to Trigger Behavior

 1. open http://hanchao.github.io/vectormap/#19.25/36.91185/121.58543
 2. open http://www.openstreetmap.org/#map=19/36.91191/121.58541
 3. The road is edited five months ago. 

### Expected Behavior

Map data is updated

### Actual Behavior

Map data is not updated

**Comment by jingsam** [comment]
Try this [link](https://www.mapbox.com/map-feedback/#/121.58543/36.91185/20) to feedback.

**Comment by hanchao** [comment]
@mourner Data has been modified before five months, but the vector tiles are not updated.

An error occurred while generating a vector tile
