### ISSUE TITLE
Functions for layout properties

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#361]
Currently bucket rules can only be static, which means attributes important for point and label placement (`fontSize`, `padding`, `size`, `spacing`, etc.) are set to a single value through the whole zoom range.

Considering that buckets are parsed individually for each tile, which has a zoom value, we can introduce the same functions we use for other rules to bucket rules, with the only difference that the values will be calculated based on tile zoom as opposed to arbitrary fractional zoom. It is also important in case we ditch buckets in user styles, to be consistent.

This issue extends #317

**Comment by lbud** [comment]
I assume this would only be for numeric layout properties?

**Comment by jfirebaugh** [comment]
Yes, for now. Though https://github.com/mapbox/mapbox-gl-style-spec/issues/237 could apply to equally to paint and layout properties.
