### ISSUE TITLE
Opaque polygon layers get covered by transparent polygon layers in 0.27

### ISSUE THREAD

**Issue by bcoakleybp** [mapbox/mapbox-gl-js#3612]
**mapbox-gl-js version**: 0.27

### Steps to Trigger Behavior

 1. Create a style in Mapbox Studio with an opaque polygon layer on top of a transparent polygon layer.
 2. Display in Mapbox GL JS

### Expected Behavior

In 0.26.0 and previous, the opaque polygon shows up on top:
![building-0 26](https://cloud.githubusercontent.com/assets/23461924/20280692/76cfab28-aa7b-11e6-81aa-130c4ac7e1b5.png)

### Actual Behavior
In 0.27, the transparent polygon covers the opaque polygon.
![building-0 27](https://cloud.githubusercontent.com/assets/23461924/20280707/8a08b7c0-aa7b-11e6-9867-3fd9f952fe30.png)

**Comment by lucaswoj** [comment]
Thank you for the bug report. I was unable to reproduce this bug with a minimal test case. Can you please update this jsbin so that it demonstrates the bug and then re-open the ticket? Thank you!

http://jsbin.com/deboparife/edit?html,output

**Comment by bcoakleybp** [comment]
I've updated the jsbin to use a Studio style that demonstrates the issue I'm seeing.  The style itself is pretty minimal:

Building footprints, white, 100% opacity
Tax parcels, black, 50% opacity
Mapbox Streets

I'm attaching the zipped style as well.

If you switch the js and css back and forth between 0.26.0 and 0.27.0, you can see the difference in rendering.
[civjizok200592ko4gd1x2omr.zip](https://github.com/mapbox/mapbox-gl-js/files/592073/civjizok200592ko4gd1x2omr.zip)

**Comment by lbud** [comment]
🙏  thanks for your report @bcoakleybp! Have a fix in the works at https://github.com/mapbox/mapbox-gl-js/pull/3628.
