### ISSUE TITLE
Document Control interface

### ISSUE THREAD

**Issue by scothis** [mapbox/mapbox-gl-js#3613]
The Control object had significant changes introduced in 0.27, however, the interface is not documented. There are several links to the missing Control docs https://www.mapbox.com/mapbox-gl-js/api/#Control

**Comment by tmcw** [comment]
Are you aware of the [IControl documentation](https://www.mapbox.com/mapbox-gl-js/api/#IControl)?

**Comment by scothis** [comment]
Thanks @tmcw. We should updated the links in [Map#addControl](https://www.mapbox.com/mapbox-gl-js/api/#Map#addControl) and [Map#removeControl](https://www.mapbox.com/mapbox-gl-js/api/#Map#removeControl)
