### ISSUE TITLE
Maps should not render 'bleeding' white lines

### ISSUE THREAD

**Issue by helmi03** [mapbox/mapbox-gl-js#3617]
mapbox-gl-js version: 0.27.0

### Steps to Trigger Behavior

 1. open https://www.mapbox.com/mapbox-gl-js/examples/ (see https://jsfiddle.net/vycc3o8c/)
 2. zoom 11.5 at Kuala Lumpur, Malaysia

### Expected Behavior
Maps rendered nicely

### Actual Behavior
Maps rendered with 'bleeding' white lines. see http://imgur.com/nkddgM0

**Comment by mourner** [comment]
Yes, seems to be the same issue as #3618. Investigating now.

**Comment by mourner** [comment]
@jfirebaugh my hunch was right — bisected this down to https://github.com/mapbox/mapbox-gl-js/pull/3461. We have not caught this because we don't have render tests where line buffers exceed the limit.

**Comment by mourner** [comment]
@helmi03 thanks for the report! We have identified the cause and are going to fix this ASAP.

**Comment by jfirebaugh** [comment]
I confirmed that this regressed in b9d95095c63a8e0193b6ee391ab308e75e1ecea3, but it doesn't seem related to overflowing the segment limit. It's happening even with less than 2^16 vertices.

**Comment by jfirebaugh** [comment]
It was an overflow error after all -- it _should_ have ben overflowing, but wasn't due to a type error.
