### ISSUE TITLE
Rendering artifacts regression in 0.27.0 for linestrings with 'line-join':'round'

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#3618]
Hey,

we're seeing rendering artifacts for LineStrings with `line-join: round` with the latest release (0.27.0 / Master) that were not present in 0.23.  It should be noted that the tiles are custom made, adheres to the VT2 spec and the console log is not throwing any errors.

I'm happy to provide example vector tiles if needed for debugging.

**mapbox-gl-js version**: Master

### Steps to Trigger Behavior

The following layer causes the rendering issue:

```
{
  'id': 'DEPCNT',
  'type': 'line',
  'source': 'composite',
  'source-layer': 'DEPCNT',
  'minzoom': 8,
  'filter': ['all', ['>','valdco',depth],['==','$type','LineString']],
  'layout': {
  	'line-join':'round'
  },
  'paint': {
  	'line-color': {
    	'stops': [[8, 'hsl(200,100%,100%)'], [9, 'hsl(195,100%,76%)']]
    },
    'line-width': {
      'base': 1.5,
      'stops': [
        [
          11,
          0.3
        ],
        [
          16,
          1
        ]
      ]
    }
  },
  'paint.night': {
    'line-color': {
    	'stops': [[8, 'hsl(200,100%,3%)'], [9, 'hsl(195,100%,16%)']]
    },
  },
  'paint.contrast': {
    'line-color': {
    	'stops': [[8, 'hsl(200,100%,100%)'], [9, 'hsl(195,100%,65%)']]
    },
    'line-width': {
      'base': 1.5,
      'stops': [
        [
          11,
          0.8
        ],
        [
          16,
          1.6
        ]
      ]
    }
  }
}

```

Removing `line-join` resolves the issue:

```
'layout': {
  	'line-join':'round'
  }
```

### Expected Behavior

Rendering in 0.23.0 / removal of `line-join:round`

![skjermbilde 2016-11-15 10 21 43](https://cloud.githubusercontent.com/assets/5638107/20300101/dbca5bf2-ab1d-11e6-8eab-3f40aaec4b08.png)

### Actual Behavior

Rendering in 0.27.0 with `line-join:round`

![skjermbilde 2016-11-15 10 21 24](https://cloud.githubusercontent.com/assets/5638107/20300110/e7bcd85e-ab1d-11e6-8bee-df6fdf9c984c.png)

**Comment by mourner** [comment]
@kristfal Can you look which release exactly broke it? 0.26 or earlier? Also, do you have that tile endpoint we could test against? Preferably a live minimal JSFiddle test case.

@jfirebaugh could it be related to the segments drawing refactor? I can't think of anything else we changed for line.

**Comment by kristfal** [comment]
@mourner: Check your PM for fiddle.

No artifacts in 0.26. Probably dupe of #3617 btw.

**Comment by kristfal** [comment]
@mourner Digging deeper, it seems like this may not be caused by `line-join`, but some other underlying issue. As far as I can tell, it only affects a single `line` layer in a style.

**Comment by mourner** [comment]
@kristfal Thanks, got the fiddle! Bisecting now.

**Comment by mourner** [comment]
Going to close in favor of #3618 so that we can update on the matter in one place.
