### ISSUE TITLE
change icon clickable bbox

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#3619]
I create my own icon with a typical marker which have a shadow on the ground. Because of this, the clickable area of the marker overlaps other marker. Is it possible to shrink the clickable area of the icon?
<img src='https://s11.postimg.org/9532hgpm7/icon.png' border='0' alt='postimage'/>

**Comment by jfirebaugh** [comment]
Hi @strech345 -- there's no built in support for this, but with Marker, you control the DOM content and event bindings. So you could, for example, use separate images for the marker and shadow, and bind the click event only to the former, or check the coordinates in the click handler and filter them there.

**Comment by strech345** [comment]
Thanks @jfirebaugh 
thats sounds good. I will check it.
Would be nice if there could be parameter for the marker to set the clickable area also.
