### ISSUE TITLE
constant high CPU from raster sources

### ISSUE THREAD

**Issue by kriscarle** [mapbox/mapbox-gl-js#3620]
Raster sources appear to stuck in a render loop and keep the tab at a constant high CPU usage.. The profiler seems to confirm that it is a render method. This occurs with examples like https://www.mapbox.com/mapbox-gl-js/example/map-tiles/ though for me they stay around 30% CPU. On a more complex map I've seen a sustained 150% CPU and my Macbook was maxed out.

**mapbox-gl-js version**: 0.27 (doesn't happen with 0.20.1)

### Steps to Trigger Behavior

 1. Go to: https://www.mapbox.com/mapbox-gl-js/example/map-tiles/
 2. Open chrome task manger / profiler
 3. Compare with other non-raster examples

### Expected Behavior
In the last version I was using (0.20.1) CPU drops to near zero after the map renders the first time. You can see an example of that here https://mapforenvironment.org/layer/map/85/Tree-Cover-Loss-2000-2014#10.86/2.3114/22.8861

### Actual Behavior
Maps with raster sources are stuck in a render loop and CPU stays high
<img width="1105" alt="task_manager_-_google_chrome_and_add_a_raster_tile_source___mapbox" src="https://cloud.githubusercontent.com/assets/2431570/20315252/32f6dd44-ab2b-11e6-8d9c-8fbef41ecd30.png">

<img width="754" alt="developer_tools_-_https___www_mapbox_com_mapbox-gl-js_example_map-tiles_" src="https://cloud.githubusercontent.com/assets/2431570/20315471/f9b163be-ab2b-11e6-844e-81f4f4bd762a.png">

**Comment by kriscarle** [comment]
appears to be related to #3398

**Comment by mourner** [comment]
@kriscarle yes, it's the same issue. Tracking a fix at https://github.com/mapbox/mapbox-gl-js/pull/3399
