### ISSUE TITLE
Marker positioning incorrect after setMaxBounds() or fitBounds().

### ISSUE THREAD

**Issue by fanwashere** [mapbox/mapbox-gl-js#3626]
**mapbox-gl-js version**: latest

### Steps to Trigger Behavior

 1. Add some markers.
 2. Use `setMaxBounds()` to set a maximum boundary.
 3. Use `setZoom()` to set an arbitrary zoom.
 4. Use `setCenter()` to set an arbitrary center (that is within the bounds).
 5. Use `setMaxBounds(null)` to remove the maximum boundary.
 6. Use `fitBounds()` to go to some arbitrary bounds. 

### Expected Behavior
Markers should appear where they should be.

### Actual Behavior
Markers don't appear where they should be. Upon inspecting the element, their `transform: translate()` is some huge number like `transform: translate(20000px, 750px)`. The y-translate is correct, but the x-translate has been as high as 35000px. So they are on the map, but just translated very far to the right. 

### Temporary Solution
I have been able to mitigate this extreme translation by doing:
```
map.setMaxBounds(myMaxBounds);
map.setCenter([0, 0]);
```
The above appears to put the markers in their correct places again, at least temporarily. I can `setMaxBounds(null)` and `fitBounds()` freely afterwards with the markers in the correct places. 

### My Guess
The markers' `transform: translate()` may be large numbers, but it may make sense if your map was really zoomed in. If you were at zoom level 10 or something, the marker should really be 20000px to the right since the world might be 30000px wide at that point. I feel like this is some problem with with `setMaxBounds(null)` or `fitBounds` and them not keeping the zoom level or marker positions updated after a change.

**Comment by mourner** [comment]
Thanks for the report! Can you set up a minimal JSFiddle test case for this?
