### ISSUE TITLE
text-color identity function is throwing WebGLRenderingContex error

### ISSUE THREAD

**Issue by bewithjonam** [mapbox/mapbox-gl-js#3629]
**mapbox-gl-js version: 0.26.0**:

```
map.addLayer({
    'type': 'symbol',
    ....
    'paint':{
      'text-color': {
      	'type': 'identity',
      	'property': 'color'
      }
    }
  });
```

If I use stops(interval function) rather identity function, it works. But i want to set the color from the geojson source based on the features property.

### Steps to Trigger Behavior

 1. https://jsfiddle.net/bewithjonam/cn4nczrn/2/

### Expected Behavior
The text should render with color

### Actual Behavior
MapboxGl throwing error and map is not rendering.

> draw_symbol.js:200 Uncaught TypeError: Failed to execute 'uniform4fv' on 'WebGLRenderingContext': No function was found that matched the signature provided.(…)

**Comment by jfirebaugh** [comment]
`text-color` doesn't support property functions yet. ⇢ #2730
