### ISSUE TITLE
Rendering Mapbox Studio Style as base layer

### ISSUE THREAD

**Issue by dshakya** [mapbox/mapbox-gl-js#3630]
## How to reproduce

- Leaflet version I'm using:1.0.1
- Browser (with version) I'm using: Firefox 49.0.2
- OS/Platform (with version) I'm using: Windows 7 Enterprise
- step 1: Created Mapbox Style in Mapbox Studio
- step 2: Added the tile normally using L.tilelayer()
- step 3: Map appears in the browser but few of the layers are not rendered completely. Only partial render and not at all most of the times.

When I load the same Mapbox style using Mapbox GL API (mapbox-gl-js), the layers load fine.

## What behaviour I'm expecting and which behaviour I'm seeing

All layers of the map to be rendered properly with L.tilelayer()

## Minimal example reproducing the issue

Using Leaflet API: http://playground-leaflet.rhcloud.com/vaxe
Same base map with using Mapbox GL API.: http://playground-leaflet.rhcloud.com/naxil

I posted this in Leaflet Issue and have been asked to put it forward to Mapbox team. Please see here: 

https://github.com/Leaflet/Leaflet/issues/5102

**Comment by mourner** [comment]
As you stated, this is not a Mapbox GL JS issue. You should report this to support@mapbox.com.

**Comment by dshakya** [comment]
Thanks @mourner . Will do so.

**Comment by dshakya** [comment]
For the sake of completeness, the issue was fixed by adding @2x for retina display. This is how Mapbox renders maps.

https://www.mapbox.com/api-documentation/#retina
