### ISSUE TITLE
removeControl doesn't remove control elements from the map

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#3638]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. addControl(control)
 2. removeControl(control)

### Expected Behavior

The control's container element should be removed from the map

### Actual Behavior

It isn't. Since it's the map's responsibility to add the element, should it also be the map's responsibility to remove that element?

---

_May be a bad idea, just realized that this situation would happen_

**Comment by mollymerp** [comment]
Which controls are you seeing this with? I just tested `GeolocateControl` and `NavigationControl` and the containers were removed on `map.remove(control)`.

**Comment by formula4** [comment]
I also am having this issue with the Directions control.

**Comment by msirghi** [comment]
@formula4 Just tested _removeControl()_. My application should display directions and on button click totally remove control. Came with this kind of solution:
`this.mapRef.removeControl(this.direction)
`

Where direction is:
 ```
this.direction = new MapboxDirections({
        accessToken: mapboxgl.accessToken,
        unit: 'metric',
        interactive: false,
        profile: 'mapbox/driving',
});
```

Hope it helps.
