### ISSUE TITLE
Data driven styling for line-width attribute

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-js#3646]
Could this feature be provided?

A use case example would be showing traffic volumes on a road network. This could be shown using colours but it would be useful to also be able to change the line width to represent higher flows (e.g. https://mts0.googleapis.com/mapslt?hl=en-US&lyrs=ft%3A15BvhPxHqMQX6aOprSJOVfVTGsC0KoYUjmLl-ElT3%7Csc%3Acol2%7Csg%3A%7Ctmplt%3A2%7Cy%3A2&x=253&y=165&z=9&w=256&h=256&source=apiv3&token=101285).

**Comment by jfirebaugh** [comment]
In progress, see #2729 / #3033.
