### ISSUE TITLE
[Request] flyToAtTime() / jump to a specific time within a flyTo

### ISSUE THREAD

**Issue by vespakoen** [mapbox/mapbox-gl-js#3647]
Hi!

I have created a renderer for mapbox-gl-js using electron so I can record videos of map transitions.

What I would like to be able to do is jump to a specific time within a flyTo animation, so I set the map at a specific point within an animation.
Then I can run the renderer to take a screenshot (which takes a while) and when that has finished move to the next frame.

I guess this is really an edge case, so I won't mind patching some methods myself.

Perhaps you can point me in the right direction?

Thanks!

**Comment by mourner** [comment]
This is an edge case so probably not worth increasing the API surface for. However, I think you can accomplish this now by subscribing to `Map` `move` event while `flyTo` animation is in progress, and capturing map state with `map.getCenter()`, `map.getBearing()`, `map.getPitch()` etc. on every frame into an array along with time, and then using it for capturing screenshots. This will get a bit easier when #3583 lands.

**Comment by vespakoen** [comment]
Thanks for the comment, found it myself:

```js
function defaultInterpolate(a, b, t) {
  return (a * (1 - t)) + (b * t);
}

function interpolateJump(sequence, t, options) {
  const interpolate = sequence.interpolate || options.interpolate || defaultInterpolate
  const interpolateCoord = sequence.interpolateCoord || options.interpolateCoord || interpolate
  const interpolatePitch = sequence.interpolatePitch || options.interpolatePitch || interpolate
  const interpolateZoom = sequence.interpolateZoom || options.interpolateZoom || interpolate
  const interpolateBearing = sequence.interpolateBearing || options.interpolateBearing || interpolate
  const { from, to } = sequence
  const center = [interpolateCoord(from.center[0], to.center[0], t), interpolateCoord(from.center[1], to.center[1], t)]
  const pitch = interpolatePitch(from.pitch, to.pitch, t)
  const zoom = interpolateZoom(from.zoom, to.zoom, t)
  const bearing = interpolateBearing(from.bearing, to.bearing, t)
  return {
    center,
    pitch,
    zoom,
    bearing
  }
}
```
