### ISSUE TITLE
Notify worker of map removal

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3652]
`style._remove()` should send a message to the worker, so that `this.workerSources[mapId]` and any other worker-side state is cleaned up.

https://github.com/mapbox/mapbox-gl-js/pull/3602#issuecomment-261392321

**Comment by asheemmamoowala** [comment]
@arindam1993 Could this be related to the memory growth in #9126. Is this still an a problem?

**Comment by arindam1993** [comment]
No, we terminate the workers so all resources are feed up automatically as a result.
But we should do something similar if we introduce an ability to control the worker pool externally of `Map` in our api.
