### ISSUE TITLE
Consolidate camera/transform state with style state

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#3654]
As a followup to [smart setStyle](https://github.com/mapbox/mapbox-gl-js/pull/3621), move the camera state management into `Style` (perhaps renamed to `StyleState` a la https://github.com/mapbox/mapbox-gl-js/issues/3650), so that camera state can be included as a top-level property to `Map#setStyle` (and `Style#setState`).

 - Accept camera/transform state as top-level setState property (includes zoom, center, pitch, bearing, minzoom, maxzoom, lngRange, latRange)
 - Move transform-mutating stuff from Camera to Style
 - Refactor Camera methods to use Style#setState
   - tricky thing here is transitions; can Camera's multi-frame easing code be reworked to use setState efficiently?

I think the second and third steps here may become _much_ simpler after https://github.com/mapbox/mapbox-gl-js/pull/3583

**Comment by titouancreach** [comment]
Thanks for answering, I didn't see the issue. This issue is opened since Nov 2016, do you have any plan to work on that ?

Tanks

**Comment by jfirebaugh** [comment]
I think we should keep `Style` and `Camera` as separate state. Typically one does _not_ want the camera to change when changing the style. In the uncommon case where you do, you can simply make two method calls.
