### ISSUE TITLE
Halfwidth punctuation prevents ideographic line breaking

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#3658]
**mapbox-gl-js version**: 0.27.0

A point-placed label that contains only Chinese characters except for an interpunct (·) uses word-based line breaking, whereas it [should use ideographic line breaking](https://github.com/mapbox/mapbox-gl-js/blob/e7e50c08339efa086bdc13c2bda2d58ae9e674fc/js/util/script_detection.js#L20). Chinese uses an interpunct to delimit transliterated Western first and last names. As a common punctuation mark in point of interest names, it shouldn’t keep a POI from getting the improved line breaking behavior we added in #3420.

<img width="113" alt="interpunct" src="https://cloud.githubusercontent.com/assets/1231218/20415130/4403be1a-aceb-11e6-82f5-91936c2841df.png">

Technically [other punctuation marks](https://github.com/mapbox/mapbox-gl-js/blob/e7e50c08339efa086bdc13c2bda2d58ae9e674fc/js/util/script_detection.js#L154) like the solidus shouldn’t turn off ideographic line breaking, either, but those punctuation marks are more likely to occur in bilingual labels where we definitely do need to err on the side of word-based line breaking.

/cc @nickidlugash @xrwang

**Comment by 1ec5** [comment]
@ian29 spotted this case of `(` turning off ideographic line breaking:

![pasted image at 2016_11_20 22_46](https://cloud.githubusercontent.com/assets/1231218/20473582/88f54fb0-af76-11e6-8868-24e377a4faa9.png)

ASCII parentheses can go either way. We probably should treat all the characters in `charHasNeutralVerticalOrientation()` as neutral for line breaking as well as uprightness, so that they only turn off ideographic line breaking if adjacent to a clearly non-ideographic character.

**Comment by nickidlugash** [comment]
Per chat with @1ec5 and @ChrisLoer, we should implement better line breaking behavior for ASCII parentheses, beyond just treating them as neutral for line breaking. Options we discussed so far:

1. Do balanced (ideographic) breaking but automatically move the line break from after any ( to before it, aka "deleting" any punctuation and adding them back in after figuring out where the line breaks should be for a balanced label. 

2. Treat ideographic characters like alphabetic characters within a parentheses.

@1ec5 @ChrisLoer please feel free to expand upon my extremely rough summary of our chat! Thank you! 🙏

**Comment by 1ec5** [comment]
> Do balanced (ideographic) breaking but automatically move the line break from after any ( to before it, aka "deleting" any punctuation and adding them back in after figuring out where the line breaks should be for a balanced label.

Here’s a more detailed explanation of what I’m imagining: around [here](https://github.com/mapbox/mapbox-gl-js/blob/5e109674c99fa5ce7372e5dc696036ee012fbaba/js/symbol/shaping.js#L145), if the next character is a `(` that would ordinarily be a line break point, preemptively make the current character the line break point. Also, if the current character is a `)` that would ordinarily be a line break point, defer the break until the next character.

**Comment by ChrisLoer** [comment]
OK, I see, (1) is just tweaking which side of a newline the parenthesis appears. So 废话废话(废话废话)废话废话 with a ~four character `maxWidth` would wrap to:

废话废话
(废话废话)
废话废话

While 废话废话废话(废话废话废话) would wrap to:

废话废话
废话(废话
废话废话)

Using "treat ideographic characters like alphabetic characters within a parentheses", we'd get:

废话废话
废话
(废话废话废话)

**Comment by ian29** [comment]
@1ec5 @nickidlugash @ChrisLoer do yall know when you expect to have a fix for this. totally fine if this is a v. rough estimate.

**Comment by ChrisLoer** [comment]
@ian20 I talked with @nickidlugash this morning, and I think we're still trying to figure out what we want for handling punctuation in general. The "interpunct" fix that started this issue is in https://github.com/mapbox/mapbox-gl-js/pull/3725, and hopefully we will merge that into gl-js soon.

**Comment by ChrisLoer** [comment]
Closing with PR #3743 -- there's no longer any special treatment for ideographic characters, so there's no way for it to get turned "off". That PR did not include special treatment for any "brace like" punctuation like the "title marks", to prevent opening or closing braces from dangling across line breaks. @nickidlugash , if you get a chance to open an issue with the set of braces we want to handle, it will be easy for me to plug in to the code.

**Comment by 1ec5** [comment]
> if you get a chance to open an issue with the set of braces we want to handle, it will be easy for me to plug in to the code.

#3811
