### ISSUE TITLE
SymbolBucket.prototype.isEmpty throws TypeErrors on startup

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#3663]
**mapbox-gl-js version**: Master

SymbolBucket randomly (roughly 1 out of 10 times) throws errors on startup. It is probably a race condition as I've only seen it happen on slower devices (iPhone 5s) which _might_ be triggered by a map resize during map initialization. Everything seems to be working fine when the map is running. 

Error:

```
TypeError: undefined is not an object (evaluating 'this.arrays.icon')
```

Offending code:

```
SymbolBucket.prototype.isEmpty = function isEmpty () {
    return this.arrays.icon.isEmpty() &&
        this.arrays.glyph.isEmpty() &&
        this.arrays.collisionBox.isEmpty();
};
```

The safari inspector is kind enough to not provide stack traces for this error 😢 , I'll keep looking for a proper stack trace.

### Expected Behavior

Errors should not be thrown.

### Actual Behavior

Errors are thrown.

**Comment by elliotleelewis** [comment]
I get this error a lot since updating I believe to v0.27.0, happens in quick succession too. For instance, I'll get 10 or 15 errors exactly like that at once. I get this error on all browsers on my 2015 MacBook Pro so don't think its to do with device speed, at least for me.

**Comment by ggho** [comment]
I am encountering a similar issue updating from v25.0.1 to v0.27.0 or v0.28.0.

In my case, this error got thrown out after Map#setFilter was called and it does not happen if I don't call Map#setFilter. 

For instance, I have a mousemove event listener which handle hover effect on a symbol layer (which would call Map#setFilter when a symbol is being hovered). After a few calls of Map#setFilter (approximately 4 to 5 calls), this error would be thrown consecutively a couple of times (from 4 - 1x times randomly). 

Error captured in Chrome:
`blob:http://localhost:9001/fcaf0a79-234f-4812-bc7d-237aabb2f995:3309 
Uncaught TypeError: Cannot read property 'icon' of undefined
isEmpty @ blob:http://localhost:9001/fcaf0a79-234f-4812-bc7d-237aabb2f995:3309
(anonymous function) @ blob:http://localhost:9001/fcaf0a79-234f-4812-bc7d-237aabb2f995:4872
serializeBuckets @ blob:http://localhost:9001/fcaf0a79-234f-4812-bc7d-237aabb2f995:4871
done @ blob:http://localhost:9001/fcaf0a79-234f-4812-bc7d-237aabb2f995:4785
gotDependency @ blob:http://localhost:9001/fcaf0a79-234f-4812-bc7d-237aabb2f995:4822
(anonymous function) @ blob:http://localhost:9001/fcaf0a79-234f-4812-bc7d-237aabb2f995:4839
receive @ blob:http://localhost:9001/fcaf0a79-234f-4812-bc7d-237aabb2f995:6711
`

**Comment by Zakay** [comment]
+1
