### ISSUE TITLE
add geometry parameter to querySourceFeatures

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#3666]
### What problem are we trying to solve?
Being able to either get information from a Source without it being visible on the map.

### What use cases are we trying to accommodate?
Point in polygon tests is one. eg. where the point is the mouse cursor and the polygon is coming from a source not visible/rendered on the map.

## Design

In https://github.com/mapbox/mapbox-gl-js/issues/2402 it was decided that `queryRenderedFeatures` will not return features not rendered on the map, which rules out solutions like this https://github.com/mapbox/mapbox-gl-js/issues/2402#issuecomment-206127866.

However the complimentary `querySourceFeatures` doesn't accept a geometry like `queryRenderedFeatures` so it won't work for point-in-polygon tests either, as far as I understand.

Current workarounds such as setting the opacity to 0.01 so that it's included in `queryRenderedFeatures` or obtaining the whole geometries from `querySourceFeatures` and using turf's point in polygon test, or using the [tilequery api](https://www.mapbox.com/api-documentation/#retrieve-features-from-vector-tiles), aren't ideal.

### Mock-Up

As per https://github.com/mapbox/mapbox-gl-js/issues/2402#issuecomment-206462697 what about including a geometry option in `querySourceFeatures` just like `queryRenderedFeatures` does?

**Comment by lucaswoj** [comment]
I'm in favor of adding a `geometry` argument to `querySourceFeatures` to make it's signature more similar to `queryRenderedFeatures`.

That being said, there's no obvious way to implement this feature internally that would be more efficient than filtering the output of `querySourceFeatures` downstream. Because of this, such a feature will be low priority for the GL JS team. We'd happily consider a PR with tests 😄

**Comment by mourner** [comment]
Closing as something that didn't get enough interest from users and maintainers to address. Also feels nice to close an issue with an ominous number like that :)
