### ISSUE TITLE
Labels become momentarily garbled while zooming

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3669]
![7325884c-c5a4-11e5-83e0-d4323c606577](https://cloud.githubusercontent.com/assets/281306/20494538/40858aea-afd2-11e6-897b-1afc5d7bf7e1.gif)

Regression of #2012 and #3086

We should use the test-suite operations API to create a regression test.

**Comment by mourner** [comment]
This regressed between 0.26 and 0.27 and I have a suspicion that I'm to blame. Bisecting now.
