### ISSUE TITLE
fitBounds with minLat -90 causes "failed to invert matrix" due to Y = -Infinity

### ISSUE THREAD

**Issue by sagenschneider** [mapbox/mapbox-gl-js#3673]
I believe there is an error in transform.js due to rounding problems of JavaScript.

For https://api.tiles.mapbox.com/mapbox-gl-js/v0.22.0/js/geo/transform.js  line 226, it has the following code:

```javascript
var y = 180 / Math.PI * Math.log(Math.tan(Math.PI / 4 + lat * Math.PI / 360))
```
Providing lat = -90 has the following problem:
* `lat * Math.PI / 360` = -0.7853981633974483
* `Math.PI / 4` = 0.7853981633974483

the rounding by JavaScript causes the addition to equal 0.  Then taking the `tan` results in 0.  __The issue is that `log(0)` is `-Infinity`__

When the code carries on with the `fitBounds` logic the error becomes "failed to invert matrix" due to Y coordinate being `-Infinity`.

The work around, I am using is the following method:
```javascript
function fixMinLat(minLat) {
    var minLatDueToRoudingError = -89.99999999999999
    return (minLat < minLatDueToRoudingError) ? minLatDueToRoudingError : minLat
}
```

It would, however, obviously be good to not have to do this work around and `fitBounds` handle -90 as minimum latitude. 

For reference the complete function in question is:
```javascript
    latY: function(lat, worldSize) {
        var y = 180 / Math.PI * Math.log(Math.tan(Math.PI / 4 + lat * Math.PI / 360));
        return (180 - y) * (worldSize || this.worldSize) / 360;
    },
```

Should possibly be for a solution:
```javascript
    latY: function(lat, worldSize) {
        var y = 180 / Math.PI * Math.log(Math.tan(Math.PI / 4 + fixMinLat(lat) * Math.PI / 360));
        return (180 - y) * (worldSize || this.worldSize) / 360;
    },
```

Or when validating latitude within bounds, use the rounding error value rather than -90

However, I will leave it in your capable hands.  Though please excuse me if may have missed something, but ideally this caught me out and used up a day of my time to identify.  I'm suspecting it might catch others out, so putting in a fix to gracefully handle the JavaScript rounding problem would be appreciated.

**Comment by mourner** [comment]
Have you tried the latest version? It should be fixed there.
