### ISSUE TITLE
Render `fill-extrusion-opacity` on a per-feature basis

### ISSUE THREAD

**Issue by ro-ka** [mapbox/mapbox-gl-js#3675]
## Motivation

Hovering areas in a layer with `fill-extrusion-height` defined on a per-feature basis shall highlight (change opacity) for the hovered layer. Traditional hovering via a separate layer doesn’t work as the hover-layer is rendered above the layer with the extrusion areas. The perspective is wrong then as the hovered area in the hover-layer is overlaying the other areas.

See this GIF for the problem:

![ezgif com-8f0ac9ee19](https://cloud.githubusercontent.com/assets/840022/20521697/c420e040-b0ac-11e6-86ad-a24e40542e01.gif)

## Design Alternatives

Provide rendering of `fill-extrusion-opacity` on a per feature basis via stops as it works for `fill-color` and others.

## Design

Couldn’t find more than one alternative.

### Mock-Up

It would work similar to defining stops on `fill-color` and others:

```js
'fill-extrusion-opacity': {
  property: 'hover',
  type: 'categorical',
  stops: [
    ['hovered-id', 1],
    ['not-hovered', 0.6]
  ]
}
```

### Concepts

As it wouldn’t introduce new concepts but apply existing concepts on a new style property there wouldn’t be much explanation needed.

### Implementation

–

**Comment by jfirebaugh** [comment]
The technical difficulty of per-feature opacity tends toward "infeasible", especially when limited to WebGL features, so this is not likely to happen any time in the forseeable future. See https://github.com/mapbox/mapbox-gl-style-spec/issues/545 for further discussion.

**Comment by ro-ka** [comment]
Okay, but are there other options to get a nice hover? Any best practices or recommendations?

**Comment by lbud** [comment]
@ro-ka your best bet in changing per-feature styles within a layer would be to style highlighted features with one of the fill-extrusion paint properties that supports data-driven styling — please refer to the [support tables in the style spec for this information](https://www.mapbox.com/mapbox-gl-style-spec/#paint_fill-extrusion).
