### ISSUE TITLE
Prefetch tiles for an animated "Map#setCamera" operation

### ISSUE THREAD

**Issue by daniel-j-h** [mapbox/mapbox-gl-js#3676]
Similarly to exposing the cache in order to let developers clear it (ref. https://github.com/mapbox/mapbox-gl-js/issues/2633) it would be great to have a feature for pre-filling the cache and caching tile parsing.

Some use-cases for this:
- I want to trigger a flyTo animation in the near future and I want to pre-cache all tiles needed for the transition. Downloading tiles on the fly is just not smooth enough especially on slow connections.
- I want to visualize a routing request and after showing the overview I want to zoom into the start location. Again, downloading and parsing tiles on the fly can be a bad user experience unless on fast connections / high end devices.

Thinking about this a bit more a first iteration of such a feature could cache tiles based on a bounding box and zoom level for example. A more advanced feature would allow the developer to queue up _any_ action (such as a flyTo) for pre-filling the cache and let the system handle downloading and parsing asynchronously and on low priority in the background when there is spare CPU / bandwidth to do so.

What should be possible already is to invoke my flyTo on a second hidden map. But this still has the overhead of doing the actual off-screen rendering. And needs a second map, so it's a hack at best.

cc @kkaefer

**Comment by lucaswoj** [comment]
see also https://github.com/mapbox/mapbox-gl-js/issues/2470

**Comment by lucaswoj** [comment]
@daniel-j-h What do you think about focusing this ticket on prefetching for animated `setCamera` operations and focusing #2470 on prefetching within a bounding box?

**Comment by daniel-j-h** [comment]
Hrm sorry for not catching the preloading ticket while searching for issues.

But yes how you handle splitting this feature request up is on you :)

**Comment by jfirebaugh** [comment]
I think the primary use case for #2470 is preloading for animations. Let's centralize discussion there.
