### ISSUE TITLE
Map#setMaxZoom caps maxZoom at 20

### ISSUE THREAD

**Issue by jlaxson** [mapbox/mapbox-gl-js#3677]
It is possible to initialize a map using options that specify an arbitrary maxZoom (Transform's default is 22).  However, Map#setMaxZoom will refuse to later set any value above 20.

setMaxZoom with this behavior was added by #2235 and #2243, but I can't find anywhere in the issue history or commit logs where it is explicitly said that this was intentional or necessary.

I have some high resolution rasters whose tiles reach their native resolution at zooms 22-24.

**mapbox-gl-js version**: 0.28.0

### Steps to Trigger Behavior

http://jsbin.com/sozesekomi/edit?html,js,output

1. Initialize map with maxZoom greater than 20.  This works and map can zoom way in.
2. Call setMaxZoom with another value greater than 20

### Expected Behavior

Max zoom is adjusted to given value, and current zoom is clamped as necessary.

### Actual Behavior

Error thrown that maxZoom must be between minZoom and 20.

**Comment by 1ec5** [comment]
Relatedly, mapbox/mapbox-gl-native#7155 tracks increasing the maximum zoom level beyond 21 in the native SDKs.
