### ISSUE TITLE
Storing style files locally doesn't work?

### ISSUE THREAD

**Issue by mg262** [mapbox/mapbox-gl-js#3679]
I'm trying to access a locally stored style file with MapBox GL JS -- I have downloaded `bright-v9.json`, renamed it to `bright-v9-local.json`, and have written the following in an HTML file in the same directory: 

```
var map = new mapboxgl.Map({
    container: 'map',
    style: 'bright-v9-local',
    zoom: 14,
    center: [0.12, 52.2]
});
```

Unfortunately this doesn't work; neither do  `bright-v9-local`,  `./bright-v9-local.json`,  `./bright-v9-local`.  Reading other issues suggests that it must be possible to host local styles, but I can't hit on the right syntax. Any help would be much appreciated.

**Edit:** To put this in context, I'm serving locally hosted PBFs using a setup like https://www.mapbox.com/mapbox-gl-js/example/third-party/ . (By using `"tiles": ["http://localhost:8080/.../{z}/{x}/{y}.pbf"]` .)  Having the style directly in the HTML file works fine for short styles, but I want to use something much longer.  As such it would be useful to be able to store the style file separately from the main HTML file, and refer to it with a relative URL.

**Comment by lbud** [comment]
@mg262 if you open up your Developer Console, what errors does it show?
If you're using a static HTML page with a local style, I suspect it might be something like
> "ajax.js:25
> XMLHttpRequest cannot load file:///Users/laurenbudorick/src/mapbox-gl-js/bright.json. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.

If that's the case, you'll need to run a local server: 
* You can do so by cloning this repo and following the steps up through "Serving the Debug Page" in the [Contributing guide](https://github.com/mapbox/mapbox-gl-js/blob/398d51fb9a2fca2ffe8271f3f63ba531f198b15e/CONTRIBUTING.md#serving-the-debug-page) to install and run this locally, 
* OR, if you're only interested in using a released version of Mapbox GL JS, a _much_ more simple approach would be using something like Python's [SimpleHTTPServer](http://www.linuxjournal.com/content/tech-tip-really-simple-http-server-python) to serve your HTML page locally (at this point the `style` like can be `'bright-v9-local.json'`).

If I'm wrong in my hunch and the cross-origin request was _not_ the problem, or if this does not solve it, feel free to reopen with more details.

**Comment by lucaswoj** [comment]
For a little more context on why we do not support AJAX requests over the `file://` protocol see https://github.com/mapbox/mapbox-gl-js/issues/3272 https://github.com/mapbox/mapbox-gl-js/pull/2466

**Comment by mg262** [comment]
The error is 

NS_ERROR_DOM_BAD_URI: Access to restricted URI denied

Is this a cross-origin request issue?

**Comment by mg262** [comment]
I tried running an HTTP server (with CORS enabled), but it didn't fix the issue. I'm running my server and navigating to localhost:8080/styles/simple.json returns the following file (albeit not zipped):

[simple.zip](https://github.com/mapbox/mapbox-gl-js/files/612042/simple.zip)

I'm creating a map via 

```var map = new mapboxgl.Map({
    container: 'map',
    style: 'http://localhost:8080/styles/simple.json',
    zoom: 14,
    center: [0.12, 52.2]
});
```

but this just results in a white screen.
