### ISSUE TITLE
Expose color interpolation

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#3684]
If I'm applying layer styling like this:

```js
map.addLayer({
  'id': 'foo',
  'type': 'circle',
  'source': 'foo',
  'source-layer': 'data',
  'paint': {
    'circle-radius': 1,
      'circle-color': {
        property: 'bar',
        colorSpace: 'lab',
        stops: [
          [0, '#1D88BD'],
          [80, '#EC6668']
        ]
      }
    }
});
```

I'd love to be able to call a method that passes a domain and returns the color breaks between them based on a `colorSpace` argument. This would be super helpful for generating legends.

This would also be useful for use cases where you load geojson and want to apply additional data processing to group the data (Like applying Jenks or ckmeans clustering) before adding and styling it as a layer. See http://bl.ocks.org/tmcw/934479c0b8075e2f0ec64bd4d7f500ba as an example that requires using a lib (d3) outside of mapboxgl to achieve this.

**Comment by jfirebaugh** [comment]
@tristen I'm not sure what you're proposing here. What does "passes a domain" mean? Can you try to explain again?

**Comment by tristen** [comment]
> @tristen I'm not sure what you're proposing here. What does "passes a domain" mean? Can you try to explain again?

Oh! I was [pulling this from d3](https://github.com/d3/d3-scale/blob/master/README.md#continuous_domain) but I guess that's not really what I was thinking. If I have two colors like `#1D88BD` & `#EC6668`. I want to be able to do something like:

```
interpolate(['#1D88BD', '#EC6668'], 10, { colorSpace: 'lab'});
```

and have it return

```
['#15534C', '#1F6354', '#2C745A', '#3D855E', '#529560', '#69A561', '#83B561', '#A0C460', '#C0D360', '#E2E06']
```

With colors interpolated the same way they would be as `circle-color` is applied. So the second argument is what I was thinking as domain. The number of values to return.

**Comment by jfirebaugh** [comment]
So you want a function that takes as input two colors, an integer _n_, and a color space, and produces an array of _n_ colors interpolated between the inputs at equally spaced intervals?

This seems like something that's best implemented in a third party library or custom code, rather than mapbox-gl-js.

**Comment by tristen** [comment]
I guess? We do this in Mapbox GL JS for coloring source features. I just want the identical output for other things.

**Comment by lucaswoj** [comment]
You can tap into the GL JS function evaluation code by pulling in the [`mapbox-gl-function`](https://github.com/mapbox/mapbox-gl-function) module. This will allow you to use the same color interpolation code (including with different `colorSpace` settings) as GL JS and GL Native. 

Do you think that'll work for your use case @tristen?

**Comment by tristen** [comment]
Ohh that works for me! I guess it would be nice if you could do this from mapbox-gl-js directly but I don't really know what the demand is for something like that. I guess it could always be part of a plugin thingy for legend generation if there's a strong need.
