### ISSUE TITLE
Combine "docs/_posts/plugins" and "docs/_data/plugins.json"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3687]
These two plugin datasets have duplicate data and are at risk of getting out of sync.

https://github.com/mapbox/mapbox-gl-js/blob/mb-pages/docs/_posts/plugins
https://github.com/mapbox/mapbox-gl-js/blob/mb-pages/docs/_data/plugins.json

**Comment by mollymerp** [comment]
agreed -- initially set it up this way bc I couldnt figure out how to access deeply nested data in jekyll 😬

**Comment by lucaswoj** [comment]
Done in #4305 😄
