### ISSUE TITLE
queryRenderedFeatures should return world-wrapped longitudes

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#3688]
#### Scenario

I'm rendering a bunch of point data as circles, and would like to generate a popup when hovering or clicking them. This is done by retrieving the lnglat of the point, and setting the popup there.

#### A snag

When I interact with features more than a world-wrap away (when `Math.abs(longitude)>180`), the popup doesn't show up anymore. Or rather, it gets projected to the un-worldwrapped location (`-180<longitude<180`). This is because `queryRenderedFeatures` returns the same longitude coordinates for the same feature, no matter how many worldwraps away I go.

#### A proposal

Return world-wrapped longitudes with `qRF` queries. This also makes it consistent with current `project`/`unproject` behavior.

**Comment by mcwhittemore** [comment]
@peterqliu - just to make sure I'm understanding this request correctly.

Currently `queryRenderedFeatures` returns `[0,0]` for null island for world left, center and right.

Where the west world extends from -540 to -180 lng, the center world extends from -180 to 180 and the east world extends from 180 to 540.

But you'd like to see `queryRenderedFeatures` return

- `[-360,0]` for the west world
- `[0,0]` for the center world
- `[360,0]` for the east world

**Comment by jfirebaugh** [comment]
We discussed this and other edge cases (bounding box that spans more than one world) when implementing `queryRenderedFeatures`, and decided on the current behavior. Instead of revisiting that, I think we need to fix #2071.
