### ISSUE TITLE
"Map#is*Loaded" methods

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3691]
There is a need for a public API that determines whether or not a source is loaded in throttling calls to `GeoJSONSource#setData`. I often find myself using `map.style.sourceCache[sourceId].loaded()` for this purpose. It would be nice to provide a public API instead: `Map#isSourceLoaded(sourceId: string): boolean`

-----

 - add `Map#isSourceLoaded(sourceId)`
 - add `Map#isStyleLoaded()`
 - add `Map#isTilesLoaded()` / `Map#isTileLoaded(coord)` / ...
 - rename `Map#loaded` -> `Map#isLoaded` / `Map#isEverythingLoaded` / ...

**Comment by sarahkleins** [comment]
Hey @lucaswoj! Going to start working on a few gl-js starter tasks next week. This one seems like a good place to start :)

**Comment by lucaswoj** [comment]
So happy to hear you'll be working on this @sarahkleins. Looking forward to working with you to 🚢 this feature! Let me know if there's anything I can do to help.

**Comment by lucaswoj** [comment]
Expanding the scope of this ticket to include

 - adding `Map#isSourceLoaded(sourceId)`
 - adding `Map#isStyleLoaded()`
 - adding `Map#isTilesLoaded()` / `Map#isTileLoaded(coord)` / ...
 - renaming `Map#loaded` -> `Map#isLoaded` / `Map#isEverythingLoaded` / ...

**Comment by mollymerp** [comment]
This will tie in nicely w the refactoring of our events system #3970 😂
