### ISSUE TITLE
Blob is not defined

### ISSUE THREAD

**Issue by cammanderson** [mapbox/mapbox-gl-js#3693]
Hi Guys. 

Very impressed with everyones hard work and releases. This project is great. 

I'm having some trouble which others may encounter. I can't seem to find any information anywhere, so this might help someone else if they encounter this. 

Using mapbox-gl v0.28, node environment, ES6 with Babel. When I run my mocha tests, I am attempting to create a MAP instance which throws an exception. "Blob is not defined". I have a pretty vanilla package.json.

For this, following the README.md, I am importing using 
```javascript
import { Map } from 'mapbox-gl/dist/mapbox-gl.js'
```

When I attempt to create an instance of the map, I get the exception "ReferenceError: Blob is not defined".

If I import the package just by referencing the 'mapbox-gl' module import only, I get the flow exception "Unexpected token :".

The use case I have is that I am writing some mocha tests for a library I hope to package and make available. 

Hopefully this is enough information to understand the issue.

Thanks!
Cam

**Comment by lucaswoj** [comment]
Hi Cam! Thanks for the thoughtful ticket.

For some unsupported tricks that'll get Mapbox GL running in node, check out the [tests for `mapbox-gl-layer-groups`](https://github.com/mapbox/mapbox-gl-layer-groups/blob/master/test.js).

I'm also interested in discussing what a proper long term solution looks like. This is a common use case that we should be able to support a little better.

**Comment by cammanderson** [comment]
Excellent, that worked a treat! Appreciate the assistance on this. :-)
