### ISSUE TITLE
Which vector tiles format is used by mapbox GL JS?

### ISSUE THREAD

**Issue by mg262** [mapbox/mapbox-gl-js#3696]
I'm trying to write my own MVT server (which tweaks MVTs before serving). When I extract the relevant tile from an MBTiles file, unzip it and serve it directly, everything works fine with Mapbox GL JS.   I can also read the contents of the tile using Java code generated from https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto , and they look sensible.  But when I try to write the tiles _back_ to a byte array and serve that, I get no map displayed. Further the re-encoded tile is smaller than the original: e.g. 

Serving tile 14 8196 5397 -- size 146150, reencodes to 142864

(Using united_kingdom.mbtiles from http://osm2vectortiles.org/downloads/ )

This makes me think that the v. of vector_tile.proto I am using is not the same as that used by Mapbox GL JS.

Examining the original PBF and re-encoded PBF in Protocol Buffer Editor doesn't reveal any differences I can find by browsing. But I _did_ notice that https://github.com/mapbox/mapbox-gl-native/blob/master/proto/vector_tile.proto extends the standard vector tile specification with additional data. (Unfortunately, using this doesn't fix the problem either.)

Can someone point me at the version of vector_tile.proto  that is used by MapBox GL JS?  (Or if anyone can think of any other reason why decoding and reencoding fails, I would be very grateful to know.)

**Comment by jfirebaugh** [comment]
https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto is the official one.

One common error is serving gzip-encoded tiles but forgetting the `Content-Encoding: gzip` header. Beyond that, this is something that you will need to debug for yourself.
