### ISSUE TITLE
Unable to change source of layer that comes from server

### ISSUE THREAD

**Issue by nicoabie** [mapbox/mapbox-gl-js#3698]
**mapbox-gl-js version**: 0.27.0

### Steps to Trigger Behavior

 1. Have a layer defined in the online style
 2. Create a new source for the layer
 3. Assign the source to the layer 
 4. Add back the layer to the map

### Example code
`map.addSource('NewSource', {
   "type": "geojson",
   data: getValidData()
 });
                        
 var l = map.getLayer('layer_defined_in_style');
 l.source = 'NewSource';
 map.addLayer(l);`

### Expected Behavior
The layer shows the new source

### Actual Behavior
It does nothing and it silently fails.
Note: this was working till version 0.26.0. 
In version 0.28.0 it fails as well.

**Comment by jfirebaugh** [comment]
Hi @nicoabie, can you provide a self-contained JSFiddle that demonstrates the issue? I would expect the code you posted to emit a validation error because you are attempting to add a layer which has the same ID as an existing layer.

**Comment by nicoabie** [comment]
Hi @jfirebaugh, thanks for taking the time.

Here is a [jsbin](https://jsbin.com/zugotug/7/edit?js,console,output) demonstrating the behavior for version 0.27.0 where no error are emitted.
Changing it to version 0.26.0 you'll see how the code used to work.
Changing it to version 0.28.0 you'll see too many errors because I believe now addLayer does not like to get a computed layer as a parameter. but I've not seen an "layer already defined error"

Please let me know how can I help you if needed, I've already cloned the repos of mapbox-gl-js and mapbox-gl-style-spec to run some tests.

**Comment by jfirebaugh** [comment]
Thanks for making the JSBin. Based on that, the difference between 0.27.0 and 0.28.0 was a change to how `Map#addLayer` works internally, but it was not a change to the publicly documented API. `Map#addLayer` has never been documented to accept an object returned by `Map#getLayer`. The fact that this worked in prior versions (even when adding a layer with a duplicate ID) was a coincidence.

You'll need to modify your code to use the documented public interface of `Map#addLayer`, passing an object that conforms to the layer types defined in the [Mapbox Style Specification](https://www.mapbox.com/mapbox-gl-style-spec/), including a unique `id` property. If you wish to base that layer off a layer that's present in the style, you can obtain the existing definition via finding the appropriate element in `map.getStyle().layers`. I've filed #3713 for making `Map#getLayer()` itself more useful for this task.

**Comment by nicoabie** [comment]
Thanks for the explanation @jfirebaugh.
I've tried your approach but I can't make it work yet for versions 0.27.0 and 0.28.0
[jsbin](https://jsbin.com/zugotug/11/edit?js,console,output)
