### ISSUE TITLE
Adding layers with interactive:true should not cause a hard fail

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#3710]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

1. Go to https://jsbin.com/bejisuxeci/edit
2. Look in console, see `Error: layers.first: unknown property "interactive...`

### Expected Behavior

I expect to see a water layer. For backwards compatibility reasons, Mapbox Studio exports all stylesheets with `"interactive": true` on every style layer. Initially importing a style with `"interactive": true` works fine, but dynamically adding a layer with `"interactive" :true` fails. This is confusing, since I expect to be able to do things like copy an existing layer, modify it, and then add it to a stylesheet with addLayer.

### Actual Behavior

No water layer renders, map is blank.

**Comment by lbud** [comment]
This will be fixed with https://github.com/mapbox/mapbox-gl-style-spec/pull/580 + https://github.com/mapbox/mapbox-gl-style-spec/pull/559 (as it is, layer validation happens differently for a full style vs for a layer added with runtime styling which is 🙅)

**Comment by samanpwbb** [comment]
@lbud good! it's a little unclear from the referenced issues if the plan to always make `"interactive": true` error, or to never make `"interactive": true` error. Which one is it?

**Comment by lucaswoj** [comment]
@samanpwbb As of https://github.com/mapbox/mapbox-gl-js/pull/3714 it'll never be an error

**Comment by lucaswoj** [comment]
Closed in #3714 😄
