### ISSUE TITLE
How to remove current markers and add new ones accordint to the filtered data ?

### ISSUE THREAD

**Issue by cranberriess89** [mapbox/mapbox-gl-js#3711]
Hi,
I've been trying to filter data according to a property of object. I can filter data but the problem is I can not see the new markers.

//Put custom images on the points where the users located.
mapTwo.on('load', function() {

        filterInput.addEventListener('keyup', function(e) {
            var value = e.target.value.trim().toLowerCase();

            $.ajax({
                type: 'POST',
                contentType: "application/json; charset=utf-8",
                datatype: 'json',
                url: '/Users/GetFilteredUserList',
                data: JSON.stringify({ stateId: value }),
                success: function (result) {
                   
               
                    L.mapbox.featureLayer().clearLayers();
                    markerLayer.clearLayers();
                    mapTwo.removeLayer( markerLayer );
                    //mapTwo.setLayoutProperty(markerLayer, 'visibility', 'none');
                                          
                    geoDataList = loadUsers(result);
                    //var newLayer = L.mapbox.featureLayer().addTo(mapTwo);

                        L.geoJson(geoDataList, {           
                            onEachFeature: function (feature, layer) {
                                var id = feature.properties.id;
                                var marker = layer;            
                                marker.setIcon(L.divIcon(feature.properties.icon));           
                                layer.bindPopup(feature.properties.id);
                                layer.on({
                                    click: whenClicked(id)
                                });
                            }
                        }).addTo(mapTwo);       
                },
                error: function () {
                }
            });
        });
    });
I've tried the clear previous markers info with "clearLayers", "removeLayer" or make the layer unvisible. But none ot them worked ! . Could you please share the way of removing the current markers and add the new ones ?

**Comment by jfirebaugh** [comment]
Hello @cranberriess89!

I regret that I am unable to help you with this question on our GitHub issue tracker because it is neither a feature request nor a bug report.

I encourage you to post this question on [StackOverflow for support help](http://stackoverflow.com/questions/tagged/mapbox-gl-js).
