### ISSUE TITLE
How to make markers resizable when the zoom level changed? 

### ISSUE THREAD

**Issue by cranberriess89** [mapbox/mapbox-gl-js#3712]
Hi,
I want the MAKI icons resizable according to the zoom level. Here is how I put the markers( with custom MAKI icons ) on the map ;

<style> .my-icon { border-radius: 100%; width: 15px; height: 15px; text-align: center; line-height: 15px; color: white; } .icon-dc { background: #ffd11a; } .icon-sf { background: #ff5c33; } </style>
function loadUsers( users ){

    var list = [];
    
    for (var i = 0; i < users.length; i++) {
      
        //Generate geographical data using the longitude & latitude points of users 
        var geoData = {
            type: 'Feature',
            geometry: {
                type: 'Point',
                coordinates: [users[i].Longitude, users[i].Latitude]
            },
            properties: {
                id: users[i].Id,
                icon: {
                    className: 'my-icon icon-dc', // class name to style
                    html: '&#9733;', // add content inside the marker
                    iconSize: null // size of icon, use null to set the size in CSS
                }
            },
            onEachFeature: onEachFeature
        };
        list.push(geoData);
    }
    return list;
}
Is there any way of exploring the markers on the current layer and so update the size of these markers on zoomend event of map ?

**Comment by jfirebaugh** [comment]
Hello @cranberriess89!

I regret that I am unable to help you with this question on our GitHub issue tracker because it is neither a feature request nor a bug report.

I encourage you to post this question on [StackOverflow for support help](http://stackoverflow.com/questions/tagged/mapbox-gl-js).
