### ISSUE TITLE
querySourceFeatures returns invalid feature coordinates on high zoom levels

### ISSUE THREAD

**Issue by data-ux** [mapbox/mapbox-gl-js#3722]
If the map zoom level > 16 the features returned from map.querySourceFeatures have invalid geometry coordinates (negative or otherwise nonsense).

https://jsbin.com/sesafumovi/edit?html,console,output

Can be reproduced on current master branch.

**Comment by mourner** [comment]
This is probably yet another consequence of #2868. I'm in process of refactoring this, after which it'll probably become clear how to fix this.

**Comment by data-ux** [comment]
@mourner Would you have any ideas about workarounds until the issue is fixed?

**Comment by x9xjdzz9** [comment]
It appears to happen at any zoom level higher than the max zoom level of my tileset. If that is the case, a workaround might be to create tiles for the higher zoom levels.

**Comment by bdon** [comment]
@data-ux change mentioned by @drewbo in #2868 (swapping z and actualZ) is a valid workaround for me

**Comment by jasonpepper** [comment]
@data-ux Thanks! That change seems to fix my test case.

**Comment by cyrilchapon** [comment]
Any update / workaround on this ? I don't get the `z` thing, since only x and y are concerned. Am I missing something ?

**Comment by marisbest2** [comment]
Any update on this? I'm having this problem as well with a mapbox style layer

**Comment by jasonpepper** [comment]
I would love to see a fix for this.

**Comment by ralphking** [comment]
@bdon Your tweak seems to work for me as well

@cyrilchapon Open dist (or whichever gl-js file you are looking at) and swap the two values in the ternary operator: https://github.com/mapbox/mapbox-gl-js/blob/de61bbfa21f070e7afbe4fd42e24e8e44e7e25f1/js/source/tile_pyramid.js#L151

Hint if you're looking at a minified source, search for i,n,t.reparseOverscaled?o:i, and swap the o and i around

**Comment by ralphking** [comment]
This is still not fixed on 0.51.0 - it's better, but if you keep zooming in the heat map will disappear. The only fix so far was the one from above, however the code has changed so much since it's no longer an option.
