### ISSUE TITLE
Some paint properties make transparent images opaque

### ISSUE THREAD

**Issue by indus** [mapbox/mapbox-gl-js#3723]
**mapbox-gl-js version**: v0.28.0

### Steps to Trigger Behavior

 1. add ImageSource with semitransparent PNG
 2. add RasterLayer with non-zero ```raster-brightness-min``` or a negative ```raster-contrast``` paint-property (haven´t seen it with other props; but maybe I have overlooked something)

see: https://jsbin.com/tinuxunumi/edit?html,output

### Expected Behavior
transparent parts of the image stay transparent

### Actual Behavior
transparent parts become semi-opaque

**Comment by jfirebaugh** [comment]
@ansis Any idea why WebGL behaves this way? I couldn't reproduce this with headless rendering.

I confirmed that `color.a` has a zero value [here](https://github.com/mapbox/mapbox-gl-js/blob/ab836206d415ca3a74257a3066d11a54ab2838cb/shaders/raster.fragment.glsl#L40-L40) when expected so I'm mystified why those pixels get drawn as non-transparent. Some premultiplied alpha issue?
