### ISSUE TITLE
queryRenderedFeatures Does Not Return Hidden Text Symbols

### ISSUE THREAD

**Issue by x9xjdzz9** [mapbox/mapbox-gl-js#3744]
When I call queryRenderedFeatures on vector symbols which use text, it will not return any features that are hidden due to overlapping. I would expect it to return all symbols even if they are not visible.

Example: https://jsfiddle.net/x9xjdzz9/jpb8krc3/

**Comment by peterqliu** [comment]
@x9xjdzz9 the way we've thought about this so far:

- features hidden due to overlapping are not rendered
- `queryRenderedFeatures()` queries only rendered features
- therefore, `queryRenderedFeatures()` would not query non-rendered features, which includes your overlapping features

**Comment by x9xjdzz9** [comment]
querySourceFeatures does not allow you to specify a geometry. I need a way to query text based features based on a geometry.

**Comment by peterqliu** [comment]
@x9xjdzz9 if you read the documentation linked above, `querySourceFeatures` returns in geojson format. geojson contains the geometry type of each feature, with which you can filter accordingly.

**Comment by x9xjdzz9** [comment]
@peterqliu, I was hoping to use a spatially indexed query. Right now, I'm keeping my points in a separate spatial index with which I perform my queries. But I am assuming MapBox-GL already has the points in a spatial index and uses that for queryRenderedFeatures, and so I feel that my separate index is redundant.

How can I filter the results based on a bounding box? I don't see anything about that in the API. All I see are the existential, comparison, and set membership filters in the API.

**Comment by kronick** [comment]
@x9xjdzz9 You can use [turf.js](http://turfjs.org) to do the bounding box filter: http://turfjs.org/docs/#inside or http://turfjs.org/docs/#within . It should work with the geojson objects you get from`querySourceFeatures`. Note that it's not doing any spatial indexing, so if you have your own spatial index set up that might be worthwhile to keep around if you have a lot of data.

**Comment by kronick** [comment]
@x9xjdzz9 Another option is to add a second layer to your style that has `paint: {text-opacity: 0}` and `layout: {text-allow-overlap: true}`. Using `queryRenderedFeatures()` on this layer should then return all points even though they are all fully transparent on the map. This way, as you rightly assumed, you get the benefit of spatial indexing built in.

You might think of queryRenderedFeatures() more as a UI feature than a data-query feature, but it can be coerced into behaving like the latter with a trick like this.

**Comment by andrewharvey** [comment]
> querySourceFeatures does not allow you to specify a geometry. I need a way to query text based features based on a geometry.

@x9xjdzz9 That's proposed in https://github.com/mapbox/mapbox-gl-js/issues/3666

**Comment by x9xjdzz9** [comment]
I can't figure out what units/projection the feature geometry coordinates are in when I call querySourceFeatures. Using a vector tile source, the feature geometry objects have coordinates like (-154.34, 80.99) for a location near the lat/lon (-77.37, 38.98).

**Comment by jfirebaugh** [comment]
@x9xjdzz9 The result of `querySourceFeatures` is an array of GeoJSON Feature objects, so the coordinates are intended to be GeoJSON lon/lat pairs. If you're seeing something else, please open a ticket, preferably with code that demonstrates the issue. Thanks!

**Comment by peterqliu** [comment]
@x9xjdzz9 note that querySourceFeatures uses the geoJSON specification (specifically, lng-lat order), and returns coordinates in world-wrapped format (i.e. 0 longitude is the same geographic location as 360, 720, etc)

**Comment by x9xjdzz9** [comment]
Added a bug report: #4011
