### ISSUE TITLE
Map loading times are very slow for areas with CJK labels

### ISSUE THREAD

**Issue by itcongaili** [mapbox/mapbox-gl-js#3748]
**mapbox-gl-js version*0.28*:

### Steps to Trigger Behavior

 1.The internet 50kb/s
 2.map need 4min load
 3.

### Expected Behavior
![image](https://cloud.githubusercontent.com/assets/11898652/20918408/d05fe998-bbd1-11e6-8f69-3c3e78c8362a.png)

**Comment by itcongaili** [comment]
I was wondering if I could load the requested resource locally! /(ㄒoㄒ)/~~

**Comment by mourner** [comment]
This is a known issue when loading map areas with CJK glyphs, especially when you use multiple font styles. Mapbox GL loads fonts, depending on which glyphs are used in the current view, as chunks of 256-sized unicode intervals. This mechanism works great for most languages, but makes download times pretty big for CJK.

It's a very challenging issue to solve, but we're working on it.

**Comment by mourner** [comment]
Also see #3466; the issue is being tracked at https://github.com/mapbox/node-fontnik/issues/36.

**Comment by itcongaili** [comment]
@mourner O(∩_∩)Othinks
