### ISSUE TITLE
WebGL portion of map disappears (grey screen) on recent Chrome versions

### ISSUE THREAD

**Issue by mbullington** [mapbox/mapbox-gl-js#3755]
Hello!

We've built mapbox-gl into our application framework, and sometimes mapbox-gl has a quite annoying tendency to disappear when another DOM element is focused or another DOM element overlays it. A grey screen is shown when the map "disappears", but we're still able to see the copyright information element in the bottom right corner.

No errors are thrown when this occurs, and it quickly snaps back if we click on the map again, resize the browser, or open Chrome Developer Tools and highlight an element in the Inspector.

We were able to replicate this issue on Chrome 54 with both our application framework and regular Mapbox Studio. The Mapbox version we currently deploy is v0.28.0. Previously we also had this issue with Mapbox version v0.26.0 as well.

Thank you!

### Steps to Trigger Behavior

 1. Give focus from map to another DOM element, perhaps overlay a DOM element over the WebGL canvas.
 2. Occasionally map will disappear, turn "grey".
 3. Resize window, F12 + Inspector, or click/drag on map for map to reappear 

### Expected Behavior

Map should never disappear.

**Comment by dglogik** [comment]
I was able to reproduce this issue in the mapbox editor as well.
![image](https://cloud.githubusercontent.com/assets/2438450/20981920/4212daf2-bc6b-11e6-819a-a66cb4fd91fd.png)

**Comment by jfirebaugh** [comment]
Thanks for the report. Is this specific to a particular computer or operating system? I don't recall having heard any other reports of this, which we would expect if the problem was widespread.

**Comment by mb12** [comment]
@jfirebaugh I've also seen this intermittently on Windows 8.1 ( IE 11.x). In my case I notice that when the map turns grey, adding a new geojson symbol layer to the map brings it back. This behavior is intermittent and does not reproduce consistently for me.

**Comment by jfirebaugh** [comment]
Could this be the same issue as #2270?

**Comment by mbullington** [comment]
I don't believe so, I've been able to reproduce on recent Chrome versions for macOS and Ubuntu, however I can't find a definite way to make it happen. It's semi-random but every time I've seen it happen it was when focus was taken away from the map to another DOM element.

**Comment by jfirebaugh** [comment]
Is this still reproducible?

**Comment by mbullington** [comment]
We are now working on deploying v0.43.0, I haven't been able to reproduce this issue.

Issue can be closed if no one else can reproduce, thanks!

**Comment by jfirebaugh** [comment]
Thanks @mbullington!
