### ISSUE TITLE
Image layer seems to trigger render loop and consume CPU without interaction

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#3757]
mapbox-gl-js version: 0.28.0

For some reason it seems like simply having an image layer enabled triggers the render loop, even when no interaction with the map is carried out.

### Steps to Trigger Behavior

 1. Go to http://codepen.io/anon/pen/gLzQqw
 2. Perform a CPU profile in Chrome and notice that it's almost completely idle
 3. Click the "Add image" button in the top left corner
 4. Wait for short while and then carry out another CPU profile

You will notice something like:

<img width="527" alt="screen shot 2016-12-07 at 16 15 44" src="https://cloud.githubusercontent.com/assets/1205805/20973312/7c031baa-bc98-11e6-8818-e894ee85a348.png">

### Expected Behavior
That the map consumes almost no CPU resources when not interacted with.

### Actual Behavior
The behavior described above.

**Comment by lucaswoj** [comment]
This is a regression I caused https://github.com/mapbox/mapbox-gl-js/commit/cd7f64fa197722be9d609a533461148339bb7be5 😞 

We should not be [extending the animation loop each time a tile is drawn](http://github.com/mapbox/mapbox-gl-js/blob/138ba626a4983afe5da0dffb8cf97f69c2c266eb/js/render/draw_raster.js#L39-L40). We should be extending it only when a tile is loaded.
