### ISSUE TITLE
Broken links in documentation - CameraOptions, AnimationOptions, Map#easeTo

### ISSUE THREAD

**Issue by kronick** [mapbox/mapbox-gl-js#3762]
Links in https://www.mapbox.com/mapbox-gl-js/api/#Map#easeTo to `CameraOptions` and `AnimationOptions` are broken. The error is just in capitalization, so may be same issue as #3445.

Links from `CameraOptions` to `Map#easeTo`, `Map#flyTo`, `Map#jumpTo` are broken. Missing the # in the middle, so could be a separate issue.

**Comment by tmcw** [comment]
@kronick please search for existing issues before posting new ones: https://github.com/mapbox/mapbox-gl-js/issues/3680

**Comment by kronick** [comment]
@tmcw I did search and found that issue as well as the one I linked to, but without an intimate understanding of how docs are generated, it wasn't clear to me this wasn't a distinct issue.
