### ISSUE TITLE
pitched circle layer drawing imperfections

### ISSUE THREAD

**Issue by jliebrand** [mapbox/mapbox-gl-js#3766]
Use the code below, then zoom in on the blue circle. 
If you zoom far enough, the circle is distorted at the bottem.
Parts of the map come through, and ultimately the bottome of the circle is clipped.

```
var coord = [-0.08813879999999585, 51.54126209999998]
var point = {
  'type': 'Point',
  'coordinates': coord
};

var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/mapbox/streets-v9', //stylesheet location
    center: coord, // starting position
    zoom: 9 // starting zoom
});

map.on('load', function() {
    map.addSource('marker', {
      type: 'geojson',
      data: point
    });

    map.addLayer({
      'id': 'marker-glow',
      'type': 'circle',
      'source': 'marker',
      'paint': {
        'circle-radius': {
              "base": 2,
              "stops": [
                [
                  0,
                  0
                ],
                [
                  20,
                  // 353039.6740660016
                  // 50000
                  353039.6740660016
                ]
              ]
            },
        'circle-color': '#00f',
        'circle-opacity': 0.7
      }
    });
    map.setPitch(60);
});
```

As a side note/question: is it possible to set the alignment of the circle?
eg such that it aligns with the map and pitches as well?

**Comment by jliebrand** [comment]
Forgot to attach the screenshot...
<img width="319" alt="screen shot 2016-12-08 at 8 51 53 am" src="https://cloud.githubusercontent.com/assets/23407884/21017422/2ceb80f6-bd61-11e6-9071-b83dcbf2d37f.png">

**Comment by jfirebaugh** [comment]
Hi @jliebrand, thanks for the report. Such large values (353039) for `circle-radius` are not supported. The effective largest value is around 512, the size of a single vector tile.

**Comment by jliebrand** [comment]
Well that size is only set so large for the largest zoom size... It's effectively working around the fact that you can't set a circle's radius to the map (but rather only to the viewport). Are there any plans to support circles being set in meters (ie aligned with the map) - and also such that it pitches with the map?

The idea here is drawing an accuracy circle around your current position. If I can't pitch it, i'll have to create an svg circle and use it as an icon at different sizes (which feels rather quirky and a hack)

**Comment by andrewharvey** [comment]
@jliebrand 

> Are there any plans to support circles being set in meters (ie aligned with the map)

#2525

> and also such that it pitches with the map?

#2420

> The idea here is drawing an accuracy circle around your current position. If I can't pitch it, i'll have to create an svg circle and use it as an icon at different sizes (which feels rather quirky and a hack)

Or instead of using Circle, [create a geojson polygon as a circle](http://turfjs.org/docs/#circle) in fixed real world units.

In #3781 I've flagged adding an accuracy circle around your current position as a future feature for the Geolocate Control but most likely won't happen without #2525.
