### ISSUE TITLE
error TS2307: Cannot find module 'mapbox-gl/dist/mapbox-gl.js'.

### ISSUE THREAD

**Issue by michaelpwilson** [mapbox/mapbox-gl-js#3767]
I am getting an error when trying to import ```mapboxgl``` into my TypeScript file.

**mapbox-gl-js version**: 0.28.0

### Steps to Trigger Behavior

 1. Import mapboxgl like in the [README](https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-other-module-systems): ```import mapboxgl from 'mapbox-gl/dist/mapbox-gl.js';``` 
 2. Run ```tsc```
 3. An error is outputted although mapbox works fine

### Expected Behavior

No error to be outputted, as mapbox does in fact work even though this error is outputted

### Actual Behavior

Error is outputted although mapbox still works fine:

``` error TS2307: Cannot find module 'mapbox-gl/dist/mapbox-gl.js'.```

**Comment by mourner** [comment]
If Mapbox does work even with the error, are you sure this is not a TypeScript bug?

**Comment by michaelpwilson** [comment]
I was able to get around this issue by using this import instead:

```import * as mapboxgl from 'mapbox-gl';```

**Comment by jfirebaugh** [comment]
Using `mapbox-gl/dist/mapbox-gl.js` is the correct way to use Mapbox GL JS in a non-Browserify module system. If this is causing an error with TypeScript, you'll need to file a bug with that project -- I don't think there's anything we can do on our side.
