### ISSUE TITLE
Disable rotation in the keyboard handler

### ISSUE THREAD

**Issue by lennerd** [mapbox/mapbox-gl-js#3768]
Implement an equivalent for disabling rotation via keyboard like in the `touchZoomRotate` handler.

Example:
``` js
map.touchZoomRotate.disableRotation();
map.keyboard.disableRotation();
```

Why? Because it would be nice to keep available keyboard shortcuts when the only thing we want is to turn of rotation via keyboard.

**Comment by jfirebaugh** [comment]
Good suggestion! Would you be willing to contribute a PR implementing this functionality?

**Comment by lennerd** [comment]
Yes, will take a look into this ASAP.

**Comment by keshineo** [comment]
So, I was wondering if a PR ever got made for this. Tilting results in some rather undesirable effects on our map right now and we would like to ensure that users cannot rotate.

**Comment by lennerd** [comment]
Was not able to work on this yet. 😕

**Comment by jasonferrier** [comment]
How does one "upvote" this issue, because if we are disabling both `dragRotate` && `touchZoomRotate`, wouldn't it make sense to fully disable rotation?

**Comment by ryanhamley** [comment]
Hi @jasonferrier we'd be willing to accept a PR on this issue. Are you interested? I could point you in the right direction if you're unfamiliar with the code base.

**Comment by i-am-ayush** [comment]
Do we have any updates regarding disable rotation from keyboard?
