### ISSUE TITLE
RFC line-cap:round with no extra length

### ISSUE THREAD

**Issue by amelhaoui** [mapbox/mapbox-gl-js#3769]
We display in the map many segments, when we use the line-cap: round, it adds some pixels at the ends which lead to overlapping segments.

**Comment by jfirebaugh** [comment]
Hi @amelhaoui, thanks for the report. I think this is the same issue as was discussed in https://github.com/mapbox/mapbox-gl-style-spec/issues/546. The consensus there was that it was better to maintain consistency with the behavior of `line-cap` in SVG.

**Comment by amelhaoui** [comment]
Hi @jfirebaugh would you please suggest a workaround ?
Thanks a lot

**Comment by jfirebaugh** [comment]
As a workaround, you'll need to adjust the line geometry or use a different `line-cap` value. If you're using `line-dasharray`, you can adjust the values to obtain the spacing you want.

**Comment by amelhaoui** [comment]
Thanks for your reply.
We really like the line-cap: round. I don't know if we could truncate segments length from the ends since length is variable and using line-dasharray won't fit.

**Comment by Jukurrpa** [comment]
@jfirebaugh Would you consider adding a new `line-cap` value which rounds the lines without adding extra length to them?

**Comment by ansis** [comment]
> Would you consider adding a new line-cap value which rounds the lines without adding extra length to them?

I would prefer not to because supporting both would complicate the internal implementation considerably.

**Comment by Jukurrpa** [comment]
Fair enough, thanks.
