### ISSUE TITLE
Fringing artifacts in circle layers

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#3771]
The changes in support of `circle-stroke` introduced some fringing artifacts around the outer edge of the circle. This can be seen in several of the test cases on the `native-circle-stroke` branch:

[circle-stroke-width/default](https://github.com/mapbox/mapbox-gl-test-suite/blob/276f03fd17d7a3a515f1dc0eb69910a69b7d6837/render-tests/circle-stroke-width/default/expected.png):

![image](https://cloud.githubusercontent.com/assets/98601/21031585/189ab5c0-bd59-11e6-8a24-c62eb95c99fa.png)

[circle-stroke-color/zoom-and-property-function](https://github.com/mapbox/mapbox-gl-test-suite/blob/d9919c4ed3abaa3585309070920142931257bd84/render-tests/circle-stroke-color/zoom-and-property-function/expected.png):

![image](https://cloud.githubusercontent.com/assets/98601/21031620/46128c08-bd59-11e6-8478-2f7ca4b0a76d.png)

**Comment by lucaswoj** [comment]
Could you point me to the `native-circle-stroke` branch? I don't see it in `gl-js`, `test-suite`, `gl-native`, or `shaders`.

**Comment by jfirebaugh** [comment]
That was a test-suite branch that I merged to master earlier today as part of https://github.com/mapbox/mapbox-gl-native/pull/7356. The test cases linked above are now on `master` in test-suite. (I simplified the tests so as to avoid hitting https://github.com/mapbox/mapbox-gl-native/issues/7357 on all of them.)
