### ISSUE TITLE
Flickering in Safari 10.0.1 on Mac

### ISSUE THREAD

**Issue by alexcavender** [mapbox/mapbox-gl-js#3774]
**mapbox-gl-js version**:v0.28.0

### Steps to Trigger Behavior

 1. Open up any page that uses MapBox GL, i.e. https://www.mapbox.com/mapbox-gl-js/example/geojson-polygon/
 2. Resize the window to force the Map container element to resize

### Expected Behavior
Map should not be flickering 
### Actual Behavior
Map is flickering very intensely and happens on container element resizing, only in Safari 10.0.1 (I am using el Capitan 10.11.6.)
Map does not flicker in Chrome, Firefox on Mac

**Comment by anandthakker** [comment]
Can reproduce in Safari 10.1:

![flicker](https://user-images.githubusercontent.com/4974151/28463723-e900a052-6def-11e7-9b5a-c55fcb2f9ec4.gif)

**Comment by jfirebaugh** [comment]
Not reproducible in 11.0.

**Comment by shongololo** [comment]
I am experiencing this in Safari 11.0.1

**Comment by mourner** [comment]
@shongololo with the latest GL JS release?

**Comment by shongololo** [comment]
@mourner yes I am using version `0.42.2`

**Comment by lbud** [comment]
Oof…I can also reproduce this on https://www.mapbox.com/mapbox-gl-js/example/simple-map/
Safari: version 11.0.1 (13604.3.5) 
GPU: Intel Iris Graphics 550 1536 MB

**Comment by PrestonL** [comment]
Also experiencing as above on https://www.mapbox.com/mapbox-gl-js/example/simple-map/

Command+F to open the Find menu is also slow and causes flickering in a lot of instances, could be more of a Safari bug?

Safari 11.0.3 (13604.5.6)
macOS 10.13.3 (17D102)
GPU: Radeon Pro 570 4 GB

**Comment by dagjomar** [comment]
Present for me and all of our iOS users. Seems to be a broad Safari issue, not specific to OSX

**Comment by PrestonL** [comment]
It may be worth noting that almost, if not all WebGL example projects I've looked at with Safari also seem to flicker in the same way, so this may be an issue with Safari / WebKit and not with mapbox.

**Comment by iljanovikov** [comment]
Still experiencing the issue 
safari 12.1.2/macos mojave 10.14.6

found [possible solution](https://github.com/pixijs/pixi.js/issues/3395#issuecomment-328495407)

**Comment by hnq90** [comment]
Happened on Safari Version 12.0.3 (14606.4.5)

**Comment by CarlosMaranje** [comment]
Happening on Firefox 107.0 (64-bit) on Linux (ElementaryOS)

**Comment by trusktr** [comment]
This can happen any time that a resize is performed between a `requestAnimationFrame` and the browser paint. Reasons this can happen is if resize loginc in (but not limited to) a `ResizeObserver` callback are resizing the map (or specifically, the `<canvas>`).

More information here, along with suggested new APIs to help make dealing with this easier:

- https://github.com/w3c/csswg-drafts/issues/9717
