### ISSUE TITLE
Create an example / blog post that shows how to use "smart" Map#setStyle with reactive programming

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3776]
The new "smart" `setStyle` #3621 allows a new way of interacting with Mapbox GL styles. Users should be able to express their style as a function of application state, call 👇 every time the application state changes, and get smooth transitions between styles. 

```
map.setStyle(generateStyle(applicationState))
```

It'd be great to show how this works with a blog post and/or demo. We may eventually want to update all our examples to prefer this paradigm.

**Comment by mollymerp** [comment]
I know @dasulit was thinking about a demo showcasing this functionality but cc @mapbox/labs for visibility.

**Comment by dasulit** [comment]
Hey @lucaswoj! I started to play around with `setStyle` a bit, with the goal of making a blog post. I'd be happy to bounce ideas back and forth if you're interested! Is this a duplicate issue of https://github.com/mapbox/mapbox-gl-js/issues/3660?

**Comment by lucaswoj** [comment]
Y, fair to call this a duplicate of #3660. I'll move my thoughts over there.
