### ISSUE TITLE
Make "eventedParentData" a function rather than a static object

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3777]
There are cases where we create circular dependencies by requiring `eventedParentData` be a static object (see https://github.com/mapbox/mapbox-gl-js/pull/3761) We could fix these problems & simplify our architecture by allowing it to be a function instead.

**Comment by jfirebaugh** [comment]
Closing, I'm assuming this was fixed at some point because:

https://github.com/mapbox/mapbox-gl-js/blob/993b7d2dc1b4885b36515f006f023750759231d4/src/util/evented.js#L31
