### ISSUE TITLE
After upgrading to 0.27.0+, previously working layers no longer show up on the map

### ISSUE THREAD

**Issue by Maturion** [mapbox/mapbox-gl-js#3779]
Issue #3706 was closed as I didn't supply a JSFiddle, but the problem still persists. This time, I've finally had time to create an example: https://jsfiddle.net/tguo140q/

Here's my original description of the problem:
> I have been creating maps in minority languages by adding custom layers with GeoJSON sources and hiding/removing some label layers supplied by the style I'm using.
> 
> After upgrading from Mapbox GL JS 0.26.0 to 0.28.0, some layers do no longer show up on my map. These problems also occur when using 0.27.0, but do not happen when going back to 0.26.0.
> Not all layers are concerned, it's basically only "place labels" that are no longer being shown. Below is an example of a layer that stopped working after upgrading. I haven't changed anything on the actual layer code and the source I've been using is the same.

**mapbox-gl-js version**: 0.27.0+

#### JSFiddle:
Here's a minimal JSFiddle demonstrating the problem: https://jsfiddle.net/tguo140q/
For testing purposes, I suggest using language codes such as `ru` or `ro`. The example is using the Mapbox Bright style.

Watch out for the _Tiraspol_ label. It will disappear when changing the language. At that point, my custom layer is added to the map, but it won't show up. The second custom layer works fine. 

If you change the Fiddle's external ressources to Mapbox GL JS 0.26.0, the _Tiraspol_ label is visible after changing the language.

The two layers I added are almost identical to `place_label_city` and `road_label` respectively (both from the Mapbox Bright style). The only difference is the data source and a slightly different filter. 

#### Noteworthy observations
 1. I do not think it's a problem with the source, the style or applied filters. It all works with previous versions of Mapbox GL JS.
 2. Problem doesn't occur with layers used for road labels. GeoJSON features with `"type": "LineString"` geometry seem to be unaffected. 
3. I cannot confirm this 100%, but it looks like the problem occurs with all GeoJSON features whose geometry type is `Point`.
4. I don't think it's related to #3710, as I've removed `"interactive": true`.

**Comment by jfirebaugh** [comment]
The JSFiddle still has a huge amount of script (10s of thousands of lines). Can you please reduce it to the minimum data needed to show the issue?

**Comment by jfirebaugh** [comment]
Yes, it's the GeoJSON I'm referring to. Can you please minimize that?

**Comment by jfirebaugh** [comment]
I went ahead and minimized it for you:

```
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <script type="text/javascript" src="https://api.tiles.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.js"></script>
    <link rel="stylesheet" type="text/css" href="https://api.tiles.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.css">
</head>
<body>
<div id='map' style='width: 600px; height: 400px;'></div>
<script>
    mapboxgl.accessToken = 'pk.eyJ1IjoibWF0dXJpb24iLCJhIjoiMzZjM2Y3ZTM2YmQ0N2VjZTM4Mzc3YjQ0M2FhMTM0NmEifQ.gW1-V772tiaBkozi48bCEA';
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/maturion/civto8qtq003j2jnxavua9tql',
        center: [29.6158, 46.8393],
        zoom: 12
    });
    map.showCollisionBoxes = true;
    map.on('load', function() {
        map.addSource('source', {
            type: 'geojson',
            data: {
                "type": "Feature",
                "properties": {
                    "name:ru": "Тирасполь"
                },
                "geometry": {
                    "type": "Point",
                    "coordinates": [
                        29.6349762,
                        46.8516737
                    ]
                }
            }
        });

        map.removeLayer("place_label_city");
        map.removeLayer("road_label");
        map.addLayer({
            "id": "localizedCityNames",
            "type": "symbol",
            "source": 'source',
            "source-layer": "place_label",
            "layout": {
                "text-font": [
                    "Open Sans Semibold",
                    "Arial Unicode MS Bold"
                ],
                "text-field": "{name:ru}",
                "text-size": 14
            },
            "paint": {
                "text-color": "#333",
                "text-halo-color": "rgba(255,255,255,0.8)",
                "text-halo-width": 1.2
            }
        });
    });
</script>
</body>
</html>
```

I expected to see the "Тирасполь" label, and do with 0.26, but not with 0.28. (It greatly helps us track down issues if you can create examples like this, that demonstrate the issue using the smallest possible amount of code.)

The issue here is `"source-layer": "place_label"`. If you remove this property, the "Тирасполь" label will appear.

GeoJSON sources do not have layers, and therefore `"source-layer"` should not be used for layers which use a GeoJSON source. Prior versions accepted and ignored the property, but the current version is stricter. This was mostly an unintended change, and we may go back to simply ignoring the property. For best compatibility, you probably still want to remove `source-layer` though.

Related issues: https://github.com/mapbox/mapbox-gl-style-spec/issues/547, https://github.com/mapbox/mapbox-gl-style-spec/issues/620.

**Comment by Maturion** [comment]
Thanks! Removing `source-layer` really helped.

**Comment by mollymerp** [comment]
👍 glad your issue got resovled @Maturion. Closing as there are no next actions.
