### ISSUE TITLE
Add `center` parameter to `ScrollZoom` and `TouchZoomRotate` handlers

### ISSUE THREAD

**Issue by mohsen1** [mapbox/mapbox-gl-js#3780]
Our app requires we persist the map center while zooming, `touchZoom: 'center'` and `scrollWheelZoom: center` is working great in Leaflet. It would be nice if GL had it as well.

**Comment by mohsen1** [comment]
What's your timeline for this feature? I'm asking because it's impacting our decision for picking a map library. Thanks!

**Comment by lucaswoj** [comment]
Regrettably, we do not yet have a timeline for adding this feature @mohsen1. 

If this feature is blocking you I'd recommend implementing it yourself and submitting a PR. It shouldn't take more than several lines of code. 

It'd be a shame to let several lines of code (contributed to the open source community!) stand between you and this awesome mapping library.

**Comment by mohsen1** [comment]
I love to do that. I actually checked out the code and it was easy to find where the change needs to be made. 

Unfortunately we have to support iOS 7, does GL renderer fall back to normal renderer in iOS7?

**Comment by lucaswoj** [comment]
We do not have an automatic fallback for clients that don't support GL because it's impossible to get feature parity between a GL-based renderer and a raster-based renderer. All the building blocks are available for you to build such a fallback: 

 - https://www.mapbox.com/mapbox-gl-js/example/check-for-support/
 - https://www.mapbox.com/api-documentation/#static

**Comment by mollymerp** [comment]
@mohsen1 just out of curiosity, can you clarify whether your feature request is to fix the center (only while the map is moving/scrolling) to wherever the map's center is when zooming starts, and then release the fixed center `onScrollEnd`, or if you want to fix the map to an arbitrary center?

**Comment by mohsen1** [comment]
@mollymerp basically we want to persist map center while zooming in/out. But use can change map center by panning the map.

**Comment by jfirebaugh** [comment]
Implemented in #3876.
