### ISSUE TITLE
Including an extraneous "source-layer" property causes GL JS to crash

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3784]
I've seen more than one support request float by regarding an extraneous `source-layer` property on a `geojson` source causing GL JS to crash https://github.com/mapbox/mapbox-gl-js/issues/3779#issuecomment-266326393. Ideally GL JS would print an error message but continue to function in this situation. We may need to add a distinction between "warnings" and "errors" in the style spec validator.

**Comment by stepankuzmin** [comment]
It seems that GL JS v0.29.0 does not crash with an extraneous `source-layer` property on a `geojson` source, but it neither displays the layer — http://jsbin.com/dizukev/7/edit?js,output (uncomment `source-layer` addition). So what is the correct way to deal with this? GL JS should emit an error and display layer regardless `source-layer` property?

**Comment by mollymerp** [comment]
Yes, it is still confusing that no error is emitted but the added layer doesn't appear. We should emit an error with a clear message per #3208, #3879

**Comment by stepankuzmin** [comment]
I made a PR for this https://github.com/mapbox/mapbox-gl-js/pull/3896

**Comment by jfirebaugh** [comment]
Thanks @stepankuzmin!
