### ISSUE TITLE
Option to not wrap the world

### ISSUE THREAD

**Issue by Que3216** [mapbox/mapbox-gl-js#3785]
We have a world map, in a panoramic container, that starts out fully zoomed out, but the wrapping looks pretty silly (can get 3+ copies of the world): http://jsfiddle.net/3wjybdf5/1/. Would it be possible to add a noWrap option? How hard would it be to add a noWrap option?

Solutions which don't work:
   - Using mapBounds (https://github.com/mapbox/mapbox-gl-js/issues/1488). We want to show the full world, and the map container is panoramic, not square.
   - Shrinking the map container, or changing the shape of the container. As you zoom in we still want the map to fill the the bounds of the panoramic container.

**Comment by lucaswoj** [comment]
This wouldn't be too difficult to add @Que3216. I encourage you to submit a PR 😄

**Comment by Que3216** [comment]
I've opened a PR: https://github.com/mapbox/mapbox-gl-js/pull/3885
