### ISSUE TITLE
Error when using line-color with identitiy function

### ISSUE THREAD

**Issue by lennerd** [mapbox/mapbox-gl-js#3789]
I encountered a bug when using `line-color` with the `identity` function and a GeoJSON based source. I'm using Chrome in 54.0.2840.98.

```
VM3875 mapbox-gl.js:62 Uncaught TypeError: Failed to execute 'uniform4fv' on 'WebGLRenderingContext': No function was found that matched the signature provided.
```

https://jsfiddle.net/lennerd/3h67dbcm/

``` js
map.addLayer({
  id: 'test-line',
  type: 'line',
  source: 'test',
  paint: {
    'line-color': {
      type: 'identity',
      property: 'stroke'
    }
  }
});
```

I also found a similar issue: https://github.com/mapbox/mapbox-gl-js/issues/3629
Though stating the given property is not available as a data-driven one (time of writing) yet, the web documentation says different: https://www.mapbox.com/mapbox-gl-style-spec/#paint-line-color

Am I doing something wrong here?

**Comment by jfirebaugh** [comment]
Thanks for the report. This was previously reported in #3639, and fixed in #3665, which will be in the next release.
