### ISSUE TITLE
HTML-GeoJson points?

### ISSUE THREAD

**Issue by weatherc** [mapbox/mapbox-gl-js#3792]
Are there a way to show html-markers with GeoJson in Mapbox GL JS? 

Tryed to use this example: https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/ but did not found any info in the docs about how/if it is possible to build custom html-based markers. 

Also, is it possible to set the margin between the shown points? 
I don't wan't clustering as its meant to show more markers (placenames) on closer zooms. That seems generally to work as i want but i want to increase the margin. The placeames are connected to the data in the GeoJson so i can't use the placenames fin the mapdata (it should show a number + placename but only show placenames for locations with the number).

I have it woking with leaflet-mapbox-gl-js but thats a bit slow so it should want to use native mapbox-gl.js: https://www.nordicweather.net/test/testmap3_2.php

**Comment by jfirebaugh** [comment]
Hi @weatherc! HTML markers are available via the `Marker` class. Check out the following examples and API documentation:

* https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/
* https://www.mapbox.com/mapbox-gl-js/example/set-popup/
* https://www.mapbox.com/mapbox-gl-js/api/#Marker

**Comment by weatherc** [comment]
As i said, do the "normal" marker-class, what you linked to, not work as i want because there are no "collision-check" for overlapping markers. The geojson-markers seems to have that so it not show too many of them (alltought i should want bigger margin between shown markers).

**Comment by mollymerp** [comment]
@weatherc we don't currently implement collision detection for HTML `Marker`s, and you can't set custom HTML for the markers in the example you linked because those are rendered in GL and not part of the HTML DOM. You can override the margins/padding for the HTML `Marker`s in your site's css though.

**Comment by weatherc** [comment]
Hi. Got it to what i want using the marker class by hardcoding the zoomlevels to the data (https://www.nordicweather.net/test/testmap2_1.php) but it got ridicolous slow/clunky now when zooming/panning. The function what removes old markers/add new ones are fast tought, takes only 5-15 ms when ca 1000 markers in the raw data.

Have also noted that function where "add layer below labels" also slows down the map quite a bit. Would be a great function and exactly what i need for showing weather-data below labels etc if it was enough fast.

Fastest/best running combination i have got so far are old Leaflet 0.7 + leaflet-mapbox-gl what works OK but as as said, need old Leaflet....
