### ISSUE TITLE
Merge the "mapbox-gl-style-spec" repo into this repo

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3794]
ref #3656 

# Todo

- move over files
- set up `@mapbox/mapbox-gl-style-spec` npm package (name still under discussion) to be published from this repo
- mark the `mapbox-gl-style-spec` npm package as deprecated
- update all Mapbox projects to use new `@mapbox/mapbox-gl-style-spec` package
- configure `mapbox-gl-style-spec` documentation to be published by `mapbox-gl-js`
- clean up `mapbox-gl-style-spec` S3 resources
- migrate `mapbox-gl-style-spec` issues & PRs
- mark the `mapbox-gl-style-spec` github repo as deprecated
- find a way to minify the style reference without checking in build artifacts

**Comment by jfirebaugh** [comment]
Same comment as https://github.com/mapbox/mapbox-gl-js/issues/3793#issuecomment-266878924 -- I think we should continue versioning and publishing a separate package, and not merge at the public API level.

**Comment by lucaswoj** [comment]
Sounds good 👍. That makes this a non-breaking change for Studio too.
