### ISSUE TITLE
Reading TAP data from stdin (use "-" argument to suppress) when npm run build-min

### ISSUE THREAD

**Issue by benjaminhon** [mapbox/mapbox-gl-js#3800]
When i run npm run build-min, i get the following

```
Reading TAP data from stdin (use "-" argument to suppress)
```

it then gets stuck.

**Comment by mourner** [comment]
What node/npm version are you using? Are you sure you don't have stale `node_modules`? Can you try removing it and doing a clean `npm install`?

**Comment by benjaminhon** [comment]
ah i did npm -g update npm and it works now

**Comment by mourner** [comment]
`npm run build-min` does not use globally installed packages, only locally installed ones. Can you try `rm -rf node_modules`, `npm install` and then `npm run build-min`? This script is working fine for us so this could be a problem with your NPM setup.
