### ISSUE TITLE
Symbols/icons get a faint outline seemingly at random

### ISSUE THREAD

**Issue by dannybloe** [mapbox/mapbox-gl-js#3801]
**mapbox-gl-js version**: 0.28

### Steps to Trigger Behavior

 1. Create a sprite png file containing images with a white outline.
 2. Use this file to put symbols on the map

Either:

 3. Create a source+layer that displays the symbol
 4. Remove the symbol data from the source (disappears from the map)
 5. Re-add the symbol data to the source (re-appears on the map)
 6. See the outline

Or:
 3. Reload the page
 4. See the outline coming and going at random. Sometimes it isn't there, sometimes it is.

Expected:
![symbol-desired](https://cloud.githubusercontent.com/assets/2369994/21179437/655a2630-c1f4-11e6-8a70-3ec01c21ba5a.png)

Erroneous:
![symbol-outlined](https://cloud.githubusercontent.com/assets/2369994/21179438/655ac6d0-c1f4-11e6-99be-9bcae5b017a2.png)

Sprite:
![map-sprites](https://cloud.githubusercontent.com/assets/2369994/21179471/8c52cb16-c1f4-11e6-92d0-8af14231de28.png)

Json:
```
{
  "trailPoint": {
	"width": 32,
	"height": 32,
	"x": 0,
	"y": 0,
	"pixelRatio": 1
  },
  "trailPointSelected": {
	"width": 32,
	"height": 32,
	"x": 0,
	"y": 32,
	"pixelRatio": 1
  },
  "trailPoint2": {
	"width": 32,
	"height": 32,
	"x": 32,
	"y": 0,
	"pixelRatio": 1
  },
  "trailPointSelected2": {
	"width": 32,
	"height": 32,
	"x": 32,
	"y": 32,
	"pixelRatio": 1
  }
}
```

**Comment by jfirebaugh** [comment]
This should be fixed; please let us know if you're still seeing the issue.
