### ISSUE TITLE
Data-Driven Styling Slow Compared to Filters

### ISSUE THREAD

**Issue by x9xjdzz9** [mapbox/mapbox-gl-js#3805]
Using data driven styling to color vector-tile points where the point id is the category on which the points are colored is far slower when compared to using filters to achieve the coloring.

https://jsbin.com/xebisuk/edit?js,output

using MapBox GL v0.28.0

**Comment by mourner** [comment]
Currently stops-based function evaluation time grows linearly with the number of stops. Tacking possible performance improvement over https://github.com/mapbox/mapbox-gl-function/issues/31
