### ISSUE TITLE
features of parent tiles showing up while rotating

### ISSUE THREAD

**Issue by indus** [mapbox/mapbox-gl-js#3810]
**mapbox-gl-js version**: v0.28.0

### Steps to Trigger Behavior

 1. add data with multiple detail/zoom-levels from "vector" source 
 2. show them on map with "fill-extrusion" layer
 3. modify pitch and/or bearing of the map

### Expected Behavior
level of detail should be constant when tiles have loaded

### Actual Behavior
features of parent tiles (lower detail levels) show up for certain angles

![image](https://github.com/indus/stuff/raw/master/mapbox_blocks.gif)

**Comment by indus** [comment]
It seems to me this has been fixed in v0.30.0.

I don't know what caused the bug and also don't know what fixed it (maybe #3399); but I´m unable to reproduce it with latest version.
I'm leaving it up to you to close - just in case you want to investigate further.

**Comment by lbud** [comment]
Thanks @indus! Closing here — please re-open if you see this again.
