### ISSUE TITLE
Transparent parts of raster tiles become opaque when brightened

### ISSUE THREAD

**Issue by lewis500** [mapbox/mapbox-gl-js#3817]
**mapbox-gl-js version**: .28

### Steps to Trigger Behavior

 1. add a raster tile source with transparent parts to the png's
 2. add a raster layer to connect to the source that has "raster-brightness-min" set to brighten up the layer

Example codepen: http://codepen.io/anon/pen/BQvmeq
In this case the transparent parts are due to the underlying map covering only part of the tiles.

### Expected Behavior
The dark parts of the tiles should be brighter, but the transparent parts should remain transparent.

### Actual Behavior
The transparent parts become whitish and opaque.

I think it must be related to [3723](https://github.com/mapbox/mapbox-gl-js/issues/3723)

**Comment by jfirebaugh** [comment]
The rendering mechanism for raster and image sources is the same, so this will indeed have the same root cause as #3723. Let's centralize discussion there.
