### ISSUE TITLE
Add support for -y variable in URL for (MTV) protobuf tiles - GeoServer

### ISSUE THREAD

**Issue by andreschardong** [mapbox/mapbox-gl-js#3827]
I'm using the Vector Tile extension on Geoserever 2.11 to publish MTV protobuff tiles.
Geoserver requires setting the y value in the URL to {-y} (I guess it's because of the orientation of the tile grid). I'm wondering if there is a equivalent syntax on mapbox-gl-js (works fine on OL3). I'm trying with {-y}, but no luck:

`http://localhost:8080/geoserver/gwc/service/tms/1.0.0/opengeo:countries@EPSG%3A4326pbf/{z}/{x}/{-y}.pbf`

the code to add the layer is:

       map.addSource("testPBF", {
                type: "vector",
                tiles: ["http://localhost:8080/geoserver/gwc/service/tms/1.0.0/opengeo:countries@EPSG%3A4326pbf/{z}/{x}/-{y}.pbf"],
                "maxzoom": 15
            });
            map.addLayer({
                "id": "id",
                "type": "fill",
                "source": "testPBF",
                "source-layer": 'countries',
                //"source-layer": "contour",
                "paint": {
                    "fill-color": "#EEE",
                    'fill-opacity': 0.75
                }
            });

**Comment by mourner** [comment]
Currently you have to pass `scheme: 'tms'` as a source option instead of `{-y}`. It appears undocumented though. cc @indus — want to address the docs for your #2565 PR? It would probably go to the `mapbox-gl-style-spec` repo.

**Comment by andreschardong** [comment]
Awesome! It's working fine.
