### ISSUE TITLE
Antialiasing not working? (ugly output)

### ISSUE THREAD

**Issue by rouen-sk** [mapbox/mapbox-gl-js#3828]
Hello,
I tried simple style over commercial map data (not OSM), and I am quite puzzled about antialiasing - for example polygons. I have the same data drawn with Mapnik into PNG for comparison. Look here:

Mapnik PNG:
![image](https://cloud.githubusercontent.com/assets/7676825/21312867/dcbb1e84-c5ee-11e6-8067-cb59627e065c.png)

Mapbox GL JS:
![image](https://cloud.githubusercontent.com/assets/7676825/21312873/e5e6e75e-c5ee-11e6-8565-17bdf54a0a64.png)

I am using v0.28.0, and for example for water polygons this simple layer:

{
    "id": "water",
    "type": "fill",
    "source": "my-vectors",
    "source-layer": "water",
    "paint": {
      "fill-color": "#96c6ea"      
    }    
  }

According documentation, antialiasing should be enabled by default, right? 
I have one warning in console: `Vector tile source "my-vectors" layer "water" does not use vector tile spec v2 and therefore may have some rendering errors.` (I am generating vector tiles with older version of Mapnik Vector Tiles at the moment) - could this be the reason?

**Comment by lucaswoj** [comment]
Thanks for reporting this issue @rouen-sk. 

You are correct in saying that antialiasing is enabled by default in GL JS. 

> I have one warning in console: `Vector tile source "my-vectors" layer "water" does not use vector tile spec v2 and therefore may have some rendering errors.` (I am generating vector tiles with older version of Mapnik Vector Tiles at the moment) - could this be the reason?

It is likely that this is the cause, especially if you're seeing correct antialiasing on other fills (i.e. the land cover areas in your screenshot).  Please try generating the tiles with a new version of Mapnik. If that doesn't solve your issue, please re-open this issue with a live demo that we can use to debug.
