### ISSUE TITLE
try rendering polygons with sdfs

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#383]
Layers with many detailed shapes, like buildings, are slow. We should try rendering the areas to a sdf (on either the cpu or gpu), and then rendering from that. This probably wouldn't be used for all fill layers, only where it helps (if it does).

Second thought is that it could also be useful for blurring (#236) individual layers before compositing them on.

**Comment by mourner** [comment]
Not very slow now. Do we still want to look into this?

**Comment by kkaefer** [comment]
Could still be cool for water to achieve the glow effect that we often use in maps.

**Comment by nickidlugash** [comment]
> Could still be cool for water to achieve the glow effect that we often use in maps.

:+1: Even though it's just one specific use case, blurred water really helps so much with the legibility of a map.

**Comment by ansis** [comment]
we have a separate issue for the glow effect: https://github.com/mapbox/mapbox-gl-js/issues/769
