### ISSUE TITLE
API: Please expose a way to get a separate instance to do projections.

### ISSUE THREAD

**Issue by janerivi** [mapbox/mapbox-gl-js#3837]
**mapbox-gl-js version**: 0.28

### Steps to Trigger Behavior

 1. Need to do projection on a "normalized map" with different tilt and rotation than the active map. (used for calculations for drawing and editing rotatable and resizable rectangles). Does not want to create a separate instance of the entire map.
 2. Currently has to do a hack to tease out an instance of the class that does the projection calculations (using the constructor found on the prototype )

### Expected Behavior
the existence of an exposed public class for that can do map projections with other settings of tilt, rotation zoom independently of the active map

### Actual Behavior
the class we use is not publicly exposed, we feal unsafe in using it fearing that it could be change in the next release without even a notice.

**Comment by lucaswoj** [comment]
Thanks for the feature request @janerivi! This feels like a smart expansion of the feature request in https://github.com/mapbox/mapbox-gl-js/issues/3343. I'll modify that ticket to include these ideas. We will make https://github.com/mapbox/mapbox-gl-js/issues/3343 the central spot for discussion.
