### ISSUE TITLE
0.29 on npm

### ISSUE THREAD

**Issue by karlguillotte** [mapbox/mapbox-gl-js#3839]
Hi,

Thanks for 0.29! Looking forward for the smart `setStyle` method, I have been using `diffStyles` for a while and happy to see that integrated. 

However, I can not find 0.29 on npm.

**Comment by lucaswoj** [comment]
Not sure how that happened. I just published the package manually. Seems to be 👍 now.

**Comment by karlguillotte** [comment]
Awesome! Thank you.
