### ISSUE TITLE
jumpTo() with geocoder

### ISSUE THREAD

**Issue by iskandarblue** [mapbox/mapbox-gl-js#3842]
**mapbox-gl-js version**:  v0.29.0

The default transition built into the Mapbox GL Geocoder is `flyTo()` when an address is input.

Is there a way to change this transition to `jumpTo()` and how would one do that?

**Comment by jfirebaugh** [comment]
There's a `flyTo` option which you can set to `false`: https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md#mapboxgeocoder

**Comment by iskandarblue** [comment]
That didn't work though

```
var geocoder = new MapboxGeocoder({
    accessToken: mapboxgl.accessToken,
    flyTo: false
});
```

This disables all movement.  Nothing happens when an address is input when you turn off flyTo

**Comment by jfirebaugh** [comment]
Indeed. That seems to be https://github.com/mapbox/mapbox-gl-geocoder/issues/78.
