### ISSUE TITLE
Too many (pending) tile requests is blocking other ajax requests

### ISSUE THREAD

**Issue by dannybloe** [mapbox/mapbox-gl-js#3848]
We are working on a Wep-app using mapbox-gl and we noticed that mapbox-gl uses all possible request-slots of the browser for fetching the tiles making it impossible to do any additional (ajax) requests by other parts of the application while they are pending. Is there a way to limit the maximum number of concurrent tile requests by mapbox to make sure there is always some extra 'space' left for other ajax calls? Our users have to be able to do other operations in the app while the map is loading its tiles.

**Comment by kristfal** [comment]
The best solution in this situation is to host your map tiles on a different domain or subdomain than your API endpoints. This will allow you to run requests in parallel and you'll have (at worst) 4 open parallel connections for your API. Another option is running over HTTP2.  [See Browserscope for details](http://www.browserscope.org/?category=network).

While zooming / panning on a device with a small screen, mapbox usually requests 4-8 tiles at the same time. For large HiDPI screens, you could be loading as many as 20 tiles at once. You would need to reduce the max-connections to 2 to retain a guaranteed 4 free parallel connections to your API (the equivalent of running the API and map server on different domains). This would in effect make the map at least three as slow to load tiles, which is probably not that great either.

**Comment by dannybloe** [comment]
Niet zo zeuren hoor. Laat dat maar aan mij over. Kan ik veel beter.
