### ISSUE TITLE
Setting map.showTileBoundaries = true causes TypeError: t is undefined.

### ISSUE THREAD

**Issue by mg262** [mapbox/mapbox-gl-js#3849]
MapBox GL JS v0.28.0 with Firefox 50.0.2: 

I'm drawing a simple map as follows:

```
var map = new mapboxgl.Map({
    container: 'map',
    style: 'http://localhost:8080/styles/simple.json',
    zoom: 14,
    center: [0.12, 52.2]
});
```

This works fine, but if I add

`map.showTileBoundaries = true;`

afterwards, I get an error: 

> TypeError: t is undefined.

on mapbox-gl.js:72:4430 .

**Comment by jfirebaugh** [comment]
I'm not able to reproduce this in a simple example. Can you create a self-contained JSFiddle that demonstrates the issue?

**Comment by mg262** [comment]
Unfortunately I can't reproduce the crash on JSFiddle.  Could you try opening up this html in firefox?

```
<!DOCTYPE html>
<html>
<head>
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.28.0/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>

<div id='map'></div>
<script>

mapboxgl.accessToken = 'pk.eyJ1IjoiZWRlbnJheWdhcmRuZXIiLCJhIjoiRlZRVlhqOCJ9.tDrWaeNRbMCtXAovQLYuzA';
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v8',
    center: [0.12, 52.2],
    zoom: 14
});

map.showTileBoundaries = true;
</script>

</body>
</html>
```

**Comment by jfirebaugh** [comment]
Yes, thank you! It seems to be a regression from bf5f7155a21c9aa0c04efd6658a7b9b133c9005a.

cc @mourner

**Comment by mg262** [comment]
Odd  that it didn't trigger in JSFiddle. (https://jsfiddle.net/z4c74y1v/).

**Comment by mourner** [comment]
Sorry about the regression, will look into it.

**Comment by mg262** [comment]
@mourner I _think_ it was caused on this line: 

`const sourceCache = this.style.sourceCaches[Object.keys(this.style.sourceCaches)[0]];`

Can `this.style.sourceCaches` be empty?
