### ISSUE TITLE
request: setting opacity of a popup

### ISSUE THREAD

**Issue by kkdd** [mapbox/mapbox-gl-js#3850]
A request for the capability of setting ```opacity``` of a popup in order to make it more attractive.

I have found the following suboptimum solution of CSS setting of ```opacity```, which is however ineffective against opacity of the part of a triangle foot of a popup:
 
```
<style>
    .mapboxgl-popup-content {
        position: relative;
        background: #fff;
        opacity: 0.7;
        border-radius: 3px;
        box-shadow: 0 1px 2px rgba(0,0,0,0.10);
        padding: 10px 10px 15px;
        pointer-events: auto;
    }
</style>
```

environment:
* **mapbox-gl-js version**: v0.29.0
* google chrome 55.0.2883.95 (64-bit)
* macosx 10.11.6

**Comment by mourner** [comment]
Thanks for the request! I feel like this is a type of feature that should be left to external CSS customization rather than implemented as a part of core. To style the tip of the popup, just use the browser inspect tool to see what class it has and then style it accordingly.
