### ISSUE TITLE
Regression on dds color interpolation in v0.29.0

### ISSUE THREAD

**Issue by averas** [mapbox/mapbox-gl-js#3851]
**mapbox-gl-js v0.29.0**:

### Steps to Trigger Behavior

 1. Go to http://codepen.io/anon/pen/ZBZrVK
 2. Review the polygon properties, the layer stop colors and the result on the map (which looks correct)
 3. Change version to v0.29.0
 4. Review the result on the map

### Expected Behavior
That the interpolation works as with v0.28.0

### Actual Behavior
Interpolation does not work.

**Comment by mourner** [comment]
Thanks for the report! This is already fixed in master (see #3838), so the fix will be included in the next release.
