### ISSUE TITLE
canvas.style.cursor doesn't change to 'grabbing' during dragPan.

### ISSUE THREAD

**Issue by sentilesdal** [mapbox/mapbox-gl-js#3854]
Weird behavior can be seen here (as of 12-22-2016):
https://www.mapbox.com/mapbox-gl-js/examples/

currently: 

**before mousedown:**
cursor has 'grab' style
**after mousedown/during mousemove:**
cursor has '_grab_' style
**on mouseup**
cursor has 'grabbing' style

should be:

**before mousedown:**
cursor has 'grab' style
**after mousedown/during mousemove:**
cursor has '_grabbing_' style
**on mouseup**
cursor has 'grabbing' style

I tried to override this behavior by setting the canvas.style.cursor during mousedown, mousemove and mouseup but the weird behavior persists.

**Comment by andrewharvey** [comment]
On Chrome 55 I can't replicate this, what platform are you seeing this?

For me it seems normal:

**before mousedown:**
cursor has 'grab' style
**after mousedown/during mousemove:**
cursor has 'grabbing' style
**on mouseup**
cursor has 'grab' style

**Comment by sentilesdal** [comment]
So it turns out it was/is an issue with some of our machines here.  Some show the behavior and some don't, very strange but it I guess it's nothing to do with Mapbox.  Thanks for looking into it though.
