### ISSUE TITLE
Programatically close popup

### ISSUE THREAD

**Issue by diegomura** [mapbox/mapbox-gl-js#3858]
Is there any way of programatically close a popup?
I couldn't find any way of doing this on the documentation.

**Comment by mollymerp** [comment]
Yes, you can use [`Popup#remove`](https://www.mapbox.com/mapbox-gl-js/api/#Popup#remove)

**Comment by diegomura** [comment]
But that would actually remove completely the popup of the map isn't it?
If I want to open it again I should call `addTo(map)` again?

**Comment by mollymerp** [comment]
@diegomura you're correct, we don't have a method for hiding popups with css (ex `visibility:none`) . the pattern of using `Popup#addTo(map)` and `Popup#remove()` is what I would suggest!

**Comment by diegomura** [comment]
Great @mollymerp. Thanks for your help!

**Comment by whatAboutJohn** [comment]
What if you don't have access to the popup created, say it was created through an evented click using `map.fire('click')`, is there an alternative way of closing the popup?

**Comment by chriszrc** [comment]
remove works to totally remove the popup, just like add works to add the popups, but to trigger a popup, you have to setup something to "open" the popup, and the equivalent call would be close. You can "close" the popup without removing the functionality entirely by clicking the popup, seems like we should be able to do this programmatically

**Comment by ryanhamley** [comment]
@chriszrc you can also just call the public method `popup.remove()` directly. we can't really think of a compelling case to essentially duplicate the `remove` functionality with a `close` method so this is the way that we recommend "closing" popups. if anyone has a good use case for a separate `close` method (say `remove` is somehow not performant enough), let us know.

**Comment by Pictor13** [comment]
> What if you don't have access to the popup created, say it was created through an evented click using `map.fire('click')`, is there an alternative way of closing the popup?

If you are fine with closing ALL the popups you can do
```
for (var popup of document.getElementsByClassName("mapboxgl-popup")) {
    popup.remove();
}
```
