### ISSUE TITLE
queryRenderedFeatures  do not retrive background

### ISSUE THREAD

**Issue by zuo1188** [mapbox/mapbox-gl-js#3860]
**mapbox-gl-js version**:
0.29.0
### Steps to Trigger Behavior
when I query features from the map, all features are printed except background ,does background feature do not all to query?
here is my code:
```
 <script src='https://api.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.js'></script>
 <link href='https://api.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.css' rel='stylesheet' />
-------------------------------------------------------------------------------------------
var map = new mapboxgl.Map({
  	    container: 'map', // container id
  	    style: style,
           interactive:true,
  	    center: [17.3364,67.6488], // starting position
  	    zoom: 12 // starting zoom
  	});
map.on('click', function (e) {
        var paddedBox = [
            [e.point.x - 3, e.point.y - 3],
            [e.point.x + 3, e.point.y + 3]
        ];
       var features = map.queryRenderedFeatures(paddedBox);
       console.log('Got features:',features);
}
```

@lucaswoj @jfirebaugh

**Comment by averas** [comment]
For <code>queryRenderedFeatures</code> the documentation states:

> Returns an array of GeoJSON Feature objects representing visible features that satisfy the query parameters

My understanding is that _features_ in this context refers to the geospatial features that are provided by the sources referenced in the map layers. The background layer is a special case without a source and therefore has no features. Returning a feature for the background would mean one would have to define what geographic footprint it actually represents.. The viewport? Map bounds? The entire world?

Is there any particular use case you have in mind?

**Comment by zuo1188** [comment]
you are right @averas  thank you!   my use case is wierd
