### ISSUE TITLE
Importing image into map overlay throws error. 

### ISSUE THREAD

**Issue by kvyb** [mapbox/mapbox-gl-js#3862]
I am trying to run the code as it appears on https://www.mapbox.com/mapbox-gl-js/example/image-on-a-map/ but with a different image source. 

when I inspect the .html in Chrome it gives the following error:

`mapbox-gl.js:87 Uncaught DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at blob:null/ef2e658b-69f0-4eb3-9234-a07a5edc1d29 may not be loaded.
    at e._prepareImage (https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.js:87:2682)
    at e.prepare (https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.js:87:2212)
    at o.prepare (https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.js:99:1982)
    at Painter.renderPass (https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.js:72:4748)
    at Painter.render (https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.js:72:4274)
    at e._render (https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.js:207:11604)`

Seems to not be a CORS issue. Is this a bug?

This is the code I am using:
```
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title></title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.29.0/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>

<div id='map'></div>
<script>
mapboxgl.accessToken = 'pk.eyJ1Ijoia3Z5YiIsImEiOiJjaXUwMHEwcmgwMDAxMnlvM3NzMm0xbGozIn0.JL_eeNZL_lDoJxijNqFPoA';
var mapStyle = {
    "version": 8,
    "name": "Dark",
    "sources": {
        "mapbox": {
            "type": "vector",
            "url": "mapbox://mapbox.mapbox-streets-v6"
        },
        "overlay": {
            "type": "image",
            "url": "http://i.imgur.com/KO7H4M9.png",
            "coordinates": [
                [-77.096355, 38.836498],
                [-76.933479, 38.968744],
                [-77.096355, 38.968744],
                [-76.933479, 38.836498],
            ]
        }
    },
    "sprite": "mapbox://sprites/mapbox/dark-v9",
    "glyphs": "mapbox://fonts/mapbox/{fontstack}/{range}.pbf",
    "layers": [
        {
            "id": "background",
            "type": "background",
            "paint": {"background-color": "#111"}
        },
        {
            "id": "water",
            "source": "mapbox",
            "source-layer": "water",
            "type": "fill",
            "paint": {"fill-color": "#2c2c2c"}
        },
        {
            "id": "boundaries",
            "source": "mapbox",
            "source-layer": "admin",
            "type": "line",
            "paint": {"line-color": "#797979", "line-dasharray": [2, 2, 6, 2]},
            "filter": ["all", ["==", "maritime", 0]]
        },
        {
            "id": "overlay",
            "source": "overlay",
            "type": "raster",
            "paint": {"raster-opacity": 0.85}
        },
        {
            "id": "cities",
            "source": "mapbox",
            "source-layer": "place_label",
            "type": "symbol",
            "layout": {
                "text-field": "{name_en}",
                "text-font": ["DIN Offc Pro Bold", "Arial Unicode MS Bold"],
                "text-size": {"stops": [[4, 9], [6, 12]]}
            },
            "paint": {
                "text-color": "#969696",
                "text-halo-width": 2,
                "text-halo-color": "rgba(0, 0, 0, 0.85)"
            }
        },
        {
            "id": "states",
            "source": "mapbox",
            "source-layer": "state_label",
            "type": "symbol",
            "layout": {
                "text-transform": "uppercase",
                "text-field": "{name_en}",
                "text-font": ["DIN Offc Pro Bold", "Arial Unicode MS Bold"],
                "text-letter-spacing": 0.15,
                "text-max-width": 7,
                "text-size": {"stops": [[4, 10], [6, 14]]}
            },
            "filter": [">=", "area", 80000],
            "paint": {
                "text-color": "#969696",
                "text-halo-width": 2,
                "text-halo-color": "rgba(0, 0, 0, 0.85)"
            }
        }
    ]
};

var map = new mapboxgl.Map({
    container: 'map',
    maxZoom: 5.99,
    minZoom: 4,
    zoom: 5,
    center: [-75.789, 41.874],
    style: mapStyle,
    hash: false
});

</script>

</body>
</html>
```

P.S. accessing the image provided in your Mapbox example for this type of plot gives a CORS error.

**Comment by averas** [comment]
Yes, this is related to CORS. You will need to host images on the same domain, or configure the web server hosting the images to reply with appropriate CORS headers.

I agree that the example provided by Mapbox perhaps should reference a CORS friendly image since many copy the examples and run them in other environments, such as jsfiddle or codepen. On the other hand, providing such an example will raise later confusion when referencing other images. The bottom line is that you have to understand CORS.

**Comment by mollymerp** [comment]
Hi @kvyb,
Thank you for reporting this issue. 

If you're loading the map locally, you'll need to use a server (we do not support loading using `file://` urls)  to fix the CORS errors you're seeing. You can do this by running `python -m SimpleHTTPServer` in Terminal in the folder you're working on.

You also need to use an `https` url to load the image, and update the coordinates of your source to match the order specified in the [style spec](https://www.mapbox.com/mapbox-gl-style-spec/#sources-image) (clockwise from top-left)

Here is a working jsfiddle of your example https://jsfiddle.net/f04ex2xc/
