### ISSUE TITLE
Feature ID (type: object) not preserved on queryRenderedFeature method

### ISSUE THREAD

**Issue by Jonibigoud** [mapbox/mapbox-gl-js#3863]
**mapbox-gl-js version**: 0.29.0

### Expected Behavior

Feature "id" property is preserved on geojson whose "id" is an object. (mongodb ObjectId)

### Actual Behavior

When i use the queryRenderedFeature's mapbogl method on a geojson collection hosted on a mongodb database, the output shows the entire document structure but the "_id" property. The thing is that each "Feature" got his auto generated _id "objectId" from the mongodb engine.

**Comment by stackTom** [comment]
How does queryRenderedFeatures return your id? As a string? If so, you can use JSON.parse(idObject) as a workaround. In my use case, it returns arrays as a string, and I use this method to get back the objects.

**Comment by jfirebaugh** [comment]
Thanks for the report @Jonibigoud. We have an existing issue on this -- #2716 -- so I'm going to close this as a duplicate.
