### ISSUE TITLE
MBtiles vector tile render loop when zooming in

### ISSUE THREAD

**Issue by stackTom** [mapbox/mapbox-gl-js#3866]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. load mbtiles vector tile source
 2. check map loaded
 3.

### Expected Behavior
map.loaded() eventually returns true, render event should stop if no changes to map are made
### Actual Behavior
map.loaded() always returns false, render event occurs infinitely

I load a vector tile source from an mbtiles server. Initially, the render event is only emitted once, and map.loaded() eventually returns true. If I zoom in sufficiently such that a large number of points from the mbtiles is visible, the render method begins to be called an infinite number of times, and map.loaded() never returns true.

I found this: https://github.com/mapbox/mapbox-gl-js/issues/3398
Could it be the same issue, or different as in my case, it is a vector tile source?

**Comment by jfirebaugh** [comment]
It's difficult to say what the issue is offhand. Could you provide a self-contained code example that demonstrates the problem?

**Comment by stackTom** [comment]
My bad. I was trying to reproduce the issue in a jsfiddle, and it turns out it is due to a base raster layer that I am using in my project. Changing the base layer to a vector mapbox style eliminates the issue, so this is in fact a duplicate of https://github.com/mapbox/mapbox-gl-js/issues/3398
