### ISSUE TITLE
Customizing popups

### ISSUE THREAD

**Issue by iskandarblue** [mapbox/mapbox-gl-js#3867]
I would like to know if it is possible to customize/stylize popups from the  `var popup = new mapboxgl.Popup()` function.

I have tried to reset the popup anchor so it is on the left (as opposed to the bottom) of the popup box in CSS with:
```
.mapboxgl-popup-anchor-left {
    margin-left: 10px;
}
```
but to no avail.   Is it also possible to change the background color/size of the popup box, x and y overflow, and could an example be provided? 

<!--
Hello! Thanks for contributing.

**Comment by jfirebaugh** [comment]
Yes, you can use CSS to customize the appearance, attaching it to the `.mapboxgl-popup` class or other related classes. To change the anchor position, see [the documentation](https://www.mapbox.com/mapbox-gl-js/api/#Popup) for the `anchor` option.

**Comment by iskandarblue** [comment]
The main question is how to make x and y overflow scrollable in the popups.  I have tried 
```
 .mapboxgl-popup {
overflow-y: scroll;
overflow-x: scroll;
max-width: 200px;
max-height: 400px;
font: 12px/20px 'Open Sans', sans-serif;
border-radius: 5px;

}
```

but this doesn't work.  Any suggestions for a workaround?

**Comment by sbamberger127** [comment]
Sorry, I know this was posted a while ago but I used 

.mapboxgl-popup-content {
overflow-y: scroll;
overflow-x: scroll;
}

**Comment by cbeddow** [comment]
When I edit the background and border CSS of the mapboxglPopup class, it appears to place a bounding box around the entire popup including the anchor, and also doesn't change the popup color from white, but instead changes the bounding box background color. How do I edit this without making it all look awkward?

**Comment by sbamberger127** [comment]
@cbeddow I did not have this problem until 2 days ago.  I have attempted a number of solutions but am still coming up short. I'm on stackoverflow trying to puzzle this one out. I'll let you know if I get anything. Right now, I only get the bounding box if I drop the "-content" portion. Once I add it the popup behaves as if unstyled. Sorry I can't be more help currently.

**Comment by ChadESmith42** [comment]
I style mine by adding a class to the popup element using the following code:
`new mapboxgl.Popup({ className: 'popups' })
                .setLngLat(coordinates)
                .setHTML(description)
                .addTo(map);`

You can add multiple classes by using comma separated strings. Then use those classes in your CSS file to style to your delight. Hope this helps!

**Comment by rilexus** [comment]
You can set the width of the popup with the setWidth function on the Popup instance.
If you set it to 'auto' it will adjust to the content by itself.

In my case it was set to 240px by default through the style attribute.
