### ISSUE TITLE
map.queryRenderedFeatures returns feature geometries cut with tile boundaries

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox-gl-js#3871]
I'm highlighting features on hover by adding features, returned by `map.queryRenderedFeatures` to a highlight layer with a corresponding style. However features, that cross tile boundaries, are highlighted partially. Seems like only a part of their geometry is returned by `map.queryRenderedFeatures`. Here is how it [looks like](https://www.dropbox.com/s/sr7mjg91sf214af/Screen%20Shot%202016-12-29%20at%2014.41.00.png?dl=0).
![screenshot](https://photos-3.dropbox.com/t/2/AACqUCDAx5sdx8duqCuDbYaFtfrQxVDdNIfc14VUbJ_qkg/12/7488735/png/32x32/3/1483030800/0/2/Screen%20Shot%202016-12-29%20at%2014.41.00.png/EN7cxwUY9vUDIAcoBw/b5u6Ah4Z_mCj5uw86MIQrqZ2RZVhWof3FqdcHY3miLY?size_mode=3&dl=0&size=2048x1536)

**Comment by peterqliu** [comment]
This is the expected behavior-- see [documentation](https://www.mapbox.com/mapbox-gl-js/api/#Map#queryRenderedFeatures).

**Comment by nextstopsun** [comment]
@peterqliu Ok, sorry. Is there a workaround to highlight a whole feature?

**Comment by peterqliu** [comment]
@nextstopsun the most straightforward way involves adding a unique identifier as an attribute for each feature in your dataset (something like `id:8927492`). Then at runtime, 

- Retrieve a feature with `queryRenderedFeatures`, and make note of its identifier.
- Call `querySourceFeatures`, and filter the results by this identifier.
- This subset will comprise all loaded pieces of your feature.

**Comment by chriswhong** [comment]
I was successful getting this to work, but it's so involved to do a `queryRenderedFeatures()` and then a `querySourceFeatures()` immediately after. 

It would be great if there was a convenience method for this, or perhaps an option on `queryRenderedFeatures()` that could query the source features behind the scenes, and maybe even stitch the chunks together into a single geometry.

**Comment by chriswhong** [comment]
Scratch that, I thought I had it working, but now I'm seeing that the "chunks" returned by `querySourceFeatures()` don't seem to align. In the attached screenshot, the polygon I am trying to highlight falls on the boundary of 4 tiles.  4 chunks are returned, but they appear to be overlapping each other.

<img width="1057" alt="fullscreen_10_31_17__11_49_am" src="https://user-images.githubusercontent.com/1833820/32233790-a0dfb834-be31-11e7-8772-9c39c9b4dece.png">

**Comment by chriswhong** [comment]
Looks like others have `turf/unioned` the chunks together:  https://github.com/mapbox/mapbox-gl-js/issues/5040

**Comment by nextstopsun** [comment]
That's awfully slow and sometimes returns errors on `union`

**Comment by chriswhong** [comment]
Yeah, giving up on this for now.  `@turf/union` was not cooperating, and I didn't want to continue down the rabbithole.  C'est la vie with vector tiles I suppose.

**Comment by nextstopsun** [comment]
Well I guess if features already got sticked together in intitial rendering it shouldn't be that hard to stick them again on selection.
