### ISSUE TITLE
queryRenderedFeatures doesn't return raster layers

### ISSUE THREAD

**Issue by diegomura** [mapbox/mapbox-gl-js#3873]
**mapbox-gl-js version**: 0.29.0

### Demo 
http://jsbin.com/xifeke/edit?html,js,output

### Steps to Trigger Behavior

 1. Create an image source with some url and coordinates
 2. Add a raster layer to print the image on the map
 3. call `queryRenderedFeatures` when mousedown at the map and filter the image layer

### Expected Behavior
An array with the raster layer

### Actual Behavior
Empty array

**Comment by tmcw** [comment]
Hi Diego,

Thanks for the issue: we're already tracking this request in #1404, so let's keep the discussion there.

Thanks,

- Tom
