### ISSUE TITLE
Allow Cross-site Source Data Request with Credentials

### ISSUE THREAD

**Issue by jasonpepper** [mapbox/mapbox-gl-js#3874]
## Motivation

What use cases are we trying to accommodate? 

Source data may contain private data that requires authentication. Furthermore, the data may be hosted at a different http origin than the map application. Currently, cross-site MapBox ajax requests will not pass authentication tokens.

## Design Alternatives

Add a boolean option to the various types of sources called "withCredentials", where if it is true the XMLHttpRequest will have the withCredentials option set to true. For example:

"mapbox-streets": {
  "type": "vector",
  "url": "mapbox://mapbox.mapbox-streets-v6",
  "withCredentials": true
}

### Concepts

How will we teach this design?

In the style spec, add a description of the new option.

### Implementation

How you would implement the design in Javascript?

    var xhr = new window.XMLHttpRequest();
    xhr.open('GET', url, true);
    xhr.responseType = 'arraybuffer';
    xhr.withCredentials = withCredentials;

**Comment by lucaswoj** [comment]
For the same reasons as https://github.com/mapbox/mapbox-gl-js/pull/2918, I'm not sure this feature fits the TileJSON ethos. This may need to depend on #3326.

**Comment by huaruiwu** [comment]
@lucaswoj those two issues look closed. Any plans on allowing credentials?

**Comment by mollymerp** [comment]
this feature is not on our current roadmap @huaruiwu.

**Comment by huaruiwu** [comment]
Without this feature, it isn't possible to have secure map data. Signing URLs have too much of an overhead. I think @x9xjdzz9 's proposed design makes sense.

**Comment by rayterrill** [comment]
We're looking to swing json and image hosting over to Cloudfront using Signed Cookies, and after struggling to track down what was happening, it appears we're running into this exact same issue. :(

**Comment by asheemmamoowala** [comment]
Closed in #5021
