### ISSUE TITLE
Do not bind handlers in a for..of loop

### ISSUE THREAD

**Issue by mohsen1** [mapbox/mapbox-gl-js#3875]
[these lines](https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/bind_handlers.js#L23-L28) made it very hard for me to figure out where `ScrollZoomHandler` is initiated. Calling constructor function like that breaks the call stack. 

I think this is a case that it's better to repeat function calls instead of abstracting out too much complexity.

**Comment by jfirebaugh** [comment]
Thanks for the suggestion @mohsen1. I'd actually prefer to stick with the existing code than repeat those four lines seven times. I'm not sure what you mean by "breaks the call stack". Here's what the call stack looks like for me when I set a breakpoint in one of the handler constructors:

![image](https://cloud.githubusercontent.com/assets/98601/21736411/5c85b0b8-d425-11e6-85fa-5c476dc8fb35.png)
