### ISSUE TITLE
Line-widths computed incorrectly with data properties

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#3877]
Using the recently implemented (#3033) `line-width` with a numeric property doesn't seem to work for me.

http://bl.ocks.org/stevage/da23922b03c5fdcba909c68755da9bb3

I have a `ppl` property which ranges from 1 to 16 mostly. Yet the calculated `line-width` always acts as if the data exceeds any range I give it (1..30 in the Gist). You can see that the `line-color` is being computed correctly. (In the Gist you can also see the properties in the console).

**mapbox-gl-js version**: 0.29.0

### Steps to Trigger Behavior

See above. Here's the specific code:

```
paint: {
                'line-color': {
                    property: 'ppl',
                    type: 'exponential',
                    stops: [
                        [1, 'red'],
                        [16, 'blue']
                    ],
                    colorSpace: 'hcl'
                    
                },
                'line-width':{
                    property: 'ppl',
                    type: 'exponential',
                    stops: [
                        [1, 1],
                        [5, 2],
                        [20, 3],
                        [30, 10]
                    ],
                    base: 1
                }
            },
```

### Expected Behavior

Red lines should be skinny (1px). Blue lines should be medium width (3px).

### Actual Behavior

All lines are fat (10px).

**Comment by jfirebaugh** [comment]
We had to back out data-driven `line-width` due to internal implementation issues (#3682). Now tracked in https://github.com/mapbox/mapbox-gl-style-spec/issues/633.

Note that you can check SDK support for data-driven properties in the support matrixes here: https://www.mapbox.com/mapbox-gl-style-spec/#paint-line-width. If there's no "data-driven styling" row, than the property doesn't yet support it.

**Comment by stevage** [comment]
Ok, thanks. Maybe it would be clearer if the table had a "data-driven styling" row with "not supported" in every column?

**Comment by jfirebaugh** [comment]
Agreed -- https://github.com/mapbox/mapbox-gl-style-spec/issues/529.
