### ISSUE TITLE
Fix pixelated icons

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#3878]
Companion ticket for https://github.com/mapbox/mapbox-gl-native/pull/7302, intended to fix pixelated icons in some situations and some GPUs. Original ticket is https://github.com/mapbox/mapbox-gl-native/issues/6863

**Comment by jfirebaugh** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-js/pull/4737.
