### ISSUE TITLE
Incorrect z-order for multiple fill-extrusion layers

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#3880]
This must be a known issue, so I'm sort of asking for a workaround.

I have two fill-extrusion layers, representing buildings from two different sources. The buildings from one layer are apparently drawn after the other layer.

![3dbuildings](https://cloud.githubusercontent.com/assets/678344/21598817/452c0b30-d1b7-11e6-80b6-f0d1a9f015d7.png)

The only fix I can see is to merge all the layers before uploading, then using lots of data-driven styles to style them separately.

**mapbox-gl-js version**: 0.29.0

**Comment by andrewharvey** [comment]
Hi Steve!

> This must be a known issue

#3387

>The only fix I can see is to merge all the layers before uploading, then using lots of data-driven styles to style them separately.

I used the DDS approach for building age at https://www.alantgeo.com.au/demos/melbournecity-building-age/ however since I have a separate layer for the hover, it suffers the same issue.

**Comment by stevage** [comment]
Hi Andrew :) Looks like merging will the be only way to go for the forseeable future.

**Comment by jfirebaugh** [comment]
The current tracking issue for this is https://github.com/mapbox/mapbox-gl-style-spec/issues/545. Let's centralize discussion there.
