### ISSUE TITLE
Allow a non truncated linesofar (overall line distance) for line shader (feature request)

### ISSUE THREAD

**Issue by kaligrafy** [mapbox/mapbox-gl-js#3883]
Would it be possible to access the overall length of a line in the line shader so we can create fading or gradient lines (like getting a value between 0.0 and 1.0 that represents the linesofar in percentage of total)? Also, it would allow a better dasharray rendering when using polygons as input to create lines (right now, the dash line is too short or to long at the location where the stroke start and end).

**Comment by kaligrafy** [comment]
Well, I just saw in the line_bucket that you limit the size of linesofar to 15 bits. Could it be possible to add a parameter that would allow more bits for the storing of the line distance so it is not truncated to zero when reaching max distance (like add a float uniform)? I know this would affect performance, but otherwise it would not be possible to use gradients or fades on line, isn't it?

**Comment by jfirebaugh** [comment]
@kaligrafy I'd rather track this as a request for a specific feature, rather than presupposing specific implementation details like shader parameters. Does https://github.com/mapbox/mapbox-gl-style-spec/issues/349 describe what you're trying to accomplish?

**Comment by kaligrafy** [comment]
Yes, as long as the linesofar is provided as a float representing the location on the line between 0.0 (start of the line) and 1.0 (end of the line)

**Comment by jfirebaugh** [comment]
Ok, let's centralize discussion at https://github.com/mapbox/mapbox-gl-style-spec/issues/349.
