### ISSUE TITLE
map#getLayerZoomRange

### ISSUE THREAD

**Issue by Naimikan** [mapbox/mapbox-gl-js#3886]
Hi!

I want to get the minzoom and maxzoom properties from layer. Only exists setLayerZoomRange.

Is there any way to get the minimum and maximum zoom from a layer?

Thanks!

**Comment by lucaswoj** [comment]
Already done in https://github.com/mapbox/mapbox-gl-js/pull/3592

**Comment by lucaswoj** [comment]
My mistake! That's for the map's zoom not the layer's. I suggest using `Map#getLayer(id).minzoom` (this won't break with #3713)

**Comment by mollymerp** [comment]
Hi @Naimikan -- Thanks for submitting this feature request. We don't have a getter method for this right now, but you can use `Map#getLayer(id).minzoom` and `Map#getLayer(id).maxzoom` to see those attributes of a given layer. We would be glad to review a PR implementing the method you describe above.

**Comment by Naimikan** [comment]
Thanks @lucaswoj and @mollymerp!
