### ISSUE TITLE
Layers flash on map when one is removed and reapplied in 0.29.0

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#3895]
In the latest version of mapbox-gl-js, all layers that share a tile source will flash if any of them are removed, then reapplied with the same id.

This is problematic in my application, where there is a large vector tile source for census blocks with many layers consuming it simultaneously. We need to be able to add and remove the layers if the user changes what they want to see, without flashing all of the layers the wish to keep.

**mapbox-gl-js version**:
0.29.0

### Steps to Trigger Behavior

jsbin example: https://jsbin.com/muyayuzeva/edit?js,output

### Expected Behavior
The `maine_layer` style layer should be removed and reapplied under the hood, but cause no flash of layers.

Also, the `new_york_layer` style layer should be unaffected by the removing/adding of the `maine_layer` style layer.

See same jsbin example w/ mapbox-gl@0.28.0 for expected behavior - https://jsbin.com/fabotihala/edit?html,js,output

### Actual Behavior
Both the `new_york_layer` and `maine_layer` flash on across the map.

**Comment by AndyMoreland** [comment]
Geojson sources exhibit the same behavior for me in 0.30.0.

**Comment by jfirebaugh** [comment]
Thank you for the detailed bug report and test case! It made bisecting this easy. Bisect landed on fc49a2cf5bb0bfc57150cad4aa84d1745f5615ba, which sounds very plausible.

cc @anandthakker

**Comment by karlguillotte** [comment]
I have the same problem starting with 0.29.0 as well. I notice that sometimes, some layers will not show at all. I can do some test once you have a fix. 

Thanks for your great mapping library!

**Comment by anandthakker** [comment]
Thanks for the clear reproduction @DannyDelott and the bisect @jfirebaugh!  

Yeah, fc49a2c is a very likely culprit.  It was an attempt to solve https://github.com/mapbox/mapbox-gl-js/issues/3633 -- wherein removing a layer and immediately re-adding it as a different type violated assumptions about the buffer in the renderer.

Potential fix is to relax the conditions under which we _clear_ the underlying source tiles (rather than just reloading them).   Right now, we do this anytime a layer of a given name is removed and re-added.  I think we can instead do it when a layer is removed and re-added _with a different type_.

**Comment by jfirebaugh** [comment]
> I think we can instead do it when a layer is removed and re-added with a different type.

That may be a good short term fix. Long term I think we should make the clear operation more granular, so it can remove data at the level of individual style layers rather than full tiles. That would prevent flickering of other layers even when a layer is removed and re-added with a different type.

**Comment by anandthakker** [comment]
> Long term I think we should make the clear operation more granular, so it can remove data at the level of individual style layers rather than full tiles.

👍 good point, agreed.  Not sure where https://github.com/mapbox/mapbox-gl-js/issues/2875 will land on the roadmap, but that might be a natural place for this, if there's no pressing need before
