### ISSUE TITLE
Popup does not pan with map

### ISSUE THREAD

**Issue by whoacowboy** [mapbox/mapbox-gl-js#3902]
**mapbox-gl-js v0.30.0**:

### Steps to Trigger Behavior

 1. Go to https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/
 2. Zoom out so you can see the same marker repeated
 3. Mouseover the new marker

### Expected Behavior
You would see the popup on the marker you are rolling over

### Actual Behavior
You see the popup over the original marker
![s1](https://cloud.githubusercontent.com/assets/8116953/21738301/7d864964-d437-11e6-9bfc-d52988c36b79.png)

If you pan more than one world you don't see the popup at all

![s2](https://cloud.githubusercontent.com/assets/8116953/21738296/7a7ddd54-d437-11e6-955b-ab9dc917101f.png)

**Comment by mourner** [comment]
Thanks for the report! This should be solved by #2071, so I'll close this issue so that discussion can continue in one place.
