### ISSUE TITLE
Add Mapbox wordmark control and enable it by default

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#3906]
Mapbox [TOS](https://www.mapbox.com/help/mapbox-logo/) require that the Mapbox logo be displayed on all Mapbox maps. Some paid plans allow users to remove the word mark requirement. 

We should add this as a configurable control and enable it by default.

**Comment by mollymerp** [comment]
This will help avoid things like https://github.com/mapbox/communications/issues/1283

**Comment by jfirebaugh** [comment]
Previously: #1825

**Comment by mollymerp** [comment]
ahh thanks @jfirebaugh I searched "wordmark" instead of "watermark" for previous issues 😬 
closing and moving discussion back to #1825
