### ISSUE TITLE
Document that "queryRenderedFeatures" includes a "layer" property on all features

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3907]

**Comment by jfirebaugh** [comment]
Did you mean `queryRenderedFeatures`? `queryRenderedFeatures` does include a `layer` property, and it is documented already. `querySourceFeatures` does not include a `layer` property -- it doesn't make sense for that API.

**Comment by lucaswoj** [comment]
Yes, I did mean `queryRenderedFeatures`. Thank you.

**Comment by jfirebaugh** [comment]
The documentation for this aspect of `queryRenderedFeatures` currently reads:

> Each feature includes a top-level `layer` property whose value is an object representing the style layer to which the feature belongs. Layout and paint properties in this object contain values which are fully evaluated for the given zoom level and feature.

Do you see specific ways this wording can be improved?

**Comment by lucaswoj** [comment]
The current wording looks good.
