### ISSUE TITLE
Add integration tests for transitions 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3912]
Migrated from https://github.com/mapbox/mapbox-gl-test-suite/issues/168

> Per https://github.com/mapbox/mapbox-gl-style-spec/issues/171, let's add tests for transition properties. Sticking point is somehow taking a screenshot after a certain elapsed time: @lucaswoj pointed me to a [wait operation](https://github.com/mapbox/mapbox-gl-test-suite/blob/a0b0e3be927dff9a01b0869a4d0b41c830370388/render-tests/runtime-styling/filter-default-to-false/style.json#L7-L19) that waits til rendering is complete, but it [doesn't support a duration argument yet](https://github.com/mapbox/mapbox-gl-js/blob/95b0ca42bf8376561db7e96c616d76696d8f65f7/test/suite_implementation.js#L83-L102).

> - [ ] extend `wait` to include a duration parameter in `gl-js`
> - [ ] add tests with durations to test transitions

Migrated from https://github.com/mapbox/mapbox-gl-test-suite/issues/116

> We should to figure out how to add tests for property transitions, in order to prevent bugs like:
> - https://github.com/mapbox/mapbox-gl-js/issues/2762
> - https://github.com/mapbox/mapbox-gl-js/issues/2769
>
> A prerequisite for this is that the test harness has control over the clock used for rendering transitions, so it can deterministically render, say, 50% of the way through a transition. Then we could add that percentage as a parameter somewhere in the test case metadata.
> 
> gl-js internals which use Date.now() directly that need to be converted to using a passed in parameter:
> 
> https://github.com/mapbox/mapbox-gl-js/blob/062f52d836e8991f694c6742ab24ecfdc643151b/js/style/style_declaration.js#L53-L53
> https://github.com/mapbox/mapbox-gl-js/blob/8eaeebbcaeea012fe7876c06fb558a0a2ea99475/js/style/style_transition.js#L54-L54
> https://github.com/mapbox/mapbox-gl-js/blob/8eaeebbcaeea012fe7876c06fb558a0a2ea99475/js/style/style_layer.js#L311-L311
> https://github.com/mapbox/mapbox-gl-js/blob/1df146627092b58c8db64d45530c74cd12a3fa02/js/render/frame_history.js#L17-L17
> https://github.com/mapbox/mapbox-gl-js/blob/7840d9c2265c1d9be52a329d9a9c38784b75b3ca/js/style/style.js#L250-L257

_Migrator's note: sinon has some built-in utilities for mocking out the system clock http://sinonjs.org/docs/#clock_

**Comment by anandthakker** [comment]
Another issue to add test for once we've made it possible in the harness: https://github.com/mapbox/mapbox-gl-js/issues/2467
