### ISSUE TITLE
Add integration regression test for extrusions causing other fills to render wrong color

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3914]
Migrated from https://github.com/mapbox/mapbox-gl-test-suite/issues/159

> (Issue fixed in mapbox/mapbox-gl-js#3548 — because of the way we are now drawing backgrounds, calling clearColor in extrusions was causing other fill layers to render the wrong color.)

**Comment by jfirebaugh** [comment]
Low value at this late date.
