### ISSUE TITLE
Regression in Firefox: Map canvas ... is larger than half of gl.MAX_RENDERBUFFER_SIZE (2048)

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#3915]
**mapbox-gl-js version**: 0.30.0

### Steps to Trigger Behavior

 1. Open https://city-of-melbourne.github.io/cafes-map/index30.html in Firefox, on a high DPI display, with the browser window covering most of the screen
 2. The map doesn't load, and the message `Map canvas (2248x1272) is larger than half of gl.MAX_RENDERBUFFER_SIZE (2048)` is in the console.
 3. However, loading the map with a small window, then expanding the window to the full screen works fine.

In Chrome, it works fine.

With Mapbox-GL-JS version 0.28.0, it works fine: https://city-of-melbourne.github.io/cafes-map/index.html

**Comment by jfirebaugh** [comment]
This message was added in #3841 in order to fix #2893.

**Comment by 1ec5** [comment]
This issue affects Mapbox Studio share pages in Firefox on Retina displays. #2893 indicates that #2673 and #2863 were the motivations behind this change. I never noticed #2673 before; not sure about #2863.

**Comment by 1ec5** [comment]
I’m unable to get #2673 to reproduce in v0.28.0, whereas my same configuration makes it very easy to hit this issue.

I opened #3986 to revert the exception for now, pending further investigation.

**Comment by andrewharvey** [comment]
As noted in https://github.com/mapbox/mapbox-gl-js/issues/2673#issuecomment-272991355 I can confirm I'm no longer seeing #2673 in v0.28.0.

**Comment by 1ec5** [comment]
The change that broke Firefox support was reverted in #3986. I reopened #2893 to track reintroducing the change.
