### ISSUE TITLE
Use lovell/sharp instead of png-js for faster integration tests

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3916]
Migrated from https://github.com/mapbox/mapbox-gl-test-suite/issues/143

> Moving this here from mapbox/mapbox-gl-js#3180
> 
> By my (unsystematic) observations in a different project, https://github.com/lovell/sharp seems to be perhaps 10-20% faster than png-js at writing a Buffer => PNG image. If it installs smoothly on CircleCI, it may be worth using it in suite_implementation.js to get faster render tests.
> 
> @mikemorris pointed out that we should (a) confirm that the OS X and Linux installs are straightforward, and (b) maybe get lovell/sharp#186 (pre-gyp) addressed.
> 
> I can confirm (a): npm install "just works" and takes about 10s on my macbook, and also works fine in a linux CircleCI container.
>
> ------
>
> We [switched to pngjs](https://github.com/mapbox/mapbox-gl-js/issues/584) to avoid a dependency on pkg-config and libpng.
>
> Sharp takes the approach of vendoring its dependency (well, downloading it at install time), and is otherwise self-contained, so that's good.
>
> I do want to wait until there are prebuilt binaries for all platforms. Non-prebuilt native modules inevitably become a support issue, usually on Windows (https://github.com/mapbox/mapbox-gl-js/issues/674, https://github.com/mapbox/mapbox-gl-js/issues/743, https://github.com/mapbox/mapbox-gl-js/issues/1061).

**Comment by jfirebaugh** [comment]
Closing here; doesn't look like prebuilt binaries for sharp are coming, so let's stick with the existing solution.
