### ISSUE TITLE
Decrease tolerance on "extent/1024-*" integration render tests

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3926]
Migrated from https://github.com/mapbox/mapbox-gl-test-suite/issues/75

> - extent/1024-fill
> - extent/1024-line
> - extent/1024-symbol
> 
> These tests all have unacceptably high tolerances due to rendering differences between running test-suite locally and on CI. We need to either find a way to test this functionality that doesn't require such high tolerances or fix the underlying problem (probably floating point precision related). 
> 
> ![download 2](https://cloud.githubusercontent.com/assets/281306/12569097/a3eaddf4-c380-11e5-9c4a-a7ddc526a206.png)
> ![download 1](https://cloud.githubusercontent.com/assets/281306/12569098/a3eb23ae-c380-11e5-9e22-cdf57e078d55.png)
> ![download](https://cloud.githubusercontent.com/assets/281306/12569099/a3ec62dc-c380-11e5-8276-85e34c72473e.png)
> ----
> Note that with pixelmatch4, it detects the difference more precisely so the diff is even bigger:
> 
> ![image](https://cloud.githubusercontent.com/assets/25395/12579151/70f3d780-c42e-11e5-9f1e-5f32efd9ffe3.png)
> ![image](https://cloud.githubusercontent.com/assets/25395/12579153/7506d9d0-c42e-11e5-9032-aa46b1f63ada.png)
> ![image](https://cloud.githubusercontent.com/assets/25395/12579159/77ece914-c42e-11e5-9891-f2109f088a7e.png)

**Comment by mourner** [comment]
No interest in addressing this at the moment.
