### ISSUE TITLE
Add integration tests for edge case map positions

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3931]
Migrated from https://github.com/mapbox/mapbox-gl-test-suite/issues/59

> As per https://github.com/mapbox/mapbox-gl-native/pull/3026, we should have render tests for the given latitude coordinates:
>
> - `(-90, -180)`
> - `(-90, 180)`
> - `(90, -180)`
> - `(90, 190)`

**Comment by jfirebaugh** [comment]
We have several tests that straddle the antimeridian now. I don't think testing +-90 latitude is possible since the camera would constrain the viewport.
