### ISSUE TITLE
Don't specify fixed zoom, bearing and pitch for geolocateControl

### ISSUE THREAD

**Issue by carrickpaul** [mapbox/mapbox-gl-js#3936]
## Motivation

The geolocateControl currently sets the zoom, bearing and pitch to default fixed values on success.
This works for a limited use cases (imagine a map of the world and you want to see what country you're in and it zooms to street level).

You can set the zoom level on the geolocate event, but I'd argue that should be the exception not the norm. 

Currently retaining the same zoom after a geolocate is difficult (impossible?) as you have to get the zoom level before the geolocate event is fired, and since it uses a normal zoom function there is no way to differentiate it from other zoom events.

## Design Alternatives

1. Remove the default settings from the success function so the map retains zoom, bearing and pitch by default. 
The user get the same functionality as the current hard coded values using 
```javascript
geoLocate.on('geolocate', function(e) {
  map.setZoom(17)
  map.setBearing(0)
  map.setPitch(0)
})
``` 

2. Pass in options to set these properties on the control (messy?)

### Implementation

for 
```javascript
class GeolocateControl extends Evented {
```

change this
```javascript
_onSuccess(position) {
  this._map.jumpTo({
    center: [position.coords.longitude, position.coords.latitude],
    zoom: 17,
    bearing: 0,
    pitch: 0
   })
}
```
 to this
```javascript
_onSuccess(position) {
  this._map.jumpTo({
    center: [position.coords.longitude, position.coords.latitude]
   })
}
```

**mapbox-gl-js version**:
v0.30.0

**Comment by andrewharvey** [comment]
This is fixed by https://github.com/mapbox/mapbox-gl-js/pull/3737. Just waiting for review for it to be merged.

**Comment by andrewharvey** [comment]
> I couldn't find an existing issue for fitBounds respecting bearing. That said, the geolocation control shouldn't use fitBounds rather it should fit to the center + radius so that at 45deg bearings the map fits the real accuracy circle.

This will ultimately be fixed by https://github.com/mapbox/mapbox-gl-js/issues/2112
