### ISSUE TITLE
feature request: adding {"rotation-alignment": "map"} option to mapboxgl.Marker()

### ISSUE THREAD

**Issue by kkdd** [mapbox/mapbox-gl-js#3937]
Hello.
For drawing arrowhead markers, I believe that mapboxgl.Marker() should have {"rotation-alignment": "map"} option. See the following examples:

https://gist.github.com/kkdd/928c67088c2debae4204bef55c170106

![apboxgl marker](https://cloud.githubusercontent.com/assets/5372642/21810140/de964868-d78d-11e6-9694-985992e4d9c9.jpg)

**Comment by emperor1412** [comment]
@mourner 
This feature make sense.

**Comment by mourner** [comment]
Maybe worth implementing in the core. However this would be easy enough to do on the application side — subscribing to the `move` event and rotating the marker element with a CSS transform.

**Comment by emperor1412** [comment]
But if you don't have "icon-rotation-alignment": "map" then when rotate map's camera, the marker always face to camera like billboard, and rotate the marker then won't work correctly, no ?

**Comment by kirillegorov-dev** [comment]
We still need the ability to point the direction of marker.

**Comment by seedgabo** [comment]
any update of this?
