### ISSUE TITLE
Automatically populate the roadmap's "Upcoming" column from "top issues"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3942]
Rather than manage the roadmap's ["Upcoming" column](https://www.mapbox.com/mapbox-gl-js/roadmap/) manually, we could populate it using the data from the [GL JS "top issues" page](https://mapbox.github.io/top-issues/#!mapbox/mapbox-gl-js). 

This will

 - eliminate a little work from our weekly cadence
 - display that there are no smoke & mirrors in our prioritization (other than the priority labels!)
 - ensure the roadmap never goes out of date
 - make it easier for the GL team to make informed decisions about task priority

**Comment by mollymerp** [comment]
this would be a fun side quest 💆
