### ISSUE TITLE
Categorical is not the default

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#3948]
Working on category-based visualisation. The documentation about categorical functions says:

>functions return the output value of the stop equal to the function input. This is the default for string domain functions.

It doesn't seem to be the default, in my case. Adding `type: 'categorical'` made this property work:

```
{"property":"SUSTAINABI","type":"categorical","stops":[["H","#a6cee3"],["","#1f78b4"],["M","#b2df8a"],["L","#33a02c"]]}
```

Sorry, no repro case.

**Comment by jfirebaugh** [comment]
Previously: #3717.

I think we should remove this from the documentation and require `type: 'categorical'`. Contextual default values add unnecessary complexity.

**Comment by stevage** [comment]
Thanks. I think I agree with you, but it leaves open the question what GL-JS should do if given a text field but no type. Fail?

**Comment by jfirebaugh** [comment]
In that case, it should fail validation [here](https://github.com/mapbox/mapbox-gl-style-spec/blob/25d721b734858b3c4d62ea89f9bf906e3bb8305a/lib/validate/validate_function.js#L164), because it will be treated as an exponential function, which do not allow string keys.

**Comment by jfirebaugh** [comment]
The (non-functional) support for implicitly categorical functions was removed, and the error message in this case will be: "number expected, string found. If you intended to use a categorical function, specify `"type": "categorical"`".

**Comment by stevage** [comment]
Nice one. I always love help messages that actually direct you towards your goal.
