### ISSUE TITLE
Map not showing on Android Chrome

### ISSUE THREAD

**Issue by lhrmota** [mapbox/mapbox-gl-js#3952]
I'm developing a site that has been having display problems when accessed from Android Chrome. It runs fine in other mobile and desktop browsers (Firefox and Chrome).

I've had two kinds of issues:
- the map displays without background: I see labels, but no streets or buildings,
- the map fails to load.

**mapbox-gl-js version**: https://api.tiles.mapbox.com/mapbox-gl-js/v0.31.0/mapbox-gl.js

### Steps to Trigger Behavior

 1. Open http://surfmaps.eu/trombone/ . It works fine elsewhere.

### Actual Behavior

On the console I can see:
evented.js:91 Error: Failed to initialize WebGL
    at e._setupPainter (map.js:1033)
    at new e (map.js:162)
    at index.js:1
Evented.fire @ evented.js:91
e._setupPainter @ map.js:1033
e @ map.js:162
(anonymous) @ index.js:1
map.js:346 Uncaught TypeError: Cannot read property 'resize' of undefined
    at e.resize (map.js:346)
    at new e (map.js:191)
    at index.js:1

**Comment by mourner** [comment]
Thanks for the report! Does this happen on a specific phone model, or any Android Chrome? What devices did you test this on?

**Comment by lhrmota** [comment]
Hi there.

I only tested it in two phones: just now with an older Wiko Goa with Android 4.4.2 (worked ok) and with my personal phone, a TP-LINK neffos with 5.1 (which shows the described problem).

Best, Luís

**Comment by mourner** [comment]
What does http://webglreport.com/ say using the phone that's not working?

**Comment by lhrmota** [comment]
Hello.

It says WebGL1 is supported, but WebGL2 is not...

The same happens with the other phone.

I've noticed something lately: as the map loads, it flashes, for some 
miliseconds, and shows the expected map. Then it goes blank, as 
described previously.

Best regards, Luís

**Comment by mourner** [comment]
@lhrmota do you see the same behavior on official Mapbox examples such as this one? https://www.mapbox.com/mapbox-gl-js/examples/

**Comment by lhrmota** [comment]
Hello.

Yes, I do, but it is nor consistent. I did only see the labels in 
"Display a map" the first time I viewed it. After a refresh, it 
displayed fine. After a second and third refresh, only labels...

Best regards.

**Comment by mourner** [comment]
When you see only labels, are there any errors in the console?

**Comment by lhrmota** [comment]
In the examples page, I saw this:
GET https://www.mapbox.com/core/api/session?_=1484156583125 403 (Forbidden)
send @ base.js:3
ajax @ base.js:3
App.refreshUser @ base.js:770
(anonymous) @ base.js:1050
c @ base.js:2
fireWith @ base.js:2
ready @ base.js:2
a @ base.js:1

In my example page (http://surfmaps.eu/trombone/), no errors whatsoever.

Bye, Luís

**Comment by mollymerp** [comment]
possible dupe / related #3437

**Comment by mourner** [comment]
Yes, the symptops are the same. Let's combine it with that ticket to keep the discussion centralized. -> #3437

**Comment by quillcraft** [comment]
I have the same problem on android devices. on the first moment I see map background, and after that showing only text layer with labels.

Android ver. / Chrome ver.: https://www.dropbox.com/s/wtlfskbfu1guqeh/IMAGE%202017-06-21%2012%3A37%3A51.jpg?dl=0
