### ISSUE TITLE
Multiple pop-ups in map view

### ISSUE THREAD

**Issue by iskandari** [mapbox/mapbox-gl-js#3955]
**mapbox-gl-js v0.30.00**:

I have been using the [filter features within map view](https://www.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/) example  on my data which works great.   In the example,  a popup is set for airports filtered in the list on hover with : 

```
popup.setLngLat(feature.geometry.coordinates)
                    .setText(feature.properties.name + ' (' + feature.properties.abbrev + ')')
                    .addTo(map); 
```

My dataset is a little different as it has multiple points for each filtered category.  As a result, only one of the points in that category gets a popup.  Here is my [example](http://iskandarblue.github.io/maps/EMA.html)   

The expected behavior is for popups to attach to all points associated with a listing.  I thought this would happen automatically with `features.forEach(function(feature)` but that is not the case.  Could a  a solution be suggested?

**Comment by jfirebaugh** [comment]
Your example appear to be offline, but I'm going to hazard a guess that the issue is that it uses only one `mbgl.Popup` instance. It's possible to show multiple popups, however you'll need to create a separate `mbgl.Popup` instance for each one.
