### ISSUE TITLE
MapDataEvent#isSourceLoaded always returns false

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#3958]
Could this be because the `data` event (which triggers the `sourcedata` event) is fired immediately _before_ the `source.load` event changes [`SourceCache._sourceLoaded` to true](https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/source_cache.js#L30) ?

I thought that was the case, but a quick gut check to switch the function calls didn't change the result. But still it might need to be addressed after we figure out 👇 .

I think the root cause is that [`isSourceLoaded`](https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style.js#L378) is set right when `addSource` is called via [`setEventedParent`](https://github.com/mapbox/mapbox-gl-js/blob/25950e634b97db8e8c4e6c465b14e386a534a193/js/util/evented.js#L120) so `sourceCache.loaded()` is invoked only once, not every time the event fires like I believe was the intended behavior ??

**Comment by lucaswoj** [comment]
> I think the root cause is that [`isSourceLoaded`](https://github.com/mapbox/mapbox-gl-js/blob/master/js/style/style.js#L378) is set right when `addSource` is called via [`setEventedParent`](https://github.com/mapbox/mapbox-gl-js/blob/25950e634b97db8e8c4e6c465b14e386a534a193/js/util/evented.js#L120) so `sourceCache.loaded()` is invoked only once, not every time the event fires like I believe was the intended behavior ?? 

I agree with this diagnosis. Nice 🕵️‍♀️ work.

**Comment by risharde** [comment]
I am having this issue with tilesets where data event never reports the layer as isSourceLoaded = true; Any advice on how I can achieve detecting when a tileset layer is fully loaded? I've spent days trying to find a solution and none work.

**Comment by caesarsol** [comment]
@risharde I have the same problem, did you find any solution?
