### ISSUE TITLE
make AttributionControl with compact option accessible

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#3959]
**mapbox-gl-js version**: 0.31.0

As far as I can tell, there is no way to activate a compacted attribution control using only the keyboard. The compacted (i) should act more like a button that can get focus by tabbing and expanding using enter.

**Comment by mourner** [comment]
Agreed, thanks for the report! Would you like to work on a PR for this?

**Comment by andrewharvey** [comment]
> Would you like to work on a PR for this?

Sorry there are other issues of much higher priority at the moment.
