### ISSUE TITLE
Aw! Snap message

### ISSUE THREAD

**Issue by mkjsobkowiak** [mapbox/mapbox-gl-js#3960]
**mapbox-gl-js version**: 0.29.0

### Steps to Trigger Behavior

 1. Run map with few points on the map
 2. Wait few hours (usualy about 2h)
 3. Aw! Snap message with white screen (in Chrome browser) (in console a lot of messages before error occurs: WARNING: Too many active WebGL contexts. Oldest context will be lost.)

### Expected Behavior
Map should be display all the time.

### Actual Behavior
Map crash after few hours.
![img_1605](https://cloud.githubusercontent.com/assets/9016207/21885812/9e556590-d8b9-11e6-801f-3fc7d386d2b6.JPG)

**Comment by mourner** [comment]
Thanks for the report! As the error from your description says, it is likely to do with opening too many tabs/windows with WebGL-related functionality in them (e.g. many tabs with Mapbox GL maps). Browsers limit the amount of WebGL contexts you can have at the same time, and there's nothing we can do about it on the GL JS side unfortunately. Closing this, but let us know if you have any suggestions about circumventing this browser behavior.
