### ISSUE TITLE
Add the ability to control the clock in integration tests

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3966]
ref #3912

**Comment by ChrisLoer** [comment]
On top of allowing us to add tests for transitions and other animations, this is important for making the test suite run quickly.

In the current code, ongoing animations don't set the `_styleDirty` flag until after the `render` and `loaded` events have already fired, which incorrectly makes the map appear to be fully loaded when it hasn't actually reached steady state. Fixing the ordering in that code makes the test suite take at least four times longer to run.

/cc @anandthakker
