### ISSUE TITLE
Rename "mb-pages" branch to "latest-release" or "stable"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3969]
There's a lot of confusion as to the difference between "mb-pages" and "master." Perhaps we could clarify the differences by renaming the "mb-pages" branch. (Not 100% sure if this is possible with our publishing infrastructure.)

**Comment by mollymerp** [comment]
Yeah, `mb-pages` is key to publishing the repo on mapbox.com but we could look in to what it would take to make a special case in publisher for this repo.

**Comment by bsudekum** [comment]
The gh api now returns the `default_branch` now, ref https://developer.github.com/v3/repos/

<img width="998" alt="screen shot 2017-01-12 at 6 02 04 pm" src="https://cloud.githubusercontent.com/assets/1058624/21915836/4ef03114-d8f1-11e6-8d92-02bcea305c15.png">

Could be useful.
