### ISSUE TITLE
Expose more geojson-vt options in GL JS Geojson sources

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapbox-gl-js#3971]
# Large geojson sources

## Problem

Large geojson sources loaded and tiled via geojson-vt on worker threads can crash clients (over 100 mb raw). 

## Minimal example

**Updated 1/14**

Loading a 170mb uncompressed polygon-geometry geojson with one property per feature source via url:
http://bl.ocks.org/ryanbaumann/raw/2ec3995bd06b8a23ac21eab990d6eaa4/#10/34.0000/-118.1800

1. Crashes on Chrome  55.0.2883.87 m (64-bit) on OSX and Windows 10
2. Success on Firefox 32 bit 50.1.0 on Windows 10
3. Microsoft Edge - Successful  on Windows 10
    * Edge seems to kick off a second worker thread.  It's able to use much more memory than Chrome or 

## Takeaways

* Different browsers yield different results
* Reducing `buffer` parameter reduces worker memory requirements and increases chances of successful tile creation and layer render with large geojson sources.

## Potential Actions

1. Investigate why Chrome crashes while Firefox and Edge succeed.
2. Add to or link to geojson-vt docs on how to use `buffer` parameter effectively.
3. Investigate [tweaking geojson-vt parameters](https://github.com/mapbox/geojson-vt) to efficiently handle specific large geojson sources in GL JS.

**Comment by mourner** [comment]
> Store and create tiles on-demand based on the map viewport, just how remote vector tiles are stored.

This describes how `geojson-vt` already works currently (you can read more about it in [my blog post](https://www.mapbox.com/blog/introducing-geojson-vt/)).

If a particular type of GeoJSON crashes the browser, it should be investigated as a bug. I tested mapbox-gl-js with 100MB sources and they were not causing any crashes.

Your example does not crash for me on Chrome / OS X.

**Comment by ryanbaumann** [comment]
@mourner thank you for the details.  After reading up more on geojson-vt, I updated the ticket subject, example, and first post to reflect the issue more accurately.

**Comment by mourner** [comment]
@ryanbaumann Thanks! I suspect we won't be able to do much about the Chrome difference, but we could expose more of the geojson-vt options to the style spec if this could help. Want to investigate tweaking the options?

**Comment by ryanbaumann** [comment]
@mourner perfect.  Yes, Im happy to tackle evaluating and documenting more geojson-vt options for geojson sources in GL JS.

**Comment by andreschardong** [comment]
hi @ryanbaumann, we also had some issue with large Geojson objects. However the files were really huge, and had to be downloaded from the server and therefore that has a bigger issue than Mapbox GL JS performance. However, mapbox was slowing down with files over 200 MB. Also check if you using formatting and events like hover (that will also affect performance). At the moment we are moving to tiled sources.

**Comment by ryanbaumann** [comment]
Reference https://github.com/mapbox/mapbox-gl-js/issues/3220 - Geojson source memory overhead storing data on the main thread.

**Comment by mourner** [comment]
Let's close this for now as not actionable. It's not a big issue since using 100+ MB GeoJSON files on the client is rarely practical in any case. Feel free to open a new issue if you think we should expose more geojson-vt options or change defaults.

**Comment by ryanbaumann** [comment]
Re-opening this issue to expose the `minzoom` option from geojson-vt in GL JS geojson source.

Minzoom is a powerful performance optimization useful for displaying dense, tightly-clustered point data sets.  Today the only performant alternative to `minzoom` is to use clustering, which works similarly well by reducing the number of features at low zoom levels to create tiles from.  

[Minimal example of using minzoom to optimize vector tile creation time on a dense geojson source](https://bl.ocks.org/ryanbaumann/d075e73beb9396e994ac4a0779babbe9).

**Comment by ryanbaumann** [comment]
Closing again - the `minzoom` feature in geojson-vt is not the best lever here.  The best solution I arrived at was to use a layer `minzoom` value to prevent loading dense tiles at lower zoom levels which cause the map to render slowly.

In general - cluster!  If you can't cluster, set a layer `minzoom` value.

**Comment by Nasiek** [comment]
What about this issue but using LineString as opposed to points?
