### ISSUE TITLE
Can't change text-ignore-placement using setLayoutProperty 

### ISSUE THREAD

**Issue by natew** [mapbox/mapbox-gl-js#3975]
**mapbox-gl-js version**: 0.28.0

### Steps to Trigger Behavior

 ```
map.getLayer('labels').setLayoutProperty('text-ignore-placement', false)
```

This won't actually change anything on the map.

**Comment by jfirebaugh** [comment]
Depending on the layers involved, that may be the expected behavior.

Can you provide a self-contained example that demonstrates the issue you're seeing?

**Comment by natew** [comment]
We've built a whole rendering layer above it, but as simple as I can tell it would look like:

```js
let map = new mapboxgl.Map({
  container: this.nodes.map,
  // style: 'mapbox://styles/mapbox/streets-v9',
  style: {
    version: 8,
    sources: {},
    addSource: () => {},
    glyphs: 'mapbox://fonts/mapbox/{fontstack}/{range}.pbf',
    layers: [],
  },
  zoom: 2,
  center: [0, 0],
  trackResize: false,
})

map.addLayer({
        id: 'labels',
        type: 'symbol',
        layout: {
          'text-field': '{name}',
          'text-padding': 4,
          'text-allow-overlap': false,
          'text-ignore-placement': false,
        },
        paint: {
          'text-color': 'rgb(85, 255, 211)',
        }
})

// load map

element.onClick = () => {
   map.getLayer('labels').setLayoutProperty('text-allow-overlap', true)
   // try this too
   map.getLayer('labels').setLayoutProperty('text-ignore-placement', true)
}

// nothing changes
```

I've tried a few different things around this as well, setting map.repaint = true and doing various combinations of the two settings.

**Comment by jfirebaugh** [comment]
There are a few things that would cause that code not to work. For instance `addSource: () => {}` and the lack of a `source` property on the added layer.

Can you post a complete, working example so we can look into this? Without that, we really can't say what the issue is.

**Comment by natew** [comment]
Do you have a code pen I can try out? Otherwise maybe I can just use some
working map on your site. I can verify it works on a variety of setups of
my own.

**Comment by natew** [comment]
Ok, here is it: http://codepen.io/anon/pen/wgoEMB

Notice it doesn't change to showing dense labels.

Now, if you edit the HTML side, at the very bottom, to have `text-ignore-placement: true` by default, you'll see it shows dense.

So it's not updating after you change the properly.

**Comment by jfirebaugh** [comment]
Thanks for the complete example!

If you change `map.getLayer('labels').setLayoutProperty('text-ignore-placement', true)` to `map.setLayoutProperty('labels', 'text-ignore-placement', true)`, this works as expected. The latter is the [documented public API](https://www.mapbox.com/mapbox-gl-js/api/#Map#setLayoutProperty) for changing layout properties.

Sorry for not spotting that in your original code snippet.

**Comment by natew** [comment]
@jfirebaugh thank you, totally missed that myself, not sure how but oh well!
