### ISSUE TITLE
Setting different color for each polygon in same layer in mapbox

### ISSUE THREAD

**Issue by alvi1987** [mapbox/mapbox-gl-js#3978]
I am displaying geojson data with mapbox-gl js, i want to style each polygon with different color in same layer. Is it possible? Anyone who have faced this issue or done it please help.

**Comment by ryanbaumann** [comment]
@alvi1987 Yes, you can use `data-driven styles` (also known as `property functions`) to style features in a layer based on property values.

https://www.mapbox.com/help/gl-dds-ref/

https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/
