### ISSUE TITLE
Search through existing stores in Store locator

### ISSUE THREAD

**Issue by anvar9991** [mapbox/mapbox-gl-js#3984]
**mapbox-gl-js version**:
I'm new at Mapbox. I've gone through this tutorial https://www.mapbox.com/help/building-a-store-locator/.
### Steps to Trigger Behavior
How can I a search field and it do a search only from the existing stores.
Is that possible?

### Expected Behavior
A User should able to search through stores.

**Comment by mourner** [comment]
Thanks for the report! However, GitHub issues in this repository exist only to report issues with the GL JS library, not to request assistance building an application. Try asking on http://stackoverflow.com/.
