### ISSUE TITLE
How can mapbox-gl-js to have aceess to other coordinates (other than WGS 84) 

### ISSUE THREAD

**Issue by jobryant** [mapbox/mapbox-gl-js#3987]
### How to make mapbox-gl be fit for custmized coordinates
**mapbox-gl-js version**: v0.28.0
    I am trying to modify this work to be fit for other projected coordinate system like EPSG:21413 or other custmized coordinates.
   So, I attempt to modify the  modules used to transform coods and to calculate which tiles to be loaded. But I faild to find the modules be responsible for calculating tiles's index. 
    **So could any tell me where aree they?** 

### Some modules relevant to coordinates transform
As is shown following, I found some modules relevant to coordinates transform, which is applied to transform (B,L) to (col, row).  **Did I miss some modules else?**
 1. js/geo/coordinate.js
 2. js/geo/lng_lat.js
 3. js/geo/lng_lat_bounds.js
 4. js/geo/transform.js

**Comment by jfirebaugh** [comment]
[tile_coord.js](https://github.com/mapbox/mapbox-gl-js/blob/master/js/source/tile_coord.js) may be the other module you're interested in.

**Comment by wangzy123** [comment]
Hi, @jobryant .
Have you found a way to  make mapbox-gl-js display custmized coordinates more than epsg:900913?

**Comment by jobryant** [comment]
> Hi, @jobryant .
> Have you found a way to make mapbox-gl-js display custmized coordinates more than epsg:900913?

Yes, I made it, but it's a invasive scheme.  I don't suggest you do that because it needs multiple modifications of the core.
