### ISSUE TITLE
How to understand the design of fire() and send()

### ISSUE THREAD

**Issue by jobryant** [mapbox/mapbox-gl-js#3988]
### How could I get relations between all the modules and how would they work together?
**mapbox-gl-js version**:v0.28.0
I find it's difficult to debug and analyse the code of mapbox-gl for me. **Most of time `fire()` and `send()` are used to organize the function calling.** I find its difficult for me to seek out which function is callar and which is callee. Is there  any good way to understand the design of mapbox-gl more efficiently?
By the way, where can I find architecture diagram or UML of Mapbox-gl. It'll be very helpful, I believe.

e.g.

`this.dispatcher.send('reloadTile', params, done.bind(this), tile.workerID);`

`this.fire('load');`

``` javascript
    fire(type, data) {
        if (this.listens(type)) {

            data = util.extend({}, data, {type: type, target: this});

            // make sure adding or removing listeners inside other listeners won't cause an infinite loop
            const listeners = this._listeners && this._listeners[type] ? this._listeners[type].slice() : [];

            for (let i = 0; i < listeners.length; i++) {
                listeners[i].call(this, data);
            }

            if (this._eventedParent) {
                this._eventedParent.fire(type, util.extend({}, data, this._eventedParentData));
            }

        // To ensure that no error events are dropped, print them to the
        // console if they have no listeners.
        } else if (util.endsWith(type, 'error')) {
            console.error((data && data.error) || data || 'Empty error event');
        }

        return this;
    }
```

**Comment by jfirebaugh** [comment]
Hi @jobryant. This issue tracker is for reporting bugs or making feature requests. Our team doesn't really have the bandwidth to answer general questions here unless they pertain to a specific bug. I suggest you try stackoverflow.com instead.

**Comment by jobryant** [comment]
Good idea, @jfirebaugh thx.
