### ISSUE TITLE
getSelectedPoints() does not work for Points

### ISSUE THREAD

**Issue by benjaminhon** [mapbox/mapbox-gl-js#3990]
I tried the new function getSelectedPoints(),
would just like to point out that it only works when selecting points in lines or polygons, but not for points themselves.

**Comment by jfirebaugh** [comment]
Hi @benjaminhon. Are you sure you filed this issue in the appropriate repository? Mapbox GL JS does not have a function named `getSelectedPoints`.

**Comment by benjaminhon** [comment]
o sorry, i think i mistook it for mapbox gl draw!
