### ISSUE TITLE
collision of layers when using a separate layer

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#3991]
I have a geojson source which renders a layer of circles (like markers). The order of layers determines which one is on top, however I would prefer not to have my geojson layer collide with e.g. streetname layers etc. (instead of having one on top of the other).

It seems this is worked upon..., but I am not sure:
https://github.com/mapbox/mapbox-gl-js/issues/2703
https://github.com/mapbox/mapbox-gl-js/issues/3034

Any solution currently/ worked on?

**Comment by mourner** [comment]
Yes, this is what #2703 is about. Let's keep the discussion centralized in that ticket.
