### ISSUE TITLE
Allow line labels to be tangential with respect to characters, words, or labels

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3995]
Continued from https://github.com/mapbox/DEPRECATED-mapbox-gl/issues/9

> Our current strategy for labeling lines is to place each _letter_ tangent to the line and allow a maximum angle between letters to be specified.
> 
> It would be nice to generalize this such that individual words or entire labels could be placed along a straight line, tangential to the line being labeled. 
> 
> This would allow roads or rivers that are two curvy to be labeled by our current labeling strategy to be labeled in a visually appealing way. 
> 
> <img width="507" alt="example" src="https://cloud.githubusercontent.com/assets/281306/12564733/bf2416a0-c365-11e5-8f01-a7f9b1153340.png">
> 
> As best I can tell, this is not done in Mapnik or competitive map rendering products but is common practice on print maps.

**Comment by mourner** [comment]
Closing since the issue seems to not be getting much attention despite requiring a non-trivial effort to implement, so we aren't likely to address it soon.
