### ISSUE TITLE
Add support for rendering 3d models 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#3996]
Continued from https://github.com/mapbox/DEPRECATED-mapbox-gl/issues/17

> We are adding support for [simple extrusions](https://github.com/mapbox/mapbox-gl-style-spec/issues/456). For buildings, there are some complex and high-profile landmarks that can't be rendered accurately with simple extrusion:
> 
> ![eiffel-tower](https://cloud.githubusercontent.com/assets/5607844/16136340/b62eef22-33f7-11e6-9982-736ec86cbd42.png)
> _Haiii, Eiffel Tower._
> 
> For these features, it seems like we would want to include 3D models. How would/could this work? How much of a lift is this? 
> 
> /cc @lbud @ajashton @mapbox/gl 

cc @mourner @tmcw @jfirebaugh

**Comment by allthesignals** [comment]
My team is interested in learning more about the status of this feature - we are also in a place where simple extrusions will not work, and we have a wealth of 3d model data that we think would fit better inside our MapboxGL stack. Any chance there's direct access to the scene interface? Is a pathway for this related to https://github.com/mapbox/mapbox-gl-js/issues/6456? Thanks!

**Comment by lbud** [comment]
> Any chance there's direct access to the scene interface? Is a pathway for this related to #6456?

Exactly @allthesignals, custom layers (#6456) will be the soonest you'll be able to accomplish this, and that feature will likely land ~this summer — native Mapbox GL support for 3D models isn't on our short- or medium-term roadmap at this time.

**Comment by allthesignals** [comment]
Thanks, @lbud - I'll keep an eye on this PR here: https://github.com/mapbox/mapbox-gl-js/pull/6124

**Comment by andrewharvey** [comment]
Over on the PR I posted some example code which helps place 3D models at given long, lats

https://github.com/mapbox/mapbox-gl-js/pull/7039#issuecomment-410621717

![selection_999 017](https://user-images.githubusercontent.com/117278/43704356-bb7296ec-99a2-11e8-93ec-a6ff0083cb55.png)

**Comment by allthesignals** [comment]
Fabulous - thanks @andrewharvey!

**Comment by andrewharvey** [comment]
I'll closing this ticket given custom layers support adding 3D models to a Mapbox GL JS map.

An official example will be followed up in #7330

3D terrain mesh is at #1489

**Comment by femski** [comment]
How can we use custom layer to display 3D terrain (by extruding raster DEM heights or something similar)? I had hoped for an example of that. But it seems its not possible at this time, correct ?

**Comment by Daandeve** [comment]
Is it possible to move the 3d object without re-importing the 3d model?

**Comment by andrewharvey** [comment]
> Is it possible to move the 3d object without re-importing the 3d model?

@Daandeve Using the example at https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/, the render method is called each frame and it refers to the modelTransfom object. So if you update your the modelTransform object to a new location, the model will move on the next frame.

**Comment by andrewharvey** [comment]
> How can we use custom layer to display 3D terrain (by extruding raster DEM heights or something similar)? I had hoped for an example of that. But it seems its not possible at this time, correct ?

@femski It is possible to build that yourself at the moment, I have implemented it, in a similar way to https://blog.mapbox.com/bringing-3d-terrain-to-the-browser-with-three-js-410068138357?, but I don't have the code to share as it's wrapped up in a whole application.

However you can see at https://blog.mapbox.com/taking-our-maps-to-the-next-dimension-dbeee37a7c4c Mapbox is working on adding this as an out of the box feature.

**Comment by Daandeve** [comment]
@andrewharvey Do you have a example? 
I'am new to both mapbox and three.js. :)

**Comment by andrewharvey** [comment]
> @andrewharvey Do you have a example?

@Daandeve sorry I don't.

**Comment by Daandeve** [comment]
Okay thanks!
I got it working.

**Comment by come25136** [comment]
@andrewharvey Hello,
Is there an example of adding multiple models to one custom layer and changing their coordinates?

I tried it myself, but I couldn't implement it well. :(

**Comment by jbixon13** [comment]
@Daandeve would you be able to share your approach?

**Comment by bvitlas** [comment]
I'm also very curious to add multiple gltf or .obj models to the map in a single custom layer. Can anyone give an example code.

**Comment by gtk2k** [comment]
@andrewharvey 
Please. Please also post an example of adding multiple 3D models to one custom layer.

**Comment by linsmeyer** [comment]
> My team is interested in learning more about the status of this feature - we are also in a place where simple extrusions will not work, and we have a wealth of 3d model data that we think would fit better inside our MapboxGL stack. Any chance there's direct access to the scene interface? Is a pathway for this related to https://github.com/mapbox/mapbox-gl-js/issues/6456? Thanks!

Hi, maybe i help you because my experiency is very large around this. You feel free tô call me +55349967019714
