### ISSUE TITLE
Display an error if a user specifies a nonsensical style layer type & geometry type combination

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4002]
Migrated from https://github.com/mapbox/DEPRECATED-mapbox-gl/issues/31 by @boundsj 

> A recent support request (for iOS) noted that we don't prohibit a developer from creating a GeoJSON source that contains a polyline and then using a fill style layer to style it. However, on iOS and Android, this combination results in some undesirable clipping behavior at high zoom levels (see screenshot below).
> 
> The solution is to use polygons with fill layers. However, should we better support the problematic combination noted above or do something mopre to warn developers that this is not supported?
> 
> #### Source with an polyline styled with a fill layer -- zooming in illustrates the reported issue
> 
> ![screenshot 2016-12-08 14 23 05](https://cloud.githubusercontent.com/assets/63186/21030137/db6d73a6-bd51-11e6-924f-9bc405b75696.png)
> 
> cc @1ec5 @cammace @jfirebaugh

**Comment by jfirebaugh** [comment]
→ #5729
