### ISSUE TITLE
Symbol placement should avoid ambiguous placement near intersections

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4003]
Migrated from https://github.com/mapbox/DEPRECATED-mapbox-gl/issues/22 by @friedbunny 

> This is a strange edge case: a [two-way road that forms a braided pattern](http://www.openstreetmap.org/way/224941798).
> 
> With [GL-JS](https://api.mapbox.com/styles/v1/mapbox/streets-v8.html?fresh=true&title=true&access_token=pk.eyJ1IjoiZnJpZWRidW5ueSIsImEiOiI3NDUyMmNjOTMxMmNlNWJhYjRkMzQxNzQzNzdhNTU2YSJ9.vYFDbe6aqIv2C9P7Gy_rCw#18.27/37.79279/-122.42800) and on native, the one-way arrows are placed near the intersections of the braid. The direction of travel remains the same, but our map appears to indicate that you should cross into the opposing lane:
> 
> ![screen_shot_2016-07-26_at_4_39_01_pm](https://cloud.githubusercontent.com/assets/1198851/17159135/f2c4ae50-534f-11e6-9ccc-8c9fd46eb3aa.png)
> 
> This road is mapped as two continuous lines with shared points where they intersect:
> 
> ![screen shot 2016-07-26 at 4 27 01 pm](https://cloud.githubusercontent.com/assets/1198851/17159191/4f183cb2-5350-11e6-88fc-7798afd1abf1.png)
> 
>  Arguably, this could be mapped differently and avoid this issue, but the fact that symbols are drawn so close to intersections is something we should look at addressing.
> 
> /cc @1ec5 @frederoni

**Comment by mourner** [comment]
Looks like there's not much interest in addressing this because of the rarity of the issue and disproportionately high effort involved in fixing it.
