### ISSUE TITLE
querySourceFeatures Returns Incorrect Geometry at Zoom Levels Above Vector Tileset Max

### ISSUE THREAD

**Issue by x9xjdzz9** [mapbox/mapbox-gl-js#4011]
When I call querySourceFeatures at a zoom level which is greater than the max zoom level of my vector tileset, the geometry coordinates are incorrect.

The example below will query the features and print their coordinates to the console when you click on the map. The initial zoom will print bad coordinates. If you zoom out and then click, it will print good coordinates. The max zoom level of the vector tileset is 11.

https://output.jsbin.com/melugiseso

**Comment by andrewharvey** [comment]
Is this the same as https://github.com/mapbox/mapbox-gl-js/issues/3722

**Comment by x9xjdzz9** [comment]
Yes, it probably is. Sorry about that.
