### ISSUE TITLE
"map.addControl(new mapboxgl.GeolocateControl());"   doesn't work in chrome.

### ISSUE THREAD

**Issue by anvar9991** [mapbox/mapbox-gl-js#4014]
**mapbox-gl-js version**:
mapbox-gl-js/v0.31.0

"Locate the user" function doesn't work in chrome. but works in firefox.

the icon is not appeared

please, check here: http://store-locator.businesscatalyst.com/

**Comment by Naimikan** [comment]
Hi @anvar9991!

Google removed Geolocation API support on websites without SSL (HTTPS) --> https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only
