### ISSUE TITLE
Unable to zoom map if webpage is user-scalable

### ISSUE THREAD

**Issue by IvanSanchez** [mapbox/mapbox-gl-js#4015]
Steps to reproduce:
* Create a webpage with**out** a `user-scalable:no` viewport meta-tag (e.g. http://jsbin.com/donayayohi , source at http://jsbin.com/donayayohi/edit?html,js,output )
* Open up that webpage in a touchscreen device (phone/tablet)
* Try performing a pinch-zoom operation on the map
* The map will never zoom in. Trying to zoom in will just make the browser zoom in the whole page.

Also:
* Try panning the map vertically
* The map viewport will always display the same area, it will be impossible to pan the map to show something north or south of the initial view bbox.

Reproducible (at least) with chrome 55 on android and mapbox-gl-js v0.31.0.

The obvious workaround is to include a `<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />` tag in the `<head>` of the page, but some web authors (me included) will need to add maps to user-scalable pages.

I suggest applying the same behaviour as in https://github.com/Leaflet/Leaflet/pull/4552 : apply a `touch-action` CSS property to the map, but only if the map is interactive. Or rather, only if the `TouchZoomRotateHandler` or the `DragPanHandler` are enabled, as appropriate.

**Comment by jdfx** [comment]
I am having the exact same issue, however this is not a problem on all mobiles.

Furthermore adding user-scalable=no does not fix my problem.

**Comment by jfirebaugh** [comment]
⇢ #4259
