### ISSUE TITLE
[FireFox] SyntaxError: missing = in const declaration

### ISSUE THREAD

**Issue by babsonmatt** [mapbox/mapbox-gl-js#4030]
**mapbox-gl-js version**: 0.31.0

### Steps to Trigger Behavior

 1. Use with FireFox

### Expected Behavior
It should work
### Actual Behavior

FireFox throws the following error: ```SyntaxError: missing = in const declaration```

![image](https://cloud.githubusercontent.com/assets/853220/22163911/e30b0c66-df22-11e6-8b5f-8f3bea9a024e.png)

![image](https://cloud.githubusercontent.com/assets/853220/22163926/fb9c2616-df22-11e6-9b4a-5caa2d7fcc72.png)

**Comment by jfirebaugh** [comment]
See https://github.com/mapbox/mapbox-gl-js#using-mapbox-gl-js-with-other-module-systems -- you need to require the distribution build.
