### ISSUE TITLE
It seems that canvas element doesn't resize when Map#resize is called

### ISSUE THREAD

**Issue by Naimikan** [mapbox/mapbox-gl-js#4044]
**mapbox-gl-js version**: v0.31.0

[CodePen Example](http://codepen.io/Naimikan/pen/jyLQKa)

### Steps to Trigger Behavior

 1. Click "Toggle sidebar" button.

### Expected Behavior
The container and canvas should resize to 100%.

### Actual Behavior
Only the container resizes to 100%

Thanks!

**Comment by jfirebaugh** [comment]
You have a CSS width transition on the map element, and you're calling `map.resize()` when it starts, not when it ends, so it's resizing to the width at the beginning of the transition.
