### ISSUE TITLE
Allow zoom levels beyond 21

### ISSUE THREAD

**Issue by jo-chemla** [mapbox/mapbox-gl-js#4051]
## Motivation

Currently using mapbox to display raster layers at different scales and resolutions, we are computing tiles from geotiffs. We'd like to visualize very precise ortho-imagery generated from SfM, onto mapbox with a cm/mm resolution. To do so, we need to be able to zoom over level 21. 

## Design Alternatives

Displaying tiles with zoom level above 21 might be proposed on an external link, disabling other mapbox user interaction - only zooming in and out and panning in the ortho. 

## Design

Allow zoom level above 21. Potential issues might be to lose the user once he or she has zoomed in too much and cannot locate himself. Issues with performances were mentionned, cannot find it again. 

### Implementation

Similar issue in Mapbox GL Native seems to state that some bugs preventing this are now removed. There seems to be a zoom level capped at 25 in this version still. See here : https://github.com/mapbox/mapbox-gl-native/issues/7155

**Comment by ryanbaumann** [comment]
@jo-chemla there is a parameter for the `Map` called `maxZoom` you can set when initializing the map container.  You can set this value higher - the default is 20.

https://www.mapbox.com/mapbox-gl-js/api/#Map

**Comment by jo-chemla** [comment]
You're right, this works immediately. I thought it was capped to 20 as shown in the doc, thanks!

**Comment by jo-chemla** [comment]
Using the doc, I cannot load raster tiles above zoom layer 22, although I set the maxzoom of layer to 24 and maxZoom of map to 25. By the way, I cannot set the maxzoom of a rasterlayer source above zoom 24, which is still an issue for me. 
The tiles above zoom level 22 are not even fetched from chrome network console, although tiles at zoom 22 are indeed fetched.

var source = {
	"type": "raster",
	"tiles": ["http://localhost/rastertiles/{z}/{x}/{y}.png"],
	"tileSize": 256, 
	"scheme": 'tms'
};

var layer = {
	"id": "raster-tiles",
	"type": "raster",
	"source": "rastertiles",
	"minzoom": 0,
	"maxzoom": 24
};
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    minZoom: 0,
    maxZoom: 25,
	center: [0,0],
	zoom: 15
});
map.on('load', function ()  {
	map.addSource('rastertiles', source);
	map.addLayer(layer);
	map.setMaxZoom(25);
	map.on('zoomend', function() {
		console.log(map.getZoom())
	})
});

**Comment by lucaswoj** [comment]
@jo-chemla Please open a new issue for this bug with a self-contained example that doesn't rely on local dev servers, if possible.

**Comment by jo-chemla** [comment]
Done, and there is indeed a problem - I've attached a sample html and tiles with zoom level above 22 
https://github.com/mapbox/mapbox-gl-js/issues/4067
