### ISSUE TITLE
Generate fuzz tests for "Map#queryRenderedFeatures"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4053]
Here's a sketch of an idea to create more robust tests for `Map#queryRenderedFeatures`:

 - create or generate a map style in which each layer is of a known solid color
 - chose a random camera position for the map
 - choose a set of {random, edge case} {points, bboxes} in the viewport
 - run `Map#queryRenderedFeatures` at each of the {points, bboxes}
 - validate the results of `Map#queryRenderedFeatures` by comparing the pixel color of the rendered map with the known layer colors

**Comment by mourner** [comment]
No interest in exploring this at the moment.
