### ISSUE TITLE
Return promises and/or accept callbacks for all async methods

### ISSUE THREAD

**Issue by gertcuykens** [mapbox/mapbox-gl-js#4061]
https://www.mapbox.com/mapbox-gl-js/api/#Map#setStyle

Can `setStyle` return a promise please or have a callback parameter? I am having a hard time doing stuff like `map.addSource('markers',...)` and `map.getSource('markers').setData(markers)` after I do `setStyle()`.

Either the event `map.on('styledata',...)` triggers too soon, or triggers a million times :)

`setStyle(...).then(...)` for the win :P

**Comment by lucaswoj** [comment]
I completely agree with the sentiment here. Let's centralize discussion in https://github.com/mapbox/mapbox-gl-js/issues/3964

**Comment by andrewharvey** [comment]
@lucaswoj Is there a workaround for this in lieu of #3964?

It seems impossible right now to do `map.addSource/map.addLayer` after a `map.setStyle` since you don't know when it's ready and if it's not ready it will error `Uncaught Error: Style is not done loading`.

**Comment by lucaswoj** [comment]
@andrewharvey That approach should work. I recommend listening for the `styledata` event rather than using a 200ms timeout.

**Comment by hoogw** [comment]
when I change style 
`map.setStyle()`


I get error  `Uncaught Error: Style is not done loading
`



This solved my problem 

Do not use  `map.on("load", loadTiles); `

instead use 

`map.on('styledata', function() {
    addLayer();
});`

**Comment by EthanHermsey** [comment]
Persist sources and layers when switching a map's base style: https://docs.mapbox.com/mapbox-gl-js/example/style-switch/
