### ISSUE TITLE
Unable to acquire assertion for process 0 after browsing on iOS

### ISSUE THREAD

**Issue by stackTom** [mapbox/mapbox-gl-js#4063]
**mapbox-gl-js version**: 0.31.0 (occurred on previous versions as well)

### Steps to Trigger Behavior

 1. visit ec2-52-41-231-16.us-west-2.compute.amazonaws.com or http://wandergis.com/memory-leak-test-case/ on an iPhone.
 2.
 3.

### Expected Behavior
Site works
### Actual Behavior
Site crashes and reloads

When I visit my site made with mbtiles which contain a large number of features on my iPhone, it works fine, but then after panning and zooming in/out for a while, the site crashes. On chrome for iOS, it says an error has occurred, and shows a chrome crash screen. On Safari for iOS, it shows an error saying "an error has occurred and the site has been reloaded", or something to that effect.
I made a simple WKWebView() app for my iPhone, and what happens is that the view turns white (the site never comes back after that). In the Xcode console, I receive the error message: "2017-01-29 01:59:40.635787 h[539:91007] #WK: Unable to acquire assertion for process 0".
Similar symptoms happen on this page: http://wandergis.com/memory-leak-test-case/
After pressing update data and waiting for the lines to appear, I can browse for a bit, but then the WKWebView crashes with messages like this:
"2017-01-29 02:02:37.909735 h[575:93325] #WK: Connection::waitForSyncReply: Timed-out while waiting for reply, id = 196 (this message can appear multiple times but then is followed by message below)
2017-01-29 02:02:38.469576 h[575:93371] #WK: Unable to acquire assertion for process 0"

Is this a gl js bug, or is there something I can do to avoid this? Is there a timeout I must configure somewhere? Thanks for any help

**Comment by stackTom** [comment]
After doing more tests with instruments, it appears that there is a memory leak somewhere. I don't believe it is in either of the linked sites, as a similar issue happens when I point my iOS app to render this page: https://www.mapbox.com/mapbox-gl-js/examples/
Initially, the app consumes around 1.2 gigabytes of RAM or less, but after zooming/panning for a while, instruments reports that the app consumes 1.5 gigabytes of RAM. It never decreases throughout the entirety of the app (although it doesn't crash as that app is simpler), even I leave the app still with no interaction.

**Comment by jfirebaugh** [comment]
Duplicating against #4052, since both issues are about increasing memory use on iOS while panning and zooming.
