### ISSUE TITLE
Add text clipping option on symbol layers

### ISSUE THREAD

**Issue by pixnlove** [mapbox/mapbox-gl-js#4064]
Hi everybody !

I have a problem with my symbol layer : my text is not hidden by other symbols, how to do like on the second screenshot (screenshot from [https://roadtrippers.com](https://roadtrippers.com) who is using Mapbox too)? FYI, my layer looks like :
```
var layer = {
        "id": "marker",
        "type": "symbol",
        "source": "markers",
        "layout": {
          "text-font": ["Lato Black"],
          "text-padding": 20,
          "text-anchor": "top",
          "text-offset": [0, -2.3],
          "text-size": 14,
          "text-allow-overlap": true,
          "text-field": "{index}",
          "text-justify": "center",
          "icon-offset": [0, -22],
          "icon-image": "marker",
          "icon-allow-overlap": true
        },
        "paint": {
          "text-color": "#FFFFFF"
        }
     };
```

![issue_mapbox](https://cloud.githubusercontent.com/assets/2814767/22408685/3048f180-e67d-11e6-821d-81e88f251d77.png)

**Comment by mollymerp** [comment]
Hi @pixnlove,
I would try setting `"text-allow-overlap": false` and `"text-optional": true`. Also, Roadtrippers is using the [`Marker`](https://www.mapbox.com/mapbox-gl-js/api/#Marker) class, not a symbol layer.

This doesn't appear to be a bug or feature request, and unfortunately we don't have the bandwidth to offer support on Github. I suggest you post future questions like this on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox-gl-js).

**Comment by pixnlove** [comment]
Thanks for your help @mollymerp. I think it's a feature request but maybe I'm doing something wrong. When I'm adding these two properties, I'm losing some text values and text index behaves badly. My map looks like now:

![capture d ecran 2017-02-01 a 18 05 24](https://cloud.githubusercontent.com/assets/2814767/22518349/925d55ba-e8ac-11e6-866c-3f7ae8ace4e2.png) 

And my layer is now:
```
var layer = {
        "id": "marker",
        "type": "symbol",
        "source": "markers",
        "layout": {
          "text-font": ["Lato Black"],
          "text-padding": 20,
          "text-anchor": "top",
          "text-offset": [0, -2.3],
          "text-size": 14,
          "text-allow-overlap": true,
          "text-field": "{index}",
          "text-justify": "center",
          "icon-offset": [0, -22],
          "icon-image": "marker",
          "icon-allow-overlap": true
        },
        "paint": {
          "text-color": "#FFFFFF"
        }
     };
```
Using marker like Roadtrippers is not very powerful with a large dataset, I would like to do the same thing with a symbol layer but you seem to consider the text as an other layer. It will be cool to have a layout property "text-clip-icon".

**Comment by mollymerp** [comment]
@pixnlove I see what you mean. I think this might be a technical limitation of our current implementation of symbol layers – we draw all icons in a layer, and then all text on top of that, so there is no maintained relationship between a single icon and its text label in the render order. 
I agree this would be a great enhancement, but it would require a significant refactor.

**Comment by pixnlove** [comment]
@mollymerp, do you have some news about this feature request ?

**Comment by mollymerp** [comment]
@pixnlove this is not on our immediate roadmap unfortunately.

**Comment by nrako** [comment]
I have the same undesired behavior but with a symbol layer. Using an icon with some inner text, I'm using that workaround with `text-optional`. But that isn't a really neat result. I wish the text and icon/marker wouldn't appear to be drawn on two different layer.

![screen shot 2017-04-10 at 09 34 06](https://cloud.githubusercontent.com/assets/425397/24850574/e1f6dfd4-1dd0-11e7-98aa-47b9fb0aadad.png)
An example here, 10 collides with 9 and therefore is hidden, but 9 is still above the icon of 10 😑.

**Comment by jfirebaugh** [comment]
Equivalent issue for native: https://github.com/mapbox/mapbox-gl-native/issues/8235.

**Comment by wthorp** [comment]
I'll go ahead and upvote this feature.

**Comment by sjorsrijsdam** [comment]
For those interested, we also ran into this issue and we "solved" it by generating icons on the fly on a off-screen canvas and using token substitution to match the correct image with the correct point.

Roughly what we did is:
```javascript
prices.forEach((price) => {
    const imageData = createIcon(price);
    map.addImage('house-' + price, imageData);
});

map.addLayer({
    layout: {
        'icon-name': 'house-{price}'
    }
});


```

**Comment by nrako** [comment]
Oh that's a very interesting approach! Thanks @sjorsrijsdam

**Comment by nrako** [comment]
@sjorsrijsdam – I was looking at the API doc for [`map#addImage`](https://www.mapbox.com/mapbox-gl-js/api/#map#addimage) and I noticed the following : 
> An Map#error event will be fired if there is not enough space in the sprite to add this image.

Then I found this [information](https://www.mapbox.com/help/define-sprite/):
> Sprites can have a maximum size of 1024x1024 pixels (2048x2048 for high DPI displays) – that means the whole sprite containing all icons must be smaller than 1024x1024 pixels.

Did you ever encountered that issue, what type of scale do you have experience with? Could you confirm that 1024x1024 is the limit?

**Comment by nrako** [comment]
Not sure this limit is actually enforced... I can't spot anything on [Map.addImage](https://github.com/mapbox/mapbox-gl-js/blob/03680eb57489cf442f8c538141ea27c73d98d532/src/ui/map.js#L1102) on [Style.addImage](https://github.com/mapbox/mapbox-gl-js/blob/03680eb57489cf442f8c538141ea27c73d98d532/src/style/style.js#L423) nor the [ImageManager.addImage](https://github.com/mapbox/mapbox-gl-js/blob/6717d08a224e4cd3aa8d0a561fa78cfddfa168c9/src/render/image_manager.js#L81)

🤔

**Comment by sjorsrijsdam** [comment]
@nrako We never ran into limits of the sprite size. We did have to abandon this idea though because of performance problems on mobile. Every time you would move or zoom the map, Mapbox would need to transfer the icon data of each icon to the WebGL context. That turned out to be a bottle neck.

**Comment by nrako** [comment]
@sjorsrijsdam – Thank you for sharing your experience. I'm not totally sure I understand why Mapbox would need to transfer all images data to the WebGL context on all "camera change" – my quick research on that topic was vain. I might just try and inspect that by myself.

Could you share what approach you ended up taking?

**Comment by jfirebaugh** [comment]
Mapbox GL JS does not transfer all images data to the WebGL context on every camera change -- only when a tile is loaded or the image is changed.

**Comment by sjorsrijsdam** [comment]
We ended up using just a single image for all items on the map and used a popup to show the price.
I probably should have added that we also fetched new data for that layer on every `moveend` en `zoomend`. So, it was probably the `setData` call that would trigger a regeneration of tiles.

**Comment by Sirpion** [comment]
At the moment it turns out that there are 3 possible options (to create behavior as in the image in the first post):
**1. Use the markers**
[https://bl.ocks.org/stevage/23d881a66e2bcca385d8cc074691b674](https://bl.ocks.org/stevage/23d881a66e2bcca385d8cc074691b674)
**2. Generating icons on the fly**
[https://jsfiddle.net/gxc5ca9d/15/](https://jsfiddle.net/gxc5ca9d/15/)
**3. Adding each icon to a new layer**
[https://codepen.io/Sirpion/pen/MXLvbO/](https://codepen.io/Sirpion/pen/MXLvbO/)

Suppose there is a need to create> 400 labels with texts that will be moved on the map in real time. 
Which of these options will cause less damage to performance? 
Or there were new options to implement this behavior (without hiding the text in a collision)?

**Comment by andrewharvey** [comment]
One solution to this may be to group these layers in a way that tells the renderer to draw these on a per feature level first. ie. feature A layer 1,2,3 . then render feature B layer 1,2,3, then composite those two.

**Comment by kapone3047** [comment]
This is a ridiculously simple and common use case that I can't believe is not supported. Have people found any practical workarounds for this?

**Comment by mushon** [comment]
Almost 3 years after this issue was opened, I still can't believe there is no proper solution from Mapbox to this basic issue. This is causing us major grief and is a huge blindspot for Mapbox

<img width="931" alt="Screen Shot 2019-10-27 at 17 45 10" src="https://user-images.githubusercontent.com/27123/67637340-52fb2980-f8e2-11e9-8343-89d6015b980f.png">

Please tell me this is already fixed and I'm just looking in the wrong place

**Comment by gotestrand** [comment]
Hi, any news on this feature request? Any possible workaround?

**Comment by gitcatrat** [comment]
Sorry, repeating the question: has anyone found reasonable workaround?

**Comment by lukashass** [comment]
@gotestrand @gitcatrat We ended up generating icons on the fly with [#map.event:styleimagemissing](https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:styleimagemissing) as suggested above.

Have a look at [Map.vue#L258](https://github.com/kiel-live/kiel-live/blob/6558e8fff8b466bdc4328a3b583ae3149d46d05b/packages/app/src/components/Map.vue#L258). We did not notice any performance problems, but keep in mind our icons are limited to only around 200 different ones. You can see the result of this at https://kiel-live.github.io/map

**Comment by gitcatrat** [comment]
@lukashass Not really an option because `text-field` contains a float that can be anything from 0 to millions.

**Comment by tristyntech** [comment]
I don't know if this will work for everyone, but this worked for me. On the left you can see a number of the circles do NOT have the text overlay. On the right you can see it is fixed. The way I did it was:
1) set the text symbol layers 'text-padding': 0. The text padding defaults to 2, so it makes the text clustering a little over-sensitive
2) 2 and 3 digit numbers have a wider radius than the single digit numbers (obviously). So for the 2 digit numbers I made the text smaller than the single digit numbers. And I made the 3 digit numbers slightly smaller than that, using an expression. 
And that's it. Hope it helps someone. 
<img width="843" alt="Screen Shot 2021-01-26 at 1 07 55 AM" src="https://user-images.githubusercontent.com/29826607/105811935-f4a07900-5f72-11eb-8240-1cf0be81ec52.png">

<img width="941" alt="Screen Shot 2021-01-25 at 2 56 05 PM" src="https://user-images.githubusercontent.com/29826607/105811693-a0959480-5f72-11eb-91d1-98586310d0ab.png">

**Comment by tristyntech** [comment]
> Sorry, repeating the question: has anyone found reasonable workaround?

I found something that worked for me, please try it and let me know if it helps.

**Comment by tristyntech** [comment]
> Hi, any news on this feature request? Any possible workaround?

I found something that worked for me, pls try it and let me know if it helps.

**Comment by xabbu42** [comment]
this seems to be similar to the issue #10002 and could also be helped by #10123

**Comment by julianmlr** [comment]
>           let markers = {};

>           this.realEstates.features.forEach(realEstate => {
>             let el = document.createElement('div');
>               el.innerHTML = "<span style=\"font-family:quicksand\" class='text-body-1'>" + this.$n(realEstate.properties.price, 'currencyNoCents') + "</span>" ;
>             el.className = 'rounded-label';
>             markers[realEstate.id] = new Mapbox.Marker(el)
>                 .setLngLat(realEstate.geometry.coordinates)
>                 .addTo(this.map);
>           })


> .rounded-label {
>   background: white;
>   padding: 0.25em 0.5em;
>   font-size: 16pt;
>   border-radius: 1em;
>   border:1px solid lightgrey;
>   
> }


Here another version of this here  [https://bl.ocks.org/stevage/23d881a66e2bcca385d8cc074691b674](url) 
Makers really have a nice behavior. Maybe this helps you. 

![image](https://user-images.githubusercontent.com/26934306/117051211-93790600-ad16-11eb-99e2-61831a858464.png)

**Comment by pratik-kanthi** [comment]
@julianmlr markers aren't as performant as symbols when you have to draw hundreds of them

**Comment by Merynek** [comment]
Any updates? MapBox still has this issue, really?

**Comment by vjeranc** [comment]
@Merynek

mapbox-gl-js isn't under an open/permissive license anymore. Any contributions coming from Mapbox will probably align with their business goals.

Any other company is probably using the older version that is under a permissive license and changes made to that would be in some public fork. Not sure if it exists.

**Comment by gtsl-2** [comment]
1. Set geojson to connect all the id's that go into cluster and set them to the id of clusterProperties.
`    cluster: true,
    clusterMaxZoom: 20,
    clusterRadius: 100,
    clusterProperties: {
      id: ["concat", ["get", "id"]],`
      
 2. Next, for each rendering, if the source's multiple cluster ids overlap, only the first one should be used. Then, Marker is created from feature3 data.
 `
 map.current.on("render", async function renderListener() {
     const features = map.current.querySourceFeatures("spotsources");
     const features2 = Object.values(
        features.reduce((acc, item) => {
          acc[item.properties.id] = item;
          return acc;
        }, {})
      );
 　function filterArray(array) {
        var result = [];
        for (let i = 0; i < array.length; i++) {
          var isSubstring = false;
          for (let j = 0; j < array.length; j++) {
            if (i !== j) {
              if (array[j].properties.id.includes(array[i].properties.id)) {
                isSubstring = true;
                break;
              }
            }
          }
          if (!isSubstring) {
            result.push(array[i]);
          }
        }
        return result;
      }
      const features3 = filterArray(features2);`
      
 **This way, there is absolutely no overlap of multiple clusters!**

**Comment by elliotclements** [comment]
Anyone found a solution to this? 
I was hoping this would be an easy fix. 

We're not using clustering and are visualizing several assets on the map. When assets overlap we have issues where the text disappears.

We have 2x Layers. 1 layer for the background circles, and 1 layer as a symbol which holds the text. Both layers are set to the same data source.

Is there a concept of hierarchy whereby assets stack behind one another if they're overlapping. 

![Screenshot 2024-09-04 204616](https://github.com/user-attachments/assets/c3e54718-e61c-4e34-9c5d-a7c052acedc9)

**Comment by tristan-garaud** [comment]
Having the same issue. This is insane that it has been running for the past 7 years... . I hope I'm missing something here.

**Comment by alexshalamov** [comment]
@tristan-garaud @elliotclements One possible solution is to use `symbol-sort-key` to enforce the feature rendering order. Please check [this render test](https://github.com/mapbox/mapbox-gl-js/tree/main/test/integration/render-tests/symbol-sort-key/text-ignore-placement) for reference.

**Comment by tristan-garaud** [comment]
@alexshalamov Oh wow, I was sure that I try this approach without success. Did it again with the example and it worked. Don't know what I missed the first time but thanks, it works.

**Comment by elliotclements** [comment]
Thanks Alex! I've been looking for this solution for months.
I combined it with an SDF image to allow me to dynamically change the colour 👌

**Comment by jonashofer** [comment]
@elliotclements Could you elaborate on your approach since it sounds like we have the same issues/requirements with the general layering issue here but also combined with the color?

**Comment by underoot** [comment]
@jonashofer You can use [SDF](https://docs.mapbox.com/help/troubleshooting/using-recolorable-images-in-mapbox-maps/) `icon-image`, which you can add to your map through [`addImage`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addimage) API and specify `sdf: true` there. SDF image can be colorized with paint property [`icon-color`](https://docs.mapbox.com/style-spec/reference/layers/#paint-symbol-icon-color). So you can add to your layer of symbols SDF image `icon-image` and use `icon-color` to change color accordingly to your data and by adding `symbol-sort-key` you can avoid cluttering of text of your symbols

**Comment by underoot** [comment]
Thank you all! I'm going to close issue, because `symbol-sort-key` property could solve original issue. Feel free to open new one if some new details will arise
