### ISSUE TITLE
Rasterlayer MaxZoom above 22 not loading

### ISSUE THREAD

**Issue by jo-chemla** [mapbox/mapbox-gl-js#4067]
Following https://github.com/mapbox/mapbox-gl-js/issues/4051

**mapbox-gl-js version**: 0.32

### Steps to Trigger Behavior

 1. Load Raster and SetMaxZoom to 25
 2. Zoom above zoom level 22
 3. Tiles above zoom level 22 do not load

### Expected Behavior
Please see following example with HTML and tiles folder - that you need to host on a server, may it be local. 
https://www.dropbox.com/s/r7s2lea3ml10nbi/sample_rastertiles_z25.zip?dl=0

### Actual Behavior
```
<html>
<head>
<script src='https://api.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.css' rel='stylesheet' />
</head>

<body>
<div id='map' style='width: 1200px; height: 800px;'></div>
<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.0.1/mapbox-gl-geocoder.js'></script>
<link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.0.1/mapbox-gl-geocoder.css' type='text/css' />
<script>
mapboxgl.accessToken = 'pk.eyJ1IjoiaWNvbmVtIiwiYSI6ImNpbXJycDBqODAwNG12cW0ydGF1NXZxa2sifQ.hgPcQvgkzpfYkHgfMRqcpw';

var source = {
	"type": "raster",
	"tiles": ["http://localhost/alkosh_z0/{z}/{x}/{y}.png"],
	"tileSize": 256, 
	"scheme": 'tms'
};

var layer = {
	"id": "raster-tiles",
	"type": "raster",
	"source": "alkosh_z0",
	"minzoom": 0,
	"maxzoom": 24
};
/*
	"sources": {
		"alkosh-z0": {
			"type": "raster",
			"tiles": ["http://localhost/alkosh_z0/{z}/{x}/{y}.png"],
			"tileSize": 256, 
			"scheme": 'tms'
		}
	},
	"layers": [{
		"id": "raster-tiles",
		"type": "raster",
		"source": "alkosh-z0",
		"minzoom": 0,
		"maxzoom": 26
	}]
*/
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    minZoom: 0,
    maxZoom: 26,
	center: [43.09602610660372, 36.73823797879133],
	zoom: 15
});
map.on('load', function ()  {
	map.addControl(new MapboxGeocoder({
		accessToken: mapboxgl.accessToken
	}));
	map.addSource('alkosh_z0', source);
	map.addLayer(layer);
	map.setMaxZoom(26);
	map.on('zoomend', function() {
		console.log(map.getZoom())
	})
});

</script>
</body>
</html>
```

**Comment by juliantai** [comment]
MaxZoom only works on raster tiles up to maxzoom of 24 according to this. https://github.com/mapbox/mapbox-gl-style-spec/pull/572

Anyone know why this is the case?

**Comment by andrewharvey** [comment]
> MaxZoom only works on raster tiles up to maxzoom of 24 according to this. mapbox/mapbox-gl-style-spec#572

@jo-chemla This test code shows it working for zoom 24 http://jsbin.com/weroyu/edit?html,output

> Anyone know why this is the case?

The style spec had a limit of 22, which I increased to 24 in https://github.com/mapbox/mapbox-gl-style-spec/pull/572. I only increased it to 24 because that was enough for my needs. I can't remember though if there were any significant GL JS issues preventing setting it higher.

**Comment by jo-chemla** [comment]
@andrewharvey Alright Thanks a lot for your example. I was only setting the layer maxzoom, and it is now working correctly. If there is no reason not to, can you please increase the maxzoom upper limit to 28 for rasterlayers? I need it for some tiled ortho images that have that pixel precision.

**Comment by andrewharvey** [comment]
I'd suggest trying to increase the value for the max zoom in the mapbox-gl-style-spec like https://github.com/mapbox/mapbox-gl-style-spec/pull/572/files and seeing if that's the only change that needs to be made or if there are gl js changes to be made too.

**Comment by jo-chemla** [comment]
I'd like to change this stylespec, based on the v8 reference - onlyupdating the maxzoom and minzoom upper bound to 28 instead of 24. I do not see yet how to do that - I can define a style and use it using map.setStyle(new mapboxgl.Style('http://stle.json')) but doing so I do not update the style spec itself. Should I clone mapbox gl js repo, edit this file - in the mapbox style spec repo -, build and use the built library in the html ? If so, can you please point me to the correct material to do that. Thanks again!

**Comment by jo-chemla** [comment]
Here is my feedback: 
 - I've cloned mapbox-gl-js and mapbox-gl-style-spec, 
 - changed the maxzoom and minzoom maximum value to 28 in v8.min.js file, 
 - used npm link to link my version of mapbox-gl-style-spec to mapbox-gl-js (going in the module directory shows my modifications, so linking is correct). 
 - built using npm run build-dev and copied pasted resulting js and css to my server folder, and used this library nistead of remote 0.32.1. 

Result is that tiles above zoom 24 are not loaded (tiles for zoom levels u pto 24 are loaded correctly), although they exist on the server. When looking at the network panel in chrome console, I can see they are downloaded, although they are not displayed on mapbox. Same happens for zoom level above 25.

**Comment by juliantai** [comment]
I get the same result as well, all the tiles come in. In addition I'm seeing this in the console. 

```blob:http://localhost:3000/50f330f0-ea4a-491d-9f0a-00382fe2b964:8233 Too many symbols being rendered in a tile. See https://github.com/mapbox/mapbox-gl-js/issues/2907
exports.warnOnce @ blob:http://localhost:3000/50f330f0-ea4a-491d-9f0a-00382fe2b964:8233
```

This is what happens to me when I zoom to 25.
![screen shot 2017-01-31 at 10 30 45 am](https://cloud.githubusercontent.com/assets/790478/22478810/4f2d270a-e7a0-11e6-9cc0-a1b6e4d3d98e.png)

**Comment by deanm** [comment]
I believe at least this code will be a a problem for zoom above 24 (even for much lower zoom levels if there is a `w` coordinate):

https://github.com/mapbox/mapbox-gl-js/blob/fea5d5fbd8c810eb7df7695b0068e0891640db54/src/source/tile_coord.js#L36

See related: https://github.com/mapbox/geojson-vt/issues/87

**Comment by rbrundritt** [comment]
JavaScript mercator maps that use the quadkey tiling system; mapbox, google maps, bing maps... will only be able to zoom in to level 24 as at level 25 the tile system calculations result in very large numbers which result in floating point error in JavaScript. Even with native code you can only get one more zoom level at best before the same limitation occurs there as well.

**Comment by asheemmamoowala** [comment]
Closing this ticket here since the reported issue seems to have been resolved in https://github.com/mapbox/mapbox-gl-js/issues/4067#issuecomment-276319797
> it is now working correctly. 


As mentioned in https://github.com/mapbox/mapbox-gl-js/issues/4067#issuecomment-396023383, zoom levels above 25 are problematic with the tiling scheme used here. We do not plan to change this.
