### ISSUE TITLE
Buggy label behavior for items on vector tiles when zooming

### ISSUE THREAD

**Issue by safreiberg** [mapbox/mapbox-gl-js#4071]
Version: 

Our application computes mapbox vector tiles and serves them to the frontend. The total number of features in the full tileset is around 200k, but when zoomed into a single feature on the map, we're seeing odd label rendering behavior.
Notes:
* A geojson representation of the same feature does not exhibit the same behavior.
* It _seems_ to get into a bad state while zooming in - if the page is refreshed at a high zoom level, there is no duplicate labeling until zooming out first.

![buggy-label-behavior-zooming-in](https://cloud.githubusercontent.com/assets/1328412/22495353/785f9ece-e7f4-11e6-9b62-7cedf5d33b16.gif)

If it would be useful, we would be happy to provide a copy of the offending mvt file.

**Comment by jfirebaugh** [comment]
Can you please set up a minimal standalone example that demonstrates the issue?

**Comment by jfirebaugh** [comment]
Closing -- @safreiberg if you're able to set up a demo please feel free to reopen.
