### ISSUE TITLE
Field with name "id" doesn't show up in queryRenderedFeatures

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox-gl-js#4072]
How come my `id` field in MVT tile doesn’t show up in feature properties when doing `queryRenderedFeatures` in Mapbox GL JS? Is it a *reserved* property or smth? Renaming to `feature_id` works, but I’d like to know the truth:nerd_face:

**Comment by mourner** [comment]
Can you submit a PR with a test case that demonstrates the bug? That will make fixing it much easier.

**Comment by nextstopsun** [comment]
I've double checked my MVTs and looks like it's a bug with protobuf message generation on a server side. Sorry for reporting.
