### ISSUE TITLE
Clustering on MultiPoint geometries

### ISSUE THREAD

**Issue by karlguillotte** [mapbox/mapbox-gl-js#4076]
**mapbox-gl-js version**: 0.32.1

### Steps to Trigger Behavior

 1. Create a source with one feature with a geometry of type MultiPoint and enable clustering on that source
 2. Create a layer that references the source created at previous step
 3. Add previously created source and layer to map and display map

### Expected Behavior

I would expect the clusters to be created from all points from the MultiPoint geometry. 

### Actual Behavior

No clusters is created. 

Perhaps it is by design, I would like to get your input if it should create or not clusters for the use-case. 

Thanks for MapBox GL !

**Comment by anandthakker** [comment]
Point clustering currently requires `Point` features (see https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-geojson-cluster)

cc @mourner

**Comment by mourner** [comment]
Yeah, this is by design, but perhaps we could improve our handling of MultiPoint geometries by splitting them into individual points (copying over properties to each one) on the supercluster side.

**Comment by karlguillotte** [comment]
Thanks for your input @mourner and @anandthakker! That is already what I am doing using http://turfjs.org/docs/#explode and it is working pretty well.

**Comment by mourner** [comment]
Let's keep this conversion to features explicit on the user's side.

**Comment by enersis-pst** [comment]
had the case where i could need this feature ;-)
