### ISSUE TITLE
Make "icon-offset" units be pixels

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4078]
_From @ansis on July 8, 2014 23:26_

from #83 

> The only thing that may cause confusion is that text-offset is in ems, while icon-offset is in pixels. But maybe that's not important.

The current units for icon-offset aren't even exactly pixels. If the icon gets scaled with icon-size then the offset also gets scaled. An icon with `"icon-offset": 6` and `"icon-size": 0.5` actually has an offset of 3 pixels.

For now the units need to be relative to the unscaled size, not absolute values, but maybe we should changes the units of icon-offset to a fraction of the original size.

_Copied from original issue: mapbox/mapbox-gl-style-spec#84_

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
