### ISSUE TITLE
Make property names use nouns rather than verbs (for example "rotate" ⇢ "rotation")

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4082]
_From @jfirebaugh on October 30, 2014 18:32_

Rationale:
- Properties use nouns wherever possible, not verbs.
- Match *-rotation-alignment.

_Copied from original issue: mapbox/mapbox-gl-style-spec#201_

**Comment by lucaswoj** [comment]
_From @peterqliu on October 30, 2014 18:36_

Feels unwieldy but agree. Do same with `translate`?

**Comment by lucaswoj** [comment]
_From @ajashton on October 30, 2014 19:46_

There is also a `justify` -> `justification`

**Comment by lucaswoj** [comment]
_From @tmcw on December 23, 2016 19:26_

Another benefit to this change is that it'd reduce the [difference between the iOS SDK's reinterpretation of properties](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/darwin/scripts/style-spec-cocoa-conventions-v8.json) and the style spec / gl-js's interface to them. It's a breaking change, which is a bummer, but I think it's worthwhile on a fixing-the-system level and also makes good sense.

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
