### ISSUE TITLE
Drop prefixes in property names

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4083]
_From @peterqliu on November 17, 2014 21:9_

![screen shot 2014-11-17 at 12 29 46 pm](https://cloud.githubusercontent.com/assets/4551508/5077130/794b9e5c-6e55-11e4-94b4-60300eb108d0.png)

Namely, `fill-`,`line-`,`raster-`,`background-`

These prefixes automatically take after the layer's `type`, and as long as they live on separate layers, are redundant. The other prefixes `icon-` and `text-` are necessary, since they can cohabit the same `symbol` layer.

_Copied from original issue: mapbox/mapbox-gl-style-spec#218_

**Comment by lucaswoj** [comment]
_From @jfirebaugh on November 20, 2014 1:31_

Given that we need the prefix for symbol properties, and we might want to use them for a combination stroked and filled "polygon" type layer as well, I think we should keep them universal.

**Comment by lucaswoj** [comment]
_From @jfirebaugh on January 30, 2015 19:44_

Keeping these for now.

**Comment by lucaswoj** [comment]
_From @1ec5 on December 21, 2016 22:59_

Dropping the redundant prefixes would be highly desirable for the iOS and macOS SDKs, where property names are expected to be grammatical: https://github.com/mapbox/mapbox-gl-native/issues/6577#issue-180968544. As of mapbox/mapbox-gl-native#7457, we have to twist the English language in weird ways to ensure that Boolean property names in particular use the right parts of speech.

**Comment by 1ec5** [comment]
More motivation for dropping prefixes on iOS and macOS: https://swift.org/documentation/api-design-guidelines/#omit-needless-words

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
