### ISSUE TITLE
Rename "background" to "cover" or "fill"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4084]
_From @edenh on November 19, 2014 22:23_

Background is misleading because you can have many of them and they don't have to be "in the back". Let's rename to "cover".

_Copied from original issue: mapbox/mapbox-gl-style-spec#219_

**Comment by lucaswoj** [comment]
_From @yhahn on November 20, 2014 4:29_

Note: similar concept in Photoshop is called a **Fill layer** (http://www.dummies.com/how-to/content/how-to-use-fill-layers-in-photoshop-cs6.html)

**Comment by lucaswoj** [comment]
_From @mourner on January 22, 2015 0:36_

Is there an actual use case for many backgrounds or putting background in a different place? Cover doesn't sounds very intuitive to me... I'd rather throw an error if there are several backgrounds or if it's not in the back, and keep "background" name.

**Comment by lucaswoj** [comment]
_From @edenh on January 22, 2015 0:39_

Multiple background layers is useful. For example, a background layer with a transparent `background-image` with another solid color background layer underneath. Also, it is useful whenever you want to "tint" the entire map or a portion by applying a semi-transparent background layer higher up in the stack.

**Comment by lucaswoj** [comment]
_From @nickidlugash on January 22, 2015 0:53_

I would be amenable to "Fill" layer if we weren't already using this layer name for something else...perhaps regardless of whether we implement polygon fills and lines in one layer (https://github.com/mapbox/mapbox-gl-style-spec/issues/223), we can still rename the current "fill" layer to "polygon" layer and rename "background" to "fill"? Too confusing?

**Comment by lucaswoj** [comment]
_From @edenh on January 22, 2015 0:57_

I tend to think of background layers in terms of the css property: [`background-size: "cover"`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size).

**Comment by lucaswoj** [comment]
_From @ljbade on January 22, 2015 7:9_

What happens in the last background layer is transparent? I guess the glClearColor comes through?

**Comment by lucaswoj** [comment]
_From @jfirebaugh on January 22, 2015 21:44_

I was thinking along the same lines as @nickidlugash. This doesn't unlock any new capabilities, so let's pause on it until we see where #223 ends up.

**Comment by lucaswoj** [comment]
_From @jfirebaugh on September 30, 2016 23:21_

We should do this for v9, and then reintroduce `background` as a style-wide global property. Meanwhile `cover` layers should require a source, and only render on loaded tiles.

That enables https://github.com/mapbox/mapbox-gl-js/issues/3280 / https://github.com/mapbox/mapbox-gl-native/issues/119.

**Comment by lucaswoj** [comment]
_From @kkaefer on October 4, 2016 8:18_

Why should they require a source?

**Comment by lucaswoj** [comment]
_From @jfirebaugh on October 4, 2016 16:4_

So that you can have two different "backgrounds":
- A base color or [grid](https://github.com/mapbox/mapbox-gl-js/issues/3280) that shows up behind unloaded tiles
- A "land" background that shows up on loaded tiles where there are no other features

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
