### ISSUE TITLE
Document glyphs 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4097]
_From @jfirebaugh on September 22, 2015 1:56_

This ticket is the `glyphs` equivalent of #315. See https://www.mapbox.com/mapbox-gl-style-spec/#sprite for how we document sprites.

Relevant questions to answer:
- What's the glyph pbf format?
- What's the algorithm for filling in the `{range}` template parameter?
- What's the algorithm for filling in the `{fontstack}` template parameter?

The answers to these question implicitly define what a glyphs API server needs to be capable of.

_Copied from original issue: mapbox/mapbox-gl-style-spec#361_

**Comment by lucaswoj** [comment]
_From @gertcuykens on July 12, 2016 21:29_

Can this get a slightly higher priority? I assume many users have no clew including me what range and fontstack means https://www.mapbox.com/mapbox-gl-style-spec/#glyphs Also I can't find any correlation with https://www.mapbox.com/mapbox-gl-style-spec/#layout-symbol-text-font to figure out what fonts I can use?

**Comment by 1ec5** [comment]
The iOS and macOS SDKs [have documented](https://github.com/mapbox/mapbox-gl-native/blob/4867db5168a11d641c27d95b2d8c242d04ece114/platform/darwin/scripts/style-spec-overrides-v8.json#L34) the `text-font` property with some basic information about how to set a custom font, but better guidance about `glyphs` specifically would be welcome.
