### ISSUE TITLE
Style formatter should remove properties set to default value

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4098]
_From @bhousel on October 12, 2015 18:14_

I see a lot of unnecessary stuff like `"visibility": "visible"`, `"text-halo-blur": 0`, etc. in both the reference styles and the ones exported from Studio.  

The style formatter really could remove properties that are set to the default value.

_Copied from original issue: mapbox/mapbox-gl-style-spec#368_

**Comment by mourner** [comment]
As far as I know, this was done a while ago on the Studio side so I think we can close.
