### ISSUE TITLE
Make "circle-blur" units be pixels

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4099]
_From @mcwhittemore on November 12, 2015 17:8_

@anandthakker raised a question today about if it is safe for circle blur to be greater than one. [The spec is a bit unclear here](https://github.com/mapbox/mapbox-gl-style-spec/blob/5a8c084a81de5bf7497952ba79dda9a83d4966ee/reference/v8.json#L1036) as it only explains what the effect of 1 should be, leaving both < 1 and > 1 to be unclear.

> Optional number.  Defaults to 0.
> Amount to blur the circle. 1 blurs the circle such that only the centerpoint is full opacity.

Looking into mapbox-gl-js circle-blur doesn't seem to be getting windowed which leads me to assume it is ok if it is greater than one. Is this right? 

Either way we should update the spec to clear this kind of question up. The other blur's are in pixels, rather than an alpha channel.

_Copied from original issue: mapbox/mapbox-gl-style-spec#378_

**Comment by lucaswoj** [comment]
_From @mcwhittemore on December 2, 2015 15:31_

@jfirebaugh any thoughts on this? Seems like < 0 shouldn't be allowed but greater than one should be. If 1 is the center point at full opacity than is 2 the center point at half opacity?

**Comment by lucaswoj** [comment]
_From @jfirebaugh on December 2, 2015 15:47_

I'm not familiar with `circle-blur`. @tmcw or @ansis might know.

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
