### ISSUE TITLE
Decrease default value for "symbol-min-distance"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4101]
_From @ansis on February 11, 2015 23:13_

Line label density improved with https://github.com/mapbox/mapbox-gl-js/pull/989 but density could be increased further by having a smaller default `symbol-min-distance` value. The current default is 250 pixels.

What would be a better default value? or is 250 fine?

@nickidlugash @edenh @peterqliu 

_Copied from original issue: mapbox/mapbox-gl-style-spec#245_

**Comment by lucaswoj** [comment]
_From @mourner on February 11, 2015 23:30_

We could also make it a function of zoom now.

**Comment by lucaswoj** [comment]
_From @ansis on February 11, 2015 23:37_

or the units for the property could be em instead of pixels

**Comment by lucaswoj** [comment]
_From @nickidlugash on February 12, 2015 2:2_

I think `symbol-min-distance` is more correlated to zoom level than to text size, so a function might work, although keeping it a literal number might be the most user-friendly, since either way I think users are going to have to adjust this value relatively frequently. 

Here's what seem to be pretty good values for a few Streets layers (at least for Outdoors style):
- road_label: 

```
{
  "base": 0.6,
  "stops": [[12, 50], [18, 250]]
}
```
- contour_label:

```
{
  "base": 0.6,
  "stops": [[11, 150], [18, 250]]
}
```
- marine_label:

```
{
  "base": 0.6,
  "stops": [[2, 50], [6, 250]]
}
```

^ The optimal value for marine labels are quite different than roads/contours because of the zoom levels that they're visible at. My instinct is to optimize the default value for labels similar to road labels – aka mid-to-long labels at mid-to-high zoom levels.  

@peterqliu @edenh have you guys had a chance to play around with label density for other data layers?

**Comment by mourner** [comment]
According to https://github.com/mapbox/mapbox-gl-style-spec/issues/245#issuecomment-74004625, `250` seems like a good default (at least for higher zoom levels), and not using a zoom expression instead makes it more user-friendly. Let's close this for now because there are no actionable alternative suggestions.
