### ISSUE TITLE
Rename "symbol-avoid-edges" to "symbol-allow-edge-overlap"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4105]
_From @lucaswoj on January 27, 2016 22:53_

- is more consistent with the naming of `icon-allow-overlap` and `symbol-allow-overlap`
- prevents users from having to think in double negatives

_Copied from original issue: mapbox/mapbox-gl-style-spec#404_

**Comment by lucaswoj** [comment]
related to https://github.com/mapbox/mapbox-gl-style-spec/issues/201

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
