### ISSUE TITLE
Prevent step and interpolate expressions from having duplicate stops

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4107]
_From @scothis on February 5, 2016 22:51_

Restore https://github.com/mapbox/mapbox-gl-style-spec/pull/397 with a migration for existing ramps similar to https://github.com/mapbox/mapbox-gl-style-spec/pull/411 for v9.

This behavior was merge in v8 and removed because it was backwards incompatible. The idea is sound and should be part of v9

_Copied from original issue: mapbox/mapbox-gl-style-spec#414_

**Comment by jfirebaugh** [comment]
We did this for expressions; for functions, we're more likely to just drop support for them entirely than make any other breaking change to them.

**Comment by jfirebaugh** [comment]
We didn't actually do this for expressions, but we should.
