### ISSUE TITLE
Add expression operator testing whether a string contains a substring

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4113]
_From @vicapow on April 5, 2016 22:46_

This would be useful for showing query results as the user types.

_Copied from original issue: mapbox/mapbox-gl-style-spec#438_

**Comment by lucaswoj** [comment]
Closely related to #233

**Comment by 1ec5** [comment]
Now that expressions have landed and can be used as filters, this is actually a request to add an expression function. Specifically, there should be a function that tests whether a string contains another string. By analogy, the most likely syntax would be `["match", needleString, haystackString]`. However, the word “match” is more closely associated with wildcards and regular expressions, which are covered by #4089.

**Comment by arethasamuel** [comment]
Hi When will this feature be ready? autocomplete search is one of our main use cases, is there an alternative way of doing a "contains" search?

**Comment by andrewharvey** [comment]
@arethasamuel if your data isn't too big you could keep an external list of the query properties from your features and filter based on the full list of names which match the user input.

**Comment by anandthakker** [comment]
@arethasamuel the best place to track this at the moment is via the discussion about regexp expressions happening at https://github.com/mapbox/mapbox-gl-js/pull/6228.  As you can see from that conversation, we're still hashing out the right API design, so there's no concrete timeline for when this functionality will be available.

**Comment by pshavr** [comment]
so
when substr?)

**Comment by dwohlfahrt** [comment]
I'll second @pshavr 's request for a substring function and associated expression syntax!

**Comment by 1ec5** [comment]
A substring test expression would make it easy to implement [these road maps color-coded by street name suffix](https://erdavis.com/2019/07/27/the-beautiful-hidden-logic-of-cities/) in GL.

**Comment by ryanhamley** [comment]
>A substring test expression would make it easy to implement these road maps color-coded by street name suffix in GL.

Here's an example of the color-coded road maps mentioned by @1ec5 
https://jsfiddle.net/rsh412/Ldn39w0x/4/
