### ISSUE TITLE
GL Style JSON fails PATCH validation

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4114]
_From @cmtoomey on April 6, 2016 14:19_

In testing PATCH requests against GL Styles, the Style JSON provided by GET
/styles/v1/{username}/{style_id} is not valid for PATCH requests made via PATCH
/styles/v1/{username}/{style_id}.

Actual request (with body) can be found [here](https://gist.github.com/cmtoomey/73aff4b3eabaa9c5debc229d6560b53a)

HTTP Response code is 422 Unprocessable Entity

**Postman output below**

![image](https://cloud.githubusercontent.com/assets/12201602/14319713/1414240e-fbc7-11e5-80ec-385dc9d2b7cd.png)

If "created" is deleted, the PATCH request fails again due to "modified"

![image](https://cloud.githubusercontent.com/assets/12201602/14319767/53d4a758-fbc7-11e5-9fab-85ec2b5fe269.png)

Deleting "modified" allows the request to go through

![image](https://cloud.githubusercontent.com/assets/12201602/14319824/8ba184ee-fbc7-11e5-8271-cf458c021a50.png)

---

Two requests for fix:
1. Remove "created" and "modified" from GET request output (hard to trace, so not preferred)
2. Update JSON validation for Style API PATCH to accept those JSON key/value pairs.

_Copied from original issue: mapbox/mapbox-gl-style-spec#439_

**Comment by lucaswoj** [comment]
_From @tmcw on April 6, 2016 15:3_

This is fully covered by API documentation, so the behavior should not come as a surprise: https://www.mapbox.com/api-documentation/#update-a-style

> Requesting a style and then using the same content to update the style will fail: you'll need to remove the created and modified properties before updating a style. The name property, which is optional for style creation, is required when updating a style. Cross-version PATCH requests are rejected.

**Comment by lucaswoj** [comment]
_From @cmtoomey on April 6, 2016 16:13_

That's fair - but I'm curious as to the existence of the behavior in the first place. Based on the [style-reference](https://www.mapbox.com/mapbox-gl-style-spec/#), created and modified aren't actually part of the spec - which is logical given the documentation and expected behavior.

However, the initial interaction with the Style JSON returns something that is off-spec. I get that parsing and deleting lines isn't a massive technical undertaking; but if we accept that creation and modification dates are useful properties (else they wouldn't  be provided), wouldn't it be easier to simply adopt them into the spec?

**Comment by lucaswoj** [comment]
This has been addressed with the `metadata` property

**Comment by lucaswoj** [comment]
_From @jfirebaugh on December 22, 2016 18:8_

I think this is still valid -- the Style API doesn't actually use `metadata` for these properties, due to historical timing. We could decrease the API friction and eliminate the documentation caveat by adding them to the style spec, so that the Style API response validates.

**Comment by samanpwbb** [comment]
Closing, this is really a Mapbox style API issue. We are tracking it internally.
