### ISSUE TITLE
Add "raster-sharpen" property

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4121]
_From @tristen on July 26, 2016 17:46_

Particularly for satellite imagery and areas where coverage is supported at lower zoom levels it would be nice to adjust sharpening.

_Copied from original issue: mapbox/mapbox-gl-style-spec#473_

**Comment by ansis** [comment]
Closing this since there doesn't seem to be much demand for this and it's because it's probably better handled on the raster creation side.
