### ISSUE TITLE
Add "line-dasharray-origin" property

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4126]
_From @samanpwbb on September 2, 2016 16:28_

It's common in vector editing tools to offset the origin point in a dasharray. Here's an example in inkscape:

![screen shot 2016-09-02 at 12 27 19 pm](https://cloud.githubusercontent.com/assets/108094/18210875/a824f126-7108-11e6-9948-36991aa27dd6.png)

Changing that value offsets the whole array. 

This property would be really useful when animating dasharrays. For example, a function like this would rotate the lines in the dasharray continuously:

``` js
  var origin = 0;
  setInterval(function() {
    map.setPaintProperty('layerid', 'dasharray-origin', origin);
    origin = origin + 1;
  }, 300);
```

_Copied from original issue: mapbox/mapbox-gl-style-spec#489_

**Comment by ansis** [comment]
Since lines are clipped to tiles the current initial offset for dashed lines isn't 0. It's random. Adding a specified offset to a random offset will still be random.

In order to make this useful we'd need to also store the length of the part of the line that was clipped off.

**Comment by samanpwbb** [comment]
I think this is a pretty low-priority request. Feel free to close if it doesn't seem worth the effort.

**Comment by ansis** [comment]
Yep, closing.
