### ISSUE TITLE
Links to special types are broken

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4133]
_From @1ec5 on October 19, 2016 7:51_

The [`sources`](https://www.mapbox.com/mapbox-gl-js/style-spec/#root-sources) property’s link to the “sources” type is broken; it should point to [this section](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources) with the anchor `#sources` rather than `#type-sources`. A similar issue affects links to the [`transition`](https://www.mapbox.com/mapbox-gl-js/style-spec/#transition) type and also the `light` type once #542 lands. (In any case, the `sources` root property should actually have `"type": "array", "value": "sources"` rather than `"type": "sources"`.)

/cc @lbud

_Copied from original issue: mapbox/mapbox-gl-style-spec#543_

**Comment by asantos3026** [comment]
Hey @lucaswoj, I'm looking in to this issue. Can you give me some info on where the route params would be in the code base?

**Comment by 1ec5** [comment]
[This line](https://github.com/mapbox/mapbox-gl-js/blob/daea8110d97d74332915d15fa35e901d826c78d7/docs/style-spec/_generate/item.html#L11) generates the broken link. Note that links to value types like “color”, “enum”, and “string” are not broken; only links to special types like “source” and “light” are affected.

**Comment by asantos3026** [comment]
@1ec5 Where is this html receiving its props from?

**Comment by 1ec5** [comment]
It comes from the style specification’s JSON file, particularly [this line](https://github.com/mapbox/mapbox-gl-js/blob/daea8110d97d74332915d15fa35e901d826c78d7/src/style-spec/reference/v8.json#L57). (Note that the documentation isn’t the only tool that uses this file; various tools in src/style-spec/ and also the mapbox-gl-native project also rely on this file.)
