### ISSUE TITLE
Fix language drift and connect "property functions" to data-driven styles

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4139]
_From @tmcw on November 8, 2016 16:52_

Via a support question this morning:

> Can I get a list of which layout/paint properties are supported for use with Property Functions... The documentation just says it is not fully supported and I can't easily tell from the code. 

Right now we have, under Property Functions:

> Note that support for property functions is not available across all properties and platforms at this time.

But then in the per-property spec

![2016-11-08 at 11 51 am](https://cloud.githubusercontent.com/assets/32314/20108334/b64884f4-a5a9-11e6-892c-1165b3020718.png)

We need to connect these things by

1. Explicitly telling people how to check if a thing is supported
2. _OR_ Using the same words to describe "property functions" and "data driven styles"

_Copied from original issue: mapbox/mapbox-gl-style-spec#567_

**Comment by lucaswoj** [comment]
_From @jfirebaugh on November 8, 2016 18:10_

"data-driven styles" / "data-driven styling" is an umbrella term. "property functions" are one type of data-driven function. "zoom-and-property functions" is another. (Arguably, the interpolation syntax supported by `text-field` and `icon-image` are a third.)

The documentation should refer to support for "data-driven styling", not about support for "property functions" specifically. We're not going to create any properties that support property functions but not zoom-and-property functions, and most people looking for DDS support information don't care about the difference between those two types of functions.

**Comment by lucaswoj** [comment]
_From @tmcw on November 8, 2016 18:31_

@jfirebaugh I see your objection but am not seeing a proposal to clarify the documentation.

To restate the problem without potentially incorrect wording:
- Right now we have some text that says "support for this feature varies across the API."
- This leads the user to ask "how does it vary? Where can I use the feature?"

If we say that support for "property functions" varies but we don't say "property function" anywhere in the particular property documentation, we're inviting the reader to ask a question and not providing the answer. I am amenable to any solution that fixes this problem.

**Comment by lucaswoj** [comment]
_From @jfirebaugh on November 8, 2016 20:29_

Concretely, I suggest fixing #529 and then replacing "Note that support for property functions is not available across all properties and platforms at this time." with the following:

> Support for property functions and zoom-and-property functions -- commonly known as "data-driven styling" -- varies by style property and SDK. Refer to the "data-driven styling" row in the SDK Support matrix for the property you're interested in.

**Comment by lucaswoj** [comment]
_From @stevage on January 4, 2017 6:35_

Thanks very much for addressing this issue. I've been bitten a few times.

Things that happen to me:

- at some point in my googling, I end up on the [Mapbox GL data-driven style reference](https://www.mapbox.com/help/gl-dds-ref/) but then later I'm looking in the Style Spec, and confused why I can't find the bit I remember from the style reference. Should there be some links from the style spec to the help page? Or some better organisation between them?
- other times I end up on [this blog post](https://www.mapbox.com/blog/data-driven-styling/), which maybe should have a banner on it now linking to the most up to date information
- I see this sentence under "Function": "The value for any layout or paint property may be specified as a function", and take it literally (*any* property), and don't see the caveats paragraphs later.
- I go looking for the "data-driven styling" section of the Style Spec and...there isn't one. There's nothing in the chapter headings on the left hand side (it's actually under "Function", but that's not obvious).

Also...tiny unrelated issue: Function "type" and Function "colorSpace" don't mention what their defaults are.

**Comment by jfirebaugh** [comment]
We have the following prose:

> Data expressions are allowed as the value of the `filter` property, and as values for most paint and layout properties. However, some paint and layout properties do not yet support data expressions. The level of support is indicated by the "data-driven styling" row of the "SDK Support" table for each property.

So at this point, I think we can globally replace "data-driven styling" with "data expressions" on https://www.mapbox.com/mapbox-gl-js/style-spec/ and call this fixed.

**Comment by SnailBones** [comment]
>     * other times I end up on [this blog post](https://www.mapbox.com/blog/data-driven-styling/), which maybe should have a banner on it now linking to the most up to date information
Created an internal issue [here](https://github.com/mapbox/www-design-service/issues/977).

**Comment by SnailBones** [comment]
From @asheemmamoowala on my [pull request](https://github.com/mapbox/mapbox-gl-js/pull/10839#pullrequestreview-705500246).

> @SnailBones The format of the style-specification is a public contract, and downstream users may depend on the `data-driven styling` text, so this may turn out to be a breaking change.
> 
> The term `data-driven styling` refers to both data and camera based styling. Replacing it with `data expressions` it makes this slightly harder to parse, but that could be resolved by adding an alternate notation to denote a property's type and the expressions it supports - that information is available in the style spec under the `expressions` and `property-type` keys.

My understanding is that some properties could support camera or zoom based expressions but not data expressions, hence the need for additional specificity. If I'm wrong about this, perhaps the field should just be 'expressions?'

Current documentation seems to predominantly use 'expressions' and rarely refers to 'data-driven styling' e.g. [style spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/) and [tutorial](https://docs.mapbox.com/help/tutorials/mapbox-gl-js-expressions/). So I'm currently in tentative agreement with @jfirebaugh that the name change improves clarity.

On the other hand, if this is a breaking change with minimum user benefit, maybe best to keep things as is and close the issue?

**Comment by SnailBones** [comment]
Breaking change could be included in a future style spec version. Closing here. See #6584.
