### ISSUE TITLE
Disallow relative URLs in styles

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4141]
_From @lucaswoj on November 17, 2016 1:43_

see https://github.com/mapbox/mapbox-gl-js/issues/3636 for more context 

_Copied from original issue: mapbox/mapbox-gl-style-spec#575_

**Comment by andrewharvey** [comment]
Given @jfirebaugh 's comments at https://github.com/mapbox/mapbox-gl-js/issues/3636#issuecomment-261119004

> I don't think it's something we should support.
> 
> - There's ambiguity about what the URL should be relative to. Should it be the style URL or the page URL?
> - If it's the style URL, then it needs explicit code and acts differently than relative URLs elsewhere in Web APIs.
> - If it's the page URL, then it's a style spec feature that can never be replicated in gl-native.
>
> Use cases where relative URLs are desired can be satisfied by preprocessing the style to produce the desired absolute URL.

I agree relative URLs are probably better not supported.

If you can't or don't want to serve absolute URLs inside the style.json, then the [Map `options.transformRequest`](https://www.mapbox.com/mapbox-gl-js/api#map) provides a way for you to change relative URLs into absolute ones at runtime, potentially using `window.location.origin`.

**Comment by mollymerp** [comment]
@michaelmcmillan transform request should work for requesting all assets from the style. If you find an issue with that feature please open a bug report. 

We are unlikely to implement this in the near future for the reasons mentioned above so I am going to close this issue. We will reopen if that changes.
