### ISSUE TITLE
Use words instead of symbols

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4145]
_From @jfirebaugh on November 28, 2016 19:44_

Replace ![image](https://cloud.githubusercontent.com/assets/98601/20683177/d3f5ea44-b55f-11e6-8153-d88128b80f37.png) and ![image](https://cloud.githubusercontent.com/assets/98601/20683188/dc589cea-b55f-11e6-883b-0d55346e81ed.png) with words ("continuous" and "discrete"?).

You can't search for symbols to see what properties use which type, and the meaning isn't clear from the symbol.

_Copied from original issue: mapbox/mapbox-gl-style-spec#584_

**Comment by lucaswoj** [comment]
_From @davidtheclark on December 1, 2016 22:1_

Why introduce "continuous" and "discrete" into the mix when there's already "interpolated" and "piecewise-constant"? My head is being tied into knots by the number of "function types" 
༼ ºººººل͟ººººº ༽

**Comment by lucaswoj** [comment]
_From @jfirebaugh on December 1, 2016 22:14_

Yeah, when I wrote that I forgot that we already had the terms "interpolated" and "piecewise-constant". We should be consistent and use one set or the other everywhere.

I have a proposal brewing to rationalize the current set of function types into something more understandable. Stay tuned.

**Comment by stevage** [comment]
Hmm, I actually like the symbols. My brain finds it a bit easier to see a symbol like the steps and get what it means (it's super intuitive, even if it would be hard to put into words) without having to deal with a phrase like "piecewise-constant". Maybe words plus symbol?
