### ISSUE TITLE
Expand SDK Support matrix for functions

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4148]
_From @jfirebaugh on November 28, 2016 19:34_

The SDK Support matrix should include rows for:

* `property` property
* `type` property
* `exponential`, `interval` and `categorical` types

_Copied from original issue: mapbox/mapbox-gl-style-spec#583_

**Comment by jfirebaugh** [comment]
Done in 8b99ace24f7083aa49dbf0dbc87389662ac61e3f.
