### ISSUE TITLE
Are "identity" zoom functions allowed?

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4151]
_From @jfirebaugh on November 30, 2016 2:7_

```
    {
      "id": "fill",
      "type": "fill",
      "source": "source",
      "source-layer": "layer",
      "paint": {
        "fill-opacity": {
          "type": "identity"
        }
      }
    }
```

Is this allowed?

_Copied from original issue: mapbox/mapbox-gl-style-spec#603_

**Comment by lucaswoj** [comment]
I can't think of a reason why we shouldn't allow this unless it adds implementation complexity.

**Comment by lucaswoj** [comment]
_From @jfirebaugh on November 30, 2016 19:13_

It will add four additional rows to #604, which translates to implementation complexity for gl-native.

**Comment by jplante** [comment]
Unless there is another way to handle circle-radius as a distance, we would like this feature:

For example - ALA Leaflet's Circle and CircleMarker - where the radius is based on either distance or pixels - we could use this for setting different radius for a Circle based on data identity attributes

**Comment by jplante** [comment]
According to this, there is no other way to handle circle-radius as a distance:
https://github.com/mapbox/mapbox-gl-js/issues/2525
