### ISSUE TITLE
Add "circle-stroke-dasharray" property

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4153]
_From @lucaswoj on November 30, 2016 18:38_

ref https://github.com/mapbox/mapbox-gl-style-spec/issues/379#issuecomment-263704489

_Copied from original issue: mapbox/mapbox-gl-style-spec#607_

**Comment by mourner** [comment]
Looks like there's no interest in implementing `circle-stroke-dasharray` because it's too rare of a use case for the required implementation effort. Should we close?

**Comment by mourner** [comment]
Closing for now, will reopen if there's enough interest in this.

**Comment by ericjames** [comment]
I have interest in this!

**Comment by wafisher** [comment]
I would like this, as well. There's no real workaround (that I know) since even dynamically generating a line layer will be fixed to the geography, whereas a circle remains a certain pixel width no matter the zoom.

**Comment by amelielecoz** [comment]
I would need this feature as well !

**Comment by azteckind** [comment]
I'm interested in being able to use this feature. I'm currently working on a project where my team and I would like to be able to create circles with dashes on a map.

I don't suppose anyone knows a relatively simple work around for a group of novice coders to use?

**Comment by wwclement** [comment]
Has  this ever been implemented?  Implementing designs with concentric walking circles is perfect use case, with a label that wraps around just inside or outside.  Thanks

**Comment by ananmaysharan** [comment]
I have interest in this feature.
