### ISSUE TITLE
Rename "text-halo" to "text-stroke"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4161]
_From @lucaswoj on December 23, 2016 14:36_

See the discussion here: https://github.com/mapbox/mapbox-gl-style-spec/issues/379

_Copied from original issue: mapbox/mapbox-gl-style-spec#636_

**Comment by lucaswoj** [comment]
_From @ajashton on January 2, 2017 19:16_

The functionality of the current `text-halo` is much closer to CSS's `text-shadow` than `text-stroke`. The halo is only ever outset from the symbol, whereas a stroke is centered directly on the outline of the symbol. The halo can be blurred while strokes cannot. Strokes can have various dasharrays, round/bevel/miter joins, and offsets but halos cannot.

Going with 'stroke' for the circle symbol as discussed in #379 seems reasonable, but I think the situation for text is quite different and it might not be worth conflating the two, unless the plan is to bring halo and stroke features more in line with each other?

**Comment by lucaswoj** [comment]
_From @nickidlugash on January 3, 2017 1:42_

Agree with @ajashton on all the above points. 

> The functionality of the current text-halo is much closer to CSS's text-shadow than text-stroke.

And using a Photoshop analogy, the current `text-halo` is much closer to the outer-glow blend mode than the stroke blend mode.

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
