### ISSUE TITLE
Camelcase all keys

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4163]
_From @lucaswoj on December 23, 2016 14:41_

Working with Mapbox style spec objects in Javascript is less ergonomic because all the dashcase properties must be quoted when they are used as identifiers. 

```js
var layer = { 'line-color': 'blue' }
layer['line-color']

vs

var layer = { lineColor: 'blue' }
layer.lineColor
```

They look odd in conjunction with the camelcased source properties #175 

_Copied from original issue: mapbox/mapbox-gl-style-spec#638_

**Comment by lucaswoj** [comment]
_From @tmcw on December 23, 2016 14:58_

Oof, that is one breaking change, but I support it 100%. We used dashes in CartoCSS too, from the CSS lineage, and in simplestyle-spec, and they're just inconvenient for no reason. This would also bring property names closer to what @1ec5 wants on the native side.

**Comment by lucaswoj** [comment]
_From @1ec5 on December 23, 2016 18:5_

I have no opinion either way. Camel case is always applied systematically, so it poses no barrier to people developing against our Android, iOS, or macOS SDKs, where we’ve exposed symbolic constants or method names instead of requiring strings to be hard-coded (as JavaScript does). Besides, the Android SDK uses [SCREAMING_SNAKE_CASE](https://www.mapbox.com/android-sdk/api/4.2.1/com/mapbox/mapboxsdk/style/layers/Property.CIRCLE_PITCH_SCALE.html) too.

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
