### ISSUE TITLE
Prohibit ["has", "$type"] and ["!has", "$type"]

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4164]
_From @jfirebaugh on January 2, 2017 18:55_

We have [a validation](https://github.com/mapbox/mapbox-gl-style-spec/blob/b87a7bb2b073cace5fb42cb6b515af4fbd1a11ca/lib/validate/validate_filter.js#L38-L38) prohibiting comparison operators with `$type`. This prohibition should extend to `has` and `!has` as well.

_Copied from original issue: mapbox/mapbox-gl-style-spec#643_

**Comment by jfirebaugh** [comment]
We're not likely to make any further changes to functions.
