### ISSUE TITLE
Rename text-field to text

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4166]
_From @1ec5 on January 5, 2017 10:58_

The `text-field` property should be renamed to simply `text`.

The name `text-field` makes it sound like the property was originally intended to identify a field in the feature’s properties object. That happens to be what this property is usually used for, but by that logic we’d have `icon-image-field` instead of `icon-image`. Given the enthusiasm for supporting more expressive values for this property in #104 and #47, the word “field” feels downright anachronistic.

The name `text-field` is also misleading when incorporated into the iOS and macOS SDKs: the developer would expect a `textField` property to hold an NSTextField or UITextField, or at least some kind of editable control, but not an NSString. There is such a thing as NSText on macOS, but no one ever uses it directly. On the other hand, `UILabel.text`, analogous to the `text-field` layout property, is one of the most commonly used properties on iOS.

/cc @lucaswoj @jfirebaugh

_Copied from original issue: mapbox/mapbox-gl-style-spec#646_

**Comment by lucaswoj** [comment]
This fits nicely with #218

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
