### ISSUE TITLE
Rename line-dasharray to line-dash-array

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4167]
_From @1ec5 on January 5, 2017 11:1_

The `line-dasharray` property should be renamed `line-dash-array`. The missing dash really bugs me, and if we were to go through with #638, `lineDasharray` would look sloppy.

/cc @lucaswoj @tmcw

_Copied from original issue: mapbox/mapbox-gl-style-spec#647_

**Comment by lucaswoj** [comment]
_From @1ec5 on January 5, 2017 11:3_

Note that the iOS and macOS SDKs call this property `lineDashPattern` [for consistency with the platform](https://developer.apple.com/search/?q=lineDashPattern&type=Reference) (and MapKit).

**Comment by lucaswoj** [comment]
_From @mourner on January 5, 2017 11:32_

AFAIR the original reason there's no dash is that SVG spec doesn't have it too, e.g. https://developer.mozilla.org/ru/docs/Web/SVG/Attribute/stroke-dasharray, and we wanted it to be consistent with existing web specs.

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
