### ISSUE TITLE
Rename text-size to text-font-size

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4168]
_From @1ec5 on January 6, 2017 22:43_

The `text-size` property should be renamed `text-font-size`. As part of #218, it would be shortened to `font-size`.

Contrary to the property’s current name, it does not specify the dimensions of the overall label the way `text-max-width` does. Instead, it specifies the font size in pixels. This inconsistency means a developer using the iOS or macOS SDK would be tempted to set the property to a `CGSize` or `NSSize` value instead of a number.

/cc @lucaswoj @jfirebaugh

_Copied from original issue: mapbox/mapbox-gl-style-spec#650_

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
