### ISSUE TITLE
Hard to see category of property in documentation

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4169]
_From @stevage on January 9, 2017 23:6_

Just a usability issue I run into a lot with the docs. Say you're looking at this property: https://www.mapbox.com/mapbox-gl-style-spec/#paint-icon-translate-anchor

You can't see whether it's a layout, paint, etc property. The only way to find that out is to scroll up, sometimes quite a long way.

It would be great if it was somehow possible to see that information on the same page as the property itself. Maybe:

- another little icon
- the text "Paint Properties" floats, so it doesn't scroll out of view
- some text or something in the left margin

_Copied from original issue: mapbox/mapbox-gl-style-spec#651_

**Comment by lucaswoj** [comment]
_From @mollymerp on January 11, 2017 21:5_

Thanks for your request @stevage - I have run into this as well. We'd be thrilled to see a PR implementing one of those options. I lean towards the second two options for clarity.

**Comment by stevage** [comment]
#4160 will actually greatly lessen the impact of this, if that goes through.

**Comment by stevage** [comment]
Hooray! :) 👍
