### ISSUE TITLE
Include 3rd party SDKs in sdk-support object?

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4170]
_From @ahocevar on January 10, 2017 15:38_

I was wondering if it would be desirable to include 3rd party SDKs like [ol-mapbox-style](https://github.com/boundlessgeo/ol-mapbox-style) in the `sdk-support` object. Something like
```json
"sdk-support": {
  "basic functionality": {
    "js": "0.10.0",
    "android": "2.0.1",
    "ios": "2.0.0",
    "macos": "0.1.0",
    "ol-mapbox-style": "1.0.0"
  }
}
```
The advantage would be an up-to-date information on supported features for those SDKs, and a way for utilities like style editors to only offer features that are supported in the target SDK.

This idea was first discussed in boundlessgeo/ol-mapbox-style#10. An alternative would be to fork the spec, but it might make sense to have this information upstream. If this is not the case, are there any other suggested ways that I might not have thought about?

_Copied from original issue: mapbox/mapbox-gl-style-spec#652_

**Comment by lucaswoj** [comment]
_From @tmcw on January 10, 2017 16:2_

I'm not opposed to this idea technically, and think it's much better than implicitly requiring you to fork the project. The chief concern is maintenance, really: with the Mapbox SDKs, we have the ability to ask our coworkers to keep the sdk-support updated, and have the leverage of being coworkers.

If we do start including 3rd party projects, I think we'd need

- An agreement that the support levels of those projects are kept up-to-date on a regular basis
- And if those projects lose maintainership, as too many open source projects do, we remove them from the spec.

**Comment by lucaswoj** [comment]
_From @ahocevar on January 10, 2017 16:26_

Thanks for your comment @tmcw. I'd be 100% supportive of the rules you suggest.

For keeping the support levels up to date, we can make update pull requests part of the release process.

If there is general agreement on such a procedure, is there anything I can help with for establishing it?

**Comment by 1ec5** [comment]
> If there is general agreement on such a procedure, is there anything I can help with for establishing it?

For the community-maintained Mapbox macOS SDK, all it took was a PR: mapbox/mapbox-gl-style-spec#641.

**Comment by ahocevar** [comment]
Cool, I'll submit a pull request too then. Thanks!

**Comment by ahocevar** [comment]
Are you still accepting a pull request for this? I had planned to work on it in the next couple of weeks.

**Comment by jfirebaugh** [comment]
Yes, we'll still accept a pull request for this @ahocevar.
