### ISSUE TITLE
easeTo goes in the wrong direction

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4178]
**mapbox-gl-js version**:0.32.1

### Steps to Trigger Behavior

 1. View https://bl.ocks.org/stevage/c80f9b241866642abdb2e6da8231cde6
 2. Wait for the second camera transition

### Expected Behavior
Camera should ease south

### Actual Behavior
Camera eases north, then miraculously reappears from the south.

It works properly with flyTo instead of easeTo.

**Comment by stevage** [comment]
Related to #3112?

**Comment by mourner** [comment]
Wow, this is interesting. Took me a while to realize what's wrong. I don't think this is related to #3112 — will investigate.

**Comment by joswinter** [comment]
The changes in pull request #3130, which hasn't been merged and is inactive seems to fix the unwanted behavior described in this issue. Because that pull request has been created to fix #3112, I think this issue is related to #3112.

**Comment by mourner** [comment]
After some investigation, I'm concluding that this is the same issue as #3112, so I'll close this one as duplicate and comment with my findings on that ticket.
