### ISSUE TITLE
Smoothly interpolate flight path across a number of points

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4180]
This might be a stretch, but thought I'd ask whether there's any way currently (or as an enhancement) to create smooth flight paths that interpolate across multiple points, like a bezier curve.

Currently, you can `flyTo` A to B to C to D, but there will be discontinuities in the velocity function at each of those points. How would you make a smooth path that goes through a number of defined points, without abruptly changing speed or direction at any point?

**Comment by mourner** [comment]
Thanks for the report! This feature is currently being tracked in #981 — let's keep the discussion centralized there. We'd love to implement this but didn't yet get around this yet — if you want to help out with a PR, please do!
