### ISSUE TITLE
Map transition goes wonky if user attempts to pan.

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4181]
**mapbox-gl-js version**: 0.32.1

### Steps to Trigger Behavior

 1. Wait for the camera to moving
 2. Click to drag the map

### Expected Behavior
Not sure. Either map stops its current transition, or the user pan is ignored.

### Actual Behavior
Map starts panning erratically in various directions, never completing its transition.

**Comment by mourner** [comment]
Hmm, can you submit a JSFiddle example that demonstrates this? I'm trying to reproduce e.g. on [this flyTo example](https://www.mapbox.com/mapbox-gl-js/example/flyto-options/), and the map stops correctly if you start panning while the animation is going.

**Comment by stevage** [comment]
Sorry, I forgot to paste the repro case. You can see it here: https://bl.ocks.org/stevage/b863ddd9364c7bf076413119215022fd

The flyTo example works fine for me too.

Ok, wait, now I see what's going on. I'm using `moveend` to start the flyto, which is also being triggered by the user pan, so the map is trying to `flyto` two different places simultaneously...and somehow causes a cascade of further `moveend` events

User error I think.

**Comment by andrewharvey** [comment]
The approach I've used is to pass some [eventData to the flyTo](https://www.mapbox.com/mapbox-gl-js/api/#Map#flyTo) and then check if that is present on the moveend to know what invoked that moveend.

**Comment by stevage** [comment]
Oh, thanks, good idea.

**Comment by stevage** [comment]
Although...that's kind of tricky, too. Seems that when a user pan happens mid-flyto, you get two `moveend` events - first the user pan, then the flyto (which I guess is halted because of the pan). So having a flyTo gracefully continue despite a user pan is a little fiddly.

**Comment by andrewharvey** [comment]
If you want a flyTo to continue despite a user pan (is that what you wanted?), it might be best to disable interactivity so they can't interact with the map via [`Map options.interactive`](https://www.mapbox.com/mapbox-gl-js/api/#Map). I don't think there is a public method currently to enable/disable this for instance on the flyTo start/end.

**Comment by stevage** [comment]
Well, I don't have my heart set on it, just exploring different options. What I'm vaguely aiming for is a slow continuous loop that the user can temporarily derail, and it will just pick up where it left off. But yeah, just exploring and learning, really.
