### ISSUE TITLE
Document easing function requirements

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4182]
https://www.mapbox.com/mapbox-gl-js/api/#AnimationOptions says:

>easing (Function) : The animation's easing function.

But it doesn't say what arguments will be passed, nor what it should return.

I took a punt that it might be f(t, b, c, d) (from [here](http://gizma.com/easing/)) but that didn't seem to be right.

**Comment by stevage** [comment]
Ok, it looks like it's just `f(t)`, where t is between 0 and 1, and you return a value between 0 and 1.

It's redundantly referred to at https://www.mapbox.com/mapbox-gl-js/api/#Map#flyTo as well.

**Comment by mourner** [comment]
Correct! Want to submit a PR that improves the docs on this?

**Comment by stevage** [comment]
Yeah, seems like something I could do - especially since you have such wonderful [meta-documentation](https://github.com/mapbox/mapbox-gl-js/tree/master/docs).
