### ISSUE TITLE
Get style then set style with raster source produce an error

### ISSUE THREAD

**Issue by fxi** [mapbox/mapbox-gl-js#4183]
**mapbox-gl-js version**: 0.32.1

### Steps to Trigger Behavior

 1. Add a raster layer:

```js
  map.addLayer({
    id: "satellite",
    type: "raster",
    source: {
      type: "raster",
      url: "mapbox://mapbox.satellite",
    }
  })
```
 2. setStyle returned by getStyle

```js
map.setStyle(map.getStyle())
``` 
[jsfiddle example](https://jsfiddle.net/fredofixie/zb4bg4df/1/)

### Expected Behavior

The style produced by getStyle should be applied without errors.

### Actual Behavior

An error is produced:  

```js
sources.satellite.tiles: a source with a "url" property may not include a "tiles" property
    at Function.module.exports.emitErrors
```

**Comment by mourner** [comment]
Looks like we serialize all source properties after TileJSON is loaded, while validation considers `tiles` and `url` mutually exclusive. Should be an easy fix.

**Comment by anandthakker** [comment]
Thanks for the bug report @fxi !  I believe the issue here is the same as in #3893, closing as duplicate.

**Comment by fxi** [comment]
@anandthakker Thanks to you! I did not see the similarity between the two issues, sorry. I will keep an eye on this :)
