### ISSUE TITLE
icon-image not showing up

### ISSUE THREAD

**Issue by clankill3r** [mapbox/mapbox-gl-js#4185]
this works:   
```
     map.addLayer({
                    "id": "coins_layer",
                    "type": "circle",
                    "source": "coins",
                    "paint": {
                        "circle-color": "#FFFF00",
                        "circle-radius": 10,
                    },
                });
```
With the following nothing is showing up:
```
  map.addLayer({
                "id": "coins_layer",
                "type": "symbol",
                "source": "coins",
                "layout": {
                    "icon-image": "rocket-15"
                }
            });
```

Anyone an idea what it can be? The documentations is driving me nuts for days.

**Comment by jfirebaugh** [comment]
Can you please create a minimal runnable example that demonstrates the issue?

**Comment by stevage** [comment]
I'm guessing your style doesn't include the Maki icons. If you create a style from scratch in Studio, you need to manually add each icon that you intend to use. (I don't know how to bulk load them all - I assume there is a way, but I haven't figured it out.)

I'm also pretty unclear on how icons work. The documentation is a bit confusing in that the Map section refers to "sprites" and "glyphs" whereas elsewhere it refers to "icons" and "fonts" and "SDF icons" and "symbols", and the relationships between all those things is a bit too implicit for my understanding.

**Comment by clankill3r** [comment]
I think I will just get the GL context so I don't need to use the mapbox api anymore.
