### ISSUE TITLE
Create an in-browser implementation of the integration test harness

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#4190]
I think creating an in-browser version of `suite_implementation.js` would ease / speed up the process of working on shaders and other rendering logic, as it would allow a flow where you load up one of the relevant render tests in the browser, possibly set breakpoints & inspect, possibly use chrome's WebGL debugging extension, and easily refresh to check changes.

**Comment by ansis** [comment]
This would also let us run all the render tests in all the actual browsers and hopefully catch some browser-specific bugs.

**Comment by mourner** [comment]
There's also a chance we could then run this on CI using CPU drivers for GL https://github.com/google/swiftshader

**Comment by asheemmamoowala** [comment]
This was done in #8584 and cbf6229bf3530b3909ab927444f6fc63a0000b27
