### ISSUE TITLE
How to test mapbox-gl in Mocha

### ISSUE THREAD

**Issue by yangdonglai** [mapbox/mapbox-gl-js#4199]
**mapbox-gl-js version**: 0.29

### Steps to Trigger Behavior

 1.create file test.js  app.js

  ```
//test.js
var app = require('./app.js');

  //app.js
var mapboxgl = require('mapbox-gl/dist/mapbox-gl.js');

```

 2. `npm i -g mocha`
 3.`mocha ./test.js`

### Expected Behavior
`mocha passing`
### Actual Behavior
```
/Users/gagogroup/learn/react-testing-demo/node_modules/.0.32.1@mapbox-gl/dist/mapbox-gl.js:225
"use strict";module.exports=self;
```

**Comment by Scarysize** [comment]
It's not that easy to test gl libraries in a non-browser environment. For mapbox-gl there is a good mock of the library: https://github.com/mapbox/mapbox-gl-js-mock

**Comment by lucaswoj** [comment]
Mapbox GL relies heavily on browser features, like WebGL, which are not available in node.

https://github.com/mapbox/mapbox-gl-js-mock is maintained by the Mapbox Studio team and should always be up to date. 

You may be interested in how https://github.com/mapbox/mapbox-gl-layer-groups mocks out browser APIs to run GL JS in Node. This is similar to how we test GL JS internally.
