### ISSUE TITLE
Tile doesn't render with no data

### ISSUE THREAD

**Issue by dmitrig01** [mapbox/mapbox-gl-js#42]
Sometimes, when viewing empty tiles, the tile doesn't render at all. This happens when the server returns an empty file -- presumably because there's no data in that tile. However, we should still show something.

Currently, it looks like this:
![](https://dl.dropboxusercontent.com/u/18917108/WebGL.png)

What's happening is that since the tile is empty, `xhr.response` is null, and the second branch is getting in this if statement: https://github.com/mapbox/llmr/blob/gl/js/vectortileloader.js#L146-L150. That gets passed back as an error when in fact there is no error -- just no data at all.
I have a feeling the server is at fault -- the client needs to at least know what layer to color in...

**Comment by jfirebaugh** [comment]
Fixed on the tile-serving side.
