### ISSUE TITLE
Sprite style property doesn't accept relative urls

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox-gl-js#4201]
While `glyphs` property accepts a relative url without any problems, I couldn't make `sprite` property with relative url work, until changed it to an absolute one. Is there a way to have a relative url for `sprite` property?

**Comment by Scarysize** [comment]
I think relative URLs where supported "by accident" in one of the older releases. AFAIK relative URLs won't be supported, but you can preprocess your style JSON to change relative urls to absolute ones.

**Comment by jfirebaugh** [comment]
Relative URLs are not supported: #4141.
