### ISSUE TITLE
Adding a symbol layer with a Polygon source leaves map in unpredictable state as of 0.29.0

### ISSUE THREAD

**Issue by dpieri** [mapbox/mapbox-gl-js#4211]
**Version:** 0.29.0+

### Steps to Trigger Behavior

 1. Use any version >= 0.29.0 (I've checked them all).
 2. Add a FeatureCollection with some polygons as a GeoJSON source.
 3. Add a symbol layer that uses this source.

### Expected Behavior
Map works like normal and looks like this (note the anchors):
<img width="719" alt="screen shot 2017-02-05 at 2 14 53 pm" src="https://cloud.githubusercontent.com/assets/539310/22630359/979efa8e-ebad-11e6-9c4c-aba6bf177e68.png">

### Actual Behavior
Map looks like this:
<img width="717" alt="screen shot 2017-02-05 at 2 14 37 pm" src="https://cloud.githubusercontent.com/assets/539310/22630360/9cf79342-ebad-11e6-96eb-7df4121ab120.png">

Map is in a strange state. It does not render the symbols, but it also seems to stop rending other features properly. It is less pronounced in the example I've included. In my codebase the map stops loading new vector layers as you move the map around (raster layers update just fine). In both cases, if you leave the browser window open long enough it will crash.

If you switch to version 0.28.0 these problems are not present.

#### Examples:
Broken in 0.29.0: https://jsbin.com/viyosubosa/1/edit?html,output
Working in 0.28.0: https://jsbin.com/koloyojiwe/edit?html,output

**Note:** If you take the 0.29.0 example and switch the layer filter from `Polygon` to `LineString`, it works fine.

**Comment by AndyMoreland** [comment]
I am also effected by this bug.
