### ISSUE TITLE
Support data-driven fill-extrusion#visiblity

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4213]
It's probably redundant to explicitly request this feature (everyone wants *every* feature data-driven, right? :)), but this would be a particularly useful one. 

Motivating use case: I'm doing a 3D visualisation by census block (similar to [this](https://www.mapbox.com/bites/00273/)). The datasets I'm visualising generally have lots of zero-rows, so currently they come out like this:

![clued3d](https://cloud.githubusercontent.com/assets/678344/22633888/35be3560-ec79-11e6-8e27-474ed3309d1b.png)

It'd be nicer, I think, to render nothing for the zero values (letting more street space show through).

Possible workarounds:

- `filter` seems to work very slowly for large numbers of values (~600)
- `opacity` is not available per-row

**Comment by jfirebaugh** [comment]
We wouldn't make "visibility" data-driven because it's exactly equivalent to filters, and would be implemented in the same way, so it would not be any faster.

**Comment by ryanbaumann** [comment]
@stevage can you use a layer filter effectively to remove zero values?
 `filter: ['>', 'property', 0]`

Another technique would be to use data-driven `fill-extrusion-opacity` to set the opacity to zero for all property values.

`fill-extrusion-opacity: {property: "Property", type:'interval', stops: [[0,0],[1,1]]`

**Comment by stevage** [comment]
Sorry, left out a key detail - I'm using the [join technique](https://www.mapbox.com/mapbox-gl-js/example/data-join/) so the parameters aren't directly on the geometries.

I'll probably have to reconsider my approach here.

@ryanbaumann Using `fill-extrusion-opacity` doesn't work as it doesn't (and [won't](https://github.com/mapbox/mapbox-gl-js/issues/3675)) support data-driven styling.

**Comment by stevage** [comment]
FWIW, looks like I was mistaken about the performance of large filters - it's working just fine.

<img width="734" alt="screenshot 2017-02-06 20 44 31" src="https://cloud.githubusercontent.com/assets/678344/22642013/174b67cc-ecad-11e6-8252-019aab137253.png">
