### ISSUE TITLE
Circles not found with map.queryRenderedFeatures when using certain style

### ISSUE THREAD

**Issue by jeroenjansen88** [mapbox/mapbox-gl-js#4214]
While using the style:
`"circle-radius": {property: 'radius', type: 'identity'}`
set on a circle layer it is no longer posible to use:
map.queryRenderedFeatures

as you can see in the example:
[JSBin](https://jsbin.com/jifabogire/edit?html,console,output)

when you click on the red dot, the console should output its title.
Yet when you actiate the second layer. (which gets the circle radius from the feature properties) you will notice that neither dot will now be found and output their titles.

The bug seems to be caused by the following code:

`styleLayerDistance = paint['circle-radius'] + translateDistance(paint['circle-translate']);`

which is located in the function: 
`FeatureIndex.prototype.query`

since paint['circle-radius'] is undefined here, the styleLayerDistance becomes NaN and when this gets added to the searchrectangle coordinates seem to be mangled aswell.

expected behaviour: features are found.
actual behaviour: features are not found.

I hope to have informed you enough.

**Comment by jfirebaugh** [comment]
Thanks for the report @jeroenjansen88. We're tracking this issue in #3604.
