### ISSUE TITLE
map.addLayer(..."circle-radius"..."stops": ...) throws error "stop domain values must be unique"

### ISSUE THREAD

**Issue by datadiver0x0** [mapbox/mapbox-gl-js#4218]
**Context: data-driven styling for circle radius; zoom and property functionality broken**

In the newest Mapbox-gl release, v0.32.1, data-driven styling for circle radius no longer works as described in the Mapbox GL data-driven style reference's ["Circle layer, zoom and circle-radius, exponential"](https://www.mapbox.com/help/gl-dds-ref/#circle-layer-zoom-and-circle-radius-exponential) example.

Setting combined zoom/property value stops using the [{ "zoom": 15, "value": 1 }, 10] format no longer works if the same value is repeated for a different zoom level (e.g. [{ "zoom": 17, "value": 1 }, 20] ).  This syntax produces the error "stop domain values must be unique".  This may be the result of an edit based on [issue #611](https://github.com/mapbox/mapbox-gl-style-spec/issues/611), "Require unique categorical function domain values".

A minimally altered version of the data-driven styling example can be found [here](http://jsbin.com/xujelur/edit?html,console,output).  I had to alter it because the original example didn't perform any data-driven styling on the circle radius.  Reverting to version v0.31.0 results in the expected functionality.

As a side note, links to "zoom and property functions docs" appear to be [broken](https://www.mapbox.com/mapbox-gl-style-spec/#types-function-zoom-property).

Thanks,
Jus

**Comment by jfirebaugh** [comment]
Thanks for the report @datadiver0x0. This was indeed an unintended result of https://github.com/mapbox/mapbox-gl-style-spec/issues/611. Fix in https://github.com/mapbox/mapbox-gl-js/pull/4220.

**Comment by datadiver0x0** [comment]
Hi, could you let me know when this will be incorporated into the production API?  Thanks.

**Comment by lucaswoj** [comment]
@datadiver0x0 Our next release will be on or before March 1st
