### ISSUE TITLE
queryRenderedFeatures not querying `current` data when styles are added / removed.

### ISSUE THREAD

**Issue by dougajmcdonald** [mapbox/mapbox-gl-js#4222]
I have a map which has a filter applied to a layer. We have a function `refreshFilter(filterValue)` which clears and then re-adds the filter with the new value.
e.g.
```
refreshFilter(filterValue) {
  removeLayer('ourLayer');
  addLayer({
      'id': 'ourLayer',
      'type': 'line',
      'filter': ['all', ['==', 'sex', filterValue]]
    }, 'marker');
}
```

This works as expected, and the features I see rendered from the GeoJson match the `sex` provided.

My problem comes when I want to return from the map, the features which match my filter. 

I updated the `refreshFilter` function to return the features which were visible using `queryRenderedFeatures` but this always returns the opposite of what I'm expecting. So if pass in `male` I visually see the features which match `sex=='male'` (expected) but the `queryRenderedFeatures` function returns features which match `sex=='female'` (unexpected).

Simplified version

```
refreshFilter(filterValue) {
  removeLayer('ourLayer');
  addLayer({
      'id': 'ourLayer',
      'type': 'line',
      'filter': ['all', ['==', 'sex', filterValue]]
    }, 'marker');
  return queryRenderedFeatures({layers: ['ourLayer']});
}
```

It seems to me that the call to `queryRenderedFeatures` hasn't waited for the layers to be changed and has queried the previous set of features to work out what to return.

Am I doing something wrong here? Any pointers greatly appreciated.

**Comment by dougajmcdonald** [comment]
As an update I hacked a `setTimeout` round the `queryRenderedFeatures` call and this works. This would suggest that the update through `addLayer` is async. Having looked over the API I can't see a callback or anything to use to ensure the new filter has been applied. 

Is these a recommended approach to handle this kind of situation?

**Comment by jfirebaugh** [comment]
Can you please create a minimal self-contained example that demonstrates the issue?

**Comment by dougajmcdonald** [comment]
@jfirebaugh I'm trying to knock up an example on jsbin but i just get a script error when i try to `addSource` with my geojson. 

I've linted the geojson and that's all good, do you have a preferred platform for demo's? I can port the code.

**Comment by dougajmcdonald** [comment]
@jfirebaugh Ok, fixed it, here's the JSBin with the access token removed:

https://jsbin.com/binawol/edit?html,js,console,output

If you click the button it will output the values I pass into the `filter` property and then after that, the `properties.DEV_STATUS` value from the features which `queryRenderedFeatures` returns (you will notice that the features are always one step the filters passed to `addLayer`.

Hope that makes sense, shout for more info,

**Comment by anandthakker** [comment]
@dougajmcdonald thank you for providing the example.   The reason the results of your `queryRenderedFeatures` lags 'behind' the most recent layer settings is that adding a layer (or using `map.setFilter` to modify a layer's filter) is an asynchronous operation.   We are [discussing ways](https://github.com/mapbox/mapbox-gl-js/issues/3964) to improve the API of async methods like this, but in the meantime, you can check `map.loaded()` to determine whether the operation is complete.  A common pattern for doing this without resorting to setTimeout is:

```js
map.addLayer(...) // make your change
map.on('render', afterChangeComplete); // warning: this fires many times per second!

function afterChangeComplete () {
  if (!map.loaded()) { return } // still not loaded; bail out.

  // now that the map is loaded, it's safe to query the features:
  map.queryRenderedFeatures(...);

  map.off('render', afterChangeComplete); // remove this handler now that we're done.
}
```

**Comment by anandthakker** [comment]
@dougajmcdonald I'm closing this issue, but if the above suggestion does not help, please feel free to [contact Mapbox Support](https://www.mapbox.com/contact/) or reopen it!

**Comment by dougajmcdonald** [comment]
Thanks for the info, this is what I suspected.

As a work around for my use case could I just query the source with the map bounds passed in? Or would I see the same kind of issue?

**Comment by dougajmcdonald** [comment]
@anandthakker I just wanted to add one more note to this issue. 

I got caught out by using either es6 fat arrow functions OR es5 bind calls when setting up a handler for the render event from inside an es6 class

If you use the following:

```
map.on(render', () => this.afterChangeComplete);
map.off('render', () => this.afterChangeComplete);
```

OR

```
map.on(render', this.afterChangeComplete.bind(this));
map.off('render', this.afterChangeComplete.bind(this));
```

Then the handler won't be removed as JS will create an anonomous function under the hood and the `off` call won't remove it.

**Comment by dlmu-lq** [comment]
Thanks to you all, Hope this helps:
`
                    // debounce from loadsh/debounce
                    let debouncedOnRender = debounce(()=>{
                        console.log("debounced render");
                        func();
                        self.map.off('render', debouncedOnRender);
                    },300);
                    this.map.on('render', debouncedOnRender);`

**Comment by tmlmt** [comment]
Hey is this hack still valid? I have the same situation where I need to update a list after a filter has been set. Checking with some logs, I can see that `afterChangeComplete` gets fired 8 times before `queryRenderedFeatures(...)` is called, but the function return the wrong list. Only a setTimeout sufficiently long enables queryRenderedFeatures to return the right list.
