### ISSUE TITLE
Why init map canvas with postion: absolute?

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#4224]
In [here](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/map.js#L1056), I notice mapbox-gl init a canvas with the style of "position: absolute", which cause canvas overflow out of its parent div. Maybe fully contained in parent div would be better?

**Comment by jfirebaugh** [comment]
It's absolute in case there are other elements prepended to the container element, which would otherwise affect its placement. If you're encountering an issue with this, could you please supply a minimal example that demonstrates the issue?

**Comment by jingsam** [comment]
I found my map became black as I visited it on my Android phone using Chrome 58, as:
![1](https://cloud.githubusercontent.com/assets/1522494/22728829/ed403556-ee1a-11e6-9dc4-91cb78d9a99e.jpg)

But landscape is OK:
![2](https://cloud.githubusercontent.com/assets/1522494/22728913/4a3c0640-ee1b-11e6-8f43-593c2ae4d47c.jpg)


When the keyboard pushed up the map, also OK:
![3](https://cloud.githubusercontent.com/assets/1522494/22728936/623344d4-ee1b-11e6-8d70-9d390f4a058a.jpg)

I inspected the console, the warning says the width and height of the map are too large. I guess it is a css issue.

Here is the link: http://101.200.63.93/

**Comment by mourner** [comment]
Yes, it looks like the HTML lacks the meta tag that prevents scaling of the page on mobile, which can make the map container too big for a small screen. It's not related to the container being absolute. I think we can close the issue as a problem on the application side.
