### ISSUE TITLE
Link to "Troubleshooting SVG image errors" when SVG upload fails in Studio

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4232]
I'm having quite a bit of difficulty generating SVGs for use as textures, which I'm uploading through Studio. The only thing that works for me is manually writing extremely simple SVGs like:

```
<svg width="16" height="64" xmlns="http://www.w3.org/2000/svg">
  <line y2="0" x2="-8" y1="64" x1="-12" stroke-width="0.5" stroke="#530"/>
  <line y2="0" x2="-4" y1="64" x1="-8" stroke-width="0.5" stroke="#530"/>
  <line y2="0" x2="0" y1="64" x1="-4" stroke-width="0.5" stroke="#530"/>
  <line y2="0" x=2"4" y1="64" x1="0" stroke-width="0.5" stroke="#530"/>
  <line y2="0" x2="8" y1="64" x1="4" stroke-width="0.5" stroke="#530"/>
  <line y2="0" x2="12" y1="64" x1="8" stroke-width="0.5" stroke="#530"/>
  <line y2="0" x2="16" y1="64" x1="12" stroke-width="0.5" stroke="#530"/>
</svg>
```

Anything generated by an online SVG editor gets rejected, with no error information (other than if the dimensions exceed 512px). What are the requirements exactly?

**Comment by jfirebaugh** [comment]
@stevage Does [this article](https://www.mapbox.com/help/studio-troubleshooting-svg/) help?

**Comment by stevage** [comment]
Oh, yes. Changing ticket title...

**Comment by mollymerp** [comment]
Thanks @stevage – I have requested updates to the documentation internally and for a link to be added when uploads fail in studio.
