### ISSUE TITLE
Error adding LogoControl

### ISSUE THREAD

**Issue by Naimikan** [mapbox/mapbox-gl-js#4242]
**mapbox-gl-js version**: v0.32.1

Example [here](http://codepen.io/Naimikan/pen/OWBpZQ)

### Steps to Trigger Behavior

 1. map.addControl(new LogoControl());

### Expected Behavior
See the Logo icon.

### Actual Behavior
Throw an error. `ReferenceError: LogoControl is not defined`

I tried `map.addControl(new LogoControl())` and `map.addControl(new mapboxgl.LogoControl())`. I think it should be `mapboxgl.LogoControl` for follow the same nomenclature that the other controls.

**Comment by jfirebaugh** [comment]
@Naimikan `LogoControl` isn't in a versioned release yet, and when it is released, it will be added to the map and shown automatically when required; you won't need to add it manually.

**Comment by Naimikan** [comment]
Thank you @jfirebaugh!
