### ISSUE TITLE
Map#queryRenderedFeatures doesn't find layers when paint property uses "identity"

### ISSUE THREAD

**Issue by Naimikan** [mapbox/mapbox-gl-js#4245]
**mapbox-gl-js version**: v0.32.1

Example [here](http://codepen.io/Naimikan/pen/OWBBzd)

### Steps to Trigger Behavior

 1. Mouse over the layers

### Expected Behavior
Change the cursor to "pointer"

### Actual Behavior
It doesn't do anything

<hr>

When I define a layer like this:
```
map.addLayer({
   "id": "route",
   "type": "circle",
   "source": {
      "type": "geojson",
      "data": {
         "type": "Feature",
         "properties": {
            radius: 10
          },
          "geometry": {
             "type": "Point",
             "coordinates": [-74.50, 40]
          }
       }
   },
   "paint": {
      "circle-color": "#FF0000",
      "circle-radius": {
         type: 'identity',
         property: 'radius'
      }
   }
});
```
the `map.queryRenderedFeatures` doesn't return any feature

**Comment by jfirebaugh** [comment]
Thanks for the report -- we're tracking this in #3604.

**Comment by Naimikan** [comment]
Thank you @jfirebaugh! I have just see the issue #3604.
