### ISSUE TITLE
RTL text plugin causes memory leaks

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#4246]
Every time a style is created, it pushes a callback onto `pluginAvailableCallbacks` which is never removed. The callback binds the style object, and the style references the map, so this leaks the entire shebang.

cc @ChrisLoer 

Refs #3264.

**Comment by ChrisLoer** [comment]
Ack!

Since the plugin can load at any time, I think we want the listener to live as long as the style (or at least until the plugin is loaded). Is there a good way to hook de-registering code to run when the style is destroyed?

**Comment by jfirebaugh** [comment]
Yeah, you can add something to `Style#_remove`.
