### ISSUE TITLE
Support fill-pattern-spacing-x, y, and stagger.

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4250]
The current model for fill patterns assumes a single image which is tiled seamlessly in both directions:
```
TTTT
TTTT
TTTT
```

However, in my experience, mostly when I've wanted to use a fill pattern, it's for an icon to be repeated with a large gap, and generally staggered:

```
I   I   I   I
  I   I   I
I   I   I
  I   I   I
```

![image](https://cloud.githubusercontent.com/assets/678344/22812354/544e36ca-ef98-11e6-83e9-16784f292aa1.png)

![image](https://cloud.githubusercontent.com/assets/678344/22812367/61f70b44-ef98-11e6-8384-f633192858ba.png)

The only way to do this currently is to generate a tiling SVG, which is (in my experience) quite fiddly. It also means there is no prospect of adjusting the tiling distance based on zoom.

So, how about the ability to specify tiling distance and stagger directly?

* `fill-pattern-x-distance`: horizontal distance between two images
* `fill-pattern-y-distance`: vertical distance between two images
* `fill-pattern-y-stagger`: vertical offset added each column

**Comment by lucaswoj** [comment]
Closely related to #4109

**Comment by stevage** [comment]
Ah, thanks. Yeah, I'm not sure whether it makes more sense to just have the hexagonal pattern, or to have the stagger attribute and hence allow rectangular, hexagonal, and possibly other patterns too.

Great description of the three important attributes there. Ok with me if you want to close and merge this.

**Comment by stevage** [comment]
After looking at #4109, another way to express this might be:

```
fill-icon: "tree15",
fill-icon-spacing: 30 // optional, with some sensible default, requires fill-icon
```

That would support the main use cases, and leave room for further options later if they're really warranted.

Using fill-icon instead of fill-pattern would imply (as from #4109):

- orientation locked to viewport (but still flat within the map plane)
- spaced and staggered in hex pattern
- icons don't scale, new ones fade in to fill the gaps

Presumably fill-icon is mutually exclusive with fill-pattern and fill-color.

**Comment by jfirebaugh** [comment]
Let's use #1831 as the umbrella ticket for fill-pattern enhancements.
