### ISSUE TITLE
about mapboxGl使用的几点问题反馈

### ISSUE THREAD

**Issue by tianbaolin** [mapbox/mapbox-gl-js#4251]
1.切换style时,重新加载地图太慢。希望能够变快。
2.map上添加的 popup 在边界上会向内偏移产生避让行为，希望这个行为可以人工设置。
3.地图缩放过快时，地图上的 popup 和 mark 会产生联动滞后的效果，希望可以减小这种滞后的效果。
4.希望能够有中文版文档，because my English isn't very well.
以上相关问题均是在mobile端测试产生的问题。
mapboxGl is very good ,I like it .thanks。

**Comment by kkaefer** [comment]
For reference, here's an automated translation:

> 1. Reload map when switching style too slow. Hoping to become faster.
> 2.map added to the map on the map will be offset inward migration to avoid behavior, I hope this behavior can be manually set.
> 3. Map zoom too fast, the map of the popup and mark will produce linkage lag effect, hoping to reduce the effect of this lag.
> 4. I hope to have the Chinese version of the document, because my English is not very well.
> The above issues are related to the mobile side of the test problems.
> MapboxGl is very good, I like it.

**Comment by lucaswoj** [comment]
> 1\. Reload map when switching style too slow. Hoping to become faster.

We are always looking to improve performance. Switching styles using `Map#setStyle` should be very smooth as of #3621. Let us know if you're seeing anything that looks like a performance regression or bug. 

> 2\. map added to the map on the map will be offset inward migration to avoid behavior, I hope this behavior can be manually set.

Perhaps you're looking for #4268

> 3\. Map zoom too fast, the map of the popup and mark will produce linkage lag effect, hoping to reduce the effect of this lag.

Perhaps you're looking for https://github.com/mapbox/mapbox-gl-js/issues/3273 

> 4\. I hope to have the Chinese version of the document, because my English is not very well.

We don't have a Chinese translation of our API docs available. @jingsam has translated the style spec documentation into Chinese: https://jingsam.github.io/mapbox-gl-style-spec/
