### ISSUE TITLE
Text label relative to icon-image/viewport?

### ISSUE THREAD

**Issue by livemixlove** [mapbox/mapbox-gl-js#4256]
I can't figure out how to keep a text-field stay in the same place relative to an icon-image.  Apologies if this is documented.  Hard to tell if this is a bug, missing feature, or due to my lack of understanding.

**mapbox-gl-js version**:
Using https://api.tiles.mapbox.com/mapbox-gl-js/v0.32.0/mapbox-gl.js
### Steps to Trigger Behavior

 **1.**
Add a icon layer with text-field labels.
```
map.addLayer({
			"id": "whatever",
			"type": "symbol",
			"source": "someData",
			"layout": {
			"icon-image": "someImage",
			"icon-offset": [0,-21],
			"text-field":"{my_text_field}",
			"text-anchor":'center',
			"text-size":11,
			"text-allow-overlap":true,
			"text-rotation-alignment":"viewport",
			"text-keep-upright": true,
			}
			,"paint":{
			"text-color":"#000000",
			"text-halo-width":1,
			'text-translate':[0,-25]
			},
})
```
 **2.**
This is a non-rotated icon+text, looking good:
<img width="629" alt="screen shot 2017-02-10 at 12 08 13 pm" src="https://cloud.githubusercontent.com/assets/148947/22842388/e4cf6f52-ef89-11e6-8007-5167964b861d.png">

This is what it looks like if you rotate:
<img width="372" alt="screen shot 2017-02-10 at 12 08 31 pm" src="https://cloud.githubusercontent.com/assets/148947/22842395/ec66f208-ef89-11e6-963f-b78e745be92a.png">
<img width="276" alt="screen shot 2017-02-10 at 12 08 19 pm" src="https://cloud.githubusercontent.com/assets/148947/22842396/ec7f475e-ef89-11e6-9a0f-d0e90d3a9a64.png">

Expected or desired behavior:
The icon labels stay in viewport space, relative to the icon.

What happens:
The text-field label appears to rotate in map space.

**Is it possible to keep a text-field label relatively placed (via text-translate) to an icon with map rotation?**

**Comment by livemixlove** [comment]
If this is not self evident, let me know and I can make an example map.

**Comment by anandthakker** [comment]
@livemixlove Does using [`text-offset`](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-offset) rather than text-translate help?   Or, another option: perhaps setting [`text-translate-anchor: "viewport"`](https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-text-translate-anchor)?

**Comment by livemixlove** [comment]
@anandthakker  thank you! `  text-translate-anchor: "viewport"` did the trick.   I had missed that property.

**Comment by anandthakker** [comment]
Glad that helped @livemixlove!  If you have other usage questions in the future, please feel free to contact [Mapbox Support](https://mapbox.com/contact/) as well!

**Comment by livemixlove** [comment]
Ok, will do.  Sorry to file an issue for a usage problem.  I'll try to make
support my front line.

**Comment by anandthakker** [comment]
No worries @livemixlove -- as you mentioned, I know that it is not always obvious whether it's a bug or a usage question!

**Comment by vaibhav5592** [comment]
What are value of my_text_field ?

**Comment by dberardo-com** [comment]
is it possible to place icons in a layer in a similar way, so that their visual distance is constant ? basically the geo coordinates of on icon will be defined, while the other icon is kept at fixed distance from the first one, and so on for all other icons in the same layer ?
