### ISSUE TITLE
SVG file accepted by upload into Studio, but not available

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4258]
I uploaded this SVG file as a texture:

```
<svg xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='12' height='12' viewBox='0 0 30 30'>
    <defs>
	<g id='curves'>
		<path stroke='#000' stroke-width='5' d='M0 0c0,30, 30,30 30,0'/>
		<path fill='#733' stroke='#955' stroke-width='2.2' d='M0 0c0,30, 30,30 30,0'/>
	</g>
	</defs>
	<rect width='100%' height='100%' fill='#733'/>
	<use x='15' y='15' xlink:href='#curves' />
	<use x='-15' y='15' xlink:href='#curves' />
	<use x='0' y='0' xlink:href='#curves' />  
	<use x='15' y='-15' xlink:href='#curves' />
	<use x='-15' y='-15' xlink:href='#curves' />
</svg>
```

Studio didn't give an error, but it doesn't show up in the texture list either. Uploading the same file again warns that I'm overwriting a file of the same name.

(Is this the right place to report bugs in Studio?)

**Comment by stevage** [comment]
Hmm, it seems to happen when there are percentages. This makes an unselectable SVG, like above:

```
<svg xmlns='http://www.w3.org/2000/svg' width='10' height='10'>
    <rect y='-30%' x='60%' width='50%' height='50%' fill='#e2e2e2' transform='rotate(45)'/>
</svg>
```

This makes a selectable, but invisible (and non-rendering) texture:

```
<svg xmlns='http://www.w3.org/2000/svg' width='10' height='10'>
	<rect y='-3' x='6' width='50%' height='50%' fill='#e2e2e2' transform='rotate(45)'/>
</svg>
```

This makes a fully functioning texture:

```
<svg xmlns='http://www.w3.org/2000/svg' width='10' height='10'>
	<rect y='-3' x='6' width='5' height='5' fill='#e2e2e2' transform='rotate(45)'/>
</svg>
```

Related to #4232 I guess.

**Comment by mollymerp** [comment]
Hi @stevage -- thanks for reporting your issue. Our team is working on improving the documentation around what properties of svgs are permitted. In this case, I believe the percentages indicate a "Responsive" svg, which are not permitted as Studio uploads as documented, sort of, [here](https://www.mapbox.com/help/studio-troubleshooting-svg/#export). 

Closing as this is not actionable in this repo
