### ISSUE TITLE
Clarity around plugins contribution model

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4260]
I'd be interested in contributing a couple of [Mapbox-GL-JS plugins](https://www.mapbox.com/mapbox-gl-js/plugins/), if Mapbox is accepting third-party plugins. But I can't see anything about what the contribution model is - what standard, if any, is required. The [only blog post I see](https://www.mapbox.com/blog/build-mapbox-gl-js-plugins/) refers only to Control plugins.

A couple I had in mind (the basic work is already done):

- supporting SimpleStyle for GeoJSON objects (see https://github.com/stevage/geojson-gist)
- animated flyTo loops (a sort of workaround for https://github.com/mapbox/mapbox-gl-js/issues/981)
- 3D extruded-fill visualisations of datasets (see https://city-of-melbourne.github.io/Data3D/ )

**Comment by lucaswoj** [comment]
There is no single type of plugin for GL JS. For example, there are plugins that add new UI elements, plugins that draw to `canvas` layers, and plugins that do data preprocessing. Therefore there is no single standard for plugins.

The plugin contribution model is

 - you create a plugin that uses the public GL JS APIs to do something useful
 - you publish the plugin on a CDN (https://unpkg.com is easy) 
 - you submit a PR to add that plugin to our [documentation](https://github.com/mapbox/mapbox-gl-js/tree/mb-pages/docs/_posts/plugins) (we're working on revamping this architecture right now, it's a little confusing at the moment) 
 - we accept the PR so long as the plugin is well-designed and well-maintained

-----

> supporting SimpleStyle for GeoJSON objects

I'd recommend the plugin exist as a function that turns a GeoJSON into a Mapbox Style

> animated flyTo loops (a sort of workaround for #981)

I'd recommend the plugin exist external to GL JS and call its methods.

> 3D extruded-fill visualisations of datasets (see https://city-of-melbourne.github.io/Data3D/ )

I'd recommend the plugin exist as a function that turns a GeoJSON and some options into a Mapbox Style

**Comment by jfirebaugh** [comment]
> supporting SimpleStyle for GeoJSON objects

Have you seen https://github.com/mapbox/simplespec-to-gl-style?

**Comment by stevage** [comment]
Thanks!

>Have you seen https://github.com/mapbox/simplespec-to-gl-style?

No I hadn't, thanks :) 

>>animated flyTo loops (a sort of workaround for #981)

>I'd recommend the plugin exist external to GL JS and call its methods.

Yeah, something like this:

`flyPath(map, route)`

where `route` is a GeoJSON object set of points with AnimationOptions as metadata.


>>3D extruded-fill visualisations of datasets (see https://city-of-melbourne.github.io/Data3D/ )

>I'd recommend the plugin exist as a function that turns a GeoJSON and some options into a Mapbox Style

Well, it needs to add a source to the map as well, so probably needs to be passed the map object, but yeah.
