### ISSUE TITLE
Canvas source errors when larger than some environment-specific size

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4262]
per @kronick 

> It seems like canvases over a certain size (which varies by browser, but as small as 256x256 in Chrome) are failing and causing the entire map layer to go white-- this doesn't happen consistently and @lbud wasn't seeing the same issues so my guess is that it has something to do with video memory or the way the texture is created from the canvas

We're going to create some minimal test cases and do some research into known limitations today.

**Comment by kronick** [comment]
Here's a debug page I put together to help get to the bottom of this: https://www.mapbox.com/labs/canvas-heatmap/canvas-debug.html

Here's what's expected (red box and green X are rendered to canvas and then placed on map):
![image](https://cloud.githubusercontent.com/assets/186834/22996458/b7e73c06-f383-11e6-828a-fe40722c9946.png)

Here's what the bug looks like:
![image](https://cloud.githubusercontent.com/assets/186834/22996443/a6238eca-f383-11e6-854f-9d8f0693219c.png)


On my 2015 Macbook Pro 13" running OSX El Capitan 10.11.6 with Intel Iris Graphics 6100 1536 MB, here's what I'm seeing by browser:

### Chrome v56.0.2924.87:
Resolutions with >= 65,536 pixels (=2^16, equivalent to 256x256) fail

### Safari 9.1.2:
Resolutions with >= 524,288 pixels (=2^19, equivalent to 1024x512) fail

### Firefox 51.0.1:
Resolutions with >= 524,288 pixels (=2^19, equivalent to 1024x512) fail
 
---

@peterqliu checked this out for me on his 2015 Macbook Pro 15" running macOS Sierra 10.12.1 with Intel Iris Pro 1536 MB and was _not_ seeing the bug in Chrome at resolutions up to 2048x2048.

**Comment by jliebrand** [comment]
FYI: would have helped out to tell you if I see this in my setup, but the debug page 403s (in the console - failing to get the mapbox dev)

**Comment by jliebrand** [comment]
Friendly ping - any update on this?

**Comment by mcwhittemore** [comment]
I'm seeing this bug spill into Mapbox Draw tickets. I'm not sure what the status of this is here, but a Draw user provided another fiddle which I'm linking to here in case what is needed to see this move forward is more examples.

[Canvas breaks the map](https://jsfiddle.net/5mascc3w/6/)
[Removing canvas fixes the map](https://jsfiddle.net/5mascc3w/6/)

**Comment by gpbmike** [comment]
@kronick 

I'm seeing a bug with the same symptoms but it is not dependent on canvas size.

My test case is a 1x1 canvas. Problem occurs when I access the webgl context of the canvas.

https://codepen.io/gpbmike/pen/qXNPOM

I created an [issue](https://github.com/mapbox/mapbox-gl-js/issues/5081) with more details.

It appears to be dependent only on hardware.

**Intel Iris Graphics 6100 1536 MB**

Hopefully this helps a bit?

**Comment by gpbmike** [comment]
I'm seeing this behavior on renderers reported as the following

- Intel(R) Iris(TM) Graphics 6000
- Intel(R) Iris(TM) Graphics 6100
- Intel Iris OpenGL Engine

Using the following to get renderer:

```javascript
const dbgRenderInfo = gl.getExtension('WEBGL_debug_renderer_info');
const renderer = gl.getParameter(dbgRenderInfo.UNMASKED_RENDERER_WEBGL);
```

**Comment by jliebrand** [comment]
Another friendly ping; can someone from Mapbox please let us know if this is something that is being actively looked at?  It's obviously a deal breaker to go down the canvas route for some of our visualisations if this is not addressed

**Comment by lbud** [comment]
I'm looking into this now. There's an old pre-release build of the canvas source feature where this problem doesn't manifest, so I suspect the answer is somewhere in the diff between 3e36acc6b64e0f62301aa9dd45255459d1a03068 and 5082fec814fb8dddd67ce8f6d8dc33b5df215526 — particularly in the possibility that affected GPUs aren't able to use `texImage2D`/`texSubImage2D` on `HTMLCanvasElement`s (in the initial implementation we copied canvas data into an `ImageData` element as an intermediary step).

**Comment by lbud** [comment]
Out of curiosity, @jliebrand @gpbmike or anyone else who's seeing this issue — are you using the `2d` or `webgl` context type?

**Comment by kronick** [comment]
@lbud iirc, this was happening both with `2D` and `webgl` contexts.

**Comment by jliebrand** [comment]
2d in our case...

**Comment by gpbmike** [comment]
> are you using the `2d` or `webgl` context type for your use case?

@lbud in my case `document.getElementById('canvas').getContext('webgl')` is enough to trigger the behavior. See my [codepen](https://codepen.io/gpbmike/pen/qXNPOM) also [linked above](https://github.com/mapbox/mapbox-gl-js/issues/4262#issuecomment-319699136).

**Comment by jliebrand** [comment]
Thanks! Out of interest, is there any details as to when or what would trigger a new release? At the moment they seem to just come roughly once a month, but I can't really put my finger on a pattern. Is it "as and when" or is there more structure to it? (and if so, when is the next one? ;-))
