### ISSUE TITLE
Significant zoom levels within 0.1 decimals

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4276]
Sometimes I see this in Studio:

<img width="573" alt="screenshot 2017-02-15 12 31 01" src="https://cloud.githubusercontent.com/assets/678344/22957170/b5e25f3e-f37a-11e6-9b44-42feccd997a1.png">
<img width="562" alt="screenshot 2017-02-15 12 31 06" src="https://cloud.githubusercontent.com/assets/678344/22957168/b584405c-f37a-11e6-9d79-17fb686155a4.png">

That is, I have zoomed slightly in or out, and it's enough to make a lot more data show up - but in both cases, the zoom level is showing as "15.0".

This can be misleading if you're trying to make a map targeted at one specific zoom level.

**Comment by lbud** [comment]
/ @scothis @mcwhittemore

**Comment by lucaswoj** [comment]
This issue tracker is only for bugs with GL JS. We will forward this bug to the Studio team internally. Thanks!

**Comment by lucaswoj** [comment]
In the future, please submit Studio bugs via our support channels.

**Comment by stevage** [comment]
Any chance of a public issue tracker for Studio? (in addition to private
one)

Reasons why I prefer Issues over  support:
- it becomes part of my public profile
- I can attach more than one image
- it doesn't get misinterpreted as a support request
- opportunities for others  to comment

On 17 Feb 2017 6:33 a.m., "Lucas Wojciechowski" <notifications@github.com>
wrote:

In the future, please submit Studio bugs via our support channels.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mapbox/mapbox-gl-js/issues/4276#issuecomment-280434253>,
or mute the thread
