### ISSUE TITLE
fitBounds thows "failed to invert matrix" on valid lnglat points of type [number, number][].

### ISSUE THREAD

**Issue by jruddell** [mapbox/mapbox-gl-js#4281]
### Notes and Versioning Funkyness
Hi there, I am trying to implement a map page on my React application. I have multiple devices with locations I want to display on the map. Currently there is a JS exception thrown when trying to call `map.fitBounds` passing it what the API docs specify.

I saw the fitbounds example provided (https://www.mapbox.com/mapbox-gl-js/example/fitbounds/) and am confused why this (http://jsbin.com/gubisufoli/edit?html,output) works while this (http://jsbin.com/bojeqafimu/edit?html,output) is failing.

On another note the exact code works fine on an older version of mapbox-gl. Here are jsbin's showing what I am describing.

Older Version - http://jsbin.com/qututahidi/edit?html,output
It seems is after v0.22.1 is where the failure starts to happen. 

### My Attempts
**mapbox-gl-js version**: v0.32.1
```
var bounds = [[-122.3888, 37.7108], [-121.8863, 37.3382]];
// attempt 1
this.map.fitBounds(bounds); 
// attempt 2
this.map.fitBounds(mapboxgl.LngLatBounds.convert(bounds))
// attempt 3
bounds = new mapboxgl.LngLatBounds(bounds);
this.map.fitBounds(bounds); 
```
all three attempts returned the same error message.

### Steps to Trigger Behavior

 1. Create a map
 2. Create two valid lnglat points
 3. Call map.fitBounds() with the lnglat points.

### Expected Behavior

The map should pan to the desired location... Like the API docs say it does.

### Actual Behavior

The map locks up and doesn't work because of the JS error

**Comment by andrewharvey** [comment]
a [LngLatBounds object](https://www.mapbox.com/mapbox-gl-js/api/#LngLatBounds) or LngLatBoundsLike is "south west", "north east". LngLat is long then lat, so the full bounds like object will be `[[west, south], [east, north]]`.

In your example you have 37.7... for south and 37.3... for north. The south number must be < the north number, which is not the case in your bounds object, hence the error.

**Comment by jruddell** [comment]
@andrewharvey Thanks for clarifying that. Is there a way then to order the points so that it would be a valid LngLatBounds object? For instance if the use case is "I have n devices with Lng and Lat coordinates and I want to be able to view all of them on the map with the click of a button" how should I do that? I had figured fitBounds was the right method to use in conjunction with the convert function `mapboxgl.LngLatBounds.convert` Maybe my assumption was wrong that the convert would convert multiple points into a valid LngLatBounds object. Any suggestions?

**Comment by andrewharvey** [comment]
You could use http://turfjs.org/docs.html#bbox or [LngLatBounds#extend](https://www.mapbox.com/mapbox-gl-js/api/#LngLatBounds#extend) iteratively with each point to extend the LngLatBounds to contain all points.

**Comment by jruddell** [comment]
@andrewharvey Thank you for your help! I was already iterating over the markers to do some additional stuff. So adding in extend was simple and easy. For others that pass by this is what I did.
```
mapMarkerBounds = new mapboxgl.LngLatBounds();
// in for loop
const point = new mapboxgl.LngLat(Lng, Lat);
mapMarkerBounds.extend(point);
// in button click handler
map.fitBounds(mapMarkerBounds, {padding: 80});
```
