### ISSUE TITLE
If npm is used instead of yarn, warn the contributor rather than silently installing possibly broken dependencies

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#4284]
### Steps to Trigger Behavior

 1. Run `npm install` in a mapbox-gl-js repository checkout.
 
### Expected Behavior

An error such as the following:

> It looks like you're using npm to install mapbox-gl-js dependencies for development. mapbox-gl-js uses yarn to manage dependencies, not npm. Please see the README for further details: `<link>`.

### Actual Behavior

npm installs versions of dependencies that don't match the known good versions in `yarn.lock`. They might not work at all, such as in [this example](https://github.com/mapbox/mapbox-gl-native/pull/8078#issuecomment-280204666), leading to confusion and frustration for the potential contributor.

**Comment by jfirebaugh** [comment]
Snippet from Mapbox Studio that does this:

    "preinstall": "ps -fp $PPID | grep -q yarn || (echo '\\033[0;33mNPM not supported, please use Yarn.\\033[0m'; exit 1) && yarn cache clean",

**Comment by mollymerp** [comment]
closed by #4287
