### ISSUE TITLE
Remove redundancies in Camera method docs

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#4286]
From: https://github.com/mapbox/mapbox-gl-js/pull/4266#pullrequestreview-21738287

@anandthakker said:

> options.easing is duplicated here. In fact, for consistency, would it make sense to remove options.easing (and options.offset) in favor of setting the type of [options] to {AnimationOptions}? I realize that, at present, this means more clicks for readers of the docs, but my preference would be to solve that problem somehow in the documentation generation step.

@lucaswoj said:

> Good idea. If we go this route, we may also want to:

> rename/alias options.linear to options.animate
> add options.duration (this will just be passed to Map#flyTo)

**Comment by lucaswoj** [comment]
On further thought, I think we should focus our energies on #2801 / #3583 rather than iterating on the existing `fitBounds` interface.
