### ISSUE TITLE
Enable property functions for "minzoom", "maxzoom", and "visibility"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#4288]
While neither layout nor paint properties, these style properties would benefit from supporting property functions. This would give style designers more control over what type of features are visible at different zoom levels while getting optimal performance and label placement. 

Vaguely related to #4160

**Comment by jfirebaugh** [comment]
Expressions are now allowed in `filter`, making it just as powerful as property function or expression-enabled `minzoom`/`maxzoom`/`visibility`.
