### ISSUE TITLE
Friction in Studio Tileset page UX

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4292]
I've been using the Tileset page (ie, /studio/tilesets/user.tilesetid) a bit recently and wanted to give some feedback on UX issues I keep running into.

### Title

At the top of the page is a title (eg "CLUE_Blocks-crid3f"). What confuses me:

1. What this title represents (is it just the first layer in the tileset?)
2. How it is generated - where does crid3f come from?
3. Why I can't change it

### Layers

I now know that next is a list of layers, and there's the phrase "This layer contains..."  but somehow I never really grasp that the grey box represents a layer – it's all just a bit too implicit. 

Usually what happens is there is only one layer in my tileset (that's the case the vast majority of the time, for user-uploaded data, right?) So there's one grey box, it has a name like "CLUE_Blocks-crid3f", and I think that's the ID for the tileset.

### Map ID

On the right, under the heading "Map ID" is the tileset ID: "cityofmelbourne.3viud7am".

1. The term "Map ID" seems confusing and maybe wrong? Surely it's the ID of the tileset. 
2. It's confusing to me as a user why the ID here doesn't match the title of the page.
3. I wish I could change the ID.
4. It's not obvious from here what I do with this ID. IMHO, writing it as "mapbox://cityofmelbourne.3viud7am" would be clearer and lead me in the right direction.

### Opaque

Frustratingly, there's no way to see anything inside the tileset, other than the names of the attributes. It would be great if there was some representative data for each attribute (eg, the most common values), and an interactive map. There's a static map at the top of the page, but its position means I don't often notice it, and depending on the data, the generated image isn't always helpful, especially on a pure black background. An overlay over mapbox-dark might be clearer.

### No path to mapbox-gl-js

There's a great button to take you into adding it to a Studio style. To add it to a dynamic style I usually find myself fumbling around, trying to remember what is a style layer ID, what's a source ID, and what's a tileset layer ID - and the subtle difference in syntax between `map.addSource('myid', { ...definition... })` and `map.addLayer({id: 'myid', ...definition...})`

Could I suggest that you spit out some boilerplate code that the user can copy and paste? Like:

```
map.addSource('mysource', {
  type: 'vector',
  url: 'mapbox://cityofmelbourne.3viud7am'
});
map.addStyle({ 
  id: 'mylayer',
  source: 'mysource',
  'source-layer': 'CLUE_Blocks-crid3f'
  type: 'line',
  paint: {
    'line-color': 'lightblue'
  }
});
```

That short piece of code would reduce a lot of friction, and spell out clearly the relationship between the tileset ID, its URL, its layer ID(s), and the source ID and layer ID you give it in mapbox-gl-js. You could maybe hide it behind a "Use in Mapbox-GL-JS" button.

**Comment by samanpwbb** [comment]
@stevage thanks for this thoughtful feedback! I'm tracking these requests in our internal Mapbox studio issue queue 👍
