### ISSUE TITLE
Option to disable zooming outside of map when renderWorldCopies is false

### ISSUE THREAD

**Issue by shotor** [mapbox/mapbox-gl-js#4293]
When `renderWorldCopies` is set to false and you zoom out far enough, you see grey around the map:

![image](https://cloud.githubusercontent.com/assets/6153419/23067861/6c61c3ec-f521-11e6-9053-635b2ddd947d.png)

Screenshot is a bit unclear, but I've zoomed out then dragged the map to the left. The grey area is the background of my webpage.

I'd like to lock the zoom when it reaches the last zoom level where the map fits.

I tried `maxBounds`

```
          maxBounds: [
                [-180, 90],
                [180, -90]
          ],
```

but it just caused the map to flicker and then hide itself. `minZoom` doesn't quite work as well.

I'd rather not resort to something like calculate how much someone can zoom then disabling the zoom on scroll.

Is there another way to achieve this, or can such a function be implemented?

**Comment by mollymerp** [comment]
I think the problem is that your maxBounds are not in [sw, ne] order – when I created an example w  `maxBounds: [[-180,-90],[180,90]]` it worked well. 

https://jsfiddle.net/jb6ngpf5/1/

Please re-open if your issue persists

**Comment by shotor** [comment]
Thanks @mollymerp, I totally missed that.

However it's still possible to drag the map vertically out of range. Do you know if there's some way to "clamp" dragging vertically?

**Comment by BoyBouw** [comment]
Had the same issue as mentioned above by shotor. "Fixed" it currently by setting my bounds to -180, -85, 180, 85. Hope this helps others

**Comment by matths** [comment]
Amazing, I have the same problem as described by @shotor in2017 and the strange workaround from @BoyBouw from 2020 is working for me, but I have to use -179, -85, 179, 85 instead. Can't find an issue or pull request for that.
