### ISSUE TITLE
populatePaintArray(...) throws "Cannot read property 'resize' of undefined"

### ISSUE THREAD

**Issue by ivanakimov** [mapbox/mapbox-gl-js#4294]
MapboxGL v0.32.1
Chrome 56.0.2924.87 (64-bit)
macOS Sierra v10.12.2

### Steps to Trigger Behavior

It's hard to reproduce as I have two Chrome browsers, one is loading the map just fine, another is throwing this (sorry I blanked out the source js as it's bundled and minified with other code; this is on our customer's browser so I don't have direct access):

![sn](https://cloud.githubusercontent.com/assets/1404596/23078409/7e2b1412-f4fd-11e6-8acd-b693de013474.jpg)

Traced the error to this @ <https://github.com/mapbox/mapbox-gl-js/blob/master/src/data/program_configuration.js#L179>:

```
...
populatePaintArray(layer, paintArray, paintPropertyStatistics, length, globalProperties, featureProperties) {
    const start = paintArray.length;
    paintArray.resize(length);
...
```

I realize I'm not providing a reproducible scenario, but is there any case where `paintArray` can be `undefined`?

**Comment by ivanakimov** [comment]
Has anyone had time to take a look at this? Maps still do not load...

**Comment by mollymerp** [comment]
@ivanakimov thanks for reporting your issue – I have not been able to reproduce this issue, so its hard to diagnose the problem. Can you provide a minimal test case of the code that is breaking on some browsers so we can take a closer look?

**Comment by ivanakimov** [comment]
@mollymerp I can give you access to the implementation that's breaking. Like I said, I have two identical browsers, and it seems to be breaking in one and not the other, so yes -- it is hard to reproduce. Where can I send a private link (the implementation is bundled with a bunch of other code)?

**Comment by ivanakimov** [comment]
Looks like somewhere between `0.32.1` and `0.34.0` this has been fixed.

**Comment by ivanakimov** [comment]
Reopening.

The bug is back on `0.36.0` on `Chrome 58.0.3029.81`.
The map **does not load** at all:

![bug](https://cloud.githubusercontent.com/assets/1404596/25452165/748ee2f6-2a79-11e7-82f5-337d6ff95b07.png)

**Comment by mollymerp** [comment]
@ivanakimov can you please provide a test case on jsbin ?

**Comment by ivanakimov** [comment]
@mollymerp this happens on some machines and not others, so I'm not able to create an isolated test case where this happens consistently. The map does not load on this page tho: http://www.sprayervalves.com/dealers/

**Comment by ivanakimov** [comment]
Maps not loading. From one of my customers:

> Hello, we're starting to see an increase in people complaining that the map isn't working. The best that we get from them is that it hangs forever. Despite using different browsers and devices on the same network, they still can't see anything. We get 2-3 of these complaints a day.

Isn't anyone else noticing this issue? cc @mourner @jfirebaugh

**Comment by mourner** [comment]
@ivanakimov I haven't been able to reproduce it yet. We still need a consistent test case to fix this.

**Comment by ivanakimov** [comment]
@mourner I just got another customer with the same issue, but on my end it works. Not sure how to give you guys a consistent test case other than the URL. Isn't it possible to at least do type checking on that line to avoid crashing?

**Comment by mourner** [comment]
@ivanakimov I don't think there's any way for us to fix this unless you find a way to set up a consistently reproducible test case. That might involve a lot of trial and error.

**Comment by Gp2mv3** [comment]
Personally I see it when OpenGL cannot be initialized. I have some occurences on Chrome 49 and OS X 10.6.

**Comment by vKongv** [comment]
It is caused by WebGL is disabled in certain machines especially for older chrome browser. Some of our customers are having this issues and we able to capture the errors from Raygun and some stack trace.

In order to simulate it on your Chrome browser, you can download [Disable WebGL Plugin](https://chrome.google.com/webstore/detail/disable-webgl/nlapleiepodflfbclacdhmbldadobpah) from chrome store and reload the map again. It should throw the error.
