### ISSUE TITLE
Add custom icons with Markers

### ISSUE THREAD

**Issue by demitrioskross** [mapbox/mapbox-gl-js#4298]
How can I add custom icons with Markers with this same mapbox code (https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/)? Or add more markes and different pictures?

**Comment by jfirebaugh** [comment]
Hi @demitrioskross. Thanks for using Mapbox. This issue tracker is for coordinating development of Mapbox GL JS via bug reports and feature requests. It's not a support forum.

**Comment by andrewharvey** [comment]
@demitrioskross You could try http://gis.stackexchange.com/questions/tagged/mapbox-gl-js
