### ISSUE TITLE
mapbox-gl-directions.js: Object dosen´t support property or method 'assign on IE11

### ISSUE THREAD

**Issue by Liverson** [mapbox/mapbox-gl-js#4316]
Hello,

on IE11 there is an error when i use mapbox-gl-directions.js to set waypoints on my map.
On all other browsers incl. Edge the waypoints are shown fine.
I tested with mapbox-gl-directions v3.0.3 and 3.1.1

I got the following error message in the console:
_Object dosen´t support property or method 'assign'_
_mapbox-gl-directions.js (6518,7)_

Breakpoint in mapbox-gl-directions.js:
_this.originInput = new _geocoder2.default(Object.assign {} ...._

When i comment out the following code, the page loading without errors.
Seems map.addControl(directions) triggers the issue

```
var directions = new MapboxDirections({
        accessToken: mapboxgl.accessToken,
        unit: 'metric',
        profile: 'cycling',
        controls: false,
        interactive: false
    });

    map.addControl(directions);
```
Greets,
Oliver

**Comment by lucaswoj** [comment]
Thanks for the bug report Oliver! There is a separate repo for tracking issues with `mapbox-gl-directions`. I just migrated this issue over for you 😄 https://github.com/mapbox/mapbox-gl-directions/issues/123
