### ISSUE TITLE
Overzoom raster tiles when no data is available

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#4318]
Counterpart to https://github.com/mapbox/mapbox-gl-native/pull/8164

Directly loading a map that requires overzooming raster tiles only shows black at **z16.50**:
https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v9.html?title=true&access_token=ACCESS_TOKEN#16.5/50.11690/-122.95461
![out](https://cloud.githubusercontent.com/assets/52399/23217554/f96b3420-f919-11e6-8cff-cd3ff7d9cd3b.png)

Directly loading the map at **z16.49** instead of **z16.50** shows the satellite tiles (and you can now zoom in beyond z16.50 and still see tiles in this location), but when panning no new tiles will be loaded:
![out2](https://cloud.githubusercontent.com/assets/52399/23217617/34bfb6c2-f91a-11e6-8005-2628b09b0a25.png)

**Comment by andrewharvey** [comment]
This is the issue reported in #4257
