### ISSUE TITLE
LineStrings rendered with fill type are not clipped as polygons

### ISSUE THREAD

**Issue by scottsfarley93** [mapbox/mapbox-gl-js#4323]
Hello,

I am reporting a bug that causes fill layers to render incorrectly at high zoom levels in the polar regions. The geojson source is valid according to geojsonlint.com and shows up properly at zoom levels less than three. At zoom levels higher than three, the polygons get jagged and extend off the screen. Progressively increasing zoom makes the problem worse. 

![good-z 2 5](https://cloud.githubusercontent.com/assets/10917266/23266402/4f37b052-f9ad-11e6-9eab-90075d76efc8.png)
*Good*: Zoom = 2.5

![bad z 3](https://cloud.githubusercontent.com/assets/10917266/23266417/5b2de318-f9ad-11e6-8347-ef2ce9564582.png)
*Bad*: Zoom = 3

![bad-z 4](https://cloud.githubusercontent.com/assets/10917266/23266562/c2f83516-f9ad-11e6-81fb-fdc9a4a6ac98.png)
*Worse*: Zoom = 3.9

A similar problem occurs in the Antarctic region as well. I suspect that the problem may have to do with being in the high latitudes.

The problem does not exist when the shapes are rendered as ```line``` type instead of ```fill```. 

[jsbin](https://jsbin.com/xotaposezu/edit?html,js,output)

**mapbox-gl-js version**: v0.32.1

**Comment by averas** [comment]
I thinks the problems stems from the fact that your GeoJSON contains MultiLineStrings, not Polygons. When you zoom in parts of these MLS end up outside the viewport and are clipped.
I converted your MLS's to Polygons which renders fine: [jsbin](https://jsbin.com/caxugucade/1/edit?html,js,output)

I would argue, however, that the rendering of MLS for type <code>fill</code> is not intuitive.

**Comment by mourner** [comment]
I see no way to do this technically because GeoJSON is sliced into tiles (in geojson-vt) independently of the style used in GL JS. On the GL JS side, this is working as designed.
