### ISSUE TITLE
Tiles cache

### ISSUE THREAD

**Issue by pronebird** [mapbox/mapbox-gl-js#4326]
Hi,

Currently when map screen shows up I see emptiness for like 5 seconds, then the map starts zooming out slowly showing blank spaces for a second until all tiles are loaded. 

At the same time bunch of XHR requests run in background, some of them hit browser cache, some get cancelled but it does not really help to provide smooth experience. 

Even if all of the tiles are cached by browser it simply takes way too long for Mapbox GL to fetch images via XHR producing blank tiles when camera zooms out and moves around.

Is there any way to cache tiles in local storage, on disk or in memory to improve the smoothness and generally decrease amount of traffic?

**Comment by remster** [comment]
I use service workers (where available) quite successfully.

**Comment by lucaswoj** [comment]
We do not support or plan to support an offline mode for GL JS. It will be easier to implement your own offline mode once we implement [custom source types](https://github.com/mapbox/mapbox-gl-js/projects/2).

Your performance concerns will be addressed by #3676. 

Previously https://github.com/mapbox/mapbox-gl-js/issues/2600 https://github.com/mapbox/mapbox-gl-js/issues/812

**Comment by pronebird** [comment]
@remster any examples of how to add caching for mapbox-gl with existing infrastructure?

**Comment by remster** [comment]
@pronebird yes. [Here's](https://bitbucket.org/remek_zajac/zikes-web/src/446027a01a279e25de127a9d9a07e83c557f4a48/zikes-ui/src/main/webapp/app/mobile/serviceWorker.js?at=master&fileviewer=file-view-default#serviceWorker.js-182) the relevant bit of the service worker code. 

[Here's](https://bitbucket.org/remek_zajac/zikes-web/src/446027a01a279e25de127a9d9a07e83c557f4a48/zikes-ui/src/main/webapp/app/scripts/lib/tileCacheDb.js?at=master&fileviewer=file-view-default) the IndexedDB db code.

In essence, whenever a call is made for a z/x/y.vector.pbf asset, it is redirected to the database first and then to the network.

For working demo, direct your Android phone to http://zikes.website/ and follow through .. it's a work in progress as i type this, so please forgive that it may not work straight of the bat. I will listen to this thread for questions. 

If you find this info useful, and as a form of gratitude, I will ask for a 'like' or 'tweet' from http://zikes.website/

@lucaswoj : you may remember me (a fellow countryman if i understand correctly) - if offline tiles are the sole motivation for custom source types, you may want to reconsider. All [but Safari support service workers](https://jakearchibald.github.io/isserviceworkerready/) as i type this, and service workers arguably solve this problem at a lower layer.

**Comment by pronebird** [comment]
Wow thanks @remster for sharing this!

**Comment by pronebird** [comment]
@remster how do you override fetch? Based on mapbox source they use XHR in `utils.js`. I don't see how I can intercept XHR requests.

**Comment by remster** [comment]
[service workers](https://developers.google.com/web/fundamentals/getting-started/primers/service-workers) are below XHR - you intercept EVERY fetch from all the assets.

self.addEventListener('fetch', function(event) {
    event.respondWith(/*HERE*/);
});

**Comment by pronebird** [comment]
@remster oh wow thanks for the link. I just realized you were talking about service workers, not web workers.

**Comment by pronebird** [comment]
@remster Thanks again. I found your implementation unnecessary complex for my needs, so to conclude I resolved this with CacheStorage that simply caches all requests to `tiles.mapbox.com` and `api.mapbox.com`. The map feels much faster now!

**Comment by MADHUSUDHANRAO527** [comment]
Android Mapbox : How to Load tiles from sd card of the mobile[offline]

I am new to mapbox android.I am able to place tiles from json. But How can i load tiles from internal storage/SD card of the mobile.

I am using below code for local storage - which is not working

RasterSource chicagoSource = new RasterSource("chicago-source", new TileSet("tileset", "asset://" + Environment.getExternalStorageDirectory().getAbsolutePath()
                        + "/OverlayTiles/{z}/{x}/{y}.png"));
                mapboxMap.addSource(chicagoSource);

                RasterLayer chicagoLayer = new RasterLayer("chicago", "chicago-source");
                mapboxMap.addLayer(chicagoLayer);
I am able to load from project assets folder - using below code, it might help someone

RasterSource chicagoSource = new RasterSource("chicago-source", new 
TileSet("tileset","asset://OverlayTiles/{z}/{x}/{y}.png"));
                        mapboxMap.addSource(chicagoSource); 
mapboxMap.addSource(chicagoSource);

                RasterLayer chicagoLayer = new RasterLayer("chicago", "chicago-source");
                mapboxMap.addLayer(chicagoLayer);

**Comment by lusicsmusics** [comment]
> We do not support or plan to support an offline mode for GL JS. It will be easier to implement your own offline mode once we implement [custom source types](https://github.com/mapbox/mapbox-gl-js/projects/2).
> 
> Your performance concerns will be addressed by #3676.
> 
> Previously #2600 #812



> we implement [custom source types](https://github.com/mapbox/mapbox-gl-js/projects/2).

what is your mean Sir about this :
"we implement custom source types."
i need an implement caches tiles that can be used in offnet

**Comment by allthesignals** [comment]
If MapboxGL uses service workers, why don't I see them in the Chrome inspector under the application tab under Service Workers? 

I ask because I have a related issue: I need to intercept the `fetch` request. To do this, I'm using PretenderJS, which should override the default XMLHttpRequest with a mock object. However, the fetch for new vector tiles still isn't being intercepted. I'm not sure why. 

One possibility is that the XMLHttpRequest object in the service worker scope isn't being overridden.

That leads me to want to try to listen to the service worker fetch event, however, where do I use `this.addEventListener('fetch')`? I would like to listen to this event but I don't have direct access to these service workers (as far as I understand).

**Comment by ryanhamley** [comment]
>If MapboxGL uses service workers, why don't I see them in the Chrome inspector under the application tab under Service Workers?

GL JS uses web workers, not service workers so they wouldn't show up in that tab. You can see objects that were downloaded and processed in web workers in the Network tab and you can see activity in the workers if you do a profile in the Memory tab.

Vector tiles are downloaded and parsed in the web workers. I'm not familiar with PretenderJS but presumably it's having trouble accessing the scope of the worker threads. I believe this is something you'll have to clarify with the maintainers of that library and/or ask on StackOverflow.
