### ISSUE TITLE
"Paused before potential out-of-memory crash" Google Chrome Canary

### ISSUE THREAD

**Issue by Carpetfizz** [mapbox/mapbox-gl-js#4330]
I'm running [this](https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/) example in **Google Chrome**  58.0.3023.0 (Official Build) canary (64-bit) and I get the following error after interacting with the map a little bit:

http://imgur.com/a/slyCZ

**Comment by mourner** [comment]
Does it happen on any other examples for you, or just this one?

**Comment by jczaplew** [comment]
I get this on map load on a project I'm working on

**Comment by Carpetfizz** [comment]
I don't get it on any of the examples on mapbox.com, but just the ones I actually implement.

**Comment by mourner** [comment]
@jczaplew any other hints to help us track this down? Does it happen with older versions? Does it happen only on your project or some of our official examples? Does it happen on a specific machine, or on any machines with Chrome Canary? OS X, Linux, Windows, or all?

**Comment by Carpetfizz** [comment]
@mourner I can test it on another Mac when I get home

**Comment by jczaplew** [comment]
@mourner 

**My system:** OS X 10.12.3 with Canary 58.0.3026.3 (64-bit)
**GL JS versions tested:** 0.28.0, 0.29.0, 0.30.0, and 0.32.1

I was also able to replicate the problem with [this example](https://www.mapbox.com/mapbox-gl-js/examples/). Oddly, it seems only to occur about 50% of the time, and in order to trigger it the developer tools must be open.

**Comment by mourner** [comment]
Thanks! I was able to replicate. Also only when the DevTools are open. The error breaks on random pieces of code (different each time), but always in the worker when parsing a vector tile. I wonder if this is something that can be fixed on our side, or simply a Chrome bug (couldn't find anything related in the tracker though).

**Comment by mourner** [comment]
Another observation: when you click "Resume script execution", the map continues to work without any issues. Given that it says "**potential** out-of-memory crash", I'm inclined to think that this is Chrome DevTools being overeager about detecting memory issues and having a false positive.

**Comment by jczaplew** [comment]
I also noticed that clicking "Resume script execution" resulted in the map working as expected. The inconsistency in the breakpoint, as well as the seeming randomness of whether or not an error is thrown at all is really odd. Hopefully it will be fixed in tomorrow's version of Canary?

**Comment by mourner** [comment]
Since this doesn't affect end users and seems to be on the Chrome side, let's close the issue for now and wait for good news from the Chrome team.

**Comment by coodoo** [comment]
Just a quick note that I had report this to the Chrome team, hopefully they will have it fixed ASAP.

**Comment by ChiefKleef** [comment]
Getting the same error now in  mapbox-gl v0.38.0 in Chrome and Opera when dev tools is open, rolled back to 0.36.0 and it's working without the error
