### ISSUE TITLE
No LogoControl in mapboxgl object

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4332]
I'm trying to add the required wordmark, using mapbox-gl-js 0.32.1:

```
map.add(new mapboxgl.LogoControl());
Uncaught ReferenceError: LogoControl is not defined
```

All the other user interface classes referred to in the doc exist on the mapboxgl object, but not this one. Am I doing something wrong?

Additional suggestion: the text [here](https://www.mapbox.com/help/attribution/) should include code that you can copy/paste to meet the wordmark requirements. Probably the examples should include it too.

**Comment by jfirebaugh** [comment]
`LogoControl` isn't in a versioned release yet, and when it is released, it will be added to the map and shown automatically when required; you won't need to add it manually.

**Comment by stevage** [comment]
Ok, thanks. I guess you're aware but at the moment there's a lot of contradiction:

- https://www.mapbox.com/help/attribution/ says you need a wordmark
- https://www.mapbox.com/mapbox-gl-js/api/#LogoControl says how to add the wordmark, but it doesn't work
- https://www.mapbox.com/tos/ makes no direction mention of a wordmark, but refers to attribution requirements.

Might be worth making clearer exactly what "our maps" means in the attribution doc. Is a wordmark required when using Mapbox-GL-JS with no Mapbox data, for instance.

**Comment by jfirebaugh** [comment]
> * https://www.mapbox.com/mapbox-gl-js/api/#LogoControl says how to add the wordmark, but it doesn't work

Removed. This was published in error.

> * https://www.mapbox.com/tos/ makes no direction mention of a wordmark, but refers to attribution requirements.

The workmark is part of the attribution requirements, as detailed in https://www.mapbox.com/help/attribution/, which the ToS link to.

> Is a wordmark required when using Mapbox-GL-JS with no Mapbox data, for instance.

This is covered in the help document, in the section "When do you have to provide attribution?"

**Comment by stevage** [comment]
Ah, thanks. Also, from the help page:

>you have build[sic] your map with Mapbox Studio or another Mapbox tool

What's "another Mapbox tool" meant to cover? Just Mapbox Studio Classic, or also TippeCanoe and maybe other tools?
