### ISSUE TITLE
Filters on LineString not working as expected

### ISSUE THREAD

**Issue by Carpetfizz** [mapbox/mapbox-gl-js#4339]
Hello,

I'm trying to render two line strings on my map, each with a different color. I've tried the following different Geojson files with the corresponding filters when I add the layers, to see if I can select them properly. None of them are working.

[Geojson Try 1](https://gist.githubusercontent.com/anonymous/f6a6af35fb22578f2c75fa5907234757/raw/e8bfda66da18159125291ea4b1035c94bf7fe379/map.geojson)

```
this.map.addLayer({
	"id": key+"-line",
	"type": "line",
	"source": key,
	"filter": ["all", ["==", "$type", "LineString"], ["has", "history"]],
});
```

[Geojson Try 2](https://gist.githubusercontent.com/anonymous/6122d100eae279bb0a01bbee5845689a/raw/55e4d08e43d12f837f0d6fd6a075a78fed809896/map.geojson)

```
this.map.addLayer({
	"id": key+"-line",
	"type": "line",
	"source": key,
	"filter": ["all", ["==", "$type", "LineString"], ["==", "history", "true"]],
});
```

The [docs](https://www.mapbox.com/mapbox-gl-js/style-spec/#types-filter) for the filter spec says

> A key must be a string that identifies a feature property

What property is it referring to? The actual `Feature.properties` dictionary, a JSON property, and if so of what element?

Thanks for any clarification.

**Comment by jfirebaugh** [comment]
The GeoJSON in your second example is correct, but the last part of the filter needs to use `true`, not `"true"`. The former is a boolean value, as in the GeoJSON, and `"true"` is a string, which is not considered equal to `true`.
