### ISSUE TITLE
map.fitBounds() throws Uncaught Error on small screens

### ISSUE THREAD

**Issue by wfendler** [mapbox/mapbox-gl-js#4344]
**v0.32.1**:

### Steps to Trigger Behavior

I think it's using a small map to plot a wide range of points then calling fitbounds on those points that causes the error. It sounds like this is a very similar problem here https://github.com/mapbox/mapbox-gl-js/issues/4281#issuecomment-280227028 but I updated my code to match the answer at the end (without turf.js) and it still doesn't work.

[Demo here](https://jsbin.com/vuremeqomo/edit?css,js,console,output)

### Expected Behavior
Fitbounds would work as expected on smaller maps.

### Actual Behavior

`fitbounds()` works on larger screens but throws an error below ~780px. This is a breakpoint which changes the map from 400px tall to 300px tall (~200px in the jsfiddle above). At this breakpoint and lower I get the following error:

```
Uncaught Error: failed to invert matrix
    at Transform._calcMatrices (transform.js:441)
    at Transform.prototypeAccessors.zoom.set (transform.js:114)
    at e._ease.moving (camera.js:715)
    at e.<anonymous> (camera.js:777)
    at Object.exports.timed (browser.js:43)
    at e.i._ease (camera.js:776)
    at e.i.flyTo (camera.js:709)
    at e.i.fitBounds (camera.js:340)
    at Map.fitBounds (application.js:15477)
    at new Map (application.js:15418)
```

And from there any time I interact with the map after the error above it gives me:
```
Uncaught Error: Invalid LngLat object: (NaN, NaN)
    at new LngLat (lng_lat.js:26)
    at Transform.coordinateLocation (transform.js:270)
    at Transform.pointLocation (transform.js:247)
    at e.unproject (map.js:508)
    at h (bind_handlers.js:140)
    at HTMLDivElement.a (bind_handlers.js:75)
```

**Comment by mollymerp** [comment]
Hi @wfendler ,
Thanks for reporting this issue. This happens when the requested map bounds cannot fit on the canvas at the given zoom, padding, center etc. In your case, the bounds you have in your example represent an area too large to fit in the canvas at the lowest zoom level (0).

We've added a better error message that will ship in the next release so hopefully this wont be as confusing in the future: https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/camera.js#L383-L386

**Comment by wfendler** [comment]
Thanks for the quick reply @mollymerp!

To make sure I understand, my map canvas is too small or has the wrong dimensions to fit it the set of markers? Or is the way I'm handling my markers vs. the bounds object incorrect?

Either way, sounds like the error message will be better - that's great - but will it continue to break the map entirely? Is there any chance we could get the fitBounds to get it close without failing entirely in this scenario? With some fluid/responsive map sizes it would be great to have mapbox-gl-js give a better error _and_ get the most close to fitting! I'm sure there are many things I could missing though on why that might be a bad idea.

**Comment by mollymerp** [comment]
> To make sure I understand, my map canvas is too small or has the wrong dimensions to fit it the set of markers? Or is the way I'm handling my markers vs. the bounds object incorrect?

You're not doing anything wrong per se, its just that the bounds in your example span California to Denmark and the map tiles at the lowest zoom level can't fit that area into 200px. At zoom 0 the width of the world is about 512px (one tile wide) and we can't make it smaller than that.

It shouldn't break the map anymore – it will just fire a warning and `return` out of the function.

**Comment by wfendler** [comment]
Totally makes sense, thanks for the explanation!

Made my map taller on mobile. ✅

**Comment by pea** [comment]
I'm having a similar issue except Mapbox should be able to fit my coords in the container. My test shows that if the coords are the width of Colorado apart Mapbox produces this error message. If the coords are almost on top of each other the fitting works.

`
var coords = [[-109.100586, 38.970466], [-102.073798, 38.897909]]; // False
var coords = [[-109.100586, 38.970466], [-109.100586, 38.970467]]; // True
`

Maybe I've just missed something(?)

Demo: https://jsfiddle.net/8yxh8xmt/32/

**Comment by mollymerp** [comment]
@pea – when using an array of cooridnates as your `LngLatBoundsLike`, the two points must be the [SW, NE] corners of the extent, in that order. Your coordinates in the first example are SE, NW corners.
`var coords = [[-109.100586, 38.897909], [-102.073798, 38.970466]]` should work

**Comment by pea** [comment]
Thanks @mollymerp. It turned out that my points were a mix of NE,SW and SW,NE. I just used some code to swap them around in the end. (I would've followed up but I couldn't find this issue post again 🙄)

**Comment by ryanhamley** [comment]
@pdegnan The docs for `fitBounds` and `setMaxBounds` define the `bounds` parameter as being of type [`LngLatBoundsLike`](https://www.mapbox.com/mapbox-gl-js/api/#lnglatboundslike). The documentation for `LngLatBoundsLike` notes that the order must be `[sw, ne]`. Maybe explicitly calling this out in the example would be helpful though. Thanks for the feedback.
