### ISSUE TITLE
Rename original circle-* properties to circle-fill-*

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#4346]
With a style like this:

```
{
  ...
  'circle-fill': 'blue',
  'circle-stroke-color': 'black',
  'circle-opacity': 0.1
}
```

it's easy to be misled into thinking that the opacity of the whole circle (fill plus stroke) is being set to 0.1. Whereas the opacity setting only applies to the fill, and the stroke has its own opacity setting, `circle-stroke-opacity`. (I just ran into this minor gotcha). 

Possible suggestions:

- rename it to `circle-fill-opacity`
- document it more clearly (`The opacity at which the circle will be drawn.` &rarr; `The opacity of the circle's filled interior.`, plus maybe some comment about the possible interaction between this property and the alpha channel of the fill color.)
- change the behaviour so that it does affect stroke. (Probably not a good idea...)

**Comment by gmaclennan** [comment]
Yes I was just using this property today and was not clear until I tested rendering that it only applied to the fill.

**Comment by serialc** [comment]
Makes sense. Possibly `circle-opacity` should override both `circle-fill-opacity` (if adopted) and `circle-stroke-color`.

**Comment by jfirebaugh** [comment]
`circle-opacity`, `circle-color`, `circle-radius`, etc. were named before there were any stroke properties. If we were to rename one to `circle-fill-*`, we'd want to rename them all, and it would be a breaking style spec change.

**Comment by stevage** [comment]
`circle-radius` also affects the stroke, though right?

**Comment by jfirebaugh** [comment]
Depends what you mean by "affects". I suppose you could say it affects the stroke in the sense that the stroke moves outward if you increase `circle-radius`. But `circle-radius` is exclusive of `circle-stroke-width`; the stroke lies entirely outside the inner fill.

**Comment by stevage** [comment]
Right. "circle-fill-opacity" sets the opacity only of the fill, while "circle-radius" sets the radius of the filled interior, and also the radius of the stroke outline...so calling it "circle-fill-radius" seems incorrect.

**Comment by mourner** [comment]
I agree that keeping `circle-radius` seems less confusing. I'd prefix the fill-specific properties though.

**Comment by mourner** [comment]
I agree that keeping `circle-radius` seems less confusing. I'd prefix the fill-specific properties though.

**Comment by jfirebaugh** [comment]
Closing here; see #6584.
