### ISSUE TITLE
Navigation Control Compass - Style mismatch between constants/css.js and dist/mapbox-gl.css

### ISSUE THREAD

**Issue by steinarn** [mapbox/mapbox-gl-js#4353]
The navigation control - compass -, is not being rendered.

```
import mapboxgl from "mapbox-gl/dist/mapbox-gl";
...
this.map.addControl(new mapboxgl.NavigationControl(), "top-right");
```
(bundled with webpack)

Outputs following html: 
`<button class="mapboxgl-ctrl-icon mapboxgl-ctrl-compass" type="button" aria-label="Reset North"><span class="arrow" style="transform: rotate(0deg);"></span></button>
`
adding following styles (from constants/css.js) to `<head>`:
`.mapboxgl-ctrl-icon.mapboxgl-ctrl-compass > div.arrow { ....  } `

css.js should be updated to (from dist/mapbox-gl.css):
`.mapboxgl-ctrl-icon.mapboxgl-ctrl-compass > span.arrow { ... }`

**Comment by jfirebaugh** [comment]
It looks like the file `constants/css.js` is out of date. This is not a file provided by mapbox-gl-js. The source file provided by mapbox-gl-js is [`mapbox-gl.css`](https://github.com/mapbox/mapbox-gl-js/blob/f44df00431bf085fb5ba2a6a3b21f3392bb532ca/dist/mapbox-gl.css#L94), which has the correct `span.arrow` selector. Please ensure you have the latest version of this file.
