### ISSUE TITLE
Custom tiles URL triggers Uncaught DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL

### ISSUE THREAD

**Issue by JamesMilnerUK** [mapbox/mapbox-gl-js#4356]
### Steps to Trigger Behavior

 1.  Create your own ungzipped tiles, in a folder i.e. : /tiles/
 2.  

```javascript

    var vectortiles = "UK"
    var url = "/tiles/{z}/{x}/{y}.pbf";
    console.log(url);

    mapboxgl.accessToken = 'pk.eyJ1IjoiamFtZXNtaWxuZXIiLCJhIjoiY2lsMm96djd1MDBjYndnbTVmajAxeHByaiJ9.mw4lltZ8qZjJHaJwbnN5Yw';
    var simple = {
        "version": 8,
        "sources": {
            "tiles": {
                "type": "vector",
                "tiles": [url]
            }
        },
        "layers": [
            {
                "id": "tiles",
                "type": "fill",
                "source": "tiles",
                "source-layer": "tiles",
                "filter": ["==", "$type", "Polygon"],
                "paint": {
                    "fill-color": "#3887be"
                }
            }
        ]
    };

    var map = new mapboxgl.Map({
        container: 'map',
        style: simple,
        zoom: 5,
        center: [-0.5, 51.0]
    });

    map.addControl(new mapboxgl.NavigationControl());
```

### Expected Behavior

Tiles loading error free. The tiles are already working with MapBox Studio using the MB Tiles, and using the raw files with Leaflet.VectorGrid:

![screen shot 2017-03-02 at 14 11 14](https://cloud.githubusercontent.com/assets/8822075/23510593/20105f68-ff52-11e6-8dee-c8c215a114df.png)

### Actual Behavior

You recieve the error:

`Uncaught DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL`

Explicitly:

![screen shot 2017-03-02 at 14 08 40](https://cloud.githubusercontent.com/assets/8822075/23510505/d2d1c872-ff51-11e6-80f4-5877ab8db69d.png)

**Comment by JamesMilnerUK** [comment]
From the spec docs:
`A URL to a TileJSON resource. Supported protocols are http:, https:, and mapbox://<mapid>.`

If developing locally just append a http:// to the front of the URL or it won't work.

**Comment by Bexanderthebex** [comment]
how to resolve this? I deployed my angular app and used an nginx file server to serve my file and I still receive this error

**Comment by nandodutra** [comment]
Hi there!

I'm with this same issue, trying use Put method on url "http://localhost:3000/establishment/6", but always return this error: **ERROR DOMException: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL**

Someone knows how solve this issue? Thank's about your support!
