### ISSUE TITLE
mapbox:// url in style.sources

### ISSUE THREAD

**Issue by gpbmike** [mapbox/mapbox-gl-js#4360]
I'm having trouble using a mapbox:// formatted url in styles.sources. It works fine if passed as a string to the style option.

**Works**
```
var map = new mapboxgl.Map({
  container: 'map',
  style: "mapbox://styles/3dr/citojzvev00002iov16tnpavi",
  center: [-74.50, 40], // starting position
  zoom: 2 // starting zoom
});
```

The above working example fetches json from `https://api.mapbox.com/styles/v1/3dr/citojzvev00002iov16tnpavi`.

**Does not work**
```
var map = new mapboxgl.Map({
  container: 'map',
  style: {
    "version": 8,
    "sources": {
      "raster-tiles": {
        "type": "raster",
        "url": "mapbox://styles/3dr/citojzvev00002iov16tnpavi",
        "tileSize": 256
      }
    },
    "layers": [{
      "id": "simple-tiles",
      "type": "raster",
      "source": "raster-tiles",
      "minzoom": 0,
      "maxzoom": 22
    }]
  },
  center: [-74.50, 40],
  zoom: 2
});
```

The above non-working example fetches from `https://api.mapbox/v4/styles.json` and 404s.

Is there another tile url format I should be using?

**Comment by jfirebaugh** [comment]
It looks like you are trying to use the [Static API](https://www.mapbox.com/api-documentation/#static) as a source for raster tiles rendered with Mapbox GL JS. Is there a particular reason you want to do this? It's an unusual use case, and as you noticed, using a `mapbox://` URL in that way is not supported. The typical use case for the Static API is to render static tiles for use with a map library other than Mapbox GL, such as Mapbox.js/Leaflet.

**Comment by gpbmike** [comment]
Sorry, pretty new to this stuff. It looks like my mapbox:// returns a mapbox style that I can use. I think I have enough info to go on now.

This work is so I can feed stuff into react-map-gl's mapStyle prop. That's why it's using the static api. It's all coming together now. Appreciate your response.
