### ISSUE TITLE
Grey maptiles when changing style in IE and Edge

### ISSUE THREAD

**Issue by shf123** [mapbox/mapbox-gl-js#4365]
**mapbox-gl-js version**:  0.32.1
It looks like the issue was introduced in version 0.22.0

### Steps to Trigger Behavior

 1. Go to https://www.mapbox.com/mapbox-gl-js/example/setstyle/ in Internet Explorer 11 or Edge
 2. Change map style to for instance "streets"
 3. Change map style back to "basic"
 4. Change map style back to "streets" 

### Expected Behavior
Map displays all tiles, and none of them are grey

### Actual Behavior
Many of the tiles are grey. 
Note: It did happen on 3 out of 6 computers we tested. In all the 3 failed cases a windows 10 OS was used, but Windows 10 was also used in cases there the bug did not happen.

![image](https://cloud.githubusercontent.com/assets/1443522/23546084/4921ab1c-fffe-11e6-9d4d-98bb8c76a676.png)

**Comment by janerivi** [comment]
This is a real drawback that would disrupt the user experience of a large portion of our users. The tiles get stuck in gray and only a reload of the page seems to get the tiles flowing again.

**Comment by anandthakker** [comment]
Thank you for reporting this issue, @shf123 

> It looks like the issue was introduced in version 0.22.0

Can you say more about this? What lead you to this conclusion?

Also: would you mind checking in the Javascript console after reproducing this bug to see if there are any error messages reported there?

**Comment by shf123** [comment]
@anandthakker I tested in different mapbox versions to see when the issue was introduced.

There are no error messages in the console.

**Comment by jfirebaugh** [comment]
I'm unable to reproduce the issue with IE 11.0.9600.18838, Update Versions: 11.0.48 (KB4047206).

**Comment by jfirebaugh** [comment]
→ #4623.
