### ISSUE TITLE
Raster tileset images appear to suffer from artifacting

### ISSUE THREAD

**Issue by prodjectOriented** [mapbox/mapbox-gl-js#4367]
**mapbox-gl-js version**: 0.32.1

### Steps to Trigger Behavior

 1. Upload tile images to Mapbox via Mapbox studio
 2. Pull down tile images as raster sources and display them on Mapbox map
 3. Observe images which appear to exhibit artifacting

### Expected Behavior
Observe images which may be down-sampled depending on zoom level, but do not exhibit degradation to the extent that it resembles noticeable artifacting

### Actual Behavior
Observe images which appear to exhibit artifacting

### Details
The artifacting in our case seems to be in the form of strange "zebra stripes" showing up in tile images returned from Mapbox - the raw source images we upload to Mapbox do not contain them.

We display raster tile sets as mosaics projected onto a Mapbox map. While the raster tileset exhibits artifacting, when we created a replica using the same source images but separate 3rd party image stitching software, the replica did not exhibit this artifacting.

**Tileset created from raster images returned from Mapbox:** 
http://www.screencast.com/t/XPBrjZNK

**Tileset created from raw source images using 3rd party stitching software:** http://www.screencast.com/t/91bhUACEXlBT

### Next Steps
I would like to:
1. See if there is anything we can do differently on our end to sidestep this issue moving forward
2. Raise this concern and get some feedback regarding whether there is a plan to work on this issue, and if so what the timeline would be like for resolution

**Comment by jfirebaugh** [comment]
@prodjectOriented Are these artifacts visible in the raw tiles from the Mapbox API, or only after those tiles are rendered with Mapbox GL? If they're visible in the raw tiles, then this isn't a bug in Mapbox GL, but rather in the backend processing. To further investigate that issue, we'd need you to contact Mapbox Support so one of our backend engineers can look into the issue.

**Comment by prodjectOriented** [comment]
@jfirebaugh These artifacts are visible in the raw tiles returned from the Mapbox API, e.g. image located at URI https://a.tiles.mapbox.com/v4/{orgId}/{z}/{x}/{y}@2x.webp

Since it sounds like this would indicate an issue in backend processing, I apologize for posting in the wrong issue thread - do you happen to know the best way I can get in touch with Mapbox support to investigate this issue in further detail?

**Comment by jfirebaugh** [comment]
Thanks for the clarification @prodjectOriented! Contact support [here](https://www.mapbox.com/contact/), and reference this issue.
