### ISSUE TITLE
Access key security issue?

### ISSUE THREAD

**Issue by divya1c** [mapbox/mapbox-gl-js#4369]
**mapbox-gl-js version**: v0.23.0

### Steps to Trigger Behavior

 1. Render a mapbox gl map (which gets tiles from mapbox servers)
 2. Go into the browser's network panel in console

### Expected Behavior
The access key for mapbox gl is not public.

### Actual Behavior
The access key is a parameter in the get request and easy for anyone to copy. So, anyone can get my access key and render their maps.

**Comment by jfirebaugh** [comment]
Hi @divya1c. This is expected behavior. [Here is our help document on the topic.](https://www.mapbox.com/help/rotate-access-token/)
