### ISSUE TITLE
Distribution CSS is not minified

### ISSUE THREAD

**Issue by jasonbarry** [mapbox/mapbox-gl-js#4370]
The distribution CSS is unminified: 
https://api.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.css

While the JS at the same location (w/ same file naming convention) is minified: 
https://api.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.js

**Comment by jasonbarry** [comment]
It would be nice to have a build process that takes the source CSS and minifies it to dist.

**Comment by jfirebaugh** [comment]
I don't think we're likely to implement this. The savings potential is very small when taking gzip content encoding into account; see https://github.com/mapbox/mapbox-gl-js/pull/4493#issuecomment-289170896

**Comment by PeterDaveHello** [comment]
I think the effort isn't so huge, not acceptable?
