### ISSUE TITLE
querySourceFeatures should accept an array of source layer IDs

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#4372]
Sometimes it may be desirable to query multiple source layers. Therefore, for consistency and parallelism with `queryRenderedFeatures`, `querySourceFeatures` should accept an _array_ of source layer IDs, rather than a single source layer ID.

**Comment by 1ec5** [comment]
Compared to calling querySourceFeatures() once per source, is there an advantage beyond concision, such as better performance?

**Comment by ansis** [comment]
> Compared to calling querySourceFeatures() once per source or queryRenderedFeatures() once per layer, is there an advantage beyond concision, such as better performance?

Nope, there is no performance advantage.
