### ISSUE TITLE
getLayer returns a layer but queryRenderedFeatures given a layer returns empty

### ISSUE THREAD

**Issue by Carpetfizz** [mapbox/mapbox-gl-js#4375]
I've added a few layers to the map and now I want to extract some features from it. I've made sure the layer exists by using this call

`console.log(this.map.getLayer(focus_key+"-point"));`

which prints:

`t {id: "8b4bc65b-4f60-43fd-bcde-fa63fa936479-point", metadata: undefined, type: "circle", source: "8b4bc65b-4f60-43fd-bcde-fa63fa936479", sourceLayer: undefined…}`

Right after, I want to get all the features in the layer so I'm calling:

`console.log(this.map.queryRenderedFeatures({layers: [focus_key+"-point"]}));`

This returns an empty array `[]`.

How can it be that the layer exists but querying for a feature in that layer, returns empty?

**Comment by peterqliu** [comment]
>How can it be 

It _can_ be, when:

- the layer has no features, or
- the layer has no features within the rendered view, at time of query

@Carpetfizz Are you sure that there is a feature from that layer in the current view, when you do the query?  a test case would be useful here.

**Comment by Carpetfizz** [comment]
I see a feature on my map, and the `layer.layout.visibility=="visible"`

**Comment by jfirebaugh** [comment]
@Carpetfizz Can you provide a minimal, self-contained example that demonstrates the issue?

**Comment by Carpetfizz** [comment]
@jfirebaugh @peterqliu here's a small demo where the bug occurs:

http://codepen.io/anon/pen/XMjPwd?editors=1011

**Comment by jfirebaugh** [comment]
Adding a layer is an asynchronous operation with respect to `queryRenderedFeatures`; see the discussion in #4222 and in particular https://github.com/mapbox/mapbox-gl-js/issues/4222#issuecomment-279446075.
