### ISSUE TITLE
queryRenderedFeatures doesnt return whole geometry at high zoom levels

### ISSUE THREAD

**Issue by dougajmcdonald** [mapbox/mapbox-gl-js#4377]
We have a map which has some polygon's as a layer, representing hoverable areas on a map.

We are using `queryRenderedFeatures` to find a site which is hovered on, and we pass that feature as the data to a new `highlighted-sites` layer. Like this:

```
this.map.on('mousemove', (evt) => {
    const sites = this.map.queryRenderedFeatures(evt.point, {layers: ['sites-fill']});
    this.map.getSource('highlighted-sites').setData({type: 'FeatureCollection', features: sites});
});
```
The expected behaviour is that the `sites` variable will contain the full geometry of the polygon which is hovered over. This works at medium zoom levels:

![hover working](https://cloud.githubusercontent.com/assets/1190042/23662395/50e8cbd6-0347-11e7-9cb3-91549a5d6bee.PNG)

When we do this at high zoom level the feature returned is not the whole geometry and as a result we only get part of the shape highlighted:

![hover not working](https://cloud.githubusercontent.com/assets/1190042/23662470/9f007698-0347-11e7-86d2-65b69a4736ab.PNG)

We would expect the function to return the whole shape again. Are we going about this the whole way? it seems like the method we're using is flawed for our expectations.

**Comment by anandthakker** [comment]
@dougajmcdonald `queryRenderedFeatures` returns features that have already been _tiled_ as part of the rendering process, and so it's very likely that at higher zooms, individual polygons returned from this method will be clipped to the tile containing your query point.

This is a limitation of using the geometry you get back from `queryRenderedFeatures` for hover styling using `geojsonSource.setData()`.  If your features have an identifying property, however, then there is an alternative approach using `setFilter` that may work for you.  [Here's an example](https://www.mapbox.com/mapbox-gl-js/example/hover-styles/) of that in action.

**Comment by dougajmcdonald** [comment]
@anandthakker thanks for the response, the approach you've described makes a lot of sense. I went with a more heavy handed approach of querying the data which was passed into the original source and using `turf` to find out whether the cursor is inside a geometry and then passing the geometry to the new layers `setData`. 
I'll switch to your approach as soon as I can as this seems more efficient,

**Comment by lp6191** [comment]
@dougajmcdonald , @anandthakker , would any of you be so kind and elaborate on how to use querysourcefeature, i'm trying to get all the 3-d building pollygon coordinates, so i can select entire building, and change it's color correctly.. the obstacle i'm facing is, that the querysourcefeatures returns completely irrelevant coordinates here is my code: ```
`var feature = map.querySourceFeatures("composite", { sourceLayer: ['building'], filter: ['==', 'extrude', 'true'] });
        var collection = turf.featureCollection(feature);
        console.log(feature); //output shown below!!!!!
        var click = [];
        click[1] = map.unproject(e.point).toArray()[1];
        click[0] = map.unproject(e.point).toArray()[0]; 
        point = turf.point(click);
        //console.log(point);
        turf.featureEach(collection, function (currentFeature, currentIndex) {
            //console.log(currentFeature);
            if(currentFeature.geometry.type == "MultiPolygon"){
                var poly = turf.multiPolygon(currentFeature.geometry.coordinates);
            }else{
                var poly = turf.polygon(currentFeature.geometry.coordinates);  
            }
                      
            //console.log(poly.geometry.coordinates);
            //console.log(point.geometry.coordinates);
            var condition = turf.inside(point.geometry.coordinates, poly.geometry.coordinates);
            //console.log(condition);
            if(condition){
                index.push(currentIndex);
            }
        });
        console.log(index);
        var feat = [];
        var temp;
//adding the coordinates to draw the entire building
        for (var ind of index) {
            for (var i = 0; i < feature[ind].geometry.coordinates.length; i++) {
                temp = {
                    "type": "Feature",
                    "geometry": {
                        "type": "Polygon",
                        "coordinates": [feature[ind].geometry.coordinates[i]]
                    }
                }
                feat.push(temp);
            }
        }`
```
and the output from logs: geometry:Object coordinates:Array(1)0: Array(9) 0: Array(2)
0:-82.74937011301517 
1:74.95645477412938 
The desired click happens around 
Latitude: 46.056947
Longitude: 14.505751

any help would be highly appreciated

**Comment by lbud** [comment]
@lp6191 unfortunately we're not able to provide support via this issue tracker. For usage questions, please [refer to our documentation](https://www.mapbox.com/mapbox-gl-js/api/), ask on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox-gl-js) or contact Mapbox support.

**Comment by lp6191** [comment]
@lbud Thanks for your reply, i know that the comment above doesn't give you enough info. I couldn't help myself and opened another issue #4950 , it has a JSFiddle in whichyou can see the unexpected behaviour (in your console at two different zoom levels, 15 and 18 for example). Sorry for opening another issue. Please help, been banging my head against the wall for about two days because of these 3D buildings :/
