### ISSUE TITLE
queryRenderedFeatures stringifies nested `properties`

### ISSUE THREAD

**Issue by dougajmcdonald** [mapbox/mapbox-gl-js#4380]
I have some GeoJSON with nested properties, something like this:

```
{
  type: 'Polygon',
  geometry: ...,
  properties: {
    id: 1,
    ratings: [
      { year: 1, score: 5 },
      { year: 2, score: 10 }
    ]
  }
}
```

When I used `queryRenderedFeatures` and return this feature I get a JSON object which looks like this:

```
{
  type: 'Polygon',
  geometry: ...,
  properties: {
    id: 1,
    ratings: "[{ "year": 1, "score": 5 },{ "year": 2, "score": 10 }]"
  }
}
``` 

So it looks like it's stringified my ratings array. I would expect to have the original feature returned with it's original structure. Is this stringification expected? 

At the moment I have a workaround by doing this:

```
    filteredFeatures.forEach((filter) => {
      filter.properties.ratings = JSON.parse(filter.properties.ratings);
    });
```

But it feels like I shouldn't need to. Any thoughts?

**Comment by Scarysize** [comment]
AFAIK the documentation states that "...For GeoJSON sources, only string and numeric property values are supported..." (https://www.mapbox.com/mapbox-gl-js/api/#Map#queryRenderedFeatures)

**Comment by dougajmcdonald** [comment]
@Scarysize aha, thank you. Sorry I missed that one. Is there a specific need to not support objects / arrays etc? Wonder if it's worth submitting as a feature request?

**Comment by jfirebaugh** [comment]
We're tracking the feature request in #2434.
