### ISSUE TITLE
Restore ESLint check

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#4387]
While reviewing #4386, I suddenly realized that ESLint isn't checking our JS code since `js` folder was renamed to `src`, but the `lint` NPM script still references `js`. We should fix the command and any issues that may have slipped. @lucaswoj @mollymerp

**Comment by mourner** [comment]
Confirmed that this commit doesn't update the `lint` script: https://github.com/mapbox/mapbox-gl-js/commit/b9e10b939c6a3fe5d7ecac209f751b4871970ede

**Comment by lucaswoj** [comment]
EEk! My mistake! Thanks for the quick fix @mourner.
