### ISSUE TITLE
Mapbox logo is added multiple times when changing style

### ISSUE THREAD

**Issue by runetvilum** [mapbox/mapbox-gl-js#4388]
**mapbox-gl-js version**: v0.33.0

### Steps to Trigger Behavior

 1. https://www.mapbox.com/mapbox-gl-js/example/setstyle/
 2. change style
 3.

### Expected Behavior
logo should only be added once
### Actual Behavior
logo is added each time you change style

**Comment by andrewharvey** [comment]
#4382
