### ISSUE TITLE
mapboxgl.util.getJSON missing

### ISSUE THREAD

**Issue by Schwanksta** [mapbox/mapbox-gl-js#4393]
**mapbox-gl-js version**: 0.33.0

### Steps to Trigger Behavior

 1. Attempt to call mapboxgl.util.getJSON

### Expected Behavior

As in previous version, perform an XHR request and get the JSON data.

### Actual Behavior

Uncaught TypeError: Cannot read property 'getJSON' of undefined

Appears mapboxgl.util is not longer accessible in the latest release.

**Comment by jfirebaugh** [comment]
> Appears mapboxgl.util is not longer accessible in the latest release.

That's correct; see #1408. You'll now need to provide your own utility for Ajax, or use browser built-ins.

I've added this change to the CHANGELOG for 0.33.0.
