### ISSUE TITLE
Can't get new canvas source to work

### ISSUE THREAD

**Issue by jliebrand** [mapbox/mapbox-gl-js#4399]
I've tried to replicate the original example show casing the canvas source, but I can't get it to work. Here's my example:
https://jsbin.com/sodirecepi/edit?html,js,console,output

Notice that if I comment out the raster layer, the map is drawn on it's own. But if I enable that layer, the map merely has it's labels drawn.

PS. it would be great to have an example in the list of examples (so we can see a working copy)

**Comment by prodjectOriented** [comment]
Appears to be working? I see an animation that comes from the CanvasSource?

**Comment by jfirebaugh** [comment]
Thanks for the report @jliebrand. I believe this is the same issue as #4262.

**Comment by jliebrand** [comment]
Sorry I'm confused, this is what I see:
<img width="1130" alt="screen shot 2017-03-10 at 6 48 01 pm" src="https://cloud.githubusercontent.com/assets/23407884/23808568/3f22c604-05c2-11e7-8502-639e86c82b56.png">

**Comment by jliebrand** [comment]
Ah sorry, didn't see the dupe... will track that one
