### ISSUE TITLE
Update single feature in large existing source.

### ISSUE THREAD

**Issue by gorbypark** [mapbox/mapbox-gl-js#4401]
This may be a possible feature request, or just a question.  Feel free to delete it if it's not appropriate here.  I currently load a ~500kb GeoJSON file full of points on initial load of my map.  I'd like to update specific features using incoming MQTT messages.  Is there a way that I can do that without re-loading the entire layer?  I can only see methods in the examples that involve polling a server for changes in the json, or updating an entire source (such as the "Update features in realtime" example, which I believe gets the new coordinates, "pushes" that to the list of coordinates, then reloads the entire layer with "map.getSource('trace').setData(data);").

**Comment by lucaswoj** [comment]
You currently need to reload the entire layer. Implementation-wise, there are limited opportunities to do incremental updates for GeoJSON sources. 

Related issues & projects

 - https://github.com/mapbox/mapbox-gl-js/projects/2
 - https://github.com/mapbox/mapbox-gl-js/issues/1504
 - https://github.com/mapbox/mapbox-gl-js/issues/2275
