### ISSUE TITLE
Copy button not working on examples page

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-gl-js#4405]
Looks like the copy button on the [gl-js examples](https://www.mapbox.com/mapbox-gl-js/examples/) page is no longer functioning.

![image](https://cloud.githubusercontent.com/assets/4587826/23816576/921c24f6-05bb-11e7-9800-adca804d5f3d.png)

/cc @mollymerp

**Comment by lucaswoj** [comment]
This may be a good excuse to begin using the [new `copyable` Jekyll plugin](https://github.com/mapbox/mapbox-gl-js/blob/master/docs/_plugins/copyable.rb) 😄

**Comment by mollymerp** [comment]
closed in 2566831
