### ISSUE TITLE
Stops handled in a different way, breaking app

### ISSUE THREAD

**Issue by jaapster** [mapbox/mapbox-gl-js#4412]
Prior to v0.33.0 this used to be a valid style:

`'circle-radius': {
   'property': 'myVar',
   'stops': [
      [{zoom: 0, value: 'a'}, 5],
      [{zoom: 0, value: 'b'}, 10],
      [{zoom: 0, value: 'c'}, 15]
   ]}
}`

Since v0.33.0 the layer for this style is no longer added to the map.
I can't find what has changed since 0.33.0.

Is this a bug?

**Comment by anandthakker** [comment]
@jaapster are you seeing any errors in the JS console?  Or, even better: could you make a https://jsbin.com example that reproduces the issue?  Thanks!

**Comment by jaapster** [comment]
@anandthakker While I was preparing this example [](https://jsbin.com/wedude/edit?html,output) I found that I omitted `'type': 'categorical'` in my style definition.

**Comment by jaapster** [comment]
In the release notes it says that 'property functions support for most symbol paint properties' were added, but I didn't think that this would break my style def. Shouldn't this change be in the section breaking changes?

**Comment by anandthakker** [comment]
Ah, okay. Thanks for following up!

I think what you've run into here may be the result of this change: https://github.com/mapbox/mapbox-gl-js/commit/a8c6259798685c9d2993c08a2d16b8866698fb66

We did not mark it as a breaking change, because the bug reported in https://github.com/mapbox/mapbox-gl-js/issues/3717 seemed to suggest that omitting `type: categorical` would not have worked before anyhow.  It sounds like you're saying that omitting it _did_ work for you -- is that right?

cc @jfirebaugh

**Comment by jfirebaugh** [comment]
I believe it would have accepted the function definition, but calculated an incorrect value (always using the last stop).

**Comment by jaapster** [comment]
@anandthakker Yes, `type: categorical` was not in my style definition before. the code in the JSBin posted above used to work. Change the mapbox url in the scripttag to 0.32.0 to verify, an orange circle should be rendered at [0, 0].

**Comment by jaapster** [comment]
@jfirebaugh Actually, I had 3 stops in my 'circle-radius' property and got three different radii.

**Comment by jaapster** [comment]
@jfirebaugh I just updated the JSBin example adding a second point geometry. If you change the included mapbox version to 0.32.0 two circles are rendered with two different radii. Without including `'type': 'categorical'`

**Comment by jfirebaugh** [comment]
Yes, I see. It looks like property-and-zoom functions were not affected by #3717, just property functions (`'stops': [['a', 10], ['b', 20]]` for example).

In any case, the solution is to add an explicit `'type': 'categorical'`. I've added this to the "breaking changes" section of the CHANGELOG: 3bdfaaa31c83a5970324fcd39340f4908b4d50f9
