### ISSUE TITLE
GeoJson points clustering 

### ISSUE THREAD

**Issue by rzbt** [mapbox/mapbox-gl-js#4415]
Hello,

Im using mapbox gl to display GeoJson points on map.
Im also using sprites to design my points. 
My point are automatically clustered (ie I see only one point in a zone where I should see lot of points). Do you know if its possible to avoid this clustering ?
I would like to see all points even in a zone that contain multiple points

Thanks

**Comment by Scarysize** [comment]
Assuming you use a `symbol` layer you can just use the `icon-allow-overlap` option: https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-allow-overlap

**Comment by rzbt** [comment]
Thank you I will try !

I really sorry to had to create an issue for that, I really search before post. 
My feeling is that each time I search for something about mapbox it's really difficult to find an answer... 
Hopefully you are really reactive 🥇
