### ISSUE TITLE
Unable to parse URL object for sprite 

### ISSUE THREAD

**Issue by rzbt** [mapbox/mapbox-gl-js#4416]
Hello,

Im using sprite file to display layer with icon-image on map.
Until today, I always used this : 

`{
    "version": 8,
    "sources": {},
    "layers": [],
    "sprite": "./assets/sprites/sprites"
}`

But I have now this error : 

> Unable to parse URL object

I used the debugger to find that happen for the sprite url.
Why this is not working anymore ?

**Comment by jfirebaugh** [comment]
Relative URLs are not supported for the `sprite` or `glyphs` property: #4141.
