### ISSUE TITLE
Implement 2D conditional terrain coloring

### ISSUE THREAD

**Issue by femski** [mapbox/mapbox-gl-js#4421]
While we wait for 3D terrain, a simple conditional 2D hill-shading would be sufficient for many needs. Something like: 

http://ivansanchez.gitlab.io/Leaflet.TileLayer.GL/demo/demo-flood.html 

Is this what you will implement in Issue #3730 ? Or is there an example somewhere that demonstrates how we can show conditional terrain today ? Thanks.

**Comment by stevage** [comment]
Yes, #3730 is about generating hill shading in the browser to simulate a terrain effect. Not sure what you mean by "conditional terrain", but maybe #3889?

**Comment by femski** [comment]
I meant showing terrain above certain height in red. Those below certain level in transparent and yellow for things in-between.

**Comment by stevage** [comment]
Yup, that's what #3889 is about - although I don't think anyone has suggested transparent. Note that #3889 is not on anyone's current to-do list, but on many people's wishlist. :)

**Comment by mollymerp** [comment]
Thanks for your request @femski. @stevage is correct! I'm working on 2d client-side hillshading which will expose several new style-spec properties for controlling how terrain appears on the map. We don't have plans to allow raw elevation querying as part of that effort. I think supporting custom raster sources would cover that use-case. Lets keep conversation centralized in #3889 and #3730.
