### ISSUE TITLE
Where is documentation for old versions?

### ISSUE THREAD

**Issue by why-el** [mapbox/mapbox-gl-js#4427]
Hey,

Apologies if this does not follow your issue guidelines. We just have a simple question: Where is the documentation for old versions such as `0.18.0`? Some of our legacy systems still run on versions like that. 

I found https://github.com/mapbox/mapbox-gl-js/tree/v0.18.0/docs, which we can run in our own servers, but I am just curious as to why there does not seem to be a Mapbox-hosted version of it.

**Comment by jfirebaugh** [comment]
Thanks for the question @why-el. We're discussing this in #2398 -- let's centralize discussion there.

**Comment by why-el** [comment]
Great, thanks for the prompt response.
