### ISSUE TITLE
Update version support matrixes for 0.33

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#4428]
We need to add v0.33.0 in the appropriate rows of the version support matrixes on https://www.mapbox.com/mapbox-gl-js/style-spec/ -- mainly "data-driven styling" for various symbol layer properties.

**Comment by mollymerp** [comment]
My mistake -- thanks @jfirebaugh for the quick fix.

**Comment by jfirebaugh** [comment]
No worries @mollymerp!
