### ISSUE TITLE
Add DDS support for "text-offset"

### ISSUE THREAD

**Issue by ericrwolfe** [mapbox/mapbox-gl-js#4435]
DDS support for `text-offset` should go hand in hand with `icon-size` https://github.com/mapbox/mapbox-gl-js/issues/4228.

__Primary use case:__ When a symbol layer contains both text and an icon, and `icon-size` is driven by a DDS function, the `text-offset` will likely need to change to handle the dynamic icon size. 

Similar to the already-implemented `icon-offset` https://github.com/mapbox/mapbox-gl-js/pull/3791.

**Comment by anandthakker** [comment]
Great point @ericfischer

**Comment by stevage** [comment]
This is marked as implemented, but in practice, it is extremely limited. There is no way to construct the array dynamically, so as far as I can tell, the only kind of "data-driven" property property is of this form:

`text-offset`: [`case', ['==','['get','direction'], 'left'], [-2, 0], ...]`
