### ISSUE TITLE
Support multi-text symbols, or combine symbols

### ISSUE THREAD

**Issue by dayAlone** [mapbox/mapbox-gl-js#4436]
<img width="794" alt="2017-03-16 8 03 25" src="https://cloud.githubusercontent.com/assets/4610649/23977205/4837588e-0a1f-11e7-973c-346e780816ef.png">

In my project, I need to make Symbols like on the image. Now I create 2 layers: 
1. with label and icon
2. with price

And in second layer set 'text-ignore-placement': true to show price and ignore overlapping with first layer. So, after this in some cases I have result like this:
<img width="673" alt="2017-03-16 8 11 08" src="https://cloud.githubusercontent.com/assets/4610649/23977338/2cc73e10-0a20-11e7-971f-8733d3b65b5a.png">

And now, I don't have any options to prevent this. If I will be able to put some array with texts to Symbol layer and style them separately it will be helpful in cases like this. 

Or if I will be able to combine some layers to one for better calculation their boundaries for overlapping it will be helpful too.

**Comment by indus** [comment]
Similar: #4366

**Comment by dayAlone** [comment]
@indus Yes, similar, but not about icons :)

**Comment by jfirebaugh** [comment]
Combining this with #4366 (I retitled it to generalize).
