### ISSUE TITLE
DDS extrusion-heights get Math.floor'ed

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#4438]
chekkit: https://jsfiddle.net/xgs8oyrc/

**mapbox-gl-js version**: v0.33.1

### Steps to Trigger Behavior

 1. Add a fill-extrusion layer
 2. Apply a categorical, DDS styling rule on `fill-extrusion-opacity` (might be other DDS types as well)
 3. For the value, use a fractional height value (e.g. 1.5)

### Expected Behavior

An extrusion of height 1.5

### Actual Behavior

An extrusion of height 1.

From the linked fiddle:

![screen shot 2017-03-16 at 1 27 58 pm](https://cloud.githubusercontent.com/assets/4551508/24017246/7119645e-0a4c-11e7-839b-1f244a2d4329.png)
_Red extrusion is DDS styled to 1.5. Blue extrusion is explicitly styled to 1.5_

cc/ @lbud

**Comment by peterqliu** [comment]
Confirming that this applies to both:

- `fill-extrusion-height` and `fill-extrusion-min-height` properties, and
- all three DDS types: `exponential`, `interval`, `categorical`

**Comment by jfirebaugh** [comment]
I believe this is because we use `Uint16` as the type of the height attribute in the vertex object in gl-js. In native, we use floating point vertex attributes for all properties. I'm working on a change to gl-js that switches to the native behavior, which should fix the issue.
