### ISSUE TITLE
Data-driven styles render map features in black if no corresponding paint stop exists

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#4441]
**mapbox-gl-js version**:
0.33.1

Between versions 0.32.1 and 0.33.1, there seems to have been a change to the style spec which is preventing us from upgrading to the latest version.

We currently use an empty stop and transparent color for map features we don't need data-driven styling for but still wish to render. See [jsbin example](https://jsbin.com/xeyekuceyo/1/edit?html,js,output) demonstrating this works in 0.32.1.

However, in 0.33.1 all features not explicitly declared in a stop gets rendered in black. See the same [jsbin example](https://jsbin.com/nosahaxezo/1/edit?html,js,output) with 0.33.1.

**Comment by jfirebaugh** [comment]
Prior to 0.33.0, it was unspecified what the behavior of categorical functions was when evaluating a feature property that matched none of the categories. It appears you were relying on the value from the first stop being returned, but that behavior was not guaranteed. In 0.33.0, we added an explicit [`default` property](https://www.mapbox.com/mapbox-gl-js/style-spec/#function-default) to the function specification. [Here's](https://jsbin.com/wagifogohi/edit?html,js,output) a working example in 0.33.1.

**Comment by DannyDelott** [comment]
This is great, thank you!
