### ISSUE TITLE
How to switch off rotating to north on mobile?

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#4444]
When I use the map on my mobile phone the map rotates to track the north of my mobile phone. How can I switch this off? I do want to continue to be able to rotate the map with touch gestures.

**Comment by 1ec5** [comment]
To clarify, are you rotating the physical device between landscape and portrait and seeing that the map rotates 90° to stay upright? Or some other behavior?

**Comment by musicformellons** [comment]
Other. It rotates at every degree that i rotate my mobile. In addition there is also the portrait landscape rotation at approx 90degrees but that is desired behavior.

**Comment by 1ec5** [comment]
Are you using GL JS or the native Mapbox Android SDK or Mapbox iOS SDK? As far as I know, bearing tracking mode isn’t built into GL JS, but it is a feature of the native SDKs.

**Comment by musicformellons** [comment]
I am using mapbox gl js and ngrok to see my app on my Android phone in
chrome browser. And it is tracking doe sure... 😃

Op wo 22 mrt. 2017 07:26 schreef Minh Nguyễn <notifications@github.com>:

**Comment by jfirebaugh** [comment]
@musicformellons Mapbox GL JS doesn't have a bearing tracking feature, so I'm not sure what you are referring to. Can you create a minimal self-contained demo to show us?

**Comment by musicformellons** [comment]
Hahaha, so why is it tracking on my phone then! I will have another look to see if I can make chocolat from this. At least I now know this is not intended behavior. I'll be back!

**Comment by musicformellons** [comment]
Ahum..., I suddenly started remembering I might implemented this myself using a snippet from somewhere and indeed I find:
```
      if (window.DeviceOrientationEvent) {
        window.addEventListener('deviceorientation', event => {
          let compassdir
          if (event.webkitCompassHeading) {
            // Apple works only with this, alpha doesn't work
            compassdir = event.webkitCompassHeading
          }
          else {
            compassdir = event.alpha
          }
          myMap.easeTo({
            bearing: 360 - compassdir,
            easing: easing
          })
        })
      }
      else {
        alert("Sorry, your browser doesn't support Device Orientation")
      }
```

After getting rid of that everything is fine now... Sorry for bothering you with this.
