### ISSUE TITLE
configurable transition timing curves

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-js#4445]
See https://github.com/mapbox/mapbox-gl-native/issues/8456 for background. Timing curves are specified as [four-element arrays of floats](https://github.com/mapbox/mapbox-gl-js/blob/b9e10b939c6a3fe5d7ecac209f751b4871970ede/src/util/util.js#L46) `[c1x, c1y, c2x, c2y]` such that a full curve definition is ` [(0.0,0.0), (c1x,c1y), (c2x,c2y), (1.0,1.0)]`. 

This could even be per-property, per-transition if we want to get crazy.

**Comment by mourner** [comment]
Closing as stale since there seems to be not enough interest to pursue this.
