### ISSUE TITLE
flyTo does not check the value of transform.renderWorldCopies

### ISSUE THREAD

**Issue by huaruiwu** [mapbox/mapbox-gl-js#4449]
**mapbox-gl-js version**: v0.34.0

### Steps to Trigger Behavior

 1. initialize a map and set `option.renderWorldCopies = false`
 2. try to do a `flyTo` where `Math.abs(tr.center.lng) + Math.abs(center.lng) > 180`

### Expected Behavior
 `flyTo` should stay in the noncopied world where `-180 < lat < 180`.
### Actual Behavior
 `flyTo` will to to bring you to a worldCopy which is not rendered.

Something like this will fix the problem.
https://github.com/huaruiwu/mapbox-gl-js/commit/4baab4a23528098fe9563d80483b5367dd6b3aea

**Comment by andrewharvey** [comment]
@huaruiwu I encourage you to submit this is a PR. Your fix looks good to me!

**Comment by andrewharvey** [comment]
Fixed in 9941dde7e8f769f01917f3fc06b80a4d46c20422
