### ISSUE TITLE
browserify bundle is broken

### ISSUE THREAD

**Issue by ellvtr** [mapbox/mapbox-gl-js#4453]
**mapbox-gl-js version**: "^0.34.0"

### Steps to Trigger Behavior

Complete reproduction of bug in this super simple dedicated repo:
https://github.com/awesomemaptools/mbtst

 1. Require module with `require('mapbox-gl/dist/mapbox-gl')` as documented here: https://www.mapbox.com/mapbox-gl-js/api/
 2. Initiate map in main.js
 3. Bundle with browserify in terminal 
`node node_modules/browserify/bin/cmd.js --entry src/main.js --outfile dist/build.js`
 4. Terminal outputs:
```
Error: Cannot find module './feature' from '.../mbtst/node_modules/mapbox-gl/dist'
    at /home/jonas/zegeba/repos/mbtst/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/home/jonas/zegeba/repos/mbtst/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/jonas/zegeba/repos/mbtst/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/jonas/zegeba/repos/mbtst/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
``` 

### Expected Behavior
Expected to create bundle in dist/build.js and when run in browser, map will render as it does using regular CDN.

### Actual Behavior
Terminal error - "Cannot find module".

**Comment by mollymerp** [comment]
We recently switched to exporting the `dist` files for bundlers (https://github.com/mapbox/mapbox-gl-js/pull/4423) – I've opened a PR to update the docs! https://github.com/mapbox/mapbox-gl-js/pull/4458

**Comment by mollymerp** [comment]
Oops, although our docs were out of date, that doesn't seem to be the issue here.

**Comment by ellvtr** [comment]
After I isolated the issue in the small repo, I made it work when requiring from source:
`require('mapbox-gl/src/index.js');`
See https://github.com/awesomemaptools/mbtst 
Still doesn't work from dist, though.

**Comment by anandthakker** [comment]
Thanks for posting the workaround, @ellvtr 

@mollymerp I think you're right that this is a result of #4423 -- the `dist/mapbox-gl.js` file is a bundle built with `browserify --standalone mapboxgl`.  (See https://github.com/mapbox/mapbox-gl-js/issues/4453 and https://github.com/mapbox/mapbox-gl-js/pull/4391 as well.)

https://github.com/substack/browser-pack/issues/45 suggests that standalone browserify bundles might not be usable as modules that can be `require()`'ed and _re_-browserified.

**Comment by anandthakker** [comment]
Ah, I think I misread that browser-pack issue -- it's about the `--require` _flag_ -- but nonetheless, it does seem like the issue here is requiring the standalone browserified bundle as if it were a 'normal' node module, and then browserifying.

**Comment by ellvtr** [comment]
I see that you changed the docs to `const mapboxgl = require('mapbox-gl')` which still produces the same error. I guess you also changed main in package.json to point to "dist/mapbox-gl.js"?
It still works with `var mapboxgl = require('mapbox-gl/src/index.js');`.

**Comment by anandthakker** [comment]
@ellvtr yes--please proceed with `require('mapbox-gl/src/index.js')` for now.  We're working to fix this, hopefully for _both_ browserify and webpack this time, over in #4462
