### ISSUE TITLE
Update sdk-support tables for Android 5.0 and iOS 3.5.0

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#4461]
Added DDS support for:

 line-gap-width
 line-color
 line-opacity
 line-offset
 circle-color
 circle-opacity
 circle-radius
 fill-color
 fill-opacity
 icon-offset
 icon-rotate
 text-transform
 text-field
 icon-opacity
 text-opacity
 text-color
 icon-color
 text-halo-color
 text-halo-blur
 text-halo-width

Also added support for numerous `function` properties (all except `colorSpace`).

cc @mapbox/android @mapbox/ios

**Comment by ivovandongen** [comment]
@jfirebaugh `icon-rotation` is `icon-rotation-alignment` here right?

**Comment by jfirebaugh** [comment]
No, it's `icon-rotate`. Fixed.
