### ISSUE TITLE
Keep "Last updated" value on roadmap page up to date

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#4464]
Currently, the "Last updated" value on the roadmap page is baked into the HTML, making it easy to forget to update it.  Ideally, it would be generated based on when the roadmap changes, but barring that, perhaps we could change the `roadmap.yml` format to include this value, so that it's easy to edit in the same place.

**Comment by asantos3026** [comment]
I'm looking in to this issue.

**Comment by mollymerp** [comment]
Thanks so much @asantos3026! Let us know if you need help or are looking for another issue to tackle 😸

**Comment by asantos3026** [comment]
@mollymerp Hey Molly! No problem 👍 I do need some help on how to get started on this issue. So the Last Updated is hardcoded in to the pages.html of the roadmap.  I am wondering how I can get access to the timestamp data, through generate.js which is building the docs. Any direction / hint would help!
