### ISSUE TITLE
new version leads to style render failed 

### ISSUE THREAD

**Issue by tianbaolin** [mapbox/mapbox-gl-js#4475]
my dear friend:
I'm so sorry to say that, the probrem  [new version leads to style render failed(click it)](https://github.com/mapbox/mapbox-gl-js/issues/4474) had not been solved.I had changed URL to a full URL, but it doesn't work。browser had get the sources file.
this is the style config file I had changed  :
`{
  "version": 8,
  "name": "liuchuang",
  "metadata": {
    "mapbox:autocomposite": true,
    "mapbox:type": "template"
  },
  "center": [
    7.696546201867221,
    0.574720297415567
  ],
  "zoom": 5.863876848515303,
  "sources": {
    "line": {
      "data": "http://112.74.161.197/data/line.geojson",
      "type": "geojson"
    }
  },
  "layers": [
    {
      "id": "background",
      "type": "background",
      "metadata": {},
      "layout": {
        "visibility": "visible"
      },
      "paint": {
        "background-color": "rgba(238,236,255,1)"
      }
    },
    {
      "id": "line",
      "type": "line",
      "source": "line",
      "source-layer": "line-5jz1pa",
      "layout": {
        "line-join": "round",
        "line-cap": "round"
      },
      "paint": {
        "line-color": "#aaa",
        "line-width": 8
      }
    }
  ],
  "created": "2016-11-21T13:07:54.972Z",
  "id": "civs382ei005z2kofmbg5hmga",
  "modified": "2017-02-24T11:58:48.482Z",
  "owner": "mallto",
  "visibility": "private",
  "draft": false
}`.
this is the link of v0.26:
[Mapbox GL JS v0.26](http://112.74.161.197/index026.html)
this is the link of v0.34:
[Mapbox GL JS v0.34](http://112.74.161.197/index034.html)
the different between them is only the version of Mapbox GL JS.

**Comment by tianbaolin** [comment]
now I had solve this probrom.in style file ,it does not allowed property of  source-layer,when I delete it ,the
map work normally.

**Comment by lucaswoj** [comment]
Yes indeed, we do not allow a `source-layer` property on GeoJSON sources. Our validator didn't always catch this error.
