### ISSUE TITLE
RasterTileSource serialize() method doesn't serialise metadata property.

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox-gl-js#4480]
While vector tile sources do serialise metadata property, raster tile sources [don't](https://github.com/mapbox/mapbox-gl-js/blob/master/src/source/raster_tile_source.js#L50).

I'm heavily relying on metadata property contents, since this is the place to keep all the data, that goes beyond the style spec (like source id's, layer group trees, etc.) 
Can you please  add metadata serialisation to all source types?

**Comment by anandthakker** [comment]
Thanks @nextstopsun and good point.  This is the same underlying issue as the one causing #3893 -- we'll track this over there.
