### ISSUE TITLE
Support clustering for HTML "Marker"s

### ISSUE THREAD

**Issue by D1M** [mapbox/mapbox-gl-js#4491]
Hello!
As we can see here https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/
we could create a custom Marker and add it to map.
e.g. new mapboxgl.Marker(...).setLngLat(...).addTo(map);

I'm trying to find the way how to add marker to the layer and organize into the Cluster. 
Smth like https://www.mapbox.com/mapbox-gl-js/example/cluster/ but with custom Markers:
1. var map = new mapboxgl.Map...
2. map.addSource(...);
3. map.addLayer(...);
4. and here map.getLayer(...).addMarker(Marker). or marker.addto(Layer/Source) or ...
As a result we should see a Cluster with custom markers.

**Comment by lucaswoj** [comment]
Hi @D1M! We do not support clustering on `Marker`s, only on `symbol` layers. This is a feature we may support in the future but have no immediate plans to add support.

**Comment by lucaswoj** [comment]
You _can_ use custom icons with a `symbol` layer via the new `Map#addImage` method (going out in the next release) or by adding the icons to your sprite in Studio.

**Comment by D1M** [comment]
@lucaswoj thanks, looking forward to see such feature in future releases of mapbox-gl!

**Comment by lucaswoj** [comment]
Let's keep this issue open to track the feature 😄

**Comment by 1ec5** [comment]
The Android and iOS analogue of this issue is being tracked in mapbox/mapbox-gl-native#5815.

**Comment by realph** [comment]
+1 I too would like to have custom markers that work with clustering.

**Comment by DarkKnight1992** [comment]
+1 would really love to have this feature

**Comment by peterqliu** [comment]
this is possible now, with https://github.com/mapbox/supercluster. Was originally built for leaflet maps, but can be adapted to GL marker.

**Comment by DarkKnight1992** [comment]
that's amazing, you guys are the best !!

**Comment by DarkKnight1992** [comment]
How to use this cluster plugin with custom html marker there is not much documentation about it ?? ;(

**Comment by peterqliu** [comment]
@DarkKnight1992 you are correct that there is no documentation specifically combining supercluster with GL custom markers. The former does provide GeoJSON as output, though, which you can figure out how to adapt as an input for the latter.

**Comment by DarkKnight1992** [comment]
@peterqliu but yo can't use custom marker as geojson in Mapbox Gl if i am not wrong ? Since you can't add a source and get a source layer very are using ajax for getting the getting and iteration for the former geojson created for mapbox leaflet to create new markers in Mapbox Gl. Is that the correct way of adding custom markers or mapbox gl provides some kind of api like loadurl() in mapbox leaflet ?

**Comment by peterqliu** [comment]
> but yo can't use custom marker as geojson in Mapbox Gl if i am not wrong ? 

@DarkKnight1992 see the first link in the original post above for an example of how to do this

**Comment by DarkKnight1992** [comment]
that's how its been done currently

**Comment by Wykks** [comment]
It is possible.
Implemented in https://github.com/alex3165/react-mapbox-gl
As you can see in the demo : http://alex3165.github.io/react-mapbox-gl/, when we rotate/pitch the map, the cluster are messed up.
Because it's not sending the real viewport to supercluster, it's based on the current axis-aligned rectangular bounding box (also see https://github.com/mapbox/mapbox-gl-js/issues/2112 )
```
const bounds = map.getBounds();
const zoom = map.getZoom();
const newPoints = supercluster.getClusters(
      [bounds.getWest(), bounds.getSouth(), bounds.getEast(), bounds.getNorth()],
      Math.round(zoom)
);
```
Does supercluster have a way to get the real viewport ?
How it is done in mapbox-gl ? Because the cluster demo (https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/) works fine with rotation/pich, and as far I know, it use supercluster internally.

**Comment by peterqliu** [comment]
>Does supercluster have a way to get the real viewport ?

@Wykks you can adapt [unproject()](https://www.mapbox.com/mapbox-gl-js/api/#map#unproject) on the four corners, for this purpose.

**Comment by DarkKnight1992** [comment]
@peterqliu ran into another problem today and paying very big price for using Mapbox Gl if there is no workaround for this problem. As i know mapbox-gl uses webgl to render images but a vast amount of our user base may not have webgl support. Can we render raster images instead of webgl? is that a possibilty ? If not then it's really been a huge waste of time using mapbox gl :(

**Comment by Wykks** [comment]
Whoa true, totally missed that, thanks !

@DarkKnight1992 Yep, as far I know mapbox-gl require webgl (hence the suffix -gl), you can use this plugin to test if mapbox-gl is supported : https://github.com/mapbox/mapbox-gl-supported

**Comment by DarkKnight1992** [comment]
@Wykks thanks. We didn't wanted to use other plugin for checking the webgl support and only a small script did the trick. But in the end i was really disappointed as we had to load to different libraries for doing the same thing. Shouldn't there be better work around for this ? Because loading a two different libraries mean using two different sets of code as a library and the actual code for the map. which goes against the basic rule of programming - "Never write code again fro the same result".

**Comment by peterqliu** [comment]
There is [documentation](https://www.mapbox.com/mapbox-gl-js/api/#supported) for checking webgl support

**Comment by brianhyper** [comment]
Any improvement on this one?

I managed to add custom icon by generating them with the addImage but I get a "SpriteAtlas out of space"...
So I tought that we could have manage our marker manually and add them to a layer and the clustering would work out of the box without having to rebuild everything... it suck that it don't... I have over 500 markers on my map and each of them have an icon with their logos... so I have to add over 500 custom icon and without clustering it's a mess...

**Comment by plucile** [comment]
+1 for marker clustering support

Also, Is there an event triggered when a symbol disappears to be part of a cluster? Using this code https://www.mapbox.com/mapbox-gl-js/example/cluster/

I have a map with markers. On click on a marker, the icon changes to an "active" style and a popup shows up. 
Since I want to use clustering, I've changed all my markers to be symbols. The only way I found to have an "active" icon on click is by adding a layer on top of all the symbols with just this point using a different icon. However when zooming out this symbol doesn't get clustered when the "default" one is resulting in the "active" icon displaying on top of the cluster... 

Thanks

**Comment by guanioramon** [comment]
+1 For marker clustering support
Hi Guys ,
please work around on this.This is most important feature.
I am still using leaflet cluster on mapboxgl to make it working but this is very important feature.

**Comment by liampmccabe** [comment]
+1

Also after this, a custom icon url would be perfect!

**Comment by liampmccabe** [comment]
For anyone still wanting this feature. The current workaround I'm using is to display both markers and clusters on a map. Using `queryRenderedFeatures` to grab the unclustered points (which are hidden using the opacity prop) and using a unique id attribute/property to show/hide the markers on events such as render/load.

**Comment by danpe** [comment]
+1 really useful

**Comment by thuanmb** [comment]
For ReactJS lover, here is a solution for clustering (using supercluster) in mapbox-gl:
https://github.com/thuanmb/react-mapbox-gl-cluster

**Comment by schlunsen** [comment]
Any news regarding this?

**Comment by 3zzy** [comment]
+1

**Comment by shamalli** [comment]
+1 "musthave" feature

**Comment by 3zzy** [comment]
Here's an example of clustering using HTML markers:
https://jsfiddle.net/iaezzy/xpvt214o/309931/

.. but the recommended way is to use 'Symbols' which I realized and moved to after I figured I could use any external image with symbols. There's really no reason to use HTML markers over symbols.

**Comment by Wykks** [comment]
@3zzy You're example is incorrect, you should use unproject (see comments above).
There are valid reasons to use HTML marker when you need very custom icons (like d3 generated icons). But yeah, before thinking about using HTML makers, one should check if it's doable using mapbox-gl style system.

**Comment by andrewharvey** [comment]
> There are valid reasons to use HTML marker when you need very custom icons (like d3 generated icons).

Could you do something like https://www.mapbox.com/mapbox-gl-js/example/add-image-generated/.

Interested to here the reasons HTML Markers are needed over symbols. Personally I know animated markers (via css or gif) is a big one. Accessibility could be mitigated with https://github.com/mapbox/mapbox-gl-accessibility.

**Comment by andkom** [comment]
+1

**Comment by Wykks** [comment]
@andrewharvey stuff like that http://bl.ocks.org/gisminister/10001728
You can't use `addImage` to do this, because you can't generate everything in this case.
And yep, animated markers is an issue with symbols.

**Comment by acostariel** [comment]
+1

**Comment by ei-grad** [comment]
Oh, found querySourceFeatures method, could be really easy to integrate with d3 overlay.

**Comment by acostariel** [comment]
@andrewharvey

> the reasons HTML Markers are needed over symbols

In my app, users should be able to choose an option once they've located a marker, and the options will depend on the status of the place that the marker refers to. So far I haven't found another way.

**Comment by pawan8525** [comment]
@D1M @lucaswoj @1ec5 @realph @DarkKnight1992  
i implemented cluster on react-native-map  in mobile app but my requirement is like below , i dont know it is possible in react-native-map or not. Please help me team
Thank you for your kind cooperation.
First part show cluster
![image](https://user-images.githubusercontent.com/38987561/44868731-4dd42780-aca9-11e8-9b83-fee2c642b359.png)

second part that i don't know how to implement please see image
![image](https://user-images.githubusercontent.com/38987561/44868830-9986d100-aca9-11e8-8dce-bdba2f96eb2b.png)


Please if any plugin in react-native

**Comment by tmcintire** [comment]
What exactly is the best option right now when needing custom cluster icons as well as custom marker icons?  Coming from leaflet, it supports this pretty well with DivIcons, I'm not sure how to implement this in mapbox though.  Halp!

**Comment by pawan8525** [comment]
Hello tmcintire,thanks for your response. So you said it is not implement in react-native map.please reply.

**Comment by tmcintire** [comment]
I'm not using the react implementations of this.  None of them expose nearly all of the api pieces that we use.  We have a complex map with lots of layers and lots of custom markers.  So we had to ditch trying to use react for this

**Comment by madc0w** [comment]
Clustering seems unnecessarily complicated.  When can we expect to do this in a simple way using the Marker object?

**Comment by bo-bremen** [comment]
+1

**Comment by silicakes** [comment]
+1 can't wait for this one

**Comment by zhumumu1992** [comment]
我在做的产品是全美房源地图，因为layers-symbol不能实现我的业务需求，所以只能使用marker来实现自定义内容和样式。之前我使用的Google map js开发的产品，现在替换到mapbox-GL-，目前我只能像以前一样继续使用supercluseter作为替代方案，产品效果也很不错，https://github.com/mapbox/supercluster

所以，希望mapbox尽快实现cluster和marker的完美结合。

**Comment by arindammatrix** [comment]
This functionality is also needed in my project. We need the combination of marker cluster and custom marker icon in our project.

**Comment by Wykks** [comment]
I already done this before, but if you do this, there a limitation : you cannot get the leaves of the clusters. And that's a big issue if you need that. So it's ok as long as you don't need theses informations do draw/interact with the cluster.

**Comment by mourner** [comment]
@Wykks why not? You can keep track of cluster ids in the DOM marker objects, and then use the new cluster API methods like [getClusterChildren](https://www.mapbox.com/mapbox-gl-js/api/#geojsonsource#getclusterchildren).

**Comment by Wykks** [comment]
Oh well, when I played with this, the new api (https://github.com/mapbox/mapbox-gl-js/pull/6829) wasn't there :smile: 
That's cool, I should try to do this in ngx-mapbox-gl :+1:

**Comment by clementmas** [comment]
@mourner that sounds good. It doesn't need to be in the Mapbox GL core but it'd be great to have an example to get us started 👍

**Comment by ryanhamley** [comment]
@malwoodsantoro @mzdraper this could be a useful example to add to our docs

**Comment by eduboxgithub** [comment]
Any news on this feature?

**Comment by arindammatrix** [comment]
@mourner @Wykks Did you guys achieved the expected result? If yes, can you please do a jsfiddle for the help of the community.

**Comment by rareslupascu** [comment]
+1

**Comment by clementmas** [comment]
Is anyone working on this? I don't know if I should keep waiting for this or look for another solution. Thanks!

**Comment by rbrundritt** [comment]
I tried the solution someone mentioned that consists of adding a transparent circle layer on the map, enabling clustering on it, the generating html markers after the map finished moving. Works great. I made sure every circle had a unique ID and created a local cache for the markers which is indexed by the ID. Tested with 20,000 markers and worked great. Likely can handle a lot more. A good code sample or plug in might be sufficient.

**Comment by matyushen** [comment]
@rbrundritt would you be able to share an example of your solution? Trying to accomplish something similar in a React project. Struggling with displaying only those HTML markers that are currently not in a cluster.

**Comment by rbrundritt** [comment]
What I've done is wait for the load event of the map to fire, then load my source and layer. Then following that call the same logic I have in the moveend event. If there is a decent amount of data in the source, the clustering logic would likely still be running and the initial query for rendered data will be blank. To address this, use the sourcechange event and have it run the same logic as moveend. This will fire when the source data updates which will address this issue and will also allow you to update the source data and have it automatically reflected in your HTML marker layer.

**Comment by matyushen** [comment]
@rbrundritt Thank you for all the info! It would be really cool if mapbox-gl supported clustering with html markers out of the box.

**Comment by mitko993** [comment]
+1
I believe this feature is long overdue.

**Comment by matthiasott** [comment]
+1 for clustering of markers. Honestly, I was surprised to learn that this is not possible yet. It just makes so much sense and is a feature many people are used to these days.

**Comment by rbrundritt** [comment]
I don't work for Mapbox, so guessing here, but suspect this was left out as the focus appears to be on native render (i.e. symbol layer) which supports much larger data sets. The native functionality supports clustering. HTML markers I think were added more so for those moving from legacy apps or who render a few points but need full HTML/CSS support.

**Comment by jonaseberle** [comment]
From first reading this, it **might seem to some it is not possible** to have clusters/markers with custom icons/HTML popups on mapbox GL which absolutely is possible.

Don't let yourself be fooled! It is absolutely possible and not too hard. Here are some pointers. 
1) use exclusively geoJSON. Add a property to hold your icon name.
2) make the layer with the unclustered items a symbol layer
    ```
    type: 'symbol',
    layout: {
      'icon-image':'{yourIconPropertyName}'
    }
    ```
3) add your custom icons with map.loadImage()
4) react to mouse clicks onto markers and create and open popups
    ```
    map.on(
            'click',
            'unclustered-points',
            function (e) {
                var coordinates = e.features[0].geometry.coordinates.slice()
                while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
                    coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360
                }

                new mapboxgl.Popup()
                    .setLngLat(coordinates)
                    .setHTML(
                        JSON.stringify(e.features[0].properties) // just an example ;)
                    )
                    .addTo(map)
            }
        )
    ```

![grafik](https://user-images.githubusercontent.com/1678001/53959555-38223d80-40e4-11e9-8715-79e409f31d72.png)

Dear Mapbox, I suggest you add an example showcasing that.

**Comment by rbrundritt** [comment]
@jonaseberle I think you missed the ask for this task. The ask is for the ability to cluster HTML markers. Clustering symbols and displaying popups with HTML content is already well known, and not what people are asking for here. Symbols are great for rendering large data set, but is not nearly as customizable as HTML markers where you have access to the full CSS stack. [Here is an example](https://azuremapscodesamples.azurewebsites.net/index.html?sample=Clustered%20Pie%20Chart%20HTML%20Markers) where HTML markers are used to represent clusters. Each cluster marker is a pie chart where each slice of the pie is fully interactive.

**Comment by jonaseberle** [comment]
Ah, I see. Thank you for the example @rbrundritt . Sorry to having derailed that issue. 
It is just that the first post mentions an example where the marker is just an image - which is exactly possible with a symbol geoJSON layer.

**Comment by mourner** [comment]
Hey, heads up that I'm working on an official example at the moment — will aim for something like on the screenshot above. Stay tuned in the nearest week!

**Comment by mourner** [comment]
The new example with HTML clusters and property aggregation is live — check it out! Thanks to everyone who participated in the thread, and let me know if there's anything we can improve / clarify. https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/

**Comment by smitraval** [comment]
Excellent work!! Although, I think the only thing missing is when we click on the marker it should zoom in the map. Is there any way I can achieve this functionality?

**Comment by andrewharvey** [comment]
@smitraval The normal symbol clustering demo does this https://docs.mapbox.com/mapbox-gl-js/example/cluster/

```js
// inspect a cluster on click
map.on('click', 'clusters', function (e) {
  var features = map.queryRenderedFeatures(e.point, { layers: ['clusters'] });
  var clusterId = features[0].properties.cluster_id;
  map.getSource('earthquakes').getClusterExpansionZoom(clusterId, function (err, zoom) {
    if (err)
      return;
 
    map.easeTo({
      center: features[0].geometry.coordinates,
      zoom: zoom
    });
  });
});
```

**Comment by smitraval** [comment]
@andrewharvey Thank you very much for your quick reply. I will try the same and update the final result here for future reference.

**Comment by smitraval** [comment]
Hi @andrewharvey , Using your example I have successfully created marker clusters with images, However I am still stuck at a point where I need to replace un-clustered points with custom html div. Here is my code

`map.on('load', function () {

            // Add a new source from our GeoJSON data and set the
            // 'cluster' option to true. GL-JS will add the point_count property to your source data.
            map.addSource("hotels", {
                type: "geojson",
                // Point to GeoJSON data. This example visualizes all M1.0+ earthquakes
                // from 12/22/15 to 1/21/16 as logged by USGS' Earthquake hazards program.
                data: hotelGeo,//"https://docs.mapbox.com/mapbox-gl-js/assets/earthquakes.geojson",
                cluster: true,
                //clusterMaxZoom: 14, // Max zoom to cluster points on
                //clusterRadius: 40 // Radius of each cluster when clustering points (defaults to 50)
            });

            map.addLayer({
                id: "clusters",
                type: "circle",
                source: "hotels",
                filter: ["has", "point_count"],
                paint: {
                    // Use step expressions (https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-step)
                    // with three steps to implement three types of circles:
                    //   * Blue, 20px circles when point count is less than 100
                    //   * Yellow, 30px circles when point count is between 100 and 750
                    //   * Pink, 40px circles when point count is greater than or equal to 750
                    //"circle-color": "blue",
                    "circle-radius": 0
                }
            });

            // map.addLayer({
            //     id: "cluster-count",
            //     type: "symbol",
            //     source: "hotels",
            //     filter: ["has", "point_count"],
            //     layout: {
            //         "text-field": "{point_count_abbreviated}",
            //         "text-font": ["DIN Offc Pro Medium", "Arial Unicode MS Bold"],
            //         "text-size": 0
            //     }
            // });

            map.addLayer({
                id: "unclustered-point",
                type: "circle",
                source: "hotels",
                filter: ["!=", "cluster", true],
                paint: {
                    "circle-color": "red",
                    "circle-radius": 4,
                    "circle-stroke-width": 1,
                    "circle-stroke-color": "#fff"
                }
            });

            // objects for caching and keeping track of HTML marker objects (for performance)
            var markers = {};
            var markersOnScreen = {};
            var coordinates = {};

            function updateMarkers() {
                var newMarkers = {};
                var features = map.querySourceFeatures('hotels');
                // for every cluster on the screen, create an HTML marker for it (if we didn't yet),
                // and add it to the map if it's not there already
                for (var i = 0; i < features.length; i++) {
                    if (!features[i]) continue;

                    var coords = features[i].geometry.coordinates;
                    var props = features[i].properties;
                    if (!props.cluster) continue;
                    var id = props.cluster_id;
                    coordinates[id] = coords;

                    // console.log("check id", id)

                    var marker = markers[id];
                    if (!marker) {

                        /*** For cluster */
                        var el = document.createElement('div');
                        var features = map.queryRenderedFeatures({ layers: ['clusters'] });

                        if (!features[i]) continue;

                        var point_count = features[i].properties.point_count_abbreviated;
                        el.className = 'marker';
                        el.id = id;
                        el.style.backgroundImage = 'url("' + Marker + '")';
                        el.style.width = '41px';
                        el.style.height = '48px';
                        el.innerHTML = "<span style='width: 41px;line-height: 42px;text-align:center;display:block'>" + point_count + "</span>"

                        // console.log("check counts", point_count);
                        marker = markers[id] = new mapboxgl.Marker({ element: el }).setLngLat(coords);

                        el.addEventListener('click', () => {
                            var features = map.queryRenderedFeatures({ layers: ['clusters'] });
                            if (!features[0]) return;
                            var clusterId = features[0].properties.cluster_id;
                            map.getSource('hotels').getClusterExpansionZoom(clusterId, function (err, zoom) {
                                if (err)
                                    return;

                                // map.easeTo({
                                //     center: coordinates[el.id],
                                //     zoom: zoom
                                // });

                                map.flyTo({
                                    center: coordinates[el.id],
                                    zoom: zoom,
                                    speed: .75
                                });

                                //console.log("check coords", coordinates)
                                // for every marker we've added previously, remove those that are no longer visible
                                //map.off("zoom");

                            });

                        }

                        );

                    }
                    newMarkers[id] = marker;

                    if (!markersOnScreen[id])
                        marker.addTo(map);
                }
                //console.log("check coords", coordinates)
                // for every marker we've added previously, remove those that are no longer visible
                for (id in markersOnScreen) {
                    //console.log("in for loop", newMarkers[id])
                    if (!newMarkers[id])
                        markersOnScreen[id].remove();
                }
                markersOnScreen = newMarkers;
            }

            // after the GeoJSON data is loaded, update markers on the screen and do so on every map move/moveend
            map.on('data', function (e) {
                if (e.sourceId !== 'hotels' || !e.isSourceLoaded) return;
                map.on('zoom', updateMarkers);
                map.on('moveend', updateMarkers);
                updateMarkers();
            });

            map.on('mouseenter', 'clusters', function () {
                map.getCanvas().style.cursor = 'pointer';
            });
            map.on('mouseleave', 'clusters', function () {
                map.getCanvas().style.cursor = '';
            });
        });`

See those red points in map? I need to change them with HTML div. Any help would be appreciated. 

![hotels-map](https://user-images.githubusercontent.com/37876589/55684205-41a3fd00-5951-11e9-8145-44af7afef0f2.png)

**Comment by NeonCreativeStudios** [comment]
@smitraval I've simplified your code and it now works for custom markers and clusters. And at the end of the updateMarkers function, there's a simple loop that removes unused markers and clusters :)

![image](https://user-images.githubusercontent.com/49883221/59383642-41145200-8d58-11e9-8f14-92d6e6115621.png)


```    
    map.addSource("addresses", {
        type: "geojson",
        data: geojson,  //"https://docs.mapbox.com/mapbox-gl-js/assets/earthquakes.geojson",
        cluster: true,
        clusterMaxZoom: 13, // Max zoom to cluster points on
        clusterRadius: 50 // Radius of each cluster when clustering points (defaults to 50)
    });
    
    map.addLayer({
        id: "clusters",
        type: "circle",
        source: "addresses",
        filter: ["has", "point_count"],
        paint: {
            "circle-radius": 0
        }
    });


    // Store IDs and cluster/marker HTMLElements
    const markers = new Map();

    function updateMarkers(){
        const features = map.querySourceFeatures('addresses');
        const newMarkers = [];

        for (let i = 0; i < features.length; i++) {
            const coords = features[ i ].geometry.coordinates;
            const props = features[ i ].properties;
            const featureID = features[ i ].id;
            
            const clusterID = props.cluster_id || null;

            if (props.cluster && markers.has('cluster_'+clusterID)) {
                //Cluster marker is already on screen
                newMarkers.push('cluster_'+clusterID);

            } else if (props.cluster) {

                //This feature is clustered, create an icon for it and use props.point_count for its count

                var el = document.createElement('div');
                el.className = 'mapCluster';
                el.style.width = '60px';
                el.style.height = '60px';
                el.style.textAlign = 'center';
                el.style.color = 'white';
                el.style.background = '#16d3f9';
                el.style.borderRadius = '50%';
                el.innerText = props.point_count;
                const marker = new mapboxgl.Marker(el).setLngLat(coords);
                marker.addTo(map);
                newMarkers.push('cluster_'+featureID);
                markers.set('cluster_'+clusterID,el);
                
            } else if (markers.has(featureID)) {

                //Feature marker is already on screen
                newMarkers.push(featureID);

            } else {
                
                //Feature is not clustered and has not been created, create an icon for it
                const el = new Image();
                el.style.backgroundImage = 'url(https://placekitten.com/g/50/50)';
                el.className = 'mapMarker';
                el.style.width = '50px';
                el.style.height = '50px';
                el.style.borderRadius = '50%';
                el.dataset.type = props.type;
                const marker = new mapboxgl.Marker(el).setLngLat(coords);
                marker.addTo(map);
                newMarkers.push(featureID);
                markers.set(featureID,el);
                
            }
            
        }

        //Let's clean-up any old markers. Loop through all markers
        markers.forEach((value,key,map) => {
            //If marker exists but is not amongst the new markers
            if (newMarkers.indexOf(key) === -1) {
                console.log('deleting key: '+key);
                //Remove it from the page
                value.remove();
                //Remove it from markers map
                map.delete(key);
            }
        });

    };`

    map.on('data', function (e) {
        if (e.sourceId !== 'addresses' || !e.isSourceLoaded) return;
        map.on('moveend', updateMarkers); // moveend also fires on zoomend
        updateMarkers();
    });
```
Console output showing markers and clusters getting removed. They are removed when they go off screen, but also when they switch from a marker to a cluster and vice versa.
![image](https://user-images.githubusercontent.com/49883221/59383556-07dbe200-8d58-11e9-84d8-3c82a0aae910.png)

**Comment by livthomas** [comment]
I have just read this thread and if I understand it correctly it is simply not possible to easily create a cluster of HTML markers. You either need to add them as a GeoJSON layer and render them using images. Or you can add them to a map directly as markers but you need to manage the hiding logic manually. Am I right or am I missing something?

I create my markers purely by using HTML and CSS. I want to add them to a cluster which would deal with the hiding logic and show the number of hidden markers (just like Leaflet plugins do it) without me having to implement anything. Is it possible or not?

**Comment by mvtenney** [comment]
@NeonCreativeStudios, thanks for your efforts! While running your example code, I am seeing the clustering work beautifully, but the max zoom seems to be ignored, and it is not unclustering into individual markers when zooming far enough.

**Comment by livthomas** [comment]
@mvtenney I am not sure if you encountered the same problem as me but unclustering was very unreliable in my application so I had to add the following line to `onMoveEnd` callback:
```typescript
map.once('idle', () => updateMarkers());
```
The only problem is that it waits not only for the zooming animation to end but also for map tiles loading so markers will appear after some time. However, AFAIK there is no `animationend` event in Mapbox GL JS and so I find this to be the only reliable solution.

**Comment by Bjmn7** [comment]
Hello, 
first of all, I thank you for your work to improve mapbox-gl-js.

I have been using it for a few months now and I am very satisfied with it, both in terms of performance and ease of use. But for almost 2 weeks now, I’ve been dealing with a problem concerning the HTML clustering. I think I've identified where the problem comes from, from which function but I don't know how to solve it, so I'm calling you. Below, the result and the function that, for me, is responsible for this rendering.

My data can change with different filters, the state of the data but also a date. When I change the date, some clusters present at the previous date remain on the map, they are not deleted as they should be in the function. And strangely, the ones that remain seem to prevent some new clusters from appearing. 

I thank you in advance for the time you will take to answer me.

   
    
    const markers: any = {};
    let markersOnScreen: any = {};

    function clusterConstructor(features: any, map: any) {
        const newMarkers: any = {};

        for (const feature of features) {
           const coords = feature.geometry.coordinates;
           const props = feature.properties;

           if (!props.cluster) continue;
           const id: number = props.cluster_id;

           let marker = markers[id];
           if (!marker) {
              const el = createDonutChart(props);
             marker = markers[id] = new mapboxgl.Marker({ element: el }).setLngLat(coords);
            }
          newMarkers[id] = marker;
          if (!markersOnScreen[id]) marker.addTo(map);
          }
        for (const id in markersOnScreen) {
           if (!newMarkers[id]) markersOnScreen[id].remove();
         }
        markersOnScreen = newMarkers;
       }


![Capture d’écran 2022-02-23 093724](https://user-images.githubusercontent.com/89902485/155286780-95372687-aeda-4d44-b207-06ddfa77cd3d.png)

**Comment by thuanmb** [comment]
@Bjmn7 the issue should come from here:
```
       let marker = markers[id];

       if (!marker) {

          const el = createDonutChart(props);

         marker = markers[id] = new mapboxgl.Marker({ element: el }).setLngLat(coords);

        }

       newMarkers[id] = marker;
       if (!markersOnScreen[id]) marker.addTo(map);
```
in above code, if the marker already in here, you don't update with the new content (data for another day). that why it's not get update.
you should always re-create/update the content of the marker (donut chart) when the date changed:
```
       let marker = markers[id];
       if (marker) {
          marker.remove()
        } 
        const el = createDonutChart(props);
        marker = markers[id] = new mapboxgl.Marker({ element: el }).setLngLat(coords);
        marker.addTo(map);
        newMarkers[id] = marker;
```

**Comment by Bjmn7** [comment]
@thuanmb Thank you very much, it works perfectly, great day to you.

**Comment by Bjmn7** [comment]
Hello, after multiple tests, it seems this solution slows down the map a lot when the function is fired by an idle event. If it is fired by a render event, it is even slower and the clusters move to the corner of the map at each render. Do you have any idea what could cause this @thuanmb ?

**Comment by thuanmb** [comment]
@Bjmn7 you can use some check to compare the props before re-rendering the clusters/markers

**Comment by OlejarzRafal** [comment]
> @smitraval Uprościłem twój kod i teraz działa on dla niestandardowych znaczników i klastrów. A na końcu funkcji updateMarkers znajduje się prosta pętla, która usuwa nieużywane znaczniki i klastry :)
> 
> ![obraz](https://user-images.githubusercontent.com/49883221/59383642-41145200-8d58-11e9-8f14-92d6e6115621.png)
> 
> ```
>     map.addSource("addresses", {
>         type: "geojson",
>         data: geojson,  //"https://docs.mapbox.com/mapbox-gl-js/assets/earthquakes.geojson",
>         cluster: true,
>         clusterMaxZoom: 13, // Max zoom to cluster points on
>         clusterRadius: 50 // Radius of each cluster when clustering points (defaults to 50)
>     });
>     
>     map.addLayer({
>         id: "clusters",
>         type: "circle",
>         source: "addresses",
>         filter: ["has", "point_count"],
>         paint: {
>             "circle-radius": 0
>         }
>     });
> 
> 
>     // Store IDs and cluster/marker HTMLElements
>     const markers = new Map();
> 
>     function updateMarkers(){
>         const features = map.querySourceFeatures('addresses');
>         const keepMarkers = [];
> 
>         for (let i = 0; i < features.length; i++) {
>             const coords = features[ i ].geometry.coordinates;
>             const props = features[ i ].properties;
>             const featureID = features[ i ].id;
>             
>             const clusterID = props.cluster_id || null;
> 
>             if (props.cluster && markers.has('cluster_'+clusterID)) {
> 
>                 //Cluster marker is already on screen
>                 keepMarkers.push('cluster_'+clusterID);
> 
>             } else if (props.cluster) {
> 
>                 //This feature is clustered, create an icon for it and use props.point_count for its count
> 
>                 var el = document.createElement('div');
>                 el.className = 'mapCluster';
>                 el.style.width = '60px';
>                 el.style.height = '60px';
>                 el.style.textAlign = 'center';
>                 el.style.color = 'white';
>                 el.style.background = '#16d3f9';
>                 el.style.borderRadius = '50%';
>                 el.innerText = props.point_count;
>                 const marker = new mapboxgl.Marker(el).setLngLat(coords);
>                 marker.addTo(map);
>                 keepMarkers.push('cluster_'+featureID);
>                 markers.set('cluster_'+clusterID,el);
>                 
>             } else if (markers.has(featureID)) {
> 
>                 //Feature marker is already on screen
>                 keepMarkers.push(featureID);
> 
>             } else {
>                 
>                 //Feature is not clustered and has not been created, create an icon for it
>                 const el = new Image();
>                 el.style.backgroundImage = 'url(https://placekitten.com/g/50/50)';
>                 el.className = 'mapMarker';
>                 el.style.width = '50px';
>                 el.style.height = '50px';
>                 el.style.borderRadius = '50%';
>                 el.dataset.type = props.type;
>                 const marker = new mapboxgl.Marker(el).setLngLat(coords);
>                 marker.addTo(map);
>                 keepMarkers.push(featureID);
>                 markers.set(featureID,el);
>                 
>             }
>             
>         }
> 
>         //Let's clean-up any old markers. Loop through all markers
>         markers.forEach((value,key,map) => {
>             //If marker exists but is not in the keep array
>             if (keepMarkers.indexOf(key) === -1) {
>                 console.log('deleting key: '+key);
>                 //Remove it from the page
>                 value.remove();
>                 //Remove it from markers map
>                 map.delete(key);
>             }
>         });
> 
>     };`
> 
>     map.on('data', function (e) {
>         if (e.sourceId !== 'addresses' || !e.isSourceLoaded) return;
>         map.on('moveend', updateMarkers); // moveend also fires on zoomend
>         updateMarkers();
>     });
> ```
> 
> Dane wyjściowe konsoli pokazujące usuwanie znaczników i klastrów. Są usuwane, gdy znikają z ekranu, ale także wtedy, gdy przechodzą ze znacznika do grupy i odwrotnie. ![obraz](https://user-images.githubusercontent.com/49883221/59383556-07dbe200-8d58-11e9-84d8-3c82a0aae910.png)

@NeonCreativeStudios 
i have a similar problem, when zooming the cluster, the markers are not visible. I tried to solve this problem but I couldn't. Can anyone help

**Comment by arenarium-dev** [comment]
Hey I dont know if its still relevant but I've been building a plugin for mapbox and other map providers. It organizes your map markers and displays them in a way to maximize readability and clarity. It also improves the performance of displaying a large number of markers.

![Image](https://github.com/user-attachments/assets/0b3065b3-123b-4aba-9313-35d89a458ce6)

If you want check it out: [https://arenarium.dev/?demo=bookings](https://arenarium.dev/?demo=bookings)
