### ISSUE TITLE
Overlay shows tiling artifacts on maps with pitch 

### ISSUE THREAD

**Issue by Neejoh** [mapbox/mapbox-gl-js#4497]
I'm currently running the latest version of Mapbox GL JS (mapbox-gl-js/v0.34.0) and I want to isolate one single country by adding semi opaque overlay layer over surrounding countries.
This pretty much works via the example on the help pages "[Style a single country](https://www.mapbox.com/help/style-single-country/#mapbox-studio)" setting the "not any of" filter on this layer; [example](http://imgur.com/a/Qvd7X)

Now the problem, I also want to set a little bit of pitch. This causes artifacts flickering on overlaying tiles which is not ideal.

------

**mapbox-gl-js/v0.34.0**:

### Steps to Trigger Behavior

 1. Follow [Style a single country](https://www.mapbox.com/help/style-single-country/#mapbox-studio) example
 2. Set "not any of" filter with ISO3 "NLD" to exclude The Netherlands from this layer
 3. Set the map style to the newly created style
 4. Set a pitch of 55
 5. Zoom and pan to the south of The Netherlands to see distorted behavior

### Expected Behavior
I expect have a single overlay without distortion on panning and zooming

### Actual Behavior
Tiles are flickering and changing on panning on zooming.
![Example](http://i.imgur.com/vgPdRPu.png)

**Comment by andrewharvey** [comment]
This sounds like either #3320 or #3517

**Comment by mourner** [comment]
This really looks like #3517, but with a vector tile source instead of GeoJSON. Interesting.

**Comment by andrewharvey** [comment]
The test case I added to #3517 at https://github.com/mapbox/mapbox-gl-js/issues/3517#issuecomment-284326380 was a vector tile source, which I suspect is the same issue as the geojson one and as you say looks like the same issue here.

**Comment by mourner** [comment]
Let's close this issue as duplicate for now and track the progress at #3517 then. We'll reopen if resolving the latter doesn't resolve this one.
