### ISSUE TITLE
the range of pitch can be larger

### ISSUE THREAD

**Issue by tianbaolin** [mapbox/mapbox-gl-js#4504]
1.I find that  the pitch attribute  of map is limited in 0~60,so I suggest it can range from 0 to 90。so I can wander in  the map。
2.the transition effect  of pitch can be smooth,now it  change suddenly。
3.I also come across this problem #3338, so is there any other methods to solve this problem?

**Comment by andrewharvey** [comment]
> 1.I find that the pitch attribute of map is limited in 0~60,so I suggest it can range from 0 to 90。so I can wander in the map。

-> #3731
