### ISSUE TITLE
about limit of  fill-extrusion-height 

### ISSUE THREAD

**Issue by tianbaolin** [mapbox/mapbox-gl-js#4506]
In the fill-extrusion layer,the fill-extrusion-height is limited above 0, but when I draw a pool ,I need set it  a minus to show it。So I  hope the value of fill-extrusion-height  can support a  minus .

**Comment by andrewharvey** [comment]
You can see the previous issues about negative fill extrusion: https://github.com/mapbox/mapbox-gl-js/issues?q=is%3Aissue+negative+fill+extrusion+height+is%3Aclosed in particular #3401

**Comment by mourner** [comment]
Closing as a duplicate of #3401. See the explanation for not supporting this feature there.
