### ISSUE TITLE
PR-ish for building with webpack

### ISSUE THREAD

**Issue by d1manson** [mapbox/mapbox-gl-js#4507]
I have managed to build from source with webpack 2 using the following config:

```
  resolve: {
    ...
    alias: {
      webworkify: 'webworkify-webpack'
    }
 },
 module: {
    preLoaders: [
      {
         loader: 'json-loader',
         test: /\.json$/
      }
    ],
    loaders: [
      { // https://github.com/webpack-contrib/transform-loader#typical-brfs-example 
        test: /\.js$/,
        include: [
          path.resolve(__dirname, "node_modules/mapbox-gl")
        ],
        loader: "transform-loader?brfs"
      },
      {
        test: /\.js$/,
        loader: "babel-loader",
        include: [
         ...
          path.resolve(__dirname, "node_modules/mapbox-gl")
        ],
        query: {
          presets: ['es2015'],
          plugins: ["transform-flow-comments", "transform-class-properties"]
        }        
      },
```

with the following `npm  install`ed: 

`flow-babel-webpack-plugin` `transform-loader`   `webworkify-webpack`

However I did have to make one tiny change to the `mapbox-gl` source itself:

**src\util\browser\web_worker.js:5** - add `.resolve` to `require` as stated [here](https://github.com/borisirota/webworkify-webpack#let-w--workrequireresolvemodulepath--options)...
```
const workerURL = window.URL.createObjectURL(
            new WebWorkify(require.resolve('../../source/worker'), {bare: true}));
```

Could you make this change in a browserify-compatible way...I haven't used browsersify myself so I don't know what that might involve.

Thanks

**Comment by mourner** [comment]
Thanks! We don't intend to support building the source with Webpack though. In your Webpack applications, you can just use the browserify-built version of Mapbox GL JS.

**Comment by d1manson** [comment]
That's a shame as it seems like it basically works already...well, this issue is here now for people to google for!
I guess it should be possible to use a webpack `alias` or `loader` in the config to patch this one call without changing the source.

**Comment by mourner** [comment]
It "basically works" until it doesn't. Mapbox GL JS is an incredibly complex codebase that takes a lot of resources to maintain, and having to maintain two build systems at the same time is a huge burden without much benefit. We tried to do this before (search the issues for "webpack"), and got burned.
