### ISSUE TITLE
Add Mapbox GL JS to the list of libraries on JSBin

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#4508]
Adding a library to the list on JSBin looks pretty simple:

 - Open a PR adding it to https://github.com/jsbin/jsbin/blob/master/public/js/editors/libraries.js
 - tag the PR with the `type: library` label

This might make it slightly more convenient for a user to put together a test case demonstrating a bug, or to quickly prototype an idea for their own reasons.  But it would also require adding another step to our release process to update the version available in the list with a new PR.  Worth it? 🤷‍♂️

**Comment by stepankuzmin** [comment]
Good idea! I've made a PR for this https://github.com/jsbin/jsbin/pull/3019

**Comment by mollymerp** [comment]
great idea! will we have to update jsbin manually when we want to bump the version?

**Comment by anandthakker** [comment]
@mollymerp yeah, we will have to put in a new PR each time, which adds another step to the release process 😬

**Comment by rowanwins** [comment]
A good workaround might be to use unpkg 

If you just use the general npm package name it will always point to the most recent version available on npm
eg `https://unpkg.com/mapbox-gl` automatically redirects `https://unpkg.com/mapbox-gl@0.34.0`

Let me know if you need more info.

**Comment by stepankuzmin** [comment]
Yes, unpkg.com is good solution! I've updated the PR.

**Comment by jfirebaugh** [comment]
Upstream PR is open and is waiting for a response. Closing here since it doesn't seem to be actionable from our side.
