### ISSUE TITLE
Mapbox GL JS V0.32.1 Marker's popup wont work on IOS

### ISSUE THREAD

**Issue by sasidharlanka** [mapbox/mapbox-gl-js#4510]
Hi All, I am using Mapbox GL JS V0.32.1. I have developed an ionic app. The Markers Works fine in android device / Chrome / as well as in safari. The same wont work on IOS simulator or on iPhone device, it doesn't work.

Please look into the issue and help me resolve it.

**Comment by mourner** [comment]
Can you reproduce the issue in a minimal JSFiddle test case with just GL JS and no frameworks like Ionic?

**Comment by sasidharlanka** [comment]
@mourner , I am new to JSFiddle. I am psoting my onClick event code for your reference. 

  map.on('click', function(e){
        var result = map.queryRenderedFeatures(e.point, {layers:['unclustered-points']});
        if(result.length){ 
            var popup= new mapboxgl.Popup({closeButton:true});
            console.log(result);
            var cname = result[0].properties.cname;
            var ctype = result[0].properties.ctype;
            var ytd =  result[0].properties.ytd;
            console.log(cname);
            map.flyTo({center: [e.lngLat.lng, e.lngLat.lat], bearing: 0, pitch: 0, speed: 0.9, curve: 1.1});
            //(feature.geometry.coordinates)
            popup.setLngLat(e.lngLat).setHTML('<p>'+cname+ ytd +'</p>').addTo(map);
        }
        // console.log("lat long cordinates" + e.lngLat);
        });

**Comment by jfirebaugh** [comment]
Thanks @sasidharlanka, but we will need a complete self-contained example, as we aren't able to debug problems with complex codebases involving 3rd party libraries without that. Please reopen if you can provide this.

**Comment by tessaalexander-uob** [comment]
In case anyone else finds this.  Try the solution suggested here: https://github.com/mapbox/mapbox.js/issues/893
