### ISSUE TITLE
Data driven text-color inconsistent at different zoom levels

### ISSUE THREAD

**Issue by YunjieLi** [mapbox/mapbox-gl-js#4514]
Demo https://bl.ocks.org/yunjieli/e964a843d42a4dd790a215cf14f58051

### Steps to trigger:
- Add a symbol layer
- Set `text-color` to DDS (`type: 'identity'`)

### Expected behavior

The '>' text will be color coded in a way consistent across zoom levels and the same as the `straight` line layer which uses the exact same data source.

### Actual behavior

The text-color is mixed up at lower ZLs (5.5 below), and does not match that of the straight line underneath. This is true at places where there is only one line so it's not crowded out by others.
At higher ZLs the colors are correct.

![image](https://cloud.githubusercontent.com/assets/12749701/24433206/f70abdcc-13db-11e7-9846-349c1b870f3d.png)

cc @mollymerp

**Comment by mollymerp** [comment]
per chat, upon initial inspection it looks like overlapping lines in the source are the cause of this behavior. please reopen if you're able to reproduce the bug with a minimal test case 🙇‍♀️

**Comment by YunjieLi** [comment]
ty @mollymerp !
