### ISSUE TITLE
DragRotateHandler still can drag & rotate when map.dragRotate.disable() is called 

### ISSUE THREAD

**Issue by paquettea** [mapbox/mapbox-gl-js#4517]
**0.34**:

### Steps to Trigger Behavior

 1. load  map
 2. call map.dragRotate.disable()
 3. ctrl + drag the map to see it rotating

### Expected Behavior

map should not rotate

### Actual Behavior

map is rotating.

I looked up the source code, and the isEnabled value is never queried to check if the event should take place. Only ignoreEvent and isActive is taken into account.

**Comment by paquettea** [comment]
problem was related to an external lib.

**Comment by plumdumpling** [comment]
@paquettea do you remember which external lib it was? I have the same issue.
