### ISSUE TITLE
Third Party Example - 404 - API_KEY update required

### ISSUE THREAD

**Issue by MoKob** [mapbox/mapbox-gl-js#4520]
Repost from over at mapbox.com (https://github.com/mapbox/www.mapbox.com/issues/1221)

<img width="1065" alt="screen shot 2017-03-29 at 08 32 23" src="https://cloud.githubusercontent.com/assets/12932279/24441559/5b710568-145a-11e7-8541-44a15ac376fd.png">

The third party example on https://www.mapbox.com/mapbox-gl-js/example/third-party/ seems to rely on a non-responsive server.

The above view is what is shown in the example. The javascript console shows quite a few errors of the form `Failed to load resource: the server responded with a status of 404 (Not Found)` for queries of the form https://vector.mapzen.com/osm/all/6/32/37.mvt?api_key=vector-tiles-LM25tq4.

This is followed by am `Error: Not Found Evented.fire @ evented.js:104`.

Since the server itself seems responsive, I assume that our API key might be outdated/blocked.
Querying https://vector.mapzen.com/osm/all/6/32/37.mvt direclty, and without a api_key, shows `Hello! You did not include a Mapzen API key with your request. Please sign up for a free key at https://mapzen.com/developers`.

**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. visit the website

### Expected Behavior

A beautiful map, even though with wrong tiles.

### Actual Behavior

Green map, not showing anything but the background.

**Comment by mollymerp** [comment]
Thanks for reporting @MoKob! Interestingly, the example seems to work for me. 
![image](https://cloud.githubusercontent.com/assets/2425307/24520983/44a9e418-153f-11e7-953c-e38a4b2daeff.png)

**Comment by MoKob** [comment]
hmmm. I tried this with safari, chrome (on my macbook) and with firefox on my desktop at home. All show the same green map and errors of tiles not being found.
Could there possibly be some connection to where the request is coming from? (e.g. Germany over US?). @daniel-j-h can you maybe check if the https://www.mapbox.com/mapbox-gl-js/example/third-party/ works on your machine, to get another sample from Germany?

**Comment by daniel-j-h** [comment]
Same for me with both Firefox and Chrome. I'm seeing 403s and 404s:

![error-example](https://cloud.githubusercontent.com/assets/527241/24542575/6f62eeda-15fc-11e7-9681-ef787094c907.png)

**Comment by mollymerp** [comment]
that is very strange, indeed. I wonder if Mapzen is banned in Germany 🙅 🇩🇪

**Comment by mollymerp** [comment]
Seems this is also an issue from requests originating in India. We should maybe find another external source to use in this example? cc @pratikyadav

**Comment by pratikyadav** [comment]
Fixed via https://github.com/mapbox/mapbox-gl-js/pull/4760
<img width="1196" alt="screen shot 2017-05-29 at 3 20 41 pm" src="https://cloud.githubusercontent.com/assets/12744420/26545219/74398892-4482-11e7-8ad0-ca921b19a924.png">


Thank you @mollymerp
