### ISSUE TITLE
Mapbox GL JS don't scroll with maximum level on safari.

### ISSUE THREAD

**Issue by dnapolloteam** [mapbox/mapbox-gl-js#4527]
**mapbox-gl-js version**:
v0.34.0
### Steps to Trigger Behavior

 1.Open mapbox gl js on safari
 2.Enable scrollwheel for this map
 3.Can't scroll with maximum level

### Expected Behavior
Can scroll with maximum level on safari.
### Actual Behavior
Can't scroll with maximum level

**Comment by mollymerp** [comment]
@dnapolloteam – thank you for reporting your issue. I'm afraid I don't know what you mean by `maximum level`. Could you clarify what you expect to see and/or provide a minimal test case?

For reference, the `Map`'s maximum zoom level is configurable: https://www.mapbox.com/mapbox-gl-js/api/#map#setmaxzoom

**Comment by dnapolloteam** [comment]
This issue happen when I don't set maximum zoom level so It will get default 20 so I can't scroll mouse until 20 on safari just < 18 . So I try to set maximum level with value 16 so It work well on cross browser.

**Comment by anandthakker** [comment]
@dnapolloteam could you provide an example using https://jsbin.com/ that demonstrates the problem?  That will likely help to isolate the issue and find a solution.

**Comment by dnapolloteam** [comment]
Sorry for later response. Thanks everybody for answer. My issue resolve I forget to set maximum level zoom at 16. At the moment it work well. Thanks again.
