### ISSUE TITLE
flyTo() "crashes"/force reloads map 

### ISSUE THREAD

**Issue by gorbypark** [mapbox/mapbox-gl-js#4529]
Version: 0.34 and below
When calling the flyTo function from an external element, it sometimes "crashes" the map (the map reloads to default view).  The flyTo animation begins and then the entire map just reloads.  No errors in the Chrome console.  The map has ~900 GeoJSON points loaded from an URL with a refresh rate of 5 seconds.  Initially I had suspicions it was "crashing" when a URL refresh was happening while the animation was running, but turning off the the GeoJSON polling resulted in the same behaviour.

Subjectively, the "crash" happens most often when the map is initially loaded and all points are viewable.  Usually (~90%) of the time after it "crashes" once, it then works flawlessly.  10% of the time it will continue "crashing" until the map is zoomed in by 4 or 5 levels, and then works flawlessly, even when fully zoomed out.

Also subjectively it seems to happen less when the flyTo animation is slowed down, but does not eliminate it.

Tested on Chrome for Windows, Chrome for macOS, Firefox for Windows and Chrome/Firefox for Android.  All exhibit similar behaviour to varying degrees.

The code causing the behaviour is as follows:

```
document.getElementById('btn-flyto-top').addEventListener('click', function() {
    map.flyTo({
        center: [-122.948759342268, 50.0734454995302],
        zoom: 15
    });
});
```

**Comment by jfirebaugh** [comment]
Thanks for the report @gorbypark. Can you please provide a minimal self-contained example that demonstrates the issue? That would greatly increase the chances of our being able to reproduce and fix the problem.

**Comment by gorbypark** [comment]
> Can you please provide a minimal self-contained example that demonstrates the issue? That would greatly increase the chances of our being able to reproduce and fix the problem.

This is about as stripped down as I can make it. `https://wbsnowmaking.com/assets/mastersnow/`

**Comment by jfirebaugh** [comment]
Thanks. What do I need to do to trigger the issue?

**Comment by gorbypark** [comment]
Sorry, I should have explained that.  If you click the "eye" icon on the upper right it will bring up a menu with options to zoom around.  If you click on any of those buttons it will trigger the issue.

**Comment by jfirebaugh** [comment]
I'm pretty sure this reload isn't caused by Mapbox GL JS, and is just the default behavior of a `button` element. Try setting `type="button"` to override the default of `type="submit"`.

**Comment by gorbypark** [comment]
This was exactly the problem.  Thank you very much and sorry for the waste of time.
