### ISSUE TITLE
Rendering error when a transparent image is added via Map#addImage

### ISSUE THREAD

**Issue by ozeron** [mapbox/mapbox-gl-js#4534]
After release 0.34.0 I was playing with `Map#addImage` functionality, trying to load images as icons. I added simple png image with transparent background and notice weird white outline, which appeared around it. 

For example I cropped rocket from file, which is being loaded for sprites. ![d2ayr08pmg00aaaaaelftksuqmcc](https://cloud.githubusercontent.com/assets/3617121/24621601/b8043c92-18aa-11e7-9305-db24dc6eb880.png)
And tried to add it to Map: (left is loaded manually, right is yours)
![2017-04-03 20 19 18](https://cloud.githubusercontent.com/assets/3617121/24621636/db63cf5e-18aa-11e7-8061-efedac42ab9e.png)
Mapbox genereted very poor white outline for this icon.
[Here is JSBin for reference: ](https://jsbin.com/purime/2/edit?html,js,output)

How I can improve quality of loaded image?

**mapbox-gl-js version**: v0.34.0

### Expected Behavior
Mapbox load image with same outlines as original image, which was loaded.
### Actual Behavior
Mapbox add it's own outlines.

**Comment by anandthakker** [comment]
Thanks for the report and the test case, @ozeron!

At first glance, it looks to me like `addImage` is not handling the transparency of the image properly.

**Comment by jfirebaugh** [comment]
`addImage` needs to premultiply the image data before copying it into the texture, as is done by [`ImageSprite`](https://github.com/mapbox/mapbox-gl-js/blob/b9e10b939c6a3fe5d7ecac209f751b4871970ede/src/style/image_sprite.js#L47-L53).

**Comment by ozeron** [comment]
@jfirebaugh Thank you, premultiplying image data fixes this issue 👍 
Still it is looks like a bug.

**Comment by anandthakker** [comment]
@ozeron agreed, still a bug!

**Comment by tbernas** [comment]
This blocker  prevents us from releasing a variety of new overlays. The most critical overlays in that group pertain to traffic incidents and severe storm tracks.

Any timeline for fixing?
