### ISSUE TITLE
How can I put a nested field name while defining a data driven styling?

### ISSUE THREAD

**Issue by agaase** [mapbox/mapbox-gl-js#4544]
My geojson data (converted to mbtiles) has following format
` "properties": {
        "excessTime": {
          "one": 123,
          "two" : 134
        }
   }
`

I want to define a style which can style based on the fields inside excessTime; something like

`
'fill-color': {
					"property" : "excessTime.one",
					"type": "interval",
					"stops" : [
					]
				},
`
Is it possible right now with the current data driven styling API?

**Comment by jfirebaugh** [comment]
It's not possible right now; you'll need to flatten the properties in the source data. A request for nested property support in tiles is tracked in https://github.com/mapbox/vector-tile-spec/issues/75.
