### ISSUE TITLE
Clipping Layers with GeoJSON

### ISSUE THREAD

**Issue by beelo** [mapbox/mapbox-gl-js#4546]
Hi,

Just wondering if there is a way to clip layers in mapbox with a Geojson feature,

Thanks

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by beelo** [comment]
I guess this will be a feature request, because I have no found a way to achieve this:
To be able to clip layers with GeoJSON features,

**Comment by shongololo** [comment]
I second this. It would be very useful to be able to clip layers, especially when managing performance on complex layers.

**Comment by bcartmell** [comment]
I too, would like to see this functionality added to mapbox-gl-js.  I currently have a need to mask an image layer with a geojson polygon.

**Comment by bcartmell** [comment]
Since this issue has been closed after being considered a 'how do I' question, I have opened a new feature request as issue #7018.
