### ISSUE TITLE
Layer Not Shown Past Tileset Max Zoom

### ISSUE THREAD

**Issue by x9xjdzz9** [mapbox/mapbox-gl-js#4564]
I have a vector tileset with a max zoom level of 11. When I zoom at level 12 or higher the layer for that tileset is no longer shown. This worked in version 0.34, but is broken in version 0.35.

Example: https://jsfiddle.net/x9xjdzz9/e7h55nvt/

**Comment by mollymerp** [comment]
Hi @x9xjdzz9 , thanks for the report + test case. This seems to be a symptom of https://github.com/mapbox/mapbox-gl-js/commit/8fd6e009084f7fbefbdf0fb3ae243e89aca41361
