### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by mgosline** [mapbox/mapbox-gl-js#4566]

**Comment by mollymerp** [comment]
yes! I can do that!

for my own reference, I'll be changing the assets found at:

* [ ] [mapbox.js](https://github.com/mapbox/mapbox.js/blob/e9157736b663ce5d7ab022ee7aaf75efb335e91b/theme/style.css#L896)
* [ ] [Mapbox GL JS](https://github.com/mapbox/mapbox-gl-js/blob/e08ccfbe2806855dc1e2cce622798ff4b200fdb3/dist/mapbox-gl.css#L109)
* [ ] [api-gl](https://github.com/mapbox/api-gl/blob/8f1b3cd4618d8a3bcb8701bcd4257c6ab7afe58a/lib/img/mapbox.svg) (mapbox/api-gl#774)
