### ISSUE TITLE
Fix broken inline tag links in documentation

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#4568]
The documentation TOC has links like `https://www.mapbox.com/mapbox-gl-js/api/#map#easeto` which correctly take you to the right anchor in the document.

But in [`https://www.mapbox.com/mapbox-gl-js/api/#map#fitbounds`](https://www.mapbox.com/mapbox-gl-js/api/#map#fitbounds) in the options the reference to `Map#easeto` has the link `https://www.mapbox.com/mapbox-gl-js/api/#mapeaseto` which doesn't work, it's coming from an inline tag like `{@link Class#method}`.

Should the TOC and anchors be `#mapeaseto` or should the `{@link Map#easeTo}` in the JSdoc go through as `#map#easeto`? I suspect the later.

**Comment by asantos3026** [comment]
@andrewharvey Do all of the inline tag links need to be changed into this format?

```#map#easeto```

**Comment by andrewharvey** [comment]
@asantos3026 My thoughts are that https://tools.ietf.org/html/rfc3986#section-3.5 doesn't seem to restrict the use of the `#` char within a fragment, so the current format that the TOC and anchors use of `#map#easeto` is probably preferred over `#mapeaseto`. But it's not my call to make.

The inline `{@link }` style links appear in be in the correct format like `{@link Map#easeTo}` to match the TOC and document anchors, so there is nothing to change there.

This is either an issue in documentation.js or how it's invoked by GL JS, but someone more knowledgeable of documentation.js and GL JS documentation could confirm this.

The `[]()` style links which are also broken is being tracked at https://github.com/mapbox/mapbox-gl-js/issues/3680#issuecomment-293228951.

**Comment by asantos3026** [comment]
@andrewharvey Thanks for the response. Okay, so someone needs to confirm this part of the issue before it can be worked on.

`This is either an issue in documentation.js or how it's invoked by GL JS, but someone more knowledgeable of documentation.js and GL JS documentation could confirm this.`
