### ISSUE TITLE
Unable to set different image for cluster and marker icon

### ISSUE THREAD

**Issue by jack-solutions** [mapbox/mapbox-gl-js#4570]
### Below  is the code for plotting marker and cluster
    // for source     
    map.addSource('markers', {
            "type": "geojson",
            "data": {
                "type": "FeatureCollection",
                "features": $scope.feature
            },
            "cluster": true,
            "clusterMaxZoom": 14, // Max zoom to cluster points on
            "clusterRadius": 50 // Radius of each cluster when clustering points (defaults to 50)
        });

        // For plotting marker
        map.addLayer({
            "id": "markers",
            "source": "markers",
            "type": "symbol",
            "filter": ["!has", "point_count"],
            "layout": {
                "icon-image": "emptyMarker_solid",
                "icon-size": 0.06,
                "icon-offset": [0, -200],
            }
        });

        // Add a layer for the clusters' count labels
        map.addLayer({
            "id": "cluster-count",
            "type": "symbol",
            "source": "markers",
            "filter": ["has", "point_count"],
            "layout": {
                "text-field": "{point_count}",
                "text-font": [
                    "Arial Unicode MS Bold"
                ],
                "text-size": 13,
                "text-offset": [0, -2],
                "text-anchor": "bottom",
                "icon-image": "emptyMarker",
                "icon-size": 0.12,
                "icon-offset": [0, -200],
            }
        });
 

### Expected Behavior
It Should display cluster icon and marker icon differently

### Actual Behavior
However, It display only one icon at a time when we allocate different name for both , but if we provide same icon name for  cluster and marker it works well

Is it possible to allocate different icon image for cluster and marker?

**Comment by anandthakker** [comment]
@jack-solutions without a working example to look at, it's hard to say for sure what's happening here.  Could you possible provide an example that demonstrates the problem using https://jsbin.com/?

**Comment by mourner** [comment]
@jack-solutions hey, any updates?

**Comment by XavierLeTohic** [comment]
Same issue here (also related to #6398)

Here's a [jsfiddle](http://jsfiddle.net/Lw3guzk5/25/) (the code is correct but there is an unexpected error on jsfiddle I don't know why).

Using ```"filter": ["has", "point_count"]``` "point_count" seems always null or 0. Only unclustered points are displayed.

My code is based on [this cluster example of mapbox-gl-js](https://www.mapbox.com/mapbox-gl-js/example/cluster/)

**Comment by XavierLeTohic** [comment]
I found something !

In the jsfiddle I used ```type: "circle"``` but this is my current code : 

```javascript
                  this.map.addLayer({
                    id: "clusters",
                    type: "symbol",
                    source: "markers",
                    filter: ["has", "point_count"],
                    layout: {
                      "icon-image": '{icon}',
                      "icon-size": 1,
                      "icon-anchor": 'bottom',
                      "icon-allow-overlap": true
                    },
                  });

                  this.map.addLayer({
                      id: "unclustered-point",
                      type: "symbol",
                      source: "markers",
                      filter: ["!has", "point_count"],
                      layout: {
                        "icon-image": "marker",
                        "icon-size": 1,
                        "icon-anchor": 'bottom',
                        "icon-ignore-placement": true,
                        "icon-allow-overlap": true
                      },
                  });
```

This code is displaying only the layer with id : ```unclustered-point```

But replacing ```symbol``` by ```circle``` and ```layout``` by ```paint``` such as the cluster example of [mapbox-gl-js](https://www.mapbox.com/mapbox-gl-js/example/cluster/) it's working !

Why it isn't working with symbol ?

**Comment by marcuscaum** [comment]
Upon this one, this is still not working, I can't use `icon-image` with `type: symbol` for a cluster item as @XavierLeTohic said

**Comment by Pictor13** [comment]
I can confirm.

Using the same icon for markers and cluster works.
Setting custom icons for markers makes them disappear; only the cluster icon is visible.

Can we reopen?

/reopen

**Comment by sunilThinkbiz** [comment]
can we add a background color?
