### ISSUE TITLE
Labels change by themselves when zooming in and out

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox-gl-js#4572]
I'm getting a strange behaviour of labels for `symbol` layers.

Labels do show up on the map, but when zooming in and out they change values by themselves. I guess they get values from neighbouring labels, but maybe not. I've also noticed, that this happens often with short 1-character labels.

Here's a [video](https://www.dropbox.com/s/1lz2h13rbu8bsu1/address_label_problem.mov?dl=0) that illustrates this behaviour. Look at address labels `7` and `4` to the left and above cursor. When zooming in or out they swap values. (feature labelled with `7` has really a value of `6`).

Another [example](https://www.dropbox.com/s/cn1mtce1s10oy6i/more_strange_labels.mov?dl=0) with labels coming from 3 concatenated fields. Look at how they change values when crossing a particular zoomlevel. Must be some kind of leak here.

**Comment by anandthakker** [comment]
Thanks for the report @nextstopsun!  Could you possibly include a code snippet (e.g. using https://jsbin.com/) that reproduces this problem in a working example?

**Comment by mourner** [comment]
@nextstopsun any updates?

**Comment by nextstopsun** [comment]
Sorry guys, this is most likely a server-side error. Need a bit more time to investigate. Will close this issue if confirmed.

**Comment by mourner** [comment]
Thanks! Let's close for now and reopen if you find the issue to be on the GL JS side.
