### ISSUE TITLE
Runtime style editing with Map#setPaintProperty causes all tiles to refresh

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#4575]
My application allows a user to create a choropleth of large vector tile sources. This is implemented as a style layer with a `fill-color` property and data-driven stops.

We also provide an editor UI to change the color scale of the choropleth between reds, blues, or greens, etc...

When a user changes the color scale, we generate the new color stops, and have two options for updating the style layer:

1. Remove the previous style layer, and reapply it with the new color stops.
2. Use the runtime api, `Map#setPaintProperty` and update just the `fill-color` property with the new stops.

Option 2 is preferred as [the example](https://www.mapbox.com/mapbox-gl-js/example/color-switcher/) shows a smooth transition between paint properties. However, it looks like data-driven style changes applied via `Map#setPaintProperty` still cause all the tiles to be reparsed/redrawn.

This is problematic in my application where we have large census tile sources that take a long time to parse, the tiles refreshing is detrimental to the user experience.

**mapbox-gl-js version**:
0.35.0

### Steps to Trigger Behavior

 1. Create a vector tile source and attach a style layer with data-driven `fill-color` property and stops.
 2. Apply new stops using the `Map#setPaintProperty` method

Here's JSBin example illustrating how changing a data-driven property refreshes all the tiles, while a basic functionality change performs a smooth transition: https://jsbin.com/rilayalilo/1/edit?html,js,output

### Expected Behavior

`Map#setPaintProperty` should not cause the entire style layer to be redrawn from the tiles up, even when making changes to data-driven properties.

### Actual Behavior

Data-driven changes applied with `Map#setPaintProperty` causes tiles to be reparsed/redrawn.

**Comment by anandthakker** [comment]
Thanks for this report @DannyDelott.  The underlying issue here is that updating a paint property to a data-driven value currently requires performing a "layout".  I've filed #4576 to track a refactor that could potentially improve the performance in cases like this.

**Comment by mourner** [comment]
Let's keep the discussion centralized in #4576.
