### ISSUE TITLE
Polyline with duplicate coordinate at the end not rendered correctly

### ISSUE THREAD

**Issue by jaapster** [mapbox/mapbox-gl-js#4579]
See this [example](https://jsbin.com/lidamukopu/edit?html,js,output).

A polygon is not always rendered correctly when the last two coordinates are identical.
In the example, when you remove the last coordinate the polygon is rendered correctly.

**Comment by kkaefer** [comment]
The last two coordinates of your polygon are identical, if you remove one of them, the polygon renders correctly.

**Comment by mourner** [comment]
@kkaefer that's in the description. :)
@jaapster the behavior is indeed weird. Also noting that a similar bug happens if you change the type to `MultiLineString`, meaning that it's not about polygons.

**Comment by jaapster** [comment]
@mourner For good measure I tried the coordinates with type "LineString. That yields a similar  result although the "gap" is positioned slightly differently.

**Comment by mourner** [comment]
Not a GeoJSON-VT issue. Looking into the GL line tesselation code now...

**Comment by mourner** [comment]
Fixed in #4634

**Comment by jaapster** [comment]
Thanks @mourner!
