### ISSUE TITLE
Can't click examples in documentation

### ISSUE THREAD

**Issue by aaronlidman** [mapbox/mapbox-gl-js#4586]
![footerclick](https://cloud.githubusercontent.com/assets/58878/25015051/0a6b66f0-202f-11e7-9df9-ddb0ed67e349.gif)

The footer is in the way.

### Steps to Trigger Behavior

 1. Go to any examples page. For example: https://www.mapbox.com/mapbox-gl-js/example/set-popup/
 2. Attempt to click the items on the bottom of the list.
 3. Can't click because the footer is in the way.

### Expected Behavior

Able to click the bottom items.

### Actual Behavior

Can't click the bottom items.

**Comment by jfirebaugh** [comment]
cc @tristen

**Comment by tristen** [comment]
Should be via ^

**Comment by andrewharvey** [comment]
@tristen This seems to be affecting https://www.mapbox.com/mapbox.js/example/v1.0.0/ too:

![selection_560](https://cloud.githubusercontent.com/assets/117278/25232074/824216c6-261d-11e7-82ec-775b0b73ae7e.png)
