### ISSUE TITLE
incorrect bounds on composited sources cause tiles not to load

### ISSUE THREAD

**Issue by karlguillotte** [mapbox/mapbox-gl-js#4587]
**mapbox-gl-js version**: 0.35.0 and above

### Steps to Trigger Behavior

 1. Upgrade from 0.34.0 to 0.35.0
 2. Zoom in and out to see blank tiles: http://avalanche-canada-dev.elasticbeanstalk.com/map

### Expected Behavior

I would expect all tiles to be displayed at all zoom levels. 

### Actual Behavior

Some tiles are blank as user zoom in and out. Here is an example of the issue: http://avalanche-canada-dev.elasticbeanstalk.com/map

I am still investigating the issue, wondering if others have experienced that issue. 

I am using the smart style setter and I have some markers on my map, But it does not matter that much because even the Mapbox map previewer shows blank tiles as well: https://api.mapbox.com/styles/v1/avalanchecanada/citxsc95s00a22inxvbydbc89.html?fresh=true&title=true&access_token=pk.eyJ1IjoiYXZhbGFuY2hlY2FuYWRhIiwiYSI6Im52VjFlWW8ifQ.-jbec6Q_pA7uRgvVDkXxsA#4.11/54.971/-124.276

Thanks for your hard work on Mapbox GL!

**Comment by mollymerp** [comment]
Hi @karlguillotte –  thanks for this report and I'm sorry this bug is affecting you. I'm pretty sure this is related to #4556 and the automatic compositing our maps API does (in addition to our API incorrectly stating the bounds of the composited source are the bounds of your avalanche source 😞 ) 

One thing you could try while we work on fixing this is turning off compositing in Mapbox Studio (or just staying on `0.34.0` until we ship a fix) 

![light___mapbox](https://cloud.githubusercontent.com/assets/2425307/25030880/330e5d1c-207d-11e7-988e-7ff34c9c5d05.jpg)

**Comment by karlguillotte** [comment]
Thanks @mollymerp ! I will stick to 0.34.0 for now.

**Comment by andrewharvey** [comment]
> our API incorrectly stating the bounds of the composited source

^ this in combination with #4556 I think should be release blocker/higher importance as it breaks a lot of maps.

People are running into this issue https://gis.stackexchange.com/questions/236428/not-all-tiles-loading-in-view-web-with-mapbox/236967#236967

Thankfully https://www.mapbox.com/api-documentation/#embed-a-style is still pinned at 0.34.0.

**Comment by mollymerp** [comment]
@andrewharvey yep I rolled back the api-styles share page to 0.34.0 on Friday because of this. This is a problem with another Mapbox service, not gl-js, so its not a release blocker for this repo. I should have a fix shipped on our Maps API soon – just keeping this issue open for visibility.

**Comment by andrewharvey** [comment]
This appears to be fixed in the API. :tada:

**Comment by mollymerp** [comment]
Yes! I pushed a fix to the maps API and bumped up the styles share page to v0.36.0. You should be good to go. Thanks for your patience!

**Comment by karlguillotte** [comment]
Amazing! Thanks @mollymerp
