### ISSUE TITLE
rel="noopener"

### ISSUE THREAD

**Issue by gertcuykens** [mapbox/mapbox-gl-js#4591]
https://developers.google.com/web/tools/lighthouse/audits/noopener

Please consider using `rel="noopener"` for your generated mapbox references

![image](https://cloud.githubusercontent.com/assets/863731/25052591/f0fce520-2152-11e7-8e32-29ca5d672df6.png)

**Comment by jfirebaugh** [comment]
Thanks for the suggestion, I agree! These links are not currently generated by GL JS itself, but we'll do this if we ever switch to generating them internally.

**Comment by areichman** [comment]
@jfirebaugh It looks like those values are set directly in the style JSON returned by the Mapbox API. Is there another public ticket for changing the values for those sources that we can track?

**Comment by jfirebaugh** [comment]
No, there's not a public ticket for it, sorry.

**Comment by MehdiSv** [comment]
Any news on this one?

**Comment by daveisfera** [comment]
If not by mapbox-gl-js, then where are these generated so we can open a ticket with that to get this fixed?
