### ISSUE TITLE
Is there a way to install mapbox through npm without need to build lib version?

### ISSUE THREAD

**Issue by pavelsl** [mapbox/mapbox-gl-js#4592]
I have tried to use npm instead of bower for all FE dependencies. And see a lot of trash when installing modules. Especially mapbox-gl-js it installs a lot of things, compiles library, tries to run yarn, tests and etc. 

Why we need to run tests during each installation? 
Isn't it better to run tests once and have comiled and tested version in repository? 
Tests run anyway outside any browser/environment scope i believe.

This question is not only about mapbox itself, more about having npm instead bower. Although might be other people tries to find the answer as well, so it could be useful to post it here.

**Comment by mourner** [comment]
Are you sure you have NPM set up correctly? If you install `mapbox-gl` as a dependency (e.g. `npm install mapbox-gl` in your project), it does not run any tests or compile anything, and only installs the most essential dependencies. 

Things you describe could only happen if you run `npm install` inside a `mapbox-gl-js` repository, but this is meant for contributors to the project, not consumers.

**Comment by pavelsl** [comment]
This is what I got today. Earlier I have seen even more. With tests notices.
Anyway there is some post install stuff. After map box installation node_modules folder contain a lot of modules. Even I install single mapbox-gl lib.

Don’t know why I don’t see any tests runs now, but sure have seen them. And my colleague as well.

wsc-000bs-Mac-mini:app wsc-000b$ npm i mapbox-gl
npm WARN deprecated geojson-area@0.1.0: This module is now under the @mapbox namespace: install @mapbox/geojson-area instead

> mapbox-gl@0.34.0 postinstall /Users/wsc-000b/projects/project1/node_modules/mapbox-gl
> cd src/style-spec && yarn || npm install

sh: yarn: command not found
@mapbox/mapbox-gl-style-spec@8.11.0-dev /Users/wsc-000b/projects/project1/node_modules/mapbox-gl/src/style-spec
├── csscolorparser@1.0.3 
Then goes some long tree.

app@0.6.2 /Users/wsc-000b/projects/project1/
└─┬ mapbox-gl@0.34.0 
  ├── @mapbox/gl-matrix@0.0.1 
  ├── @mapbox/shelf-pack@3.0.0 
  ├── @mapbox/unitbezier@0.0.0 
  ├── @mapbox/whoots-js@3.0.0 

Then goes some long tree. Again

wsc-000bs-Mac-mini:app wsc-000b$ 

May be the problem is in "postinstall": "cd src/style-spec && yarn || npm install” ?

Sorry, if I bother you Vladimir.

**Comment by mourner** [comment]
@pavelsl the postinstall script installs a few additional dependencies (needed for the style-spec module), but it shouldn't affect install times much. Tests and build scripts still don't run on install. I'll only consider reopening the issue if you can show steps to replicate the original issue consistently.
