### ISSUE TITLE
This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results

### ISSUE THREAD

**Issue by liwanchong04719** [mapbox/mapbox-gl-js#4594]
my program use the latest version mapbox-gl ,  when i use webpack packed up my program , the warn is 'This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results'

**Comment by jfirebaugh** [comment]
This is a known issue with webpack; see https://github.com/mapbox/mapbox-gl-js/issues/2742#issuecomment-267001402 for a workaround.

**Comment by liwanchong04719** [comment]
you  closed my issue, but i can't find how to solve my question

**Comment by liwanchong04719** [comment]
you closed my issue, but i can't find how to solve my question@ @jfirebaugh
