### ISSUE TITLE
Rectangular WMS tiles don't load

### ISSUE THREAD

**Issue by Naimikan** [mapbox/mapbox-gl-js#4599]
**mapbox-gl-js version**: v0.35.1

Codepen: https://codepen.io/Naimikan/pen/JNYyvd

Hi! I'm trying to add a WMS source:

```javascript
map.addLayer({
   'id': 'wms-test-layer',
   'type': 'raster',
   'source': {
      'type': 'raster',
      'tiles': [
         'https://nowcoast.noaa.gov/arcgis/services/nowcoast/radar_meteo_imagery_nexrad_time/MapServer/WmsServer?bbox={bbox-epsg-3857}&service=WMS&request=GetMap&version=1.3.0&layers=1&styles=&format=image/png&transparent=true&height=481&width=1024&crs=EPSG:3857'
      ],
      'tileSize': 256
   },
   'paint': {}
});
```

But I get a black layer. I'm sure that is not a problem with mapbox-gl, but I don't know what happen. If I open Chrome console, I get this error: `[.Offscreen-For-WebGL-0x692fcdc7a00]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering`

Thanks!

**Comment by mourner** [comment]
> height=481&width=1024

Is this intentional? You're requesting rectangular tiles. Mapbox GL only supports square tiles.

**Comment by andrewharvey** [comment]
> height=481&width=1024

@Naimikan not sure if you worked it out but you should set these both to 256.

You might also be able to set to 512 and change the tileSize to 512.

**Comment by Naimikan** [comment]
Hi @andrewharvey!

Thank you so much! It worked!
