### ISSUE TITLE
"charCodeAt is not a function" error with string-domain zoom-and-property function

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-js#4605]
This JS Bin illustrates a string-domain zoom-and-property function that is working as expected: https://jsbin.com/curewoqexi/edit?html,output

However, if I change the `zoom` property in the last stop to `7`, the style breaks and I see the following error in the devtools console (meaningless filenames omitted):

```
Uncaught TypeError: h.charCodeAt is not a function
    at SymbolBucket.populate
    at WorkerTile.parse
    at VectorTileWorkerSource.t
    at VectorTileWorkerSource.t
    at XMLHttpRequest.r.onload
```

Another angle on this problem: If I reduce the GL JS version to 34, I no longer see this `charCodeAt` error (or any relevant errors in the console); but the style does not work. It renders `NaN,NaN,NaN` where it should render one of my values. 

Please let me know if there's anything else I can try out to help debug this!

cc @aparlato, @dasulit, @samanpwbb

**Comment by mourner** [comment]
Here's a smaller test case:

```js
const spec = require('./src/style-spec/reference/latest');
const createFn = require('./src/style-spec/function/');

const fn = createFn({
    type: 'categorical',
    property: 'name_en',
    stops: [
        [{ value: 'Maroua', zoom: 0 }, 'xxx'],
        [{ value: 'Maroua', zoom: 2 }, 'XXX']
    ]
}, spec.layout_symbol['text-field']);

console.log(fn(1, {name_en: 'Maroua'}));
// [ 'xNaN', 'xNaN', 'xNaN' ]
```

So the root issue here is that the value is not defined for zooms between categorical stops in zoom-and-property functions. At least I'd expect it to be defined as "same as previous stop", since `fn(3, ...` works like this. cc @jfirebaugh
