### ISSUE TITLE
Problems with Dataset and Tileset

### ISSUE THREAD

**Issue by redka** [mapbox/mapbox-gl-js#4608]
# Problems with Dataset and Tileset

We have an issue with Mapbox datasets not exporting correctly to tilesets. This issue is happening with both Uploads API and exporting using Mapbox Studio.

It’s happening half of the time with our data , making it mismatched, misaligned and actually completely wrong. It reminds simplification, and here’s what it looks like on example:

Dataset representation:
 
[http://d.pr/i/LNsP](http://d.pr/i/FDIY)

Tileset/Style representation:

[http://d.pr/i/LNsP](http://d.pr/i/LNsP)

This is one example, but we've seen this happening all the time with all kinds of features in dataset. 

We tried uploading features one-by-one to dataset, tried exporting to tileset with delay, and tried combining all features we have into one single MultiLineString - nothing helps.

Attaching example's geojson. (970.geojson)
[970.geojson.zip](https://github.com/mapbox/mapbox-gl-js/files/932686/970.geojson.zip)

**Comment by mourner** [comment]
Thank you for the report! However, it seems unrelated to this repository, which specifically tracks issues with the Mapbox GL JS library and its style specification. Can you please submit the report to the [Mapbox support channel](https://www.mapbox.com/contact/support/) instead? We'll do our best to help you out!
