### ISSUE TITLE
Build route

### ISSUE THREAD

**Issue by redka** [mapbox/mapbox-gl-js#4609]
We are using MapboxDirections.swift and mapbox-gl-directions. All parts of the route are build on the route, but first and last segments slightly deviate from the road. This is critical to our use case, since we are trying to match road ratings from different users, and we need routes to completely match the road.

For MapboxDirections.swift we are using shapeFormat .geojson(it provides more accurate data than polyline), routeShapeResolution = .full, and cycling profile(our usecase is built with cycling in mind).

So what happens when we want to create two routes using Mapbox Directions API.
We are sending query for the first one:

curl "https://api.mapbox.com/directions/v5/mapbox/cycling/$from;$to?overview=$overview&geometries=$geometries&access_token=$token"

where:
from='-80.008886,40.427531'
to='-79.997513,40.42578'

overview='full'
geometries='geojson'

and for the second one:

curl "https://api.mapbox.com/directions/v5/mapbox/cycling/$from;$to?overview=$overview&geometries=$geometries&access_token=$token"

where:
from='-80.005137,40.427024'
to='-79.999234,40.426894'

overview='full'
geometries='geojson'

and as the result we're receiving two routes (see attachments)

After that we're creating features on the same dataset and see that the last point of second route is outside of the road (see attachment) 

What we have to do to prevent that, because we want the points of both routes to be same on the same road.

[mapbox-attach.zip](https://github.com/mapbox/mapbox-gl-js/files/932726/mapbox-attach.zip)

**Comment by mourner** [comment]
Thank you for the report! However, it seems unrelated to this repository, which specifically tracks issues with the Mapbox GL JS library and its style specification. Can you please submit the report to the [Mapbox support channel](https://www.mapbox.com/contact/support/) instead? We'll do our best to help you out!
