### ISSUE TITLE
setData or adding new layer causes increased memory usage and crashing

### ISSUE THREAD

**Issue by rvratner** [mapbox/mapbox-gl-js#4618]
I'm using mapbox to load 1-4000 items to a map using an ajax call to a geojson file.
When left open, it seems to be using up memory and eventually freezing the browser.

Any help would be much appreciated. Looks maybe similar to this?
https://github.com/mapbox/mapbox-gl-js/issues/2607

**mapbox-gl-js version**: v0.36.0

### Steps to Trigger Behavior

 1. Load page, keep open for ~10 min
 2. Map loads data via setData()
 3. Open Activity Monitor, Google Chrome helper will show usage of 2GB memory
 4. Page will freeze

### Expected Behavior
Memory use should remain constant

### Actual Behavior
Memory use is increasing

**Comment by mourner** [comment]
Can you please provide a JSFiddle test case (as minimal as possible) for reproducing the issue? There's a similar issue #4562 but it's Safaris-specific. Also linking previous discussion in #2607

**Comment by joshluongo** [comment]
+1 for this issue, I've got a large data set that updates frequently and somewhere in mapbox-gl appears to be retaining the old data.

**Comment by jfirebaugh** [comment]
#5455 fixed a leak that may have caused this. If this is still reproducible in v0.42 or later, please open a new issue and include a test case.

**Comment by aspskaxianet** [comment]
how do you fix this setData problem?
