### ISSUE TITLE
Marker Icon Location Wrong

### ISSUE THREAD

**Issue by buriwoy** [mapbox/mapbox-gl-js#4621]
Hi guys,

I'm trying to change marker icons and then revert back. But when I do that the marker icons are positioned wrong, a bit off. Here is jsfiddle: https://jsfiddle.net/3tfsu51d/3/

There I'm just applying a new class for 5 secs and then removing it in 5 secs.

I'm using undocumented `_update` method. What is the recommended  way of updating marker's icon, anchor, etc.?

thanks,
-- buriwoy

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by buriwoy** [comment]
thanks @jfirebaugh.

Actually, "how do I" was the second part. The first part is in the jsfiddle. Do you have any comments on that behavior?

thanks!

**Comment by jfirebaugh** [comment]
`el.className = 'marker ' + 'grown'` removes the `.mapboxgl-marker` class from the element, which is interfering with the positioning that Mapbox GL does.

**Comment by buriwoy** [comment]
thanks @jfirebaugh! That worked!
