### ISSUE TITLE
MapBox 0.36.0 - undefined is not an object (evaluating 'e._layers[t].serialize')

### ISSUE THREAD

**Issue by YannKauderer** [mapbox/mapbox-gl-js#4633]
**mapbox-gl-js version**: 0.36.0

Hi everyone,

I'm developping an app with Ionic 2 and Mapbox GL JS. On one of my screen I have 3 tabs which filters POIs in a single map. When I go from one tab to another (first time) it works just perfectly, but when I try to go to another, or go back to the first one, i got an error : **undefined is not an object (evaluating 'e._layers[t].serialize')** 

Here is my code for removing markers (generated by geojson) : 

```javascript
function removeGarages() {
    this.map.removeSource('markers');
    this.garages.forEach(garage => {
        this.map.removeLayer(garage.id);
    });
}
```

My code for adding the markers : 

```javascript
function addMarkers() {
    this.markers = [];
    let geojson = {
      "type": "geojson",
      "data": {
        "type": "FeatureCollection",
        "features": []
      }
    };

    markers.forEach(marker => {
      let coordinates = [marker.location.lng, marker.location.lat];
      let m = {
          "type": "Feature",
          "properties": {
            "id": marker.id.toString()
          },
          "geometry": {
            "type": "Point",
            "coordinates": coordinates
          }
      };
      this.markers.push(coordinates);

      geojson.data.features.push(m);
    });

    this.map.addSource('markers', geojson);
    // then parse the geojson and call this.map.addLayer({/*marker's properties*/})
}
```

Thanks for your help guys !

**Comment by mourner** [comment]
Can you please set up a minimal JSFiddle test case that reproduces the issue (without any frameworks like Ionic)?

**Comment by YannKauderer** [comment]
Hi @mourner ! 

Thanks for the reply and here is the JSFiddle : [https://jsfiddle.net/jr6yojmv/](url). Same bug without any libraries (try to change the filters 2-3 times).

**Comment by jfirebaugh** [comment]
The issue stems from passing a numeric layer ID to `removeLayer` when a string is expected. Reduced test case:

```js
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/light-v9'
    });

    map.on('load', function() {
        map.addSource('markers', {
            "type": "geojson",
            "data": {
                "type": "Point",
                "coordinates": [0, 0]
            }
        });

        map.addLayer({
            "id": "1234",
            "type": "circle",
            "source": "markers"
        });

        map.addLayer({
            "id": "asdf",
            "type": "circle",
            "source": "markers"
        });

        map.removeLayer(1234);

        map.addLayer({
            "id": "1234",
            "type": "circle",
            "source": "markers"
        });
    });
```

The numeric value results in [`this._order.indexOf(id)`](https://github.com/mapbox/mapbox-gl-js/blob/1355c306b0584afaa389f95d80bc743d34d37056/src/style/style.js#L538-L538) returning `-1`, and subsequently the last entry is spliced out of `this._order` rather than the desired entry.
