### ISSUE TITLE
unable to set 'text-anchor'

### ISSUE THREAD

**Issue by liwanchong04719** [mapbox/mapbox-gl-js#4639]
i want to set label in the polygon top-left ,but it could't use . how do i  have to set

**Comment by mourner** [comment]
When `symbol-placement` is set to `point`, Mapbox GL JS calculates an anchor point for each polygon that's the farthest from its edges. You can read about how it works [here](https://www.mapbox.com/blog/polygon-center/). Setting `text-anchor` to `top-left` then makes the text label top left corner be placed in that point. If you want the label to the left and up from the anchor point, you would use `bottom-right`. See the [documentation for text-anchor](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-anchor).
