### ISSUE TITLE
Allow interval zoom and property functions for categorical properties

### ISSUE THREAD

**Issue by gmaclennan** [mapbox/mapbox-gl-js#4640]
**mapbox-gl-js version**: v0.36.0

### Steps to Trigger Behavior

 1. Define a layer zoom-and-property function based on a string property

### Expected Behavior

Paint value interpolates between zooms

### Actual Behavior

Paint value jumps at each zoom

--

If I define a style like:

```json
"paint": {
    "circle-radius": {
        "property": "population",
        "type": "interval",
        "stops": [
            [{ "zoom": 15, "value": "children" }, 10],
            [{ "zoom": 15, "value": "adults" }, 50],
            [{ "zoom": 17, "value": "children" }, 20],
            [{ "zoom": 17, "value": "adults" }, 60],
            [{ "zoom": 20, "value": "children" }, 30],
            [{ "zoom": 20, "value": "adults }, 70]
        ]
    },
}
```

I would hope that it would work like a zoom function, but with different values for each property. But this gets an error that the value must be a number for an interval type property function. Perhaps related to https://github.com/mapbox/mapbox-gl-js/issues/4154 ?

**Comment by jfirebaugh** [comment]
It sounds like you want `"type": "categorical"`, not `"type": "interval"`.

**Comment by gmaclennan** [comment]
With categorical the values (circle-radius in this case) jump at each stop. I was looking for functionality where using this zoom-property function would be the same as creating a layer filtered by each property and then having a standard zoom function circle-radius.

e.g. for the above example, by hope was that it would be functionally equivalent to creating two layers with `filter: ['==', 'population', 'adults']` and `filter: ['==', 'population', 'children']` and then for each of then:

```json
// adults
"paint": {
    "circle-radius": {
        "property": "population",
        "type": "interval",
        "stops": [
            [15, 50],
            [17, 60],
            [20, 70]
        ]
    }
}

// children
"paint": {
    "circle-radius": {
        "stops": [
            [15, 10],
            [17, 20],
            [20, 30]
        ]
    }
}
```

(This is a contrived example, but wanted something simple to illustrate the issue)

**Comment by jfirebaugh** [comment]
Can you put together a JSFiddle that demonstrates the jumping behavior for categorical? That sounds like a bug.

**Comment by nextstopsun** [comment]
+1 here. AFAIK there is no way to use zoom-and-property functions for `categorical` function type yet. What would be great to have is this:

```
stops: [
  [{zoom: 16, value:"tree"}, #00FF00],
  [{zoom: 17, value:"tree"}, #00BB00],
  [{zoom: 16, value:"bush"}, #00FFEE],
  [{zoom: 17, value:"bush"}, #00BBEE]
]
```
So colour can be switched (or interpolated) when zoom level changes.

Filtering out by single value and then using just a zoom function is a bad option, because then I end up with hundreds of layers.

**Comment by felixLam** [comment]
This would indeed be quite useful as it would allows us to reduce the number of layers for related entities from the same source-layer.

**Comment by jfirebaugh** [comment]
Zoom-and-property functions with `"type": "categorical"` appear to work as expected to me.

https://jsfiddle.net/tc08sprm/

Here we see the radius of features with one property value smoothly interpolating from 0 to 20, and features with a different property value going the opposite direction.

So as far as I understand the request, this is possible and working. If I'm misunderstanding the request, please provide a complete working example like above.

**Comment by felixLam** [comment]
@jfirebaugh Thanks for the quick reply and the JSFiddle.
