### ISSUE TITLE
MapBox stopped working on SqaureSpace

### ISSUE THREAD

**Issue by pelicanpaul** [mapbox/mapbox-gl-js#4643]
Hi,

Let me say that the map displays fine by itself when I run locally.

I just starting getting an error when using Mapbox with SquareSpace. This use to work and I cannot figure what is up with this error. 

**test-share:198 Uncaught ReferenceError: mapboxgl is not defined**

You can see
https://www.5gyres.org/test-share

There once was a map there.... How can mapboxgl not be defined?

I am calling

<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.css' rel='stylesheet' />

Anyone run into this on SquareSpace.?

thanks!

**Comment by jfirebaugh** [comment]
mapbox-gl.js includes a [UMD](https://github.com/umdjs/umd), and `define` and `define.amd` are present in the global environment, so mapbox-gl.js is assuming it should initialize itself via AMD, in which case `window.mapboxgl` is not set.

**Comment by pelicanpaul** [comment]
I see that in that SquareSpace environment window.mapboxgl is not an object and undefined.  How do I work around this? thanks,

**Comment by pelicanpaul** [comment]
Just for the next bloke that has this problem. I moved the      
```
<!--mapbox-->
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.32.1/mapbox-gl.css' rel='stylesheet' />
``` 
scripts to the Site's Code  Injection field - it was at the Page Level Code Injection. I think SquareSpace changed the order of the scripts loading. Voila! It works now,
