### ISSUE TITLE
Allow event listeners triggers to be configurable

### ISSUE THREAD

**Issue by Jhovanni** [mapbox/mapbox-gl-js#4646]
## Motivation
Recently I've been working in a real time location video game. I want user interaction to be simple: instead of needing to use Ctrl+Left click, or Right click to rotate map, I would love to be able to configure it to rotate map use simple left click.
Similar for rotation with touch listeners: rotate map when single dragging, instead of needeing to pinch with two fingers. For this case I am planing to rotate always using the center of the map, no matter where dragging starts.

## Design Alternatives
Provide functionality to configure event listeners triggers. I've been looking around the documentation, stackoverflow and several places: seems like this is not supported.

## Design
Being able to configure triggers, will allow developers to implement moouse or touch events in ways that fit theirs expected behaviour

### Implementation
Probably, map listeners can accept parameters to specify which event should trigger the event. Like dratgRotateListener accepting as option { trigger: 'left'}, { trigger: 'right'}

**Comment by mollymerp** [comment]
@Jhovanni thanks for the feature request! I think this wouldn't be too hard to implement if you want to take a stab at a PR. 

> I've been working in a real time location video game
are you aware of our Unity SDK? https://www.mapbox.com/unity/

**Comment by Jhovanni** [comment]
Thanks
Yes, I am aware of Unity SDK, and I plan to use it, but I want different versions of the game. For web version I am using mapbox gl js

**Comment by mourner** [comment]
Looks like there's not enough interest in implementing this at the moment, and there were no updates in more than a year, so I'm closing this for now.
