### ISSUE TITLE
Collision boxes don't appear until you move map

### ISSUE THREAD

**Issue by aparlato** [mapbox/mapbox-gl-js#4647]
**mapbox-gl-js version**: All versions above 0.33.0

[Minimal demo of bug](https://jsbin.com/quqofec/edit?html,js,console,output)

No errors or warnings.

### Steps to Trigger Behavior

 1. Apply `map.showCollisionBoxes = true` (happens on load in demo)
 2. No collision boxes appear
 3. Move map
 4. Collision boxes appear

### Expected Behavior

Collision boxes show up on `map.showCollisionBoxes = true`

### Actual Behavior

Collision boxes show up only after moving map when `map.showCollisionBoxes = true`

**Comment by mollymerp** [comment]
Bisected and #4347 seems to be the culprit ☹️
