### ISSUE TITLE
`default` value in zoom-and-property function ignored

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#4651]
**mapbox-gl-js version**: commit `82eec5d35e4afc5290da2c1f2250b71b0cc8bd8f`

### Steps to Trigger Behavior

 1. Create a zoom-and-property function with a `default` value

### Expected Behavior

Default value is assigned for data property values that are not assigned in the stops of the function.

### Actual Behavior

Style spec default value is assigned.

**Comment by jfirebaugh** [comment]
@nickidlugash What's the function definition you're using?

**Comment by nickidlugash** [comment]
@jfirebaugh sorry, I forgot to include [a minimal stylesheet](https://gist.github.com/nickidlugash/d847c242c2c76098c88618a2add199fe).
