### ISSUE TITLE
Tiles don't seem to cache correctly

### ISSUE THREAD

**Issue by jliebrand** [mapbox/mapbox-gl-js#4659]
Please see this demo video:
https://drive.google.com/file/d/0BzCBmj4tsO_ndWtySkNLczI4QTQ/view

As I zoom out, the tiles at the top of the map need to get loaded in (you'll see the background pattern first, then the tiles load). I then zoom back in again, and then out again... The same tiles appear to be loaded again... each time I do this (shown a couple of times in the video).

I can't quite work out when this happens, vs when the cache appears to be correct, but my suspicion is for tiles that are on the edge of the viewport.  

I'm using Mapbox GL JS 0.32.1.

**Comment by DannyDelott** [comment]
This may not be a caching issue, but rather a re-parsing of the tiles. Can you confirm that the tiles are being re-requested from the network?

**Comment by jliebrand** [comment]
I think you might be right; still trying to find out definitely either way, but looks like it's a re-parsing. Which also shouldn't happen, right?

**Comment by anandthakker** [comment]
> Which also shouldn't happen, right?

This depends on the size of the tile cache, which is determined based on the size of the viewport.  If you could provide a live, minimal example reproducing this behavior, that will help determine whether it's expected or erroneous.

**Comment by jliebrand** [comment]
Actually, this has been a while now, and I dont think I've seen this happening recently. I'll close this bug now, and re-open one if/when I see it happening again (that time with some more repo steps)
