### ISSUE TITLE
Provide ES6 modules with striped flow types, to be able to use it in create-react-app

### ISSUE THREAD

**Issue by stereobooster** [mapbox/mapbox-gl-js#4664]
Example of code https://github.com/stereobooster/create-react-app-map-gl/tree/react-map-gl-2

Error:
```
Uncaught Error: Module parse failed: node_modules/react-map-gl/node_modules/mapbox-gl/js/util/util.js Unexpected token (15:35)
You may need an appropriate loader to handle this file type.
|  * @private
|  */
| exports.easeCubicInOut = function(t: number): number {
|     if (t <= 0) return 0;
|     if (t >= 1) return 1;
```

Suggesting to add something like this into `package.json`

```
 "module": "dist-es6/index.js",
```

`dist-es6` will contain ES6 modules (same as src) with flow-types striped.

Thanks.

**Comment by stereobooster** [comment]
Tried primitive

```
"module": "dist-es6/index.js",
"scripts": {
"build-es6": "mkdir -p dist-es6 && flow-remove-types src/ --out-dir dist-es6 && cd src && find . -name '*.json' | cpio -pdm ../dist-es6 && cd ../",
```

but doesn't seem to work. Probably need to look into browserify or I missed something.

**Comment by jfirebaugh** [comment]
We've considered switching to ES6 modules, but we need something like https://github.com/rollup/rollup/issues/1029 to be solved first. Closing here; we'll reconsider when there's a solution for web workers.

**Comment by stereobooster** [comment]
Small note: "rollup webworkify" required because there is no good way to overcome "single file limitation".

> we use the blob: construct to create our web workers. We could potentially dodge this - use file-based web workers, but we don't have a clear way to do this while also keeping mapbox-gl-js compatible with bundlers like browserify & webpack which generate single-file bundles including this software. If there's a way around that limitation or even with an extra step but preserving the default behavior for everyone else, we'd be game for including it.
