### ISSUE TITLE
Restore CSP documentation

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#4665]
The README used to contain documentation for the CSP directives required by Mapbox GL JS (#2980), but it got lost in a merge (779931e5b604bb868e1cf0d361a8e6147eed141d). Let's restore it.

**Comment by jfirebaugh** [comment]
<pre>
## Using Mapbox with [CSP](https://developer.mozilla.org/en-US/docs/Web/Security/CSP)

You may use a Content Security Policy to restrict the resources your page has
 access to, as a way of guarding against Cross-Site Scripting and other types of
 attacks. If you do, Mapbox GL JS requires the following directives:

```
child-src blob: ;
img-src data: blob: ;
script-src 'unsafe-eval' ;
```

Requesting styles from Mapbox or other services will require additional
 directives. For Mapbox, you can use this `connect-src` setting:

```
connect-src https://*.tiles.mapbox.com https://api.mapbox.com
```
</pre>

**Comment by jfirebaugh** [comment]
0a6e4dc8ded6ee3e96ef2de360b17814314d125b

**Comment by mollymerp** [comment]
😞  whoops! thanks for the fix @jfirebaugh
