### ISSUE TITLE
QueryRenderedFeatures to Measure Distance between layers

### ISSUE THREAD

**Issue by dja** [mapbox/mapbox-gl-js#4667]
Mapbox-GL v0.36.0

I'd like to be able to do something like this: [Leaflet Geometry Util - Distance](http://makinacorpus.github.io/Leaflet.GeometryUtil/leaflet.geometryutil.js.html#line42), and measure distance between two rendered layers. Ultimately, what I'd like to do is revise a layer's `circle-radius` based on the zoom, to where it accurately represents a set distance. I've found that it's more documented to do this via Leaflet/Mapbox.js, but there must be a way to work with layers more dynamically in Mapbox-GL too.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
