### ISSUE TITLE
Overlapping popups

### ISSUE THREAD

**Issue by knutole** [mapbox/mapbox-gl-js#4676]
**mapbox-gl-js version**: 0.36.0

### Steps to Trigger Behavior

 1. Add popups to GeoJSON points that are quite close to each other
 2. Open all popups
 3. Behold overlapping popups.

### Expected Behavior
Would be nice if popups would be aware of each other, and adjust `offset` accordingly. Is this something that exists now? (Can't find it.)

### Actual Behavior
<img width="654" alt="screen shot 2017-05-03 at 22 13 54" src="https://cloud.githubusercontent.com/assets/2197944/25679543/007a2b34-304e-11e7-8700-25768b485103.png">

**Comment by jfirebaugh** [comment]
Hi @knutole, thanks for using Mapbox GL. This is something that you'll need to solve yourself. In general, collision avoidance is a hard problem, and one we don't plan to implement for popups.
