### ISSUE TITLE
Style a Bivariate Map

### ISSUE THREAD

**Issue by jdeboer-geoplan** [mapbox/mapbox-gl-js#4684]
Bivariate maps are occasionally useful see https://en.wikipedia.org/wiki/Bivariate_map

Is there a way to style them with mapbox gl?  At the moment my plan is to include an additional attribute in my geoJSON that combines my two data points and I can use that in a property function.  This is inelegant as I'd need to edit and reload my geoJSON when the user changes classifications.

Possibly this could be done with a change to property functions to take two properties

something like 
{
  "fill-color": {
    "property": "temperature",
    "bivariate-property": "population",
    "stops": [
      // temperature is low, population is low - blue
      [{ value: 0, value2: 100}, 'blue'],
      // temperature is low, population is high - cyan
      [{ value: 0, value2: 10000}, 'cyan'],
      //temperature is high, population is low - red
     [{ value: 20, value2: 100},'red'],
     //temperature is high, population is high - yellow
     [{ value: 20, value2: 10000},'yellow'],
    ]
  }
}

**Comment by jfirebaugh** [comment]
> include an additional attribute in my geoJSON that combines my two data points

This is the best current solution. #4077 tracks the request for property functions that can combine multiple data properties using arbitrary arithmetic expressions.

**Comment by jdeboer-geoplan** [comment]
Ah smashing, thanks for that, I hadn't found that issue, I'll comment on that one with the bivariate map use case. thanks again great work.
