### ISSUE TITLE
Minification with uglify does not work for distributed ES6 code

### ISSUE THREAD

**Issue by NameFILIP** [mapbox/mapbox-gl-js#4692]
In our workflow, we concatenate all dependencies with Browserify and then running UglifyJS on it. It works well for `mapbox-gl-style-spec@8.10.0`, but fails for `@mapbox/mapbox-gl-style-spec@8.11.0` with the message:
```
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: keyword (const)
```
On the UglifyJS readme page there is a statement: "Release versions of `uglify-js` only support ECMAScript 5 (ES5)". I've also found this issue: https://github.com/mishoo/UglifyJS2/issues/448 (open since 2014).

Was this a conscious decision to start publishing `@mapbox/mapbox-gl-style-spec` with ES6 syntax (`const`, etc)?

**Comment by mollymerp** [comment]
@NameFILIP thanks for using Mapbox! yes, we made a conscious decision to switch to ES6 syntax across our mapbox-gl javascript ecosystem https://github.com/mapbox/mapbox-gl-js/issues/3368

**Comment by mourner** [comment]
Also note that UglifyJS v3 just released, with full ES6 support: https://github.com/mishoo/UglifyJS2
If you find yourself needing to turn a mapbox-gl-style-spec-dependent project compatible with ES5, we suggest using https://buble.surge.sh/ (which we use for the GL JS codebase) or Babel.
