### ISSUE TITLE
Setting cookie for image source

### ISSUE THREAD

**Issue by huaruiwu** [mapbox/mapbox-gl-js#4694]
**mapbox-gl-js version**: current

`ImageLayer` uses `utils/ajax` to make the request but it does not include cookies in the header. This is a problem because I need to retrieve images off of CloudFront and require a signed cookie. Setting `xhr.withCredentials = true` fixes the problem https://github.com/huaruiwu/mapbox-gl-js/commit/beb2b61ac2c538fad91f36769b5498271c728553.

**Comment by jfirebaugh** [comment]
Thanks for the request. Folding this in with the same request in #3874.
