### ISSUE TITLE
Regenerating Map from Map Instance

### ISSUE THREAD

**Issue by YannKauderer** [mapbox/mapbox-gl-js#4696]
Hey guys !

I was wondering if it's possible to regenerate a map from a Map Instance, I'm facing an issue and if it's possible it will solve everything.
By the way, I'm using Mapbox GL JS v0.37.0.

Thanks guys ! (and girls :P)

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
