### ISSUE TITLE
map.queryRenderedFeatures() returns incorrect empty list 

### ISSUE THREAD

**Issue by migurski** [mapbox/mapbox-gl-js#4699]
In this preview, you can roll over dots and see a “zoom in for more” popup: http://bl.ocks.org/migurski/raw/e16054023c550cfdaa87e67650de932f/#12.09/37.8029/237.7334

When you get down to z15+, you can roll over dots and see the street address in a popup: http://bl.ocks.org/migurski/raw/e16054023c550cfdaa87e67650de932f/#15.27/37.8044/237.7294

When you roll _past_ z16, you no longer see the popup, and that’s bad: http://bl.ocks.org/migurski/raw/e16054023c550cfdaa87e67650de932f/#17.03/37.80491/237.72903

Been talking this over with @peterqliu in Slack. He reports that [`map.queryRenderedFeatures()` is returning an empty list at line 71](https://gist.github.com/migurski/e16054023c550cfdaa87e67650de932f#file-index-html-L71), and suggests this may be related to https://github.com/mapbox/mapbox-gl-js/issues/2279. At least [one dot at high zoom works](https://bl.ocks.org/migurski/raw/e16054023c550cfdaa87e67650de932f/#21.54/40.78640/-73.97840), so the pattern’s not immediately obvious.

**Comment by migurski** [comment]
Chatting with @ericfischer, who recommends passing a smallish bbox to `map.queryRenderedFeatures()` instead of a single point. I may try this.

**Comment by ericfischer** [comment]
In particular like [mbview does here](https://github.com/mapbox/mbview/blob/d06a31aa8a59388388d24fa37f642e5faa7c6df9/views/vector.ejs#L157), with a 3-pixel buffer around the pointer.

**Comment by mollymerp** [comment]
hi @migurski – you were on an old version of gl-js, and when I upgraded to the most recent release and added a 3px by 3px bbox like in this example (https://www.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures-around-point/) I no longer experienced the issue where `qRF` didn't return any features. Please reopen if you continue to have issues.

![image](https://cloud.githubusercontent.com/assets/2425307/25926036/6197a84e-35a1-11e7-8303-c1d53043c63b.png)

https://jsbin.com/hequmupofu/edit?html,js,output

**Comment by migurski** [comment]
Thank you @mollymerp!

**Comment by peterqliu** [comment]
@mollymerp the bbox solution works great for this scenario, but on a technical level, should we still *expect* `qRF` to work with just a single point query? Is there a deeper bug here that we should root out?

**Comment by mollymerp** [comment]
@peterqliu it does work for me with a single point, you just have to be more exacting with your cursor.

**Comment by migurski** [comment]
Does that mean the big rendered points are not the same as hit areas?

**Comment by mollymerp** [comment]
mmm I'm not sure what you mean – you should be able to mouse over the whole rendered feature and get a result even if you don't use a bounding box
![qrf](https://cloud.githubusercontent.com/assets/2425307/25976865/76d2017a-366c-11e7-895e-de91b7d9b917.gif)

**Comment by migurski** [comment]
In the previous version I was getting a very small hit area right in the middle of each dot. I guess this is fixed in the newer version of GL?

**Comment by mollymerp** [comment]
yes it may have been fixed in https://github.com/mapbox/mapbox-gl-js/pull/4243 – is the `circle-radius` there using a property functiomn?

**Comment by migurski** [comment]
I’m not sure what that means — in case it’s interesting, here’s what it looks like in Studio:

<img width="329" alt="screen shot 2017-05-11 at 5 18 50 pm" src="https://cloud.githubusercontent.com/assets/58730/25977106/f4654a88-366d-11e7-82b2-8d7c7f3bc8b7.png">
