### ISSUE TITLE
Sort point features by y-axis

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#470]
![img_0624](https://cloud.githubusercontent.com/assets/32314/3320227/535003f4-f728-11e3-98c3-11b70bedfd4b.PNG)

For overlays and possibly for built-in layer data, we need to sort by y-axis before displaying overlapping features that look like 'markers' - otherwise things look weird. This will need to be recalculated based on rotation if we want to really nail it.

**Comment by ansis** [comment]
This is easy to implement with the new labeling: https://github.com/mapbox/mapbox-gl-js/commit/5bf094f7c26ebe2730f258b2ac5cef1ca804767d

How should this be specified in the style? spec issue here: https://github.com/mapbox/mapbox-gl-style-spec/issues/274

**Comment by incanus** [comment]
This is mostly designed for annotations, so the style is hardcoded such as in https://github.com/mapbox/mapbox-gl-native/blob/0a2ee766dbe65e3d23d0e5cba79776560ff29275/src/mbgl/style/style_parser.cpp#L40-L69, then would have the ability to turn a feature like this on or off via API.

**Comment by ChrisLoer** [comment]
#5150 partially reverts this behavior (by allowing sort order inconsistencies at tile boundaries) in order to fix #2706 along with other issues. See discussion at https://github.com/mapbox/mapbox-gl-js/pull/5150#issuecomment-326438377.
