### ISSUE TITLE
Small Multiple Support

### ISSUE THREAD

**Issue by skokenes** [mapbox/mapbox-gl-js#4703]
## Motivation
Thanks to data-driven styles, we can now create data visualizations like choropleths. One useful visualization technique is small multiples, where you repeat the same chart form multiple times with the different data. You can see this idea illustrated with maps [here](https://i1.wp.com/flowingdata.com/wp-content/uploads/2013/07/00-featured-edit.png?w=625).

It would be great to be able to do the same with mapbox. Currently the only way that I am aware of to do this is by setting up multiple maps on a page. This does not scale well as it requires a new gl context per map. There are browser limits on the number of gl contexts on a page at any given time.

## Design Alternatives
Use a different map per small multiple, but as mentioned this leads to performance issues.

## Design
Some sort of method for creating multiple maps that share a gl context? Could be accomplished using [gl.scissor](https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/scissor)

If a user could specify a gl context they created from gl.scissor instead of just a div element to place the canvas, that may solve the problem.

### Mock-Up
```
var myContext = canvas.getContext('webgl').scissor(0,0,100,100);
var map = new mapboxgl.Map({
      context: myContext
      style: 'style'
      center: [0,0],
      zoom: 1
    });
```

**Comment by jfirebaugh** [comment]
Thanks for the suggestion @skokenes, but I don't think we're likely to implement this. It would add a lot of complexity for a relatively uncommon case. As a workaround, you might consider using static images instead, e.g. with the [Mapbox Static API](https://www.mapbox.com/api-documentation/#static).
