### ISSUE TITLE
Minzoom option does not work for symbols using polygon as its source

### ISSUE THREAD

**Issue by bwyss** [mapbox/mapbox-gl-js#4705]
mapbox-gl-js version: 0.37.0

I am rendering a symbol using a polygon as its source. I have set the minzoom option to 1, however at zoom levels below 6 the symbol is not rendering on the map. Here is an example of this behavior: http://jsfiddle.net/LLhdfsdv/ To reproduce the issue zoom out till you see the north american continent.

**Comment by andrewharvey** [comment]
Just guessing here, perhaps at such a low zoom https://github.com/mapbox/geojson-vt is dropping the polygon because it has become so tiny.

You could try using https://github.com/mapbox/polylabel to convert your polygon source into a point based source and use that for the symbol.

**Comment by bwyss** [comment]
I think you are right, thanks for the link
