### ISSUE TITLE
Complex text shaping

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-js#471]
Breaking this out from https://github.com/mapbox/gl-ported-maps/issues/20#issuecomment-43928958

Text shaping has moved client-side with switch to glyph ranges instead of augmented vector tiles, so complex text is no longer being shaped properly.

Proper text shaping:
![casa](https://cloud.githubusercontent.com/assets/1421652/3058542/79edc872-e1e1-11e3-84fd-625b5cef0051.jpg)

Currently backwards, and without complex text shaping:
![screen shot 2014-05-29 at 1 12 33 pm](https://cloud.githubusercontent.com/assets/1149913/3120706/851ac39e-e754-11e3-94e3-a262140456dc.png)

**Comment by fnicollet** [comment]
I am also interested in this fix. I produce vector tiles with hebrew text only in Israel and users have been complaining that the text is reverted

**Comment by mikemorris** [comment]
-> https://github.com/mapbox/mapbox-gl/issues/4

**Comment by jimmont** [comment]
[Hebrew labels look like nonsense until you realize they're flipped](https://github.com/mapbox/mapbox-gl/issues/4#issuecomment-211750696) is there a solution I can implement now to resolve this for my gl-js map?
