### ISSUE TITLE
[style-spec] client-side hill-shading source/layer/properties

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#4711]
As we prepare to add a new layer type for rendering hill-shading on the client using a tiled DEM, we need to discuss the associated style-spec properties that will need to be added.

The plan right now is to initially release the hill-shading functionality using the terrain-rgb raster tiles as the source.

The properties in @kkaefer's [original implementation](https://github.com/mapbox/mapbox-gl-style-spec/compare/terrain-rendering) using encoded DEM in a vector tile feature he added the following properties:

`terrain-shadow-color`: The color of the terrain that faces away from the light source.
`terrain-highlight-color`: The color of the terrain that faces towards the light source.
`terrain-accent-color`: The color used to accentuate rugged terrain with sharp cliffs and gorges.
`terrain-illumination-direction`: Direction of the light source. Defaults to top left.
`terrain-illumination-alignment`: Direction of the light source when the map is rotated. `viewport` or `map`
`terrain-exaggeration`:  Intensity of the terrain

Now that we have a global [`light`](https://www.mapbox.com/mapbox-gl-js/style-spec/#root-light) I imagine the last three can be replaced with the global light properties. 

Opening this ticket to start discussing naming and additional properties we may need. @andrewharvey has [suggested](https://github.com/mapbox/mapbox-gl-js/pull/4701#issuecomment-300964890) we call this layer type `hillshade` and save the `terrain` layer type for use with 3d mesh terrain (feature request #1489 )

cc @mapbox/gl @mapbox/cartography-cats

**Comment by ajashton** [comment]
> call this layer type hillshade and save the terrain layer type for use with 3d mesh terrain 

+1 to "hillshade". FWIW our current use of "terrain" (as in "[Mapbox Terrain](https://www.mapbox.com/vector-tiles/mapbox-terrain/)") refers to the combination of elevation (incl. hillshade) and landcover information.

**Comment by 1ec5** [comment]
> Now that we have a global light I imagine the last three can be replaced with the global light properties.

That would be ideal. It’s difficult enough for a developer using the runtime styling API to visualize the light object’s `position` value; finding an appropriate corresponding value for `terrain-illumination-*` would be even more frustrating.

Should light object’s `color` value also influence the hillshading colors too?

> terrain-exaggeration: Intensity of the terrain

Could this exaggeration be expressed in relation to some real-world unit? What is the default value, and how would we describe its effect on the hillshading?

**Comment by kkaefer** [comment]
> +1 to "hillshade"

I used "terrain" intentionally because it's more than "just" hillshading in that it includes openness. However, I can see that "terrain" is too broad and overloaded, so I'd be okay with "hillshade" even if it doesn't tell the whole story.

**Comment by andrewharvey** [comment]
This has been done in #5286
