### ISSUE TITLE
transform symbol vertices outside of shaders

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#4718]
Broader context: https://github.com/mapbox/mapbox-gl-js/issues/4704

I'm working on transforming symbol vertices in javascript. Each frame the vertices are shifted, offset, projected and added to buffers as gl coordinates. Doing the transform outside of shaders let's us have full access to the line geometry which let's us render better in pitched views.

---

I'm working on this in the [cpu-label-transform](https://github.com/mapbox/mapbox-gl-js/tree/cpu-label-transform) branch.

I've hacked in a rough implementation that is mostly working, but it's currently taking ~20ms to run. I'm working on a bunch of relatively low-hanging optimizations that will hopefully cut that down significantly.

@ChrisLoer @kkaefer

**Comment by ansis** [comment]
Update: it's getting faster ~10ms but not quite there yet. Still some clear optimization opportunities.

**Comment by ansis** [comment]
Update:

This is getting closer. The cpu vertex transformation is now taking roughly 1-2ms on a large map on my computer.

I ended up moving as much work as possible back to the shader:
- the final matrix multiply to move from label plane coords to gl coords
- corner extrusion and rotation
- all point label rendering (in progress)

I still need to:
- remove old, dead code
- clean up new code
- finish up point label optimization

And then:
- rebase on master with pitch-scaling work

**Comment by mourner** [comment]
@ansis 1-2ms sounds fantastic!

**Comment by ChrisLoer** [comment]
@ansis That's awesome! I just checked out the branch and it's running nice and smooth in my browser.
