### ISSUE TITLE
Line extrusion possible?

### ISSUE THREAD

**Issue by quillcraft** [mapbox/mapbox-gl-js#4719]
How to create line extrusion (not polygon extrusion) in mapbox?
I need to create line diagram through the path on the map.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
