### ISSUE TITLE
RTL and bidirectional text

### ISSUE THREAD

**Issue by mikemorris** [mapbox/mapbox-gl-js#472]
Need to implement Unicode bidi algorithm for RTL and bidirectional text to reverse the display order of glyphs.

Should look like this:
![casa](https://cloud.githubusercontent.com/assets/1421652/3058542/79edc872-e1e1-11e3-84fd-625b5cef0051.jpg)

Currently looks like:
![screen shot 2014-05-29 at 1 12 33 pm](https://cloud.githubusercontent.com/assets/1149913/3120706/851ac39e-e754-11e3-94e3-a262140456dc.png)

**Comment by mourner** [comment]
Is this duplicate of #471?

**Comment by mikemorris** [comment]
@mourner Nope, RTL is pretty straightforward for non-complex scripts like Hebrew.

**Comment by fnicollet** [comment]
Also interested in this issue but I have no idea how to patch it

**Comment by mushon** [comment]
Just mentioning I ran into this problem as well in the Mapbox Studio beta and was forwarded here after reporting it. I can't help fix it but I will be happy to test a fix once one comes up. I also want to stress the importance of this issue as without this fix Mapbox-GL cannot be used by approximately half a billion people. Hope you make sure to prioritize this fix and definitely not launch without it. 
Keep up the good work and let me know if and how I can help.

**Comment by mushon** [comment]
Here's the bug documentation I sent for your reference:
![image](https://cloud.githubusercontent.com/assets/27123/10619985/62f0d308-7781-11e5-8f19-c42b87669918.jpg)

**Comment by mikemorris** [comment]
-> https://github.com/mapbox/mapbox-gl/issues/4
