### ISSUE TITLE
Allow configuring zoom speed/step

### ISSUE THREAD

**Issue by juho-hanhimaki** [mapbox/mapbox-gl-js#4723]
## Motivation
Zooming the map via scroll or double tap feels too slow most of the time. There is too much scrolling or double tapping to do. This is especially painful on devices with only touchpad.

Our use scenario has large fleet of assets that are situated around the globe. Users will often start with wide view of globe and then go into deep zoom levels to see more of the local context around specific asset. This process involves a lot of zooming in (and sometimes out too). It is common complaint for us that there is too much zooming to be done to get to desired level of zoom.

## Design
Make zoom step/speed was configurable via map options or in the zoom handlers. At the moment it seems the scroll_zoom.js and dblclick_zoom.js use hard coded values instead of configurable values.

**Comment by andrewharvey** [comment]
I've found this varies by the pointer device/os a fair bit. For me it's the opposite the scroll wheel on the mouse is slow but the touchpad scroll is nice and fast.

Perhaps in your UI you could hint your users to use Shift+drag a box to speed up zooming in? as a workaround for it being configurable.

**Comment by stevage** [comment]
Also running into this. My experience is like Andrew's - with the touchpad it's easy to do a big swipe that zooms forever, whereas the wheel is much more work.

It seems to be related to how much data is being displayed. An empty map scrolls in and out quickly, while a very heavy one feels like it's skipping scroll events.

**Comment by Caerbannog** [comment]
The title of this issue is about adding a configuration option.
I suspect that fixing the related issue #7572 (inconsistent scroll speed across browsers) might be a better solution for some of the people affected here.

**Comment by wisyr** [comment]
Current scrolling speed is way too low. Looking forward for this feature.

**Comment by mourner** [comment]
Here are the constants that have to be made configurable: 

https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/handler/scroll_zoom.js#L19-L22

Adding a "good first issue" label — a PR would be welcome! You can see how handler options are implemented in other handlers like drag pan or drag rotate.

**Comment by ryanhamley** [comment]
Closed by https://github.com/mapbox/mapbox-gl-js/pull/7863 🎉
