### ISSUE TITLE
Icons for Places and Highways do not Render in Safari

### ISSUE THREAD

**Issue by caneroj1** [mapbox/mapbox-gl-js#4728]
**mapbox-gl-js version**: master

### Steps to Trigger Behavior

 1. Use mapbox-gl-js to render the `mapbox://styles/mapbox/streets-v9` style
 2. Open the map in Safari Version 10.1
 3. See that there are no icons that mark places.

### Expected Behavior
There are black dots signifying the location of places on the map, like "Brak" and "Sabha", and there are also the icons behind the highway numbers.
<img width="1052" alt="screen shot 2017-05-20 at 11 32 31 am" src="https://cloud.githubusercontent.com/assets/3110602/26276943/2baea3a2-3d50-11e7-84cc-36800c975752.png">

### Actual Behavior
There are no black dots signifying the location of places on the map, like "Brak" and "Sabha", and highway icons are missing.
<img width="1279" alt="screen shot 2017-05-20 at 11 32 58 am" src="https://cloud.githubusercontent.com/assets/3110602/26276945/33cba738-3d50-11e7-89a1-2564411b8049.png">

I am using the mapbox-gl-js from master so I can get the fix from #4688, otherwise the labels wouldn't even be displaying.

**Comment by kkaefer** [comment]
This seems to be the same issue as in https://github.com/mapbox/mapbox-gl-js/pull/4688

@lbud, I think we need a longer-term solution for binding attributes in the correct order, and possibly about enabling/disabling them correctly. In Native, we explicitly specify the order of attributes, and bind them in ascending order.

**Comment by jfirebaugh** [comment]
> This seems to be the same issue as in #4688

I'm not so sure. @caneroj1 you said "I am using the mapbox-gl-js from master so I can get the fix from #4688". Can you confirm that you see this issue even after the fix from #4688?

**Comment by kkaefer** [comment]
@jfirebaugh I'm seeing the problem as well, and it has the same sluggish behavior as #4688. It only happens on every 20th reload or so.

![mapbox gl js debug page 2017-05-24 11-47-05](https://cloud.githubusercontent.com/assets/52399/26397464/b9557cfc-4076-11e7-912d-07a97e828894.png)

**Comment by mollymerp** [comment]
here's the `map.painter.cache` symbolIcon readout for when I can reproduce the issue
```json
{
    "program": {},
    "numAttributes": 3,
    "a_size": 0,
    "a_data": 1,
    "a_pos_offset": 2,
    ...
}
```
and the same for when the map is working correctly

```json
{
    "program": {},
    "numAttributes": 3,
    "a_pos_offset": 0,
    "a_size": 1,
    "a_data": 2,
    ...
}
```

**Comment by mollymerp** [comment]
Slightly different, but also occurred since the last release, so #4747 could be related.

**Comment by caneroj1** [comment]
@jfirebaugh Yes, I can confirm it is still happening.

@kkaefer Interesting. It happens more frequently than every 200th reload for me, though. They're never there.

I can try getting another build off of master sometime today and see what the status is.

**Comment by kkaefer** [comment]
@caneroj1 

> It happens more frequently than every 200th reload for me, though. They're never there.

That's possible. The attribute assignments are dependent only on the GPU driver/Shader compiler, so if your machine has a different GPU, you're likely to see different results. E.g. it's also possible that your shader cache has cached a version of the program with the bad attribute assignment, so you're now seeing it on every reload because it's retrieving the cached program.

**Comment by lbud** [comment]
Sorry for not taking a look at this sooner — this is the same root cause as #4688; that PR only fixed it for the `symbol_sdf` shader. For now I'm going to implement the same fix for the `symbol_icon` shader (manually binding `a_data` to attribute location 0 since it is always defined), and as @kkaefer says we should revisit the idea of manually binding all attributes in a fixed order as we do in native.

**Comment by jfirebaugh** [comment]
I think we should pursue the more complete fix now -- I think this issue could come up for any of the shaders.

If `createProgram` had access to a "program interface", it could iterate over `layoutAttributes`. We could give it access via `configuration`, by passing the full `programInterface` [here](https://github.com/mapbox/mapbox-gl-js/blob/13363a2b7eb6154272827dda066f588b050412bb/src/data/buffer_group.js#L34-L34) and storing a reference.

**Comment by lbud** [comment]
👉 #4794
