### ISSUE TITLE
Generated symbol icons change opacity at z>=1

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#4729]
**mapbox-gl-js version**: v0.37.0

### Steps to Trigger Behavior
Check out this fiddle: https://jsfiddle.net/bh3fgmyp/ Or:

 1. Instantiate a map, and prepare an image as a buffer like https://www.mapbox.com/mapbox-gl-js/example/add-image-generated/, except with alpha values <255
 2. Add the image as a symbol icon, as done in the example.
 3. Zoom in and out

### Expected Behavior
Raster should preserve alpha value at all zooms.

### Actual Behavior
Image grows noticeably more opaque at z>=1

**Comment by jfirebaugh** [comment]
Doesn't happen if you move to coordinates other than 0,0, so I think this is a duplicate of #4617.
