### ISSUE TITLE
Load Multiple Images for addImage()

### ISSUE THREAD

**Issue by realph** [mapbox/mapbox-gl-js#4736]
I need to add multiple images to my map using `addImage()`. The [example here](https://www.mapbox.com/mapbox-gl-js/example/add-image/) shows how to load and add a single image to your map.

I was wondering if there's a recommended way to load and add multiple images to the map?

Any help is appreciated. Thanks in advance!

**Comment by jfirebaugh** [comment]
Hi @realph, thanks for using Mapbox GL. The recommended way is to call `addImage()` multiple times, once for each of the images you want to add. For example, you can add a loop to the example code to do this. Hope that helps!

**Comment by realph** [comment]
👍

**Comment by willdawson** [comment]
@realph Did you ever get this working? Would love to see what you ended up with :)

**Comment by foundryspatial-duncan** [comment]
as of this comment, `addImage` is asynchronous, and takes a callback. So adding 5 images would require you to bury your code 5 levels deep in callbacks. Is there a way to do with with `Promise`s?

**Comment by twelch** [comment]
@foundryspatial-duncan it looks like loadImage() is the method with the callback not addImage(). From what I can see you don't have to wait for the callback of one request before kicking off additional so you can just amend the example with a loop like:

```
For each image url {
  map.loadImage(url, function(error, image) {
    map.addImage('foo', image)
  }
}
```

**Comment by foundryspatial-duncan** [comment]
Oops, that's my mistake. I was thinking of loadImage, where you'd want to make sure all of your images were loaded and added before trying to use them on the map... In that case you'd need to get creative with promises 👍

**Comment by andrealemanno** [comment]
i have almost the same problem but i think the code of @twelch can't work since this way you will give all the images the same id "foo". The problem of using a for loop is that you can handle when the callback will be called and so you can't decide a different id for each image you want to add to the map.

Does anyone has a solution for this?

**Comment by qrobin** [comment]
@andrealemanno just use array of objects to iterate. Previously create it:
```
const images =[
  {imageUrl: 'path/to/image_1.png', id: 'image_1'},
  {imageUrl: 'path/to/image_2.png', id: 'image_2'},
  ...
]
```

**Comment by ShadowSonic** [comment]
@qrobin 

    images.forEach(img => {
        map.loadImage(img.url, function(error, res) {
            map.addImage(img.id, res)
        })
    })

Missing ) from loadImage(

Tested with relative path /images/image.png and absolute path https://... both brings me this error

> Uncaught TypeError: Cannot read property 'width' of undefined
    at o.addImage (map.js:1104)
    at (index):75
    at ajax.js:157
    at XMLHttpRequest.M.r.onload (ajax.js:120)

**Comment by mvl22** [comment]
> Oops, that's my mistake. I was thinking of loadImage, where you'd want to make sure all of your images were loaded and added before trying to use them on the map... In that case you'd need to get creative with promises 👍

Has anyone come up with a workable solution?

I understand all the looping stuff above, but it seems to me that the loadImage/addImage pairs have to be run before the data is then loaded on the map.

(I do find it incredible that a modern mapping library makes it so incredibly difficult simply to create markers loaded over a URL dynamically.)

**Comment by mvl22** [comment]
> Has anyone come up with a workable solution?

Seems that this is the only workable approach:
https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/

**Comment by snorkleboy** [comment]
```
        Promise.all(images.map(img => new Promise((resolve, reject) => {
            map.loadImage(img.url, function (error, res) {
                map.addImage(img.id, res)
                resolve();
            })
        })))
        .then(()=>DoStuffWithLoadedImages)
```

**Comment by xiangzp** [comment]
Can I load a sprites sheet image,then set it to the 'icon-image'? the problem is, I don`t know how to make it works like `background-url`/`background-position` in CSS. I can`t find the solutions in [style-spec](https://docs.mapbox.com/mapbox-gl-js/style-spec/)

Has anyone come up with a workable solution?

**Comment by visser** [comment]
@snorkleboy , thanks for the example but I couldn't get it to work on my instance. Could you drop a codepen.io example as I'm confident yours is the right approach for loading multiple external Images before loading the Layers.

**Comment by brucelee21** [comment]
var hostpital = ['IMSS', 'ISSSTE', 'PEMEX', 'SEDESA', 'SEMAR', 'SSA'];

hostpital.forEach(myFunction);

function myFunction(value, index, array) {
    map_hospitales.loadImage(
        'directory_or_url_image' + value + '.png',
        function(error, image) {
            if (error) throw error;
            map_hospitales.addImage(value, image);
        }
    );
}

"properties": {
    "title": 'TITLE',
    "hospital": 'IMSS'


    map_hospitales.addLayer({
        'id': 'points',
        'type': 'symbol',
        'source': 'point',
        'layout': {
            'icon-image': '{hospital}',   // reference value in json  to property hospital. '{}'
            "icon-allow-overlap": true,
            'icon-size': .7
        }
    });

**Comment by S-n-d** [comment]
@snorkleboy's answer works. But beware: you cannot use SVG's 😉

**Comment by carlos-amador-git** [comment]
@snorkleboy yes, you can use SVGs.

**Comment by s-ai-kia** [comment]
Thank You @snorkleboy , works just fine.

const images = [{url:'',id:''},{url:'',id:''},{url:'',id:''}]
 Promise.all(
    images.map(img => new Promise((resolve, reject) => {
        map.loadImage(img.url, function (error, res) {
            if (error) throw error;
            map.addImage(img.id, res)
            resolve();
        })
    }))
).then(console.log("Images Loaded"))

Then addSource1(), addLayer1(); AddSource2(), AddLayer2() ....so on.

**Comment by elgabato** [comment]
> > Has anyone come up with a workable solution?
> 
> Seems that this is the only workable approach: https://docs.mapbox.com/mapbox-gl-js/example/custom-marker-icons/

good approach but I'd love to see a different approach using addImage.

**Comment by ssontag55** [comment]
> @snorkleboy yes, you can use SVGs.


"Could not load image because of The source image could not be decoded.. Please make sure to use a supported image type such as PNG or JPEG. Note that SVGs are not supported."
