### ISSUE TITLE
Return serialized style layer from map.getLayer() 

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#4742]
Currently, `map.getLayer()` returns a `StyleLayer` object, which has methods like `setPaintProperty`, etc.  This is misleading, because `StyleLayer`'s setters are not intended to be user-facing: to work properly, they depend on being called as part of the batch updating flow that's managed by the `Style` object.

I think it would be clearer to just return a serialized version of the layer from `map.getLayer()`.

**Comment by anandthakker** [comment]
Refs https://github.com/mapbox/mapbox-gl-js/issues/4738

**Comment by jfirebaugh** [comment]
Duplicate of #3713.
