### ISSUE TITLE
Standardizing raster inputs

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#4745]
Currently, gl-js accepts raster inputs in several forms:

1) As source for a raster layer type, via

    a) **a raster tileset:** in the form of a tile id, or
    b) **an image overlay:** in the form of a specific image url or dataurl (https://www.mapbox.com/mapbox-gl-js/example/image-on-a-map/)

2) As a symbol sprite via `addImage`, which takes either

    a) `HTMLImageElement`: an explicit DOM element, or
    b) `ImageData` buffer: a `Uint8ClampedArray` (https://www.mapbox.com/mapbox-gl-js/example/add-image-generated/)

To standardize inputs as much as possible, it would be ideal to add 2a) and 2b) into accepted raster source formats, and add 1b) to accepted `addImage` formats. The only exception is 1a), which as a tileset, makes sense only as a raster layer source.

**Comment by mourner** [comment]
Closing as stale since there seems to be not enough interest to pursue this.
