### ISSUE TITLE
Firefox for Android (53.0.2) - no glyphs are displayed

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#4747]
**mapbox-gl-js version**:
current master (06:30 UTC)

### Steps to Trigger Behavior

 1. create a standalone build from current master
 2. use mapbox-gl.js and mapbox-gl.css files in https://www.mapbox.com/mapbox-gl-js/examples/
 3. open the HTML with latest Firefox for Android (53.0.2) 

### Expected Behavior

glyphs are displayed

### Actual Behavior

glyphs are **not** displayed

![image](https://cloud.githubusercontent.com/assets/20856381/26390953/0b2ab0b2-4061-11e7-88c4-48481d1cd8e3.png)

Could be related to https://github.com/mapbox/mapbox-gl-js/issues/4607

**Comment by mollymerp** [comment]
@pathmapper thanks for using Mapbox. Does this also occur with the latest release (i.e. www.mapbox.com/mapbox-gl-js/examples) or was this introduced since the last release?

**Comment by pathmapper** [comment]
@mollymerp seems like this was introduced since the last release - with v0.37.0 everything is fine.

**Comment by jfirebaugh** [comment]
Almost certainly the same issue as #4728.
