### ISSUE TITLE
Change hash to be in lng,lat order

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#4748]
Ah, the age old question... 

The [`Hash`](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/hash.js) class is, to my knowledge, the only part of mapbox-gl-js that uses `lat,  lng` order instead of `lng, lat`. I can't find any information about why this might be, but I would guess that it is to do with the old map-feedback site. In future releases (after #4685 🚢 ), gl-js maps attribution control will link to the new feedback site, so changing the `Hash` hopefully won't have downstream complications from that. 💭 

Does anyone know why changing this might be problematic? @mapbox/gl-core

**Comment by jfirebaugh** [comment]
It's not just the map-feedback site, it's any site that uses `Hash` -- all Mapbox API embed pages, for example. This would be an extremely disruptive change and I don't think it would be worth it.

**Comment by mollymerp** [comment]
Aw dang. Isn't api-styles the only one that uses mapbox-gl though? Or do you just mean for preserving consistency between all mapbox embed sites?

**Comment by jfirebaugh** [comment]
Yeah, any site that uses `Hash` would be affected. If we change the format, and the site updates to the new version, any existing permalinks using the old format would stop working.

**Comment by peterqliu** [comment]
I think we originally did lat-lng for [consistency with Google](https://github.com/mapbox/gl-internal/issues/61).

>If we change the format, and the site updates to the new version, any existing permalinks using the old format would stop working.

A bit more kludge, but we could add a new hash parameter that communicates what order the coordinates should be interpreted in 😅

**Comment by mollymerp** [comment]
I'm going to close for now because this is not high priority and depends on a number of things external to mapbox-gl.
