### ISSUE TITLE
can't render text  like others

### ISSUE THREAD

**Issue by liwanchong04719** [mapbox/mapbox-gl-js#4759]
![image](https://cloud.githubusercontent.com/assets/14052734/26489996/2684ab7e-423c-11e7-88fe-104357810481.png)
 i want to render text in the map  but the middle can't show anything, they  have the same conditions, the conditions like below picture
![image](https://cloud.githubusercontent.com/assets/14052734/26490093/8e6734f0-423c-11e7-9c0d-285d05dac032.png)

**Comment by mollymerp** [comment]
Hi @liwanchong04719 - thank you for using Mapbox. 
This issue queue is for bug reports and feature requests only. If you intend to be doing one of those things, please fill out the issue template as the information we ask for is necessary for us to diagnose and/or address the issue. 

For questions like "how do I do x" please use either [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox-gl-js) or [Mapbox Support](https://www.mapbox.com/help/)
