### ISSUE TITLE
React component for mapbox-gl library

### ISSUE THREAD

**Issue by NameFILIP** [mapbox/mapbox-gl-js#4762]
Since React has conquered the frontend world, do you guys have any future plans on creating and maintaining a React wrapper for mapbox-gl?

I know there are a couple of existing libraries which try to do it, but none of them are really great..

**Comment by charliedotau** [comment]
hells yes.    Upvote.

**Comment by jasonbarry** [comment]
It would be great to have an official React component. The best / most maintained I've seen so far is from Uber: https://github.com/uber/react-map-gl

**Comment by alex3165** [comment]
I started to work on `react-mapbox-gl` a year ago now and I have iterated many times on it from feedbacks from developers using it in production which brought me to a v2 release yesterday https://github.com/alex3165/react-mapbox-gl. I would be happy to discuss about what you think is missing, if you think it is not good enough.

I also deployed a brand new website with better examples to show how to use the library: http://alex3165.github.io/react-mapbox-gl/

**Comment by anandthakker** [comment]
Closing here in favor of #6090
