### ISSUE TITLE
Bug: Polygons won't extrude for custom tilesets served by mapbox studio

### ISSUE THREAD

**Issue by jaskiratr** [mapbox/mapbox-gl-js#4764]
**mapbox-gl-js version**: **v0.33.0** and subsequent releases till **v0.37.0**

### Steps to Trigger Behavior

 1. Generate the tileset using tippecanoe `tippecanoe -ad -n buildings -f -o buildings.mbtiles buildings.geojson`
 2. Upload it to mapbox studio
 3. Test it using [3d-buildings](https://www.mapbox.com/mapbox-gl-js/example/3d-buildings/) example

### Expected Behavior
The extrusions render very well in versions **v0.32.0 & v0.32.1**

![image](https://cloud.githubusercontent.com/assets/8619877/26558783/63063cae-4479-11e7-8056-1373d1078ed9.png)

### Actual Behavior
The extrusions do not have height in versions **v0.33.0** onward
No errors/warnings are thrown in browser console. 

![image](https://cloud.githubusercontent.com/assets/8619877/26558802/7d6b1c90-4479-11e7-8d3b-c751e92157b4.png)

The height property is `Number`
<img src="https://cloud.githubusercontent.com/assets/8619877/26558888/f7715acc-4479-11e7-8910-f0552f68cbd9.png" alt="img" width="350px" >

**Comment by ryanbaumann** [comment]
@jaskiratr can you create a minimal example in a [JSfiddle](https://jsfiddle.net/)?

**Comment by jaskiratr** [comment]
Sure. Here you go.
**v0.32.1**
https://jsfiddle.net/1qy2hqr7/2/

**v0.37.0**
https://jsfiddle.net/ekk0a6n8/

Thanks!

**Comment by ryanbaumann** [comment]
@jaskiratr interesting, it looks as though your tileset contains a value that is interpreted as a string for height in 0.37 of GL JS.  Here's a [forked version](https://jsfiddle.net/6mL2cuk4/2/) of your v0.37 example with a popup showing the data property, and a categorical data-driven style added to test string property matches.

![2017-05-29 22_27_34-edit fiddle - jsfiddle](https://cloud.githubusercontent.com/assets/4342845/26569196/10020746-44be-11e7-8d37-fe48e2523f9e.png)

**Comment by jaskiratr** [comment]
@ryanbaumann Ah, interesting! You suspicion must be correct. Let me look into this today and prepare the dataset again. Will report back my findings. Thanks a bunch!
