### ISSUE TITLE
heading of an airplane in animate-point-along-route in examples

### ISSUE THREAD

**Issue by kkdd** [mapbox/mapbox-gl-js#4767]
Hello,
The heading of an airplane doesn't look nice in [animate-point-along-route](https://github.com/mapbox/mapbox-gl-js/blob/master/docs/_posts/examples/3400-01-15-animate-point-along-route.html) of examples. It would be better if it's along the locus:

![animate-point-along-route](https://cloud.githubusercontent.com/assets/5372642/26586174/532b72fc-4589-11e7-90ad-a25c978c8b4b.png)

**Comment by emperor1412** [comment]
I'm looking for this too.
I'm also wondering why the line appear to be curved for this far distance, so orient the plane along the curve like this would involve bearing calculation, no ?

Hi @mourner, how about this?

**Comment by andrewharvey** [comment]
> I'm also wondering why the line appear to be curved for this far distance, so orient the plane along the curve like this would involve bearing calculation, no ?

That's right see the updated example in #6554. The line is curved as it represents the shortest line between two points in a sphere.
