### ISSUE TITLE
Update Documentation for map.loadImage, loadImage does not support .svg file extension

### ISSUE THREAD

**Issue by denistsoi** [mapbox/mapbox-gl-js#4768]
**0.37.0**:

### Steps to Trigger Behavior

 1. use map.loadImage(`.svg`)
 2. no errors are thrown, image is not shown.

### Expected Behavior
SVG Image should be shown

(Example of expected behaviour)
<img width="664" alt="screen shot 2017-05-31 at 10 27 41 am" src="https://cloud.githubusercontent.com/assets/3061779/26613289/a3986552-45ec-11e7-95a1-79c754976443.png">

### Actual Behavior
Image should be shown (or have an appropriate error is Svg is unsupported). Documentation should be updated to reflect supported file types.

<img width="696" alt="screen shot 2017-05-31 at 10 27 06 am" src="https://cloud.githubusercontent.com/assets/3061779/26613290/a39f5786-45ec-11e7-8f1d-c71f4e1e6115.png">

---
Solved by converting SVG -> PNG (however, this should be updated in documentation).

**Comment by mollymerp** [comment]
@denistsoi thanks for using Mapbox and for the documentation improvement suggestion!

**Comment by mollymerp** [comment]
closed by #4769

**Comment by nik736** [comment]
I am also facing this issue. Are there any plans for adding svg support to loadImage and if not what's the recommended alternative to loadImage to make use of svgs? 

Thanks

**Comment by bennkingy** [comment]
Any alternative yet?
