### ISSUE TITLE
Per-layer transition property (style specification)

### ISSUE THREAD

**Issue by mbullington** [mapbox/mapbox-gl-js#4771]
## Motivation

Changing transition properties globally is often unwanted for only changing a single layer's transition duration, but the per property transition properties (while useful) can become tedious to maintain if you're setting them all to the same values.

Especially useful for disabling all transitions within a single layer.

## Design Alternatives

- Set global style, but changing every layer instead of a per-layer basis
- Maintaining and changing the *-transition property of every style property.

## Design

I propose a `transition` style property to handle this. Default would be 300ms, just like is hardcoded right now into Mapbox.

### Mock-Up

```
map.setPaintProperty("layer-123", "transition", {
  "duration": 300,
  "delay": 0
});
```

### Implementation

To implement in JavaScript, it would require some changes to the style spec library, as well as style/style_layer.js.

To implement in C++, I assume a similar process wouldn't be too difficult to replicate.

The style spec would also need to change, as well as documentation.

**Comment by anandthakker** [comment]
An alternative to making this a new style-spec property would be to simply add convenience methods in the JS & Native APIs for setting the per-style-property transition for all of a layer's properties to a given value.

**Comment by mourner** [comment]
Closing as stale since there seems to be not enough interest to pursue this. Personally I'd support the reverse — getting rid of individual property transitions and only having one global setting, which would simplify the spec & the code around this significantly.
