### ISSUE TITLE
document mouseenter/mouseleave

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#4772]
As used in the [hover popup example](https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/). 

Looks like these are different from the other mouse events, as they pertain to specific style layers, rather than the map object as a whole.

**Comment by mollymerp** [comment]
Oh good catch – it's only mentioned here https://www.mapbox.com/mapbox-gl-js/api/#map#on

If you want to add it it would go at the bottom of `src/ui/map.js` with the other map events https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/map.js#L1718-L1760 😸

**Comment by jfirebaugh** [comment]
Added in #5126.
