### ISSUE TITLE
querySourceFeatures for Original Feature

### ISSUE THREAD

**Issue by nitrag** [mapbox/mapbox-gl-js#4782]
I am trying to have a click event of a Polyline return the original geojson and send it to a server.

Currently calling `querySourceFeatures` returns the geometry at the **current zoom level**. However, because of Vector Tile simplification (from Mapbox) the geometry has significantly less points. At zoom level 14/15 there are 15 geometries, at zoom level 16 there are 66 geometries. I was hoping there would be a method to `querySourceFeatures` with a parameter of a certain zoom level, or the original version. It doesn't appear to be available. 

I tried manually zooming the map and then running `querySourceFeatures` but since `querySourceFeatures` doesn't have a callback the query starts/completes before the zoom finishes.

It's going to be confusing to my users why the map zooms in before moving to the next page.

Oh, and this is all because with the Mapbox API you can't query a Vector Tilesource by ID. I don't have it in a Dataset because there is currently no functionality for generating a Vector Tileset programmatically from an uploaded Dataset - it has to be manually initiated.

**Comment by andrewharvey** [comment]
> I don't have it in a Dataset because there is currently no functionality for generating a Vector Tileset programmatically from an uploaded Dataset - it has to be manually initiated.

https://github.com/mapbox/mapbox-cli-py/blob/master/README.md#datasets-create-tileset

If you check the source code you'll see the exact REST API call to make. You can then pull your original GeoJSON via the Datasets API.

**Comment by nitrag** [comment]
@andrewharvey This looks like it would work, it seems Studio does a similar API call.

However, I actually just remembered my issue with Datasets API is that I can't replace an entire Dataset with a new GeoJSON file - only edit individual features. So right now I am skipping the dataset, generating the Shapefile and uploading to Tilesets API. This leaves me without a dataset to query for an exact Feature ID.

**Comment by andrewharvey** [comment]
> However, I actually just remembered my issue with Datasets API is that I can't replace an entire Dataset with a new GeoJSON file - only edit individual features.

Right now you either need to make individual delete calls to the API to empty all features then insert each new feature, or delete the dataset and make a new one (more efficient but you'll need to keep track of the changing id).

> So right now I am skipping the dataset, generating the Shapefile and uploading to Tilesets API. This leaves me without a dataset to query for an exact Feature ID.

It's a bit messy but with the above you should be able to get it working with the Datasets API. If not you might need to build your own external service for this. Tilesets aren't designed to retrieve features, as it's a loss process, a Tileset has geometries simplified and cut to tile boundaries.

**Comment by jfirebaugh** [comment]
The fact that feature querying returns results only for loaded tiles, and only the (simplified) geometry that is present in the vector tiles, are fundamental limitations and unlikely to change. These APIs are not intended to be a general purpose spatial query system, and we don't plan to extend them to load tiles that aren't necessary for rendering the map, for example.

Thanks @andrewharvey for suggesting other approaches based on the Datasets API. I agree with those recommendations.

**Comment by nitrag** [comment]
Thanks folks for the quick feedback. I feared it had to do with the
limitations of currently loaded tiles. I'll attempt to get the API
procedure running but I really wish there was an "Empty Dataset" endpoint
instead of removing one by one, especially seeing as how that would burden
your API server.
