### ISSUE TITLE
Navigation Control compass click event IE 11 throws: Object doesn't support this action

### ISSUE THREAD

**Issue by keyofj** [mapbox/mapbox-gl-js#4784]
mapboxgl - v.0.37.0
Internet Explorer - 11.0.38

When you click the compass the following error is thrown only in Internet Explorer:

Object doesn't support this action
File: mapbox-gl.js, Line: 370, Column: 41

If you click on the error it takes me to line 105 in function copyMouseEvent(e) 

This can be duplicated using the examples page: [Navigation Control](https://www.mapbox.com/mapbox-gl-js/example/navigation/)

Open IE Debugger Tools (F12) and you will see the error above.

In the example page, the map will go ahead and return to due North, but in  applications that use IE 11 embedded the JavaScript error raises an alert window and will not allow the application to continue.

**Comment by jfirebaugh** [comment]
Fixed in #5157.
