### ISSUE TITLE
Full screen control should not be displayed on unsupported device

### ISSUE THREAD

**Issue by ethan-ho** [mapbox/mapbox-gl-js#4786]
**mapbox-gl-js version**: 0.37.0

### Steps to Trigger Behavior

 1. Visit [Fullscreen](https://www.mapbox.com/mapbox-gl-js/example/fullscreen/) example on iOS device, I am using iPad  
 2. Click the fullsceen button on the map

### Expected Behavior
If fullscreen JavaScript API is not supported on current device, the button should not be added to the map instance, like the GeolocateControl [currently does](https://github.com/mapbox/mapbox-gl-js/blob/c3de2d2a681ce69e61089db3a22e5225175e217a/src/ui/control/geolocate_control.js#L70).

### Actual Behavior
The button is appearing but do nothing.

**Comment by mollymerp** [comment]
closed by #4838

**Comment by jerrygarciame123** [comment]
Can't we just use JS to check and add/remove accordingly?  Thanks, John
