### ISSUE TITLE
Mapbox fails to register service worker on Chrome 59

### ISSUE THREAD

**Issue by sondreb** [mapbox/mapbox-gl-js#4788]
Chrome was recently upgraded to version 59, which have some changes to how it handles CSP. Was unable to find any details on this change, but Mapbox GL JS now fails, where on version 58 it worked just fine.

Console error:

_Refused to create a worker from 'blob:URL' because it violates the following Content Security Policy directive: "script-src * 'unsafe-eval' 'unsafe-inline'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback._

"unsafe-eval" and other settings for CSP is enabled to make Mapbox work, and the exact same codebase runs fine on Chrome 58, but not 59.

Anyone knows what is now needed in the CSP to make Mapbox work again?

Mapbox GL JS version: 0.37

**Comment by kristfal** [comment]
This is a very liberal CSP that works with mapbox-gl-js. You can gradually restrict it to your own preferences by replacing wildcards with your own URLs.

```
<meta http-equiv="Content-Security-Policy" content="default-src * 'unsafe-inline' 'unsafe-eval' 'self'; script-src * 'unsafe-inline' 'unsafe-eval' blob:; img-src * 'self' data: blob:;"/>
```

**Comment by anandthakker** [comment]
👍 @kristfal 

If you're using Mapbox tiles & other resources, then the following is a more restrictive CSP that should work.

```html
<meta http-equiv="Content-Security-Policy" content="child-src blob: ; img-src data: blob: ; script-src 'self' 'unsafe-eval'; connect-src https://*.tiles.mapbox.com https://api.mapbox.com">
```
(This is [documented here](https://www.mapbox.com/mapbox-gl-js/api/#csp-directives) for future reference)

**Comment by sondreb** [comment]
Thanks, this did help :)

**Comment by yipcma** [comment]
any chance to have an CSP that does not involve the to be deprecated `child-src`? I tried different combination of `worker-src` and `frame-src` without success. map doesn't load.

**Comment by Tarun-Kumar-Sharma-svg** [comment]
where do I put the url
