### ISSUE TITLE
Marker click throws TypeError: Cannot read property 'x' of null

### ISSUE THREAD

**Issue by keyofj** [mapbox/mapbox-gl-js#4791]
mapboxgl v.0.37.0

When a marker is placed on screen and then subsequently clicked the following error is thrown:

`index.js:28 Uncaught TypeError: Cannot read property 'x' of null
    at Point.equals (index.js:28)
    at HTMLDivElement.s (bind_handlers.js:113)
​`
It is inconsistent and sometimes goes away if you click on the marker several times or if you drag the marker to a different position.  It sometimes does not occur at all.

It happens when a marker is placed on screen after using the autocomplete plugin.

It can also happen adding a marker using a drag n drop action.

It happens across desktop browsers IE, Chrome, Firefox.

The marker is created using a custom div element:
`var marker = new mapboxgl.Marker(el, { offset: [-10, -15]).setLngLat(lngLat).addTo(map)`

You can access a test map [here:](http://mapstaging.listcounts.com/ViewMap?mapGUID=41223db7-31fc-423d-ac1c-ccb33da46100&mapType=1)

- Use the search box at the top or on the right hand side are map tools. Click and drag the marker on to the map.

- After the marker is placed on the map a popUp auto opens. Whether that is closed or not, or if you drag the marker or any other action, just click on the marker to get the error.

Again it is inconsistent. Any ideas on what may trigger this? I am at a loss.

Thank you,

**Comment by jfirebaugh** [comment]
I'm seeing the marker jump around unexpectedly, but not any `TypeError`s. Chrome 58.0.3029.110.

![gl](https://user-images.githubusercontent.com/98601/26845644-ffe0b36e-4aab-11e7-85ed-3ae02f315c86.gif)

Could you please create a minimal example on JSFiddle that reproduces the issue?

**Comment by keyofj** [comment]
@jfirebaugh It does not do it when you are dragging. Just click on the marker. My 2nd bullet point was confusing. It is only on click. Sorry for not being clearer on that.

**Comment by jfirebaugh** [comment]
I don't see any error when clicking on the marker either.

**Comment by keyofj** [comment]
Hmmm...so I wonder what else must be installed on my machine that may be causing it to error? I am using the same version of Chrome 58.0.3029.110. Any suggestions of where I might look?

**Comment by keyofj** [comment]
So I tested this at home and I get the same results with the error happening on click. I am really baffled why you do not see it happening.

**Comment by anandthakker** [comment]
I'm able to reproduce the error using the link provided above.  Somehow, it looks like when clicking the marker, [`onMouseDown`](https://github.com/mapbox/mapbox-gl-js/blob/bef996624ff5e7d8feb5475512b0d1bd65d1dd14/src/ui/bind_handlers.js#L47) is not being fired before `onClick`.  When clicking elsewhere on the map, though, the mousedown handler does fire before the click handler as expected.

@keyofj is there any chance you're handling `mousedown` events on your marker div, and stopping propagation?

**Comment by keyofj** [comment]
@anandthakker Not for mousedown, but I do have these two listeners:

`
// keep the map from panning when marker is dragged
            markerProperties.element.addEventListener("mouseenter", function (e) {
                map.dragPan.disable();
            });
            markerProperties.element.addEventListener("mouseleave", function (e) {
                map.dragPan.enable();
            });
`

**Comment by yipcma** [comment]
got same issue when using it in vue

```
Uncaught TypeError: Cannot read property 'x' of null
    at Point.equals (mapbox-gl.js:53)
    at HTMLDivElement.s (mapbox-gl.js:353)
    at sendClick (framework7.js:9904)
    at HTMLDocument.handleTouchEnd (framework7.js:10090)
```

**Comment by keyofj** [comment]
@anandthakker Looking at the reference from yipcma above, should we alter the way we are making the popup? This is how we are attaching the popUp in the click event of the marker.

```javascript
var infoWindow = new mapboxgl.Popup({
        closeButton: false,
        closeOnClick: false,
        offset: {
                'top': [0, -18],
                'top-right': [0, -18],
                'top-left': [0, -18],
                'bottom': [0, -18],
                'bottom-left': [0, -18],
                'bottom-right': [0, -18],
                'left': [0, -18],
                'right': [0, -18],
            }
});

marker.setPopup(infoWindow);
```

**Comment by anandthakker** [comment]
@keyofj Hmm, I don't see anything problematic in the code snippets you've posted.

Without a minimal example reproducing the bug, it's very difficult to diagnose it -- particularly if, as I suspect may be the case, it has something to do with how DOM event handlers are interacting.

I've been attempting to reproduce by modifying an example like https://www.mapbox.com/mapbox-gl-js/example/set-popup/, but I'm having no luck.  Could you try making a small example that reproduces the bug outside of the context of your application?  Thanks!

**Comment by keyofj** [comment]
We are using Kendo UI for the drag and drop feature. I am wondering if that is having some conflicting issue. I will try to remove it and see if it still happens and try to get a smaller sample together. It may take me a couple days with the other work items I have to finish for our Mapbox deployment. Thank you for all of your help.

**Comment by keyofj** [comment]
@anandthakker Ok I have found it is the Kendo UI draggable that is causing the issue. SO I am going to close this AND also give you  a HUGE THANK YOU for looking at this. I wish I would have figured this out sooner so it would not have taken so much of your time.

**Comment by anandthakker** [comment]
@keyofj no problem, glad to hear the problem is solved! 🎉
