### ISSUE TITLE
Dynamically add curved labels along route

### ISSUE THREAD

**Issue by daumann** [mapbox/mapbox-gl-js#4801]
Similar to this leaflet plugin: http://makinacorpus.github.io/Leaflet.TextPath/ I would like to add curved text labels on the map.

Example: given three lat/lng points (north west, centroid, north east of a polygon) - I would like to add a label which is drawn along the curved route of those points.

What I found so far was https://www.mapbox.com/blog/placing-labels/ (a 2014 post showing this functionality - but it does not seem to be exposed with the mapbox GL API at the moment)

Another finding is this here: https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-route/ - only the moving point along route should be a static label along route

Is this already possible with the current API? Is it planned? Thanks for any pointers.

**Comment by mourner** [comment]
You can add labels to GeoJSON lines the same way you do for vector tile roads. Check out the documentation for the symbol layer: https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol — `symbol-placement: "line"` is what you want.

**Comment by daumann** [comment]
@mourner Is there a mapbox line "Bézier curve" interpolation functionality? Or does one have to construct a "curve" oneself?

**Comment by mourner** [comment]
@daumann you would have to construct it yourself.

**Comment by andrewharvey** [comment]
@daumann http://turfjs.org/docs/#bezier
