### ISSUE TITLE
TileLayer support in mapbox gl?

### ISSUE THREAD

**Issue by KfirShainholtz** [mapbox/mapbox-gl-js#4802]
Hey guys,
I've been mastering the API pretty much,
and didn't encounter any TileLayer support in mapbox gl.

To clarify myself, I want to add to my **custom sources, that I serve**,
another layer on top of them (sometimes) like buildings, roads etc.

Is it possible, and if it does, can it be done easily? I saw the vector sources,
but couldn't understand how to plug both sources on top of each other.

If there's any L.TileLayer simillarities, I would really appreciate anyone to let me know
about it.

Thanks!

**Comment by mollymerp** [comment]
Hi @KfirShainholtz, thanks for using Mapbox. Yes, you can add a [raster source](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-raster) using the tile URL for your custom tiles and a [raster layer](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-raster) to add it to the map.

In the future, please only use this issue tracker for bug reports and feature requests. If you have usage questions, I recommend you ask on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox-gl-js) or contact Mapbox support.
