### ISSUE TITLE
symbol text rendered twice with zoom function for text-anchor

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#4810]
**mapbox-gl-js version**: 0.37.0

https://jsbin.com/qubimewusu/1/edit?html,output

I notice this all the time, but can't reliability replicate 100% of the time, but zooming in and out crossing the zoom where the labels swap from text-anchor: center to bottom you'll see the label rendered twice for a few frames.

![out2](https://user-images.githubusercontent.com/117278/26959447-874581fe-4d13-11e7-9bd5-ede01fc3c356.gif)

It happens with all `place-city-lg-s` layer labels from Mapbox Streets, but I can't replicate with a GeoJSON source https://jsbin.com/qaruzetaci/1/edit?html,output.

I can't say for sure, but it seems this behaviour started appearing in 0.27.0, maybe related to https://github.com/mapbox/mapbox-gl-js/issues/3669.

**Comment by nspringer-alk** [comment]
I am having similar issues with my own styles.  I have a city symbol layer transition like the above on `text-anchor` and `text-justify` between levels 8 and 9:
```
"text-justify": {
      "stops": [
        [
          8,
          "left"
        ],
        [
          9,
          "center"
        ]
      ]
    },
    "text-anchor": {
      "stops": [
        [
          8,
          "bottom-left"
        ],
        [
          9,
          "center"
        ]
      ]
    }
```
The weird thing is the double labels show up at zoom 9.0 to 9.45, after the transition.  This is version 0.39.
![image 395](https://user-images.githubusercontent.com/7513188/31230809-17024cea-a9b3-11e7-85a3-0649bf73dd45.png)

**Comment by ChrisLoer** [comment]
I believe this should be fixed on `master` now that we've merged #5150, but I'm not quite sure how to test it. @andrewharvey, any chance you could test this with `master` and see if we've resolved the problem?

**Comment by andrewharvey** [comment]
@ChrisLoer I still see the issue with master with #5150.

**Comment by ChrisLoer** [comment]
@andrewharvey Thanks for checking!
