### ISSUE TITLE
Feature visibility control by style or data

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#4812]
Generally the server serve the data with vector tile format, and the `mapbox-gl-js` client api render the features by a specified `style`. 

Now who should take the responsibility for  controlling the visibility of the features? Because the server have to full control to serve data according to the tile coordinate, features not returned by the tile will not be rendered. Also the style can control the visibility of the features too.

For example, a certain layer of features should only be visible when `zoom>10` , then we have too choice:

1.  Return this features in the vector tile even if the `zoom<=10`, but set the style to not display these features.

2.  Remove the features from the vector tile once `zoom<=10`.

Which is better?

Further more, for a given tile coordinate `x` `y` `z`, how do you decide which data should be served? For example tile with `x=2` `y=2` `z=1` will cover a huge area of the world, it is unacceptable to return all the features. Is it possible to share the same filter rule in the style of both client and server side?

**Comment by jfirebaugh** [comment]
What data you include in a vector tile is a cartographic decision that depends on how you plan to use the tiles. For example, if you never want to use the vector tiles with a style where buildings are visible at z<=10, then omitting them from the vector tiles is fine. If you do include them, then you may be able to use the vector tiles with multiple styles, some of which do show buildings at those zoom levels.
