### ISSUE TITLE
text-anchor, text-justify inconsistent with symbol-placement lines

### ISSUE THREAD

**Issue by daumann** [mapbox/mapbox-gl-js#4822]
Here is a demonstration:
http://jsfiddle.net/wm18a33d/131/

Despite 
```
"text-anchor": "center",
"text-justify": "center",
```
The text seems to be aligned to the left of the line on some zoom levels.

My guess is that on some zoom levels, the engine is trying to repeat the symbol (text) but the repetition is not yet shown, leaving only the first symbol + the space in-between.
So for example with "test test test" as the text it looks like that:

` "test test test"___________|cut|"test test test"`

Is there an option to disable repetition of symbols or dynamically setting the font-size so that 1 text symbol fills the whole available space (on the line)? This would fix the problem.

**Comment by daumann** [comment]
@mourner is there an API option to disable repetition of symbols on a line?

**Comment by mourner** [comment]
> Is there an option to disable repetition of symbols or dynamically setting the font-size so that 1 text symbol fills the whole available space (on the line)? This would fix the problem.

This was fixed by introducing `symbol-placement: line-center` in #6821.
