### ISSUE TITLE
Base label "keep-upright" orientation based on start and end of label

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#4825]
With https://github.com/mapbox/mapbox-gl-js/pull/4781, labels will now re-orient themselves based on perspective. 🎉 

The current approach determines label orientation by looking at whether the segment the anchor of the label is on is upright: this can lead to labels that look "upside down" even though technically the segment their anchor is on is "right side up".

![image](https://user-images.githubusercontent.com/375121/26845174-8130bbdc-4aaa-11e7-886d-e8c8933fc766.png)

I think it would probably be a better heuristic if we detected the orientation of a line label based on the beginning and the end of the label instead of the orientation of the middle line segment (although there could certainly be cases where this looked less natural).

/cc @nickidlugash @ansis

**Comment by nickidlugash** [comment]
I think this makes sense 👍  While there will be instances where the middle segment is more representative of a larger proportion of the label, I think it's probably easier to read a label that _starts_ upright, all else being equal.
