### ISSUE TITLE
Support lab color interpolation

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#483]
From https://github.com/mapbox/mapbox-gl-style-spec/issues/62#issuecomment-46887921 - there are many perceptual scales, but this is a good place to start.

**Comment by tmcw** [comment]
Now that data-driven styles have landed, I think this is actionable.

```js
'circle-color': {
    property: 'sqrt',
    'interpolate-color': 'lab',
    stops: [
        [0, '#f1f075'],
        [250, '#e55e5e']
    ]
}
```

cc @lucaswoj @jfirebaugh ?

**Comment by lucaswoj** [comment]
@tmcw Do you have thoughts on exposing a `interpolate-color` configuration option vs adopting a better color interpolation algorithm by default?
