### ISSUE TITLE
0.38.0 does not pick up canvas source size changes

### ISSUE THREAD

**Issue by skeggse** [mapbox/mapbox-gl-js#4831]
**mapbox-gl-js version**: `0.38.0`

### Steps to Trigger Behavior

 1. Create a map with a canvas source
 2. Resize the canvas, and redraw its contents

### Expected Behavior

The drawn image accurately reflects the canvas contents, accounting for the canvas's new resolution.

### Actual Behavior

The drawn image reads from the original resolution, producing odd artifacts if the canvas shrunk, or stretching the image if the canvas grew.

Note that this behavior changed between `0.37.0` and `0.38.0`, and setting `animate` to true doesn't solve the problem.

Happy to provide an MCVE on request.

**Comment by lbud** [comment]
@skeggse thanks for the report. I'm not able to reproduce this — it would be great if you could provide an MCVE 🙏
