### ISSUE TITLE
Inconsistent zoom value when add layers with different tilesize

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#4837]
Here is the [live example](https://jsfiddle.net/3htth7Lr/1/).

Once you open the network monitor you will find that for a given zoom level like `16`, the vector layer will load sources as it is, while the raster layer will load tiles of zoom `17`.

So if no raster tiles will be loaded at zoom `17`, this is caused by the different `tileSize`, `512` for the vector tile source  and  `256` for the raster source.

I have tried to set the size to `256` for vector tile source, it will throw error which says vector tile only support tilesize of `512`. 🐶 

Anyway to fix that?

**Comment by jfirebaugh** [comment]
No, this is expected behavior. The intrinsic tile size for Mapbox GL is 512, so raster sources with 256px tiles will load tiles from one zoom level higher in order to cover the same area at the appropriate resolution.
