### ISSUE TITLE
I can’t add a geojson layer sourced from a data attribute.

### ISSUE THREAD

**Issue by jonnybarnes** [mapbox/mapbox-gl-js#4844]
**mapbox-gl-js v0.38.0**:

When given the following HTML:

```html
<div class="map"
    data-latitude="53.4983"
    data-longitude="-2.3805"
    data-geojson="{
    'type': 'FeatureCollection',
    'features': [{
        'type': 'Feature',
        'geometry': {
            'type': 'Point',
            'coordinates': [-2.3805, 53.4983]
        },
        'properties': {
            'title': 'The Bridgewater Pub',
            'icon': 'marker'
        }
    }]
}"></div>
```
with the folliwing javascript:
```js
//
let dataLatitude = div.dataset.latitude;
let dataLongitude = div.dataset.longitude;
let data = div.dataset.geojson;
//
let map = new mapboxgl.Map({ // <-- line 100 of mapbox-utils.js
    container: div,
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [dataLongitude, dataLatitude],
    zoom: 15
});
//
map.on('load', function () {
    map.addLayer({
        'id': 'points',
        'type': 'symbol',
        'source': {
            'type': 'geojson',
            'data': data
        },
        'layout': {
            'icon-image': '{icon}-15',
            'text-field': '{title}',
            'text-offset': [0, 1]
        }
    });
});
```
I get the following error in my Console:

Error | Location
-------|------------
`[203]</Evented.prototype.fire` | `mapbox-gl.js:416:1187`
`[203]</Evented.prototype.fire` | `mapbox-gl.js:416:1027`
`[203]</Evented.prototype.fire` | `mapbox-gl.js:416:1027`
`[83]</GeoJSONSource</e.prototype.load/<` | `mapbox-gl.js:176:1176`
`[83]</GeoJSONSource</e.prototype._updateWorkerData/this.workerID<` | `mapbox-gl.js:176:1828`
`[193]</Actor.prototype.receive` | `mapbox-gl.js:396:658`
`Actor` | `mapbox-gl.js:396:97`
`Dispatcher` | `mapbox-gl.js:412:241`
`t` | `mapbox-gl.js:308:1292`
`[190]</Map</e.prototype.setStyle` | `mapbox-gl.js:390:9245`
`e` | `mapbox-gl.js:390:2626`
`addMap` | `mapbox-utils.js:100:14`
`<anonymous>` | `maps.js:7:4`
`__webpack_require__`  | `bootstrap%206b1d5c4242398ec1dc6a:19`
`<anonymous>` | `bootstrap%206b1d5c4242398ec1dc6a:65`
`<anonymous>` | `https://jonnybarnes.localhost/assets/js/maps.js:1:11`

I’m compiling that down to es5 with webpack/babel-loader, but the resultant js isn’t very different:
```
var map = new _mapboxGl2.default.Map({
    container: div,
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [dataLongitude, dataLatitude],
    zoom: 15
});
```
and the `map.on('load')` block is identical.

Indeed the map itself loads, but the geosjon layer isn’t added.

Anyone know what’s going wrong?

I can `console.log()` the data variable and it looks correct.

**Comment by jfirebaugh** [comment]
Thanks for providing the error stack trace. What's the error message?

**Comment by jonnybarnes** [comment]
> What’s the error message?

“Error”

I have a workaround for this, as oppose to generating the GeoJSON backend and embedding it in the HTML, I can just include the things that alter per map, i.e. the point name and point marker, and generate the data variable in my js. Which works.

Originally I had `<div class="map"></div><script>var geojson={...}</script>` which worked locally, but stopped working on the server due to a CSP policy. So I took the geojson string and put it in a data attribute as above and I couldn’t get it to work even locally.

**Comment by jonnybarnes** [comment]
So maybe you can close this as I have a workaround, but I can’t understand why the above didn’t work

**Comment by jfirebaugh** [comment]
Well, not a very helpful error message, is it. :) Can you provide a self-contained JSFiddle that demonstrates the issue? We can take a closer look. Thanks!

**Comment by jonnybarnes** [comment]
Okay, here goes.

JSFiddle showing error: https://jsfiddle.net/jonnybarnes/ra1m18n1/

Various files showing my code: https://gist.github.com/jonnybarnes/87f003ada660a6da4563f26fa058b38c

**Comment by jfirebaugh** [comment]
That's too much code for us to be able to diagnose the issue. Can you please create a more minimal example (e.g. no compiled modules, no external dependencies other than Mapbox GL JS)?

**Comment by AugustMiller** [comment]
This certainly seems like it could stem from passing a string (the data-attribute's value) to a function that expects an object… all the examples from the Mapbox documentation point toward this requiring an object.

What happens when you call `JSON.parse(div.dataset.geojson)`, instead of passing the raw content of the attribute?
