### ISSUE TITLE
DDS line-color interpolation not quite right

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#4850]
**mapbox-gl-js version**: 0.38.0

### Steps to Trigger Behavior

check out https://jsfiddle.net/ezkL8mhc/2/, or

 1. Add a geojson dataset of line strings, with some numerical property.
 2. Add a line layer using that geojson as a source, and style it with a continuous data-driven line-color with that numerical property. In the jsfiddle, i used

```
            'line-color': {
                'property':'total',
                'stops':[[0,'lime'], [300, 'blue']]
            }
```

### Expected Behavior
The colors should interpolate smoothly between the declared stops. 

### Actual Behavior
The colors don't quite correspond to the values. Below is a screenshot from the jsfiddle, where i've drawn both the lines, as well as a symbol layer that articulates the same `total` property in text. Note that although the lines should go from lime to blue as the numbers increase, that isn't always case: 

<img width="401" alt="screen shot 2017-06-17 at 9 54 42 pm" src="https://user-images.githubusercontent.com/4551508/27258167-20afd624-53a8-11e7-8399-d5fc8d5aab49.png">

**Comment by peterqliu** [comment]
(sorry for the massive geojson in the example)

**Comment by peterqliu** [comment]
Made a more pared down test case [here](https://bl.ocks.org/peterqliu/a17f3afd70fc65c03dfbad80849246ac), and the code lives [here](https://gist.github.com/peterqliu/a17f3afd70fc65c03dfbad80849246ac).

![screen shot 2017-06-23 at 5 34 00 pm](https://user-images.githubusercontent.com/4551508/27504168-2ccab870-583a-11e7-90f5-280fb4a9e5d8.png)

The underlying dataset for the lines, triangles, and numbers is a geojson of linestrings, each with a `total` property. The lines and triangles are colored based on `total`, and the numbers display `total` itself.

The lines and triangle symbols are styled with the [same data-driven color rule](https://gist.github.com/peterqliu/a17f3afd70fc65c03dfbad80849246ac#file-index-html-L28-L31), which goes from `red` to `blue` as `total` goes from `0` to `120`. Despite this, the triangles' colors clearly don't match their corresponding lines.

It looks like the triangle colors are closer to what the numbers indicate, which suggests that there's a bug with DDS `line-color`

**Comment by mollymerp** [comment]
@peterqliu I was just about to ask for something this 😛  Will dig in next week 🎨

**Comment by peterqliu** [comment]
:man_facepalming: just realized i had pulled one of these https://github.com/mapbox/mapbox-gl-js/issues/4514#issuecomment-290179605

<img src ='https://m.popkey.co/2805e4/0mrKW_s-200x150.gif'>
