### ISSUE TITLE
Customize inertia values from drag pan

### ISSUE THREAD

**Issue by Jinkwon** [mapbox/mapbox-gl-js#4851]
**mapbox-gl-js version**:
Latest version

### Steps to Trigger Behavior
No steps. :)

### Expected Behavior
There is no way to customize velocity value.
https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/handler/drag_pan.js#L153

### Actual Behavior
I need options to configure velocity value.

**Comment by peterqliu** [comment]
`drag pan` is set at a velocity such that the map position under the mouse stays constant throughout the panning motion. How would you propose a configurable velocity would work? Or do you mean the velocity after `mouseup`/`touchend`?

**Comment by mourner** [comment]
I guess we want [these const values](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/handler/drag_pan.js#L9-L10) exposed as options. E.g. Leaflet allows their customization.

**Comment by Jinkwon** [comment]
@mourner That's what I wanted. 👍

**Comment by 1ec5** [comment]
Relatedly, on iOS, we abandoned these options in favor of a default inertial pan that lasts about one second regardless of the strength of the gesture (mapbox/mapbox-gl-native#1266), plus a `decelerationRate` option (mapbox/mapbox-gl-native#5504). The default was chosen for consistency with scroll views on that platform. It would be nice to be able to tailor the internal panning for touch devices (#949) differently than when using a mouse on a desktop platform.

**Comment by Jinkwon** [comment]
Is there any working progress?

**Comment by mourner** [comment]
@Jinkwon not at this moment, but we'd of course welcome a pull request.

**Comment by Jinkwon** [comment]
@mourner OK. ;)

**Comment by ansis** [comment]
This was implemented a while back in https://github.com/mapbox/mapbox-gl-js/pull/8887

**Comment by dimaShin** [comment]
Hi guys.
Thanks for this feature. 
Unfortunately, it seems broken now. 
[The original implementation of the DragPan enable method](https://github.com/mapbox/mapbox-gl-js/pull/8887/files#diff-e3bc728d4d52181f4190413efb4ecfb2b039e8386cf17555b79d758d3d115790R104) had a check to ignore calls when already enabled. However, [later this check was removed](https://github.com/mapbox/mapbox-gl-js/commit/164b0bea09fcafdbfc22c170f6adf54cdc9fd5bc?diff=split&w=0#diff-c2b5117facc11353f28baafa5d7788deb1234055fc5602b565ff180b86d11de8R52). This means that any call will rewrite the inertia options. I'm facing this behaviour with [the draw library](https://github.com/mapbox/mapbox-gl-draw/blob/main/src/setup.js#L56).

@ansis , Github [blames](https://github.com/mapbox/mapbox-gl-js/commit/164b0bea09fcafdbfc22c170f6adf54cdc9fd5bc) you :)
