### ISSUE TITLE
dragRotate.disable still allows for rotation when using keyboard

### ISSUE THREAD

**Issue by keyofj** [mapbox/mapbox-gl-js#4855]
mapboxgl 0.38.0

When map.dragRotate.disable() is set it correctly stops the mouse from being able to rotate / pitch the map. But you can still do it using SHIFT + UP ARROW on the keyboard.

This can be reproduced on the example page

[Disable map rotation](https://www.mapbox.com/mapbox-gl-js/example/disable-rotation/)

Is there another function to set to disable the keyboard controls?

**Comment by ChrisLoer** [comment]
Hi @keyofj, you can [disable all keyboard navigation](https://www.mapbox.com/mapbox-gl-js/api/#keyboardhandler#disable) with

`map.keyboard.disable()`

Is that what you're looking for, or are you specifically looking for disabling rotation but leaving other keyboard navigation controls in place?

**Comment by jfirebaugh** [comment]
> disabling rotation but leaving other keyboard navigation controls in place

That specifically is being tracked in #3768.

**Comment by keyofj** [comment]
Thanks Chris. That should work. Our users at this time will not need the keyboard navigation controls.

Michael

________________________________
