### ISSUE TITLE
Loading maps for the first time is too slow

### ISSUE THREAD

**Issue by JunYanchan** [mapbox/mapbox-gl-js#4858]
**mapbox-gl-js version**:0.38.0

### Steps to Trigger Behavior

 1.I used the official mapbox://styles/mapbox/light-v9 to set map styles and found initialization was too slow to load maps.
 2.Finds that you always ask for a certain type of PBF format file（）
 

### Expected Behavior
      Load maps as quickly as possible
### Actual Behavior
      **Open Network,found a lot of requests for .pbf**  
      **For example, many similar requests url：** (https://api.mapbox.com/fonts/v1/mapbox/Open%20Sans%20Semibold,Arial%20Unicode%20MS%20Bold/39168-39423.pbf?access_token=pk.eyJ1IjoiY2hlbmp1bnlhbiIsImEiOiJjaXh6aHE3enIwMDR2MzNvN2YwMmZvMDlyIn0.2Cy8Z_qvQ1IGKpqASmZjtA )

**Comment by jfirebaugh** [comment]
Hi @JunYanchan, thanks for the report. We're aware that loading glyph PBFs for CJK languages is a performance issue in network-constrained environments. We're tracking this in #3466.

**Comment by JunYanchan** [comment]
@jfirebaugh Thank you. I read the article, but it doesn't seem to explain how it works. Can you tell me the specific usage? Developing mapbox GL.js (javaScript) on the web web page?
