### ISSUE TITLE
Why does transform.coveringTiles return nothing when z is smaller than minZoom?

### ISSUE THREAD

**Issue by immiao** [mapbox/mapbox-gl-js#4863]
**mapbox-gl-js version**:
Latest version.

### Steps to Trigger Behavior
            var tiles = this.mapTransform.coveringTiles({ tileSize: 512, minzoom: myMinZoom, maxzoom: 22, roundZoom: true });

### Expected Behavior
I want the higher zoom-level covering tiles information but not the current zoom-level covering tiles by setting `minzoom`.

### Actual Behavior
It returns an empty array.

**Comment by jfirebaugh** [comment]
You should set the zoom level of the transform to get covering tiles for that zoom level. If the current zoom level is less than minzoom, then there aren't any tiles available -- that's just the definition of minzoom.
