### ISSUE TITLE
text-color and queryRenderedFeatures depend on text-field

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#4881]
**mapbox-gl-js version**: 0.38.0

this one is weird.

### Steps to Trigger Behavior

 1. Create geojson of linestrings, with a certain numerical property. Add that geojson as a source
 2. Add a line layer and symbol layer, both with that source. Color them by DDS `line-` and `text-color`, based on that numerical property. Use the same color ramp for both.
 3. Set the symbol's `text-field` to some literal string.

### Expected Behavior
The text and lines should be in the same color. Querying the same features in both layers should give the same result.

### Actual Behavior
Despite having the same source data, they are very different colors, and give back different values when queried. But! If we change the symbol layer's `text-field` to a token of the numeric property, both the color and queried value are correct. It feels as if the renderer is being lazy about evaluating the numeric property for the symbol layer, unless we actually need it to display as text.

Made a fiddle here: https://jsfiddle.net/usx396b3/ . The demo alternates between the token and literal `text-field` every 2 seconds, and you can see the color difference. Click on the text to console log the underlying numeric fields for the symbol and line layers: they will match when the text is a token, but not when it's a literal.

Literal `text-field`:
![screen shot 2017-06-23 at 7 47 48 pm](https://user-images.githubusercontent.com/4551508/27505124-e381b034-584c-11e7-93a4-fcd96082b1d2.png)

Token `text-field`:
![screen shot 2017-06-23 at 7 47 39 pm](https://user-images.githubusercontent.com/4551508/27505125-e382a386-584c-11e7-8e8f-1a04625ecce8.png)

**Comment by peterqliu** [comment]
(oh and I've checked and confirmed that there aren't overlapping lines here 👍 )

**Comment by jfirebaugh** [comment]
This is #3645.
