### ISSUE TITLE
Cannot display 3D buildings on top of satellite map

### ISSUE THREAD

**Issue by jo-chemla** [mapbox/mapbox-gl-js#4889]
**mapbox-gl-js version**: v0.38.0

### Steps to Trigger Behavior

https://jsbin.com/mupiyubuji/edit?html,output and replace with your token

 1. Try to apply satellite `style: 'mapbox://styles/mapbox/satellite-v9',`
 2. And add 3D buildings layer following example https://www.mapbox.com/mapbox-gl-js/example/3d-buildings/
 3. 3D buildings do not appear, and lead to error composite source not recognized. After adding composite source separately, 3D buildings still do not appear, even if you add composite source separately : `if (! map.getSource('composite')) {map.addSource('composite', { type: 'vector', url: 'mapbox://mapbox.mapbox-streets-v5'});}`

### Expected Behavior
3d buildings should be displayed with given style, even on satellite

**Comment by ashleyclough** [comment]
There's no height data in mapbox://mapbox.mapbox-streets-v5, try using mapbox://mapbox.mapbox-streets-v7 as your composite source.

**Comment by lbud** [comment]
Thanks @ashleyclough! That's correct — height data was not yet added in streets-v5.

**Comment by jo-chemla** [comment]
Thanks, don't know why I did not use the last version!
