### ISSUE TITLE
Clustering using symbol layers has a myriad of issues

### ISSUE THREAD

**Issue by cebartling** [mapbox/mapbox-gl-js#4892]
Our solution had been using the Marker API (https://www.mapbox.com/mapbox-gl-js/api/#marker) previously with SVG icons. Recently we have needed to support a large number of points of interest (6,500+). Originally we attempted to manage this large number of points of interest through the Marker API, but that approach soon demonstrated performance issues (browser would hang and become unresponsive). 

We then moved towards an approach of using a GeoJSON source and a couple of filtered symbol layers to control clustering and marker definition. We have however been a bit disappointed in the results: 

1. Clustered symbols don't always render at the default zoom level. Interestingly the clustered pin count would render, but the symbol icon typically did not. Zooming in and out of the map typically forced the symbol icons to render appropriately.
2. Marker icons would "move" on the map tile as you zoomed in to the point of interest. When rendering the marker through the Marker API, the marker icon would stay fixed to its geo-position and would not move as you zoomed in to a point of interest. Marker symbols defined through a layer definition seem to exhibit this symbol movement during zooming.
3. Symbols are being clipped by map tiles. There has been issues with this in the past and I used the `buffer` trick to try and solve them (per https://github.com/mapbox/mapbox-gl-js/issues/2066).
4. Clustered symbols don't always render. This is fine, if the invisible clustered symbol contributes its pin count to another clustered symbol. That doesn't always happen.

Overall, we're seeing enough discrepancies between symbols defined in source and layers and markers defined through the Marker API to wonder what is the right approach going forward.

**mapbox-gl-js version**: 0.37.0

**Comment by julieemunro** [comment]
Hi @cebartling - thanks for providing all this context! Might you be able to share a sample of code so our team can reproduce the issue or a gif of what is happening? cc: @lizziegooding

**Comment by cebartling** [comment]
@julieemunro, @lizziegooding: Unfortunately the code that demonstrates these issues are in a private repository and are part of a commercial product. We are conversing about alternatives that we can put together. I will update this issue with our direction.

**Comment by cebartling** [comment]
This screenshot demonstrates symbols being clipped by map tiles. The symbol is a PNG image with the pin count rendered within it. We have also seen this phenomenon with unclustered markers.

![sentera__agvault](https://user-images.githubusercontent.com/33961/27604025-b583e44c-5b3d-11e7-98a3-7814e7c77e67.png)

**Comment by cebartling** [comment]
@julieemunro, @lizziegooding: A Flash movie demonstrating clustered symbols don't always render at a zoom level. Unarchive to view.

[2017-06-27_1347.swf.zip](https://github.com/mapbox/mapbox-gl-js/files/1106430/2017-06-27_1347.swf.zip)

**Comment by cebartling** [comment]
@julieemunro, @lizziegooding: This screencast demonstrates where the clustered marker pin count is rendered, but the symbol is not at certain zoom levels. The issue manifests itself towards the end of the short screencast. You can faintly see the pin count text when the mouse cursor circles around it to highlight the rendering issue.

https://www.screencast.com/t/CO3DLNWF

**Comment by cebartling** [comment]
@julieemunro, @lizziegooding: This screencast demonstrates unclustered symbols _moving_ across the map as the zoom level changes. These unclustered symbols have distinct geo-positions and should be _stuck_ to those geo-positions. It's as if the unclustered symbols are participating in the floating position of the clustering solution (supercluster). Contrast this to how markers behave using the Marker API in Mapbox GL JS.

[asset pins moving.mp4.zip](https://github.com/mapbox/mapbox-gl-js/files/1106533/asset.pins.moving.mp4.zip)

**Comment by mourner** [comment]
Thanks for the report! Can you please set up a minimal live [JSFiddle](http://jsfiddle.net/) test case that reproduces the issue (or multiple ones, each for a single isolated issue)? This will make it much easier for us to identify and fix everything.

**Comment by cebartling** [comment]
@mourner I will start putting something together yet today. I should have something to show in a couple of hours.

**Comment by cebartling** [comment]
@mourner OK, it took me a couple more hours than I originally thought. ;-) This first public fiddle demonstrates the missing cluster symbols at the default zoom level and the clipping of the cluster symbol at tile edge as you zoom into through the large cluster in southern Canada. 

https://jsfiddle.net/cebartling_sentera/f7067o2x/

You will need to set your access token at the top of the JavaScript section; all else should be good to go. 

Note that I have the GeoJSON source `buffer` attribute set to `512`. I was trying to use that to control the map tile clipping and when I set it that high, the symbol icons disappeared at the default zoom level. I'll work on demonstrating some of the other issues. The code in this fiddle is very similar to what we are using in our product, sans the sourcing of images and canned GeoJSON data from Dropbox.

**Comment by cebartling** [comment]
@mourner I think we have solved one of our issues due to loading symbol images. The load of each image is done asynchronously and our setting of the source and layers is not aware of that. I have updated the JSFiddle for this discovery.

**Comment by julieemunro** [comment]
@mourner can you give this a look on Monday for @cebartling?

**Comment by mourner** [comment]
@julieemunro not today — a lot on my plate currently, but I'll get to it this week.

**Comment by peterqliu** [comment]
>I think we have solved one of our issues due to loading symbol images

@cebartling awesome. to clarify, did this solve the missing cluster symbols, or the symbol clipping? At first glance, I see neither of these bugs in the jsfiddle.

**Comment by cebartling** [comment]
@peterqliu Solves the issue of missing cluster symbols. The symbol clipping by map tiles still exists and is demonstrable in the JSFiddle example.

**Comment by peterqliu** [comment]
>The symbol clipping by map tiles still exists and is demonstrable in the JSFiddle example.

@cebartling I suggest using smaller circles, to reduce the chance that they exceed the size of each tile buffer.

On a side note, I also suggest using a separate [circle layer](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-circle) instead of `icon-image`. [Note how they stay sharp at all zoom levels](https://jsfiddle.net/f7067o2x/72/).

**Comment by julieemunro** [comment]
Hi @cebartling - hope you had a nice 4th of July! Was this helpful, or are you still experiencing the symbol clipping?

**Comment by cebartling** [comment]
@julieemunro and @peterqliu: I just reviewed a PR in our codebase to migrate away from `icon-image` symbols and instead use `circle` layers for clustered markers instead. This will avoid quality issues with raster-based icons and zooming that @peterqliu. Also hopefully that the clipping issues that we have been having with the `icon-image` symbols will disappear going with the `circle` layer approach.
