### ISSUE TITLE
Add bounds parameter to flyTo()

### ISSUE THREAD

**Issue by gagecarto** [mapbox/mapbox-gl-js#4894]
## Motivation
When using flyTo() it would be useful to be able to include bounds rather than just center and zoom.

There are many instances when exact map bounds are important, especially when the bearing and pitch is also being adjusted.

### Mock-Up
```
map.flyTo({
    bounds:[
        [-120.85,28.25],
        [-113.06,36.38]
    ],
    pitch:35,
    bearing:-180
  })
```

**Comment by mollymerp** [comment]
Hi @gagecarto, thanks for using Mapbox. You can use [`Map#fitBounds`](https://www.mapbox.com/mapbox-gl-js/api/#map#fitbounds) for this. Unfortunately, `fitBounds` doesn't support `pitch` and `bearing` options (that issue is tracked at #2112), but you can apply those parameters with other camera operations if you need them.

**Comment by gagecarto** [comment]
Thanks @mollymerp - I am looking to add bounds to a flyTo() event so that the animation is seamless with pitch, bearing and bounds.

**Comment by mollymerp** [comment]
you can pass `pitch`, `bearing`, and `linear: false` (this is the default) as options and `fitBounds` will behave like `flyTo`. The only thing is the `pitch` and `bearing` arguments might make it so your bounds are not exactly fit.

**Comment by gagecarto** [comment]
looks like pitch works in fitBounds but not bearing. trying like below

```
var initBounds=[
  [-134.88,31.16],
  [-91.87,49.01]
]

map.fitBounds(initBounds,{
  bounds:initBounds,
  bearing:180,
  pitch:40
})

```

**Comment by mollymerp** [comment]
Oh yes you're right. We overwrite `options.bearing=0` in the `fitBounds` function 😞

**Comment by gagecarto** [comment]
Oh heck.. Any way to overwrite that options.bearing=0 when calling fitBounds()

**Comment by andrewharvey** [comment]
@gagecarto I wonder if you could possible use https://github.com/mapbox/geo-viewport to get the center, zoom from your bounds and then use `flyTo`?

**Comment by peppahjackk** [comment]
@andrewharvey That was looking promising until the `.viewport` method there is returning [incorrect zoom levels](https://github.com/mapbox/geo-viewport/issues/30)

**Comment by gagecarto** [comment]
@newguy123-creator - This has not yet changed.. I use the geo-viewport functions below to deal with this now. 

https://github.com/mapbox/geo-viewport
