### ISSUE TITLE
HTTP Referrer not passed to maptile server

### ISSUE THREAD

**Issue by sergyv** [mapbox/mapbox-gl-js#4899]
Hello!
we are implementing a token-based authentication and part of it makes use of HTTP Referrer field to check from which website the visitors are coming to download tiles. When receiving requests for pbf on our tile server from mapbox gl we dont get a referrer field. Is there a way to get that field forcefully filled?

Thanks!

**Comment by jfirebaugh** [comment]
Unfortunately, no. The browser controls what gets sent in the referrer header, and client-side JavaScript cannot override what the browser chooses.

**Comment by PaulChipault** [comment]
Hey,
It's a bit surprising, our others front-end javascript components do add the proper referrer header when sending XMLHttpRequests, as required by the referrer-policy header of our server. Even when mapbox-gl loads the map style, it use the proper header, only the tile-loader won't use it when sending request. Any idea ?

**Comment by pirxpilot** [comment]
Tile request (differently from style request) originate from web workers. `mapbox-gl-js` web workers are created from blobs. Most browsers will send empty `Referer` header in such cases, some versions of Edge send `blob` as a referrer.

**Comment by exotfboy** [comment]
Now mapbox support [tokens restriction for url](https://docs.mapbox.com/help/how-mapbox-works/access-tokens/#adding-url-restrictions-to-access-tokens), seems like that the referer can be sent to server.

Anything changed?
