### ISSUE TITLE
canvas.style.cursor does not update to 'grab' or 'grabbing' after being set to 'default'

### ISSUE THREAD

**Issue by wittjosiah** [mapbox/mapbox-gl-js#4901]
**mapbox-gl-js version**: v0.38.0

### Steps to Trigger Behavior

I setup a slightly modified version of the [drag a point example](https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/) which demonstrates this behaviour here: http://jsbin.com/lazisolesi/1/edit?html,output. This works as expected for me in Firefox 54 but does not work as expected in Chrome 58.
 1. Open Chrome
 2. Move cursor over point
 3. Click and drag point

### Expected Behavior
1. Move cursor over point
2. cursor changes to `grab` hand
3. Click and drag point
4. cursor changes to `grabbing` hand

### Actual Behavior
1. Move cursor over point
2. cursor does not change
3. Click and drag point
4. cursor does not change

Based on the example I setup above if you click not on the point you get the `move` cursor, which works. The `grab` and `grabbing` cursors do not seem to update.

**Comment by jfirebaugh** [comment]
Chrome and other webkit-based browsers require `-webkit-grab`/`-webkit-grabbing`. See the compatibility table here: https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by wittjosiah** [comment]
Thanks for the quick response @jfirebaugh! That does indeed solve my issue 😄
