### ISSUE TITLE
setStyle should use setData in diff when it can

### ISSUE THREAD

**Issue by brandonbloom** [mapbox/mapbox-gl-js#4914]
I'm making use of the new-ish "smart" `setStyle` in a React application. Modulo some small issues (see #4912) , it works quite well!

One thing I noticed was that geojson layers are compared in a way that includes their data property. If the data changes, a `removeSource`/`addSource` pair is executed, which results in reloading data and a visible flicker. A better thing to do would be to emit a `setData` operation to ensure smooth animation.

**Comment by anandthakker** [comment]
👍 

related (but not the same): https://github.com/mapbox/mapbox-gl-js/issues/3692

**Comment by anandthakker** [comment]
Done in #5332

**Comment by brandonbloom** [comment]
Thanks!
