### ISSUE TITLE
Buggy ring classification on GeoJSON multipolygons

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#4922]
**mapbox-gl-js version**: 0.38

When displaying complex multipolygons with holes, there seems to be a bug happening somewhere around the ring classification routine that causes severe striping artifacts when triangulating:

![image](https://user-images.githubusercontent.com/25395/27743038-60e298b0-5dc3-11e7-8bc2-43b6f027a485.png)

If I simply filter out all small rings (length < 20), the artifacts are gone. I'm not yet sure the root is ring classification, but it intuitively looks like the culprit. Needs to be investigated further. 

@peterqliu if this is indeed a separate bug from earcutting polygons with small self-intersections, perhaps we could fix some of the artifacts seen on the isochrone demo.

**Comment by peterqliu** [comment]
I'm a bit out of my depth here, but the rendering bugs on the isochrones demo aren't stripes, but **failures to fully flex inward, on concave portions of a polygon**. Here's the same thing at two slightly different zooms:

Bad:
<img width="706" alt="screen shot 2017-06-30 at 2 51 56 pm" src="https://user-images.githubusercontent.com/4551508/27751848-efdf4aba-5da3-11e7-9060-5d0e4d0208e8.png">

Good:

<img width="1014" alt="screen shot 2017-06-30 at 2 52 02 pm" src="https://user-images.githubusercontent.com/4551508/27751862-fce72f02-5da3-11e7-858c-9771bbb4b331.png">

Approximate location for ^: https://www.mapbox.com/bites/00156/#9.21/52.5851/13.3365

**Comment by mourner** [comment]
I no longer have a test case from the original report, so closing in favor of tracking issues in #7023.
