### ISSUE TITLE
Having the browser zoom level at something other than 100% causes 'icon-image' icons to not display

### ISSUE THREAD

**Issue by subwai** [mapbox/mapbox-gl-js#4928]
**mapbox-gl-js version**: 0.38.0

### Steps to Trigger Behavior
Everything tested on macOS Sierra 10.12.5

REPRODUCIBLE: Chrome Version 59.0.3071.115 (Official Build) (64-bit)
REPRODUCIBLE: Firefox 54.0.1 (64-bit)
For some reason this is not an issue in Safari: Version 10.1.1 (12603.2.4)

 1. Go to https://www.mapbox.com/mapbox-gl-js/example/add-image-generated/ or https://www.mapbox.com/mapbox-gl-js/example/add-image/
 2. Set browser zoom level to 110% (or 90%), by pressing "Cmd +"
 3. Reload the page

### Expected Behavior
- The icon you try to load in these examples should display

### Actual Behavior
- The icon is not displaying at all (however the map base is still there)

The bug only seems to be a problem for the layer property "icon-image".

**Comment by mollymerp** [comment]
Hi @subwai, thanks for the detailed report. I was able to reproduce this bug on my macbook pro in Chrome. We will investigate 🕵️‍♀️
