### ISSUE TITLE
Draw a route with a large number of data points, and the animation blinks

### ISSUE THREAD

**Issue by JunYanchan** [mapbox/mapbox-gl-js#4930]
mapbox-gl-js version:v-0.38

1.I draw an animated route, a route or a marker flashes.
2.I set the animation through resquestAnimationFrame, each time loop 6 points and then push to an array and then set sourceData.

![image](http://joyrun-activity.b0.upaiyun.com/h5_demo/ani_line.gif)

![image](http://joyrun-activity.b0.upaiyun.com/h5_demo/code_demo.png)

Expected Behavior:
I hope that the flashing situation in the graph does not appear, hoping to draw the route and the marker to synchronize, so that the marker stays at the last point of the route array

**Comment by kristfal** [comment]
As a workaround: Have you tried to put the point and linestring in a single feature collection and add it as a single source? You can then use style filters to render each feature type in the source differently.

**Comment by JunYanchan** [comment]
@kristfal Thanks for your reply, I try to combine point and lineString in a source, but I do not know how to render the last point of lineString to the point attribute

**Comment by mourner** [comment]
@JunYanchan you would need to create a `FeatureCollection` with two features — one with `Point` geometry and the other with `LineString` geometry. Then they would be a part of the same source and so guaranteed to be in sync. You would then create two different layers two style the features differently based on type.

The issue of markers out of sync with the map is tracked elsewhere — #2257

**Comment by JunYanchan** [comment]
@mourner Thank you very much for your help, I have solved the problem of not being synchronized, but the occasional flashing pattern is still present.

**Comment by JunYanchan** [comment]
@mourner After testing, I found that there seems to be a conflict between the route rendering and the map background? Because I loaded the online map tiles, there was no route to render the flicker problem.

**Comment by anjinlu** [comment]
Hi Jun Yan,

How did you resolve the issue?

Thanks.
