### ISSUE TITLE
can not  render out   symbol layer's icon image

### ISSUE THREAD

**Issue by tianbaolin** [mapbox/mapbox-gl-js#4935]
hello:
now I came across a problem,when I change a style, the  symbol layer cann not render out it's icon image.
the icon image area show a black  rectangle,but sometimes it render correct. I use the  v0.37.
![75a6b5c78d92587565b5203a1047cc0](https://user-images.githubusercontent.com/15847558/27864012-614837b0-61bf-11e7-9624-3b4e0f38eb10.jpg)
![f6762717c53d66ed64c13cf55a69fb8](https://user-images.githubusercontent.com/15847558/27864042-876fd7b8-61bf-11e7-9504-536e07783893.jpg)

**Comment by jfirebaugh** [comment]
Thanks for the report! This will be fixed by #4876. Let's track it in that issue.
