### ISSUE TITLE
Icon and text symbols disappearing on a specific text/icon-size

### ISSUE THREAD

**Issue by edpop** [mapbox/mapbox-gl-js#4942]
Hello.
There is a symbol layer unexpected disappearing on a specific text/icon-size zoom function. You may see it also in Mapbox Studio.

**mapbox-gl-js version**: v0.38.0

### Steps to Trigger Behavior

 1. Go to https://jsbin.com/nacagabewe/1/edit?html,output
 2. Look at 17.9 zoom
 3. Look at 18.0 zoom
 4. Look at 18.1 zoom

### Expected Behavior
The layer should be displayed on 18.0 zoom

### Actual Behavior
The layer is not displayed on 18.0 zoom

**Comment by jfirebaugh** [comment]
Thanks for the report and the example. Looks like this stopped working sometime between v0.34.0 and v0.35.0. #4455 looks like a likely candidate.

**Comment by gilazr** [comment]
As a temporary workaround, we added 0.1 to the stops zoom levels. Hope this helps
