### ISSUE TITLE
fix symbol-features-in/tilted-outside query test

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#4945]
This should be fixed with the switch to global, viewport-based label placement.

<img width="1267" alt="screen shot 2017-07-06 at 11 13 14 am" src="https://user-images.githubusercontent.com/1421652/27918207-38d5bb0e-623c-11e7-8ac2-75f7fa249894.png">

**Comment by ChrisLoer** [comment]
Fixed in #5150.
