### ISSUE TITLE
Windows 10 & Firefox 54: 'invalid argument'

### ISSUE THREAD

**Issue by brambow** [mapbox/mapbox-gl-js#4960]
**mapbox-gl-js version**: 0.38

### Steps to Trigger Behavior

 1. Use Windows 10 and Firefox
 2. Try to load site that works on Chrome and all browsers (including Firefox) on MacOS

### Expected Behavior
I expect the map page to load.  It works in Chrome in Windows 10 and on Chrome, Firefox and Safari in MacOS

### Actual Behavior
I get a console error TypeError: invalid argument

![image](https://user-images.githubusercontent.com/6227786/27988582-f30fc05c-63f2-11e7-8b36-7f4b3a5b6bfd.png)

**Comment by brambow** [comment]
Update: seems to go away if I revert to mapboxGL version 0.37

**Comment by lauramosher** [comment]
I have a similar issue with Sprite trying to load the icons. It occurs on both Windows and MacOS for Chrome, Firefox, and IE.

![image](https://user-images.githubusercontent.com/2660801/28022781-1d4a6a58-655a-11e7-93d2-a9d22aa8560f.png)

Reverting to 0.37 does seem to solve the issue; but this is less than ideal.

**Comment by mourner** [comment]
@brambow @lauramosher thanks a lot for the report, looks like a regression! Does it happen on any maps you open, or only given some specific conditions? If so, could you set up a minimal test case?

Also, if you're willing to spend some time to help us fix this — the best way would be to do a `git bisect` between 0.37 and 0.38 to find the exact commit that introduced the issue.

**Comment by lauramosher** [comment]
`git bisect` output says that 5afdc762da7c272cfbcde371089d6bdbbe6b6d82 is the first bad commit. I've included the output of my bisect for your perusal.

```
➜  mapbox-gl git:(master) git bisect start
➜  mapbox-gl git:(master) git bisect good v0.37.0
➜  mapbox-gl git:(master) git bisect bad v0.38.0
Bisecting: 33 revisions left to test after this (roughly 5 steps)
[df738b931d987004c8116a64eac5913a7359f9a3] Recalculate collision box shape at placement time based on distance from camera to the center of the tile. Recalculating the shape allows the collision approximations in the shaders to remain more accurate.
➜  mapbox-gl git:(df738b9) git bisect bad
Bisecting: 16 revisions left to test after this (roughly 4 steps)
[4a85df68533ae8fbf644f9f60df77eea344cd1c1] Enable gl-native test for Arabic letter-spacing (#9057)
➜  mapbox-gl git:(4a85df6) git bisect good
Bisecting: 8 revisions left to test after this (roughly 3 steps)
[6daed99e215f6d4180eb7b07b05fd7174c58e859] Add links to run individual benchmarks
➜  mapbox-gl git:(6daed99) git bisect bad
Bisecting: 3 revisions left to test after this (roughly 2 steps)
[feb84c82c28da8678d8c11c1536b206d699e8c61] Add tests for 1.5x image
➜  mapbox-gl git:(feb84c8) git bisect bad
Bisecting: 1 revision left to test after this (roughly 1 step)
[c728137fdc2e9ee046dd7a7a18f599caeecc0759] Remove destructuring assignment, per CONTRIBUTING.md
➜  mapbox-gl git:(c728137) git bisect good
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[5afdc762da7c272cfbcde371089d6bdbbe6b6d82] Simplify and fix sprite atlas coordinate calculations
➜  mapbox-gl git:(5afdc76) git bisect bad
5afdc762da7c272cfbcde371089d6bdbbe6b6d82 is the first bad commit
commit 5afdc762da7c272cfbcde371089d6bdbbe6b6d82
Author: John Firebaugh <john.firebaugh@gmail.com>
Date:   Fri May 19 16:42:47 2017 -0700

    Simplify and fix sprite atlas coordinate calculations

    * Always return image metrics exclusive of padding
    * Work with integer coordinates whenever possible
    * Eliminate redundant SpriteAtlasElement members
    * Fix asymmetric re-padding in getIconQuad when pixelRatio != 1
    * Add explanatory comments

:040000 040000 aa0bb2abebced9b8c3e4f1103936f7907fda09a5 449e80af72a18c5a5d423b0d530384fcb9aff7e9 M      src
:040000 040000 3c1f0ba27cd50bf017be38a683fc9b7e061500d7 61c349727bf5d5701f44c37e855929e3a15046b6 M      test
➜  mapbox-gl git:(5afdc76)
```

**Comment by lauramosher** [comment]
It appears to happen on any map I have open with browser zoomed either direction from native 100%.
