### ISSUE TITLE
How to change text color on hover

### ISSUE THREAD

**Issue by phiphou** [mapbox/mapbox-gl-js#4961]
Hi,

I'm trying to change the color of the text of a marker on mouse over, but with no luck. map.getCanvas().style.cursor = 'pointer' works well for cursor changing, but is there a way to change text color ? 

I tried with map.setFilter("pois_hover", ["==", "name", features[0].properties.name]); but the text below the original text is "buggy". See [http://osm.phiphou.org/vector-interactive#20/48.76276/2.67216 ](http://osm.phiphou.org/vector-interactive#20/48.76276/2.67216 )

I want to keep the underneath layer in order to have a good text colision behaviour. 

Sorry for my bad english.

Thanks

**Comment by andrewharvey** [comment]
https://gis.stackexchange.com/questions/tagged/mapbox-gl-js is a better place to ask for help on how do I do this type questions, as next time if someone has a similar query they can find the answer there.

Is this what you wanted? https://jsbin.com/nemipiyoco/edit?html,output

It uses the setData approach to hovers, as it is faster at least until #2874 is resolved.

**Comment by phiphou** [comment]
I always forget to ask on SE, but will do so next time. You perfectly answer my question, thanks a lot ;)
