### ISSUE TITLE
Polygon overlaps itself doesn't show normally

### ISSUE THREAD

**Issue by huangyingjie** [mapbox/mapbox-gl-js#4962]
## Problem and code
* Here is my code:
````js
          map.addLayer({
              'id': 'maine',
              'type': 'fill',
              'source': {
                  'type': 'geojson',
                  'data': {
                      'type': 'Feature',
                      'geometry': {
                          'type': 'Polygon',
                          'coordinates': [[[116.37688636779785,39.93091599989282],
                            [116.41559600830078,39.89999167197871],
                            [116.37027740478516,39.89771993624399],
                            [116.41353607177734,39.9317880642358],
                            [116.37688636779785,39.93091599989282]
                          ]]
                      }
                  }
              },
              'layout': {},
              'paint': {
                  'fill-color': '#088',
                  'fill-opacity': 0.8
              }
          });
````
* And This is the screenshot
![image](https://user-images.githubusercontent.com/1618397/28002607-516faf46-6569-11e7-8faf-b8042a40e56d.png)
When Change the zoom:
![image](https://user-images.githubusercontent.com/1618397/28002694-fcbb3fc8-6569-11e7-83d4-3b89ee87768c.png)

## What's my expectation
![image](https://user-images.githubusercontent.com/1618397/28002773-a761f156-656a-11e7-8c88-53da28b814cd.png)

## Why not forbid overlapping?
I shall do this later, but there was too much data overlaps; and customers ask to show as my description before.

**Comment by ddimaria** [comment]
Turf union? https://github.com/Turfjs/turf/tree/master/packages/turf-union

**Comment by huangyingjie** [comment]
@ddimaria it use two or more polyons, but here it is just one polygon..

**Comment by mourner** [comment]
This is a technical limitation — we currently have no way to properly triangulate invalid self-intersecting polygons.

**Comment by huangyingjie** [comment]
Hello @mourner , could you please describe the `technical limitation`  in detail?  article、issue etc.

**Comment by mourner** [comment]
@huangyingjie there is no fast, stable algorithm for triangulating non-simple (self-intersecting) polygons. For triangulation, we use https://github.com/mapbox/earcut, which is very fast, but assumes that polygons do not self-intersect. 

We clean up all self-intersections in our vector tiles, but don't do so yet in JavaScript. Detecting and resolving self-intersections is a very hard problem, which I started exploring in https://github.com/mapbox/polysnap project, but haven't finished yet.
