### ISSUE TITLE
areTilesLoaded() doesn't return true in some situations

### ISSUE THREAD

**Issue by twelch** [mapbox/mapbox-gl-js#4975]
v0.38.0

### Steps to Trigger Behavior
https://jsfiddle.net/ujxun8kp/7/
 1. Go the example, wait for it to fully load
 2. shift-drag a small box and zoom in to a place where there are points.

![tile-load-event-bug](https://user-images.githubusercontent.com/81816/28109194-0b198536-66a3-11e7-8e68-1ca9363767a5.gif)

### Expected Behavior
The map zooms in, 'data' events fire as requested vector tiles come in.  Eventually map.areTilesLoaded() will return true when called within a 'data' event handler, when the last tile arrives.  Now we can ensure we are querying the complete set of map features in view.

### Actual Behavior
At times this works, but in certain situations (such as when using a box zoom after the initial map load in the fiddle), areTilesLoaded() consistently never returns true within the 'data' event handler when the last tile arrives.  In project code, I've seen this behavior on the initial map load as well but I've only been able to reproduce in a simple example as described.

What's the use case?
Store locator, with lots of stores, published as vector tiles.  A list of locations on the page is populated using features queried from the current map view.  List must be populated after the map loads *and* all tiles have arrived.  The list must be kept up to date with the map view (subsequent pans, zooms, resizes).  Features should not be queried from the map again until all tiles arrive.

Workaround
If I check map.areTilesLoaded() by polling with an interval, it will return true after the last tile 'data' event.  But, I'd rather use a map event to act on that state change as soon as possible.

I'm open to other ideas.  I discussed a similar issue with @mollymerp earlier in the year using older API methods to check map state.

**Comment by mollymerp** [comment]
@twelch thanks for the detailed report! I can reproduce and it does seem to be undesired behavior so I will try and take a look later this week.
