### ISSUE TITLE
Using local vector tiles map

### ISSUE THREAD

**Issue by zhuchen2** [mapbox/mapbox-gl-js#4976]
Hi,

We are developing an offline map using vector tiles. 

```
VectorSource museums = new VectorSource("museums_source", "mapbox://zhuchen2.cahlf5q4");
map.addSource(museums);
```

I tried to uses the code above to fetch the map stored in mapbox studio, it works. However, we want to support offline map, which means that the map should be load from local storage. I googled the problem, but I can't find any examples to show how to load local vector tiles. I am even not sure if it is supported. I've convertd the geojson file to .mbtiles. Can I get some help?

Thanks

**Comment by mourner** [comment]
Thank you for the issue! However, this repository only tracks issues with the Mapbox GL JS library and its style specification, and this seems more like an general front-end development question. 

I'd personally suggest looking into HTML5 App Manifest or Service Workers: 
- https://www.html5rocks.com/en/tutorials/appcache/beginner/
- https://developers.google.com/web/fundamentals/getting-started/codelabs/offline/

**Comment by mourner** [comment]
Looks like there's a proposal that should make things like this easier: #4917

**Comment by AliAbed93** [comment]
do you find the answer? 
 i want load a raster from local storage in unity and i searched the universe for this and nothing.
@mourner please give me some clue!!!
