### ISSUE TITLE
Tiles hide annotations at certain zoom levels

### ISSUE THREAD

**Issue by gilazr** [mapbox/mapbox-gl-js#4978]
mapbox-gl-js version: 0.38.0

### Steps to Trigger Behavior

Sadly, I couldn't find a way to constantly reproduce it, but this happens once every 15-20 attempts.
Happens on both Chrome and Safari on iOS, Android, macOS, Windows

 1. Site loads onto map a layer of annotations (with a custom style)
 2. User changes zoom level
 3. At a certain zoom level, right when a tile changes, it hides some / all of the annotations (see attached images)

### Expected Behavior
Zooming should not affect display of annotations

### Actual Behavior
It does

<img width="617" alt="screen shot 2017-07-12 at 20 30 00" src="https://user-images.githubusercontent.com/821806/28161778-8273f1e0-67cd-11e7-9e15-5d3527018022.png">
<img width="616" alt="screen shot 2017-07-12 at 20 29 47" src="https://user-images.githubusercontent.com/821806/28161779-827808f2-67cd-11e7-9f02-dfe88f7d0e35.png">
<img width="616" alt="screen shot 2017-07-12 at 20 29 47" src="https://user-images.githubusercontent.com/821806/28161795-92aaa54a-67cd-11e7-97a2-0b84f976a382.png">

**Comment by gilazr** [comment]
So, it seems that in some cases the source was not fully loaded before we called setData. Adding this seems to solve the problem. As seen in [this line](https://github.com/mapbox/mapbox-gl-js/blob/master/test/unit/ui/map.test.js#L280) of the tests

**Comment by mollymerp** [comment]
@gilazr this looks like an issue with your data/tileset. Can you please set up a minimal JSBin that demonstrates the problem?

**Comment by gilazr** [comment]
@mollymerp Hi, the code was hard to move to JSBin because there was too much going on. 
We eventually solved it by gradually loading everything in this order:

map
source
images
markers

Thank you for your response :)
