### ISSUE TITLE
Text label cut at tile border

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#4994]
**mapbox-gl-js version**: 
v0.38.0

### Steps to Trigger Behavior

Open https://jsfiddle.net/6ns3zrny/ and have a look at the label "RIO BLANCO".

(tested with Chrome/Chromium/Firefox on Windows/Linux)

### Expected Behavior

Label is not cut

### Actual Behavior

Label is cut

![image](https://user-images.githubusercontent.com/20856381/28356227-9ed53ec2-6c67-11e7-935c-c1a722ff4887.png)

The used tileset was created by uploading a shapefile to Mapbox Studio. Creating a tileset out of the same shapefile with Mapbox Studio Classic and buffer 64, the label is not cut. So it seems like it has something to do with the tile buffer. 
However, according to the Mapbox support team:
"Rather than Mapbox Studio Classic, which requires you to set the tile buffer size on upload, with the new Mapbox Studio you can set label buffers dynamically using the text-padding option. You can configure this option in Mapbox Studio by navigating to the Style > Placement tab of your symbol layer."

We've increased the text-padding, but unfortunately it has no effect. The label is still cut at the tile boundary. According to your support team this is unexpected behaviour.

**Comment by mourner** [comment]
What's the style of the label layer? This may be a duplicate of #2706

**Comment by pathmapper** [comment]
@mourner thanks, yes it's duplicate, the style has `"text-allow-overlap": true` .
So the current options are not to use `"text-allow-overlap": true` or use tilesets created with Mapbox Studio Classic or tippecanoe and set a sufficient tile buffer, right?
As far as I can see, there a no options to set the tile buffer when creating a tileset with the current Mapbox Studio.
