### ISSUE TITLE
Back-publish v0.26.1 and remove `npm-shrinkwrap.json`

### ISSUE THREAD

**Issue by abmai** [mapbox/mapbox-gl-js#5001]
**mapbox-gl-js version**: v0.26.0

### Steps to Trigger Behavior

 1. `npm install` any project that still depend on `v0.26.0`
 2. get `npm ERR! fetch failed https://registry.npmjs.org/gulp-sourcemaps/-/gulp-sourcemaps-1.7.0.tgz`
 3.

### Expected Behavior
Installation should complete smoothly

### Actual Behavior
Error'ed out on unfound `gulp-sourcemaps` `1.7.0` - which does not exist in NPM

===================

Hey all,

We have a version of our project that still depends on mapbox `0.26.0`, and cannot upgrade that particular version path to mapbox `>= 0.27.0` because of the dependency on later versions of Node.

Things have been working fine for the past few months but recently we've been getting errors about `gulp-sourcemaps` `1.7.0` not found when installing. It's listed in the `npm-shrinkwrap.json` for this version but does not exist in npm. Is it possible to publish a `0.26.1` that has this specific dependency removed, or the entire `npm-shrinkwrap` for that matter? I noticed that `0.27.0` doesn't have a shrinkwrap file.

**Comment by abmai** [comment]
Looks like we can pin to this commit: https://github.com/mapbox/mapbox-gl-js/commit/3470d0bf0b81440f0d04a9d9e825ee43e65f7638

I think it would still be useful to publish a `0.26.1` that removes `npm-shrinkwrap` or `devDependencies` from that shrinkwrap file, but I'll leave that up to the maintainers to decide :).

**Comment by jfirebaugh** [comment]
@abmai Yes, I recommend you pin to the commit you need in your project's package.json. We unfortunately don't have the resources to support old versions of Mapbox GL JS.
