### ISSUE TITLE
Port raster tile masking

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#5003]
In https://github.com/mapbox/mapbox-gl-native/pull/9468, we're introducing masks for rendering only the parts of raster tiles that aren't covered by other (higher zoom level) tiles on the same layer. This prevents flickering and overlapping tiles when raster tiles are translucent, either because their `raster-opacity` is less than `1`, or the image data itself is translucent.

/cc https://github.com/mapbox/mapbox-gl-js/pull/4701 @mollymerp

**Comment by jfirebaugh** [comment]
Done in #5105.
