### ISSUE TITLE
Code bug in vector_tile_source

### ISSUE THREAD

**Issue by sanjin-saric** [mapbox/mapbox-gl-js#5005]
There is a bug that might lead to worker number 0 not being utilized properly.
```javascript
if (!tile.workerID || tile.state === 'expired') {
   tile.workerID = this.dispatcher.send('loadTile', params, done.bind(this));
} else if (tile.state === 'loading') {
   // schedule tile reloading after it has been loaded
   tile.reloadCallback = callback;
} else {
   this.dispatcher.send('reloadTile', params, done.bind(this), tile.workerID);
}
```
If the worker is assigned index 0, it will never be re-utilized for reloading. I believe the tile will constantly be loaded instead of reloaded if it was being handled by worker 0.
Correct if statement should be `if (tile.workerID !== undefined && tile.workerID !== null ... )`

**Comment by mollymerp** [comment]
Thanks for the report @sanjin-saric – would you like to submit a PR implementing this fix?

**Comment by sanjin-saric** [comment]
@mollymerp done
