### ISSUE TITLE
minzoom property of layer only takes int (decimal just rounds up)

### ISSUE THREAD

**Issue by ralphking** [mapbox/mapbox-gl-js#5006]
### Steps to Trigger Behavior

Create a layer, set min zoom property to 12.5, max zoom to 20, add to the map

### Expected Behavior

The layer disappears when zoom gets below 12.5

### Actual Behavior

The layer disappears at 13 (12.5 has rounded up). This seems to happen for any decimal.

Is this expected?

**Comment by jfirebaugh** [comment]
Duplicate of #2929.
