### ISSUE TITLE
Tileset miss points from Dataset

### ISSUE THREAD

**Issue by bravecow** [mapbox/mapbox-gl-js#5007]
Dataset polygons:
![image](https://user-images.githubusercontent.com/988471/28425974-7933a190-6d7a-11e7-8c44-b2d75974d14d.png)

Styles:
![image](https://user-images.githubusercontent.com/988471/28426089-d0b1be66-6d7a-11e7-8153-dc720c7862df.png)

What does can cause this? Too much features? (~1600 buildings)

**Comment by jfirebaugh** [comment]
Hi @bravecow -- this is most likely related to the Mapbox dataset API and not Mapbox GL itself. Please contact Mapbox support and they can help diagnose. https://www.mapbox.com/contact/support/

**Comment by bravecow** [comment]
Thanks! Will do.
