### ISSUE TITLE
Ability to disable pitch/tilt after map creation

### ISSUE THREAD

**Issue by DanielGibbsNZ** [mapbox/mapbox-gl-js#5012]
I can create a map with pitch/tilt disabled using the `pitchWithRotate` option, but if I later want to disable it there is no (documented) way to do so. Would it be possible to add this feature?

I've found a partial hack to do this, but it only disables pitch via dragging, not via keyboard shortcuts:

```
map.dragRotate._pitchWithRotate = false;
```

**Comment by mollymerp** [comment]
Hi @DanielGibbsNZ – thanks for using Mapbox. We do have an open issue for standardizing our setters/getters and constructor options #4029 

Closing this issue to centralize discussion over there, but feel free to submit a PR for this issue specifically if you'd like!
