### ISSUE TITLE
Jest, Enzyme, Have a site using mapbox-gl-js that is failing in test coverage, pointing to mapbox-gl as culprit. 

### ISSUE THREAD

**Issue by sgoldens** [mapbox/mapbox-gl-js#5026]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1.
 2.
 3.

**Comment by sgoldens** [comment]
Poo. I'm sorry. I think I misunderstood the correct way to reopen an issue I believe is unclear in its resolve and explanation. This may be my misunderstanding. I'm trying to improve test coverage of a portfolio site I'm working very hard on developing. There appears to be issue related to mapbox-gl. (I love this tech. Please don't hate me.) I'm trying to test-cover a tiny prototype game i'm working on, available here: http://sashagoldenson.com/#geo-quiz and the help I've found was obtuse and I'm asking for clarity, if easily possible. I'll do whatever heavy lifting I can. Thank you in advance for your time. Best, -Sasha

**Comment by mollymerp** [comment]
@sgoldens thanks for using Mapbox. Unfortunately, we cannot provide support on this issue tracker; it is only for bugs and feature requests. 

Mapbox GL JS requires a browser to run. It appears you're trying to use the `/dist` files in a node testing environment, which is not supported. I suggest you try asking on StackOverflow or the react-mapbox-gl issue tracker.

**Comment by mhinc14** [comment]
@sgoldens Did you manage to find a solution to this in the end. If yes, please are you able to share your solution in order to help anyone stuck with the same issue. :) thanks

**Comment by kuanb** [comment]
Looks like, in tests, one should use something like `mapbox-gl-js-mock` (https://github.com/mapbox/mapbox-gl-js-mock/) in lieu of mapbox-gl.

But, as is illustrated by some PRs with author's who are confused (ex: https://github.com/mapbox/mapbox-gl-js-mock/issues/27); implementation is not as straightforward as it perhaps could be.

**Comment by rlueder** [comment]
For others landing here looking for a solution on how to mock mapbox-gl the solution can be found in Jest documentation: [Mocking Node Modules](https://jestjs.io/docs/en/manual-mocks.html#mocking-node-modules)
