### ISSUE TITLE
Add way of creating Map instance without an enclosing container/DOM element

### ISSUE THREAD

**Issue by lmcd** [mapbox/mapbox-gl-js#5027]
I'm drawing `map._canvas` to a texture in another WebGL context, so don't require the underlying DOM element. I'm just `display:none`'ing it for now, but I think it'd be cleaner if `container` was simply optional.

**Comment by jfirebaugh** [comment]
It would still need some way of obtaining a width and height for the canvas. I think for the use case you describe, you can supply a container that's a detached DOM node.
