### ISSUE TITLE
Add image on map overlay area

### ISSUE THREAD

**Issue by 96sohan96** [mapbox/mapbox-gl-js#5029]
Hello,

I just using [Play map locations as a slideshow Example](https://github.com/mapbox/mapbox-gl-js/blob/master/docs/_posts/examples/3400-01-18-playback-locations.html). I want to add image on (map-overlay) area. Which will change with map like another content on that area. what should I do?

Thank You...

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
