### ISSUE TITLE
New York, US gl scoring

### ISSUE THREAD

**Issue by fordc5** [mapbox/mapbox-gl-js#5043]
Foreword: this is not as much of a bug report as it is a question and possible request for change.

**mapbox-gl-js version**: 0.39.0

### Actual Behavior
 1. The location: 'New York, US' or 'New York, United States' will result in first showing New York city rather than New York state. I believe the score the gl gives to both is the same in this scenario but it defaults to New York City. 

### Expected Behavior
So I question this result. I recognize that google actually does the same thing when you search for New York, United States. However, if someone is searching for New York, US I feel like that is pretty well defined as wanting the state. If a user just types in 'New York' I can understand bringing them to NYC, but unless you have data to show me that more users want NYC rather than NY State when typing in 'New York, United States' I am surprised that state is not scored higher. 

I recognize that this was a fairly brief and cursory report, if you would like more details/information I am happy to talk more about it.

**Comment by jfirebaugh** [comment]
Hi @fordc5, thanks for using Mapbox. This would be an issue for the Mapbox Geocoding service rather than Mapbox GL. You can submit feedback for that [here](https://www.mapbox.com/geocoder-feedback/).
