### ISSUE TITLE
In custom map, glyph doesn't load.

### ISSUE THREAD

**Issue by jhjhjh96** [mapbox/mapbox-gl-js#5048]
I seccess to display map in hosting my TileJSON.
 
But, Font doesn't work.
 
Common mapbox map was loaded glyph data, my map doesn't it.
 
Both map request same glyph URL. 
 
[my_project request url ]
"https://api.mapbox.com/fonts/v1/mapbox/{fontstack}/{range}.pbf?access_token=pk.eyJ1Ijoic3lrNTg0IiwiYSI6ImNpcjYwNnFiZTAwY3VnMm5mMjBuamxrODIifQ.9ed2KXYVZnmRV9Sc39VzdA"
 
[mapbox request url ]
"https://api.mapbox.com/fonts/v1/mapbox/{fontstack}/{range}.pbf?access_token=pk.eyJ1Ijoic3lrNTg0IiwiYSI6ImNpcjYwNnFiZTAwY3VnMm5mMjBuamxrODIifQ.9ed2KXYVZnmRV9Sc39VzdA"

But result wasn't same.. 
 
What was wrong?

[mapbox map]
![mapbox](https://user-images.githubusercontent.com/26427276/28605685-f842e72e-720d-11e7-819f-7c7f89972b5b.PNG)

[my map]
![mymap](https://user-images.githubusercontent.com/26427276/28605687-f87782d6-720d-11e7-8fd1-e59a2dbe27cb.PNG)

**Comment by jfirebaugh** [comment]
Can you provide a minimal, self-contained example that demonstrates the issue?
