### ISSUE TITLE
map.off  (type, listener) don't work

### ISSUE THREAD

**Issue by TriplePenetretion** [mapbox/mapbox-gl-js#5049]
map.off - How it works?

    <input id="b2" type="button" name="button2" value="add marker"/>

       var isActive = false; // switch

    b2.onclick = function () {
        if (isActive == false) {
           map.on('click', onMapClick);
        } else {
            map.off('click', onMapClick);
        }
        console.log(map.listens('click', onMapClick));
        if (isActive == false) {
            isActive = true;
        } else {
            isActive = false;
        }
    }

onMapClick - add marker
 console.log(map.listens('click', onMapClick)) -  Always true => map.off don't work
How it works? Example please

**Comment by TriplePenetretion** [comment]
temporary solution

     map.on('click', function(e) {
        if (isActive == true) {

            var el = document.createElement('div');
            var elChild = document.createElement('div');
            el.appendChild(elChild);
            elChild.className = 'marker';

            jQuery.ajax({
                type: "POST",
                url: "index.php?option=com_ajax&module=customcrayon&format=json",
                data: {
                    type: 'point',
                    coordinates: JSON.stringify(e.lngLat),
                    style: 'marker',
                    content: 'нет',
                    query: 'insert'
                }
            });

            new mapboxgl.Marker(el, {offset: [-5, -30]})
                .setLngLat(e.lngLat)
                .addTo(map)
        }
    });

    var isActive = false;

    b2.onclick = function () {
        if (isActive == false) {
            isActive = true;
        } else {
            isActive = false;
        }
    }

**Comment by jfirebaugh** [comment]
Can you create a JSFiddle that demonstrates the issue you're seeing?

**Comment by Andi-Lo** [comment]
Not sure if it is related to his problem but I experience that `map.off` is not working when using it in conjunction with `.bind()`. 

Example: https://jsfiddle.net/andi_lo/guzskv7n/8/

In a project I am using es6 classes and thus almost always need to use `.bind(this)` to not lose my class reference when assigning an event handler.

**Comment by jfirebaugh** [comment]
@Andi-Lo You need to pass the same function instance to `off` that you pass to `on`, but `.bind(this)` returns a _new_ function instance each time it's called. So instead of `map.off('click', handleMapClick.bind(this))`, you need to retain a reference to the bound function you passed to `on`, and pass that to `off`. (This is not specific to Mapbox GL's event system -- the same is true of `add`/`removeEventListener`, jQuery, etc.)

**Comment by Andi-Lo** [comment]
Awesome thats how it works. Thanks 👍

**Comment by goors** [comment]
I have same issue. .off work only first time and if you activate same event listener again and .off again, .off just get ignored. I did sam thing as @TriplePenetretion  (https://github.com/mapbox/mapbox-gl-js/issues/5049#issuecomment-318012777)

**Comment by tannerjt** [comment]
I think this is a good use case for a [Singleton design pattern](https://www.dofactory.com/javascript/singleton-design-pattern) for your callback function.  This will make sure you're creating and calling the same function every time.

**Comment by Bernoulli-IT** [comment]
@tannerjt Singletons is a design principle applied to classes imho, not in the context of a single method.

**Comment by tannerjt** [comment]
> @tannerjt The singletons design pattern is applied to classes, not to single method(s).

The goal in this case is to always reference the same callback function, meaning the exact object reference in memory.  .off and .on will only work if you are referencing the same exact object reference.  Maybe there is another design pattern to accomplish this?  The singleton design pattern has always worked best for me.  Check to see if the object (string, function) or class already has an instance created, and if so, return the instance.

**Comment by Bernoulli-IT** [comment]
@tannerjt Off courese I understand the purpose of the "same object (method) reference" for correctly (un)subscribe to event handlers. But what I aimed to add to this thread is that this is not called the Singleton Design Pattern.

**Wikipedia**:
[In software engineering, the singleton pattern is a software design pattern that restricts the instantiation of a class to one "single" instance. This is useful when exactly one object is needed to coordinate actions across the system. The term comes from the mathematical concept of a singleton.](https://en.wikipedia.org/wiki/Singleton_pattern)

So it doesn't apply to a method. Is this more clear?
