### ISSUE TITLE
Documentation should indicate if function is sync or async

### ISSUE THREAD

**Issue by sthomp** [mapbox/mapbox-gl-js#5050]
I've gotten into a habit of performing a routine check whenever I update source data:
```
    const onSourceData = (e) => {
      if (e.isSourceLoaded) {
        map.off('sourcedata', onSourceData);
        // Do follow up stuff here
      }
    }
    map.on('sourcedata', onSourceData);
    // update source data here
```

However, I've noticed that not all functions are async. For example, `addSource` is async however `removeSource` is sync.

Would it be possible to indicate in the documentation if a function will performed async?

**Comment by sthomp** [comment]
Hm sorry nevermind.. I updated from mapbox-gl 0.38.0 to 0.39.1 and now removeSource is returning the event (although e.isSourceLoaded is true which seems strange?). So Im guessing its safe to assume all functions that modify source data are async now? If so feel free to close.

**Comment by jfirebaugh** [comment]
Can you clarify what exactly you mean by "sync" and "async"? `addSource` and `removeSource` are both sync with regard to `Map#getSource` -- they modify the style immediately. Depending on the source type and other details of the state of the map and style, there may be effects triggered by adding a source which happen asynchronously (most importantly loading tiles).

**Comment by sthomp** [comment]
Mainly referring to previous issue: https://github.com/mapbox/mapbox-gl-js/issues/5019

'Updates to the map that affect which features are drawn -- e.g., map.setFilter(layerId, [...]), or map.getSource(geojsonSourceId).setData(...) -- occur asynchronously'

**Comment by jfirebaugh** [comment]
Correct, that comment is referring to the end effect of rendering the map with the changes applied -- that part is always asynchronous.
