### ISSUE TITLE
Custom routing direction 

### ISSUE THREAD

**Issue by RevathiZoho** [mapbox/mapbox-gl-js#5053]
How can i use my custom API's for routing direction on vector tiles instead of mapbox API.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
