### ISSUE TITLE
Function.property for iconImage

### ISSUE THREAD

**Issue by uburoiubu** [mapbox/mapbox-gl-js#5054]
Couldn't figure it out. Is it already supported?
```
symbolLayer = new SymbolLayer("event_layer", "event_source");
        symbolLayer.setProperties(
                PropertyFactory.iconImage(Function.property("eventTypeId", Stops.categorical(
                        Stop.stop(1730916298, PropertyFactory.iconImage("event_in")),
                        Stop.stop(-937726786, PropertyFactory.iconImage("event_out"))
                ) ))
        );
```

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
