### ISSUE TITLE
map.addLayer() mutates the input layer's source

### ISSUE THREAD

**Issue by Jakobud** [mapbox/mapbox-gl-js#5057]
I've got a really weird bug that I have finally been able to reproduce. I attempt to create a polyline from some GeoJSON data structure. The GeoJSON structure has a `source` property that contains the longitude and latitude coordinates.

When I examine the GeoJSON object in the JavaScript console in the Chrome Dev Tools, initially it shows the `source` property as an `Object` as it should. But when you expand the GeoJSON object it then shows the `source` property value as a `string` and it changes it to the same value as the `id` of the GeoJSON object. So obviously since the `source` property is a string it no longer works as a valid GeoJSON object for my polyline.

Really really weird. I cannot figure this out. Check out the following screenshot:

![screen shot 2017-07-27 at 2 09 51 pm](https://user-images.githubusercontent.com/87356/28690799-c4703f8a-72d7-11e7-8927-5c2a1409dadd.png)

See? It shows `source` as an `Object`. But when you expand it, its a `string` AND it matches the `id` of the object every time.

If you look at the following JSFiddle:

https://jsfiddle.net/mwfrcroj/

You can see that the GeoJSON data structure is setup properly. Clearly, the `source` property is not a string. It has the correct object structure. But something weird happens when the layer is added to the map. The source is changed to a string as you can see in the console.

ADDITIONALLY, if you comment out the `map.addLayer()` command:

```
// map.addLayer(solidRoute)
```

And run the fiddle again, you will see that the `source` does NOT change to a string. So the center of this problem is originating when the layer is added to the map via MapBox.

**mapbox-gl-js version**: 0.39.1

### Steps to Trigger Behavior

 1. Use this fiddle: https://jsfiddle.net/mwfrcroj/
 2. Run the fiddle
 3. Examine the JavaScript console
 4. Note that the `source` property of the GeoJSON object gets changed from it's object to a string

### Expected Behavior

The `source` property should continue to be an Object and should not change.

### Actual Behavior

The `source` property gets changed to a string with the same value as the `id` of the GeoJSON object. Therefore the GeoJSON object will no longer work since there are no longer coordinates.

**Comment by peterqliu** [comment]
Turns out that adding layer-specific sources [also mutates the input layer object's `source` parameter](https://github.com/mapbox/mapbox-gl-js/blob/ca9a32bbde138da94479501b55aedcd170b71d2f/src/style/style.js#L439-L442). Under the hood, layer-specific sources invoke the traditional `map.addSource()` workflow.

@Jakobud I suggest keeping your geojson object in a separate variable and just pass it in by reference.

**Comment by Jakobud** [comment]
Interesting. Can you elaborate on this? Because I'm simply following the documentation example on how to draw a polyline: https://www.mapbox.com/mapbox-gl-js/example/geojson-line/

Are you saying this isn't the proper way to do it?

**Comment by peterqliu** [comment]
@Jakobud nah, you're doing it right. It's just that if you want to keep your geojson around for later use, you'll want to store it separately from the layer object, because `.addLayer()` will mutate the layer object you feed it.

**Comment by jfirebaugh** [comment]
This is a bug -- `Map#addLayer` shouldn't ever mutate the input.

**Comment by Jakobud** [comment]
I'm not trying to keep it around for later. The MapBox simply isn't adding my polyline layer to the map. I don't get any JS errors about invalid GeoJSON structure either. That is why I was trying to `console.log` my input, just to make sure it was correct.

Is there anything about my syntax that is incorrect? How come the documentation example works fine but mine brings up this bug? I'm not immediately seeing the difference.

**Comment by peterqliu** [comment]
@Jakobud ah, [geojson](http://geojson.org/) uses longitude-latitude order. Your linestring is currently near a pole:

<img width="228" alt="screen shot 2017-07-27 at 4 02 15 pm" src="https://user-images.githubusercontent.com/4551508/28692138-fde77262-72e4-11e7-8941-1515b4ee2309.png">

**Comment by Jakobud** [comment]
/facepalm

Okay so the code is working fine and I guess the mutation is just a side effect. Thank you for your help!

**Comment by jfirebaugh** [comment]
Turns out we have an issue for the input mutation: #4040.

**Comment by TonyLugg** [comment]
I just came across this myself.  If I want to draw a rectangle by updating the source coordinates as the mouse is dragged, I should keep the source in a separate variable and update the coordinates there?  I don't see a setSource method...
