### ISSUE TITLE
Issue with layers getting "cropped" on pan/tilt

### ISSUE THREAD

**Issue by tbassett44** [mapbox/mapbox-gl-js#5058]
**mapbox-gl-js version**:
0.39.1
### Steps to Trigger Behavior
The issue seems to be prevalent when the bearing or tilt are non-zero, other than that, this issues seems to be pretty hit or miss.  Even though there are many layers configured in the same way, it only sometimes happens.

### Expected Behavior
Markers should show in their entirety regardless of pan/tilt, especially with "icon-allow-overlap":true

### Actual Behavior
Markers sometimes get cut off or dont show at all.  See images below.

In the images below, a marker is animated across the map (non zero pan/tilt values).  Interestingly, it started off as completely hidden, then as the marker moved, it slowly came into view with a clear line cutting off some of the marker.

![upload_thumb-1](https://user-images.githubusercontent.com/3107159/28692087-5dcd68fc-72dc-11e7-8fd1-133102af8c9f.png)
![upload_thumb](https://user-images.githubusercontent.com/3107159/28692089-61b0ab64-72dc-11e7-8422-81c4b6462439.png)

Any help with this would be greatly appreciated, thanks!

**Comment by tbassett44** [comment]
Here is a video to see a bit more clearly...

https://player.groupup.me/video/YnLtw1Uzw

**Comment by pathmapper** [comment]
@tbassett44 this is likely related to https://github.com/mapbox/mapbox-gl-js/issues/2706.
I had a similar [issue](https://github.com/mapbox/mapbox-gl-js/issues/4994). You could try to increase the tile buffer or set `"icon-allow-overlap":false` .

**Comment by tbassett44** [comment]
@pathmapper How/where do you change the tile buffer?  Not seeing documentation on that.  Thanks for the quick response!

**Comment by pathmapper** [comment]
@tbassett44 are you using a custom or a Mapbox tileset? When you are creating a custom tileset you could use [Mapbox Studio Classic](https://www.mapbox.com/mapbox-studio-classic/). There it is possible to set the buffer size in the [data layer options](https://www.mapbox.com/help/studio-classic-sources/#data-layer-options). Or you could use [tippecanoe](https://github.com/mapbox/tippecanoe) with `-b` option. With the current Mapbox Studio I think it is not possible at the moment.

**Comment by mollymerp** [comment]
@tbassett44 can you provide a jsfiddle or jsbin that reproduces this behavior?

**Comment by tbassett44** [comment]
@mollymerp It is not being reproduced here, but I made a lot of headway on the jsfiddle.  I have a feeling this might be due to the complexities of the overall map being built.  Will put in the time when I have it to try to reproduce entirely.

https://jsfiddle.net/gxc5ca9d/13/

**Comment by pathmapper** [comment]
jsfiddle with cut marker: https://jsfiddle.net/gxc5ca9d/14/

**Comment by tbassett44** [comment]
Wow, thanks @pathmapper!!!  Seeing as you were able to reproduce, does this fit with what you were saying above?  We get our tiles from: https://openmaptiles.com/ and we have a custom tile serving mechanism.

**Comment by pathmapper** [comment]
Can't reproduce with v0.42.0: https://jsfiddle.net/gxc5ca9d/15/

Seems that https://github.com/mapbox/mapbox-gl-js/pull/5150 fixed it.

**Comment by mollymerp** [comment]
Thanks @pathmapper ! Glad to hear it.
