### ISSUE TITLE
How to use map.fire to simulate map.on("click")?

### ISSUE THREAD

**Issue by Roxyi** [mapbox/mapbox-gl-js#5060]
Hi, I tried using [fire](https://www.mapbox.com/mapbox-gl-js/api/#evented#fire) to simulate click function, but I met a problem.

For example, my click function is:
```javascript
map.on("click", function(e){
  console.log(e);
});
```
If you actually click on the map, the results will be:
![image](https://user-images.githubusercontent.com/8086358/28694154-1bb0416e-72f6-11e7-8c68-af1cfc7ce093.png)

Now I need to simulate a user click on the center of the map.  My fire function is:
```javascript
var center =  map.getCenter();
map.fire("click", {lngLat: center});
```
And the results I got is:
![image](https://user-images.githubusercontent.com/8086358/28694131-fcf0e88c-72f5-11e7-8ca3-c67d2423dab3.png)

The problem is that in the results of my fire function, there is no **"point"**. Without the parameter "point", I will not be able to use **map.queryRenderedFeatures()** to get the layer's features.

I know that I missed the parameter "point" in my fire function, but I cannot find a way to get it.

Any help with this would be greatly appreciated. Thanks!

**Comment by jfirebaugh** [comment]
Hi @Roxyi. You can use [Map#project](https://www.mapbox.com/mapbox-gl-js/api/#map#project) to translate from `LngLat` to screen coordinates.

**Comment by Roxyi** [comment]
@jfirebaugh   Thank you so much. It solved my problem. Also this solved my other question. I was working on getting the features merely based on lat and lng. I think using the projected point, I will be able to do it.

**Comment by justinmanche** [comment]
For anyone using this to simulate clicks in test environments like Cypress, I've had success with this:
```
map.fire('click', { latLng: coords, point: map.project(coords), originalEvent: {} })
```

**Comment by jaikumar-Xperate** [comment]
i tried all solution but in my scenario click event is not working 
can anyone suggest something

**Comment by chriszrc** [comment]
@jaikumar-Xperate it still works, but note that `features` will be empty. If you're relying on getting information about the clicked features, you need to use `queryRenderedFeatures` and supply them yourself-
