### ISSUE TITLE
DDS text-field does not accept tokens

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#5062]
`text-field:{property}` renders text depending on the property, but DDS (categorical and interval) text-field renders the literal `{property}` string, without parsing the property itself.

**Comment by lbud** [comment]
This is [expected behavior](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-field).

**Comment by jfirebaugh** [comment]
See also #4484.
