### ISSUE TITLE
Incorrect default text positioning on a curve

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#507]
#### Original issue:  https://github.com/mapbox/mapbox-gl-style-spec/issues/61

Text seems to be positioned too high compared to expected behavior:
![screen shot 2014-06-18 at 5 19 57 pm](https://cloud.githubusercontent.com/assets/5607844/3320873/27395092-f730-11e3-9092-b04272b838a9.png)

Fontstack shown is:
"Helvetica LT Std Roman, Arial Unicode MS Regular, Open Sans Regular"

I also tried with:
"Gotham Medium, Arial Unicode MS Bold, Open Sans Semibold",

**Comment by mourner** [comment]
Is this still reproducible?

**Comment by ansis** [comment]
I haven't seen this since then and the fonstacks listed here are dead. A lot has changed since then, so I'll assume this was fixed. @nickidlugash if you see this again, reopen.
