### ISSUE TITLE
GET http 500 error

### ISSUE THREAD

**Issue by jhjhjh96** [mapbox/mapbox-gl-js#5082]
![mapbox](https://user-images.githubusercontent.com/26427276/28865407-cbd94442-77aa-11e7-908d-ccf5fc10df16.PNG)
I am wondering how request 'http' again until server response.

Currently, I success play my map, but I have a little problem.
Because request time is short, sometimes client can't get data.

Sever is working slowly but client doesn't stay and output error (get ~~~ 500()).
So I want to ask your advise about 'waiting server's respond' or 'when this error occured, request again' 

How should I do?

ps. I am opening my local server.  If you want to see this map, here ' http://118.130.22.146:3000/ '
and because of cross origin, you have to install 'CORS' plug-in in chrome.

https://chrome.google.com/webstore/detail/allow-control-allow-origi/nlfbmbojpeacfghkpbjhddihlkkiljbi/related?hl=ko

When you move map fastly, '500 error' will ouccur.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
