### ISSUE TITLE
setStyle on raster sources triggers a full reload under some circumstances in v0.39.1

### ISSUE THREAD

**Issue by cubodehelio** [mapbox/mapbox-gl-js#5083]
Hello guys, this is (maybe) kind a continuation of the issue [#3893](https://github.com/mapbox/mapbox-gl-js/issues/3893) I'm still having this problem under some circumstances in **v.0.39.1**.

Updated fiddle here: https://jsfiddle.net/3s8gdhwr/
In the example I'm changing the `layout.visibility` on a single layer after a timeout and a full reload is triggered. This happen even if I comment the line that made the change (use `setStyle` with no style changes at all). Also the console shows this warning:

```
Unable to perform style diff: Unimplemented: setLayerProperty..  Rebuilding the style from scratch.
```

I suspect that the problem arise from this part of the style:

```json
"sources": {
  "composite": {
    "url": "mapbox://mapbox.mapbox-streets-v7",
    "type": "vector"
  },
  "mapbox://mapbox.satellite": {
    "url": "mapbox://mapbox.satellite",
    "type": "raster",
    "tileSize": 256
  }
```

But i can't be sure though.

**Comment by jfirebaugh** [comment]
Remove the `"interactive": true`'s from the layers. This property is not needed anymore.
