### ISSUE TITLE
GET tiles 404 (Not Found) and evented.js:104 Error

### ISSUE THREAD

**Issue by Roxyi** [mapbox/mapbox-gl-js#5093]
**mapbox-gl-js version**:  mapbox-gl.js v0.39.1

### Steps to Trigger Behavior

 1. Upload a shapefile to Mabox Studio and it automatically converted my shapefile to vector tiles
![image](https://user-images.githubusercontent.com/8086358/28930570-6207022e-7841-11e7-8ffd-145c5e279626.png)

 2. Use mapbox gl js to add the vector tiles to the map
example: [js bin](https://jsbin.com/lujoja/4/edit?html,console,output)
 
3. Continue zooming out the map

### Expected Behavior
no error

### Actual Behavior
![image](https://user-images.githubusercontent.com/8086358/28930709-d1ab6a48-7841-11e7-9930-8fcd04a344ea.png)
It gave me 404 and evented.js:104 error
![image](https://user-images.githubusercontent.com/8086358/28930762-f8388b78-7841-11e7-82e4-3d6ae04e95ba.png)

I guess when you zoom in and out the map, it sometimes returns empty content.

This is changed to **Error: http status 200 returned without content**, if I add a third party vector tile source.

**Comment by Roxyi** [comment]
Update to this issue:

Hi guys, I think I solved this problem. First, I would like to apologize that I made a mistake in the previous issue report. The mbtiles is actually created by Mapbox Studio Classic not by Mapbox Studio. 

I think the problem is caused by Mapbox Studio Classic. See these two mbtiles.
![image](https://user-images.githubusercontent.com/8086358/28936692-77f008b4-7856-11e7-9473-eb300c83690e.png)
![image](https://user-images.githubusercontent.com/8086358/28936716-8d6cc47a-7856-11e7-8579-21eca4936508.png)

The first one is created by directly uploading shapefile to Mapbox Studio and the second one is created in Mapbox Studio Classic. The second one has more zoom level but a smaller size. So that's why there is empty content returned. I don't know why Mapbox Studio Classic cut the size of the mbtiles. I think engineers from Mapbox will help explain.

Also I tested the mbtiles created by [tippecanoe](https://github.com/mapbox/tippecanoe), there is no error message. So I think if you want to adjust the zoom extent or host the mbtiles by yourself, tippecanoe is the best way.

**Comment by Roxyi** [comment]
I did more tests with tiles created by Mapbox Studio and tippecanoe. There is still 404 error.
I updated the [js bin](https://jsbin.com/lujoja/edit?html,console,output) with the tiles created by Mapbox Studio.

Now it is not that easy to trigger the error. When you point your mouse at the west border of Manhattan and zoom in. The error will appear. Also, when you point your mouse outside the border, zoom in, the error will also appear.

**Comment by lbud** [comment]
Hi @Roxyi, thanks for the report. This is expected browser behavior — see https://github.com/mapbox/mapbox-gl-js/issues/1800#issuecomment-310380381 for further explanation.

**Comment by lbud** [comment]
Er, sorry, spoke too soon — Mapbox GL shouldn't be logging that as an error anymore, only the browser.

**Comment by Roxyi** [comment]
@lbud Thanks for your help. I guess this is the browser behavior too. When I added mbtiles from a third party tile source. It will return Error: http status 200 returned without content,

These error messages do not affect the map, they are just annoying when you need to debug in the console.

**Comment by jfirebaugh** [comment]
→ #5574
