### ISSUE TITLE
Clarify documentation about stop function behavior for input < lowest stop value

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#5098]
**mapbox-gl-js version**:
0.39.1

According to the [style specification for Function Types](https://www.mapbox.com/mapbox-gl-js/style-spec/#function-type):

> interval
> **functions return the output value of the stop just less than the function input**. The domain (input value) must be numeric. Any style property may use interval functions. For properties marked with ,  the "interval" symbol, this is the default function type.

This means that any feature with a value **less than the first stop** should take the default value if it exists, and any feature with a value **greater than the last stop** should take the output value of the last stop.

### Steps to Trigger Behavior
https://jsbin.com/naciqocuja/1/edit?js,output

### Expected Behavior
Maryland should be transparent, not red.

### Actual Behavior
Maryland is red, despite it's value being less than the lowest declared stop.

This behavior has existed since version 0.32.0, when `default` was first introduced to the style specification.

**Comment by jfirebaugh** [comment]
The current behavior is correct, it's the documentation that should be clarified.

**Comment by DannyDelott** [comment]
Thanks @jfirebaugh for the reply. I was really hoping the behavior was wrong and the documentation was correct! :)

Here's a more "real world" example.

I only want to style the features with a `dangerLevel` of 10 or greater. It should be sufficient to declare this as the only stop. https://jsbin.com/loperudiqu/1/edit?js,output

However, the current behavior treats the same as if I had simply set `fill-color: 'red'` when the whole purpose of doing data-driven styling is to style only the data you care about!

If the behavior is in fact correct, how would one declare data-driven stops to accomplish this scenario? 

![image](https://user-images.githubusercontent.com/4524175/28986754-262bd18a-791d-11e7-9c0a-6b0cb94a925c.png)

**Comment by lbud** [comment]
> whole purpose of doing data-driven styling is to style only the data you care about

The whole purpose of data-driven styling is to _style_ data differently based on its underlying properties. The purpose of filters is to _select_ only the data you want to render.

For your use case you should use a filter to prohibit certain features from being styled by this layer:
```
"id": ...,
"filter": [ ">=", "dangerLevel", 10 ],
"paint": { ... },
```
See [filter documentation](https://www.mapbox.com/mapbox-gl-js/style-spec/#types-filter) for further details.

**Comment by DannyDelott** [comment]
Thanks @lbud for the response.

Don't filters prevent the feature from being rendered at all? In this case, I still want to be able to do `queryRenderedFeatures` and interact with the entire layer, I just don't want them to be red.

**Comment by anandthakker** [comment]
@DannyDelott perhaps `querySourceFeatures` would work for you?  If not, another option would be to use a separate, transparent layer for querying.

**Comment by DannyDelott** [comment]
Thanks @anandthakker for the suggestion. I think we're going to go with using a separate transparent layer for querying.
