### ISSUE TITLE
map.unproject(...) delivers different values compared to 0.38.0

### ISSUE THREAD

**Issue by tanwald** [mapbox/mapbox-gl-js#5107]
**mapbox-gl-js version**:
0.39.2
### Steps to Trigger Behavior

 1. Upgrade from 0.38.0 to 0.39.2
 2. Compare markers set with LngLat-values from map.unproject(...) before and after upgrade

### Expected Behavior
Markers set with values from map.unproject(...) are at the same position before and after upgrade. 
### Actual Behavior
I use map.unproject(...) to define a bounding box that is smaller than the one you get with map.getBounds(). After the upgrade this bounding box is bigger than before - bounds are even beyond canvas size.

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained JSFiddle that demonstrates the issue?

**Comment by tanwald** [comment]
Sorry, map.unproject(...) delivers consistent values. Offset values for custom markers seem to be interpreted differently - relative to the center of the marker. Is this a new and intended behaviour? 

The fiddles are identical except for the api version:

v0.38.0
https://jsfiddle.net/u4e30xqb/1/
v0.39.1
https://jsfiddle.net/u4e30xqb/2/

**Comment by tanwald** [comment]
Okay, it is intended behaviour...  breaking change in v0.39.0
