### ISSUE TITLE
Roads from different layer can not merge

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#5109]
![image](https://user-images.githubusercontent.com/16457917/29009815-29eefa20-7b59-11e7-9382-3c436b138f09.png)

As shown above, there are two layer of road, and one is drawn on the top of another.

While we want this kind of effect:

![image](https://user-images.githubusercontent.com/16457917/29009825-34604ed2-7b59-11e7-8c6d-5365cbb097be.png)

Is this possible?

**Comment by stevage** [comment]
Yes, of course. Create one layer for the outlines, and on top of it, a layer for the interiors.

Probably best to ask support questions at gis.stackexchange.com or stackoverflow.com, tagged "mapbox-gl-js".

**Comment by exotfboy** [comment]
> Yes, of course. Create one layer for the outlines, and on top of it, a layer for the interiors.

That's what we are doing at the moment.

In fact there are four layers:

```
road_type_a_outline
road_type_a_fill
road_type_b_outline
road_type_b_fill
```

**Comment by peterqliu** [comment]
@exotfboy put both fills above both outlines.

**Comment by exotfboy** [comment]
@peckjon Thanks, it worked. 👍
