### ISSUE TITLE
mapboxgl.Marker undefined if togglePopup() when initialising Marker

### ISSUE THREAD

**Issue by Utzel-Butzel** [mapbox/mapbox-gl-js#5116]
When creating a new marker and setting up a popup which will be immediately enabled via `togglePopup()` the created marker returns undefined.

based on the [Custom Marker Icons](https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/) demo
```
var markerEl = new mapboxgl.Marker(el)
.setLngLat(marker.geometry.coordinates)
.setPopup(popup)
.addTo(map)
.togglePopup();
 console.log(markerEl);

```
**mapbox-gl-js version**:
v0.37.0

### Steps to Trigger Behavior

 1. Creating the marker
 2. Console output

### Expected Behavior
Return the `var markerEl`
### Actual Behavior
returns undefined if `.togglePopup() `set otherwise it returns the correct element

**Comment by mollymerp** [comment]
@Utzel-Butzel thanks for the report. You're right, the documentation does say that `Marker#togglePopup` should return the `Marker` element, and right now it's returning nothing.
