### ISSUE TITLE
Render tests results for text-pich-{alignment,scaling} are false positives

### ISSUE THREAD

**Issue by brunoabinader** [mapbox/mapbox-gl-js#5118]
Our current render tests are indicating false positives for the following render tests in GL JS:

| Render test | Diff (image) |
|--|--|
| text-pitch-alignment/auto-text-rotation-alignment-map | ![1](https://user-images.githubusercontent.com/76133/29092038-8a4f5aa6-7c8d-11e7-8291-408b35a6ede8.png) |
| text-pitch-alignment/map-text-rotation-alignment-map | ![2](https://user-images.githubusercontent.com/76133/29092048-90afa158-7c8d-11e7-927f-533c1817ef48.png) |
| text-pitch-scaling/line-half | ![3](https://user-images.githubusercontent.com/76133/29092057-99af2a26-7c8d-11e7-8014-bec82c9afbf5.png) |

We're removing the diff handicap for these tests in https://github.com/mapbox/mapbox-gl-js/pull/5117.

This issue will be used as a guide in our test suite ignore list for GL JS to pursue a proper fix.

Related: https://github.com/mapbox/mapbox-gl-native/issues/9732

**Comment by ChrisLoer** [comment]
The global/viewport collision detection changes will require a re-visit of all these tests, and hopefully once we make those changes the test behavior will become more stable. It does make me nervous to have these tests disabled on both platforms until then...

/cc @ansis @mollymerp

**Comment by brunoabinader** [comment]
Fixed in #5660.
