### ISSUE TITLE
icon-offset scales in integer steps

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#5129]
**mapbox-gl-js version**: 0.37.0

### Steps to Trigger Behavior

I have an icon image which is a pin (where the bottom end of the pin represents the precise location). It gets bigger as you zoom in. I'm trying to line up a text label so the label always sits at the bottom end of the pin.

The relevant part of the pin style looks like this:

```
    layout: {
        'icon-image': 'Markers%20for%20Mapbox-01',
        'icon-size': {
            stops: [
                [13, 1 * pinScale],
                [17, 3 * pinScale]
            ]
        },
        'icon-allow-overlap': true,
        'icon-offset': { stops: [
            [13, [0, -30]],
            [17, [0, -90]]
        ]}
    },

```

And the label:

```
    layout: {
        'text-size': 16,
        'text-font': ['CoM Regular','Arial Unicode MS Regular'],
        'text-field': '{Title}',
        'text-anchor': 'left'
   }
```

Observe what happens when I zoom in or out across an integer zoom boundary:

<img width="525" alt="screenshot 2017-08-10 14 51 49" src="https://user-images.githubusercontent.com/678344/29154964-e97b6a34-7ddb-11e7-8f9e-244bdbaa7ed2.png">

<img width="523" alt="screenshot 2017-08-10 14 52 01" src="https://user-images.githubusercontent.com/678344/29154966-ebc74948-7ddb-11e7-88f4-b18e95d5df2a.png">

![faces-marker](https://user-images.githubusercontent.com/678344/29155051-8d85cb6a-7ddc-11e7-967c-5d0ed0ea2bd5.gif)

### Expected Behavior

Smooth transitioning, so the offset is scaling at exactly the same rate as the icon is getting bigger, so the illusion of the label being attached to a specific point on the icon works.

### Actual Behavior

The offset seems to jump in whole integer amounts, leading to the icon jumping around distractingly.

The same thing happens with `text-offset`

**Comment by kristfal** [comment]
Just to chime in: Our current workaround is to create a buffer at the bottom of the marker so the actual center of the sprite matches the tip of the marker. This isn't really optimal, and I'd say an `icon-anchor` property that behaves similar to `text-anchor` would be the best solution as it wouldn't require any intricate scale / offset matching in the style to make this behavior work.

**Comment by stevage** [comment]
Thanks. In this particular case that's awkward to implement as the marker asset is loaded dynamically from an asset library that I don't control.

Looks like the `icon-anchor` issue was [raised once before](https://github.com/mapbox/mapbox-gl-js/issues/3002) and closed with a different workaround (for markers, rather than icons, actually).

**Comment by jfirebaugh** [comment]
This is the expected behavior of `icon-offset` -- per the [documentation](https://www.mapbox.com/mapbox-gl-js/style-spec/#other-function), layout property functions are evaluated only at integer zoom levels:

> There is an important difference between the way that zoom functions render for layout and paint properties. Paint properties are continuously re-evaluated whenever the zoom level changes, even fractionally. The rendered value of a paint property will change, for example, as the map moves between zoom levels 4.1 and 4.6. Layout properties, on the other hand, are evaluated only once for each integer zoom level. To continue the prior example: the rendering of a layout property will not change between zoom levels 4.1 and 4.6, no matter what stops are specified; but at zoom level 5, the function will be re-evaluated according to the function, and the property's rendered value will change. (You can include fractional zoom levels in a layout property zoom function, and it will affect the generated values; but, still, the rendering will only change at integer zoom levels.)

Consider using the paint property `icon-translate` instead.
