### ISSUE TITLE
Keep important glyphs always exist while others conflict with them disappear by zooming

### ISSUE THREAD

**Issue by huangyingjie** [mapbox/mapbox-gl-js#5130]
What's the rule that deal with two words scrambled for the same place ?
I find that one of them disappear, but I don't understand why. And how can I control that?

For example, When I reduce the zoom, I want that `Railway Station name` should never be replaced by other road name or poi name.

**Comment by jfirebaugh** [comment]
Hi @huangyingjie. Symbol priority is determined by the order of the layers in the style. In a style's array of layers (i.e. ["country", "city", "road"], later layers (i.e. "road") symbols take precedence over earlier layers.
