### ISSUE TITLE
Marker offset changes from 0.38 to 0.39 cause marker to jump on map drag

### ISSUE THREAD

**Issue by keyofj** [mapbox/mapbox-gl-js#5131]
mapbox-gl-js version: 0.39.1

### Steps to Trigger Behavior

 1. Place custom marker on screen 
```javascript
var marker = new mapboxgl.Marker()
```
 2. Move the marker to an intersection as a reference point
![image](https://user-images.githubusercontent.com/8008256/29185141-637b6240-7dd6-11e7-999e-d40842fbfddb.png)
 
 3. Click on the map away from the marker, and SLIGHTLY drag the map.
![image](https://user-images.githubusercontent.com/8008256/29185276-bd8b335a-7dd6-11e7-9e41-cf3b6c1461d9.png)

### Expected Behavior
The marker remains at the position moved to.

### Actual Behavior
The marker jumps and ignores the applied offsets.

Referencing the updates for 0.39 I saw that the marker was updated to position at its center. Taking that change into account I adjusted the marker offset with no effect. I can even take an offset off completely and it has the same behavior.

We also attached a mapbox popup to the marker and found that when the marker is originally placed on the map the popup opens centered on the marker (no offsets have been applied to the popup).

![image](https://user-images.githubusercontent.com/8008256/29185669-eb2aa1fa-7dd7-11e7-9c29-87e0cd5c08a0.png)

If I move the marker to another position and click  to open the popup the popup is aligned to the top left of the marker.

![image](https://user-images.githubusercontent.com/8008256/29185722-289c8cd8-7dd8-11e7-97a4-193091b0be9e.png)

When I again click on the map and slightly drag, the marker jumps to the popup.
![image](https://user-images.githubusercontent.com/8008256/29185759-47aeb06a-7dd8-11e7-83ec-3fee667a9dd8.png)

If I revert back to version 0.38.0 none of the above happens and all is fine. The placement of these markers is critical to our application as the center point is used in reports to calculate distances. If the markers jump like this then those reports can be incorrect.

Any suggestions?

**Comment by peterqliu** [comment]
>Move the marker to an intersection as a reference point

>If I move the marker to another position and click to open the popup the popup is aligned to the top left of the marker.

@keyofj how are you performing these moves?

**Comment by peterqliu** [comment]
@keyofj I'm unsure how Kendo works, but if it's pure DOM manipulation, note that mapbox-gl does not track marker state (or any state, really) in the DOM. You will need to update marker position by calling [.setLngLat()](https://www.mapbox.com/mapbox-gl-js/api/#popup#setlnglat)

**Comment by keyofj** [comment]
Yes sir we do that as mapbox does not have built in draggable features as Google.

The issue is not Kendo. There is a change made in mapbox from version 38 to 39 that is causing the issue. From the change list for 39 there was a change to the marker and how it centers. I surmise that it was done in relation to symbols and not the marker object?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mollymerp** [comment]
@keyofj can you please provide a minimal example on jsfiddle or jsbin that reproduces the behavior you're seeing?

**Comment by keyofj** [comment]
I have created two jsFiddles for you. One for version 0.38.0 which works as expected and one using 0.39.1 where the marker jumps as described above.

[v0.38.0](https://jsfiddle.net/keyofj/54v61L3y/17/) - works
[v0.39.1](https://jsfiddle.net/keyofj/vfoLb8bf/44/) - marker jumps

**Comment by jfirebaugh** [comment]
Thanks @keyofj, that JSFiddle helped -- I can see why it's behaving that way. When `setLngLat` is called at the end of the drag, the marker element is still hidden, so the 50% offset is calculated based on a size of zero. In other words, this is the same issue as described in #5133. I'm going to close in favor of that issue. The fix looks straightforward and we should be able to address it for the next release.

**Comment by keyofj** [comment]
@jfirebaugh Thanks! I thought that with the Kendo draggable that the callbackSuccess was fired after the dragend but that was just an assumption on my part. Do you think if I temporarily move the show() into the success that would temporarily help?
