### ISSUE TITLE
Prevent 500 HTTP code from throwing an exception

### ISSUE THREAD

**Issue by rvratner** [mapbox/mapbox-gl-js#5141]
Hi,

We're using a public ocean shelf tileset, and when we zoom into certain areas, the service is throwing a 500 (instead of a 404, tile not found). We're hoping for a way to suppress this. Is there an event listener we can hook into to stop the errors from being thrown?

**mapbox-gl-js version**: v0.39.1

### Steps to Trigger Behavior

 1. Load raster tile
 2. Tile server throws 500
 3. client throws 500 JS error in log

### Expected Behavior
We're hoping for a way to suppress the 500 error if the tile doesn't exist

### Actual Behavior
Browser is throwing multiple 500 GET errors.

**Comment by mollymerp** [comment]
hi @rvratner and thanks for the report. unfortunately, there is no way to do this currently, and I'm not sure we'd want to implement this in core. is the 500 error breaking your maps or just cluttering up the console?

**Comment by stevage** [comment]
Just checking you're aware of [this handler](https://stackoverflow.com/questions/42772538/mapbox-how-to-avoid-javascript-errors-for-tilesets-that-arent-available-at-the/42777638#42777638). (I don't know if it works on 500s.)

**Comment by rvratner** [comment]
Hi,
Thanks for your response. It's not breaking the maps, just cluttering the console (and we have e2e tests that fail if there's console errors.).

@stevage I saw that handler and tried it, it quiets the mapbox errors but the browser still throws the GET 500 error. Makes sense why you wouldn't want to implement it in core, though I can imagine this happening on other instances where APIs don't send the correct response.

For now we'll try and change the tests to ignore that use case and see if we can get a hold of the authors of the service throwing the error in the first place.

You can close this ticket, thanks

Rachel

**Comment by mollymerp** [comment]
Even if we didn't emit an error in this case, the browser would still fire its own error unfortunately. Hope you find a solution that works for you!

**Comment by stevage** [comment]
@rvratner I feel your pain. I've worked with lots of crappy government spatial services, seen the behaviour you're experiencing - as well as the equally painful 200s generated by some versions of GeoServer even when there is an error, helpfully expressed in XML. :/

**Comment by rvratner** [comment]
Thanks @stevage and @mollymerp, appreciate your help :)
