### ISSUE TITLE
Introduce a generic object serializer/deserializer for WebWorker transfers

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5143]
See [sketch here](https://github.com/mapbox/mapbox-gl-js/compare/web-worker-transfer).

The idea is to replace all our manually-defined `serialize` methods with a generic serializer function that recursively serializes the own-properties of an object and records the constructor name, and all our manually-defined `deserialize` methods with a generic deserializer that looks up the constructor name in a class registry, then uses `Object.create` to reconstitute an instance without triggering the constructor.

Properties that should not be serialized (e.g. cached computed values) shall be marked as non-enumerable.

In the sketch above, `Tranferable`s that should be transferred can be flagged by setting a `transfer: true` property on the `Transferable`. But I think it would be better to make `serialize` a transfer-only operation, and require you to copy ahead of time of any `Transferable`s you need to copy.

**Comment by anandthakker** [comment]
> Properties that should not be serialized (e.g. cached computed values) shall be marked as non-enumerable.

This is elegant from the point of view of the serialize/deserialize code, but I think the verbosity it requires in client code is a bit much:

```js
(Object.defineProperty: any)(this,  '_cached', {
  writable: true,
  enumerable: false,
  value: this.n * this.n
});
```

Since classes have to be registered anyway, an alternative would be to allow an optional `{ include: [property name] }` argument to `register()`.

**Comment by anandthakker** [comment]
I suppose we could also reduce verbosity with a helper function `addTemporaryProperty(this, '_cached', this.n * this.n)`, but that still feels more complicated / less readable to me.

**Comment by jfirebaugh** [comment]
I'm 👍  on a `register` option with reversed sense: `{ omit: [...] }`.
