### ISSUE TITLE
event listeners on a layer should be dormant when the layer is removed, and re-activated when the same layer is re-added

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#5145]
For the background see https://gis.stackexchange.com/questions/251921/how-to-remove-events-map-onclick-from-mapbox-gl

If a user add's event listeners to a layer with `map.on(type, layer, listener)` and then removes that layer without having removed the event listeners with `map.off`, GL JS will fire an error when that event listener tries to trigger.

I can't think of any use cases for GL JS to not removing any active event listeners when calling removeLayer.

**mapbox-gl-js version**: 0.39.1

### Steps to Trigger Behavior

 1. addLayer
 2. register an event listener on that layer
 3. remove the layer without removing the event listeners with `off`

https://jsbin.com/jecixe/edit?html,console,output

### Expected Behavior

Upon removeLayer, GL JS would automatically remove any event listeners.

### Actual Behavior

    "The layer '' does not exist in the map's style and cannot be queried for features."

**Comment by jfirebaugh** [comment]
I wouldn't expect it to produce an error, but I also wouldn't expect it to deregister the event listener. Instead, I'd expect the event listener to simply remain dormant until a layer with a matching ID was added again.

The analog this API is modeled on is [jQuery delegated events](http://api.jquery.com/on/#direct-and-delegated-events), which works that way. In fact, you can add a delegated event listener prior to there being any matching descendants / layers, which is sometimes handy.
