### ISSUE TITLE
Navigation_control.js has copyMouseEvent function which ignores buttons

### ISSUE THREAD

**Issue by JelmerBaas** [mapbox/mapbox-gl-js#5148]
Navigation_control.js has copyMouseEvent function which ignores buttons and forces right mouse button. This event propagates to the map and fires our right mouse up handler.

**mapbox-gl-js version**: 0.39.1

### Steps to Trigger Behavior

 1. Create map with compass
 2. Left click compass
 3. originalEvent.button is always 2

### Expected Behavior
copyMouseEvent copies original button

### Actual Behavior
copyMouseEvent has hard-coded buttons: 2

See: https://jsfiddle.net/oqnta3ek/

**Comment by jfirebaugh** [comment]
Fixed in #5157.
