### ISSUE TITLE
dependency: fast-stable-stringify

### ISSUE THREAD

**Issue by BernhardRode** [mapbox/mapbox-gl-js#5152]
Hi,

currently mapbox-gl-js has the dependency fast-stable-stringify, which is licensed under a GPL-3 license. This is problematic for corporate developers (like me), as we are not allowed to build apps with copyleft based licenses.

Do you think that it, would it be possible to get rid of that dependency?

**Comment by mourner** [comment]
Yes, I think it could be replaced. Thanks for the suggestion.

**Comment by BernhardRode** [comment]
@mourner do you know when mapbox is going to release the net patch version (including this change)

The current version is a blocker for us at the moment and we'd like to release our next version =)

**Comment by mourner** [comment]
@BernhardRode we're working on getting a new release pretty soon. Only [a few issues](https://github.com/mapbox/mapbox-gl-js/issues?q=is%3Aissue+is%3Aopen+label%3A%22release+blocker%22) left to handle.
