### ISSUE TITLE
windows explorer doesn't working

### ISSUE THREAD

**Issue by jhjhjh96** [mapbox/mapbox-gl-js#5158]
![232](https://user-images.githubusercontent.com/26427276/29396685-3919efe8-8354-11e7-8aa9-6c33fb40f897.PNG)
[ms explorer]

![44343](https://user-images.githubusercontent.com/26427276/29396686-393f08fa-8354-11e7-8059-d619f61e7373.PNG)
[chrome]

**chrome, edge are working.
but explorer 11 isn't.

My OS is win10 64bit.
and my html is same source (https://www.mapbox.com/mapbox-gl-js/examples/)**

[node.js local server]
// eslint-disable-next-line strict
const fs = require('fs');
const express = require('express');
const app = express();
const port = 3000;

app.use('/dist', express.static(`${__dirname}/dist`));
app.use('/public', express.static(`${__dirname}/public`));

app.get('/', (req, res) => {
    fs.readFile(`${__dirname}/dist/map.html`, (error, data) => {
        res.writeHead(200, {'Content-Type': 'text/html'});
        if (error) {
            console.error(error);
        }
        res.end(data);
    });
});

app.listen(port);
console.log(`Listening on port 3000`);

**what is problem in my project?**

**Comment by anandthakker** [comment]
@jhjhjh96 thanks for reporting this issue.  Couple questions:
 - Does it _always_ fail to load? (Could you reloading the page a few times?)
 - If you open https://www.mapbox.com/mapbox-gl-js/examples/ directly, do you see the same problem?

Possibly a duplicate of #3040

**Comment by jhjhjh96** [comment]
Yes, it always fail. I think this problem is CORS.
I found request origin was 'blob://'.
after add cors header, I will ask again.
thank you
