### ISSUE TITLE
Use zoomTo independent from jumpTo

### ISSUE THREAD

**Issue by stephanbogner** [mapbox/mapbox-gl-js#5159]
Hello all,

I am moving the map along a route (by getting a certain point on the route through turf) and want to toggle between being zoomed in and out. However it seems to me, that using `map.jumpTo` overwrites `map.zoomTo`. (Maybe related to [1051](https://github.com/mapbox/mapbox-gl-js/issues/1051))

### Demo
https://jsbin.com/rayemefiza/edit?html,output
(If you set `move` to false in the first line of JS, you can see that zooming works)

**mapbox-gl-js version**: v0.39.1

### Steps to Trigger Behavior
1. Open link
2. Done

### Actual Behavior (or what I had expected)
Map should be centered according to jumpTo and zooming works independently from that.

**Is the current behaviour the intended one?**
*Thanks for your patience and the awesome product you folks are creating :)*

**Comment by anandthakker** [comment]
Hi @stephanbogner - thank you for providing the example.

The reason you're seeing this behavior is that `jumpTo()` always interrupts any in-progress movement that may be happening -- so, yes, this is intended behavior.

One way you can make this work is to stop doing `jumpTo` when you begin zooming, and wait for the `zoomend` event before resuming.  Here's a variation on your example that does this: https://jsbin.com/qitobadeyi/edit?html,output
