### ISSUE TITLE
Lint for features unsupported by Node v4 in cross-platform testing code

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5164]
The modules in `test/integration` directory are used to run query, render, and (soon) expression integration tests for both GL JS and GL Native.  Since GL Native [supports Node v4](https://github.com/mapbox/mapbox-gl-native/blob/master/package.json#L33), we should lint these sources for ES2015 features that aren't supported in node 4.

**Comment by jfirebaugh** [comment]
Have you found a linter that will do this? I looked for one when we wanted to limit use of Bublé features to the node 4 subset, but couldn't find anything.

It'd also be useful for the examples, where we want to stick to ES5.

**Comment by anandthakker** [comment]
I think `eslint` can do it.  I'm using it in the `feature/expressions` branch to verify that the JS generated in each integration test is ES5 only:

https://github.com/mapbox/mapbox-gl-js/blob/6965f91cfd71ee7f442bfeaec934aad72f3a6670/test/integration/lib/expression.js#L79-L80

For node v4 features, I was going to look into https://github.com/mysticatea/eslint-plugin-node
