### ISSUE TITLE
"Tree" type in data style of points

### ISSUE THREAD

**Issue by noeltech** [mapbox/mapbox-gl-js#5167]
## Motivation

1."Tree" visualization from points are important next to 3d buildings
 2. Almost all local governments  and few private org. collects Tree/Plant data with geo tagging for 
 preservation, inventory,analysis,environment impact and a lot more..
(Im sorry if I dont know how to this with github,i just request feature for the first time ever )

## Design Alternatives
?

## Design
visualize the points by attributes
1.age of tree -color
2.height of tree-height, number of branches, how the leaves are spread

### Mock-Up
?

### Concepts
?

### Implementation
?

**Comment by jfirebaugh** [comment]
Hi @noeltech, thanks for the suggestion. We'd most likely support this as part of a more general 3d model feature, which is tracked in #3996. Closing as a duplicate.
