### ISSUE TITLE
Is there support or a way to create leader lines with arrows?

### ISSUE THREAD

**Issue by donnyv** [mapbox/mapbox-gl-js#5169]
I looked through the style guide and couldn't find this. Is it possible to create leader lines with arrows? 

example
![section-view-4](https://user-images.githubusercontent.com/2224189/29461044-41a695a4-83f8-11e7-911e-20d5b2d71093.gif)

**Comment by ryanbaumann** [comment]
@donnyv do you have a DXF or CAD document you're trying to convert a Mapbox GL vector tile source?  Or do you need to use the style of a generic leader line in a Mapbox GL map?

**Comment by donnyv** [comment]
Yes I have a DXF that I'm currently converting to geojson using OGR2OGR. Unless you know of a tool to convert to vector tiles?

**Comment by ryanbaumann** [comment]
If your DXF has leader lines in it already, they will most likely convert to a vector representation that Mapbox GL can render.  It depends on the specific DXF.

Once your DXF is in geojson format, you can directly load it as a Mapbox GL geojson source, or use a tool like Tippecanoe to cut layer styles.

[Really basic example](https://api.mapbox.com/styles/v1/rsbaumann/ciy6owizg00002squ9hqd7ihv.html?fresh=true&title=true&access_token=pk.eyJ1IjoicnNiYXVtYW5uIiwiYSI6IjdiOWEzZGIyMGNkOGY3NWQ4ZTBhN2Y5ZGU2Mzg2NDY2In0.jycgv7qwF8MMIWt4cT0RaQ#4.5/-0.532/39.099/-1)

**Comment by donnyv** [comment]
Nice! Thanks for the info and example.

**Comment by peterqliu** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/4096

see [last comment](https://github.com/mapbox/mapbox-gl-js/issues/4096#issuecomment-303367657) on how to do this currently.
