### ISSUE TITLE
Big sprite maps overflowing the Uint8ClampedArray

### ISSUE THREAD

**Issue by pwilczynski** [mapbox/mapbox-gl-js#5173]
In our application, users are able to re-style their icons. In the course of usage, therefore, a user may quickly overflow the sprite map. We've added icon reaping, which helps in some cases, but there's not much we can do when the user wants to have more icons than can be stored in the sprite map. Do you have any recommendations aside from forking Mapbox GL JS and changing it to a Uint16Array or otherwise increasing the size of the sprite map. Was Uint8Array chosen based on specifics of graphics card texture scaling, or was it just assumed to be a sufficient size?

**Comment by jfirebaugh** [comment]
Hi @pwilczynski. Yes, this is a known issue described in #141, and we have work underway to address it in #4876. (`Uint8Array` vs `Uint16Array` isn't really the issue here -- it's the capacity of the sprite atlas, not the size of array elements, that needs to be increased.)

**Comment by pwilczynski** [comment]
Hey @jfirebaugh thanks so much - we'll track #4876 and I'll make sure we take a look as that progresses. It's awesome to hear that you're working on this; we can't wait!
