### ISSUE TITLE
Dynamic symbol size based on source polygon

### ISSUE THREAD

**Issue by daumann** [mapbox/mapbox-gl-js#5176]
When using symbols with polygons as sources, the label is correctly placed on top of the polygon.
Is it possible to have the text-size dynamic to the size of the source polygon?

Example:
http://jsfiddle.net/LLhdfsdv/18/

It would be nice to have labels express the size of the entity (like in most maps).

**Comment by peterqliu** [comment]
@daumann you will need to compute the size of the entity separately, and include it as a property of the entity (e.g., as a property in a GeoJSON feature). 

In vector tiles, the entity is cut into many square pieces, and loses any concept of the whole (including size) once it's in these tiles.
