### ISSUE TITLE
Mapbox gl : How to perform a filter in a polygon ?

### ISSUE THREAD

**Issue by Baguewi** [mapbox/mapbox-gl-js#5178]
I want to make a filter on the geometry of my layer source vector.  
`var polygone = ..... 
 var filter = polygone.reduce(function (memo, coord) {  
  memo.push(coord);     
  return memo; 
 }, ['in', '$coordinates']);
 map.setFilter(layer, filter); `  
But I can not figure out how to apply the filter. Can someone help me?

**Comment by mourner** [comment]
You can only filter by feature type and properties. If you want to filter by certain geometry, you should do it before you send the data to GL JS, or preprocess it somehow to filter by properties.

**Comment by Baguewi** [comment]
Thank you @mourner
