### ISSUE TITLE
Changing styles causes Directions to break

### ISSUE THREAD

**Issue by bslevine** [mapbox/mapbox-gl-js#5180]
Using a modified version of the set style example with mapbox-gl-js v0.38.0: https://www.mapbox.com/mapbox-gl-js/example/setstyle/

HTML:
`  <ul style="padding-left:inherit;">
    <li><a class="btn-floating waves-effect waves-light" (click)="switchStyle('basic')"><img src="../../../assets/image/Map Layers/basicTheme.PNG" /></a> Basic</li>
    <li><a class="btn-floating waves-effect waves-light" (click)="switchStyle('bright')"><img src="../../../assets/image/Map Layers/brightTheme.PNG" /></a> Bright</li>
    <li><a class="btn-floating waves-effect waves-light" (click)="switchStyle('dark')"><img src="../../../assets/image/Map Layers/darkTheme.PNG" /></a> Dark</li>
    <li><a class="btn-floating waves-effect waves-light" (click)="switchStyle('light')"><img src="../../../assets/image/Map Layers/lightTheme.PNG" /></a> Light</li>
    <li><a class="btn-floating waves-effect waves-light" (click)="switchStyle('satellite')"><img src="../../../assets/image/Map Layers/satelliteTheme.PNG" /></a> Satelilite</li>
    <li><a class="btn-floating waves-effect waves-light" (click)="switchStyle('streets')"><img src="../../../assets/image/Map Layers/streetsTheme.PNG" /></a> Street</li>
  </ul>
</div>`

JS:
`    switchStyle(style) {
        this.map.setStyle('mapbox://styles/mapbox/' + style + '-v9');
        $('.fixed-action-btn').closeFAB();
    }`

After calling the switchStyle function to change the basemap and trying to use mapbox directions to place the origin and destination, I get the following error:

evented.js:104 The layer 'directions-route-line-alt' does not exist in the map's style and cannot be queried for features.
  | Evented.fire | @ | evented.js:104
-- | -- | -- | --
  | t.queryRenderedFeatures | @ | style.js:758
  | e.queryRenderedFeatures | @ | map.js:739
  | _move | @ | mapbox-gl-directions.js:7055
  | Evented.fire | @ | evented.js:87
  | h | @ | bind_handlers.js:139
  | a | @ | bind_handlers.js:75

I should be expecting the directions to work and showing me both the directions and alternate route. What I get is the map showing me it tried to get the route but ends up not showing anything at all.

Using Angular 4, Materalize CSS, JQuery, and TurfJS.

From what I understand, this is the same issue as this issue and wondering if a solution or work around has be implemented yet: https://github.com/alex3165/react-mapbox-gl/issues/129

**Comment by bslevine** [comment]
**Update:**Found a workaround for the mean time. Creating a settings page that 2-way binds the theme of the base map and then reloading the map page. It isn't ideal but its a temporary solution as it forces the map to be re-initialize with the directions api loading fresh instead of changing the base map and worrying about the direction layers being deconstructed.

**Comment by mollymerp** [comment]
I'm pretty confident this is an issue with your app and not with mapbox-gl-js. If the issue persists in a minimal test case without external frameworks/dependencies, please open a new issue.
