### ISSUE TITLE
Documentation doesn't mention multiple paint objects, but uses them in examples

### ISSUE THREAD

**Issue by calocan** [mapbox/mapbox-gl-js#5182]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Go to example: https://www.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/
 2. Find addLayer call with multiple paint properties
```
'paint': {
            // make circles larger as the user zooms from z12 to z22
            'circle-radius': {
                'base': 1.75,
                'stops': [[12, 2], [22, 180]]
            },
            // color circles by ethnicity, using data-driven styles
            'circle-color': {
                property: 'ethnicity',
                type: 'categorical',
                stops: [
                    ['White', '#fbb03b'],
                    ['Black', '#223b53'],
                    ['Hispanic', '#e55e5e'],
                    ['Asian', '#3bb2d0'],
                    ['Other', '#ccc']]
            }
        }
```
 3. Search the docs for an explanation of multiple paint properties. Search the docs for how to access and update multiple paint properties.

### Expected Behavior
The docs should clearly explain the option of defining a single object paint properties or multiple paint properties defined by different keys. The docs should then explain how to read and update the multiple paint properties.

### Actual Behavior
The docs seem to assume a single paint object that is not labeled with a key like  'circle-radius' or 'circle-color'. Simple functions like layer.getPaintProperty(layer, 'property') or layer.getPaintProperty('property') to access the name of the property don't work. 

Manipulating the paint properties seems fundamental to doing interesting things with the map. However there is no example that shows how to change the active paint property, handle multiple paint properties, etc.

**Comment by anandthakker** [comment]
Hi @calocan, thanks for using Mapbox.

The [documentation for `addLayer`](https://www.mapbox.com/mapbox-gl-js/api/#map#addlayer), links to the Mapbox style specification documentation for [layers](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers), which says of a layer's `paint` property:

> Paint properties appear in the layer's "paint" object.

Are these the parts of the documentation that you found unclear?  (Alternatively, if you didn't find these docs the first time you looked, can you point me to where your searches did take you?  This may help us improve the searchability/navigability of our documentation.)

**Comment by calocan** [comment]
Hi @anandthakker,

I understand that paint property belongs to the layer. But if you look at the Mapbox examples there is sometimes a paint property defined with multiple keys:

`'paint': { 
  // make circles larger as the user zooms from z12 to z22 
  'circle-radius': { 
    'base': 1.75, 
    'stops': [[12, 2], [22, 180]] 
   }, 
  // color circles by ethnicity, using data-driven styles 
  'circle-color': { 
    property: 'ethnicity', 
    type: 'categorical', 
    stops: [ ['White', '#fbb03b'], ['Black', '#223b53'], ['Hispanic', '#e55e5e'], ['Asian', '#3bb2d0'], ['Other', '#ccc']] 
  } 
}`

There is nothing in the API docs about how to ask the layer for it the 'circle-radius' object nor how to update it. There is no layer.getPaintObject('circle-radius').set('property', 'secondaryEthnicity'). The only thing in the API docs is layer.getPaintProperty, which seems to assume that paint looks like this:

`  'paint': { 
    property: 'ethnicity', 
    type: 'categorical', 
    stops: [ ['White', '#fbb03b'], ['Black', '#223b53'], ['Hispanic', '#e55e5e'], ['Asian', '#3bb2d0'], ['Other', '#ccc']] 
  } `

in which case layer.getPaintProperty('property') oddly still doesn't retrieve 'ethncity'. I believe the API lacks the ability to manipulate layer.paint objects  that have keyed paint objects within them. I also believe that the documentation uses examples of such paint objects, as above, but offers no examples of manipulating them. Does that make sense?

Thanks,
Andy

**Comment by andrewharvey** [comment]
Along with the [Style spec docs](https://www.mapbox.com/mapbox-gl-js/style-spec/) you might find it helpful to look at a full sample style like this one https://github.com/mapbox/mapbox-gl-styles/blob/master/styles/basic-v9.json

Your second code block isn't valid, the paint object must contain paint properties, here are the valid ones for `circle` layers https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-circle.

> There is nothing in the API docs about how to ask the layer for the 'circle-radius' object 

https://www.mapbox.com/mapbox-gl-js/api/#map#getpaintproperty

    map.getPaintProperty('layer', 'circle-radius')

> nor how to update it.

https://www.mapbox.com/mapbox-gl-js/api/#map#setpaintproperty

    map.setPaintProperty('layer', 'circle-radius', { 
        'base': 1.75, 
        'stops': [[12, 2], [22, 180]] 
    });

**Comment by calocan** [comment]
Hi @anandthakker,

Okay I finally understand. My problem was that the docs describe the following circle-color as a **property function**. I was confused because the definition of circle-color below is not a function, but naturally your code converts it into one. Thanks.

```
'paint': { 
  // make circles larger as the user zooms from z12 to z22 
  'circle-radius': { 
    'base': 1.75, 
    'stops': [[12, 2], [22, 180]] 
   }, 
  // color circles by ethnicity, using data-driven styles 
  'circle-color': { 
    property: 'ethnicity', 
    type: 'categorical', 
    stops: [ ['White', '#fbb03b'], ['Black', '#223b53'], ['Hispanic', '#e55e5e'], ['Asian', '#3bb2d0'], ['Other', '#ccc']] 
  } 
}
```

**Comment by Scarysize** [comment]
@calocan There is also documentation on those functions:
https://www.mapbox.com/mapbox-gl-js/style-spec/#types-function

Once you get a grasp, they become a very powerful tool 👍

**Comment by anandthakker** [comment]
Thanks for following up, all!

I'm going to close here, since the immediate question was addressed, and the underlying difficulty seems to been, in large part, the multiple meanings of "property" this context, which is probably not something we can act on in the near term.
