### ISSUE TITLE
Buggy dragging in the 'drag a point' example (Chrome Browser)

### ISSUE THREAD

**Issue by g-combs-hobsons** [mapbox/mapbox-gl-js#5187]
Buggy dragging in the "drag a point" example immediately after double clicking on the map to zoom in.

The behavior was previously logged in another bug ticket (#3352) that was closed due to being stale (@lucaswoj @mourner @mollymerp) but is repeatable today in Chrome. As a note, this has also been demonstrated as unexpected behavior on the draggable point example by multiple other individuals in my office on Chrome.

Mapbox GL Example:
https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/

Browser: Chrome Version 60.0.3112.101 (Official Build) (64-bit)
OS: Mac OS Sierra 10.12.3

### Steps to Trigger Behavior
1. After a fresh load of the page, hold down and drag the point to a new location (e.g. away from the center of the map)
2. Double click the map, near the pin, to zoom in.
3. Hold down and drag the point on the map (e.g. back to the center) and you'll see the point start to move before stopping, though you continue to hold down and drag the point.

### Expected Behavior
The point will be draggable across the map with the appropriate sequence of mouse move and mouse up events being fired to the handling methods.

### Actual Behavior
The point start to move with the drag before stopping and no longer firing the appropriate mouse move and mouse up events to the handling methods.

### Notes
There are no errors or warnings logged in the Chrome debugger console as this is happening to indicate a traceable issue.

From copying the sample code and testing it in Chrome I can see that the method responding to the mouse move is being called on just the first couple 'moves' of the point after zooming in w/a dblclick. It then suddenly stops being called though I continue to hold down and drag the point.

On an additional note, once I stop moving the point and let up on the mouse (mouse up), no mouse up event is fired (the mouse up method is not called). If I then click on the point again there are two mouse up events being fired (mouse up method is called twice back-to-back).

**Comment by g-combs-hobsons** [comment]
The details should be adequate for recreating this but if at some point it is needed for me to capture a screen cast of the steps on Chrome, please let me know.

**Comment by g-combs-hobsons** [comment]
Thank you @jfirebaugh

**Comment by g-combs** [comment]
This ticket is quickly approaching 30 days without any response and impacts behavior on the browser with the highest market share for us; in addition to being an issue that was previously identified and closed without a resolution or workaround. Has anyone in the community worked around this issue or found a solution for this?

**Comment by mourner** [comment]
@g-combs I can't seem to reproduce this at the current example page with 0.47.0. Can you try it now?
