### ISSUE TITLE
Why I am getting blank page for Mapboxgl api on IOS?

### ISSUE THREAD

**Issue by rajaa1985** [mapbox/mapbox-gl-js#5189]
Working on mapboxgl with ionic3, angular4 and cordova.

I have build .apk and .ipa files. I installed .apk file in my android device it works as expected (ie mapbox tiles, my icons (I have added some icons to custom some functionalities for eg. added an icon to switch the map style) and my markers are loaded successfully).

When I install the .ipa file in my Iphone my icons only loaded but mapbox tiles not getting loaded. Also the markers. I get blank white screen.

What is wrong with my implementation?

Please provide me the appropriate solution for this.

**Comment by jfirebaugh** [comment]
Hi @rajaa1985. Unfortunately, we're unable to debug highly-specific implementation issues such as this. If you think you've located a bug in Mapbox GL JS, please file a ticket, using the issue template provided, and provide a minimal, self-contained example that reproduces the issue independent of third-party frameworks or libraries such as ionic3, angular4 and cordova.

**Comment by rajaa1985** [comment]
**My html code**
<div id='map'></div>

**My Logic code in component**
let data = myJson data;

mapboxgl.accessToken = 'My access token';
    var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v9',
      attributionControl: false,
      center: [-74.50, 40],
      zoom: 12
    });

map.on('load', function () {
      map.addSource("place", {
        type: "geojson",
        data: data,
        cluster: true,
        clusterMaxZoom: 14, // Max zoom to cluster points on
        clusterRadius: 50 // Radius of each cluster when clustering points (defaults to 50)
      });

      map.addLayer({
        "id": "places",
        "type": "circle",
        "source": "place",
        "paint": {
          "circle-radius": 7,
          "circle-color": "#32CD32",
          "circle-stroke-width": 4,
          "circle-stroke-color": "#FFFFFF"
        }

      });
  
    });

Can you help with me with the code added here?

This code works fine in Android. I mean map is loading as expected. But in Iphone My app is working but Map is not loading. Any guess what is wrong?
