### ISSUE TITLE
Doccument how to remove filter

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#5194]
From [this question on StackOverflow](https://stackoverflow.com/questions/45820818/remove-filter-with-mapbox-gl-js), it seems there's no official way to remove a filter from a layer. However, `map.setFilter('mylayer')` works - so the doc should reflect that the second argument is optional, and calling the function without it removes the filter.

**Comment by mourner** [comment]
Yeah. It actually acts like `map.setFilter('mylayer', undefined)`. `null` works in that case as well.

**Comment by andrewharvey** [comment]
See also https://github.com/mapbox/mapbox-gl-js/issues/2638.

Closing as the [documentation fix is live now](https://www.mapbox.com/mapbox-gl-js/api/#map#setfilter). :tada:
