### ISSUE TITLE
TypeError: Cannot read property 'push' of undefined in VectorTileFeature.prototype.loadGeometry

### ISSUE THREAD

**Issue by sjsafranek** [mapbox/mapbox-gl-js#5198]
TypeError: Cannot read property 'push' of undefined in VectorTileFeature.prototype.loadGeometry

I am writing a VectorTile server for Perl and I am getting the following error when attempting to load a vector tile for a layer containing multiple Point features. On line 5082 it looks like the "line" variable is undefined --> line.push(new Point(x,y));.

The variables within the function are:
end = 1506
cmd = 2
pbf.pos = 20
x = -6
y = 4
lines = []
line = undefined

Thanks!

**Comment by jfirebaugh** [comment]
Hi @sjsafranek -- you haven't used the provided issue template so it's difficult to tell, but this doesn't sound like a mapbox-gl-js issue. If you think you've found a bug in mapbox-gl-js, please open a new issue, fill out the issue template completely, and provide a minimal self-contained example that demonstrates the issue. Thanks!
