### ISSUE TITLE
Sprite rendering broken on Android devices with devicePixelRatio 4

### ISSUE THREAD

**Issue by kristfal** [mapbox/mapbox-gl-js#5202]
### Steps to Trigger Behavior

View map with sprites on Android devices such as the LG-V20 and Samsung Galaxy S6 with devicePixelRatio 4

### Expected Behavior

Sprites are rendered properly

### Actual Behavior

Sprites are rendered as black boxes. See attached screenshot.

### Affected version

0.39.0 

This was working previously, possibly during 0.38.0 or 0.37.0. We're working with our customers to narrow down the issue and identify the breaking version.

Update: This is working in 0.37.0

![](https://downloads.intercomcdn.com/i/o/31001341/1da66cbd9dd5d804461fa2e6/Screenshot_20170812-080107.png)

**Comment by kristfal** [comment]
Just an update: Confirming that this was working in 0.37.0.

**Comment by dagjomar** [comment]
Probably has to do with the refactoring of how spritesheet and ImageAtlas is working?

**Comment by jfirebaugh** [comment]
I'm not able to reproduce this with Chrome Devtools's built-in device simulation with a `devicePixelRatio` 4. Will have to track down a physical device.

**Comment by kristfal** [comment]
@jfirebaugh yes, I couldn’t reproduce myself in Chrome. 

Also, I’m not seeing the issue on an S7 with DPR 4, and given the user’s screenshot, I’m having a feeling he have enabled some kind of screen magnification that may be the culprit. 

We’ve bought an S6 and waiting for it to arrive. I’ll get back to you with details when I’ve tested myself.

**Comment by jfirebaugh** [comment]
@kristfal Any additional information?

**Comment by Scarysize** [comment]
Not sure if this plays in here, but we had issues with sprites not being rendered when the DPR isn't an integer value. We actually so black boxes as in the screenshot above for very high DPR values (>10) and sprites not showing up at all for non-integer values (not even black boxes).

What works great for simulating DPRs is headless Chrome using Puppeteer https://github.com/GoogleChrome/puppeteer (see `Page#deviceScaleFactor`)

**Comment by kristfal** [comment]
@jfirebaugh Hey! Sorry for the slow reply. We managed to get our hands on a S6 and gave it a spin. Given the screenshots from our user, he seem to have activated some kind of Android screen magnification / text size adjustments.

We tried all combinations of text and screen sizes, but couldn't reproduce the issue on our S6 using the latest release of mapbox-gl-js. We also haven't heard back from the user, so I think you can close this, and I'll re-open if we get encounter similar issues or can reproduce on our end.

**Comment by jfirebaugh** [comment]
Thanks!
