### ISSUE TITLE
Add a style property to prevent symbols from being rendered upside down when a certain rotation is applied to it

### ISSUE THREAD

**Issue by bart-1990** [mapbox/mapbox-gl-js#5203]
## Motivation

Suppose you have a feature of the type 'symbol' with the icon of a car which you want to align with the direction it is driving. It's already possible to use the icon-rotate property to rotate the icon to do so. However, once the rotation passes 180 degrees (supposing the car icon is pointing north at a rotation of 0 degrees) the car icon will be rendered upside down. At that point it should be possible to mirror the icon to prevent this from happening.

## Design Alternatives

Add a lay-out option to prevent an icon from begin rendered upside down once it's rotated more than x degrees.

<img width="233" alt="screen shot 2017-08-29 at 14 38 35" src="https://user-images.githubusercontent.com/7540719/29821320-c848354a-8cc7-11e7-9e85-0da802821260.png">

**Comment by mourner** [comment]
Closing as stale — looks like there's not enough demand to implement this.
