### ISSUE TITLE
mapbox v0.23.0 link gives 0.24.0

### ISSUE THREAD

**Issue by divya1c** [mapbox/mapbox-gl-js#5204]
**mapbox-gl-js version**: 0.23.0
I've been encountering weird bugs in my code because of this.

### Steps to Trigger Behavior
 1. Go to https://api.tiles.mapbox.com/mapbox-gl-js/v0.23.0/mapbox-gl.js or link it in any html

### Expected Behavior
Gets v0.23.0 of mapbox gl library

### Actual Behavior
Gets v0.24.0 mapbox gl library.

**Comment by jfirebaugh** [comment]
I think this was an error in the publishing process. Unfortunately, we can't change it, as users may be depending on the existing link. I recommend you upgrade to a recent version in any case -- 0.23.0 and 0.24.0 are a year old.
