### ISSUE TITLE
Map click events are not always reliable

### ISSUE THREAD

**Issue by shongololo** [mapbox/mapbox-gl-js#5205]
I am finding that when using a mouse event on the map, e.g.:
```
webglmap.once('click', () => { console.log('clicked') })
```
The corresponding behaviour / response is not always reliable and sometimes requires two or three clicks before an event properly fires.

Is this a bug or more likely something to do with implementation?

**Comment by jfirebaugh** [comment]
@shongololo It's hard to say in the abstract. Could you create a minimal self-contained example that demonstrates what you're seeing?

**Comment by shongololo** [comment]
Unfortunately the project setup and interaction is fairly involved but I'll see if I can find a way to distill the issue. Thanks.

**Comment by jfirebaugh** [comment]
Thanks, let us know if you do.
