### ISSUE TITLE
Support array of layers for map.on

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#5211]
Currently you can do this:

```
    map.on('mouseenter', 'my-points', function(e) {...});
```

But if you want the same behaviour on multiple layers, you can't do it directly:

```
   var f = function(e) {
    ...
   };
    map.on('mouseenter', 'my-points', f);
    map.on('mouseenter', 'my-other-points', f);
```

It would seem reasonable to expect to be able to do:

```
    map.on('mouseenter', ['my-points', 'my-other-points'], function(e) { ... })`
```

**Comment by jfirebaugh** [comment]
See #4578 for why we elected not to support this.

**Comment by stevage** [comment]
Ok, thanks for the link.

**Comment by Stephane-Ag** [comment]
The [documentation](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#on) makes it seem like this is now a feature but it does not work for me. I have "mapbox-gl": "1.6.1".
What version was this introduced? Any link to a new PR with why it was eventually added?

**Comment by stevage** [comment]
@Stephane-Ag You are many major versions behind the latest release.

**Comment by Stephane-Ag** [comment]
@stevage I know that which is why I included my version. That answer does not help with either of my questions.
