### ISSUE TITLE
NavigationControl Maximum call stack

### ISSUE THREAD

**Issue by qiaolei1973** [mapbox/mapbox-gl-js#5212]
when i drap the map use NavigationControl. 
![image](https://user-images.githubusercontent.com/20394320/29913716-83886b4e-8e68-11e7-9b0a-a234548ae0a1.png)

**Comment by jfirebaugh** [comment]
Hi @qiaolei1973, thanks for the report. This issue was fixed by #5157, and this fix will be in the next release.
