### ISSUE TITLE
Getting Projection-Matrix for WGS84 from the transform objection

### ISSUE THREAD

**Issue by jacmendt** [mapbox/mapbox-gl-js#5213]
Hello MapboxGl-Team and thanks for the great work you are doing. I use mapbox-gl-js as my basic mapping engine and try to display on top of it different area interpolations based on WebGL. I already had some good results for me and now I want to do some distance calculation with the [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula) within my shaders. 

For this to happen, I need to transform my pixel coordinates within the shaders to WGS84 coordinates. I saw that you offer within the `transform` object in mapbox-gl-js events already a couple of transformation matrix like the `pixelMatrix`, `pixelMatrixInverse` and `projMatrix`. But this transformation matrices does not seem to help me on transforming pixel coordinates to WGS84 or the other way around. 

Is there an easy way for me to get such a matrix from the `transform` object or another part of the mapbox-gl-js library? Or do I have to calculate it by myself?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
