### ISSUE TITLE
collision debug removed after v0.11.1 ?

### ISSUE THREAD

**Issue by Roxyi** [mapbox/mapbox-gl-js#5217]
Hi, I noticed that there is an example about adding collision debug to the map here: http://jsfiddle.net/3k3cxrrq/

However, when I changed mapbox-gl.js to current version which is v0.39.1, the collision debug disappeared.

Is there a way use collision debug in the current version of mapbox-gl.js?

**Comment by jfirebaugh** [comment]
It's `map.collisionBoxes` now: http://jsfiddle.net/ywnovxrw/

**Comment by Roxyi** [comment]
@jfirebaugh  Thank you!
