### ISSUE TITLE
Add detail to Expressions section of style-spec documentation

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5219]
- [x] Narrative intro section with a couple examples
- [x] High level description of type system, assertions vs. coercions
- [x] `curve` details
- [x] `match` details
- [x] `let` details
- [x] `coalesce` details
- [x] details about type coercion rules (per https://github.com/mapbox/mapbox-gl-js/issues/5219#issuecomment-339164651)

**Comment by davidtheclark** [comment]
@anandthakker How about more explanation in the coercion section about what types get coerced in what ways? I'm wondering about questions like the following: Will the boolean `true` be coerced to the number `1`, or error? Will the string `700px` be coerced to the number `700`, or error? Do all non-empty strings coerced to booleans become `true`? Basically: How close are these rules to the rules of coercion in JavaScript?

**Comment by anandthakker** [comment]
👍 good call @davidtheclark, i'll add it to the list in the top of the ticket

**Comment by jfirebaugh** [comment]
I think these are all addressed now -- followup issues are #5500 and #5685.
