### ISSUE TITLE
Drop the `{ expression: }` wrapper object for expressions used in layout/paint properties

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5222]
@jfirebaugh had  💡realized 💡  that, except for font stack arrays, expressions are always distinguishable from other literal arrays that might currently be used as style properties.  Since it's very unlikely that anyone's using a font whose name clashes with one of our expressions, this means that we can drop the wrapper object, e.g.: `circle-color: { expression: [ 'to-color', ['get', 'x'] ] }` => `circle-color: [ 'to-color', ['get', 'x'] ]`

**Comment by anandthakker** [comment]
cc @nickcordella @aparlato

**Comment by mourner** [comment]
BTW, in a similar vein, could we drop array wrappers for some predefined values like `["properties"]`, `["zoom"]` etc.? So that array would still be accepted in case we want to add options in future, but a string literal too.

**Comment by jfirebaugh** [comment]
My worry with that is that there may be contexts (either with the expression forms we have now, or with ones we add in the future) where both a string literal and `["properties"]`/`["zoom"]` are plausible arguments. Then the user would have to disambiguate by using brackets or not, and that would be confusing for someone who is not aware of the ambiguity. I'd prefer to keep it unambiguous all the time.
