### ISSUE TITLE
Recover stop functions performance after switching to expressions

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#5224]
#4777 converts stop functions to expressions under the hood, but the latter are roughly 30x slower to execute based on a simple Node benchmark like this (update: 13x slower after recent PRs):

```js
var fn = createFunction({
    'base': 1.75,
    'stops': [[0, 1], [22, 10]]
}, {default: 1});

console.time('fn');
for (var x = 0, sum = 0; x <= 22; x += 0.00001) {
    sum += fn({zoom: x});
}
console.timeEnd('fn');
```

It would be great to optimize this before release. Currently the generated code looks like this: 

```js
(function coalesce() {
    try {
        var result = $this.evaluateCurve(
            $globalProperties.zoom,
            [0, 22],
            [
                function() { return 1; }.bind(this),
                function() { return 10; }.bind(this)
            ],
            {name: 'exponential', base: 1.75},
            'number'
        );
        if (result !== null) return result;
    } catch (e) {}
    return 1;
})();
```

Two things that would probably help us get there are:

1. Get rid of `try/catch` in `coalesce` (or of `coalesce` in `curve`).
2. Get rid of binded function wrappers for constants.
3. Get rid of the IIFE wrapper if possible.

@anandthakker @jfirebaugh

**Comment by anandthakker** [comment]
@mourner I'm wary of node benchmarks, because some of the `assert` statements I have in the expressions code could be sort of costly.  As part of this work, maybe we should add a dedicated 'function evaluation' benchmark to the in-browser benchmark suite

**Comment by mourner** [comment]
@anandthakker I made a minified production bundle from the function code for the benchmark to make sure asserts don't contribute to the benchmark results.

**Comment by mourner** [comment]
@anandthakker looks like a new `evaluationContext` is [created on every call](https://github.com/mapbox/mapbox-gl-js/blob/9ee7362a7540ec6f489658806ffd53794e61e135/src/style-spec/function/compile.js#L78). Is there a way to avoid that? Putting it outside the closure (coupled with previous speedups) brings us down to 2x slowdown vs original stops implementation — not that bad.

**Comment by anandthakker** [comment]
Oh, good catch @mourner.  The state currently maintained in `evaluationContext` is a cache of `UnitBezier` objects and parsed colors, so there should be no problem moving it out -- and, indeed, reusing those colors could really help in color functions.

**Comment by jfirebaugh** [comment]
We switched back to the old code for functions while expressions mature, but performance of converted functions is now on par or better. Here I've modified the `FunctionEvaluate` benchmark to use a converted function on the right: https://bl.ocks.org/anonymous/raw/145d5eb126df41c535a545835b153c44/
