### ISSUE TITLE
improve layer opacity performance

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#523]
- [x] check if the memory for the render textures is reallocated on each frame (we were!)
- [ ] render the composited layer into the texture right before using it, not at the start of the layer group. This should reduce the number of render textures needed by a lot

Also, we should think more about how we can prevent double drawing without rendering into a texture. With the depth buffer we can prevent double drawing, but this falls apart near edges where we have antialiasing. We could draw antialiasing for lines in a separate draw calls to solve this problem for a single layer, but overlapping lines with different colors would still be aliased where they meet. We should also check whether availability and performance of msaa is good enough that we could drop our own antialiasing.

**Comment by AbelVM** [comment]
Any news on getting composite layers bac... like 6 years later?

[luma.gl ](https://luma.gl/ ) is enabling `comp-op` blending modes in WebGL and I can't find any performance hit while using it. Blending modes by luma.gl can be tested while within kepler.gl indeed
