### ISSUE TITLE
Move Typescript type definition files to mapbox-gl-js

### ISSUE THREAD

**Issue by alex3165** [mapbox/mapbox-gl-js#5239]
I would like to suggest to move the type definition file from [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mapbox-gl) to this repository.

This way, there is a possibility to reflect an API change on the type definition files straight away in the same PR without overhead.

I would also suggest to use [typings-tester](https://github.com/aikoven/typings-tester) to run the tests for the type definition file.

**Comment by mourner** [comment]
Thanks for the suggestion! However, unfortunately no one from the Mapbox GL JS team uses TypeScript (we prefer Flow), which means that the maintainers of this repo won't be able to maintain the TypeScript definitions properly. And we don't want to host something we won't be able to commit to maintaining. Let's keep it in DefinitelyTyped for now.

**Comment by sheerun** [comment]
@mourner Maybe it's good time to reconsider switching to typescript? Many projects are using typescript instead of flow so your flow definitions aren't as useful for other developers

**Comment by sheerun** [comment]
many projects like e.g. Jest switched

**Comment by mourner** [comment]
We are considering it, but won't act on this any time soon. Rewriting such a complex codebase is an enormous lift, and our team doesn't have the resources for it at the moment — there are higher priority things to work on.
