### ISSUE TITLE
Don't redo placement for zoom-only changes of an unpitched map

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5248]
While profiling #5208 (https://jsfiddle.net/w2frv0ns/), I noticed frequent calls to `redoPlacement` happening on the worker during the zoom animation.

![image](https://user-images.githubusercontent.com/98601/30128113-469f5296-92f6-11e7-9fb0-10b4bace2ff4.png)

Redoing placement was not previously necessary for zoom-only changes, and according to @ChrisLoer, still shouldn't be necessary if the map is not pitched. Therefore this is a performance regression we should fix.

**Comment by jfirebaugh** [comment]
@ChrisLoer Can you take a look? I think this may be a significant performance regression.

**Comment by ChrisLoer** [comment]
@jfirebaugh Yeah, I can put together a quick PR that just skips the zoom-triggered placement in when pitch is low-to-zero. The code will be superseded by #5150 when that lands.
