### ISSUE TITLE
LngLatBounds: Mismatch between doc and actual code

### ISSUE THREAD

**Issue by Wykks** [mapbox/mapbox-gl-js#5249]
**mapbox-gl-js version**: v0.39.1

### Expected Behavior

From the docs, LngLatBounds constructor (and convert) take a LngLatBoundsLike which is "A LngLatBounds object or an array of LngLatLike objects in [sw, ne] order."

### Actual Behavior

The LngLatBounds constructor (and convert), can take an array of four coordinate as well:
https://github.com/mapbox/mapbox-gl-js/blob/a7ef1498dda23980a3d7745b38641238c36ddd97/src/geo/lng_lat_bounds.js#L34
Which is actually convenient when using `@turf/bbox`, but it should be documented accordingly.

**Comment by mourner** [comment]
Good catch! Want to submit a PR with the docs fix?

**Comment by andrewharvey** [comment]
Sorry to overload this issue, but I wanted to chime in that I find the current description of "array of LngLatLike objects in [sw, ne] order" confusing, as GL JS uses LngLat, so for me `[ws, en]` is clearer as it shows the longitude before the latitude, unlike the current description.

I get that in this case it's explaining the order of the two corner points of the bounds so it's technically correct, but still I found it confusing for when trying to construct the bounds object.

**Comment by andrewharvey** [comment]
> The LngLatBounds constructor (and convert), can take an array of four coordinate as well:

This is actually documented under [LngLatBoundsLIke](https://www.mapbox.com/mapbox-gl-js/api/#lnglatboundslike) "_or an array of numbers in [west, south, east, north] order._" added in https://github.com/mapbox/mapbox-gl-js/commit/2a4e81796b902b03d6ef2faa317febc5ad32ca12. @Wykks do you think that's enough or it should also be documented at LngLatBounds?

**Comment by mollymerp** [comment]
I believe we kept the option to use an array of 4 coordinates in order to maintain backward compatibility, but we wanted to eventually deprecate this and make the constructor less flexible.

https://github.com/mapbox/mapbox-gl-js/blob/a7ef1498dda23980a3d7745b38641238c36ddd97/src/geo/lng_lat_bounds.js#L28-L29

**Comment by Wykks** [comment]
@andrewharvey Totally good for me, thanks! :)

@mollymerp But as I said in the first post of this issue, this format is useful when you use `@turf/bbox` 😿
