### ISSUE TITLE
Google-Chrome v59 crash on Android Mobile  

### ISSUE THREAD

**Issue by knigal** [mapbox/mapbox-gl-js#5251]
How to trigger:

1. Get a Xiaumi Redmi 4X phone (or equiv), running chrome v59 
2. On device, use Chrome to pen https://www.mapbox.com/mapbox-gl-js/examples
3. Use map for a minute or two: zoom in/out, pan, rotate
4. Boom! chrome crashes (see screenshot)

Expected result: chrome should stay alive and allow further interaction with map =)

Note:
I have devtools connected via remote debug to device's chrome page. When the page crashes, I didn't see an error. It disconnects when the page cash occures

![2017-09-07 14 16 30](https://user-images.githubusercontent.com/1245766/30161057-bd76f2b6-93d7-11e7-9b38-48b85ba44455.png)
![2017-09-04 19 47 57](https://user-images.githubusercontent.com/1245766/30161055-bd566906-93d7-11e7-9620-904bd4300764.png)
![2017-09-04 20 55 09](https://user-images.githubusercontent.com/1245766/30161054-bd50e670-93d7-11e7-9315-2241d9ac083e.png)
![2017-09-04 21 02 53](https://user-images.githubusercontent.com/1245766/30161056-bd61dcd2-93d7-11e7-8071-ed36c71e0ca9.png)

**Comment by jfirebaugh** [comment]
Thanks for the report @knigal. A browser crash like this is almost always a bug in the browser itself, pretty much by definition. There shouldn't be any way that client side JS can trigger a browser crash, and if there is it's usually considered a security issue (DOS). I would encourage you to file an issue in the [chromium issue tracker](http://dev.chromium.org/for-testers/bug-reporting-guidelines). I'm going to close here as this is not likely to be something we can fix on the Mapbox GL side.

**Comment by knigal** [comment]
@jfirebaugh is it not possible that under certain conditions, there's a memory leak on the `mapboxgl.js` side, which then ends up triggering the browser out of memory and "crash" action? 
In such cases, the browser is taking the "right action" by shutting down the tab and displaying the "page crashed" message. If that's the case, the fix would definitely be on the mapboxgl.js side. Would you disagree?
