### ISSUE TITLE
Possible memory leak when setData with GeoJSON

### ISSUE THREAD

**Issue by alex2wong** [mapbox/mapbox-gl-js#5252]
**mapbox-gl-js version**:  0.39.1

### Steps to Trigger Behavior

 1. open https://alex2wong.github.io/mapbox-plugins/examples/hexgrid/
 2. try dragging and zooming the map
 3. updating hexgrid layer data would cause memory increase concerning Actor.js
 4. wait several mins, the memory would go up.. to 2GB or 3GB util crash.

### Expected Behavior
memory retain normal.
### Actual Behavior
this tab's memory cost somtimes may increase to to 1GB

Use Chrome(v61) performance debug tool to track the call stack, it seems geojson_source related code would call actor.js to perform multi-thread calculation.. I've heard about actor model somtimes would go out of control and create many subactor which means it may cause memory leak. Correct me if I am wrong.

Actually ,updating to latest mapbox-gl.js performs better than old version. But it still has something wrong with the memory, and the map would gets slow or crash when memory leaks.

![memoryleak4](https://user-images.githubusercontent.com/10528482/30164637-c2666710-940f-11e7-9e98-a9e396b75bc5.jpg)

Thanks! mapbox is brilliant : )

**Comment by jfirebaugh** [comment]
I'm not able to reproduce the behavior you are describing. I see a sawtooth pattern to memory use, where growth is followed by a GC event:

![image](https://user-images.githubusercontent.com/98601/30184952-8415b7f8-93d4-11e7-999b-765e8f6855cc.png)

**Comment by alex2wong** [comment]
@jfirebaugh  yes, you're right, the GC have collect some of mapbox related object normally, which indicated by the sawtooth pattern. This shows the js heap( max value 168Mb) seems right. But the total memory (over 3GB) this tab occupied keeps increasing as time goes by. attach chrome task screenshot:

![memory_jsheap](https://user-images.githubusercontent.com/10528482/30190999-c1dd0d2e-9470-11e7-8852-18a04c3fd3d5.png)

Do you have any idea why the total memory keeps increasing ? I just drag and zoom for a while.

**Comment by ThiyagarajanShivSankaran** [comment]
@alex2wong Did this issue fixed for you. For me not 😞.

**Comment by alex2wong** [comment]
closed since this does not happen frequently in later tests. thx
