### ISSUE TITLE
Any info on release schedule?

### ISSUE THREAD

**Issue by jliebrand** [mapbox/mapbox-gl-js#5254]
Sorry, this isn't really a bug, but I made a comment on a closed bug last week (#4262) and I'm not sure people get notifications on closed bugs?

Basically, I'm curious to know when the next release is scheduled. In particular to try the fix for issue 4262, but also in general: do you have a roadmap or a schedule I can see to plan for updates?

**Comment by anandthakker** [comment]
Hi @jliebrand,
We don't have a formal release schedule, but we generally try to publish a release approximately once every 1-2 months.  We're hoping to do the next one very soon, but have a [few issues that need to be resolved](https://github.com/mapbox/mapbox-gl-js/labels/release%20blocker) before we can do so.

**Comment by jliebrand** [comment]
Ah "release-blocker"... that helps, thanks.

Look forward to seeing an update; been seeing a lot of great fixes come in!

**Comment by andrewharvey** [comment]
> do you have a roadmap or a schedule I can see to plan for updates?

https://www.mapbox.com/mapbox-gl-js/roadmap/
