### ISSUE TITLE
Simple method for animating png/marker icon along linear path (Geojson: point-a to point-b)

### ISSUE THREAD

**Issue by veratechnz** [mapbox/mapbox-gl-js#5264]
Have used the docs and demo [animation-boilerplates ](https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-route/) but am struggling to animate my current marker. It is a dynamically generated png that updates position every second (setInterval). The change is quite small/short (less than 1km) but I am keen to animate along a linear path to the updated coordinate. 
  
```
        map.on('load', function () {

              var num = key.toString();
              // create a HTML element for each feature
              var el = document.createElement("img");
              el.src = 'assets/img/car-' + num + '.png';

              //Code above creates inline image for map placement
              setInterval(function(){

                // make a marker for each feature and add to the map
                var cars = new mapboxgl.Marker(el, { offset: [-50 / 2, -50 / 2] })
                .setLngLat(geojson.cars[key].geojson.geometry.coordinates)
                .addTo(map);

              }, 1000); // setInterval Ends
```

**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1.
 2.
 3.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
