### ISSUE TITLE
styledataloading  event not implemented

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#5267]
**mapbox-gl-js version**:
0.39.1

I'm trying to implement a progress bar for when tiles are requested and then ultimately rendered to the map. 

From the docs, the `styledataloading` and `styledata` events looks like a promising signal for when a tile request is made and rendered, however it does not look like `styledataloading` has been implemented! 😄 

Searching the repo for the term `styledataloading` shows it's been defined, but not implemented in the library code.
https://github.com/mapbox/mapbox-gl-js/search?utf8=%E2%9C%93&q=styledataloading&type=

JSBin:  https://jsbin.com/dilafolifi/1/edit?js,output

**Comment by mollymerp** [comment]
hi @DannyDelott – it actually is implemented: https://jsbin.com/qilekilato/edit?js,output 
here's the code: https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/map.js#L1712

**Comment by mollymerp** [comment]
> From the docs, the styledataloading and styledata events looks like a promising signal for when a tile request is made and rendered

If you're interested in tile loading / loaded events you should listen for [`sourcedata`](https://www.mapbox.com/mapbox-gl-js/api/#map.event:sourcedata) and [`sourcedataloading`](https://www.mapbox.com/mapbox-gl-js/api/#map.event:sourcedataloading) with `e.tile` defined in the event
