### ISSUE TITLE
loading json style via URL results in XML error logged to console 

### ISSUE THREAD

**Issue by dieterdreist** [mapbox/mapbox-gl-js#5270]
I get "XML-Verarbeitungsfehler: nicht wohlgeformt
Adresse: file:///Users/foo/Documents/js/no_map.json Zeile Nr. 1, Spalte 1:" 
(in English: "XML-Parsing error: not wellformed, Address: file:///Users/foo/Documents/js/no_map.json 1 1).

As this is a json file it is no surprise it isn't a wellformed XML.

I'm loading it like this:
map.setStyle('js/no_map.json', { "diff": true });  // (relative URL to a json)

The json is passing all lint tests without a problem. It is working (the map sets the style), just that I get this malformed XML error in the console. (I don't get the errror for styles I load with the same command from mapbox with a string like "mapbox://styles/myUsername/myStyleID")

**Comment by jfirebaugh** [comment]
Mapbox GL JS doesn't support `file://` URLs due to weird issues like this. Please host the `no_map.json` somewhere -- possibly using a local HTTP server -- and load it via a `https://` or `http://` URL.
