### ISSUE TITLE
On Safari 11+, fullscreen mode is distorted

### ISSUE THREAD

**Issue by aparajita** [mapbox/mapbox-gl-js#5273]
**mapbox-gl-js version**:

0.39.1

### Steps to Trigger Behavior

 1. Open https://www.mapbox.com/mapbox-gl-js/example/fullscreen/ in Safari 11+.
 2. Click on the fullscreen control.

### Expected Behavior

Map is scaled properly.

### Actual Behavior

Map is stretched horizontally. You can see that easily by looking at the labels.

I checked in Safari 9.1 and it works correctly.

**Comment by jfirebaugh** [comment]
It works correctly in Safari 10 too, so this is probably a regression in Safari. Have you opened an issue in the Apple bug reporter?

**Comment by aparajita** [comment]
Not yet, I wasn't sure if it was a Safari bug or not. Since the bug isn't there in 10 and is in Safari TP, it must be a webkit regression.

**Comment by aparajita** [comment]
Reported to both Apple and WebKit.org.

**Comment by ashleyclough** [comment]
I fear there may be more to the problem:

Go to the full screen demo in Safari 10.1.2 on an iMac 17 inch retina display and the full screen image is very obviously distorted, the same full screen view in Chrome 61 displays correctly.

Safari:
![full screen safari](https://user-images.githubusercontent.com/912721/30396047-2aa27a6c-98c0-11e7-940b-e8e4c8fded37.jpg)

Chrome:
![full screen chrome](https://user-images.githubusercontent.com/912721/30396064-358d6d6a-98c0-11e7-960c-fcb2c0ab5c1a.jpg)

**Comment by aparajita** [comment]
@jfirebaugh Did you test on a Retina or non-Retina display?

**Comment by ashleyclough** [comment]
Retina - shows a canvas of 5120 x 2880 px.

**Comment by aparajita** [comment]
Screen aspect ratio may have something to do with it. Seems like it's working correctly on displays with an aspect ration of 1.6, but is stretched on displays with an aspect ratio of 16:9.

**Comment by aparajita** [comment]
Here's the WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=176841

**Comment by anandthakker** [comment]
👍 thanks for filing the WebKit issue @aparajita

**Comment by jfirebaugh** [comment]
You may be hitting `gl.MAX_RENDERBUFFER_SIZE` like in #2673. If so, I'm afraid this is something we're not going to be able to fix.

**Comment by aparajita** [comment]
Nope, the image is crisp, just stretched. I did some more investigation and it has to do with the aspect ratio of the display, but only at certain resolutions. See the [Apple bug report](https://bugreport.apple.com/web/?problemID=34410953) for more info.

**Comment by mourner** [comment]
Closing as a browser bug we can't address on our side. Let's hope the Safari team fixes it soon.
