### ISSUE TITLE
Identical Lat/Long Data points do not overlap in UI

### ISSUE THREAD

**Issue by bfuerst** [mapbox/mapbox-gl-js#5275]
Hi,

We have two datapoints with identical Lat/Longs and expect them to overlap but in our Mapbox GL (https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.js) web UI the points are slightly separated. Attached is an example of what it looks like in the UI when it is zoomed in.

Ex - https://image.ibb.co/fQdKuv/2017_08_11_13_33_14.jpg
2017_08_11_13_33_14

Steps to trigger behavior

Load two points with identical lat/longs from two different datasets
Convert both datasets to tilesets
Layer the two tilesets in a style
Apply style to web map
Zoom into Lat/Long and the identical points do not overlap
Expected behavior

Points with identical lat/longs would overlap

Actual behavior

Points with identical lat/longs do not overlap

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained JSFiddle that demonstrates the issue?
