### ISSUE TITLE
mapboxgl undefined when loading the Mapbox GL Library dynamically

### ISSUE THREAD

**Issue by meghamukim** [mapbox/mapbox-gl-js#5276]
I am trying to include the MapboxGL library dynamically in my JS file using Dojo syntax. I make sure I call the respective function using the Mapbox APIs after the library has loaded by using the 'onload' attribute. I include this script tag in the <head> section.

var script = domConstruct.create("script",{type: "text/javascript", src: "https://api.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.js",
                    onload: this._instantiateMap.bind(this,target, l, r, t, b)});

But when I try to access in the first line of the function:
mapboxgl.accessToken = <accesskey>;

This gives me the error below:
**DisplayWidget.js:282 Uncaught ReferenceError: mapboxgl is not defined
    at Object._instantiateMap **

To confirm that I face this only with Mapbox file, I tried to include jQuery file dynamically and it works fine.

Any help would be appreciated! I have been stuck because of this past 2  days !!!

**Comment by jfirebaugh** [comment]
Are you using require.js? See #5110.

**Comment by meghamukim** [comment]
No I am not using Require.js. We use Dojo framework for the application at work. Also, it works perfectly fine when I include it statically in my HTML file in the <head> section.

**Comment by jfirebaugh** [comment]
Ok. Unfortunately, we don't have the resources to debug interactions with 3rd party libraries, as they are rarely issues with Mapbox GL JS itself, but rather configuration and setup issues that are beyond our control. If you can reduce this to a minimal test case that shows the error lies in Mapbox GL JS itself, let us know.

**Comment by meghamukim** [comment]
I am not sure how it is not clear that the issue is with the loading of Mapbox GL JS. I mentioned that to be sure there are no issues on my end I also used the same code to include jQuery library dynamically and that seems to work fine. I am confused why will Mapbox GL not be loaded if other 3rd party libraries are loaded!

**Comment by valentinbdv** [comment]
Exact same problem here, can't load mapboxgl dynamically. ;/

**Comment by brian-brss** [comment]
The same issue when I tried to load Mapbox gl into the Episerver widget(dojo-based widget).
