### ISSUE TITLE
Refactor texture-related classes

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5277]
#5101 introduced [`RenderTexture`](https://github.com/mapbox/mapbox-gl-js/blob/c462e30c0468f07c0eb48d693fd4c4e47fbaa660/src/render/render_texture.js) and #5190 introduced [`Texture`](https://github.com/mapbox/mapbox-gl-js/blob/6658c470e7df709b0c95f16b9e0340ccd2977574/src/render/texture.js). There's also #4811, an older take on the same idea by @mourner, and existing code that uses texture-related WebGL calls directly without using either class.

We should refactor and sort this out. Here's my proposed design:

* We need a state-tracking wrapper like gl-native's [`gl::State<T>`](https://github.com/mapbox/mapbox-gl-native/blob/bed96c800cac49a14957954d9ae8e71ec2c46b9a/src/mbgl/gl/state.hpp) and associated [value traits](https://github.com/mapbox/mapbox-gl-native/blob/bed96c800cac49a14957954d9ae8e71ec2c46b9a/src/mbgl/gl/value.hpp).
* However, the way that native does texture binding is not quite right. All that should be publicly exposed are property setters and methods on the `Texture` class. Internally, a property setter should:
  1. Check the tracked state, and exit if it's a redundant operation.
  2. If not, then check that tracked state of the texture binding for the current texture unit. If changing that is a redundant operation skip it, otherwise bind the texture.
  3. Update the state.
* For texture handling that's not connected to a draw call (e.g. stuff that happens in the upload step), just always use texture unit 0. For texture handling during a draw call, there should be a way of supplying `Texture` references as the value of uniforms, and having the internals handle assigning unique texture units, binding the textures, and setting the unit identifiers with `glUniform*`.

**Comment by ryanhamley** [comment]
Closing as outdated
