### ISSUE TITLE
MarkerView change order when move or zoom

### ISSUE THREAD

**Issue by PhanVanLinh** [mapbox/mapbox-gl-js#5287]
**com.mapbox.mapboxsdk:mapbox-android-sdk:5.0.2@aar*:

### Steps to Trigger Behavior

 1. Create a simple demo
 2. Add more than 20 markers in Map
 3. Move or zoom

### Expected Behavior
MarkerView should not change order when move or zoom
### Actual Behavior
MarkerView change order when move or zoom

![ezgif-1-bfa350ff48](https://user-images.githubusercontent.com/15084259/30409472-6d175f6a-992f-11e7-8e1e-fd7c89330250.gif)

**Comment by jfirebaugh** [comment]
Hi @PhanVanLinh. Bugs in the Mapbox Android SDK should be filed in https://github.com/mapbox/mapbox-gl-native. This is the repository for Mapbox GL JS, the web SDK.

**Comment by AliTaheriNastooh** [comment]
If you use PointAnnotation, this behavior doesn't occur
