### ISSUE TITLE
texImage2D/texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads

### ISSUE THREAD

**Issue by rofrol** [mapbox/mapbox-gl-js#5292]
- Include a link to a minimal demonstration of the bug.
https://www.mapbox.com/mapbox-gl-js/example/geojson-line/
 - Check the console for relevant errors and warnings

```
Loading failed for the <script> with source “https://assets.customer.io/assets/track.js”.
geojson-line:1
Loading failed for the <script> with source “https://s.adroll.com/j/roundtrip.js”.
geojson-line:1
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:47:4
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
line_atlas.js:139:12
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
line_atlas.js:146:16
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
frame_history.js:70:8
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
frame_history.js:75:12
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:47:4
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
line_atlas.js:146:16
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
frame_history.js:75:12
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:47:4
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
line_atlas.js:146:16
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
frame_history.js:75:12
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:47:4
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
frame_history.js:75:12
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:47:4
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
frame_history.js:75:12
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
frame_history.js:75:12
Error: WebGL: No further warnings will be reported for this WebGL context. (already reported 32 warnings)
frame_history.js:75:12
```

**mapbox-gl-js version**: from website

### Steps to Trigger Behavior

1. Open Firefox
  - Firefox 57.0a1 (2017-09-12) (64-bit)
  - Linux 4.10.0-33-generic #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
 2. Go to https://www.mapbox.com/mapbox-gl-js/example/geojson-line/

### Expected Behavior
Shows example

### Actual Behavior
Empty section with example

**Comment by jfirebaugh** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1400077

**Comment by yuvadm** [comment]
@jfirebaugh Looks like a WONTFIX. Should probably be fixed elsewhere?

**Comment by localjo** [comment]
It's my understanding that the Firefox team recommends that `UNPACK_PREMULTIPLY_ALPHA_WEBGL` not be used. Should mapbox-gl be updated to not use it?

**Comment by jfirebaugh** [comment]
IMO, the Firefox developers are being frustratingly obtuse. To remove the warning, GL JS would need to add code that does exactly what the browser already has an officially specified, built in way to do, and probably does faster than is possible in JS.

**Comment by danger89** [comment]
@jfirebaugh maybe in the case,.. discuss with Firefox devs.

**Comment by mourner** [comment]
Looks like there's no interest in addressing this in the nearest future, and warnings are pretty harmless, so I think we can close as stale for now.

**Comment by ahk** [comment]
Just to note, this message has been upgraded to an error in FF at some point:

`Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.`

I spent a while searching bugzilla but I couldn't see if any newer issues update this since their last comment from two years ago, though it did become an error in that time.

**Comment by joehuggans** [comment]
Can anyone confirm that this is still not fixed i.e. mapbox doesn't work in Firefox? The strange thing for me was it was working until I migrated a website and now it suddenly plays up.

**Comment by asheemmamoowala** [comment]
> mapbox doesn't work in Firefox? 

While this warning is still present, mapbox-gl-js continues to work in the Firefox browser. If you are seeing issues with maps rendering in Firefox, please open a separate issue with a minimal reproducible case to help maintainers diagnose the root case.

**Comment by shaikharfan7** [comment]
How to solve this? I've been referring to mapbox tutorial and having the same error while plotting the pin on the map. Using Firefox and application is being made in django.

**Comment by aggregate1166877** [comment]
From the Firefox team:
> [...] We do not optimize this path, since devs should just not use this. It's still functional, because that's what the spec requires, but we advise against using it.

So, I get log spam because Firefox disagrees with spec... because they "know better" than spec.

Solution is simple: Advise your customers to use a browser with more than 4% market share.
