### ISSUE TITLE
Video export support

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#5297]
From discussion with @julieemunro, it seems like GL JS is frequently used to generate videos showing off some cool map interaction/animation. Our current guidance is to do a screen capture while interacting with or animating the map.

We could make these videos look slicker with dedicated support for video export. I'm imagining that we would build support for rendering frames with specified clock times, instead of running off the system clock (this is also a requirement for #3966). You would make an "export video" call along with a series of animation instructions, and GL-JS would render every frame of the animation to some data output (PNGs stored in memory?). We'd point users at something like `ffmpeg` for turning the frames into a video format of their choice.

The advantage here is that we could make 100% smooth 60fps videos at any level of map complexity. We wouldn't render any frame until we had all the dependencies (e.g. if a frame depends on a new tile, load the tile completely before rendering the frame, so we'd never render a blank tile), and we'd be stutter-free even on otherwise expensive-to-render maps.

/cc @ErinQuinn

**Comment by pock** [comment]
Any new news about this?

**Comment by mourner** [comment]
Great news! I just learned that there are new browser APIs that allow us to do this easily in the browser without heavy libraries, `canvas.captureStream` and `MediaRecorder` — see the demo here https://webrtc.github.io/samples/src/content/capture/canvas-record/ 🎉🎉🎉

**Comment by ChrisLoer** [comment]
@ryanhamley and I have been playing around with this on the `video-export` branch.

To get an intuition for what this looks like and what the potential win is, here's a **before** that's just a plain quicktime screen recording:

https://chrisloer.github.io/flightRecording.mp4?

And here's that same animation **after** (captured to webm and then re-encoded as an mp4):

https://chrisloer.github.io/lessjank.mp4

Our findings are roughly:

- As we hoped, it doesn't turn out to be that hard to hook up GL JS to take as long as it needs to render each frame in an animation (i.e. wait for all tiles to load, also potentially take longer than 16ms to finish drawing the frame) while maintaining an artificial clock so that fade/ease animations etc. follow the expected curve. :tada:
- We were able to use `MediaRecorder` to capture video, but the problem we couldn't surmount is that the `MediaRecorder` really seems oriented towards real-time capture. Even when we feed it individual frames through the `requestFrame()` API, it generates video with those individual frames replayed over whatever real-time elapse happened during the recording. 😞 
- We successfully used the `webm-writer` package to capture video one frame at a time. After looking at what the package does, we think it would be pretty straightforward for us to do the same thing ourselves without the dependency. :tada:
- The `webm-writer` approach (which is basically to call `canvas.toDataURL('image/webp', {quality: quality});` for each frame) is significantly slower than the real-time capture with `MediaRecorder`. We ended up recording at something like 2-3 FPS. Not clear if this is a big deal, and we might be able to do it faster if we roll it ourselves -- but a lot of it seems to be the cost of preserving the drawing buffer and reading it out on every frame. 🤷‍♂️ 
- Playback of the `.webm` video is still janky! 😞This actually seems to be a video encoding issue. Using `ffmpeg` to transform the webm videos to h264-encoded mp4 seems to pretty much make the jank go away (:tada: ?). We don't really have much understanding/experience of optimizing video playback experience, but this implies that we probably won't be able to make a simple/lightweight JS implementation "click here to save a jank-free video". Instead it'll be something like "click here to export `webm` video, and then go to <some website?> to convert that to an mp4".

cc @lobenichou

**Comment by abenrob** [comment]
@ChrisLoer I'd be really interested to see your approach here. The animation looks great, and shows lots of potential. Convert to mp4 is fine in my book, and programming a video is so much more fine-tuneable than screen-recording manually...

**Comment by erictheise** [comment]
I was one of the few non-Mapbox developers that gave a [lightning talk at the San Francisco office](https://mapbox-happy-hour-sf.splashthat.com/) last night. One of the stated purposes of the event was to gather developer feedback and I got some laughs by calling out this issue out by number and name during my talk. Very. Specific. Feedback.

Any progress on this?

**Comment by vakila** [comment]
Hi @erictheise , thanks for joining & speaking at the SF event last night! Hope it was enjoyable.

This is something we're still working on but don't have a concrete timeline for. The `video-export` branch is still where we're tracking our work & experiments with this. 

Other than the feedback that this is something you're interested in, do you have any specific feedback on the proposal and approach so far?

cc @lobenichou

**Comment by pke** [comment]
So the current state is that we still can't record lets say 24fps as fast as the computer can render/move the map?
What I mean is that the output video would look smooth regardless how fast it could be recorded. For that we would need to able to:

1. Control the mapbox animations for pan and zoom etc (using duration options) :heavy_check_mark: 
2. Let MediaRecorder record 1 frame at the time

I guess point 2 is still not possible?

**Comment by vakila** [comment]
@pke Correct, our [experiments with `MediaRecorder`](https://github.com/mapbox/mapbox-gl-js/issues/5297#issuecomment-426020019) showed it not to be well suited for this:

> We were able to use MediaRecorder to capture video, but the problem we couldn't surmount is that the MediaRecorder really seems oriented towards real-time capture. Even when we feed it individual frames through the requestFrame() API, it generates video with those individual frames replayed over whatever real-time elapse happened during the recording.

The prototype on this branch uses `webm-writer` to do what you describe, i.e. take the time needed to record frames so that all tiles etc. are loaded fully before each frame is captured, and then compile the still frames into a video. As described above, the recording process is slow, and the video must be manually transcoded from `.webm` to `.mp4` or such, but the resulting video is smooth.

**Comment by pke** [comment]
So in my scenario render time is not that important. It does not need to be in real-time. Whats important is that all resources are fully loaded and can be rendered. I can then take a canvas snapshot and save it on disk using the Chrome FileWriter API and then at the end run ffmpeg or similar to compose the final movie natively from all the snapshot images.

Would I have to use the branch you pointed me to or could I just register for the "render" event and in that capture the canvas? Then I could use an up-to-date mapbox GL branch and add this functionality on top.

One problem could be animation easying couldn't it when I step through the animations frame by frame?
I am using the `panTo` function, which has a default duration of 0.5 seconds (not in the docs, mind you) and uses an easing function. I guess when I want to pan frame by frame I would have to call `panTo` 60 times for a second worth of animation so to keep the default duration of `panTo` I'd have to call it with `duration: (frame * 0.5 / fps)`. But my fear is that this would change the easing of the motion.

**Comment by ClemensT74** [comment]
Hello folks

I am new here and I´m wondering if there are any new workflows to "export a video" or "image sequence.

Any help would be appreciated.
Greetings Clemens

**Comment by vakila** [comment]
Hi @ClemensT74, welcome - no new workflows on this yet, if/when we have updates we'll track them here. 

@pke I'm not sure I 100% understand your question(s) but if you want to roll your own recorder you could run a loop that updates the map position for this frame, waits enough time that you can be sure the tiles have loaded, snapshots the canvas and then goes on to the next frame. Yes, you would have to calculate the easing yourself as you wouldn't be able to make use of the built-in (eased) animations. You also would miss some other built-in animation e.g. labels fading in and out as they are collided - but depending on your use case/map style, that might not be an issue.

Sorry I don't have any more helpful updates at this point - We'll keep you all posted of any new developments! :heart: 

cc @lobenichou

**Comment by ma2rten** [comment]
Is there any update on this? I tried running the existing branch but I'm getting a ton of errors: 

<img width="438" alt="Screen Shot 2020-05-14 at 6 57 24 PM" src="https://user-images.githubusercontent.com/928271/82003258-c3665f80-9614-11ea-9b54-033059bcfa03.png">

It seems like the branch is too old to work with the current mapbox api. I would be super grateful, if you could help me to rebase this branch on master for me.

**Comment by mourner** [comment]
Made good progress on this in https://github.com/mapbox/mapbox-gl-js/pull/10172 — check this out!

**Comment by supRy** [comment]
Hi, I've been using the example code in #10172 to much success. Thank you for the effort to get this working! I have been having a small issue. I am using a custom map style which has an opacity on a satellite image. Sometimes when zooming in, a couple tiles have that opacity delayed. This means that in the video there are a couple frames with a couple tiles that look like they are flashing. Is there anyway to wait to record the frame until after it has stabilized (and opacity has applied to all tiles)?

I've attached an example

https://user-images.githubusercontent.com/12651670/116764229-72e73e00-a9ee-11eb-8291-8838ee6246ff.mp4

**Comment by mourner** [comment]
Closing this for now since the PR was merged and is mostly working well. Let's open new tickets for any possible improvements.
