### ISSUE TITLE
CanvasSource coordinates inverted in 0.40.0

### ISSUE THREAD

**Issue by gpbmike** [mapbox/mapbox-gl-js#5300]
**mapbox-gl-js version**: 0.40.0

### Steps to Trigger Behavior

 1. Add canvas layer to map with coordinates order top left, top right, bottom right, bottom left per [spec](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-canvas).

### Expected Behavior

Canvas layer should render in desired location.

### Actual Behavior

Canvas layer is rotated and flipped. If you use the following order the canvas layer will render correctly: bottom left, bottom right, top right, top left.

Here's a giphy that compares v0.37.0 (first, smooth fps) to v0.40.0 (second, choppy fps). Notice the colored layer is positioned differently in the second example.

![](https://media.giphy.com/media/l378lZihO4g3F4J0Y/giphy.gif)

Framerate issues addressed here: https://github.com/mapbox/mapbox-gl-js/issues/5301

**Comment by lbud** [comment]
omg the internet 💀 — `webgl.readPixels` and canvas `ImageData` are inverted 🤕 so adding an [intermediary image buffer](https://github.com/mapbox/mapbox-gl-js/pull/5155) to mitigate GPU-specific rendering issues introduced this, and I apparently didn't have any vertically asymmetrical test canvas pages to catch this 🤦‍♀️ 

Fixing in https://github.com/mapbox/mapbox-gl-js/pull/5303, which will be included in a patch release within the next week.
