### ISSUE TITLE
Extrusion Layer - fill-extrusion not rendering after v34 when using stops & external data

### ISSUE THREAD

**Issue by Pantoeflou** [mapbox/mapbox-gl-js#5305]
**mapbox-gl-js version**: 34+

### Steps to Trigger Behavior
Add extrusion layer, where paint details is based on properties: property & stops [maybe text properties is no longer supported here?]

Working example with comments of working and not working available here: https://jsfiddle.net/4ydrb09h/5/
==> comment and un-comment JS script include portion in HTML tab to see difference

### Expected Behavior
Paint extrusion Layer

### Actual Behavior
No layers displayed when using JS version > 34

**Comment by ashleyclough** [comment]
The issue is with your scaling of the 'height' value: 'GP' height 97 * 700 = 67900 which is greater than the maximum value of 65535 (see your browser console). Use 600 and it works.

**Comment by Pantoeflou** [comment]
As easy as that! Cant believe I missed it

Thanks a lot Ashley - the world makes sense again!
