### ISSUE TITLE
"above any label layer" Example

### ISSUE THREAD

**Issue by cyrilchapon** [mapbox/mapbox-gl-js#5306]
I think this little piece of code

```
    var layers = map.getStyle().layers.reverse();
    var labelLayerIdx = layers.findIndex(function (layer) {
        return layer.type !== 'symbol';
    });
```

Introduced [on the 3D buildings example](https://www.mapbox.com/mapbox-gl-js/example/3d-buildings/) should reside on the [Add a new layer below labels example](https://www.mapbox.com/mapbox-gl-js/example/geojson-layer-in-stack/)

Shouldn't it ? I would be helpful

**Comment by cyrilchapon** [comment]
(I just found myself struggling at finding this little yet useful piece of code inside the whole examples stack)

**Comment by anandthakker** [comment]
Good idea @cyrilchapon!  Would be happy to have a PR adding this.

**Comment by jfirebaugh** [comment]
Done in #5537.
