### ISSUE TITLE
Mapbox Map with Google as source reference

### ISSUE THREAD

**Issue by pierzen** [mapbox/mapbox-gl-js#5311]
## thecanadianpress map published with source reference MapBox-Google

Is it possible to use Google as a source? If not, reference to OpenStreetMap is needed.

### Web Publication
see http://thecanadianpress-a.akamaihd.net/graphics/2017/september/pc-septembre/alerte-amber/carte-alerte-amber.png
 
### Expected Behavior

source = OpenStreetMap ?

### Actual Behavior

source = Google

**Comment by mourner** [comment]
It's not possible to use Google as a source with Mapbox GL. It also always attributes OpenStreetMap. I don't understand the report, but going to close since it doesn't seem like there's an issue on our side.

**Comment by pierzen** [comment]
What's about OpenStreetMap license with this product?

**Comment by pierzen** [comment]
Source reference now corrected with mention of OpenStreetMp on the CanadianPress map.
