### ISSUE TITLE
Not working in Internet Explorer IE11.447.14393.0

### ISSUE THREAD

**Issue by gmaclennan** [mapbox/mapbox-gl-js#5312]
**mapbox-gl-js version**: 0.40.0

### Steps to Trigger Behavior

 1. Open https://www.mapbox.com/mapbox-gl-js/examples/ in Internet Explorer 11

### Expected Behavior

Map appears

### Actual Behavior

A blank map appears.

![image](https://user-images.githubusercontent.com/290457/30515176-e4b53340-9ad7-11e7-98fb-7059edbe4f91.png)

**Comment by pemil** [comment]
I have the same problem in IE 11. 

I get this error in some examples only in IE 11, and no rendered map. Don't know if it's related.

![skaermbillede 2017-09-18 kl 14 05 39](https://user-images.githubusercontent.com/9801004/30541168-7c88a9e2-9c7a-11e7-8112-98974c988751.png)

**Comment by jfirebaugh** [comment]
Thanks for the report; fixed for 0.40.1.

**Comment by mikkom** [comment]
There still seems to be some issues with IE11. For example at times the map in https://www.mapbox.com/mapbox-gl-js/example/cluster/ stays blank and usually after a page refresh or two starts working again. In our own app the map stays blank no matter how many times we reload the page.

![capture](https://user-images.githubusercontent.com/77391/30591295-e35cdde8-9d4a-11e7-981c-3976f9f67398.PNG)

**Comment by mikkom** [comment]
False alarm, I guess my problem was a combination of Windows running on Parallels and some weird cache issues. The map seems to be loading now just fine on IE11, too. Sorry about the noise 🙂
