### ISSUE TITLE
Custom tooltip does not overlays over mapboxgl.Marker

### ISSUE THREAD

**Issue by benderlidze** [mapbox/mapbox-gl-js#5316]
v40
I want a custom tooltip overlay over a div marker. I have tried a different variants with z-index but with no luck. Any suggestions how to fix it?
Thanks!

Here is a jsfiddle with the problem:
https://jsfiddle.net/t9sjv1sn/
If you hover the lowest marker there will be a tooltip under the top marker.

**Comment by jfirebaugh** [comment]
To fix this issue, set an appropriate CSS `z-index` on your `.tooltip` class.
