### ISSUE TITLE
Bug in typescript definition

### ISSUE THREAD

**Issue by pvdyck** [mapbox/mapbox-gl-js#5318]
In index.d.ts typescript definition, there is no way to use "identity" in StyleFunction 👍 

export interface StyleFunction {
		stops: any[][];
		property?: string;
		base?: number;
		type?: "identity" | "exponential" | "interval" | "categorical";
		default?: any;
		"colorSpace"?: "rgb" | "lab" | "interval";
	} 

stops should be optional.

### Steps to Trigger Behavior

Use any stylefunction (like "circle-color") with "identity" as type.

### Expected Behavior

... works ;-)

### Actual Behavior

Error raised in console : layers.clusters.paint.circle-color.stops: identity function may not have a "stops" property

**Comment by mourner** [comment]
We don't officially maintain a TypeScript definition. If you find any issues with it, please submit them to the author in the repo where it is hosted.
