### ISSUE TITLE
WPF Mapbox Control

### ISSUE THREAD

**Issue by TonyLugg** [mapbox/mapbox-gl-js#5319]
## Motivation

We have a dispatch and journey management solution that is used by SaaS and enterprise customers.  Due to the nature of our solution, our desktop client is usually used within our customers' monitoring centers.  Bing Maps has a WPF control that makes it easy to use with our Windows desktop application.  We would like to move these customers to Mapbox but have found it difficult to get the Mapbox GL JavaScript code to work within the IE based WebBrowser control.  A WPF Mapbox control would help us with this initiative.

## Design Alternatives

It should be possible to use a Canvas in WPF similar to how it is done in HTML 5 to display the vector tiles and additional layers.  We are not looking for additional functionality from what the JS version offers, just a stable alternative that works well for the desktop.

### Mock-Up

It should look similar to the web/JS version.

### Concepts

The concepts should be very similar to the web/JS version.

### Implementation

A C# implementation would be the best as it is widely used and should be able to handle the task.

**Comment by jfirebaugh** [comment]
Hi @TonyLugg -- we don't currently have plans to release a native Windows SDK. If we did, it would likely be done via [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/) rather than JS. For some past discussion in that context, see https://github.com/mapbox/mapbox-gl-native/issues/8429.

**Comment by AliFlux** [comment]
There is an opensource map control available that works with both WPF and WinForms. It allows custom map provider that we could use for raster tile rendering that is pre-rendered on the server.

https://github.com/radioman/greatmaps

For vector tiles, a relatively easier way would be to port the mapbox native implementation to Windows. Then fetch the vector tiles from server, render on client, and pass them to greatmaps.

**Comment by TonyLugg** [comment]
@AliFlux I recently built a WPF control that works with Mapbox and other raster tile API's.  If I had known about GMap.NET I would have used it for sure.  I may still... thanks for the info.

**Comment by ryanbaumann** [comment]
Noting that we have a Mapbox Maps SDK for QT which you can build to run native on Windows at https://github.com/mapbox/mapbox-gl-native/blob/380f5dc88bb4103a528740e67d887a8695529528/platform/qt/README.md

**Comment by AliFlux** [comment]
@ryanbaumann, it still requires Qt. Which apart from being a hassle to setup and integrate, has a lot of licensing limitations.

**Comment by AliFlux** [comment]
Apparently we can only fetch vector tiles from mbtiles using C#. Rendering isn't properly implemented on C# at the moment. https://github.com/mapbox/mapbox-sdk-cs

**Comment by AliFlux** [comment]
Just stumbled upon something interesting:
https://github.com/OsmSharp/VectorTileToBitmapRenderer

Someone write a full-fledged vector tile renderer in C# :D Will try it in a couple of hours and give an update here.

**Comment by AliFlux** [comment]
Hi. 

I ended up writing my very own vector tile rendering client for C#/WPF. Try it out and let me know what you think:

https://github.com/AliFlux/VectorTileRenderer

Thanks.

**Comment by TonyLugg** [comment]
I could not get the static demo to run.  I think it is looking for tiles in the file system.  My use case would be to simply specify a Mapbox access key and have the control download the tiles from the Mapbox servers.

**Comment by AliFlux** [comment]
I've ported Mapbox to WPF using CefSharp. Check out MapboxNet. 

![3d](https://user-images.githubusercontent.com/8333794/56814301-52f96e80-6858-11e9-8d10-041e56821571.png)

**Comment by TonyLugg** [comment]
@AliFlux I ended up building a WPF control that uses the Mapbox Tile API (REST).  It is not vector based but it works well.  How portable is CefSharp?  Does it require anything to be installed on the client?  I am intrigued by your vector solution and will check it out for sure.  What would really shine would be a Mapbox WPF control with native vector tile support.  I was considering building one but have not had time yet.

**Comment by AliFlux** [comment]
MapboxNet is practically the Mapbox GL JS running on Google V8 engine. All of the APIs are exposed to C# code, with enough abstraction that it doesn't feel like its running in a VM. + There is support for MVVM/data-binding.

It's pretty portable. Doesn't require anything to be installed on the client except for .Net Framework 4.6.2.
