### ISSUE TITLE
Mapbox GL Polygon Display Issues

### ISSUE THREAD

**Issue by Craytor** [mapbox/mapbox-gl-js#5324]
Mapbox GL version: v0.40.0

Polygons are not showing up correctly on Mapbox GL, but show up perfectly fine on Leaflet and other GIS applications.

```
this.map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/satellite-v9',
    center: [-74.50, 40],
    zoom: 9
});

this.map.addSource("warnings", {
    "type": "geojson",
    "data": "https://wx-api.dev.tjyouschak.me/alerts/severe/watches"
});

this.map.addLayer({
    "id": "warnings",
    "type": "fill",
    "source": "warnings",
    "paint": {
        "fill-outline-color": "#fa0000",
        "fill-opacity": 0.5,
    }
});
```
### Expected Behavior
https://gist.github.com/anonymous/f9241462697e850d7df68442e4f75fe4

### Actual Behavior
<img width="676" alt="screen shot 2017-09-18 at 7 38 17 pm" src="https://user-images.githubusercontent.com/3680866/30569597-bb5f96e2-9ca9-11e7-83f9-315bf35a0d94.png">

**Comment by peterqliu** [comment]
looks like https://github.com/mapbox/mapbox-gl-js/issues/3080

**Comment by Craytor** [comment]
Yeah, I just noticed that. I wonder if there is a work around for this issue.

**Comment by Craytor** [comment]
After much debugging and looking around on the web, I have found that the issue is bad GeoJSON (well not necessarily bad, but not what I was intending to do).

#5278 helped me figure out where I went wrong.
