### ISSUE TITLE
cache is not cleared when removing a source

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#5327]
[This](https://github.com/mapbox/mapbox-gl-js/pull/3359) issue seems to suggest that the cache is cleared when removing a source. When I remove a layer and source like this:
```
        map.removeLayer(markerLayer.id)
        map.removeSource('markers')
```
The layer indeed disappears. Then I adjust my source, add it and the layer back again; it still does not show my adjustments. It will show the adjustment after I clear the cache and refreshed my browser.

So why is the cache not cleared?

**Comment by jfirebaugh** [comment]
By "the cache", are you referring to the browser cache? Mapbox GL JS does not have any control over that. If you need to bypass the browser cache, you'll have to serve the tiles with appropriate `cache-control` headers.

**Comment by musicformellons** [comment]
Yes, thanks, that's more what I need!
