### ISSUE TITLE
Error on Ionic IOS when loading offline pbf files (EXC_BAD_ACCESS)

### ISSUE THREAD

**Issue by rklerck** [mapbox/mapbox-gl-js#5334]
I'm really struggling with this. I have an ionic app with local pbf files inside it using the mapbox gl js. When I run it in the browser it all works (shows the map). But when I run it on my ios device it doesn't. Probably because it isn't resolved in an url. I'm talking about this part here:

`"tiles": [location.origin+location.pathname+"assets/gabon/{z}/{x}/{y}.pbf"],`

I know it's not really a bug, but I hope someone can help. I'm not getting an error on my device, it's just stuck! And sometimes after a while I see this: error "Thread 9: EXC_BAD_ACCESS

**Comment by jfirebaugh** [comment]
Sorry, we aren't able to debug integrations with third-party frameworks like Ionic. Mapbox GL JS is a JS library; if there's an `EXC_BAD_ACCESS` it's a bug in native code somewhere.
