### ISSUE TITLE
Context for Evented listeners

### ISSUE THREAD

**Issue by rendrom** [mapbox/mapbox-gl-js#5336]
Why current Evented class has no use context to attach listeners?

https://github.com/mapbox/mapbox-gl-js/blob/244d1e77e20b815a4834c54858053ea473e5c62c/src/util/evented.js#L42

It was very useful in Leaflet Events 

https://github.com/Leaflet/Leaflet/blob/e5a3d5ecc360af77e291451172c60d4e3807cf72/src/core/Events.js#L37
```js
	on: function (types, fn, context) {
```
Problem example:

```js
class App {

    constructor (map) {
        // 1 
        map.on("style.load", this.onStyleLoad)

        // 2 use binding
        map.on("style.load", this.onStyleLoad.bind(this))
        // but it is impossible to unsubscribe from this listener late:
        // map.off("style.load", this.onStyleLoad.bind(this)) OR 
        // map.off("style.load", this.onStyleLoad) is NOT work

       // 3 Leaflet style
       map.on("style.load", this.onStyleLoad, this) // Work correct
    }

    onStyleLoad() {
        // 1 - here this is map, not app instance
        // 2-3 - this is app
    }
}
```

**Comment by jfirebaugh** [comment]
The `context` argument is not necessary in modern JavaScript. Instead, use [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions) or `.bind(this)`.

**Comment by jfirebaugh** [comment]
In your `this.onStyleLoad.bind(this)`, do `this.onStyleLoad = this.onStyleLoad.bind(this)` prior to calling `on` and `off` (`off` needs to be called with the same function instance as was used for `on`; `.bind(this)` creates a new function each time it is called).

**Comment by rendrom** [comment]
@jfirebaugh yes, I do, but but this is much more difficult to simple passing the context. From my point of view.

**Comment by Bernoulli-IT** [comment]
@jfirebaugh Yes that will work appropriately but is pretty cumbersome if in each and every class there have to be (several) private fields to keep track of this ☹
