### ISSUE TITLE
Error when easing function sends event where another easing function is listening

### ISSUE THREAD

**Issue by pkang** [mapbox/mapbox-gl-js#5341]
A JSFiddle demonstrating this issue is [here](https://jsfiddle.net/pablokang/ohc3mpco/).

A simple guard to make sure [`_finishFn`](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/camera.js#L881) exists would help, but unsure what sort of repercussions this would have.

**Comment by anandthakker** [comment]
Thanks for the report and the clear test case, @pkang 

From an initial look, I think this is a reentrancy problem:
 - `_prepareEase()`, which handles firing the `*start` events, being executed before `_ease()`, which handles setting up the `_abortFn`
 - So, when the `zoomstart` handler in the test case initiates a new easing, the `this.stop()` has no `_abortFn` to call.

**Comment by pkang** [comment]
That's exactly right.

**Comment by anandthakker** [comment]
@pkang A temporary workaround for this would be to defer the easing initiated by the `zoomend` to the next tick, via `setTimeout(() => map.flyTo(...), 0)`

**Comment by pkang** [comment]
The test case was a straw man to demonstrate the problem and the deferring would work. In our more complicated application, however, it would feel unnatural to wrap every easing function with a `setTimeout`. 

I have a [fork of this project](https://github.com/scootnetworks/mapbox-gl-js/commit/e973f5136fb2c03bd15693d5494fe65fe489e258) that guards against the undefined `_finishFn` case. So far I haven't seen any issues doing this  (disclaimer: haven't tried it in production yet) but I suspect this could be an issue for others.

**Comment by plul** [comment]
I am experiencing an error that may be related.

If I use `.flyTo` and I interact with the map in any way whatsoever (zoom, move, with a mouse, programmatically...) while it is doing the flyTo transition, then it crashes immediately upon completing the flyTo transition.

```
ERROR TypeError: t is undefined
Stack trace:
[224]</Camera</i.prototype._finishEase@http://localhost:8100/build/vendor.js:81415:7642
[224]</Camera</i.prototype._ease/this._abortFn<@http://localhost:8100/build/vendor.js:81415:7488
a@http://localhost:8100/build/vendor.js:81457:591
F</l</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:15649
onInvokeTask@http://localhost:8100/build/vendor.js:4971:24
F</l</t.prototype.invokeTask@http://localhost:8100/build/polyfills.js:3:15562
F</c</r.prototype.runTask@http://localhost:8100/build/polyfills.js:3:10815
F</h</e.invokeTask@http://localhost:8100/build/polyfills.js:3:16787
e/this.invoke@http://localhost:8100/build/polyfills.js:3:16669
n@http://localhost:8100/build/polyfills.js:3:52
 core.js:1350
```
