### ISSUE TITLE
New 'bbox' filter type for style layer spec

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#5356]
## Motivation

I would like to be able to set a bounding box filter on a style layer so that only features inside this region are rendered.

My application consumes tile sources which provide data for the entire USA, eg: a national parks tile source.

However, my users only care about their specific project area, usually a city or county. We would like to only render features that exist within this project area.

The best we can do right now is to limit their movement outside their project area by attaching a `mapBounds` to the map.

- Pink = user's project area
- `mapBounds` = user's project area + a little padding on all sides
- Green = national parks dataset

![uf2-bounds](https://user-images.githubusercontent.com/4524175/30883845-5c0256b6-a2c2-11e7-9562-f97a19b3cd70.gif)

This experience is less than ideal,  since restricting map movement can be confusing for some users, eg: 

- the map zoom control begins nooping at a certain point
- users hit invisible walls when trying to drag pan
- features render on map, but get cut off at the boundaries

The preferred experience would be to allow the user to zoom/pan the map without these restrictions. If they leave their project area, we simply don't render any of the features there.

We had originally thought to attach `bounds` to the tile source instead of the map itself, which would prevent those tiles from being requested. However if the user zooms out to the entire US, they'll receive all the data in a single tile.

![image](https://user-images.githubusercontent.com/4524175/30885526-760eeb22-a2c8-11e7-9722-87631d7156d6.png)

## Design

A new filter type, `bbox` that can be declared in the style layer spec:

```js
  map.addLayer({
    id: 'parks',
    type: 'fill',
    source: 'parks_source',
    'source-layer': 'parks',
    // Only render a feature if the statename is california,
    // and the feature exists within this bbox
    filter: [
      "all",
      ["==", "statename", "california"],
      ["bbox", '<southwestLng>', '<southwestLat>', '<northeastLng>', '<northeastLat>'],
    ],
    paint: {
      'fill-color': 'green',
      'fill-outline-color': 'darkgreen',
    },
  });
```

**Comment by peterqliu** [comment]
@DannyDelott thanks for the suggestion. The current implementation of filters is meant to act only on properties of each feature, rather than their geometry. Accommodating the latter is a significant refactor (I'll let the gl-js team chime in on the lift involved), and also a fundamental shift in what filters are meant to do.

The best way to show only features within an area is to filter them while making the source data, with tools like [tippecanoe](https://github.com/mapbox/tippecanoe).

**Comment by DannyDelott** [comment]
Thanks for the reply @peterqliu. That's good to know about the current filter implementation.

**Comment by anandthakker** [comment]
Yep, echoing @peterqliu, filters aren't currently designed to work with feature geometry

If you need to filter features by geometry dynamically, you might have luck exploring a library like [RBush](https://github.com/mourner/rbush), which would allow you to build an index of features that could be queried by bbox, and then use the result of such a query to update a layer's filter with a list of relevant id's.

Thanks for the thoughtful suggestion, @DannyDelott -- closing for now, as supporting this would be incompatible with other, performance-related constraints for the foreseeable future.
