### ISSUE TITLE
Only run lint/flow on tracked files

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#5358]
By default, linting runs on all files that it can find. However, we should only run it on files that are tracked by Git, if a repository exists.

**Comment by anandthakker** [comment]
I'm not sure if eslint/flow can easily be configured to do this, but even if it can, a consequence would be that editor integrations would fail to show lint warnings in new files that aren't yet added to git.

What's the advantage of not checking files that aren't checked into git?

**Comment by jfirebaugh** [comment]
Good points @anandthakker. Let's stick with the current setup.
