### ISSUE TITLE
Dynamic Makers make map slow

### ISSUE THREAD

**Issue by cuvant** [mapbox/mapbox-gl-js#5360]
Hello,

Currently I'm working on a map app, and I decided to use MapBox GL JS API for the map. Currently I have an issue when I load the map on a big screen > 24inch. The map is lagging hard, and I have idea what may cause this.

I simply do a AJAX call  on 'zoomed' event to fetch the locations that should be displayed in the maps view point.

Then I just loop through the GeoJSON and create markes and add items in the nabar.

You can see the behaviour [here](https://app.potdrive.com/). Thank you :)

**Comment by jfirebaugh** [comment]
Can you quantify the performance you're seeing, or provide profiling data? Just glancing at the page you linked in Chrome, I'm not seeing the issue.

**Comment by joedjc** [comment]
Possibly linked to this: https://github.com/mapbox/mapbox-gl-js/issues/5390

I think its very browser dependent - Safari, IE and Edge seem to have the problem but FireFox and Chrome are ok.
