### ISSUE TITLE
Missing tiles from custom tilesets in composite sources gives 404 error

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-js#5366]
If I use a custom tileset which contains data for a specific location (i.e. not the whole world), together with a standard mapbox source (e.g. mapbox streets) I get 404 (missing) errors from the custom tileset tiles where they don't exist.

Would it be possible to return a 204 message (No Content) which seems to be handled better by the browser?

Tested in mapbox 0.40.1

**Comment by jfirebaugh** [comment]
Yes, good thought -- we have an internal ticket for our tiles API requesting a switch to 204. See also #5093.
