### ISSUE TITLE
Why offset of icons not defined in sprite.json

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#5369]
because offset of sprite depends on each elements size i'm wondering why it isn't definded in sprite.json file. If i have different icon sizes i've to change it on js level for every icon. For me this didn't make sense. 
So is it possible to define it in sprite.json otherwise why not?

Thanks

**Comment by jfirebaugh** [comment]
In some cases, the offset is dependent on the type of feature being displayed, or other style-related considerations, rather than the icon itself, so we chose to make this as flexible as possible.

**Comment by strech345** [comment]
Would it not nice to have it also in sprite.json as default and let the possibility to change it dynamically on js? I doesn't understand why i have to think about this parameter if i want to use some icon. For me it is a property which describe the icon like all the others.
