### ISSUE TITLE
Reinstate direct implementation for old-style functions

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5379]
Per chat w/ @mourner and @jfirebaugh, the plan is to remove the automatic migration of old-style functions to expressions, instead reinstating a direct implementation for them. (We may be able to at least share some of the stops-interpolating logic between this and `evaluation_context`).

This would make expressions a fully opt-in feature.

**Comment by jfirebaugh** [comment]
Note that I do hope that once expressions have matured we can switch back to a conversion strategy, rather than maintain two evaluation pathways.
