### ISSUE TITLE
Add a text-background-color property

### ISSUE THREAD

**Issue by bart-1990** [mapbox/mapbox-gl-js#5381]
Add a text-background-color property to set the background-color of a text label. Introducing this property would also require the need for some sort of padding property to define the distance of the space around the text that should be colored.

There are cases where the text-halo properties aren't sufficient to stand the text out from the background. Having the possibility to add a background-color to text would help.

**Comment by jfirebaugh** [comment]
Hi @bart-1990, thanks for the suggestion. You can accomplish something similar with the current properties by creating a square background image and then using [`icon-text-fit`](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-icon-text-fit). We have various other issues that suggest enhancements in the same vein: #4366, #4436. Closing as covered by those issues.
