### ISSUE TITLE
Identical Lat/Long Data points do not overlap in UI #5275

### ISSUE THREAD

**Issue by bfuerst** [mapbox/mapbox-gl-js#5385]
Hi,

We have two datapoints with identical Lat/Longs and expect them to overlap but in our Mapbox GL (https://api.tiles.mapbox.com/mapbox-gl-js/v0.39.1/mapbox-gl.js) web UI the points are slightly separated. Attached is an example of what it looks like in the UI when it is zoomed in.

JSFIDDLE - https://jsfiddle.net/rjtL4154/7/

Ex - https://image.ibb.co/fQdKuv/2017_08_11_13_33_14.jpg
Ex - https://ibb.co/hWjFrG
2017_08_11_13_33_14

Steps to trigger behavior

Load two points with identical lat/longs from two different datasets
Convert both datasets to tilesets
Layer the two tilesets in a style
Apply style to web map
Zoom into Lat/Long and the identical points do not overlap
Expected behavior

Points with identical lat/longs would overlap

Actual behavior

Points with identical lat/longs do not overlap

**Comment by jfirebaugh** [comment]
Hi @bfuerst -- thanks for the JSFiddle. That's a lot of code though. In order to make it easy for us to help you, could you please mean reduce it to the minimal amount of code necessary to show the issue? Thanks!

**Comment by bfuerst** [comment]
Hi @jfirebaugh - Sure, see new URL! We deleted most of the JavaScript and are down to 25 lines. 
https://jsfiddle.net/yrpLyddx/

**Comment by jfirebaugh** [comment]
Is that the right link? I'm still seeing 770 lines:

![image](https://user-images.githubusercontent.com/98601/31037322-370715d0-a525-11e7-9441-4415e7e28795.png)

**Comment by bfuerst** [comment]
Sorry, try this one - https://jsfiddle.net/ccrews/yrpLyddx/2/

**Comment by jfirebaugh** [comment]
Sorry, I really need to ask you to make it smaller -- e.g. just hard code two points that you believe should be overlapping, without requiring any UI or user interaction. This serves two purposes:

* Enable me to help you with out a lot of back and forth about what's needed to replicate the issue (as we're doing now).
* Eliminate your own code as a potential source of the issue.

**Comment by bfuerst** [comment]
Hi,

We have updated the JS Fiddle and provided screenshots from within the mapbox studio application. 
JS Fiddle - https://jsfiddle.net/dvLpujn3/

To recap, we have two data sets with a point at the exact same Lat/Long 
Picture - https://ibb.co/msoDkb

But these two points with the exact same Lat/Long do not over lap in the Mapbox Style tab or our JS Fiddle
Picture - https://ibb.co/fnO4Qb

Note - Every colored point on the JS Fiddle has a corresponding Gray point with the exact same lat/long. 
Zooming in on any point on the JS Fiddle should show our issue.

We have verified that the lat/longs are exactly the same in the datasheets tab but on the style tab the points separate

**Comment by jfirebaugh** [comment]
The data is coming from two different tilesets with different maximum zooms. The ["all" tileset](https://www.mapbox.com/studio/tilesets/dtrementozzi.cj8ervmj1175g33o51y29qaf3-9cjfv/) has maximum zoom 8, while the ["rooftop" tileset](https://www.mapbox.com/studio/tilesets/dtrementozzi.cj8erwv0818lu33lbio6wl5ts-7l371/) has maximum zoom 7. Because the maximum zooms differ, the precision of coordinates at zooms above the maximum will differ. That's why points don't appear at the same position. To resolve the issue, ensure that the tilesets have the same maximum zoom, or load all the point data from a single tileset.
