### ISSUE TITLE
Wrong geometry with queryRenderedFeatures

### ISSUE THREAD

**Issue by benderlidze** [mapbox/mapbox-gl-js#5389]
I am trying to get the geometry of the polygon with queryRenderedFeatures
On zoom level 12 is ok, but on 15 I got the wrong geomentry.
Here is my code, and I everytime on mouse over I get the different coordinates.
Here https://codepen.io/benderlidze/pen/qPXNJv - hover the mouse from the top on the poly and from the bottom. The red poly is a geometry returned by queryRenderedFeatures and it is always different.

`  map.on("mousemove", "seatRowsFill", function(e) {
    	
    	map.getCanvas().style.cursor = 'pointer'; 
        map.setFilter("seatRowsFill-hover", ["==", "rowNumber", e.features[0].properties.rowNumber]);
  		
  		var relatedFeatures = map.queryRenderedFeatures(e.point, { layers: ['seatRowsFill'],"filter": ["==", "rowNumber", e.features[0].properties.rowNumber]  } )
  		console.log(relatedFeatures["0"].geometry.coordinates["0"][2])
  		`

**Comment by anandthakker** [comment]
Hi @benderlidze , thanks for using Mapbox.

The reason that the geometries returned by `queryRenderedFeatures` are different from the underlying source data is that data is converted to "tiles" internally.  From the [queryRenderedFeatures documentation](https://www.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures):

> Because features come from tiled vector data or GeoJSON data that is converted to tiles internally, feature geometries may be split or duplicated across tile boundaries and, as a result, features may appear multiple times in query results. For example, suppose there is a highway running through the bounding rectangle of a query. The results of the query will be those parts of the highway that lie within the map tiles covering the bounding rectangle, even if the highway extends into other tiles, and the portion of the highway within each map tile will be returned as a separate feature. Similarly, a point feature near a tile boundary may appear in multiple tiles due to tile buffering.

If you need to recover the entire feature geometry based on a `queryRenderedFeatures()` query, then your best bet is to include a unique identifier on each feature's `properties` object, and use that identifier to look up the feature from your original GeoJSON.
