### ISSUE TITLE
Run benchmarks against previous release as part of release process

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5392]
While our benchmark system, especially with recent improvements, will help us catch individual changes that introduce performance regressions, it's very possible for regressions that are too small to detect to accumulate slowly.

As a guard against this, let's add a step to our release process wherein we benchmark against the previous release (possibly upping the sample count to get better estimates since this only happens once every few weeks).

**Comment by jfirebaugh** [comment]
I did this manually for 0.42.2. One issue I ran into is that if there have been changes to the benchmarks themselves (e.g. #5680), then the results are not comparable.

**Comment by mourner** [comment]
As far as I understand, this has been already addressed by #5878 and #6134.
