### ISSUE TITLE
Design an expression constraint or form that allows for statically determining all possible output values.

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5393]
It seems that we need to be able to determine statically (i.e., without access to feature data) what all the possible output values are for some expressions:
 - [`text-font`](https://github.com/mapbox/mapbox-gl-native/issues/9939#issue-256329821) - needed because "One of the components of an offline region download is the complete set of glyph range PBFs for all the font stacks used by that region's style"
 - `icon-image` - per chat with @ian29 @aparlato, "we need to know all the icon names referenced by a style in order to check that the icons exist"

In order to do this, we need a way to define an enforceable constraint on expressions that guarantees that guarantees that its possible output values is a subset of the set of string literals used in the expression.  (Theoretically possible for the guarantee to be looser, but this is probably good enough.)

**Comment by anandthakker** [comment]
cc @jfirebaugh

**Comment by anandthakker** [comment]
Copying over from chat:

@jfirebaugh It seems like it should be pretty straightforward to write a static analyzer that recursively descends an expression AST to determine potential outputs, with some sort of sentinel value for "unknown"/"dynamic value"

@jfirebaugh hm, my fear with that approach is that it might be hard for users to understand, without some trial and error, what expressions they could use

@anandthakker Studio can use some stricter but easier to understand rule if it wants to. But this would solve @ian29's need and the offline glyph's need.

hm yeah, good point.  I was thinking in terms of people authoring raw expressions, but as I myself have argued elsewhere, the users doing that are very likely to be expert

**Comment by jfirebaugh** [comment]
We have a plan for this in https://github.com/mapbox/mapbox-gl-native/issues/9939#issuecomment-335895131.
