### ISSUE TITLE
Marker Click to Return Lat Lng

### ISSUE THREAD

**Issue by Craytor** [mapbox/mapbox-gl-js#5397]
**mapbox-gl-js version**: 0.40.0

I am having a strange issue with MapBox GL. I've searched through the issues and couldn't find my exact issue.

I have markers that I have created and added to my map as a type of "circles" and I'm using the data options so I have base and stops. When I click on a maker, I expect to be able to find the lat and lng of the point in the geometry, but that is not the case. When I click on a marker from way out, I get the response that I clicked the marker (logging it to the console), but also it clicks onto a polygon (this is fine), so I can see the originating point of where I clicked. When I zoom in on a marker it is way off from a point, and therefore if I click the point again the geometry in the feature shows a different point.

Here is what I'm trying to do: click on a marker, get the marker's point (as I set in the geojson) and then find all polygons that exist at that layer.

When you think you click on the icon (the listener that listens to icon clicks says you clicked):
<img width="831" alt="screen shot 2017-10-03 at 8 36 38 pm" src="https://user-images.githubusercontent.com/3680866/31155257-ba4b0516-a87a-11e7-8075-f1dae3ea267d.png">

After you zoom in this is how far off the click was:
<img width="690" alt="screen shot 2017-10-03 at 8 37 00 pm" src="https://user-images.githubusercontent.com/3680866/31155266-c8c157a8-a87a-11e7-8c16-02d422e117e3.png">

And finally, if you click the marker again this is what it shows:
<img width="844" alt="screen shot 2017-10-03 at 8 37 15 pm" src="https://user-images.githubusercontent.com/3680866/31155272-d1089570-a87a-11e7-8c32-1ac6d27c266b.png">

Any suggestions would be much appreciated!

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained JSFiddle that demonstrates the issue?

**Comment by Craytor** [comment]
@jfirebaugh Alright, should have added that earlier. It isn't as great, but I think it has what is needed, and was able to see the issue using this as well.

http://jsfiddle.net/Craytor/01b97w0L/74/

Please let me know if I should add anything to the fiddle.

**Comment by jfirebaugh** [comment]
Thanks. So what's the issue you're reporting, in terms of "expected result" versus "actual result"?

**Comment by Craytor** [comment]
I'm expecting that when I click on a marker that I can get the lat and lng of the marker so that I can find out what polygons exist at that point.

Instead, what is happening is that it seems to be getting the point where you click the map, which is not necessarily the actual point of the marker (that was defined in the geojson).

I was hoping that `e.features[0].geometry.coordinates` was the point of the marker, but it appears it is where you click the map based on my trial and errors.

**Comment by jfirebaugh** [comment]
Inside the click handler for the `myPoint`, `e.features[0].geometry.coordinates` is the location of the marker. Is what you're noticing that if you place a popup at that location when the map is zoomed out, and then zoom in, that it's no longer precisely positioned on the point? If so, see #4733 and https://github.com/mapbox/mapbox-gl-native/issues/8992#issuecomment-301624564.

**Comment by Craytor** [comment]
Okay, so I am confused by `e.features[0].geometry.coordinates` being the location of the marker because in my geojson the coordinate is `[-123.199274, 39.153673]`. Though, when you click on the marker it is saying `-123.19931030273438, 39.15349256868936` and not `-123.199274, 39.153673`.

**Comment by jfirebaugh** [comment]
GeoJSON data is converted to a tiled format (like vector tiles) internally, and coordinates at a given zoom level may not round trip exactly. What you're seeing is the same as #4733; closing as a duplicate.
