### ISSUE TITLE
Underlying fill layers cause extrusions to look weird

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#5399]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Add a fill layer
 2. Add an extrusion layer atop it
 3. Check out the weird colors

### Expected Behavior

Should not affect the apparent color of extrusions.

### Actual Behavior
![screen shot 2017-10-04 at 12 14 09 pm](https://user-images.githubusercontent.com/4551508/31195238-772a9e0c-a8fe-11e7-847d-3bf5e3cd6dfd.png)

^ Extrusions over a fill of water geometry. Note how you can see the lakes

**Comment by peterqliu** [comment]
Hmm can't reproduce within Studio itself -- this bug may be limited to geojson sources, or when the fill and extrusions are using different sources.

**Comment by jfirebaugh** [comment]
JSFiddle?

**Comment by peterqliu** [comment]
Actually the result of a silent error, related to https://github.com/mapbox/mapbox-gl-js/issues/5400. Closing.
