### ISSUE TITLE
Unify `createExpression()` and `createExpressionWithErrorHandling()`

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5409]
From https://github.com/mapbox/mapbox-gl-js/pull/5407#discussion_r142951681:

> Could we use an error return type by default, and push the try/catch up to StyleDeclaration#calculate?

**Comment by jfirebaugh** [comment]
Tried this (https://github.com/mapbox/mapbox-gl-js/commit/693366bfb8d20f5335c8358852f8b0d17f7495e5) but it [regresses layout performance](https://bl.ocks.org/anonymous/raw/2b247bab7e59c3f83fa75ad8c7f2921d/). Let's go with your idea of making it an option. Or maybe we can base it off of whether the `defaultValue` option is present?
