### ISSUE TITLE
`yarn start` can't cope with source file changes

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5411]
If you modify a source file while `yarn start` is running, you get:

```
Error: Parsing file /Users/john/Development/mapbox-gl-js/src/style-spec/expression/index.js: 'import' and 'export' may appear only with 'sourceType: module' (16:0)
```

**Comment by mourner** [comment]
Same with NPM. But it seems to only happen when changing a branch, and gets fixed after relaunching `start`.

**Comment by anandthakker** [comment]
Ugh, yeah. 

> But it seems to only happen when changing a branch, and gets fixed after relaunching start

It seems to happen for me when changing any file in `src/`, not only when changing branches.  E.g. with `start-bench`, changing `benchmarks_view.js` works fine, but changing actual GL JS source files causes this error.

**Comment by jfirebaugh** [comment]
This got fixed upstream somewhere.
