### ISSUE TITLE
Circles don't respond to events on the stroke area

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#5426]
**mapbox-gl-js version**: 0.40.1

### Steps to Trigger Behavior

 1. https://codepen.io/stevebennett/pen/NaYaLv
 2. Notice how hovering over the green border doesn't change the interior color.

### Expected Behavior
Hovering over the stroke part of the circle would trigger events.

I'm working on a map with very thick borders like that.

**Comment by anandthakker** [comment]
👍 thanks for the report & example @stevage

**Comment by stevage** [comment]
For comprehensiveness I'll point out that a workaround is to use two circle layers of different radius rather than a stroke outline, but there may be cases where that's inconvenient or worse for performance or whatever.
