### ISSUE TITLE
Collision detection bug

### ISSUE THREAD

**Issue by dannybloe** [mapbox/mapbox-gl-js#5428]
**mapbox-gl-js version**: 40.1
We have several layers with text but somehow it seems that the collision detection fails. See screenshot.
![screen shot 2017-10-09 at 14 51 17](https://user-images.githubusercontent.com/2369994/31338904-557c3660-ad01-11e7-9687-bbd94a2d834c.png)

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained JSFiddle that demonstrates the issue?

**Comment by dannybloe** [comment]
Here it is: [https://jsfiddle.net/jaapl/f4azehk9/14/](url)

**Comment by jfirebaugh** [comment]
Thanks! Current versions of Mapbox GL JS don't support collision detection between separate sources. We're working on that in #5150.
