### ISSUE TITLE
Print area of map different than what is displayed—right side is cropped

### ISSUE THREAD

**Issue by rdlugosz** [mapbox/mapbox-gl-js#5432]
**mapbox-gl-js version**: 0.40.1

### Steps to Trigger Behavior

 1. Set browser width to something medium-sized (like 1000px wide)
 2. Visit https://www.mapbox.com/mapbox-gl-js/examples/
 3. Notice the right-hand side of the map includes water to the right of "Tom's River"
 4. Press `cmd-p` to get a print preview
 5. Notice that the right edge of the map is now cropped to the left of the original display; it cuts of all of the water and most of the "Tom's River" label.

### Expected Behavior

The printed version of the map should contain roughly the same information as what is shown before pressing Print.

### Actual Behavior

The map is truncated (cropped) on the right-hand side. The left side does not seem to be impacted.

**Comment by jfirebaugh** [comment]
Most likely this will be a page CSS/browser/OS-specific issue. I can't reproduce the issue in Chrome 62 on macOS. Is there a particular browser/OS combination that's producing the issue for you?

**Comment by rdlugosz** [comment]
See attached screenshot from Chrome 62 on macOS. Notice that the map in the print preview is cropped from the right compared to the map shown in the full browser screen (you can only see the bottom edge in this screen shot, but obvious enough because of the water).

<img width="1087" alt="screen shot 2017-10-26 at 11 35 45 am" src="https://user-images.githubusercontent.com/402328/32062315-271a7a18-ba42-11e7-814f-63f462db222c.png">

**Comment by jfirebaugh** [comment]
Looks like the expected behavior to me: the page is reflowed to fit the width of the printed page.

**Comment by rdlugosz** [comment]
Expected to us doesn’t necessarily mean acceptable to the user. Consider a scenario where this was a photograph being displayed & when the user prints the right edge is cropped away instead of something more reasonable (like shrinking to fit).

I’m open to suggestions as to how to address this. Here are a couple of thoughts I had:
1. When the available width changes, the current contents of the GL Canvas are scaled to fit within the space, just like you would with a photo. (Not sure if this is possible.)

2. Add some JS that catches the change to a print media query and re-renders the map (along with its various bounds settings, layers, etc.) at a smaller size. 

3. Render two maps, one that’s hidden on print and a second, smaller map that is only shown on print but attempts to follow changes made to the first map.

Am I missing some obvious CSS property that would cause the canvas to behave differently when it overflows the printable area? Would appreciate any suggestions you may have.

**Comment by jfirebaugh** [comment]
Defining print-specific styling is something that a page author is responsible for -- it's not something that Mapbox GL JS can or should try to control. As you suggest: some pages may want to reflow to the width of the printed page, some may want to fix a minimum width, some may want to resize or hide certain elements. In general, `@media print {  … }` in your CSS is the way you specify the desired behavior.

**Comment by bart-1990** [comment]
@rdlugosz did you find a (CSS) solution to fix this?

**Comment by locomo** [comment]
this fixed it for me (in @media print {})

```
	.mapboxgl-canvas {
		width: 100% !important;
	}
```
