### ISSUE TITLE
Collision detection: false positives?

### ISSUE THREAD

**Issue by jaapster** [mapbox/mapbox-gl-js#5439]
**mapbox-gl-js version**: 0.40.1

I just noticed something strange.

In this pitched map, there are two symbols that are not colliding. When rotating the map, the pink one is hidden.

![ezgif-2-a15b98c841](https://user-images.githubusercontent.com/1597572/31377230-a7e7e9a2-ada7-11e7-95ec-6d8b069f125d.gif)

I can't figure out why this is happening. I would expect the pink one to stay visible.

Another thing that I don't think is right is that the collision boxes for both symbols are oriented flat on the map. In order to accurately detect any collisions, I would expect them to have the same orientation as the pink and blue images.

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained JSFiddle that demonstrates the issue?
