### ISSUE TITLE
Actors don't properly clean up callback references

### ISSUE THREAD

**Issue by tgecho** [mapbox/mapbox-gl-js#5443]
**mapbox-gl-js version**: 0.40.1

### Steps to Trigger Behavior

 1. Load any map (for example: https://www.mapbox.com/mapbox-gl-js/examples/)
 2. Count the number of callbacks retained by the worker actors:
    On the example page, run this in the console: `document.getElementById('demo').contentWindow.map.style.dispatcher.actors.reduce((total, actor) => Object.keys(actor.callbacks).length + total, 0)`

### Expected Behavior
The number of callbacks should rise and fall back to 0

### Actual Behavior
The number of callbacks continues to climb as you interact with the map

#### Background / Details
I'm investigating some an apparent memory leaks (in a much more complicated scenario with auto refreshing data), and I noticed references were being held open by this issue. Basically, [the actor saves a callback](https://github.com/mapbox/mapbox-gl-js/blob/master/src/util/actor.js#L45), but in some cases the worker never calls back since many if its methods don't use the `done` param. The primary culprits seem to be setLayers and updateLayers in [source/worker.js](https://github.com/mapbox/mapbox-gl-js/blob/master/src/source/worker.js), though I noticed others.

Experimentally clearing them with `map.style.dispatcher.actors.forEach(a => a.callbacks = {})` seems to somewhat bring memory usage back down, though not completely.

**Comment by jfirebaugh** [comment]
Good catch!

**Comment by tgecho** [comment]
I'm trying my hand at a fix for this and I've noticed that `loadTile` is another leaky event type. It has a callback, so retaining it is correct, but apparently it doesn't always get called back, especially when zooming/panning.
