### ISSUE TITLE
Is there anyway to know whether it is zoom in/out when using touch event?

### ISSUE THREAD

**Issue by Altiano** [mapbox/mapbox-gl-js#5452]
I try to change the pitch based on zoom level.
Right now it is works fine when using wheel.

But when using (zoom) touch, it is hard to figure out when should I change the pitch.
This is because there is no way to know whether it is zoom in/out from event object.
 
What I done so far when using wheel, is to attach a native call back to wheel event so that I know whether it is zoom in/out by ready the property `deltaY`.

**Comment by Scarysize** [comment]
Store the current zoom of the map and compare it to the zoom after the a zoom event. If the new zoom value is greater than the old, the map was zoomed out (and vice versa).

```js
let lastZoom = map.getZoom();

map.on('zoom', () => {
  const currentZoom = map.getZoom();
  if (currentZoom > lastZoom) {
    // zoom in
  } else {
    // zoom out
  }

  lastZoom = currentZoom;
});
```

**Comment by Altiano** [comment]
@Scarysize yup that's good..

Just curious, why not add another variable to `event` object to let us know zoom in/out?

**Comment by Altiano** [comment]
@Scarysize hit a major problem.
I wasn't able to control how much zoom level on every wheel event if I listening for zoom level.
Any idea?

**Comment by jfirebaugh** [comment]
I second @Scarysize's recommendation. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
