### ISSUE TITLE
Incorrect rendering order with raster layer

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#5466]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

```
layers: [
        {
          id: 'img_w',
          type: 'raster',
          source: 'img_w',
        },
        {
          id: 'isobands',
          type: 'fill',
          source: 'isobands',
          paint: {
            'fill-color': 'blue',
            'fill-outline-color': 'green'
          }
        }]
```

### Expected Behavior
mapbox-gl-js 0.40.0
![image](https://user-images.githubusercontent.com/1522494/31615611-b26444c8-b24f-11e7-940a-51cd40cdcad2.png)

### Actual Behavior
mapbox-gl-js 0.41.0

![image](https://user-images.githubusercontent.com/1522494/31615529-7561fb10-b24f-11e7-9419-2642e4e27356.png)

**Comment by lbud** [comment]
Thanks @jingsam! Confirmed; here is a [fiddle to reproduce](https://jsfiddle.net/lbud/r1sm611n/4/). Bisected to efd018f2df2ff99bd285d04e6ed7a56ddf666a8f. Disabling depth testing on raster layers causes this to suffer the same fate as https://github.com/mapbox/mapbox-gl-js/issues/2074. @mollymerp I'm not up to speed on that PR — is disabling depth testing required to achieve its end?

(Also, looking around in various draw_* functions makes me suspect we could reproduce this effect for a few other layer types as well…)

In the meantime if this is blocking anyone, a workaround is to set `fill-opacity: 0.99` on the affected layer.

**Comment by mollymerp** [comment]
Oooh thank you for the report @jingsam and for bisecting @lbud! I'll look into a fix for this.
