### ISSUE TITLE
[suggestion] Graceful fallback into mapbox.js

### ISSUE THREAD

**Issue by silicakes** [mapbox/mapbox-gl-js#5468]
## Motivation
Although webGL is supported by most modern devices, some are lacking the resources to compute and maintain various interactions.
In a good case - the performance will be decreased, but more the often, the app will crash.

I'd like to suggest a unifying API that will serve as a bridge so that transitioning from one library to another, won't require an additional code base.

## Design Alternatives
Although a bridging interface is the first idea that comes to mind, several alternatives are possible:

* Maintain two separate code bases and decide which one to use
* Allow limitation of some of the GL features, as an alternative "lite" library (something in the form of mapbox-gl-js-lite): unsupported APIs will defer into doing nothing, thus maintaining the same logic for both apps
* Creating a set of optimization and profiling tools in order to gain a better understanding of mapbox-gl-js' resource comsumption.

## Design advantages/disadvantages
In my opinion, a design or at least a suggestion to the implementation of one, should be suggested by the official mapbox documentation.

A few points I had in mind:
* Creating a bridged API can take a while and will eventually require tweaking the original code base
* Using a lite version of the application, doesn't promise an efficient resource consumption
* Profiling and optimizing will require a redesign and decoupling of the entire library, which might take a long while, or even not being worth of the effort.

## Implementation
A possible form of performance optimization, might include a place a developers could pass their own rendering/memory management implementations.

A possible form of a Bridged API might include mapping to mapbox.js' APIs while unsupported features will through informative warnings, without doing more than that

Another possibility is to create a documentation that suggest ways of achieving the above, without any changes to either of the libraries.

As this is a discussion, I'd be more than happy to hear your thoughts and get a better grasp as to where the wind blows.
Should the idea mature enough, I'd be more than happy to expand it with gists/PR's.

**Comment by jfirebaugh** [comment]
Thanks for the suggestion @silicakes. We've considered this, but concluded that bridging is best done at the application level, not in a generic library. A generic library would have to limit itself to the subset of functionality that is available in both Mapbox GL JS and Mapbox.js, would come with a long list of caveats and gotchas, and would require significant development investment and ongoing support. It's not something we plan to do at this time.

**Comment by silicakes** [comment]
@jfirebaugh - thanks for the quick reply, I understand the significance of developing these features.
Should we resort into solving the issue, I'll gladly share some insights here, for future generations.
