### ISSUE TITLE
Question: How do write render tests?

### ISSUE THREAD

**Issue by sanjin-saric** [mapbox/mapbox-gl-js#5472]
Hello,

I would like to know the process of making one render test. I understand that the idea is to to compare the pixels of two images, but I don't know how to get the expected.png image. Can anyone give me some pointers? The documentation in `test` folder is rather obscure.

**Comment by mourner** [comment]
This is documented in the [readme here](https://github.com/mapbox/mapbox-gl-js/tree/master/test/integration). In particular, you can run `UPDATE=1 node test/render.test.js your-test-name` to update the `expected.png` image.
