### ISSUE TITLE
queryRenderedFeatures throws error if map has layer type 'heatmap'

### ISSUE THREAD

**Issue by johnnyflinn** [mapbox/mapbox-gl-js#5473]
**mapbox-gl-js version**:

### Steps to Trigger Behavior
 1.   Copy heatmap example
 2.  Create event that triggers queryRenderedFeatures(e.point). I used mousemove
 3.  See Console Log

Plunkr: https://plnkr.co/edit/i8eyFV4ZvHEED16jg4DM?p=preview
Add access token and run.
### Expected Behavior
No error thrown.
### Actual Behavior
Throws uncaught TypeError: e[n].queryRadius is not a function.  While I'm not looking to query features in the actual heatmap layer, I do wish to query other created layers that share the map with the heatmap layer.  If the heatmap layer is 'visible', this error will always be thrown, preventing the results of the function from ever returning.  Setting the heatmap's layer property 'visibility' to 'none' allows queryRenderedFeatures to return as expected.

**Comment by reyemtm** [comment]
It looks like the heatmap layer and query layer need to have different sources. 

See an updated Plunkr: https://plnkr.co/edit/4DIEAUvfUUE91EcWMf8b?p=preview

All I did was add the same data again with a different source id.

*Also there is no need for a mapbox api key for simple examples like this - see the blank style in the link above.*

**Comment by johnnyflinn** [comment]
Thanks a lot for the fix.   
Is this by design?  Seems redundant to add duplicate sources.

**Comment by johnnyflinn** [comment]
After fiddling with it some more, if you specify the layers array option with the evented layer, the error is resolved.
`map.on('mouseenter', "earthquakes-point", function(e) {
      let features = map.queryRenderedFeatures(e.point,{
      layers: ['earthquakes-point']
    })
    console.log(features)`

See Plunk: https://plnkr.co/edit/z8T716p6NkL7hhUf8bEi?p=preview

It still seems redundant to have to specify both the layer the event is to occur as well as the array of layers in the queryRenderedFeatures option.

**Comment by veuncent** [comment]
I had the same problem (mapbox-gl.js v0.41.0) and @reyemtm 's answer solved it for me. No need to add the layer id in the map.on() call. 

Thanks!

**Comment by jfirebaugh** [comment]
cc @mourner
