### ISSUE TITLE
Convert queryRenderedSymbols to run entirely in viewport coordinates

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#5475]
Follow up to PR #5150.

`queryRenderedFeatures` converts a viewport-geometry query into tile coordinates and then queries the `FeatureIndex` of each tile for results. That used to include a query to a tile-specific `CollisionTile` for symbol results, but it now forwards symbol queries to the global/viewport-aligned `CollisionIndex`, where the tile unit query geometry is converted back to viewport coordinates.

The current approach works fine and I don't think the round-trip coordinate transformation is a performance bottleneck, but we can probably refactor this to be simpler by moving `queryRenderedSymbols` out of the tile-based `FeatureIndex`.

**Comment by ChrisLoer** [comment]
This doesn't matter that much, but while doing the native port of #5150 it occurred to me that even with the current tile-based query architecture, it's unnecessary to re-project the collision boxes, since the projected box coordinates are already stored in the `GridIndex` and it's easy to modify `GridIndex` to return them as part of a query.

**Comment by ChrisLoer** [comment]
Marking this as a bug because the current tile based implementation of `queryRenderedFeatures` won't include tiles with symbols that "bleed over" into adjacent tiles (if the query only intersects the adjacent tile). Doing the query entirely against the global collision index would solve this problem.

**Comment by geografa** [comment]
Adding this test case as a good example of  where this is failing:
https://jsfiddle.net/x1fLbnzg/1/

Zooming in to markers labeled `F` and `1` demonstrate how the markers that are not clickable when spanning over into adjacent tiles:

![markerthing](https://user-images.githubusercontent.com/134753/38433967-a6a42180-3981-11e8-96fc-f2ca29bd4cba.gif)

![ohnoes](https://user-images.githubusercontent.com/134753/38434032-da5f0986-3981-11e8-95b1-47c9b94446d0.gif)

cc @ChrisLoer @malwoodsantoro

**Comment by ChrisLoer** [comment]
Fixed in #6497.
