### ISSUE TITLE
Add a coordinate-depending visibility property to layers.

### ISSUE THREAD

**Issue by max-simon** [mapbox/mapbox-gl-js#5479]
## Motivation
Imagine a map for one city only. With a visibility property depending on the coordinates of the features it would be possible to hide all features out of the city.

### Mock-Up
The user would see only features inside a given area.
The developer could generate a polygon in which the features are presented.

### Implementation
Create a paint-property *restricting-polygon* or something like this which accepts a (Multi)Polygon. The result would be, that only features, which are inside this polygon, are presented. 
Another option could be to add a method to Data-Objects, which accepts a (Multi)Polygon and deletes all features outside this polygon.
The union of polygons and features could be done with *turf*.

**Comment by jfirebaugh** [comment]
→ #5847
