### ISSUE TITLE
Build fails when using mapbox-gl webpack 3 and babel-minify-webpack-plugin

### ISSUE THREAD

**Issue by viperfx07** [mapbox/mapbox-gl-js#5483]
**mapbox-gl-js version**: 0.39.1

### Steps to Trigger Behavior

 1. Set up Mapbox with webpack 3
 2. Mapbox is used with import mapboxgl from 'mapbox-gl'.

### Expected Behavior
Mapbox can be successfully uglified.

### Actual Behavior
When building for production, Uncaught ReferenceError: z is not defined.
It's related to #4359, but I'm not sure how to make it working for babel-minify-webpack-plugin

I'm aware that the error was caused by `comparison` flag on UglifyJS, but it doesn't work when I specify the Babel Minify Webpack Plugin options like this:
`MinifyJsPlugin({
 flipComparisons: false,
 simplifyComparisons: false
})`

adding 
` module:{
   ...
   noParse: /(mapbox-gl)\.js$/
  ....
}
` on webpack setttings doesn't work as well

Thanks for your help!

**Comment by viperfx07** [comment]
Found the workaround

````
import MinifyJsPlugin from 'babel-minify-webpack-plugin';

webpackSettings: {
    plugins:[
        ...
        MinifyJsPlugin({  builtIns:false })
        ...
    ]
}
````

**Comment by anandthakker** [comment]
Thanks for posting it back here!
