### ISSUE TITLE
Tap on mobile in Framework7 throws "Cannot read property 'x' of null" because startPos only defined in onMouseDown

### ISSUE THREAD

**Issue by neekfenwick** [mapbox/mapbox-gl-js#5485]
Reproducible case: https://codepen.io/neekfenwick/pen/dVaZEd
__MapBoxGL version v0.41.0 from CDN__

Steps:
1/ open above URL __on mobile device or similar with touch support__ e.g. Chrome on Android
2/ connect dev tools
3/ tap on the map

Expected result:  Nothing much.
Actual result: Uncaught TypeError: Cannot read property 'x' of null

See attached screenshot.

It looks like the tap fires through onClick, which is bound to the 'click' event (bind_handlers.js line 40) but onClick tries to use `startPos` local variable:

    `function onClick(e            ) {
        const pos = DOM.mousePos(el, e);

        if (pos.equals((startPos     ))) {
            fireMouseEvent('click', e);
        }
    }`

Unfortunately, `startPos` is only defined in onMouseDown:

`startPos = DOM.mousePos(el, e);`

Is this a bug or am I missing something?
![startpos assignment in onmousedown](https://user-images.githubusercontent.com/266415/31765376-602d1148-b4ee-11e7-892b-4beff80e4f95.png)
![startpos usage](https://user-images.githubusercontent.com/266415/31765377-60608dfc-b4ee-11e7-9122-ec2d63646e0a.png)

**Comment by neekfenwick** [comment]
I think wrapping my example in a Framework7 app caused the problems, but I'm not sure about this any more.

I'm having trouble reproducing the bug today.  I had the idea that Framework7 might be doing something nasty with the event handlers, so I edited my Codepen to remove framework7, thinking it would operate like jsfiddle and save a new version of the codepen, but I ended up overwriting my old Codepen.  When I forked and tried reverted my changes, I had lost the original exact Codepen with the error.  Putting framework7 back into it did not reproduce the original error.

I've ended up with two codepens, neither of which seem to trigger the error:

Original codepen, with f7 removed then re-added: https://codepen.io/neekfenwick/pen/dVaZEd

Plain non-framework7 example: https://codepen.io/neekfenwick/pen/VMRLqv

Frustrating :/

The original line of code triggering the exception was in mapbox/point-geometry/index.js:

```
equals: function(other) {
        return this.x === other.x &&
               this.y === other.y;
    },
```

called from onClick in my original screenshot in onClick.

FYI I will be on a trip from Sat 21 until Thurs 26 and unlikely to reply.

**Comment by jfirebaugh** [comment]
Hi @neekfenwick -- unfortunately, we're unable to debug interactions with 3rd party frameworks. If you can provide a minimal self-contained example that points to this being a bug with Mapbox GL JS, we can take a look.

**Comment by neekfenwick** [comment]
Understood @jfirebaugh thank you.  The framework7 forum turned up a solution, to add `no-fastclick` class to the map (or an element that contains it).  re: https://framework7.io/docs/fast-clicks.html

**Comment by mgd722** [comment]
Thanks for leaving this up, @neekfenwick!  You've just ended a very frustrating hours-long search.
