### ISSUE TITLE
Labels and icons fade out and in

### ISSUE THREAD

**Issue by ttsirkia** [mapbox/mapbox-gl-js#5491]
**mapbox-gl-js version**:

3e51b6c

### Steps to Trigger Behavior

 1. Call `setFilter` (and open a popup which seems to be irrelevant)

### Expected Behavior

The map remains the same, the popup opens.

### Actual Behavior

All labels and icons in one specific data source fade out with a transition animation and instantly back in.

![mapbox-bug](https://user-images.githubusercontent.com/2797729/31814992-fa8351d0-b593-11e7-9919-db22616a74f2.gif)

The purple circle and its text as well as the gray labels are in different data source (vector tile) than the blinking elements which are all in the same vector tile.

**Comment by anandthakker** [comment]
Thanks for reporting this issue @ttsirkia !

Could you please provide self-contained example reproducing this issue?   Having an example to work with will make it much more likely that we can successfully diagnose and solve the problem.

**Comment by ttsirkia** [comment]
Was this closed because this has been fixed or I haven't had time to create JSFiddle example?

**Comment by jfirebaugh** [comment]
Hi @ttsirkia, thanks for responding. We get a lot of issues that don't have enough information to diagnose and fix the reported issue, so we close issues labeled "needs information" after a while without a response (a week or so). If you find the time to create a JSFiddle we'll be happy to reopen the issue and investigate.

**Comment by ttsirkia** [comment]
It seems tricky to create a minimal example but I found the position in the commit history when this appears. Commit 2835484 is the last one that works, 1355618 does not produce a working build and the next commit 3e51b6c has this bug.

**Comment by ttsirkia** [comment]
You can see the issue here: https://julia.dy.fi/map/view?mode=bulletins#13.94/60.0685/23.663 Just hover mouse above those purple circles as in the GIF animation. Commit 3e51b6c is in use.

**Comment by jfirebaugh** [comment]
cc @ChrisLoer @ansis

**Comment by ansis** [comment]
thanks for the example @ttsirkia

I think the `map.setFilter(...)` is triggering a tile reload which `CrossTileSymbolIndex` is not handling properly. @ChrisLoer I think we can fix this when porting the -native CrossTileSymbolIndex changes back to -js.

**Comment by ttsirkia** [comment]
Yes, I confirm that commenting out `setFilter` resolved the issue so the bug is there, not showing the popup. Thanks for investing the issue! I replaced the Mapbox script with version 0.41.0 but I'm happy to test this again when there is a patch available.

**Comment by jfirebaugh** [comment]
This issue can also be observed on the "Filter features within map view" example. http://localhost:8080/mapbox-gl-js/example/filter-features-within-map-view/, if you run `yarn start-docs` locally.
