### ISSUE TITLE
Fullscreen does not work

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#5492]
When

**mapbox-gl-js version**:
0.41.0

MacBook Air 2017
macOS High Sierra
Chrom dev 63

### Steps to Trigger Behavior

 1. https://jsfiddle.net/jingsam/fwonyptc/1/
 2. click fullscreen control

### Expected Behavior

Map is fullscreened

### Actual Behavior

A black screen was shown.

**Comment by jingsam** [comment]
Use Shift + Command + F works as expected.

**Comment by mollymerp** [comment]
@jingsam thanks for the report – webkit doesn't automatically change the css rules for fullscreen elements, so we need to add `width: 100%` on the map container for `FullscreenControl` to work as expected. https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API

https://jsfiddle.net/yeuc45n7/

We should fix this in core though.
