### ISSUE TITLE
Layer "ref" property undocumented

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#5497]
I can't see anywhere in the [current documentation](https://www.mapbox.com/mapbox-gl-js/style-spec) where the "`ref`" property (by which a layer's style properties come from another layer) is documented. It's weird, I'm sure I have seen this documentation previously.

**Comment by jingsam** [comment]
The "ref" now is implemented internally in the latest mapbox-gl-js. So you don't need to declare in your styles explictly now.

**Comment by stevage** [comment]
Does that mean that no "ref" parameter will ever show up in a style generated by Studio?

**Comment by jingsam** [comment]
yes

**Comment by jfirebaugh** [comment]
Yes, we removed this documentation since it's now an internal implementation detail only.

**Comment by stevage** [comment]
Ok, thanks. Just curious because I still noticed it in a style I just downloaded, but maybe it hadn't been updated yet or something.
