### ISSUE TITLE
ScrollZoomHandler does not always apply options properly

### ISSUE THREAD

**Issue by BartCorremans** [mapbox/mapbox-gl-js#5501]
**mapbox-gl-js version**: v0.41.0

### Steps to Trigger Behavior

 1. Call `map.scrollZoom.disable()` (or set `scrollZoom` to `false` in options when creating map)
 2. Call `map.scrollZoom.enable()`
 3. Call `map.scrollZoom.enable({ around: 'center' })`

### Expected Behavior

Calling `enable()` the second time should apply the options object and make the scroll zoom handler scroll around the centre of the map instead of the cursor.

### Actual Behavior

The scroll zoom handler does not apply the options on the second call.

The opposite is true also; calling `enable()` with options and then calling `enable()` again without options will not properly reset the options.

https://jsbin.com/tupovojawu/1/edit?html,js,output

**Comment by mollymerp** [comment]
@BartCorremans thanks for using mapbox and for the detailed report! 
As the function is written, if you call `map.scrollZoom.enable()` when the control is already enabled, it returns without doing anything, and this is consistent with the rest of our mouse/keyboard handlers. Your example works if you add a call to `map.scrollZoom.disable()` in the first timeout. 

It might make sense to add a method that allows users to set the `around` option separately from enabling/disabling the handler. 

https://jsbin.com/tupovojawu/1/edit?html,js,output

https://github.com/mapbox/mapbox-gl-js/blob/c5554ff48335a9afdaba0453ef503618683146e9/src/ui/handler/scroll_zoom.js#L61-L62

**Comment by mollymerp** [comment]
adding a setter for `around` falls under #4029

**Comment by BartCorremans** [comment]
Thanks for the reply!
