### ISSUE TITLE
Fix bugs preventing mapbox-gl-style-spec package on NPM from being used externally

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5502]
Current issues with the mapbox-gl-style-spec package:

- Flow types in `expression/*.js` prevent the package from being used directly: `require('@mapbox/mapbox-gl-style-spec')` fails with syntax errors
- The absence of a `browserify: { transform: ["unflowify", "bubleify", "./build/strictify"] }` setting in `package.json` prevents browserify from being able to bundle a program that uses `@mapbox/mapbox-gl-style-spec` as a dependency (except maybe if that build used the "global transform" antipattern).
- Published npm package does not include `flow-typed` directory from the root repo.  I haven't actually checked whether any types declared there are used within `src/style-spec`, but even if they aren't now, it is likely that they will be in the future.
- (from #5522) Usage of `let` and `const` without `"use strict";` is forbidden in Node v4.0.  More broadly: as of now, the style-spec package needs to be usable in Node v4.0 and IE 11, both of which have limited ES6 support.

After resolving the above issues, we should also add a build test that simulates installing @mapbox/mapbox-gl-style-spec outside of the gl-js repo and attempts to (a) require it in node, (b) bundle it.

**Comment by anandthakker** [comment]
cc @davidtheclark @dasulit the issues above apply to the version of the style spec that includes expressions code.  I've got this on my radar, but please let me know if/when it's imminently blocking you and we'll expedite.

**Comment by davidtheclark** [comment]
Thanks, @anandthakker.

> Published npm package does not include flow-typed directory from the root repo

If I understand the intent right, I have a warning for you: In my experience, including this directory will *not* fix the problem (of a Flow-enabled consumer not understanding the types), because the consumer's Flow will not know about this directory. The only way I've been able to get Flow types in an npm package to work for the consumer's Flow is to `import type` every type that's used.

**Comment by lamuertepeluda** [comment]
Will we be able again to load only the style modules for creating filters even in a non-browserify(ed)/un-flowified environment (e.g. webpack, or just the mapbox-gl CDN) in next releases?

**Comment by anandthakker** [comment]
@lamuertepeluda I believe the current issue to be the only thing blocking that.  After it is fixed, it will be possible to load the modules in the `@mapbox/mapbox-gl-style-spec` package from a plain Node environment.

**Comment by anandthakker** [comment]
Fix published as `@mapbox/mapbox-gl-style-spec@v10.0.1`

**Comment by lamuertepeluda** [comment]
Hi,

I think the package "@mapbox/mapbox-gl-style-spec" is broken again (versions `10.0.1` and `10.1.0`)... 😢 

Using webpack:

`import styleSpec from '@mapbox/mapbox-gl-style-spec';`

leads to

```
index.js?fd90:formatted:31 Uncaught Error: Cannot find module 'sort-object'
    at s (index.js?fd90:formatted:31)
    at eval (index.js?fd90:formatted:41)
    at Object.31../reference/latest.js (index.js?fd90:formatted:3462)
    at s (index.js?fd90:formatted:38)
    at eval (index.js?fd90:formatted:41)
    at Object.38../composite (index.js?fd90:formatted:8066)
    at s (index.js?fd90:formatted:38)
    at e (index.js?fd90:formatted:51)
    at eval (index.js?fd90:formatted:51)
    at i (index.js?fd90:formatted:4)
```

**Comment by lamuertepeluda** [comment]
It works in node.js, though... 
I will try to import the featureFilter function using the define plugin or by injecting it into the global namespace, as a workaround, but I don't like this approach. It would be nice to have just an unflowified working module. Possibly also with a dev build.

**Comment by anandthakker** [comment]
@lamuertepeluda I believe this is due to https://github.com/mapbox/mapbox-gl-js/issues/5674 and has been fixed in master.

**Comment by lamuertepeluda** [comment]
Thanks @anandthakker, I'll wait for next tag release :)

**Comment by lamuertepeluda** [comment]
@anandthakker 

I tried to build from master... I get now a different error when importing into webpack 😞 

```
Uncaught Error: Cannot find module 'util'
    at s (index.js?fd90:1)
    at eval (index.js?fd90:1)
    at Object.4.util (index.js?fd90:461)
    at s (index.js?fd90:1)
    at eval (index.js?fd90:1)
    at Object.52../composite (index.js?fd90:11034)
    at s (index.js?fd90:1)
    at e (index.js?fd90:1)
    at eval (index.js?fd90:1)
    at eval (index.js?fd90:1)
```

what about also publishing a version "10.1.1" of this package with these annoying bug fixed? Or do you plan to do along with next mapbox release?

**Comment by lamuertepeluda** [comment]
I think I have found some culprits of the above:

[This line](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/error/validation_error.js#L2) and [this line](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/expression/compound_expression.js#L6) are requiring node modules, namely `util` and `assert`, right? They are not found when importing into webpack (and probably browserify too).

How to build ignoring/stripping them out for browser?

**Comment by lamuertepeluda** [comment]
You have to pardon my browserify-ignorance, I'm more a webpack guy, but I found out that removing `--no-builtins --insert-global-vars=\"__filename,__dirname\"` from `build` command fix it.

```diff
-    "build": "../../node_modules/.bin/browserify style-spec.js --no-builtins --insert-global-vars=\"__filename,__dirname\" --standalone=mapboxGlStyleSpecification | ../../node_modules/.bin/derequire > dist/index.js",
+    "build": "../../node_modules/.bin/browserify style-spec.js --standalone=mapboxGlStyleSpecification | ../../node_modules/.bin/derequire > dist/index.js",
```

Of course I'm not sure if this is really enough from the module point of view, but after doing this I could

```bash
npm run build && npm pack
cp mapbox-mapbox-gl-style-spec-10.1.0.tgz ../../../style-spec-build
z my-project
npm i <path-to>/style-spec-build/mapbox-mapbox-gl-style-spec-10.1.0.tgz
```

And happily 

```js
const styleSpec = require('@mapbox/mapbox-gl-style-spec');
// or even better
import { featureFilter } from '@mapbox/mapbox-gl-style-spec';
```
😃 

There is also a minor but I will open another issue for that, since the README is wrong

What does the `'g'` stands for in the generated filter function? https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/feature_filter/index.js#L72

**Comment by jfirebaugh** [comment]
Thanks for investigating @lamuertepeluda. Could you open a fresh issue with these findings? Thanks!

**Comment by lamuertepeluda** [comment]
@jfirebaugh done! see #5871
