### ISSUE TITLE
Mapbox Draw - Free Draw Tool

### ISSUE THREAD

**Issue by nribeiro90** [mapbox/mapbox-gl-js#5503]
**mapbox-gl-js version**:
Hello,

Currently the mapbox has a drawing tool. However, it only allows you to draw through geometric shapes.

My suggestion is to develop a free drawing tool on the map.

### Steps to Trigger Behavior

 1. A new drawing format is added to the mapbox-draw;
 2. The user clicks on map and move the mouse;
 3. On mouseup, the drawed area is filled.

### Expected Behavior

More interactive maps, that allow to filter data with the drawed area.

Thanks,
Nuno

**Comment by mourner** [comment]
Thanks for the suggestion! Did you mean to report this in the gl-draw repo though? This one is for GL JS core issues.
