### ISSUE TITLE
Multiple maps and multitouch input not working

### ISSUE THREAD

**Issue by navenedrob** [mapbox/mapbox-gl-js#5504]
**mapbox-gl-js version**: 0.41.0

### Steps to Trigger Behavior

 1. Add multiple maps to a page
 2. Open on multitouch device (in my case, a [multitouch table by Ideum](https://ideum.com/products/touch-tables))
 3. Try to use two or more maps at same time

### Expected Behavior
Maps are able to be controlled independently but at same time. Touch interactions should route to each map correctly based on touch.

### Actual Behavior
Maps are not able to be controlled independently, only one at a time.

Temporary example page: http://place-names.shi.ikshare.com

**Comment by navenedrob** [comment]
Would this be functionality I would have to implement manually? If so, what best method would be used to route these touches to each map so that my expected behavior is realized?

**Comment by stevage** [comment]
Just to make sure I understand, you want to simultaneously have one finger on each map, embedded within the same page? What's your use case?

**Comment by navenedrob** [comment]
@stevage My use case is the linked example. Hard to imagine outright but I'm creating four workspaces, each with its own map, that is to be used by up to 4 users. Those 4 users would be touching the table top (e.g. the touch screen) at the same time. So far that I've tried it, if you're interacting with one map, then another person tries to interact with another map only one of the maps works.

I'm thinking this is likely maybe because of the way the touches and or event listeners are being handled or attached.

**Comment by navenedrob** [comment]
Here are some pics to help visualize the interaction by multiple people with the table:

![two-84-ideum-touchtables](https://user-images.githubusercontent.com/792055/32018304-80a76dee-b997-11e7-889f-c5cb26fed4fc.jpg)
![colossus-855x480](https://user-images.githubusercontent.com/792055/32018305-80b94fe6-b997-11e7-9e8d-321be2fce16c.jpg)

**Comment by navenedrob** [comment]
@stevage Did you have any additional input?

**Comment by navenedrob** [comment]
Here is a simple repo with a basic setup that can be used to test. Pull it up on your localhost on a multitouch device.

https://github.com/interactiveknowledge/project_multitouch_test

**Comment by stevage** [comment]
> Pull it up on your localhost on a multitouch device.

Huh, I don't even know how I'd do that. But I deployed it to Gist for you:

http://rawgit.com/stevage/e560ed502ebfff8667f1aef81abae7fe/raw/2505a9c3b7c7b692cfc958f4ee2404da27cdb006/index.html

**Comment by jfirebaugh** [comment]
The reason this happens is that the drag pan handler captures move events at the `document` level. Without support for pointer events and [setPointerCapture](https://developer.mozilla.org/en-US/docs/Web/API/Element/setPointerCapture) (which are not supported by WebKit), this is the only way to continue the pan with a gesture that goes outside the bounds of the map container.

**Comment by jfirebaugh** [comment]
→ #6446
