### ISSUE TITLE
Wrong z-order of raster in 0.41

### ISSUE THREAD

**Issue by flp-gpc** [mapbox/mapbox-gl-js#5509]
I have an issue when displaying a vector layer above a raster layer.

Everything was working well in v0.39:
```
  "layers": [
    {
      "id": "relief",
      "type": "raster",
      "source": "srtm",
      "paint": {
        "raster-opacity": 1
      }
    },
    {
        "id": "water",
        "type": "fill",
        "source": "osm",
        "source-layer": "water",
        "paint": {
          "fill-opacity": 1,
          "fill-color": "#89bddd"
        }
    }
  ]
```

When I switch to the v0.41, the raster is wrongly displayed above all other vector layers. Is there anything specific to the 0.41 or is this an issue ?

**Comment by mourner** [comment]
Yep! It's a bug. Tracking in #5466. Closing this one as duplicate.
