### ISSUE TITLE
TypeError: Cannot read property 'sdfIcons' of undefined

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5516]
The code example in #5447 is broken in an additional way on `master`, producing the error "TypeError: Cannot read property 'sdfIcons' of undefined".

`this` should be `bucket`:

https://github.com/mapbox/mapbox-gl-js/blob/005d60ecb689016a1b491ab45485e444ff3bf766/src/symbol/symbol_layout.js#L88

Needs a fix and a regression test.

cc @ChrisLoer

**Comment by ChrisLoer** [comment]
Fixed with #5525.
