### ISSUE TITLE
Custom parsing/processing/modification of vector tiles after loading

### ISSUE THREAD

**Issue by waissbluth** [mapbox/mapbox-gl-js#5527]
Hello,

Is there currently a way to extend/customize/replace the method doing the parsing of incoming vector tiles for a layer? Or a way to tap into the tile data before rendering, to perform operations on properties in-place?

This would be useful, for example, to "deserialize" stringified properties ([like these](https://github.com/mapbox/tippecanoe/issues/155)) before the styling and rendering occurs, and before there is a more definitive solution to [this](https://github.com/mapbox/vector-tile-spec/issues/75) or [this](https://github.com/mapbox/mapbox-gl-js/issues/2434) issue.

**Comment by anandthakker** [comment]
Hi @waissbluth, thanks for your question.  Extensibility for 'sources' like you describe is something we're planning to work on, but it's still in early (i.e. design, not implementation) stages right now.  You can track it over at #2920
