### ISSUE TITLE
Split "curve" expression into "step" and "interpolate" expressions

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5528]
In retrospect, `"curve"` is overgeneralized:

* `["curve", input, ["step"], ...]` and `["curve", input, anything else, ...]` have different stop signatures -- step has an extra output value. This makes it awkward for them to share the same expression name.
* `step` is universally supported by paint and layout properties, while other interpolation types are supported only by certain properties. This is something we need to call out in documentation, and it would be simpler to be able to say "Supports `"interpolate"` expressions" rather than "Supports all `curve` interpolation types"/"Supports only `step` interpolation".

Instead, there should be two expressions:

* `["step", input, stop_output_0: OutputType,
    stop_input_1: number, stop_output_1: OutputType,
    stop_input_n: number, stop_output_n: OutputType, ... ]`
* `["interpolate", interpolation, input, 
    stop_input_1: number, stop_output_1: OutputType,
    stop_input_n: number, stop_output_n: OutputType, ...]`

Note that I've also swapped the position of the `interpolation` and `input` arguments for `interpolate`. I think `["interpolate", ["exponential", base], input, ...]` reads better than `["interpolate", input, ["exponential", base], ...]`.

This would be a breaking change, so it's best to get it made now, before adoption is widespread. The following will need to be updated:

* GL JS implementation
* GL JS docs
* Expression blog post
* Expression help guide
* Styles

**Comment by jfirebaugh** [comment]
> Note that I've also swapped the position of the `interpolation` and `input` arguments for `interpolate`. I think `["interpolate", ["exponential", base], input, ...]` reads better than `["interpolate", input, ["exponential", base], ...]`.

It was actually already in this order, but incorrectly swapped in the docs.

**Comment by anandthakker** [comment]
cc @davidtheclark @dasulit @colleenmcginnis @nickidlugash @aparlato

**Comment by jfirebaugh** [comment]
Proposed implementation in #5542.

This is a breaking change, and I wish we had made it before the first GL JS release with expressions, but in the long term think it's worth it to improve the clarity of one/two of the most important expression operators.

Comments and concerns welcome!

**Comment by davidtheclark** [comment]
I like the clarification here 👍 ⚡️

**Comment by stevage** [comment]
As an outsider, I like this. I find some of the new expression stuff really very abstract and a bit hard to wrap my head around, and "curve" was an example of that. Anything that makes using Mapbox-GL-JS more concrete is welcome.

**Comment by mourner** [comment]
I like this. Also, `interpolate` is a better word for what's going on under the hood. Breaking compatibility should be OK if it's done early, before full-scale adoption of the feature.
