### ISSUE TITLE
Revise terminology for classifying expressions

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#5531]
We lack an unambiguous vocabulary for classifying expressions. [The style specification says](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions):

> The `expression_name` is the name of a specific expression, e.g. `'*'` or `'case'`. Each `argument_i` is either a literal value (a string, number, boolean, or `null`), or else another expression in the array form above.

The wording “a specific expression” conflates the concept of an _expression_ (an instance of the value that a paint/layout property or filter is set to) with the subset of expressions being described. Even “expression name” implies that “expression” is the entire subset of expressions. Meanwhile, the “[Get started with Mapbox GL JS expressions](https://www.mapbox.com/help/mapbox-gl-js-expressions/)” guide refers to “expression types”, which risks confusion with an expression’s evaluated data type.

Making matters worse, the style specification also describes a subset of expressions as “property expressions”. This term is supposed to refer to expressions that contain references to feature properties, but you set a paint or layout property to an expression whether or not the expression refers to a feature property.

I propose the following terminology:

* _expression_ — an instance of the value that a paint or layout property or filter is set to
* _expression operator_ — the first part of the expression array; by metonymy, the subset of expressions that begin with a given operator
* _data expression_ — an expression that contains the `get` operator somewhere within
* _camera expression_ — an expression that contains the `zoom` operator somewhere within (with a nod to #4154)

One thing going in favor of _expression operator_ is that filters are classified by “operators” too.

/cc @mapbox/gl @colleenmcginnis

**Comment by davidtheclark** [comment]
> an instance of the value that a paint or layout property or filter is set to

@1ec5 I'm having some trouble understanding this phrase. Could you clarify a bit more?

**Comment by 1ec5** [comment]
Sure: you set `text-field` or `filter` to an expression (which may contain subexpressions).

**Comment by colleenmcginnis** [comment]
>Meanwhile, the “Get started with Mapbox GL JS expressions” guide refers to “expression types”, which risks confusion with an expression’s evaluated data type.

I did struggle to find a neutral word to use here that would also be intuitive. I think "expression operator" is a good fit.

**Comment by stevage** [comment]
Are `curve` and `let` and `concat` examples of "expression operators" too? That seems a bit awkward, as they would be statements or functions in other languages.

**Comment by 1ec5** [comment]
This syntax doesn’t distinguish between binary and n-ary operators. “Function” could work too, but it comes with some baggage, having been applied to property functions in the pre-expression days.
