### ISSUE TITLE
Mapbox GL JS wrongly sending "Cache-Control: no-cache"

### ISSUE THREAD

**Issue by fabriciodosanjossilva** [mapbox/mapbox-gl-js#5538]
**mapbox-gl-js version**:
0.41.0

### Steps to Trigger Behavior

 1. Copy example from https://www.mapbox.com/mapbox-gl-js/example/map-tiles/ and create a index.html file. Open in it browser.
 2. Zoom in slowly into a specific point
 3. Clear browser network (download) history
 4. Zoom out slowly
 5. Note in browser network history that every tile is loaded again. No cache is made.
 6. Inspect HTTP request headers. Note that although Mapbox tile servers sends "Cache-Control:max-age=43200,s-maxage=604800" on all responses, Mapbox GL JS wrongly sends "Cache-Control: no-cache" on all requests.

### Expected Behavior
Mapbox Gl JS should allow browser to cache tiles whenever possible, respecting Cache-Control max-age responses.

### Actual Behavior
Mapbox GL JS forces browser to ignore local cache and to download every tile again. This is making my Mapbox bill skyrocket.

**Comment by jfirebaugh** [comment]
Mapbox GL JS doesn't have control over the browser's caching behavior. You probably have "Disable cache" checked in devtools:

![image](https://user-images.githubusercontent.com/98601/32089155-1c2d3b30-ba9d-11e7-8547-e6088de1e775.png)

**Comment by fabriciodosanjossilva** [comment]
Your're wright. I'm sorry.
