### ISSUE TITLE
keep-upright for single-glyph vertical text may be broken

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#5544]
I haven't tested this yet, but while porting #5150 to native, I noticed what looks like a vestigial use of `symbol.vertical` at https://github.com/mapbox/mapbox-gl-js/blob/574052653fbaf59ae8e6d7e1a571ed47bac0f83e/src/symbol/projection.js#L302.

I'm pretty sure `vertical` isn't a member of the `placedSymbols` anymore. We should be using `symbol.writingMode == WritingMode.vertical`. I believe what will happen is that single-glyph CJK labels will be upside down over a 90 degree range.

Needs a regression test.

/cc @ansis @1ec5

**Comment by 1ec5** [comment]
> I believe what will happen is that single-glyph CJK labels will be upside down over a 90 degree range.

I’m not seeing any issues with [this way](http://www.openstreetmap.org/way/240494750) tagged `name=桥` when rendered in the Mapbox Streets style.

**Comment by ChrisLoer** [comment]
Thanks for that example, @1ec5. It looks like the `keepUpright` problem is being hidden by vertical text just being disabled entirely for single glyph labels.
