### ISSUE TITLE
Discourage developers from adding canvas sources to style JSON

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#5545]
The [`canvas` source type](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-canvas) documentation should state that `canvas` sources are only to be used at runtime in JavaScript code, never in style JSON. This source type is inherently platform-specific: some platforms like iOS have no concept of a rendering surface associated with a unique identifier. A platform-specific source type has no place in a file format that’s intended to be portable across platforms.

Ideally, `canvas` would be omitted entirely from the style specification. However, GL JS uses the style specification to document its runtime styling API, so that isn’t an option right now.

/cc @anandthakker

**Comment by jfirebaugh** [comment]
1c719f159c9e6ce0695d7f67020caeec45017338
