### ISSUE TITLE
Reserved words in style-spec documentation should be in lower case in sidebar

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#5549]
I have often found it confusing that the names of source and layer types are given in title case in the sidebar:

- Vector, Raster, GeoJSON, Image, Video, Canvas
- Background, Fill, Line, Symbol, Raster, Circle, Fill-Extrusion, Heatmap

These are all special words which, once lowercased, are entered verbatim in the style spec document. (As opposed to words like "Array", "Glyphs" and "Feature data" which only appear in the documentation.) Other special words such as "layers", "anchor" and "delay" do appear in lowercase in the sidebar. 

I can't see much justification for the inconsistency, especially since the actual headings they refer to are indeed lowercase ("geojson", "fill-extrusion" etc).

<img width="167" alt="screenshot 2017-10-30 17 01 26" src="https://user-images.githubusercontent.com/678344/32156875-fd0a3e0c-bd93-11e7-836d-4bf4c5373004.png">

**Comment by jfirebaugh** [comment]
Agreed. I don't think there's any particular reason they're capitalized.
