### ISSUE TITLE
[Question]Need help for drawing route in different direction

### ISSUE THREAD

**Issue by StevanCakic** [mapbox/mapbox-gl-js#5551]
Hi, 

I have a question. I need help for this problem:

![image](https://user-images.githubusercontent.com/13205146/32162536-a8ae919e-bd59-11e7-8a35-8d5b2321a92a.png)

but I want this:

![image](https://user-images.githubusercontent.com/13205146/32162281-b931328e-bd58-11e7-91b2-fe9ea955b939.png)

So I want to change direction for the route if curve goes to another "map" (same map but boundaries are exceeded). Any suggestions? 

Note: Red line is imaginary line which represents map boundaries(max/man lat and lng)

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
