### ISSUE TITLE
Consider eliminating 'heatmap-intensity' property

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5552]
Currently, we have two style properties, `heatmap-intensity` and `heatmap-weight`, that affect heatmap output in the same way: they both act as multipliers in the kernel density calculation; however, `heatmap-intensity` must be _feature constant_, whereas `heatmap-weight` is intended to be _feature dependent_.   The intent is for users to use `heatmap-weight` to specify the data-driven effect of each point on the heatmap output, and to use `heatmap-intensity` to "globally" control the effect of _every_ point on the output.

The advantage of the split is that, since `heatmap-intensity` is 'feature constant', it can be changed very quickly at runtime, whereas changing `heatmap-weight` is a more costly operation.  The disadvantage is that we have two properties that do the same thing, which can be confusing.

Is quickly changing the global intensity of the visualization a common enough use case to make the extra complexity in the spec worthwhile?   My gut instinct is no--I think if someone is wanting to change a heatmap layer, it's much more likely that they really want to change the _content_, i.e. the data that's being visualized.  What do others think?

**Comment by anandthakker** [comment]
@mapbox/gl

**Comment by mourner** [comment]
I'm personally in favor of keeping two properties. 

The multipliers, while essentially the same, are used for two distinct things — `weight` is for changing the underlying data, and `intensity` as a purely presentational aspect of the visualization, like `radius` and `opacity`. If we require building complex expressions such as `["*", ["number", ["get", "point_count"]], ["interpolate", ...]` (or nested interpolations) to use both (which is essential for a good heatmap visualization), it will make building a Mapbox Studio UI for heatmaps exceptionally difficult. 

Another reason to keep the two is the ability to change intensity in real time, which seems pretty useful —
 e.g. having a UI slider to adjust, or smoothly transitioning between two intensities for a visualization that combines several distinct datasets that can be switched.

Totally understand the disadvantages though too. Having two very similar properties is certainly confusing.

**Comment by ryanbaumann** [comment]
I'm 👍 for two style properties.  The UI slider use case is the most relevant here - I want to be able to change the visual intensity of a heatmap independant of the underlying data ramp.

**Comment by anandthakker** [comment]
> The multipliers, while essentially the same, are used for two distinct things — weight is for changing the underlying data, and intensity as a purely presentational aspect of the visualization

A counterpoint: why would we introduce a distinction like this for heatmaps, when we don't have it for any other layer type?   The same arguments would seem to apply to, say, using `circle-radius` as a data visualization layer.

> The UI slider use case is the most relevant here - I want to be able to change the visual intensity of a heatmap independant of the underlying data ramp

@ryanbaumann can you say more about this?  What's a practical application for this type of slider?  When I tried to imagine how I'd use a slider, I kept coming back to changing the underlying data, not just the visual intensity -- but this may well be a failure of imagination on my part :)

**Comment by mourner** [comment]
Closing as stale since there seems to be not enough interest to pursue this.
