### ISSUE TITLE
Add data-driven-styling support for `text-font` 

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#5568]
Data-driven styling for font stacks would be very useful, especially now that expressions have landed. Per chat with @jfirebaugh, this was infeasible before per-tile glyph atlases, but feasibility has not been reviewed since per-tile glyph atlases landed.

We are also now working on [expression constraints](https://github.com/mapbox/mapbox-gl-js/issues/5393) that will allow the use of data-driven expressions with limited output values.

/cc @anandthakker @aparlato

**Comment by jfirebaugh** [comment]
This looks relatively straightforward to implement now.

**Comment by nickidlugash** [comment]
@jfirebaugh that's great! Is there an ETA yet for implementation? Is it blocked by https://github.com/mapbox/mapbox-gl-js/issues/5393? Please let me know if there's anything I can do to help out.
