### ISSUE TITLE
Border of translucent polygon with fill-color or fill-pattern shows artifacts

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#5570]
**mapbox-gl-js version**: current Studio 

### Steps to Trigger Behavior

 1. Upload the following SVG file to a sprite of a style in Mapbox Studio:
[bright_green_fill.svg.zip](https://github.com/mapbox/mapbox-gl-js/files/1431974/bright_green_fill.svg.zip)

 2. Use it as a fill pattern for a polygon.

### Expected Behavior

The polygon border shows no artifacts.

### Actual Behavior

The polygon border shows artifacts.

![image](https://user-images.githubusercontent.com/20856381/32244234-34c22b72-be78-11e7-96e6-2fae51949f90.png)

**Comment by pathmapper** [comment]
This issue happens also with `fill-color` instead of `fill-pattern`:

https://jsfiddle.net/2p9qed2u/

![image](https://user-images.githubusercontent.com/20856381/32654829-dbcf2d76-c60b-11e7-88dc-056b7a9d366d.png)

**Comment by jfirebaugh** [comment]
The current `fill-outline-color` implementation depends on a GL feature with limited platform support. We're tracking a different way to render fill outlines in #2080 -- in the meantime, if you have precise requirements for the rendering of fill outlines, we recommend using a separate line layer to draw the outline.
