### ISSUE TITLE
SourceCache checks status 404 but status code not sent in postMessage

### ISSUE THREAD

**Issue by deanm** [mapbox/mapbox-gl-js#5574]
When one of the web workers makes an AJAX request that fails, it will throw an AJAXError (with status: Number) back to the callback.  Ex:

https://github.com/mapbox/mapbox-gl-js/blob/25e5f1dd9d55835d9572e15893740aa90aae9eeb/src/source/vector_tile_source.js#L107

However, when this goes through the actor, this AJAXError is simply converted to a string for the message posted back to the main thread:

https://github.com/mapbox/mapbox-gl-js/blob/25e5f1dd9d55835d9572e15893740aa90aae9eeb/src/util/actor.js#L68

It looks like _tileLoaded however is specifically trying to handle the condition for 404:

https://github.com/mapbox/mapbox-gl-js/blob/25e5f1dd9d55835d9572e15893740aa90aae9eeb/src/source/source_cache.js#L228

However the `err` object will have just been a generic `Error` recreated from the string:

https://github.com/mapbox/mapbox-gl-js/blob/25e5f1dd9d55835d9572e15893740aa90aae9eeb/src/util/actor.js#L77

So it seems like there is some logic to handle 404 errors specially, however as the network fetches are usually done by the source workers, the status code doesn't make it back to that code.

**Comment by mollymerp** [comment]
fixed in #6126
