### ISSUE TITLE
how to map views count decrease.

### ISSUE THREAD

**Issue by achalnexus** [mapbox/mapbox-gl-js#5582]
I have already premium account in mapbox.
I am using personal mapbox access token. 
We have implement mapbox in our project. Our project link is https://cali.usedirect.com/CaliforniaSaturnStaging/. 

I have some question regarding radius mapview count.

1)	How much time after update mapview count in my account.
2)	If I am use this mapbox version. If each and every time I am call this api so increase count or not.?
<script src='https://api.mapbox.com/mapbox-gl-js/v0.38.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v0.38.0/mapbox-gl.css' rel='stylesheet' />
3)	If each every time call access token call then increase or not.? 
4)	How to calculation mapvew count and I am how to check mapview count in my application.
5)	How to reducing my map view count

**Comment by anandthakker** [comment]
Hi @achalnexus , thanks for using Mapbox.  You may find answers to some of your questions in the [Account FAQ](https://www.mapbox.com/help/account-faq/).  If this doesn't answer all of your questions, please contact Mapbox Support at https://www.mapbox.com/contact/support/
