### ISSUE TITLE
geojson as url source + turf.js + manipulation of subset of features' properties

### ISSUE THREAD

**Issue by shawnmgoulet** [mapbox/mapbox-gl-js#5591]
**mapbox-gl-js version**: >=0.27.0 <=0.38.0

(1) I also have a `Feature` geojson type of a single polygon adding to my map from a url source.
(2) I have a `FeatureCollection` geojson type of ~4k polygons adding to the map also from a url source.

I use turf.intersect between (1) and (2) to select the intersecting polygons of (2).
I then store the intersecting polygons [a sub-set of (2)] to an array.
I then manipulate the values of some properties of those intersecting polygons with simple math.

I now want to update (2) with the resulting values of the array.

I would love to use something like `setData` to update (2), but that is not possible for a subset which also is not (a) a geojson data object or (b) a url to one as specified in the [docs](https://www.mapbox.com/mapbox-gl-js/api/#geojsonsource#setdata).

Hopefully I have explained this sufficiently.  If so, what is the suggested workflow in this case?

**Comment by mollymerp** [comment]
Hi @shawnmgoulet thanks for using Mapbox! 
This issue tracker is only intended for feature requests and bug reports. For "how do I ...?" questions like this, I suggest you reference our help pages https://www.mapbox.com/help/ or StackOverflow https://stackoverflow.com/tags/mapbox-gl-js and if you still can't find an answer, you can contact Mapbox support at https://www.mapbox.com/contact/support/.
