### ISSUE TITLE
How to set cluster:false for source programmatically?

### ISSUE THREAD

**Issue by benderlidze** [mapbox/mapbox-gl-js#5595]
Is there a way to set cluster:false for source programmatically and update the map?
I can set it with `map.getSource("source")._options.cluster = false` but as I understand it is a private method and anyway nothing changes after all even after
`map.getSource('icons').setData(collection);`
Thanks

**Comment by jfirebaugh** [comment]
There isn't a way to change this option after the source is created. It's expensive to do so, so if you need to switch between clustered and non-clustered frequently, you might be best off creating two sources and toggling between them using layer `visibility` properties.

**Comment by goors** [comment]
this would be awesome to have. something like brake cluster `this.map.getLayer('cluster').brake` or something like that. Adding N sources and then switching visibility is just something that is unsustainable on long run.

**Comment by zoutepopcorn** [comment]
This guy helped me:
https://stackoverflow.com/questions/70109527/mapbox-change-source-property
