### ISSUE TITLE
Ionic 3 with Mapbox-gl map not appear

### ISSUE THREAD

**Issue by mrezzaaa** [mapbox/mapbox-gl-js#5596]
Help me please . 
I'm using `mapbox-gl@0.41.0 ` installed using npm 

and here my `ionic info`
`cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.16.0
    ionic (Ionic CLI) : 3.16.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.1
    Cordova Platforms  : android 6.2.3 ios 4.4.0
    Ionic Framework    : ionic-angular 3.8.0

System:

    Android SDK Tools : 26.1.1
    ios-deploy        : 1.9.2 
    Node              : v8.6.0
    npm               : 5.3.0 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0.1 Build version 9A1004 

Environment Variables:

    ANDROID_HOME : /Users/{Username}/Library/Android/sdk

Misc:

    backend : pro
I'm using this tutorial 
[Ionic 2 with Mapbox](http://gowriter.blogspot.co.id/2017/03/integrating-mapbox-gl-js-map-into-ionic.html)

### Expected Behavior
I want to showing mapbox in specific page.

### Actual Behavior
Map placement is loaded like Mapbox logo & link on left bottom of the screen.
and Map improvement link also appear in right bottom of the screen .
Finding similar problem and trying using crosswalk and map is still not showing .
Added 
`  <meta http-equiv="Content-Security-Policy" content="default-src 'self' blob: file:;child-src blob: file: ;img-src data: blob: http: https: file: ;script-src 'unsafe-eval' 'unsafe-inline' file: blob: http: https:;style-src 'unsafe-eval' file: http: https:;connect-src 'unsafe-eval' ws://* http://* https://*  https://*.tiles.mapbox.com https://api.mapbox.com">
`
on head of index.html 
also added 
`<access origin="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="file://*" />
    <allow-intent href="blob:*" />
    <allow-intent href="blob:http:*" />
    <allow-intent href="blob:file:*" />
    <allow-navigation href="*" />
`
on config.xml and still not works 

![screenshot_1509909358](https://user-images.githubusercontent.com/14961709/32418234-7a5362fe-c298-11e7-9eb6-be284f56ef53.png)

BUT working when using `ionic serve` 

<img width="760" alt="screen shot 2017-11-06 at 2 29 47 am" src="https://user-images.githubusercontent.com/14961709/32418335-6732a39a-c29a-11e7-9d19-168a3da012b2.png">

If i'm check on logs 
`
WebGL Supported
blob:file%3A///64c19b5d-d1af-4688-b2e9-f5255bd72731:145 Uncaught SyntaxError: Unexpected token ILLEGAL

blob:file%3A///64c19b5d-d1af-4688-b2e9-f5255bd72731:145 Uncaught SyntaxError: Unexpected token ILLEGAL

blob:file%3A///64c19b5d-d1af-4688-b2e9-f5255bd72731:145 Uncaught SyntaxError: Unexpected token ILLEGAL

blob:file%3A///64c19b5d-d1af-4688-b2e9-f5255bd72731:145 Uncaught SyntaxError: Unexpected token ILLEGAL`

Please help me :(

**Comment by jfirebaugh** [comment]
Hi @mrezzaaa, thanks for using Mapbox GL. Unfortunately, we are unable to debug complex interactions with third-party frameworks such as Iconic. If you believe this is a bug in Mapbox GL itself, please create a self-contained demo that shows the issue independently of Ionic.

**Comment by mrezzaaa** [comment]
Hi @jfirebaugh ,
Thanks for your response .
I think Mapbox gl bug on several browser . 
Because when i'm using in chrome on desktop it's works well also chrome on mobile.
But not on mobile webview :( .

**Comment by leondroidgeeks** [comment]
I get the same error. Mapbox says it cannot initialize WebGL. Also I think just displaying a map using a popular Framework like Ionic isn't a complex interaction........

**Comment by dmorfav** [comment]
Hi @jfirebaugh still persist this bug? i intended using mapbox with ionic and not render the map in android native when i testing
