### ISSUE TITLE
Never resolve tokens after evaluating a text-field or icon-image expression

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5599]
We want to deprecate and remove `{}` token interpolation in favor of string expressions like `concat`, so we should avoid setting the precedent that interpolation is supported in combination with expressions. A text-field or icon-image expression that evaluates to a string containing `{` and `}` characters should always treat those characters literally, and never do interpolation, regardless of whether the expression is feature-constant or not.

cc @anandthakker

**Comment by jfirebaugh** [comment]
Note that this implies that any auto-conversion of stop-based functions to expressions needs to convert `{}`-interpolation to equivalent `get` and `concat` expressions.

**Comment by dpieri** [comment]
It took me a while to figure out what this change was. Am I correct in concluding that my existing styles that use tokens like this will still work?

```json
"icon-image": "{shield}-{reflen}",
```

**Comment by jfirebaugh** [comment]
Yes, correct, the change affects only expressions, not constant string values.
