### ISSUE TITLE
If I use react-map-gl ,can I import mapbox-gl at the same time.

### ISSUE THREAD

**Issue by Wwangchen** [mapbox/mapbox-gl-js#5607]
import MapGL, { SVGOverlay } from 'react-map-gl';
import mapboxgl from 'mapbox-gl';
I want to know the MapGL and the mapboxgl are the same object ?
Is it correct I use like this? I look forward to your reply.

**Comment by jfirebaugh** [comment]
This would be a question to ask in the react-map-gl repository: https://github.com/uber/react-map-gl.
