### ISSUE TITLE
Disable layer loading when maxzoom exceeded

### ISSUE THREAD

**Issue by mrdrprofuroboros** [mapbox/mapbox-gl-js#5610]
Hello there!
I'm wondering how can I prevent layer loading when your map zoom is more than tile spec maxzoom. So I could have, say, 5 layers and each of then has to be shown exactly on the diapason [minzoom, maxzoom], but now they overlay one another, and if you load your map on the highest zoom all of them will be present. Is that possible with current means of mapbox?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
