### ISSUE TITLE
"history.replaceState" error on Mobile Safari 

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#5612]
We're seeing a spike in occurrences of an error message on our embed page (i.e. https://api.mapbox.com/styles/v1/mapbox/outdoors-v9.html)

```
SecurityError: Attempt to use history.replaceState() more than 100 times per 30.000000 seconds
```

Research suggests this error message is new to iOS 9.3.  

**mapbox-gl-js version**: v0.40.1

### Steps to Trigger Behavior

 - Navigate to "https://api.mapbox.com/styles/v1/mapbox/outdoors-v9.html?access_token=..." in Safari on an iPhone running iOS 9.3 or later 
 - Zoom and pan around the map continuously for 30 seconds 

### Expected Behavior

No error messages

### Actual Behavior

```
SecurityError: Attempt to use history.replaceState() more than 100 times per 30.000000 seconds
```

**Comment by anandthakker** [comment]
I don't have a cord with me to plug in my phone and see the console, but I'm curious: do you have to move the map very frequently to reproduce this?  100 times per 30 seconds, being > 3 times per second, seems abnormally frequent for `moveend` events.

**Comment by lucaswoj** [comment]
@anandthakker 👉  https://github.com/mapbox/mapbox-gl-js/pull/5613#issuecomment-342950732
