### ISSUE TITLE
Reproduction for distortion problem

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#5614]
I have post the issue in #5265  about the  distortion rendering.

And now I created a live example to verify this problem, I load the same vector tiles by mapbox and openlayers, while ol render the data correctly.

Mapbox([Live demo](https://exotfboy.github.io/mapbox-line-demo/index.html#10/76.0185/20.6732)):
![image](https://user-images.githubusercontent.com/16457917/32527627-f38d67dc-c469-11e7-9ce2-1963b820b6a4.png)

> The line is drawn with  no problem at first, once you zoom in  you will find the distortion,when keep zoom in , the distortion disappear.

Openlayers([Live demo](https://exotfboy.github.io/mapbox-line-demo/ol.html)) works perfectly:

![image](https://user-images.githubusercontent.com/16457917/32527834-cd0f9016-c46a-11e7-87f5-028dff2535e3.png)

**Comment by jfirebaugh** [comment]
Thanks -- could you please add this as a comment on the existing issue?

**Comment by exotfboy** [comment]
I add this as a comment on the origin post at the first, but got no attention after two days, so I delete that comment and post it here.

I added that again just now.
