### ISSUE TITLE
Sometimes, a symbol beacoms invisible when zooming the map

### ISSUE THREAD

**Issue by sunhuiqiang9004** [mapbox/mapbox-gl-js#5617]
**mapbox-gl-js version**:0.41.0

### Steps to Trigger Behavior

 1.Here is the style
``` javascript
{
      id : 'location-layer',
      source : 'location-source',
      type : 'symbol',
      minZoom : 0,
      maxZoom : 22,
      filter : [
        'all',
        ['==', '$type', 'Point'],
        ['==', 'render', 'ips-location']
      ],
      layout : {
        'icon-image' : '{icon_sails}',
        'icon-size' : 1.5,
        'icon-offset' : [0, 0],
        'icon-rotate' : rotate || 0,
        'icon-rotation-alignment' : align || 'auto'
      },
      paint:{
        'icon-opacity':1
      }
    }
```
 2.call map.getSource('location-source').setData(data)  every  40ms
 3.zoom the map

### Expected Behavior
The symbol is always visible
### Actual Behavior
Sometime the symbol becomes invisible

![image](https://user-images.githubusercontent.com/18169804/32534693-44cc3798-c41c-11e7-86b9-cfb3e58774d3.png)

![image](https://user-images.githubusercontent.com/18169804/32534629-0da745fa-c41c-11e7-9ebc-d12eaf308221.png)

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained JSFiddle that demonstrates the issue?
