### ISSUE TITLE
heatmap-color isn't transitionable

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5630]
The docs for `heatmap-color` claim that it is "![image](https://user-images.githubusercontent.com/98601/32581299-37a07872-c49e-11e7-8ede-7b17ba4d799e.png)", but I don't think that's true.

**Comment by ryanbaumann** [comment]
@jfirebaugh It does show [transition effects](https://jsbin.com/nenazosimi/edit?html,output)

![](https://cl.ly/2c0i45190Z1v/download/Screen%20Recording%202017-11-08%20at%2004.25%20PM.gif)

However, the bug below effects it

1. Heatmap-color does not change render state on the first setPaintProperty update (ticketed here https://github.com/mapbox/mapbox-gl-js/issues/5627)

**Comment by jfirebaugh** [comment]
@ryanbaumann In your example, there's a `setInterval` function registered that changes the `heatmap-color` every 50 ms. That forces the color ramp to be recalculated, effectively simulating a property transition. Without that forced 50 ms refresh, it wouldn't transition.

**Comment by jfirebaugh** [comment]
cb647733f07d5cf5093c35f5aa40a357e3e778bb
