### ISSUE TITLE
Why coordinates are modified on zoom

### ISSUE THREAD

**Issue by JiDai** [mapbox/mapbox-gl-js#5638]
Hi,

I have one question. I put a pen to illustrate https://codepen.io/JiDai/pen/vWgxBq

**mapbox-gl-js version**: 0.41

### Steps to Trigger Behavior

 1. Go to pen
 2. Hover the dot marker, see the coordinates
 3. zoom out, see different coordinates

**Comment by anandthakker** [comment]
GeoJSON data is converted to a tiled format (like vector tiles) internally.  A vector tile's geographic precision varies based on zoom level, and, therefore, coordinates for a given feature may vary slightly from one zoom level to another.  This issue is tracked in #4733; closing as a duplicate.

**Comment by JiDai** [comment]
Thanks
