### ISSUE TITLE
Icon collision boxes don't account for `icon-text-fit`

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#5641]
See discussion at https://github.com/mapbox/mapbox-gl-js/pull/5632/#discussion_r149846100.

`CollisionFeature` takes a `Shaping` as an input for determining the size of collision boxes. This works fine for text, but for icons with `icon-text-fit: true`, the quads generated for the icon by `getIconQuads` may not match the `Shaping`.

I suspect the right fix here is to move most of the `icon-text-fit` logic into `shapeIcon`.

My guess is this hasn't been a big deal in practice because when people are using `icon-text-fit` they also use `icon-allow-overlap` and `icon-ignore-placement`, and rely on the matching text's collision box. But it'd be better not to have that gotcha.

/cc @jfirebaugh @ansis @anandthakker

**Comment by kkaefer** [comment]
This will be fixed by https://github.com/mapbox/mapbox-gl-js/pull/8741
