### ISSUE TITLE
Error assigning curve expression to 'fill-outline-color' property

### ISSUE THREAD

**Issue by mbloch** [mapbox/mapbox-gl-js#5642]
**mapbox-gl-js version**: 0.41.0

### Steps to Trigger Behavior

 1. Using the JS api, assign the following expression to the `fill-outline-color` property of a fill-type layer's `paint` object:
    `['curve', ['linear'], ['zoom'], 8, 'rgba(255,255,255,0)', 9, 'rgba(255,255,255,1)']`

### Expected

Style expression should be applied. The same expression runs correctly when assigned to  `fill-color`.

### Actual behavior

Layer is not rendered, and a runtime error is thrown:
![image](https://user-images.githubusercontent.com/1232222/32629398-0d52d2c6-c567-11e7-91eb-a5bb31a1fedb.png)

### Similar error in the Styles GUI

Clicking the "Enable zoom function" button in the "1px stroke" menu of a polygon layer throws an error.
![image](https://user-images.githubusercontent.com/1232222/32629500-6cd139c2-c567-11e7-98eb-a1f027736dd7.png)

![image](https://user-images.githubusercontent.com/1232222/32629558-9ffc9922-c567-11e7-868a-3607df1a1bf7.png)

**Comment by jfirebaugh** [comment]
Thanks for the report! This was fixed as a side effect of #5573. I've opened a PR adding a regression test to make sure it doesn't come back.
