### ISSUE TITLE
Reduce Flow globals defined in interface files.

### ISSUE THREAD

**Issue by vicapow** [mapbox/mapbox-gl-js#5643]
`Callback`, `Transferable`, `VectorTileFeature` and likely others are types defined globally (this is the default for libdefs) but instead should instead of required explicitly. This is useful when using mapboxl-gl-js in other projects that may have conflicting global type name conflicts.

If I get some time, I'm happy to tackle this, but wanted to get feedback before I start.

Best,

**Comment by vicapow** [comment]
Mind if I also merge the `flow-typed/geojson.js` file to [geojson-types](https://github.com/vicapow/geojson-types) so it can be shared across projects?

**Comment by vicapow** [comment]
Mind if I move the libdef of `@mapbox/unitbezier` to flow-typed?

**Comment by jfirebaugh** [comment]
👍 on explicit requires. I'd prefer to keep the definitions locally controlled though. E.g. for the GeoJSON types, I reviewed several other modules, but none of them fit our needs exactly.

**Comment by vicapow** [comment]
> E.g. for the GeoJSON types, I reviewed several other modules, but none of them fit our needs exactly.
Makes sense. What if you creating a new repo, similar to geojson-types, that I could contribute to? I just want to use the same types across projects. I don't care so much who controls them.
