### ISSUE TITLE
Get method in lru_cache.js  cause confusion.

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#5645]
After I reviewed the `src/util/lru_cache.js`, I found `get(key)` may cause confusion.

In LRU algorithm, when I access a data, the data should stay in cache. But `get(key)` returns the data and deletes it in the cache, this is not I expected. After I checked the other members, I found `getWithoutRemoving` was the method I expected.

Should it be clearly to name these methods as `get` and `getAndRemove` pairs?

**Comment by jfirebaugh** [comment]
Sure, want to submit a pull request?
