### ISSUE TITLE
Performance regression in getRenderedFeatures calls

### ISSUE THREAD

**Issue by symbyte** [mapbox/mapbox-gl-js#5648]
Starting with v0.40.0 (and still present in v0.41.0) I've noticed 2 behaviors when using the `getRenderedFeatures` api that I think worth mentioning:

1. The time that it takes to build the `vtLayers` member in `FeatureIndex` when running `query` has increased from about 680ms for a layer with a GeoJSON feature collection with ~58k features as the source to about 10s for that same layer. (might be related to the recent changes in @mapbox/pbf here: https://github.com/mapbox/pbf/pull/82).
![v0.39.1 run](https://imgur.com/H3R3GSU.png)
![v0.41.0 run](https://imgur.com/OnjhrMK.png)

2. `vtLayers` is sometimes being rebuilt multiple times, sometimes in succession, when using the `queryRenderedFeatures` api on the same GeoJSON feature collection without having changed the visibility of any features. 
![v0.41.0 multiple vtLayers rebuilds](https://imgur.com/CeBjGg0.png)

Any ideas on this? This difference in performance makes the `queryRenderedFeatures` pretty much unusable for layers with more than a few thousand geojson features. 

If any more info is needed I'd be glad to help in any way I can!

**Comment by jfirebaugh** [comment]
cc @mourner

**Comment by mourner** [comment]
This looks strange indeed. Can't be related to recent `pbf` changes because they are only for the proto compiler, not for encoding/decoding itself.

**Comment by symbyte** [comment]
Oh, I see. The change in how strings are read (using a TypedArray instead of a Buffer) was made around a year ago in https://github.com/mapbox/pbf/pull/59, but it seems mapbox-gl-js only started relying on that implementation in v0.40.0. Sorry, my mistake!

**Comment by mourner** [comment]
@symbyte it didn't change how strings are read under the hood for the browser (it doesn't have `Buffer`, this is a Node-specific thing).

**Comment by symbyte** [comment]
Oh, ok. I was just lining up the entries with the call stack I posted above (which was captured in electron, hence its access to Buffer) with changes to the readString method in `@mapbox/pbf`.

**Comment by mourner** [comment]
@symbyte is the regression only happening in Electron, or browsers too?

**Comment by symbyte** [comment]
I threw together a couple of jsbins to find out:
v0.39.1: http://jsbin.com/veniqimuye/2/edit?html,output
v0.41.0: http://jsbin.com/quveruvunu/1/edit?html,output

From what I could tell when messing with these, the performance seems to be about the same. Looks like this could be an electron specific regression due to its use of Node.js constructs.

**Comment by jfirebaugh** [comment]
Ok, assuming this is not something we need to try to work around in gl-js.
