### ISSUE TITLE
Understanding GL Style stops

### ISSUE THREAD

**Issue by mnboos** [mapbox/mapbox-gl-js#5657]
Hi all

I don't understand the Mapbox GL Style "stops" properly. Let's assume the following paint:

```
"paint": {
        "line-width": {
          "stops": [
            [
              9,
              0.5
            ],
            [
              20,
              18
            ]
          ]
        }
      }
```

Is the line-width only evaluated at zoom-levels >= 9 and <= 20? Or what will the line-width be at zoom-level 8, for example?

**Comment by andrewharvey** [comment]
If you do this in Mapbox Studio it will show the function graph.

![zoom-function](https://user-images.githubusercontent.com/117278/32704326-37c53db2-c857-11e7-83f1-af8615cb59c4.png)

It shows that it's a constant function outside of your stop range. So in your case at zoom 8 the width will be 0.5px, and at zoom 21 will be 18px.

PS. You can ask help questions like this on https://stackoverflow.com/tags/mapbox-gl-js or https://gis.stackexchange.com/tags/mapbox-gl-js.

**Comment by mnboos** [comment]
Thanks a lot!
