### ISSUE TITLE
Map-scale to zoom-level mapping

### ISSUE THREAD

**Issue by mnboos** [mapbox/mapbox-gl-js#5658]
Hi all

I wonder where/how you get a corresponding zoom-level for a specific map-scale. Like this, but the other way round:

```python
zoom_level_by_lower_scale_bound = {
    1000000000: 0,
    500000000: 1,
    200000000: 2,
    50000000: 3,
    25000000: 4,
    12500000: 5,
    6500000: 6,
    3000000: 7,
    1500000: 8,
    750000: 9,
    400000: 10,
    200000: 11,
    100000: 12,
    50000: 13,
    25000: 14,
    12500: 15,
    5000: 16,
    2500: 17,
    1500: 18,
    750: 19,
    500: 20,
    250: 21,
    100: 22,
    0: 23
}
```

Thanks for helping

**Comment by jfirebaugh** [comment]
Hi @mnboos -- take a look at the [scale control](https://github.com/mapbox/mapbox-gl-js/blob/5bebe1cd725e9af0c6be25928bdbde468bebdf61/src/ui/control/scale_control.js#L61-L127) for some example code.
