### ISSUE TITLE
Number attributes being detected as Strings

### ISSUE THREAD

**Issue by yoursweater** [mapbox/mapbox-gl-js#5664]
I'm uploading geographical data as tilesets after compressing them with tippecanoe, and I'm noticing that attributes such as population count for a region are being detected as strings by Mapbox.

Accordingly, while I'd like to make a chloropeth map based on population, I'm unable to do so because my property function is treating each of the variables as strings, thus preventing the interval stops from being set/working. There should be some sort of a feature allowing the user to choose what type of variable a number really should be treated as by mapbox. I'm not sure what I can do at this point to get the chloropeth map up and working.

**Comment by anandthakker** [comment]
@yoursweater can you use https://github.com/mapbox/tippecanoe#tippecanoe-decode to confirm that the tippecanoe-generated tiles have the numeric (not string) data you expect?  This will help isolate where the erroneous number=>string change is happening.

Meanwhile, as a workaround, you can use [`"to-number"`](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-types-to-number) in a property expression to coerce the incoming property value to a number.  For example:

```js
{
  "fill-color": [
    "step" // ('step' is the expressions equivalent of "interval" functions
    ["to-number", ["get", "my_property_name"]], // get 'my_name_property' from each feature, but coerce it to a number before using it
    "blue",
    5, "green", // note that, unlike functions, the "stops" are flat, not wrapped in two-element arrays
    10, "yellow"
  ]
}
```

**Comment by yoursweater** [comment]
I feel somewhat silly - it turns out that the numbers were, in fact, being loaded in as strings. I went back and filtered through the data again to correct that. Still, it's good to know that there's a programmatic way to coerce the incoming property value. Thanks!

**Comment by ericfischer** [comment]
You can also coerce the type on the `tippecanoe` side with `--attribute-type`.
