### ISSUE TITLE
mapbox-gl-style-spec package fails when bundled with Browserify

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-js#5674]
**mapbox-gl-js version**: 0.42

### Steps to Trigger Behavior

 1. Create a test directory and install `browserify` and `@mapbox/mapbox-gl-style-spec`.
 2. Add an `index.js` file with:

```js
var styleSpec = require('@mapbox/mapbox-gl-style-spec');
console.log(styleSpec.format({
  layers: []
}));
```

 3. Add an `index.html` file with:

```html
<!DOCTYPE html>
<html lang="en">
<body>
  <script src="./build.js"></script>
</body>
</html>
```

4. Run `npx browserify index.js > build.js`.
5. Open `index.html` in Chrome (where we wouldn't have to worry about any ES2015 business).

### Expected Behavior

Everything goes fine.

### Actual Behavior

Something goes wrong with module resolution:

```
Uncaught Error: Cannot find module 'sort-object'
    at s (_prelude.js:1)
    at _prelude.js:1
    at s (index.js:26)
    at index.js:28
    at Object.r.31../reference/latest.js (index.js:2989)
    at s (index.js:27)
    at index.js:28
    at Object.r.38../composite (index.js:7536)
    at s (index.js:27)
    at e (index.js:32)
```

If I comment out the lines that use `sort-object`, I get the same error for `lodash.isequal`, another external dependency.

**Comment by davidtheclark** [comment]
Another thing to note: Running `node build.js` works just fine. Which means that Node is able to figure out where `'sort-object'` and other dependencies are, but Browserify is not.

**Comment by jfirebaugh** [comment]
Looks like this is caused by the combination of `--no-bundle-external` and `derequire`. @anandthakker, do you recall how you intended this to work?

**Comment by anandthakker** [comment]
Ah, shoot.  This is a mistake.  I'd hoped to use `no-bundle-external` to avoid duped dependencies, but as @jfirebaugh says it's not compatible with `derequire`.  We should just drop `no-bundle-external`.

**Comment by anandthakker** [comment]
@davidtheclark if you're using `browserify` (so that the `browserify: { transform: [] }` configuration in `package.json` will be respected), a workaround is to change `var styleSpec = require('@mapbox/mapbox-gl-style-spec');` to `var styleSpec = require('@mapbox/mapbox-gl-style-spec/style-spec');`
