### ISSUE TITLE
Map fails to load every other try on Windows 10, IE11

### ISSUE THREAD

**Issue by lukeconlon** [mapbox/mapbox-gl-js#5675]
This issue was previously posed on the closed issue #3040, but my customers are still reporting that maps fail to load every other load on IE11. I've been able to reproduce this issue by visiting https://www.mapbox.com/mapbox-gl-js/example/simple-map/ on browserstack with Windows 10, IE11. 

The map will initialize and load on every odd try (i.e. 1, 3, 5, ...), but on every other try it fails to call the map load event and render the map tiles.

I thought v0.40.1 would fix this issue (#5321), but I have tried v0.40.1 and v.0.41.0 and the issue is still present.

**Comment by jfirebaugh** [comment]
Thanks @lukeconlon. Other (open) issue tracking this are #4821 and #4623, so I'm going to close this as a duplicate. Unfortunately, as noted in #3040, this is a fundamental bug in IE which it appears infeasible to work around.

**Comment by lukeconlon** [comment]
@jfirebaugh Thanks for the update, I missed the mention that these issues stem back to the Microsoft security update for IE11.
