### ISSUE TITLE
Query results should contain evaluated style properties

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5677]
The documentation for `queryRenderedFeatures` says:

> Each feature includes a top-level layer property whose value is an object representing the style layer to which the feature belongs. Layout and paint properties in this object contain values which are fully evaluated for the given zoom level and feature.

The second sentence doesn't reflect the current behavior: currently, the `layer` objects in the results are just [`serialize`d layers](https://github.com/mapbox/mapbox-gl-js/blob/cb42e3930a76d5034bd32f03a18d71ee449928a1/src/data/feature_index.js#L235), and `serialize` doesn't produce property values evaluated for the given zoom level or feature. You can confirm this via [this](https://www.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures/) example.

I agree with the intent of the documentation -- since you can already obtain the unevaluated property values via runtime styling APIs, it's more useful to get the evaluated properties. We should fix the behavior to match what's documented.

**Comment by asheemmamoowala** [comment]
Closed by https://github.com/mapbox/mapbox-gl-js/pull/9198
