### ISSUE TITLE
icon-halo-color doesn't work with Map.addImage

### ISSUE THREAD

**Issue by Kilatsat** [mapbox/mapbox-gl-js#5684]
**mapbox-gl-js version**:
0.42.0

### Steps to Trigger Behavior
http://jsbin.com/daqocuxelo/1/edit?html,output

### Expected Behavior
We expect a 2 pixel halo around the cat

### Actual Behavior
There is a larger square around the cat

**Comment by jfirebaugh** [comment]
I think for this to work, you need to supply an image that's actually an [SDF](https://blog.mapbox.com/drawing-text-with-signed-distance-fields-in-mapbox-gl-b0933af6f817), i.e. uses the alpha channel to represent the signed distance from the edge of the icon. The `Cat_silhouette.svg.png` image you're using is just a regular PNG. It happens to work without `icon-halo-color` mostly by chance (the image does have an alpha channel with 0 and 1 values).

**Comment by Kilatsat** [comment]
Ah, so the line `map.addImage('cat', image, {sdf: true});` is not doing an image->SDF conversion of any kind? What would be a better description of that `{sdf: true}` option?

**Comment by jfirebaugh** [comment]
Correct, the `sdf` option is a flag indicating whether the input image is already in SDF form and should be rendered as such, or is just a normal RGBA image.

**Comment by Kilatsat** [comment]
That helps a lot, thanks! I'll direct my efforts toward fixing the example code and making the documentation more clear.
