### ISSUE TITLE
How to use 'interpolate' and 'step'

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#5696]
It looks curve is no longer supported in version 0.42.0, but I do not find clear examples of how to use the new 'interpolate' and 'step'.

I use e.g. this function for flyTo:    
```
map.flyTo({
      center: [lng, lat],
      offset: offSet, 
      zoom: zoom,
      speed: 4.0 
      curve: 0.4
    })
```

What would that be with the new expressions?

**Comment by jfirebaugh** [comment]
The `curve` _expression_ is no longer support. This is unrelated to the `curve` option for `flyTo`. There's been no change to that functionality.
