### ISSUE TITLE
The ScaleControl is missing box-sizing = border-box in the css

### ISSUE THREAD

**Issue by shf123** [mapbox/mapbox-gl-js#5697]
### Steps to Trigger Behavior

 1. Go the mapbox's example site for measuring 
https://www.mapbox.com/mapbox-gl-js/example/measure/

 2. Add scale controller: 
map.addControl(new mapboxgl.ScaleControl({ unit: "metric"}));
 
3. Measure the width of the scalebar

### Expected Behavior
The measurement and the scalebar value should be close.

### Actual Behavior
The difference is too big.

It hopefully becomes more clear when showing two scalebars where I have added "border-box" to the first. 

![image](https://user-images.githubusercontent.com/1443522/32957676-b6329736-cbbc-11e7-81f4-8630362abf8f.png)

![image](https://user-images.githubusercontent.com/1443522/32957719-d48f3824-cbbc-11e7-82df-59c8b013d72e.png)

I think it also makes sense when looking at the code in scale_control.js. As far as I can see, it is assumed that the calculated width should not have an extra padding.

![image](https://user-images.githubusercontent.com/1443522/32957852-1dc469c4-cbbd-11e7-9207-a67e4d85e4e8.png)

**Comment by mollymerp** [comment]
Thanks for the report @shf123. I believe you're right we're not accounting for the 10px of padding we add in to the container. Would you be interested in submitting a PR with this fix?

**Comment by shf123** [comment]
@mollymerp Yes. I have not done many pull request before, so I hope I did it correct here https://github.com/mapbox/mapbox-gl-js/pull/5715
