### ISSUE TITLE
navigationControl compass can't change the pitch

### ISSUE THREAD

**Issue by BrunoSalerno** [mapbox/mapbox-gl-js#5711]
**mapbox-gl-js version**: 0.40

### Steps to Trigger Behavior

 1. Add the navigationControl
 2. Try to change the pitch by clicking the compass of the navigationControl and moving the mouse
 3. The map rotates, the pitch doesn't change

### Expected Behavior
Until version 0.39.1, clicking the compass and moving the mouse would change the pitch of the map

### Actual Behavior
Clicking the compass and moving the mouse only rotates the map

[0.39.1 jsfiddle](https://jsfiddle.net/brunosalerno/m2ugtweL/)
[0.40 jsfiddle](https://jsfiddle.net/brunosalerno/o5gy6czd/)

Maybe related with https://github.com/mapbox/mapbox-gl-js/pull/5157 ? (and @anandthakker comment ?)

**Comment by jfirebaugh** [comment]
Huh, I didn't realize the old version did that!
