### ISSUE TITLE
Big rendering issues in Safari

### ISSUE THREAD

**Issue by BrunoSalerno** [mapbox/mapbox-gl-js#5712]
**mapbox-gl-js version**: 0.42

### Steps to Trigger Behavior

 1. Load the map in Safari (11.0.1)
 
### Expected Behavior
All the features of the map should be rendered

### Actual Behavior
Lines and polygons missing
![](https://cdn.pbrd.co/images/GUe9FRt.png)
The screenshot is taken from the [Navigation Example](https://www.mapbox.com/mapbox-gl-js/example/navigation/)

In versions < 0.42 it works fine.

**Comment by ashleyclough** [comment]
The issue seems to be 0.42.1 - my maps that were working correctly in Safari desktop in 0.42.0 have all lost polygons and lines in 0.42.1. No console messages are shown.

**Comment by mourner** [comment]
@jfirebaugh I bisected this to #5682.

**Comment by dannybloe** [comment]
Maybe it is a good suggestion that before making a new release to at least check if all Mapbox examples still work in all major browsers on all major OS's?
