### ISSUE TITLE
Raster Tile Placement Errors [0.42.1]

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapbox-gl-js#5713]
**mapbox-gl-js version**: 0.42.1

### Steps to Trigger Behavior

 1. Open https://www.mapbox.com/mapbox-gl-js/example/satellite-map/ in Chrome v62 or Firefox v57
 2. Zoom out to z0
 3. Zoom back into z3

![](https://cl.ly/2n190E223c1F/download/Image%202017-11-18%20at%206.46.03%20PM.png)

### Expected Behavior
Raster tiles are placed in the proper tile location in the map context.

### Actual Behavior
Raster tiles are not placed in the proper tile location in the map context.  Higher zoom level tiles are visible at lower zoom levels (i.e. at z0, I can see z1 tiles placed).

The issue seems to only effect raster tiles.  I am unable to reproduce on any vector tile source.

**Comment by jfirebaugh** [comment]
Bisects to b06c86ba3b9a90eac77061076d8aa9f5e6206520.
