### ISSUE TITLE
Maps not rendering correctly in Safari

### ISSUE THREAD

**Issue by jaapster** [mapbox/mapbox-gl-js#5718]
**mapbox-gl-js version**: 0.42.1

### Steps to Trigger Behavior

1. Open any mapbox example in Safari (macOS High Sierra)

### Expected Behavior
I would expect to see all layers in the map

### Actual Behavior
Only point geometries (and background layer?) are visible.

**Comment by jfirebaugh** [comment]
Duplicate of #5712.
