### ISSUE TITLE
Expose map.getImage

### ISSUE THREAD

**Issue by alex3165** [mapbox/mapbox-gl-js#5735]
Hello,

I would need to know if an image has already been added or not, would it be possible to expose a `map.getImage` function? I can see that `addImage` is already "protected":
```
  if (this.imageManager.getImage(id)) {
    return this.fire('error', {error: new Error('An image with this name already exists.')});
  }
``` 
But I would like to avoid the error message and prevent from calling `map.addImage` upfront by checking is the image is already there in my application.

**mapbox-gl-js version**: 0.42.2

**Comment by ArturAntonov** [comment]
I found some error. And 'try-catch' not helping.
```
try {
          this.map.addImage('arrow-head', image);
        } catch (e) {
          console.log('image with id "arrow-head" is already exists');
        }

```
Even if i use 'try-catch' i still get error.
```
vendor.bundle.js:44292 Error: An image with this name already exists.
    at t.addImage (vendor.bundle.js:44178) [angular]
    at e.addImage (vendor.bundle.js:44266) [angular]
```
Is the method "addImage" async?

**Comment by mollymerp** [comment]
@alex3165 we would gladly accept a PR implementing this method!
