### ISSUE TITLE
layer without paint property after map.getLayer(Id) in 0.42.2

### ISSUE THREAD

**Issue by rendrom** [mapbox/mapbox-gl-js#5746]
After update to mapbox-gl version 0.42.2 my application broke because there is no more "paint" property in returned by map.getLayer(layerId) method.

See examples

0.42.2 - paint property does not exist
https://jsfiddle.net/rendrom/L577ptf6/

0.42.0 - paint property exist
https://jsfiddle.net/rendrom/6tz6c6xq/

**Comment by mourner** [comment]
`paint` and `layout` properties were never documented. Instead you should use `map.getPaintProperty(layerId, propName)` (see [docs](https://www.mapbox.com/mapbox-gl-js/api#map#getpaintproperty)).

**Comment by rendrom** [comment]
Thanks for the answer. In my case, it is required to work with the paint object. Now I have to get it out of style
