### ISSUE TITLE
Adding multiple source GEOJSON to one Layer ID

### ISSUE THREAD

**Issue by aabhishekbindal** [mapbox/mapbox-gl-js#5747]
I have multiple data source files (GeoJSONs). I want to load all the GeoJSON files to a particular LayerID created in the mapbox studio. If i try adding multiple GeoJSON files using a loop, then it overrides the existing files and load the styling for the last GeoJSON file. Is there a way to load all the geoJSON files in a folder and apply consistent styling for them?

**Comment by mourner** [comment]
You can simply merge the files into one GeoJSON. E.g. using https://github.com/mapbox/geojson-merge

**Comment by aabhishekbindal** [comment]
Vladimir,

Thanks for your reply. But We want to keep an attribute(ID) against each
GeoJSON file, for the correspondance with the data in the database.

So is there any way I can load multiple GeoJSONs for a single layer?

Regards,
Abhishek
