### ISSUE TITLE
Add ability to fix map corner position during map.resize()

### ISSUE THREAD

**Issue by rychoo2** [mapbox/mapbox-gl-js#5748]
Hello, 
When map.resize() is called the map is fit the new size of container. 
However it's also causing the map to "move". See below codepen to resize map on toggle sidebar:
https://codepen.io/anon/pen/JOZMYM

It would be great if you could specify which corner of the map should keep position after resize() to avoid map "moving" effect. It would look like map is extending to fit the new space without moving.

Thanks

**Comment by jfirebaugh** [comment]
Duplicate of #4269.
