### ISSUE TITLE
Explicit 3d elevation support for features (as opposed to 2.5d extrusions)?

### ISSUE THREAD

**Issue by shongololo** [mapbox/mapbox-gl-js#5749]
Is there any possibility to support a 3d coordinate system (z or height coordinate) in Mapbox GL JS?

In other words, honouring 'z' coordinates in 3d space when viewing a pitched Mapbox GL JS map as opposed to simply extruding a 2d polygon in 2.5d using a height property?

Use cases:
- Situations where some features, e.g. buildings on hills, are higher than other features (as defined by 3 coordinate systems as opposed to a base-height property)
- Situations such as where you need to show a bridge crossing-over a road at a lower elevation
- Being able to show individual building floor levels inside a building shell

At the end of the day, this is really an issue of whether Mapbox GL JS could support a 3rd coordinate (x and y and z) instead of only 2 coordinates (x and y) in 3d space?

Geospatial tools such as PostGIS already support height coordinates and it would be nice to extend this functionality to Mapbox GL JS.

**Comment by andrewharvey** [comment]
For terrain meshes see #1489.

For setting an altitude on the circle, symbol, line layer types (fill is supported though fill-extrusion type) see #3993, but I suspect it will initially be one altitude per feature as I don't think the vector tiles spec supports a z value per coordinate of a linestring (https://github.com/mapbox/vector-tile-spec/issues/76).
