### ISSUE TITLE
performance regression between v0.32 and v0.42

### ISSUE THREAD

**Issue by mprove** [mapbox/mapbox-gl-js#5752]
On migrating my webapp from mapbox gl version 0.32 to 0.42 I recognized a significant performance drop. The update/frame rate is even worse than before just for panning the map around. On iOS it is below acceptance. Apart from replacing the mapbox engine there is no other modification in my JS code. Any thoughts?

Here is a video to demonstrate the difference: https://vimeo.com/244512199

**mapbox-gl-js version**: 0.32.1 vs. 0.42.2

### Steps to Trigger Behavior

 1. Open Chronoscope with v0.32.1: https://mprove.de/chronoscope/map.html?q=53.51850,9.67088&z=11.53&y=1937&o=0
 2. Open Chronoscope with v0.42.2:  https://mprove.de/chronoscope/map42.html?q=53.51850,9.67088&z=11.53&y=1937&o=0
 3. Move the maps around and compare the update performance

### Expected Behavior
faster or at least same update performance / frame rate for newer mapbox gl version

### Actual Behavior
the update performance is slower for 0.42.2 compared to 0.32.1 before

**Comment by mourner** [comment]
@mprove does a barebones Mapbox GL JS map (e.g. from the first example but fullscreen) perform as bad? If it does, can you try different versions between 0.32 and 0.42 and see which version regresses the performance the most for you?

**Comment by andest01** [comment]
This problem is also present on Windows 10 Pro, Version 1703 viewed in Chrome Version 62.0.3202.94.

Mapbox GL JS 0.32.1 FPS: 50-60 FPS
Mapbox GL JS 0.42 FPS: 10-15 FPS.

**Comment by mprove** [comment]
Thanks for picking this up. I will perform more tests by
a) disabling my custom features one by one (basically it is just one huge map image on top and a marker. ) and then
b) testing against different versions.
wrt/me: stay tuned

**Comment by jfirebaugh** [comment]
Bisects to 2d359e97d58c85bf87326c50b381d501f3ab29d0.

**Comment by mprove** [comment]
Here is my application w/ 0.43.0
https://mprove.de/chronoscope/map43.html?q=53.51850,9.67088&z=11.53&y=1937&o=0

It is much better than w/ 0.42.2! It feels good using the mouse and it is usable again on iPad.
However, in terms of keyboard scrolling framerate, v0.43.0 is not as fast as v0.32.1. I'll open a new issue: #5996
