### ISSUE TITLE
How to disable features added in the mapbox studio

### ISSUE THREAD

**Issue by aabhishekbindal** [mapbox/mapbox-gl-js#5753]
Hi Team,

I have added a GeoJSON files which uses Mapbox studio as a reference inorder to build an map application.

I have added data source files in the Mapbox studio for styling purpose. But I don't want to use these data source in our actual map. Is there a way I can disable these data sources data (see the attached screenshot) to be added in the actual map.
![image](https://user-images.githubusercontent.com/5121761/33260356-95149bd2-d385-11e7-9f1f-02b11e027122.png)

I have custom data sources which I will be pulling in on runtime.

Thanks.

**Comment by andrewharvey** [comment]
You can ask "how do I" questions like this at https://stackoverflow.com/questions/tagged/mapbox-gl-js

What I normally do is make the layer invisible in Mapbox Studio, then client side in GL JS swap the source over to your client side source and make the layer visible.
