### ISSUE TITLE
mouseenter event not firing correctly on circle

### ISSUE THREAD

**Issue by VictorChen** [mapbox/mapbox-gl-js#5756]
When you enter the circle from the **LEFT** side (works fine on other sides, just not the left), the `mouseenter` event doesn't get fired until you reach closer to the center.

Reproducer:
https://jsfiddle.net/0mknjj30/6/

<img width="581" alt="screen shot 2017-11-27 at 1 16 02 pm" src="https://user-images.githubusercontent.com/1408813/33282003-3814554a-d375-11e7-8c4e-8eb693edd2ca.png">

I'd expect it to trigger **AS SOON** as my cursor touches the left edge of the circle

**Comment by peterqliu** [comment]
thanks for the issue @VictorChen 

[Looks like the left edge of the circle spills into a different tile](https://jsfiddle.net/0mknjj30/8/) that doesn't contain the point geometry for the circle, despite the circle being rendered in it:

![screen shot 2017-11-27 at 11 30 09 am](https://user-images.githubusercontent.com/4551508/33285213-7f166b2c-d366-11e7-8ebf-e2d67e206ca2.png)

**Comment by peterqliu** [comment]
^ @VictorChen to clarify, that is the expected behavior, just an undesirable one. The `mouseenter` event acts on the location of the underlying data, rather than the rendered pixels.

**Comment by VictorChen** [comment]
thanks @peterqliu, although that feels like a weird expected behavior (the fact that the `mouseenter` event gets triggered sometimes on the edge and sometimes not).

**Comment by andrewharvey** [comment]
I thought increasing [the buffer](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-geojson-buffer) might help, ensuring that the feature is also present in the tile on the left but testing this with buffer: 512 made no difference.

**Comment by ajfickas** [comment]
I've run into this issue trying to implement hover states for features in a symbol layer. `queryRenderedFeatures` fails to return a given feature when hovering portions of the feature's icon and label that cross into another tile.

Here's repro: https://jsfiddle.net/ajfickas/gpv122z4/

Is the plan to address this as part of https://github.com/mapbox/mapbox-gl-js/issues/6022?
