### ISSUE TITLE
Feature request: make fill-extrusion vertical gradient configurable

### ISSUE THREAD

**Issue by nmccrea-db** [mapbox/mapbox-gl-js#5768]
Hey folks. Thanks for making such an amazing platform.

I'm using **mapbox-gl-js 0.42.2**. I am representing a stack of blocks on a map using fill extrusions. The problem I'm having is that the lowest blocks are shaded slightly darker than the blocks above them. Here is an example:

<img width="1041" alt="funky shading 01" src="https://user-images.githubusercontent.com/32711966/33390183-2b65ff8a-d503-11e7-86f6-d2573ef64c1b.png">

In this example, all four blocks that are pointed out are given the same paint color (in this case, `white`). But the lowest two are rendered slightly darker than the higher two. Above the first two levels, there are no other inconsistencies.

It appears to have something to do with the elevation of the blocks. For example, if I make the bottom-most block thicker, and thus raise the elevation of the second block, then the inconsistency only affects the first block:

<img width="1045" alt="funky shading 02" src="https://user-images.githubusercontent.com/32711966/33390305-7e9caa6e-d503-11e7-9d94-6636e59c30d5.png">

The problem exists regardless of what color paint is being used:

<img width="493" alt="screen shot 2017-11-29 at 1 04 02 pm" src="https://user-images.githubusercontent.com/32711966/33391069-e5e2848a-d505-11e7-8348-49bed0e7ad3e.png">

And regardless of opacity:

<img width="524" alt="screen shot 2017-11-29 at 1 03 40 pm" src="https://user-images.githubusercontent.com/32711966/33391084-f3e951b2-d505-11e7-8810-0748399cbdd1.png">

<img width="489" alt="screen shot 2017-11-29 at 1 03 27 pm" src="https://user-images.githubusercontent.com/32711966/33391095-f964b758-d505-11e7-8d4d-24f330b6b52e.png">

This is in a geoJSON layer. The geoJSON is produced like this:

```javascript
      {
        'type': 'FeatureCollection',
        'features': geometries.map( geometry => ({
          'type': 'Feature',
          'properties': {
            'height':       geometry.height + geometry.baseElevation,
            'base_height':  geometry.baseElevation + VISUAL_SPACE_BETWEEN_BLOCKS,
            'color':        colorForType(geometry.type)
          },
          'geometry': {
            'type': 'Polygon',
            'coordinates': [
              geometry.polygon.concat([geometry.polygon[0]]),
            ],
          },
        }))
      }
```

And the paint is defined as follows:

```javascript
{
  'fill-extrusion-color': {
    'type':     'identity',
    'property': 'color',
  },
  'fill-extrusion-height': {
    'type':     'identity',
    'property': 'height',
  },
  'fill-extrusion-base': {
    'type':     'identity',
    'property': 'base_height',
  },
  'fill-extrusion-opacity': 0.9,
};
```

For my application, the coloring of the blocks is an important visual indicator, so any insight into how I might be able to make the coloring stay consistent would be greatly appreciated.

Thanks in advance.

**Comment by stevage** [comment]
Have you tried playing with the lighting settings to see if that, um, sheds any light? Does it happen the same when you're only rendering that bottom layer? (Ie, is it affected by the presence of higher levels?)

**Comment by lbud** [comment]
Currently this is expected behavior; the fill-extrusion shader adds a slight vertical gradient to provide some visual contrast between features (it was originally written primarily with a 3D building use case in mind). I'm going to reframe this ticket as a feature request: I'd be open to adding a paint property to make this configurable.

**Comment by nmccrea-db** [comment]
Thanks very much @lbud. Yes, this would be a useful feature for our case.

**Comment by jesus-deepblocks** [comment]
Hi @lbud, I'm following up on this issue. Has this feature been implemented? If not, there is any chance we could have some sort of idea on its ETA and also can you point me in the direction of a workaround in the meantime? 

Thanks.

**Comment by spimou** [comment]
@nmccrea-db I am trying to achieve the same result on the map like yours, extruding multiple polygons on the same position, one on top of the other. But I cannot get mapbox to do it. Can you please take a look [here](https://github.com/mapbox/mapbox-gl-js/issues/12321) ? Thanks
