### ISSUE TITLE
Layer "type" property is incorrectly documented as "optional"

### ISSUE THREAD

**Issue by lucaswoj** [mapbox/mapbox-gl-js#5772]
[From StackOverflow:](https://stackoverflow.com/questions/47397217/why-is-type-or-ref-required-for-layer-in-mapbox-gl-js/47399228?noredirect=1#comment81769907_47399228)

 > [mapbox-gl-js throws an error if a layer does not have a type. However, type is optional in the spec, and ref is not mentioned in the spec (was apparently taken out at some point). Can somebody clarify this? Should type be required then for the layer in the spec? Or something else?](https://stackoverflow.com/questions/47397217/why-is-type-or-ref-required-for-layer-in-mapbox-gl-js/47399228?noredirect=1#comment81769907_47399228)

As reported, the layer `type` property is documented as "optional."

<img width="702" alt="screen shot 2017-11-29 at 1 47 07 pm" src="https://user-images.githubusercontent.com/281306/33400711-d24f09f6-d50b-11e7-805c-cb8a3ab7c334.png">

(Naively changing the style reference causes a few failing unit tests.)

**Comment by jfirebaugh** [comment]
It should be marked as required in the docs, but treated as optional if `ref` is present, for backwards compatibility.
