### ISSUE TITLE
Make "Missing Mapbox GL JS CSS" a console warning

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5786]
Putting "Missing Mapbox GL JS CSS" in the DOM has confused at least one user (#5785) and causes other issues (https://github.com/mapbox/mapbox-gl-js/issues/5359#issuecomment-342325200).

Instead, it should be a console warning that's logged when a map is created and there's no CSS rule targeting `.mapboxgl-map` present. This can be checked using [CSSOM APIs](https://developer.mozilla.org/en-US/docs/Web/API/CSS_Object_Model).

**Comment by rtwalz** [comment]
For now the workaround I'm using is adding `display: none` to the class `mapboxgl-missing-css`

**Comment by stevage** [comment]
Just encountered another confused user. (He told me that "the CSS isn't loading", on the strength of that DOM element.) Another possible solution would be deleting the DOM element once the CSS has indeed loaded.

**Comment by jczaplew** [comment]
FWIW, the CSSOM APIs only function as expected with cross-loaded CSS resources when the attribute `crossorigin="anonymous"` is added to the `<link>`. 

If you load the CSS as most people do, with `<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.45.0/mapbox-gl.css' rel='stylesheet' />`, the rules of the stylesheet are not available via `document.styleSheets`. I'm uncertain as to whether this is a chromium bug or feature, but you could hack around this by making an additional request for all stylesheets that do not contain a `rules` or `cssRules` attribute, but that seems like a heavy-handed solution for a fairly small problem.
 
In the absence of a better solution, simply checking the computed style of `.mapboxgl-map` might suffice. Something like 

````javascript
let mapboxglMap = document.querySelector('.mapboxgl-map')
if (!mapboxglMap || window.getComputedStyle(mapboxglMap).overflow != 'hidden') {
    // CSS error
}
````

The nasty bit is that it depends on a hardcoded CSS value that could change in the future. Thoughts as to whether this might be an appropriate method of checking if the CSS has loaded?
