### ISSUE TITLE
map.setPaintProperty() fill-color not redrawing after modifying stops

### ISSUE THREAD

**Issue by justinhurlburt** [mapbox/mapbox-gl-js#5802]
**mapbox-gl-js version**:
0.42.1 & 0.42.2

### Steps to Trigger Behavior

 1. Create a layer with paint property 'fill-color' and give it a range of stops
 2. Modify the stops color and call `map.setPaintProperty()` with the new stops
 3. Observe 1 of 2 outcomes: Either the layer redraws only once and not again, or the layer does not redraw at all.

### Expected Behavior
When modifying stops and calling `map.setPaintProperty()` the layer should redraw with the correct stops colors

### Actual Behavior
When modifying stops and calling `map.setPaintProperty()` the layer redraws only once or not at all

Fiddles:
0.42.0 - WORKS
https://jsfiddle.net/bmdqb0nv 

0.42.1 - BROKEN
https://jsfiddle.net/9qj1szd6

0.42.2 - BROKEN
https://jsfiddle.net/a7qo64s2

### Workaround
call `map.setPaintProperty(<layer name>, 'fill-color');` before using the new stops.

**Comment by mollymerp** [comment]
thanks for the thorough report @justinhurlburt. this bisects to 7e87d7c

**Comment by mollymerp** [comment]
this line https://github.com/mapbox/mapbox-gl-js/commit/7e87d7c05c541f98e06df2bc08b96e931ace9549#diff-0fcf9ef37a1614185cad0dcbd5ec5529L775 is always returning true in the current code, so `_updateLayer` is never called. it seems the style is already updated before `layer.setPaintProperty` is called 💭  
cc @jfirebaugh

**Comment by jfirebaugh** [comment]
As a workaround, avoid updating `fillColor.stops` in place -- generate a fresh array for each `setPaintProperty` call.
