### ISSUE TITLE
how do you get the current centre point of a mapbox object?

### ISSUE THREAD

**Issue by lopugit** [mapbox/mapbox-gl-js#5810]
**mapbox-gl-js version**: 3.1.1

### Steps to Trigger Behavior

 1. make map
 2. wait for load
 3. console.log(map) on every move event

### Expected Behavior
some property with the current centre point as a latlng kind of data type
### Actual Behavior
no property to give the current location

Hello :)

I'm trying to make a select location thing, and what I'm doing is triggering an event on a button click, which has access to the loaded map object, and which then adds a marker at the current centre location.

But there's no way to get the current centre location of the mapbox object.

Could you please direct me on how to do this? :O

I've tried

```javascript
```

**Comment by jaapster** [comment]
Is `Map.getCenter` what you're looking for?

[https://www.mapbox.com/mapbox-gl-js/api/#map#getcenter](https://www.mapbox.com/mapbox-gl-js/api/#map#getcenter)

**Comment by lopugit** [comment]
@jaapster 

come on man you look for like an hour..... sorry about that <3
