### ISSUE TITLE
line-opacity not working on headless chrome

### ISSUE THREAD

**Issue by satorbs** [mapbox/mapbox-gl-js#5816]
Hello :)

I use mapbox-gl-js with headless chrome control by remote-interface running on docker. 
Now headless chrome needs to disable gpu so i include libosmesa in this environment.
Then the "line-opacity" property of added line source is not working but another object drawn with alpha value individually seems to be work well.
Could you think of anything?

Thanks.

**mapbox-gl-js version**: 0.42.2
**another environment information**: 
  * doker: 17.09.0-ce-mac35
  * google chrome: 62.0.3202.94-1
  * libosmesa: 17.0.1-6.20170307

### Steps to Trigger Behavior

 1. launch chrome with headless mode and control by [remote interface](https://github.com/cyrus-and/chrome-remote-interface)
 2. draw map and line and capture screenshot by debugging protocol on chrome
 3. it is shown below

### Expected Behavior
line opacity worked properly like "on display" below
### Actual Behavior
it is filled with white color and edge is jagged

* on display
![capture_1](https://user-images.githubusercontent.com/26701368/33652716-c2a8506e-daad-11e7-82d6-233ff78e2800.png)

* opacty: 0.1
![capture_2](https://user-images.githubusercontent.com/26701368/33652724-c90ae76e-daad-11e7-9a71-d4623c9bbe6e.png)

* opacity: 0.7
![capture_3](https://user-images.githubusercontent.com/26701368/33652851-3d38fba8-daae-11e7-9e0a-797a5007a58d.png)
![capture_4](https://user-images.githubusercontent.com/26701368/33653660-1448f8f8-dab1-11e7-85fc-03603fe37a8f.png)

**Comment by jfirebaugh** [comment]
Hi @satorbs -- I don't think this is an environment that we're going to be able to officially support right now. If support is important for you, you're welcome and encouraged to dig in further, but we'll need to keep our testing resources focused on "headed" browsers.
