### ISSUE TITLE
map.on("mousemove", "state-fills", function(e) {}) fires features?

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#5817]
I saw in example 
```
 map.on("mousemove", "state-fills", function(e) {
        map.setFilter("state-fills-hover", ["==", "name", e.features[0].properties.name]);
    });
```
https://www.mapbox.com/mapbox-gl-js/example/hover-styles/
that there is a map.on method which takes three arguments. Where is this documented? 
I doesn't fount it on
https://www.mapbox.com/mapbox-gl-js/api/#evented#on

it look like i could give one - maybe more? - layers on which this event will call and where i get also a feature set. 

I have some questions:
- Is this a regular function?
- Will this also works for other events, exspecially for data loading event?
For me it would be nice to get a feature list of a loading vector tile. 
- Is this faster than call the queryRenderedFeatures?

**Comment by jfirebaugh** [comment]
It's documented [here](https://www.mapbox.com/mapbox-gl-js/api/#map#on) (second variant).
