### ISSUE TITLE
New events related functionalities

### ISSUE THREAD

**Issue by rulyotano** [mapbox/mapbox-gl-js#5818]
## Motivation

Improve the events system for attending more complex and natural scenarios. For instance, you have a layer of polygons with a click event handler, and want to add a measure distance control (same as in the samples), every time you click on a polygon for measuring the distance, besides the new measure point, also the click is handled by the polygon and the popup is showed.
Another case of use is that when you click in a marker, you would need all near features or markers, but marker doesn't have event handling.

### Suggestions

1. Make an event system based on layers or priority, and not in add-to-queue order. Even a good idea could be to have a parameter in subscription that would be if it can listen from bottom-up or up-bottom.

2. Make markers evented objects. In this way you could have all mouse arguments in the event (you doesn't have it in dom events)

3. Implement stopPropagation or similar.

**Comment by jfirebaugh** [comment]
Thanks for the suggestions @rulyotano. We're thinking about these issues generally in #6022. Let's centralize discussion there.
