### ISSUE TITLE
Fully automate serialization/deserialization of web worker messages

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#5823]
Following up on https://github.com/mapbox/mapbox-gl-js/pull/5702, we should fully automate serialization and deserialization, encapsulating the process within `Actor#send()`.  

The most invasive aspect of this will likely be refactoring style layers such that the `setLayers` message can use the generic serialization mechanism.

**Comment by jfirebaugh** [comment]
The `setLayers` serialization returns a plain object that's compatible with auto-serialization, so it seems like we could do this without converting that (there would just be a bit of extra overhead). I [tried it out](https://github.com/mapbox/mapbox-gl-js/compare/auto-serialize) and ran into a different problem: the auto-serializer is greedy about `Transferable`s, and transfers any `ArrayBuffer` or view it encounters. But `ImageManager` and `GlyphManager` want to retain their buffers, so they need to make a pre-copy, or we could add another option for `register` to control the behavior. I originally thought we'd go with the former, but the latter now seems more convenient.

**Comment by jfirebaugh** [comment]
On second thought, explicit cloning is better: sometimes we do want to transfer image data (when sending atlases back from worker to main thread), rather than copying it.
