### ISSUE TITLE
Revise documentation of the `bearing` map option to avoid implying that it represents "rotating" the map

### ISSUE THREAD

**Issue by bartvde** [mapbox/mapbox-gl-js#5828]
So I have a style spec doc with the following:

```
"center": [-93, 45], 
"zoom": 3, 
"bearing":15,
```

This results in:

![selection_433](https://user-images.githubusercontent.com/319678/33769015-bd87eb9a-dc28-11e7-8712-94e7fb0e958d.png)

However the style spec has this definition:

Default bearing, in degrees clockwise from true north. The style bearing will be used only if the map has not been positioned by other means (e.g. map options or user interaction).

So I would expect it to be other way round (rotated clockwise 15 degrees).

Either the style spec needs to get updated, or the implementation needs to be changed. Can anybody provide some guidance on this? TIA.

**Comment by anandthakker** [comment]
Hi @bartvde -- "bearing" doesn't mean "the amount the map is rotated".  Rather, it refers to the compass direction that is "up" on the map.  So, for instance, a bearing of 90° means that _east_ is up.

**Comment by bartvde** [comment]
ah sorry about that @anandthakker, I was a bit confused given that the definition in mapbox gl js differs from that in the style spec

The initial bearing (rotation) of the map, measured in degrees counter-clockwise from north. If bearing is not specified in the constructor options, Mapbox GL JS will look for it in the map's style object. If it is not specified in the style, either, it will default to0 .
--

**Comment by anandthakker** [comment]
Ah, I see what you mean: the "(rotation)" may be misleading.  I'll reopen this issue to track clarifying the GL JS docs.  Thanks!

**Comment by bartvde** [comment]
yes the rotation part is a bit misleading, but also the direction is written up differently (counter-clockwise  versus clockwise).

**Comment by jfirebaugh** [comment]
Previously: #4179, c32d6157f6057d77a27a53dd79ee73c93163bff8. The clockwise/counter-clockwise discrepancy was mentioned there but somehow I neglected to correct it! In any case, it seems that clockwise/counter-clockwise is itself ambiguous. I'll try a different definition.

**Comment by jfirebaugh** [comment]
ed51dd4081d6aebf9bcffb82409de0da20d6f530
