### ISSUE TITLE
Pinch zoom not working with Windows Mobile 10

### ISSUE THREAD

**Issue by ttsirkia** [mapbox/mapbox-gl-js#5830]
**mapbox-gl-js version**: 0.42

### Steps to Trigger Behavior

 1. Open https://www.mapbox.com/mapbox-gl-js/example/simple-map/ in Windows Phone (in my case Lumia 950)
 2. Try to pinch zoom the map

### Expected Behavior

The map will be zoomed, the web page remains the same.

### Actual Behavior

Often the page will be zoomed as well and the position of the map will jump to a random position near the original location.

Are there some quirks that could disable zooming the underlaying web page? It seems that `touch-actions` does not work.

**Comment by ttsirkia** [comment]
This is probably not a bug in the library. Can be fixed by CSS:

```css
html {
  -ms-touch-action: none;
  touch-action: none;
}
```

**Comment by phanisnvs** [comment]
Hi,

In our application, we use mapbox gl/api for viewing contact pins in map. In Android and IOS devices, we can able to pinch (touch) to Zoom in and out pins in the map.But in Surface pro3 pinch in and out function is not working instead it is panning the map.

Any leads on how to check for the issue / provide guidance to get solution
