### ISSUE TITLE
Mapbox Studio styles don't produce consistent colors in generated PNG tiles

### ISSUE THREAD

**Issue by portsmouth** [mapbox/mapbox-gl-js#5833]
This is an issue with the Mapbox Studio web app, but I'm not sure where to log it, and it may be due to how the tiles are rendered via Mapbox GL.

I am trying to use Mapbox Studio to generate a style containing an integer ID per country (in range 0-255), encoded in the color channels of the image. The attached style [country_index_style.json.zip](https://github.com/mapbox/mapbox-studio-classic/files/1545025/country_index_style.json.zip) achieves this by generating a layer per country (defined by a geojson file containing country boundaries),  with fill-color #xy0000 where xy is the hex code for the country. (Note I also specified "fill-antialias: false" to prevent anti-aliasation from corrupting the IDs near country boundaries).  For example, I assign Romania the fill color #b80000 (equivalent to rgba(184,0,0,1)).

This all looks good in Mapbox studio, as here: https://www.mapbox.com/studio/styles/jamports/cjazkexj8bn9e2smqtp4x2lxf/

I then need to download tiles from this style, via URLs like:
https://api.mapbox.com/styles/v1/jamports/cjazkexj8bn9e2smqtp4x2lxf/tiles/512/4/9/5?access_token=<my-token>

However the (PNG) tiles which are downloaded via the request above are *not* exactly consistent with the style, for example the tile linked to above shows a portion of Romania but the color of the pixels is actually #b90000 (which should correspond to Russia in the style).  

The color in the tiles is not even consistently wrong, e.g. the tile adjacent to the one above has the *correct* color for Romania according to the style, i.e. #b80000, as here:

https://api.mapbox.com/styles/v1/jamports/cjazkexj8bn9e2smqtp4x2lxf/tiles/512/4/8/5?access_token=<my-token>

Is this an issue with the tile rendering from Mapbox Studio, or is there something I'm missing in either my style, or in how I should interpret the color of the downloaded tiles?  (e.g. perhaps the color in the tiles should not be expected to match the fill color in the style itself, for some reason).

[country_index_style.json.zip](https://github.com/mapbox/mapbox-gl-js/files/1545037/country_index_style.json.zip)

**Comment by jfirebaugh** [comment]
Yes, tiles served from the static tile API are size-optimized, and generated using [indexed color](https://en.wikipedia.org/wiki/Indexed_color) -- this can result in colors that are not precisely equivalent to what you get from client-side vector tile rendering.

**Comment by portsmouth** [comment]
Ah OK, thanks for the explanation.  So I take it there is no way to control how Mapbox optimizes the tiles, e.g. the indexing scheme? In my case I only need 256 distinct colors in one channel.  Do you see any way for me then to reconstruct the actual original specified fill color of the layer via the static API?    Even if there was some way for me to encode in the three 8-bit colors channels enough  information to be able to reconstruct the intended 0-255 value, that would work.   

There must be others trying to use Mapbox static API to serve tiles which contain region indices encoded as colors.

**Comment by jfirebaugh** [comment]
I don't know of a way to do that, sorry. It's not really an intended use of the static tile API -- the API is more for serving tiles as a fallback alternative for browsers that lack WebGL support.

**Comment by portsmouth** [comment]
OK sure,  so I suppose the "official" way to do what I want would be to grab the *vector* tiles of the style (containing various polygon boundaries etc.), and then render those myself in webGL.

**Comment by jfirebaugh** [comment]
Yes -- if you use Mapbox GL JS, then you can use [`queryRenderedFeatures`](https://www.mapbox.com/mapbox-gl-js/api#map#queryrenderedfeatures) to perform the query.

**Comment by portsmouth** [comment]
Thanks for the help, appreciate it!
