### ISSUE TITLE
fitBounds not exact?

### ISSUE THREAD

**Issue by jordandalley** [mapbox/mapbox-gl-js#5834]
Forgive my noobiness if I've missed something, but when using fitBounds on a canvas of 960x720, the map camera overlaps the bounds specified in the coordinates on the left and right (960px).

I'm assuming that's because of aspect ratio, and that mapbox-gl does not stretch the tiles. Is the any way to force a bounding box to exact coordinates? I have radar imagery i'd like to overlay that it has to adhere to.

Thanks,
Jordan.

**Comment by mourner** [comment]
Indeed, we can't stretch the map to accommodate exact bounds. You should work around that with application logic (e.g. setting up the map container size to match the needed aspect ratio or leaving the sides empty when overlaying the radar imagery).

**Comment by jordandalley** [comment]
Thanks. I'll give it a shot :)
