### ISSUE TITLE
0.42.1 introduces visual glitches+unwanted polygons on GeoJSON sources with $type filters

### ISSUE THREAD

**Issue by snkashis** [mapbox/mapbox-gl-js#5838]
Ever since upgrading our platform to 0.42.1(and then later on 0.42.2), we have experienced some dramatic visual glitches on our only page which utilizes a GeoJSON source that contains both Point and Polygon features through 2 different layers(filtered by $type).
Roads on the basemap seems to have a irregular dashed pattern that is not normal for our style, and large and small polygons which are not desired seem to fill large parts of the whole map randomly.
This issue occurs in all current versions of Chrome, Safari and Firefox on MacOS Sierra.
We have since reverted to **0.42.0** and the problem has gone away completely.

**mapbox-gl-js version**: 0.42.1 - 0.42.2

### Steps to Trigger Behavior

1.  Build a mapbox map with 0.42.1 or 0.42.2
2. Make a GeoJSON Source
3. Add layers which connect to that source, one for Points and one for Polygons, with respective filters "["==", "$type", $ENTITY_TYPE]"
4. Add a FeatureCollection containing both Point and Polygon Features to that source.

### Expected Behavior
Map appears normally, river on right does not appear filled in.Expected features(2 rectangles + one point exist)
![42 0](https://user-images.githubusercontent.com/361323/33809033-deef1068-ddb5-11e7-88dc-5dbec54115df.png)

### Actual Behavior
Map has odd road styling and unwanted polygons in addition to the expected features.Same zoom level between screenshots.
![42 2](https://user-images.githubusercontent.com/361323/33809035-e3cca686-ddb5-11e7-9d84-7fca1c37ea5a.png)

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained JSFiddle that demonstrates the issue?

**Comment by snkashis** [comment]
Hey @jfirebaugh - sorry for the delay here - spent a chunk of time yesterday trying to build a decent example to show this in action, but it's not operating as expected(as in the isolated example works fine...). I have figured out though the visual corruption only happens after the first move(either programmatic or user driven) though.

**Comment by jfirebaugh** [comment]
Ok, please let us know if you're able to set up an example.
