### ISSUE TITLE
layer.paint problem for symbol (0.42.2)

### ISSUE THREAD

**Issue by neore** [mapbox/mapbox-gl-js#5839]
**mapbox-gl-js version**: 0.42.2

Hi everybobdy and congratulations for this amazing platform.
A strange issue appear in 0.42.2 and doesn't in 0.42.0

### Steps to Trigger Behavior
![capture d ecran 2017-12-11 a 09 04 00](https://user-images.githubusercontent.com/15775949/33820970-4af4bad2-de52-11e7-9723-77634db0648a.png)

### Expected Behavior
Normal behavior.

### Actual Behavior
There point are coming from a simple GEOJSON point file with a 'name' property.

PROBLEM : 
Text is not displayed at every zoom levels, he's here (hover confirm this) but fully transparent.
The problem is coming from paint property : If I comment text-color, text is coming back...
All paint properties are ignored. (text-halo-blur, text-halo-color,text-halo-width)
Issue comes with 0.42.2, not present in 0.42.0

Thanks a lot.

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained JSFiddle that demonstrates the issue?

**Comment by neore** [comment]
Hi, I've passed 4 hours to try to reproduce the issue on JSFiddle without success... I'll continue to investigate to understand. But issue is not coming up... Grrr....
Please, push this issue in end of stack ;-)

**Comment by jfirebaugh** [comment]
Ok, please let us know if you're able to set up an example.
