### ISSUE TITLE
Rotation never ends on Angular

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#5841]
It is strange, i've two Angular Projects where i use MapboxGL 0.42.2. 
At one of it the rotation never ends. 

I see that  at onUp the removeEventListener will be called and this._onMove is set. But the onMove will be called anyway. Does someone understand why? Maybe because of capture = true?
```
DragRotateHandler.prototype._onUp = function _onUp (e                     ) {
        var this$1 = this;
    window.document.removeEventListener('mousemove', this._onMove, {capture: true});
```

**Comment by mollymerp** [comment]
Hi @strech345, thanks for using Mapbox. In order for us to diagnose your issue, we need to be able to reproduce it. Please use the provided issue template for your bug report and include a minimal jsfiddle or jsbin (preferably without Angular or any third party libraries) that reproduces the issue you're seeing.

**Comment by strech345** [comment]
Hallo @mollymerp 
sorry, i found the bug at the zone.js version
https://github.com/angular/zone.js/issues/737. So no problem of mapbox.

**Comment by jfirebaugh** [comment]
Thanks for letting us know!
