### ISSUE TITLE
Layers with basic styling render beneath labels by default

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#5848]
**mapbox-gl-js version**:
0.42.2

### Steps to Trigger Behavior

 1. Create 2 style layers, one with data-driven fill color and one with basic fill color
 2. Call `map.setStyle` to set the style

https://jsbin.com/meridarebi/1/edit?js,output

### Expected Behavior

Both layers should appear above the labels.

### Actual Behavior

Data-driven layers appear correctly above the label, while the basic fill-color layer renders beneath the labels.

![image](https://user-images.githubusercontent.com/4524175/33903646-e07ac020-df2d-11e7-8c82-3de84eb0d922.png)

**Comment by jfirebaugh** [comment]
Thanks for the report, we're tracking this in #2074. As a workaround, you can set the opacity of the "Maine" layer to 0.99.
