### ISSUE TITLE
Data-driven style from multiple feature properties

### ISSUE THREAD

**Issue by gagecarto** [mapbox/mapbox-gl-js#5855]
Is it possible to use multiple properties from the same feature for styling?

For example, an ecological unit with properties for both mammal richness and fish richness. Ideally I could add or multiple them together right in the property function. E.G.

`{

    "circle-color": {
        "property": "mammalRichness"+"fishRichness",
        "stops": [
            [0, 'blue'],
            [100, 'red']
        ]
      }
    }
`

I understand I could easily do all this beforehand but this would help keep file sizes down.

**Comment by jfirebaugh** [comment]
Yes, please see https://www.mapbox.com/help/mapbox-gl-js-expressions/ and https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions.

**Comment by anandthakker** [comment]
@gagecarto this is possible using the (somewhat recent) [expressions](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions) system.  The example above using an expression would look like:
```js
{
  "circle-color": [
     "interpolate",
     ["linear"],
     [ "+", ["get", "mammalRichness"],  ["get", "fishRichness"]],
     0,
     "blue",
     100,
     "red"
  ]
}
```

**Comment by gagecarto** [comment]
@anandthakker - Just radical what you all are doing with Mapobx GL.. Thanks!
