### ISSUE TITLE
Map not working with IE11

### ISSUE THREAD

**Issue by ttsirkia** [mapbox/mapbox-gl-js#5857]
**mapbox-gl-js version**: 4658095 (0.42.2 is still working)

### Steps to Trigger Behavior

 1. Open a map with IE 11 and open console

### Expected Behavior

Map opens, no errors

### Actual Behavior

IE throws error "Object doesn't support `slice`". The minified location is mapbox-gl.js (546,1207). That is `util/image.js`

`return new AlphaImage({width: this.width, height: this.height}, this.data.slice());`

**Comment by tkohr** [comment]
It seems to me that the same error exists (again) when calling map.addImage(). 
Steps to reproduce: Open https://www.mapbox.com/mapbox-gl-js/example/add-image-generated/ in IE 11.

In my application I have the problem when using versions 0.45.0 and 0.44.2. When I downgrade to the version I used before (0.40.1) everything works fine however.

**Comment by ryanhamley** [comment]
Hey @tkohr this issue has been fixed in v0.46.0 which, barring any setbacks, should be released Wednesday.

**Comment by tkohr** [comment]
That's good news. Thanks!

**Comment by tkohr** [comment]
I confirm updating to v0.46.0 solved the problem for us.
