### ISSUE TITLE
Map is not using the fetched data to draw the layer

### ISSUE THREAD

**Issue by ttsirkia** [mapbox/mapbox-gl-js#5860]
**mapbox-gl-js version**: 0.40.0 and newer (0.39.1 works)

### Steps to Trigger Behavior

 1. Load a map
 2. Zoom in

### Expected Behavior

Map loads data with higher precision. Data becomes visible.

### Actual Behavior

Data is requested but not drawn. The layer is completely missing or using earlier loaded tile with lower zoom level. The layer mainly contains lines and some circles. OSM data is perfectly drawn, this data is generated by tippecanoe. If it is not drawn at all, the elements become visible when zooming out again.

This is a bit tricky to replicate because currently the only platform that I have found to be buggy is Android Chrome, version 62.0.3202.84.

One of the failing tiles is attached.

[4720.zip](https://github.com/mapbox/mapbox-gl-js/files/1557465/4720.zip)

**Comment by jfirebaugh** [comment]
Hi @ttsirkia, thanks for the report. We're going to need more information for this to be actionable. Are there debug messages in the developer console? Can you put together a minimal test case?

**Comment by ttsirkia** [comment]
Mobile debugging is a bit problematic but here are two links which show the problem.

Working (0.39.1): https://julia.dy.fi/map/view?mode=infra#15.37/60.4039/25.1063
Broken (latest): https://julia.dy.fi/map/view?test=1&mode=infra#15.37/60.4039/25.1063

At least with my Android phone, the railway is not visible in the upper part of the map. After zooming out, it becomes visible and when zooming back in, it becomes blurry because it is still using the tile for low zoom level.

**Comment by ttsirkia** [comment]
By using ADB to debug the Android phone, I was able to collect more information which is hopefully relevant.

![kuva](https://user-images.githubusercontent.com/2797729/34006564-7ea917d0-e107-11e7-8364-2e2defa8cf09.png)
 ```
Uncaught RangeError: out of range source coordinates for image copy
    at copyImage (mapbox-gl-dev2.js:546)
    at Function.RGBAImage.copy (mapbox-gl-dev2.js:546)
    at a (mapbox-gl-dev2.js:388)
    at mapbox-gl-dev2.js:388
    at Image.n.onload (mapbox-gl-dev2.js:522)
copyImage @ mapbox-gl-dev2.js:546
RGBAImage.copy @ mapbox-gl-dev2.js:546
a @ mapbox-gl-dev2.js:388
(anonymous) @ mapbox-gl-dev2.js:388
n.onload @ mapbox-gl-dev2.js:522
```

**Comment by ttsirkia** [comment]
Debug prints reveal that this constraint `srcPt.x > srcImg.width - size.width` fails. `50 > 49` in this case.

**Comment by jfirebaugh** [comment]
Thanks, that's very helpful! I can reproduce the issue locally by setting a custom `devicePixelRatio`.

**Comment by jfirebaugh** [comment]
The spritesheet https://julia.dy.fi/tiles/styles/julia/sprite@2x.{json,png} is invalid. The `crossing-g` image is purported to be a 49 pixel wide image at x coordinate 50, which would require a PNG at least 99 pixels wide, but the PNG is only 98 pixels wide.

**Comment by ttsirkia** [comment]
Interesting reason. Thanks @jfirebaugh for explaining the root cause!
