### ISSUE TITLE
Line width property based on zoom

### ISSUE THREAD

**Issue by rigoneri** [mapbox/mapbox-gl-js#5861]
Hey, I'm not sure if this is the right place to post questions like this, but after hours I couldn't find an answer, and this might help someone in the future.

To start, I have the width of a line (in meters) that I want to be able to be correctly adjusted based on zoom level. So I originally had something like this:

```
paint: {
    "line-width": lineWidth
}
```

But the line width we have is in meters not pixels and when I adjusted the zoom level it stayed fixed to that size. And after googling around couldn't find a easy solution and we came up with this:

```
paint: {
    "type": "exponential",
    "base": 2,
    "stops": [
        [0, lineWidth * Math.pow(2, (0 - 16))],
        [24, lineWidth * Math.pow(2, (24 - 16))]
    ]
}
```
That surprisingly works but seems to me that there's a easier way to achieve that. 

However now we've changed to have the line width as a property in the tiles, because the line width can be different based one certain lines and in different line "paths". So we came up with this:

```
paint: {
    "line-width": {
        "type": "exponential",
        "property": "line_width",
        "base": 2,
        "stops": [
            [{zoom: 10, value: 12}, 12 * Math.pow(2, (10 - 16))],
            [{zoom: 24, value: 12}, 12 * Math.pow(2, (24 - 16))],
        ]    
    }
}
```

However that only handles if the line width is 12 but the line width can vary between 0 to 50. Which lead me to creating a function that generates the stops to every single possible combination. Which seems way overkill, and I'm seeing some performance issues.

Is there a easier way to achieve this? Be able to draw a line from a property where the width is correctly represented in every zoom level in meters. (If I have to convert it into pixels instead of meters before generating the vector tiles I can do that, but will need some guidance)

Thanks in advance, 

Rigo

**Comment by jfirebaugh** [comment]
You can use [expressions](https://www.mapbox.com/help/mapbox-gl-js-expressions/) to do this. Something like:

```
["interpolate", ["exponential", 2], 
  0, ["*", ["get", "line_width"], ["^", 2, -16]], 
  24, ["*", ["get", "line_width"], ["^", 2, 8]]]
```

More documentation [here](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions).

**Comment by rigoneri** [comment]
Awesome! Thanks for the help!

For future reference I end up with this, had to add the 'zoom' as the input:

```
paint: {
    'line-width': [
        'interpolate', 
        ['exponential', 2], 
        ['zoom'],
        10, ["*", ["get", "line_width"], ["^", 2, -6]], 
        24, ["*", ["get", "linw_width"], ["^", 2, 8]]
    ],
}
```

**Comment by joedjc** [comment]
@jfirebaugh @rigoneri This is really useful...i'm also trying to use it to display a circle radius's and line widths in meters. I'm finding the accuracy is affected by the map projection. Would be interested to know if this could also be accounted for using expressions...perhaps if latitude were available as a property? (doesn't need to be perfect - I guess it would be impossible for very large shapes without distorting them?)

**Comment by johnnyzen** [comment]
> Awesome! Thanks for the help!
> 
> For future reference I end up with this, had to add the 'zoom' as the input:
> 
> ```
> paint: {
>     'line-width': [
>         'interpolate', 
>         ['exponential', 2], 
>         ['zoom'],
>         10, ["*", ["get", "line_width"], ["^", 2, -6]], 
>         24, ["*", ["get", "linw_width"], ["^", 2, 8]]
>     ],
> }
> ```

Can anyone help me to use this calculation in Android?

**Comment by johnnyzen** [comment]
I got as far as:

`
pipeLineLayer.lineWidth(interpolate {
                        exponential {
                            literal(2.0)
                        }
                        zoom()
                        stop {
                            literal(10.0)
                            stop {
                                get("line-width")
                                literal(23.0)
                            }
                        }
                        stop {
                            literal(24.0)
                            stop {
                                get("line-width")
                                literal(27.0)
                            }
                        }
                    })
`

**Comment by Lucho-git** [comment]
> Awesome! Thanks for the help!
> 
> For future reference I end up with this, had to add the 'zoom' as the input:
> 
> ```
> paint: {
>     'line-width': [
>         'interpolate', 
>         ['exponential', 2], 
>         ['zoom'],
>         10, ["*", ["get", "line_width"], ["^", 2, -6]], 
>         24, ["*", ["get", "linw_width"], ["^", 2, 8]]
>     ],
> }
> ```

Thanks for posting this, was really useful!

**Comment by wchargin** [comment]
> This is really useful...i'm also trying to use it to display a circle radius's and line widths in meters. I'm finding the accuracy is affected by the map projection. Would be interested to know if this could also be accounted for using expressions...perhaps if latitude were available as a property? (doesn't need to be perfect - I guess it would be impossible for very large shapes without distorting them?)

Here's a way to achieve this, using the fact that the number of feet per pixel [falls off as the cosine of the latitude][1]:

```typescript
// Expects data source to have two GeoJSON properties:
//    - latitude: representative latitude to use for distortion correction
//    - lineWidthFt: desired width of line, in real-world feet

const pxPerFootAtZoom = (atZoom) => {
  // At zoom level 16, one pixel at the equator corresponds to 3.92 feet:
  // https://docs.mapbox.com/help/glossary/zoom-level/
  const baseZoom = 16;
  const baseWidthAtEquator = 1 / 3.92; // px/foot
  // Each zoom level magnifies by a factor of two.
  const zoomScale = 2 ** (atZoom - baseZoom);
  const zoomedWidthAtEquator = baseWidthAtEquator * zoomScale;
  // And, away from the equator, there are more pixels per foot.
  const projectionScale = ["cos", ["*", Math.PI / 180, ["get", "latitude"]]];
  return ["/", zoomedWidthAtEquator, projectionScale];
};

const paintStyle = {
  "line-color": "black",
  "line-width": [
    "interpolate",
    ["exponential", 2],
    ["zoom"],
    ...[10, ["*", ["get", "lineWidthFt"], pxPerFootAtZoom(10)]],
    ...[24, ["*", ["get", "lineWidthFt"], pxPerFootAtZoom(24)]],
  ],
};
```

[1]: https://docs.mapbox.com/help/glossary/zoom-level/#zoom-levels-and-geographical-distance
