### ISSUE TITLE
Paint performance regressed from 0.42.2

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#5865]
We need to recover this before releasing 0.43:

![image](https://user-images.githubusercontent.com/98601/34012384-6a001d9a-e0c8-11e7-9a24-ac6853ffeeff.png)

https://bl.ocks.org/anonymous/raw/3e1f39faef3155a250cda03b52b43e9e/

**Comment by averas** [comment]
I am actually seeing a quite significant performance degradation already from 0.41.0 to 0.42.0 (and all releases after it).

In 0.41.0 zooming in and out over a quite dense vector tile layer is smooth:

![0.41.0](https://user-images.githubusercontent.com/1205805/34134772-1957cc7e-e45d-11e7-8294-cab27daedc78.gif)

Everything the same but switching to 0.42.0 (or 0.42.1 or 0.42.2):

![0.42.0](https://user-images.githubusercontent.com/1205805/34134793-39405a88-e45d-11e7-9982-9e70d3cd8f94.gif)

There is an especially evident judder when passing whole number zoom levels as can be seen in the gif above. I also get tons of these in the console:

<img width="483" src="https://user-images.githubusercontent.com/1205805/34134861-8c0be746-e45d-11e7-97ba-e06aac7a92f4.png">

Which I don't get with 0.41.0...

Macbook Pro Late 2013
MacOS Sierra 10.12.6
Chrome Version 59.0.3071.115 (Official Build) (64-bit)

**Comment by averas** [comment]
I created an example demonstrating the issue at https://codepen.io/anon/pen/YYwoKx
Change to 0.41.0 to see it work smoothly. I also realised that the difference between 0.41.0 and 0.42.x is not only the performance, but the visual rendering is quite different as well, both in the initial state and when zooming in/out.

**Comment by jfirebaugh** [comment]
Looks related to viewport collision detection. Since it isn't a regression from regressed from 0.42.2, could you please open a separate issue? Thanks!

**Comment by jfirebaugh** [comment]
Good here as of https://github.com/mapbox/mapbox-gl-js/pull/5896.

https://bl.ocks.org/anonymous/raw/a6c326488580a7d7c3b3227bfc588f4c/
