### ISSUE TITLE
queryRenderedFeatures not working for vector soruces

### ISSUE THREAD

**Issue by ttsirkia** [mapbox/mapbox-gl-js#5873]
**mapbox-gl-js version**: 0.43.0-beta

### Steps to Trigger Behavior

 1. Add a popup handler (mouseenter)
 2. Hover mouse over the marker

### Expected Behavior

Popup becomes visible

### Actual Behavior

Nothing happens

No errors in console. Static or dynamic data, no difference. `queryRenderedData` is also affected. It seems that this is somehow related to data which is stored in tiles.

**Comment by ttsirkia** [comment]
`queryRenderedFeatures` also broken in Chrome.

**Comment by jfirebaugh** [comment]
Thanks @ttsirkia, can you make a test case please? I'm not immediately seeing any issues in the examples that create `Popup`s (I assume that's what you mean by "tooltip"), so the details here are important.

**Comment by ttsirkia** [comment]
Yes, I meant popups. Even this simple code does not work with Chrome.

```javascript
    map.on('mouseenter', 'myData', function(e) {
      map.getCanvas().style.cursor = 'pointer';
    });
```

I try to downgrade the library and see which commit causes the problem.

**Comment by jfirebaugh** [comment]
http://jsbin.com/qudoyasiho/edit?html,output

This is working fine for me. Does it not work for you?

**Comment by ttsirkia** [comment]
That example works fine. I just figured out that commit e2bac0b8 is the first that does not work with my code in Chrome.

**Comment by ttsirkia** [comment]
You can try this:
https://julia.dy.fi/map/view?mode=diagram&test=1#17.49/61.309124/23.754908

It is running e2bac0b There should be a popup in the green and yellow circle, and they are visible in Firefox but not in Chrome.

**Comment by ttsirkia** [comment]
Actually, it doesn't work in Firefox either.

**Comment by jfirebaugh** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/98601/34061682-2b680044-e19e-11e7-9aac-7c90826bc7c2.png)

**Comment by ttsirkia** [comment]
Did you disable the cache in Chrome to be sure that it is using the version I just built? That is how it should work but I can't get the popup with that version.

**Comment by jfirebaugh** [comment]
Yeah, I think I must have had the page cached. With a forced refresh, I no longer see the tooltip.

Can you minimize a test case from this page?

**Comment by ttsirkia** [comment]
I'll try.

**Comment by ttsirkia** [comment]
I finally found one example that shows the problem: http://jsbin.com/wekikalepu/1/edit?html,output The mouse pointer does not change with the latest version as it doesn't recognize the grass area.

**Comment by ttsirkia** [comment]
I wasn't able to create any examples if the data was defined in the code. But by using data in tiles, this issue became visible. It also seems that for labels changing the mouse pointer still works but symbols and other areas are not recognized by `queryRenderedFeatures`.

**Comment by jfirebaugh** [comment]
Thanks! Was able to bisect using that example, landed on e2bac0b8d2bdafd601ef00d4e46285e93075268a.

**Comment by ttsirkia** [comment]
Glad to hear but I already knew the commit and reported that :)

**Comment by ttsirkia** [comment]
Thanks @jfirebaugh for fixing this issue, too!

**Comment by jfirebaugh** [comment]
@lbud deserves the credit, not me!

**Comment by ttsirkia** [comment]
Sorry, thanks @lbud ! :) Nevertheless, you @jfirebaugh have been very active to investigate these issues. That is highly appreciated.
