### ISSUE TITLE
Cut constants code from validate.js

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-js#5875]
I found code in the style spec's `validate.js` function that deals with constants.

https://github.com/mapbox/mapbox-gl-js/blob/6465c04107f34dceb2c16bfd824fdf8c3380fc53/src/style-spec/validate/validate.js#L48-L56

Since constants are for pre-v8 styles, and support for validation of pre-v8 style versions [was cut in v0.42](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#%EF%B8%8F-breaking-changes-1), would it be ok to eliminate this code?

If so, I can PR the change.

**Comment by jfirebaugh** [comment]
The `if (!(value in style.constants))` block should definitely be removed. You could view the remainder as a v8 validation: it's checking that v8 styles don't try to use a deprecated feature. That said, I think constants are far enough in the past that it's unlikely that this check is helpful, and it seems like it's could be a false positive in some corner cases. So I'm 👍  on removing it all.
