### ISSUE TITLE
How to add optimized route layer to Map?

### ISSUE THREAD

**Issue by kevinschaffter** [mapbox/mapbox-gl-js#5877]
Hello,

I have initialized a map and made a succesful ajax request for the optimized route however now I just need to add the layer.  I can't find documentation describing this exact process.

This is the[ optimized route](https://api.mapbox.com/optimized-trips/v1/mapbox/walking/-80.14161839999997,25.7886677;-80.18920760000003,25.810382;-80.1930898,25.7671673?geometries=geojson&access_token=pk.eyJ1Ijoia2V2aW5zY2hhZmZ0ZXIiLCJhIjoiY2piNnNkMmQ2OTBiZzMzcnpzM252OGttdSJ9.vp7HQwPNr--uNONxICdJzg.json): 

I have this now although it doesn't work of course:

```JS
    $.ajax({
      method: 'GET',
      url: directionsRequest,
    }).done(function(data) {
      var route = data;

      map.addLayer({
        id: 'route',
        type: 'line',
        source: {
          type: 'LineString',
          data: {
            type: 'Feature',
            geometry: route
          }
        },
        paint: {
          'line-width': 5
        }
      });
```

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
