### ISSUE TITLE
It is difficult to 'refresh' a source in v0.43.0-beta.1

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-js#5879]
Hi,

I have a use case where I want to refresh/reload the currently visible tiles from a source (because the source data has changed).

At the moment I can call .removeSource() then .addSource() in quick succession which results in the source being reloaded fairly painlessly. As far as I know there's no other way of doing this?

In 0.43.0-beta.1 I can't remove the source without removing all the layers and adding them again due to this change: https://github.com/mapbox/mapbox-gl-js/pull/5562.

Could there be a 'refreshSource()' method which reloads the current tiles? Preferably, it would wait until the new tiles have been received before removing the old ones so there is no 'flicker' (where nothing is visible between removing the old tiles and adding the new ones)?

Thanks!

**Comment by jfirebaugh** [comment]
Yes, it's true that we don't have an API to do this. Tracking that in #2633.
