### ISSUE TITLE
Better error message for missing LngLat data

### ISSUE THREAD

**Issue by nickforddesign** [mapbox/mapbox-gl-js#5880]
**mapbox-gl-js version**: 1.6.2

### Steps to Trigger Behavior

 1. Try to bind a popup to a marker using `.setPopup`, before `.setLngLat`, which is not necessarily counterintuitive

```js
const popup = new mapboxgl.Popup()
  .setDOM('<h1>Hello World!</h1>')

const marker = new mapboxgl.Marker()
  .setLngLat([lng, lat])
  .setPopup(popup)
  .addTo(this.map)
```

### Expected Behavior

An error saying that `LngLatLike` argument is missing altogether?

### Actual Behavior

``"Error: `LngLatLike` argument must be specified as a LngLat instance, an object {lng: <lng>, lat: <lat>}, or an array of [<lng>, <lat>]"``

**Comment by jfirebaugh** [comment]
I'm not able to replicate the issue. After correcting your example code (`setDOM` → `setHTML`), I don't get any errors:

http://jsbin.com/kahufozate/edit?html,output

Can you provide a self-contained example on jsbin that shows the error?

**Comment by nickforddesign** [comment]
Oh man, apologies for the typo and also for providing code that doesn't throw the error haha, it was a crazy day. I probably copied my code after fixing the problem. Here's the updated JSBin:

http://jsbin.com/kesiyeluqe/edit?html,output

**Comment by vuongnguyen-agilityio** [comment]
Hi @jfirebaugh 

Thanks for your help.
But *sometimes*, I still got this issues on v0.53.1
Could you please help to take a look? 🥇

Thanks!
