### ISSUE TITLE
'queryRenderedSymbols' results invalid between tile reload and next rendered frame

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#5887]
Consider a currently loaded tile A, with symbol X displaying on screen and in the collision index, then trigger a reload of tile A.

1. When the reloaded tile result arrives on the foreground, `Tile#loadVectorData` will get called, which will reset the tile's `featureIndex` to a new index from the result. The new index won't have a `collisionIndex` set yet.
2. `SourceCache#_tileLoaded` immediately schedules a "full placement"
3. On the next `Map#render`, full placement will run, and update the `collisionIndex` of all tiles

If someone queries the map between steps 2 and 3, symbol X _will_ be present in tile A's featureIndex, but it won't show up in the query results because the featureIndex isn't linked to a collisionIndex.

The invalid state should only last milliseconds, but if something is querying the map frequently (for instance, the `mouseover` handler), and it happens to hit this gap, you'll see some form of flickering.

/cc @ansis @andrewharvey @livemixlove

**Comment by tobrun** [comment]
Linking https://github.com/mapbox/mapbox-gl-native/issues/8799 as the gl-native equivalent.

**Comment by ChrisLoer** [comment]
> The invalid state should only last milliseconds, but if something is querying the map frequently (for instance, the mouseover handler), and it happens to hit this gap, you'll see some form of flickering.

This is what happened in closely-related issue #5506. We should get this fixed in the next release.

**Comment by ChrisLoer** [comment]
Fixed in #6497.
