### ISSUE TITLE
Toggle Layers Functionality to turn on/off layers embedded within custom mapbox style

### ISSUE THREAD

**Issue by camilaandinod** [mapbox/mapbox-gl-js#5910]
Hello! 

I am creating an interactive webmap using mapbox-gl-js and was wondering if it is possible to turn on/off layers that are embedded within the custom mapbox style, for instance a layer that I created via mapbox studio (adding specific data and styling it accordingly)? 

I run into this example: https://www.mapbox.com/mapbox-gl-js/example/toggle-layers/ but this one only works when the layers themselves are defined within the java script code. 

If anyone know any way around this, please let me know!

Thank you!

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. You can accomplish this by setting the `visibility` property of the layer to `"none"` using [`setLayoutProperty`](https://www.mapbox.com/mapbox-gl-js/api#map#setlayoutproperty) (and back to `"visible" to toggle it back on).

```
map.setLayoutProperty(layerID, "visibility", "none");
```

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by camilaandinod** [comment]
Hi John,

Thank you for the quick response. I've been trying to contact the Mapbox
support team for a few weeks now with no response. That's why I opted for a
Github issue thread. Is there any chance you could answer a couple more
questions I have?

Thanks,

Camila

**Comment by ErinQuinn** [comment]
Thanks @jfirebaugh. @camilaandinod, are you experiencing an issue with the submission form? We don't see a recent ticket from you - please resubmit from https://www.mapbox.com/contact/support/#products so as to get routed properly, thanks!
