### ISSUE TITLE
Markers move from their coordinates after adding/removing class name

### ISSUE THREAD

**Issue by bradsimantel** [mapbox/mapbox-gl-js#5912]
**mapbox-gl-js version**: 0.43.0

### Steps to Trigger Behavior

 1. Dynamically add class name to a marker.
 2. Dynamically remove class name from that marker.
 3. Zoom in/out to see markers move from their coordinates

A demo of this behavior is available here: https://codepen.io/anon/pen/jYMBRq

### Expected Behavior

Markers shouldn't move from their coordinates while zooming.

### Actual Behavior

Markers move from their coordinates while zooming.

### Notes

I think this same bug was previously reported in #5133 and #5151 (I modified the CodePen from #5151 for my demo), which were both resolved by #5139.

**Comment by andrewpomeroy** [comment]
Looks like you're wiping out the `mapbox-marker` class when you change `className`, which I presume is used as a selector to handle positioning of the markers.

https://codepen.io/andrewpomeroy/pen/GyjmZK

**Comment by bradsimantel** [comment]
@andrewpomeroy: Good catch! Closing this issue.
