### ISSUE TITLE
map.on(event, 'canvas-layer', callback) is not capturing events.

### ISSUE THREAD

**Issue by SiggyF** [mapbox/mapbox-gl-js#5916]
**v0.43.0**:
I created this minimal example to show that currently, raster layers based on canvas sources do not seem to capture events. 

https://jsbin.com/yuvaducena/edit?html,css,js,output

### Steps to Trigger Behavior

 1. Create a map with a raster layer, based on a canvas source
 2. Subscribe to the layers events, using `map.on(event, 'layer-id', callback)` api
 3. Log the event 

### Expected Behavior
Event logged.

### Actual Behavior
Nothing logged.

**Comment by SiggyF** [comment]
I found #1404 which is probably related.

**Comment by jfirebaugh** [comment]
Yep, same issue. I'll note there that canvas-sourced raster layers should be included.
