### ISSUE TITLE
Max vertices per segment is 65535

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#5920]
**mapbox-gl-js version**: 0.43.0

What does the following warning from the console mean?

`Max vertices per segment is 65535: bucket requested 98611`

Does that means there are too many nodes for the geometry of a certain feature and I have to simplify the geometry?

**Comment by jfirebaugh** [comment]
> Does that means there are too many nodes for the geometry of a certain feature and I have to simplify the geometry?

Yes, exactly. It indicates a very complex line, polygon, or symbol feature, and you should simplify the geometry.
