### ISSUE TITLE
Switch off close pop up event

### ISSUE THREAD

**Issue by divya1c** [mapbox/mapbox-gl-js#5922]
**mapbox-gl-js version**: v0.42.0
Hi! 

I am using popup.on('close', function(p)){} to make a close popup event. But, I need to have this event fired only in certain cases ie when i click on the close button and not when i programmatically remove the popup. How do I switch off the close event on the popup? 

I've tried to do popup.off('close') but it doesn't work.

Thanks!

**Comment by jfirebaugh** [comment]
You need to call `popup.off('close', fn)`, where `fn` is the same function that you used for `on`.
