### ISSUE TITLE
Error when using flow-bin@0.62.0

### ISSUE THREAD

**Issue by rsolomon** [mapbox/mapbox-gl-js#5923]
[Flow 0.62.0](https://github.com/facebook/flow/blob/master/Changelog.md#0620) removed support for static properties on interfaces.

**mapbox-gl-js version**: 0.43.0

### Steps to Trigger Behavior

 1. `npm install flow-bin@0.62.0`
 2. `flow`

### Expected Behavior

No flow errors.

### Actual Behavior

The following flow error:

```
mapbox-gl/src/source/source.js:41
 41:     static workerSourceURL?: URL;
         ^^^^^^ Unexpected static modifier
```

**Comment by rimiti** [comment]
I've same problem 👍
