### ISSUE TITLE
Move sharable libdefs to flowtyped in a way others can use them

### ISSUE THREAD

**Issue by vicapow** [mapbox/mapbox-gl-js#5924]
Lots of these: https://github.com/mapbox/mapbox-gl-js/tree/master/flow-typed
can live here: https://github.com/flowtype/flow-typed/tree/master/definitions/npm

If you give me permission, I'd be happy to help.

**Comment by jfirebaugh** [comment]
Thanks for the offer, but honestly, these are more just for our own convenience while developing, and I don't want the overhead of PRs to a third party repository if we need to make changes. You're of course free to submit whatever you want to flow-typed, but we'll most likely continue to use the local files.
