### ISSUE TITLE
Native text (Bengali) does not show correctly

### ISSUE THREAD

**Issue by nafis042** [mapbox/mapbox-gl-js#5926]
In OSM data there are some road names in native language (Bangla). Mapbox doesn't seem to show these correctly. I have tried some different Bangla Unicode Fonts (Noto Sans Bangla UI etc) but nothing worked. Here are 2 images side by side. Mapnik openstreetmap can show it correctly but mapbox can't. 
![openstreetmap](https://user-images.githubusercontent.com/26213218/34462960-fafb730e-ee78-11e7-95b1-b1bfbaed9d10.png)
![mapbox](https://user-images.githubusercontent.com/26213218/34462962-032387d8-ee79-11e7-8b23-9399c094b6fe.png)
I can't figure out where the problem is and how to solve it.

**Comment by jfirebaugh** [comment]
It's not currently supported, unfortunately. Tracking this in #4009.
