### ISSUE TITLE
line-dasharray:0 is  error

### ISSUE THREAD

**Issue by xiaoq07** [mapbox/mapbox-gl-js#5929]
mapbox-gl-js version: 0.43.0

the Mapbox Style Specification said 
line-dasharray  :
Optional array of numbers greater than or equal to 0,

Steps to Trigger Behavior
```
addLayer({
   ....
paint:{
   line-dasharray:[0]
}
})
```

 **Expected Behavior**
 
 the line-dasharray is no effect;
 line-dasharray could have default value?
 **Actual Behavior**
   there is no line to show ,

**Comment by jfirebaugh** [comment]
As the documentation goes on to say `line-dasharray` specifies the lengths of the alternating dashes and gaps that form the dash pattern. So `[0]` means zero-length dash (followed by no gap). It's like if you specified the opacity as `0` -- nothing shows up, and that's expected.
