### ISSUE TITLE
Use same algorithm in latY

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#5930]
We projected latitude  to Y in two places:

https://github.com/mapbox/mapbox-gl-js/blob/cbe1cec9afcd570427753b9aa0a96b5a92e98b1b/src/geo/transform.js#L288-L291

https://github.com/mapbox/mapbox-gl-js/blob/cbe1cec9afcd570427753b9aa0a96b5a92e98b1b/src/source/tile_bounds.js#L40-L44

I notice that the two code varies. Shall we unified with same logic to improve maintenance ? 

And in the second:
```
return Math.pow(2, zoom - 1) + 0.5 * Math.log((1 + f) / (1 - f)) * -scale;
```

`-scale` is wired, especially prefix with a `*`. Should we add a parenthesis?

**Comment by vulkd** [comment]
It looks like this was resolved by #7488 / #7570
