### ISSUE TITLE
Staging docs show up in Google search results

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-js#5931]
I searched for "mapbox" and this was in the second page of results:

<img width="665" alt="screen shot 2018-01-02 at 9 41 23 am" src="https://user-images.githubusercontent.com/628431/34491633-6b7f64a4-efa1-11e7-8c49-cbd9c017ef07.png">

To fix this, `<meta name="robots" content="noindex">` tags need to be added to `<head>` during staging builds.

This could probably be done with a conditional in the `PageShell` component: https://github.com/mapbox/mapbox-gl-js/blob/cbe1cec9afcd570427753b9aa0a96b5a92e98b1b/docs/components/page_shell.js#L9-L12

cc @mapbox/frontend

**Comment by jfirebaugh** [comment]
Tracking a fix for this internally.
