### ISSUE TITLE
How to add constant value to a layer filter expression

### ISSUE THREAD

**Issue by magicdawn** [mapbox/mapbox-gl-js#5945]
**mapbox-gl-js version**:
0.42.2

### Steps to Trigger Behavior

I have filter factory for a geojson layer

```js
function getFilter(show){
  return [
    'all',
    ['==', 'id', 1],
    Boolean(show)
  ]
}
```
error message: layers.demo_layer.filter[2]: array expected, boolean found

- I tried to use `['boolean', Boolean(show)]` type assertion and `['to-boolean', Boolean(show)]` type converter, error message like `layers.demo_layer.filter[2][0]: expected one of [==, !=, >, >=, <, <=, in, !in, all, any, none, has, !has], "to-boolean” found`
- Also tried https://github.com/mapbox/mapbox-gl-js/pull/5193, use `{ expression: [...] }`
error message says `layers.realtime_vehicle_locate_layer.filter: array expected, object found`

BTW, The doc

https://www.mapbox.com/mapbox-gl-js/style-spec/#other-filter
> A filter selects specific features from a layer. A filter is defined using any boolean expression. In previous versions of the style specification, filters were defined using the deprecated syntax documented below:

https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions
> The value for any layout property, paint property, or filter may be specified as an expression. 

After that I'm confused how to write a filter expression 😢

**Comment by jfirebaugh** [comment]
Try:

```
function getFilter(show){
  return [
    'all',
    ['==', ['get', 'id'], 1],
    Boolean(show)
  ]
}
```

Note the use of `['get', 'id']` rather than just `'id'`. Using `['all', ['==', 'id', 1], Boolean(show)]` doesn't work because it mixes syntax from old-style filters (`['==', 'id', 1]`) and expressions (boolean literal), which isn't supported. If you use any expression features, then the whole filter must conform to the syntax described in https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions.

**Comment by magicdawn** [comment]
Thanks. now I get the difference between the deprecated old style and the new style.
