### ISSUE TITLE
Visible parts of GeoJSON features are clipped on large zoom levels

### ISSUE THREAD

**Issue by basharov** [mapbox/mapbox-gl-js#5946]
**mapbox-gl-js version**: 0.43.0

### Steps to Trigger Behavior

 1. Add a GeoJSON layer to the map 
 2. Attach a mousemove listener to the added layer, that highlights the layer with another fill color.
 3. Zoom closely to some feature on the map.
 4. See how the feature is clipped on some sides while moving the mouse cursor over it.

### Expected Behavior

 The whole feature area is visible that is inside the viewport.

### Actual Behavior

The feature area is partly visible.

![geojson_cut](https://user-images.githubusercontent.com/625090/34568822-08f92bde-f178-11e7-8ab1-df22cd3024ac.gif)

**Comment by jfirebaugh** [comment]
Without a specific code example, I can't be sure, but it looks like you're running into one of the documented behaviors of [`queryRenderedFeatures`](https://www.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures):

> Because features come from tiled vector data or GeoJSON data that is converted to tiles internally, feature geometries may be split or duplicated across tile boundaries and, as a result, features may appear multiple times in query results. For example, suppose there is a highway running through the bounding rectangle of a query. The results of the query will be those parts of the highway that lie within the map tiles covering the bounding rectangle, even if the highway extends into other tiles, and the portion of the highway within each map tile will be returned as a separate feature. Similarly, a point feature near a tile boundary may appear in multiple tiles due to tile buffering.

To avoid this, apply a filter that includes any tile feature with a matching ID or other unique property, as in [this example](https://www.mapbox.com/mapbox-gl-js/example/hover-styles/).
