### ISSUE TITLE
Expressions of Equality throws error 

### ISSUE THREAD

**Issue by andest01** [mapbox/mapbox-gl-js#5947]
**mapbox-gl-js version**:
Mapbox Version 0.43.0
### Steps to Trigger Behavior
http://jsbin.com/tonekocohu/1/edit?html,output

Create a Mapbox Style with the following paint property:
```
// Minnesota = 27, BRRRRRR ITS COLD
const VERY_COLD_US_STATE_FIPS_CODE = '27' 

// a string property on your source's GeoJSON
const PROPERTY_NAME = 'fips' 

// lets make a style that will highlight Minnesota's border with a
// thicker border - so you know where it's cold!
const equalityExpression = ['==', ['get', PROPERTY_NAME], VERY_COLD_US_STATE_FIPS_CODE]
const widthExpression = ['case',
  equalityExpression, 2.5,
  0.5,
]

// apply our expression to the `line-width` property
// per the mapbox style spec

// this doesnt work :(
const paintProperty = {
    'line-width': widthExpression,
    'line-color': '#FFFFFF',
  },
}
```

### Expected Behavior
The style for the applied geometry uses the expression correctly.

### Actual Behavior
The mapbox engine crashes: `Uncaught Error: can't serialize object of type function`
![screen shot 2018-01-04 at 11 22 06 am](https://user-images.githubusercontent.com/1424223/34575798-a030cac0-f141-11e7-9cd9-b639d113fc26.png)

`==` is undocumented, but clearly exists in the code base.
https://github.com/mapbox/mapbox-gl-js/blob/919be588592509f97eeb4a22510b56e7982dbcc6/src/style-spec/expression/definitions/equals.js
https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/expression/definitions/index.js#L37

The `==` operator did work in a prior mapbox version, specifically `0.42.0`.

**Comment by andest01** [comment]
There's a workaround: Use `all` with `<=` and `>=`.
```
const greaterThanCondition = ['>=', ['to-string', ['get', PROPERTY_ID]], expectedProperty]
const lessThanCondition = ['<=', ['to-string', ['get', PROPERTY_ID]], expectedProperty]
const terribleEquality = ['all', greaterThanCondition, lessThanCondition]
const widthExpression = ['case',
  noStateSelected, 0.5,
  terribleEquality, 2.5,
  0.5,
]
```

**Comment by jfirebaugh** [comment]
@andest01, thanks for the report. Could you please provide a self-contained example on jsbin.com or similar that shows the issue?

**Comment by andest01** [comment]
@jfirebaugh http://jsbin.com/cumotohelu/3/edit?html,output

**Comment by jfirebaugh** [comment]
That seems to be generating some unrelated style validation errors.

**Comment by andest01** [comment]
How frustrating - I inadvertently pasted an older version. My apologies. 

I tested this version in a new tab and it's exhibiting the above behavior.
http://jsbin.com/tonekocohu/1/edit?html,output

![screen shot 2018-01-04 at 12 35 39 pm](https://user-images.githubusercontent.com/1424223/34578769-cd136cb4-f14b-11e7-81fb-884cd383237b.png)

**Comment by jfirebaugh** [comment]
Ok, I can reproduce it after some tweaks to that example. Should be an easy fix.
