### ISSUE TITLE
Render tokens, math functions, and text-size percentages

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-js#595]
We might be able to cut down on a lot of layers and simplify the stylesheet by introducing tokens and math functions in render tokens and percentage-based text-size (style) properties. I'm imagining something like:

Render *(equivalent to <code>30 - (labelrank * 0.5)</code>):*
```js
"text-max-size": {
  "-": [30, {"*": ["{labelrank}", 0.5]}]
}
```

Style:
```js
"text-size-percentage": {
  "stops": [[4, 60], [12, 100]]
}
```

@nickidlugash @aj would this be useful/worthwhile?

**Comment by jfirebaugh** [comment]
https://github.com/mapbox/mapbox-gl-style-spec/issues/47
https://github.com/mapbox/mapbox-gl-style-spec/issues/105
