### ISSUE TITLE
Performance issues using multiple image layers for animation

### ISSUE THREAD

**Issue by jordandalley** [mapbox/mapbox-gl-js#5952]
Hi there,

As per the example here on https://www.mapbox.com/mapbox-gl-js/example/animate-images/ I have animated a series of images and switch them on and off using map.setPaintProperty('imagex', 'raster-opacity', y);.

For a small number of images, little performance degradation is noticeable. However, the more images added the slower the user interface becomes.

In a profiler, it appears that every time the raster-opacity is changed from 0 to 1, mapbox-gl rerenders the image entirely. Also, the more image layers, the slower that rerendering is.

The working example I have is here: https://www.townsvilleweather.com/?p=enhradar

Is there a workaround for this phenomenon at all?

Cheers,
Jordan.

**Comment by mourner** [comment]
Not sure if there's a workaround for the image source, but have you considered using a VideoOverlay instead? That could be much more efficient both for rendering and bandwidth.

**Comment by jfirebaugh** [comment]
Hi @jordandalley, it looks like you're using 0.41.0. Can you please try updating to the latest version?
 There was an important [performance fix for image sources](https://github.com/mapbox/mapbox-gl-js/pull/5845) in 0.43.0.

**Comment by jordandalley** [comment]
Perfect! Thanks heaps. Works a treat now.
