### ISSUE TITLE
draw text and halo in one call

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#596]
Text halos are currently drawn in a separate call. Since text is usually drawn with a halo we should add halo support to the shader so that we can do it in one.

**Comment by anandthakker** [comment]
Looked into this again in working on #4186 -- @jfirebaugh proposed `gl_FragDepth` as a promising way to handle the overlap issue, but, alas, the browser support for it is very limited (65% desktop, < 5% mobile)
