### ISSUE TITLE
mapbox-gl does not render all GeoJSON layers

### ISSUE THREAD

**Issue by vicapow** [mapbox/mapbox-gl-js#5970]
This is only on master and from what I can tell is not an issue with the latest published version, 0.43.0. 

Here's the full example after modifying setstyle.html.

Expected: A red circle layer to be rendered as in https://jsbin.com/kurufojuvi/edit?html,output.

<img width="154" alt="screen shot 2018-01-08 at 8 06 44 pm" src="https://user-images.githubusercontent.com/583385/34704789-6bf12aee-f4b0-11e7-931d-f664a9a1a88f.png">

Actual: No red layer is ever rendered.

<img width="132" alt="screen shot 2018-01-08 at 8 07 35 pm" src="https://user-images.githubusercontent.com/583385/34704791-6e46c9ac-f4b0-11e7-8d90-ff27555bf42d.png">

I was able to track this down to [this specific diff](https://github.com/mapbox/mapbox-gl-js/commit/fa95c19c0160949dec1b482ee7f259d04e51db90): from @ChrisLoer 19 days ago. Can we revert?

````html
<!DOCTYPE html>
<html>
<head>
    <title>Mapbox GL JS debug page</title>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel='stylesheet' href='/dist/mapbox-gl.css' />
    <style>
        body { margin: 0; padding: 0; }
        html, body, #map { height: 100%; }
    </style>
</head>

<body>
<div id='map'></div>
<script src='/dist/mapbox-gl-dev.js'></script>
<script src='/debug/access_token_generated.js'></script>
<script>

var data = {
    type: 'FeatureCollection',
    features: [
        {
            type: 'Feature',
            properties: {},
            geometry: { type: 'Point', coordinates: [ -122.41848707199095, 37.77554439836295 ] }
        }
    ]
};
var style = {
    version: 8,
    name: 'example',
    minzoom: 0,
    maxzoom: 22,
    sources: {
        source1: { type: "geojson", data: data },
        source2: { type: "geojson", data: data },
        source3: { type: "geojson", data: data },
        source4: { type: "geojson", data: data },
        source5: { type: "geojson", data: data }
    },
    layers: [
        {
            id: 'source1-layer',
            source: 'source1',
            type: 'circle',
            paint: { 'circle-radius': 50, 'circle-color': '#ccc' }
        }, {
            id: 'source2-layer',
            source: 'source2',
            type: 'circle',
            paint: { 'circle-radius': 40, 'circle-color': '#999' }
        }, {
            id: 'source3-layer',
            source: 'source3',
            type: 'circle',
            paint: { 'circle-radius': 30, 'circle-color': 'red' }
        }, {
            id: 'source4-layer',
            source: 'source4',
            type: 'circle',
            paint: { 'circle-radius': 20, 'circle-color': '#333' }
        }, {
            id: 'source5-layer',
            source: 'source5',
            type: 'circle',
            paint: { 'circle-radius': 10, 'circle-color': '#000' }
        }
    ]
};

var map = window.map = new mapboxgl.Map({
    container: 'map',
    zoom: 22,
    center: [-122.41848286, 37.77552867],
    style: style,
    hash: style
});

// map.loaded() never returns `true`.
// The 3rd layer (red point) never renders.
setInterval(() => { console.log(map.loaded()); }, 100);

</script>
</body>
</html>
````

**Comment by ChrisLoer** [comment]
Thanks for the super-clear report, @vicapow! I can reproduce the problem in Safari but not Chrome or Firefox -- which browser(s) are you using? I'll investigate and come up with a fix (hopefully this won't require a revert).

**Comment by vicapow** [comment]
@ChrisLoer Glad to help! This is my setup

Chrome Version 63.0.3239.132 (Official Build) (64-bit)
OS X 10.12.6 (16G1036)
MacBook Pro (13-inch, 2017, Four Thunderbolt 3 Ports)
3.5 GHz Intel Core i7
16 GB 2133 MHz LPDDR3
Intel Iris Plus Graphics 650 1536 MB

**Comment by vicapow** [comment]
I've also just tested this on Safari and FireFox and am able to reproduce the issue in those browsers, as well. Based on your changes this doesn't seem like a browser specific issue or GPU related. Might be worth double checking your cache was cleared in Chrome when you tried it.

<img width="1907" alt="screen shot 2018-01-10 at 10 50 11 am" src="https://user-images.githubusercontent.com/583385/34789740-476f65ba-f5f4-11e7-8495-291ae6d47d58.png">

**Comment by ChrisLoer** [comment]
The problem is that when one GeoJSON worker is handling multiple sources, it can mix up loadData/coalesce messages between the two sources. Whether or not it messes up depends on timing, which probably accounts for the differences between what you saw and what I saw.

The fix is pretty easy, I'll submit a PR later today.

**Comment by ChrisLoer** [comment]
Fixed temporarily with revert of https://github.com/mapbox/mapbox-gl-js/commit/fa95c19c0160949dec1b482ee7f259d04e51db90 via #5971.

We plan to restore the coalesce functionality with #5983.
