### ISSUE TITLE
Layer is not displayed for maxzoom

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#5975]
**mapbox-gl-js version**: v0.43.0

### Steps to Trigger Behavior

 Add a layer and set `maxzoom` matching the default `zoom` of the map.
 
### Expected Behavior
Layer is shown for the `maxzoom` zoom level.

### Actual Behavior
Layer is not shown for the `maxzoom` zoom level. https://jsfiddle.net/fo543kwa/

Without `maxzoom`  the layer is displayed:  https://jsfiddle.net/fo543kwa/1/

Documentation for `maxzoom`:

Style Spec:
~~https://www.mapbox.com/mapbox-gl-js/style-spec#sources-vector-maxzoom~~

Mapbox Studio:
![image](https://user-images.githubusercontent.com/20856381/34759946-1076abd8-f5de-11e7-864a-3ca203217e93.png)

**Comment by pathmapper** [comment]
Maybe this is expected behaviour and I'm only confused by the tooltip in Studio.

If it's expected behaviour, this issue could be closed as there is already an issue regarding the documentation of `maxzoom`: https://github.com/mapbox/mapbox-gl-js/issues/5918

**Comment by pathmapper** [comment]
In the issue description linked wrongly to the source `maxzoom` in the style spec, layer `maxzoom` is this one:
https://www.mapbox.com/mapbox-gl-js/style-spec/#layer-maxzoom


> maxzoom
Optional number between 0 and 24 inclusive.
The maximum zoom level on which the layer gets parsed and appears on.

**Comment by jfirebaugh** [comment]
It's a half-open range: the layer is visible when `minzoom <= z < maxzoom`. We'll clarify the docs.

**Comment by pathmapper** [comment]
Thanks!
