### ISSUE TITLE
Line-pattern rendering pieces of other sprites

### ISSUE THREAD

**Issue by aparlato** [mapbox/mapbox-gl-js#5978]
**mapbox-gl-js version**: 0.43.0

[Similar/same issue appears to have come up and been resolved in native](https://github.com/mapbox/mapbox-gl-native/issues/9976). Hopefully I'm not making a repeat issue here, but didn't see it in gl-js issue queue.

### Steps to Trigger Behavior

 1. Create a line pattern on a thicker line (use motorway in Streets for instance)
 2. Add an icon (try `de-federal-4`, not all icons behave this way, but enough do)
 3. Zoom in anywhere between z 17 and z 22 (Also works if you just increase width significantly)
 4. See other icons partially rendered in addition to desired icon

![image](https://user-images.githubusercontent.com/15698320/34790883-14b1e3e2-f5f8-11e7-93bb-13813c4d0ad7.png)

### Expected Behavior

Scale icon as needed for `line-pattern`.

### Actual Behavior

Scales icon, but shows pieces of other sprites at high zooms or large widths.

**Comment by jfirebaugh** [comment]
This seems like it could be the same issue as https://github.com/mapbox/mapbox-gl-native/issues/9976, but re-reviewing https://github.com/mapbox/mapbox-gl-native/pull/9990, it doesn't look like the right fix. When an image is added to the pattern atlas, all the pixels within the padded bounds for that image are overwritten. Therefore it shouldn't matter whether or not there were previous images that got removed, or whether or not their rects were cleared. I suspect that sufficiently wide lines simply cause the line pattern shader to read outside of the proper texture bounds for the pattern image.

**Comment by jfirebaugh** [comment]
Test case in https://github.com/mapbox/mapbox-gl-js/commit/47aa5f7a8dca12f1a92c426845bc4c51c02f10ec.
