### ISSUE TITLE
Wobbly/shaky/dancing point icons on hover with many points

### ISSUE THREAD

**Issue by mapsam** [mapbox/mapbox-gl-js#5980]
Hello folks!

We're noticing point icons dancing around when hovering on point icon layers. This appears to only happen when there are many points styled to use icons and the hover action requires the icon to change. Here's a working example here (with a gif below): https://bl.ocks.org/jessesnyder/70f175b6b252e81dceabc458f01c4562

![point-wobble-gl-js](https://user-images.githubusercontent.com/1943001/34798122-a2e9fe80-f60f-11e7-86b4-e6e584f12cfc.gif)

*Tangentially related to https://github.com/mapbox/mapbox-gl-js/issues/5506 as you can see the hover effect flickers on the icon as well.*

**mapbox-gl-js version**: 0.43.0

### Steps to Trigger Behavior

 1. hover over the points

### Expected Behavior

No wobble

### Actual Behavior

Wobble

cc @malwoodsantoro @jessesnyder

**Comment by ansis** [comment]
Thanks for the example! I can reproduce with 0.43.0 but not on master so it looks like it's been fixed. I think https://github.com/mapbox/mapbox-gl-js/pull/5890 might have done it. The wobbling was actually buggy fading hiding a point and uncovering a nearby-but-slightly-off point

**Comment by mrwweb** [comment]
@ansis @mapsam I'm glad the wobble got fixed!

To test, I copied the above gist and updated to v0.44.0: https://bl.ocks.org/mrwweb/9b177f693d8f7c6b965f2c2a46a276d3

The wobble issue is indeed fixed, but in Firefox and Chrome the symbol-layer-change-on-hover feature works only intermittently before completely stopping. It appears that was also buggy in v0.43.0 ([which you can still test](https://bl.ocks.org/jessesnyder/70f175b6b252e81dceabc458f01c4562)), though it's actually more responsive in that previous version (though still not right).

This may be related to #6022. We're eager to see better support of hover-related interactions for our map!
