### ISSUE TITLE
can not add a empty source .

### ISSUE THREAD

**Issue by xiaoq07** [mapbox/mapbox-gl-js#5986]
i want to add a empt geojson as source  and i get a error  as 
this:

  let geojson = {
        'type': 'geojson',
        'data': {
            'type': 'FeatureCollection',
            []
        }
    };
map.addSource(id,geojon);
then  i get a console error 
``` 
Uncaught TypeError: Cannot read property 'type' of undefined
```

**Comment by thunderkid** [comment]
This works. In case google leads anyone else here.
```
{
  'type': 'geojson',
  'data': {
    'type': 'FeatureCollection',
    'features': []
  }
}
```

**Comment by mvl22** [comment]
I think the documentation at:
https://docs.mapbox.com/mapbox-gl-js/api/sources/#geojsonsource#setdata

which shows an empty data being created:

```
map.addSource('source_id', {
    type: 'geojson',
    data: {}
});
```

is wrong.
