### ISSUE TITLE
Uncaught (in promise) Error: Unimplemented type: 3 

### ISSUE THREAD

**Issue by brstillwell** [mapbox/mapbox-gl-js#5992]
I have read that this error is being caused by the pbf files not being gzipped when being imported and saved. How exactly do I compress them in transit? I have installed the compression module for express and it gzips everything except these pbfs. Is there some sort of middleware that I am missing?

**Comment by mollymerp** [comment]
Hi @brstillwell – thank you for using Mapbox. This issue tracker is for bug reports and feature requests only. I suggest you ask this question on [StackOverflow](https://stackoverflow.com/questions/tagged/vector-tiles) or contact [Mapbox Support](www.mapbox.com/help) for help with your issue.
