### ISSUE TITLE
Footer bleeds into sidebar nav

### ISSUE THREAD

**Issue by kalimar** [mapbox/mapbox-gl-js#6001]
**mapbox-gl-js version**:

### Steps to Trigger Behavior

 1. Scroll down on https://www.mapbox.com/mapbox.js/example/v1.0.0/coffeescript/

![screen shot 2018-01-16 at 10 53 38 am](https://user-images.githubusercontent.com/1248672/34997873-95f72bda-faab-11e7-9035-664bbedc9f09.png)

### Expected Behavior
The footer should be below the main content body and sidebar

### Actual Behavior
Footer bleeds into the left navigation bar. I believe the footer may need absolute positioning.

**Comment by andrewharvey** [comment]
This is being tracked over on the mapbox.js repo at https://github.com/mapbox/mapbox.js/issues/1231
