### ISSUE TITLE
setData causes some labels to fade out and fade in

### ISSUE THREAD

**Issue by ttsirkia** [mapbox/mapbox-gl-js#6002]
**mapbox-gl-js version**: f232d74

### Steps to Trigger Behavior

 1. Update data by calling `setData`

### Expected Behavior

Labels stay where they are or move to a new position

### Actual Behavior

Labels fade out and immediatelly back in.

f232d74 is the first version having this problem.

**Comment by ttsirkia** [comment]
Is the master available in any CDN? I could try to create a minimal JSFiddle if the reason for this is not obvious.

**Comment by ttsirkia** [comment]
https://jsfiddle.net/c0tg4h5o/1/

**Comment by ChrisLoer** [comment]
Wow, who needs CI when we've got people like you testing our commits so quickly! 😉 

I see the problem in the JSFiddle, investigating now.

**Comment by ChrisLoer** [comment]
Fixed with #6003, thanks again @ttsirkia!
