### ISSUE TITLE
Examples for to-string and to-number expression documentation

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mapbox-gl-js#6007]
The links to the ECMAScript specification may be accurate but they are probably not very helpful, really, for most readers. 

They also might leave out some expression-specific edge cases. For example, if a string like `"thing"` would get `NaN` when coerced in JS — what happens in the type coercion expression? Looks like maybe GL JS issues a warning and the property's default value is used?

**Comment by jfirebaugh** [comment]
Would adding a sentence like "For example, the expression `["to-number", "thing"]` is an error." to the end of the existing `to-number` documentation address your concern, or are there other specific cases you have in mind?

I tried to strike a good balance between covering the essential behaviors that would be needed for basic use of these operators, and avoiding _ad hoc_ coverage of particular edge cases. If you really need to know the precise behavior in edge cases, you _are_ actually best served by the ECMAScript specification in my opinion -- trying to re-specify all of its detail seems like it would be undue weight for the style specification (not to mention it's significant work and we'd probably miss something).

**Comment by davidtheclark** [comment]
> trying to re-specify all of its detail seems like it would be undue weight for the style specification

This is true 😃. 

I do think that the `NaN` situation — for `to-number` the equivalent of JS's `NaN` is an error — might be worth noting. For everything else, I guess I'm just expressing that for most end users the ECMAScript spec probably reads like nonsense, so unless they know JS pretty well the link won't help explain much, right? It works for *accuracy*, though. A short list of examples could cover all the cases that most people would need, certainly enough to grasp what these expressions are for. However, I understand if you think the style spec itself isn't the right place for that kind of handwavy documentation. I wonder if there's a better place?

(The origin of this issue is building a UI for Studio, where the docs we show users are derived from the style spec — but we definitely can't take for granted that an ECMAScript spec reference means anything to an average Studio user. Maybe the fundamental problem is that Studio's documentation needs are so different from the spec's, but right now they're bound together. cc @mapbox/studio)

**Comment by jfirebaugh** [comment]
> A short list of examples could cover all the cases that most people would need

Do you have some particular examples in mind?

**Comment by davidtheclark** [comment]
Oh, maybe stuff like 

- `["to-string", 4] === "4"`
- `["to-string", false] === "false"`
- `["to-number", "4"] === 4`
- `["to-number", "foo"]` errors
- `["to-boolean", 0] === false`
- `["to-boolean", 1] === true`
- `["to-boolean", ""] === false`
- `["to-boolean", "foo"] === true`

**Comment by jfirebaugh** [comment]
I find myself resistant to adding examples that duplicate what's spelled out already in the prose. I think it's because I view the individual operator documentation as a reference work rather than a tutorial.

@anandthakker, 3rd opinion?

**Comment by anandthakker** [comment]
I'm okay with including examples to help make it a little more accessible.  (Maybe not `["to-string", false] === "false"` since we actually have a sentence that says this, but some of the others seem fine.)

It may be worthwhile to split these into two paragraphs: the first with just the "plain" language description parts (and whatever examples are needed to make it pretty clear to most readers), and the second filling out full accuracy by referring to the ECMAScript spec.

**Comment by alpha-beta-soup** [comment]
What about `["to-number", "4 m"] === ???`

**Comment by ryanhamley** [comment]
I'm inclined to agree with John's reasoning above, especially since we haven't had any significant issues with this since this ticket was opened. I'm closing it as stale.
