### ISSUE TITLE
icon-image not rendering sometimes when changing geojson data

### ISSUE THREAD

**Issue by tjhelmuth** [mapbox/mapbox-gl-js#6008]
Hi, I'm trying to get a map with icons rendered on a vector based map using mapbox gl. It works fine in most scenarios but I change the geojson data for the markers showing on the map and every time I change that data, I calculate the bounds and pan the map to fit those bounds.

I have been noticing in some scenarios the symbol layer with icon-image is not rendering for certain geojson features. The circle renders, so I'm sure the map knows about the feature itself, but it does not draw the icon right away. If I zoom in on that feature, the icon will eventually render, but I need to understand why it's not rendering initially and correct that.

It seems like it affects features near the edge of the map, and when I resize the map up to 4k width, the issue never happens when there is enough space between the icon and the edge of the map.

Image of issue: 
https://i.imgur.com/LejFd4P.png

Reproducible test case:
http://jsfiddle.net/Lb4h5dbx/18/

**mapbox-gl-js version**: 
0.43.0

### Steps to Trigger Behavior

 1. Keep the section of jsfiddle with the map relatively small <= ~1680 px width
 2. Click Third -> Second -> First -> All **without allowing the animations to finish**

Note: **If I set animate:false in the fitBounds options, it seems to reduce the frequency of this happening, but it still occasionally happens.**

### Expected Behavior
The eastern marker should always show the symbol layer
### Actual Behavior
The eastern marker almost always has the symbol layer, my icon, hidden.

I really appreciate this library and I could very easily be doing something wrong but I really need to be able to always show the icons.

**Comment by tjhelmuth** [comment]
This seems to be fixed recently as I am not able to reproduce the issue after building the latest code myself. Not sure what was broken or what fixed it.

**Comment by ansis** [comment]
Thanks for the test case! Since it seems to be fixed on `master` I'll close this issue. Please re-open if you encounter it again
