### ISSUE TITLE
this$1.layers[id] is undefined

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#6014]
**mapbox-gl-js version**: 0.43.0

### Steps to Trigger Behavior

I'm nowhere near a minimal repro on this. I have a fairly heavy app, with various layers that are turned on and off. Sometimes, after a few cycles of switching layers, the map stops responding to any further input, and this message is in the console (when using the `-dev` build):

```
TypeError: this$1._layers[id] is undefined  style.js:387:79
TypeError: this$1.style._layers[layerId] is undefined   painter.js:131:16
```

Unfortunately I can't publish the app I'm working on. 

Any suggestions for tests to try to try to narrow it down?

**Comment by asheemmamoowala** [comment]
> various layers that are turned on and off

@stevage are you using `Map.addLayer` and `Map.removeLayer`, or some other method to turn the layers on/off? When a layer is re-added does it reuse the previous `id`?

**Comment by stevage** [comment]
> are you using Map.addLayer and Map.removeLayer, or some other method to turn the layers on/off? 

Yes.

> When a layer is re-added does it reuse the previous id?

Yes. Basically, I want to switch the source for a layer, but there's no way to do that directly, so I remove it and add it again immediately.

I'll try adding a slight delay before adding the layer again to see if that prevents the issue. Unfortuntely it's not predictable.

**Comment by asheemmamoowala** [comment]
Is the `visibility` layout property not viable in your application? It should be more performant than the add/remove layer approach.

A (more) predictable way to know when a style update, such as add/remove layer, is complete is to use a handler for the [`styledata`](https://www.mapbox.com/mapbox-gl-js/api/#map.event:styledata) event.

**Comment by stevage** [comment]
Thanks, that's helpful. Using `visibility` is possible, although it changes a fair amount of code for me - currently, the one visible layer always has the same ID. Are there any downsides to having a large number of invisible layers?

**Comment by asheemmamoowala** [comment]
@stevage invisible layers are not processed for rendering, so it consumes fewer resources compared to a visible layer. That said toggling visibility requires re-preparing the layer and will perform as well as `addLayer`/`removeLayer.`
