### ISSUE TITLE
Docs about css for stuff like geolocate

### ISSUE THREAD

**Issue by Forsskieken** [mapbox/mapbox-gl-js#6015]
Hi there,

I can't seem to find documentation regarding css for the geolocate button.
I looked in github, stack exchange the api.mapbox.com so quite a few places.
In the underlying screenshot one can see what I'm trying to achieve.

The other thing I can't seem to find is how to search for data outside the viewport, but restricted to a bounding box.

![image](https://user-images.githubusercontent.com/3041025/35088670-c61e9df4-fc34-11e7-8a8e-f80aaa458ee0.png)

Kind regards,
Guy Forssman

**Comment by andrewharvey** [comment]
It doesn't look like custom styles is documented much but you can override CSS found in https://github.com/mapbox/mapbox-gl-js/blob/master/dist/mapbox-gl.css with your own styling.

If you want to move a control outside the map take a look at this example https://github.com/mapbox/mapbox-gl-js/blob/adf7793b39fd8799579e88cb4e049fe1b9199922/docs/pages/example/mapbox-gl-geocoder-external-search-box.html

**Comment by mollymerp** [comment]
HI @Forsskieken – thank you for using Mapbox! This issue tracker is for bug reports and feature requests. If @andrewharvey's suggestions didn't solve your issues, I suggest you ask your questions on [StackOverflow](https://stackoverflow.com/tags/mapbox-gl-js) or contact [Mapbox support](www.mapbox.com/help).
