### ISSUE TITLE
The info icon should be removed if the stylesheet is not from Mapbox

### ISSUE THREAD

**Issue by Roxyi** [mapbox/mapbox-gl-js#6017]
**mapbox-gl-js version**: 0.43.0

It seems that in the v-0.43.0, if you are not using stylesheets from Mapbox, the Mapbox logo will not be shown on the map. 
![image](https://user-images.githubusercontent.com/8086358/35118332-7029cd94-fc5f-11e7-8a5d-a290959bb6c8.png)

However, when the size of the map container goes to 600px or less, there will be an info icon on the bottom-right of the map.
![image](https://user-images.githubusercontent.com/8086358/35118438-c106b3f8-fc5f-11e7-9538-9f005a796306.png)

If you click that info icon, there is nothing shown to you. I think it should be removed. Otherwise, there should be some information shown to users.

**Comment by ttsirkia** [comment]
It should show the copyright information about the map tiles. Are you missing that data in your data source?

**Comment by andrewharvey** [comment]
Keep in mid that "i" icon expands on mouse hover not on click, so sometimes is buggy especially on touchscreens when you try to click it.

**Comment by Roxyi** [comment]
@ttsirkia You mean the style.json?

**Comment by Roxyi** [comment]
@andrewharvey Here is a [JSFiddle](https://jsfiddle.net/yixu/x03xg74b/) example I created. I don't see anything whether hover or click the "i"

**Comment by ttsirkia** [comment]
Typically the attribution info comes from the tiles. See Map.options to disable the mark.

**Comment by Roxyi** [comment]
@ttsirkia Thank you. The attribution info is missing in the tiles of the basemap. I got rid of the "i" icon by disabling the attributionControl in map.options.

**Comment by ttsirkia** [comment]
Seems that this is fixed in #6042 so that the icon is not visible if the attribution info is empty.
