### ISSUE TITLE
var fea = map.queryRenderedFeatures({layers:['jzw']});it did not return every feature in the jzw layer

### ISSUE THREAD

**Issue by zhangpengye** [mapbox/mapbox-gl-js#6023]
who can tell me, i want click layer ,and return every feature from the queryRenderedFeatures，but it doesnot return every feature.why???

**Comment by ansis** [comment]
What is it returning? What are you expecting it to return?

`map.queryRenderedFeatures({layers:['jzw']})` should return all features within the current viewport. It will not return features from tiles that are not currently loaded.

**Comment by zhangpengye** [comment]
thank you,i want ask you some analysis problem，in mapbox，i can use a point to generate buffer，but i can not use line generate buffer,in turf ,it use this sentences to initializa the map.
 var map = L.mapbox.map('map', 'mapbox.dark', { zoomControl: false });
but in mapbox ，it use this sentences below to initializa the map.
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [-96, 37.8],
    zoom: 3
});
it lack of the "L",so i can not use line buffer in mapbox?

**Comment by zhangpengye** [comment]
@ansis 
thank you,i want ask you some analysis problem，in mapbox，i can use a point to generate buffer，but i can not use line generate buffer,in turf ,it use this sentences to initializa the map.
var map = L.mapbox.map('map', 'mapbox.dark', { zoomControl: false });
but in mapbox ，it use this sentences below to initializa the map.
var map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/mapbox/streets-v9',
center: [-96, 37.8],
zoom: 3
});
it lack of the "L",so i can not use line buffer in mapbox?

**Comment by ansis** [comment]
The documentation for Turf can be found here: http://turfjs.org/docs

You maybe want to check our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
