### ISSUE TITLE
TypeError when calling setPaintProperty

### ISSUE THREAD

**Issue by astrojams1** [mapbox/mapbox-gl-js#6030]
I'm trying to customize the background's fill color and am hitting a type error when the map loads. The relevant code is typed below, and I am attaching a screenshot of the error I see when this runs. 

```
var map = new mapboxgl.Map({
        container: this.mapContainer,
        center: homePoint.geometry.coordinates,
        style: 'mapbox://styles/mapbox/outdoors-v10',
        interactive: false,
});
    map.on('load', function () {
        map.setPaintProperty('background','fill-color', 'rgb(237,0,0)')
})
```

![screen shot 2018-01-20 at 5 30 18 pm](https://user-images.githubusercontent.com/1023503/35191993-7714b8b4-fe3d-11e7-96bb-1e9990086ed2.png)

**Comment by ansis** [comment]
Background layers have a `background-color` property instead of `fill-color`: https://www.mapbox.com/mapbox-gl-js/style-spec#layers-background

I've opened an issue about improving the error messages for cases like this! https://github.com/mapbox/mapbox-gl-js/issues/6033
