### ISSUE TITLE
User location dot flickers

### ISSUE THREAD

**Issue by areichman** [mapbox/mapbox-gl-js#6034]
**mapbox-gl-js version**: 0.43.0

### Steps to Trigger Behavior

 1. Visit https://www.mapbox.com/mapbox-gl-js/example/locate-user/
 2. Click geolocate control

### Expected Behavior

An animated pulse should be visible without any flickering/blinking.

### Actual Behavior

In addition to the pulsing animation, a flicker/blink appears as part of the animation.

I see this behavior in Safari on macOS as well as Safari/Chrome/Firefox/Edge on iOS. I do not see the flicker/blink behavior in Chrome for macOS or Windows 7.

### Possible Fix

It appears to me those browsers are introducing the flicker when the `box-sizing` is set to the default value of `content-box`. Setting `border-box` for the location dot makes the flicker go away, but then some width/height adjustments are needed, along with some top/left adjustments to make the pulse line up with the dot again.

**Comment by andrewharvey** [comment]
I think this issue should be fixed by https://github.com/mapbox/mapbox-gl-js/pull/5498

**Comment by andrewharvey** [comment]
Should be fixed now by #5498.
