### ISSUE TITLE
Is there a callback for fitbounds method?

### ISSUE THREAD

**Issue by divya1c** [mapbox/mapbox-gl-js#6035]
Hi! 

Is there a callback or promise for fitbounds method or is there any other similar method to fitbounds that fulfills this spec? Or is there an event that is triggered after fit bounds?

Thanks!

**Comment by asheemmamoowala** [comment]
@divya1c thanks for using Mapbox!

`Map.fitBounds`  fires a `moveend` event after it completes. `pitchend` and `zoomend` events may also be fired if needed. You may use the `eventData` parameter to aff objects useful to recognize the event in the event handler callbacks.

You can ask "how do I" questions like this at https://stackoverflow.com/questions/tagged/mapbox-gl-js
