### ISSUE TITLE
First time I open a popup

### ISSUE THREAD

**Issue by marioerro** [mapbox/mapbox-gl-js#6038]
I'm trying to create a popup, but first time I do not get the right style. What I can be doing wrong?

    var canvas = document.getElementById("canvas");
.
.
.
My html.

         <canvas id='canvas' style="min-width: 600px; margin: -4px"></canvas>

.
.
.

    map.on('click', 'region-capa', function (e) {
            if (typeof myChart != 'undefined') {
                myChart.destroy();
            }
            if (e) {
                nombre = e.features[0].properties.SST_NOMBRE;
                $.ajax({
                    type: "GET",
                    url: "/Mapa/GetEstadisticas/" + parseInt(e.features[0].properties.SST_ID),
                    contentType: "application/json",
                    dataType: "json",
                    success: function (response) {
                        if (response) {
                            grafica(response);
                            new mapboxgl.Popup({ closeButton: true, closeOnClick: true })
                                .setLngLat(e.lngLat)
                                .setDOMContent(canvas)
                                .addTo(map);
                        }

                    },
                    failure: function (response) {
                        alert(response);
                    }
                });
            }
        });;

![captura](https://user-images.githubusercontent.com/2707903/35266189-c11f0856-0022-11e8-9a4e-0e8c2a8420a0.JPG)

**Comment by lbud** [comment]
Hi @marioerro, thanks for using Mapbox. For "how do I" questions like this we recommend you ask on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox-gl-js). This issue tracker is for reporting bugs and feature requests. Thank you!
