### ISSUE TITLE
Set pitch slow since 4.3 update

### ISSUE THREAD

**Issue by Jhovanni** [mapbox/mapbox-gl-js#6040]
I have a map, and update its pitch when user zoom. Pitch is calculated on zoom event. Using 0.42.2 it works great, but when I updated to 43.0, it started to slow a lot. After verifying where the issue was, I identifyied its setPitch method taking much more time than before.

**mapbox-gl-js version**: 43.0

### Steps to Trigger Behavior

 1. Initialice map
 2. In map zoom, set map pitch to any value (it can be the same every, doesn't matter)
 3. See how map zoom is too slow now. It wasn't this way in version 0.42.2

### Expected Behavior
Call setPitch method sould be fast as before

### Actual Behavior
setPitch method use impacts in performance where it did not before

**Comment by asheemmamoowala** [comment]
@Jhovanni Thank you for using mapbox-gl-js! Could you provide a minimal jsfiddle or jsbin that reproduces this issue to help us diagnose your issue?

**Comment by Jhovanni** [comment]
https://jsfiddle.net/2e9o5kp9/#&togetherjs=qtTf8mtPPc
Version 0.44.0 looks more efficient again. But I leave the script to help prevent the problem from happening again in later versions

**Comment by asheemmamoowala** [comment]
Fixed in v0.44.0 by https://github.com/mapbox/mapbox-gl-js/pull/6029
