### ISSUE TITLE
add the ability to access data outside of the feature properties for data driven styles

### ISSUE THREAD

**Issue by kewlspopo** [mapbox/mapbox-gl-js#6045]
I have a json which maps id to values and would like to make a choropleth map from this. 
From the choropleth map examples in the mapbox-gl-js docs, it seems we're limited to just using values from the actual features. 

This should be added.

**Comment by asheemmamoowala** [comment]
@kewlspopo Thank you for using Mapbox! This is possible and covered in the [Join local data](https://www.mapbox.com/mapbox-gl-js/example/data-join/) example.

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). Thank you!
