### ISSUE TITLE
could line-dasharray support Function

### ISSUE THREAD

**Issue by wxqqq** [mapbox/mapbox-gl-js#6053]
i want to add a line layer with different  line-dash style.
but the line-dasharray didn't support property functions.

it means i have to  add mulitylayer to show the effect. 

could fix it ?

**Comment by lbud** [comment]
Closing as duplicate of https://github.com/mapbox/mapbox-gl-js/issues/3045 — we haven't implemented this yet for technical reasons; see ticket for details.
