### ISSUE TITLE
"!has" is missing in docs for expressions

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#6054]
`"!has"` is missing in the docs, currently only `"has" `is documented: 
https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-has

**Comment by anandthakker** [comment]
Thanks @pathmapper. It's a bit confusing, but `!has` is actually not an expression -- rather, it's part of the older [*Filter* syntax](https://www.mapbox.com/mapbox-gl-js/style-spec/#other-filter), which has now been superseded by expressions.  The equivalent using expressions is `["!", ["has", ...]]`

**Comment by pathmapper** [comment]
@anandthakker thanks for your explanation!
