### ISSUE TITLE
Remove `worker:source blob` CSP requirement (iframe sandbox `allow-same-origin` support)

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapbox-gl-js#6056]
# Issue:

Running Mapbox GL JS in a sandboxed iframe with only the `allow-scripts` permission blocks GL JS from running on IE11, Edge, and Safari browsers.

EX: 
`<iframe src="https://www.mapbox.com/bites/00384" sandbox="allow-scripts"></iframe>`

# Minimal test case:
https://bl.ocks.org/ryanbaumann/c28a57618ecd60d23f59d24d91d016fd

If the map in the example above does not load tiles in a browser, that means that the  **allow-same-origin** sandbox permissions are required for the browser iframe sandbox.  In IE11 and Edge, the example above does not load for me.  

The root cause of the map not loading in the minimal example above using sandboxed iframes on IE11 and Edge _seems_ to be due to fetching same-origin blob URL requests at web worker boot time:

Error messages loading the minimal example above:

**On Edge:**
![](https://cl.ly/2x361Z2Y0X47/download/Image%202018-01-25%20at%208.01.59%20AM.png)

**On IE11:**
![](https://cl.ly/2E3I0T1c291v/download/Image%202018-01-25%20at%208.06.51%20AM.png)

# Desired Solution 

If a new build of GL JS that eliminates the `worker:src blob` CSP, loading the test page above should work on IE11, Edge, and Safari.

See https://github.com/mapbox/mapbox-gl-js/issues/5939 for a potential solution.

**Comment by jfirebaugh** [comment]
Since this is so closely related to #6058, let's centralize discussion there.
