### ISSUE TITLE
Pausing with the mousedown while panning prevents any further panning (0.44.0)

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-js#6063]
Hi,

I'm noticing an issue after upgrading to 0.44.0. Took a while to work out what was going on but I believe it is the following:

v0.44.0

### Steps to Trigger Behavior

 1. Start panning around the map
 2. Stop/pause panning for a moment, but keep holding down the mouse button
 3. Move the mouse to start panning again

### Expected Behavior

Panning should continue after the pause if the user is still holding the mouse button down without having to let go.

### Actual Behavior

The map does not continue to pan (and appears frozen) until the user stops panning (let go of the mouse button) then starts again.

It can look like the map randomly freezes if the user happens to pause for a moment e.g. they pan left, pause, then pan right.

I've tested this in Chrome, Safari and Edge on a couple of computers. I was able to replicate using the mapbox examples.

Thanks,
Joe

**Comment by anandthakker** [comment]
Thanks for the report @joedjc!  Fix pending in #6068
