### ISSUE TITLE
Dragging ends before mouse button is released

### ISSUE THREAD

**Issue by ttsirkia** [mapbox/mapbox-gl-js#6072]
**mapbox-gl-js version**: 0.44

### Steps to Trigger Behavior

 1. Press mouse button
 2. Drag the map
 3. Stop dragging but keep the button pressed
 4. Drag more

### Expected Behavior

Map position moves always when dragged

### Actual Behavior

If there is a short pause in dragging, the map doesn't move anymore although mouse button is still pressed.

Try with this example: https://www.mapbox.com/mapbox-gl-js/example/simple-map/

**Comment by ttsirkia** [comment]
Caused by 0f4441bb7ca783657a49b8bbb7d134da4ee88406

**Comment by pathmapper** [comment]
Duplicate of https://github.com/mapbox/mapbox-gl-js/issues/6063, fix is already there https://github.com/mapbox/mapbox-gl-js/pull/6068 
but I wonder why it has been merged in `0.44` instead of `master` @anandthakker

**Comment by ttsirkia** [comment]
Closed as duplicate
