### ISSUE TITLE
Perform projections and unprojections with custom zoom

### ISSUE THREAD

**Issue by Syntaf** [mapbox/mapbox-gl-js#6077]
## Motivation

While working on http://www.slacklinegroups.com , I've run into an issue where the current implementations of  `unproject()` and `project()` are preventing me from calculating important offsets at a future zoom level before a `flyTo` is used.

Consider the following (simplified) scenario:
* You have a map filled with markers, starting at a zoom of **4**
* Clicking any marker flies to that location with a zoom of **7.7** and opens a popup filled with content
* You decide you want to actually fly **100px** below the marker everytime.
* Attempting to do this with `project()` and `unproject()` is currently impossible, as both functions only work with the *current* zoom level, which is **4**. 

The above can also be illustrated with code:

```javascript
map.on('click', 'my-marker-layer', function(e) {
    // grab the location of the marker, then project it to the coordinate space
    var coordinatesToFlyTo = e.features[0].geometry.coordinates;
    var coordsToPoint = map.project(coordinatesToFlyTo);

    // add 100px to it's y value
    coordsToPoint.y += 100;

    // unproject it back to LngLat, but wait... we just added 100px
    // at zoom level 4, not 7.7. Unfortunately, there's no way to
    // actually calculate where to fly to so we end up 100px below
    // the marker :(
    coordinatesToFlyTo = map.unproject(coordsToPoint);

    map.flyTo({
        center: coordinatesToFlyTo,
        zoom: 7.7
    });
});
```
 
## Design Alternatives

It would be nice to be able to perform a projection and unprojection with custom zoom levels. If we added this to the current implementation however, you could write code such as:

```javascript
var LatToPoint = map.project(cords, 4);
var PointToLat = map.unproject(cords, 7.7);
```

which doesn't make any logical sense and would produce strange results.

Another idea might be to create an entirely new method that performs both the projection and unprojection given a zoom, then executes a block of code in between to ensure a consistent zoom is kept between project/unproject e.g.

```javascript
var newLat = map.projectAndUnproject(cords, 7.7, function(point) {
    point.y += 100;
});
```

## Design

I think the latter idea mentioned in the section above would be the better solution of the two. By using a function to constrain the lifetime of the custom zoom, you can ensure you won't run into any errors where different zooms were specified.

### Mock-Up

The API of the function would be as follows:

```javascript
projectAndUnprojected(lnglat: LngLatLike, zoom: number, body: any)
```

### Concepts

N/A

### Implementation

The implementation of this would lie in `map.js`, and be a new method:

```javascript
    // map.js
    projectAndUnprojected(lnglat: LngLatLike, zoom: number, body: any)
    {
        const oldZoom = this.transform.zoom;

        this.transform.zoom = zoom;
        const projectedPoint = this.transform.locationPoint(LngLat.convert(lnglat));
        const newProjectedPoint = body.call(this, projectedPoint);
        const unprojectedPoint = this.transform.pointLocation(Point.convert(newProjectedPoint));
        
        this.transform.zoom = oldZoom;
        return unprojectedPoint;
    }
```

A C++ implementation would be needed as well, but I haven't yet looked into that.

**Comment by jfirebaugh** [comment]
Let's centralize discussion on #5687.

**Comment by Syntaf** [comment]
Sorry for the late response, been a bit busy, but your solution @mollymerp seems to be sufficient in this use case. Thanks!
