### ISSUE TITLE
Drag-to-pan unresponsive in 0.44.0

### ISSUE THREAD

**Issue by geirsagberg** [mapbox/mapbox-gl-js#6081]
**mapbox-gl-js version**: 0.44.0

### Steps to Trigger Behavior

 1. Press and hold left mouse button on map for a few secs
 2. Move mouse

OR

1. Start dragging to pan
2. Pause dragging for a few secs, but keep pressing left mouse button
3. Resume dragging

### Expected Behavior
Map pans

### Actual Behavior
Map does not pan

Can be tested in https://www.mapbox.com/mapbox-gl-js/example/simple-map/, which uses 0.44.0.

Tested locally, the problem does not exist in 0.43.0.

**Comment by geirsagberg** [comment]
The problem seems to be worse on high DPI screens; I notice it constantly on my Surface Book 2 with 3000 x 2000 resolution (225% scaling), much less frequently when I change to 1440x960 (100% scaling).

**Comment by geirsagberg** [comment]
Here is a gif showcasing the issue on the low DPI screen as well, though I had to work harder to provoke it:

![mapbox-2](https://user-images.githubusercontent.com/594564/35523808-03bb355c-0520-11e8-9289-0aff46ebebed.gif)

**Comment by geirsagberg** [comment]
See that the grabbing "slips" at times.

**Comment by ttsirkia** [comment]
Probably fixed by #6068. Similar tickets #6072 and #6063

**Comment by geirsagberg** [comment]
Agreed, looks like a duplicate of those two. So the fix will be in 0.45 @ttsirkia ?

**Comment by geirsagberg** [comment]
Or in 0.44.1?

**Comment by ttsirkia** [comment]
I don't know but it seems that the fix is merged to master.

**Comment by mollymerp** [comment]
It looks like this is a duplicate and should be fixed but #6068 or #6125 – 0.44.1 should be released early next week. Please reopen if the issue persists.
