### ISSUE TITLE
A vector tile source Rendering problem

### ISSUE THREAD

**Issue by yangyanan05521** [mapbox/mapbox-gl-js#6083]
Hi，I'm confused these problems so long and haven't found a solution，please help me ,thank you so much.
I render the map with a vector tile source, tiles source has MULTIPOLYGON and POLYGON pbf data.
But, different zoom would find these problems:
1.about 3 zoom:
![tim 20180126091213](https://user-images.githubusercontent.com/31086273/35615219-73960202-06ac-11e8-9de9-510f580afb74.png)
2.about 8 zoom:
![8_1](https://user-images.githubusercontent.com/31086273/35615354-d69f150a-06ac-11e8-848d-07d4d15f55b0.png)
![8_2](https://user-images.githubusercontent.com/31086273/35615498-41df995c-06ad-11e8-940b-6beca80657c4.png)
3.about 5 zoom
![5](https://user-images.githubusercontent.com/31086273/35615539-5ec1b24e-06ad-11e8-84a3-e344e4d42d02.png)

this is my code: 
1. map.addSource('ProvincialRegion', {
          "type": "vector",
          "tiles": [appConfig.developUrl+"automate/monitor/pbf/outline/{z}/{x}/{y}?convListId="+mapParam]
        })
2.var provinceFaillayer={
          "id": 'ProvincialRegion_0',
          "type": 'fill',
          "source" : "ProvincialRegion",
          "source-layer": 'outarea',
          "layout": {
            "visibility": "visible"
          },
          "paint": {
            "fill-color": "#ffae45",
            'fill-outline-color': '#ffffff'
           },
          "minzoom": 3,
          "maxZoom":8,
          "filter": ["==", "status", "0" ]
        };
3. map.addLayer(provinceFaillayer);

**Comment by lbud** [comment]
Hey @yangyanan05521, it's likely your vector tiles contain geometries that are not OGC simple and valid. The polygon triangulation library used in mapbox-gl-js does not handle degenerate cases (e.g. self-intersections, etc) and may cause rendering errors like those you're seeing. `node-mapnik` has helpful methods to report geometry [simplicity](http://mapnik.org/documentation/node-mapnik/3.6/#VectorTile.reportGeometrySimplicity) and [validity](http://mapnik.org/documentation/node-mapnik/3.6/#VectorTile.reportGeometryValidity). Please let us know if you're able to confirm that your tiles are OGC simple and valid and are still producing rendering errors.
