### ISSUE TITLE
layout visibility property gets removed when layer is visible

### ISSUE THREAD

**Issue by bloigge** [mapbox/mapbox-gl-js#6084]
Version: 0.44

### Expected Behavior
If a layer is visible on the map the visibility property in the layout object of the layer should be `'visible'`.

### Actual Behavior
Currently the `visibility` property is removed from the object if the layer is visible. Using the method `map.getLayoutProperty(layerId, 'visibility')` the visibility state is returned correct. But for example when accessing the whole styling via `map.getStyle()` the property isn't available anymore in all visible layers. I updated mapbox from 0.41 to 0.44. I am not sure when this changed. In the past I was able to see the visibility property in the layout object of a layer. When a layer is set back to invisible using `map.setLayoutProperty(layerId, 'visibility', 'none')` the property becomes available again --> `"visibility":"none"`.

**Comment by bloigge** [comment]
After re-reading the style spec I found out that the visibility property is optional. I guess some internal changes reset the properties and when accessing the style via `map.getStyle()` the style will be set to the minimum properties representing the current state. So there won't be any visibility property - because it's visible by default. Although in the past a property wasn't removed after it was set once.

**Comment by shawel** [comment]
Just a thought! this change can mess generic diff algorithms to set the layout property.
