### ISSUE TITLE
remote WMTS Layer for mapbox gl with different Tile-Resolution

### ISSUE THREAD

**Issue by 808730** [mapbox/mapbox-gl-js#6089]
Hello! 

I would like to implement a free WMTS Layer in mapbox gl (raster tile-source). Here an example:

https://jsbin.com/nozoval/1/edit?html,output

I get no error throwing in the console, but it seems the raster tiles are generated different on the server,
as i get "empty images" from the server and no raster tiles on the map! Example Response from server:

https://www.wmts.nrw.de/geobasis/wmts_nw_dop20/tiles/nw_dop20/EPSG_3857_16/9/267/167.jpeg

The generation of x and y resolutions on each zoom level seems to vary from the Mapbox GL JS TileSpecification which defines specific Tile-Boundaries on each zoom level 
(http://www.maptiler.org/google-maps-coordinates-tile-bounds-projection/).
 
Is there already an issue belonging to that problem, where a remote TileService uses a different TileGeneration with different resolutions on each zoom level? 

This WMTS is created with MapProxy! The ZoomLevels are generated by the parameter 'resolution' (for further information look into the metadata of the service: https://www.wmts.nrw.de/geobasis/wmts_nw_dop20/1.0.0/WMTSCapabilities.xml).

**mapbox-gl-js version**: v0.42.0

Thanks for Help,
Philipp

**Comment by 808730** [comment]
Here is a working example with this WMTS above in OpenLayers:
https://jsbin.com/jocobak/1/edit?html,console,output

See in the console for the tile-layer properties! 
Can anyone point out why mapbox can't handle this, but OL?

Thanks for your help! 
Philipp

**Comment by mollymerp** [comment]
@808730 thanks for using Mapbox. I'm afraid the tileset you're trying to use is not compatible with mapbox gl. Our raster source type currently only supports `xyz` and `tms` tiling schemes, and does not support `wmts`: https://www.mapbox.com/mapbox-gl-js/style-spec#sources-raster-scheme

I don't know a lot about WMTS but in the working example it is requesting tiles like 
`https://www.wmts.nrw.de/geobasis/wmts_nw_dop20/tiles/nw_dop20/EPSG_3857_16/03/132/86.jpeg` at zoom level 8 and that tile coordinate does not exist in the xyz or tms tilescheme.

**Comment by strech345** [comment]
hello @mollymerp ,
i think a wmts is a very useful and standard map service and it would be nice to use it on mapbox gl.

**Comment by ssingh13-rms** [comment]
is `wmts` officially supported now?
