### ISSUE TITLE
Overzoomed artifacts

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#6097]
**mapbox-gl-js version**:
0.44.0

### Steps to Trigger Behavior

I have a very dense parcel dataset. I use tippecanoe to generate mbtiles with z0-z13. When I overzoomed to z18, works fine. But to z19, I noticed this:

![image](https://user-images.githubusercontent.com/1522494/35795855-945f051e-0a95-11e8-96aa-36b2241222d5.png)

If you look carefully, there are also a very thin line inside the wired polygon.

When I zoom to z20:
![image](https://user-images.githubusercontent.com/1522494/35795954-e757080c-0a95-11e8-8a63-352460342f8b.png)

The wired polygon disappears, but the thin line still exists.

Util overzoomed to z22, The wired polygon and thin line all disappear.

![image](https://user-images.githubusercontent.com/1522494/35796041-24dd14fa-0a96-11e8-92e0-5e67061f320a.png)

Note that, I found many polygons like this. Some exists at z17 and disappear at z20, other exists at z20 and disappear z22. 

### Actual Behavior
![qq20180205-165202](https://user-images.githubusercontent.com/1522494/35795724-04711758-0a95-11e8-8a73-a3534b8e9cb0.gif)

**Comment by pathmapper** [comment]
@jingsam I wonder if the polygons you are seeing this issue are tiled so that a polygon is split in several parts and overzooming works then independently on these different parts.

To find out, could you make the tiles boundaries visible: `map.showTileBoundaries = true;` ?

**Comment by mourner** [comment]
What options did you use for Tippecanoe? By default, it simplifies polygons separately even if they share a portion of a border, so simplification can be different. There's [an option](https://github.com/mapbox/tippecanoe#attempts-to-improve-shared-polygon-boundaries) named `--detect-shared-borders` which tries to avoid these kinds of problems, although it's computationally pretty expensive. Try it out.

In any case, this is data processing issue, not GL JS one, so I'm closing here.

**Comment by jingsam** [comment]
I have tried various options with tippecanoe, including the `--detect-shared-borders` option. But this issue still exists. At first I guess it was a tippecanoe issue. However, I noticed that this issue only happens when tiles are overzoomed, for example, I generate tiles with z0-z13, but the artifacts appears at z19. So i assue it is a rendering issue.

**Comment by jingsam** [comment]
@pathmapper I confirmed that these artifacts do not appear on boundaries.
![qq20180205-174253](https://user-images.githubusercontent.com/1522494/35797882-1688030a-0a9c-11e8-9913-6ee00cf392b0.gif)

**Comment by jingsam** [comment]
I regenerate a mbtiles with z0-z16, and the artifacts do not show at z19, but appear at z22. It seems that when a tile overzoomed about 6 levels, this issue exists.

**Comment by jingsam** [comment]
Tried another datasets. Same issue. It appears that this issue is not related to data

**Comment by jfirebaugh** [comment]
@jingsam Can you put together a minimal self-contained demonstration?
