### ISSUE TITLE
change "drag a point" example to use Marker

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#6102]
Performance isn't great on https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/ and this is a pain point for users (https://github.com/mapbox/mapbox-gl-js/issues/2334#issuecomment-352612642). Using `Marker` would drastically simplify the code in the example and have better performance because we wouldn't be using `setData` to change the location.

**Comment by jfirebaugh** [comment]
Since this would require doing much of the work for #3087 (Add "draggable" property to "Marker" class), it's probably best just to do that. Then the example is a one-liner.

**Comment by jay-manday** [comment]
I'd love to take this on, I got really familiar with `Marker` while working on #6031 with @andrewharvey. 

I think we should expose a `drag` option that defaults to `false` for the marker object. This can reference an `onDrag()` method that can update the marker to new coordinates when the `click`  ends. 

This could make it really easy for people to use, if it works out I can totally write docs in a follow up PR with a simple example and explanation.

**Comment by jay-manday** [comment]
Hi I was looking into this a bit over the weekend and wanted to get feedback on two possible routes to take for adding dragging behaviors for marker points, I've looked into both routes but wanted to check in and get feedback on my approach.

### option 1: A dedicated `drag_marker` event handler
after looking into how the `drag_pan` handler was working to get more of a feel as to how events are treated, I thought it might be potentially advantageous to house this functionality in a dedicated `drag_marker` event handler file that hooks into the `marker` element, I tried this initially but got a bit stuck. I tried this first as opposed to the maybe simpler solution of just tacking this onto `marker` for a few reasons:
- keep main marker file lightweight as this is a particular, though popular use case.
- stay consistent with patterns used in other event handlers ie pan, rotate, zoom.

I did make some progress though still have to sort out a few more of the nuts and bolts, namely correctly hooking up the drag_marker handler to marker, this approach however might be unnecessarily complex. 

### option 2: Embedding this into Marker
This was the other route I started to explore after hitting a wall with option one. Didn't see any performance downsides with going this route but I liked the idea of splicing away the functionality into a separate file. However I'm realizing its simpler just to have this built into marker as to have the listeners set onto the same dom node that their originating from. I could be totally overthinking this as i'm still getting familiar with the architecture of the project and open source contributing in general but thought i'd mention my approach. 🌱n_n
