### ISSUE TITLE
Simultaneous map zoom and drag throws TypeError

### ISSUE THREAD

**Issue by dm261395** [mapbox/mapbox-gl-js#6106]
**mapbox-gl-js version**:
v0.44.0

### Steps to Trigger Behavior

 1. On the Mapbox GL JS simple map example at https://www.mapbox.com/mapbox-gl-js/example/simple-map/, start zooming in or out on the map via the mouse wheel scroll.
 2. Before finishing zooming, click and drag the map in some direction. 
 3. Type error is thrown (Chrome console output): 

> Uncaught TypeError: Cannot read property 'x' of undefined

GIF demonstration:
![bug](https://user-images.githubusercontent.com/34164181/35911484-d61969d8-0bf1-11e8-85cc-2433273a8209.gif)

I am on macOS High Sierra Version 10.13.3. I have encountered this error on Chrome Version 64.0.3282.140, Firefox Quantum v58.0 and Safari Version 11.0.3 since the mapbox-gl upgrade v0.44.0.

**Comment by mourner** [comment]
Fixed in #6113
