### ISSUE TITLE
Remove all labels from the map

### ISSUE THREAD

**Issue by haimyyy** [mapbox/mapbox-gl-js#6108]
It is possible to remove street and city labels from the map? 
Thanks!

**Comment by ttsirkia** [comment]
Remove the layer that adds the labels?

**Comment by haimyyy** [comment]
@ttsirkia All the labels are separate layer?
I want to use 3D Building option map without streets name or cities name...

**Comment by ttsirkia** [comment]
Yes they are. The actual layer names depend on the data source you are using. See for example: https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#road_label and https://www.mapbox.com/mapbox-gl-js/example/toggle-layers/

**Comment by lbud** [comment]
Thanks @ttsirkia! 

One more option if you _always_ want your basemap to have no labels is to create your own map, using a default map template as a starting point, in Mapbox Studio: see [here](https://www.mapbox.com/help/create-a-custom-style/) for a tutorial.

**Comment by haimyyy** [comment]
Thanks Both :)
