### ISSUE TITLE
showTileBoundaries debug increases z when overzoomed

### ISSUE THREAD

**Issue by Synesso** [mapbox/mapbox-gl-js#6111]
**mapbox-gl-js version**: 0.44.0

### Steps to Trigger Behavior

 1. Go to https://www.mapbox.com/maps/streets/ (this uses a much older version of the library, but I have recreated it locally with 0.44.0)
 2. Open console and enter `map.showTileBoundaries = true;` Tile boundaries should show.
 3. Double click to zoom onto tile `16/53556/28605` until zoom level 17.

### Expected Behavior

The tile debug should continue to show `16/53556/28605` 

### Actual Behavior

The tile debug shows `17/53556/28605`

**Comment by asheemmamoowala** [comment]
Duplicates #5535
