### ISSUE TITLE
Enum type missing from mapbox-gl-style-spec doc page

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#6116]
I expect to see the enum type in this list at https://www.mapbox.com/mapbox-gl-js/style-spec/#types, but it is not present.

![screen shot 2018-02-08 at 4 40 23 pm](https://user-images.githubusercontent.com/108094/36005935-f6f243c0-0cee-11e8-9b2a-1189aa4f3527.png)

In the spec, [properties like `text-transform`](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/reference/v8.json#L1679) use the enum type.

**Comment by jay-manday** [comment]
Hi @samanpwbb I can take care of this, I've been meaning to review the style specs as per #5438 and this is a good place to start!

**Comment by jfirebaugh** [comment]
These were intentionally removed; see #5577.
