### ISSUE TITLE
in mapbox-gl-style-spec, document # of values each expression takes

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#6117]
**mapbox-gl-js version**: .44

### Steps to Trigger Behavior

See https://github.com/mapbox/mapbox-gl-js/blob/b88ec9df343f31335ddbd7aaf17a65d97ebaadd8/src/style-spec/reference/v8.json#L2015

### Expected Behavior

It would be helpful if the spec reference JSON doc specified the # of arguments different expressions take. For example:
``` json

      "to-boolean": {
        "doc": "Converts the input value to a boolean. The result is `false` when then input is an empty string, 0, `false`, `null`, or `NaN`; otherwise it is `true`.",
        "group": "Types",
        "value-count": 1
      },
      "to-color": {
        "doc": "Converts the input value to a color. If multiple values are provided, each one is evaluated in order until the first successful conversion is obtained. If none of the inputs can be converted, the expression is an error.",
        "group": "Types",
        "value-count": "Unbounded"
   }, 
      "rgb": {
        "doc": "Creates a color value from red, green, and blue components, which must range between 0 and 255, and an alpha component of 1. If any component is out of range, the expression is an error.",
        "group": "Color",
        "value-count": 3
      },   
```

### Actual Behavior

There is no way to know from the spec how many arguments an expression takes.

---

I am not sure `value-count` is the right property name, or how to describe cases where the value count is unbounded – curious if anyone has insights there.

**Comment by samanpwbb** [comment]
Would be worth documenting argument type as well 🤔.

**Comment by anandthakker** [comment]
This is tricky.  Even leaving aside argument types and just considering argument count:
 - Some expressions have multiple signatures, e.g., `[get, feature_property]`, `[get, key, object]`.  That's not too bad: maybe `value-count: [1, 2]`.
 - Others are unbounded.  Also not too bad, `value-count: ["Infinity"]` or `value-count: [null]` or something like that.
 - But others, like `step`, `interpolate`, `case`, `match` are unbounded but still have specific constraints -- e.g., `[step, x, y0, x1, y1, ...]` must have an even number of arguments.

If we start considering types, too, then it gets quite a bit more complicated -- it would take a very sophisticated type language to fully express the signatures of every expression operator.

**Comment by davidtheclark** [comment]
Is it possible that a free text description of arguments could do the job here? That would provide full flexibility for the situations @anandthakker brings up; and I don't think a more structured, type-based approach would benefit Studio *more*, since we'd just have to translate the structured data into text.

**Comment by anandthakker** [comment]
@davidtheclark something sort of in between exists here: https://github.com/mapbox/mapbox-gl-js/blob/ea613ea61ff9c33a377dd92eaea08648ead370e5/docs/components/expression-metadata.js

I'm not sure whether or not we should add that to the style spec, but it's certainly a possibility.

**Comment by samanpwbb** [comment]
Ah, upon further reflection, I don't think we need to add this to the spec. Studio will maintain it's own type annotation info, which needs to be formatted in a specific way, and we'll write a test against the spec to ensure we're covering every expression. Thanks for chiming in here @anandthakker & @davidtheclark !
