### ISSUE TITLE
Wrong popup position when zoom out mapbox

### ISSUE THREAD

**Issue by thachnv** [mapbox/mapbox-gl-js#6118]
**mapbox-gl-js version**: 0.44.0

### Steps to Trigger Behavior

 1.  Go to https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/
 2. Zoom out all the way until can't zoom out any more. Now we can see 2 points that will popup when hover.
 3. Hover the left point, popup position is correct. Hover the right point, popup still pop on the left point

### Expected Behavior
- Popup on correct position
### Actual Behavior
- Hover to the right but popup pop on the left:
<img width="764" alt="untitled" src="https://user-images.githubusercontent.com/17398700/36010012-bc10c572-0d81-11e8-8759-add2e79a1871.png">

**Comment by andrewharvey** [comment]
related to #4577

**Comment by jfirebaugh** [comment]
I've added code to this example to show how to handle this case.
