### ISSUE TITLE
We need isZooming api

### ISSUE THREAD

**Issue by Jinkwon** [mapbox/mapbox-gl-js#6119]
**mapbox-gl-js version**: 0.44.0

### Steps to Trigger Behavior
- no Steps :)

Hello mapboxgl.
Thanks for your good library.
I know that mapbox has isMoving(), but no isZooming.
Is there any reason ?

**Comment by mollymerp** [comment]
wish granted ✨  #6128

**Comment by stegano** [comment]
+1

**Comment by stegano** [comment]
+1
