### ISSUE TITLE
Intersection polygon opacities geojson causes addition.

### ISSUE THREAD

**Issue by CraigglesO** [mapbox/mapbox-gl-js#6120]
https://imgur.com/a/d2doe

The left is what is happening and the right is what I want. I realize it's technically possible with geo-json but not supported yet?

I know with svg's it's easy, and while leaflet supports svg polygons mapbox-gl doesn't?

Can I get advice on what to do to produce the results I am looking for?

**Comment by lbud** [comment]
Correct @CraigglesO, Mapbox GL does not support SVG polygons. You'll need to process your data in a way that produces the combined polygon for rendering — check out Turf.js for simple in-browser geospatial operations. For this case you'll probably want [@turf/union](http://turfjs.org/docs#union).
