### ISSUE TITLE
Minimum size for boxzoom (suggestion)

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#6132]
In my map I have an interaction where shift-clicking does something. One issue is that if the mouse moves even slightly during the process of shift-clicking, it triggers a box-zoom, to a tiny box.

My suggestion: don't trigger a box-zoom if the box is less than X by X pixels, where X is something like 20.

There doesn't seem to be any way for me intercept the boxzoom handler and reject it, so my workaround for now is to disable boxzoom any time that the shift-click feature is available.

**Comment by jfirebaugh** [comment]
> intercept the boxzoom handler and reject it

Thinking about a potential way to do this in #3290.
