### ISSUE TITLE
map.boxZoom undocumented

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#6133]
There seems to be a property, `map.boxZoom` which is a [BoxZoomHandler](https://www.mapbox.com/mapbox-gl-js/api#boxzoomhandler), but this fact is not documented.

**Comment by mollymerp** [comment]
all the default interaction handlers are stored on the `Map` object (if they're not disabled in the `Map` constructor) and none of them are documented, but I'm not sure if there's a reason.

https://github.com/mapbox/mapbox-gl-js/blob/c0158855ddfa34f4706c5190e6d3da3972e1b901/src/ui/bind_handlers.js#L8-L30

**Comment by jfirebaugh** [comment]
There's no reason they shouldn't be documented, though we might want to unroll the `for (const name in handlers)`, making them simple static properties so each can be documented inline.

**Comment by jfirebaugh** [comment]
362a771371368a97a4f5d55536748598db13f219
