### ISSUE TITLE
Update ScaleControl unit of distance on the fly

### ISSUE THREAD

**Issue by ryanhamley** [mapbox/mapbox-gl-js#6137]
## Motivation

It should be possible to programatically change the ScaleControl's unit of distance and have the ScaleControl instantly update. This is helpful for applications that may need to show scale's in different units based on a site's location.

## Design Alternatives

You could remove the scale and add it back when you want to change the unit.

Alternatively, you could provide a method to update the scale's internal unit and update the scale.

## Design

Removing and re-adding the control is inefficient and can result in layout issues if multiple controls are in the same container. Updating the internal unit is fairly straightforward and only requires calling the existing `updateScale` method. I believe exposing this method is the proper way to achieve this goal.

### Mock-Up

N/A

### Concepts

N/A

### Implementation

Proposed [pull request here](https://github.com/mapbox/mapbox-gl-js/pull/6138)

**Comment by kriscarle** [comment]
In case it helps anyone, I've put together a custom scale control that shows metric and imperial at the same time, along with cursor coordinates https://github.com/maphubs/mapbox-gl-dual-scale-control

![image](https://user-images.githubusercontent.com/2431570/36232057-4e6517cc-11ae-11e8-9e55-58a2bd5b4513.png)

**Comment by jfirebaugh** [comment]
This was added in #6274.
