### ISSUE TITLE
Please help with creating polygons for each point on the map

### ISSUE THREAD

**Issue by Okami92** [mapbox/mapbox-gl-js#6142]
Hello. Sorry for noob question, but I've been trying to make it work for several days already, and haven't found suitable solution.

I have geojson file with following structure: 

```{
   "type": "FeatureCollection",
   "features": [
  {
    "type": "Feature",
    "geometry": {
       "type": "Point",
       "coordinates":  [ 6.773456,51.227741 ]
    },
    "properties": {
    "City":"Düsseldorf",
    "Inhabitants_27_05_1970":671999,
    "Inhabitants_25_05_1987":563531,
    "Inhabitants_09_05_2011":586291
    }
  },
  ...
```

And for each of this points I need polygon on the map, like this: http://prntscr.com/ie5lh8

Polygon from screenshot is made with the help of tutorial on mapbox website, but I can't find a way to implement it for my data collection, where I only have 2 coordinates and in my geojson file there is no data for this polygons.

Please help.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
