### ISSUE TITLE
Expressions equivalent for membership filter "in"

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#6144]
The following example is still using the membership filter `"in"`:
https://www.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/

`"in"` is documented as deprecated filter syntax: 
https://www.mapbox.com/mapbox-gl-js/style-spec#other-filter

I wonder if there is an expressions equivalent or a way to achieve the same result with the currently documented expressions.

If such a membership filter is possible with the currently existing expressions, an update of the example linked above would be much appreciated (if "in" is already also an expression, it is missing in the docs).

If there is currently no expressions equivalent: Will there be one in the future?

**Comment by anandthakker** [comment]
Thanks for reporting this @pathmapper.  The `match` expression provides an equivalent that's _almost_ as concise as `"in"`:

`["in", "key", a, b, c, ...]` from the old filter syntax would translate to `["match", ["get", "key"], [a, b, c, ...], true, false]`

**Comment by pathmapper** [comment]
Thanks for the fast response @anandthakker ! 
Updated the example in https://github.com/mapbox/mapbox-gl-js/pull/6148, hope this PR to `mb-pages` is the right way to do it, but I'm afraid I handled it incorrectly.

**Comment by jfirebaugh** [comment]
@pathmapper's contribution was merged in #6154. Thanks!
