### ISSUE TITLE
Tiny map shake while zooming in on raster tiles

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#6150]
In `v0.44` on the ["raster tile source" example](https://www.mapbox.com/mapbox-gl-js/example/map-tiles/), if you zoom in you can notice (at least on Mac Chrome/Firefox/Safari) a slight jitter back and forth:

![raster shake on zoom](https://user-images.githubusercontent.com/375121/36171774-bc357a72-10b8-11e8-84aa-16500d8b8be8.gif)

My initial guess is that this has something to do with the [recent change to align raster tile projection matrices to a pixel grid](https://github.com/mapbox/mapbox-gl-js/pull/6026).

/cc @anandthakker @kkaefer @mollymerp

**Comment by jfirebaugh** [comment]
See #6709 and https://github.com/mapbox/mapbox-gl-native/issues/11737 for similar reports.

@kkaefer What do you make of these issues? Is it possible to reconcile the simultaneous expectation of crisp raster imagery and zero "stutter" between a raster overlay and vector basemap?

**Comment by P-Zenker** [comment]
Any updates to this issue(s)?

**Comment by mourner** [comment]
@jfirebaugh maybe it should pixel-align when idle, and not align while animating?

**Comment by wboykinm** [comment]
@jfirebaugh I can confirm the effect is pretty crazy when slowly easing. Here's a raster tileset on top of a style that's meant to match, but you can see the foreground overlay dancing all over the base: 

![jitter](https://user-images.githubusercontent.com/735463/45955282-710aa200-bfdd-11e8-9ab9-753cd4584c7b.gif)

(Might be better-visible [in the example map itself](https://wboykinm.github.io/bird/) than in the above poor-framerate gif)
