### ISSUE TITLE
Update 3rd party vector tile source demo to a new data source

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#6151]
The [third party vector tile source example](http://localhost:8080/mapbox-gl-js/example/third-party/) relies on `tile.mapzen.com`. It seems to be working for now, but I believe we expect that to shut down before too long. :cry: We should find a different third party source for the demo.

**Comment by jfirebaugh** [comment]
Previously: #6051.

**Comment by ttsirkia** [comment]
How about https://www.tilehosting.com/ ?

**Comment by friedbunny** [comment]
Replaced in #6156.
