### ISSUE TITLE
Video example has silent audio track, won't play on mobile

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#6152]
The video used in the video debug page and the [video example](https://www.mapbox.com/mapbox-gl-js/example/video-on-a-map/) does not play on mobile due to mobile browser policies forbidding videos with audio tracks from autoplaying (https://webkit.org/blog/6784/new-video-policies-for-ios/). We'll need to strip the audio track from the video to get it to display correctly on mobile (even though it is silent it seems it contains an audio track).

**Comment by jfirebaugh** [comment]
@jacobsonjohnm 👋  Do you know of a tool that would allow us to easily strip the audio tracks from these two files:

* https://www.mapbox.com/drone/video/drone.mp4
* https://www.mapbox.com/drone/video/drone.webm

**Comment by jacobsonjohnm** [comment]
@jfirebaugh yes, I can do that in premiere, give me a few minutes and I will get it done for you.

Just to be certain, you just want the audio removed or separated?

**Comment by jfirebaugh** [comment]
Thanks! Yes, removed completely.

**Comment by jacobsonjohnm** [comment]
@jfirebaugh 
Here is the mP4 version: https://www.dropbox.com/s/p2klegse7nzm4rr/drone.mp4?dl=0

I will have to find a conversion to create the webm version.

**Comment by jfirebaugh** [comment]
Hmm, that version is 24.8 MB, while the original is 9.6 MB. It's important that this file remain bandwidth-efficient. Is there a way to strip the audio that keeps the file size roughly the same (ideally smaller)?

**Comment by jfirebaugh** [comment]
(Source of these files is https://github.com/mapbox/drone/tree/mb-pages/video, if that helps.)

**Comment by jacobsonjohnm** [comment]
Yes, I can export at a lower res. Give me about 45min to get back to my
desk.

**Comment by jacobsonjohnm** [comment]
Ok, the file is down to 7mb now. I can bring it down lower if need be, but will compromise quality a bit.

**Comment by jacobsonjohnm** [comment]
Same link: https://www.dropbox.com/s/p2klegse7nzm4rr/drone.mp4?dl=0

**Comment by jfirebaugh** [comment]
I updated the video asset that's used in this example, but it still doesn't work. I think iOS Safari has other compatibility issues that prevent this example from working. Not planning on further investigation.
