### ISSUE TITLE
Suggest Example Point Moving on Tablet / Ipad

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#6159]
Hello,

the example [https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/](https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/) for me is not working on ipad. It would be nice to know how to draw, move a geometry on tablet / ipad.

Best
Stephan

**Comment by jfirebaugh** [comment]
Duplicate of #3017.
