### ISSUE TITLE
Change the map container

### ISSUE THREAD

**Issue by felixerdy** [mapbox/mapbox-gl-js#6165]
## Motivation
I would like to update the map so that the instance runs in another div container

### Implementation
Something like `setContainer(string: container)`

**Comment by jfirebaugh** [comment]
Sorry, this isn't something we're likely to support; it would introduce substantial complexity to the codebase.

**Comment by tannerjt** [comment]
I would love to see something like this as well.  This is similar to Open Layers getTarget() and setTarget() - https://github.com/openlayers/openlayers/blob/v6.1.1/src/ol/PluggableMap.js#L1355

My primary reason for needing this capability is to teleport my map do a different container for making print images of varying sizes.

**Comment by AntonioRecaldeRusso** [comment]
You can to move the container itself to different parts of the dom tree

**Comment by lebaphi** [comment]
Hi @felixerdy, do you resolve this issue?
