### ISSUE TITLE
Provide turn-by-turn navigation in javascript SDK

### ISSUE THREAD

**Issue by troyibm** [mapbox/mapbox-gl-js#6168]
We have used mapbox navigation SDK for android and iOS for compelling demos, but are looking to provide this demonstration to a broader audience via a web app.  Unfortunately, it looks like the navigation and directions APIs aren't part of the mapbox javascript SDK.  Am I wrong?  If there isn't anything provided by the javascript SDK, do you think it is possible for us to use the current functionality to build this ourselves relatively easily?  Thanks.

**Comment by jfirebaugh** [comment]
> Unfortunately, it looks like the navigation and directions APIs aren't part of the mapbox javascript SDK.

We don't currently have navigation support, but directions is available ([plugin](https://www.mapbox.com/mapbox-gl-js/plugins/#mapbox-gl-directions), [example](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions)).

If you need more that what that provides, it may be possible to build the functionality you need yourself. Please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). (We try to keep this issue tracker focused on bugs and feature requests.) Thank you!
