### ISSUE TITLE
Info: how to speed up Animation in Angular Project

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#6176]
Hello,

i've a lot of performance issus when using mapbox gl in angular project. Zoom Animation or dragging some geometries on the map was really slow.
With this command it works like it should ;-)

```
this.zone.runOutsideAngular(() => {
  this.map = new this.mapbox.Map( ... );
})
```
I also do it for all events.

for more info have a look on this site
https://blog.thoughtram.io/angular/2017/02/21/using-zones-in-angular-for-better-performance.html

Hope that helps someone

**Comment by jfirebaugh** [comment]
Thanks for the tip @strech345. This could help someone who comes here searching for information about Angular performance issues.

Closing here since this isn't an issue or feature request.
