### ISSUE TITLE
Enhancement - Allow map.addImage to specify a set of icons as in a spritesheet

### ISSUE THREAD

**Issue by Codain** [mapbox/mapbox-gl-js#6177]
My proposal is to allow the `Map.addImage` function to accept a JSON object which defines all icons embedded in the image (as with a regular spritesheet).

This way one would do one `Map.loadImage` to load a custom spritesheet and then do one `Map.addImage`to add a whole set of new icons (instead of having to load plenty of icons).

-----
**Rational**

I have a map which uses a Mapbox Studio style with it's default spritesheet. Fine.

But I have another layer with custom features and a need for dynamic icons (icons are defined depending of feature attributes, among which we have the color). I've only few options to style icons on those layers:

1. Modify the style spritesheet in Mapbox Studio to embed any type of icons. I want to avoid that since it would be a dummy task to reproduce regularly. Moreover there is plenty of limitations in the SVG support which makes icon editing not easy.
2. Have a lot of `Map.loadImage` and `Map.addImage` (one per icon). I find this mechanism a performance-killer and dirty code. As a performance-looker I'm not proud of this solution.
3. Use markers (i.e. html codes on top of the map, with CSS spritesheet mechanism) but with this solution I've to break styling between different layers.
4. Investigate SDF? Few documentation, no example, a risk to drop the feature according to other issues... I want to avoid this solution
4. Propose a new system, which i'm doing here.

**Comment by jfirebaugh** [comment]
Thanks for the suggestion @Codain!

Using multiple `Map.addImage` calls is the way to go here; we're not likely to extend `Map.addImage` to support multiple images, and even if we did, it wouldn't be more efficient than simply calling `Map.addImage` in a loop.

Note that you don't necessarily have to use `Map.loadImage` to load each image individually: you could create your own spritesheet or other format that packages multiple icons in one request, unpack that in application code, and then loop over the images, calling `Map.addImage` for each one.

**Comment by Codain** [comment]
@jfirebaugh Thanks for the feedback. I use a loading loop and a generated JSON configuration file (as you suggest, it's my option 2) but I still think it would be nice, once an image has been loaded, to be able to send a set of {X, Y, W, H} instead of a single icon name to `Map.addImage`. It would reduce my server bandwidth and loading time, which also means performance even if it's not on your side. Mapgl already handles spritesheets and image loading, it's sad it can't use both at the same time ;) . Anyway, I will have to live with Option 2 I fear...
