### ISSUE TITLE
Remove mention of string token syntax from docs

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#6185]
**mapbox-gl-js version**: 0.44.0

I recommend taking more aggressive steps to deprecate the token-based lookup syntax used in `icon-image` and `text-field` now that expressions exist. One simple step would be to omit mention of token lookups in the spec `doc` field (See https://github.com/mapbox/mapbox-gl-js/blob/38c7250da7b5153c531d0b5b8ff4a2f07f9ab863/src/style-spec/reference/v8.json#L1368 and https://github.com/mapbox/mapbox-gl-js/blob/38c7250da7b5153c531d0b5b8ff4a2f07f9ab863/src/style-spec/reference/v8.json#L1085. 

With the introduction of expressions, Studio will be converting all token lookups to `get` expressions. We're doing this to reduce the number of different ways a user can do the same thing and to eliminate the confusion that would occur if user attempted to perform a token lookup inside a zoom or decision expression. Studio will also surface docs for expressions – so we don't want the docs to be a source of confusion either.

**Comment by jfirebaugh** [comment]
I agree we should do this. Do we need to wait for expression to be available on native before doing so though? cc @mapbox/mobile

**Comment by 1ec5** [comment]
The API reference for [iOS map SDK v3.7._x_](https://www.mapbox.com/ios-sdk/api/3.7.4/Classes/MGLSymbolStyleLayer.html#/c:objc%28cs%29MGLSymbolStyleLayer%28py%29text) and [macOS map SDK v0.6._x_](http://mapbox.github.io/mapbox-gl-native/macos/0.6.1/Classes/MGLSymbolStyleLayer.html#/c:objc%28cs%29MGLSymbolStyleLayer%28py%29text) will continue to mention `{token}` syntax, so no problem for either of those SDKs. (They link out to the style specification reference, but only in passing.)

The [Android map SDK documentation site](https://www.mapbox.com/android-docs/map-sdk/) is already pointing to the v6.0.0-beta.2 API reference, so perhaps it isn’t a problem there either?

**Comment by zugaldia** [comment]
> The Android map SDK documentation site is already pointing to the v6.0.0-beta.2 API reference, so perhaps it isn’t a problem there either?

I'm afraid that's a bug (https://github.com/mapbox/android-docs/pull/312).
