### ISSUE TITLE
GL JS v44 - with a symbol layer, no event is fired when mousing over features

### ISSUE THREAD

**Issue by ksummerill** [mapbox/mapbox-gl-js#6189]
**mapbox-gl-js version**: v0.44.0

### Steps to Trigger Behavior

1. Use setFilter() function and mouseenter event to create hover effect (black border triangle to solid black triangle)
2. mouse over icons that are added to map as a symbol layer 
3. Observe that event is not fired when using GL JS 44

### Expected Behavior
Events are fired when you mouse over them (as in v39)
![gljs39_feb](https://user-images.githubusercontent.com/26940739/36335904-4e62612c-1338-11e8-9772-78402d17275a.gif)

### Actual Behavior
Events are not fired (as in v44)
![gljs44_feb](https://user-images.githubusercontent.com/26940739/36335896-45b8836c-1338-11e8-977c-ec7184d5ab7d.gif)

**Comment by jfirebaugh** [comment]
Sounds like #6074. Can you check if 0.44.1 resolves the issue?

**Comment by aag6z** [comment]
@jfirebaugh Just tested with 0.44.1. Events now fire but the icon still does not change on mouseenter

![hmta2i7req](https://user-images.githubusercontent.com/8423627/36337113-79e01824-135d-11e8-98eb-9206746c7318.gif)

**Comment by mollymerp** [comment]
@aag6z per chat, the issue you're running into there is the label collision algorithm preventing the "hover" layer from placing the feature on top of the original layer.
