### ISSUE TITLE
Add possibility to serve tiles over http2 to improve loading time

### ISSUE THREAD

**Issue by stalniy** [mapbox/mapbox-gl-js#6201]
First of all, I really like what you guys do! Thank you for your work!

**mapbox-gl-js version**: 0.44.1

### Steps to Trigger Behavior

 1. Open any map
 2. Check network tab in chrome dev tools (or similar)
 3. Add `Protocol` column
 4. Scroll map to non-visited area
 5. See the protocol for protobuf requests (HTTP 1.1) 

### Expected Behavior

It would be good to have an option to serve protobuf tiles over HTTP2 and get benefits from multiplexing.

### Actual Behavior
Tiles served over HTTP 1.1

**Comment by kubino** [comment]
+1

**Comment by bschimpf** [comment]
this seems like it might be as simple as enabling this in your cloudfront configuration: https://aws.amazon.com/about-aws/whats-new/2016/09/amazon-cloudfront-now-supports-http2/

Possible to look at this? I don't think it's feature work, probably as simple as a single configuration change in AWS.

**Comment by dshakya** [comment]
I am using Leaflet to call Mapbox maps and see this as well. Would be great if the maps were served using HTTP/2 protocol.

**Comment by dagjomar** [comment]
+1

**Comment by dbauszus-glx** [comment]
I using Leaflet and request raster tiles from Mapbox. The requests have a http 1.1 header it seems.

**Comment by mollymerp** [comment]
Our server-side teams have this improvement on their radar, but we don't have a timeline for when it will be completed at this time.

**Comment by WingGithub** [comment]
+1

**Comment by peleccom** [comment]
+1

**Comment by bramjoosten** [comment]
I'm a bit surprises this isn't implemented yet. Any news on the progress?

**Comment by skhaz** [comment]
This would be nice.

**Comment by MehdiSv** [comment]
Any news on this? It would be great!

**Comment by eklauberg** [comment]
+1

**Comment by asheemmamoowala** [comment]
This issue tracker is for reporting bugs and feature requests to the mapbox-gl-js library. Switching to HTTP/2 does not require any code changes to this library and is handled entirely by the browser. For those using GL-JS with their own servers, this should be possible already.

It is on our teams roadmap to investigate changes to GL-JS that make better use of HTTP/2 connections, but none of that work is planned yet

Please [contact support](https://www.mapbox.com/contact/) to learn more or to provide more context on your needs for HTTP/2 support.

**Comment by WingGithub** [comment]
For those who are interested, I contacted support. I'm not sure which issue they will be updating on github if not this. Here is the reply:

Hey there, 
The switch to HTTP/2 poses some challenges for Mapbox's infrastructure and we are undergoing tests and working with our customers to ensure that there are no disruptions to existing deployments when the switch may be made. For now, we will keep customers notified via the GitHub repository.

Rafa Gutierrez
Mapbox Support

**Comment by mo-ian-watkins** [comment]
Can I ask again where this request has got to please? The user experience of our applications could be greatly enhanced if the tiles could be served via http2.

**Comment by KonradKlimczak** [comment]
any update on it? is it ever going to change?

**Comment by joaobarcia** [comment]
Same here, Google Lighthouse identifies mapbox using http1 as the biggest possible speed improvement on our website. Are there any plans to improve on this?
