### ISSUE TITLE
Fade effect when add/move symbol layer

### ISSUE THREAD

**Issue by thekip** [mapbox/mapbox-gl-js#6202]
We are integrating mabpox-gl-draw library, and want to put on map points with icon styling (using style option).
We found that between **0.43.0** and **0.44.0** was made breaking changes which are not listed in changelog. 

In **0.44.0** icon put on map blinks with fade effect whenever draw library repaint it (when activate/deactivate, move, etc)

![point-blinks-aquarium](https://user-images.githubusercontent.com/1586852/36467875-1419747c-16e1-11e8-9f7d-df218b82aa4c.gif)

In **0.43.0** it works without such behavior. 

![point-blinks-aquarium-43](https://user-images.githubusercontent.com/1586852/36468087-3d95db1e-16e2-11e8-9ec1-4cc9e7d7d783.gif)

I prepared stackblitz example where you can try it with **0.44.0** version: 

https://stackblitz.com/edit/mapbox-drawer-44?file=index.js

Or with **0.43.0** version:

https://stackblitz.com/edit/mapbox-drawer-43?file=index.js

### Steps to Reproduce: 
1. Select on right tool bar "marker tool"
2. Put marker on map
3. Move marker, or activate/deactivate (by clicking on marker, then on map)

**Comment by jfirebaugh** [comment]
cc @ChrisLoer @ansis

**Comment by ansis** [comment]
## The workaround
add `'icon-allow-overlap': true` to the layer's style.

```
layout: {
        'icon-size': 2,
        'icon-image': 'aquarium-11',
        'icon-allow-overlap': true
      },
```

## The bug
With 0.44 we started not forcing full collision calculations whenever new tiles are loaded. Instead, we possibly use the old stale collision data for a few frame. Not forcing a full placement is good for performance reasons. In order for this approach to work we need to successfully match features in the new tiles with the features used for the old collision calculations.

We don't have any way of doing this right now. The current matching is based on text and *location*. If the location too much, the match fails and the feature is hidden until the next full collision calculations are done.

## Possible fixes

### A) Go back to forcing full calculations on tile load

Doing full calculations whenever a new tile is loaded would avoid the need for matching but it would also result in more dropped frames.

### B) Provide a way of specifying how to match features
One way to do this would be to have a `keyFn` argument for `setData`, similar to d3:
```
.setData(data, function(d, index) {
    return d.id;
})
```
Alternatively this could be a style spec property set on the source.

**Comment by ttsirkia** [comment]
This is related to https://github.com/mapbox/mapbox-gl-js/issues/6052

**Comment by ansis** [comment]
Thanks @ttsirkia, I had forgotten about that issue.

@thekip I'll close this issue in favour of #6052
