### ISSUE TITLE
'Error: Error' message too generic to debug

### ISSUE THREAD

**Issue by HeercoGrond** [mapbox/mapbox-gl-js#6204]
**mapbox-gl-js version**:  npm shows ^0.43.0

I'm trying to debug the loading of tiles from local device. Map is initialised as follows:

```
 this.map = new mapboxgl.Map({
        container: 'map', // container id
        style: mapboxStyle,
        center: [this.route.points[0].coordinate.lng, this.route.points[0].coordinate.lat],
        zoom: 18, // starting zoom
        dragRotate: false, // disable rotation
        transformRequest: (url, resourceType) => { 
                    console.log(url, resourceType);

            return {
             url: url,
             headers: { 'Access-Control-Allow-Origin' : '*'}
            }
     }
});
```

in mapboxStyle the tilesurl is changed to read something like this: `file:///storage/emulated/0/Android/data/com.someCompany.someApp/files/active/tiles/{z}-{x}-{y}.vector.pbf`

![image](https://user-images.githubusercontent.com/21168987/36477433-6f340320-1701-11e8-8236-5f6f3d35dd50.png)

Unfortunately, all I get is the generic `Error: Error` message when listening for error calls and printing the error using console.log(e.error). I can't seem to find anywhere why this is and I think this might be an error in mapbox itself. The files exist and loading them works with a regular ajax request, just not using Mapbox.

Tested on Android 7.0 and Android 4.4 with Xwalk and regular webview

**Comment by jfirebaugh** [comment]
This was fixed in #6126 and will be in the next release.
