### ISSUE TITLE
Style.load event missing from docs

### ISSUE THREAD

**Issue by yuletide** [mapbox/mapbox-gl-js#6210]
`Style.load` event is missing from the docs. The closest I could find is [styledata](https://www.mapbox.com/mapbox-gl-js/api/#map.event:styledata). 

https://jsfiddle.net/01b97w0L/

**Comment by mollymerp** [comment]
`style.load` is not part of the public API (see https://github.com/mapbox/mapbox-gl-js/issues/3970#issuecomment-275722197) – you can listen for `styledata` events and check `map.isStyleLoaded()` to see if the style has loaded.
