### ISSUE TITLE
Color pointer doesn't move when trying to change color.

### ISSUE THREAD

**Issue by thenerdyouknow** [mapbox/mapbox-gl-js#6213]
When trying to change the color of any values on a basic map on Mapbox Studio, the pointer doesn't move at all and stays at the value it originally held. On opening Console in Chrome, there were Uncaught TypeError: Cannot read property '0' of undefined errors that prevented me from dragging the pointer. But while the console is open, the pointer can be dragged around and the color can be changed. 
I'm using a ThinkPad T510, with a Google Chrome of version 63.0.3239.132(64 bit). 
Attached is a screenshot of the errors in the console.

![image](https://user-images.githubusercontent.com/16417887/36542282-69ea0d46-1806-11e8-8765-fc98099261a2.png)

**Comment by jfirebaugh** [comment]
Thanks for the report. I've forwarded this to the Mapbox Studio team to take a look. Closing here since it is not a mapbox-gl-js issue.
