### ISSUE TITLE
text-field don't show in smaller zoom

### ISSUE THREAD

**Issue by yangyanan05521** [mapbox/mapbox-gl-js#6219]
Hi~I use a symbol layer for showing text , I want the Map maxZoom is 7 , but in this maxZoom don't show  individual text and I try to set the Map(maxZoom : 8 ) , text will show entirely.

Thanks a lot!!!

### Expected Behavior
the Map(maxZoom : 8 ) , text will show entirely.
![relate](https://user-images.githubusercontent.com/31086273/36580577-c81a2e80-18a3-11e8-9782-8cac8f406a3a.png)

### Actual Behavior
the Map(maxZoom : 7) , show  individual text
![problem](https://user-images.githubusercontent.com/31086273/36580567-b923d6e2-18a3-11e8-9443-85371455c1ba.png)

### this is my code:

 1.   new mapboxgl.Map :
       new mapboxgl.Map({
            container: 'map',
            style: maplayer.simple,
            zoom: 4,
            center: [107.02932, 37.68486],
            minZoom:4,
            maxZoom:7
          })
 2.   add source :
       map.addSource('mapMeshcenter', {
          "tiles": [
            appConfig.developUrl+"amc/monitor/pbf/meshpoint/{z}/{x}/{y}"
          ],
          "type": "vector"
        })
 3.  symbol layer :
    var meshLayer_centername = {
          id: 'mapblock_layer2',
          type: 'symbol',
          "minzoom": 7,
          interactive: true,
          "source" : "mapMeshcenter",
          'source-layer': 'meshpoi',
          layout:{
            "text-field": "{meshId}",
            'text-size':10,
            "text-justify": "center",
            "visibility": "none",
            "icon-text-fit": "both",
            "text-allow-overlap":true,
            "text-padding":0
          },
          paint: {
            "text-color": "#ffffff"
          }
        }
4.  map.addLayer(meshLayer_centername);

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?

**Comment by ansarikhurshid786** [comment]
I am looking for the same.
