### ISSUE TITLE
fix fill-image alignment

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#622]
from https://github.com/mapbox/mapbox-gl-style-spec/issues/133

@ajashton 

> This is a 18x18px pattern (so, 16x16px without the edge pixels) so it should tile perfectly into 512px.

![](http://i.imgur.com/Tizc6II.png)

**Comment by jfirebaugh** [comment]
@kkaefer Is this the fix mentioned in https://github.com/mapbox/mapbox-gl-js/pull/851#issuecomment-66762860?

**Comment by kkaefer** [comment]
I don't understand the original ticket.

**Comment by jfirebaugh** [comment]
I have a strong hunch that this is fixed by #851. Closing.
