### ISSUE TITLE
Dynamic terrain not all created equally?

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-gl-js#6220]
Do the National sources of the terrain RGB-encoded dem source differ in quality/resolution?

This is the US/Canada border at 48.995N / -113.862 W at zoom 13:

![dynamic terrain on us canada border](https://user-images.githubusercontent.com/912721/36601855-1fe45af0-18ae-11e8-905e-b59341982f6f.jpg)

**Comment by mollymerp** [comment]
@ashleyclough yes, the `terrain-rgb` data comes from many different open data sources, and the quality at higher zoom levels varies quite a bit, in some cases by country/region.

**Comment by jczaplew** [comment]
@mollymerp is there a citation for all the elevation data sources somewhere?
