### ISSUE TITLE
error keeps logged while zooming

### ISSUE THREAD

**Issue by mapsgeek** [mapbox/mapbox-gl-js#6221]
**mapbox-gl-js version**:
0.44.1
### Steps to Trigger Behavior

 1. zoom in and out while having a vector source and layer added to the map

### Expected Behavior
 no errors to be logged into the console while zooming in and out
### Actual Behavior
error  
`evented.js:109 Error: Error
    at Actor.receive (VM1271 mapbox-gl.js:501)`

**Comment by jfirebaugh** [comment]
Fixed in #6126.
