### ISSUE TITLE
remove anonymous gist dependency from benchmarks 

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#6224]
per https://github.com/blog/2503-deprecation-notice-removing-anonymous-gist-creation

![image](https://user-images.githubusercontent.com/2425307/36615378-d845a4a6-1894-11e8-9d18-f05cf71afd97.png)

**Comment by jfirebaugh** [comment]
Alternatives:

* Create an oauth'd GitHub app that can gist on behalf of the user (cons: oauth is a pain, this will pollute folks' gist collections)
* Upload directly to S3 bucket (cons: requires access to AWS credentials)
* Find some other anonymous hosting service

**Comment by anandthakker** [comment]
Darn, just tried to fix this by generating a data URI that could be pasted into a PR, but GH markdown sanitizes that away (which makes sense)

**Comment by mourner** [comment]
There are no viable and easy alternatives, so we'll remove the share button for now -> #8066
