### ISSUE TITLE
querysourceFeature with 3rd party vector tiles

### ISSUE THREAD

**Issue by mapsgeek** [mapbox/mapbox-gl-js#6226]
**mapbox-gl-js version**:
0.44.1
### Steps to Trigger Behavior
it's more like a straightforward question than an issue, does querysourcefeatures works with 3rd party hosted vector tiles same as it do with mapbox's hosted sources?

i have an mbtiles file built with tippecanoe from a geojson source and i'm serving it using nodejs server.
i can render the source and the layers from it so fine but the querysourceFeatures return only 3 features
while it does one i change the source to mapbox hosted version it returns the whole data with hunderds of features.

`  this.map.addSource("newyork", {
          "type": "vector",
          "tiles": [
            "http://localhost:3000/nycs/{z}/{x}/{y}.pbf"
          ]
        });

        this.map.addLayer({
          "id": "new",
          "type": "circle",
          "source": "newyork",
          "source-layer": "nycgeojson",
          "paint": {
            "circle-color": "rgba(210, 8, 8, 1)"
          }
        }); // Place polygon under these labels.

      });

      this.map.on('load', () => {

        let features = this.map.querySourceFeatures('newyork', {
          sourceLayer: 'nycgeojson'
        });

        this.features = features;
        console.log(this.features)
      })`
### Expected Behavior
this.features contains hundreds of features 

### Actual Behavior
only 3 features returns

**Comment by stevage** [comment]
>i have an mbtiles file built with tippecanoe from a geojson source and i'm serving it using nodejs server.

You may need to be more specific about this, and particularly whether you're using a TileJSON endpoint or not.

**Comment by mapsgeek** [comment]
i'm adding an z,x,y protobuf extension vector source
"http://localhost:3000/nycs/{z}/{x}/{y}.pbf"

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?
