### ISSUE TITLE
URL put into tiles not calling to localhost because of CORS Error?

### ISSUE THREAD

**Issue by HeercoGrond** [mapbox/mapbox-gl-js#6230]
**mapbox-gl-js version**: mapbox-gl.js v0.44.1

### Steps to Trigger Behavior

 1. Run a HTTP server on an android device serving files and tiles.
 2. Inside of the style, use a http://localhost:8080/get-tile/{z}/{x}/{y} request to the android HTTP server (with or without file extension)

### Expected Behavior

Localhost get is called and the file / data is retrieved.

### Actual Behavior

CORS Error without even calling to the server (call is not logged on Android Console);

#### My process

I've been running into this issue for a while now, but I don't seem to be making any progress. To display it more simply: Using axios to make the request to the same resource
```
        axios.get("http://localhost:8080/get-tile/14/8474/5350.vector.pbf").then(response => { 
            console.log("received response");
            console.log(response);
            console.log(JSON.stringify(response.data));
        }).catch(rejection => { 
            console.log("rejected request..");
            console.log(rejection.status);
        });
```

And corresponding logcat: 
![image](https://user-images.githubusercontent.com/21168987/36679445-81659304-1b13-11e8-8f54-8b2a6085a053.png)

Now, when using the same construction on the url: 
![image](https://user-images.githubusercontent.com/21168987/36679617-eee0ca02-1b13-11e8-8b72-e1c9c740ceee.png)

I have enabled CORS headers on the server, but it's not even initiating the call from Mapbox GL JS side, in which I have already attempted to activate the Access-Control-Allow-Origin: * construction.

**Comment by jfirebaugh** [comment]
Sorry that we can't help further, but this is going to be an issue somewhere in your implementation, not in Mapbox GL JS. Mapbox GL JS makes requests, and does require an `Access-Control-Allow-Origin` header on the response.

**Comment by HeercoGrond** [comment]
You are correct; there was a stray resource loader in the project. Apologies.
