### ISSUE TITLE
Infer type assertions for `object`

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#6235]
From https://github.com/mapbox/mapbox-gl-js/issues/2434#issuecomment-367594239:

```js
[
  "get", "b",
  ["get", "a"]
]
```

fails to typecheck with `[2]: Expected object but found value instead.`.  We should be able to infer the `["object", ...]` wrapper needed here.

**Comment by jfirebaugh** [comment]
I though for a minute we didn't even have `["object", ...]` yet... but it's just missing from the docs.
