### ISSUE TITLE
potential performance issue: animated canvas layer drains CPU

### ISSUE THREAD

**Issue by jliebrand** [mapbox/mapbox-gl-js#6239]
I'm trying to debug a potential performance issue, and I noticed that the animated canvas source is draining a lot of CPU, even if there is no drawing going on.

Here's a reduced example:
https://codepen.io/anon/pen/QQJQLV?editors=0010

The example adds a canvas, which doesn't have any drawing code. Using the chrome task manager, the codepen tab is drawing about 90% cpu ?

<img width="612" alt="screen shot 2018-02-27 at 09 37 04" src="https://user-images.githubusercontent.com/23407884/36721206-22d7bfda-1ba2-11e8-9a19-da5123291833.png">

(using mapbox v0.44.1)

**Comment by jfirebaugh** [comment]
The canvas source by default assumes an animated canvas which needs to be repainted every frame. If your source is static, set the [`animate`](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-canvas-animate) option to true when creating the source, or call [`pause`](https://www.mapbox.com/mapbox-gl-js/api/#canvassource#pause) afterwards.
