### ISSUE TITLE
creating maps with multipolygons not working using mapbox api call

### ISSUE THREAD

**Issue by prosperva** [mapbox/mapbox-gl-js#6241]
I am tring to use MapBox to draw maps which have multi polygons (e.g USA, RUSSIA, etc).

In the case of USA, I have about 49 encoded polylines generated and 52 for Russia. The USA having Alaska completely separated from the bigger map. Simple polygons will only have one encoded polyline (e.g. Rwanda, etc).

MapBox provides this API call:

    https://api.mapbox.com/styles/v1/mapbox/streets-v10/static/path-5+f44-0.5(`ENCODED POLYLINE`)/auto/1000x1000?access_token= 

where `ENCODED POLYLINE` equals to the encoded polyline

I have tried adding multiple polylines separated by comas as follows:

    https://api.mapbox.com/styles/v1/mapbox/streets-v10/static/path-5+f44-0.5(`ENCODED POLYLINE`,`ENCODED POLYLINE`,`ENCODED POLYLINE`)/auto/1000x1000?access_token= 

and tried this:

    https://api.mapbox.com/styles/v1/mapbox/streets-v10/static/path-5+f44-0.5(`ENCODED POLYLINE`),(`ENCODED POLYLINE`)/auto/1000x1000?access_token= 

But none of the above seem to work.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. This issue tracker is for reporting bugs and feature requests in Mapbox GL JS, the Javascript library. This question isn't related to Mapbox GL JS, so please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). Thank you!
