### ISSUE TITLE
Get filtered features

### ISSUE THREAD

**Issue by PetrKaleta** [mapbox/mapbox-gl-js#6251]
I am using `mapbox-gl-js v0.44.1`.  Please have a look on the following example:

```javascript
map.addSource('foo', {
  'type': 'vector',
  'url': 'mapbox://...'
});

map.addLayer({
  'id': 'foo',
  'source': 'foo',
  'source-layer': 'acreage',
  'type': 'fill'
  ...
});
```

And I am filtering this source using `map.setFilter('foo', [...])`. How can I fit bounds to all filtered features?

I thought I can use `map.querySourceFeatures('foo', {'sourceLayer': 'acreage', filter: map.getFilter('foo')})` but this seems to be a wrong way, because I am getting very strange bounding boxes.

Any idea?

**Comment by jfirebaugh** [comment]
If by "all filtered features" you mean features in the source that both intersect the current viewport and match the filter, the approach you suggest sounds good to me. If that doesn't seem to be working, please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the "strange bounding boxes" issue.

If you need to fit a bounding box which includes features that aren't necessarily in the loaded set of vector tiles, then you'll need to compute and communicate that bounding box by some other means. Per the [documentation for `querySourceFeatures`](https://www.mapbox.com/mapbox-gl-js/api/#map#querysourcefeatures):

> The domain of the query includes all currently-loaded vector tiles and GeoJSON source tiles: this function does not check tiles outside the currently visible viewport.

**Comment by PetrKaleta** [comment]
Ah, this seems to be a problem, I don't wanna intersect it with a current viewport. Because imagine you have for example 5 polygons visible. So you filter just on of them and fit bounds to it. That works perfecly, but then if you filter to another one and want to get it, then it seems to be a problem, because it is not in your viewport (because in your viewport is that previously filtered one)...

Do you get my point?

**Comment by jfirebaugh** [comment]
Yes, I understand. Unfortunately, that's out of the scope of what `querySourceFeatures` (and by extension, Mapbox GL JS) can support. It's primarily a map renderer, and not intended to be a general-purpose vector tile query mechanism. The best I can suggest is that if the dataset isn't changing too often, you might be able to compute the bounding box server side and send it with the page or in some auxiliary request.

**Comment by arethasamuel** [comment]
Hi How do you implement what you said? "The best I can suggest is that if the dataset isn't changing too often, you might be able to compute the bounding box server side and send it with the page or in some auxiliary request."

How do you search for features using filter on a tileset?
