### ISSUE TITLE
"invert" layer selection

### ISSUE THREAD

**Issue by theochampion** [mapbox/mapbox-gl-js#6257]
In my map, I have a layer with a mvt source and I wondered If this is currently possible to "invert" layer selection.

For example is the following map, what is currently red would become transparent and vice versa.
<img width="657" alt="screen shot 2018-03-01 at 12 08 57" src="https://user-images.githubusercontent.com/14275989/36841750-a3dd9142-1d49-11e8-9926-d56ccc24ab92.png">

Is this possible to do this without modifying the vector tile source ? Or is there a way to "substract" a layer from another to achieve the same effect ?

**Comment by jfirebaugh** [comment]
No, you'll need to modify the source to accomplish this. See #993 for past discussion.
