### ISSUE TITLE
How can I adjust the size of attribution?

### ISSUE THREAD

**Issue by naykun** [mapbox/mapbox-gl-js#6264]
**Platform:**

Browser Chrome
OS Windows 10

**Mapbox SDK version:**

v0.38.0/mapbox-gl.js

### Steps to trigger behavior
mapboxgl.accessToken ='-----------';
    var map = new mapboxgl.Map({
        container: 'main',
        style: 'mapbox://styles/----------------',
        center:[116.402030, 39.937034],
        zoom:12
    });
just as the basic setting in the document
### Expected behavior
A map with an normal size attribution.
### Actual behavior
![image](https://user-images.githubusercontent.com/20919663/36885120-faeaf584-1e1f-11e8-81a4-2f8741d3aceb.png)
Obviously the attribution is too large. How can I adjust it? 

I have tried to change the value of compact in AttributionControl (https://www.mapbox.com/mapbox-gl-js/api/#attributioncontrol) . But it didn't work. Thanks a lot.

**Comment by jingsam** [comment]
You can add fellowing css:
```
.mapboxgl-ctrl-attrib {
  font-size: 10px;
}
```
Note that the default font-size of attribution text is 12px, and your text seems larger than that. Did you zoomed your page to 150%?

**Comment by naykun** [comment]
Thanks a lot. That works ! But I never zoomed my page, which is odd.
![image](https://user-images.githubusercontent.com/20919663/36886737-c84ca61e-1e28-11e8-81c1-f99091afed07.png)
