### ISSUE TITLE
Coordinate accuracy in China

### ISSUE THREAD

**Issue by davidyu37** [mapbox/mapbox-gl-js#6265]
**mapbox-gl-js version**: 0.43

### Steps to Trigger Behavior

 1. Draw marker with coordinates from Google map
 2. Markers appears to be off 
 
Have tried to use some library that converts WGS to GCJ and vice versa. 

It works for the most part except markers in Beijing. 

How has everyone been solving this issue?

This is the library that I mentioned: https://github.com/googollee/eviltransform

**Comment by mollymerp** [comment]
Hi @davidyu37 – can you please post a reproduction of the issue you're experiencing on jsbin or jsfiddle? Based on your description, I'm not sure if the issue you're describing is actionable for this library or if it is an issue with the third-party `eviltransform` you've linked above. Thank you!
