### ISSUE TITLE
in cluster example，source must be geojson,but my source is vector,so ,i want ask everyone how to solve the question

### ISSUE THREAD

**Issue by zhangpengye** [mapbox/mapbox-gl-js#6279]
map.addSource("earthquakes", {
        type: "geojson",
        // Point to GeoJSON data. This example visualizes all M1.0+ earthquakes
        // from 12/22/15 to 1/21/16 as logged by USGS' Earthquake hazards program.
        data: "/mapbox-gl-js/assets/earthquakes.geojson",
        cluster: true,
        clusterMaxZoom: 14, // Max zoom to cluster points on
        clusterRadius: 50 // Radius of each cluster when clustering points (defaults to 50)
    });
but, 
map.addLayer({
        "id": "mapillary",
        "type": "line",
        "source": {
            "type": "vector",
            "tiles": ["https://d25uarhxywzl1j.cloudfront.net/v0.1/{z}/{x}/{y}.mvt"],
            "minzoom": 6,
            "maxzoom": 14
        },
        "source-layer": "mapillary-sequences"）
who can tell me how to transfer vector to geojson.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
