### ISSUE TITLE
Handle retina <=> non-retina switch

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#628]
When moving the browser window from a retina to a non-retina screen (or vice versa), we're not properly changing the map:

* The switch is only detected on browser window resize. Instead, we should check on every frame (or on window move?) whether the ratio changed
* The sprite isn't reloaded. We should move to a one-json and multiple .png file format and require that all pixels

**Comment by mourner** [comment]
The original issue is a big effort to solve and is not worth fixing given how little trouble it introduces. The comments point to a different issue, so if they are still relevant, a new issue should be opened. Closing this one.
