### ISSUE TITLE
Expressions not painting tileset zones consistently

### ISSUE THREAD

**Issue by lcapel** [mapbox/mapbox-gl-js#6282]
I have uploaded and converted a GeoJSON map to a vector tileset. I noticed that some of the countries that I was trying to display were not being painted correctly by the paint expression. I have created a couple of example maps including only these countries so that you can have a look at the issue. Notice how in the first example, which does not use expressions, all countries are being painted correctly. In the second example none of them are and one of them Ecuador is only being painted in its main territory while the Galapagos islands are not. I am using the latest version (0.44.1) of Mapbox. 

**N.B.** Please replace the API key with a working one when you look at the examples, the tilesets have been set to be public.

[Harcoded paint color example](http://jsbin.com/kovafabijo)
[Expression color eample](http://jsbin.com/hufetizixo)

**Comment by jfirebaugh** [comment]
Only "Ecuador" matches the "name" property from your vector tile source. The other countries have "name" properties like "Dominican Rep.", "Turks and Caicos Is.", "S. Georgia". Those don't match any of the strings used in the match expression, so it falls back to the default value "#000000".
