### ISSUE TITLE
Documentation of Filter function needs a little cleanup

### ISSUE THREAD

**Issue by 3vivekb** [mapbox/mapbox-gl-js#6284]
### Steps to Trigger Behavior
Head to here:
https://www.mapbox.com/mapbox-gl-js/style-spec#other-filter
 1. "A filter is defined using any boolean expression. "  - the link where the word expression is no longer correct.

2. "A value (and v0, ..., vn for set operators) must be astring, number, or boolean to compare the property value against."  'astring' should be 'a string'.

3. Which is deprecated?  Which is not deprecated?

**Comment by jfirebaugh** [comment]
Hopefully 5c1bc104f0c478a2fabb19ac6e5b04c3d3c46306 clarifies things (and 2e514f4ff3780ae9d231c42da7dc642da349baf9 fixes the whitespace).

**Comment by 3vivekb** [comment]
This helps thanks!
