### ISSUE TITLE
Style specification should specify color space

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#6285]
The style specification should specify which color space the [Color](https://www.mapbox.com/mapbox-gl-js/style-spec/#types-color) type is expressed in. Most likely it should be sRGB, for consistency with [CSS’s color data type](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value).

/ref mapbox/mapbox-gl-native#11391
/cc @mapbox/gl-core

**Comment by jfirebaugh** [comment]
Done in 04b1c938c11954087437267d3b931c0421cd6423.
