### ISSUE TITLE
GeoJSON source setData position is not matching with the original data at different zoom-levels.

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-js#6286]
**mapbox-gl-js version**: v0.44.1

### Steps to Trigger Behavior

 1. Load custom geojson source on top of the map.
 2. Identify one of those feature by using `queryRenderedFeatures` at higher zoom level between 0 to 8.
 3. And highlight the selected feature by adding another source and layer with custom paint property.
 4. Now, zoom in closer to the feature. Highlighted feature position is not matching with the original feature for different zoomlevel.

Look at this jsfiddle for more,
https://jsfiddle.net/thiyagarajan_/1m9ufon5/19/

Herewith, I am attaching the images as well, 

<img width="693" alt="hightlight_issue_1" src="https://user-images.githubusercontent.com/17313049/37028697-f994c4e2-215a-11e8-85c0-661f77a337fe.png">
<img width="698" alt="hightlight_issue_2" src="https://user-images.githubusercontent.com/17313049/37028698-f9bf68b4-215a-11e8-9897-63221fd004b1.png">
<img width="694" alt="hightlight_issue_3" src="https://user-images.githubusercontent.com/17313049/37028699-f9e8aac6-215a-11e8-9298-b2ea92eda818.png">
<img width="699" alt="hightlight_issue_4" src="https://user-images.githubusercontent.com/17313049/37028700-fa205ad4-215a-11e8-976f-21f6c09a05c7.png">

**Comment by mourner** [comment]
Thanks for the report! This is a technical limitation of `queryRenderedFeatures` — the features are encoded into vector tiles, which have limited resolution appropriate for the zoom level they're created for. You'll have to get the original position through some other means — e.g. saving the feature id and matching it against a lookup table with original locations.

**Comment by ThiyagarajanShivSankaran** [comment]
@mourner we have loaded about 30 style's in Mapbox-studio, and each style has more than 50 layer's.
So, you are telling us to create a lookup table for each feature in the layer's and match the original coordinates with that, Bravo. 

Then why I need to use MapBox?
