### ISSUE TITLE
Ugly render vector tiles polygon from geoserver

### ISSUE THREAD

**Issue by nqlong** [mapbox/mapbox-gl-js#6287]
**mapbox-gl-js version**:0.44.1

### Steps to Trigger Behavior

 I used code below for rendering mabox vector tiles format from geoserver 2.12.
```
   mapboxgl.accessToken = 'pk.eyJ1IjoibnFsb25nIiwiYSI6ImNqZGl4cG9rdjBlNG4ycXFwOG9neHVyYmIifQ.sojbuOEH4ASnaAWAKvWQqQ';
    
 

  //map info here
 var map = new mapboxgl.Map({
     container: 'map', // container id
     style: 'mapbox://styles/mapbox/streets-v9', //stylesheet location
     center: [ 106.707, 10.7], // starting position[35.890, -75.664]
     zoom: 11, // starting zoom
     hash: true, //get hash
     minZoom: 0, //minzoom
     maxZoom: 22, //maxzoom
    //  preserveDrawingBuffer: true //exporting images
  });

map.on('load', function () {

    var GEOSERVERURL='http://159.89.203.165:8080';
    var layerName ='vlab:qhpksdd';
    var vectorLayerSource = GEOSERVERURL + 
    '/geoserver/gwc/service/tms/1.0.0/' +
    layerName +
    '@EPSG%3A900913' +
    '@pbf/{z}/{x}/{y}.pbf';

    map.addSource('plainning_source', {
        "type": "vector",
        "scheme":'tms',
        "tiles":[vectorLayerSource],
        minzoom: 10,
        maxzoom: 22,
        tileSize:512
  });
    map.addLayer({
        "id": "plainning_layer_fill",
        "type": "fill",
        "source": "plainning_source",
        "source-layer": "qhpksdd",
        "filter": ["==", "$type", "Polygon"],
        layout: {
        visibility: 'visible'
        },
        "paint": {
            "fill-outline-color": "#3887be",
            "fill-color": 'rgba(30,60,90,0)'

            
        }
  });

  map.addLayer({
        "id": "plainning_layer_line",
        "type": "line",
        "source": "plainning_source",
        "source-layer": "qhpksdd",
        "filter": ["==", "$type", "Polygon"],
        layout: {
        visibility: 'visible'
        },
        "paint": {
            "line-color": "#3887be"
         
        }
  });
```
 
The geometry of polygons are too mess in mapbox when comparing to openlayers. It seems the generalization process of mapbox make that. I would like to turn off that process. Please suggest any idea, thanks
 

### Expected Behavior
<img width="1428" alt="screen shot 2018-03-07 at 12 40 01 am" src="https://user-images.githubusercontent.com/7588864/37048472-9294dcbe-21a0-11e8-94be-834c4d37a556.png">

### Actual Behavior

<img width="1378" alt="screen shot 2018-03-07 at 12 48 17 am" src="https://user-images.githubusercontent.com/7588864/37048712-47861cdc-21a1-11e8-8dc8-2e7fddd663fc.png">

**Comment by mollymerp** [comment]
@nqlong thanks for using Mapbox GL! mapbox-gl-js does not do any client-side generalization/simplification, it appears these errors are due to the fact that the vector tiles from your server do not conform to v2 of the vector-tile spec:
![image](https://user-images.githubusercontent.com/2425307/37051299-e26a1932-212a-11e8-96b9-a4512aca87b1.png)

Unfortunately, you will have to generate your tiles according to v2 in order for mapbox-gl-js to be able to correctly tesselate and render the geometries.
