### ISSUE TITLE
Icon and text overlap conflict

### ISSUE THREAD

**Issue by PhaelIshall** [mapbox/mapbox-gl-js#6292]
**mapbox-gl-js version**

I have encountered what I think is a bug. I have several icons on display and each icon has a `text-field ` under it. At any given zoom level, I would like to have the icons always show, but the text only show when there is no overlap.

### Steps to Trigger Behavior

 1. Have several markers on a map with custom icon + `text-field`
 2. set ` "icon-allow-overlap": true, `and `"text-allow-overlap": false,`
 3. animate the markers by updating the Source data

### Expected Behavior
The icons should always be there, and the text should only be displayed when there is no overlap
### Actual Behavior
The icons disappear with the text when there is an overlap. The behavior should be separate.

**Comment by jfirebaugh** [comment]
Hi @PhaelIshall, thanks for using Mapbox. Setting [`"text-optional": true`](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-optional) should produce the desired behavior in this case.
