### ISSUE TITLE
Mapbox-gl JS app is crashing in all the IOS mobile device browsers.

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-js#6300]
**mapbox-gl-js version**: v0.44.1

Our mapbox app is not working in any of the mobile device browsers. 
We also tested with a empty map along with our style loaded on it, but that too crashing while panning and zooming the map.

**Devices Tested:** 
iPhone-X,  iPhone-8 ,  iPhone-7,  iPhone-6 etc.
iPad Air, iPad Air-2, iPad 3rd Gen, iPad 4th Gen etc. 

**Browsers Tested:** 
Chrome Version 64.0.3282.186,  Safari Version 11.0.2, Firefox 58.0.2 (64-bit) etc.

 **Browser Console:**  Web Page Crashed (This web page reloaded because a problem occurred).

What we need to do?

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?

**Comment by ThiyagarajanShivSankaran** [comment]
@jfirebaugh actually it's crashing without our code.
Like, we took the url from Mapbox-studio `share, develop & use` and used in mobile browsers. 

[https://api.mapbox.com/styles/v1/user/cjam100rcd6kq2rdsadadasdas.html?fresh=true&title=true&access_token=pk.xxxxxxxxxxxxqwwwwww-wwwwwwwwww#zoomlevel/lat/-long/0](url)

I can't share that url here in public. How can I share to you for further investigation?

**Comment by stalniy** [comment]
Works fine in WKWebView on iphone6 & iphone5SE

**Comment by ThiyagarajanShivSankaran** [comment]
@stalniy WKWebView? Are you taking about iOS SDK?

**Comment by stalniy** [comment]
I use `mapbox-gl@0.44.1` in [cordova](https://cordova.apache.org/) based mobile app

**Comment by ThiyagarajanShivSankaran** [comment]
@stalniy Oh Ok. Sorry, I didn't know about it.

**Comment by jfirebaugh** [comment]
It looks like the complexity of the style is running the iPhone out of memory, and as a result iOS is killing the process. This is one of the most complex styles I've come across, with 10+ datasources, 300+ layers, and multi-megabyte vector tiles. I suggest you work with Mapbox support on ways to reduce the complexity of the style and size of the vector tiles in order to reach an acceptable level of performance.
