### ISSUE TITLE
map.on('click') callback function returning null for random tuples in the tileset.

### ISSUE THREAD

**Issue by agdhruv** [mapbox/mapbox-gl-js#6301]
**mapbox-gl-js version**: v0.44.1

### Steps to Trigger Behavior

 1. Go to [this](https://agdhruv.github.io/mapbox-scrollytelling-starter/) webpage.
 2. Click on few of the circles visualised on the map to trigger popups.

### Expected Behavior
All the popups must show a numerical value for population density.

### Actual Behavior
Some of the popups show `NaN` for population density, while some don't. There seems to be no pattern to which cities show `NaN` and which do not. The population density is calculated using the area of the city, which is stored in the tileset. For the cities showing `NaN`, this is because the population is being divided by `null` which is what those cities are returning for their `area` property.

**Comment by jfirebaugh** [comment]
> For the cities showing NaN, this is because the population is being divided by null which is what those cities are returning for their area property.

That's correct: some of the features in your dataset do not have an `area` property (for instance the "Ghaziabad" feature), so the divisions `pop_2001/city_area` and `pop_2011/city_area` produce `NaN`. This would be something you need to fix in the dataset.

**Comment by agdhruv** [comment]
@jfirebaugh I rechecked my dataset. I have the `area` property in all the features.

**Comment by jfirebaugh** [comment]
@agdhruv Here's a dump from `vt2geojson https://a.tiles.mapbox.com/v4/agdhruv.cjdzvi97z2xfb2xpdmevpcj12-1wmep/4/11/6.vector.pbf?<your access token>`:

<details>
<pre>
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          80.33203125,
          26.470573022375078
        ]
      },
      "properties": {
        "area": 403.7,
        "city": "Kanpur",
        "pop_2001": 2551337,
        "pop_2011": 2765348,
        "rank": 12,
        "sqrt_2001": 1597.3,
        "sqrt_2011": 1662.9
      },
      "id": 1
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          80.914306640625,
          26.858380138726574
        ]
      },
      "properties": {
        "area": 350,
        "city": "Lucknow",
        "pop_2001": 2185927,
        "pop_2011": 2817105,
        "rank": 11,
        "sqrt_2001": 1478.5,
        "sqrt_2011": 1678.4
      },
      "id": 2
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          72.5811767578125,
          23.029187346744592
        ]
      },
      "properties": {
        "area": 464,
        "city": "Ahmedabad",
        "pop_2001": 3520085,
        "pop_2011": 5577940,
        "rank": 5,
        "sqrt_2001": 1876.2,
        "sqrt_2011": 2361.8
      },
      "id": 3
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          88.3355712890625,
          22.543000965921863
        ]
      },
      "properties": {
        "city": "Kolkata",
        "pop_2001": 4572876,
        "pop_2011": 4496694,
        "rank": 7,
        "sqrt_2001": 2138.4,
        "sqrt_2011": 2120.5
      },
      "id": 4
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.849609375,
          30.90693797089463
        ]
      },
      "properties": {
        "city": "Ludhiana",
        "pop_2001": 1398467,
        "pop_2011": 1613878,
        "rank": 22,
        "sqrt_2001": 1182.6,
        "sqrt_2011": 1270.4
      },
      "id": 5
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.8660888671875,
          26.917171977972316
        ]
      },
      "properties": {
        "area": 111.8,
        "city": "Jaipur",
        "pop_2001": 2322575,
        "pop_2011": 3046163,
        "rank": 10,
        "sqrt_2001": 1524,
        "sqrt_2011": 1745.3
      },
      "id": 6
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          85.14404296875,
          25.611809521055477
        ]
      },
      "properties": {
        "area": 99.97,
        "city": "Patna",
        "pop_2001": 1366444,
        "pop_2011": 1683200,
        "rank": 19,
        "sqrt_2001": 1168.9,
        "sqrt_2011": 1297.4
      },
      "id": 7
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          73.201904296875,
          22.299261499741206
        ]
      },
      "properties": {
        "area": 225,
        "city": "Vadodara",
        "pop_2001": 1306227,
        "pop_2011": 1666703,
        "rank": 20,
        "sqrt_2001": 1142.9,
        "sqrt_2011": 1291
      },
      "id": 8
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.8660888671875,
          26.917171977972316
        ]
      },
      "properties": {
        "area": 111.8,
        "city": "Jaipur",
        "pop_2001": 2322575,
        "pop_2011": 3046163,
        "rank": 10,
        "sqrt_2001": 1524,
        "sqrt_2011": 1745.3
      },
      "id": 9
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          72.5811767578125,
          23.029187346744592
        ]
      },
      "properties": {
        "area": 464,
        "city": "Ahmedabad",
        "pop_2001": 3520085,
        "pop_2011": 5577940,
        "rank": 5,
        "sqrt_2001": 1876.2,
        "sqrt_2011": 2361.8
      },
      "id": 10
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.8660888671875,
          26.917171977972316
        ]
      },
      "properties": {
        "area": 111.8,
        "city": "Jaipur",
        "pop_2001": 2322575,
        "pop_2011": 3046163,
        "rank": 10,
        "sqrt_2001": 1524,
        "sqrt_2011": 1745.3
      },
      "id": 11
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          73.201904296875,
          22.299261499741206
        ]
      },
      "properties": {
        "area": 225,
        "city": "Vadodara",
        "pop_2001": 1306227,
        "pop_2011": 1666703,
        "rank": 20,
        "sqrt_2001": 1142.9,
        "sqrt_2011": 1291
      },
      "id": 12
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          80.914306640625,
          26.858380138726574
        ]
      },
      "properties": {
        "city": "Lucknow",
        "pop_2001": 2185927,
        "pop_2011": 2817105,
        "rank": 11,
        "sqrt_2001": 1478.5,
        "sqrt_2011": 1678.4
      },
      "id": 13
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.849609375,
          22.72045700902588
        ]
      },
      "properties": {
        "area": 389.8,
        "city": "Indore",
        "pop_2001": 1474968,
        "pop_2011": 1960631,
        "rank": 15,
        "sqrt_2001": 1214.5,
        "sqrt_2011": 1400.2
      },
      "id": 14
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          80.33203125,
          26.470573022375078
        ]
      },
      "properties": {
        "city": "Kanpur",
        "pop_2001": 2551337,
        "pop_2011": 2765348,
        "rank": 12,
        "sqrt_2001": 1597.3,
        "sqrt_2011": 1662.9
      },
      "id": 15
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          88.3355712890625,
          22.543000965921863
        ]
      },
      "properties": {
        "city": "Kolkata",
        "pop_2001": 4572876,
        "pop_2011": 4496694,
        "rank": 7,
        "sqrt_2001": 2138.4,
        "sqrt_2011": 2120.5
      },
      "id": 16
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          80.914306640625,
          26.858380138726574
        ]
      },
      "properties": {
        "area": 350,
        "city": "Lucknow",
        "pop_2001": 2185927,
        "pop_2011": 2817105,
        "rank": 11,
        "sqrt_2001": 1478.5,
        "sqrt_2011": 1678.4
      },
      "id": 17
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.4151611328125,
          28.66649117698661
        ]
      },
      "properties": {
        "area": 133.3,
        "city": "Ghaziabad",
        "pop_2001": 968256,
        "pop_2011": 1636068,
        "rank": 21,
        "sqrt_2001": 984,
        "sqrt_2011": 1279.1
      },
      "id": 18
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.1240234375,
          28.652030630362262
        ]
      },
      "properties": {
        "area": 1484,
        "city": "Delhi",
        "pop_2001": 9879172,
        "pop_2011": 11034555,
        "rank": 2,
        "sqrt_2001": 3143.1,
        "sqrt_2011": 3321.8
      },
      "id": 19
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.1240234375,
          28.652030630362262
        ]
      },
      "properties": {
        "area": 1484,
        "city": "Delhi",
        "pop_2001": 9879172,
        "pop_2011": 11034555,
        "rank": 2,
        "sqrt_2001": 3143.1,
        "sqrt_2011": 3321.8
      },
      "id": 20
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          88.3355712890625,
          22.543000965921863
        ]
      },
      "properties": {
        "area": 205,
        "city": "Kolkata",
        "pop_2001": 4572876,
        "pop_2011": 4496694,
        "rank": 7,
        "sqrt_2001": 2138.4,
        "sqrt_2011": 2120.5
      },
      "id": 21
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.4151611328125,
          23.251440517055997
        ]
      },
      "properties": {
        "city": "Bhopal",
        "pop_2001": 1437354,
        "pop_2011": 1798218,
        "rank": 17,
        "sqrt_2001": 1198.9,
        "sqrt_2011": 1341
      },
      "id": 22
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          88.3355712890625,
          22.543000965921863
        ]
      },
      "properties": {
        "area": 205,
        "city": "Kolkata",
        "pop_2001": 4572876,
        "pop_2011": 4496694,
        "rank": 7,
        "sqrt_2001": 2138.4,
        "sqrt_2011": 2120.5
      },
      "id": 23
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          73.201904296875,
          22.299261499741206
        ]
      },
      "properties": {
        "area": 225,
        "city": "Vadodara",
        "pop_2001": 1306227,
        "pop_2011": 1666703,
        "rank": 20,
        "sqrt_2001": 1142.9,
        "sqrt_2011": 1291
      },
      "id": 24
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          78.0194091796875,
          27.181355765758894
        ]
      },
      "properties": {
        "area": 188.4,
        "city": "Agra",
        "pop_2001": 1275134,
        "pop_2011": 1585704,
        "rank": 24,
        "sqrt_2001": 1129.2,
        "sqrt_2011": 1259.2
      },
      "id": 25
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.4151611328125,
          23.251440517055997
        ]
      },
      "properties": {
        "area": 285.9,
        "city": "Bhopal",
        "pop_2001": 1437354,
        "pop_2011": 1798218,
        "rank": 17,
        "sqrt_2001": 1198.9,
        "sqrt_2011": 1341
      },
      "id": 26
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.849609375,
          22.72045700902588
        ]
      },
      "properties": {
        "area": 389.8,
        "city": "Indore",
        "pop_2001": 1474968,
        "pop_2011": 1960631,
        "rank": 15,
        "sqrt_2001": 1214.5,
        "sqrt_2011": 1400.2
      },
      "id": 27
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.4151611328125,
          28.66649117698661
        ]
      },
      "properties": {
        "city": "Ghaziabad",
        "pop_2001": 968256,
        "pop_2011": 1636068,
        "rank": 21,
        "sqrt_2001": 984,
        "sqrt_2011": 1279.1
      },
      "id": 28
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          85.14404296875,
          25.611809521055477
        ]
      },
      "properties": {
        "area": 99.97,
        "city": "Patna",
        "pop_2001": 1366444,
        "pop_2011": 1683200,
        "rank": 19,
        "sqrt_2001": 1168.9,
        "sqrt_2011": 1297.4
      },
      "id": 29
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.849609375,
          30.90693797089463
        ]
      },
      "properties": {
        "area": 310,
        "city": "Ludhiana",
        "pop_2001": 1398467,
        "pop_2011": 1613878,
        "rank": 22,
        "sqrt_2001": 1182.6,
        "sqrt_2011": 1270.4
      },
      "id": 30
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.849609375,
          30.90693797089463
        ]
      },
      "properties": {
        "area": 310,
        "city": "Ludhiana",
        "pop_2001": 1398467,
        "pop_2011": 1613878,
        "rank": 22,
        "sqrt_2001": 1182.6,
        "sqrt_2011": 1270.4
      },
      "id": 31
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          73.201904296875,
          22.299261499741206
        ]
      },
      "properties": {
        "city": "Vadodara",
        "pop_2001": 1306227,
        "pop_2011": 1666703,
        "rank": 20,
        "sqrt_2001": 1142.9,
        "sqrt_2011": 1291
      },
      "id": 32
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.1240234375,
          28.652030630362262
        ]
      },
      "properties": {
        "city": "Delhi",
        "pop_2001": 9879172,
        "pop_2011": 11034555,
        "rank": 2,
        "sqrt_2001": 3143.1,
        "sqrt_2011": 3321.8
      },
      "id": 33
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.4151611328125,
          28.66649117698661
        ]
      },
      "properties": {
        "area": 133.3,
        "city": "Ghaziabad",
        "pop_2001": 968256,
        "pop_2011": 1636068,
        "rank": 21,
        "sqrt_2001": 984,
        "sqrt_2011": 1279.1
      },
      "id": 34
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          85.14404296875,
          25.611809521055477
        ]
      },
      "properties": {
        "city": "Patna",
        "pop_2001": 1366444,
        "pop_2011": 1683200,
        "rank": 19,
        "sqrt_2001": 1168.9,
        "sqrt_2011": 1297.4
      },
      "id": 35
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          88.3355712890625,
          22.543000965921863
        ]
      },
      "properties": {
        "area": 205,
        "city": "Kolkata",
        "pop_2001": 4572876,
        "pop_2011": 4496694,
        "rank": 7,
        "sqrt_2001": 2138.4,
        "sqrt_2011": 2120.5
      },
      "id": 36
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.1240234375,
          28.652030630362262
        ]
      },
      "properties": {
        "city": "Delhi",
        "pop_2001": 9879172,
        "pop_2011": 11034555,
        "rank": 2,
        "sqrt_2001": 3143.1,
        "sqrt_2011": 3321.8
      },
      "id": 37
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          80.33203125,
          26.470573022375078
        ]
      },
      "properties": {
        "city": "Kanpur",
        "pop_2001": 2551337,
        "pop_2011": 2765348,
        "rank": 12,
        "sqrt_2001": 1597.3,
        "sqrt_2011": 1662.9
      },
      "id": 38
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.8660888671875,
          26.917171977972316
        ]
      },
      "properties": {
        "city": "Jaipur",
        "pop_2001": 2322575,
        "pop_2011": 3046163,
        "rank": 10,
        "sqrt_2001": 1524,
        "sqrt_2011": 1745.3
      },
      "id": 39
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.4151611328125,
          23.251440517055997
        ]
      },
      "properties": {
        "city": "Bhopal",
        "pop_2001": 1437354,
        "pop_2011": 1798218,
        "rank": 17,
        "sqrt_2001": 1198.9,
        "sqrt_2011": 1341
      },
      "id": 40
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.849609375,
          22.72045700902588
        ]
      },
      "properties": {
        "city": "Indore",
        "pop_2001": 1474968,
        "pop_2011": 1960631,
        "rank": 15,
        "sqrt_2001": 1214.5,
        "sqrt_2011": 1400.2
      },
      "id": 41
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.849609375,
          30.90693797089463
        ]
      },
      "properties": {
        "city": "Ludhiana",
        "pop_2001": 1398467,
        "pop_2011": 1613878,
        "rank": 22,
        "sqrt_2001": 1182.6,
        "sqrt_2011": 1270.4
      },
      "id": 42
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          73.201904296875,
          22.299261499741206
        ]
      },
      "properties": {
        "city": "Vadodara",
        "pop_2001": 1306227,
        "pop_2011": 1666703,
        "rank": 20,
        "sqrt_2001": 1142.9,
        "sqrt_2011": 1291
      },
      "id": 43
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          80.914306640625,
          26.858380138726574
        ]
      },
      "properties": {
        "city": "Lucknow",
        "pop_2001": 2185927,
        "pop_2011": 2817105,
        "rank": 11,
        "sqrt_2001": 1478.5,
        "sqrt_2011": 1678.4
      },
      "id": 44
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          72.5811767578125,
          23.029187346744592
        ]
      },
      "properties": {
        "area": 464,
        "city": "Ahmedabad",
        "pop_2001": 3520085,
        "pop_2011": 5577940,
        "rank": 5,
        "sqrt_2001": 1876.2,
        "sqrt_2011": 2361.8
      },
      "id": 45
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.8660888671875,
          26.917171977972316
        ]
      },
      "properties": {
        "city": "Jaipur",
        "pop_2001": 2322575,
        "pop_2011": 3046163,
        "rank": 10,
        "sqrt_2001": 1524,
        "sqrt_2011": 1745.3
      },
      "id": 46
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.4151611328125,
          28.66649117698661
        ]
      },
      "properties": {
        "area": 133.3,
        "city": "Ghaziabad",
        "pop_2001": 968256,
        "pop_2011": 1636068,
        "rank": 21,
        "sqrt_2001": 984,
        "sqrt_2011": 1279.1
      },
      "id": 47
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.4151611328125,
          23.251440517055997
        ]
      },
      "properties": {
        "area": 285.9,
        "city": "Bhopal",
        "pop_2001": 1437354,
        "pop_2011": 1798218,
        "rank": 17,
        "sqrt_2001": 1198.9,
        "sqrt_2011": 1341
      },
      "id": 48
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          78.0194091796875,
          27.181355765758894
        ]
      },
      "properties": {
        "city": "Agra",
        "pop_2001": 1275134,
        "pop_2011": 1585704,
        "rank": 24,
        "sqrt_2001": 1129.2,
        "sqrt_2011": 1259.2
      },
      "id": 49
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.849609375,
          22.72045700902588
        ]
      },
      "properties": {
        "area": 389.8,
        "city": "Indore",
        "pop_2001": 1474968,
        "pop_2011": 1960631,
        "rank": 15,
        "sqrt_2001": 1214.5,
        "sqrt_2011": 1400.2
      },
      "id": 50
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          78.0194091796875,
          27.181355765758894
        ]
      },
      "properties": {
        "city": "Agra",
        "pop_2001": 1275134,
        "pop_2011": 1585704,
        "rank": 24,
        "sqrt_2001": 1129.2,
        "sqrt_2011": 1259.2
      },
      "id": 51
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.849609375,
          22.72045700902588
        ]
      },
      "properties": {
        "city": "Indore",
        "pop_2001": 1474968,
        "pop_2011": 1960631,
        "rank": 15,
        "sqrt_2001": 1214.5,
        "sqrt_2011": 1400.2
      },
      "id": 52
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          80.914306640625,
          26.858380138726574
        ]
      },
      "properties": {
        "area": 350,
        "city": "Lucknow",
        "pop_2001": 2185927,
        "pop_2011": 2817105,
        "rank": 11,
        "sqrt_2001": 1478.5,
        "sqrt_2011": 1678.4
      },
      "id": 53
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          85.14404296875,
          25.611809521055477
        ]
      },
      "properties": {
        "area": 99.97,
        "city": "Patna",
        "pop_2001": 1366444,
        "pop_2011": 1683200,
        "rank": 19,
        "sqrt_2001": 1168.9,
        "sqrt_2011": 1297.4
      },
      "id": 54
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          85.14404296875,
          25.611809521055477
        ]
      },
      "properties": {
        "area": 99.97,
        "city": "Patna",
        "pop_2001": 1366444,
        "pop_2011": 1683200,
        "rank": 19,
        "sqrt_2001": 1168.9,
        "sqrt_2011": 1297.4
      },
      "id": 55
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          78.0194091796875,
          27.181355765758894
        ]
      },
      "properties": {
        "area": 188.4,
        "city": "Agra",
        "pop_2001": 1275134,
        "pop_2011": 1585704,
        "rank": 24,
        "sqrt_2001": 1129.2,
        "sqrt_2011": 1259.2
      },
      "id": 56
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.4151611328125,
          23.251440517055997
        ]
      },
      "properties": {
        "area": 285.9,
        "city": "Bhopal",
        "pop_2001": 1437354,
        "pop_2011": 1798218,
        "rank": 17,
        "sqrt_2001": 1198.9,
        "sqrt_2011": 1341
      },
      "id": 57
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          78.0194091796875,
          27.181355765758894
        ]
      },
      "properties": {
        "area": 188.4,
        "city": "Agra",
        "pop_2001": 1275134,
        "pop_2011": 1585704,
        "rank": 24,
        "sqrt_2001": 1129.2,
        "sqrt_2011": 1259.2
      },
      "id": 58
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.1240234375,
          28.652030630362262
        ]
      },
      "properties": {
        "area": 1484,
        "city": "Delhi",
        "pop_2001": 9879172,
        "pop_2011": 11034555,
        "rank": 2,
        "sqrt_2001": 3143.1,
        "sqrt_2011": 3321.8
      },
      "id": 59
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          80.33203125,
          26.470573022375078
        ]
      },
      "properties": {
        "area": 403.7,
        "city": "Kanpur",
        "pop_2001": 2551337,
        "pop_2011": 2765348,
        "rank": 12,
        "sqrt_2001": 1597.3,
        "sqrt_2011": 1662.9
      },
      "id": 60
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          80.33203125,
          26.470573022375078
        ]
      },
      "properties": {
        "area": 403.7,
        "city": "Kanpur",
        "pop_2001": 2551337,
        "pop_2011": 2765348,
        "rank": 12,
        "sqrt_2001": 1597.3,
        "sqrt_2011": 1662.9
      },
      "id": 61
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          72.5811767578125,
          23.029187346744592
        ]
      },
      "properties": {
        "city": "Ahmedabad",
        "pop_2001": 3520085,
        "pop_2011": 5577940,
        "rank": 5,
        "sqrt_2001": 1876.2,
        "sqrt_2011": 2361.8
      },
      "id": 62
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          77.4151611328125,
          28.66649117698661
        ]
      },
      "properties": {
        "city": "Ghaziabad",
        "pop_2001": 968256,
        "pop_2011": 1636068,
        "rank": 21,
        "sqrt_2001": 984,
        "sqrt_2011": 1279.1
      },
      "id": 63
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          72.5811767578125,
          23.029187346744592
        ]
      },
      "properties": {
        "city": "Ahmedabad",
        "pop_2001": 3520085,
        "pop_2011": 5577940,
        "rank": 5,
        "sqrt_2001": 1876.2,
        "sqrt_2011": 2361.8
      },
      "id": 64
    },
    {
      "type": "Feature",
      "geometry": {
        "type": "Point",
        "coordinates": [
          75.849609375,
          30.90693797089463
        ]
      },
      "properties": {
        "area": 310,
        "city": "Ludhiana",
        "pop_2001": 1398467,
        "pop_2011": 1613878,
        "rank": 22,
        "sqrt_2001": 1182.6,
        "sqrt_2011": 1270.4
      },
      "id": 65
    }
  ]
}
</pre>
</details>

There are five features with the name "Ghaziabad" (IDs 18, 28, 34, 47, 63). Of those five features, three have an "area" property and two do not.
