### ISSUE TITLE
Add a "popup.open" event

### ISSUE THREAD

**Issue by jmeyers91** [mapbox/mapbox-gl-js#6302]
Basically the same as [Add a "popup.close" event](https://github.com/mapbox/mapbox-gl-js/issues/2584) except an `open` event should also trigger when the popup opens.

### Expected Behavior
This should log `'open'` to the console when the popup opens:

```
let popup = new mapboxgl.Popup()
popup.on('open', function(e) {
    console.log('open');
})
```

### Actual Behavior

The `open` event is never fired.

**Comment by jfirebaugh** [comment]
Hey @jmeyers91! This would make a good first contribution. Would you like to take a stab at a PR?

**Comment by jmeyers91** [comment]
Sure

**Comment by jfirebaugh** [comment]
Done in #6311. Thanks @jmeyers91!
