### ISSUE TITLE
Marker dynamic styling (fade out on zoom)

### ISSUE THREAD

**Issue by theochampion** [mapbox/mapbox-gl-js#6306]
I'm buidling a map in which I have custom markers (html elements styled with CSS) and I was wondering, is it possible to style them dynamicly based on zoom level to make them fade out on zoom in for example ? (just like what it is possible to do with the symbol layer)

And if not what would be a way to acheive this effect ?

**Comment by jfirebaugh** [comment]
This isn't a built-in feature of the library; you would need to implement it yourself, e.g. by listening for `zoom` events and showing or hiding the marker.
