### ISSUE TITLE
Question about filters (sorry for inappropriate submission, can't find the right place to post it :/ )

### ISSUE THREAD

**Issue by Agterra** [mapbox/mapbox-gl-js#6307]
Hey !

Firstable, I’m sorry to post this here but I have a question and I can’t figure out how to ask it with the actual Github organization. 

After a long search, I can’t find my answer through the Github issues board since my question is not an issue…

I would love to know if a filter option has been implemented that could let me find a substring into a property’s string, for exemple 

	map.setFilter(“myLayer”, [“contains”, “name”, substringToFindInName]);

It would filter all symbols witch name’s containing this substring.

I’ve seen a “match” update but it seems inappropriate for what I want…

I think your work is amazing, I’ve been working on an application for Lyon city in France for 2 months now, I really enjoy using you API Mapbox.

I hope someone could answer me or at least lead me on how to ask this question properly on Github.

Best regards from France,

Louis.

**Comment by jfirebaugh** [comment]
We're tracking the request for this feature in #4113.
