### ISSUE TITLE
Improve build time

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#6309]
Follow-up to https://github.com/mapbox/mapbox-gl-js/pull/6196

On my laptop, rebuilding takes about 7s:
- 3.2s to build `rollup/build/{index,worker,chunk1}.js`, and then
- 4s just to assemble these into the final bundle

That second step is much slower than it needs to be.  It's using Rollup again, but only to make sure the sourcemaps for `{index,worker,chunk1}.js` get properly consumed/composed into the final sourcemap.  This means we're wasting lots of time re-parsing these ast's even though it's not at all necessary.

**Comment by mourner** [comment]
Here's a perf profile for a build from scratch: https://gist.github.com/mourner/0acdc68648627ac431229d2ad601eefc

A quick scan seems to suggest there are some nice low hanging fruits there.

**Comment by anandthakker** [comment]
See also https://github.com/rollup/rollup/issues/1553

**Comment by anandthakker** [comment]
Tracking with a project board here: https://github.com/mapbox/mapbox-gl-js/projects/11

**Comment by jfirebaugh** [comment]
Rollup 0.58.0 and later includes https://github.com/rollup/rollup/pull/2119. We're currently on 0.57.1; however upgrading to 0.58.2 seems to break our solution for Web Workers:

```
$ /Users/john/Development/mapbox-gl-js/node_modules/.bin/rollup -c --environment BUILD:production

src/index.js, src/source/worker.js → rollup/build/mapboxgl...
(!) Circular dependency: src/style-spec/expression/parsing_context.js -> src/style-spec/expression/compound_expression.js -> src/style-spec/expression/parsing_context.js
(!) Circular dependency: src/style-spec/validate/validate.js -> src/style-spec/validate/validate_function.js -> src/style-spec/validate/validate.js
(!) Circular dependency: src/style-spec/validate/validate.js -> src/style-spec/validate/validate_function.js -> src/style-spec/validate/validate_object.js -> src/style-spec/validate/validate.js
(!) Circular dependency: src/style-spec/validate/validate.js -> src/style-spec/validate/validate_function.js -> src/style-spec/validate/validate_array.js -> src/style-spec/validate/validate.js
(!) Circular dependency: src/style-spec/validate/validate.js -> src/style-spec/validate/validate_layer.js -> src/style-spec/validate/validate_paint_property.js -> src/style-spec/validate/validate_property.js -> src/style-spec/validate/validate.js
(!) Circular dependency: src/style-spec/validate/validate.js -> src/style-spec/validate/validate_layer.js -> src/style-spec/validate/validate.js
(!) Circular dependency: src/style-spec/validate/validate.js -> src/style-spec/validate/validate_light.js -> src/style-spec/validate/validate.js
(!) Circular dependency: src/geo/lng_lat_bounds.js -> src/geo/lng_lat.js -> src/geo/lng_lat_bounds.js
(!) Circular dependency: src/index.js -> src/ui/map.js -> src/style/style.js -> src/util/global_worker_pool.js -> src/util/worker_pool.js -> src/util/browser/web_worker.js -> src/index.js
(!) Circular dependency: src/index.js -> src/ui/map.js -> src/style/style.js -> src/util/global_worker_pool.js -> src/util/worker_pool.js -> src/index.js
created rollup/build/mapboxgl in 15.7s

rollup/mapboxgl.js → dist/mapbox-gl.js...
[!] Error: Could not resolve './build/mapboxgl/chunk1' from rollup/mapboxgl.js
Error: Could not resolve './build/mapboxgl/chunk1' from rollup/mapboxgl.js
    at error (/Users/john/Development/mapbox-gl-js/node_modules/rollup/dist/rollup.js:199:15)
    at /Users/john/Development/mapbox-gl-js/node_modules/rollup/dist/rollup.js:20674:25
    at <anonymous>
```

**Comment by mourner** [comment]
@guybedford does this ring a bell? Probably related to your recent chunk-related changes...

**Comment by guybedford** [comment]
@mourner no idea what that might be actually. It seems like the resolveId plugin function is not returning anything for that case. Let me know if you can isolate this a little more perhaps.

**Comment by anandthakker** [comment]
Writing from my phone so I haven’t checked this out, but I suspect this is
because our two-step build process relies on knowing the name of the shared
chunk emitted by the first step, and it looks like that name now includes a
hash instead of just being “chunk1”.

Note that the tree-shaking improvements won’t help our dev build time
because we’re only doing tree shaking on prod builds

**Comment by guybedford** [comment]
Note a quick fix here would be to add `chunkNames: '[alias].js'` to the Rollup configuration, to avoid adding the hash.
