### ISSUE TITLE
Add expression operators for geometry length and area

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#6310]
The style specification should define expression operators related to the geographic size of a feature. It’s sometimes useful to filter or style linestring features according to their lengths or polygon features according to their areas.

Currently, designers must rely on the source to provide this information on each feature. For example, the Mapbox Streets source defines a `len` field on each feature in the [`road_label`](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#road_label) layer:

> The `len` field stores the length of the road segment in projected meters, rounded to the nearest whole number. This can be useful for limiting some label styles to longer roads.

and an `area` field on the [`state_label`](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#state_label) layer:

> The `area` field is the physical area of the entity in square kilometers. Use it to help filter and size your state labels at different zoom levels.

However, not every vector source layer provides this information, and a GeoJSON source is far from guaranteed to contain `len` and `area` fields. Dedicated expression operators would make it easier for the designer to account for geometry without an extra preprocessing step.

The `length` operator name is already used for getting the length of a string or array, so `geometry-length` and `geometry-area` would be my next suggestion. Contrary to the Streets source, I’d recommend expressing `geometry-area` in square meters, not square kilometers.

/cc @anandthakker @ajashton

**Comment by jfirebaugh** [comment]
Would such expressions be expected to calculate a result based on the complete geometry of a feature which has been split across tiles? I think that would be a natural assumption and the desired behavior in most cases that I can imagine.

Implementing that behavior would be quite difficult in our current layout model, in which tiles can be processed independently and in parallel. I would be extremely reluctant to give up on that algorithmic property. 

As an alternative, this can be accomplished at the dataset level by precomputing feature areas or lengths and including them as feature properties.

**Comment by 1ec5** [comment]
Yes, I think you’re right on all those points. For vector sources, I agree that precomputing the areas and lengths would be a sound optimization (and would also get around the thorny issue of feature reconstruction across tile boundaries). Do you think GL JS (or one of the native SDKs) should get in the business of making this precomputation easier? Should there be a standard way for vector tiles to indicate the length or area of a feature, so that style authors aren’t dependent on the vector tile source to anticipate a need for lengths and areas?

**Comment by jfirebaugh** [comment]
It seems to me this can be something that's included on an as-needed basis in datasources that need to make use of area and length. I don't think it's too much to ask that in cases such as this, the style author and source creator, if not the same person, must collaborate to produce a dataset with the necessary properties. This is the tradeoff of vector tiles: in return for the size, performance, and portability, some cartographic decisions must be baked in.
