### ISSUE TITLE
Rendering artifacts when rendering Polygons with complex inner rings

### ISSUE THREAD

**Issue by bfrengley** [mapbox/mapbox-gl-js#6313]
**mapbox-gl-js version**: 0.43.0 and up (possibly earlier as well)

### Steps to Trigger Behavior

Rendering polygons with complex inner rings (from either GeoJSON or vector tiles) sometimes results in artifacts appearing on the map, in the form of "spikes" from one inner ring to another which act like the inner rings are connected. These only persist over certain zoom levels.

See the following JSFiddle for an example case: https://jsfiddle.net/ndm00abw/10/

### Expected Behavior

![image](https://user-images.githubusercontent.com/37278140/37262195-8f6194f0-2606-11e8-95ac-1136818ab6c3.png)

At the next zoom level:
![image](https://user-images.githubusercontent.com/37278140/37262226-b3996b2c-2606-11e8-99aa-0be8d2e2473f.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/37278140/37262187-7e696056-2606-11e8-9941-e1a875046b51.png)

At the next zoom level:
![image](https://user-images.githubusercontent.com/37278140/37262222-ac2a5090-2606-11e8-81a6-90a8ecccb2d8.png)

Some examples rendering from a vector tile:
![image](https://user-images.githubusercontent.com/37278140/37262394-c6839a36-2607-11e8-948e-8e32b218e972.png)

![image](https://user-images.githubusercontent.com/37278140/37262428-f556a25e-2607-11e8-835a-be8a16374285.png)

![image](https://user-images.githubusercontent.com/37278140/37262439-003ef68a-2608-11e8-8e27-4a872e6690fc.png)

Possibly related to #6069 and #4922, but this affects normal `Polygon`s rather than `MultiPolygon`s

**Comment by jfirebaugh** [comment]
How were these geometries generated? It looks like the inner polygons contain self-intersections:

![image](https://user-images.githubusercontent.com/98601/37294596-64a2df72-25d3-11e8-910f-0da4b2aa9ece.png)

Mapbox GL is able to guarantee artifact-free rendering only for non-degenerate geometry (and that's also required by the vector tile specification).

**Comment by bfrengley** [comment]
They were generated using https://github.com/mapbox/wagyu.

It seems that the inner rings are all valid in isolation, but there are three points where two inner rings meet (only at tangents). As best I can tell, this kind of geometry is considered valid in GeoJSON (as mentioned in #2696), while the vector tile spec considers it invalid.

Is there a way to represent this kind of geometry in such a way that mapbox-gl-js can render it correctly, or is the only solution to avoid polygons with touching inner rings?

**Comment by flippmoke** [comment]
@bfrengley @jfirebaugh I looked at the expected rings and this is valid as per the OGC. We have multiple interior rings that are touching at discrete points, it is not a self intersection of a single interior ring. I do not think that this is an issue with wagyu, it seems that it is likely an issue in earcut instead. /cc @mourner

**Comment by mourner** [comment]
@bfrengley can you reduce the offending polygons to a minimal example and submit an issue to Earcut?

**Comment by mourner** [comment]
Looks like this is similar to a bunch of polygon artifacts issues we already have here — simplifying/grid-snapping polygons on lower zoom levels introduces self-intersections even if input polygons are valid. I'm planning to get back to my work on fast polygon fixing soon to try to tackle this once and for all.

**Comment by exelban** [comment]
Hi.
Receive the same error.
Any fix for this bug?

When zoom in/out the second layer disappear.

![zrzut ekranu 2018-06-20 o 15 58 03](https://user-images.githubusercontent.com/13332412/41663301-5f4f04aa-74a3-11e8-8423-e846a0faf90e.png)

**Comment by mourner** [comment]
Made a master ticket for this and similar issues to centralize the discussion: 7023
