### ISSUE TITLE
Proper way to access popup DOM node?

### ISSUE THREAD

**Issue by jmeyers91** [mapbox/mapbox-gl-js#6318]
I want to be able to add custom click listeners to my map popups, but I'm constructing the popups using `setHTML`. Internally, the element I'm trying to access is called `_content`, but there doesn't seem to be any public method/getter for accessing this property, so I'm doing this:

    popup._content.querySelector('.popup-close-button').addEventListener('click', () => {
      point.mapMarker.togglePopup();
    });

Is there a better way to do this without going through the private variable `_content`?

**Comment by jfirebaugh** [comment]
Could you use [`setDOMContent`](https://www.mapbox.com/mapbox-gl-js/api#popup#setdomcontent) instead of `setHTML`, and bind the listener directly to the `Node`? That's usually what we suggest.
