### ISSUE TITLE
Polygons from Geojson layer appear dark and are not clickable

### ISSUE THREAD

**Issue by RamizSami** [mapbox/mapbox-gl-js#6319]
Hey. I am adding some data through GeoJSON in a Vue project using https://github.com/phegman/vue-mapbox-gl but some of the polygons appear dark (the same color as outline) and are not clickable. For example this GeoJSON feature: https://dpaste.de/exLL appears like this:
![image](https://user-images.githubusercontent.com/15404125/37307728-a92a06a4-265d-11e8-8e53-f7dff8013325.png)
The above feature is of the same color as its outline and it is not clickable. While some polygons appear normal like this:
![image](https://user-images.githubusercontent.com/15404125/37307795-de92afc6-265d-11e8-940b-d3cdec3eaad1.png)
and these are also clickable. By clickable I mean that click event on dark features is not working and that on light features is working. Is there anything that I am missing? The Geojson also appears to be valid on http://geojson.io/ and http://geojsonlint.com/ but on the map, this issue occurs.

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?

By the way, the GeoJSON feature at https://dpaste.de/exLL doesn't match the screenshot you posted. On geojson.io it looks like this:

![image](https://user-images.githubusercontent.com/98601/37308861-724def08-25fc-11e8-9ea4-6e5bbf271bfc.png)

**Comment by RamizSami** [comment]
Hey John. Thanks a lot for quick reply. And sorry I posted the wrong GeoJSON. Here is the correct link: https://dpaste.de/YzxV#L1
Also, would the live development link of the project (http://35.171.197.91:8080/) work or I still need to reproduce the issue on jsbin.com?

**Comment by jfirebaugh** [comment]
Thanks! No need for jsbin, I can see the issue from the updated paste: the `MultiPolygon` geometry contains two copies of the same identical outer ring. So this is a data issue, not a GL JS issue.

**Comment by RamizSami** [comment]
Thanks a lot for the help John. I understand it now. Will keep asking if I run into more issues :)
