### ISSUE TITLE
Evaluating MapboxGL code in Phantomjs

### ISSUE THREAD

**Issue by aaaaahaaaaa** [mapbox/mapbox-gl-js#6321]
Hi,

I'm displaying a map inside an Angular 5 application. The app is generated with Angular CLI and uses Webpack and Karma as a test runner.

I need my tests to run in a headless browser (PhantomJS), but I get the following error when it hits my mapbox-gl code:
```
PhantomJS 2.1.1 (Mac OS X 0.0.0) MapComponent should create FAILED
        TypeError: undefined is not an object (evaluating 'this.painter.resize') in http://localhost:9876/_karma_webpack_/vendor.bundle.js (line 71189)
        resize@http://localhost:9876/_karma_webpack_/vendor.bundle.js:71189:5632
        e@http://localhost:9876/_karma_webpack_/vendor.bundle.js:71189:3161
        ...
```
I imagine it has to do with WebGL obviously not being part of Phantomjs. Could there be a solution?

**Comment by jfirebaugh** [comment]
Yep, Mapbox GL JS requires WebGL and thus cannot be used in PhantomJS. See #5026, #4199, #3436 for suggestions for testing.

**Comment by aaaaahaaaaa** [comment]
Thank you.
