### ISSUE TITLE
Bug: Fill Extrusion merge sometimes different tile zoom levels

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#6322]
For Layer Typ Fill Extrusion i get the following problem:
At a specific zoomlevel the layer show a low resolution or maybe a merge of different zoom levels of this layer. It also happens at bearing or changing the vertical angle. This doesnt't happen by using fill type as layer type.
It also didnt happen if i limit the min z to level 13 by using tippecanoe. I doesn't set any other parameters

type = fill extrusion
![image](https://user-images.githubusercontent.com/7572377/37368012-407b1cc6-2705-11e8-8d6b-675ced799afc.png)

type = fill
![image](https://user-images.githubusercontent.com/7572377/37368018-45e1c444-2705-11e8-9702-9d9119d3d55b.png)

**Comment by lbud** [comment]
@strech345 it's hard to see exactly what the issue is from those screenshots. Could you please provide a minimal self-contained JSFiddle reproducing the issue?
