### ISSUE TITLE
"icon-image": "{class}_11"  --- are not loading in Map

### ISSUE THREAD

**Issue by sudipbarman1** [mapbox/mapbox-gl-js#6329]
**mapbox-gl-js version**: 0.36.0

### Steps to Trigger Behavior
I am reading map from pbf vector file for mapbox-gl-leaflet for offline suport. 
Able to load pbf files and applied styling on it. 
But failing to show the "icon-image", declare in map file (bright-v9.JSON). In this file   "sprite":   "glyphs":  are provided as local reference.  but "icon-image" is not loading.

  "sprite": "https://iqind030/EnterpriseDesktop/offline/vectorFinal/openMapJson/sprite/sprite",
  "glyphs": "https://iqind030/EnterpriseDesktop/offline/vectorFinal/openMapJson/glyphs/{fontstack}/{range}.pbf",

Full Style File: https://gist.github.com/anonymous/e77cfc3cbce09987b5a1a3dd1e91ff4a

Need small help in this. Struggling from few days but no success.

Thanks,
Barman

**Comment by anandthakker** [comment]
Thanks for using Mapbox, and sorry to hear you're running into this issue. Could you please provide self-contained example reproducing this issue?   Having an example to work with will make it much more likely that we can successfully diagnose and solve the problem.
