### ISSUE TITLE
order Layer, Pinpoint or Point over Polygon

### ISSUE THREAD

**Issue by rbinsztock** [mapbox/mapbox-gl-js#6343]
Hi, I am actually using AngularJS component, one to render Point, one to draw Polygon and one for the map.

I create a new geojson data for each pinpoint or polygon associated to an id.

The main problem is the Point or pinpoint is always displayed under the Polygon on the map. I tried to change z-index property of the Point or Pin with map.setLayoutProperty but it does not have any effect on the map canvas.

it's weird that we can't specify which level of display the layer will have on the map.

Does it exist a way to globally order Layer on the map ?
Do I need to create a global layer on the component map and manage all my layers here instead of create a new layer for each polygon or point inside each components ?

Thank you :)

**Comment by mourner** [comment]
Layers are drawn in the order they are set in the style. You can move layers using `map.moveLayer(id, beforeId)` method: https://www.mapbox.com/mapbox-gl-js/api/#map#movelayer
