### ISSUE TITLE
Wrong map

### ISSUE THREAD

**Issue by EagleDangar** [mapbox/mapbox-gl-js#6358]
Hello,
          Why is mapbox showing wrong India's map? Could you fix it, please?
![capture](https://user-images.githubusercontent.com/22347619/37565842-da468e9c-2ad6-11e8-910e-44a66ea856b8.PNG)

**Comment by jingsam** [comment]
Please use [mapbox-gl-boundaries](https://github.com/mapbox/mapbox-gl-boundaries) plugin to solve territorial disputes.
