### ISSUE TITLE
CORS problem for Geoserver TMS (pbf) layer.

### ISSUE THREAD

**Issue by sharseema** [mapbox/mapbox-gl-js#6359]
I want to access TMS (pbf) layer from Geoserver in Mapbox GL,however i am getting CORS error.How to solve CORS error using coding to render TMS (pbf) layer in Mapbox GL .
  Actually i dont have any server side access, so i want to solve CORS problem using Coding only.I solved CORS problem for WFS layer Using Ajax but the ajax not working for TMS layer, is there any solution for TMS CORS. Thanks

**Comment by jfirebaugh** [comment]
Server-side support for CORS is a requirement. You'll need to work with the server administrator to enable CORS. There isn't a client-side workaround possible.
