### ISSUE TITLE
can text be on top of fill-extrusion

### ISSUE THREAD

**Issue by dbskccc** [mapbox/mapbox-gl-js#6360]
thanks for the fill-extrusion type layer, but it only show the shape, can it show some text(icon) on top of it through property?
![text_top](https://user-images.githubusercontent.com/15682369/37574741-0e66b698-2b5e-11e8-9851-3250c76b440f.png)

**Comment by jingsam** [comment]
Would be possible if you set the map with a lower pitch, such as 5 or 10.

**Comment by jfirebaugh** [comment]
@dbskccc I'm not sure if I completely understand the question, but text and icons in Mapbox GL JS are rendered with [symbol layers](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol). You can add a symbol layer in addition to the fill extrusion layer to show text and icon on top of extrusions.

Also, note that this issue tracker is for reporting bugs and feature requests. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). Thank you!
