### ISSUE TITLE
Text distorts when "text-max-width" is set to 0 and the string exceeds a certain width

### ISSUE THREAD

**Issue by james-wagner11** [mapbox/mapbox-gl-js#6368]
![image](https://user-images.githubusercontent.com/5375270/37676151-217c74b0-2c45-11e8-895f-09460a4e4c8d.png)

**mapbox-gl-js version**: v0.44.1

### Steps to Trigger Behavior

 1. Create a symbol layer with a text field (roughly 40-50 characters or longer)
 2. Set "layout"."text-max-width" to 0
 3. Optional: set "layout"."text-anchor" to "left" or "right" (this causes the distortion to happen sooner than with "center")

Here is a fiddle: [jsfiddle.net/nog8ko0o](https://jsfiddle.net/nog8ko0o/)

Thanks!

**Comment by jfirebaugh** [comment]
Thanks for the report @james-wagner11 (and especially for including a fiddle)!

It looks like this might be another case of #1531. @ChrisLoer can you confirm?

**Comment by ChrisLoer** [comment]
Yup, it's the same issue. As a first approximation, your label can't be wider than a tile, although the limit can be significantly less if the anchor is near a tile boundary.

@james-wagner11, could you comment on #1531 with some more information on your use case? Although this limitation is in some ways fundamental to the way we render tiles, we can increase the drawable width by reducing the (currently quite high) precision we use for glyph positioning. If doubling the allowable label width unlocks some useful behavior, we'll probably want to do it.
