### ISSUE TITLE
Is it possible to have s̶t̶r̶i̶k̶e̶t̶h̶r̶o̶u̶g̶h̶ text?

### ISSUE THREAD

**Issue by donnyv** [mapbox/mapbox-gl-js#6369]
I was looking through the style API and noticed there is no "text-decoration" option to add a strike through the text. Am I missing something or is this not currently possible?

**Comment by mourner** [comment]
Currently not possible, and as far as I know, there's no interest in implementing this at the moment. So I'll close for now.
