### ISSUE TITLE
Listeners do not take into account text-rotate layout property

### ISSUE THREAD

**Issue by navenedrob** [mapbox/mapbox-gl-js#6373]
**mapbox-gl-js version**: 0.44.1

### Steps to Trigger Behavior

https://jsfiddle.net/mjt9xqxy/4/

### Expected Behavior

Listener should work when clicking text, even if rotated.

### Actual Behavior

Toggle area for listener is misplaced and does not take into account text-rotate. See example.

**Comment by anandthakker** [comment]
Thanks for the report and clear reproduction @navenedrob 🙇 !

I believe this is the same underlying issue as #6075 -- let's track it there.
