### ISSUE TITLE
add clusterMinSize configuration

### ISSUE THREAD

**Issue by abdallahhamdy** [mapbox/mapbox-gl-js#6374]
Could you consider adding a clustering feature to set clusterMinSize along with clusterMinZoom and Radius
this way we can preconfigure the allowed minimum size of a cluster, that would prevent clustering pairs which really shouldn't be

**Comment by mourner** [comment]
No plans to implement this at the moment. I think it's fine to cluster pairs.

**Comment by mourner** [comment]
> And may I remind you that Mapbox is a paid service, would be nice if these sort of ideas are not so easily discarded.

May I in turn remind you that Mapbox GL JS is an open source project of incredible scope and complexity, and a handful of contributors are working their asses off to maintain it in good health while prioritizing many hundreds of feature requests and trying to contain complexity growth and parity with the mobile SDKs. Submitting a thoughtful pull request might help us reconsider; scornful comments certainly won't.

**Comment by mourner** [comment]
Re-evaluated, adding this feature in #9748.
