### ISSUE TITLE
Label placement line

### ISSUE THREAD

**Issue by tomass** [mapbox/mapbox-gl-js#6382]
**mapbox-gl-js version**: 0.44.1

## Motivation
Nice way of putting labels for polygon objects (f.e. lakes) is to rotate (and probably curve) the label along the centerline of a polygon (rough idea is described here: https://bl.ocks.org/veltman/403f95aee728d4a043b142c52c113f82). This centerline curve is calculated on data side and provided as a line object (calculation of such centerline is out of the scope of this issue).

Currently there is no way to nicely label such "center" lines. mapbox-gl-js places labels on seemingly random(?) place on the line:
![paveikslas](https://user-images.githubusercontent.com/969513/37797203-dca097fc-2e21-11e8-9e6d-ce0c9d0da7ad.png)
In this example centerline is simplified to the limit, making it a simple straight line with two nodes (in order to avoid problems because of large changes in azimuth etc.). Everything in this picture is in one tile (no boundary crossing). Transparent red line is the "centerline". Blue text is Symbol layer drawn on such centerline with style defined as:

      <...>
      "layout": {
        "text-field": "{name}",
        "symbol-placement": "line",
        "text-font": ["Roboto Condensed Italic"],
        "text-size": 18,
        "text-justify": "center",
        "symbol-spacing": 1000,
        "text-anchor": "center"
      },

Position of label is to the left (top) of the center on the leftmost and center lake, more or less at the center for the rightmost lake. It would be good to have a possibility to request a label to be drawn in the center of the centerline (_text-justify: center_ apparently has no effect here).

It would also be good to have a possibility to request that only one label be drawn for such centerline without resorting to impossibly large values for _symbol-spacing_.

Nice to have: if part of the centerline is outside of the viewport, center could be calculated only for visible part of the centerline.

## Design

My suggestion:
1. _"text-justify": "center"_ should do as it says - draw label in the center.
2. _"text-single" "true"_ - could be added to request that only one label be drawn per object/tile.

**Comment by stevage** [comment]
Just wanted to clarify based on my understanding of what you're proposing: An option to allow a single label to be placed on a line, such that the midpoint of the label is halfway along the line. (Trying to avoid the ambiguous word "center')

If so, you should probably change the title, as it has nothing to do with polygons. (Although I understand the primary motivation is for labelling polygons, indirectly.)

I can see several other ways to indicate this in the style spec:

- `symbol-placement: line-midpoint`
- `symbol-spacing: 0` (to indicate that the symbol is not repeated, and could default to the midpoint)

I'm not sure tying it to `text-justify` is right. For starters, this probably applies equally well to icons. But maybe it could be used in combination with `symbol-spacing: 0` to indicate whether the single label should be at the left, middle or right.

It might be nice to be flexible enough to allow another desirable option, which is placing a single label, with automatically calculated letter spacing such that the label covers the entire line. (Maybe `text-justify: justify` or `text-justify: fill`).

**Comment by nickidlugash** [comment]
See https://github.com/mapbox/mapbox-gl-js/issues/5061

**Comment by tomass** [comment]
@nickidlugash #5061 does look to be solving the same problems. I'm fine with closing this issue.
