### ISSUE TITLE
Incorrect cross-fading at non-integer zoom levels

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#6390]
http://jsbin.com/gatejucoti/edit?html,output

![crossfade](https://user-images.githubusercontent.com/2425307/37857524-c847f06a-2eb8-11e8-97c7-d8a1abd19131.gif)

This is because the crossfade interpolation factor `t`  is designed to cross-fade the property across integer zoom levels, so when you have a non-integer zoom level, the `from` and `to` values of the `CrossFadedProperty` will be incorrect at integer zooms after a non-integer stop. 

I think we should disallow non-integer stops for these properties, because they're non-interpolatable so they won't work anyways with data-driven expressions, so I think it may cause confusion if they're supported for camera expressions. 

@nickidlugash @natslaughter do you have strong feelings about this?

cc @ansis @anandthakker

**Comment by natslaughter** [comment]
@mollymerp I don't recall ever trying to switch a line pattern between integer z-levels, where this cross-fade issue appeared, and can't think of a use case when switching patterns between z-levels would be necessary. 
I don't have any strong opinions on disallowing this. 

cc @nickidlugash

**Comment by ansis** [comment]
I agree, integer-only stops make sense here.
