### ISSUE TITLE
Modernize distributed bundle

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#6391]
IE 11 is the only browser we target that doesn't support the ES2015 that we currently compile to ES5:

<img width="487" alt="screen shot 2018-03-19 at 3 07 34 pm" src="https://user-images.githubusercontent.com/4974151/37857605-d39665f4-2ed2-11e8-8513-1b665b73d9f7.png">

_Via babel-preset-env.  According to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment), Edge does support basic destructuring, just not 'rest' for arrays/objects._

I propose that we:
 - Modernize our main bundle (`dist/mapbox-gl.js`, `https://api.tiles.mapbox.com/mapbox-gl-js/VERSION/mapbox-gl.js`) to un-transpiled ES2015 code.
 - Continue to support IE 11 by distributing a separate compatibility bundle as `dist/mapbox-gl.ie11.js` / `https://api.tiles.mapbox.com/mapbox-gl-js/VERSION/mapbox-gl.ie11.js`.

There are benefits to a modernized bundle for users who don't need IE 11 support:
 - It'll be a bit smaller -- not tons, but with a 500K+ bundle, every bit counts.
 - If it's not already faster, I think it will be soon: it seems pretty likely that JS engines will start including optimizations that are specific to ES2015 constructs that wouldn't apply to their ES5-compiled counterparts.

(We could also do this the other way: keep `dist/mapbox-gl.js` as-is, but start destributing `dist/mapbox-gl.es2015.js` or something)

**Comment by andrewharvey** [comment]
While I like the idea, I think it makes more sense to be opt in (es2015 build) for the time being rather than opt out (ie11 build). I still see a fair amount of users on IE11 or on outdated Chrome/Firefox builds.

**Comment by anandthakker** [comment]
> it seems pretty likely that JS engines will start including optimizations that are specific to ES2015 constructs that wouldn't apply to their ES5-compiled counterparts.
 
One example of such an optimization: looks like object spread syntax will be faster than a transpiled equivalent (or Object.assign) in v8: https://twitter.com/bmeurer/status/1015105293301280768
