### ISSUE TITLE
TMS 3D rendering

### ISSUE THREAD

**Issue by sharseema** [mapbox/mapbox-gl-js#6396]
Hi,
I have created 3D map using TMS layer from geoserver and MapBoxGL. Normally using Mapbox style at 5 zoom level  i can able to view 3D, However, i am using Geoserver TMS layer initially at 5 zoom level i am unable to see 3D view and data is displaying in 2D. After smoothly zooming 3D data is appearing. I want to view initially whole India with 3D at zoom level 5 (this is zoom level where i can see whole India). Is it possible to see 3D view of whole India initially at zoom level 5 ?
Here is the code i tried:
`var map = new mapboxgl.Map({
    container: 'map',style:"http://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json",
    zoom:5,pitch:360,minZoom:6,center: [77,18]
});
     map.addSource('testLayer', {
            "type": "vector",
            "scheme": "tms",
            "tiles":["http://xx.xx.xxx.xxx/geoserver/gwc/service/tms/1.0.0/Cities:All_India_GDP_WGS_project@EPSG%3A900913@pbf/{z}/{x}/{y}.pbf"]
          }),
     map.addLayer({
       "id": "hessen","source": "testLayer",
       "source-layer": "All_India_GDP_WGS_project",
       'type': 'fill-extrusion',
       'paint': {'fill-extrusion-color': {'property': 'GRIDCODE',"type":'exponential',
             "stops": [[1, "#1e90ff"],[7, "#1e90ff"]
       'fill-extrusion-height':{"type": "exponential","property": "GRIDCODE",
                "stops":[[1,1000],[7,7000]]},
            'fill-extrusion-base': {"type": "interval","property": "GRIDCODE",
                "stops":[[0,1000]]},'fill-extrusion-opacity':1}});
`
Thanks.

**Comment by mourner** [comment]
Can you make a live test case (e.g. on JSFiddle) for your issue? Otherwise we won't be able to diagnose the problem, especially given that it uses a third-party vector tile source.

**Comment by sharseema** [comment]
Hi ,
I have added code in code-pen,but its not working,may be cors problem.
Check Code pen  [Link](https://codepen.io/seema30fresher/pen/aYLYZg).

**Comment by sharseema** [comment]
![image](https://user-images.githubusercontent.com/32618906/37897553-0e994936-3104-11e8-9eac-f6414bfb0a5f.png)
In above Output i used Geoserver TMS(Mapbox Vector-PBF) layer,not display initially 3D at Zoom level 5/6.
![image](https://user-images.githubusercontent.com/32618906/37897667-53363112-3104-11e8-892e-698e942324e9.png)
In above output i use mapbox style,Display initially 3D at zoom level 5/6.
I want same result like mapbox style using  Geoserver TMS layer.

**Comment by mourner** [comment]
Looks like this is a problem specific to GeoServer implementation of Mapbox Vector Tiles, and there's nothing we can do to help on our side. You should submit an issue there.
