### ISSUE TITLE
3d object zoom

### ISSUE THREAD

**Issue by AlexandreRangel** [mapbox/mapbox-gl-js#6397]
Dear friends from Mapbox,

is this the right place for code questions?

I'm building a project based on the three.js + mappa.js + mapbox example (https://mappa.js.org/docs/examples-three-js.html) but I'd like to have a different 3d object zoom behaviour.
I'd like the 3d objects on top of the map to change the zoom level according to the map zoom, so they could keep their relative sizes to the map features. Is it possible?

Thank you!

Alexandre Rangel
www.quasecinema.org

**Comment by mourner** [comment]
> is this the right place for code questions?

Unfortunately not — this is a place for reporting issues with Mapbox GL JS specifically. You could try StackOverflow or ask the author of the Mappa example.
