### ISSUE TITLE
"cluster": true is not creating 'point_count' attribute?

### ISSUE THREAD

**Issue by stevew2511** [mapbox/mapbox-gl-js#6398]
mapbox-gl-js version: 0.44.1
chrome version 59.0.3071.86 (64 bit)

Hi, I am having trouble with the cluster function. It doesn't appear to be adding the 'point_count' attribute to the geojson source that I have added via javascript. For testing purposes I am using the 'earthquakes.geojson' file. It seems that the filter option cannot see the 'point_count' attribute. If I remove the filter I can see the data and everything else works as intended i.e. 'on click' event. The javascript console shows no errors, so I'm not sure if IIS 6.0 is the problem and out of ideas on what to try next. Hope someone can help.

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?

**Comment by stevew2511** [comment]
We are using our own servers offline with our vector tiles (created via ArcGIS Pro) and the mapbox-gl api. Our server is windows 2012 R2 with IIS 6.0. I don't think the problem is with Mapbox directly, I have a feeling that it could be IIS permissions? I was hoping someone may be able to give me some tips/advice? Where does mapbox-gl write the point_count attribute? Is it in the file on the hard-drive or  memory?

**Comment by jfirebaugh** [comment]
The point_count attribute is added in memory to the features in the GeoJSON source.

If you track this down to Mapbox GL JS, we'll be happy to investigate further given a self-contained example. Closing for now.

**Comment by yumindeckard** [comment]
do you have documentation for this `point_count ` attribute?  I cannot find it.

**Comment by fantasyado** [comment]
> do you have documentation for this `point_count ` attribute? I cannot find it.

It appears that if set `withCluster(true)` then mapbox will add this attr automatically to GeoSource during runtime.
