### ISSUE TITLE
Polygons feature flicker (flash on screen) on render

### ISSUE THREAD

**Issue by rbinsztock** [mapbox/mapbox-gl-js#6400]
Hi,

I am actually using Mapbox to render sectors on map with specific paint and type options.

Each time the user select a zone I need to change the polygons on the map to display the polygon with another paint properties or type (fill or line). So I redraw all polygons on any edit.

The main problem is the rendering on the map, polygons are flashing on each redraw, does it have a way to prevent this ? What can help to fix this problem ?

![flickerpolygonsselection](https://user-images.githubusercontent.com/829378/37916101-50aff894-311b-11e8-8596-57ea7328beeb.gif)

Thank you

**Comment by mollymerp** [comment]
Hi @rbinsztock – thanks for using Mapbox and sorry you're having an issue. 
In order for us to diagnose this, we need all the information that the issue template requests and a minimal reproduction of the issue on JSbin or JSfiddle that does not include any third party or application-specific code. Thank you!

**Comment by rbinsztock** [comment]
I will close for now as it may not mapbox gl related. Will try to do a JSFiddle to reproduce the behavior.
