### ISSUE TITLE
`event` passed from map.on('moveend' missing `originalEvent` on some interactions

### ISSUE THREAD

**Issue by hryanjones** [mapbox/mapbox-gl-js#6405]
**Context**: I'm looking for a way to tell whether user interaction caused the map to move. The use case is that we use `.fitBounds` to set the initial state and when the user changes the bounding box (via scroll zoom, double click zoom, drag to pan, the navigation controls, keyboard commands, etc.) we want to persist the bounds, but we don't want to do this when it's a `fitBounds`.

Is there a way to tell that it was user initiated? The only time I've seen where I can distinguish is when I also see an `.originalEvent` property in the event in addition to `.target` which happens on some user interactions, but not on all of them.

**mapbox-gl-js version**: (using version that was in the examples on mapboxGL website)

### Steps to Trigger Behavior

1. Using HTML below with console open
2. notice that `.fitBounds` triggers the `event` and it doesn't have an `.originalEvent` property
3. notice that the event logged from these interactions have an `.originalEvent`:
  - drag
  - double click
  - if you use the keyboard +/- buttons
4. notice that `.originalEvent` is missing if you do the following:
  - click on the navigation +/- zoom buttons
  - if you scroll to change zoom

```html
<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.1/mapbox-gl.css' rel='stylesheet' />
<style>
    body { margin:0; padding:0; }
    #map { position:absolute; top:0; bottom:0; width:100%; }
</style>

<div id='map'></div>
<script>
mapboxgl.accessToken = ''; // Put your own mapbox token here

var map = new mapboxgl.Map({container: 'map', style: 'mapbox://styles/mapbox/streets-v9'});
map.fitBounds([[-133.4261895047858, 27.268363255653668], [-89.21205651435507, 46.38482102526038]]);
map.addControl(new mapboxgl.NavigationControl());

map.on('moveend', function(event) {
    console.log(event);
});
</script>
```

**Comment by soldt** [comment]
A solution would be to add eventData to the fitBounds method.

`eventData(Object)Additional properties to be added to event objects of events triggered by this method.`

Example:
```
map.fitBounds(lngLatBounds, {}, {breakonfitbounds: true});
```

Return foorbar
```
map.on('moveend', function (e) {
  if (e.breakonfitbounds) {
    return;
  }
  // Do something
});
```

**Comment by sheerun** [comment]
I'm using library that doesn't allow to pass extra args to fitBounds, it would be nice if originalEvent was passed by default by mapboxgl, currently there's no way to tell whether zoomend has beeen triggered by user or fitting bounds

**Comment by stepankuzmin** [comment]
Hi everyone!

I've created PR that adds `originalEvent` property to `NavigationControl` events. Also `originalEvent` was added to user-initiated scroll `zoomend` and `moveend` events in https://github.com/mapbox/mapbox-gl-js/pull/6175

**Comment by mourner** [comment]
@stepankuzmin what else should be covered to consider this ticket resolved?

**Comment by stepankuzmin** [comment]
I think nothing more is needed. @hryanjones can you please try to reproduce your issue with the master build of `mapbox-gl-js`?

**Comment by mourner** [comment]
OK, let's close for now and reopen if there are any more items left to do.

**Comment by derwaldgeist** [comment]
Is there already a release including this?

I stumbled upon the problem here
https://github.com/urbica/react-map-gl/issues/276

If I understand things correctly, this missing event causes `react-map-gl` not to report back viewport changes after clicking on the GeolocationControl. Which feels pretty weird because the zoom gets out of sync.
