### ISSUE TITLE
Avoid transitive dependency on JSV

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#6406]
Updated: `jsonlint-lines-primitives` includes a dependency on JSV, which has a <a href="https://github.com/garycourt/JSV/issues/94">malformed package.json</a> that breaks some downstream tooling.  That dependency only appears to be used by jsonlint's CLI, so we don't need it. We should eliminate the transitive dependency.

<details>
<summary>(Original comment)</summary>
<div class="comment-body markdown-body js-preview-body" style="min-height: 381px;">
We should remove the dependency on <code>jsonlint-lines-primitives</code> package:</p>
<ul>
<li><a href="https://github.com/search?l=JSON&amp;q=jsonlint-lines-primitives&amp;ref=opensearch&amp;type=Code">As far as I can tell</a>, it's a fork of <a href="https://github.com/zaach/jsonlint">https://github.com/zaach/jsonlint</a> that is not backed by a repo on GitHub (cc <a class="user-mention" data-hovercard-user-id="32314" href="https://github.com/tmcw" aria-describedby="hovercard-aria-description">@tmcw</a> - do you remember if this is accurate?)</li>
<li>Linting JSON itself is out of scope</li>
<li>We really only use this to get line numbers for style validation errors.  Since we already track a key path (e.g. <code>layers[0].paint.fill-color</code>), we could reconstruct line numbers using that information if need be.</li>
</ul>
<p>Prompted tangentially by an issue that came up where one of jsonlint's dependencies, JSV, has a <a href="https://github.com/garycourt/JSV/issues/94">malformed package.json</a> that breaks some tooling.</p>
</div>
</details>

**Comment by anandthakker** [comment]
> one of jsonlint's dependencies, JSV

Note that jsonlint appears to only use JSV in its CLI tool, which we don't need.

**Comment by anandthakker** [comment]
>  that is not backed by a repo on GitHub

Wrong, here it is: https://github.com/tmcw/jsonlint/tree/lines-primitives

**Comment by tmcw** [comment]
Seems fine to remove it, though reconstructing line numbers based on a path like `layers[0].paint.fill-color` might be of similar or higher complexity than retaining line numbers in the datastructure, as jsonlint-lines-primitives currently does.

**Comment by anandthakker** [comment]
Indeed -- I was overly optimistic about a simpler json-parser-with-source package already existing.  

Since the JSV dependency is the only immediate issue, going to refocus this issue on just removing that dependency.

**Comment by anandthakker** [comment]
Created https://github.com/mapbox/jsonlint/pull/1 to serve as a cli-less fork of this package that we can publish under `@mapbox/jsonlint`
