### ISSUE TITLE
Style-spec Filter link broken

### ISSUE THREAD

**Issue by tobrun** [mapbox/mapbox-gl-js#6407]
The link on the left pane to navigate to the filters section seems to be broken:

<img width="1398" alt="screen shot 2018-03-27 at 11 06 20" src="https://user-images.githubusercontent.com/2151639/37976263-178f5174-31af-11e8-8205-026a64e4bc9a.png">

It currently redirects to:
 - https://www.mapbox.com/mapbox-gl-js/style-spec/#other-filter-deprecated-syntax

While it should be:
 - https://www.mapbox.com/mapbox-gl-js/style-spec/#other-filter

**Comment by jfirebaugh** [comment]
Fixed in #6408.
