### ISSUE TITLE
Animate points along a route with multiple markers

### ISSUE THREAD

**Issue by vathsanvk** [mapbox/mapbox-gl-js#6410]
How do I use Animate point along a route with multiple points keeping browser performance in mind?

e.g. https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-route/

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
