### ISSUE TITLE
MapBox Marker lng_lat.js throws error on valid latitude

### ISSUE THREAD

**Issue by tetreault** [mapbox/mapbox-gl-js#6413]
### Steps to Trigger Behavior

 1. Create a mapboxgl.Marker 
 2. have setLngLat take a negative valid latitude less than -90
 3. error gets thrown about invalid latitude

```
            data[1].coords = [24.0755, -110.3637]; // correct lat long for La Paz in Baja California Sur
            const elStop2 = document.createElement('div');
            elStop2.className = 'marker';
            const elStop2inner = `
              <ul>
                <li>
                  <img src="img/mapbox_marker_plane_symbol.svg"><p>${data[1].destCity}</p>
                </li>
                <li>
                  <p class="leave-time">${data[1].departTime}</p>
                </li>
                <li>
                  <p>${data[1].price}</p>
                </li>
              </ul>
            `;
            elStop2.innerHTML = elStop2inner;
            new mapboxgl.Marker(elStop2)
             .setLngLat(data[1].coords)
             .addTo(map);

            elStop2.addEventListener('click', (e) => {
               e.preventDefault();
               alert('clicked mapBoxStop2!');
            });
```

### Expected Behavior
I expect the marker to be added at the given lat/long, since that is a valid lat/long for La Paz. 

Google Maps reference: https://www.google.com/maps/place/24%C2%B004'31.8%22N+110%C2%B021'49.3%22W/@24.6427284,-111.8833102,7z/data=!4m5!3m4!1s0x0:0x0!8m2!3d24.0755!4d-110.3637

### Actual Behavior

It throws an error saying the latitude is invalid because it isn't between 90 & -90. 

<img width="729" alt="screenshot 2018-03-28 10 37 50" src="https://user-images.githubusercontent.com/5934354/38036156-16f19a22-3274-11e8-977b-0435e2f8e71c.png">

Apologies for not being able to make a more cohesive demo, as this is part of a bigger client project. However, this was functional if I use other lat/long coords, but throws an error on this valid lat/long for La Paz.

**Comment by jfirebaugh** [comment]
You've got latitude and longitude reversed in the `setLngLat` call. As indicated by the name, it takes longitude first, latitude second: `setLngLat([-110.3637, 24.0755])`.

**Comment by tetreault** [comment]
wow, very stupid mistake on my part... its one of those mornings. Sorry @jfirebaugh - thx for the response!
