### ISSUE TITLE
It blinks too much

### ISSUE THREAD

**Issue by Jinkwon** [mapbox/mapbox-gl-js#6418]
**mapbox-gl-js version**: Latest version

### Steps to Trigger Behavior

 1. no steps

### Expected Behavior
No more blink.

### Actual Behavior
Blink like my eyes.

![blink](https://user-images.githubusercontent.com/1798916/38072302-a098ed24-3360-11e8-849d-c8e0dd176c82.gif)

**Comment by mourner** [comment]
Duplicate of #6315. The fix is in the works.

**Comment by Jinkwon** [comment]
Resolved at v0.45.0
