### ISSUE TITLE
double-tap-to-zeoom breaks when handling both touch and mouse events...

### ISSUE THREAD

**Issue by jliebrand** [mapbox/mapbox-gl-js#6420]
We have added a "long press" handler on our map, which we want for both desktop and mobile devices. To do this, we listen for the 'touchstart' and the 'mousedown', and start a timer when either happens. We call evt.originalEvent.preventDefault() when receiving the touchStart event, to avoid (on touch devices) both the mouse and the touch events from kicking off timers (or doing any other duplicate handling).

This works fine, except that it appears to break the default double tap to zoom behaviour from mapbox?

I don't really want to add flags in my code on touchstart (to then ignore the mouse events), because we also need to support devices that have both touch and mouse (surface, pixel, etc). So we can't just blatantly ignore all mouse events just because a touch event happened. This is where preventDefault on the touchstart is ideal, because it prevents THAT touch event from also firing a mouse events, but it does not prevent future mouse-only events...

Any recommendations on how to best handle both touch and mouse devices (and touch+mouse devices) ?

**Comment by jliebrand** [comment]
for reference:
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent

**Comment by jfirebaugh** [comment]
> add flags in my code on touchstart (to then ignore the mouse events)

This sounds like the right approach to me. You don't necessarily need to completely _ignore_ subsequent mouse events if there's other things that might happen in response -- just avoid restarting the timer. (And of course reset the flag once the timer completes.)

**Comment by jliebrand** [comment]
I appreciate you have a lot of logic in place that relies on the event not having been prevented, but i'm not convinced this is the correct approach. For users with a touch&mouse device (Google Pixel, or MS Surface), there are two use cases:

1- the user tapped (touch) the screen
2- the user click with their mouse

To support both cases, we need to know during the mousedown event IF that event resulted from a touchstart event, or not. And since events are asynchronous, it's not as simple as setting a flag during the touchstart - we also need to clear the flag. We also can't clear the flag on touchend because that fires before the mouse events.

So in order to handle this, we have to put some rather ugly hack in place like this:

```
function onTouchStart() {
    this.ignoreMouse_ = true;
    window.setTimeout(() => {
      this.ignoreMouse_ = false;
    }, 10);
}
```

Notice the 10ms delay... that is clearly bound to screw up at some point, but I don't see any other way of determining when to ignore mouse events and when not to ignore them.

**Comment by jfirebaugh** [comment]
But you're already starting such a timer -- you said in the original post you "start a timer when either happens". So what's wrong with resetting the flag when that timer completes?
