### ISSUE TITLE
Bite sized chunk out of Van Ness

### ISSUE THREAD

**Issue by aparlato** [mapbox/mapbox-gl-js#6421]
**mapbox-gl-js version**: 0.44.1

### Steps to Trigger Behavior

 1. Zoom in on Van Ness Avenue on z12 (starts z12 ends z13) here:
![image](https://user-images.githubusercontent.com/15698320/38097731-06503f72-332b-11e8-88eb-1614dcb32f5f.png) in a style with roads styled with line-width (just look at Streets or any style really)

### Expected Behavior

- line is styled as intended and has consistent width.

### Actual Behavior

- line has dent in one side of it at this particular point.

**Comment by lbud** [comment]
😮 
That doesn't _look_ like a rendering bug, actually. The OSM data looks suspicious here, with a little weird extra space between the two sides: https://www.openstreetmap.org/way/397116938#map=17/37.77661/-122.41844
![image](https://user-images.githubusercontent.com/3170312/38106931-645fa890-3345-11e8-89d9-6a0c97c1a531.png)

I suspect this is some kind of simplification issue? @ian29 or @ajashton, does that sound right to you?

**Comment by mollymerp** [comment]
yeah I think its a data issue: 
<img width="237" alt="image" src="https://user-images.githubusercontent.com/2425307/38116421-d08cfa8a-3364-11e8-9682-dc73044bd73b.png">

something funky w the casing too only at that zoom level

**Comment by lbud** [comment]
Closing here — @aparlato please follow up on the data side 🙇‍♀️
