### ISSUE TITLE
How to get 3d buildings according to height information from geojson file?

### ISSUE THREAD

**Issue by pallyra1** [mapbox/mapbox-gl-js#6426]
Hey,
I have a geojson file which has height information of all the features. I added the geojson in tilesets in mapbox studio. Upon visualising the map, the buildings are still in 2d. How to use the height information in geojson file? A portion of geojson file is as follows : 

`{"type":"FeatureCollection",
"features":[{
"type":"Feature",
"properties":{"color":"#ffffff","height":25,"minHeight":18.5},
"geometry":{
"type":"Polygon",
"coordinates":[[[13.396574,52.521638],
[13.395243,52.520942],
[13.395511,52.520753],
[13.396841,52.521449],
[13.396707,52.521544],
[13.396601,52.521619],
[13.396574,52.521638]]]},
"id":"o2-COM-CEIL_6644-8864167-Default_Material"},`

I want all the buildings according to the height in geojson file.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
