### ISSUE TITLE
map.hover() a shorthand for mouseenter + mouseleave

### ISSUE THREAD

**Issue by samsammurphy** [mapbox/mapbox-gl-js#6431]
## Motivation

Reduce the amount of code required for effecting change when hovering over a layer. For example, the standard way to change the mouse cursor might look something like this:

```
    map.on('mouseenter', 'polygon_layer', function () {
        map.getCanvas().style.cursor = 'pointer';
    });

    map.on('mouseleave', 'polygon_layer', function () {
        map.getCanvas().style.cursor = '';
    });
```

## Design Alternatives

The proposed feature is syntactic sugar, so do nothing is an option.

### Mock-Up

JQuery has a nice shorthand for this functionality via [hover()](https://api.jquery.com/hover/). It would be cool if something like that was implemented in mapbox, e.g.:

```
    map.hover('polygon_layer', function () {
            map.getCanvas().style.cursor = 'pointer';
        });
```

### Implementation

I would create a small wrapper function for the 'mouseenter' and 'mouseleave' event handlers.

**Comment by jfirebaugh** [comment]
Hi @samsammurphy, thanks for the suggestion! Making hover behaviors easy is definitely something we're interested in doing. You can follow our current work on this in #6019 and #6021.

**Comment by samsammurphy** [comment]
Thanks @jfirebaugh
