### ISSUE TITLE
Fill-color expected odd number of arguments

### ISSUE THREAD

**Issue by KonWoj** [mapbox/mapbox-gl-js#6434]
I try to change fill colours basing on attribute, but i have to perform mapping values, so i done this: 
const max_expr =['max', ['get', 'att1'], ['get', 'att2']];
And in layer:
'fill-color' : ['case', ['==', max_expr, 1], 'red', ['==', max_expr, 2], 'blue']
But i get fill-color: expected odd number of arguments

**Comment by brncsk** [comment]
You have to provide `case` with a default choice as its last argument, e.g.:

```js
{
  ...
  "fill-color" : [
    "case",
    ["==", max_expr, 1], "red",
    ["==", max_expr, 2], "blue",
    "black"
  ]
}
```

**Comment by anandthakker** [comment]
👍 @brncsk 's answer is correct.  I'm closing here, but opened https://github.com/mapbox/mapbox-gl-js/issues/6437 to track improving this error message, which was definitely not nearly as helpful as it could have been!
