### ISSUE TITLE
Layer with "Icon-offset" does not trigger mouseenter/click event (0.44.1)

### ISSUE THREAD

**Issue by benderlidze** [mapbox/mapbox-gl-js#6436]
I have 2 layers with mouse events - circle and symbol (some icon for circle)
And when I use 
 "icon-offset": [-500, 0],
the symbol layer does not triger the mouseenter/click event
Here is a fiddle http://jsfiddle.net/5xdmpthw/1/

But when I set the offset to  "icon-offset": [-200, 0](actually it overlaps the circle layer now) it is ok, the event is triggered, but I don't want to overlap the circle layer
I have tried it with 0.42.2 and it looks ok but got some other bugs.
Any help? Thanks.

**Comment by anandthakker** [comment]
Thank you for the report and the isolated test case!  This was fixed in https://github.com/mapbox/mapbox-gl-js/pull/6135, which will be included in the forthcoming 0.45 release.  (Confirmed locally that the issue does not appear on `master`)
