### ISSUE TITLE
Next Release dates

### ISSUE THREAD

**Issue by dave11mj** [mapbox/mapbox-gl-js#6451]
**mapbox-gl-js version**: `0.44.1`

### Steps to Trigger Behavior

 1. Visit https://www.mapbox.com/mapbox-gl-js/roadmap/
 2. Look for release dates
 3. Notice there isn't any

### Expected Behavior
Documentation on how often or when will new releases be available.

### Additional Comments
Hello!

It seems in version `0.44.1` it does not allow you pan while zooming (panning stops working as soon as a 2nd touch events is registered). I couldn't find an issue on the github issues page specifically related to multi touch panning while zooming, but when I forked the repo and did a standalone build it seems to have being resolved. I see the last release was in February 13, and there seems to be periodical releases, so I was wondering if there are release dates documented somewhere, since I couldn't find any on roadmap website.

Thanks !

**Comment by jfirebaugh** [comment]
We're preparing a release right now.

**Comment by dave11mj** [comment]
Cool ! thanks for the quick reply xD !
