### ISSUE TITLE
Calling map.remove() on map with hash set to true throws 'can't read property getCenter of undefined'

### ISSUE THREAD

**Issue by allthesignals** [mapbox/mapbox-gl-js#6452]
JSBin: https://jsfiddle.net/c9dmmc37/7/

This can randomly fail certain acceptance test suites.

Version: **0.44.1**:

### Steps to Trigger Behavior

 1. Enable `hash: true`
 2. Call `map.remove()`
 3. Check console.log

### Expected Behavior
I can call `remove()` with a hash-enabled map without console errors. This can sometimes throw off automated testing frameworks.

### My User Agent
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36

### Full stack trace
<details/>

```
hash.js:55 Uncaught TypeError: Cannot read property 'getCenter' of undefined
    at Hash.getHashString (hash.js:55)
    at Hash._updateHashUnthrottled (hash.js:93)
    at r (throttle.js:15)
Hash.getHashString @ hash.js:55
Hash._updateHashUnthrottled @ hash.js:93
r @ throttle.js:15
setTimeout (async)
r @ throttle.js:16
(anonymous) @ throttle.js:24
Evented.fire @ evented.js:93
i.jumpTo @ camera.js:501
e @ map.js:326
window.onload @ (index):87
load (async)
(anonymous) @ (index):84
```

</details>

**Comment by chriswhong** [comment]
The error happens when `getHashString()` tries to `getCenter()` from a non-existent map.  Seems like we just need to check for the existence of the map in `getHashString()`, or check for it in ` _updateHashUnthrottled()` and never call `getHashString()` at all.  Should the hash just be an empty string if the map does not exist?


```   
 _updateHashUnthrottled() {
        const hash = this.getHashString();  
        window.history.replaceState(window.history.state, '', hash);
    }
```

**Comment by chriswhong** [comment]
On further examination, it seems to only throw this error if you remove the map immediately after creating it.  

https://jsfiddle.net/c9dmmc37/14/

This fiddle adds a 1 second setTimeout to the `map.remove()` and there is no error.

**Comment by allthesignals** [comment]
@andrewharvey https://github.com/mapbox/mapbox-gl-js/pull/6490 <-- put one together here, but I'm not quite sure how to take care of some of the housekeeping tasks in your PR workflow.
