### ISSUE TITLE
marker.remove() not working on marker with custom Element and svg inside

### ISSUE THREAD

**Issue by Liquid2Sky** [mapbox/mapbox-gl-js#6457]
Hello,
I am a little bit unsure if it is a bug or expected / known behavior but it feels like a bug :-D 
I tried to create a set of custom marker with fontawesome icons but was unable to remove a marker once it was displayed on the map. I created a little testcase, linked below 

**mapbox-gl-js version**: v0.44.1

### Steps to Trigger Behavior
https://jsfiddle.net/LiquidSky/xr4rq9zw/19/
 1. Create Custom Marker with e.g. fontawesome icon
 2. Put it on map
 3. Call marker.remove()

### Expected Behavior
Marker get removed
### Actual Behavior
Marker stays

**Comment by jfirebaugh** [comment]
It looks like the fontawesome JS is doing some tricky DOM manipulation behind the scenes, replacing any element with a `fas` class with an SVG element. Mapbox GL JS has no way to know about this, so it just tries to remove the original div, which is no longer in the page. Try making the `fas` div a child of the div you set as marker content.
