### ISSUE TITLE
resetNorth does not fire rotate events

### ISSUE THREAD

**Issue by cephirothdy2j** [mapbox/mapbox-gl-js#6460]
Sorry, not sure if this a bug report or a feature request ... If there is a workaround to tell when the user clicks the "On Reset North" button in the [Navigation Control](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/control/navigation_control.js), I'd love to hear it.

### Expected Behavior

Given that the "Zoom In" and "Zoom Out" buttons in the navigation control fire the [`zoomIn()`](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/camera.js#L215) and [`zoomOut()`](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/camera.js#L234) methods (and thus the `zoom*` events), I would expect that clicking the "Reset North" button would either fire the `rotate*` events or a new `onResetNorth` event when it calls [`resetNorth()`](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/camera.js#L302).

### Actual Behavior

Clicking the "Reset North" button only fires the `move*` events.

**Comment by asheemmamoowala** [comment]
Clicking on the _Reset North_ button emits the `rotateend` event. If this is not working for you, please provide a minimal reproduction of the issue on JSbin or JSfiddle that does not include any third party or application-specific code. Thank you!

**Comment by cephirothdy2j** [comment]
Here is your [JSBin demonstrating the issue](http://jsbin.com/hefiqejefi/edit?html,js,output) ...

### Steps to Reproduce

1. Visit the JSBin link.
2. Enter an access token in the JavaScript panel.
3. Rotate the map either by mouse-downing on the compass button, or mouse-downing on the map while holding the control / alt key, and moving the cursor until the map is askew.
4. You will see the `rotateend` event fire in your browser's console as expected.
5. Click the compass button to return the map to north (fires `resetNorth()`). You will see that the `rotateend` event does not fire per the browser's console.

**Comment by asheemmamoowala** [comment]
@cephirothdy2j thank you for reporting this issue. It has been fixed in #6218 and will be available in the next release.

**Comment by cephirothdy2j** [comment]
Thanks, @asheemmamoowala. Running the master branch locally I am able to confirm that the issue is resolved.

FYI though `resetNorth` in [ui/camera.js](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/camera.js#L301) does not yet mention the new event(s) that will fire. 😄

**Comment by asheemmamoowala** [comment]
#6471 tracks the documentation issue.
