### ISSUE TITLE
Prevent markers from overlapping

### ISSUE THREAD

**Issue by theochampion** [mapbox/mapbox-gl-js#6462]
**0.44.2**:

Hi there, thanks for what you are doing here, it's awesome ! 👍 

I'm using [markers](https://www.mapbox.com/mapbox-gl-js/api/#marker) to display city names on my map and I'm trying the prevent them from overlapping (just like what is possible to do with a [layer symbol](https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-symbol))

Is is possible to do with the current API ? Else what would be a good way to implement this ?

Thanks !

**Comment by dagjomar** [comment]
Is there a reason why you don't want to implement it using a Layer symbol instead?

**Comment by theochampion** [comment]
@dagjomar I want to be able to use HTML to customize my markers. This is not possible with a layer symbol right ?

**Comment by andrewharvey** [comment]
see also #4491 for Marker clustering which would be able to be used to prevent Marker overlaps.

**Comment by jfirebaugh** [comment]
Markers do not support collision detection, and it's not something we're likely to add as it would add a significant amount of complexity. If you want sophisticated label layout, please use a symbol layer as @dagjomar suggests.

**Comment by arenarium-dev** [comment]
@tzvc Hey, dont know if its still relevant, but Ive been building a plugin for mapbox and other map providers that enables you to organize a large number of custom markers with HTML.

![Image](https://github.com/user-attachments/assets/e33d89da-dc1d-4ac9-9d0b-9d17439d8689)

You can chek it out at: [https://arenarium.dev/?demo=bookings](https://arenarium.dev/?demo=bookings)
