### ISSUE TITLE
Heatmap density calculation

### ISSUE THREAD

**Issue by fighterii** [mapbox/mapbox-gl-js#6463]
**mapbox-gl-js version**: v0.44.2

### Steps to Trigger Behavior

 1. https://jsfiddle.net/vw046awm/6/
 2. 10 points at the same spot; 5 points at an other spot
 3. No Clustering

### Expected Behavior
- 10 points => maximum amount of points => no weight / intensity scaling => density: 1 
resulting in an heatmap circle of color  "rgb(178,24,43)" (dark red)
- 5 points => half of the maximum amount of points => no weight / intensity scaling => density: 0.5
resulting in an heatmap circle of color between  0.4, "rgb(209,229,240)" and 0.6, "rgb(253,219,199)" (somewhere between light green and rose)

### Actual Behavior
- Both spots have the same color (the one assigned to a density of 1 "rgb(178,24,43)" (dark red))

Am i missing something here? Am i missunderstanding how a heatmap should work and calculate the density?

**Comment by mourner** [comment]
Density can go above 1 when there are many points in one spot. This is what happens here — both spots have red area inside, but you can notice that the second one has a smaller radius of red and a smoother gradient. Working as designed.

**Comment by fighterii** [comment]
@mourner : Is there a workaround, how to get a color palette which works like i expected?

I don't want to hardcode the maximum value of a spot (because data changes), so i have to get it on the go.

I have some ideas in mind, but therefore i have to get the maximum amount of heatmap-density or points in the same spot somehow. With that information "max-points" i could create a heatmap-intensity scaling with 1/max-points, resulting in a heatmap-density with the effective range of 0 to 1.

Do i have to process all points manually before? Maybe i could go with clustering, but i don't think there is a function that gets me the maximum of point_count over all clusters?

It would be nice to have a scale ranging from 0 to 100% giving me that information, so i can use a color palette which really represents my data.

**Comment by mourner** [comment]
@fighterii see #6112 for a proposal addressing this.

**Comment by fighterii** [comment]
@mourner : maybe you can have a look at my edit as well. 
But thanks, i'll have a look at the referenced issue

**Comment by fighterii** [comment]
@mourner But as explained in my edit, i think the density stays a "1" as a maximum? https://jsfiddle.net/vw046awm/10/ A color which is assigned to densities above 1 is never painted. 
So two spots with a difference of 100% in point_count both get a density of 1? 

I don't want to say you are not right and maybe the heatmap feature works as designed, but i have a hard time to understand whats going on under the hood here. And i can't understand why the heatmap is designed to work in this way (which benefit would you have from making two very different spots look alike).

**Comment by mourner** [comment]
The fact that density is capped at 1.0 is a technical limitation due to the way it's calculated (on the shader side). To see different colors for those spots, you'll have to bring intensity down. Since you can't adjust the density automatically yet, you'll have to wait for #6112 for a full solution.

**Comment by fighterii** [comment]
Thank you, now i understand completly and will find a workaround by manually changing intensity :)
