### ISSUE TITLE
Make a zoom pinch on mobile device (zoomend event)

### ISSUE THREAD

**Issue by Ruzafan** [mapbox/mapbox-gl-js#6466]
### Steps to Trigger Behavior

 1. Make a zoom pinch on mobile device
 

### Expected Behavior
Fires the zoomend event when the user stop making zoom

### Actual Behavior
Keeps permanent firing zoomend event

**Comment by jfirebaugh** [comment]
This has been fixed for the next release.

**Comment by ldfloresgon** [comment]
@jfirebaugh any news? thanks
