### ISSUE TITLE
An expression to check if an array contains a string

### ISSUE THREAD

**Issue by jc211** [mapbox/mapbox-gl-js#6473]
I have a geojson property which is an array. I would like to have an expression that checks if that array contains a certain string. 
['has', 'mystring', ['get', 'myarray']]

Is this possible currently? If not, would it be possible to make the existing 'has' expression operate on arrays as well as objects?

**Comment by anandthakker** [comment]
It's not possible currently, but I agree that it's something we should add.

**Comment by Macksen** [comment]
I recently discovered that I am in need of a similar expression, but that also takes an array input containing **multiple strings** and compares them to the values in the feature array property, is that possible to look at in the same issue?

**Comment by Twansparant** [comment]
That's too bad, is there a workaround?
What if I'm able to explode the array as a comma separated string or something?
Could I use an expression to search for the presence of the value as part of another string?
Thanks!

**Comment by anandthakker** [comment]
@Twansparant that also doesn't yet exist, but is something we're planning to add.  Most directly tracked at https://github.com/mapbox/mapbox-gl-js/pull/6228

**Comment by Twansparant** [comment]
Thanks for your replies @anandthakker!

**Comment by jfirebaugh** [comment]
Duplicate of #4698.
