### ISSUE TITLE
Canvas layer causes high CPU/GPU utilization

### ISSUE THREAD

**Issue by jakubbartel** [mapbox/mapbox-gl-js#6474]
**mapbox-gl-js version**: 0.44.1

### Steps to Trigger Behavior

 1. create canvas
 2. addSource of type canvas
 3. addLayer of type raster with the canvas source

### Expected Behavior

No HW overutilization (as in case of image source which is working properly).

### Actual Behavior

CPU and GPU goes to almost 100%. Tested on Windows 10 laptop with retina display in chrome (~100% CPU), firefox (~100% CPU), edge (~80% CPU), and on Windows 10 desktop with classic resolution in chrome (~40% CPU).

You can clearly see when website with the map was loaded.

![cpu](https://user-images.githubusercontent.com/22750048/38459318-765f3cbc-3aa8-11e8-9189-4deacef67849.png)
![gpu](https://user-images.githubusercontent.com/22750048/38459332-8fbce358-3aa8-11e8-8d44-15cac662336c.png)

The canvas source option `animate` is crucial - if set to `false` the HW utilization is gone.

Code snippet for following demo: https://jsbin.com/lurikafuzu/edit?html
Demo: with canvas http://35.205.238.108/canvas.html (the same overlay with image source http://35.205.238.108/index.html)

**Comment by jfirebaugh** [comment]
This is the expected behavior -- if `animate` is true, then it's assumed that the canvas is animated and the map will render at 60 fps. If you have a static canvas, set `animate` to false.

**Comment by jakubbartel** [comment]
Thanks for the reply!

Is there a way how to set some options to decrease the resources utilization? Or make manual refresh? We update canvas once per ~2 seconds as new data arrive, so a triggered update could be a good solution. I know play() and pause() but it doesn't seem to be a good approach for one time refresh.

**Comment by lbud** [comment]
> Is there a way how to set some options to decrease the resources utilization? Or make manual refresh? We update canvas once per ~2 seconds as new data arrive, so a triggered update could be a good solution.

Not at this time, but it would be feasible to add a method to trigger a single frame redraw. Please open a new ticket framing this as a feature request for further discussion 🙇‍♀️
