### ISSUE TITLE
My build is smaller than official build

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#6477]
Recently I checked out master branch and run `yarn build-min`. I found that my build of `mapbox-gl.js` is smaller than the official build on [unpkg](https://unpkg.com/mapbox-gl@0.44.2/dist/):

My build of `mapbox-gl.js`: 588KB
The offical build of `mapbox-gl.js`: 715.09 kB

**Comment by anandthakker** [comment]
Are you building from master?
https://github.com/mapbox/mapbox-gl-js/pull/6196, which hasn’t yet been
included in a release, reduced the bundle size.

**Comment by jingsam** [comment]
Yes, I build from the master branch.
