### ISSUE TITLE
get expression with the object falls with exception

### ISSUE THREAD

**Issue by AntonPilyak** [mapbox/mapbox-gl-js#6479]
**mapbox-gl-js version**: 0.44.2

### Steps to Trigger Behavior

 1. define an object like this:
     const object = {
          color : 'white'
     };
 2. try to use it in a get-expression like this:
{   
   'line-color': ['get', 'color', object],
   ...
}
 3. get the following exception:
   'Bare objects invalid. Use ["literal", {...}]'

### Expected Behavior
get a white colored line
### Actual Behavior
exception

**Comment by jfirebaugh** [comment]
Try `['get', 'color', ['literal', object]]`.

**Comment by AntonPilyak** [comment]
Ok, thanks, that works, BUT! I think it should be described in the docs. Right now the style spec says: 

[get](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-get)

Retrieves a property value from the current feature's properties, or **from another object** if a second argument is provided. Returns null if the requested property is missing.
["get", string]: value
["get", string, object]: value
