### ISSUE TITLE
Multi-touch Panning

### ISSUE THREAD

**Issue by dave11mj** [mapbox/mapbox-gl-js#6483]
**mapbox-gl-js version**: `0.44.2`

### Steps to Trigger Behavior

 1. `npm install mapbox-gl-js` and load it into a page
 2. Test on a touchscreen device
 3. Try to pan with more than one finger and notice the map doesn't respond

### Expected Behavior
User should be able to pan with more than one finger and zoom if necessary.

### Actual Behavior
As soon as second touch is detected the panning is disabled.

### Additional Notes
The map seems to work as expected when I forked the repo and generated a standalone build while following the [contribution guidelines](https://github.com/mapbox/mapbox-gl-js/blob/master/CONTRIBUTING.md). Is this behavior expected for a future release and would there be a way to cherry pick the fixes from the standalone build while this fix makes it way to the stable version ?

Thanks!

**Comment by mollymerp** [comment]
Hi @dave11mj ! If the behavior isn't present on master the bug has most likely been fixed. We should be releasing a beta of `v0.45.0` this week that includes the fix.

> would there be a way to cherry pick the fixes from the standalone build while this fix makes it way to the stable version ?

yes if you find the commit that fixes your issue you could cherry pick it onto the `v0.44.0` branch and create a local build.

**Comment by dave11mj** [comment]
Hey @mollymerp I am not as familiar with mapbox issue tracking but are issues usually closed before the fix has being released or is this issue being tracked by another ticket ? I'll be happy to test `v0.45.0` as soon as its available on npm ! :D 

Thanks for the speedy reply btw ! ^^

**Comment by andrewharvey** [comment]
> are issues usually closed before the fix has being released

Correct, issues are closed when they are fixed in master.

**Comment by dave11mj** [comment]
Thanks for clarifying that ! :D
