### ISSUE TITLE
COG Tiff support?

### ISSUE THREAD

**Issue by donnyv** [mapbox/mapbox-gl-js#6485]
Is it possible to load Cloud Optimized GeoTIFFs? Openlayers has support but was wondering if Mapbox was thinking of adding it.
https://github.com/cholmes/cog-map

**Comment by mollymerp** [comment]
@donnyv as long as the server endpoint uses XYZ or WMS tiling schemes, you should be able to add it as a raster layer. https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-raster-scheme

in the example you posted it looks like they are using xyz and this should work with Mapbox https://github.com/cholmes/cog-map/blob/master/main.js#L16

In the future for "how do I... ?" questions, please use a site like StackOverflow or contact Mapbox support. This issue tracker is for bug reports and feature requests. Thanks!

**Comment by wiesehahn** [comment]
Are there any updates on this?

A similar question was asked on Stackoverflow [here](https://stackoverflow.com/questions/63989239/how-to-add-raster-data-using-mapbox-gl-js) without satisfying answers.

Since COGs are tiled internally and can be queried partially via HTTP GET requests they seem to be made for adding them to a webmap in my understanding.

If it is possible already in an easy way I am missing some example or documentation.

**Comment by crubier** [comment]
The simple truth here is that Cloud Optimized Geotiff go against Mapbox business interests. They have no incentive to allow Cloud Optimized Geotiffs in Mapbox as it makes their tiling services redundant.

**Comment by jo-chemla** [comment]
Hi @mapbox team, should we open a new issue for COG support as a raster tile source/protocol or reopen that one? The above cog-map example linked by OP relies on a [TiTiler](https://github.com/developmentseed/titiler) middleware, which ingests a COG source and on-the-fly produce tiles (optimized localized fetch, mosaic, reprojection) based on standard XYZ/TMS tiles requests. 

As seen in this [discussion](https://github.com/maplibre/maplibre-gl-js/discussions/1246), @oscarfontsfrom from @geomatico implemented support in maplibre via [geomatico/maplibre-cog-protocol](https://github.com/geomatico/maplibre-cog-protocol). Would be nice to have a similar feature directly within mapbox-gl-js!
