### ISSUE TITLE
incorporate a css build system

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#6493]
It can be painstaking to edit the [inline svg assets in mapbox-gl.css](https://github.com/mapbox/mapbox-gl-js/blob/master/dist/mapbox-gl.css#L107) by hand.

There is also inconstancy, some are base64 encoded others url encoded.

Should we convert the mapbox-gl.css into [SASS](http://sass-lang.com/guide) and use https://www.npmjs.com/package/sass-inline-svg to automatically base64 and inline SVG assets.

**Comment by anandthakker** [comment]
Good idea, though I'd be more inclined towards [PostCSS](http://postcss.org/) over SASS.
