### ISSUE TITLE
In map.addSource() canvas type not allowed

### ISSUE THREAD

**Issue by salmau** [mapbox/mapbox-gl-js#6500]
**version**:
I'm currently using 5.6.0 version of NodeJS with the Aurelia framework.
The mapbox-gl version is 0.44.2.

Aim : add a layer with a canvas as data type (like doc says it is allowed https://www.mapbox.com/mapbox-gl-js/style-spec#sources).

### Steps to Trigger Behavior

 1. Trying to add a canvas source : 
```
map.addSource('canvas', {
    'type': 'canvas',
    'canvas': 'mycanvas',
    "coordinates": [
            [-81.490, 46.437],
            [-72.582, 46.437],
            [-72.582, 38.907],
            [-81.490, 38.907]
        ],
  });
```

### Expected Behavior

Canvas type allowed.

### Actual Behavior

 '{ 'type': "canvas"; 'canvas': string; "coordinates": number[][]; }' not allowed by the expecting types 'VectorSource | RasterSource | GeoJSONSource | ImageSource | VideoSource | GeoJSONSourceRaw'.

In your module there are types Canvas and CanvasSource. But never called.

**Comment by lbud** [comment]
Hi @salmau, I suspect you're using a module or framework around mapbox-gl-js (such as `react-map-gl` or `react-mapbox-gl`), and I believe this is likely a bug there (`GeoJSONSourceRaw` is not a mapbox-gl-js type, for example, and likely an intermediary definition) — please file a ticket in that repo. If you can reproduce this error using the pure mapbox-gl-js library please open a new bug report including a minimal reproduction with JSFiddle or the like.
