### ISSUE TITLE
Filter by geometry-type with new expressions

### ISSUE THREAD

**Issue by Twansparant** [mapbox/mapbox-gl-js#6508]
**mapbox-gl-js version**:
0.44.0

### Steps to Trigger Behavior

 1. Apply a filter by geometry-type on layer using new expressions:
```javascript
filter: [
	'all',
	// ['==', '$type', 'Polygon'] // old syntax was working
	// ['==', 'Polygon', 'geometry-type'], // not working
	['==', 'geometry-type', 'Polygon'], // not working
	// ['match', 'Polygon', 'geometry-type', true, true], // only works with default set to true
]
```

### Expected Behavior
Layer only shows polygons

### Actual Behavior
Layer not showing anything

What should the new syntax be for this kind of filter?
Thanks!

**Comment by jfirebaugh** [comment]
`"geometry-type"` is itself an expression operator (that takes no arguments), so the full syntax is `["==", ["geometry-type"], "Polygon"]` or `["match", ["geometry-type"], "Polygon", true, false]`. (You might want to use `"match"` if you have several geometry types that should pass, e.g. `["match", ["geometry-type"], ["LineString", "Polygon"], true, false]`.)

On its own (without surrounding square brackets), a string like `"geometry-type"` is just a string, same as `"Polygon"`.

Hope that helps!

**Comment by Twansparant** [comment]
> Hope that helps!

Definitely!
This one: `["==", ["geometry-type"], "Polygon"]` did the trick!
Thanks a lot!
