### ISSUE TITLE
Filter expression if value is in (nested) property array

### ISSUE THREAD

**Issue by Twansparant** [mapbox/mapbox-gl-js#6509]
**mapbox-gl-js version**: 0.44.0

### Steps to Trigger Behavior

 1. Apply a filter which should check if a string value is present in an feature property array using new expressions:
```javascript
this.map.addLayer({
	id: 'category-1',
	type: 'symbol',
	source: 'features',
	layout: {
		'icon-image': 'category-1',
		'icon-size': 0.5
	},
	filter: [
		'all',
		['==', ['geometry-type'], 'Point'],
		['in', ['array', ['get', 'subCategory']], 'category-1']
	]
});
```
Where **subCategory** is a feature property array:
```
['category-1', 'category-2']
```

### Expected Behavior
Adds a `category-1` layer when `category-1` is found in the subCategory array.

### Actual Behavior
Produces the error:
```javascript
Error: layers.category-1.filter[1][1]: string expected, array found
```

How should the new expression syntax look to find a value in an array?
Thanks a lot!

**Comment by jfirebaugh** [comment]
It's not currently possible. Tracking this in #6473.
