### ISSUE TITLE
using relative paths for assets in examples makes them less portable

### ISSUE THREAD

**Issue by samsammurphy** [mapbox/mapbox-gl-js#6511]
The [3D indoor mapping](https://www.mapbox.com/mapbox-gl-js/example/3d-extrusion-floorplan/) example does not work locally out of the box. 

As mentioned on [SO](https://stackoverflow.com/questions/42096737/extrude-polygons-for-3d-indoor-mapping-in-mapbox/49815556#49815556) it results in this error:
`Failed to load file:///mapbox-gl-js/assets/indoor-3d-map.geojson: Cross origin requests are only supported for protocol schemes:`

The line causing this CORS issue is [here](https://github.com/mapbox/mapbox-gl-js/blob/13ea16df5eabc4c8867d69e81da180cdcd6cc6b2/docs/pages/example/3d-extrusion-floorplan.html#L20).

A simple workaround might be to use inline json?

**Comment by andrewharvey** [comment]
@samsammurphy good point. I think we should:

1. Always use the absolute URL (so it actually works when it's copy pasted somewhere else)
2. Enable the CORS headers for the assets which need them (not sure if that's possible with the way it's hosted by Mapbox)

**Comment by samsammurphy** [comment]
@andrewharvey thanks, that's a more appropriate title. 

The [image example](https://www.mapbox.com/mapbox-gl-js/example/image-on-a-map/) has a similar portability issue due to [this path](https://github.com/mapbox/mapbox-gl-js/blob/13ea16df5eabc4c8867d69e81da180cdcd6cc6b2/docs/pages/example/image-on-a-map.html#L13).

**Comment by andrewharvey** [comment]
https://stackoverflow.com/questions/49912764/how-to-add-clusters-in-map-box looks like someone else running into this.
