### ISSUE TITLE
map.setFilter() breaks overzoomed tile

### ISSUE THREAD

**Issue by szymonkaliski** [mapbox/mapbox-gl-js#6515]
**mapbox-gl-js version**: 0.44.2 (but this also happens on 0.44.1, 0.44.0, and 0.43.0)

We've stumbled onto strange bug, where map.setFilters() breaks overzoomed tile (makes it disappear).

### Setup

Here's link to a repo containing everything that's needed to reproduce: https://github.com/szymonkaliski/mapbox-gl-js-bug-reproduce

1. `./get-indonesia-tiles.sh` - downloads latest OSM QA tiles from https://osmlab.github.io/osm-qa-tiles/ (I think it might be relevant that OSM QA tiles have only zoom level 12)
2. `npm install`
3. `npm start`
4. open `http://localhost:3000`

### Steps to Trigger Behavior

1. zoom map in (to 13+ so mapbox-gl-js overzooms)
2. change date and submit

### Expected Behavior

Tile features are filtered and visible.

### Actual Behavior

Tile disappears completely:

![gif](https://user-images.githubusercontent.com/1040420/38777629-8ed6d60c-40ab-11e8-844f-29d0b672a62f.gif)

### Other notes

Everything works fine if user stays on zoom level 12 (default), changes the date, and submits (some features might disappear but that's the idea - to filter map to specific timestamp).
Tile breaks only if user zooms in (to 13+ so mapbox-gl-js overzooms), and then changes the date.

**Comment by asheemmamoowala** [comment]
The source needs to define its `maxzoom` property.

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by szymonkaliski** [comment]
Thank you, that helps. I would suggest maybe adding one paragraph about "overzoom" to the https://www.mapbox.com/mapbox-gl-js/style-spec/#sources link, knowing what I know now it's clear what `maxzoom` is for, but before your answer this felt like a bug.

Thanks again!
