### ISSUE TITLE
support custom textures on fill-extrusion layers

### ISSUE THREAD

**Issue by onny** [mapbox/mapbox-gl-js#6516]
Hey,
I would like to ask if it's already possible to add "3d" images to mapbox gl js or is there maybe some workaround in how to achieve an image layer in 3d-perspective?

Best regards,
Jonas

**Comment by onny** [comment]
Thanks @andrewharvey for your replay. Of course you're right the term "3d image" is kind of unspecific.
In my project where I'm using mapbox gl js, I've added a custom 3d building layer. On some walls I would like to have a custom texture (e.g. an image) instead of a simple color.
Not sure if this is already possible or a planned feature.

**Comment by andrewharvey** [comment]
I don't think there is a ticket for this already, but it touches https://github.com/mapbox/mapbox-gl-js/issues/3996 and https://github.com/mapbox/mapbox-gl-js/issues/1489

**Comment by onny** [comment]
Thanks for clarifying my request ;)

**Comment by jfirebaugh** [comment]
I don't think we're likely to implement this as titled, as part of `fill-extrusion `, so let's roll this into #3996.

In the meantime @onny, you may be interested in the [Mapbox SDK for Unity](https://www.mapbox.com/unity/), which is more targeted to the 3d space.

**Comment by aartikanungo** [comment]
> In my project where I'm using mapbox gl js, I've added a custom 3d building layer. On some walls I would like to have a custom texture (e.g. an image) instead of a simple color.
> Not sure if this is already possible or a planned feature.

Hello @onny i want to do something exactly like this. want to add image in place of color filled. Did you get the solution for this?  thanks in advance :)

**Comment by abrichr** [comment]
Here's a crude approximation:

```
const textureUrl = './texture.jpg'  // replace this with a URL to your texture
const textureName = 'buildingTexture';

map.loadImage('./texture.jpg', function (error, image) {
  if (error) throw error;
  map.addImage(textureName, image);
})

map.addLayer({
    ...
    type: 'fill-extrusion',
    paint: {
      'fill-extrusion-pattern': textureName,
      ...
    }
    ...
  },
  ...
);
```

![image](https://user-images.githubusercontent.com/774615/117741728-13004c80-b1d1-11eb-8c89-7ad563163bba.png)
