### ISSUE TITLE
Error occurs when I zoom too much on the map

### ISSUE THREAD

**Issue by salmau** [mapbox/mapbox-gl-js#6517]
Version:
I'm currently using node v8.11.1 (npm v5.6.0) with the Aurelia framework.
The mapbox-gl version is 0.44.2.

The code : 
```
    mapboxgl.accessToken = XXXX
    let map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/tilkal/cjfxnfaka3ech2rmzkgrix7p7',
      zoom: 0,
      center: [12, 28]
    })

    // displaying the points on the map
    // loading red marker for claim map
    map.on('load', function () {
       map.loadImage('/src/assets/images/markers/marker-red-light.png', function (error, image) {
          if (error) throw error;
          map.addImage('marker-red-light', image)
          map.addLayer(data)
        })
     })
```

### Steps to Trigger Behavior

 1. The page loads successfully.
 2. I drag, zoom on the map.
 3. When I zoom too close, errors appear.

### Expected Behavior
No error

### Actual Behavior
![error-mapbox](https://user-images.githubusercontent.com/38292202/38807810-19669cd0-417e-11e8-92a3-08936c3ea31e.png)

**Comment by mourner** [comment]
Thanks for the report! Can please you set up a minimal live test case (e.g. on JSFiddle or JSBin) that reproduces the issue without using any third-party frameworks? Otherwise we won't be able to diagnose the issue.
