### ISSUE TITLE
missing labels on FF/Win

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#652]
https://news.ycombinator.com/item?id=8145338

> Doesn't look intentional. I've gotten drastically different street name coverage for the same area at the same zoom level depending on whether I got there by panning or zooming. And neither one includes names for the whole screen. Still a few kinks to work out?
> ![image](https://cloud.githubusercontent.com/assets/98601/3836198/f42bc494-1dce-11e4-86fd-404b6a23bc87.png)
> It feels like the text pops in and out as large zones, and the zones are unloading themselves before the whole zone is offscreen, sometimes leaving large areas blank.
> For reference, the upper image was produced by panning. The area on the right had been showing text, but it vanished as it got near the edge of the screen.

**Comment by mourner** [comment]
Is this still reproducible on latest FF/Win?

**Comment by jgillich** [comment]
I just tried the [example](https://www.mapbox.com/mapbox-gl-js/examples/), works fine now.

**Comment by mourner** [comment]
Yay!
