### ISSUE TITLE
Event object types required by new Evented#fire are not exported

### ISSUE THREAD

**Issue by bfrengley** [mapbox/mapbox-gl-js#6522]
**mapbox-gl-js version**: master (to be release 0.45.0)

With the changes in https://github.com/mapbox/mapbox-gl-js/commit/87c6332ea442b3a7628cc9c21212ffbe99487171 made as a part of #6218, Evented#fire (and by extension Map#fire) expects an [`Event` object](https://github.com/mapbox/mapbox-gl-js/blob/master/src/util/evented.js#L22-L35) rather than a string, as previously. However, the `Event` and `ErrorEvent` types are not exposed to mapbox-gl-js consumers, while the `Evented` class is [documented as part of the public API](https://www.mapbox.com/mapbox-gl-js/api/#evented).

Calls to Map#fire can be made by creating an object in the shape of an `Event` object (e.g., `map.fire({ type: 'move', originalEvent: e })`), but with the lack of documentation of `Event` and `ErrorEvent`, this isn't obvious.

Is there intention to export and/or document these types?

**Comment by jfirebaugh** [comment]
No, the intention is that `Evented#fire` is private as of the next release; see 2b645718743c4a5f229be9ab90df2a77328fbcce.

If you can tell us more about your use of `map.fire`, we may be able to suggest an alternative.

**Comment by jfirebaugh** [comment]
Related: https://github.com/mapbox/mapbox-gl-draw/issues/766

**Comment by jfirebaugh** [comment]
Thanks for reporting this. We elected to roll back that change until we have a suitable replacement for your use case; `Map#fire` will continue to support the existing usage in the meantime.

**Comment by bfrengley** [comment]
Thanks! 🙂

**Comment by schorsch** [comment]
Sorry to ask, as i could not find a discussion about that in other tickets, but what are the reasons to privatice Evented? 
Some kind of event handling is needed anyway for the default events, [map.on('xy)](https://www.mapbox.com/mapbox-gl-js/api/#map#on) , so where are the problems to expose such to custom events?

**Comment by foundryspatial-duncan** [comment]
> If you can tell us more about your use of map.fire, we may be able to suggest an alternative.

Can you please advise on how to simulate a map click at given coordinates? It used to be something like `map.fire('click', <something>);` - I can't think of how I'd do this with an external event emitting library.

The project I'm working on is still using 0.44.2 anyway, but the docs for that version are gone from the website (?)

**Comment by bravecow** [comment]
@jfirebaugh `fire` is good for custom plugins:

https://www.mapbox.com/mapbox-gl-js/api/#icontrol

Other way we need to pass callbacks to constructor 😞

**Comment by allthesignals** [comment]
Is there a main thread for discussion about the future of Map#fire? I am running across a few relevant threads, both issues and PRs:

https://github.com/mapbox/mapbox-gl-draw/issues/766
https://github.com/mapbox/mapbox-gl-js/pull/6605
https://github.com/mapbox/mapbox-gl-js/issues/6607
