### ISSUE TITLE
Double click on the map emits 'click' event twice

### ISSUE THREAD

**Issue by pedroscaff** [mapbox/mapbox-gl-js#6524]
**mapbox-gl-js version**: 0.44.2

### Steps to Trigger Behavior

 1. Add event listeners:
```js
map.on('dblclick', e => {
  console.log(e)
})
map.on('click', e => {
  console.log(e)
})
```
 2. Double click on the map

### Expected Behavior
Only `dblclick` event is emitted

### Actual Behavior
`click` event is emitted twice and after that `dblclick` is emitted.

**Comment by jfirebaugh** [comment]
Hi @pedroscaff, thanks for using Mapbox! Receiving two `click` events followed by a `dblclick` is the expected behavior. It mirrors what happens with [normal DOM click events](https://www.quirksmode.org/dom/events/click.html).
