### ISSUE TITLE
How to update vector source

### ISSUE THREAD

**Issue by rouen-sk** [mapbox/mapbox-gl-js#6525]
Hi,
I am trying to use Mapbox GL JS (v0.44.0) for visualizing custom data (polygons with density of specific events over time). I am generating vector tiles on server for every specific zoom/x/y/time. On client side, I have defined Mapbox style, with `source` with type `vector` and `tiles` property pointing to my server endpoint, I add it by calling `map.addSource()` and then I add several layers using this source by `map.addLayer`. All works fine. But then, user want to switch to another point in time - that means different set of vector tiles (from different URL on my server).  
What is the correct way to do this?
1. Is is supported to modify `tiles` property of souce object already added to map? Will this automatically raise some event causing the map to refresh?
2. Or must I remove all layers (since I guess there cant be layers with missing source), then remove source, then add new source and add all layers again? Is this OK performance-wise?
Thanks!

**Comment by asheemmamoowala** [comment]
For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
