### ISSUE TITLE
Feature request: Prevent world repeat

### ISSUE THREAD

**Issue by jasonbarry** [mapbox/mapbox-gl-js#6529]
It would be awesome if there was a property on map init you could specify to prevent the world from repeating horizontally. 

As a workaround, we have the `minZoom` update on window resize. 

```JS
window.addEventListener('resize', () => {
  // this coefficient was found by manually testing optimal zoom levels at different browser widths
  const MAGIC_MINZOOM_COEFFICIENT = 984.615384615;
  this._mapMinZoom = window.innerWidth / MAGIC_MINZOOM_COEFFICIENT;
});
```

But that's a little clunky.

**Comment by jfirebaugh** [comment]
This exists, it's `renderWorldCopies: false`.

**Comment by jasonbarry** [comment]
@jfirebaugh yes, but then the aspect ratio of the map doesn't fit its container (there are white vertical bars on the left and right of the canvas). I would expect the `minZoom` to increase when `renderWorldCopies` is true.

**Comment by jfirebaugh** [comment]
That wasn't something that I've heard from other users of `renderWorldCopies`, so I think it's probably best to leave `minZoom` and `renderWorldCopies` decoupled. They're both configurable, so if you do want them coupled you have that option.
