### ISSUE TITLE
Custom search from geojson data 

### ISSUE THREAD

**Issue by sharseema** [mapbox/mapbox-gl-js#6532]
Hi,
I have the India Geojson [file](https://github.com/sharseema/data/blob/master/State.geojson) on GitHub ,from that file i want to search the state name.I have saw the mapbox GL geocoder [example](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-local-geocoder/) but in this example  where can i add the custom Geojson file for search, Thanks.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
