### ISSUE TITLE
Vector Tile parse error

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#6537]
I am using the vector tiles generated by ourselves(with mapbox-gl-js 0.44.2).

While we often meet the following errors in the console:

1 Expected varint not more than 10 bytes
Sounds like this tile format is invalid. Any tool to check that?

2 http status 200 returned without content.
For a tile there is no data , what should we do ?

**Comment by stevage** [comment]
1. https://github.com/mapbox/vtvalidate

2. 200 is ok, but [204 is better](https://github.com/mapbox/mapbox-gl-js/issues/4691).

**Comment by jfirebaugh** [comment]
Thanks @stevage!
