### ISSUE TITLE
map can't show because set the parentDom css property :transform 

### ISSUE THREAD

**Issue by wxqqq** [mapbox/mapbox-gl-js#6539]
the map can't show. 
here is the example:
[(https://jsfiddle.net/q1udzova/1/)](https://jsfiddle.net/q1udzova/1/)
**mapbox-gl-js version**:  the last version
### Steps to Trigger Behavior

 when the parent div has  css properties:
  tramsform:scale(0.5,0.5);

### Expected Behavior
 map  is show as normal.
### Actual Behavior
the map can't show.

**Comment by jfirebaugh** [comment]
This doesn't seem related to Mapbox GL JS. When you apply a transform to the body, it seems to get a height of 0. Try adding an explicit `height:100vh;`: https://jsfiddle.net/q1udzova/6/.

**Comment by wxqqq** [comment]
sorry for open it ,
 this is the [https://jsfiddle.net/q1udzova/6/](https://jsfiddle.net/q1udzova/6/)

i think because the body is scale so  the symbol cant get right position. 
the click event didn't work.
