### ISSUE TITLE
Incorrect feature coordinates while we are using querySourceFeatures \ queryRenderedFeatures on interaction with zoom

### ISSUE THREAD

**Issue by Glareone** [mapbox/mapbox-gl-js#6541]
Hi guys.
This bug is based on incorrect features coordinates while we are using querySourceFeatures \ queryRenderedFeatures on interaction with zoom.
Link with demo: https://jsfiddle.net/1y5ag9r4/34/
In demo: 
2 Layers , 1 of them is 'technical'. 
2 Sources, 1 of them is 'technical'
We select features with featureIds [1,2,3] from original Layer\Source using  querySourceFeatures \ queryRenderedFeatures, attach this features to technical source and expect that it will be "highlighted" properly. No matter how we attach features(using setData or remove+create source)
 
### Steps to Trigger Behavior

 1. Zoom In or zoom out

### Expected Behavior
  1. Whole lines highlighted
### Actual Behavior
   1. See half-highlighted line

**Comment by jfirebaugh** [comment]
This is expected behavior per [the documentation for `queryRenderedFeatures`](https://www.mapbox.com/mapbox-gl-js/api#map#queryrenderedfeatures):

> Because features come from tiled vector data or GeoJSON data that is converted to tiles internally, feature geometries may be split or duplicated across tile boundaries and, as a result, features may appear multiple times in query results. For example, suppose there is a highway running through the bounding rectangle of a query. The results of the query will be those parts of the highway that lie within the map tiles covering the bounding rectangle, even if the highway extends into other tiles, and the portion of the highway within each map tile will be returned as a separate feature. Similarly, a point feature near a tile boundary may appear in multiple tiles due to tile buffering.
