### ISSUE TITLE
Point labels fail to display

### ISSUE THREAD

**Issue by astrojams1** [mapbox/mapbox-gl-js#6543]
Hello,

I apologize that this question is vague. Let me know what information I can provide that will help. 

I am working on my personal project (IRLMAP.COM), which lets users create custom point maps.

I sometimes encounter an issue where points users add are missing their label (see images). If I resize the map, the points labels will sometimes return. This is only a problem with the text: the point circle renders consistently.

Notice that some points are missing labels:
![screen shot 2018-04-19 at 10 35 42 am](https://user-images.githubusercontent.com/1023503/39008579-f0280c9a-43bd-11e8-91e9-2fd1369c6b1a.png)

Here is a more zoomed in picture:
![screen shot 2018-04-19 at 10 35 51 am](https://user-images.githubusercontent.com/1023503/39008584-f4379508-43bd-11e8-9015-114cf3cb5e98.png)

Here is a code for the ComponentWIllUpdate lifecycle event, which handles updating the map when the points change:

```
componentWillUpdate(nextProps, nextState) {
    const { points, homePoint, bounds, config } = this.state
    let arr = []
    points.forEach((p, i) => {
      if (!p.properties.search) {
        arr.push(p)
      }
    })
    if (this._map.getSource('points')) {
      this._map.getSource('points').setData({
        type: 'FeatureCollection',
        features: arr
      })
    }
    if (this._map.getSource('home-point')) {
      if (!homePoint.properties.search) {
        this._map.getSource('home-point').setData({
          type: 'FeatureCollection',
          features: (config.mapLayoutOptions.homePoint) ? [homePoint] : []
        })
      } else {
        this._map.getSource('home-point').setData({
          type: 'FeatureCollection',
          features: []
        })
      }
    }
    if (!this.state.isDraggingPoint) {
      this._map.resize()
      this._map.fitBounds(bounds, {padding: 40, animate: false})
    }
  }
```

**Comment by jfirebaugh** [comment]
Hi @astrojams1, thanks for using Mapbox. It looks like you want to set the [`text-allow-overlap`](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-allow-overlap) property to true.

If you've set this property, and are still not getting the desired behavior, please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue.

**Comment by astrojams1** [comment]
I do indeed have this set to true when I initially add the layer...

```
map.addLayer({
        id: 'points-label',
        source: 'points',
        type: 'symbol',
        layout: {
          'text-allow-overlap': true,
          'text-field':'{extIndex}',
          'text-size': pointSize/2*1.3,
        }
      })
```

**Comment by iryanjan18** [comment]
Is it also possible to add circle label just like symbol.layout.text-field?
