### ISSUE TITLE
Add a way to remove/add multiple markers at once

### ISSUE THREAD

**Issue by Wykks** [mapbox/mapbox-gl-js#6547]
## Motivation

When you need to add/remove lots of marker in a frame. It's costly because there's no way to remove/add multiple markers at once.
This is needed for a "good" implementation of marker clustering. (And maybe toggle lots of marker at once).

## Design

Add a `MarkerGroup` just like the `LayerGroup` from `leaflet` to be able to directly add/remove a group of marker. 
But in the marker clustering use case this kind of api is not really helpful.
Maybe, something like
`Map.addMarkers([Marker, ...])`
`Map.removeMarkers([Marker, ...])`
Which may do less dom call.

Edit: Nevermind, after more carefull performance investigation, in the case of marker clustering, it's not really necessary. It's slow because of the smooth zoom vs step zoom in leaflet, so there's something else to do in this case.

But, the feature is still relevant when adding/removing bunch of markers.

**Comment by mourner** [comment]
At the moment I feel like there's not enough incentive to complicate the API with this feature instead of just adding/removing markers in a loop and tracking them as a group on the app level. It's fast enough. So I'm closing for now.
