### ISSUE TITLE
Rendering unicode chars as text-field not working

### ISSUE THREAD

**Issue by fighterii** [mapbox/mapbox-gl-js#6557]
**v0.44.2**:

### Steps to Trigger Behavior

 1. https://jsfiddle.net/3caxnwsb/
 2. Add a Symbol Layer with an text-field with unicode character '\u2192'
 3.

### Expected Behavior
An arrow is printed on top of the line

### Actual Behavior
Layer is not printed, however if you set text-field to '->' you can see an "arrow" (but looking bad)

Maybe there is a better way to overlay my FeatureCollection with arrows, indicating the direction from start to end. Sadly i noticed creating the fiddle, that the text displayed is not going the right way (the "right" line should go from right to left).

I couldn't find a working example, which achieves this. Also i didn't find an icon-image for "arrow". I'd like to achieve a look like the one-way direction arrays, but for my own route.

**Comment by jfirebaugh** [comment]
Open Sans Regular does not provide a glyph for U+2192. You'll need to add a fallback font to the `text-font` property that contains this glyph; for example "Arial Unicode MS Regular":

https://jsfiddle.net/3caxnwsb/1/

**Comment by fighterii** [comment]
@jfirebaugh: Thanks a lot!
But is there a way to achieve that the text is rendered from first to last point (So that the right line is actually rendered with an arrow facing to the left)?

**Comment by jfirebaugh** [comment]
If you don't care about where on the line the symbol appears, you can use U+2190 LEFTWARDS ARROW, of course. If you want to control the direction that the symbol-spacing algorithm actually lays out the symbols, you'll need to reverse the direction in the data.

**Comment by fighterii** [comment]
Actually the data is ordered as a route,coming from the right (east) and then turning right to go northwards.

Or at least it should be, because that is the way I drove with a gps tracker.

So your saying that the rendering should already respect the order of data, am I right? 
Sorry, but I can't find good documentation, so I'm glad some people who are familiar with the engine are out there helping!

**Comment by fighterii** [comment]
@jfirebaugh:
Actually i checked the data:
https://jsfiddle.net/3caxnwsb/2/
and
https://jsfiddle.net/3caxnwsb/3/
by flipping the coordinates of "route 19" -> The data order is not respected by the symbol-spacing algorithm. Should it be?

**Comment by fighterii** [comment]
Managed to figure it out by myself with the docs:
text-keep-upright defaults to "true" -> setting it to false achieves that the arrow follows the data direction:
https://jsfiddle.net/3caxnwsb/5/
And i guess i'm able to figure out why the text is not centered on the middle of the line as well :)
Thanks a lot again!

**Comment by jfirebaugh** [comment]
Glad you figured it out! The centering thing may be the fact that that particular glyph is not centered relative to the baseline, or it might be #1130.
