### ISSUE TITLE
Add support for markers

### ISSUE THREAD

**Issue by tomaspinho** [mapbox/mapbox-gl-js#656]
I want to use this library in conjunction with the Mapbox service for a game I am currently developing. However, we need support for custom markers like the Google Maps JavaScript API provides. We need markers with custom images, bindable events and a similar simple API.

**Comment by robschley** [comment]
Is handling map labels that show up on mouse hover within the scope Mapbox GL or is that something that should be handled in HTML/JS? I tried to use some trickery to get the current hover point and bind the GeoJSON properties to a separate symbols layer to dynamically show labels when you mouse over certain GeoJSON polygons but it doesn't work fluidly. I'm using the GeoJSON source `setData()` API but the layer doesn't seem to be redrawn until I change the zoom level of the map. When I start zooming in and out, it sometimes works but it appears to also cache previously rendered points as well.

**Comment by jfirebaugh** [comment]
Lately I've been thinking of "Markers" as being more of a series of incremental improvements and additions than as a monolithic feature. These include:

* Data-driven styling (https://github.com/mapbox/mapbox-gl-js/issues/146). This is in itself a collection of features:
  * Data-driven functions (a.k.a. "scales" -- https://github.com/mapbox/mapbox-gl-style-spec/issues/226)
  * Arithmetic operators (https://github.com/mapbox/mapbox-gl-style-spec/issues/47)
  * Tokens in number/color properties (https://github.com/mapbox/mapbox-gl-style-spec/issues/105)
* Highlight individual features (https://github.com/mapbox/mapbox-gl-js/issues/200)
* Style-aware hit testing (https://github.com/mapbox/mapbox-gl-js/issues/316)
* Popups (https://github.com/mapbox/mapbox-gl-js/issues/325)
* Make adding GeoJSON easier (https://github.com/mapbox/mapbox-gl-js/issues/327)
* Default layers for data overlays (https://github.com/mapbox/mapbox-gl-style-spec/issues/162)
* Multiple sprites and individual images in style (https://github.com/mapbox/mapbox-gl-js/issues/358)
* Sort symbols by y-axis (https://github.com/mapbox/mapbox-gl-js/issues/470)
* Get unprojected geometry from featuresAt (https://github.com/mapbox/mapbox-gl-js/issues/723) / in fact just GeoJSON (https://github.com/mapbox/mapbox-gl-js/issues/1010)
* "per-layer" mouse events + automatically provide target feature in event (https://github.com/mapbox/mapbox-gl-js/issues/1002)

There is one marker related thing that's major enough to disqualify as "incremental" in my book, and that's clustering (https://github.com/mapbox/mapbox-gl-js/issues/837).

**Comment by incanus** [comment]
Awesome, great way to break the progression down @jfirebaugh. 

As I showed in chat the other day with @kkaefer @1ec5, on the native side, we have a high bar for markers to "just work" in the way that devs expect. 

--

![markers](https://cloud.githubusercontent.com/assets/17722/6279681/9b08e218-b859-11e4-8d21-aeb3137e6233.gif)

*Note how selection changes despite the gesture location not changing, so that obscured markers can be cycled through. Also, the selected marker temporarily moves to the front. These are the absolute barebones, simple pins without styling, added to an Apple map.*

--

As we think about how this builds out on JS and native, taking a staged approach lets us focus on the things we need to ship for an MVP, then the rest of what people might expect of a toolkit, then the things that no one expects because it's brand new territory. 

And agree on clustering.

**Comment by StepanKuzmin** [comment]
Crossposting [this](https://github.com/mapbox/mapbox-gl-js/issues/837#issuecomment-114063243) question.

Is there are any plans for leaflet-like markers styling? It could be something like `L.divIcon` which deals with gl context. It would be nice to have ability to style markers with all webgl power. Also it is not so simple to build custom markers using sprites, if marker display depends on it's content. I mean that I must have sprite icon for every possible marker display. So instead of that I want to handle marker displaying by myself.

**Comment by OmniEarthDev** [comment]
Back in version 7 of the "streets" style  ("https://www.mapbox.com/mapbox-gl-styles/styles/mapbox-streets-v7.json").  There was an "icon-image" of "secondary_marker" or "default_marker" used via GeoJson that looked like the markers everyone knows and loves.  The problem was these named images were only available in the "streets" style version and not in any other of the Mapbox canned styles.   ( FYI:  The latest style version removed the images. )

Hopefully, a new and different implementation of markers will be coming soon. 

When it does, If there is a connection with styles again PLEASE make it uniform across all the Mapbox styles!

**Comment by Randgalt** [comment]
Where does this stand? I'm new to Mapbox. I was using the JS lib for starters and got nice markers working. Is there anyway to do this in the GL lib? This issue is over a year old? I have to say it's not been a pleasant experience starting as a Mapbox newbie.

**Comment by 1ec5** [comment]
> The problem was these named images were only available in the "streets" style version and not in any other of the Mapbox canned styles. ( FYI: The latest style version removed the images. )

These markers were added for the Mapbox iOS SDK, which does support markers (called “annotation images”). At the time they were added, annotation images had to be baked into the styles, which is why you saw them there. As of mapbox/mapbox-gl-native#941 and mapbox/mapbox-gl-native#2440, the Mapbox iOS and Android SDKs bundle the default images locally, so they were removed from the styles. (These SDKs also allow you to specify custom images or generate them at runtime.)

**Comment by d-simon** [comment]
I'd be interested if there is any progress to be expected on this.
This is quite frustrating, especially since there are examples of markers on the official page but once you dig in, you start to notice the marker-hell currently present in the GL Lib.
So what's the state? Any plans? ETA?

**Comment by lucaswoj** [comment]
@d-simon 

At a high level, the plan is to develop features that free us from having a notion of "markers" that is separate from the notion of symbol layers, fill layers, etc.

 - re-colorable icons
 - interactivity on all map features 
 - something like marker clustering for map features

----

 > This is quite frustrating, especially since there are examples of markers on the official page but once you dig in, you start to notice the marker-hell currently present in the GL Lib.

What are you finding difficult in the transition from our examples to production code?

**Comment by jfirebaugh** [comment]
To update [my previous rundown](https://github.com/mapbox/mapbox-gl-js/issues/656#issuecomment-75164917), we've made progress on a number of features and are working on others:

* In progress: data-driven styling (https://github.com/mapbox/mapbox-gl-style-spec/issues/249). @lucaswoj has been working on laying some of the groundwork for this feature in mapbox-gl-js.
* Partially implemented: [Highlight individual features](https://github.com/mapbox/mapbox-gl-js/issues/200). Full implementation depends on data-driven styling. We did post [an example](https://www.mapbox.com/mapbox-gl-js/example/hover-styles/) of a way to accomplish this with existing functionality, but it should be easier.
* Not implemented: [Style-aware hit testing](https://github.com/mapbox/mapbox-gl-js/issues/316)
* Implemented: Popups
* Implemented: Make adding GeoJSON easier
* Not implemented: Default layers for data overlays (https://github.com/mapbox/mapbox-gl-style-spec/issues/162)
* Not implemented: [Multiple sprites and individual images in style](https://github.com/mapbox/mapbox-gl-js/issues/358). This is one of the most requested features and will be a high priority for the next style-spec revision.
* Implemented: Sort symbols by y-axis
* Implemented: Get GeoJSON geometry from featuresAt
* Not implemented: "per-layer" mouse events + automatically provide target feature in event (https://github.com/mapbox/mapbox-gl-js/issues/1002)
* In progress: marker clustering -- @mourner is [working on this](https://github.com/mapbox/supercluster)

@d-simon Anything in particular that's causing you difficulties that's not covered by the above? From the other comments here it sounds like support for individual symbol icons loaded from URL is the biggest thing that we can do to allow for a more familiar "put a marker with this image at this location" API. Is that what you're looking for too?

**Comment by jmjavier** [comment]
When I follow this example https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/ and use my own style created in Mapbox studio, the Maki icons don't work. Is there a specific layer that I need to create in my style for it to have the Maki icons available?

**Comment by lucaswoj** [comment]
@jmjavier Every style has an associated spritesheet. Markers are regular `symbol` layers and use images from that spritesheet. 

If you add the [Maki icons](https://github.com/mapbox/maki/tree/mb-pages/src) you want to use to your style in Studio via an existing symbol layer, the example should work as expected.

<img width="962" alt="screen shot 2015-12-15 at 10 18 53 am" src="https://cloud.githubusercontent.com/assets/281306/11819569/6c35cc6a-a315-11e5-8a62-006f28e8799f.png">

**Comment by bgentry** [comment]
> Partially implemented: Highlight individual features. Full implementation depends on data-driven styling. We did post an example of a way to accomplish this with existing functionality, but it should be easier.

@jfirebaugh so I didn't realize that I could use the `filter` functionality as a way to achieve hoverable markers. Instead, I made two layers (unselected and selected) each with separate sources. When the user moves their mouse, my event handler changes the data for both of these sources using `setData` (and lodash to filter the complete list of markers for each respective layer).

I tried using the `filter` approach instead, and it appears to be *much* slower than what I was already doing (manually filtering and using `setData()` on the data sources). Using `filter` introduces a noticeable delay before the map is redrawn as compared to the more manual approach. I notice this same kind of delay when hovering over states in the example: https://www.mapbox.com/mapbox-gl-js/example/hover-styles/

Just letting you know in case you're unaware of the performance problems with this method. I have a map with a couple hundred pins on it. Will be sticking with the manual way of doing things for now :)

**Comment by jmjavier** [comment]
@lucaswoj that worked for me. thanks for the explanation.

**Comment by d-simon** [comment]
@lucaswoj Thanks for the heads-up. (And apologies for my "blunt" comment.)
I will attempt to make use of that and report back :+1: 

@jfirebaugh Well, I'm not sure if I have understood correctly: We are struggling with non-round markers in a tilted map (using geoJSON features). We use `featureAt` with a radius, but it does not feel like a actual hover, more like an approximation. The tilted map doesn't make things easier: When selecting a marker that is "far in the back", the hover barely covers the entire marker.
How would we go about implementing a regular marker correctly? Do we need to use the `filter`?

What caused me additional headache are cut off markers when using `icon-allow-overlap: true` which were then cut off partially in our map. Am I going right in the assumption that this will be resolved with https://github.com/mapbox/mapbox-gl-js/pull/1727 ?

**Comment by jfirebaugh** [comment]
Thanks @d-simon, that helps clarify what we need to work on to make markers easier:

* [Style-aware hit testing](https://github.com/mapbox/mapbox-gl-js/issues/316) so that hover respects the actual size of the marker on screen.
* [Multiple sprites and individual images in style](https://github.com/mapbox/mapbox-gl-js/issues/358) so marker images don't have to be included in the style sprite.

I believe you are correct that the issue with cut off markers will be fixed with #1727.

**Comment by uhuru-be** [comment]
The "style-aware hit testing" would be a great feature.

To implement showing marker info when hovering a marker, I now bind a "mousemove" event to the map and then use the featureAt function to detect if the mouse moves over a marker (using a radius of 10), much like the following example on the Mapbox website : 
https://www.mapbox.com/mapbox-gl-js/example/marker-popup/

However, this is not very straightforward to me.  Is this the way to go (for now) ?
Also how do I close the "popup" when the mouse moves away from the marker ?

**Comment by tristen** [comment]
@uhuru-be

> However, this is not very straightforward to me. Is this the way to go (for now) ?

Yep - this is the way to go.

> Also how do I close the "popup" when the mouse moves away from the marker ?

There's a pending pull request demonstrating that [behaviour here](https://github.com/mapbox/mapbox-gl-js/pull/1861).  The example [file is here](https://github.com/mapbox/mapbox-gl-js/blob/f09e02f02140a7be010525ad5159a986557fcf7d/docs/_posts/examples/3400-01-06-popup-on-hover.html).

**Comment by ttoni** [comment]
Any news on custom markers? 

I was pretty happy with the way mapbox.js and L.divIcon worked. I had control over every aspect of styling and layering of images. 
I ported my map-styles to mapbox-gl and now I don´t see any way to display markers the way I need to. 

My markers are consisting of: 
- a marker-shape-like background image 
- a user profile photo on top of that background image
- text overlay on top of user profile photo (45deg text rotation)

(see example of my markers here: https://uebermaps.com/maps/726-the-record-covers-of-new-york)

I see there might be a way to do image overlays with sprites but haven´t really figured out how. But then I still don´t know how to draw an image on top of the background image. And i see no way to draw text (with rotation) with sprites.

**Comment by aidanlister** [comment]
I just want simple markers like mapbox.js has :(

**Comment by marcushat** [comment]
Is it sad that it's easier to overlay a marker in html( using map.project(lngLat) ) or using canvas directly than it is to do it the mapboxgl way? That's the route I went. I understand you guys are trying to prioritize and build out this new thing but I really think such a basic and common thing as plotting a point should be simple.

**Comment by than** [comment]
Ditto. I'm having to abandon using Mapbox GL for a big project because I need the ability to deal with markers in a flexible, customizable way.

**Comment by ttoni** [comment]
Same here, still using mapbox.js because of inflexible markers in mabox gl.

**Comment by mourner** [comment]
What would you think of a lightweight GL JS plugin that provides a simple API for Leaflet-like DOM markers synchronized with a GL map?

**Comment by marcushat** [comment]
Same too. There is a very real development cost both in time and money to have the build every little thing from scratch and then to have to maintain that larger codebase. I absolutely love the idea of MapboxGL but I unfortunately won't be able to use for any non-trivial project until there is more abstraction and better documentation. I may release a plugin when I'm done to add synchronized markers with html or canvas api if I can get everything to work without without bugs.

**Comment by ttoni** [comment]
Would that include the marker cluster (#320)? Sounds good.

**Comment by marcushat** [comment]
@mourner Exactly what I had in mind. If I end up using GL then I'll definitely make a plugin and share it.

**Comment by mourner** [comment]
@marcushat we may take a stab at it too, and then see whether it can fit in the core.

@ttoni that comment was about GL Native. GL JS already has [clustering support](https://www.mapbox.com/mapbox-gl-js/example/cluster/).

**Comment by marcushat** [comment]
@mourner Awesome, would love to see that!

**Comment by ttoni** [comment]
@mourner great. Yes, I know, just wanted to check if the plugin uses the same clustering.

**Comment by mirraj2** [comment]
Why is it that Mapbox GL doesn't include the most basic good-looking markers that everyone expects a map to have?  This is the only thing that is holding me back from using Mapbox.

**Comment by lucaswoj** [comment]
@mirraj2 Most mapping libraries treat the basemap as a black-box canvas and allow you to place some simple primitives (i.e. markers) on top. On the other hand, Mapbox exposes all the data and drawing primitives of the basemap to you, the developer. 

The upside of this approach is that you have full access to the data underlying the map, the ability to mix in your own data, and full control of the map's visual appearance. The downside of this approach is that some simple use cases (i.e. adding markers) require a couple extra steps because we expose more basic primitives. 

 1. Add a "data source" containing marker coordinates and metadata 
 2. Add a "style layer" which draws the marker data source using a particular shape, color, etc.

[Here is an example of this approach.](https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/js/example/geojson-markers/)

We are planning, in the near future, to release a plugin that makes this process simpler.

**Comment by than** [comment]
@lucaswoj I think there's also a huge desire here for "markers" to mean more than just static images on the map. (And maybe that's a mismatch in vernacular here among the dev...)

There was a suggestion above somewhere to fake more dynamic 'markers' with popups, but that requires a lot of customization and results in another layer of separation between the data source, the style layer, and in my case, a lot of extra popup elements on the map.

**Comment by mirraj2** [comment]
All I want are good looking static markers.  I literally just switched to google maps from mapbox because google maps lets me use whatever static image I want for my markers. On mapbox, it is HELL to use a basic PNG image as a marker.

The example you gave me uses built-in marker images that look like complete crap. I want to use actual good looking markers.

**Comment by Randgalt** [comment]
Well, @lucaswoj the old JS library did perfect markers. All we want is what _your other product already supports_.

**Comment by ttoni** [comment]
Couple of points that where key to a map marker in my mapbox-js projects and fully possible with leaflet html markers: 
 - Background image (f.e. png with shape of marker)
 - Font image (f.e. user avatar that was fetched from s3 and replaced a default user icon at)
 - Text overlay that has css styling (f.e. place name, user name, badge)

That´s not possible with static image markers or I couldn´t find a good documentation on how to achive this. Some map projects of mine are really stalled now because of this missing feature.

**Comment by emiltin** [comment]
Wish it not more straight-forward to place markers and interact with them. Or maybe I just can't find an example of how to do it.

**Comment by mtin79** [comment]
@lucaswoj :
I can't see how to easily (or at all) create your own markers (styling e.g.: with images like animated gifs, png, ...) via GeoJSONSource#setData as you mentioned above "Add marker in source #2552".
For me this issue is not closed.

**Comment by n1ghtie** [comment]
@mtin79 follow this guide https://github.com/mapbox/mapbox-gl-js/issues/822 (look at what @peterqliu says), I found this useful. Although I agree there should be an easier way to do this.

**Comment by lucaswoj** [comment]
@mtin79 Adding new icons/images/sprites at runtime is a separate issue: https://github.com/mapbox/mapbox-gl-js/issues/358

**Comment by zo0m** [comment]
@n1ghtie Hello, I have issue with adding custom markers. I read help article from your link but I cant find button "Add SVG Images".
It should be here:
![image](https://cloud.githubusercontent.com/assets/1734953/15830714/8b00c01e-2c22-11e6-93d0-31f454ed26f8.png)

I dont see it:
![14297761211b4969a53340f6a7fd7e20 1](https://cloud.githubusercontent.com/assets/1734953/15830690/70192836-2c22-11e6-9e65-fe1f246116f4.png)

Could you please help me. Thanks

**Comment by tristen** [comment]
@zo0m the dialog appears when you click the text input field (to the right of the "image" label), not the edit by zoom level link.

**Comment by mourner** [comment]
Pushed a basic implementation in #2725.

**Comment by tomaspinho** [comment]
Wow, thanks @mourner and the rest of the Mapbox team!

**Comment by samvermette** [comment]
I tried adding my own SVGs to the icon library of a custom mapbox style (based off the Streets style) and was never able to link to them.. every other icon worked, but not the ones I uploaded. I published the style, made sure I was linking my Mapbox to it... tried different names... 

Ended up downloading the style's json and switching the sprite reference to a custom json which only contains the icons I initially wanted to show, but now I lost every other icon too (highway shields, park, etc). Can't believe how painful it was to show custom images on the map. Any clue on why my custom icons aren't working as part of an existing style?

**Comment by n1ghtie** [comment]
How do you reference them? It should be like this

```
var markers = {
    "type": "FeatureCollection",
    "features": [{
      "type": "Feature",
      "properties": {
        "marker-symbol": "Volcano" // name of symbol in your sprite sheet
      },
      "geometry": {
        "type": "Point",
        "coordinates": [-155.24917602539062,
          19.326046963894633
        ]
      }
    }]
}
      map.addSource("markers", {
        "type": "geojson",
        "data": markers
      });
      map.addLayer({
        "id": "markers",
        "type": "symbol",
        "maxzoom": 10,
        "minzoom": 8,
        "source": "markers",
        "layout": {
          "icon-image": "{marker-symbol}" //important to have it!
        }
      });
```

If you upload your images under mapbox studio and reference the name correctly you will get an image on your map :)

**Comment by achalnexus** [comment]
How to dynamic market not set in map box. I am list of data get and one by one marker set in mapbox but not successfully set marker.
I m wrote code this type of code..

var MarkerDatalist=[];
map.addSource("markers", {
        "type": "geojson",
        "data": {
            "type": "FeatureCollection",
            "features": [MarkerDatalist]
        }
    });

    map.addLayer({
        "id": "markers-layers",
        "type": "symbol",
        "source": "markers",
        "layout": {
            "icon-image": "{marker-symbol}-15",
            "text-field": "{title}",
            "text-font": ["Open Sans Semibold", "Arial Unicode MS Bold"],
            "text-offset": [0, 0.3],
            "text-anchor": "top"
        }
    });
	
	function CreateMarker(pID, pointlong, pointLat, icon1, InfoHTML, bDraggable, sTitle, ParkName, Parksize) {
    var MapMarkerset = {
        "type": "FeatureCollection",
        "features": [{
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [pointlong, pointLat]
            },
            "properties": {
                "id": pID,
                "title": sTitle,
                "description": InfoHTML,
                "parksize": Parksize,
                "marker-symbol": "monument"
            }
        }]
    }
    MarkerDatalist.push(MapMarkerset);
    //map.getSource('markers').setData(MapMarkerset);
}

and other issue is zoom in out page reload in asp.net..?
Give me some help.

**Comment by kylebebak** [comment]
Adding markers to a map is really basic functionality. I put it to the Mapbox devs that most people, if they knew how difficult it was to render a few hundred markers with custom styles to a map, wouldn't even consider using Mapbox for a project.

The attitude I've seen in these issues regarding markers is really disconcerting, and will ensure that a lot of users migrate to Google Maps.

Better documentation is needed, with an example showing exactly how to handle this use case. It's a really common use case. It's probably **the most common use case**.

**Comment by ryanbaumann** [comment]
@kylebebak See https://www.mapbox.com/mapbox-gl-js/example/add-image/ for a great example of adding a custom icon / marker at runtime.

**Comment by Rajavelu** [comment]
Hi, any examples for handling mouseover, click events on markers which are created as symbol layer?

**Comment by fallenartist** [comment]
Such an _example_ can be found in _examples_: https://www.mapbox.com/mapbox-gl-js/example/center-on-symbol/ 😃

**Comment by Rajavelu** [comment]
@fallenartist Thanks for your reply. 
I want to show a custom image with a label in cluster marker. tried as follows:
                      

> VectorUtil.map.addLayer({
>                                         id: "unclustered-point", // No I18N
>                                         type: "symbol", // No I18N
>                                         source: "clusterMarker", // No I18N
>                                         filter: ["!has", "point_count"], // No I18N
>                                         "layout": {
>                                             "icon-image": "user-icon",
>                                             "icon-allow-overlap": true,
>                                             "text-field": "**{name}**",
>                                             "text-font": ["Open Sans Bold"],
>                                             "text-size": 11,
>                                             "text-transform": "uppercase",
>                                             "text-letter-spacing": 0.05,
>                                             "text-offset": [0, 1.5]
>                                         },
>                                         "paint": {
>                                             "text-color": "#00f",
>                                             "text-halo-color": "#fff",
>                                             "text-halo-width": 2
>                                         }
>                             });

But still not working. My geojson data contains name field, refer sample data:
{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"coordinates":["-94.921","39.3682"]},"name":"Allen"},{"type":"Feature","geometry":{"coordinates":["-85.2843","35.0018"]},"name":"Tom"}]}

Thanks in advance for any solution

**Comment by SephReed** [comment]
Am I taking crazy pills?!

### THERE IS NO WAY TO ADD STANDARD MARKERS USING ADD LAYER????

This is absolute insanity... Do I really have to iterate over my GeoJson using `addMarker()` for each one?
