### ISSUE TITLE
Rendering issue with map position/zoom + tileset w/Features per zoom level

### ISSUE THREAD

**Issue by ksummerill** [mapbox/mapbox-gl-js#6560]
**mapbox-gl-js version**: 0.44.2

### Steps to Trigger Behavior

 1. Open this map: https://bl.ocks.org/j5kay/a50925604a76c892826e5d3a7db77ddd
 2. Click and drag to move around the map, observe rendering behavior.

### Expected Behavior
Map rendering is smooth and consistent as you move around the map

### Actual Behavior
Rendering is jumpy, appearing and disappearing - https://ookla.d.pr/GoSLAX

**Comment by jfirebaugh** [comment]
Is `mapbox://ookla-ops.coverage-carrier-3221` a partial tilset, not covering the whole world? If so, I suspect this is a variant of #5829 / #4691, where when GL JS encounters a 404 response for a tile outside but adjacent to the boundary of the tileset, which triggers loading the parent tile, which also covers tiles at the natural zoom level that _do_ exist.

**Comment by j5kay** [comment]
@jfirebaugh - Yes, it has data not only within the LngLatBounds specified in the tileset's TileJSON, but also has features on a per-zoom basis between its z=0 to z=10 zoom extents (also specified in the TileJSON).

Not sure if the per-zoom tile data also plays a role per se, but when using `circle`-based layers for rendering data, it seems that multiple zoom levels are merged versus the exclusive rendering for `heatmap` or `extrusion`-based layers. Maybe a separate issue entirely, but I could make an example that illustrates the behavior with `circle` layers, if it's useful.

**Comment by jfirebaugh** [comment]
Thanks for the report! I'm consolidating all the issues related to this bug in #6768.
