### ISSUE TITLE
map.addLayer / map.removeLayer / map.setFilter seem slow on Firefox

### ISSUE THREAD

**Issue by mdartic** [mapbox/mapbox-gl-js#6561]
**mapbox-gl-js version**: 0.44.2 , 0.45.0-beta.1

### Steps to Trigger Behavior

 1. create a fullscreen map with a mapbox street style
 2. add layer circle of geojson data
 3. add mousemove / mouseleave / click handlers on layers that add/remove layers or use setFilter or use setData

### Expected Behavior

The layers are added / removed / filtered smoothly.

### Actual Behavior

The layers are added / removed / filtered slowly on Firefox.
Works correctly on Chrome / Chromium / Opera / Vivaldi.
The `setData` is more performant than the other strategies.

You can see the result here : https://jsbin.com/nicopal/ and see the code here : https://jsbin.com/nicopal/edit

Here are two gif illustrating how smooth / slow it is : 

* Chrome with add/remove layers

![mapbox-mousemove-chrome](https://user-images.githubusercontent.com/2027964/39246773-d21f6e58-4897-11e8-895c-e9b0ecc63c97.gif)

* Firefox with add/remove layers

![mapbox-mousemove-firefox](https://user-images.githubusercontent.com/2027964/39246779-d72bb6fe-4897-11e8-9604-2125d918f720.gif)

* Firefox with setFilter

![mapbox-mousemove-firefox-setfilter](https://user-images.githubusercontent.com/2027964/39257402-b7567dae-48b1-11e8-97e7-b52d663bacea.gif)

On Chrome, sometimes, warnings are saying `[Violation] 'requestAnimationFrame' handler took 91ms`.

On Firefox, no error, but the layers are added / filtered so slowly... 

If we use `setData`, performance is better on Firefox : (jsbin here : https://jsbin.com/vusojuf/edit?js,output)

![mapbox-mousemove-firefox-setdata](https://user-images.githubusercontent.com/2027964/39353982-8486303c-4a09-11e8-88ae-3dbe2df7b7aa.gif)

The lag is still present even if `setData`.

Is there any improvement available to make Firefox smoother ?

**Comment by stegano** [comment]
Processing with filters or expressions appears to improve performance over removing and adding layers.

**Comment by mdartic** [comment]
Thanks for your help, I've change the code with `map.setFilter`, but problem is still here : 

![mapbox-mousemove-firefox-setfilter](https://user-images.githubusercontent.com/2027964/39257239-5b9710e6-48b1-11e8-9be9-c6add4f01a79.gif)

I've updated the code in the jsbin.

**Comment by peterqliu** [comment]
Hi @mdartic , great question. `setFilter` and `addLayer` are both valid ways to do this, but the most performant method is actually `setData` on the layer for your active state. You can extract the feature geometry via `queryRenderedFeatures` on your mouse event, and use that to populate the active layer (big white circle).

**Comment by mdartic** [comment]
Thank you @peterqliu 
That's the result in Firefox : 

![mapbox-mousemove-firefox-setdata](https://user-images.githubusercontent.com/2027964/39351160-f0ef9230-4a00-11e8-8825-519ad158d599.gif)

And the code updated : https://jsbin.com/vusojuf

`setData` seems better in performance, but lag is still present.
We don't have anymore the "queue effect" that we had in `addLayer` / `removeLayer` / `setFilter`.
But Firefox seems still late in refreshing the map style.

Do you think this lag could be more optimized ?

**Comment by jfirebaugh** [comment]
Yes, we just merged a major feature to better support use cases like this: #6263 (see also #6020). It will be in the 0.46 release.

**Comment by Amit-Gore** [comment]
@jfirebaugh  When can we expect the 0.46 release? I have a vector tile source and filtering out the layer is having the same effect as above. Earlier when I was using geojson source it was working perfectly fine but now it has major performance issues. Can I expect these issues to be covered in next release?

**Comment by mollymerp** [comment]
@Amit-Gore it should be available by tomorrow evening.
