### ISSUE TITLE
When scrolling with the Apple Magic mouse, Map#isMoving() always returns false

### ISSUE THREAD

**Issue by stegano** [mapbox/mapbox-gl-js#6562]
**mapbox-gl-js version**:
- v0.44.2 or later

### Steps to Trigger Behavior
When call `map.isMoving()` during zoomIn or zoomOut, the result is always `false`.

1. Open the chrome browser console.
2. Enter the code below.
  ```javascript
  setInterval(() => { console.log(map.isMoving()); });
  ```
3. Zoom in or zoom out using the Apple Magic Mouse wheel. 🍎 
4. The result is always `false`.

### Expected Behavior
```javascript
true 
```
### Actual Behavior
```javascript
false 
```
  But seems It works well in v0.44.1.

**Comment by stegano** [comment]
Also, the mapbox version in the examples on the Mapbox website seesm to be wrong. 
The Mapbox website uses v0.44.2, but the cannot use `Map.isZooming()` (added in https://github.com/mapbox/mapbox-gl-js/commit/c0158855ddfa34f4706c5190e6d3da3972e1b901)

**Comment by jfirebaugh** [comment]
0.44.2 doesn't include c0158855ddfa34f4706c5190e6d3da3972e1b901:

![image](https://user-images.githubusercontent.com/98601/39255006-c8ebffe0-48ab-11e8-8dd4-8cd77dc50838.png)

**Comment by stegano** [comment]
With the Apple Magic Mouse, the map#isMoving() result is always `false` when scrolling. :(

**Comment by stegano** [comment]
@jfirebaugh 
I wonder if this is a bug..
I want a feature that lets me know the status when I zoom in with Apple Magic mouse or trackpad. Is there a way? 😞

**Comment by ansis** [comment]
This has been fixed by https://github.com/mapbox/mapbox-gl-js/pull/9365. If you have a chance to test and confirm, that would be great! The fix is in `master` and will be released in a beta release tomorrow.

**Comment by stegano** [comment]
@ansis Thank you for not forgetting to fix :D
