### ISSUE TITLE
Draggable Point Example doesn't work in Edge

### ISSUE THREAD

**Issue by rbrundritt** [mapbox/mapbox-gl-js#6565]
Example: https://www.mapbox.com/mapbox-gl-js/example/drag-a-point/

When you try and click and drag the blue circle, the map pans instead of the point. This was reported in the past and reported as fixed, but I suspect that this was either not tested/fixed in Edge or the fix is not live. Here are some related issues that are closed:

- [#2333](https://github.com/mapbox/mapbox-gl-js/pull/2333)
- [#2329](https://github.com/mapbox/mapbox-gl-js/issues/2329)

**Comment by jfirebaugh** [comment]
This seems to be working now; I think it was fixed by #6325.
