### ISSUE TITLE
Support two finger pitch gesture

### ISSUE THREAD

**Issue by sharseema** [mapbox/mapbox-gl-js#6568]
Hi,
The tilt view of 3d map is properly working on desktop and mobile using keyboard as well as mouse along with another map interaction feature (like Rotate,pan and zoom view) but in mobile tilt view is not working.

I saw some tilt view issue and read about tilt on mapbox document. As per my understanding  based on documentation pinch is called as tilt view. I tried with pinch as well as bearing but not working on mobile.
Please check this [example](https://codepen.io/seema30fresher/pen/aYLYZg)

Thanks.

**Comment by jfirebaugh** [comment]
Hi @sharseema. Can you be more specific about what "not working" means? What did you try, what did you expect to happen, and what happened instead?

**Comment by sharseema** [comment]
hi,
I am trying tilt map in mobile using two finger swap but tilt view not working on mobile.
Thanks.

**Comment by sharseema** [comment]
For all the touchscreen mobile its giving problem. we tested on google chrome, Firefox and safari browser.
Thanks.

**Comment by rbrundritt** [comment]
I've also tested this in all mobile versions of Edge. I'm also seeing this in all desktop browsers as well.

**Comment by jfirebaugh** [comment]
Ah right, sorry -- a two finger pitch gesture is not yet implemented in GL JS (on any platform/browser).

**Comment by jfirebaugh** [comment]
Turns out we have an existing issue for this: #3405.
