### ISSUE TITLE
Cannot Mouseover Popups

### ISSUE THREAD

**Issue by CharlesInteractive** [mapbox/mapbox-gl-js#6585]
**mapbox-gl-js version**: v0.44.2

### Steps to Trigger Behavior
 1. Go to this example link [Display a popup on hover](https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/).
 2. Mouseover an icon to display a popup.
 3. Attempt to mouseover the popup.

### Expected Behavior
The example includes links in the popups. You would expect to be able to mouseover the popup to click the on the links.

### Actual Behavior
The popup disappears before you can click on the link. 

Either you should be able to mouseover to the popup to click on the link, or not which would make the popup links in this example misleading.

**Comment by CharlesInteractive** [comment]
Thank you. I figured that was the expected behavior, but I though maybe something had broke since the popups included those unreachable links.

**Comment by jfirebaugh** [comment]
Fixed!
