### ISSUE TITLE
HillShading has slight artificial glossy look

### ISSUE THREAD

**Issue by pmem1** [mapbox/mapbox-gl-js#6591]
The glossy look appears to be caused by ridgelines being too bright. On the left is Tristen's style. On the right the image has been retouched to dampen down ridgeline brightness. I think the retouched image has a more realistic terrain appearance. Is this a bug in the shading algorithm?

![image](https://user-images.githubusercontent.com/32402159/39523470-a235310c-4e0d-11e8-80cc-901cea057a38.png)

**Comment by mollymerp** [comment]
Hi @pmem1 – thanks for using mapbox! You can control the brightness of terrain highlights with `hillshade-highlight-color` and `hillshade-accent-color` and tune the appearance to your preferences. The shaders were designed with the input of our cartography team to allow maximum flexibility for map designers. If you still think there is a bug after experimenting with the style properties, please feel free to reopen and include a self-contained minimal example of the behavior you're seeing.

**Comment by pmem1** [comment]
Hi there
I don't think you can isolate the bright ridgelines with those parameters. In fact, I've yet to see a mapbox hill shade that doesn't have that glossy look when zoomed in. Another example below with mapbox on the left and a more conventional less reflective example from another vendor on the right. (click to see full size)

I think the mapbox approach has the potential to go from merely beautiful to absolutely stunning if an example could be produced that addresses this issue.

![contrast](https://user-images.githubusercontent.com/32402159/39573122-c65bee56-4ec9-11e8-898e-5e1a0bdc32ee.png)
