### ISSUE TITLE
Looking for documentation of line-gradient property in v0.45.0-beta.1

### ISSUE THREAD

**Issue by kylehovey** [mapbox/mapbox-gl-js#6593]
I'm really excited about #6303! Our project currently just quantizes lines into hundreds of lines in a Multi-Line string with different colors, so this should really speed up the app. Is there documentation yet for this feature, or is that not a possibility for beta releases?

**Comment by mollymerp** [comment]
@kylehovey documentation is not live on mapbox.com until the final release, but you can run it locally with `yarn start-docs` or use the code [here](https://github.com/mapbox/mapbox-gl-js/blob/master/debug/line-gradient.html) as an example.
