### ISSUE TITLE
Occlusion stops working when `icon-allow-overlap`, `icon-ignore-placement`, and `text-ignore-placement` are set to true

### ISSUE THREAD

**Issue by jonsadka** [mapbox/mapbox-gl-js#6616]
Setting the following layout properties seems to break occlusion of the text layer
```
      "icon-allow-overlap": true,
      "icon-ignore-placement": true,
      "text-ignore-placement": true,
```

**mapbox-gl-js version**: 0.44.2
**browser**: Chrome Version 66.0.3359.139

### Steps to Trigger Behavior
Create a layer with an icon and text and the following layout properties
```
  map.addLayer({
    ...
    type: "symbol",
    layout: {
      ...
      "icon-allow-overlap": true,
      "icon-ignore-placement": true,
      "text-ignore-placement": true
    }
    ...
  });
```

### Link to Demonstration
https://codepen.io/jonsadka/pen/gzxyqg

### Expected Behavior
Text is rendered on top of all the icon
<img width="37" alt="screen shot 2018-05-04 at 1 03 55 pm" src="https://user-images.githubusercontent.com/6504944/39650565-7f5d88b4-4f9d-11e8-9bf3-38e20ec193b1.png"> <img width="46" alt="screen shot 2018-05-04 at 1 04 02 pm" src="https://user-images.githubusercontent.com/6504944/39650568-866c9456-4f9d-11e8-9740-d9aa8a014206.png">

### Actual Behavior
Text should layer with the icon it's attached to

**Comment by jfirebaugh** [comment]
Hi @jonsadka, thanks for using Mapbox. We're tracking this in #4064.
