### ISSUE TITLE
If you set layout.icon-offset in a geojson layer, mouse events do not find the icon

### ISSUE THREAD

**Issue by mwarren2** [mapbox/mapbox-gl-js#6624]
**mapbox-gl-js version**: v0.44.2

**browser**: Chrome

### Steps to Trigger Behavior

 1. Just add an icon-offset to an icon, the offset I use is [0, -50]
 2. Add a click event listener
 3. You will get no response from clicking the icon
This also happens with map.queryRenderedFeatures()

Just remove the icon-offset and mouse events start working again.

**Comment by jfirebaugh** [comment]
Does this layer happen to use `icon-rotate` as well? Could be a duplicate of #6075.

cc @ChrisLoer

**Comment by ChrisLoer** [comment]
Or if it has `symbol-placement: line` it could be #4798.

**Comment by mwarren2** [comment]
@jfirebaugh @ChrisLoer 

Yes, the layer also uses `icon-rotate`
(but NOT `symbol-placement`)

However if I remove `icon-rotate` it just moves the problem - the icon then responds to a mouse click at least but produces an empty array for map.queryRenderedFeatures.

For now the only reasonable workaround is remove `icon-offset`.
The map doesn't look right, but I can continue coding.

**Closing this as it's clearly a duplicate.**
