### ISSUE TITLE
Update documentation on necessary CSP directives

### ISSUE THREAD

**Issue by rangeoshun** [mapbox/mapbox-gl-js#6626]
Hi, thanks for the great, feature rich map you provide.

I found one issue with current documentation available on:

https://www.mapbox.com/mapbox-gl-js/api/

The `child-src` directive is deprecated, it should address it as `worker-src`, to avoid collision with `frame-src`.

Also, `image-src` is lacking the `*.tiles.mapbox.com`. `blob:` is not enough in itself with current version.

**mapbox-gl-js version**: 0.44.1

**browser**: Chrome 66.0.3359.139 (Official Build) (64-bit)

**Comment by jfirebaugh** [comment]
Note that Edge, IE, and Safari do not support `worker-src`, while Chrome skips `child-src`, so for compatibility you must now specify _both_ `worker-src blob:` and `child-src blob:`.

> Also, `image-src` is lacking the `*.tiles.mapbox.com`. `blob:` is not enough in itself with current version.

This should be covered by the subsequent paragraph:

> Requesting styles from Mapbox or other services will require additional directives. For Mapbox, you can use this connect-src directive:
> ```
> connect-src https://*.tiles.mapbox.com https://api.mapbox.com
> ```

**Comment by rangeoshun** [comment]
`image-src` is not `connect-src` we need both, don't we?

**Comment by rangeoshun** [comment]
And thanks for the details on `worker-src`!

**Comment by jfirebaugh** [comment]
I think only `image-src blob:` is needed because GL JS loads images with an XHR request rather than an `<img>` tag.
