### ISSUE TITLE
Undefined values in config fields overwrite default values

### ISSUE THREAD

**Issue by mlms13** [mapbox/mapbox-gl-js#6635]
**mapbox-gl-js version**: 0.45.0

**browser**: Firefox, probably all others?

### Steps to Trigger Behavior

 1. Follow all of the [quickstart](https://www.mapbox.com/mapbox-gl-js/api/) instructions
 2. In the config object, add `zoom: undefined`

### Link to Demonstration

https://codepen.io/anon/pen/GdyRXB

### Expected Behavior

Because I didn't provide a value for `zoom`, the default (`0`) will be used instead.

### Actual Behavior

Runtime exceptions.

My usecase: I'm generating the code from ReasonML. It's easy for me to create a type for optional values. It's less easy for me to create a type for object fields that might be missing entirely.

Other, imaginary usecase: Before displaying the map, I make users select configuration options in a form. Since most settings aren't required, I don't require users to provide those values in my form. I want to take the user input and dump it straight into the config object, missing values and all. Currently I would have to check the user input for missing values and conditionally delete fields from the config object.

**Comment by andrewharvey** [comment]
I think it makes sense to change the current behaviour so that if `undefined` is provided as an option value it should be treated the same as if the option is omitted.

**Comment by mlms13** [comment]
For what it's worth, I found some [compiler magic](https://bucklescript.github.io/docs/en/object.html#special-creation-function) for ReasonML/OCaml that makes it possible to create JS objects with missing values resulting in omitted fields.

So my immediate need has been taken care of, but I do still think it would be nice to support optional _values_ in addition to optional fields.

**Comment by mourner** [comment]
Closing as stale since there seems to be not enough interest to pursue this.
