### ISSUE TITLE
Find all street intersections

### ISSUE THREAD

**Issue by vbresults** [mapbox/mapbox-gl-js#6639]
I want to get a list of intersections currently visible on the map.  Preferably, without having to click.  If that's not possible, I'd like to find all of the intersections within x meters of where I clicked.

Thank you.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
