### ISSUE TITLE
Events do not trigger after a feature position change

### ISSUE THREAD

**Issue by Mistin7** [mapbox/mapbox-gl-js#6641]
**mapbox-gl-js version**: 0.44.0

### Steps to Trigger Behavior

When I change the position of any feature, it's just "disappear" from the mapbox canvas. Rather we can see it, but events are not triggered.
For example, I hang a mouseenter event for my feature, then change feature's position and after that mouseenter event does not trigger.

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?
