### ISSUE TITLE
v0.45.0 breaks mapbox-gl-directions plugin/example

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#6642]
**mapbox-gl-js version**: v0.45.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. Open https://jsbin.com/gipahagera/edit?html,output
 2. Click somewhere on the route between A and B and drag the route

![auswahl_277](https://user-images.githubusercontent.com/20856381/39779086-6cc939dc-5308-11e8-91e6-fb5590b3e338.png)

### Expected Behavior

Destination (B) is not moved and the route is adapted as with v0.44.2
https://jsbin.com/zidemesofe/edit?html,output

![auswahl_276](https://user-images.githubusercontent.com/20856381/39779094-745f794a-5308-11e8-9f45-c060e492f2e7.png)

### Actual Behavior

Destination (B) is moved

![image](https://user-images.githubusercontent.com/20856381/39779073-5bb9891c-5308-11e8-9f88-77a5ad016f1d.png)

Also reproducible with:
https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/

**Comment by mollymerp** [comment]
@pathmapper I'm not sure if this is a bug in mapbox-gl-js, it seems like a bug with how mapbox-gl-directions depends on events from gl-js, which changed since `0.44.*` (#6218). I will look into it and move this issue over to the plugin repo if this is the case.

**Comment by pathmapper** [comment]
@mollymerp I was also unsure where to open this issue and ended up posting it here since #6218 wasn't listed as breaking change in the `v0.45.0` release notes.

Anyway, thanks for looking into it!
