### ISSUE TITLE
WebGL context is terminated mobile devices.

### ISSUE THREAD

**Issue by ujazdowskip** [mapbox/mapbox-gl-js#6647]
Bug occurs on low/mid-end devices. This occurs on:

* Samsung J5 - very often
* Samsung J7 - slightly less often
* LG G6 - does not occur

**Versions**

0.44.2 - very often
0.45.0 - slightly less often

**Browsers**:

* newest Chrome

### Steps to Trigger Behavior

 1. Open map on mobile device
 2. Make some panning/zoom operations

### Link to Demonstration

https://jsbin.com/gizadaqicu/edit?html,output

But this bug is dependent rather on device not on specific map. It occurs as well during browsing official documentation.

### Expected behavior

Map should work.

### Actual Behavior

Web gl context is terminated with error message:
`WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost`

**Comment by jontyt** [comment]
+1 Happening for Samsung Tab A (SM-P555). 
Crash appears to happen more frequently as more layers are added to the map. Happens almost immediately even with most maps on the examples section of the documentation. 

Have checked GPU logs, GPU memory is fine (.0MB / 102MB max), memory is fine and not climbing (around 42MB in my test map). 
No useful information found in the chrome console besides the warning message `WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost`.

Any help here would be extremely helpful as this is a critical issue preventing a release.

**Comment by bravecow** [comment]
The same on desktop chrome OSX:

![image](https://user-images.githubusercontent.com/988471/71081475-eee53b00-2197-11ea-8e4d-bf25793b1cef.png)

![image](https://user-images.githubusercontent.com/988471/71081497-fc022a00-2197-11ea-91f3-fd2c4457bbfc.png)

**Comment by karimnaaji** [comment]
Closing in favor of https://github.com/mapbox/mapbox-gl-js/issues/9516 which has more detailed steps about that type of issue and reproduction.
