### ISSUE TITLE
GeoJSON MultiLineStrings with `lineMetrics=true` only render first line

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#6649]
**mapbox-gl-js version**: 0.45.0

GeoJSON sources with `lineMetrics: true` only render the first line of the multi ([demo](https://jsfiddle.net/lbud/ar1c8trq/2/)). This is an upstream issue that will be fixed once https://github.com/mapbox/geojson-vt/pull/103 is merged + patch released — will close here once we update that dependency.

**Comment by mourner** [comment]
Released in geojson-vt v3.1.2.
