### ISSUE TITLE
Label randomly flickering on setData

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6652]
**mapbox-gl-js version**: 0.45.0
**browser**: Chrome 66 / macOS

### Steps to Trigger Behavior
 1. Update a label's property belonging to a text-field using `setData()`.
 2. Usually, when updating relatively quickly, it flickers.
 3. Usually, when updated after waiting for a while, it doesn't flicker.

### Link to Demonstration
https://codesandbox.io/s/q8lrpv5wyw
Try changing the setTimeout value to 2000 which stops the flicker in 80% of the updates.  

### Expected Behavior
Should not flicker.

### Actual Behavior
Usually it flickers. Sometimes, with slower updates it does not flicker.

**Comment by mollymerp** [comment]
The text fading in and out is part of how our label collision detection algorithm works. If you'd like to avoid it, you can set `text-allow-overlap` to true. Also, I would not recommend using `setData` to update just the text-field property – you can use `setLayoutProperty` instead if you're not changing geometry.
http://jsbin.com/mugolukebi/edit?html,output
