### ISSUE TITLE
Add ngx-mapbox-gl to Framework Integrations list

### ISSUE THREAD

**Issue by Wykks** [mapbox/mapbox-gl-js#6654]
Hi!

It would be great if you can add
https://github.com/Wykks/ngx-mapbox-gl
to
https://www.mapbox.com/mapbox-gl-js/plugins/

:smiley:

**Comment by jfirebaugh** [comment]
Sure, want to make a PR adding it to the "Framework Integrations" section?

**Comment by Wykks** [comment]
Sure! :) https://github.com/mapbox/mapbox-gl-js/pull/6657

**Comment by jfirebaugh** [comment]
Thanks!
