### ISSUE TITLE
Type error when combining filter expressions with "all"

### ISSUE THREAD

**Issue by foundryspatial-duncan** [mapbox/mapbox-gl-js#6656]
**mapbox-gl-js version**: 0.44.2

**browser**: Chrome 66 on OSX

### Steps to Trigger Behavior
With a geojson source that has properties like this:

 1. Create a map filter with a `"=="` expression
 2. Create a map filter with an `"in"` expression
 3. Observe that they both work fine independently
 4. Combine the 2 with "all" and observe that an error is thrown:

> `Error: layers.points.filter[1][1][1]: string expected, array found` 

### Link to Demonstration
https://codepen.io/foundryspatial-duncan/pen/ZoojRM
(Open the console and click the buttons)

### Expected Behavior
The "all" expression would combine the filters as expected

### Actual Behavior
An error is thrown in the console and the filter doesn't apply.

**Comment by lbud** [comment]
@foundryspatial-duncan Filter 1 in your example uses expression syntax; Filter 2 uses the old filter syntax. Both syntaxes work in filters but as noted in the [documentation](https://www.mapbox.com/mapbox-gl-js/style-spec#other-filter), 
> Though filters defined with this syntax will continue to work, we recommend using the more flexible expression syntax instead. Expression syntax and the deprecated syntax below cannot be mixed in a single filter definition.

To combine these you'll need to convert the old style filter to an expression by changing the `["==", "net", "alpha"]` clauses to `["==", ["get", "net"], "alpha"]`.

**Comment by foundryspatial-duncan** [comment]
Ah, of course. Sorry, it was a classic 4:52pm Friday mistake :)

**Comment by awulkan** [comment]
@lbud Thanks, your comment helped me several years later. There really should be a better error message for this.
