### ISSUE TITLE
Font in mapbox-gl-js

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#6666]
I have two questions related to fonts in this library:

1 Font loader

When we specify  the font name in the style file, the fonts will be loaded by mapbox-gl-js, however it seems that once more then one fonts are used in the style, mapbox will tried to load them at the same time, see the url sent by mapbox:

`./Open%20Sans%20Regular,Arial%20Unicode%20MS%20Regular/1-256.pbf`

After decode we got this:

`./Open Sans Regular,Arial Unicode MS Regular/1-256.pbf`

Seems like mapbox tried to load both `Open Sans Regular` and `Arial Unicode MS Regular` in a single http request.

Now I want to know how can I return the font data for this kind of requests? Since we have put all the fonts in our own server and serve the by nginx. That's ok for `/Open Sans Regular/1.256.pbf` and `./Arial Unicode MS Regular/1-256.pbf`.  How to combine them together?

2 Css font.

Is it possible to use css font directly instead of using the `pbf encoded font`? We find that the fonts loading cost too much which will slow the map rendering.

**Comment by jfirebaugh** [comment]
Hi @exotfboy, thanks for using Mapbox. @jingsam's answer is a good one.

For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by exotfboy** [comment]
@jfirebaugh 

I am so surprised that this is an opensource project, and your link is a company help document and business contact support. So an opensource project related questions can be asked for the company?

**Comment by exotfboy** [comment]
@jingsam 👍

But it seems that the `localIdeographFontFamily` override all the fonts defined in the style which maybe not proper. Event I use `localIdeographFontFamily`, different layers in the style may still need different font.

**Comment by qiulinFV** [comment]
> @jingsam 👍
> 
> But it seems that the `localIdeographFontFamily` override all the fonts defined in the style which maybe not proper. Event I use `localIdeographFontFamily`, different layers in the style may still need different font.

https://github.com/mapbox/mapbox-gl-js/issues/10664#issuecomment-840237738
