### ISSUE TITLE
[docs] showOverdrawInspector is missing in docs

### ISSUE THREAD

**Issue by jingsam** [mapbox/mapbox-gl-js#6667]
https://www.mapbox.com/mapbox-gl-js/api/#map#showtileboundaries

The showOverdrawInspector is missing in docs.

![image](https://user-images.githubusercontent.com/1522494/40036580-d71a0fb4-583a-11e8-884a-2dbe7c0acceb.png)

**Comment by jfirebaugh** [comment]
This is intentionally omitted; it's for internal optimization work and not a public API.
