### ISSUE TITLE
Zooming with scroll wheel during pan ease resets pan action. 

### ISSUE THREAD

**Issue by bicubic** [mapbox/mapbox-gl-js#6668]
This issue is not present in 0.32.0, so I believe it's a regression caused by pan/zoom ease handling. 

**mapbox-gl-js version**:
0.45.0

**browser**:
Confirmed in Chrome, Firefox. Expect bug is not browser specific. 

### Steps to Trigger Behavior
 1. Initiate a pan ease with mouse drag + inertia 
 2. While pan easing animation is in progress, scroll mouse wheel to initiate a zoom ease

### Link to Demonstration
Can be replicated in any demos which allow panning and zooming. 

### Expected Behavior
Zoom and pan animations should be cumulative
### Actual Behavior
The pan animation will stop while the zoom is in progress, and then jerk to the new eased position

**Comment by averas** [comment]
Probably the same root cause, but wanted to mention this on the issue as well.

When initiating an animation programatically, for example with map.easeTo(), mouse wheel zooming does not interrupt the animation, which causes weird UX.

Demonstrated here (start mouse wheel/touch pad zooming during animation):

https://codepen.io/anon/pen/ZRevPa

**Comment by averas** [comment]
This seems to be a regression not present in <0.45.0.

**Comment by bicubic** [comment]
It may be related to https://github.com/mapbox/mapbox-gl-js/pull/5743

**Comment by mourner** [comment]
This is no longer reproducible in v0.47 (although I don't remember the exact PR that fixed it).

**Comment by clemishow** [comment]
I'm on v0.47 and I still have the issue.
Mozilla/5.0 (Linux; Android 8.0; SM-G960F Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Crosswalk/23.53.589.4 Mobile Safari/537.36

**Comment by mourner** [comment]
I might have misunderstood the issue — I can no longer reproduce the jerking motion when zooming during panning inertia, it just stops the inertia and zooms. Zoom and inertia are not cumulative, like the original issue requests, but I think they shouldn't be.
