### ISSUE TITLE
Object function ArrayBuffer() { [native code] } has no method 'isView' 

### ISSUE THREAD

**Issue by talyuk** [mapbox/mapbox-gl-js#6669]
Hello! I have Android 4.x with Cordova app, which uses Chrome 30 as webview, and mapbox cannot be displayed because of error: 

`Uncaught TypeError: Object function ArrayBuffer() { [native code] } has no method 'isView' `

It didn't work on some previous versions of mapbox-gl too. 
I've tried to use older version (0.36), but I have other errors like below: 
![image](https://user-images.githubusercontent.com/3207991/40049123-8925b022-583c-11e8-91d3-68a499e91d55.png)

How to make it work? Thanks a lot. 

Mapbox latest (v45) 
Android 4.4.2, Chrome 30.0.0 (Native browser)
Device Honor 3c Lite

**Comment by talyuk** [comment]
I need to say, that I have fallback for unsupported browsers with mapbox.js. 
I have found temporary solution: detect webgl support as described here (https://stackoverflow.com/a/41029281), not with mapboxgl.supported():

```javascript
var supported;

try {
    var canvas = document.createElement('canvas');
    supported = !! window.WebGLRenderingContext && (canvas.getContext('webgl') || canvas.getContext('experimental-webgl'));
} catch(e) { supported = false; }

try {
    // let is by no means required, but will help us rule out some old browsers: http://caniuse.com/#feat=let
    eval('let foo = 123;');
} catch (e) { supported = false; }

if (supported === false) {
    console.log("WebGL is not supported");
}
```

Therefore this browser will not use mapbox-gl and ArrayBuffer.isView.
I hope mapbox team can comment on this

**Comment by jfirebaugh** [comment]
Okay -- want to submit a PR to https://github.com/mapbox/mapbox-gl-supported that adds a test for `ArrayBuffer.isView`?
