### ISSUE TITLE
enter fullscreen mode from API

### ISSUE THREAD

**Issue by kukiel** [mapbox/mapbox-gl-js#6671]
## Motivation

It would be useful to have a function that toggle fullscreen mode so it could be used from outside of a map or within a custom control.

## Design

It could be named like `map.toggleFullscreen()`

**Comment by ryanhamley** [comment]
Hi @kukiel can you tell us a bit more about how you would use this feature? The browser's fullscreen API has to be initiated through a user interaction like a click and can't be programmatically controlled. But if you're building a custom control or attaching a listener to another element, you could call `map.getContainer().requestFullscreen()` and `map.getContainer().exitFullscreen()` (or the appropriate browser-specific versions of those calls) to toggle fullscreen mode. Is there any reason that calling the methods directly like this wouldn't work for your use case?

**Comment by kukiel** [comment]
@rachelholm Damn you are absolutely right, I forgot fullscreen can be called through interaction only. 

But this

>     map.getContainer().requestFullscreen()

is doing a job for me, thanks for sharing.

Maybe useful for some else:

>     const container = map.getContainer();
>     const rfs =
>       container.requestFullscreen ||
>       container.webkitRequestFullScreen ||
>       container.mozRequestFullScreen ||
>       container.msRequestFullscreen;
> 
>     rfs.call(container);

Love mapbox, great job guys!

**Comment by bendytree** [comment]
Fun fact - `requestFullscreen` is not supported on iPhone
