### ISSUE TITLE
Data-driven visibility with expressions

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6672]
1. In the older tickets asking about adding data-driven visibility, the official answers have been to use filters.
2. Filters are now deprecated.
3. As of today, what is the recommended way to implement data-driven visibility?

Personally I'm quite happy using MobX and just conditionally adding features in setData, but always triggering a setData for something as simple as toggling visibility of a single feature isn't optimal.

**Comment by anandthakker** [comment]
@hyperknot the old filter syntax is deprecated, but [not filters themselves](https://www.mapbox.com/mapbox-gl-js/style-spec/#layer-filter).  You can still set a layer's `filter:` property (or use `setFilter()`), but the filter should now be an [expression](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions)
