### ISSUE TITLE
Adding raster layer becomes blurry on some zoomlevels

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-js#6677]
I'm using version 0.45, and I'm adding a rasterlayer to my map in this way:

`map.on('load', function () {

    map.addSource('n_tracktiles', {
        type: 'raster',
        tiles: ['https://xxx.com/geoserver/gwc/service/gmaps?layers=mylayer&zoom={z}&x={x}&y={y}&format=image/png&version=1&versiond=' + new Date().getTime()],
        tileSize: 256
    });

    map.addLayer({
        'id': 'tracktiles',
        'type': 'raster',
        'source': 'n_tracktiles',
        'layout': {
            'visibility': 'visible'
        }
    });

    map.setPaintProperty('tracktiles', 'raster-opacity', 0.7);

    getVisibleNodes();

});`

On certain zoomlevels, raster tiles become blurry. Am I doing something wrong?

![blurry1 fw](https://user-images.githubusercontent.com/10425157/40117183-7c76e12c-5916-11e8-8dc4-e8299e7a0a79.png)

![blurry2 fw](https://user-images.githubusercontent.com/10425157/40117202-8bbdf9a4-5916-11e8-8898-a4aeacbd990a.png)

**Comment by jfirebaugh** [comment]
This is expected behavior. Raster tiles are static images and therefore appear perfectly crisp only at integer zoom levels.
