### ISSUE TITLE
Marker click not occur when map is loaded

### ISSUE THREAD

**Issue by nijs9** [mapbox/mapbox-gl-js#6678]
**mapbox-gl-js version**:0.45

**browser**: Chrome

### Steps to Trigger Behavior

 1. Load map
 2. Add some markers with click event
 3. When map is loaded first time, sometimes the first click-event on a marker does not occure

### Expected Behavior

Click event is fired

### Actual Behavior

Map 'moveend' event is fired, markers redraw

`var el = document.createElement('div');
                    el.className = 'mapbox-marker';
                    el.setAttribute('nodeData', JSON.stringify(result[i]));
                    el.style.backgroundImage = 'url(' + url_node + ')';
                    el.style.width = marker_width;
                    el.style.height = marker_height;

                    el.addEventListener('click', function (e) {

                        window.alert(JSON.parse(this.getAttribute('nodeData')).nodeRegion);
                        console.log("click", e);
                    });

                    nodesOnMap.push(new mapboxgl.Marker(el)
                        .setLngLat([result[i].nodeLon, result[i].nodeLat])
                        .addTo(map));`

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?

**Comment by jfirebaugh** [comment]
I'm not seeing that; `handleMapClick` is always being logged here: http://output.jsbin.com/mulinuxowe/

**Comment by nijs9** [comment]
Strange. I'm not using mapbox map, but OpenMapTiles. Maybe is has something to do with that.

**Comment by jfirebaugh** [comment]
Okay -- if you can show how to replicate it reliably let us know. Closing for now.

**Comment by nijs9** [comment]
@jfirebaugh  Can you please reopen! I've opened your solution on jsbin on 2 different PC's, in the latest Google Chrome version and this bug occurs also in your solution. This are the steps which triggered the behaviour:

- Open your map and open Chrome developer console
- Refresh map and click on map
- repeat refreshing page and click one time on map. Sometimes no click event is fired on first click after mapload. It's very clear it's a bug now. It occurs only after first click after page refresh.

**Comment by nijs9** [comment]
Not to explain in that case... I've tested on a third PC, and the same issue occurs: when refreshing in browser and not F5, map click event sometimes not triggered on first map click. No problem, it's not a disaster, but I'm sure there is something wrong there.

**Comment by nijs9** [comment]
Hi @jfirebaugh look here please, I tested in latest Google Chrome on Windows 10, on three different PC's. You can see some green-white markers with a number. When clicking on it, normally an alert dialog appears. In most times it does, but often it does not. In all other browsers this works fine, except in Chrome. Here you can find code and run possibility, as you can see, it's very basic:

https://output.jsbin.com/runijow/

**Comment by benoitbzl** [comment]
Hi, I am seeing the same issue with the mapbox example [https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/](https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/).
It works correctly until I first drag the map. Afterwards, none click event is passed down to the marker event handler.

mapboxgl-js: 0.45
Chrome: 66.0.3359.181 (Official Build) (64-bit)
OS: Windows 10
