### ISSUE TITLE
empty map in Firefox, including hello world example

### ISSUE THREAD

**Issue by matkoniecz** [mapbox/mapbox-gl-js#6682]
**mapbox-gl-js version**: 0.45.0 from https://www.mapbox.com/mapbox-gl-js/example/simple-map/

**browser**: Firefox 60 on Ubuntu 16

### Steps to Trigger Behavior

 1. open https://www.mapbox.com/mapbox-gl-js/example/simple-map/ example in Firefox

### Link to Demonstration

https://www.mapbox.com/mapbox-gl-js/example/simple-map/

### Expected Behavior

In both Chromium and Firefox map is displayed

### Actual Behavior

Map is displayed only in Chromium

**Comment by matkoniecz** [comment]
Originally reported as https://github.com/osmlab/changeset-map/issues/174

**Comment by mollymerp** [comment]
Hi @matkoniecz – Sorry to hear you're running into an issue! I'm using Firefox and the map shows up fine for me. Are there any errors in the console, and does this https://www.mapbox.com/mapbox-gl-js/example/check-for-support/ example fire an alert? Also if you include the information on `Graphics` from the information on the `about:support` page in Firefox that would be helpful in diagnosing your issue.

**Comment by matkoniecz** [comment]
> Are there any errors in the console

The resource at “https://api.segment.io/v1/p” was blocked because tracking protection is enabled.[Learn More]
simple-map
The resource at “https://www.google-analytics.com/analytics.js” was blocked because tracking protection is enabled.[Learn More]
simple-map
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.
simple-map:1
The resource at “https://connect.facebook.net/en_US/fbevents.js” was blocked because tracking protection is enabled.[Learn More]
simple-map
Loading failed for the <script> with source “https://connect.facebook.net/en_US/fbevents.js”.
simple-map:1
The resource at “https://snap.licdn.com/li.lms-analytics/insight.min.js” was blocked because tracking protection is enabled.[Learn More]
simple-map
Loading failed for the <script> with source “https://snap.licdn.com/li.lms-analytics/insight.min.js”.
simple-map:1
The resource at “https://s.adroll.com/j/roundtrip.js” was blocked because tracking protection is enabled.[Learn More]
simple-map
Loading failed for the <script> with source “https://s.adroll.com/j/roundtrip.js”.
simple-map:1
The resource at “https://munchkin.marketo.net/munchkin.js” was blocked because tracking protection is enabled.[Learn More]
simple-map
Loading failed for the <script> with source “https://munchkin.marketo.net/munchkin.js”.
simple-map:1
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:73:12
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
line_atlas.js:142:8
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:73:12
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
line_atlas.js:149:12
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.

> Are there any errors in the console, and does this https://www.mapbox.com/mapbox-gl-js/example/check-for-support/ example fire an alert?

The resource at “https://api.segment.io/v1/p” was blocked because tracking protection is enabled.[Learn More]
check-for-support
The resource at “https://www.google-analytics.com/analytics.js” was blocked because tracking protection is enabled.[Learn More]
check-for-support
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.
check-for-support:1
The resource at “https://connect.facebook.net/en_US/fbevents.js” was blocked because tracking protection is enabled.[Learn More]
check-for-support
Loading failed for the <script> with source “https://connect.facebook.net/en_US/fbevents.js”.
check-for-support:1
The resource at “https://snap.licdn.com/li.lms-analytics/insight.min.js” was blocked because tracking protection is enabled.[Learn More]
check-for-support
Loading failed for the <script> with source “https://snap.licdn.com/li.lms-analytics/insight.min.js”.
check-for-support:1
The resource at “https://s.adroll.com/j/roundtrip.js” was blocked because tracking protection is enabled.[Learn More]
check-for-support
Loading failed for the <script> with source “https://s.adroll.com/j/roundtrip.js”.
check-for-support:1
The resource at “https://munchkin.marketo.net/munchkin.js” was blocked because tracking protection is enabled.[Learn More]
check-for-support
Loading failed for the <script> with source “https://munchkin.marketo.net/munchkin.js”.
check-for-support:1
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:73:12
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
line_atlas.js:142:8
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
line_atlas.js:149:12
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:73:12
Error: WebGL warning: texSubImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
line_atlas.js:149:12
Error: WebGL warning: texImage2D: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.
texture.js:73:12
The resource at “https://api.segment.io/v1/m” was blocked because tracking protection is enabled.[Learn More]
check-for-support

It seems that "was blocked because tracking protection is enabled" appeared in log recently (FF upgrade that included https://developer.mozilla.org/en-US/Firefox/Privacy/Tracking_Protection?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default ? Or I miscopied in earlier report?)

**Comment by matkoniecz** [comment]
After enabling tracking console output got limited to https://gist.github.com/matkoniecz/6c36164c6279b7265e0e9cab6f105ba9#file-support_check_with_tracking_enabled-log (in support check) and https://gist.github.com/matkoniecz/6c36164c6279b7265e0e9cab6f105ba9#file-simple_example_with_tracking_enabled-log with no change in rendered WWW page.

**Comment by matkoniecz** [comment]
>  Also if you include the information on Graphics from the information on the about:support page in Firefox that would be helpful in diagnosing your issue.

https://gist.github.com/matkoniecz/6c36164c6279b7265e0e9cab6f105ba9#file-debug_info-log

**Comment by matkoniecz** [comment]
Attempt to preemptively answer some likely questions:

- I disabled all extensions (NOT using "restart with extensions disabled" (AKA --safe-mode parameter) as it also kill WebGL)
- I verified that https://get.webgl.org/ has a spinning cube
- I visited https://www.mapbox.com/mapbox-gl-js/example/simple-map/ and https://www.mapbox.com/mapbox-gl-js/example/check-for-support/ to verify that nothing that I tried so far has changed

**Comment by matkoniecz** [comment]
Note: I am now using 60.0.1 (64-bit) (minor version increase since initial report)

**Comment by mollymerp** [comment]
Hi @matkoniecz sorry for the delay and thank you for the error logs and GPU report – is this still affecting you? I'm on the same version and don't see an issue. 

I'm not familiar with nouveau drivers, have you made sure your GPU is supported on https://nouveau.freedesktop.org/wiki/CodeNames/? We haven't received any other reports of this nature so I'm inclined to believe this is an issue with your setup 😕 

(Different FF version and rendering behavior, but possibly related #6728 ?)

**Comment by matkoniecz** [comment]
I am pretty sure that I have no separate graphic card but integrated one.

"you can find your chipset by doing dmesg | grep -i chipset" gives me only:

> [    0.151901] DMAR: Disabling IOMMU for graphics on this chipset

**Comment by mollymerp** [comment]
hmm, I think that is the reason why the map isn't showing up. I'm not super familiar with hardware but it sounds like your graphics card isn't working correctly, and that is probably causing your problem. (see https://unix.stackexchange.com/a/189266) Do any other webgl applications work? for example https://threejs.org/examples/#webgl_geometries

I'm going to close this ticket because I'm pretty confident its a specific issue with your machine, but please re-open if you find evidence to the contrary.
