### ISSUE TITLE
Document map.fadeDuration option

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#6694]
The map has an undocumented `fadeDuration` option that controls how long collision fade-in/fade-out animations take. It defaults to 300ms, but in our test suite we set the value to 0ms so that we can render maps instantly. Other than that, we just use it internally for debugging. We don't have equivalent behavior on gl-native because gl-native supports an explicit "still" rendering mode. We're also considering a per-layer "disable collision fade" feature (#6692) that might supersede the global option, but we don't have any definite plans there.

Users are starting to discover this option as they look for ways to control animation behavior, and it's confusing to figure out how the global collision `fadeDuration` interact with runtime styling paint property transitions, the raster fade duration, etc. We should document the functionality to avoid causing confusion, even though it's functionality that we think is best left untouched in almost all cases.

@lbud @ansis @jfirebaugh

**Comment by pathmapper** [comment]
> confusing to figure out how the global collision fadeDuration interact with runtime styling paint property transitions

The cause for my confusion in #6519 was that I wrongly assumed that the initial label fade-in is a transition (the default value for both,`fadeDuration` and [transition duration](https://www.mapbox.com/mapbox-gl-js/style-spec#transition-duration), is 300ms).
