### ISSUE TITLE
Symbol layers are always drawn on top

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#6711]
**mapbox-gl-js version**: v0.45.0

**browser**: Chrome on Linux

### Steps to Trigger Behavior

Add a layer of type `fill` to the streets-v9 style with `map.addLayer` without providing a `before` argument.

### Link to Demonstration

http://jsbin.com/seviqomame/edit?html,output 
(which is https://www.mapbox.com/mapbox-gl-js/example/geojson-polygon/ with increased fill-opacity)

or

http://jsbin.com/pikisolehu/edit?html,output 
(which is https://www.mapbox.com/mapbox-gl-js/example/geojson-layer-in-stack/ without `before` argument and increased fill-opacity)

### Expected Behavior

The polygon is drawn on top of the labels because there is no `before` argument specified for the additional `fill` layer thus the layer will be appended to the end of the layers array.

### Actual Behavior

The labels are drawn on top.

**Comment by jfirebaugh** [comment]
Thanks for the report, we're tracking this in #2074. As a workaround, you can set the opacity of the fill layer to 0.99.
