### ISSUE TITLE
Communicate lack of support for feature-state in layout properties

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#6724]
When reading up on feature-state, I noticed this line: https://github.com/mapbox/mapbox-gl-js/blob/872c372fb0c748ebfa2599c9b3a358b74bf89394/src/style-spec/validate/validate_expression.js#L24 – does this mean that layout properties like `icon-image` and `text-size` cannot be used with the `feature-state` expression? If that is the case, could we capture this constraint in the spec documentation: https://github.com/mapbox/mapbox-gl-js/blob/1a8e9fec61af6569cb60d074bb07ad7fbc1e9704/src/style-spec/reference/v8.json#L2609 ? 

Right now, there's no way to know that we're supposed to hide this expression in the Studio UI for layout properties with data driven styling support.

**Comment by asheemmamoowala** [comment]
@samanpwbb Are you thinking that a note in the `doc` field would be enough, or are you looking for an additional field in the style-spec to automate the Studio UI?

**Comment by samanpwbb** [comment]
An additional field would be best.

**Comment by jfirebaugh** [comment]
How about adding `"feature-state"` as a potential element of the `"parameters"` array property added in #6521?
