### ISSUE TITLE
Support different color for fill-extrusion

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#6726]
There is only a property `fill-extrusion-color` used for color setting for type of `fill-extrusion`

While it seems that only one color is not enough(note the red square):
![image](https://user-images.githubusercontent.com/16457917/40460228-2b677b0c-5f38-11e8-8082-2eb193dd7e32.png)

Is it possible to add another color property?

**Comment by lbud** [comment]
@exotfboy if I understand correctly you're asking if there is a way to set an extrusion top color differently from its sides — we do not plan to support that use case. The sides are shaded based on the provided color (differently from the way the top is shaded, based on the angle of the light). 

(If you're interested in having more control over the angle/color/intensity of the light source, however, you can customize those with the stylesheet's [`light` property](https://www.mapbox.com/mapbox-gl-js/style-spec/#light) or corresponding [runtime API](https://www.mapbox.com/mapbox-gl-js/api/#map#setlight).)

**Comment by exotfboy** [comment]
@lbud  Thank you, I will have a try.
