### ISSUE TITLE
How do you parse and use the properety fill-extrusion-height

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#6727]
For a layer of type `fill-extrusion` there is a property `fill-extrusion-height` used to draw the height for the feature. And the unit of this property is `meter`.

https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-fill-extrusion-fill-extrusion-height

While I wonder how does mapbox-gl-js parse and use the property. Since when I search the property in [gitbub](https://github.com/mapbox/mapbox-gl-js/search?l=JavaScript&q=fill-extrusion-height&type=)  I do not find any codes that tried to retrieve the data from the style and use it for rendering.

**Comment by jingsam** [comment]
I can't figure out what problem you want to solve.

**Comment by jfirebaugh** [comment]
It's used in this loop (`property` will be `fill-extrusion-height` in one of the loop iterations):

https://github.com/mapbox/mapbox-gl-js/blob/4d2b9ad05349c1d67d2f07777de8fbe48434151b/src/data/program_configuration.js#L377-L379

If you are running into an issue with fill extrusions, please use the issue template to report it. Thanks!
