### ISSUE TITLE
Major problems with Firefox 62.0a1

### ISSUE THREAD

**Issue by ttsirkia** [mapbox/mapbox-gl-js#6728]
**mapbox-gl-js version**: Latest

**browser**: Firefox 62.0a1 (Nightly)

### Steps to Trigger Behavior

 1. See any of the examples, https://www.mapbox.com/mapbox-gl-js/example/geojson-line/

### Expected Behavior

The example works

### Actual Behavior

Labels and all custom behavior such as the GeoJSON line is missing.

Is the new Firefox broken or are there some compatibility issues?

**Comment by jfirebaugh** [comment]
It's working fine for me. Does 60.0.1 work for you?

**Comment by ttsirkia** [comment]
Firefox 60 works perfectly. The nightly 62.0a1, however, does not work at all. It renders the filled areas but all the labels, roads etc. are missing. Of course this can be a bug in Firefox but if there are some upcoming incompatible changes, it will break all recent Mapbox versions I tested. 64-bit Win10 was in use.

**Comment by ttsirkia** [comment]
Here is a screenshot comparison:

![image](https://user-images.githubusercontent.com/2797729/40510941-e20883d8-5fa6-11e8-8a46-fdfb88f18370.png)

**Comment by ttsirkia** [comment]
Firefox 61 beta releases also working, it is just the alpa (nightly) branch which has this strange behavior.

**Comment by ttsirkia** [comment]
The nightly version has been just updated and cannot reproduce anymore, closing the issue as nothing wrong here.

**Comment by ttsirkia** [comment]
The root cause in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1464089

**Comment by jfirebaugh** [comment]
Thanks for tracking down the upstream issue!
