### ISSUE TITLE
Marker with `a` element does not open the url when clicked

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#6730]
version: 0.45.0

When add marker(`a` element) to map, and click the marker. A new page with the `href` of the marker element should be opened, but nothing happened.

https://jsfiddle.net/8z8vukk0/

Try to click the red marker.

Also when you click the map, you will find that the position of the marker is changed a little.

**Comment by jfirebaugh** [comment]
Works for me too. @exotfboy is that the right example?

**Comment by exotfboy** [comment]
I am sure I can not open none of the links when I post this issue, but now I found that the link can be opened sometime(not all). I will tried to make a video to verify that.

https://i.imgur.com/wGtnQS7.gif

**Comment by ttsirkia** [comment]
I was able to reproduce this with Google and Firefox. When clicking about 50 times, there is one click which doesn't do anything.

**Comment by ttsirkia** [comment]
Now when the example has been open a while, it seems that the probability to get a "broken link" is much higher. It is easier to reproduce this with Chrome.

**Comment by jfirebaugh** [comment]
If you move the mouse between the mousedown and the mouseup, it's interpreted as a map drag rather than a click event. I suspect that's what's happening.

If you don't want to allow dragging the map via the marker element:

```
map.on('mousedown', function(e) {
    const target = e.originalEvent.target;
    if (target === marker.getElement() || marker.getElement.contains(target)) {
        e.preventDefault();
    }
});
```

**Comment by jfirebaugh** [comment]
I've also reopened #1832 -- if you are interested in adding a click tolerance option, we'd welcome a PR.

**Comment by ttsirkia** [comment]
The issue can definitely be reproduced although the mouse doesn't move at all. For some reason, it is considered as drag start.

**Comment by jfirebaugh** [comment]
I can reproduce a browser bug in Chrome that would cause this: https://bugs.chromium.org/p/chromium/issues/detail?id=721341

I guess the drag handler needs to filter out spurious move events.

**Comment by exotfboy** [comment]
As @ttsirkia  said, the link can not be opened even I do not move the mouse.

**Comment by ttsirkia** [comment]
I tried this tool https://dvcs.w3.org/hg/d4e/raw-file/tip/mouse-event-test.html but couldn't get any spurious mousemove events.

**Comment by ttsirkia** [comment]
That confirms the root cause. For some reason, it occurs more often for you. And I'm still wondering why I couldn't see the behavior with that tool.

**Comment by exotfboy** [comment]
@ttsirkia @jfirebaugh 

 Thank you guys for the insistence of finding the root cause for this unusual issue.
