### ISSUE TITLE
Hexbins visualisation

### ISSUE THREAD

**Issue by HoudaFer** [mapbox/mapbox-gl-js#6731]
Hello,
I'm making my baby steps on programming with Angular 4 and I'm using Mapbox to display a huge amount of data in different ways.cThe data is basically in CSV format but I'm converting it to Geojson with python and I request that API in the angular project.
I have made many visualisations: with markers, heatmaps, dot-density, clusters..
Now I need to make a hexbins visualisation, but I can't find any of mapbox tutorials related to that.
Is it possible to provide me some help to do it??

**Comment by jingsam** [comment]
You should tranforming your geojson data to hexbin grid data. You can do that offline or online with turf.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
