### ISSUE TITLE
Hash is broken on official examples in IE11

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6732]
**mapbox-gl-js version**: 0.45.0
**browser**: IE11

### Steps to Trigger Behavior
 1. Go to https://www.mapbox.com/mapbox-gl-js/example/3d-buildings/

### Expected Behavior
Works

### Actual Behavior
Doesn't work, as it terminates in a SecurityError because of `window.history.replaceState`.
Not only the hashing is broken but the whole map gets broken afterwards with `Unable to get property '0' of undefined or null reference` errors in gl-matrix.

    _updateHashUnthrottled() {
        const hash = this.getHashString();
        window.history.replaceState(window.history.state, '', hash);
    }

**Comment by jfirebaugh** [comment]
Thanks, fixed.
