### ISSUE TITLE
instanceof errors in IE 11

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6733]
**mapbox-gl-js version**: 0.45.0
**browser**: IE 11

### Link to Demonstration
Official examples:
- https://www.mapbox.com/mapbox-gl-js/example/animate-images/
- https://www.mapbox.com/mapbox-gl-js/example/cluster/

The examples work, but throw an error in IE 11 for `web_worker_transfer.js`.

```
Invalid operand to 'instanceof': Function expected
```

```
export function deserialize(input: Serialized): mixed {
    if (input === null ||
        input === undefined ||
        typeof input === 'boolean' ||
        typeof input === 'number' ||
        typeof input === 'string' ||
        input instanceof Boolean ||
        input instanceof Number ||
        input instanceof String ||
        input instanceof Date ||
        input instanceof RegExp ||
        input instanceof ArrayBuffer ||
        ArrayBuffer.isView(input) ||
        input instanceof ImageData) {
        return input;
    }
```

Does IE 11 require a core-js polyfill to work correctly?

**Comment by bart-1990** [comment]
I think it's because ArrayBuffer is not fully supported in IE.

**Comment by ansis** [comment]
Closing because [IE 11 is no longer supported](https://github.com/mapbox/mapbox-gl-js/blob/main/CHANGELOG.md#200). Thanks for reporting this.
