### ISSUE TITLE
The zooms in zoom-and-property ramp stops are floored

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#6742]
**mapbox-gl-js version**: v0.45.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. Add a layer with zoom-and-property styling
 2. Use fractional zoom level with at least one of the stops
 

### Link to Demonstration
demo: https://bl.ocks.org/peterqliu/raw/96a7e01f5ac71c46547a484f9ffec931/#0/15.3/-66

### Expected Behavior
In the demo, the circle is styled to go from white to red, as zoom goes from 0.9 to 1. (https://gist.github.com/peterqliu/96a7e01f5ac71c46547a484f9ffec931/#file-index-html-L48-L49)

### Actual Behavior
The color transition starts right at zoom 0.

**Comment by anandthakker** [comment]
@peterqliu this is poorly documented, but expected, behavior: https://github.com/mapbox/mapbox-gl-js/issues/5760
