### ISSUE TITLE
Click on Marker

### ISSUE THREAD

**Issue by bhartendukumar12** [mapbox/mapbox-gl-js#6749]
Hi,
I was successfully able to create the markers.Now I want to know how can I add custom data to marker and when I click on marker how can I capture that data or how to know which marker has been clicked.

Any help would be appreciated.

Thanks,
Bhartendu

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
