### ISSUE TITLE
Raster cross-fading flickers with black

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#675]
Raster cross-fade has a weird issue @ansis 

![raster-flicker](https://cloud.githubusercontent.com/assets/25395/3854163/dded3b4a-1ed2-11e4-8ad8-527722377f8c.gif)

**Comment by anandthakker** [comment]
I'm still seeing this (on master, as of 2d14cfe4ff1bb43954477345937de38b885eac42)

**Comment by ansis** [comment]
83d7c6796e17d1dab21f2984ec00d72ccfd0399b and 6171a2fc23224870c1e6d943bc4db4abbe36b525 should fix this
