### ISSUE TITLE
Large line-offset produces artifacts

### ISSUE THREAD

**Issue by andreasg123** [mapbox/mapbox-gl-js#6755]
**mapbox-gl-js version**: 0.45.0

**browser**: Chrome 66, Firefox 60; Windows 10 1709

### Steps to Trigger Behavior

 1. Create 'line' layer with GeoJSON 'LineString' source.
 2. Set 'line-width' to 5 and 'line-offset' to 12 ('line-join' and 'line-cap' are both 'round').
 3. Lines have a very variable widths.

### Link to Demonstration

'line-offset': 0
![offset-0](https://user-images.githubusercontent.com/15636985/40689049-519eec12-6355-11e8-8622-4ac64c40d485.png)

'line-offset': 4
![offset-4](https://user-images.githubusercontent.com/15636985/40689055-54becbc4-6355-11e8-8ee3-6b2e57c8c231.png)

'line-offset': 12
![offset-12](https://user-images.githubusercontent.com/15636985/40689056-5769d4c2-6355-11e8-836b-41b2903e4894.png)

**Comment by lbud** [comment]
Thanks for the report @andreasg123! We're tracking this in https://github.com/mapbox/mapbox-gl-js/issues/3809 — closing here as duplicate.

**Comment by andreasg123** [comment]
Thanks for letting me know that this is a known issue. It would be helpful if the documentation for [line-offset](https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-offset) would suggest using only `"line-join":"miter"` until this is fixed. I can confirm that the problem doesn't exist with the default `line-join`.
