### ISSUE TITLE
@mapbox/gl-matrix is gone, 0.45.0 no longer works

### ISSUE THREAD

**Issue by mbrennek** [mapbox/mapbox-gl-js#6758]
**mapbox-gl-js version**: 0.45.0

**browser**: none, install issue

### Steps to Trigger Behavior

 1. Add "mapbox-gl": "^0.45.0" as a dependency
 2. yarn install
 3. See error message "warning mapbox-gl > @mapbox/gl-matrix@0.0.1: This
error An unexpected error occurred: "Received malformed response from registry for undefined."

### Link to Demonstration

[@mapbox/gl-matrix](https://github.com/mapbox/gl-matrix) does not exist

Was it deleted after [this PR](https://github.com/mapbox/mapbox-gl-js/pull/6751) was merged?

### Expected Behavior

Repository still exists, the current release of mapbox-gl-js installs and runs

### Actual Behavior

Depends on which cache you are installing from.  My local dev machine can still pick up a cached version of gl-matrix, but our CI slaves can't find it.

**Comment by mollymerp** [comment]
The module was deprecated but I just installed it locally using `npm i @mapbox/gl-matrix` and I didn't have any issues. Maybe this is an issue with yarn? 
https://www.npmjs.com/package/@mapbox/gl-matrix

**Comment by ryanhamley** [comment]
As @mollymerp said, the `@mapbox/gl-matrix` package has been deprecated but it should still be installable. This appears to be a [sporadic issue with the NPM registry](https://github.com/yarnpkg/yarn/issues/4771).

**Comment by mbrennek** [comment]
Like I said, I can install locally on my dev box as well.  Possibly still in a CDN cache somewhere?

The npmjs link you posted links to [https://github.com/mapbox/gl-matrix](https://github.com/mapbox/gl-matrix) on GitHub, which gives me a 404.

**Comment by mollymerp** [comment]
yes, the repository was deleted because, but the module still exists on the npm registry. I have installed mapbox-gl@0.45.0 locally and remotely in a docker container without encountering this issue, so I think it may be unique to your environment. If you cannot resolve the issue, please provide the error log with the `--verbose` option enabled so we can dig in with more information.

**Comment by mbrennek** [comment]
Update: This morning our CI slaves are working again.  I thought the timing of the repo getting deleted and yarn install failing was too coincidental to not be related.

Lesson learned.  Even when you're sure it's not the package manager's fault this time, it's still the package manager's fault. Sorry to bother you.
