### ISSUE TITLE
Border around a set of polygon features

### ISSUE THREAD

**Issue by jdeboer-geoplan** [mapbox/mapbox-gl-js#6761]
## Motivation

It would be very nice to be able to put a border around a group of polygons that are linked in some way.  An example would be an outline around the highlight in https://www.mapbox.com/mapbox-gl-js/example/using-box-queryrenderedfeatures/
I've looked through raised issues but I don't see this there but i might well have missed it as I'd have thought it would be something people would want to do.

## Design Alternatives

My current design is to go to a back end server, do a union of the underlying polygons, return that as geoJSON and draw that.

## Design

I'm aware that this is hard. union of polygons is slow but I see this as more not drawing the internal lines of a style which might be simpler?

**Comment by ttsirkia** [comment]
You could use, for example, Turf.JS to define the bounding box and then convert that to GeoJSON. See `bbox` and `bboxPolygon` (http://turfjs.org/docs#bbox) Using those both should give you the answer.

**Comment by ttsirkia** [comment]
Also `union` available there, if that was more you were looking for.

**Comment by jfirebaugh** [comment]
Hi @jdeboer-geoplan! I don't think this is a feature we're likely to build into Mapbox GL itself -- we want to keep it focused on map rendering rather than general purpose geoprocessing -- so the approach that @ttsirkia suggests using Turf is probably the best.

**Comment by vinaynb-at** [comment]
@jdeboer-geoplan I trying to achieve something similar as your use case. Did you manage to build the feature ?

**Comment by jdeboer-geoplan** [comment]
Hi @vinaynb-at I am still building the outline polygon on a back end server and adding them as a geoJson layer, still think it would be nice to have in mapbox gl but never got time to think about it more fully.

**Comment by vinaynb-at** [comment]
@jdeboer-geoplan thanks for your reply.
