### ISSUE TITLE
Is it possible to add support to different vector tile formats?

### ISSUE THREAD

**Issue by NameFILIP** [mapbox/mapbox-gl-js#6763]
Currently, the supported format is XYZ, but there are others:
* https://gis.stackexchange.com/questions/132242/what-are-the-differences-between-tms-xyz-wmts
* https://gist.github.com/tmcw/4954720#gistcomment-1570349

We have a service that serves data using S2 cells. How hard is it to make the vector tile interface generic with and ability to have separate implementations for different tile formats?

**Comment by ttsirkia** [comment]
XYZ is just a scheme to construct the URL. The server returns protobuf-encoded tiles. So did you actually mean the format of the URL or the contents retrieved from the address?

**Comment by NameFILIP** [comment]
Aren't these two connected? XYZ and S2 are different ways to split the globe into cells. So, both, the url and the contents will change.

[S2 Cells](https://medium.com/sidewalk-talk/s2-cells-and-space-filling-curves-keys-to-building-better-digital-map-tools-for-cities-a312aa5e2f59)

**Comment by ttsirkia** [comment]
If I understood correctly, S2 is just a way to define the location and its boundary but it doesn't give any spesification about the data format that should be used to return the vector tile contents. So, you are talking about the URL patterns not the actual vector tile format?

**Comment by mollymerp** [comment]
We already support `TMS` for raster sources, and it looks like it should work for vector sources too but it's just not documented. 

Supporting S2 cells is not on our roadmap at this time and would require a significant refactor/rewrite of a large portion of the codebase.
