### ISSUE TITLE
Is it possible to use a expression in an "icon-image" tag?

### ISSUE THREAD

**Issue by SantiagoHorcajo** [mapbox/mapbox-gl-js#6765]
Hi, the question is more related to mapbox style specification than to mapbox-gl-js

### Question
In [tileserver-gl](https://github.com/klokantech/tileserver-gl) it's possible to use JSON style files following mapbox style format just to render vector tiles from OpenMapTiles.
I can use without errors the following style to render some POIs with an icon coming from an sprite:
     "icon-image": "airport_11",
but If I try to use an expression like the following:
     "icon-image": ["at", 1, ["airport_11", "airfield_11"]],
when trying to recover the map in Firefox I get the following error in the console:
     Error: layers[91].layout.icon-image: string expected, array found
So, the question is: does mapbox style specification allow the use of expressions with "icon-image" tag or is a bug of tileserver-gl?

### Links to related documentation
The expression ["at"](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-lookup) retreives an item from an array

Thanks in advance,
Santiago

**Comment by jfirebaugh** [comment]
It looks like tileserver-gl is not using a version of Mapbox GL that supports expressions.

However, when it's updated, note that you need to use a `"literal"` operator if you want to embed a literal array in an expression:

```
"icon-image": ["at", 1, ["literal", ["airport_11", "airfield_11"]]]
```

**Comment by SantiagoHorcajo** [comment]
Thanks, jfirebaugh
