### ISSUE TITLE
Can it support 3dtiles format?

### ISSUE THREAD

**Issue by tangjuncheng1986** [mapbox/mapbox-gl-js#6766]

**Comment by jfirebaugh** [comment]
I'm not sure what you mean by "3dtiles format". Maybe you're looking for #3996 or #1489.

**Comment by tangjuncheng1986** [comment]
Thank you.The "3d-tiles"  has entered the Open Geospatial Consortium (OGC) Community Standard process. https://github.com/AnalyticalGraphicsInc/3d-tiles.

**Comment by tomvantilburg** [comment]
Late to the party but there is a preliminary extension now for mapboxgl to support 3D tiles: [https://github.com/Geodan/mapbox-3dtiles](https://github.com/Geodan/mapbox-3dtiles)
