### ISSUE TITLE
Style object literal not compatible with MapboxOptions

### ISSUE THREAD

**Issue by Squrrli** [mapbox/mapbox-gl-js#6767]
Hello, I was trying to set up a video layer (following the guide on the Mapbox tutorials page.

Everything to this point has worked but when i had 'layers': {} to the style object the map is not created saying: 
Argument of type '{ container: string; style: { 'version': number; 'sources': { 'satellite': { 'type': string; 'url...' is not assignable to parameter of type 'MapboxOptions'.
  Types of property 'style' are incompatible.
    Type '{ 'version': number; 'sources': { 'satellite': { 'type': string; 'url': string; 'tileSize': numbe...' is not assignable to type 'string | Style'.
      Type '{ 'version': number; 'sources': { 'satellite': { 'type': string; 'url': string; 'tileSize': numbe...' is not assignable to type 'Style'.
        Types of property 'layers' are incompatible.
          Type '{ 'id': string; 'type': string; 'source': string; }[]' is not assignable to type 'Layer[]'.
            Type '{ 'id': string; 'type': string; 'source': string; }' is not assignable to type 'Layer'.
              Types of property 'type' are incompatible.
                Type 'string' is not assignable to type '"symbol" | "raster" | "fill" | "line" | "circle" | "fill-extrusion" | "background" | "heatmap"'.

For reference i copied the code from here (https://www.mapbox.com/mapbox-gl-js/example/video-on-a-map/) as what i had written was not working either.

When I removed the layers: [] from this style object the map will work again but no video is displayed.

Any help would be greatly appreciated.

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example that demonstrates the issue? It sounds like you're using flow, so this will probably need to be in a repo with a package.json rather than jsbin.com or similar.
