### ISSUE TITLE
Click events are inconsistent on Macbook Pro Trackpad

### ISSUE THREAD

**Issue by ChiefKleef** [mapbox/mapbox-gl-js#6775]
**macbook**: MacBook Pro (15-inch, 2016)

**mapbox-gl-js version**: 0.45.0

**browser**: Chrome (latest)

Normal trackpad clicks are often misinterpreted as nonclicks.

### Steps to Trigger Behavior

 1.  Click on the map quickly.
 1.  Sometimes the click event does not fire.

Behavior seen at the final click of [this GIF](https://i.gyazo.com/7a95726480c1c7edc282cb547e9bb50c.gif)

### Expected Behavior
Trackpad mapbox-gl click events should have the same sensitivity as DOM click events.

### Actual Behavior
Trackpad mapbox-gl click events are less sensitive than DOM.

**Comment by pathmapper** [comment]
Sounds like it could be the same issue as described in https://github.com/mapbox/mapbox-gl-js/issues/6730. Maybe https://github.com/mapbox/mapbox-gl-js/pull/6757 fixes your issue?

**Comment by ChiefKleef** [comment]
I don't think it's the same issue described in #6370 . Mine is related directly to clicking on the canvas and firing of the main 'click' event. However, #6757 seems promising.

**Comment by jfirebaugh** [comment]
I'm pretty sure #6757 fixes this issue.
