### ISSUE TITLE
How to set label for marker ?

### ISSUE THREAD

**Issue by Rajavelu** [mapbox/mapbox-gl-js#6776]
Hi,

How to set text label for a marker?

Created marker as following:
var el = document.createElement('div');
el.id = 'vmaps-marker';
new mapboxgl.Marker(el, {offset:[*, *]}).setLngLat([lon, lat]);

Can be set label if i create marker using a symbol layer. But how to set label if i create marker using above new mapboxgl.Marker() method ?

**Comment by jfirebaugh** [comment]
Use HTML elements to achieve the desired rendering, and pass that to the `Marker` constructor.

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
