### ISSUE TITLE
Fullscreen in Chrome keeps the height of the non-fullscreen map

### ISSUE THREAD

**Issue by ezk84** [mapbox/mapbox-gl-js#6777]
As it says in the title. On Firefox it works as expected.

**mapbox-gl-js version**: 0.45.0

**browser**:  Chrome 66.0.3359.181 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Open the demonstration below
 2. Click the fullscreen button on top-right corner.
 3. Observe height of map.

### Link to Demonstration

https://codepen.io/ezk84/pen/XYdOgN

### Expected Behavior
The fullscreen map should be as high as the screen is high (height: 100%)

### Actual Behavior
The fullscreen map maintains the height set on the non-fullscreen version.

**Comment by ralphking** [comment]
You've set your containing div to 500px height, so thats all the max height the map will ever reach. 

This works as expected: https://codepen.io/anon/pen/dKMEpZ

**Comment by jfirebaugh** [comment]
Thanks @ralphking. That's correct, you'll need to adjust the CSS.

**Comment by ezk84** [comment]
This isn’t what I would expect: you’re saying that the only way to have a map that when normal has a set non-100% height *and* is full-screenable is to have some extra code to modify the CSS when I press the full screen button. That to me sounds like the full screen button is defective. 

Somehow in Firefox it works as expected.

**Comment by ondrej-vesely** [comment]
Sorry for opening old thread, however the fullscreen feature should definitely override the div style.
Luckily, you can just use **min-height** instead of **height.**

https://codepen.io/anon/pen/LrKagG
Works as expected.
