### ISSUE TITLE
Fixing matrix errors

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6782]
Failed to invert matrix errors are quite bad, as they get the UI in a "stuck" state, where no interaction have any effect. Effectively the map part of the application is frozen.

I've been debugging how do they happen using Sentry in a live production site, as otherwise I couldn't reproduce it on my machine, but they happen very regularly to users (across all kind of browsers).

There are multiple ways a map can get into this illegal state, here is the most common one:

1. **scroll_zoom / _onScrollFrame /  delta !== 0** is not run first. This means that `this._targetZoom` is not initialized.
https://github.com/mapbox/mapbox-gl-js/blob/b9e32bf6cebfe830bf6faa9be8635dc31709a4ff/src/ui/handler/scroll_zoom.js#L207

2. **interpolate** receives a value with `undefined` as the second parameter. The way interpolate is written, it'll turn this into `NaN`, even if k is 0. 
https://github.com/mapbox/mapbox-gl-js/blob/b9e32bf6cebfe830bf6faa9be8635dc31709a4ff/src/ui/handler/scroll_zoom.js#L235

3. **geo / transform / set zoom** has a guard for making sure a value is between min and max zoom, but this guard doesn't protect against NaN. 
https://github.com/mapbox/mapbox-gl-js/blob/b9e32bf6cebfe830bf6faa9be8635dc31709a4ff/src/geo/transform.js#L161

4. **NaN** goes through setZoom and just kills the matrix calculations.

Recommendations:

1. By far the safest and simplest option is to guard **set zoom**. This'll protect against all kind of errors, not just this.  I recommend adding an 

```
if (typeof zoom !== 'number' || !isFinite(zoom)) return
```

guard at the first line.

2. Interpolate could return a value without calculation if t is 0 or 1, both as an optimization as well as making it more reliable.

3. scroll_zoom should be fixed so that _targetZoom and _easing is always initialised.

@anandthakker @mourner @jfirebaugh

**Comment by bravecow** [comment]
We are getting same errors after upgrade to v45:

![image](https://user-images.githubusercontent.com/988471/41221350-8b8b1164-6d6c-11e8-8f63-0da69009e2f8.png)

Downgrading to 44 😞

**Comment by andrewharvey** [comment]
see also #6486

**Comment by hyperknot** [comment]
@bravecow I think this was present in 0.44 as well, look at #6486. 
https://github.com/mapbox/mapbox-gl-js/pull/6029 appeared in 0.44.0 I believe.

**Comment by hyperknot** [comment]
Two more paths for an illegal matrix error.

1. This line:
https://github.com/mapbox/mapbox-gl-js/blob/b9e32bf6cebfe830bf6faa9be8635dc31709a4ff/src/ui/handler/scroll_zoom.js#L244
sets zoom to `undefined`. `undefined` gets turned into NaN after the min-zoom guard, which again sets zoom to NaN.

2. `_easing()` is not present at this point:
https://github.com/mapbox/mapbox-gl-js/blob/b9e32bf6cebfe830bf6faa9be8635dc31709a4ff/src/ui/handler/scroll_zoom.js#L234

Causes an exception and later an assertion error, but I believe this doesn't propagate to illegal matrix error.

**Comment by hyperknot** [comment]
What would you like to be the solution here? I can make a PR for adding 

```
if (typeof zoom !== 'number' || !isFinite(zoom)) return
```

to set zoom. This would solve all the problems in practice, as a quick term solution.

A better solution of revised scroll logic should still be considered in the future though.
