### ISSUE TITLE
Is there anyway to extend the XYZ computing rules without modifying the source code?????

### ISSUE THREAD

**Issue by DLCJianyf** [mapbox/mapbox-gl-js#6786]
I am using baidu map. it's XYZ calculation rules are a little different. if using mapboxgl's rule, the unfolded map will be a mess
![tim 20180607224538](https://user-images.githubusercontent.com/18675306/41107259-9819fa50-6aa4-11e8-89c4-6cd9af9da072.png)

baidu:
![14141738-6ebc1eeccd0f4cd189eb50c11683947c](https://user-images.githubusercontent.com/18675306/41106830-7d8c394c-6aa3-11e8-8691-24611390fb1f.png)

google:
![13172344-e075238b682b4e6b8d208334433b8cbc](https://user-images.githubusercontent.com/18675306/41106911-b6bb6440-6aa3-11e8-879a-cf33b3bad89f.png)

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. Unfortunately, I don't think this is something we can help you with; this issue tracker is for reporting bugs and feature requests in Mapbox GL. For "how do I" questions involving Baidu maps, you'll need to ask elsewhere.
