### ISSUE TITLE
When is next release?

### ISSUE THREAD

**Issue by grillorafael** [mapbox/mapbox-gl-js#6798]
### Question

Hi all,

Just want to know when is the next date for a release. There are loads of good stuff added since `0.45.0` and I didn't find anywhere saying when is the next release date.

Would be great to have a release schedule (i.e. Monthly? Weekly? Every x days?)

**Comment by andrewharvey** [comment]
`v0.46.0-beta.1` just landed -> https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.46.0-beta.1

**Comment by mollymerp** [comment]
barring any major setbacks, final release should be out next wednesday 6/20
