### ISSUE TITLE
Map#getLayer throws undefined error

### ISSUE THREAD

**Issue by gzurbach** [mapbox/mapbox-gl-js#6801]
**mapbox-gl-js version**: 0.45.0

**browser**: experienced in multiple browsers

### Steps to Trigger Behavior

 1. Create new map `new mapboxgl.Map()`
 2. Wait for `map.on('load', ...)`
 3. Call `map.addSource` to load GeoJSON data then `map.addLayer`
 3. Call `map.getLayer('layer-id')`

### Expected Behavior

Call should return the layer with the specified ID, or undefined if the ID corresponds to no existing layers.

### Actual Behavior (intermittent)

We experience this intermittent error: 
```
Cannot read property 'getLayer' of undefined
```

The stack points to this line:
```js
n.prototype.getLayer = function(t) {
  return this.style.getLayer(t)
}
```

It's not easy to reproduce consistently and I don't have enough understanding of MapboxGL's internals to comprehend why `this.style` is still `undefined` considering my code is within the `on('load', ...)` callback. Let me know if a larger code sample would help.

**Comment by gzurbach** [comment]
Closing this as I realized the mistake was mine. Sorry for the noise!

**Comment by llaver** [comment]
> Closing this as I realized the mistake was mine. Sorry for the noise!

This has been most helpful..

**Comment by StuRuby** [comment]
I met the same mistake again , can you tell me how do you solve it that time?

**Comment by 3zzy** [comment]
In my case, I hadn't set the `style` correctly when initializing the map, so `addSource` threw this error.
