### ISSUE TITLE
unknown property lineMetrics error

### ISSUE THREAD

**Issue by georgem3** [mapbox/mapbox-gl-js#6802]
As per documentaion: I'm trying to use the line-gradient effect. The source is "geojson" and the layer is "line". Adding the lineMetrics property (set to true) throws the above error.

Source object:
```
exports.createGeoJSON = function(coords) {
    this.type = "geojson";
    this.data = {
        "type": "FeatureCollection",
        "features": [{
            "type": "Feature",
            "properties": {},
            "geometry": {
                "coordinates": coords,
                "type": "LineString"
            }
        }]
    };
    this.lineMetrics = true;            ///// throws error when added
    this.tolerance = 1;
}
```

**Comment by ryanhamley** [comment]
Hi @georgem3 are you using version 0.45.0? Line gradients were added in this version so anything older will not have the `lineMetrics` option.

**Comment by georgem3** [comment]
I must've missed the release, that solved it thanks! Is rgba() the only supported format for colors?

**Comment by ryanhamley** [comment]
No, you can use any valid [color type](https://www.mapbox.com/mapbox-gl-js/style-spec#types-color) in the line-gradient expression. You can see that our [official example](https://www.mapbox.com/mapbox-gl-js/example/line-gradient/) uses color names.
