### ISSUE TITLE
0.45 seems to break with "." in layer ID (still) 

### ISSUE THREAD

**Issue by georgem3** [mapbox/mapbox-gl-js#6804]
Referenced initially in #6660, PR #6700 doesn't seem to fix this:
Layers wouldn't render unless "."s were replaced/deleted in ID

Same error:
```
this.parent.getWorkerSource(...)[a[2]] is not a function
...
```

**Comment by anandthakker** [comment]
@georgem3 the bug fix was merged since the 0.45 release.  It should be available soon in the next release.
