### ISSUE TITLE
semi-transparent lines and joins

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#681]
Current line tessellation is designed for opaque lines. Bevelled and round joins overlap with the line. I'm wondering if we could change this so that lines can be safely drawn semi-transparently.

![screen shot 2014-08-10 at 4 33 30 pm](https://cloud.githubusercontent.com/assets/1421652/3870946/daf57e50-20e6-11e4-8e60-e6d3e8cd36e8.png)

**Comment by mourner** [comment]
Good enough now right?

**Comment by lbud** [comment]
^ still problematic in round line joins: 
![image](https://cloud.githubusercontent.com/assets/3170312/5962472/0e8b0b02-a799-11e4-9b32-87dbf70f33fd.png)
(https://github.com/mapbox/mapbox-gl-js/issues/794)

**Comment by mourner** [comment]
@lbud should we keep both open or close one?

**Comment by lbud** [comment]
Eh keep closed I suppose; I'll refine the scope of the other ticket.
