### ISSUE TITLE
Style spec bug with 'none' combiner filter

### ISSUE THREAD

**Issue by sanjin-saric** [mapbox/mapbox-gl-js#6817]
**mapbox-gl-js version**:
Latest
**browser**:
Any
### Steps to Trigger Behavior

Put a filter on layer with 'none' combiner. 
As functions put two expressions. The style will not get validated.
Something like: 
```json
"filter": [
            "none",
            [
                ">",
                [
                    "number", ["get", "prop1"]
                ],
                10000
            ],
            [
                "<",
                [
                    "number",
                    [ "get",  "prop2" ]
                ],
                10000
            ]
        ],
```

The  culprit lies here (`src/style-spec/feature_filter/index.js`): 

```javascript
switch (filter[0]) {
    case 'has':
        return filter.length >= 2 && filter[1] !== '$id' && filter[1] !== '$type';

    case 'in':
    case '!in':
    case '!has':
    case 'none':
        return false;

    case '==':
    case '!=':
    case '>':
    case '>=':
    case '<':
    case '<=':
        return filter.length === 3 && (Array.isArray(filter[1]) || Array.isArray(filter[2]));

    case 'any':
    case 'all':
        for (const f of filter.slice(1)) {
            if (!isExpressionFilter(f) && typeof f !== 'boolean') {
                return false;
            }
        }
        return true;

    default:
        return true;
    }
```

The `none` combiner should be with 'any' and 'all' as the documentation states

> The "all", "any", and "none" filter operators are used to create compound filters. The values f0, ..., fn must be filter expressions themselves.

Although, blatantly moving this case will probably not fix the issue. Im just reporting it for now.

**Comment by jfirebaugh** [comment]
Hi @sanjin-saric! The portion of the documentation you quoted is in the "Filter (deprecated syntax)" section. Expression-based filters do not support a "none" expression operator -- use `["!", ["any", ...]]` instead.

**Comment by sanjin-saric** [comment]
Thanks!
