### ISSUE TITLE
GeoLocation Controls not getting created via npm (but works with cdn)

### ISSUE THREAD

**Issue by sentiasa** [mapbox/mapbox-gl-js#6822]
First, I have created the exact same map with mapbox-js CDN and now I have installed it from NPM. On the one I have installed via npm, it doesn't show geolocation controls however it does on the CDN version. (navigation controls work on both cdn and npm so it's not a path problem).

```
map.addControl(new mapboxgl.GeolocateControl({
         positionOptions: {
              enableHighAccuracy: true
         },
         trackUserLocation: true
}));

map.addControl(new mapboxgl.NavigationControl());
```

Checking on the html,  this is the CDN version:
![screen shot 2018-06-15 at 02 40 05](https://user-images.githubusercontent.com/9021386/41444773-7d06ef1a-7045-11e8-82e2-cc30087f7d0b.png)

But checking on the NPM version:
![screen shot 2018-06-15 at 02 41 27](https://user-images.githubusercontent.com/9021386/41444811-af7474ae-7045-11e8-9f73-a58a5ff08213.png)
it doesn't create this line (also I don't receive any errors in the console):
```
<button class="mapboxgl-ctrl-icon mapboxgl-ctrl-geolocate" type="button" aria-label="Geolocate" aria-pressed="false"></button>
```
_In the screenshots, they are the other way around for cdn and npm however I tried it both ways, and same issue continues._

**mapbox-gl-js version**: "_id": "mapbox-gl@0.45.0" 
Also: `<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.45.0/mapbox-gl.js'></script>`

**browser**: Chrome Version 67.0.3396.87 OSX

Also, on the NPM version, it does show the navigations but as you can see it shows a grey empty div for geolocation.
![screen shot 2018-06-15 at 02 44 54](https://user-images.githubusercontent.com/9021386/41444888-27726e84-7046-11e8-82a8-2db840d90389.png)

------

Did I do something wrong or is this a bug?

**Comment by andrewharvey** [comment]
Are your mapbox js and css pointing to the same release?
