### ISSUE TITLE
How to trigger a layout update after addImage?

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6824]
**mapbox-gl-js version**: 0.45.0

### Question
When `addImage` is run after a source/layer, the images will never appear on the current integer zoom level. On other zoom levels they display fine.

My JSBin: https://jsbin.com/riwutuw

This is also tracked as a bug here: https://github.com/mapbox/mapbox-gl-js/issues/6231

My question is that how is it possible to trigger a layout update/re-render for the current zoom?

**Comment by jfirebaugh** [comment]
Let's keep discussion on #6231.
