### ISSUE TITLE
Many symbols per tile at max zoom causes incorrect displaying of symbols.

### ISSUE THREAD

**Issue by ckyleda** [mapbox/mapbox-gl-js#6825]
**mapbox-gl-js version**: 0.40.0

**browser**: Chrome 67.0.3396 (Linux)

### Steps to Trigger Behavior

Load an arbitrary amount of symbols (or, possibly a few symbols with large amounts of properties - I am unsure whether the amount of data in the symbol can also trigger this issue.)
And zoom in.

This is definitely related to https://github.com/mapbox/mapbox-gl-js/issues/2907 - with the symbol array only being uint16 and there being an overview. But as I am not rendering that many symbols, it also seems that the amount of properties in the symbols also can cause an overflow.

The previous suggested code to convert this array to a more suitable type, such as uint32, no longer works due to architecture changes.

What's the rationale behind having such a limited array for symbol storage? Is it possible to modify this to support many more, and more complex symbols?

### Expected Behavior

Any amount of symbols should be renderable on the map.

### Actual Behavior

"Too many symbols being rendered in a tile." thrown in console, and map then does not display any further symbols and 'hangs' for a while until presumably the symbol buffer has been cleared out.

**Comment by mollymerp** [comment]
@ckyleda thanks for using mapbox-gl-js and sorry you're having an issue! can you please create a minimal reproduction of the issue you're seeing on jsbin or jsfiddle, and upgrade to the most recent version of this library (v0.46.0-beta.1)

**Comment by ckyleda** [comment]
@mollymerp Unfortunately this is not reproducible in jsbin/jsfiddle - the required amount of symbols apparently needed to trigger this simply refuse to render with no error.

Upgrading is also a no-go. However, this issue has existed since 2016, so I doubt it's been fixed recently. However, I can verify that it is triggering the exact same warning that was implemented in that issue.

**Comment by mollymerp** [comment]
@ckyleda our symbol placement implementation has changed dramatically and that error is no longer emitted by mapbox-gl-js. The current versions don't have a hard cap on the number of symbols and we don't patch older versions, so I'm afraid you'll have to upgrade in order to get around this error. Closing here, but if you still have trouble with the current version please open a new ticket.
