### ISSUE TITLE
Clarify documentation for sprite property

### ISSUE THREAD

**Issue by ryanhamley** [mapbox/mapbox-gl-js#6832]
The style docs say that the [`sprite` property is required](https://www.mapbox.com/mapbox-gl-js/style-spec#root-sprite) if a layer uses the `background-pattern`, `fill-pattern`, `fill-extrusion-pattern`, `line-pattern` and `icon-image` properties. [The standalone sprite section](https://www.mapbox.com/mapbox-gl-js/style-spec#sprite) of the docs however doesn't mention the `fill-extrusion-pattern` requirement.

In either case, this is confusing. These properties may be necessary when setting up a map's root style, but at runtime you can use the `addImage` method to help setup a layer that makes use of the `*-pattern` and `icon-image` properties without requiring a sprite URL.

This came up as I was trying to add validation for styles that use the "required" properties without a sprite URL in #6831. A strict test that throws an error turns out to be a breaking change for styles that use these properties in runtime via `addImage`.

**Comment by jfirebaugh** [comment]
Aha -- yes, we even used to have the validation, but removed it with the addition of `addImage`.

https://github.com/mapbox/mapbox-gl-js/commit/f50a30453649421c2f30877bdcb4e33dfd0b273f#diff-d2fa2e781710b64955ee1cf6467242d4

#6231 is related. The ideal behavior in my opinion is to validate that image references are valid at the time they are added to the style.

**Comment by ansis** [comment]
The docs now mention `fill-extrusion-pattern`. It also no longer says that the sprite is required ("its icons can be used to render..."). The docs could be better (like all our style-spec docs could be) but these specific issues seem fixed.
