### ISSUE TITLE
queryRenderedFeatures bbox broken with circle-translate

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6833]
**mapbox-gl-js version**: 0.45.0
**browser**: Chrome latest

### Steps to Trigger Behavior
 1. Have a circle layer with `circle-translate`
 2. Run `queryRenderedFeatures` with bbox on that layer

### Link to Demonstration
https://jsbin.com/viqafex
(based on official example "using-box-queryrenderedfeatures")

### Expected Behavior
All features should be selected

### Actual Behavior
Some features are randomly missing. If you move the map around, different features are missing.

![screenflow](https://user-images.githubusercontent.com/494223/41571924-bdb65ac2-7375-11e8-8210-592853ba0618.gif)

**Comment by mourner** [comment]
Related: #2653

**Comment by ThiyagarajanShivSankaran** [comment]
@mourner Even we are also facing this issue. Please, fix this immediately.

**Comment by hyperknot** [comment]
@ThiyagarajanShivSankaran a workaround is to add a helper layer with `circle-opacity: 0` and no `circle-translate`. It's not super precise but works well.
