### ISSUE TITLE
Better multitouch zoom/pan/rotate support

### ISSUE THREAD

**Issue by msbarry** [mapbox/mapbox-gl-js#6838]
## Motivation

When you touch the map to zoom pan or rotate on a mobile device, the drag pan handler and touch zoom/rotate handler don't quite feel as natural as what mapbox-gl-native provides.  The goal of the interaction should be to keep the same points on the map beneath your fingers as you move them so it feels like you're directly manipulating the map, but:

- when you put two fingers down at exactly the same time, you can't pan the map during a zoom or zoom/rotate (maybe this is a bug?)
- when you put two fingers down at slightly different times, you can pan/zoom/rotate at the same time but the map "slips" and the same points don't stay below your two fingers. Mapbox-gl-js tries to keep the same points on the map below both fingers.

## Design Alternatives

There are a few different ways that I can see to accomplish this:

- slight tweaks to drag pan and touch zoom/rotate handler to attempt to keep the same points on the map below your fingers as you zoom/drag/pan
- a new integrated multitouch handler in mapbox-gl-js that tracks each current touch, where it started and where it is now and attempts to apply the drag/zoom/rotate that best map “from” points to “to” points, like [this demo](https://rawgit.com/axelpale/nudged/master/examples/nudged-gesture/index.html) ([source](https://github.com/axelpale/nudged/blob/master/examples/nudged-gesture/lib/Model.js)) for the [nudged library](https://github.com/axelpale/nudged)
- a separate package that implements the integrated multitouch handler

## Design

Please help me pick which design alternative to go with.

### Mock-Up

n/a - no UI components

### Concepts

This might slightly change the effect of the drag/zoom/rotate options depending on which alternative we go with.

### Implementation

This only affects mapbox-gl-js. The implementation depends on which design alternative we go with.

I am happy to help implement any of the alternatives, just let me know which is the best place to put it.

**Comment by msbarry** [comment]
A better name may be “make touch interaction closer to native.” The logic seems easier to express in a single handler that tracks “from” touch points and the “to” points they each map to then figures out the transform, rotate, and/or zoom that best maps from points to to points. The same goal may be accomplished with tweaks to the separate drag and zoom/rotate handlers.

**Comment by mollymerp** [comment]
@msbarry hi there, thanks for using mapbox! if this is a feature request, can you please fill out all the requested information in the [issue template](https://github.com/mapbox/mapbox-gl-js/blob/v0.46.0/.github/ISSUE_TEMPLATE/Feature_request.md) so we can fully understand and evaluate the request?

**Comment by msbarry** [comment]
Thanks @mollymerp, updated the description.  There are a few alternatives so I'm not sure which to suggest for implementation. Let me know what you think or if you need more information.

**Comment by mollymerp** [comment]
Thanks for the clarification @msbarry. 
> when you put two fingers down at exactly the same time, you can't pan the map during a zoom or zoom/rotate (maybe this is a bug?)

this isn't a bug – we don't yet support two-finger panning (tracked at #2618)

> when you put two fingers down at slightly different times, you can pan/zoom/rotate at the same time but the map "slips" and the same points don't stay below your two fingers. Mapbox-gl-js tries to keep the same points on the map below both fingers.

I can't reproduce this – the initial touchpoints stay below my fingers as I zoom/pan on mobile, but I'm not actually sure that this is desired behavior anyways (we shouldn't require users to place their fingers at slightly different times) 

I think this also might duplicate some of the conversation in #2618, so I'm thinking we should consolidate this issue over there.

**Comment by msbarry** [comment]
For the latter I think that #6722 might be the main source of inconsistency I see. Sounds good moving conversation over to #2618, if we have a two finger pan that plays nicely with the touch zoom rotate handler then it should solve most of the issue.

**Comment by jfirebaugh** [comment]
Yeah, I think #6722 is the second issue, and let's centralize discussion of multitouch panning at #2618.
