### ISSUE TITLE
Support rendering 3d extrusions

### ISSUE THREAD

**Issue by amyleew** [mapbox/mapbox-gl-js#684]
Please add building height styling options for building data  in Mapbox GL. 

Specifically [building data](https://www.mapbox.com/carto/api/2.3.0/#building
) in CartoCSS can be rendered in a 3d look using building-fill, building-fill-opacity, and building-height.

Can we add this functionality to Mapbox GL?

**Comment by trallarn** [comment]
I know this issue is closed, but I can't find any doc on how to render extrusions. Has this feature really been added?

**Comment by kkaefer** [comment]
No, this features hasn't been added yet. There's an experimental branch that has real buildings, which will eventually get merged though.

**Comment by jonathanward** [comment]
What is the status of development on the 2.5d line extruding?

**Comment by ansis** [comment]
implementing this:

### the first part

- merge the earcut branch https://github.com/mapbox/mapbox-gl-js/pull/1606
- roughly recreate [the really old demo branch](https://github.com/mapbox/mapbox-gl-js/tree/building) ([example](https://www.mapbox.com/bites/00135/#15.92/40.7212/-73.9928/-39.3)) on top of master. Manually rewriting everything with the old branch as a guide is probably better than trying to rebase.
- figure out how this should look in the style spec. Discuss and implement that
- add render tests
- port to -native

### followup

- fix antialiasing (draw faded 1px lines along all edges?)
- fix depth related bugs

**Comment by lbud** [comment]
I've roughly recreated last year's demo branch at https://github.com/mapbox/mapbox-gl-js/tree/building-redux (thanks to the codespirit of @ansis 👻 the old branch ported pretty easily).

![image](https://cloud.githubusercontent.com/assets/3170312/15556773/a685e50a-229d-11e6-9505-42a0233bd2b8.png)

Shaders at https://github.com/mapbox/mapbox-gl-shaders/tree/js-buildings, a spec branch (filled in only by copying fill properties for validation purposes, not definitive spec suggestions) at https://github.com/mapbox/mapbox-gl-style-spec/tree/buildings. I've modified this repo's debug page/style in this branch for the sake of quick iteration, not to be merged.

Still lots of TODOs to clean up rough edges in this branch + will open a spec ticket to discuss what this should look like.

**Comment by jonathanward** [comment]
Nice work with the development!

I wanted to get a sense of how far along the development progress is - how long do you expect until functionality analogous to [http://keks.com/dev/line3/ ](http://keks.com/dev/line3/ ) will be present.

**Comment by lbud** [comment]
@jonathanward at this time this feature is still very much in development, and spec changes are still not finalized at https://github.com/mapbox/mapbox-gl-style-spec/issues/456, so I really can't give a timeline — though it is looking like at least initially we don't plan to support extruding non-polygon features.

**Comment by lbud** [comment]
quick status update:
* most of the spec changes proposed for extrusions are implemented in mapbox-gl-js; mostly finished with adding data-driven properties and then need to figure out antialiasing
* after that, still need to 
  * port to native
  * work with Studio team to integrate extrusion type
  * solidify spec changes and do releases of -js, -native and -spec

**Comment by contra** [comment]
@ibud Any docs for enabling this feature? Didn't see any in the PR. Demos look great BTW - thanks a lot for putting in the work!

**Comment by lbud** [comment]
@contra check out the accompanying style spec PR https://github.com/mapbox/mapbox-gl-style-spec/pull/495 — the `fill-extrude-base` and `fill-extrude-height` paint properties enable this, so a fill layer for buildings might include a property function like 
```
"paint": {
    "fill-extrude-height": {
        "stops": [[0, 0], [1000, 1000]],
        "property": "height"
    }
}
```

if the specified source layer has a property called "height" in its features. 
This feature will be in the next Mapbox GL JS library release.
