### ISSUE TITLE
Expressions convert functions: output linear interpolation? 

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#6840]
In the [functions to convert deprecated functions to expressions](https://github.com/mapbox/mapbox-gl-js/blob/a5a8dfe5b90737dbb295eaca7f41c667ae4060a8/src/style-spec/function/convert.js), we are converting functions with type `exponential` and base `1` to interpolation expressions with type `["exponential", 1]`. While this is the most exact conversion, would it be more useful to convert these to type `["linear"]`?

/cc @anandthakker @jfirebaugh @tristen @aparlato

**Comment by Jo-IE** [comment]
Hi! I would like to work on this :)

I have a quick clarification:
So when `base` equals 1, we would just change the expression to look like this `expression = ['interpolate', ['linear'], ['number', ['get', parameters.property]]] `

and this should be done in both the `convertPropertyFunction` and the `convertZoomFunction`?

Thank you!

**Comment by tristen** [comment]
👋 @Jo-IE 

> So when `base` equals 1, we would just change the expression to look like this `expression = ['interpolate', ['linear'], ['number', ['get', parameters.property]]] `

Correct!

> and this should be done in both the `convertPropertyFunction` and the `convertZoomFunction`?

Correct too!

**Comment by Jo-IE** [comment]
Thank you @tristen!
