### ISSUE TITLE
Animating a point uses a lot of CPU on the latest versions

### ISSUE THREAD

**Issue by CombesA** [mapbox/mapbox-gl-js#6844]
**mapbox-gl-js version**: v0.45.0

**browser**: Chrome v67.0

### Steps to Trigger Behavior

 1. Load the fiddle linked below.
 2. Put your accessToken on top of the JS file.
 3. You can change the mapbox version in the link to the mapbox script in the head of the html file.

### Link to Demonstration
https://jsfiddle.net/CombesA/wdkf8xqr/4/

Hello there !

My team and I have been working with mapbox for some time now, and we wanted to implement a "pulse" effect on a point.

I found someone online who showed a way to do it (https://bl.ocks.org/danswick/2f72bc392b65e77f6a9c), so I took it and modified it a bit to suit our needs.
But when implementing it in our solution, I saw that a pulse effect on a single point made our browsers (tested on Chrome, Edge, Firefox) use around 50-60% of our CPU.
The problem was that, when taking the exact same code as the person who came up with this idea, CPU usage was not more than 10-15%.
I noticed then that he did this effect while being on the release 12.2 of Mapbox. We're working with the version 45.0, but I tested it on the 46.0 and the CPU usage is still as high.

After doing some testing this animation with different versions of MapBox, I noticed that the CPU usage was starting to get pretty high after the 22.1 release. 22.0 seems to work fine, but 22.1 makes the CPU usage high when doing this animation.

Behaviour is the same whether there's 1 point or even 1000000 (tested).

(Note that, on JSFiddle, we can notice the change in CPU usage, but the usage is lower than when doing it on a static html and JS files.)

### Expected Behavior
CPU usage shouldn't be that high when animating a point.

### Actual Behavior
CPU usage is way too high (above 50%).

Thank you in advance !

**Comment by ryanhamley** [comment]
There's a [different way](https://docs.mapbox.com/mapbox-gl-js/example/add-image-animated/) to create an animated point now and this no longer appears to be an issue
