### ISSUE TITLE
consider replacing offset{Height/Width} with client{Height/Width} for map canvas sizing

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#6848]
We currently use the map `container`'s `offsetHeight` and `offsetWidth` to size the map canvas element, which leads to odd behavior when using a border, including `Map#getCenter`, `Map#getBounds`, etc. returning incorrect values for what is visible to the user because some of the map canvas will be hidden by the container.

https://github.com/mapbox/mapbox-gl-js/blob/bf88cd735b06eacc607c188a2508c9912140768d/src/ui/map.js#L1474-L1477

![image](https://user-images.githubusercontent.com/2425307/41749822-744f60b4-756d-11e8-88b4-78d52b2323d1.png)

![image](https://user-images.githubusercontent.com/2425307/41749950-348a8a02-756e-11e8-8975-8c0fb3ea6b1b.png)

If we used `clientHeight`/`clientWidth` to size the canvas, we would eliminate this behavior, but I'm not sure what the original reasoning was behind the choice to use `offset*`

This would qualify as a breaking change. If we decide not to make this change, we could specify in the documentation that a map's `container` cannot have a border. 

### Expected Behavior
with `client{Height/Width}` sizing, canvas remains within the main content area of the container element

![expected](https://user-images.githubusercontent.com/2425307/41750084-d5e15e62-756e-11e8-9a86-369944307fee.gif)

### Actual Behavior

with current behavior, canvas overflows the main content area and is partially hidden due to a border being used on the container element

![actual](https://user-images.githubusercontent.com/2425307/41750078-ceb3a0be-756e-11e8-837f-e1de7a4e4995.gif)

cc @mourner @jfirebaugh @kkaefer

**Comment by mourner** [comment]
I think it's save to switch to `clientWidth`/`Height`. `offsetWidth`/`Height` was there pretty much [since the first commit](https://github.com/mapbox/mapbox-gl-js/blame/ff5b9e188dd89e130b265e905f05d31d78d29de2/js/painter.js).  I would guess that the original reason for the choice is that those two get mixed up all the time. :)

**Comment by jfirebaugh** [comment]
Besides the canvas sizing code, is there any other code that would need to be adjusted, e.g. map center calculations, projection, event handling... ?

**Comment by ryanhamley** [comment]
Popups are using the container's offsetWidth and offsetHeight [here](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/popup.js#L292-L293)

**Comment by mollymerp** [comment]
@ryanhamley I think those lines are referring to the `Popup` element's container, but we probably want to make the change there as well because users may want to use borders on their popups as well.

@jfirebaugh as far as I can tell the projection/transform/mouse event code all relies on the canvas container size

**Comment by raysuelzer** [comment]
I spent a few hours trying to figure out why the canvas was not respecting the style properties of the container and setting the height="480" for no apparent reason. IT would be ideal to use client height.
