### ISSUE TITLE
Automatically generate feature `id` values for geojson & cluster sources

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapbox-gl-js#6849]
## Motivation

Examples using map.setFeatureState() like this https://www.mapbox.com/mapbox-gl-js/example/hover-styles/ require that a user include an integer parent `id` value in their geojson or vector tile source.

## Design Alternatives

* Create more documentation about parent `id` requirement to use featureStates

## Design

* Automatically generate parent a `id` value for a geojson source in geojson-vt, so that all geojson source features support featureStates.  
* Automatically generate a `parent` id for `clustered` geojson datasources

* Not sure if a similar approach is possible for vector tile sources.

### Mock-Up

Geojson-vt auto-generates feature `id` values for geojson and cluster sources.

### Concepts

* Vector tile `id` values
* The difference between how vector tile sources and geojson sources are created and how they support featureStates.

**Comment by andrewharvey** [comment]
:+1: There's a discussion around this over at #6019

**Comment by ryanbaumann** [comment]
Thanks, @andrewharvey!  Open to feedback about whether to close ticket then and re-open a docs-focused ticket that details how to create `id` values for features to use with feature states.

**Comment by asheemmamoowala** [comment]
Depends on [geojson-vt#109](https://github.com/mapbox/geojson-vt/pull/109) and [supercluster#94](https://github.com/mapbox/supercluster/pull/94).
