### ISSUE TITLE
Some LngLat values for fitBounds() fn don't work

### ISSUE THREAD

**Issue by aswinckr** [mapbox/mapbox-gl-js#6850]
I was testing out different `LngLat` values and turns out some of them don't respond to `fitBounds()`. 

I've recreated this issue here - https://codepen.io/aswinckr/pen/mKLvbb

You can replace the first `testingCoordinates` variable in JS to compare the working and not working values. 

Thanks in advance!

**Comment by jfirebaugh** [comment]
`fitBounds` requires [coordinates in `sw, ne` order](https://www.mapbox.com/mapbox-gl-js/api/#lnglatboundslike). The "not working" examples do not work because they are not in that order.

**Comment by aswinckr** [comment]
Hi @jfirebaugh Thanks for helping out. But what's the way to fit these points if they are not in `sw, ne` order but a straight line across the map? I tried converting this into bounds - `bounds = new mapboxgl.LngLatBounds(point, originPoint)` but it still doesn't move.

**Comment by jfirebaugh** [comment]
You can use `new mapboxgl.LngLatBounds(point).extend(originPoint)`.

**Comment by aswinckr** [comment]
Works, thank you!

**Comment by nikikokkinos** [comment]
In `bounds = new mapboxgl.LngLatBounds().extend(point).extend(originPoint)`, what exactly does `point` and `originPoint` represent? I'm having the same problem with my code where my data is in latlng and not lnglat. 

`  map.on('click', 'Hospitals', function (e) {

    var coordinates = e.features[0].geometry.coordinates;

    var bounds = coordinates.reduce(function(bounds, coord) {
      return bounds.extend(coord);
    }, new mapboxgl.LngLatBounds(coordinates[0], coordinates[0]));

    bounds = new mapboxgl.LngLatBounds().extend(bounds).extend(bounds)

    map.fitBounds(potentialhospitals, {
      padding: 20
    })
  })`

`Hospitals` is the `layerid` and `potentialhospitals` is the `sourceid`.
