### ISSUE TITLE
panBy "shakes" popups randomly

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6859]
**mapbox-gl-js version**: 0.46.0
**browser**: Chrome 67

### Steps to Trigger Behavior
 1. run panBy with a small value or even [0,0]
 
### Link to Demonstration
https://jsbin.com/vamubun/8

### Expected Behavior
Should not "shake" popup.

### Actual Behavior
Shakes popup, randomly. 
- Depends on the zoom level, window size. 
- Sometimes it shakes vertically, sometimes horizontally
- Usually after one shake there is no more, even with multiple panBy calls.
- But sometimes there is a shake after each panBy.

Recording (at 2x zoom):

![screenflow](https://user-images.githubusercontent.com/494223/41825446-806ddf3c-7820-11e8-80d3-0fab5f8642ed.gif)

**Comment by jfirebaugh** [comment]
This is a side effect of popup anchors being rounded to pixel coordinates to avoid blurriness, while the map center is not. I don't think we plan to change this, so you're probably best off avoiding making tiny pan operations.

**Comment by hyperknot** [comment]
This is happening with `panBy([0,0])` (like in the jsbin) so there is definitely something going on if even [0,0] introduces rounding errors.

**Comment by hyperknot** [comment]
Just for the reference, the actual function called with panBy([0,0]) is:
```
map.easeTo({
    center: map.getCenter(),
})
```

**Comment by hyperknot** [comment]
@jfirebaugh fixed in this: https://github.com/mapbox/mapbox-gl-js/pull/6860
