### ISSUE TITLE
There is a case when user can't drag map anymore in iOs

### ISSUE THREAD

**Issue by rantiev** [mapbox/mapbox-gl-js#6861]
Noticed the same behavior on both ipad and iphone (ios 11.*)
mapbox versions 0.45.0 & 0.46.0

http://output.jsbin.com/bitexef (0.46.0)
http://output.jsbin.com/lonemi/1 (0.45.0)

Steps to reproduce (better to reproduce it on iphone, more easily):
1) scroll the page to the very bottom
2) try to scroll/drag map with finger swipe

Sometimes problem appears after map rotation and additional page scrolling. Map is added into element which has fixed positioing

**Comment by rantiev** [comment]
Here is an example fix button which fixes the issue 
http://output.jsbin.com/macoruj

Noticed that if i pitch map a bit then pitch it again map dragging works again.

**Comment by ryanhamley** [comment]
I tried this in Chrome and Safari on ios 15.2.1 and I can no longer replicate this. The issue seems to be corrected.
