### ISSUE TITLE
Is there a way to move multiple point from one location to another

### ISSUE THREAD

**Issue by Mukeysh** [mapbox/mapbox-gl-js#6862]
I just want to know is there any way to move points from one location to another lets say 1000 points from one point to another. I just need this for dummy purpose.

Any suggestion would be appreciated.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
