### ISSUE TITLE
Customisable unclustered marker in cluster marker

### ISSUE THREAD

**Issue by Rajavelu** [mapbox/mapbox-gl-js#6863]
Hi, I want to use cluster markers with a customizable unclustered point.
Referred https://www.mapbox.com/mapbox-gl-js/example/cluster/ for the same.
In that example, we just added a circle for unclustered points. But I want to customizable markers like https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/ when showing unclustered points.
How to do the same?
Also how to set popup on cluster marker?

Thanks in advance,
Rajavelu M

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our documentation and examples -- I think https://www.mapbox.com/mapbox-gl-js/example/add-image/ will be the relevant example for you. This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by Rajavelu** [comment]
Hi @jfirebaugh Thanks for your reply.

But I think its a new feature request in the cluster.
https://www.mapbox.com/mapbox-gl-js/example/cluster/
From above example, we can simply draw circle only.
But i want to show a label(for example name, which will avail in my source geojson data) on that circle/below the circle. 

As i am new to mapbox-gl, Sorry. if I didn't understand correctly.
