### ISSUE TITLE
How can I change navigation control zoom icons color?

### ISSUE THREAD

**Issue by gabimoncha** [mapbox/mapbox-gl-js#6864]
**mapbox-gl-js version**: ^0.45.0

### Question
How can I change navigation control zoom icons color? Mapbox allows to change the navigation control background, but how can you change the color of the '+' and '-' icons?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. You'll need to override the `background-image` property of the `.mapboxgl-ctrl-icon.mapboxgl-ctrl-zoom-in`/`out` CSS or create your own control to accomplish this.

**Comment by gabimoncha** [comment]
👍 thanks!
