### ISSUE TITLE
Each 'zoomend', 'zoomstart', 'zoom' event should have it's own source (entity/scenario) which triggered it. Currently there are so many events that trigger these events even when the user does not really perform any action.

### ISSUE THREAD

**Issue by meghamukim** [mapbox/mapbox-gl-js#6866]
The only event captured in 0.45 version is the WheelEvent i.e. when the map is zoomed in/out using the scroll wheel of the mouse. There is no way the user can know if the map was zoomed in through the navigation controls on the map or through the camera, render functions.

**Comment by jfirebaugh** [comment]
When you trigger a camera mutation programmatically via a method like [`map.setZoom()`](https://www.mapbox.com/mapbox-gl-js/api#map#setzoom), you can provide an "event data" argument whose properties will be transferred to the event object. You can use this to distinguish the event from user-triggered camera movement.

**Comment by meghamukim** [comment]
That is not what I am requesting for. I am requesting for some way to tell if the map was zoomed in/out by a REAL zoom operation that may be via - Mouse scroll wheel or using the navigation controls UI on the Map itself as compared to when the 'zoomend' event is triggered through a chain of events when: 
- Map is rendered 
- Map is panned to a different location
- Map is re-rendered.
