### ISSUE TITLE
Rendering Carto Layers

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#6870]
I wonder whats the best way to render Carto layers (that use Carto CSS for styling) in Mapbox GL? 

Getting the GeoJSON from Carto SQL API is easy but its the conversion of CartoCSS to the paint object is the messy part which I want to avoid. 

I understand Carto provides vector tiles but since I'm new to both Mapbox and Carto I'm unsure how to consume those vector tiles in Carto if all I have is a URL to viz.json?

Thanks.

**Comment by jfirebaugh** [comment]
Mapbox GL does not support CartoCSS, and as you note, there's no simple conversion between CartoCSS to the Mapbox Style Specification. You'll need to switch to the Mapbox Style Specification, or use a renderer other than Mapbox GL to render your CartoCSS.

**Comment by 3zzy** [comment]
Thanks. So even using the vector tiles (MVT) it would just render the layers from Carto without styling? How does that work? Is there an example I could follow?
