### ISSUE TITLE
VueJS map not loading correctly

### ISSUE THREAD

**Issue by danielnitscheladoo** [mapbox/mapbox-gl-js#6872]
Documenting an issue I came across today: if you're attempting to use store your mapbox-gl-js map as state in VueJS, you might find your map or map styles broken (I can only describe this as missing some map details like labels, or perhaps showing detail at the wrong level).

This occurs when VueJS attempts to make your mapbox object observable. The solution is either a) don't store your mapbox object in VueJSs state, or b) as @magicdawn [mentions here](https://github.com/vuejs/vue/issues/2637#issuecomment-393102761), set `map._isVue = true` before assigning the mapbox object to your VueJS state.

**Comment by samuelantonioli** [comment]
I've build a Vue plugin that makes it possible to make Vue variables non-reactive (it uses the beforeCreated hook). The solution in [#2637](https://github.com/vuejs/vue/issues/2637) is not very clean and future-proof.

Please look at [Vue-Static](https://github.com/samuelantonioli/vue-static).

```html
<script>
export default {
    static() {
        return {
            map: null,
        };
    },
    mounted() {
        this.map = new mapboxgl.Map({...});
    },
};
</script>
```
