### ISSUE TITLE
text font size auto scale for different resolution

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#6873]
Font size is defined in the style, while the same size may result in different visual effect in different screen resolution.

For example, font size of `12` maybe fine for 1280x1024, while it looks smaller in 1920x1280.

So can we scale the font size automatically to fit the screen resolution?

**Comment by jfirebaugh** [comment]
I don't think this should be something that's built into Mapbox GL. The relationship between screen resolution and text size (a.k.a. the device pixel ratio) is something that's typically configured at the OS level, and then 12 point font is the same size no matter the context.

If you really want to deviate from this norm, you can change the text size using runtime styling. Or, you might want something like #1953 instead.
