### ISSUE TITLE
feature-state expression is always evaluated to null in filter

### ISSUE THREAD

**Issue by stepankuzmin** [mapbox/mapbox-gl-js#6876]
Consider this example (https://jsbin.com/rogidup/9/edit?js,output):

```js
map.addLayer({
  id: 'points',
  type: 'circle',
  source: 'points',
  paint: {
    'circle-color': '#fff'
  },
  filter: ["feature-state", "display"]
});

map.setFeatureState({ id: 1, source: 'points' }, { display: true });
```

It seems, that `featureState` is `undefined` when evaluating `feature-state` expression context in `filter`. So `feature-state` expression is always evaluated to `null` in `filter`.

https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/expression/definitions/index.js#L175

**mapbox-gl-js version**: v0.46.0

**browser**: Google Chrome 67.0.3396.87

### Steps to Trigger Behavior

 1. Set feature state
 2. Filter features according to this state

### Link to Demonstration

https://jsbin.com/rogidup/9/edit?js,output

### Expected Behavior

Features can be filtered according to their state

### Actual Behavior

Features can't be filtered according to their state

**Comment by asheemmamoowala** [comment]
@stepankuzmin Thank you for using Mapbox. The `feature-state` expression was added specifically to enable interactivity with data-driven styling. Can you speak to more of the use case you are expecting to use the `feature-state` expression in a layer filter?

**Comment by stepankuzmin** [comment]
Thanks for the reply, @asheemmamoowala!

The ability to filter features based on their state seems consistent to me.

Imagine the following use case. I've got a set of features on the map and I want to add values to them from some external API. But this API may not have some values for specific features and it seems logical to filter them out.

**Comment by asheemmamoowala** [comment]
@stepankuzmin `feature-state` expressions should be supported only in the data-driven styling enabled paint properties. Adding support for them in filter expressions, while possible, is outside of their intended use case. Maybe you could use the layer's `-opacity` property with a `feature-state` expression to get the desired filtering effect?

**Comment by strech345** [comment]
@asheemmamoowala 
setting `opacity` per feature is not possible for `fill-extrusion`. So in this case only filter is possible to hide elements. 
And i don't understand why the join example now change to feature state if this should only be used for interaction.  https://www.mapbox.com/mapbox-gl-js/example/data-join/
If it is now the prefered way to use it also for joining data, filter should be also worked - from my side.

The other problem on feature-state is that the ids are never deleted. If i use it for joining data there maight be millions of entries, and i don't have the possiblity to delete some of them.
https://github.com/mapbox/mapbox-gl-js/issues/6889

i really need a performant and menory less way to add aditional feature data per tile by using feature.id or some property value to style and filter features.

**Comment by davidswinegar** [comment]
@asheemmamoowala I'm running into a use-case in my application in which this would be useful. I have two layers referencing the same source: Layer 1, which renders all data as lines with a certain style, and Layer 2, which renders part of the data as lines with an different style. Certain features would be moved in or out of Layer 2 based on application state, and I'd like to use `feature-state` so that I don't have to update the source data (which is relatively expensive). 

There are other solutions (like using multiple sources and duplicating my data), but this would be far more performant and seems like an intuitive use-case. Performance is already an issue in our application and any part we can get back would be helpful.

cc @cmdoptesc @dyakovlev

**Comment by asheemmamoowala** [comment]
@davidswinegar The intent of adding `feature-state` was so that separate layers would not be needed. What is the difference in the style properties between Layer 1 and Layer2? Paint properties alone can be factored into a single layer.

**Comment by dyakovlev** [comment]
@asheemmamoowala there are significant interactive behaviors attached to the layer that rendered the filtered subset of features. The non-filtered layer is mostly static except for some click handlers (that move features into the interactive layer).

**Comment by DanPen** [comment]
What about when you need to filter clustered data?

**Comment by mryellow** [comment]
> The feature-state expression was added specifically to enable interactivity with data-driven styling. Can you speak to more of the use case you are expecting to use the feature-state expression in a layer filter?

Visibility is data driven styling.
