### ISSUE TITLE
How to use, user movement turn by turn navigation with mapboxgl, mapbox gl direction in meteor hybrid app development

### ISSUE THREAD

**Issue by deligent** [mapbox/mapbox-gl-js#6877]
**mapbox-gl-js version**:

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
