### ISSUE TITLE
Low performance, cordova iOS 9.3.5

### ISSUE THREAD

**Issue by TristanPct** [mapbox/mapbox-gl-js#6879]
**mapbox-gl-js version**: 0.46.0

**browser**: cordova (iOS 9.3.5)

### Steps to Trigger Behavior

 1. Add mapbox-gl-js to a cordova app
 2. Run the app on iOS (tested on iPad Mini with iOS 9.3.5)

### Source code

<details>
<summary>index.html</summary>

```html
<!DOCTYPE html>
<html>
<head>
    <meta name="format-detection" content="telephone=no">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
    
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.46.0/mapbox-gl.css' rel='stylesheet' />

    <link rel="stylesheet" type="text/css" href="css/index.css">

    <title>Test - Cordova Mapbox GL JS</title>
</head>
<body>
    <div class="app">
        <div id="map"></div>
    </div>
    <script type="text/javascript" src="cordova.js"></script>
    <script type="text/javascript" src="js/index.js"></script>
</body>
</html>
```
</details>

<details>
<summary>index.js</summary>

```js
var app = {
    initialize: function() {
        document.addEventListener("deviceready", this.onDeviceReady.bind(this), false);
    },

    onDeviceReady: function() {
        mapboxgl.accessToken = "YOUR TOKEN HERE";
  
        var map = new mapboxgl.Map({
            container: "map",
            style: "mapbox://styles/mapbox/streets-v9",
            center: [6.1198157, 45.9017086],
            zoom: 15
        });
    },
};

app.initialize();
```
</details>

<details>
<summary>index.css</summary>

```css
body {
    margin: 0;
    padding: 0;
}

#map {
    width: 100vw;
    height: 100vh;
}
```
</details>

### Expected Behavior

No lag ?

### Actual Behavior

Heavy lag on the iPad mini (not smooth when panning or zooming, take long time to load tiles...).
Very small freezes with the same app on an iPhone 6 (iOS 11).
No problem with the app on One Plus One (Android 7.1.2).

What is strange is that the demo on https://www.mapbox.com/mapbox-gl-js/example/simple-map/ running on the iPad with Safari has no lag.

## Update

Using https://github.com/apache/cordova-plugin-wkwebview-engine seems to reduce lag on the iPad, but it still have a lower performance than the Safari version.

**Comment by jfirebaugh** [comment]
Hi @TristanPct, thanks for using Mapbox. Unfortunately, our team doesn't have the resources to offer formal support for third-party frameworks such as Cordova. If you find a way to replicate the performance issue in a regular browser environment let us know. Otherwise, we strongly recommend using the Mapbox Maps SDK for iOS for native development.
