### ISSUE TITLE
Mapbox hidden map taking huge memory for large size map in IE11 and Microsoft edge

### ISSUE THREAD

**Issue by Lavanya007** [mapbox/mapbox-gl-js#6883]
**mapbox-gl-js version**: v0.46.0

    While taking screen shot of large size map using hidden map getting error 'Not enough memory resources are available to complete this operation' in IE11 and Edge browsers but working fine in chrome and firefox browsers. Can any body tell me how to reduce hidden map memory for large size maps like 55.88cm x 86.36cm and 60.96cm  x 91.44cm etc page sizes.

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. I think with that large of a size, you're going to need to split the render into multiple pieces and then rejoin them afterward. For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
