### ISSUE TITLE
setFeatureState and the need for removeFeatureState

### ISSUE THREAD

**Issue by cammanderson** [mapbox/mapbox-gl-js#6889]
Hi Guys, 

Working with the new setFeatureState, and I noticed that there isn't a way to remove the state supplied. You must always provide a value to merge it, and can't reset to the original values. 

Use cases are varied, and not sure of the overall impact, but I am updating a react project to offer the function, but I can't 'reset' the state back to 'pre' application of the setFeatureState. Ideally, I would be able to remove the feature state completely, and then assumingly it would source from the original value of the underlying source data. If not, you'd have to track the original property value of the object to work around it. Not sure if we need to add a removeFeatureState() ?

Cheers
Cam

**mapbox-gl-js version**:
0.46.0

**browser**:
N/A

### Steps to Trigger Behavior

 1. setFeatureState({ source: 'composite', layer: 'water', id: 0 }, { value: true })
 2. setFeatureState({ source: 'composite', layer: 'water', id: 0 }, null)

### Expected Behavior
Remove feature state entirely

### Actual Behavior
Because underlying it is using an extend, the null || {} values have no effect.

featureState: { value: true }

**Comment by asheemmamoowala** [comment]
@cammanderson this should be possible by getting the current state with `Map#getFeatureState()` and setting all values to `null` or `undefined` before calling `Map#setFeatureState()`.

**Comment by peterqliu** [comment]
@cammanderson @asheemmamoowala from a design perspective, should the `removeFeatureState` reset the entire state object, or allow users to reset specific keys within the object?

**Comment by peterqliu** [comment]
Making some progress for a key-level `removeFeatureKey` over at https://github.com/mapbox/mapbox-gl-js/commit/37409713d205d6be97712ca4d3a0f0f4a863423b

**Comment by asheemmamoowala** [comment]
Closed by #7761
