### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by wboykinm** [mapbox/mapbox-gl-js#689]
I believe this originates from [my adaptation of a style `.json`](http://bl.ocks.org/wboykinm/8a7501d07ab29737940e), but the message isn't flagged to a line that I can debug. Did the constants change in the past few days?

**Comment by sohamkumar-chauhan** [comment]
> Can you use `mapbog-gl-dev.js` instead? It has source maps baked in so much easier to debug.

How to import with npm since there is no npm version present?
