### ISSUE TITLE
fill-extrusion-height-transition jumps to final height value

### ISSUE THREAD

**Issue by bradbarnett** [mapbox/mapbox-gl-js#6891]
I'm using v0.46.0 and `fill-extrusion-height-transition` doesn't seem to be transitioning when I use `map.setPaintProperty('3d-buildings', 'fill-extrusion-height', 75);` . Instead it simply jumps to the new height value. When I switch to `fill-extrusion-opacity-transition` it seems to be working, which makes me think it's specific to the extrusion height. Anyone else able to reproduce? 

See fiddle: https://jsfiddle.net/xpvt214o/331073/

**Comment by lbud** [comment]
@bradbarnett transitions don't work to or from data-driven property values — further discussion/feature request at https://github.com/mapbox/mapbox-gl-js/issues/3170.
