### ISSUE TITLE
Scaling an SVG becomes blurry in Safari when used on page with Mapbox

### ISSUE THREAD

**Issue by w1llywonka** [mapbox/mapbox-gl-js#6893]
**mapbox-gl-js version**: 0.46.0

**browser**: Safari 11.1.1

### Steps to Trigger Behavior

 1. Have an SVG on the page with a Mapbox Map. (see fiddle).
 2. Use the + button in top right to scale the SVG (up to around 8 or so to see in fiddle).

### Link to Demonstration
https://jsfiddle.net/willywonka/xpvt214o/332407/

### Expected Behavior
SVG does not become blurry when scaled.

### Actual Behavior
SVG does become blurry when scaled. You can fix it by clicking the checkbox in the top left (which sets the Mapbox div to display: none.

**Comment by jfirebaugh** [comment]
Hi @w1llywonka, thanks for the report. This looks like a browser bug -- Mapbox GL does not have control over the rendering of SVGs. You may want to open an issue on https://bugs.webkit.org/ or https://bugreport.apple.com/.
