### ISSUE TITLE
Programmatic drag map

### ISSUE THREAD

**Issue by ansarikhurshid786** [mapbox/mapbox-gl-js#6898]
Hi, 
I am using mapbox gl with ionic 3. 

is there any way to programmatic drag the map?

**Comment by jfirebaugh** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
