### ISSUE TITLE
What should the expectations be for getting OSM updates?

### ISSUE THREAD

**Issue by mike-marcacci** [mapbox/mapbox-gl-js#6899]
**mapbox-gl-js version**: any

### Question

First off, I know this isn't really the ideal place to post this question, but since the "contact support" links also resolve to specific products, I figured I'd at least ask this in a public forum to help others answer similar questions in the future. Feel free to direct me elsewhere if you find it appropriate.

I've been working on a collaborative project for rock climbers called [boltline](https://www.boltline.org/) and we're just starting to on-board guidebook authors / potential heavy contributors. We keep a database of climbs and climbing areas, but our guidance has been to ask contributors to edit roads and trails on OSM, since it's a fantastic resource and we see no reason to duplicate their efforts.

However, edits made to OSM do not seem to be taken up by Mapbox, even after more than a week. I am aware that Mapbox employs an additional vetting process for updates, so I am hoping for a little more clarity in how this works, and what expectations our users can have.

Here are a few areas with missing trail data, and the corresponding edits made in OSM:

#### The Fins
- https://www.boltline.org/area/0535cc45-dcc8-4f8a-995c-c8fe0f7ccf8c
- https://www.openstreetmap.org/changeset/60090032#map=17/43.73036/-113.08149

#### Wild Iris
- https://www.boltline.org/area/708e4919-2318-4cd9-a20f-2e2635035cfa
- https://www.openstreetmap.org/changeset/60156529#map=14/42.5896/-108.7505

#### Lime Kiln Canyon
- https://www.boltline.org/area/66a4bf8e-9f18-447d-be4d-c10a288c7042
- https://www.openstreetmap.org/changeset/60157060#map=14/36.6541/-114.0036

Thanks in advance for the help, and also for all your awesome tools!

### Links to related documentation

- https://www.mapbox.com/help/how-mapbox-data-works/

**Comment by ashleyclough** [comment]
This may be to do with the way you've categorised your paths in OSM - I notice that the ones that show up in Mapbox's terrain maps as 'paths' have tags of 'highway' and 'track', the ones you've added are tagged as 'highway' and 'footway'. Try editing the tags for the ones you've added to OSM to see if they then show up.

**Comment by jfirebaugh** [comment]
Hey @mike-marcacci -- contacting support (you can use [this path](https://www.mapbox.com/contact/support/#products/map)) is the way to go here. They can look into this in more detail.

**Comment by mike-marcacci** [comment]
@ashleyclough - wow, thanks for that insight! I will look into this.
@jfirebaugh - sounds great, thanks for the link!
