### ISSUE TITLE
How to use “case” expresion on nested properties?

### ISSUE THREAD

**Issue by goors** [mapbox/mapbox-gl-js#6901]
How to use nested value in order to use case == operator? Something like:

    this.map.setPaintProperty("somelayer", "fill-color",
            ["case",
              ["==", ["properties:some_prop"], someval],
              "#34c0dd",
              "#499bbc"]

where properties is dict:

    properties = {
    some_prop: 1,
    some_prop2: 2,
    // and so on
    }

I have tried `["properties.some_prop"`] and `["properties"]["some_prop"]` and that does not work as well.

And how to print that mapbox query like console.log or something?

**Comment by jfirebaugh** [comment]
Hi @goors, please see our [help document](https://www.mapbox.com/help/mapbox-gl-js-expressions/)) on expressions.
