### ISSUE TITLE
New plugin: mapbox-choropleth

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#6902]
Just a suggestion for the plugins page: https://www.npmjs.com/package/mapbox-choropleth

I guess it's probably a "utility library" in that categorisation scheme.

**Comment by jfirebaugh** [comment]
Cool, want to submit a PR?

**Comment by stevage** [comment]
Oh, I didn't realise that code was maintained in the public repo. I [see it now](https://github.com/mapbox/mapbox-gl-js/blob/master/docs/pages/plugins.js#L84).
