### ISSUE TITLE
fitBounds with -90 results in uncaught error

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#6906]
This must have been introduced in a recent version but calling fitBounds with a bounding box containing `-90` results in an uncaught error.

<img width="1440" alt="screen shot 2018-07-03 at 9 37 20 am" src="https://user-images.githubusercontent.com/61150/42223032-c8f8f78e-7ea4-11e8-921c-ebf3a4bbcaee.png">

**mapbox-gl-js version**:
`v0.46.0`

**browser**:
Chrome `Version 67.0.3396.99 (Official Build) (64-bit)`

### Steps to Trigger Behavior

Call `fitBounds` with a sw latitude coordinate of `-90`

### Link to Demonstration
https://jsfiddle.net/tristen/bytzwu08/ Click "Fit bounds" and view the console

**Comment by ryanhamley** [comment]
Hi @tristen, thanks for the great report! This isn't a bug _per se_, but rather an inherent limitation of the Mercator map projection. Mercator maps project the poles at infinity making it impossible to fully render them (both on the web and on paper). Specifically, the Web Mercator projection that Mapbox uses is unable to accurately project latitudes north of 85.05° and south of -85.05°.

I think your report points to a couple of improvements that we can implement however. One is to clamp latitude inputs to the supported range and another is to log a warning to the console alerting the user that this is being done. I'm going to leave this open for now so we can use the ticket to track those improvements.

**Comment by tristen** [comment]
> One is to clamp latitude inputs to the supported range and another is to log a warning to the console alerting the user that this is being done.

+1 to both of these improvements
