### ISSUE TITLE
[urgent][mapbox.cn] Breaking change

### ISSUE THREAD

**Issue by tomacadi** [mapbox/mapbox-gl-js#6907]
Hello,

Until recently I had a fully functional map with the following request:
https://api.mapbox.cn/styles/v1/mapbox/streets-v10?optimize=true&access_token=[my_valid_api_key]

If I switch to api.mapbox.com, it works properly. 
I have just noticed that it is giving a 502 error now:

> 502 ERROR
> The request could not be satisfied.
> CloudFront wasn't able to connect to the origin. 
> For more information on how to troubleshoot this error, please refer to the CloudFront documentation (https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/http-502-bad-gateway.html). 
> Generated by cloudfront (CloudFront)

What has changed?

**Comment by jfirebaugh** [comment]
Hi @tomacadi -- for API outages, please contact help@mapbox.com or your emergency email address if you are a Mapbox Enterprise customer.
