### ISSUE TITLE
Function to check (or gracefully fail) if bounds is invalid for fitBounds()

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6911]
1. I'm using '@turf/bbox' to generate the bounding box for all visible features.
2. This bounding box can sometimes include "Infinity" values, which breaks `fitBounds`.
3. Thus I'm manually checking with `bounds.includes(Infinity)` before every time I'm calling `fitBounds`.
4. This works well, but it turns out there are some cases when the bounds are not "Infinity", but just some huge number, which also fails fitBounds.

One such example is:
```
[5.8488465, 36.5302427, 697804, 5010733]
```

Since a fit to all visible features is such a basic use case for all mapping libraries, I recommend to either:

1. Gracefully fail in fitBounds, without an exception, with a console warning maybe.
or
2. Make a function which checks if a LngLatBoundsLike object is valid for fitBounds. I don't know how should wrapping be handled, what exact input is allowed for fitBounds, etc. but there should be a function which can check all the specs.

**Comment by ryanhamley** [comment]
Thanks for this @hyperknot! This is very similar to #6906. I'll add some tests to ensure values like this get handled properly, but I'm going to close this ticket since the solution is already being tracked in the other issue.

**Comment by hyperknot** [comment]
Thanks!

**Comment by hyperknot** [comment]
What is the state of fitBounds today?

I think this is what is happening today:
- lat values 85..90 are silently clamped
- lat values 90+ are raising `Invalid LngLat latitude value: must be between -90 and 90`
- lon values are simply passed as they are? Are there no checks on them? Is there a guideline or an internal function present somewhere about how to write a check for lon values? Or should I take it simple and clamp it to -360..360?

In 0.53.1 the following is happening:
`fitBounds([-36000, -10, 0, 10])` -> makes a rollercoaster animation
`fitBounds([-360000, -10, 0, 10])` -> makes a crazy rollercoaster animation
`fitBounds([-10e308, -10, 0, 10])` -> raises Invalid LngLat object: (NaN, NaN) exception

I have no idea how can turf.bbox come up with e308 values, but somehow it happens and I'd like to guard fitBounds against going bad. Also I'd like to make sure the 90+ values do not raise an exception, but get clamped like 85..90 values. Any recommendation?
