### ISSUE TITLE
Load image from json

### ISSUE THREAD

**Issue by xeroxstar** [mapbox/mapbox-gl-js#6912]
Hello, i am kind new to the mapbox and i have a question, can i load image base on the json file for example, can i add somewhere in the json an image url? 

```
data: {
                "type": "FeatureCollection",
                "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                "features":[
                    {   "type"        : "Feature",
                        "properties"  : {
                            "id"      : "ak16994521",
                            "mag"     : 2.3,
                            "time"    : 1507425650893,

                            image:'HTTP://MY-SITE.COM/IMAGE.PNG',

                            "felt"    : null,
                            "tsunami" : 0
                        },
                        "geometry" : {
                            "type" : "Point",
                            "coordinates": [ -73.5878, 45.5288, 0.0 ]
                        }
                    }
                ]
 }
```

I don't need an icon but i want to load an image because for the app i build, for every point i create it should display a logo for a company and not a static icon.
Thanks

**Comment by xeroxstar** [comment]
Nevermind, i did found a solution how to do it...

**Comment by jfirebaugh** [comment]
Hi @xeroxstar — thanks for using Mapbox. Glad to hear you found what you needed!

**Comment by styledev** [comment]
@xeroxstar Can you share your solution here? I can't find any documented way to pull an image from the geojson properties field and display it on the AddLayer marker.
