### ISSUE TITLE
The 'composite' source layer no longer includes the custom layers added through mapbox studio

### ISSUE THREAD

**Issue by johnnyluu** [mapbox/mapbox-gl-js#6916]
**mapbox-gl-js version**:
0.46.0
**browser**:
chrome
### Steps to Trigger Behavior

 1. run `map.querySourceFeatures('composite', {sourceLayer: 'custom-source-id'})` on map load
 2. run `map.getSource('composite').vectorLayerIds`

### Expected Behavior
`map.querySourceFeatures('composite', {sourceLayer: 'custom-source-id'})` returns the features in the custom data source
`map.getSource('composite').vectorLayerIds` includes all the custom layers added to the style through Mapbox Studio

### Actual Behavior
`map.querySourceFeatures('composite', {sourceLayer: 'custom-source-id'})` returns empty array
`map.getSource('composite').vectorLayerIds` doesn't include the ids of the custom sources added through Mapbox Studio

This is how I used to get the list of features from a Mapbox style, but apparently it doesn't work anymore. Not sure if this is a bug, or the layers have been intentionally removed from 'composite'. If they have been removed, how do I query custom sources now?

Thank you!

**Comment by jfirebaugh** [comment]
Thanks for using Mapbox, and sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue?

**Comment by johnnyluu** [comment]
Here it is: http://jsbin.com/qaraqowewi/edit?html,output

As you can see in getStyle(), there are multiple custom sources added, but they're not in the list of vectorlayerIds, and querySouceFeatures returns an emtpy array. 

Let me know when you're done, I'll delete the access token.

**Comment by jfirebaugh** [comment]
Thanks, but is that a complete example? I don't see `getStyle` used, and it produces "ReferenceError: minBounds is not defined" when run.

**Comment by johnnyluu** [comment]
Sorry it didn't save. Try this: http://jsbin.com/jugiquzipo/1/edit?html,output

**Comment by pathmapper** [comment]
@johnnyluu I don't know if your custom `sourceLayer: 'qmuseum'` should be part of `'composite'`.
Did you check [if source compositing is on](https://www.mapbox.com/help/reduce-tileset-sources/#make-sure-source-compositing-is-on) in Studio?

Currently there are two other vector sources used in your style in addition to `'composite'`:

![auswahl_339](https://user-images.githubusercontent.com/20856381/42379650-afa33874-812b-11e8-85cf-ef74c64432af.png)


The  `sourceLayer: 'qmuseum'` is part of the source `mapbox://romeodigital.cjj3km0x101boaspjvjbtzh87-2iicz`, so you would need to query this source:

http://jsbin.com/qawulatelo/edit?html,output

**Comment by jfirebaugh** [comment]
Thanks @johnnyluu! Hopefully @pathmapper's comment's led you to a solution. If not, please reach out to [Mapbox support](https://www.mapbox.com/contact/), who can look into what's going on. It doesn't look to me like this is an issue with Mapbox GL, but rather how the style and sources are structured.

**Comment by johnnyluu** [comment]
@pathmapper Yes, you're right. The source compositing options was off in Mapbox. It's all working as expected now. Thanks.
