### ISSUE TITLE
Click event for added <div> markers randomly stop working

### ISSUE THREAD

**Issue by GitFlip** [mapbox/mapbox-gl-js#6928]
**mapbox-gl-js version**: 0.45.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. I open my demo app and click on the map icons that are created dynamically from the geojson
 2. Pop-ups appear
 3. My colleague opens up the demo app and the pop-ups do not work for him
 4. I close my demo app and the pop-ups now work for him
 5. If I reopen the demo app while they work for him they do not work for me

I should maybe note, we are using the same public access token.

### Link to Demonstration

Please note in my JSBin below that the access token has been removed. Please add your access token.

https://jsbin.com/ciqebukifa/edit?html,js,output

### Expected Behavior
My colleague and I should both be able to have the demo app open from two different computers and we should be able to both invoke the pop-ups when we click on the icons.

### Actual Behavior
When we each have the demo app open only one of us gets the pop-ups. The other just has the icons twitch a bit when you click.

**Comment by jfirebaugh** [comment]
Can you please try upgrading to 0.46? I suspect this was fixed by #6757.

**Comment by GitFlip** [comment]
@jfirebaugh So far the issue is fixed by upgrading to 0.46. Do you mind if we keep the issue open for a few more days while my colleague and I do some local testing?

**Comment by jfirebaugh** [comment]
Closing since it's been a week+ now. Please let us know if it's still an issue!
