### ISSUE TITLE
I am shifting from the mapbox js to mapbox gl js. I need to how to convert the leaflet function for the mapbox gl js.

### ISSUE THREAD

**Issue by vikyrock** [mapbox/mapbox-gl-js#6930]
`I` am shifting from the mapbox js to mapbox gl js. I need to how to convert the leaflet function for the mapbox gl js.

in mapbox.js I was using:

` imageUrl = 'http://localhost:1337/tiles/{z}/{x}/{myY}.png`

`var map = L.mapbox.map('map', 'mapbox.streets', {
        infoControl: false,
        attributionControl: false,
        maxZoom: 21,
        minZoom: 16
    })     
`
 `   var TopoLayer = L.tileLayer(imageUrl, {
        maxZoom: 21,
        minZoom: 16,
        myY: function (data) {
            return (Math.pow(2, data.z) - data.y - 1)
      }
    })`
I am using the 3rd party tiles to overlay on the maps. which was working fine in the leaflet mapbox js. How can I change this into mapbox gl js?

**Comment by andrewharvey** [comment]
Your stackoverflow question at https://stackoverflow.com/questions/51224669/how-to-convert-the-mapbox-js-function-into-mapbox-gl-js was the right place to ask "how do I" questions
