### ISSUE TITLE
Fullscreen issues in Safari

### ISSUE THREAD

**Issue by nik736** [mapbox/mapbox-gl-js#6932]
**mapbox-gl-js version**: 0.46.0

**browser**: Safari 11

### Steps to Trigger Behavior

 1. Take the fullscreen example: https://www.mapbox.com/mapbox-gl-js/example/fullscreen/
 2. Wrap it in a div that sets a width/height, for example: width:500px;height:300px;margin:auto;position:relative
 3. Click on the fullscreen icon, in Chrome and Firefox everything works as expected but in Safari the area has the same size in fullscreen mode (500x300) as in the regular browser view without clicking on the fullscreen icon

### Link to Demonstration

https://output.jsbin.com/nosekuvata

### Expected Behavior

Map should be displayed in fullscreen mode

### Actual Behavior

Map is limited to the wrapped div width and height.

**Comment by jfirebaugh** [comment]
Mapbox GL JS doesn't reach outside the map container to change other CSS when the fullscreen button is clicked. You'll need to adjust the CSS so that this works as expected. See #6777 for similar discussion.
