### ISSUE TITLE
Document that you can't add "attribution" property to a TileJSON-loaded vector source

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#6934]
**mapbox-gl-js version**: v0.46.0

**browser**: Chrome on Linux

### Link to Demonstration

https://jsbin.com/kivaqajija/edit?html,output

### Expected Behavior

According to the style spec it should be possible to add an `attribution` property:

https://www.mapbox.com/mapbox-gl-js/style-spec#sources-vector-attribution

### Actual Behavior

Error: `a source with a "url" property may not include a "attribution" property`

**Comment by pathmapper** [comment]
The same for `raster` sources:
https://jsbin.com/caqenoxojo/edit?html,output

For `raster-dem` sources no error, but the attribution is not displayed:
https://jsbin.com/qiqoduheve/edit?html,output

**Comment by pathmapper** [comment]
Just found https://github.com/mapbox/mapbox-gl-js/issues/5936#issuecomment-355094236, so the error for `vector` and `raster` sources is expected behaviour.

I guess for `raster-dem` sources it's just missing.

It would be useful if the docs would mention that it is not possible to use some properties if providing a TileJSON resource with the `url` property.

**Comment by asheemmamoowala** [comment]
Closed by #8232
