### ISSUE TITLE
Positron style: Some letters with diacritics in the Metropolis font are missing

### ISSUE THREAD

**Issue by interDist** [mapbox/mapbox-gl-js#6940]
The Positron style uses typically a combination of the Metropolis and the Noto Sans / Klokantech Noto Sans fonts. However, various letters with diacritics are missing from the Metropolis font, and thus are taken from the Noto Sans font, which has a different baseline. This results in these letters being misaligned in the rendition of the names.

**mapbox-gl-js version**: v0.45.0

**browser**: any

### Demonstration

![image](https://user-images.githubusercontent.com/1909012/42511237-91fe0406-8451-11e8-834d-3805f1b01bac.png)

![image](https://user-images.githubusercontent.com/1909012/42511376-fed281c4-8451-11e8-8d54-94d892309763.png)

**Comment by jfirebaugh** [comment]
Hi @interDist. This is an issue with the style rather than the renderer, and it isn't a Mapbox style, so you'll need to contact the creator (looks like https://github.com/openmaptiles/positron-gl-style).

**Comment by ChrisLoer** [comment]
Mixing fonts in a single word is always going to be problematic, but we do have a separate issue tracking the request to support fonts with different baselines:

https://github.com/mapbox/mapbox-gl-js/issues/191
