### ISSUE TITLE
Changing the mapbox style while a Layer is present causes "Error: Style is not done loading"

### ISSUE THREAD

**Issue by SvitlanaKozeletska** [mapbox/mapbox-gl-js#6947]
The style changes are work fine if there aren't any other layers on top of it, but I faced the issue  "Error: Style is not done loading" when I try to change the style with the already applied layers. 

Would appreciate any help and suggestions

**Comment by jfirebaugh** [comment]
Hi @SvitlanaKozeletska, thanks for using Mapbox. The "Style is not done loading" error indicates that you're attempting to make modifications to a style that's still in the process of loading, before the [map `load` event has fired](https://www.mapbox.com/mapbox-gl-js/api/#map.event:load). Modifications made during this window would be overwritten once the style completes loading, so they are disallowed. You should wait to make modifications until after this event fires.

**Comment by elanioazul** [comment]
Hi, Im working with angular and have the code attached. It is giving me same error that @SvitlanaKozeletska was having, with only one Source and one Layer added . Cannot figure it out the answer you gave to @SvitlanaKozeletska. Any help? Thx in advance

[map.service.txt](https://github.com/mapbox/mapbox-gl-js/files/4402429/map.service.txt)
[map.component.txt](https://github.com/mapbox/mapbox-gl-js/files/4402430/map.component.txt)
