### ISSUE TITLE
Multiple requests for a custom studio style

### ISSUE THREAD

**Issue by burakozdemir32** [mapbox/mapbox-gl-js#6955]
**v0.46.0**:

### Multiple requests for a custom studio style
Hello,

I created a custom map style based on mapbox-streets by using Mapbox studio. Everything works fine, but the number of map requests.

When a map is loaded on a page, there are two different requests. The first one is for the custom style and the other one is for mapbox-streets-v7. Therefore, on my map usage statistics, a map load is considered as double map loads. Is there any solution for this case?

### Code
```
    var mapbox = new mapboxgl.Map({
        container: $jqel[0],
        style: 'style_id',
        zoom: zoom,
        infoControl: false,
        attributionControl: false,
        scrollZoom: false,
        touchZoom: false,
        dragRotate: false
    });

    // Add zoom and rotation controls to the map.
    mapbox.addControl(new mapboxgl.NavigationControl({showCompass: false}));

    mapbox.setCenter([lng, lat]);
    // create the marker
    new mapboxgl.Marker({"color": "#ffffff"})
    .setLngLat([lng, lat])
    .addTo(mapbox);
```

**Comment by jfirebaugh** [comment]
Hi @burakozdemir32, thanks for using Mapbox.

> The first one is for the custom style and the other one is for mapbox-streets-v7. 

If you're talking about the tile requests, you can turn on "Source compositing" in Studio:

![image](https://user-images.githubusercontent.com/98601/42659628-b5b3b124-85dd-11e8-8644-29f1f9592bc6.png)

**Comment by burakozdemir32** [comment]
Thank you, I will try your suggestion out.
