### ISSUE TITLE
getArrayBuffer: null is not an object (evaluating 'r.byteLength')

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#6962]
**mapbox-gl-js version**: 0.46
**browser**: Mobile Safari 10.3.3

### Steps to Trigger Behavior
 1. Load a raster map

This seems to happen very rarely, but the fix is trivial.

Error:
https://sentry.io/share/issue/ecd7254fe5234e128fc91152272f2fcb/

Fix would be simply adding a check for `response` in `getArrayBuffer()`.

**Comment by mourner** [comment]
@hyperknot Would you be open to a pull request if the fix is trivial?

**Comment by ansis** [comment]
It looks like this was fixed in https://github.com/mapbox/mapbox-gl-js/pull/7371/files
