### ISSUE TITLE
Publish Flow type definitions alongside compiled bundle

### ISSUE THREAD

**Issue by anandthakker** [mapbox/mapbox-gl-js#6963]
There isn't currently a straightforward way for a downstream consumer of Mapbox GL JS to benefit from the Flow type annotations that exist throughout our source code (and, specifically, on our public API).  We should find a way to distribute `dist/mapbox-gl.js.flow` alongside the main bundle.

https://github.com/facebook/flow/issues/5871 suggests that the `flow gen-flow-types` tool may get deprecated soon and so we probably don't want to rely on that. 

Since we _do_ include `src/` in our npm package, we could use the approach mentioned in https://github.com/facebook/flow/issues/5871#issuecomment-376018369 -- i.e., have `dist/mapbox-gl.js.flow` look like:

```js
// @flow
export * from '../src/index.js';
```

This almost works, except that the downstream package would need to add many of the ignores that we use: https://github.com/mapbox/mapbox-gl-js/blob/f55e5489e249da575b7cd0ff80dc71ac970b714d/.flowconfig#L2-L12

**Comment by shanshanzhu** [comment]
Can you try this in the .flowconfig? `<PROJECT_ROOT>/node_modules/.*`
