### ISSUE TITLE
label's position not in good location

### ISSUE THREAD

**Issue by Rajavelu** [mapbox/mapbox-gl-js#6978]
Hi,
I want to change continent/country label's position. Is it possible?

For example refer attached image, want to change position of 'Europe' label. 
<img width="826" alt="screen shot 2018-07-17 at 6 56 42 pm" src="https://user-images.githubusercontent.com/3033600/42821896-4027371e-89f7-11e8-957a-426d798b595b.png">

**Comment by jfirebaugh** [comment]
Hi — thanks for using Mapbox. This repo is for reporting issues, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please refer to our [help documentation](https://www.mapbox.com/help/), ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox), or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).
