### ISSUE TITLE
Snap to dominant street orientations

### ISSUE THREAD

**Issue by 1ec5** [mapbox/mapbox-gl-js#6982]
## Motivation

@mourner made a map that [visualizes the dominant street orientations](https://blog.mapbox.com/visualizing-street-orientations-on-an-interactive-map-1eefa6002afc) in the current viewport. In many localities, the street grid is the frame of reference for the cardinal directions, even if the roads are generally slightly offset from true cardinal directions. From an aesthetic point of view, a dominant street grid would be so prominent on the map that aligning the map to it would make the map look much more polished. (Maybe you can tell I’m the sort of person who notices when a wall-mounted painting is lopsided.)

[![before](https://user-images.githubusercontent.com/1231218/42851446-9879a3b8-89e1-11e8-8121-8dc763e06a81.png)](https://mourner.github.io/road-orientation-map/#13.96/39.10383/-84.51033) [![after](https://user-images.githubusercontent.com/1231218/42851451-9da019e4-89e1-11e8-942d-c84274813c96.png)](https://mourner.github.io/road-orientation-map/#13.96/39.10383/-84.51033/-10)
_Cincinnati, before and after a 10° clockwise rotation_

## Design

When viewing an area where the dominant street grid is slightly offset, clicking the rotation button should rotate the map to the “local north” instead of true north. The rotation gesture could snap to any dominant street orientation, including the local north.

### Implementation

I’m unsure whether the local north snapping behavior should go into this library itself or whether it should be a plugin. But we don’t have a separate plugin repository, so I figure this is a decent place to start.

/cc @ajashton @peterqliu @samanpwbb

**Comment by stevage** [comment]
Wow, that's a pretty interesting cartographic question. Personally I think I'd find it pretty weird and disorienting seeing Melbourne snapped to true north instead of its usual jaunty 7.5 degree angle.

Kind of feels a bit premature to put something so experimental and untried in the core library though, right?

**Comment by andrewharvey** [comment]
> Wow, that's a pretty interesting cartographic question. Personally I think I'd find it pretty weird and disorienting seeing Melbourne snapped to true north instead of its usual jaunty 7.5 degree angle.

I think that's just because you're so used to seeing it that way that anything else looks weird. Most of the old paper tourist maps of Melbourne CBD I've seen are aligned to the street grid.

**Comment by stevage** [comment]
>I think that's just because you're so used to seeing it that way that anything else looks weird.

Oh, absolutely. It would be weird to most users, too, I imagine. Unless of course it was a particular feature of the map that made sense.

Also, the CBD is a bit different, it's on a different angle again :) Definitely printed CBD maps are generally aligned vertically.

**Comment by 1ec5** [comment]
> Definitely printed CBD maps are generally aligned vertically.

Yes, I should point out that paper maps are my original inspiration for this idea. I’ve collected a number of tourist maps oriented to the street grid, as well as some larger-scale maps that do likewise. But there are also plenty of printed store locator maps and such that are rotated too.

> Kind of feels a bit premature to put something so experimental and untried in the core library though, right?

Perhaps! A plugin might well be the right way for this feature to prove its worth to start out with. I don’t know if it would require access to internals though. Either way I would agree with keeping this behavior somehow opt-in to start out with, because developers migrating from other map libraries would likely be surprised by the map rotating away from due north.

There’s definitely a point at which there’s so much noise in the orientations that the map would revert to the existing behavior. I don’t know what that threshold would be. Perhaps it should depend not only on the predominance of a certain street orientation but also whether the streets at the very center of the map conform to that orientation. (The viewport could be just off to the side of the CBD.)

**Comment by ansis** [comment]
This seems like a really interesting idea for a demo and/or plugin but it doesn't seem suitable for core mapbox-gl-js.
