### ISSUE TITLE
Allow smaller zoom than 0 in portrait (mobile) views

### ISSUE THREAD

**Issue by juho-hanhimaki** [mapbox/mapbox-gl-js#6983]
## Motivation

In portrait mode, especially on mobiles, the smallest available zoom level 0 shows only a part of the world in latitude direction. This is because map doesn't wrap in longitude direction (world copies aren't allowed in longitude direction).

This is issue because in some applications it might be necessary to see whole world in mobile (portrait) views.

In this example on iPhone X we're unable to see markers in Asia and west US because zoom is already minimum:
![Minimum zoom on mobile](https://i.imgur.com/CyibkMh.png)

**Comment by jfirebaugh** [comment]
Thanks for the report; we're tracking this in #3055.
