### ISSUE TITLE
mapboxgl-style-spec (v13.0.1): import broken "Can't resolve 'fs' in browser

### ISSUE THREAD

**Issue by lamuertepeluda** [mapbox/mapbox-gl-js#6984]
I think latest mapboxgl-style-spec is broken for importing into browser. I use it really a lot for creating GeoJSON feature filters dynamically also outside mapboxgl.

Module: `mapboxgl-style-spec`
Version: 13.0.1 (latest npm available package)
Issue: import broken "Can't resolve 'fs'
Platform: browser

Demonstration: https://stackblitz.com/edit/js-kqrbqj

Latest working version I tried was 11.1.1

**Comment by lamuertepeluda** [comment]
Guys I just tried with @mapbox/mapbox-gl-style-spec@13.1.0

Problem still exists! Maybe you should consider reopening this issue...

**Comment by jfirebaugh** [comment]
The fix wasn't included in 13.1.0. It will be in the next release.

**Comment by lamuertepeluda** [comment]
I see. I'll wait for it. Thanks for your prompt reply :)

**Comment by nicholas-l** [comment]
I am still getting this error even though I am using 13.1.1-beta.1 and I can see the require('fs') in the dist/index.js file. Has the dist file been updated with the change?

**Comment by mollymerp** [comment]
Sorry about that @nicholas-l – I just published `v13.1.1`. Let us know if you still have an issue with that version.

**Comment by nicholas-l** [comment]
Excellent! thanks for the quite turn around 👍
