### ISSUE TITLE
How to constrain the map to a region spanning the 180/-180 longitude?

### ISSUE THREAD

**Issue by interDist** [mapbox/mapbox-gl-js#6985]
### Question

Mapbox-GL JS library allows using the `maxBounds` attribute or `setMaxBounds` function to constrain the displayed map to a specific geographic region. However, when the region spans the longitude of 180/-180 degrees, the result is the whole length of the “world strip” (between the two specified latitudes), instead of the desired box.

For example, the bounding box for Kiribati is {"northeast": [177.048, 4.900], "southwest": [-174.743, -11.646]} but the map cannot be constrained to this box correctly when using these coordinates directly.

(I realize this sounds like a specific use case, but I do think this warrants a clarification in the documentation.)

### Links to related documentation

https://www.mapbox.com/mapbox-gl-js/api/#map (parameter `options.maxBounds`)
https://www.mapbox.com/mapbox.js/api/v3.1.1/l-map-class/#map-maxbounds (map state `maxBounds` option)

**Comment by ryanhamley** [comment]
Hey @interDist thanks for the issue report. This is something that came up recently in a separate discussion of clamping latitude inputs to valid Web Mercator values. You can see the discussion [here](https://github.com/mapbox/mapbox-gl-js/pull/6918). I agree that the documentation can use some clarification around the issue of handling latitude and longitude but we're also working on a fix to make an example like you described work as expected.

**Comment by stevage** [comment]
Shouldn't the bounding box in question be around the other way? That is:

```
{"northeast": [-174.743, 4.900], "southwest": [177.048, -11.646]}
```

**Comment by mourner** [comment]
@interDist had the same thought as @stevage — can you try this out with the correct values?

**Comment by interDist** [comment]
@mourner  , @stevage  : when I use the bbox 
```
{"northeast": [177.048, 4.900], "southwest": [-174.743, -11.646]} 
```
the map initially displays correctly (top or left image) but upon any interaction, snaps to the 180 longitude (bottom or right image) and then scrolls through the whole “length” of the world.
![KI correct region](https://user-images.githubusercontent.com/1909012/43187982-5536cbd6-8ff3-11e8-95cd-248c1152625a.png)
![KI snapped to 180](https://user-images.githubusercontent.com/1909012/43188567-ad5b475a-8ff4-11e8-8f83-3349f05cdd0c.png)

but when I use the suggested bbox
```
{"northeast": [-174.743, 4.900], "southwest": [177.048, -11.646]}
```
the map shows a completely unrelated part of the world. only upon any interaction, the map reloads and then shows the correct region.
![KI incorrect region](https://user-images.githubusercontent.com/1909012/43188194-d6518166-8ff3-11e8-8c50-53a7b18875d9.png)

Here is another example, for Fiji.
Image 1: map displays the correct region for bbox `{"northeast": [179.900, -12.261], "southwest": [-179.900, -21.943]}`
![FJ correct region](https://user-images.githubusercontent.com/1909012/43188741-2bc823ba-8ff5-11e8-8032-e4f531499e59.png)

Image 2: map snaps to 180 longitude upon interaction
![FJ snapped to 180](https://user-images.githubusercontent.com/1909012/43188790-49df7060-8ff5-11e8-89b2-8e6b8383f1ee.png)

Image 3: map displays incorrect region for bbox `{"northeast": [-179.900, -12.261], "southwest": [179.900, -21.943]}`
![FJ incorrect region](https://user-images.githubusercontent.com/1909012/43189364-af2eeef4-8ff6-11e8-9c6b-c56486a054e2.png)

Image 4: map reloads and shows a somehow correct region upon interaction
![FJ snapped to approx region](https://user-images.githubusercontent.com/1909012/43189417-d37ca742-8ff6-11e8-965e-16ca2ce292d9.png)

**Comment by ryanhamley** [comment]
@interDist Can you please provide a minimal example that shows this behavior in JSBin or somewhere like it? That would be a big help in diagnosing the issue.

**Comment by stevage** [comment]
https://codepen.io/stevebennett/pen/EpvKqa

https://codepen.io/stevebennett/pen/rrzeEX

**Comment by interDist** [comment]
In addition to @stevage 's codepens, here is an example that replicates quite closely the setup on our web site: https://jsbin.com/zihuhukepa/edit?js,output
At first, Fiji will appear in the centre of the map, as expected, but you will notice that an interaction with the map will cause it to 'jump'.

**Comment by noizyboy** [comment]
Having similar issues when trying to constrain a MapBox map to just New Zealand. 

Because most of NZ is to the west of 180°, but the Chatham Islands are just across it to the east (at about -176°), it's difficult to set maxBound values there that doesn't cause all the sorts of problems that can be seen in the examples above. 

e.g. If I try to allow for about 20° leeway to the east and west of the country, we end up with this herky-jerky thing...
https://jsbin.com/temorul/edit?output
