### ISSUE TITLE
3d flying trajectory with polylines

### ISSUE THREAD

**Issue by IvanovSP** [mapbox/mapbox-gl-js#6987]
Hello. As i understand currently mapbox have the functionality to set polyline with an array of dots.

**But**  i have task to set flying trajectory where different points of polyline could be on a different altitude. So polyline could be not parallel to the ground.

cant find anything here https://www.mapbox.com/mapbox-gl-js/style-spec#layers-line

as i understand only thing that could be done about it with fillExtrusion like in this example? https://blog.mapbox.com/run-the-catalina-eco-marathon-in-3d-a176aea18094

Maybe you have some plans with adding z coordinate to line array for building complex polyline?

**Comment by jfirebaugh** [comment]
Hi @IvanovSP, we're tracking this feature request in #3993.
