### ISSUE TITLE
how to prevent multiple popup with multiple layers(geojson and symbo layer) by click event?

### ISSUE THREAD

**Issue by szoyaung** [mapbox/mapbox-gl-js#7003]
first, my english is very bad, If the writing is wrong, please forgive！
i have two layer，all source type are geojson，and type are symbol, 
when i click the symbol which has overlap other layer symbol,  it will open two popup window  belong to the two layer, 
how can i prevent this situation and only open the top symbol's popup window??
thranks for your answer！

**Comment by ansarikhurshid786** [comment]
Hi, 
Have you got solution. I am also facing same problem.

**Comment by szoyaung** [comment]
@ansarikhurshid786

**Comment by szoyaung** [comment]
@ansarikhurshid786
no, have not~

**Comment by szoyaung** [comment]
@jfirebaugh

**Comment by cs11wcq** [comment]
I have this same issue. Anyone know the solution?
