### ISSUE TITLE
Benchmark sharing is broken

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#7006]
When you click on the "Share" button in the benchmark view, you get the following error — most likely due to the [recent shutdown of anonymous gists](https://blog.github.com/2018-02-18-deprecation-notice-removing-anonymous-gist-creation/). We have to find another way to share benchmarks. cc @jfirebaugh @anandthakker 

![image](https://user-images.githubusercontent.com/25395/43063494-a1a2b40c-8e64-11e8-96ef-9cebc9f840ec.png)

**Comment by anandthakker** [comment]
@mourner yep -- Dupe of https://github.com/mapbox/mapbox-gl-js/issues/6224
