### ISSUE TITLE
Add ability to mask layer by GeoJSON geometry

### ISSUE THREAD

**Issue by bcartmell** [mapbox/mapbox-gl-js#7018]
Need ability to mask/clip layers (such as 'raster' and 'image') to a GeoJSON Polygon or MultiPolygon.

Ideally, one would be able to reference the GeoJSON layer in a 'paint' or 'layout' style property as 'mask', 'clip-geometry', or similar.

**Comment by mourner** [comment]
Currently there are no plans to implement this in the core because it's a relatively rare use case that requires a lot of effort to implement, and our team is focused on higher priority issues at the moment. 

However you can try a workaround of adding an "inverted" GeoJSON polygon which occupies the entire world with a hole in the shape of a polygon you need as a mask, and overlaying that inverted polygon on top of your raster layer.

**Comment by jstratman** [comment]
If you're okay with just masking, turf.mask() offers an easy solution: http://turfjs.org/docs/#mask   I haven't personally used it for anything more than relatively simple polygons and have relied on pre-processing complex multipolygon masks, so don't have a great sense of its limits.

**Comment by bcartmell** [comment]
@mourner, the 'inverted' geojson option will not work for me because I want to keep the maps base imagery visible.  I'm looking to mask an image that was added on to the map as layer type 'image'.

@jstratman, Turf.mask() is for masking one geometry against another, which is not quite what I'm looking for here.  I  have a layer of type 'image' that I need to clip to a geometry.

I think this would be a beneficial feature as mapbox-gl-js could apply this during the layer render process with a lot less overhead than could otherwise be achieved.

I've also thought about achieving this through a plugin, but I cannot find any documentation around the plugin system.  Is there some available?  Is there a method for plugins to hook into the layer rendering process?

**Comment by bcartmell** [comment]
@franciscolourenco, I ended up using a separate canvas to perform the clipping and then render the output on the map via the 'canvas' layer type.

**Comment by planemad** [comment]
Related feature request to have an inverted fill to mask layers: https://github.com/mapbox/mapbox-gl-js/issues/6267

**Comment by danielfdsilva** [comment]
@bcartmell Do you have a code sample of how you did this? Or could you elaborate? Many thanks

**Comment by bcartmell** [comment]
@danielfdsilva, unfortunately, the code is proprietary so I'm not sure how much detail I can provide.  I'll just say that the goal is to leverage the clip() method of CanvasRenderingContext2D.

**Comment by indus** [comment]
I need this feature as well. just to give some additional applications where this would be handy:
- a "slideable (raster) layers"  a bit like this: https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-compare/
- masking heatmaps (lets say you have a heatmap of seasurface temperature based on a grid of meassurements then it wouldn't make sense when the blur of the heatmap draws over land)

**Comment by tomasdev** [comment]
> Related feature request to have an inverted fill to mask layers: #6267

I may have a race condition on my example, but keep refreshing till you see it. https://jsfiddle.net/3tw94vm5/

I've used a TurfJS `circle` of 0.5km and then used the booleanWithin to make sure any given street (from the `road` layer of streets) was entirely fit in that circle. Then just add some coloring et voilá.

<img width="660" alt="Screen Shot 2019-07-10 at 5 12 30 PM" src="https://user-images.githubusercontent.com/364033/61005345-09d49900-a336-11e9-884b-db756c3eb04b.png">

**Comment by willymaps** [comment]
Clipping raster layers based on vector geometry would be great for creating views like this, which may become more relevant if globe view integrates a terminator/sun position:

![image](https://user-images.githubusercontent.com/12721145/164283970-f27eb498-e9fb-4ab7-8214-1298d7c1d055.png)

Image: https://www.fourmilab.ch/cgi-bin/Earth
Related: https://github.com/mapbox/mapbox-gl-js/issues/2490#issuecomment-566249359
