### ISSUE TITLE
Changing styles causes Directions to break 

### ISSUE THREAD

**Issue by mikeomeara1** [mapbox/mapbox-gl-js#7019]
Please see original issue post [#5180](https://github.com/mapbox/mapbox-gl-js/issues/5180) in which the OP never provided a repro (and thus is was closed).

If you change a maps style with directions already rendered you end up with hundreds of errors: `Error: The layer 'directions-route-line-alt' does not exist in the map's style and cannot be queried for features.`

Example was requested in previous issue which I'm providing here: [https://plnkr.co/edit/M8mj1WTH1KjDa1dhiUKw?p=preview](https://plnkr.co/edit/M8mj1WTH1KjDa1dhiUKw?p=preview). 

This example was generated from the directions example: [https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/](https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-directions/)

Steps to Repro:

1. Set start and end points for directions
2. Hit "Change Style" button at the top

After every mouse movement or other map interaction the error noted above is generated.

**Comment by mikeomeara1** [comment]
I had to work around this by removing the directions control and directions polylines by:

```
       this.directionsControl.removeRoutes();
       this.map.removeControl(<any>this.directionsControl);
```

But this requires the user to re-do all their directions requests after the map style changes.

**Comment by mourner** [comment]
Let's track this in the Direction plugin's repo, since the issue appears to be on that side.
