### ISSUE TITLE
Vector tiles not loading in IE 11

### ISSUE THREAD

**Issue by Rajavelu** [mapbox/mapbox-gl-js#7022]
Hi,
Still https://github.com/mapbox/mapbox-gl-js/issues/3040 not fixed. right ?
Bcoz, i met the same issue till now in Internet Explorer version: 11.0.9600.16428

Also, tried as following:
_var map = new mapboxgl.Map({
    container: 'map',
    style: {version: 8, sources: {}, layers: []},
    // style: 'mapbox://styles/mapbox/streets-v9',
    center: [-74.50, 40],
    zoom: 9
});
map.setStyle('mapbox://styles/mapbox/streets-v9');_

But not working :(

**Comment by jfirebaugh** [comment]
This is #4623.
