### ISSUE TITLE
Fill-color changes in same step bracket

### ISSUE THREAD

**Issue by rishabhjain30** [mapbox/mapbox-gl-js#7026]
Mapbox-gl-version: v0.46.0

Created a map with the following style json, however in the same layer with the property value in same bin, different variants of same colors appear in random features
{
  'fill-color': [
        'step',
        ['get', 'aff_bld'],
          '#000000', 
         0, '#d73027',
         11, '#fc8d59',
         15, '#fee08b',
         21, '#d9ef8b',
         40, '#91cf60',
         70, '#1a9850', 
        ],
    'fill-opacity': 0.7,
    'fill-outline-color': '#ffffff
};
![image](https://user-images.githubusercontent.com/6352329/43230627-9d1d2894-9086-11e8-93bc-6119a78b507a.png)
All the grids in the above image have value in the same 0-11 bin

**mapbox-gl-js version**:

**browser**:

### Steps to Trigger Behavior

 1.
 2.
 3.

### Link to Demonstration

https://jsbin.com/

**Comment by jfirebaugh** [comment]
It looks like you have overlapping/stacked features in the darker bins.

If that's not the case, please create a minimal self-contained example on [jsbin.com](http://jsbin.com/?html,output) that demonstrates the issue.
