### ISSUE TITLE
Cannot initialize Map

### ISSUE THREAD

**Issue by benydc** [mapbox/mapbox-gl-js#7028]
**mapbox-gl-js version**:0.47.0

**browser**: Firefox

I'm trying to initialize the Map but I'm getting an error on the constructor of Map:
`TypeError: mapboxgl.Map is not a constructor`

This is my code:
```
import * as mapboxgl from 'mapbox-gl';

    (mapboxgl as any).accessToken = 'TOKEN';
    const map = new mapboxgl.Map({
      container: this.mapboxWrapper,
      style: 'STYLE_URL',
      center: [24.579,46.470], // starting position
      zoom: 8.5, // starting zoom
      maxZoom: 8.8
    });
```

I'm using Typescript 2.9.2

### Steps to Trigger Behavior

 1.
 2.
 3.

### Link to Demonstration

https://jsbin.com/

**Comment by mourner** [comment]
Unfortunately there's not enough information for us to diagnoze the issue — you didn't fill the blanks in the issue template. Will reopen if you provide us with a minimal, reproducible test case.
