### ISSUE TITLE
How to update feature fill color after map initialize?

### ISSUE THREAD

**Issue by benydc** [mapbox/mapbox-gl-js#7030]
**mapbox-gl-js version**: 0.47.0

### Question

I initialized the map with a custom style done on Mapbox Studio.

I want to change fill color for a certain feature in that style layer, how can I do this?

I tried to use setPaintProperty but documentation doesn't show how to select a specific feature using a custom property, ex. id

**Comment by ansis** [comment]
Hi — thanks for using Mapbox. This repo is for reporting issues, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please refer to our help documentation, ask other users on StackOverflow, or reach out to our excellent support team.

https://www.mapbox.com/mapbox-gl-js/api/#map#setfeaturestate
https://www.mapbox.com/mapbox-gl-js/style-spec#expressions-feature-state
https://www.mapbox.com/mapbox-gl-js/example/hover-styles/
