### ISSUE TITLE
Style-spec docs not recognizing mouse hover location for scrolling

### ISSUE THREAD

**Issue by mzdraper** [mapbox/mapbox-gl-js#7034]
**browser**: Chrome 67 on macOS

### Steps to Trigger Behavior

 1. Go to docs (eg: https://www.mapbox.com/mapbox-gl-js/style-spec/#layers-heatmap)
 2. Scroll on side bar then main
 3. Switch back to side bar and scroll

### Demonstration

![large gif 1664x1278](https://user-images.githubusercontent.com/25856619/43281302-2dbe187c-90c8-11e8-84c0-d4d109073e7e.gif)

### Expected Behavior
If the mouse is hovering over the side bar, the sidebar should scroll instead of the main docs (right side).

### Actual Behavior
This "sticky" scroll isn't always registering which container the mouse is in when hovering, especially the sidebar is at the top or bottom.

(cc @colleenmcginnis @HeyStenson)

**Comment by jfirebaugh** [comment]
Are you seeing the main docs scrolling instead of the sidebar even when the sidebar _could_ scroll in the given direction? I can only reproduce the main docs scrolling when scrolling up when the sidebar is at the top, or down when it's at the bottom, which is the usual behavior of overflowing elements (e.g. the same thing happens with this comment box if I make it shorter than the contents).

**Comment by andrewharvey** [comment]
> Are you seeing the main docs scrolling instead of the sidebar even when the sidebar could scroll in the given direction?

Yes, I can reproduce that.

**Comment by mzdraper** [comment]
> Are you seeing the main docs scrolling instead of the sidebar even when the sidebar could scroll in the given direction?

Yes.

> I can only reproduce the main docs scrolling when scrolling up when the sidebar is at the top, or down when it's at the bottom, which is the usual behavior of overflowing elements

It occasionally occurs when the sidebar is neither at the top or bottom as well.
![large gif 1942x1290](https://user-images.githubusercontent.com/25856619/43349654-2c8b6538-91b6-11e8-8626-7dafa0b850e1.gif)

**Comment by colleenmcginnis** [comment]
@mzdraper this should be fixed post #7530.
