### ISSUE TITLE
Features with same id

### ISSUE THREAD

**Issue by benydc** [mapbox/mapbox-gl-js#7038]
**mapbox-gl-js version**: 0.47.0

**browser**: Firefox

### Steps to Trigger Behavior

 1. Imported my GeoJSON as tiles to Mapbox Studio
 2. setFeatureState when mouse is over
 3. two features have same fill-color instead of one

### Link to Demonstration

I don't have a private JSBin. 

https://jsbin.com/

**Comment by benydc** [comment]
Here is the JSFiddle:
http://jsbin.com/gifakub/edit?html,output

The setFeatureState doesn't even work in JSFiddle with setPaintProperty().

**Comment by asheemmamoowala** [comment]
The console shows 
```
Error: The sourceLayer parameter must be provided for vector source types.
```

The first argument to the `map.setFeatureState` needs `source`, `id`, and for vector sources `sourceLayer` properties.

**Comment by benydc** [comment]
Ok, updated to include the sourceLayer but the issue with duplicate id for feature is still there, try and hover over on one of the left top white box.

http://jsbin.com/gifakub/edit?html,output

**Comment by benydc** [comment]
@asheemmamoowala tried installing latest version of tippecanoe via brew but always getting 0.33.1, are you able to update the brew version to latest so I can use the id generation?

**Comment by ericfischer** [comment]
Oh, sorry, I didn't tag the release but will do that now. https://github.com/mapbox/tippecanoe/releases/tag/1.30.3

**Comment by pilaas** [comment]
Above suggestion doesn't work. `queryRenderedFeatures` returns list with items which IDs are duplicated and such items contains different features (in other words, same array's items IDs but different features within those items). Running `setFeatureState` with this duplicated ID affects two territories on map (if their styling depends on feature state). Looks like `queryRenderedFeatures` returns IDs within tile's scope and `setFeatureState` takes ID and applies it to every feature which has  same ID within its tile. If it's not desired behaviour I can create example, let me know.
