### ISSUE TITLE
How to query coordinates of a value within a filtered layer that is outside the viewport?

### ISSUE THREAD

**Issue by gabrielmoncea** [mapbox/mapbox-gl-js#7046]
I was using `queryRenderedFeatures` to get the coordinates of a point and then `flyTo` that particular location. When testing it, I discovered that it works only when that point is in the viewport.
Is there a method to get the coordinates of a value within a filtered layer that is outside the viewport?

**Comment by jfirebaugh** [comment]
No, not from `queryRenderedFeatures` or `querySourceFeatures`. You'll have to arrange to get the coordinates through some other means.

**Comment by gabrielmoncea** [comment]
Can you give me some suggestions? Or an idea of how I can implement this? As vast as the mapbox documentation is I might have missed something that could help me
