### ISSUE TITLE
I wanna to know how can I get bearing of user movement using onUserLocationUpdate.

### ISSUE THREAD

**Issue by Edison4mobile** [mapbox/mapbox-gl-js#7048]
From onUserLocationUpdate, I am getting below result.
location : {
        timestamp: 0,
        latitude: 0.0,
        longitude: 0.0,
        altitude: 0.0,
        heading: 0.0,
        accuracy: 0.0,
        speed: 0.0
      }
So, I thought, the heading value is bearing of user movement. but it seems this is not.
Is there any way that i can know bearing?
Thanks a lot.

**Comment by asheemmamoowala** [comment]
Unfortunately there's not enough information for us to diagnose this issue — please fill the blanks in the issue template. Will reopen if you provide a minimal, reproducible test case.
