### ISSUE TITLE
Using `setFeatureState` with Vector Tiles

### ISSUE THREAD

**Issue by manassra** [mapbox/mapbox-gl-js#7049]
**mapbox-gl-js version**: 0.47.0

### Question
Is there a way to use `setFeatureState` with VectorTile layers if the feature id is a string?

**Context**: I have a VectorTile source that serves tiles I generated using Tippecanoe. Having noticed that `setFeatureState` relies on having a unique id for each feature, I tried re-generating the tiles with Tippecanoe, this time with setting the `id` property for each feature with it's uuid property (an identifier that I don't control myself). Tippecanoe complains that non-numeric ids aren't allowed according to the [Vector Tile Spec](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L32). How do I set the state of the feature if I can't set its id? Can `setFeatureState` be used with properties (by having `id` under the feature properties)?

**Comment by asheemmamoowala** [comment]
Tippecanoe is reporting correctly that string values are not valid ids in v2.1 of the spec. Try using integer ids instead. 
`Map#setFeatureState` does not work with `feature.properties.id`, it needs `feature.id`

**Comment by manassra** [comment]
Hi @asheemmamoowala! I unfortunately cannot use integer ids (since the feature ids are generated elsewhere as uuids).Is there anyway around this?

**Comment by ericfischer** [comment]
I recently added a Tippecanoe feature to auto-assign numeric IDs, which you may find useful: https://github.com/mapbox/tippecanoe/pull/615

**Comment by manassra** [comment]
Thanks for the pointer, @ericfischer. This will be helpful, but I will still have to maintain a mapping between the auto-generated ids and the feature uuids somewhere for the local join to work. I am wondering if there is an easier way to do this.

**Comment by devPuppySim** [comment]
Hello, I started using tippecanoe about 15 minutes ago and I have a question on using this new feature.

How exactly would I use this new feature to set the feature.id to be equal to an id attribute in the geojson? In the super basic example command from the documentation, the command I'm using is this (on a Mac): `$ tippecanoe -o LHA_tiles.mbtiles -zg --drop-densest-as-needed Desktop/LHA2017_tiles/lha_reallysimple.json`. 

How do I use --generate-ids to convert my attribute "LHA_NUM" to be the feature.id of the output .mbtiles?

Thanks for your help in advance!

**Comment by asheemmamoowala** [comment]
@devPuppySim this issue tracker is for reporting bugs and feature requests for the gl-js project only.
For "how do I" questions like this, please refer to the [documentation for tippecanoe](https://github.com/mapbox/tippecanoe/blob/master/README.md#adding-calculated-attributes), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). Thank you!
