### ISSUE TITLE
Add draggable option to Popups

### ISSUE THREAD

**Issue by bhatt40** [mapbox/mapbox-gl-js#7054]
## Motivation

In our application, when the user hovers over a feature in a layer, a popup appears with data about the feature.  If the user clicks on the feature, it 'freezes' the popup, meaning that it will stay open even if they hover off the feature.  If they click anywhere else on the map, the popup will become unfrozen and disappear.

We've had customers request to be able to drag and move a frozen popup.  They still want to see the data in the popup, but the popup may be covering features in other layers that they also want to see.

## Design Alternatives

Our current workaround is to attach the popup to a draggable marker, then render the marker as a move icon below the popup.  The user can click and drag the marker to move the popup.

![image](https://user-images.githubusercontent.com/3288516/43465553-3064df64-94a3-11e8-831a-3f5d8331960a.png)

It would be cleaner for our UI if the user could click and drag the popup itself.

## Design

Adding a draggable option to the Popup object and adding the corresponding methods would be the simplest solution for the user and would be in line with the new draggable option on the Marker object.

**Comment by mourner** [comment]
Thanks for the report! Unfortunately, context-sensitive, rarely used features like this are out of scope for the GL JS core — we'd like to keep it focused and not add too much UI logic. We feel it's better left to users to implement, e.g. using `popup.setLngLat(lngLat)` method to move the popup. Your solution is quite nice as well.

**Comment by hussamkhatib** [comment]
@bhatt40 You can use [draggabilly](https://github.com/desandro/draggabilly)
