### ISSUE TITLE
on canvas changed callback

### ISSUE THREAD

**Issue by rehovicova** [mapbox/mapbox-gl-js#7059]
**mapbox-gl-js version**: v0.46.0

### Question
Is there any way how to tell when canvas refreshed? I will show an example which should make it clear. 
I have a map and I am updating the center `setCenter();` and the zoom `setZoom();`. Then I am taking the map canvas `getCanvas();` and drawing it onto my canvas.

```
let canvas1 = this._map_overlay.getCanvas();
this._map_overlay.setCenter([lng, lat]);
this._map_overlay.setZoom(zoom);
let canvas2 = this._map_overlay.getCanvas();
```
In this case the `canvas` is not updated - the `canvas1` and `canvas2` are the same. However this is working:

```
let canvas1 = this._map_overlay.getCanvas();
this._map_overlay.setCenter([lng, lat]);
this._map_overlay.setZoom(zoom);
setTimeout(function() {
      let canvas2 = this._map_overlay.getCanvas();
}, 20);

```

The canvas2 is now updated base on the new zoom and center. This is a hot fix for this issue but I would rather some callback that would tell me when the canvas is updated. Something like:

```
this._map_overlay.on('canvasChanged', e => { 
      // Work with updated canvas	
});
```

Is there currently a way how achieve that?

**Comment by jfirebaugh** [comment]
Sounds like you're looking for the [`render`](https://www.mapbox.com/mapbox-gl-js/api#map.event:render) event.

**Comment by rehovicova** [comment]
@jfirebaugh that is working, but it is firing too many times. Is it because it fires with every loaded tile? Is there something what would fire just once after all tiles are loaded?

**Comment by ronalb** [comment]
follow
