### ISSUE TITLE
Symbol layer object with LineString source disappears when zooming out

### ISSUE THREAD

**Issue by everhardt** [mapbox/mapbox-gl-js#7062]
**mapbox-gl-js version**: 0.47.0

**browser**: Chrome, version 68.0.3440.75 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Create a Layer based on a GeoJson source with a feature that has LineString coordinates
 2. Zoom out and the Layer object will disappear

### Link to Demonstration

https://jsfiddle.net/r3ju6p15/

### Expected Behavior
Both red labels ("LineString label" and "Point label") should remain visible when zooming out until you see most of Europe.

### Actual Behavior
"LineString label" disappears. It is not caused by a collission: there is also no red collision box where the label should be.

**Comment by mourner** [comment]
This happens because GL JS automatically drops line strings it considers too small to render as a part of data simplification process. You can work around this by setting `tolerance: 0` in geojson source options, or simply using points instead of line strings for symbols like this.
