### ISSUE TITLE
Option to set token for non-mapbox uri

### ISSUE THREAD

**Issue by loosi** [mapbox/mapbox-gl-js#7064]
## Motivation

We're using mapbox with our own tiles (openmaptiles) - works flawlessly. 
Now we would like to use a custom access_token mechanism to rate requests from third party users. 
Unfortunately right now there is no option to force a token usage for non-mapbox uri. 
JS checks right now if the style uri starts with "mapbox//" and disables any token logic. 

This would be great for self-hosted tiles with rate limiting/quotas or whatsoever.
Attaching a custom token to the style uri is not really a good idea, the following requests for data files won't use that token. 

### Implementation

Actually we just need a "force-token" option for that. There is a lot of logic in the JS to parse and build uri for mapbox, that should not be used for that. 

Side effect: This option could be used in mapbox-gl js for leaflet and work there as well.

**Comment by anandthakker** [comment]
@loosi have you seen the `transformRequest` option that's available on `Map`? https://www.mapbox.com/mapbox-gl-js/api/#map

This should allow you to provide your own access token logic.

**Comment by loosi** [comment]
@anandthakker thx for pointing to that. transformRequests works (at least for uri rewrite). It seems to have problems with custom headers, I'll open another issue for that.
