### ISSUE TITLE
Ternary expression in iconImage expression

### ISSUE THREAD

**Issue by paganaye** [mapbox/mapbox-gl-js#7067]
**mapbox-gl-js version**:

### Question
I have markers with an icon that depend on the property `product_type`.
I would like the image to be based from two properties : (in java syntax) 
`product_type + (selected ? "-selected" : "")`

I have trouble building adding this ternary expression.

### Links to related documentation

This is my existing code.
`
       return new SymbolLayer(layerId, "geo_json_source")
                .withProperties(PropertyFactory.iconImage(Expression.get("product_type")),
                        iconAllowOverlap(true));
`

**Comment by mourner** [comment]
You're looking for the case expression https://www.mapbox.com/mapbox-gl-js/style-spec#expressions-case

**Comment by paganaye** [comment]
I does work, thanks:
For completion the expression is:
`Expression.switchCase(
   Expression.coalesce(Expression.get(MapConstants.PROPERTY_SELECTED), Expression.literal(false)), 
   Expression.literal("-selected"),
   Expression.literal(""))
`
