### ISSUE TITLE
Literal Expression vs Function vs FeatureState of Memory & Performance

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#7072]
i need to join a huge amount of features (millions) with data to color and filter these. The features does only have a id.
I wrote a tile loader to load and unload key value pairs from server per tile of a specific zoom level. For example buildings by level 13. This means i have to call the setPaintProperty on every new tile load. I have to store all key value pairs also, and create a actual list for active tiles. These method needs much memory and is very cpu expensive. 
What is the prefered way and which is the most performant and cpu efficient? I would like to store the data into the feature, because then i don't have to store it twice and have to do the unload of the data on tile unload myself. I understand that featureState will still store this information after the feature is unload. So then this method will be the same as using styling expressions. 
It would be really nice to list all solutions and to compare performance and memory. 
Does someone know if there are other solutions then the following?

I found these solutions
**FeatureState**
https://www.mapbox.com/mapbox-gl-js/example/data-join/

**Literal**
```
const data = {
1: "#4B91BD",
2: "#B5E9FF",
....
}
this.map.setPaintProperty("buildings", "fill-extrusion-color",
        ["get", ["to-string", ["get", "id"]], ["literal", data]]);
```

**Function**
```
const data = [
[1, "#4B91BD"],
[2, "#B5E9FF"],
....
]
this.map.setPaintProperty("buildings", "fill-extrusion-color", {
      property: "id",
      type: "categorical",
      default: "#686868",
      stops: data
    });
```

Maybe it is also good to cluster ids by color. Because i saw, that the color string have to be interpreted, this needs also much cpu ressources. 
Do you also know other performance tips?

**Comment by jfirebaugh** [comment]
By far the most performant and CPU efficient way to do this is to include the color in the feature properties directly, and set `fill-extrusion-color` to `["get", "color"]`. But if you can't do that, then the approaches you listed are good alternatives. Which performs the best probably depends on the size of your data and access/update patterns. You should profile and benchmark to see how they compare for your use case.
