### ISSUE TITLE
MULTIPOINT is not displaying on the map

### ISSUE THREAD

**Issue by dmitrykinakh** [mapbox/mapbox-gl-js#7074]
I've tried to display transit stops (circles) on my map but before I wanted to style them.
I was surprised that type the of data for some reason are not displaying on the map (the same area shows data in QGIS)
QGIS: 
![image](https://user-images.githubusercontent.com/8025637/43257499-a393a1ce-90d8-11e8-8aae-e695e61301f3.png)

Maputnik: 
![image](https://user-images.githubusercontent.com/8025637/43257382-57d8dd26-90d8-11e8-8696-0e64ebeba4c4.png)

Same happens for other my data set which is also MULTIPOINT.

I'm attaching one row from the table from where I'm loading transit stop data to give you an idea what might be wrong.
[example.txt](https://github.com/maputnik/editor/files/2231576/example.txt)

Here also there is a video which illustrates my issue - http://take.ms/wIyhk

**Comment by jfirebaugh** [comment]
Hi @dmitrykinakh. This repo is for reporting issues, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with Maputnik, you'll need to contact the Maputnik developers.
