### ISSUE TITLE
Is it possible to set some "buffer" to download more tiles around viewport?

### ISSUE THREAD

**Issue by rouen-sk** [mapbox/mapbox-gl-js#7082]
Hello,
Right now, when I load map for example on zoom 12 and zoom out to 11, for a second there is "blank space" around map until the tiles are loaded. Is is possible to set some "buffer" to pre-load (download) 1 more tile in each direction on zoom 12, so that when I zoom out, no blank space is visible? 
Something like this for Leaflet: https://github.com/TolonUK/Leaflet.EdgeBuffer

**Comment by asheemmamoowala** [comment]
Duplicate of #2826
