### ISSUE TITLE
Incorrect documentation for null values conversion in to-number expression.

### ISSUE THREAD

**Issue by sharkinsspatial** [mapbox/mapbox-gl-js#7083]
**mapbox-gl-js version**: 0.47.0

**browser**: Chrome 67.0.3396.87

### Steps to Trigger Behavior

 1. Apply filter expression to a source where the property used in the [get](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-get) expression does not exist for the feature.
 2. Use a [to-number](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-types-to-number) expression to convert the null value to 0.

### Link to Demonstration

[jsFiddle](https://jsfiddle.net/d8pbvwjk/7/) (please open devTools to see relevant console warnings).

### Expected Behavior
Non-existent property value should be converted to 0 as described in the [to-number](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-types-to-number) documentation.

### Actual Behavior
A console warning `Could not convert null to number.` is created.

I am using this approach in filter expressions as described in this [issue](https://github.com/mapbox/mapbox-gl-js/issues/5835#issuecomment-350721881).  It also appears that the existing [tests](https://github.com/mapbox/mapbox-gl-js/blob/8a19f6079933817fd73eed71159130b8ac53a00f/test/integration/expression-tests/to-number/basic/test.json#L24) contradict the `to-number` null value handling described in the documentation.

**Comment by anandthakker** [comment]
Ah.  Yeah, IIRC the documentation states our original intent, and I still think that makes sense.

**Comment by Sillson** [comment]
Question about the behavior if someone has a moment to answer -- 

If the the "to-number" function returns 0 from null, doesn't this conflict with parsing a string of '0'? Fore example, if I'm hoping to conditionally style in the following way: 

```
'paint': {
      'circle-color': [
        'case',
          ['all', [">=", ["to-number", ["get", "value"]], 0], ["<", ["to-number", ["get", "value"]], 100]], '#fff',
          ['all', [">=", ["to-number", ["get", "value"]], 100], ["<", ["to-number", ["get", "value"]], 500]], '#000',
          "#2f2f2f"
      ]
    },
```

This means both my null and '0' values return 0.

**Comment by dhaq** [comment]
> 

Did you resolved this issues on iOS?
