### ISSUE TITLE
Using text-color or opacity error

### ISSUE THREAD

**Issue by diversoft** [mapbox/mapbox-gl-js#7089]
Error: layers.points.layout.text-opacity: unknown property "text-opacity"
I use mapbox-gl-js 0.47

**mapbox-gl-js version**:

**Comment by andrewharvey** [comment]
`text-opacity` is a paint property not a layout property, see https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-symbol-text-opacity

**Comment by diversoft** [comment]
thank you andrewharvey，i am using ESRI Weather font, to draw wind, but wind text is blur,
very goood in MS Word

when text-size=24
![image](https://user-images.githubusercontent.com/2303685/43752617-6edca8f8-9a34-11e8-8f43-8ebf227d73e0.png)

when text-size=50
![image](https://user-images.githubusercontent.com/2303685/43752648-97ecd95c-9a34-11e8-9c81-ca5bd67a8346.png)

when text-size=80
![image](https://user-images.githubusercontent.com/2303685/43752669-b62c1aea-9a34-11e8-98dd-5777dea963ac.png)

**Comment by diversoft** [comment]
has some global settings for drawing text？thanks

**Comment by andrewharvey** [comment]
Hi @diversoft thanks for using Mapbox. This repo is for reporting issues, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please refer to our [help documentation](https://www.mapbox.com/help/), ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox), or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).

If you think that you've run into a bug, could you post a new issue with a link to a reproducible example of the issue?

**Comment by diversoft** [comment]
ok
