### ISSUE TITLE
Custom icon for every marker

### ISSUE THREAD

**Issue by mashkovtsevlx** [mapbox/mapbox-gl-js#7092]
[Angular 6, Firebase]
Hello. I'm trying to assign own icon for every marker. I tried to add marker-symbol field in properties for every marker, but it don't help.
Here's my layer config: 

    this.map.addLayer({
        id: 'firebase',
        source: 'firebase',
        type: 'symbol',
        layout: {
          "icon-size": 2,
          'text-offset': [0, 1.5]
        },
        paint: {
          'text-color': '#f16624',
          'text-halo-color': '#fff',
          'text-halo-width': 2
        }
    })

My idea how to make custom marker icons is to make separate layer for every marker type with own icons and to set icon in layer properties. But I think there's a better solution. Thanks

**Comment by mourner** [comment]
You can use [Mapbox GL Expressions](https://www.mapbox.com/mapbox-gl-js/style-spec#expressions). E.g. `['get', 'marker-symbol']` to use a value from the `marker-symbol` property.
