### ISSUE TITLE
Warnings due to undefined feature-state even though setting for all features

### ISSUE THREAD

**Issue by charandas** [mapbox/mapbox-gl-js#7097]
**mapbox-gl-js version**:

0.47.0

**browser**:

Chrome

### Steps to Trigger Behavior

 1. See [JSBin](https://jsbin.com/sehigixuca/1/edit?html,js,console,output)
 2. Open Chrome Devtools as JSBin console won't show the failures

### Link to Demonstration

[JSBin](https://jsbin.com/sehigixuca/1/edit?html,js,console,output)

### Expected Behavior

1. It should not report null on feature-state property since we are setting it, and its even styling it.

### Actual Behavior

1. It reports 4 warnings, but in debugging with mapbox-dev bundle, I see that it happens for each of 10000 features (well I did not step through every single one of them, but that's a guess) in AssertionError (that arises from CompoundExpression). The debugger shows the context and associated feature/feature-state, and feature-state is of course `{}` (unexplainable since it applies the styling fine).

```
Expected value to be of type number, but found null instead.
... repeated 3 more times...
```

### Additional Info

I won't worry about the warnings if this was working for me throughout, but it works only for `fill-color` and not `fill-pattern` (when using [this PR](https://github.com/mapbox/mapbox-gl-js/pull/6289)).

I also am curious about what's up with exactly 4 warnings. Is there a policy in there in somewhere to not spew console when encountering errors in that context.

**Comment by asheemmamoowala** [comment]
@charandas Given that all features may not always have state associated with them, I would recommend adding a type conversion and fallback, like: 
`map.setPaintProperty('ctracts', 'fill-color', ["step", ["number", ["feature-state", "lmi"], 0], "#FFFFFF", 1, "#FFB6C1", 3, "#FAFAD2"])`

> curious about what's up with exactly 4 warnings. Is there a policy in there in somewhere to not spew console when encountering errors in that context.

The warnings are emitted only once, but come from multiple web workers which run in isolation, so you don't see one for each feature. I've opened https://github.com/mapbox/mapbox-gl-js/issues/7122 to track the work to remove the warnings.

**Comment by charandas** [comment]
That worked awesomely @asheemmamoowala. Thanks!
