### ISSUE TITLE
Approach to writing integration tests

### ISSUE THREAD

**Issue by gorshkov-leonid** [mapbox/mapbox-gl-js#7100]
**mapbox-gl-js version**: 0.47.0

### Question
Hi. I want to write integration tests for an application that uses `mapbox-gl`. I don't want to use `mapbox-gl- mock` but I want to test screen and features as `mapbox-gl` do that. But this solution means I need to create test framework (or copy a lot of files from `test` folder of `mapbox-gl`).  

1. Maybe do you have some suggests how to write integration tests for apps that use `mapbox-gl`?
1. Which way do you consider using in future? Are you going to use headless browser instead of `headless-gl` in `node`.
1. What do you think about other frameworks, for example, `headless-chrome`+`pupperteer`+`jest` instead of `headless-gl`? 1. Are you going to extract solution to write integration tests?

**Comment by mourner** [comment]
The way we test Mapbox internally shouldn't matter to external apps — we never intended testing to be exposed publicly in any interface. Use whatever works for you — `headless-chrome` + `puppeteer` sounds like a promising combination which we'd love to explore ourselves, it just requires a very big effort to rewrite our `headless-gl` setup.
