### ISSUE TITLE
Flow types in Style-Spec published module.

### ISSUE THREAD

**Issue by nicholas-l** [mapbox/mapbox-gl-js#7105]
The @mapbox/mapbox-gl-style-spec includes flow types in the library. Most libraries that include flow support include .js.flow files instead of including it in the source files. Would this be possible? Other wise people require a build step in a dependency. If not possible can this build step be documented and included in the package.json file?

Bit of context: I am trying to use the feature_filter and expression modules of this great library 💯 

**mapbox-gl-js version**:
13.1.0
**browser**:
NA
### Steps to Trigger Behavior

 1.
 2.
 3.

### Link to Demonstration

https://jsbin.com/

**Comment by jfirebaugh** [comment]
Hi @nicholas-l, thanks for using Mapbox. You should require/import the `main` entry point specified by `@mapbox/mapbox-gl-style-spec`'s package.json. The structure and contents of individual source files within the package is not considered part of the public API.
