### ISSUE TITLE
Color rendered in map different from (same)color rendered in a div.

### ISSUE THREAD

**Issue by rafiqdeen** [mapbox/mapbox-gl-js#7109]
**mapbox-gl-js version**: 
0.47.0

**browser**: 
Chrome - Version 66.0.3359.139 (Official Build) (64-bit)

**os**: 
Ubuntu 14.04 

### Steps to Trigger Behavior

 1. Open the link in Ubuntu Chrome : http://jsfiddle.net/s306ytar/24/

### Link to Demonstration : 
Link : http://jsfiddle.net/s306ytar/24/

### Expected Behavior
Same color displayed in map and in a div should be the same.

### Actual Behavior
Same color displayed in map is different from the same color displayed in a div.

**Comment by ansis** [comment]
I'm not able to reproduce this. Both colours are identical for me. Can you post a screenshot showing what you are seeing?

**Comment by ryanhamley** [comment]
![screen shot 2018-08-10 at 11 02 54 am 2](https://user-images.githubusercontent.com/4523080/43973725-319454c2-9c8d-11e8-882c-cb63711cea63.png)
![screen shot 2018-08-10 at 11 02 55 am 2](https://user-images.githubusercontent.com/4523080/43973728-31acf5b8-9c8d-11e8-9b91-bd1943eb84ad.png)

Hey @ansis if I check the circle and the div with Mac's color meter, I get slightly different values.

**Comment by ansis** [comment]
Interesting! I'm seeing identical values using color meter

**Comment by jmlopez-rod** [comment]
I have my div background set to this color `#F2F2F2` (242, 242, 242)  but if I set an extrusion to the same color the color I get (248, 248, 248). To make it match I had to go to `#EBEBEB` (235, 235, 235) which magically renders as the same color I wanted.

@ansis Not sure why you are not seeing the difference with the color meter. Mine shows two different colors (not the same as the ones from @ryanhamley) but mine are as follows:

rectangle: (79, 144, 198)
circle: (77, 140, 197)

**Comment by ryanhamley** [comment]
This seems like it could be dependent on the screen and color settings on a user's computer. I see what I posted above if I'm viewing the demo on my monitor, but if I view it on my laptop screen, I see almost identical values (the R channel is off by 1 but G and B are the same). I also confirmed that I didn't have Flux on so the values aren't shifted at all.

**Comment by jfirebaugh** [comment]
I think this is probably a rounding difference in GL implementations which we can't control.

**Comment by ansis** [comment]
I don't think this is just rounding. I think the browser is applying some sort of monitor colour profile or gamma correction while blending. [`EXT_sRGB`](https://developer.mozilla.org/en-US/docs/Web/API/EXT_sRGB) (85% support) could help with this. There would probably also be some performance cost associated with using this. Is this something we should look into further?
