### ISSUE TITLE
Fallback to use non-retina assets

### ISSUE THREAD

**Issue by mick** [mapbox/mapbox-gl-js#711]
Mapbox-gl-js automatically tries to load retina assets on retina screens, but if those images arent available it should fallback to using the non-retina version of the image.

Example: http://mapmeld.github.io/van-gogh-map/#6.06/39.756/-814.736  fails to load on a retina screen with these errors: 
![screen shot 2014-08-19 at 11 50 29 am](https://cloud.githubusercontent.com/assets/26278/3971231/c249f736-27d1-11e4-9b82-9f4142c20955.png)

**Comment by jfirebaugh** [comment]
We have future plans for sprites that would make this unnecessary -- https://github.com/mapbox/mapbox-gl-style-spec/issues/220, https://github.com/mapbox/mapbox-gl-style-spec/issues/222. Outside of changes in that vein, we're not planning to change the behavior of sprite asset requests, so I'm going to close this issue.
