### ISSUE TITLE
Tooltip for navigation controls

### ISSUE THREAD

**Issue by mmmatthew** [mapbox/mapbox-gl-js#7115]
## Motivation
The compass navigation function is not well-known, and could use an explanation. Just clicking the button does not do anything unless the map was rotated.

## Design
A simple tooltip could clarify this, for desktop users at least.

**Comment by andrewharvey** [comment]
I agree we should have `title` attributes on the button which browsers will render as a tooltip on hover.

**Comment by bravecow** [comment]
For compass it would be better to hide like google maps do, I think:

https://bravecow.github.io/mapbox-gl-controls/#p-zoom-compass

**Comment by ansis** [comment]
Thanks for noticing! https://github.com/mapbox/mapbox-gl-js/pull/7373 adds tooltips
