### ISSUE TITLE
map.getCanvas().style.cursor is not working if vector layers overlap

### ISSUE THREAD

**Issue by gabrielmoncea** [mapbox/mapbox-gl-js#7117]
**mapbox-gl-js version**: 0.47

**browser**: Chrome/68.0.3440.106

### Steps to Trigger Behavior

 1. Add more than two layers on a map with the following:
```
                map.on('mouseenter', layerId, function() {
			map.getCanvas().style.cursor = 'pointer';
		});

		map.on('mouseleave', layerId, function() {
			map.getCanvas().style.cursor = '';
		});
``` 
 2. Set the opacity below 0.8 in order to see the layers in places where they overlap.
 3. Move the mouse cursor over the layers to see the behaviour

### Link to Demonstration

I archived a screen recording to show the bug.

[mapbox style cursor bug.zip](https://github.com/mapbox/mapbox-gl-js/files/2282648/mapbox.style.cursor.bug.zip)

### Expected Behavior

In this case, where layers overlap, the cursor should remain as a `pointer` because it leaves the layer, but enters another layer that dictates the cursor to be a pointer.

### Actual Behavior
When the cursor leaves the first layer and enters the other, it changes from `pointer` to `hand` as if the second layer doesn't exist and the cursor is only on the map. The only way to make the cursor change back into a pointer is to move it out of the map or on an html tag like a popup div.

**Comment by jfirebaugh** [comment]
Hi @gabrielmoncea — thanks for using Mapbox. This behavior is as-designed: the `mouseenter` and `mouseleave` fire on an individual layer basis. If you have two or more layers and you want to set an icon when the cursor is over _either_ of them, you'll need to keep a counter of calls, incremented in `mouseenter` and decremented in `mouseleave`, and set the cursor style when it's greater than zero.
