### ISSUE TITLE
'hover' event - mousemove?

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#713]
The 'hover' event emitted by mapbox-gl-js seems the same as 'mousemove' - is there any reason for it not to be named the same?

**Comment by tristen** [comment]
Also [`down`](https://github.com/mapbox/mapbox-gl-js/blob/master/js/ui/interaction.js#L102) should change to `mousedown`.

**Comment by mourner** [comment]
See https://github.com/mapbox/mapbox-gl-js/pull/949 — `down` shouldn't be renamed because it's an internal event for normalizing interactions.
