### ISSUE TITLE
How to put multiple numeric ranges into a single layer?

### ISSUE THREAD

**Issue by dmitrykinakh** [mapbox/mapbox-gl-js#7134]
Hi there,

I was analyzing the https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions in case I'll find a way how to have ranges in my layer.

For example, I've properties dataset where one of the columns is **bedrooms**  which shows count in integer format.

I my mapbox layer I want to have something like:
bedrooms=0
1>=bedrooms<10
10>=bedrooms<20

In mapbox studio I've only this - http://take.ms/VobG8
That allows me to add smth like bedrooms >=10 via

`[
  "case",
  [
    "==",
    ["get", "bedrooms"],
    0
  ],
  "hsl(60, 100%, 90%)",
  [
    ">=",
    [
      "number",
      ["get", "bedrooms"]
    ],
    10
  ],
  "hsl(0, 0%, 0%)",`

But how turn this on into doubled ranges?

PS. Sorry if I put the question int the wrong repo.

**Comment by mourner** [comment]
You're looking for logical expressions such as `all` https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-all — e.g. combining conditions `1 >= bedrooms` & `bedrooms < 10` with `all` will give you a range.
