### ISSUE TITLE
How can I get a mapbox.cn token?

### ISSUE THREAD

**Issue by JoJ123** [mapbox/mapbox-gl-js#7138]
How can I get a mapbox.cn token?
I've sended several mails to them, but didn't get an answer.

We are using MapBox in our global version. 
For our China Deployment we want to switch to mapbox.cn, because with the global one, we can't use the geocoder in China.

Can someone give me the right contact?

**Comment by ansis** [comment]
Unfortunately we can't help with that. I'm guessing you've already tried, but the [china contact page](https://www.mapbox.cn/contact/) or [sales and support](https://www.mapbox.com/contact/) might help.

**Comment by chriswu42** [comment]
Hi @JoJ123, we apologize that you haven't gotten any email responses for your inquiry to our mapbox.cn endpoint. I will check with our team to understand what might have happened, if you haven't already please send us a description of your use case to `china [at] mapbox [dot] com` and I'll have someone on our China team follow up with a solution for your needs. If you still haven't heard back for whatever reason by next week please let me know.

cc @alee321 @raylausn @Cyrussss

**Comment by raylausn** [comment]
Hi @JoJ123 This is Ray from the APAC BD team, may I have your email or contact info so we can talk?
