### ISSUE TITLE
Fire functions before Popup closes?

### ISSUE THREAD

**Issue by leahwchang** [mapbox/mapbox-gl-js#7140]
**mapbox-gl-js version** v0.46.0:

### Question

Hello, been integrating mapbox for 2 weeks now and it works great! My company is trying to add features to popup windows and now I've run into a block. On our map, there are 500 markers so 500 popup windows. We have a street viewer div inside the popup window that initiates when a popup is opened. The problem occurs when I try to close the viewer on popup close event: the popup '.mapboxgl-popup-content' div is removed hence unable access the street viewer div to close the viewer properly. Is there any way to fire some functions before a popup closes? We don't want to use mouseenter/mouseleave since there are too many markers on the map region. Any help or pointers to the right direction is appreciated. Thanks!

**Comment by jfirebaugh** [comment]
Sounds like you're looking for the `Popup` [`close` event](https://www.mapbox.com/mapbox-gl-js/api#popup.event:close).

**Comment by leahwchang** [comment]
Hi @jfirebaugh , we've tried that but the popup div is removed so the content is inaccessible for us.

**Comment by leahwchang** [comment]
Is it possible to slow down the close event?
