### ISSUE TITLE
Mapbox-GL Fails to Load with in Firefox v61.0.2 in Linux  Fedora

### ISSUE THREAD

**Issue by JeromeDane** [mapbox/mapbox-gl-js#7155]
**mapbox-gl-js version**:

**browser**: Firefox 61.0.2 (64-bit) in Linux Fedora (release 28)

### Steps to Trigger Behavior

 1. Load https://www.mapbox.com/mapbox-gl-js/example/simple-map/ in Firefox 61.0.2 in Linux Fedora

### Expected Behavior

Map renders

### Actual Behavior

Map fails to render, throwing the following warning in the developer console:

```
app-8fe07dc58e16336edae7.js:1:105997
Error: WebGL warning: Failed to create WebGL context: WebGL creation failed:
* Error during native OpenGL init.
* Exhausted GL driver caps.
* Exhausted GL driver options.
app-8fe07dc58e16336edae7.js:1:106022
Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Error during native OpenGL init.
* Exhausted GL driver caps.
* Exhausted GL driver options. 
```

**Comment by go-d** [comment]
Probably [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1480755) (happens after update to libdrm 2.4.93):
> The temporary fix is going to about:config, searching security.sandbox.content.read _path_whitelist and adding `/sys/`.

**Comment by ryanhamley** [comment]
Yeah unfortunately this appears to be a bug in Firefox. There's nothing we can do on our end so I'm going to close the issue. Hopefully Firefox will fix the issue soon.
