### ISSUE TITLE
Is there a existing plugin for clusters  I can use to ignore fucking styles and whole screen of circles

### ISSUE THREAD

**Issue by q869939686** [mapbox/mapbox-gl-js#7158]
Is there a existing plugin for clusters  I can use to ignore fucking styles and whole screen of circles?

Leaflet Markercluster is useless!

![image](https://user-images.githubusercontent.com/29123332/44375015-0e2c7380-a524-11e8-9e82-1a5ae1f4bf50.png)

**Comment by jingsam** [comment]
> Everyone is invited to participate in Mapbox’s open source projects and public discussions: we want to create a welcoming and friendly environment. Harassment of participants or other unethical and unprofessional behavior will not be tolerated in our spaces. 

Please read [Code of Conduct](https://www.contributor-covenant.org/version/1/2/0/code-of-conduct.html)
