### ISSUE TITLE
How get marker data, from generated unclustered layer when i`m using GeoJson?

### ISSUE THREAD

**Issue by Tahrz** [mapbox/mapbox-gl-js#7162]
**mapbox-gl-js version**: 0.47

### Question

Hi! How can i get marker info (for example Name, witch i have in GeoJson file), when click on generated marker? 
That`s how i generate unclustered markers:
```
map.addLayer({
        id: "unclustered-point",
        type: "symbol",
        source: "earthquakes",
        filter: ["!has", "point_count"],
        layout: {
            "icon-image": "myImageName",
            "icon-size": 1,
            "icon-offset": [24, -43],
        }, 
    });
```
so on map it`s just a layer with unclustered markers witch i can click... but how i can get **user_id** after click on marker (for example in **console.log()** )?
```
[{ 
"type": "Feature",
"properties" { 
"scalerank":2,
"name":"scloud",
"user_id":"scloud",
"comment":1,
"name_alt":null,
"lat_y":46.4433297,
"long_x":30.7532281,
"region":null,"subregion":null,
"featureclass":null},
"geometry":{"type":"Point","coordinates":[30.7532281,46.4433297]}
}]
```

### Links to related documentation

https://www.mapbox.com/mapbox-gl-js/example/cluster/

**Comment by jfirebaugh** [comment]
Hi — thanks for using Mapbox. This repo is for reporting issues, requesting features, and coordinating work related to the various Mapbox Map SDKs. For help with “how do I” questions, please refer to our [help documentation](https://www.mapbox.com/help/), ask other users on [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox), or reach out to our excellent [support team](https://www.mapbox.com/contact/support/).
