### ISSUE TITLE
Coordinates in directions request isn`t same with response coordinates ...

### ISSUE THREAD

**Issue by Tahrz** [mapbox/mapbox-gl-js#7167]
**mapbox-gl-js version**: 0.47

**browser**: Chrome Version 68.0.3440.106 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Request URL 
``` 
https://api.mapbox.com/directions/v5/mapbox/walking/46.447820799999995,30.739660800000003;46.4778208,30.7396608?geometries=geojson&access_token={MyToken}
```

### Expected Behavior
Coordinates from request must be in response... 

### Actual Behavior
I get not my coordinates in response... so that`s why route draw in enother country...

Coordinates, which i send:
```
start = [46.447820799999995,30.739660800000003],
end = [46.4778208,30.7396608]
```
Coordinates in response
```
start = [46.447172,30.73663],
end = 46.476164,30.732026]
```

**Comment by jfirebaugh** [comment]
This isn't an issue with mapbox-gl-js, but I'll answer anyway: this is expected behavior, because the directions API snaps input coordinates to the nearest relevant road segment.

**Comment by Tahrz** [comment]
Funny. So... my markers with coordinates:
Screen #1: https://prnt.sc/klnxsk

And, how you said "API snaps input coordinates to the nearest relevant road segment"
Screen #2: https://prnt.sc/klnyzw

**So input coordinates in Odessa, Ukraine - output in Iraq ... API works without problems!***
