### ISSUE TITLE
Adding a WMS source via addLayer envelopes surrounding tiles with single background color

### ISSUE THREAD

**Issue by samfader** [mapbox/mapbox-gl-js#7188]
**mapbox-gl-js version**: 0.48.0

**browser**: Confirmed in Chrome, Safari

### Steps to Trigger Behavior

 1. Add WMS tiles via addLayer - or simply go to [this example](https://www.mapbox.com/mapbox-gl-js/example/wms/)
 2. You'll see tiles surrounding the WMS tiles don't look right - but zoom out and it gets worse. Eventually, the entire map div is white, except the WMS tiles.

### Link to Demonstration

https://www.mapbox.com/mapbox-gl-js/example/wms/
https://bl.ocks.org/samfader/raw/6cc79a707681af6f8c60172b3227b5ee/ (in this example, I added an `&BGCOLOR=0x000000` param to the WMS URL to demonstrate that in this case, the map is swallowed by black tiles and not white)

I'm not seeing any console errors specifically.

### Expected Behavior
The WMS tiles appear as expected in the map, but surrounding tiles are not taken over by a background color.

### Actual Behavior
As you zoom out, tiles surrounding the WMS tiles are enveloped by a single color, until the entire div (minus the WMS tiles) is one color.

**Comment by asheemmamoowala** [comment]
`BGCOLOR` changes the background color of the tiles served by the WMS server, but not their opacity. Use `transparent=false` as specified in the [WMS reference](http://docs.geoserver.org/latest/en/user/services/wms/reference.html#getmap)

**Comment by samfader** [comment]
@asheemmamoowala it looks like the _default_ is `transparent=false`, and setting `transparent=true` in the WMS URL is actually what needs to happen here. Thanks for pointing this out. Is [this](https://github.com/mapbox/mapbox-gl-js/blob/master/docs/pages/example/wms.html) the correct code that needs to be updated to fix this example?

**Comment by asheemmamoowala** [comment]
@samfader that is the correct example. While you are at it, could you please also fix it in this [debug page](https://github.com/mapbox/mapbox-gl-js/blob/master/debug/wms.html). 🙇

**Comment by samfader** [comment]
@asheemmamoowala mind reviewing real quick? https://github.com/mapbox/mapbox-gl-js/pull/7189
