### ISSUE TITLE
Diacritic marks on certain glyph letters incorrectly placed

### ISSUE THREAD

**Issue by ghost** [mapbox/mapbox-gl-js#7195]
**mapbox-gl-js version**: 0.48.0

**browser**: Electron 2.0.3/Chromium

### Expected Behavior

It should appear like below:

```
Sít' Eetí G̱eeyí <--- notice the i's
(Rendu Inlet)
```

### Actual Behavior

It appears like this:

<img width="248" alt="screen shot 2018-08-24 at 12 08 15 pm" src="https://user-images.githubusercontent.com/792055/44596017-cfebba00-a798-11e8-9414-97bb38cf8ecb.png">

This place is a native place in SE Alaska written out in one of the native languages of that area. Most but not all diacritic marks are coming through fine but the **i's** stand out.

**Comment by ikphilip** [comment]
I've also been able to reproduce this problem. Perhaps my demo might be illuminating.

I'm mostly interested in the Combining Macon Below (U+0331) and lower case g. My demo also has an example where a Combining Acute symbol is displayed incorrectly with a lower case i.

It would be useful for me to display the macron below the g without intercepting the descender. I am unsure why this occurs but it is isolated to the canvas rendering of the text.

https://jsfiddle.net/9L7opy1c/2/
