### ISSUE TITLE
Single finger pan events overlaps with multi touch pan

### ISSUE THREAD

**Issue by pakastin** [mapbox/mapbox-gl-js#7196]
There is no touch point count filtering in single finger pan. When you start multi touch pan there’s single and multi touch pan functions doing DOM updates simultaneously.

I noticed this when was fixing the multi touch center issue. Will debug more if there’s an easy fix. I’m not sure how the events should work in such case, so didn’t want to rush with a fix..

**Comment by pakastin** [comment]
Here's a good description how it affects the UX: https://github.com/mapbox/mapbox-gl-js/issues/6722#issuecomment-421928604

**Comment by jliebrand** [comment]
sub
