### ISSUE TITLE
is it possible to get feature properties and id that is outside viewport?

### ISSUE THREAD

**Issue by benydc** [mapbox/mapbox-gl-js#7198]
**mapbox-gl-js version**: 0.47.0

### Question
I have an issue where I have a feature selected, but map is zoomed in and if I move away from that feature, I cannot query for it anymore, since I can only query for rendered features on viewport. Is it possible to get query feature id and it's property using another method? I'm using the Mapbox Studio url, which already has the datasources in it.

**Comment by benydc** [comment]
I found a solution, at the beginning of the map I get a reference of all my features that I need info later:
`this.seatFeatures = this.map.queryRenderedFeatures(undefined, { layers: ['seats-layer'] });`

**Comment by dollysingh3192** [comment]
> I found a solution, at the beginning of the map I get a reference of all my features that I need info later:
> `this.seatFeatures = this.map.queryRenderedFeatures(undefined, { layers: ['seats-layer'] });`

Hi @benydc , 

I have a similar problem, where i want to filter feature's that are not in viewport, I made an ajax call to complete geojson i need. I have also posted the same on stackoverflow. 

https://stackoverflow.com/questions/61980850/filter-features-outside-the-viewport-in-mapbox

Can you please have a look and help me, if i am doing something wrong here?
Thank you in advance
