### ISSUE TITLE
New line in labels on polygons with Mapbox client

### ISSUE THREAD

**Issue by srmanc** [mapbox/mapbox-gl-js#7203]
I want to draw labels along lines / polygons in Mapbox.

I started designing the map in Maputnik, an open source tool. Here's what I got out of Maputnik and was quite happy with.

![image](https://user-images.githubusercontent.com/25658970/44663251-447c5e00-aa10-11e8-947b-1396e64a8302.png)

Then I moved the style to the mapbox client and to my surprise, the line breaks / new lines from the labels disappeared. Here's how:

https://i.stack.imgur.com/GTkKU.png
![image](https://user-images.githubusercontent.com/25658970/44663256-4a723f00-aa10-11e8-85d4-4a277b6a2d9e.png)

Upon further testing I found out that this only happens if I place labels on lines (placement = line). This also happens if I try and hardcode some dummy label anywhere in the sources (even in the JS/HTML part).

How can I achieve linebreaks along lines? Is this possibly a bug in the Mapbox client? I can post a jsfiddle if it helps.

**Comment by mourner** [comment]
This is likely a question to Maputnik developers, since it's displaying correctly in GL JS on the Maputnik side. Maybe something to do with how styles are exported, or a version mismatch.

If you can provide us with a minimal test case (e.g. using JSFiddle), I can reopen the issue.

**Comment by srmanc** [comment]
Here is the JSFiddle:
https://jsfiddle.net/srmanc/L6g07fmw/6/

And here is the (correct) render in Maputnik:
https://maputnik.github.io/editor/?style=https://gist.githubusercontent.com/srmanc/9d6e3c06591d93d9d3432ae01dfbcbe4/raw/e4383b7a8403305a5cb683e5390c1e82beb3bcb0/style.json#5.49/44.853/-67.81

If the upper link doesn't work, please go to maputnik.github.io/editor and load the style from here:

Style json (same as in JSFiddle):
https://gist.githubusercontent.com/srmanc/9d6e3c06591d93d9d3432ae01dfbcbe4/raw/e4383b7a8403305a5cb683e5390c1e82beb3bcb0/style.json

Geojson (same as in Style json, if needed):
https://gist.githubusercontent.com/srmanc/2d48dd35780e5995daa83d7a4e00b854/raw/296de1c6f7534eaf8933bcd6858d19128a26d4d8/polygon.geojson

I do not believe it is a version mismatch, I've tried a lot of combinations and none of them worked. I doubt that it is a style export issue, because I've tried to hardcode the style and geojson in JS - it didn't work either.

Any thoughts appreciated.

**Comment by mourner** [comment]
Thanks for the test cases! Might be a regression — will look into it.

**Comment by IvanVoevodin** [comment]
I have also encountered similar problem for multi-line labels of lines when symbol-placement is equal to line-center (it is not reproduced for symbol-placement=point). I believe it might be related?
Here’s the JSFiddle: https://jsfiddle.net/iv_vo/t53bg8sh/

**Comment by srmanc** [comment]
Workaround. This is what maputnik does:
https://jsfiddle.net/0vur8kqa/1/

If you set the RTL text plugin (setRTLTextPlugin, please see the new jsfiddle), new line works again.

**Comment by srmanc** [comment]
Any progress on this? Setting the RTL plugin opens up a different can of worms for us.
