### ISSUE TITLE
Get the information when mouse hover a 3D bar

### ISSUE THREAD

**Issue by camillalo** [mapbox/mapbox-gl-js#7217]
## Description
When i need to add some 3d bars in the map, how to get the information of these bars when the mouse hover on one bar ! 
I can't find some method to complete this operation!

**Comment by andrewharvey** [comment]
Do you mean #3122?

**Comment by jfirebaugh** [comment]
Sounds like a probable duplicate of #3122. @camillalo, in the future, when opening an issue, please fill out the provided issue template completely -- we need all this data in order to provide an answer.

**Comment by camillalo** [comment]
@Andrewharvey @jfirebaugh yes,it is. Thanks a lot
