### ISSUE TITLE
Fix #6828 break the flyTo end position in some cases

### ISSUE THREAD

**Issue by benoitbzl** [mapbox/mapbox-gl-js#7222]
**mapbox-gl-js version**: 0.48

**browser**: Chrome

### Steps to Trigger Behavior

At the end of animation, when final scale does not produce the correct zoom value, the zoom value is forced to the desired one (purpose of the fix #6828). But the scale value is not modified accordingly, so that the center computation goes wrong at 

https://github.com/mapbox/mapbox-gl-js/blob/8dd624d4e09f68d4a8739f1d140a983cae7e23e0/src/ui/camera.js#L970

The scale value does not match the one of the transform object, so the unproject() function produces wrong values.

**Comment by mourner** [comment]
Would you be open to submitting a PR for this?

**Comment by benoitbzl** [comment]
I am not sure yet how to compute the scale value based on the zoom value, but I will give it a try this afternoon.

**Comment by benoitbzl** [comment]
I submitted PR #7223.
