### ISSUE TITLE
dashed line is cropped and intervals are quite random sometimes

### ISSUE THREAD

**Issue by AntonPilyak** [mapbox/mapbox-gl-js#7226]
**mapbox-gl-js version**: 048.00

**browser**: Chrome

### Steps to Trigger Behavior

 1. try to draw a dashed line with line-dasharray
 2. zoom in and zoom out
 3. strange artifacts will appear, sometimes lines are cropped and have ugly skew endings even on relatively straight parts

### Link to Demonstration
https://jsfiddle.net/a_a_a_a/jndhoy7p/7/

![bug-line-dasharray](https://user-images.githubusercontent.com/35178096/44925052-82012400-ad4d-11e8-8949-46d38421d45a.png)

![bug-line-dasharray2](https://user-images.githubusercontent.com/35178096/44925080-9cd39880-ad4d-11e8-8bd3-32b0c96aae56.png)
![bug-line-dasharray-3](https://user-images.githubusercontent.com/35178096/44925362-88dc6680-ad4e-11e8-8837-d079506d8073.png)

**Comment by ryanhamley** [comment]
The clipping that you're seeing happens at tile boundaries and is being tracked here https://github.com/mapbox/mapbox-gl-js/issues/5395

The spacing issues are a little more unclear. Can you provide a minimal repro of the highway lane markers being spaced improperly? I'm guessing it may be related to https://github.com/mapbox/mapbox-gl-js/issues/5567, possibly in combination with tile boundary clipping, but without a demo, there's no way to tell.

**Comment by AntonPilyak** [comment]
Yes, will do it a bit later - it requires some time to make that kind of demo.
