### ISSUE TITLE
Initializing new Map

### ISSUE THREAD

**Issue by benydc** [mapbox/mapbox-gl-js#7227]
**mapbox-gl-js version**: 0.48.0

**browser**: Firefox

### Steps to Trigger Behavior

 1. import Map `import { Map, NavigationControl, Popup } from 'mapbox-gl';`
 2. I initialize the new Map with correct settings: this.map = new Map({ ... });
 3. I receive error on the console log about `Uncaught TypeError: Map is not a constructor`

I'm using Typescript.

### Link to Demonstration

https://jsbin.com/

### Expected Behavior
This has worked fine on 0.47.0 release, I don't understand what changed.

**Comment by mourner** [comment]
Can you provide a minimal test case to reproduce this behavior?

**Comment by benydc** [comment]
@mourner I'm not able to set the accessToken in the mini repo:
https://stackblitz.com/edit/angular-u8lgoz

The repo uses Angular 6 with Typescript.

**Comment by mourner** [comment]
@benydc can you make sure it's reproducible? I only see Angular errors unrelated to Mapbox:

![image](https://user-images.githubusercontent.com/25395/44984072-21a7f780-af84-11e8-832d-3f20cad2e8e0.png)

**Comment by benydc** [comment]
@mourner I got it working the dirty way, I was not able to add the mapbox-gl as library dependency to my project, because it was always failing with: `Trace warning: ../node_modules/mapbox-gl/dist/mapbox-gl.js has more than one anonymous define. May be a built file from another build system like, Ender. Skipping normalization.` I think it's because of the custom define function with worker for AMD. 

I then chose to include the library in the prepend section or aurelia bundle, as global dependency and removed the ```
export = mapboxgl;
export as namespace mapboxgl;
``` from type definition file. 

It will be great if someone has a solution on how to get this working the right way.

**Comment by mourner** [comment]
Unfortunately we can't help with an issue that doesn't have a clearly reproducible test case (which also indicates how it's a mapbox-gl-js issue). Let's close this for now and reopen if there's one.

**Comment by vidjuheffex** [comment]
I'm having the same issue

new mapboxgl..Map () 

map is not a contructor.

**Comment by pacocom** [comment]
Same problem for Angular Test:
component.ts
```
import { Map } from 'mapbox-gl';

@Component({
  selector: 'app-heatmap',
  templateUrl: './heatmap.component.html',
  styleUrls: ['./heatmap.component.scss'],
})
export class HeatmapComponent implements AfterViewInit {
  @ViewChild('mapEl', { static: true }) mapEl: ElementRef<HTMLDivElement>;
  @Input() data: HeatMapData;

  private map: Map;

  constructor() {}

  ngAfterViewInit(): void {
    this.map = new Map({
```



spec.ts
```
TypeError: mapbox_gl_1.Map is not a constructor

> 18 | const mockMap: Map = new Map();
     |                      ^
  19 |
  20 | describe('DownloadLocationComponent', () => {
```

**Comment by capan** [comment]
I'm having the same problem. 
My test file is below;

`import React from 'react';`
`import { render } from '@testing-library/react';`
`import 'jest-canvas-mock';`
`import App from './App';`

`jest.mock('mapbox-gl/dist/mapbox-gl', () => ({`
  `Map: () => ({}),`
`}));`
`test('renders learn react link', () => {`
  `const { getByText } = render(<App />);`
  `const linkElement = getByText(/learn react/i);`
  `expect(linkElement).toBeInTheDocument();`
`});`

I'm running npm test and I get the folowing error;

![image](https://user-images.githubusercontent.com/7265736/75258411-759d4080-57f7-11ea-8048-64cb6c258c3e.png)

**Comment by fahad9924** [comment]
Hello, I am facing the same problem. I am using Mapbox plugin in my Magento 2 Store but the map is not initializing.

The error says ,

`mapboxgl.Map is not a constructor` 

the code is 

require(['jquery','domReady!','https://api.mapbox.com/mapbox-gl-js/v1.2.0/mapbox-gl.js'], function($,mapboxgl) {
        	mapboxgl.accessToken = 'pk.eyJ1IjoiYXN0aXgiLCM3RuaW11MGFyNzNkb2lhMmdremZ1aSJ9._waO8n_06fDFbqW2hvVjKg';
            var map = new mapboxgl.Map({
            container: 'map', // container id
            style: 'mapbox://styles/mapbox/streets-v11', // stylesheet location
            center: [-74.5, 40], // starting position [lng, lat]
            zoom: 9 // starting zoom
            });
    });



Have any of you find a solution. It will be kind of you if you help me on this matter. 

Thanks.
