### ISSUE TITLE
stable symbol collision 

### ISSUE THREAD

**Issue by magicdawn** [mapbox/mapbox-gl-js#7229]
**mapbox-gl-js version**: 0.48.0

### Question

![mapbox](https://user-images.githubusercontent.com/4067115/44984503-8d538a00-afaf-11e8-9bf3-45291e141268.gif)

I'm using symbol layer config like this
```js
type: 'symbol',
layout: {
  'icon-size': 0.5,
  'icon-image': `some-icon-image`,
  'icon-padding': 15,
},
```

and using the default symbol collision strategy. When zoom increases, it feels like the icon is moving?
So I'm curoius about how mapbox decide which `Point` stay, which `Point` hide?
Is there a config to do a stable collision that behaves: when zoom increases, the shown symbol do not disappear, just show more and more symbols. 
`stable` means `the symbol` already shown stays when zoom increases.

I can not find too much about symbol collision with Google. so I'm asking here. Sorry.

**Comment by magicdawn** [comment]
For anyone who is also working on same problem, here is an user land solution:

- use `curList = initialFilter(fullList)` for initial render
- when map zoom increase, use `curList = filterMore(...)`
- when map zoom decrease, use `curList = filterLess(...)`

this depends on `map.project` & behaves not too slow when `fullList.length = 2000`

https://gist.github.com/magicdawn/2d27bba1f11fe222a8f0a6ba6b192535

**Comment by Tanguyabel** [comment]
@magicdawn thanks for opening this issue and providing your workaround. I encounter the same issue and would like to address it. I understand your filtering methods but what I didn't figure out is the way you are actually using your filtered lists in the end. Could you please elaborate or give a more complete example? That would be very helpful, many thanks in advance!
