### ISSUE TITLE
Accessing street line data

### ISSUE THREAD

**Issue by bnolan** [mapbox/mapbox-gl-js#723]
I'm trying to use a physics engine to constrain people so they can only walk around the city on visible roads. I can't see any way to get the street centerline data out of mapbox gl. Can someone give me pointers on where to start looking for the centerline data for streets? I'm happy to share a demo showing how to use the data or contribute to an API if people can give me some pointers. :)

**Comment by jfirebaugh** [comment]
Fixed with #1010.
