### ISSUE TITLE
uuid and validateUuid part of the public API?

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#7230]
@asheemmamoowala do you think the `uuid` and `validateUuid` methods from the user turnstyle should be `@private`? Right now they show up in the public API docs https://www.mapbox.com/mapbox-gl-js/api#uuid

**Comment by asheemmamoowala** [comment]
@andrewharvey those methods should be private. -> #7231

**Comment by mollymerp** [comment]
closed #7231
