### ISSUE TITLE
Composition of Layers is taking too long

### ISSUE THREAD

**Issue by maciekmp** [mapbox/mapbox-gl-js#7236]
Hello friends,

I have an app with around 1500 markers on it. One of the important moments in it is changing filters of markers after what we remove all markers from the map and add again. As you can see on the image below work on js side is pretty fast (I think I do almost everything I can to speed this part up). But in second half of operation (before we see update on the screen) we have big operation which is called "Composition of layers". As I know it is because of many layers of the map. Actually as you can see on second screen every map due use of css transition is separate layer which need to be merge with others on the end of render update process. 

I want to ask do you aware of this behavior and do you have any solution to speed this up beside of rendering to layers and similar solutions - I need html markers for this case.

<img width="1440" alt="zrzut ekranu 2018-09-5 o 14 19 17" src="https://user-images.githubusercontent.com/605659/45100606-0a0a7380-b12a-11e8-8dfc-cbde9612266a.png">

![zrzut ekranu 2018-09-5 o 16 33 20 2](https://user-images.githubusercontent.com/605659/45100737-43db7a00-b12a-11e8-81dc-5590df46a376.png)

**Comment by mourner** [comment]
Markers are DOM elements, the responsibility for their rendering lies on the browser and there's nothing we can do about its performance. If you have a lot of markers, we recommend using a GL symbol layer instead — it can render hundreds of thousands of points.

**Comment by maciekmp** [comment]
Thanks for fast response but I am pretty surprised that you close it so fast. 

Even if how layers are rendered lies on the browser side developers have impact when browser generates them. For example without transition we can omit creation of extra layers on the browser rendering engine side and maybe speed things up? 
For example google maps have a single layer.

**Comment by mourner** [comment]
The markers feature was added in addition to the symbol layer because it enables rich HTML content and CSS styling, but at the trade-off of using a separate DOM element for each marker, which doesn’t perform well with a lot of markers. Google Maps uses a Canvas layer to render markers — if you want an equivalent in GL JS, use a symbol layer.

**Comment by maciekmp** [comment]
Thanks! I just want to make clear that I was comparing to Google Maps API (not with Google Maps as service) and it looks like HTML element. I need those `rich HTML content and CSS styling` for big amount of markers and I am just trying to figure if any optimization is possible.

Thanks for help again
