### ISSUE TITLE
Polygon rendering is broken at big zoom levels

### ISSUE THREAD

**Issue by vehsakul** [mapbox/mapbox-gl-js#7237]
A simple `fill` layer with geojson data containing a triangle is not rendered properly at bigger zooms. You even have a [similar example](https://www.mapbox.com/mapbox-gl-js/example/geojson-polygon/) and it seems to work but the polygon is huge so it makes a little sense to zoom.
**mapbox-gl-js version**:
0.48.0
**browser**:
chrome, firefox
### Link to Demonstration
http://jsbin.com/quyipojafo/1/edit?html,output (insert your token)
### Expected Behavior
I should see a triangle
### Actual Behavior
I see a broken triangle

**Comment by mourner** [comment]
You forgot to close the polygon (which is required by GeoJSON spec). Adding another point equal to the first fixes the issue.

**Comment by vehsakul** [comment]
@mourner Thanks! My fault!
