### ISSUE TITLE
gl.texImage2D "Invalid argument" in IE 11

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#7241]
Many examples started failing in IE 11 after #7171 with an "Invalid argument" error here:

https://github.com/mapbox/mapbox-gl-js/blob/93fef1aea9b242c02203f71f86dd9e838adf1a84/src/render/texture.js#L73

Guessing here, but maybe IE 11 does not like `0` for width and height, which didn't happen before #7171 but now it is?

cc @mourner

**Comment by mourner** [comment]
It's a good hypothesis, although I'm not sure how exactly that happens — does IE11 provide a stack trace?
