### ISSUE TITLE
3d fill-extrusion-heights on iOS Safari are flat when height is over 65,536 meters

### ISSUE THREAD

**Issue by levelsio** [mapbox/mapbox-gl-js#7247]
- versionGlJs: 0.47.0 

Platform: Safari iOS (and also Android 3rd-party reports)

Example Link: https://nomadlist.com/3d

### Expected Behavior
Fill extrusion height is set from a features geoJSON dataset: 
'fill-extrusion-height': {type: 'identity', property: 'height'}, 

### Actual Behavior
fill-extrusion-heights in 3d ignore height on Safari iOS regardless of height value and all show as flat.

I think it's because I am showing fill-extrusion-heights on a world level, so they're quite big. And it's making some kind of integer overflow (65,536?) on iOS. I've seen Safari iOS handle integers differently before.

On any desktop browser like Safari MacOS and Chrome MacOS they show up properly as large bars.

How it looks on iOS:
![photo_2018-09-07_03-52-13](https://user-images.githubusercontent.com/7150848/45184549-6f0cb900-b251-11e8-9377-7c5c09933035.jpg)

How it should look (in Chrome desktop responsive mode): <img width="557" alt="screen shot 2018-09-07 at 03 51 41" src="https://user-images.githubusercontent.com/7150848/45184558-746a0380-b251-11e8-842d-ccdb6cd55d38.png">

And how it looks on Chrome desktop:
<img width="1055" alt="screen shot 2018-09-07 at 03 51 50" src="https://user-images.githubusercontent.com/7150848/45184557-73d16d00-b251-11e8-8e61-82cc53f00bb8.png">

**Comment by levelsio** [comment]
It seems to be reported before:
https://github.com/mapbox/mapbox-gl-js/issues/3954

"yes, fill-extrusion-height uses a Uint16 type, so the maximum possible value is 65535. At the moment we don't have plans to use bigger numbers as the increase in memory usage would be substantial for what seems to be a pretty limited use case — from what I've seen so far most use cases don't come near 65535 meters." by @lbud on 2017-01-13

It's stated the limit is removed:
https://github.com/mapbox/mapbox-gl-js/pull/5338

Is it though?

**Comment by jfirebaugh** [comment]
Duplicate of #7104.

**Comment by levelsio** [comment]
> Duplicate of #7104.

Sorry but this is wrong. It's a different issue. The examples in #7104 work fine on my iPhone 8 Plus in Safari iOS, but the fill-extrusion-height in my example works on no mobile devices at all, only desktop. 

Please re-open the issue, thanks!

**Comment by levelsio** [comment]
I've confirmed it's 65,536 height limit on mobile. So I think fill-extrusion-height is STILL defined as an Int16, as seen in https://github.com/mapbox/mapbox-gl-js/issues/3954. That issue was reportedly fixed and closed, but it's still Int16 on mobile somehow.

<img width="835" alt="screen shot 2018-09-12 at 15 12 18" src="https://user-images.githubusercontent.com/7150848/45411426-66c3dc00-b69e-11e8-9582-1a797edf1e83.png">

**Comment by ChrisLoer** [comment]
The issue was actually an (optionally) low-precision float rather than a Int16 vs Uint16 distinction, but this should be fixed with #7292 -- please give it a try! Although I don't see a way in which this is different from #7104, so maybe I'm missing something. At any rate, I was able to reproduce using an iPhone 8.
