### ISSUE TITLE
real-world iOS zooming chooses the wrong "center"

### ISSUE THREAD

**Issue by mike-marcacci** [mapbox/mapbox-gl-js#7255]
**mapbox-gl-js version**: v0.48.0

**browser**: Safari, iOS 11.4.1

### Steps to Trigger Behavior

 1. Open a map, such as [this one](https://www.mapbox.com/mapbox-gl-js/example/simple-map/)
 2. Zoom all the way out
 3. Try to zoom all the way into the southern tip of South America using two thumbs

### Link to Demonstration
https://www.mapbox.com/mapbox-gl-js/example/simple-map/

### Expected Behavior
The map should always zoom towards the intended point.

### Actual Behavior
The map frequently zooms towards incorrect points.

Below is a recording of me trying to zoom towards the "Alberto de Agostini National Park" label text in my iPhone. Sometimes it zooms where I want it, sometimes to the west, sometimes to the east.

![screenrecording_09-08-2018 19-23-56 2018-09-08 19_37_59](https://user-images.githubusercontent.com/690517/45260518-b6549000-b39e-11e8-9654-b0d2812a55d3.gif)

**Comment by ryanhamley** [comment]
Hi @mike-marcacci thanks for the report. This bug was fixed by https://github.com/mapbox/mapbox-gl-js/pull/7191 which will be included in v0.49.0 which should be released on Wednesday.

**Comment by mike-marcacci** [comment]
Ah, thanks! I totally missed that - must have only searched issues and not PRs. Cheers!
