### ISSUE TITLE
After run "yarn start-dev", show Error Tip with "path.."

### ISSUE THREAD

**Issue by zhaoyangsoft** [mapbox/mapbox-gl-js#7256]
**mapbox-gl-js version**:
0.48.0

**browser**:
chrome  65.0.3325.181
### Steps to Trigger Behavior

 1.  git clone ..
 2.  yarn 
 3.  yarn start-dev
 4.  show error tip  as  follow: 
![image](https://user-images.githubusercontent.com/1456421/45266019-47069b00-b487-11e8-96c9-ca9f266bdc3b.png)

**Comment by mourner** [comment]
What's your Node version?

**Comment by mourner** [comment]
Discovered that I'm getting this too on Node v10.10 — investigating...
