### ISSUE TITLE
Custom marker elements with CSS position property do not overlap

### ISSUE THREAD

**Issue by colinkahn** [mapbox/mapbox-gl-js#7258]
**mapbox-gl-js version**: 0.48.0

**browser**:

### Steps to Trigger Behavior

 1. Create a map and add a couple markers with the same lat/lng who either have an inline style or class that sets `position`.

### Link to Demonstration

https://www.mapbox.com/mapbox-gl-js/example/custom-marker-icons/

1. Edit the `geojson` so two markers overlap.
2. Add the line `el.style.position = "static";` or in the CSS `.marker` definition add `position: static;`.

### Expected Behavior

Markers should overlap regardless of the presence of the position property.

### Actual Behavior

Markers are forced to never overlap.

**Comment by jfirebaugh** [comment]
The `.mapboxgl-marker` element depends on absolute positioning for correct placement; you'll need to find an alternative to using static positioning. Perhaps you can apply the style to an inner element instead?

**Comment by colinkahn** [comment]
Hi @jfirebaugh, 

That sounds fine, and what I've done is wrapped my element in another unstyled div. What I think is necessary is to perhaps document this. Searching for 'overlap' regarding mapbox only brings up irrelevant topics.
