### ISSUE TITLE
Paused before potential out-of-memory crash.

### ISSUE THREAD

**Issue by pakastin** [mapbox/mapbox-gl-js#7266]
I don't have much other info about this, but happens very often:
![nayttokuva 2018-9-12 kello 11 52 13](https://user-images.githubusercontent.com/1475902/45413670-5f8ed500-b682-11e8-8035-7a2350153f2c.png)

Might have to do with updating sources with raw GeoJSON data (not from URL). Latest beta version, also happens with latest stable.

**Comment by pakastin** [comment]
Probably related to #5252

**Comment by manodupont** [comment]
@jfirebaugh Is there any limit written in the documentation ? I assume there is one  cause its happening here for me too. It only happens obviously on a bigger geojson file. So I am just wondering if there is any tweak or setting or conf on mapbox-gl that I can play with ?
