### ISSUE TITLE
Cannot read property 'equals' of undefined

### ISSUE THREAD

**Issue by xcxooxl** [mapbox/mapbox-gl-js#7269]
**mapbox-gl-js version**: 0.49.0-beta.1 /  0.48

**browser**: Chrome Version 69.0.3497.81 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Drag the map for the first time
 2. Then just move the mouse over the map

### Expected Behavior
move events, drag events etc should work.

### Actual Behavior
drag end event, pitchend, map move event, not working
most likely because of this exception

The exception happens in onMove method inside mapbox-gl
seems it happens at :
`this._lastPos.equals(n) || "pending" === this._state`

**Comment by behuda** [comment]
whats the solution to this issue

**Comment by AndrejB1** [comment]
Have we got a solution to this issue? It shouldn't be closed when no answer was provided.

**Comment by mourner** [comment]
@AndrejB1 if this is still an issue, can you provide a minimal live test case with the latest version of Mapbox GL JS?

**Comment by mourner** [comment]
Noting that the issue was closed by its author immediately after submitting it, not by maintainers of the project.

**Comment by AndrejB1** [comment]
@mourner, I have a live website where you can see it in effect yourself. Open the console. At first there should only be "unknown error" messages (I'm curious about them also). But to reproduce the error,  just tilt it around with the right mouse button for a bit, and then every time you move the mouse over the map, it will send an error.

www.mapfoundry.org

This is the html of mgl-map:

<mgl-map [style]="'mapbox://styles/andrejb1/cjsa49n2i35kf1fpabomawkgw'" [zoom]="[8]" [center]="[0,0]" (load)="map = $event"
    (zoomStart)="zoomStarted($event)">

**Comment by aweinmacher** [comment]
@AndrejB1 @mourner In our case this problem was most probably created by one of external scripts that added listeners to window events - we didn't manage to figure out the specific trigger, but removing all the window events magically solved the issue.

**Comment by AndrejB1** [comment]
@mourner @aweinmacher My 'solution' was different. I just upgraded the project from angular 5 to 7 and the problem disappeared. Might be a versioning issue then.
