### ISSUE TITLE
Cannot render base64 image in IE 11

### ISSUE THREAD

**Issue by bart-1990** [mapbox/mapbox-gl-js#7270]
**mapbox-gl-js version**: 0.48.0

**browser**: Internet Explorer 11

When I try to add a base64 image to the map it doesn't get rendered in Internet Explorer. In other browsers the image does show up. It's important that we can do this in all browsers as the images in our project are converted to base64 strings by webpack.

### Steps to Trigger Behavior

 1. Get a base64 string that represents a .png image.
 2. Load the base64 string in the map using the loadImage function (https://www.mapbox.com/mapbox-gl-js/api/#map#loadimage).
 3. Add the image to the map using the addImage function (https://www.mapbox.com/mapbox-gl-js/api/#map#addimage).
4. Use the image in a layer and add that layer to the map.

### Link to Demonstration

https://plnkr.co/edit/GHsMhNGf6UDBBKIpy3DN?p=preview

### Expected Behavior
The image should be rendered on the map.

### Actual Behavior
The image doesn't get rendered on the map.

**Comment by jfirebaugh** [comment]
Seems like IE11 is unable to handle an XHR request for that data URL. You can work around this by using `Image`: https://plnkr.co/edit/VhF3lNZlTEqdxJZwZGRV?p=preview.

**Comment by bart-1990** [comment]
Yes, this solves the problem. Ticket can be closed. Thanks for the help!

**Comment by mapcarta** [comment]
I'm curious why this ticket has been closed, as far as I know this bug still exists. Currently about 8% of our Mapbox GL JS loads use Internet Explorer. Would it make sense to update Mapbox GL JS with a bug fix such as follows?

image = document.createElement('img');
image.src = url;
image.onload = callback;

Note base64 images start with something like 'data:image/png;base64,'. I haven't checked if this bug applies to other image formats besides PNG.
