### ISSUE TITLE
Custom query parameter for style

### ISSUE THREAD

**Issue by cyrilchapon** [mapbox/mapbox-gl-js#7284]
Hey,

In here we're pluging our map to a custom source that comes from a custom server.

That's plugged like this :

```
sources: {
  ...,
  myCustomSource: {
    type: 'vector',
    url: 'https://the-server.com/s/tileserver/data/thestyle.json'
  }
}
```

The first query, (`GET https://the-server.com/s/tileserver/data/thestyle.json`) and each of the subsequent tile queries (`GET https://the-server.com/s/tileserver/data/124343.pbf`) needs an `apiKey` custom query parameter.

How to accomplish that ? (ie. declare a source in a way it appends the parameter to each query)

**Comment by ansis** [comment]
Hey, the [options.transformRequest](https://www.mapbox.com/mapbox-gl-js/api/#map) map option can be used to modify requests and add api keys. We still need to fix up the documentation for it ( issue https://github.com/mapbox/mapbox-gl-js/issues/6871) to make it easier to use. I think the first argument the callback receives is the url and it must return an object with this type: https://www.mapbox.com/mapbox-gl-js/api#requestparameters

**Comment by markusand** [comment]
Let's say we add a source to an already created map after a button has been pressed, and we need to add the api key at the same moment. Is there a way to set transformRequest after the map has been created?

**Comment by ryanhamley** [comment]
@markusand `map.transformRequest` has to be set during map construction. I think it's possible we could add a setter method for that, but I could imagine it being a little tricky. For example, if there are tiles being requested when the `transformRequest` is updated, should we cancel the in-progress tile loads and re-request them with the new function? If you want to request this as a feature, I'd say the best course of action is to open a new ticket specifically for this request and we can concentrate discussion there. Thanks!
