### ISSUE TITLE
QueryRendredFeatures behavior 

### ISSUE THREAD

**Issue by Pagnito** [mapbox/mapbox-gl-js#7285]
**mapbox-gl-js version**:

### Question

I noticed when i QueryRendredFeatures it rounds my id to a whole number. I need my ids to have floats, is there a way to avoid it rounding my id like that

**Comment by ryanhamley** [comment]
Hi @Pagnito The [spec](https://www.mapbox.com/vector-tiles/specification/) that Mapbox vector tiles implement requires positive integers for feature IDs so the library has to work within those parameters. Unfortunately, I don't think there's a workaround for using floats as feature IDs.
