### ISSUE TITLE
Style multiple features

### ISSUE THREAD

**Issue by Pagnito** [mapbox/mapbox-gl-js#7287]
**mapbox-gl-js version**:

### Question

I need to style multiple features on hover, each a different color according to their type. At the moment I am using [get, color] from properties and on hover im looping through the ids i need styled and using setFeatureState for each id. Wondering if there is a better way

**Comment by mourner** [comment]
You could also try doing this with `setFilter` — there's an example for that in the docs: https://www.mapbox.com/mapbox-gl-js/example/query-similar-features/
