### ISSUE TITLE
The app crash if you enter and exit constantly from the view containing the map

### ISSUE THREAD

**Issue by Losnen** [mapbox/mapbox-gl-js#7288]
**mapbox-gl-js version**: 0.49.0-beta.1 (npm)

**browser**: Movile app (iOS), developed with Ionic 3 + Angular 

### Steps to Trigger Behavior

 1.  enter and exit constantly from the view containing the map

### Link to Demonstration
Link to the video that reproduces the error

https://drive.google.com/file/d/1xRHHUm3TbQY4zu6P9QyzMQvolYiIN8lj/view?usp=sharing

### Expected Behavior

The app should not crash

### Actual Behavior

the app crash

**Comment by mourner** [comment]
Are you calling `map.destroy()` when exiting the map view? Can you reproduce this with a minimal test case (without third-party frameworks like Angular/Ionic) and share the link?

**Comment by Losnen** [comment]
> Are you calling `map.destroy()` when exiting the map view? Can you reproduce this with a minimal test case (without third-party frameworks like Angular/Ionic) and share the link?

Fix this with the function ```map.remove()``` when exiting the map view 

Thanks! @mourner

**Comment by mourner** [comment]
Great, thanks for the update!
