### ISSUE TITLE
can't add a new source immediately after initializing with a style URL

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#729]
```
var map = new mapboxgl.Map({
    container: 'map',
    style: 'https://www.mapbox.com/mapbox-gl-styles/styles/outdoors-v4.json',
    center: [-34.6, -58.4],
    zoom: 11
});

map.addSource('test', new mapboxgl.Source({
    type: 'vector',
    url: 'mapbox://mapbox.mapbox-streets-v6-dev'
}));
```

Uncaught TypeError: Cannot read property 'sources' of undefined [source.js:245](https://github.com/mapbox/mapbox-gl-js/blob/6030270968b6d4aa781f9ef315f2c5178e0e15f6/js/source/source.js#L245)

This occurs because the [map setStyle](https://github.com/mapbox/mapbox-gl-js/blob/6030270968b6d4aa781f9ef315f2c5178e0e15f6/js/ui/map.js#L68) happens asynchronously.

**Comment by NabeelSaleem333** [comment]
ERROR TypeError: Cannot read property 'addSource' of undefined
code:     this.map.on('load', function() {
      this.map.addSource('myImageSource', {
          type: 'image',
          url: 'https://www.mapbox.com/images/foo.png',
          // coordinates: [
          //     [70.425, 46.437],
          //     [75.516, 46.437],
          //     [76.516, 37.936],
          //     [80.425, 37.936]
          // ]
      });
      this.map.addLayer({
          id: 'overlay',
          source: 'myImageSource',
          type: 'raster',
          paint: {
          'raster-opacity': 0.85
          }
      });
    });
