### ISSUE TITLE
About examples - 'geojson-polygon'

### ISSUE THREAD

**Issue by Niumeng1** [mapbox/mapbox-gl-js#7293]
Hello.
There are problems with filling polygon. thanks

**Comment by Niumeng1** [comment]
There are no problems with multiple points,but 3 points or 4 points, there will be problems with map enlargement.

**Comment by mourner** [comment]
We have to close the issue since you haven't provided us with enough details to understand and diagnose it. The issue template you have to fill when submitting a bug report is there for this purpose.
