### ISSUE TITLE
Doc disambiguation for mouseover event

### ISSUE THREAD

**Issue by Fractaliste** [mapbox/mapbox-gl-js#7295]
Into [current documentation](https://www.mapbox.com/mapbox-gl-js/api/#map.event:mouseover) the mouseover event appears twice with different explanation:
![doc_error](https://user-images.githubusercontent.com/5181419/45760868-5c1fbe80-bc2b-11e8-8ce0-ba373cc2a05c.png)

The second one refers to mouseenter event which seems to be much more restricted than mouseover one's

**Comment by ryanhamley** [comment]
Thanks for the heads up! Closed by https://github.com/mapbox/mapbox-gl-js/pull/7299
