### ISSUE TITLE
About examples - 'geojson-polygon.html'

### ISSUE THREAD

**Issue by Niumeng1** [mapbox/mapbox-gl-js#7305]
**mapbox-gl-js version**: v0.49.0

**browser**: 69.0.3497.92

### Steps to Trigger Behavior

 1. 
When the map zoom is 8, there is no problem on the Polygon.
![image](https://user-images.githubusercontent.com/21193895/45790283-9f733f00-bcb6-11e8-8306-28582429eb61.png)

 2. When the map zoom is greater than 8, there is a problem on the Polygon.
![image](https://user-images.githubusercontent.com/21193895/45790345-f416ba00-bcb6-11e8-9cf2-1e4fdd03fc61.png)

 3. Data is 
![image](https://user-images.githubusercontent.com/21193895/45790482-a64e8180-bcb7-11e8-8141-fabdec5504bd.png)

**Comment by ryanhamley** [comment]
Hi @Niumeng1 you just need to close your polygon. In other words, the coordinates should be
```
'coordinates': [[
    [-67.1373435126877, 45.137451890638886],
    [-66.96466, 44.8096],
    [-68.03252, 44.3252],
    [-67.1373435126877, 45.137451890638886]
]]
```
