### ISSUE TITLE
Allow Custom Tool Tips

### ISSUE THREAD

**Issue by jjmacky** [mapbox/mapbox-gl-js#7306]
Custom tooltips were recently released in Power BI: https://docs.microsoft.com/en-us/power-bi/desktop-tooltips

It would be really useful if mapbox incorporated these. Right now I would love to show a tooltip with custom design and information when a user hovers over a particular county. Right now the county color is choropleth based on population, but having a tool tip show other useful information about the county on hover would be really cool (ex. male/female breakdown, median income, red vs. blue county, etc.).

**Comment by mourner** [comment]
This is already possible with the `Popup` class — see this example: https://www.mapbox.com/mapbox-gl-js/example/popup-on-hover/
