### ISSUE TITLE
Doc - strange link to Github sources

### ISSUE THREAD

**Issue by Fractaliste** [mapbox/mapbox-gl-js#7307]
Into current documentation there is some links toward Github sources (see in orange for instance):

![doc_error](https://user-images.githubusercontent.com/5181419/45802287-ba45b380-bcb6-11e8-8cfb-7e203b3708a9.png)

But these links are quite strange (and my browser show me some intrusion warning when I click them):

> https://**10952e7ac4d77658af99874a25bde51908441981@github.com**/mapbox/mapbox-gl-js/blob/403f54fe500d99b0fd05550fd47329457172e10a/src/ui/map.js#L228-L1773

**Comment by ryanhamley** [comment]
Interesting. The odd URL doesn't show up in Chrome, but does seem to be visible in Safari and Firefox (not sure about Edge/IE yet). Each browser seems to handle it a bit differently as well. I don't see the `alphanumerics@` part of the URL when testing the docs locally either even in browsers where it shows up in the production site.

**Comment by domlet** [comment]
Closing this issue because:
1. the layouts for pages on docs.mapbox.com have changed significantly since 2018 
2. links to items like `src/ui/map.js` on the current layouts appear as expected
