### ISSUE TITLE
how I can get my styles list of Studio?

### ISSUE THREAD

**Issue by luogeng2017** [mapbox/mapbox-gl-js#7308]
**mapbox-gl-js version**:

### Question

have any way to get my styles list of Studio?I want to get the styles list in my code.

**Comment by kkaefer** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by luogeng2017** [comment]
@kkaefer ok,but i can’t find this in the  help documentation,this(person  styles list) maybe a feature request.

**Comment by luogeng2017** [comment]
@andrewharvey I'm just seeing this,thank you
