### ISSUE TITLE
fill-extrusion layer  composite with linelayer  

### ISSUE THREAD

**Issue by tangjuncheng1986** [mapbox/mapbox-gl-js#7315]
Hello! Thanks for contributing.
    When linelayer is on the  top of fill-extrusion layer,when chang the pitch value ,the line will look offset . 
 
 
![image](https://user-images.githubusercontent.com/19219876/45857938-a620b580-bd8d-11e8-8700-1eaab7c21cd6.png)
![image](https://user-images.githubusercontent.com/19219876/45857950-b33da480-bd8d-11e8-9fc8-064f940326e0.png)

**Comment by tangjuncheng1986** [comment]
![image](https://user-images.githubusercontent.com/19219876/45858123-732af180-bd8e-11e8-940b-be5d6475c74d.png)
![image](https://user-images.githubusercontent.com/19219876/45858134-8047e080-bd8e-11e8-90eb-90a0e35a8fcf.png)

**Comment by indus** [comment]
I would guess that is normal. The line layer is on the base level (surface) of the map but the extrusion - to be precise the top of the extrusion - is on a higher level. On the - mostly hidden - bottom of the extrusion both layers matche up but not on the top. This is only noticible when you pitch the map - not when you look straight down on both layers. You can make the extrusion semi-transparent to get a better idea what is going on.

I think there is no way to elevate a line layer in the moment.

**Comment by mourner** [comment]
@indus thanks for chiming in and providing a correct answer! While we're still exploring ways to enable rendering lines on non-zero altitude, I'll close this issue as expected behavior.

**Comment by pathmapper** [comment]
> While we're still exploring ways to enable rendering lines on non-zero altitude

I'm also interested in this feature.
Is there an open issue somewhere or maybe reopen here to track it?

**Comment by ryanhamley** [comment]
@pathmapper check out https://github.com/mapbox/mapbox-gl-js/issues/3993
