### ISSUE TITLE
Some expression maths not working in IE11

### ISSUE THREAD

**Issue by ashleyclough** [mapbox/mapbox-gl-js#7318]
Version: 0.49.0
Internet Explorer 11

Some (complex) maths in expressions used to calculate circle-radius are failing in IE11 - circles appear small and fixed with no variation. Same code renders correctly in other browsers.

Both these fail:

```
"circle-radius": [
      "+",["*",["log2",["get", "point_count"]],12],10
]
```

Console reports: Object doesn't support property or method 'log2'

```
"circle-radius": [
       "+",["*",["sqrt",["get", "point_count"]],6],20
]
```

Have reverted to unsophisticated 'property' and 'stops' sizing from pre-expression days.

**Comment by mourner** [comment]
Good catch — submitted a fix in #7320.
