### ISSUE TITLE
How to use render-test to compare maps

### ISSUE THREAD

**Issue by dimitrilahaye** [mapbox/mapbox-gl-js#7328]
**mapbox-gl-js version**: 0.44.1

### Question

Hello !
I wonder how to write functionnal test with test-render from mapbox-gl.
I would like to launch test suite from command lines into Jenkins. Then I would like to generate a map in PNG format and compare it with an expected PNG.
Have you got, please, a tutorial or example?

**Comment by mourner** [comment]
The render test suite is not intended to be used externally — it's only for running core Mapbox GL tests during development, so we don't expose any related public API.

For an integration test, I'd suggest looking into using Google Puppeteer for launching headless Chrome and rendering a map, and then use https://github.com/mapbox/pixelmatch to compare screenshots.

**Comment by dimitrilahaye** [comment]
Thanks for the answer 👍
