### ISSUE TITLE
raster-resampling has no effect on raster tiles (eg. nearest neighbor is still blurry)

### ISSUE THREAD

**Issue by robhawkes** [mapbox/mapbox-gl-js#7331]
**mapbox-gl-js version**: v0.49.0

**browser**: Chrome 69.0.3497.92 (Windows 64bit)

### Steps to Trigger Behavior

 1. Set up a basic map instance with a raster tile layer
 2. Set the `raster-resampling` paint property of the raster tile layer to `nearest`
 3. Over-zoom map and notice blurry tiles

### Link to Demonstration

http://jsbin.com/nohuromeqa/1/edit?js,output

### Expected Behavior

According to [the documentation](https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-raster-raster-resampling), when setting the  `raster-resampling` paint property to `nearest` the raster tiles should have sharp pixels when over-zoomed.

> Nearest neighbor filtering interpolates pixel values using the nearest original source pixel creating a sharp but pixelated look when overscaled

Also, when changing the `raster-resampling` paint property to `linear` the results should appear different.

### Actual Behavior

When setting the `raster-resampling` paint property to `nearest` the raster tiles have blurry pixels when over-zoomed.

When changing the `raster-resampling` paint property to `linear` the results appear the same (blurry).

#### Over-zoomed in QGIS
![2018-09-25 08_48_02-_untitled project - qgis](https://user-images.githubusercontent.com/22612/46001375-07ed6200-c0a3-11e8-9cd6-47b896b13458.png)

#### Over-zoomed in Mapbox GL JS with `raster-resampling` set to `nearest`

![2018-09-25 08_49_18-mbtiles raster test](https://user-images.githubusercontent.com/22612/46001416-1c315f00-c0a3-11e8-969e-dd1c86ba758b.png)

#### Over-zoomed in Mapbox GL JS with `raster-resampling` set to `linear`

![2018-09-25 08_49_51-mbtiles raster test](https://user-images.githubusercontent.com/22612/46001419-1f2c4f80-c0a3-11e8-97be-92da2f8c0211.png)

#### Original tile

![174333](https://user-images.githubusercontent.com/22612/46001284-d379a600-c0a2-11e8-8360-c8f5ab2cdd09.png)

#### Over-zoomed in Mapbox GL JS with `raster-resampling` set to `nearest`

![2018-09-25 09_09_35-js bin - collaborative javascript debugging](https://user-images.githubusercontent.com/22612/46001309-e12f2b80-c0a2-11e8-8716-dc4e90894d63.png)

#### Over-zoomed in Photoshop (1000% increase in size)

![2018-09-25 09_02_27-174333 png 100 rgb_8 _](https://user-images.githubusercontent.com/22612/46001338-f310ce80-c0a2-11e8-9403-9577d77a13e9.png)

**Comment by mourner** [comment]
Interesting! Might be GPU-dependent? Here's how the example works for me on macOS:

![image](https://user-images.githubusercontent.com/25395/46019609-27a57a00-c0e5-11e8-8a87-2378ff3622a3.png)

Can you also try different browsers?

**Comment by robhawkes** [comment]
Ah good question, I hadn't checked other browsers and machines yet.

Here are the results of a few tests:

* Windows, NVIDIA GeForce GTX 1070
  * Firefox (62.0.2) looks blurry
  * Edge (42.17134.1.0) looks blurry
* Windows (Surface Book 2), NVIDIA GeForce GTX 1050
  * Chrome (69.0.3497.100) looks blurry
* MacOS (MacBook Pro Retina, 2012)
  * Chrome (69.0.3497.100) looks pixellated
* iOS (iPhone 8 Plus)
  * Chrome 69.03497.105 (iOS) looks pixellated

Looks like Windows vs. MacOS / iOS more than GPU. Are you able to replicate it on a Windows machine?

**Comment by robhawkes** [comment]
Me neither, I'll see if I can find a moment to have a look and poke around.

If it helps, the Three.js examples using a nearest mag filter work as expected (pixellated) on Windows: https://threejs.org/examples/webgl_materials_texture_filters.html

![image](https://user-images.githubusercontent.com/22612/46071737-997ad380-c178-11e8-8be1-7ad72a80bf4e.png)

**Comment by andrewharvey** [comment]
It's passing in the render tests which run on Linux, and I can't replicate this on my Linux machine either, so certainly it being a Windows specific issue sounds plausible.

**Comment by Scarysize** [comment]
I can also confirm this issue. I validated that both MIN & MAG texture filters are set to `NEAREST` using the WebGL Inspector Chrome Extension. This only happens on Windows, no issues on macOS:

![image](https://user-images.githubusercontent.com/10571630/49435016-e81a9e80-f7b5-11e8-91a2-82ce3d6098db.png)

Instead of blur, we get rainbowy edges, as we remap grey scale colors of the original tile image.

**Comment by Scarysize** [comment]
I did some digging, and from what I can gather, the problematic lines are here:

https://github.com/mapbox/mapbox-gl-js/blob/321a3695a6c068a1cfd58629ed9d8dcb333b8bbd/src/source/raster_tile_source.js#L129-L131

If commented out, everything looks fine on my side.

**Comment by SnailBones** [comment]
I'm hitting this while implementing https://github.com/mapbox/mapbox-gl-js/pull/12268, not only on Windows but also on MacOS VM. 

This issue can be fixed on Mac by using Chrome flag `--use-gl-desktop` as introduced in https://github.com/mapbox/mapbox-gl-js/pull/10389, however that causes a separate set of tests to fail with missing globe and inconsistent stars. (Same or similar test failures that led to https://github.com/mapbox/mapbox-gl-js/pull/12090)

<img width="1066" alt="windows-raster-resampling" src="https://user-images.githubusercontent.com/14878684/198734257-b603b103-c233-42f7-95cb-979d7d6786f1.png">

A likely related issue appearing In the same circumstances: icons appear to have incorrect resampling.
<img width="1084" alt="windows-icon-offset-literal" src="https://user-images.githubusercontent.com/14878684/198734262-3ca41011-cfc7-4b29-983d-41eed932e95f.png">

**Comment by michaelagal** [comment]
Has anyone found a solution to this issue? I've tried versions 1.6 and version 2.8 and in both cases "nearest" raster-resampling is not working on Windows. It works on Linux/iOS (including on Android).
