### ISSUE TITLE
Get bounding box of an airport

### ISSUE THREAD

**Issue by JohnDeved** [mapbox/mapbox-gl-js#7344]
I need the bounding box of an airport. i know you can get it for a city and places. but i dont see a way to get it from an airport. is it possible?

**Comment by mourner** [comment]
If you use a style based on Mapbox Streets v7, you can query `landuse` layer with `class = "industrial"` as per [this doc](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#landuse) — this way you can get a polygon of an airport area.

**Comment by JohnDeved** [comment]
thanks for your reply!
to clarify, you are saying i can use "queryRenderedFeatures" to get a polygon of an airport?
otherwise im not sure what you mean with query
