### ISSUE TITLE
Marker icon shifts when zooming while using marker offset

### ISSUE THREAD

**Issue by arkwis** [mapbox/mapbox-gl-js#7350]
**mapbox-gl-js version**: 0.49
**browser**: Chrome 69

### Link to Demonstration
https://jsfiddle.net/67swd01j/3/

When zooming in/out, the marker visibly shifts the location, instead of being tied to it's assigned geolocation. 

### Expected behavior
**(version 0.38)**
https://jsfiddle.net/8ktpq524/1/

**Comment by mourner** [comment]
As far as I remember, it works differently because anchor default changed. Now you can just do `new mapboxgl.Marker(el, {anchor: 'bottom'})` and it works correctly.

**Comment by arkwis** [comment]
Thanks for the reply, but I have already tried adding the `anchor` attribute and it did not solve the issue.

`var marker = new mapboxgl.Marker(el, {
    anchor: 'bottom',
    offset: [-30, -72]
  })
  .setLngLat([-79.969116, 40.427812])
  .addTo(map);`

**Comment by mourner** [comment]
@arkwis I mean, add the anchor attribute **instead** of `offset`. I just tried on your JSFiddle and it worked.

**Comment by arkwis** [comment]
@mourner Thanks again, did not realize adding an extra offset would re-introduce the issue. Appreciate your help.
