### ISSUE TITLE
Change z-index of a feature

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#7353]
I've created a separate stroke layer to display when a feature is clicked. It works mostly but when the feature (point) is behind another feature (point) it doesn't look very well:

GIF: https://imgur.com/pDm45TB

Is there a way to adjust the z-index of individual features?

**Comment by mourner** [comment]
Currently symbol features have a global ordering (see also #7076) — you may disable it with #7219, but this may have unintended consequences. The easiest workaround is probably putting highlighted feature on a different layer.

**Comment by bravecow** [comment]
Moving to new layers works well, but you can't use `setFeatureState` to style: https://www.mapbox.com/mapbox-gl-js/example/hover-styles/

98% style options (circle, fill and line rules) will be the same (except color maybe).

This way `setFeatureState` usable only for geojson source and small datasets, where you are able to reorder features on the fly 😏
