### ISSUE TITLE
Custom transform on marker icons

### ISSUE THREAD

**Issue by Pagnito** [mapbox/mapbox-gl-js#7356]
**mapbox-gl-js version**:

### Question
I need to load an image or icon from my folder. I initially used new Marker but css rotation doesnt seem to work on it. I looked into symbols but they don't seem to work with anything but outside url sources. Is there a way i can add an image from my folder and be able to manipulate it with css transforms?

**Comment by ryanhamley** [comment]
Hi @Pagnito this isn't currently possible. Internally, the marker class sets `translate` transformations to place the marker according to the anchor and screen position. Setting a CSS transformation directly on the marker element when it's created will therefore be overwritten and setting transforms with a CSS rule will either be ignored or break the marker's positioning, depending on the CSS specificity. It would be possible though to allow for additional transforms to be applied with some changes to the library and I think that would probably be pretty useful. I'm going to investigate this a bit. Thanks for bringing the issue up!

**Comment by Pagnito** [comment]
Sweet thanks...hopefully that can be a new feature

**Comment by ansis** [comment]
@Pagnito I think you could try putting the image within a div and applying your transform to the image. Our transform would get set on the outer div and wouldn't overwrite your transform.

>  I looked into symbols but they don't seem to work with anything but outside url sources. 

You can add images that can be used by symbol layers by using [map.addImage](https://www.mapbox.com/mapbox-gl-js/api/#map#addimage).
