### ISSUE TITLE
how to load custom tiles（base on EPSG:4326）？

### ISSUE THREAD

**Issue by szoyaung** [mapbox/mapbox-gl-js#7357]
Here's a arcgis server ， has tiled， and the EPSG is 4326, the tile origin is -400,400, what should i do to load this tile?
Here are some parameters：
Spatial Reference: 4326 
Tile Info:
Height: 256
Width: 256
DPI: 90
Levels of Detail: (# Levels 3)
Level ID: 0 [ Start Tile, End Tile ]
Resolution: 9.765664903423653E-4
Scale: 384764.063144
Level ID: 1 [ Start Tile, End Tile ]
Resolution: 4.882832451711827E-4
Scale: 192382.031572
Level ID: 2 [ Start Tile, End Tile ]
Resolution: 2.4414162258559134E-4
Scale: 96191.015786
Format: PNG32
Compression Quality: 0
Origin: X: -400.0
Y: 400.0
Spatial Reference: 4326
Initial Extent:
XMin: 116.40214190582036
YMin: 35.336725267533296
XMax: 116.67168724856081
YMax: 35.4897721994283
Spatial Reference: 4326 
Full Extent:
XMin: 115.858
YMin: 34.437
XMax: 117.614
YMax: 35.985
Spatial Reference: 4326 
Units: esriDecimalDegrees

**Comment by mollymerp** [comment]
Hi @szoyaung, thanks for using Mapbox. This issue tracker is for bug reports and feature requests. For "how to" questions like this, try posting on StackOverflow or contacting Mapbox support www.mapbox.com/help

**Comment by AManWithoutADream** [comment]
hello,bro.Have you solved it now?I also have this problem.

**Comment by aneeq-ur-rehman4** [comment]
Any solution to this?
