### ISSUE TITLE
MapBox Load Image Synchronously

### ISSUE THREAD

**Issue by rapicastillo** [mapbox/mapbox-gl-js#7360]
## Motivation

In general, would it be possible for us to have ways for asynchronous calls to be able to have sync versions / a sync option? Or at least have it return a promise?

For example, I think just having loadImage return a promise would be great.

**Comment by mollymerp** [comment]
Hi @rapicastillo, thanks for using Mapbox GL. If you have a feature request, please fill out the associated issue template and open a new issue.
