### ISSUE TITLE
Vector tiles not loading properly

### ISSUE THREAD

**Issue by Rajavelu** [mapbox/mapbox-gl-js#7370]
Hi,
Vector tiles not loading properly(refer attached gif), data rendered but tiles image not rendering(just blinking while drag).
There is no error in console. Any Idea about this issue?

User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

![macos_maps_issue](https://user-images.githubusercontent.com/3033600/46537582-466af400-c8cf-11e8-9db2-d139b34dabdc.gif)

**Comment by mourner** [comment]
You didn't provide all the information necessary for diagnosing it. Please fill out all the fields in the issue template, including a link to a minimal reproducing case.
