### ISSUE TITLE
Is it possible to use expression in setPaintProperty ?

### ISSUE THREAD

**Issue by Manopriya** [mapbox/mapbox-gl-js#7372]
Hi ,
I have created circles with different colors in single Layer with the help of expression. But I couldn't use the same in setPaintProperty. 

**mapbox-gl-js version**:v0.49.0

### Link to Demonstration

https://jsfiddle.net/s6k4nc73/
### Expected Behavior
       map.setPaintProperty("points","circle-color",
                     ['match',
                    ['get','idx'],
                    0,"black",
                    1,"blue",
                    2,"green",
                    3,"red"
       ] );
         
But throws error 
          

> Error: layers.points.paint.circle-color: Expected an even number of arguments.

### Actual Behavior

working fine in addLayer

         map.addLayer({
        "id": "points",
        "source": "pointsource",             
        "type": "circle",
        "paint": {
            'circle-radius':10,
            'circle-color': [
                    'match',
                    ['get', 'id'],
                    0, 'red',
                    1, 'blue',
                    2, 'green',
                    3, 'black',
                    /* other */ 'pink'

                ],
            'circle-stroke-width':1,
            'circle-stroke-color':'white'
        }
    });

**Comment by mourner** [comment]
You're seeing an expression error which says the number of arguments in the `match` expression is wrong. Looks like you forgot to add a fallback value (`addLayer` call has `pink` at the end, and `setPaintProperty` doesn't).

**Comment by Manopriya** [comment]
As you said , When I add the fallback value, all the circles are getting the fallback color. 
updated Js fiddle https://jsfiddle.net/s6k4nc73/2/
It didn't act according with the expression given. Am I thinking wrong ? kindly clarify me.

**Comment by mourner** [comment]
@Manopriya Here's a fixed version: https://jsfiddle.net/Mourner/s6k4nc73/9/

1. You had a typo (`idx` instead of `id`)
2. You put `setPaintProperty` outside of the `load` event handler.

**Comment by Manopriya** [comment]
> @Manopriya Here's a fixed version: https://jsfiddle.net/Mourner/s6k4nc73/9/
> 
>     1. You had a typo (`idx` instead of `id`)
> 
>     2. You put `setPaintProperty` outside of the `load` event handler.

Sorry for the typo error, Thanks for clarification
