### ISSUE TITLE
Add sdk-support entry for filter

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#7374]
## Motivation

The value for `filter` can be an expression but there [isn't an entry for `sdk-support` in the style spec](https://github.com/mapbox/mapbox-gl-js/blob/83aebca5e8266888ed457ae5f1d92b44ba493908/src/style-spec/reference/v8.json#L2169-L2173) for it. Studio uses this information for compatibility and evaluating if expression supported UIs should be present. Can we document the sdk-support information for filter expressions?

**Comment by ansis** [comment]
from talking:

Expressions are available in filters whenever they are available elsewhere. So far support for expressions in features hasn't been tracked with `sdk-support`. Studio should use the way it determines support for expressions in properties to determine support for expressions in filters.

I *think* this means we don't have to add a sdk-support key here unless we add it everywhere. Should we add `sdk-support` for [`"expression"`](https://github.com/mapbox/mapbox-gl-js/blob/244104e3cd0039e0d457845d77b034bc775c31c9/src/style-spec/reference/v8.json#L2308-L2312)?

**Comment by tristen** [comment]
> I think this means we don't have to add a sdk-support key here unless we add it everywhere. Should we add sdk-support for "expression"?

This happened with [`data-driven styling` version entries](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/reference/v8.json#L4989-L4994) but the same model wasn't applied for expressions. I can always account for this in my code, it just seemed odd at first there wasn't any compatibility data for filter values.

**Comment by mollymerp** [comment]
> Expressions are available in filters whenever they are available elsewhere. 

Is this true? I think it isn't, at least for gl-native. Filter expression support was added by Lucas after the initial PR: https://github.com/mapbox/mapbox-gl-native/pull/11251

**Comment by tristen** [comment]
I think I'm inclined to close this. There are [compatibility entries for each expression](https://github.com/mapbox/mapbox-gl-js/blob/b7307214d7b6593cb9b984b40e1b88833fc2c533/src/style-spec/reference/v8.json#L2015-L2859) and Studio should move off looking for this data from property names.
