### ISSUE TITLE
Label placement along line is weird

### ISSUE THREAD

**Issue by Xeenych** [mapbox/mapbox-gl-js#7375]
Label placement along lines is bugged.
When you set "text-max-angle" low, labels are not placed if line has sharp corners.
When you set "text-max-angle" high enough, symbols in one label collide with each other.
THis looks ugly.
![1](https://user-images.githubusercontent.com/11345848/46629495-b08ecd80-cb49-11e8-85bb-61995971deba.jpg)

The more the offset from original curve the more smooth should be the "guide" line for label placement
![2](https://user-images.githubusercontent.com/11345848/46629652-4f1b2e80-cb4a-11e8-9157-474af02ca89c.jpg)

**Comment by ansis** [comment]
Thanks for reporting! Since we're tracking this bug in https://github.com/mapbox/mapbox-gl-js/issues/3718 I'll close this issue.
