### ISSUE TITLE
Security Error on WebWorker Still Exist in IE11 Windows 7

### ISSUE THREAD

**Issue by thu07** [mapbox/mapbox-gl-js#7377]
I try to use mapbox-gl-draw in IE 11 Windows 7 OS. The running page is the example listed at https://bl.ocks.org/dnseminara/0790e53cef9867e848e716937727ab18. The Chrome and Firefox works great. However, the Security Error Problem in IE is still there. 

# The IE Version is the latest: 11.0.9600.18860
# Mapbox Version: v0.49.0
# mapbox-gl-draw Version: v1.0.9

Please help me to figure it out. Thanks.

**Comment by ryanhamley** [comment]
Hi @thu07 unfortunately, you haven't given us enough to determine what's happening. In the future, please fill out the fields in the issue template and provide a minimal reproduction of the bug if possible. That being said, there are known issues with certain versions of IE11. See https://github.com/mapbox/mapbox-gl-js/issues/3040 and https://github.com/mapbox/mapbox-gl-js/issues/4623 especially this comment https://github.com/mapbox/mapbox-gl-js/issues/4623#issuecomment-328584165. Microsoft released a patch to fix this issue in Edge but not for IE11. It's likely that this is an IE bug which we can't address.

**Comment by thu07** [comment]
Hi @ryanhamley  Thank you so much for your response. The error I met is SCRIPT5022: SecurityError. When I trace into the code, the problem is in web_worker.js file and the line is "return (new window.Worker(workerURL)     );"

The problem is similar with   [https://github.com/mapbox/mapbox-gl-js/issues/6384](url). However, it still can not be resolved.

**Comment by ryanhamley** [comment]
Yep, see this comment https://github.com/mapbox/mapbox-gl-js/issues/3040#issuecomment-256493151 Some versions of IE11 unfortunately have a bug in the way they handle web workers, which are essential to the Mapbox GL JS library. This bug is known by Microsoft but they've chosen not to patch it on IE11. I'm sad to say that I don't think there's any way for us to handle this on our end.

**Comment by thu07** [comment]
Got it. Thank you so much for your help.
