### ISSUE TITLE
Hot swapping access tokens in mapboxgl - Event when token has become invalid.

### ISSUE THREAD

**Issue by icyJoseph** [mapbox/mapbox-gl-js#7378]
**mapbox-gl-js version**:

### Question

Hi,

I have a setup on which, when the user access my content, a temporary token is generated. 

This token's last for one hour.

What I need to know is if there is any event I can listen to for invalid token, which I could use to trigger a refresh.
 

BR,

J

**Comment by ansis** [comment]
Invalid tokens trigger errors which you can listen to with `map.on('error', function(err) { ... })`. Look for a `AJAXError` with a `401` status code!
