### ISSUE TITLE
Dragging a marker out of the map

### ISSUE THREAD

**Issue by iang0ld** [mapbox/mapbox-gl-js#7380]
## Motivation

I want to have a map and scheduling component on the same page. I then want to plot a series of markers on the page and be able to drag a marker for the map onto the schedule control, hopefully with standard HTML 5 drag and drop and include some information like an address id so that the schedule can create an appointment using the information from the map.

**Comment by ryanhamley** [comment]
Hi @iang0ld this isn't likely something that we'd build support for. Drag and drop functionality isn't available in some browsers we support and this is a pretty specific use case. You may be able to extend the library yourself to meet your needs or you could use click events to handle populating the schedule from the map.
