### ISSUE TITLE
Does layer type "fill" support polygons with holes?

### ISSUE THREAD

**Issue by Xeenych** [mapbox/mapbox-gl-js#7385]
**mapbox-gl-js version**:
0.49.0
**browser**:
Chrome  69.0.3497.100 (64 бит)
### Question
Does layer type "fill" support polygons with holes?

I'm trying to laod GLIMS database to MapBox. There shoul be polygons with holes? but "fill" is rendered twice on top of holes.

**Comment by ansis** [comment]
Yes, we support polygons with holes! If you think there might be a bug can you please provide a reproducible example of this so that we can look into it? The "Bug report" new issue template has all the things we need to follow up on bug reports.

**Comment by Xeenych** [comment]
This is the polygon with a hole I'm truing to display.
[tmp2.zip](https://github.com/mapbox/mapbox-gl-js/files/2464569/tmp2.zip)

This polygon in QGIS
![test](https://user-images.githubusercontent.com/11345848/46735621-691a5580-cc9f-11e8-9474-691fdabaaaf0.jpg)

This polygon in MapBox
![test2](https://user-images.githubusercontent.com/11345848/46735777-e1811680-cc9f-11e8-8499-b509db3b6b28.jpg)
