### ISSUE TITLE
Cannot apply zoom formula to data conditions

### ISSUE THREAD

**Issue by neverwiredhouse** [mapbox/mapbox-gl-js#7386]
**mapbox-gl-js version**:
0.45.0

**browser**:
chrome

### Steps to Trigger Behavior

 1. choose a layer (country_label is what I used) whose data type is "Symbol" for text.
 2.  click on the "size" option
 3. (ensure all places are accessible, no filter)
 4. at the bottom change the "code" and add this:

```
[
  "match",
  ["get", "scalerank"],
  1,
  [
    "interpolate",
    ["linear"],
    ["zoom"],
    1,
    10,
    6,
    24
  ],
  2,
  [
    "interpolate",
    ["linear"],
    ["zoom"],
    3,
    10,
    8,
    24
  ],
  10
]
```

### Expected Behavior
The size will change at different zooms for individual matches. The assumption is that you can apply a _formula_ to each **data condition**

### Actual Behavior
I get an error, "Invalid GL JSON" and the sizes don't change. :(

**Comment by ansis** [comment]
Due to implementation challenges we only allow `interpolate` expressions that use `["zoom"]` to be used as outer expressions. Unfortunately they can't be used as inputs into other expressions. In your case you would need to move the `["match", ...]` into the `interpolate` expression:

```
[
    "interpolate",
    ["linear"],
    ["zoom"],
    1,
    [
        "match",
        ["get", "scalerank"],
        1, 10,
        2, ???
    ],
    6,
    [
        "match",
        ["get", "scalerank"],
        1, 24,
        2, ???
    ],
]
```
