### ISSUE TITLE
Zoom stop functions permit `literal` expressions, which trigger font API 404 status code

### ISSUE THREAD

**Issue by emilymdubois** [mapbox/mapbox-gl-js#7387]
**mapbox-gl-js version**: 0.46.0

**browser**: Google Chrome v69.0.3497.100

### Steps to Trigger Behavior

1. Create a stylesheet with a zoom stop function containing literal expressions (see snippet below).
1. Observe that stylesheet passes validation.
1. Zoom into/out of the map so that the zoom stops are breached.
1. Observe API error in console with format `https://api.mapbox.com/fonts/v1/{username}/literal,{encoded_fonts}/{range}.pbf?access_token={token}`. It looks like the `literal` expression reference is making its way into the font request.

```js
{
  "base": 1,
  "stops": [
    [
      6,
      [
        "literal",
        [
          "Open Sans Regular",
          "Arial Unicode MS Regular"
        ]
      ]
    ],
    [
      7,
      [
        "literal",
        [
          "Open Sans Bold",
          "Arial Unicode MS Regular"
        ]
      ]
    ]
  ]
}
```

### Link to Demonstration

1. Click on [this style link](https://api.mapbox.com/styles/v1/emilymdubois-1/cjn1tbzdo5qtn2rpccyy7atu3.html?fresh=true&title=true&access_token=pk.eyJ1IjoiZW1pbHltZHVib2lzLTEiLCJhIjoiY2piZmF1YjltMnVvYjJ3bXIzbzUzaWpmZCJ9.3rcEI0saBslzhRjCpXzzlA#1.61/0/0).
1. Observe font API error in browser network console.

### Expected Behavior

The `literal` expression reference should be removed before making the font API request.

### Actual Behavior

The font API request contains the `literal` expression reference.

**Comment by ansis** [comment]
It looks like your example is mixing the the old data-driven functions `{ base: 1, stops: [...]}` with new expressions `["literal", ...]`. We support mixing the within styles, but not within individual style properties.

I think you could rewrite it to use either just the old style, or, preferably the new. I haven't tested these examples so I could be adding some other bug:

Old:

```
{
  "base": 1,
  "stops": [
    [
      6,
      [
        "Open Sans Regular",
        "Arial Unicode MS Regular"
      ]
    ],
    [
      7,
      [
        "Open Sans Bold",
        "Arial Unicode MS Regular"
      ]
    ]
  ]
}
```

New (using [step expressions](https://www.mapbox.com/mapbox-gl-js/style-spec#expressions-step)):

```
["step",
    ["zoom"],
    ["literal", ["Open Sans Regular", "Arial Unicode MS Regular"],
    7, ["literal", ["Open Sans Bold", "Arial Unicode MS Regular"]]
]
```

Did you write your expression in Studio? Did studio provide any sort of validation. I'm wondering what we can do to help people avoid this issue.

**Comment by emilymdubois** [comment]
> Did you write your expression in Studio?

Yes. We've patched a fix that makes this difficult to do in the UI, but the JSON editor is pretty fair game.

> Did studio provide any sort of validation.

Yes, we validate property values configured in the JSON editor using the mapbox-gl-js [validate_property](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/validate/validate_property.js) script. However, you can see that it's not catching this error:

<img width="30%" alt="screen shot 2018-10-09 at 1 04 19 pm" src="https://user-images.githubusercontent.com/6913048/46688791-e1134d80-cbc3-11e8-83f4-16cba08cb8d6.png">

I can implement a catch in Studio, but if I'm accurate in thinking the validate_property script should throw an error on this, I can submit the pull request into this repo directly.
