### ISSUE TITLE
"Default" option for new expressions

### ISSUE THREAD

**Issue by stdmn** [mapbox/mapbox-gl-js#7389]
**mapbox-gl-js version**: 0.49.0
### Question

I've been using complex expressions to style large geo-datasets. Because the datasets are so large, there are a number of null or undefined values. I can use the "default" field of the deprecated function expression, but as far as I can tell, there is no way to use a "case" expression in the values for the function expression (**from documentation:** "_Stop output values must be literal values (i.e. not functions or expressions)_"). 

This means I have to choose between using a "case" expression (which I use for hover feature states) and having a "default" to catch for non-numeric or non-string data. Even when I try to force to a number or string using "to-number" or "to-string," the data still cannot be evaluated.

I may be missing something, but it doesn't seem to be possible to use a default value with "case."

### Links to related documentation

[CodePen here](https://codepen.io/bms711/pen/oaZLRy/)

Example of function expression with [default](https://www.mapbox.com/mapbox-gl-js/style-spec#function-default):
```
'circle-radius': {
        property: keyAttribute,
        base: exponent,
        stops: [
          [{ zoom: 8, value: 5 }, 1],  <---- using a "case" expression here doesn't work
          [{ zoom: 8, value: 100 }, 20],
          [{ zoom: 16, value: 5 }, 20],
          [{ zoom: 16, value: 100 }, 400]
        ],
        default: 0
      }
```

Example "case" expression:
```
 'circle-radius':   ['case', 
         ['<', ["to-number", ["get", "size"]], 0], <---- doesn't catch null/undefined
         0,
         ['interpolate',['linear'], 
         ['get','size'], 0, 0, 8, 10]],
```

**Comment by ansis** [comment]
[[to-number, maybeNumber, fallback]](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-types-to-number) accepts a fallback value as a third argument that is used when the conversion fails. `false` and `null` are automatically converted to `0`.

You might also be interested in [`["number", ...]`](https://www.mapbox.com/mapbox-gl-js/style-spec#expressions-types-number) which is similar but does not automatically convert `false` and `null` to 0.

I think changing `'<'` to `'<='` fixes your example.

But I think it could also be simplified to just
```
"circle-radius": ['interpolate', ['linear'], ['number', ['get', 'size'], 0], 0, 0, 8, 10],
```

For these kinds of questions please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
