### ISSUE TITLE
Document lat/lng

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#739]
So @duncangraham lost a bunch of time on this one: there's the same mismatch between lat/lon API and lon/lat data as in Leaflet. We mention this in the docs pretty simply, but maybe it's something that should be either covered in a dedicated section or mentioned earlier, like [in the first map example](https://www.mapbox.com/mapbox-gl-js/api/#new-mapboxgl-map-options-).

**Comment by jfirebaugh** [comment]
[We're switching to lon, lat](https://github.com/mapbox/mapbox-gl-js/pull/1433) to match GeoJSON and avoid that particular kind of mismatch. But this should still be documented.
