### ISSUE TITLE
Zoom is off center on touch devices when importing mapbox-gl through node_module

### ISSUE THREAD

**Issue by Mindcraft1** [mapbox/mapbox-gl-js#7397]
**mapbox-gl-js version**: 0.49.0

**browser**: 

Chrome Android
Chrome IOS (Iphone 8, iphone7)

Did not test other browsers

### Steps to Trigger Behavior

1. Place your fingers around the intended target to initiate zoom
2. Expand your fingers in a pinch & zooming gesture
3. Observe target moves away from the center of your fingers

### Link to Demonstration

I created a small [repo](https://github.com/Mindcraft1/mapbox_zoom_bug_showcase) reproducing the issue

### Expected Behavior

Target should stay in center (between fingers) during zooming.

### Actual Behavior

Target moves off center as the user zooms into it.

**Comment by ryanhamley** [comment]
I was unable to reproduce the behavior in Chrome on an iPhone X or an HTC One using your repo. If you can create a gif of what you're seeing, that might be helpful, but honestly I can't think of any reason this wouldn't be working just because it was installed with npm.

**Comment by Mindcraft1** [comment]
Hi @ryanhamley, I created a GIF from Chrome on my Samsung Galaxy S8 trying to Zoom on the Arc de Triomphe.

![zoom_optimized](https://user-images.githubusercontent.com/6388208/46854323-c8dc4200-ce00-11e8-9104-99f94b0781f4.gif)

**Comment by brambow** [comment]
I'm having a similar problem on a non-mobile device. Zooming always moves to left of center. Latest version of GL library.

![mapboxzoom](https://user-images.githubusercontent.com/6227786/49300707-e046bb80-f490-11e8-9398-39a7e5ddc633.gif)

I don't really think this is a Mapbox bug because I have some other projects where it's working, but I'm wondering if it's possible that some CSS elsewhere in my project could be affecting what the map thinks is the center?

**Comment by underbluewaters** [comment]
I'm also seeing this issue with flexbox layout. The map is set to 100% width but the height is variable. Zoom using a mouse on chrome is off-center in the y dimension.

**Comment by mryellow** [comment]
> after the container is resized you need to call [map.resize()](https://www.mapbox.com/mapbox-gl-js/api/#map#resize). If the change is a result of the window resizing

This can be the case for many kinds of styling of containers. The "resize" can be CSS loading rather than the actual window changing sizes at all.
