### ISSUE TITLE
"canonicalize" tile urls from TileJSON so they use config.API_URL

### ISSUE THREAD

**Issue by mollymerp** [mapbox/mapbox-gl-js#7400]
gl-native has a step where it converts mapbox.com tile urls to use the mapbox:// prefix so that they ultimately fire requests at the `baseApiUrl` domain. we should add behavior in mapbox-gl-js as well, I think.

```cpp
// Return a "mapbox://tiles/..." URL (suitable for normalizeTileURL) for the given Mapbox tile URL.
std::string canonicalizeTileURL(const std::string& url, style::SourceType, uint16_t tileSize);
```
https://github.com/mapbox/mapbox-gl-native/blob/f3341dd589c6330c0cfd6e8e381398d08493b48a/src/mbgl/util/mapbox.hpp#L21-L22

we should also consider adding a setter/getter for API_URL (native exposes these functions [here](https://github.com/mapbox/mapbox-gl-native/blob/d4f41364140cc37820f9a9bbff58e5e124097469/include/mbgl/storage/default_file_source.hpp#L45-L46))

**Comment by kkaefer** [comment]
Hm, the main reason this function exists in Native is for caching: the TileJSON endpoints from `api.mapbox.com` serve tile template URLs (in the `tiles` key) that are resolved to real HTTP URLs. For caching, however, we're canonicalizing them to `mapbox://` so that we don't cache `a.tiles.mapbox.com` and `b.tiles.mapbox.com` twice even though they serve the same resource. They also contain access token which we're stripping for cache lookups so that we don't have a per-access token cache.

**Comment by kkaefer** [comment]
sorry, rereading the title of this issue and it's exactly what we use it for 😅

**Comment by mollymerp** [comment]
@kkaefer good to know about the caching behavior. fwiw I took a closer look at the native codebase, and confirmed that native isn't making requests to the `{a/b}.tiles.mapbox.com` endpoints – tile URLs are normalized to `"https://api.mapbox.com/v4/tileset.id/z/x/y.vector.pbf"` using the baseURL. Making this change in JS would change existing behavior, but I'm not sure it would count as a breaking change.

**Comment by kkaefer** [comment]
Yeah good point. Mapbox TileJSONs return a `tiles` array with
`[ "http://a.tiles.mapbox.com/v4/...", "http://b.tiles.mapbox.com/v4/..." ]`. On Native, we resolve that back to a `mapbox://` URL for the reasons stated above. The reason we have two different tile URLs here is to increase the number of simultaneous connections: Many browsers (used to?) limit the number of simultaneous connections per hostname to something between 2 and 6. We should revisit this now that we are using the [Fetch API](https://github.com/mapbox/mapbox-gl-js/pull/7371).

Apart from the number of simultaneous connections, another consideration is also DNS resolution: We're typically loading a style from `api.mapbox.com`, then tiles from `*.tiles.mapbox.com`. We're also doing a request to `api.tiles.mapbox.com`. This means that we're doing at least 4 DNS queries when loading a map. Reducing those to 1-2 might be worth the concurrency penalty if it still exists.

**Comment by mollymerp** [comment]
according to [the internet](https://developer.pushtechnology.com/cloud/latest/manual/html/designguide/solution/support/connection_limitations.html) the minimum limit for browsers we support is 6 🤔

<img width="337" alt="image" src="https://user-images.githubusercontent.com/2425307/46996668-56a28080-d0d2-11e8-8a95-08e80c8c1aff.png">

I can run some benchmarks on various browsers to see if this change would affect network request performance.
