### ISSUE TITLE
custom layers example broken in IE and Edge

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#7406]
The custom layers example is not working on IE on some devices. Edge crashes at least on some devices. @kkaefer

**Comment by ansis** [comment]
The first error was caused by `"hash": true` triggering a SecurityError in IE (possibly only within a iframe). https://github.com/mapbox/mapbox-gl-js/pull/7408 avoids it. I still need to open an issue so that we can fix this properly but it's not a new issue and doesn't need to block the release.

Even after this is fixed the custom layer sometimes fails to show up in IE. This is just the long-standing https://github.com/mapbox/mapbox-gl-js/issues/4623 issue. It's pretty serious but it shouldn't block the release because it has existed for a long time and because it is not a simple fix.

I spent a day looking into the IE issue. The short summary is: there is an IE browser bug that sometimes drops messages sent to workers. This is a known bug and will not be fixed in IE. If we want to fix this in IE we need to treat communication to works as unreliable. This would add significant complexity.

The IE issue is pretty serious on it's own, but the fact that it prevents the `load` event from being fired makes it break examples like this one. A public `style.load` event would work around this issue and would also let developers make modifications to the map earlier.

**Comment by kkaefer** [comment]
I'm still having trouble getting the custom layers example to work correctly on MS Edge. IE and Chrome work fine on the machine I'm using, but Edge crashes with:

```
Fault bucket 1474035799637301183, type 5
Event Name: MoAppCrash
Response: Not available
Cab Id: 0

Problem signature:
P1: Microsoft.MicrosoftEdge_42.17134.1.0_neutral__8wekyb3d8bbwe
P2: praid:ContentProcess
P3: 11.0.17134.48
P4: 5ae3f17b
P5: ntdll.dll
P6: 10.0.17134.254
P7: a5a334d4
P8: c0000008
P9: 000000000009dcda
P10: 
```

The function call that triggers the crash is the `gl.linkProgram()` call. I added extensive error checking support to this example with `gl.getError()` and checking for shader compile and program link status with `gl.getShaderParameter()`, but they don't report any faults.

**Comment by kkaefer** [comment]
Further debugging showed that MS Edge crashes when using `gl_PointSize` on this machine (just the presence is enough, regardless of the value). This bug is captured in https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4468541/ but still unresolved. The JSFiddle linked there also crashes on the machine I'm using.

I submitted a PR that removes `gl_PointSize` in https://github.com/mapbox/mapbox-gl-js/pull/7413
