### ISSUE TITLE
How to package the source codes into a file?

### ISSUE THREAD

**Issue by flyiiiiii** [mapbox/mapbox-gl-js#7417]
IIdownload the source codes of mapbox-gl and add some codes.How could I package them to one js file?

**Comment by ansis** [comment]
Thanks for your interest. [CONTRIBUTING.md](https://github.com/mapbox/mapbox-gl-js/blob/master/CONTRIBUTING.md) contains all the information on building from source.

**Comment by flyiiiiii** [comment]
Thank you.I succeed!
