### ISSUE TITLE
Ability to play flv file

### ISSUE THREAD

**Issue by kamakshidasan** [mapbox/mapbox-gl-js#7423]
## Motivation

Currently, Mapbox only supports webm + mp4 files to be played on the map. It would nice if other formats could be supported: I have a live stream as a FLV file, that I would like to show on top of a map. 

If there is a workaround, do let me know! :)

**Comment by kkaefer** [comment]
Mapbox GL depends on browser support to decode videos and doesn't implement its own webm/mp4 decoding. This means that we can't add flv video support.

You could try using https://github.com/Bilibili/flv.js to transmux the FLV stream to MP4 segments and feed that into the `<video>` container, then add that one to the map. That project also claims support for FLV live streams. Please note that we don't support or endorse this plugin.
