### ISSUE TITLE
Add getElement method to Popup (like Marker)

### ISSUE THREAD

**Issue by cantacell** [mapbox/mapbox-gl-js#7425]
Adding a getElement method (like Marker or Leaflet Popup) on Popup gives the possibility to change dynamically the css className.
Regards,
Francesco

**Comment by DeusVultSVK** [comment]
CAN I work on this issue?

**Comment by ryanhamley** [comment]
@DeusVultSVK yep, see our contributor's guide https://github.com/mapbox/mapbox-gl-js/blob/master/CONTRIBUTING.md

**Comment by mollymerp** [comment]
@DeusVultSVK Thank you! Let us know if you have questions or need help implementing this feature.

**Comment by andrewharvey** [comment]
This was done in #8123

**Comment by shubhuhidev** [comment]
Popup.getElement() method giving undefined

**Comment by RicardoTactiql** [comment]
@shubhuhidev If the marker is closed it gives undefined. 

Is there a solution to that?
