### ISSUE TITLE
Text doesn't follow rotation of map

### ISSUE THREAD

**Issue by donnyv** [mapbox/mapbox-gl-js#7429]
I've set the initial rotation of all the text labels.
![image](https://user-images.githubusercontent.com/2224189/47047815-b480a800-d166-11e8-9580-cc43a8ac5fc4.png)

But when I rotate the map. The text doesn't follow the rotation of the map. What am I doing wrong?
![image](https://user-images.githubusercontent.com/2224189/47047857-d11ce000-d166-11e8-9ed6-e5d4a9297c5e.png)

**Comment by mollymerp** [comment]
@donnyv Thanks for using mapbox. Unfortunately there is not enough information here for us to look into the issue. Please fill out the provided issue template for reporting a bug and include a jsbin or jsfiddle reproduction of what you're seeing so we can help diagnose and fix the issue.
