### ISSUE TITLE
A strange question about fill color

### ISSUE THREAD

**Issue by ifzm** [mapbox/mapbox-gl-js#7433]
**mapbox-gl-js v0.50.0**:

### A strange question about fill color
1. I am trying to render multiple polygons
![image](https://user-images.githubusercontent.com/12740295/47084626-9d18ec00-d246-11e8-8674-f0cdc723a3e9.png)
2. Very successful drawing
![image](https://user-images.githubusercontent.com/12740295/47084723-000a8300-d247-11e8-8eb2-ca3ed3d87bb3.png)
3. A strange shape appeared when I zoomed, as shown :eye: 
![image](https://user-images.githubusercontent.com/12740295/47084792-3b0cb680-d247-11e8-8e8e-14fb686f688c.png)

I hope I can get help, thank you very much. :smile:

**Comment by mourner** [comment]
See #7023
