### ISSUE TITLE
"Can't serialize object of unregistered class" errors in console

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#7435]
**mapbox-gl-js version**: master
**browser**: Chrome

### Steps to Trigger Behavior

 1. Open `debug/index.html` page
 2. Zoom in/out one level.

### Expected Behavior

No errors.

### Actual Behavior

![image](https://user-images.githubusercontent.com/25395/47100516-f0d00900-d237-11e8-861e-b781e5cf42ec.png)

Bisecting now. I haven't noticed any breakage of the map itself, but the error is suspicious.

**Comment by mourner** [comment]
Reproducible with Streets v10 too — edited the description/title.

**Comment by pburkindine** [comment]
@mollymerp 	I am still seeing this error when using Electron 61; it complains that ArrayBuffer is not registered when trying to download Tiles.

**Comment by pburkindine** [comment]
Added issues with repro:
https://github.com/mapbox/mapbox-gl-js/issues/8287
https://github.com/cypress-io/cypress/issues/4322
