### ISSUE TITLE
Some GeoJSON geometries break in v0.46+

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#7436]
**mapbox-gl-js version**: v0.46+
**browser**: any

### Link to Demonstration

 1. Test case by @samfader https://bl.ocks.org/samfader/raw/0c68b85662ecb933bc5cbcfb7a673cfc/
 2. Test case by @anisart https://codepen.io/anisart/pen/wYpwpb

### Expected Behavior

Shapes look the same on all zoom levels.

### Actual Behavior

Important vertices are dropped on some zoom levels.

Reported in comments to #7023.

**Comment by mourner** [comment]
Bisected to https://github.com/mapbox/mapbox-gl-js/commit/4fd646c909cb383b8be064ba7961b18afe4e7ea9, digging into geojson-vt now.

**Comment by anisart** [comment]
I tried to charge order and direction of points in polygon. It stopped breaking when I set polygon from top-right point. But it doesn't help in all cases.

**Comment by mourner** [comment]
It's likely caused by https://github.com/mapbox/geojson-vt/commit/7226705d9ae8d140243b11894bc9db0f89051ef8, — I'll look closer why that happens and submit a fix tomorrow.

**Comment by samfader** [comment]
@mourner is it possible that this change might be causing a new issue - namely, lines of polygons are faintly visible in polygons themselves? See my test case:

https://bl.ocks.org/samfader/d1c9ab411d04bc82093c25cc80c55103

Here is the same data rendered as type `line` so you can see that those lines are still being rendered under the polygons: https://bl.ocks.org/samfader/39bc8e61c4b63f7739e75277fc40c554

Let me know if a new ticket is in order here.

**Comment by mourner** [comment]
@samfader maybe it was "working" before accidentally? The behavior looks like something I'd expect — to guarantee gapless rendering, you'd use a buffer in the tile data.

Also, let's confirm that it's related to the geojson-vt issue by checking in both v0.50 and v0.44.

**Comment by samfader** [comment]
@mourner apologies, I'm not sure I completely understand what you mean. Do you mind expanding on how this is expected behavior?

That being said, it looks like you're right that it's not related to the `geojson-vt` issue, because in v0.44: https://bl.ocks.org/samfader/ced01c4609da3979be1922f9b01740f6

Still seeing the lines. So I think I just need to get a better understanding of why this is expected given the data I have.

**Comment by mourner** [comment]
@samfader if you set `fill-antialias: false` in the layer paint properties, the lines disappear. You can look at antialias as a sort of a polygon gradient stroke.

As far as I understand (@ansis correct me if I'm wrong), if it's drawn on the tile boundary (there's no buffer), only half of it is clipped, and another one produces those subtle lines. This is the consequence of having `buffer = 0` in the data, so I think it's working as designed. The proper fix is to add a buffer to the tiles, and a workaround is to disable antialiasing (although this will make polygon edges look slightly less nice). Perhaps updating our fill antialiasing algorithm somehow would fix this issue (e.g. only draw smoothed pixels on the "outside" of a polygon), but we probably shouldn't spend time on this.

**Comment by ansis** [comment]
I think `buffer=0` should still be fine for gapless polygons because the lines are drawn on the outside and the inside part should be clipped away. That said, I'm not surprised this is buggy. @samfader I'm not seeing any lines or gaps in the example you posted. Could you provide a screenshot of what you are seeing?

**Comment by mourner** [comment]
Here's what I'm seeing on my retina MBP (in Chrome, FF and Safari):

![image](https://user-images.githubusercontent.com/25395/48561415-33950780-e8f0-11e8-9b6f-804ce4a344ec.png)

If you pitch the map or rotate it far enough, the lines disappear.

**Comment by samfader** [comment]
@ansis see screenshot above, but also my apologies since I modified my example and forgot to change it back. You should be able to see the lines in this test case: https://bl.ocks.org/samfader/d1c9ab411d04bc82093c25cc80c55103
