### ISSUE TITLE
Unreported breaking change: 0.45.0

### ISSUE THREAD

**Issue by mannnick24** [mapbox/mapbox-gl-js#7446]
Please make sure your breaking changes documentation contains all breaking changes. With mapbox version 45.0 there was a breaking change to the "error" event object

https://github.com/mapbox/mapbox-gl-js/commit/87c6332ea442b3a7628cc9c21212ffbe99487171#diff-03dff4f6d04644ac7a8d79a53f8f78ca
87c6332ea442b3a7628cc9c21212ffbe99487171
Event objects
@jfirebaugh
jfirebaugh committed on 21 Feb

e.g.
_event.status is now _event.error.status

**Comment by mollymerp** [comment]
Hi @mannnick24 – sorry to hear you ran into an unexpected breakage. We do make an effort to emphasize all breaking changes in our changelog entries. I'm not sure where you're seeing `_event.error.status` in the codebase, and the breaking changes to Evented were included in the changelog. If you can provide more details on what broke, I would be happy to add an entry into the changelog.

**Comment by mannnick24** [comment]
thanks ...

https://github.com/mapbox/mapbox-gl-js/commit/87c6332ea442b3a7628cc9c21212ffbe99487171#diff-03dff4f6d04644ac7a8d79a53f8f78ca
Within this change was a move to use an ErrorEvent object as the error event. the structure of the ErrorEvent differs from what was previously emited in the way I described above.
e.g.
- this._source.fire('data', {dataType: 'source', tile: tile, coord: tile.tileID});
+this._source.fire(new Event('data', {dataType: 'source', tile: tile, coord: tile.tileID}));
