### ISSUE TITLE
Position sticky and copyrights

### ISSUE THREAD

**Issue by RomanMarchenko** [mapbox/mapbox-gl-js#7447]
**mapbox-gl-js version**: 0.49.0

**browser**: Chrome, 70.0.3538.67 (64)

### Steps to Trigger Behavior

 1. Use position: sticky with map

Copyright fade away

### Link to Demonstration

https://monosnap.com/file/c6FR6aI9V9kaMRAbXq8OJUQ7xSsgAb

**Comment by ryanhamley** [comment]
Are you able to recreate this issue in a minimal example in JSBin? It seems possible that this bug is dependent on the specifics of how the app is structured. 

[MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/position#Sticky_positioning)
> A stickily positioned element is treated as relatively positioned until it crosses a specified threshold, at which point it is treated as fixed until it reaches the boundary of its parent.

**Comment by SpellChucker** [comment]
This issues is still happening for me. It's as simple as having your map in a div with `position: sticky`. The copyright and containers disappear.
