### ISSUE TITLE
double click to zoom then attempting to pan via drag is broken

### ISSUE THREAD

**Issue by mlg87** [mapbox/mapbox-gl-js#7454]
**mapbox-gl-js version**: 0.50.0

**browser**: chrome

### Steps to Trigger Behavior

 1. load map
 2. double click to zoom
 3. try to pan via dragging
 4. cursor will either turn to file (or in the case my gif a copyright sign)

### Link to Demonstration

this was reported in our app, but i reproduced it on the mapbox site. [here is an mp4 of the behavior happening on the mapbox site](https://www.dropbox.com/s/s4taufe40csvzca/mapbox-bug.mp4?dl=0)

### Expected Behavior
the user can pan the map via dragging after double click zooming

### Actual Behavior
they can't

**Comment by ChrisLoer** [comment]
Hi @mlg87, I tried double-clicking to zoom and then panning on the map at https://www.mapbox.com/maps/streets/, and I didn't see the same behavior shown in your video (using Chrome on Mac). Does it happen to you every time?

I took a glance at the source for https://www.mapbox.com/maps/streets/, and there's a fair amount of JS there outside of mapbox-gl-js that's managing scroll position, canvas resizing, map position, etc. It's very possible the loss of pan-ability you're seeing is some unexpected interaction between that code and GL JS. Can you help us isolate this problem by reproducing in a minimal JSFiddle just using GL JS?

**Comment by ChrisLoer** [comment]
🤔 I don't see the behavior on that pen either (just double clicking and then panning). My Chrome version is currently 69.0.3497.100.

**Comment by mlg87** [comment]
bizarre. i was on 69.0.3497.100 when it was happening. i just upgraded to 70.0.3538.77 to see if it would make a difference and i cant get it to happen on your site, our map or the pen that i linked to. im gonna close this. thanks for your time
