### ISSUE TITLE
bug? feature?   the tile requests still send  when i  setLayoutProperty('layerId', 'visibility', 'none' ) 

### ISSUE THREAD

**Issue by Eric-wh-007** [mapbox/mapbox-gl-js#7456]
**mapbox-gl-js version**:  v0.50.0

### Question

the tile requests still send  when i  setLayoutProperty('layerId', 'visibility', 'none' ) 
is this a bug or feature?

**Comment by mourner** [comment]
We can't say for sure because you have not filled out the required issue template, including a minimal reproducible test case.

**Comment by mourner** [comment]
Please don't submit duplicate issues like #7457 in the future — you can add information in one ticket instead.

**Comment by mourner** [comment]
Please don't submit duplicate issues like #7457 in the future — you can add information in one ticket instead.
