### ISSUE TITLE
map.setLayoutProperty('layerId', 'visibility', 'none' )  still  send tile request. why?

### ISSUE THREAD

**Issue by Eric-wh-007** [mapbox/mapbox-gl-js#7457]
**mapbox-gl-js version**:v0.50.0

### Question
mapbox still send tile request when i setLayoutProperty('layerId', 'visibility', 'none' ) 
it's bug or feature?

**Comment by Eric-wh-007** [comment]
```  
```

**Comment by Eric-wh-007** [comment]
# demo  code
```  
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title>Adjust a layer's opacity</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.50.0/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>

<style>
.map-overlay {
    font:bold 12px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
    position: absolute;
    width: 25%;
    top: 0;
    left: 0;
    padding: 10px;
}

.map-overlay .map-overlay-inner {
    background-color: #fff;
    box-shadow:0 1px 2px rgba(0, 0, 0, 0.20);
    border-radius: 3px;
    padding: 10px;
    margin-bottom: 10px;
}

.map-overlay label {
    display: block;
    margin: 0 0 10px;
}

.map-overlay input {
    background-color: transparent;
    display: inline-block;
    width: 100%;
    position: relative;
    margin: 0;
    cursor: ew-resize;
}
</style>

<div id='map'></div>

<div class='map-overlay top'>
    <div style="background:#fff;">
        <button onclick="showLayer()">show</button>
        <button onclick="hideLayer()">hide</button>
        <p>layer visibility: <span id="visibility"></span></p>
    </div>
</div>

<script>
mapboxgl.accessToken = 'pk.eyJ1IjoiODA3NTczNTE1IiwiYSI6ImNqZmJ5bXZ6ODBtdnMzM21zZGFwMW9kMncifQ.qVjod6pfoKs35WrQ7zmnLA';

var visibleTextEl = document.getElementById('visibility');
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/light-v9',
    center: [-87.6321, 41.8362],
    minZoom: 9.5,
    maxZoom: 13,
    zoom: 9.5
});

var slider = document.getElementById('slider');
var sliderValue = document.getElementById('slider-value');

map.on('load', function() {

    map.addLayer({
        "id": "chicago",
        "source": {
            "type": "raster",
            "url": "mapbox://mapbox.u8yyzaor"
        },
        "type": "raster"
    });

});

function showLayer() {
    map.setLayoutProperty('chicago', 'visibility', 'visible');
    visibleTextEl.innerText = 'show'
}

function hideLayer() {
    map.setLayoutProperty('chicago', 'visibility', 'none');
    visibleTextEl.innerText = 'hide'
}
</script>

</body>
</html>
```

**Comment by ChrisLoer** [comment]
Hi @Eric-wh-007, the expected behavior is that we'll stop requesting tiles when there are no layers within a style that are currently using a given source. That is in fact the behavior I see when I load up your example code. What I did:

- Load your page with the "Network" tab open in Chrome developer tools
- Zoom in, watch new raster tiles load
- Hide raster layer (this triggers some network activity)
- Zoom/pan further: no new raster tiles load

What are you seeing that's different?

**Comment by Eric-wh-007** [comment]
> Hi @Eric-wh-007, the expected behavior is that we'll stop requesting tiles when there are no layers within a style that are currently using a given source. That is in fact the behavior I see when I load up your example code. What I did:
> 
> * Load your page with the "Network" tab open in Chrome developer tools
> * Zoom in, watch new raster tiles load
> * Hide raster layer (this triggers some network activity)
> * Zoom/pan further: no new raster tiles load
> 
> What are you seeing that's different?

thank u your reply !
i understand your means. 
i just want **not send tiles requests** when i run ```  map.setLayoutProperty('layerId', 'visibility', 'none')```  
i did:

1. open 'Network' tab on chrome devTools
2. click hide buttons to ```setLayoutProperty visibility none``` 
3. the tiles requests still be sent

i have seen the same issue, so dont need to reply me

**Comment by zhenyanghua** [comment]
> Hi @Eric-wh-007, the expected behavior is that we'll stop requesting tiles when there are no layers within a style that are currently using a given source. That is in fact the behavior I see when I load up your example code. What I did:

@ChrisLoer, Does this mean in order not to load the tiles for raster layer, it must be removed from the map instance while the source could still be kept in the map?

**Comment by asheemmamoowala** [comment]
@zhenyanghua If there are no visible layers on the map that reference the raster source, it will not load any tiles.
