### ISSUE TITLE
Text doesn't follow rotation of map

### ISSUE THREAD

**Issue by donnyv** [mapbox/mapbox-gl-js#7462]
**mapbox-gl-js version**: 0.50.0

**browser**: Chrome, Firefox & EDGE

### Steps to Trigger Behavior
Rotate map

### Link to Demonstration
https://jsbin.com/kibisojiro/edit?html,output

### Expected Behavior
As the map is rotated. The text rotates with the map.

### Actual Behavior
The text sticks to its initial rotation

**Comment by ansis** [comment]
The [`text-rotation-alignment`](https://www.mapbox.com/mapbox-gl-js/style-spec#layout-symbol-text-rotation-alignment) can be used to control whether the text rotates with the map. I think you're looking for
```
'text-rotation-alignment': 'map'
```
