### ISSUE TITLE
Add only pitch capability without bearing

### ISSUE THREAD

**Issue by cantacell** [mapbox/mapbox-gl-js#7465]
Is it possible to add a feature  to block the rotate (due relative bounds check) without block the pitch?
Regards,
Francesco

**Comment by ChrisLoer** [comment]
Hi @cantacell, I may not be understanding your request, but the built-in handler that controls pitch and rotation in response to mouse movement is called `DragRotateHandler`. It doesn't have a "rotate only" mode. However, you could make your own handler that controlled pitch directly via `Map.setPitch`.

**Comment by cantacell** [comment]
I'm sorry I was not clear.
I wish the user could only tilt without the rotate.
