### ISSUE TITLE
Line smoothing

### ISSUE THREAD

**Issue by Plantain** [mapbox/mapbox-gl-js#7468]
Splitting out from #114 and #6973, for making 'prettier' plots, adding curves to geometry data and plumbing them all the way through to the renderer is a very heavyweight solution to a problem some line smoothing might solve.

Example of some unpleasant corners in real world geometry data:
<img width="528" alt="screen shot 2018-10-23 at 1 42 11 pm" src="https://user-images.githubusercontent.com/319895/47358247-84d32200-d6c9-11e8-9fe1-dd2651384b02.png">

Is this possible?

**Comment by ChrisLoer** [comment]
By "line smoothing" do you mean could we add a style option to automatically convert the edges of a polygon into curves based on some pre-set curve parameters? I think in terms of the rendering this would probably end up looking very similar to whatever we did for #6973, except that there wouldn't be a way to specify the curve.

cc @ansis @mourner

**Comment by Plantain** [comment]
Reading #6973 a bit closer I think that would actually fulfil what I'm trying to achieve.
