### ISSUE TITLE
Switching satellite maps or vector maps

### ISSUE THREAD

**Issue by Niumeng1** [mapbox/mapbox-gl-js#7472]
**mapbox-gl-js version**:0.50.0

### Question
Excuse me.
    When I switch from a vector map to a satellite map, I use the map.setStyle method to find out if the data can be smoothly switched like Google Maps when it is reloaded.

1. Code

> var map  = new mapboxgl.Map({
    container: 'originalMap',
    zoom: 8.8,
    style: 'mapbox://styles/mapbox/streets-v9', // stylesheet location
    center: [-74.50, 40], // starting position [lng, lat]
});

> let sdom = document.getElementById("switch");
let countNum=0;
 sdom.addEventListener("click",function(e){
     e.preventDefault();
     countNum++;
     if(countNum%2==0){
        map.setStyle("mapbox://styles/mapbox/streets-v9");
     }else{
        map.setStyle("mapbox://styles/mapbox/satellite-v9");
     }
 })

2. Demo
![image](https://user-images.githubusercontent.com/21193895/47401899-b0abe180-d775-11e8-8f3b-24d6ee2e1812.png)

![image](https://user-images.githubusercontent.com/21193895/47401920-c4efde80-d775-11e8-914b-89e38f643f07.png)

3.Questions
 Reloading data results in poor visual effects.
Is there a solution that is more efficient than this switch?

   Thanks.

**Comment by Niumeng1** [comment]
supplementary.
![ad](https://user-images.githubusercontent.com/21193895/47402304-7fccac00-d777-11e8-95d5-00094b07a4cb.gif)

thanks.

**Comment by Niumeng1** [comment]
supplementary.

![ad](https://user-images.githubusercontent.com/21193895/47402632-2a919a00-d779-11e8-8f53-9f608db6f1c5.gif)

thanks.

**Comment by Niumeng1** [comment]
It's settled. Thanks.

**Comment by ChrisLoer** [comment]
> It's settled. Thanks.

Hi @Niumeng1 , I didn't understand the question, but it sounds like you've figured out a solution?

**Comment by Niumeng1** [comment]
yes
