### ISSUE TITLE
Some examples confused

### ISSUE THREAD

**Issue by flyiiiiii** [mapbox/mapbox-gl-js#7473]
I see the example 'Animate 3D buildings based on ambient sounds' in the page 'https://www.mapbox.com/mapbox-gl-js/example/dancing-buildings/'.I was confused about the source.The codes follow:
map.addLayer({
            'id': '3d-buildings-' + i,
            'source': 'composite',
            'source-layer': 'building',
            'filter': ['all', ['==', 'extrude', 'true'], ['>', 'height', i * binWidth], ['<=', 'height', (i + 1) * binWidth]],
            'type': 'fill-extrusion',
            'fill-extrusion-opacity': .6  }
        });
Where can I  find the source named 'composite'?How does it form?What are the filters for this?Can I get the fiters for the 'road' source-layer? 
Looking forward to your replying.

**Comment by ChrisLoer** [comment]
Hi @flyiiiiii , thanks for using Mapbox! Unfortunately we can't provide general support for Mapbox via GitHub issues, although I can tell you the source/source-layer in that example come from the "style" set at map creation time, and the style itself was created in Mapbox Studio based off one of our templates.
