### ISSUE TITLE
How do I create a blur effect in circle type?

### ISSUE THREAD

**Issue by wlfei0502** [mapbox/mapbox-gl-js#7475]
**mapbox-gl-js 0.50.0-beta.1**:

### Question
How do I create a blur effect in circle type? 
Like heatmap-density property.

**Comment by ChrisLoer** [comment]
Hi @wlfei0502 , thanks for using Mapbox! We can't provide general support via GitHub issues, but this one seems really easy: https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-circle-circle-blur
