### ISSUE TITLE
how to calculate the value of tanslate based on longitude and latitude.

### ISSUE THREAD

**Issue by dinglei92** [mapbox/mapbox-gl-js#7481]
Hello, I have a question in custom layer. In #7039，have a example using ThreeJS, but I do't know how to calculate the value of tanslate based on longitude and latitude.  I hope to get your advice, thanks !

![_20181025130137](https://user-images.githubusercontent.com/16033134/47477137-4fa80a80-d856-11e8-94af-731a5d3d844e.png)

**Comment by ChrisLoer** [comment]
Hi @dinglei92, the relevant documentation is here: https://github.com/mapbox/mapbox-gl-js/blob/ab7d06a3fff9c67564cf49eb60b83e84bda49121/src/style/style_layer/custom_style_layer.js#L115-L135

The projection matrix you receive is spherical mercator coordinates, so if you change that translation to [0.5, 0.5], you'll see the cube move to "null island" in the center of the map.

Unfortunately, we can't provide general support with using mapbox or custom layers via GitHub issues.

**Comment by ansis** [comment]
@dinglei92 we haven't yet exposed a method for projecting from lnglat to mercator coordinates. I've opened an issue about adding that here: https://github.com/mapbox/mapbox-gl-js/issues/7485

**Comment by ansis** [comment]
https://github.com/mapbox/mapbox-gl-js/pull/7488 adds a new `MercatorCoordinate` type that can be used to calculate this value. It will be included in the next release.

```js
const translation = new mapboxgl.MercatorCoordinate.fromLngLat({lng: -79.39, lat: 43.65}, 72);

...

makeTranslation(translation.x, translation.y, translation.z)
```
