### ISSUE TITLE
Setting definition for cluster-count when Clustering

### ISSUE THREAD

**Issue by KJoWu** [mapbox/mapbox-gl-js#7484]
Currently we have a list of properties that have a field called amenities which is an integer.

Is there a way to set all the properties on a map via the cluster layer, but have the cluster count reference the property field instead of the property itself? 

Thanks!

**Comment by ChrisLoer** [comment]
Hi @KJoWu, I think the answer to your question is "no", but you may be interested in this PR: https://github.com/mapbox/mapbox-gl-js/pull/7004. cc @mourner
