### ISSUE TITLE
when I add a fill layer,i want to change the fill-color ,so the layer would not cover the layer below

### ISSUE THREAD

**Issue by zhangpengye** [mapbox/mapbox-gl-js#7490]
and in the API DOCS, it says ' This color can be specified as rgba with an alpha component and the color's opacity will not affect the opacity of the 1px stroke'.   the code Below:
            map.addLayer({
                'id': 'maine1',
                'type': 'fill',
                'source': {
                    'type': 'geojson',
                    'data': circle1
                },
                'layout': {},
                'paint': {
                    'fill-color': rgba(255, 255, 255, 0),
                    'fill-opacity': 0.5,
                    'fill-antialias': true,
                    'fill-pattern':true

                }
            });
but rgba is not defined
    at map.<anonymous> (test.html:56)
why

**Comment by ansis** [comment]
> `rgba(255, 255, 255, 0)` needs to be a string `'rgba(255, 255, 255, 0)'`

---

For future questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
