### ISSUE TITLE
New style switcher plugin

### ISSUE THREAD

**Issue by el** [mapbox/mapbox-gl-js#7495]
Hi, I just created a style switcher for `mapbox-gl`

Here is the npm package page: https://www.npmjs.com/package/mapbox-gl-style-switcher

![](https://raw.githubusercontent.com/el/style-switcher/HEAD/assets/closed.png)

![](https://raw.githubusercontent.com/el/style-switcher/HEAD/assets/open.png)

**Comment by el** [comment]
> Nice! Did you want to add it to https://www.mapbox.com/mapbox-gl-js/plugins/ via a PR? The source for that list is at https://github.com/mapbox/mapbox-gl-js/blob/mb-pages/docs/pages/plugins.js

Done 👍  https://github.com/mapbox/mapbox-gl-js/pull/7496

**Comment by hmendezm** [comment]
Hi everybody,
 it is a way to sitch the style but stay in the same extent and zoom on the map? I am using this plugin but my problem is every time the user switches the style this takes the user to a default position and after coming back to the position where the user was before the change.

Best,
hmendezm

**Comment by andrewharvey** [comment]
@hmendezm probably best to raise that over at https://github.com/el/style-switcher, this plug in is not maintained here.

**Comment by hmendezm** [comment]
Thanks, Andre
