### ISSUE TITLE
iOS8 rendering gets funny

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#750]
Mapbox GL JS performance on iOS8 is pretty smooth. But there are funny artifacts:

![gl-js-buggy](https://cloud.githubusercontent.com/assets/25395/4327926/11f6a378-3f7f-11e4-8ad8-60d683d30f5a.gif)

@kkaefer @ansis any ideas? It seems to only affect points/lines (not polygons, even on closer zoom with lots of buildings), skewing/translating tiles in a weird way.

**Comment by edenh** [comment]
Confirming here. It looks like just changing all `a_pos` attributes to `highp` is enough to fix this issue.

**Comment by ljbade** [comment]
@mourner have a look at the way the shader math is done.

Floating point can be more accurate if you are careful with your math operators and the order they occur.

E.g. division will cause more problems than multiplication

**Comment by mourner** [comment]
@ansis unfortunately this is still an issue with iOS 8.3 and the latest master.

**Comment by mourner** [comment]
OK figured out that while there's no apparent way to fix this by changing the math, just changing `matrix` uniforms to `highp` selectively in shaders (e.g. fill works ok without highp) also fixes the issue. I'm going to proceed with the fix. 

Memory shouldn't be a concern since it's a uniform and not an attribute, and if we have performance concerns, we could dynamically strip out `highp` string from shaders when in initializing them for particular platforms where this is not an issue.

**Comment by jfirebaugh** [comment]
I'm not _too_ concerned with this, but according to https://developer.mozilla.org/en-US/docs/Web/WebGL/WebGL_best_practices "Using highp precision in fragment shaders will prevent your content from working on some older mobile hardware".

**Comment by mourner** [comment]
> Using highp precision in _fragment_ shaders

We're using it in vertex shaders only.

**Comment by incanus** [comment]
My understanding when I was last doing shader work was that it's ideal to keep the same precision between both vertex and fragment shaders?

**Comment by ansis** [comment]
> the same precision between both vertex and fragment shaders

I don't think this matters. I think I remember reading that it can be a good idea to keep precision the same within a single vertex shader, but I don't think it matters very much.
