### ISSUE TITLE
map.loadImage() is underdocumented

### ISSUE THREAD

**Issue by bdirito** [mapbox/mapbox-gl-js#7504]
```
callback(Function)Expecting  callback(error, data) . Called when the image has loaded or with an error argument if there is an error.
```
What exactly are the arguments to that callback function? All we know is that error can be falsy and that data can be passed into map.addImage() by virtue of the example.

**Comment by ryanhamley** [comment]
`loadImage` results in an AJAX request to load the image data. If an error occurs during the request, the callback will be called with only one argument, the `error` which will be a typical AJAX error. If the request succeeds, then the callback will be called with the first argument (the error) being `null` and the second argument being an [HTMLImageElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement). You can see where the callback is called in this file: https://github.com/mapbox/mapbox-gl-js/blob/master/src/util/ajax.js#L181-L195

**Comment by ansis** [comment]
Re-opening this issue until we add ^ to the documentation.

**Comment by ryanhamley** [comment]
I'm going to close this and the other issues @bdirito opened to consolidate this discussion and work into this single ticket https://github.com/mapbox/mapbox-gl-js/issues/7505
