### ISSUE TITLE
CanvasSource rendering issues

### ISSUE THREAD

**Issue by Plantain** [mapbox/mapbox-gl-js#7506]
I have an app that renders wind streams over the top of a map, using a canvas source.
Normally it should look like this, with particles moving according to the wind, and everything works fine.

<img width="696" alt="screen shot 2018-10-29 at 9 27 49 pm" src="https://user-images.githubusercontent.com/319895/47678230-90d74c00-dbc1-11e8-9d5f-a244a48f04d8.png">

However, sporadically, and almost irreproducibly (for me), I occasionally get this, with the particles moving as expected, but the path behind being white and never repainting. It's almost like the repaint on the map isn't happening, but I have animate=true in the CanvasSource
<img width="689" alt="screen shot 2018-10-29 at 9 27 43 pm" src="https://user-images.githubusercontent.com/319895/47678233-916fe280-dbc1-11e8-9be0-40f12c7472e4.png">

Some users report they get it 100% of the time, and there doesn't seem to be anything unusual about their configurations (latest Chrome etc).

Removing/readding the layer and source fixes the problem reliably.

I haven't been able to reproduce it in a minimal test case yet, but I'm hoping someone will recognize right away the issue from the screenshots.

v0.49.0. Seems to affect Chrome and Safari at least.

**Comment by Plantain** [comment]
For context, the body of the draw loop:
                var g = params.canvas.getContext("2d");
                g.lineWidth = PARTICLE_LINE_WIDTH;
                g.fillStyle = fadeFillStyle;
                g.globalAlpha = 0.6;

                function draw() {
                        // Fade existing particle trails.
                        var prev = "lighter";
                        g.globalCompositeOperation = "destination-in";
                        g.fillRect(bounds.x, bounds.y, bounds.width, bounds.height);
                        g.globalCompositeOperation = prev;
                        g.globalAlpha = 0.9;

                        // Draw new particle trails.
                        buckets.forEach(function(bucket, i) {
                                if (bucket.length > 0) {
                                        g.beginPath();
                                        g.strokeStyle = colorStyles[i];
                                        bucket.forEach(function(particle) {
                                                g.moveTo(particle.x, particle.y);
                                                g.lineTo(particle.xt, particle.yt);
                                                particle.x = particle.xt;
                                                particle.y = particle.yt;
                                        });
                                        g.stroke();
                                }
                        });
                }

**Comment by ryanhamley** [comment]
Hi @Plantain thanks for using Mapbox. Definitely update this ticket if you can reproduce it in a minimal test case. It looks like the blending mode may be periodically getting out of whack. cc @ansis @mourner
