### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by samuelrb14** [mapbox/mapbox-gl-js#7508]
**mapbox-gl-js version**: 0.49.0

### Question

How can I use Mapbox GL JS on a offline mode?

**Comment by folsze** [comment]
@ryanhamley is it feasible to make this work by developing a local server as is mentioned here in this comment:
https://stackoverflow.com/a/43484182/20009330

I have been thinking of developing some sort of bridge from the native layer. For a Hybrid Native App (CapacitorJS Plugin). 

Is this possible or are there some huge barriers that would prevent this?
