### ISSUE TITLE
how to set multiple "all" filters

### ISSUE THREAD

**Issue by predictwise** [mapbox/mapbox-gl-js#7509]
**mapbox-gl-js version**: v0.50.0

### Question
I want to implement a filter that contains multiple "all" filters.
For example, i want to get all the data  from Jan 2014 to Apr 2015 using following code, but it failed! 

```
filterLastYear = ['==', ['get', 'Year'], 2014];  

thisYear = ['==', ['get', 'Year'], 2015];
monthOfThisYear = ['match', ['get', 'Month'], [1, 2, 3, 4], true, false];
filterThisYear = ['all', thisYear, monthOfThisYear]

map.setFilter('contributions', ['all', filterLastYears, filterThisYear]);
```
I can implement this logical condition with python code easily, just like:
```
if (year == 2014) and (year == 2015 and month in [1, 2, 3, 4]):
     some code here
```
### Expected Behavior
The filters should be applied and the map should show data with the whole year of 2014, i.e 2014-01 ~ 2014-12, and 2015-01 ~ 2015-04.

### Actual Behavior
I got nothing on the map!

### My data structure(a geojson file)
```
{
  "type": "FeatureCollection",
  "features": [{
    "type": "Feature",
    "properties": {
      "Year": 2014,
      "Month": 1
    },
    "geometry": {
      "type": "Point",
      "coordinates": [-73.9066122, 40.7453924]
    }
  }, {
    "type": "Feature",
    "properties": {
      "Year": 2015,
      "Month": 3
    },
    "geometry": {
      "type": "Point",
      "coordinates": [-73.8427393, 40.8794247]
    }
  }
.....
.....
]
}
```

Please tell me how to write right expression and thanks in advance!

**Comment by mourner** [comment]
> if (year == 2014) and (year == 2015

A year can't be both 2014 and 2015 at the same time. You're probably looking for [any](https://www.mapbox.com/mapbox-gl-js/style-spec/#expressions-any) expression, not `all`.

**Comment by predictwise** [comment]
Thanks! How stupid i am!
