### ISSUE TITLE
Public styledeclaration/styleconstants interface

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#751]
Right now we have to dirty-hook into them and when they [change locations](177960a8d0cf4add744be34191f59f74bd4287b9) it breaks. Ideally we could do something like `mapboxgl.style.StyleDeclaration` to use this code outside of a Map object.

**Comment by mourner** [comment]
Do we still need with the new style properties API?

**Comment by jfirebaugh** [comment]
https://github.com/mapbox/mapbox-gl-function / https://www.npmjs.com/package/mapbox-gl-function
