### ISSUE TITLE
Add LatLngBounds.contains() method

### ISSUE THREAD

**Issue by ryanhamley** [mapbox/mapbox-gl-js#7512]
## Motivation

I'm splitting this request out from https://github.com/mapbox/mapbox-gl-js/issues/7090 in which several different `LatLng` and `LatLngBounds` methods were brought up. GL Native has a [`LatLngBounds.contains`](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/geo.cpp#L37) utility method which is missing in JS. Adding this method to JS would increase parity between GL implementations and provide a useful method to users.

## Design

I can see two possibilities.

1) A static method on LatLngBounds
```
LatLngBounds.contains(bounds, point)
```

2) An instance method
```
const bounds = new LatLngBounds([sw, ne]);
bounds.contains(point);
```

I'd say the instance method is preferable since all other methods on `LatLngBounds` are also instance methods. The static method would mostly be useful as a pure utility method in which you may want to check arbitrary bounds for a point, but does that have many use cases? I'm unsure.

`contains` should be able to check that a bounding box contains a [point](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/geo.cpp#L41) or a [CanonicalTileID](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/geo.cpp#L37), as the Native implementation does. Native also checks [unwrapped bounds](https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/geo.cpp#L68), but that concept isn't well defined in JS and I think we can side step that implementation for now.

### Implementation

We should be able to just port the C++ implementation
https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/tile_range.hpp#L40

**Comment by ryanhamley** [comment]
Thanks for pointing that ticket out. The lack of methods like this was mostly due to a conceptual way of thinking about Mapbox GL JS as a rendering library, not a geospatial query library. But given that there's user demand, it's straightforward to implement and it brings JS into parity with Native, I think it's ok to move forward with this. We'd welcome a PR if you're interested in adding this @FernandoKGA

**Comment by FernandoKGA** [comment]
I would love to @ryanhamley , however, I don't have so much time to develop a topic like this now as I'm studying, in addition, I do not have enough experience or practice with JS, yet. I'm using the API to develop a web project as a final test on one of my subjects at university. Probably by the time I will have finished the project, someone would already done it. (I think...)

**Comment by ryanhamley** [comment]
The GL JS implementation of this will need to implement all 3 definitions of `contains` in the GL Native repo as seen in https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/util/geo.cpp#L37-L65
