### ISSUE TITLE
Is there any way to add 3d building textures in mapbox GL JS?

### ISSUE THREAD

**Issue by Vinita18** [mapbox/mapbox-gl-js#7520]
Hi, I want to ask, Is there any way to add 3d building textures on map using GL JS?
I found the option to change the color of the buildings in mapbox studio but I want to add textures to the 3D buildings to give more realistic look like Unity. Or does mapbox supports unity webGL builds?

**Comment by ryanhamley** [comment]
Hi @Vinita18 there's no way to apply textures to a 3d extrusion layer, but our new [custom layer interface](https://www.mapbox.com/mapbox-gl-js/api/#customlayerinterface) may suit your needs. They allow for rendering 3d models on your map as seen [here](https://bl.ocks.org/andrewharvey/7b61e9bdb4165e8832b7495c2a4f17f7). If you have further questions, our [support team](https://www.mapbox.com/contact/support/) is available to help.

**Comment by spencerthayer** [comment]
The [example](https://bl.ocks.org/andrewharvey/7b61e9bdb4165e8832b7495c2a4f17f7) posted above no longer works. @ryanhamley has the required code changed?

**Comment by ryanhamley** [comment]
@spencerthayer I'm not sure why that link doesn't work, but we have an official example of adding 3d models to GL JS now: https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/

**Comment by spencerthayer** [comment]
@ryanhamley thanks for that. I used the CodePen example and [saved my own](https://codepen.io/spencerthayer/pen/JjOqwVg) but it's not working. Any ideas why it wouldn't be?

**Comment by ryanhamley** [comment]
It's working, but you changed the map center, but not the model origin, so the model is being rendered somewhere offscreen.
