### ISSUE TITLE
Calling setRTLTextPlugin causes multiple requests for the js file

### ISSUE THREAD

**Issue by haywoodsloan** [mapbox/mapbox-gl-js#7525]
**mapbox-gl-js version**: v0.50.0

**browser**: Chrome (70.0.3538.77), Edge (44.17763.1.0)

### Steps to Trigger Behavior

 1. Call `mapboxgl.setRTLTextPlugin(...)`

### Link to Demonstration

https://www.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/

### Expected Behavior

The RTL plugin is requested once after calling `mapboxgl.setRTLTextPlugin(...)`

### Actual Behavior

The RTL plugin is requested multiple time, nearly simultaneously so no benefit from caching. It appears this could be correlated to the machine's number of logical processors. A machine with 12 logical processors saw 6 requests where as a machine with 4 logical processors saw only 2, but this could be coincidental.

**Comment by ryanhamley** [comment]
It's actually not coincidental. What you're seeing is the web workers that the library spins up requesting a copy of the RTL Text plugin, which the workers use in shaping text and laying out the vector tiles during parsing. The number of workers that spin up is 1/2 your machine's logical processors or 6, whichever is smaller. The main thread should download the plugin and store it in the browser cache and then each worker should request the cached copy. The caching behavior was implemented in https://github.com/mapbox/mapbox-gl-js/pull/6170.

At the risk of asking the obvious, can you confirm that you're seeing this behavior with caching enabled in your dev tools?

**Comment by haywoodsloan** [comment]
Thank you for the reminder about Chrome's devtools disabling caching by default. After enabling caching I see the behavior you described, one request is downloaded then all the others are pulled from the cache. Everything looks good.
