### ISSUE TITLE
Mapbox Unity SDK support for webGL platform

### ISSUE THREAD

**Issue by Vinita18** [mapbox/mapbox-gl-js#7531]
Hi,

Does mapbox Unity sdk support unity-webGL builds?
https://www.mapbox.com/mapbox-unity-sdk/docs/02-known-issues.html reference page
in the platform support section web/Unity webGL platform is not mentioned. 

Is there any update on this in the latest Mapbox SDK?

**Comment by ryanhamley** [comment]
Hi @Vinita18 the Unity SDK is compatible with all environments the Unity engine supports, so you can use a Unity WebGL build.

Please note that this issue tracker is for reporting bugs and requesting features in the Mapbox GL JS library. To get an answer for a more generalized or non GL JS question like this, I'd suggest contacting our [support team](https://www.mapbox.com/contact/support/).
