### ISSUE TITLE
Calling map.getLayoutProperty will throw an undefined error when layer doesn't exist

### ISSUE THREAD

**Issue by donnyv** [mapbox/mapbox-gl-js#7537]
## Motivation
Calling map.getLayoutProperty should not throw an undefined error when layer name doesn't exist. 

## Design Alternatives
It should return null.

## Design
I thought I was having issues with my map object because an undefined error was being thrown.

### Implementation
javascript

I was using version 0.50.0

**Comment by ryanhamley** [comment]
Thanks for reporting this @donnyv `getLayoutProperty` definitely shouldn't crash the map in this situation. `setLayoutProperty` handles this exact situation by throwing a non-fatal error warning that the layer doesn't exist so I submitted a PR to allow `getLayoutProperty` to do the same thing. The call to `getLayoutProperty` will then return `undefined`.
