### ISSUE TITLE
yarn build and yarn test-build appear to be broken

### ISSUE THREAD

**Issue by ryanhamley** [mapbox/mapbox-gl-js#7542]
https://github.com/mapbox/mapbox-gl-js/pull/7494 changed the `build` script in `package.json` but https://github.com/mapbox/mapbox-gl-js/pull/7515 appears to have reverted it back. Updating the `build` script to `run-s build-docs && batfish build` fixes `yarn build`. However, `yarn run test-build` still fails with the error `Error: ENOENT: no such file or directory, open '<pathway>/mapbox-gl-js/dist/style-spec/index.js'`. So far I haven't had any luck tracking this error down.

This appears to be causing errors on CircleCI as well since we updated the CI image and cleared the cache tonight as seen [here](https://circleci.com/gh/mapbox/mapbox-gl-js/31523).

**mapbox-gl-js version**:
`master`

**browser**:
n/a

### Steps to Trigger Behavior

 1. be up to date on `master`
 2. run `yarn build` or `yarn run test-build`

### Expected Behavior
Build should work and the tests should pass

### Actual Behavior
Build and tests fail

**Comment by booo** [comment]
I'm quite unfamiliar with this whole build ecosystem. 

If I run:
```
yarn build
yarn build-dev
yarn build-prod
yarn build-prod-min
yarn build-style-spec
```
The tests will pass. I guess some dependencies of the build script do get executed.

**Comment by asheemmamoowala** [comment]
The `build-style-spec` target is a dependency for `test-build`.
