### ISSUE TITLE
Allow ability to change the color and size of custom icons

### ISSUE THREAD

**Issue by carrieVant** [mapbox/mapbox-gl-js#7545]
## Motivation

We are looking into switching from openlayers to MapBox GL JS and would like a way to change the color and size of custom icons without needing to add additional icons to our sprite.  Openlayers currently supports this functionality with the Color and Scale properties on ol.style.Icon.  We currently adjust the color and scale of icons based on data attributes changing.

## Design Alternatives

Support the color property on Marker when also using the element property.  Add a scale property to Marker that will adjust the scale/size of a custom marker.

## Design

new mapboxgl.Marker({element: i, color: '#F00', scale: 1.3})

### Implementation

new mapboxgl.Marker({element: i, color: '#F00', scale: 1.3})

**Comment by ryanhamley** [comment]
Hi @carrieVant when you pass an element to the Marker constructor, the element has to be an HTML element which can be styled normally with CSS. You may be thinking of symbol markers which do not use the Marker constructor. If your sprite contains SDF icons, you can change their color dynamically depending on data with the [`icon-color`](https://www.mapbox.com/mapbox-gl-js/style-spec#paint-symbol-icon-color) style property. You can see an example of using symbol layers as markers [here](https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/).
