### ISSUE TITLE
support fitBounds options when setting the initial map bounds

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#7553]
Support for initial bounds as map constructor option was added in #5518, internally it uses `fitBounds` but it doesn't expose the [`fitBounds` options](https://www.mapbox.com/mapbox-gl-js/api/#map#fitbounds) `padding`, `offset`, `maxZoom`.

We could add a `bounds_options` option, but that just feels too complicated so I'm against it.

I think the best solution here will come out of #2801, which will likely open up a simpler approach to passing the initial camera state for the Map as a single object.

**Comment by andrewharvey** [comment]
One possible workaround is to set the `bounds` without additional `fitBounds` options as a `Map` option to get it close enough at initialisation, and then immediately call `map.fitBounds` with the same bounds but with additional options.

This does seem to happen fast enough that no tile requests are actually made for the original bounds with no options, only tile requests for the `fitBounds` with options. Given this, I'd say this issue is low priority since it would really only help to reduce roadblocks for developers who face similar issues.

**Comment by pathmapper** [comment]
Such a `bounds` padding option was requested in this [stackoverflow comment](https://stackoverflow.com/questions/53330202/set-map-bounds-based-on-multiple-marker-lng-lat/53332980#comment93567150_53332980).
