### ISSUE TITLE
Labels slipping/cropping at tile bounds

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#757]
As we pan in and out, labels tuck under other layers at certain fractional zoom levels. So far, I've only seen this happen with city labels.

EDIT: happens with all symbols.

**Comment by peterqliu** [comment]
(bump)

This continues to be one of the most conspicuous rendering bugs in `gl-js`. Would appreciate some prioritization here

**Comment by jfirebaugh** [comment]
@peterqliu: No status change since https://github.com/mapbox/mapbox-gl-js/issues/757#issuecomment-60295415 -- blocked by #193, which is blocked by https://github.com/mapbox/mapbox-gl-js/issues/682, which is blocked by https://github.com/mapbox/mapnik-vector-tile/issues/53.

**Comment by mourner** [comment]
@jfirebaugh last time I asked @ansis, he said layer-by-layer isn't blocked by tessellation anymore, with an active branch about it. :)

**Comment by peterqliu** [comment]
Test case, if anyone still needs: https://www.mapbox.com/bites/00108/#15.26/40.7306/-73.9869

**Comment by amyleew** [comment]
Another test case: [label slippage from z3 - z4](https://www.mapbox.com/bites/00184/slowfly.html)

![label-slip](https://cloud.githubusercontent.com/assets/4587826/9948080/ed06adb6-5d6d-11e5-87b4-b0fe34305ef9.gif)

**Comment by lyzidiamond** [comment]
tagging @mapbox/support for known issue

**Comment by samanpwbb** [comment]
just noticed that setting `text-allow-overlap` to `true` seems to make this problem go away:

with text-allow-overlap:
<img width="556" alt="screen shot 2015-11-03 at 4 14 45 pm" src="https://cloud.githubusercontent.com/assets/108094/10921881/175c111c-8246-11e5-8adc-4a4749aa63c4.png">
without text-allow-overlap:
<img width="549" alt="screen shot 2015-11-03 at 4 14 38 pm" src="https://cloud.githubusercontent.com/assets/108094/10921882/175f96b6-8246-11e5-9e80-140685e378cb.png">

**Comment by peterqliu** [comment]
@samanpwbb interesting; have you run into issues with the text colliding with symbols, when you turn that on?

**Comment by samanpwbb** [comment]
@peterqliu yes, but they're not so bad.

**Comment by samanpwbb** [comment]
heh, how about this – I'm now seeing the reverse behavior:
![screen shot 2015-11-03 at 6 39 20 pm](https://cloud.githubusercontent.com/assets/108094/10925224/41348910-825a-11e5-951a-550af7f30ae3.png)
![screen shot 2015-11-03 at 6 39 17 pm](https://cloud.githubusercontent.com/assets/108094/10925223/4134860e-825a-11e5-8ffc-99dfd15ddd24.png)

**Comment by jfirebaugh** [comment]
Status update here is that work is in progress to fix this issue in https://github.com/mapbox/mapbox-gl-js/pull/1197, but is blocked on issues with our headless rendering test system.

**Comment by lucaswoj** [comment]
State update #2: fixing this bug is my highest priority right now and work is progressing in #1727. We are pushing hard to fix the underlying problems with our headless rendering test system.

**Comment by Rachine** [comment]
Hey, thank you to put priority on this one, have the same problem here!

**Comment by samanpwbb** [comment]
:fireworks:

**Comment by peterqliu** [comment]
:O :O :O :tada: :dancer:

**Comment by lucaswoj** [comment]
@ansis is back in town, ladies and gentleman :smile:

**Comment by planemad** [comment]
:rocket: :rocket: :rocket: :rocket: :rocket:

**Comment by manuelroth** [comment]
Great work, really nice to see this fixed. Looking forward to the next release.
