### ISSUE TITLE
Fixed Scale in Scale Control

### ISSUE THREAD

**Issue by reyemtm** [mapbox/mapbox-gl-js#7577]
### Static Scale Control
I want my maps to have a fixed scale, i.e. 1" = x ft or mi (ideally for printing, but that's another issue altogether). It looks like this was discussed in the [initial scale control topic](https://github.com/mapbox/mapbox-gl-js/issues/1807) and mentioned in a way [here](https://github.com/mapbox/mapbox-gl-js/issues/5658).

I see this as something that could be added to the scale-control options. I have a working demo of this for devices where 1" equals 96px.

    static: true,
    maxWidth: 96

The adjustment to the scale control looks like this

    let distance = (options && options.static === true) ? maxDistance.toFixed(0) : getRoundNum(maxDistance);
    distance = (unit === 'mi') ? maxDistance.toFixed(2) : distance;
    const ratio = (options && options.static === true) ? 1 : distance / maxDistance;

However I think this breaks down with different device PPI. Ideally units to pixels would be worked out in the control, but maybe this is not possible with JavaScript:

    static: true,
    staticWidth: 1,
    staticUnits: 'in' //inches, pixels, centimeters, millimeters, throw an error is this would be larger than the map container

Going a bit deeper, it would be great to have this integrated into the map if possible so that calling
    
    map.setScale(['1', '2000', 'in', 'ft']) //or something like that

would zoom the map to the appropriate zoom level that matches this scale.

**Comment by asheemmamoowala** [comment]
>  this breaks down with different device PPI. Ideally units to pixels would be worked out in the control, but maybe this is not possible with JavaScript:

Based on this [stackoverflow](https://stackoverflow.com/questions/40480617/is-a-css-pixel-really-an-absolute-unit-that-is-is-1-inch-96px-true) post, it seems that it is not possible to accurately determine the real DPI for a screen in the browser. Print may be another matter.
