### ISSUE TITLE
Unable to use circle-radius interpolation based on zoom expression

### ISSUE THREAD

**Issue by emakarov** [mapbox/mapbox-gl-js#7583]
**mapbox-gl-js version**: 0.51.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. I'm unable to get circle-radius interpolation based on zoom get working
 2. I took the basic example from docs
 3. Added very basic circle-radius expression on linear interpolation
4. Circle size is not changing

Example is here, not sure what is wrong

https://jsbin.com/jacifawite

**Comment by ansis** [comment]
The example is working for me but the effect isn't that apparent with the chosen zoom levels. The zoom for the second stop is `10` so the radius will be the same at every zoom > 10. In your example the circle size is 1 if you zoom all the way out.

 I changed the values of your example to make the effect more visible: https://jsbin.com/qusikifeyo/

**Comment by emakarov** [comment]
oh... thanks
