### ISSUE TITLE
Custom attribution strings have additional <p> tags causing layout problems (v0.51.0)

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-js#7589]
Hi,

Since v0.51.0 custom attributions have additional `<p>` tags around them causing the layout to stack:

<img width="648" alt="screenshot 2018-11-13 at 20 33 46" src="https://user-images.githubusercontent.com/13920398/48441488-95842e80-e783-11e8-83d9-e73ebef2ad4d.png">

The pipe separator is also surrounded by `<p>` tags.

You can replicate using a simple example:

`map.addControl(new mapboxgl.AttributionControl({customAttribution: "MY CUSTOM ATTRIBUTION"}));`

I can resolve by reverting back to v0.50.0

**Comment by ryanhamley** [comment]
This was introduced in https://github.com/mapbox/mapbox-gl-js/pull/7444/files to fix compact attributions. Looks like we need to make the `<p>` tags inline for full size attributions as well.

**Comment by andrewharvey** [comment]
also happening in https://www.mapbox.com/designer-maps/#cali-terrain
