### ISSUE TITLE
Initial bounds resets map's pitch to 0

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#7597]
**mapbox-gl-js version**: v0.51.0

### Question

Initial `bounds` added in https://github.com/mapbox/mapbox-gl-js/pull/5518 resets the map's pitch ([jsbin](https://jsbin.com/pazaqafobe/1/edit?html,output)), is this expected behavior?

Asking because `map.fitBounds` preserves the pitch ([jsbin](https://jsbin.com/zepamemuqa/1/edit?html,output)) and it isn't documented that `bounds` resets it.

### Links to related documentation

https://www.mapbox.com/mapbox-gl-js/api/#map

https://www.mapbox.com/mapbox-gl-js/api/#map#fitbounds

**Comment by mourner** [comment]
This looks like an oversight in #5518. @stepankuzmin would you mind submitting a fix? Should a small change.

**Comment by stepankuzmin** [comment]
Sorry for the late response, fixed in #7617
