### ISSUE TITLE
addSource loading data from a URL does not work in IE11

### ISSUE THREAD

**Issue by adeshp** [mapbox/mapbox-gl-js#7599]
Mapbox addSource not able to load the geojson data from a url in a IE11 browser.

**mapbox-gl-js version**: v0.51.0

**browser**: IE 11

### Steps to Trigger Behavior

 1. Create a map.
 2.  addSource function to load geojson data from a url

### Expected Behavior

The map should load data from the url in IE11

### Actual Behavior

The data is not loaded in IE11.

**Comment by mourner** [comment]
Is this reproducible on one of the official examples, i.e. [this one](https://www.mapbox.com/mapbox-gl-js/example/live-geojson/)? If not, can you provide a minimal test case?
