### ISSUE TITLE
turnstile event localStorage cleaning

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#7602]
Following up on @scottgerring's question at https://github.com/mapbox/mapbox-gl-js/pull/6980#issuecomment-436502564 ...

@asheemmamoowala if you're using temporary access tokens which are fresh for each user session, recurring users can quite easily gather quite a few of these localStorage items per day, as the days go on this will just keep growing.

Not only that but it looks like under the current implementation Mapbox will see those as new unique users when actually they are recurring users.

What if instead of using the access token as the localStorage key you only use the account username of the access token?

**Comment by asheemmamoowala** [comment]
> under the current implementation Mapbox will see those as new unique users when actually they are recurring users.

The actual count of unique users is calculated using the turnstile event data and ignores multiple requests from the same `userId` within a certain period.  So extra events being sent will not adversely affect any "MAU" type statistics.

> What if instead of using the access token as the localStorage key you only use the account username of the access token?

This would help with the proliferation of items in the local storage but not help with the extraneous requests being sent when the access token changes frequently.
