### ISSUE TITLE
Use of fetch API breaks cordova apps

### ISSUE THREAD

**Issue by gpiffault** [mapbox/mapbox-gl-js#7603]
**mapbox-gl-js version**: 0.51.0

**browser**: Chrome 70 (webview)

#7371 introduces a bug in cordova apps loading local assets. The fetch API doesn't support the `file:` scheme whereas xhr does (https://github.com/github/fetch/pull/92#issuecomment-140665932) so when style specification or images are stored locally, they won't load after 0.51.0 (works fine up to 0.50.0).

For reference, I commented on the commit here https://github.com/mapbox/mapbox-gl-js/commit/eec8cd5e43ee861b5202a1e1eb2e7d5739e0dfef#commitcomment-31351193

**Comment by mourner** [comment]
Yeah, we should probably switch to XHR when requesting a URL with a file protocol. cc @kkaefer Would you like to do a PR with the fix?

**Comment by kkaefer** [comment]
It looks like no browser allows access via `file://` URLs anyway´ due to security constraints. E.g. Chrome reports:

`Access to XMLHttpRequest at 'file://test/integration/tiles/14-8803-5375.mvt' from origin 'file://' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.`

**Comment by gpiffault** [comment]
This behaviour is disabled in the webview cordova uses (only for xhr, not for fetch, it's probably not possible for fetch). Unfortunately I think it's not rivial to test it out, you need to install cordova, make a sample project and run it on a device. I can help with the testing.

**Comment by mourner** [comment]
@kkaefer it's possible in certain environments like Cordova. We had related PRs before, e.g. this one https://github.com/mapbox/mapbox-gl-js/pull/6610

**Comment by ansarikhurshid786** [comment]
I am also using ionic 3 which use cordova for building ios and android application. In my application it is working fine. I seen my application running on local web server.

**Comment by kkaefer** [comment]
@gpiffault This should be fixed in https://github.com/mapbox/mapbox-gl-js/pull/7818.

**Comment by gpiffault** [comment]
@kkaefer Thanks. Actually it didn't directly fixed my use case besause I used relative URLs to load the local assets so the [regexp](https://github.com/mapbox/mapbox-gl-js/pull/7818/files#diff-613b4e62662c8d2275ce897c4eba3bd2R170) isn't enough in this case. It works when I convert my URLs to absolute but it's not quite straightforward, you might get new bug reports about this.

**Comment by denis1994** [comment]
I have the same problem. I use mapbox in react project with cordova but my pins images aren't loaded. Downgrading to 0.50.0 works fine. I also use relative paths.

**Comment by denis1994** [comment]
@gpiffault I will test your commit and report here. Perhaps they can take it to the actual version.
