### ISSUE TITLE
Is there any way to rotate an image ?

### ISSUE THREAD

**Issue by gawlk** [mapbox/mapbox-gl-js#7606]
Hi,

I was playing with your wonderful library after using Leaflet for a few months to see if I could make the switch, but there one vital feature to me that seems to be missing.

**Can I add an image to a map and then rotate it on the fly ? If not, what would be the best way to add this feature ?**

I spent the whole day yesterday to see how it could be achieved but I kept hitting walls over and over again. I tried to add images via layers, symbols and markers. Layers can't be rotated and symbols/markers don't have fixed positions. [Here's the library](https://github.com/IvanSanchez/Leaflet.ImageOverlay.Rotated) that I'm currently using in Leaflet, which comes with an [example](http://ivansanchez.github.io/Leaflet.ImageOverlay.Rotated/demo.html). I thought about doing an .extends() like in Leaflet but it doesn't seem to be possible with Mapbox. If it is, I'm trully sorry for the inconvenience.

Thank you for your answer and your great work ! :+1: 

Kevin

**Comment by ryanhamley** [comment]
There's not really a way to do this right now but there's a ticket for adding animation for images (https://github.com/mapbox/mapbox-gl-js/issues/7588) if you'd like to read some proposals for this. There's no specific timeline on this feature at the moment though.
