### ISSUE TITLE
Custom Style Layer (Webgl) positioning issue at high zoom

### ISSUE THREAD

**Issue by neverwiredhouse** [mapbox/mapbox-gl-js#7616]
**mapbox-gl-js version**:
0.51.0

**browser**:
Chrome & Safari

### Steps to Trigger Behavior

 1. click link below
 2. zoom in really far, make sure to study an edge
 3. watch it shake like crazy

### Link to Demonstration
https://www.mapbox.com/mapbox-gl-js/example/custom-style-layer/

### Expected Behavior
polygon continues to render (this happens to lines too)

### Actual Behavior
polygon/lines freaks out

**Comment by mourner** [comment]
See discussion about this in #7268. Closing as duplicate.
