### ISSUE TITLE
Detect turns in the NavigationRoute response

### ISSUE THREAD

**Issue by nedelcu28** [mapbox/mapbox-gl-js#7619]
**mapbox-gl-js version**:

### Question
Hello,

i am trying to perform an action when a turn instruction is detected(leftTurn, rightTurn).From the documentation i understand i have to do something like response.steps.legs.type.turn() but that doesnt work. Disclaimer:the response object works as intended but i don't know how to acces some of its data.

**Comment by mourner** [comment]
Looks like you're reporting an issue in the wrong repo. This one is about map rendering, and isn't related to navigation API responses.
