### ISSUE TITLE
Expression generating black styles with nested objects.

### ISSUE THREAD

**Issue by rebz** [mapbox/mapbox-gl-js#7620]
_The example provided is not my original code, just a mini-version that is similar to how I am loading data and attempting to style._

**mapbox-gl-js version**: 0.51.0

**browser**: Chrome Version 70.0.3538.110 (Official Build) (64-bit) on MacOS

### Steps to Trigger Behavior

 1. Please view the CodeSandbox Source link below.
 2. Open the file `/components/SourceLayer.vue`
 3. Notice the expressions used for styling against a nested property `pcp.Zip`.

### Link to Demonstration

1. [CodeSandbox Source](https://codesandbox.io/s/l9n1y8xywz) for a view of the source code.
2. [CodeSandbox Web View](https://j2orr5wj9.codesandbox.io/) to view just the web output.

### Things to Note

I am importing a CSV file, then importing a Geojson file, then joining the CSV columns into the relative Geojson feature props. Once complete, I store this in a variable and reference that as a map source. You can see this taking place in `App.vue` on CodeSandbox.

Not sure if this is an actual bug or me not understanding how expressions work. My apologies if the latter as I'm brand-spanking new to Mapbox. Appreciate any insight or help on understanding this.

### Expected Behavior
Each `feature.properties` should contain an object under the key `pcp`. I should see precincts (features) on the map highlighted `green` if their `feature.properties.pcp.Zip` has a value. At most their `fill-opacity` should be set to `1`. When I hover over a feature it should turn from `green` with an opacity of `1` to the color `blue` with an opacity of `0.5`.

### Actual Behavior
Some features gain the correct `green` color, but a cluster of features in the center have a color of `black`. Also, once a user leaves a feature (mouseout), instead of reverting back to the color `green` from `blue`, it appears to change to `black` with an opacity of `1`. Neither of these effects are intended.

The "cluster of black features" in the middle of the map is not something I experienced until I tried to replicate my project in CodeSandbox to show on here. Below is a screenshot of my project on my local machine where I am only experiencing the post-hover issue.
![image](https://user-images.githubusercontent.com/628385/48992112-323fb800-f104-11e8-8933-47b8f8fd3792.png)

**Comment by mourner** [comment]
Unfortunately nested property values aren't currently supported — it's a tough technical challenge. Some more background in #2434 — let's close this one as a duplicate.
