### ISSUE TITLE
point to sector

### ISSUE THREAD

**Issue by dfy167** [mapbox/mapbox-gl-js#7621]
Hello! Thanks for contributing.

but i want render point to sector with dirction ,r . how can i accomplish.
are there any api to change point feature to any other feature so when loaded point i can change it to sector or anything else i want

**Comment by mourner** [comment]
It's not very clear what you're trying to accomplish from the short description, but I think you could use an SVG marker for drawing an arbitrary arc over a point. https://www.mapbox.com/mapbox-gl-js/api/#marker
