### ISSUE TITLE
Expose lower-level API for flattened/resolved layers

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#763]
The layers that mapbox-gl-js interacts with internally are flattened, remapped, merged from the stylesheet input. Applications that interact with the stylesheet need to be able to expect how this will work in some logical way, and not to re-implement the internals of mapbox-gl-js.

**Comment by jfirebaugh** [comment]
@tmcw Is there still a need here?

**Comment by lucaswoj** [comment]
@tmcw Would this need go away if we removed the idea of `ref`s from gl-js?

**Comment by tmcw** [comment]
For my usecase, there is no longer a need for this API: we un-resolve refs on the way in and resolve them on the way out, and treat the map's style object as a strictly write-only resource (we never use any `get` methods.

Happy to reopen if this need is clear for another usecase, but closing for now as unnecessary.
