### ISSUE TITLE
Invalidate style if layout/paint properties are not inside the layout/paint object

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#7630]
**style-spec version**: 13.4.0

### Steps to Trigger Behavior / Demonstration

[`gl-style-validate`](https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec#gl-style-validate) the following style:

```
{
    "version": 8,
    "sources": {
        "composite": {
            "url": "mapbox://mapbox.mapbox-streets-v7",
            "type": "vector"
        }
    },
    "layers": [
        {
            "id": "waterway",
            "type": "line",
            "source": "composite",
            "source-layer": "waterway",
            "layout": {},
            "line-cap": "round",
            "line-join": "round",
            "paint": {},
            "line-color": "hsl(249, 88%, 56%)",
            "line-width": 10
        }
    ]
}
```

### Expected Behavior

Style validation throws errors, because layout/paint properties are not located inside the layout/paint object.

### Actual Behavior

Style is validated.

**Comment by mourner** [comment]
Technically, this is just a layer with default layout/paint properties and some custom additional properties which are allowed — whether they match any existing layout/paint property names shouldn't matter, so I'm inclined to say this is a valid style.
