### ISSUE TITLE
Load Mapbox GL JS map after receiving window.onmessage

### ISSUE THREAD

**Issue by jnucc86** [mapbox/mapbox-gl-js#7635]
mapbox-gl-js version v0.49.0:

Hi Im trying to add an interactive map to my Wix site using Mapbox GL JS via an Iframe added to the page site.

The Wix iframe is not responsive, so as a work around I want to ask the site to send through it's window dimensions prior to loading the iframe map, which can be used to set the correct map dimensions.

I have been able to do the following:
1.  Get the current window dimensions
2. Send them as a window.onmessage event to Mapbox GL JS

My issue is that the map loads before this message is seen by the Mapbox script.  I believe this is an asynchronous javascript issue - I need to tell Mapbox GL JS to wait until it has received the dimensions prior to loading.  It would even be acceptable to have the page load, then once the dimensions are received just resize the canvas/map div.  But I havent been able to get it to work. I think I need to incorporate a promise function but I'm struggling.  I wouldn't consider myself a coder and I think I've reached my knowledge limit. 

Below is my javascript to load the map.  Any help would be appreciated:

```
<script>
mapboxgl.accessToken = 'pk.eyJ1Ijoiam51Y2MiLCJhIjoiY2pjdDBsMWlkMGMybDMzanlkM3IyNTZlbiJ9.WXJufnbOYIZiMHzP_1AW5w';
const map = new mapboxgl.Map({
  container: 'map',
  style: 'mapbox://styles/jnucc/cjocwj8xs3l872rpiuc8kaqcr?optimize=true',
  center: [145.568893, -37.489065],
  zoom: 8
})
;

var width = 0;
var height = 0;

window.onmessage = (event) => {
  if (event.data) {
      height = event.data[0];
      width = event.data[1];
      console.log(event.data)    // I can see this appear in the browser console
  }
}

map.on('load', function() {

  if (width > 0) {     // This doesnt work because width stays = 0
       document.getElementById('map').style.width = width;
       document.getElementById('map').style.height = height;
   }

});
</script>
```

**Comment by mourner** [comment]
What you can do instead is to simply resize the map in `onmessage` regardless if it's loaded or not:

```js
window.onmessage = (event) => {
  if (event.data) {
      map.style.height = event.data[0] + 'px';
      map.style.width = event.data[1] + 'px';
      map.resize(); // will adjust the map to the new size
  }
}
```

**Comment by jnucc86** [comment]
Hi mourner, thanks for the suggestion.  I havent been able to get this to work.  Looks like code works to change the map height and width (i've included code to change both the canvas and the div dimensions as per [this](https://gist.github.com/danswick/fc56f37c10d40be62e4feac5984250d2) example, but the map.on('loa') function seems to ignore this change and either overrides or doesnt see it.  I have put the window.onmessage event before the map.on function.

**Comment by mourner** [comment]
@jnucc86 this is not the place to get CSS help or app dev advice — it's the place to report GL JS issues. Unless you can provide a bug report with the provided form fully filled, including a minimal live example that demonstrates a Mapbox GL JS issue, we won't be able to help you.
