### ISSUE TITLE
symbol flickering related to wrapped tiles

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#7639]
Symbols occasionally flicker at the lowest zoom level, likely related to wrapping.

**mapbox-gl-js version**: master and v0.51

**browser**: chrome

### Steps to Trigger Behavior

 1. open https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/
 2. wait until it loads
 3. quickly zoom out to the lowest zoom

### Link to Demonstration

https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/

### Expected Behavior

no flickering

### Actual Behavior

flickering

---

cc @ChrisLoer 

I'm not marking this as a release blocker because it is not that significant and because it affects the previous version.

**Comment by ChrisLoer** [comment]
This looks like a pretty simple bug:

https://github.com/mapbox/mapbox-gl-js/blob/16a0c1de245e91a1a779829629d11945af560b51/src/source/tile_id.js#L94-L101

`isChildOf` doesn't account for wrap, so the cross tile symbol index picks up "child" tiles in different world copies. Looks like we have the same problem on native.

**Comment by ChrisLoer** [comment]
Fixed in #7644.
