### ISSUE TITLE
Setting Conditionals within Layer

### ISSUE THREAD

**Issue by Bestboat131** [mapbox/mapbox-gl-js#7646]
I have geojson data that has a property field called status which has 2 possible values: "selected" and "deselected".

I'm following the clustering feature example in the docs and can change the the color of the circle by using the match and status function. 
```
 const UnclusteredLayer = {
  id: "unclustered-point",
  type: "circle",
  source: "geoJsonSample",
  filter: ["!", ["has", "point_count"]],
  paint: {
    "circle-radius": 6,
    "circle-color": [
      "match",
      ["get", "status"],
      "selected",
      "green",
      "deselected",
      "red",
      "#ccc" //other
    ]
  }
};
```

If I'm converting this into a layer with symbols, can I use the same match function to change the icon image or do I need to create 2 layers with 2 separate geojson sources (1 with the selected properties and the other with deselected) to show a different icon image? I can't find an example in the documentation so I'm wondering what the syntax is for it. 

```
const UNCLUSTERED_LAYER = {
    filter: ["!", ["has", "point_count"]],
    id: "unclustered-point",
    source: "geoJsonSample",
    type: "symbol",
    layout: {
    "icon-image": "custom-marker2",
    "icon-allow-overlap": true,
    "icon-size": 0.06
  }

```

**Comment by ansis** [comment]
Yes, you should be able to use the same match function!
