### ISSUE TITLE
Setting the same value with setLayoutProperty triggers render event

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#7648]
**mapbox-gl-js version**:
0.51.0

**browser**:
Chrome

### Background

My application subscribes to the map's `render` event for many reasons, eg: showing a spinner while the map renders tiles/layers.

I notice we get flickers of a spinner when calling `setLayoutProperty` on a layer and passing the same value that's already in the layer.

### Steps to Trigger Behavior

 1. Call `setLayoutProperty` on a known, visible layer
 2. Set the visibility property to `visible`
 3. Set the visibility property to `visible` again

### Link to Demonstration
Click the "Test" button in this jsbin:
https://jsbin.com/faqupawuho/1/edit?console,output

### Expected Behavior

Calling `map.setLayoutProperty('some-layer', 'visibility', 'visible')` when the layer is already visible should be a no-op.

### Actual Behavior
Two `render` events fire (see console logs in the JSBin example)

**Comment by weiliang903** [comment]
same issue for me.
`this.map.setPaintProperty(this._rainfallId, 'raster-opacity', visible ? 0.6 : 0);`
 it's working

**Comment by mourner** [comment]
This was likely fixed by #7459. I'll reopen if it's not the case.
