### ISSUE TITLE
image requests that used to be queued can't be aborted

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#7650]
Image requests that are queued return a Cancelable object that only cancels the request if the request is still queued. Once the request has been unqueued it is not possible to abort the network request. Calling `cancel` at that point will do nothing.

https://github.com/mapbox/mapbox-gl-js/blob/16a0c1de245e91a1a779829629d11945af560b51/src/util/ajax.js#L186

@mourner I don't think this should block the beta because it is already in the previous version. should it block the final release?

**mapbox-gl-js version**: v0.50 and master

**browser**: all

### Steps to Trigger Behavior

 1. open http://localhost:9966/debug/satellite.html#7.85/58.009/-113.643 in large viewport to queue up image requests
 2. wait a bit so that some requests complete and queue requests start
 3. zoom quickly to abort requests

### Link to Demonstration

http://localhost:9966/debug/satellite.html#7.85/58.009/-113.643

### Expected Behavior

Requests for previously queued images abort.

### Actual Behavior

Requests for previously queued images do not abort.

**Comment by mourner** [comment]
It's not critical but may affect performance, so I'd cherry-pick the fix into beta if there's time. Submitted a potential fix in #7655.
