### ISSUE TITLE
Large number of raster layers

### ISSUE THREAD

**Issue by Xeenych** [mapbox/mapbox-gl-js#7660]
I have a map with 25 raster layers, added as mapbox tilesets via mapbox://something.....
Layers mostly do not overlap.
Every time the map is scrolled or zoomed MapBox tries to fetch every layer, which imapcts map performance.
MapBox should respect BBOX of raster layers and should not try to load ever one of it.

**Comment by asheemmamoowala** [comment]
@Xeenych Thank you for using Mapbox! The gl-js library supports the TileJSON `bounds` property and limits loading tiles outside of the defined bounds for a source. 

If you are seeing an error, please provide a minimal demonstration of the bug. We recommend using https://jsbin.com.

**Comment by Xeenych** [comment]
Here it is
https://jsbin.com/coxurazuxi/edit?html,output

There are two raster sheets added using mapbox tilesets.

Each time you move the map mapbox-gl sends tons of requests to mapbox to query tiles. Even if you are viewing a region out of layer's extents.

So, if there are e.g. 10 layers, mapbox-gl will send request to query every layer.

**Comment by asheemmamoowala** [comment]
@Xeenych In your example the raster sources do not have the bounding box specified. Use the [`bounds`](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-raster-bounds) property of the source to specify the bounding box to constrain tile requests.
