### ISSUE TITLE
Studio Map won't render in Edge 2018 Release

### ISSUE THREAD

**Issue by stegel** [mapbox/mapbox-gl-js#7671]
**mapbox-gl-js version**: 0.51.0

**browser**: Microsoft Edge October 2018 (
Microsoft Edge 44.17763.1.0, Microsoft EdgeHTML 18.17763, and Microsoft Windows Version 10.0.17763 Build 17763.

### Steps to Trigger Behavior

 1. Go to https://jsbin.com/yakopis/edit?html,js,output in Chrome
 2. Map renders okay
 3. Go to https://jsbin.com/yakopis/edit?html,js,output in Edge
 4. Unable to render map fully.

### Link to Demonstration
https://jsbin.com/yakopis/edit?html,js,output

### Expected Behavior
Map would work the same in Edge as other browsers

### Actual Behavior
Map is nonfunctional in Edge Oct 2018.
![edgeerror](https://user-images.githubusercontent.com/106086/49487873-5ab96780-f812-11e8-9c4f-611cf53e8a2d.png)

**Comment by stegel** [comment]
Any suggestions of what I can do in the mean time?

**Comment by ansis** [comment]
@stegel I can't think of any workarounds but we plan to release a new version on wednesday this week. Or if you are willing to build mapbox-gl-js yourself you could disable [webp detection](https://github.com/mapbox/mapbox-gl-js/blob/7ddbfa2d374d1bab63abbb6ec405ba751895164e/src/util/browser.js#L61-L64) and build a version for yourself.

**Comment by stegel** [comment]
I'll wait til weds! Thanks

**Comment by ansis** [comment]
@asheemmamoowala do you have any thoughts on how best to handle this?

It looks like it is not possible to pass a webp image to gl.texImage2D(...). Several possibilities:
- detect edge and disable webp in edge
- when detecting webp support try adding it to a texture and see if it throws (this means a gl context is necessary for detection)
- catch the error and use `browser.getImageData(...)` before `gl.texImage2D(...)` which works but is slower

**Comment by asheemmamoowala** [comment]
@ansis I've added to an issue logged on the [Edge issues forum](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/19221241/).

> - detect edge and disable webp in edge

I think this is the best strategy until the issue is fixed. Image and Raster sources both would perform very poorly with either of the other options.

> - when detecting webp support try adding it to a texture and see if it throws (this means a gl context is necessary for detection)
> - catch the error and use browser.getImageData(...) before gl.texImage2D(...) which works but is slower

Is the performance with `browser.getImageData()` acceptable, and does it continue to support transparency ? I don't see the advantage of adding this support temporarily

**Comment by stegel** [comment]
When does this end up in the version hosted on the cdn? I compiled locally
for now.

**Comment by ansis** [comment]
@stegel on wednesday we'll release the final version of 0.52. A beta with this fix has already been released https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0-beta.2/mapbox-gl.js
