### ISSUE TITLE
Is there any way to use feature properties in custom function by expression?

### ISSUE THREAD

**Issue by dythbj** [mapbox/mapbox-gl-js#7684]
## Motivation

I have a vectorTile source layer named buildings, the layer has properties A, B and C, as we know in expression, we can get the properties by ["let", "pro_a", ["get", "A"] ], then we can use "pro_a" in expression like this:
```
                 [
                        "interpolate",
                        ["linear"],
                        ["var", "pro_a"],
                        274,
                        ["to-color", "#edf8e9"],
                        1551,
                        ["to-color", "#006d2c"]
                   ]
```

but the property A is not exhaustion, and my willing is much more complicated, so  is there anyway ,that i can use the properties like this:
```
                   [
                        "interpolate",
                        ["linear"],
                        1,
                        1, ["literal", customFuction(["var", "pro_a"], ["var", "pro_b"])]
                   ]
```
or like this:
```
                  [
                        "interpolate",
                        ["linear"],
                        1,
                        1, ["literal", customFuction(["get", "A"], ["get", "B"])]
                   ]
```

"customFuction" is my own defined function.

hope for you helps, thanks!

**Comment by ansis** [comment]
If I'm understanding your question correctly you are asking whether it is possible to define your own expression function? It is currently not possible to define a new expression function or have expressions call javascript functions.

**Comment by ansis** [comment]
Yep, unfortunately we can't support that right now. Sorry!

**Comment by gideongrossmanHome** [comment]
And now? If not, is there a workaround?

**Comment by gideongrossmanHome** [comment]
@dythbj  Did you ever figure out a solution to this? I have the same need - for a coloring a choropleth map. Thanks for any insight! - Gideon

**Comment by dythbj** [comment]
Noop, Mapbox expression dose not support this, sorry!


 原始邮件 
发件人: gideongrossmanHome<notifications@github.com>
收件人: mapbox/mapbox-gl-js<mapbox-gl-js@noreply.github.com>
抄送: dythbj<gaojie@dyth.tech>; Mention<mention@noreply.github.com>
发送时间: 2020年5月1日(周五) 16:08
主题: Re: [mapbox/mapbox-gl-js] Is there any way to use feature propertiesin custom function by expression? (#7684)


@dythbj Did you ever figure out a solution to this? I have the same need - for a coloring a choropleth map. Thanks for any insight! - Gideon

**Comment by gideongrossmanHome** [comment]
It is in fact possible. I got it working.  Use the “match” expression.

**Comment by morandd** [comment]
@gideongrossmanHome  can you provide a snippet showing your solution?
