### ISSUE TITLE
clarify `geometry-type` expression behavior for vector tile sources

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mapbox-gl-js#7699]
## Problem

The documentation for `geometry-type` in the spec (https://github.com/mapbox/mapbox-gl-js/blob/64ebdda0bc527c837263bb8f64685d53abcd7d37/src/style-spec/reference/v8.json#L2738) could clarify which property types will be available for which source types. Current copy is:

> Gets the feature's geometry type: Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon.

Based on a quick experiment, it doesn't appear like the `geometry-type` expression ever returns a multi* feature when applied to a vector tile source. 

## Suggestion

There's likely more nuance going on here than I'm aware of – in which case, the appropriate explanation in the appropriate place would solve this issue better than anything I can come up with. Here are some suggestions based on what I know:

- Add a sentence to the spec documentation, something like: "Multi* feature types will only be detectable in GeoJSON sources, use the singular forms when working with vector tile sources".
- Change the behavior of `geometry-type` to return true for multi-features in both vector tile and GeoJSON source types.

**Comment by mourner** [comment]
I wonder whether it makes sense to differentiate between Multi and Single geometries in the context of a Mapbox style — perhaps we should do the other way around and fix GeoJSON to return `Polygon`/`Line`/`Point` for single geometries as well?

It's definitely a design omission — we should have thought this out to be consistent. The only problem with fixing this is that it's a breaking change, so perhaps updating the docs would be an easier first step, assuming a follow-up.

**Comment by chloekraw** [comment]
cc @zmiao @alexshalamov @tmpsantos @pozdnyakov

**Comment by SnailBones** [comment]
@HeyStenson's commit provides the documentation fix. 

Added to #6584 so we can revisit the breaking change in the next style spec version.
