### ISSUE TITLE
How to send WMS feature request

### ISSUE THREAD

**Issue by shrikantkunte** [mapbox/mapbox-gl-js#7714]
In my app I want to send a feature request to WMS server. In openlayer I found a solution 
```
MyLayer.getSource()
                .getGetFeatureInfoUrl(
                    evt.coordinate,
		     map.getView().getResolution(),
		     map.getView().getProjection(),	
			{
			 'INFO_FORMAT': 'application/json',
			'propertyName': 'OBJECTID,HOUSE_NUM'
			}
		);
```
This creates an URL of feature request. Is there any alternative method for "getGetFeatureInfoUrl" in mapbox-gl. Example will be very helpful.

**Comment by asheemmamoowala** [comment]
Mapbox-gl-js doesn't provide this type of WMS support. 

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by kancharla-sandeep** [comment]
> In my app I want to send a feature request to WMS server. In openlayer I found a solution
> 
> ```
> MyLayer.getSource()
>                 .getGetFeatureInfoUrl(
>                     evt.coordinate,
> 		     map.getView().getResolution(),
> 		     map.getView().getProjection(),	
> 			{
> 			 'INFO_FORMAT': 'application/json',
> 			'propertyName': 'OBJECTID,HOUSE_NUM'
> 			}
> 		);
> ```
> 
> This creates an URL of feature request. Is there any alternative method for "getGetFeatureInfoUrl" in mapbox-gl. Example will be very helpful.

Did you find any way

**Comment by jingsam** [comment]
By providing a url to a WMS server that supports EPSG:3857 (or EPSG:900913) as a source of tiled data. The server url should contain a "{bbox-epsg-3857}"replacement token to supply the bbox parameter.

```
"wms-imagery": {
    "type": "raster",
    "tiles": [
    'http://a.example.com/wms?bbox={bbox-epsg-3857}&format=image/png&service=WMS&version=1.1.1&request=GetMap&srs=EPSG:3857&width=256&height=256&layers=example'
    ],
    "tileSize": 256
}
```
