### ISSUE TITLE
Multipe Marker mapboxgl ionic

### ISSUE THREAD

**Issue by Matthis2909** [mapbox/mapbox-gl-js#7718]
Is it possible to loop for create Marker with mapboxgl ?

buildMap() {
  console.log(this.lng, this.lat);
    this.map = new mapboxgl.Map({
        container: 'map',
        style: this.style,
        zoom: 16,
        center: [this.lng, this.lat]
    });

        var elCreature = document.createElement('div');
        elCreature.className = 'icon-creature alpaca';
        elCreature.addEventListener('click',  (e:Event) => this.showToastWithCloseButton());

        var markerCreature = new mapboxgl.Marker(elCreature, {offset: [-20, -20]})
            .setLngLat([this.lng, this.lat])
            .addTo(this.map);

}

Work for one marker. I try for loop but none is displayed

**Comment by ansis** [comment]
@Matthis2909 thanks for using mapbox-gl-js. Can you please provide all the information asked for by the bug report template? Unfortunately we can't debug issues without it. Specifically, 

> Providing a minimal, complete, verifiable demonstration. (See https://stackoverflow.com/help/mcve for guidelines on creating an effective example.)
>
> https://jsbin.com/

**Comment by enrico-lombardo** [comment]
Hi Ansis,

I am writing to you as I am a bit desperate. I'm absolutely not programming expert. I'll explain my problem: I need to insert the timestamp in a video generated on Mapbox. Can I show you the code? I'm going crazy.


/* global document, fetch, window */
import React, {Component} from 'react';
import {render} from 'react-dom';
import MapGL from 'react-map-gl';
import DeckGLOverlay from './deckgl-overlay.js';

// Set your mapbox token here
const MAPBOX_TOKEN = 'pk.eyJ1IjoiZW5yaWNvLWxvbWJhcmRvIiwiYSI6ImNqanBncWhiZDJrNmoza21kMW1kYm5jbjUifQ.lp2Ly3emN4kX3Dr2zs46SQ' ; // eslint-disable-line

// Funzione per estrarre i parametri GET dall'url
function findGetParameter(parameterName) {
    var result = null,
        tmp = [];
    location.search
        .substr(1)
        .split("&")
        .forEach(function (item) {
          tmp = item.split("=");
          if (tmp[0] === parameterName) result = decodeURIComponent(tmp[1]);
        });
    return result;
}

// Oggetto per mostrare il timestamp
export default class Counter extends Component {

  render() {
    const {time, date_start, date_end} = this.props;
    let timestamp = moment(date_start).add(parseInt(time), 'minutes').format("DD-MM-YYYY HH:mm:ss")

    if(moment(date_start).add(parseInt(time), 'minutes') > moment(date_end)){
      timestamp = moment(date_end).format("DD-MM-YYYY HH:mm:ss")
    }
    var h1Style = {
      color: 'white'
    };

    return (
      <h1 style={h1Style}>{timestamp}</h1>
    );
  }
}

// Source data CSV
const DATA_URL = {
  BUILDINGS:
    'https://raw.githubusercontent.com/uber-common/deck.gl-data/master/examples/trips/buildings.json', // eslint-disable-line
  TRIPS:
    './22o.json' // eslint-disable-line
};

class Root extends Component {
  constructor(props) {
    super(props);
    this.state = {
      viewport: {
        ...DeckGLOverlay.defaultViewport,
        width: 500,
        height: 500
      },
      buildings: null,
      trips: null,
      time: 0
    };
    
	// Parametri del GET. Se non ci sono vengono forzati automaticamente

    let param_snap = findGetParameter('snap')

    let param_date = findGetParameter('date')
    let param_min_time = findGetParameter('min_time')
    let param_max_time = findGetParameter('max_time')
    let param_min_lat = findGetParameter('min_lat')
    let param_min_long = findGetParameter('min_long')
    let param_max_lat = findGetParameter('max_lat')
    let param_max_long = findGetParameter('max_long')
		
		
    fetch(DATA_URL.BUILDINGS)
      .then(resp => resp.json())
      .then(data => this.setState({buildings: data}));

    fetch(DATA_URL.TRIPS)
      .then(resp => resp.json())
      .then(data => this.setState({trips: data}));
  }

  componentDidMount() {
    window.addEventListener('resize', this._resize.bind(this));
    this._resize();
    this._animate();
  }

  componentWillUnmount() {
    if (this._animationFrame) {
      window.cancelAnimationFrame(this._animationFrame);
    }
  }

  _animate() {
    this.setState({
      // Ogni frame (30 o 60 al secondo) aumento il tempo di 1/5. time corrisponde ai minuti (vedi componente COUNTER)
      time: this.state.time + 1/5
    });
    this._animationFrame = window.requestAnimationFrame(this._animate.bind(this));
  }

  _resize() {
    this._onViewportChange({
      width: window.innerWidth,
      height: window.innerHeight
    });
  }

  _onViewportChange(viewport) {
    this.setState({
      viewport: {...this.state.viewport, ...viewport}
    });
  }

  render() {
    const {viewport, buildings, trips, time} = this.state;

    return (
      <MapGL
        {...viewport}
        mapStyle="mapbox://styles/mapbox/streets-v9"
        onViewportChange={this._onViewportChange.bind(this)}
        mapboxApiAccessToken={MAPBOX_TOKEN}
      >
		
        <DeckGLOverlay
          viewport={viewport}
          buildings={buildings}
          trips={trips}
          trailLength={20}
          time={time}
        />
      </MapGL>
    );
  }
}

render(<Root />, document.body.appendChild(document.createElement('div')));

**Comment by ansis** [comment]
@enrico-lombardo  – thank you for using Mapbox! This issue tracker is for bug reports and feature requests. I suggest you ask your questions on [StackOverflow](https://stackoverflow.com/tags/mapbox-gl-js) if you have a general programming question or contact [Mapbox support](www.mapbox.com/help) if you have a question about using mapbox-gl. Thanks!
