### ISSUE TITLE
Filter ["all",["==",["geometry-type"],"Polygon"],["!",["has","lp"]]] is prohibited by validation

### ISSUE THREAD

**Issue by gorshkov-leonid** [mapbox/mapbox-gl-js#7730]
**mapbox-gl-js version**:
0.51.0

**browser**:
all

**Description**:
We used filter ` ["all",["==","$type","Polygon"],["!has","lp"]]` it worked. But when this filter was wrapped by another filter some error threw. As I understand we are using deprecated syntax and it is root cause.

I tried to fix filter to `["all",["==","$type","Polygon"],["!",["has","lp"]]]` and got error 
`expected [==, !=, >, >=, <, <=, in, !in, all, any, none, has, !has], "!" found`

You can say that this expression is using deprecated syntax `["==","$type","Polygon"]`. Ok I changed it to `["all",["==",["get","$type"],"Polygon"],["!",["has","lp"]]] ` and got error 
` string expected, array found` (it is about `["get","$type"]`).

You can say that this expression is using deprecated syntax $type. Ok I tried to use "geometry-type", but got  error again

![image](https://user-images.githubusercontent.com/2270831/50475002-83c9b400-09dc-11e9-81ec-9afd84672c30.png)

I tried also 
`["all",["match",["geometry-type"],["Polygon"],true,false],["!",["has","lp"]]]` as in [test in feature_filter.test.js](https://github.com/mapbox/mapbox-gl-js/blob/7ddbfa2d374d1bab63abbb6ec405ba751895164e/test/unit/style-spec/feature_filter.test.js#L123) but got error  `expected one of [==, !=, >, >=, <, <=, in, !in, all, any, none, has, !has], "match" found`

It looks like [test in feature_filter.test.js](https://github.com/mapbox/mapbox-gl-js/blob/7ddbfa2d374d1bab63abbb6ec405ba751895164e/test/unit/style-spec/feature_filter.test.js#L123) and [comment](https://github.com/mapbox/mapbox-gl-js/issues/6508#issuecomment-380842379)
 
**Could you say me, is it a bug?** 
I read documentation about "get", "has", "!", "==", "all", "geometry-type". Last expression seems correct, but It does not work:
```
["all",["==",["geometry-type"],"Polygon"],["!",["has","lp"]]]
``` 
Is it related to #7699, #7679 ?

**Comment by mourner** [comment]
Can you please set up a minimal test case (e.g. on JSFiddle) reproducing the issue?

**Comment by gorshkov-leonid** [comment]
Hello @mourner. Sorry for bother.  I did not reproduce an error. May be I got wrong with this expression. I tried to debug with only breakpoint in constructor of ValidationError. So first error occured by filter expression `["all",["==",["geometry-type"],"LineString"],["any",["==","sp","_"],["all",["!has","sp"],["any",["!has","sp"],["==","sp","_"]]]]]` (https://jsfiddle.net/goleon/sj40agth/) . Hm `!has`  is deprecated too. 

I tried to fix expression: `["all",["==",["geometry-type"],"LineString"],["any",["==","sp","_"],["all",["!",["has","sp"]],["any",["!",["has","sp"]],["==","sp","_"]]]]]` but got errors `string expected, array found`, `expected one of [==, !=, >, >=, <, <=, in, !in, all, any, none, has, !has], "!" found` (https://jsfiddle.net/goleon/nup8gL9q/)

**Comment by gorshkov-leonid** [comment]
Any updates?

**Comment by gorshkov-leonid** [comment]
Hello @mourner, do you have any news. Did you accept these things as bugs?

**Comment by mourner** [comment]
I've looked through all the examples and I think you're just mixing legacy filter syntax and the new expression syntax in all of them. In the case of the last "not working" examples, the culprit is `["==","sp","_"]` — since you're comparing two literal strings (and not e.g. `["==", ["get", "sp"], "_"]`), GL JS thinks this is a legacy filter, but then fails to parse it because it has things from the expression system (such as `["geometry-type"]`).

**Comment by TannerPerrien** [comment]
I just stumbled upon this trying to figure out why certain combinations of expressions weren't working. Is there any documentation that outlines legacy vs non-legacy? I looked in the docs for this but ended up not finding anything.
