### ISSUE TITLE
Map tiles aren't rendering in headless chrome (via TestCafe)

### ISSUE THREAD

**Issue by adimakis** [mapbox/mapbox-gl-js#7733]
**mapbox-gl-js version**: latest

**browser**: Headless Chrome 71.0.3578 / Windows 10.0.0

**testcafe**: 0.23.3

**node**: 8.12.0

### Description
Map tiles are not rendered in latest headless Chrome v71.0.3578 so screenshots taken from TestCafe are incorrect. The exact same code was working with headless Chrome v70.0.3538.110.

### Steps to Trigger Behavior
 1. Install latest [TestCafe](https://devexpress.github.io/testcafe/documentation/using-testcafe/installing-testcafe.html) and latest Chrome.
 2. Save the following script in a file (e.g. mapTakeElementScreenshot.js)
```
import { Selector } from "testcafe"

fixture`Test mapbox`
  .page `https://www.mapbox.com/mapbox-gl-js/example/simple-map/`
  .beforeEach(async t => {})

  test("take screenshot", async t => {
    await t.wait(10000)
    const map = Selector("#demo")
    await t.takeElementScreenshot(map, "test_mapbox.png")
  })
```
3. Run test in headless mode to create the image snapshot
`testcafe chrome:headless .\mapTakeElementScreenshot.js -e -s "./"`
4. Run test in normal mode to create the expected image snapshot
`testcafe chrome .\mapTakeElementScreenshot.js -e -s "./"`

### Link to Demonstration

Run test as described in previous section to get the image snapshots below.

### Expected Behavior
Correct screenshot (taken with headless Chrome v70.0.3538.110):  

![image](https://user-images.githubusercontent.com/869847/50519179-5fe09e00-0ac2-11e9-9e71-7661a6881835.png)

### Actual Behavior
Screenshot taken with headless Chrome v71.0.3578:

![image](https://user-images.githubusercontent.com/869847/50519210-7d156c80-0ac2-11e9-8a87-752ec3de7e5d.png)

**Comment by mourner** [comment]
Are you sure this is a Mapbox GL JS issue and not one with the setup (TestCafe / headless-chrome / etc.?). Does headless Chrome output anything in the console? Can you make sure the GPU is turned on in the environment?

**Comment by andrewharvey** [comment]
also check out https://github.com/mapbox/mapbox-gl-js/issues/7721

I ran into the same background only map you're seeing and it went away when I swapped between chrome, chrome beta, and chrome dev.

**Comment by mourner** [comment]
Awesome, thanks for the update! Closing.
