### ISSUE TITLE
Cannot disable two-finger dragPan by dragPan.disable()

### ISSUE THREAD

**Issue by cs09g** [mapbox/mapbox-gl-js#7737]
**mapbox-gl-js version**:
v0.50.0

**browser**:
Android Chrome 71.0.3578.99

### Steps to Trigger Behavior

 1. create map
```javascript
map = new mapboxgl.Map({
    container: "map",
    center: [lng, lat],
    zoom: zoom,
    style: styleJSON,
});
```
 2. disable dragPan
`map.dragPan.disable();`

 3. try two-finger dragging on mobile device

### Link to Demonstration
https://codepen.io/anon/pen/gZogGZ

### Expected Behavior
shouldn't be draggable

### Actual Behavior
still draggable

#2618 
it was working as expected with v0.12.2 but v0.50.0
https://codepen.io/mapbox/pen/rxwpVx

**Comment by mourner** [comment]
The `dragPan` handler is only responsible for single-point panning such as by mouse or one finger. Try doing `map.touchZoomRotate.disable();` to disable two-finger interaction.

**Comment by cs09g** [comment]
@mourner Doesn't it about feature required for touchPan? `map.touchZoomRotate` handles zoom and rotate.
