### ISSUE TITLE
boxZoomBounds no longer available in boxzoomend event

### ISSUE THREAD

**Issue by itsmequinn** [mapbox/mapbox-gl-js#7739]
Release v0.49.0 removed the boxZoomBounds from booxzoomend events but the documentation for boxzoomend still says that a boxZoomBounds should be available as part of that event's data.

**mapbox-gl-js version**: v0.49.0 and later

**browser**: Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Load a mapbox gl js map
 2. Shift and click+drag to trigger a boxzoomend event
 3. Observe the event's data and see that it only contains originalEvent, target and type properties

### Expected Behavior
bozZoomBounds should contain the bounds of the map after zooming
### Actual Behavior
boxZoomBounds does not exist

**Comment by ryanhamley** [comment]
Closed by #7741
