### ISSUE TITLE
map.remove() does not remove Popups

### ISSUE THREAD

**Issue by davidgilbertson** [mapbox/mapbox-gl-js#7744]
**mapbox-gl-js version**: 0.52.0

**browser**: Chrome 71

### Steps to Trigger Behavior

 1. Render a map
 2. Add a `new Popup`
 3. Call `map.remove()`

### Expected Behavior
The popup should be removed

### Actual Behavior
The popup remains behind even after the map is removed.

----

Seems like `map.remove()` is removing the `mapboxgl-canvas-container` div and the `mapboxgl-control-container` div and some other things, but missing the `mapboxgl-popup` div, which is a sibling to `mapboxgl-canvas-container` (and of course it's not just the div...)

For a workaround, I'm tracking and manually removing any popups that I add with `popup.remove()`

**Comment by ryanhamley** [comment]
Thanks for reporting this! I can confirm with a minimal repro [here](https://jsbin.com/vosacuq/edit?html,output).

**Comment by davidgilbertson** [comment]
Thanks for doing the repro for me, I was in a rush when I logged this yesterday.

**Comment by davidgilbertson** [comment]
That was fast, thanks @andycalder! Any idea when this will be available in a prod release?

**Comment by ryanhamley** [comment]
@davidgilbertson Our next release will be a beta that's scheduled for January 23rd with the final release a week later on the 30th. You can use the `master` branch until then if you need this functionality ASAP.

**Comment by davidgilbertson** [comment]
That's excellent, thanks. I'm in no rush.
