### ISSUE TITLE
Missing margin on compact attribution control when minimized

### ISSUE THREAD

**Issue by eftas-gka** [mapbox/mapbox-gl-js#7745]
**mapbox-gl-js version**: 0.52

**browser**: Chrome

### Steps to Trigger Behavior

 1. Create map with geolocate control in bottom-right position
 2. Margin of compact attribution control differs between minimized and maximized state

### Possible Solution

Solved by setting a fixed height of 20px to the containing div (.mapboxgl-ctrl.mapboxgl-ctrl-attrib.mapboxgl-compact).

**Comment by ryanhamley** [comment]
Closed by #7831
