### ISSUE TITLE
[docs] Bump examples from streets-v9 to streets-v11

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#7753]
Many of our examples, including some in prominent places such as the "quickstart", are still using `streets-v9`. We should move to `streets-v11` because:

- `streets-v9` uses less-legible/uglier "pitched" street labels because of a technical limitation we no longer have. Our examples will look better with `streets-v11`
- Our users will frequently start their projects using our example code, and using `streets-v9` means they'll be working with an older data source and they won't have the styling improvements we've made.

Quick search shows 67 places we uses the `streets-v9` URL -- almost all of them should be switched. It _should_ be a simple find/replace, but we'll want to at least briefly check the examples to make sure they're not broken by the change.

cc @katydecorah @ryanhamley

**Comment by katydecorah** [comment]
cc @mapbox/docs maybe we could roll this into https://github.com/mapbox/mapbox-gl-js/pull/7530

**Comment by HeyStenson** [comment]
> maybe we could roll this into #7530

Good thinkin' @katydecorah! 💪

**Comment by colleenmcginnis** [comment]
Fixed in https://github.com/mapbox/mapbox-gl-js/pull/8056 🎉
