### ISSUE TITLE
Style Expression [feature-state] cause 'The feature id parameter must be provided and non-negative.'

### ISSUE THREAD

**Issue by ParryQiu** [mapbox/mapbox-gl-js#7758]
**mapbox-gl-js version**: 0.52.0

#### **constructor the features:**

```
features.push({
          type: 'Feature',
          id: item.areaId,
          geometry: {
            type: 'Polygon',
            coordinates: [dataArray],
          },
          ......
```

#### **add layer's paint expression:**

```
'fill-color': ['get', 'color'],
'fill-opacity': ['case',
    ['boolean', ['feature-state', 'hover'], false],
        0.8,
        0.5
]
```

style expression `feature-state` cause the following exception.
any way to set the feature id in expression?
mapbox-gl-js v0.47.0 works well.

> Error: The feature id parameter must be provided and non-negative.
>     at i.setFeatureState (mapbox-gl.js:33)
>     at Map.r.setFeatureState (mapbox-gl.js:33)
>     at Map.<anonymous> (map.polygon.ts:89)
>     at Map.delegates.r.(:4200/anonymous function) (http://localhost:4200/vendor.js:16905:272500)
>     at Map.ht.fire (mapbox-gl.js:29)
>     at Map.map.fire (setup.js:51)
>     at HTMLDivElement.<anonymous> (mapbox-gl.js:33)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
>     at Object.onInvokeTask (core.js:3811)
>     at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)

**Comment by mourner** [comment]
We can't diagnose the issue since you didn't provide a minimal live example. My guess based on the cited error is that `id` of features you use isn't a non-negative number.

**Comment by Disorrder** [comment]
@mourner does it mean I can't use string ids? Only numbers?

**Comment by asheemmamoowala** [comment]
String ids will only work for features if they are convertible to integers. eg: `"1234"`

**Comment by torkjellt** [comment]
Did you find a solution for this?

**Comment by brambow** [comment]
I'm getting this error, but my feature id does exist and is not negative:

![image](https://user-images.githubusercontent.com/6227786/63535633-eb8abd00-c4df-11e9-80b8-90cf764ab63c.png)

**Comment by brambow** [comment]
I'm getting this error, but my features definitely have an id and it's not negative:

![image](https://user-images.githubusercontent.com/6227786/63535902-8e433b80-c4e0-11e9-8bdc-e95e6598b8e7.png)

**Comment by ParryQiu** [comment]
> Did you find a solution for this?
`id` must be a non-negative number.

**Comment by vgoklani** [comment]
bump
