### ISSUE TITLE
Simple way to set "everything" or "nothing" filter

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#7759]
## Motivation

Two situations that often arise for me:

1. I create a 'highlight' layer using a filter, but currently nothing is selected, so I create a nonsense filter to select nothing: `filter: ['==', 'id', -999]`
2. I have applied a filter chosen by the user, now I want to remove that restriction, so I set a filter that selects everything: `map.setFilter('mylayer', ['>=', 'id', 0])`

Both of these methods seem really hacky and inelegant.

### Options for selecting nothing

1. `filter: [false]`,
2. `map.setFilter(false)`

### Options for selecting everything

1. `filter: null`
2. `filter: []`
3. `filter: [true]`
4. `map.clearFilter()`
5. `map.setFilter(true)`

I'm a bit surprised that `[false]` and `[true]` don't work already.

**Comment by mourner** [comment]
Currently `map.setFilter(layerId, null)` clears the filter (meaning "select everything"), which fits our API convention for clearing the state for other methods.

To "select nothing", you can do `map.setFilter(layerId, false)`. `false` is a valid expression, you shouldn't wrap it with an array (the latter is only for special values like `["zoom"]`).

**Comment by stevage** [comment]
Interesting, thanks. Could have sworn I tried `map.setFilter(layerId)` (ie, passing `undefined`), which also works.
