### ISSUE TITLE
Lines taper off when stroking polygons 

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#776]
Top edges only:

![screen shot 2014-10-15 at 11 14 38 am](https://cloud.githubusercontent.com/assets/4551508/4650869/433728cc-5497-11e4-9ca9-704265281d75.png)

**Comment by ansis** [comment]
@mourner [that](https://cloud.githubusercontent.com/assets/25395/5351748/fe173e6e-7f28-11e4-93e0-d8806fee6048.png) looks like it could be a different issue. If you see it again, can you open an issue with the specific feature

**Comment by peterqliu** [comment]
@ansis also possibly related: https://github.com/mapbox/auto/issues/54
