### ISSUE TITLE
Can style expressions of 'match' be more efficient?

### ISSUE THREAD

**Issue by dythbj** [mapbox/mapbox-gl-js#7762]
Hi all:
  I have a vectorTile source layer named buildings, there are about 60000 features in it.I render the layer by 'fill-extrusion' type, and it looks like this:
![image](https://user-images.githubusercontent.com/41282663/51013624-90363b00-159e-11e9-8f91-9e8c3249b0d3.png)
  
  Now, i want change the 'fill-extrusion-color',  so i do it like this:
  
![image](https://user-images.githubusercontent.com/41282663/51013905-11da9880-15a0-11e9-8875-af896583f906.png)

  and use this function like this:
![image](https://user-images.githubusercontent.com/41282663/51013937-4ea68f80-15a0-11e9-877d-61580e075338.png)

 The render process is like this(sorry that i don't know how to upload an video, so i intercepted some fragments of my video):
![image](https://user-images.githubusercontent.com/41282663/51014236-8104bc80-15a1-11e9-8a06-fa29d0e29700.png)
![image](https://user-images.githubusercontent.com/41282663/51014246-924dc900-15a1-11e9-8815-07d956d6bcec.png)
![image](https://user-images.githubusercontent.com/41282663/51014253-9f6ab800-15a1-11e9-9f75-aa4fda975ce2.png)
![image](https://user-images.githubusercontent.com/41282663/51014259-ae516a80-15a1-11e9-934f-b5b090e93633.png)

  as we see, the process is not smooth and efficient(very bad)...
  so, my question is that this style expression of 'match' can be more efficient？or is there other way to realize my goal ? Thanks!

  Note：i have read [this](https://github.com/mapbox/mapbox-gl-js/issues/6082) , but the property i used in the expression ->"ID" is a string type field, so that i can't use 'Property functions' as well.

**Comment by mourner** [comment]
Expressions consisting of 60,000 subexpressions will certainly be slow. You'll have to come up with a way to set up `fill-extrusion-color` expression in an analytical way (e.g. some kind of formula based on the properties, not a big lookup). I'm not familiar with your data/use case, and you might need to add more properties to the data for this, but I don't think we can do anything on GL JS side to help here. Closing this as a support question.

**Comment by dythbj** [comment]
> Expressions consisting of 60,000 subexpressions will certainly be slow. You'll have to come up with a way to set up `fill-extrusion-color` expression in an analytical way (e.g. some kind of formula based on the properties, not a big lookup). I'm not familiar with your data/use case, and you might need to add more properties to the data for this, but I don't think we can do anything on GL JS side to help here. Closing this as a support question.

Thanks at all ! You are right, that the key is "a big lookup", i will try other options,maybe use a geojson source, and fill my data's to the feature properties, then i can render by the peoperties.

Thanks @mourner

**Comment by asheemmamoowala** [comment]
@dythbj You could also use the `feature-state` expression along with `Map#setFeatureState` API to set the color property using external data.

See an example of this technique here: https://bl.ocks.org/ryanbaumann/733ba99c5ca1d9d15259081b395e4b00/414e974f854c20c263edddc6c9cc934d0956a9ac

**Comment by dythbj** [comment]
> @dythbj You could also use the `feature-state` expression along with `Map#setFeatureState` API to set the color property using external data.
> 
> See an example of this technique here: https://bl.ocks.org/ryanbaumann/733ba99c5ca1d9d15259081b395e4b00/414e974f854c20c263edddc6c9cc934d0956a9ac

Thanks asheem, but my use case is a bunch of random numbers, the "featurestate" may not be able to cover all my case.

**Comment by dythbj** [comment]
> @dythbj You could also use the `feature-state` expression along with `Map#setFeatureState` API to set the color property using external data.
> 
> See an example of this technique here: https://bl.ocks.org/ryanbaumann/733ba99c5ca1d9d15259081b395e4b00/414e974f854c20c263edddc6c9cc934d0956a9ac

Hi  @mourner ,  @asheemmamoowala :
   I tried another way to achieve this, i convert my data to geojson, and when my calaulate is done,
   my calaulate result is an array of numbers like this **on each building**:
   [0, 0.00230345,........,0.0324432]
   Each array is about 2K of numbers in it.
   Then i add the array to the feature's properties like this:
    {"type": "Feature",
      "properties": {
          "id": 1,
          "floor": 4,
          //the array values
          "u0": 0,
          "u1": 0.00230345,
          .
          .
          .
          .
          .
          "u2343": 0.0324432
          //the array values
      }
   }

   Then i add the geojson source layer by  'fill-extrusion' type, and i change the 'fill-extrusion-color' by the expression like this:
   _self.map.setPaintProperty('analyse_polygon', 'fill-extrusion-color', ["interpolate", ["linear"],
                      ["get", "u" + index],
                        0, "blue",
                        1.2, "royalblue",
                        2.4, "cyan",
                        4.2, "lime",
                        5.2, "yellow",
                        6.2, "red"]
                  );
   The index is 0,1,2.....and so on.

   The result is:
   1) The render process is a little efficient
   2) The problem is the more properties i add to each feature, the more slow render process for the fill-extrusion layer(even out of memory)
    So, The result is a failure by this way.
