### ISSUE TITLE
Edges of large heatmap blobs are slightly clipped

### ISSUE THREAD

**Issue by alibabzo** [mapbox/mapbox-gl-js#7763]
**mapbox-gl-js version**: 0.52.0

**browser**: Firefox 64.0, Safari 12.0.2

### Steps to Trigger Behavior

 1. Attempt to render a heatmap with a large number of points on the same coordinates

### Link to Demonstration

https://jsfiddle.net/65fspvz0/3/

### Expected Behavior

Heatmap is not clipped around the edges

### Actual Behavior

<img width="218" alt="clip" src="https://user-images.githubusercontent.com/2822871/51026994-b7cdd900-1587-11e9-8534-a0c0ba53b8b6.png">

**Comment by mourner** [comment]
Yes, this is a known technical limitation with the heatmap layer. The recommended workaround is to use GeoJSON clustering.

**Comment by alibabzo** [comment]
@mourner thanks for getting back so fast!

Could you elaborate on 'GeoJSON clustering'? Do you mean serving a different GeoJSON which is 'pre-clustered', using `"cluster": true` on the source, or something else?

**Comment by alibabzo** [comment]
@mourner Looks good - thanks for the clarification.
