### ISSUE TITLE
 Polygon fill-extrusion foreground extrusions missing with some tiles

### ISSUE THREAD

**Issue by joedjc** [mapbox/mapbox-gl-js#7767]
I'm experiencing an issue displaying tiles generated using PostGIS St_AsMVT in mapbox. The foreground extrusions are always missing.

<img src="https://s3-eu-west-1.amazonaws.com/www.iventis.co.uk/assets/postgis_vs_mapnik.png">

As this seems to be specific to tiles generated by PostGIS, I posted this as an issue with PostGIS (https://trac.osgeo.org/postgis/ticket/4293). However, they are suggesting the tile is valid and it therefore may be a mapbox issue (or something i'm doing wrong).

**mapbox-gl-js version**: v0.52.0
**browser**: Chrome Version 71.0.3578.98

### Steps to Trigger Behavior

 1. Create a MVT containing a Polygon generated from PostGIS using St_AsMVT e.g.
**Query used to generate tile in PostGIS**
`SELECT (ST_AsMVT(q, '303', 4096, 'geom')) as data FROM
	(
		SELECT
		ST_AsMVTGeom(
		ST_MakeValid(ST_Transform(ST_GeomFromText('POLYGON((2.35044440995268 48.8547079153776,2.34939134536916 48.8548089953983,2.34865467128913 48.8544487872917,2.34849994773995 48.8531318335876,2.35117736888415 48.8532126364981,2.35044440995268 48.8547079153776))',4326),3857)),
		ST_MakeBox2D(ST_Point(260497.392395924, 6250714.42504853), ST_Point(261720.384848486, 6249491.43259597)),
		4096,
		256,
		true
		) geom
	) as q`
 2. Display polygon using fill-extrusion
 

### Link to Demonstration

**PostGIS tile rendered in mapbox**
https://s3-eu-west-1.amazonaws.com/www.iventis.co.uk/test.html

### Expected Behavior

Fill-extrusion should render with solid sides/walls.

Here is an example with the same tile rendered from a Mapnik generated tile which appears correctly:

**Mapnik tile rendered in mapbox**
https://s3-eu-west-1.amazonaws.com/www.iventis.co.uk/test_mapnik.html

### Actual Behavior

The foreground extrusions are always missing when tiles have been generated by PostGIS.

### Links to tiles

**PostGIS generated tile**
https://s3-eu-west-1.amazonaws.com/www.iventis.co.uk/assets/15/16597/11273.pbf

**Mapnik generated tile**
https://s3-eu-west-1.amazonaws.com/www.iventis.co.uk/assets/mapnik/15/16597/11273.pbf

**Comment by Algunenano** [comment]
The Mapnik tile decoded with node-mapnik:
```
[
  {
    "version": 2,
    "name": "303",
    "extent": 4096,
    "features": [
      {
        "type": 3,
        "id": 1,
        "properties": {
          "id": 1992,
          "latitude_adj": "",
          "layerid": 303
        },
        "geometry": [
          9,
          6938,
          3034,
          34,
          784,
          116,
          546,
          1694,
          1995,
          92,
          116,
          1491,
          15
        ]
      }
    ]
  }
]
```

The PostGIS tile decoded with node-mapnik too:
```
[
  {
    "name": "303",
    "extent": 4096,
    "version": 2,
    "features": [
      {
        "type": 3,
        "properties": {},
        "geometry": [
          9,
          7722,
          3150,
          34,
          783,
          115,
          549,
          410,
          115,
          1492,
          1996,
          91,
          15
        ]
      }
    ]
  }
]
```

The PostGIS tile doesn't include the `feature.id`, which should be OK, but it doesn't include either any of the `properties` (`id`, `latitude_adj` and `layerid`). Do the extrusions depend on them?

**Comment by joedjc** [comment]
@Algunenano - no the properties are just some application data but are not used for the extrusion in either of the examples. It's interesting that the geometry in the tiles seems to be slightly different - particularly the last 6 co-ordinates which seem to be in a different order? I'm wondering if someone from mapbox would know what would cause the extrusions to render in this way.

**Comment by Algunenano** [comment]
> I'm wondering if someone from mapbox would know what would cause the extrusions to render in this way.

I missed checking the validity report of your tiles: From your Postgis tile I get:
```
Uncaught Error: Vector Tile has POLYGON with first ring clockwise. It is not valid according to v2 of VT spec.
```

What version of Postgis are you running? I don't get this issue with trunk, and if I recall this correctly this was fixed in 2.4.5.

**Comment by joedjc** [comment]
I am using 2.4.4 at the moment so that may well explain it. I will try upgrading

**Comment by joedjc** [comment]
@Algunenano - I can confirm it's working correctly in more recent PostGIS versions. Many thanks for your help.
