### ISSUE TITLE
Compact attribution control does not collapse non-link text

### ISSUE THREAD

**Issue by russss** [mapbox/mapbox-gl-js#7768]
**mapbox-gl-js version**: 0.50.0
**browser**: Chrome

### Steps to Trigger Behavior
If the map attribution string contains any text which is not within an `<a>` element, that text is erroneously displayed while the attribution control is collapsed. 

This also happens when more than one data source is used because mapbox-gl-js itself inserts a pipe character between attribution strings.

### Link to Demonstration

You can see this happen on [openinframap.org](https://openinframap.org) when it's resized to a small enough width to trigger the collapsed behaviour.

![image](https://user-images.githubusercontent.com/45057/51089191-14d0b700-1761-11e9-9bd3-b03e80c3ce7b.png)

**Comment by mourner** [comment]
I see that you're using v0.50 — can you make sure the same behavior can be seen with the latest version, v0.52?

**Comment by russss** [comment]
Oh, that's weird, npm thought I was on the latest version. It's fixed in 0.52, sorry for the mistaken bug report!
