### ISSUE TITLE
Can mapbox-gl-js add some animation basemap style?

### ISSUE THREAD

**Issue by ilomon10** [mapbox/mapbox-gl-js#7770]
**mapbox-gl-js version**: `any version`

### Question 
Can mapbox-gl-js add some animation basemap style?

I don't know how [they](https://github.com/tangrams) make it but maybe its possible.
here the [example](https://tangrams.github.io/tron-style) found on [github/tangrams](https://github.com/tangrams/tron-style)

Thanks

### Links to related documentation

[Animate point along line] https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-line/
[Dancing buildings] https://www.mapbox.com/mapbox-gl-js/example/dancing-buildings/
[Animate a line] https://www.mapbox.com/mapbox-gl-js/example/animate-a-line/
[Animate point along route] https://www.mapbox.com/mapbox-gl-js/example/animate-point-along-route/
[Add an image] https://www.mapbox.com/mapbox-gl-js/example/image-on-a-map/
[Animate a series of image] https://www.mapbox.com/mapbox-gl-js/example/animate-images/

Or use D3.js and make them like animate (maybe)

**Comment by mourner** [comment]
Not at the moment, but there's a plugin for this kind of visualizations: https://deck.gl
