### ISSUE TITLE
Blurriness in rendering raster tiles

### ISSUE THREAD

**Issue by aliir74** [mapbox/mapbox-gl-js#7771]
**mapbox-gl-js version**: 0.52.0

### Question
Hi all, I use mapbox gl js for rendering raster tiles but tiles in a browser after rendering have blurriness but main tile images are clear

I added `tilesize` to my style but my problem still exists.

```
"sources": {
    "high_update": {
        "type": "raster",
        "tileSize": 256,
        "tiles": [
            "http://192.168.101.16:8000/images/{z}/{x}/{y}.png"
        ],
        "minzoom": 3,
        "maxzoom": 16
    }
},
"layers": [
    {
        "id": "simple-tiles",
        "type": "raster",
        "source": "high_update",
        "minzoom": 0,
        "maxzoom": 22
    }
]
```

my tile image:

![](https://cdn.pbrd.co/images/HWnZPXK.png)

my rendered map:

![](https://cdn.pbrd.co/images/HWo0kL1.png)

Sorry for asking in github instead of stackoverflow. The stackoverflow show me this error `You need at least 10 reputation to post images.
`

### Links to related documentation
[raster sources](https://www.mapbox.com/mapbox-gl-js/style-spec/#sources-raster)

**Comment by peterqliu** [comment]
@aliir74 two things come to mind:

- the renderer loads raster tiles at the nearest integer zoom, which means they're blurrier at all zooms x.0 to x.5 (rounded down), and sharper at x.5 to x.0 (rounded up). https://github.com/mapbox/mapbox-gl-js/issues/1030 has some more historical context

- allowing fractional zoom and map rotation/pitch means it's hard to align pixels to the screen, which might contribute to blurriness. Per https://github.com/mapbox/mapbox-gl-js/pull/7426 the renderer now aligns when the map idles

**Comment by aliir74** [comment]
I find my problem is in mobile view mode. In a browser with a wide view didn't any blurry tile. but in mobile view everything gets blurry.

Wide view in Chrome:
![](https://cdn.pbrd.co/images/HWysX0a.png)

Mobile view in Chrome:
![](https://cdn.pbrd.co/images/HWytBqa.png)

**Comment by aliir74** [comment]
@peterqliu I mean when you see map on mobile things gets blurry but in desktop everything is ok.

I'm trying to generate rasters in 512x512 size to see the result.

**Comment by aliir74** [comment]
@peterqliu Do you have any idea why this blurry thing happen in mobile size?

**Comment by asheemmamoowala** [comment]
@aliir74 Can you test the [v0.53.0 beta](https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.53.0-beta.1) to see if it resolves the bluriness ?

**Comment by aliir74** [comment]
@asheemmamoowala I increase the ratio in my picture and blurriness is gone. seems mobile screens have more resolution display.

**Comment by bart-1990** [comment]
I'm also experiencing bluriness in tiles, especially at the .5 zoom level.
Is there any explanation for this?

First image, zoom level = 1.5
Second image, zoom level = 1.5019

<img width="862" alt="1-5" src="https://user-images.githubusercontent.com/7540719/56423407-34b9ce80-62ac-11e9-81b4-ba0cb8e28817.png">
<img width="838" alt="1-5019" src="https://user-images.githubusercontent.com/7540719/56423409-34b9ce80-62ac-11e9-83a9-d1e54fe3c853.png">
