### ISSUE TITLE
Track popups to mouse cursor

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#7777]
## Motivation

I've seen many use cases (in Studio's data inspector, in [my own demos](https://www.mapbox.com/bites/00273/), and [from others](https://github.com/mapbox/mapbox-gl-js/issues/7772)) where we'd want a popup "inspector" to follow the mouse, rather than any static lnglat. I've usually built these from scratch, but would be ideal to extend the current popup API for this.

## Design Alternatives

Can simulate this with the current popup by detecting mouse position on every `mousemove`, projecting that to lnglat, and `setLngLat` to the popup. On `mouseout` and `mouseenter` of the map element, the popup would hide and show itself, respectively.

But it would be nice to one-line this.

## Design/Mockup

Some API ideas:

- `popup.setLngLat({trackCursor: true})` : would expand the current method accept object literals
-  `popup.trackCursor()`: would add a new method to the Popup class, that along with `setLngLat` would mutually overwrite each other.
- Have mouse tracking as the default behavior if `setLngLat` is not called. May be the easiest to implement, but weirdest to use in practice.

**Comment by ryanhamley** [comment]
I think this would be pretty similar to the draggable marker code, the meat of which is https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/marker.js#L371-L375 It's also important to account for any offset between the cursor position and the position of the element being moved around the screen which is calculated here https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/marker.js#L441

Another use case for this would be working with multiple, stacked fill extrusions and querying them to show a popup with information as you move to various "floors" of the stacked extrusions. Could be useful for things like real estate apps or terrain applications with raster-dem tiles.

**Comment by peterqliu** [comment]
>I think this would be pretty similar to the draggable marker code

@ryanhamley exactly, though can we short-circuit the `mouse pixel` ➡️ `lnglat` ➡️ `popup translation pixel` dance, and just keep everything in px? Cursor offset straight to popup's CSS translate 🤔

**Comment by ryanhamley** [comment]
You mean because there wouldn't be a LatLng for the popup in the case where it's following the cursor? I think that makes sense. I just wonder if leaving latLng undefined or null would cause unexpected issues elsewhere. It's definitely something you could explore. My guess is the only argument against cutting out the conversion to/from LatLng in this case is one of consistency within the API.

**Comment by bravecow** [comment]
mouse cursor popup I do this way:

```javascript
popup(event) {
  const canvas = this.map.getCanvas();
  const node = document.querySelector('#map-popup');
  if (event) {
    canvas.style.cursor = 'pointer';
    node.textContent = event.features[0].properties.title;
    node.style.left = `${event.originalEvent.clientX}px`;
    node.style.top = `${event.originalEvent.clientY}px`;
    node.style.display = 'block';
  } else {
    canvas.style.cursor = '';
    node.style.display = 'none';
    node.textContent = '';
  }
}
```

**Comment by jacksonrya** [comment]
Y'all can just follow [mapbox's guide to display a popup on hover](https://docs.mapbox.com/mapbox-gl-js/example/popup-on-hover/), but set the popup's lngLat to the mapbox event's lngLat property.

`popup.setLngLat(e.lngLat)
.setHTML(description)
.addTo(map);`

**Comment by ryanhamley** [comment]
@peterqliu your PR for this fix just needs to have a couple of conflicts resolved and then it can be merged and this issue can be closed

**Comment by peterqliu** [comment]
https://github.com/mapbox/mapbox-gl-js/pull/7786 🚢 

<img src='https://media.giphy.com/media/rl0FOxdz7CcxO/giphy.gif'>
