### ISSUE TITLE
`fill-extrusion-color` renders features in black when set to "transparent" in the stops

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#7785]
**mapbox-gl-js version**:
0.51.0

**browser**:
Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

### Background
Our app uses `fill` and `fill-extrusion` layers so users can toggle back and forth between "flat" and "3D" visualizations of their data.

In cases where the data is 0 for a given polygon, we want to render it transparent so that the map is easier to understand, eg: "Here are all the US States with at least one Ivy League college."

When converting between `fill` and `fill-extrusion` layers, we just change all occurrences of `fill` to `fill-extrusion` in the style layer. This works almost perfectly, except when there are "transparent" color values.

### Steps to Trigger Behavior

 1. Create a `fill-extrusion` layer and set a data-driven color stop to "transparent".

### Link to Demonstration
(Not the Ivy League example, but demonstrates the issue nonetheless)
https://jsbin.com/buporamafa/1/edit?js,output

### Expected Behavior
Maine, New Hampshire, and Massachusetts should be transparent as declared in the stops.

### Actual Behavior
Maine, New Hampshire, and Massachusetts are rendered in black.

![image](https://user-images.githubusercontent.com/4524175/51353210-cbd07980-1a64-11e9-9c34-dacb050b3d20.png)

**Comment by asheemmamoowala** [comment]
This is a known limitation, as described in the documentation for [`fill-extrusion-color`](https://docs.mapbox.com/mapbox-gl-js/style-spec#paint-fill-extrusion-fill-extrusion-color). You may use [`fill-extrusion-opacity`](https://docs.mapbox.com/mapbox-gl-js/style-spec#paint-fill-extrusion-fill-extrusion-opacity) instead.
