### ISSUE TITLE
Commercial Usage Question

### ISSUE THREAD

**Issue by joewoodhouse** [mapbox/mapbox-gl-js#7788]
**mapbox-gl-js version**: All

### Question

Hopefully a simple question - is it permitted to use mapbox-gl-js in a commercial product without having a mapbox account? We would like to use this for a commercial paid-for product, but the cost of a commercial license for MapBox is far too expensive for us at the moment. I'm wondering if we are able to use mapbox-gl-js itself without using e.g. a mapbox studio style. Some other issues I've read seem to suggest the library will work OK without setting an accessToken, but I'd like to know in terms of licensing whether this is permitted.

The documentation linked below says "To use any of Mapbox's tools, APIs, or SDKs, you'll need a Mapbox access token." - I'm not sure whether tools includes this open-source library or not.

### Links to related documentation

https://docs.mapbox.com/help/glossary/access-token

**Comment by chloekraw** [comment]
Hi @joewoodhouse, thanks for asking! We work with all kinds of developers who use Mapbox GL JS in commercial products, and would love to get in touch with you to hear more about what you're building and how we can support you. Feel free to drop your email here or fill out [our contact form](https://www.mapbox.com/contact/sales/). In the meantime, I'll close out this ticket in the issue tracker. Thanks!
