### ISSUE TITLE
Marker with img tag looses its focus when it starts dragging.

### ISSUE THREAD

**Issue by cs09g** [mapbox/mapbox-gl-js#7795]
**mapbox-gl-js version**:
v0.52.0

**browser**:
Firefox 64.0.2
IE 11

### Steps to Trigger Behavior

 1. create marker with img element
 2. set draggable true and add to map
 3. start dragging

### Link to Demonstration
https://jsfiddle.net/9ru0z3dw/

### Expected Behavior
marker should be dragging as expected.

### Actual Behavior
marker shows its ghost icon and cursor turns to not-allowed.

### Workaround
Setting following code on marker element, it works as expected but, I think this should be a part of library.
`element.ondragstart = () => { return false; }`

**Comment by ryanhamley** [comment]
@cs09g We always welcome PRs! You're right that it would be added in the constructor.
