### ISSUE TITLE
Raster sources are slow - a lot of 404 requests

### ISSUE THREAD

**Issue by bravecow** [mapbox/mapbox-gl-js#7798]
**mapbox-gl-js version**: 0.52.0

**browser**: Chrome, OSX

### Steps to Trigger Behavior

Add multiple layers with type raster:

```javascript
TILES.orthophotos.forEach((mapId, index) => {
  this.map.addLayer({
    id: `orthophoto-${index}`,
    type: 'raster',
    source: {
      type: 'raster',
      tiles: [`https://api.mapbox.com/v4/${mapId}/{z}/{x}/{y}.png?access_token=${window.mapAcessToken}`],
      tileSize: 256,
    },
    minzoom: 14,
  });
});
```

Now map bounds, that should render only one layer makes a lot of requests to all layers:

![image](https://user-images.githubusercontent.com/988471/51543476-4edb4080-1e66-11e9-81a3-e74aa1c2deae.png)

So loading visible area is very slow:

![image](https://user-images.githubusercontent.com/988471/51543621-ab3e6000-1e66-11e9-9a6b-5c4e70f248ad.png)

### Expected Behavior

Requests made to visible layer source only.

### Actual Behavior

Requests made to all layers.

### Example

https://mapbox-raster.stackblitz.io/

**Comment by mourner** [comment]
Could you provide a minimal live test case that demonstrates the problem? We can't diagnose it otherwise.

**Comment by bravecow** [comment]
@mourner 

app: https://mapbox-raster.stackblitz.io/
editor: https://stackblitz.com/edit/mapbox-raster

**Comment by mourner** [comment]
You don't specify the bounds for your tile sources anywhere. If you have them in the sources TileJSON metadata, you should specify `url` (which is either of `mapbox://` format or links directly to `.tilejson` file) instead of custom source definition with `tiles`. Closing because this works as expected.
