### ISSUE TITLE
How can I query all features in a GeoJSON source

### ISSUE THREAD

**Issue by dieterdreist** [mapbox/mapbox-gl-js#7802]
**mapbox-gl-js version**:
v0.52.0

### Question
I have been trying to access objects in a GeoJSON source but found the result would depend on the current zoomlevel and screen extent even with 
"querySourceFeatures(sourceID, parameters?)"

My GeoJSON contain lines, I have several files I load via the gl-js API from my webserver, I am adding them to the map and everything renders fine, but I would want to access this source data to do some calculations without reloading them from the server a second time. How can I access the raw source data?

I also found that the sources resulted "empty" with querySourceFeatures(sourceID, parameters?)" if the current map view was zoomed out, and "filled" when zooming in, I would have expected this behaviour from queryRenderedFeatures, not from the querySourceFeatures function.

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/api/#map#querysourcefeatures
https://docs.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures

**Comment by mourner** [comment]
`querySourceFeatures` queries data contained in the tiles in the current map view:

>  The domain of the query includes all currently-loaded vector tiles and GeoJSON source tiles: this function does not check tiles outside the currently visible viewport.

So this is working as designed. You shouldn't worry about the cost of requesting the GeoJSON file twice though, because browser will cache it the first time.

**Comment by cylqinsmoon** [comment]
Yes, for example, I zoomed in on a state in the United States, clicking through quryrenderedfeatures and qurysourcefeatures can only get a portion of the state's boundaries and may be split. Can't I get the boundaries of the state in my original data?
