### ISSUE TITLE
How to limit the number of web Worker create by mapbox-gl-js?

### ISSUE THREAD

**Issue by AlanKnightly** [mapbox/mapbox-gl-js#7810]
I run into a problem that when testing on UC browser (device: iphone6s) , the code below:
new mapboxgl.Map(opt);

It will throw an error: QuotaExceededError:Failed to construct 'Worker': Maximum worker number has been reached.
Is there any way to control or limit the number of workers for mapboxjs to solve this problem? I cant find any relative option from the doc

**Comment by mourner** [comment]
You can limit the number of workers by setting `mapboxgl.workerCount = <number>;` before instantiating any maps, but we forgot to document this — good catch! Will be fixed by #7812.
