### ISSUE TITLE
Satellite view, Bug in FF, not in Chrome

### ISSUE THREAD

**Issue by arena94** [mapbox/mapbox-gl-js#7822]
**mapbox-gl-js version**: v052

**browser**: FF

### Steps to Trigger Behavior

 1. go to http://www.nogent94.com/bugs/mapbox/
 2. click on specific control : arrow (upper right)
 3. by clicking on this control, you are supposed to change map style.
on FF satellite tiles are not rendered (black), on satellite+streets, only streets
on Chrome: everything is ok

### Link to Demonstration

http://www.nogent94.com/bugs/mapbox/

### Expected Behavior
FF as Chrome does

### Actual Behavior
on FF satellite tiles are not rendered (black), on satellite+streets, only streets

![bug](https://user-images.githubusercontent.com/1025411/51780566-cc75a980-210f-11e9-9df8-5be0d2638891.png)

Regards

**Comment by ryanhamley** [comment]
You appear to be serving WebP images for your tiles but Firefox does not support WebP images. You'll need JPG or PNG fallbacks for cross-browser support.

**Comment by arena94** [comment]
Thank you for the reply.

I must miss something !

The external libraries called are exactly the same than on the following page :
https://docs.mapbox.com/mapbox-gl-js/example/setstyle/

and there, i can see satellite pictures ... ???

![capture](https://user-images.githubusercontent.com/1025411/51786658-7fbdbd00-2167-11e9-883d-7a7f33f8c3ec.PNG)

**Comment by cs09g** [comment]
Where did you create your style which includes the url template for each source? The example on mapbox uses `png` but yours `webp`.

**Comment by arena94** [comment]
hello @cs09g 
i did not create any style. Apparently, sometimes it works, sometimes it doesn't.
So i suppose i am in a sort of default mode, and the server serves (maybe) the less busy (webp or png).

an extract of my code :

```
	this.get_maptype = function(maptype) {
                var s = v = null;
		switch(maptype)
		{
			case 'SATELLITE': s = 'satellite'; v = '9';	break;
			case 'HYBRID'	: s = 'satellite-streets'; v = '11'; break;
			case 'TERRAIN'	: s = 'outdoors'; v = '11';	break;
			default	 	: s = 'streets'; v = '11';	break;
		}
                return 'mapbox://styles/mapbox/' + s + '-v' + v;
	};
```

**Comment by ryanhamley** [comment]
It's possible that this is related to a bug we uncovered last week where a race condition occasionally allowed WebP tiles to be requested in browsers that didn't support them (although I only observed this bug myself in Safari). It was fixed with https://github.com/mapbox/mapbox-gl-js/pull/7817 so you may want to test with the `master` branch of GL JS if you can to see if that solves your problem. The bug fix will be included in the next release of GL JS which comes out later this week.

**Comment by arena94** [comment]
Thank you @ryanhamley , 
I realise how a newbie i am. 
Cannot figure out what file to use after dowloading master zip file !!!
Btw, another question (or suggestion) instead of loading 
`https://api.tiles.mapbox.com/mapbox-gl-js/v0.52.0/mapbox-gl.js`
is there sort of a
`https://api.tiles.mapbox.com/mapbox-gl-js/latest/mapbox-gl.js`
link ?
Regards

**Comment by arena94** [comment]
apparently, something have changed on the server side today, 
Seems to work everytime now ! :-)

**Comment by asheemmamoowala** [comment]
> is there 'sort of' a
https://api.tiles.mapbox.com/mapbox-gl-js/latest/mapbox-gl.js
link ?

We do not have a CDN url pointing to the `latest` release. An important reason for this is that the APIs are changing, and using such a URL would risk breaking a lot of customer deployments.

Using NPM (`> npm install mapbox-gl-js`), you can get the latest version, but I would recommend against this for the reasons mentioned above.
