### ISSUE TITLE
Keeping a marker centered even during map move

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#7823]
I need to keep the marker centered all the time, even during drag and pan of the map and update its LngLat according to the map movement.

While most of it works, but I just can't figure out how to keep the marker cenrtered *during* the map drag/pan.

Here's what I have so far: 
https://jsfiddle.net/iaezzy/yLf4wgzd/1/

    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v9',
        center: [0, 0],
        zoom: 2
    });
    var marker = new mapboxgl.Marker()
        .setLngLat([0, 0])
        .addTo(map);
    
    map.on('movestart', function (e) {
        console.log(`Current Map Center: ${map.getCenter()}`);
        marker.setLngLat(map.getCenter());
    });
    map.on('moveend', function (e) {
        console.log(`Current Map Center: ${map.getCenter()}`);
        marker.setLngLat(map.getCenter());
    });

One way I can think of is to poll `map.isMoving` every few milliseconds and update the markers location but that doesn't seem an optimal solution.

**Comment by dagjomar** [comment]
Isn’t there an event for “move”?

**Comment by 3zzy** [comment]
Ah darn, not sure how I missed that. Thanks!

**Comment by digcrow** [comment]
I have found better trick, I hope it will help :
mapbox-gl : [v1.6.0]
`map = new mapboxgl.Map({
            container: 'map', // container id
            style: 'mapbox://styles/mapbox/streets-v11',
            center: [0, 0],
            minZoom: 8,
            zoom: 13
        });

        marker = new mapboxgl.Marker({
            draggable: true
        })
            .setLngLat([0, 0])
            .addTo(map);

        marker.on('dragend', onDragEnd);

    function onDragEnd() {
        var lngLat = marker.getLngLat();
        console.log('Longitude: ' + lngLat.lng + ' Latitude: ' + lngLat.lat);

        // move map to where the marker is dragged 
        map.flyTo({
            center: [
                lngLat.lng,
                lngLat.lat
            ],
            essential: false // this animation is considered essential with respect to prefers-reduced-motion
        });
    }`

**Comment by barghi** [comment]
You can use `move` event

```
map.on('move', function (e) {
    console.log(`Current Map Center: ${map.getCenter()}`);
    marker.setLngLat(map.getCenter());
});
```

**Comment by andros59** [comment]
You can use drag and zoom event

`mapboxgl.accessToken = 'pk.eyJ1IjoiYW5kcm9zNDkiLCJhIjoiY2toY29peTQwMDlqZDJ4cGZnMTZkeG1kcyJ9.k22HHSeRu3Asfh0SlODMQg';
    var coordinates = document.getElementById('coordinates');
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v11',
        center: [0, 0],
        zoom: 2
    });

    var marker = new mapboxgl.Marker({
    })
        .setLngLat([0, 0])
        .addTo(map);

    map.on('drag', function() {
    	centro=map.getCenter();
      marker.setLngLat(centro);
    });
    map.on('zoom', function() {
    centro=map.getCenter();
      marker.setLngLat(centro);
    });`

**Comment by csimpi** [comment]
I found it a bit pretty lame and unnecessarily heavy to subscribe to an event that could fire lots of times in order to keep a marker in the middle of the map, also in some particular cases (e.g. slow device) the marker might move with the map for a moment before it gets repositioned to the center :/

**Comment by gregholst** [comment]
@csimpi I agree with you. I have a search field to enter the desired position of the map and after pressing return the map flies to the destination given in the search field. I am using react-map-gl and with the solution proposed by @barghi a warning message is created: Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render
