### ISSUE TITLE
Have you considered adding fill-gradient attributes to fill layers?

### ISSUE THREAD

**Issue by huashaoxu** [mapbox/mapbox-gl-js#7827]
**mapbox-gl-js version**: 0.50
Have you considered adding fill-gradient attributes to fill layers? like the picture
![image](https://user-images.githubusercontent.com/35364039/51841131-d6362180-2348-11e9-8508-c5b3c463fb36.png)

**Comment by mourner** [comment]
See #769 and #6816.
