### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by flawyte** [mapbox/mapbox-gl-js#7829]
### Steps to Trigger Behavior

 1. Go to https://docs.mapbox.com/mapbox-gl-js/api/#map#fitbounds
 2. In the description of `options.linear`, click on `Map#easeTo`

### Expected Behavior

It should scroll to `easeTo()`'s documentation.

### Actual Behavior

Nothing happens because the URL links to `#mapeaseto` instead of `#map#easeto`.
Same problem for `Map#flyTo` and all other method links I've tried.

**Comment by andrewharvey** [comment]
Thanks for the report @flawyte, this looks like a duplicate of #4568 so I'll close this to avoid fragmenting the issue.
