### ISSUE TITLE
How to remove/reset a specific filter on a layer?

### ISSUE THREAD

**Issue by tyler-x** [mapbox/mapbox-gl-js#7832]
**mapbox-gl-js version**:

### Question
Let's say I have applied two different filters on the same layer, and now I want to remove or reset one of the filter I applied, how do I achieve it?

e.g.
map.setFilter(THELAYER, [condition 1]);
map.setFilter(THELAYER, [condition 2]);

I know I can use map.setFilter(THELAYER); to reset the filters on THELAYER, but it will remove all two filters, what about I want to keep say condition 2, and remove condition 1?

By the way, these filters only works on frontend, right? There is no way I can setup some filters to filter data from back end, e.g. on mbtiles, do some SQL queries.

Thanks a lot~!

**Comment by stevage** [comment]
G'day. It's best to ask for help over at stackoverflow.com, using the mapbox-gl-js tag.

But anyway: there's no such thing as different filters on the same layer. In your code above, the second call replaced the first filter. If you want to combine filters, you need to use either `all` or `any`:

`map.setFilter(THELAYER, ["all", [condition 1], [condition 2]])`

And yeah, back end "filtering" would be a completely different topic with totally different techniques etc.
