### ISSUE TITLE
map.getLayer(). paint and .layout expose internals

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#7844]
**mapbox-gl-js version**:

0.51.0

![screenshot 2019-01-30 11 24 38](https://user-images.githubusercontent.com/678344/51949688-a474a600-2481-11e9-96cc-fc35928d08a1.png)

I'm not sure exactly what the intended use of `map.getLayer()` is, but this object whose `paint` and `layout` properties contain `_properties` and `_values` isn't very useful in this form. It seems to be exposing mapbox-gl-js internals, through this public API, which is, um, odd.

By contrast, this gives exactly the result I was expecting from `map.getLayer('lots-line')`:

`map.getStyle().layers.find(l => l.id === 'lots-line')`

I gather this was addressed recently in  #7502, but it still seems under-documented to me.

**Comment by andrewharvey** [comment]
See #3713

> The type currently returned by Map#getLayer is private and has no documented methods. The only documented thing you can do with it is check if it's null or not. This isn't very useful. It would be more useful to return the serialized, style spec representation of the layer.

I'll close this in favour of keeping the discussion about Map#getLayer in #3713, but shout out if it's a different issue.
