### ISSUE TITLE
Labels are duplicating

### ISSUE THREAD

**Issue by mohomedanees** [mapbox/mapbox-gl-js#7846]
Hi,

I'm facing an issue that the labels are duplicating in the map. 

![image](https://user-images.githubusercontent.com/12741808/51956690-a5e8a300-246e-11e9-9734-859cf21c6ea9.png)

From below link you can see how the map shows.
https://api.mapbox.com/styles/v1/mohomedanees/cjrbm4tui3ce72smsthr559xe.html?fresh=true&title=true&access_token=pk.eyJ1IjoibW9ob21lZGFuZWVzIiwiYSI6ImNqcG52ZzM2MDA3OXM0MnM2a3lxZ2JkNzYifQ.UQCRaNiLwcwYnutjsM7ziA#10.9/53.416328/-2.763367/0

And please don't say this is a duplicate of #5583. I need to know the proper fix how to sort out this issue.

**Comment by andrewharvey** [comment]
Hi @mohomedanees https://github.com/mapbox/mapbox-gl-js/issues/5583#issuecomment-341840524 really is the best advise here, it explains the reason this happens at the moment and the your best options for a solution. That is, to create your own point dataset from those polygons where you want the label so you're only labelling points not polygons.

https://github.com/andrewharvey/geojson-polygon-labels is one option to do that with options to use the polygon centroid, or pole of inaccessibility. Instructions are in the README. You need to npm install the tool, and then call `geojson-polygon-labels polygons.geojson > labels.geojson`.

Alternatively you can use any number of GIS tools such as QGIS to create centroid points.

**Comment by mohomedanees** [comment]
Thanks for the advice @andrewharvey
