### ISSUE TITLE
Shaking raster map after easeTo\flyTo

### ISSUE THREAD

**Issue by aliir74** [mapbox/mapbox-gl-js#7849]
Hi all.
I use raster tiles and want to keep the user in integer zoom level for prevent from blurry tiles.
on `moveend` event I call `map.easeTo` to nearest integer zoom level but after the end of the animation, my map and marker start shaking.
See this video for seeing this shaking:
[https://vimeo.com/314318425]()

**mapbox-gl-js version**:
0.52.0
**browser**:
Google Chrome
### Steps to Trigger Behavior

 1. Source raster tiles
 2. Use `easeTo` for keeping zoom level integer
```
map.on('moveend', _u.debounce(function() {
            map.easeTo({
                zoom: Math.round(map.getZoom()),
                speed: 0.3
            })
        }, 1000));
```
### Link to Demonstration
[https://docs.mapbox.com/mapbox-gl-js/api/#map#flyto]()
### Expected Behavior
Change zoom to integer zoom level and fix map without shaking.
### Actual Behavior
`Easeto` desire zoom level but with shaking after the end of easing

**Comment by asheemmamoowala** [comment]
@aliir74 The `moveend` event is called after an `easeTo` even when the zoom doesn't actually change. This is what is causing the continuous map shake in your case. It can be easily addressed with a guard for a integer zoom, with something like: 
```
        let currZoom = map.getZoom();
            if (Math.round(currZoom) !== currZoom) {
```

https://github.com/mapbox/mapbox-gl-js/pull/7426 addresses a different form of raster shaking, and can be tested in the [0.53 beta](https://github.com/mapbox/mapbox-gl-js/releases/tag/v0.53.0-beta.1)

**Comment by ivjia** [comment]
anyone can help? I still suffer this issue
