### ISSUE TITLE
Why the offset option works opposite when it's a single number?

### ISSUE THREAD

**Issue by cs09g** [mapbox/mapbox-gl-js#7854]
**mapbox-gl-js version**:
latest

### Question
Negagive offsets indicate left-top as its documentation, but when it's a single number, it works oppsitely.
Why does it work like this way?

https://jsfiddle.net/ruh3egj0/
Oppsite position changes between `offset: 50` and `offset: [0, 50]` .

ps. actually, `offset: 50` should be shorthand of `offset: [50, 50]` as CSS does. 

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/api/#popup

**Comment by andrewharvey** [comment]
tldr: https://docs.mapbox.com/mapbox-gl-js/example/set-popup/

> A pixel offset applied to the popup's location specified as:
> - **a single number specifying a distance from the popup's location**
> - a PointLike specifying a constant offset
> - an object of Points specifing an offset for each anchor position Negative offsets indicate left and up.

Per the documentation, when using a single number for the offset this is specifying a distance from the popup's location.

Also see the documentation for Popup anchor:

> If unset the anchor will be dynamically set to ensure the popup falls within the map container with a preference for 'bottom'.

So if you specify an offset of 50, then when the anchor is bottom it will offset up 50px, when the anchor is bottom, down 50px etc.

See the example at https://docs.mapbox.com/mapbox-gl-js/example/set-popup/ for how a single number offset works, make sure to pan the map around with the popup open to force it to change anchors

**Comment by cs09g** [comment]
But, don't you think the direction should be static? it's dynmic direction up to it's anchor. sometimes positive value means up and sometimes means down.

**Comment by andrewharvey** [comment]
That's right, it's static but relative to the anchor.

In this case of a single number positive integers mean in the opposite direction of the anchor. ie. if anchor is bottom-left |_ then the direction of the single positive integer offset is to the top right

This makes things a hell of a lot simpler for this kind of use case https://docs.mapbox.com/mapbox-gl-js/example/set-popup/

Does that help?

**Comment by cs09g** [comment]
It's much useful though! :) The functionality is actually one of very annoying work to implement.
