### ISSUE TITLE
enlarge code section in examples

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#7856]
![screenshot from 2019-01-31 12-36-32](https://user-images.githubusercontent.com/117278/52024408-e0c50680-2554-11e9-936b-9600fced1583.png)

The code section in the new examples layout is very small, could it be made a bit bigger so it's easier to read?

eg https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/

**Comment by pathmapper** [comment]
The following screenshot is taken on a screen with a resolution of 2560x1440. With a 4K resolution there will be even more unused space.

![auswahl_524](https://user-images.githubusercontent.com/20856381/52039073-d0506400-2533-11e9-8115-c036a86ce3db.png)

**Comment by ryanhamley** [comment]
cc @colleenmcginnis @malwoodsantoro

**Comment by mourner** [comment]
Fixed in #7876
