### ISSUE TITLE
GeoJson Source in Runtime Styling

### ISSUE THREAD

**Issue by mdakram** [mapbox/mapbox-gl-js#7860]
**mapbox-gl-js v0.52**:

### Question
Do Mapbox Supports, `GeoJson` support in Runtime Styling.

I tried same Style (file with two Source 1. `Vector`, 2. `GeoJson`) file with `mapbox-gl-native` and `mapbox-gl-js`.

It was working as expected in Native SDK but it seems mapbox-gl-js is ignoring if source type is GeoJson.

**Comment by mourner** [comment]
Please fill out the issue template fully, including a link to a minimal reproducible test case (e.g. JSFiddle). We can't diagnose the issue with this description.

**Comment by mdakram** [comment]
@mourner My apologies for coming up with half of information i have created a sample and updated issue with link. Please see if this can help.
