### ISSUE TITLE
setLayerZoomRange causing rasters to be re-requested

### ISSUE THREAD

**Issue by nreese** [mapbox/mapbox-gl-js#7865]
Whenever `setLayerZoomRange` is called with new min/max values on a layer containing raster tiles, all tiles are requested. Is this expected behavior? I am using mapbox-gl version `0.45.0` in Chrome 71.0.3578.98. 

Below is the code used to create the layer.

```
    mbMap.addSource(sourceId, {
      type: 'raster',
      tiles: [url],
      tileSize: 256,
      scheme: 'xyz',
    });

    mbMap.addLayer({
      id: mbLayerId,
      type: 'raster',
      source: sourceId,
      minzoom: 0,
      maxzoom: 22,
    });
```

Then if `mbMap.setLayerZoomRange(mbLayerId, 0, 15);` is called, all tiles are re-fetched. Why are the tiles re-fetched? The map is at zoom level 3 so the change should have no effect on the current tiles.

**Comment by mourner** [comment]
@nreese 
- Did you make sure the behavior is the same on the latest version, v0.52.0 or v0.53.0-beta.1?
- Can you set up a minimal reproducible test case to demonstrate this (e.g. with JSFiddle)?

**Comment by nreese** [comment]
@mourner The problem exists in `v0.52.0`. Here is a js-fiddle that demonstrates the problem https://jsfiddle.net/reesenathan/pwb6nz74/. Adjust the slider in the top left corner and notice that when you release the slider and `setLayerZoomRange` is triggered, the tiles flicker because they are getting re-fetched.

**Comment by peterqliu** [comment]
Looks like killing this line removes the flicker, while preserving the method functionality:

https://github.com/mapbox/mapbox-gl-js/blob/ead961f7c6b903bb5bbfbc3f128362bb46d421eb/src/style/style.js#L735

does anything rely on this line running, that I'm not seeing?
