### ISSUE TITLE
"Invalid calling object" error in IE

### ISSUE THREAD

**Issue by gorshkov-leonid** [mapbox/mapbox-gl-js#7867]
**mapbox-gl-js version**:
0.52.0

**browser**:
IE 11

### Steps to Trigger Behavior
It is difficult to emulate case

## Motivation

I use "/node_modules/mapbox-gl/src" for compilation custom source type.  So It is quite illelegal. But I have not variants, do not blame me....

So, I see error 
![image](https://user-images.githubusercontent.com/2270831/52128512-94f68800-264e-11e9-93e0-efa42bc3fee6.png)
It is strange error that occurred when context object cannot be used during function's call.
I found closest case in https://github.com/vuejs/vue/issues/4465. 
There are commits:
https://github.com/vuejs/vue/commit/ff32ad1cfec258d35b7ee50e47aecab506fab541
https://github.com/vuejs/vue/commit/edb75c872c1ff6f3eb61ea24fc01226e8622c6eb
Problem can be checked via `eval('"use strict";var raf=window.requestAnimationFrame;raf(function(){})');`
So, I tried to fix it in mapbox(locally in node_modules)
v1
![image](https://user-images.githubusercontent.com/2270831/52128754-38479d00-264f-11e9-97a5-7ab1d3e48ee9.png)
v2
![image](https://user-images.githubusercontent.com/2270831/52128878-89579100-264f-11e9-9ba1-8d24266a6690.png)
Both of these variants works. 

Could you apply this microifix as preventive measure? thanks

**Comment by mourner** [comment]
Due to complex build system setup, we do not officially support Mapbox GL JS builds beyond the already built files (in the `dist` folder), and unfortunately do not have the capacity to debug IE11+Webpack issues with custom builds at the moment.
