### ISSUE TITLE
Expose a "clearRTLTextPlugin" or a give a way to check if the rtl plugin is requested

### ISSUE THREAD

**Issue by gimyboya** [mapbox/mapbox-gl-js#7869]
## Motivation

Right now there is no way to check if the RTL plugin has been requested or not, as such if we try to set it while it was already requested the following error occurs: ` setRTLTextPlugin cannot be called multiple times.`. which is an expected behavior.

however, if this error is not caught it may block the controls from rendering. 
In my case, i encountered this error in a vuejs component where I always initialize the RTL plugin when the component is loaded even tho I make sure to destroy the map using `map.remove()` after each time leaving the component the error still persists whenever I navigate back to that route (which loads that component again)

## Design Alternatives

expose [this function](https://github.com/mapbox/mapbox-gl-js/blob/ead961f7c6b903bb5bbfbc3f128362bb46d421eb/src/source/rtl_text_plugin.js#L28) in the `index.js` or create a getter to `pluginRequested` variable to check if the RTL plugin has been requested

**Comment by abdelhameedhamdy** [comment]
I encountered this issue in a vuejs component as well.
