### ISSUE TITLE
when mapbox-gl-js is included in a browserify bundle, the web worker runs the entire bundle

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#787]
Potential fix: https://github.com/shama/workerify

However, as far as I can tell this would lead to duplicating code that's shared between the worker and the main library (it will appear once as normal browserified source and once embedded in the worker blob string). Commenting out the worker line from mapbox-gl.js and running a command to see the overlap:

```
~/Development/mapbox-gl-js $ comm -12 <(node_modules/.bin/browserify --list js/source/worker.js | sort) <(node_modules/.bin/browserify --list js/mapbox-gl.js | sort)
/Users/john/Development/mapbox-gl-js/js/data/buffer/buffer.js
/Users/john/Development/mapbox-gl-js/js/data/buffer/buffer_set.js
/Users/john/Development/mapbox-gl-js/js/data/buffer/fill_elements_buffer.js
/Users/john/Development/mapbox-gl-js/js/data/buffer/fill_vertex_buffer.js
/Users/john/Development/mapbox-gl-js/js/data/buffer/glyph_vertex_buffer.js
/Users/john/Development/mapbox-gl-js/js/data/buffer/icon_vertex_buffer.js
/Users/john/Development/mapbox-gl-js/js/data/buffer/line_element_buffer.js
/Users/john/Development/mapbox-gl-js/js/data/buffer/line_vertex_buffer.js
/Users/john/Development/mapbox-gl-js/js/data/buffer/outline_elements_buffer.js
/Users/john/Development/mapbox-gl-js/js/data/create_bucket.js
/Users/john/Development/mapbox-gl-js/js/data/element_groups.js
/Users/john/Development/mapbox-gl-js/js/data/fill_bucket.js
/Users/john/Development/mapbox-gl-js/js/data/line_bucket.js
/Users/john/Development/mapbox-gl-js/js/data/raster_bucket.js
/Users/john/Development/mapbox-gl-js/js/data/symbol_bucket.js
/Users/john/Development/mapbox-gl-js/js/geo/lat_lng.js
/Users/john/Development/mapbox-gl-js/js/geo/transform.js
/Users/john/Development/mapbox-gl-js/js/source/tile_coord.js
/Users/john/Development/mapbox-gl-js/js/style/reference.js
/Users/john/Development/mapbox-gl-js/js/style/render_properties.js
/Users/john/Development/mapbox-gl-js/js/symbol/anchor.js
/Users/john/Development/mapbox-gl-js/js/symbol/interpolate.js
/Users/john/Development/mapbox-gl-js/js/symbol/placement.js
/Users/john/Development/mapbox-gl-js/js/symbol/resolve_text.js
/Users/john/Development/mapbox-gl-js/js/symbol/shaping.js
/Users/john/Development/mapbox-gl-js/js/util/actor.js
/Users/john/Development/mapbox-gl-js/js/util/browser/ajax.js
/Users/john/Development/mapbox-gl-js/js/util/token.js
/Users/john/Development/mapbox-gl-js/js/util/util.js
/Users/john/Development/mapbox-gl-js/node_modules/browserify/node_modules/buffer/index.js
/Users/john/Development/mapbox-gl-js/node_modules/browserify/node_modules/buffer/node_modules/base64-js/lib/b64.js
/Users/john/Development/mapbox-gl-js/node_modules/browserify/node_modules/buffer/node_modules/ieee754/index.js
/Users/john/Development/mapbox-gl-js/node_modules/browserify/node_modules/buffer/node_modules/is-array/index.js
/Users/john/Development/mapbox-gl-js/node_modules/mapbox-gl-style-spec/reference/v5.json
/Users/john/Development/mapbox-gl-js/node_modules/pbf/index.js
/Users/john/Development/mapbox-gl-js/node_modules/pbf/node_modules/ieee754/index.js
/Users/john/Development/mapbox-gl-js/node_modules/point-geometry/index.js
/Users/john/Development/mapbox-gl-js/node_modules/unitbezier/index.js
```

**Comment by tmcw** [comment]
> It seems to me that the simplest approach here is just requiring the script to be not bundled. It saves us a lot of problems and lets just leave things as it is.

This doesn't work for my use case: requiring this to be an exception makes it impossible to use [testing libraries](https://github.com/hughsk/smokestack) and breaks sourcemaps if you concat.

**Comment by mourner** [comment]
OK, not requiring, but maybe at least recommending it for production use? Testing + sourcemaps is limited to development.

**Comment by tmcw** [comment]
Yeah, so far we're patching around this by running

```js
window.mapboxgl = require('mapbox-gl');
```

Before tests in browserify, and using a separate script for the main page.

**Comment by jleppert** [comment]
Just want to say this bug burnt me bad. Maybe mention this somewhere that mapbox-gl is incompatible with browserify or at least throw some exception or something?

**Comment by jfirebaugh** [comment]
Sorry about that @jleppert. This is now mentioned in the README.

**Comment by vicapow** [comment]
Without browserify, it makes it difficult to create useable components on top of mapboxGL. Instead of saying "Hey, to use this component just npm install my-special-mapbox-gl-react-component". There's an additional step of including the mapbox-gl in a separate script tag.

**Comment by tmcw** [comment]
@vicapow yep, we're all aware that this is a big inconvenience, but haven't found a solution to it. We're keeping this ticket open until we figure out one, or if you have any ideas, we'd love to merge a pull request.

**Comment by vicapow** [comment]
@tmcw Here's my first stab at it: https://github.com/mapbox/mapbox-gl-js/pull/1214

**Comment by jfirebaugh** [comment]
Fixed in 2adecdb1cbbd6298ee225fd2f3a0953b236120e8.

**Comment by AbrahamArun** [comment]
In the latest version (0.8.1) using browserify, I have to 
```javascript
window.mapboxgl = require('mapbox-gl');
```
whereas in 0.7.0, the below would have sufficed.
```javascript
require('mapbox-gl');
```

**Comment by tmcw** [comment]
@AbrahamArun that's the desired behavior, right? For a commonjs include, you should

```js
var mapboxgl = require('mapbox-gl');
```

In order to control what the export is named as: this is the same as most other modules.

**Comment by vicapow** [comment]
@AbrahamArun Also, browserify wasn't supported in 0.7.0 so it's still unclear to me how this could be a breaking change.

**Comment by AbrahamArun** [comment]
Hmmmm. I might be wrong and probably there is something fishy in my build system. But ever since I have updated to 0.8.0

Neither
```javascript
var mapboxgl = require('mapbox-gl');
```
nor

```javascript
require('mapbox-gl');
```
seems to work, throwing this error
<img width="525" alt="screen shot 2015-07-15 at 1 03 07 am" src="https://cloud.githubusercontent.com/assets/5391059/8682778/6a71a90a-2a8c-11e5-9ea2-e13127a2e368.png">

and I have to do the following to get it working
```javascript
window.mapboxgl = require('mapbox-gl');
```

**Comment by tmcw** [comment]
You are running this require in the same file as the code that needs `mapboxgl` right?

**Comment by AbrahamArun** [comment]
Yep
