### ISSUE TITLE
getting street corners

### ISSUE THREAD

**Issue by fabianburghardt** [mapbox/mapbox-gl-js#7872]
**mapbox-gl-js version**: v0.52.0

### Question
I'm looking for a way to get the closest street corner points within a "xx-meter" radius.

Visualization attached:
https://s15.directupload.net/images/190204/d9umio3v.png

### Links to related documentation

https://github.com/mapbox/mapbox-gl-js/issues/723
https://docs.mapbox.com/api/navigation/

**Comment by asheemmamoowala** [comment]
@fabianburghardt GL-JS has no concept of street intersections or corners. You might be able to use `queryRenderedFeatures` to get the closest geometry features with turf's [lineIntersect](http://turfjs.org/docs/#lineIntersect) to determine intersections.
