### ISSUE TITLE
Incorrect display of the 3D model after adding it to the map as custom layer in v0.52.0

### ISSUE THREAD

**Issue by Solomka12** [mapbox/mapbox-gl-js#7874]
**mapbox-gl-js version**:
 v0.52.0

**browser**:
 Google Chrome 71.0.3578.98

### Link to Demonstration
Full example can be seen here:
[https://bl.ocks.org/ryanbaumann/b9725e79b5b1742d92ada00ddbf5c3d3](https://bl.ocks.org/ryanbaumann/b9725e79b5b1742d92ada00ddbf5c3d3)

### Expected Behavior
*in v0.51.0*
[https://i.imgur.com/cLR3OFJ.jpg](https://i.imgur.com/cLR3OFJ.jpg)

### Actual Behavior
*in v0.52.0*
[https://i.imgur.com/R9T3Tsa.jpg](https://i.imgur.com/R9T3Tsa.jpg)

**Comment by RubioV** [comment]
I can confirm I was having the same problem. It appears the rendering order is incorrect since v0.52.0.

v0.51.0:
![image](https://user-images.githubusercontent.com/107693/53170559-b361fa80-35e0-11e9-8836-66ce7d79a149.png)

v0.52.0:
![image](https://user-images.githubusercontent.com/107693/53170491-7f86d500-35e0-11e9-85b9-85bcc21509da.png)

**Comment by ansis** [comment]
In order for depth rendering to work correctly the layer needs to specify `"renderingMode": "3d"`. For example:

```
var threeJSModel = {
    id: 'custom_layer',
    type: 'custom',
    renderingMode: '3d'
    ...
};
```

This was not documented anywhere! I've opened a pull request to document this property: https://github.com/mapbox/mapbox-gl-js/pull/7951

@RubioV @Solomka12 can you confirm that this fixes your issues?

@ryanbaumann - https://bl.ocks.org/ryanbaumann/b9725e79b5b1742d92ada00ddbf5c3d3 should start using `"renderingMode": "3d"`

**Comment by ryanbaumann** [comment]
Updated the block example @ansis, thanks for the bug report @rubiov @solomka12 

https://bl.ocks.org/ryanbaumann/b9725e79b5b1742d92ada00ddbf5c3d3/4848a74b67ea1f2b803f587cc9caf8a23e3f83f8

**Comment by RubioV** [comment]
@ansis: yes this fixes the problem, thanks!

**Comment by Solomka12** [comment]
Yes, everything works as it should, thanks!
Now even models in custom layers are part of the map. This can be seen by the way they are displayed with the native `3d-buildings` layer:

`renderingMode: '3d'`
![with3d](https://user-images.githubusercontent.com/19479521/53487422-375e2b80-3a94-11e9-9f10-ac46ec1ef3dc.jpg)

But what if I need this behavior when my model overlaps all other native layers. How do I get this effect now?

`renderingMode: '2d'`
![with2d](https://user-images.githubusercontent.com/19479521/53487620-af2c5600-3a94-11e9-8499-ee07d2a088e4.jpg)

**Comment by ansis** [comment]
@Solomka12 thanks for confirming! Adding this to the top of `render` should work:
```js
gl.clear(gl.DEPTH_BUFFER_BIT);
```

This clears all the depth information previously rendered which lets you draw above the buildings.

**Comment by Nimash68** [comment]
@ansis Hi Ansis, how can i do that?
