### ISSUE TITLE
Cascade undocumented

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#788]

**Comment by lbud** [comment]
Documenting `map.style.cascade` wouldn't be (I think) useful without also documenting mutating the stylesheet with `map.style.layerMap['layerId'].paint['fill-color'] = #f00`…which is not a method per se, but so…is that ok? Or does that present a need for a `Style` method that safely mutates `layerMap` without surfacing it so publicly (like a `map.style.setIn([layerId, 'paint', 'fill-color'], '#f00'`)?
@tmcw @jfirebaugh @edenh

**Comment by jfirebaugh** [comment]
#755 is the ticket for a mutable style property API.

**Comment by michaelsteffen** [comment]
FWIW, when I was playing around with gl-js, I really wanted such an API.  If it would be useful, I'm happy at any point to share thoughts on what this looks like as a newbie learning the library (while recognizing that y'all have probably been over this ground many times already).  And my naive $.02 is that a mutable style property API would be much preferable to surfacing layerMap and cascade . . .

**Comment by lbud** [comment]
Fixed (sort of unintentionally) in https://github.com/mapbox/mapbox-gl-js/commit/487537a0cf2490cc26dd0862f797d2f0d22847d8 but I still don't really think this issue is resolved without a good example; however, given that an example is contingent on the resolution of #755 I'm closing here.

**Comment by lbud** [comment]
⃗ #921
