### ISSUE TITLE
Q: Need to know if these layers are OSM replicated data or mapbox custom for streets V7

### ISSUE THREAD

**Issue by mhuconcern** [mapbox/mapbox-gl-js#7881]
**mapbox-streets-v7**:

### Question
The website states that most layers are osm replicated data apart from #marine_label, #country_label, #state_label, #admin.

The writeup on the website per layer is not very descriptive to know if it is osm replicated data or custom.

"water_label", "road-label", "motorway_junction", "waterway_label", "airport_label", "rail_station_label", "mountain_peak_label", "housenum_label" seem like they are mapbox custom data and "place_label", "poi_label" seem like they use osm tags but i don't know if mapbox modifies this data.

Is it safe to say that the above mentioned ones are OSM replicated data ?

### Links to related documentation

https://docs.mapbox.com/vector-tiles/mapbox-streets-v7/

**Comment by andrewharvey** [comment]
I've seen for OSM objects which have wikidata or wikipedia tags, the mapbox-streets vt's will use the name from wikidata/wikipedia instead of OSM's name tag.

**Comment by mourner** [comment]
Let's keep issues in this repo focused on Mapbox GL JS specifically. For questions about Mapbox Streets, I suggest contacting Mapbox support.
