### ISSUE TITLE
use examples' descriptions in search filter

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#7888]
A while back I submitted a PR #6514

> something that's bugged me for a while is searching for an example by a term not in the title. This PR includes the example description text in that search/filter. This catches a few extra terms like these which would otherwise go exampleless.
> 
> raster base -> Display a satellite map
> geolocate -> Locate the user
> expressions
> switcher -> show and hide layers
> compare -> swipe between maps

It looks like that has regressed in the new docs, I can't find where this logic has moved to in the code, hopefully someone will be able to take a look and re-implement this as it's very helpful for users.

**Comment by katydecorah** [comment]
Thanks @andrewharvey! We added this feature in dr-ui today. I'll likely do a release this week and I will update here as soon as that happens.

**Comment by katydecorah** [comment]
This was added in https://github.com/mapbox/mapbox-gl-js/pull/7909
