### ISSUE TITLE
Markers are hidden on initial zoom level

### ISSUE THREAD

**Issue by wkornilow** [mapbox/mapbox-gl-js#7899]
**mapbox-gl-js version**: 0.53.0

**browser**: Chromium 71.0.3578.98

### Link to Demonstration
https://codesandbox.io/s/810j3nv178

### Actual Behavior
I found a stange bug. Markers are not visible at the initial zoom level. For example, if I initialize a map with zoom === 12, markers will be visible on zoom lower or higher than 12.

**Comment by ParryQiu** [comment]
`loadImage` is a callback function, you should make sure that all your code is in the wrapper of this callback function.

**Comment by peterqliu** [comment]
@ParryQiu is correct, and that seems to resolve the issue. Closing barring further actions
