### ISSUE TITLE
v0.53.0 JavaScript error mapbox-gl.js:29 Uncaught TypeError: e is not a function

### ISSUE THREAD

**Issue by jwoodwardtfx** [mapbox/mapbox-gl-js#7905]
It seems that when fast panning the map on v0.53.0 I sometimes get a Javascript error. It seems to be related to cancelling tile requests that are in progress.

_mapbox-gl.js:29 Uncaught TypeError: e is not a function
    at vu.receive (mapbox-gl.js:29)_

It appears that within "actor.js" it gives an error in the "receive" function:

```
if (data.type === '<response>' || data.type === '<cancel>') {
        callback = this.callbacks[data.id];
        delete this.callbacks[data.id];
        if (callback && data.error) {
            callback(deserialize(data.error));
        } else if (callback) {
**-- ERROR HERE WHEN TRYING TO USE OBJECT CALLBACK AS A FUNCTION ---**
              callback(null, deserialize(data.data));
        }
    }
```

Here **_callback_** is actually an object which contains a single function called "cancel".

It seems that this may have originally come from "makeXMLHttpRequest" (which returns an object containing a single method called cancel).

This didn't happen on v0.52.0.

Thanks,
Joe

**Comment by ryanhamley** [comment]
Are you seeing this in a specific browser(s)? https://github.com/mapbox/mapbox-gl-js/issues/7904 reports the same issue but specifically on Chrome > 66

**Comment by jwoodwardtfx** [comment]
I reproduced this bug on a Chromium build, reporting itself as "Chrome/62.0.3202.9".
