### ISSUE TITLE
Multiple symbol layers not showing symbols at certain zoom levels

### ISSUE THREAD

**Issue by mllava** [mapbox/mapbox-gl-js#7920]
Hi,
I am having issues with a map that has four symbol layers (one for each symbol type: circle, square, triangle, diamond) showing features from one single source, and using filters in each layer depending on the 'shape' attribute.
The problem happens (sometimes, not always!) when displaying the map for the first time, none of the symbols show, but then zooming in and out the appear and disappear for certain zoom levels.
I've managed to replicate the problem in here: https://jsfiddle.net/dqht2wfj/1/  
Mind that the problem happens sometimes, so if it all works well, please try reloading
I'm using Mapbox GL JS 0.53 in Chrome.
I've tried different settings for the symbols layers with no luck. 
Thanks in advance!

### Steps to Trigger Behavior
 1. Load example  
 2. zoom in/out with mouse wheel

### Link to Demonstration
https://jsfiddle.net/dqht2wfj/1/ 

### Expected Behavior
Symbols should be visible for the starting zoom level and zooming all zoom levels within [minzoom, maxzoom]

### Actual Behavior
Symbols appear and disappear for certain zoom levels within [minzoom, maxzoom]

**Comment by mllava** [comment]
Demo from JSfiddle
[190218_symbols.mp4.zip](https://github.com/mapbox/mapbox-gl-js/files/2875610/190218_symbols.mp4.zip)

**Comment by ryanhamley** [comment]
See https://github.com/mapbox/mapbox-gl-js/issues/7899. `loadImage` is a callback method and you should move the code that depends on the image inside the callback as seen in the JSFiddle in the linked issue.
