### ISSUE TITLE
How to setLayoutProperty with a coalesce function ?

### ISSUE THREAD

**Issue by ststeiger** [mapbox/mapbox-gl-js#7928]
**mapbox-gl-js version**: 
```
module.exports = { "version": "0.35.1" }
```

### Question
I want to set the label-texts on my map to this formula:
`coalesce(user_specified_language, en, native)`

I'm using mapbox-gl with leaflet. 
I tried with mapox-gl-language
```
<script src="libs/mapbox/mapbox-gl-language.js"></script>

var lingua = new MapboxLanguage({ defaultLanguage: 'ru' })
gl._glMap.addControl(lingua);
```

but this had absoluetly no effect. 

Then i tried to do it myselfs, with setLayoutProperty. 
I have successfully altered the language (the country name shows in cyrillic when I set it to Russian), but I cannot figure out how to use "coalesce" with multiple field values in setLayoutProperty.   
All I can do is to concat the values, which is not what I want. 
```
        gl._glMap.on('load', function () {
            var keys = Object.keys(gl._glMap.style._layers);

            for (var i = 0; i < keys.length; ++i) {
                if (gl._glMap.style._layers[keys[i]].layout["text-field"]) {

                    if (gl._glMap.style._layers[keys[i]].layout["text-field"].indexOf("name") != -1)
                    {
                        console.log(keys[i], gl._glMap.style._layers[keys[i]].layout["text-field"]);
                        // debugger;
                        gl._glMap.setLayoutProperty(keys[i], 'text-field', ["coalesce", ["get", "latin"], ["get", "nonlatin"]]);
                        //gl._glMap.setLayoutProperty(keys[i], 'text-field', '{name:ru}');
                        // gl._glMap.setLayoutProperty(keys[i], 'text-field', '{name:ru}', '{name:latin}');
                        // gl._glMap.setLayoutProperty(keys[i], 'text-field', 'coalesce({name:ru}, {name:latin})');

                        // gl._glMap.setLayoutProperty(keys[i], 'text-field', ["coalesce", ["string", ["get", "name:ru"]], ["string", ["get", "name:latin"]]]);

                    }
                    
                }

                
            }
```

if I use the coalesce array, as adviced via google-search, all I get is

> mapbox-gl.js:14766 Error: layers.place-country-1.layout.text-field: string expected, array found
>     at Function.module.exports.emitErrors (mapbox-gl.js:11779)
>     at e.i._validate (mapbox-gl.js:11495)
>     at e.i.setLayoutProperty (mapbox-gl.js:11386)
>     at t.setLayoutProperty (mapbox-gl.js:11131)
>     at e.setLayoutProperty (mapbox-gl.js:14162)
>     at e.<anonymous> ((index):226)
>     at e.Evented.fire (mapbox-gl.js:14763)
>     at e._render (mapbox-gl.js:14221)

I have now googled and tried for the better part of 3 hours, but nothing - so I give up here if nobody can help me. 

This is the full page
https://github.com/ststeiger/VectorTileServer/blob/master/VectorTileServer/wwwroot/index.htm

The vector-tile server can be run with [Rider](https://www.jetbrains.com/rider/download/) or [Visual Studio Community Edition](https://visualstudio.microsoft.com/vs/community/).

**Comment by mourner** [comment]
The v0.35.1 version of GL JS is two years old — expressions for `text-field` likely weren't supported at the time. Please upgrade to the newest version, and I'll reopen the issue if you still have trouble.

**Comment by ststeiger** [comment]
Ah, crap, I forgot. 
I downloaded mapbox-gl from the sample-page, because in the github-releases there is only the source that needs to be built. 
I've now downloaded the latest stable version from the CDN, and now it works. 

The docs at 
https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-field
say 

> data-driven styling: >= 0.33.0 ...

apparently this is not the same.

**Comment by mourner** [comment]
@ststeiger yeah, that was with the old-style property function syntax; expressions only appeared in v0.41+ (https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-coalesce)
