### ISSUE TITLE
queryRenderedFeatures Cluster coordinates

### ISSUE THREAD

**Issue by B-Henderson** [mapbox/mapbox-gl-js#7932]
**mapbox-gl-js version**: 0.42.2

### Question

I'm trying to use queryRenderedFeatures on moveend to get the geometry of all rendered clusters. I am able to get the clusters correctly but in the return I can't seem to be able to get their coordinates. The clusters render correctly and work as intended I just can't seem to get their coordinates.

https://i.gyazo.com/6681e47bf5c539c7654704b7bcfc2c35.png

In the screenshot is what is returned after I call:

```
map.on('moveend', 'clusters', e => {

        let a = map.queryRenderedFeatures({
          layers: ['clusters']
        });
        a.forEach(array => {
          console.log(array)
        })
});
```

Is there anyway to get the coordinates of each rendered cluster?

Thanks,
Ben

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures

**Comment by B-Henderson** [comment]
It was because the coordinates geometry is inherited by the object and can be referenced just as

 `object.geometry.coordinates `

using this I was able to get a clusters coordinate.

Sorry about that, feel free to close

**Comment by mourner** [comment]
Yeah. This is because geometry is decoded lazily for performance reasons, so it is stored in binary format until you access it directly.
