### ISSUE TITLE
Return all features from a vector tile layer regardless of current view

### ISSUE THREAD

**Issue by courlu** [mapbox/mapbox-gl-js#7933]
### Question

So i'm trying to access all the features from a vector tile layer but have hit the issue of _queryRenderedFeatures_ and _querySourceFeatures_ only returning what is in the visible map viewport. 

**An example use case:**
I want to zoom to the full extent of filtered features in a layer. So i need to iterate features to construct a bounding box, but I need this to work independent of the viewport. (e.g. i need it to zoom out if the filtered features aren't all within the current viewport) 

Is this in any way possible? It's not clear from the documentation how I can access the features of vector tiles that aren't currently being rendered.

**Comment by mourner** [comment]
Can you elaborate on how you expect this to work? Do you mean features that are included in the tiles loaded in the current viewport, but placed just outside of it?

**Comment by courlu** [comment]
I mean to access _every_ feature globally in the layer, regardless of which tiles are rendered.

**Comment by mourner** [comment]
This is just not possible technically. Would you expect the browser to request potentially thousands of tiles from the server on a single query?
