### ISSUE TITLE
Style validation fails for fraction number without a leading 0

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#7935]
**style-spec version**: 13.6.0

### Steps to Trigger Behavior / Demonstration

[`gl-style-validate`](https://www.npmjs.com/package/@mapbox/mapbox-gl-style-spec#gl-style-validate) the following style:

```
{
    "version": 8,
    "sources": {
        "composite": {
            "url": "mapbox://mapbox.mapbox-streets-v7",
            "type": "vector"
        }
    },
    "layers": [
        {
            "id": "water",
            "type": "fill",
            "source": "composite",
            "source-layer": "water",
            "paint": {
              "fill-color": "rgb(158,189,255)",
              "fill-opacity": .9
             }
        }
    ]
}
```

### Expected Behavior

Style validation throws no error, because the library works with fraction numbers without leading `0`, see codepen example in https://github.com/mapbox/mapbox-gl-js/issues/7925#issue-411739072.

### Actual Behavior

Style validation throws an error, because there is a fraction number without a leading `0` for 
`fill-opacity`:

![image](https://user-images.githubusercontent.com/20856381/53117262-c924e080-354a-11e9-8b57-e2bab42b9956.png)

**Comment by mourner** [comment]
This is because it has to be a valid JSON. `.9` notation is not a part of JSON spec. Check here: https://jsonlint.com/
