### ISSUE TITLE
remove marker on popup close causes infinite loop

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#7938]
**mapbox-gl-js version**:
0.53

**browser**: 
Firefox

### Steps to Trigger Behavior

 1. Open popup
 2. Close popup

### Link to Demonstration
https://jsbin.com/nelaqorayi

### Expected Behavior
Marker removed on popup close.

### Actual Behavior
Infinite loop and crash on popup close.

**Comment by tayyab-1** [comment]
@3zzy  Did you find a solution to this? I am facing the same problem.

**Comment by gustavoazo** [comment]
Been a long time since OP but....Same behaviour here:

My code:

```
 newMarkerPopup.on('close', (e) => {
                newMarkerOnMap.remove();
            });
```

Browser console (MS EDGE) says:

```
util.ts:318 
 Uncaught RangeError: Maximum call stack size exceeded
    at Popup.<anonymous> (map_functions.js:508:32)
    at Popup.<anonymous> (map_functions.js:508:32)
```

I'm just following mapbox docs:

![Image](https://github.com/user-attachments/assets/7815613f-4262-4678-a8b0-e8158b19e798)
