### ISSUE TITLE
Fix rendering artifacts with round line joins and semi-transparent or gap-width lines

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#794]
test case: https://www.mapbox.com/bites/00059/#15.1/36.9060/-76.0800

![image](https://cloud.githubusercontent.com/assets/3170312/4763594/11ce107e-5b14-11e4-94a9-6119d58808a9.png)

![image](https://cloud.githubusercontent.com/assets/3170312/4763573/d7818f9a-5b13-11e4-9f9f-7ee7a3999e93.png)

**Comment by lbud** [comment]
More clearly:
![image](https://cloud.githubusercontent.com/assets/3170312/5962955/b4a0b016-a79c-11e4-9aed-67488b2fd39c.png)
![image](https://cloud.githubusercontent.com/assets/3170312/5962963/cd9cc82a-a79c-11e4-90a2-b1e4652ae8bf.png)

**Comment by ljbade** [comment]
I have noticed this in native too. Came up recently when my line dashes were bugging out but still see it on other transparent lines.

**Comment by ansis** [comment]
We now skip adding round joins for shallow joins where miters are indistinguishable from round joins. This removes most of the dots within a segment. There are still overlapping dots where different segments overlap:

![screen shot 2015-06-26 at 12 32 23 pm](https://cloud.githubusercontent.com/assets/1421652/8375656/ab5d6f30-1bff-11e5-9afe-8e6684538e04.png)
*all roads in the image have `"line-join": "round"`*

We could make the tessellation slightly more complicated to get rid of all overlap within a segment, but I don't think this matters if we don't also get rid of overlap across different segments.

For overlap between different segments there are two ways this could be done:
- draw into a separate texture first, then composite it. We tried this. It's too slow.
- prevent double drawing with the depth buffer. With this approach lines would be drawn twice. Once for the solid part and once for the antialiased/blurred edge. There would still be tiny 1px artifacts where the antialiased/blurred edges for different features overlap, but I don't think we can avoid that without having a huge performance cost. Something similar could be implemented for polygons.

**Comment by mourner** [comment]
It seems like currently only sharp corners have this problem:

![image](https://user-images.githubusercontent.com/25395/58196975-09c00180-7cd4-11e9-82db-4da2ecae66f9.png)

**Comment by mourner** [comment]
Closing as we addressed this well enough it seems.
