### ISSUE TITLE
Road Can not Render normally on some tiles.

### ISSUE THREAD

**Issue by cdqrain** [mapbox/mapbox-gl-js#7947]
Hello everyone, I'm a newbie of Mapbox GL user. I generated the map vector tile all by myself. Then use Mapbox GL to render the map. Now, I meet a strange problem on some tiles when zoom > 17. It looks like this: _http://lbs.fjmap.net/map/assets/map_bug.png_
The zoom level < 17, It looks very well. Can anyone help me, what happened on the vector tile ?

**Comment by mourner** [comment]
This looks like a lack of buffers around tiles. You can see more clearly what's going on by setting `map.showTileBoundaries = true;`. Geometry should be clipped with a buffer (not on the exact boundary) to ensure seamless transition between tiles.
