### ISSUE TITLE
Unable to preventDefault inside passive event listener invocation

### ISSUE THREAD

**Issue by gDev95** [mapbox/mapbox-gl-js#7957]
Since nobody has attempted to answer my question on `stackoverflow`, I would like to post the link to my post to gain some more insights from you on here. Since this error is thrown in `mapbox-gl-js` I think its more related to this repo than to [ngx-mapbox-gl](https://github.com/Wykks/ngx-mapbox-gl). 

This error is thrown everytime i scroll or move into or on the map and I was not able to reproduce this in stackblitz , that is why I do not assume you guys can solve this but rather look for a hint to *WHY* this could happen since I have not done anything apart from `npm install ngx-mapbox-gl mapbox-gl@0.52.0 --save`
[my stackoverflow post](https://stackoverflow.com/questions/54863822/unable-to-preventdefault-inside-passive-event-listener-invocation-when-scrolli)

**Comment by mourner** [comment]
Can you provide a minimal reproducible test case for this that demonstrates that it's a GL JS issue (e.g. without Angular, etc.)? The stack trace doesn't mean much without context.

**Comment by gDev95** [comment]
@mourner Thank you for the quick response but unfortunately I tried to reproduce it, in my case a test case could just the displaying the map. But I tried this and it was not reproducible. So I assume there is no easy answer to what **could** (*not does*) cause this issue. I will try over at [ngx-mapbox-gl](https://github.com/Wykks/ngx-mapbox-gl) if someone has an idea, even though I guess they won't either :/

**Comment by nisimjoseph** [comment]
I experience the same issue in Android Chrome WebView. the only way I could `event.preventDefault()` for those events is to listen by passive=false, fir example:
`document.addEventListener('touchmove', handleTouchMove, {passive:false, capture:true});`
And I got times where the `touchmove` is not fired and the event which is fired is `pointermove`, so I am using both.

**Comment by AxemaFr** [comment]
Had same problem with "mousemove" event.

I didn't dig deep into it, but here's my workaround solution:

It has something to do with zone.js, that is provided with Angular.

Disabling zone.js by patching it __zone_symbol__UNPATCHED_EVENTS flag with 'mousemove' did the trick for me.

You can read more about it [here](https://github.com/angular/angular/blob/main/packages/zone.js/lib/zone.configurations.api.ts) or [here](https://stackoverflow.com/questions/60532445/angular-8-disabling-specific-events-from-being-checked-on-polyfills-ts-isnt-wo)
