### ISSUE TITLE
Support .tls

### ISSUE THREAD

**Issue by BuddyNik** [mapbox/mapbox-gl-js#7958]
Hello! Does the mapbox-gl-js work with **.tls** files?

I am interested [satelite ](https://docs.mapbox.com/mapbox-gl-js/example/setstyle/), but with **3D houses**. [Example](https://www.youtube.com/watch?v=WJhRVrJXO3E).

**Comment by mourner** [comment]
No, but you can use the `CustomLayer` interface to draw custom 3D features on the map. Here's an example using ThreeJS: https://github.com/mapbox/mapbox-gl-js/blob/master/debug/threejs.html

**Comment by BuddyNik** [comment]
Thanks for the answer.

Is this the only way?

**Comment by mourner** [comment]
At the moment, yes.

**Comment by BuddyNik** [comment]
Thanks.

**Comment by BuddyNik** [comment]
Maybe someone will come in handy. This is not the only [way](https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=Bloom.html).

![1](https://user-images.githubusercontent.com/36342741/53500126-c8e09400-3aba-11e9-9333-6dbb54f051b4.PNG)
