### ISSUE TITLE
MultiLineString feature disappears after zooming out

### ISSUE THREAD

**Issue by bart-1990** [mapbox/mapbox-gl-js#7960]
I have a MultiLineString feature which disappears as soon as the zoom level is 8 or lower. 
Maybe this is happening because the line strings are very short? I tried adjusting the maxzoom and minzoom level of the layer, but that did not help.

**mapbox-gl-js version**: 0.53.0

**browser**: Chrome

### Link to Demonstration

https://jsbin.com/yiyijisemi/edit?html,output

### Expected Behavior
Line stays visible.

### Actual Behavior
Line disappears.

**Comment by mourner** [comment]
You need to make simplification `tolerance` smaller (or set it to `0` to disable simplification). By default, lines that are too small are filtered out.

**Comment by bart-1990** [comment]
Thanks for the answer, this fixed my issue. :)
