### ISSUE TITLE
CustomLayerInterface min/maxzoom for 3d (gltf) objects

### ISSUE THREAD

**Issue by vcebotari** [mapbox/mapbox-gl-js#7965]
**mapbox-gl-js version**: 0.52.0

### Question

is where a way to set min/maxzoom for 3d(gltf) objects, added through 
`CustomLayerInterface` ?

now 3d elements are render on every zoom, but i don't want to render it before 15 zoom(for example)

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/api/#customlayerinterface

**Comment by ansis** [comment]
I think `minzoom` and `maxzoom` are worth adding to CustomLayerInterface for consistency. In the mean time, you can just the current zoom level in `render` and choose no to render it if the zoom is too low.

```
onAdd: function(map) {
    this.map = map;
},
render: function(gl, matrix) {
    if (this.map.getZoom() < 15) return;
    ...
}
```

**Comment by vcebotari** [comment]
@ansis, sounds like a not bad workaround, thanks!

**Comment by karimnaaji** [comment]
@vcebotari you should be able to add zoom range caps on your layer by calling [`setLayerZoomRange`](https://docs.mapbox.com/mapbox-gl-js/api/#map#setlayerzoomrange) on your map.

This would suspend calls to your custom style `render` function.

```
map.addLayer(new MyCustomLayer());
// suspend the layer rendering after zoom 15 and before zoom 24
map.setLayerZoomRange('my-later-id', 15, 24);
```

I'll go ahead and close this issue, but I believe @ansis workaround or this API should be enough for your use case, feel free to reopen if it doesn't work out!
