### ISSUE TITLE
setRTLTextPlugin does not work on Chrome

### ISSUE THREAD

**Issue by jvence** [mapbox/mapbox-gl-js#7968]
mapboxgl.setRTLTextPlugin('https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.0/mapbox-gl-rtl-text.js'); throws the following error in Chrome (works fine with Safari and Firefox):

Refused to execute script from 'blob:https://....' because its MIME type ('') is not executable.

**Comment by mourner** [comment]
Hmm, can you share a live test case where the error occurs, and also add more details about your OS / browser version / etc.? The official example with the RTL plugin seems to work fine in Chrome: https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/
