### ISSUE TITLE
mapbox.once event gives  Uncaught TypeError

### ISSUE THREAD

**Issue by sumitparkash** [mapbox/mapbox-gl-js#7975]
**mapbox-gl-js version**
:0.53.0

I have added a layer in the mapbox having 3 points.

I want to show a popup on click of the point only once. For that, I have used the mabpox **once** event  as defined in documentation
https://docs.mapbox.com/mapbox-gl-js/api/#evented#once

However, when you click on the point it gives you error
**evented.js:121 Uncaught TypeError: s.call is not a function
    at r.dt.fire (evented.js:121)**

this is the code I used
`map.once('click', id, function (e) {
                    var coords = getMarkerLatLng(e, type);
                    new mapboxgl.Popup()
                            .setLngLat(coords)
                            .setHTML("Pooint Clicked")
                            .addTo(map);
                })`

If you change the **once** event with the **on**  event , then everything works fine.  .i.e this code works fine. 
`map.on('click', id, function (e) {
                    var coords = getMarkerLatLng(e, type);
                    new mapboxgl.Popup()
                            .setLngLat(coords)
                            .setHTML("Pooint Clicked")
                            .addTo(map);
                })`

But this function will be called every time. I need to call the function only  once when the user click on the point for the first time. 

I have created a  js fiddle to demonstrate the issue
https://jsfiddle.net/devsumitparkash/x5rk1n83/

Also wanted to know is there a way to send  extra data to the  mapbox click event like we have in jquery
`$('.leadtoscore').on('click', {event_type: 'shot'}, add_event);`

**Comment by ansis** [comment]
It looks like `once` only supports two arguments:

`map.once('click', function(e) { ... });`

There is a special version of `on` implemented for `Map` that supports the third (middle) layer argument. @mourner should we support a three argument version of map.once?

@sumitparkash in the mean time you could use `map.off` within your callback function to remove the event listener. Or you could use the two argument version and manually call `queryRenderedFeatures` with your layer id within the callback.

**Comment by mourner** [comment]
> @mourner should we support a three argument version of map.once?

I think we should, for consistency.

**Comment by sumitparkash** [comment]
@ansis  thanks for your suggestion. Already using `map.off` .
But Still you be nice if `map.once()` behaves same as `map.on`
