### ISSUE TITLE
Custom Basemap overlap other layer

### ISSUE THREAD

**Issue by mikahoy045** [mapbox/mapbox-gl-js#7980]
How to put custom basemap like openlayers or leaflet (but this is my own) raster files example :
`http://blablabla.bla/{z}/{x}/{y}.png`

I tried to insert it using :
```
map.addSource('bla.tile',{
		'type': 'raster',
		'tiles': ['http://blablabla.bla/{z}/{x}/{y}.png'],
		'tileSize': 150
	})

map.addLayer({
		'id': 'bla',
		'type': 'raster',
		'source': 'bla.tile'
	})
```

it works but it overlapp my feature / other shape that load (since it's a basemap).

**Comment by jingsam** [comment]
![image](https://user-images.githubusercontent.com/1522494/53690052-210ae500-3d9e-11e9-9f14-2b089031ac97.png)

**Comment by mikahoy045** [comment]
Thank you, so I had to declare the before again each time I add new layer? example I dont want Mapbox basemap style I just want my own Raster Tiles to be basemap how to declare it once to became the base (the last bottom layer)? Is it not applicable in **new mapboxgl.Map()**? since map [compare](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-compare/) only works for that function.

**Comment by andrewharvey** [comment]
close posted https://gis.stackexchange.com/questions/314149/put-custom-xyz-tile-in-mapbox

**Comment by andrewharvey** [comment]
I think what you'll find better is just creating your own style object when you initialise the map with your raster tiles. Then any other layers you add after will go on top.

See https://docs.mapbox.com/mapbox-gl-js/style-spec/ and https://docs.mapbox.com/mapbox-gl-js/example/image-on-a-map/

**Comment by andrewharvey** [comment]
Either way I'll close this as it doesn't appear to be a bug or feature request.
