### ISSUE TITLE
Marker().getLngLat doesn't take offset into consideration? 

### ISSUE THREAD

**Issue by katfchan** [mapbox/mapbox-gl-js#7982]
**mapbox-gl-js version**: 1.0.9

**browser**: Chrome 72.0.3626.119 (Official Build) (64-bit)

### Steps to Trigger Behavior

```
    var markerOffset = new mapboxgl.Marker()
      .setLngLat(center)
      .setOffset(this.props.offset)
    var markerNoOffset = new mapboxgl.Marker()
      .setLngLat(center)
    console.log(`markerOffset longlat: ${markerOffset.getLngLat()}`);
    console.log(`markerNoOffset longlat: ${markerNoOffset.getLngLat()}`);
```

### Expected Behavior
I would have thought each of the above markers would return a `LngLat` with different coordinates

### Actual Behavior
They return the same coordinates

Is this the intended behavior? Is there a way for users to calculate any give coordinates if they already have a px offset?

**Comment by andrewharvey** [comment]
This is the intended behaviour.

I guess you could use [`map.project`](https://docs.mapbox.com/mapbox-gl-js/api/#map#project) to get the pixel coordinates for the marker's LngLat, then add your offset, then `map.unproject` to get back the lng, lat for the offset location.

**Comment by katfchan** [comment]
Oh, that works. Thank you so much!
