### ISSUE TITLE
Get the position of a symbols icon or text AFTER translate, etc?

### ISSUE THREAD

**Issue by wysisoft** [mapbox/mapbox-gl-js#7984]
I run queryRenderedFeatures and I pick up on symbols inside of a BBOX, and I want to know the exact position of these symbols so I can place a popup at that location, but I can only seem to get the feature position from the features returned from queryRenderedFeatures, not the "after translate and padding and etc" position of the icon or text rendering of the symbol. Any Ideas?

**Comment by andrewharvey** [comment]
I think you'd need to check the layers style spec translate values and then also apply them to the popup offset.
