### ISSUE TITLE
Enable setFeatureState with string ids

### ISSUE THREAD

**Issue by lanlugar** [mapbox/mapbox-gl-js#7986]
## Motivation
I have want to setFeatureState of wfs layers gotten directly from mapbox, i am using the name of the feature to set the id, so i can easily reference the layer, however mapbox setFeatureState apparently doesn't work with string ids

**Comment by ryanhamley** [comment]
Feature IDs such as those provided to `setFeatureState` can be a string, but the string has to be directly convertible to a base ten number. So `'1234'` is a valid feature ID but `'myID'` or a hex number wouldn't be. This is a technical limitation of the current vector tile specification.

**Comment by davidgilbertson** [comment]
"...can be a string, but the string has to be directly convertible to a base ten number. So '1234' is a valid feature ID but 'myID' or a hex number that includes letters wouldn't be. This is a technical limitation of the current vector tile specification"

It would be great to have that description [in the setFeatureState description](https://docs.mapbox.com/mapbox-gl-js/api/#map#setfeaturestate), as a note next to 
![image](https://user-images.githubusercontent.com/4443482/59887320-3c116b80-9406-11e9-8f39-3978f2421c9a.png)

I think it's caused many people many hours of head scratching.
