### ISSUE TITLE
Line-width does not change when zooming

### ISSUE THREAD

**Issue by mapy42130** [mapbox/mapbox-gl-js#799]
Hi there !

I'm using https://github.com/ElectronicChartCentre/java-vector-tile to encode tiles generated from OpenStreetMap data, and drawing them with the mapBox CSS styles bright-v4.json (from https://www.mapbox.com/mapbox-gl-styles/styles/bright-v4.json).
I have an issue that concerns zooming and styling.
See below:

![sc1](https://cloud.githubusercontent.com/assets/6999772/4827507/ff74b298-5f78-11e4-8236-f60e91fc4e8d.png)
I run my program with a zoom initialized at z = 2. Everything's alright.

![sc2](https://cloud.githubusercontent.com/assets/6999772/4827593/ab0bf8aa-5f79-11e4-8171-26cb57352898.png)
When I'm zooming by z = 15, roads drawn are only lines and buildings are only grey squares.
To get good styling I have to initialize my map at z = 18 or more. The CSS style becomes ok.

![sc3](https://cloud.githubusercontent.com/assets/6999772/4827819/3af33b30-5f7b-11e4-999f-0c8947c60e2f.png)
This is what it should look like. But even when I initialize at z = 18, when I zoom out, roads width doesn't change. 

![sc4](https://cloud.githubusercontent.com/assets/6999772/4827889/b7fc5c7e-5f7b-11e4-845d-bfb7977c4532.png)

Have you ever seen this issue? 

Thanks for your help,
Yoann

**Comment by jfirebaugh** [comment]
http://dev.business-geografic.com:9000/ is no longer accessible. Is this still an issue?

**Comment by fnicollet** [comment]
Not really, it must be something strange because in other tests, when generating tiles, it works just fine. You can close this issue, thanks
