### ISSUE TITLE
"Layer with id 'foo' does not exist on this map" in "moveLayer"

### ISSUE THREAD

**Issue by dieterdreist** [mapbox/mapbox-gl-js#7991]
**mapbox-gl-js version**:
v0.53.1

**browser**:
Firefox

### Steps to Trigger Behavior

 1.use the map.moveLayer function 
 2.
 3.

### Link to Demonstration

https://jsbin.com/

### Expected Behavior
no error

### Actual Behavior
Error: "Layer with id "marine-label-lg-pt" does not exist on this map."

in the console, I can see the layer is there (also: it worked before upgrading to 0.53.1)
and I can see that the command fails:

map.getLayer("marine-label-lg-pt"); // WORKS
Object { id: "marine-label-lg-pt", type: "symbol", visibility: "visible", _featureFilter: _featureFilter(), metadata: {…}, minzoom: 1, maxzoom: 4, source: "composite", sourceLayer: "marine_label", filter: (3) […], … }

map.moveLayer("bridge-motorway-2", "marine-label-lg-pt");  // FAILS

Error: "Layer with id "marine-label-lg-pt" does not exist on this map."
    moveLayer https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js:33 moveLayer https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js:33 <anonymous> debugger eval code:1 

mapbox-gl.js:29:16457

    fire https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js:29 moveLayer https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js:33 moveLayer https://api.tiles.mapbox.com/mapbox-gl-js/v0.53.1/mapbox-gl.js:33 <anonym> debugger eval code:1 

The same code works in v.0.53.0
map.moveLayer("bridge-motorway-2", "marine-label-lg-pt"); // WORKS
replies (no error):
Object { _moving: true, _zooming: true, transform: {…}, _bearingSnap: 0, _renderFrameCallback: (), _interactive: true, _maxTileCacheSize: null, _failIfMajorPerformanceCaveat: false, _preserveDrawingBuffer: false, _trackResize: false, … }

**Comment by peterqliu** [comment]
@dieterdreist can you make a minimal test case that reproduces this error?

**Comment by dieterdreist** [comment]
in the meantime it happened on v0.53.0 as well, so it may be a different issue, I’ll let you know when I found out more, maybe it’s a bug in my app.
