### ISSUE TITLE
How can I temporarily deactivate map interaction?

### ISSUE THREAD

**Issue by dieterdreist** [mapbox/mapbox-gl-js#7992]
**mapbox-gl-js version**:

### Question
How can I temporarily deactivate map interaction? I have some animations where I do not know exactly how long they will take (flyTo with speed), and I would not want the user to interrupt these animations, i.e. no keyboard, click, touch or similar should interrupt the flyTo animation.

When the flyTo is done, I would like to reenable user interaction with the map.

**Comment by peterqliu** [comment]
`options.interactive` https://docs.mapbox.com/mapbox-gl-js/api/#map

**Comment by dieterdreist** [comment]
But that’s on creation time only, or am I misguided? I found changing the map’s _interactive property later on had no effect on the interactivity.

**Comment by peterqliu** [comment]
@dieterdreist ah you're correct. Have you tried modulating this on the CSS side with `pointer-events: none` on the map element?

**Comment by dieterdreist** [comment]
great hint, this works. Thank you!

**Comment by smohanty92** [comment]
I'm trying to do the opposite..enable `interactive` how do I that? I just want to move the map with arrow keys
