### ISSUE TITLE
How to Place Frame Cache on Screen？

### ISSUE THREAD

**Issue by herewaitting** [mapbox/mapbox-gl-js#7994]
**mapbox-gl-js version**:
0.53.0
### Question
I have a frame cache that can now be added as a custom layer, but the following will happen, so I want to know how to draw directly into the screen, not as a custom layer.

### Links to related documentation
![_20190306165810](https://user-images.githubusercontent.com/22114883/53868640-7579c300-4031-11e9-99dc-96e358efb9d3.png)
![_20190306165824](https://user-images.githubusercontent.com/22114883/53868647-77438680-4031-11e9-927f-f296d8bcf1bd.png)

**Comment by vakila** [comment]
Hi @herewaitting! Thanks for reaching out. As the team requested more information and we haven't heard back in over a month, we're going to close this issue. If you want to reopen it, please:
  - Ensure you can reproduce the issue using the latest release.
  - Check the console for relevant errors and warnings.
  - Include a link to a minimal demonstration of your code. We recommend using https://jsbin.com.
  - Include links to the specific section(s) of the documentation where you would have expected to find an answer to this question.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.

Thank you!
