### ISSUE TITLE
Get Features points details associated to Layer

### ISSUE THREAD

**Issue by nimmanapallivenu** [mapbox/mapbox-gl-js#7997]
**mapbox-gl-js version**:

### Question
How to get list of feature that are available in selected layer. i can able to get number of features count but not able to get each and every features details 

 map.addLayer({
        id: "drivers",
        type: "circle",
        source: "drivers_info",
        filter: ["has", "point_count"],
        paint: {
            // Use step expressions (https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-step)
            // with three steps to implement three types of circles:
            //   * Blue, 20px circles when point count is less than 100
            //   * Yellow, 30px circles when point count is between 100 and 750
            //   * Pink, 40px circles when point count is greater than or equal to 750
            "circle-color": [
                "step",
                ["get", "point_count"],
                "#51bbd6",
                100,
                "#f1f075",
                750,
                "#f28cb1"
            ],
            "circle-radius": [
                "step",
                ["get", "point_count"],
                20,
                100,
                30,
                750,
                40
            ]
        }
    });
 // inspect a cluster on click
    map.on('click', 'cluster-drivers', function (e) {
        var features = map.queryRenderedFeatures(e.point, { layers: ['cluster-drivers'] });
        
        new mapboxgl.Popup()
        .setLngLat(e.features[0].geometry.coordinates)
        .setHTML('<b>Number of Drivers</b> ' +e.features[0].properties.point_count)
        .addTo(map);
    });

**Comment by mourner** [comment]
You're probably looking for this: https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources-geojson-clusterProperties

**Comment by risharde** [comment]
That does not solve trying to get all features within a layer - is this even possible with mapbox? Been googling and can't seem to find a direct answer.
