### ISSUE TITLE
Using functions inplace of expressions

### ISSUE THREAD

**Issue by aaomidi** [mapbox/mapbox-gl-js#8001]
**mapbox-gl-js version**: 0.53.1

### Question

Why can't I use functions on fields that can have expressions?

Let's say I'm creating a `symbol` layer in mapbox. I want to change the text based on the values that "create" the symbol.

I would like to do something like:

``` javascript
        map.addLayer({
          id: 'cluster-tds',
          type: 'symbol',
          source: 'tds',
          filter: ['has', 'point_count'],
          layout: {
            'text-field': function (feature_group) {
              console.log(feature_group)
              return 'abc' // Some calculation done using feature_group
            },
            'text-font': ['DIN Offc Pro Medium', 'Arial Unicode MS Bold'],
            'text-size': 12
          }
        })
```

To give you more context, I'm trying to make the text-field there, the average of TDS (Total Dissolved Solids) values defined in layers/sources above it. As shown here:

``` javascript
map.addSource('tds', {
          type: 'geojson',
          data: datahandler.getGeoJSON(),
          cluster: true,
          clusterMaxZoom: 14,
          clusterRadius: 50
        })
        map.addLayer({
          id: 'clusters',
          type: 'circle',
          source: 'tds',
          filter: ['has', 'point_count'],
          paint: {
            'circle-color': [
              'step',
              ['get', 'point_count'],
              '#C6C013',
              5, // count
              '#ef8a17',
              20, // count
              '#ef2917'
            ],
            'circle-radius': [
              'step',
              ['get', 'point_count'],
              20,
              5, // count
              30,
              20, // count
              40
            ]
          }
        })
```

I would like to access the FeatureGroup that constitute the Label. Average out the TDS values that were defined in the properties of the `tds` source. And display it as the label to the viewer.

**Comment by mourner** [comment]
Due to various technical limitations, the style spec can only be pure JSON — no arbitrary functions allowed. As a workaround, you could generate a GeoJSON source dynamically and create a layer based on it.

**Comment by aaomidi** [comment]
Thank you for responding @mourner. Is what I suggested even possible? Averaging out the value of a FeatureGroup and displaying it as the "symbol" for a cluster? If so do you have any documentation you can refer me to?

**Comment by mourner** [comment]
You can try using [clusterProperties](https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources-geojson-clusterProperties) first, and if that's not enough, you'll probably have to use [source.getClusterLeaves](https://docs.mapbox.com/mapbox-gl-js/api/#geojsonsource) method to get all the children of a cluster, do some calculation and generate a new point in a GeoJSON source you'll use for an additional label layer.
