### ISSUE TITLE
Support zoom-driven styling for icon-allow-overlap

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#8002]
## Motivation

I have several times run into this problem where I want to have icon-allow-overlap behave differently at different zooms for a key dataset:

* Low zoom: `false`, so the map isn't overwhelmed with a sea of overlapping icons
* High zoom: `true`, so every point is visible, and isn't blocked by some irrelevant icon or text in the basemap.

## Design Alternatives

The only workaround I have is two different layers with disjoint minzoom/maxzoom.

### Mock-Up

Like every other zoom-driven function.

**Comment by peterqliu** [comment]
All layout properties should support zoom-driven styling 🤔 @stevage can you make a test case showing it not working?

**Comment by stevage** [comment]
Oh, it does work, huh. I was misled by the documentation which says that "basic functionality" is implemented but "data-driven styling" is not supported. I assumed zoom-driven behaviour came under "data-driven styling" but I guess not.
