### ISSUE TITLE
Example for using `fill-pattern`

### ISSUE THREAD

**Issue by flawyte** [mapbox/mapbox-gl-js#8004]
The docs for the iOS SDK contains [an example](https://docs.mapbox.com/ios/maps/examples/fill-pattern/) of using the `fill-pattern` property along with an image of our choice. However the Mapbox GL JS doc doesn't, so I thought it would be great to add one, especially given that it's pretty simple to do once you know how, but it's not the same when there's no example and you have to figure out by yourself by reading the API documentation.

I could even submit a PR to get you started if you want.

**Comment by ryanhamley** [comment]
Hey @flawyte we always welcome new examples and PRs! To point you in the right direction, examples live in https://github.com/mapbox/mapbox-gl-js/tree/master/docs/pages/example and require an html file as well as a js file with some description information. You should be able to just follow the existing examples pretty easily.

**Comment by flawyte** [comment]
Thanks @ryanhamley! I'll try to take a look next week :)

**Comment by flawyte** [comment]
What image should I use for the pattern? I thought about using the Mapbox compact logo ; I'd copy it from `/src/css/svg/` to `/docs/pages/assets/` to use it in my code.

**Comment by ryanhamley** [comment]
Hey @flawyte The cat image is fine to use. For the `pixelRatio` question, it might require a bit more research but it could be a bug. If you think it is, it would be great if you could produce a minimal reproduction of it with JSBin and open a new issue.

As for the blurriness, that would be expected on an image at fractional zoom levels. Images are updated only at integer zoom levels and then scaled between zoom levels, inevitably leading to some degree of blurriness.

**Comment by flawyte** [comment]
Done! Here's the issue about the `pixelRatio` thing : #8020

About the blurriness, it behaves just like you describe expect for the default zoom level, `0`, where it's blurry by default. That's actually the zoom level on the screenshot.
I added `zoom: 1` when creating the map to fix this so the image appears sharp by default and not blurry.
Will submit a PR soon.

**Comment by flawyte** [comment]
Just submitted the PR : #8022 🎉

About the blurriness at the default zoom level `0`, do you want me to open an issue for that too or should the current behavior remain?

**Comment by ryanhamley** [comment]
I'm not sure about the z0 behavior. We'll have to investigate that but it could be a bug.
