### ISSUE TITLE
Mapbox iOS: Find layers visible inside polygon

### ISSUE THREAD

**Issue by bharathreddys77** [mapbox/mapbox-gl-js#8006]
Hi,

I've added a polygon with circle shape on the Mapbox iOS map view.This polygon circle will be always on the center of the map covering 1 mile radius distance from the center of the map. I also have  restricted places geojson which is uploaded in the Mapbox studio and the same map style url is using  in iOS map. When user change the map by dragging if I would like to know either restricted place layer is part of the 1 mile radius circle. Can someone help me how to use  `mapView.visibleFeatures` method  on the Polygon. Below is the method used to create Polygon.

`let polygon = MGLPolygon(coordinates: outerCoords, count: UInt(outerCoords.count), interiorPolygons: [innerCircle!])`

**Comment by ryanhamley** [comment]
Hi @bharathreddys77 this issue tracker is for Mapbox GL JS. You're looking for [GL Native](https://github.com/mapbox/mapbox-gl-native) although for a general help question I'd recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us)
