### ISSUE TITLE
Fullscreen control does not have a default tooltip when hovered

### ISSUE THREAD

**Issue by dmytro-gokun** [mapbox/mapbox-gl-js#8009]
Navigation controls do. For sure, it is possible to select the DOM element manually and assign the whatever tooltip we like. This, however, binds us to implementation details. 

Another point here: if we want the tooltip to change based on the current _isFullscreen state, we have to catch corresponding events (e.g. repeat the browser-dependent code in our apps and maintain that as browsers change and progress). That does not look like a smart solution.

**Comment by andrewharvey** [comment]
This should be an easy change. Did you want to submit a PR?

This is how it sets the aria-label, but not title currently

https://github.com/mapbox/mapbox-gl-js/blob/361769fd1f1c6f7c21ae7f4078efcd7ae2d542a7/src/ui/control/fullscreen_control.js#L90

This is how it's done for navigation

https://github.com/mapbox/mapbox-gl-js/blob/361769fd1f1c6f7c21ae7f4078efcd7ae2d542a7/src/ui/control/navigation_control.js#L93

**Comment by dmytro-gokun** [comment]
@andrewharvey Yep, I would like to try. 

Question: do you think it makes sense to have different aria-babel/title based on the current "fullscreen" state. Something along these lines "Enter fullscreen mode"/"Exit fullscreen mode"? What do you think?

**Comment by andrewharvey** [comment]
> Question: do you think it makes sense to have different aria-babel/title based on the current "fullscreen" state. Something along these lines "Enter fullscreen mode"/"Exit fullscreen mode"? What do you think?

Yes, after all, the icon is different based on enter/exit, so aria-label and title should have the same distinction.
