### ISSUE TITLE
What can read pbf files?

### ISSUE THREAD

**Issue by BTF-Sang** [mapbox/mapbox-gl-js#8013]
I want to modify the style of the specified building, etc., do I need to modify the specified attributes in the pbf file? If I need to, what software do I need to open pbf? I haven't found the software to try to open the pbf file. I hope to reload the existing building style.

**Comment by mourner** [comment]
You can try using `map.setFeatureState` to set a particular state for a building with a specified id, and then style it accordingly using the `["feature-state"]` expression. [Here's an example
](https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/).

Note that this issue tracker is for reporting issues with the library, not for asking support questions. Please use StackOverflow or similar forums.

**Comment by BTF-Sang** [comment]
@mourner      
Thank you for helping me a lot. This property I have seen on the official website API has not yet had such a flexible function.
