### ISSUE TITLE
How to make multiple markers for same point?

### ISSUE THREAD

**Issue by ansidev** [mapbox/mapbox-gl-js#8016]
**mapbox-gl-js version**:

### Question
I am creating a map view that contains the location and its courses. The problem is location and its courses have the same coordinate data. So when I add the markers, they will be overwritten.

I googled the solution and I found a demo (use Google Map API) at https://jawj.github.io/OverlappingMarkerSpiderfier/demo-3.html.

Can I implement the demo with Mapbox GL JS?

**Comment by mourner** [comment]
https://github.com/bewithjonam/mapboxgl-spiderifier

**Comment by ansidev** [comment]
Thanks! Perfect!
