### ISSUE TITLE
GlyphManager continually re-requests ranges with missing glyphs

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#8027]
Consider the `format` expression demo:

```
map.setLayoutProperty(layer, 'text-field', ['format',
  ['get', 'name_en'], { 'font-scale': 1.2 },
  '\n', {},
  ['get', 'name'], {
    'font-scale': 0.8,
    'text-font': ['literal', [ 'DIN Offc Pro Italic', 'Arial Unicode MS Regular' ]]
  }]);
```

`\n` isn't in `0-255.pbf` for this fontstack, which is fine, because it doesn't need to draw anything, and the actual line breaking is handled separately in the shaping. But whenever a tile gets reloaded, `getGlyphs` won't find the glyph here:

https://github.com/mapbox/mapbox-gl-js/blob/c189971a3a49df118047dba442c7287e4ddde141/src/render/glyph_manager.js#L59-L63

So it will re-request the entire range. This probably isn't a _huge_ deal because the data should be cached, and it's not super-expensive to reload the PBF... but it's wasteful and it looks ugly in the network monitor (it grabbed my attention because if you have the cache disabled it looks like a major source of data traffic in maps that reload tiles frequently).

I don't think gl-native has the same issue since its glyph manager checks for already-loaded _ranges_ instead of _glyphs_:

https://github.com/mapbox/mapbox-gl-native/blob/096dea16e31c6e0d91eba0cab1ab2efc5d6ae853/src/mbgl/text/glyph_manager.cpp#L45-L52

cc @ryanhamley @asheemmamoowala

**Comment by skol-pro** [comment]
Not fixed as of today ?

Since I added some `\n` in my points title, I get hundreds of calls per seconds to `/0-255.pbf`.
