### ISSUE TITLE
text-keep-upright: true + symbol-placement: point

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#803]
"symbol-placement": "point", "text-rotation-alignment": "map", "text-keep-upright": false, 180 bearing:
![image](https://cloud.githubusercontent.com/assets/98601/4891028/1d9e4642-63a4-11e4-83e7-6e9b93b014e1.png)
(as expected)

"symbol-placement": "point", "text-rotation-alignment": "map", "text-keep-upright": true, 180 bearing:
![image](https://cloud.githubusercontent.com/assets/98601/4891055/45c62482-63a4-11e4-87df-6a82b21627e8.png)
(expected upright text)

**Comment by ansis** [comment]
https://github.com/mapbox/mapbox-gl-test-suite/pull/18/files changes the test case
https://github.com/mapbox/mapbox-gl-js/pull/1079 changes the rendering to match the updated test case

The labels in the test case are not upright. This is intended. "text-keep-upright" should only have an effect on line labels. Do we need any spec changes to express this?

**Comment by jfirebaugh** [comment]
So `text-keep-upright` requires `"symbol-placement": "line"`? We should add a `requires` for that to the spec.

**Comment by ansis** [comment]
added in https://github.com/mapbox/mapbox-gl-style-spec/pull/266

We could allow it for points but I'm not sure that it would be useful.
