### ISSUE TITLE
Desktop Safari crash under heavy text layout load

### ISSUE THREAD

**Issue by ChrisLoer** [mapbox/mapbox-gl-js#8031]
@jfirebaugh helped me discover a problem! 😄

On Safari Version 12.0.3 (14606.4.5), Mac OS 10.14.3 (18D109), AMD Radeon R9 M370X 2048 MB/Intel Iris Pro 1536 MB, this JSFiddle will crash for me pretty reliably (usually during the first run of the "slider" animation, but sometimes I have to sit and move the slider around for a while):

https://jsfiddle.net/2xf6p9vo/3/

I have no idea what the root cause of the crash is, but I think the relevant stressor is that the animation continually updates the `circle-radius` property, but because that property is data-driven it also triggers re-layout of the text. The crash doesn't happen when the text isn't showing or is in a different source.

The "Safari crashes when tons of stuff is being sent back and forth between workers and foreground" sounds vaguely like https://github.com/mapbox/mapbox-gl-js/issues/4695, although in this case the crash seems to happen while the process is only using mid-hundred-MBs of memory.

cc @mourner @ansis

**Comment by femski** [comment]
Issue with ArrayBuffer not being freed between webworker and main thread has been fixed in iOS 12.2 Safari. See: https://bugs.webkit.org/show_bug.cgi?id=194268
Thank you for the demo that led to resolution. Mapbox on IOS is great again!

**Comment by mourner** [comment]
Just confirmed that the JSFiddle above consistently crashes for me in Safari 12.0, but NOT in Safari Technology Preview (12.2), so it indeed seems like the issue was fixed. 🎉
