### ISSUE TITLE
The number of DOM nodes rises when setData(URL) is called frequenty

### ISSUE THREAD

**Issue by poletani** [mapbox/mapbox-gl-js#8032]
**mapbox-gl-js version**: 0.53.1

**browser**: tested in chrome, but possibly in all browsers

### Steps to Trigger Behavior

 1. minimal code is following: create source and update the source using setData(URL) periodicaly

```
#HTML code
<div id="map"></div>
<button onclick="updateSource()">UPDATE</button>

#JS code
map.addSource("src", {
   "type" : "geojson",
   "data" : {
        "type": "Feature",
        "geometry": {
          type : "Point",
          coordinates : [14.5, 50.5]
        }
    }
});

function createJsonUrl (json = '') {
    return window.URL.createObjectURL(new Blob([json], {type: 'application/json'}));
};

function setSourceData (sourceId, data) {
   const src = map.getSource(sourceId);
   if (src) src.setData(data);
};

function updateSource () {
  const url = createJsonUrl(
    JSON.stringify({
      "type": "Feature",
      "geometry": {
        type : "Point",
        coordinates : [14.5 + (Math.random()-0.5)/4, 50.5 + (Math.random()-0.5)/4]
      }
    })
  );
  setSourceData('src', url);
};
```
2. open in chrome dev tools - performace tab
3. start recording
4. click several times to UPDATE button
5. stop recording 
6. check number of DOM nodes (green line in performance report)
 
### Expected Behavior
The number of DOM nodes should be constant. 

### Actual Behavior
Number of DOM nodes (green line in performance report ) constantly rises with each source update. In case of fast animation using requestAnimationFrame, after some time DOM garbage collector is called, caused noticeably longer animation frame ("freezing").
The cause is the method browser.resolveURL(), which creates new A element out of the document tree only for the purpose of the url normalization. 
The easiest solution would be to make url resolving optional (I guess it's not needed especially in case of object URLs). Or rewrite the method resolveURL() to reuse the anchor element node, if possible....?

Anyway, thank you for the great piece of software!

**Comment by mourner** [comment]
Thanks for the report! I'm wondering why it's not garbage-collected if `a` goes out of references at the end of `resolveUrl` and isn't attached to the DOM anywhere.
