### ISSUE TITLE
Does map.loadImage() support local file paths?

### ISSUE THREAD

**Issue by courlu** [mapbox/mapbox-gl-js#8037]
**mapbox-gl-js version**: latest

### Question

I'm trying to load a .png image from a local path instead of a http url. Is this supported?
It's not very clear from the documentation, and I can't seem to get it to work.

I've tried both absolute and relative file paths, with and without the file:// protocol and nothing seems to work.  Replacing the path with a web http path works as expected.

For example, should this work?

        map.loadImage(`file://../images/myImage.png`, (error,image) => { ... } )

And related side question:
Can I retrieve an image from my spritesheet for use outside of the map? e.g. I want to display a symbol on a custom legend, which has been loaded in from SVG into mapbox studio

**Comment by mourner** [comment]
In the browser, no, this is technically impossible because of browser's security restrictions. If you're doing this simply for testing, you can use a simple static web server to make it work.

For the spritesheet image — not through a public method, but as a workaround you can get it currently in raw form that can be rendered on a Canvas. `map.style.imageManager.getImage(id)`

**Comment by charleneedwardson** [comment]
import myImage from '../images/myImage.png';

map.loadImage(myImage, (error,image) => { ... } );

**Comment by VaidasDatenis** [comment]
Can someone provide this is Angular 7+ ?
@charleneedwardson solution doesn't work..

**Comment by leonardas103** [comment]
> Can someone provide this is Angular 7+ ?
> @charleneedwardson solution doesn't work..

Check your image path, else, maybe you are trying to load an SVG image? 
In that case use [map.addImage](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addimage) with an HTMLImageElement:

```
import Cat from '../images/cat.svg';

const image = new Image(35, 35);
image.src = Cat;
map.addImage('cat-name', image);
```

**Comment by gongzemin** [comment]
> const image = new Image(35, 35);
> image.src = Cat;
> map.addImage('cat-name', image);

svg seems doesn't support add class, image.className = 'filter-green'
 .filter-green { 
      filter: invert(48%) sepia(79%) saturate(2476%) hue-rotate(86deg) brightness(118%) contrast(119%);
  }
wouldn't change the color of image. It seems mapboxGl change svg to png, so add class wouldn't work.
Am i right?

**Comment by rcabre95** [comment]
> import myImage from '../images/myImage.png';
> 
> map.loadImage(myImage, (error, image) => { if (error) throw error; map.addImage('image-name', image); });

Not sure when the change was made, but as of November 29, 2021, this workaround no longer works 😕 ... not sure why they would change this. Now it only accepts strings and not StaticImageData

**Comment by leonardas103** [comment]
> Not sure when the change was made, but as of November 29, 2021, this workaround no longer works  

@rcabre95  Did you try my suggestion or read the documentation?  

Working example on how to load a local image onto the map:
`https://replit.com/@leonardas103/MapboxLocalImage`

**Comment by kimmykokonut** [comment]
I came across this issue too, trying to load a png from my assets folder, in development, local. This was my fix:
```
import foo from 'path to png'

(in the onMounted if React, onMapLoaded if using vue ts @loaded event on mapbox-map)
const image = new Image();
  image.src = foo;
  image.onload = () => {

    mapInstance.addImage('custom-marker', image);
    ....etc addSource(), addLayer()
```
