### ISSUE TITLE
Using MapTouchEvent

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#8040]
**mapbox-gl-js version**:
0.53.1

### Question

I need to detect single or multiple finger touches inside the touch event. The documentation doesn't specify a usage example of events like `MapTouchEvent`. I tried the following without success:

```
map.on('MapTouchEvent', function(e){
    console.log(e);
}

```

Thanks

**Comment by mourner** [comment]
You're looking for `touch*` family of `Map` events. See the docs here: https://docs.mapbox.com/mapbox-gl-js/api/#map.event:touchstart
