### ISSUE TITLE
Numbers and symbols mixed with CJK text are misaligned

### ISSUE THREAD

**Issue by cs09g** [mapbox/mapbox-gl-js#8041]
**mapbox-gl-js version**:
master branch

### Question
I upgraded mapbox-gl-js version to master from 0.50.0. Texts including unicode, number were displaying alright but with master.

with v0.50.0 (also okay with v0.53.1)
![image](https://user-images.githubusercontent.com/7428017/54415171-cdee4600-473e-11e9-8d93-a76700ccad2a.png)

with master
![image](https://user-images.githubusercontent.com/7428017/54415203-e9595100-473e-11e9-81de-eb70c63acc0b.png)

Texts' font looks a bit different and the vertical positions are different between special characters/numbers and unicode string.

I have checked its style from layer info, it sets the same properties.
Any changes made on the text-fields since v0.53.1? so I can modify the part of causing this issue.

p.s. the reason why I tried to upgrade was https://github.com/mapbox/mapbox-gl-js/issues/7614

Thanks.

**Comment by mourner** [comment]
Weird! Can you provide us with a minimal reproducible live test case for this? We'll bisect to the offending commit.

**Comment by cs09g** [comment]
Maybe it can be tested from adding symbol with the similiar pattern of text(Korean, special character, number) and the same font on the map. The font is [NanumGothicBold](https://www.ffonts.net/NanumGothicBold.font.download).

**Comment by mourner** [comment]
@cs09g please set up a JSFiddle — that would help us a lot.

**Comment by cs09g** [comment]
I would like to share my screen but it's on developing and private for the company yet.
I have to check whether the reason's on the font or some part of the library.
Changing text from mapbox base sample doesn't make the problem.
https://jsfiddle.net/cs09g/xbL0m4og/13/

**Comment by cs09g** [comment]
@mourner This is not happening on tags/v0.53.1 but master. Could you verify this issue?

**Comment by mourner** [comment]
@cs09g did I understand correctly that the JSFiddle above does not reproduce the problem? I still can't verify it unless there's a minimal public test case.

**Comment by mourner** [comment]
I suspect this is caused by #8008. Can you confirm that the issue is solved by passing `localIdeographFontFamily: false` as a map option?

**Comment by cs09g** [comment]
@mourner Thanks, I confirm it solves the issue!

**Comment by exotfboy** [comment]
I have met this same issue before, and it is not caused by the engine but the font used in the style.

Different font result in different appearance. Seems like caused by the different baseline in the font, maybe  this can be adjusted by the engine.

**Comment by cs09g** [comment]
@exotfboy engine may not be able to handle the font's baseline. baseline is on each characters of the font.

**Comment by exotfboy** [comment]
Seems like that the miss-aligned is caused by different parts of the text  rendered by different font.

See this example : https://jsfiddle.net/s4wgqac5/

When using font `Arial Unicode MS Regular` all the characters including cjk, eng and number are aligned correctly.

When using font `Ubuntu Regular, Arial Unicode MS Regular`, the cjk is rendered by `Arial Unicode MS Regular` since the `Ubuntu xx` does not contains the cjk charecters, and the rest of the text are rendered by `Ubuntu`.

I am not sure if this can be adjusted.

**Comment by cs09g** [comment]
Right, that's why we use fontforge to edit its align manually for those fonts.

**Comment by exotfboy** [comment]
Really? Could you show us how to adjust the alignment of a certain font by fontforge?
