### ISSUE TITLE
Zoom is restricted with options.renderWorldCopies active

### ISSUE THREAD

**Issue by dieterdreist** [mapbox/mapbox-gl-js#8042]
**mapbox-gl-js version**:
mapbox-gl.js v0.53.1

**browser**:
all browsers

### Steps to Trigger Behavior

 1. create a map view and look at it on a screen in portrait orientation
 2. try to see the whole world by zooming out

### Link to Demonstration

https://docs.mapbox.com/mapbox-gl-js/example/simple-map/
### Expected Behavior
Can zoom out until you see at least the whole world at once (potentially also show multiple copies of the world, there is even an option for it), regardless of screen proportions.

### Actual Behavior
Zooming is restricted in a way that you cannot zoom out further as the map filling up the whole screen vertically. On a screen in portrait orientation this means seeing only a part of the world, while it allows for the whole world at once in landscape orientation.

**Comment by mourner** [comment]
This is the same underlying issue as #3055, so closing as duplicate. Currently we define zoom 0 as the one where z0 tile is displayed with 512x512 resolution, and we don't support minzoom less than 0.
