### ISSUE TITLE
Port "format" expression's text-color option from native to gl-js

### ISSUE THREAD

**Issue by alexshalamov** [mapbox/mapbox-gl-js#8045]
Port https://github.com/mapbox/mapbox-gl-native/pull/14062 to gl-js.

- Render tests: https://github.com/mapbox/mapbox-gl-js/pull/8046
- Port: https://github.com/mapbox/mapbox-gl-js/pull/8068

**Comment by chloekraw** [comment]
Actually closed by me 😁
