### ISSUE TITLE
Marker's collision performs false-positive on big zooms 

### ISSUE THREAD

**Issue by aleksandr-vin** [mapbox/mapbox-gl-js#805]
When on zoom 20-22 there are enough space between 2 markers but the second one is hidden for eternity, only *-allow-overlap helps.

Here is the sample (with *-allow-overlap's turned True -- turn them False and reload and 'P3' will be missed, then zoom-zoom-zoom)
http://jsfiddle.net/aleksandrvin/p3hsbo2p/

**Comment by mourner** [comment]
Now tiles are overscaled with placement recalculated on each zoom, so this should be fixed.
