### ISSUE TITLE
Drag 1 point in  many points map

### ISSUE THREAD

**Issue by shoabshah** [mapbox/mapbox-gl-js#8050]
Hi All,

We have a requirement where-in we have to provide drag drop facility for markers / points. The example [https://docs.mapbox.com/mapbox-gl-js/example/drag-a-point/](https://docs.mapbox.com/mapbox-gl-js/example/drag-a-point/) works perfect for 1 marker. **Because it is hardcoded to geojson.features[0].geometry.coordinates = [coords.lng, coords.lat];**

However, in  a multi point scenario how to set the geojson for respective feature which was dragged?

Kindly let know if any further details required.

Thankx

**Comment by peterqliu** [comment]
@shoabshah for multiple points, the portion involving Mapbox GL is still the same: listening to mouse interactions, and updating via setData. You would need to add separate logic to distinguish the points:

- unique identifier for each point
- on point drag, figure out which point's getting moved
- update the right point in the geojson with its new coordinate
- setData as before

**Comment by shoabshah** [comment]
Hi Peter,
Thank you for the pointers. Based on this example [https://stackoverflow.com/questions/55218425/mapbox-gl-js-drag-1-point-in-many-points-map](url) was able to get it done. However, would wish to get an sample from you side as well :). 
Thank you

**Comment by colleenmcginnis** [comment]
Glad you got it working! Because the Mapbox GL JS concepts needed to complete this task are covered in https://docs.mapbox.com/mapbox-gl-js/example/drag-a-point/, I don't think we should build and maintain a second example.
