### ISSUE TITLE
use npm run start to compile mapbox have some problem

### ISSUE THREAD

**Issue by cc-ch** [mapbox/mapbox-gl-js#8051]
I hvae to use **npm run start** to compile. But I have some problem with it.
![WechatIMG61](https://user-images.githubusercontent.com/19361098/54530138-eb304800-49bc-11e9-98c6-e5dd00ccdfd3.jpeg)

![WechatIMG61](https://user-images.githubusercontent.com/19361098/54530198-1c107d00-49bd-11e9-966c-1e31bbcc0081.jpeg)

help thx

**Comment by mourner** [comment]
This project uses Yarn as the package manager of choice. Try removing the `node_modules` folder and reinstalling dependencies with Yarn, and let us know if it doesn't work.
