### ISSUE TITLE
Invalid type on LngLatBounds.extend

### ISSUE THREAD

**Issue by fc** [mapbox/mapbox-gl-js#8065]
It appears that `LngLatLike` and `LngLatBoundsLike` should also be allowed since the convert methods used here accept those types:
https://github.com/mapbox/mapbox-gl-js/blob/master/src/geo/lng_lat_bounds.js#L85-L91

I believe it is just a matter of changing it in the comments and in the type definition:
`LngLat | LngLatBounds` to `LngLat | LngLatBounds | LngLatLike | LngLatBoundsLike`, or to just `LngLatLike | LngLatBoundsLike` - not sure off the top of my head if the `instanceof` call will need `LngLat` to be explicitly set as a type (refer to lines 74 and 78).

I haven't created a PR since I don't have the time to test right now....but should be enough info for someone to look into it.

**mapbox-gl-js version**:
Latest version

### Expected Behavior
No type errors

### Actual Behavior
Invalid types
Something like this will fail TypeScript type checks:
```
bounds.extend([number, number]);
```

**Comment by fc** [comment]
`@types/mapbox-gl` will also need to be updated once a fix here has been done:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/mapbox-gl/index.d.ts#L883

**Comment by asheemmamoowala** [comment]
@fc Thanks for the detailed issue, want to submit a PR?

**Comment by marcofugaro** [comment]
any updates on this? should `@types/mapbox-gl` be updated to `v1.0.0`?

**Comment by asheemmamoowala** [comment]
> any updates on this? 

We would welcome a PR contribution for the issue in the OP. 

> should @types/mapbox-gl be updated to v1.0.0?

Could you please create a separate issue for this

**Comment by sgolbabaei** [comment]
closed by https://github.com/mapbox/mapbox-gl-js/pull/9293
