### ISSUE TITLE
Image source renders too long. Main thread hangs when processing

### ISSUE THREAD

**Issue by vladimir-barsuchenko** [mapbox/mapbox-gl-js#8067]
## Motivation

- I use different image sources on different pages. Mapbox instance remains the same.
- When I switch a page it takes ~4 seconds to render 4K image. Also it's needed to be said that image is scaled down initially to fit screen boundaries.

 
When I add Image source to a map main thread hangs and takes too long to render large images.

```
map.addSource(
  'overlaySourceId',
  {
    type: 'image',
    url: '...',
    coordinates: [...],
  },
);
```

When compared to native `<img src="">` where images are loaded instantly even if image is 4K,
for mapbox to render it, it requires about 4 seconds. 

### Implementation

To avoid main thread being frozen you might want to consider using something similar to `img.decode` [see here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decode)

Since you are using Canvas approach, please take a look at `OffscreeenCanvas` and how to utilize it to do background image rendering.

Detailed explanation with implementation can be found [here](https://youtu.be/wkDd-x0EkFU?t=841)

**Comment by mourner** [comment]
This is likely to have been fixed already because we use `createImageBitmap` where possible to avoid expensive blob-based decoding, so I'm closing — will reopen if there are reports of it still being bad 🤞
