### ISSUE TITLE
The default marker is positioned incorrectly

### ISSUE THREAD

**Issue by dmytro-gokun** [mapbox/mapbox-gl-js#8071]
I'm creating a default droplet-shaped marker (by omitting options.element as described here: https://docs.mapbox.com/mapbox-gl-js/api/#marker). As a result the marker is positioned slightly higher then it should be. You can see it here:

https://jsbin.com/ragudog/5/edit?html,output

The reason is that <svg> is an inline element and the size of the div is determined by the size of the svg + line-height setting (which is 20px for the map by default).

So, in order to fix this, we need to change that default droplet svg to be a "block" element. If everybody agrees, I will submit a PR to fix this issue.

**Comment by dmytro-gokun** [comment]
After some thinking ... one could argue that when using the default marker, anchor & offset should be overridden as well, so that the droplet's pin point to exact location. Any thoughts?

**Comment by mourner** [comment]
Yes, we'll welcome a PR! The sharp end point definitely should point to exact location.

**Comment by dmytro-gokun** [comment]
@mourner Deal. I'll work on this.
