### ISSUE TITLE
Exception when creating an all filter made of different sub-expressions

### ISSUE THREAD

**Issue by Zirak** [mapbox/mapbox-gl-js#8073]
**mapbox-gl-js version**: 0.53.1

**browser**: Tested on Firefox stable / Chrome canary

### Steps to Trigger Behavior

 1. Create a filter containing an `all` expression, with two sub-filters: One a nested expression, another a non-expression (see example below)
 2. Get an exception saying you're a bad person
 3. Contemplate whether you truly are a bad person

### Link to Demonstration

https://jsbin.com/howogemigu/1/edit?js,output

### Expected Behavior

Creating a filter such as:

```json
["all",
  ["==", "foo", ["get", "whatever"]],
  ["==", "1", "2"]]
```

Should maybe be ok probably.

### Actual Behavior
An exception is thrown: `Error: "layers.ohnose.cold.filter[1][2]: string, number, or boolean expected, array found"`

### Traceback
As the first instinct is that I did something horribly wrong, I looked into the code to figure out what's going on:

1. We enter [`validateFilter`](https://github.com/mapbox/mapbox-gl-js/blob/42f00ac3e963f6dda9f4ed5390201e5ff25fa41a/src/style-spec/validate/validate_filter.js#L10-L19) with `options.value` being `['all', ...]`
1. In [`isExpressionFilter` for the `'all'` case](https://github.com/mapbox/mapbox-gl-js/blob/42f00ac3e963f6dda9f4ed5390201e5ff25fa41a/src/style-spec/feature_filter/index.js#L38-L44) we recurse with each child
1. In [the `'==`' and friends case](https://github.com/mapbox/mapbox-gl-js/blob/42f00ac3e963f6dda9f4ed5390201e5ff25fa41a/src/style-spec/feature_filter/index.js#L29-L35), the first child passes the test, the second does not, so the overall call in step 2 returns `false`, thus we enter `validateNonExpressionFilter`
1. The [case for `'all'`](https://github.com/mapbox/mapbox-gl-js/blob/42f00ac3e963f6dda9f4ed5390201e5ff25fa41a/src/style-spec/validate/validate_filter.js#L85-L96) once again recurses into each child
1. In [the `'=='` case fallthrough](https://github.com/mapbox/mapbox-gl-js/blob/42f00ac3e963f6dda9f4ed5390201e5ff25fa41a/src/style-spec/validate/validate_filter.js#L55-L83) is the check against [the primitive data types](https://github.com/mapbox/mapbox-gl-js/blob/42f00ac3e963f6dda9f4ed5390201e5ff25fa41a/src/style-spec/validate/validate_filter.js#L79-L81), which fail for the first `==`.

As there seems to be a dichotomy between expression and non-expression, this may be intended, but at the very least incredibly confusing to encounter and debug the meaning. If it's indeed unintended behaviour, there're several ways to deal with this specific bug (e.g. special-casing [other operators than `'$type'`](https://github.com/mapbox/mapbox-gl-js/blob/42f00ac3e963f6dda9f4ed5390201e5ff25fa41a/src/style-spec/validate/validate_filter.js#L71), or validating whether each array item is an expression individually), and if it's intended behaviour, maybe a leading `isMixedExpressionAndNonExpression` which throws a more indicative error?

In related news, and this may be a separate thing, but is there a non brute-force way to debugging filters? As in, if you have a typo in filter 107 out of 400 and it's just too late/early to see the difference between `state` and `staet`, where does one put the breakpoint to see the filter execution and see he's an idiot?

Thanks in advance.

**Comment by stevage** [comment]
For anyone else wondering, the "you're a bad person" exception is:

> `Error: "layers.ohnose.cold.filter[1][2]: string, number, or boolean expected, array found"`

Anyway, here is a smaller repro case:

https://jsbin.com/pikokisogi/edit?js,console,output

```
const layers = [{
  id: 'ohnose',
  source: 'thing',
  type: 'circle',
  filter: ['all', true, ['==', 1, 2]]
}];

var map = new mapboxgl.Map({
    container: 'map',
    style: { version: 8, sources: {
      thing: {
        type: 'geojson',
        data: { type: 'FeatureCollection',features: []}
      }
    }, layers: layers},
});
```

It definitely looks like a bug. I don't see any reason this isn't valid:

```
filter: ['all', true, ['==', 1, 2]]
```

There's some weird behaviour here. This is ok:

`filter: ['all', ['==', '1', '2']]`

This is not:

`filter: ['all', true, ['==', '1', '2']]`

This is not ok:

`filter: ['all', ['==', 1, 2]]`

**Comment by Zirak** [comment]
For the `['all', true, ['==', '1', '2']]` case, that's the [`'all'` case here](https://sourcegraph.com/github.com/mapbox/mapbox-gl-js@42f00ac3e963f6dda9f4ed5390201e5ff25fa41a/-/blob/src/style-spec/validate/validate_filter.js#L86) recursing for every array element, and failing [this check on the first one](https://sourcegraph.com/github.com/mapbox/mapbox-gl-js@42f00ac3e963f6dda9f4ed5390201e5ff25fa41a/-/blob/src/style-spec/validate/validate_filter.js#L25-27). 
I guess the distinction of bug/feature would lie on your definition of what an expression vs non-expression filters are.

**Comment by mourner** [comment]
Yeah, it's a tricky case — we had to put some flawed heuristics for determining if something is a legacy filter or an expression to both 1) support expressions as filters, 2) keep backwards compatibility. There will inevitably be edge cases stemming from this. The good thing is that it shouldn't affect anyone severely, since filters like `['==', 1, 2]` are useless anyway. 

I think I'm going to close this, but I'm open to any suggestions for how we can improve this — e.g. a PR that improves the error message to make it clearer what's going would be very welcome.

**Comment by Zirak** [comment]
Ah, I see, thanks for the clarification. This actually started when I was writing out a filter taking inspiration from some of the builtin `mapbox-draw` filters, specifically ones like [these here](https://sourcegraph.com/github.com/mapbox/mapbox-gl-draw@2a0f84dc4db828764ac79c85a0f151233db7ed5c/-/blob/src/lib/theme.js#L173-176):

```json
{
  "id": "gl-draw-point-active",
  "type": "circle",
  "filter": ["all",
    ["==", "$type", "Point"],
    ["!=", "meta", "midpoint"],
    ["==", "active", "true"]],
  "paint": {
    "circle-radius": 5,
    "circle-color": "#fbb03b"
  }
}
```

Deriving from that, I attempted to write the following:

```json
["all",
  ["==", "active", "true"],
  ["==", "foo", ["get", "user_something"]]]
```

But got all fubar. The "fix" is to change `"active"` to `["get", "active"]`, but that was incredibly non-obvious (to me) at first, since in my eyes `mapbox-draw` knew what it was doing better than me, and only after delving into mapbox code I realised that this is the distinction between expressions and "legacy" filters.

How do you think it'd be best to approach determining there's this "mixed" expression/legacy? One approach is for `'all'` and friends (anything accepting sub-expressions) to look for and report inconsistent return values of `isExpressionFilter`. Something (a bit cleaner, of course) than:

```javascript
function isMixedBag(subexpressions) {
    const hasExpressions = subexpressions.some(isExpressionFilter);
    const hasNonExpressions = subexpressions.some(not(isExpressionFilter));

    return hasExpressions && hasNonExpressions;
}
```

What do you think?

**Comment by wchargin** [comment]
In case this helps anyone else, I only realized upon reading this issue (and specifically [this comment][1]) that apparently Mapbox has *two* different, incompatible expression DSLs. I had these two filters, each of which worked:

```typescript
// both these filters work...
const filter1 = ["==", "$type", "Point"];
const filter2 = ["==", ["get", "myProperty"], someValue];
```

[1]: https://github.com/mapbox/mapbox-gl-js/issues/8073#issuecomment-476691999

…so I was confused to see errors when combining them:

```typescript
// but this didn't?
const filter3Broken = [
  "all",
  ["==", "$type", "Point"],
  ["==", ["get", "myProperty"], someValue],
];
// ^ error: string, number, or boolean expected, array found
```

I now see that I need to migrate `"$type"` to `["geometry-type"]`—which totally does make sense; I was wondering how the typing worked and this feels much more like what I'd expect from a Lisp. But when you search for `$type` into the Mapbox docs, it documents that special key without any mention that you can use the `["geometry-type"]` form within an expression.

Working filter:

```typescript
const filter4Fixed = [
  "all",
  ["==", ["geometry-type"], "Point"],  // now a uniform S-expression
  ["==", ["get", "myProperty"], someValue],
];
```

TIL, and I can work with this now that I understand it better; just leaving breadcrumbs here for anyone who might be in a similar situation.

**Comment by stevage** [comment]
Yes, this has been a problem every since they first introduced the new expression syntax.  It's very painful to trip over because it's such an unexpected situation and the error message is so unhelpful.

Really they should just deprecate the old style and give warnings when it's used.

**Comment by david-morris** [comment]
> I think I'm going to close this, but I'm open to any suggestions for how we can improve this

As someone who wants to automate ingesting styles from diverse sources, I'd like an Expression keyword like `["eval-any-filter", legacyFilterOrExpression]` of type bool.  That way you can `["all"...]` your filters together without caring about their details.
