### ISSUE TITLE
Mapbox markers flashing when using `icon-allow-overlap`

### ISSUE THREAD

**Issue by jakob-fuchs** [mapbox/mapbox-gl-js#8077]
https://stackoverflow.com/questions/55341462/mapbox-markers-flashing-when-using-icon-allow-overlap

Reposting this here since it seems like most Mapbox questions are not being answered on SO.

Feel free to delete this issue if this is not the right place.

**Comment by mourner** [comment]
Please don't skip filling details we ask in the ticket template when you submit an issue. Can you provide a minimal reproducible test case (e.g. with JSFiddle)?

**Comment by jakob-fuchs** [comment]
Link here: https://codepen.io/jakobfuchs/details/VRRgJO

Seems to be happening a bit less in this demo, so maybe it is necessary to toggle the filter a few times.

In case this is a browser issue, I'm using the Brave browser (Version 0.61.52 Chromium: 73.0.3683.86 (Official Build) (64-bit)) running on Linux.

**Comment by jakob-fuchs** [comment]
Any more information needed?

**Comment by jakob-fuchs** [comment]
Rewriting the map with maptalks on a stadia base layer solved the problem :tada:
