### ISSUE TITLE
Is there a way to brighten/darken tiles based on a custom function?

### ISSUE THREAD

**Issue by shobhitg** [mapbox/mapbox-gl-js#8080]
Hi,

I am trying to see if I can apply a custom brightness function on the raster tiles.

I see there are some `paint` knobs to control the brightness and contrast:
https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-raster-raster-brightness-min
and
https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-raster-raster-contrast

But what I really want is an ability to define a custom  brightness function.

Here is what I am trying to do: Any pixel that is brighter than a certain threshold of gray should turn to white and the remaining pixels stay as is.
This is a bit more custom than the raster brightness or raster contrast knob.

Is this possible anyhow?

**Comment by andrewharvey** [comment]
#3889 would allow you to re-map a raster, hopefully supporting this use case.

**Comment by mourner** [comment]
Yep, closing as a duplicate of #3889.
