### ISSUE TITLE
map.on(type, layer, listener) event doesn't return features

### ISSUE THREAD

**Issue by denboogert** [mapbox/mapbox-gl-js#8085]
**mapbox-gl-js version**:
0.53.1

**browser**:
Google Chrome is up-to-date
Versie 73.0.3683.86 (Officiële build) (64-bits)

in Angular/Ionic 4; npm install mapbox-gl

### Steps to Trigger Behavior

this.map.on('mousemove', 'district-fill', (e) => { console.log(e);});

### Link to Demonstration
n.a. 

### Expected Behavior _**(as in version 0.44.0)**_
console.log:
{features: Array(1), lngLat: LngLat, point: Point, originalEvent: MouseEvent, type: "mousemove", …}
**features: [Feature]**
lngLat: LngLat {lng: 6.143085295959736, lat: 51.428327445134585}
originalEvent: MouseEvent {isTrusted: true, screenX: 1222, screenY: 1012, clientX: 1110, clientY: 855, …}
point: Point {x: 739.0435791015625, y: 855}
target: e {moving: false, transform: Transform, _bearingSnap: 7, _interactive: true, _maxTileCacheSize: null, …}
type: "mousemove"
__proto__: Object

### Actual Behavior
console.log:
o {point: a, lngLat: bu, originalEvent: MouseEvent, type: "mousemove", _defaultPrevented: false, …}
lngLat: bu {lng: 6.175355340089396, lat: 51.43412634777155}
originalEvent: MouseEvent {isTrusted: true, screenX: 1232, screenY: 1011, clientX: 1119, clientY: 855, …}
point: a {x: 748.0435791015625, y: 855}
target: r {_moving: false, _zooming: false, transform: lo, _bearingSnap: 7, _renderFrameCallback: ƒ, …}
type: "mousemove"
_defaultPrevented: false
defaultPrevented: (...)
__proto__: ft

Downgrading to 0.44.0 returns the features as expected from the documentation.

**Comment by mourner** [comment]
Can you please set up a minimal reproducible test case (e.g. on JSFiddle)? There's not enough information for us to diagnose the issue.

**Comment by denboogert** [comment]
I put in two hours, but could not get mapbox-gl it to work on StackBlitz: https://stackblitz.com/edit/angular-9djiw2. 

I will return to this later.
This example works: https://docs.mapbox.com/mapbox-gl-js/example/popup-on-hover/
So it must be related to the integration in Ionic 4 and Angular (therefore I used Stackblitz and not jsFiddle).

**Comment by denboogert** [comment]
Thank you for your quick response!

**Comment by denboogert** [comment]
Downgraded to 0.44.0 for now. That is working (without any other changes). All higher (tested) versions 0.45.0, 0.46.0, 0.50.0, 0.52.0 have the same issue.

**Comment by denboogert** [comment]
After a rather long investigation I found that the events do still contain information about features, but that this information is not shown on console.log(event). I managed to change my own code, that broke as a result of the changes made regarding events in version 0.45.0. Upgraded to 0.53.1. Thanks again!
