### ISSUE TITLE
getClusterLeaves() returns array of features with incorrect geometry type 

### ISSUE THREAD

**Issue by courlu** [mapbox/mapbox-gl-js#8089]
I'm using the getClusterLeaves method on a clustered source, to get the features contained within each cluster:

https://docs.mapbox.com/mapbox-gl-js/api/#geojsonsource#getclusterleaves

However, the array of point features returned incorrectly have their geometry type set to "point" instead of "Point" (Note the [geojson specification](https://tools.ietf.org/html/rfc7946) that specifies the properties are case sensitive), thus attempting to use this collection results in problems unless the type is first manually modified like so:

`features.forEach(f => f.geometry.type = 'Point');`

As an example, without modfying the type property, attempting to get a bounding box using turf js results in the error 

> "Unknown geometry type"

**Comment by mourner** [comment]
I can't reproduce this issue — the returned features have the correct geometry type. You'll have to provide us with a minimal reproducible test case for us to diagnose this.
