### ISSUE TITLE
Allow popup to be bound to shape (GEOJson)

### ISSUE THREAD

**Issue by mloffer** [mapbox/mapbox-gl-js#8091]
I would like to show a shape on the map, with a popup alongside that contains additional information and a call-to-action to act on that shape.

Currently, the best I can do is set the popup to a point (setLngLat). The most obvious choice for this is the centroid of the shape. However, this effectively covers the shape with the popup.

## Design

Provide a method that takes a shape as the target for the popup. This method would need to pan and/or zoom the map to accommodate both the popup and the shape in the viewport.

### Mock-Up

![existing](https://user-images.githubusercontent.com/666696/55114163-76d16500-509e-11e9-9fcd-c44e87c03141.PNG)

![tobe](https://user-images.githubusercontent.com/666696/55114253-abddb780-509e-11e9-857c-ef77f4f0909d.PNG)

**Comment by andrewharvey** [comment]
I think this is something you could implement yourself on top of mapbox-gl-js.

For example you could take the polygon bbox, then find which points of the polygon touch that bbox, which should give you at least 4 viable popup anchor points, from there you can set the appropriate anchor on the popup to ensure it doesn't overlap your polygon. All possible at the moment.

Then based on the size of your popup, map.fitBounds to ensure you can see both...

**Comment by peterqliu** [comment]
agree that 👆is the best option here.
