### ISSUE TITLE
Mapbox JS API accessed through Python's Plotly - Zoom is broken

### ISSUE THREAD

**Issue by bearmountainsolutions** [mapbox/mapbox-gl-js#8094]
As explained in more detail here:
https://community.plot.ly/t/mapbox-zoom-stops-working-once-figure-data-is-updated/21296/3

There is something broken when using mapbox through plotly to generate geospatial scatterplots.  The main problem is that when the API is called a second time (the user makes a selection to filter the data that is being plotted on the map, for example), all zoom controls disappear - u can no longer scroll to zoom for example.

This is something that recently happened (last 2 days or so) and is a critical breakage.  Apps no longer work in an acceptable way (smooth zooming is not just nice to have, its necessary in order to find where your data points are etc).

**Comment by asheemmamoowala** [comment]
Your bug seems to be specific to the use of mapbox-gl-js in plotly. If you think this is a bug in mapbox-gl-js, please provide an isolated, minimal, reproducible demonstration.

**Comment by mourner** [comment]
I don't think it's anything on the GL JS side. You should report this issue to Plotly.

**Comment by bearmountainsolutions** [comment]
ok thank you for your responses
