### ISSUE TITLE
optimize query param does not work anymore

### ISSUE THREAD

**Issue by nicotejera** [mapbox/mapbox-gl-js#8097]
**mapbox-gl-js version**:

**browser**:

### Steps to Trigger Behavior

 1. Create a map using a custom style and add the "optimize=true" query param to the URL
 2. The map does not render

### Link to Demonstration

https://output.jsbin.com/tezobugone

### Expected Behavior
The map would render as it used to

### Actual Behavior
It doesn't render anymore

**Comment by mourner** [comment]
Your JSBin example renders fine for me. Is it still not working for you? If so, does it happen everywhere, or only on a specific hardware / OS / browser combination?

**Comment by andrewharvey** [comment]
It also looks fine to me, with the style flag being passed through to the tile requests correctly.

There was an issue last month on the API side where passing the style optimise flag through to the tilejson didn't translate through to the tiles, but it looks like that's fixed now.

**Comment by nicotejera** [comment]
It appears like now it's fixed - it was not rendering yesterday for some reason, we were getting an encoding issue in all browsers and devices and the vector tiles were just not rendering. Thanks for checking!
