### ISSUE TITLE
Symbols in 3D space

### ISSUE THREAD

**Issue by danvk** [mapbox/mapbox-gl-js#8098]
## Motivation

If you create a map visualization with both fill-extrusion and symbol layers, the symbol layers do not respect the 3D nature of the scene:

![3d symbol](https://user-images.githubusercontent.com/98301/55193614-e2d6ca80-517d-11e9-9b2d-6a81568b6084.gif)

The bus icon _looks_ like it's on the ground. This illusion is maintained until you tilt the map, at which point you realize there's a mix of flat & 3d layers, and the bus appears on top of all the buildings. This breaks the illusion of 3D.

## Design Alternatives

- Create a GeoJSON MultiPolygon that has the shape of a bus icon and use a fill-extrusion layer with zero height.
- Use `fill-extrusion-pattern` with a square-shaped GeoJSON polygon. Unfortunately it's hard to get exactly one copy of the "pattern" to display.

## Design

You guys know better but a few thoughts:

- Add a way to make symbol layers exist in 3D space.
- Add a way to place a symbol on a feature in a fill-extrusion layer.

**Comment by mourner** [comment]
This is  possible with the new Custom Layer API. Here's an example with a ThreeJS 3D model: https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/

**Comment by danvk** [comment]
Thanks @mourner. Do you have any simpler examples you can point to? If not I can try to figure something out.

**Comment by mourner** [comment]
@danvk we should definitely add a simpler example, but meanwhile you can take a look here — it's an example of a custom layer rendering a simple 3D cube: https://github.com/mapbox/mapbox-gl-js/blob/master/debug/custom3d.html

**Comment by ssathya07** [comment]
Hi, i'm looking to solve the exact problem mentioned above i.e. 

- Add a way to make symbol layers exist in 3D space.
- Add a way to place a symbol on a feature in a fill-extrusion layer.

Is there support to display a "text symbol" in a 'fill-extrusion' layer using Mapbox GL V2.2.0 (not using custom layers)? 

Thanks!

**Comment by karimnaaji** [comment]
@ssathya07 symbols are adjusted above the ground plane following terrain elevation post v2. But not yet allowed to have a custom height offset to adjust them on top of fill-extrusion layers. Are you trying to have symbols on top of buildings for example?

**Comment by ssathya07** [comment]
@karimnaaji Yes, I'm trying to figure out a way to display "text" corresponding to a fill-extrusion layer (polygons on top of a building). currently, I have a fill-extrusion layer and also a symbol layer separately to display the text. 

> @ssathya07 symbols are adjusted above the ground plane following terrain elevation post v2. But not yet allowed to have a custom height offset to adjust them on top of fill-extrusion layers. Are you trying to have symbols on top of buildings for example?

**Comment by ssathya07** [comment]
> @ssathya07 symbols are adjusted above the ground plane following terrain elevation post v2. But not yet allowed to have a custom height offset to adjust them on top of fill-extrusion layers. Are you trying to have symbols on top of buildings for example?

@karimnaaji can you please let me know if/when this (custom height offset or display using polygon centroid) will be available? currently, this is a blocker for us from using mapbox GL.

**Comment by djpirra** [comment]
Would really be awesome to have 3D objects to be added to a layer easily. Specially ones regarding transportation, objects, people, signals, etc...

Did anyone have a working example with this?
