### ISSUE TITLE
map is broken on higher screen resolutions in Chrome

### ISSUE THREAD

**Issue by kukiel** [mapbox/mapbox-gl-js#8102]
**mapbox-gl-js version**:
0.53.1
tested also with 0.54.0-beta.1
**browser**:
Version 72.0.3626.121 (Official Build) (64-bit)
### Steps to Trigger Behavior

 1. Open https://mapbox-marker-bug--lukaszkukielka.repl.co/
 2. On lower resolution everything works fine
![image](https://user-images.githubusercontent.com/16286018/55276314-d3c55900-52f2-11e9-8f3c-c107f207ff8a.png)
 3. Toggle on device toolbar
![image](https://user-images.githubusercontent.com/16286018/55276451-22bfbe00-52f4-11e9-98d2-804f3e94bbae.png)
 4. Set resolution to 5125x2100
![image](https://user-images.githubusercontent.com/16286018/55276504-7f22dd80-52f4-11e9-8aeb-196f3e078315.png)

 5. Marker is misplaced + map zoom is not zooming to the cursor position.
![image](https://user-images.githubusercontent.com/16286018/55276326-f0619100-52f2-11e9-977a-c5d29e4cceca.png)

I was experiencing it on large resolution screen but right now can only reproduce using mobile mode in Chrome but behaviour is the same.

Code: https://repl.it/@LukaszKukielka/mapbox-marker-bug

**Comment by peterqliu** [comment]
@kukiel thanks for the bug report. The linked repl test case doesn't seem to run 🤔 can you make a minimal reproduction in jsfiddle?

**Comment by kukiel** [comment]
@peterqliu can you try again? I restarted the repl and it works now. Will provide jsfiddle if that fails again.

**Comment by peterqliu** [comment]
@kukiel thanks. I can reproduce this via the debug tool, and the offset actually starts at as low as 2100x2100. 

However, I don't see this when I set my *actual* system screen resolution higher. This is 3840 x 2400 -- note the sprite sits properly on the city:

![Screen Shot 2019-04-17 at 11 37 10 AM](https://user-images.githubusercontent.com/4551508/56313339-40b85b80-6107-11e9-88c0-da0207c08ed2.png)

Compare this to the Chrome device simulator at the same resolution, with the offset sprite:

<img width="1507" alt="Screen Shot 2019-04-17 at 11 48 55 AM" src="https://user-images.githubusercontent.com/4551508/56313492-93921300-6107-11e9-9851-684ff4a71d6c.png">

Will keep digging on this, but wondering if part of the disparity is with the Chrome tool itself. @kukiel what was the resolution of the larger screen on which you originally saw the bug?

**Comment by peterqliu** [comment]
Looks like this bug happens only when we resize the map _outside_ the browser's `onresize` event, like by changing the system display resolution, or plugging in an external monitor, or using debug tools at runtime. The behavior disappears once we resize the map window.

Since these don't seem part of common user behavior, and we lack a good way to listen for resolution changes outside the browser, I'm inclined to punt on this

**Comment by peterqliu** [comment]
the only way to handle this in an automated fashion is to check `screen.width` persistently, for all maps, which seems an undue overhead for such a corner case as this. A manual [resize](https://docs.mapbox.com/mapbox-gl-js/api/#map#resize) seems like the best way to go.
