### ISSUE TITLE
how to use mapbox for untiy sdk in  offine application

### ISSUE THREAD

**Issue by WorldInMine** [mapbox/mapbox-gl-js#8105]
**mapbox-gl-js version**:

### Question

Hello, I'd like to ask if (map box for untiy sdk) can use third-party map services such as (tile). Our application needs to be used in an offline environment. Looking forward to your reply

**Comment by mourner** [comment]
This is a place to report issues with Mapbox GL JS. For questions about the Unity SDK, you should probably contact Mapbox sales or support. https://www.mapbox.com/contact/
