### ISSUE TITLE
Hash links are not clickable in documentation

### ISSUE THREAD

**Issue by bravecow** [mapbox/mapbox-gl-js#8108]
Docs context: _In contrast to Map#queryRenderedFeatures, this function returns_

Where Map#queryRenderedFeatures points to **#mapqueryrenderedfeatures**:

![image](https://user-images.githubusercontent.com/988471/55391083-475ca580-5541-11e9-9e10-824a1fa9e845.png)

But real hash of `queryRenderedFeatures` is **#map#queryrenderedfeatures**:

![image](https://user-images.githubusercontent.com/988471/55391097-4fb4e080-5541-11e9-81ce-914ea3318c47.png)

**Comment by andrewharvey** [comment]
I believe this is a duplicate of #4568

**Comment by andrewharvey** [comment]
I'll close this to keep this discussion centralised around the existing ticket.

**Comment by bravecow** [comment]
Sure. Thanks. 2 years old. Have never noticed this bug till yesterday 😱
