### ISSUE TITLE
Vector Tiles can not overzoomable with v0.54.0

### ISSUE THREAD

**Issue by dythbj** [mapbox/mapbox-gl-js#8109]
**mapbox-gl-js version**:
v0.54.0-beta.1
**browser**:
Chrome 73.0.3683.86
### Steps to Trigger Behavior
1. I make a mbtiles file by tippecanoe,and the max zoom is 10
2. if i use the mapbox-gl-js(0.50.0), no matter how larger i zoom the map in, the tiles are still there
3. if i use the newest version(v0.54.0-beta.1), when i zoom in above than 10, the map become empty.

Did i miss something?

**Comment by mourner** [comment]
Can you set up a minimal reproducible test case (e.g. on JSFiddle)?

**Comment by dythbj** [comment]
> Can you set up a minimal reproducible test case (e.g. on JSFiddle)?

Sorry mourner, i host the mbtiles file as a service , but i can put it on the internet. I have some screenshot here like these:
1. when the zoom level is less than 10, the tiles rendering normal, like this:
![image](https://user-images.githubusercontent.com/41282663/55402058-11d9ab80-5585-11e9-91aa-6f8497102ba6.png)
2. when i zoom over 10, no tiles rendering, like this:
![image](https://user-images.githubusercontent.com/41282663/55402107-30d83d80-5585-11e9-8f74-d9ecb5543f19.png)

**Comment by mourner** [comment]
Unfortunately I'm not able to reproduce the issue locally with my own sources, so you'll have to set up a live example.

**Comment by rbrundritt** [comment]
Have you set the min/max zoom range for the source? If not, then it will try retrieving tiles for other zoom levels.

**Comment by dythbj** [comment]
> Have you set the min/max zoom range for the source? If not, then it will try retrieving tiles for other zoom levels.

No, i didn't. And the zoom range is up to 20.

**Comment by GordoRank** [comment]
I'm experiencing the same having moved from 53.1 to 54.1 beta.

My particular tileset only contains up to level 7 and usually over overzooms the rest of the way since they are just boundaries.

In 53.1, they work zoomed all the way in, but in 54.1 beta they disappear after zoom level 17.

**Comment by dythbj** [comment]
Yes, dear GordoRank. We have the same problem, and i canno’t find any official description about this.


原始邮件
发件人:GordoRanknotifications@github.com
收件人:mapbox/mapbox-gl-jsmapbox-gl-js@noreply.github.com
抄送:dythbjgaojie@dyth.tech; Authorauthor@noreply.github.com
发送时间:2019年4月5日(周五) 06:57
主题:Re: [mapbox/mapbox-gl-js] Vector Tiles do not rendering when the zoomlevel is over (#8109)


I'm experiencing the same having moved from 53.1 to 54.1 beta.
My particular tileset only contains up to level 7 and usually over overzooms the rest of the way since they are just boundaries.
In 53.1, they work zoomed all the way in, but in 54.1 beta they disappear after zoom level 17.

**Comment by mourner** [comment]
@dythbj we still need a live reproducible test case for this 🙏

**Comment by exotfboy** [comment]
@dythbj First, you can make sure if the tiles are not loaded from the server at all or loaded but not rendered.

**Comment by dythbj** [comment]
> @dythbj First, you can make sure if the tiles are not loaded from the server at all or loaded but not rendered.

Thanks exotfboy. Of course the tiles are not loaded from server, when i zoom over 10, because i just made a 10 level tileset. The question is when i use v0.50.0, it will try retrieving tiles for other zoom levels, but the v0.54.0 not.

**Comment by exotfboy** [comment]
As other people suggested, you may create a live example through jsfiddle, you do not have to deploy your real data to the internet, just show us your scripts and styles(the tile url can be filled like 'http://404.mvt').

Otherwise we can not help you.

**Comment by dythbj** [comment]
> As other people suggested, you may create a live example through jsfiddle, you do not have to deploy your real data to the internet, just show us your scripts and styles(the tile url can be filled like 'http://404.mvt').
> 
> Otherwise we can not help you.

Yes, my shell for make tileset is like: tippecanoe -z10 -L water:/......./water.geojson -o water.mbtiles
and my style is like this:
{
      "id": "water",
      "layout": {},
      "paint": {
        "fill-color": "hsl(196, 80%, 70%)"
      },
      "source": "composite",
      "source-layer": "water",
      "type": "fill"
    }
Hope for you help!

**Comment by dythbj** [comment]
The problem is like this:
![QQ20190425-124220](https://user-images.githubusercontent.com/41282663/56710225-a2a44100-6757-11e9-9b79-1220981e0293.gif)

**Comment by mourner** [comment]
@dythbj a gif won't help — we still can't diagnose this without a live reproducible test case.

**Comment by dythbj** [comment]
> @dythbj a gif won't help — we still can't diagnose this without a live reproducible test case.
Dear mourner:
Finally, i make a live reproducible test case:[http://jsrun.net/mrXKp/edit](url)

Checkout!

**Comment by exotfboy** [comment]
You didn't set the `maxzoom` of the source.

Check this:
https://jsfiddle.net/dem5qL0w/

**Comment by dythbj** [comment]
> You didn't set the `maxzoom` of the source.
> 
> Check this:
> https://jsfiddle.net/dem5qL0w/

Thanks exotfboy:
Yes, it works! Also i have another problem, if i have 2 layers in my source, layer1's maxzoom is 11, layer2's maxzoom is 18, which one shoud i set in my source?

**Comment by exotfboy** [comment]
Then you should serve the two layers in two separate sources instead.

**Comment by dythbj** [comment]
> Then you should serve the two layers in two separate sources instead.

em, i always want to know, that there are 100+ layers in mapbox's basemap, are they have the same maxzoom, or are they's maxzoom all 22?

**Comment by mourner** [comment]
Layers minzoom/maxzoom control which layers to skip when processing/rendering the map on a particular zoom. Source minzoom/maxzoom controls which tiles to request — e.g. if you don't set maxzoom, the map will try to request new z19 tiles when you zoom to 19, with the map disappearing, instead of overzooming z18.

**Comment by dythbj** [comment]
> Layers minzoom/maxzoom control which layers to skip when processing/rendering the map on a particular zoom. Source minzoom/maxzoom controls which tiles to request — e.g. if you don't set maxzoom, the map will try to request new z19 tiles when you zoom to 19, with the map disappearing, instead of overzooming z18.

Yes mourner, but i still don't know why it's all right in 0.50.0?
