### ISSUE TITLE
What solution to improve the user experience when downloading maps?

### ISSUE THREAD

**Issue by doankhoa95** [mapbox/mapbox-gl-js#8117]
How can I limit the display of data in the user view. I have a big data to display on the map including line, symbol, polygon. I don't think of any other solution to improve the user experience in addition to downloading data in a view. Thanks for all comments!

**Comment by mourner** [comment]
For general questions, please use StackOverflow or contact Mapbox support. This repo is limited specifically to issues with GL JS.
