### ISSUE TITLE
How can I use mbtiles with Mapbox

### ISSUE THREAD

**Issue by minhhq221190** [mapbox/mapbox-gl-js#8126]
Hi,

I'm currently dealing with offline map, markers and poligon. After searching with google, I found out that the Mapbox support offline map and the MBtiles is the source data to display. But, when I was doing some code with the mapbox js, I do not know how to load the mbtiles file to display the map, I followed example but cannot find the way out (most of them use pbf or png tiles).
It looks like that I miss understand some where. May someone help me out,  please?

**Comment by mourner** [comment]
GL JS (this repo) does not support offline maps. GL Native (the core of our mobile SDKs does), but has a different format than MBTiles. See the docs for offline maps here: https://docs.mapbox.com/help/troubleshooting/mobile-offline/
