### ISSUE TITLE
@mapbox/geojson-rewind does not exist

### ISSUE THREAD

**Issue by Wykks** [mapbox/mapbox-gl-js#8127]
**mapbox-gl-js version**: 0.53.1

**browser**: N/A

### Steps to Trigger Behavior

@mapbox/geojson-rewind listed in dev dependencies doesn't exist in npm repository https://www.npmjs.com/search?q=%40mapbox%2Fgeojson-rewind

Due to this, you cannot use mapbox-gl in stacklitz for example.
(Try to add mapbox-gl to deps in any stackblitz project)

**Comment by mourner** [comment]
What do you see when you type `npm info @mapbox/geojson-rewind` with the latest NPM version?

**Comment by Wykks** [comment]
Well.. I do see the package :open_mouth: 

Not sure why it's not listed in npmjs website, nor not found by stackblitz then...

**Comment by mourner** [comment]
I'm not sure too, but this doesn't seem like an issue on our side.

**Comment by sandipp** [comment]
> Well.. I do see the package 😮
> 
> Not sure why it's not listed in npmjs website, nor not found by stackblitz then...

@Wykks do you got solution for this?

**Comment by Wykks** [comment]
@sandipp Not yet
