### ISSUE TITLE
generateId vs generateIds discrepancy in documentation

### ISSUE THREAD

**Issue by mvl22** [mapbox/mapbox-gl-js#8133]
For a GeoJSON source, documentation refers in various places to generateIds (plural):

"For GeoJSON sources without feature ids, set the `generateIds` option in the GeoJSONSourceSpecification to auto-assign them."
https://docs.mapbox.com/mapbox-gl-js/api/#map#setfeaturestate
https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/map.js#L1469

but in the spec it seems to be `generateId` (singular):
https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/reference/v8.json#L385

and using `generateIds` gives:
`Error: sources.[mySourceName]: unknown property "generateIds"`

Looks like the correct thing to use is therefore `generateId`, though admittedly `generateIds` would have been a clearer string to use, as it generates multiple IDs, one for each GeoJSON feature.

**Comment by asheemmamoowala** [comment]
@mvl22 Thanks for reporting this issue. Would you be interested in opening a PR to address this issue?

**Comment by asheemmamoowala** [comment]
closed by #8549
