### ISSUE TITLE
fill-extrusion  for sloped polygon

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#8136]
mapbox-gl-js support `fill-extrusion` to simulate 3d polygons like buildings, however it seems that it only support the polygon with the same height(`fill-extrusion-height`) and base height(`fill-extrusion-base`) , like this:

![image](https://user-images.githubusercontent.com/16457917/55781430-b35c8200-5adc-11e9-8cd2-6dba71eee19f.png)

I wonder if it can support the sloped polygon which means the polygon may have different height and base height:

![image](https://user-images.githubusercontent.com/16457917/55781481-ccfdc980-5adc-11e9-9abf-5585c9904f65.png)

Is this possible?

**Comment by andrewharvey** [comment]
I think introducing this kind of complexity is best handled by loading a 3D model rather than overloading fill-extrustion.

If it was done through fill-extrusion how would you propose the style spec would work?

**Comment by exotfboy** [comment]
For a single,small feature, we can use the 3D model, but how about an overpass (represented by polygon)? 

It would be a hard job to build the 3D model, and we still have to adjust the accurate location for the model in the map.

> If it was done through fill-extrusion how would you propose the style spec would work?

I think the current style spec is enough, the  information about the height and base height can be read from properties of the feature.

**Comment by andrewharvey** [comment]
When you say sloped polygon? Do you mean to support different roof shapes like https://wiki.openstreetmap.org/wiki/Simple_3D_buildings#Roof_shape ? Is this ask the same as #3998?

**Comment by exotfboy** [comment]
Yes but go further. Not only different roof shapes but the road especially the overpass:

![image](https://user-images.githubusercontent.com/16457917/55844144-7fca3800-5b6e-11e9-9edb-427d75d02f47.png)

**Comment by peterqliu** [comment]
>I think the current style spec is enough, the information about the height and base height can be read from properties of the feature

This is more complex than it might seem -- we'd have to represent a height and base value for each vertex, handle errors gracefully, and somehow generate planes with points that aren't coplanar (triangulation?). Agree that this is better suited for 3D models in a custom layer.

**Comment by peterqliu** [comment]
Closing for now, until a solid implementation idea materializes

**Comment by xavier630** [comment]
+1 for this feature. 

In my case I really just want 3d linestrings, though could work with extruded polygons if they could be slanted.

**Comment by ats1999** [comment]
> +1 for this feature.
> 
> In my case I really just want 3d linestrings, though could work with extruded polygons if they could be slanted.

+1
