### ISSUE TITLE
IE11 Function Expected Error

### ISSUE THREAD

**Issue by LeeDavidPriest** [mapbox/mapbox-gl-js#8139]
**mapbox-gl-js version**: 0.52.0 and 0.53.0

**browser**: Internet Explorer 11

### Steps to Trigger Behavior

 1. Load up IE11 and open the console
 2. Navigate to https://docs.mapbox.com/mapbox-gl-js/example/fitbounds/
 3. Click the 'fit to Kenya button'
 4. There is likely to be some SCRIPT5002 function expected errors in the console

### Expected Behavior

Map animations such as setting bounds and zooming in and out don't cause errors to be thrown.

### Actual Behavior
So far I have found that using bounds.extend, fitBounds or using the zoom in and out buttons can cause IE11 to throw the following error sometimes multiple times:

SCRIPT5002 function expected
File: mapbox-gl-unminified.js, Line: 18341, Column: 13

Having a look at the error in the console this if statement is highlighted:

```
if(data.type === ‘<response>’ || data.type === ‘<cancel>’) {
     callback = this.callbacks[data.id]
     delete this.callbacks[data.id]
  if(callback && data.error) {
     callback(deserialize(data.error));
  } else if (callback) {
     callback(null, deserialize(data.data));
  }
}
```

The **callback(deserialize(data.error));** is the line that IE11 is flagging as the issue.

I experienced this issue using both minified and unminified versions of mapbox-gl.js. 

The errors don't cause the map to crash and there's nothing really noticeable to a user but the errors are still there in the background and are fired through to our sentry account causing quite high usage.

**Comment by mourner** [comment]
This is fixed in `v0.54.0-beta.1` and will be fixed in the final `v0.54.0` release.
