### ISSUE TITLE
custom layer(3D) and fill-extrusion layer display issue

### ISSUE THREAD

**Issue by yangjnMapBox** [mapbox/mapbox-gl-js#8145]
1."map.getStyle().layers " can't get custom layer;
2.map loads custom layer and  fill-extrusion layer , fill-extrusion is showed through custom layer(3d model).
![image](https://user-images.githubusercontent.com/44802474/56013529-b39a8e80-5d23-11e9-8c54-494406e3a8e1.png)
(https://user-images.githubusercontent.com/44802474/56013547-c745f500-5d23-11e9-99f4-c5023ef74dac.png)

**Comment by jingsam** [comment]
Do you add `this.renderingMode = '3d'` in your custom layer?

**Comment by yangjnMapBox** [comment]
i don’t add renderingMode=3d.
when i delete fill-extrusion-pattern of fill-extrusion layer ,map show ok.

发自我的 iPhone

**Comment by jingsam** [comment]
you should!
