### ISSUE TITLE
Mobile: global stopPropagation lead to page not scrollable 

### ISSUE THREAD

**Issue by AlanKnightly** [mapbox/mapbox-gl-js#8147]
see the simplest demo below:
https://codepen.io/alanknightly/pen/BEZZYw

After touchmoving the map container on mobile devices, you cant scroll the page, and everytime you zoom in/zoom out the map, the zoom level seems to be reset at the first moment you scaling the map.

Im not sure is this a issue of mapbox or just a mistake of my webpage's js logic. But I did meet this problem and we know how to walkaround it now.
I just want to report that I have met this odd situaction.

**Comment by ryanhamley** [comment]
By stopping propagation of the `touchend` event on the map object, the map will never know that you've stopped interacting with it and will continue to pan around when you're trying to scroll the page. This is an issue with your setup, not the library itself. Thanks!
