### ISSUE TITLE
Mapbox Visual - PowerBI, polygons not interactive only basemap 

### ISSUE THREAD

**Issue by amymcampbell** [mapbox/mapbox-gl-js#8148]
I've been trying to use PowerBI to visualise some data interactively but this only works for point lat/lon data. So I've been developing the polygons in Mapbox and then using the PowerBI Mapbox Visual plugin to add these in, however it only adds these in as a basemap eg no information provided when clicking on polygons like the usual data in PowerBI. 

Can anyone suggest how to do this or if there is a better way?
Thanks

**Comment by andrewharvey** [comment]
Have you seen https://github.com/mapbox/mapboxgl-powerbi?

**Comment by mourner** [comment]
Not sure what's the best place to ask this question (maybe contact support?), but I'll have to close this because it's not a core Mapbox GL JS issue.
