### ISSUE TITLE
Report missing layer as error

### ISSUE THREAD

**Issue by BHare1985** [mapbox/mapbox-gl-js#8152]
## Motivation

I just spent the past 5 hours trying to debug why my vector tiles were not appearing. Turns out my node-mapnik server was setting the layer name dynamically at the request level. There was no indication from mapbox GL that anything was wrong, despite my request for a layer called "defaultLayer" and there only exists two layers in the vector: "carto1" and "carto2"

I had to breakpoint https://github.com/mapbox/mapbox-gl-js/blob/e0c4d4679d06be7c0f51970b26a184f8d9ed6d5b/src/source/vector_tile_worker_source.js#L51 and look at the payload to figure out it was getting a different layer

## Design Alternatives

Only care if a layer is missing, not is there are erroneous layers
send console.err if some sort of debug mode is set (Does a debug mode exist?)
send console.warn instantly with or without debug mode
send console.info instantly with or without debug mode

## Design

I believe a good approach is to have some sort of debug mode that is available to the end consumer of the library. (If one exists, it has to be enabled in the all the demos, because I worked off a demo).

If such a debug mode existed, then I think it would be appropriate to send a console.err or even throw a js error if the map configuration is looking for a layer that does not exist in the vector.

You could argue that it could be removing a "feature" in that vector tiles will show a layer if it exists, but fail gracefully if it does not. I would conclude that such a feature should be controlled at a higher level (wrapper to standard mapbox gl) since the common use-case (I assume) would be that there is a 1:1 correspondence to what you want to render and what the vector contains, having more or less can be considered an invalidate state.

### Mock-Up

N/A

### Concepts

I do not know if this is considered a breaking change from an API/Mapbox standpoint, but I think consideration should be given in that people may be abusing/using this feature/bug currently. This new feature should probably have some sort of verbose/debug opt in

### Implementation

I don't know the code enough but I think something at https://github.com/mapbox/mapbox-gl-js/blob/e0c4d4679d06be7c0f51970b26a184f8d9ed6d5b/src/source/vector_tile_worker_source.js#L51

That looks at the parsed layer names are contained in a hashset of the possible layer configurations

**Comment by mourner** [comment]
> the common use-case (I assume) would be that there is a 1:1 correspondence to what you want to render and what the vector contains, having more or less can be considered an invalidate state.

This is tricky, because it's very common for layers referenced in the style to not be present in a particular tile. E.g. imagine having a building layer, but browsing to an area where there are no buildings. This goes for both differences across tiles on the same zoom and across zoom levels.

**Comment by peterqliu** [comment]
>why my vector tiles were not appearing

@BHare1985 do you mean you were adding a style layer for a given vector source-layer, and no features appeared? If so, it would be helpful to check against that vector tileset's tileJSON, which contains a comprehensive list of source layers within. That would be the most reliable way to see if you got the source-layer's name right.

Checking against individual tiles isn't as good, because they don't list source-layers without features inside the tile, even if that layer exists somewhere else in the tileset.
