### ISSUE TITLE
Unable to find package @mapbox/geojson-rewind

### ISSUE THREAD

**Issue by arturhun** [mapbox/mapbox-gl-js#8153]
Hi, Not sure whose responsibility it is, but I wanted to create a stackblitz.com sandbox project using mapbox-gl and when adding the package, I got this failure error:

PACKAGE NOT FOUND
Unable to find package @mapbox/geojson-rewind in the NPM registry.

I looked into my main project and I am apparently not using this one, so not sure why it was found required. Is that something that mapbox would be able to fix?

(stackblitz.com > TypeScript project > add dependency)

**Comment by mourner** [comment]
This seems to be a Stackblitz bug — please report it there. @mapbox/geojson-rewind is present in the NPM registry, which you can verify with `npm info @mapbox/geojson-rewind`. Previously reported in #8127.
