### ISSUE TITLE
onRemove with WebGLRenderingContext argument

### ISSUE THREAD

**Issue by ogiermaitre** [mapbox/mapbox-gl-js#8154]
## Motivation

It is said in the documentation that onRemove gives a chance to clean up listeners and gl ressources.
I use this method to delete the buffers I allocated using createBuffer before. It would be convenient to have the WebGLRenderingContext (gl) passed to this function, as it is done with the onAdd method. It also would be symmetrical (add, remove).

Is there any reason why this is not the case ?

Thanks,
Regards

### Mock-Up

```
onRemove(map,gl){
 //...
}
```

**Comment by mourner** [comment]
I think this would be a sensible addition. Want to submit a PR? Should be a 1-line change.

**Comment by ogiermaitre** [comment]
I would be glad to. I will look into it ASAP.
