### ISSUE TITLE
403 Forbidden for Geocoding API request

### ISSUE THREAD

**Issue by jijishthomas** [mapbox/mapbox-gl-js#8155]
Hi,
I am using mapbox tiles with leaflet js. 
While firing a reverse geocoding API request, I am getting 403 Forbidden!!
The map tiles are served correctly, but issue only for geocoding API.
I tried using the same key which is used for maps.

I am currently developing hybrid mobile application via IONIC framework. I am facing this issue both from locahost and from the real mobile application.

**Comment by mourner** [comment]
Please contact support for any issues with the Geocoding API. This place is for reporting issues about Mapbox GL JS library specifically.
