### ISSUE TITLE
MapMouseEvent docs are not full

### ISSUE THREAD

**Issue by HarelM** [mapbox/mapbox-gl-js#8162]
**mapbox-gl-js version**:
Latest: 0.54

**browser**:
Any

### Steps to Trigger Behavior

 1. write console log on a mouse event to learn what are the available properties

### Link to Demonstration
https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/

### Expected Behavior
Docs should contain all properties in the event

### Actual Behavior
Properties such as `features` are not documented.
This in theory is not problematic since I can usually do `console.log(event)` in most cases.
But since this fails in chrome with the following error:
`Error: Object too large to inspect. Open your browser console to view.` it makes it extremely annoying to understand what are the properties of an object.

**Comment by fc** [comment]
"Error: Object too large to inspect. Open your browser console to view." -- is that an actual Chrome error?  Who or what is generating that error message?  Can't you just open Chrome's console to see the object?

**Comment by HarelM** [comment]
@fc Yes, this is a chrome error, but not the issue I'm talking about. 
I can probably inspect the object using the debugger but then I can't know which field is public and part of the API and which is private and can change, I know there's a convention of "_" for private fields but still - these things should just be a part of the docs so that no one will get confused...

**Comment by domlet** [comment]
Fixed by mapbox/mapbox-gl-js#10825
