### ISSUE TITLE
heatmap that doesn't change with zoom?

### ISSUE THREAD

**Issue by wysisoft** [mapbox/mapbox-gl-js#8165]
Can I have a heatmap that stays static while zooming? The default heatmap basically disappears after a few zoom levels.

**Comment by peterqliu** [comment]
@wysisoft what do you mean by staying static? If you're looking for the radii to scale with the real-world distance, you can do a zoom-dependent `heatmap-radius` that doubles with every integer zoom level.

**Comment by mourner** [comment]
Yep, you can define radius to be a multiple of 2^zoom with an expression.
