### ISSUE TITLE
Fix outdated mention of RawGit in the GeoJSON help guide

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#8169]
I was reading [Working with large GeoJSON sources in Mapbox GL JS](https://docs.mapbox.com/help/troubleshooting/working-with-large-geojson-data/) and came across this sentence: 

> For GitHub files, you can use RawGit, which makes sure that the proper Content-Type header is applied to your data. 

Interestingly:

> RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.
> 
> GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
> 
> If you're currently using RawGit, please stop using it as soon as you can. 

¯\_(ツ)_/¯

**Comment by mourner** [comment]
Nice catch! Seems like there's an alternative now: https://raw.githack.com/ — want to submit a PR with a fix?

**Comment by ahk** [comment]
Hi @3zzy thanks for the help. This info was updated and merged.
