### ISSUE TITLE
How to found nearest feature

### ISSUE THREAD

**Issue by Parveenkmr44** [mapbox/mapbox-gl-js#8171]
**mapbox-gl-js version**:0.53.1

### Question
I have a feature and want to find the nearest feature of this. Can anyone please help in the same.

### Links to related documentation

http://embed.plnkr.co/GDixNNDGqW9rvO4R1dku/

**Comment by peterqliu** [comment]
Not internally, but you can use Turf: https://turfjs.org/docs/#nearestPoint

**Comment by Parveenkmr44** [comment]
@peterqliu Thank you
