### ISSUE TITLE
Utility functions to get mapscale and to convert mapscale to zoom level

### ISSUE THREAD

**Issue by geoyogesh** [mapbox/mapbox-gl-js#8172]
## Motivation

I am rewriting the arcgis javascript web application to mapbox gl.

I refactored most of existing features.

like rendering the existing arcgis dynamic mapservice in mapbox gl
this.map.addLayer({
          'id': 'some-id',
          'type': 'raster',
          **'minzoom': 7,
          'maxzoom': 15,**
          'source': {
              'type': 'raster',
              'tiles': [ mapserviceUrl + '/export?token=' + token + '&dpi=96&transparent=true&format=png32&layers=show%3A' + layerId + '&bbox={bbox-epsg-3857}&bboxSR=EPSG:3857&imageSR=EPSG:3857&size=256,256&f=image'],
              'tileSize': 256
          },
          'layout': {
            'visibility': 'visible'
            }
      });

There are couple if missing pieces to consider   

1. setting the min and max zoom level for layer..if there are any unity functions to convert scale such as 1:2454232.26 to zoom level 7.. it would be really great.

2. displaying the current map scale such as 1:2454232.26. this as fairly easy to implement in arcgis javascript api using  getScale method. but i couldnt find any alternative in mapbox gl
https://developers.arcgis.com/javascript/3/jsapi/esri.geometry.scaleutils-amd.html

**Comment by peterqliu** [comment]
I could be misunderstanding, but this is difficult on web mercator for two reasons:

- the Web part: we're rendering to pixels, which could be different real-world dimensions depending on your display settings and resolution
- the Mercator part: the projection scales the map slightly differently at every latitude, so there isn't one specific ratio

If you do get a ratio for zoom 0, though, it doubles for every incremental zoom level.

**Comment by geoyogesh** [comment]
Sorry i thought it a basic feature... please correct me if am wrong... if we can show scale-bar for a map extent(existing scalebar widget) then we should able to get the scale in ratio's too right?

**Comment by peterqliu** [comment]
The scale bar is valid as long as it stays _to scale with the map_. We can stretch or shrink the whole thing, and it would still represent the same distance. But expressing scale in terms of a ratio depends on how big it actually appears, and that depends on the device display.

Put another way, we can express the scale ratio on paper maps, because we get to control how big we're printing it. But we don't have the same control on screens.

**Comment by geoyogesh** [comment]
this is closest value i can get by trail and error but its not perfect... I am pretty sure i am missing simething
const y = this.map.getCanvas().height;
    const x = this.map.getCanvas().width;
    const left = this.map.unproject([0, y]);
    const bottom = this.map.unproject([x, y]);
    const maxMeters = turf.distance(turf.point([left.lng, left.lat]), turf.point([bottom.lng, bottom.lat]), { units: 'miles' }) * 1609.344;
    const metersPerPixel = (maxMeters / x);
    const metersOnScreen = metersPerPixel * window.screen.availWidth; 
    const scale = metersOnScreen / 0.28;
    this.currentScale = (scale).toFixed(2);

**Comment by peterqliu** [comment]
What you're missing is precisely what I've alluded to in my past two comments: the physical dimensions (centimers/inches/millimeters) of the display regardless of pixels. Without it, you can express `metersPerPixel`, but not an actual scale ratio.

**Comment by geoyogesh** [comment]
is there a way to determine whether empty layer are getting loaded into raster layer [arcgis server returns empty tiles if requested zoom level is not within the min and max scale].. that way i can update the application to set the custom layer selector to disabled state
![image](https://user-images.githubusercontent.com/1282742/56531559-40162f80-6522-11e9-8914-8332027afc5c.png)
