### ISSUE TITLE
Unexpected event sequence

### ISSUE THREAD

**Issue by HarelM** [mapbox/mapbox-gl-js#8175]
**mapbox-gl-js version**: 0.53.1

**browser**: chrome 73.0.3683.103 

### Steps to Trigger Behavior

 1. register to the following events: `mousedown` `mouseup` `mousemove` `touchstart` `touchmove` `touchend`
 2. Click on a windows laptop with touch screen on the map

### Link to Demonstration
https://jsbin.com/jevaqibinu/1/edit?html,js,output

### Expected Behavior
The following events should fire in this order:
`touchstart`
`touchend`
 - OR -
`touchstart`
`mousedown`
`mouseup`
`touchend`
- OR -
`mousedown`
`touchstart`
`touchend`
`mouseup`

### Actual Behavior
`touchstart`
`touchend`
`mousemove` (??)
`mousedown`
`mouseup`

I would like to support both touch screen and regular mouse and this really complicate things when I'm trying to add custom interaction to the map...

**Comment by peterqliu** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent#Event_order

Turns out this is both

- the intended behavior by Mozilla, and Windows is following suit, and
- the ordering is implementation-specific, and out of our control

**Comment by HarelM** [comment]
@peterqliu thanks for the info!
if anyone else gets here: It seems that calling `event.originalEvent.preventDefault()` allows canceling the mouse events if needed.
