### ISSUE TITLE
What is the element with the class="mapboxgl-canary"

### ISSUE THREAD

**Issue by veratechnz** [mapbox/mapbox-gl-js#8178]
**mapbox-gl-js version**:
"mapbox-gl": "^0.37.0",' npm version

### Question
What is the element with the class="mapboxgl-canary"?
I have it on my local version but when I deploy the app to heroku this element dissappears...
`<div class="mapboxgl-canary" style="visibility: hidden;"></div>`
Just wondering what this is, and what it's purpose is for....

### Links to related documentation
I searched in docs and on Google, there isn't a lot on this question...
https://docs.mapbox.com/mapbox-gl-js/api/
https://docs.mapbox.com/mapbox-gl-js/api/#user%20interface

**Comment by mourner** [comment]
You don't need to worry about it. It's a temporary element created to check if Mapbox GL CSS file is loaded when rendering the map, and log a warning if not:

https://github.com/mapbox/mapbox-gl-js/blob/4cce1a9150c06f5bf6cf44867d78fd59b30b2b83/src/ui/map.js#L1563-L1571

**Comment by brookjordan** [comment]
@mourner Is there any way to manually skip this check? The way we load the CSS means we can’t guarantee it will be there when mapbox is initialised, but it will always be loaded soon after.

**Comment by mourner** [comment]
@brookjordan one way to skip the check is to have the following CSS snippet loaded somewhere before GL JS:

```css
.mapboxgl-canary { background-color: salmon; }
```
