### ISSUE TITLE
Video example does not load on IE 11

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-js#8187]
**mapbox-gl-js version**: 0.54.0-beta.2 
Possibly earlier versions too

**browser**: Internet Explorer 11 (IE11)

### Steps to Trigger Behavior

 1. Load the video example https://www.mapbox.com/mapbox-gl-js/example/video-on-a-map/

### Expected Behavior
Video overlay on top of raster layer

### Actual Behavior
No video overlay, not even a black screen like seen in #7567

**Comment by ansis** [comment]
[IE 11 is no longer supported](https://github.com/mapbox/mapbox-gl-js/blob/main/CHANGELOG.md#200).
