### ISSUE TITLE
geocoder plugin does not work in IE11

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-js#8188]
All the geocoder plugin examples at  https://docs.mapbox.com/mapbox-gl-js/example/ don't work in IE11.

**mapbox-gl-js version**: 0.54.0-beta.2
**browser**: Internet Explorer 11 (IE11)

The `mapbox-gl-geocoder` plugin has a dependency on `@mapbox/mapbox-sdk` which is an ES6 module, and requires polyfill of `Promise` for old browsers. 

Ideally, the GL-JS examples should include a polyfill so that the example works, and `mapbox-gl-goecoder` also documents that need for polyfills in its README.

### Expected Behavior
Typing in the geocoder shows auto-complete results

### Actual Behavior
Geocoder text input shows spinner icon, but never shows any auto-complete results.

Browser console reports error that `Promise` could not be found.

**Comment by colleenmcginnis** [comment]
cc @katydecorah @scottsfarley93
