### ISSUE TITLE
Functional inconsistency: validation cannot be disabled for API methods queryRenderedFeatures, querySourceFeatures,  addSource, addLayer

### ISSUE THREAD

**Issue by gorshkov-leonid** [mapbox/mapbox-gl-js#8189]
API provides way to disable expressions validation for some cases. As I undastand it has been done for performace in production, it is our case too. Next methods provide ability to disable validation:
- Map.setFilter
- Map.setLayoutProperty
- Map.setPaintProperty
- Map.setFilter
- Map.setLight

But validation also is used  in following methods, and cannot be disabled:
- queryRenderedFeatures, querySourceFeatures 
- addSource, addLayer (are not so critical)

**mapbox-gl-js version**: 0.54 beta 2
**browser**: any

**Comment by gorshkov-leonid** [comment]
Sorry for typo

**Comment by mourner** [comment]
This shipped for `queryRenderedFeatures`, `querySourceFeatures`. I think we can close this because `addSource` and `addLayer` aren't per-frame operations, so don't really need this optimization.

**Comment by gorshkov-leonid** [comment]
Yes, I agree
