### ISSUE TITLE
Layers with the same features will not both be visible

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#819]
If you create two layers that have the same features (same data layer and same filters), only the layer placed first is visible, even using the `text-allow-overlap` and `text-ignore-placement` options. 

For reference, I am trying to get two labels rendered for the same features in order to use `text-translate` to create a drop shadow effect.

If this is not a JS issue I can ticket elsewhere.

/cc @kkaefer @mourner @tmcw @edenh

**Comment by lbud** [comment]
@nickidlugash is this still the case for you? I'm seeing
![image](https://cloud.githubusercontent.com/assets/3170312/5639838/2f14dc46-95d2-11e4-90cb-fed456f9ae2b.png)
with layers
``` json
{
    "id": "road_label_shadow",
    "type": "symbol",
    "source": "mapbox",
    "interactive": true,
    "source-layer": "road_label",
    "minzoom": 6,
    "paint": {
      "text-size": 32,
      "text-halo-width": 1,
      "text-halo-color": "white"
    },
    "layout": {
      "text-field": "{name_en}",
      "text-font": "Open Sans Semibold, Arial Unicode MS Bold",
      "text-max-size": 32,
      "text-max-width": 10,
      "symbol-placement": "line"
    }
  }, {
    "id": "road_label",
    "type": "symbol",
    "source": "mapbox",
    "interactive": true,
    "source-layer": "road_label",
    "minzoom": 6,
    "paint": {
      "text-size": 32,
      "text-halo-width": 1,
      "text-color": "blue",
      "text-halo-color": "white",
      "text-translate": [4,4]
    },
    "layout": {
      "text-field": "{name_en}",
      "text-font": "Open Sans Semibold, Arial Unicode MS Bold",
      "text-max-size": 32,
      "text-max-width": 10,
      "symbol-placement": "line",
      "text-allow-overlap": true,
      "text-ignore-placement": true
    }
  }
```

**Comment by nickidlugash** [comment]
@lbud I hadn't tested since I opened the issue, but I just tested it now and it seems to be working :+1:
