### ISSUE TITLE
osm_id returned with map.featuresAt() is always 0

### ISSUE THREAD

**Issue by thomaskonrad** [mapbox/mapbox-gl-js#820]
Hi,

I'm trying to get more information about a feature on the map when the user clicks on it, and therefore I need the osm_id of the object(s). Now when I retrieve the features under the mouse cursor with `featuresAt()`, the osm_id is always 0 (I have only tested it with POIs so far). Here's an example:

```
[Object]
    0: Object
        _bucket: "poi_label_4"
        _type: "Point"
        extent: 4096
            properties: Object
                localrank: 23
                maki: "restaurant"
                name: "Heidenkummer"
                [SNIP]
                osm_id: 0
                ref: ""
                scalerank: 4
                type: "Restaurant"
                website: "http://www.heidenkummer.at/"
            [SNIP]
```

Now the osm_id should rather be 1031098737 in this particular case. When analyzing the vector tile, this is what I see:

```
  values {
    string_value: "Heidenkummer"
  }
  values {
    int_value: -1031098737
  }
  values {
    string_value: "http://www.heidenkummer.at/"
  }
```

So the tile source returns the correct value. Is returning always 0 as the osm_id intended behavior? If so, how can I get the osm_id of a POI a user clicked on?

Thank you
Tom

**Comment by mourner** [comment]
I assume this is no longer reproducible since pbf can handle big integers now (both signed and unsigned, fixed and varint) .
