### ISSUE TITLE
Get Actual visible feature properties along with default cluster properties 

### ISSUE THREAD

**Issue by moorthysubu** [mapbox/mapbox-gl-js#8202]
Hi, 
Android SDK version 7.2.0, 
Question: How to get actual feature properties along with the cluster's properties when cluster-enabled using GeoJsonSource, When tried to query source features using "querySourceFeatures" this method, It lists the visible clusters features with own cluster properties like cluster_id, cluster,point_count, etc, but cannot able to find the cluster top feature in for that geocoordinate along with this
Can you help me to get it solved?

**Comment by mourner** [comment]
This is a repo for GL JS, not for the Android SDK. You might be looking for [getClusterLeaves method](https://docs.mapbox.com/android/api/map-sdk/7.3.2/com/mapbox/mapboxsdk/style/sources/GeoJsonSource.html#getClusterLeaves-Feature-long-long-).
