### ISSUE TITLE
Adding Bounce method to Map Markers

### ISSUE THREAD

**Issue by zaouch** [mapbox/mapbox-gl-js#8206]
## Motivation

A bounce method on markers to show off a marker on hover or click. 
Leaflet.js does have this feature, but not the GL API. 

For instance, [here](http://maximeh.github.io/leaflet.bouncemarker/)

**Comment by ryanhamley** [comment]
It looks like this is a third-party plugin for Leaflet, not part of the core API. I think it's unlikely we'd add something like this to the GL JS core API but if you create a solid, well-documented plugin, we'd be happy to add it to the plugins page.
