### ISSUE TITLE
Tilting compass as map tilted

### ISSUE THREAD

**Issue by cs09g** [mapbox/mapbox-gl-js#8208]
## Motivation
When you rotate a map, compass on the navigation control rotates as much as the degree map rotated. but when you tilt the map, the compass doesn't interact for the pitch.

Also, when you click the compass, it makes the map degree to 0 as its default value but pitch would never be back to default even when you click the compass again.

I think when it interacts with both its bearing and pitch, will give better UX.
Implementation would look like(drag mouse on the MAP labeled element, and see compass below. and click the compass):
https://jsfiddle.net/cs09g/5an14p6r/

**Comment by mourner** [comment]
That's a cool idea! Want to make a PR with the change?

**Comment by cs09g** [comment]
Sure, one more discussion left about compass button clicking. One options is to reset bearing and pitch at once, the other is two-step reset-first click: reset bearing, second click(when bearing is 0): reset pitch. Which option would be better?

**Comment by cs09g** [comment]
@mourner Could you share your idea for the options?

**Comment by mourner** [comment]
I'm not sure, both seem good... @samanpwbb what do you think?

**Comment by andrewharvey** [comment]
I think one click to reset both is simpler.

**Comment by ryanhamley** [comment]
This is basically closed by https://github.com/mapbox/mapbox-gl-js/pull/8226 The only thing not implemented in that PR is reseting the pitch when the compass button is clicked

**Comment by samanpwbb** [comment]
I checked Apple and Google maps for precedent and looks like _neither_ use the compass to control pitch. The compass's sole purpose is to communicate the cardinal directions and to allow user to reset direction. Pitching the compass makes directionality less clear. 

Therefore, I am actually not sure a rotating compass control is a good idea. At the very least, this should be an optional feature.

If we do implement it, one click to reset would likely match user expectations most closely (double-click interactions like this are rare on the web).

**Comment by ryanhamley** [comment]
#8226 does implement pitching on the compass control but we could make the functionality optional in an additional PR that implements the on-click pitch reset.

**Comment by pakastin** [comment]
What would you suggest for the name of the pitching setting?

**Comment by pakastin** [comment]
Hmm.. but it already controls the pitch by default, so wouldn't make much sense 😂

Maybe `visualizePitch`?

**Comment by ryanhamley** [comment]
@samanpwbb You're saying that the compass icon shouldn't move at all by default right? That both pitch and bearing visualization should be optional.

**Comment by pakastin** [comment]
> Therefore, I am actually not sure a rotating compass control is a good idea. At the very least, this should be an optional feature.

I think he meant `rotating` –> `pitching`
