### ISSUE TITLE
Allow external icon-image

### ISSUE THREAD

**Issue by jenius** [mapbox/mapbox-gl-js#822]
Right now the only option for `symbol.icon-image` is a string in reference to a precompiled sprite sheet that's undocumented and very difficult for any normal user to be able to update. If the `icon-image` property would also take a URL to an image and render that, it would be fantastic. This would also mean great support for custom markers, which is a huge missing piece from mapbox gl right now. Bonus points if icon-image would accept svgs!

**Comment by jfirebaugh** [comment]
Remaining issues here are covered by #358.

**Comment by fallenartist** [comment]
Thanks for the explanation @peterqliu. Did anyone manage to use custom markers and would share a working example? For some reason I can't get them to show up linking to either Mapbox or custom style and sprites. See [this question on SO](http://stackoverflow.com/questions/31026462/cant-get-custom-markers-to-work-in-mapbox-gl-js). Thanks.

**Comment by ktruckenmiller** [comment]
+1 @fallenartist

**Comment by lukerollans** [comment]
Hello from 2016 all of the above 2014/15 comments :)

So, we're switching from Google Maps to Mapbox GL, and I've just come across this. The necessity of a sprite sheet is an absolute deal breaker for us. Has this been addressed at all? If not, we'll need to switch to Mapbox.js (leaflet)

**Comment by peterqliu** [comment]
@lukerollans what's your use case? Mapbox Studio now makes the sprite sheet for you, though it still means you prepare it in the map style ahead of time.

**Comment by lukerollans** [comment]
@peterqliu we are a travel companion application, in which our subscribers add their businesses so travelers can find them easily. Within the app is a map page and a "featured image" is used as the map marker. So, they're completely user defined and quite variable.

**Comment by wagerfield** [comment]
What does `sdf` mean in `sprite.json`? You have it set to `false` and so do all the definitions in [`bright.json`](https://www.mapbox.com/mapbox-gl-styles/sprites/bright.json).

**Comment by aidanlister** [comment]
I can't seem to apply colours to the maki icon sprite sheet .. do I need to make my own for each set of colours I want?

**Comment by lucaswoj** [comment]
@aidanlister Maki does not support the `symbol-color` property because it is not an SDF icon set. You must make your own for each set of colors you want. You may find [Maki Chef](https://www.mapbox.com/maki-chef/) useful.

**Comment by wagerfield** [comment]
For anyone who wants to generate their own sprite sheets for Mapbox from SVG icons using gulp, I've created a gulp plugin that wraps Mapbox's [spritezero](https://www.npmjs.com/package/spritezero) package.

You can find the `gulp-spritezero` package [here](https://npmjs.com/package/gulp-spritezero).

The only thing it doesn't do right now is generate SDF images—I haven't figured that bit out yet. So if anyone knows how to do this, please point me in the right direction or create a PR.

**Comment by lucaswoj** [comment]
There hasn't been much communication about this yet but we are seriously considering dropping SDF support because it is undocumented and unused. See https://github.com/mapbox/mapbox-gl-style-spec/issues/444 for more.

**Comment by java99** [comment]
why not use svg? Whats your ideas for the future?

**Comment by java99** [comment]
https://github.com/rev22/svgl ?

what is the purpose of generating sdf/png files when dealing with vector gfx? 
Is there a method to use svg in opengl on your maps?

**Comment by koolkarni** [comment]
Why can i just add my Image url to layout 


    map.addLayer({
        "id": "uck1",
        "type": "symbol",
        "source": "uck1",
        "layout": {
            "icon-image": "http://x.x.x.x/an.png"
        }
    });

**Comment by Scarysize** [comment]
@koolkarni Icons are supplied via a sprite sheet, not via a single file per (potential) feature.
@lucaswoj What is the current stance on SDF icons? We are considering to open source our sprite sheet generator. A simple cli tool to generate a (sdf) sprite sheet from a directory of SVG files.

**Comment by lucaswoj** [comment]
No official stance on SDF icons or per-feature icons at the moment. I'm personally in favor of using an established standard + `icon-colorize` rather than our undocumented SDF standard.

**Comment by mgd722** [comment]
To those of you arriving here from a very frustrating Google search, external/generated icons _can_ be passed to `icon-image` if you use `map.loadImage()` and `map.addImage()` first.

Examples:
[Add an icon to the map](https://www.mapbox.com/mapbox-gl-js/example/add-image/)
[Add a generated icon to the map](https://www.mapbox.com/mapbox-gl-js/example/add-image-generated/)

**Comment by santinogue** [comment]
@mgd722 there's a limitation of 500 icons per sprite right? And only one sprite per map can be loaded, map.loadImage() add the new image to the sprite, as far as I know, our situation is that we are using the symbol layer to implement custom markers and we are reaching the limit of 500 images with the images of the markers and the svgs used by our custom mapbox maps (our layers). Any ideas on how can we sort this issue, other alternatives?

**Comment by Scarysize** [comment]
@santinogue There is a complimentary `map.removeImage` method: https://www.mapbox.com/mapbox-gl-js/api/#map#removeimage

We are using this successfully to switch out icon which are not being displayed right now. If you want to display a lot more icon simultaneously you are going to run into problems.

**Comment by santinogue** [comment]
@Scarysize thanks for your answer, but `removeImage` wont help us. For example, we have copied the street layer from mapbox and made some modifications, we load the sprite containing the svgs for that map and other custom ones, so there are like 400 (or more) icons on that sprite, that leves 100 icons or less to use with the symbol layers (our custom markers), and we want to display them at the same time.

**Comment by Scarysize** [comment]
Okay, but be aware that the limit of icons is not fixed to 500. The limit is the maximum size of the internal sprite sheet, which is limited to 1024x1024px (2048x2048 on retina). So you might squeeze some more icons into your style by using smaller images.

**Comment by santinogue** [comment]
Ok, the 500 icons restriction is specified in the API documentation https://www.mapbox.com/api-documentation/#sprites, anyway, if the limit is 500 or 1000, if we keep adding styles or new icons, we will reach the limit eventually, is this something that want's to be supported?

**Comment by dagjomar** [comment]
@santinogue @Scarysize Are you sure these are hard limits now? After the internal changes to the SpriteAtlas, I believe there might be only hardware or internal memory that would limit the amount of icons you could add using addImage().

**Comment by santinogue** [comment]
@dagjomar I'm not sure, but the documentation led me to think that. Maybe someone can clarify if this limits are still there, and the docs should be updated if not the case.

**Comment by jfirebaugh** [comment]
The limits documented at https://www.mapbox.com/api-documentation/#sprites apply to the sprites web API (`/styles/v1/{username}/{style_id}/sprite/...`). There is no explicit limit to the number of images that can be added via the Mapbox GL JS `addImage` API -- only the effective (and device specific) limits imposed by available RAM and maximum WebGL texture size.

**Comment by shrutikar** [comment]
I used map.loadImage( ) and map.addImage( ). It works fine when the image is "http://.........". I have created my custom icons which lay on my server where my index.html is also there (in the same folder). But it seems to pick the icons mentioned as "http://......" but not the icons in my folder. It works fine on my local machine. Is there a way around to this?

**Comment by lucaswoj** [comment]
@shrutikar It sounds like you're asking about loading icons over protocols other than `http://`, such as via the local file system (`file://`). Protocols other than `http://` may work to some extent but cannot be relied upon. You'll save yourself some trouble if you always use the `http://` protocol, including using a local http development server on your computer. 

[StackOverflow](http://stackoverflow.com/questions/tagged/mapbox-gl-js) is a better place for questions like this in the future. We try to reserve GitHub issues for feature requests and bug reports.

**Comment by mvl22** [comment]
> If the icon-image property would also take a URL to an image and render that, it would be fantastic.

> map.addLayer({
    "id": "uck1",
    "type": "symbol",
    "source": "uck1",
    "layout": {
        "icon-image": "http://x.x.x.x/an.png"
    }
});

Out of interest, what is the technical reason for this not being possible? Is there some fundamental issue here, or is this just not a development priority?

It's possible to create images by creating a DOM element and attaching that to the map, though this is presumably rather inefficient.
