### ISSUE TITLE
Map container is incorrect using fullscreen mode on Android Chrome

### ISSUE THREAD

**Issue by musicformellons** [mapbox/mapbox-gl-js#8222]
**mapbox-gl-js version**: 0.54.0-beta.1

**browser**: Android Chrome

### Steps to Trigger Behavior
 1. A map with a transparant pane on top. 
<img src="https://user-images.githubusercontent.com/10334123/57252048-8d7abc80-704b-11e9-97b1-2c4e215c9d62.png" width="200" height="400">

 2. When you drag the pane up the fullscreen mode is triggered and the top addressbar disappears.
<img src="https://user-images.githubusercontent.com/10334123/57252067-9a97ab80-704b-11e9-9e73-ed3e94fbec00.png" width="200" height="400">

 3. Navigate to another page. 
<img src="https://user-images.githubusercontent.com/10334123/57252093-a5524080-704b-11e9-89c1-ed6d769fb7df.png" width="200" height="400">

 4. Undo fullscreen mode.
<img src="https://user-images.githubusercontent.com/10334123/57252104-b13e0280-704b-11e9-9d2c-4893cc882efb.png" width="200" height="400">

 5. Return to page 1, now the css of the map container is bugged. Half of the page is not filled with map anymore.
<img src="https://user-images.githubusercontent.com/10334123/57252166-d3378500-704b-11e9-8ab5-93412f665f93.png" width="200" height="400">

 6. When going back to fullscreen mode the map container is correct again.
<img src="https://user-images.githubusercontent.com/10334123/57252172-d9c5fc80-704b-11e9-9328-2e4578cea04e.png" width="200" height="400">

### Expected Behavior
The map should have a proper container (fills complete page) when returned to at step 5.

### Actual Behavior
The map container is corrupt/ not ok.

**Comment by mourner** [comment]
This looks like an issue with your app, not with GL JS.

**Comment by musicformellons** [comment]
Because it looks like an issue related to what? Other pages do not show this behavior.

**Comment by musicformellons** [comment]
Solved now, indeed app related... Thx.

**Comment by musicformellons** [comment]
The canvas container I get at step 5 is 400px x 300px which is a [kind of default](https://github.com/mapbox/mapbox-gl-js/blob/bf88cd735b06eacc607c188a2508c9912140768d/src/ui/map.js#L1475) it seems. I use Vue's  'keep-alive' element on the map trying to avoid rerendering/ loading when returning to the map page. The issue seems to be that the container is not yet rendered at the moment of routing back towards the map page. I can hack around it by calling map.resize() on the 'activate'  hook of the map page, but then you have a short flicker which is not nice.

[This seems to be pretty much the same problem](https://github.com/mapbox/mapbox-gl-js/issues/7990), but then on Safari instead of Chrome. I would consider compliance to fullscreen browser guidelines to be a mapbox-gl issue.
