### ISSUE TITLE
`generateId` fails in conjunction with `cluster` (source specification)

### ISSUE THREAD

**Issue by ChiefKleef** [mapbox/mapbox-gl-js#8223]
**mapbox-gl-js version**: 0.54.0

### Steps to Trigger Behavior

Add source with the specifications `cluster = true` and `generateId = true`

### Expected Behavior

All features should have a generated id

### Actual Behavior

Only clustered features have a generated Id

**Comment by asheemmamoowala** [comment]
@ChiefKleef This is currently not supported when using clustered GeoJSON sources. It is being tracked in [this ticket](https://github.com/mapbox/supercluster/issues/97) in the supercluster repo. 

Want to work on a PR for this?

**Comment by ChiefKleef** [comment]
I'm interested in working on it, yes

**Comment by mrmos** [comment]
@asheemmamoowala not sure if it really matters, but this seems more like a bug than a feature?
