### ISSUE TITLE
setRTLTextPlugin is not working in version 0.54.0

### ISSUE THREAD

**Issue by mathimani** [mapbox/mapbox-gl-js#8225]
**v0.54.0**:

**All Browsers**:

mapboxgl.setRTLTextPlugin with react-map-gl is not working, where the same code working fine in v0.53.1.

**Comment by mourner** [comment]
Here's it is working fine with v0.54.0: https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/
If it's not working for you, please provide a minimal reproducible live test case. Closing the issue for now.
