### ISSUE TITLE
setStyle: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by jacknkandy** [mapbox/mapbox-gl-js#8233]
I have been receiving an error `Cannot read property 'get' of undefined` for some time but have been unable to consistently reproduce. 

I have recently identified that this error is occurring in our project as a result of calling the `setStyle` function, but it does not always occur. We have a requirement to update the URL of a given VectorSource. Since there is no way to do this directly, we are using the hack:

```
var newStyle = map.getStyle();
newStyle.sources.<yourSourceId>.tiles = <newSourceUrl>;
map.setStyle(newStyle);
````

as demonstrated here https://github.com/mapbox/mapbox-gl-js/issues/3709#issuecomment-265346656.

This is normally working fine, but sometimes we will receive the error `Cannot read property 'get' of undefined` when calling `setStyle`.

If I do not make any modifications to the source object, e.g.:
```
var newStyle = map.getStyle();
map.setStyle(newStyle);
```
 this error does not occur. 

I would prefer to be able to update the VectorSource directly but there is no current way of doing so (a new feature request perhaps?).

**mapbox-gl-js version**: 0.54.0

**browser**: Chrome 68

### Steps to Trigger Behavior

 1. Add layer using VectorSource
 2. Update `tile` property of source using pattern:
```
const newStyle = map.getStyle();
newStyle.sources[sourceId].tiles = [url];
map.setStyle(newStyle);
```
 3. Error generated by browser

### Demonstration
I have found it very difficult to create a minimal reproduction (due to our vector sources not being accessible outside of the project), so I have attached a GIF instead.

![test2](https://user-images.githubusercontent.com/40873630/57436186-8a1d4600-7282-11e9-8fa7-f4bd9a3c64ab.gif)

Background:
We are using MVT vector tiles for all layers in our project due to the large amount of data we are working with. There is an underlying SQL query that powers each layer which is dynamic with various filters applied (as part of the WHERE clause). 

When the user searches for an item, the underlying query that powers the specific layer is updated to include the item searched for as part of the tiles. When the user clears the search, the query is reset back (i.e. the search filter is cleared).

Each time the query changes, a new tile URL is generated. The source is therefore updated each time using the pattern shown above. It is during the `setStyle` call that the error is generated.

### Expected Behavior
No errors

### Actual Behavior
Receive the following error:
```
zone.js:199 Uncaught TypeError: Cannot read property 'get' of undefined
    at da (mapbox-gl.js:29)
    at e.queryRadius (mapbox-gl.js:29)
    at Xu.loadVectorData (mapbox-gl.js:29)
    at i.a (mapbox-gl.js:33)
    at _u.receive (mapbox-gl.js:29)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17290)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:498)
```

**Comment by jacknkandy** [comment]
I have swapped over from using the dist file **mapbox-gl.js** to **mapbox-gl-dev.js** to get a better stack trace:

```
zone.js:199 Uncaught TypeError: Cannot read property 'get' of undefined
    at getMaximumPaintValue (mapbox-gl-dev.js:17355)
    at CircleStyleLayer.queryRadius (mapbox-gl-dev.js:24559)
    at Tile.loadVectorData (mapbox-gl-dev.js:32173)
    at VectorTileSource.done (mapbox-gl-dev.js:39519)
    at Actor.receive (mapbox-gl-dev.js:30619)
```

It appears the error is originating from the following line:
https://github.com/mapbox/mapbox-gl-js/blob/dd2f519d85bbf1d863aa3cb16aed5842e775afa3/src/style/query_utils.js#L11

I have put a console.log on the `layer.paint` property and it is undefined at the time of execution. Could this be a possible timing issue?

![image](https://user-images.githubusercontent.com/40873630/57496556-06f9ff80-7317-11e9-9f2e-868839e89a7d.png)

**Comment by DinakaranS** [comment]
Hi jacknkandy,
 
Even i am getting the same error.
<img width="551" alt="Screenshot 2019-05-10 at 2 46 56 PM" src="https://user-images.githubusercontent.com/8424594/57516587-a24c9e00-7332-11e9-9057-e28f71f86a31.png">

**Comment by vince1995** [comment]
Any progress on this?

**Comment by asheemmamoowala** [comment]
It is very hard and time consuming to work on this issues without a minimal reproducible case. It helps speed up debugging and ensuring that the fix is not speculative but addresses the root cause.

cc @vince1995 @jacknkandy @DinakaranS

**Comment by zhyt1985** [comment]
try set options.diff to false

**Comment by lizapritchard** [comment]
@zhyt1985 could you elaborate on this? I'm having a similar issue

**Comment by simplemind** [comment]
Hi,
I started getting a similar issue after adding a marker with color property. It appears that adding a comma after the last property resolves the issue.

The guide recommends using this which causes an issue:
`const marker1 = new mapboxgl.Marker({ color: "black" })`

whereas the below with an added comma no longer reproduces the error:
`const marker1 = new mapboxgl.Marker({ color: "black", })`

I hope this solves your issues also.

**Comment by bk201lucifer** [comment]
> 贴 Have you solved it

**Comment by dtabarceazeni** [comment]
Getting a similar error when mounting and un-mounting maps in quick succession 
![Screenshot 2023-07-19 at 18 54 49](https://github.com/mapbox/mapbox-gl-js/assets/109207790/815a9248-9c1f-41f7-803c-2418928c857f)

**Comment by amplicity** [comment]
This happens periodically with me as well, and i've had a hard time reliably reproducing. Has anyone solved this?
