### ISSUE TITLE
Avoiding mouse events with opacity 0

### ISSUE THREAD

**Issue by mklopets** [mapbox/mapbox-gl-js#8234]
**mapbox-gl-js version**: 0.54.0

### Question
What's the best way to disable touch events on a symbol's text-field once it's faded out? Not sure if this is a bug report, feature request or just a plain ol' question 😄 

#### Situation:
You have a symbol with a text-field. You want to hide the text-field when you're zoomed out past some level.

So you use an exponential function on the `text-opacity` paint property:
```
'text-opacity': { type: 'exponential', stops: [[5,0], [6,1]] }
```
Now it fades out when moving from zoom level 6->5. Awesome.

Now you decide to do something on `mouseenter` of the symbol, e.g show a popup. When the label's visible, all is good – `mouseenter` fires when hovering both the icon and the text.

However, when you zoom out past level 5 and the label is invisible, hovering the space it once used to occupy still triggers the `mouseenter` event.

#### Possible solutions
- work around the issue by setting the `text-field` layout property to empty string based on zoom:
```
'text-field': { type: 'interval', stops: [[0, ''], [5, 'your label here']] }`
```
- mapbox-gl-js stops registering mouse events on anything with opacity = 0
- mapbox-gl-js adds "visibility" boolean properties to text, icon etc, which can then use an interval function

**Comment by peterqliu** [comment]
the `text-field` and `visibility` layout properties should work well, but doesn't afford you the fade transition, if it's important.

if this is just a one-off situation, the easiest is to `map.getZoom()` on the `mouseenter` event and ignore the event if you're at a zoom where the label should be invisible.

**Comment by mklopets** [comment]
@peterqliu thanks for the suggestions. Is there a way to tell based on the event if it was fired on an `icon-image` or `text-field`? In my case, below some zoom level, the label becomes invisible but the icon stays – so I can't disregard the events at that zoom altogether.

The fade transition is handled by the `text-field` interval solution – the fade is first done by the exponential `text-opacity` function and once that hits 0, the `text-field` is immediately unset. Still, this feels hacky.

**Comment by peterqliu** [comment]
>Is there a way to tell based on the event if it was fired on an icon-image or text-field

No, unless they're on separate symbol layers

**Comment by mourner** [comment]
I think we shouldn't change the behavior here — there are other use cases that depend on layers being interactive with opacity: 0. It is an intentional convention to have zero-opacity layers interactive, and zero-visibility non-interactive.
