### ISSUE TITLE
is it possible to query collided features at some point?

### ISSUE THREAD

**Issue by cs09g** [mapbox/mapbox-gl-js#8235]
### Question
`queryRenderedFeatures` quries rendered features only which is literally visible on the map. If there's method like `queryFeaturesAt` or `queryCollidedFeaturesAt`, then we can find out which features are covered by one feature, so we may apply this for clustering symbol functionality.

`showCollisionBoxes=true` displays collision boxes so I guessed there's some way to get information about the each box as well but unfortunately could find it yet.

**Comment by mourner** [comment]
> so we may apply this for clustering symbol functionality

Can you expand more on what you want to achieve so we could understand the use case better?

**Comment by cs09g** [comment]
We cluster things to represent more important one or to represent less items on the map. Clustered items can be extra data from server(e.g. weather icons) and also **POI symbols on map itself**.
This is about the clustering POIs on map itself without any extra data.
1. When some building has lots of points at the same coordinates, we're not able to see less-important points below the most-important point.
2. What if we want to serve more information(POIs) for specified coordinates to give users better UX powered by vector map? When it's image tiles, we had to zoom in to get more information but it's vector tiles.(We can set style `text-allow-overlap:true` for layer but then there would be too many features displaying.)

**Comment by mourner** [comment]
Sorry for a late response — we don't plan to introduce any new APIs related to this at the moment, but you can usually work around this by using `querySourceFeatures` and then filtering the results manually against the current pointer position.
