### ISSUE TITLE
Mapbox GL JS layer animation low fps

### ISSUE THREAD

**Issue by ArturGasparyan** [mapbox/mapbox-gl-js#8237]
I use the following Javascript code to animate a radar layer on my map:

```javascript
function updateLayer() {

	window.requestAnimationFrame(updateLayer);	   
	   
	var now = Date.now();
	elapsed = now - then;	   

	if (elapsed > fpsInterval) {
        //fpsInterval being 1000 / 10 or 1000 / 60
		then = now - (elapsed % fpsInterval);
			
		updateLayerImage();

   	}

}
```

updateLayerImage() cycles through the radar images of the last 3 hours at 5 minute steps.

However this results in an extremely slow animation (around 1-2 fps). Here are the things I did:

 - Since I'm loading radar images directly from an official weather source, each image being around 500 KB to 3 MB, I figured that this might be a bottleneck when loading them 60 times per second. So I wrote an independent script which caches the radar images of the last 3 hours on my own server, which provides a faster connection. Resulted in only little improvement.
 - I changed that cache code to additionally compress the images to around 300 KB each, which should make it faster, but didn't help much.
 - I'm not an expert in Javascript and wasn't sure how to "cache" images inside the client's browser, so I do the following: Once an image is downloaded I add it as a simple (hidden) img src="" id="" tag. Once my updateLayerImage() cycled back to the same image I do not load it again from my server but actually reuse the image.
 - Mapbox GL JS doesn't support, however, updating the image of an image source but only its url which makes it download it again. So I downloaded the Mapbox GL JS code and changed the image source file to have a function taking an HTMLImageElement as a parameter and assigning it to the source without downloading anything. Yarn installed the code and embedded my own Mapbox GL JS file and there you go, no network connections happen after all the images have been loaded into the HTML page. Still not actually faster.

I'm out of ideas, since I have relatively small images, I do not load them from the internet more than once and reuse them. But still my fps is very low. I'm beginning to think that it's a limitation of Mapbox GL JS...

How to improve my fps?

**Edit:**
Measuring performance time of `updateLayerImage()` results in varying durations of 45 ms to under 2 ms! Inside `updateLayerImage()` I call Mapbox GL JS's functions inside the image_source.js file which fires a `dataloading` event, I assign my new image to its image variable and then I call _finishLoadinig() which fires a `data` event. Some of this image rendering magic - I think - takes a lot of time. Any way to simply reassign the image variable and trigger a simple re-draw?

**Comment by ryanhamley** [comment]
Have you seen [this example of animating images](https://docs.mapbox.com/mapbox-gl-js/example/animate-images/)? You shouldn't need to manually call `requestAnimationFrame` since GL JS internally syncs animation to `window.requestAnimationFrame`.

**Comment by ArturGasparyan** [comment]
Thank you, yes, of course I’ve seen it. But isn’t window.requestAnimationFrame a better replacement for setInterval? I switched to it because my start with setInterval resulted in comparably low fps...

**Comment by peterqliu** [comment]
The ideal way to do this is preparing the images into a video on the backend, and adding it as such https://docs.mapbox.com/mapbox-gl-js/example/video-on-a-map/

**Comment by ArturGasparyan** [comment]
I thought about this, however I would like to be able to scrub forward and backward in my timeline. Do you think this would be easier with a video and mapbox than with images?

**Comment by ArturGasparyan** [comment]
@peterqliu I tried the setInterval() solution again. As with everything I tried before, I get Safari's "safari this page is using significant memory" warning at the top and, again, around 1-2 fps.

Regarding the video solution: How could I control that video? As in, allow the user to travel in time. I'm showing a map with a radar overlay and I would like the user to scrub backwards and forwards to see how the rain is moving...

Your example shows only a video which is added and played back in a loop.

**Comment by peterqliu** [comment]
@ArturGasparyan you're correct that there's no way to add video controls. can you make a live example of what you're doing with the setInterval images?

also as a side note,

>Mapbox GL JS doesn't support, however, updating the image of an image source but only its url which makes it download it again

if you're requesting an image that has been downloaded in the past, the browser should be able to get it from the cache to avoid a re-download

**Comment by ArturGasparyan** [comment]
@peterqliu

I will try to create an example in a few days. 

Regarding the image source: I added the functionality to load from image source instead of url myself.

And no, it does not reuse the cached images automatically, I checked.

**Comment by peterqliu** [comment]
>And no, it does not reuse the cached images automatically, I checked.

@ArturGasparyan it may depend on your browser's cache settings

<img width="1281" alt="Screen Shot 2019-05-16 at 11 52 54 AM" src="https://user-images.githubusercontent.com/4551508/57879445-5c2f8880-77d1-11e9-9b45-15edd1566853.png">



Also, if you go down the video route, turns out you *can* control it by accessing the element through `map.getSource("<your video source name>)").video`, and then using the HTML5 video's `currentTime` setter. We might add convenience methods to make this more explicit.

**Comment by ArturGasparyan** [comment]
@peterqliu 

Thanks for coming back to me, I will try changing the cache settings, I somehow didn’t manage to use the cache. No matter what I try it’s really really slow and I can’t believe it’s that hard. Will come back on this one.

**Comment by ArturGasparyan** [comment]
The issue at hand is this: Using images with a resolution of 2048x2048 results in 60 fps whilst using images with a resolution of 8192x8192 (my intended resolution) with the **same size in KB** results in 2 fps with frame drops and a CPU load of around 100 %.

**Comment by asheemmamoowala** [comment]
> with the same size in KB 

Even though the file size is the same, the size of the texture, after decoding is going to be much larger. This affects performance as the time to transfer texture data to the GPU is exponentially larger with the larger image size.
