### ISSUE TITLE
Hide or disable controls instead of remove

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#8239]
Currently there's just `onRemove` method which completely removed the control for the map. Would be good to be able to `hide` and/or `disable` controls as well. 

One use case is switching between view and edit modes when using Mapbox Draw. When in draw mode, most of the controls in the 'view' mode are not required on the map.

Of course, I could just hide the controls using CSS currently but not sure if thats the best way to do it.

**Comment by mourner** [comment]
Hiding with CSS is perfectly fine, as is `Map` `removeControl` — whatever you feel is more convenient.
