### ISSUE TITLE
The "change style" example in the Docs generates the following warning: Unable to perform style diff: Unimplemented: setSprite

### ISSUE THREAD

**Issue by ggrocca** [mapbox/mapbox-gl-js#8241]
This is just a warning, no broken functionality here. My wild guesses are that there's something wrong in the Docs example, or there's a spurious warning that needs to be fixed (third possibility: this warning is due to an open issue, but I see that issues #2058 and #2059 are closed). I'm totally new to mapbox though (just started to playing with APIs a few days ago, so apologies in advance if I'm missing something obvious).

Full warning:
```
Unable to perform style diff: Unimplemented: setSprite..  Rebuilding the style from scratch. (util.js:329)
```
**mapbox-gl-js version**: 0.54

**browser**: Chromium Version 75.0.3738.0 (Developer Build) (64-bit) MacOS

### Steps to Trigger Behavior and Link to Demonstration

- Go to https://docs.mapbox.com/mapbox-gl-js/example/setstyle/
- Open DevTools.
- Change style.
- See warning.

### Expected Behavior

No warning.

### Actual Behavior

There's a warning.

**Comment by mourner** [comment]
While the warning can be safely ignored, we're still interested in speeding up `setStyle` for cases like this, so let's reopen #2058.
