### ISSUE TITLE
Focused control button doesn't defer visually from non-focused

### ISSUE THREAD

**Issue by life777** [mapbox/mapbox-gl-js#8246]
**mapbox-gl-js version**: 0.54.0

**browser**: Chome 74 for Linux

### Steps to Trigger Behavior

If you have some controls on the map (like zoom controls) and you navigate to them with Tab button you can't distinguish what button is focused now. There are no styles for focused state on the buttons. There should be either outline (like on links in attributions control) or apply hover styles when button is focused.

 1. Open map with zoom control
 2. Navigate with Tab to any zoom button

### Link to Demonstration
Example with mapbox:
https://jsbin.com/qemokezepu/edit?html,output 

### Expected Behavior

Focused buttons should have different styles (or just outline) than non-focused.

### Actual Behavior

User can't distinguish what button he/she is currently focused on.

**Comment by andrewharvey** [comment]
I'm +1 to having a blue highlight around focused buttons, exactly like GitHub does, which seems to be best practice. Are you interested in putting together a PR?

**Comment by life777** [comment]
Yes, I would love to help you with this case during this week. Thanks.
