### ISSUE TITLE
Why the feature-state is not supported for layout.icon-image?

### ISSUE THREAD

**Issue by atsarego** [mapbox/mapbox-gl-js#8249]
Problem:
We have points which has 10 different states (each state has its own image) and these states must be switched quickly in response to user. 
The feature-state is a suitable feature to do it. But the feature-state is not supported for layout.icon-image.
To do that we decided to create 10 layers for each point state presentation. And we use feature-state in paint.icon-opacity to hide point states that are not active at current time. This aproach leads to performace issues in case of a big number of items.

So, I have two questions:

What is the reason why the feature-state is not supported for layout.icon-image? It seems to be helpfull.

What would you suggest for our case?

**Comment by asheemmamoowala** [comment]
> What is the reason why the feature-state is not supported for layout.icon-image?

The `feature-state` APIs were introduced to provide a performant way to make updated to specific identifiable features. The `layout` properties of a layer are more expensive to change, and that is why they are not supported with `feature-state` APIs as yet.


This issue tracker is for reporting bugs and feature requests. For future questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/).

**Comment by OmarSarhan** [comment]
What's the alternative approach to changing icons on features when clicked?

**Comment by wysisoft** [comment]
You can data drive icon-image and then use setdata to change the data that drives the icon. The performance of this will be pretty good for smaller data sets, and not good for larger ones
