### ISSUE TITLE
Rainviewer Source Possible?

### ISSUE THREAD

**Issue by weswitt** [mapbox/mapbox-gl-js#8252]
I think the answer is no, but asking just in case.

Is it possible to use radar image data from https://www.rainviewer.com/api.html ?

The data are served as tiles rendered as transparent PNG images. Requests are in the for of: https://tilecache.rainviewer.com/v2/radar/1557940200/256/{z}/{x}/{y}/2/0_0.png

Is it possible to make this work even though their not using any TileJSON ?

**Comment by weswitt** [comment]
Using the following code I can see in Firefox's network debugger the requests to the rainviewer server for the tiles just as expected. Good. The issue is that the rainviewer tile server expects the x & y values to be EPSG:3857, but they are not. It seems that if I can get mapbox to ask for EPSG:3857 coordinates it will work.  Is this possible?

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title></title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.25.1/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.25.1/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>

<div id='map'></div>
<script>
mapboxgl.accessToken = 'pk.eyJ1Ijoid2Vzd2l0dCIsImEiOiJjanZwaXFna28yM2gwM3lxbHdnbG05ZmE0In0.Y9ChPI860gDZPyGV-6TPmA';
var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/mapbox/streets-v9', //stylesheet location
    center: [-122.6793, 45.5155], // starting position
    zoom: 7 // starting zoom
});

map.on('load', function () {
        map.addSource('rainviewer', {
            "type": 'raster',
            "tiles": ['https://tilecache.rainviewer.com/v2/radar/1557937200/256/{z}/{x}/{y}/2/0_0.png'],
            "tileSize": 256
        });
        map.addLayer({
            "id": "radar-tiles",
            "type": "raster",
            "source": "rainviewer",
            "minzoom": 0,
            "maxzoom":22
        });
    });

</script>

</body>
</html>

**Comment by weswitt** [comment]
After more investigation is seems that the x&y values used by mapbox conform to the math described by the openstreetmap page below. Is this correct?

https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#X_and_Y

**Comment by asheemmamoowala** [comment]
The tile requests served from that API do not have an `Access-Control-Allow-Origin` header. You can use the `transformRequest` Map option to provide a method that adds the `no-cors` header to requests to that API.

**Comment by SebastianSmolorz** [comment]
This issue wasn't answered, can we please reopen? @weswitt Did you ever get this to work?

**Comment by asheemmamoowala** [comment]
I don't see any issues with rainviewer tiles when run on localhost: 
```
map.on('load', function() {
    map.addSource('rainviewer', {
        "type": "raster",
        "tiles": ['https://tilecache.rainviewer.com/v2/radar/1563472800/256/{z}/{x}/{y}/2/1_1.png'],
        "tileSize": 256
    });

    map.addLayer({
        "id": "rainviewer-test-layer",
        "type": "raster",
        "source": "rainviewer",
        "paint": {}
    });
});
```

**Comment by SebastianSmolorz** [comment]
Don't you need to specify coordinates?

**Comment by doyle-mark** [comment]
Did anyone ever manage to add a rainviewer layer? Personally I could never get it to work
