### ISSUE TITLE
Map zoom fires "movestart" many times, but "moveend" only once

### ISSUE THREAD

**Issue by bambielli-flex** [mapbox/mapbox-gl-js#8256]
I'm not sure if this is a bug, but it was unexpected behavior to me.

I'm attaching event listeners to `movestart` and `moveend`. 

I'm finding that while dragging / panning the map, the event listeners trigger when I would expect them to trigger (when user starts moving the map `movestart` fires, then when they release the map `moveend` fires) 

However while zooming it looks like `movestart` is firing many many times while `moveend` is still only firing once. 

This seems somewhat related to #6512, but with the zoom api instead of resize.

**mapbox-gl-js version**:
0.53.1
**browser**:
Chrome

### Steps to Trigger Behavior

 1. attach map.on('movestart', () =>{}) and map.on('moveend', () => {}) event listeners.
 2. zoom the map in or out.

### Link to Demonstration

https://jsfiddle.net/bambielli767/Lc5yutef/9/

### Expected Behavior

`movestart` and `moveend` are both triggered once, when zooming starts and when zooming finishes.

### Actual Behavior

`movestart` is triggered many many times, while `moveend` is still only triggered once.

**Comment by mourner** [comment]
This definitely looks like a bug. Thanks for the report! Might have regressed in recent versions.

**Comment by bambielli-flex** [comment]
No prob. If you think the fix is simple enough for a first timer of the project, I'd be happy to look in to it.

**Comment by ryanhamley** [comment]
This doesn't appear to be a recent regression. I tested back to v0.35.0 and observed this behavior. 

The event is being fired [here](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/handler/scroll_zoom.js#L219). `zoomstart` and `zoomend` exhibit the same behavior. `movestart` and `zoomstart` are duplicating the `move` and `zoom` events. I'm not sure the best way to fix this off the top of my head, but `marker.js` uses an [internal state to track whether or not a `dragstart` or `drag` event should be fired](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/marker.js#L384-L408) so something like that might work well for this.

**Comment by bambielli-flex** [comment]
I'll take a look!

**Comment by mourner** [comment]
@ryanhamley it definitely used to work before. So far I traced this back to somewhere between v0.14 (working fine) and v0.15 (buggy). Which apparently means this is the first known occurrence of someone depending on that event in 3+ years 😆

**Comment by Eh2406** [comment]
@mourner I did not realize this was a bug and just filtered it out in my code.

**Comment by vpmammana** [comment]
I am observing this only on the real android. When I test it on a desktop webbrowser emulating an android, the problem doesn't show up. The problem is intermitent. Some times zoom triggers moveend, sometime it doesn't.
