### ISSUE TITLE
Update docs with current CSP script-src requirement

### ISSUE THREAD

**Issue by skylarweaver** [mapbox/mapbox-gl-js#8265]
I'm trying to setup my CSP to work with mapbox, and it appears the [Mapbox documentation](https://docs.mapbox.com/help/troubleshooting/how-to-use-mapbox-securely/#csp-directives) urges one to make a CSP more vulnerable than it needs to be.

The documentation indicates to add `script-src 'unsafe-eval' ;` to one's csp, but if I am understanding [this version update](https://github.com/mapbox/mapbox-gl-js/blob/master/CHANGELOG.md#0440) correctly, it seems that 'unsafe-eval' is no longer required, which is great news for security.

It would be great if we could update the documentation here if that is true: https://docs.mapbox.com/help/troubleshooting/how-to-use-mapbox-securely/#csp-directives

**Comment by ryanhamley** [comment]
Hi @skylarweaver you are correct about `unsafe-eval` no longer being required. The issue with the docs is being tracked in https://github.com/mapbox/mapbox-gl-js/issues/6892 Thanks!

**Comment by mourner** [comment]
@skylarweaver note that it's still required for the default build; using Mapbox GL JS without `unsafe-eval` requires using a special build, as documented here: https://docs.mapbox.com/mapbox-gl-js/overview/#csp-directives
