### ISSUE TITLE
Add a more intuitive syntax for line opacity gradients

### ISSUE THREAD

**Issue by mzdraper** [mapbox/mapbox-gl-js#8270]
## Motivation

Create maps with smooth opacity transitions to represent something like road popularity/density.

![image](https://user-images.githubusercontent.com/25856619/58118064-f1a59080-7bb4-11e9-94e1-471ba97f0cf9.png)
![image](https://user-images.githubusercontent.com/25856619/58118164-2285c580-7bb5-11e9-9d8e-351272daafb6.png)

### Mock-Up

To developers, it'd be used the same way in `line-gradient`:

```
'line-opacity': [
    'interpolate',
    ['linear'], 
    ['line-progress'],
      0, .2,
      1, 1
]
```

**Comment by mourner** [comment]
This is already possible by using the alpha component of colors in `line-gradient` expression:

```js
'line-gradient': [
    'interpolate',
    ['linear'], 
    ['line-progress'],
    0, "rgba(0, 0, 255, 0.2)",
    1,  "rgba(0, 0, 255, 1)"
]
```

I'm not sure we want to introduce an alternative syntax for that because of the increased complexity, but the current way to do that isn't obvious — let's discuss.

**Comment by mzdraper** [comment]
This works! I think adding an example on the [examples page](https://docs.mapbox.com/mapbox-gl-js/examples/) would sufficient.

**Comment by asheemmamoowala** [comment]
Closing this as this already possible.
