### ISSUE TITLE
Data-driven-styling for image in fill-pattern

### ISSUE THREAD

**Issue by noam-zweig** [mapbox/mapbox-gl-js#8285]
## Motivation

I want to show a layer on the map, with different polygons, that the fill image of each polygon is taken from different sources, that are dynamic (images are changes, and image urls are changing).

## Design Suggestion
I want to load vector tiles, where the fill-pattern of the different polygons in the tile, is taken from images. The images are decided in the server side, and can be changed on the fly.

I wanted to use the combination of vector tiles, and data-driven-style, where in the server side, I'll create vector tiles. 
Every vector tile will have a separate feature per polygon, and one of the properties will hold the image-url (or something like that).
In the client side it will look like this:

```javascript
mapStyle={{
    sources: {
        'data': {
            type: 'vector',
            tiles: ['https://<url>/tiles/{z}/{x}/{y}.vector.pbf'],
        },
    },
    layers: [
        {
            id: 'l-pattern',
            source: 'data',
            type: 'fill',
            'source-layer': 'dataLayer',
            paint: {
                'fill-pattern': ['get', 'url'],
            },
        },
    ],
}}
```

The problem is, that the "fill-patter" property supports only sprites.
And sprites are not an option here (not dynamic. Only small pictures. Not refreshed enough).

**Comment by asheemmamoowala** [comment]
> The problem is, that the "fill-patter" property supports only sprites.

The `fill-pattern` property already supports data-driven styling, and can use images added by name prior to the setting the paint property, in addition to sprite-based images. You can do this using `map#loadImage` and `map#addImage` as shown in this [example](https://docs.mapbox.com/mapbox-gl-js/example/fill-pattern/).
