### ISSUE TITLE
Plygon with multiple holes 

### ISSUE THREAD

**Issue by sanket1411** [mapbox/mapbox-gl-js#8286]
**mapbox-gl-js version**:

### Question
How to I display multipolygon or polygon with multiple  holes,according to your documentation the outer most ring should be at start of geometry followed by inner most rings,and the fill will be applied in even-odd fashion.I think my geometry is upto your standard but mapbox is not rendering it.

example of polygon with multiple nested inner holes
https://jsfiddle.net/h3fyL9oj/1/

http://geojson.io can render this feature
 
If there is a geometry correction for feature please point out so.

Is Winding order of geometry to be considered(given in vector tile specs) or it is only related to vector tile specification.

**Comment by mourner** [comment]
The vector tile specification doesn't have a concept of "nested inner holes". What you have in practice here is three different polygons — one big one with a hole, and two additional small ones. Currently it's not technically possible to render the GeoJSON above with GL JS — see a related issue #7023 for some details.
