### ISSUE TITLE
removeFeatureState doesn't handle id '0'

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-js#8293]
Moving forward from [#7632(comment)](https://github.com/mapbox/mapbox-gl-js/issues/7632#issuecomment-494985798)

> Looking at removeFeatureState function in the SourceFeatureState class, it does use the number feature id, but the if statements would fail if the id is 0. Lines 65, 70. Will need to test this to verify.

https://github.com/mapbox/mapbox-gl-js/blob/a67c21368ad363ae48fece3cf8937327dbdfe172/src/source/source_state.js#L61-L70

**Comment by peterqliu** [comment]
@asheemmamoowala that was by design 🤔  _should_ it handle zero? or negative values, or even strings as the ticket suggests?

**Comment by asheemmamoowala** [comment]
It need to handle `0` because that is a valid feature id. A string 0 can be cooerced to a number and will be handled before it gets to the `SourceState#removeFeatureState` method.

**Comment by peterqliu** [comment]
🚢
