### ISSUE TITLE
Data-driven styles - Case and Other functions

### ISSUE THREAD

**Issue by apresmoi** [mapbox/mapbox-gl-js#8294]
**mapbox-gl-js version**: latest

### Question

Hello ! 

I wonder if there is a way to combine this:
```
"line-color": {
  property: 'prop',
  type: 'categorical',
  stops: [
    ['0x06', '#2C9DF1'],
    ['0x05', '#223b53'],
  ]
}
```
with the "case" expression.

I need something like this:
```
"line-color": {
   'case',
  ['boolean', ['feature-state', 'hover'], false], 'red',
  {
    property: 'prop',
    type: 'categorical',
    stops: [
      ['0x06', '#2C9DF1'],
      ['0x05', '#223b53'],
    ]
  }
}
```

Thanks in advance!

**Comment by mourner** [comment]
The equivalent of legacy categorical functions in the new expression system is `match`: https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-match

**Comment by apresmoi** [comment]
Thanks a lot @mourner it suits my problem perfectly.

I leave the correct way to do it if anyone is interested.
```
"line-color": {
   'case',
  ['boolean', ['feature-state', 'hover'], false], 'red',
  ['match',
    ['get', 'prop'],
    '0x06', '#2C9DF1',
    '0x05', '#223b53',
    'transparent'
  ]
}
```
