### ISSUE TITLE
Does addImage save the image to style permanently?

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#8301]
I've been using `addImage` (https://docs.mapbox.com/mapbox-gl-js/api/#map#addimage) to add symbols to one of the default styles (`mapbox://styles/mapbox/streets-v9`).

I wonder if the added images are saved permanently to the sprite or is it just for the session? If stored permanently, where can I view/edit/remove them?

Thanks!

**Comment by ryanhamley** [comment]
They are not permanently added to the sprite. `addImage` is per session
