### ISSUE TITLE
Decreasing intensity of a Vector Layer Tileset.

### ISSUE THREAD

**Issue by shashankpandey2012** [mapbox/mapbox-gl-js#8313]
I want to know how to decrease light intensity of a Vector Layer without decreasing its intensity. Is it possible to decrease the light intensity of layer and layover another layer on it to highlight some function

**Comment by peterqliu** [comment]
@shashankpandey2012 can you say more about the difference between *intensity* and *light intensity*?

**Comment by ryanhamley** [comment]
Hi @shashankpandey2012 I'm not sure I understand exactly what you're trying to achieve. You can adjust the light intensity for the entire scene with a [`Light` object](https://docs.mapbox.com/mapbox-gl-js/style-spec/#root-light) (either as part of your style spec or by calling `map.setLight`).

But I think perhaps you're asking for something like [opacity](https://docs.mapbox.com/mapbox-gl-js/example/adjust-layer-opacity/)? Opacity can be set on layers such as fill, line, circle and raster, but it's not possible to adjust the opacity of the vector tiles.

**Comment by shashankpandey2012** [comment]
@ryanhamley @peterqliu  I am working with polygons filled with different colors. If I select a Feature Polygon , I just want to highlight the selected feature without decreasing opacity of other features or map. How can I do that ?

**Comment by peterqliu** [comment]
>highlight the selected feature without decreasing opacity of other features

@shashankpandey2012 this is the default behavior -- opacities of other features don't change unless you change them.
