### ISSUE TITLE
SVG symbols using addImage

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#8320]
Since `addImage` accepts `HTMLImageElement`, `ImageData` (or an object that mimics `ImageData`) so I tried to do this:

```
<img src="/path/to/image.svg" width="50" height="70" />
map.addImage("cat", document.querySelector("img"));
```

.. but it doesn't seem to add the image. So I'm wondering if SVG is supported?

I don't understand how someone [got it to work](https://github.com/mapbox/mapbox-gl-js/issues/5529) before without converting it to a raster image, or maybe their example is incomplete?

**Comment by mourner** [comment]
Can you set up a full example you're expecting to work (e.g. with JSFiddle)?

**Comment by 3zzy** [comment]
@mourner Sure, https://jsfiddle.net/pc983uez/

**Comment by mourner** [comment]
This one works — I added `crossOrigin="Anonymous"` to image attributes. https://jsfiddle.net/Mourner/6vxm0roc/

**Comment by 3zzy** [comment]
@mourner Turns out it doesn't work in IE11:
[Imgur](https://i.imgur.com/9kvBSI0.png)

I really hope there's a fix or a workaround for this. :(

**Comment by 3zzy** [comment]
@mourner My bad, I was missing `img.crossOrigin = 'Anonymous';` that got rid of the error but it still doesn't render. Confirmed with your fiddle:

![IE11 SVG Test](https://i.imgur.com/SNLGGwo.png)

**Comment by 3zzy** [comment]
@mourner So turns out this happens only in IE11 cause it "taints" the canvas, the only workaround is to convert the SVG to PNG before drawing it on the canvas. In other words, SVG can't be drawn on canvas without a SecurityError in IE11.
