### ISSUE TITLE
Graticule label placement at the edge of view area

### ISSUE THREAD

**Issue by bibeksh9** [mapbox/mapbox-gl-js#8322]
The requirement is this example,
https://github.com/Leaflet/Leaflet.Graticule
Currently, I'm using two layers one for the lines and another symbol layer to show the labels.
But there is no option to put it on the edge always.

**Comment by ryanhamley** [comment]
Hi @bibeksh9 graticules are not something we plan to support at this time. I'm not sure what you mean by "put it on the edge always". Can you use JSBin or something similar to create an example of what you're trying to achieve?

**Comment by bibeksh9** [comment]
You can observe in the image that latitude and longitude display values are visible on the edge of the map.
![image](https://user-images.githubusercontent.com/14129440/58988952-72dd6400-8800-11e9-8587-7254ba3bef0b.png)

**Comment by ryanhamley** [comment]
This is something you'll have to implement yourself. Looking at the Leaflet plugin you linked to shows that it's overlaying a canvas on the map which seems like a reasonable solution. You can use a [canvas source](https://docs.mapbox.com/mapbox-gl-js/api/#canvassource) to achieve this which should make it easier to position the labels at the edge of the screen/canvas at all times.
