### ISSUE TITLE
How to remove a poi label from the map based on its type (e.g: 'Restaurant')? [codesandBox]

### ISSUE THREAD

**Issue by ReactGirl** [mapbox/mapbox-gl-js#8323]
Hi.

I'm trying to remove from the map just the label with the type of restaurant.

I could remove all labels using the following code:

```javascript
this.map.on("load", () => {
      this.map.style.stylesheet.layers.forEach(layer => {
        if (layer.id === "poi-label") {
          // How can I execute this only for poi-label which is Restaurant?
          this.map.removeLayer(layer.id);
        }
      });
    });
```
However this will remove all the pois, not only restaurant. 
I also could have a helper to get the restaurants from **this.map.queryRenderedFeatures()**, but not sure if this might be useful.

Please see my codesandbox:
[codeSandBox](https://codesandbox.io/s/mapboxdatalayer-f1hdw)

**Comment by mourner** [comment]
I think the easiest way to hide a particular feature in a layer is to use `map.setFeatureState` in combination with a `visibility` expression that depends on `feature-state`. In the following example, feature state is used for hover effect, but this could be adapted to your use case: https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/

**Comment by scherroman** [comment]
To exclude a category of points of interest using code, you can use the [`map.setFilter`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#setfilter) function:

```
map.setFilter('poi-label', ['!=', 'category_en', 'Restaurant'])
```

To do it in Mapbox Studio:

Eject the "Points of interest labels" component by selecting it under the "Components" tab then clicking the eject button -> Add a filter to the 'poi-label' layer by selecting it under the "Layers" tab, clicking the "Select Data" tab in the top right of the layer panel -> selecting the "Filter" tab -> clicking "Add another condition" -> Selecting the "category_en" data field -> Selecting the "is not" condition -> Selecting "Restaurant" as the value.
