### ISSUE TITLE
Add heading to GeolocateControl

### ISSUE THREAD

**Issue by Plantain** [mapbox/mapbox-gl-js#8329]
## Motivation
Navigating yourself from a map with only position is difficult, showing a direction indicator or compass heading makes it much easier. Most modern mobile devices have a compass built in. Google Maps supports it.

## Design
  map.addControl(new mapboxgl.GeolocateControl({
        positionOptions: {
                  enableHighAccuracy: true
              },
        fitBoundsOptions: {
          maxZoom:7,
        },
        trackUserLocation: true
        trackUserHeading: true <----
  }), 'bottom-left');

### Mock-Up
Example from Google Maps, see the direction arrow pointing out of the blue dot.
![xbZ8a](https://user-images.githubusercontent.com/319895/59103596-9521cf80-892f-11e9-8239-bb0e628db1bb.png)

**Comment by andrewharvey** [comment]
@Plantain Do you have a good summary of the browser support for this? My understanding is browser support is not standardised and patchy.

Need absolute compass, not just relative bearing (it seems some browsers may only support the latter?).

**Comment by andrewharvey** [comment]
See also some background at #3781, the original design was to include the bearing.

**Comment by Plantain** [comment]
My understanding is it works on FF/Chrome via DeviceOrientation (it does require the users compass to already be calibrated), and it works on Safari via webkitCompassHeading.

**Comment by andrewharvey** [comment]
> My understanding is it works on FF/Chrome via DeviceOrientation (it does require the users compass to already be calibrated), and it works on Safari via webkitCompassHeading.

Yeah I was just reading up on this now. It's not standard across browsers, but looks like we can support on Chrome and Safari separately.

I'd been keen to help review a PR which implemented this if you wanted to have a go.

**Comment by douglasg14b** [comment]
@tsuz Has this been released? I'm noticing this doesn't work, neither on a phone, or when using Chrome's devtools sensors.

**Comment by douglasg14b** [comment]
After some debugging it looks like this may be the problem:

js
```
        const addListener = () => {
            if ('ondeviceorientationabsolute' in window) {
                window.addEventListener('deviceorientationabsolute', this._onDeviceOrientationListener);
            } else {
                window.addEventListener('deviceorientation', this._onDeviceOrientationListener);
            }
        };
```

`deviceorientationabsolute` seems to only fire once, but `deviceorientation` fires whenever the orientation changes.
