### ISSUE TITLE
callback for fetch/xhr

### ISSUE THREAD

**Issue by martinlierschof** [mapbox/mapbox-gl-js#8330]
## Motivation
Currently there is only a function to add headers to fetch/xhr but it would be nice to be able to deal with your own implementation or axios. There would be lots of use cases like serving from own cache (localforage) etc..

## Design Alternatives
There is no known alternative to this right now

## Design

it would be really simple, just add another value (function) to the object returned by requestTransform like "fetchCallback" and "xhrCallback". This method is called instead of "self.fetch" or "xhr" in the respective functions, the user just needs to be able to provide the response in the same format as fetch or xhr (as a promise). Also then you dont need to deal with the whole ajaxError class etc.. in the callback.

### Mock-Up
    var fetcher = self.fetch;
    if(requestParameters.fetchCallback){
      fetcher = requestParameters.fetchCallback;
    }
    fetcher(request).then(function (response) {
    ....
### Concepts
The mockup shows that as log as the response corresponds to the self.fetch we should be ok, so the user can decide how the data is returned.
i dont know if this is the best implementation, but in our case we have our own handling of requests via axios which patches some headers and serves from cache.
Also it would allow to deal with broken xhr/fetch implementations for users who would need to wait otherwise for a patch of mapbox-gl-js.

### Implementation
i dont know the C++ code but iam guessing this is not part of it and the mockup shows the implementation

**Comment by asheemmamoowala** [comment]
@martinlierschof  Thank you for this request. The library calls `fetch` from WebWorker's as well, which would require that the callback either be made available to the workers, or that workers have to roundtrip every fetch request to the main thread.

In your proposal, you say :

> There would be lots of use cases like serving from own cache (localforage) etc..

Can you provide more details on what exactly you are trying to do with the ability to provide your own fetch implementation?

**Comment by asheemmamoowala** [comment]
Closing this as inactive for now. @martinlierschof feel free to re-open when you have a chance to provide the requested information: 

> Can you provide more details on what exactly you are trying to do with the ability to provide your own fetch implementation?

With the release of v1.1, gl-js uses the [Cache API (MDN)](https://developer.mozilla.org/en-US/docs/Web/API/Cache) to cache mapbox tiles. Other resources are cached by the browser automatically.
