### ISSUE TITLE
Raster layer pixelation instead of blur in overzoom 

### ISSUE THREAD

**Issue by noam-zweig** [mapbox/mapbox-gl-js#8334]
**mapbox-gl-js version**:

### Question
I'm showing layers of information on the map. In my case - weather layers.
The weather is accurate to some level (for the example - let's say 1km x 1km).
This means, that from zoom level ~7 and higher, there is no meaning to bring the data again from the tile server, as a single pixel is less than 1km x 1km.

So I used the maxzoom=7 of a source.
The issue now, is that when zooming to a higher level than 7, it shows a blur picture.
I would want to show pixelated picture (as each pixel represents data).

How can I do it?

### Links to related documentation

I tried to use the "antialias" (as mentioned here - https://docs.mapbox.com/mapbox-gl-js/api/) and it didn't change anything.
I also saw that there is a way to tell the context "imageSmoothingEnabled=false" - but I didn't find how can I use it.

**Comment by andrewharvey** [comment]
On your raster layer you can set `raster-resampling` to `nearest` https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-raster-raster-resampling.

**Comment by noam-zweig** [comment]
Great. Thanks for the answer.
I'll take a look on it!
