### ISSUE TITLE
`map.removeFeatureState()` is not a function

### ISSUE THREAD

**Issue by flawyte** [mapbox/mapbox-gl-js#8338]
Is it me or `Map#removeFeatureState` was removed? Because it's still in the [docs](https://docs.mapbox.com/mapbox-gl-js/api/#map#removefeaturestate) but when I try to use it I get `Uncaught TypeError: map.removeFeatureState is not a function`.

**mapbox-gl-js version**: 0.52.0

**browser**: Chrome 74

**Comment by mourner** [comment]
`removeFeatureState` was added in v0.53.0.
