### ISSUE TITLE
fill-extrusion can't display normally：  bug 🐞

### ISSUE THREAD

**Issue by Zhouyuj** [mapbox/mapbox-gl-js#8341]
**mapbox-gl-js version**: 1.0.0

**browser**: Google Chrome LatestVersion

### Steps to Trigger Behavior
Hi, I'm developing an website using mapboxgl-js. I add some fill-extrusion layers in Mapbox Studio in order to test 3D function, while the layers didn't display well, as we can see below, the district where red arrow pointed was empty
![image](https://user-images.githubusercontent.com/9909141/59338891-c89c9980-8d35-11e9-895a-e4aa05871457.png)

but this layers in Mapbox Studio can well display
![image](https://user-images.githubusercontent.com/9909141/59339151-38128900-8d36-11e9-8f5a-b98a237834ab.png)

the layer property was same :
     fill-extrusion-color: c7c7c7;
     fill-extrusion-height: ['interpolate', ['linear'],['zoom'], 19, 0 ,22, 1.5]
     fill-extrusion-pattern: 'default' // this just make sure it looks more clear

I want my website's 3D function goes well just like goes in Mapbox Studio. can anyone help me? thx a lot.

**Comment by mourner** [comment]
Can you show a minimal reproducible test case (e.g. with JSFiddle)? This kind of artifact usually means the input polygons are not valid polygons according to the vector tile specification (winding order of polygon rings is wrong).
