### ISSUE TITLE
Scale-up of all buildings on the Layer

### ISSUE THREAD

**Issue by Niumeng1** [mapbox/mapbox-gl-js#8342]
**mapbox-gl-js version**:0.52

### Question
hello,
How can we scale each building in a layer with the same scale?
Instead of fixing only one value.
step0:
![image](https://user-images.githubusercontent.com/21193895/59343451-8166d680-8d3e-11e9-8f5c-67d4fb480558.png)

step1: 
![image](https://user-images.githubusercontent.com/21193895/59343101-ae66b980-8d3d-11e9-82ed-b79ffd04c0a4.png)

step2:
```
   map.setPaintProperty('3d-buildings', 'fill-extrusion-height',1500).setPaintProperty('3d-buildings','fill-extrusion-color','#FFFFFF')
```
step3:
![image](https://user-images.githubusercontent.com/21193895/59343143-c2122000-8d3d-11e9-900f-d1d276c8c9e8.png)

**Comment by mourner** [comment]
You would use an expression:

```js
 map.setPaintProperty('3d-buildings', 'fill-extrusion-height', ['*', ['get', 'height'], 5]);
// set building height to 5 times the `height` property value
```
