### ISSUE TITLE
Not a valid GeoJSON object on version > 0.51 when add an empty coordinates array

### ISSUE THREAD

**Issue by cantacell** [mapbox/mapbox-gl-js#8343]
Creating a layer with an empty coordinates array will report an error 'Input data is not a valid GeoJSON object' only on versions > 0.51.
Code: 
map.addLayer({
              'id': 'draw_layer',
              'type': 'fill',
              'source': {
                'type': 'geojson',
                'data': {
                  'type': 'Feature',
                  'geometry': {
                    'type': 'GeometryCollection',
                    'geometries': [{
                        'type': 'Polygon',
                        'coordinates': []
                      }]
                  }
                }
              },

Jsfiddle for version 0.51: https://jsfiddle.net/3yeogx9n/1/
Jsfiddle for version 1.0.0: https://jsfiddle.net/3yeogx9n/

For versions > 0.51 the correct code must be:
 ....   'type': 'Feature',
        'geometry': {
          'type': 'GeometryCollection',
          'geometries': []
        }

Is it correct?
Thanks.

**Comment by stevage** [comment]
That's not a valid GeoJSON object, as the `Feature` object lacks a `properties` member. You can test this at geojsonlint.com.

**Comment by mourner** [comment]
Yes, geometries with an empty coordinates array are invalid GeoJSON.

**Comment by stevage** [comment]
That's not strictly true according to [the spec](http://geojson.win/). It actually doesn't state any requirement about the length of the coordinates array for Polygon objects, but it does also state:

> GeoJSON processors MAY interpret Geometry objects with empty "coordinates" arrays as null objects. 

I don't see anything to suggest that a Polygon with a zero-length coordinates array is invalid.

(The more you look at the GeoJSON spec, the weirder it becomes.)

**Comment by Ranjan-choudhary** [comment]
But this is my valid geojson data still its giving  error Input data is not a valid GeoJSON object
my code is here

mapboxgl.accessToken = 'pk.eyJ1IjoibHVjYXN3b2oiLCJhIjoiNWtUX3JhdyJ9.WtCTtw6n20XV2DwwJHkGqQ';
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9'
});

map.on('load', function () {
            map.addSource('national-park', {
                'type': 'geojson',
                'data': "{
            "type": "FeatureCollection",
            "features": [
                {
                "type": "Feature",
                "properties": {
                    "class_id": "1"
                },
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                        [
                        [73.30557373837911, 30.103124977028912],
                        [75.18588382556533, 23.078333889589615],
                        [84.75837154215725, 26.031952363658277],
                        [78.26275487732727, 30.937550343177648],
                        [73.30557373837911, 30.103124977028912]
                        ]
                    ]
                }
            }]
        }"
            });
            map.addLayer({
                'id': 'maine1',
                'type': 'fill',
                'source': 'national-park',
                'layout': {},
                'paint': {
                    'fill-color': 'blue',
                    'fill-opacity': 0.8
                }
            });
        });

**Comment by stevage** [comment]
There's something wrong with the code you've included, that's not valid JavaScript. You have some extra double quotes around your GeoJSON object at least.

**Comment by princedacy** [comment]
@Ranjan-choudhary did you get to fix that error even though the geoJSON is valid?
