### ISSUE TITLE
Default value for `text-variable-anchor`

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#8344]
## Motivation

Currently, there isn't a [default value for `text-variable-anchor`](https://github.com/mapbox/mapbox-gl-js/blob/5b415130e75561f6e0cfd6f652359b2e3a417bc1/src/style-spec/reference/v8.json#L1817-L1884) making it all or nothing. There's no way to write an expression that enables this label treatment at high zooms and disables it at low zooms.

## Design Alternatives

Enable some sort of `false` default value

## Design

```js
{
  id: 'poi-label',
  type: 'symbol',
  source: 'mapbox-streets',
  'source-layer': 'poi_label',
  layout: {
    'text-size': 12.5,
    'text-field': ['get', 'name'],
    'text-justify': 'auto',
    'text-radial-offset': ['step', ['zoom'], 0 15, 10],
    'text-variable-anchor': [
      'step',
      ['zoom'],
      false, // Hypothetical "default" value
      15,
      ['left', 'right', 'bottom', 'top']
    ]
  }
}
```

**Comment by mapcarta** [comment]
We've had success using a single-element arrays for text-variable-anchor, when used with the zoom-dependant "step" function. This can be paired with another zoom-dependant "step" function for "text-radial-offset" with one of the values set to 0. We're using Mapbox GL JS version 1.2.0. For example:

```
{
  'stops':[
    [
      9,
      ['center']
    ],
    [
      10,
      ['bottom', 'top']]
  ]
}
```

**Comment by tristen** [comment]
@mapcarta thanks for sharing! that's a good workaround and works for me. Unless there's a valid reason to provide a default value to `text-variable-anchor` @asheemmamoowala @mourner, I'm happy to close this.

**Comment by asheemmamoowala** [comment]
> that's a good workaround and works for me

Great. There is one caveat here, that is you won't be able to switch between `text-offset` and `text-radial-offset` within a single layer depending on zoom. That is similar to the underlying issue with https://github.com/mapbox/mapbox-gl-js/issues/8331. i.e. the presence of a property changes the layer's behavior regardless of the value.

If that constraint is OK, then let's close this.

**Comment by tristen** [comment]
Right. I'm OK with this caveat for now and if that larger, underlying issue is more or less captured in #8331 then I'm we're good here.

**Comment by chloekraw** [comment]
Thank you @mapcarta! 

cc @mapbox/map-design-team @mapbox/docs https://github.com/mapbox/mapbox-gl-js/issues/8344#issuecomment-516386251 is a great example of content that could live in the future "map design docs" to show people how to do things with the style spec properties that enable variable label placement.
