### ISSUE TITLE
Allow map viewport to include areas outside of real longitudes / latitudes

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#835]
![repos](https://cloud.githubusercontent.com/assets/4551508/5065024/89f38552-6dca-11e4-81eb-d2224b7233ae.gif)

Right now, zooming all the way out usually involves translation of the map to ensure we don't see any gaps. This shift is hard to predict programmatically, and can affect applications that need to track and control map center at all times. Is there (or should we build) a map prop to disable this auto-reposition?

**Comment by musicformellons** [comment]
+1

**Comment by mourner** [comment]
Closing the issue as stale, since there doesn't seem to be much interest in addressing it.
