### ISSUE TITLE
How to get raw geojson data from addSource request: follow-up

### ISSUE THREAD

**Issue by vgoklani** [mapbox/mapbox-gl-js#8350]
Hello - thanks for the follow-up on the previous question:

https://github.com/mapbox/mapbox-gl-js/issues/8333

I tried this:

	map.on('load', function() {
		map.addSource("geo_data", {
			"type": "geojson",
			"data": "/data.geojson",
			"buffer": 1,
			"maxzoom": 14,
			"generateId": true
		});
		map.addLayer({
			id: 'locations',
			type: 'symbol',
			source: "geo_data",
			layout: {
				'icon-image': 'restaurant-15',
				'icon-allow-overlap': true,
			}
		});

		const stores = map.querySourceFeatures("geo_data");
		console.log(stores)

but unfortunately it's returning an empty array. 

@mourner is the GeoJSON data stored somewhere else (?), even as a private variable?

@planemad the data is visible on the default view of the map - the code was taken from the sweetgreens example, and I'm just passing the data from the server instead of hard-coding it. Thanks!

**Comment by stevage** [comment]
I don't think the raw GeoJSON is stored anywhere. Assuming it gets converted to vector tiles then thrown away. If you need to access it (which is a common need), you'll need to fetch it yourself. I find a useful pattern is:

1. Create source, with empty GeoJSON: `{ type: 'FeatureCollection', features: [] }`
2. Create layer that uses source.
3. Fetch the actual data (using d3.json or axios or `fetch()`).
4. When the data arrives, store it and call `map.setData()` to update the source.

**Comment by bibeksh9** [comment]
You can try this 
map.getSource(sourceName).serialize().data

**Comment by mourner** [comment]
> but unfortunately it's returning an empty array.

It's probably returning an empty array because it didn't finish loading. I think you have to subscribe to some event before doing `querySourceFeatures` — e.g. `map.once('idle', ...)`.

> is the GeoJSON data stored somewhere else (?), even as a private variable?

The problem is that it's stored on the Web Worker side, not on the main thread, so there's no easy way to fetch it.

Anyway, I'd recommend that you fetch your GeoJSON in the app _in addition_ to loading it as a GL JS GeoJSON source. That removes any gotchas / difficulties from this case.

**Comment by dollysingh3192** [comment]
> > but unfortunately it's returning an empty array.
> 
> It's probably returning an empty array because it didn't finish loading. I think you have to subscribe to some event before doing `querySourceFeatures` — e.g. `map.once('idle', ...)`.
> 
> > is the GeoJSON data stored somewhere else (?), even as a private variable?
> 
> The problem is that it's stored on the Web Worker side, not on the main thread, so there's no easy way to fetch it.
> 
> Anyway, I'd recommend that you fetch your GeoJSON in the app _in addition_ to loading it as a GL JS GeoJSON source. That removes any gotchas / difficulties from this case.

Hi @mourner ,
I am facing a similar issue and asked at stackoverflow: https://stackoverflow.com/questions/61980850/filter-features-outside-the-viewport-in-mapbox

Can you please have a look and help me, if i am doing something wrong?
Thank you in advance
