### ISSUE TITLE
Is it possible to change text direction for imported OSM data?

### ISSUE THREAD

**Issue by vomc** [mapbox/mapbox-gl-js#8352]
**mapbox-gl-js version**: @latest

### Question

Is there a way to change the text direction in Mapbox studio? I am asking because I haven't been able to google a solution to this issue. 

I have a customized style designed for a mapping project where we are pulling in custom streetname data from OSM tags (some of these I've outlined in red below). I have imported these as a text layer in my project but am looking for a way to reverse the text direction to right-to-left. 

<img width="1337" alt="Screen Shot 2019-06-14 at 2 18 59 AM" src="https://user-images.githubusercontent.com/78635/59475395-836a8b80-8e4b-11e9-9497-dd83b8bb38d5.png">

### Links to related documentation

Hoped to find info here:
https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-string

Style link:
https://studio.mapbox.com/styles/jochenh/cjwvc87wh02k31cmoclnojey2/edit/#15.39/31.95921/35.916752

**Comment by ryanhamley** [comment]
Hi @vomc you can use the [RTL Plugin](https://github.com/mapbox/mapbox-gl-rtl-text) as seen in [this example](https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/).
