### ISSUE TITLE
When render a lot of points (more than 150000), the chrome browser use a lot of memory about 1.5GB?

### ISSUE THREAD

**Issue by ggservice007** [mapbox/mapbox-gl-js#8357]
When render a lot of points (more than 150000), the chrome browser use a lot of memory about 1.5GB? 
At last the chrome crash because no memory.

My Env:
Mapbox-gl-js Version 1.0.0.

**Comment by mourner** [comment]
Unfortunately there's not enough information in the ticket for us to address this. Please fill the ticket template thoroughly next time you submit one.
