### ISSUE TITLE
how to get layer`s bound

### ISSUE THREAD

**Issue by JerckyLY** [mapbox/mapbox-gl-js#8360]
**mapbox-gl-js version**:

### Question

There is currently no way to directly get the bound of the layer, whether it is a vector type or a raster type layer.

**Comment by stevage** [comment]
I think this should do what you want: `map.getSource('mysource').tileBounds.bounds`

**Comment by JerckyLY** [comment]
> I think this should do what you want: `map.getSource('mysource').tileBounds.bounds`
First of all, thank you for your reply, but I did not find the 'tileBounds' attribute in map.getSource('mysource'). Is it a version issue?

**Comment by JerckyLY** [comment]
> I think this should do what you want: `map.getSource('mysource').tileBounds.bounds`

OK, thank you very much!

**Comment by peterqliu** [comment]
>I think this should do what you want: map.getSource('mysource').tileBounds.bounds

If by "layer" you mean style layer, this would work only if the style layer contains all features in the source. If the layer has a filter, or the source has more than one source-layer, then the style layer's extent will almost certainly be smaller than the source's.

**Comment by stevage** [comment]
True.

Also, pointing out that the method I gave is completely undocumented.

**Comment by peterqliu** [comment]
Closing for now -- no immediately obvious way to do this without changes to backend/tile generation process

**Comment by Nuhasami** [comment]
> True.
> 
> Also, pointing out that the method I gave is completely undocumented.

hi, just wondering, does this method still exist?
