### ISSUE TITLE
Vector tile layer 'underzooming'

### ISSUE THREAD

**Issue by mzervens** [mapbox/mapbox-gl-js#8361]
**mapbox-gl-js version**: Latest

### Question

Is it possible to configure mapbox-gl-js to render a detailed tile level at lower detail zoom levels?
For example we have a vector tile cache with data at zoom level 5 and we also want to display this same data at zoom level 4 (lower resolution).

Thanks!

**Comment by andrewharvey** [comment]
related to #7388

**Comment by stevage** [comment]
Pretty sure this has been discussed and ruled out.

**Comment by mourner** [comment]
Yep, this comment still stands https://github.com/mapbox/mapbox-gl-js/issues/7388#issuecomment-428271170
