### ISSUE TITLE
Marker clustering

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#837]
Yes, it's that issue you were kind of thinking of and expecting, I'm posting it.

* How should gl-js support clustering? Should it be a first-class style, built into the library by default, or a plugin?
* How should clusters be represented in vector tiles, if at all?

**Comment by StepanKuzmin** [comment]
As I understood, this behaviour is not marker clustering?

![map](https://cloud.githubusercontent.com/assets/533564/8279376/760daa94-18ed-11e5-9435-fc36778255d5.gif)

How can I deal with this behaviour? Can I specify radius which causes marker disappearing using style or something?

**Comment by mourner** [comment]
@StepanKuzmin what's the source of the data here?

**Comment by StepanKuzmin** [comment]
Hi, @mourner! It's GeoJSON source.

**Comment by mourner** [comment]
@StepanKuzmin take a look at symbol properties here https://www.mapbox.com/mapbox-gl-style-spec/#symbol. It's not clustering, it's collision avoidance.

**Comment by StepanKuzmin** [comment]
Oh, I see. Thanks for reply, @mourner! 

Btw, is there are any plans for leaflet-like markers styling? I saw https://github.com/mapbox/mapbox-gl-js/issues/1260 and https://github.com/mapbox/mapbox-gl-js/issues/656, so maybe it would be something like `L.divIcon` which return gl context? It would be nice to have ability to style markers with all webgl power.

**Comment by mourner** [comment]
Happening in #1931
