### ISSUE TITLE
Pinch zoom not working in IE11

### ISSUE THREAD

**Issue by SamuelTrimble** [mapbox/mapbox-gl-js#8375]
**mapbox-gl-js version**: v1.0.0
**browser**: IE11 (11.0.130)
**os**: Windows 10 (1903)

### Steps to Trigger Behavior

 1. Open basic map in IE11.
 2. Use two-finger pinch gesture to attempt to zoom in/out.

### Link to Demonstration

https://jsbin.com/lixepihuca/1/edit?html,js,output

### Expected Behavior
Map zooms in/out as fingers move apart/together.

### Actual Behavior
Map pans around as fingers move without zooming. As if only one finger is detected.

.
.
.
Thanks @mzdraper for directing me to this repo so I could submit this.

**Comment by ansis** [comment]
Closing because [IE 11 is no longer supported](https://github.com/mapbox/mapbox-gl-js/blob/main/CHANGELOG.md#200). Thanks for reporting this.
