### ISSUE TITLE
Marker text is doubled on zoom

### ISSUE THREAD

**Issue by ekelleyv** [mapbox/mapbox-gl-js#838]
On this example, zoom in on one of the markers and the text appears doubled and slightly offset. Chrome 38, Mac OS X 10.9.2.

https://www.mapbox.com/mapbox-gl-js/example/geojson-markers/

![](http://cl.ly/image/0E1g2c2D1Z3t/Screen%20Shot%202014-11-17%20at%201.28.42%20PM.png)

![](http://cl.ly/image/0P1z102s3N24/Screen%20Shot%202014-11-17%20at%201.28.21%20PM.png)

Also, does the geoJSON marker text not take into account previously placed labels for collision detection? As in, you can get to a point where "Mapbox SF" is directly over the "San Francisco" map label. I am guessing different layers have no knowledge of each other?

**Comment by jfirebaugh** [comment]
No longer reproducible.
