### ISSUE TITLE
mapbox gl js show utfGrid layer demo

### ISSUE THREAD

**Issue by steeeeps** [mapbox/mapbox-gl-js#8381]
I want use mapboxgl js v0.52.0 to show utfGrid layer created by mapnik ,  is there any demo?
thanks.

**Comment by peterqliu** [comment]
hi @steeeeps , can you say more about how you're incorporating utfGrid? code snippets would be helpful

**Comment by steeeeps** [comment]
hi @peterqliu  
 I'm using vector tile to visualize  data now , and provide interaction capabilities in mapboxgl . But a part of my website users still use old computer or old browsers ，the vector tile datas rendering is slow. so i want change vector tile to raster with uftgrid to show geographic datas. but i can't find any demos for mapboxgl js library.

**Comment by peterqliu** [comment]
check out this example for raster tile rendering with mbxgl: https://docs.mapbox.com/mapbox-gl-js/example/map-tiles/

the demo is currently down because the tile endpoint (stamen) is down, but you can swap in the url for the tiles you need

**Comment by steeeeps** [comment]
ok , thanks.
