### ISSUE TITLE
Tile boundaries show at high zoom when polygon boundaries are in a `line` layer 

### ISSUE THREAD

**Issue by dbrnz** [mapbox/mapbox-gl-js#8385]
Mapbox GL 1.0.0

Chrome, Firefox, Safari

Vector tiles were generated using `tippecanoe`.

### Steps to Trigger Behavior

 1. Style polygons from a vector tile source in a `line` layer, with line width scaled to zoom level. e.g:
```
 {
      'id': id,
      'source': source_id,
      'source-layer': layer_id,
      'type': 'line',
      'filter': [ '==', '$type', 'Polygon' ],
      'paint': {
          'line-color': 'blue',
          'line-width': [ "interpolate", ["exponential", 2], ["zoom"],  0, 0.5,  8, 128 ]
       }
}
```
2. Zoom in.

### Expected Behavior
<img width="656" alt="Screen Shot 2019-06-24 at 10 00 23 PM" src="https://user-images.githubusercontent.com/239220/60012762-e6241880-96d0-11e9-8063-4d96e16d3d2a.png">

### Actual Behavior
<img width="659" alt="Screen Shot 2019-06-24 at 10 00 05 PM" src="https://user-images.githubusercontent.com/239220/60012808-ff2cc980-96d0-11e9-98c4-0685a248c20e.png">

**Comment by ericfischer** [comment]
This looks to me like you need to specify a larger tile buffer (with tippecanoe's `-b` option) to make the edges of the clipped polygons further from the tile edge.

**Comment by dbrnz** [comment]
Aha, that did it, thanks!
