### ISSUE TITLE
Add ability to use next zoom level for raster tiles

### ISSUE THREAD

**Issue by ekelleyv** [mapbox/mapbox-gl-js#839]
In order to avoid pixelated raster tiles, would it not make sense to display the tile for the next zoom level instead of the previous zoom level? As in show the tiles for `ceil(zoom)`? The scaled up raster tiles look pretty bad:

![](http://cl.ly/image/323n1c0u3u01/Screen%20Shot%202014-11-17%20at%202.27.07%20PM.png)

There is a good chance I am just missing a setting.

**Comment by edenh** [comment]
@ekelleyv you can half the [`tileSize`](https://www.mapbox.com/mapbox-gl-style-spec/#raster) property in the raster source specification to increase resolution. This does however cause double the amount of tiles to be loaded.

**Comment by jfirebaugh** [comment]
⇢ #1030
