### ISSUE TITLE
How to set clusterMaxZoom based on zoom in mapbox?

### ISSUE THREAD

**Issue by GiorgioMartini** [mapbox/mapbox-gl-js#8396]
**mapbox-gl-js version**:

### How to set clusterMaxZoom based on zoom in mapbox?

I want to set clusterMaxZoom value, based on the zoom.

So at very high zoom, I have some settings, and then from some point on, I have another settings.

Ive think it could be done with Expressions, but in the examples, they change properties of circleRadius:

paint: {
  'circle-radius': [
    'interpolate', ['linear'], ['zoom'],
    10, ['/', ['-', 2017, ['number', ['get', 'Constructi'], 2017]], 30],
    13, ['/', ['-', 2017, ['number', ['get', 'Constructi'], 2017]], 10],
  ],
  'circle-opacity': 0.8,
  'circle-color': 'rgb(171, 72, 33)'
}
});

So i tried to do this:

at zoom 5, set the clusterMaxZoom to 25 at zoom 13, set the clusterMaxZoom to 250

Like this:

    clusterMaxZoom: [
      'interpolate', ['linear'], ['zoom'],
    5, 25,
    13, 250,
    ],
This is how it looks on my source:

    map.addSource('users', {
    type: "geojson",
    // Point to GeoJSON data. This example visualizes all M1.0+ users
    // from 12/22/15 to 1/21/16 as logged by USGS' Earthquake hazards program.
    data: markers,
    cluster: true,
    // clusterMaxZoom: 22, // Max zoom to cluster points on
    clusterMaxZoom: [
      'interpolate', ['linear'], ['zoom'],
    5, 25,
    13, 250,
    ],
    clusterRadius: 250 // Radius of each cluster when clustering points (defaults to 50)
    });
But it doesnt work, I get this error:

sources.users.clusterMaxZoom: number expected, array found

Any idea how to change the clusterMaxZoom based on zoom?

### Links to related documentation

https://docs.mapbox.com/help/tutorials/mapbox-gl-js-expressions/#add-a-zoom-expression

**Comment by peterqliu** [comment]
thanks for the question @GiorgioMartini. a few notes:

>Ive think it could be done with Expressions

unfortunately, the expressions syntax applies only to style properties in layers, but not in parameters of `addSource`. `clusterMaxZoom` is [restricted to numbers](https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources-geojson-clusterMaxZoom)

>at zoom 5, set the clusterMaxZoom to 25 at zoom 13, set the clusterMaxZoom to 250

I'm unclear about what the desired effect is -- zoom-dependent `clusterMaxZoom` doesn't make immediate sense, because the property only specifies the maximum zoom to apply clustering. It's a zoom boundary that wouldn't need to move, even as you move around in it. Can you say more about what specifically you're wanting to change as the map zooms?

**Comment by GiorgioMartini** [comment]
Thanks for the help, it means a lot, couldnt get an answer online :)

So, im building an app where you can see users on a map, but i don't want to show their exact location because of privacy.

So i thought I could cluster them, then show how many people like in the radius of a cluster, so their location is just approximate.

So whith normal clusterMaxZoom and clusterRadius settings like 14 and 25 correspondingly, it works fine until we zoom very much into the map. then the  clusters decluster, and you can see the exact location of the users.(which i dont want)


So if at a certain zoom level i could change the settings to:
clusterMaxZoom: 22
clusterRadius: 250

Then at very zoomed levels it still clusters, 

The problem is, if i keep these lasts settings, then when zoomed out, it overclusters.


Do you think there is another way to solve this issue, in another more proper way with mapbox's fetures?

I would love to know.

Thanks

**Comment by peterqliu** [comment]
Sounds like you want to scale the cluster radius not by screen pixels, but roughly according to some real world distance.

Unfortunately neither `clusterMaxZoom` nor `clusterRadius` can be zoom dependent properties, and there's no way to implement different clustering schemes for different zoom ranges.

However, you can approximate the effect by adding the same datasource multiple times with gradually increasing clusterRadii, each with a corresponding style layer visible at gradually increasing zoom ranges (minZoom and maxZoom). Low zooms would show the source with lowest radius, and as the user zooms in, the subsequent layers fade in and out with sources of increasing radius. Does that make sense?

**Comment by GiorgioMartini** [comment]
Ill try that! also I got a sweetspot by playing with the maxZoomCluster and clusterRadius, and setting a maxZooom level for the map.

I also used expression to make the singe users circle bigger on lower levels so that their area where they live is pretty big, so you can see where more less a users lives but not its exact location, which is what i want. 

I think Its a good enough solution. Thanks for helping out!  :)
