### ISSUE TITLE
switch raster tile source in example

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#8398]
https://docs.mapbox.com/mapbox-gl-js/example/map-tiles/ is broken, because the stamen endpoint looks like it's no longer active. let's switch it to a mapbox one, or a stable external one

**Comment by andrewharvey** [comment]
related to #8274

A potential problem with using a Mapbox one is, people might end up using a direct tile URL instead of getting the tilejson with `mapbox://`. Then again, it's probably not a big issue.

**Comment by andrewharvey** [comment]
> because the stamen endpoint looks like it's no longer active.

So it looks like the stamen tiles work, but aren't available over https, so you get mixed content errors. In #8482 I swap to using https to fix the example.

I'd also be open to using something like mapbox.pencil or mapbox.pirates, the old cartocss Mapbox defaults, which still shows how to use raster tiles, but all using Mapbox services.
