### ISSUE TITLE
assign color to layer using a function

### ISSUE THREAD

**Issue by hmendezm** [mapbox/mapbox-gl-js#8400]
**mapbox-gl-js version**:

### Question

Hi Guys,
is it a way to use a function instead of values in the stops:[]? In my case, the colors are not defined prior so there is a function that calculates them. How I can call a function with the value of the property. This function returns the color (string)
best
Hank

**Comment by asheemmamoowala** [comment]
@hmendezm The value properties can reference arbitrary JavaScript methods. You can use the expressions syntax if the logic can be encapsulated there. 
[Example](https://docs.mapbox.com/mapbox-gl-js/example/data-driven-circle-colors/)
[Expressions documentation](https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions)

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by hmendezm** [comment]
HI asheemmamoow,

The expressions do not work for me because the data is dynamic. for instance in the example you "hardcode" the value and the color, in my case, the values of the property could be hundreds and the colors are calculated by an algorithm.

**Example**
'fill-color': [
'match',
['get', 'ethnicity'],
'White', '#fbb03b',
'Black', '#223b53',
'Hispanic', '#e55e5e',
'Asian', '#3bb2d0',
/* other */ '#ccc'
]

**What I need**
'circle-color': [
'match',
['get', 'ethnicity'], **getColor(Protertyvalue)**
]

function getColor(value){
// Do calculation
return color;
}

**Comment by 2803media** [comment]
@hmendezm did you find a solution ? Thanks i'm in the same situation

**Comment by bw1984** [comment]
i'm currently trying to figure out how to accomplish this also
