### ISSUE TITLE
Undocumented expressions

### ISSUE THREAD

**Issue by aparlato** [mapbox/mapbox-gl-js#8403]
**mapbox-gl-style-spec version**:
"@mapbox/mapbox-gl-style-spec": "^13.7.0"

### Question

It looks like there are new expressions that aren't documented like [`error`](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/expression/definitions/index.js#L118-L122) as well as expressions that are documented without sdk compatibility tables: https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-is-supported-script

This recently caused an [issue in Studio](https://github.com/mapbox/studio/issues/11710) since we now use gl's sdk compatibility tables for expressions. We mitigated this by not checking compatibility for expressions that don't have a compatibility table, but ideally all expressions should probably be documented.

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions

**Comment by asheemmamoowala** [comment]
SDK compatibility tables have been added for all types. And `error` is not a true public expression. Closing as fixed
