### ISSUE TITLE
Fix requirements for text-radial-offset and text-variable-anchor in style spec

### ISSUE THREAD

**Issue by dereklieu** [mapbox/mapbox-gl-js#8410]
In the style spec reference, [text-radial-offset](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/reference/v8.json#L1798) and [text-variable-anchor](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/reference/v8.json#L1831) should both have `text-field` added to their requirements. This would make these two consistent with the other `text-` properties. As it is, in Studio you can select these two properties when you shouldn't be able to.

![text-style-spec](https://user-images.githubusercontent.com/1590802/60373086-c2ecb800-99b3-11e9-827a-5bcee3c49355.gif)

In addition, [text-offset](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/reference/v8.json#L2124) should have `!: text-variable-anchor` in it's requirements in addition to `!: text-radial-offset` which it already has.

In addition to #8397, we would love to get this fixed before supporting these two new, highly-anticipated properties in Studio :) I'm happy to create a PR for this.

**Comment by chloekraw** [comment]
Closed by https://github.com/mapbox/mapbox-gl-js/pull/8418
