### ISSUE TITLE
Map is not loading when using mapboxgl-popup

### ISSUE THREAD

**Issue by DevN1mr0d** [mapbox/mapbox-gl-js#8412]
**mapbox-gl-js version**: WP Mapbox GL JS Maps Version 2.0.5

**browser**: Chrome Version 75.0.3770.100 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Use example code from https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/ for a popup function
 2. Replace accessToken and style respectively
 3. Test page

### Link to Demonstration

[Test page](http://www.archaeoimage.com/312876-2/)

### Expected Behavior

Map is loading, info box shows when using popup on click function

### Actual Behavior

Map is not loading. Code used from [example page](https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/)
 with minimal changes:

`<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title>Display a map with a custom style</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=yes' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.0.0/mapbox-gl.css' rel='stylesheet' />
    <style>
      
        #map { position:inherit; top:0; bottom:0; width:200%; height:699px; }
    </style>
</head>
<body>

<style>
.mapboxgl-popup {
max-width: 400px;
font: 12px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
}
</style>
<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.0.0/mapbox-gl-directions.js'></script>
<link rel='stylesheet' href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-directions/v4.0.0/mapbox-gl-directions.css' type='text/css' />

<style>
.mapboxgl-popup {
max-width: 400px;
font: 12px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
}
</style>
<div id='map'></div>
<script>
mapboxgl.accessToken = 'pk.eyJ1IjoiZ2VvcmdpZXdlYiIsImEiOiJjanZrM3htOWswbG9lM3ptZzd4ejBqbjNtIn0.dCv92Fq2pWzpJvEnEY6RyA';
var map = new mapboxgl.Map({
    container: 'map', // container id
    style: 'mapbox://styles/georgieweb/cjxc84fsf09da1cs6jjxot2j9', //hosted style id
    center: [77.38, 29], // starting position
    zoom: 3 // starting zoom
map.scrollZoom.enable();
map.addControl(new mapboxgl.NavigationControl());
map.addControl(new MapboxDirections({
accessToken: mapboxgl.accessToken
}), 'top-left');

</script>

</body>
</html>`

**Comment by andrewharvey** [comment]
This appears to be an error in your implementation, check the console and it will show the problem.
