### ISSUE TITLE
How to change marker icon when hovering over sidebar item?

### ISSUE THREAD

**Issue by GiorgioMartini** [mapbox/mapbox-gl-js#8414]
**mapbox-gl-js version**:

### How to change marker icon when hovering over sidebar item?

In your docs, you have a tutorial where you show how to fly to a location and show a popup when clicking on an item on a sidebar.
https://docs.mapbox.com/help/tutorials/building-a-store-locator/

However, for changing the icon/image/paint of a marker, i dont know how to do it, as my markers are on layers, and I have `NOT` created the markers like this: 

```
new mapboxgl.Marker(el)
.setLngLat(marker.geometry.coordinates)
.addTo(map);
```
But instead I used the paint circle feature in a layer. I am also using clustering.

So I dont have acces to a marker object where I can add and remove it like:  marker.remove()

What type of setup do i need in order to have the my markers and clusters, and then when I hover over an item on the sidebar it changes the marker icon or bouces it or do something to highlight they are related?

This is my code, where i have a geoJson in a variable called markers, and I paint the icons with the paint feature:  

```
      map.on('load', function() {
        
        map.addSource('users', {
        type: "geojson",
        data: markers,
        cluster: true,
        clusterMaxZoom: 22,
        clusterRadius: 50, // Radius of each cluster when clustering points (defaults to 50)
        });

          map.addLayer({
            id: "singles",
            type: "circle",
            source: "users",
            filter: ["!has", "point_count"],
            paint: {
                'circle-radius': {
                    'base': 10,
                    'stops': [[5, 20], [15, 500]]
                },
                'circle-color': '#ddffc8',
              }
          });

        map.addLayer({
            id: "singles-count",
            type: "symbol",
            source: "users",
            filter: ["!has", "point_count"],
            layout: {
              "text-field": "1",
              "text-font": ["DIN Offc Pro Medium", "Arial Unicode MS Bold"],
              "text-size": 12,
            }
          });

        map.addLayer({
          id: "clusters",
          type: "circle",
          source: "users",
          filter: ["has", "point_count"],
          paint: {
            "circle-color": '#ddffc8',
            'circle-radius': {
                'base': 10,
                'stops': [[5, 20], [15, 500]]
            },
          }
        });
         
        map.addLayer({
          id: "cluster-count",
          type: "symbol",
          source: "users",
          filter: ["has", "point_count"],
          layout: {
          "text-field": "{point_count_abbreviated}",
          "text-font": ["DIN Offc Pro Medium", "Arial Unicode MS Bold"],
          "text-size": 12
          }
        });
});
```
I created asimplified version of what i have here, so you can see my setup: https://codepen.io/giorgiomartini/pen/qzVJBz?editors=1010
Thanks!

**Comment by mourner** [comment]
You would use `map.setFeatureState` method, e.g. like in this example https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/

**Comment by ian-whitestone** [comment]
hey @GiorgioMartini, just curious if you ever got this working and have an example you could share, I am running into the same problem.

**Comment by solarcellsky** [comment]
你可以定义一个 function 绑定(click or mouseenter)到你的 sidebar item 上，获取某一个参数，比如: id, function 里调用

map.setLayoutProperty('here is your layer id', 'icon-image', ['match', ['id'], 'here is your id', 'icon-selected', 'icon-default']);

这里的 'icon-selected', 'icon-default' 需要你自己定义一个对象， 比如：

const myIcons = {
     'icon-default' : 'your icon image',
     'icon-selected': 'your icon image',
}

然后下面这样添加你的 iocns 到地图实例：

for (const key in myIcons) {
      if (myIcons.hasOwnProperty(key)) {
        map.loadImage(myIcons[key], (error, image) => {
          if (error) throw error;
          map.addImage(key, image);
        });
      }
}
