### ISSUE TITLE
How to create Heatmap without loading jsonfile

### ISSUE THREAD

**Issue by shobishani** [mapbox/mapbox-gl-js#8421]
**mapbox-gl-js version**:
   Latest
### Question
I am trying to create HeatMap layer.
in documentation it's created with json file but I don't have the json file from another url I have coordinates.

I tried to create geoJson in object and then parse it to json.
and `map.addSource(geoJson)` 
> geoJson is variable where String Json is.
when it loads it gives me error that 

> http://localhost:4200/campaigns/%7B%22type%22:.............
basically it's treating geoJson data as URL where this will be loaded.

I tried docs but couldn't find another way, So How can I create HeatMap if I have coordinates not some json file path. 

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/

**Comment by mourner** [comment]
@shobishani if you pass it GeoJSON directly, it should be a JS object, not a string. If you have it as a string, pass it as `JSON.parse(geojsonString)`.
