### ISSUE TITLE
Remove outline from fill layer

### ISSUE THREAD

**Issue by simonrp84** [mapbox/mapbox-gl-js#8423]
Hello,
I am using mapbox GL JS (v1.1.0) to display a series of GeoJSON polygon / fill objects. However, these exhibit the known issue of rendering problems (#7023), as shown by the horizontal yellow line in the pic below.
![Untitled](https://user-images.githubusercontent.com/13449576/60517478-aa441100-9cd7-11e9-8329-3fc9af217e3a.png)

It seems to me that this is an issue with the outline, so I tried fiddling with `fill-outline-color` and that does indeed change the color of these erroneous lines but does not get rid of them.
Is there a way to adjust some of the other props of the outline? For example by setting the fill outline opacity or similar? I tried a few combinations and checked the docs but can't find anything that looks suitable.
This is, unfortunately, a bit of a showstopper so any ideas and suggestions would be most welcome.

[edit] I should add, I'm not in charge of the JSON objects that need to be displayed, so editing the JSON to be compliant with how Mapbox can draw them is, sadly, not an option.

**Comment by mourner** [comment]
Unfortunately I can't diagnose the issue because there's not enough information — you haven't filled out the bug report template, including a minimal live test case. It's hard to guess what's going on just seeing the screenshot.

**Comment by simonrp84** [comment]
Hello,
This isn't meant to be a bug report (this bug has already been reported many times, see the issue #7023 that I link to) but a question about attempting to find a workaround.
This issue will occur with any of the test cases given in #7023, such as #3545. I'm just asking if there is a property, say `fill-outline-opacity`, that could negate this issue.

**Comment by mourner** [comment]
@simonrp84 I don't think those artifacts are related to fill outline in any way. Generally you can disable the fill outline with [fill-antialias: false](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-fill-fill-antialias).

**Comment by simonrp84** [comment]
Hi, just to add for anyone else that finds this: The `fill-antialias: false` option does fix the vast majority of the artefacts present when plotting GeoJSON polygons.
