### ISSUE TITLE
How to get mapbox's camera to follow a moving icon in real time.

### ISSUE THREAD

**Issue by mjcc007** [mapbox/mapbox-gl-js#8428]
Hello, <br>
 I'm moving a symbol in real time, and I'm following it with my camera (like flyto or setcenter), but I have sort of jitter/drift between the move of the map and the markers.<br>
I use mapboxgl on the web. <br>
How do I use the camera smoothly?<br>
thanks!

**Comment by mourner** [comment]
Can you please fill out the issue template? We can't guess what kind of jitter/drift you're seeing without a live test case at least.

**Comment by asheemmamoowala** [comment]
@mjcc007 Feel free to re-open this issue when you have additional details based on our issue template.
