### ISSUE TITLE
Uncaught Error: failed to invert matrix

### ISSUE THREAD

**Issue by gurprreetkhattra** [mapbox/mapbox-gl-js#8430]
Its working on another locations but not working on some locations, jsfiddle link shared below

https://jsfiddle.net/gskhattra/swmhLfd9/2/

Error message below, 

Google Chrome
Version 75.0.3770.100 (Official Build) (64-bit) 

Uncaught Error: failed to invert matrix
    at ho._calcMatrices (transform.js:589)
    at ho.po.zoom.set (transform.js:176)
    at ho._constrain (transform.js:487)
    at ho.setMaxBounds (transform.js:416)
    at r.setMaxBounds (map.js:529)
    at r.<anonymous> (19:172)
    at r.St.fire (evented.js:115)
    at r._render (map.js:1758)
    at map.js:1829

**Comment by andrewharvey** [comment]
Your bounds don't look right:

[[76.6902311, 30.7111782], [76.68409729003906, 30.70661735534668]]

See https://docs.mapbox.com/mapbox-gl-js/api/#lnglatbounds the format is south west, north east. South must be < north, and west < east.

**Comment by gurprreetkhattra** [comment]
@andrewharvey  thanks for replay, but these lat, long return by android sdk in navigation. then how  these wrong. please explain?
