### ISSUE TITLE
for better overlaying getViewExtent  which returns pixel rect and lnglat bounds for pitched and rotated maps

### ISSUE THREAD

**Issue by arthur-clifford** [mapbox/mapbox-gl-js#8432]
## Motivation
I am making image overlay layers and would like to be able to render a layer image un-pitched and un-rotated such that when it is overlayed on the map it covers the view to the edge of the map.

This is a bit abstract to write about ... but if you think of the image overlay as beign a texture on a thin 3D wafer that gets tilted and rotated, the problem is even if you give me the maximum and and minimum lat/lon values for the tilted and rotated map, I don't get a pixel width and height back for the image I need to generate to provide enough pixel data to fill in the extra area at the top/sides of the tilted wafer to cover the area filled in by tiles out to the edge of the map.

Currently I'm using a routine that requests a rendered layer by getting the ultilted unrotated extents and using the width and height of the map. The result is that the image looks fine tilted and rotated but if you pan to where the image would be cropped in untilted unrotated view, the image seems to arbitrarily get cut of in the tilted map.

You can see the problem by going here:
https://app-dev.simplelayers.com/~staging/apps/public/simple_map/8406

* When the polygons show up, right click to tilt the map to 45 degrees (everything looks ok)
* Then drag the map north about half the height height of the polygons image.
* You'll see that the top row of polygons gets cut off after the image reloads.
* Drag it back a little south and you'll see things re-appear.
* If you click the Arrow to the right of the house icon button in the upper left of the page, it will reorient the map and you'll see that the crop on the tilted map is where the top of the un-pitched map reaches the top of the window.

## Design Alternatives

Of course tiles are the trend, but they are not always as viable a solution.
You *could* chose to go all tiles all the time, but I don't personally believe you *should*, overlaying and tiling are best used together

I could attempt to make my map-server render a pitched and rotated image at the extents and map center, but that assumes it can do that in the first place, and it assumes that the tech it uses to do that is the same as the gl tech being used in by mapbox-gl, in particular it assumes both are using the same floating point accuracy and transforms.

## Design

My opinion on this front is that if you are going to allow folks to do image overlays than we should figure out how to do that for pitched and rotated maps.

It is also been my presumption that either the viewer or the server should be maintaining the pixel/geometry relationships but never both.

So, the model I would prefer is one in which I can get the bounding rectangle in pixels that would encompass the loaded tiles used for rendering a pitched and rotated map, and then the LngLat bounds to georeference them with.

With that I can render an image which when loaded will fill the pitched and rotated map and which will let gl work out the transformations for pitching and rotating the loaded image.

### Mock-Up

For developers:
Something like ...
const exts:RenderExtents = map.getRenderExtents();

Where:
interface RenderExtents {
   view: { width:number, height: number }
   bounds: LngLatBounds
}

For users:
The will see a map that doesn't arbitrarily crop overlay images at the map element's width and height.

### Concepts
Teaching the design should be expanding the example for an image overlay on the examples page to where user interaction on the map will trigger an event which can be handled and used to update the request url with width and height in pixels and a bbox, which are farily common requirements for WMS (as opposed to tile services).

I don't know if any of this is novel. But others have asked for extents of the pitched map in the past and they've opted to get things as a geometry they can use with postgres. 

I think the key here is not to get caught up in the fact that things are 3D. Its like having a square paper map on a table, you can walk around the table and sit down at the table or stand over it, but the map is in reality just a square map on the table. From your perspective it is distorted and skewed and titled and rotated etc.Your field of view will sub-set an area on the map, and what we want to load while you are looking at that part of the map is whatever will at least fill your field of view. But what we load is not tilted. Its like getting a piece of paper and then laying it on top of the map. Once you've overlayed the paper so that it fits the map where you want it, then it will share the distortion of the underlying map that your perspective has when you walk around the table.

I guess you can say that with 3D rotation and pitching of a map, the "unprojected extents" are not the map corners in lat/lon its the width and height of a square/rectangular map in pixels  and the georeferencing info needed to associate the corners of the pixel dimensions. The important, and perhaps less obvious, distinction here is that the width and height are not the width and height of the map's div tag. If we are basing things on tiles, then it would be the pixel dimensions based on the tiles required to fill the view area at its pitched and rotated state.

### Implementation

I'm creating a separate issue for a feature request for a more general ViewChange event. In an ideal world there would be an event with a debounce timing that would allow the user to move and pan and rotate the map and when they stop we'd get a single event to listen for that would include the render extents. 

A developer in any language that can work with event handling would be able to get the information from the event for then sending to rendering services to generate imagery to return which should just entail a url modification.

If we want to be even more helpful you could make the image overlay tech automatically  listen to that event and maintain a reference to the current map's ViewExtent and support url place holders like {width} {height} and {minlat} {minlng} {maxlat} and {maxlng} so that when the view changes the URL is automatically updated and an image reload is triggered (or by calling an updateURL handler), that way we could support url syntaxes like the z/x/y syntaxes for tiles and can account for changes to bbox/extent requirements.

What parts of the Mapbox GL ecosystem will need to change to accommodate this design?

At a minimum an api call for getting the notion of a ViewExtent that includes pixel rect and LngLat bounds.

The ViewChange event feature request would be helpful too.

If desired, perhaps building out the image overlay options and automatic url updating, or calling a updateURL handler per above.

Are there any important edge cases?
Not necessarily for MapBox tech. In my case I'm returning requests for images as  json which includes a status, the pixel dimensions the server got, the extents the server adjusts to, and the image data as base64 data. I had to do that to make the image show up correctly because its not safe to assume that the extents for the map when the image gets back is the same or that the server didn't tweak something in the process.  The json also allows for error statuses and providing additional metadata. But given an image, width and height, and extents Mapbox will properly render an image.

Visual Example:
1) Overlay layer on top of tiles
![full view](https://user-images.githubusercontent.com/20714715/60764810-3f7f3680-a045-11e9-9a78-ad7341b7b2a0.png)
2) Pitched overlay image, looks fine
![pitched](https://user-images.githubusercontent.com/20714715/60764816-5756ba80-a045-11e9-8205-178d58590261.png)
3) Panning crops the image
![pitched_panned](https://user-images.githubusercontent.com/20714715/60764981-f1b7fd80-a047-11e9-889c-5b4b6e1cd9b1.png)
4) compare cropped image to where the view extent is when panned image is unpitched.
![pitched_panned-unpitched](https://user-images.githubusercontent.com/20714715/60764988-f54b8480-a047-11e9-8d19-91e3d5e91071.png)

So to recap:
For any image rendering service I need LngLat extents and a width and height in pixels. 

If I use the view-port for dimensions, and the extents when un-pitched, I do not have enough data when pitched, or pitched-and-rotated, to render a layer completly within the visual area, and thus seemingly-weird, though logical, cropping occurs.

I use the view port pixel dimensions because it is the only pixel dimensions I have access to via the API with a known lnglat extent.

Therefore: 
I would like the pixel dimensions of the "wafer", for lack of better word, that is displayed within the view port that I need to cover, and its extents. So that the third image above looks like the second image above but panned/moved toward the top of the map and only cropping if it is at the edge of the view-port when the map is pitched and rotated.

**Comment by mourner** [comment]
Can you please provide a **minimal** live test case for that overlay issue with a readable source code so that we could see what's exactly going on?

> In an ideal world there would be an event with a debounce timing that would allow the user to move and pan and rotate the map and when they stop we'd get a single event to listen

Did you try the `idle` event?

**Comment by arthur-clifford** [comment]
At the moment the original link is as minimal as I can provide, so I append info at the end of the issue for clarity.

**Comment by mourner** [comment]
Looks like there are no plans to introduce any new APIs related to the use case at the moment, and a potential issue doesn't have a minimal test case, so there are no actionable items here for the team — let's close, but feel free to open a new issue if there's a more specific proposal or a bug report.
