### ISSUE TITLE
CameraChange or ViewChange event

### ISSUE THREAD

**Issue by arthur-clifford** [mapbox/mapbox-gl-js#8433]
## Motivation
I am overlaying image layers on the mapbox slippy map experience.
I want to update the overlay whenever the user finishes interacting with the map in such a way that it causes the map to be, rotated, pitched, moved, or zoomed

Because I want my layer not to over-refresh I also want to be able to provide a debounce/timeout duration to give the user a little time to do any number of the above interactions before I do a refresh.

## Design Alternatives

using current tech I am attempting to handle each of the events and trigger a redraw of my l ayers, but it gets tricky as the firing of the events can start to interfere with each other and cause more refreshing than I want.

## Design

For situations like image overlay rendering, you want a more universal change event.
Below I'm floating the notion of a camerachange event. Note, though, that there may be a better name. 'change' is not ideal because you might want a more universal event for noting that style or layer order or other changes have happened to a map, I would assume you'd have something like that eventually.

I'm more interested in isolating the user interaction events that would require redrawing a layer. Even if the underlying geometries are rotated or pitched in effect what we're really talking about is that the user's view of the map has changed. 

on('camerachange',(event:CameraChangeEvent)=>{
  // Do something
});
interface CameraChangeEvent {
  ...
  pitch: number;
  bearing: number;
  center: LngLat,
  viewExtents: ViewExtent
  ...
}

I'm including a reference here to the notion of a ViewExtent which is part of feature request issue:
#8432

We need more than the view dimensions and lng/lat values we need to know what we have to cover with a rendered layer.

Having a single event we can listen to for view changes makes updating stuff on the map easier.
This would be true for any layer type where a change in the view might require updating the layer.

### Mock-Up

map = new map...
map.on('camerachange',(event)=>{
  UpdateLayers();
  // or something cooler
});

Perhaps also:
map.setViewChangeDebounce(msecs:number);
Hopefully you can find a better name than that. But it would be ideal if the view change event has a debounce timing and interruption built into it because If the user right-clicks to pitch and rotate, scroll zooms, and drag pans the map in quick succession, while they are do-ing the operations I don't want overlay layers reloading all over the place.

Also, I would use such an event for tracking changes to the map location for having a navigation history. So the idea is knowing when the user has actually finished changing the view in a perhaps multi-step but quick operation I can push the new view into a history array.  

### Concepts

Well, contributors should consider whether there are combinations of events that together mean something. For instance panning and zooming and rotating etc are all part of changing the view. If there is a categorical grouping like that, it is a good candidate for a collective event.

Debouncing is a term from electronics buttons and is a bit of a pain to think about in its original form. But the general idea is that you don't necessarily want to handle every event exactly when it is fired as it may not actually be the event you want and you may want at a little time to consider whether a different event is fired. For instance the challenge of handling a click and double click on teh same button is that a double click will fire a single click event too. So you end up having a timeout that waits long enough for the double click so that you can fire that and if you do you can cancel the timeout.

Actually, setting up a nav history will illustrate the challenge of deciding when exactly did the view change to where you would want it as part of the history rather than while you were in the middle of getting to the view you wanted.

Classically panning and zooming etc took a bit to handle and so each operation was a candidate for saving as navigation history. However, y'all have made everything so slick that you can do several nav operations crazy fast. So you've changed the problem space to now be a question as to when exactly a nav change has occurred.

Of course with a nav history you could always have a button that remembers your view at any given point, but if you want a sort of undo navigation, then changes to view orientation etc if automatably collectable would be useful.

Also, in my case as an image overlay developer the images i'm overlaying being dynamically rendered are in essence a reflection of a nav/view history. So knowing when that history has been added to is kinda important.

### Implementation

This problem space may be deceptive in that it might sound simple to have the new event.

The challenges are in getting timings right and figuring out the differences between the -ing operations and -end operations. In other words we want to flag the fact that the user started or is dragging, rotating, or pitching the map, but after they stopped but within a time frame begin another of those operations such that even though the dragend event might have fired if the user is still rotating the map that we don't fire the viewchange event yet. This is in essence sending a user-stopped-changing-the-view event, so it shouldn't be sent just because any one of the events has stopped but the others still may be in effect.

**Comment by mourner** [comment]
Either `Map` `moveend` or `idle` events (depending on exact use case) will cover what you need.

**Comment by arthur-clifford** [comment]
moveend doesnt cover rotation and pitch.
I can check out idle

**Comment by mourner** [comment]
@arthur-clifford if it doesn't, that would be a bug — please double-check and submit a bug report if so. Given `moveend`'s semantic purpose, it shouldn't discriminate between different types of interaction, as the docs suggest too:

> Fired just after the map completes a transition from one view to another

**Comment by arthur-clifford** [comment]
Ok, Just for context I was trying to get both a nav history and my layer overlay stuff working in 0.54 and some of my issues with moveend or other events may be related to that version. I had upgraded to 1.1.0 to see if that would fix some stuff I was seeing but then hit the performance issue I brought up. 

 

Is it your belief it moveend should also account for zooming? I know for sure that my movend event had not been triggering when I zoomed via scroll wheel (again with the older version).

 

I will see what I can figure out and will submit bug issues if it isn’t something I was doing.

 

Thanks for pointing out the idle handler, I’d not seen that.

 

Art

**Comment by mourner** [comment]
> Is it your belief it moveend should also account for zooming? I know for sure that my movend event had not been triggering when I zoomed via scroll wheel (again with the older version).

I think `moveend` should trigger after _any_ kind of map view change. I just checked with the latest version and it seems to work as expected on zoom, pitch and rotation.

**Comment by arthur-clifford** [comment]
I've implemented movend, I can work with it.
