### ISSUE TITLE
Cross-hairs display during zooming

### ISSUE THREAD

**Issue by stefanzero** [mapbox/mapbox-gl-js#8435]

**Comment by stefanzero** [comment]
## Motivation


Using the mousewheel on Desktop changes the zoom level of the map. On Mobile, 
a multi-point pinch gesture also changes the zoom level of the map.  However, 
it is sometimes a challenge to know the exact point that is the center of the zoom action.

## Design Alternatives


Add a temporary set if cross-hairs over the map at the centerpoint of the zoom.
Remove the cross-hairs after the current zoom has finished.


## Design


Create a canvas element the same size as the map element, and layer it above with
the CSS rule { pointer-events: none } so the event handling of the map is not 
affected.  Draw 2 lines as cross-hairs when a map is zooming.  Advantage: implementing 
this is simple (see Mock-Up) and highly performant.

Drawbacks: On Mobile, when a pinch gesture is in progress, movement of touch points will cause 
simultaneous panning (movement) of the map. This would cause the cross-hairs to no 
longer be centered over the zoom point.  To correct the cross-hair location, either 
the cross-hairs would have to be redrawn when the map is being panned which zoomed, or
panning of the map can be temporarily disabled when zooming is in progress.

Since it is difficult to maintain a constant centerpoint position of the gesture when a 
pinch gesture is in progress, it is difficult to zoom in on an exact point.  Even 
without cross-hairs, it might be desirable to add an option to the api to prevent 
panning while a zoom is in progress.

### Mock-Up



Here is a mock-up of the design:

https://portfolio.stefanzero.com/mapbox/zoom/index.html

This works as expected on Desktop, since the map cannot be panned when a mousewheel 
zoom is in progress.  On iOS, this Mock-up does not maintain the centerpoint correctly 
since the map can be panned while a zoom is in progress.  On Android, the Mock-up works 
properly.

### Concepts


This should be added an option, with additional input parameters for size, color, width, and 
dash-style of the cross-hairs can be customized.  On the documentation page, add an 
iframe that displays a sample implementation,  so the user (programmer) can see it in action.


### Implementation



A quick mock-up of the JavaScript code can be seen by using Chrome Dev Tools to inspect this code:

https://portfolio.stefanzero.com/mapbox/zoom/index.html

A simple JavaScript function "drawCrossHairs" is added that draws cross-hairs.  Another function 
"debounceClearCanvas" is added that will clear the canvas after a debounce delay time.  For 
Desktop, a "wheel" event handler calls "drawCrossHairs" and then "debounceClearCanavas".  

The Mobile implementation is more difficult, since multiple gesture touch points control both 
the location of the cross-hairs and detection of when a zoom is in progress.  But the idea is
the same as for desktop: when a zoom is occurring, call "drawCrossHairs" followed by 
"debounceClearCanvas".  

The "Mock-up" code for Mobile was based on some sample code on MDN for pinch gestures, which does 
not work as well on iOS as on Android.  The iOS code will need a more complex design to correctly 
issues with determination of the cross-hair location.  On Android, the cross-hairs do move as the 
map is panned.

An edge case is when the pinch gesture is moved outside the map.  The current mapbox 
implementation allows the map to be zoomed even when the gesture moves beyond the boundary 
of the map.  In this case, the cross-hairs may also move beyond the boundaries of the map.

**Comment by mourner** [comment]
Thanks for the detailed suggestion! I think this is a good candidate for a third-party plugin, but not something we would want to pursue in the library core, so I'm inclined to close the issue.
