### ISSUE TITLE
Memory Leak on Safari

### ISSUE THREAD

**Issue by neore** [mapbox/mapbox-gl-js#8437]
**mapbox-gl-js version**: 1.1.0

**browser**: Safari 12.1.1 on Mojave

### Steps to Trigger Behavior

 1. Load test page : https://dev.geopeche.com/test.html
 2. Zoom and pan actively since a few time
 3. Safari say "High memory usage..."

On Safari iOS, the  page will be reload after memory leak.

### Link to Demonstration
https://dev.geopeche.com/test.html

### Expected Behavior
Don't use to many memory and don't crash...

### Actual Behavior
Memory usage increase dramatically during zoom and pan actions to exceed max.
On Safari Desktop : A message appears to inform user of high memory usage.
On Safari iOS : Page will be force to reload.
On Safari iOS in PWA : Page will be reload 2 times and refuse to reload after a last try.
On Chrome iOS : Page crash with "Aïe, Aïe, Aïe" message at first memory leak.

In Web Inspector, memory climbs to exceed 3Go...
<img width="1155" alt="Capture d’écran 2019-07-06 à 23 05 40" src="https://user-images.githubusercontent.com/15775949/60761225-83257080-a044-11e9-8f79-a937d0324efe.png">

**Comment by andrewharvey** [comment]
@neore is this the same as #8282 (which also stemmed from #4695)

**Comment by neore** [comment]
After others tests : 
- Chrome iOS v75.0 is affected too with "Aïe Aïe Aïe" error page or "Aw, Snap!" in English version.
- Firefox iOS v17.3 is affected too with force page reloading.

**Comment by asheemmamoowala** [comment]
@neore on iOS, all browsers use the underlying Apple Webkit implementation.

Closing as duplicate #8282.
