### ISSUE TITLE
Get data source (country-/ street labels) manually.

### ISSUE THREAD

**Issue by Pryotic** [mapbox/mapbox-gl-js#8438]
Hello,
I'm pretty new to using mapbox and after hours of search I didn't really come closer to a solution of my problem, so I'm gonna ask here.

I'm building an app, that is using map box. Although I'm not using the mapbox SDK but only the APIs, until now for loading Tiles. Country labels, street labels and other labels are visible on that Tiles, but only as a part of the image that the tiles are.
Now I need to draw all labels on the map manually. So I need to access the data source of the Map Box styles directly, for example get all country or street names and their position in a given area (the one the user is viewing).

I also thought that maybe, there is no point in doing that with a mapbox api, since the mapbox data comes from OpenStreetMaps, and I should maybe try to get the data directly from there. But I really couldn't figure out how to do it.. 

I'm not sure if that is the right place to ask, but I would really appreciate any help a lot!

**Comment by asheemmamoowala** [comment]
@pryotic this issue tracker is for bug reports and feature requests for the `mapbox-gl-js` SDK. For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). 


> Country labels, street labels and other labels are visible on that Tiles, but only as a part of the image that the tiles are.

You can use the [Vector Tiles API](https://docs.mapbox.com/api/maps/#retrieve-vector-tiles) to retrieve the underlying vector tiles and use a vector tile parsing library like [vector-tile-js](https://github.com/mapbox/vector-tile-js) to use its contents.
