### ISSUE TITLE
Line Width in Meters

### ISSUE THREAD

**Issue by 1Map** [mapbox/mapbox-gl-js#8439]
**mapbox-gl-js version**: Latest

### Question

Ho can I specify my line-width to be in meters?  I want, for example, my line-width to be 1 meter wide, not 1 pixel.

**Comment by andrewharvey** [comment]
I think the only way you can do this reliably is to convert to a polygon.

You can create a zoom function such that the line width doubles with each zoom, ensuring that the with is fixed to the ground, but due to the projection of the map you won't get it exactly 1m wide across different latitudes.

**Comment by mourner** [comment]
Seconding what Andrew said. Check out https://turfjs.org/docs/#buffer
