### ISSUE TITLE
Use eslint rules for padding-line-between-statements

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-js#8444]
Use the [`padding-line-between-statements`](https://eslint.org/docs/rules/padding-line-between-statements) rules in the `eslint` configuration to disallow extraneous newlines.

This will help clear styling issue from PRs as in https://github.com/mapbox/mapbox-gl-js/pull/8399#discussion_r299255259

**Comment by mourner** [comment]
I think you're looking for https://eslint.org/docs/rules/no-multiple-empty-lines instead.
