### ISSUE TITLE
esm dependency vunerability

### ISSUE THREAD

**Issue by tholman** [mapbox/mapbox-gl-js#8450]
Getting some github alerts while using this lib due to  `"esm": "~3.0.84",`

<img width="703" alt="Screen Shot 2019-07-09 at 4 34 33 PM" src="https://user-images.githubusercontent.com/794999/60921025-982e1980-a267-11e9-8f70-cf6e908ec752.png">

Do you think you could give them a bump?

**Comment by mourner** [comment]
Not at the moment, since newer versions completely break our setup. However, you can safely dismiss this warning because it doesn't affect users of GL JS in any way. `esm` is only used by contributors for running tests.

**Comment by woodhull** [comment]
In that case, could `esm` be moved to a devDependency?

**Comment by mourner** [comment]
Yes, we should probably do that. Previously it was moved for easier integration with `mapbox-gl-native` which reuses the GL JS shaders, but I think we can live with maintaining the same dependency there — it overweighs GitHub/NPM showing security warnings for projects using GL JS.
