### ISSUE TITLE
fill-extrusion-pattern not work on click event , a bug like #8273

### ISSUE THREAD

**Issue by longwind91** [mapbox/mapbox-gl-js#8460]
mapbox-gl-js version: 0.54.0

browser: chrome

Steps to Trigger Behavior
click map to excute setPaintProperty function, but it don't work, the property fill-extrusion-pattern not changed

Link to Demonstration
https://jsbin.com/rukoji/edit?html,css,js,output

Expected Behavior
change paint property, the fill-extrusion-pattern will be greenArrow

Actual Behavior
don't work, the fill-extrusion-pattern is still redArrow

**Comment by ryanhamley** [comment]
https://github.com/mapbox/mapbox-gl-js/issues/8273 is the previous bug report of a similar issue

**Comment by pathmapper** [comment]
The above linked jsbin demonstration uses `v1.0.0`.

With `v1.1.0` it works as expected (https://github.com/mapbox/mapbox-gl-js/pull/8289 is available since `v1.1.0-beta.1`) :
https://jsbin.com/ketaqimece/edit?html,css,js,output

**Comment by longwind91** [comment]
it can worsk with v1.1.0
