### ISSUE TITLE
Can't access sprite file by relative URL

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#8461]
**mapbox-gl-js version**: 1.1.0

I'm wanting to use a self-hosted sprite file, available at `/sprite@2x.json` and `/sprite@2x.png` on the domain where I'm hosting the site.

Putting this in my style file doesn't work:

```
            sprite: '/sprite'
```

> `Error: Unable to parse URL object`

These also fail: `sprite`, `http:///sprite`, `./sprite`.

Is there another way to achieve this, or are relative URLs just not supported for sprite files?

This is problematic because it makes deploying more work: I need code that detects whether running locally (`localhost:8080//...`) or on the deployed site, and now I also need to know the deployed site's URL.

**Comment by stevage** [comment]
Well, I guess this workaround works:

```
sprite: `${window.location}sprite`
```

**Comment by mourner** [comment]
We don't support relative URLs intentionally — see the discussion at #3636 and linked tickets.

**Comment by stevage** [comment]
Thanks for the context. Interesting rationale. Makes sense that a style file needs to work in contexts other than web, I guess.
