### ISSUE TITLE
clusterMaxZoom wrong behaviour for large zoom levels

### ISSUE THREAD

**Issue by hallo02** [mapbox/mapbox-gl-js#8464]
See: https://jsfiddle.net/5vyo1d7q/1/

Given:

- Two geoJson features with the same coordinates,
- A clusterMaxZoom property set to 20,
- and a maxZoom property set to 19

**What I expect:**
Seeing a cluster until the end of scrolling/zooming.

**What I actually see**
Seeing two individual points.

This is related to #2898

**Comment by mourner** [comment]
Add `maxzoom: 20` to the source. By default it's `18`, and `clusterMaxZoom` is capped by `maxzoom - 1`.

**Comment by strech345** [comment]
For me it looks that `clusterMaxZoom` must lower than `maxZoom` right? because i ve to set `maxzoom: 21` to show anyway clusters
