### ISSUE TITLE
start-docs heap out of memory

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#8475]
When I try to start-docs from publisher-production on Linux, I get a heap out of memory error and the server crashes.

```
 yarn run batfish start
yarn run v1.16.0
warning ../../package.json: No license field
$ mapbox-gl-js/node_modules/.bin/batfish start
[16:45:38 Batfish] Starting the development server.
[16:45:38 Batfish] Wait ...
[16:45:47 Batfish] Go!
[16:45:47 Batfish] Development server ready.
  > Access your site at http://localhost:8080/mapbox-gl-js/
  > Available externally at http://192.168.1.2:8080/mapbox-gl-js/
  > Compiled files are in _site
[16:45:47 Batfish] Webpack compiled in 7.7s

<--- Last few GCs --->

[17528:0xc03040]    39826 ms: Scavenge 1379.0 (1421.4) -> 1378.4 (1422.4) MB, 2.5 / 0.0 ms  (average mu = 0.277, current mu = 0.247) allocation failure 
[17528:0xc03040]    39830 ms: Scavenge 1379.2 (1422.4) -> 1378.6 (1422.9) MB, 2.6 / 0.0 ms  (average mu = 0.277, current mu = 0.247) allocation failure 
[17528:0xc03040]    39835 ms: Scavenge 1379.4 (1422.9) -> 1379.2 (1423.4) MB, 2.9 / 0.0 ms  (average mu = 0.277, current mu = 0.247) allocation failure 


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0xc7d24ed452b]
Security context: 0x1ee0cb7aede9 <JSObject>
    1: anymatch(aka anymatch) [0x2f6f69e0521] [mapbox-gl-js/node_modules/anymatch/index.js:~8] [pc=0xc7d261bc159](this=0x38a09a1025a9 <null>,criteria=0x147bd2e37209 <JSArray[1]>,value=0x03d2d3e02a09 <JSArray[2]>,returnIndex=0x38a09a1025d9 <undefined>,startIndex=0x38a09a1025d9 <undefined>,endIndex=0x38a09a1025d9 <undefined>)
    2: arguments ad...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

If I instead run this with `--max_old_space_size=4096` then it works without issue:

> node --max_old_space_size=4096 ./node_modules/.bin/batfish start

> node --version
v10.15.2

From Debian unstable.

Is anyone else running into this issue, should we change the package.json to default to a larger max_old_space_size, or add a note to CONTRIBUTING?

**Comment by asheemmamoowala** [comment]
@vakila You were seeing this on your linux machine too, right?

Updating the docs and adding `NODE_OPTIONS` to the npm run command should make this easier.

I've also gone ahead and opened a batfish issue: https://github.com/mapbox/batfish/issues/311.

**Comment by vakila** [comment]
@asheemmamoowala yes I've run into this problem too - sometimes setting the max old space size has fixed it, and sometimes it hasn't - it seems there is another issue with a batfish process getting orphaned somehow. I haven't had time to dig into it enough to track down that issue & file a ticket, will try to do that the next time I run into it.
