### ISSUE TITLE
Vector tile line rendering regression

### ISSUE THREAD

**Issue by jkoelewijn** [mapbox/mapbox-gl-js#8477]
After upgrading from version 1.0.0 to 1.1.0 we experienced a rendering regression while rendering lines from a vector tile. See screenshot below for comparison between the two versions. An extra almost vertical line is rendered that should not be there.

In #2854 a similar issue has been posted, but in our case we _don't_ get the warning `Geometry exceeds allowed extent`.

**mapbox-gl-js version**: 1.1.0

**browser**: latest Chrome, latest Firefox, latest Edge and latest Internet Explorer

### Screenshot

![Screenshot of rendering with two versions](https://jkoelewijn.github.io/issues/mapbox/mapbox-gl-js/line-rendering-regression/screenshot.png)

### Steps to trigger behavior

1. Visit https://jkoelewijn.github.io/issues/mapbox/mapbox-gl-js/line-rendering-regression/mapbox-gl-js-1.1.0.htm.
2. Observe that an extra almost vertical line is rendered compared to https://jkoelewijn.github.io/issues/mapbox/mapbox-gl-js/line-rendering-regression/mapbox-gl-js-1.0.0.htm.

### Source code of example

https://github.com/jkoelewijn/jkoelewijn.github.io/tree/master/issues/mapbox/mapbox-gl-js/line-rendering-regression

**Comment by mourner** [comment]
Confirmed. Bisected to #8306. Investigating.

**Comment by mourner** [comment]
So, the artifact is expected after #8306 — geometry for that feature indeed exceeds allowed extent. Now we need to investigate why there's no warning about it.

**Comment by mourner** [comment]
Fix for both the warning and the artifact pending at #8306.
