### ISSUE TITLE
Load fonts only once.

### ISSUE THREAD

**Issue by ktherage** [mapbox/mapbox-gl-js#8483]
**mapbox-gl-js version**: latest

**browser**: all

### Steps to Trigger Behavior

 1. create a least two containers for maps
 2. load the page

### Link to Demonstration

https://jsbin.com/nibifonoxa

### Expected Behavior

Common fonts shall be downloaded once and shared between maps.

### Actual Behavior

Common fonts are downloaded each times that a map is loaded.

**Comment by andrewharvey** [comment]
it looks like you've missed filling out the issue template, could you fill it out please, or provide more detail on the issue or feature? thanks

**Comment by ktherage** [comment]
@andrewharvey yeah, i missed click. i've updated, issue.

**Comment by mourner** [comment]
I don't think we should do any special caching of font data by URL, because it's redundant — browsers do it natively. If you uncheck "Disable cache" in DevTools when exploring the Network tab, you can see that font requests are properly fetched from cache.

**Comment by ktherage** [comment]
@mourner , i'm sorry but i've unchecked "disable cache" and i'm still getting this behaviour (see GIF bellow). There is maybe  something i'am not understanding, i this case can you explain it to me.

![Peek 19-07-2019 12-02](https://user-images.githubusercontent.com/35264408/61527711-5fd3cb80-aa1d-11e9-9fb5-1f6a743b5d28.gif)

**Comment by andrewharvey** [comment]
> @mourner , i'm sorry but i've unchecked "disable cache" and i'm still getting this behaviour (see GIF bellow). There is maybe something i'am not understanding, i this case can you explain it to me.

It looks like you're talking about the Mapox telemetry calls, not fonts... Is that right?

**Comment by ktherage** [comment]
@andrewharvey I don't know, the only thing i see (and what i show in the GIF). Is that i see fetch calls about fonts (follow the mouse :wink:).

**Comment by asheemmamoowala** [comment]
@ktherage each of the font requests is for a different font (weight). The Mapbox Streets 11 style uses multiple weights of the `DIN Offc Pro` font.
![Screen Shot 2019-07-19 at 12 20 46 PM](https://user-images.githubusercontent.com/11619675/61560000-e5f11180-aa1f-11e9-9ed4-ab90dc5a22dd.png)

**Comment by mourner** [comment]
@ktherage it says "disk cache" for the font request entries in your GIF.

**Comment by ktherage** [comment]
well, anyways it is disturbing for me to see fetch calls getting fired when in fact their is cache.
This makes the browser getting slower.
But well, i'll see to rework my feature as it seems unmakeable.

Thanks for helping.

Have a nice day.
