### ISSUE TITLE
remove google analytics cookie

### ISSUE THREAD

**Issue by DMamak** [mapbox/mapbox-gl-js#8485]
Hello,
        I noticed today that mabox adds _ga cookie which is google analytics. I was planning on using mapbox for the website I'm working on but that cookie braches the cookie policy of the website. is there a way to remove/ not generate that cookie ? 

Kind Regards

**Comment by mourner** [comment]
Mapbox GL JS does not add any cookies. This is likely a problem with your website specifically, and isn't related to Mapbox.

**Comment by petergoes** [comment]
I have the same issue. From what I can tell, Mapbox is setting a `_ga` cookie. 

![mapbox-cookie](https://user-images.githubusercontent.com/642489/68123454-3d52b900-ff0d-11e9-8276-c78314a1c0af.png)


We don't have any google analytics implemented, and the domain is .mapbopx.com. Do I miss something?

**Comment by mourner** [comment]
@petergoes it's likely set by the https://www.mapbox.com/ website, not the library.

**Comment by petergoes** [comment]
@mourner Thanks for the response

**Comment by KesselRun-xyz** [comment]
Exactly. The cookies you see there were set when you visited www.mapbox.com.
If you close all the browser tabs to www.mapbox.com and clear the cookies, your should be able to confirm from browser dev tools that hose are not set

**Comment by maxstrebel** [comment]
Sorry, but I got the same issue. They get added without visiting mapbox.com. As soon as the map is shown in the client, a cookie from mapbox.com is set.
