### ISSUE TITLE
Marker popups don't work when marker is draggable

### ISSUE THREAD

**Issue by mkoos** [mapbox/mapbox-gl-js#8492]
I'm trying to have a marker that is draggable and has a function that fires `.on('dragend', onDragEnd)`, but that also has a popup when simply clicked on. The popup works as long as the marker is `.setDraggable(false)`. As soon as the marker is set `.setDraggable(true)`, then `.on('dragend', onDragEnd)` fires, but the popup doesn't display.

**mapbox-gl-js version**: 1.1

**browser**: Chrome

### Steps to Trigger Behavior

 1. Add marker
 2. .setPopup()
 3. .setDraggable(true)

### Link to Demonstration
https://jsfiddle.net/oxLfvugt/1/

### Expected Behavior
When clicking the marker, a popup should appear.
### Actual Behavior
When clicking the marker, `marker.on('dragend', onDragEnd);` is triggered instead, with no popup.

**Comment by ryanhamley** [comment]
Your demonstration is working as expected for me. I can drag the marker and when I click the marker, I get a popup.
