### ISSUE TITLE
"query*Features" Feature doesn't return GeoJson Properties

### ISSUE THREAD

**Issue by po-trottier** [mapbox/mapbox-gl-js#8503]
Version : mapbox-gl-js v1.1.1 
Browser: Chrome (Also true for Firefox)

This is a big problem for me as I use "queryRenderedFeatures" to set the "mapbox.Popup" property as the following tutorial (https://docs.mapbox.com/help/tutorials/add-points-pt-3/).

The same issue also occurs for "querySourceFeatures"...

**Here are the steps I have taken:**

1. I created a new Style in the Mapbox Studio

2. I uploaded a valid GeoJson Tileset (It was successfully processes)

3. I added a Layer to my MapBox map Style that uses GeoJson Tilesets to display a big number of markers on the map

4. I added an "on('click' , e => {...})" event listener which runs "map.queryRenderedFeatures" for my specific layer on my client app. (I am using VueJS)

5. When I click on a marker, it is detected the layer properly, but the feature.properties object contains nothing but the "Icon" field I created.

6. This same "Icon" field is used in the Mapbox studio to determine which Icon to display at the given location (I used Data Conditions for the Icon of the marker). The "Icon" property is a simple string.

7. There are about 10 other properties including "Name" that are not sent back but that can be accessed on the Mapbox Studio GUI. They are also all strings or numbers.

8. When I add a dummy condition such as "Name => Exists" to set a specific icon in the Studio GUI, the Name property is sent back the the client and can be used...

**Comment by asheemmamoowala** [comment]
@po-trottier could you please provide a minimal reproduction of the bug on JSBin? That would help a lot in determining what is happening.

**Comment by po-trottier** [comment]
Here's a simple snippet that represents my use case:
https://jsbin.com/gawojadudo/edit?html,js,console,output

Since I'm working with Vue.JS there are some ES6 features that are being compiled to ES5 by Babel and I have the mapbox-gl package installed via NPM.

Here is another snippet that should work if a valid Access Key, Style and Layer Name are added:
https://jsbin.com/mamosucota/edit?html,js,console,output

The same issue occurs with the CDN version of Mapbox as with the node package.

**Comment by asheemmamoowala** [comment]
@po-trottier When using the `?optimize=true` URL query parameter with your style, the unreferenced feature properties are stripped off as part of the optimization. You can read more about it [here](https://docs.mapbox.com/api/maps/#vector-tiles) and [here](https://docs.mapbox.com/help/glossary/style-optimized-vector-tiles/)

**Comment by po-trottier** [comment]
That worked like expected! Thanks for your help.

**Comment by po-trottier** [comment]
@asheemmamoowala Actually, after removing `?optimize=true` from the style, I still have the same problem, it simply occurs at specific zoom levels. 

So by using the same code but not optimized, I can click on markers and get the GeoJson data properly when the zoom level is lower than 14 (1 to 13.9) but when the zoom level is >= 14 then I loose all GeoJson properties. (I got those values by using Mapbox Studio)

It almost seems as if this is happening because the street names in my area are loaded at that zoom level and it overflows the available memory.

One workaround for now would be to limit the max zoom to 13.9 but ideally I would like to be able to zoom in to level 14 without loosing all the data inside the markers.

**Comment by asheemmamoowala** [comment]
@po-trottier At this point, it seems like the issue is unrelated to the mapbox-gl-js library, but is an issue with the tiles that are being served. 
I would recommend that you [contact support](https://www.mapbox.com/contact/), where they can help with debugging your specific style and tilesets
