### ISSUE TITLE
how to change the name of city in the map to Chinese?

### ISSUE THREAD

**Issue by gavinyf** [mapbox/mapbox-gl-js#8505]
**mapbox-gl-js version**:

### Question

I want to change the language of map to Chinese, but after I follow the steps in the doc, the map just change the name of country but city and province ,so how to change the language of city in the map to Chinese. 

### Links to related documentation
https://docs.mapbox.com/help/troubleshooting/change-language/

**Comment by ryanhamley** [comment]
There's not enough information here for us to offer a concrete answer. You may just need to set the language on the `#city_label` field. However, I'd point out this note from the docs you linked:

> The `name_zh` field contains Mandarin using simplified Chinese characters for our custom label layers: `#country_label`, `#state_label`, and `#marine_label`. All other label layers are sourced from OpenStreetMap and may contain one of several dialects and either simplified or traditional Chinese characters in the `name_zh` field.

Note that `#city_label` is one layer that is sourced from OpenStreetMap. Some cities may have Chinese translations but many, especially outside of Chinese-speaking areas, likely won't. This happens with other languages such as Spanish as well. If you have your own data set with city names in Chinese, you could use that instead but instructions on how to set that up are outside the scope of this issue tracker. For more information or help on getting this working, please contact [Mapbox support](https://support.mapbox.com/hc/en-us). Thanks!
