### ISSUE TITLE
y-ordering over different layers for symbols

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#8509]
### Question
Like the picture shows, the rendering order for icons looks difficult at overlapping symbols of different layers.
Is there a possebility without merge these layers to handle the rendering order by y-distance?
![image](https://user-images.githubusercontent.com/7572377/61471971-dcb26700-a983-11e9-82a1-f292ef04e6dd.png)

**Comment by ryanhamley** [comment]
There's currently no way to change the render order of symbols across layers. That would require some pretty significant changes to GL JS so it's unlikely it will happen any time soon, if at all.  The only way to get a particular layer to render under another layer is to add it to the map first. Within a layer, you can control render order with `symbol-sort-key` and `symbol-z-order`.
