### ISSUE TITLE
how can i use  fill-color,fill-pattern  expressions at the same time ? 

### ISSUE THREAD

**Issue by cdhuangyong** [mapbox/mapbox-gl-js#8514]
I want to set some features to use fill-color by expression, and some features use fill-pattern

the fill layer, when I use expressions to determine the style of the face, fill-color, fill-pattern will be abnormal, like this:

map.setPaintProperty("layerId","fill-pattern",
      ["case",["==",1,["get","num"]],"imageId", ["literal",null] ]
);
map.setPaintProperty("layerId","fill-color",
      ["case",["==",2,["get","num"]], "red" , "black" ]
)

browser will throw errors:  Expected string but found null instead;

**Comment by cdhuangyong** [comment]
By the way, can you speak Chinese? Can I use Chinese next time?

**Comment by cdhuangyong** [comment]
我解决了！ 如果fill-pattern使用表达式，当表达式的值为null，我就自己创建画布去画一个纯色的图片代替

**Comment by cdhuangyong** [comment]
I solved it! If fill-pattern uses an expression, when the value of the expression is null, I create my own canvas to draw a solid-color picture instead.

**Comment by ryanhamley** [comment]
Glad you figured out a solution @cdhuangyong

**Comment by hannawalter** [comment]
So I'm having the same issue -- I see the documentation says that `fill-pattern` will remove `fill-color` but I wish we could either set `fill-pattern` to null, and have the color come through, or set both (e.g. a transparent pattern on top of a fill)

**Comment by thejasonxie** [comment]
Just had this same issue of using fill-pattern and fill-color together. 

I was able to achieve this by just using fill-pattern with an image that's filled with a solid color by using the match expression `'match', ['get', 'propertytype']` for pattern-fill to determine whether to use a pattern image or a solid color image based on the object's 'propertytype'

**Comment by movahhedi** [comment]
```ts
export async function LoadSvgAsImage({
	svgDataUri,
	height,
	width,
}: {
	height?: number | undefined;
	svgDataUri: string;
	width?: number | undefined;
}) {
	return new Promise<HTMLImageElement>((resolve) => {
		const image = new Image(width, height);
		image.onload = () => {
			// map.addImage("hello", img);
			resolve(image);
			image.remove();
		};
		image.src = svgDataUri;
	});
}

export async function LoadSvgAsImageInMap({
	svgDataUri,
	height,
	width,
	map,
	id,
}: {
	height?: number | undefined;
	id: string;
	map: MapLibreMap;
	svgDataUri: string;
	width?: number | undefined;
}) {
	if (map.hasImage(id)) {
		return;
	}
	const image = await LoadSvgAsImage({ svgDataUri, height, width });
	map.addImage(id, image);
}

export function GenerateSolidColorSvg(fillColor: string): string {
	// For solid colors (no pattern), generate a simple solid color SVG
	const svgSize = 100;
	return `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="${svgSize}" height="${svgSize}" viewBox="0 0 ${svgSize} ${svgSize}">
            <rect width="${svgSize}" height="${svgSize}" fill="${fillColor}"/>
        </svg>`.replace(/#/g, "%23");
}
```

```ts
const patternSvg = GenerateSolidColorSvg("#ff0000")

// Load the SVG as an image in the map
await LoadSvgAsImageInMap({
	id: patternId,
	map,
	svgDataUri: patternSvg,
});
```
