### ISSUE TITLE
Expression for undefined feature-state value

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#8525]
I can't find a nice way to implement "If there is no feature-state value "X" then ...".

For properties, there is `["has", "X"]`.

The best I have found is:

`["==", ["coalesce", ["get", "X"], -1], -1]`

Is there a better way? Should there be?

**Comment by asheemmamoowala** [comment]
The [`coalesce`](https://docs.mapbox.com/mapbox-gl-js/style-spec/#expressions-coalesce) expression is the right way to do this. It is the suggested way to implement fallbacks in cases like this.

> Is there a better way? Should there be?

The type assert expressions (`to-number`, `boolean`, `string`, etc.) allow providing fallbacks within the same expression, but in the case of `feature-state` it would not make sense. 
```
['feature-state', 'X', 'YZ', ['feature-state', 'Y', 'ZZ']]
```
You can see that it would not be clear if `YZ` and `ZZ` should refer to fallback values, or fallback keys. And if it represented fallback values, then you would end up with nested `feature-state` expressions. `coalesce` seems the better solution for this.
