### ISSUE TITLE
Indicate node version support in package.json

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-js#8528]
The npm `package.json` (and yarn) both support the [`engine`](https://docs.npmjs.com/files/package.json#engines) field to indicate supported versions of Node.

Use this field to indicate what node versions are supported for this project.

cc @ahk

**Comment by mourner** [comment]
I think we shouldn't. The `engines` field is meant primarily for Node packages, where installing one as a dependency with an unsupported Node version means you can't use it. In our case, even if we, say, switch to Node v12+ for GL JS development, we still want to allow users on Node of any version (including older ones) to install `mapbox-gl-js` as a dependency for bundling, regardless of development requirements of `mapbox-gl-js` for contributors.

**Comment by mourner** [comment]
We should definitely update instructions in [CONTRIBUTING.md](https://github.com/mapbox/mapbox-gl-js/blob/master/CONTRIBUTING.md) though — they're definitely very outdated (mentioning Node v4 etc.) 😅

**Comment by ahk** [comment]
It's frustrating that there is no equivalent of "engines" for the `dev` side of a `package.json`. I guess this is complicated by the fact that our project runs in three environments: Browser as library, Node.js as library (rare), and Node.js as contributor. There is no way to configure these environments separately. This seems especially troubling for the web usage where users are basically left with "It should work in a browser". I'm still a little sad that we don't have some kind of support within `package.json` for the (now deprecated) `bower` use case (pre-built web browser libraries served via NPM and possibly re-buildable with node build tools).

**Comment by jingsam** [comment]
Unifying node version is useful for the consistency of develop environment. I think it's OK to set `engines` field in `package.json`. As npm states:
> this field is advisory only and will only produce warnings when your package is installed as a dependency.

So if developers install `mapbox-gl-js` in older node, it will functional well with some advisory warnings. That means `mapbox-gl-js` will work on this node but not the best one.

Note that current setting is `>=6.4.0`, I think it would be better to use node 8.

**Comment by asheemmamoowala** [comment]
> Note that current setting is >=6.4.0, I think it would be better to use node 8.

I should've looked to see if it exists already. This ticket resulted from anecdotal mentions that v10+ doesn't work with the project. I'll update the `engines` field if clear min/max node version constraints exist.

**Comment by mourner** [comment]
> anecdotal mentions that v10+ doesn't work with the project

I used v10 for the last year while developing GL JS without issues. v12 also works without problems after #8443.

> So if developers install mapbox-gl-js in older node, it will functional well with some advisory warnings. 

These warnings can be both confusing and annoying if the `engines` range is too specific. I'm good with setting >=8 because v6 reached end of life anyway, but not more specific that that.

**Comment by asheemmamoowala** [comment]
> I used v10 for the last year while developing GL JS without issues. v12 also works without problems after #8443.

👍  I upgraded to `v10.16.0` today, but had to rebuild `headless-gl`. It wasn't trivial to figure out. Finally worked by upgrading to the latest yarn (`1.17.3`) which includes a [fix](https://github.com/yarnpkg/yarn/pull/4750) to rebuild native modules when the node version has changed.

**Comment by mourner** [comment]
> So if developers install mapbox-gl-js in older node, it will functional well with some advisory warnings.

Also not all clients follow the "advisory" comment. E.g. Yarn throws an error unless you specify `--ignore-engines`:

```
error mapbox-gl@1.1.1: The engine "node" is incompatible with this module. Expected version ">=8.16.0".
error Found incompatible module
```

**Comment by asheemmamoowala** [comment]
>These warnings can be both confusing and annoying if the engines range is too specific. I'm good with setting >=8 because v6 reached end of life anyway, but not more specific that that.

Are you suggesting >=8, but not specifying the minor version?

> Yarn throws an error unless you specify `--ignore-engines`

Since our project is setup with yarn, I wonder if it even makes sense then to commit a change that forces users of this project to upgrade to node 8?

**Comment by mourner** [comment]
> Are you suggesting >=8, but not specifying the minor version?

I guess we could specify a minor one too, but I think major is enough. We should definitely avoid `<=` specifiers though.

> Since our project is setup with yarn, I wonder if it even makes sense then to commit a change that forces users of this project to upgrade to node 8?

BTW Yarn itself [requires ">= 4.0.0"](https://github.com/yarnpkg/yarn/blob/master/package.json#L107), so it's quite slack.

**Comment by asheemmamoowala** [comment]
Given that `engines` is already listed in the `package.json` file, the the hard error from yarn when using an unsupported node version, and that node v6 still works with existing dependencies, Im inclined to close this out as not needing and changes.
