### ISSUE TITLE
Rendering issues: water pattern being applied on solid ground

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#853]
Hello,

I just noticed a weird rendering bug in some areas while generating my own tiles (some lines would just not render at all, mostly tertiary roads) but while testing on the official examples in that area, I noticed a bug with mapbox's tiles, that can be reproduced in the official examples.

I made a jsfiddle for it (forked from someone else's, the JS files is recent enough and it can be reproduced in mapbox examples as well):
http://jsfiddle.net/fnicollet/vd41bs4j/

Here is the result:
![image](https://cloud.githubusercontent.com/assets/1240481/5209039/54746886-75ba-11e4-914d-99efb56c3cca.png)

Here is the same aread on OSM:
http://www.openstreetmap.org/way/277075992#map=17/45.9536/5.1767

If you pan up, you will noticed that the tile column also has this strange water pattern applied to it until a certain point.
There are multiple lakes in the area on the left but no water in the column. Strange thing, it also disappears when you unzoom.
It can also be reproduced at these coodinates: 45.9677,4.8500 and in other areas (always at zoom 15) of the map, which seem to have nothing in common

Do you know why this is happening? Is there something special in this area?

Thanks for your help!
Fabien

**Comment by ansis** [comment]
@fnicollet are you still able to reproduce this with master?

**Comment by lucaswoj** [comment]
(this was probably fixed by #2307)

**Comment by lucaswoj** [comment]
Please re-open if this wasn't fixed!

**Comment by fnicollet** [comment]
Yes i believe this can now be closed, thanks!
Le 23 mars 2016 22:54, "Lucas Wojciechowski" <notifications@github.com> a
écrit :
