### ISSUE TITLE
I drew a hollow polygon, how to make the hollow part transparent

### ISSUE THREAD

**Issue by LEAFER1994** [mapbox/mapbox-gl-js#8530]
code:
map.addLayer({
            "id": "mask",
            "type": "fill",
            "source": {
              "type": "geojson",
              "data": {
            	  'type': 'Feature',
            	  'geometry': {
            		  'type': 'Polygon',
            		  'coordinates': [[[-360,90],[-360,-90],[360,-90],[360,90],[-360,90]],
            	                  [[-99.35,37.83],[-88.18,37.22],[-87.63, 33.28],[-99.37,33.63],[-99.35,37.83]]]
            	  }
              },
              "maxzoom":16
            },
            "paint": {
            	'fill-color': '#000000',
            	'fill-opacity': 1,
            	'fill-outline-color':'#FFFF00'
            }
		});

result:
![image](https://user-images.githubusercontent.com/45807526/61678990-4db49e80-ad37-11e9-914f-3390a992607c.png)

**Comment by asheemmamoowala** [comment]
@LEAFER1994 For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. 

You can either use a [`fill-color`](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-fill-fill-color) value with rgba components to separately affect the fill and the outline stroke.
