### ISSUE TITLE
Style specification version number used for root property

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#8533]
**style spec version**: 13.7.1

### Question

The [latest release version of the style spec](https://github.com/mapbox/mapbox-gl-js/releases/tag/style-spec%4013.7.1) is `13.7.1` but the version used for the required root property [version](https://docs.mapbox.com/mapbox-gl-js/style-spec/#root-version) must be `8`.

What's the reason for sticking with `8` for the root property?

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/style-spec/#root-version

https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/CHANGELOG.md

**Comment by mourner** [comment]
`13.7.1` is the version of the `style-spec` package. `8` is the version of the style specification format itself. We will bump this again when it's time to change the style format (regardless of specific layer types/properties).
