### ISSUE TITLE
wrong behavior when two layers have same text but different opacity

### ISSUE THREAD

**Issue by DMamak** [mapbox/mapbox-gl-js#8534]
I have two layers layer 1(id="points-labels",source="pin") and layer 2(id="updated-points-labels",source="updatedPin"), layer 1 has text-opacity of 1, layer 2 has text-opacity of 0.
Every 2 seconds there is transition where layer 1 opacity changes to 0 and layers 2 changes to 1.
If there is common text between these two layers(for example UK) and layer 1 is faded out and layer 2 is faded in then 'UK' is not visible(even though it should be), but if layer 1 is faded in and layer 2 is faded out then the text is visible.
the text not shared by the layers works fine.
if i change it that layer 2 has constant opacity of 0 and it never updates to 1 then common text to layer 1 is still faded out.

**Comment by mourner** [comment]
Please fill out the provided issue template fully, including a minimal live test case. Short text description isn't enough for us to diagnose the issue.

**Comment by DMamak** [comment]
Sorry I was gone abroad and didn't have time to update the issue. I managed to figure this out. Its not a bug but crossSourceCollisions was true and symbols on different layers collided.
