### ISSUE TITLE
Popup breaks in v1.1.1

### ISSUE THREAD

**Issue by Tanguyabel** [mapbox/mapbox-gl-js#8535]
Hi,
Migrating my code to mapbox-gl v1.1.1 have broken something with the `Popup`. I use dynamic calls to `setLngLat` to make it show up after it is first created and added to the map. When I make such a call prior to any move (pan/zoom) on the map, an error occurs and the popup do not show up.

**mapbox-gl-js version**: 1.1.1

**browser**: all

### Steps to Trigger Behavior

 1. Create a map and add a popup to it
 2. Dynamically display the popup by calling `setLngLat` later on

### Link to Demonstration

https://codepen.io/anon/pen/jgWQYz

In this example we create a map, add a popup to it, then bind mouse over on the map to trigger the positioning of the popup. It is just a dummy way to show the popup for the purpose of this demo. Any other way to dynamically call `setLngLat` seems to give similar results.

### Expected Behavior

The popup should show up.

### Actual Behavior

Prior to any move (pan/zoom) on the map, the popup won't show up and the following error will be reported: TypeError: undefined is not an object (evaluating 'this._container.classList')

**Comment by mourner** [comment]
The regression likely got introduced in #7786 — @peterqliu want to take a look?

**Comment by peterqliu** [comment]
🚢
