### ISSUE TITLE
[docs] clarify browser compatibility for clearStorage api

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-js#8541]
The new [clearStorage API](https://docs.mapbox.com/mapbox-gl-js/api/#clearstorage) added in https://github.com/mapbox/mapbox-gl-js/pull/8363 is not supported on all browsers and only supported over HTTPS on some browsers. This info should be in our docs.

@ansis, is the following accurate and complete:
- clearStorage is not supported on Internet Explorer or Edge Mobile
- clearStorage works on iOS Safari as long as traffic is served over HTTPS
- clearStorage works on HTTP and HTTPS for all other major browsers

cc @asheemmamoowala @mourner

**Comment by asheemmamoowala** [comment]
~clearStorage works on iOS Safari as long as traffic is served over HTTPS~
~clearStorage works on HTTP and HTTPS for all other major browsers~

`clearStorage` works on browsers where the `Cache` API is available and enabled. This includes all major browsers when pages are served over `https://`. It excludes Internet Explorer and Edge Mobile.

**Comment by chloekraw** [comment]
👍 @asheemmamoowala . I didn't see guidance from our docs documentation or other API docs on the best way to format this entry. What do you think of the changes pushed to [this branch](https://github.com/mapbox/mapbox-gl-js/tree/clearstorage-api-compatibility)?


<img width="659" alt="Screen Shot 2019-07-25 at 10 00 20 AM" src="https://user-images.githubusercontent.com/34117059/61893494-078c4600-aec3-11e9-8273-280e7fac1d9c.png">

**Comment by asheemmamoowala** [comment]
@chloekraw This is a good enhancement, but it doesn't provide enough context to a developer of what storage this impacts, specifically because there is no documentation around how map resources are cached and stored. Maybe a lengthier explanation is needed over in: https://docs.mapbox.com/mapbox-gl-js/overview/
