### ISSUE TITLE
Running tests in-browser instead of node

### ISSUE THREAD

**Issue by arindam1993** [mapbox/mapbox-gl-js#8547]
## Motivation
Currently the unit and render test suites runs in node instead of within the browser, this has a number of drawbacks.
- Node-TAP needs to support and have separate tooling JS features we want to use for the browser (ES6, flow, TypeScript etc)
- Development and need for continued maintenance of mocks to simulate the browser environment in node(`headless-gl` and custom `window` mocks) and the inconsistencies that are created as a result.
- Ties gl-js code, which is intended for the browser, to node and a certain versions of it, instead of having just the build tooling ( `devDependencies` ) rely on node.
- Tests on CI are not run on the multitude of browsers that we support, increasing burden on manual testing post release.
- Tests are harder to debug and iterate on, the browser provides better tooling for this.
- The use of separate test frameworks for the various types of tests that we have.

## Design
- Use one test framework for writing tests, we currently use `tap` and can keep using that with `tape` which is a browser compatible version of the same.
- Build the test code with a similar build pipeline to that of the production build, and use a test-runner ( `testem` ) to deploy the built test file to multiple test browsers and collect test results.
 `testem` has a cool architecture wherein all it does it serve up the test file on a static page, this lets you run the tests in any browser, even remote ones including mobile devices.
It then captures the rest results on the page and ships it back to the server via websocket where it can be collected from multiple browser instances.

- Remove all the weird mocks and stubs and 🎉 

## Mock-Up
- Checkout the `devops/test-browserify` branch.
https://github.com/mapbox/mapbox-gl-js/compare/devops/test-browserify?expand=1
- `npm install testem -g`
- `node build/build-test.js`
- `testem`

This should build the `unit/ui` tests and run them in chrome, and report the results back to cli.

## Gotchas and TODO's
- `rollup` does not currently work with `tape` because of the way `tape` uses some specific commonjs syntax, we could submit a PR to `tape` to fix this.
- `tape` does not support `beforeEach` and `afterEach` , we could submit a PR to `tape` to add this as well.
- Some of our tests assume that they are running in node and use `fs`, we'd have to refactor those.

**Comment by mourner** [comment]
This is awesome, I would love for this to land!

> * `tape` does not support `beforeEach` and `afterEach` , we could submit a PR to `tape` to add this as well.

Note that `tape` doesn't support those by design, there were numerous issues about it which maintainers closed, and I generally agree with their reasoning (`tape`'s philosophy is to be as explicit and simple as possible). We could either wrap `tape` with our own flavor that adds these, or try getting rid of the hooks by explicitly calling setup/teardown code in each test that needs it.

**Comment by ahk** [comment]
Really happy about this effort and curious about some smaller points:

- Can anyone comment on the quality of the assertions, async support, and ability to isolate test runs with tape? I haven't used it before though it looks good.

- Does tape actually support the Safaris? I'm having a hard time understanding their support matrix. It looks on their README image like it doesn't, and if you click through to their CI report with their list of supported platforms and CI status, it looks like it only knows about Safari 6, but for example on my macbook I'm all the way on 12. It doesn't make sense to me that a library like this wouldn't support Safari (mobile or desktop) so I assume I'm just looking at the wrong information or misunderstanding it.

**Comment by arindam1993** [comment]
> Really happy about this effort and curious about some smaller points:
> 
> * Can anyone comment on the quality of the assertions, async support, and ability to isolate test runs with tape? I haven't used it before though it looks good.
> * Does tape actually support the Safaris? I'm having a hard time understanding their support matrix. It looks on their README image like it doesn't, and if you click through to their CI report with their list of supported platforms and CI status, it looks like it only knows about Safari 6, but for example on my macbook I'm all the way on 12. It doesn't make sense to me that a library like this wouldn't support Safari (mobile or desktop) so I assume I'm just looking at the wrong information or misunderstanding it.

I think the support is not super fancy, but it works and is minimal.

And regarding running in Safari, it does work, and its a function of `browserify`/`babel` to be able to build `tape` rather than `tape` itself.

**Comment by arindam1993** [comment]
@asheemmamoowala and I discussed this in-person a bit today, and we talked about trying to get the `render` and `query` tests to run in the browser. After having dug into the code around those I have some ideas on how to architect a solution for running the same in the browser.

I don't think this will be possible with a port, it'd be easier to re-write some of the code we have in `harness.js`, `server.js` and `suite_implementation.js` to use a test frameworks, we can keep using `tape` to stay consistent with our unit tests.

## Block diagram
```

                                                                   disk I/O
                                                                     ^     +
                                                                     |     |
                                                                     |     |
                   +---------------------+                   +-------------v-------+
                   |                     |                   |                     |
                   |                     |                   |                     |
                   |    testem           |              +--->+    file_manager     +<--------------+
                   |                     |              |    |                     |               |
                   |                     |              |    |                     |               |
                   +---------------------+              |    +---------------------+               |
                    ^                                   |                                          |
                    |                                   |                                          |
                    |                                   |                                          |
    node            |                                   |                                          |
  +------------------------------------------------------------------------------------------------------+
    browser         |                                   |                                          |
                    |                                   |                                          |
                    |                                   |GET                                       |
                    |                                   |style.json                                |
                    |                                   |expected query json                       |
                    |                                   |expected rendered image                   |
                    |                                   |                                          |
                    |               +--------------------------+                                   |
                    +--------------->                          |                                   |
           test results             |                          |                                   |
           over ws://               |   built test bundle.js   +-----------------------------------+
           (part of testem library) |                          |           POST
                                    |                          |           updated render images
                                    +--------------------------+           updated query json


```

## file_manager
This is a custom node mostly static server we'd have to write to handle all of the synchronous i/o in `harness.js`. This involves:
- process the `glob` on the folder and return a list of style json paths.
- pre-processing the test `style.json` 's and changing the url's to point to `localhost`
- static serve `mapbox-gl-styles` and `@mapbox/mvt-fixtures`
- static serve expected outputs ( images and query json's)
- when a result needs to be updated handle writing of the results back to disk via listening for POST's

## built bundle.js
This runs in the browser and is a `browserify`/`rollup` bundle. The entrypoint for this bundle would be a singular `tape` test that does the following would handle everything currently happening in `suite_implementation.js`, which involves, 
- get a list of tests to run from `file_manager`, then for each test:
  - request style and expected output from `file_manager`
  - create a map and run operations defined in the style
  - assert
  - teardown

`tape` + `testem` can handle the test reporting, instead of us having to write some custom code for it like we do now

**Comment by arindam1993** [comment]
A few updates and changes from the architecture described above:

- Instead of relying on the `file_manager`, a separate node-server to serve up test fixtures, I've switched to using a script that does some codegen and generates a json file with all the fixture data inlined into it, images get encoded as `base64` strings. The test suite can just `import` the fixture file and the build system will inline everything and make it available synchronously.
- This comes with the tradeoff that it really bloats the size of the bundle that needs to be deployed to the browser, for the query tests, its at a manageable 6 MiB, but for the render tests its a massive 105 MiB 😅 

Any thoughts on using this approach.

**Comment by asheemmamoowala** [comment]
> but for the render tests its a massive 105 MiB 😅

How long does it take to load a page/bundle of this size? Is there an advantage to doing it this way? Will this affect teh time/workflow for creating new render/query tests?

**Comment by arindam1993** [comment]
> > but for the render tests its a massive 105 MiB 😅
> 
> How long does it take to load a page/bundle of this size? Is there an advantage to doing it this way? Will this affect teh time/workflow for creating new render/query tests?

It doesnt really add to the bundling time since all a json import does is concat the file in.
Workflow wise it shouldn't effect anything much, the total build time is 6-7s right now.

The main place where this takes a hit is the initial load for the test page, when the script has to be downloaded, when the browser is on the same machine as the test server this is not an issue.
When running on ci we can minify to alleviate some of the bloat.

UPDATE:
A first version of the query tests running in the browser is now working, its on 
https://github.com/mapbox/mapbox-gl-js/compare/devops/test-browserify?expand=1

checkout and run 
`node -r esm test/query.browser.test.js` to start

**Comment by arindam1993** [comment]
Closing this issue and moving some of the discussion internally.
