### ISSUE TITLE
Switch to 6to5

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#855]
https://github.com/mapbox/mapbox-gl-online/issues/558 — we should probably do this here too.

**Comment by jfirebaugh** [comment]
Yeah, going to revert to es5. Tooling support for es6 in node is too premature.

**Comment by jfirebaugh** [comment]
Also, to answer "why not io.js" -- it doesn't yet support the ES6 features we use (arrow functions and object literal extensions).

**Comment by mourner** [comment]
Yes, sounds good.

**Comment by jfirebaugh** [comment]
Recording for posterity the reasons to switch back:

* There are no node debuggers that understand source maps, so breakpoints etc. don't work correctly.
* Couldn't get istanbul to work under traceur or 6to5.

**Comment by thejameskyle** [comment]
> Couldn't get istanbul to work under traceur or 6to5.

You can use [isparta](https://github.com/douglasduteil/isparta) as your instrumentor and it should work fine.

**Comment by mourner** [comment]
@jfirebaugh just wondering, did you try https://github.com/evanw/node-source-map-support?

**Comment by jfirebaugh** [comment]
Yes. It's only for exception stack traces though, doesn't help with debugging or code coverage.
