### ISSUE TITLE
Flickering of zoom control buttons on IE

### ISSUE THREAD

**Issue by kbauhausness** [mapbox/mapbox-gl-js#8551]
**mapbox-gl-js version**: v54.0

**browser**: IE11

### Steps to Trigger Behavior

1. Load any style's share URL (like this one for [Streets](https://api.mapbox.com/styles/v1/mapbox/streets-v11.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NDg1bDA1cjYzM280NHJ5NzlvNDMifQ.d6e-nNyBDtmQCVwVNivz7A#2/0/0)) in IE11 (I used browserstack), or initialize a map with GL JS including zoom control buttons
2. zoom in and out, and note that the zoom control buttons will become grayed out sporadically at various zoom levels

@vallendm noted:
>Looking into the history of the changes to navigation_control.js this change might have broken things
mapbox/mapbox-gl-js#8023

>The change uses the classlist object ( https://developer.mozilla.org/en-US/docs/Web/API/Element/classList ) and uses the toggle function which is supported in IE since v10. But IE doesn't support the 2 argument version of the function the above PR uses. This results in the button switching state rather than updating to the correct state.

### Link to Demonstration

see share URL above

### Expected Behavior
zoom control buttons should be greyed out if the zoom is either at max/min

### Actual Behavior
currently zoom control buttons can be greyed out at any zoom level and flicker as zoom level changes

cc @asheemmamoowala

**Comment by ryanhamley** [comment]
This was fixed in https://github.com/mapbox/mapbox-gl-js/pull/8495 and will be in the upcoming release
