### ISSUE TITLE
Restrict current location - maxBounds

### ISSUE THREAD

**Issue by ansarikhurshid786** [mapbox/mapbox-gl-js#8552]
mapbox team/community

I am using mapbox-gl-js to show map in my application using ionic3 framework. I want restrict region in map. I am using maxBounds. It is working as expected. 

When user click on current location then maxBounds restriction not working. How to apply maxBounds(restricted region) when user press current location?

**Comment by ryanhamley** [comment]
There is currently not a way to do this within GL JS. See https://github.com/mapbox/mapbox-gl-js/issues/4872 for some discussion. https://github.com/mapbox/mapbox-gl-js/issues/6789#issuecomment-396131712 presents a potential workaround. I'm going to close this to focus discussion in #4872
