### ISSUE TITLE
Switch to karma

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#856]
Once I finish [karma-tap](https://github.com/mapbox/karma-tap) we should do this - karma has better browser launcher support and a higher chance of hookins as a CI.

**Comment by jfirebaugh** [comment]
@tmcw Still want to do this?

**Comment by tmcw** [comment]
Nah, karma's a trainwreck. We should use [smokestack instead](https://github.com/hughsk/smokestack).

**Comment by jfirebaugh** [comment]
:+1: We can pick that up if we do another browser testing push.
