### ISSUE TITLE
IE11 does not support `Object.includes()`

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#8564]
[This PR](https://github.com/mapbox/mapbox-gl-js/pull/8466) introduces an `includes` method (https://github.com/mapbox/mapbox-gl-js/pull/8466/files#diff-3bdcadb35be47763a1abccc9707d22e0R181) that IE11 does not support.

**mapbox-gl-js version**: 1.2.0-beta.1

**browser**: IE11

### Steps to Trigger Behavior

 1. Errors on startup

**Comment by mourner** [comment]
Fixed by #8565
