### ISSUE TITLE
Is there any built in message functionality? 

### ISSUE THREAD

**Issue by benderlidze** [mapbox/mapbox-gl-js#8566]
Is there any built in message functionality?  I mean like in google maps over map 
![Screenshot_9](https://user-images.githubusercontent.com/8510813/61991949-4e637280-b060-11e9-9d32-f3830668a884.png)

**Comment by andrewharvey** [comment]
Can you just place your own text or HTML content over the map div on your own?

**Comment by mourner** [comment]
Yeah. We leave that to the discretion of downstream users.
