### ISSUE TITLE
How to give an MGLAnnotation feedback when tapped?

### ISSUE THREAD

**Issue by makinggainz** [mapbox/mapbox-gl-js#8567]
**mapbox-gl-js version**: latest as of writing

### Question

How to give an MGLAnnotation feedback when tapped?

### Links to related documentation:
1. https://docs.mapbox.com/ios/maps/examples/draggable-views/

When an annotation is tapped I would like for it to have some sort of feedback. (like a depression (width and height contract as seen on snapchat)).

I have tried doing this through gesture recognizers but I find that they dont seem to work as intended and also dont allow the didselect to run. So now I am trying to make it work using [this example on mapboxes website][1] where an annotation can be dragged.

 I only have 2 issues with this. 1: it seems to animate in a delayed fashion and 2 how can I prevent the annotation from being movable.

**Comment by andrewharvey** [comment]
This is the issue tracker for Mapbox GL JS (JavaScript SDK), the native (ios, linux, android, etc.) SDK issue tracker is at https://github.com/mapbox/mapbox-gl-native. So I'll close this issue here, feel free to post over at the mapbox-gl-native project.
