### ISSUE TITLE
Can we add actual svg on map in layer in map-icon

### ISSUE THREAD

**Issue by sanket1411** [mapbox/mapbox-gl-js#8568]
**mapbox-gl-js version**:

### Question

Have seen https://jsfiddle.net/Mourner/6vxm0roc/ example, but at higher zoom levels when the svg is converted to image the details are lost,as we are resizing the image.

Is there a sag to draw svg or do I need to convert it to image only.

Thanks.

**Comment by ryanhamley** [comment]
You can also try drawing the SVG directly into a canvas and place that canvas element as a [CanvasSource](https://docs.mapbox.com/mapbox-gl-js/api/#canvassource)
