### ISSUE TITLE
Use MapBpx GL JS without Access Token

### ISSUE THREAD

**Issue by Stophface** [mapbox/mapbox-gl-js#8569]
**mapbox-gl-js version**: 1.1.1

### Question
Is it possible to use `MapBox GL JS` without `Access Token`, when own Raster- or Vector Tiles are provided? This [library](https://github.com/uber/react-map-gl), providing `React Components` for `Mapbox GJ JS`, suggests that this is possible.

> Display Maps Without A Mapbox Token
> 
> It is possible to use the map component without the Mapbox service, if you use another tile source (for example, if you host your own map tiles). You will need a custom Mapbox GL style that points to your own vector tile source, and pass it to ReactMapGL using the mapStyle prop. This custom style must match the schema of your tile source. 

Source: https://uber.github.io/react-map-gl/#/Documentation/getting-started/about-mapbox-tokens

This feature further is provided in `React Native MapBox GL` since `v6`, see related [Issue](https://github.com/nitaliano/react-native-mapbox-gl/issues/630)

### Links to related documentation
https://docs.mapbox.com/help/glossary/access-token/

**Comment by mourner** [comment]
Yes, you only have to provide an access token if you use Mapbox vector tile servers.

**Comment by willemcape** [comment]
I believe this issue has resurfaced.

mapbox-gl-js version: 2.7.1

By sending a request that uses a non-mapbox tile source with simple geojson layers, I get the following error: 

```
Error: A valid Mapbox access token is required to use Mapbox GL JS. To create an account or a new access token, visit https://account.mapbox.com/
    at kt.errorCb (<anonymous>:36:477387)
    at kt.getSessionAPI (<anonymous>:31:20176)
    at Map._authenticate (<anonymous>:36:476982)
    at Map._render (<anonymous>:36:475802)
    at <anonymous>:36:480201
```

This error is thrown after the `idle` event is fired, so it is still possible to render a map, but after it is rendered this error is thrown.

**Comment by stepankuzmin** [comment]
Hi @willemcape,

A valid Mapbox access token is required to instantiate a `Map` object in GL JS v2. Please refer to the [Migration guide to GL JS v2](https://docs.mapbox.com/mapbox-gl-js/guides/migrate-to-v2/).

**Comment by DoisKoh** [comment]
By the way... I presume this means it's not possible to use MapBox GL JS without an internet connection?

That would kill our consideration to have a MapBox GL JS frontend for low budget projects, and Atlas for bigger project stuff... we'd just have to pick a more flexible stack.

**Comment by jingsam** [comment]
> By the way... I presume this means it's not possible to use MapBox GL JS without an internet connection?
> 
> That would kill our consideration to have a MapBox GL JS frontend for low budget projects (e.g. with Geoserver or some other free WMS hosted on-prem), and MapBox GL JS + MapBox Atlas for bigger project stuff... we'd just have to pick a more flexible stack.

You can use mapbox-gl-js in offline environment by provide an invalid token, such as `pk.no-token`
