### ISSUE TITLE
add support for asset://

### ISSUE THREAD

**Issue by incanus** [mapbox/mapbox-gl-js#857]
Background in https://github.com/mapbox/mapbox-gl-native/issues/579. For web, these will likely be in a known, hosted place such as the current `http://mapbox.com/mapbox-gl-styles/...`.

**Comment by tmcw** [comment]
@incanus can you clarify that a little bit? Would asset:// fall-back to online assets after checking a local store?

**Comment by incanus** [comment]
Can't find the original ticket, but I think @kkaefer had expressed the idea that we remain consistent between platform styles so that they are interchangeable. I agree with that. 

The scheme could fall back; hadn't considered that. We can do whatever we like since we are creating the `asset://` scheme but the original intent is only local, since this can be counted on for bundled styles. 

On JS, maybe it could treat as a relative path, otherwise look in a defined place such as `/mapbox-gl-styles`?

**Comment by jfirebaugh** [comment]
I'm still not seeing a need for `asset://` URLs on the JS side. `mapbox://` URLs are serving us well.
