### ISSUE TITLE
Zoomed out map is out of view if the container is too small

### ISSUE THREAD

**Issue by gabrielmoncea** [mapbox/mapbox-gl-js#8570]
Hello. I created a minimap in order to show the user where the current viewport is on the base map. The minimap's container's width and height weren't a problem, until now when I need to show the whole world. Is there something I'm missing or this wasn't intended? Is there anything to do that I can help / fix this?

**mapbox-gl-js version**: 1.1.1

**browser**: Chrome/75.0.3770.142

### Steps to Trigger Behavior

 1. Create a project and display a map according to [docs](https://docs.mapbox.com/mapbox-gl-js/example/simple-map/)
 2. Change #map style to `{ width: 120px; height: 120px }`
 3. Set `zoom: 0`

### Link to Demonstration

https://jsbin.com/tusurut/1/edit?html,output

### Expected Behavior
I would be nice if the map can show the whole world on `zoom: 0`, no matter the container dimensions.

### Actual Behavior
It looks like minimum dimensions are aproximative `width: 520px` and `height: 400px`

**Comment by ryanhamley** [comment]
This is a known issue https://github.com/mapbox/mapbox-gl-js/issues/3055. We'd essentially need to handle negative zoom. I'm going to close this to focus discussion in the original ticket. Thanks!
