### ISSUE TITLE
NavigationControl - Compass icon is not rotating anymore

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#8579]
**mapbox-gl-js version**: v1.2.0

**browser**: Chrome/Firefox

### Steps to Trigger Behavior

 1. Map with map navigation controls 
`map.addControl(new mapboxgl.NavigationControl());`

 2. Rotate the map

### Link to Demonstration

https://docs.mapbox.com/mapbox-gl-js/example/navigation/

### Expected Behavior

The compass is rotating.

### Actual Behavior

There is only a very tiny shaking of the compass icon when the map is rotated.

Note: 
If the `visualizePitch` option introduced in https://github.com/mapbox/mapbox-gl-js/pull/8296 is used, the compass is rotating as expected: https://jsbin.com/xuwiguniti/1/edit?html,output

**Comment by peterqliu** [comment]
might be related to https://github.com/mapbox/mapbox-gl-js/pull/8296

**Comment by peterqliu** [comment]
culprit lies in this line, not being properly degree-ified from radians:

https://github.com/mapbox/mapbox-gl-js/blob/19e30229e1ebfc7406d62d3d3b402253af0d0b46/src/ui/control/navigation_control.js#L82

**Comment by peterqliu** [comment]
Separately, compass at max pitch looks tiny and not easily readable. Gonna try to size it up subtly based on pitch

![Screen Shot 2019-08-06 at 12 26 07 PM](https://user-images.githubusercontent.com/4551508/62571715-ecb4bc80-b846-11e9-9dbb-23862535239d.png)

**Comment by peterqliu** [comment]
🚢 https://github.com/mapbox/mapbox-gl-js/pull/8605
