### ISSUE TITLE
`line-gap-width` gap is too wide?

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#858]
Assigning the same value for `line-gap-width` in a road casing layer as the `line-width` value in a road layer should result in the casing being flush with the fill. Instead, it seems like there is a slight gap between the two:

e.g. 

![screen shot 2014-12-02 at 5 10 08 pm](https://cloud.githubusercontent.com/assets/5607844/5272900/61d04560-7a4f-11e4-962a-ff585bd4038c.png)
![screen shot 2014-12-02 at 5 10 19 pm](https://cloud.githubusercontent.com/assets/5607844/5272901/61d10e14-7a4f-11e4-911c-b5f11ec66b3b.png)

```
{
    "id": "road_street_casing",
    "type": "line",
    "source": "mapbox",
    "source-layer": "road",
    "filter": ["in", "class", "street", "street_limited"],
    "layout": {
      "line-join": "round",
      "line-cap": "round"
    },
    "paint": {
      "line-color": "@street_case",
      "line-width": "@street_casing_width",
      "line-gap-width": "@street_width"
    }
}, {
    "id": "road_street",
    "ref": "road_street_casing",
    "paint": {
      "line-color": "@street",
      "line-width": "@street_width"
    }
  },
```
The additional gap seems to stay consistent regardless of either the `line-gap-width` or `line-width` values. Possibly related to the antialiasing?

/cc @lbud @nickidlugash

**Comment by jfirebaugh** [comment]
Fixed in 359a576471e20373333cae80a5eccda95ee4cdc2.
