### ISSUE TITLE
Stacking polygons with fill-color and opacity doesn't darken overlapping fills

### ISSUE THREAD

**Issue by geografa** [mapbox/mapbox-gl-js#859]
When styling a polygon with overlaps, the fill-color and opacity remain the same:
![](https://cloud.githubusercontent.com/assets/3875803/5132732/617ffad2-70cd-11e4-947b-30baf0194bd2.png)

Expected results are similar to studio (CartoCSS): 
![](https://cloud.githubusercontent.com/assets/3875803/5132727/3d506d36-70cd-11e4-93fa-9c48ee649a56.png)

Live example:
http://jsfiddle.net/0npp5v9t/

**Comment by ansis** [comment]
To draw polygons, we current make a stencil of which pixels are within any polygon and which aren't. We then paint all pixels within the stencil once, so even if multiple polygons cover the same pixel the pixel will get coloured once.

When we switch to https://github.com/mapbox/mapbox-gl-js/pull/948 for drawing fills overlapping polygons will be drawn as expected. They should already be drawn this way in -native.

**Comment by nickidlugash** [comment]
@ansis is it possible to separate this out into a different property, per https://github.com/mapbox/mapbox-gl-style-spec/issues/273? Both are ways of declaring opacity are very useful.

**Comment by mourner** [comment]
This was fixed by #1606.

**Comment by cyrilchapon** [comment]
In 2018, is there a way to accomplish the first behavior ? As the second is the default, and no polygon-opacity is inside the style spec

**Comment by awulkan** [comment]
@cyrilchapon Hey, did you ever find a solution to this? I'm trying to solve the same problem since it would increase our performance for certain parts of the app.

**Comment by CramericaIndustries** [comment]
Have you found a solution @cyrilchapon @charlesxbai ? I would like to implement the same.

**Comment by charlesxbai** [comment]
@CramericaIndustries no I was unable to find a way to implement this. 
If I remember correctly, [maplibre.org](https://maplibre.org/) recently implemented this feature.

**Comment by CramericaIndustries** [comment]
@charlesxbai thanks! Unfortunately it does not appear in the change log.
[https://github.com/maplibre/maplibre-gl-js/blob/main/CHANGELOG.md](https://github.com/maplibre/maplibre-gl-js/blob/main/CHANGELOG.md)
