### ISSUE TITLE
Make hash configurable

### ISSUE THREAD

**Issue by SebCorbin** [mapbox/mapbox-gl-js#8596]
## Motivation

Hash option is a boolean, if we set it, we can't use `location.hash` for anything else other than the mapbox hash. It would be nice to implement a query parameter style, if defined, like `myurl.org/mymap#map=10.37/14.589/-61.0225&config=myotheroptions`.
This is useful for permalinks for application containing a configurable map of anything else actually.

## Design Alternatives

Add an optional (to prevent breaking change) `hashName` option, that if defined, make the hash a query parameter-styled string.

### Implementation

Add and document this option, modify `ui/hash.js` so that it replaces (if defined), only the `hashName` part of the map.

**Comment by asheemmamoowala** [comment]
@SebCorbin Thanks for the proposal. Would you be interested in implementing it as well? The changes should be limited to https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/hash.js and fairly isolated to test.

**Comment by SebCorbin** [comment]
Sure, I have a PR in progress, I think I'll drop the `hashName` in favor of a `hash` option that can be boolean or string. I see that you support IE11, so I may not use [URLSearchParams](https://caniuse.com/#search=URLSearchParams), right?

**Comment by andrewharvey** [comment]
Related to #7725. I like this approach to make it more flexible and let the developer choose the name they want to use.

**Comment by JesseWeinstein** [comment]
I'm very glad to see this -- please consider also allowing the named form as a *input only* alternative, ideally on by default. That way all maps using mapbox-gl will automatically be able to accept pasted-in URLs from OSM without barfing.

**Comment by andrewharvey** [comment]
was closed by #8603
