### ISSUE TITLE
Any default value for fill-pattern?

### ISSUE THREAD

**Issue by Haixiang6123** [mapbox/mapbox-gl-js#8606]
**mapbox-gl-js version**:

### Question
When I search for the usage of `fill-pattern`, I found this example: https://bl.ocks.org/malwoodsantoro/a47bd1a2106728ac915dee3a5d2bbb3a.
In the example, the `fill-pattern` value is `grarden-11`, so I am wondering if there are any kind of "default values" for `fill-pattern`? I did try to search the whole documentation, seems like it doesn't mention much about that.

### Links to related documentation

https://bl.ocks.org/malwoodsantoro/a47bd1a2106728ac915dee3a5d2bbb3a.

**Comment by asheemmamoowala** [comment]
@Haixiang6123 thanks for using mapbox-gl-js!

There is no default value for the `fill-pattern` property. For a fill layer, the default behavior is to fill with a single color, and the default value for `fill-color` is black(#000000). 

More information is available in the style spec docs at https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-fill-fill-pattern
