### ISSUE TITLE
Query line-color of clicked feature

### ISSUE THREAD

**Issue by bloigge** [mapbox/mapbox-gl-js#8607]
Is it possible to get the current line-color value (or any other property) of a feature which was queried using `queryRenderedFeatures`? I think of a method which evaluates the data-driven styling of the layer against the current feature?

Thats the data-driven styling for the line-color property:
`{"line-color":{"stops":[["NONE","#1f91ef"],["360","#00d150"]],"property":"projection","type":"categorical"}}`

**Comment by peterqliu** [comment]
A combination of `queryRenderedFeatures` and `getPaintProperty` will retrieve the value of the `line-color` property, but if the value is a data-driven style or an expression, there is no way to evaluate it within mbxgl.

But if it's a categorical data-driven rule like you have above, you can implement your own conditional logic by accessing the relevant property in the queried feature.

**Comment by asheemmamoowala** [comment]
This would be solved by https://github.com/mapbox/mapbox-gl-js/issues/8373
