### ISSUE TITLE
Map appears to zoom automatically after onSourceData receives data

### ISSUE THREAD

**Issue by vomc** [mapbox/mapbox-gl-js#8608]
Here I have my map loaded. You can see a blue geoJson polygon there. I then start zooming out. As soon as another feature comes in from my tileset, the map suddenly zooms in on a random location without me doing anything:

![mapboxZoomWithTiles](https://user-images.githubusercontent.com/78635/62690304-c6b92480-b9cc-11e9-9db5-32e2b341fe4a.gif)

**mapbox-gl-js version**: ^0.53.1

**browser**: Version 75.0.3770.100 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. You need a map connected to a tileset that contains a few geoJSON features
 2. Open the browser and begin zooming out
 3. Listen to `onSourceData` and console log it

You will notice that immediately when something comes in from `onSourceData` the map begins to zoom to some location all by itself. I assume it is perhaps trying to find a center between the already loaded items and for some reason begins to zoom to that location...

**Comment by peterqliu** [comment]
@vomc can you make a test case?

**Comment by vomc** [comment]
@peterqliu @mourner -- sorry about this, after further testing I realized this had to do with my own react/mapboxGL integration... closing
