### ISSUE TITLE
How to animate millions of points

### ISSUE THREAD

**Issue by grobins** [mapbox/mapbox-gl-js#8610]
Hi,

I have 50 million points that I have built tiles with using Tippecanoe with no feature dropping but adding clustering so a single point might represent many points at some levels.

I would like to animate these points as they represent vehicle trajectories through a day.  For each point, I have an epoch and the epoch of the next point which is around 10seconds later.

I have tried simply looping through all the epochs of that day and for each one querying the tiles that for points that have a location where the iterated epoch is between the current point epoch and the next epoch.  So it's finding the windows that overlap my queried time and displaying them.  This is the only way I could figure out how to 'animate' a large number of points.

But the results are choppy.  vehicles will move along the road, then drop off, and reappear elsewhere, despite having a contiguous dataset of points.

Ideally, I would use the animate line feature, but I am not sure how to tie that into the timeline of the day.  For each line, I would have a start time and end time, but the individual vertices along the line aren't reached in a linear fashion, the speed changes, so simplifying starting the animation at a particular time and running it through for each line isnt' going to work.  Also, there are millions of trips, so even though I can display them on the map using tiles, I'm not sure if they will be able to be animated.

Any suggestions or direction to examples would be appreciated.

**Comment by peterqliu** [comment]
[Custom layers](https://docs.mapbox.com/mapbox-gl-js/example/custom-style-layer/) would be your best bet to get that sort of performance.
