### ISSUE TITLE
[iOS] Update single feature in large existing source.

### ISSUE THREAD

**Issue by songyuyang0918** [mapbox/mapbox-gl-js#8619]
I found this feature in js, and I want to do the same in IOS.
![  ](https://user-images.githubusercontent.com/15685672/62855919-0d3cb500-bd26-11e9-8062-a40e503940c1.gif)

In my existing understanding, I felt that the process was extremely tedious. Adding and deleting points to mutilPolygon was terrifying to contemplate.
Is there any good way? Or a recommended plug-in?

**Comment by andrewharvey** [comment]
@songyuyang0918 This repo is for Mapbox GL JS only, the native SDK is over at https://github.com/mapbox/mapbox-gl-native/.

**Comment by songyuyang0918** [comment]
@andrewharvey  I don't understand what you mean. Can IOS SDK also implement type functions? Need I look it up in the document? Still not supported?

**Comment by peterqliu** [comment]
>I understand shape updates, but the process of implementing them is a challenge for me.

@songyuyang0918 this implementation would be specific to the platform, so I suggest cutting this ticket in the native repository.

**Comment by songyuyang0918** [comment]
I'm going to do something similar on IOS,
Now I have a question:
In iOS, how do you compute a central coordinate between two known latitude and longitude coordinates?
