### ISSUE TITLE
jagged line artifacts on extruded layers

### ISSUE THREAD

**Issue by alecf** [mapbox/mapbox-gl-js#8644]
**mapbox-gl-js version**: 1.2.1

**browser**: Chrome 76

### Steps to Trigger Behavior

 1. Load a polygon layer, extrude it using `fill-extrusion-height`
 2. Pan and zoom the map around
 3. See rendering artifacts

Specifically this is about the jagged edges of lines such as the vertical edge of this extrusion in this screenshot:
![image](https://user-images.githubusercontent.com/135340/63133094-6f8cf400-bf78-11e9-9985-07f2d1bad6cc.png)

This is an example of the `'paint'` property we're using for that exact rendering:
```json
{
    "fill-extrusion-color": {
        "property": "pop",
        "default": "transparent",
        "type": "interval",
        "stops": [
            [
                0,
                "rgb(187, 222, 251)"
            ],
            [
                2,
                "rgb(158, 197, 236)"
            ],
            [
                3,
                "rgb(129, 172, 221)"
            ],
            [
                4,
                "rgb(100, 147, 206)"
            ],
            [
                6,
                "rgb(71, 121, 191)"
            ],
            [
                7,
                "rgb(42, 96, 176)"
            ],
            [
                9,
                "rgb(13, 71, 161)"
            ]
        ]
    },
    "fill-extrusion-height": [
        "*",
        [
            "max",
            [
                "number",
                [
                    "get",
                    "pop"
                ]
            ],
            0
        ],
        1
    ],
    "fill-extrusion-opacity": 0.9
}
```

### Link to Demonstration

I will try to put one together, but I basically any extrusion demonstrates this.

Strangely, I cannot see these same artifacts on the 3d indoor mapping demo:
https://docs.mapbox.com/mapbox-gl-js/example/3d-extrusion-floorplan/
![image](https://user-images.githubusercontent.com/135340/63133152-b4188f80-bf78-11e9-9467-18068f9e528b.png)

### Expected Behavior

Smooth lines
### Actual Behavior

Jagged lines

**Comment by andrewharvey** [comment]
You'll want to use `antialias: true` as a Map option like in the example.
