### ISSUE TITLE
Satellite view removed existing layer(line or geojson) from street view 

### ISSUE THREAD

**Issue by Piruthivirajan** [mapbox/mapbox-gl-js#8646]
Satellite view removed an existing layer(line or geojson) from street view v-9

**mapbox-gl-js version**:

**browser**:

### Steps to Trigger Behavior

 1.street view
 2.draw line layer
 3.change to Satellite 

### Link to Demonstration

https://jsbin.com/

### Expected Behavior in Satellite 

![expected](https://user-images.githubusercontent.com/23399359/63176136-ffa76800-c062-11e9-99fd-f395388d9744.JPG)

**Comment by ryanhamley** [comment]
Layers and sources are per style. When you change the style, the new style does not know about the old style's sources and layers so they won't automatically reappear on the map. You'll need to add the line layer to the satellite style when you switch to it.

**Comment by Piruthivirajan** [comment]
Thanks for your response. Is there any shortcut to get already drew layers(Line or geojson), Then apply to satellite style?

**Comment by ryanhamley** [comment]
Not really. This is something you'll have to implement yourself however best works in your application. It's common to keep track of what layers have been added/are visible and then loop over them and add them again when the style changes.

**Comment by andrewharvey** [comment]
#4006 has some proposals and workarounds.
