### ISSUE TITLE
Support metadata property in geojson sources

### ISSUE THREAD

**Issue by nextstopsun** [mapbox/mapbox-gl-js#8647]
Metadata property works great in sources of all types except `geojson`. In case of `geojson` source I'm getting an error: 
```
unknown property "metadata"
```

Please allow adding this property to geojson sources. 
I'm using it to generate and manage layer tree within a style object and for other useful metadata.

**Comment by peterqliu** [comment]
To our knowledge, there's no `metadata` property for source objects of any type https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources . where have you seen the property used?

**Comment by asheemmamoowala** [comment]
Hi @nextstopsun ! Thanks for reaching out. As the team requested more information and we haven't heard back in over a month, we're going to close this out. If you want to reopen it, please:
- Include a link to a minimal demonstration of your code. We recommend using https://jsbin.com.
- Include links to the specific section(s) of the documentation where you would have expected to find an answer to this question.

Thank you!
