### ISSUE TITLE
flyTo is broken since v1.2

### ISSUE THREAD

**Issue by vanhumbeecka** [mapbox/mapbox-gl-js#8648]
**mapbox-gl-js version**: 1.2.1

**browser**:
After upgrading to 1.2.X, the whole 'flyTo' mechanism is broken. There is no standard 'smooth' transition anymore. Change happens instantly without 'flyTo'
Tested in: 
* FireFox 68.0.2 (64-bit) on MacOS
* Brave Version 0.67.125 Chromium: 76.0.3809.100 (Official Build) (64-bit)

Not only in my apps is the transition gone, also on the [official example](https://docs.mapbox.com/mapbox-gl-js/example/flyto/) page of Mapbox it is not working>

**I can confirm it DOES work in Version 1.1.1**
So the bug was introduced in v1.2

### Link to Demonstration
Even on the official example page, it is broken:
https://docs.mapbox.com/mapbox-gl-js/example/flyto/

### Expected Behavior
flyTo realy "flies" between points. There is no smooth transition now

### Actual Behavior
No smooth transition

**Comment by ryanhamley** [comment]
I cannot reproduce this behavior with either of the browsers you listed. I confirmed that I'm using those specific versions of the browsers and I tested the example page you linked. It works as expected.

**Comment by mourner** [comment]
@vanhumbeecka perhaps you have `prefers-reduced-motion` set in browser preferences? Mapbox GL JS respects it since v1.2.0: https://github.com/mapbox/mapbox-gl-js/pull/8494

**Comment by vanhumbeecka** [comment]
> @vanhumbeecka perhaps you have `prefers-reduced-motion` set in browser preferences? Mapbox GL JS respects it since v1.2.0: #8494

Hm, I never even knew of these preferences, but will try them out later today.
