### ISSUE TITLE
"line-dasharray" has some problems that cannot be rendered

### ISSUE THREAD

**Issue by cdhuangyong** [mapbox/mapbox-gl-js#8656]
**mapbox-gl-js version**: 1.20.0

**browser**: chrome  版本 70.0.3534.4（正式版本） （32 位）

### Steps to Trigger Behavior

 1 .Add a MultiPolygon geojson source
 2. Add a line layer
 3. Paint add “line-dasharray” style , The value is [10,8]

### Expected Behavior
When zoomed to a certain level, the dotted line is cropped or disappeared, but there is no problem with the solid line.
like this: 
(See https://github.com/cdhuangyong/issues/blob/master/mapbox-line-dasharray.png)

### Actual Behavior
If it is a dotted line
like this: 
(See https://github.com/cdhuangyong/issues/blob/master/mapbox-line-nodash.png)

**Comment by cdhuangyong** [comment]
I really want to find the cause of this problem, because I used another attribute "line-pattern"

**Comment by ryanhamley** [comment]
@cdhuangyong You're correct that `line-pattern` and `line-dasharray` are mutually exclusive. This is documented in the style spec as you can see below. Patterned and dashed lines are rendered with separate shaders so both properties cannot be applied to the same line.

<img width="796" alt="Screen Shot 2019-08-19 at 11 53 48 AM" src="https://user-images.githubusercontent.com/4523080/63291287-183c9b80-c278-11e9-8f08-80d6181d5b08.png">
