### ISSUE TITLE
How to add street names to layers ?

### ISSUE THREAD

**Issue by diafoirus** [mapbox/mapbox-gl-js#8658]
Hello guys!, 

After testing other JS viewers (Raster and vectors),  finally Mapbox GL JS  is the perfect fit for my personal project, but right know I can't figure out how to add street names to my current transport_layer.

I'm hosting my own maps (openstreetmaps dump + PostGIS + Tegola tile server), I can render my transport_layer, but I can't figure out how to add the street names to the rendered layer.

With the following code I could get some details about my geometry/path :

`      map.on('mousemove', function (e) {
        var features = map.queryRenderedFeatures(e.point);
        var json_data = JSON.stringify(features, null, 2);
        console.log(json_data);
      });`

and it's output is :

`[{
	"geometry": {
		"type": "LineString",
		"coordinates": [
			[
				-80.3170108795166,
				25.692488246511118
			],
			[
				-80.31707525253296,
				25.69407380723274
			],
			[
				-80.31709671020508,
				25.695523996725186
			],
			[
				-80.31713962554932,
				25.696297423899722
			],
			[
				-80.3172254562378,
				25.69850166378518
			],
			[
				-80.31726837158203,
				25.699990469389633
			],
			[
				-80.31728982925415,
				25.700531848629794
			],
			[
				-80.31737565994263,
				25.702774679254404
			]
		]
	},
	"type": "Feature",
	"properties": {
		"access": "",
		"service": "",
		"name": "Palmetto Expressway",
		"ref": "FL 826",
		"class": "highway",
		"type": "motorway",
		"tunnel": 0,
		"bridge": 0
	},
	"id": 38708863,
	"layer": {
		"id": "transport",
		"type": "line",
		"source": "zones",
		"source-layer": "transport_lines"
	},
	"source": "zones",
	"sourceLayer": "transport_lines",
	"state": {}
}]`

I see that the street name is available in properties->name, but I can't figure out how to add this name/information to each geometry/vector in my layer.

I attached my current proof implementation (html file)

[gis_mapboxgl_2.html.zip](https://github.com/mapbox/mapbox-gl-js/files/3516321/gis_mapboxgl_2.html.zip)

Thanks in advance for any help!

**Comment by mourner** [comment]
You need to add a new layer that references the lines with type=symbol and "text-field" set to `["get", "name"]`. Note that this is a place to report issues with GL JS, not for asking questions about the library — StackOverflow would be more suitable for this.
