### ISSUE TITLE
3rd Party External PBF Vector Source (doc & example?)

### ISSUE THREAD

**Issue by canadaka** [mapbox/mapbox-gl-js#866]
I am unable to get MVT/PBF vector tiles working from an external http:// source. I don't see any documentation or examples of this.

The sources docs page only mentions topoJSON and doens't actually give any info or example of using a 3rd party url: https://www.mapbox.com/mapbox-gl-style-spec/#sources

I created a very simple Style JSON file that includes:
```
"sources": {
    "trailforks": {
      "type": "vector",
      "url": "http://domain.com/{z}/{x}/{y}.pbf",
      "maxzoom": 15
    }
  },
```

Along with trying to specify a source in the JS
```
var test = new mapboxgl.Source({
        type: 'vector',
        url: 'http://domain.com/{z}/{x}/{y}.pbf'
    });
    map.addSource('test1', test);
```

Nothing loads and the Chrome console log has errors:
Line #5433
GET http://domain.com/%7Bz%7D/%7Bx%7D/%7By%7D.pbf net::ERR_NAME_NOT_RESOLVED
Line #2618
Uncaught #<XMLHttpRequestProgressEvent>

**Comment by timrobertson100** [comment]
Hi @canadaka - I hit the same issue as you on this. 

The call to load the tiles is executing this method: https://github.com/mapbox/mapbox-gl-js/blob/master/js/util/browser/ajax.js#L23

You might want to explore overloading that function to do what you want there?

**Comment by MajuSadagopan** [comment]
I'm hosting pbf tiles generated using tippecanoe on S3 and I can't seem to get tiles to render. The tiles seem to be loading but nothing renders.

I sometimes get this error when rendering but nothing outside of that.
(VM3578 mapbox-gl.js:501)

`map.addLayer({
        "id": "soils",
        "type": "fill",
        "source": {
            "type": "vector",
            "tiles": ["https://d2jyc3sz0j3f3j.cloudfront.net/soi151_vectortiles/{z}/{x}/{y}.pbf"],
        },
        "source-layer": "soi151_vectortiles",
        "paint": {
            "fill-color": "rgb(53, 175, 109)",
            "fill-outline-color": "rgb(53, 175, 109)"
        }
    });`

**Comment by dioslibre** [comment]
Hi @MajuSadagopan, did you find any solution?
