### ISSUE TITLE
mapbox-gl-plot

### ISSUE THREAD

**Issue by JerckyLY** [mapbox/mapbox-gl-js#8664]
**mapbox-gl-js version**:

### Question
Is there an article or demo about mapbox-plot?

**Comment by mourner** [comment]
No idea what this was about.

**Comment by JerckyLY** [comment]
It’s about plotting military operations on a map

**Comment by JerckyLY** [comment]
> No idea what this was about.

It’s about plotting military operations on a map

**Comment by JerckyLY** [comment]
> > No idea what this was about.
> 
> It’s about plotting military operations on a map
here:   https://ilocation.oschina.io/plot4ol3sample/

**Comment by mourner** [comment]
Still no clue what this is about. The link above is an OpenLayers 3 map and has nothing to do with Mapbox.
