### ISSUE TITLE
Filtering features in map view with addSource geojson?

### ISSUE THREAD

**Issue by Halvorny** [mapbox/mapbox-gl-js#8665]
Hi!

I was looking at this example https://docs.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/ .

and I was wondering if this is possible to achieve with GeoJSON through the addSource function? What happens to the GeoJSON when it is added in this manner. Does it turn into vector tiles as suggested in this comment: https://github.com/mapbox/mapbox-gl-js/issues/8350#issuecomment-501982259 ? Or is there any way to query the raw GeoJSON data after it has been added through addSource?

**Comment by mourner** [comment]
Please see [previous discussions about this](https://github.com/mapbox/mapbox-gl-js/issues?utf8=✓&q=is%3Aissue+is%3Aclosed+geojson+source+raw+data). Note that this repo's issues section is for reporting bugs and feature requests — StackOverflow would be a better place for questions.
