### ISSUE TITLE
Icon collision problem

### ISSUE THREAD

**Issue by xiaofsu** [mapbox/mapbox-gl-js#8668]
Hello,EveryOne.
When I use the mbtiles file.
I am trying to render more data to the map.
But I found that when the map is zoomed out, the dots become irregular.
And the point will automatically detect the collision and block other icons.
Before that, I confirmed that I had turned off collision detection, so it should be all displayed, but it is not all displayed, but shows the style shown in the figure.
![image](https://user-images.githubusercontent.com/46067472/63432571-fbf55600-c453-11e9-8d87-873b5f9b73e1.png)
![image](https://user-images.githubusercontent.com/46067472/63432782-61e1dd80-c454-11e9-9dbe-7f0d21bf9b42.png)
You can see that after I zoom in, the icons are displayed regularly.
![image](https://user-images.githubusercontent.com/46067472/63432590-00ba0a00-c454-11e9-8485-07710f574df7.png)
Is it a problem when I generate the mbtiles file, or is my property set incorrectly on my page?
I use tippecanoe to generate mbtiles.
thank you very much.
xiaoFsu.

**Comment by andrewharvey** [comment]
Very likely tippecanoe is dropping dense features, so I would guess it's not a GL JS issue. You can tweak that, it's documented in the README for tippecanoe.

You can check our mbtiles from tippecanoe with https://github.com/mapbox/mbview.
