### ISSUE TITLE
Will mapbox consider introduce sharp corners in glyphs

### ISSUE THREAD

**Issue by initialdmg** [mapbox/mapbox-gl-js#8675]
**mapbox-gl-js version**: v1.2.1

### Question

Now text drawing with SDF glyphs appears a little rounded, especially for CJK charactors. The text symbols seems weird exported using high PPI. I'd like to know if there's a plan to upgrade the glyph rendering method or shader?

**Comment by kkaefer** [comment]
Previous discussion around this topic: https://github.com/mapbox/mapbox-gl-native/issues/137

**Comment by initialdmg** [comment]
Closing this issue for there is a relating issue.
