### ISSUE TITLE
circle-sort-key/literal render test fails locally on macOS

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#8680]
@ahk `circle-sort-key/literal` render test (introduced in #8467) fails for me locally, apparently because of some minor precision differences that make the debug line shift by 1 pixel:

![image](https://user-images.githubusercontent.com/25395/63537744-2b24c980-c51f-11e9-872a-f4f93cdf587a.png)

@ahk could we remove `debug: true` from the test? Or maybe shift the center slightly to make it consistent across platforms?

**Comment by ahk** [comment]
Could it be helpful to just make the test pixel dimensions bigger? Ideally it's very obvious that cross-tile interaction is important in the test. Do you have any tips on how I can verify I made this test more robust?
