### ISSUE TITLE
Inverted polygon fill? (Polygon with hole) 

### ISSUE THREAD

**Issue by PuffedRiceCrackers** [mapbox/mapbox-gl-js#8686]
Is it possible to draw polygon with a hole?
I saw some threads about this on Android forum
but I couldn't find information on this on JS doc. 
This is a get around to only show specific city of which I have polygon coordinates,
so if anyone can direct me to instruction that can do this instead of inverted fill, I'd greatly appreciate that too!

**Comment by andrewharvey** [comment]
You can create a GeoJSON Polygon with a hole https://gist.github.com/andrewharvey/978590af4d5ebb1d0ed122da6ce7ebea
