### ISSUE TITLE
Integration with FullStory

### ISSUE THREAD

**Issue by GadyTal** [mapbox/mapbox-gl-js#8695]
**mapbox-gl-js version**: Latest

### Question
We’re using MapboxGL js, I’m trying to use Full-Story on my app.
FullStory doesn’t support canvas elements, and it looks like they support only map images.
They were able to resolve this issue on Google Maps by passing optimized:false to each marker initialization as an option.
See Google Maps solution here: https://help.fullstory.com/hc/en-us/articles/360020829413
Is there any solution to use MapBox and FullStory together?
Any ideas?  :man-juggling:
Links to related documentation: https://docs.mapbox.com/mapbox-gl-js/api/ (edited) 

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/api/ map options section

Map screenshot from FullStory:

![map](https://user-images.githubusercontent.com/22914916/63764611-e0fd6880-c8cf-11e9-8f31-c718e595bab2.png)

**Comment by mourner** [comment]
If it doesn't support Canvas, there's nothing we can do on GL JS side. You'll have to use something like https://docs.mapbox.com/help/glossary/static-images-api/
