### ISSUE TITLE
"line-join" doesn't work for a FeatureCollection of multiple LineString-s

### ISSUE THREAD

**Issue by NameFILIP** [mapbox/mapbox-gl-js#8698]
A simple use case of displaying a traffic line (a line with segments of different colors) is quite complicated. I am not able to achieve a smooth joining of the separate LineStrings. I tried `"line-join": "round"`, but it doesn't work. Is there a way to achieve that?

![image](https://user-images.githubusercontent.com/834796/63818237-fd5fcc00-c8f4-11e9-97a6-01a0dce946fd.png)

https://jsfiddle.net/NameFILIP/oLw1ysjm/21/

**Comment by kkaefer** [comment]
The lines in your example are separate, while `line-join` refers to how multiple segments within the _same_ line should be joined. To smooth over discontinuities between separate lines with coincident end points, you can use `"line-cap": "round"`.

**Comment by kkaefer** [comment]
https://docs.mapbox.com/mapbox-gl-js/example/line-gradient/ might get you some of the way there; but ultimately, Mapbox GL lacks the ability to associate properties per vertex or segment, it only supports properties on the geometry level. For that purpose, a `Feature` also is its distinct geometry, even if it's part of a `FeatureCollection`. If you have control over the geometry, you could e.g. add tiny slivers of lines that point towards the "next" point, which is what Google seems to be doing here.
