### ISSUE TITLE
Line width varies incorrectly in tilted views

### ISSUE THREAD

**Issue by sansumbrella** [mapbox/mapbox-gl-js#8699]
**mapbox-gl-js version**: 1.2.1

**browser**: Chrome, Firefox (latest)

### Steps to Trigger Behavior

 1. Draw a line on a map
 2. Tilt and rotate the map

### Link to Demonstration

[Sample Map](https://api.mapbox.com/styles/v1/david-wicks/cjzvc9h3p111f1cqsl83oligu.html?fresh=true&title=true&access_token=pk.eyJ1IjoiZGF2aWQtd2lja3MiLCJhIjoiY2p4NmcydTRvMDhlNTN5bzNjbWViZHZ0eCJ9.NoZ_wNuMVCZj0xQ3ZakqvQ)

### Expected Behavior
The lines have a consistent width.

### Actual Behavior
The lines along some angles are thinner than others. The line width also varies along its length.
![image](https://user-images.githubusercontent.com/81553/63862966-773a9880-c97b-11e9-97b8-80aa9c2ff1d1.png)
![image](https://user-images.githubusercontent.com/81553/63863106-ad781800-c97b-11e9-8a28-968591cd4998.png)

**Comment by mourner** [comment]
Can you elaborate on why you think this is not the expected behavior? Lines are aligned with the map plane, not the screen plane, so they are obviously distorted with perspective, varying appearance depending on the angle.

**Comment by mourner** [comment]
> The line appearance does not appear scaled based on distance from the camera

@sansumbrella this is not how perspective works. Try putting your phone on a table, looking at it from a side angle, and rotate it to see how the apparent width changes.

Here's my Kindle in the same spot but with two orientations. When oriented vertically, the apparent width is twice as big.

![photo_2019-08-28 21 01 19](https://user-images.githubusercontent.com/25395/63880773-06c16500-c9d7-11e9-8c41-96a0d9253e6e.jpeg)
![photo_2019-08-28 21 01 14](https://user-images.githubusercontent.com/25395/63880771-06c16500-c9d7-11e9-9f2c-007e96a1ef68.jpeg)
