### ISSUE TITLE
IE does not report render event after loaded event

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-js#8702]
Moving forward from https://github.com/mapbox/mapbox-gl-js/pull/8633#issuecomment-525824476
@mannnick24 reported: 

> I believe there is now a race condition related to `triggerRepaint` in the `map.render`
> 
> in map.js is this
> if (this._sourcesDirty || this._repaint || this._styleDirty || this._placementDirty) {
> this.triggerRepaint();
> } else if (!this.isMoving() && this.loaded()) {
> this.fire(new Event('idle'));
> }
> and I think the tiles may not have loaded, but sourcesDirty could be false,
> 
> anyhoo, on IE we may or may not get a render after the map reports loaded() our product always waits for a a render with the map loaded (if dataloading) so our viz hangs in IE
> 
> Here is a fiddle, that may or may not trigger the fitbounds in IE - chrome seems to always pass
> loadedrender.zip

Reproduction: https://jsbin.com/vovogurufe/edit?html,output

cc @kkaefer @kbauhausness

**Comment by juho-hanhimaki** [comment]
This was causing issues for us on IE so had to go back to v1.2.1.
