### ISSUE TITLE
cacheEntryPossiblyAdded: TypeError Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by javiergarciagonzalez** [mapbox/mapbox-gl-js#8705]
Hi!

Since we bumped this morning to v1.3.0, we are getting production error that says "Cannot read property 'send' of undefined".

This is happening in the method `cacheEntryPossiblyAdded` from the file `src/utils/tile_request_cache.js`.
This method receives a dispatcher and that dispatcher has a method `getActor()` that it's sometimes returning undefined. That causes the error in the title of this issue.

I couldn't reproduce it locally, but I hope this can ring the bell for you mapbox team.

**mapbox-gl-js version**: 1.3.0

**browser**: Chrome 71.0.3578

### Expected Behavior
Code doesn't give typeErrors
### Actual Behavior
It does when `dispatch.getActor()` returns undefined

**Comment by mourner** [comment]
Thanks for the report! We'll try to find a solution, but it will be hard without a reproducible test case — if you do get to reproduce locally eventually, let us know.

**Comment by ansis** [comment]
@javiergarciagonzalez how often are you seeing this error reported? is it a couple errors here and there or something most users are hitting?

Also, are you using `map.remove()`? Do you have any raster tile sources on your map?

**Comment by ansis** [comment]
I was able to reproduce this error with raster map found in `debug/satellite.html` when forcing a reload (`map.style._reloadSource('mapbox')`) shortly before removing it (`map.remove()`). I opened a fix for that here: https://github.com/mapbox/mapbox-gl-js/pull/8711

I don't really have a way of knowing if this is the exact issue you were seeing though.
