### ISSUE TITLE
flyTo documentation: minZoom vs curve

### ISSUE THREAD

**Issue by 1chandu** [mapbox/mapbox-gl-js#8712]
Question regarding `flyTo` docs :

https://github.com/mapbox/mapbox-gl-js/blob/9d5049e774d0b4cb1f82e2bcc9fbc1c1df901251/src/ui/camera.js#L801

As per above doc, `options.minZoom` is ignored when `options.curve` is specified, but looking at the [code](https://github.com/mapbox/mapbox-gl-js/blob/9d5049e774d0b4cb1f82e2bcc9fbc1c1df901251/src/ui/camera.js#L891), it looks the opposite, `curve` is ignored when `minZoom` is specified? is that right or am I missing something?

**Comment by arindam1993** [comment]
Hi @1chandu , thanks for pointing out the documentation inconsistency, I believe you are correct.

**Comment by 1chandu** [comment]
@arindam1993 , I also think as per the docs if `minZoom` is specified, `zoom` doesn't exceed `minZoom`, a quick test shows `minZoom` is not respected. Are there any unit tests you can point me to? Is this working as documented?

**Comment by mourner** [comment]
Related: #4953
