### ISSUE TITLE
How to: create an elevated map

### ISSUE THREAD

**Issue by DanieleSuppo73** [mapbox/mapbox-gl-js#8714]
I've discovered Mapbox with Unity, and the very first example create an elevated (3D) map with satellite imagery.
Now I'm using js, and the map is actually 2D.
How can I get the map in 3D?
Many thanks!

**Comment by ryanhamley** [comment]
Hi @DanieleSuppo73 thanks for using Mapbox. At this time, GL JS does not have true 3D support, but we hope to implement that in the future. I'm not sure what Mapbox Unity map you're referring to but GL JS does offer support for [hillshading](https://open.spotify.com/album/7rEjB7GCTH0KEtskbAkpgg?si=P4oG7MwbT7u1DQkdVIcIxA), [extruded buildings](https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/) and [polygons](https://docs.mapbox.com/mapbox-gl-js/example/3d-extrusion-floorplan/) and a custom layer API which allows for [complex 3D models and scenes](https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/). Hope this helps!

**Comment by DanieleSuppo73** [comment]
Hi @ryanhamley thanks for your reply,
I can confirm you that in Uity the very simple Mapbox demo scene the map has elevation:
1- download Unity Mapbox sdk 2.0
2- Import into Unity
3- Put your token in the window that open at startup
4- Load "ZoomableMap" scene
5- Press PLAY
6- Move around the globe. You will see that the map is elevated! Mountains are elevated, etc.

So, if this is possible through Unity, why can't it be possible through js?

**Comment by ryanhamley** [comment]
They are two different libraries that run in different environments and have different capabilities. The Unity SDK is built with Unity, a game engine built with 3D rendering as a primary purpose. GL JS is a Javascript library that enables web mapping. 3D is not baked into the web platform the same way it is in Unity so we have to do the hard work of implementing that functionality. It *is* possible to have 3D in GL JS and we plan to implement it in the future, but it hasn't happened yet.

**Comment by DanieleSuppo73** [comment]
I see, thanks!

**Comment by DanieleSuppo73** [comment]
Is there actually some work-around to get elevated maps within Mapbox (maybe with three.js)?

**Comment by ryanhamley** [comment]
You can use Three.js in our [Custom Layer Interface](https://docs.mapbox.com/mapbox-gl-js/api/#customlayerinterface) to implement a 3D model or scene. See the example I linked to above.

Note that this issue tracker is for reporting bugs and requesting features in GL JS. If you need general support on implementing a Custom Layer, I'd recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks!
