### ISSUE TITLE
SDK support section of fill-sort-key missing

### ISSUE THREAD

**Issue by asheemmamoowala** [mapbox/mapbox-gl-js#8715]
The Style spec documentation for [fill-sort-key](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-fill-fill-sort-key) does not list the correct supported version for GL-JS

![image](https://user-images.githubusercontent.com/11619675/64059805-1e841f00-cb78-11e9-865c-d8995d2da4dc.png)

This and other `-sort-key` properties were added in v1.2.0.

cc @ahk

**Comment by andrewharvey** [comment]
It would be nice to also clarify what this sorts only within the layer, or works across layers.
