### ISSUE TITLE
flyto on iPhone broken recently

### ISSUE THREAD

**Issue by dieterdreist** [mapbox/mapbox-gl-js#8716]
**mapbox-gl-js version**: recent versions including v1.3.0

**browser**:
mobile safari
### Steps to Trigger Behavior

var CameraTransform = map.cameraForBounds(bb, {	padding: padding });
CameraTransform.bearing = 0;
CameraTransform.pitch = 0;
CameraTransform.curve = 1.4;
CameraTransform.speed = 0.5;

map.flyTo(CameraTransform, { geolocateSource: true });

 1. the above code used to work (just tested my code with the v0.52.0 version and the same code works without modifications on iPhone), but is now broken since a few versions. No error is thrown, but rather than performing a flyTo, the map jumps. 
This only happens on iPhone, different browsers work as expected.

### Link to Demonstration

https://jsbin.com/

**Comment by kkaefer** [comment]
Could you please update the demo link with the correct URL?

**Comment by mourner** [comment]
Likely the same issue as https://github.com/mapbox/mapbox-gl-js/issues/8648#issuecomment-522428685

**Comment by dieterdreist** [comment]
You are correct, turning off the accessibility feature for „reduce the motion of the user interface including the parallax effect of icons“, it works like before. Is there a way to ignore the setting?
