### ISSUE TITLE
Directions Example Not Working on Internet Explorer

### ISSUE THREAD

**Issue by puremana** [mapbox/mapbox-gl-js#8717]
Since I have seen Mapbox GL JS is trying to cater towards IE too, I noticed the directions example located at https://docs.mapbox.com/help/tutorials/getting-started-directions-api/ doesn't work on Internet Explorer due to `req.responseType = 'json';` in

```javascript
var req = new XMLHttpRequest();
req.responseType = 'json';
req.open('GET', url, true);
  req.onload = function() {
  var data = req.response.routes[0];
  var route = data.geometry.coordinates;
```

This could be changed to
```javascript
var req = new XMLHttpRequest();
req.open('GET', url, true);
  req.onload = function() {
  var json = JSON.parse(req.response);
  var data = json.routes[0];
  var route = data.geometry.coordinates;
```
to work on IE.

Was going to change this myself but I couldn't see any repo that included the code for those docs. Thanks

**Comment by arindam1993** [comment]
Hi @puremana , thanks a lot for pointing this out. 🙌 

Unfortunately the `/help` pages are in an internal repo, so we can't accept external contributions, sorry :(
But we've captured this request in the issue tracker for that repo, and it should be fixed soon.

Closing this to prevent duplication.
