### ISSUE TITLE
rotation based on attribute

### ISSUE THREAD

**Issue by halset** [mapbox/mapbox-gl-js#873]
I have a ORIENTATION attribute in a feature that I want to use as the value to the "icon-rotate" attribute. Like this. 

"layout": {
      "icon-image": "triangle-12",
      "icon-rotation-alignment": "map",
      "icon-rotate": "{ORIENTATION}"
}

Is there a way to have a "Number" data type that is based on a attribute like the "String" data type does with {}? It does not seem to work for me now.

**Comment by andrewharvey** [comment]
For the benefit of anyone else who lands here you can now do this with dds identity function.

```
"icon-rotate": {
   "type": "identity",
   "property": "ORIENTATION"
}
```

Unfortunately although Mapbox Studio has DDS support now, it doesn't look like the identity function support is there yet :disappointed:

**Comment by AbrahamArun** [comment]
I see this issue as closed, but I still cant figure out how `Number` data type for tokens/attributes work. I have tried the following two ways, and they don't to work.

```javascript
      'text-rotate': {
         'type': 'identity',
         'property': 'rotation'
      },
```

```javascript
      'text-rotation': '{rotation}',
```

**Comment by andrewharvey** [comment]
@AbrahamArun From the example at https://github.com/mapbox/mapbox-gl-js/issues/873#issuecomment-303355598

If your property is named rotation then in your style you'll have:

```
"layout": {
   "icon-rotate": {
      "type": "identity",
      "property": "rotation"
   }
}
```

You shouldn't wrap it in braces like `{...}`.

**Comment by AbrahamArun** [comment]
@andrewharvey That is exactly what I have done. The `{rotation}` was just the 2nd method I tried, i.e., tokens.

**Comment by AbrahamArun** [comment]
And this I am trying for `text-rotate`

**Comment by andrewharvey** [comment]
@AbrahamArun Could you post a minimal jsbin example?

**Comment by AbrahamArun** [comment]
@andrewharvey This is how my style layer looks:

```javascript
{
    'id': 104,
    'type': 'symbol',
    'source': sourceId,
    'paint': {
      'text-color': black
    },
    'layout': {
      'icon-allow-overlap': true,
      'icon-ignore-placement': true,
      'text-field': '{price}',
      'text-rotate': {
         'type': 'identity',
         'property': 'rotation'
      },
      'text-max-width': 10,
      'text-allow-overlap': true,
      'text-ignore-placement': true,
      'text-justify': 'center',
      'text-size': {
          'base': 1,
          'stops': [[15, 2], [16.63, 8], [18, 20], [19, 40]]
      }
      ,'text-offset':[0,-0.1]
    },
  };
```

Is the right way to do it?

**Comment by MartinHerich** [comment]
Any solution to this? I have the same problem.
"layout": {
                "visibility": "visible",
                "text-field": "{TEXT}",
                "text-size": {
                    "base": 1,
                    "stops": [
                        [
                            19,
                            16
                        ],
                        [
                            22,
                            16
                        ]
                    ]
                },
                "text-rotate": {
					"type": "identity",
					"property": "ORIENTATION"
				}
            },
doesn't work

**Comment by andrewharvey** [comment]
@MartinHerich do you have a minimal jsbin example of it not working?

**Comment by MartinHerich** [comment]
OK. I found my way to use the field. Actually the problem was that MAPBOX changed the name of field from ORIENTATION to ORIENTATIO on import. Now it works. But I need to use formula on text-rotate as my values are in GONs with the beggining on south. My formula would be like 
(ORIENTATION-300)*0.9 
but when I write it in property then it won't be recognised and all the texts are on 0 grad. Is there any special syntax needed?

**Comment by rlanda123** [comment]
I have a property named "heading". When I am trying to rotate the icon by binding the rotation property to heading, it is not working. Please see below:
 map.addLayer({
        "id": "tracker",
        "type": "symbol",
        "source": 'trace',
        "layout": {
            "icon-image": "airport-15",
            "icon-allow-overlap": true,
            "icon-rotate" : {heading},
            "text-field": "{name}",
            "text-font": ["Open Sans Semibold", "Arial Unicode MS Bold"],
            "text-offset": [0, 0.6],
            "text-anchor": "top"
        }
    });

Can someone please help me how to make it work?
Thanks a lot in advance.

**Comment by rlanda123** [comment]
@MartinHerich Did you have it working? If so, would you please post the addLayer()? Thanks a lot.

**Comment by AddoSolutions** [comment]
Having the same issue as above:

```javascript


  // Add current location marker
  map.addSource('current-location', {
    "type": "geojson",
    "data": {
      "type": "Point",
      "coordinates": this.start,
      "properties":{
        "rotation":315
      }
    }
  });

  map.addLayer({
    "id": "current-location-marker",
    "source": "current-location",
    "type": "symbol",
    "layout": {
      "icon-image": "sa-currentLocation",
      "icon-size": 0.4,
      "icon-padding":1,
      "icon-allow-overlap":true,
      "icon-anchor": "center",
      "icon-pitch-alignment":"map",
      //"icon-rotation-alignment":"map",
      "icon-rotate": { "type": "identity", "property": "rotation" }
    },
  });

```

**Comment by AddoSolutions** [comment]
Solved my own issue (hopefully others too).  The single "Point" needed upgrading to a "Feature"

```
      // Add current location marker
      map.addSource('current-location', {
        "type": "geojson",
        "data": {
          type: 'Feature',
          geometry: {
            "type": "Point",
            "coordinates": this.start
          },
          "properties":{
            "heading":315
          }
        }
      });
```

**Comment by cs09g** [comment]
for me, the `property` from mbtiles was string format. In this case, you can customize [this code](https://github.com/mapbox/mapbox-gl-js/blob/master/src/symbol/quads.js#L96) as:
```javascript
feature.properties.YOUR_STRING_PROP = +feature.properties.YOUR_STRING_PROP;
const angle = layer.layout.get('icon-rotate').evaluate(feature, {}) * Math.PI / 180;
```

**Comment by DaveThePianoDude** [comment]
Hi.  You can do something like

` "layout": {
        "icon-image": "tunnel-exit",
        "icon-rotate": ["get","AOO"],
        "text-field": "Tunnel Mouth",
        "text-offset": [-5,2]
      },
`
