### ISSUE TITLE
style the shared outlines between rendered features in a layer

### ISSUE THREAD

**Issue by gandhiamarnadh** [mapbox/mapbox-gl-js#8731]
**mapbox-gl-js version**:

### Question

My req is to use fill-outline-color for  rendered features in a layer and make transparent the outline's which are shared between features ( I looked into documentation of layer type fill and line), but couldn't find a way to achieve this.

an example to be make it clear: My layer filtering California and Nevada should have an outline color but the shared border between two states should be invisible.

**Comment by mourner** [comment]
I think the only way to do something similar technically is two have stroke layer first, and fill layer afterwards so that it draws on top. We can't detect and treat shared borders differently at runtime.
