### ISSUE TITLE
Is this library 64bit compliant for android play store requirements?

### ISSUE THREAD

**Issue by jwitheford** [mapbox/mapbox-gl-js#8739]
**mapbox-gl-js version**: 0.54.0

### Question
Hey there. I am using this package in an ionic mobile application that I am building and since midway through August have been unable to upload APK's to the google play store. The only thing I can link this to is the recent changes to the Google Play requirements that force all apps to support 64bit applications.

They say to check the application for .so files, and the only ones I have are for this library here.

Is it on the roadmap to make this comply anytime soon? If not, can anybody point me in the right direction of getting it to work myself?

Thanks in advanced

### Links to related documentation

https://developer.android.com/distribute/best-practices/develop/64-bit

**Comment by mourner** [comment]
This requirement seems to only be relevant to native code. Mapbox GL JS is purely JavaScript library and relies on browser architecture. If you're unable to upload Ionic APKs, that's not a problem on our side — submit an issue there.

**Comment by jwitheford** [comment]
Thanks for the reply @mourner, I guess my issue is not really related to ionic which is why I didn't go there first. Its the fact that I am getting native libraries in my application for mapbox and I'm not sure where they are coming from. We chose the javascript library so that we didn't have to use any native libraries and could share code between our mobile and web apps...
