### ISSUE TITLE
featuresAt example only showing polygons

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#874]
![image](https://cloud.githubusercontent.com/assets/3170312/5370263/d327b6e6-7fd4-11e4-90a1-cdeabd8910fe.png)
The [featuresAt](https://www.mapbox.com/mapbox-gl-js/example/featuresat/) example seems to be only showing polygons, no matter how much I try to hover over a line or point.

**Comment by jfirebaugh** [comment]
Let's track in #902.
