### ISSUE TITLE
Older versions of chrome text rendering breaks (chrome 48)

### ISSUE THREAD

**Issue by baversjo** [mapbox/mapbox-gl-js#8742]
**mapbox-gl-js version**:
1. 1.3.1 (and whatever runs on your site)

**browser**:
chrome 48 on osx

### Steps to Trigger Behavior

 1. Download this older version of chrome, chrome 48: https://sourceforge.net/projects/osxportableapps/files/Chromium/Chromium_OSX_48.0.2564.116.dmg/download
 2. goto your simple example: https://docs.mapbox.com/mapbox-gl-js/example/simple-map/
 3. see how text is incorrectly rendered: 
<img width="1547" alt="Screenshot 2019-09-09 16 00 34" src="https://user-images.githubusercontent.com/371678/64537413-1156f500-d31b-11e9-9c18-8466a733159c.png">

### Expected Behavior
Text should render in correct size

### Actual Behavior
text is rendered in huge size

**Comment by baversjo** [comment]
Mapbox gl 0.45 works perfectly on chrome 48 by the way.

**Comment by baversjo** [comment]
the reason I'm filing this is because I have devices using mapbox gl on android 4.4 and they're stuck on this version of chrome and are affected by this.

**Comment by baversjo** [comment]
if you do not want to solve this bug maybe you would consider disabling showing text on older versions of chrome so at least the map renders?

**Comment by igal1c0de4n** [comment]
The maps on chrome versions < 48 are pretty much useless. 
Seems like `mapboxgl.supported()`should return `false` for those browsers
Is this an easy change?

**Comment by kkaefer** [comment]
> Mapbox gl 0.45 works perfectly on chrome 48 by the way.

I tried this, but 0.45 has the same rendering error on Chrome 48.

**Comment by kkaefer** [comment]
The last version that was still working correctly is 0.34. The commit that starts failing in Chrome 48 is 13363a2b7eb6154272827dda066f588b050412bb, as part of #4455.

**Comment by baversjo** [comment]
@kkaefer thank you so much for finding a fix for this!!
