### ISSUE TITLE
A more granular control over handling of prefers-reduced-motion

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#8743]
## Motivation

There's quite a bit of confusion over GL JS handling of `prefers-reduced-motion` OS option (see #8288 and #8494 for background). Examples: #8716, #8648

## Design

From https://github.com/mapbox/mapbox-gl-js/pull/8494#issuecomment-529168645 by @andrewharvey:

> could be we expose some kind of option so the app developer can say if this transition is considered essential or not?

We could add `{essential: true}` to animation options (`false` by default) that makes it animate regardless of `prefers-reduced-motion`. That would allow developers to fully control the experience, marking animations as essential where necessary. cc @arindam1993

**Comment by dnspnjrs** [comment]
@aMoniker are you willing to share a snippet of your ugly hack? I'm struggling with this issue in a project.

**Comment by aMoniker** [comment]
@dnspnjrs It's in typescript, but should work fine in plain javascript if you remove the types:

```
/**
 * The prefers-reduced-motion hacks below are to circumvent broken map panning
 * that was introduced when mapbox started paying attention to this:
 * https://github.com/mapbox/mapbox-gl-js/blob/master/src/util/browser.js#L60
 *
 * They may fix this issue, which might mean we can delete this hack:
 * https://github.com/mapbox/mapbox-gl-js/issues/8743
 */

let origMatchMedia: (query: string) => MediaQueryList;
const reducedMotionQuery = '(prefers-reduced-motion: reduce)';
function reducedMotionHack() {
  if (!window.matchMedia) return;
  origMatchMedia = window.matchMedia;
  window.matchMedia = matchMediaHack;
}
function matchMediaHack(query: string): MediaQueryList {
  if (query !== reducedMotionQuery) return origMatchMedia(query);
  const mql: MediaQueryList = {
    matches: false,
    media: reducedMotionQuery,
    onchange: null,
    addListener: () => null,
    removeListener: () => null,
    addEventListener: () => null,
    removeEventListener: () => null,
    dispatchEvent: () => true,
  };
  return mql;
}
```

Then call `reducedMotionHack()` once sometime during your app's initialization.

**Comment by andrewharvey** [comment]
Proposal to change the API to support an essential AnimationOption at #8883, we could then update the example at https://docs.mapbox.com/mapbox-gl-js/example/flyto-options/ to include this essential option, since to demonstrate "slowly fly to a location" it's essential that the animation occurs.
