### ISSUE TITLE
Provide a 'debug' option to silence console output

### ISSUE THREAD

**Issue by wmelton** [mapbox/mapbox-gl-js#8746]
## Motivation

Currently, MapBox dumps a ton of informational info to the console including passing the api key prominently in plain site in one of the console logs. While things like that aren't rocket science to get to, it seems best practice to be able to suppress large log outputs like this in production.

Would be great to see a config option 'debug: false' or something similar to suppress console output, at min for informational outputs.

### Implementation

Configuration option:

`debug: false`

In the library, if you're about to log some informational logs with `console.log()`, simply do a quick config check, e.g. 

` if(config.debug){console.log(msg);}` or something more elegant.

**Comment by ryanhamley** [comment]
The Mapbox GL JS library doesn't really have any `console.log` statements in the source code so I don't think the logs are coming from the library. Can you provide an example?

**Comment by wmelton** [comment]
Apologies - I had `Log XMLHTTPRequests` accidentally flagged in Chrome causing all the verbose output. Doh! Closing.
