### ISSUE TITLE
Add raster image on 3d building (3D indoor mapping)

### ISSUE THREAD

**Issue by aartikanungo** [mapbox/mapbox-gl-js#8770]
is there any way to add raster image on 3D building (3D indoor mapping) just like we add color in fill-extrusion type.
i just want to fit an image on particular coordinates just like fill-extrusion-color. (with base height and height) Thanks in advance :)

**Comment by mourner** [comment]
Not at the moment. For any advanced 3D such as textured buildings, you would have to use custom GL layers (such as on [this example](https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/)). Previously: #7520 #6516
