### ISSUE TITLE
ScaleControl uses inconsistent earth radius

### ISSUE THREAD

**Issue by exe-dealer** [mapbox/mapbox-gl-js#8777]
**mapbox-gl-js version**: 1.3.1

**browser**: *

Why scale control uses different earth radius than mercator projection code? Is this ok?

https://github.com/mapbox/mapbox-gl-js/blob/2020f3f9ced516086508925411bd098fbb4c3234/src/ui/control/scale_control.js#L130

https://github.com/mapbox/mapbox-gl-js/blob/2020f3f9ced516086508925411bd098fbb4c3234/src/geo/mercator_coordinate.js#L9

**Comment by ryanhamley** [comment]
Hmm, that's a good question. I think the radius in `scale_control` is fine.

From [Wikipedia](https://en.wikipedia.org/wiki/Mercator_projection):
>for small scale (large region) applications the variation may be ignored, and mean values of 6,371 km and 40,030 km may be taken for the radius and circumference respectively

@andrewharvey was there a specific reason you chose 6378137 for the radius in `mercator_coordinate`? Maybe it would be a good thing to pull magic values like this into a file that could be included elsewhere so we can define them once and not have inconsistencies in the code.

**Comment by andrewharvey** [comment]
The figure in `mercator_coordinate` came from the [EPSG:3857 definition](https://www.epsg-registry.org/report.htm?type=selection&entity=urn:ogc:def:crs:EPSG::3857&reportDetail=short&style=urn:uuid:report-style:default-with-code&style_name=OGP%20Default%20With%20Code&title=EPSG:3857).

**Comment by mourner** [comment]
@andrewharvey given how the value is used in `MercatorCoordinate`, I think we should change it to mean radius value rather than the equator one from EPSG:3857. The latter also defines inverse flattening (298.257223563) which defines how this radius [varies across the globe](https://en.wikipedia.org/wiki/Flattening).

**Comment by andrewharvey** [comment]
> @andrewharvey given how the value is used in MercatorCoordinate, I think we should change it to mean radius value rather than the equator one from EPSG:3857. The latter also defines inverse flattening (298.257223563) which defines how this radius varies across the globe.

@mourner Sorry I don't understand. What does "radius value" mean here?

At the equator (ie. along the semi-major axis) the inverse flattening won't matter or affect it right? And then we use the scale factor to account for larger latitudes being larger on the map.

**Comment by mourner** [comment]
@andrewharvey at the equator, it won't, but at other latitudes, it will — the Earth radius (the circumference is calculated from) will be smaller. You can either account for that with complicated formulas, or take a mean value across latitude range for simplicity — super-precision isn't important for the scale control anyway.

**Comment by andrewharvey** [comment]
> @andrewharvey at the equator, it won't, but at other latitudes, it will — the Earth radius (the circumference is calculated from) will be smaller. You can either account for that with complicated formulas, or take a mean value across latitude range for simplicity — super-precision isn't important for the scale control anyway.

Ok, maybe I misunderstood this then, I thought the scale factor formula I used accounted for this. But maybe that's just for the Mercator projection on a spherical datum instead of on the ellipsoidal datum which EPSG:3857 uses..

**Comment by mourner** [comment]
@andrewharvey yes, exactly. Standard Mercator formulas, including the scale factor one, [assume spherical earth](https://en.wikipedia.org/wiki/Mercator_projection#The_spherical_model) and so usually use the mean radius value as approximation.

**Comment by Meekohi** [comment]
Proposed correction: #9202

**Comment by ryanhamley** [comment]
Closed by #9202. Thanks @Meekohi!
