### ISSUE TITLE
minimal zoom level incorrect for small map size

### ISSUE THREAD

**Issue by Akiyamka** [mapbox/mapbox-gl-js#8778]
Hello!
[According to glossary](https://docs.mapbox.com/help/glossary/zoom-level/) zoom level = 0 must show whole earth.
But it doesn't work for map with width and height `< 512px`.
**Example:**
https://js-muk3zs.stackblitz.io

**Why it's important**
Small map canvas need for minimap feature. 
This is a useful thing if we want to show on the map which part of the world the map is currently pointing to. Example
http://aesqe.github.io/mapboxgl-minimap/

**mapbox-gl-js version**:
1.3.1

### Expected Behavior
zoom === 0 must show world event on small maps

### Actual Behavior
zoom 0 show world only if map size more that 512px

**Comment by Akiyamka** [comment]
**Workaround**
```
#map {
  position: absolute;
  top: 0;
  bottom: 0;
  width: 512px;
  height: 512px;
  transform: scale(.3);
  transform-origin: top left;
}
```
https://js-d9aysl.stackblitz.io/

**Comment by ryanhamley** [comment]
Hi @Akiyamka thanks for the report. This is a known issue that is being tracked in https://github.com/mapbox/mapbox-gl-js/issues/3055 so I will close this as a duplicate issue.
