### ISSUE TITLE
Mapbox attribution is not showing as expected

### ISSUE THREAD

**Issue by ertkjern** [mapbox/mapbox-gl-js#8783]
I am trying to implement Mapbox using React and it works great. 

But i noticed that the Mapbox attribution is not showing quite as expected. I can find the logo in the DOM with `width: 0px, height: 0px`. And the text is hidden somewhere behind. So by tweeking the texts css it shows as expected. 

I was primarily following the blogpost from Mapbox (https://blog.mapbox.com/mapbox-gl-js-react-764da6cc074a) and tried to copy paste his solution into Codesandbox, but the issue seems to presist also here. 

I can of course add it manually, but i expect it to show by default. 

**mapbox-gl-js version**:
` "mapbox-gl": "^1.3.1",`

**browser**:
Chrome 

### Steps to Trigger Behavior

 1. Implement Map using React

### Link to Demonstration
The code (copied basicly directly from the blog post) can be found here: 
https://codesandbox.io/embed/admiring-swirles-38qom

### Expected Behavior

Mapbox attribution, logo + text, to be displayed

### Actual Behavior
Text hidden away, Logo not showing at all.

**Comment by mourner** [comment]
You likely forgot to include [Mapbox CSS](https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.css) on the page.

**Comment by ertkjern** [comment]
Of course, I assumed it was a part of the module for some reason. 
Thank you so much for your help.
