### ISSUE TITLE
Circle/Cluster color based on expression

### ISSUE THREAD

**Issue by mquilling** [mapbox/mapbox-gl-js#8784]
I would like the ability to base paint properties on an expression with a variable computed in the cluster.  Currently I am doing something like:

```
'circle-color': [
  'step',
  ['get', 'my_var'],
  '#2ECC71',
  1,
  '#caca01',
  15,
  '#E74C3C',
],
```

which colors things: 
```
my_var == 0: green
0 < my_var < 15: yellow
my_var >= 15: red
```
what I want is something like:
```
percentage = my_var/point_count
percentage == 0: green
percentage < 0.1: yellow
percentage >= 0.1: red
```

It wasn't clear to me if this was possible with the current implementation?  If not is there a plan to implement/workaround?  

Thanks!

**Comment by asheemmamoowala** [comment]
@mquilling You can use the `point_count` property on the cluster features to do this using `["get", "point_count"]`.

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, we recommend using [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox-gl-js) or [contacting support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

**Comment by mquilling** [comment]
I am using that but what I really want to do is have an expression like my_var/point_count but the library gave me a warning that expressions are not supported if I recall correctly.

Does the library support that expression in a step (not using just point_count alone)?  If not this is a feature request.  

I will contact support as you recommend, thanks!
