### ISSUE TITLE
Upgrade esm to 3.1.0 to remove Regular Expression Denial of Service (ReDoS) security vulnerability

### ISSUE THREAD

**Issue by nreese** [mapbox/mapbox-gl-js#8791]
`esm@3.0.84` has a [Regular Expression Denial of Service (ReDoS) security vulnerability](https://snyk.io/vuln/SNYK-JS-ESM-72880).

Upgrading to 3.1.0 will resolve this vulnerability

**Comment by andrewharvey** [comment]
see #8744 #8672 #8450

**Comment by nreese** [comment]
Thanks for the links.
