### ISSUE TITLE
Transparent area on 3D view

### ISSUE THREAD

**Issue by MikeChenfu** [mapbox/mapbox-gl-js#8792]
**mapbox-gl-js version**:

### Question
Hello, I am using `'fill-extrusion-height':   ['/', ['get', 'population'], 100],` to show the 3D view. However, some sides of the tube become transparent, as shown in below picture. I appreciate if anyone has suggestion about it.
 
<img width="1671" alt="Screen Shot 2019-09-23 at 4 20 57 PM" src="https://user-images.githubusercontent.com/17817768/65464093-b0e9ac80-de1e-11e9-9222-fc4c9042827a.png">

**Comment by ryanhamley** [comment]
Hi @MikeChenfu can you create a minimal example that shows the issue? We recommend sites like JSBin for this purpose. It looks like you may want to set `antialias: true` on your map to reduce the jagged edges of the extrusions, but I don't think that will fix the issue at the base of the extrusion.

**Comment by MikeChenfu** [comment]
Thanks @ryanhamley for the quick reply. I attach the example. I appreciate if you have any suggestions. 
```
<!DOCTYPE html>
<html>
<head>
<meta charset='utf-8' />
<title>Update a choropleth layer by zoom level</title>
<meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.js'></script>
<link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.css' rel='stylesheet' />
<style>
body { margin:0; padding:0; }
#map { position:absolute; top:0; bottom:0; width:100%; }
</style>
</head>
<body>

<div id='map'></div>
 
<script>
mapboxgl.accessToken = 'pk.eyJ1Ijoic2dtbXN4eiIsImEiOiJjazBmcHp5bXowdmV0M21udTN3dGM0OW94In0.sPJ2yyoEgWSyFEUQH7vQoA';
var map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/mapbox/light-v10',
center: [-98, 38.88],
minZoom: 3,
zoom: 3
});
 
var zoomThreshold = 4;
map.on('load', function() {
map.addSource('population', {
'type': 'vector',
'url': 'mapbox://mapbox.660ui7x6'
});
map.addLayer({
'id': 'county-population',
'source': 'population',
'source-layer': 'state_county_population_2014_cen',
'type': 'fill-extrusion',
'filter': ['==', 'isCounty', true],
'paint': {
'fill-extrusion-color': [
'interpolate',
['linear'],
['get', 'population'],
0, '#F2F12D',
100, '#EED322',
1000, '#E6B71E',
5000, '#DA9C20',
10000, '#CA8323',
50000, '#B86B25',
100000, '#A25626',
500000, '#8B4225',
1000000, '#723122'
],
'fill-extrusion-height': ['/', ['get', 'population'], 10],
'fill-extrusion-opacity': 0.75
}
}, 'waterway-label');
});
</script>
</body>
</html>
```

**Comment by mourner** [comment]
@MikeChenfu what tool did you use to generate vector tiles for this source? I've seen an issue like this happen before and the culprit was incorrect winding order of polygons.

**Comment by MikeChenfu** [comment]
@mourner You are correct. I try a different data generated from tippecanoe. Everything is good. Thanks.
