### ISSUE TITLE
GeolocateControl Icon

### ISSUE THREAD

**Issue by desmeit** [mapbox/mapbox-gl-js#8797]
How can I change the icon when I click GeolocateControl?

![Bildschirmfoto 2019-09-24 um 13 10 05](https://user-images.githubusercontent.com/9454529/65506800-b6053500-decc-11e9-8d30-122ff21dd4f0.png)

**Comment by andrewharvey** [comment]
You can override some of the CSS classes from the [dist css](https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.css) such as `.mapboxgl-ctrl-geolocate`

**Comment by desmeit** [comment]
thanks
