### ISSUE TITLE
Drop warning thrown when image equates to "" and image expression type is not used

### ISSUE THREAD

**Issue by tristen** [mapbox/mapbox-gl-js#8800]
**mapbox-gl-js version**: `v1.4.0-beta.1`

### Question

`icon-image: ""` is a valid value, so I was confused when I saw this warning thrown.

<img width="710" alt="Screen Shot 2019-09-24 at 4 22 25 PM" src="https://user-images.githubusercontent.com/61150/65547468-8c0d3c00-dee7-11e9-879e-cf2e6e0fd696.png">

As its a common scenario to write an expression that chooses some features to use `""` and others to use one, I think this sends a confusing message to a user. 

Understanding the rationale behind adding it in `v1.4.0` as part of the new image expression type, can we limit the warning thrown to when its in use?

### Links to related documentation

- Image expression type PRs
  - https://github.com/mapbox/mapbox-gl-js/pull/8684
  - https://github.com/mapbox/mapbox-gl-js/pull/8775

**Comment by ryanhamley** [comment]
>can we limit the warning thrown to when its in use

I'm not sure I understand this part. What do you think would be the expected outcome of `icon-image: "'`? Should we just treat it as if `icon-image` was never defined?

**Comment by samanpwbb** [comment]
Throwing this warning seems consistent with existing expression warnings, for example, when a field value is the incorrect type in a get expressions. I think it's useful.

I do wonder if Mapbox GL should have separate `development` and `production` modes – where, depending on your NODE_ENV value at build time, warnings either are or are not displayed. This would eliminate the concern of console spam while freeing us up to surface more helpful warnings.

**Comment by tristen** [comment]
> I'm not sure I understand this part. What do you think would be the expected outcome of `icon-image: "'`? Should we just treat it as if `icon-image` was never defined?

Yes. It should be treated as if `icon-image` was never defined. 

> Throwing this warning seems consistent with existing warnings, for example, when a field value is the incorrect type in a get expression. I think it's useful.

An incorrect type in a get expression is an example of something wrong and yeah, a warning should be thrown. However, providing `""` as a possible option is a legitimate thing to do.

> I do wonder if Mapbox GL should have separate `development` and `production` modes – where, depending on your NODE_ENV value at build time, warnings either are or are not displayed. This would eliminate the concern of console spam while freeing us up to surface more helpful warnings.

Yeah, that crossed my mind too (similar to how React does this) +1

**Comment by asheemmamoowala** [comment]
> However, providing "" as a possible option is a legitimate thing to do

I agree with this. Even in development mode, the error message or the `styleimagemissing` event for this case do not make any sense - they don't help the developer understand which layer, layer-property, or for which feature the problem exists.

More so, `""` is the absence of a valid image name, where image name must be 1+ alphanumeric characters.
