### ISSUE TITLE
How use Babylon.js add 3d model

### ISSUE THREAD

**Issue by fengfenghao** [mapbox/mapbox-gl-js#8801]
How use the babylon.js to load a 3d mode，I found a case in which three.js loaded a 3D model, but there was no babylon.js，Is there a case of Babylon.js loading 3D model?

**Comment by mourner** [comment]
There's no official example with Babylon.js, but feel free to work on a pull request adding one in the https://github.com/mapbox/mapbox-gl-js-docs repo if you feel the Three.js example isn't enough.
