### ISSUE TITLE
mapbox-gl.css v1.4.0 is not found

### ISSUE THREAD

**Issue by xavier114fch** [mapbox/mapbox-gl-js#8816]
Mapbox GL JS CSS v1.4.0 is missing and popup is broken.

**mapbox-gl-js version**: v1.4.0

**browser**: Firefox/Chrome

### Steps to Trigger Behavior

 1. Open any page using Mapbox GL JS v1.4.0
 2. If it has popup it loses CSS styling
 3. Opens developer tools on browser gives this error message (from Firefox)

> 
The resource from “https://api.mapbox.com/mapbox-gl-js/v1.4.0/mapbox-gl.css” was blocked due to MIME type (“application/json”) mismatch (X-Content-Type-Options: nosniff).

### Link to Demonstration
Any page with using Mapbox GL JS v1.4.0

### Expected Behavior
CSS loads successfully

### Actual Behavior
CSS loading failure with this error message
`{"message":"Not Found"}`

**Comment by mourner** [comment]
Yes — the `deploy-release` CI job for the v1.4.0 failed with a timeout. Might be some temporary hiccup — I just triggered a rerun. Hopefully everything will work in half an hour.

**Comment by mourner** [comment]
It's live! https://api.mapbox.com/mapbox-gl-js/v1.4.0/mapbox-gl.css
