### ISSUE TITLE
How to change current location image programatic?

### ISSUE THREAD

**Issue by ansarikhurshid786** [mapbox/mapbox-gl-js#8820]
I have changed current location image using css but it is not perfect because when i upgrade mapbox gl js version that is not working. 

is there any programmatic way to change current location image. 

It is really a very nice feature if it will available.

**Comment by andrewharvey** [comment]
You can change it by overriding the CSS classes https://github.com/mapbox/mapbox-gl-js/blob/master/src/css/mapbox-gl.css#L519
