### ISSUE TITLE
Efficient methods to combine external data with MVT in MapBox GL JS

### ISSUE THREAD

**Issue by akshetty9** [mapbox/mapbox-gl-js#8822]
### Question

We have a need to show a large number of features on the map(1M) 
In addition to this, every feature needs to be color-coded, based on a value which gets generated as part of a calculation that runs in the server. 
These calculations can be triggered by users, and values are generated per calculation.
Every asset gets 48 values after this calculation. A time slider on the map lets the user view the colors based on the time step (1-48).

We use geo server, which serves mvt from PostGIS and client handles styling.
We would like to know what is the efficient method to handle this.

1. Load time series data (value for each time step ) in separate JSON,use data join on the map to combine TimeSeries data with Feature data
   - Does not perform well for the large data set.
2. Use views in PostGIS/geo server to combine time series data with features
   - Time series data can possibly be stored in a separate NQSQL database. 
   - Joining the data is not possible
3. Load time series for each time step on time slider change, use set-features method to update the style.
   - Does not perform well after 10K features.
Are there any other methods to handle this more efficiently?

**Comment by kkaefer** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, check [StackOverflow](https://stackoverflow.com/questions/tagged/mapbox) or [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
