### ISSUE TITLE
styleimagemissing emitted while Image operator deems the image available

### ISSUE THREAD

**Issue by everhardt** [mapbox/mapbox-gl-js#8831]
I've started using the `image` operator in combination with `coalesce` on the `icon-image` layout property. I now see in the console sometimes the following error:

```
Image "{"name":"[redacted]","available":true}" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.
```

It's differs from refresh to refresh which image gets this error, therefore I think it has to do with symbols that are to be displayed immediately after loading. And I suspect the issue to be that either:
* the parser of the `icon-image` layout property does not know how to deal with an Image object instead of its name string
* the coalesce and image operators has another definition of available than the parser of `icon-image` (as `available` is `true`)

**mapbox-gl-js version**: 1.4.0

**browser**: Chrome 77

**Comment by ryanhamley** [comment]
Hi @everhardt can you supply a minimal reproduction of the bug? If you can set up an example in something like JSBin, that would be extremely helpful for debugging the issue.

**Comment by everhardt** [comment]
This shows the issue: https://codepen.io/everhardt/pen/OJJLayz

There are no icons rendered and in the console you see (among others):
```
Image "{"name":"zoo-11","available":true}" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.
```
