### ISSUE TITLE
Behavior of  `line-cap` + `line-dasharray`

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#884]
Currently, line caps do not control the caps of line segments in lines using `line-dasharray`. They do in carto, and I think they should in GL, too.

In carto:

![screen shot 2014-12-12 at 1 35 54 pm](https://cloud.githubusercontent.com/assets/5607844/5417157/6f2d6a5a-8204-11e4-8487-703839a680e8.png)

In mapbox-gl-js:

![screen shot 2014-12-12 at 1 36 53 pm](https://cloud.githubusercontent.com/assets/5607844/5417167/81500918-8204-11e4-9d08-946d36b54e7b.png)

```
  {
    "id": "BicycleLane",
    "type": "line",
    "source": "Bike Lanes DC",
    "source-layer": "BicycleLane",
    "layout": {
      "line-cap": "round",
      "line-join": "round"
    },
    "paint": {
      "line-color": "#942192",
      "line-width": "6",
     "line-dasharray": [6, 2]
    }
  }
```

**Comment by ansis** [comment]
done in https://github.com/mapbox/mapbox-gl-js/pull/938
