### ISSUE TITLE
Popup Anchor Occasionally Does Not Allow for Full View of Popup

### ISSUE THREAD

**Issue by BRosentreter** [mapbox/mapbox-gl-js#8851]
The popup on the map sometimes ends up being cutoff when it can't be shown fully in the up or down directions, and therefore shows with the default anchor direction and is cutoff.

**mapbox-gl-js version**: mapbox-gl.js v1.4.0

**browser**: Google Chrome 

### Steps to Trigger Behavior

 1. Have a map setup with popups on hover. 
 2. Zoom in far enough to the map that the popup window wouldn't naturally fit above or below the anchor. 
 3. Hover over the anchor and the popup will be cutoff to whatever default anchor is set. In the case of the API documentation's own example, it gets cut off at the bottom.

### Link to Demonstration
Both of these can be recreated on the API documentation [here](https://docs.mapbox.com/mapbox-gl-js/example/popup-on-hover/)

Example of the popup as expected 
<img width="852" alt="Screen Shot 2019-10-09 at 3 56 00 PM" src="https://user-images.githubusercontent.com/5523408/66526382-505c9f80-eaad-11e9-9657-3f155ffbda75.png">

Example of the popup when it gets cutoff
<img width="843" alt="Screen Shot 2019-10-09 at 3 46 56 PM" src="https://user-images.githubusercontent.com/5523408/66526314-0ffd2180-eaad-11e9-9a36-c29eb9f47dfa.png">

### Expected Behavior
I'm not exactly sure what the expected behavior should be, I think it would be the most logical if it just determined in what direction the popup can fully be viewed in the map and choose that anchor point after that.

### Actual Behavior
The popup will be cutoff depending on the default anchor direction

**Comment by andrewharvey** [comment]
You're describing the case where there exists no anchor where the popup won't end up being off screen/map, is that right? Sorry, I don't follow your expected behaviour, are you saying it should pick the anchor which results in the least amount of cut off? Or are you saying you want to be able to set the preference for when it can't avoid cut off?

I think the current behaviour is reasonable, as most of the time content starts from the top, so getting cut off at the bottom just hints the user to pan a bit more to see the rest of the content.

**Comment by BRosentreter** [comment]
> You're describing the case where there exists no anchor where the popup won't end up being off screen/map, is that right? Sorry, I don't follow your expected behaviour, are you saying it should pick the anchor which results in the least amount of cut off? Or are you saying you want to be able to set the preference for when it can't avoid cut off?
> 
> I think the current behaviour is reasonable, as most of the time content starts from the top, so getting cut off at the bottom just hints the user to pan a bit more to see the rest of the content.

Well in the example I posted, it's obvious that the full popup would fit if its anchor was on the right side of the popup. If the popup is made to fit in the window size, why does it matter how zoomed in I am? If the popup was somehow taller than half the window and wider than half the window, sure it would never fully fit, but if it isn't as in most cases, why can it not be made to fit?

**Comment by andrewharvey** [comment]
Oh sorry I miusderstood your question. You're right than in the example, the popup can be cut off at the bottom when instead it could fit on the right.

This sounds exactly like #7675, so I'll close here to keep the discussion together on the existing ticket, but if this is a different issue, please just say so.

**Comment by BRosentreter** [comment]
> Oh sorry I miusderstood your question. You're right than in the example, the popup can be cut off at the bottom when instead it could fit on the right.
> 
> This sounds exactly like #7675, so I'll close here to keep the discussion together on the existing ticket, but if this is a different issue, please just say so.

Yeah that ticket is exactly what I'm referencing, thanks!
