### ISSUE TITLE
Dblclick and Right click event in layer

### ISSUE THREAD

**Issue by smartman21cen** [mapbox/mapbox-gl-js#8862]
Now I can't integrate dblclick and right click event to set some functionality in mgl-layer.
I checked mapbox-gl-js document but how can implement this functionalities?
Please check and let me know

**Comment by mourner** [comment]
```js
// double click
map.on('dblclick', 'myLayer', function () { ... });

// right click
map.on('contextmenu', 'myLayer', function () { ... });
```
