### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isExpression' of undefined

### ISSUE THREAD

**Issue by uct8086** [mapbox/mapbox-gl-js#8866]
hey, bro. i use babel to build the proj, but it occur an error :

```
 stylefunction.js?bd89:27 Uncaught TypeError: Cannot read property 'isExpression' of undefined
    at eval (stylefunction.js?bd89:27)
    at Module../node_modules/ol-mapbox-style-tang/stylefunction.js (app.js:14422)
    at __webpack_require__ (app.js:727)
    at fn (app.js:101)
    at eval (index.js:21)
    at Module../node_modules/ol-mapbox-style-tang/index.js (app.js:14410)
    at __webpack_require__ (app.js:727)
    at fn (app.js:101)
    at eval (openlayer_helper.js:31)
    at Module../client/common/utils/openlayer_helper.js (app.js:996)
```
and my babel config is : 
```
{
      test: /\.js$/,
      loader: 'babel-loader',
      exclude: /node_modules\/(?!(ol|d3|@mapbox\/mapbox-gl-style-spec)\/).*/,
      include: [resolve('client'), resolve('test'), resolve('node_modules/ol'), resolve('node_modules/@mapbox/mapbox-gl-style-spec')],
      options: {
        presets: ['stage-2']
      }
    },
```
then i found that the expression folder was typescript style, how can i exchange it ...

help me, my bro.

**mapbox-gl-js version**:13.9.0

**browser**: chrome 76, IE 11

**Comment by mourner** [comment]
Unfortunately we can't afford to spend time debugging Webpack/Babel issues of other people's apps, so you'll have to find a solution yourself. We also don't have or use any TypeScript in the project. You can try asking devs of OpenLayers (which seems to be involved here).

P.S. Please avoid addressing people as "bros" in issues — this is disrespectful to all non-male maintainers of this and other projects.

**Comment by uct8086** [comment]
> Unfortunately we can't afford to spend time debugging Webpack/Babel issues of other people's apps, so you'll have to find a solution yourself. We also don't have or use any TypeScript in the project. You can try asking devs of OpenLayers (which seems to be involved here).
> 
> P.S. Please avoid addressing people as "bros" in issues — this is disrespectful to all non-male maintainers of this and other projects.

ok，thanks for your reminder.
