### ISSUE TITLE
Draw and Move polyline from any point 

### ISSUE THREAD

**Issue by anujsinghwd** [mapbox/mapbox-gl-js#8867]
I am trying to make feature like iflightplanner in my application like this.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24680004/66731552-903cd180-ee75-11e9-9d5a-e098c1841f7e.gif)

**Comment by kkaefer** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
