### ISSUE TITLE
geolocation error handling not working

### ISSUE THREAD

**Issue by kilianso** [mapbox/mapbox-gl-js#8870]
Geolocation error handling is not working. 

**mapbox-gl-js version**: 1.4.1

**browser**: Safari 13.0.2 on Mac OS Mojave

### Steps to Trigger Behavior

 1. Disable location service in system settings.
 2. Open example below and try to locate user by clicking the geolocation control.

### Link to Demonstration

[Locate User Example](https://docs.mapbox.com/mapbox-gl-js/example/locate-user/
)
### Expected Behavior
1. If user clicks on "do not allow", control should be visually updated to indicate that it is not possible to set the location.
2. If user has disabled overall location services in system settings of Mac OS, there needs to be a message or visual indicator that mapbox control will not work.

### Actual Behavior

1. If user clicks on "do not allow" – control appearance is not updated.
2. If user has disabled the overall location services in system settings of Mac OS – there is no notification, or any other indicator, that the mapbox control for geolocation is not working.

**Comment by kkaefer** [comment]
@kilianso you can test the PR in https://github.com/mapbox/mapbox-gl-js/pull/8871
