### ISSUE TITLE
Opening credits in Electron

### ISSUE THREAD

**Issue by doyle-mark** [mapbox/mapbox-gl-js#8882]
## Motivation

In an electron app, when the user clicks on the "Mapbox" credits/OSM credits; Electron opens a new electron window. This ruins the "native" experience for the user and makes them realise they're just looking into a chromium window.

## Design

Have an option to specify to Mapbox to open the link in browser.

### Implementation
Use shell to open the link in the user's default browser [`shell.openExternal`](https://electronjs.org/docs/api/shell)

**Comment by mourner** [comment]
I don't think we should have any Electron-specific code in GL JS itself. However, there should be a manageable workaround — on the app side, query all links in the copyright control and intercept their onclick handler to use Electron code.
