### ISSUE TITLE
Inaccurate rendering of shapes

### ISSUE THREAD

**Issue by Arash-Nouri** [mapbox/mapbox-gl-js#8885]
Hi,

I am trying to create an overlay of the streets of the US. The **map streets v8** provided by Mapbox is missing some information that I need. So, I downloaded the OSM files ([from here](https://download.geofabrik.de)) and filtered out everything but roads. Now, I am trying to upload this data as a layer in Mapbox but the shapes are inaccurate. I tried different ways, like uploading Geojson files or Mbtiles files. Every time I get different shapes. 

For example, this image shows 3 lines all representing the same road. The red one is created in Mapbox studio as a line shape. Black one is from an uploaded Mbtiles file and Blue is from an uploaded Geojson file of Alabama. The road starts from ["lat": 34.8174377, "lon": -86.9436697] to [ "lat": 34.8175178, "lon": -86.9439487]. You can view the original this road [here](https://overpass.kumi.systems/api/interpreter?data=[out:json];way(475110135);(._;%3E;);out;).

<img width="766" alt="Screen Shot 2019-10-21 at 11 56 30 AM" src="https://user-images.githubusercontent.com/7662364/67222334-1a97af00-f3fb-11e9-9a33-ecab06587a89.png">

Can someone please confirm whether this is actually a bug or I am doing something wrong here? Is there a short fix for this?

Thanks!

**Comment by andrewharvey** [comment]
ref https://gis.stackexchange.com/questions/339341/inaccurate-rendering-of-shapes-in-mapbox

**Comment by kkaefer** [comment]
@Arash-Nouri This looks like a data problem, not a rendering problem. Please contact Mapbox support with a detailed description at https://support.mapbox.com/.
