### ISSUE TITLE
map.querySourceFeatures returning an empty array

### ISSUE THREAD

**Issue by ashishvicesoftware** [mapbox/mapbox-gl-js#8888]
Hi
I am trying to get features using "querySourceFeatures" but it return an empty array. Here is my function :-

```js
 const features = map.querySourceFeatures("scoutred", {
      sourceLayer: "parcels",
      filter: ["==", ["get", "geohash"], propertyDetailByCoordinates.geohash]
});
```

This is my mapBox.JSON sytle :-
 
```json
    {
      "id": "parcels-fills",
      "type": "fill",
      "source": "scoutred",
      "source-layer": "parcels",
      "minzoom": 15,
      "maxzoom": 20,
      "paint": {
        "fill-color": "#6894D9",
        "fill-opacity": ["case",
         ["==", ["feature-state", "state"], "activehover"],
        1,
        0
        ]
        },
      "layout": {
       }
    },
```

**Comment by kkaefer** [comment]
You can find more information on how `querySourceFeatures` works in the API documentation at https://docs.mapbox.com/mapbox-gl-js/api/#map#querysourcefeatures. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Please reopen this issue if you believe there's a bug with this function. Thank you!
