### ISSUE TITLE
Check for GL errors

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#889]
Most WebGL calls should be immediately followed by a call to gl.getError and checking for errors. We can wrap the context [like suggested here](https://www.khronos.org/webgl/wiki/Debugging) and do this automatically. (Though I wouldn't use webgl-debug.js directly, it's buggy.)

**Comment by lucaswoj** [comment]
We could use `assert` to add these checks without affecting production performance

**Comment by jfirebaugh** [comment]
Closing; we've managed fine without this for years. WebGL implementations typically log to the console anyway if you do something wrong.
