### ISSUE TITLE
allow a custom user location dot in the GeolocateControl

### ISSUE THREAD

**Issue by ansarikhurshid786** [mapbox/mapbox-gl-js#8891]
It will be really very nice feature. If developer can change current location icon/image just passing image path mapbox gl js api.

**Comment by andrewharvey** [comment]
So right now you can change the style through CSS, and you can inline a PNG or SVG into your CSS style. Could you say anything more about the use case for needing more control beyond what you can do at the moment through CSS overrides?

**Comment by ansarikhurshid786** [comment]
I can change image by overriding using css but it will really helpful if this library itself provide property to change icon / image.

**Comment by kkaefer** [comment]
@ansarikhurshid786 do you have any concrete reasons for not using CSS to change the icon?

**Comment by ansarikhurshid786** [comment]
@kkaefer it is little difficult to change icon because there is several icon/image in different state.  this feature made easy to change icon / image properly

**Comment by andrewharvey** [comment]
@ansarikhurshid786 You're talking about the icon on the map right? It's defined https://github.com/mapbox/mapbox-gl-js/blob/master/src/css/mapbox-gl.css#L519 there is just one CSS class for the normal dot, and then another one also applied when "stale". I don't think that is too onerous.

**Comment by kkaefer** [comment]
> it is little difficult to change icon because there is several icon/image in different state. 

Providing icons in a different way doesn't change the fact that there are several states that require different icons?

**Comment by andrewharvey** [comment]
I think the current approach of setting styles via CSS is good enough, I'm not against an API change to set your own user location dot graphic, but if we do, my preference is to let the user pass in an Element, which in turn gets passed to Marker. How you fill that Element (with an svg, png or whatever) is then completely up to you.

**Comment by mourner** [comment]
I think the current way of customizing icons with CSS is good enough — no need to increase API surface.
