### ISSUE TITLE
Browser query-test runner doesnt report test timeouts and crashed tests correctly

### ISSUE THREAD

**Issue by arindam1993** [mapbox/mapbox-gl-js#8902]
Discovered by @ryanhamley, this is two issues that are related. If a test crashes, the exception gets silently caught by the test runner and the callstack exits causing `t.end()` to never be called, resulting in the test timing out.

The code that generates the visualization then crashes as its unable to parse the timeout metaData correctly.

**Comment by asheemmamoowala** [comment]
Addressed by https://github.com/mapbox/mapbox-gl-js/pull/10351
