### ISSUE TITLE
 SVG Icon shows a background, even when no background is defined

### ISSUE THREAD

**Issue by gromain** [mapbox/mapbox-gl-js#8903]
**mapbox-gl-js version**:1.4.1

### Question
When loading an Icon in Mapbox Studio, and using it on the map, the background of the icon shows itself.
For example here is a simple icon I made, you can see the grey background of the SVG viewport. However, there is no background defined in the SVG file.
![image](https://user-images.githubusercontent.com/2188885/67567342-040a9400-f72a-11e9-919d-7556f50b7e58.png)

SVG is as follows:
`<svg version="1.1" viewBox="0 0 60 100" xmlns="http://www.w3.org/2000/svg"><g transform="translate(0 -270.542)"><circle cx="30.7143" cy="320.274" r="12.7679" style="fill:#d2d2d2;stroke-linecap:round;stroke-linejoin:round;stroke-width:18.8976;stroke:#000"/></g></svg>`

No effect has been defined on the icon.

### Links to related documentation
I found no information about this kind of problem in the [Troubleshooting SVG image errors in Mapbox Studio](https://docs.mapbox.com/help/troubleshooting/studio-svg-upload-errors/) page.

**Comment by kkaefer** [comment]
I tried this with the SVG you provided, but I'm unable to reproduce this. I uploaded the SVG to Studio and added it to a symbol layer. The icon shows up correctly, without the border in your screenshot. Could you please try again? If this issue persists, please use https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231, mention this issue, and send your username and style ID so we can investigate further.

**Comment by gromain** [comment]
Mmmmmm,, you're right. It seems like it's not happening anymore.
Maybe it was a problem with my browser. If this happens again, I'll contact support.
Thanks for checking this and getting back to me!
