### ISSUE TITLE
some map data have different show in different zoom level

### ISSUE THREAD

**Issue by ZChengL** [mapbox/mapbox-gl-js#8919]
some map data have different show in different zoom level . for example I draw some walls, and the adjacent walls will fill the grey face between them;

![image](https://user-images.githubusercontent.com/19296715/67733117-5d2f3c00-fa38-11e9-8fb1-e5d92523f907.png)

![image](https://user-images.githubusercontent.com/19296715/67733150-6d471b80-fa38-11e9-8afb-72a5538f8268.png)

how to relsove this problem ? i need help

**Comment by vakila** [comment]
Hi @ZChengL, thanks for using Mapbox! 

It sounds like you are reporting a bug/problem in mapbox-gl-js, so could you please provide the information requested in our [bug report issue template](https://github.com/mapbox/mapbox-gl-js/issues/new?template=Bug_report.md)? 

If you can, it would be really helpful to see a link to a minimal demonstration of the bug using a site like https://jsbin.com or similar.

**Comment by ZChengL** [comment]
> Hi @ZChengL, thanks for using Mapbox!
> 
> It sounds like you are reporting a bug/problem in mapbox-gl-js, so could you please provide the information requested in our [bug report issue template](https://github.com/mapbox/mapbox-gl-js/issues/new?template=Bug_report.md)?
> 
> If you can, it would be really helpful to see a link to a minimal demonstration of the bug using a site like https://jsbin.com or similar.

There is no link to provide a demo for now   ，but I will build a demo to show my problem later .  I just decribe how do I operate ,  I use MercatorUtil convert the longitude coordinate and latitude coordinate (in degrees) of geometry to pixel X/Y coordinate at a certain zoom level in Java progam. pbfand use Mapbox GL JS to rendering in HTML5 page. and html5 request in .pbf form
but now I have not demo link to show the problem.
