### ISSUE TITLE
Custom Overlay Image is stretch inbound polygon

### ISSUE THREAD

**Issue by phanthinh** [mapbox/mapbox-gl-js#8921]
Hi everyone,

For my example: I want to add an overlay image to a place. so I used the code below, but image is stretch. It's an issue of mapbox or what's wrong from my code, who can help me pls. Thanks 

```
map.addSource('unique', {
      "type": "image",
      "url": floors[0].url,
      "coordinates": coors
    });
    map.addLayer({
      "id":'unique',
      "source":'unique',
      "type": "raster",
      "paint": {
        // "raster-opacity": 1
      }
    });
```

<img width="1002" alt="Screen Shot 2019-10-29 at 11 17 04" src="https://user-images.githubusercontent.com/5910795/67737449-d4b39a00-fa3d-11e9-8216-ea87eda6872d.png">

**Comment by indus** [comment]
Do you know the projection of your image? Maybe it is not EPSG:3857.

**Comment by phanthinh** [comment]
@indus I don't know the projection image type, I using https://res.cloudinary.com/phanthinh9889est/image/upload/v1572234208/bQC0xZkGWlsZMuNIJAUFteJFOwwPFn1o1Z01N3ayZ1fceYCzBeiQsV5cWq9piMhF_bpgxks.png 

So I need to convert it to `EPSG:3857`, correct?

**Comment by mourner** [comment]
@phanthinh this means the projection of the image doesn't match the projection of the map (Web Mercator), or the coordinates given are incorrect. There's nothing we can do on GL JS side to help with this.

**Comment by phanthinh** [comment]
@mourner 
I don't think so, there is the same function with google map but image show not good.
I saw a good example from google map: https://developers-dot-devsite-v2-prod.appspot.com/maps/documentation/javascript/examples/overlay-hideshow

Whether `mapbox GL JS` can do this?
