### ISSUE TITLE
Port individual textures for line dash patterns

### ISSUE THREAD

**Issue by kkaefer** [mapbox/mapbox-gl-js#8922]
https://github.com/mapbox/mapbox-gl-native/pull/15862

**Comment by ansis** [comment]
We'll probably need atlases to implement data driven line dasharrays. Is it worth porting this or trying to jump directly to per-tile atlases instead?

**Comment by mourner** [comment]
Yep, line dash pattern textures need to be generated as per-tile atlases to support data-driven cases. #10591
