### ISSUE TITLE
Overlapping points become brighter

### ISSUE THREAD

**Issue by huashaoxu** [mapbox/mapbox-gl-js#8932]
How to achieve this effect? Whether to support the use of blending render?
![image](https://user-images.githubusercontent.com/35364039/67999838-c7461c00-fc98-11e9-813b-1c65989b6215.png)

**Comment by kkaefer** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

You're looking for heatmaps. See https://docs.mapbox.com/mapbox-gl-js/example/heatmap-layer/
