### ISSUE TITLE
Available images should not be hardcoded in expression runner harness

### ISSUE THREAD

**Issue by alexshalamov** [mapbox/mapbox-gl-js#8933]
Images that are available during expression evaluation should be part of an expression test.

Because of that, in native, I had to hardcode "monument-15" into expression runner.

/cc @ryanhamley

**Comment by ryanhamley** [comment]
@alexshalamov I posted https://github.com/mapbox/mapbox-gl-js/pull/8935 to fix this. Let me know if that solves your issue on native or not.
