### ISSUE TITLE
Overlaping PopUp

### ISSUE THREAD

**Issue by diouck** [mapbox/mapbox-gl-js#8938]
Hello,
I have an application with several points that overlap. How to manage the popup to display one by one all the pop
Thank you

**Comment by ahk** [comment]
Hi, are you trying to find out how to select all the overlapping points when many of them are clicked at once? Would you like to cycle through on click one by one, or instead show a list and allow the user to select?

**Comment by diouck** [comment]
Hello,
Thank you for your answer. In fact, I have only one point layer with for example 3 overlapping point. I would like to display popups one by one with for example a button before and after.


it will be rather to go from one click to another, or rather to display a list

I also find examples but do not solve the problem
https://gis.stackexchange.com/questions/253694/combining-popup-info-from-overlapping-polygons-in-mapbox-gl-js

Thanks!

**Comment by mourner** [comment]
Closing as an application-side question, not a GL JS issue.
