### ISSUE TITLE
Geolocation fails in Chrome (no error)

### ISSUE THREAD

**Issue by janeschindler** [mapbox/mapbox-gl-js#8947]
When I click the geolocator in the mapbox gl js demo in Chrome (https://docs.mapbox.com/mapbox-gl-js/example/locate-user/), I am asked to share my location. I click yes. The locator spins indefinitely, I am never located, and there is no console error.
My version of Chrome is Version 78.0.3904.70 (Official Build) (64-bit). 
Geolocation works fine in Safari for me.

**mapbox-gl-js version**: 1.5.0

**browser**: Chrome Version 78.0.3904.70 (Official Build) (64-bit)

### Steps to Trigger Behavior

 1. Click geolocate in example
 2. I am not located

### Link to Demonstration
https://docs.mapbox.com/mapbox-gl-js/example/locate-user/

### Expected Behavior
I should be located

### Actual Behavior
I am not located

**Comment by andrewharvey** [comment]
Can you test other sites that use geolocation in Chrome to see if it's specific to GL JS or your Chrome install?

**Comment by ahk** [comment]
Currently I can't reproduce this on macOS Catalina, Chrome Version 78.0.3904.97 (Official Build) (64-bit)
