### ISSUE TITLE
The drawing line looks like broken

### ISSUE THREAD

**Issue by zhaojinkun** [mapbox/mapbox-gl-js#8951]
I use the following code to draw line, but the lines looks like broken,could you help to check it.Thank you.
my code is:
```
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title>Add an image</title>
    <meta name='viewport' content='initial-scale=1,maximum-scale=1,user-scalable=no' />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.5.0/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.5.0/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:100%; }
    </style>
</head>
<body>

<div id='map'></div>
<script>
mapboxgl.accessToken = '<your token>';
var mapStyle = {
    "version": 8,
    "name": "Dark",
    "sources": {
        "mapbox": {
            "type": "vector",
            "tiles": ["https://d25uarhxywzl1j.cloudfront.net/v0.1/{z}/{x}/{y}.mvt"],
        },
    },
    "sprite": "mapbox://sprites/mapbox/dark-v10",
    "glyphs": "mapbox://fonts/mapbox/{fontstack}/{range}.pbf",
    "layers": [
        {
            "id": "background",
            "type": "background",
            "paint": {"background-color": "#111"}
        },
        {
            "id": "ext_lane_boundary",
            "source": "mapbox",
            "source-layer": 'mapillary-sequences',
            "type": "line",
            "layout": {
                "line-cap": "butt",
                "line-join": "miter",
            },
            paint: {
                'line-color': 'red',
                'line-width': {
                    base: 1.55,
                    stops: [[6, 4], [14, 7]],
                },
            },
        },
    ]
};

var map = new mapboxgl.Map({
    container: 'map',
    maxZoom: 14,
    minZoom: 6,
    zoom: 12,
    center: [-87.622088, 41.878781],
    style: mapStyle
});

</script>

</body>
</html>

```
<img width="1257" alt="line_broken" src="https://user-images.githubusercontent.com/22229652/68266974-a8c29500-008b-11ea-87ed-d8284d408313.png">

**Comment by ansis** [comment]
It looks like the data in your tiles is clipped exactly to the tile boundaries. There needs to be some extra padding in order to avoid these artifacts. For example, if you have a line going across a tile with an extent of 4096 it should extend a bit past 0 on the left side and a bit past 4096 on the right side.

**Comment by zhaojinkun** [comment]
Dear ansis:
  I have checked the geometry which between two tile,I found the geometry is serial.
  tile 1: geometry is  [4096L, 1887L], [3043L, 2365L], [1321L, 3147L], [0L, 3746L]
  tile 2: geometry is [4096L, 3746L], [3948L, 3813L], [3322L, 4096L]

  could you help me to check why the connect position which between two tiles is broken.

<img width="676" alt="line_broken_issue" src="https://user-images.githubusercontent.com/22229652/70133689-930fb200-16c1-11ea-8265-9dadb38d694d.png">
<img width="827" alt="line_broken_geometry_sequence" src="https://user-images.githubusercontent.com/22229652/70133691-93a84880-16c1-11ea-8e9a-5613c45257ce.png">

**Comment by zhaojinkun** [comment]
Dear ansis：
  if i can fix this issue by setting the mapbox style,as I can't change the vector data in the service.

**Comment by kkaefer** [comment]
No, that's not something Mapbox GL can do.
