### ISSUE TITLE
How do scale image marker when zoom in and zoom out

### ISSUE THREAD

**Issue by phanthinh** [mapbox/mapbox-gl-js#8964]
**mapbox-gl-js version**: latest version

### Question: How do scale image marker when zoom in and zoom out

This is my issue (see my attachment). When i zoom in or zoom out then image marker need to scale with current zoom as well. `Mapbox gl js` can be do it?
![how-do-scale-image-maker-when-zoom](https://user-images.githubusercontent.com/5910795/68592227-1aa04180-04c5-11ea-924c-af7a1eca51aa.gif)

This is my code 
`
  var div = document.createElement('div');
  div.style.borderStyle = 'none';
  div.style.backgroundSize = 'contain';
  div.style.backgroundRepeat = 'no-repeat';
  div.style.borderWidth = '0px';
  div.style.position = 'absolute';
  div.style.width = floors[0].width + 'px';
  div.style.height = floors[0].height + 'px';

  // Create the img element and attach it to the div.
  var div_image = document.createElement('div');
  div_image.style.backgroundSize = 'contain';
  div_image.style.backgroundRepeat = 'no-repeat';
  div_image.style.width = '100%';
  div_image.style.height = '100%';
  div_image.style.position = 'absolute';
  div_image.classList.add('image_overlay');

  var img = document.createElement('img');
  img.src = floors[0].url;
  img.style.width = '100%';
  img.style.height = '100%';
  img.style.opacity = '0.4';

  div_image.appendChild(img);
  div.appendChild(div_image);
  var el = div;

  markers.push(new mapboxgl.Marker({element: el, draggable: true})
    .setLngLat(coordinates)
    .addTo(map));

  var overlay = $( '.image_overlay' );
  overlay.attr('data-width', floors[0].width);
  overlay.attr('data-height', floors[0].height);

  overlay.resizable({
    aspectRatio: true,
    handles: 'ne, se, sw, nw',
    stop: function( event, ui ) {
      var width = ui.size.width;
      var height = ui.size.height;
      overlay.attr('data-width', width);
      overlay.attr('data-height', height)
    }
  });`

Best regards,
Phan Thinh

**Comment by ansis** [comment]
The best way to do this is probably with an `ImageSource`. You can specify the locations of all four corners of the image and mapbox-gl-js will scale and translate the image for you https://docs.mapbox.com/mapbox-gl-js/api/#imagesource.

**Comment by phanthinh** [comment]
@ansis I know but when use `ImageSource` then I can't resizable polygon image. Can you help me a new way for this?

**Comment by ansis** [comment]
I'm not sure I fully understand what you are trying to achieve, but if you want to resize the marker on zoom you can

```
map.on('render', function() {
    const scale = Math.pow(2, map.getZoom());
    // set css size based on scale
});
```

**Comment by cwills** [comment]
@phanthinh - did you ever find a solution?

**Comment by viktor2312456** [comment]
> I'm not sure I fully understand what you are trying to achieve, but if you want to resize the marker on zoom you can
> 
> ```
> map.on('render', function() {
>     const scale = Math.pow(2, map.getZoom());
>     // set css size based on scale
> });
> ```

Thank you very much
React variant
```
const map = useRef(null);
   map.current = new maplibregl.Map();
  useEffect(() => {
      const centerCoordinates = [30.459211, 50.368835];
      const desiredSizeInMeters = 5000; // Set the base size in meters

      // Add a custom HTML element at the center of the circle
      const customElement = document.createElement("div");
      customElement.className = "custom-element";
      customElement.style.background = "linear-gradient(#e66465, #9198e5)"; // Style as needed
      customElement.style.borderRadius = "50%";
      customElement.style.display = "flex";
      customElement.style.alignItems = "center";
      customElement.style.justifyContent = "center";
      customElement.innerHTML = "<div>Custom Element</div>"; // Add your content here

      const marker = new maplibregl.Marker({
        element: customElement,
        rotationAlignment: "map",
        pitchAlignment: "map",
      })
        .setLngLat(centerCoordinates)
        .addTo(map.current);

      // Function to calculate pixel size from meters
      const calculatePixelSizeFromMeters = (meters) => {
        const centerPixel = map.current.project(centerCoordinates);
        const northCoordinates = [centerCoordinates[0], centerCoordinates[1] + meters / 111320]; // Roughly 1 meter in latitude
        const northPixel = map.current.project(northCoordinates);
        return Math.abs(northPixel.y - centerPixel.y);
      };

      // Update custom element size on zoom
      const updateElementSize = () => {
        const pixelSize = calculatePixelSizeFromMeters(desiredSizeInMeters);
        customElement.style.width = `${pixelSize}px`;
        customElement.style.height = `${pixelSize}px`;
      };

      // Initial size update
      updateElementSize();

      // Update size on zoom change
      map.current.on("zoom", updateElementSize);

      // Clean up event listener on unmount
      return () => {
        map.current.off("zoom", updateElementSize);
      };
    
  }, [map]);
```
