### ISSUE TITLE
map.fitBounds does not animate

### ISSUE THREAD

**Issue by jfrankl** [mapbox/mapbox-gl-js#8970]
**mapbox-gl-js version**: 1.2.0+

**browser**: Chrome 78.0.3904.97

### Steps to Trigger Behavior

 1. Use fitBounds on any Mapbox GL JS project (example: run `map.fitBounds([[-133, 16], [-68, 50]])`) using version 1.2.0 or later

### Link to Demonstration

Mapbox GL JS 1.1.0 (animation when you click "Test fitBounds" button): https://jsfiddle.net/hdwjby38/14/
Mapbox GL JS 1.2.0 (no animation when you click "Test fitBounds" button): https://jsfiddle.net/3svo9Lmf/7/

### Expected Behavior

In earlier versions of Mapbox GL JS, running fitBounds would animate to the new location.

### Actual Behavior

It appears that as of 1.2.0, the camera no longer animates. I could not find any mention of a change in the release notes, so I am assuming this is a bug. Setting an option like `duration: 1000` seems to have no effect. I tested on 1.5.0 and it has the same issue.

**Comment by ryanhamley** [comment]
The `flyTo` animations work as expected for me in both examples. You most likely have your computer or browser set to reduce motion which is now detected by [`prefers-reduced-motion` starting in 1.2.0](https://github.com/mapbox/mapbox-gl-js/pull/8494)

**Comment by jfrankl** [comment]
@ryanhamley that's definitely it. Thank you.
