### ISSUE TITLE
Deformation of the map

### ISSUE THREAD

**Issue by qkaibo** [mapbox/mapbox-gl-js#8973]
**mapbox-gl-js version**:
1.3.1 1.4.1  1.5.0  

**browser**:
chrome

I drew two vertical lines. 
show in QGIS tool is ok!
![image](https://user-images.githubusercontent.com/20093077/68736378-741a8480-061b-11ea-8702-0f0780d495f0.png)

show in Arcmap also is OK!
![image](https://user-images.githubusercontent.com/20093077/68736438-a330f600-061b-11ea-83db-d39621bfee38.png)

But use mapbox show this map , then get the deformation of the map!
The Angle between the two lines becomes about 94 degrees!WHY?
![image](https://user-images.githubusercontent.com/20093077/68736530-dc696600-061b-11ea-84f5-41cd8fa83638.png)

Geojson of this map.
{
type: "FeatureCollection",
features: [
{
type: "Feature",
id: "FF.1",
geometry: {
type: "MultiLineString",
coordinates: [
[
[
113.83687224,
34.55840554,
0
],
[
113.8372535,
34.55833453,
0
]
]
]
},
geometry_name: "the_geom",
properties: {
Id: 0
}
},
{
type: "Feature",
id: "FF.2",
geometry: {
type: "MultiLineString",
coordinates: [
[
[
113.83707306,
34.55836785,
0
],
[
113.83702164,
34.5580918,
0
]
]
]
},
geometry_name: "the_geom",
properties: {
Id: 0
}
}
],
totalFeatures: 2,
numberMatched: 2,
numberReturned: 2,
timeStamp: "2019-11-13T05:43:19.658Z",
crs: {
type: "name",
properties: {
name: "urn:ogc:def:crs:EPSG::4326"
}
}
}

**Comment by mourner** [comment]
@qkaibo can you please provide a live test case (e.g. on JSFiddle or JSBin), as noted in the bug report template?

**Comment by qkaibo** [comment]
@mourner  https://jsfiddle.net/qkaibo/sncmk9b1/2/

**Comment by Plantain** [comment]
It's your projection - in EPSG:4326 those are perpendicular, but not in EPSG:3857 that is used by Mapbox.

**Comment by qkaibo** [comment]
What should I do if I want to display two vertical lines on the map?

**Comment by ansis** [comment]
@qkaibo you can use [`MercatorCoordinate`](https://docs.mapbox.com/mapbox-gl-js/api/#mercatorcoordinate`) to help with this:

```
const center = MercatorCoordinate.fromLngLat(centerLngLat);
const offset = [x, y];
const endA = new MercatorCoordinate(center.x + x, center.y + y, 0).toLngLat();
const endB = new MercatorCoordinate(center.x + y, center.y -x, 0).toLngLat();

// The lines center -- endA and center -- endB will be perpendicular
```

The general idea is to project your location into the projected coordinate space. Then add the offsets. Then unproject back to lnglat.

**Comment by qkaibo** [comment]
thanks @ansis   It' a good suggestion!
