### ISSUE TITLE
Marker wrong positioning with anchor

### ISSUE THREAD

**Issue by cs09g** [mapbox/mapbox-gl-js#8976]
**mapbox-gl-js version**:
v1.5.0
**browser**:
Chrome 78.0.3904.97
### Steps to Trigger Behavior

 1. add Marker with anchor: "bottom"
 2. zoomIn, zoomOut
 3. Marker is moving out from the position.

### Link to Demonstration
https://jsfiddle.net/cs09g/crnhkuje/

### Expected Behavior
marker should be at South Korea.

### Actual Behavior
marker is moving north.

the red dot tends to work as actual anchor.
![image](https://user-images.githubusercontent.com/7428017/68832996-b0baae80-06f5-11ea-9ef2-2f7f23d3544a.png)

**Comment by andrewharvey** [comment]
What's happening is the default marker has an offset built into it to ensure the tip is at the coordinates, however when you set the anchor then it breaks that.

So what's the use case for using the default marker and setting the anchor? Perhaps we should add a console warning or just ignore the anchor when using the default marker.

**Comment by andrewharvey** [comment]
This is the same issue as was just reported again at #9717. If we can improve the documentation or console warnings, feel free to propose that with a PR.
