### ISSUE TITLE
Prevent @2x tiles from being loaded on a Mapbox raster source

### ISSUE THREAD

**Issue by Plantain** [mapbox/mapbox-gl-js#8978]
@2x mapbox.terrain-rgb tiles are unreasonably large for slow/mobile internet connections (>400KB/tile), causing slow map load speeds.

@2x DPI is not necessary for many use cases, but there seems to be no way to override this choice.

I propose that if tileSize: 256 is set on a mapbox:// source, it will force the @1x tiles much like specifying tileSize:512 forces the @2x tiles at https://github.com/mapbox/mapbox-gl-js/blob/2020f3f9ced516086508925411bd098fbb4c3234/src/util/mapbox.js#L118

**Comment by ansis** [comment]
The  existing [`tileSize`](https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources-raster-tileSize) property is already used for the display size so we can't use it for the dpi unfortunately. I think we should look into:
- does high dpi ever make sense for terrain rgb layers?
- a way of disabling high dpi
    - does this need to be per-source or can it be per-map?

Is disabling something that would be useful for all raster layers or just terrain?

**Comment by Plantain** [comment]
I'm not convinced high DPI does make sense for terrain-rgb, but attempts to get it to render side by side by manually overriding the @2x trigger very different rendering for some reason that I suspect is unrelated. If someone else is able to produce a demo I would be interested to see how it compares.

For my use case I would be content to disable it per-map, but I think more generally having it per-source makes more sense - it seems plausible some sources will have more detail in their dataset than others.

**Comment by Plantain** [comment]
![ex2](https://user-images.githubusercontent.com/319895/69478556-b4cc8780-0deb-11ea-9e99-6bb9ed95a59b.png)
![ex](https://user-images.githubusercontent.com/319895/69478557-b4cc8780-0deb-11ea-99ab-130226e3f3a3.png)

See the difference between:
    map.addSource('dem', {
             "type": "raster-dem",
             "tiles": ["https://api.mapbox.com/v4/mapbox.terrain-rgb/{z}/{x}/{y}@2x.webp?sku=101izN5FVC2dN"]
          });
and
    map.addSource('dem', {
             "type": "raster-dem",
              "url": "mapbox://mapbox.terrain-rgb"
          });

This makes it quite hard to compare whether `@2x` is offering anything - any ideas why there is such a rendering difference from changing the URL?

**Comment by andrewharvey** [comment]
Well 2x is twice the resolution which is effectively the next zoom level up for regular tiles. Would be interesting to see a comparison between native zoom, and overzoom by 1, by 2, by 3 zooms etc.

**Comment by Plantain** [comment]
This is comparing 2x tiles to 2x tiles.
The only difference is whether it's specified via
map.addSource('dem', {
"type": "raster-dem",
"tiles": ["https://api.mapbox.com/v4/mapbox.terrain-rgb/{z}/{x}/{y}@2x.webp?sku=101izN5FVC2dN"]
});
or
map.addSource('dem', {
"type": "raster-dem",
"url": "mapbox://mapbox.terrain-rgb"
});

**Comment by ansis** [comment]
V2 never loads @2x tiles for dem sources!

https://github.com/mapbox/mapbox-gl-js/blob/b3e7319c296ac2612a0e283adc7c1e5a6a57ab1c/src/source/raster_dem_tile_source.js#L43
