### ISSUE TITLE
Div on Top of map is Draggable

### ISSUE THREAD

**Issue by projectcalix** [mapbox/mapbox-gl-js#8981]
I currently have a div which sits on top of Mapbox that displays Data.
However, I am able to interact with the map by clicking/dragging within the div window.

Is there a way to turn off interaction while within the div window?

**Comment by mourner** [comment]
@projectcalix would you be able to fill in the original bug report form, including a live minimal test case for the issue?

**Comment by projectcalix** [comment]
need to do more research, will re-open
