### ISSUE TITLE
Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.

### ISSUE THREAD

**Issue by bravecow** [mapbox/mapbox-gl-js#8986]
Version: 1.4.0

From Sentry:

`TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.`

Windows 7, Chrome Version: 78.0.3904

![image](https://user-images.githubusercontent.com/988471/69060918-e676d480-0a20-11ea-81a2-81ce2f5d8ea3.png)

![image](https://user-images.githubusercontent.com/988471/69060960-fb536800-0a20-11ea-9e72-b2205a94bf22.png)

![image](https://user-images.githubusercontent.com/988471/69060994-09a18400-0a21-11ea-859c-1812b875f5aa.png)

I also should note that we use mapbox map with `mapboxgl.supported()` method.

**Comment by ryanhamley** [comment]
This has been reported before https://github.com/mapbox/mapbox-gl-js/issues/6312 but it doesn't seem like anyone was ever able to nail down a reproducible example or a potential cause.

**Comment by bravecow** [comment]
FYI: https://stackoverflow.com/questions/50684887/is-there-any-maps-per-page-limitation-in-mapbox-gl

> I'm trying to have 17 small maps on the same page using mapbox-gl and facing:
> WARNING: Too many active WebGL contexts. Oldest context will be lost.
> Uncaught TypeError: Failed to execute 'shaderSource' on 'WebGLRenderingContext': parameter 1 is not of type 'WebGLShader'.

**Comment by bravecow** [comment]
I opened ~50 tabs with fully loaded maps and didn't get any error (Catalina + latest Chrome). Maybe someone will have a better luck to reproduce it.

**Comment by bravecow** [comment]
+1 for multiple tabs issue: https://github.com/mapbox/mapbox-gl-js/issues/6312#issuecomment-555620885

**Comment by ansis** [comment]
I was able to reproduce this by triggering gl context loss just before a shader is created. In this case the map is already failing to render so the error is fairly harmless but I opened a PR to clean up the logs: https://github.com/mapbox/mapbox-gl-js/pull/9017
