### ISSUE TITLE
Marker for 3D building

### ISSUE THREAD

**Issue by bravecow** [mapbox/mapbox-gl-js#8988]
## Motivation

For now you can highlight 3D building only with color. For data viz sometimes we need to highlight multiple features. For example, building can be **filtered** (for example, gray color) and in your **favorites**.

Using current pin you can do something like that:

![image](https://user-images.githubusercontent.com/988471/69073798-c2be8900-0a36-11ea-9570-6763dac96f9d.png)

## Design

![image](https://user-images.githubusercontent.com/988471/69077427-48920280-0a3e-11ea-96f1-7a79376cecef.png)

### Implementation

```
{
    'fill-extrusion-color': ...,
    'fill-extrusion-base': ...,
    'fill-extrusion-height': ...,
    'fill-extrusion-opacity': ...,
    'fill-extrusion-vertical-gradient': false,
    'icon-image': 'favorite',
    'icon-...': '...',
}
```

**Comment by mourner** [comment]
What's the advantage of having this as a new style spec property? I believe we don't want to add complexity (both in terms in code & API) where there's already an easy solution.

**Comment by bravecow** [comment]
Advantage is you do not cover main object. Games do the same with HP bar over buildings and units, for example:

![image](https://user-images.githubusercontent.com/988471/69078948-9eb47500-0a41-11ea-9f4e-f8b8be2782ab.png)

**Comment by ryanhamley** [comment]
I think this could be covered by implementing https://github.com/mapbox/mapbox-gl-js/issues/3993

**Comment by bravecow** [comment]
> I think this could be covered by implementing #3993

Sure. Thanks, didn’t see this issue.

**Comment by ryanhamley** [comment]
Cool, let's close this to concentrate discussion there
