### ISSUE TITLE
doubleClickZoom not working on ios chrome browser

### ISSUE THREAD

**Issue by GULERTOLGA** [mapbox/mapbox-gl-js#8989]
**mapbox-gl-js version**:
v.1.5.0
**browser**:
ios 13.1.3 Chrome mobile browser
### Steps to Trigger Behavior

 1. Open https://docs.mapbox.com/mapbox-gl-js/example/toggle-interaction-handlers/ on ios chrome and try to zoom by double tap

### Link to Demonstration
https://docs.mapbox.com/mapbox-gl-js/example/toggle-interaction-handlers/ 

### Expected Behavior
Zoom to tapped point
### Actual Behavior
only zoom after disable touchZoomRotate and dragPan events together

**Comment by ryanhamley** [comment]
If I'm understanding correctly, you're reporting that on iOS Chrome, you cannot zoom in by double clicking until you turn off both `touchZoomRotate` and `dragPan`? I cannot reproduce this behavior. Everything looks like it's working as expected in that example on my device. Can you give more information about what you're seeing?

**Comment by GULERTOLGA** [comment]
Yes as you understand, I opened the web page in my iphone chrome browser and double-clicked to map. But nothing happens. It works fine when I disable touchZoomRotate and dragPan events.

Actually, I'm having this problem on my flutter webview plugin, but it's happening at my mobile chrome browser too. 

thanks.

**Comment by kkaefer** [comment]
I can't reproduce this either.
