### ISSUE TITLE
"Geometry exceeds allowed extent, reduce your vector tile buffer size"

### ISSUE THREAD

**Issue by dmytro-gokun** [mapbox/mapbox-gl-js#8992]
This was initially reported in https://github.com/mapbox/mapbox-gl-js/issues/8639, but that issue is closed now.

The thing is that mapbox outputs lots of these warnings to the console which totally screws our e2e tests.

Is there any plans to fix this?

**Comment by kkaefer** [comment]
What version of Mapbox GL JS are you using? Are you using tiles from api.mapbox.com? If so, at what locations do these warnings occur?

**Comment by dmytro-gokun** [comment]
> What version of Mapbox GL JS are you using?

1.5.0

> Are you using tiles from api.mapbox.com?

Yes. For example: mapbox://styles/mapbox/streets-v9.

>  If so, at what locations do these warnings occur?

E.g. zoom=9, center=[-74.50, 40]. 

Another example would be mapbox://styles/mapbox/light-v9, zoom=15.5, center=[-74.0066, 40.7135].
These are by no means the only points.

NB. Here: https://github.com/mapbox/mapbox-gl-js/issues/8639#issuecomment-539564574, @mourner said: "This seems to be a minor issue with some tiles in Mapbox Streets on our side — you can safely ignore the warning while we investigate a fix". So the question is... is that investigation still in progress? Is there any update for that?

**Comment by mourner** [comment]
It's in progress, but we have no updates on when this will be fixed on the data side yet. I think you should fix your e2e testing setup anyway — console warnings shouldn't be a blocker for anything.

**Comment by dmytro-gokun** [comment]
@mourner You are (probably) right about e2e tests. But that's only one side of the problem. The other side is that it spams the console and makes debugging harder. Also, a minor inconvenience, that's true. But nevertheless, it makes sense to have that fixed. The problem is not new, many people suffer from it. Would be really nice to have this fixed.

**Comment by awulkan** [comment]
I'm getting 6 of these warnings every time I load the map or change map style in our app. It's centered on Sweden at zoom level 4. Not a blocker, but as dmytro-gokun said it clutters the console.

**Comment by mourner** [comment]
It outputs one warning per worker thread (but not more) whenever it encounters an affected tile. The data-side fix will take some time, so meanwhile we have two options — either leave the warnings as is for now, or remove them completely but have a risk of some users having rare rendering issues when using badly tiled data that exceeds maximum extent without any indication of what's exactly wrong. 

I'll try to come up with some middle ground — perhaps we can suppress the warning if the clamping is within some small threshold (the current warnings with Mapbox Streets are triggered by a 1px-off error).

**Comment by derwaldgeist** [comment]
+1

Getting this in combination with react-map-gl, when zooming out. We're using maptiler as a tile service, should this be relevant.

**Comment by kkaefer** [comment]
@derwaldgeist This warning is caused because vector tiles contain geometry that exceeds the allowed extent. It's not a problem with Mapbox GL itself but with the vector data source. That means that if you're using a third-party data source, they have to fix this problem on their side.

**Comment by derwaldgeist** [comment]
@kkaefer Ok, thanks, good to know.

**Comment by lastzero** [comment]
Using Mapbox GL for one day and instantly came across this issue:
https://demo.photoprism.org/places/s2:80858741f414

San Francisco seems to be especially affected!
Looks like we need to report this to our third party source :D

**Comment by FrancescoSaverioZuppichini** [comment]
Same here

**Comment by NickPepper** [comment]
MapBox v1.8.1 still has this annoying issue...

**Comment by kkaefer** [comment]
This warning is caused because vector tiles contain geometry that exceeds the allowed extent. It's not a problem with Mapbox GL itself but with the third-party vector data source you're using. I recommend switching to [Mapbox-hosted vector tiles](https://www.mapbox.com/maps/).

**Comment by mourner** [comment]
Sorry for not addressing this yet — since this does not affect the map experience in any way, and only surfaces as a couple warnings in the dev console, we've been focusing on more pressing issues. But if this is really as annoying as the comments seem to suggest, perhaps we should prioritize a client-side fix, at least for the Streets source (where the trigger is a tiny off-by-one-pixel issue). 

We've locked the thread to avoid "+1" type of comments — please upvote the issues you want fixed instead, this helps us prioritize them.

**Comment by saifulkhan** [comment]
I am also getting the same warning. We are using Mapbox in our Ionic/Angular project.
