### ISSUE TITLE
Map.project(...) return an error value when the map is tilted and enlarged

### ISSUE THREAD

**Issue by yeniao96** [mapbox/mapbox-gl-js#8995]
**mapbox-gl-js version**:  1.5.0

**browser**:  chrome

### Steps to Trigger Behavior

 1.  Tilt the map;
 2.  zoon in;
 3.  move the map until the target point is off screen;
 4.  use 'map.project' to get coordinates of the target point;

### Expected Behavior

get a right value (e.g., [435, 1583])

### Actual Behavior

get an error value (e.g., [-1262, -64553] )

**Comment by mourner** [comment]
Can you please provide a minimal live test case (e.g. on JSFiddle) so that it's easier for us to diagnose the issue?

**Comment by yeniao96** [comment]
This is a test case . [Coordinate transformation](https://jsfiddle.net/yeniao/1gyvh48z/51/) 
Keep the pitch and drag down the map to make the red point be out of the map. 
Look at the value at the top left of map , in the correct case, the value should be positive, but drag to a certain degree, the value will become negative. 
How did this happen?

**Comment by yeniao96** [comment]
> 您能否提供一个最小的实时测试用例（例如在JSFiddle上），以便我们更轻松地诊断问题？

This is a test case . [Coordinate transformation](https://jsfiddle.net/yeniao/1gyvh48z/51/) 
Keep the pitch and drag down the map to make the red point be out of the map. 
Look at the value at the top left of map , in the correct case, the value should be positive, but drag to a certain degree, the value will become negative. 
How did this happen?

**Comment by yeniao96** [comment]
> Can you please provide a minimal live test case (e.g. on JSFiddle) so that it's easier for us to diagnose the issue?

This is a test case . Coordinate transformation
Keep the pitch and drag down the map to make the red point be out of the map.
Look at the value at the top left of map , in the correct case, the value should be positive, but drag to a certain degree, the value will become negative.
How did this happen?

**Comment by ansis** [comment]
Thanks for the test case. I'm not sure this is a bug.

The point goes from positive to negative as it goes behind the camera. If you imagine a viewport that was infinitely large and a field of view that was 180 degrees you would still only be able to project things that are in from of the camera.

Negative values are weird but they fit in with how projections work. We could return NaN or something like that but then `map.unproject(map.project(lngLat))` would not return the same value (which it does now).
