### ISSUE TITLE
IE11 tile queue regression

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#8998]
Capturing @arindam1993 https://github.com/mapbox/mapbox-gl-js/pull/8913#issuecomment-553622495 to make sure we address it before doing a release:

> this PR could bring back the issue of requests being stuck in the pending state on IE11 when tile requests get cancelled, I just did some testing and it looks like it has 😬.

**Comment by arindam1993** [comment]
Did some testing to quantify the difference better:
I'm using the following debug page to trigger a large amount of tile load cancellations:
After the map `idle` event it rapidly zooms out and zooms back into the same spot.
```
<!DOCTYPE html>
<html>
<head>
    <title>Mapbox GL JS debug page</title>
    <meta charset='utf-8'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <link rel='stylesheet' href='../dist/mapbox-gl.css' />
    <style>
        body { margin: 0; padding: 0; }
        html, body, #map { height: 100%; }
    </style>
</head>

<body>
<div id='map'></div>

<script src='../dist/mapbox-gl-dev.js'></script>
<script src='../debug/access_token_generated.js'></script>
<script>

var map = window.map = new mapboxgl.Map({
    container: 'map',
    zoom: 12.5,
    center: [-77.01866, 38.888],
    style: 'mapbox://styles/mapbox/streets-v10',
    hash: true
});

map.once('idle', function(){
    map.easeTo({ center: [-77.01866, 38.888], zoom: 1, duration: 1000});

    setTimeout(function(){
        map.easeTo({ center: [-77.01866, 38.888], zoom: 12.5, duration: 1000});
    }, 1200)
});

</script>
</body>
</html>
```

And here are the results:

| browser      | 1.5.0 | 1.5.1-beta |
|--------------|-------|------------|
| chrome (osx) | ~40   | ~70        |
| ie 11        | ~25   | ~120       |

The number indicates the number of requests sent out by looking at the network tab in the inspector.
