### ISSUE TITLE
queryRenderedFeatures Exception:  Cannot read property 'sub' of undefined

### ISSUE THREAD

**Issue by cdhuangyong** [mapbox/mapbox-gl-js#8999]
**mapbox-gl-js version**:
1.5.0
**browser**:
chorme
### Steps to Trigger Behavior

 1.  Layer type: fill-extrusion
      source geometry type :  MultiPolygon
 2.  When I call the method “queryrenderedfeatures” to query features，Sometimes an error is reported, like the title

  I found the rule that when the map level is relatively large, there will be no problem, while when the map level is relatively small, there will be some problems，I guess the simplification algorithm takes the length of the point less than 4

The location of the exception error：
（see:  https://github.com/cdhuangyong/issues/blob/master/error20191120.png?raw=true）
  **projectedFace[3] Sometimes undefined**

**Comment by cdhuangyong** [comment]
This problem will appear when my polygon data is simplified. I hope to solve this problem as soon as possible. Thank you

**Comment by ansis** [comment]
It looks like the image you're sharing is in a private repository. Could you share it publicly? A https://jsfiddle.net/ example that we can run would help us diagnose the issue

**Comment by cdhuangyong** [comment]
@ansis This is a demo I wrote. When the mouse moves into the face, it will throw an exception
[https://jsfiddle.net/cdhuangyong/hgopj9uw/](url)
