### ISSUE TITLE
Html in feature object

### ISSUE THREAD

**Issue by orshefi** [mapbox/mapbox-gl-js#9000]
Hi All,

TL;DR: What is the best practice of rendering dynamic HTML objects on the map?

These are the conclusions I have so far from reading the docs:
1. Mapbox uses markers to render HTML objects on the map.
2. Markers are ineffective as oppose to features and layers when used for a large number of objects.
3. The objects I need is constantly moving (Dynamic).
4. I stumbled upon this example: https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/
It seems that it uses markers that are being managed by a layer and optimized using the viewport (?)

Much appreciate your help :)

**Comment by ansis** [comment]
`marker.setLngLat(...)` is the only way to update the location of markers. Whenever the markers move you need to call this with the new location.

You're right that markers aren't that performant for large amounts of features. The example you linked adds the data to the map as regular features and then uses `querySourceFeatures` to figure out what features are visible and only creating markers for those features. This works well for features that don't move but it could be less performant if all the features are constantly moving. I'd suggest trying and seeing how well it works. If it's too slow you will probably need to implement your own way of figuring out which markers you need to show for the current viewport.

**Comment by orshefi** [comment]
Hi @ansis,

Thanks for the quick reply.

Are you familiar with an estimation of what amount of rendered markers should worry me?
Is there any example that you are familiar with that I can take inspiration from?

**Comment by ansis** [comment]
> Are you familiar with an estimation of what amount of rendered markers should worry me?

I'm not sure. I'd suggest trying it out with different amounts and seeing what feels acceptable to you.

> Is there any example that you are familiar with that I can take inspiration from?

I don't think we have any examples of supporting large amounts of html markers.
