### ISSUE TITLE
map.getstyle() can't get custom layer

### ISSUE THREAD

**Issue by ajiko** [mapbox/mapbox-gl-js#9001]
map.getstyle() method can get many layer in style but no custom layers, like deck.gl layer. how can I get all the layers include deck.gl layer?

**Comment by kkaefer** [comment]
Custom layers are explicitly excluded from `getStyle` in https://github.com/mapbox/mapbox-gl-js/blob/254674eecba53a275a77599fdac8908f9900c350/src/style/style.js#L322-L331. `getStyle` is used for serializing a style to a JSON data structure, and custom layers contain functions that are cannot be represented in JSON.

To obtain an individual custom layer, use `getLayer()`.

**Comment by mayteio** [comment]
Can we make this a feature request then? We have a scenario where we're adding n custom layers, and need to track what has been added without knowing their ids ahead of time. I thought prefixing and filtering `map.getStyle().layers` for this prefix would work, then I found this issue.

**Comment by mayteio** [comment]
Seems it just searches the _layers object?

https://github.com/mapbox/mapbox-gl-js/blob/254674eecba53a275a77599fdac8908f9900c350/src/style/style.js#L750-L758

Something like this could work:

```
/**
 * Return the style layer object with the given `id`.
 *
 * @param {string} id - id of the desired layer
 * @returns {?Object} a layer, if one with the given `id` exists
 */
getLayer(id: string): Object {
  return this._layers[id];
}

/**
 * Return style layers whose `id` matches a search string
 *
 * @param {string} search - search string to filter layer ids
 * @returns {?Object[]} an array of layers, if any that include the given `search` in their `id` exists
 */
getLayers(search: string): Object[]{
  return Object.entries(this._layers).filter(([id, layer]) => id.includes(search)).map(([,layer]) => layer)
}
```

**Comment by mayteio** [comment]
> map.getstyle() method can get many layer in style but no custom layers, like deck.gl layer. how can I get all the layers include deck.gl layer?

You can access it current with `map.style._layers[customLayerId]` - though I'm sure there's a reason `_layers` is private. Are you able to elaborate @kkaefer?

**Comment by kkaefer** [comment]
@mayteio same explanation as above: the idea of `getStyle` is to return a valid Style JSON file that conforms to the style specification. Custom layers inherently can't be part of a style document because they contain functions and always require the use of runtime styling. Therefore, you'll have to use individual `getLayer` calls. I recommend against using `map.style._layers[customLayerId]` in production code because this API is private and might change in future versions of Mapbox GL.

**Comment by mayteio** [comment]
OK great, thanks for the explanation. 

Unfortunately we have a situation with deck.gl where we have an array of layers that we add to Mapbox via @deck.gl/mapbox. If an item is removed from that array, we have no way of knowing what it’s ID was. Thus we prefix all layers with “custom-“, find them in mapbox, find the difference (I.e those who are in mapbox and not in the deck.gl array) and then remove them. The only way for us is to use map._layers as these custom layers are (rightly) not in the style JSON.

**Comment by marcofugaro** [comment]
So how do I get a list of all the layers I added?

`getLayers` even exists in [mapbox-gl-native](https://github.com/mapbox/mapbox-gl-native/pull/8195)

**Comment by mayteio** [comment]
When you call `map.addLayer`, prefix your layer id with `custom-`. Then you can get a list of all added layers with `map._layers.filter(l => l.id.includes('custom-'))`. You can then loop through these and remove them one by one.
