### ISSUE TITLE
Vibration in CustomLayer with hight zoom

### ISSUE THREAD

**Issue by ogiermaitre** [mapbox/mapbox-gl-js#9006]
**mapbox-gl-js version**: 1.5

**browser**: Chrome, Firefox and Safari, on macOS and Windows.

### Steps to Trigger Behavior

 1. Implements the NullIslandLayer as in documentation (moving the island to a detailed area).
 2. flyTo the island with a hight zoom factor (16x or higher).

### Link to Demonstration

A minimal example showing the problem: 
https://www.wikimaps.io/bugs/mb/null_island.html

A hard to see illustration:
![vibrations](https://user-images.githubusercontent.com/24251307/69327651-27076580-0c4e-11ea-85ea-84ac1b104e43.gif)

### Actual Behavior
We implement a custom layer based on the example provided in the documentation ([NullIslandLayer](https://docs.mapbox.com/mapbox-gl-js/api/#customlayerinterface)). We notice that when zooming closely on the data points we can see that they are vibrating, w.r.t. the background.
I put here a minimal example that shows the problem.

Note: as the api example, my example does not work on safari (because safari needs an attribute to be bounded the shader program). But I did a test, binding a dummy attribute and the same behavior can be observed.

**Comment by mourner** [comment]
This is a known issue — floating point in the shader can't represent the position with good enough precision. You'll have to follow [a more complicated example](https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/) that employs `MercatorCoordinate` utility and set the camera with some matrix transformations on render.
