### ISSUE TITLE
Aggreagate property of a cluster when using superclustering

### ISSUE THREAD

**Issue by badders** [mapbox/mapbox-gl-js#9007]
**mapbox-gl-js version**: latest

### Question

I have a layer with points that are being clustered. Each point has a 'colour' property that is used when rendering the individual point.

When rendering the cluster (filtered on has point_count) i would like to set the circle color property to be the 'average' of the colours of all the points, simply average the R, G and B values seperately. I cant seem to find a way to do this at the moment using the style expressions, is this possible? Can I write my own external function that is handed the list of points and returns the value I want?

**Comment by ansis** [comment]
I think it might be possible but tricky! I haven't tried but something like this maybe:

```
clusterProperties: {
"sum-r": ["+", ["at", 0, ["to-rgba", ["get", "colorprop"]]]],
"sum-g": ["+", ["at", 1, ["to-rgba", ["get", "colorprop"]]]],
"sum-b": ["+", ["at", 2, ["to-rgba", ["get", "colorprop"]]]]
}
```
docs for clusterProperties: https://docs.mapbox.com/mapbox-gl-js/style-spec/#sources-geojson-clusterProperties

```
"circle-color": ["rgb",
    ["/", ["get", "sum-r"], ["get", "point_count"]],
    ["/", ["get", "sum-g"], ["get", "point_count"]],
    ["/", ["get", "sum-b"], ["get", "point_count"]]]
```

> Can I write my own external function that is handed the list of points and returns the value I want?

Nope this is not possible right now.

**Comment by badders** [comment]
Thanks, i had completely overlooked the cluster properties
