### ISSUE TITLE
Fill and line layers on same tiled source data diverge based on zoom

### ISSUE THREAD

**Issue by dyakovlev** [mapbox/mapbox-gl-js#9009]
We are seeing an issue regarding fill vs. line alignment that affects layers generated from tiled data. 

**mapbox-gl-js version**: 1.5.0

**browser**: Chrome 78.0.3904.97

### Steps to Trigger Behavior

 1. use tippecanoe to build vector tiles for polygon geometries
 2. build a map with a tiled source and fill+line layers showing this tiled source (same initialized source for both)
 3. zoom to a corner of the geometry
 4. observe line layer detaching from fill layer in a different but deterministic way per unit zoom level

### Link to Demonstration

[JSBin link](https://output.jsbin.com/jipamojuza)

Static example -
<img width="433" alt="Screen Shot 2019-11-21 at 3 43 12 PM" src="https://user-images.githubusercontent.com/127997/69387716-8c258000-0c7b-11ea-8e1e-bee0965c41c9.png">

Animated example showing different issues and unit zoom -
![bad-simplification](https://user-images.githubusercontent.com/127997/69388061-8c724b00-0c7c-11ea-9654-e8b451c6c735.gif)

Sample geometry: [GeoJSON](https://github.com/mapbox/mapbox-gl-js/files/3877410/geoms.txt) or [Tiles](https://github.com/mapbox/mapbox-gl-js/files/3877425/tiles.zip)

### Expected Behavior

Border lines stay in their defined locations.

### Actual Behavior

Border lines seem to move or align to some sort of grid depending on zoom level.

I've tested with a `geojson` source type and inlined geojson, and cannot reproduce this behavior.

**Comment by dyakovlev** [comment]
One additional bit of context here is the tiles are generated only through z10, and the issues are exhibited on z14-z18. So, this *issue seems to only be triggered when the underlying data is overzoomed*.

**Comment by dyakovlev** [comment]
maybe related, but happening to a GeoJSON source - https://github.com/mapbox/mapbox-gl-js/issues/7023#issuecomment-517164123

Is my answer here to generate more zooms? Wondering why this only happens to line layers and not polygon layers.

**Comment by ansis** [comment]
Thanks for the good reproduction.

Yep, you're right that this is a result of overzooming.

It could be float truncation. The line tessellation sometimes creates new vertices to split a line segment. Without enough precision this interpolated vertex won't be close to the line segment.

Or maybe there is a precision issue in the shader.

> Is my answer here to generate more zooms? Wondering why this only happens to line layers and not polygon layers.

Yep, until this is fixed I think that will be your best solution.

**Comment by dyakovlev** [comment]
@ansis thanks for the confirmation. Do you have any expectation on when this would be worked on? (just for better reasoning around our internal fix's longevity..)

**Comment by ansis** [comment]
@dyakovlev I've opened a fix for it here https://github.com/mapbox/mapbox-gl-js/pull/9024 . This may make it into the next release that is scheduled to go out wednesday dec 4th.
