### ISSUE TITLE
Overlapping Markers at the same place

### ISSUE THREAD

**Issue by SwDebugMapbox** [mapbox/mapbox-gl-js#9013]
Hello,
In my current project, I display markers in different places but the problem is that when I unzoom all the markers gather in the same place and it becomes unreadable. Before that I displayed my points as a symbol layer and there was no problem for this with the option icon-allow-overlap, however I could not move them as it is possible to do with markers. In short, do you know how I could do to have the effect of the icon-allow-overlap option with markers ? 

Thanks ! :)

**Comment by ansis** [comment]
Unfortunately it's not possible to prevent collisions with markers.

[Here](https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/) is a complicated example that uses clustering to avoid overlap for markers, but since it also uses symbol layers it may be hard to make it work with markers that can move.

**Comment by SwDebugMapbox** [comment]
Okay thanks for your answer. I just watched your link, but this example is not representative of what I want to do in the project. In fact, markers are located in different floors in a building. So I would like to have a marker that gathers the others in the shape of spiders like the project mapboxgl-spiderifier. But it works with symbol layer too, have you an alternative for my problem ?

**Comment by mourner** [comment]
Yeah, I would suggest either following the clustering example, or hiding the markers with some manual logic that checks for collisions (if there are a lot of them, you could use an indexing library like https://github.com/mourner/rbush/).

There are no plugins for spiderfy-like behavior for markers, but you could make one! We're not planning on adding this to the library core though.

**Comment by SwDebugMapbox** [comment]
Hello,
If someone have the same problem, you can do like me : display layers all the time and when you want to move your layers you display them with markers draggable option at true.
