### ISSUE TITLE
Chrome Canary: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope'

### ISSUE THREAD

**Issue by robhawkes** [mapbox/mapbox-gl-js#9019]
**mapbox-gl-js version**: v1.5.0

**browser**: Chrome Canary v80.0.3977.0

### Steps to Trigger Behavior

 1. Open Mapbox example from documentation site (or any map) in latest Chrome Canary

### Link to Demonstration

https://docs.mapbox.com/mapbox-gl-js/example/simple-map/

### Expected Behavior

* Map will be displayed as usual, as it does in Chrome (not Canary).

### Actual Behavior

* Map background is displayed but nothing else appears
* Multiple errors in console related to Web Workers
* Maps worked in Chrome Canary as of end of last week

```
Uncaught DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': ArrayBuffer at index 59 could not be transferred.
    at a (blob:https://docs.mapbox.com/b78f2a61-03c1-407d-8d75-2d354d3a65c1:1:294044)
    at blob:https://docs.mapbox.com/b78f2a61-03c1-407d-8d75-2d354d3a65c1:1:349126
    at o.L (blob:https://docs.mapbox.com/b78f2a61-03c1-407d-8d75-2d354d3a65c1:1:346699)
    at blob:https://docs.mapbox.com/b78f2a61-03c1-407d-8d75-2d354d3a65c1:1:346086
    at Fu.process (blob:https://docs.mapbox.com/b78f2a61-03c1-407d-8d75-2d354d3a65c1:1:293928)
    at MessagePort.Vu.MessageChannel._channel.port2.onmessage (blob:https://docs.mapbox.com/b78f2a61-03c1-407d-8d75-2d354d3a65c1:1:292300)
```

### Screenshots

![Screen Shot 2019-11-25 at 12 11 10](https://user-images.githubusercontent.com/22612/69539594-c1341a00-0f7c-11ea-8d33-7220acb5efd4.png)
![Screen Shot 2019-11-25 at 12 10 59](https://user-images.githubusercontent.com/22612/69539595-c1341a00-0f7c-11ea-9f93-3009eec7dc46.png)

**Comment by daaain** [comment]
I have the same problem using Kepler.gl.

My hunch is that this is not a library issue, but something has changed in Chrome which prevents it to connect to the tile server and the worker cannot load the tiles any more.

**Comment by mourner** [comment]
Confirmed, investigating. Thanks for catching this!

**Comment by mourner** [comment]
All the errors happen when trying to transfer an zero-length array. Submitting a PR with a quick fix.

**Comment by mourner** [comment]
Here's a [corresponding Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1027937&) — please star it to indicate its importance to the Chromium team. Hopefully it will be fixed before this hits beta channel so we won't have to do lots of patch releases retroactively for previous minor versions.

**Comment by mourner** [comment]
This got fixed on the Chromium side. 🎉
