### ISSUE TITLE
featuresAt with radius 0/not defined only returns Polygons

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#902]
…bug? 
Can only find `LineString`/`Point`s if `radius` >= 1.

**Comment by lbud** [comment]
The above two functions (`lineContainsPoint`, `pointContainsPoint`) leave absolutely zero tolerance for what seem to be imperfect computations (see https://github.com/mapbox/mapbox-gl-js/issues/874 — it's impossible to mouse over a Point or LineString and see a result). Should we add a tiny bit of tolerance (i.e. change [this line](https://github.com/mapbox/mapbox-gl-js/blob/mb-pages/js/data/feature_tree.js#L112) to 
``` js
    if (distToSegmentSquared(p, v, w) < (r || 1)) return true;
```
and similarly in the point calculation)? Or is that…cheating?
@jfirebaugh

**Comment by jfirebaugh** [comment]
Well `radius` is supposed to provide that tolerance, right?

See #316 for relevant discussion -- for many/most uses cases of featuresAt, I think what we really want is paint-property-aware hit testing.

**Comment by lbud** [comment]
> Well `radius` is supposed to provide that tolerance, right?

I suppose so, yes, but it's weird that it's only possible to find Polygon features without providing a `radius`. It's not even that it's very hard to click on an exact LineString/Point; it's literally impossible to do so because of these calculations. The assumption would be that with `radius: 0` you should be able to find a feature on exact click/hover.

**Comment by lbud** [comment]
maybe even a `Math.floor` would be an ok answer here — I've logged the calculations at least from `lineContainsPoint` and when mousing over a line I've been able to log something like 0.16
