### ISSUE TITLE
Please modify the license field in package.json

### ISSUE THREAD

**Issue by rzyanhao** [mapbox/mapbox-gl-js#9027]
![image](https://user-images.githubusercontent.com/9431954/69639867-524be380-1098-11ea-95ef-515946d57627.png)
this format of license is not permitted by our code pre-checker
thank you!

**Comment by mourner** [comment]
This is a perfectly valid license value [as per NPM documentation](https://docs.npmjs.com/files/package.json#license). Please submit an issue to your code pre-checker or update its configuration.

**Comment by rzyanhao** [comment]
> This is a perfectly valid license value [as per NPM documentation](https://docs.npmjs.com/files/package.json#license). Please submit an issue to your code pre-checker or update its configuration.

yeah, it's valid,  but  I think it's hard for pre-checker to check the license, because there is no "BSD-3-Clause" string in the LICENSE.txt。The owner of our code pre-checker is looking for a method to check this, it's a hard work.
