### ISSUE TITLE
Slow performance when loading layers

### ISSUE THREAD

**Issue by ainhi90** [mapbox/mapbox-gl-js#9039]
I read some issues regarding layer loading performance, but I think my problem is different, so I decided to open a new Issue.

I have in mapbox a Style that has 3 custom layers I need for my application, but, apart from that, I also need to create quite a few layers after making a call to an API.

I will add an image of the application:
![show_test](https://user-images.githubusercontent.com/5947431/69815496-b8e71380-11f6-11ea-878e-938bc9840fd7.PNG)

As you can see, there are squares of different colors (the end application will have the whole highlighted part full of squares, not just in both sides). Each square has a unique ID and needs to be clickable so that, when clicked, some information is shown of that specific square.

The thing is that it takes a lot of time loading all the layers, and I need it to be faster. I read some people that say to combine layers, but I think, in my case, it can't be done, as each square needs to be independent.

I hope somebody knows what I can do, because, right now, I am stuck

Thanks in advance!!

**Comment by kkaefer** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

That said, you can combine layers by [using data-driven styling](https://docs.mapbox.com/help/how-mapbox-works/map-design/#data-driven-styles). This allows shapes on the same layer to be colored based on data in the source. You can [use queryRenderedFeatures](https://docs.mapbox.com/mapbox-gl-js/example/queryrenderedfeatures-around-point/) to determine what was clicked. With [feature states, you can create a hover effect too](https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/).
