### ISSUE TITLE
Premultiply sprites in workers

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#904]
We're seeing sprite premultiplication - https://github.com/mapbox/mapbox-gl-js/blob/mb-pages/js/style/image_sprite.js#L25-L44 this loop - as one of the biggest sync operations in gl-js. Is this something we could do in a worker?

**Comment by tmcw** [comment]
Am I correct in sensing that this _isn't_ a commonly-identified performance problem and we should close the ticket?

**Comment by lucaswoj** [comment]
@tmcw Yes, I think that's a fair conclusion. If this comes up in profiling we can revisit.
