### ISSUE TITLE
Cannot re-add attribution control without attribution property in TileJSON

### ISSUE THREAD

**Issue by cs09g** [mapbox/mapbox-gl-js#9051]
**mapbox-gl-js version**:
v1.6.1, v1.5.1, ... maybe more
**browser**:
latest chrome

### Steps to Trigger Behavior

 1. initialize a map with custom StyleJSON uses custom TileJSON which doesn't have `attribution` property. 
```javascript
var map = new mapboxgl.Map({
  style: "customStyle", // which means the file is not served from :mapbox
  attributionControl: false,
});
```
 2. add attribution control with `customAttribution`.
```javascript
var customAttribution = new mapboxgl.AttributionControl({
  customAttribution: "<a>abc</a>",
});
map.addControl(customAttribution);
```
 3. remove the attribution control.
```javascript
map.removeControl(customAttribution);
```
4. add the attribution control again.
```javascript
map.addControl(customAttribution);
```
### Expected Behavior
Attribution should be added again.

### Actual Behavior
Attribution wrapper is created but content's empty.

I suspect the attribution always empty from `source` so [here](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/control/attribution_control.js#L164) is always `true`.

**Comment by kkaefer** [comment]
Thanks for reporting this bug! Fix is in https://github.com/mapbox/mapbox-gl-js/pull/9052.
