### ISSUE TITLE
Should double-click & hold & scroll up/down work in GL JS?

### ISSUE THREAD

**Issue by tsuz** [mapbox/mapbox-gl-js#9053]
**mapbox-gl-js version**:

### Question

In Android and iOS SDK, there is a [feature](https://docs.mapbox.com/ios/api/maps/5.5.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)zoomEnabled) to "double tap & hold & pan up/down" which allows users to change the zoom level with one finger. In GL JS, this is not implemented although many websites can be viewed on mobile. From the [tests](https://github.com/mapbox/mapbox-gl-js/tree/2020f3f9ced516086508925411bd098fbb4c3234/test/unit/ui/handler), it seems feasible, but is there a reason behind this design? 

### Links to related documentation

[GL JS -> Double click zoom](https://docs.mapbox.com/mapbox-gl-js/api/#map#doubleclickzoom)
[iOS Docs -> Double Tap Zoom](https://docs.mapbox.com/ios/api/maps/5.5.0/Classes/MGLMapView.html#/c:objc(cs)MGLMapView(py)zoomEnabled)

**Comment by vakila** [comment]
Hi @tsuz , thanks for asking! Yes, this is something we plan to implement in the future, as part of some overall improvements we're making to our touch gesture handling. I don't have an exact timeline for you but stay tuned and you'll see this "quick zoom" interaction supported in an upcoming release.

**Comment by tsuz** [comment]
@vakila Thanks for the response. Looking forward to this!

**Comment by vakila** [comment]
No problem! 

Just to be clear, what we're planning to implement is the double-tap-hold-drag-up/down functionality for touch devices (aka "quick zoom" on some platforms) - we don't have any major changes for click/scroll handling planned as we already have scroll-to-zoom functionality for mouse users. (Just in case the issue title, which differs from the issue description, causes any confusion for folks following along.)

**Comment by tsuz** [comment]
@vakila 

> Just to be clear, what we're planning to implement is the double-tap-hold-drag-up/down functionality for touch devices (aka "quick zoom" on some platforms) 

So, on a touch device, let's say GL JS rendered on Chrome in mobile would be able to perform "double-tap-hold-drag-up/down" functionality? Whereas if you double click and drag up via a mouse, it will not do have the same behavior as the mobile one? If so, how will you be determining one over the other?

**Comment by vakila** [comment]
@tsuz Correct. On a touch device users will be able to zoom the map with the single-finger double-tap-hold-drag (quick zoom) gesture, as well as the current two-finger pinch to zoom in/out.  Users interacting with the map via a mouse on a desktop browser will have the existing mouse controls, which include double-click to zoom in, and scroll to zoom in/out. We don't have any plans to implement an additional double-click-hold-drag mouse interaction; to my knowledge that's not a common interaction supported by other maps, nor something users have come to expect or ask for.
 
> how will you be determining one over the other?

Essentially the same way we do already: Events coming from the mouse vs. touch are of different types, so we can detect what type of interaction it is and react appropriately. A given handler might respond to only one type of event (as with the [TouchZoomHandler](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/handler/touch_zoom_rotate.js) or [KeyboardHandler](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/handler/keyboard.js) for example) or a handler might listen to multiple types of events and react appropriately based on the event type (as in the [DragPanHandler](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/handler/drag_pan.js) for example).

**Comment by ansis** [comment]
This gesture has been implemented by https://github.com/mapbox/mapbox-gl-js/pull/9365. If you have a chance to test and confirm, that would be great! The gesture is in `master` and will be released in a beta release tomorrow.
