### ISSUE TITLE
boxZoom with padding

### ISSUE THREAD

**Issue by kukiel** [mapbox/mapbox-gl-js#9056]
## Motivation

I have a map that is conditionally covered by some other DOM elements depending on the current elements toggle state. I like to use boxZoom but then if some element is covering 30% of the map on the bottom it's not considered by default and the part that I zoomed in is covered by the DOM element at the bottom.

### Implementation

Map object option like `zoomBoxOptions` (similar to `fitBoundsOptions`) with setter and getter that would be later considered when boxZooming would be perfect.

Edit: I was checking for any other way on how to implement that, looked like intercepting boxzoomstart/end events could be an answer, but there is no `boxZoomBounds` anymore to fit map to adjusted bounds. If you have other suggestions that's could potentially work that's also great.

**Comment by kkaefer** [comment]
This sounds like a good addition. It looks like the underlying call to `Map#fitScreenCoordinates` already accepts an object that includes padding. I could see two ways of implementing this: 

- Add a `padding` parameter to the BoxZoomHandler's options object and a `boxZoomOptions` parameter to the Map object that passes the options on to the constructor, similar to how we have a `fitBoundsOptions` object.
- Add a generic `padding` property to the Map object that gets respected for all camera operations that don't have an explicit` padding` property set.

Do you want to take a first stab at it?

**Comment by asheemmamoowala** [comment]
Some portion of this will overlap with changes pending in https://github.com/mapbox/mapbox-gl-js/pull/8638.

cc @arindam1993

**Comment by kukiel** [comment]
@kkaefer I could try with first option as it seems less conflicting with other work and simpler to implement - are you ok with that?

**Comment by kkaefer** [comment]
Hm, @arindam1993's work in https://github.com/mapbox/mapbox-gl-js/pull/8638 seems to enable what you're looking for as well. @arindam1993, what's the status of this PR?

**Comment by ryanhamley** [comment]
Quick update: #8638 was unblocked recently so we may get some movement there in the near future

**Comment by andrewharvey** [comment]
> Add a generic padding property to the Map object that gets respected for all camera operations that don't have an explicit padding property set.

I prefer this option, set it globally so you don't need to pass it for each camera operation. Then #9265 and #10169 would naturally be solved as all bounds are now for the inner view.

**Comment by andrewharvey** [comment]
#10386 should solve your original issue as described, although the implementation is different. With #10386 if you set a global padding, then the box zoom interaction will correctly fit to the inset bounds.

**Comment by andrewharvey** [comment]
I'll close this because I think it's fixed by #10386 but if I've misunderstood the issue here, just let me know.
