### ISSUE TITLE
heatmap layer `s "heatmap-radius" value don`t set Smaller than 5

### ISSUE THREAD

**Issue by huashaoxu** [mapbox/mapbox-gl-js#9060]
"heatmap-radius" value don`t set Smaller than 5 ，otherwise heatmap will flicker

**Comment by ryanhamley** [comment]
Hi, thanks for using Mapbox. This is a known issue. See https://github.com/mapbox/mapbox-gl-js/issues/5563

Please note that when reporting bugs, it's best to fill out the issue template and include a working example of the bug with a link to JSFiddle/Code Pen.
