### ISSUE TITLE
the custom layer always on top , Can't change its order

### ISSUE THREAD

**Issue by huashaoxu** [mapbox/mapbox-gl-js#9061]
the custom layer always on top , Can't change its order.  
 use threejs as the custom layer , It always hides other layers for example circle layer

**Comment by kkaefer** [comment]
Hi, thanks for using Mapbox. For "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!

That said, the [`map.addLayer` takes a second argument](https://docs.mapbox.com/mapbox-gl-js/api/#map#addlayer) that allows you to specify the ID of another layer. The new layer will be placed before/under it.

**Comment by huashaoxu** [comment]
Don't close problems at will。to custom layer ，“addLayer” doesn`t  work. order not controlled
