### ISSUE TITLE
.flyTo() should fly to the nearest version of destination

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#907]
Instead of one several world-wraps away:

![flyto](https://cloud.githubusercontent.com/assets/4551508/5563215/4391cbf2-8e16-11e4-9795-e79322a7108c.gif)

This is happening when map is `hash:true` and I don't specify position in the URL.

**Comment by mourner** [comment]
@ljbade it flickers on other parts of the world, although I'm sure I already fixed this at some point. Looks like a regression, possibly after tile loading refactor by @jfirebaugh.

**Comment by peterqliu** [comment]
@mourner v2 terrain might also be contributing

[link](https://www.mapbox.com/bites/00080)

**Comment by mourner** [comment]
@peterqliu in the demo, subtract 720 from all the longitudes. Should make it better.

**Comment by jfirebaugh** [comment]
Flickering is fixed in #925.
