### ISSUE TITLE
RTL plugin lazy loading doesn't work on GeoJSON source

### ISSUE THREAD

**Issue by hyperknot** [mapbox/mapbox-gl-js#9075]
**mapbox-gl-js version**: 1.60

**browser**: Chrome latest stable

### Steps to Trigger Behavior
 1. Set RTL text lazy loading to true 
```
mapboxgl.setRTLTextPlugin(
  window.location.origin + '/static/js/@mapbox/mapbox-gl-rtl-text/mapbox-gl-rtl-text.min.js',
  err => {
    console.log(err)
  },
  true
)
```
 2. Load a map without RTL text
 3. Add text which contains RTL characters, for example "این یک متن فارسی است که در سمت راست قرار می‌گیرد"

### Expected Behavior
Network panel should load the RTL plugin + the matching PBF files

### Actual Behavior
RTL plugin does not get loaded + matching PBF files are not loaded either
Nothing is visible on the map in place of the text.

**Comment by ryanhamley** [comment]
cc @arindam1993

**Comment by kkaefer** [comment]
@hyperknot looking at the example at https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-rtl-text/, right-to-left text seems to work as intended. If you believe it doesn't, please provide a reproduction website (e.g. via [jsfiddle.net]https://jsfiddle.net/)). Please include information about the browser version and operating system used.

**Comment by arindam1993** [comment]
Hey @kkaefer , I think @hyperknot is referring to lazy loading the plugin, and not the docs example which loads it synchronously.
I think this still might be an outstanding issue with adding rtl text based labels via GeoJSON. Is that what you mean by pt 3. @hyperknot ?

**Comment by hyperknot** [comment]
@arindam1993 yes, I'm adding text labels via GeoJSON! That's where the whole lazy loading makes sense!

95% of my users are on non RTL regions, hence I would like to make the bundle + plugin loading size as small as possible for them. But at the same time 5% of the users need the RTL plugin, so it'd be important to load it only for those users.

I mean what other use cases can be considered registered which received the recent support in 1.60?

I'll try to make a minimal repro case / test case which you can include in your test suite.

**Comment by arindam1993** [comment]
> I mean what other use cases can be considered registered which received the recent support 

It does work with vector tiles for the basemap, wherein you start your viewport somewhere without rtl text and then move over to an area with rtl text.

**Comment by hyperknot** [comment]
I see. So there is indeed a bug, and it's that lazy loading doesn't work on GeoJSON sources, it only works on vector tile source. I believe there should be a test case for:
- GeoJSON with initially RTL text
- GeoJSON which is updated to contain RTL text

**Comment by arindam1993** [comment]
I can confirm this is indeed the issue, here's a js fiddle with a test case :
https://jsfiddle.net/egyoam5t/3/

**Comment by hyperknot** [comment]
@arindam1993 thanks so much for creating the fiddle!

**Comment by arindam1993** [comment]
#9091  is up which fixes the issue.

Here's a jsfiddle with the latest build that demonstrates that the issue has indeed been fixed.
https://jsfiddle.net/egyoam5t/6/
