### ISSUE TITLE
match expression for fill-color not working in React

### ISSUE THREAD

**Issue by MikeChenfu** [mapbox/mapbox-gl-js#9089]
**mapbox-gl-js version**:

### Question

I try moving my mapbox code into the react framework. But when I use the `setPaintProperty()`, I got the error `Error: layers.state-2d.paint.fill-color: color expected, array found`.  Here is my code.

Html
```
<!DOCTYPE html>
<html lang='en'>
<head>
  <title></title>
  <meta charset='utf-8'>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <link href='https://api.mapbox.com/mapbox-assembly/v0.24.0/assembly.min.css' rel='stylesheet'>
  <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.3.1/mapbox-gl.css' rel='stylesheet' />
  
</head>
<body>
  <div id='app'></div>
  <script src='https://api.mapbox.com/mapbox-assembly/v0.24.0/assembly.js'></script>
</body>
</html>
```
js
```
componentDidMount() {
    this.map = new mapboxgl.Map({
      container: this.mapContainer,
      style: 'mapbox://styles/mapbox/dark-v9',
      center: [5, 34],
      zoom: 1.5
    });
    this.map.on('load', () => {
      this.map.addSource("state-population", {
        'type': 'vector',
        'url': sourceMatch["state-population"]
     });
    this.map.addLayer({
        'id': "state-2d",
        'source': "state-population",
        'source-layer': 'states',
         'maxzoom': zoomThreshold[0],
        'type': 'fill',
        'layout': {
          'visibility': 'visible'
           },
        'paint': {"fill-opacity":0.8 }
    }, 'waterway-label');
  });
   this.addColor();
}

addColor = () => {
    let fillstyle =  ["match", ['get', 'KeyIndex'], 32, "#DA6436", 33, "#C22E00", 34, "#B2DCDF", 35, "#F8C0AA", "#636363"];
    this.map.on("moveend",() => {
      this.map.setPaintProperty("state-2d", "fill-color", fillstyle ); // not working
      this.map.setPaintProperty("state-2d", "fill-color", "#DA6436" ); // working
    });
  }
```

`this.map.setPaintProperty` returns the error when I pass the `["match", ['get', 'KeyIndex'],...`. I really appreciate if anyone has some ideas about this problem.

**Comment by ryanhamley** [comment]
Does this work when you use `setPaintProperty` and this `match` expression in a plain JS map (i.e. not in React)?

**Comment by MikeChenfu** [comment]
Yes, it is working on the plain JS map. Do you think there is any limitation on the react?

**Comment by ryanhamley** [comment]
I can't really think of any obvious explanation. Does moving `this.map.addLayer` and `this.addColor` inside `this.map.on('load', () => {...});` help?

**Comment by MikeChenfu** [comment]
Thanks @ryanhamley. I just try it, as shown in the code, but still not working. 
```

this.map.on('load', () => {
...
  this.map.addLayer({
        'id': "state-2d",
        'source': "state-population",
        'source-layer': 'states',
         'maxzoom': zoomThreshold[0],
        'type': 'fill',
        'layout': {
          'visibility': 'visible'
           },
        'paint': {"fill-opacity":0.8 }
    }, 'waterway-label');
  this.map.setPaintProperty("state-2d", "fill-color", ["match", ['get', 'KeyIndex'],  32, "#DA6436", ...]);
});
```

**Comment by ryanhamley** [comment]
OK I'll leave this open then since it seems to be a bug. I don't have any intuition off the top of my head about why it would stop working in React. We don't officially support React but this seems like a fairly basic use case. If you're able to share a minimal React setup that displays this bug, that would be helpful.

**Comment by MikeChenfu** [comment]
Thanks @ryanhamley. Sure, I'll setup a demo for this problem.

**Comment by MikeChenfu** [comment]
@ryanhamley I have solved this problem. I updated the package file but does not install it. Old version (0.39.1)of mapbox has the problem. New package works well. Thanks for your kind help.

**Comment by ryanhamley** [comment]
Ah great to hear!
