### ISSUE TITLE
Change map option min/maxZoom ⇢ min/maxzoom

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/mapbox-gl-js#909]
Follow the TileJSON naming convention for these properties everywhere.

https://github.com/mapbox/mapbox-gl-js/commit/4862629ed786fe1cc878f7b3d9e721fbd1b0b9c6#commitcomment-9084635

**Comment by jfirebaugh** [comment]
> Stylesheet spec is a separate thing, not a JS API, so it's OK to have it differently there.

I'd oppose having `"maxzoom": 12` in the style spec but requiring `new mbgl.Source({maxZoom: 12})`, if that's what you're suggesting. The style spec and API not really separate in this case; the options you pass to `new mbgl.Source(options)` are (and should be) exactly the same as the source options in the style spec.

**Comment by mourner** [comment]
Then I'd make Source accept both `maxzoom` and `maxZoom`. Most developers just won't understand why `maxzoom` and not `maxZoom`, because they will mostly use styles with mapbox:// shortcuts without even thinking about what happens under the hood (TileJSON, etc.).
