### ISSUE TITLE
Mapbox shows city names in different language compare to mapbox-gl

### ISSUE THREAD

**Issue by dehghani-mehdi** [mapbox/mapbox-gl-js#9094]
Hello,

**mapbox-gl-js version**: 
`https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.js`

**browser**: `Firefox`

### Steps to Trigger Behavior

This setup (Mapbox-GL):
```
<script src="https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.js"></script>
<link href="https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.css" rel="stylesheet" />

mapboxgl.accessToken = '...';
var map = new mapboxgl.Map({
	container: 'map',
	style: 'mapbox://styles/mapbox/streets-v11',
	center: [54.22748801297328, 33.03455357122766],
	zoom: 5
});

if (mapboxgl.getRTLTextPluginStatus() !== 'loaded') {
	mapboxgl.setRTLTextPlugin('https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.3/mapbox-gl-rtl-text.js');
}
```
Produce this:
![mapbox-gl](https://user-images.githubusercontent.com/9152330/70616188-19c51180-1c23-11ea-8182-ddaf7a130452.png)

And this setup (Mapbox):
```
<link href='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.css' rel='stylesheet' />
<script src='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.js'></script>
<script src="https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.0/mapbox-gl.js"></script>

L.mapbox.accessToken = '...';
mapboxgl.accessToken = '...';
var map = L.mapbox.map('map', 'mapbox.streets', {
	zoomControl: false
}).setView([32.50370987448676, 54.18352427434857], 5);

if (mapboxgl.getRTLTextPluginStatus() !== 'loaded') {
	mapboxgl.setRTLTextPlugin('https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-rtl-text/v0.2.3/mapbox-gl-rtl-text.js');
}
```
Produce this:
![mapbox](https://user-images.githubusercontent.com/9152330/70616324-6b6d9c00-1c23-11ea-84ae-327a94796f4e.png)

### Expected Behavior

Mapbox-GL should be produce same result as Mapbox.

### Actual Behavior

Mapbox-GL produce different result compare to Mapbox.

**Comment by kkaefer** [comment]
This is by design. Mapbox GL is a lot more flexible as to what labels it displays. The default mapbox-streets style uses English. You can use https://github.com/mapbox/mapbox-gl-language/ to change the display language. To replicate the behavior of mapbox.js, use the "multilingual" map.

**Comment by dehghani-mehdi** [comment]
@kkaefer I tried `multilingual`, but I got same result as before. should I file an issue?

```
<script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-language/v0.10.1/mapbox-gl-language.js'></script>

map.addControl(new MapboxLanguage({ defaultLanguage: 'mul' }));
```
