### ISSUE TITLE
async GeoJSON load

### ISSUE THREAD

**Issue by ewirth** [mapbox/mapbox-gl-js#9104]
## Motivation

I would like to use places.features.forEach {} ... on GeoJSON data.
Like in this example: https://docs.mapbox.com/mapbox-gl-js/example/filter-markers/
Or this: https://docs.mapbox.com/help/how-mapbox-works/web-apps/

Our aim is to collect/use geojson data from file sources.

Problems with the addSource() implementation way:  
- If I add it as a source with addSource(), and after I query source features with 'querySourceFeatures(), its empty (I can't loop on that...).
- I don't want to use add.mapLayers, since I build up the map's interface inside the forEach loop based on some conditions.

If I use alternative stuff to load the GeoJSON, then that only possible with an asynchronous way:
```js
fetch("oil_mills_12122019.geojson")
  .then(response => response.json())
  .then(json => buildUpMapbox(json));
}); 

```
But then I have to put all the mapbox codes inside a function, which is not elegant I suppose.
And another thing is that I would like to load more GeoJSON data, not only one.

So the problem is quite complex.

## Design

Which design should we implement?
querySourceFeatures() should work similarly as queryRenderedFeature.
If I console.log(querySourceFeatures('my-added-source'), it would be best to see the JSON object.

What are the advantages of this design?
- The user doesn't have to add the data to unnecessary layers, which does not follow their programming methodology.

**Comment by arindam1993** [comment]
Hi @ewirth , you should be able to see your data once with `querySourceFeatures('my-added-source')` once the source is loaded. Even with geojson sources, we process them async into tiles so we can render them efficiently.

you should be able to do something like 
```
map.getSource('my-added-source').once('data' , (data) => { // do stuff with loaded features }
```
