### ISSUE TITLE
Full map is not drawn before browser window is resized

### ISSUE THREAD

**Issue by sspilleman** [mapbox/mapbox-gl-js#9113]
**mapbox-gl-js version**: 1.6.0

**browser**: Google Chrome

### Steps to Trigger Behavior

 1. Load map
 2. Map isn't drawn fully (see pic below)
 3. Resize Browser
 4. Rest of map is drawn

### Expected Behavior

Map is fully drawn on initial load

### Actual Behavior

![image](https://user-images.githubusercontent.com/592486/70885083-1ab9c280-1fd8-11ea-97e5-b563ea356dce.png)

### After Rezize

![image](https://user-images.githubusercontent.com/592486/70885197-75531e80-1fd8-11ea-8ce4-d0c3203edd80.png)

**Comment by kkaefer** [comment]
This happens because Mapbox GL can't determine the dimensions of the containing element when it's initialized. To fix it, you could either call `map.resize()` manually once the size of the container has been determined, or give at a fixed height, e.g. with CSS.

**Comment by jstoxrocky** [comment]
@kkaefer Sorry for the ping on an old post - running into this same issue. I would like my map to be fullscreen so I think I can rule out giving my map a fix height if I want a responsive design - so I believe that calling map.resize is the best approach for me. How exactly should I figure out when the size of the container has been determined...is this not figured out quite early on during the request to mapbox? Feeling a little lost here, would appreciate any help you can give.

**Comment by itanka9** [comment]
@jstoxrocky Maybe [ResizeObserver](https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver) help you? You can call `map.resize()` in its callback. Also, there is a nuance with ResizeObserver - you should not change size of element observed in callback or you will get infinite loop.
