### ISSUE TITLE
web component

### ISSUE THREAD

**Issue by lorenzofox3** [mapbox/mapbox-gl-js#9117]
## Motivation

Web components are a very promising technology now supported by every browser. The declarative approach of HTML makes web component a perfect fit for people who would like to use maps in a declarative way without any UI framework. On the contrary because web components are HTML, you should also be able to integrate them with whatever UI library

## Design Alternatives

I already have developed such a library and would like to collect some feedback and see wheter it interests people.

Please refer to the [following repository](https://github.com/Citykleta/mapboxgl-webcomponent) for more details

**Comment by ryanhamley** [comment]
Hi @lorenzofox3 thanks for sharing your library. It looks great! We encourage you to continue developing the library to be fully featured and I know personally I'd love to see some live demos with code samples.

While web components are exciting, I think it's unlikely Mapbox GL JS will move to officially supporting them until/unless they become the standard for working with HTML. This isn't on our roadmap or really even our radar at this point. I'm going to close this issue as not actionable on our end, but feel free to post updates on your library here. Thanks!
