### ISSUE TITLE
pricing policy confirmation

### ISSUE THREAD

**Issue by AnandSrini** [mapbox/mapbox-gl-js#9130]
**mapbox-gl-js version**: ^1.3.0

### Question
Confirming the pricing policy

Do we get billed, if we are using our own raster/vector tile server? (like geoserver)

We shouldn't be right? Because we are not requesting a mapbox maintained/mapbox hosted tiles.

### Links related
[Pricing guide](https://docs.mapbox.com/accounts/overview/pricing/#mapbox-gl-js-v100-and-higher)

**Comment by ansis** [comment]
Yep, that's correct! If you are not using mapbox-hosted tiles and styles you will not get billed.
