### ISSUE TITLE
Remove layer does not remove the source id reference

### ISSUE THREAD

**Issue by Rumpelstinsk** [mapbox/mapbox-gl-js#9135]
Removing a layer does not release the `id`. When you remove a layer you cannot add another with the same id, despite, there is not any layer with that id, because you just removed it.

## Steps to Trigger Behavior

 1. Here is a code sample: https://jsbin.com/sevijigujo/1/edit?html,output
```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>Add a third party vector tile source</title>
<meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.1/mapbox-gl.js"></script>
<link href="https://api.tiles.mapbox.com/mapbox-gl-js/v1.6.1/mapbox-gl.css" rel="stylesheet" />
<style>
	body { margin: 0; padding: 0; }
	#map { position: absolute; top: 0; bottom: 0; width: 100%; };

  </style>
</head>
<body>
  <button id="toogle" onClick="toogle()" disabled="disabled"
          style="position:absolute; top: 0; z-index:100; width: 100px; height: 50px">Add layer</button>
<div id="map"></div>
<script>
	mapboxgl.accessToken = "#MAPBOX_TOKEN#";
var map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/mapbox/light-v10',
zoom: 12,
center: [-87.622088, 41.878781]
});
 
map.on('load', function() {
  $("#toogle").removeAttr("disabled");
  
// Add Mapillary sequence layer.
// https://www.mapillary.com/developer/tiles-documentation/#sequence-layer

});
 
map.addControl(new mapboxgl.NavigationControl());
  
  layerShown = false;
  function toogle(){
    if(!layerShown){
      map.addLayer(
{
'id': 'mapillary',
'type': 'line',
'source': {
'type': 'vector',
'tiles': [
'https://d25uarhxywzl1j.cloudfront.net/v0.1/{z}/{x}/{y}.mvt'
],
'minzoom': 6,
'maxzoom': 14
},
'source-layer': 'mapillary-sequences',
'layout': {
'line-cap': 'round',
'line-join': 'round'
},
'paint': {
'line-opacity': 0.6,
'line-color': 'rgb(53, 175, 109)',
'line-width': 2
}
},
'waterway-label'
);
    
    $("#toogle").text("Remove layer");
    }
  else{
    map.removeLayer("mapillary");
    $("#toogle").text("Add layer");
  }
  
  layerShown = !layerShown;
  
    
  }
</script>
 
</body>
</html>
```
 2. Remplace `#MAPBOX_TOKEN#` by your real token
 3. Click add layer
 4. Click remove layer
 5. Click add layer. No layer is shown and there are errors on chrome's console.

> style.js:531 Uncaught Error: There is already a source with this ID
>     at i.addSource (style.js:531)
>     at i.addLayer (style.js:632)
>     at r.addLayer (map.js:1624)
>     at toogle (runner:24)
>     at HTMLButtonElement.onclick (runner:1)

**Comment by andrewharvey** [comment]
Yet another argument for avoiding inline sources, at least in the official docs... See #5728.

When you include your source in your addLayer, it secretly adds a source to your style with the same id as the layer. So when you remove the layer, the source is still there, and it goes to add it again with addLayer but it's already there.

Given the feedback in #5728 seems to agree that this makes the docs more confusing, I'm going do a PR to change this back.

In the meantime you could either remove the source when you remove the layer, or when you add the layer don't inline the source, just add it separately.
