### ISSUE TITLE
Using variable in setting up value filter for mapbox

### ISSUE THREAD

**Issue by wenhaowuuu** [mapbox/mapbox-gl-js#9140]
Hi all,

I'm trying to set up a value comparison filter using a variable name as
map.setFilter('my-layer', ['>', 'area', reported_Area]);

But couldn't get it work. Seems the Mapbox Filter only takes in actual fixed value (such as 10000). Is there any example to be able to use a variable name and pass value to the filter?

Thank you!

**mapbox-gl-js version**:

**Comment by mourner** [comment]
The code above looks like it should work. Can you provide us with a live minimal test case (e.g. with JSFiddle) that demonstrates the code you expect to work that doesn't? We won't be able to diagnose the issue without it.
