### ISSUE TITLE
How to change the id of layer

### ISSUE THREAD

**Issue by Yuki-Zhao** [mapbox/mapbox-gl-js#9144]
let layers = map.getStyle().layers;

let id = layers[1].id;

i want to change the id. how to change ?

**Comment by tristen** [comment]
@Yuki-Zhao you would need to [remove the layer first](https://docs.mapbox.com/mapbox-gl-js/api/#map#removelayer) then [add a new one](https://docs.mapbox.com/mapbox-gl-js/api/#map#addlayer). Note that this repo is for reporting bugs and feature requests — [StackOverflow](http://stackoverflow.com/) would be a better place to ask questions.
