### ISSUE TITLE
NavigationControl buttons are missing SVG images.

### ISSUE THREAD

**Issue by rlmcneary2** [mapbox/mapbox-gl-js#9147]
**mapbox-gl-js version**:
1.6.0

**browser**:
Firefox

### Steps to Trigger Behavior
 1. Create a map.
 2. Add a NavigationControl without options (e.g. `new NavigationControl()`).

### Link to Demonstration
https://0gtf3.csb.app/

### Expected Behavior
The navigation control should include images for each of the three buttons (image from version 1.5.1).
![navigation-1 5 1](https://user-images.githubusercontent.com/1216670/71547328-cbc34400-296c-11ea-8467-f16ec32235e6.jpg)

### Actual Behavior
The navigation control has three operable buttons but there are no visible graphics. Inspector shows that the buttons now contain an empty span and the button no longer has an SVG image (image from version 1.6.0).
![navigation-1 6 0](https://user-images.githubusercontent.com/1216670/71547370-4ab87c80-296d-11ea-85ad-63728a3b48a3.jpg)

**Comment by mourner** [comment]
You appear to be using an older CSS file for a newer Mapbox GL JS version. Update the CSS to the latest version and everything should work.

**Comment by rlmcneary2** [comment]
OK. Thanks for the assist.
