### ISSUE TITLE
Disable map rotation doesn't work with url hash

### ISSUE THREAD

**Issue by jessecrouch** [mapbox/mapbox-gl-js#9148]
When using [all of the settings that disable map rotation](https://docs.mapbox.com/mapbox-gl-js/example/disable-rotation/), the map is still able to rotate if the user changes the hash in the url (ex: https://localhost?10/30.261/-97.717/-97.7)

Expected: User should not be able to rotate the map by any means. Bearing should lock.

Ideally there would be a map creation setting such as bearingLock, a permanent version of resetNorth.

**Comment by ryanhamley** [comment]
I have a PR up for this https://github.com/mapbox/mapbox-gl-js/pull/9156
