### ISSUE TITLE
Regression in VectorTile on the "prerendered" property

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#915]
Hi,

I just updated to the very last version of the repo but unfortunately, code that was working before no longer works.
I am using mapbox-gl-js in IE with bright-v6.json.

The code fails here:
https://github.com/mapbox/mapbox-gl-js/blob/4e53999bc66d00c2c6a2ff0d6cdcde24789a9cd7/js/source/vector_tile.js#L68

cannot find "prerendered" from an undefined reference. Might be some other changes with buckets?
"bucket" = "water_pattern" in my case

Thanks,
Fabien

**Comment by lbud** [comment]
Thanks @fnicollet! It looks like there are undefined buckets where source layers haven't been encountered yet at certain zoom levels (i *think*) — pushed an easy fix at https://github.com/mapbox/mapbox-gl-js/commit/c0d005177814164bebe337b85320c70ba718ea7a, but will keep poking to see if there's a bigger bucket problem here.

**Comment by fnicollet** [comment]
Thanks @lbud , it looks like it fixed the issue. From my testing, there is no more regression :)

Fabien
