### ISSUE TITLE
fill-extrusion 3D object disappears on rotate

### ISSUE THREAD

**Issue by wentao978** [mapbox/mapbox-gl-js#9150]
**mapbox-gl-js version**: 1.3.1

**browser**: chrome 79

### Steps to Trigger Behavior

 1. 3D

**Comment by mourner** [comment]
I'll have to close the issue since you didn't provide any details necessary for diagnosing it. The official example works fine with rotation in Chrome https://docs.mapbox.com/mapbox-gl-js/example/3d-buildings/
