### ISSUE TITLE
I have error using mapbox-gl in uni-app

### ISSUE THREAD

**Issue by Mrxpj** [mapbox/mapbox-gl-js#9151]
**code:**
```javascript
<template>
	<view id="map">
		
	  </view>
</template>
<script>
import mapboxgl from 'mapbox-gl'
export default {
	name: 'maps',
	data() {
		return {
			msg: '123'
		}
	},
	mounted() {
		// const mapboxgl = require('mapbox-gl')
		mapboxgl.accessToken = myAccessToken
		var map = new mapboxgl.Map({
		      container: 'map', // container id
		      style: 'mapbox://styles/mapbox/outdoors-v9',
		      center: [-121.403732, 40.492392],
		      zoom: 10
			})
		}
}
</script>
<style>
	@import url('https://api.tiles.mapbox.com/mapbox-gl-js/v0.44.2/mapbox-gl.css');
	body { margin: 0; padding: 0; }
	#map { position: absolute; top: 0; bottom: 0; width: 100%; }
</style>
```

**error:**
Uncaught ReferenceError: _create is not defined
    at cdfd3289-8247-4811-ba5e-db289ff520c6:1
    at cdfd3289-8247-4811-ba5e-db289ff520c6:1
    at cdfd3289-8247-4811-ba5e-db289ff520c6:1

but it is ok in vue-cli

**Comment by ifzm** [comment]
uni-app frame have  not dom

**Comment by Mrxpj** [comment]
> uni-app frame have not dom

Thank you. This mean mapbox-gl is not available in the uniapp framework？

**Comment by mourner** [comment]
Not sure what `uni-app` is but this isn't the right place to ask about integration issues — maybe try asking its developers.

**Comment by ifzm** [comment]
> > uni-app frame have not dom
> 
> Thank you. This mean mapbox-gl is not available in the uniapp framework？

use webview or mapbox-gl-native
