### ISSUE TITLE
Some ends of linestrings are not rendered

### ISSUE THREAD

**Issue by shaleve** [mapbox/mapbox-gl-js#9152]
On occassion, an end of a linestring feature, which is on a tile's edge, will not render, although properties can still be seen while hovering with the mouse over the missing segment.
See screenshot for clarification:
![image](https://user-images.githubusercontent.com/42799661/71641499-c6843300-2ca5-11ea-9809-c43970633ae9.png)
This means that the connected points do exist, they are just not being drawn.

**Comment by mourner** [comment]
Unfortunately a screenshot is not sufficient for us to diagnose the issue. Please fill out the issue form as requested, including a live minimal reproducible test case.

**Comment by kkaefer** [comment]
Closing this since we can't act on this report unless we receive further information. Please reopen with a a reproduction test case.

**Comment by mourner** [comment]
I'm pretty sure now this is a duplicate of #5171, with the fix coming in https://github.com/mapbox/mapbox-gl-js/pull/9218.
