### ISSUE TITLE
Dynamic styling: how to dynamically use geolocation information - e.g. ["get", "latitude"]

### ISSUE THREAD

**Issue by dancherb** [mapbox/mapbox-gl-js#9153]
Is there a way to do this without manually storing the required geolocation data in feature properties?

I can't find a way to do this in the documentation / style specification, so this can either act as a request for a documentation update, or a feature request. Thanks!

**Comment by ryanhamley** [comment]
It sounds like you might be asking for global variables. There's an existing issue for that https://github.com/mapbox/mapbox-gl-js/issues/7946 so I'm going to close this to concentrate discussion there.

If you think that feature wouldn't cover your use case, please fill out the feature request issue more fully to elaborate on what you're requesting. Thanks!

**Comment by dancherb** [comment]
My bad for being unclear - I'm referring to accessing the location data of a particular feature, not of the map itself. In the same way that you can add properties to features (e.g. "id") and then access them via ["get", "id"], I'd like to access the latitude of a feature to style it accordingly. @ryanhamley

**Comment by ryanhamley** [comment]
This isn't supported right now but there is an open ticket for it https://github.com/mapbox/mapbox-gl-js/issues/8218
