### ISSUE TITLE
Circle stops rendering when center is off-screen (React Native)

### ISSUE THREAD

**Issue by dancherb** [mapbox/mapbox-gl-js#9154]
Posting here as well as the React Native repo in case it's relevant here, or there's a shared setting.

I'm rendering a large circle (CircleLayer within a ShapeSource with one feature) with a thick radius around the user's location. When the user scrolls away so that the center (the user icon) is no longer on the screen, the circle abruptly stops rendering altogether. This is irregular depending on the area - sometimes it stops rendering immediately when the user goes off-screen, and in other corners when the user goes off-screen and then some. 

I'm assuming this is intended for performance - is there a way to turn off this behaviour and to always show the circle?

Android
React Native: 0.61.5
@react-native-mapbox-gl/maps: 7.0.4

![circle](https://user-images.githubusercontent.com/32280121/71678232-9491d000-2d7c-11ea-8bed-648b747fa2d4.png)

**Comment by arindam1993** [comment]
Hi @dancherb , looks like `react-native-mapbox-gl` has bindings with the mapbox mobile SDK's which are based on https://github.com/mapbox/mapbox-gl-native and not GL-JS. I'm closing this issue since its not the same codebase.
