### ISSUE TITLE
how do I  change the  data when use CustomLayerInterface  create custom layer?

### ISSUE THREAD

**Issue by xuweimeng** [mapbox/mapbox-gl-js#9160]
**mapbox-gl-js version**:

### Question

```
class NullIslandLayer {
    constructor() {
        this.id = 'null-island';
        this.type = 'custom';
        this.renderingMode = '2d';
    }

    onAdd(map, gl) {
        
        // add some model at there ...
    }

    render(gl, matrix) {
       // ...
    }
}

map.on('load', function() {
    map.addLayer(new NullIslandLayer());
});
```
Look at the code above, When the model at onAdd function is loaded successfully, how to chang the model and no need remove this layer, load new model by add this layer again?

**Comment by asheemmamoowala** [comment]
@xuweimeng Thank you for using mapbox-gl-js. 

The `CustomLayerInterface`only defines the minimum methods you need to implement to work with the Custom layer API. You can define your own methods to change the model at any time and force a map update to trigger a new call to the `CustomLayerInterface#render` method.

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
