### ISSUE TITLE
Make cursor the center of zoom in tilted maps

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#917]
When zooming in 2D, the point under the mouse stays put, while everything else expands and contracts around it. I'd like the same in tilted perspective.

![tilt](https://cloud.githubusercontent.com/assets/4551508/5651464/7f8060a8-965c-11e4-9b8d-919d3925b45e.gif)
*Note how the mouse goes from water to land as I zoom in*

We might have to project the mouse position from the canvas object to the tilted view to get the actual desired position, in perspective.

cc/ @ansis

**Comment by fnicollet** [comment]
Hello @peterqliu , I didn't know this "tilt" branch existed, looks very cool ! Is there an online demo hosted somewhere? Do you know if it will be ready to be merged in master at some point?

Fabien

**Comment by ansis** [comment]
@fnicollet no online demo yet. It should be possible to get [the perspective branch](https://github.com/mapbox/mapbox-gl-js/tree/perspective) working locally, if you're interested. It will be merged into master at some point, but I'm not sure how soon.

**Comment by fnicollet** [comment]
Thanks for the quick answer @ansis , unfortunately, it seems that the perspective branch is too far behind and doesn't have some commits for Windows build. I'll wait for the merge :)

**Comment by temsa** [comment]
@ansis "perspective" branch is fun locally.

I had some troubles for doing a quick merge with the "touch" branch too, as the perspective branch uses some older coding conventions.

Yet, this would be very interesting to have both "touch" and "perspective" available, as this would constitute a great basis for creating a Navigation website (using OSRM or a commercial direction+instruction provider), which seems not to exists yet.

:+1: for merging it
