### ISSUE TITLE
OBJC_CLASS_$_MMEEventsManager

### ISSUE THREAD

**Issue by aditya16051992** [mapbox/mapbox-gl-js#9171]
ld: warning: arm64 function not 4-byte aligned: _unwind_tester from /Users/waysmeans/Desktop/UNITY/KiwiGit/Unity/KIWI_WaysAnsMeans/IOSBUILD/Libraries/libiPhone-lib.a(unwind_test_arm64.o)
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_MMEEventsManager", referenced from:
      objc-class-ref in MapboxMetricsClient.o
  "_MMEAPIClientBaseURL", referenced from:
      _initialize in MapboxMetricsClient.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by ryanhamley** [comment]
This is not an actionable bug report or feature request. If you'd like to report a bug or request a feature, please fill out the appropriate template in full. In any case, this appears to be GL Native code, not GL JS.
