### ISSUE TITLE
Add a stretchable image to the map ,words looks not well.Please

### ISSUE THREAD

**Issue by sslnwyl** [mapbox/mapbox-gl-js#9175]
![image](https://user-images.githubusercontent.com/27253644/72239211-3afe9080-361b-11ea-92f4-9cc0ce654660.png)

**Comment by mourner** [comment]
Unfortunately we can't diagnose this by a screenshot alone. Please fill out the bug report form presented when submitting an issue.

**Comment by sslnwyl** [comment]
Sorry that. MyQuestion is Very Simple then I just give a pictrue. The Example about "Add a stretchable image to the map" has some bugs. I think words should be covered by these Icon-Images above it.But
now,We can't  distinguish any of them when words get together.
