### ISSUE TITLE
Self-defined map style doesn't work with fill-extrusion-color

### ISSUE THREAD

**Issue by YayinC** [mapbox/mapbox-gl-js#9178]
**mapbox-gl-js version**:

### Question
When I use self-defined map style, I can't display fill-extrusion-color (no matter what color I assign, they will only display in grey). However, when I use mapbox template (dark, light, etc), the fill-extrusion-color works well.
Does anyone have the similar problem?

**Comment by mourner** [comment]
We haven't seen any similar reports — might be some issue in your style. However, since you haven't provided any details like a minimal live test case, we have no way of diagnosing your problem, so I have to close this.
