### ISSUE TITLE
map within iframe with external domain broken on brave browser

### ISSUE THREAD

**Issue by andrewharvey** [mapbox/mapbox-gl-js#9186]
**mapbox-gl-js version**: 1.6.1

**browser**: brave

I'm not sure if this is fixable on our side but...

1. Take any of the examples at https://docs.mapbox.com/mapbox-gl-js/examples/ and save it as an HTML page on a domain for example A.com.
2. In a web page on domain B.com add an <iframe width="500px" height="500px" src="https://A.com/page.html"></iframe>

On all browser this works except the Brave browser.

### Link to Demonstration

https://www.alantgeo.com.au/share/iframe.html

The error at https://github.com/mapbox/mapbox-gl-js/blob/master/src/util/image.js#L57 is thrown.

`Uncaught (in promise) DOMException: An attempt was made to break through the security policy of the user agent.`
`Uncaught RangeError: out of range source coordinates for image copy`

I tried to set a CSP but I still couldn't get it working.

**Comment by ryanhamley** [comment]
Just a note that we've had other issues with the Brave browser. It's security settings can interfere with things that GL JS requires to work properly. See https://github.com/mapbox/mapbox-gl-js/issues/8377 for some discussion

**Comment by andrewharvey** [comment]
> Just a note that we've had other issues with the Brave browser. Its security settings can interfere with things that GL JS requires to work properly. See #8377 for some discussion

It's likely we can't do anything about this too, but I just haven't investigated to know for sure. It's slightly different to #8377 since this happens without the opt in disable fingerprinting option that was the issues in #8377.

I just don't know enough about CSP to know if this is fixable or not. If you think it's not fixable feel free to close.

**Comment by andrewharvey** [comment]
In case this is unable to be fixed here I've opened https://github.com/mapbox/mapbox-gl-supported/issues/25 in case mapbox-gl-supported can detect the potential issue and return false.

**Comment by kkaefer** [comment]
This is fundamentally the same setting: By default, Brave is configured to "Only block cross-site device recognition attempts". Loading a website from a different hostname via the iframe means that Brave blocks attempts to access `canvas`, which we require to load sprite images.

**Comment by kkaefer** [comment]
See https://github.com/mapbox/mapbox-gl-supported/pull/28 for further explanation. This isn't something that we can fix on our side. Brave disables a few commonly used OpenGL APIs, e.g. `getUniformLocation`. They likely due this because it would allow fingerprinting GPU drivers which assign uniforms in a peculiar way, but our code relies on these APIs.
