### ISSUE TITLE
Сan’t update position of the moving in real time point on the map under Blazor

### ISSUE THREAD

**Issue by aviabunin** [mapbox/mapbox-gl-js#9187]
I am using MapBox under Blazor. There is a point with JSON coordinates changing in realtime. In Index razor page on mouse click I call the javascript function:
```
refreshJSON: function (str) { 
  window.jsontest = JSON.parse(str);
  window.map.getSource('drone').setData(window.jsontest);
}
```
where jsontest contains new coordinates, The point changes position, but the entire map is redrawn (~3 sec), not just the point. This does not suit. How can I fix the problem? In Index.razor code:
```
 private void refreshMapJson()
    {
        Time = DateTime.UtcNow.ToString();
        refreshCoords();
        JSRuntime.InvokeVoidAsync("refreshJSON", currJson);
        StateHasChanged();
    }
```

**Comment by mourner** [comment]
Can you replicate the same issue exclusively with GL JS in a browser (without Blazor), and share a live test case?

**Comment by aviabunin** [comment]
As a first step I did such a test.
[live test](https://jsfiddle.net/ATerentjev/w8bv31n0/31/)
Please note that there is no error on the first line, but  the error message on the second line ( wrong json format, although the expression **jsonleft** is the same)

```
      map.addSource('drone', window.jsonleft);	
      map.getSource('drone').setData(window.jsonleft);
```
What is wrong?

**Comment by mourner** [comment]
@aviabunin you're passing the source definition instead of the data to `setData`, which rightfully thinks this isn't valid GeoJSON. This works:

```js
map.getSource('drone').setData(window.jsonleft.data);
```
