### ISSUE TITLE
Default minzoom of -2 prevents NavigationControl button from being disabled

### ISSUE THREAD

**Issue by malwoodsantoro** [mapbox/mapbox-gl-js#9191]
**mapbox-gl-js version**: v1.6.1

**browser**: Tested in latest versions of Chrome/FF 

### Steps to Trigger Behavior

1) Compare behavior between **v1.5.0** (https://jsfiddle.net/fgc1ubrp/) and **v1.6.1** (https://jsfiddle.net/ug0sfL8x/). Press the minus zoom button until fully zoomed out.
 
2) With **v1.5.0**, minZoom is 0 by default and the button is disabled as expected when the map reaches z0 (relevant code - https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/control/navigation_control.js#L80)
![Screen Shot 2020-01-15 at 12 31 10 PM](https://user-images.githubusercontent.com/19801577/72470478-c439d280-3795-11ea-9301-23e32fce68a1.png)
With **v1.6.1,** minZoom is -2 and the button is never disabled as the map can never reach the negative zoom. 
![Screen Shot 2020-01-15 at 12 32 50 PM](https://user-images.githubusercontent.com/19801577/72470477-c439d280-3795-11ea-94a0-95c983925419.png)

I believe the change in this behavior is due to the `defaultMinZoom` change: https://github.com/mapbox/mapbox-gl-js/pull/9028/files#diff-c6d02b0c73aa7597f4224ec35497cfe2L104.

### Expected Behavior
Minus zoom button is disabled when the map cannot be zoomed out any further. 

### Actual Behavior
Minus zoom button is never disabled because the map cannot zoom out to the negative zoom.

**Comment by ryanhamley** [comment]
This was reported in https://github.com/mapbox/mapbox-gl-js/issues/9172

I'm going to close this to consolidate discussion in that ticket
