### ISSUE TITLE
Self-defined map style doesn't work with "fill-extrusion-color"

### ISSUE THREAD

**Issue by YayinC** [mapbox/mapbox-gl-js#9199]
### Question
Sorry I have to post this issue again. My map style doesn't work with "fill-extrusion-color". What ever color I assign, it will display grey. However, if I use default Mapbox map, it works well. Here is the example:
When using mapbox default map, it works well:
![image](https://user-images.githubusercontent.com/35982086/72563268-e9504300-3872-11ea-9320-06fca820f905.png)
When using my map style, it shows grey:
![image](https://user-images.githubusercontent.com/35982086/72563309-01c05d80-3873-11ea-9572-93b75f43cf9a.png)

My code:
	mapboxgl.accessToken = 'xxx';
    var map = new mapboxgl.Map({
        container: 'map',
        //style: 'mapbox://styles/username/xxxxx',
       style: 'mapbox://styles/mapbox/dark-v10',
        zoom: 13,
        center: [-122.447303, 37.753574]
    });

    map.on('load', function() {
        map.addLayer({
            'id': 'markets',
            'type': 'fill-extrusion',
            'source': {
                type: "vector",
               url:'mapbox://mapbox.660ui7x6'
            } ,
            'source-layer': 'state_county_population_2014_cen',
            'filter': ['==', 'isState', true],
            'paint': {
                'fill-extrusion-color':"red",
                'fill-extrusion-height':200
            }
        });
    });

**Comment by mourner** [comment]
@YayinC can you provide the style id that causes the problem? Or if it's sensitive, can you contact support@mapbox.com with the necessary details? Otherwise there's still no way for us to reproduce the issue.

**Comment by YayinC** [comment]
Do you need the mapbox token as well or just the style id?

**Comment by asheemmamoowala** [comment]
Hi @YayinC ! Thanks for reaching out. As the team requested more information and we haven't heard back in over a month, we're going to close this out. If you want to reopen it, please:

- Include a link to a minimal demonstration of your code. We recommend using https://jsbin.com. 

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
Thank you!
