### ISSUE TITLE
Point opacity changed when fly to next layer

### ISSUE THREAD

**Issue by MikeChenfu** [mapbox/mapbox-gl-js#9200]
Hello, I implemented a 3D demo based on Mapbox. I add four layers on it.(3 polygon layers and 1 point layer). In the first two polygon layers, point layer shows well but it become unsharp when I zoom to the thrid polygon layer. I appreciate if anyone has any idea about it.

```js

map.addLayer({
      'id': "points",
      'source': {
            'type':'geojson',
            'data' : data
       },
      'type': 'circle',
      'layout': {
            'visibility': 'visible'
      },

      'paint': {
      'circle-radius':
       {
           'stops': [
               [5, 4],
               [9,8],
               [12, 10]
            ]
      },
      'circle-color':  '#00498d' ,
      }
 });
```

* points shown in the second layer
<img width="374" alt="Screen Shot 2020-01-16 at 3 12 31 PM" src="https://user-images.githubusercontent.com/17817768/72563589-9f1b9180-3873-11ea-9ed2-e5db56ccb96f.png">

* points shown in the third layer
<img width="558" alt="Screen Shot 2020-01-16 at 3 12 46 PM" src="https://user-images.githubusercontent.com/17817768/72563601-a2168200-3873-11ea-9f66-1c095aebe14a.png">

**Comment by mourner** [comment]
Can you please provide a minimal live example? A screenshot isn't enough for us to diagnose the issue.

**Comment by MikeChenfu** [comment]
@mourner Sorry for the delayed response. I check the demo again. I found the opacity is not changed. The reason is the point layer is under the polygon layer(3rd layer) so that it becomes unsharp. I am going to write an example for that,.
