### ISSUE TITLE
Got NO_TOKEN_WARNING with a valid access token in Chrome

### ISSUE THREAD

**Issue by sugia** [mapbox/mapbox-gl-js#9207]
**mapbox-gl-js version**:
react-map-gl@5.1.5

**browser**:
Chrome (Version 79.0.3945.130 (Official Build) (64-bit))

### Description
The same token works well in:
Firefox (Version 72.0.1 (64-bit))
Safari (Version 13.0.4 (14608.4.9.1.4))
Yandex (Version 19.12.0.769 (64-bit))

but got NO_TOKEN_WARNING in:
Chrome (Version 79.0.3945.130 (Official Build) (64-bit))

### Expected Behavior
<img width="376" alt="Screen Shot 2020-01-20 at 8 30 09 AM" src="https://user-images.githubusercontent.com/2340878/72742683-1ba5bd00-3b5f-11ea-83f1-58feb0a461be.png">

### Actual Behavior
<img width="376" alt="Screen Shot 2020-01-20 at 8 29 53 AM" src="https://user-images.githubusercontent.com/2340878/72742701-23fdf800-3b5f-11ea-8786-49debdd2d588.png">

**Comment by mourner** [comment]
Please provide a minimal live reproducible test case. Screenshots aren't enough for us to diagnose the issue.

**Comment by sugia** [comment]
Sure. It's https://www.amplichat.com. You'll need to register an account to get into the map page.

> Please provide a minimal live reproducible test case. Screenshots aren't enough for us to diagnose the issue.

**Comment by mourner** [comment]
@sugia it's not a minimal test case if it requires registration. From what I'm seeing, this doesn't appear to be an issue with GL JS — you should report this in `react-map-gl`.
