### ISSUE TITLE
Add marker to map on click and output its latitude and longitude

### ISSUE THREAD

**Issue by Magnuspil** [mapbox/mapbox-gl-js#9209]
Hi all,

I have been searching on both stack, and the documentation - without a clear solution on how to go about this. 

Would it be possible to let users click on map to place a marker (and then remove the old one), while it outputs the latitude and longitude as separate strings? I haven't been able to find anything on this solution, using Mapbox GL JS - i could find something similar on Mapbox JS, but we prefer using the GL JS solution.

Thank you for your help, in advance.

**Comment by thezealousfool** [comment]
Do not create a marker on click. Create one marker and update it's coordinates on click.

```
this.map = new mapboxgl.Map({
  container: "map",
  style: "<style_url>",
});
this.marker = new mapboxgl.Marker();
this.map.on('click', this.add_marker.bind(this));

add_marker: function (event) {
  var coordinates = event.lngLat;
  console.log('Lng:', coordinates.lng, 'Lat:', coordinates.lat);
  this.marker.setLngLat(coordinates).addTo(this.map);
}
```

**Comment by mourner** [comment]
Thanks for chiming in @thezealousfool! That looks like the best solution.

**Comment by Magnuspil** [comment]
> Do not create a marker on click. Create one marker and update it's coordinates on click.
> 
> ```
> this.map = new mapboxgl.Map({
>   container: "map",
>   style: "<style_url>",
> });
> this.marker = new mapboxgl.Marker();
> this.map.on('click', this.add_marker.bind(this));
> 
> add_marker: function (event) {
>   var coordinates = event.lngLat;
>   console.log('Lng:', coordinates.lng, 'Lat:', coordinates.lat);
>   this.marker.setLngLat(coordinates).addTo(this.map);
> }
> ```

Hi!

Thank you for your input, it's really appreciated.

However, I'm getting this error, when trying the code:
_Error: index.html:69 - Uncaught SyntaxError: Function statements require a function name_

Here is my current code: 
_https://gist.github.com/Magnuspil/dc9d4916c842f35d780c0baffac7a311_

Thank you!

**Comment by thezealousfool** [comment]
```var map = new mapboxgl.Map({
container: 'map',
style: 'mapbox://styles/mapbox/streets-v11',
center: [-79.4512, 43.6568],
zoom: 13
});

var marker = new mapboxgl.Marker();
map.on('click', add_marker);

function add_marker (event) {
  var coordinates = event.lngLat;
  console.log('Lng:', coordinates.lng, 'Lat:', coordinates.lat);
  marker.setLngLat(coordinates).addTo(map);
}```

**Comment by KyrosNox** [comment]
This is what I was searching for. Thanks Much!!!
