### ISSUE TITLE
line-dasharray with zero gap set still renders with tiny gaps

### ISSUE THREAD

**Issue by 3zzy** [mapbox/mapbox-gl-js#9213]
When `line-dasharray` property is present with just `[1,0]` (no gap), it still renders small gaps that are not clearly visible in regular view:

![Imgur](https://imgur.com/mhVbGQG.png)

However, if you look carefully:

![Imgur](https://imgur.com/sighaC6.png)

Example: https://jsfiddle.net/iaezzy/mgwrh9bf/2/

**Comment by karimnaaji** [comment]
The artifact with this zero gap is incoming from the interpolation done here https://github.com/mapbox/mapbox-gl-js/blob/master/src/shaders/line_sdf.fragment.glsl#L38

As a `line-dasharray` of values `[1,0]` will basically represents a triangle signal in the distance field with a cutoff on the empty dash pattern, the interpolation interprets the down slope as the start of an empty dash pattern (negative field values), but it's usually not a problem with non-zero values. 

Changing the values of u_sdfgamma to make the smoothstep more steep fixes this issue but has unwanted consequences for the regular use case.

Current behavior:

<img width="312" alt="Screen Shot 2020-01-23 at 9 41 00 PM" src="https://user-images.githubusercontent.com/7061573/73086592-e8d13100-3e9e-11ea-9d44-fd99ada02b23.png">

sdf with more _steep_ interpolation, lower u_sdfgamma:

<img width="312" alt="Screen Shot 2020-01-24 at 11 41 03 AM" src="https://user-images.githubusercontent.com/7061573/73086601-ea9af480-3e9e-11ea-880a-e0f2760f19ff.png">

@3zzy What particular use case does this cover? Are you feeding values generated by code and this ends up being a visible artifact?

Other than tweaking the u_sdfgamma values, another fix would be to flatten the distance field in areas next to 0-length patterns but I don't think this particular use case warrants the added complexity of detecting that when generating the distance field. @ansis , what's your opinion? Should we only reflect the behavior/non-suport in the spec documentation?

**Comment by 3zzy** [comment]
@karimnaaji Thanks for the detailed explanation. I spent quite some time figuring it out without luck.

You're right, basically I'm feeding values generated by code and it ends up being a visible artifact. So I've fixed it by only adding the `line-dasharray` paint property if `dasharray[dasharray.length -1] !== 0`

**Comment by arindam1993** [comment]
If I understand this correctly couldn't this be fixed by computing the smoothstep width dynamically using `fwidth`?

**Comment by ansis** [comment]
> Other than tweaking the u_sdfgamma values, another fix would be to flatten the distance field in areas next to 0-length patterns but I don't think this particular use case warrants the added complexity of detecting that when generating the distance field. @ansis , what's your opinion? Should we only reflect the behavior/non-suport in the spec documentation?

I would probably preprocess the dasharray in LineAtlas#addLine(...) to remove 0-width spaces.

> If I understand this correctly couldn't this be fixed by computing the smoothstep width dynamically using fwidth?

Do you have a formula in mind for calculating the step size? I see how this could be used to reduce the step size as the derivative changes but I couldn't come up with mathematical reasoning for why the step size should be related to the derivative.

**Comment by arindam1993** [comment]
Something linear works as a good approximation, I don't actually know the details of how we determine `u_sdfgamma` and `floorwidth`, but if you want a `2px` antialiased edge around a `signedDist` value of `0.5` then:
```
float blurWidth = fwidth(signedDist) * 2.0 ; //since we want a 2px width
float alpha = smoothstep( 0.5 - blurWidth/2 , 0.5+blurWidth/2, signedDist) 
```

**Comment by karimnaaji** [comment]
@3zzy this will be fixed by https://github.com/mapbox/mapbox-gl-js/pull/9246 in the next release.
