### ISSUE TITLE
load additional Sprite

### ISSUE THREAD

**Issue by webdeb** [mapbox/mapbox-gl-js#9224]
**mapbox-gl-js version**:  1.6.1

### Question
how can I load an additional sprite?
I saw, that I could load an additional image with the `addImage` method, however this method loads images only one-by-one. I would like to load a complete sprite how it is defined by the api.

As I understood from the code, I would have to reimplement the logic in https://github.com/mapbox/mapbox-gl-js/blob/b61d19b8ed84b37f729bba44503b8d69ab209c13/src/style/style.js#L253

Just wanted to ask, if you mind to expose it as a method of `style` so we could add multiple sprites after the initial loading?

```js
style.loadSprite(url)
```

Thank you

**Comment by kkaefer** [comment]
See https://github.com/mapbox/mapbox-gl-js/pull/9226#issuecomment-578098987
