### ISSUE TITLE
Mouse wheel stops animation when scrollZoom is disabled

### ISSUE THREAD

**Issue by TiloNN** [mapbox/mapbox-gl-js#9230]
**mapbox-gl-js version**: 1.6.1

### Question
Is it correct, that a user mouse wheel interaction stops a fly to animation, even when the scrollZoom was deactivated? 

```           
map.on('wheel', function(e) {
    e.preventDefault();
});

map['scrollZoom'].disable();
map['boxZoom'].disable();
map['dragRotate'].disable();
map['dragPan'].disable();
map['keyboard'].disable();
map['doubleClickZoom'].disable();
map['touchZoomRotate'].disable();

map.fitBounds( geojsonExtent(geojson), {
    padding: {top: 200, bottom:30, left: 30, right: 30}
});

```

If so, Is there a way to prevent that?
I opened a stackoverflow question, but like to make sure it is not a bug.

https://stackoverflow.com/questions/59895815/how-to-prevent-with-mapbox-gl-js-that-a-mouse-wheel-interaction-stops-a-fitboun

Thx for your support!

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/example/disable-scroll-zoom/

**Comment by kkaefer** [comment]
Thanks for this bug report. This indeed is a bug; mouse wheel activity shouldn't interfere with anything if the scrollZoom handler is disabled.

**Comment by ansis** [comment]
This has been fixed by https://github.com/mapbox/mapbox-gl-js/pull/9365. If you have a chance to test and confirm, that would be great! The fix is in `master` and will be released in a beta release tomorrow.

**Comment by karimnaaji** [comment]
@TiloNN the fix that @ansis mentioned was published yesterday, feel free to give it a try! https://www.npmjs.com/package/mapbox-gl/v/1.10.0-beta.1

**Comment by TiloNN** [comment]
Looks good.
Works for me, thanks!
I'll wait until it leaves beta before using it productive.
