### ISSUE TITLE
Figuring out when clusters are query-able (computed and rendered)

### ISSUE THREAD

**Issue by alexandrukis** [mapbox/mapbox-gl-js#9234]
**mapbox-gl-js version**: 1.2.1

### Question

Hello. I have this scenario which I'm failing to properly detect:

0. The user enters the page at a certain boundingRect (so the map is not always centered at the same position)
1. I'm providing a GeoJSON to MapBox, specifying the data should be clustered
2. I'm waiting for everything to be rendered
3. I want to select the features in the current viewport, so I can display everything in a list

The problem is - I didn't find any good way of figuring out when the the data has been loaded  and rendered on the map (step 2). If the user is at some weird position, **there's no way I can figure out if there are no clusters in that area, or the data simply hasn't been loaded yet**.

I have tried multiple hacks and workarounds, like listening to `sourcedata`, `data`, `style.load`, or `idle` events, checking `map.areTilesLoaded()` or `map.loaded()`, but nothing works.

Any ideas on how to achieve this? 

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/api/#map#querysourcefeatures
https://docs.mapbox.com/mapbox-gl-js/api/#geojsonsource

**Comment by arindam1993** [comment]
hey @alexandrukis !

I think the [Filter features within a map view example](https://docs.mapbox.com/mapbox-gl-js/example/filter-features-within-map-view/) should be helpful for your use case.
We typically reserve the GitHub issue pages for bug-reports or new-feature discussions. I think you'd get broader help from the community on stackoverflow instead. Closing this, please feel free to reopen if you find a bug with your usecase!

**Comment by alexandrukis** [comment]
Hey @arindam1993. I appreciate your fast answer, but this is not really what I asked. 

I am perfectly comfortable with querying features in the viewport. What I need is a way to know when the features are query-able, so I can interpret an empty list correctly - is it empty because there are no features _anywhere_, or is it empty because there are simply no features at this map position.

In a sense, this _is_ a feature request, as I cannot see any mechanism I can use to know when everything is stable, all the computations are finished, and `queryRenderedFeatures()` will actualy return results from my provided GeoJSON.
