### ISSUE TITLE
how to get coordinates bounds of image overlay

### ISSUE THREAD

**Issue by phanthinh** [mapbox/mapbox-gl-js#9257]
**mapbox-gl-js version**: 1.4.1

### Question
I have to write an example `add image URL to mapbox` 
1/ I added an image URL https://lh6.googleusercontent.com/proxy/m0Abshs45CPxuq9yF_yiOWdP5Aal1-lDOUEZNxS_11ozM9zunXXfomjsD7-gSmMrs91ozOPpu3gQQBZ4FkRnGaUtPo_2nGg88FxasdgveQ5Eq6diTc3SbJw76Stb1-5RXg
2/ Show to center a latitude/longtitude

My question: I want to get coordinates bounds of the image. How to do it? 

Best regards,
Phan Thinh

**Comment by ryanhamley** [comment]
If you're adding the image by calling `map.addImage`, you may be better off creating an [image source](https://docs.mapbox.com/mapbox-gl-js/api/#imagesource) which allows you to specify the bounds of the image yourself. To zoom to the image and center it, you could then use those bounds in [`map.fitBounds`](https://docs.mapbox.com/mapbox-gl-js/api/#map#fitbounds).

Note that this Github queue is for reporting bugs and requesting features. For "how to" questions like this, we recommend contacting [Mapbox support](https://support.mapbox.com/hc/en-us) or asking on Github. Thanks!
