### ISSUE TITLE
Non mapbox URLs don't work for vector tiles?

### ISSUE THREAD

**Issue by timrobertson100** [mapbox/mapbox-gl-js#927]
I don't know if this is restricted to vector tiles or not, but I am using this:

```
    "local": {
      "type": "vector",
      "url": "http://localhost:3000/api/0/0/0.vector.pbf",
      "maxzoom": 15
    }
```

And the VectorTile is never instantiated. I have not got to the bottom of it, but somewhere there is a ```"SyntaxError: Unexpected token" ``` being thrown after the source is added.  

My complete style is [on this gist](https://gist.github.com/timrobertson100/253dc5dc8a36a0765eb0)

Perhaps it is the http://  or perhaps the port that causes the issue?

**Comment by timrobertson100** [comment]
This issue is reported in error.  

I had correctly implemented a backend, but the client starts by requesting a JSON document which is expected to describe the layer - this _appears_ to be an undocumented step.  For anyone stumbling across this issue, you need to provide metadata JSON along the lines of the following in addition to the vector service:
```
{
  "version": 6,
  "constants": {
    "@land": "#f4efe1",
    "@water": "#cdd"
  },
  "sources": {
    "mapbox": {
      "type": "vector",
      "url": "mapbox://mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v6-dev",
      "maxzoom": 15
    },
    "local": {
      "type": "vector",
      "url": "http://localhost:3000/meta.json",
      "maxzoom": 15
    }
  },
  "layers": [
    {
      "id": "background",
      "type": "background",
      "paint": {
        "background-color": "@land"
      }
    },
    {
      "id": "water",
      "type": "fill",
      "source": "mapbox",
      "source-layer": "water",
      "paint": {
        "fill-color": "@water",
        "fill-opacity": 0.75,
        "fill-outline-color": "#a2bdc0"
      }
    },
    {
      "id": "local",
      "type": "fill",
      "source": "local",
      "source-layer": "road",
      "minzoom": 0,
      "maxzoom": 22,
      "paint": {
        "fill-color": "#ff0",
        "fill-opacity": 1,
        "fill-outline-color": "#a2bdc0"
      }
    }
  ]
}
```

**Comment by jfirebaugh** [comment]
Hey @timrobertson100. You also have the option of including the TileJSON inline in the source:

```
...
    "local": {
      "type": "vector",
      "maxzoom": 15,
      "tiles": ["http://localhost:3000/api/{z}/{x}/{y}.vector.pbf"]
    }
...
```

This is documented in the Mapbox GL [style spec](https://www.mapbox.com/mapbox-gl-style-spec/#sources).

**Comment by timrobertson100** [comment]
Thanks!
