### ISSUE TITLE
Map opens in the same position on map no matter what I do with the 'center' column, and panning, zoom etc is extremely buggy

### ISSUE THREAD

**Issue by jason-james** [mapbox/mapbox-gl-js#9271]
**mapbox-gl-js version**: 1.7

**browser**: Chrome and Opera

### Steps to Trigger Behavior

```        
map = new mapboxgl.Map({
            container: this.mapContainer,
            style: 'mapbox://styles/iotxplorer/ck6c2lgoo4nuo1iqhp2yt7ary',
            zoom: 11.15,
            center: [-0.15003204345703125, 51.50489601254001],
            hash: true,
            maxBounds: bounds
        });
```
### Link to Demonstration

Link to video displaying behavior: https://streamable.com/cyfd7

Part of the choppiness is due to the video recording but partly it actually looks like that. When I zoom out it shows flashes of where it should actually be centered to. On reload it just always defaults to that location or nearby it. I suspect the actual location is 'underneath' somehow but when I use hash=true it has the actual coordinate of where it loads to, rather than where I specify as center.

I have tried to set center in code, and lock center as a custom css style on the mapbox website, nothing works. Also, the coordinates that it is actually loading on are not referenced anywhere in the code.

Its also definitely not my computer.

### Expected Behavior
I would expect zoom pan and centre to work without bugs. Or at least centre. 

### Actual Behavior
It dosen't

**Comment by andrewharvey** [comment]
What value are you passing for maxBounds? It sounds  like the viewport is being constrained by your maxBounds.

**Comment by jason-james** [comment]
> What value are you passing for maxBounds? It sounds like the viewport is being constrained by your maxBounds.

Oh man thank you, that was it. 

The value was

```
        var bounds = [
            0.248565673828125,51.33146969705743, // Southwest coordinates
            -0.5005645751953125, 51.65211086156918, // Northeast coordinates
        ];
```

If I remove maxbounds it works.
