### ISSUE TITLE
How do I get source id of mapbox layer. 

### ISSUE THREAD

**Issue by tnsivanagarajan** [mapbox/mapbox-gl-js#9273]
Hello everyone,

I am new to mapbox-gl-js. 

I am working in mapbox-gl-js related development since last week.

I am rendering map from mapbox api URL. Please see below.

**https://api.mapbox.com/styles/v1/mapbox/streets-v11?access_token=${MAPBOX_ACCESS_TOKEN}**

But I wanted to know that where I can get **source id**.

**Comment by mourner** [comment]
```js
const sourceId = map.getLayer('park').source;
```

Note that this is a place to report issues with the library. For generic questions, it's best to ask on StackOverflow or contact support@mapbox.com.
