### ISSUE TITLE
Can I use a 'fill' type layer if my source is clustered?

### ISSUE THREAD

**Issue by omguhh** [mapbox/mapbox-gl-js#9277]
Hello!  I love this library, it's amazing - thank you for all the hard work :) 

I wanted to ask if it was possible to use a 'fill' type of layer if my source has the cluster properties?

An example: 

```
export default (features) => ({
    key: 'clustered',
    value: {
        type: 'geojson',
        data: {
            type: 'FeatureCollection',
            features
        },
        cluster: true,
        clusterMaxZoom: 14, // Max zoom to cluster points on
        clusterRadius: 50 // Radius of each cluster when clustering points (defaults to 50),
    }
})
```

and the layer would be something like: 

```
{
    id: id,
    type: "fill",
    source: "clustered",
    "filter": ["!", ["has", "point_count"]],
    "fill-color": "#38ACC9",
    "fill-opacity":  0.5
}
```

I'm not seeing anything on the map if I try this :/ am I just misunderstanding what the cluster layer is used for? does it always have to be a circle type of layer?

**Comment by karimnaaji** [comment]
I don't think that you can visualize this layer type with it, points are the only layer type that you can visualize with the cluster option (correct me if I'm wrong @mourner).

@omguhh Did you find that documentation was lacking information about that?

**Comment by asheemmamoowala** [comment]
Hi @omguhh! Thanks for reaching out. As the team requested more information and we haven't heard back in over a month, we're going to close this out. If you want to reopen it, please:

- Include a link to a minimal demonstration of your code. We recommend using https://jsbin.com.
- Include links to the specific section(s) of the documentation where you would have expected to find an answer to this question.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.

Thank you!
