### ISSUE TITLE
Create a Geocode Marker on map render

### ISSUE THREAD

**Issue by Magnuspil** [mapbox/mapbox-gl-js#9278]
Hi,

After long searching in the docs, I can't seem to find an answer to this.
DEMO Site: kygo-watches.com/mapbox

Background:
We are trying to create an application, which includes Mapbox Geocoder API, where there is just one marker at all time, whether you search or click the map, the same marker just moves around. 

As of now, you can only create a marker if you search first - then you can click around to move the marker. We are curious, if it's possible to create the click functionality already on map render, so the user have the ability to create the marker, without having to search first?

Thank you very much!

**Comment by asheemmamoowala** [comment]
@Magnuspil Have you looked at this example: https://docs.mapbox.com/mapbox-gl-js/example/drag-a-marker/

For future "how do I" questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests. Thank you!
