### ISSUE TITLE
Enhancement request: token based coloring

### ISSUE THREAD

**Issue by timrobertson100** [mapbox/mapbox-gl-js#928]
It would be really nice to be able use ```{tokens}``` to customize styling based on feature values.  e.g. 
```
"paint": {
  "fill-color": "{color}";
  "line-color": "rgb({r}, {g}, {b})",
}
```
Is something like this in the pipeline please?

**Comment by mourner** [comment]
Yes, we consider implementing something like this. Similar issue: https://github.com/mapbox/mapbox-gl-style-spec/issues/105 — we discuss style improvements in that repo.
