### ISSUE TITLE
How to add bing maps with api key?

### ISSUE THREAD

**Issue by microspace** [mapbox/mapbox-gl-js#9283]
How do I add bing maps to mapbox gl js?
I've seen [this example ](https://github.com/kepta/idly/wiki/examples#using-bing-satellite-map), but it is violating bing maps [term of use](https://www.microsoft.com/en-us/maps/product).

So question is: How to pass to `tiles` the url, i get from [Get Imagery Metadata](https://docs.microsoft.com/en-us/bingmaps/rest-services/imagery/get-imagery-metadata) ?

This is wrong, as I directly pass tile url endpoints. I want to pass url endpoint returned from Get Imagery Metadata API method.

   ```
                sources: {
                    'raster-tiles': {
                        type: 'raster',
                        tiles: [
                            'https://ecn.t0.tiles.virtualearth.net/tiles/a{quadkey}.jpeg?g=587&mkt=en-gb&n=z',
                            'https://ecn.t1.tiles.virtualearth.net/tiles/a{quadkey}.jpeg?g=587&mkt=en-gb&n=z',
                            'https://ecn.t2.tiles.virtualearth.net/tiles/a{quadkey}.jpeg?g=587&mkt=en-gb&n=z',
                            'https://ecn.t3.tiles.virtualearth.net/tiles/a{quadkey}.jpeg?g=587&mkt=en-gb&n=z',
                        ],
                    },
                },
   ```

**Comment by karimnaaji** [comment]
Hey @microspace for how-to and term of use concerns it's better to directly reach out to 
support@mapbox.com they are better equipped for this type of questions. We're trying to reduce the amount of issues that are not directly related to the library and focus on feature discussions and/or bugs.

**Comment by microspace** [comment]
Thank you for response, @karimnaaji . Can you consider my question as feature request?

**Comment by moravcik** [comment]
The SO answer is saying only how to get Bing tile URL template, but the real problem is that I need to compute quadKey to supply to Bing URL template. 

It is basically this code:

    export function tile2quad(x: number, y: number, z: number): string {
      let quad = '';
      for (let i = z; i > 0; i--) {
        let digit = 0;
        const mask = 1 << (i - 1);
        if ((x & mask) !== 0) {
          digit++;
        }
        if ((y & mask) !== 0) {
          digit += 2;
        }
        quad = quad + digit;
      }
      return quad;
    }

So the question is, how can I wire `tile2quad` function to `style.sources[mysource].tiles` pattern ?

**Comment by microspace** [comment]
Mapbox has [built in](https://github.com/mapbox/mapbox-gl-js/blob/63a683ffc29e30fda06cb73a5dec5a2ed8d862f0/src/source/tile_id.js#L189) quadkey support.
Here is [example ](https://github.com/kepta/idly/wiki/examples#using-bing-satellite-map).

**Comment by moravcik** [comment]
@microspace, thank you for your help. 

May I have one additional question? 
Is there any support for custom tile URL function like `getTileUrl()` in Leaflet? 

We have following URL pattern `BASE_URL/{z}/z{z}_{x}x{y}.jpg` and `{z}` gets resolved only once. But there are also other cases where URL has to be computed in few lines of code. Thank you again.
