### ISSUE TITLE
Map doesn't load if location can't be determined

### ISSUE THREAD

**Issue by Xandaros** [mapbox/mapbox-gl-js#9301]
**mapbox-gl-js version**: No clue

**browser**: Firefox 72.0.1

### Rest of the template

I can't really follow the rest of the template. I was told by [baduk.club](https://baduk.club/map/) to report the issue here. In fairness, I do think the problem is on mapbox's side.

If I try to open the website in Firefox, it simply stays blank. Or, since they are now aware of the issues, leaves you with a message pointing you here.
It appears that it attempts to get geoip data by making a request to https://ipinfo.io/json, which is blocked due to CORS policies. Chromium seems to allow it, though... at least for me. I've seen reports saying it works in Firefox, but not in Chrome.

The exact errors in console:
```
Loading failed for the <script> with source “https://cdn.simpleanalytics.io/hello.js”. map:140:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ipinfo.io/json. (Reason: CORS request did not succeed).

TypeError: NetworkError when attempting to fetch resource.
```

Maybe there are other issues at play here, they really should have their own issue tracker. If this turns out to be irrelevant, I'm sorry for the noise.

**Comment by ryanhamley** [comment]
It fails in Chrome for me, but not in Firefox. At any rate, this isn't an issue with GL JS. They would need to adjust their application to allow for fetching cross origin resources and/or they should have a fallback in case the initial location gathering fails (e.g. if they can't fetch a location, they could just show a default map of the world). We also provide a simple way of gathering a user's location that's integrated with the map via our [Geolocate Control](https://docs.mapbox.com/mapbox-gl-js/example/locate-user/).

If they truly believe there's a bug with GL JS, they would need to create an issue, fill out all the necessary information and have a minimal reproduction of the bug. Telling users to report it is not helpful for us or the users.
