### ISSUE TITLE
How to multiply a value when using identity property functions on Geojsonlayer styling ?

### ISSUE THREAD

**Issue by capan** [mapbox/mapbox-gl-js#9302]
**mapbox-gl-js version**: 5.2.1

### Question

How to multiply a value when using identity property functions for styling ? I want to multiply a value, in my case it is **magnitude**;

```
MapboxGL.CirclePaint = {
      'circle-color': 'red',
      'circle-radius': { type: 'identity', property: 'magnitude' },
    };
```

I've tried 

```
MapboxGL.CirclePaint = {
      'circle-color': 'red',
      'circle-radius': { type: 'identity', property: 'magnitude*5' },
    };
```
But it seems to be not working with identity property functions.

**Comment by ryanhamley** [comment]
The function syntax is deprecated. We recommend using expressions instead. For this particular use case, you can use the [`*` expression](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#*) like so `circle-radius: ['*', ['get', 'magnitude'], 5]`
