### ISSUE TITLE
Popup Position Question

### ISSUE THREAD

**Issue by sgurin** [mapbox/mapbox-gl-js#9306]
Hi guys,

Thanks for such a cool tool. We use a mapbox on our website and attach popup to the pins on the map.

We need to control the position of the popup when it reaches the corner of the block https://prnt.sc/r46jrr

We found that your API automatically put classes on the popup when it sticks to the edge of the block https://docs.mapbox.com/mapbox-gl-js/example/popup/ but it works only if the popup is in the middle of the pin. Our popup is on the left side of the pin.

How we can control when classes  mapboxgl-popup-anchor-left appears? Because now it appears only when we rich half of the popup width :(

Thanks a lot

**Comment by andrewharvey** [comment]
Sorry I don't understand. What does "block" and "sticks" mean?

Could you elaborate more, and ideally put together a minimal example which demonstrates the issues or request?

**Comment by sgurin** [comment]
@andrewharvey Hi, sorry for the complicated explanation.

Please take a look on the example https://jsfiddle.net/n09hx6wa/

I took en example from https://jsfiddle.net/api/post/library/pure/ and changed left position of the popup. But class mapboxgl-popup-anchor-bottom-left https://prnt.sc/r4honl added only if I cross the 1/2 width of the popup. So, how can I change position of the popup if its left side of the popup would be on the left edge of the visible mapbox area?

**Comment by andrewharvey** [comment]
I'm still not sure I completely get it, but the `.mapboxgl-popup { left: -100px; }` is what's causing an issue since it's throwing off the auto-anchor calculation.

If you don't want auto-anchor, then you can pass a fixed anchor option to the Marker https://docs.mapbox.com/mapbox-gl-js/api/#marker

**Comment by sgurin** [comment]
@andrewharvey 

Yep, position of the popup is our headache. In our design https://prnt.sc/r4j8l5 popup located at -100px 
100 pixels to the left of the pin. We need to change popup position from left to right when 
when its edge is touching the edge of the block with the map. Otherwise it would be cropped as on the screen.  I found an example https://docs.mapbox.com/mapbox-gl-js/example/popup/. It that example if you drag map to the left https://prnt.sc/r4jboh the popup position would be changed https://prnt.sc/r4jbw3 It happens because there is some listener that check position of the popup https://prnt.sc/r4jc6t and change the classname on the popup when the pin is on the PopupWidth/2 distance from the edge of the visible area of the map. https://prnt.sc/r4jdu9 https://prnt.sc/r4je4g

In our design popup is not in the middle of the pin. So, the class appears not correctly :( https://prnt.sc/r4jf02 still the same class https://prnt.sc/r4jffg and only if I drag the map on half of the popup size https://prnt.sc/r4jg3b

So, the class should be changed right after the beginning of the popup coincides with the edge of the map https://prnt.sc/r4jhd4

**Comment by andrewharvey** [comment]
Any reason not to use an `offset` option, instead of the left css, or just increase the width and do your styling internal to the Marker element?

I don't think there is anything we can do if you're fiddling with the positioning external to GL JS.
