### ISSUE TITLE
Dash Array support for circle

### ISSUE THREAD

**Issue by mtiwari95** [mapbox/mapbox-gl-js#9309]
### Dash circle layer on a point does not exist in the list of example. 
![image](https://user-images.githubusercontent.com/45939087/74810299-15009600-5315-11ea-9a8a-68b9131585dd.png)
I have gone through all of the examples as shown below URL and also checked the Mapbox GL JS repository for an existing issue. But there is no issue created for this.

https://docs.mapbox.com/mapbox-gl-js/example/add-image-animated/

https://github.com/mapbox/mapbox-gl-js/issues/

**Comment by stevage** [comment]
Out of curiosity, what is your use case? You could use something like `turf.circle` to generate circular geometry, then style it like any other line.

**Comment by mtiwari95** [comment]
Great, thanks for the help. I am able to create the dashed circle by using Turf.js and it has lots of module to work with geospatial analysis.
