### ISSUE TITLE
Line jag bug

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#931]
I can't explain this one, but found this weird jag on what should be a straight road line segment (E Main St in Durham, NC should run completely straight through this screenshot). This is reproducible across GL styles:
![image](https://cloud.githubusercontent.com/assets/3170312/5730156/c4ea8ae0-9b2c-11e4-8228-0688a77629a0.png)
(this view is at [35.995, -78.901], z 16.6)
![image](https://cloud.githubusercontent.com/assets/3170312/5730152/bdaba67e-9b2c-11e4-85b7-1857ea189a07.png)
![image](https://cloud.githubusercontent.com/assets/3170312/5730251/5c5f4550-9b2d-11e4-81de-54bb89372ba6.png)

For comparison, see classic Mapbox JS styles:
(4sq — highlighted where the GL jag is, area visible in [this query](https://foursquare.com/explore?mode=url&near=Durham%2C%20NC&q=rue%20cler))
![image](https://cloud.githubusercontent.com/assets/3170312/5730186/f54cfdb2-9b2c-11e4-9b0b-7a266fc7a7a6.png)
(mapbox.com example map)
![image](https://cloud.githubusercontent.com/assets/3170312/5730276/8aa621fe-9b2d-11e4-821b-d704c74fa07e.png)

**Comment by jfirebaugh** [comment]
This was a glitch in the OSM data -- see the history for [this node](http://www.openstreetmap.org/node/2613436020/history).

Will ticket upstream to investigate why the change from 3 months ago isn't showing up in the vector tiles.
