### ISSUE TITLE
Disjointed refresh of cluster circles vs cluster labels on zoom

### ISSUE THREAD

**Issue by gwacker** [mapbox/mapbox-gl-js#9318]
https://docs.mapbox.com/mapbox-gl-js/example/cluster/

If you zoom in and out on the cluster example, the cluster circles refresh at a different time than the cluster labels which depending on delay length can give the function a jerky, disjointed feel.

If the timing of the cluster circle and label updates could be synced it would give a better experience  more inline with the buttery smoothness that is Mapbox GL JS.

**Comment by asheemmamoowala** [comment]
@gwacker Thank you for reporting this issue. 

The synchronization issue you are seeing is due to the label fade duration which can be controlled by setting the `fadeDuration` option in the Map constructor to `0`.
