### ISSUE TITLE
What are the correct types to map variables using Mapbox in React-Typescript app?

### ISSUE THREAD

**Issue by Rumpelstinsk** [mapbox/mapbox-gl-js#9319]
After taking a look to [mapbox documentation][1], I wrote this component

    import React from "react";
    import mapboxgl from "mapbox-gl";
    import "./Map.css";
    
    mapboxgl.accessToken = "...";
    
    type Props = {
      longitude: number;
      latitude: number;
    };
    
    class Map extends React.Component<Props> {
      private mapContainer: any;
      private map: any;
    
      componentDidMount(): void {
        this.map = new mapboxgl.Map({
          container: this.mapContainer,
          center: [this.props.longitude, this.props.latitude],
          style: "....",
          zoom: 13
        });
      }
      render(): JSX.Element {
        return (
          <div
            ref={(el): void => {
              this.mapContainer = el;
            }}
            className="mapContainer"
          />
        );
      }
    }
    
    export default Map;

This code works correctly, however, in my real project, we are using TypeScript. I don't want to use `any` for `mapContainer` and `map`.

I have imported `"@types/mapbox-gl": "^1.7.0",` into my project, but I cannot figure out what type I have to use here.

My tries until now:

 - `private map:mapboxgl.Map`. It seems to be correct, but then it complais because it is not initialized on the constructor. According to mapbox documentation it has to be initialize on `componentDidMount`. I can type the variable with `mapboxgl.Map | null`. But then i have to check constally to not be null, to remove  some annoying warnings.
 - `private mapContainer = React.userRef<HtmlElement>(null);`. But then, when i try to initialize the map, it says Type `'RefObject<HTMLElement>' is not assignable to type 'string | HTMLElement'.`

Any ideas?

  [1]: https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/?utm_medium=sem&utm_source=google&utm_campaign=sem%7Cgoogle%7Cbrand%7Cchko-googlesearch-pr01-dynamicsearchcampaign-nb.broad-all-landingpage-search&utm_term=brand&utm_content=chko-googlesearch-pr01-dynamicsearchcampaign-nb.broad-all-landingpage-search&gclid=EAIaIQobChMImYqUwa3g5wIV1_ZRCh2rAg_2EAAYASAAEgI_SPD_BwE

**Comment by Rumpelstinsk** [comment]
Thanks to r3dst0rm in StackOverflow

**Comment by louiskenyon98** [comment]
What was the solution to this?

**Comment by trwong** [comment]
found the StackOverflow solution: https://stackoverflow.com/questions/60322612/what-are-the-correct-types-to-map-variables-using-mapbox-in-react/60334542#60334542
