### ISSUE TITLE
"in" expression not working inside "case" expression

### ISSUE THREAD

**Issue by akern40** [mapbox/mapbox-gl-js#9336]
**mapbox-gl-js version**: 1.3.1

**browser**: Firefox 72.0.2, Chrome 80.0.3987.116

### Steps to Trigger Behavior

 1. Setup an icon layer
 2. Use an "in" expression inside a "case" expression when setting a paint property

### Link to Demonstration

https://jsbin.com/zidovuketo/edit?html,console,output

### Expected Behavior
The icon should show at full opacity.

### Actual Behavior
Error occurs; in the jsbin the error message won't print (not sure why), but the error I'm getting is:
```
Error: "layers.toronto-restaurants.paint.icon-opacity[1][0]: Unknown expression "in". If you wanted a literal array, use ["literal", [...]]."
```

Any help would be greatly appreciated; if it turns out I'm just doing something wrong, sorry!

**Comment by ryanhamley** [comment]
The `in` expression was added in `1.6.0` but your demonstration is using `1.3.1`. You need to upgrade your GL JS version.
