### ISSUE TITLE
Xcode error: "UnityArKit.a" directory not found

### ISSUE THREAD

**Issue by Taymourabdelal** [mapbox/mapbox-gl-js#9341]
Anyone got this error before?

clang: error: no such file or directory: '/..../Libraries/com.unity.xr.arkit/Runtime/iOS/UnityARKit.a'
Command Ld failed with a nonzero exit code

**Comment by mourner** [comment]
You accidentally posted this in the wrong repo — this one isn't related to Unity or iOS.
