### ISSUE TITLE
Trying to get exact number of properties/cluster children under a cluster on Click/hover

### ISSUE THREAD

**Issue by AkashJeedigunta** [mapbox/mapbox-gl-js#9348]
**mapbox-gl-js version**: 1.8.0

### Question
I have introduced HTML custom clusters on the Map using => https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/

I am trying to click/hover on a cluster and a single point to get the properties under it. But the returned objects are inconsistent and sometime returns nothing

*If it is a single point on the map give me single object with it's properties*

*If it is a clustered point , return array of objects with all properties under that cluster that are not visible yet, like how Deck.gl shows on hover => https://deck.gl/#/examples/core-layers/icon-layer*

### Links to related documentation

Tried APIS from mapbox are mentioned below. Able to get the point for a single point but when clicked on cluster does not go in the 'click' function

### To get clustered bound using query APIS:
https://docs.mapbox.com/mapbox-gl-js/api/#map#queryrenderedfeatures
https://docs.mapbox.com/mapbox-gl-js/api/#map#querysourcefeatures

### To find cluster children
https://docs.mapbox.com/mapbox-gl-js/api/#geojsonsource#getclusterchildren
https://docs.mapbox.com/mapbox-gl-js/api/#geojsonsource#getclusterleaves

### Sample of my code 
https://jsfiddle.net/rb76Lutd/

Please assist if I am doing it right or missing any key piece. Thanks in advance

**Comment by asheemmamoowala** [comment]
@AkashJeedigunta in the fiddle you have provided, there is no layer rendered on the map with the clustered points, so the `queryRenderedFeatures` call will not return any cluster points. You can add an additional layer with a `filter:[ '==', 'cluster', true]` to fix that.
