### ISSUE TITLE
StyleImageInterface definition differs from the documented interface

### ISSUE THREAD

**Issue by DiogoAndre** [mapbox/mapbox-gl-js#9350]
**mapbox-gl-js version**: Master

The `StyleImageInterface` defined on  [style/style_image.js](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style/style_image.js#L24-L31) is different from the version documented on the same file. The return type for the `render()` function is implemented as `void` but documented as `boolean`, which looks like the correct return type.

```
export type StyleImageInterface = {
    width: number,
    height: number,
    data: Uint8Array | Uint8ClampedArray,
    render?: () => void,
    onAdd?: (map: Map, id: string) => void,
    onRemove?: () => void
};
```

```
 * @function
 * @memberof StyleImageInterface
 * @instance
 * @name render
 * @return {boolean} `true` if this method updated the image. `false` if the image was not changed.
```

**Comment by ryanhamley** [comment]
Closed by https://github.com/mapbox/mapbox-gl-js/pull/9604
