### ISSUE TITLE
How to unit test expressions

### ISSUE THREAD

**Issue by nreese** [mapbox/mapbox-gl-js#9354]
Is there any way to unit test expressions? For example, I am working on an expression to pull a value from features and would like to set up a unit test that takes the expression and provides the output when passed features. Is this possible.

**Comment by ryanhamley** [comment]
@nreese We have [separate tests for expressions](https://github.com/mapbox/mapbox-gl-js/tree/master/test/integration/expression-tests) which aren't unit tests. The expression test runner is https://github.com/mapbox/mapbox-gl-js/blob/master/test/expression.test.js

Is this something you're planning on submitting as a PR for inclusion in the library?

**Comment by nreese** [comment]
> Is this something you're planning on submitting as a PR for inclusion in the library?

No. Testing the output of expressions in isolation seems like a common use case across mapbox users. I am just curious if there was an easy way to test expressions.

**Comment by ryanhamley** [comment]
Ah ok, it sounds like you're thinking more of a way to evaluate an expression outside of GL JS like https://github.com/mapbox/mapbox-gl-js/issues/7670

**Comment by nreese** [comment]
> it sounds like you're thinking more of a way to evaluate an expression outside of GL JS like #7670

Yes.

**Comment by ryanhamley** [comment]
Cool, I'm going to close this as a duplicate so we can focus discussion in one ticket. Thanks!
