### ISSUE TITLE
Get Zoom level of bounding box

### ISSUE THREAD

**Issue by maximelebreton** [mapbox/mapbox-gl-js#9360]
Hello, I would like to have the **zoom level** of a **bounding box**.

I'm **not interested** by `map.fitBounds`, because I want to set a specific **center** with `map.flyTo `or `map.easeTo`.

So I would like to do this:
```js
const bounds = new mapboxgl.LngLatBounds([-73.9876, 40.7661], [-73.9397, 40.8002]);
const boundsZoom = bounds.getZoomLevel(); // <-- this method doesn't exists, that's my wish
map.flyTo({
  center: [-73.9876, 40.7661],
  zoom: boundsZoom
});
```

Thanks

**Comment by tristen** [comment]
👋 @maximelebreton I'd recommend looking at a package like https://github.com/mapbox/geo-viewport to do that. Also heads up that questions like these are best asked on StackOverflow.

**Comment by maximelebreton** [comment]
thanks @tristen
