### ISSUE TITLE
express in line-pattern is not work

### ISSUE THREAD

**Issue by qq379797807** [mapbox/mapbox-gl-js#9361]
when i use express in layer's line-paint like below is not work when state is change to selected .why? 
is work well in line-color, is it a bug? 

paint: {
    'line-paint:['case',
        ["feature-state", "selected"],false],['image','image_selected'],
        ['image','image_selected']
}

**Comment by mourner** [comment]
Please fill all the details when you're submitting an issue — we have no way of diagnosing an issue with such a scarce description and no reproducible live test case.
