### ISSUE TITLE
Opacity not changing for glTF 3D object

### ISSUE THREAD

**Issue by jclaun1** [mapbox/mapbox-gl-js#9363]
**mapbox-gl-js version**: Current

### Question
I am attempting to change the opacity of a custom layer which includes a 3D model loaded in using GLTFLoader. The code I am using is inspired by [this example](https://docs.mapbox.com/mapbox-gl-js/example/adjust-layer-opacity/), using the 3D object loading done [here](https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/).

The slider seems to be disconnected, but even when I try other approaches I have yielded no results.

index.php:

`<!DOCTYPE html>
            <html>
            <head>
                <meta charset="utf-8" />
                <title>Adjust a layer's opacity</title>
                <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
                <script src="https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.js"></script>
                <link href="https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css" rel="stylesheet" />
                <style>
                    body { margin: 0; padding: 0; }
                    #map { position: absolute; top: 0; bottom: 0; width: 100%; }
                </style>
            </head>
            <body>
                <style>

                .map-overlay {
                    font: bold 12px/20px 'Helvetica Neue', Arial, Helvetica, sans-serif;
                    position: absolute;
                    width: 25%;
                    top: 0;
                    left: 0;
                    padding: 10px;
                }            

                .map-overlay .map-overlay-inner {
                    background-color: #fff;
                    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
                    border-radius: 3px;
                    padding: 10px;
                    margin-bottom: 10px;
                }
            
                .map-overlay label {
                    display: block;
                    margin: 0 0 10px;
                }
            
                .map-overlay input {
                    background-color: transparent;
                    display: inline-block;
                    width: 100%;
                    position: relative;
                    margin: 0;
                    cursor: ew-resize;
                }
            </style>
            
            <div id="map"></div>
            
            <div class="map-overlay top">
                <div class="map-overlay-inner">
                    <label>Layer opacity: <span id="slider-value">100%</span></label>
                    <input
                        id="slider"
                        type="range"
                        min="0"
                        max="100"
                        step="0"
                        value="100"
                    />
                </div>
            </div>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/102/three.js"></script>
            <script src="https://unpkg.com/three@0.106.2/build/three.min.js"></script>
            <script src="https://unpkg.com/three@0.106.2/examples/js/loaders/GLTFLoader.js"></script>
            <script>
                mapboxgl.accessToken = 'pk.eyJ1IjoibmxhbWJlMiIsImEiOiJjazVubXJyM3IweDRwM25wNndlbWhjc3U5In0.4y-pp1CsRG42pY_h5xTdcA';
                var map = new mapboxgl.Map({
                    container: 'map',
                    style: 'mapbox://styles/nlambe2/ck74u5l5e0bkl1imzteomk9zr',
                    center: [-76.862165, 39.221635],
                    zoom: 20
                });
                // parameters to ensure the model is georeferenced correctly on the map
                var modelOrigin = [-76.862165, 39.221635];
                var modelAltitude = .1;
                var modelRotate = [Math.PI / 2, 1.375, 0];
                var modelAsMercatorCoordinate = mapboxgl.MercatorCoordinate.fromLngLat(
                    modelOrigin,
                    modelAltitude
                );

                // transformation parameters to position, rotate and scale the 3D model onto the map
                var modelTransform = {
                    translateX: modelAsMercatorCoordinate.x,
                    translateY: modelAsMercatorCoordinate.y,
                    translateZ: modelAsMercatorCoordinate.z,
                    rotateX: modelRotate[0],
                    rotateY: modelRotate[1],
                    rotateZ: modelRotate[2],
                    // rotateZ: -1,
                    /* Since our 3D model is in real world meters, a scale transform needs to be
                    * applied since the CustomLayerInterface expects units in MercatorCoordinates.
                    */
                    scale: modelAsMercatorCoordinate.meterInMercatorCoordinateUnits()
                };

                var THREE = window.THREE;

                // configuration of the custom layer for a 3D model per the CustomLayerInterface
                var customLayer = {
                    id: '3d-model',
                    type: 'custom',
                    renderingMode: '3d',
                    onAdd: function (map, gl) {
                        this.camera = new THREE.Camera();
                        this.scene = new THREE.Scene();

                        // create two three.js lights to illuminate the model
                        var directionalLight = new THREE.DirectionalLight(0xffffff);
                        directionalLight.position.set(0, -70, 100).normalize();
                        this.scene.add(directionalLight);

                        var directionalLight2 = new THREE.DirectionalLight(0xffffff);
                        directionalLight2.position.set(0, 70, 100).normalize();
                        this.scene.add(directionalLight2);

                        // use the three.js GLTF loader to add the 3D model to the three.js scene
                        var loader = new THREE.GLTFLoader();
                        loader.load(
                            'https://docs.mapbox.com/mapbox-gl-js/assets/34M_17/34M_17.gltf',
                            //'scene.gltf',
                            function (gltf) {
                                //gltf.scene.scale.set(.00750, .00750, .00750);
                                //gltf.scene.scale.set(.01, .01, .01);
                                this.scene.add(gltf.scene);
                            }.bind(this)
                        );
                        this.map = map;

                        // use the Mapbox GL JS map canvas for three.js
                        this.renderer = new THREE.WebGLRenderer({
                            canvas: map.getCanvas(),
                            context: gl,
                            antialias: true
                        });

                        this.renderer.autoClear = false;
                    },
                    render: function (gl, matrix) {
                        var rotationX = new THREE.Matrix4().makeRotationAxis(
                            new THREE.Vector3(1, 0, 0),
                            modelTransform.rotateX
                        );
                        var rotationY = new THREE.Matrix4().makeRotationAxis(
                            new THREE.Vector3(0, 1, 0),
                            modelTransform.rotateY
                        );
                        var rotationZ = new THREE.Matrix4().makeRotationAxis(
                            new THREE.Vector3(0, 0, 0),
                            modelTransform.rotateZ
                        );

                        var m = new THREE.Matrix4().fromArray(matrix);
                        var l = new THREE.Matrix4()
                            .makeTranslation(
                                modelTransform.translateX,
                                modelTransform.translateY,
                                modelTransform.translateZ
                            )
                            .scale(
                                new THREE.Vector3(
                                    modelTransform.scale,
                                    -modelTransform.scale,
                                    modelTransform.scale
                                )
                            )
                            .multiply(rotationX)
                            .multiply(rotationY)
                            .multiply(rotationZ);

                        this.camera.projectionMatrix = m.multiply(l);
                        this.renderer.state.reset();
                        this.renderer.render(this.scene, this.camera);
                        this.map.triggerRepaint();
                    }
                };
                
                var slider = document.getElementById('slider');
                var sliderValue = document.getElementById('slider-value');
                var current = 25;
                
                map.on('load', function() {
                    /*map.addSource('customLayer', {
                    'type': 'raster',
                    'url': 'mapbox://mapbox.u8yyzaor'
                    });
                    map.addLayer({
                        'id': 'chicago',
                        'source': 'chicago',
                        'type': 'raster'
                    });*/
                    
                    map.addLayer(customLayer, 'parking-new-height');
                    
                    map.setPaintProperty(
                        '3d-model',
                        'custom-opacity',
                        .25
                    );
                    customLayer.setProperties(
                        customOpacity( current / 100)
                    );
                    slider.addEventListener('input', function(e) {
                        // Adjust the layers opacity. layer here is arbitrary - this could
                        // be another layer name found in your style or a custom layer
                        // added on the fly using `addSource`.
                        map.setPaintProperty(
                            '3d-model',
                            'custom-opacity',
                            parseInt(e.target.value, 10)
                        );
                        
                        // Value indicator
                        sliderValue.textContent = e.target.value + '%';
                    });
                });
            </script>
            
            </body>
            </html>
    `

[backup.zip](https://github.com/mapbox/mapbox-gl-js/files/4273272/backup.zip)

**Comment by astojilj** [comment]
Something like this should do:

```
const setOpacity = (obj, value) => {
  if (obj['material']) {
    obj.material['transparent'] = true;
    obj.material['opacity'] = value;
  }
  for (let child of obj.children) setOpacity(child, value);
}
setOpacity(customLayer.scene, 0.25);
```

**Comment by jclaun1** [comment]
@astojilj This solution did not work. The layer is still unaffected

**Comment by astojilj** [comment]
@jclaun1 
> @astojilj This solution did not work. The layer is still unaffected

Check the scene object hierarchy in debugger to verify the values of properties and if the objects are under customLayer.scene.
Check also Renderer.alpha value and material alphaTest.
The question here is out of the Mapbox code scope as Three.js renderer handles rendering and opacity. Try to get information from some of the Three.js supporting forums.

**Comment by henning101** [comment]
@astojilj I ran into the same issue. For some reason the transparency sometimes works and sometimes it doesn't. I tried to change the layer ordering by moving the Three.js layer to the bottom or top using `moveLayer` but that doesn't seem to affect the result. I also tried to call
```
gl.glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA)
gl.glEnable( GL_BLEND )
```
in the onAdd function of the layer. But that doesn't work either

**Comment by henning101** [comment]
Nevermind. The problem was in my code logic. Trying to extend the Mapbox example https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/ I think it is quite easy to run into this pitfall so here's the problem: I added multiple identical GLFT objects to the Three.js layer because this is what you would normally do. Then, for each object I did the camera translation from the example for each individual object's lng lat. The problem is you don't need Three.js "copies" of the objects because all you do is move the camera around and take "pictures" of the same object. What happens is that if you add multiple transparent objects the transparency becomes less and less because the renderer keeps drawing them on top of each other without ever resetting. So long story short you only need to add the base object once in the `onAdd` function and then execute the render procedure from the example for each of your object instances (GeoJSON points for example) lng lat.

**Comment by astojilj** [comment]
@henning101 
Thank you. Solution you presented should perform better for a lot of copies. Of course, developer is responsible for sorting. 
Do you see problem with (semi) transparent PNGs opacity (if using them for sprites / 3D object textures) or with object opacities? Please free to share code / screenshot in new issue if you find some other issues with this approach.

**Comment by henning101** [comment]
@astojilj yea it's super fast even with a large number of copies. This is the modified example code (I loop through an array of GeoJSON objects with a point geometry):
```javascript
render: function(gl, matrix) {
  if (this.features !== undefined) {
    for (let i = 0; i < this.features.length; i++) {
      const feature = this.features[i]

      const modelTransform = mercatorTransform(
        feature.geometry.coordinates,
        0,
        [Math.PI / 2, 0, 0]
      )

      const rotationX = new THREE.Matrix4().makeRotationAxis(
          new THREE.Vector3(1, 0, 0),
          modelTransform.rotateX
      )
      const rotationY = new THREE.Matrix4().makeRotationAxis(
          new THREE.Vector3(0, 1, 0),
          modelTransform.rotateY
      )
      const rotationZ = new THREE.Matrix4().makeRotationAxis(
          new THREE.Vector3(0, 0, 1),
          modelTransform.rotateZ
      )

      const m = new THREE.Matrix4().fromArray(matrix);
      const l = new THREE.Matrix4()
          .makeTranslation(
              modelTransform.translateX,
              modelTransform.translateY,
              modelTransform.translateZ
          )
          .scale(
              new THREE.Vector3(
                  modelTransform.scale,
                  -modelTransform.scale,
                  modelTransform.scale
              )
          )
          .multiply(rotationX)
          .multiply(rotationY)
          .multiply(rotationZ);

      this.camera.projectionMatrix = m.multiply(l)
      this.renderer.state.reset()
      this.renderer.render(this.scene, this.camera)
      this.map.triggerRepaint()
    }
  }
}
```
I also put the transform code into a different file:
```javascript
import mapboxgl from 'mapbox-gl'

export const toMercatorCoordinate = (origin, altitude) => {
  return mapboxgl.MercatorCoordinate.fromLngLat(origin, altitude)
}

export const mercatorTransform = (origin, altitude, rotation) => {
  const mc = toMercatorCoordinate(origin, altitude)
  return {
    translateX: mc.x,
    translateY: mc.y,
    translateZ: mc.z,
    rotateX: rotation[0],
    rotateY: rotation[1],
    rotateZ: rotation[2],
    scale: mc.meterInMercatorCoordinateUnits()
  }
}
```
