### ISSUE TITLE
Not able to Order layers

### ISSUE THREAD

**Issue by hmendezm** [mapbox/mapbox-gl-js#9366]
**mapbox-gl-js version**: 1.8.1

**browser**: Chrome

### Steps to Trigger Behavior
Hi Guys.
I am using moverLayer but it looks like it does not take effect the new order. My situation is that the user has controls to allow to add a layer to the map. The user can choose any kind of combination but the layer should be ordered according to business rules. for instance, if you add the traffic information layer and after the zip code information layer. The user should be able to hover traffic and see information and hover zip code and see the information. The problem is the zip code layer cover traffic layer so I need always to the traffic layer in the top of zipcode. I also used layer beneath but it is not working. I checked the layer array and the order is ok but the map is not reflecting the order.

In the example attached, I am adding the layers in the correct order and the reoderLayer function will reorder the layers if the user changes the order. Although the layers are in order for the hover and click for the zip code layer always is triggered. 

Best,
hmendezm

### Link to Demonstration
found attached zip code with example

### Expected Behavior

1. When I hover traffic layer, it should show traffic popup info.
2. when I hove zip code, it should show zipcode popup info
3. when I hover or click cluster, it should do cluster action. 

### Actual Behavior
When I hover traffic or cluster always zipcode layer popup show up although the order  (bottom-top) of the layers are: zip code, traffic, and clusters 
[example overlaping layer problem.zip](https://github.com/mapbox/mapbox-gl-js/files/4276710/example.overlaping.layer.problem.zip)

**Comment by ryanhamley** [comment]
Your `mousemove` event for the `traffic` layer is being overridden by the `mousemove` event for `zipcode-fills`. Move the `traffic` listener to after the `zipcode-fills` one and it should work.

For future reference, it's very helpful to provide a _minimal_ example of the issue you're facing. Strip things down to the bare essentials that still show what's happening without things like SVG charts and CSS that don't affect the potential bug. Thanks for re-submitting with an example though. Hope this helps and if you have more questions on your implementation, I'd recommend contacting Mapbox support as we cannot offer general support through this issue tracker.

**Comment by hmendezm** [comment]
Thank you Ryan, I thought that when you move a layer using moveLayer, it will move also the events. 

Best,
Henry

**Comment by PeterMattenet** [comment]
How is this intended behavior? So then, layers can be moved from one order to another, but the mousemove events of those same layers can't? Even if I reorder my layers, I'm still stuck with the original mousemove event handlers order?
