### ISSUE TITLE
`line-pattern` soft breaking change ahead

### ISSUE THREAD

**Issue by karimnaaji** [mapbox/mapbox-gl-js#9394]
We are about to approve and go forward with https://github.com/mapbox/mapbox-gl-js/pull/9266.

To recap the discussions considering our current options; some of styling might have been designed with the current behavior in mind and changing it might lead to different results. To anticipate the confusion of the new behavior, we will make sure to provide a clear changelog entry and express our reasoning behind it.

We will eventually require to introduce new stylespec options to express different ways of wrapping textures and patterns, but for the time being and to give more consistent behavior to our users with the current spec, we will go forward and introduce a soft visual breaking change.

If anyone is concerned about their styles using `line-pattern`s, please share them here here so we can provide thorough guidance and support for the transition.

The steps to transition would require the following:
1. Compare your style in the new version of the build, is the new behavior of lines using `line-pattern` desired for your case? If not:
2. Look whether any of your image pattern is clipped (any case where the width of the line is smaller than the pattern attached to it)
3. For each of these lines revisit your asset in order to clip the pattern to match the previous behavior

To better understand the visual differences between the change the old and new behavior, make sure to look at the new baselines for the render tests in https://github.com/mapbox/mapbox-gl-js/pull/9266.

For other contacts make sure to either tag @chloekraw , @ansis or @karimnaaji !

**Comment by Plantain** [comment]
Would this change be causing graphical distortions with fill-pattern?
With a fill-pattern layer, zooming now is causing chaotic distortive behaviour like pictured:
![ex2](https://user-images.githubusercontent.com/319895/77984162-51400100-736d-11ea-9361-b047e5405bc7.png)a
![ex](https://user-images.githubusercontent.com/319895/77984167-52712e00-736d-11ea-927e-e3fb02281290.png)
![ex3](https://user-images.githubusercontent.com/319895/77984157-4f763d80-736d-11ea-9dbf-6ba8153ae046.png)

**Comment by karimnaaji** [comment]
That seems like a different issue, possibly related to https://github.com/mapbox/mapbox-gl-js/issues/9479, we may have an incorrect data layout bug we are currently tracking. Can you post how you are adding the image and what styling rules you are using for this layer?

**Comment by xfpopxf** [comment]
![image](https://user-images.githubusercontent.com/59993585/232950718-4eab9fd1-cefc-4a14-bbfc-afc471825cb8.png)

**Comment by xfpopxf** [comment]
line-pattern Image capping problem

**Comment by xfpopxf** [comment]
![pattern](https://user-images.githubusercontent.com/59993585/232951115-240e4b3d-76c4-4e63-add1-d492b50e4a82.png)
