### ISSUE TITLE
Retain Inline GeoJSON Feature Layer After setStyle is Called

### ISSUE THREAD

**Issue by m0hamad** [mapbox/mapbox-gl-js#9399]
Will there ever be support for retaining an inline GeoJSON layer after calling setStyle()? If you are working on something like that right now, is there is an effective alternative other than calling addSource() and addLayer() again which erases the current changes?

**Comment by asheemmamoowala** [comment]
@m0hamad We do not plan to build this at this time. The recommended approach is to call `addSource()`  and `addLayer()` separately. Note that even with that approach, the GeoJSON source will need to be present in the new style passed to `setStyle()`.
