### ISSUE TITLE
Ionic iOS and Android app crashes on zoom out

### ISSUE THREAD

**Issue by StevieWag** [mapbox/mapbox-gl-js#9415]
I am using mapbox-gl in an Ionic 5 app with Cordova. I have multiple layers on the map and Geolocation and Background-Geo in place. I am using Cordava Webview Plugin Version 4.1.0. with Ionic-Webview 5.22.0. I have the latest version of mapbox-gl installed.

In the browser, the app runs great and without any issues or console warnings/errors. 

When I deploy the app on native iOS or Android devices, the app crashes when the user zooms out. We tested it on various devices. There is no pattern I can identify - sometimes it crashes on the first zoom out, sometimes the app is quite stable for a while but still crashes after some zoom outs.

**Here are my package.json dependencies:**

"@angular/animations": "^8.2.14",
    "@angular/common": "^8.2.14",
    "@angular/core": "^8.2.14",
    "@angular/fire": "^5.4.2",
    "@angular/forms": "^8.2.14",
    "@angular/platform-browser": "^8.2.14",
    "@angular/platform-browser-dynamic": "^8.2.14",
    "@angular/router": "^8.2.14",
    "@capacitor/core": "^1.5.1",
    "@capacitor/ios": "^1.5.1",
    "@ionic-native/background-geolocation": "^5.22.0",
    "@ionic-native/core": "^5.22.0",
    "@ionic-native/diagnostic": "^5.22.0",
    "@ionic-native/geolocation": "^5.22.0",
    "@ionic-native/google-maps": "^5.5.0",
    "@ionic-native/http": "^5.22.0",
    "@ionic-native/ionic-webview": "^5.22.0",
    "@ionic-native/keyboard": "^5.22.0",
    "@ionic-native/splash-screen": "^5.22.0",
    "@ionic-native/status-bar": "^5.22.0",
    "@ionic-native/vibration": "^5.22.0",
    "@ionic/angular": "^5.0.4",
    "@mauron85/cordova-plugin-background-geolocation": "^3.1.0",
    "@ngx-translate/core": "^12.1.2",
    "@ngx-translate/http-loader": "^4.0.0",
    "@turf/along": "^6.0.1",
    "@turf/bearing": "^6.0.1",
    "@turf/circle": "^6.0.1",
    "@turf/destination": "^6.0.1",
    "@turf/distance": "^6.0.1",
    "@turf/helpers": "^6.1.4",
    "@turf/invariant": "^6.1.2",
    "@turf/length": "^6.0.2",
    "@turf/line-intersect": "^6.0.2",
    "@turf/meta": "^6.0.2",
    "@turf/nearest-point-on-line": "^6.0.2",
    "@types/mapbox-gl": "^1.8.0",
    "cordova-android": "8.1.0",
    "cordova-ios": "^5.1.1",
    "cordova-js": "^5.0.0",
    "cordova-plugin-advanced-http": "^2.4.1",
    "cordova-plugin-file": "^6.0.2",
    "cordova-plugin-geolocation": "^4.0.2",
    "cordova-plugin-ionic-webview": "^4.1.0",
    "cordova-plugin-vibration": "^3.1.1",
    "cordova.plugins.diagnostic": "^5.0.1",
    "core-js": "^2.6.11",
    "firebase": "^7.9.3",
    "geofirex": "^0.1.0",
    "geojson-rbush": "^3.1.2",
    "hammerjs": "^2.0.8",
    "lodash.debounce": "^4.0.8",
    "mapbox-gl": "^1.8.1",
    "moment": "^2.24.0",
    "node-sass": "^4.13.1",
    "rxjs": "^6.5.4",
    "tslib": "^1.11.1",
    "zone.js": "~0.9.1"

**Platform**: iOS and Android

**Steps to Trigger Behavior**
 1. Open app
 2. Use the app for a while before zooming out
 3. App crashes after zoom out and freezes at the intro screen

**Link to Demo Video**
https://drive.google.com/open?id=1cDxbdJoiNQg65d9G6UP2kbMIWUEFB1IW 

**Expected Behavior**
Ionic Android and iOS app should not crash while zooming out of the map

**Actual Behavior**
App crashes on iOS and Android devices after zooming out with no pattern

**Comment by StevieWag** [comment]
I also migrated the project to Ionic Capacitor, but the behaviour stays the same.

Additionally, I remove all my layers from the map without any success.

When debugging the app in XCode, I constantly get the following error on every movement I do on the map: "...[Process] kill() returned unexpected error 1"

Looks a little bit like a memory overflow which causes the app to kill.

**Comment by StevieWag** [comment]
In the browser I realized this warning. "Geometry exceeds allowed extent, reduce your vector tile buffer size".

Could it be related?

**Comment by sgolbabaei** [comment]
Thanks for using Mapbox, @StevieWag. Sorry to hear you're running into an issue. In order for us to diagnose this issue, we'll need to be able to reproduce it ourselves. Could you please create a minimal self-contained example on jsbin.com that demonstrates the issue?

**Comment by StevieWag** [comment]
Hey guys, sorry for opening the issue. I found the bug and it was related to the Ionic navigation. Since "swipeGesture" was enabled globally, the app navigated to the intro screen and has frozen there after swiping from left to right while using the map.

Using [swipeGesture]="false" on every router outlet and the side menu fixed it.

So hopefully this helps someone who runs into the same problem.
