### ISSUE TITLE
What are the available styles apart from "bright" and "outdoor"?

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#942]
Hello,

This is more of a question than an issue.In the examples, those JSON files are used for styles:
https://www.mapbox.com/mapbox-gl-styles/styles/outdoors-v6.json
https://www.mapbox.com/mapbox-gl-styles/styles/bright-v6.json

As well as a satellite one who only references the satellite layer from mapbox.

Are there some other styles available that could be used with mapbox-gl-js? It looks like only outdoors has a "night" style, is there a version of "bright" with a night style?

Also, how are the JSON styles created? By hand?

Thanks,
Fabien

**Comment by ljbade** [comment]
You can find all the current example styles at https://github.com/mapbox/mapbox-gl-styles/tree/mb-pages/styles which can also be used as a starting point for creating a custom style.

We are currently working on an editor for GL styles, keep an eye on the [blog](https://www.mapbox.com/blog/) for an announcement when we launch it.

@peterqliu: I assume you are familiar with "night" GL styles?

**Comment by jfirebaugh** [comment]
> It looks like only outdoors has a "night" style, is there a version of "bright" with a night style?

Nope, just outdoors at the moment.
