### ISSUE TITLE
NavigationControl does not have icons in Chrome and only part of then in Firefox

### ISSUE THREAD

**Issue by khashashin** [mapbox/mapbox-gl-js#9421]
In Chrome the NavigationControl does have any icon and in Firefox it renders only zoom in and zoom out icons

**mapbox-gl-js version**:
JavaScript: https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.js
CSS: https://api.mapbox.com/mapbox-gl-js/v1.8.1/mapbox-gl.css

**browser**:
Chrome 79
Firefox 73

![In Chrome](https://user-images.githubusercontent.com/17837758/76622233-632e4100-6531-11ea-8138-dfdf0f80befb.png)

In Chrome: The css of the rendered span element
```
.mapboxgl-ctrl button.mapboxgl-ctrl-zoom-in .mapboxgl-ctrl-icon {
    background-image: url(data:image/svg+xml;charset=utf-8,%3Csvg width='29' height='29' viewBox='0 0…1.5-.75 1.5-1.5S19.75 13 19 13h-3v-3c0-.75-.75-1.5-1.5-1.5z'/%3E%3C/svg%3E);
}
```

![In Firefox](https://user-images.githubusercontent.com/17837758/76622553-04b59280-6532-11ea-8b0d-df5153c64f74.png)

![image](https://user-images.githubusercontent.com/17837758/76622666-39294e80-6532-11ea-8002-1b7028e54e3c.png)

**Comment by sgolbabaei** [comment]
Thanks for using Mapbox, @khashashin . Sorry to hear you're running into an issue. 
Unfortunately I can't see this issue while testing locally in Chrome and Firefox.

![image](https://user-images.githubusercontent.com/32684731/76641135-53e9cc00-650e-11ea-9da4-939d8478f06a.png)

Could you please create a minimal self-contained example on jsbin.com that demonstrates the issue?

**Comment by asheemmamoowala** [comment]
@khashashin Thank you for reaching out and using Mapbox-GL-JS. As the team requested more information and we haven't heard back in over a month, I'm going to close this issue. If you want to reopen the issue, please:

Ensure you can reproduce the issue using the latest release.
* Check the console for relevant errors and warnings.
* Include a link to a minimal demonstration of your code. We recommend using https://jsbin.com.
* Include links to the specific section(s) of the documentation where you would have expected to find an answer to this question.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help. 

Thank you!
