### ISSUE TITLE
Style pencil-v6 shows rendering artifacts and missing elements

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#943]
Hello,

In issue #942 , i asked about the available styles apart from "bright-v6" and "outdoors-v6" and @ljbade redirected me to this part of the repo:
https://github.com/mapbox/mapbox-gl-styles/tree/mb-pages/styles

It has a few more styles that I have been experimenting with. The "pencil-v6" one looks pretty cool ! but there are some rendering artifacts, I believe because of the sprite dimension.
Here is a jsfiddle to show you the result:
http://jsfiddle.net/fnicollet/y0t6qgdn/ 

Another strange thing is that there seem to be a race condition of some kind, at least, it shows different results as you refresh the page. To test, open a private navigation window with the jsfiddle. It should show:
![image](https://cloud.githubusercontent.com/assets/1240481/5789685/da7851da-9e74-11e4-9f01-e36a44daefb1.png)

Rendering looks ok. Refresh the page. This is what you would get:
![image](https://cloud.githubusercontent.com/assets/1240481/5789689/f1c59e9c-9e74-11e4-9d30-6ff6936b5da4.png)

Refresh a third time and you will get the first result or the bugged one, it seems very random. Here is the sprite used by pencil-v6:
https://www.mapbox.com/mapbox-gl-styles/sprites/pencil.png
It is larger than the other ones because of the background. Maybe this hasn't been tested recently?

Also, if you zoom out, you will notice that the maritime borders are missing but maybe that's just wrong in the style definition?
![image](https://cloud.githubusercontent.com/assets/1240481/5789702/7448ebee-9e75-11e4-8c7f-ed539754850d.png)

If this issue should be submitted to https://github.com/mapbox/mapbox-gl-styles/, i would be happy to move (or duplicate) the issue but it looks like there are rendering issues in mapbox-gl-js as well

Fabien

**Comment by nickidlugash** [comment]
@fnicollet Thanks for ticketing. These are fixed in [`pencil-v7`](https://github.com/mapbox/mapbox-gl-styles/blob/v7/styles/pencil-v7.json)

Note that currently there is still a rendering issue with tiling: https://github.com/mapbox/mapbox-gl-js/issues/972

**Comment by fnicollet** [comment]
Thanks @nickidlugash , I just tried pencil-v7 and it works well :)

I can notice the bug #972 but only while zooming between zoom levels. When being at exactly a zoom level, there is no white border.

I found another rendering issue with pencil tho, I am going to open another ticket for it with details
