### ISSUE TITLE
How to retrieve "coordinates" from Feature geojson Source

### ISSUE THREAD

**Issue by amelielecoz** [mapbox/mapbox-gl-js#9432]
Hi, 
I made this fiddle to expose my problem : 
http://jsfiddle.net/amelielcz/31t20mbg/46/

I use exponential interpolation to draw circles on my map. The circles must reflect the real diameters specified in the source (in meters). 
I manage to do it bu my formula must also include the latitude, which obviously impact the radius calculation.

I do not manage to replace the hard coded latitude '44' with the latitude given in the Source. I tried to use ['get'] lookup method, with no success.
Anyone has an idea?

**Comment by ansis** [comment]
It's currently not possible to get the coordinates from within an expression. We've talked about this but there are some challenges in making it consistent (the coords are usually rounded, could be multiple for different geometry types, only part of the geometry is available within each tile).

Workaround:

You could add the latitude as a property in your geojson feature and then access it the way you access other properties, for example:

```js
    {
          'type': 'Feature',
          'properties': {
            'id': 3,
            'name': 'name3',
            'radius': 25,
            'latitude', 43.52670
          },
          'geometry': {
            'type': 'Point',
            'coordinates': [5.44839, 43.52670]
          }
    }
```

**Comment by arindam1993** [comment]
Hey @amelielecoz ! 

Looks like your need pretty much the same feature as https://github.com/mapbox/mapbox-gl-js/issues/8218

I'm closing this as a duplicate, can we continue further discussion there?
