### ISSUE TITLE
Why are all the dependencies bundled?

### ISSUE THREAD

**Issue by trygveaa** [mapbox/mapbox-gl-js#9447]
**mapbox-gl-js version**: v1.8.1/master

### Question

As far as I can see, all of the dependencies are bundled into the compiled file in dist. What is the reason for this?

This means that if you have a project that uses mapbox which also use some of the same dependencies as mapbox, those dependencies won't be shared, so the total size of the project will be unnecessarily big.

**Comment by mourner** [comment]
- We need to fully control how the bundle is generated to support a complicated worker instantiation scheme I won't go into detail here.
- Dependencies we use are very small compared to the size of the GL JS code itself, so bundling them doesn't have much overhead.
