### ISSUE TITLE
More detail in console messages caused by style issues

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#9448]
This screencap shows a current situation I'm dealing with:

![Screen Shot 2020-03-22 at 9 26 24 am](https://user-images.githubusercontent.com/678344/77237843-b2562f00-6c1f-11ea-9f60-4f69c9ce6659.png)

I'm loading a very large style file from a third party, and it has some issues. The trouble is that none of these error messages gives me any way at all to figure out what the issues are. I can see that:

- some URL somewhere is malformed
- there is some problem with a `light` property of something (is this an issue with my style file? I have no idea)
- some kind of JSON somewhere is malformed (I don't even know what file)
- somehow, something has caused an internal error affecting something called `_layerConfigs`

I suspect (without knowing very much) that issues 2 and 4 are probably flow-on issues caused by whatever the style problems are. Maybe mapbox-gl-js should be throwing a bigger error and refusing to continue processing?

Anyway, it would be really helpful if these kinds of errors would include:
- what file triggered the error
- the id of the layer/source/whatever 
- the specific object (url, etc) if possible

Currently the only diagnostic technique I can think of is to selectively add or remove bits from the style file to see if it loads or not.

**Comment by asheemmamoowala** [comment]
@stevage Have you tried using the style-specs [`gl-style-validate`](https://github.com/mapbox/mapbox-gl-js/blob/master/src/style-spec/README.md#gl-style-validate) method to validate the style outside of GL-JS? 

Im closing this as a duplicate to consolidate the discussion in https://github.com/mapbox/mapbox-gl-js/issues/9314
