### ISSUE TITLE
How to adjust the tilt angle on the phone

### ISSUE THREAD

**Issue by chenkai0520** [mapbox/mapbox-gl-js#9451]
i can not adjust the tilt angle on the phone

**Comment by ryanhamley** [comment]
This is a known issue. https://github.com/mapbox/mapbox-gl-js/issues/3405 We're working on a major refactoring of mobile gesture support right now that will address a number of long-standing issues such as this. We're hoping this will be available for our next release v1.10.0 but that's subject to change if needed.
