### ISSUE TITLE
How to get rendered label bounding boxes?

### ISSUE THREAD

**Issue by kymillev** [mapbox/mapbox-gl-js#9458]
### Question
I want to get the position of each rendered label for a rendered map, to later use to train a recognition model on. Basically, given a feature returned by map.queryRenderedFeatures, I want to get its collision bounding box. These boxes are visible when map.showCollisionBoxes = true and clearly used in the underlying logic to render text labels and do collision detection.

I have looked into the source code, but could not find an easy way to get the coordinates of these collision boxes.  I found this related [StackOverflow question](https://stackoverflow.com/questions/58737934/is-there-a-way-to-get-the-bounding-box-of-a-text-label-in-mapbox-gl-js), without any answers. Any help is greatly appreciated.

**Comment by ryanhamley** [comment]
>I want to get the position of each rendered label for a rendered map, to later use to train a recognition model on

Hi @kymillev thanks for using Mapbox. We were interested in why you want to train your model on collision box dimensions and how you may be caching the data. Typically, under [Section 3.2 of the Mapbox Terms of Service](https://www.mapbox.com/legal/tos/#[MAMA]), we have some caching limitations:
>You may cache Map Assets on end-user devices (e.g., laptops, smartphones, or tablets) for offline use for up to 30 days, but each device must populate its cache using direct requests to the Mapping APIs and content from a cache may only be consumed by a single end user. On mobile devices, you may only cache up to the limits set in the applicable Mapbox SDK (defined below), and you may not circumvent or change those limits.

It looks like you're with a university though. Is this for a research project? If so, our community team may be able to work with you so you can conduct your research. cc @mjdanielson

**Comment by kymillev** [comment]
Hello @ryanhamley , thank you for your quick response. I was unaware that this process would be against the ToS. Is it allowed to generate the maps and only use them for private use or does that also fall under the caching limit? 

This would indeed be used for my research project (I'm a PhD student), I'm now collecting maps with labeled text on them and looking at various different resources and datasets. The application/tool would not serve maps, but recognize text on given raster maps in order to georeference them. Mapbox looks to be a great tool to generate a custom map dataset in different styles and populate these with synthetic text. This dataset would then be used to train & validate the text recognition model. Any help or tools you can provide would be greatly appreciated.

**Comment by ryanhamley** [comment]
Hi @kymillev can you reach out to our Community team at community@mapbox.com with more information about your research? They can provide more information on the best way to utilize Mapbox in your research.

I'm going to close this ticket for now since this may not be actionable on our end. Thanks for using Mapbox and I hope we can help with your research! If you need more information from the maintenance team, you can reply here.
