### ISSUE TITLE
can anyone suggest i need to show somedata in popup, how to send somec extra data in geoJSON 

### ISSUE THREAD

**Issue by ashokch8** [mapbox/mapbox-gl-js#9460]
var geojson = {
      'type': 'FeatureCollection',
      'features': [
        {
          'type': 'Feature',
          'properties': {
            'message': 'Foo',
            'iconSize': [60, 60],

          },
          'geometry': {
            'type': 'Point',
            'coordinates': [-66.324462890625, -16.024695711685304]
          },'extradata': {
            'something' : "hi"
          }
        },
}

this is showing undefined if access 'something'

**Comment by ashokch8** [comment]
or how to add JSOn file as addsource and shows clusters and markers of it on map

**Comment by mourner** [comment]
You can only put extra data in feature `properties`. However, this is a place to report issues — a StackOverflow would be a better place to ask for help and for generic questions.
