### ISSUE TITLE
compose之后，mapbox地图不见

### ISSUE THREAD

**Issue by wuxiang1228** [mapbox/mapbox-gl-js#9464]
![}KYE4 BC0OZ5}@E5IQDIWKV](https://user-images.githubusercontent.com/40557858/77540758-a1871100-6ede-11ea-922d-c37a8d61c496.png)
![}WGOO1)3N9`}0EXF@_6SOW7](https://user-images.githubusercontent.com/40557858/77540764-a350d480-6ede-11ea-9662-9917bf30fdf8.png)
![H1RG~{HJ)Q{(HQNLDFYKM O](https://user-images.githubusercontent.com/40557858/77540768-a64bc500-6ede-11ea-9d8a-4e66bc5765cc.png)

**Comment by wuxiang1228** [comment]
compose之后，地图不见了，是图层压盖了么，一直解决不了，求大佬解答

**Comment by ryanhamley** [comment]
Hi, can you please fill out the issue completely including a minimal example of whatever issue you're facing? Screen shots are not enough for us to diagnose any issue. Also, unfortunately we do not have any Chinese speakers on the team. If you are able to explain in English, that would be helpful. I'm going to close this for now but feel free to provide more information and we'll try to help.

**Comment by wuxiang1228** [comment]
The applied mapbox officially loads 3D model examples and was used in my experiments. A polygon area was drawn in three, and then superimposed on the mapbox. After using the outline to increase the outer border of the light, the original mapbox part is gone, and the polygon can be loaded without the channel rendering.

**Comment by wuxiang1228** [comment]
The applied mapbox officially loads 3D model examples and was used in my experiments. A polygon area was drawn in three, and then superimposed on the mapbox. After using the outline to increase the outer border of the light, the original mapbox part is gone, and the polygon can be loaded without the channel rendering.

**Comment by ryanhamley** [comment]
If this is a bug, can you reproduce the problem with as little code as possible in [JSFiddle](http://jsfiddle.com/)? That will help us figure out what's going on.
