### ISSUE TITLE
How to set the projection of mapboxgl to Mercator

### ISSUE THREAD

**Issue by 359126613** [mapbox/mapbox-gl-js#9475]
Hello! Thanks for contributing.
Excuse me,How to set the projection of mapboxgl to Mercator?thanks

**Comment by stevage** [comment]
Mapbox-GL-JS always uses Web Mercator, EPSG:3857.

**Comment by 359126613** [comment]
> Mapbox-GL-JS always uses Web Mercator, EPSG:3857.

When I instantiate the map the coordinates are latitude and longitude
var map = new mapboxgl.Map({
container: 'map', // container id
style: 'mapbox://styles/mapbox/streets-v11', // stylesheet location
center: [-74.5, 40], // starting position [lng, lat]
zoom: 9 // starting zoom
});
