### ISSUE TITLE
Use mapbox-gl multiple maps to present a legend

### ISSUE THREAD

**Issue by HarelM** [mapbox/mapbox-gl-js#9476]
**mapbox-gl-js version**: 1.6.1

### Question
I've read the following issues:
https://github.com/mapbox/mapbox-gl-js/issues/7332
https://github.com/mapbox/mapbox-gl-js/issues/3960

I'm using mapbox-gl not just to present the map but also to present a legend.
This legend is dynamic by the content of the map, which is dynamic too (a user can switch between sources and layers to present a different map according to what he needs).

When opening the legend I encounter the above error which causes the main map to stop working.
This is a bad user experience.
These legend maps are not moving and do not need interaction, but they need to be dynamic.
I was wondering if there's a way to statically create images from a map to avoid using too many web-gl contexts - so that the legend is created dynamically but resources are kept low.

Not sure I managed to convey the message clearly.
I would like a utility method of some sort to create an image from a map with style and sources or something similar, does this exist?

**Comment by asheemmamoowala** [comment]
> I was wondering if there's a way to statically create images from a map to avoid using too many web-gl context

The `preserveDrawingBuffer` option to the Map [constructor](s://docs.mapbox.com/mapbox-gl-js/api/#map), can be used to export the map canvas as a png using `map.getCanvas().toDataURL()`, 

> avoid using too many web-gl contexts

Even with the suggestion above, you will want to re-use the same map instance for legends instead of creating a new one for each instance.
