### ISSUE TITLE
map.fitBounds(...) behaves differently in v 1.9.0

### ISSUE THREAD

**Issue by waissbluth** [mapbox/mapbox-gl-js#9477]
**mapbox-gl-js version**: 1.9.0

**browser**: Chrome 80.0

### Steps to Trigger Behavior
 1. Call `map.fitBounds(bbox, { padding: { top: 200, left: 0, right: 0, bottom: 0 })`

### Link to Demonstration
v 1.9.0: https://jsfiddle.net/Lozwbnq5/2/
v 1.8.1: https://jsfiddle.net/pd6o2Ljc/2/

### Expected Behavior
Both should behave the same; the behavior in v 1.8.1 seems more proper.

### Actual Behavior
In version 1.9.0, the bounds from the top seem to be double (400px).

I believe this issue was introduced in https://github.com/mapbox/mapbox-gl-js/pull/8638

**Comment by arindam1993** [comment]
Yep, I think I know where this is coming from!

**Comment by arindam1993** [comment]
Thanks for the detailed bugreport! fix has been merged and is going out in the `1.9.1` release.
