### ISSUE TITLE
Version published to npm doesn't match commits in this repository

### ISSUE THREAD

**Issue by watson** [mapbox/mapbox-gl-js#9478]
The last version that was published to npm (v1.9.0) doesn't appear to contain all the commits that it's supposed to.

E.g. the PR #9425 was merged into `master` before v1.9.0 was published, but if you download v1.9.0 from npm those changes are not included.

One way this could have happened was if the local directory wasn't in a clean state or wasn't checked out to master when v1.9.0 was published.

**Comment by ryanhamley** [comment]
Hi @watson #9425 was merged after we cut the release branch for 1.9.0, so it did not make it into the release. It will be part of 1.10.0 next month
