### ISSUE TITLE
mapboxgl GeolocateControl location is wrong. 

### ISSUE THREAD

**Issue by ThiyagarajanShivSankaran** [mapbox/mapbox-gl-js#9490]
**mapbox-gl-js version**:

**browser**: All

### Steps to Trigger Behavior

 1. Go to this https://docs.mapbox.com/mapbox-gl-js/example/locate-user/
 2. Click on location button.
 3. It's show wrong location on map

### Link to Demonstration

https://jsbin.com/

### Expected Behavior

It should zoom in to the correct location.

### Actual Behavior

It's more that 100 miles between the shown location and my exact location.

<img width="1230" alt="Screen Shot 2020-04-02 at 8 56 08 AM" src="https://user-images.githubusercontent.com/17313049/78207817-5cf00c80-74c0-11ea-8aa9-bac9f3a87aae.png">

**Comment by andrewharvey** [comment]
Based on my testing, the control is correctly showing the location returned by the location provider, so most likely this is not an issue in GL JS but rather a difference between your true location and the location returned by your location provider, which is outside of our control.

**Comment by andrewharvey** [comment]
Also you'll see the accuracy radius circle shown is quite large, which indicates that the location provider isn't so certain about your location. The fact that your true location is within this range means it's actually working as expected.

From a design perspective it might be worth turning off the small blue dot and only leaving on the radius circle for large inaccuracies, but that might make it even more unclear to the user. I think any change to the default behaviour should be well thought out and reasoned from a UX perspective.
