### ISSUE TITLE
Userlocation is not center inside showAccuracyCircle

### ISSUE THREAD

**Issue by ansarikhurshid786** [mapbox/mapbox-gl-js#9492]
In latest version i am facing issue. userlocation is not in center inside showAccuracyCircle. 
**mapbox-gl-js version**: 1.9.0

**browser**: chrome, safari

### Steps to Trigger Behavior
![Screen Shot 2020-04-02 at 11 12 08 AM](https://user-images.githubusercontent.com/20280498/78220631-ed374d00-74d2-11ea-9a1b-21108dff192e.png)
![Screen Shot 2020-04-02 at 11 12 56 AM](https://user-images.githubusercontent.com/20280498/78220637-ef99a700-74d2-11ea-9018-411d41ed70c6.png)
 1. When GeolocateControl is enable 

### Expected Behavior
Center userlocation inside showAccuracyCircle

### Actual Behavior
userlocation is topleft in showAccuracyCircle. 

See screenshot for your reference.

**Comment by mourner** [comment]
@ansarikhurshid786 can you show a minimal live test case? I don't see this problem on official examples like [this one](https://docs.mapbox.com/mapbox-gl-js/example/locate-user/), so perhaps it's something in your app CSS interfering with the markers?

**Comment by ansarikhurshid786** [comment]
yes right i have some css to fix another issue .

**Comment by ansarikhurshid786** [comment]
```
.mapboxgl-user-location-dot {
        background-color: transparent !important;
        box-shadow: 0 0 0px rgba(0, 0, 0, 0.25) !important;
        border-radius: 0px !important; 
    }
```


if comment above css then i face screenshot issue.
![Screen Shot 2020-04-02 at 11 39 11 AM](https://user-images.githubusercontent.com/20280498/78222633-9895d100-74d6-11ea-98ca-9431f93a068a.png)

**Comment by mourner** [comment]
So, closing as a CSS issue on your side.
