### ISSUE TITLE
Response from api.mapbox.com with 403 Error stored in shared browser cache

### ISSUE THREAD

**Issue by Akiyamka** [mapbox/mapbox-gl-js#9495]
First of all: I understand that this is not the most appropriate place for this bug, but I hope that I will be redirected to where it should be fixed. (I couldn't find a better place than this)

### Prerequests
Two sites (http://a.com and http://b.com) on different domains using the **same** mapbox style and token.

Token must have [url-restrictions](https://docs.mapbox.com/help/how-mapbox-works/access-tokens/#url-restrictions) = http://a.com

### Steps to Trigger Behavior
1. Open site http://b.com, clear cache, and reload page. See `403 Forbidden` on request to https://api.mapbox.com... (this is expected since this domain is not included in the allowed domains)

2. Open site http://a.com, and see `403 Forbidden (from disk cache)` on request to https://api.mapbox.com... (**this is a bug**, because domain a.com is allowed to use this token, but browser read cache from previous response addressed from b.com)

### Why is this happening
Some browses use [cross-site shared cache](https://sirdarckcat.blogspot.com/2019/03/http-cache-cross-site-leaks.html) by default. 

### Possible solution
Adding the `Cache-Control: private` header for responses with 403 error should solve this problem.

### Link to Demonstration
https://www.dropbox.com/s/yzb1fmykx6qldsa/Peek%202020-04-02%2014-39.gif?dl=0

**mapbox-gl-js version**: 1.5.0

**browser**:
Chromium Version 79.0.3945.130 (Developer Build) (64-bit) - reproduced
Google Chrome Version 80.0.3987.149 (Official Build) (64-bit) - reproduced
Firefox 74.0 (64-bit) - not reproduced

### Expected Behavior
API should work regardless of where the user was before

### Actual Behavior
API does not work if the user has previously visited a site with an invalid token

**Comment by asheemmamoowala** [comment]
@Akiyamka Thank you for reporting this issue. The best place to report this or similar issues would be to contact [Mapbox Support](https://support.mapbox.com/hc/en-us).

Closing this ticket here since it is not actionable.

**Comment by ErinQuinn** [comment]
👋 echoing @asheemmamoowala, thanks! 

We went ahead and created an internal report for the team that owns this service, so need to write to us on support about this particular issue @Akiyamka.

**Comment by jayenashar** [comment]
even with private cache, i am still having an issue.  if the user accesses the URL before the URL is added to the whitelist, it seems to be stuck in the cache for a really long time.  is it possible to have a shorter expiration for 403 errors?
