### ISSUE TITLE
Overzoom/overscaling not working for raster-layers

### ISSUE THREAD

**Issue by Suven** [mapbox/mapbox-gl-js#9505]
**mapbox-gl-js version**: v1.9.1

**browser**: Chrome 80

### Steps to Trigger Behavior

 1. Create a Map with minZoom-maxZoom set to 0-20
 2. Add a raster layer with maxzoom 10
 3. Zoom above 10

### Link to Demonstration

https://codepen.io/mensgis/pen/NWGKRaR?editable=true

### Expected Behavior
The raster-layer will still be drawn, with the overscaling-method defined in https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-raster-raster-resampling .
This is the documented behaviour from https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#raster-maxzoom 

> Maximum zoom level for which tiles are available, as in the TileJSON spec. Data from tiles at the maxzoom are used when displaying the map at higher zoom levels.

### Actual Behavior

The raster-tiles just disappear at higher zoom levels

**Comment by Suven** [comment]
My bad. 

For others, running into the same issue: if you set maxzoom on the layer, mapbox will only show the raster up to that zoom. If you want to overzoom instead, set the maxzoom on the source only. Not the layer.

**Comment by krisaoe** [comment]
@Suven Do your raster tiles overzoom when you set the maxzoom in their source?
Mine are still disappearing despite setting maxzoom to their respective tileMatrixSet numbers (wmts).

**Comment by krisaoe** [comment]
Actually, this was due to a typo on my end.
I had set maxZoom instead of maxzoom.
Overzoom is working as expected.
