### ISSUE TITLE
Lines with line-dasharray property are a bit blurry

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#951]
This is not extremely noticeable, but lines with line-dashes appear a bit blurry on non-retina, particularly at the points when the dashes are being stretched out:

![blurry-linedash](https://cloud.githubusercontent.com/assets/5607844/5884981/07349e0a-a333-11e4-9001-0055ccc74859.gif)

If there is a simple fix for this that would be great, but otherwise it's probably not a big deal.

/cc @ansis

**Comment by ansis** [comment]
They were twice as blurry as they needed to be. Fixed in https://github.com/mapbox/mapbox-gl-js/commit/35b42808922506a6039b8bfd3dc10098692c1268 and on native in https://github.com/mapbox/mapbox-gl-native/commit/8f620bed8a5c1cf350f820daa879dad2fe5c3f17
