### ISSUE TITLE
issue in showing complete route in Android

### ISSUE THREAD

**Issue by arunpandian22** [mapbox/mapbox-gl-js#9510]
### Steps to Trigger Behavior

 1. When giving the source and destination and start navigation using navigation view in android When It starts the navigation.it  does not show the complete route to the destination in the navigation  view

### Expected Behavior
* It should show the complete route to the destination for some locations. actually I checked with google maps for the same source and destination. It works

### Actual Behavior
*  Some times it doesn't show the complete route to the destination

**Comment by karimnaaji** [comment]
@arunpandian22 , just to confirm, did you have this issue using this library or the native version of it https://github.com/mapbox/mapbox-gl-native?

**Comment by asheemmamoowala** [comment]
@githubuser Thank you for using Mapbox-GL-JS and for reaching out. As the team requested more information and we haven't heard back in a month, I'm going to close this issue. If you want to reopen the issue, please:

Ensure you can reproduce the issue using the latest release.
* Check the console for relevant errors and warnings.
* Include a link to a minimal demonstration of your code. We recommend using https://jsbin.com.
* Include links to the specific section(s) of the documentation where you would have expected to find an answer to this question.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help. 

Thank you!
