### ISSUE TITLE
¿Is `MultiLineString` a valid filter expressión?

### ISSUE THREAD

**Issue by Rumpelstinsk** [mapbox/mapbox-gl-js#9523]
**mapbox-gl-js version**: 1.7.0

### Question
I have this filter in a layer:

`filter: ["==", "$type", "LineString"]`

This filter works as expected. However I want to filter multiple conditions, so I change it to:

`filter: ["any",  ["==", "$type", "LineString"],  ["==", "$type", "MultiLineString"]]`

That brokes the layer, and nothing is display. So, Is `MultiLineString` a valid expresion? How can I chain this two conditions?

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#==
https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#any

**Comment by ryanhamley** [comment]
You linked to documentation for the expressions `==` and `any` but the `$type` variable is only available with the older filter syntax, so technically what you've written is not an expression at all.

From the [filter docs](https://docs.mapbox.com/mapbox-gl-js/style-spec/other/):

>"$type": the feature type. This key may be used with the "==","!=", "in", and "!in" operators. **Possible values are "Point", "LineString", and "Polygon".**

So no, `MultiLineString` is not a valid value. The filter syntax is deprecated and we recommend using expressions if possible. You may have better luck making use of the [`geometry-type`](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#geometry-type) expression which can recognize `MultiLineString` features.
