### ISSUE TITLE
symbol-min-distance = 0 will break map

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#953]
Setting `"symbol-min-distance": 0` (which is the [specified min](https://github.com/mapbox/mapbox-gl-style-spec/blob/v7/reference/v6.json#L267)) makes the map kind of break, no errors, it just doesn't really work as soon as you zoom past very low z-levels. Setting it to 1 fixes this. Either there's a 0 case that needs to be handled or the min should be 1…?

**Comment by ansis** [comment]
The min should be 1

**Comment by lbud** [comment]
:+1: will fix in the spec
