### ISSUE TITLE
adding a custom marker in mapbox not working

### ISSUE THREAD

**Issue by sanadnajjar** [mapbox/mapbox-gl-js#9544]
so im trying to add a custom marker in mapbox using trail coordinates, and its not working. any help would be very much appreciated.

the error on console: (.setlnglat() seems to be the problem)

```
lng_lat.js:149 Uncaught Error: `LngLatLike` argument must be specified as a LngLat instance, an object {lng: <lng>, lat: <lat>}, an object {lon: <lng>, lat: <lat>}, or an array of [<lng>, <lat>]
    at Function.jl.convert (lng_lat.js:149)
    at o.setLngLat (marker.js:283)
    at trails:42617
    at Array.forEach (<anonymous>)
    at addMarkers (trails:42604)
    at r.<anonymous> (trails:42595)
    at r.Mt.fire (evented.js:119)
    at r._render (map.js:2210)
    at map.js:2317
```
my code is below:

```
    function addMarkers() {
        /* For each feature in the GeoJSON object above: */
        trails.features.forEach(function(marker) {
            /* Create a div element for the marker. */
            var el = document.createElement('div');
            /* Assign a unique `id` to the marker. */
            el.id = "marker-" + marker.properties.id;
            /* Assign the `marker` class to each marker for styling. */
            el.className = 'marker';

            /**
             * Create a marker using the div element
             * defined above and add it to the map.
             **/
            new mapboxgl.Marker(el, { offset: [0, -23] })
                .setLngLat(marker.geometry.coordinates) <--------------------
                .addTo(map);
    }
```

**Comment by andrewharvey** [comment]
This is most likely an issue on your side and not in GL JS, perhaps some of your features aren't point geometries? Best practice would be to check the Geometry type is Point.

**Comment by sanadnajjar** [comment]
Yeah thats true, i figured it out. The coordinates were in wrong format as i converted them from GPX to GeoJson.
Thank you though

**Comment by elgabato** [comment]
I think I have a similar issue, I don't understand when adding the markers to Mapbox :error will occurred says
 Cannot read properties of undefined (reading 'addTo') : 

see attachment, maybe some knows why this happened and it's fully working on my sandbox 
![image](https://user-images.githubusercontent.com/39982054/233335146-3d5c5a87-2515-475f-aa13-68a7fa2cad39.png)
