### ISSUE TITLE
Is there anyone know this style?

### ISSUE THREAD

**Issue by dythbj** [mapbox/mapbox-gl-js#9545]
### Question
This style used to be one of the [Gallerys](https://www.mapbox.com/gallery/), but i cann't find it anymore, is there anyone know the link of the style like blow?
![WechatIMG88](https://user-images.githubusercontent.com/41282663/79100385-ef35c180-7d98-11ea-8f56-1342bbbe18ef.png)

Thanks!!!

**Comment by karimnaaji** [comment]
Note that this is a place to report issues with the library. 
For questions about styling availability like this one, it's usually best to contact support@mapbox.com!
