### ISSUE TITLE
Support newlines in symbol text fields

### ISSUE THREAD

**Issue by ajashton** [mapbox/mapbox-gl-js#955]
If a text field in a vector tile contains a newline character, it is ignored for rendering. For most geodata this would be uncommon, but I think GL should handle this like Mapnik and render the appropriate line breaks.

![screenshot from 2015-01-26 17 17 24](https://cloud.githubusercontent.com/assets/126952/5909535/7380809e-a57f-11e4-8574-55c5ce26f601.png)

**Comment by danpat** [comment]
This feature would be nice, I'd like to be able to add a `text-field` with something like this:

`"text-field": "{speed} km/h ➜\n{duration} sec"`
