### ISSUE TITLE
Mapbox Streets v8 returns undefined for feature id on events for road layers. Is this intended?

### ISSUE THREAD

**Issue by mihaipanait** [mapbox/mapbox-gl-js#9567]
**mapbox-gl-js version**: 1.9.1

### Question
Compared with Mapbox Streets v7, Mapbox Streets v8 returns undefined for feature id on events for road layers. Is this intended?

I have seen in the documentation that Mapbox performs some optimization on vector layers, like joining road segments, but i would expect the id to be either 0 or a random id from the joined segments, not undefined. In v7 i get the feature id correctly on hover or other interactions on the event.features array.

v8
![v8](https://user-images.githubusercontent.com/3032687/79310156-22489400-7f04-11ea-8d80-aabbe6e38756.png)

v7
![v7](https://user-images.githubusercontent.com/3032687/79310355-78b5d280-7f04-11ea-8c5b-448d1bfa5601.png)

### Links to related documentation
https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/#ids

**Comment by mihaipanait** [comment]
Maybe it is worth mentioning that i'm using mapbox in react with react-map-gl.

**Comment by mihaipanait** [comment]
Apparently it is an issue related to the style am using rather than to the Streets API version. 
If i use style: 'mapbox://styles/mapbox/light-v10', it returns the correct id. The id is undefined only when i use my custom map style. Probably i'm missing something in the way i define my style.
I'll close the issue since it is not related to Streets api.

**Comment by mihaipanait** [comment]
I can't figure out what is wrong. I've put together an example without react.
https://jsfiddle.net/jzcf8m56/22/

pay attention to the feature id on hover:
![no-feature-id-v10-vs-v11-style](https://user-images.githubusercontent.com/3032687/79391469-4b0b7080-7f7a-11ea-8ac8-2dd01584ad93.gif)

**Comment by mihaipanait** [comment]
what is even more strange is that on mapbox docs page works correctly and when you click the link to edit in jsFiddle the example doesn't show the id anymore.

docs page:
![2020-04-16 00_56_22-Get features under the mouse pointer _ Mapbox GL JS _ Mapbox](https://user-images.githubusercontent.com/3032687/79393292-b73ba380-7f7d-11ea-8584-0c624e296244.png)

jsFiddle:
![2020-04-16 00_58_17-](https://user-images.githubusercontent.com/3032687/79393336-cd496400-7f7d-11ea-9e4c-caac0d79d137.png)

could it be related somehow to the access token being used?

**Comment by mihaipanait** [comment]
Apparently there are tiles that do have a feature id (using streets-v11). You can see the tile limit if you look at the buildings layer:
![no-feature-id-v11-tile-issue-2](https://user-images.githubusercontent.com/3032687/79398365-397d9500-7f89-11ea-9689-5c3c6970a98e.gif)

![no-feature-id-v11-tile-issue](https://user-images.githubusercontent.com/3032687/79398450-6df15100-7f89-11ea-9b4f-65edde33a270.gif)

maybe the tile data is truncated for whatever reason.

**Comment by mihaipanait** [comment]
Besides the fact that some tiles have the feature id and some don't, it seems that it is also dependent on the zoom level. If you zoom too much or too little the feature id is undefined again:
![no-feature-id-v11-tile-issue-zoom](https://user-images.githubusercontent.com/3032687/79399192-616df800-7f8b-11ea-9405-970fc8e10859.gif)

**Comment by asheemmamoowala** [comment]
@mihaipanait Thank you for the detailed report and for using Mapbox. This issue tracker is for reporting bugs and feature requests for the mapbox-gl-js library. Since the issue reported here is related to the Streets v8 Vector tiles, it is not relevant to this project.
For future issues or questions like this, please refer to our [help documentation](https://www.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). 

The [documentation](https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/#ids) of streets v8 vector tiles, says this about IDs:
> Often, multiple objects from the same or multiple proprietary sources are combined into a single object in our vector tiles. For example, water polygons are unioned to avoid seams, and road lines are joined to save space. In these cases the ID is either 0 or one of the input IDs chosen at random.
