### ISSUE TITLE
Render suite times out on retina-raster default test

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#958]
Some recent builds seem to time out when running the render test suite at some point: https://travis-ci.org/mapbox/mapbox-gl-js/builds/48578759 cc @jfirebaugh

**Comment by mourner** [comment]
@edenh it started consistently freezing on `retina-raster default` test after your https://github.com/mapbox/mapbox-gl-js/commit/0d0019e37f4b2762a0cf72ab3d22805491d4bd7b and https://github.com/mapbox/mapbox-gl-js/commit/15a5b24026365451f91649af62e0aaa4471c1e60 commits. Can you take a quick look?

**Comment by mourner** [comment]
Previous commits completely broke GL JS because TileCoord required the browser module which depended on having `window` present, and since TileCoord is used in the worker too, it throwed an error and didn't do anything.

**Comment by mourner** [comment]
Nah, Mapbox GL JS works, but the Travis build still errors.

**Comment by jfirebaugh** [comment]
Fixed by #959.
