### ISSUE TITLE
this bug amazing me!

### ISSUE THREAD

**Issue by lijingyu1538** [mapbox/mapbox-gl-js#9585]
![image](https://user-images.githubusercontent.com/38616073/79571320-97c38880-80ed-11ea-8fbd-54c0b4ac942b.png)
![image](https://user-images.githubusercontent.com/38616073/79571381-af9b0c80-80ed-11ea-9530-e9f71f8dc1d6.png)
I  don't know what happened , who can tell me!!

**Comment by andrewharvey** [comment]
There's a ticket for this at #2434, so I'll close this in favour of that existing ticket.
