### ISSUE TITLE
Creating a mapbox gl wrapper for the neo.mjs framework

### ISSUE THREAD

**Issue by tobiu** [mapbox/mapbox-gl-js#9598]
Hello everyone,

I am the main author of the webworkers driven UI framework neo.mjs and already started to create a wrapper layer to make it easier for devs to use your maps inside a neo app. The framework and all demo apps are MIT licensed.

https://github.com/neomjs/neo

The framework was released to the public on November 23rd, 2019 and is slowly gaining traction:
![7000](https://user-images.githubusercontent.com/1177434/79637483-5334fd00-8180-11ea-817f-4e1f6e5dc986.png)

Since this project should generate new customers on your end, it would be nice to get a bit of your support.

## So, what is special about neo.mjs?
There are 3 major design goals:
1. Most parts of the framework and the apps you build with it run inside a worker
2. Use ES8+ directly inside the browser, especially in web workers as well (dev mode)
3. At least for the dev mode (until other browsers catch up to Chrome), no JS builds or transpilations

In case you look close at the right side of this screenshot (inside the App worker):
![Screenshot 2020-04-18 at 14 34 27](https://user-images.githubusercontent.com/1177434/79637714-f1759280-8181-11ea-8ef0-cdc252399ca3.png)

It would make total sense and would be super nice to include mapbox gl as a npm package, but this is not possible at this point, since the import statements on your end do not follow the ES6+ specs. The file extensions are missing, so a browser can not use them.

Example: index.js
```
// @flow

import assert from 'assert';
import supported from '@mapbox/mapbox-gl-supported';
```

We can open a separate ticket for this one, it can only work in case your dependencies use correct import statements as well (which is not yet the point for most npm packages).

What I did so far is:

1. main thread: https://github.com/neomjs/neo/blob/dev/src/main/lib/MapboxGL.mjs
The main thread is loading your library in case the global framework config "useMapboxGL" is set to true. We need to create remote methods which will get exposed to the App worker here (since we do want to define maps inside the App worker).
2. extending Neo.component.Base: https://github.com/neomjs/neo/blob/dev/src/component/wrapper/MapboxGL.mjs
this one already supports some of your API methods and will create map instances based on the internal specs once components get mounted into the dom.
3. for a framework demo app (covid dashboard), i created a real life map here: https://github.com/neomjs/neo/blob/dev/apps/covid/view/mapboxGl/Component.mjs

the map styles are strongly(!) inspired by https://blog.mapbox.com/visualizing-the-progression-of-the-2019-ncov-outbreak-66763eb59e79, which is added in the attribution section of the demo app itself.

You can take a look at the current version here (desktop only, in progress => non final):

> dist/production: 
https://neomjs.github.io/pages/node_modules/neo.mjs/dist/production/apps/covid/index.html#mainview=mapboxglmap

> dev mode (this is the impressive one using ES8 directly without builds, Chrome 80 only)
https://neomjs.github.io/pages/node_modules/neo.mjs/apps/covid/index.html#mainview=mapboxglmap

In case you like this project, you are definitely welcome to help out. I will open new tickets / issues here to provide feedback on some of the downsides i ran into (and some ideas on how to fix them).

Demo video: https://www.youtube.com/watch?v=7dnVUchs6VU

Best regards & feedback appreciated, Tobias

**Comment by asheemmamoowala** [comment]
@tobiu  Congratulations on the traction you are seeing with Neo.mjs and thank you for sharing your project and the implementation of Mapbox-GL with us.

**Comment by mourner** [comment]
@tobiu this is cool, thanks for sharing! 

Regarding ES imports — the source code is not meant to be directly imported in downstream projects since it contains flow types, dependencies, etc., but there is an existing 
ticket about exposing a ESM bundle (in addition to the UMD one we currently have) #8676 — let's track the progress there.
