### ISSUE TITLE
Using local webserver with Brave browser throws ajax error, prevents map rendering

### ISSUE THREAD

**Issue by will-r-chase** [mapbox/mapbox-gl-js#9599]
Very strange issue I found when using a local web server with Brave browser. It seems that trying to open any mapbox map in Brave when using a local web server causes an ajax error that prevents rendering (I assume it's unable to fetch map tiles). The interaction only happens with a local web server, opening the HTML document in Brave works fine. Also, the interaction is specific to Brave--opening the local web server in Chrome or Safari works fine. The ajax error is: ```evented.js:140 Error: Could not load image because of out of range source coordinates for image copy. Please make sure to use a supported image type such as PNG or JPEG. Note that SVGs are not supported.
at ajax.js:280```

**mapbox-gl-js version**: 1.9.1

**browser**: Brave

### Steps to Trigger Behavior

 1. Create a minimal map example like at https://docs.mapbox.com/mapbox-gl-js/overview/
 2. Within VSCode, start a local web server using LiveServer plugin
 3. Open the local web server in Brave browser

### Link to Demonstration

Sorry, since this is browser and server specific, I can just give my minimal map code, and ask that you follow the steps above, opening with LiverServer in Brave browser. 
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <script src="https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.js"></script>
    <link
      href="https://api.mapbox.com/mapbox-gl-js/v1.9.1/mapbox-gl.css"
      rel="stylesheet"
    />
  </head>
  <body>
    <div id="map" style="width: 400px; height: 300px;"></div>
    <script>
      mapboxgl.accessToken =
        'pk.eyJ1Ijoid2NoYXNlMTQiLCJhIjoiY2p2dnYwOXBvMGJvNDQzcDkxcTZqNWd3dCJ9.UqxE9xtZJevAQem-lKCYnA';
      var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/mapbox/streets-v9',
      });
    </script>
  </body>
</html>
```

### Expected Behavior
Renders a minimal map

### Actual Behavior
Throws the error: ```evented.js:140 Error: Could not load image because of out of range source coordinates for image copy. Please make sure to use a supported image type such as PNG or JPEG. Note that SVGs are not supported.
    at ajax.js:280```

**Comment by andrewharvey** [comment]
This looks to be the same issue as #8377, in short I don't think Brave should be considered a supported browser due to restrictions on the Brave side.

If you try to check for support https://docs.mapbox.com/mapbox-gl-js/example/check-for-support/ it should indicate that the browser is not supported.

**Comment by asheemmamoowala** [comment]
As mentioned above, this is likely an unsupported browser. Please use the latest version of the [gl-js-supported](https://github.com/mapbox/mapbox-gl-supported/releases/tag/v1.5.0) module to verify that a device/browser is supported.
