### ISSUE TITLE
Integer zoom snapping option for raster maps

### ISSUE THREAD

**Issue by edenh** [mapbox/mapbox-gl-js#960]
Scaled raster tiles don't look great. Should we introduce an option to "snap" to integer zoom levels?

**Comment by jfirebaugh** [comment]
It should be possible to get much better looking results without requiring integer zoom level snapping. Let's try out a combination of #839 and/or better scaling algorithms first.

**Comment by mourner** [comment]
Yeah, snapping to integer zoom won't be a great experience either...

**Comment by jfirebaugh** [comment]
⇢ #1030

**Comment by quinncnl** [comment]
#1591
