### ISSUE TITLE
Third party tiles vector tiles aren't showing

### ISSUE THREAD

**Issue by shobishani** [mapbox/mapbox-gl-js#9601]
**mapbox-gl-js version**:v1.9.1

Third party tiles layer isn't showing on map i'm able to view it using TileServer-GL but when I add that to mapbox-gl-js it's not visible and there's no error as well. I've checked with devtools and Tileserver-GL does gives 200 with some encoded response. I've generated those tiles using tippecanoe.
[https://github.com/mapbox/tippecanoe](url).
`map.on('load', function () {
    map.addSource('small', {
        'type': 'vector',
        'tiles': [
            'http://localhost:8080/data/countries-z3/{z}/{x}/{y}.pbf',
        ],
    });
    map.addLayer({
        'id': 'small',
        'type': 'fill',
        'source': 'small',
        'source-layer': 'small-sequences',
        'layout': {},
        'paint': {
            'fill-color': '#088',
            'fill-opacity': 0.8
        }
    });
});`

Image of inspect view of TileServer-GL for the imported/served tiles.
https://i.stack.imgur.com/FLW6q.png

**Comment by asheemmamoowala** [comment]
@shobishani Thank you for your opening this ticket. To help the maintainers and community understand and address the problem accurately can you please provide a minimal, complete, verifiable demonstration of the issue. We recommend using https://jsbin.com. Please include information about the browser version and operating system used.

**Comment by dioslibre** [comment]
Hey @shobishani, did you find a solution? 
tiles are fetched correctly by mapbox-gl with a 200 response, plus they work fine on openlayers.

**Comment by shobishani** [comment]
I'm not serving those tiles now I'm uploading it to Mapbox api using s3
bucket and I've created custome layer for that. So this worked out for me.
You may close the issue it must be something wrong the way i was doing.

**Comment by dioslibre** [comment]
I was not specifying the correct source-layer. I corrected it. it's working fine now. Thanks for the reply.

**Comment by shobishani** [comment]
Can you please share your code snippet

**Comment by dioslibre** [comment]
I'm using PostGIS to generate the vector tiles, and an express server to serve them. The SQL is:

`async (req, res) => {
  const { z, x, y } = req.params;
  // console.log({ z, x, y });
  const m = 20037508.34;
  const r = (m * 2) / 2 ** z;
  // Query the database, using ST_AsMVTGeom() to clip the geometries
  // Wrap the whole query with ST_AsMVT(), which will create a protocol buffer
  const SQL = `
    SELECT ST_AsMVT(q, 'Geometries', 4096, 'geom', 'id')
    FROM (
      SELECT
          id,
          ST_AsMVTGeom(
              geom,
              ST_MakeEnvelope(
                ${-m + x * r},
                ${m - y * r},
                ${-m + x * r + r},
                ${m - y * r - r},
                3857),
              4096,
              256,
              true
          ) geom
      FROM "Geometries" c
    ) q
  `;

  try {
    const tile = await sequelize.query(SQL);

    // set the response header content type
    res.setHeader("Content-Type", "application/x-protobuf");

    // trigger catch if the vector tile has no data, (return a 204)
    if (tile[0][0].st_asmvt.length === 0) {
      res.status(204);
    }

    // send the tile!
    res.send(tile[0][0].st_asmvt);
  } catch (e) {
    console.log(e);
    res.status(404).send({
      error: e.toString(),
    });
  }
};`

The important part is `ST_AsMVT(q, 'Geometries', 4096, 'geom', 'id')`, 'q' is the result of the second select clause, 'Geometries' in my case, is the *source-layer*. So, the working client code for me is:

`const map = new mapboxgl.Map({
      container: "editor",
      zoom: 10,
      style: {
        version: 8,
        sources: {
          "google-maps": {
            type: "raster",
            tiles: ["https://mt3.google.com/vt/lyrs=m&x={x}&y={y}&z={z}"],
            tileSize: 256,
          },
          casablanca: {
            type: "vector",
            tiles: ["http://localhost:8000/tile/{z}/{x}/{y}"],
            tileSize: 512,
          },
        },
        layers: [
          {
            id: "google-layer",
            type: "raster",
            source: "google-maps",
            minzoom: 0,
            maxzoom: 24,
          },
          {
            id: "casablanca-fill",
            type: "fill",
            minzoom: 10,
            maxzoom: 24,
            source: "casablanca",
            "source-layer": "Geometries",
            paint: {
              "fill-color": "#627BC1",
              "fill-opacity": [
                "case",
                ["boolean", ["feature-state", "hover"], false],
                1,
                0.5,
              ],
            },
          },
          {
            id: "casablanca-line",
            type: "line",
            minzoom: 10,
            maxzoom: 24,
            source: "casablanca",
            "source-layer": "Geometries",
            paint: {
              // "fill-color": "rgba(53,175,109, .87)",
              // "fill-outline-color": "rgba(255,255,255, 1)",
              "line-color": "#627BC1",
              "line-width": 2,
            },
          },
        ],
      },
      center: [-7.5, 33.5],
    });`

Hope this helps.

**Comment by dioslibre** [comment]
Sorry the formatting is messed up.

**Comment by henriktorget** [comment]
Source-layer is case sensitive 🤦 

This helped me double check:
> The important part is `ST_AsMVT(q, 'Geometries', 4096, 'geom', 'id')`, 'q' is the result of the second select clause, 'Geometries' in my case, is the _source-layer_. So, the working client code for me is:

Thank you!
