### ISSUE TITLE
Filter - group by specific feature property

### ISSUE THREAD

**Issue by fc** [mapbox/mapbox-gl-js#9606]
## Motivation

If a map tileset contains multiple overlapping features, there is not an easy way to show only one of those layers.

For example, an airspace region has 3 identical "No Fly Zone" polygons but each polygon has a different date range.  On the map we want to only see one of those polygons but if a user clicked on it, they would be able to see details associated with each one.

If a feature could have a 'groupBy' field then when it filtered, we could group by a specific property and only show that one layer.  Maybe we could even get a count of the grouped polygons.

**Comment by andrewharvey** [comment]
Sounds like this might be able to be done client side with feature states and setting the opacity based on the feature state.

**Comment by fc** [comment]
@andrewharvey I just read up more on that, that seems like a helpful route of exploration! thank you.

Were you think of something like this?
- listen in the on map load or map move events
- then, call `queryRenderedFeatures` that are in the 'no fly zone' layer
- then, if there are more than one, set the feature state of the excess features to have an opacity of zero.

Or was there a different direction you were thinking of?
Do you think this would lead to any flickering of the features on the screen?

**Comment by andrewharvey** [comment]
Yeah something along those lines, I haven't through through it too much, so you could try it and see how it does.

To avoid flicker (if there is any) you could start with features being not visible per the style and then only turn on the ones once you've done your test and set feature states.
