### ISSUE TITLE
Mapbox does not show all buildings on zoom level smaller than 15

### ISSUE THREAD

**Issue by dmitrykinakh** [mapbox/mapbox-gl-js#9608]
Hello there,

I'm using Mapbox studio for creating a custom style for an app I'm building. However,
I've faced that if I'll change on which zoom level 3d buildings should appear (I've set to 11) I see 
the following behavior:
z11 - no buildings
![image](https://user-images.githubusercontent.com/8025637/79834419-b6f43b80-83b5-11ea-8e1f-25ecb4f0211e.png)
z12 - no buildings
![image](https://user-images.githubusercontent.com/8025637/79834453-c5daee00-83b5-11ea-8314-23f6209e19d6.png)
z13 - 3 buildings
![image](https://user-images.githubusercontent.com/8025637/79834498-d9865480-83b5-11ea-8655-be04c5661d01.png)
z14 - ~20 buildings
![image](https://user-images.githubusercontent.com/8025637/79834530-e60aad00-83b5-11ea-82b9-ea9f3afdb712.png)
z15 - all (thousands)
![image](https://user-images.githubusercontent.com/8025637/79834562-f4f15f80-83b5-11ea-8708-c51447a70a93.png)

I understand that displaying them all buildings on zoom level 11 might looks badly but would like to understand the logic by which those buildings starts appearing on different zoom levels.

**Comment by stevage** [comment]
The documentation for Mapbox Streets is here: https://docs.mapbox.com/vector-tiles/reference/mapbox-streets-v8/

It explains which data is available at each zoom level.

**Comment by dmitrykinakh** [comment]
thanks a lot @stevage

**Comment by hhyein** [comment]
How did you solve this problem?

**Comment by dmitrykinakh** [comment]
I've just accepted this as is.
