### ISSUE TITLE
Add "*-halo-opacity" properties

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#961]
For when I'd like hollow text outlines, especially over imagery: text-opacity: 0, halo-opacity:1

![screen shot 2015-01-28 at 11 19 43 am](https://cloud.githubusercontent.com/assets/4551508/5945547/1608eea4-a6e4-11e4-9980-002d3c0ea292.png)

cc/ @kkaefer @ansis

**Comment by peterqliu** [comment]
A (crazy) alternative here is using image fills for the text itself, that matches the terrain imagery underneath

**Comment by kkaefer** [comment]
Nah, making outlines from the text is fairly straightforward in shader code.

**Comment by ansis** [comment]
@peterqliu want to implement this when you have time?

After adding it to the spec you need to use instead of `-opacity` here: https://github.com/mapbox/mapbox-gl-js/blob/c4efd8c177be3bf7156eeb88322af395d0848219/js/style/style_layer.js#L182-L185

**Comment by peterqliu** [comment]
ooh i'll take a stab. added to my punchlist

**Comment by lucaswoj** [comment]
Hollow type face is a good workaround. We still want to add this feature! 😄

**Comment by jfirebaugh** [comment]
Can't you already do this with `"text-color: "rgba(0, 0, 0, 0)", "text-halo-color": whatever`?

**Comment by kkaefer** [comment]
No, because the halos won't have a cutout for the fill.

**Comment by jfirebaugh** [comment]
Ok, so this isn't as simple as adding a property. It would require custom behavior in the shader. I'm inclined to close -- using a hollow typeface is a good solution.
