### ISSUE TITLE
moveend event not fired when map moves from calling setMinZoom or setMaxZoom

### ISSUE THREAD

**Issue by nreese** [mapbox/mapbox-gl-js#9610]
Calling setMinZoom and setMaxZoom causes the map to zoom if the current view is outside the new  range. The problem is that `moveend` is not fired when the map finishes moving.

**Comment by sgolbabaei** [comment]
Thank you @nreese for using Mapbox. To help the maintainers and community understand and address the problem accurately can you please provide a minimal, complete, verifiable demonstration of the issue. We recommend using https://jsbin.com. Please include information about the browser version and operating system used.

**Comment by nreese** [comment]
Is there a reason why this has been closed? Has this been fixed?

**Comment by mourner** [comment]
@nreese this has been closed because we asked for a minimal, reproducible live test case, both in the issue template and in a comment afterwards, and haven't heard back in more than a month.
