### ISSUE TITLE
decide on TapDragZoom direction before release

### ISSUE THREAD

**Issue by ansis** [mapbox/mapbox-gl-js#9612]
We need to figure out with dragging down zooms in our out for the one-finger tap-drag-zoom gesture.

> I just tested the new gestures and they feel great!
One thing that didn't feel right though was the TapDragZoom that I feel it should be inverted so that drag down zooms in instead of out. That's what users using the gesture on gmaps is used to and it's also how it works if you're using the two-finger scroll gesture on a touchpad. Did you discuss this internally?

Thanks for catching this so that we can be more conscious about this.

In Google maps dragging down zooms in.
In Apple maps dragging down zooms out.

In desktop browsers on a macbook scrolling down zooms in by default (but flipping scroll settings can change this). I'm not sure about other browsers.

cc @Neorth @bradjonesca

**Comment by mvl22** [comment]
Interestingly, looks like Google used to do it the other way round, as of c. 19th September 2012 when it was introduced:
https://youtu.be/4ntvK2RuxBk

However, I notice that shows an Android phone. I don’t know if Gmaps on Apple was the same.

(This was amazingly the same day that Apple Maps launched:
https://en.m.wikipedia.org/wiki/Apple_Maps )

Looks like Apple didn’t copy the feature until 2017:

https://www.macobserver.com/tips/quick-tip/how-to-use-one-handed-zoom-in-ios-11s-maps/

Personally I prefer the Google direction of down to zoom in.

I would go with whichever app is more popular (Google Maps presumably, even on iOS, and they seem to have got there first anyway) but add a setting to allow it to be reversed by the developer if really wanted.

**Comment by chloekraw** [comment]
On our mobile SDKs, dragging down zooms in. I think we should be internally consistent when it comes to the native mobile experience and mobile web.

Allowing the developer to reverse it makes sense, but I’d prefer to add it later if it becomes a popular request in the future.
