### ISSUE TITLE
Add jsdoc/check-examples to eslintrc

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mapbox-gl-js#9616]
## Motivation

While reviewing https://github.com/mapbox/mapbox-gl-js/pull/9607 I noticed some inconsistencies with inline code examples that could be caught by enabling `jsdoc/check-examples` in `.eslintrc`.

What can check-examples help with?

- Catching syntax errors
- Fixing and warning about inconsistent indentation
- Enforcing code conventions 

### Implementation

In `.eslintrc`, add under `rules`:

```js
"jsdoc/check-examples": ["warn",  {
  "checkEslintrc": false,
  "baseConfig": {
    "rules": {
// we may need to override some rules in the base config, for example using var instead of let/const
    }
  }
}]
```

- We may need to update jsdoc to take advantage of some newer options that would allow us to override the base config.
- Documentation: https://www.npmjs.com/package/eslint-plugin-jsdoc#eslint-plugin-jsdoc-rules-check-examples

cc @danswick

**Comment by HeyStenson** [comment]
@ansis added `jsdoc/check-examples` in https://github.com/mapbox/mapbox-gl-js/pull/10847, and these changes will launch once https://github.com/mapbox/mapbox-gl-js/pull/10707 is ready to go. ✨
