### ISSUE TITLE
After changing source-data using source.setData, querySourceFeatures doesn't contain new source-data

### ISSUE THREAD

**Issue by skarnl** [mapbox/mapbox-gl-js#9619]
I'm using mapbox to draw markers and clusters, and I'm using `querySourceFeatures` for that, since I need the clustering part and I want to draw HTML-markers.

I based my implementation on the blogpost by Mapbox (https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/)
But after I update my source using `setData` the features I get from `querySourceFeatures` aren't updated, so I don't see my new data displayed on the map. 

Here is my code, a bit simplified:

```
      //initial I do:
      map.addSource('earthquakes', {
            'type': 'geojson',
            'data': {
                "type": "FeatureCollection",
                "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                "features": [
                        { "type": "Feature", "properties": { "id": "ak16994521", "mag": 2.3, "time": 1507425650893, "felt": null, "tsunami": 0 }, "geometry": { "type": "Point", "coordinates": [ -151.5129, 63.1016, 0.0 ] } },
                        { "type": "Feature", "properties": { "id": "ak16994519", "mag": 1.7, "time": 1507425289659, "felt": null, "tsunami": 0 }, "geometry": { "type": "Point", "coordinates": [ -150.4048, 63.1224, 105.5 ] } },
                ]
            },
            'cluster': true,
            'clusterRadius': 80,
        });

        // circle and symbol layers for rendering individual earthquakes (unclustered points)
        map.addLayer({
            'id': 'earthquake_circle',
            'type': 'circle',
            'source': 'earthquakes',            
        });

        //draw the markers using the updateMarkers function below:
       function updateMarkers() {
            var newMarkers = {};
            var features = map.querySourceFeatures('earthquakes');
            
            // for every cluster on the screen, create an HTML marker for it (if we didn't yet),
            // and add it to the map if it's not there already
            for (var i = 0; i < features.length; i++) {
                var coords = features[i].geometry.coordinates;
                var props = features[i].properties;
                var id = props.cluster_id;
                     
                // draw the HTML-marker on screen etc
      }
```

And after a while (`setInterval`) I do this:

```
   map.getSource('earthquakes').setData({
            'type': 'geojson',
            'data': {
                "type": "FeatureCollection",
                "crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
                "features": [
                     { "type": "Feature", "properties": { "id": "ak16994521", "mag": 2.3, "time": 1507425650893, "felt": null, "tsunami": 0 }, "geometry": { "type": "Point", "coordinates": [ -151.5129, 63.1016, 0.0 ] } },
                     { "type": "Feature", "properties": { "id": "ak16994519", "mag": 1.7, "time": 1507425289659, "felt": null, "tsunami": 0 }, "geometry": { "type": "Point", "coordinates": [ -150.4048, 63.1224, 105.5 ] } },
                     { "type": "Feature", "properties": { "id": "ak16994517", "mag": 1.6, "time": 1507424832518, "felt": null, "tsunami": 0 }, "geometry": { "type": "Point", "coordinates": [ -151.3597, 63.0781, 0.0 ] } },
                     { "type": "Feature", "properties": { "id": "ci38021336", "mag": 1.42, "time": 1507423898710, "felt": null, "tsunami": 0 }, "geometry": { "type": "Point", "coordinates": [ -118.497, 34.299667, 7.64 ] } },
                ]
            },
            'cluster': true,
            'clusterRadius': 80,
      });
```

But when I then check the output from the `querySourceFeatures` it still has the same amount of features ... the changes / added features aren't drawn on the layer.

Even when I check after some time it's still not updated or anything.

The only way I got the layer to update was doing this before creating a new source and layer:

```
map.removeLayer("earthquake_circle");
map.removeSource("earthquakes");
```

But this caused flickering ... since we remove the complete layer and adding it again.

For the full (actual running) code, check this codepen: https://codepen.io/skarnl/pen/RwWrdPm?editors=0010

Some extra explanation, what I did in this codepen:

I based it on the original codepen from your blogpost, but added a method to dynamically add features.
The method `createData` will generate a new GeoJson and use that for the `setData` call. I also have added an `setInterval` to add 10 marker every 5 seconds.

So it looks like some kind of bug that the `querySourceFeatures` doesn't get updated with new source-data after a `setData`.

More information:

**mapbox-gl-js version**: 1.9.1
**browser**: Chrome Version 81.0.4044.113 (Official Build) (64-bit) (OSX)

### Link to Demonstration
https://codepen.io/skarnl/pen/RwWrdPm?editors=0010

### Expected Behavior
After calling the `setData` I expect the `querySourceFeatures` to return the updated features.

### Actual Behavior
The `querySourceFeatures` keep on returning the features that were present during the initial source creation ... they never change to reflect any adjusted source.

**Comment by sgolbabaei** [comment]
Thank you for using mapbox-gl-js. With your example, you are sending an entire source spec to setData, while `setData` expects a geojson object. Setting it to use `newSource.data` in your example (line 1430) should make it work.
