### ISSUE TITLE
Custom tooltip for NavigationControl 

### ISSUE THREAD

**Issue by lucasgao** [mapbox/mapbox-gl-js#9620]
Current NavigationControl tooltip is build in Zoom in and Zoom out. Can we support to use custom tooltip text?

**Comment by ryanhamley** [comment]
Hi @lucasgao https://github.com/mapbox/mapbox-gl-js/pull/8095 added a way to implement localization of UI strings. This approach is flexible enough to be used to customize the tooltips for control buttons as well. Here's an example of this approach:

```
var map = window.map = new mapboxgl.Map({
    container: 'map',
    zoom: 12.5,
    center: [-77.01866, 38.888],
    style: 'mapbox://styles/mapbox/streets-v10',
    hash: true,
    locale: {
        'NavigationControl.ZoomIn': 'testing',
        'NavigationControl.ZoomOut': 'foobar'
    }
});
```

For a full list of customizable strings, see https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/default_locale.js

**Comment by lucasgao** [comment]
thank you @ryanhamley which version supports this?

**Comment by ryanhamley** [comment]
This was added in v1.6.0
