### ISSUE TITLE
Marker is flickering when position changes, dependent on zoom level

### ISSUE THREAD

**Issue by atyshka** [mapbox/mapbox-gl-js#9621]
**mapbox-gl-js version**:
1.9.1
**browser**:
Firefox and Chromium
### Steps to Trigger Behavior

 1. Create a new marker with a point source:
```
                map.addSource('point', {
                    'type': 'geojson',
                    'data': {
                        'type': 'FeatureCollection',
                        'features': [
                            {
                                'type': 'Feature',
                                'geometry': {
                                    'type': 'Point',
                                    'coordinates': [0, 0]
                                }
                            }
                        ]
                    }
                });
                map.addLayer({
                    'id': 'points',
                    'type': 'symbol',
                    'source': 'point',
                    'layout': {
                        'icon-image': 'car',
                        'icon-size': 1
                    }
                });
```
 2. Update the point source as new position arrives over a websocket:
```
        map.getSource('point').setData({
            'type': 'FeatureCollection',
            'features': [
                {
                    'type': 'Feature',
                    'geometry': {
                        'type': 'Point',
                        'coordinates': [lng, lat]
                    }
                }
            ]
        });
```

### Link to Demonstration
Image 1: intended behavior when zoomed out
![Peek 2020-04-23 12-33](https://user-images.githubusercontent.com/19317207/80125319-82bc7e80-855f-11ea-8226-93acdcc91d8d.gif)
Image 2: Flashing when zoomed in
![Peek 2020-04-23 12-33-2](https://user-images.githubusercontent.com/19317207/80125327-85b76f00-855f-11ea-9fc3-b11b46c20d9e.gif)

### Expected Behavior
Marker instantly moves to new position regardless of zoom level
### Actual Behavior
Marker is fading out and in as it moves to new position when the view is zoomed sufficiently. This does not happen if the view is zoomed out enough.

**Comment by atyshka** [comment]
Will work on adding a minimal reproducible example when time permits

**Comment by sgolbabaei** [comment]
Thanks a lot @atyshka. Providing a minimal example will help the maintainers and community understand and address the problem accurately. We recommend using https://jsbin.com. Please include information about the browser version and operating system used.

**Comment by atyshka** [comment]
@sgolbabaei Here is an example: https://jsfiddle.net/c1e7pj2f/. I used jsfiddle since this is adapted from a mapbox jsfiddle sample. This is reproducible in Chrome 80.0.3987.158 on Linux.

**Comment by atyshka** [comment]
@sgolbabaei Any updates? Are you able to reproduce the issue with the example I posted?

**Comment by stevage** [comment]
I wonder if it's related to #9435 
As a workaround, if you put `fadeDuration: 0` in the map creation, the effect goes away.

FYI, the correct term here is "symbol layer", not marker. Markers are [something else](https://docs.mapbox.com/mapbox-gl-js/api/#marker).

**Comment by mourner** [comment]
By default, symbols are fading according to the global `fadeDuration` option when they might collide. Setting `'icon-allow-overlap': true` in the example above also gets rid of this if you want to control this per layer.

**Comment by andrewtuplin** [comment]
@mourner 

I'm still seeing this issue on my project when moving layers -- each representing a vehicle -- of type 'symbol' using SetData() to update coordinates.  Neither setting the global fadeDuration to 0 nor 'icon-allow-overlap':true makes any difference.

**Comment by uditgogoi** [comment]
Any solution on this? I am getting this issue when I am using a video and moving it's coordinates using `setCoordinates()`. When pausing the video using `map.value.getSource("video").pause()` and playing it again using  `map.value.getSource("video").play()`, I am getting this flickering.
