### ISSUE TITLE
Map rendering takes long time, Performance issue

### ISSUE THREAD

**Issue by hemanta25** [mapbox/mapbox-gl-js#963]
In map, I draw 400 markers, but when I zooming the map it takes long time to render the map.It's decreases the performance. Please suggest me how to increase the performance of rendering map.

**Comment by mourner** [comment]
JSFiddle please?

**Comment by mourner** [comment]
Also, what is your browser? OS? Mapbox GL JS version? Generally you should read this http://www.macwright.org/report-a-bug/

**Comment by hemanta25** [comment]
Hi Vladimir,

Good Morning,

My browser version is IE 11,
OS : Windows 7 Professional Service pack 1
Mapbox GL JS version : v1.6.2

Thanks,
Hemant

**Comment by mourner** [comment]
There are problems and lacking features in IE11 that make it much slower than other modern browsers like Chrome, Firefox and Safari when it comes to Mapbox GL JS.  The next IE version should get much better in this regard, so up till now we've been focusing on performance in other browsers.
