### ISSUE TITLE
custom line break height for \n

### ISSUE THREAD

**Issue by lucasgao** [mapbox/mapbox-gl-js#9631]
![image](https://user-images.githubusercontent.com/11338060/80390332-48622280-887a-11ea-98b8-b4a51ba3936e.png)
As you can see the line break by add "\n" has more height than the line break by the text-max-width

**Comment by ryanhamley** [comment]
@lucasgao can you create a minimal reproduction of this in JSBin or JSFiddle and post it here? that will help us debug
