### ISSUE TITLE
Rotation on Modern iPhone + Chrome

### ISSUE THREAD

**Issue by Equanimaster** [mapbox/mapbox-gl-js#9639]
**mapbox-gl-js version**: 1.9.1

**browser**: iPhone - Google Chrome.

### Steps to Trigger Behavior

 1. Map container width: 100%, height: 100%, fill whole browser window.
 2. Open on iPhone on Chrome browser.
 3. Rotate multiple time phone to switch portrait to landscape mode.

### Expected Behavior
Mapbox should catch "orientationchange" event and trigger .resize();

### Actual Behavior
Mapbox is resizing container, but canvas remains small.
The size of canvas is the last visible area - new area.

![before_rotation](https://user-images.githubusercontent.com/42443808/80478208-dbbc5600-8955-11ea-9e53-698b0979eac2.jpg)

![after_rotation](https://user-images.githubusercontent.com/42443808/80478206-db23bf80-8955-11ea-97a9-a30cb948370e.jpg)

**Comment by arindam1993** [comment]
Good point @Equanimaster !

We should bind `_onWindowResize` to the `orientationchange` event [here](https://github.com/mapbox/mapbox-gl-js/blob/master/src/ui/map.js#L438), so `trackResize` works for this use case.

The only caveat is, I'm not completely sure if the parent container has already resized when `orientationchange` gets fired.

Patch is welcome @Equanimaster !

**Comment by Equanimaster** [comment]
I have hard-coded into my code this orientationchange  + resize() and its working like a charm.

**Comment by kiraarghy** [comment]
Hey @arindam1993,

I've run into the same issues as @Equanimaster, I'm happy to pick this up and submit a PR given they haven't submitted anything yet.

However, looking at the mdn docs, the orientationchange event seems to be [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Window/orientationchange_event#Browser_compatibility), is that something the mapbox-gl-js team is happy with?

Thanks.

**Comment by Equanimaster** [comment]
I was thinking about the same,
but I'm not sure that this is a good fix,
because double trigger of resize on other browsers,
could cause problems.
I've never contributed to a project like this on github,
if there's a guide I could try commit my idea.

**Comment by ryanhamley** [comment]
Closed by https://github.com/mapbox/mapbox-gl-js/pull/9652
