### ISSUE TITLE
Calling map.easeTo() after map.fitBounds() with a padding does not preserve the padding

### ISSUE THREAD

**Issue by waissbluth** [mapbox/mapbox-gl-js#9643]
Hello,

As I was trying to work around issue https://github.com/mapbox/mapbox-gl-js/issues/9641 by using `map.easeTo()` instead of `map.fitBounds()`, I encountered that easeTo applies an additional padding if fitBounds was already called with a padding from the same side. I was expecting easeTo to respect the original padding that was passed to fitBounds, but that does not seem to be the case.

**mapbox-gl-js version**: v.10.0

**browser**: Chome for Mac 81.0.4044.113

### Steps to Trigger Behavior

 1. call `map.fitBounds(bbox, {padding: {top: 100})`
 2. call `map.easeTo({padding: {top: 100, left: 100})`

### Link to Demonstration

https://jsfiddle.net/xqc2br59/

### Expected Behavior
To have the bounding box be centered on the screen with 100px at the top.

### Actual Behavior
The bounding box has a 200px padding at the top.

**Comment by arindam1993** [comment]
Hi @waissbluth , I agree that this is confusing, but FWIW its actually intended behaviour and a sideffect of introducing two different concepts with the same name. Theres a lot more ontext in 
https://github.com/mapbox/mapbox-gl-js/issues/4268 and https://github.com/mapbox/mapbox-gl-js/pull/8638 but I'll provide short summary here.

![PaddingOptions](https://user-images.githubusercontent.com/1449257/80646603-e7754e80-8a21-11ea-8373-0de2ee2198e3.png)


In your case the first call to `fitBounds` is updating the zoom and center to account for padding, and then you add additional fov based padding on top with the call to easeTo.
