### ISSUE TITLE
`Map.isMoving()` incorrectly returns true inside `mouseup` event handler

### ISSUE THREAD

**Issue by DannyDelott** [mapbox/mapbox-gl-js#9647]
**mapbox-gl-js version**:
1.10.0

**browser**:
Chrome Version 81.0.4044.129 (Official Build) (64-bit)

It looks like there was a possible regression introduced in `mapbox-gl@1.10.0` that affects the result of `map.isMoving()` inside the `mouseup` event handler.

### Steps to Trigger Behavior

 1. Add a layer to the map, then set a `mouseup` event handler on it.
 2. Click on one of the layer's feature and call `map.isMoving()` in the handler.

### Link to Demonstration
🐞`mapbox-gl@1.10.0` - https://codesandbox.io/s/magical-leavitt-6zhso
✅ `mapbox-gl@1.9.1` - https://codesandbox.io/s/lucid-hawking-ruywl

### Expected Behavior
Clicking on Maine should output `map.isMoving() === false`, ie:

```
map.on('mouseup', statesLayerId, () => {
  map.isMoving() // false
}
```

### Actual Behavior
Clicking on Maine outputs `map.isMoving() === true`

**Comment by arindam1993** [comment]
Thanks for the solid bug report @DannyDelott !

@ansis would you know whats causing this?

**Comment by karimnaaji** [comment]
@ansis is this related to https://github.com/mapbox/mapbox-gl-js/pull/9365#issuecomment-619109197?
