### ISSUE TITLE
Map displaying and clicking on features is broken with version 1.9 >

### ISSUE THREAD

**Issue by bar3200** [mapbox/mapbox-gl-js#9648]
**mapbox-gl-js version**: 1.9, 1.10

**browser**: chrome

### Steps to Trigger Behavior

 1. load map and style
 2. load circle layer from geojson
 3. hover on / off / click on features

### Expected Behavior

![image](https://user-images.githubusercontent.com/49412060/80860895-8c3a9a80-8c73-11ea-8fde-057b4ac83e66.png)

click on features works. this is version 1.8.1.

### Actual Behavior

![image](https://user-images.githubusercontent.com/49412060/80860914-bbe9a280-8c73-11ea-95a1-b64dd8fc2dfb.png)

As u can see, the "search" div is relocated on it's own, and i can't click on features.

**Comment by yinminhe** [comment]
I also encountered this problem, how to solve it

**Comment by bar3200** [comment]
> I also encountered this problem, how to solve it

I closed it because I realized that the reason was the search div I implemented onto the map. I guess something in this version is different.
Anyways, try implement any component you want on the map as custom control and it will work.
