### ISSUE TITLE
Centre in Mapbox

### ISSUE THREAD

**Issue by Sowmya-Sukhanand** [mapbox/mapbox-gl-js#9649]
Can we have the inputs given to the centre of the map in child component with coordinates from object passed from a parent component

**Comment by ryanhamley** [comment]
Hi @Sowmya-Sukhanand I'm not sure what you're trying to accomplish. You can use [`map.getCenter()`](https://docs.mapbox.com/mapbox-gl-js/api/#map#getcenter) to get the coordinates of the map center. The coordinates are just an array so you should be able to pass them between whatever components you have as needed.

This seems more of a how-to question so I'd recommend contacting [Mapbox support](https://support.mapbox.com/hc/en-us). Thanks!
