### ISSUE TITLE
Enable custom raster tiled sources like WMS

### ISSUE THREAD

**Issue by Sumbera** [mapbox/mapbox-gl-js#965]
Would be great to have WMS or custom raster-tile source url support through official API. {x},{y},{z}  is not used by classic  WMS - based services  where spherical Mercator coordinates are needed as BBOX. Currently WMS works only by hacking into source._loadTile.
Sample and more details also here http://bl.ocks.org/Sumbera/ba554bb5cc8dfe4d7866

for simple bbox support, {mleft}, {mtop}, {mbottom}, {mright} could be added into TileCoord.url (only  for raster-tiles ?) plus calc Spherical Mercator bbox. However there might come other bbox , quadkey etc requirements...so custom url hook  would be perfect.

**Comment by StepanKuzmin** [comment]
+1

**Comment by fxi** [comment]
+1

**Comment by DenisCarriere** [comment]
+1

**Comment by tmcw** [comment]
Anyone want to roll a PR for this? The problem I've had in the past developing against WMS servers is that there aren't any stable WMS servers on the internet - I've used the NOAA server, but it doesn't support CORS, so this qualification of espg:3857 support + it'll stay online + CORS eliminates all WMS servers I know of.

**Comment by DenisCarriere** [comment]
What if you host your own GeoServer at Mapbox for WMS testing purposes. There's a few [GeoServer Dockerfiles](https://hub.docker.com/r/winsent/geoserver/) that can get you started really fast. 

As for schemas, you could primarily focus on the latest OGC schema of [WMS 1.3](http://www.opengeospatial.org/standards/wms).

**Comment by DenisCarriere** [comment]
I've been able to load a WMS 1.1 using Leaflet without a problem.
```javascript
L.tileLayer.wms("http://localhost:8080/geoserver/ows", {
    layers: 'imagery:Brockville',
    format: 'image/png',
    transparent: true,
    maxZoom: 23,
    maxNativeZoom: 23
}).addTo(map)
```
It would be really nice to have this built in MapboxGL. :+1:

**Comment by tmcw** [comment]
I'd really prefer not to host a server just to develop a feature - WMS servers are unstable and slow, and nobody around here wants to maintain one. Unless someone wants to roll a PR for this, I don't think it's going to happen - this is a feature that connects to a kind of server that doesn't really exist on the internet.

**Comment by DenisCarriere** [comment]
I agree with you, those WMS servers are old technology, so much trouble to enable this feature. :(

**Comment by Sumbera** [comment]
WMS is not the problem, nor you need your own WMS server, nor public server.  You can provide custom URL tile consturctor and leave it up to the client to define final URL string.  GMSTileURLConstructor might be good  example  of elegant 'style in API'  :) you can [follow here](http://blog.sumbera.com/2014/04/21/wms-with-google-maps-on-ios/).

**Comment by m0ose** [comment]
I also +1 this request.
The server at http://sedac.ciesin.columbia.edu/geoserver/ seems stable. 
You can use it in leaflet with
`L.tileLayer.wms("http://sedac.ciesin.columbia.edu/geoserver/ows",{layers:'gpw-v3:gpw-v3-population-density_2000', opacity:0.6})
`

**Comment by jerrygarciame123** [comment]
I need to consume ArcGIS Rest API services into Mapbox GL API.  ArcGIS has a WMS specification.

Any new pathways for this?

**Comment by wangtun** [comment]
I have some satellite .png tiles but the origin point of the tiles is not the Mercator origin point , I wish mapboxgl exports the url function so I can get my customs png tiles

**Comment by jfirebaugh** [comment]
WMS support landed in #2612.

**Comment by DenisCarriere** [comment]
Woot woot! :) This deserves its own Twitter post

**Comment by user1104** [comment]
Even I need to consume ArcGIS Rest API services into Mapbox GL API. ArcGIS has a WMS specification.

Is there any new pathways for this?

**Comment by deligence** [comment]
Hey @user1104 have you got any success in using ArcGIS Rest API in Mapbox GL?
