### ISSUE TITLE
symbols disapear when i add a text field(when textField="" it work correctly.)

### ISSUE THREAD

**Issue by azadeh18** [mapbox/mapbox-gl-js#9650]
symbols disappear when i add a text field property. of course when textField="" , it work correctly.
would you mind to help me on this?
that's my code:

` private void addSymbolToMap(String name, LatLng point) {
  mapStyle.addImage(name, getResources().getDrawable(R.drawable.mapbox_marker_icon_default));
        SymbolManager sampleSymbolManager = new SymbolManager(mapView, map, mapStyle);
   sampleSymbolManager.setIconAllowOverlap(true);
        sampleSymbolManager.setTextAllowOverlap(true);
        sampleSymbolManager.setIconRotationAlignment(ICON_ROTATION_ALIGNMENT_VIEWPORT);
 SymbolOptions sampleSymbolOptions = new SymbolOptions()
                .withLatLng(point)
                .withIconImage(name)
                .withIconSize(1.5f);
                .withTextField("test")
                .withTextFont(new String[] { "Arial Unicode MS Regular"});
 Symbol sampleSymbol = sampleSymbolManager.create(sampleSymbolOptions);
}

`

**Comment by ryanhamley** [comment]
Hi @azadeh18 You are using GL Native, not GL JS. In either case, we cannot offer help with debugging on Github so please contact [Mapbox Support](https://support.mapbox.com/hc/en-us) for further assistance. In the future, please don't post the same message asking for help in multiple tickets.
