### ISSUE TITLE
Authenticate over ESRI ArcGIS WMS server with login and password digest

### ISSUE THREAD

**Issue by flacombe** [mapbox/mapbox-gl-js#9651]
**mapbox-gl-js version**: 0.44.1

### Question

I'm currently trying to plot some wms layers served from ESRI ArcGis server which requires authentication with login and password (no token) for Digest auth.
It seems that only an additional header to give bearers and other information required by Digest auth can make it work. Am I missing anything in Mapbox API?

QGis is currently able to fetch data with simple login/password without any further code. Would it be desirable to do the same with Mapbox gl js?

It is about private data I can't share with you for now i'm sorry.

All the best

### Links to related documentation

It's about this documentation : https://docs.mapbox.com/mapbox-gl-js/example/wms/

**Comment by ryanhamley** [comment]
You may want to try the `transformRequest` option (map options are in the docs [here](https://docs.mapbox.com/mapbox-gl-js/api/#map)). This is more of a how-to question, so if you need more assistance please contact [Mapbox support](https://support.mapbox.com/hc/en-us).

>A callback run before the Map makes a request for an external URL. The callback can be used to modify the url, **set headers**, or set the credentials property for cross-origin requests. Expected to return an object with a url property and optionally headers and credentials properties.

```
var map = new mapboxgl.Map({
  container: 'map',
  center: [-122.420679, 37.772537],
  zoom: 13,
  style: style_object,
  hash: true,
  transformRequest: (url, resourceType)=> {
    if(resourceType === 'Source' && url.startsWith('http://myHost')) {
      return {
       url: url.replace('http', 'https'),
       headers: { 'my-custom-header': true},
       credentials: 'include'  // Include cookies for cross-origin requests
     }
    }
  }
});
```

**Comment by flacombe** [comment]
Hi @ryanhamley and thank you for answer

Well, I'm not able to generate the proper digest bearer currently and only have login and password.
I didn't ask how to add a header but will login and password options be supported ?

All the best

**Comment by ryanhamley** [comment]
@flacombe I think it's doubtful. I don't remember this coming up previously and our own tile servers don't make use of logins and passwords so this would be a highly specialized thing to add to the library. I understand if you can't share your data, but I think your best bet to get help would be contacting our support team at the link in my previous reply. If you can share your general setup, they may have some more ideas for you.

**Comment by flacombe** [comment]
Understood.

Be sure your tiles will be more valuable with private business overlay on top of them.
Adding login/password capabilities isn't only to disperse your efforts but offer extra possibilities to use your product instead of another.

Tech support request sent by the way.
All the best
