### ISSUE TITLE
Allow OffscreenCanvas for Canvas Source

### ISSUE THREAD

**Issue by backspaces** [mapbox/mapbox-gl-js#9659]
## Motivation

My repo uses offscreen canvases when they are available and not part of the html page. This is to be web-worker ready.

So I was surprised when making a Canvas Source to have my (offscreen) canvas cause an error. 

Is it feasible for mapbox to allow offscreen canvases where canvases are input to mapbox?

## Design Alternatives

First, whenever user's canvases are allowed, clearly document whether or not offscreen is OK.

Secondly, modify the code where possible to accept offscreen canvases.

## Design

Documentation first. Implementation if possible.

### Mock-Up

Only difference is that the dev has to be careful not to expose mapbox to offscreen canvases.

### Concepts

Simply explain the offscreen canvas issues and where they are OK to use.

### Implementation

In my work, the implementation was only where I create canvases and 2d/3d contexts to have an "offscreen" boolean which defaults to be "inWorker".

**Comment by ryanhamley** [comment]
Hey @backspaces thanks for using GL JS. There's actually an existing ticket for this issue at https://github.com/mapbox/mapbox-gl-js/issues/8104 so I'm going to close this ticket to concentrate all discussion there. This improvement is on our radar but we don't currently have a timeline for implementing it.
