### ISSUE TITLE
.setStyle() to empty stylesheet does not wipe map

### ISSUE THREAD

**Issue by peterqliu** [mapbox/mapbox-gl-js#966]
Using `.setStyle()` to an [empty stylesheet](https://www.mapbox.com/mapbox-gl-styles/styles/empty-v6.json) successfully clears the `map.style.stylesheet.layers` object, but the map stays visible.

**Comment by jfirebaugh** [comment]
What version are you using?

**Comment by peterqliu** [comment]
@jfirebaugh reproducible with both https://api.tiles.mapbox.com/mapbox-gl-js/v0.5.2/mapbox-gl.js and our dev.js

**Comment by peterqliu** [comment]
@jfirebaugh or by opening https://github.com/mapbox/mapbox-gl-styles/blob/v7/index.html and selecting the `empty` style
