### ISSUE TITLE
Colors do not interpolate on line-color

### ISSUE THREAD

**Issue by paulcheteles** [mapbox/mapbox-gl-js#9661]
Hello, I'm trying to build a map for hiking/biking/running with routes that have a steepness gradient shown as the route color (for example flat- blue, steep-yellow, really steep - red). I've manages to have an array of steepness (expressed in degrees) that is associated to each route segment, and it works, the color are assigned correctly, but are not interpolated and the whole line looks like a bunch of blocky colors put together. See image: https://i.imgur.com/WXRFPqk.png

Also, I'm building the entire route as a series of lineStrings,each linestring with its own steepness degree.

This is the code for building the series of LineStrings: 

```
    for (i = 0; i < geoJSON.features.length - 1; i++) {
      trackObj.features[i] = {
        'type': 'Feature',
        'properties': {
          'gradient': gradientArray[i]
        },
        'geometry': {
          'type': 'LineString',
          'coordinates': [
            coordinates[i],
            coordinates[i + 1]
          ]
        }
      }
    }
```

This is the code I use for the route layer:
```
map.addLayer({
        'id': 'route',
        'type': 'line',
        'source': 'route',
        'layout': {
          'line-join': 'miter',
          'line-cap': 'butt'
        },
        'paint': {
          'line-width': 5,
          'line-color': [
            'interpolate',
            ['linear'],
            ['get', 'gradient'],
            0,
            'hsl(241, 100%, 65%)',
            5,
            'hsl(197, 100%, 65%)',
            10,
            'hsl(125, 100%, 65%)',
            15,
            'hsl(59, 100%, 65%)',
            20,
            'hsl(0, 100%, 65%)',
          ]
        }
      });
```

**Comment by ryanhamley** [comment]
Hi @paulcheteles can you please provide a minimal reproduction of the issue in JSBin or something similar? It appears to me based on the screenshot that it may be interpolating the line color, but the route is made up of many short lines which leads to the blocky look.

**Comment by paulcheteles** [comment]
Of course, here it is: https://jsbin.com/pifocaqoji/edit?html,output

I've slimmed down the trackObj a bit to avoid code bloating. Let me know if you need additional info.

**Comment by asheemmamoowala** [comment]
@paulcheteles The `line-color` property does not create a gradient between line segments in the way that you are expecting. To create a colored gradient on a line, use the [line-gradient](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-line-line-gradient) property. 
This property doesn't support data-driven styling, and the request for that is being tracked over at: https://github.com/mapbox/mapbox-gl-js/issues/8977
