### ISSUE TITLE
Opening a marker's pop-up should set focus to the pop-up's content

### ISSUE THREAD

**Issue by skorasaurus** [mapbox/mapbox-gl-js#9662]
**mapbox-gl-js version**:
confirmed on 1.10.0

**browser**:
confirmed with firefox 75 on ubuntu and chrome on windows 

### Steps to Trigger Behavior

 1. [Open demonstration page](http://bl.ocks.org/skorasaurus/40d6f977d2db8038b99ed6aca5354f73)
 2. press tab several times so a marker a has focus
 3. press enter to open its pop-up
 4. Press tab again

### Link to Demonstration
Demonstration source
https://gist.github.com/skorasaurus/40d6f977d2db8038b99ed6aca5354f73 

Viewable demonstration
http://bl.ocks.org/skorasaurus/40d6f977d2db8038b99ed6aca5354f73

### Expected Behavior

the keyboard focus should change to the pop-up's contents of the marker 
whether through a designated keydown event (pressing enter on the keyboard while focus is on the marker) or the click event. 

In other words, a user who is only able to use a keyboard will tab through 
each tabbable element, reach a marker that they would like to access, press enter to open, and expects that during their next tab, the focus would be on the first 
tabbable element (the link, a heading, or a close button for the pop-up)
in that pop-up.  

### Actual Behavior

After a user opens the pop-up, and presses tab, the focus changes to the next 
item in the source. 

In the test case that loads a geojson array of 27 elements, if a user tabs after opening, the focus changes to the next point in the source data. As a result, if the user opens up a pop-up for a point that was 4th in the source data, they'll have to tab through the remaining 23 entries, plus any other elements on the page. 

This is a bug because users who are only able to use a keyboard to navigate have to go through significant more work in order to access the content of a pop-up (which may contain a link).

**Comment by ryanhamley** [comment]
Thanks for the thorough report @skorasaurus! We welcome contributions, if you're interested in supplying a pull request to fix this issue. Our [contributor guidelines](https://github.com/mapbox/mapbox-gl-js/blob/master/CONTRIBUTING.md) can get you started.

**Comment by avpeery** [comment]
Hi @ryanhamley it looks like this issue was addressed in the merged PR #9774 (https://github.com/mapbox/mapbox-gl-js/pull/9774). Should this issue be closed? Thanks!

**Comment by ryanhamley** [comment]
Yep looks like an oversight. Thanks for checking @avpeery
