### ISSUE TITLE
What projection is really being used?

### ISSUE THREAD

**Issue by Rumpelstinsk** [mapbox/mapbox-gl-js#9664]
Reading your documentation I came to 2 pages that claims that different proyections are being used by Mapbox:

- [This link](https://docs.mapbox.com/mapbox-gl-js/api/#lnglat) says EPGS:4326 is being used
- [This other link](https://docs.mapbox.com/help/glossary/source/) says EPSG:3857 is being used

I'm a bit confused right now. Is 4326 used un mapbox-gl-js, and 3587 somewhere else? Maybe proyections are dependant on source type?

**Comment by ryanhamley** [comment]
Hi @Rumpelstinsk good question! I can see how the docs could be confusing. EPSG:4326 (or WGS84) is used to store coordinates in data. The latitude and longitude of features in GeoJSON that we use in GL JS are stored in EPSG:4326. However, EPSG:4326 cannot be displayed directly on a two-dimensional surface so GL JS automatically converts the EPSG:4326 latitude and longitude to EPSG:3857, also known as Web Mercator.
