### ISSUE TITLE
Marker change position with zoom

### ISSUE THREAD

**Issue by syldor** [mapbox/mapbox-gl-js#9669]
A marker with a set position will slide a bit with zoom. We can see it in this codepen where the marker size is updated with the zoom to not grow:

https://codepen.io/a10k/pen/EJLMMy

At low zoom we have the marker positioned on the street. 

![image](https://user-images.githubusercontent.com/4158062/81387236-91e72300-9140-11ea-8bc1-8bb128cc9973.png)

When zooming out, the marker slides down in the river.

![image](https://user-images.githubusercontent.com/4158062/81387288-a2979900-9140-11ea-8281-fa891370fc30.png)

The CSS file is inlined.

**Comment by andrewharvey** [comment]
>   //svgContainer && (svgContainer.style.transform = "rotate(" + -map.getBearing() + "deg)");

looks like it would be easier to just the rotationAlignment Marker option https://docs.mapbox.com/mapbox-gl-js/api/#marker

I'm not sure why the marker shifts, but doing zoom dependent scale would be a lot easier with a symbol layer.

**Comment by syldor** [comment]
This is not a mapbox problem, but the svg element overflowing its parent div, like explain here: https://stackoverflow.com/questions/27833908/svg-element-not-coming-inside-a-div

Sorry about that !
