### ISSUE TITLE
addImage error

### ISSUE THREAD

**Issue by dythbj** [mapbox/mapbox-gl-js#9673]
mapbox: 1.7.0-dev
browser: chrome  80.0.3987.163
os:macOS 10.15.4
=======================================
Client code:
   map.loadImage('http://127.0.0.1:7001/public/lib/fill.png', (err, image) => {
        if (err) throw err;
        map.addImage('pattern', image);
    });
Error: 
    ajax.js: Could not load image. Please make sure to use a supported image type such as PNG or JPEG. Note that SVGs are not supported.
=======================================
As i track source code，i noticed that：
1) loadImage() is allright

2)The "data",get from the imageBitmap is undefined,like this:
<img width="869" alt="WX20200509-204210@2x" src="https://user-images.githubusercontent.com/41282663/81474441-0fda2580-9238-11ea-9765-cd622b7ab9a1.png">

3)The data.length !== width * height * channels  triggered the error,like this:
<img width="824" alt="WX20200509-193348@2x" src="https://user-images.githubusercontent.com/41282663/81474608-3ba9db00-9239-11ea-834f-6d9122b9a65e.png">

can any one help?

**Comment by karimnaaji** [comment]
@dythbj can you post the full code for this example (ideally in https://jsfiddle.net), as well as the png you are using?
