### ISSUE TITLE
touchmove event changed in v1.10, not fired when map is moved

### ISSUE THREAD

**Issue by fcandi** [mapbox/mapbox-gl-js#9676]
**mapbox-gl-js version**: 1.10.0

**browser**: Chrome

### Steps to Trigger Behavior

touchmove event is not fired when moving the map on touch devices

### Expected Behavior

Touchmove event should be fired whenever the map moves on touch devices, as it is in all versions prior to 1.10.0

### Actual Behavior

The touchmove event is only fired when a draggable marker is moved on touch devices

**Comment by karimnaaji** [comment]
@fcandi Thanks for the report, I created a comparison example to identify whether this is a regression.

- [v1.9.0](https://jsfiddle.net/kanaa/crL210mt/17/embedded/result)
- [v1.10.0](https://jsfiddle.net/kanaa/crL210mt/16/embedded/result)

This part of the code seems covered by unit tests, but I can confirm this is a regression in v1.10.0 as I just tested and compared on iOS.

cc @ansis

**Comment by fcandi** [comment]
Thanks @ansis this is exactly what I am talking about. But you Switches the
titles of your links. The first points to the 1.10 version and the second
to 1.9 ;)

Andreas

Karim Naaji <notifications@github.com> schrieb am Mo. 11. Mai 2020 um 23:52:

**Comment by karimnaaji** [comment]
@fcandi Will be available as part of v1.10.1, thanks for the report!
