### ISSUE TITLE
line dashes don't interpolate between stops

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#968]
Stop functions don't seem to get interpolated. It looks like the dasharray is just switching at the onset of the next zoom level in the stop function:

![linedash-stop-functions](https://cloud.githubusercontent.com/assets/5607844/5965712/2e7941f8-a7cc-11e4-8635-1e3fcc27b36b.gif)

```
{
    "id": "admin_level_3",
    "type": "line",
    "source": "mapbox",
    "source-layer": "admin",
    "filter": ["all", [">=", "admin_level", 3], ["==", "maritime", 0]],
    "layout": {
      "line-join": "round"
    },
    "paint": {
      "line-color": "@admin",
      "line-dasharray": {
        "stops": [[4, [10, 3, 3, 3]], [18, [3, 0.5, 0.5, 0.5]]]
      },
      "line-width": {
      "base": 1,
      "stops": [[4, 0.4], [5, 1], [12, 3]]
      }
    }
  }
```

**Comment by mourner** [comment]
Wasn't this intended behavior? https://github.com/mapbox/mapbox-gl-style-spec/issues/237

**Comment by nickidlugash** [comment]
You're right. For some reason I wasn't thinking this would be the behavior :/
