### ISSUE TITLE
Provide the ability to close network requests to https://events.mapbox.com/

### ISSUE THREAD

**Issue by ParryQiu** [mapbox/mapbox-gl-js#9687]
## Motivation

> Mapbox Telemetry is a powerful location analytics platform included in this SDK. By default, anonymized location and usage data is sent to Mapbox whenever the host app causes it to be gathered. The Mapbox Terms of Service require your app to provide users with a way to individually opt out of Mapbox Telemetry, which is provided automatically as part of the attribution control.

It should be possible to manually close this network request in an offline environment.

REFER: [https://github.com/mapbox/mapbox-gl-native/issues/9125
](https://github.com/mapbox/mapbox-gl-native/issues/9125)
## Design Alternatives

Provide setting function for map instance to deal with this problem.

## Design

map.setScenario(NETWORK.OFFLINE);

**Comment by asheemmamoowala** [comment]
@ParryQiu Mapbox-GL-JS does not collect location analytics via `Mapbox Telemetry` and is not supported in an offline environment. Closing this here as it doesn't seem relevant, and an answer has already provided at https://github.com/mapbox/mapbox-gl-native/issues/9125#issuecomment-319715933 where you have also commented.
