### ISSUE TITLE
Marker Div different height as context

### ISSUE THREAD

**Issue by strech345** [mapbox/mapbox-gl-js#9692]
if you check the marker cluster example, the maker div have a different height then the svg. Why this happens?
https://docs.mapbox.com/mapbox-gl-js/example/cluster-html/

![image](https://user-images.githubusercontent.com/7572377/82065894-f8cf8380-96ce-11ea-879f-5721ec9cabbb.png)

**Comment by mourner** [comment]
Nice catch! Found [an answer here](https://stackoverflow.com/questions/24626908/how-to-get-rid-of-extra-space-below-svg-in-div-element) — we need to set `display: block` on the SVG element to avoid the gap under the div (which also makes the markers shift slightly). 

@strech345 want to do a quick PR to https://github.com/mapbox/mapbox-gl-js-docs to fix this?

**Comment by strech345** [comment]
@mourner you mean only writing the pr? because i dont know where in the code to solve this.

**Comment by mourner** [comment]
@strech345 here https://github.com/mapbox/mapbox-gl-js-docs/blob/publisher-production/docs/pages/example/cluster-html.html

**Comment by strech345** [comment]
@mourner ok maybe im a litttle bit stupid, but how to create a new pr?
if i go to pull request and click on new pr it tells me
`Choose different branches or forks above to discuss and review changes.`

**Comment by mourner** [comment]
@strech345 you can click on the "edit" button at the top right of the file, and GitHub will walk you through afterwards:

![image](https://user-images.githubusercontent.com/25395/83895645-aa585680-a75b-11ea-8696-fa3eaa656d13.png)

**Comment by strech345** [comment]
@mourner 
thanks. Thought i should work locally with vs code to test it.

**Comment by HeyStenson** [comment]
This was resolved in https://github.com/mapbox/mapbox-gl-js-docs/pull/344 - closing!
