### ISSUE TITLE
Mapbox Popup showing up in top left corner with "mousemove" eventlistener

### ISSUE THREAD

**Issue by m0hamad** [mapbox/mapbox-gl-js#9693]
**mapbox-gl-js version**: 1.10

**browser**: Google Chrome V 81.0

### Steps to Trigger Behavior

 1. Hovering over the very edge of a fill-extrusion feature triggers the popup to show up in the top left corner of the map, although I have a trackPointer() instance member added.

### Demonstration
*** Screenshots attached ***
I have a fill-extrusion layer added to the map where I am displaying 3D buildings and wanted to add a Popup that shows up on hover. The popup mostly works fine when hovering the 3D buildings, but occasionally when I am hovering on the edge of a building feature, the popup; will show up on the top left corner of the map rather than where the cursor is. I'm not sure if this is a bug or not but I have not been able to resolve this issue.

### Expected Behavior

Mapbox popup shows up in the same location as the cursor because I have added .trackPointer()

### Actual Behavior
The popup shows up in the top-left corner

<img width="1351" alt="Mapbox_Popup_Issue" src="https://user-images.githubusercontent.com/25091942/82085256-f3ac0d80-96a9-11ea-81fc-79e9ccdeed62.png">
<img width="1353" alt="Mapbox_Popup" src="https://user-images.githubusercontent.com/25091942/82085365-2524d900-96aa-11ea-9ac9-5eac18355146.png">

**Comment by karimnaaji** [comment]
Hey @m0hamad , do you mind giving a link, or build a small restricted example showing the behavior? It's easier for us to focus on the problem and address the underlying issue. Usually https://jsfiddle.net is a good way to share that type of bugs.

**Comment by Bernoulli-IT** [comment]
Exactly the same issue here.

**Comment by sychovSaveliy** [comment]
@SourceCipher hey! This solution helped me:
```
.mapboxgl-popup-track-pointer {
    border-radius: 10px;
    overflow: hidden;
 }
```
