### ISSUE TITLE
text-rotate not working

### ISSUE THREAD

**Issue by tom62291** [mapbox/mapbox-gl-js#9699]
Dear All,

I have using the mapbox vector tile with mapbox vector tile spec with following setting for a layers:

      {
         "id":"Labels/BuildingHouseNoPoint/<all other values>",
         "type":"symbol",
         "source":"esri",
         "source-layer":"BuildingHouseNoPoint",
         "filter":[
            "==",
            "_symbol",
            0
         ],
         "minzoom":18,
         "layout":{
            "icon-image":"Labels/BuildingHouseNoPoint/<all other values>",
            "icon-allow-overlap":true,
            "text-font":[
               "Arial Regular"
            ],
            "text-size":10,
            "text-anchor":"center",
            "text-offset":[
               0.0,
               0
            ],
            "text-rotate":{
               "property":"_label_angle",
               "default":0
            },
            "text-field":"{_name}",
            "text-optional":true,
            "text-rotation-alignment":"map"
         },
         "paint":{
            "icon-color":"rgba(240,240,240,0)",
            "text-color":"#343434"
         }
      }

However, seems the point text label doesn't rotate based on the attributes "_label_angle"
Please help.

Thank you.

**Comment by fishead** [comment]
Just got this error report from Sentry, hope it's useful.

![image](https://user-images.githubusercontent.com/874813/82194485-7989bc00-9929-11ea-82b8-3cac7e584326.png)
![image](https://user-images.githubusercontent.com/874813/82194343-3af40180-9929-11ea-9773-7b1e6bdffb51.png)

**Comment by tom62291** [comment]
Hi all, I just figured that "type"="identity" is required in the "text-rotate" node.
Thank for your help
