### ISSUE TITLE
How to distinguish user-interaction and programmatic events?

### ISSUE THREAD

**Issue by HighSoftWare96** [mapbox/mapbox-gl-js#9700]
**mapbox-gl-js version**:
1.9.1
### Question
I'm using the mapbox-gl-js package (specifically with the ngx-mapbox wrapper). I have an issue distinguishing the events that are triggered programmatically and the events triggered by a user interaction. Is there a way to know the difference between these two types of events without listening to all the user-interaction events possibile? I have not found anything neither in the documentation nor on StackOverflow. 

In my particular case I'm listening to the moveend event and I the application loops when I try to save in the application state the map changes.

**Comment by andrewharvey** [comment]
All of the camera methods like https://docs.mapbox.com/mapbox-gl-js/api/#map#setcenter have a second optional argument `eventData`. So when you programatically trigger these events you could pass an object as the eventData and then check for that in the listener.

**Comment by HighSoftWare96** [comment]
Ok, so this cannot be done natively without adding that argument?

**Comment by HighSoftWare96** [comment]
I think the only way to fix this is by modifying the ngx-mapbox API then...
