### ISSUE TITLE
Mapbox Direction says totally wrong route!

### ISSUE THREAD

**Issue by BerkeAras** [mapbox/mapbox-gl-js#9701]
Mapbox Direction API gives often a totally wrong route. I am in Germany and I use two german coordinates, but it gives soo often this route: `"summary":"Ceerigaabo - Badhan Highway برن‎‎ - طريق السريع عيرجابو"`

I don't know where to put this issue :(

**Comment by sgolbabaei** [comment]
@BerkeAras Thanks for using Mapbox. You can report this issue here:
https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231

I am going to close this issue since this is not related to Mapbox gl-js
