### ISSUE TITLE
List Co-Ordinates of Different Countries

### ISSUE THREAD

**Issue by Aurorum** [mapbox/mapbox-gl-js#9704]
It'd be fantastic if a list could be added containing the co-ordinates for all countries. For example, with Kenya, they're listed here: https://docs.mapbox.com/mapbox-gl-js/example/fitbounds/

```js
map.fitBounds([
[32.958984, -5.353521],
[43.50585, 5.615985]
]);
```

But I've been searching for ones for the United Kingdom for a bit now, and can't seem to come across them anywhere! Having a list of them would be super helpful. :)

**Comment by mourner** [comment]
You can find them by searching for "country bounding boxes". Here's the first result I found: https://gist.github.com/graydon/11198540

**Comment by Aurorum** [comment]
Perfect, thank you so much! :)
