### ISSUE TITLE
Mapbox Popups

### ISSUE THREAD

**Issue by Sowmya-Sukhanand** [mapbox/mapbox-gl-js#9712]
The css style applied to popup up contents is not reflecting

code:

.mapboxgl-popup-content{
    color: #F3F3DD;
    background-color: #91785D;
    border-color: #91785D;
    max-width: 250px;
    box-shadow: 3px 3px 2px #8B5D33;
    font-family: 'Oswald';
}

I use mapbox@1.10.0

var popup=new mapboxgl.Popup({offset:25,closeButton:false,closeOnMove:true})
              
                .setHTML(
                  '<div >'+
                    '<p>'+
                          Hello
                    '</p>'+
                  '</div>'
                  );

**Comment by sgolbabaei** [comment]
Thank you for your opening this ticket. To help the maintainers and community understand and address the problem accurately can you please provide a minimal, complete, verifiable demonstration of the issue. We recommend using https://jsbin.com. Please include information about the browser version and operating system used.
