### ISSUE TITLE
symbol layer dissappears

### ISSUE THREAD

**Issue by transfluxus** [mapbox/mapbox-gl-js#9714]
**mapbox-gl-js version**:
v1.10.1

**browser**:
chromium and firefox
firefox endures longer

### Steps to Trigger Behavior

My application with vue and mapbox (mabox-gl-vue). It happens only after a a while but is sooner triggered, when I have a sidemenu open (see video) return to the map and zoom

https://youtu.be/O8-kug7vWWY

But I also just found that when I have a popup open and zoom its triggered:

https://youtu.be/xK_Wh0Ratyo

### Link to Demonstration

Basically this https://docs.mapbox.com/mapbox-gl-js/example/cluster/
but extended a bit (trying to fix it)

```
this.map.addLayer({
            id: layer_base_id + '_cluster-count',
            type: 'symbol',
            source: source_name,
            filter: ['has', 'point_count'],
            layout: {
              "text-allow-overlap": true,
              "text-ignore-placement": true,
              'text-field': '{point_count_abbreviated}',
              'text-font': ['DIN Offc Pro Medium', 'Arial Unicode MS Bold'],
              'text-size': 14
            }
          })

```

I also set the source to             tolerance: 0
### Actual Behavior

text stays visible

**Comment by transfluxus** [comment]
indeed, having a mousemove listener creating a popup:
```
          this.act_popup = new this.mapboxgl.Popup()
            .setLngLat(coordinates)
            .setHTML(feature.properties.title)
            .addTo(this.map)
        })
```

causes it

**Comment by mourner** [comment]
@transfluxus does it happen for you on https://docs.mapbox.com/mapbox-gl-js/example/cluster/? If so, can you provide more details about your environment — OS, GPU, and whether this reproduces on a different machine? If it doesn't happen on the official example, can you provide a minimal live test case where it does, e.g. JSFiddle or CodePen?

**Comment by transfluxus** [comment]
@mourner thanks for the response. It doesnt happen on the cluster-example. I changed the fiddle in order to show popups when I click on a cluster, but everything is still fine. 

maybe its caused by mapbox-gl-vue but that library is actually just a thin wrapper.

I am on ubuntu 20.04, Intel Corporation UHD Graphics 620

Is there any layer attribute that I can check, which might have magically be changed?

**Comment by mourner** [comment]
@transfluxus I don't know. 🤔 Try removing things from a reproducible example bit by bit until you get to a minimal example, preferably without other libraries / wrappers.

**Comment by transfluxus** [comment]
ok, so the problem really just seems to come from the interplay of mapbox-gl and vue.
This works
```
this.act_popup = new this.mapboxgl.Popup()
  .setLngLat(coordinates)
  .setText(feature.properties.title)
this.act_popup.addTo(this.map)
```

while this doesn't

```
this.act_popup = new this.mapboxgl.Popup()
  .setLngLat(coordinates)
  .setText(feature.properties.title)
  .addTo(this.map)
```

even tho in both cases the assignment is ok. considering that act_popup is an reactive property... 
no idea :)
