### ISSUE TITLE
Upscale raster tiles

### ISSUE THREAD

**Issue by brzez** [mapbox/mapbox-gl-js#9716]
Is there a way of upscaling raster tiles?

Similar to [maxNativeZoom / minNativeZoom](https://leafletjs.com/reference-1.6.0.html#gridlayer-maxnativezoom)  in Leaflet

Is there a way to enable this in mapbox-gl?

**Comment by andrewharvey** [comment]
set a lower maxzoom on the source and then a higher maxzoom on the layer?
