### ISSUE TITLE
Add marker with 'anchor: bottom' adds marker in wrong place

### ISSUE THREAD

**Issue by bjtaylor1** [mapbox/mapbox-gl-js#9717]
When I run
```javascript
var marker = new mapboxgl.Marker( {
    	anchor: 'bottom'
    }).setLngLat([-74.5, 40]).addTo(map);
```
It adds the marker in the wrong place.
Expected behaviour: the bottom of the marker (the point) should point exactly to the coordinates specified.
Actual behaviour: the bottom of the marker is slightly north of the coordinates specified.
Mapbox version: see fiddle
Browser: Safari Version 13.1 (15609.1.20.111.8)

**To reproduce:**
https://jsfiddle.net/bentaylor/f3xzauyp/1/
Keep clicking where you think the base of the marker is.

I have added a `map.click` event to reposition the marker at the point where you clicked. If you keep clicking the base of the marker, it keeps moving north! To get the marker to stay still, you have to actually click below (south of) it.

**Comment by andrewharvey** [comment]
You can just remove the anchor option and it the default Marker element will already anchor at the tip.

Is there a valid use case for wanting to change the anchor of the default marker?

Do you have a suggestion of how this should work differently? So should we try to build in a special case for using anchor with the default marker or just issue a console warning to say it is unexpected?

**Comment by mourner** [comment]
To have it at the bottom, pass `offset: [0, 0]` in the options in addition to the `anchor`. The `anchor` is `center` by default, so when he default marker is used, we position it in place using an offset. Here's a comment in the code that explains how this happens:

https://github.com/mapbox/mapbox-gl-js/blob/aaaaa4eb94944ff5a99d5936deccee2d1ad5bc8d/src/ui/marker.js#L195-L201

**Comment by bjtaylor1** [comment]
OK, I see.
I guess I was interepreting that `anchor: bottom` meant "anchor the _bottom_ of the marker (i.e. the tip) at the point that you clicked.

Thanks for looking and the suggestion anyway

**Comment by mourner** [comment]
@bjtaylor1 that's exactly how it works, except the special case where `offset` is not provided and you use the default marker with non-default `anchor` (so it automatically sets `offset` to `[0, -14]`, expecting `anchor` to be `center`). In practice this shouldn't be a problem.
