### ISSUE TITLE
Init full screen map with options

### ISSUE THREAD

**Issue by ballonura** [mapbox/mapbox-gl-js#9718]
**mapbox-gl-js version**: 1.10.1
**browser**: any

There is anyway to initialize map in fullscreen mode (with the options object)? I have map that u can re-init the map with on-map custom button, and when you do it on fullscreen mode, the map init in regular mode (the browser stay in fullscreen mode), and the fullscreen control also return to init state.

**Comment by mourner** [comment]
It's not exposed through a public API, but you could try using the fullscreen API directly, like so:

```js
const container = map.getContainer();

if (container.requestFullscreen) { // good browsers
    container.requestFullscreen();
} else if (container.msRequestFullscreen) { // IE11
    container.msRequestFullscreen();
}
```

The control should pick up the change. But this only works if initiated through a user gesture (e.g. in a button click handler).

**Comment by ballonura** [comment]
Don't work because of: "Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture."
