### ISSUE TITLE
Y offset if elements exist within map, since 1.9.0

### ISSUE THREAD

**Issue by stevage** [mapbox/mapbox-gl-js#9721]
**mapbox-gl-js version**: 1.9.0 and later

**browser**: Tested in FF and Chrome

This bug/change is a bit hard to describe succinctly. It occurs when you have (for some reason) an element within the map:

`<map id="map"><span>My map</span></map>`

Prior to 1.9.0, the behaviour I see:

* the map contents are pushed below the element, 
* pointer events at the bottom of the span have a y value of 0.
* no pointer events occur behind the span
* calling `map.on('mousemove', e => queryRenderedFeatures(e.point.y))` works as expected.

![Screen Shot 2020-05-25 at 3 15 11 pm](https://user-images.githubusercontent.com/678344/82780775-86635e00-9e9b-11ea-98f9-08ad39cc3133.png)

(The pink line is a line within the map. The white box at the top is the browser's address bar)

From 1.9.0 onwards:

* the map contents appear behind the element (the overall effect is the map appears slightly higher compared to the previous situation) 
* pointer events at the bottom of the span have a y value of 0
* pointer events on the span have a negative y value
* calling `map.on('mousemove', e => queryRenderedFeatures(e.point.y))` doesn't work properly - the point's y value needs to be offset by the height of the span element to match up with what `queryRenderedFeatures()` expects.

This last point is the significant one, and how it actually manifested.

Code pen with issue (v 1.9.0): https://codepen.io/stevebennett/pen/NWGmGKM

Code pen without issue (v1.8.0): https://codepen.io/stevebennett/pen/ExVJVxY

**Comment by mourner** [comment]
> It occurs when you have (for some reason) an element within the map

I don't think we expect there to be any existing elements — can you say more about your use case? Why would you have a non-empty container for the map?

**Comment by stevage** [comment]
I thought you might ask that :)

No use case here. Helping someone else with a map, and I don't know why they had an element inside it either.

**Comment by andrewharvey** [comment]
I may have in the past put some text in there like "map loading" or "webgl not supported" but neither of those are the best way to deal with such situations. But either way if mapbox gl expects the div to be empty, we could document that in the API docs and/or add a warning if it's not empty.

**Comment by ansis** [comment]
Adding a warning sounds good to me. Seems like it would be a bit more useful than docs in this case

**Comment by HansBrende** [comment]
@ryanhamley @ansis @mourner I have a use-case:
<img width="406" alt="Screen Shot 2023-01-27 at 2 41 05 AM" src="https://user-images.githubusercontent.com/5846890/215044810-aea18396-437c-40ca-a9a4-70c4d975940a.png">

As you can see, I'm adding the geographical coordinates of the current cursor position to the map above the attribution. And now I see this warning every time I open the console. Is this really negatively impacting interactivity any more than the attribution element is (which by the way, is a child of the same container element you're warning about)? Because from where I stand it seems like a false and annoying warning.

**Comment by stepankuzmin** [comment]
Hi, @HansBrende. I assume it would be more idiomatic to create a custom control using [IControl](https://docs.mapbox.com/mapbox-gl-js/api/markers/#icontrol) interface to achieve the same results without adding separate elements inside the map.

**Comment by HansBrende** [comment]
@stepankuzmin that's a possibility, however, it also raises the question "more idiomatic according to _whom_?" I'd argue that forcing us to use an imperative style with `document.createElement` etc. is **very un-idiomatic** in the larger web ecosystem where we like to use React components.

**Comment by stepankuzmin** [comment]
Yes, that's true that in your use case, it'd be more idiomatic to use a declarative way. But unfortunately, GL JS doesn't provide a React solution out of the box, and we rely on the end users implementing all the necessary wrappings around the GL JS library. You can still implement the custom control using the [IControl](https://docs.mapbox.com/mapbox-gl-js/api/markers/#icontrol) interface and use the imperative `myUpdateLogic` function in `useEffect` to update the underlying element.

**Comment by HansBrende** [comment]
@stepankuzmin well after thinking about it for a bit, I just went with the following approach instead, which seems to be simpler:

```jsx
return (
    <div style={{position: 'relative'}}>
        <div className="map-container" ref={mapContainerRef} style={{width: '100%', height: '100%'}}/>
        <div className="map-coordinates" ref={mapCoordinatesRef}/>
    </div>
);
```

Seems to work fine. But anyways, at least now you have at least one valid use-case (since use-cases were asked for above).

**Comment by stevage** [comment]
Sorry to chime in late - but yes, placing other HTML elements over (rather than within) the map element is the standard approach. 

I usually don't bother using the IControl interface unless it's particularly important that the control follows the CSS layout rules and/or other styling.
