### ISSUE TITLE
Should ideally 'fail fast' if there is content in map div

### ISSUE THREAD

**Issue by bjtaylor1** [mapbox/mapbox-gl-js#9722]
If we initialize MapBox GL in a div that has content, I would ideally like it to fail fast and warn me that there shouldn't be any pre-existing content in the div.
Instead, it goes ahead and initializes in the div, but reports inaccurate coordinates in the click event.

https://jsfiddle.net/bentaylor/muspL8ho/6/

I appreciate that this could well be regarded as "user error", not least because it is in the documentation _somewhere_, but I can't recall where now, and it took me a fair while to figure out this was why my example was going wrong yesterday - and I almost wrote it off before discovering this.
A simple `console.warn` would suffice to achieve the objective without disrupting any existing apps for which it doesn't matter, i.e. without the cure ever being worse than the symptom.

**Comment by andrewharvey** [comment]
I agree, but let's fold this into #9721 as it looks like the same issue.

**Comment by bjtaylor1** [comment]
Agree, looks like same thing.
