### ISSUE TITLE
full world mask clipping issues during zoom

### ISSUE THREAD

**Issue by khrome-cape** [mapbox/mapbox-gl-js#9725]
**mapbox-gl-js version**: 1.4.1

### Question

First, I apologize if this should be a bug, but I first wanted to ask a question, before I assume there is a defect.

I'm encountering Issues with clipping in a couple of scenarios:

- when I have a series of punchouts and one of them fully contains one or more of the others.
![contained](https://user-images.githubusercontent.com/38257089/82948262-b58ed380-9f5e-11ea-89ad-ff46a540878a.png)

- when I have many large GeoJSON sources onscreen at once, I get various artifacts at certain zoom levels, but none at others(this is the same view zoomed in less than a zoom level)... 

<img width="900" alt="land" src="https://user-images.githubusercontent.com/38257089/82948322-cfc8b180-9f5e-11ea-820d-d0956aead196.png">

<img width="956" alt="zoomed" src="https://user-images.githubusercontent.com/38257089/82948368-e3741800-9f5e-11ea-9a64-4bc721660699.png">

I realize the first case is a degenerate case where performance may not be as expected, but the second case seems to be brought on by a combination of vertex and data density that I have not been able to reproduce in an isolated case. Is there some known performance characteristics I could work around in the data that might alleviate this( possibly related to clustering or buffering)? The app uses 6 sources with 3-5 layers per source, with a range of structures per layer rarely exceeding 100 at the polygon complexity you see in the isolated example.

I have an isolated case of data similar to the app, but it does not reproduce the behavior [here](https://jsfiddle.net/khrome/f3dzymq2/)

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/style-spec/sources/#geojson

**Comment by mourner** [comment]
It's hard to tell what happens here without a minimal live test case. It might be the case of #7023, but usually that only manifests if the polygon is very detailed and complex.

**Comment by khrome-cape** [comment]
Thanks, this is actually pretty helpful as we encounter the issue only rarely. We're definitely loading too much data in the browser and there's a plan to reduce that, albeit distant. If, as a part of that, the issue is resolved or I get further information, I'll be sure to post again or reopen.
