### ISSUE TITLE
unminified mapbox-gl broken

### ISSUE THREAD

**Issue by hlolli** [mapbox/mapbox-gl-js#9726]
**mapbox-gl-js version**:

1.10.1

**browser**:

(fails on build-time)

### Steps to Trigger Behavior

 1. npm install mapbox-gl
 
### Link to Demonstration

I think some of the javascript bundlers are incorrectly configured.

On lines 8185-8198 in the file dist/mapbox-gl-unminified.js you should see

```js
    for (var i$1 = 0, list$1 = groupedByOutput; i$1 < list$1.length; i$1 += 1) {
        var ref = list$1[i$1];
        var outputIndex = ref[0];
        var labels = ref[1];
        if (labels.length === 1) {
            serialized.push(coerceLabel(labels[0]));
        } else {
            serialized.push(labels.map(coerceLabel));
        }
        serialized.push(this.outputs[outputIndex$1].serialize());
    }
    serialized.push(this.otherwise.serialize());
    return serialized;
```

where the token `outputIndex$1` is undeclared, this breaks builds with for example google closure compiler, not sure how this affects other compilers.

**Comment by mourner** [comment]
Confirmed. It's a bug in Buble: https://github.com/bublejs/buble/issues/258
I wonder why we never saw this error in testing and on live maps — the affected code is `Match` expression `serialize`.

**Comment by mourner** [comment]
Looks like the offending code (introduced in #6469) is never used at runtime, that's why we never noticed the issue. It's only reproducible when you process the bundle with Google Closure.

**Comment by mourner** [comment]
No longer relevant in v2+ since we don't transpile the bundle now.
