### ISSUE TITLE
Rendering artifacts on buildings when using pencil-v7 style

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#974]
Hello,

I opened issue #943 which has been fixed by using the pencil-v7 style. It fixes most issues I was having  but I now have rendering artifacts with pencil-v7, it happens on every building, see this screenshot:

![image](https://cloud.githubusercontent.com/assets/1240481/5992509/dfab905e-aa2c-11e4-8369-1ca6b12d8196.png)

(it creates some smiley faces on some buildings but that's not the point :) )

Here is the link to pencil-v7:
https://github.com/mapbox/mapbox-gl-styles/blob/v7/styles/pencil-v7.json

It looks like the black line is always in the same direction, always the same length and seem to origin from the centroid of the polygon

If you need more informations, just tell me

Thanks,
Fabien

**Comment by ansis** [comment]
@fnicollet are you still seeing this with the lastest style and mapbox-gl-js?

**Comment by fnicollet** [comment]
Hello @ansis ,

Just updated both mapbox-gl-js and pencil-v7 today and can still reproduce the issue

Fabien

**Comment by jfirebaugh** [comment]
The pencil style and v7 styles are no longer supported.
