### ISSUE TITLE
Clusters shall not take into account non visible features

### ISSUE THREAD

**Issue by Codain** [mapbox/mapbox-gl-js#9742]
Context: Mapbox GL JS 1.10.1 for a website.

It looks like clusters (based on (https://docs.mapbox.com/mapbox-gl-js/example/cluster/)) take into account all features on the map, including those which are on a layer with visibility set to none (such as when using (https://docs.mapbox.com/mapbox-gl-js/example/filter-markers/)) .

I would expect clusters to not take into account hidden features by default and to be updated when toggling visibility of layers. If necessary a boolean attribute such as "clusterIgnoreHiddenFeatures" could be provided on Source objects to toggle behaviour.

**Comment by mourner** [comment]
The reason why it works this way is that clustering is a concept that applies to **sources** (the data), not **layers** (its presentation), and happens only once after the GeoJSON source loads, not when any of the layers change.

One way we could address this is by implementing #2613, so let's continue the discussion there.

**Comment by Codain** [comment]
Ok, thanks. Sorry for the dupplicate, I did not find it when searching before creating this issue.
