### ISSUE TITLE
Newline in Mapbox Studio Text Field still no worky 

### ISSUE THREAD

**Issue by ramz211** [mapbox/mapbox-gl-js#9743]
**mapbox-gl-js version**:

**browser**: Chrome, firefox, Edge

### Steps to Trigger Behavior

 1. Load external multiline geojson file into tileset
 2. Enter a property into Studio Text Field to display that text along line with \n to display text on new lines
 

### Link to Demonstration

This issue/bug has been brought up and closed before without resolution. 
#6064 
#3179

### Expected Behavior
\n in Studio Text Field entries, \n should render as new line
![Screenshot_2020-05-29 Studio](https://user-images.githubusercontent.com/64946725/83320575-ca3cc700-a1fd-11ea-96e2-8e7228f6b617.png)
![Screenshot_2020-05-29 Studio(1)](https://user-images.githubusercontent.com/64946725/83320585-d9237980-a1fd-11ea-83c2-ce819e9fb1cd.png)

### Actual Behavior
\n Line breaks PREVIEW correctly in Studio, but do not render. After rendering, all text shows on 1 line. In Studio, if you click "Edit Json" it views correctly with the \n , but when you click back to "Edit Value" the \n have all been replaced with blank spaces, and in rendered maps, all text is on 1 line
![Screenshot_2020-05-29 Studio(2)](https://user-images.githubusercontent.com/64946725/83320656-5c44cf80-a1fe-11ea-8c25-02f0362247b9.png)
![Screenshot_2020-05-29 Monochrome2](https://user-images.githubusercontent.com/64946725/83320587-dfb1f100-a1fd-11ea-9e61-966d1db71fa2.png)

**Comment by asheemmamoowala** [comment]
@ramz211 Thank you for using Mapbox-GL-JS. This issue tracker is for reporting bugs and feature requests to mapbox-gl-js. 
What you are describing is an issue with using the Studio editor, which is not within the scope of this project. [Mapbox support](https://www.mapbox.com/contact/) is the right place to request help with issue pertaining to Studio. Thank you!
