### ISSUE TITLE
Glitch on fill pattern

### ISSUE THREAD

**Issue by frodrigo** [mapbox/mapbox-gl-js#9745]
Present on 1.10.1 and previous version.

Particularly visible when using more fill patterns. But even present with less fill pattern.

Issue only on first zoom in an area. Reload the page to show it again on the same area.

![Peek 31-05-2020 17-37](https://user-images.githubusercontent.com/1785486/83356335-dba0e300-a365-11ea-821c-2177e5f7c489.gif)

Same glitch observed on Linux Firefox and Linux Chrome.

* Live demo: https://vecto-dev.teritorio.xyz/styles/teritorio-tourism-gl-style-bug-pattern/#11.08/44.9346/-0.488
* Style: https://vecto-dev.teritorio.xyz/styles/teritorio-tourism-gl-style-bug-pattern/style.json
* Wetland polygon on the demo: https://www.openstreetmap.org/way/42273322

**Comment by asheemmamoowala** [comment]
This is looking similar to the issues demonstrated in #9724 with a simpler reproducible case. Closing here to keep the discussion focussed in a single ticket.
