### ISSUE TITLE
Track User Location not panning camera

### ISSUE THREAD

**Issue by Magnuspil** [mapbox/mapbox-gl-js#9746]
Hi, 

I have experienced some issues while tracking users GPS location on our map.

I have followed the official documentation, to run the tracuserlocation programmatically on Map Load, however i'm experiencing an error the second time visiting. First time, it works fine. The location is tracked, the camera moved and coordinates changed I'm logging coordinate changes in console). However, the second time entering the site, the coordinates changes but the camera doesnt move at all. The Geolocate icon also changes to this: https://imgur.com/a/bMnhSul

The icon with the dot in the middle, is the one showing when every aspect works (camera animating and so), while the icon without the dot (but still blue), is showing when only coordinates change.

I'm running this code:

```
mapboxgl.accessToken = 'USE OWN KEY';
    var marker = new mapboxgl.Marker();
    var map = new mapboxgl.Map({
        container: 'map',
        style: 'mapbox://styles/custom/ck6j63f0e10w11inyc4c8za4k',
        center: [115.1383, -8.3692],
        zoom: 13
    });

  const geolocate = new mapboxgl.GeolocateControl({
positionOptions: {
enableHighAccuracy: true
},
trackUserLocation: true
});
  map.addControl(geolocate);
  
map.on('load', function () {

      geocoder.query('Bali') // or wherever you want the marker to start
      geolocate.trigger();
      $("#map").css("pointer-events","none");
    });
```

Why does it not move the camera some times and some it works fine?

Thank you!

**Comment by andrewharvey** [comment]
In the documentation at https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol it say

> In this mode the GeolocateControl has three interaction states:
> 
> * active - the map's camera automatically updates as the user's location changes, keeping the location dot in the center. Initial state and upon clicking the GeolocateControl button.
> * passive - the user's location dot automatically updates, but the map's camera does not. Occurs upon the user initiating a map movement.
> * disabled - occurs if Geolocation is not available, disabled or denied.

What you describe is when it enters the passive state such that the user location dot will move but not the camera. It does this to still allow the user freedom to pan and move the map while their location is changing.

If you'd like to lock onto the location you could set `interactive: false` as a map option stopping user interaction of the map and hence it should never enter the _passive_ state and always be _active_.

**Comment by Magnuspil** [comment]
Hi AndrewHarvey,

Thank you for your response. The intended use, is that it should always be interactive, but each time you enter the site it should pan the camera to your location. If you are on site, and moves around - then it's totally fine it doesnt animate, but it's expected to animate everytime you enter the site. So why does it not work that way? Because, shouldn't that piece of code, make it pan to the users location everytime the browsers refresh?

**Comment by andrewharvey** [comment]
I'm not sure what you mean by "each time you enter the site", but looking at your code where you have

```
geocoder.query('Bali') // or wherever you want the marker to start
geolocate.trigger();
```

Since both of those are asynchronous is it possible that the map move is being triggered by the first line, which is then moving the geolocate control into _passive_?

If you can nail down exactly the scenario which triggers the issue that would help.

The implementation is at

https://github.com/mapbox/mapbox-gl-js/blob/cfeff87b2f16fdd8480d7b760d9c19f4accb7485/src/ui/control/geolocate_control.js#L394-L405

so if the map is moved and it's not from a resize event then it will move into this _passive_ state.

I think in an ideal world, moving into _passive_ would only happen from a human moving the map and not from the map being moved progamatically, but I'm not even sure that is the issue here.

**Comment by Magnuspil** [comment]
Hi Andrew,

Thank you for your reply and elaboration. It definitely helps.

Let me elaborate more, on the issue at hand

**What's our goal?**
We wish to achieve, that every time you enter our site, with the map on, it automatically locates the user on the map. While this happens, the user coordinates are display in an input field to the user. This last part, works as expected. It successfully displays the user coordinates every time the enters the site.

**Whats happening right now then?**
As mentioned above, the users coordinates are displayed accordingly. That part works. However, the first i enter the site, then the camera moves from marker set on the map (we set a marker first time the enter our site, on a general location), to the users location. We still wants to use the general location but as a fallback, if user location is not possible.

When entering the site numerous times, i experience that a majority of the time, the camera is not panning to the user location but stays at the general location ( a marker set on the center of the map). After refreshing a couple of times, it pans to the user location, but it only happens a minority of the times. Mostly, it stays on the general location. 

It's expected to pan to the location every time you enter the site.

You can test for yourself, here: https://jsfiddle.net/MagnusPilegaard/g1Lap5jr/9/

It always prints the correct coordinates to the inputs, so it for sure finds the location every time. The camera just doesn't pann

**Comment by andrewharvey** [comment]
> After refreshing a couple of times, it pans to the user location, but it only happens a minority of the times.

Yes what you're seeing that does sound like what I mentioned:

> Since both of those are asynchronous is it possible that the map move is being triggered by the first line, which is then moving the geolocate control into passive?

> You can test for yourself, here: https://jsfiddle.net/MagnusPilegaard/g1Lap5jr/9/

Yes in your code if the geolocate control gets a position first it will start flying to the user location, but then is interrupted by the geocoder result and will then will then fly to the geocoder position. So from what I can see GL JS is working as expected in this, and if you want to change this behaviour you'll need to address this in your code.

I'm still interested to hear any suggestions or improvements for how the GeolocateControl works, but so far I can't see any changes warranted.
