### ISSUE TITLE
Difference between expression and function

### ISSUE THREAD

**Issue by exotfboy** [mapbox/mapbox-gl-js#9747]
As said in the [offical docs](https://docs.mapbox.com/mapbox-gl-js/style-spec/other/#function), the `function` and `filter` is not preferred, we should use `expression` instead.But what's the difference?  

For example the `has` [expression](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#has): `["has", string]`

The `has` filter to be [deprecated ](https://docs.mapbox.com/mapbox-gl-js/style-spec/other/#existential-filters): `["has", key]`

I can  not see any difference. They are all array(s). So does the Comparison filters,Set membership filters. And for the Combining filters like `["all", f0, ..., fn]` , how to transform them to expression?

Also for property functions:
>Warning
As of v0.41.0, property expressions is the preferred method for styling features based on zoom level or the feature's properties. Zoom and property functions are still supported, but will be phased out in a future release.

Before, we will use something like this to set the `fill-color` according to the 'code'property of the feature:
```
"fill-color": {
   "default": "red",
   "type": "categorical",
   "property": "code",
   "stops": [[ "a", "red"],[ "b", "blue"],[ "c", "green"] ]
}
```
How to implement that using expression?

**Comment by mourner** [comment]
@exotfboy the overall difference is that `filter` is has a more restricted syntax and is only applicable to filters, while expressions are much more powerful, and universal in a sense that they can be used for both properties and filters.

For the `has` example specifically, the key difference is that legacy filter syntax expects feature property name as `key`, while the expression accepts an arbitrary string that can itself be an expression that evaluates to a string (so you would use `["get", "prop"]` for an equivalent, but could also use any other complex expression).

As for the legacy "property functions", the expression equivalents are:

- [match](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#match) for "categorical" functions
- [step](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#step) for "interval" functions
- [interpolate](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#interpolate) for "exponential" functions

Generally we're planning an overhaul of the expressions documentation to make it more clear and add a ton of examples. Tagging @mapbox/docs for visibility.

**Comment by exotfboy** [comment]
@mourner  Thanks. :)

As you said `a ton of examples` maybe much more clear. Looking forward to that.
