### ISSUE TITLE
Custom layer with renderWorldCopies

### ISSUE THREAD

**Issue by zakjan** [mapbox/mapbox-gl-js#9759]
**mapbox-gl-js version**: 1.10.0

### Question

Custom layer receives the transformation matrix in prerender/render functions for a single world only. When renderWorldCopies is true, how do I get the transformation matrix for all rendered world copies? So that I could render the copies of the custom layer as well.

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/api/properties/#customlayerinterface
https://docs.mapbox.com/mapbox-gl-js/example/custom-style-layer/
https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/

**Comment by zakjan** [comment]
I have found an undocumented way how to do it currently, without any more matrices.

In prerender/render, I get the rendered worlds with:

```
const worldOffsets = map.transform.getVisibleUnwrappedCoordinates({x: 0, y: 0, z: 0}).map(x => x.wrap).sort((a, b) => a - b);
return worldOffsets.slice(1, worldOffsets.length - 1);
```

Then I render my shaders multiple times for each worldOffset, pass it as uniform, and add `vec2(uWorldOffset, 0)` to every Mercator position before multiplying with the matrix. It works!

Is this a good solution, or would you recommend something better? I'm worried about the way to get the rendered worlds, because `map.transform` is private.

**Comment by zakjan** [comment]
Closing, I have switched to simple `map.getBounds`. It returns the entire bounds, including world copies. The bounds can be transformed to Mercator, and used as shader input vertices, rendering the custom layer in a single draw call.

**Comment by GarrettCannon** [comment]
@zakjan Any chance you could throw an example into a codepen/jsfiddle? I would like to be able to do the same thing. Much appreciated!

**Comment by m9dfukc** [comment]
@zakjan I would also be interested in how to apply the `map.getBounds`. Currently I do it with multiple render passes but that seems not very elegant. Any code example would be very welcome even a very simple one just to get the rough picture.

Thanks!

**Comment by tangzijun** [comment]
private getWorldOffsets() {
    const bounds = this.map.getBounds();
    const west = bounds.getWest();
    const east = bounds.getEast();

    const x1 = 0 - Math.ceil((Math.abs(west) - 180) / 360);
    const x2 = Math.ceil((Math.abs(east) - 180) / 360);

    const worldOffsets = [];
    for (let i = x1; i <= x2; i++) {
      worldOffsets.push(i);
    }
    return worldOffsets;
  }

**Comment by tangzijun** [comment]
Here is my solution：https://github.com/maplibre/maplibre-gl-js/discussions/4614#discussioncomment-10462526
