### ISSUE TITLE
marker.on 'drag' event does not match documentation

### ISSUE THREAD

**Issue by Yermo** [mapbox/mapbox-gl-js#9763]
**mapbox-gl-js version**:

1.10.1
**browser**:

Chrome 77.0.3865.90 (Official Build) (64-bit) under Ubuntu Linux 

### Steps to Trigger Behavior

 1. add 'drag' event handler to the https://docs.mapbox.com/mapbox-gl-js/example/drag-a-marker/ example.

e.g.

```
function onDrag( event ) {
  console.log( "Drag event is:", event );
};

marker.on('drag', onDrag);
```
 2. add breakpoint on console.log
 3. examine the structure the event
 4. note that it does not match the MapMouseEvent https://docs.mapbox.com/mapbox-gl-js/api/?size=n_10_n#map.event:drag. There are no point or lngLat members. 

### Link to Demonstration

https://jsbin.com/

### Expected Behavior

The documentation states it should be a MapMouseEvent with point and lngLat members.

### Actual Behavior

There are no point or lngLat members in the event object for a drag event on a marker.

**Comment by Yermo** [comment]
The same is true for the dragend event.

**Comment by andrewharvey** [comment]
Which part of the docs say that the Marker `drag` and `dragend` events pass a `MapMouseEvent`? At https://docs.mapbox.com/mapbox-gl-js/api/markers/#marker-events it just says they are passed the marker of type `Marker`. This is also confirmed in the source https://github.com/mapbox/mapbox-gl-js/blob/cccd8588a01c3856706d538a2221c5d9a9373764/src/ui/marker.js#L502-L511

**Comment by andrewharvey** [comment]
The bit you linked to at https://docs.mapbox.com/mapbox-gl-js/api/map/#map.event:drag is a `drag` event on the `Map` object, not the `drag` event on the `Marker` object.

**Comment by Yermo** [comment]
#oops. 

My bad.

**Comment by Yermo** [comment]
Having said that is there an acceptable way of getting the current coordinates as the marker is being dragged? I'm using target._pos but the x/y coordinates it returns is slightly off so I'm patching it but it feels really ugly. (The idea is that I want to highlight features under the marker as I am dragging over them.)

**Comment by andrewharvey** [comment]
What about just calling marker.getLngLat() on Marker `move`? However if you're then going to call `Map#queryRenderedFeatures` you'll need the unprojected point which you can get with `Map#project(lngLat)` see https://docs.mapbox.com/mapbox-gl-js/api/map/#map#project

**Comment by Yermo** [comment]
That's a good point. I'll give that a try.  Thank you.
