### ISSUE TITLE
changing filters in casade or mutable vector tile features

### ISSUE THREAD

**Issue by alexmuro** [mapbox/mapbox-gl-js#977]
I am trying to do a basic map where the feature I am hovering over changes color [example](http://bl.ocks.org/mbostock/4657115)
 
  My approach so far is to make 2 layers in my source, 1 with all features from a vector source and 1 which is filtered to a single feature.  Then I do this
```
  var currentFeature = {properties:{geoid:'23'}};
  map.on('hover', function(e) {
      map.featuresAt(e.point, {radius: 5}, function(err, features) {
          if (err) throw err;
          if(features[0]){
            if(currentFeature.properties.geoid !==  features[0].properties.geoid){
              style.layers[2].filter = ["==", "geoid", features[0].properties.geoid];
              map.setStyle(style);
              currentFeature = features[0]
            }
          }
      });
  });
```
  This works but map.setStyle() takes way too long to re render the map to create a fluid effect.
 
  I know I can edit the style in map.style.layerMap['layerid'] and I can change things in paint or paint.class and use cascade to get the map to update very quickly, however that doesn't help in this case.
  
   Another approach would be to modify the feature's properties such that it complies with a preset filter but there is no setData() for vector tiles and modifying data regured by featuresAt() isn't effective.

  Is it possible to put filters inside of the cascade refresh? Or is it possible to update vector tile data? What would be involved in implementing one of these features?

**Comment by jfirebaugh** [comment]
Hi Alex -- the short answer is that there isn't a good way to do this right now. See #146 and #200 for issues tracking this use case.
