### ISSUE TITLE
Ability to retrieve a single image from styles sprite

### ISSUE THREAD

**Issue by weslleyaraujo** [mapbox/mapbox-gl-js#9770]
Hey there, I haven't found any API on which I could retrieve an SVG/png of a specific icon on my sprite (uploaded via Mapbox studio)

I want to use the same icon on parts of my UI alongside with the map, didn't want to keep SVG's on my side + Mapbox, would rather have things in sync

Is there a way to do that? 🤔

**Comment by ryanhamley** [comment]
There is no API to retrieve the image data from a sprite sheet. If you want to avoid duplication, you may want to invert this by loading the image at runtime with [map.loadImage](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#loadimage) and [map.addImage](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addimage). The image data will be available for you to use elsewhere if `loadImage` is successful.

**Comment by weslleyaraujo** [comment]
Thanks for clarifying  and for the suggestion 👍
