### ISSUE TITLE
CSP Worker: Failed to construct worker. Cannot be accessed from null

### ISSUE THREAD

**Issue by tsengliwei** [mapbox/mapbox-gl-js#9783]
I am following the [doc](https://docs.mapbox.com/mapbox-gl-js/api/) to use the CSP worker distribution. I created a minimal sample page to test the CSP worker. However, I keep getting the error 
`web_worker.js:9 Uncaught DOMException: Failed to construct 'Worker': Script at 'PATH_TO/mapbox-gl-csp-worker.js' cannot be accessed from origin 'null'.`

I have tried to use the worker both locally and from the CDN, but I still got the same issue. This is my sample code:

The local file structure is:
-csp_test.html
-mapbox-gl-csp-worker.js

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8' />
    <title>CSP Test</title>
    <script src='https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl-csp.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl.css' rel='stylesheet' />
    <style>
      body {
        margin: 0;
        padding: 0;
      }

      #map {
        position: absolute;
        top: 0;
        bottom: 0;
        width: 100%;
      }
    </style>
  </head>
  <body>
    <div id='map'></div>
    <script>
    // mapboxgl.workerUrl = "https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl-csp-worker.js";
    mapboxgl.workerUrl = "mapbox-gl-csp-worker.js";
    mapboxgl.accessToken = 'pk.eyJ1IjoidHNlbmdsaXdlaSIsImEiOiJjazlsd210ZDUwZWtoM2VuNWRtbW9xbTMyIn0._fQlFJlWjAjIZrG19H7htg'; // replace this with your access token
    var map = new mapboxgl.Map({
      container: 'map',
      style: 'mapbox://styles/mapbox/streets-v9', // replace this with your style URL
      center: [-87.661557, 41.893748],
      zoom: 10.7
    });
    // code from the next step will go here
    </script>
  </body>
</html>
```

What am I missing and how do I get it to work? Also, if I were to use its npm distribution, I probably cannot set the meta tag. In that case, how could I make it to work as well? Thank you!

**Comment by mourner** [comment]
Are you opening this page in the browser as a local file? Browsers don't allow running workers in that case. You'd have to serve it from a static web server.

**Comment by tsengliwei** [comment]
I ran the code with the worker downloaded locally and open the file on a static web serve, and it works. However, if I ran the code with the CDN worker URL "https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl-csp-worker.js" on a static web server, I am still getting the error
[](Uncaught DOMException: Failed to construct 'Worker': Script at 'https://api.mapbox.com/mapbox-gl-js/v1.10.1/mapbox-gl-csp-worker.js' cannot be accessed from origin 'http://127.0.0.1:8887'.)

**Comment by ElmoJones3** [comment]
I'm also getting the above error, in my case, I'm trying to have this bundled in a react app, and haven't been able to get this to work.
