### ISSUE TITLE
i am getting 'Image "minimo-grey_poi-1" could not be loaded. ' warning after upgrading version 0.48.0 to latest 1.11.0 

### ISSUE THREAD

**Issue by intermx-nagaraj** [mapbox/mapbox-gl-js#9784]
Image "minimo-grey_poi-1" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event.https://

**Comment by ryanhamley** [comment]
You need to make sure that the requested image is available either as part of your style's sprite sheet or by using [`map.addImage`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addimage) at runtime. If you need to load the image from an external source, you can use [`map.loadImage`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#loadimage) before calling `addImage`.

Note that this issue tracker is for reporting bugs and requesting features. For general support and "how-to" questions, we recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us).
