### ISSUE TITLE
Marker is not rendered in the correct place

### ISSUE THREAD

**Issue by velobarplus** [mapbox/mapbox-gl-js#9785]
**mapbox-gl-js version**: affects version from 1.9.0 to 1.11.0

**browser**: Chrome

### Steps to Trigger Behavior
Update to a version newer than 1.8.1.
From 1.8.1 to prior versions it works as expected.

### Link to Demonstration
https://velobar.plus/routes/letape-du-tour-de-france-2020/

### Expected Behavior
When you move you mouse over the elevation profile from under the map, a marker should appear on the map, and it follows the position of the elevation profile.

### Actual Behavior
After updating to the latest version, when hovering over the elevation profile from under the map, the marker is positioned in the wrong place, it is off the map.

**Comment by andrewharvey** [comment]
I can't see the issue on that link? Could you post a minimal reproducible example of the issue?

**Comment by velobarplus** [comment]
@andrewharvey the on in the link is the working version, I think it is obvious I'm not going to leave a non working version online.
Basically there is a marker, and when I do `setLngLat()` it places it in the wrong place (outside of the visible map), and this happens only after version 1.9.0 (including).

https://velobar.plus/assets/js/route.js - `var mapRabbitMarker`
line 312

**Comment by andrewharvey** [comment]
@velobarplus to quote the issue template

> Providing a minimal, complete, verifiable demonstration *dramatically* improves maintainers' and other community members' ability to understand and address the problem you're reporting. (See https://stackoverflow.com/help/mcve for guidelines on creating an effective example.)
