### ISSUE TITLE
mapbox.places showing inaccurate information of services around a coordinate

### ISSUE THREAD

**Issue by Kireet-Gannavarapu** [mapbox/mapbox-gl-js#9786]
The services shown around a point by bbox parameter are different after I increase the range. i.e the services closer to me are not shown when I increase the range of the bbox

**mapbox-gl-js version**: 

**browser**: Firefox

### Steps to Trigger Behavior

I have created a mini project to demonstrate the bug. 
https://obscure-escarpment-67611.herokuapp.com/
In there, for the second form field, use the following values:
37.8715926,-122.2727469
Starbucks
10

after looking at the results, go back and use the same coordinates and service type but change the range from 10 to 20

You will notice that one of the starbucks store which was shown in 10km range is not shown in 20km range.

### Link to Demonstration

https://obscure-escarpment-67611.herokuapp.com/

### Expected Behavior
I was expecting to get all the services around the point.

### Actual Behavior
Missing Information of many services

**Comment by ryanhamley** [comment]
Hi @Kireet-Gannavarapu thanks for using Mapbox. The GL JS team does not maintain the Places API so I'm going to close this as not actionable on our end. I recommend you contact [Mapbox Support](https://support.mapbox.com/hc/en-us) for further guidance.
