### ISSUE TITLE
App is getting crashes when map is on keep alive page and holding in different page

### ISSUE THREAD

**Issue by Taxi4you** [mapbox/mapbox-gl-js#9791]
**mapbox-gl-js version**: 1.8.0

**browser**: chrome

### Steps to Trigger Behavior

 1. Page "A" for example is the page that holds the map. This page is stetted to work on keep alive mode - that means that if I move to page "B", page "A" is keep working and functioning.
 2. Navigating to page "B"
 3. After 10-20 seconds the app will be crashed and completely closed.

Tested on Samsung A70.
When user viewing page "A" the app won't get crashed even after days.
Using React JS v16 and Framework7.

**Comment by ryanhamley** [comment]
Hi @Taxi4you unfortunately this is not actionable as is. We need more information. It would be great if you could strip out the React and Framework7 code to get a reproducible example in plain Javascript. At the very least, we'd need to see a live site that this happens to. I'm going to close this issue as non-actionable but feel free to reopen it when you can provide an example.
