### ISSUE TITLE
Request header field accept-language is not allowed by Access-Control-Allow-Headers in preflight response

### ISSUE THREAD

**Issue by pitchinnate** [mapbox/mapbox-gl-js#9800]
**mapbox-gl-js version**:  1.9.1

**browser**: Chrome 83.0.4103.106

### Steps to Trigger Behavior

 1. Override your location using Chrome's Sensor option.
 2. Load a site that uses mapbox and pulls in a mapbox dataset via api.
 3. Will see a CORS error for the api call.

### Link to Demonstration

` Access to XMLHttpRequest at 'https://api.mapbox.com/datasets/v1/omitted/123/features?access_token=publickeyhere' from origin 'https://fake.site' has been blocked by CORS policy: Request header field accept-language is not allowed by Access-Control-Allow-Headers in preflight response.`

### Expected Behavior

Mapbox api should add `accept-language` as a valid CORS header as Chrome especially likes to send it when dealing with Geolocation.

### Actual Behavior

CORS request fails as the header isn't allowed.

**Comment by ryanhamley** [comment]
Hi @pitchinnate Thanks for using Mapbox. The API services are not overseen by the GL JS team so there's nothing actionable for us with regards to the GL JS library on this issue. I'd recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us) who can pass along your issue and perhaps help with potential workarounds.
