### ISSUE TITLE
how mapbox show a big geojson file with heatmap

### ISSUE THREAD

**Issue by WtyFile** [mapbox/mapbox-gl-js#9803]
**mapbox-gl-js version  v1.5.0**:

### Question

i have a 40MB geojson file,
it's like {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"dbh":0},"geometry":{"type":"Point","coordinates":[-79.91746,40.44356]}},{"type":"Feature","properties":{"dbh":12},"geometry":{"type":"Point","coordinates":[-79.94606,40.44961]}},...
when i cut it to less than 30MB,the mapbox webpage can load. But it must be less than 30MB. I wonder how can i use a larger geojson file to show the webpage. Or are there any other method to show the data by using heatmap?

### Links to related documentation
Look forward to your reply.

**Comment by karimnaaji** [comment]
@WtyFile I recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us) for this type of help regarding the use of the library, we're only focusing on actionable bugs and issues on github.
