### ISSUE TITLE
Dynamically turn off/on scrollZoom based on mapZoom value

### ISSUE THREAD

**Issue by chapmanjacobd** [mapbox/mapbox-gl-js#9806]
## Motivation

I would like to disable zooming if the map is zoomed out and the user is scrolling out and enable zooming if the user has already scrolled to the top of the page and are continuing to scroll up (like they are expecting the map to zoom in) does that make sense?

It would be nice if this behavior was already built-in to mapbox-gl-js as an option.

## Design Alternatives

I can't think of any

## Design

Maybe this could be accommodated via adding a padding option in setBounds. I'm not sure

### Implementation

https://stackoverflow.com/questions/62441249/zoom-in-map-when-at-top-of-page-scroll-page-when-map-is-zoomed-out

**Comment by karimnaaji** [comment]
@ansis is this something already possible with the current gesture system?

**Comment by andrewharvey** [comment]
I think a mockup would be really handy to help understand what you're asking.

"disable zooming if the map is zoomed out" I don't understand what "if the map is zoomed out means" the map has a zoom somewhere between the min and max zoom, so what's zoomed out?

By default if you're scrolling down and the map has reached the minzoom it will stop zooming out and then if you've scrolled to the top of the page and scrolling up and over the map, then it will already zoom in. Sorry I don't understand your question.

**Comment by chapmanjacobd** [comment]
If the map is at minZoom and the user keeps scrolling out then the page should move down

I was able to get it to work using the existing API! Thanks for your help :)

Here is the relevant code if someone else is interested in achieving similar behavior:

```js
map.on('zoom', () => {
    const [[w, s], [e, n]] = map.getBounds().toArray()

    if ((w < -179.9 && 179.9 < e) || (s < -73.9 && 82.9 < n)) {
        window.scrollTo({ top: window.scrollY + window.innerHeight * 0.05 })
    } else {
        if (0 < window.scrollY)
            window.scrollTo({ top: 0, behavior: 'smooth' })
    }
})
```

It would be nice if the map could know that it has reached the map bounds but for now those will need to be hard-coded (?)

Here is what this behavior looks like: [https://gallant-brahmagupta-ee9cbc.netlify.app/](https://gallant-brahmagupta-ee9cbc.netlify.app/)

**Comment by andrewharvey** [comment]
> If the map is at minZoom and the user keeps scrolling out then the page should move down

Oh I get it now. I'm not sure if that's something which should happen by default as when you're scrolling on the map it would be weird to have the page start scrolling, unless it's a non interactive map. I think this kind of behaviour is something that would be customised for each site depending on how your maps are embedded and what you want the UX to be.

**Comment by chapmanjacobd** [comment]
Yes. I definitely don't think it should be a default behavior, but it would
be nice to have slightly more fine-grained control. A map.on('zoomIn') and
map.on('zoomOut') would be nice but it's working without that.

https://github.com/mapbox/mapbox-gl-js/issues/824

I would have had this issue as well if my map didn't start at the top or
end at the bottom. I'm referencing that issue here so that other people
could consider my solution if they are having that issue
