### ISSUE TITLE
Render map in my own canvas

### ISSUE THREAD

**Issue by gitcatrat** [mapbox/mapbox-gl-js#9807]
**mapbox-gl-js version**:
1.6.1 or later

### Question
I need to render the map to my WebGL canvas which already has all kinds of visuals and effects. Few things that need to be done:

* Mapbox map canvas still exists but it's either moved out of viewport or hidden
* Map is drawn to a quad in my canvas as a texture like this: `gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, map.getCanvas());`
* My canvas already has pretty solid interaction layer, it understands drags, pinches, etc. Plan:
  * My canvas logic determines that it was map quad that got hit
  * Create a correct fake event (`new Event` API) and dispatch it to Mapbox HTML element that has listeners (don't know yet which one)
* Finally figure out how to render all the markers and popups in canvas and not HTML

So my question is: does Mapbox have any tools that can help me or this plan sounds reasonable?

**Comment by ryanhamley** [comment]
Hi @gitcatrat GL JS doesn't provide any tools that would help with any of this. The overall approach sounds reasonable but it's hard to say without knowing exactly what you want to do. You could conceivably convert HTML markers and popups to symbol layers. If you need more help, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).
