### ISSUE TITLE
Support animating the camera along a path

### ISSUE THREAD

**Issue by mourner** [mapbox/mapbox-gl-js#981]
With the perspective view in place, we'd want to easily make flight animation that follows a particular set of points, e.g. like Cesium does: http://www.doarama.com/view/160847

**Comment by lucaswoj** [comment]
ref #2801

**Comment by stevage** [comment]
Cool. Implementing this would probably be beyond me (maths and 3D are definitely not my strong suits), but I'm happy to help workshop what the interface might look like.

For instance, a couple of options:

1: `map.setCamera([pos1, pos2, pos3...])`

Issues:
- how to indicate whether the path should loop
- a lot of the behaviour of the animation options will behave differently when they're interpolated across a number of points. For instance, an easing function from A to B then from B to C doesn't make sense - probably it would have to ease from A to C. Or maybe easing doesn't have a use case here, and linear interpolation is the only thing that makes sense.

2: `map.setCameraPath(path)`

Issues
- What format is `path`? 
- Does this relatively niche use case justify a top level method?

3: `map.setCamera({ ... }); map.addCameraDestination( { ... } ); ...`

Issues:
- probably just not good.


Also, there is a bigger issue here in that currently you can't explicitly set a camera's 3D position (in X, Y, Z terms - you can only express it in polar coordinates from a given target destination).

**Comment by lucaswoj** [comment]
In the pursuit of making GL JS the smallest & sharpest tool possible, we're going to punt on this feature and encourage it to be written as a plugin.

**Comment by stevage** [comment]
Yeah, probably a good idea. I'm not sure it's actually doable yet though, with the existing API. Currently, you can only animate a path along a straight line, or a curve (with very few parameters). So you can't really create an arbitrarily curving line, I don't think (could be wrong!). Maybe you'd have to make a looot of `flyTo` calls :)

**Comment by lucaswoj** [comment]
> you'd have to make a looot of `flyTo` calls :)

Yes! Or `Map#setCamera` calls #2801 😄. This is how any implementation would need to work on some level.

**Comment by stevage** [comment]
Yeah, I'm looking forward to that API simplification.

Btw, and just FYI: "to punt on" is really ambiguous. In British/Australian/NZ/... English, it means "to take a gamble on". I gather in American English it means something like "to take the safe option". :)

**Comment by lucaswoj** [comment]
My apologies! I didn't realize how regional that idiom was. The definition I was shooting for was ["If you punt on something, you decide not to do or include it"](http://dictionary.cambridge.org/us/dictionary/english/punt-on-sth)

**Comment by stevage** [comment]
Ha, no apology necessary. ([Punting on the River Cam](https://www.google.com.au/search?q=punting+on+the+river+cam&newwindow=1&biw=1440&bih=800&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwj8ppKcqKXSAhVLppQKHWUADBsQsAQIaw) is something else entirely...)
