### ISSUE TITLE
Firefox printing map is empty

### ISSUE THREAD

**Issue by JanLoebel** [mapbox/mapbox-gl-js#9810]
Hi there,

I have a problem regarding printing a map displayed with leaflet and mapbox-gl. Use the official url: https://openmaptiles.org/docs/website/leaflet/ try to print it as a pdf and the first map is completely empty.

**mapbox-gl-js version**: 1.10.1

**browser**:
Firefox / Firefox-Developer-Edition on Windows 10

### Steps to Trigger Behavior
 1. Open https://openmaptiles.org/docs/website/leaflet/ with Firefox 
 2. Click printing this page in Firefox
 3. Select print to PDF

### Expected Behavior
-> Showing the map in the pdf

### Actual Behavior
-> showing white/grey where the map should be

Anyone else who is having this behaviour? Thank you for any help!

**Comment by andrewharvey** [comment]
You might need to enable `preserveDrawingBuffer` as a [map option](https://docs.mapbox.com/mapbox-gl-js/api/map/#map-parameters) for this, could you try and see if that solve this?

**Comment by JanLoebel** [comment]
@andrewharvey Thank you so much, enabled `preserveDrawingBuffer` and it worked also in the Firefox browser. Wired that it seems it's the only one needing this option. Thank you!
