### ISSUE TITLE
Get the difference of background from Api Mapbox-gl (ex: position of state/county label)

### ISSUE THREAD

**Issue by dlcd2203** [mapbox/mapbox-gl-js#9817]
**mapbox-gl-js version**:1.9.1

### Question:
My website used Mapbox-gl and  storybook to render the image to check the difference.
**My issue:**  I see the difference of mapbox renderer via the position of state/county label  every few weeks. And I did not change any style of mapbox.
How to I avoid this.
![difference](https://user-images.githubusercontent.com/5329091/85529229-0ade0380-b637-11ea-98db-59db46384d9c.png)

Please find in attachment files. The pink label perform the difference of label position

**Comment by asheemmamoowala** [comment]
@dlcd2203 Thank you for using Mapbox-GL-JS. These types of minor differences can occur for many reasons: changes to the underlying tiles, change to screen size/position, rendering on different device among others.

The [pixelatch](https://github.com/mapbox/pixelmatch) library is a good tool to compare images accounting for small difference. This is what the tests for GL-JS use as well.
