### ISSUE TITLE
Style spec expressions migrator produces invalid expression for categorical function

### ISSUE THREAD

**Issue by dereklieu** [mapbox/mapbox-gl-js#9822]
**style-spec version**: `13.13.1`

**browser**: n/a

### Steps to Trigger Behavior

This is my test case. This style validates with no errors.

[legacy-style.json.zip](https://github.com/mapbox/mapbox-gl-js/files/4826754/legacy-style.json.zip)

```
{
  "version": 8,
  "name": "test",
  "sources": {
    "composite": { "url": "mapbox://foo.bar", "type": "vector" }
  },
  "layers": [
    {
      "id": "test",
      "type": "symbol",
      "source": "composite",
      "source-layer": "test",
      "layout": {
        "icon-image": {
          "base": 1,
          "type": "categorical",
          "property": "FOO",
          "stops": [["T0", "T0"], ["T1", "T1"], ["T2", "T2"]]
        }
      },
      "paint": {}
    }
  ]
}
```

Running this style through the `migrate` function produces the following:

```
{
  "version": 8,
  "name": "test",
  "sources": {"composite": {"url": "mapbox://foo.bar", "type": "vector"}},
  "layers": [
    {
      "id": "test",
      "type": "symbol",
      "source": "composite",
      "source-layer": "test",
      "layout": {
        "icon-image": [
          "match",
          ["get", "FOO"],
          "T0",
          "T0",
          "T1",
          "T1",
          "T2",
          "T2",
          null
        ]
      },
      "paint": {}
    }
  ]
}

```

This style validates with one error:

`layers[0].layout.icon-image[8]: Expected resolvedImage but found null instead.`

Looks like this categorical function is being migrated to a match expression with an invalid fallback value.

**Comment by dereklieu** [comment]
I should have some time to look into this next week. This feature is elevated for us as it features prominently in an upcoming Studio release.

**Comment by samanpwbb** [comment]
I believe this was fixed by https://github.com/mapbox/mapbox-gl-js/pull/10060/files - the fallback will now be an empty string instead of null.
