### ISSUE TITLE
AttributionControl misses updates

### ISSUE THREAD

**Issue by blq** [mapbox/mapbox-gl-js#9824]
Updating custom attributions is missed if the source layer is not initially visible. 

This codepen https://codepen.io/blqute/pen/PoZjbpp illustrates it (based on https://docs.mapbox.com/mapbox-gl-js/example/wms/ )
Only changes: 
1) I added a custom attribution to the source ("nj.gov")
2) added minzoom=10 to the layer to make it initially hidden (appear after couple of zoom ins)

=> the custom attribution is never shown. 
Comment out "`minzoom`" and the attribution shows.

Checking the code I think the `AttributionControl:onAdd/onRemove` methods need to nudge `_updateAttributions` also on "`moveend`" event, otherwise an initially hidden attribution never get's a chance to appear.

Sizing: needs investigation

**Comment by mourner** [comment]
Thanks a lot for the report! I've attempted to fix this in #9943 — check it out.

**Comment by blq** [comment]
Seems to work! 
But.. now I want more ;) Ideally I think attributions should match whats actually visible on the screen, regardless of expressions. If you have several overlays or sources spread across the globe, you'd like the ones not visible to not show attribution.
That's how Google maps does it for example, local map data providers' attributions only show for the local area.
Is that feasible to add you think?
