### ISSUE TITLE
Custom Markers not showing on map when used with Angular?

### ISSUE THREAD

**Issue by jeprince** [mapbox/mapbox-gl-js#9828]
**mapbox-gl-js version**: 1.11.0

### Why, when Using Mapbox with Angular, markers are not showing when using a custom HTML element?
 
I followed [this guide](https://docs.mapbox.com/help/tutorials/custom-markers-gl-js/), and many others but I cannot get a custom marker to show up in an Angular Project. It works fine in a normal [HTML website]( https://codepen.io/jeprince/pen/bGErgLQ) but not in Angular.

I created a sample [StackBliz site](https://stackblitz.com/edit/angular-ivy-rbry3a) to show what I mean.

**Comment by ryanhamley** [comment]
Hi @jeprince in your example, you're not supplying the custom marker to the `Marker` constructor. Once you do that, you can inspect the page to see that the element is being added to the map as expected. For whatever reason, the CSS is not being applied properly so it has no height, width, background color, etc. That's not an issue with GL JS though. If you can figure out why Angular isn't properly applying your CSS, you should be good to go.

Please note for the future that this issue tracker is for reporting bugs and requesting features in GL JS. We aren't typically able to resolve bugs that only manifest themselves in frameworks so for help with those issues or general how-to questions, we recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks for using Mapbox!

**Comment by jeprince** [comment]
> you're not supplying the custom marker to the `Marker` constructor.

I know... but if I add the custom marker doesn't appear on the map, hence me asking this. I don't know how mapbox is loaded into Angular exactly and why it is ignore my CSS for that component.

**Comment by ryanhamley** [comment]
I'm not sure either but it's not a bug in GL JS. It's likely something wrong with the particular implementation of Angular. Mapbox has a great [support team](https://support.mapbox.com/hc/en-us) that can help you get up and running though.
