### ISSUE TITLE
`line-width` does not interpolate between some function values

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#983]
I can't figure out exactly what the issue is, but I have a style with this width constant:

```
"@street-width": {
      "base": 1.4,
      "stops": [
        [
          13,
          0
        ],
        [
          14,
          10
        ],
        [
          20,
          20
        ]
      ]
    },
```

And it is assigned to both the `line-width` of a road layer, and the `line-gap-width` of a road casing layer. The `line-gap-width` of the road casing layer interpolates between all three stops in the function, but the `line-width` of the road layer doesn't seem to interpolate between the first two stops (it switches values once it hits the second stop):

![line-width-function](https://cloud.githubusercontent.com/assets/5607844/6115893/ec6c9dce-b076-11e4-9b7b-56e0e4bfa5d7.gif)
 

I've tried changing the values (e.g. making the first stop a non-zero number), but it doesn't seem to make a difference.

**Comment by jfirebaugh** [comment]
Traced this to a style bug (differing `minzoom` values for the fill and casing).
