### ISSUE TITLE
[Ionic Angular] map.loadImage(): Could not load image because of Cannot read property 'map' of undefined.

### ISSUE THREAD

**Issue by iMeteox** [mapbox/mapbox-gl-js#9831]
I'm using mapbox-gl-js in an Ionic Angular(v6.8.0) project. Whenver I call the function 'map.loadImage()', whether it's when I click on a button or in a lifetime function like "ngOnInit", an error is thrown (see "Actual Behavior" below). Other than that, MapboxGL JS is behaving as intended in my project.

**mapbox-gl-js version**: 1.10.1

**browser**: Google Chrome

### Steps to Trigger Behavior

 1. Generate an empty Ionic Angular project. Install mapbox-gl-js into it.
`ionic start myApp blank`
`npm install mapbox-gl --save`

 2. Use this as the content of home.page.html:
`<div id='map'></div>`

 3. This pastebin should be the content of home.page.ts. Most of the code has been taken from a MapboxGL JS example:
https://pastebin.com/zrxY7bwW

 4. Use the following command to launch the application:
`ionic serve`

### Expected Behavior
The image is loaded and added to the map.

### Actual Behavior
The following error is thrown at mapbox-gl.js, line 31;
`Uncaught (in promise): Error: Could not load image because of Cannot read property 'map' of undefined. Please make sure to use a supported image type such as PNG or JPEG. Note that SVGs are not supported.
Error: Could not load image because of Cannot read property 'map' of undefined. Please make sure to use a supported image type such as PNG or JPEG. Note that SVGs are not supported.`

I'm assuming this could be a scope issue, but I could very much be wrong.

**Comment by ryanhamley** [comment]
>I'm assuming this could be a scope issue

Hi @iMeteox you are correct. Based on the error message, it seems the value of `this` within the `loadImage` callback is no longer the outer class where `map` is defined. You can work around this by [binding `this`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Function/bind) to the correct scope or saving `this.map` into a variable declared in the outer scope. If you need further help, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us).

**Comment by iMeteox** [comment]
Thank you so much, I'm not used to Angular and Javascript scopes, but it worked. For anyone encountering the same problem, the simple solution is the following;

In the home.page.ts, you should define a variable that is going to hold the value of "this" (your component) in the function in which you desire to load the image. When loading the image,  you should use that variable (line 54-55), to call your map object instead of "this".

My problem is fixed, my anxieties are gone, and I will go to sleep a smarter programmer than I was the previous day. Thank you once again!
