### ISSUE TITLE
error: Branch labels must be unique

### ISSUE THREAD

**Issue by radhikavm** [mapbox/mapbox-gl-js#9832]
**mapbox-gl-js version**: 1.10.1

### Question

Hello,
I am getting this error: layers.postcodes.filter[2]: Branch labels must be unique. I am using match expression :
map.setFilter('postcodes', ['match', ['get', 'name'], highlighting, true, false]);

I may be probably missing something obvious but can some please explain what exactly does that mean with reference to the above context.

### Links to related documentation

[https://github.com/mapbox/mapbox-gl-js/pull/7662](https://github.com/mapbox/mapbox-gl-js/pull/7662)

**Comment by mourner** [comment]
Without full code it's hard to tell for sure, but I would guess that the variable `highlighting` from above is an array that contains duplicate values (e.g. `["foo", "foo"]`). Make sure the values are unique.
