### ISSUE TITLE
AddImage/AddLayer - hides other layers on zoom even when "insertBeforeID" option is used

### ISSUE THREAD

**Issue by ostapski** [mapbox/mapbox-gl-js#9833]
I have a problem with runtime added marks - when a mark (an image) is added at runtime - it hides the country name (at some zoom) - when zooming in - country name will appear ...eventually

To solve it - I went onto a search spree ...to find out how to solve it ... found it (so i thought) - 
the second parameter of the "addLayer" function where one can specify before what ID should it go ...done that ...Great ...country name is there ...
and half of the marks are gone :) ... zooming in ....some of the marks start to show ...then again disappear the closer you zoom in. 

Basically:

> - if runtime layers inserted BEFORE some "symbol" layers .. - they will be hidden on zoom by newly activated layes...that fit the zoom condition 
> - If runtime layers inserted above all - they are always visible - but will hide some text layers 
> 

anyway ...
I tried to limit the size of image (in order to limit overlapping issue) - and found NO OPTION FOR IT ...???? 
ok
I searched for Layer size limit - NO OPTION FOR IT ??? ...
WHY ????
The only option i've found is - **"icon-size"**: ... which is a scale option ...(very confusing !!!)

**mapbox-gl-js version**:
1.11.0

**browser**:
Not Chrome

### Steps to Trigger Behavior

 1. Create a map with text layers (country names , cities ...etc)
 2. OnLoad - insert few markers BEFORE statically defined text layers (as the docs suggest) - thus ..scan through them all - find the last one ...or first one ...NO MATER !!!
 3. See that you can see them all from starting zoom ...and during zoom in / out 

### Link to Demonstration

https://42amsterdam.net/mapbox_test.php

### Expected Behavior

Mark Images should be visible at all time - at all zoom levels !!! Not hiding other layers
Added Image Layers should not hide other layers (its an PNG ... how is it possible 10x20 semi-transparent image overlap a whole country ?)
Image should have a size !!! (one of them ..the image or the layer.. you choose)
Layer!! should have a position (coordinates) ... not the "Source" ...because layers are linked to the source ...with the current logic - i need to add multiple (similar) sources ...but at different location - and link a layer to it 
It would be way better to create single image - and link whatever layer ...at whatever position ...to it !!!

### Actual Behavior

as described above ↑

**Comment by mourner** [comment]
It's very hard to understand what's going on from this description and the demo (which currently only shows a bunch of markers without a base map), but I risk taking a guess that the options you're looking for are [icon-allow-overlap](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-icon-allow-overlap) and/or [icon-ignore-placement](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-symbol-icon-ignore-placement). 

Also, I strongly suggest not adding a separate source/layer per a single marker — all of these symbols can be represented as a single layer with a collection of features as a source, with an icon chosen based on a feature property, like [in this example](https://docs.mapbox.com/mapbox-gl-js/example/popup-on-click/).
