### ISSUE TITLE
Input data is not a valid GeoJSON object.

### ISSUE THREAD

**Issue by Aiamjay** [mapbox/mapbox-gl-js#9835]
**mapbox-gl-js version**:

### Question
Hi, I tried to follow the guide from your website: https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-line-line-color. Everything is the same, but when I ran, I get an error: Input data is not a valid GeoJSON object.

**Comment by manelbrioude** [comment]
did you find a solution?
