### ISSUE TITLE
Real time updates with setBearing and setCenter: manual map events (pan / zoom) not working anymore after update from 1.8.1 to 1.10.1

### ISSUE THREAD

**Issue by methodus** [mapbox/mapbox-gl-js#9836]
**mapbox-gl-js version**: 1.10.1

### Question

I created a custom user location dot, which is animated in real time using requestAnimationFrame based upon the example from here: https://docs.mapbox.com/mapbox-gl-js/example/live-update-feature/

Since upgrading from 1.8.1 to 1.10.1 the code below does not work anymore. When code updates the map bounds (center and bearing) it is not possible anymore to move or zoom the map. Obviously, the number of events, which are sent drop the events coming from the user. So, if I reduce the number of update interval to 500ms, I am able to move the map, but the dot is then jerky.

The function below uses the additional event data to disable the automatic map movements, when the user moves the map. The function onMoveStart is registered via this.map.on('movestart',...). But the event is not coming through. I only receive the map events, when I disable the map updates by setting the lock state to PositionLockState.UNLOCKED for instance via button.

Any suggestions?

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/example/live-update-feature/

### Code

```
private animateUserPosition(timestamp: DOMHighResTimeStamp) {
    const delta_t = timestamp - (this.animationTimestamp || 0);

    // Request new frame
    this.userAnimationId = requestAnimationFrame((timestamp) => this.animateUserPosition(timestamp))

    if (this.animationTimestamp && delta_t < 33) {
      return
    }

    if (!this.markerInstance) {
      return
    }

    this.animationTimestamp = timestamp

    let lat = 0; let lng = 0;
    let interval_t = 1
    const coords = this.markerInstance.getLngLat()

    const delta_s = delta_t / 1000

    if (coords) {
      lat = coords.lat
      lng = coords.lng
      interval_t = Math.max(Math.min(delta_s, 0.20), 0.033) * 2
    }

    const [posLng, posLat] = this.position.geometry.coordinates

    const diff_X = posLat - lat; //latitudes
    const diff_Y = posLng - lng; //longitudes

    const coord_X = interval_t * diff_X + lat
    const coord_Y = interval_t * diff_Y + lng

    const diff_accuracy = this.position.properties.accuracy - this.accuracy
    const new_accuracy = interval_t * diff_accuracy + this.accuracy

    this.accuracy = new_accuracy

    this.accuracySize = Math.max(this.pixelValue(coord_X, new_accuracy, this.map.getZoom()), DEFAULT_ACCURACY_SIZE)

    if (this.positionLockState >= PositionLockState.BEARING_LOCKED && this.map) {
      const diff_h = this.shortAngleDist(this.userHeading, this.position.properties.heading); // heading
      const heading = interval_t * diff_h + this.userHeading

      this.map.setBearing(heading, GeolocateSource)

      this.userHeading = heading
    }

    if (this.positionLockState >= PositionLockState.POSITION_LOCKED && this.map) {
      this.map.setCenter([coord_Y, coord_X], GeolocateSource)
    }

    this.markerInstance.setLngLat([coord_Y, coord_X])
  }

...

  onMoveStart(event: any) {
    if (!event.geolocateSource) {
      this.positionLockState= PositionLockState.UNLOCKED
    }
  }
```

**Comment by mourner** [comment]
Would you be able to provide a minimal live test case for the issue? It's a little hard to diagnose just looking at the code.
