### ISSUE TITLE
Question about customized marker

### ISSUE THREAD

**Issue by Aiamjay** [mapbox/mapbox-gl-js#9837]
**mapbox-gl-js version**:

### Question
Hi, I have a problem about customizing a marker. I create a div for a marker and then set svg as the background image of this div. The following code works:
<img width="1417" alt="Screen Shot 2020-07-03 at 7 27 54 PM" src="https://user-images.githubusercontent.com/13723721/86503473-4c6f5c80-bd63-11ea-9a9b-310c846854b5.png">
<img width="705" alt="Screen Shot 2020-07-03 at 7 28 06 PM" src="https://user-images.githubusercontent.com/13723721/86503476-56915b00-bd63-11ea-921b-fa760d547236.png">

But when I add a style to the path inside the svg, I get nothing. 
<img width="1525" alt="Screen Shot 2020-07-03 at 7 23 10 PM" src="https://user-images.githubusercontent.com/13723721/86503470-44afb800-bd63-11ea-8f01-b38d8345cfe2.png">

**Comment by mourner** [comment]
Can you provide a link to a minimal live test case demonstrating the issue? It's impossible to see what may be the issue here otherwise, but it's likely not related to GL JS itself.

**Comment by Aiamjay** [comment]
Solved, I cannot use '' '' in `` expression.
