### ISSUE TITLE
Is it possible to use generic icons in layers?

### ISSUE THREAD

**Issue by elC0mpa** [mapbox/mapbox-gl-js#9839]
**mapbox-gl-js version**: 1.11.0

### Question
```javascript
myLayer: {
        id: 'layerId',
        type: 'symbol',
        source: 'source-id',
        layout: {
          'icon-image': 'lar la-star'
        }
      }
```
I want to use a project icon to represent a layer, the thing is that I can use these icons outside the map and even to change the default markers slot, but if I try to add them in this map, it raises the next warning

> Image "lar la-star" could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event

I would like to know what are 'sprite' properties in the style and if there is a way I can achieve this using layers and sources bacause with markers it is pretty simple

### Links to related documentation
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#symbol

**Comment by mourner** [comment]
As the error suggests, you would have to use the `addImage` API to add any additional icons for use by symbol layers that are not already present in the style. See example here https://docs.mapbox.com/mapbox-gl-js/example/add-image/
