### ISSUE TITLE
draw_background is trying to draw an object, rather than a color array

### ISSUE THREAD

**Issue by lbud** [mapbox/mapbox-gl-js#984]
In `master`:
[This line](https://github.com/mapbox/mapbox-gl-js/blob/master/js/render/draw_background.js#L75) should be passing an array to the draw call as `color`, but is as of recently passing a color object and erroring:
![image](https://cloud.githubusercontent.com/assets/3170312/6116345/d7b0d762-b060-11e4-93c1-11ae4cce7ea8.png)
![image](https://cloud.githubusercontent.com/assets/3170312/6116357/f52feea4-b060-11e4-992f-7f27a9373b9d.png)

**Comment by ansis** [comment]
Is your style spec up to date?

**Comment by lbud** [comment]
Ah, good catch — it was locally linked to an outdated version. I need to write something into my bash profile to update all 1000 relevant repos at once : \
