### ISSUE TITLE
How to Modify Tile Data ? (callback or any structure to decode my tile data)

### ISSUE THREAD

**Issue by MostafaSh** [mapbox/mapbox-gl-js#9840]
**summery ->** 
in our company, we use our  own tile servers. we encode both tile-urls and Tile data in some way for protecting our data. 
now, we are going to start using mapbox-gl in our webApps.

**problem ->**
 I cannot find the callback or any solution to modifying each tile data after they've got fetched. it seems there is no solution defined in docs or forums.

**what I am seeking for ->**
if there is any solution defined already, please leave a sample or the address to it's doc for me.
if there is no solution, is there any upcoming  release of mapbox-gl wich provides any solution for my problem? if there is, is there any timing for it?

**Comment by mourner** [comment]
There's currently no way to do that directly through the API — you'll either have to modify the source code, or try an undocumented custom sources API discussed in #2920. Unfortunately we have no timeline for improvements on that front at the moment.
