### ISSUE TITLE
whole world at once in portrait view?

### ISSUE THREAD

**Issue by dieterdreist** [mapbox/mapbox-gl-js#9842]
**mapbox-gl-js version**:1.10.1

### Question
Is it possible to show the whole world on a phone in portrait orientation? Currently I can't zoom out more as when the map covers the available screen height, but I would rather have it cover the whole width only (i.e. have blank areas on top and below, see the whole world on one screen).

**Comment by mourner** [comment]
This is currently not possible with GL JS unfortunately. Some prior discussion on this can be found in #3055.
