### ISSUE TITLE
Satellite tiles 404 not found when map is zoomed in on some areas

### ISSUE THREAD

**Issue by beshad** [mapbox/mapbox-gl-js#9845]
i am having problem when using Satellite street view. map view becomes blurry with missing tiles and console errors:

`VM1511:1 GET https://api.mapbox.com/v4/mapbox.satellite/17/129562/81256.webp?access_token=pk.eyJ1Ixxxg 404 (Not Found)`

![Screen Shot 2020-07-06 at 3 12 25 PM](https://user-images.githubusercontent.com/14914745/86635659-79ec2c80-c027-11ea-93ff-cad507580433.png)

visual blurry tiles disappear when zoomed out, normally after zoom level around 10 and i noticed this mostly exists on remote regions. is this an issue with this library not having proper tile Ariel imagery for this region or maybe i am doing something wrong?

![image](https://user-images.githubusercontent.com/14914745/86635849-bae44100-c027-11ea-9962-e646df0446d3.png)

thanks

**Comment by mourner** [comment]
Yes, this is most likely about not having coverage for higher zoom levels in some remote areas. But in any case, I'd contact support about this — it's not an issue with GL JS specifically.
