### ISSUE TITLE
Update style spec docs for mobile SDK support

### ISSUE THREAD

**Issue by chloekraw** [mapbox/mapbox-gl-js#9847]
I was looking through the style spec docs and there may be a few mobile version numbers missing from the style spec docs for features that are now supported:

- Android: https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-fill-extrusion-fill-extrusion-vertical-gradient
- iOS: https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#is-supported-script
- Android and iOS: https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#types-number-format
- Android and iOS: https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#accumulated

Let's confirm whether these properties/expressions are supported and if so, which SDK version first added support for them.

cc @mapbox/maps-android @mapbox/maps-ios

**Comment by Chaoba** [comment]
Android:

- fill-extrusion-vertical-gradient: 7.0.0

- number-format: 8.4.0

- accumulated: 8.4.0
