### ISSUE TITLE
Can customlayer support threejs shadow

### ISSUE THREAD

**Issue by qkaibo** [mapbox/mapbox-gl-js#9848]
add shadow in mapbox default example
https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/

But it didn't work.  can customlayer support threejs shadow?

**Comment by mourner** [comment]
This is a place to report issues with GL JS — unfortunately we don't have team bandwidth to answer ThreeJS-related questions.

**Comment by jscastro76** [comment]
I think I have resolved this quite old ([almost historic in Stackoverflow I'd say](https://stackoverflow.com/questions/58243572/unable-to-cast-a-shadow-with-three-js-and-mapbox-gl)) and requested demand... Glad to help to modify the [example](https://docs.mapbox.com/mapbox-gl-js/example/add-3d-model/) with a pull request if you are interested @mourner 
![MapboxShadow](https://user-images.githubusercontent.com/38470852/89126379-88721a80-d4e5-11ea-994b-eee1122e2a39.gif)
