### ISSUE TITLE
New Event: Geolocation Off

### ISSUE THREAD

**Issue by jmunowitch** [mapbox/mapbox-gl-js#9853]
## Motivation

When a user turns on Geolocate, they are centered on their location. 

When a user turns off Geolocate, we would like to opportunity re-center on the customer's data, which may not be close to their current location.

**Comment by mourner** [comment]
`GeolocateControl` produces an `error` event. You can subscribe to it with `control.on('error', (e) => { ... })`, and interpret [according to the spec](https://w3c.github.io/geolocation-api/#position_error_interface).
