### ISSUE TITLE
Sprite property in Style / Adding custom images

### ISSUE THREAD

**Issue by jordymeow** [mapbox/mapbox-gl-js#9854]
Hello,

Previously, I was using _loadImage_ + _addImage_ to dynamically add my custom icons to a layer, but that was slowing-down the loading of the map tremendously.

Since I am always using the same icons, I decided to upload them using the MapBox SDK. I did a script for that, I named them correctly, and I can see those icons when I am loading the file directly. When I visit MapBox Studio, I can visit that style, and download it. My icons can be found in the zip bundle, under the right names.

However, when I am checking which images have been loaded using _listImages()_, I don't see them, and they are definitely missing since I am getting this error for all of them:

_Image [...] could not be loaded. Please make sure you have added the image with map.addImage() or a "sprite" property in your style. You can provide missing images by listening for the "styleimagemissing" map event._

I had a look in the file being loaded as my MapBox style (which is the one I designed using MapBox Studio, and which I used also for the upload of the images), and I can see something like this:

`"sprite":"mapbox://sprites/[myaccount]/[A]/[B]"`

"A" is exactly the same as my Style ID. However, I have no idea what "B" is, where it comes from, and how it was set. I had a look in the style.json file downloaded from Studio and indeed, "B" is different in it. I have no idea where and how this is set up and I can't find any information about it.

Can anybody help, or give me pointers? Thanks a lot :)

**Comment by arindam1993** [comment]
Hey @jordymeow , we use the issue section here for bug and feature discussions, stackoverflow or mapbox's support team are better avenues for queries like this.
