### ISSUE TITLE
How can I draw symbols in the following image using mapbox apis

### ISSUE THREAD

**Issue by Aiamjay** [mapbox/mapbox-gl-js#9855]
**mapbox-gl-js version**:

### Question
I'm currently transferring googlmap to mapbox. I'm wondering how can I draw symbols in the following image using mapbox apis. The two NPC cars in mapbox in the pic.
<img width="570" alt="Screen Shot 2020-07-07 at 11 45 04 AM" src="https://user-images.githubusercontent.com/13723721/86827979-83858c80-c047-11ea-8677-a23d9d05415f.png">

**Comment by mourner** [comment]
Please check out all the icon-related examples by entering "icon" in the search field on our examples page: https://docs.mapbox.com/mapbox-gl-js/examples/

**Comment by Aiamjay** [comment]
I tried to use icon to draw things, but when using icon, how could I change capacity and border line width?
