### ISSUE TITLE
How to label a marker in MapBox

### ISSUE THREAD

**Issue by Aiamjay** [mapbox/mapbox-gl-js#9858]
**mapbox-gl-js version**:

### Question
Hi, I'm a map developer of map-based application. I need to label a marker in mapbox. I use the following code to create a customized marker.
<img width="947" alt="Screen Shot 2020-07-07 at 7 29 16 PM" src="https://user-images.githubusercontent.com/13723721/86867752-3aa1f800-c088-11ea-8ae3-04b21c2c1650.png">

It works like that:
<img width="627" alt="Screen Shot 2020-07-07 at 7 31 27 PM" src="https://user-images.githubusercontent.com/13723721/86867882-776def00-c088-11ea-8091-924891129e44.png">
<img width="304" alt="Screen Shot 2020-07-07 at 7 32 43 PM" src="https://user-images.githubusercontent.com/13723721/86867979-a8e6ba80-c088-11ea-981a-01cd8830aa45.png">

Now I need to label the marker, could you please tell me how to do this? Great thanks! 🙏😊

**Comment by andrewharvey** [comment]
Could either be done as:

1. A symbol layer
2. A popup
3. Part of the HTML Marker element

**Comment by mourner** [comment]
@Aiamjay GitHub issues in this repo are meant for either bug reports or feature requests. For questions, please use StackOverflow or contact Mapbox support.
