### ISSUE TITLE
How to add a map style offline on Mapbox gl?

### ISSUE THREAD

**Issue by Georger2323** [mapbox/mapbox-gl-js#9861]
When declaring a map object, a style has to be defined in the form of a link (e.g mapbox://styles/mapbox/satellite-streets-v11).

My question is, is it possible to create my own style at mapbox studio, download it and then provide the path of the folder instead of the public link? Or is there any other way it can be done offline?

**Comment by Georger2323** [comment]
I've just realized that I just have to provide the path of the .json file

**Comment by mourner** [comment]
You can inline the style JSON in place of the URL. However it will still need to access API endpoints for tiles, fonts, etc. Covering offline capabilities out of the box is out of scope for GL JS.
