### ISSUE TITLE
map.setPaintProperty  expression  decision ==

### ISSUE THREAD

**Issue by coffee-gh** [mapbox/mapbox-gl-js#9862]
```
map.setPaintProperty('layerId', 'line-color', [
      'match',
      ['get', 'line-id'],
      1, '#00C0C0',
      2, '#006666',
     '#ffffff' //property : line-id ===3  line-id ===4 ,line-color all set to '#ffffff' value
    ]);
```
If there is a match like expression, I just want to change the color property  line-id  ===1 in the property of many layers

eg：
```
map.setPaintProperty('layerId', 'line-color', [
      '==',
      ['get', 'line-id'],
      1, '#00C0C0'
    ]);
```
to set the color property '#00c0c0' ,whick line-id === 1 ,
it doesn't works? Thank you

**Comment by mourner** [comment]
Can you please rephrase the question? I don't follow what you're trying to achieve.

**Comment by coffee-gh** [comment]
> Can you please rephrase the question? I don't follow what you're trying to achieve.
eg:
map.addLayer({
  id: 'layerId',
  type: 'line',
  source: {
    type: 'geojson',
    data: {
      type: 'FeatureCollection',
      features: [
        {
          type: 'Feature',
          geometry: {
            type: 'LineString',
            coordinates: [
              [111, 21],
              [112, 33],
              [113, 40],
            ],
          },
          properties: {
            'line-id': 1,
          },
        },
        {
          type: 'Feature',
          geometry: {
            type: 'LineString',
            coordinates: [
              [110, 40],
              [112, 39],
              [113, 24],
            ],
          },
          properties: {
            'line-id': 2,
          },
        },
      ],
    },
  },

  paint: {
    'line-color': '#fff000',// default value
  },
});

map.setPaintProperty('layerId', 'line-color', [
  'match',
  ['get', 'line-id'],
  1,
  '#00C0C0', // I just want to change line-color where line-id === 1 in properties
  '#99CCFF', //and other  line-color all set to '#99CCFF' value.I don't want to change line-color where line-id === 2  in  properties
]);

I just want to change line-color where line-id === 1 in properties
and other  line-color all set to '#99CCFF' value.I don't want to change line-color where line-id === 2  in  properties


Is there any expression  to achieve ?
thank you

**Comment by mourner** [comment]
@coffee-gh no, it's not technically possible — all features are re-evaluated when you change the paint property of a layer. You would have to combine all the values for a layer in a single expression (e.g. a `match` or a `case` expression with both colors defined). Alternatively, if you want a fast way to update a single feature (e.g. for hover), use the `feature-state` API, e.g. like in this example https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/
