### ISSUE TITLE
Warning in browser console about missing CSS declarations

### ISSUE THREAD

**Issue by ericmorand** [mapbox/mapbox-gl-js#9869]
When using mapbox-gl with the following initialisation code:

```js
const map = new mapboxgl.Map({
            container: host,
            style: 'mapbox://styles/mapbox/streets-v11', // stylesheet location
            center: [6, 46.2], // starting position [lng, lat]
            zoom: 9, // starting zoom
            accessToken: accessToken
        });
```

The following warning is displayed in the browser console:

> This page appears to be missing CSS declarations for  Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/.

We don't want to use the CSS you provide to us. We only use custom CSS for everything we code. This warning falsely worry our customers about an error on our delivery.

**Comment by andrewharvey** [comment]
This warning is triggered by the lack of:

https://github.com/mapbox/mapbox-gl-js/blob/fc7ac016bed5595a9783d82468a5a139196f2a96/src/css/mapbox-gl.css#L19-L21

If you're not using the mapbox-gl.css and instead using 100% your own CSS you can include the above CSS for the canary which would stop the warning.

I think it's reasonable for this warning to be present as most people would be using the library with the provided CSS and this warning helps catch cases where that CSS isn't included.

**Comment by ericmorand** [comment]
> I think it's reasonable for this warning to be present as most people would be using the library with the provided CSS and this warning helps catch cases where that CSS isn't included.

Well, it is reasonable if you assume that most people don't read the documentation. Which is why I think it is not reasonable. People who read the documentation and decide to not use the included CSS are the one penalized, while people not reading the documentation are cherished with a warning in the console.

Anyway, thanks for the solution.

**Comment by mourner** [comment]
> People who read the documentation and decide to not use the included CSS are the one penalized

It's reasonable to expect a warning in the console for people who don't use the library in the way intended by the developers. Also, not including the CSS is a common mistake even if you do read the docs — I'm not an exception to this myself.

**Comment by andrewharvey** [comment]
> Also, not including the CSS is a common mistake even if you do read the docs — I'm not an exception to this myself.

and hopefully https://github.com/mapbox/mapbox-gl-js-docs/pull/356 would help too :wink:

**Comment by ericmorand** [comment]
@mourner 

> It's reasonable to expect a warning in the console for people who don't use the library in the way intended by the developers.

Why would the developers intention be that we use _their_ stylesheet? That they provide a stylesheet as convenience is great, and it's very nice from them, but I don't understand why they would want to enforce consumers of the library to use _their_ stylesheet.

The doc should say "For convenience, we provide a starter stylesheet in the package and/or the following CDN url". And not enforce anything.

**Comment by andrewharvey** [comment]
> Why would the developers intention be that we use their stylesheet? That they provide a stylesheet as convenience is great, and it's very nice from them, but I don't understand why they would want to enforce consumers of the library to use their stylesheet.

My 2c on this is the stylesheet is not optional it's a core part of the library, the library is not designed to work without it. It doesn't just contain design but also functionality. Extending the style with your own on top of the provided CSS is usually better, but if you're going to use 100% your own then there are some bare minimum CSS that needs to be provided for the library to work as intended, and the canary is one of them.

**Comment by ericmorand** [comment]
> the library is not designed to work without it

I surely hope you're wrong. CSS is at the rendering layer whil JS is at the behavior one. If the JS layer is dependent on the CSS layer, then the library is flawed at its core.

From my experience with the lib, there is no dependency between the two layers, which is great. Just the warning.

**Comment by mourner** [comment]
> I surely hope you're wrong. CSS is at the rendering layer whil JS is at the behavior one. If the JS layer is dependent on the CSS layer, then the library is flawed at its core.

Without the included CSS, the core rendering engine continues to work. However, the whole UI layer, which includes attribution, logo (required to adhere to Mapbox & OSM terms of conditions), navigation, scale, geolocation & scale controls, markers, popups, cursors, box zoom, etc., will not work. This UI layer is not a part of a "recommended starter stylesheet", it's a part of the core experience.

If you thing this is a flaw, that's fine, but a gentle reminder that this project follows a [code of conduct](https://github.com/mapbox/mapbox-gl-js/blob/main/CODE-OF-CONDUCT.md), and derogatory tone towards maintainers of the project will not be tolerated.

**Comment by ericmorand** [comment]
> Without the included CSS, the core rendering engine continues to work. However, the whole UI layer, which includes attribution, logo (required to adhere to Mapbox & OSM terms of conditions), navigation, geolocation & scale controls, markers, popups, cursors, box zoom, etc., will not work.

With all due respect, they work as expected. We have a fully functioning UI with our own stylesheet - zoom, markers, popup, etc - and even the required logo. I understand your point but I think we don't agree on the definition of the term "required". The stylesheet is definitely required if one want an out-of-the-box working map. But it is possible to have a perfectly working map without the recommended stylesheet. Thus it makes this stylesheet, by definition, _not_ required.

About the code of conduct, I'm sorry if my tone may sound derogatory. It's by no mean deliberate.

**Comment by andrewharvey** [comment]
> With all due respect, they work as expected. We have a fully functioning UI with our own stylesheet - zoom, markers, popup, etc - and even the required logo.

Then you must have copied across all the the required bits from the included CSS, everything except for the required canary (which you now have).

> I understand your point but I think we don't agree on the definition of the term "required". The stylesheet is definitely required if one want an out-of-the-box working map. But it is possible to have a perfectly working map without the recommended stylesheet. Thus it makes this stylesheet, by definition, not required.

I think it's just semantics, it's still required for the UI but you've modified it into your own, and so long as you include all the required bits it'll work, though not a "supported" use case. Same way if you modified some of the JS code, it may well still work but more once you do this, you "void you warranty". Again all just my personal opinion here.

**Comment by ericmorand** [comment]
@andrewharvey , we didn't copy anything, we didn't even doanloaded the provided stylesheet. And I assume it is writtent in CSS so it would be of no use considering that our stylesheets are compiled from SASS. What we did was creating styles and markups for the required UI elements as we would for any other element of the page, and handle the events.

Amyway, I'll probably end up patching the library to remove that warning. Thanks for your support.
