### ISSUE TITLE
Error when adding multiple markers: "TypeError: undefined is not an object (evaluating 'i.leaf')" 

### ISSUE THREAD

**Issue by SupremumLimit** [mapbox/mapbox-gl-js#987]
I'm getting this error with v0.6.0 of the API. The error seems to appear when adding more than ~5 markers. Fewer is OK. 

I'm calling `setData` to update the source data: 

    @nodesSource.setData result

where `result` is, for example: 

    {"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[37.7057877,55.6262796]},"properties":{"id":3039917461}},{"type":"Feature","geometry":{"type":"Point","coordinates":[37.7060377,55.626321]},"properties":{"id":3039917464}},{"type":"Feature","geometry":{"type":"Point","coordinates":[37.7059759,55.6263631]},"properties":{"id":3039917465}},{"type":"Feature","geometry":{"type":"Point","coordinates":[37.7060175,55.6263652]},"properties":{"id":3039917466}},{"type":"Feature","geometry":{"type":"Point","coordinates":[37.7059352,55.6263683]},"properties":{"id":3039917467}},{"type":"Feature","geometry":{"type":"Point","coordinates":[37.7063512,55.6263728]},"properties":{"id":3039917468}},{"type":"Feature","geometry":{"type":"Point","coordinates":[37.7060558,55.6263744]},"properties":{"id":3039917469}},{"type":"Feature","geometry":{"type":"Point","coordinates":[37.7058994,55.6263804]},"properties":{"id":3039917470}}]}

**Comment by jfirebaugh** [comment]
@SupremumLimit Can you provide a JSFiddle?

**Comment by SupremumLimit** [comment]
Here is a JSFiddle: https://jsfiddle.net/dh227maf/1/

Press "Show nodes" and you'll see the error in the console. I get the error both in Safari and Chrome.
