### ISSUE TITLE
Is there any way to click on maker DOM without trigger map click event

### ISSUE THREAD

**Issue by Aiamjay** [mapbox/mapbox-gl-js#9872]
**mapbox-gl-js version**:1.11.0

**browser**: Chrome latest

### Steps to Trigger Behavior

 1. register click event on map using map.on('click', callback)
 2. register click event on marker dom using dom.addEventListener('click', callback)
 3. when clicked marker, triggered both map click event and marker click event

### Link to Demonstration

Code:
<img width="710" alt="Screen Shot 2020-07-13 at 6 38 27 PM" src="https://user-images.githubusercontent.com/13723721/87370544-15a1ff00-c538-11ea-91ac-446d661aaf00.png">

https://jsbin.com/

### Expected Behavior
When clicked marker, stop propagating click event to map  
### Actual Behavior
triggred both click events

**Comment by andrewharvey** [comment]
What if you add [stopPropogation](https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation) to your event?

eg.
```
marker.getElement().addEventListener('click', function (e) {
      e.stopPropagation();
    })
```

**Comment by ryanhamley** [comment]
This is the correct way to do this for now. There's an existing ticket (https://github.com/mapbox/mapbox-gl-js/issues/7793) for adding events like `click` directly to the Marker API but there's no timeline for that right now. Also note that for general support and "how to" questions, we recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us).

**Comment by Aiamjay** [comment]
Solved thank you

**Comment by michael-mml** [comment]
`stopPropagation()` also stops the event from bubbling to open any popups attached to the marker.

Not a great workaround imo.
