### ISSUE TITLE
Canvas sources sized in exact powers of 2 (e.g. 512x512) render as black squares

### ISSUE THREAD

**Issue by ryanhamley** [mapbox/mapbox-gl-js#9873]
**mapbox-gl-js version**: starting from v0.50.0

**browser**: all

### Steps to Trigger Behavior

 1. add a canvas source layer
 2. set the height and width to be an exact power of 2

### Link to Demonstration

https://jsfiddle.net/rsh412/2exz0ukh/3/

### Expected Behavior

https://jsfiddle.net/rsh412/wrtq3hpk/2/
<img width="664" alt="Screen Shot 2020-07-14 at 4 57 10 PM" src="https://user-images.githubusercontent.com/4523080/87487659-1a77b900-c5f3-11ea-8249-4df3741c959d.png">

### Actual Behavior
<img width="665" alt="Screen Shot 2020-07-14 at 4 58 50 PM" src="https://user-images.githubusercontent.com/4523080/87487728-4e52de80-c5f3-11ea-8207-69a54730a733.png">

The console shows many warnings `[.WebGL-0x7f9a73693000]RENDER WARNING: texture bound to texture unit 1 is not renderable. It might be non-power-of-2 or have incompatible texture filtering (maybe)?` for both `texture unit 1` and `texture unit 0`.

If you change the size of the canvas in the example from 256x256 to 256x257, the canvas renders as expected.

I tracked the introduction of the bug to https://github.com/mapbox/mapbox-gl-js/commit/4e926e37e997715b5479e73c468bfa67e47b87ae.

**Comment by ryanhamley** [comment]
cc @ansis

**Comment by Grooo** [comment]
Thanks!
I had been crazy all day with this mystery.

**Comment by kirrukirru** [comment]
Can we expect the resolution any time sooner? There is also some issue with applying transparency at the excess pixel added to workaround this issue.
![image](https://user-images.githubusercontent.com/11042757/108014194-5e241c80-7033-11eb-8c10-e04b2f474fd4.png)

**Comment by tavimori** [comment]
Debug for several nights and now I found this is an open issue...

**Comment by tavimori** [comment]
I found a workaround to this:

1. Initially set the canvas to a non-power-of-2 size. 
2. After Mapbox render it once, resize the canvas won't trigger the bug.

**Comment by SnailBones** [comment]
Same as https://github.com/mapbox/mapbox-gl-js/issues/11132, fixed by https://github.com/mapbox/mapbox-gl-js/pull/11162
