### ISSUE TITLE
NPM Package Unpacked Size 30.7 MB

### ISSUE THREAD

**Issue by jpswade** [mapbox/mapbox-gl-js#9878]
The size of this npm package is pretty ridiculous.

[![install size](https://packagephobia.com/badge?p=mapbox-gl)](https://packagephobia.com/result?p=mapbox-gl)

**Comment by mourner** [comment]
@jpswade would you like to educate us on what part of the NPM package should be removed? Source maps? Development build? A build for CSP-restricted environments? Source with flow types? The style spec bundle? Or maybe some particular features of GL JS itself? We'll be happy to hear your constructive suggestions.

**Comment by jpswade** [comment]
@mourner if you just wanted a banana, would you buy the whole jungle?
