### ISSUE TITLE
Clarify sprite limits (addImage)

### ISSUE THREAD

**Issue by pathmapper** [mapbox/mapbox-gl-js#9879]
**mapbox-gl-js version**: v1.11.1

### Question

From the docs for [addImage](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#addimage):

> A Map.event:error event will be fired if there is not enough space in the sprite to add this image.

Could you please clarify "not enough space in the sprite"?

### Links to related documentation

- https://docs.mapbox.com/mapbox-gl-js/style-spec/sprite/

- https://docs.mapbox.com/help/glossary/sprite/

**Comment by mourner** [comment]
We should document this better, but basically this is bounded by WebGL `MAX_TEXTURE_SIZE`, which depends on the user's GPU. Most of the time it's at least 4096x4096, and many modern GPUs have 8192x8192 or 16384x16384. You can check yours through `map.painter.context.maxTextureSize`.

**Comment by pathmapper** [comment]
Thanks @mourner, `map.painter.context.maxTextureSize` worked (with `main`, https://github.com/mapbox/mapbox-gl-js/pull/9694 didn't make it into a release until now).

Is there a way to get the current sprite size to find out how much space is left until `maxTextureSize` is reached?

**Comment by pathmapper** [comment]
The use case is to add several images with `addImage` and make sure that it's working for most users, so 4096x4096 seems to be an appropriate sprite size.
