### ISSUE TITLE
The Equation between Pixel on map and meter

### ISSUE THREAD

**Issue by Aiamjay** [mapbox/mapbox-gl-js#9880]
**mapbox-gl-js version**:1.11.0

### Question
Could you please tell me the relationship between pixel on map and meter in real world? 
I need to accurately draw something on map. That's important for me. Please!

**Comment by arindam1993** [comment]
The code here 
https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/control/scale_control.js#L87

is a good place to start, the summary is :
1. Use `map.unproject` to comvert from pixel co-ordinates to lng,lat
2. Calculate distance from lng,lat using haversine distance
https://en.wikipedia.org/wiki/Haversine_formula
