### ISSUE TITLE
A highlight effect. SetData takes 2s for updating source with 6000 features.

### ISSUE THREAD

**Issue by DartWelder** [mapbox/mapbox-gl-js#9882]
Hi! I'm trying to implement a highlight effect by hover effect on the table's row. I've got the data table related to Mapbox's point features. I update the map point's styles by my rxjs state (every change in the state calls styles updating on my map). For small features count, it works well, but it takes 2 seconds for updating styles on the map with 6000 points. Directly setData execution takes 150-200 ms, but rendering takes 1-3 seconds. How can I improve the performance of the Mapbox for my task? As I wrote, I have 6000 points on the map, and when I hover the cursor over a row in the table I want to change the style for2 points. Change of style implemented by changing the feature's layer (might that be the matter?). 

Thanks for any ideas.

**mapbox-gl-js version**: 0.45.0 / 1.11.1

**Comment by mourner** [comment]
Don't use `setData` for highlighting — it reprocesses the whole data set every time. Use `feature-state` instead — see an example here https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/

**Comment by DartWelder** [comment]
@mourner, thank you!
