### ISSUE TITLE
Get error when doing "Yarn install"

### ISSUE THREAD

**Issue by ATerentjev** [mapbox/mapbox-gl-js#9890]
Dear Gurus!
  I am working with MapBox-gl some time. Previously, I successfully got a working environment.
But now I started getting an error when preparing development environment. My steps:
1. clone repository in mapbox-gl-js directory and go in it
2. npm i node-gyp 

I get next log:

`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm notice created a lockfile as package-lock.json. You should commit this file.
+ node-gyp@7.0.0
added 99 packages from 66 contributors and audited 101 packages in 12.116s
2 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
PS D:\mapbox\mapbox-gl-js
`
Then when I try  

3.   yarn install 

I get next log:

PS D:\mapbox\mapbox-gl-js> yarn install

yarn install v1.22.4
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by u
nsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[3/5] Fetching packages...
info fsevents@2.1.2: The platform "win32" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.12: The platform "win32" is incompatible with this module.
info "fsevents@1.2.12" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @mapbox/mapbox-gl-supported@1.5.0" has unmet peer dependency "mapbox-gl@>=0.32.1 <2.0.0".
warning " > @mapbox/mapbox-gl-rtl-text@0.2.3" has unmet peer dependency "mapbox-gl@>=0.32.1 <2.0.0".
[5/5] Building fresh packages...
[1/5] ⡀ canvas
[-/5] ⡀ waiting...
[3/5] ⡀ core-js-pure
[4/5] ⡀ gl
error D:\mapbox\mapbox-gl-js\node_modules\gl: Command failed.
Exit code: 7
Command: prebuild-install || node-gyp rebuild
Arguments:
Directory: D:\mapbox\mapbox-gl-js\node_modules\gl
Output:
prebuild-install WARN install No prebuilt binaries found (target=12.18.3 runtime=node arch=x64 libc= platform=win32)
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@12.18.3 | win32 | x64
gyp info spawn C:\Python27\python.exe
gyp info spawn args [
gyp info spawn args   'D:\\mapbox\\mapbox-gl-js\\node_modules\\gl\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\mapbox\\mapbox-gl-js\\node_modules\\gl\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\mapbox\\mapbox-gl-js\\node_modules\\gl\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\myadmin\\.node-gyp\\12.18.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\myadmin\\.node-gyp\\12.18.3',
gyp info spawn args   '-Dnode_gyp_dir=D:\\mapbox\\mapbox-gl-js\\node_modules\\gl\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\myadmin\\.node-gyp\\12.18.3\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\mapbox\\mapbox-gl-js\\node_modules\\gl',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\mapbox\\mapbox-gl-js\\node_modules\\gl\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack Error: spawn C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\15.0\Bin\MSBuild.exe ENOENT
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
gyp ERR! stack     at onErrorNT (internal/child_process.js:469:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\mapbox\\mapbox-gl-js\\node_modules\\gl\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\mapbox\mapbox-gl-js\node_modules\gl
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v4.0.0

PS D:\mapbox\mapbox-gl-js>
Can't anybody help what I am doing false ?

**Comment by mourner** [comment]
This is an issue with building https://github.com/stackgl/headless-gl on Windows / Node v12 — please report it there.
