### ISSUE TITLE
Filter expressions: Is it possible to filter polygons which contain a particular point?

### ISSUE THREAD

**Issue by atyshka** [mapbox/mapbox-gl-js#9891]
**mapbox-gl-js version**: 1.10

### Question
I have a layer containing geojson polygons, and I would like to filter it to polygons that contain a certain lat long point. I would like to devise a filter expression that accomplishes this. Looking through the reference of expressions, I see a "within" statement that returns true when a particular point is within a polygon. That is almost what I want, but its first argument is the point, and the second arg is the polygon to search. It is my understanding that when applying a filter to a layer, the item from the layer is going to be inserted at the beginning of the filter expression. This would not work for me then, as it would be trying to determine whether the polygon is within the point, which makes no sense. Is there any way I can manipulate the ordering of the filter expression, perhaps using variables, such that I can perform a query as to whether a particular point lies within a polygon for each polygon in a layer?

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#within

**Comment by ryanhamley** [comment]
There isn't a `contains` expression that's the opposite of `within`. A possible workaround might be to use [`queryRenderedFeatures`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#queryrenderedfeatures) (or `querySouceFeatures`) to find the features that intersect with a particular point and then use [`setFeatureState`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#setfeaturestate) to update the `fill-opacity` of your polygons, similar to the [hover effect example](https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/). If you need more guidance, I'd recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us).
