### ISSUE TITLE
is there any meterToPixelAtZoomAtLat function in the web version of Mapbox gl

### ISSUE THREAD

**Issue by Aiamjay** [mapbox/mapbox-gl-js#9893]
**mapbox-gl-js version**: 1.11.0

### Question
Is there any function in web version of Mapbox GL to transfer meter to pixels in Mapbox GL, like getMetersPerPixelAtLatitude in the android version of mapbox?
<img width="630" alt="Screen Shot 2020-07-23 at 6 00 23 PM" src="https://user-images.githubusercontent.com/13723721/88353102-1e9d8800-cd11-11ea-8d73-7c83a123dea6.png">

**Comment by andrewharvey** [comment]
No there isn't. It would depend on the zoom you're at. But you can check out https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/control/scale_control.js and https://docs.mapbox.com/mapbox-gl-js/api/geography/#mercatorcoordinate#meterinmercatorcoordinateunits using both approaches you should be able to calculate this.

**Comment by ryanhamley** [comment]
Historically, we've not included much in the way of geospatial analysis tools directly in the library. You may be able to use [Turf.js](https://turfjs.org/) for analysis though in addition to the approach that Andrew noted above.

**Comment by Aiamjay** [comment]
> No there isn't. It would depend on the zoom you're at. But you can check out https://github.com/mapbox/mapbox-gl-js/blob/main/src/ui/control/scale_control.js and https://docs.mapbox.com/mapbox-gl-js/api/geography/#mercatorcoordinate#meterinmercatorcoordinateunits using both approaches you should be able to calculate this.

HI Andrewharvey,
I have a problem related to your answer, pics below are from your documentation:
![Screen Shot 2020-11-02 at 4 42 43 PM](https://user-images.githubusercontent.com/13723721/97934448-9d4f8b80-1d2a-11eb-8971-2611bd890935.png)
![Screen Shot 2020-11-02 at 4 42 51 PM](https://user-images.githubusercontent.com/13723721/97934451-9fb1e580-1d2a-11eb-8857-934cfb4387a0.png)

my question is: given a latitude, how to calculate accurate meter/pixel? The doc only list some estimated meter/pixel in a given  range of latitude. How to calculate accurate one?

**Comment by Coldsewoo** [comment]
@whatoeat2night 
Here's what i'm using

```javascript
 const canvas = map.getCanvas()
 const width = canvas.clientWidth
 const height = canvas.clientHeight
 const lnglat = map.unproject(width/2, height/2) // or any point on the canvas
 const one_px_diff = map.unproject(width/2 + 1, height/2) // 1 px diff in x from point above
 const meter_per_pixel = lnglat.distance(one_px_diff)  // use this value
```

the value cannot be same for all map canvas since the latitudes are not the same between bottom and top points of the canvas, but the difference can be negligible if zoom level is large enough.
