### ISSUE TITLE
Generating raster tile instead of fetching from url

### ISSUE THREAD

**Issue by dkegle** [mapbox/mapbox-gl-js#9897]
I have spatial data which is too large to be displayed as a single raster overlay. Tiles need to be generated. However, it is not possible to generate them on the server. The data comes to client in a compressed private format.

LeafletJS has layer called GridLayer, which enables you to do this. Instead of giving url to fetch tiles, you can write your own function which takes tile parameters (x,y,z) as input, and returns generated tile as result (div, canvas or img). This is short example in the docs:
https://leafletjs.com/reference-1.6.0.html#gridlayer

As a real world example, this very powerful approach is used here:
https://www.windy.com/

Is there anything similar in Mapbox GL JS? How would one approach this problem? Is it even possible to do this?

**Comment by ryanhamley** [comment]
Hi @dkegle GL JS doesn't have a correlate to Leaflet's GridLayer. I think the way you'd want to to approach this is to generate your tiles client-side, then add the tiles as a raster source. There's a few older issues that reference similar ideas such as https://github.com/mapbox/mapbox-gl-js/issues/7390, https://github.com/mapbox/mapbox-gl-js/issues/5597 and https://github.com/mapbox/mapbox-gl-js/issues/9280. If you need further help getting this set up, I'd recommend contacting [Mapbox Support](https://support.mapbox.com/hc/en-us).

**Comment by douglasg14b** [comment]
@ryanbaumann I think the question is asking "How do I have mapbox call my local function with params x,y,z for tiles"

This is a need I also have. I need to generate tiles on the fly client-side, in addition to the normal map tiles retrieved on the server, in order to render a grid.

Can mapbox call a local function to retrieve map tiles on-demand for a layer?
