### ISSUE TITLE
Confusing error if a style doesn't have a matching source

### ISSUE THREAD

**Issue by SupremumLimit** [mapbox/mapbox-gl-js#990]
If I add a style but don't add a matching source immediately, I get this error in Safari: 

    TypeError: Attempted to assign to readonly property.

or this error in Chrome:

    Uncaught TypeError: Cannot set property 'used' of undefined

Here is a fiddle which demonstrates this: http://jsfiddle.net/7zfxue2g/

It would be nice if the error hinted at the actual problem (it took me hours to work this out) or even better, if I could set up styles independently from the sources.

**Comment by jfirebaugh** [comment]
The way that we would address this is by validating incoming styles, which is being discussed in #796. In the meantime, you can use [mapbox-gl-style-lint](https://github.com/mapbox/mapbox-gl-style-lint) to validate styles externally.

> set up styles independently from the sources

In general complete independence is unlikely -- we are likely to want to maintain the invariant that every layer must reference a valid source -- but we will probably have APIs to add and remove layers.
