### ISSUE TITLE
Fallback images are not working with manually added image

### ISSUE THREAD

**Issue by francois2metz** [mapbox/mapbox-gl-js#9900]
**mapbox-gl-js version**: 1.11.1

**browser**: Firefox, Chrome and I believe all others

### Steps to Trigger Behavior

 1. Load and add an image with `addImage` named `custom-marker`
 2. Load a geojson source (or any other source) with points
 3. Style the points with an icon-image with a fallback

```
'icon-image': ["coalesce",
  ['image', 'nonexistant'],
  ['image', 'custom-marker']
]
```

### Link to Demonstration

I updated the example "Draw GeoJSON points" to reproduce it https://docs.mapbox.com/mapbox-gl-js/example/geojson-markers/

https://jsfiddle.net/5ga36cnw/3/

### Expected Behavior

The Mapbox DC office should display the custom marker

### Actual Behavior

The Mapbox DC office don't display any marker

### Additional stuff

- If the loaded image is used in the first position, the marker image is displayed.
```
'icon-image': ["coalesce",
  ['image', 'custom-marker'],
  ['image', 'custom-marker']
]
```
- I believe I fixed the bug in the PR https://github.com/mapbox/mapbox-gl-js/pull/9838

**Comment by karimnaaji** [comment]
This will be available in 1.12, thanks for the contribution @francois2metz !
