### ISSUE TITLE
after setRenderWorldCopies  false. I am not able to set 100% width

### ISSUE THREAD

**Issue by Vgurnani** [mapbox/mapbox-gl-js#9902]
map = new mapboxgl.Map({
      container: mapContainer.current,
      style: 'mapbox://styles/mapbox/streets-v11',
      center: coordinates,
      zoom: zoom,
      attributionControl: false,
      maxZoom: 8,
      minZoom: 1
    })
    map.setRenderWorldCopies(false)

I am using this code and not able set 100% width

**Comment by ryanhamley** [comment]
`setRenderWorldCopies` won't interfere with the ability to set 100% width on the map. What I assume you're seeing is something like the screenshot below. The map and its container are still 100% width in the screenshot but only one tile is being rendered which includes the full world. In situations where the map/container are wider than the width of a single tile, we render copies of that single tile to fill out the sides. Setting `renderWorldCopies` to false disables that and you see whitespace instead. If you only want one copy of the world without white space, your map container would have to be the same size as the tile with a bounds applied to prevent panning into the white space. If you need further assistance, please contact [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks!

<img width="1440" alt="Screen Shot 2020-07-28 at 10 45 27 AM" src="https://user-images.githubusercontent.com/4523080/88701878-75171780-d0bf-11ea-8426-4e3fce599494.png">
