### ISSUE TITLE
How to add source with Deck GL layer on Mapbox gl js?

### ISSUE THREAD

**Issue by John2397** [mapbox/mapbox-gl-js#9904]
I have a Scatter Layer from deck gl and I would like to add data to that layer every X ms.
But how can I show the updated data on the map?
This is the declaration of the layer:

```
const myDeckLayer = new MapboxLayer({
    id: 'my-scatterplot',
    type: ScatterplotLayer,
    data: [
        {position: [100.434,30.3344, 10], size: 3}
        
    ],
    getPosition: d => d.position,
    getRadius: d => d.size,
    getColor: [255, 0, 0]
});

//then push data every X ms and update the map every time
```

If the above was a mapbox layer, I could call the following every time I want to update the map:
`map.getSource('sourceID').setData(jsonObject)`

But how could I do that using the Deck gl layer?

**Comment by ryanhamley** [comment]
Hi @John2397 we don't maintain Deck.GL so you'd need to refer to their documentation. I'm not very familiar with the API but it looks like you may need to do something [like this](https://deck.gl/docs/developer-guide/performance#handle-incremental-data-loading).

**Comment by John2397** [comment]
For anyone wondering, here is the answer https://github.com/visgl/deck.gl/issues/4834
