### ISSUE TITLE
Geocoder in 2 steps (2 pages)

### ISSUE THREAD

**Issue by alexv86** [mapbox/mapbox-gl-js#9907]
Hello,

I did a lot of digging into the documentation and I couldn’t find any information on this particular case.

I want to implement mapbox in 'two parts ' on my site:

1. On the homepage.
I have the geocoder search box where I fill in an address. I was able to find out how to use the geocode without a map here (https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-geocoder-no-map/)

2. Once we validate the place in the geocoder box, we are redirected to another page of the website containing the map and which is positioned on the place chosen in step 1.

I do not see how to make the link, local storage? Ideas or practical cases?

Thanks !!

**Comment by ryanhamley** [comment]
Hi @alexv86 this is going to be entirely dependent on the structure of your app so we can't really give guidance here. Local storage could work. If you have something like a React app, you could store the location in the app's state. If you need general assistance in setting this up, you can contact [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks.
