### ISSUE TITLE
Updating from 1.8.1 positions "markers" below the canvas element

### ISSUE THREAD

**Issue by vitaliyhayda** [mapbox/mapbox-gl-js#9908]
I've updated from 1.8.1 to 1.11.1 (also tried 1.9.0) and it positions "markers" below the canvas element

To fix, I had to add following CSS:

    .mapboxgl-marker {
        top: 0;
    }

Not yet sure why, but I've isolated this issue to the Mapbox version

**Comment by ryanhamley** [comment]
Hi @vitaliyhayda when reporting an issue, it's very helpful to fill out the template that is provided. At a minimum, we need a working example that shows this problem (you can use JSBin, JSFiddle or CodePen). It would also be helpful to know what browser you're using. Our main [marker example](https://docs.mapbox.com/mapbox-gl-js/example/add-a-marker/) does not show this issue so we need more information.
