### ISSUE TITLE
Token always invalid on static website 

### ISSUE THREAD

**Issue by SelaO** [mapbox/mapbox-gl-js#9910]
We have a static website hosted on S3, let's say its address is http://blah-blah.s3-website.eu-central-1.amazonaws.com.

I need to restrict my token only for this URL, but even though I tried any of the following combinations it still doesn't work (getting not authorized):

http://blah-blah.s3-website.eu-central-1.amazonaws.com
https://blah-blah.s3-website.eu-central-1.amazonaws.com
blah-blah.s3-website.eu-central-1.amazonaws.com

But when I add: amazonaws.com, it works. 
So any chance you could help with getting this to work with our specific S3 URL? 

Just to be clear the URL is correct of course and we navigate to our site from that URL, and of course, blah-blah is just for the example.

**Comment by mourner** [comment]
Can you please contact support@mapbox.com about this? GL JS repo itself doesn't control how referrer filtering works — that happens on the backend.
