### ISSUE TITLE
feature Id Alphanumeric

### ISSUE THREAD

**Issue by hmendezm** [mapbox/mapbox-gl-js#9918]
**mapbox-gl-js version**: 1.10.0

### Question

I have feature Ids that are alphanumeric and other numeric. The numeric Ids are kept as is but the alphanumeric ids are set undefined. Is it a way to set the addSource method to accept Alphanumeric values in feature.id?

I try promoted by it is return always undefined for all features.

Note: this happens in mousemove events  and querySourceFeatures

best
Hmendez

**Comment by mourner** [comment]
Currently there's no way to support this because the Vector Tile specification only allows integers as feature `id` — you would have to store alphanumeric id as a feature property for it to work with `promoteId`. Closing as a duplicate of #2716.
