### ISSUE TITLE
Idle event not firing in headless browser

### ISSUE THREAD

**Issue by weswitt** [mapbox/mapbox-gl-js#9920]
I'm trying to get a map rendered using headless chrome via puppeteer.  I'm very close but have one remaining problem. I was having the problem of tiles not rendering but I found issue 7721 saying that "preserveDrawingBuffer: true" is required. I added that map option and now the tiles are rendered. The remaining problem is that in headless mode it seems that the "idle" event is not fired. I uses the idle event to synchronize the nodejs script so it knows when the map is fully rendered. This code works fine with an interactive browser. The issue is not specific to chromium as it also repros with the full google-chrome browser. Is this a known problem? Is there an alternate method for knowing when the map has finished rendering?

`(async() => {
console.log("test starting");
const puppeteer = require('puppeteer');
const browser = await puppeteer.launch({headless: true,userDataDir: "data"});
const page = (await browser.pages())[0];
await page.goto('file:///map.html');
await page.waitForFunction('document.querySelector("#sync").textContent.includes("sync")');
await page.setViewport({ width: 800, height: 480 });
await page.screenshot({path: 'map.png'});
await browser.close();
})();

<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8' />
    <title></title>
    <meta name="viewport" content="initial-scale=1,maximum-scale=1,user-scalable=no" />
    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.js'></script>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css' rel='stylesheet' />
    <style>
        body { margin:0; padding:0; }
        #map { position:absolute; top:0; bottom:0; width:800px; height:480px; }
    </style>
</head>
<body>
<div id='map'></div>
<div id='sync'></div>
<script>
const outputContainer = document.getElementById('sync');
mapboxgl.accessToken = '**token**';
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mapbox/streets-v9',
    center: [-122.3351,47.6080],
    zoom: 7,
    preserveDrawingBuffer: true
});
map.once('idle', (e) => {
    outputContainer.innerHTML += `sync<br>`;
});
</script>
</body>
</html>
`

**Comment by weswitt** [comment]
OK after further debugging I discovered that using map.once for catching the idle event won't work in headless. I changed this to map.on and it does work. The map tiles are rendered as expected. The one difference is performance. Rendering in an interactive browser takes maybe 5 seconds, but in headless is takes about 30 seconds at least. This is not ideal but at least the map is rendered and I can live with it. Is there anything I can do to improve the headless performance?

**Comment by mourner** [comment]
This might be a race condition in the way you set up waiting for the result (e.g. `idle` firing earlier than the wait function establishes), not an issue with GL JS directly. We also haven't noticed any performance issue when using the headless mode. You can find an example of how we set up Puppeteer for internal benchmarks here: https://github.com/mapbox/mapbox-gl-js/blob/main/bench/gl-stats.js
