### ISSUE TITLE
Enable pinch-to-zoom, disable scroll zooming

### ISSUE THREAD

**Issue by AndrejGajdos** [mapbox/mapbox-gl-js#9921]
**mapbox-gl-js version**: 1.10.1

### Question

Mapbox GL provides option `scrollZoom` to enable/disable zooming on scroll and pinch-to-zoom events. Is it possible to allow zooming on pinch-to-zoom and disable scrolling on scroll event?

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/api/map/#map#scrollzoom

**Comment by sgolbabaei** [comment]
Thank you @AndrejGajdos for opening this ticket. There are multiple [user interaction handlers](https://docs.mapbox.com/mapbox-gl-js/api/handlers/) that can be used to modify ways in which the map responds to user input. 

[TouchZoomHandler](https://docs.mapbox.com/mapbox-gl-js/api/handlers/#touchzoomrotatehandler) and [scrollZoomHandler](https://docs.mapbox.com/mapbox-gl-js/api/handlers/#scrollzoomhandler) can set to enable or disable using the handlers. 
```
map.scrollZoom.disable();
map.touchZoomRotate.enable();
```

**Comment by AndrejGajdos** [comment]
I was referring pinch-to-zoom on a touchpad, not a touchscreen. TouchZoomHandler enables pinching on a touchscreen, not touchpad.

**Comment by Jonatan-r** [comment]
> @sgolbabaei I was referring pinch-to-zoom on a touchpad, not a touchscreen. TouchZoomHandler enables pinching on a touchscreen, not touchpad.

@sgolbabaei is right! This is not the same thing! Why was this closed?

**Comment by mhuconcern** [comment]
The TouchZoomHandler works on touch screen but not touch pad. Makes it hard to use android debugging tools
