### ISSUE TITLE
To highlight the poi label after geocoder results instead of creating maker.

### ISSUE THREAD

**Issue by ZownIt** [mapbox/mapbox-gl-js#9922]
Hi All,
Is it possible to highlight the specific poi_lable name component after geocoder result ? we also have issues in the getting the correct coordinates from the geocoder for the poi places? Any suggestions would be welcomed.

**Comment by sgolbabaei** [comment]
Thank you @ZownIt for opening this ticket. To help the maintainers and community understand and address the problem accurately can you please provide a minimal, complete, verifiable demonstration of the issue. We recommend using https://jsbin.com. Please include information about the browser version and operating system used.

**Comment by ZownIt** [comment]
Sorry about that adding more information. Hopefully, this gives a better picture.  I'm creating an application that displays restaurant details. so I used MapboxGeocoder to perform the search and create a marker out of the result.   Below is the code snippet.
const mapboxGeocoder = new MapboxGeocoder(mapboxGeocoderOptions);
 mapboxGeocoder.on('result', function(remapboxGeocodersults) {
        map.flyTo({
            center: remapboxGeocodersults.result.geometry.coordinates,
            zoom: 18,
        });
        const marker = {
            type: 'Feature',
            geometry: {
                type: 'Point',
                coordinates: [
                    remapboxGeocodersults.result.geometry.coordinates[0],
                    remapboxGeocodersults.result.geometry.coordinates[1],
                ],
            },
            properties: {
                description: remapboxGeocodersults.result.place_name.split(',')[0],
            },
        };
        .......

However, there were a good amount of restaurants whose marker is positioned away from the actual location. Maybe because of the incorrect coordinates. So the idea is to change the style of the restaurant name in the map instead of creating a maker, this will remove the marker floating around the wrong location.
My question is it possible to do such kind of styling or is there a way we can get more accurate coordinates. I could able to see using SetLayoutProperty for "POI_LABLE" we can change the styles of the name attribute. Is it possible to apply a filter here and change the style of the matched name?. Thanks for looking into this question.

**Comment by andrewharvey** [comment]
I'll close here as it's more of a support question and has now been posted at https://stackoverflow.com/questions/63333729/mapbox-gl-change-poi-label-name-style-using-geocoder-search-result
