### ISSUE TITLE
How to zoom in or out map view，the map view content(tile) don't change ?

### ISSUE THREAD

**Issue by KiNoHa** [mapbox/mapbox-gl-js#9924]
**mapbox-gl-js version**:

### Question
I want to zoom in or out the map view,but I don't want to change the map content.Maybe somewhere  I can set a zoom factor to multiply the map camera matrix.Please answer me! Thank you!!

**Comment by sgolbabaei** [comment]
Thank you for using mapbox-gl-js. For future "how do I" questions like this, please refer to our help documentation, and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
