### ISSUE TITLE
Custom icon for single label (restuarant)

### ISSUE THREAD

**Issue by caraneel** [mapbox/mapbox-gl-js#9925]
Hello,

I'm working with Mapbox to build a website where restaurant managers can search for their restaurants and then drop pins nearby. However, the generated location of the pin is offset (oftentimes by a lot) from the actual location of the restaurant. To address this, I was hoping to change the icon of the specified location (in this case, PizzaPlex) from the default fork-and-knife icon to the orange pin icon you can see to the left of it in the middle of the building, for more accuracy.

Is there a way to do this without affecting all the other restaurant icons? Or is there a way to improve the accuracy of the generated marker pin in the first place?

<img width="839" alt="Screen Shot 2020-08-11 at 12 56 20 PM" src="https://user-images.githubusercontent.com/15758690/89925892-10d17900-dbd2-11ea-83a6-759d98e5bcf3.png">

**Comment by sgolbabaei** [comment]
Thank you for using mapbox-gl-js. You can use Mapbox studio to replace the default source layer of POI data with your own, you can check [this blog post](https://blog.mapbox.com/creating-custom-poi-layers-in-studio-df46045503e1) for more information. For future "how do I" questions like this, please refer to our help documentation, and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
