### ISSUE TITLE
user location (geolocation) is not working on chrome.

### ISSUE THREAD

**Issue by niloofarsamimi1993** [mapbox/mapbox-gl-js#9927]
there is a problem with geolocation for me. mapbox  'Locate the user" page is not working on chrome.when i click on geolocation control it keeps turning and map doesn't show my location.it works with VPN.and it works in firefox, edge and internet explorer.
here is the link to this page:
"https://docs.mapbox.com/mapbox-gl-js/example/locate-user/"

and  this is what i see:
![mapbox](https://user-images.githubusercontent.com/59602797/90029882-a0f5e800-dcd0-11ea-9b61-a6a6f0219abb.PNG)

**Comment by mourner** [comment]
Does geolocation on any other page work in the same conditions? Are there any errors or warnings in the console?

**Comment by niloofarsamimi1993** [comment]
> Does geolocation on any other page work in the same conditions? Are there any errors or warnings in the console?
I uploaded my own file to my server and it has the same problem but it is not served over HTTPS.i don't know about other pages.and there is no error in the console.

**Comment by niloofarsamimi1993** [comment]
> Does geolocation on any other page work in the same conditions? Are there any errors or warnings in the console?

I uploaded my own file to my server and it has the same problem but it is not served over HTTPS.i don't know about other pages.and there is no error in the console

**Comment by mourner** [comment]
@niloofarsamimi1993 there is still not enough information to conclude that the issue is specific to GL JS. It seems to me like a problem in your network setup / browser.

**Comment by niloofarsamimi1993** [comment]
@mourner i checked it on different PCs connected to different networks and the same problem appeared.how else can i help?

**Comment by andrewharvey** [comment]
> @mourner i checked it on different PCs connected to different networks and the same problem appeared.how else can i help?

but do other sites on the same browser work with geolocation, you can test with https://browserleaks.com/geo? Seems more likely to be a browser issue.

**Comment by niloofarsamimi1993** [comment]
no.other sites doesn't work with geolocation.so it seems to be  a geolocation problerm not a mapbox problem.thank you very much.do you have any idea how can i investigate this problem?
