### ISSUE TITLE
want the text lable not hide automatically by change zoom level

### ISSUE THREAD

**Issue by DachengChen** [mapbox/mapbox-gl-js#9929]
Thanks to help

exsample:  https://jsfiddle.net/vgxbu8ys/38/

**mapbox-gl-js version**: 1.11.1

**browser**: all brower

### Steps to Trigger Behavior

 1. at the zoom level 22 you can see the geneated text label above the linestring
 2. if you zoom out , the text label is gone
 3. i have alreay try to change with all related properties, but still not work

### Link to Demonstration
https://jsfiddle.net/vgxbu8ys/38/

**Comment by sgolbabaei** [comment]
Thank you for using mapbox-gl-js. For future "how do I" questions like this, please refer to our [help documentation](https://docs.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to https://stackoverflow.com/questions/tagged/mapbox-gl-js to ask the community for help.
