### ISSUE TITLE
How to use get expression on another object other than the feature

### ISSUE THREAD

**Issue by jcardus** [mapbox/mapbox-gl-js#9932]
**mapbox-gl-js 1.12.0**:

### Question

I'm getting "invalid value at Object" or "Bare objects invalid. Use ["literal", {...}] instead." when trying to use the second argument of the get expression:

`["get", string, object]: value`

The documentation says 

> Retrieves a property value from the current feature's properties, **or from another object if a second argument is provided**

The documentation is not very clear on how to use the second argument and I can't find an example anywhere. 
Is it possible to use it on any object? 

[here's](https://jsfiddle.net/khyxLr5z/) an example not working.

### Links to related documentation

https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#get

**Comment by asheemmamoowala** [comment]
As described in the error message, you need to wrap the `object` in a literal expression as described [here](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#types-literal).

```
'text-field': ['get', 'text', ["literal", { text: "abc", text2: "abcd"}]]
```
