### ISSUE TITLE
Mapbox Style with Multi-condition query found error

### ISSUE THREAD

**Issue by FreeGIS** [mapbox/mapbox-gl-js#9934]
**mapbox-gl-js version**:v1.12.0

**browser**:google  84.0.4147.125

### Steps to Trigger Behavior

 1. The Style as follow:
`"filter": ['all',[">=", ["to-number",  ["get", "value"]],5],["==", "ybsk", 0]],`
the error was printed:
` layers.flowLayer.filter[1][1]: string expected, array found`
 2. when i used in single condition:
`
"filter": ['all',[">=", ["to-number",  ["get", "value"]],5]],  `
  or 
`"filter": ['all',["==", "ybsk", 0]],  `
the result is ok.
`
So i suspect there is a problem with the style caused by array parsing in mapbox gl API

**Comment by mourner** [comment]
Unfortunately we have no way of reproducing the issue without a live test case prompted in the issue template, so I'll have to close this.
