### ISSUE TITLE
.mapboxgl-canvas lost position:absolute

### ISSUE THREAD

**Issue by dragooncjw** [mapbox/mapbox-gl-js#9938]
**mapbox-gl-js version**: 1.11.1

### Question
I have found that in this version, dom in my mapbox which class name is `mapboxgl-canvas` lost default setup 'position: absolute;' and my markers shifted. I tried to define my own .mapboxgl-canvas in css. But I failed. I wonder if there is a solution or is this is a bug?

**Comment by mourner** [comment]
This is likely an issue on your end, unless you can provide a reproducible live test case — Mapbox GL JS CSS file didn't change in this regard:

https://github.com/mapbox/mapbox-gl-js/blob/45242e75447aeb3dc2b61ecf3cdfa622fc4c39bc/src/css/mapbox-gl.css#L8-L12

**Comment by dragooncjw** [comment]
Thanks for your reply. But I update my mapbox from `0.53.1` to `1.11.1` and then this question showed, maybe you can pay some attention. I've also found a solution. Thank you again for your patient answer.
