### ISSUE TITLE
Enable IPv6 support for Mapbox

### ISSUE THREAD

**Issue by ikomwrestling** [mapbox/mapbox-gl-js#9939]
## Motivation

Mapbox API doesn't support IPv6 thus the resources cannot be received via an IPv6 connection.

## Design

Since the API seems to use CloudFront, fixing this should be as easy as [enabling IPv6 on CloudFront distribution](https://aws.amazon.com/tw/blogs/aws/ipv6-support-update-cloudfront-waf-and-s3-transfer-acceleration/) and [creating an AAAA ALIAS record pointing to it](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-to-cloudfront-distribution.html#routing-to-cloudfront-distribution-config).

Thank you

**Comment by mourner** [comment]
This sounds like a great suggestion, but I'd contact support@mapbox.com about it. This repo is limited to issues with GL JS library specifically, so I'll have to close this.
