### ISSUE TITLE
Mapbox: "Mapbox: "Cannot get property 'map' of undefined'" while trying to use addImage

### ISSUE THREAD

**Issue by Gonza462** [mapbox/mapbox-gl-js#9947]
**mapbox-gl-js version**:

**browser**: Google chrome

### Steps to Trigger Behavior

 1. In React create class component.
 2. then create a map object
this.map = new mapboxgl.Map({
      container: "map", // html element id in render
      style: `mapbox://styles/${styleName}`,
      center: [lon, lat], // note lon comes before lat - geoJSON convention
      zoom: [zoomScale],
    });

 3. then spawn a map and try to add an icon as a point. But the icon is a picture that has to be rendered. I followed mapbox cat example.

this.map.on("load", (e) => {
      this.map.loadImage('https://upload.wikimedia.org/wikipedia/commons/7/7c/201408_cat.png',function(error,image) {
        if(error) throw error;
        this.map.addImage('cat',image);
      })

### Link to Demonstration
https://docs.mapbox.com/mapbox-gl-js/example/add-image/

https://jsbin.com/

### Expected Behavior
supposed to render icon of a cat.
### Actual Behavior
it throws an error
Mapbox: "Cannot get property 'map' of undefined' on the line where says 'this.map.addImage(...).
Without this line i can render symbols just fine but its only using the stock symbols that come with installed. for example right now im using this for my layer for symbols.

this.map.addLayer({
          id: "allStations",
          type: "symbol",
          source: "point-truck",
          layout: {
            "icon-image": "restaurant-15",
            "icon-size": 2.0,
          },
        });

how ever I want to render a custom image.

**Comment by mourner** [comment]
Please don't use this repo's GitHub issues to ask generic JavaScript questions — it's strictly for reporting issues with GL JS. Here's a page describing how `this` keyword works: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this
