### ISSUE TITLE
How does map.on('load') work?

### ISSUE THREAD

**Issue by yls00** [mapbox/mapbox-gl-js#9949]
**mapbox-gl-js version**: I am using react.

### Question
I have used the following function to load my choropleth layer and markers. 

```
map.on("load", function () {
    addChoroplethLayer(map, choropleth_data);
    addMarkers(map, marker_data);
});
```

However, sometimes the map and the style is correctly loaded but the layer(data) is not added to the map. 

![image](https://user-images.githubusercontent.com/37783082/90971929-758dad00-e4c9-11ea-96f4-229ef044b0f8.png)

So I added print statement in the map.on('load') function and found out that the print statement is not executed, which means that  map.on('load') is not executed. Therefore, I am wondering if there are any premises to call this function. But there is nothing about it in the documentation or shown in the example. So, my question is: how to use  map.on('load') correctly to load the layers?

**Comment by mourner** [comment]
@yus252 the map `load` event can only happen once.

**Comment by yus252** [comment]
I only called it once. It loads the data most of the time, but not always. Seems a little bit uncontrolled. What else can cause the map.on('load') not execute?

**Comment by mourner** [comment]
@yus252 you might be calling it once **after** the `load` event already fired.

**Comment by yus252** [comment]
How can I make sure the load even already fire? Aren't map.load('on' is the loading event?
