### ISSUE TITLE
fitBounds padding options

### ISSUE THREAD

**Issue by tmcw** [mapbox/mapbox-gl-js#995]
fitBounds [supports padding on all sides](https://www.mapbox.com/mapbox-gl-js/api/#new-mapboxgl-map-options--map-method-options) but it would be useful to support padding on specific edges, or provide a `[wsen]` array to support usecases like sidebar'ed maps.

**Comment by jfirebaugh** [comment]
#1025

**Comment by tristen** [comment]
Not sure how #1025 is related. +1 on supporting padding on specific edges.

**Comment by 1ec5** [comment]
Also tracked in #1339.
