### ISSUE TITLE
Filter by Counties for US

### ISSUE THREAD

**Issue by connorsoohoo** [mapbox/mapbox-gl-js#9950]
## Motivation

Want a search to filter by and report counties for a given location (i.e. for US).

- Search for a specific county in the US.
- Search for a location and return the county that it is a part of.

## Design

Currently in the search API, we have that Forward geocoding -> types allows to filter results to include only a subset of the available feature types. Current options are country, region, postcode, district, place, locality, neighborhood, address, and poi.

Would be natural to have `district` correspond to `county`, specifically for the US.

### Documentation

Change documentation here : https://docs.mapbox.com/api/search/
and here: https://docs.mapbox.com/api/search/#data-types

**Comment by ryanhamley** [comment]
This is the repo for Mapbox GL JS. We do not oversee the Search API. Your best bet will be to contact [Mapbox Support](https://support.mapbox.com/hc/en-us). Thanks!
