### ISSUE TITLE
'LineString' use vector mode to zoom in and out for maximum cracks

### ISSUE THREAD

**Issue by ohmyray** [mapbox/mapbox-gl-js#9953]
![image](https://user-images.githubusercontent.com/33082558/91247234-67b78080-e784-11ea-9fec-03ce13acf877.png)

**Comment by mourner** [comment]
There's not enough detail to tell for sure, but this usually happens when your vector tiles have no buffer. Add a buffer when generating your vector tiles, so that lines go a little past the extent. For example, GeoJSON layers use a buffer of 64 (in a 4096-extent tile) by default.
