### ISSUE TITLE
Recent changes messed up the railroad styles in IE11

### ISSUE THREAD

**Issue by fnicollet** [mapbox/mapbox-gl-js#996]
Hello,
Here is a screenshot of the same data with a build from 3 February in IE:
![image](https://cloud.githubusercontent.com/assets/1240481/6177487/8a8c88e2-b307-11e4-939c-5e050ba6c0fa.png)

and here is one that i just build (right after https://github.com/fnicollet/mapbox-gl-js/commit/e43c1d7ba77e71f592bf5d85c20206ee872f668c):

![image](https://cloud.githubusercontent.com/assets/1240481/6177451/516563cc-b307-11e4-987f-3f7a1f692a78.png)

As you can see, the kind of dashes on the railroad are now different

Fabien

**Comment by jfirebaugh** [comment]
Did you update the style for [line-dasharray changes](https://github.com/mapbox/mapbox-gl-style-spec/blob/mb-pages/CHANGELOG.md#700)?

**Comment by fnicollet** [comment]
ah i am still using v6 styles, that must be it, thanks!

**Comment by fnicollet** [comment]
Just tried with the v7 styles, it was the issue, thanks a lot !
