### ISSUE TITLE
How to do get value from custom geojson prop without properties for paint expression

### ISSUE THREAD

**Issue by gislayer** [mapbox/mapbox-gl-js#9965]
i have a sample geojson like
{
type:"feature",
style:{polygon:{"line-color":"#FF0000"}},
properties:{...},
geometry:{...}
}
This structer.

How can i use in paint expression this style.polygon["line-color] value?

i am working on thematic map and i have a sample geojson like that.

**Comment by mourner** [comment]
Unfortunately you can't — in expressions, you can only access flat properties inside the `properties` object, per GeoJSON specification. So you'd have to change the input GeoJSON to:

```js
{
  type: 'Feature',
  properties: {
    'polygon-line-color': '#FF0000'
  },
  geometry: ...
}
```
