### ISSUE TITLE
GeolocateControl User Position Dot out-of-center of Pulsing Blue Live-Circle

### ISSUE THREAD

**Issue by Squiji** [mapbox/mapbox-gl-js#9966]
For some reason I am getting a styling issue on the GeoLocateControl User Position
![gpsBug](https://user-images.githubusercontent.com/50003357/92336401-f9f93780-f054-11ea-9c0d-09bd7ddfd899.png)

I've tried commenting out everything in my css and it still will not center like the tutorial.

**Comment by ryanhamley** [comment]
It's impossible for us to say what's happening without a reproducible example. Are you including the mapbox-gl.css file in your site? I think it's unlikely that this is a bug in GL JS and is probably specific to something in your setup so I'd recommend contacting [Mapbox Support](http://support.mapbox.com/) if you need more help.

**Comment by Squiji** [comment]
Yes v 12

**Comment by andrewharvey** [comment]
Are you JS and CSS both from the same mapbox-gl-js release?

**Comment by Squiji** [comment]
> Are your JS and CSS both from the same mapbox-gl-js release?

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    	
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="theme-color" content="#000000">
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json">
    
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">  
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://api.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.css" type="text/css"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.0.0/mapbox-gl-geocoder.css" type="text/css" />
    
    <link href="mapbox-gl-controls/theme.css" rel="stylesheet">
    <title>XXXXXX</title>
  </head>
  <body>
    <noscript>
      You need to enable JavaScript to run this app.
    </noscript>
    <div id="root">
	<div id="app"></div>
    </div>
    
        
        <script src="/socket.io/socket.io.js"></script>
        
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
	<script src='https://api.tiles.mapbox.com/mapbox-gl-js/v1.12.0/mapbox-gl.js'></script>
	
	
	<script src="https://api.tiles.mapbox.com/mapbox.js/plugins/turf/v2.0.0/turf.min.js" charset="utf-8"></script>
	
	<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>   
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v4.5.1/mapbox-gl-geocoder.min.js"></script>
  </body>
</html>

**Comment by andrewharvey** [comment]
There are a bunch of other CSS libraries included here, you could try to identify which one might be causing a conflict by inspecting the element with developer tools and seeing which CSS files are affecting it.

**Comment by Squiji** [comment]
> There are a bunch of other CSS libraries included here, you could try to identify which one might be causing a conflict by inspecting the element with developer tools and seeing which CSS files are affecting it.

As far as I tried, inspecting the geolocator did not show up when right clicking it.. guess I need to expand out each div..Okay, will give it a shot.

**Comment by Squiji** [comment]
Well the canvas is at 400px and the geolocator is translating at 200px, 200px. 

<canvas class="mapboxgl-canvas" tabindex="0" aria-label="Map" width="400" height="400" style="width: 400px; height: 400px;"></canvas>
<div class="mapboxgl-user-location-accuracy-circle mapboxgl-marker mapboxgl-marker-anchor-center" style="transform: translate(-50%, -50%) translate(200px, 200px) rotateX(0deg) rotateZ(0deg);"></div>
<div class="mapboxgl-user-location-dot mapboxgl-marker mapboxgl-marker-anchor-center" style="transform: translate(-50%, -50%) translate(200px, 200px) rotateX(0deg) rotateZ(0deg);"></div>

Looks like everything is default. I do not have any custom CSS defined for those classes.

Guess Ill start commenting out each stylesheet and see what happens.

**Comment by Squiji** [comment]
> There are a bunch of other CSS libraries included here, you could try to identify which one might be causing a conflict by inspecting the element with developer tools and seeing which CSS files are affecting it.

Well at least one is affecting the accuracy circle: 
.center, .center-align {
    text-align: center;
}
Inherited from a parent div. I would have thought these map controls would only have inherited css from the mapcontainer.

**Comment by Squiji** [comment]
> There are a bunch of other CSS libraries included here, you could try to identify which one might be causing a conflict by inspecting the element with developer tools and seeing which CSS files are affecting it.

https://imgur.com/a/lvAx6Fj
(Here is the before and after disabling the parent div text align. Overriding the text align in the accuracy circle element style does not change the text align, not even with !important.) Please advise.

**Comment by andrewharvey** [comment]
If you have a minimally reproducing example I might be able to take a look.
