### ISSUE TITLE
What is the reason behind division by EXTENT while calculating the position matrix in transform.js?

### ISSUE THREAD

**Issue by DushyantChetiwal** [mapbox/mapbox-gl-js#9970]
**mapbox-gl-js version**: 1.12.0

### Question
This is the part of code I am referring to. It says in the code that EXTENT is the maximum value of the internal tile coordinate system but I don't understand what that means.
`    const posMatrix = mat4.identity(new Float64Array(16));`
`    mat4.translate(posMatrix, posMatrix, [unwrappedX * scale, canonical.y * scale, 0]);`
`    mat4.scale(posMatrix, posMatrix, [scale / EXTENT, scale / EXTENT, 1]);`
`    mat4.multiply(posMatrix, aligned ? this.alignedProjMatrix : this.projMatrix, posMatrix);`

**Comment by mourner** [comment]
Vector tiles can have a different extent (it's encoded in each layer), but in the shaders, we normalize all coordinates to the 8192 extent. Reasons are explained there:

https://github.com/mapbox/mapbox-gl-js/blob/f2117b4ef501bbab298898e4f6c34083178d519a/src/data/extent.js#L3-L13

Please avoiding using GitHub issues in this repo to ask questions — its purpose is to file bug reports and feature requests.
