### ISSUE TITLE
Different zoo, map.querySourceFeatures(), it will return different feature

### ISSUE THREAD

**Issue by Yuki-Zhao** [mapbox/mapbox-gl-js#9971]
when the zoom of map is 1, map.querySourceFeatures(sourceId, {sourceLayer: 'testLayer'}), it will return 3 features. but when the zoom is 10. map.querySourceFeatures(sourceId, {sourceLayer: 'testLayer'}), it will return 6 features. why?

**Comment by ryanhamley** [comment]
>The domain of the query includes all currently-loaded vector tiles and GeoJSON source tiles: this function does not check tiles outside the currently visible viewport.

You can see that [the documentation for `querySourceFeatures`](https://docs.mapbox.com/mapbox-gl-js/api/map/#map#querysourcefeatures) notes that the query occurs within the current vector tiles and geojson sources, so this behavior would be expected.
