### ISSUE TITLE
Passing a Variable to setHtml 

### ISSUE THREAD

**Issue by boldfish1121** [mapbox/mapbox-gl-js#9973]
I've been reading the docs.

Is it possible to pass a variable to setHtml? I'm trying to pass in a prop from my React component called this.props.formatForPopover but it is always undefined

```
map.on('click', 'test-layer', function (e) {
    var coordinates = e.features[0].geometry.coordinates.slice();
    while (Math.abs(e.lngLat.lng - coordinates[0]) > 180) {
    coordinates[0] += e.lngLat.lng > coordinates[0] ? 360 : -360;
    }

    var description = this.props.formatForPopover

    new mapboxgl.Popup()
      .setLngLat(coordinates)
      .setHTML(description)
      .addTo(map);
    });
```

**Comment by ryanhamley** [comment]
`setHTML` takes a string. It can be a variable. You'll have to debug your application. I assume that `this.props.formatForPopover` is undefined; perhaps you have a typo or aren't correctly setting the prop.

**Comment by boldfish1121** [comment]
can setHtml take a function?

**Comment by ryanhamley** [comment]
No, the argument passed to `setHTML` has to be a string. If you have a function that returns a string, you could do something like this `setHTML(myFunction())` which should work fine, but `setHTML(myFunction)` wouldn't because `setHTML` won't call the function.
