### ISSUE TITLE
Map.on with combine keys/mouse events

### ISSUE THREAD

**Issue by hmendezm** [mapbox/mapbox-gl-js#9976]
**mapbox-gl-js version**: 1.12.0

### Question

I am using a map.on with mouse events but I need to have map.on with ctrl+click. Users can be able to select a layer in the map by pressing the control key and press click in the mouse.

best 
hmendezm

**Comment by mourner** [comment]
You have access to the original click event with `e.originalEvent`. Then you can check its properties, e.g. `e.originalEvent. ctrlKey` for whether control was pressed during the click.

**Comment by hmendezm** [comment]
Thank you, mourner
