### ISSUE TITLE
Fill images are cropped

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/mapbox-gl-js#998]
It looks like fill images are being cropped:

![fill-image-truncated](https://cloud.githubusercontent.com/assets/5607844/6195599/c65fa3d6-b39d-11e4-9412-021c1f8781c9.png)

And

![screen shot 2015-02-13 at 4 31 50 pm](https://cloud.githubusercontent.com/assets/5607844/6195611/dfa7a348-b39d-11e4-80ae-77264ef334ab.png)

The first example uses a image file that is 16 x 8px, the second uses one that is 64 x 64px.

/cc @ansis

**Comment by ansis** [comment]
How are these sprites being created?
Can you push the sprites and styles somewhere?

**Comment by nickidlugash** [comment]
@ansis the first style is [the latest Bright](https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/styles/bright-v7.json). I'm pretty certain that the sprite was created with the [`build-sprite` script](https://github.com/mapbox/mapbox-gl-js/blob/master/bin/build-sprite.js).

**Comment by nickidlugash** [comment]
@ansis [Latest Bright](https://github.com/mapbox/mapbox-gl-styles/blob/mb-pages/styles/bright-v7.json) now looks like this, with visible gaps between the image tiling:

![screen shot 2015-02-18 at 12 37 28 am](https://cloud.githubusercontent.com/assets/5607844/6232485/3a908b8c-b707-11e4-9714-0f7e11623c75.png)

Is there anything I should do to optimize this on the image-file creation side?

**Comment by nickidlugash** [comment]
^ That was a retina screenshot. I currently don't have access to a non-retina screen.

**Comment by ansis** [comment]
It looks right on retina and non-retina for me. I'm guessing this was a mapbox-gl-js and style version mismatch. If you see it again, reopen
