### ISSUE TITLE
Polygon render error

### ISSUE THREAD

**Issue by jaapster** [mapbox/mapbox-gl-js#9981]
Hi,

The issue that I'm seeing is that complex polygons with holes are rendered incorrectly.
The holes are filled at certain zoom levels.

I seems that the simplification that happens before rendering sometimes results in invalid geometries.

Example where holes are filled
![Screenshot 2020-09-16 at 10 37 30](https://user-images.githubusercontent.com/1597572/93313453-c793cb00-f808-11ea-9bed-7bbf624b547b.png)

Example after zooming in and holes are rendered correctly
![Screenshot 2020-09-16 at 10 37 45](https://user-images.githubusercontent.com/1597572/93313541-e4c89980-f808-11ea-9289-710e21962ffa.png)

**mapbox-gl-js version**: 1.12.0

**browser**: Chrome

### Steps to Trigger Behavior

 1. Add a geojson source containing a complex geometry (included in example)
 2. Zoom in and out

### Link to Demonstration

As the example is too large for jsbin, I have attached a zip containing the example.
Unzip and open the included HTML file in a browser.

[example.zip](https://github.com/mapbox/mapbox-gl-js/files/5230932/example.zip)

### Expected Behavior

The holes in the polygons never get filled

### Actual Behavior

The holes in the polygons do get filled at certain zoom levels

**Comment by mourner** [comment]
This looks like yet another case of #7023 — let's keep the discussion there.
