### ISSUE TITLE
How to add / remove control buttons dynamically on mapbox draw

### ISSUE THREAD

**Issue by John2397** [mapbox/mapbox-gl-js#9983]
Sorry for asking in the wrong section  but the repo here https://github.com/mapbox/mapbox-gl-draw doesn't seem to be active.

I'd like to know how to add or remove the control draw buttons dynamically, e.g when user clicks a button make the `line_string ` control button to appear.

This is how a `draw` object is declared:
```
var draw = new MapboxDraw({
    displayControlsDefault: false,
    controls: {
        polygon: true,
        boxSelect: true,
        trash: true
    }
});
```

So how can I change the `controls` later on?

I've tried 
```
draw.controls =  {
        line_string: true,
        polygon: false
    }
```
but it doesn't work

**Comment by sgolbabaei** [comment]
Thank you for using mapbox-gl-js. For future "how do I" questions like this, please refer to our [help documentation](https://docs.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to [https://stackoverflow.com/questions/tagged/mapbox-gl-js](https://stackoverflow.com/questions/tagged/mapbox-gl-js) to ask the community for help.
