### ISSUE TITLE
Using object settings in case expression

### ISSUE THREAD

**Issue by stepanchvatik** [mapbox/mapbox-gl-js#9984]
Hello, I am trying to change base vector source (openmaptiles) properties, render_height of building to be exact.
I need to hide specific extruded buildings, which I replaced with GLTF models. I added this specification in 3D layer:

`		"fill-extrusion-height": ["case",
						       ["boolean", ["feature-state", "hidden"], true],
						        0,
							["literal",	{
						                "property": "render_height",
								"type": "identity"
							}
                                                        ]`
and later in code I have this:
	map.setFeatureState(
		{ source: 'openmaptiles', sourceLayer: "building",id: 416 }, <-- specific building, some buildings have same ID, but that is not problem
		{ hidden:true }				
	);
**mapbox-gl-js version**: 1.11.1

### Question
The question is - how can I include that property+type array in layer specification in case expression? Like usually it's like [case, cond, val1, val2], but I need val2 to be array of properties.

**Comment by sgolbabaei** [comment]
Thank you for using mapbox-gl-js. For future "how do I" questions like this, please refer to our [help documentation](https://docs.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to [https://stackoverflow.com/questions/tagged/mapbox-gl-js](https://stackoverflow.com/questions/tagged/mapbox-gl-js) to ask the community for help.
