### ISSUE TITLE
Layer Layout properties ignore floating zoom numbers while interpolating

### ISSUE THREAD

**Issue by onlymate** [mapbox/mapbox-gl-js#9986]
Hey everyone, 
I got a strange behaviour while playing around with the **interpolate** expression.
It seems like that every property in "Layout" of a layer ignores floating numbers while interpolating with the zoom level. 
Properties in the "Paint" section of layer work like charme. 

I've tried to achieve that the icon will rotate at zoom _17.1_ and will change his opacity at zoom _17.1_
Actually the icon is rotating at zoom _18_, not _17.1_

I've tried also other properties for "Layout" and "Paint". It seems to me that only all "Layout" properties are affected. Not the properties in "Paint".

I know this use case will work with the **step** expression. This is just a minimalistic setup where I was playing around with **interpolate** and discovered this bug. 

You will find a demo on the bottom of this issue, just zoom in and while you move your mouse over the map the zoom level on the top of the screen will be updated. 

**mapbox-gl-js version**: 1.12.0

**browser**: Safari, Firefox, Chrome

### Layout and Paint property
`
'layout': {
              'icon-image': 'cat',
              'icon-rotate': [
                "interpolate",
                ["exponential", 2],
                ["zoom"],
                0, 0,
                17, 0,
                17.1, 90,
                22, 90
              ],
              'icon-size': 1
            }
`

`
            'paint': {
              'icon-opacity': [
                "interpolate",
                ["exponential", 2],
                ["zoom"],
                0, 1,
                17, 1,
                17.1, 0.5,
                22, 0.5
              ]
            }
`

### Example Video
![demo](https://user-images.githubusercontent.com/25883227/93454024-ae5b4f00-f8da-11ea-9b79-bfed86020ae5.gif)

### Expected Behavior
Icon will rotate and change his opacity at zoom _17.1_

### Actual Behavior
Icon is changing his opacity at zoom _17.1_
Icon is rotating at zoom level _18_, **not** _17.1_

### Link to Demonstration

https://jsfiddle.net/0v2s5xhg/

**Comment by sgolbabaei** [comment]
Thank you for using mapbox-gl-js. Layout properties are only evaluated at integer zoom levels.
