### ISSUE TITLE
update data on a style source

### ISSUE THREAD

**Issue by sirmmo** [mapbox/mapbox-gl-js#9990]
**mapbox-gl-js version**: 1.12.0

### Question

I am implementing a time based mvt service with data from different time periods and the possibility to navigate through that data. Based on the year the tile server sends an mvt of that specific timeframe and a coherent styling gives the visualization. I would need to be able to update the data (invalidate and reload) in the viewport without resetting the style considering the changing date and not only the changing coordinates.

Thanks

### Links to related documentation

https://map.openhistorymap.org/866/4/43.67/1.57

**Comment by sgolbabaei** [comment]
Thank you for using mapbox-gl-js. For future "how do I" questions like this, please refer to our [help documentation](https://docs.mapbox.com/help/), and if you can't find the answer there, [contact support](https://www.mapbox.com/contact/). This issue tracker is for reporting bugs and feature requests.

You might also consider posting your question to [https://stackoverflow.com/questions/tagged/mapbox-gl-js](https://stackoverflow.com/questions/tagged/mapbox-gl-js) to ask the community for help.
