### ISSUE TITLE
Add rotation to source

### ISSUE THREAD

**Issue by yuanyuan-xy** [mapbox/mapbox-gl-js#9992]
## Design Alternatives
When a source thousands or even tens of thousands of image data, I want to give so much data to add their own rotation Angle, but only to be unified in the layer set Angle setting, but so so much the picture is the same point of view, is there any way can be set separately, or add a few a few pictures layer, but so many layer is added in the map seems to is not a suitable solution

**Comment by karimnaaji** [comment]
Hello @yuanyuan-xy , do you mind giving some more information in the other sections of the issue template? There's a lot of missing bits about your use case as well as the actual issue you are facing. If I understand correctly you are trying to display a lot of images on the map, is that correct? What is the most simple example you could provide on what you are trying to achieve?
