### ISSUE TITLE
Is icon-opacity in symbol layers compatible with feature-state?

### ISSUE THREAD

**Issue by migvel** [mapbox/mapbox-gl-js#9993]
Hello,

From the documentation:
https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#paint-symbol-icon-opacity

I see that icon-opacity supports feature-state in symbol layers, but when I use it as for example(in paint):
` 'icon-opacity':  ['case', ['boolean',['feature-state','hover'],false],1,0.3]`

icons just takes the initial opacity and there is no change on hover.

Is this a bug? Or the documentation is wrong? or my use of it?

Thanks and regards.

**Comment by karimnaaji** [comment]
Your usage seems to be right. At first look this seems to be a bug, do you have a full example to post on jsfiddle to confirm the behavior?

**Comment by migvel** [comment]
Sorry I checked out, and I can confirm that my usage was incorrect. The feature-state for that case works as expected.

Thanks.
