### ISSUE TITLE
How to fix strange texture and jittering

### ISSUE THREAD

**Issue by Narrenschlag** [mapbox/mapbox-gl-js#9996]
Hello together. My issue can be seen in the title.
Here a picture. Left is the problem, right is how it is supposed to look like.

![image](https://user-images.githubusercontent.com/71547522/93854789-a58dc300-fcb6-11ea-8cf2-02418f94757e.png)

Greetings, Max 👍

**Comment by karimnaaji** [comment]
hey @Narrenschlag , this is [z fighting](https://en.wikipedia.org/wiki/Z-fighting), but what engine is that? Can you replicate this issue using this library in an example?

**Comment by karimnaaji** [comment]
Closing due to lack of details, feel free to reopen with more information!
